-- Object: TABLE citrus_usr.HOLM_MAK
-- Server: 10.253.78.167 | DB: DMAT
--------------------------------------------------

CREATE TABLE [citrus_usr].[HOLM_MAK]
(
    [HOLM_ID] NUMERIC(10, 0) NOT NULL,
    [HOLM_EXCM_ID] NUMERIC(10, 0) NOT NULL,
    [HOLM_DT] DATETIME NOT NULL,
    [HOLM_DESC] VARCHAR(200) NULL,
    [HOLM_CREATED_BY] VARCHAR(25) NOT NULL,
    [HOLM_CREATED_DT] DATETIME NOT NULL,
    [HOLM_LST_UPD_BY] VARCHAR(25) NOT NULL,
    [HOLM_LST_UPD_DT] DATETIME NOT NULL,
    [HOLM_DELETED_IND] NUMERIC(10, 0) NOT NULL
);

GO
