-- Object: TABLE citrus_usr.SCREEN_COMPONENT
-- Server: 10.253.78.167 | DB: DMAT
--------------------------------------------------

CREATE TABLE [citrus_usr].[SCREEN_COMPONENT]
(
    [SCRC_SCR_ID] NUMERIC(10, 0) NOT NULL,
    [SCRC_COMP_ID] NUMERIC(10, 0) NOT NULL,
    [SCRC_COMP_CD] VARCHAR(20) NULL,
    [SCRC_COMP_NAME] VARCHAR(50) NULL,
    [SCRC_COMP_DESC] VARCHAR(200) NULL,
    [SCRC_COMP_TYPE] VARCHAR(50) NULL,
    [SCRC_TAB_ID] NUMERIC(10, 0) NULL,
    [SCRC_TAB_NAME] VARCHAR(50) NULL,
    [SCRC_CREATED_BY] VARCHAR(25) NOT NULL,
    [SCRC_CREATED_DT] DATETIME NOT NULL,
    [SCRC_LST_UPD_BY] VARCHAR(25) NOT NULL,
    [SCRC_LST_UPD_DT] DATETIME NOT NULL,
    [SCRC_DELETED_IND] SMALLINT NOT NULL
);

GO
