-- Object: PROCEDURE citrus_usr.CLASS_AUTO_PROCESS_PRM
-- Server: 10.253.78.167 | DB: DMAT
--------------------------------------------------

    
    
Create PROCEDURE [citrus_usr].[CLASS_AUTO_PROCESS_PRM]          
(          
 @FOR VARCHAR(2),    
 @USERID VARCHAR(25),    
 @PROCESSON VARCHAR(10),    
 @EXCHANGE_SEG VARCHAR(25)          
)          
AS          
--exec msajag.dbo.CLASS_AUTO_PROCESS_PRM @FOR='1',@PROCESSON='ALL',@USERID='YatinN'    
BEGIN          
 DECLARE @PROCESSTYPE VARCHAR(MAX),    
 @EDIT_ON VARCHAR(MAX)    
 IF @FOR='1'          
  BEGIN          
   IF @PROCESSON='ALL'    
    BEGIN    
   SELECT DISTINCT PROCESS_TYPE FROM TBL_AUTO_PROCESS_MASTER     
    END    
    ELSE    
    BEGIN    
   --SELECT @PROCESSTYPE  =  PROCESS_TYPE FROM TBL_AUTO_PROCESS_CONTROL_MASTER WHERE USERID=@USERID    
   --AND EXCH_SEGMENT = @EXCHANGE_SEG    
       
   --CREATE TABLE #DATA (FDATA VARCHAR(MAX))      
   --INSERT INTO #DATA       
   --SELECT * FROM dbo.fnSplitString2Tbl(@PROCESSTYPE,'~')     
       
   SELECT DISTINCT PROCESS_TYPE FROM TBL_AUTO_PROCESS_MASTER --WHERE PROCESS_TYPE IN(SELECT FDATA FROM #DATA WHERE FDATA<>'')    
    END         
  END          
 IF @FOR='2'          
  BEGIN          
   SELECT DISTINCT PROCESS_FOR FROM TBL_AUTO_PROCESS_MASTER          
  END          
 IF @FOR='3'          
  BEGIN          
   IF @PROCESSON='ALL'    
    BEGIN    
     SELECT DISTINCT  'DP' As exchange , 'CDSL' as segment,    
     SERVERNAME = ''      
--     FROM MULTICOMPANY ORDER BY 2,1 DESC          
    END    
   ELSE    
    BEGIN    
    -- SELECT DISTINCT  UPPER(LTRIM(RTRIM(EXCHANGE))) , UPPER(LTRIM(RTRIM(SEGMENT))),    
    -- (CASE WHEN PRIMARYSERVER = 1    
    --THEN 'PRIMARY-' ELSE 'DELIVERY-' END) + UPPER(LTRIM(RTRIM(EXCHANGE))) +'-'+ UPPER(LTRIM(RTRIM(SEGMENT)))     
    --AS SEGMENT,SERVERNAME = SHARESERVER+ '.' + SHAREDB + '.dbo.'      
    -- FROM MULTICOMPANY A,TBL_AUTO_PROCESS_CONTROL_MASTER B    
    -- WHERE A.EXCHANGE = LTRIM(RTRIM(.dbo.PIECE(B.EXCH_SEGMENT, '-', 2)))    
    -- AND A.SEGMENT = LTRIM(RTRIM(.dbo.PIECE(B.EXCH_SEGMENT, '-', 3)))    
    -- AND (CASE WHEN PRIMARYSERVER = 1    
    --THEN 'PRIMARY' ELSE 'DELIVERY' END) = LTRIM(RTRIM(.dbo.PIECE(B.EXCH_SEGMENT, '-', 1)))    
    -- AND B.USERID=@USERID    
    --  ORDER BY 2,1 DESC      
     SELECT DISTINCT  'DP' As exchange , 'CDSL' as segment,    
     SERVERNAME = ''         
    END    
  END    
      
  IF @FOR='4'          
  BEGIN          
      
  --SELECT @EDIT_ON  =  EDIT_ON FROM TBL_AUTO_PROCESS_CONTROL_MASTER     
  --WHERE USERID=@USERID AND EXCH_SEGMENT = @EXCHANGE_SEG    
      
  --CREATE TABLE #EDITDATA (FDATA VARCHAR(MAX))      
  --INSERT INTO #EDITDATA       
  --SELECT * FROM dbo.fnSplitString2Tbl(@EDIT_ON,'~')     
       
  SELECT SELECTEDTEXT=UPPER(SELECTEDTEXT),TEXTVAL=UPPER(TEXTVAL) FROM TBL_AUTO_EDIT_ON_MASTER    
  --WHERE SELECTEDTEXT IN(SELECT FDATA FROM #EDITDATA WHERE FDATA<>'')  ORDER BY SRNO       
    
      
  END       
      
  IF @FOR='5'          
  BEGIN      
  SELECT SELECTEDTEXT=UPPER(SELECTEDTEXT),TEXTVAL=UPPER(TEXTVAL) FROM TBL_AUTO_EDIT_ON_MASTER  ORDER BY SRNO       
  END      
      
  IF @FOR='6'          
  BEGIN      
  SELECT @PROCESSTYPE  =  PROCESS_TYPE FROM TBL_AUTO_PROCESS_CONTROL_MASTER WHERE USERID=@USERID    
  AND EXCH_SEGMENT = @EXCHANGE_SEG    
       
  CREATE TABLE #PROCESSDATA (FDATA VARCHAR(MAX))      
  INSERT INTO #PROCESSDATA       
  SELECT * FROM dbo.fnSplitString2Tbl(@PROCESSTYPE,'~')        
      
  SELECT DISTINCT PROCESS_TYPE=A.PROCESS_TYPE,BLOCK=ISNULL(B.BLOCK,'0'),    
  BLOCKON=(CASE WHEN CONVERT(VARCHAR, ISNULL(BLOCKON,''), 103)='01/01/1900' THEN '' ELSE CONVERT(VARCHAR, BLOCKON, 103) END)    
  FROM TBL_AUTO_PROCESS_MASTER A    
  FULL OUTER JOIN TBL_AUTO_PROCESS_BLOCK_DET B    
  ON A.PROCESS_TYPE=B.PROCESS_TYPE       
  WHERE A.PROCESS_TYPE IN(SELECT FDATA FROM #PROCESSDATA WHERE FDATA<>'')    
  END          
      
       
    
END

GO
