-- Object: PROCEDURE citrus_usr.Pr_rpt_bill_profile_filter_Shilpa_fordata
-- Server: 10.253.78.167 | DB: DMAT
--------------------------------------------------


--PR_RPT_BILL_PROFILE_FILTER 	'CDSL',3,'JAN 26 2009','JUN 26 2009','N','N','1234567890123456','','','N','Y','',1,'HO|*~|',''	

CREATE  PROC [citrus_usr].[Pr_rpt_bill_profile_filter_Shilpa_fordata]              
@PA_DPTYPE VARCHAR(4),                      
@PA_EXCSMID INT,                      
@PA_FROMDATE DATETIME,                      
@PA_TODATE DATETIME,                      
@PA_BULK_PRINTFLAG CHAR(1), --Y/N
@PA_STOPBILLCLIENTS_FLAG CHAR(1), --Y/N 
@PA_FROMACCID VARCHAR(16),                      
@PA_TOACCID VARCHAR(16),  
@PA_GROUP_CD VARCHAR(10),     
@PA_TRANSCLIENTSONLY CHAR(1),
@PA_HLDG_YN CHAR(1),
@PA_PROFILE VARCHAR(100),
@PA_LOGIN_PR_ENTM_ID NUMERIC,                        
@PA_LOGIN_ENTM_CD_CHAIN  VARCHAR(8000),                        
@PA_OUTPUT VARCHAR(8000) OUTPUT
AS                      
BEGIN  

---return 0                    
--              SELECT * FROM TEMPTABLEABCD14JULLY2014
--select * from BILL_ANGEL_18082015_new  ORDER BY DPAM_ACCTNO,DPAM_SBA_NAME,CASE WHEN ORDER_BY='2' THEN '0' ELSE ORDER_BY END
-- ,ISIN_NAME,CONVERT(DATETIME,TRANS_DATE),DPM_TRANS_NO 
--RETURN

--set @PA_TOACCID= @PA_FROMACCID

--if @PA_TODATE < 'APR 01 2017'
if @PA_TODATE <= 'Mar 31 2019'
begin 






declare @p15 varchar(1)
set @p15=NULL
exec Pr_rpt_bill_profile_filter_shilpa_arch @pa_dptype,@pa_excsmid,@pa_fromdate,
@pa_todate,@pa_bulk_printflag,@pa_stopbillclients_flag,
@pa_fromaccid,@pa_toaccid,@pa_group_cd,@pa_transclientsonly,@pa_Hldg_Yn,
@pa_profile,@pa_login_pr_entm_id,@pa_login_entm_cd_chain,@pa_output=@p15 output


return 

end 




              
SET NOCOUNT ON             
SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED   
 DECLARE @@DPMID INT,  
 @@L_CHILD_ENTM_ID NUMERIC,
 @@LEDGERID INT,
 @@BILLDUEDATE VARCHAR(11),
 @@SSQL VARCHAR(8000),
 @@REPORTNAME VARCHAR(10),
 @PA_PREVFROMDATE DATETIME ,
 @@L_GRPMSTR_CD CHAR(1)
  ,@@BBOCODE VARCHAR(10)
 SET @@BBOCODE = ''
 
 
-- SELECT DISTINCT  ACCP_CLISBA_ID 
--INTO #ECN FROM ACCOUNT_PROPERTIES 
--WHERE ACCP_ACCPM_PROP_CD = 'ECN_FLAG' 
--AND ACCP_VALUE NOT IN ('','//') AND ACCP_VALUE='YES'


        

SET @@L_GRPMSTR_CD =  ISNULL(CITRUS_USR.FN_SPLITVAL(@PA_GROUP_CD,2),'')  
SET @PA_GROUP_CD =  ISNULL(CITRUS_USR.FN_SPLITVAL(@PA_GROUP_CD,1),'')  
          
 SELECT @@DPMID = DPM_ID FROM DP_MSTR WITH(NOLOCK) WHERE DEFAULT_DP = @PA_EXCSMID AND DPM_DELETED_IND =1                      
 SELECT @@L_CHILD_ENTM_ID    =  CITRUS_USR.FN_GET_CHILD(@PA_LOGIN_PR_ENTM_ID , @PA_LOGIN_ENTM_CD_CHAIN)
 SELECT @@LEDGERID =FIN_ID FROM FINANCIAL_YR_MSTR WHERE FIN_DPM_ID = @@DPMID AND  (@PA_FROMDATE BETWEEN FIN_START_DT AND FIN_END_DT) AND FIN_DELETED_IND = 1
 SELECT @@BILLDUEDATE = CONVERT(VARCHAR(11),BILLC_DUE_DATE,109) FROM BILL_CYCLE WHERE BILLC_DPM_ID = @@DPMID AND BILLC_FROM_DT = CONVERT(VARCHAR(11),@PA_FROMDATE,109) AND BILLC_TO_DT = CONVERT(VARCHAR(11),@PA_TODATE,109)  

 SET @@BBOCODE = ISNULL(CITRUS_USR.FN_SPLITVAL(@PA_PROFILE,2),'') 
 SET @PA_PROFILE = ISNULL(CITRUS_USR.FN_SPLITVAL(@PA_PROFILE,1),'')  


IF @PA_PROFILE ='0'
SET @PA_PROFILE = ''
 
                       
 IF @PA_FROMACCID = ''                      
 BEGIN                      
  SET @PA_FROMACCID = '0'                      
  SET @PA_TOACCID = '99999999999999999'                      
 END                      
 IF @PA_TOACCID = ''                      
 BEGIN                  
   SET @PA_TOACCID = @PA_FROMACCID                      
 END                      

IF @@BBOCODE <> ''
BEGIN
SELECT ACCP_VALUE BBO , DPAM_SBA_NO CLIENTID 
INTO #BBOCODE FROM ACCOUNT_PROPERTIES , DP_ACCT_MSTR  
WHERE ACCP_ACCPM_PROP_CD='BBO_CODE'
AND ACCP_CLISBA_ID = DPAM_ID 
AND ACCP_VALUE = @@BBOCODE

IF @@BBOCODE <> ''
SELECT @PA_FROMACCID = MIN(CLIENTID ) FROM #BBOCODE 

IF @@BBOCODE <> ''
SELECT @PA_TOACCID = MAX(CLIENTID ) FROM #BBOCODE 

 CREATE CLUSTERED INDEX IX_1 ON #BBOCODE(CLIENTID,BBO)  

END    

CREATE TABLE #LEDGERBAL (
DPAM_ID BIGINT,
PREV_BILL_BAL NUMERIC(18,2)
)

  CREATE TABLE #ACLIST(DPAM_ID BIGINT,DPAM_SBA_NO VARCHAR(16),DPAM_SBA_NAME VARCHAR(150),EFF_FROM DATETIME,EFF_TO DATETIME)
  IF @PA_STOPBILLCLIENTS_FLAG = 'Y'
  BEGIN
    IF @PA_PROFILE <> ''
    BEGIN 
		
		IF @@BBOCODE <> ''
		INSERT INTO #ACLIST SELECT DPAM_ID,DPAM_SBA_NO,DPAM_SBA_NAME,EFF_FROM,ISNULL(EFF_TO ,'DEC 31 2900')
		FROM CITRUS_USR.fn_acct_list_bytushar (@@DPMID ,@PA_LOGIN_PR_ENTM_ID,@@L_CHILD_ENTM_ID,@PA_FROMACCID,@PA_TOACCID) , CLIENT_DP_BRKG 
		WHERE DPAM_STAM_CD <> '02_BILLSTOP'	
        AND   DPAM_ID = CLIDB_DPAM_ID 
        AND   CLIDB_EFF_TO_DT >= 'DEC 31 2099' 
        AND   CLIDB_BROM_ID = @PA_PROFILE
        AND   CLIDB_DELETED_IND = 1
        AND EXISTS(SELECT CLIENTID,BBO FROM #BBOCODE WHERE CLIENTID = DPAM_SBA_NO AND BBO = CASE WHEN @@BBOCODE <> '' THEN @@BBOCODE ELSE BBO END )

		IF @@BBOCODE = ''
		INSERT INTO #ACLIST SELECT DPAM_ID,DPAM_SBA_NO,DPAM_SBA_NAME,EFF_FROM,ISNULL(EFF_TO ,'DEC 31 2900')
		FROM  CITRUS_USR.fn_acct_list_bytushar (@@DPMID ,@PA_LOGIN_PR_ENTM_ID,@@L_CHILD_ENTM_ID,@PA_FROMACCID,@PA_TOACCID)  , CLIENT_DP_BRKG 
		WHERE DPAM_STAM_CD <> '02_BILLSTOP'	
        AND   DPAM_ID = CLIDB_DPAM_ID 
        AND   CLIDB_EFF_TO_DT >= 'DEC 31 2099' 
        AND   CLIDB_BROM_ID = @PA_PROFILE
        AND   CLIDB_DELETED_IND = 1
        --AND EXISTS(SELECT CLIENTID,BBO FROM #BBOCODE WHERE CLIENTID = DPAM_SBA_NO AND BBO = CASE WHEN @@BBOCODE <> '' THEN @@BBOCODE ELSE BBO END )
    END 
    ELSE 
    BEGIN
		IF @@BBOCODE <> ''
    	INSERT INTO #ACLIST SELECT DPAM_ID,DPAM_SBA_NO,DPAM_SBA_NAME,EFF_FROM,ISNULL(EFF_TO  ,'DEC 31 2900')
		FROM CITRUS_USR.fn_acct_list_bytushar (@@DPMID ,@PA_LOGIN_PR_ENTM_ID,@@L_CHILD_ENTM_ID,@PA_FROMACCID,@PA_TOACCID) 
		WHERE DPAM_STAM_CD <> '02_BILLSTOP'	
        AND EXISTS(SELECT CLIENTID,BBO FROM #BBOCODE WHERE CLIENTID = DPAM_SBA_NO AND BBO = CASE WHEN @@BBOCODE <> '' THEN @@BBOCODE ELSE BBO END )	

		IF @@BBOCODE = ''
    	INSERT INTO #ACLIST SELECT DPAM_ID,DPAM_SBA_NO,DPAM_SBA_NAME,EFF_FROM,ISNULL(EFF_TO  ,'DEC 31 2900')
		FROM CITRUS_USR.fn_acct_list_bytushar (@@DPMID ,@PA_LOGIN_PR_ENTM_ID,@@L_CHILD_ENTM_ID,@PA_FROMACCID,@PA_TOACCID) 
		WHERE DPAM_STAM_CD <> '02_BILLSTOP'	
       -- AND EXISTS(SELECT CLIENTID,BBO FROM #BBOCODE WHERE CLIENTID = DPAM_SBA_NO AND BBO = CASE WHEN @@BBOCODE <> '' THEN @@BBOCODE ELSE BBO END )	
    END  
  END 
  ELSE
  BEGIN
    IF @PA_PROFILE <> ''
    BEGIN 
		IF @@BBOCODE <> ''
		INSERT INTO #ACLIST SELECT DPAM_ID,DPAM_SBA_NO,DPAM_SBA_NAME,EFF_FROM,ISNULL(EFF_TO  ,'DEC 31 2900')
		FROM CITRUS_USR.fn_acct_list_bytushar (@@DPMID ,@PA_LOGIN_PR_ENTM_ID,@@L_CHILD_ENTM_ID,@PA_FROMACCID,@PA_TOACCID) 	 , CLIENT_DP_BRKG 	
        WHERE   DPAM_ID = CLIDB_DPAM_ID 
        AND   CLIDB_EFF_TO_DT >= 'DEC 31 2099' 
        AND   CLIDB_BROM_ID = @PA_PROFILE
        AND   CLIDB_DELETED_IND = 1
        AND EXISTS(SELECT CLIENTID,BBO FROM #BBOCODE WHERE CLIENTID = DPAM_SBA_NO AND BBO = CASE WHEN @@BBOCODE <> '' THEN @@BBOCODE ELSE BBO END )

		IF @@BBOCODE = ''
		INSERT INTO #ACLIST SELECT DPAM_ID,DPAM_SBA_NO,DPAM_SBA_NAME,EFF_FROM,ISNULL(EFF_TO  ,'DEC 31 2900')
		FROM CITRUS_USR.fn_acct_list_bytushar (@@DPMID ,@PA_LOGIN_PR_ENTM_ID,@@L_CHILD_ENTM_ID,@PA_FROMACCID,@PA_TOACCID) 	 , CLIENT_DP_BRKG 	
        WHERE   DPAM_ID = CLIDB_DPAM_ID 
        AND   CLIDB_EFF_TO_DT >= 'DEC 31 2099' 
        AND   CLIDB_BROM_ID = @PA_PROFILE
        AND   CLIDB_DELETED_IND = 1
        --AND EXISTS(SELECT CLIENTID,BBO FROM #BBOCODE WHERE CLIENTID = DPAM_SBA_NO AND BBO = CASE WHEN @@BBOCODE <> '' THEN @@BBOCODE ELSE BBO END )

    END
    ELSE 
    BEGIN
		IF @@BBOCODE <> ''
    	INSERT INTO #ACLIST SELECT DPAM_ID,DPAM_SBA_NO,DPAM_SBA_NAME,EFF_FROM,ISNULL(EFF_TO ,'DEC 31 2900')
		FROM CITRUS_USR.fn_acct_list_bytushar (@@DPMID ,@PA_LOGIN_PR_ENTM_ID,@@L_CHILD_ENTM_ID,@PA_FROMACCID,@PA_TOACCID) 
        WHERE EXISTS(SELECT CLIENTID,BBO FROM #BBOCODE WHERE CLIENTID = DPAM_SBA_NO AND BBO = CASE WHEN @@BBOCODE <> '' THEN @@BBOCODE ELSE BBO END )

		IF @@BBOCODE = ''
    	INSERT INTO #ACLIST SELECT DPAM_ID,DPAM_SBA_NO,DPAM_SBA_NAME,EFF_FROM,ISNULL(EFF_TO ,'DEC 31 2900')
		FROM CITRUS_USR.fn_acct_list_bytushar (@@DPMID ,@PA_LOGIN_PR_ENTM_ID,@@L_CHILD_ENTM_ID,@PA_FROMACCID,@PA_TOACCID) 
       -- WHERE EXISTS(SELECT CLIENTID,BBO FROM #BBOCODE WHERE CLIENTID = DPAM_SBA_NO AND BBO = CASE WHEN @@BBOCODE <> '' THEN @@BBOCODE ELSE BBO END )

    END  
  
  END 
  
  
   
  --delete a from #ACLIST a where not exists (select 1 from #ECN where ACCP_CLISBA_ID = DPAM_ID )
  
  
  
--SELECT * FROM #ACLIST WHERE DPAM_SBA_NO = '1201090000004621'

 IF @PA_BULK_PRINTFLAG = 'Y'
 BEGIN
		DELETE A FROM #ACLIST A,BLK_CLIENT_PRINT_DTLS 
		WHERE DPAM_ID = BLCKPD_DPAM_ID AND BLKCPD_DPMID = @@DPMID
		AND BLKCPD_RPTNAME = 'BILL'

		--DELETE A FROM #ACLIST A,AngelOwnAccount 
		--WHERE DPAM_SBA_NO = CLIENT_CODE --AND BLKCPD_DPMID = @@DPMID
		--AND BLKCPD_RPTNAME = 'BILL'
		
		--SELECT * FROM AngelOwnAccount 
 END
 
 --IF @pa_transclientsonly ='Y' OR @pa_transclientsonly = 'N'
 --BEGIN 
 
	--		DELETE A FROM #ACLIST A,AngelOwnAccount 
	--		WHERE DPAM_SBA_NO = CLIENT_CODE --AND BLKCPD_DPMID = @@DPMID
		
 --END 
 

CREATE TABLE #TMPHLDG 
(
	[DPHMCD_DPM_ID] [NUMERIC](18, 0) NOT NULL,
	[DPHMCD_DPAM_ID] [NUMERIC](10, 0) NOT NULL,
	[DPHMCD_ISIN] [VARCHAR](20) NOT NULL,
	[DPHMCD_CURR_QTY] [NUMERIC](18, 3) NULL,
	[DPHMCD_FREE_QTY] [NUMERIC](18, 3) NULL,
	[DPHMCD_FREEZE_QTY] [NUMERIC](18, 3) NULL,
	[DPHMCD_PLEDGE_QTY] [NUMERIC](18, 3) NULL,
	[DPHMCD_DEMAT_PND_VER_QTY] [NUMERIC](18, 3) NULL,
	[DPHMCD_REMAT_PND_CONF_QTY] [NUMERIC](18, 3) NULL,
	[DPHMCD_DEMAT_PND_CONF_QTY] [NUMERIC](18, 3) NULL,
	[DPHMCD_SAFE_KEEPING_QTY] [NUMERIC](18, 3) NULL,
	[DPHMCD_LOCKIN_QTY] [NUMERIC](18, 3) NULL,
	[DPHMCD_ELIMINATION_QTY] [NUMERIC](18, 3) NULL,
	[DPHMCD_EARMARK_QTY] [NUMERIC](18, 3) NULL,
	[DPHMCD_AVAIL_LEND_QTY] [NUMERIC](18, 3) NULL,
	[DPHMCD_LEND_QTY] [NUMERIC](18, 3) NULL,
	[DPHMCD_BORROW_QTY] [NUMERIC](18, 3) NULL,
	[DPHMCD_HOLDING_DT] DATETIME
	)  


CREATE INDEX IX_1_HLDG ON #TMPHLDG([DPHMCD_DPM_ID],[DPHMCD_DPAM_ID],[DPHMCD_ISIN],[DPHMCD_HOLDING_DT])

IF @PA_HLDG_YN ='Y'
BEGIN 
	INSERT INTO #TMPHLDG
	EXEC  [pr_get_holding_fix_latest]   @@DPMID,@PA_FROMDATE,@PA_TODATE,@PA_FROMACCID,@PA_TOACCID,''

END 



CREATE TABLE #VW_FETHOB(V_CDSHM_DPM_ID NUMERIC 
			, V_CDSHM_DPAM_ID NUMERIC,V_CDSHM_ISIN VARCHAR(20),V_CDSHM_OPN_BAL NUMERIC(18,3)
--			,V_CDSHM_TRANS_NO VARCHAR(150)
)

CREATE INDEX IC_OB ON #VW_FETHOB(V_CDSHM_DPM_ID,V_CDSHM_DPAM_ID,V_CDSHM_ISIN)

  INSERT INTO #VW_FETHOB
  EXEC PR_GET_OB_FIX @@DPMID,@PA_FROMDATE,@PA_TODATE,@PA_FROMACCID,@PA_TOACCID,''


SELECT * ,CITRUS_USR.FN_SPLITVAL_BY(CDSHM_TRANS_CDAS_CODE,16,'~') EXEDT
,CITRUS_USR.FN_SPLITVAL_BY(CDSHM_TRANS_CDAS_CODE,9,'~') EXETIME INTO #TMP_CDSL_HOLDING_DTLS FROM CDSL_HOLDING_DTLS
WHERE CDSHM_TRAS_DT >=@PA_FROMDATE AND CDSHM_TRAS_DT <=@PA_TODATE  
AND CDSHM_BEN_ACCT_NO BETWEEN @PA_FROMACCID AND @PA_TOACCID

   
                    
                
 IF (@PA_DPTYPE = 'CDSL')                      
 BEGIN                
	 
	SELECT @PA_PREVFROMDATE = MAX(DPHMCD_HOLDING_DT) FROM DP_DAILY_HLDG_CDSL WITH(NOLOCK) WHERE DPHMCD_HOLDING_DT <= CONVERT(VARCHAR(11),@PA_TODATE,109)
	CREATE TABLE #TEMPMAINCDSL              
	(          
	DPAM_ID BIGINT,            
	DPAM_SBA_NAME VARCHAR(200),          
	DPAM_ACCTNO VARCHAR(16),            
	TRANS_DESC VARCHAR(200),              
	DPM_TRANS_NO VARCHAR(10),              
	TRANS_DATE DATETIME,              
	ISIN_CD VARCHAR(12),              
	OPENING_BAL NUMERIC(19,3),          
	QTY NUMERIC(19,3),          
	ORDER_BY INTEGER,  
	LINE_NO BIGINT,          
	CHARGE_VAL NUMERIC(19,2)  , SETTM_ID VARCHAR(25),  TR_SETTM_ID VARCHAR(25) , TRATM_CD VARCHAR(25) 
    ,EXEDT DATETIME  ,C_D_FLAG CHAR(1) 
	)      

           
           
   IF @PA_GROUP_CD <> ''      
   BEGIN            
    INSERT INTO #TEMPMAINCDSL(DPAM_ID,DPAM_SBA_NAME,DPAM_ACCTNO,TRANS_DESC,DPM_TRANS_NO,TRANS_DATE,ISIN_CD,OPENING_BAL,QTY,ORDER_BY,LINE_NO,CHARGE_VAL,SETTM_ID,TR_SETTM_ID,TRATM_CD,EXEDT,C_D_FLAG)           
    SELECT DISTINCT CDSHM_DPAM_ID,          
    DPAM_SBA_NAME,          
    CDSHM_BEN_ACCT_NO,                      
    CDSHM_TRATM_DESC=REPLACE(CDSHM_TRATM_DESC,'        ',''),              
    CDSHM_TRANS_NO,                      
    CDSHM_TRAS_DT,                      
    CDSHM_ISIN,                      
    ISNULL(V_CDSHM_OPN_BAL,0),            
    CDSHM_QTY,          
    1,  
    CDSHM_ID,                    
    CDSHM_CHARGE   ,   CDSHM_SETT_NO ,  RIGHT(ISNULL(CDSHM_TRG_SETTM_NO,'') ,7)  , CDSHM_TRATM_CD    
,CONVERT(DATETIME, CASE WHEN EXEDT <> '' THEN SUBSTRING(EXEDT,5,4)+'-'
+SUBSTRING(EXEDT,3,2)
+'-'+SUBSTRING(EXEDT,1,2)
+ ' ' + 
REPLACE(
SUBSTRING(EXEDT,9,2)
+':'+SUBSTRING(EXEDT,11,2)+':'+SUBSTRING(EXETIME,13,2)
, '00:00:00', '00:00:00') ELSE 
SUBSTRING(EXETIME,5,4)+'-'
+SUBSTRING(EXETIME,3,2)
+'-'+SUBSTRING(EXETIME,1,2)
+ ' ' + 
REPLACE(
SUBSTRING(EXETIME,9,2)
+':'+SUBSTRING(EXETIME,11,2)+':'+SUBSTRING(EXETIME,13,2)
, '00:00:00', '00:00:00') END )
    ,CASE WHEN CDSHM_QTY > 0 THEN 'C' ELSE 'D' END         
    FROM #TMP_CDSL_HOLDING_DTLS WITH(NOLOCK)
 LEFT OUTER JOIN  #VW_FETHOB   ON V_CDSHM_DPAM_ID = CDSHM_DPAM_ID 
      AND V_CDSHM_ISIN = CDSHM_ISIN               
	   AND V_CDSHM_DPM_ID = CDSHM_DPM_ID   
    ,ACCOUNT_GROUP_MAPPING G WITH(NOLOCK)               
    ,#ACLIST ACCOUNT                            
    WHERE   CDSHM_DPM_ID = @@DPMID            
    AND CDSHM_TRAS_DT >=@PA_FROMDATE AND CDSHM_TRAS_DT <=@PA_TODATE                      
    AND (CDSHM_TRATM_CD IN('2246','2277','2201','3102','2270','2220','2262','2251','2202','2205','2280','2255','2215') OR ISNULL(CDSHM_CHARGE,0) <> 0)          
    AND CONVERT(NUMERIC,CDSHM_BEN_ACCT_NO) BETWEEN CONVERT(NUMERIC,@PA_FROMACCID) AND CONVERT(NUMERIC,@PA_TOACCID)   
    AND G.DPAM_ID = CDSHM_DPAM_ID      
    AND GROUP_CD =  @PA_GROUP_CD       
    AND CDSHM_DPAM_ID = ACCOUNT.DPAM_ID              
    AND (CDSHM_TRAS_DT BETWEEN EFF_FROM AND EFF_TO)  

 END  
 ELSE  
 BEGIN  
    INSERT INTO #TEMPMAINCDSL(DPAM_ID,DPAM_SBA_NAME,DPAM_ACCTNO,TRANS_DESC,DPM_TRANS_NO,TRANS_DATE,ISIN_CD,OPENING_BAL,QTY,ORDER_BY,LINE_NO,CHARGE_VAL,SETTM_ID, TR_SETTM_ID,TRATM_CD,EXEDT,C_D_FLAG)           
    SELECT DISTINCT CDSHM_DPAM_ID,          
    DPAM_SBA_NAME,          
    CDSHM_BEN_ACCT_NO,                      
    CDSHM_TRATM_DESC=REPLACE(CDSHM_TRATM_DESC,'        ',''),              
    CDSHM_TRANS_NO,             
    CDSHM_TRAS_DT,                      
    CDSHM_ISIN,                      
    ISNULL(V_CDSHM_OPN_BAL,0),            
    CDSHM_QTY,          
    1,  
    CDSHM_ID,                       
    CDSHM_CHARGE     ,   CDSHM_SETT_NO ,  RIGHT(ISNULL(CDSHM_TRG_SETTM_NO,'') ,7) ,CDSHM_TRATM_CD    
,CONVERT(DATETIME, CASE WHEN EXEDT <> '' THEN SUBSTRING(EXEDT,5,4)+'-'
+SUBSTRING(EXEDT,3,2)
+'-'+SUBSTRING(EXEDT,1,2)
+ ' ' + 
REPLACE(
SUBSTRING(EXEDT,9,2)+':'+SUBSTRING(EXEDT,11,2)+':'+SUBSTRING(EXETIME,13,2), '00:00:00', '00:00:00') ELSE 
SUBSTRING(EXETIME,5,4)+'-'+SUBSTRING(EXETIME,3,2)+'-'+SUBSTRING(EXETIME,1,2)+ ' ' + 
REPLACE(
SUBSTRING(EXETIME,9,2)+':'+SUBSTRING(EXETIME,11,2)+':'+SUBSTRING(EXETIME,13,2), '00:00:00', '00:00:00') END )

,CASE WHEN CDSHM_QTY > 0 THEN 'C' ELSE 'D' END                    
    FROM #TMP_CDSL_HOLDING_DTLS WITH(NOLOCK) LEFT OUTER JOIN  #VW_FETHOB   ON V_CDSHM_DPAM_ID = CDSHM_DPAM_ID 
      AND V_CDSHM_ISIN = CDSHM_ISIN          
	  AND V_CDSHM_DPM_ID = CDSHM_DPM_ID ,          
    #ACLIST ACCOUNT                            
    WHERE   CDSHM_DPM_ID = @@DPMID            
    AND CDSHM_TRAS_DT >=@PA_FROMDATE AND CDSHM_TRAS_DT <=@PA_TODATE                      
    AND (CDSHM_TRATM_CD IN('2246','2277','2201','3102','2270','2220','2262','2251','2202','2205','2280','2255','2215') OR ISNULL(CDSHM_CHARGE,0) <> 0)          
    AND CONVERT(NUMERIC,CDSHM_BEN_ACCT_NO) BETWEEN CONVERT(NUMERIC,@PA_FROMACCID) AND CONVERT(NUMERIC,@PA_TOACCID)                                               
    AND CDSHM_DPAM_ID = ACCOUNT.DPAM_ID              
    AND (CDSHM_TRAS_DT BETWEEN EFF_FROM AND EFF_TO)  
  
 END          
 
 
--logic to delete extra records of 2215 on May 15 2021
delete from   #tempmaincdsl    
where      
tratm_cd in ('2215')    
and  exists     
(select CDSHM_BEN_ACCT_NO , CDSHM_TRANS_NO, CDSHM_ISIN, CDSHM_QTY     
from #tmp_cdsl_holding_dtls where CDSHM_BEN_ACCT_NO = dpam_acctno    
and CDSHM_TRANS_NO = dpm_trans_no and isin_cd =CDSHM_ISIN and qty =  CDSHM_QTY    
and cdshm_tratm_cd in('2215') 
and CDSHM_CDAS_TRAS_TYPE<>'4' and 	CDSHM_CDAS_SUB_TRAS_TYPE <> '409' 
)     
--logic to delete extra records of 2215 on May 15 2021
          
   IF @PA_HLDG_YN         = 'Y'
   BEGIN 
	   IF @PA_TRANSCLIENTSONLY <> 'Y'    
	   BEGIN     
	  IF @PA_GROUP_CD <> ''      
	  BEGIN   
		 INSERT INTO #TEMPMAINCDSL(DPAM_ID,DPAM_SBA_NAME,DPAM_ACCTNO,TRANS_DESC,DPM_TRANS_NO,TRANS_DATE,ISIN_CD,OPENING_BAL,QTY,ORDER_BY,LINE_NO,CHARGE_VAL,SETTM_ID , TR_SETTM_ID)           
		 SELECT DISTINCT DPHMCD_DPAM_ID,            
		 DPAM_SBA_NAME,          
		 DPAM_SBA_NO,                      
		 TRANS_DESC=--CONVERT(VARCHAR,ISNULL(DPHMCD_CURR_QTY,0.000)) + '|' + CONVERT(VARCHAR,ISNULL(DPHMCD_FREE_QTY,0.000)) + '|' + CONVERT(VARCHAR,ISNULL(DPHMCD_LEND_QTY,0.000)) + '|' +  CONVERT(VARCHAR,ISNULL(DPHMCD_FREEZE_QTY,0.000)) + '|' + CONVERT(VARCHAR,ISNULL(DPHMCD_LOCKIN_QTY,0.000)) + '|' + CONVERT(VARCHAR,ISNULL(DPHMCD_AVAIL_LEND_QTY,0.000)) + '|' + CONVERT(VARCHAR,ISNULL(DPHMCD_PLEDGE_QTY,0.000)) + '|' + CONVERT(VARCHAR,ISNULL(DPHMCD_EARMARK_QTY,0.000)) + '|' + CONVERT(VARCHAR,ISNULL(DPHMCD_BORROW_QTY,0.000)),        
CONVERT(VARCHAR,ISNULL(DPHMCD_CURR_QTY,0.000)) + '|' 
						 + CONVERT(VARCHAR,ISNULL(DPHMCD_FREE_QTY,0.000)) + '|' 
						+ CONVERT(VARCHAR,ISNULL(DPHMCD_FREEZE_QTY,0.000)) + '|' 
						+ CONVERT(VARCHAR,ISNULL(DPHMCD_PLEDGE_QTY,0.000)) + '|' 
						+ CONVERT(VARCHAR,ISNULL(DPHMCD_DEMAT_PND_VER_QTY,0.000)) + '|' 
						+ CONVERT(VARCHAR,ISNULL(DPHMCD_REMAT_PND_CONF_QTY ,0.000)) + '|' 
						+ CONVERT(VARCHAR,ISNULL(DPHMCD_DEMAT_PND_CONF_QTY,0.000)) + '|' 
						+ CONVERT(VARCHAR,ISNULL(DPHMCD_SAFE_KEEPING_QTY,0.000)) + '|' 
						--+ CONVERT(VARCHAR,ISNULL(DPHMCD_LOCKIN_QTY,0.000)) + '|' 
						+ convert(varchar,case when ISNULL(DPHMCD_EARMARK_QTY,0.000)<>'0' then ISNULL(DPHMCD_EARMARK_QTY,0.000)+ISNULL(DPHMCD_LOCKIN_QTY,0.000) else  Convert(varchar,ISNULL(DPHMCD_LOCKIN_QTY,0.000)) end)  + '|'     
						+ CONVERT(VARCHAR,ISNULL(DPHMCD_ELIMINATION_QTY,0.000)) + '|' 
						+ CONVERT(VARCHAR,ISNULL(DPHMCD_EARMARK_QTY,0.000)) + '|' 
						+ CONVERT(VARCHAR,ISNULL(DPHMCD_AVAIL_LEND_QTY,0.000))  + '|' 
						+ CONVERT(VARCHAR,ISNULL(DPHMCD_LEND_QTY,0.000))  + '|' 
						+ CONVERT(VARCHAR,ISNULL(DPHMCD_BORROW_QTY,0.000)),   
		 TRANS_NO='',                      
		 TRANS_DATE='DEC 31 2100',                      
		 DPHMCD_ISIN,                      
		 0,            
		 0,          
		 3,  
		 0,        
		 0 ,'', RIGHT(ISNULL('','') ,7)                        
		 FROM #TMPHLDG WITH(NOLOCK)  
		 ,ACCOUNT_GROUP_MAPPING G WITH(NOLOCK)              
		 ,#ACLIST ACCOUNT                    
		 WHERE           
		 DPHMCD_HOLDING_DT = @PA_TODATE-- @PA_PREVFROMDATE  COMMENTED BY SHILPA FOR HOLDING NOT COMING IN BILL
		 AND ISNUMERIC(DPAM_SBA_NO) = 1                       
		 AND CONVERT(NUMERIC,DPAM_SBA_NO) BETWEEN CONVERT(NUMERIC,@PA_FROMACCID) AND CONVERT(NUMERIC,@PA_TOACCID)   
		 AND G.DPAM_ID = DPHMCD_DPAM_ID      
		 AND GROUP_CD =  @PA_GROUP_CD      
		 AND DPHMCD_DPAM_ID = ACCOUNT.DPAM_ID              
		 AND (DPHMCD_HOLDING_DT BETWEEN EFF_FROM AND EFF_TO)    
		 AND DPHMCD_DPM_ID = @@DPMID       
		 --AND ISNULL(DPHMCD_CURR_QTY,0) <> 0         
	  END  
	  ELSE  
	  BEGIN  
		 INSERT INTO #TEMPMAINCDSL(DPAM_ID,DPAM_SBA_NAME,DPAM_ACCTNO,TRANS_DESC,DPM_TRANS_NO,TRANS_DATE,ISIN_CD,OPENING_BAL,QTY,ORDER_BY,LINE_NO,CHARGE_VAL,SETTM_ID , TR_SETTM_ID)           
		 SELECT DISTINCT DPHMCD_DPAM_ID,            
		 DPAM_SBA_NAME,          
		 DPAM_SBA_NO,                      
		 TRANS_DESC=--CONVERT(VARCHAR,ISNULL(DPHMCD_CURR_QTY,0.000)) + '|' + CONVERT(VARCHAR,ISNULL(DPHMCD_FREE_QTY,0.000)) + '|' + CONVERT(VARCHAR,ISNULL(DPHMCD_LEND_QTY,0.000)) + '|' +  CONVERT(VARCHAR,ISNULL(DPHMCD_FREEZE_QTY,0.000)) + '|' + CONVERT(VARCHAR,ISNULL(DPHMCD_LOCKIN_QTY,0.000)) + '|' + CONVERT(VARCHAR,ISNULL(DPHMCD_AVAIL_LEND_QTY,0.000)) + '|' + CONVERT(VARCHAR,ISNULL(DPHMCD_PLEDGE_QTY,0.000)) + '|' + CONVERT(VARCHAR,ISNULL(DPHMCD_EARMARK_QTY,0.000)) + '|' + CONVERT(VARCHAR,ISNULL(DPHMCD_BORROW_QTY,0.000)),
CONVERT(VARCHAR,ISNULL(DPHMCD_CURR_QTY,0.000)) + '|' 
						 + CONVERT(VARCHAR,ISNULL(DPHMCD_FREE_QTY,0.000)) + '|' 
						+ CONVERT(VARCHAR,ISNULL(DPHMCD_FREEZE_QTY,0.000)) + '|' 
						+ CONVERT(VARCHAR,ISNULL(DPHMCD_PLEDGE_QTY,0.000)) + '|' 
						+ CONVERT(VARCHAR,ISNULL(DPHMCD_DEMAT_PND_VER_QTY,0.000)) + '|' 
						+ CONVERT(VARCHAR,ISNULL(DPHMCD_REMAT_PND_CONF_QTY ,0.000)) + '|' 
						+ CONVERT(VARCHAR,ISNULL(DPHMCD_DEMAT_PND_CONF_QTY,0.000)) + '|' 
						+ CONVERT(VARCHAR,ISNULL(DPHMCD_SAFE_KEEPING_QTY,0.000)) + '|' 
						--+ CONVERT(VARCHAR,ISNULL(DPHMCD_LOCKIN_QTY,0.000)) + '|' 
						+ convert(varchar,case when ISNULL(DPHMCD_EARMARK_QTY,0.000)<>'0' then ISNULL(DPHMCD_EARMARK_QTY,0.000)+ISNULL(DPHMCD_LOCKIN_QTY,0.000) else  Convert(varchar,ISNULL(DPHMCD_LOCKIN_QTY,0.000)) end)  + '|'     
						+ CONVERT(VARCHAR,ISNULL(DPHMCD_ELIMINATION_QTY,0.000)) + '|' 
						+ CONVERT(VARCHAR,ISNULL(DPHMCD_EARMARK_QTY,0.000)) + '|' 
						+ CONVERT(VARCHAR,ISNULL(DPHMCD_AVAIL_LEND_QTY,0.000))  + '|' 
						+ CONVERT(VARCHAR,ISNULL(DPHMCD_LEND_QTY,0.000))  + '|' 
						+ CONVERT(VARCHAR,ISNULL(DPHMCD_BORROW_QTY,0.000)),   
		 TRANS_NO='',                      
		 TRANS_DATE='DEC 31 2100',                      
		 DPHMCD_ISIN,                      
		 ISNULL(DPHMCD_CURR_QTY,0),            
		 0,          
		 3,  
		 0,        
		 0    ,'',RIGHT(ISNULL('','') ,7)                         
		 FROM #TMPHLDG WITH(NOLOCK),          
		 #ACLIST ACCOUNT                    
		 WHERE           
		 DPHMCD_HOLDING_DT = @PA_TODATE --@PA_PREVFROMDATE   COMMENTED BY SHILPA FOR HOLDING NOT COMING IN BILL
		 AND ISNUMERIC(DPAM_SBA_NO) = 1                       
		 AND CONVERT(NUMERIC,DPAM_SBA_NO) BETWEEN CONVERT(NUMERIC,@PA_FROMACCID) AND CONVERT(NUMERIC,@PA_TOACCID)                                               
		 AND DPHMCD_DPAM_ID = ACCOUNT.DPAM_ID              
		 AND (DPHMCD_HOLDING_DT BETWEEN EFF_FROM AND EFF_TO)
		 AND DPHMCD_DPM_ID = @@DPMID         
		 --AND ISNULL(DPHMCD_CURR_QTY,0) <> 0         
	  
	  END  
	  END  
	  ELSE  
	  BEGIN  
	  IF @PA_GROUP_CD <> ''      
	  BEGIN   
		 INSERT INTO #TEMPMAINCDSL(DPAM_ID,DPAM_SBA_NAME,DPAM_ACCTNO,TRANS_DESC,DPM_TRANS_NO,TRANS_DATE,ISIN_CD,OPENING_BAL,QTY,ORDER_BY,LINE_NO,CHARGE_VAL,SETTM_ID, TR_SETTM_ID )           
		 SELECT DISTINCT DPHMCD_DPAM_ID,            
		 DPAM_SBA_NAME,          
		 DPAM_SBA_NO,                      
		 TRANS_DESC=--CONVERT(VARCHAR,ISNULL(DPHMCD_CURR_QTY,0.000)) + '|' + CONVERT(VARCHAR,ISNULL(DPHMCD_FREE_QTY,0.000)) + '|' + CONVERT(VARCHAR,ISNULL(DPHMCD_LEND_QTY,0.000)) + '|' + CONVERT(VARCHAR,ISNULL(DPHMCD_LEND_QTY,0.000)) + '|' + CONVERT(VARCHAR,ISNULL(DPHMCD_FREEZE_QTY,0.000)) + '|' + CONVERT(VARCHAR,ISNULL(DPHMCD_LOCKIN_QTY,0.000)) + '|' + CONVERT(VARCHAR,ISNULL(DPHMCD_LOCKIN_QTY,0.000)) + '|' + CONVERT(VARCHAR,ISNULL(DPHMCD_AVAIL_LEND_QTY,0.000)) + '|' + CONVERT(VARCHAR,ISNULL(DPHMCD_AVAIL_LEND_QTY,0.000)) + '|' + CONVERT(VARCHAR,ISNULL(DPHMCD_PLEDGE_QTY,0.000)) + '|' + CONVERT(VARCHAR,ISNULL(DPHMCD_EARMARK_QTY,0.000)) + '|' + CONVERT(VARCHAR,ISNULL(DPHMCD_BORROW_QTY,0.000)),        
CONVERT(VARCHAR,ISNULL(DPHMCD_CURR_QTY,0.000)) + '|' 
						 + CONVERT(VARCHAR,ISNULL(DPHMCD_FREE_QTY,0.000)) + '|' 
						+ CONVERT(VARCHAR,ISNULL(DPHMCD_FREEZE_QTY,0.000)) + '|' 
						+ CONVERT(VARCHAR,ISNULL(DPHMCD_PLEDGE_QTY,0.000)) + '|' 
						+ CONVERT(VARCHAR,ISNULL(DPHMCD_DEMAT_PND_VER_QTY,0.000)) + '|' 
						+ CONVERT(VARCHAR,ISNULL(DPHMCD_REMAT_PND_CONF_QTY ,0.000)) + '|' 
						+ CONVERT(VARCHAR,ISNULL(DPHMCD_DEMAT_PND_CONF_QTY,0.000)) + '|' 
						+ CONVERT(VARCHAR,ISNULL(DPHMCD_SAFE_KEEPING_QTY,0.000)) + '|' 
						--+ CONVERT(VARCHAR,ISNULL(DPHMCD_LOCKIN_QTY,0.000)) + '|' 
						+ convert(varchar,case when ISNULL(DPHMCD_EARMARK_QTY,0.000)<>'0' then ISNULL(DPHMCD_EARMARK_QTY,0.000)+ISNULL(DPHMCD_LOCKIN_QTY,0.000) else  Convert(varchar,ISNULL(DPHMCD_LOCKIN_QTY,0.000)) end)  + '|'     
						+ CONVERT(VARCHAR,ISNULL(DPHMCD_ELIMINATION_QTY,0.000)) + '|' 
						+ CONVERT(VARCHAR,ISNULL(DPHMCD_EARMARK_QTY,0.000)) + '|' 
						+ CONVERT(VARCHAR,ISNULL(DPHMCD_AVAIL_LEND_QTY,0.000))  + '|' 
						+ CONVERT(VARCHAR,ISNULL(DPHMCD_LEND_QTY,0.000))  + '|' 
						+ CONVERT(VARCHAR,ISNULL(DPHMCD_BORROW_QTY,0.000)),   
		 TRANS_NO='',                      
		 TRANS_DATE='DEC 31 2100',                      
		 DPHMCD_ISIN,                      
		 ISNULL(DPHMCD_CURR_QTY,0),            
		 0,          
		 3,  
		 0,        
		 0  ,'', RIGHT(ISNULL('','') ,7)                             
		 FROM #TMPHLDG WITH(NOLOCK)  
		 ,ACCOUNT_GROUP_MAPPING G WITH(NOLOCK)              
		 ,#ACLIST ACCOUNT                    
		 WHERE           
		 DPHMCD_HOLDING_DT =@PA_TODATE --@PA_PREVFROMDATE   COMMENTED BY SHILPA FOR HOLDING NOT COMING IN BILL        
		 AND EXISTS(SELECT DPAM_ID FROM #TEMPMAINCDSL T1 WITH(NOLOCK) WHERE T1.DPAM_ID = DPHMCD_DPAM_ID)                            
		 AND ISNUMERIC(DPAM_SBA_NO) = 1                       
		 AND CONVERT(NUMERIC,DPAM_SBA_NO) BETWEEN CONVERT(NUMERIC,@PA_FROMACCID) AND CONVERT(NUMERIC,@PA_TOACCID)   
		 AND G.DPAM_ID = DPHMCD_DPAM_ID      
		 AND GROUP_CD =  @PA_GROUP_CD      
		 AND DPHMCD_DPAM_ID = ACCOUNT.DPAM_ID              
		 AND (DPHMCD_HOLDING_DT BETWEEN EFF_FROM AND EFF_TO)    
		 AND DPHMCD_DPM_ID = @@DPMID
		-- AND ISNULL(DPHMCD_CURR_QTY,0) <> 0              
	  END  
	  ELSE  
	  BEGIN  
		 INSERT INTO #TEMPMAINCDSL(DPAM_ID,DPAM_SBA_NAME,DPAM_ACCTNO,TRANS_DESC,DPM_TRANS_NO,TRANS_DATE,ISIN_CD,OPENING_BAL,QTY,ORDER_BY,LINE_NO,CHARGE_VAL,SETTM_ID , TR_SETTM_ID)           
		 SELECT DISTINCT DPHMCD_DPAM_ID,            
		 DPAM_SBA_NAME,          
		 DPAM_SBA_NO,                      
		 TRANS_DESC=--CONVERT(VARCHAR,ISNULL(DPHMCD_CURR_QTY,0.000)) + '|' + CONVERT(VARCHAR,ISNULL(DPHMCD_FREE_QTY,0.000)) + '|' + CONVERT(VARCHAR,ISNULL(DPHMCD_LEND_QTY,0.000)) + '|' +  CONVERT(VARCHAR,ISNULL(DPHMCD_FREEZE_QTY,0.000)) + '|' + CONVERT(VARCHAR,ISNULL(DPHMCD_LOCKIN_QTY,0.000)) + '|' + CONVERT(VARCHAR,ISNULL(DPHMCD_AVAIL_LEND_QTY,0.000)) + '|' + CONVERT(VARCHAR,ISNULL(DPHMCD_PLEDGE_QTY,0.000)) + '|' + CONVERT(VARCHAR,ISNULL(DPHMCD_EARMARK_QTY,0.000)) + '|' + CONVERT(VARCHAR,ISNULL(DPHMCD_BORROW_QTY,0.000)),
CONVERT(VARCHAR,ISNULL(DPHMCD_CURR_QTY,0.000)) + '|' 
						 + CONVERT(VARCHAR,ISNULL(DPHMCD_FREE_QTY,0.000)) + '|' 
						+ CONVERT(VARCHAR,ISNULL(DPHMCD_FREEZE_QTY,0.000)) + '|' 
						+ CONVERT(VARCHAR,ISNULL(DPHMCD_PLEDGE_QTY,0.000)) + '|' 
						+ CONVERT(VARCHAR,ISNULL(DPHMCD_DEMAT_PND_VER_QTY,0.000)) + '|' 
						+ CONVERT(VARCHAR,ISNULL(DPHMCD_REMAT_PND_CONF_QTY ,0.000)) + '|' 
						+ CONVERT(VARCHAR,ISNULL(DPHMCD_DEMAT_PND_CONF_QTY,0.000)) + '|' 
						+ CONVERT(VARCHAR,ISNULL(DPHMCD_SAFE_KEEPING_QTY,0.000)) + '|' 
						--+ CONVERT(VARCHAR,ISNULL(DPHMCD_LOCKIN_QTY,0.000)) + '|' 
						+ convert(varchar,case when ISNULL(DPHMCD_EARMARK_QTY,0.000)<>'0' then ISNULL(DPHMCD_EARMARK_QTY,0.000)+ISNULL(DPHMCD_LOCKIN_QTY,0.000) else  Convert(varchar,ISNULL(DPHMCD_LOCKIN_QTY,0.000)) end)  + '|'     
						+ CONVERT(VARCHAR,ISNULL(DPHMCD_ELIMINATION_QTY,0.000)) + '|' 
						+ CONVERT(VARCHAR,ISNULL(DPHMCD_EARMARK_QTY,0.000)) + '|' 
						+ CONVERT(VARCHAR,ISNULL(DPHMCD_AVAIL_LEND_QTY,0.000))  + '|' 
						+ CONVERT(VARCHAR,ISNULL(DPHMCD_LEND_QTY,0.000))  + '|' 
						+ CONVERT(VARCHAR,ISNULL(DPHMCD_BORROW_QTY,0.000)),   
		 TRANS_NO='',                      
		 TRANS_DATE='DEC 31 2100',                      
		 DPHMCD_ISIN,                      
		 ISNULL(DPHMCD_CURR_QTY,0),            
		 0,          
		 3,  
		 0,        
		 0   ,'', RIGHT(ISNULL('','') ,7)                   
		 FROM #TMPHLDG WITH(NOLOCK),          
		 #ACLIST ACCOUNT                    
		 WHERE DPHMCD_HOLDING_DT = @PA_TODATE --@PA_PREVFROMDATE   COMMENTED BY SHILPA FOR HOLDING NOT COMING IN BILL          
		 AND EXISTS(SELECT DPAM_ID FROM #TEMPMAINCDSL T1 WITH(NOLOCK) WHERE T1.DPAM_ID = DPHMCD_DPAM_ID)                            
		 AND ISNUMERIC(DPAM_SBA_NO) = 1                       
		 AND CONVERT(NUMERIC,DPAM_SBA_NO) BETWEEN CONVERT(NUMERIC,@PA_FROMACCID) AND CONVERT(NUMERIC,@PA_TOACCID)                                   
		 AND DPHMCD_DPAM_ID = ACCOUNT.DPAM_ID              
		 AND (DPHMCD_HOLDING_DT BETWEEN EFF_FROM AND EFF_TO)
		 AND DPHMCD_DPM_ID = @@DPMID     
		-- AND ISNULL(DPHMCD_CURR_QTY,0) <> 0         
	  
	  END  
	  
	  END          
   END    
PRINT 'SS'
     PRINT @PA_PREVFROMDATE
 --SELECT * FROM #TEMPMAINCDSL
 IF @PA_GROUP_CD <> ''      
 BEGIN           
  INSERT INTO #TEMPMAINCDSL(DPAM_ID,DPAM_SBA_NAME,DPAM_ACCTNO,TRANS_DESC,DPM_TRANS_NO,TRANS_DATE,ISIN_CD,OPENING_BAL,QTY,ORDER_BY,LINE_NO,CHARGE_VAL)           
  SELECT CLIC_DPAM_ID,DPAM_SBA_NAME,DPAM_SBA_NO,CLIC_CHARGE_NAMe,'1',CLIC_TRANS_DT=@PA_TODATE,'A',NULL,NULL,2,0,SUM(CLIC_CHARGE_AMT)           
  FROM CLIENT_CHARGES_CDSL WITH(NOLOCK)  
  ,ACCOUNT_GROUP_MAPPING G WITH(NOLOCK)              
  , #ACLIST ACCOUNT             
  WHERE           
  CLIC_DPM_ID = @@DPMID                      
  AND CLIC_CHARGE_NAME <> 'SERVICE TAX'           
  AND CLIC_TRANS_DT >=@PA_FROMDATE AND CLIC_TRANS_DT <=@PA_TODATE                       
  AND ISNUMERIC(DPAM_SBA_NO) = 1                        
  AND CONVERT(NUMERIC,DPAM_SBA_NO) BETWEEN CONVERT(NUMERIC,@PA_FROMACCID) AND CONVERT(NUMERIC,@PA_TOACCID)                       
  AND G.DPAM_ID = CLIC_DPAM_ID      
  AND GROUP_CD =  @PA_GROUP_CD      
  AND CLIC_DPAM_ID = ACCOUNT.DPAM_ID   
  AND CLIC_DELETED_IND=1                     
  AND (CLIC_TRANS_DT BETWEEN EFF_FROM AND EFF_TO)   
  GROUP BY CLIC_DPAM_ID,DPAM_SBA_NO,DPAM_SBA_NAME,CLIC_CHARGE_NAME     
  UNION ALL 
   SELECT CLIC_DPAM_ID,DPAM_SBA_NAME,DPAM_SBA_NO,'<b>TOTAL CHARGES</b>','2',CLIC_TRANS_DT=@PA_TODATE,'B',NULL,NULL,2,0,SUM(CLIC_CHARGE_AMT)           
  FROM CLIENT_CHARGES_CDSL WITH(NOLOCK)  
  ,ACCOUNT_GROUP_MAPPING G WITH(NOLOCK)              
  , #ACLIST ACCOUNT             
  WHERE           
  CLIC_DPM_ID = @@DPMID                      
  AND CLIC_CHARGE_NAME <> 'SERVICE TAX'           
  AND CLIC_TRANS_DT >=@PA_FROMDATE AND CLIC_TRANS_DT <=@PA_TODATE                       
  AND ISNUMERIC(DPAM_SBA_NO) = 1                        
  AND CONVERT(NUMERIC,DPAM_SBA_NO) BETWEEN CONVERT(NUMERIC,@PA_FROMACCID) AND CONVERT(NUMERIC,@PA_TOACCID)                       
  AND G.DPAM_ID = CLIC_DPAM_ID      
  AND GROUP_CD =  @PA_GROUP_CD      
  AND CLIC_DPAM_ID = ACCOUNT.DPAM_ID   
  AND CLIC_DELETED_IND=1                     
  AND (CLIC_TRANS_DT BETWEEN EFF_FROM AND EFF_TO)   
  GROUP BY CLIC_DPAM_ID,DPAM_SBA_NO,DPAM_SBA_NAME 
  UNION ALL 
   SELECT CLIC_DPAM_ID,DPAM_SBA_NAME,DPAM_SBA_NO,'<b>SERVICE TAX</b>','3',CLIC_TRANS_DT=@PA_TODATE,'C',NULL,NULL,2,0,SUM(CLIC_CHARGE_AMT)           
  FROM CLIENT_CHARGES_CDSL WITH(NOLOCK)  
  ,ACCOUNT_GROUP_MAPPING G WITH(NOLOCK)              
  , #ACLIST ACCOUNT             
  WHERE           
  CLIC_DPM_ID = @@DPMID                      
  AND CLIC_CHARGE_NAME = 'SERVICE TAX'           
  AND CLIC_TRANS_DT >=@PA_FROMDATE AND CLIC_TRANS_DT <=@PA_TODATE                       
  AND ISNUMERIC(DPAM_SBA_NO) = 1                        
  AND CONVERT(NUMERIC,DPAM_SBA_NO) BETWEEN CONVERT(NUMERIC,@PA_FROMACCID) AND CONVERT(NUMERIC,@PA_TOACCID)                       
  AND G.DPAM_ID = CLIC_DPAM_ID      
  AND GROUP_CD =  @PA_GROUP_CD      
  AND CLIC_DPAM_ID = ACCOUNT.DPAM_ID   
  AND CLIC_DELETED_IND=1                     
  AND (CLIC_TRANS_DT BETWEEN EFF_FROM AND EFF_TO)   
  GROUP BY CLIC_DPAM_ID,DPAM_SBA_NO,DPAM_SBA_NAME,CLIC_CHARGE_NAME 
               
 END  
 ELSE  
 BEGIN  
  INSERT INTO #TEMPMAINCDSL(DPAM_ID,DPAM_SBA_NAME,DPAM_ACCTNO,TRANS_DESC,DPM_TRANS_NO,TRANS_DATE,ISIN_CD,OPENING_BAL,QTY,ORDER_BY,LINE_NO,CHARGE_VAL)           
  SELECT CLIC_DPAM_ID,DPAM_SBA_NAME,DPAM_SBA_NO,CLIC_CHARGE_NAME,'1',CLIC_TRANS_DT=@PA_TODATE,'A',NULL,NULL,2,0,SUM(CLIC_CHARGE_AMT)           
  FROM CLIENT_CHARGES_CDSL WITH(NOLOCK)         
  , #ACLIST ACCOUNT             
  WHERE           
  CLIC_DPM_ID = @@DPMID                      
  AND CLIC_CHARGE_NAME <> 'SERVICE TAX'           
  AND CLIC_TRANS_DT >=@PA_FROMDATE AND CLIC_TRANS_DT <=@PA_TODATE                       
  AND ISNUMERIC(DPAM_SBA_NO) = 1                        
  AND CONVERT(NUMERIC,DPAM_SBA_NO) BETWEEN CONVERT(NUMERIC,@PA_FROMACCID) AND CONVERT(NUMERIC,@PA_TOACCID)                       
  AND CLIC_DPAM_ID = ACCOUNT.DPAM_ID   
  AND CLIC_DELETED_IND=1                      
  AND (CLIC_TRANS_DT BETWEEN EFF_FROM AND EFF_TO)
  GROUP BY CLIC_DPAM_ID,DPAM_SBA_NO,DPAM_SBA_NAME,CLIC_CHARGE_NAME                     
  UNION ALL 
    SELECT CLIC_DPAM_ID,DPAM_SBA_NAME,DPAM_SBA_NO,'<b>TOTAL CHARGES</b>','2',CLIC_TRANS_DT=@PA_TODATE,'B',NULL,NULL,2,0,SUM(CLIC_CHARGE_AMT)           
  FROM CLIENT_CHARGES_CDSL WITH(NOLOCK)         
  , #ACLIST ACCOUNT             
  WHERE           
  CLIC_DPM_ID = @@DPMID                      
  AND CLIC_CHARGE_NAME <> 'SERVICE TAX'           
  AND CLIC_TRANS_DT >=@PA_FROMDATE AND CLIC_TRANS_DT <=@PA_TODATE                       
  AND ISNUMERIC(DPAM_SBA_NO) = 1                        
  AND CONVERT(NUMERIC,DPAM_SBA_NO) BETWEEN CONVERT(NUMERIC,@PA_FROMACCID) AND CONVERT(NUMERIC,@PA_TOACCID)                       
  AND CLIC_DPAM_ID = ACCOUNT.DPAM_ID   
  AND CLIC_DELETED_IND=1                      
  AND (CLIC_TRANS_DT BETWEEN EFF_FROM AND EFF_TO)
  GROUP BY CLIC_DPAM_ID,DPAM_SBA_NO,DPAM_SBA_NAME
  UNION ALL 
    SELECT CLIC_DPAM_ID,DPAM_SBA_NAME,DPAM_SBA_NO,'<b>SERVICE TAX</b>','3',CLIC_TRANS_DT=@PA_TODATE,'C',NULL,NULL,2,0,SUM(CLIC_CHARGE_AMT)           
  FROM CLIENT_CHARGES_CDSL WITH(NOLOCK)         
  , #ACLIST ACCOUNT             
  WHERE           
  CLIC_DPM_ID = @@DPMID                      
  AND CLIC_CHARGE_NAME = 'SERVICE TAX'           
  AND CLIC_TRANS_DT >=@PA_FROMDATE AND CLIC_TRANS_DT <=@PA_TODATE                       
  AND ISNUMERIC(DPAM_SBA_NO) = 1                        
  AND CONVERT(NUMERIC,DPAM_SBA_NO) BETWEEN CONVERT(NUMERIC,@PA_FROMACCID) AND CONVERT(NUMERIC,@PA_TOACCID)                       
  AND CLIC_DPAM_ID = ACCOUNT.DPAM_ID   
  AND CLIC_DELETED_IND=1                      
  AND (CLIC_TRANS_DT BETWEEN EFF_FROM AND EFF_TO)
  GROUP BY CLIC_DPAM_ID,DPAM_SBA_NO,DPAM_SBA_NAME  
  
 END  
           
   IF @PA_TRANSCLIENTSONLY <> 'Y'    
   BEGIN





   INSERT INTO #TEMPMAINCDSL(DPAM_ID,DPAM_SBA_NAME,DPAM_ACCTNO,TRANS_DESC,DPM_TRANS_NO,TRANS_DATE,ISIN_CD,OPENING_BAL,QTY,ORDER_BY,LINE_NO,CHARGE_VAL) 
   SELECT DPAM_ID , DPAM_SBA_NAME, DPAM_SBA_NO , '','','','',0,0,4,0,0 FROM #ACLIST A
   WHERE NOT EXISTS(SELECT DPAM_ID FROM #TEMPMAINCDSL B WHERE A.DPAM_ID = B.DPAM_ID)
   AND  ISNUMERIC(DPAM_SBA_NO)=1 AND EFF_FROM BETWEEN  @PA_FROMDATE AND @PA_TODATE 
   AND CONVERT(NUMERIC,DPAM_SBA_NO) BETWEEN CONVERT(NUMERIC,@PA_FROMACCID) AND CONVERT(NUMERIC,@PA_TOACCID)   

   END 	

    SET @@SSQL ='INSERT INTO #LEDGERBAL
	SELECT DPAM_ID,SUM(CASE WHEN LDG_VOUCHER_TYPE = 5 AND LDG_VOUCHER_DT >= ''' + CONVERT(VARCHAR(11),@PA_FROMDATE,109) + ''' THEN 0 ELSE ISNULL(LDG_AMOUNT,0)  END )
	FROM (
	SELECT DISTINCT DPAM_ID FROM #TEMPMAINCDSL
	) TMP LEFT OUTER JOIN LEDGER' + CONVERT(VARCHAR,@@LEDGERID) + ' ON DPAM_ID = LDG_ACCOUNT_ID AND LDG_ACCOUNT_TYPE = ''P'' AND LDG_VOUCHER_DT <= ''' + CONVERT(VARCHAR(11),@PA_TODATE,109) + ''' AND LDG_DELETED_IND = 1
	GROUP BY DPAM_ID'
	EXEC(@@SSQL)


 INSERT INTO #TEMPMAINCDSL(DPAM_ID,DPAM_SBA_NAME,DPAM_ACCTNO,TRANS_DESC,DPM_TRANS_NO,TRANS_DATE,ISIN_CD,OPENING_BAL,QTY,ORDER_BY,LINE_NO,CHARGE_VAL)           
  SELECT LEDGER.DPAM_ID,DPAM_SBA_NAME,DPAM_SBA_NO,'<b>PREVIOUS BALANCE</b>','4',CLIC_TRANS_DT=@PA_TODATE,'D',NULL,NULL,2,0,PREV_BILL_BAL           
  FROM  #LEDGERBAL LEDGER
  , #ACLIST ACCOUNT             
  WHERE     ISNUMERIC(DPAM_SBA_NO)=1 AND       CONVERT(NUMERIC,DPAM_SBA_NO) BETWEEN CONVERT(NUMERIC,@PA_FROMACCID) AND CONVERT(NUMERIC,@PA_TOACCID)                       
  AND LEDGER.DPAM_ID  = ACCOUNT.DPAM_ID   
  
  
  
 INSERT INTO #TEMPMAINCDSL(DPAM_ID,DPAM_SBA_NAME,DPAM_ACCTNO,TRANS_DESC,DPM_TRANS_NO,TRANS_DATE,ISIN_CD,OPENING_BAL,QTY,ORDER_BY,LINE_NO,CHARGE_VAL)           
  SELECT DPAM_ID,DPAM_SBA_NAME,DPAM_ACCTNO,'<b>NET AMOUNT</b>','5',@PA_TODATE,'E',NULL,NULL,2,0,SUM(CASE WHEN  TRANS_DESC = '<b>TOTAL CHARGES</b>'
   THEN CHARGE_VAL           
  WHEN  TRANS_DESC = '<b>SERVICE TAX</b>' THEN CHARGE_VAL
  WHEN  TRANS_DESC = '<b>PREVIOUS BALANCE</b>' THEN CHARGE_VAL ELSE 0 END )
  FROM #TEMPMAINCDSL GROUP BY DPAM_ID,DPAM_SBA_NAME,DPAM_ACCTNO
  
  update a   set TRANS_DESC =case when  isnull(TRANS_DESC,'')='1_DIBOOK' then 'DIS BOOK CHARGES'
when  isnull(TRANS_DESC,'')='1_POAFIXED' then 'POA CHARGES'
when  isnull(TRANS_DESC,'')='INV CORP_ACMAIN' then 'ANNUAL MAINTAINENCE CHARGES'
when  isnull(TRANS_DESC,'')='JK INV_ACMAIN' then 'ANNUAL MAINTAINENCE CHARGES'
when  isnull(TRANS_DESC,'')='LIF1250_DIBOOK' then 'DIS BOOK CHARGES'
when  isnull(TRANS_DESC,'')='LIF1250_ONETIME' then 'LIF1250 AMC CHARGES'
when  isnull(TRANS_DESC,'')='LIF1250_POAFIXED' then 'POA CHARGES'
when  isnull(TRANS_DESC,'')='LIF1250C_POAFIXED' then 'POA CHARGES'
when  isnull(TRANS_DESC,'')='LIF1250Q_DIBOOK' then 'DIS BOOK CHARGES'
when  isnull(TRANS_DESC,'')='NBC_ACMAIN' then 'ANNUAL MAINTAINENCE CHARGES'
when  isnull(TRANS_DESC,'')='NBFC INVW_DIBOOK' then 'DIS BOOK CHARGES'
when  isnull(TRANS_DESC,'')='TRADERS_ACMAIN' then 'ANNUAL MAINTAINENCE CHAGES'
when  isnull(TRANS_DESC,'')='TRADERS_POAFIXED' then 'POA CHARGES'
when  isnull(TRANS_DESC,'')='ZEROWAIVE_DIBOOK' then 'DIS BOOK CHARGES'
when  isnull(TRANS_DESC,'')='ZEROWAIVE_POAFIXED' then 'POA CHARGES'
when  isnull(TRANS_DESC,'')='ZEROWAIVE1_POAFIXED' then 'POA CHARGES'
when  isnull(TRANS_DESC,'')='DEMAT COURIER CHARGE' then 'DEMAT CHARGES'
when  isnull(TRANS_DESC,'')='DEMAT REJECTION CHARGE' then 'DEMAT CHARGES'
when  isnull(TRANS_DESC,'')='1_ACMAIN' then 'ANNUAL MAINTAINENCE CHARGES'
 else isnull(TRANS_DESC,'') end from #TEMPMAINCDSL a where ORDER_BY = 2  
  
  

	IF @@L_GRPMSTR_CD='N'
	BEGIN  
	PRINT '112'
	SELECT ORDER_BY,T.DPAM_ID,DPAM_SBA_NAME,DPAM_ACCTNO,                      
	CDSHM_TRATM_DESC= ISNULL(UPPER(LTRIM(RTRIM(TRANS_DESC))),''),              
	ISNULL(DPM_TRANS_NO,'') DPM_TRANS_NO,                      
	TRANS_DATE=CONVERT(VARCHAR(11),TRANS_DATE,109),                      
	ISNULL(T.ISIN_CD,'') ISIN_CD,          
	ISIN_NAME=ISNULL(ISIN_NAME,''),                      
	OPENING_BAL=REPLACE(CONVERT(VARCHAR,ISNULL(OPENING_BAL,0)),'.000',''),            
	DEBIT_QTY= CASE WHEN  QTY <= 0 THEN REPLACE(CONVERT(VARCHAR,ABS(QTY)),'.000','') ELSE '' END,                      
	CREDIT_QTY= CASE WHEN QTY > 0 THEN REPLACE(CONVERT(VARCHAR,ABS(QTY)),'.000','') ELSE '' END,
	CLOSING_BAL = REPLACE(CONVERT(VARCHAR,(ISNULL(OPENING_BAL,0) + ISNULL(QTY,0))),'.000',''),          
	CHARGE_VAL=ISNULL(CHARGE_VAL,0)  * -1,
	PREV_BILL_BAL=ISNULL(PREV_BILL_BAL,0),
	BILL_DUE_DT =@@BILLDUEDATE,
--	TRANS_DATE,
	ISNULL(SETTM_ID,'') SETTM_ID, ISNULL(TR_SETTM_ID,'') TR_SETTM_ID,ISNULL(TRATM_CD,'') TRATM_CD,
	VALUATION=CONVERT(NUMERIC(18,2),CONVERT(NUMERIC(18,3),CASE WHEN ORDER_BY = '3' THEN CITRUS_USR.FN_SPLITVAL_BY(TRANS_DESC,1,'|') ELSE '0' END )*ISNULL(CLOPM_CDSL_RT,0))  
	,RATE = ISNULL(CLOPM_CDSL_RT,0) ---INTO BILL_ANGEL_18082015_new
	,isnull(inv_no  ,'') invoice_no
,isnull(cl_gst_no,'') GST_no
,isnull(SINGLELOC,'') Base_loc_service_cnt
,case when  isnull(cl_gst_no,'')  <> '' then 'Y' else 'N' end GST_no_YN 
into billdata18052021
	FROM #TEMPMAINCDSL T WITH(NOLOCK)
	left outer join bo_bill_inv_mapping on boid = dpam_acctno and month(trans_date) = billmonth and YEAR(trans_date)= billyear
left outer join (SELECT ENTR_SBA BOID,REPLACE(ENTM_SHORT_NAME,'_BL','') + '/' + STATE_CODE SINGLELOC
, CASE WHEN ISNULL(CITRUS_USR.FN_UCC_ENTP(ENTR_BR,'BL',''),'')<>'' THEN CITRUS_USR.FN_UCC_ENTP(ENTR_BR,'BL','') + '/' + STATE_CODE ELSE '' END  MULTLOC,STATE_CODE
, CITRUS_USR.FN_UCC_accp(dpam_id ,'CLIENT GST','')  cl_gst_no
 FROM ENTITY_RELATIONSHIP E,ENTITY_MSTR,TIN_MSTR , dp_Acct_mstr WHERE GETDATE() BETWEEN ENTR_FROM_DT AND ISNULL(ENTR_TO_DT,'DEC 31 2100')
AND ENTR_DUMMY5=ENTM_ID and DPAM_SBA_NO = ENTR_SBA 
AND REPLACE(ENTM_SHORT_NAME,'_BL','')=STATE_NAME) v on   v.boid=dpam_acctno
	LEFT OUTER JOIN  ISIN_MSTR I WITH(NOLOCK) ON T.ISIN_CD = I.ISIN_CD
 LEFT OUTER JOIN CLOSING_PRICE_MSTR_CDSL ON T.ISIN_CD = CLOPM_ISIN_CD AND ISNULL(CLOPM_DT,'01/01/1900') = ( SELECT TOP 1 CLOPM_DT FROM CLOSING_PRICE_MSTR_CDSL WHERE CLOPM_ISIN_CD = T.ISIN_CD AND CLOPM_DT <= @PA_TODATE AND CLOPM_DELETED_IND = 1  ORDER BY CLOPM_DT DESC)
		
	LEFT OUTER JOIN  #LEDGERBAL L ON T.DPAM_ID = L.DPAM_ID
	--WHERE T.DPAM_ID = L.DPAM_ID
ORDER BY DPAM_ACCTNO,DPAM_SBA_NAME,CASE WHEN ORDER_BY='2' THEN '0' ELSE ORDER_BY END
 ,case  WHEN ORDER_BY='2' and TRANS_DESC ='CGST @9%' then 'S'
  WHEN ORDER_BY='2' and TRANS_DESC ='SGST @9%' then 'T'
   WHEN ORDER_BY='2' and TRANS_DESC ='IGST @18%' then'U'
    WHEN ORDER_BY='2' and TRANS_DESC ='UGST @9%' then 'V' 
    WHEN ORDER_BY='2' and left(TRANS_DESC ,1)='<' then 'Z' 
    else 'A' end  
    
  ,ISIN_NAME,CONVERT(DATETIME,TRANS_DATE),EXEDT,DPM_TRANS_NO,C_D_FLAG 
	END
    ELSE IF @@L_GRPMSTR_CD='Y'
    BEGIN
    PRINT '111'
	SELECT ORDER_BY,T.DPAM_ID,DPAM_SBA_NAME,DPAM_ACCTNO,                      
	CDSHM_TRATM_DESC= ISNULL(UPPER(LTRIM(RTRIM(TRANS_DESC))),''),              
	DPM_TRANS_NO,                      
	TRANS_DATE=CONVERT(VARCHAR(11),TRANS_DATE,109),                      
	T.ISIN_CD,          
	ISIN_NAME=ISNULL(ISIN_NAME,''),                      
	OPENING_BAL=REPLACE(CONVERT(VARCHAR,ISNULL(OPENING_BAL,0)),'.000',''),            
	DEBIT_QTY= CASE WHEN  QTY <= 0 THEN REPLACE(CONVERT(VARCHAR,ABS(QTY)),'.000','') ELSE '' END,                      
	CREDIT_QTY= CASE WHEN QTY > 0 THEN REPLACE(CONVERT(VARCHAR,ABS(QTY)),'.000','') ELSE '' END,
	CLOSING_BAL = REPLACE(CONVERT(VARCHAR,(ISNULL(OPENING_BAL,0) + ISNULL(QTY,0))),'.000',''),          
	CHARGE_VAL=ISNULL(CHARGE_VAL,0)  * -1,
	PREV_BILL_BAL=ISNULL(PREV_BILL_BAL,0),
	BILL_DUE_DT =@@BILLDUEDATE,
	TRANS_DATE,
	ISNULL(SETTM_ID,'') SETTM_ID, ISNULL(TR_SETTM_ID,'') TR_SETTM_ID,TRATM_CD,
VALUATION=CONVERT(NUMERIC(18,2),CONVERT(NUMERIC(18,3),CASE WHEN ORDER_BY = '3' THEN CITRUS_USR.FN_SPLITVAL_BY(TRANS_DESC,1,'|') ELSE '0' END )*ISNULL(CLOPM_CDSL_RT,0))  
	,RATE = ISNULL(CLOPM_CDSL_RT,0) --INTO BILL_ANGEL_18082015_new
	,isnull(inv_no  ,'') invoice_no
,isnull(cl_gst_no,'') GST_no
,isnull(SINGLELOC,'') Base_loc_service_cnt
,case when  isnull(cl_gst_no,'')  <> '' then 'Y' else 'N' end GST_no_YN 
	FROM #TEMPMAINCDSL T WITH(NOLOCK)
	left outer join bo_bill_inv_mapping on boid = dpam_acctno and month(trans_date) = billmonth and YEAR(trans_date)= billyear
left outer join (SELECT ENTR_SBA BOID,REPLACE(ENTM_SHORT_NAME,'_BL','') + '/' + STATE_CODE SINGLELOC
, CASE WHEN ISNULL(CITRUS_USR.FN_UCC_ENTP(ENTR_BR,'BL',''),'')<>'' THEN CITRUS_USR.FN_UCC_ENTP(ENTR_BR,'BL','') + '/' + STATE_CODE ELSE '' END  MULTLOC,STATE_CODE
, CITRUS_USR.FN_UCC_accp(dpam_id ,'CLIENT GST','')  cl_gst_no
 FROM ENTITY_RELATIONSHIP E,ENTITY_MSTR,TIN_MSTR , dp_Acct_mstr WHERE GETDATE() BETWEEN ENTR_FROM_DT AND ISNULL(ENTR_TO_DT,'DEC 31 2100')
AND ENTR_DUMMY5=ENTM_ID and DPAM_SBA_NO = ENTR_SBA 
AND REPLACE(ENTM_SHORT_NAME,'_BL','')=STATE_NAME) v on   v.boid=dpam_acctno
	LEFT OUTER JOIN  ISIN_MSTR I WITH(NOLOCK) ON T.ISIN_CD = I.ISIN_CD
LEFT OUTER JOIN CLOSING_PRICE_MSTR_CDSL ON T.ISIN_CD = CLOPM_ISIN_CD AND ISNULL(CLOPM_DT,'01/01/1900') = ( SELECT TOP 1 CLOPM_DT FROM CLOSING_PRICE_MSTR_CDSL WHERE CLOPM_ISIN_CD = T.ISIN_CD AND CLOPM_DT <= @PA_TODATE AND CLOPM_DELETED_IND = 1  ORDER BY CLOPM_DT DESC)

	LEFT OUTER JOIN #LEDGERBAL L ON T.DPAM_ID = L.DPAM_ID , GROUP_MSTR
	WHERE  DPAM_ACCTNO = GRP_CLIENT_CODE
	ORDER BY DPAM_ACCTNO,DPAM_SBA_NAME,CASE WHEN ORDER_BY='2' THEN '0' ELSE ORDER_BY END
	 ,case  WHEN ORDER_BY='2' and TRANS_DESC ='CGST @9%' then 'S'
  WHEN ORDER_BY='2' and TRANS_DESC ='SGST @9%' then 'T'
   WHEN ORDER_BY='2' and TRANS_DESC ='IGST @18%' then'U'
    WHEN ORDER_BY='2' and TRANS_DESC ='UGST @9%' then 'V' 
    WHEN ORDER_BY='2' and left(TRANS_DESC ,1)='<' then 'Z' 
    else 'A' end 
     ,ISIN_NAME,CONVERT(DATETIME,TRANS_DATE),EXEDT,DPM_TRANS_NO,C_D_FLAG  

    END

   TRUNCATE TABLE #TEMPMAINCDSL               
   TRUNCATE TABLE #LEDGERBAL

	DROP TABLE #TEMPMAINCDSL  
	DROP TABLE #LEDGERBAL 
    
 END                      
 ELSE                      
 BEGIN                
              
	SELECT @PA_PREVFROMDATE = MAX(DPDHMD_HOLDING_DT) FROM DP_DAILY_HLDG_NSDL WITH(NOLOCK) WHERE DPDHMD_HOLDING_DT < @PA_FROMDATE
           
   CREATE TABLE #TEMPMAINNSDL              
   (              
   TRANS_DATE DATETIME,              
   DPAM_ID BIGINT,              
   DPAM_ACCTNO VARCHAR(16),            
   DPAM_SBA_NAME VARCHAR(200),            
   ISIN_CD VARCHAR(12),
   SETT_TYPE VARCHAR(3),
   SETT_NO VARCHAR(10),              
   DPM_TRANS_NO BIGINT,              
   QTY NUMERIC(19,3),              
   BOOK_NARR_CD VARCHAR(3),              
   BOOK_TYPE VARCHAR(3),        
   BEN_CTGRY VARCHAR(2),        
   BEN_ACCT_TYPE VARCHAR(2),              
   TRANS_DESC VARCHAR(200),              
   FINAL_TRANS INT,          
   CHARGE_VAL NUMERIC(19,2),
   LINE_NO BIGINT              
   )              
                  
                 
 IF @PA_GROUP_CD <> ''      
 BEGIN                 
   INSERT INTO #TEMPMAINNSDL             
   SELECT DISTINCT NSDHM_TRANSACTION_DT,NSDHM_DPAM_ID,NSDHM_BEN_ACCT_NO,DPAM_SBA_NAME
  ,NSDHM_ISIN,NSDHM_SETT_TYPE,NSDHM_SETT_NO,CONVERT(NUMERIC,NSDHM_DPM_TRANS_NO),NSDHM_QTY,              
    NSDHM_BOOK_NAAR_CD,NSDHM_BOOK_TYPE,NSDHM_BEN_CTGRY,NSDHM_BEN_ACCT_TYPE,              
   TRANS_DESC= ISNULL(NSDHM_TRN_DESCP,'')      
   ,0          
   ,NSDHM_CHARGE,NSDHM_LN_NO               
   FROM NSDL_HOLDING_DTLS WITH(NOLOCK)  
    ,ACCOUNT_GROUP_MAPPING G WITH(NOLOCK)                       
   ,#ACLIST ACCOUNT                      
   WHERE           
   NSDHM_DPM_ID = @@DPMID                      
   AND NSDHM_TRANSACTION_DT >=@PA_FROMDATE AND NSDHM_TRANSACTION_DT <=@PA_TODATE                       
   AND ISNUMERIC(NSDHM_BEN_ACCT_NO) = 1                        
   AND CONVERT(NUMERIC,NSDHM_BEN_ACCT_NO) BETWEEN CONVERT(NUMERIC,@PA_FROMACCID) AND CONVERT(NUMERIC,@PA_TOACCID)                       
    AND G.DPAM_ID = NSDHM_DPAM_ID      
   AND GROUP_CD =  @PA_GROUP_CD     
   AND NSDHM_DPAM_ID = ACCOUNT.DPAM_ID                        
   AND (NSDHM_TRANSACTION_DT BETWEEN EFF_FROM AND EFF_TO) 
   AND LTRIM(RTRIM(NSDHM_TRASTM_CD)) <> ''        
 END  
 ELSE  
 BEGIN  
   INSERT INTO #TEMPMAINNSDL             
   SELECT DISTINCT NSDHM_TRANSACTION_DT,NSDHM_DPAM_ID,NSDHM_BEN_ACCT_NO,DPAM_SBA_NAME
   ,NSDHM_ISIN,NSDHM_SETT_TYPE,NSDHM_SETT_NO,CONVERT(NUMERIC,NSDHM_DPM_TRANS_NO),NSDHM_QTY,              
    NSDHM_BOOK_NAAR_CD,NSDHM_BOOK_TYPE,NSDHM_BEN_CTGRY,NSDHM_BEN_ACCT_TYPE,              
   TRANS_DESC= ISNULL(NSDHM_TRN_DESCP,'')      
   ,0          
   ,NSDHM_CHARGE,NSDHM_LN_NO              
   FROM NSDL_HOLDING_DTLS WITH(NOLOCK),                      
   #ACLIST ACCOUNT                      
   WHERE           
   NSDHM_DPM_ID = @@DPMID                      
   AND NSDHM_TRANSACTION_DT >=@PA_FROMDATE AND NSDHM_TRANSACTION_DT <=@PA_TODATE                       
   AND ISNUMERIC(NSDHM_BEN_ACCT_NO) = 1                        
   AND CONVERT(NUMERIC,NSDHM_BEN_ACCT_NO) BETWEEN CONVERT(NUMERIC,@PA_FROMACCID) AND CONVERT(NUMERIC,@PA_TOACCID)                       
   AND NSDHM_DPAM_ID = ACCOUNT.DPAM_ID                        
   AND (NSDHM_TRANSACTION_DT BETWEEN EFF_FROM AND EFF_TO)    
   AND LTRIM(RTRIM(NSDHM_TRASTM_CD)) <> ''           
 END         
                 

   	  
  --FOR NON POOL ACCOUNTS 
	
		  DELETE FROM #TEMPMAINNSDL WHERE BEN_ACCT_TYPE NOT IN('20','30','40') AND BOOK_NARR_CD IN ('031','032','041','043','053','054','055','056','057','061','076','073','074','075','095','098','099','121','123','124','153','156','163','173','183','193','201','203','213','101')               
		    
		  UPDATE M SET FINAL_TRANS = 1,SETT_TYPE='',SETT_NO=''             
		  FROM #TEMPMAINNSDL M            
		  WHERE BEN_ACCT_TYPE NOT IN('20','30','40') AND CONVERT(INT,M.BOOK_NARR_CD) = ISNULL((SELECT MAX(CONVERT(INT,BOOK_NARR_CD)) FROM #TEMPMAINNSDL M1 WHERE M.DPM_TRANS_NO = M1.DPM_TRANS_NO AND M.ISIN_CD = M1.ISIN_CD AND M.DPAM_ID = M1.DPAM_ID AND M.BEN_ACCT_TYPE = M1.BEN_ACCT_TYPE),0)            

			--ADDED FOR DEMAT & REMAT PENDING TRANSACTIONS 
			UPDATE #TEMPMAINNSDL SET FINAL_TRANS = 1,SETT_TYPE='',SETT_NO='' WHERE BEN_ACCT_TYPE IN('12','13') 
			--ADDED FOR DEMAT & REMAT PENDING TRANSACTIONS

	    --FOR NON POOL ACCOUNTS            
	
	     -- FOR POOL ACCOUNTS
		     DELETE FROM #TEMPMAINNSDL WHERE BEN_ACCT_TYPE IN('20','30','40') AND BOOK_NARR_CD IN ('031','032','041','043','053','054','055','056','057','061','076','073','074','075','095','098','099','121','123','124','153','156','163','173','183','193','201','203','213')
		
		     UPDATE #TEMPMAINNSDL SET FINAL_TRANS = 1 WHERE  BEN_ACCT_TYPE IN('20','30','40') AND  SETT_TYPE <> '00'



	     -- FOR POOL ACCOUNTS          
   IF @PA_HLDG_YN = 'Y'
   BEGIN              
	   IF @PA_TRANSCLIENTSONLY = 'Y'    
	   BEGIN                 
		 INSERT INTO #TEMPMAINNSDL              
		 SELECT @PA_PREVFROMDATE,DPDHMD_DPAM_ID,DPAM_SBA_NO,DPAM_SBA_NAME,DPDHMD_ISIN,DPDHMD_SETT_TYPE,DPDHMD_SETT_NO,NULL,SUM(DPDHMD_QTY),NULL,NULL,DPDHMD_BENF_CAT,DPDHMD_BENF_ACCT_TYP,'*',3,0,NULL              
		 FROM FN_DAILYHOLDING(@@DPMID,@PA_PREVFROMDATE,@PA_FROMACCID,@PA_TOACCID,'',@PA_GROUP_CD,@PA_LOGIN_PR_ENTM_ID,@@L_CHILD_ENTM_ID)            
		 WHERE EXISTS(SELECT DPAM_ID FROM #TEMPMAINNSDL WITH(NOLOCK) WHERE DPAM_ID = DPDHMD_DPAM_ID)  
     	 GROUP BY DPDHMD_DPAM_ID,DPAM_SBA_NO,DPAM_SBA_NAME,DPDHMD_ISIN,DPDHMD_SETT_TYPE,DPDHMD_SETT_NO,DPDHMD_BENF_CAT,DPDHMD_BENF_ACCT_TYP               
	   END    
	   ELSE    
	   BEGIN   
	   	
   		INSERT INTO #TEMPMAINNSDL              
		 SELECT @PA_PREVFROMDATE,DPDHMD_DPAM_ID,H.DPAM_SBA_NO,H.DPAM_SBA_NAME,DPDHMD_ISIN,DPDHMD_SETT_TYPE,DPDHMD_SETT_NO,NULL,SUM(DPDHMD_QTY),NULL,NULL,DPDHMD_BENF_CAT,DPDHMD_BENF_ACCT_TYP,'*',3,0,NULL              
		 FROM FN_DAILYHOLDING(@@DPMID,@PA_PREVFROMDATE,@PA_FROMACCID,@PA_TOACCID,'',@PA_GROUP_CD,@PA_LOGIN_PR_ENTM_ID,@@L_CHILD_ENTM_ID) H,#ACLIST A
		 WHERE DPDHMD_DPAM_ID = A.DPAM_ID  AND @PA_PREVFROMDATE BETWEEN EFF_FROM AND EFF_TO
		 GROUP BY DPDHMD_DPAM_ID,H.DPAM_SBA_NO,H.DPAM_SBA_NAME,DPDHMD_ISIN,DPDHMD_SETT_TYPE,DPDHMD_SETT_NO,DPDHMD_BENF_CAT,DPDHMD_BENF_ACCT_TYP    
	   END    
    END 
  
  IF @PA_GROUP_CD <> ''      
  BEGIN   
    INSERT INTO #TEMPMAINNSDL          
    SELECT CLIC_TRANS_DT=@PA_TODATE,CLIC_DPAM_ID,DPAM_SBA_NO,DPAM_SBA_NAME,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,CLIC_CHARGE_NAME,2,SUM(CLIC_CHARGE_AMT),NULL           
    FROM CLIENT_CHARGES_NSDL WITH(NOLOCK)  
    ,ACCOUNT_GROUP_MAPPING G WITH(NOLOCK)          
    , #ACLIST ACCOUNT             
    WHERE           
    CLIC_DPM_ID = @@DPMID                      
    AND CLIC_TRANS_DT >=@PA_FROMDATE AND CLIC_TRANS_DT <=@PA_TODATE                       
    AND CLIC_CHARGE_NAME <> 'TRANSACTION CHARGES'           
    AND ISNUMERIC(DPAM_SBA_NO) = 1                        
    AND CONVERT(NUMERIC,DPAM_SBA_NO) BETWEEN CONVERT(NUMERIC,@PA_FROMACCID) AND CONVERT(NUMERIC,@PA_TOACCID)                       
      AND G.DPAM_ID = CLIC_DPAM_ID      
    AND GROUP_CD =  @PA_GROUP_CD    
    AND CLIC_DPAM_ID = ACCOUNT.DPAM_ID                        
    AND (CLIC_TRANS_DT BETWEEN EFF_FROM AND EFF_TO)   
	GROUP BY CLIC_DPAM_ID,DPAM_SBA_NO,DPAM_SBA_NAME,CLIC_CHARGE_NAME         
 END  
 ELSE  
 BEGIN  
    INSERT INTO #TEMPMAINNSDL          
    SELECT CLIC_TRANS_DT=@PA_TODATE,CLIC_DPAM_ID,DPAM_SBA_NO,DPAM_SBA_NAME,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,CLIC_CHARGE_NAME,2,SUM(CLIC_CHARGE_AMT),NULL           
    FROM CLIENT_CHARGES_NSDL WITH(NOLOCK)         
    , #ACLIST ACCOUNT             
    WHERE           
    CLIC_DPM_ID = @@DPMID                      
    AND CLIC_TRANS_DT >=@PA_FROMDATE AND CLIC_TRANS_DT <=@PA_TODATE                       
    AND CLIC_CHARGE_NAME <> 'TRANSACTION CHARGES'           
    AND ISNUMERIC(DPAM_SBA_NO) = 1                        
    AND CONVERT(NUMERIC,DPAM_SBA_NO) BETWEEN CONVERT(NUMERIC,@PA_FROMACCID) AND CONVERT(NUMERIC,@PA_TOACCID)                       
    AND CLIC_DPAM_ID = ACCOUNT.DPAM_ID                        
    AND (CLIC_TRANS_DT BETWEEN EFF_FROM AND EFF_TO)    
	GROUP BY CLIC_DPAM_ID,DPAM_SBA_NO,DPAM_SBA_NAME,CLIC_CHARGE_NAME         
 END            



     -- FOR POOL ACCOUNTS
	     DELETE FROM #TEMPMAINNSDL WHERE BEN_ACCT_TYPE IN('20','30','40') AND ISNULL(SETT_TYPE,'') = '00'
     -- FOR POOL ACCOUNTS
     --FOR NON POOL ACCOUNTS 
       UPDATE #TEMPMAINNSDL SET SETT_TYPE='',SETT_NO='' WHERE FINAL_TRANS = 3 AND BEN_ACCT_TYPE NOT IN('20','30','40')
     --FOR NON POOL ACCOUNTS 
            
   CREATE TABLE #TEMPRUNNING              
   (  
   RUNNINGID BIGINT IDENTITY(1,1),              
   TRANS_DATE DATETIME,              
   DPAM_ID BIGINT,              
   DPAM_ACCTNO CHAR(16),            
   DPAM_SBA_NAME VARCHAR(200),            
   ISIN_CD VARCHAR(12),
   SETT_TYPE VARCHAR(3),
   SETT_NO VARCHAR(10),                 
   DPM_TRANS_NO VARCHAR(10),              
   QTY NUMERIC(19,3),              
   BOOK_NARR_CD VARCHAR(3),              
   BOOK_TYPE VARCHAR(3),        
   BEN_CTGRY VARCHAR(2),        
   BEN_ACCT_TYPE VARCHAR(2),              
   TRANS_DESC VARCHAR(200),              
   FINAL_TRANS INT,          
   CHARGE_VAL NUMERIC(19,2),
   LINE_NO BIGINT,  
   CLOSING_QTY NUMERIC(18,3)               
   )              
   CREATE INDEX IX_1 ON #TEMPRUNNING(DPAM_ID,BEN_CTGRY,BEN_ACCT_TYPE,ISIN_CD)                 
           
           
   
                       
   INSERT INTO #TEMPRUNNING   
   SELECT M.*,CLOSING_QTY=0.000              
   FROM #TEMPMAINNSDL M WITH(NOLOCK) WHERE FINAL_TRANS > 0              
   ORDER BY DPAM_ID,ISIN_CD,BEN_CTGRY,BEN_ACCT_TYPE,SETT_TYPE,SETT_NO,TRANS_DATE,LINE_NO,DPM_TRANS_NO,BOOK_NARR_CD
                 
                 
   UPDATE T               
   SET CLOSING_QTY = (SELECT SUM(ISNULL(QTY,0)) FROM #TEMPRUNNING T1 WITH(NOLOCK) WHERE T1.RUNNINGID <= T.RUNNINGID AND T1.DPAM_ID =T.DPAM_ID AND T1.BEN_CTGRY = T.BEN_CTGRY AND T1.BEN_ACCT_TYPE = T.BEN_ACCT_TYPE AND T1.ISIN_CD = T.ISIN_CD AND T1.SETT_TYPE=T.SETT_TYPE AND T1.SETT_NO = T.SETT_NO)          
   FROM #TEMPRUNNING T WITH(NOLOCK)             
            
            
   DELETE T FROM #TEMPRUNNING T WITH(NOLOCK)          
   WHERE EXISTS(SELECT DPAM_ID,ISIN_CD FROM #TEMPRUNNING T1 WITH(NOLOCK)          
   WHERE T.DPAM_ID = T1.DPAM_ID AND T1.BEN_CTGRY = T.BEN_CTGRY AND T1.BEN_ACCT_TYPE = T.BEN_ACCT_TYPE AND T.ISIN_CD = T1.ISIN_CD AND T1.TRANS_DESC <> '*')           
   AND T.TRANS_DESC='*'          


    SET @@SSQL ='INSERT INTO #LEDGERBAL
	SELECT DPAM_ID,SUM(CASE WHEN LDG_VOUCHER_TYPE = 5 AND LDG_VOUCHER_DT >= ''' + CONVERT(VARCHAR(11),@PA_FROMDATE,109) + ''' THEN 0 ELSE ISNULL(LDG_AMOUNT,0) * -1 END )
	FROM (
	SELECT DISTINCT DPAM_ID FROM #TEMPRUNNING
	) TMP LEFT OUTER JOIN LEDGER' + CONVERT(VARCHAR,@@LEDGERID) + ' ON DPAM_ID = LDG_ACCOUNT_ID AND LDG_ACCOUNT_TYPE = ''P'' AND LDG_VOUCHER_DT <= ''' + CONVERT(VARCHAR(11),@PA_TODATE,109) + ''' AND LDG_DELETED_IND = 1
	GROUP BY DPAM_ID'
	EXEC(@@SSQL)    
         
   SELECT FINAL_TRANS,T.DPAM_ID,DPAM_SBA_NAME,NSDHM_BEN_ACCT_NO=DPAM_ACCTNO,BEN_TYPE=LTRIM(RTRIM(ISNULL(BEN.DESCP,BEN_ACCT_TYPE) + ' ' + CASE WHEN SETT_TYPE <> '' THEN ISNULL(S.SETTM_DESC,SETT_TYPE) + '/' + SETT_NO ELSE '' END)),DPM_TRANS_NO=ISNULL(DPM_TRANS_NO,''),                      
   TRANS_DESC=LTRIM(RTRIM(ISNULL(TRANS_DESC,''))),              
   NSDHM_TRANSACTION_DT=CONVERT(VARCHAR(11),TRANS_DATE,109),                      
   NSDHM_ISIN=T.ISIN_CD,                      
   ISIN_NAME=ISNULL(ISIN_NAME,T.ISIN_CD),               
   OPEN_QTY = REPLACE(CONVERT(VARCHAR,(CASE WHEN FINAL_TRANS = 3 THEN CLOSING_QTY ELSE CLOSING_QTY - QTY END)),'.000',''),                    
   DEBIT_QTY= CASE WHEN QTY <= 0 THEN REPLACE(CONVERT(VARCHAR,ABS(QTY)),'.000','') ELSE '' END,                      
   CREDIT_QTY= CASE WHEN QTY > 0 THEN REPLACE(CONVERT(VARCHAR,ABS(QTY)),'.000','') ELSE '' END,                
   CLOSING_QTY= REPLACE(CONVERT(VARCHAR,CLOSING_QTY),'.000',''),          
   CHARGE_VAL= ISNULL(CHARGE_VAL,0)   * -1,
   PREV_BILL_BAL=ISNULL(PREV_BILL_BAL,0),
   BILL_DUE_DT =@@BILLDUEDATE,
   TRANS_DATE           
   FROM #TEMPRUNNING T WITH(NOLOCK) LEFT OUTER JOIN ISIN_MSTR I WITH(NOLOCK) ON T.ISIN_CD = I.ISIN_CD 
   LEFT OUTER JOIN SETTLEMENT_TYPE_MSTR S WITH(NOLOCK) ON T.SETT_TYPE = S.SETTM_TYPE AND ISNULL(S.SETTM_TYPE,'') <> ''  AND S.SETTM_DELETED_IND = 1          
   LEFT OUTER JOIN CITRUS_USR.FN_GETSUBTRANSDTLS('BEN_ACCT_TYPE_NSDL') BEN ON T.BEN_ACCT_TYPE = BEN.CD , #LEDGERBAL L   
   WHERE T.DPAM_ID= L.DPAM_ID                    
   ORDER BY DPAM_ACCTNO,FINAL_TRANS,ISIN_NAME,RUNNINGID,18          
    

   TRUNCATE TABLE #TEMPMAINNSDL    
   TRUNCATE TABLE #TEMPRUNNING               
   TRUNCATE TABLE #LEDGERBAL 
   DROP TABLE #TEMPMAINNSDL    
   DROP TABLE #TEMPRUNNING               
   DROP TABLE #LEDGERBAL
              
              
                        
 END                      
     
      TRUNCATE TABLE #ACLIST
	  DROP TABLE #ACLIST                  
END

GO
