-- Object: TABLE citrus_usr.tempdataaccd
-- Server: 10.253.78.167 | DB: DMAT
--------------------------------------------------

CREATE TABLE [citrus_usr].[tempdataaccd]
(
    [ACCD_CLISBA_ID] NUMERIC(10, 0) NOT NULL,
    [ACCD_ACCT_NO] VARCHAR(25) NOT NULL,
    [ACCD_ACCT_TYPE] VARCHAR(20) NOT NULL,
    [ACCD_ACCDOCM_DOC_ID] NUMERIC(10, 0) NOT NULL,
    [ACCD_VALID_YN] SMALLINT NOT NULL,
    [ACCD_REMARKS] VARCHAR(250) NULL,
    [ACCD_DOC_PATH] VARCHAR(200) NOT NULL,
    [ACCD_CREATED_BY] VARCHAR(25) NOT NULL,
    [ACCD_CREATED_DT] DATETIME NOT NULL,
    [ACCD_LST_UPD_BY] VARCHAR(25) NOT NULL,
    [ACCD_LST_UPD_DT] DATETIME NOT NULL,
    [ACCD_DELETED_IND] SMALLINT NOT NULL,
    [ACCD_BINARY_IMAGE] VARBINARY(MAX) NULL
);

GO
