-- Object: PROCEDURE citrus_usr.PR_UPD_AUTOBANKRECO_091010
-- Server: 10.253.78.167 | DB: DMAT
--------------------------------------------------

--BEGIN TRAN
--EXEC [PR_UPD_AUTOBANKRECO] 1,''
--ROLLBACK

CREATE PROCEDURE [citrus_usr].[PR_UPD_AUTOBANKRECO_091010]
(
 @PA_FINID NUMERIC,
 @PA_OUTPUT VARCHAR(1000) OUTPUT 
)
AS
BEGIN
DECLARE 
  @P_SQL VARCHAR(8000),
  @P_SQL1 VARCHAR(8000),
  @P_COUNT INT,
  @P_COUNT1 INT
    
  SET @P_SQL = ''
  SET @P_SQL1 = ''
  SET @P_COUNT = 0
  SET @P_COUNT1 = 0

  CREATE TABLE #AKHIL
  ( TOT NUMERIC ) 
 
  BEGIN TRY 
   SELECT @P_COUNT1 = COUNT(1) FROM TMP_AUTORECO_MSTR 
   IF @P_COUNT1 = 0
   BEGIN  
     SELECT 'TEMP TABLE IS EMPTY' AS [REPLY MESSAGE]
   END
   ELSE
   BEGIN
   BEGIN TRANSACTION        

   SET @P_SQL = @P_SQL + ' UPDATE L
					SET L.LDG_BANK_CL_DATE = A.TRNS_DT
					FROM LEDGER'+CONVERT(VARCHAR,@PA_FINID)+ ' L,
					(SELECT LDG_VOUCHER_TYPE, LDG_VOUCHER_NO, TRNS_DT, LDG_BANK_CL_DATE, LDG_INSTRUMENT_NO , CHQ_NO
					FROM LEDGER'+CONVERT(VARCHAR,@PA_FINID)+ ', TMP_AUTORECO_MSTR 
					WHERE LDG_INSTRUMENT_NO = CHQ_NO)A
					WHERE A.LDG_VOUCHER_TYPE = L.LDG_VOUCHER_TYPE AND A.LDG_VOUCHER_NO = L.LDG_VOUCHER_NO '
 
   EXEC (@P_SQL)

   SET @P_SQL1 = @P_SQL1 + ' INSERT INTO #AKHIL SELECT COUNT(1) FROM TMP_AUTORECO_MSTR WHERE CHQ_NO NOT IN 
							 (SELECT LDG_INSTRUMENT_NO FROM LEDGER'+CONVERT(VARCHAR,@PA_FINID)+ ' 
							  WHERE LDG_INSTRUMENT_NO IS NOT NULL AND LDG_INSTRUMENT_NO <> '''')'
		  
   EXEC (@P_SQL1)

   SELECT @P_COUNT = TOT FROM #AKHIL   
 
   IF @P_COUNT = 0
     BEGIN 
        SELECT 'ALL CHEQUE DETAILS ARE UPDATED' AS [REPLY MESSAGE]
     END   
   ELSE
     BEGIN 
        SET @P_SQL1 = @P_SQL1 + ' SELECT * FROM TMP_AUTORECO_MSTR WHERE CHQ_NO NOT IN 
							 (SELECT LDG_INSTRUMENT_NO FROM LEDGER'+CONVERT(VARCHAR,@PA_FINID)+ ' 
							  WHERE LDG_INSTRUMENT_NO IS NOT NULL AND LDG_INSTRUMENT_NO <> '''')'
		  

        EXEC (@P_SQL1)
     END
   COMMIT TRANSACTION  
   END
  END TRY 
  BEGIN CATCH 
   
       ROLLBACK TRANSACTION         
       SELECT  ERROR_MESSAGE() AS [ERRORMESSAGE]

  END CATCH 

         
  
END

GO
