-- Object: TABLE citrus_usr.ALLOWED_SIGNATORY
-- Server: 10.253.78.167 | DB: DMAT
--------------------------------------------------

CREATE TABLE [citrus_usr].[ALLOWED_SIGNATORY]
(
    [ALWD_ID] NUMERIC(10, 0) NOT NULL,
    [ALWD_SIGN_NAME] VARCHAR(40) NOT NULL,
    [ALWD_SIGN_EMAIL] VARCHAR(100) NULL,
    [ALWD_FROM_DT] DATETIME NOT NULL,
    [ALWD_TO_DT] DATETIME NOT NULL,
    [ALWD_DPM_DPID] VARCHAR(25) NOT NULL,
    [ALWD_USER_NAME] VARCHAR(50) NOT NULL,
    [ALWD_CREATED_BY] VARCHAR(25) NOT NULL,
    [ALWD_CREATED_DT] DATETIME NOT NULL,
    [ALWD_LST_UPD_BY] VARCHAR(25) NOT NULL,
    [ALWD_LST_UPD_DT] DATETIME NOT NULL,
    [ALWD_DELETED_IND] SMALLINT NOT NULL
);

GO
