-- Object: TABLE citrus_usr.ADDR_ACCT_MAK
-- Server: 10.253.78.167 | DB: DMAT
--------------------------------------------------

CREATE TABLE [citrus_usr].[ADDR_ACCT_MAK]
(
    [ADRM_ID] NUMERIC(10, 0) NOT NULL,
    [ADR_CLISBA_ID] NUMERIC(10, 0) NOT NULL,
    [ADR_ACCT_NO] VARCHAR(25) NULL,
    [ADR_ACCT_TYPE] VARCHAR(20) NOT NULL,
    [ADR_CONCM_ID] NUMERIC(10, 0) NOT NULL,
    [ADR_CONCM_CD] VARCHAR(20) NOT NULL,
    [ADR_ID] NUMERIC(10, 0) NOT NULL,
    [ADR_1] VARCHAR(55) NULL,
    [ADR_2] VARCHAR(55) NULL,
    [ADR_3] VARCHAR(55) NULL,
    [ADR_CITY] VARCHAR(50) NULL,
    [ADR_STATE] VARCHAR(50) NULL,
    [ADR_COUNTRY] VARCHAR(50) NULL,
    [ADR_ZIP] VARCHAR(50) NULL,
    [ADR_CREATED_BY] VARCHAR(25) NOT NULL,
    [ADR_CREATED_DT] DATETIME NOT NULL,
    [ADR_LST_UPD_BY] VARCHAR(25) NOT NULL,
    [ADR_LST_UPD_DT] DATETIME NOT NULL,
    [ADR_DELETED_IND] SMALLINT NOT NULL
);

GO
