-- Object: TABLE citrus_usr.FILEGEN_FORANGELID_holding_MIMANSA
-- Server: 10.253.78.167 | DB: DMAT
--------------------------------------------------

CREATE TABLE [citrus_usr].[FILEGEN_FORANGELID_holding_MIMANSA]
(
    [BOID] VARCHAR(200) NULL,
    [ISIN_CD] VARCHAR(100) NULL,
    [ISIN_NAME] VARCHAR(200) NULL,
    [FREEZE_QTY] MONEY NULL,
    [PLEDGE_QTY] MONEY NULL,
    [FREE_QTY] MONEY NULL,
    [LOCKIN_QTY] MONEY NULL,
    [FILLER0] MONEY NULL,
    [DPHMCD_DEMAT_PND_VER_QTY] MONEY NULL,
    [FILLER1] MONEY NULL,
    [FILLER2] MONEY NULL,
    [FILLER3] MONEY NULL,
    [FILLER4] MONEY NULL,
    [CLOSINGRATE] MONEY NULL
);

GO
