-- Object: TABLE citrus_usr.Delete_Suresh_DP_Trx_UCC
-- Server: 10.253.78.167 | DB: DMAT
--------------------------------------------------

CREATE TABLE [citrus_usr].[Delete_Suresh_DP_Trx_UCC]
(
    [boid] CHAR(16) NULL,
    [cm_acc_closuredate] VARCHAR(8) NULL,
    [cm_acctype] VARCHAR(2) NULL,
    [cm_active] VARCHAR(20) NOT NULL,
    [cm_add1] VARCHAR(30) NOT NULL,
    [cm_add2] VARCHAR(30) NOT NULL,
    [cm_add3] VARCHAR(30) NOT NULL,
    [cm_bankname] VARCHAR(8000) NOT NULL,
    [cm_blsavingcd] VARCHAR(20) NOT NULL,
    [cm_bostatementcycle] CHAR(2) NULL,
    [cm_brboffcode] VARCHAR(8000) NULL,
    [cm_brcode] VARCHAR(8000) NOT NULL,
    [cm_cd] VARCHAR(20) NULL,
    [cm_chgsscheme] VARCHAR(200) NULL,
    [cm_city] VARCHAR(25) NOT NULL,
    [cm_clienttype] VARCHAR(4) NULL,
    [cm_country] VARCHAR(25) NOT NULL,
    [cm_dateofbirth] VARCHAR(8) NULL,
    [cm_divbankacno] VARCHAR(50) NULL,
    [cm_divbankccy] VARCHAR(100) NULL,
    [cm_divbankcode] VARCHAR(12) NULL,
    [cm_divbranchno] VARCHAR(2) NOT NULL,
    [cm_dpintrefno] VARCHAR(20) NULL,
    [cm_email] CHAR(50) NULL,
    [cm_lastname] CHAR(20) NULL,
    [cm_micr] VARCHAR(12) NULL,
    [cm_middlename] CHAR(20) NULL,
    [cm_mobile] VARCHAR(17) NULL,
    [cm_name] VARCHAR(150) NULL,
    [cm_occupation] CHAR(4) NULL,
    [cm_opendate] VARCHAR(8) NULL,
    [cm_pin] VARCHAR(10) NOT NULL,
    [cm_poaforpayin] VARCHAR(1) NOT NULL,
    [cm_poaregdate] VARCHAR(8) NOT NULL,
    [cm_productcd] VARCHAR(30) NULL,
    [cm_sech_name] VARCHAR(142) NULL,
    [cm_state] VARCHAR(25) NOT NULL,
    [cm_tele1] VARCHAR(17) NULL,
    [cm_thih_name] VARCHAR(142) NULL,
    [cm_title] VARCHAR(1) NOT NULL,
    [IS POA] VARCHAR(1) NOT NULL,
    [Master POA ID] CHAR(16) NOT NULL,
    [cm_freezedt] VARCHAR(8000) NULL,
    [cm_freezereason] VARCHAR(200) NOT NULL,
    [cm_freezeyn] VARCHAR(1) NOT NULL,
    [cb_add1] VARCHAR(30) NOT NULL,
    [cb_add2] VARCHAR(30) NOT NULL,
    [cb_add3] VARCHAR(30) NOT NULL,
    [cb_annualincome] VARCHAR(100) NULL,
    [cb_bankadd1] VARCHAR(30) NOT NULL,
    [cb_bankadd2] VARCHAR(30) NOT NULL,
    [cb_bankadd3] VARCHAR(30) NOT NULL,
    [cb_bankbranch] VARCHAR(200) NULL,
    [cb_bosettlementplanflag] CHAR(1) NULL,
    [cb_city] VARCHAR(25) NOT NULL,
    [cb_cmcd] VARCHAR(20) NULL,
    [cb_country] VARCHAR(25) NOT NULL,
    [cb_degree] CHAR(4) NULL,
    [cb_dividendcurrency] VARCHAR(1) NOT NULL,
    [cb_fathername] VARCHAR(50) NULL,
    [cb_formno] VARCHAR(20) NULL,
    [cb_geographical] CHAR(4) NULL,
    [cb_language] VARCHAR(100) NULL,
    [cb_lifestyle] VARCHAR(1) NOT NULL,
    [cb_nationality] CHAR(3) NULL,
    [cb_nominee] VARCHAR(142) NULL,
    [cb_nominee_dob] VARCHAR(8) NULL,
    [cb_nomineeadd1] VARCHAR(30) NULL,
    [cb_nomineeadd2] VARCHAR(30) NULL,
    [cb_nomineeadd3] VARCHAR(30) NULL,
    [cb_nomineecity] VARCHAR(25) NULL,
    [cb_nomineecountry] VARCHAR(25) NULL,
    [cb_nomineepin] VARCHAR(10) NULL,
    [cb_nomineestate] VARCHAR(25) NULL,
    [cb_panno] VARCHAR(25) NULL,
    [cb_pin] VARCHAR(10) NOT NULL,
    [cb_sechfathername] VARCHAR(50) NULL,
    [cb_sechlastname] VARCHAR(20) NULL,
    [cb_sechmiddle] VARCHAR(20) NULL,
    [cb_sechpanno] VARCHAR(25) NULL,
    [cb_sechtitle] VARCHAR(1) NOT NULL,
    [cb_setupdate] VARCHAR(1) NOT NULL,
    [cb_sexcode] CHAR(1) NOT NULL,
    [cb_state] VARCHAR(25) NOT NULL,
    [cb_tele1] VARCHAR(17) NULL,
    [cb_thirdfathername] VARCHAR(50) NULL,
    [cb_thirdlastname] VARCHAR(20) NULL,
    [cb_thirdmiddle] VARCHAR(20) NULL,
    [cb_thirdpanno] VARCHAR(25) NULL,
    [cb_thirdtitle] VARCHAR(1) NOT NULL,
    [cb_voicemail] VARCHAR(20) NULL,
    [Last_Modified_Date] DATETIME NULL,
    [sClientID] NUMERIC(16, 0) NULL,
    [sPartyCode] VARCHAR(10) NULL,
    [sClientName] VARCHAR(100) NULL,
    [sBrid] VARCHAR(10) NULL,
    [sClientType] VARCHAR(10) NULL,
    [sMobile] VARCHAR(50) NULL,
    [sEmailID] VARCHAR(100) NULL,
    [sSEBIDebar] DATETIME NULL,
    [sDPFreeze] VARCHAR(8) NULL,
    [sDPClosure] VARCHAR(8) NULL,
    [sTransaction] VARCHAR(1) NULL,
    [sValuation_First] MONEY NULL,
    [sValuation_Last] MONEY NULL,
    [sVariation] MONEY NULL,
    [sDateTime] DATETIME NULL,
    [sProduct] VARCHAR(10) NULL,
    [BoMoblie] VARCHAR(50) NULL
);

GO
