-- Object: TABLE citrus_usr.NSDL_DPM_RESPONSE
-- Server: 10.253.78.167 | DB: DMAT
--------------------------------------------------

CREATE TABLE [citrus_usr].[NSDL_DPM_RESPONSE]
(
    [NSDL_ACCT_ID] VARCHAR(16) NULL,
    [NSDL_LINE_NO] VARCHAR(20) NULL,
    [NSDL_BATCHNO] VARCHAR(20) NULL,
    [NSDL_CREATED_BY] VARCHAR(20) NULL,
    [NSDL_CREATED_DT] VARCHAR(11) NULL,
    [NSDL_LST_UPD_BY] VARCHAR(20) NULL,
    [NSDL_LST_UPD_DT] VARCHAR(11) NULL,
    [NSDL_DELETED_IND] INT NULL
);

GO
