-- Object: VIEW citrus_usr.MF_VIEW_25102016
-- Server: 10.253.78.167 | DB: DMAT
--------------------------------------------------

CREATE VIEW [citrus_usr].[MF_VIEW_25102016]
AS
SELECT  NISE_PARTY_CODE AS CLIENT_CODE,FIRST_HOLD_NAME AS ClientName,
FIRST_HOLD_ADD1 AS ADDRESS1,FIRST_HOLD_ADD2 AS ADDRESS2,FIRST_HOLD_ADD3 AS ADDRESS3,FIRST_HOLD_ADD4 AS CITY,
CONVERT(VARCHAR(15),'NA') AS OtherCity,FIRST_HOLD_STATE State,CONVERT(VARCHAR(15),'') OtherState,FIRST_HOLD_CNTRY AS Country,
CONVERT(VARCHAR(15),'NA') AS OtherCountry,FIRST_HOLD_PIN PinCode,EMAIL_ADD AS EMAILID,
'NA'OfficePhoneNo,'NA'	OfficeExtensionNo,'NA'	OfficeFaxNo,FIRST_HOLD_PHONE	HomePhonoNo,'NA'HomeFaxNo, FIRST_HOLD_MOBILE MobileNo,T.Description Occupation,
I.Description AnnualIncome,DIVIDEND_ACCOUNT_NO AccountNo,(CASE WHEN BANK_ACCOUNT_TYPE='10' THEN 'SAVINGS' ELSE 'CURRENT' END)	AccountType,
BANK_NAME BANKNAME,BANK_ADD1 BankBranch,''BankBranchCode,''BankCity,C.TYPE AS PersonalStatus,''TaxStatus,Category,'CDSL'DepositoryName,
'ANGEL BROKING PVT LTD' DPName ,'12032000'	DPID,CLIENT_CODE BeneficiaryAccountNo,SECOND_HOLD_NAME SecondAppName,THIRD_HOLD_NAME ThirdAppName,BO_DOB DOB1,
'' DOB2,''	DOB3,FIRST_HOLD_PAN PANNo1,SECOND_HOLD_ITPAN PANNo2,THIRD_HOLD_ITPAN PANNo3,
''MINNo1,''	MINNo2,''	MINNo3,'NA'EcsNo,'NA' UINNo,FIRST_HOLD_FNAME Father_HusbandName,
LTRIM(RTRIM(ISNULL(DPHD_GAU_FNAME,'')))+' '+LTRIM(RTRIM(ISNULL(DPHD_GAU_MNAME,'')))+' ' +LTRIM(RTRIM(ISNULL(DPHD_GAU_LNAME,''))) GuardianName,
'' GuardianRelationship, DPHD_GAU_DOB	GuardianDOB,DPHD_GAU_PAN_NO	GaurdianPANNo,''	GaurdianMINNo,
LTRIM(RTRIM(ISNULL(DPHD_NOM_FNAME,'')))+' '+LTRIM(RTRIM(ISNULL(DPHD_NOM_MNAME,'')))+' ' +LTRIM(RTRIM(ISNULL(DPHD_NOM_LNAME,''))) NomineeName,
''	NomineeRelation,''	NomineeDOB,(CASE WHEN ISNULL(POA_VER,'') IN (2,1) THEN 'Y' ELSE 'N' END)POA,''SubBroker,''	CreatedBy,ACTIVE_DATE CreatedOn,''	LastModifiedBy,''	LastModifiedOn,
BRANCH_CODE	BranchID,'NA'OtherBankName,'NA'	BankCode,BO_BRANCH_NO	IFSCCODE,'Y'	KYCflag
FROM TBL_CLIENT_MASTER 	 C
LEFT OUTER JOIN 
DP_HOLDER_DTLS ON CLIENT_CODE =DPHD_DPAM_SBA_NO 
LEFT OUTER JOIN 
TYPE_MASTER T ON T.CODE= PROFESSION_CODE AND T.TYPE ='OCCUPATION'
LEFT OUTER JOIN 
TYPE_MASTER I ON I.CODE= INCOME_CODE AND I.TYPE ='INCOME'
WHERE STATUS ='ACTIVE' 
and NISE_PARTY_CODE IN ('V49038',
'A85012',
'KOLK9200',
'K50251',
'NOR317',
'K46795',
'P14438',
'R47022',
'R6540',
'A23214',
'K17733',
'M53706',
'H10651',
'A99423',
'S158131',
'R68750',
'VL002',
'VL001',
'J41740',
'V45643'
)

GO
