-- Object: TABLE citrus_usr.TBL_OFFMARKETREASON
-- Server: 10.253.78.167 | DB: DMAT
--------------------------------------------------

CREATE TABLE [citrus_usr].[TBL_OFFMARKETREASON]
(
    [TBLOMR_SLIPNO] VARCHAR(50) NULL,
    [TBLOMR_REMARKS] VARCHAR(100) NULL,
    [TBLOMR_CREATED_BY] VARCHAR(100) NULL,
    [TBLOMR_CREATED_DT] DATETIME NULL,
    [TBLOMR_LST_UPD_BY] VARCHAR(100) NULL,
    [TBLOMR_LST_UPD_DT] DATETIME NULL,
    [TBLOMR_DELETED_IND] SMALLINT NULL
);

GO
