-- Object: PROCEDURE citrus_usr.PR_OTP_MSTR
-- Server: 10.253.78.167 | DB: DMAT
--------------------------------------------------


create PROCEDURE [citrus_usr].[PR_OTP_MSTR]( 
@PA_LOGIN_NAMES VARCHAR(20)
,@PA_SBA_NO  VARCHAR(20) 
,@PA_MOB VARCHAR(12)
,@PA_TXTSERIAL VARCHAR(20)
,@PA_OTPNO VARCHAR(6)
,@PA_ACTION VARCHAR(20)
, @PA_OUTPUT  VARCHAR(8000) OUTPUT  
                       )  
AS  
--  
--  
BEGIN 
IF @PA_ACTION='INS'
BEGIN
INSERT INTO OTP_MSTR (OTP_TYPE,OTP_MOBILE,OTP_BOID,OTP_CTR_BOID,OTP_NO,OTP_INTREFNO,OTP_CREATED_BY,OTP_CREATED_DT,OTP_LST_UPD_BY,OTP_LST_UPD_DT,OTP_DELETED_IND)
SELECT 'T',@PA_MOB,@PA_SBA_NO,'',@PA_OTPNO,@PA_TXTSERIAL,@PA_LOGIN_NAMES,GETDATE(),@PA_LOGIN_NAMES,GETDATE(),1
WHERE NOT EXISTS (SELECT OTP_INTREFNO FROM OTP_MSTR WHERE OTP_INTREFNO=@PA_TXTSERIAL)
END 
IF @PA_ACTION='UPD'
BEGIN
UPDATE OTP_MSTR SET OTP_NO=@PA_OTPNO,OTP_LST_UPD_DT=GETDATE() WHERE OTP_INTREFNO=@PA_TXTSERIAL
END

END

GO
