-- Object: PROCEDURE citrus_usr.PR_IMP_PEND_DRF
-- Server: 10.253.78.167 | DB: DMAT
--------------------------------------------------


--CREATE TABLE TBL_PENDING_DRF
--(SRNO			NUMERIC IDENTITY(1,1),
-- COMPNM			VARCHAR(100),
-- ISIN			VARCHAR(15),
-- REQ			NUMERIC,
-- TOT_PEND_REQ	NUMERIC,
-- PEND_REQ_30	NUMERIC(18,5),
-- CREATED_DT		DATETIME,
-- CREATED_BY		VARCHAR(20)
--)

--select * from TBL_PENDING_DRF

create PROCEDURE [citrus_usr].[PR_IMP_PEND_DRF](@PA_COMPM_NM VARCHAR(100),
								@PA_ISIN VARCHAR(15),
								@PA_REQ NUMERIC,
								@PA_TOT_REQ NUMERIC,
								@PA_PEND_REQ30 NUMERIC(18,5),
								@PA_LOGIN_NAME VARCHAR(20))
AS
BEGIN 
	IF NOT EXISTS (SELECT ISIN FROM TBL_PENDING_DRF WHERE REQ=@PA_REQ AND TOT_PEND_REQ = @PA_TOT_REQ AND PEND_REQ_30 = @PA_PEND_REQ30 and ISIN = @PA_ISIN)
	BEGIN
		INSERT INTO TBL_PENDING_DRF 
		VALUES (@PA_COMPM_NM,@PA_ISIN,@PA_REQ,@PA_TOT_REQ,@PA_PEND_REQ30,GETDATE(),@PA_LOGIN_NAME)
	END
END

GO
