-- Object: TABLE citrus_usr.SETT_MSTR
-- Server: 10.253.78.167 | DB: DMAT
--------------------------------------------------

CREATE TABLE [citrus_usr].[SETT_MSTR]
(
    [SETM_EXCH] VARCHAR(20) NOT NULL,
    [SETM_SEGMENT] VARCHAR(20) NOT NULL,
    [SETM_SETT_TYPE] VARCHAR(10) NOT NULL,
    [SETM_SETT_NO] VARCHAR(10) NOT NULL,
    [SETM_START_DATE] DATETIME NOT NULL,
    [SETM_END_DATE] DATETIME NOT NULL,
    [SETM_FUNDS_PAYIN] DATETIME NOT NULL,
    [SETM_FUNDS_PAYOUT] DATETIME NOT NULL,
    [SETM_SEC_PAYIN] DATETIME NOT NULL,
    [SETM_SEC_PAYOUT] DATETIME NOT NULL,
    [SETM_SETT_MERGE] DATETIME NULL,
    [SETM_SETT_ACTIVE] VARCHAR(1) NULL,
    [SETM_SETT_SPECIAL] VARCHAR(1) NULL,
    [SETM_CREATED_BY] VARCHAR(25) NOT NULL,
    [SETM_CREATED_DT] DATETIME NOT NULL,
    [SETM_LST_UPD_BY] VARCHAR(25) NOT NULL,
    [SETM_LST_UPD_DT] DATETIME NOT NULL,
    [SETM_DELETED_IND] SMALLINT NOT NULL
);

GO
