-- Object: TABLE citrus_usr.CONC_ACCT_MAK
-- Server: 10.253.78.167 | DB: DMAT
--------------------------------------------------

CREATE TABLE [citrus_usr].[CONC_ACCT_MAK]
(
    [CONCMAK_ID] NUMERIC(10, 0) NOT NULL,
    [CONC_CLISBA_ID] NUMERIC(10, 0) NOT NULL,
    [CONC_ACCT_NO] VARCHAR(25) NULL,
    [CONC_ACCT_TYPE] VARCHAR(20) NOT NULL,
    [CONC_CONCM_ID] NUMERIC(10, 0) NOT NULL,
    [CONC_CONCM_CD] VARCHAR(20) NOT NULL,
    [CONC_ID] NUMERIC(10, 0) NOT NULL,
    [CONC_VALUE] VARCHAR(50) NOT NULL,
    [CONC_CREATED_BY] VARCHAR(25) NOT NULL,
    [CONC_CREATED_DT] DATETIME NOT NULL,
    [CONC_LST_UPD_BY] VARCHAR(25) NOT NULL,
    [CONC_LST_UPD_DT] DATETIME NOT NULL,
    [CONC_DELETED_IND] SMALLINT NOT NULL
);

GO
