-- Object: TABLE citrus_usr.EXCH_SEG_MSTR_MAK
-- Server: 10.253.78.167 | DB: DMAT
--------------------------------------------------

CREATE TABLE [citrus_usr].[EXCH_SEG_MSTR_MAK]
(
    [EXCSM_ID] NUMERIC(10, 0) NOT NULL,
    [EXCSM_COMPM_ID] NUMERIC(10, 0) NOT NULL,
    [EXCSM_EXCH_CD] VARCHAR(20) NOT NULL,
    [EXCSM_SEG_CD] VARCHAR(20) NOT NULL,
    [EXCSM_SUB_SEG_CD] VARCHAR(20) NOT NULL,
    [EXCSM_DESC] VARCHAR(20) NOT NULL,
    [EXCSM_PARENT_ID] NUMERIC(10, 0) NULL,
    [EXCSM_RMKS] VARCHAR(250) NULL,
    [EXCSM_CREATED_BY] VARCHAR(25) NOT NULL,
    [EXCSM_CREATED_DT] DATETIME NOT NULL,
    [EXCSM_LST_UPD_BY] VARCHAR(25) NOT NULL,
    [EXCSM_LST_UPD_DT] DATETIME NOT NULL,
    [EXCSM_DELETED_IND] SMALLINT NOT NULL,
    [excsm_bit] INT NULL
);

GO
