-- Object: TABLE citrus_usr.b_23
-- Server: 10.253.78.167 | DB: DMAT
--------------------------------------------------

CREATE TABLE [citrus_usr].[b_23]
(
    [ACCP_ID] NUMERIC(10, 0) NOT NULL,
    [ACCP_CLISBA_ID] NUMERIC(10, 0) NOT NULL,
    [ACCP_ACCT_NO] VARCHAR(25) NOT NULL,
    [ACCP_ACCT_TYPE] VARCHAR(20) NOT NULL,
    [ACCP_ACCPM_PROP_CD] VARCHAR(20) NOT NULL,
    [ACCP_ACCPM_PROP_ID] NUMERIC(10, 0) NOT NULL,
    [ACCP_VALUE] VARCHAR(100) NOT NULL,
    [ACCP_CREATED_BY] VARCHAR(25) NOT NULL,
    [ACCP_CREATED_DT] DATETIME NOT NULL,
    [ACCP_LST_UPD_BY] VARCHAR(25) NOT NULL,
    [ACCP_LST_UPD_DT] DATETIME NOT NULL,
    [ACCP_DELETED_IND] SMALLINT NOT NULL
);

GO
