-- Object: PROCEDURE citrus_usr.PR_AUTOECNFLAG_BYANGELTBL
-- Server: 10.253.78.167 | DB: DMAT
--------------------------------------------------


CREATE PROCEDURE PR_AUTOECNFLAG_BYANGELTBL
(
@PA_LOGINNAMES VARCHAR(30)
)
AS

BEGIN

SELECT DISTINCT ACCP_VALUE FROM ACCOUNT_PROPERTIES ,DP_ACCT_MSTR , ANAND1.MSAJAG.DBO.EMAIL_API WHERE ACCP_ACCPM_PROP_CD='ECN_FLAG'
AND ACCP_DELETED_IND=1  AND DPAM_ID=ACCP_CLISBA_ID AND ACCP_DELETED_IND=1
AND DPAM_BBO_CODE=CL_CODE AND EXCHANGE='DPID' AND STATUS='0'

--Update T set t.ACCP_VALUE='YES' FROM ACCOUNT_PROPERTIES T ,DP_ACCT_MSTR , ANAND1.MSAJAG.DBO.EMAIL_API WHERE ACCP_ACCPM_PROP_CD='ECN_FLAG'
--AND ACCP_DELETED_IND=1  AND DPAM_ID=ACCP_CLISBA_ID AND ACCP_DELETED_IND=1
--AND DPAM_BBO_CODE=CL_CODE AND EXCHANGE='DPID' AND STATUS='0'


--Update V set v.status='1' FROM ACCOUNT_PROPERTIES X ,DP_ACCT_MSTR , ANAND1.MSAJAG.DBO.EMAIL_API V WHERE ACCP_ACCPM_PROP_CD='ECN_FLAG'
--AND ACCP_DELETED_IND=1  AND DPAM_ID=ACCP_CLISBA_ID AND ACCP_DELETED_IND=1
--AND DPAM_BBO_CODE=CL_CODE AND EXCHANGE='DPID' AND STATUS='0' 



END

GO
