-- Object: PROCEDURE dbo.RPT_ACC_TRIALBALANCE
-- Server: 10.253.33.91 | DB: ACCOUNTSLBS
--------------------------------------------------



CREATE PROCEDURE [dbo].[RPT_ACC_TRIALBALANCE]    

	@VDT VARCHAR(11),               /* AS ON DATE ENTERED BY USER */    
	@FLAG VARCHAR(15),              /* SORT ORDER FOR REPORT - CODEWISE OR NAMEWISE */    
	@VIEWOPTION VARCHAR(10),        /* OPTIONS FOR ACCOUNTS SELECTION - ALL, GL, PARTY */    
	@BALANCE VARCHAR(10),           /* NORMAL OR WITHOPBAL */    
	@STDATE VARCHAR(11),            /* START DATE ENTERED BY USER */    
	@CURRYRSTDATE VARCHAR(11), /* START DATE OF FINANCIAL YEAR */    
	@OPENENTRYFLAG INT,    
	@OPENINGENTRYDATE VARCHAR(11),  /* O/P ENTRY DATE ( VTYP = 18 ) FROUND FROM LEDGER FOR VDT <= LAST DATE ENTERED BY USER */    
	@STATUSID VARCHAR(20),          /* AS BROKER/BRANCH/CLIENT ETC. */    
	@STATUSNAME VARCHAR(20),        /* IN CASE OF BRANCH LOGIN BRANCHCODE */    
	@SORTBYDATE VARCHAR(3),          /* WHETHER REPORT IS BASED ON VDT OR EDT */    
	@BULK VARCHAR(1) = 'N',
	@FNAME VARCHAR(200) = ''

/*
	Exec rpt_Acc_TrialBalance 'Mar 31 2007', 'codewise', 'all', 'withopbal', 'Apr  1 2006', 'Apr  1 2006', 0,'Apr  1 2006', 'BROKER', '%', 'Edt', 'Y', 'D:\TEST.TXT'
*/
    
AS    

DECLARE  
	@@COSTCODE AS VARCHAR(3),
	@@TEMPTABLE AS VARCHAR(100),
	@@SQL AS VARCHAR(2000),
	@@ERRORCNT AS INT

    
SELECT * INTO 	#ACMAST FROM ACMAST WHERE 1 = 2    
  
SELECT CLTCODE,VAMT DRTOT,VAMT CRTOT, VAMT AMOUNT INTO #TEMPLEDGER FROM LEDGER WHERE 1=2    
  
SELECT CLTCODE,VAMT DRTOT,VAMT CRTOT, VAMT AMOUNT,ACNAME,VNO BRANCHCODE, LNO ACCAT  INTO #TEMPLEDGERFINAL FROM LEDGER WHERE 1=2    

IF UPPER(@STATUSID) = 'BROKER'    
	BEGIN
		IF @BALANCE='NORMAL'    
			IF @SORTBYDATE = 'VDT'    
				BEGIN       
					INSERT INTO #TEMPLEDGER SELECT L.CLTCODE , 0,0,  
					AMOUNT = SUM(CASE WHEN UPPER(L.DRCR) = 'D' THEN VAMT ELSE -VAMT END)    
					FROM LEDGER L WHERE VDT >= @CURRYRSTDATE + ' 00:00:00' AND VDT <=  @VDT + ' 23:59:59'      
					GROUP BY L.CLTCODE    
				END    
			ELSE   
				BEGIN    
					INSERT INTO #TEMPLEDGER    
					SELECT CLTCODE, AMOUNT=SUM(AMOUNT) ,0,0     
					FROM      
					(       
					SELECT L.CLTCODE, AMOUNT = ISNULL(SUM( CASE WHEN UPPER(L.DRCR) = 'D' THEN VAMT ELSE -VAMT END),0)  
					FROM LEDGER L WHERE EDT LIKE @CURRYRSTDATE + '%' AND VTYP = 18      
					GROUP BY L.CLTCODE      
					
					UNION ALL      
					
					SELECT L.CLTCODE, AMOUNT = SUM( CASE WHEN UPPER(L.DRCR) = 'D' THEN VAMT ELSE -VAMT END)   
					FROM LEDGER  L  WHERE EDT >= @CURRYRSTDATE + ' 00:00:00' AND EDT <=  @VDT + ' 23:59:59' AND VTYP <> 18      
					GROUP BY L.CLTCODE
					
					UNION ALL      
					
					SELECT L.CLTCODE,AMOUNT = ISNULL(SUM( CASE WHEN UPPER(L.DRCR) = 'C' THEN L.VAMT ELSE -L.VAMT END),0)  
					FROM LEDGER L  WHERE L.EDT >=  @CURRYRSTDATE + ' 00:00:00'    
					AND VDT < @CURRYRSTDATE      
					GROUP BY L.CLTCODE       
					) T      
					GROUP BY CLTCODE       
				END    
		ELSE  
			IF @SORTBYDATE = 'VDT'    
				BEGIN    
					IF @STDATE = @CURRYRSTDATE
						BEGIN
							INSERT INTO #TEMPLEDGER    
							SELECT L.CLTCODE ,    
							DRTOT = SUM(CASE WHEN VTYP <> 18 AND VDT >= @STDATE  THEN ( CASE WHEN UPPER(L.DRCR) = 'D' THEN VAMT ELSE 0 END) ELSE 0 END),     
							CRTOT = SUM(CASE WHEN VTYP <> 18 AND VDT >= @STDATE  THEN ( CASE WHEN UPPER(L.DRCR) = 'C' THEN VAMT ELSE 0 END) ELSE 0 END),     
							OPBAL = SUM(CASE WHEN (VDT LIKE @STDATE + '%' AND VTYP = '18') THEN ( CASE WHEN UPPER(L.DRCR) = 'D' THEN VAMT ELSE -VAMT END) ELSE 0 END)    
							FROM LEDGER L WHERE  VDT >= @CURRYRSTDATE + ' 00:00:00' AND VDT <= @VDT + ' 23:59:59'     
							GROUP BY L.CLTCODE    
						END
					ELSE
						BEGIN
							INSERT INTO #TEMPLEDGER    
							SELECT L.CLTCODE ,    
							DRTOT = SUM(CASE WHEN VTYP <> 18 AND VDT >= @STDATE  THEN ( CASE WHEN UPPER(L.DRCR) = 'D' THEN VAMT ELSE 0 END) ELSE 0 END),     
							CRTOT = SUM(CASE WHEN VTYP <> 18 AND VDT >= @STDATE  THEN ( CASE WHEN UPPER(L.DRCR) = 'C' THEN VAMT ELSE 0 END) ELSE 0 END),     
							OPBAL = SUM(CASE WHEN VDT < @STDATE THEN ( CASE WHEN UPPER(L.DRCR) = 'D' THEN VAMT ELSE -VAMT END) ELSE 0 END)    
							FROM LEDGER L WHERE  VDT >= @CURRYRSTDATE + ' 00:00:00' AND VDT <= @VDT + ' 23:59:59'     
							GROUP BY L.CLTCODE    
						END
				END    
			ELSE    
				BEGIN    
					IF @STDATE = @CURRYRSTDATE
						BEGIN
							INSERT INTO #TEMPLEDGER    
							SELECT L.CLTCODE ,    
							DRTOT = SUM(CASE WHEN VTYP <> 18 AND EDT >= @STDATE    THEN ( CASE WHEN UPPER(L.DRCR) = 'D' THEN VAMT ELSE 0 END) ELSE 0 END),     
							CRTOT = SUM(CASE WHEN VTYP <> 18 AND EDT >= @STDATE   THEN ( CASE WHEN UPPER(L.DRCR) = 'C' THEN VAMT ELSE 0 END) ELSE 0 END),     
							OPBAL = SUM(CASE WHEN (VDT LIKE @STDATE + '%' AND VTYP = '18') THEN ( CASE WHEN UPPER(L.DRCR) = 'D' THEN VAMT ELSE -VAMT END) ELSE 0 END + CASE WHEN (EDT >= @CURRYRSTDATE AND VDT < @CURRYRSTDATE) THEN ( CASE WHEN UPPER(L.DRCR) = 'C' THEN VAMT ELSE -VAMT END) ELSE 0 END)
							FROM LEDGER L WHERE EDT >= @CURRYRSTDATE + ' 00:00:00' AND EDT <= @VDT + ' 23:59:59'     
							GROUP BY L.CLTCODE    
						END
					ELSE
						BEGIN
							INSERT INTO #TEMPLEDGER    
							SELECT L.CLTCODE ,    
							DRTOT = SUM(CASE WHEN VTYP <> 18 AND EDT >= @STDATE    THEN ( CASE WHEN UPPER(L.DRCR) = 'D' THEN VAMT ELSE 0 END) ELSE 0 END),     
							CRTOT = SUM(CASE WHEN VTYP <> 18 AND EDT >= @STDATE   THEN ( CASE WHEN UPPER(L.DRCR) = 'C' THEN VAMT ELSE 0 END) ELSE 0 END),     
							OPBAL = SUM(CASE WHEN EDT < @STDATE THEN (CASE WHEN UPPER(L.DRCR) = 'D' THEN VAMT ELSE -VAMT END) ELSE 0 END  + CASE WHEN (EDT >= @CURRYRSTDATE AND VDT < @CURRYRSTDATE) THEN (CASE WHEN UPPER(L.DRCR) = 'C' THEN VAMT ELSE -VAMT END) ELSE 0 END)    
							FROM LEDGER L WHERE EDT >= @CURRYRSTDATE + ' 00:00:00' AND EDT <= @VDT + ' 23:59:59'     
							GROUP BY L.CLTCODE    
						END
				END     
  
		IF  @VIEWOPTION = 'PARTYWISE'     
			BEGIN    
				INSERT INTO #TEMPLEDGERFINAL SELECT L.*,LEFT(ACNAME,30) ACNAME, BRANCHCODE,ACCAT   
				FROM #TEMPLEDGER L, ACMAST A WHERE L.CLTCODE =A.CLTCODE   AND ACCAT= 4 AND ( DRTOT <> 0 OR CRTOT <> 0 OR  AMOUNT <> 0)  
			END    
		ELSE    
			IF @VIEWOPTION = 'GL'    
				BEGIN    
					INSERT INTO #TEMPLEDGERFINAL SELECT L.*,LEFT(ACNAME,30) ACNAME, BRANCHCODE,ACCAT   
					FROM #TEMPLEDGER L, ACMAST A WHERE L.CLTCODE =A.CLTCODE   AND ACCAT <> 4 AND ( DRTOT <> 0  OR CRTOT <> 0 OR  AMOUNT <> 0)  
				END    
			ELSE    
				BEGIN    
					INSERT INTO #TEMPLEDGERFINAL SELECT L.*,LEFT(ACNAME,30) ACNAME, BRANCHCODE,ACCAT   
					FROM #TEMPLEDGER L, ACMAST A WHERE L.CLTCODE =A.CLTCODE  AND ( DRTOT <> 0  OR CRTOT <> 0 OR  AMOUNT <> 0)  
				END   
		  
		IF @VIEWOPTION = 'GL'    
			BEGIN  
				INSERT INTO #TEMPLEDGERFINAL  
				SELECT 'ZZZZZZZZZZ',SUM(DRTOT),SUM(CRTOT),SUM(AMOUNT),'CLIENT BALANCES',' ',4  FROM #TEMPLEDGER L, ACMAST A WHERE L.CLTCODE =A.CLTCODE  AND ACCAT = 4   
			END  
	END 
/*  -- FOR BRANCH SELECTION --  */  
IF UPPER(@STATUSID) = 'BRANCH'    
	BEGIN
		SELECT @@COSTCODE = (SELECT COSTCODE FROM COSTMAST C, CATEGORY C2 WHERE C2.CATEGORY = 'BRANCH' AND C.CATCODE = C2.CATCODE AND COSTNAME = @STATUSNAME )  
			IF @BALANCE='NORMAL'    
				IF @SORTBYDATE = 'VDT'    
					BEGIN       
						INSERT INTO #TEMPLEDGER SELECT L.CLTCODE , 0,0,  
						AMOUNT = SUM(CASE WHEN UPPER(L.DRCR) = 'D' THEN VAMT ELSE -VAMT END)    
						FROM LEDGER L, LEDGER2 L2 WHERE VDT >= @CURRYRSTDATE + ' 00:00:00' AND VDT <=  @VDT + ' 23:59:59'      
						AND L.VNO = L2.VNO AND L.VTYP = L2.VTYPE AND L.BOOKTYPE = L2.BOOKTYPE AND L.LNO = L2.LNO
						AND COSTCODE = @@COSTCODE
						GROUP BY L.CLTCODE    
					END    
				ELSE   
					BEGIN    
						INSERT INTO #TEMPLEDGER    
						SELECT CLTCODE, AMOUNT=SUM(AMOUNT) ,0,0     
						FROM      
						(       
						SELECT L.CLTCODE, AMOUNT = ISNULL(SUM( CASE WHEN UPPER(L.DRCR) = 'D' THEN VAMT ELSE -VAMT END),0)  
						FROM LEDGER L, LEDGER2 L2 WHERE EDT LIKE @CURRYRSTDATE + '%' AND VTYP = 18      
						AND L.VNO = L2.VNO AND L.VTYP = L2.VTYPE AND L.BOOKTYPE = L2.BOOKTYPE AND L.LNO = L2.LNO
						AND COSTCODE = @@COSTCODE
						GROUP BY L.CLTCODE      

						UNION ALL      

						SELECT L.CLTCODE, AMOUNT = SUM( CASE WHEN UPPER(L.DRCR) = 'D' THEN VAMT ELSE -VAMT END)   
						FROM LEDGER L, LEDGER2 L2 WHERE EDT >= @CURRYRSTDATE + ' 00:00:00' AND EDT < @VDT AND VTYP <> 18      
						AND L.VNO = L2.VNO AND L.VTYP = L2.VTYPE AND L.BOOKTYPE = L2.BOOKTYPE AND L.LNO = L2.LNO
						AND COSTCODE = @@COSTCODE
						GROUP BY L.CLTCODE       

						UNION ALL      

						SELECT L.CLTCODE,AMOUNT = ISNULL(SUM( CASE WHEN UPPER(L.DRCR) = 'C' THEN L.VAMT ELSE -L.VAMT END),0)  
						FROM LEDGER L, LEDGER2 L2 WHERE L.VDT >=  @CURRYRSTDATE + ' 00:00:00' AND EDT < @CURRYRSTDATE
						AND L.VNO = L2.VNO AND L.VTYP = L2.VTYPE AND L.BOOKTYPE = L2.BOOKTYPE AND L.LNO = L2.LNO
						AND COSTCODE = @@COSTCODE
						GROUP BY L.CLTCODE       
						) T      
						GROUP BY CLTCODE       
					END    
			ELSE  
				IF @SORTBYDATE = 'VDT'    
					BEGIN    
						INSERT INTO #TEMPLEDGER    
						SELECT L2.CLTCODE ,    
						DRTOT = SUM(CASE WHEN VTYP <> 18 AND VDT >= @STDATE  THEN ( CASE WHEN UPPER(L.DRCR) = 'D' THEN VAMT ELSE 0 END) ELSE 0 END),     
						CRTOT = SUM(CASE WHEN VTYP <> 18 AND VDT >= @STDATE  THEN ( CASE WHEN UPPER(L.DRCR) = 'C' THEN VAMT ELSE 0 END) ELSE 0 END),     
						OPBAL = SUM(CASE WHEN VDT < @STDATE THEN ( CASE WHEN UPPER(L.DRCR) = 'D' THEN VAMT ELSE -VAMT END) ELSE 0 END)    
						FROM LEDGER L, LEDGER2 L2 WHERE  VDT >= @CURRYRSTDATE + ' 00:00:00' AND VDT <= @VDT + ' 23:59:59'
						AND L.VNO = L2.VNO AND L.VTYP = L2.VTYPE AND L.BOOKTYPE = L2.BOOKTYPE AND L.LNO = L2.LNO
						AND COSTCODE = @@COSTCODE
						GROUP BY L2.CLTCODE    
					END    
				ELSE    
					BEGIN    
						INSERT INTO #TEMPLEDGER    
						SELECT L2.CLTCODE ,    
						DRTOT = SUM(CASE WHEN VTYP <> 18 AND VDT >= @STDATE    THEN ( CASE WHEN UPPER(L.DRCR) = 'D' THEN VAMT ELSE 0 END) ELSE 0 END),     
						CRTOT = SUM(CASE WHEN VTYP <> 18 AND VDT >= @STDATE   THEN ( CASE WHEN UPPER(L.DRCR) = 'C' THEN VAMT ELSE 0 END) ELSE 0 END),     
						OPBAL = SUM(CASE WHEN VDT < @STDATE THEN ( CASE WHEN UPPER(L.DRCR) = 'D' THEN VAMT ELSE -VAMT END) ELSE 0 END)    
						FROM LEDGER L, LEDGER2 L2 WHERE EDT >= @CURRYRSTDATE + ' 00:00:00' AND EDT <= @VDT + ' 23:59:59'     
						AND L.VNO = L2.VNO AND L.VTYP = L2.VTYPE AND L.BOOKTYPE = L2.BOOKTYPE AND L.LNO = L2.LNO
						AND COSTCODE = @@COSTCODE
						GROUP BY L2.CLTCODE    
					END     

		IF  @VIEWOPTION = 'PARTYWISE'     
			BEGIN    
				INSERT INTO #TEMPLEDGERFINAL SELECT L.*,LEFT(ACNAME,30) ACNAME, BRANCHCODE,ACCAT   
				FROM #TEMPLEDGER L, ACMAST A WHERE L.CLTCODE =A.CLTCODE   AND ACCAT= 4 AND ( DRTOT <> 0 OR CRTOT <> 0 OR  AMOUNT <> 0)  
			END    
		ELSE    
			IF @VIEWOPTION = 'GL'    
				BEGIN    
					INSERT INTO #TEMPLEDGERFINAL SELECT L.*,LEFT(ACNAME,30) ACNAME, BRANCHCODE,ACCAT   
					FROM #TEMPLEDGER L, ACMAST A WHERE L.CLTCODE =A.CLTCODE   AND ACCAT <> 4 AND ( DRTOT <> 0  OR CRTOT <> 0 OR  AMOUNT <> 0)  
				END    
			ELSE    
				BEGIN    
					INSERT INTO #TEMPLEDGERFINAL SELECT L.*,LEFT(ACNAME,30) ACNAME, BRANCHCODE,ACCAT   
					FROM #TEMPLEDGER L, ACMAST A WHERE L.CLTCODE =A.CLTCODE  AND ( DRTOT <> 0  OR CRTOT <> 0 OR  AMOUNT <> 0)  
				END   
  
		IF @VIEWOPTION = 'GL'    
			BEGIN  
				INSERT INTO #TEMPLEDGERFINAL  
				SELECT 'ZZZZZZZZZZ',SUM(DRTOT),SUM(CRTOT),SUM(AMOUNT),'CLIENT BALANCES',' ',4  FROM #TEMPLEDGER L, ACMAST A WHERE L.CLTCODE =A.CLTCODE  AND ACCAT = 4   
			END  
	END 
/* ---------------------------- */  

IF @BULK = 'N'
	BEGIN
		IF @FLAG = 'CODEWISE'    
			BEGIN  
				SELECT * FROM #TEMPLEDGERFINAL ORDER BY  CLTCODE, ACNAME, BRANCHCODE  
			END  
		ELSE  
			BEGIN  
				SELECT * FROM #TEMPLEDGERFINAL  ORDER BY  ACNAME,CLTCODE, BRANCHCODE  
			END  
	END
ELSE IF @BULK = 'Y'
	BEGIN
		IF @FNAME <> ''
			BEGIN
				INSERT INTO TEMP_TRIALBALANCE_BULK (CLTCODE, DRTOT, CRTOT, AMOUNT, ACNAME, BRANCHCODE, ACCAT, PROCID)
				SELECT CLTCODE,DRTOT,CRTOT, AMOUNT, ACNAME, BRANCHCODE, ACCAT, PROCID = @@SPID FROM #TEMPLEDGERFINAL
/*				CREATE TABLE ERROR_TBL
					(
						ERR_ID INT
					)*/
				IF @FLAG = 'CODEWISE'
					BEGIN
						SELECT @@SQL = "MASTER.DBO.XP_CMDSHELL 'DEL " + @FNAME + "', no_output"
						EXEC (@@SQL)
						SELECT @@SQL = "INSERT INTO ERROR_TBL EXEC MASTER.DBO.XP_CMDSHELL 'BCP " + CHAR(34) + "SELECT * FROM ACCOUNT.DBO.TEMP_TRIALBALANCE_BULK WHERE PROCID = " + CONVERT(VARCHAR, @@SPID) + " ORDER BY CLTCODE, ACNAME, BRANCHCODE" + CHAR(34) + " queryout " + CHAR(34) + @FNAME + CHAR(34) + " -c -q -t " + CHAR(34) + "," + CHAR(34) + " -U " + CHAR(34) + "SA" + CHAR(34) + " -P " + CHAR(34) + "M0" + CHAR(34) + "', no_output "
					END
				ELSE
					BEGIN
						SELECT @@SQL = "MASTER.DBO.XP_CMDSHELL 'DEL " + @FNAME + "', no_output"
						EXEC (@@SQL)
						SELECT @@SQL = "INSERT INTO ERROR_TBL EXEC MASTER.DBO.XP_CMDSHELL 'BCP " + CHAR(34) + "SELECT * FROM ACCOUNT.DBO.TEMP_TRIALBALANCE_BULK WHERE PROCID = "  + CONVERT(VARCHAR, @@SPID) + " ORDER BY CLTCODE, ACNAME, BRANCHCODE" + CHAR(34) + " queryout " + CHAR(34) + @FNAME + CHAR(34) + " -c -q -t " + CHAR(34) + "," + CHAR(34) + " -U " + CHAR(34) + "SA" + CHAR(34) + " -P " + CHAR(34) + "M0" + CHAR(34) + "', no_output "
					END
				SELECT @@SQL
				RETURN
				EXEC (@@SQL)
/*				IF @@ERRORCNT <> 0
					BEGIN
						SELECT 'SOME ERROR OCCURED WHILE EXPORTING FILE'
					END*/
			END
		ELSE
			BEGIN
				SELECT * FROM #TEMPLEDGERFINAL ORDER BY  CLTCODE, ACNAME, BRANCHCODE  
			END
	END
ELSE	
	BEGIN
		SELECT * FROM #TEMPLEDGERFINAL ORDER BY  CLTCODE, ACNAME, BRANCHCODE  
	END

GO
