-- Object: PROCEDURE dbo.ACC_PRINTRECONCILE
-- Server: 10.253.33.91 | DB: ACCOUNTSLBS
--------------------------------------------------

--EXEC ACC_PRINTRECONCILE '995116', 'STATEMENT', 'MAR 31 2008', 'MAR 31 2008'  
CREATE PROCEDURE  [DBO].[ACC_PRINTRECONCILE]                    
@CODE VARCHAR(10),                  
@REPORTTYPE VARCHAR(10),                  
@TDATE  DATETIME,                  
@FDATE  DATETIME                  
AS                  
              
SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED             
                
IF UPPER(@REPORTTYPE) = 'STATEMENT'                  
BEGIN                  
	SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED  
	SELECT   
	 L.VTYP, L.BOOKTYPE, L.VNO, VDT, TDATE=CONVERT(VARCHAR,L.VDT,103), ISNULL(DDNO,'') DDNO, ISNULL(CLTCODE ,'') CLTCODE ,                   
	 ISNULL( ACNAME ,'') ACNAME, L.DRCR, DRAMT=(CASE WHEN UPPER(L.DRCR) = 'D' THEN RELAMT  ELSE 0 END ),                  
	 CRAMT= (CASE WHEN UPPER(L.DRCR) = 'C' THEN RELAMT ELSE 0 END ),                   
	 TRELDT=ISNULL(CONVERT(VARCHAR, RELDT , 103),''), L1.REFNO                  
	FROM   
	 LEDGER L,   
	 LEDGER1 L1 ,                  
	 (SELECT VNO, VTYP, BOOKTYPE FROM LEDGER WHERE CLTCODE = @CODE AND VDT <= @TDATE ) L2  
	WHERE   
	 L.VTYP = L2.VTYP AND L.VNO= L2.VNO AND L.BOOKTYPE = L2.BOOKTYPE                   
	 AND L.VTYP = L1.VTYP AND L.BOOKTYPE = L1.BOOKTYPE AND L.VNO = L1.VNO AND L.LNO = L1.LNO      
	 AND CLTCODE <> @CODE  
	 AND NOT EXISTS  
	  (SELECT L3.DDNO FROM LEDGER1 L3, (SELECT VNO, VTYP, BOOKTYPE FROM LEDGER WHERE CLTCODE = @CODE AND VDT <= @TDATE AND VTYP = 16) L4  
	  WHERE L1.DDNO = L3.DDNO AND CONVERT(VARCHAR(11),L1.DDDT,109) = CONVERT(VARCHAR(11),L3.DDDT,109) AND L1.RELAMT = L3.RELAMT  
	  AND L3.VNO = L4.VNO AND L3.VTYP = L4.VTYP AND L3.BOOKTYPE = L4.BOOKTYPE AND L1.BOOKTYPE = L3.BOOKTYPE )  
	 AND (RELDT ='1900-01-01 00:00:00.000' OR RELDT >  @TDATE )  
	ORDER BY   
	 L.DRCR, VDT, L.VTYP, L.VNO  
END                  
ELSE                  
BEGIN                  
	SELECT DISTINCT VTYP, BOOKTYPE, VNO, LNO INTO #TBLBANKRECO_TMP FROM LEDGER WHERE CLTCODE = @CODE         
	AND VDT >= @FDATE AND VDT <= @TDATE       
	      
	CREATE CLUSTERED      
	  INDEX [PARTYVDT] ON [DBO].[#TBLBANKRECO_TMP] ([VNO], [VTYP], [BOOKTYPE])      
	WITH      
		FILLFACTOR = 90      
	ON [PRIMARY]      
	      
	SELECT L.* INTO #LEDGER_TMP      
	FROM LEDGER L, #TBLBANKRECO_TMP T      
	WHERE L.VNO = T.VNO       
	AND L.VTYP = T.VTYP      
	AND L.BOOKTYPE = T.BOOKTYPE      
	      
	CREATE CLUSTERED      
	  INDEX [PARTYVDT] ON [DBO].[#LEDGER_TMP] ([VNO], [VTYP], [BOOKTYPE], [LNO])      
	WITH      
		FILLFACTOR = 90      
	ON [PRIMARY]      
	      
	SELECT L.* INTO #LEDGER1_TMP      
	FROM LEDGER1 L, #TBLBANKRECO_TMP T      
	WHERE L.VNO = T.VNO       
	AND L.VTYP = T.VTYP      
	AND L.BOOKTYPE = T.BOOKTYPE      
	      
	CREATE CLUSTERED      
	  INDEX [PARTYVDT] ON [DBO].[#LEDGER1_TMP] ([VNO], [VTYP], [BOOKTYPE], [LNO])      
	WITH      
		FILLFACTOR = 90      
	ON [PRIMARY]      
	      
	 SELECT L.VTYP, L.BOOKTYPE, L.VNO, VDT, TDATE=CONVERT(VARCHAR,L.VDT,103), ISNULL(DDNO,'') DDNO, ISNULL(CLTCODE ,'') CLTCODE ,                   
	 ISNULL( ACNAME ,'') ACNAME, L.DRCR, DRAMT=(CASE WHEN UPPER(L.DRCR) = 'D' THEN RELAMT  ELSE 0 END ),                  
	 CRAMT= (CASE WHEN UPPER(L.DRCR) = 'C' THEN RELAMT ELSE 0 END ),                   
	 TRELDT=ISNULL(CONVERT(VARCHAR, RELDT , 103),''), L1.REFNO                  
	 FROM #LEDGER_TMP L, #LEDGER1_TMP L1, #TBLBANKRECO_TMP T      
	 WHERE L.VTYP = T.VTYP AND L.VNO= T.VNO AND L.BOOKTYPE = T.BOOKTYPE                   
	 AND L.VTYP = L1.VTYP AND L.BOOKTYPE = L1.BOOKTYPE AND L.VNO = L1.VNO AND L.LNO = L1.LNO      
	 AND CLTCODE <> @CODE AND VDT >= @FDATE AND VDT <= @TDATE                  
	 ORDER BY L.DRCR, VDT, L.VTYP, L.VNO      
	      
	DROP TABLE #TBLBANKRECO_TMP      
	DROP TABLE #LEDGER_TMP      
	DROP TABLE #LEDGER1_TMP      
END

GO
