-- Object: PROCEDURE dbo.RPT_RETURNFIELDS_ALL
-- Server: 10.253.33.91 | DB: ACCOUNTSLBS
--------------------------------------------------



CREATE PROC RPT_RETURNFIELDS_ALL
/*
	EXEC RPT_RETURNFIELDS_ALL 'BROKER', 'S', 'PARTY', 'Y', 'N', 'Y', 'N', 'Y'
*/
	@STATUSID VARCHAR(10),
	@SUMMARYOPT VARCHAR(1),
	@RPTNAME VARCHAR(20),
	@NSE VARCHAR(1),
	@BSE VARCHAR(1),
	@NSEFO VARCHAR(1),
	@NCX VARCHAR(1),
	@MCX VARCHAR(1)
AS

DECLARE
	@@SQL AS VARCHAR(2000)

SET NOCOUNT ON

SELECT @@SQL = "SELECT RETURNFLDS = FIRSTPART "
IF @NSE = 'Y'
	BEGIN
		SELECT @@SQL = @@SQL + "+ NSEPART "
	END
IF @BSE = 'Y'
	BEGIN
		SELECT @@SQL = @@SQL + "+ BSEPART "
	END
IF @NSEFO = 'Y'
	BEGIN
		SELECT @@SQL = @@SQL + "+ NSEFOPART "
	END
IF @NCX = 'Y'
	BEGIN
		SELECT @@SQL = @@SQL + "+ NCXPART "
	END
IF @MCX = 'Y'
	BEGIN
		SELECT @@SQL = @@SQL + "+ MCXPART "
	END

SELECT @@SQL = LTRIM(RTRIM(@@SQL))

SELECT @@SQL = @@SQL + " FROM TBL_MASTER_PARTYLEDGER_ALL "
SELECT @@SQL = @@SQL + "WHERE REPORTNAME = '" + @RPTNAME + "' "
SELECT @@SQL = @@SQL + "AND STATUSID = '" + @STATUSID + "' "
SELECT @@SQL = @@SQL + "AND SUMMARYOPT = '" + @SUMMARYOPT + "'"

--PRINT (@@SQL)
EXEC (@@SQL)

GO
