-- Object: PROCEDURE dbo.NEWASP_MARGINTRIALBALANCE
-- Server: 10.253.33.91 | DB: ACCOUNTSLBS
--------------------------------------------------


--NEWASP_MARGINTRIALBALANCE 'Mar 31 2006', 'codewise','partywise','normal','Apr 1 2005', 'Apr 1 2005', 1,'Apr 1 2005', 'BRANCH', 'TEST', 'vdt', '11212','','BSE'

CREATE PROCEDURE  [dbo].[NEWASP_MARGINTRIALBALANCE]  
  
@VDT VARCHAR(11),               /* AS ON DATE ENTERED BY USER */  
@FLAG VARCHAR(15),              /* SORT ORDER FOR REPORT - CODEWISE OR NAMEWISE */  
@VIEWOPTION VARCHAR(10),        /* OPTIONS FOR ACCOUNTS SELECTION - ALL, GL, PARTY */  
@BALANCE VARCHAR(10),           /* NORMAL OR WITHOPBAL */  
@STDATE VARCHAR(11),            /* START DATE ENTERED BY USER */  
@CURRYRSTDATE VARCHAR(11), /* START DATE OF FINANCIAL YEAR */  
@OPENENTRYFLAG INT,  
@OPENINGENTRYDATE VARCHAR(11),  /* O/P ENTRY DATE ( VTYP = 18 ) FROUND FROM LEDGER FOR VDT <= LAST DATE ENTERED BY USER */  
@STATUSID VARCHAR(20),          /* AS BROKER/BRANCH/CLIENT ETC. */  
@STATUSNAME VARCHAR(20),        /* IN CASE OF BRANCH LOGIN BRANCHCODE */  
@SORTBYDATE VARCHAR(3),          /* WHETHER REPORT IS BASED ON VDT OR EDT */  
@SHOWZEROBAL VARCHAR(1) = 'N',  /* SHOW ZERO BAL   */ 
@GRPCODE VARCHAR(20),
@SHAREDB VARCHAR(20),
@EXCHANGE VARCHAR(10),
@SEGMENT VARCHAR(9)  
AS  
  
DECLARE  
@@SELECTQURY  AS VARCHAR(2000),  
@@FROMTABLES  AS VARCHAR(2000),  
@@WHEREPART   AS VARCHAR(1000),  
@@SQL		  AS VARCHAR(1000),  
@@WHEREPART1  AS VARCHAR(500),  
@@WHEREPART2  AS VARCHAR(500),  
@@WHEREPART3  AS VARCHAR(500),  
@@ADDWHERE    AS VARCHAR(200),  
@@GROUPBY     AS VARCHAR(200),  
@@SORTBY      AS VARCHAR(200),  
@@HAVING      AS VARCHAR(200),
@@COSTCODE    AS VARCHAR(3)  
 

CREATE TABLE #COSTMAST
(
	COSTCODE INT
)

IF @STATUSID = 'REGION'
BEGIN
	SET @@SQL = " INSERT INTO #COSTMAST "
	SET @@SQL = @@SQL + " SELECT COSTCODE FROM COSTMAST C, "+ @SHAREDB +".DBO.REGION R WHERE REGIONCODE = RTRIM('"+@STATUSNAME+"') AND COSTNAME = BRANCH_CODE "
END

IF @STATUSID = 'AREA'
BEGIN
	SET @@SQL = " INSERT INTO #COSTMAST "
	SET @@SQL = @@SQL + " SELECT COSTCODE FROM COSTMAST C, "+ @SHAREDB +".DBO.AREA A WHERE AREACODE = RTRIM('"+@STATUSNAME+"') AND COSTNAME = BRANCH_CODE "
END

IF @STATUSID = 'BRANCH'
BEGIN
	SET @@SQL = " INSERT INTO #COSTMAST "
	SET @@SQL = @@SQL + " SELECT COSTCODE FROM COSTMAST WHERE COSTNAME = RTRIM('"+@STATUSNAME+"') "
END
PRINT(@@SQL)  
EXEC(@@SQL) 

IF UPPER(@STATUSID) = 'BROKER'  
BEGIN  
 SELECT @@GROUPBY    = " GROUP BY L.PARTY_CODE , A.ACNAME, BRANCHCODE, ACCAT"  
END  
ELSE  
BEGIN  
 SELECT @@GROUPBY    = " GROUP BY ML.PARTY_CODE , A.ACNAME, BRANCHCODE, ACCAT"
END  
  
IF UPPER(@STATUSID) = 'BROKER'  
BEGIN  
 IF @FLAG = 'CODEWISE'  
 BEGIN  
    SELECT @@SORTBY = " ORDER BY  L.PARTY_CODE, A.ACNAME, BRANCHCODE"  
 END  
 ELSE   
 BEGIN   
    SELECT @@SORTBY = " ORDER BY  A.ACNAME, L.PARTY_CODE, BRANCHCODE"  
 END  
END  
ELSE  
BEGIN  
 IF @FLAG = 'CODEWISE'  
 BEGIN  
    SELECT @@SORTBY = " ORDER BY  ML.PARTY_CODE, A.ACNAME"  
 END  
 ELSE   
 BEGIN   
    SELECT @@SORTBY = " ORDER BY  A.ACNAME, ML.PARTY_CODE"  
 END  
END  
  
IF @VIEWOPTION = 'PARTYWISE'  
BEGIN  
   SELECT @@ADDWHERE  = " AND A.ACCAT = 4 "   
END  
ELSE IF @VIEWOPTION = 'GL'  
BEGIN  
	SELECT @@ADDWHERE  = " AND A.ACCAT <> 4 "   
END  
ELSE  
BEGIN  
	SELECT @@ADDWHERE  = " "   
END  
  
IF @STATUSID = 'BROKER'  
BEGIN  
      	SELECT @@WHEREPART1 = " WHERE VDT <= '" + @VDT + " 23:59:59' AND L.PARTY_CODE=  A.CLTCODE"   
      	SELECT @@WHEREPART2 = " WHERE VDT >= '" + @CURRYRSTDATE + " 00:00:00' AND VDT <= '" + @VDT + " 23:59:59' AND L.PARTY_CODE=  A.CLTCODE"   
      	SELECT @@WHEREPART3 = " WHERE VDT >= '" + @OPENINGENTRYDATE + " 00:00:00' AND VDT <= '" + @VDT + " 23:59:59' AND L.PARTY_CODE=  A.CLTCODE"   
END  
ELSE
BEGIN  
      	SELECT @@WHEREPART1 = " WHERE EXISTS(SELECT COSTCODE FROM #COSTMAST C WHERE L.COSTCODE = C.COSTCODE) AND VDT <= '" + @VDT + " 23:59:59' AND ML.PARTY_CODE=A.CLTCODE AND ML.MCLTCODE=L.CLTCODE AND ML.PARTY_CODE=  A.CLTCODE"   
      	SELECT @@WHEREPART2 = " WHERE EXISTS(SELECT COSTCODE FROM #COSTMAST C WHERE L.COSTCODE = C.COSTCODE) AND VDT >= '" + @CURRYRSTDATE + " 00:00:00' AND VDT <= '" + @VDT + " 23:59:59' AND ML.PARTY_CODE=A.CLTCODE AND ML.MCLTCODE=L.CLTCODE AND ML.PARTY_CODE=  A.CLTCODE"   
      	SELECT @@WHEREPART3 = " WHERE EXISTS(SELECT COSTCODE FROM #COSTMAST C WHERE L.COSTCODE = C.COSTCODE) AND VDT >= '" + @OPENINGENTRYDATE + " 00:00:00' AND VDT <= '" + @VDT + " 23:59:59' AND ML.PARTY_CODE=A.CLTCODE AND ML.MCLTCODE=L.CLTCODE AND ML.PARTY_CODE=  A.CLTCODE"   
END  

IF @STATUSID = 'BROKER'  
BEGIN  
IF @BALANCE='NORMAL'  
BEGIN  
   IF @OPENENTRYFLAG = 0   
   BEGIN  
      SELECT @@SELECTQURY = "SELECT L.PARTY_CODE , ACNAME=ISNULL(A.ACNAME,''), BRANCHCODE, AMOUNT = ISNULL(SUM(CASE WHEN UPPER(DRCR) = 'D' THEN AMOUNT ELSE -AMOUNT END),0),ACCAT,'" + @EXCHANGE + "','MARGIN " + @EXCHANGE + " - " + @SEGMENT +"' "  
      SELECT @@FROMTABLES = " FROM MARGINLEDGER L , (SELECT CLTCODE, ACNAME = LONGNAME, ACCAT, BRANCHCODE FROM ACMAST WITH(NOLOCK) WHERE  GRPCODE LIKE '" + @GRPCODE + "' + '%') A "   
      SELECT @@WHEREPART  = @@WHEREPART1 + @@ADDWHERE  
   END  
   ELSE IF @OPENENTRYFLAG = 1  
   BEGIN  
        SELECT @@SELECTQURY = "SELECT L.PARTY_CODE , ACNAME=ISNULL(A.ACNAME,''), BRANCHCODE, AMOUNT = ISNULL(SUM(CASE WHEN UPPER(DRCR) = 'D' THEN AMOUNT ELSE -AMOUNT END),0),ACCAT,'" + @EXCHANGE + "','MARGIN " + @EXCHANGE + " - " + @SEGMENT +"' "  
        SELECT @@FROMTABLES = " FROM MARGINLEDGER L , (SELECT CLTCODE, ACNAME = LONGNAME, ACCAT, BRANCHCODE FROM ACMAST WITH(NOLOCK) WHERE  GRPCODE LIKE '" + @GRPCODE + "' + '%') A "   
        SELECT @@WHEREPART  = @@WHEREPART2 + @@ADDWHERE  
   END  
   ELSE IF @OPENENTRYFLAG = 2  
   BEGIN  
        SELECT @@SELECTQURY = "SELECT L.PARTY_CODE , ACNAME=ISNULL(A.ACNAME,''), BRANCHCODE, AMOUNT = ISNULL(SUM(CASE WHEN UPPER(DRCR) = 'D' THEN AMOUNT ELSE -AMOUNT END),0),ACCAT,'" + @EXCHANGE + "','MARGIN " + @EXCHANGE + " - " + @SEGMENT +"' "  
        SELECT @@FROMTABLES = " FROM MARGINLEDGER L , (SELECT CLTCODE, ACNAME = LONGNAME, ACCAT, BRANCHCODE FROM ACMAST WITH(NOLOCK) WHERE  GRPCODE LIKE '" + @GRPCODE + "' + '%') A "   
        SELECT @@WHEREPART  = @@WHEREPART3 + @@ADDWHERE  
   END  
END  
ELSE IF @BALANCE='WITHOPBAL'  
BEGIN  
   IF @OPENENTRYFLAG = 0 
   BEGIN  
      IF @CURRYRSTDATE = @STDATE   
         BEGIN  
            SELECT @@SELECTQURY = "SELECT L.PARTY_CODE , ACNAME=ISNULL(A.ACNAME,''), BRANCHCODE, DRTOT = SUM(CASE WHEN UPPER(DRCR) = 'D' THEN AMOUNT ELSE 0 END), CRTOT = SUM(CASE WHEN UPPER(DRCR) = 'C' THEN AMOUNT ELSE 0 END),OPBAL = 0 "  
            SELECT @@FROMTABLES = " FROM MARGINLEDGER L , (SELECT CLTCODE, ACNAME = LONGNAME, ACCAT, BRANCHCODE FROM ACMAST WITH(NOLOCK) WHERE  GRPCODE LIKE '" + @GRPCODE + "' + '%') A "   
            SELECT @@WHEREPART  = @@WHEREPART1 + @@ADDWHERE  
         END  
      ELSE  
         BEGIN  
           SELECT @@SELECTQURY = "SELECT L.PARTY_CODE , ACNAME=ISNULL(A.ACNAME,''), BRANCHCODE,DRTOT = SUM(CASE WHEN VTYP <> 18 AND VDT >= '" + @STDATE + "'   THEN ( CASE WHEN UPPER(DRCR) = 'D' THEN AMOUNT ELSE 0 END) ELSE 0 END),CRTOT = SUM(CASE WHEN VTYP <> 18 AND VDT >= '" + @STDATE + "'    THEN ( CASE WHEN UPPER(DRCR) = 'C' THEN AMOUNT ELSE 0 END) ELSE 0 END),OPBAL = SUM(CASE WHEN VDT < '" + @STDATE + "'  THEN ( CASE WHEN UPPER(DRCR) = 'D' THEN AMOUNT ELSE -AMOUNT END) ELSE 0 END) "  
           SELECT @@FROMTABLES = " FROM MARGINLEDGER L , (SELECT CLTCODE, ACNAME = LONGNAME, ACCAT, BRANCHCODE FROM ACMAST WITH(NOLOCK) WHERE  GRPCODE LIKE '" + @GRPCODE + "' + '%') A "   
           SELECT @@WHEREPART  = @@WHEREPART1 + @@ADDWHERE  
         END  
   END  
   ELSE IF @OPENENTRYFLAG = 1 
   BEGIN  
      IF @CURRYRSTDATE = @STDATE   
         BEGIN  
                SELECT @@SELECTQURY = "SELECT L.PARTY_CODE , ACNAME=ISNULL(A.ACNAME,''), BRANCHCODE,DRTOT = SUM(CASE WHEN VTYP <> 18 AND VDT >= '" + @STDATE + "'  THEN ( CASE WHEN UPPER(DRCR) = 'D' THEN AMOUNT ELSE 0 END) ELSE 0 END),CRTOT = SUM(CASE WHEN VTYP <> 18 AND VDT >= '" + @STDATE + "'  THEN ( CASE WHEN UPPER(DRCR) = 'C' THEN AMOUNT ELSE 0 END) ELSE 0 END),OPBAL = SUM(CASE WHEN VTYP = 18 THEN ( CASE WHEN UPPER(DRCR) = 'D' THEN AMOUNT ELSE -AMOUNT END) ELSE 0 END)"  
                SELECT @@FROMTABLES = " FROM MARGINLEDGER L , (SELECT CLTCODE, ACNAME = LONGNAME, ACCAT, BRANCHCODE FROM ACMAST WITH(NOLOCK) WHERE  GRPCODE LIKE '" + @GRPCODE + "' + '%') A "   
                SELECT @@WHEREPART  = @@WHEREPART2 + @@ADDWHERE  
         END  
      ELSE  
         BEGIN  
           SELECT @@SELECTQURY = "SELECT L.PARTY_CODE , ACNAME=ISNULL(A.ACNAME,''), BRANCHCODE,DRTOT = SUM(CASE WHEN VTYP <> 18 AND VDT >= '" + @STDATE + "'    THEN ( CASE WHEN UPPER(DRCR) = 'D' THEN AMOUNT ELSE 0 END) ELSE 0 END),CRTOT = SUM(CASE WHEN VTYP <> 18 AND VDT >= '" + @STDATE + "'   THEN ( CASE WHEN UPPER(DRCR) = 'C' THEN AMOUNT ELSE 0 END) ELSE 0 END),OPBAL = SUM(CASE WHEN VDT < '" + @STDATE + "'  THEN ( CASE WHEN UPPER(DRCR) = 'D' THEN AMOUNT ELSE -AMOUNT END) ELSE 0 END) "  
           SELECT @@FROMTABLES = " FROM MARGINLEDGER L , (SELECT CLTCODE, ACNAME = LONGNAME, ACCAT, BRANCHCODE FROM ACMAST WITH(NOLOCK) WHERE  GRPCODE LIKE '" + @GRPCODE + "' + '%') A "   
           SELECT @@WHEREPART  = @@WHEREPART2 + @@ADDWHERE  
         END  
   END  
   ELSE IF @OPENENTRYFLAG = 2  
   BEGIN  
      	SELECT @@SELECTQURY = "SELECT L.PARTY_CODE , ACNAME=ISNULL(A.ACNAME,''), BRANCHCODE,DRTOT = SUM(CASE WHEN VTYP <> 18 AND VDT >= '" + @STDATE + "'     THEN ( CASE WHEN UPPER(DRCR) = 'D' THEN AMOUNT ELSE 0 END) ELSE 0 END),CRTOT = SUM(CASE WHEN VTYP <> 18 AND VDT >= '" + @STDATE + "'   THEN ( CASE WHEN UPPER(DRCR) = 'C' THEN AMOUNT ELSE 0 END) ELSE 0 END),OPBAL = SUM(CASE WHEN VDT < '" + @STDATE + "'   THEN ( CASE WHEN UPPER(DRCR) = 'D' THEN AMOUNT ELSE -AMOUNT END) ELSE 0 END) "  
      	SELECT @@FROMTABLES = " FROM MARGINLEDGER L , (SELECT CLTCODE, ACNAME = LONGNAME, ACCAT, BRANCHCODE FROM ACMAST WITH(NOLOCK) WHERE  GRPCODE LIKE '" + @GRPCODE + "' + '%') A "   
      	SELECT @@WHEREPART  = @@WHEREPART3 + @@ADDWHERE  
   END  
END  
END    
  
  
IF @STATUSID = 'BRANCH'  
BEGIN  
IF @BALANCE='NORMAL'  
BEGIN  
   IF @OPENENTRYFLAG = 0  
   BEGIN  
      	SELECT @@SELECTQURY = " SELECT ML.PARTY_CODE , ACNAME=ISNULL(A.ACNAME,''), BRANCHCODE,AMOUNT = ISNULL(SUM(CASE WHEN UPPER(ML.DRCR) = 'D' THEN ML.AMOUNT ELSE -ML.AMOUNT END),0), ACCAT,'" + @EXCHANGE + "','MARGIN " + @EXCHANGE + " - " + @SEGMENT +"' "  
      	SELECT @@FROMTABLES = " FROM LEDGER2 L LEFT OUTER JOIN (SELECT PARTY_CODE,AMOUNT,VTYP,VNO,BOOKTYPE,LNO,DRCR,MCLTCODE,VDT FROM MARGINLEDGER) ML ON L.VNO=ML.VNO AND L.VTYPE=ML.VTYP AND L.BOOKTYPE=ML.BOOKTYPE AND L.LNO=ML.LNO ,(SELECT CLTCODE, ACNAME = LONGNAME, ACCAT, BRANCHCODE FROM ACMAST WITH(NOLOCK) WHERE  GRPCODE LIKE '" + @GRPCODE + "' + '%') A "   
      	SELECT @@WHEREPART  = @@WHEREPART1 + @@ADDWHERE  
   END  
   ELSE IF @OPENENTRYFLAG = 1  
   BEGIN  
      	SELECT @@SELECTQURY = " SELECT ML.PARTY_CODE , ACNAME=ISNULL(A.ACNAME,''), BRANCHCODE,AMOUNT = ISNULL(SUM(CASE WHEN UPPER(ML.DRCR) = 'D' THEN ML.AMOUNT ELSE -ML.AMOUNT END),0), ACCAT,'" + @EXCHANGE + "','MARGIN " + @EXCHANGE + " - " + @SEGMENT +"' "  
      	SELECT @@FROMTABLES = " FROM LEDGER2 L LEFT OUTER JOIN (SELECT PARTY_CODE,AMOUNT,VTYP,VNO,BOOKTYPE,LNO,DRCR,MCLTCODE,VDT FROM MARGINLEDGER) ML ON L.VNO=ML.VNO AND L.VTYPE=ML.VTYP AND L.BOOKTYPE=ML.BOOKTYPE AND L.LNO=ML.LNO ,(SELECT CLTCODE, ACNAME = LONGNAME, ACCAT, BRANCHCODE FROM ACMAST WITH(NOLOCK) WHERE  GRPCODE LIKE '" + @GRPCODE + "' + '%') A "   
      	SELECT @@WHEREPART  = @@WHEREPART2 + @@ADDWHERE  
   END  
   ELSE IF @OPENENTRYFLAG = 2  
   BEGIN  
      	SELECT @@SELECTQURY = " SELECT ML.PARTY_CODE , ACNAME=ISNULL(A.ACNAME,''), BRANCHCODE,AMOUNT = ISNULL(SUM(CASE WHEN UPPER(ML.DRCR) = 'D' THEN ML.AMOUNT ELSE -ML.AMOUNT END),0), ACCAT,'" + @EXCHANGE + "','MARGIN " + @EXCHANGE + " - " + @SEGMENT +"' "  
      	SELECT @@FROMTABLES = " FROM LEDGER2 L LEFT OUTER JOIN (SELECT PARTY_CODE,AMOUNT,VTYP,VNO,BOOKTYPE,LNO,DRCR,MCLTCODE,VDT FROM MARGINLEDGER) ML ON L.VNO=ML.VNO AND L.VTYPE=ML.VTYP AND L.BOOKTYPE=ML.BOOKTYPE AND L.LNO=ML.LNO ,(SELECT CLTCODE, ACNAME = LONGNAME, ACCAT, BRANCHCODE FROM ACMAST WITH(NOLOCK) WHERE  GRPCODE LIKE '" + @GRPCODE + "' + '%') A "   
      	SELECT @@WHEREPART  = @@WHEREPART3 + @@ADDWHERE  
   END  
END  
END 

	SELECT @@HAVING = " HAVING	CASE WHEN '" + @SHOWZEROBAL + "' <> 'Y' THEN SUM(CASE WHEN UPPER(L.DRCR) = 'D' THEN AMOUNT ELSE -AMOUNT END) ELSE 1 END <> 0  "
  
PRINT @@SELECTQURY + @@FROMTABLES + @@WHEREPART + @@GROUPBY + @@HAVING + @@SORTBY   
  
EXEC (@@SELECTQURY + @@FROMTABLES + @@WHEREPART + @@GROUPBY +  @@HAVING + @@SORTBY )

GO
