-- Object: PROCEDURE dbo.GET_SUBBROKERS
-- Server: 10.253.33.91 | DB: ACCOUNTSLBS
--------------------------------------------------


CREATE PROC GET_SUBBROKERS
AS
DECLARE 
	@@SQL AS VARCHAR(2000),
	@@NSE AS INT,
	@@BSE AS INT,
	@@NSEFO AS INT,
	@@MCX AS INT,
	@@NCDX AS INT

SET NOCOUNT ON

SELECT @@NSE = COUNT(1) FROM MASTER.DBO.SYSDATABASES WHERE NAME = 'MSAJAG'
SELECT @@BSE = COUNT(1) FROM MASTER.DBO.SYSDATABASES WHERE NAME = 'BSEDB'
SELECT @@NSEFO = COUNT(1) FROM MASTER.DBO.SYSDATABASES WHERE NAME = 'NSEFO'
SELECT @@MCX = COUNT(1) FROM MASTER.DBO.SYSDATABASES WHERE NAME = 'MCDX'
SELECT @@NCDX = COUNT(1) FROM MASTER.DBO.SYSDATABASES WHERE NAME = 'NCDX'

SELECT @@SQL = " "

IF @@NSE > 0
	BEGIN
		SELECT @@SQL = @@SQL + "SELECT SUB_BROKER, SBNAME = NAME FROM MSAJAG.DBO.SUBBROKERS UNION "
	END
IF @@BSE > 0
	BEGIN
		SELECT @@SQL = @@SQL + "SELECT SUB_BROKER, SBNAME = NAME FROM BSEDB.DBO.SUBBROKERS UNION "
	END
IF @@NSEFO > 0
	BEGIN
		SELECT @@SQL = @@SQL + "SELECT SUB_BROKER, SBNAME = NAME FROM NSEFO.DBO.SUBBROKERS UNION "
	END
IF @@MCX > 0
	BEGIN
		SELECT @@SQL = @@SQL + "SELECT SUB_BROKER, SBNAME = NAME FROM MCDX.DBO.SUBBROKERS UNION "
	END
IF @@NCDX > 0
	BEGIN
		SELECT @@SQL = @@SQL + "SELECT SUB_BROKER, SBNAME = NAME FROM NCDX.DBO.SUBBROKERS"
	END

SELECT @@SQL = RTRIM(LTRIM(@@SQL))
IF RIGHT(@@SQL, 5) = 'UNION'
	BEGIN
		SELECT @@SQL = LEFT(@@SQL, LEN(@@SQL) - 5)
	END

SELECT @@SQL = "SELECT SUB_BROKER, SBNAME FROM (" + @@SQL + ") A ORDER BY SUB_BROKER, SBNAME"

EXEC (@@SQL)

GO
