-- Object: PROCEDURE dbo.GetCltcode
-- Server: 10.253.33.91 | DB: ACCOUNTSLBS
--------------------------------------------------


CREATE PROCEDURE [dbo].[GetCltcode]
(
	@LETTERS VARCHAR(100),
	@TXTTEXTBOX VARCHAR(1000),
	@EXCSEGMENT VARCHAR(30),
	@STATUSID VARCHAR(25),
	@STATUSNAME VARCHAR(25)
)
AS
/*
	CALLAJAX :: TXTOPPCODE, TXTMARGINCODE, TXTACCOUNT, TXTTPACNUM, TXTCHARGEACCOUNT
	callajaxCC :: CATEGORY, COSTCENTER
*/
/* 
@TXTTEXTBOX = FIELD TYPE TO FIND ~ BOOKTYPE ~ CODE AS PE VTYPE( E.G. BANKCLTCODE FOR VTYPE 3) ~ TXTACCOUNT VALUE
IN CASE OF COST CENTER
@TXTTEXTBOX = FIELD TYPE TO FIND ~ BOOKTYPE ~ BRANCHCODE ~ CAREGORY VALUE ~
@LETTERS = VALUE TO FIND
 EXEC GetCltcode '', 'COSTCENTER~01~ALL~BRANCH', 'NSE-CAPITAL', 'broker', 'broker'

GetCltcode 'H', 'COSTCENTER~01~ALL~BRANCH', '', 'BROKER', 'MEGHA'
GetCltcode '%', 'TXTOPPCODE~01~CASHCLTCODE~~', '', 'BROKER', 'MEGHA'
GetCltcode 'i', 'TXTOPPCODE~01~BANKCLTCODE~~', '', 'BRANCH', 'BRANCH'
GetCltcode '%', 'TXTTPACNUM~01~CASHCLTCODE~CLI00003~', '', 'BROKER', 'BROKER'
GetCltcode '%', 'TXTBRANCHCODE~01~CASHCLTCODE~CLI00003~', '', 'BROKER', 'BROKER'
GetCltcode '', 'TXTADDBY~01~CASHCLTCODE~CLI00003~', 'NSE-CAPITAL', 'BROKER', 'BROKER'


USE MSAJAG
SELECT TOP 2 * FROM CLIENT5
SELECT TOP 2 * FROM CLIENT2
SELECT TOP 2 * FROM POBANK
SELECT TOP 2 * BRANCH
*/
BEGIN
	SET NOCOUNT ON;
	DECLARE @ACTIVEDAYS INT,
	@CONTROLSRC VARCHAR(20),
	@BOOKTYPE VARCHAR(2),
	@CLTFILTER VARCHAR(100),
	@TXTPARTYCODE VARCHAR(10),
	@CATSRC VARCHAR(50),
	@BRCODE VARCHAR(15),
	@CATTEXT VARCHAR(100),
	@BRANCHCODE VARCHAR(20),
	@CODEFLAG INT,
	@GSHAREDBNAME VARCHAR(20),
	@EXCHANGE VARCHAR(20),
	@SEGMENT VARCHAR(20),
	@SQL VARCHAR(MAX)

	SET @EXCHANGE = LTRIM(RTRIM(.DBO.PIECE(@EXCSEGMENT, '-', 1)))
	SET @SEGMENT = LTRIM(RTRIM(.DBO.PIECE(@EXCSEGMENT, '-', 2)))

	SET @CONTROLSRC	= .DBO.PIECE(@TXTTEXTBOX, '~', 1)
	SET @BOOKTYPE = .DBO.PIECE(@TXTTEXTBOX, '~', 2)
	SET @CLTFILTER	= .DBO.PIECE(@TXTTEXTBOX, '~', 3)
	SET @TXTPARTYCODE = .DBO.PIECE(@TXTTEXTBOX, '~', 4)
--	SET @CATSRC	= .DBO.PIECE(@TXTTEXTBOX, '~', 1)
--	SET @BRCODE	= .DBO.PIECE(@TXTTEXTBOX, '~', 3)
--	SET @CATTEXT = .DBO.PIECE(@TXTTEXTBOX, '~', 4)

	SELECT @ACTIVEDAYS = ACTIVEDAYS FROM OWNER
	SELECT @CODEFLAG = CASE ACCAT WHEN  '3' THEN 1 WHEN '4' THEN 2 ELSE 0 END FROM ACMAST WHERE CLTCODE = @TXTPARTYCODE
	
	IF UPPER(LTRIM(RTRIM(@CONTROLSRC))) = 'TXTACCOUNT'
		BEGIN
			IF @CLTFILTER = 'JVCODES'
				BEGIN
					SELECT TOP 5 LTRIM(RTRIM(CLTCODE)) + '~' + LTRIM(RTRIM(BRANCHCODE)) + '~' + LTRIM(RTRIM(LONGNAME)),
						'(' + CLTCODE + ') -' + ACNAME 
					FROM ACMAST (NOLOCK)
					WHERE ACCAT NOT IN  ('1','2','18')
						AND (LEFT(ACNAME,LEN(@LETTERS)) = @LETTERS OR LEFT(CLTCODE, LEN(@LETTERS)) = @LETTERS)
						AND BRANCHCODE = CASE WHEN @STATUSID = 'BRANCH' THEN @STATUSNAME ELSE BRANCHCODE END
					ORDER BY 2,1
				END
			ELSE
				BEGIN
				SELECT TOP 5 LTRIM(RTRIM(CLTCODE)) + '~' + LTRIM(RTRIM(BRANCHCODE)) + '~' + LTRIM(RTRIM(LONGNAME)),
							'(' + CLTCODE + ') -' + ACNAME
				FROM ACMAST A (NOLOCK)
				WHERE ACCAT IN  ('3','4','18')
					AND (LEFT(ACNAME,LEN(@LETTERS)) = @LETTERS OR LEFT(CLTCODE,LEN(@LETTERS)) = @LETTERS)
					AND NOT EXISTS ( SELECT PARTY_CODE, INACTIVEFROM 
									FROM MSAJAG.DBO.CLIENT5 C5 WITH(NOLOCK), MSAJAG.DBO.CLIENT2 C2 WITH(NOLOCK)
									WHERE LTRIM(RTRIM(C2.CL_CODE)) = C5.CL_CODE 
											AND DATEADD(DAY,@ACTIVEDAYS,INACTIVEFROM) <= GETDATE() 
											AND A.CLTCODE = PARTY_CODE
									)		
					AND (BRANCHCODE =  CASE WHEN @STATUSID = 'BRANCH' THEN @STATUSNAME ELSE BRANCHCODE END
						OR BRANCHCODE = CASE WHEN @STATUSID = 'BRANCH' THEN 'ALL' ELSE BRANCHCODE END)
				ORDER BY 2,1
			END
		END
	ELSE IF  UPPER(LTRIM(RTRIM(@CONTROLSRC))) = 'TXTCHARGEACCOUNT'
		BEGIN
			SELECT LTRIM(RTRIM(CLTCODE)) + '~' + LTRIM(RTRIM(BRANCHCODE)) + '~' + LTRIM(RTRIM(LONGNAME)),
				'(' + cltcode + ') -' + acname
			from AcMast (NoLock)
			WHERE ACCAT  IN  ('3','18')
				AND (LEFT(ACNAME,LEN(@LETTERS)) = @LETTERS OR LEFT(CLTCODE,LEN(@LETTERS)) = @LETTERS)
				AND BRANCHCODE LIKE CASE WHEN @STATUSID = 'BRANCH' THEN @STATUSNAME ELSE '%' END
			ORDER BY 2,1
		END
	ELSE IF  UPPER(LTRIM(RTRIM(@CONTROLSRC))) = 'TXTOPPCODE'
		BEGIN
			IF @CLTFILTER = 'BANKCLTCODE' OR @CLTFILTER = 'CASHCLTCODE'
				BEGIN					
					SELECT TOP 5 CLTCODE + '~' + LONGNAME + '~' + BRANCHCODE, '(' + CLTCODE + ') -' + LONGNAME
					FROM ACMAST
					WHERE ACCAT  = CASE WHEN @CLTFILTER = 'BANKCLTCODE' THEN '2' ELSE '1' END
						AND BOOKTYPE LIKE @BOOKTYPE
						AND (LEFT(ACNAME,LEN(@LETTERS)) = @LETTERS OR LEFT(CLTCODE,LEN(@LETTERS)) = @LETTERS)
						AND (BRANCHCODE LIKE CASE WHEN @STATUSID = 'BRANCH' THEN @STATUSNAME ELSE '%' END
						OR  LTRIM(RTRIM(BRANCHCODE)) LIKE 'ALL')
					ORDER BY 2,1
				END
		ELSE
			BEGIN
				SELECT TOP 10 LTRIM(RTRIM(CLTCODE))+'~'+LTRIM(RTRIM(BRANCHCODE))+'~'+LTRIM(RTRIM(LONGNAME)),
					'(' + CLTCODE + ') -' +ACNAME
				FROM ACMAST(NOLOCK)
				WHERE ACCAT = '4'
					AND (ACCAT = CASE WHEN @CLTFILTER <> 'MJVCODES' THEN '3' ELSE ACCAT END
					OR ACCAT = CASE WHEN @CLTFILTER <> 'MJVCODES' THEN '18' ELSE ACCAT END)
					AND ((LEFT(ACNAME,LEN(@LETTERS)) = @LETTERS)  OR (LEFT(CLTCODE,LEN(@LETTERS)) = @LETTERS))
					AND BRANCHCODE LIKE CASE WHEN @STATUSID = 'BRANCH' THEN @STATUSNAME ELSE '%' END
				ORDER BY 2,1
			END
	END
	ELSE IF  UPPER(LTRIM(RTRIM(@CONTROLSRC))) = 'TXTMARGINCODE'
		BEGIN
			SELECT TOP 5 CLTCODE+'~'+LONGNAME+'~'+BRANCHCODE,'(' + CLTCODE + ') -' +LONGNAME
				FROM ACMAST(NOLOCK)
				WHERE ACCAT  IN ('3', '4', '14')
					AND ((LEFT(ACNAME,LEN(@LETTERS)) = @LETTERS) OR (LEFT(CLTCODE,LEN(@LETTERS)) = @LETTERS))
					AND (BRANCHCODE LIKE CASE WHEN @STATUSID = 'BRANCH' THEN @STATUSNAME ELSE '%' END
						OR  LTRIM(RTRIM(BRANCHCODE)) LIKE 'ALL')
				ORDER BY 2,1
		END
	ELSE IF UPPER(LTRIM(RTRIM(@CONTROLSRC))) = 'TXTTPACNUM' AND @CODEFLAG = 2
		BEGIN
			SELECT TOP 10 A.ACCNO + '~' + A.CHEQUENAME + '~' + ISNULL(B.BANK_NAME,'') + '~' + ISNULL(B.BRANCH_NAME,''),
				A.DEFAULTBANK + '~' + '('+A.ACCNO+') - '+ ISNULL(B.BANK_NAME,'')+'~'+ISNULL(B.BRANCH_NAME,'')
			FROM MULTIBANKID A LEFT OUTER JOIN MSAJAG.DBO.POBANK B ON (A.BANKID = B.BANKID)
			WHERE 1=1
				AND A.CLTCODE = @TXTPARTYCODE
			ORDER BY 2,1
		END
	ELSE IF UPPER(LTRIM(RTRIM(@CONTROLSRC))) = 'TXTBRANCHCODE'
		BEGIN
			SELECT TOP 5 LTRIM(RTRIM(C.COSTNAME)) + '~' + LTRIM(RTRIM(S.LONG_NAME)), '('+LTRIM(RTRIM(C.COSTNAME))+') - '+LTRIM(RTRIM(S.LONG_NAME)), B.DEFAULTAC
			FROM BRANCHACCOUNTS B inner join costmast c on (c.costName = b.branchname)
				INNER JOIN MSAJAG.DBO.BRANCHES S ON (S.BRANCH_CD = B.BRANCHNAME)
			WHERE ((LEFT(C.COSTNAME,LEN(@LETTERS)) = @LETTERS) OR (LEFT(S.LONG_NAME,LEN(@LETTERS)) = @LETTERS))				
				AND C.COSTNAME LIKE  CASE WHEN @STATUSID = 'BRANCH' THEN @STATUSNAME ELSE C.COSTNAME END
			ORDER BY 3 DESC,2
		END
	ELSE IF UPPER(LTRIM(RTRIM(@CONTROLSRC))) = 'CATEGORY' OR  UPPER(LTRIM(RTRIM(@CONTROLSRC))) = 'COSTCENTER'
		BEGIN
			SET @CATSRC	= .DBO.PIECE(@TXTTEXTBOX, '~', 1)
			SET @BRCODE	= UPPER(LTRIM(RTRIM(.DBO.PIECE(@TXTTEXTBOX, '~', 3))))
			SET @CATTEXT = .DBO.PIECE(@TXTTEXTBOX, '~', 4)
			
			IF @CATSRC = 'CATEGORY'
				BEGIN
					SELECT RTRIM(LTRIM(CATCODE)), RTRIM(LTRIM(UPPER(CATEGORY)))
					FROM CATEGORY
					WHERE (category LIKE @LETTERS + '%' or catcode LIKE @LETTERS + '%')
							AND CATEGORY <> 'BRANCH'--CASE WHEN @BRCODE <> 'ALL' THEN 'BRANCH' ELSE '' END
				END
			ELSE -- COSTCENTER --
				 -- GetCltcode 'H', 'COSTCENTER~01~ALL~BRANCH', '', 'BROKER', 'MEGHA'
				BEGIN
					SELECT COSTCODE = RTRIM(LTRIM(CC.COSTCODE)), COSTNAME = RTRIM(LTRIM(UPPER(CC.COSTNAME)))
					FROM CATEGORY C, COSTMAST CC
					WHERE C.CATCODE=CC.CATCODE 
						AND C.CATEGORY= @CATTEXT
						AND CC.COSTNAME = CASE WHEN @STATUSID = 'BRANCH' AND @CATTEXT = 'BRANCH' THEN @STATUSNAME ELSE CC.COSTNAME END
						AND CC.COSTNAME  LIKE CASE WHEN @STATUSID = 'BRANCH' AND @CATTEXT = 'BRANCH' THEN @STATUSNAME ELSE @LETTERS + '%' END
					ORDER BY RTRIM(LTRIM(CC.COSTCODE)), CC.COSTNAME
				
				END			
		END
	ELSE IF UPPER(LTRIM(RTRIM(@CONTROLSRC))) = 'TXTADDBY' OR  UPPER(LTRIM(RTRIM(@CONTROLSRC))) = 'TXTFILTERON'
		BEGIN --
			SELECT @GSHAREDBNAME = UPPER(LTRIM(RTRIM(SHAREDB)))  FROM VW_MULTICOMPANY WHERE EXCHANGE = @EXCHANGE AND SEGMENT = @SEGMENT
			IF @GSHAREDBNAME <> ''
				BEGIN
					SET @SQL = "SELECT TOP 10 UPPER(FLDUSERNAME), UPPER(FLDFIRSTNAME) FROM " + @GSHAREDBNAME + ".DBO.TBLPRADNYAUSERS  "
					SET @SQL = @SQL + "WHERE ((LEFT(FLDUSERNAME," + CONVERT(VARCHAR, LEN(@LETTERS)) + ") = '" + @LETTERS + "') OR (LEFT(FLDFIRSTNAME," + CONVERT(VARCHAR, LEN(@LETTERS)) + ") = '" + @LETTERS + "')) "
					SET @SQL = @SQL + "ORDER BY 1"
					EXEC(@SQL)
				END
		END

END

/*
EXEC GetCltcode 'hO', 'COSTCENTER~01~ALL~BRANCH', 'NSE-CAPITAL', 'broker', 'broker'

SELECT RTRIM(LTRIM(CC.COSTCODE)), COSTNAME = RTRIM(LTRIM(UPPER(CC.COSTNAME)))
					FROM CATEGORY C, COSTMAST CC
					WHERE C.CATCODE=CC.CATCODE 
						AND C.CATEGORY= @CATTEXT
						AND CC.COSTNAME = CASE WHEN @STATUSID = 'BRANCH' AND @CATTEXT = 'BRANCH' THEN @STATUSNAME ELSE CC.COSTNAME END
						AND CATEGORY LIKE CASE WHEN @STATUSID = 'BRANCH' AND @CATTEXT = 'BRANCH' THEN @LETTERS + '%' ELSE CATEGORY END
						--AND (COSTCODE LIKE @LETTERS + '%' OR COSTCODE LIKE @LETTERS + '%')
						AND COSTCODE LIKE CASE WHEN @STATUSID = 'BRANCH' AND @CATTEXT = 'BRANCH' THEN COSTCODE ELSE @LETTERS + '%' END
					ORDER BY CC.COSTNAME					
				
*/

GO
