-- Object: PROCEDURE dbo.SELECTION_QUERIES_PROC
-- Server: 10.253.33.91 | DB: ACCOUNTSLBS
--------------------------------------------------

--EXEC SELECTION_QUERIES_PROC 'BROKER','%','REGION','%'
CREATE PROC SELECTION_QUERIES_PROC
@STATUSID VARCHAR(15),
@STATUSNAME VARCHAR(10),
@SELECTON VARCHAR(15),
@SEARCH VARCHAR(10),
@FROMAC VARCHAR(10) = '0000000000',
@TOAC VARCHAR(10) = 'ZZZZZZZZZZ'
AS

DECLARE
@@SELECTIONQUERY AS VARCHAR(500),
@@FINALQUERY AS VARCHAR(500)

DECLARE CUR_SELECTION_PARAMETER CURSOR FOR
	SELECT 
		SELECTIONQUERY
	FROM
		SELECTION_QUERIES_TABLE
	WHERE
		STATUSID = @STATUSID
		AND SELECTON = @SELECTON		
        
        OPEN CUR_SELECTION_PARAMETER
        
        FETCH NEXT FROM CUR_SELECTION_PARAMETER
        INTO @@SELECTIONQUERY

WHILE @@FETCH_STATUS = 0        
BEGIN
	SELECT @@FINALQUERY = REPLACE(@@SELECTIONQUERY, 'STATUSNAME', '''' + @STATUSNAME + '''')
	SELECT @@FINALQUERY = REPLACE(@@FINALQUERY, 'FROMAC', '''' + @FROMAC + '''')
	SELECT @@FINALQUERY = REPLACE(@@FINALQUERY, 'TOAC', '''' + @TOAC + '''')
	SELECT @@FINALQUERY = REPLACE(@@FINALQUERY, 'SEARCH', '''' + @SEARCH + '''')

	FETCH NEXT FROM CUR_SELECTION_PARAMETER
	INTO @@SELECTIONQUERY
END

CLOSE CUR_SELECTION_PARAMETER
DEALLOCATE CUR_SELECTION_PARAMETER

PRINT @@FINALQUERY
EXEC (@@FINALQUERY)

GO
