-- Object: PROCEDURE dbo.UNCLEARED_CHEQUES
-- Server: 10.253.33.91 | DB: ACCOUNTSLBS
--------------------------------------------------

CREATE PROC UNCLEARED_CHEQUES  
@FROM_CODE VARCHAR(10),  
@TO_CODE VARCHAR(10),  
@VDT VARCHAR(11),
@BANKCODE_FR VARCHAR(10) = '0', 
@BANKCODE_TO VARCHAR(10) = 'Z'
  
AS  
  
SELECT   
 L.VNO, VDT = CONVERT(VARCHAR(10), VDT, 103), EDT = CONVERT(VARCHAR(10), EDT, 103),   
 CLTCODE, ACNAME, DDNO, VAMT, BANK_CODE  
FROM   
 (SELECT * FROM LEDGER WHERE VDT <= @VDT + ' 23:59' AND EDT > @VDT + ' 23:59' AND CLTCODE BETWEEN @FROM_CODE AND @TO_CODE AND VTYP = 2) L,   
 LEDGER1 L1,
 (SELECT VNO, VTYP, BOOKTYPE, BANK_CODE = CLTCODE FROM LEDGER WHERE CLTCODE BETWEEN @BANKCODE_FR AND @BANKCODE_TO) L2 
WHERE  
 L.VNO = L1.VNO AND L.VTYP = L1.VTYP AND L.BOOKTYPE = L1.BOOKTYPE AND L.LNO = L1.LNO  
 AND L.VNO = L2.VNO AND L.VTYP = L2.VTYP AND L.BOOKTYPE = L2.BOOKTYPE AND L.CLTCODE <> BANK_CODE

GO
