-- Object: PROCEDURE dbo.PR_CLASSFILEUPD
-- Server: 10.253.33.91 | DB: ACCOUNTSLBS
--------------------------------------------------

CREATE PROC [dbo].[PR_CLASSFILEUPD]
(
	@USERNAME VARCHAR(20),
	@SESSION_ID VARCHAR(30),
	@FILE_TYPE VARCHAR(100)
)
AS

  SET NOCOUNT ON 

  DECLARE @RETMESSAGE VARCHAR(1000) 

  SET @RETMESSAGE = @FILE_TYPE + ' - FILE UPLOADED SUCCESSFULLY' 

  IF @FILE_TYPE = 'APP SECURITIES(NSECM)' OR @FILE_TYPE = 'APP SECURITIES(NSEFO)'   
    BEGIN   
      EXEC MSAJAG.DBO.V2_APPROVEDSECURITIES_NSE @USERNAME,@SESSION_ID,@FILE_TYPE  
    END  
  
  IF @FILE_TYPE = 'APP SECURITIES'   
    BEGIN   
      EXEC MSAJAG.DBO.V2_APPROVEDSECURITIES_BROKER @USERNAME,@SESSION_ID,@FILE_TYPE  
    END  
  
  IF @FILE_TYPE = 'FNO EXPOSURE(PMS)'   
    BEGIN   
      EXEC NSEFO.DBO.V2_FNOEXPOSUREPMS_UP @USERNAME,@SESSION_ID,@FILE_TYPE,@RETMESSAGE OUTPUT  
    END  
  
  IF @FILE_TYPE = 'JV FILE(PMS)'   
    BEGIN   
      EXEC ACCOUNTFO.DBO.JVUPLOAD_PMS @USERNAME,@SESSION_ID,@FILE_TYPE ,8,'02',@RETMESSAGE OUTPUT   
    END  
  
  IF @FILE_TYPE = 'BANK RECEIPT(PMS)'   
    BEGIN   
      EXEC RECPAYUPLOAD_PMS @USERNAME,@SESSION_ID,@FILE_TYPE,@RETMESSAGE OUTPUT  
    END  
  
  IF @FILE_TYPE = 'BANK PAYMENT(PMS)'   
    BEGIN   
      EXEC RECPAYUPLOAD_PMS @USERNAME,@SESSION_ID,@FILE_TYPE,@RETMESSAGE OUTPUT  
    END  

  IF @FILE_TYPE = 'BANK RECEIPT FO(PMS)'   
    BEGIN   
      EXEC ACCOUNTFO.DBO.RECPAYUPLOAD_PMS @USERNAME,@SESSION_ID,@FILE_TYPE,@RETMESSAGE OUTPUT  
    END  
  
  IF @FILE_TYPE = 'BANK PAYMENT FO(PMS)'   
    BEGIN   
      EXEC ACCOUNTFO.DBO.RECPAYUPLOAD_PMS @USERNAME,@SESSION_ID,@FILE_TYPE,@RETMESSAGE OUTPUT  
    END 
  
  IF @FILE_TYPE = 'ADDITIONAL TRADE DETAILS'   
    BEGIN   
      EXEC MSAJAG.DBO.PMS_TRADEDETAILS_UP @USERNAME,@SESSION_ID,@FILE_TYPE,@RETMESSAGE OUTPUT  
    END  

  IF @FILE_TYPE = 'POA HOLDING(PMS)'   
    BEGIN   
      EXEC MSAJAG.DBO.PMS_POABALANCES_UP @USERNAME,@SESSION_ID,@FILE_TYPE,@RETMESSAGE OUTPUT  
    END  

  IF @FILE_TYPE = 'BANK ENTRIES'     
    BEGIN     
      EXEC RECPAYUPLOAD @USERNAME,@SESSION_ID,@FILE_TYPE,@RETMESSAGE OUTPUT    
    END   

  IF @FILE_TYPE = 'JOURNAL VOUCHER'     
    BEGIN     
      EXEC DRCRNOTEUPLOAD @USERNAME,@SESSION_ID,@FILE_TYPE,@RETMESSAGE OUTPUT    
    END 

  IF @FILE_TYPE = 'DEBIT NOTE'     
    BEGIN     
      EXEC DRCRNOTEUPLOAD @USERNAME,@SESSION_ID,@FILE_TYPE,@RETMESSAGE OUTPUT    
    END 

  IF @FILE_TYPE = 'CREDIT NOTE'     
    BEGIN     
      EXEC DRCRNOTEUPLOAD @USERNAME,@SESSION_ID,@FILE_TYPE,@RETMESSAGE OUTPUT    
    END 



  DELETE CLASSFILEUPD   
  WHERE  SESSION_ID = @SESSION_ID   
  
  SELECT @RETMESSAGE

GO
