-- Object: PROCEDURE dbo.PREPAIDCARD_CHARGES_UPLOAD
-- Server: 10.253.33.91 | DB: ACCOUNTSLBS
--------------------------------------------------


CREATE PROC [DBO].[PREPAIDCARD_CHARGES_UPLOAD]  
 @UNAME VARCHAR(25),  
 @VTYP SMALLINT,  
 @BOOKTYPE VARCHAR(2),
 @TRADEDATE VARCHAR(11),
 @GLCODE VARCHAR(10)
AS  
 
 SET NOCOUNT ON  
  
 DECLARE  
  @@ERROR_COUNT AS INT,  
  @@SQL AS VARCHAR(2000),  
  @TRDATE  VARCHAR(10),
  @SERGLCODE VARCHAR(10),
  @EDUCESSTAXCODE VARCHAR(10),
  @CESS_TAXCODE VARCHAR(10),
  @BROKGLCODE VARCHAR(10)

SELECT @SERGLCODE=ACCODE FROM MSAJAG.DBO.VALANACCOUNT WHERE ACNAME = 'SERVICE TAX'
SELECT @CESS_TAXCODE=ACCODE FROM MSAJAG.DBO.VALANACCOUNT WHERE ACNAME = 'CESS TAX'
SELECT @EDUCESSTAXCODE=ACCODE FROM MSAJAG.DBO.VALANACCOUNT WHERE ACNAME = 'EDU CESS TAX'
SELECT @BROKGLCODE=ACCODE FROM MSAJAG.DBO.VALANACCOUNT WHERE ACNAME = 'BROKERAGE REALISED'

SELECT @TRDATE = CONVERT(VARCHAR,CONVERT(DATETIME,@TRADEDATE),103)

 CREATE TABLE [#RECPAY_TABLE]  
 (  
  SRNO INT,  
  VVDT VARCHAR(10),  
  EEDT VARCHAR(10),  
  CLTCODE VARCHAR(10),  
  DRCR VARCHAR(1),  
  AMOUNT MONEY,  
  NARRATION VARCHAR(500),  
  SNO INT IDENTITY (1, 1) NOT NULL ,  
  VDT DATETIME NULL ,  
  UPDFLAG VARCHAR (1)  NOT NULL DEFAULT('N'),  
  EDT DATETIME NULL ,  
  VNO VARCHAR (12)  NULL ,  
  ACNAME VARCHAR (100)  NULL ,  
  FYSTART DATETIME NULL,  
  FYEND DATETIME NULL,  
  COSTCODE SMALLINT NULL,  
  LNO SMALLINT NOT NULL DEFAULT(0)  
 ) ON [PRIMARY]  
  
 CREATE TABLE [#RECPAY_TABLE_LNO]  
 (  
  SNO INT ,  
  LNO INT IDENTITY (1, 1) NOT NULL  
 ) ON [PRIMARY]  
  

  CREATE TABLE #RECPAY_TABLE_TMP  
  (  
   SRNO INT  IDENTITY (1, 1) NOT NULL,  
   CLTCODE VARCHAR(10),  
   DRCR VARCHAR(1),  
   AMOUNT MONEY,  
   NARRATION VARCHAR(500),
   SERTAXFLAG INT,
   BROKAMT MONEY,
   SERTAXAMT MONEY,
   CESS_TAX MONEY,
   EDUCESSTAX MONEY,
   FLAG INT
  )  
  
--------------- WRITE YOUR SELECT QUERY TO INSERT THE DATA IN #RECPAY_TABLE_TMP TABLE ----------------
	INSERT INTO #RECPAY_TABLE_TMP (CLTCODE,DRCR,AMOUNT,NARRATION,SERTAXFLAG, BROKAMT, SERTAXAMT, CESS_TAX, EDUCESSTAX, FLAG)
	SELECT PARTY_CODE,'D',PP_SCHEME_AMT=(CASE WHEN PP_SERVICE_TAX = 1 THEN PP_SCHEME_AMT ELSE PP_SCHEME_AMT + ROUND(PP_SCHEME_AMT * SERVICE_TAX / 100,2) END),
    NARRATION='PRE PAID BROKERAGE', PP_SERVICE_TAX,
	PP_BROK_AMT = ROUND((CASE WHEN PP_SERVICE_TAX = 1 THEN PP_SCHEME_AMT * 100 / (100 + SERVICE_TAX) ELSE PP_SCHEME_AMT END),2),
	PP_SER_AMT = (CASE WHEN PP_SERVICE_TAX = 1 
					   THEN PP_SCHEME_AMT - ROUND(PP_SCHEME_AMT * 100 / (100 + SERVICE_TAX),2) 
					   ELSE ROUND(PP_SCHEME_AMT * SERVICE_TAX / 100,2)
				  END),
    CESS_TAX, EDUCESSTAX, 1
	FROM MSAJAG.DBO.TBL_PREPAID_MAPPING PM,MSAJAG.DBO.TBL_PREPAID_SCHEME PS, MSAJAG.DBO.GLOBALS G WHERE
	PM.PP_SCHEME_NO = PS.PP_SCHEME_NO
	AND @TRADEDATE  BETWEEN PP_FROM_DATE AND PP_TO_DATE 
	AND AMT_POSTED = 0 
	AND PP_FROM_DATE BETWEEN YEAR_START_DT AND YEAR_END_DT

	INSERT INTO #RECPAY_TABLE_TMP (CLTCODE,DRCR,AMOUNT,NARRATION,SERTAXFLAG, BROKAMT, SERTAXAMT, CESS_TAX, EDUCESSTAX, FLAG)
    SELECT @GLCODE, 'D', SUM(REL_AMT), 
	NARRATION = 'REL PRE PAID BROKERAGE', 0, 0, 0, 0, 0, 2 FROM MSAJAG.DBO.TBL_PREPAID_TRANS
    WHERE PP_TRANS_DATE LIKE @TRADEDATE + '%'
    AND POSTFLAG = 0 AND PP_AMTTYPE IN ('C', 'T')

	INSERT INTO #RECPAY_TABLE_TMP (CLTCODE,DRCR,AMOUNT,NARRATION,SERTAXFLAG, BROKAMT, SERTAXAMT, CESS_TAX, EDUCESSTAX, FLAG)
    SELECT PARTY_CODE, 'D', REL_AMT, 
	NARRATION = 'PRE PAID BROKERAGE', 0, 
	PP_BROK_AMT = ROUND(REL_AMT * 100 / (100 + SERVICE_TAX), 2), 
    PP_SER_AMT = REL_AMT - ROUND(REL_AMT * 100 / (100 + SERVICE_TAX), 2), 
    CESS_TAX, EDUCESSTAX, 3 FROM MSAJAG.DBO.TBL_PREPAID_TRANS, MSAJAG.DBO.GLOBALS G
    WHERE PP_TRANS_DATE LIKE @TRADEDATE + '%'
    AND POSTFLAG = 0 AND PP_AMTTYPE = 'A'
	AND @TRADEDATE BETWEEN YEAR_START_DT AND YEAR_END_DT

  INSERT INTO #RECPAY_TABLE  
   (SRNO,  
   VVDT,  
   EEDT,
   CLTCODE,  
   DRCR,  
   AMOUNT,  
   NARRATION)  
  SELECT  
   SRNO,  
   @TRDATE AS VVDT,  
   @TRDATE AS EEDT,  
   UPPER(CLTCODE),  
   DRCR,  
   AMOUNT,  
   LEFT(NARRATION, 234)  
  FROM #RECPAY_TABLE_TMP  
  WHERE AMOUNT > 0 AND FLAG IN (2, 3)

  INSERT INTO #RECPAY_TABLE  
   (SRNO,  
   VVDT,  
   EEDT,
   CLTCODE,  
   DRCR,  
   AMOUNT,  
   NARRATION)  
  SELECT  
   SRNO,  
   @TRDATE AS VVDT,  
   @TRDATE AS EEDT,  
   UPPER(@BROKGLCODE),  
   DRCR='C',  
   AMOUNT=(CASE WHEN FLAG = 2 THEN AMOUNT ELSE BROKAMT END),  
   LEFT(NARRATION, 234)  
  FROM #RECPAY_TABLE_TMP  
  WHERE AMOUNT > 0 AND FLAG IN (2 ,3)

  INSERT INTO #RECPAY_TABLE  
   (SRNO,  
   VVDT,  
   EEDT,
   CLTCODE,  
   DRCR,  
   AMOUNT,  
   NARRATION)  
  SELECT  
   SRNO,  
   @TRDATE AS VVDT,  
   @TRDATE AS EEDT,  
   UPPER(CLTCODE),  
   DRCR,  
   AMOUNT,  
   LEFT(NARRATION, 234)  
  FROM #RECPAY_TABLE_TMP  
  WHERE AMOUNT > 0 AND FLAG = 1

  INSERT INTO #RECPAY_TABLE  
   (SRNO,  
   VVDT,  
   EEDT,
   CLTCODE,  
   DRCR,  
   AMOUNT,  
   NARRATION)  
  SELECT  
   SRNO,  
   @TRDATE AS VVDT,  
   @TRDATE AS EEDT,  
   @GLCODE,  
   'C',  
   BROKAMT,  
   LEFT(NARRATION, 234)  
  FROM #RECPAY_TABLE_TMP 
  WHERE BROKAMT > 0 AND FLAG = 1

  INSERT INTO #RECPAY_TABLE  
   (SRNO,  
   VVDT,  
   EEDT,
   CLTCODE,  
   DRCR,  
   AMOUNT,  
   NARRATION)  
  SELECT  
   SRNO,  
   @TRDATE AS VVDT,  
   @TRDATE AS EEDT,  
   @SERGLCODE,  
   'C',  
   SERTAXAMT = SERTAXAMT - ROUND((SERTAXAMT * CESS_TAX) / (100 + EDUCESSTAX + CESS_TAX),2) - ROUND((SERTAXAMT * EDUCESSTAX) / (100 + EDUCESSTAX + CESS_TAX),2),  
   LEFT(NARRATION, 234)  
  FROM #RECPAY_TABLE_TMP
  WHERE SERTAXAMT > 0 AND FLAG IN (1, 3)

  INSERT INTO #RECPAY_TABLE  
   (SRNO,  
   VVDT,  
   EEDT,
   CLTCODE,  
   DRCR,  
   AMOUNT,  
   NARRATION)  
  SELECT  
   SRNO,  
   @TRDATE AS VVDT,  
   @TRDATE AS EEDT,  
   @CESS_TAXCODE,  
   'C',  
   CESSTAXAMT = ROUND((SERTAXAMT * CESS_TAX) / (100 + CESS_TAX + EDUCESSTAX),2),  
   LEFT(NARRATION, 234)  
  FROM #RECPAY_TABLE_TMP
  WHERE ROUND((SERTAXAMT * CESS_TAX) / (100 + CESS_TAX + EDUCESSTAX),2) > 0 AND FLAG IN (1, 3)

  INSERT INTO #RECPAY_TABLE  
   (SRNO,  
   VVDT,  
   EEDT,
   CLTCODE,  
   DRCR,  
   AMOUNT,  
   NARRATION)  
  SELECT  
   SRNO,  
   @TRDATE AS VVDT,  
   @TRDATE AS EEDT,  
   @EDUCESSTAXCODE,  
   'C',  
   EDUCESSTAXAMT = ROUND((SERTAXAMT * EDUCESSTAX) / (100 + EDUCESSTAX + CESS_TAX),2),  
   LEFT(NARRATION, 234)  
  FROM #RECPAY_TABLE_TMP
  WHERE ROUND((SERTAXAMT * EDUCESSTAX) / (100 + EDUCESSTAX + CESS_TAX),2) > 0 AND FLAG IN (1, 3)

  UPDATE  
   #RECPAY_TABLE  
   SET  
    VDT = CONVERT(DATETIME, RIGHT(VVDT,4) + '-' + SUBSTRING(VVDT,4,2) + '-' + LEFT(VVDT,2)),  
    EDT = CONVERT(DATETIME, RIGHT(EEDT,4) + '-' + SUBSTRING(EEDT,4,2) + '-' + LEFT(EEDT,2)),  
    FYSTART = P.SDTCUR,  
    FYEND = P.LDTCUR,  
    UPDFLAG = 'Y',  
    ACNAME = LONGNAME,  
    COSTCODE = C.COSTCODE  
    FROM ACMAST A, PARAMETER P, COSTMAST C  
    WHERE A.CLTCODE = #RECPAY_TABLE.CLTCODE  
    AND P.CURYEAR = 1  
    AND A.ACCAT IN ('3','4','104')  
    AND A.BRANCHCODE = C.COSTNAME  
    AND A.BRANCHCODE <> 'ALL'  
  
    UPDATE  
   #RECPAY_TABLE  
   SET  
    VDT = CONVERT(DATETIME, RIGHT(VVDT,4) + '-' + SUBSTRING(VVDT,4,2) + '-' + LEFT(VVDT,2)),  
    EDT = CONVERT(DATETIME, RIGHT(EEDT,4) + '-' + SUBSTRING(EEDT,4,2) + '-' + LEFT(EEDT,2)),  
    FYSTART = P.SDTCUR,  
    FYEND = P.LDTCUR,  
    UPDFLAG = 'Y',  
    ACNAME = LONGNAME,  
    COSTCODE = (SELECT TOP 1 COSTCODE FROM COSTMAST WHERE COSTNAME = 'HO')  
    FROM ACMAST A, PARAMETER P  
    WHERE A.CLTCODE = #RECPAY_TABLE.CLTCODE  
    AND P.CURYEAR = 1  
    AND A.ACCAT IN ('3','4','104')  
    AND A.BRANCHCODE = 'ALL'  
 
/* '--------------------------DECLARATION OF VARIABLES FOR VALIDATIONS ------------------------*/  
  
 DECLARE  
  @@STD_DATE VARCHAR(11),  
  @@LST_DATE VARCHAR(11),  
  @@VNOMETHOD INT,  
  @@ACNAME CHAR(100),  
  @@MICRNO VARCHAR(10),  
  @@DRCR VARCHAR(1)  
  
  
/* '--------------------------VALIDATION FOR VOUCHER DATE NOT IN CURRENT FIN YEAR ------------------------*/  
  
 SELECT @@ERROR_COUNT = COUNT(1) FROM #RECPAY_TABLE WHERE VDT NOT BETWEEN FYSTART AND FYEND  
  
 IF @@ERROR_COUNT > 0  
  BEGIN  
   SELECT 'DATE MISMATCH'  
   DROP TABLE #RECPAY_TABLE_TMP  
   DROP TABLE #RECPAY_TABLE  
     
   RETURN  
  END  
  
/* '--------------------------UPDATE OF COST CODE ------------------------*/  
  
 UPDATE #RECPAY_TABLE  
  SET COSTCODE = (SELECT TOP 1 COSTCODE FROM COSTMAST WHERE COSTNAME = 'HO')  
 WHERE COSTCODE IS NULL  

/*--------------------------VALIDATION FOR DIFFERENT VDTS IN SAME VOUCHER ------------------------*/  
  
 SELECT @@ERROR_COUNT = COUNT(DISTINCT VDT) FROM  #RECPAY_TABLE WHERE SRNO IN (SELECT DISTINCT SRNO FROM #RECPAY_TABLE)  
 GROUP BY SRNO HAVING COUNT(DISTINCT VDT) > 1  
 IF @@ERROR_COUNT > 0  
  BEGIN  
   SELECT 'SOME OF THE VOUCHERS ARE HAVING DIFFERENT VOUCHER DATES'  
   DROP TABLE #RECPAY_TABLE_TMP  
   DROP TABLE #RECPAY_TABLE  
     
   RETURN  
  END  
  
/*--------------------------VALIDATION FOR DRCR MISMATCH IN SAME VOUCHER ------------------------*/  
  
 SELECT @@ERROR_COUNT = COUNT(1) FROM  
  (SELECT AMOUNT = SUM(CASE WHEN DRCR = 'D' THEN AMOUNT ELSE -AMOUNT END)  
  FROM #RECPAY_TABLE  
  GROUP BY SRNO  
  HAVING SUM(CASE WHEN DRCR = 'D' THEN AMOUNT ELSE -AMOUNT END) <> 0) A  
 IF @@ERROR_COUNT > 0  
  BEGIN  
   SELECT 'DEBIT AND CREDIT TOTALS DO NOT MATCH IN SOME VOUCHERS.'  
   DROP TABLE #RECPAY_TABLE_TMP  
   DROP TABLE #RECPAY_TABLE  
     
   RETURN  
  END  
  
/* '--------------------------FINAL VALIDATION BASED ON UPDFLAG ------------------------*/  
  
 SELECT @@ERROR_COUNT = COUNT(1) FROM  
 (  
  SELECT DISTINCT  
   CLTCODE  
  FROM #RECPAY_TABLE  
  WHERE UPDFLAG = 'N'  
 ) A  
  
 IF @@ERROR_COUNT > 0  
  BEGIN  
   SELECT 'FILE CANNOT BE UPLOADED AS THE FOLLOWING CLIENTS DO NOT EXIST' UNION ALL  
   SELECT DISTINCT  
    CLTCODE  
   FROM #RECPAY_TABLE  
   WHERE UPDFLAG = 'N'  
   DROP TABLE #RECPAY_TABLE_TMP  
   DROP TABLE #RECPAY_TABLE  
     
   RETURN  
  END  
  
 DECLARE  
  @@NEWVNO AS VARCHAR(12),  
  @@VDT AS VARCHAR(11),  
  @@LNOCUR AS CURSOR,  
  @@LNOVNO AS INT,  
  @@NOREC AS INT  
  
  
/* '--------------------------AUTO GENERATION OF VNO (FULL LOGIC)------------------------*/  
 DECLARE  
  @@MAXVNO AS VARCHAR(12),  
  @@VNO AS VARCHAR(12),  
  @@RCOUNT AS INT  
 SELECT TOP 1  
  @@VDT = CONVERT(VARCHAR(11), VDT, 109)  
 FROM  
  #RECPAY_TABLE  
  
 SELECT TOP 1  
  @@VNOMETHOD = VNOFLAG,  
  @@STD_DATE = CONVERT(VARCHAR(11), SDTCUR, 109),  
  @@LST_DATE = CONVERT(VARCHAR(11), LDTCUR, 109)  
 FROM  
  PARAMETER  
 WHERE  
  @@VDT BETWEEN SDTCUR AND LDTCUR  
  
   
 SELECT  
  @@NOREC = COUNT(DISTINCT SRNO)  
 FROM  
  #RECPAY_TABLE  
  
 IF @@VNOMETHOD = 0  
  BEGIN  
   SELECT  
    @@MAXVNO = CONVERT(VARCHAR(12), ISNULL(MAX(CONVERT(NUMERIC,LASTVNO)),0))  
   FROM  
    V2_LASTVNO WITH (TABLOCKX,HOLDLOCK)  
   WHERE  
    VTYP = @VTYP  
    AND BOOKTYPE = @BOOKTYPE  
    AND VDT BETWEEN @@STD_DATE AND @@LST_DATE + ' 23:59'  
   IF @@MAXVNO = '0'  
    BEGIN  
     SELECT @@MAXVNO = CONVERT(VARCHAR(12), CONVERT(NUMERIC, RIGHT(@@STD_DATE, 4) + '00000000') + @@NOREC)  
     SELECT @@VNO = RIGHT(@@STD_DATE, 4) + '00000001', @@RCOUNT = 0  
    END  
   ELSE  
    BEGIN  
     SELECT @@VNO = CONVERT(VARCHAR(12), CONVERT(NUMERIC, @@MAXVNO)+1), @@RCOUNT = 1  
     SELECT @@MAXVNO = CONVERT(VARCHAR(12), CONVERT(NUMERIC, @@MAXVNO)+@@NOREC)  
    END  
   IF @@RCOUNT = 1  
    BEGIN  
     UPDATE  
      V2_LASTVNO  
     SET  
      LASTVNO = @@MAXVNO  
     WHERE  
      VTYP = @VTYP  
      AND BOOKTYPE = @BOOKTYPE  
      AND VDT BETWEEN @@STD_DATE AND @@LST_DATE + ' 23:59'  
    END  
   ELSE  
    BEGIN  
     INSERT INTO  
      V2_LASTVNO  
      (VTYP, BOOKTYPE, VDT, LASTVNO)  
     VALUES  
      (@VTYP, @BOOKTYPE, @@STD_DATE, @@MAXVNO)  
    END  
  END  
 ELSE IF @@VNOMETHOD = 1  
  BEGIN  
   SELECT  
    @@MAXVNO = CONVERT(VARCHAR(12), ISNULL(MAX(CONVERT(NUMERIC,LASTVNO)),0))  
   FROM  
    V2_LASTVNO WITH (TABLOCKX,HOLDLOCK)  
   WHERE  
    VTYP = @VTYP  
    AND BOOKTYPE = @BOOKTYPE  
    AND VDT BETWEEN @@VDT AND @@VDT + ' 23:59'  
   IF @@MAXVNO = '0'  
    BEGIN  
     SELECT @@MAXVNO = RIGHT(@@VDT, 4) + RIGHT('0' + RTRIM(LTRIM(CONVERT(VARCHAR(2), MONTH(@@VDT)))), 2) + RIGHT('0' + LTRIM(RTRIM(CONVERT(VARCHAR(2), DAY(@@VDT)))), 2) + '0000'  
     SELECT @@MAXVNO = CONVERT(VARCHAR(12), CONVERT(NUMERIC, @@MAXVNO) + @@NOREC)  
     SELECT @@VNO = RIGHT(@@VDT, 4) + RIGHT('0' + RTRIM(LTRIM(CONVERT(VARCHAR(2), MONTH(@@VDT)))), 2) + RIGHT('0' + LTRIM(RTRIM(CONVERT(VARCHAR(2), DAY(@@VDT)))), 2) + '0001', @@RCOUNT = 0  
    END  
   ELSE  
    BEGIN  
     SELECT @@VNO = CONVERT(VARCHAR(12), CONVERT(NUMERIC, @@MAXVNO)+1), @@RCOUNT = 1  
     SELECT @@MAXVNO = CONVERT(VARCHAR(12), CONVERT(NUMERIC, @@MAXVNO)+@@NOREC)  
    END  
   IF @@RCOUNT = 1  
    BEGIN  
     UPDATE  
      V2_LASTVNO  
     SET  
      LASTVNO = @@MAXVNO  
     WHERE  
      VTYP = @VTYP  
      AND BOOKTYPE = @BOOKTYPE  
      AND VDT BETWEEN @@VDT AND @@VDT + ' 23:59'  
    END  
   ELSE  
    BEGIN  
     INSERT INTO  
      V2_LASTVNO  
      (VTYP, BOOKTYPE, VDT, LASTVNO)  
     VALUES  
      (@VTYP, @BOOKTYPE, @@VDT, @@MAXVNO)  
    END  
  END  
 ELSE IF @@VNOMETHOD = 2  
  BEGIN  
   SELECT  
    @@MAXVNO = CONVERT(VARCHAR(12), ISNULL(MAX(CONVERT(NUMERIC,LASTVNO)),0))  
   FROM  
    V2_LASTVNO WITH (TABLOCKX,HOLDLOCK)  
   WHERE  
    VTYP = @VTYP  
    AND BOOKTYPE = @BOOKTYPE  
    AND MONTH(VDT) = MONTH(@@VDT)  
    AND YEAR(VDT) = YEAR(@@VDT)  
   IF @@MAXVNO = '0'  
    BEGIN  
     SELECT @@MAXVNO = RIGHT(@@VDT, 4) + RIGHT('0' + RTRIM(LTRIM(CONVERT(VARCHAR(2), MONTH(@@VDT)))), 2) + '000000'  
     SELECT @@MAXVNO = CONVERT(VARCHAR(12), CONVERT(NUMERIC, @@MAXVNO) + @@NOREC)  
     SELECT @@VNO = RIGHT(@@VDT, 4) + RIGHT('0' + RTRIM(LTRIM(CONVERT(VARCHAR(2), MONTH(@@VDT)))), 2) + '000001', @@RCOUNT = 0  
    END  
   ELSE  
    BEGIN  
     SELECT @@VNO = CONVERT(VARCHAR(12), CONVERT(NUMERIC, @@MAXVNO)+1), @@RCOUNT = 1  
     SELECT @@MAXVNO = CONVERT(VARCHAR(12), CONVERT(NUMERIC, @@MAXVNO)+@@NOREC)  
    END  
   IF @@RCOUNT = 1  
    BEGIN  
     UPDATE  
      V2_LASTVNO  
     SET  
      LASTVNO = @@MAXVNO  
     WHERE  
      VTYP = @VTYP  
      AND BOOKTYPE = @BOOKTYPE  
      AND MONTH(VDT) = MONTH(@@VDT)  
      AND YEAR(VDT) = YEAR(@@VDT)  
    END  
   ELSE  
    BEGIN  
     INSERT INTO  
      V2_LASTVNO  
      (VTYP, BOOKTYPE, VDT, LASTVNO)  
     VALUES  
      (@VTYP, @BOOKTYPE, @@VDT, @@MAXVNO)  
    END  
  END  
  
 UPDATE  
  #RECPAY_TABLE  
 SET VNO = CONVERT(VARCHAR(12), CONVERT(NUMERIC,@@VNO) + SRNO - 1)  
  
  
/* '--------------------------AUTO GENERATION OF LNO ------------------------*/  
  
 SET @@LNOCUR = CURSOR FOR  
  SELECT DISTINCT SRNO FROM #RECPAY_TABLE  
 OPEN @@LNOCUR  
  FETCH NEXT FROM @@LNOCUR INTO @@LNOVNO  
 WHILE @@FETCH_STATUS = 0  
  BEGIN  
   INSERT INTO #RECPAY_TABLE_LNO  
    (SNO)  
   SELECT SNO FROM #RECPAY_TABLE WHERE SRNO = @@LNOVNO  
   UPDATE RP  
    SET LNO = RL.LNO  
   FROM #RECPAY_TABLE RP, #RECPAY_TABLE_LNO RL  
   WHERE RP.SNO = RL.SNO  
   TRUNCATE TABLE #RECPAY_TABLE_LNO  
   FETCH NEXT FROM @@LNOCUR INTO @@LNOVNO  
  END  
 CLOSE @@LNOCUR  
 DEALLOCATE @@LNOCUR  
 DROP TABLE #RECPAY_TABLE_LNO  
  
/* '--------------------------BEGIN POSTING TO TRANSACTION TABLES ------------------------*/  
/*==============================  
      LEDGER RECORD  
==============================*/  
 INSERT  
 INTO LEDGER  
 SELECT  
  VTYP = @VTYP,  
  VNO,  
  EDT,  
  LNO,  
  ACNAME,  
  DRCR,  
  VAMT = AMOUNT,  
  VDT,  
  VNO1 = VNO,  
  REFNO = 0,  
  BALAMT = AMOUNT,  
  NODAYS = 0,  
  CDT = GETDATE(),  
  CLTCODE,  
  BOOKTYPE = @BOOKTYPE,  
  ENTEREDBY = @UNAME,  
  PDT = GETDATE(),  
  CHECKEDBY = @UNAME,  
  ACTNODAYS = 0,  
  NARRATION  
 FROM  
  #RECPAY_TABLE  
  
/*==============================  
 LEDGER3 RECORD  
==============================*/  
 INSERT  
 INTO LEDGER3  
 SELECT  
  NARATNO = LNO,  
  NARRATION,  
  REFNO = 0,  
  VTYP = @VTYP,  
  VNO,  
  BOOKTYPE = @BOOKTYPE  
      FROM  
  #RECPAY_TABLE 
  
 DELETE FROM TEMPLEDGER2  
  WHERE SESSIONID = '9999999999'  
 INSERT INTO TEMPLEDGER2  
 SELECT  
  'BRANCH',  
  C.COSTNAME,  
  AMOUNT,  
  VTYP = @VTYP,  
  VNO,  
  LNO,  
  DRCR,  
  '0',  
  BOOKTYPE = @BOOKTYPE,  
  SESSIONID = '9999999999',  
  CLIENT_CODE = CLTCODE,  
  'A',  
  '0'  
 FROM  
  #RECPAY_TABLE RP,  
  COSTMAST C  
 WHERE  
  RP.COSTCODE = C.COSTCODE  
  
 DECLARE @@L2CUR AS CURSOR,  
  @@L2VNO AS VARCHAR(12)  
 SET @@L2CUR = CURSOR FOR  
  SELECT DISTINCT VNO FROM #RECPAY_TABLE ORDER BY VNO  
 OPEN @@L2CUR  
 FETCH NEXT FROM @@L2CUR INTO @@L2VNO  
 WHILE @@FETCH_STATUS = 0  
  BEGIN  
   EXEC INSERTTOLEDGER2 '9999999999', @@L2VNO, '1', '1', '1', 'BROKER', 'BROKER'  
   FETCH NEXT FROM @@L2CUR INTO @@L2VNO  
  END  
  DELETE FROM TEMPLEDGER2  
   WHERE SESSIONID = '9999999999'  
  CLOSE @@L2CUR  
  DEALLOCATE @@L2CUR  
  
 UPDATE MSAJAG.DBO.TBL_PREPAID_MAPPING
 SET AMT_POSTED=1 
 WHERE @TRADEDATE BETWEEN PP_FROM_DATE AND PP_TO_DATE  
 AND AMT_POSTED=0

 UPDATE MSAJAG.DBO.TBL_PREPAID_TRANS SET POSTFLAG = 1
 WHERE PP_TRANS_DATE LIKE @TRADEDATE + '%'
 AND POSTFLAG = 0

 SELECT RESULT = '0~<HR><B>.:: DATA POSTED SUCCESSFULLY ::.</B><HR>'   
 UNION ALL  
 SELECT RESULT = VNO + ', ' + DRCR + ', ' + CLTCODE + ', ' + CONVERT(VARCHAR, AMOUNT) FROM #RECPAY_TABLE ORDER BY 1  
 DROP TABLE #RECPAY_TABLE_TMP  
 DROP TABLE #RECPAY_TABLE

GO
