-- Object: PROCEDURE dbo.NEWASP_TRIALBALANCEPARTYTOTAL
-- Server: 10.253.33.91 | DB: ACCOUNTSLBS
--------------------------------------------------


CREATE  PROCEDURE  [dbo].[NEWASP_TRIALBALANCEPARTYTOTAL] 

/* REPORT : CONSOLIDATED TRIAL BALANCE        
FILE : TRIALBAL.ASP
DISPLAYS CONSOLIDATED TRIAL BALANCE */


@VDT VARCHAR(11),               /* AS ON DATE ENTERED BY USER */
@FLAG VARCHAR(15),              /* SORT ORDER FOR REPORT - CODEWISE OR NAMEWISE */
@VIEWOPTION VARCHAR(10),        /* OPTIONS FOR ACCOUNTS SELECTION - ALL, GL, PARTY */
@BALANCE VARCHAR(10),           /* NORMAL OR WITHOPBAL */
@STDATE VARCHAR(11),            /* START DATE ENTERED BY USER */
@CURRYRSTDATE VARCHAR(11),	/* START DATE OF FINANCIAL YEAR */
@OPENENTRYFLAG INT,
@OPENINGENTRYDATE VARCHAR(11),  /* O/P ENTRY DATE ( VTYP = 18 ) FROUND FROM LEDGER FOR VDT <= LAST DATE ENTERED BY USER */
@STATUSID VARCHAR(20),          /* AS BROKER/BRANCH/CLIENT ETC. */
@STATUSNAME VARCHAR(20),        /* IN CASE OF BRANCH LOGIN BRANCHCODE */
@SORTBYDATE VARCHAR(3),          /* WHETHER REPORT IS BASED ON VDT OR EDT */
@GRPCODE VARCHAR(20),
@SHAREDB VARCHAR(20),
@EXCHANGE VARCHAR(10),
@SEGMENT VARCHAR(9)
AS

DECLARE
@@SELECTQURY  AS VARCHAR(8000),
@@FROMTABLES  AS VARCHAR(2000),
@@WHEREPART   AS VARCHAR(1000),
@@SQL		  AS VARCHAR(1000),  
@@WHEREPART1  AS VARCHAR(500),
@@WHEREPART2  AS VARCHAR(500),
@@WHEREPART3  AS VARCHAR(500),
@@ADDWHERE    AS VARCHAR(200),
@@GROUPBY     AS VARCHAR(200),
@@SORTBY      AS VARCHAR(200),
@@COSTCODE    AS VARCHAR(3)

/*
SELECT @@GROUPBY = " GROUP BY L.DRCR "
SELECT @@SORTBY  = " ORDER BY  L.DRCR "
*/

SELECT @@GROUPBY = " "
SELECT @@SORTBY  = " "

SELECT @@ADDWHERE  = " AND A.ACCAT = 4 " 
CREATE TABLE #COSTMAST
(
	COSTCODE INT
)

IF @STATUSID = 'REGION'
BEGIN
	SET @@SQL = " INSERT INTO #COSTMAST "
	SET @@SQL = @@SQL + " SELECT COSTCODE FROM COSTMAST C, "+ @SHAREDB +".DBO.REGION R WHERE REGIONCODE = RTRIM('"+@STATUSNAME+"') AND COSTNAME = BRANCH_CODE "
END

IF @STATUSID = 'AREA'
BEGIN
	SET @@SQL = " INSERT INTO #COSTMAST "
	SET @@SQL = @@SQL + " SELECT COSTCODE FROM COSTMAST C, "+ @SHAREDB +".DBO.AREA A WHERE AREACODE = RTRIM('"+@STATUSNAME+"') AND COSTNAME = BRANCH_CODE "
END

IF @STATUSID = 'BRANCH'
BEGIN
	SET @@SQL = " INSERT INTO #COSTMAST "
	SET @@SQL = @@SQL + " SELECT COSTCODE FROM COSTMAST WHERE COSTNAME = RTRIM('"+@STATUSNAME+"') "
END
PRINT(@@SQL)  
EXEC(@@SQL) 

IF @STATUSID = 'BROKER'
BEGIN
   IF @SORTBYDATE = 'VDT'
   BEGIN
      SELECT @@WHEREPART1 = " WHERE VDT <= '" + @VDT + " 23:59:59' AND L.CLTCODE=  A.CLTCODE " 
      SELECT @@WHEREPART2 = " WHERE VDT >= '" + @CURRYRSTDATE + " 00:00:00' AND VDT <= '" + @VDT + " 23:59:59' AND L.CLTCODE=  A.CLTCODE" 
      SELECT @@WHEREPART3 = " WHERE VDT >= '" + @OPENINGENTRYDATE + " 00:00:00' AND VDT <= '" + @VDT + " 23:59:59' AND L.CLTCODE=  A.CLTCODE" 
   END
   ELSE
   BEGIN
      SELECT @@WHEREPART1 = " WHERE EDT <= '" + @VDT + " 23:59:59' AND L.CLTCODE=  A.CLTCODE" 
      SELECT @@WHEREPART2 = " WHERE EDT >= '" + @CURRYRSTDATE + " 00:00:00' AND EDT <= '" + @VDT + " 23:59:59' AND L.CLTCODE=  A.CLTCODE" 
      SELECT @@WHEREPART3 = " WHERE EDT >= '" + @OPENINGENTRYDATE + " 00:00:00' AND EDT <= '" + @VDT + " 23:59:59' AND L.CLTCODE=  A.CLTCODE" 
   END
END
ELSE --IF @STATUSID = 'BRANCH'
BEGIN
	--SELECT @@COSTCODE = (SELECT COSTCODE FROM COSTMAST C, CATEGORY C2 WHERE C2.CATEGORY = 'BRANCH' AND C.CATCODE = C2.CATCODE AND COSTNAME = @STATUSNAME )
   IF @SORTBYDATE = 'VDT'
   BEGIN
      SELECT @@WHEREPART1 = " WHERE L2.VTYPE = L.VTYP AND L2.BOOKTYPE = L.BOOKTYPE AND L2.VNO = L.VNO AND L2.LNO = L.LNO AND EXISTS(SELECT COSTCODE FROM #COSTMAST C WHERE L2.COSTCODE = C.COSTCODE) AND VDT <= '" + @VDT + " 23:59:59' AND L.CLTCODE=  A.CLTCODE"
      SELECT @@WHEREPART2 = " WHERE L2.VTYPE = L.VTYP AND L2.BOOKTYPE = L.BOOKTYPE AND L2.VNO = L.VNO AND L2.LNO = L.LNO AND EXISTS(SELECT COSTCODE FROM #COSTMAST C WHERE L2.COSTCODE = C.COSTCODE) AND VDT >= '" + @CURRYRSTDATE + " 00:00:00' AND VDT <= '" + @VDT + " 23:59:59' AND L.CLTCODE=  A.CLTCODE"
      SELECT @@WHEREPART3 = " WHERE L2.VTYPE = L.VTYP AND L2.BOOKTYPE = L.BOOKTYPE AND L2.VNO = L.VNO AND L2.LNO = L.LNO AND EXISTS(SELECT COSTCODE FROM #COSTMAST C WHERE L2.COSTCODE = C.COSTCODE) AND VDT >= '" + @OPENINGENTRYDATE + " 00:00:00' AND VDT <= '" + @VDT + " 23:59:59' AND L.CLTCODE=  A.CLTCODE"
   END
   ELSE
   BEGIN
      SELECT @@WHEREPART1 = " WHERE L2.VTYPE = L.VTYP AND L2.BOOKTYPE = L.BOOKTYPE AND L2.VNO = L.VNO AND L2.LNO = L.LNO AND EXISTS(SELECT COSTCODE FROM #COSTMAST C WHERE L2.COSTCODE = C.COSTCODE) AND EDT <= '" + @VDT + " 23:59:59' AND L.CLTCODE=  A.CLTCODE"
      SELECT @@WHEREPART2 = " WHERE L2.VTYPE = L.VTYP AND L2.BOOKTYPE = L.BOOKTYPE AND L2.VNO = L.VNO AND L2.LNO = L.LNO AND EXISTS(SELECT COSTCODE FROM #COSTMAST C WHERE L2.COSTCODE = C.COSTCODE) AND EDT >= '" + @CURRYRSTDATE + " 00:00:00' AND EDT <= '" + @VDT + " 23:59:59' AND L.CLTCODE=  A.CLTCODE"
    SELECT @@WHEREPART3 = " WHERE L2.VTYPE = L.VTYP AND L2.BOOKTYPE = L.BOOKTYPE AND L2.VNO = L.VNO AND L2.LNO = L.LNO AND EXISTS(SELECT COSTCODE FROM #COSTMAST C WHERE L2.COSTCODE = C.COSTCODE) AND EDT >= '" + @OPENINGENTRYDATE + " 00:00:00' AND EDT <= '" + @VDT + " 23:59:59' AND L.CLTCODE=  A.CLTCODE"
   END
END

/*  -- FOR BROKER --  */
/* ------------------ */

IF @STATUSID = 'BROKER'
BEGIN
/*---- IF USER WANTS TO SEE NORMAL TRIAL BALANCE ---*/
IF @BALANCE='NORMAL'
BEGIN
   IF @OPENENTRYFLAG = 0   /* OPENING ENTRY ( VTYP = 18 ) NOT FOUND IN LEDGER */
   BEGIN
      SELECT @@SELECTQURY = "SELECT AMOUNT = ISNULL(SUM(CASE WHEN UPPER(DRCR) = 'D' THEN -VAMT ELSE -VAMT END),0),'" + @EXCHANGE + "','" + @EXCHANGE + " - " + @SEGMENT +"' "
      SELECT @@FROMTABLES = " FROM LEDGER L , (SELECT CLTCODE, ACNAME = LONGNAME, ACCAT, BRANCHCODE FROM ACMAST WITH(NOLOCK) WHERE  GRPCODE LIKE '" + @GRPCODE + "' + '%') A  " 
      SELECT @@WHEREPART  = @@WHEREPART1 + @@ADDWHERE
   END
   ELSE IF @OPENENTRYFLAG = 1  /* OPENING ENTRY ( VTYP = 18 ) FOUND IN LEDGER FOR SELECTED YEAR */
   BEGIN
      IF @SORTBYDATE = 'VDT'
         BEGIN
            SELECT @@SELECTQURY = "SELECT AMOUNT = ISNULL(SUM(CASE WHEN UPPER(DRCR) = 'D' THEN -VAMT ELSE VAMT END),0),'" + @EXCHANGE + "','" + @EXCHANGE + " - " + @SEGMENT +"' "
            SELECT @@FROMTABLES = " FROM LEDGER L , (SELECT CLTCODE, ACNAME = LONGNAME, ACCAT, BRANCHCODE FROM ACMAST WITH(NOLOCK) WHERE  GRPCODE LIKE '" + @GRPCODE + "' + '%') A  " 
            SELECT @@WHEREPART  = @@WHEREPART2 + @@ADDWHERE
	 END
      ELSE
         BEGIN
            SELECT @@SELECTQURY = " SELECT AMOUNT=ISNULL(SUM(AMOUNT),0),'" + @EXCHANGE + "','" + @EXCHANGE + " - " + @SEGMENT +"'  FROM "
            SELECT @@SELECTQURY = @@SELECTQURY + " (SELECT AMOUNT = SUM(CASE WHEN UPPER(DRCR) = 'D' THEN -VAMT ELSE VAMT END) "            
            SELECT @@SELECTQURY = @@SELECTQURY + " FROM LEDGER L , (SELECT CLTCODE, ACNAME = LONGNAME, ACCAT, BRANCHCODE FROM ACMAST WITH(NOLOCK) WHERE  GRPCODE LIKE '" + @GRPCODE + "' + '%') A  " 
            SELECT @@SELECTQURY = @@SELECTQURY + @@WHEREPART2 + @@ADDWHERE + " AND L.VTYP <> 18 "
            SELECT @@SELECTQURY = @@SELECTQURY + " UNION ALL "
            SELECT @@SELECTQURY = @@SELECTQURY + "SELECT AMOUNT = SUM(BALAMT)"
            SELECT @@SELECTQURY = @@SELECTQURY + " FROM LEDGER L , (SELECT CLTCODE, ACNAME = LONGNAME, ACCAT, BRANCHCODE FROM ACMAST WITH(NOLOCK) WHERE  GRPCODE LIKE '" + @GRPCODE + "' + '%') A  " 
            SELECT @@SELECTQURY = @@SELECTQURY + @@WHEREPART2 + @@ADDWHERE + " AND L.VTYP = 18 ) T"
            SELECT @@FROMTABLES = " "
            SELECT @@WHEREPART  = " "
	 END
   END
   ELSE IF @OPENENTRYFLAG = 2  /* OPENING ENTRY ( VTYP = 18 ) FOUND IN LEDGER FOR EARLIER YEAR */
   BEGIN
      IF @SORTBYDATE = 'VDT'
         BEGIN
            SELECT @@SELECTQURY = "SELECT AMOUNT = ISNULL(SUM(CASE WHEN UPPER(DRCR) = 'D' THEN -VAMT ELSE VAMT END),0),'" + @EXCHANGE + "','" + @EXCHANGE + " - " + @SEGMENT +"' "
            SELECT @@FROMTABLES = " FROM LEDGER L , (SELECT CLTCODE, ACNAME = LONGNAME, ACCAT, BRANCHCODE FROM ACMAST WITH(NOLOCK) WHERE  GRPCODE LIKE '" + @GRPCODE + "' + '%') A  " 
            SELECT @@WHEREPART  = @@WHEREPART3 + @@ADDWHERE
	 END
      ELSE
         BEGIN
            SELECT @@SELECTQURY = " SELECT AMOUNT=ISNULL(SUM(AMOUNT),0),'" + @EXCHANGE + "','" + @EXCHANGE + " - " + @SEGMENT +"'  FROM "
            SELECT @@SELECTQURY = @@SELECTQURY + " (SELECT AMOUNT = SUM(CASE WHEN UPPER(DRCR) = 'D' THEN -VAMT ELSE VAMT END)"            
            SELECT @@SELECTQURY = @@SELECTQURY + " FROM LEDGER L , (SELECT CLTCODE, ACNAME = LONGNAME, ACCAT, BRANCHCODE FROM ACMAST WITH(NOLOCK) WHERE  GRPCODE LIKE '" + @GRPCODE + "' + '%') A  " 
            SELECT @@SELECTQURY = @@SELECTQURY + @@WHEREPART3 + @@ADDWHERE + " AND L.VTYP <> 18 "
            SELECT @@SELECTQURY = @@SELECTQURY + " UNION ALL "
            SELECT @@SELECTQURY = @@SELECTQURY + "SELECT AMOUNT = SUM(BALAMT)"
            SELECT @@SELECTQURY = @@SELECTQURY + " FROM LEDGER L , (SELECT CLTCODE, ACNAME = LONGNAME, ACCAT, BRANCHCODE FROM ACMAST WITH(NOLOCK) WHERE  GRPCODE LIKE '" + @GRPCODE + "' + '%') A  " 
            SELECT @@SELECTQURY = @@SELECTQURY + @@WHEREPART2 + @@ADDWHERE + ") T"
            SELECT @@FROMTABLES = " "
            SELECT @@WHEREPART  = " "
	 END
   END
END
/*--- IF USER WANTS TO SEE TRIAL BALANCE WITH OPENING BALANCES ---*/
ELSE IF @BALANCE='WITHOPBAL'
BEGIN
   IF @OPENENTRYFLAG = 0   /* OPENING ENTRY ( VTYP = 18 ) NOT FOUND IN LEDGER */
   BEGIN
      IF @CURRYRSTDATE = @STDATE 
         BEGIN
            SELECT @@SELECTQURY = "SELECT DRTOT = ISNULL(SUM(CASE WHEN UPPER(DRCR) = 'D' THEN -VAMT ELSE 0 END),0), CRTOT = ISNULL(SUM(CASE WHEN UPPER(DRCR) = 'C' THEN VAMT ELSE 0 END),0),OPBAL = 0 "
            SELECT @@FROMTABLES = " FROM LEDGER L , (SELECT CLTCODE, ACNAME = LONGNAME, ACCAT, BRANCHCODE FROM ACMAST WITH(NOLOCK) WHERE  GRPCODE LIKE '" + @GRPCODE + "' + '%') A  " 
            SELECT @@WHEREPART  = @@WHEREPART1 + @@ADDWHERE
         END
      ELSE
         BEGIN
           SELECT @@SELECTQURY = "SELECT DRTOT = ISNULL(SUM(CASE WHEN VTYP <> 18 AND VDT >= '" + @STDATE + "' THEN ( CASE WHEN UPPER(DRCR) = 'D' THEN -VAMT ELSE 0 END) ELSE 0 END),0), CRTOT = ISNULL(SUM(CASE WHEN VTYP <> 18 AND  VDT >= '" + @STDATE + "' THEN ( CASE WHEN UPPER(DRCR) = 'C' THEN VAMT ELSE 0 END) ELSE 0 END),0), OPBAL = ISNULL(SUM(CASE WHEN VDT < '" + @STDATE + "' THEN ( CASE WHEN UPPER(DRCR) = 'D' THEN -VAMT ELSE VAMT END) ELSE 0 END),0) "
           SELECT @@FROMTABLES = " FROM LEDGER L , (SELECT CLTCODE, ACNAME = LONGNAME, ACCAT, BRANCHCODE FROM ACMAST WITH(NOLOCK) WHERE  GRPCODE LIKE '" + @GRPCODE + "' + '%') A  " 
           SELECT @@WHEREPART  = @@WHEREPART1 + @@ADDWHERE
         END
   END
   ELSE IF @OPENENTRYFLAG = 1  /* OPENING ENTRY ( VTYP = 18 ) FOUND IN LEDGER FOR SELECTED YEAR */
   BEGIN
      IF @CURRYRSTDATE = @STDATE 
         BEGIN
            IF @SORTBYDATE = 'VDT'
               BEGIN
                  SELECT @@SELECTQURY = "SELECT DRTOT = ISNULL(SUM(CASE WHEN VTYP <> 18 AND VDT >= '" + @STDATE + "' THEN ( CASE WHEN UPPER(DRCR) = 'D' THEN -VAMT ELSE 0 END) ELSE 0 END),0), CRTOT = ISNULL(SUM(CASE WHEN VTYP <> 18 AND VDT >= '" + @STDATE + "' THEN ( CASE WHEN UPPER(DRCR) = 'C' THEN VAMT ELSE 0 END) ELSE 0 END),0), OPBAL = ISNULL(SUM(CASE WHEN VTYP = 18 THEN ( CASE WHEN UPPER(DRCR) = 'D' THEN -VAMT ELSE VAMT END) ELSE 0 END),0)"
                  SELECT @@FROMTABLES = " FROM LEDGER L , (SELECT CLTCODE, ACNAME = LONGNAME, ACCAT, BRANCHCODE FROM ACMAST WITH(NOLOCK) WHERE  GRPCODE LIKE '" + @GRPCODE + "' + '%') A  " 
                  SELECT @@WHEREPART  = @@WHEREPART2 + @@ADDWHERE
               END
	    ELSE
	       BEGIN
                  SELECT @@SELECTQURY = "SELECT DRTOT = ISNULL(SUM(CASE WHEN VTYP <> 18 AND VDT >= '" + @STDATE + "' THEN ( CASE WHEN UPPER(DRCR) = 'D' THEN -VAMT ELSE 0 END) ELSE 0 END),0), CRTOT = ISNULL(SUM(CASE WHEN VTYP <> 18 AND VDT >= '" + @STDATE + "' THEN ( CASE WHEN UPPER(DRCR) = 'C' THEN VAMT ELSE 0 END) ELSE 0 END),0), OPBAL = ISNULL(SUM(CASE WHEN VTYP = 18 THEN BALAMT ELSE 0 END),0)"
                  SELECT @@FROMTABLES = " FROM LEDGER L , (SELECT CLTCODE, ACNAME = LONGNAME, ACCAT, BRANCHCODE FROM ACMAST WITH(NOLOCK) WHERE  GRPCODE LIKE '" + @GRPCODE + "' + '%') A  " 
                  SELECT @@WHEREPART  = @@WHEREPART2 + @@ADDWHERE
	       END
         END
      ELSE
         BEGIN
           SELECT @@SELECTQURY = "SELECT DRTOT = ISNULL(SUM(CASE WHEN VTYP <> 18 AND VDT >= '" + @STDATE + "' THEN ( CASE WHEN UPPER(DRCR) = 'D' THEN -VAMT ELSE 0 END) ELSE 0 END),0), CRTOT = ISNULL(SUM(CASE WHEN VTYP <> 18 AND VDT >= '" + @STDATE + "' THEN ( CASE WHEN UPPER(DRCR) = 'C' THEN VAMT ELSE 0 END) ELSE 0 END),0), OPBAL = ISNULL(SUM(CASE WHEN VDT < '" + @STDATE + "' THEN ( CASE WHEN UPPER(DRCR) = 'D' THEN -VAMT ELSE VAMT END) ELSE 0 END),0) "
           SELECT @@FROMTABLES = " FROM LEDGER L , (SELECT CLTCODE, ACNAME = LONGNAME, ACCAT, BRANCHCODE FROM ACMAST WITH(NOLOCK) WHERE  GRPCODE LIKE '" + @GRPCODE + "' + '%') A  " 
           SELECT @@WHEREPART  = @@WHEREPART2 + @@ADDWHERE
         END
   END
   ELSE IF @OPENENTRYFLAG = 2  /* OPENING ENTRY ( VTYP = 18 ) FOUND IN LEDGER FOR EARLIER YEAR */
   BEGIN
      IF @SORTBYDATE = 'VDT'
         BEGIN
            SELECT @@SELECTQURY = "SELECT DRTOT = ISNULL(SUM(CASE WHEN VTYP <> 18 AND VDT >= '" + @STDATE + "' THEN ( CASE WHEN UPPER(DRCR) = 'D' THEN -VAMT ELSE 0 END) ELSE 0 END),0), CRTOT = ISNULL(SUM(CASE WHEN VTYP <> 18 AND VDT >= '" + @STDATE + "' THEN ( CASE WHEN UPPER(DRCR) = 'C' THEN VAMT ELSE 0 END) ELSE 0 END),0), OPBAL = ISNULL(SUM(CASE WHEN VDT < '" + @STDATE + "' THEN ( CASE WHEN UPPER(DRCR) = 'D' THEN -VAMT ELSE VAMT END) ELSE 0 END),0) "
            SELECT @@FROMTABLES = " FROM LEDGER L , (SELECT CLTCODE, ACNAME = LONGNAME, ACCAT, BRANCHCODE FROM ACMAST WITH(NOLOCK) WHERE  GRPCODE LIKE '" + @GRPCODE + "' + '%') A  " 
            SELECT @@WHEREPART  = @@WHEREPART3 + @@ADDWHERE
	 END
      ELSE
	 BEGIN
            SELECT @@SELECTQURY = " SELECT AMOUNT=ISNULL(SUM(AMOUNT),0) FROM "
            SELECT @@SELECTQURY = @@SELECTQURY + " (SELECT AMOUNT = SUM(CASE WHEN UPPER(DRCR) = 'D' THEN -VAMT ELSE VAMT END)"            
            SELECT @@SELECTQURY = @@SELECTQURY + " FROM LEDGER L , (SELECT CLTCODE, ACNAME = LONGNAME, ACCAT, BRANCHCODE FROM ACMAST WITH(NOLOCK) WHERE  GRPCODE LIKE '" + @GRPCODE + "' + '%') A  " 
            SELECT @@SELECTQURY = @@SELECTQURY + @@WHEREPART3 + @@ADDWHERE + " AND L.VTYP <> 18 "
            SELECT @@SELECTQURY = @@SELECTQURY + " UNION ALL "
            SELECT @@SELECTQURY = @@SELECTQURY + "SELECT AMOUNT = SUM(BALAMT)"
            SELECT @@SELECTQURY = @@SELECTQURY + " FROM LEDGER L , (SELECT CLTCODE, ACNAME = LONGNAME, ACCAT, BRANCHCODE FROM ACMAST WITH(NOLOCK) WHERE  GRPCODE LIKE '" + @GRPCODE + "' + '%') A  " 
            SELECT @@SELECTQURY = @@SELECTQURY + @@WHEREPART2 + @@ADDWHERE + ") T"
            SELECT @@FROMTABLES = " "
    SELECT @@WHEREPART  = " "
	 END
   END
END
END    /* END OG STATUSID = 'BROKER'  */


/*  -- FOR BRANCH SELECTION --  */
/* ---------------------------- */

IF @STATUSID = 'BRANCH'
BEGIN
/*---- IF USER WANTS TO SEE NORMAL TRIAL BALANCE ---*/
IF @BALANCE='NORMAL'
BEGIN
   IF @OPENENTRYFLAG = 0   /* OPENING ENTRY ( VTYP = 18 ) NOT FOUND IN LEDGER */
   BEGIN
      SELECT @@SELECTQURY = " SELECT AMOUNT = ISNULL(SUM(CASE WHEN UPPER(L2.DRCR) = 'D' THEN -CAMT ELSE CAMT END),0),'" + @EXCHANGE + "','" + @EXCHANGE + " - " + @SEGMENT +"' "
      SELECT @@FROMTABLES = " FROM LEDGER L, LEDGER2 L2 LEFT OUTER JOIN ACMAST A ON L2.CLTCODE=  A.CLTCODE  " 
      SELECT @@WHEREPART  = @@WHEREPART1 + @@ADDWHERE
   END
   ELSE IF @OPENENTRYFLAG = 1  /* OPENING ENTRY ( VTYP = 18 ) FOUND IN LEDGER FOR SELECTED YEAR */
   BEGIN
      SELECT @@SELECTQURY = " SELECT AMOUNT = ISNULL(SUM(CASE WHEN UPPER(L2.DRCR) = 'D' THEN -CAMT ELSE CAMT END),0),'" + @EXCHANGE + "','" + @EXCHANGE + " - " + @SEGMENT +"' "
      SELECT @@FROMTABLES = " FROM LEDGER L, LEDGER2 L2 LEFT OUTER JOIN ACMAST A ON L2.CLTCODE=  A.CLTCODE  " 
      SELECT @@WHEREPART  = @@WHEREPART2 + @@ADDWHERE
   END
   ELSE IF @OPENENTRYFLAG = 2  /* OPENING ENTRY ( VTYP = 18 ) FOUND IN LEDGER FOR EARLIER YEAR */
   BEGIN
      SELECT @@SELECTQURY = " SELECT AMOUNT = ISNULL(SUM(CASE WHEN UPPER(L2.DRCR) = 'D' THEN -CAMT ELSE CAMT END),0),'" + @EXCHANGE + "','" + @EXCHANGE + " - " + @SEGMENT +"' "
      SELECT @@FROMTABLES = " FROM LEDGER L, LEDGER2 L2 LEFT OUTER JOIN ACMAST A ON L2.CLTCODE=  A.CLTCODE  " 
      SELECT @@WHEREPART  = @@WHEREPART3 + @@ADDWHERE
   END
END
ELSE IF @BALANCE='WITHOPBAL'
BEGIN
   IF @OPENENTRYFLAG = 0   /* OPENING ENTRY ( VTYP = 18 ) NOT FOUND IN LEDGER */
   BEGIN
      IF @CURRYRSTDATE = @STDATE 
         BEGIN
            SELECT @@SELECTQURY = "SELECT DRTOT = ISNULL(SUM(CASE WHEN UPPER(L2.DRCR) = 'D' THEN -CAMT ELSE 0 END),0), CRTOT = ISNULL(SUM(CASE WHEN UPPER(L2.DRCR) = 'C' THEN CAMT ELSE 0 END),0),OPBAL = 0 "
            SELECT @@FROMTABLES = " FROM LEDGER L, LEDGER2 L2 LEFT OUTER JOIN ACMAST A ON L2.CLTCODE=  A.CLTCODE  " 
            SELECT @@WHEREPART  = @@WHEREPART1 + @@ADDWHERE
         END
      ELSE
         BEGIN
           SELECT @@SELECTQURY = "SELECT DRTOT = ISUNLL(SUM(CASE WHEN L.VTYP <> 18 AND L.VDT >= '" + @STDATE + "' THEN ( CASE WHEN UPPER(L2.DRCR) = 'D' THEN -CAMT ELSE 0 END) ELSE 0 END),0), CRTOT = ISNULL(SUM(CASE WHEN L.VTYP <> 18 AND L.VDT >= '" + @STDATE + "' THEN ( CASE WHEN UPPER(L2.DRCR) = 'C' THEN CAMT ELSE 0 END) ELSE 0 END),0), OPBAL = ISNULL(SUM(CASE WHEN L.VDT < '" + @STDATE + "' THEN ( CASE WHEN UPPER(L2.DRCR) = 'D' THEN -CAMT ELSE CAMT END) ELSE 0 END),0) "
           SELECT @@FROMTABLES = " FROM LEDGER L, LEDGER2 L2 LEFT OUTER JOIN ACMAST A ON L2.CLTCODE=  A.CLTCODE  " 
           SELECT @@WHEREPART  = @@WHEREPART1 + @@ADDWHERE
         END
   END
   ELSE IF @OPENENTRYFLAG = 1  /* OPENING ENTRY ( VTYP = 18 ) FOUND IN LEDGER FOR SELECTED YEAR */
   BEGIN
      IF @CURRYRSTDATE = @STDATE 
         BEGIN
            SELECT @@SELECTQURY = "SELECT DRTOT = ISNULL(SUM(CASE WHEN L.VTYP <> 18 AND L.VDT >= '" + @STDATE + "' THEN ( CASE WHEN UPPER(L2.DRCR) = 'D' THEN -CAMT ELSE 0 END) ELSE 0 END),0), CRTOT = ISNULL(SUM(CASE WHEN L.VTYP <> 18 AND L.VDT >= '" + @STDATE + "' THEN ( CASE WHEN UPPER(L2.DRCR) = 'C' THEN CAMT ELSE 0 END) ELSE 0 END),0), OPBAL = ISNULL(SUM(CASE WHEN L.VTYP = 18 THEN ( CASE WHEN UPPER(L2.DRCR) = 'D' THEN -CAMT ELSE CAMT END) ELSE 0 END),0)"
            SELECT @@FROMTABLES = " FROM LEDGER L, LEDGER2 L2 LEFT OUTER JOIN ACMAST A ON L2.CLTCODE=  A.CLTCODE  " 
            SELECT @@WHEREPART  = @@WHEREPART2 + @@ADDWHERE
         END
      ELSE
         BEGIN
           SELECT @@SELECTQURY = "SELECT DRTOT = ISNULL(SUM(CASE WHEN L.VTYP <> 18 AND L.VDT >= '" + @STDATE + "' THEN ( CASE WHEN UPPER(L2.DRCR) = 'D' THEN -CAMT ELSE 0 END) ELSE 0 END),0), CRTOT = ISNULL(SUM(CASE WHEN L.VTYP <> 18 AND L.VDT >= '" + @STDATE + "' THEN ( CASE WHEN UPPER(L2.DRCR) = 'C' THEN CAMT ELSE 0 END) ELSE 0 END),0), OPBAL = ISNULL(SUM(CASE WHEN L.VDT < '" + @STDATE + "' THEN ( CASE WHEN UPPER(L2.DRCR) = 'D' THEN -CAMT ELSE CAMT END) ELSE 0 END),0) "
           SELECT @@FROMTABLES = " FROM LEDGER L, LEDGER2 L2 LEFT OUTER JOIN ACMAST A ON L2.CLTCODE=  A.CLTCODE  " 
           SELECT @@WHEREPART  = @@WHEREPART2 + @@ADDWHERE
         END
   END
   ELSE IF @OPENENTRYFLAG = 2  /* OPENING ENTRY ( VTYP = 18 ) FOUND IN LEDGER FOR EARLIER YEAR */
   BEGIN
      SELECT @@SELECTQURY = "SELECT DRTOT = ISNULL(SUM(CASE WHEN L.VTYP <> 18 AND L.VDT >= '" + @STDATE + "' THEN ( CASE WHEN UPPER(L2.DRCR) = 'D' THEN -CAMT ELSE 0 END) ELSE 0 END),0), CRTOT = ISNULL(SUM(CASE WHEN L.VTYP <> 18 AND L.VDT >= '" + @STDATE + "' THEN ( CASE WHEN UPPER(L2.DRCR) = 'C' THEN CAMT ELSE 0 END) ELSE 0 END),0), OPBAL = ISNULL(SUM(CASE WHEN L.VDT < '" + @STDATE + "' THEN ( CASE WHEN UPPER(L2.DRCR) = 'D' THEN -CAMT ELSE CAMT END) ELSE 0 END),0) "
      SELECT @@FROMTABLES = " FROM LEDGER L, LEDGER2 L2 LEFT OUTER JOIN ACMAST A ON L2.CLTCODE=  A.CLTCODE  " 
      SELECT @@WHEREPART  = @@WHEREPART3 + @@ADDWHERE
   END
END
END /* END OF BRANCH LOGIN OR BRANCH SELECTION FROM BROKER LOGIN */

PRINT @@SELECTQURY + @@FROMTABLES + @@WHEREPART + @@GROUPBY + @@SORTBY  

EXEC (@@SELECTQURY + @@FROMTABLES + @@WHEREPART + @@GROUPBY + @@SORTBY )

GO
