-- Object: PROCEDURE dbo.CLS_INSERT_FILEDATA
-- Server: 10.253.33.91 | DB: MSAJAG
--------------------------------------------------



CREATE PROCEDURE [dbo].[CLS_INSERT_FILEDATA] (
	@SESSIONID VARCHAR(200),
	@TEXTLINE VARCHAR(MAX), --LINE BY LINE IN NORMAL AND FILE PATH IN BULK
	@UNAME VARCHAR(50),
	@METHOD VARCHAR(10)
	)
AS
DECLARE @SEP VARCHAR(1),
	@LOOPID INT,
	@DATA VARCHAR(MAX),
	@DATE DATETIME

SET @LOOPID = 1
SET @DATE = GETDATE()
SET @SEP = '§'

IF (@UNAME='' OR @UNAME IS NULL)
SET @UNAME=HOST_NAME ()
 
BEGIN TRANSACTION
IF RTRIM(LTRIM(UPPER(@METHOD))) = UPPER('NORMAL')
BEGIN
	--WHILE 1 = 1
	--BEGIN
	--	SET @DATA =.dbo.CLS_Piece(LTRIM(RTRIM(@TEXTLINE)), @SEP, @LOOPID)

	--	IF @DATA IS NULL
	--		OR @DATA = ''
	--	BEGIN
	--		BREAK
	--	END

	--	INSERT INTO MSAJAG..FILEDATA
	--	VALUES (
	--		@SESSIONID,
	--		@DATA,
	--		@DATE,
	--		@UNAME
	--		)
	--	SET @LOOPID = @LOOPID + 1
	-- END
		INSERT INTO MSAJAG..FILEDATA
		SELECT @SESSIONID, ITEMS, @DATE, @UNAME FROM DBO.CLS_SPLIT(@TEXTLINE,@SEP)
		
	
END
ELSE IF RTRIM(LTRIM(UPPER(@METHOD))) = UPPER('BULK')
BEGIN
	--XP_CMDSHELL 'TYPE D:\BACKOFFICE\JV_SAMPLE.CSV' 
	SET @DATA = " SELECT FILE_DATA INTO #FILE FROM FILEDATA WHERE 1 = 2  "
	SET @DATA = @DATA + "BULK INSERT #FILE FROM '" + @TEXTLINE + "' WITH  (ROWTERMINATOR = '\N', FIRSTROW = 2, KEEPNULLS) "
	SET @DATA = @DATA + "INSERT INTO FILEDATA SELECT '" + @SESSIONID + "', FILE_DATA, '" + CONVERT(VARCHAR,@DATE,109) + "', '" + @UNAME + "' "
	SET @DATA = @DATA + "FROM #FILE "
	SET @DATA = @DATA + "DROP TABLE #FILE "
	
	EXEC (@DATA)
END

IF @@ERROR = 0
	COMMIT
ELSE
	ROLLBACK

SELECT @SESSIONID

GO
