-- Object: PROCEDURE dbo.usp_rdb_bse_mastar_sync
-- Server: 10.253.33.91 | DB: MSAJAG
--------------------------------------------------

CREATE proc [dbo].[usp_rdb_bse_mastar_sync]  
(@date as varchar(25))  
as begin 

delete from AngelBSECM.BSEDB_AB.DBO.SETTLEMENT where cast (Sauda_date as date)=@date  
  
print ('additional 1')  
Insert into  AngelBSECM.BSEDB_AB.DBO.SETTLEMENT ([ContractNo] ,[BillNo] ,[Trade_no] ,[Party_Code] ,[Scrip_Cd] ,[User_id] ,[Tradeqty] ,[AuctionPart] ,[MarketType] ,[Series] ,[Order_no] ,[MarketRate] ,[Sauda_date] ,[Table_No] ,[Line_No] ,[Val_perc] ,[Normal] ,[Day_puc] ,[day_sales] ,[Sett_purch] ,[Sett_sales] ,[Sell_buy] ,[Settflag] ,[Brokapplied] ,[NetRate] ,[Amount] ,[Ins_chrg] ,[turn_tax] ,[other_chrg] ,[sebi_tax] ,[Broker_chrg] ,[Service_tax] ,[Trade_amount] ,[Billflag] ,[sett_no] ,[NBrokApp] ,[NSerTax] ,[N_NetRate] ,[sett_type] ,[participantcode] ,[Status] ,[Pro_Cli] ,[CpId] ,[Instrument] ,[BookType] ,[Branch_Id] ,[TMark] ,[Scheme] ,[Dummy1] ,[Dummy2]) 
SELECT ContractNo=ContractNo_seg,BillNo=DENSE_RANK()over(order by sett_no,sett_desc,party_code),Trade_no,Party_Code,Scrip_Cd,User_id=UserID,Tradeqty=qty,AuctionPart='N',MarketType='0',Series,Order_no,  
MarketRate=market_rate, Sauda_date=CONVERT(DATETIME,TRADE_TIME),   
Table_No=0,Line_No=0,Val_perc=0,Normal=0,Day_puc=0,day_sales=0, Sett_purch=0, Sett_sales=0,Sell_buy=buysell,  
Settflag=(CASE WHEN TRADE_TYPE = 'T' THEN buysell+1 ELSE buysell+3 END),Brokapplied=net_rate_per_unit,  
NetRate=(CASE WHEN buysell = 1 THEN market_rate+net_rate_per_unit  
ELSE market_rate-net_rate_per_unit END),  
Amount=QTY*market_rate,Ins_chrg=stt,turn_tax,other_chrg=0,sebi_tax=sebifee,Broker_chrg=Stampduty,Service_tax,Trade_amount=QTY*market_rate,  
Billflag=(CASE WHEN TRADE_TYPE = 'T' THEN buysell+1 ELSE buysell+3 END),sett_no,NBrokApp=net_rate_per_unit,  
NSerTax=service_tax,N_NetRate=(CASE WHEN buysell = 1 THEN market_rate+net_rate_per_unit ELSE market_rate-net_rate_per_unit END),  
sett_type=sett_desc,Partipantcode=memID,Status='11',Pro_Cli='1',CpId='',Instrument=1,BookType=1,Branch_Id=party_code,TMark=Trade_type,  
Scheme=0,Dummy1=0,  
Dummy2=0  
from pcnorderDetails_rtb(Nolock) where trade_Date=@date  And  segment ='BSE CM'  



delete from AngelBSECM.BSEDB_AB.dbo.Charges_Detail where cast( CD_Sauda_Date as date)=@date  
print ('additional 2')  
insert into AngelBSECM.BSEDB_AB.dbo.Charges_Detail  ([CD_PARTY_CODE] ,[CD_SETT_NO] ,[CD_SETT_TYPE] ,[CD_SAUDA_DATE] ,[CD_CONTRACTNO] ,[CD_TRADE_NO] ,[CD_ORDER_NO] ,[CD_SCRIP_CD] ,[CD_SERIES] ,[CD_BUYRATE] ,[CD_SELLRATE] ,[CD_TRDBUY_QTY] ,[CD_TRDSELL_QTY] ,[CD_DELBUY_QTY] ,[CD_DELSELL_QTY] ,[CD_TRDBUYBROKERAGE] ,[CD_TRDSELLBROKERAGE] ,[CD_DELBUYBROKERAGE] ,[CD_DELSELLBROKERAGE] ,[CD_TOTALBROKERAGE] ,[CD_TRDBUYSERTAX] ,[CD_TRDSELLSERTAX] ,[CD_DELBUYSERTAX] ,[CD_DELSELLSERTAX] ,[CD_TOTALSERTAX] ,[CD_TRDBUY_TURNOVER] ,[CD_TRDSELL_TURNOVER] ,[CD_DELBUY_TURNOVER] ,[CD_DELSELL_TURNOVER] ,[CD_COMPUTATION_LEVEL] ,[CD_MIN_BROKAMT] ,[CD_MAX_BROKAMT] ,[CD_MIN_SCRIPAMT] ,[CD_MAX_SCRIPAMT] ,[CD_TIMESTAMP])
SELECT CD_PARTY_CODE =PARTY_CODE,CD_SETT_NO=SETT_NO,CD_SETT_TYPE=SETT_TYPE ,CD_SAUDA_DATE=TRADE_DATE,CD_CONTRACTNO=CONTRACTNO,CD_TRADE_NO='',  
CD_ORDER_NO =P.ORDER_NO,  
CD_SCRIP_CD =SCRIP_CD,CD_SERIES=SERIES,  
CD_BUYRATE=(CASE WHEN BUY_SELL_FLAG ='1' THEN CAST(TRADE_PRICE AS MONEY) ELSE  0 END ),  
CD_SELLRATE=(CASE WHEN BUY_SELL_FLAG ='2' THEN CAST(TRADE_PRICE AS MONEY) ELSE 0 END ) ,  
CD_TRDBUY_QTY= (CASE WHEN INTRA_DELFLAG ='T' THEN (CASE WHEN BUY_SELL_FLAG ='1' THEN CAST(QTY AS FLOAT) ELSE 0 END ) ELSE 0 END),  
CD_TRDSELL_QTY=(CASE WHEN INTRA_DELFLAG ='T' THEN (CASE WHEN BUY_SELL_FLAG ='2' THEN CAST(QTY AS FLOAT) ELSE 0 END ) ELSE 0 END),  
CD_DELBUY_QTY =(CASE WHEN INTRA_DELFLAG ='D' THEN (CASE WHEN BUY_SELL_FLAG ='1' THEN CAST(QTY AS FLOAT) ELSE 0 END ) ELSE 0 END),  
CD_DELSELL_QTY=(CASE WHEN INTRA_DELFLAG ='D' THEN (CASE WHEN BUY_SELL_FLAG ='2' THEN CAST(QTY AS FLOAT) ELSE 0 END ) ELSE 0 END),  
CD_TRDBUYBROKERAGE=(CASE WHEN INTRA_DELFLAG ='T' THEN (CASE WHEN BUY_SELL_FLAG ='1' THEN CAST(BROKERAGE AS MONEY)  ELSE 0 END )ELSE 0 END),  
CD_TRDSELLBROKERAGE=(CASE WHEN INTRA_DELFLAG ='T' THEN (CASE WHEN BUY_SELL_FLAG ='2' THEN CAST(BROKERAGE AS MONEY) ELSE 0 END )ELSE 0 END),  
CD_DELBUYBROKERAGE =(CASE WHEN INTRA_DELFLAG ='D' THEN (CASE WHEN BUY_SELL_FLAG ='1' THEN CAST(BROKERAGE AS MONEY)  ELSE 0 END )ELSE 0 END),  
CD_DELSELLBROKERAGE=(CASE WHEN INTRA_DELFLAG ='D' THEN (CASE WHEN BUY_SELL_FLAG ='2' THEN CAST(BROKERAGE AS MONEY)  ELSE 0 END )ELSE 0 END),  
CD_TOTALBROKERAGE=BROKERAGE,CD_TRDBUYSERTAX=(CASE WHEN BUY_SELL_FLAG ='1' THEN CAST(BROKERAGE AS MONEY)*18/100 ELSE 0 END ),  
CD_TRDSELLSERTAX=(CASE WHEN BUY_SELL_FLAG ='2' THEN CAST(BROKERAGE AS MONEY)*18/100 ELSE 0 END ),CD_DELBUYSERTAX=0,CD_DELSELLSERTAX=0,  
CD_TOTALSERTAX=CAST(BROKERAGE AS MONEY)*18/100,  
CD_TRDBUY_TURNOVER= (CASE WHEN INTRA_DELFLAG ='T' THEN (CASE WHEN BUY_SELL_FLAG ='1' THEN CAST(QTY AS FLOAT)*CAST(TRADE_PRICE AS MONEY)  ELSE 0 END ) ELSE 0 END),  
CD_TRDSELL_TURNOVER= (CASE WHEN INTRA_DELFLAG ='T' THEN (CASE WHEN BUY_SELL_FLAG ='2' THEN CAST(QTY AS FLOAT)*CAST(TRADE_PRICE AS MONEY)  ELSE 0 END ) ELSE 0 END),  
CD_DELBUY_TURNOVER=(CASE WHEN INTRA_DELFLAG ='D' THEN (CASE WHEN BUY_SELL_FLAG ='1' THEN CAST(QTY AS FLOAT)*CAST(TRADE_PRICE AS MONEY)  ELSE 0 END ) ELSE 0 END),  
CD_DELSELL_TURNOVER=(CASE WHEN INTRA_DELFLAG ='D' THEN (CASE WHEN BUY_SELL_FLAG ='2' THEN CAST(QTY AS FLOAT)*CAST(TRADE_PRICE AS MONEY)  ELSE 0 END ) ELSE 0 END),  
CD_COMPUTATION_LEVEL=(CASE WHEN ORDER_NO <>'' THEN 'O'ELSE '' END),  
CD_MIN_BROKAMT='0',CD_MAX_BROKAMT='0',CD_MIN_SCRIPAMT='0',CD_MAX_SCRIPAMT='0',CD_TIMESTAMP=GETDATE()  
 FROM PRORDERWISEDETAILS_rtb P where trade_date =@date   
and  segment ='BSE CM'



print ('additional 3')  
INSERT INTO AngelBSECM.BSEDB_AB.dbo.charges_detail  ([CD_PARTY_CODE] ,[CD_SETT_NO] ,[CD_SETT_TYPE] ,[CD_SAUDA_DATE] ,[CD_CONTRACTNO] ,[CD_TRADE_NO] ,[CD_ORDER_NO] ,[CD_SCRIP_CD] ,[CD_SERIES] ,[CD_BUYRATE] ,[CD_SELLRATE] ,[CD_TRDBUY_QTY] ,[CD_TRDSELL_QTY] ,[CD_DELBUY_QTY] ,[CD_DELSELL_QTY] ,[CD_TRDBUYBROKERAGE] ,[CD_TRDSELLBROKERAGE] ,[CD_DELBUYBROKERAGE] ,[CD_DELSELLBROKERAGE] ,[CD_TOTALBROKERAGE] ,[CD_TRDBUYSERTAX] ,[CD_TRDSELLSERTAX] ,[CD_DELBUYSERTAX] ,[CD_DELSELLSERTAX] ,[CD_TOTALSERTAX] ,[CD_TRDBUY_TURNOVER] ,[CD_TRDSELL_TURNOVER] ,[CD_DELBUY_TURNOVER] ,[CD_DELSELL_TURNOVER] ,[CD_COMPUTATION_LEVEL] ,[CD_MIN_BROKAMT] ,[CD_MAX_BROKAMT] ,[CD_MIN_SCRIPAMT] ,[CD_MAX_SCRIPAMT] ,[CD_TIMESTAMP])
SELECT  CD_PARTY_CODE =PARTY_CODE,CD_SETT_NO=SETT_NO,CD_SETT_TYPE=SETT_TYPE ,CD_SAUDA_DATE=TRADE_DATE,CD_CONTRACTNO=CONTRACTNO,CD_TRADE_NO='',  
CD_ORDER_NO =P.ORDER_NO,  
CD_SCRIP_CD ='BRKSCR',CD_SERIES='BSE',  
CD_BUYRATE=(CASE WHEN BUY_SELL_FLAG ='1' THEN CAST(TRADE_PRICE AS MONEY) ELSE  0 END ),  
CD_SELLRATE=(CASE WHEN BUY_SELL_FLAG ='2' THEN CAST(TRADE_PRICE AS MONEY) ELSE 0 END ) ,  
CD_TRDBUY_QTY= (CASE WHEN INTRA_DELFLAG ='I' THEN (CASE WHEN BUY_SELL_FLAG ='1' THEN CAST(QTY AS FLOAT) ELSE 0 END ) ELSE 0 END),  
CD_TRDSELL_QTY=(CASE WHEN INTRA_DELFLAG ='I' THEN (CASE WHEN BUY_SELL_FLAG ='2' THEN CAST(QTY AS FLOAT) ELSE 0 END ) ELSE 0 END),  
CD_DELBUY_QTY =(CASE WHEN INTRA_DELFLAG ='D' THEN (CASE WHEN BUY_SELL_FLAG ='1' THEN CAST(QTY AS FLOAT) ELSE 0 END ) ELSE 0 END),  
CD_DELSELL_QTY=(CASE WHEN INTRA_DELFLAG ='D' THEN (CASE WHEN BUY_SELL_FLAG ='2' THEN CAST(QTY AS FLOAT) ELSE 0 END ) ELSE 0 END),  
CD_TRDBUYBROKERAGE=(CASE WHEN INTRA_DELFLAG ='I' THEN (CASE WHEN BUY_SELL_FLAG ='1' THEN CAST(BROKERAGE AS MONEY)  ELSE 0 END )ELSE 0 END),  
CD_TRDSELLBROKERAGE=(CASE WHEN INTRA_DELFLAG ='I' THEN (CASE WHEN BUY_SELL_FLAG ='2' THEN CAST(BROKERAGE AS MONEY) ELSE 0 END )ELSE 0 END),  
CD_DELBUYBROKERAGE =CAST(BROKERAGE AS MONEY),  
CD_DELSELLBROKERAGE=(CASE WHEN INTRA_DELFLAG ='D' THEN (CASE WHEN BUY_SELL_FLAG ='2' THEN CAST(BROKERAGE AS MONEY)  ELSE 0 END )ELSE 0 END),  
CD_TOTALBROKERAGE=BROKERAGE,CD_TRDBUYSERTAX=(CASE WHEN BUY_SELL_FLAG ='1' THEN CAST(BROKERAGE AS MONEY)*18/100 ELSE 0 END ),  
CD_TRDSELLSERTAX=(CASE WHEN BUY_SELL_FLAG ='2' THEN CAST(BROKERAGE AS MONEY)*18/100 ELSE 0 END ),
CD_DELBUYSERTAX=CAST(BROKERAGE AS MONEY)*18/100,CD_DELSELLSERTAX=0,  
CD_TOTALSERTAX=CAST(BROKERAGE AS MONEY)*18/100,  
CD_TRDBUY_TURNOVER= (CASE WHEN INTRA_DELFLAG ='I' THEN (CASE WHEN BUY_SELL_FLAG ='1' THEN CAST(QTY AS FLOAT)*CAST(TRADE_PRICE AS MONEY)  ELSE 0 END ) ELSE 0 END),  
CD_TRDSELL_TURNOVER= (CASE WHEN INTRA_DELFLAG ='I' THEN (CASE WHEN BUY_SELL_FLAG ='2' THEN CAST(QTY AS FLOAT)*CAST(TRADE_PRICE AS MONEY)  ELSE 0 END ) ELSE 0 END),  
CD_DELBUY_TURNOVER=(CASE WHEN INTRA_DELFLAG ='D' THEN (CASE WHEN BUY_SELL_FLAG ='1' THEN CAST(QTY AS FLOAT)*CAST(TRADE_PRICE AS MONEY)  ELSE 0 END ) ELSE 0 END),  
CD_DELSELL_TURNOVER=(CASE WHEN INTRA_DELFLAG ='D' THEN (CASE WHEN BUY_SELL_FLAG ='2' THEN CAST(QTY AS FLOAT)*CAST(TRADE_PRICE AS MONEY)  ELSE 0 END ) ELSE 0 END),  
CD_COMPUTATION_LEVEL=(CASE WHEN ORDER_NO <>'' THEN 'O'ELSE '' END),  
CD_MIN_BROKAMT='0',CD_MAX_BROKAMT='0',CD_MIN_SCRIPAMT='0',CD_MAX_SCRIPAMT='0',CD_TIMESTAMP=GETDATE()  
 FROM PRORDERWISEDETAILS_rtb P WHERE trade_date =@date   
AND  SEGMENT ='BSE CM' and security_name like '%additional%'  



delete from  AngelBSECM.BSEDB_AB.dbo.TBL_STAMP_DATA where cast (SAUDA_DATE as date)=@date and Sett_type in ('C','D','RD','RC')  
delete from  AngelBSECM.BSEDB_AB.dbo.STT_ClientDetail where cast (SAUDA_DATE as date)=@date and Sett_type in ('C','D','RD','RC')  


delete from AngelBSECM.BSEDB_AB.dbo.Charges_Detail
where CD_Sauda_Date =@date and isnull(CD_Series,'')=''


end

GO
