-- Object: PROCEDURE dbo.CLS_UPDATE_USRPWD
-- Server: 10.253.33.91 | DB: MSAJAG
--------------------------------------------------




  
CREATE PROC [dbo].[CLS_UPDATE_USRPWD]   
(  
  @USENAME VARCHAR(30),  
  @NEWPWD VARCHAR(30),  
  @NEWPWD_ORG VARCHAR(30),  
  @EMAILID VARCHAR(100)  
) AS  
--exec cls_update_usrpwd @USENAME='0a147',@NEWPWD=',sa6^$',@NEWPWD_ORG='nar3iT',@EMAILID='dipti.shrikhande@mkttech.in'
  
DECLARE @ERRCODE  INT,  
  @ERRMSG VARCHAR(MAX),  
  @EMAILFROM VARCHAR(200),  
  @EMAILTO VARCHAR(200),  
  @EMAILSUBJECT VARCHAR(300),  
  @EMAILMESSAGE VARCHAR(MAX),  
  @SMTP_SRV_NAME VARCHAR(60),  
  @COMPANYNAME VARCHAR(200),
  @PartyCode varchar(30)  
    
IF (SELECT COUNT(1) FROM TBLPRADNYAUSERS (NOLOCK) WHERE FLDUSERNAME = @USENAME) = 0  
BEGIN  
print 'IF (SELECT COUNT(1) FROM TBLPRADNYAUSERS (NOLOCK) WHERE FLDUSERNAME = @USENAME) = 0   1'  
  SET @ERRCODE = -1  
  SET @ERRMSG = 'INVALID EMAIL ID / USER ID'     
  SELECT ERRCODE = @ERRCODE, ERRMSG = @ERRMSG , EMAILFROM = @EMAILFROM, EMAILTO = @EMAILTO, EMAILSUBJECT = @EMAILSUBJECT,   
  EMAILMESSAGE = @EMAILMESSAGE, SMTP_SRV_NAME = @SMTP_SRV_NAME  
  RETURN  
END  
  
DECLARE @ADMIN_AUTO INT  
SELECT @ADMIN_AUTO = FLDADMINAUTO,@PartyCode=isnull(fldstname,0) FROM TBLPRADNYAUSERS (NOLOCK)  
WHERE FLDUSERNAME = @USENAME

  
  
IF (SELECT COUNT(1) FROM TBLADMIN (NOLOCK) WHERE FLDAUTO_ADMIN = @ADMIN_AUTO AND FLDSTNAME = 'CLIENT') > 0  
BEGIN  
 --IF (SELECT COUNT(1) FROM CLIENT_DETAILS (NOLOCK) WHERE CL_CODE = @USENAME AND EMAIL=@EMAILID)= 0  
 IF (SELECT COUNT(1) FROM MSAJAG.DBO.CLIENT_DETAILS  WHERE CL_CODE = @PartyCode AND EMAIL like '%' + @EMAILID + '%')= 0  
 BEGIN  
 --print '1'  
 print 'IF (SELECT COUNT(1) FROM [10.204.7.52].MSAJAG.DBO.CLIENT_DETAILS  WHERE CL_CODE = @USENAME AND EMAIL=@EMAILID)= 0  2'  
  SET @ERRCODE = -1  
  SET @ERRMSG = 'INVALID EMAIL ID / USER ID'     
  SELECT ERRCODE = @ERRCODE, ERRMSG = @ERRMSG , EMAILFROM = @EMAILFROM, EMAILTO = @EMAILTO, EMAILSUBJECT = @EMAILSUBJECT,   
  EMAILMESSAGE = @EMAILMESSAGE, SMTP_SRV_NAME = @SMTP_SRV_NAME  
  RETURN   
 END  
END  
ELSE  
BEGIN  
 IF (SELECT COUNT(1) FROM TBLPRADNYAUSERS (NOLOCK) WHERE FLDUSERNAME = @USENAME  
   AND (FLDADDRESS1 = @EMAILID OR FLDADDRESS2 = @EMAILID )) = 0   
 BEGIN  
--print '2'  
 print 'IF (SELECT COUNT(1) FROM TBLPRADNYAUSERS (NOLOCK) WHERE FLDUSERNAME = @USENAME  
   AND (FLDADDRESS1 = @EMAILID OR FLDADDRESS2 = @EMAILID )) = 0 3'  
  SET @ERRCODE = -1  
  SET @ERRMSG = 'INVALID EMAIL ID / USER ID'     
  SELECT ERRCODE = @ERRCODE, ERRMSG = @ERRMSG , EMAILFROM = @EMAILFROM, EMAILTO = @EMAILTO, EMAILSUBJECT = @EMAILSUBJECT,   
  EMAILMESSAGE = @EMAILMESSAGE, SMTP_SRV_NAME = @SMTP_SRV_NAME  
  RETURN  
 END  
END  
  
UPDATE TBLPRADNYAUSERS  
SET FLDPASSWORD = @NEWPWD   
WHERE FLDUSERNAME =   @USENAME   
  
UPDATE A SET  FLDFIRSTLOGIN = 'Y', FLDFORCELOGOUT = 0,FLDSTATUS=0   
FROM TBLUSERCONTROLMASTER A,  
TBLPRADNYAUSERS B  
WHERE A.FLDUSERID = B.FLDAUTO AND B.FLDUSERNAME =   @USENAME   
  
  
SELECT @EMAILFROM = EMAIL,@SMTP_SRV_NAME = SMTP_SRV_NAME,@COMPANYNAME = COMPANY FROM MSAJAG.DBO.OWNER   
  
IF ISNULL(@EMAILFROM,'') = '' --OR ISNULL(@SMTP_SRV_NAME,'') =''  
BEGIN  
 SET @ERRCODE = 1  
 SET @ERRMSG = 'PASSWORD UPDATED SUCCESSFULLY. NO EMAIL SEND. PLEASE CONTACT THE ADMINISTRATOR'     
 SELECT ERRCODE = @ERRCODE, ERRMSG = @ERRMSG , EMAILFROM = @EMAILFROM, EMAILTO = @EMAILTO,   
 EMAILSUBJECT = @EMAILSUBJECT, EMAILMESSAGE = @EMAILMESSAGE, SMTP_SRV_NAME = @SMTP_SRV_NAME  
 RETURN  
END  
  
SELECT @EMAILTO= FLDADDRESS1 FROM TBLPRADNYAUSERS (NOLOCK) WHERE FLDUSERNAME = @USENAME  
AND PATINDEX('%@%',FLDADDRESS1) > 0  
  
IF ISNULL(@EMAILTO,'') = ''  
BEGIN  
 SELECT @EMAILTO= FLDADDRESS2 FROM TBLPRADNYAUSERS (NOLOCK) WHERE FLDUSERNAME = @USENAME  
 AND PATINDEX('%@%',FLDADDRESS2) > 0  
END  
  
IF ISNULL(@EMAILTO,'') = ''  
BEGIN  
 SELECT @EMAILTO = EMAIL FROM MSAJAG.DBO.CLIENT_DETAILS  WHERE CL_CODE = @USENAME  
END  
  
SET @ERRCODE = 2  
SET @ERRMSG = 'NEW PASSWORD EMAILED TO THE REGISTRED EMAIL ID'  
  
SET @EMAILSUBJECT = 'AUTO-GENERATED E-MAIL FROM BACKOFFICE TEAM OF ' + @COMPANYNAME  
--************************
SET @EMAILMESSAGE = 'Dear Customer,<BR><BR>As per your request, please find your new Backoffice password:<BR><BR>'  
SET @EMAILMESSAGE = @EMAILMESSAGE +  'Your new password is : <FONT COLOR = RED> '  
SET @EMAILMESSAGE = @EMAILMESSAGE +   @NEWPWD_ORG  + ' </FONT><BR><BR>We request you to change your password the next time when you log in<BR><BR>'  
SET @EMAILMESSAGE = @EMAILMESSAGE +  'Your User Name is : '+@USENAME+'<BR><BR>Assuring you of our best services.<BR><BR>'  
SET @EMAILMESSAGE = @EMAILMESSAGE +  'Regards, <BR>Angel BO Team<BR>'
SET @EMAILMESSAGE = @EMAILMESSAGE +  @COMPANYNAME + '<BR>'  
--************************
  
--SET @EMAILMESSAGE = 'DEAR CUSTOMER,<BR><BR>AS PER YOUR REQUEST WE HAVE RESET YOUR BACKOFFICE ACCESS PASSWORD.<BR>'  
--SET @EMAILMESSAGE = @EMAILMESSAGE +  'PLEASE USE THE FOLLOWING PASSWORD FOR FIRST LOGIN: <FONT COLOR = RED> '  
--SET @EMAILMESSAGE = @EMAILMESSAGE +   @NEWPWD_ORG  + ' </FONT><BR>ON SUCCESSFUL FIRST LOGIN YOU SHALL BE REQUESTED '  
--SET @EMAILMESSAGE = @EMAILMESSAGE +  'TO CHANGE THE PASSWORD.<BR><BR>REGARDS, <BR><BR>CUSTOMER CARE<BR>'  
--SET @EMAILMESSAGE = @EMAILMESSAGE +  @COMPANYNAME + '<BR>'  
  
SELECT ERRCODE = @ERRCODE, ERRMSG = @ERRMSG , EMAILFROM = @EMAILFROM, EMAILTO = @EMAILTO, EMAILSUBJECT = REPLACE( @EMAILSUBJECT, '&','~' ),   
EMAILMESSAGE = Replace (REPLACE(REPLACE( @EMAILMESSAGE, '<', '$' ),'>','@'),'&','~') , SMTP_SRV_NAME = @SMTP_SRV_NAME  
  
  EXEC msdb.dbo.sp_send_dbmail  
    @profile_name ='Support',  
    @recipients = @EMAILTO,  
    @body = @EMAILMESSAGE,  
	@body_format = 'HTML',
    @subject=@EMAILSUBJECT ;
	
/*------------------------------------------------------------------ END OF THE PROC -------------------------------------*/

GO
