-- Object: PROCEDURE dbo.PROC_VAR_UPLOAD
-- Server: 10.253.33.91 | DB: MSAJAG
--------------------------------------------------


CREATE PROC [dbo].[PROC_VAR_UPLOAD](@FILEDATE VARCHAR(11), @FILEPATH VARCHAR(150)) AS    
Declare @strSql varchar(400),
@DETAILKEY	VARCHAR(10),
@RECCNT	INT
    
TRUNCATE TABLE MG02_TMP

set @strSql = 'Bulk insert MG02_TMP from ''' + @FilePath  + ''' with ( ROWTERMINATOR = ''' + char(10) + ''' )'        
Exec(@strSql)      

SELECT @DETAILKEY = ISNULL(.DBO.PIECE(FILETEXT,',',2),'0')      
FROM MG02_TMP
WHERE LEFT(FILETEXT,2) = 10 

IF @DETAILKEY <> REPLACE(CONVERT(VARCHAR,CONVERT(DATETIME,@FILEDATE),103),'/','')
	RETURN

Delete FROM varcontrol where  Detailkey = @DETAILKEY
Delete FROM varDetail where  Detailkey = @DETAILKEY

SELECT @RECCNT = ISNULL(COUNT(1),0) FROM MG02_TMP
WHERE LEFT(FILETEXT,2) = 20 

INSERT INTO VARCONTROL
SELECT ISNULL(.DBO.PIECE(FILETEXT,',',1),0), 
	   @FILEDATE, 
	   ISNULL(.DBO.PIECE(FILETEXT,',',3),0),
	   (CASE WHEN ISNULL(.DBO.PIECE(FILETEXT,',',5),'-1') = '-1' THEN '0' ELSE ISNULL(.DBO.PIECE(FILETEXT,',',4),'0') END),
	   --(CASE WHEN ISNULL(.DBO.PIECE(FILETEXT,',',5),'-1') = '-1' THEN ISNULL(.DBO.PIECE(FILETEXT,',',4),'0') ELSE ISNULL(.DBO.PIECE(FILETEXT,',',5),'0') END),
	   @RECCNT,
	   @DETAILKEY,
	   'NSE', 'CM'	   
FROM MG02_TMP
WHERE LEFT(FILETEXT,2) = 10 

INSERT INTO varDetail
SELECT ISNULL(.DBO.PIECE(FILETEXT,',',1),0), 
	   ISNULL(.DBO.PIECE(FILETEXT,',',2),''),
	   ISNULL(.DBO.PIECE(FILETEXT,',',3),''),
	   ISNULL(.DBO.PIECE(FILETEXT,',',4),''),
	   ISNULL(.DBO.PIECE(FILETEXT,',',5),0),
	   ISNULL(.DBO.PIECE(FILETEXT,',',9),0),
	   ISNULL(.DBO.PIECE(FILETEXT,',',7),0),
	   ISNULL(.DBO.PIECE(FILETEXT,',',8),0),
	   ISNULL(.DBO.PIECE(FILETEXT,',',10),0),
	   @DETAILKEY
FROM MG02_TMP
WHERE LEFT(FILETEXT,2) = 20

GO
