-- Object: PROCEDURE dbo.PROC_ADNL_FUND_UPLOAD
-- Server: 10.253.33.91 | DB: MSAJAG
--------------------------------------------------


CREATE PROC [dbo].[PROC_ADNL_FUND_UPLOAD] (@TDATE VARCHAR(10), @FILEFOR VARCHAR(20), @FILETYPE VARCHAR(50), @PROGID VARCHAR(50), @UNAME VARCHAR(50),@FILENAME VARCHAR(100) = '')

AS

-- EXEC PROC_ADNL_FUND_UPLOAD '09/04/2018', '', '', '1234567890', ''
DECLARE @RECCNT INT,
		@FILEDATE	DATETIME

SELECT @FILEDATE = CONVERT(DATETIME,LEFT(LEFT(RIGHT(@FILENAME,12),8),2) + '/' + RIGHT(LEFT(LEFT(RIGHT(@FILENAME,12),8),4),2) + '/' + LEFT(RIGHT(@FILENAME,8),4),103)

SELECT TRANSDATE, CLIENTCODE, AMOUNT, FLAG, UPLOAD_BY, UPLOAD_ON 
INTO #DATA
FROM TBL_ADHOC_LIMIT
WHERE 1 = 2 

INSERT INTO #DATA (TRANSDATE, CLIENTCODE, AMOUNT, FLAG, UPLOAD_BY, UPLOAD_ON)
SELECT @FILEDATE, .DBO.PIECE(FILE_DATA,',',2),.DBO.PIECE(FILE_DATA,',',3),'FUND',
		UPLOAD_BY = @UNAME, UPLOAD_ON = GETDATE()
FROM FILEDATA
WHERE PROGID = @PROGID  
AND CONVERT(DATETIME,.DBO.PIECE(FILE_DATA,',',1),103) = @FILEDATE

SELECT @RECCNT = 0 
SELECT @RECCNT = ISNULL(COUNT(1),0) FROM #DATA

IF @RECCNT > 0 
BEGIN 
	DELETE FROM TBL_ADHOC_LIMIT 
	WHERE TRANSDATE= @FILEDATE
	AND FLAG = 'FUND'

	INSERT INTO TBL_ADHOC_LIMIT
	SELECT * FROM #DATA
END

SELECT STRMSGCODE = 1, STRMSG = CONVERT(VARCHAR,@RECCNT) + ' RECORD(S) UPLOADED.'

GO
