-- Object: PROCEDURE dbo.VALAN_ADDITIONAL_CHARGES
-- Server: 10.253.33.91 | DB: MSAJAG
--------------------------------------------------


/*--- BILL POSTING  IPFT_CHRG ------*/

CREATE	PROC [dbo].[VALAN_ADDITIONAL_CHARGES]
		(
		@SETT_NO		VARCHAR(7),    
		@SETT_TYPE		VARCHAR(2) 
		)

		AS

		/*
		EXEC	VALAN_ADDITIONAL_CHARGES '2022521','M'
		*/

		DECLARE	@START_DATE         DATETIME,    
				@END_DATE           DATETIME,    
				@SEC_PAYIN          DATETIME,    
				@SEC_PAYOUT         DATETIME,    
				@ACNAME             VARCHAR(50),    
				@ACCODE             VARCHAR(10),
				@IPFTCHRG			VARCHAR(10)	


		SELECT	@START_DATE = START_DATE,    
				@END_DATE = END_DATE,    
				@SEC_PAYIN = SEC_PAYIN,    
				@SEC_PAYOUT = SEC_PAYOUT    
		FROM	SETT_MST (NOLOCK)
		WHERE	SETT_NO = @SETT_NO    
				AND SETT_TYPE = @SETT_TYPE 


		SELECT  @ACNAME = V.ACNAME,    
				@IPFTCHRG = V.ACCODE    
		FROM    VALANACCOUNT V(NOLOCK),
				ACCOUNT.DBO.ACMAST A(NOLOCK)    
		WHERE   V.ACCODE = A.CLTCODE
				AND V.ACNAME = 'INVESTOR PROTECTION FUND TRUST'
				AND EFFDATE = (SELECT  MAX(EFFDATE)    
								FROM   VALANACCOUNT A    
								WHERE  A.EFFDATE <= @END_DATE   
										AND V.ACNAME = A.ACNAME)    
		ORDER BY V.ACNAME   


		IF ISNULL(@ACNAME,'') = ''
		BEGIN
			SELECT 'IPFT CHARGES VALAN ACOOUNT NOT SETUP IN MASTER'
			RETURN
		END

		--SELECT @ACNAME, @IPFTCHRG, @START_DATE, @END_DATE

		DELETE	FROM ACCBILL
		WHERE	SETT_NO = @SETT_NO AND SETT_TYPE = @SETT_TYPE AND PARTY_CODE = @IPFTCHRG

		DELETE	FROM ACCBILL 
		WHERE	SETT_NO = @SETT_NO AND SETT_TYPE = @SETT_TYPE
		AND PARTY_CODE IN (SELECT ACCODE FROM VALANACCOUNT WHERE ACNAME = 'ROUNDING OFF')

		DELETE	FROM IACCBILL
		WHERE	SETT_NO = @SETT_NO AND SETT_TYPE = @SETT_TYPE AND PARTY_CODE = @IPFTCHRG

		DELETE	FROM IACCBILL 
		WHERE	SETT_NO = @SETT_NO AND SETT_TYPE = @SETT_TYPE
		AND PARTY_CODE IN (SELECT ACCODE FROM VALANACCOUNT WHERE ACNAME = 'ROUNDING OFF')


		INSERT	INTO ACCBILL
		SELECT	@IPFTCHRG,    
				0,    
				'2',    
				@SETT_NO,    
				@SETT_TYPE,    
				@START_DATE,    
				@END_DATE,    
				@SEC_PAYIN,    
				@SEC_PAYOUT,    
				ROUND(SUM(IPFT_CHRG),2),    
				BRANCH_CD,    
				'BILL POSTED' 
		FROM	TBL_ADDITIONAL_TAX_DATA T (NOLOCK),
				CLIENT1 C1 (NOLOCK)
		WHERE	T.SETT_NO = @SETT_NO    
				AND T.SETT_TYPE = @SETT_TYPE 
				AND T.PARTY_CODE = C1.CL_CODE
				AND TRDTYPE = 'N'
		GROUP BY
				BRANCH_CD,
				SETT_NO,
				SETT_TYPE


		INSERT	INTO ACCBILL
		SELECT	@IPFTCHRG,    
				0,    
				'2',    
				@SETT_NO,    
				@SETT_TYPE,    
				@START_DATE,    
				@END_DATE,    
				@SEC_PAYIN,    
				@SEC_PAYOUT,    
				ROUND(SUM(IPFT_CHRG),2),    
				'ZZZ',    
				'BILL POSTED' 
		FROM	TBL_ADDITIONAL_TAX_DATA T (NOLOCK),
				CLIENT1 C1 (NOLOCK)
		WHERE	T.SETT_NO = @SETT_NO    
				AND T.SETT_TYPE = @SETT_TYPE 
				AND T.PARTY_CODE = C1.CL_CODE
				AND TRDTYPE = 'N'
		GROUP BY
				SETT_NO,
				SETT_TYPE


		INSERT INTO ACCBILL
		SELECT PARTY_CODE=ACCODE,BILL_NO=0,
		SELL_BUY=(CASE WHEN ISNULL(SUM(CASE WHEN SELL_BUY = 1 THEN AMOUNT ELSE - AMOUNT END),0) > 0 THEN 2 ELSE 1 END),
		S.SETT_NO,S.SETT_TYPE,S.START_DATE,S.END_DATE,PAYIN_DATE=FUNDS_PAYIN,
		PAYOUT_DATE=FUNDS_PAYOUT,AMOUNT=ABS(ISNULL(SUM(CASE WHEN SELL_BUY = 1 THEN AMOUNT ELSE - AMOUNT END),0)),
		BRANCHCD,NARRATION='BILL POSTED'
		FROM ACCBILL G, SETT_MST S, VALANACCOUNT 
		WHERE S.SETT_NO = @SETT_NO
		AND S.SETT_TYPE = @SETT_TYPE
		AND S.Sett_No = G.Sett_No
		AND S.Sett_Type = G.Sett_Type
		AND ACNAME = 'ROUNDING OFF'
		AND BRANCHCD <> 'ZZZ' 
		GROUP BY ACCODE,S.SETT_NO,S.SETT_TYPE,S.START_DATE,S.END_DATE,FUNDS_PAYIN,FUNDS_PAYOUT,BRANCHCD 
		HAVING  ABS(ISNULL(SUM(CASE WHEN SELL_BUY = 1 THEN AMOUNT ELSE - AMOUNT END),0)) > 0 
		ORDER BY BRANCHCD 

		
		INSERT INTO ACCBILL
		SELECT PARTY_CODE=ACCODE,BILL_NO=0,
		SELL_BUY=(CASE WHEN ISNULL(SUM(CASE WHEN SELL_BUY = 1 THEN AMOUNT ELSE - AMOUNT END),0) > 0 THEN 2 ELSE 1 END),
		S.SETT_NO,S.SETT_TYPE,S.START_DATE,S.END_DATE,PAYIN_DATE=FUNDS_PAYIN,
		PAYOUT_DATE=FUNDS_PAYOUT,AMOUNT=ABS(ISNULL(SUM(CASE WHEN SELL_BUY = 1 THEN AMOUNT ELSE - AMOUNT END),0)),
		BRANCHCD='ZZZ',NARRATION='BILL POSTED'
		FROM ACCBILL G, SETT_MST S, VALANACCOUNT, ACCOUNT.DBO.ACMAST 
		WHERE S.SETT_NO = @SETT_NO
		AND S.SETT_TYPE = @SETT_TYPE
		AND S.Sett_No = G.Sett_No
		AND S.Sett_Type = G.Sett_Type
		AND VALANACCOUNT.ACNAME = 'ROUNDING OFF' 
		AND G.Party_Code = CLTCODE 
		AND (BRANCHCD = 'ZZZ' OR ACCAT = 4)
		GROUP BY ACCODE,S.SETT_NO,S.SETT_TYPE,S.START_DATE,S.END_DATE,FUNDS_PAYIN,FUNDS_PAYOUT  
		HAVING  ABS(ISNULL(SUM(CASE WHEN SELL_BUY = 1 THEN AMOUNT ELSE - AMOUNT END),0)) > 0  


		INSERT	INTO IACCBILL
		SELECT	@IPFTCHRG,    
				0,    
				'2',    
				@SETT_NO,    
				@SETT_TYPE,    
				@START_DATE,    
				@END_DATE,    
				@SEC_PAYIN,    
				@SEC_PAYOUT,    
				ROUND(SUM(IPFT_CHRG),2),    
				BRANCH_CD,    
				'BILL POSTED' 
		FROM	TBL_ADDITIONAL_TAX_DATA T (NOLOCK),
				CLIENT1 C1 (NOLOCK)
		WHERE	T.SETT_NO = @SETT_NO    
				AND T.SETT_TYPE = @SETT_TYPE 
				AND T.PARTY_CODE = C1.CL_CODE
				AND TRDTYPE = 'I'
		GROUP BY
				BRANCH_CD,
				SETT_NO,
				SETT_TYPE


		INSERT	INTO IACCBILL
		SELECT	@IPFTCHRG,    
				0,    
				'2',    
				@SETT_NO,    
				@SETT_TYPE,    
				@START_DATE,    
				@END_DATE,    
				@SEC_PAYIN,    
				@SEC_PAYOUT,    
				ROUND(SUM(IPFT_CHRG),2),    
				'ZZZ',    
				'BILL POSTED' 
		FROM	TBL_ADDITIONAL_TAX_DATA T (NOLOCK),
				CLIENT1 C1 (NOLOCK)
		WHERE	T.SETT_NO = @SETT_NO    
				AND T.SETT_TYPE = @SETT_TYPE 
				AND T.PARTY_CODE = C1.CL_CODE
				AND TRDTYPE = 'I'
		GROUP BY
				SETT_NO,
				SETT_TYPE


		INSERT INTO IACCBILL
		SELECT PARTY_CODE=ACCODE,BILL_NO=0,
		SELL_BUY=(CASE WHEN ISNULL(SUM(CASE WHEN SELL_BUY = 1 THEN AMOUNT ELSE - AMOUNT END),0) > 0 THEN 2 ELSE 1 END),
		S.SETT_NO,S.SETT_TYPE,S.START_DATE,S.END_DATE,PAYIN_DATE=FUNDS_PAYIN,
		PAYOUT_DATE=FUNDS_PAYOUT,AMOUNT=ABS(ISNULL(SUM(CASE WHEN SELL_BUY = 1 THEN AMOUNT ELSE - AMOUNT END),0)),
		BRANCHCD,NARRATION='BILL POSTED'
		FROM IACCBILL G, SETT_MST S, VALANACCOUNT 
		WHERE S.SETT_NO = @SETT_NO
		AND S.SETT_TYPE = @SETT_TYPE
		AND S.Sett_No = G.Sett_No
		AND S.Sett_Type = G.Sett_Type
		AND ACNAME = 'ROUNDING OFF'
		AND BRANCHCD <> 'ZZZ' 
		GROUP BY ACCODE,S.SETT_NO,S.SETT_TYPE,S.START_DATE,S.END_DATE,FUNDS_PAYIN,FUNDS_PAYOUT,BRANCHCD 
		HAVING  ABS(ISNULL(SUM(CASE WHEN SELL_BUY = 1 THEN AMOUNT ELSE - AMOUNT END),0)) > 0 
		ORDER BY BRANCHCD 

		
		INSERT INTO IACCBILL
		SELECT PARTY_CODE=ACCODE,BILL_NO=0,
		SELL_BUY=(CASE WHEN ISNULL(SUM(CASE WHEN SELL_BUY = 1 THEN AMOUNT ELSE - AMOUNT END),0) > 0 THEN 2 ELSE 1 END),
		S.SETT_NO,S.SETT_TYPE,S.START_DATE,S.END_DATE,PAYIN_DATE=FUNDS_PAYIN,
		PAYOUT_DATE=FUNDS_PAYOUT,AMOUNT=ABS(ISNULL(SUM(CASE WHEN SELL_BUY = 1 THEN AMOUNT ELSE - AMOUNT END),0)),
		BRANCHCD='ZZZ',NARRATION='BILL POSTED'
		FROM IACCBILL G, SETT_MST S, VALANACCOUNT, ACCOUNT.DBO.ACMAST 
		WHERE S.SETT_NO = @SETT_NO
		AND S.SETT_TYPE = @SETT_TYPE
		AND S.Sett_No = G.Sett_No
		AND S.Sett_Type = G.Sett_Type
		AND VALANACCOUNT.ACNAME = 'ROUNDING OFF' 
		AND G.Party_Code = CLTCODE 
		AND (BRANCHCD = 'ZZZ' OR ACCAT = 4)
		GROUP BY ACCODE,S.SETT_NO,S.SETT_TYPE,S.START_DATE,S.END_DATE,FUNDS_PAYIN,FUNDS_PAYOUT  
		HAVING  ABS(ISNULL(SUM(CASE WHEN SELL_BUY = 1 THEN AMOUNT ELSE - AMOUNT END),0)) > 0

GO
