-- Object: PROCEDURE dbo.CLS_UPLOAD_INVOICE_IRN_DETAILS
-- Server: 10.253.33.91 | DB: MSAJAG
--------------------------------------------------



--DECLARE @FILEPATH VARCHAR(300)
--SET @FILEPATH = 'D:\BACKOFFICE\EI.CSV'

--EXEC CLS_UPLOAD_INVOICE_IRN_DETAILS 'D:\BACKOFFICE\EI.CSV'

CREATE PROC [dbo].[CLS_UPLOAD_INVOICE_IRN_DETAILS]
@FILEPATH VARCHAR(300)
AS
 
 
 BEGIN

CREATE TABLE #FILEDATA
	(
		SRNO VARCHAR(50),
        INV_NO VARCHAR(150),
        INVOICE_DATE VARCHAR(150),
        BUYER_GSTIN	VARCHAR(300),
        INVOICE_VALUE VARCHAR(150),
        ACK_NO NVARCHAR(500),
        ACK_DATE NVARCHAR(500),
        IRN	NVARCHAR(300),
        EWB_NO NVARCHAR(800)   ,
		QRCODE VARCHAR(MAX)  
	)
	
	DECLARE @@SQL VARCHAR(MAX)
	SET @@SQL= ' BULK INSERT #FILEDATA FROM ''' + @FILEPATH + ''' WITH  (ROWTERMINATOR = ''0X0A'',FIELDTERMINATOR = '','', FIRSTROW=2)' -- ''\N'',
	PRINT @@SQL
	EXEC (@@SQL)



	INSERT INTO INVOICE_IRN_DETAILS
	SELECT SRNO,INV_NO,CONVERT(DATETIME,INVOICE_DATE,103),BUYER_GSTIN,INVOICE_VALUE,ACK_NO,ACK_DATE,IRN,EWB_NO,B.CL_CODE
	FROM #FILEDATA A
	INNER JOIN MSAJAG..CLIENT_DETAILS B
	ON A.BUYER_GSTIN = B.GST_NO

END

GO
