-- Object: PROCEDURE dbo.CLS_TRADE_IMPORT
-- Server: 10.253.33.91 | DB: MSAJAG
--------------------------------------------------


--SET ANSI_PADDING ON
--GO





CREATE  PROC [dbo].[CLS_TRADE_IMPORT]
(          
 @FILETYPE  VARCHAR(20),          
 @SAUDA_DATE  VARCHAR(11),          
 @FILEPATH  VARCHAR(2000),
 @STEP VARCHAR(25), 
 @PROCESS_FOR VARCHAR(100) = 'IMPORT_TRADE',  
 @IMPORTTYPE  VARCHAR(10)       
) 
/*
	EXEC DBO.[CLS_TRADE_IMPORT] @FILETYPE='SECURITY',@SAUDA_DATE='26/06/2019',@FILEPATH='D:\BACKOFFICE\TRADE\NSEEQ$SCRIP_260619.TXT|',@STEP='1',@PROCESS_FOR='IMPORT_EXCHANGE_FILE',@IMPORTTYPE='BULK'
	EXEC DBO.[CLS_TRADE_IMPORT] @FILETYPE='CP',@SAUDA_DATE='27/06/2019',@FILEPATH='D:\BACKOFFICE\TRADE\NSECASHFILEUPLOADED$27060000.MD|',@STEP='1',@PROCESS_FOR='IMPORT_EXCHANGE_FILE',@IMPORTTYPE='BULK'
	EXEC DBO.[CLS_TRADE_IMPORT] @FILETYPE='C_STT',@SAUDA_DATE='28/06/2019',@FILEPATH='D:\BACKOFFICE\TRADE\NSECASHFILEUPLOADED$C_STT_26062019.CSV|',@STEP='1',@PROCESS_FOR='IMPORT_EXCHANGE_FILE',@IMPORTTYPE='BULK'
	EXEC DBO.[CLS_TRADE_IMPORT] @FILETYPE='MWST',@SAUDA_DATE='28/06/2019',@FILEPATH='D:\BACKOFFICE\TRADE\NSECASHFILEUPLOADED$MWST_06769_T_27062019.CSV|',@STEP='1',@PROCESS_FOR='IMPORT_EXCHANGE_FILE',@IMPORTTYPE='BULK'
	EXEC DBO.[CLS_TRADE_IMPORT] @FILETYPE='C_VAR',@SAUDA_DATE='28/06/2019',@FILEPATH='D:\BACKOFFICE\TRADE\NSEEQ$C_VAR1_14062019_6.DAT|',@STEP='1',@PROCESS_FOR='IMPORT_EXCHANGE_FILE',@IMPORTTYPE='BULK'
	EXEC DBO.[CLS_TRADE_IMPORT] @FILETYPE='C_STT',@SAUDA_DATE='28/06/2019',@FILEPATH='D:\BACKOFFICE\TRADEFILES\NSE$C_STC_MAR2018_26032018.CSV|',@STEP='1',@PROCESS_FOR='IMPORT_EXCHANGE_FILE',@IMPORTTYPE='BULK'
*/           
AS
	DECLARE 

		@FILESINGLE VARCHAR(1000),
		@LOOPID INT,
		@DEFPATH VARCHAR(500),
		@IMPFILE VARCHAR(500),
		@SQL VARCHAR(8000),
		@PROCID VARCHAR(50),
		@MESSAGE VARCHAR(100),
		@INTMODE INT
		SET @MESSAGE = 'FILE UPLOADED SUCCESSFULLY'
		
IF LEN(@SAUDA_DATE) = 10 AND CHARINDEX('/', @SAUDA_DATE) > 0  
 BEGIN  
  SET @SAUDA_DATE = CONVERT(VARCHAR(11), CONVERT(DATETIME, @SAUDA_DATE, 103), 109)  
 END 

DECLARE	
	@SNO   NUMERIC(18,0),          
	@SUBPROCESSID INT         
	 
   SELECT @SNO = SNO, @SUBPROCESSID = SUB_PROCESS_ID from [CLS_TBL_PROCESS_DETAIL] where PROCESS_FOR = @PROCESS_FOR

IF @PROCESS_FOR = 'IMPORT_TRADE'
BEGIN
   IF @STEP = 'START_IMP'
   BEGIN
	TRUNCATE TABLE FOFTTRADE_1_IMP
	TRUNCATE TABLE FOFTTRADE_2_IMP
	TRUNCATE TABLE FOFTTRADE_3_IMP
	TRUNCATE TABLE FOFTTRADE_4_IMP	
	TRUNCATE TABLE FOFTTRADE_1_IMP_OMINISYS
	TRUNCATE TABLE FOFTTRADE
	TRUNCATE TABLE FOTRADE

    DELETE [CLS_TBL_PROCESS_DETAIL] WHERE PROCESS_TYPE = 'TRADE' 
    INSERT INTO [CLS_TBL_PROCESS_DETAIL] (PROCESS_DATE, BUSINESS_DATE,EXCHANGE,SEGMENT,PROCESS_TYPE,PROCESS_FOR,PROCESS_ID,SUB_PROCESS_ID,PROCESS_START_DATE,PROCESS_STARTED_DATE,PROCESS_END_DATE,PROCESS_ENDED_DATE,PROCESS_STATUS,PROCESS_HALTED_AT,INTERNAL_PROCESS_ID) VALUES 
	( @SAUDA_DATE, @SAUDA_DATE, 'NSE','FUTURES','TRADE', @PROCESS_FOR,0,0,GETDATE(),GETDATE(),GETDATE(),GETDATE(),99,'','START_IMP')

	SET @SUBPROCESSID = 0
	SET @SNO = @@IDENTITY
	

	IF @IMPORTTYPE = 'NORMAL'
	 BEGIN
		--print 'test'
		EXEC CLS_IMPORT_TRADE_FILE @FILEPATH, 'SYSTEM', @SAUDA_DATE, 1, @FILETYPE
		EXEC [CLS_PROC_TRADE_UP] @SNO, @SUBPROCESSID, @FILETYPE, @SAUDA_DATE ,@FILESINGLE, @STEP,@IMPORTTYPE
	 END
	ELSE IF @IMPORTTYPE = 'BULK'
	 BEGIN
	    TRUNCATE TABLE FOFTTRADE_1_IMP
		TRUNCATE TABLE FOFTTRADE_2_IMP
		TRUNCATE TABLE FOFTTRADE_3_IMP
		TRUNCATE TABLE FOFTTRADE_4_IMP	
		TRUNCATE TABLE FOFTTRADE_1_IMP_OMINISYS
		TRUNCATE TABLE FOFTTRADE
		TRUNCATE TABLE FOTRADE
		IF @FILETYPE = 'DBVIEW'
	     BEGIN
			EXEC CLS_IMPORT_TRADE_FILE @FILESINGLE, 'SYSTEM', @SAUDA_DATE, 2, @FILETYPE	
			EXEC [CLS_PROC_TRADE_UP] @SNO, @SUBPROCESSID, @FILETYPE, @SAUDA_DATE ,@FILESINGLE,@STEP,@IMPORTTYPE
	      END
		ELSE
		 BEGIN
			SET @LOOPID = 1
			SET @DEFPATH = .DBO.PIECE(@FILEPATH, '$', 1)
			SET @FILEPATH = .DBO.PIECE(@FILEPATH, '$', 2)
			WHILE 1 = 1
				BEGIN
					SET @FILESINGLE = .DBO.PIECE(@FILEPATH, '|', @LOOPID)
					IF @FILESINGLE = '' OR @FILESINGLE IS NULL
						BEGIN
							BREAK
						END
					SET @FILESINGLE = @DEFPATH + '\' + @FILESINGLE
					Declare @Dummy varchar(200)
					SET @Dummy = "Exec [CLS_PROC_TRADE_UP] '" + convert(varchar,@SNO) + "', '" + convert(varchar,@SUBPROCESSID) + "','" +  @FILETYPE + "','" + @SAUDA_DATE + "' ,'" + @FILESINGLE + "', '" + @STEP + "','" + @IMPORTTYPE + "' "
					--print @Dummy
					--select @SNO, @SUBPROCESSID, @FILETYPE, @SAUDA_DATE ,@FILESINGLE,@STEP,@IMPORTTYPE
					--
					EXEC CLS_IMPORT_TRADE_FILE @FILESINGLE, 'SYSTEM', @SAUDA_DATE, 2, @FILETYPE
					SET @LOOPID = @LOOPID + 1
				END
				EXEC [CLS_PROC_TRADE_UP] @SNO, @SUBPROCESSID, @FILETYPE, @SAUDA_DATE ,@FILESINGLE,@STEP,@IMPORTTYPE
		END
	 END
	END
   ELSE -- NEXT STEP 
    BEGIN
		EXEC [CLS_PROC_TRADE_UP] @SNO, @SUBPROCESSID, @FILETYPE, @SAUDA_DATE ,@FILESINGLE,@STEP,@IMPORTTYPE
	END
	SELECT * FROM [CLS_TBL_PROCESS_DETAIL] WHERE PROCESS_FOR = @PROCESS_FOR AND SNO = @SNO --and PROCESS_STATUS <> 100 
END
ELSE
 BEGIN

	SET @IMPFILE = @FILETYPE

	IF @IMPFILE <> 'TRADE'
	BEGIN
		SET @SAUDA_DATE = LEFT(CONVERT(DATETIME,@SAUDA_DATE,103),11)
	END
	
   
	DELETE [CLS_TBL_PROCESS_DETAIL] WHERE PROCESS_TYPE <> 'TRADE' 
    INSERT INTO [CLS_TBL_PROCESS_DETAIL] (PROCESS_DATE, BUSINESS_DATE,EXCHANGE,SEGMENT,PROCESS_TYPE,PROCESS_FOR,PROCESS_ID,SUB_PROCESS_ID,PROCESS_START_DATE,PROCESS_STARTED_DATE,PROCESS_END_DATE,PROCESS_ENDED_DATE,PROCESS_STATUS,PROCESS_HALTED_AT) VALUES ( @SAUDA_DATE, @SAUDA_DATE, 'NSE','FUTURES','IMPORT_EXCHANGE_FILE', @PROCESS_FOR,0,0,GETDATE(),GETDATE(),GETDATE(),GETDATE(),0,'')
	SELECT @SNO = SNO, @SUBPROCESSID = SUB_PROCESS_ID FROM [CLS_TBL_PROCESS_DETAIL] WHERE PROCESS_FOR = @PROCESS_FOR   
	SET @SUBPROCESSID = 0
	
	SET @LOOPID = 1
	SET @FILEPATH = .DBO.PIECE(replace(@FILEPATH,'|',''), '$', 1)
	--SET @FILEPATH = .DBO.PIECE(@FILEPATH, '$', 2)
	WHILE 1 = 1
		BEGIN
			
			SET @FILESINGLE = .DBO.PIECE(@FILEPATH, '|', @LOOPID)
			IF @FILESINGLE = '' OR @FILESINGLE IS NULL
				BEGIN
					BREAK
				END
			IF @IMPORTTYPE = 'NORMAL'
			BEGIN
				SET @PROCID = @FILEPATH
				SET @INTMODE = 1
				IF @IMPFILE ='CP'
				BEGIN
					SET @FILEPATH = @SAUDA_DATE
				END
			END
			SET @FILESINGLE = @FILEPATH  --@DEFPATH+ '\' + @FILESINGLE
			--print @FILESINGLE

			IF @IMPFILE ='CP'
			BEGIN
				BEGIN TRY
					EXEC PROC_FOCLOSING_MD_UP @FILESINGLE, @SAUDA_DATE, @PROCID 
				END TRY
				BEGIN CATCH 
					SELECT @MESSAGE = ERROR_MESSAGE() 
				END CATCH
			END
			IF @IMPFILE = 'F_CN01'
			BEGIN
				BEGIN TRY
					EXEC PROC_CONTRACT_MST  @FILESINGLE, @SAUDA_DATE, @PROCID 
				END TRY
				BEGIN CATCH 
					SELECT @MESSAGE = ERROR_MESSAGE() 
				END CATCH
			END
			IF @IMPFILE = 'C_SCRIP'
			BEGIN
				BEGIN TRY
					EXEC CLS_PR_COMMONSCRIPCDODE_UPLOAD @FILESINGLE, @PROCID
				END TRY
				BEGIN CATCH 
					SELECT @MESSAGE = ERROR_MESSAGE() 
				END CATCH
			END
			IF @IMPFILE = 'STT'
			BEGIN
				BEGIN TRY
					EXEC PROC_STT_STT01_UP  @FILESINGLE, @SAUDA_DATE, @PROCID  
				END TRY
				BEGIN CATCH 
					SELECT @MESSAGE = ERROR_MESSAGE() 
				END CATCH
			END
			IF @IMPFILE = 'POSITION'
			BEGIN
				BEGIN TRY
					EXEC PROC_POSITION_PS04_UP  @FILESINGLE, @SAUDA_DATE, @PROCID
				END TRY
				BEGIN CATCH 
					SELECT @MESSAGE = ERROR_MESSAGE() 
				END CATCH
			END
			IF @IMPFILE = 'MARGIN'
			BEGIN
				BEGIN TRY
 				 
					EXEC PROC_MARGIN_MG13_UP  @FILESINGLE, @SAUDA_DATE, @PROCID
					
				END TRY
				BEGIN CATCH 
					SELECT @MESSAGE = ERROR_MESSAGE() 
				END CATCH
			END
			IF @IMPFILE = 'CONTRACT'
			BEGIN
				BEGIN TRY
					EXEC PROC_CONTRACT_MST_UP  @FILESINGLE, @SAUDA_DATE , @PROCID
				END TRY
				BEGIN CATCH 
					SELECT @MESSAGE = ERROR_MESSAGE() 
				END CATCH
			END
			IF @IMPFILE = 'S_MAPP'
			BEGIN
				BEGIN TRY
					EXEC FO_SCRIPMAPPINGUPLOAD_WRAPPER @FILESINGLE, @PROCID
				END TRY
				BEGIN CATCH 
					SELECT @MESSAGE = ERROR_MESSAGE() 
				END CATCH
			END

			IF @IMPFILE = 'CORPACT_1' OR @IMPFILE = 'CORPACT_2'
			BEGIN
				BEGIN TRY
					EXEC PR_IMPORT_CORPACTFILE_FILE @PROCID,'AUTO IMPORT', @SAUDA_DATE, @INTMODE, @IMPFILE, @FILESINGLE
				END TRY
				BEGIN CATCH 
					SELECT @MESSAGE = ERROR_MESSAGE() 
				END CATCH
			END

			IF @IMPFILE = 'POSITION_STD'
			BEGIN
				BEGIN TRY
					EXEC PROC_POSITION_PS04_UP_STANDARD  @FILESINGLE, @SAUDA_DATE, @PROCID
				END TRY
				BEGIN CATCH 
					SELECT @MESSAGE = ERROR_MESSAGE() 
				END CATCH
			END

			IF @IMPFILE = 'SETT_STD'
			BEGIN
				BEGIN TRY
				--SELECT @FILESINGLE,@SAUDA_DATE
					EXEC Proc_Sett_Mst_Up_UDIFF  @FILESINGLE, 'U', @PROCID
				END TRY
				BEGIN CATCH 
					SELECT @MESSAGE = ERROR_MESSAGE() 
				END CATCH
			END

				IF @IMPFILE = 'OBLIGATION_STD'
			BEGIN
				BEGIN TRY
					EXEC CLS_OBLIGATION_IMPORT_FILE  @FILESINGLE, 'UP', '/n' , @PROCID
				END TRY
				BEGIN CATCH 
					SELECT @MESSAGE = ERROR_MESSAGE() 
				END CATCH
			END


			IF @IMPFILE = 'MARGIN_STD'
			BEGIN
				BEGIN TRY
					EXEC PROC_MARGIN_MG13_UP_STANDARD  @FILESINGLE, @SAUDA_DATE, @PROCID
				END TRY
				BEGIN CATCH 
					SELECT @MESSAGE = ERROR_MESSAGE() 
				END CATCH
			END			
			IF @IMPFILE = 'CONTRACT_STD'
			BEGIN
				BEGIN TRY
					EXEC PROC_CONTRACT_MST_UP_STANDARD  @FILESINGLE, @SAUDA_DATE , @PROCID
				END TRY
				BEGIN CATCH 
					SELECT @MESSAGE = ERROR_MESSAGE() 
				END CATCH
			END
			IF @IMPFILE = 'MARGIN_EOD'
			BEGIN
				BEGIN TRY
					EXEC PROC_MARGIN_MG13_UP_STANDARD_EOD  @FILESINGLE, @SAUDA_DATE, @PROCID
				END TRY
				BEGIN CATCH 
					SELECT @MESSAGE = ERROR_MESSAGE() 
				END CATCH
			END
			IF @IMPFILE = 'MRG_UDIFFEOD'
			BEGIN
				BEGIN TRY
					EXEC PROC_MARGIN_MG13_UP_UDIFF_EOD  @FILESINGLE, @SAUDA_DATE, @PROCID
				END TRY
				BEGIN CATCH 
					SELECT @MESSAGE = ERROR_MESSAGE() 
				END CATCH
			END
			IF @IMPFILE = 'MRG_UDIFFPEAK'
			BEGIN
				BEGIN TRY
					EXEC PROC_MARGIN_MG13_UP_UDIFF_PEAK  @FILESINGLE, @SAUDA_DATE, @PROCID
				END TRY
				BEGIN CATCH 
					SELECT @MESSAGE = ERROR_MESSAGE() 
				END CATCH
			END
			----------------- below PART SRE-38205 BY VAIBHAV K ---------------------
			IF @IMPFILE = 'C_VAR_BOD'
			BEGIN
			BEGIN TRY
			EXEC PROC_VAR_UPLOAD_BOD @SAUDA_DATE, @FILESINGLE,@PROCID
			END TRY
			BEGIN CATCH 
			SELECT @MESSAGE = ERROR_MESSAGE() 
			END CATCH
			END
						----------------- END ABOVE PART SRE-38205 BY VAIBHAV K ---------------------



			SET @LOOPID = @LOOPID + 1
		END
		IF @MESSAGE = 'FILE UPLOADED SUCCESSFULLY'
		BEGIN
			IF @IMPFILE = 'CP'
			BEGIN
				SET @SQL = ""
				SET @SQL = " SELECT *  FROM ( SELECT FLAG = (CASE WHEN ISNULL(UPCOUNT,0) > 1 THEN 1 ELSE -1 END), MSG = (CASE WHEN ISNULL(UPCOUNT,0) > 1 THEN 'FILE UPLOADED SUCCESSFULLY WITH NO OF ROWS - ' + CONVERT(VARCHAR,ISNULL(UPCOUNT,0)) ELSE 'NO DATA FOUND IN THE FILE OR FILE IS NOT CORRECT.' END) FROM FOCLOSING_COUNT ) A "
			END
			IF @IMPFILE = 'F_CN01'
			BEGIN
				SET @SQL = ""
				SET @SQL = " SELECT *  FROM ( SELECT FLAG = (CASE WHEN ISNULL(COUNT(1),0) > 1 THEN 1 ELSE -1 END), MSG = (CASE WHEN ISNULL(COUNT(1),0) > 1 THEN 'FILE UPLOADED SUCCESSFULLY WITH NO OF ROWS - ' + CONVERT(VARCHAR,ISNULL(COUNT(1),0)) ELSE 'NO DATA FOUND IN THE FILE OR FILE IS NOT CORRECT.' END) FROM FoScrip_IMP ) A "
			END
			IF @IMPFILE = 'C_SCRIP'
			BEGIN
				SET @SQL = ""
				SET @SQL = " SELECT *  FROM (SELECT FLAG = (CASE WHEN ISNULL(COUNT(1),0) >= 1 THEN 1 ELSE -1 END), MSG = (CASE WHEN ISNULL(COUNT(1),0) >= 1 THEN 'FILE UPLOADED SUCCESSFULLY WITH NO OF ROWS - ' + CONVERT(VARCHAR,ISNULL(COUNT(1),0)) ELSE 'NO DATA FOUND IN THE FILE OR FILE IS NOT CORRECT.' END) FROM CLS_COMMONSCRIP_TEMP ) A  "
			END
			IF @IMPFILE = 'CONTRACT'
			BEGIN
				SET @SQL = ""
				SET @SQL = " SELECT *  FROM ( SELECT FLAG = (CASE WHEN ISNULL(COUNT(1),0) > 1 THEN 1 ELSE -1 END), MSG = (CASE WHEN ISNULL(COUNT(1),0) > 1 THEN 'FILE UPLOADED SUCCESSFULLY WITH NO OF ROWS - ' + CONVERT(VARCHAR,ISNULL(COUNT(1),0)) ELSE 'NO DATA FOUND IN THE FILE OR FILE IS NOT CORRECT.' END) FROM FOSCRIP_IMP ) A "
			END
			IF @IMPFILE = 'STT'
			BEGIN
				SET @SQL = ""
				SET @SQL = " SELECT *  FROM ( SELECT FLAG = (CASE WHEN ISNULL(COUNT(1),0) > 1 THEN 1 ELSE -1 END), MSG = (CASE WHEN ISNULL(COUNT(1),0) > 1 THEN 'FILE UPLOADED SUCCESSFULLY WITH NO OF ROWS - ' + CONVERT(VARCHAR,ISNULL(COUNT(1),0)) ELSE 'NO DATA FOUND IN THE FILE OR FILE IS NOT CORRECT.' END) FROM STT_EXCHG WHERE STT_DATE = '" + @SAUDA_DATE + "' ) A "
			END
			IF @IMPFILE = 'POSITION'
			BEGIN
				SET @SQL = ""
				SET @SQL = " SELECT *  FROM ( SELECT FLAG = (CASE WHEN ISNULL(COUNT(1),0) > 1 THEN 1 ELSE -1 END), MSG = (CASE WHEN ISNULL(COUNT(1),0) > 1 THEN 'FILE UPLOADED SUCCESSFULLY WITH NO OF ROWS - ' + CONVERT(VARCHAR,ISNULL(COUNT(1),0)) ELSE 'NO DATA FOUND IN THE FILE OR FILE IS NOT CORRECT.' END) FROM FOEXERCISEALLOCATION_TEMP) A "
			END	
			IF @IMPFILE = 'MARGIN'
			BEGIN
				SET @SQL = ""
				SET @SQL = " SELECT *  FROM ( SELECT FLAG = (CASE WHEN ISNULL(COUNT(1),0) > 0 THEN 1 ELSE -1 END), MSG = (CASE WHEN ISNULL(COUNT(1),0) > 0 THEN 'FILE UPLOADED SUCCESSFULLY WITH NO OF ROWS : ' + CONVERT(VARCHAR,ISNULL(COUNT(1),0)) ELSE 'NO DATA FOUND IN THE FILE OR FILE IS NOT CORRECT.' END) FROM FOMARGINNEW_IMP ) A "
			END
			IF @IMPFILE = 'CORPACT_1' OR @IMPFILE = 'CORPACT_2'
			BEGIN
				SET @SQL = ""
				SET @SQL = " SELECT *  FROM ( SELECT FLAG = (CASE WHEN ISNULL(COUNT(1),0) > 0 THEN 1 ELSE -1 END), MSG = (CASE WHEN ISNULL(COUNT(1),0) > 0 THEN 'FILE UPLOADED SUCCESSFULLY WITH NO OF ROWS : ' + CONVERT(VARCHAR,ISNULL(COUNT(1),0)) ELSE 'NO DATA FOUND IN THE FILE OR FILE IS NOT CORRECT.' END) FROM FOCORPACTPOSITION_IMP ) A "
			END

			IF @IMPFILE = 'POSITION_STD'
			BEGIN
				SET @SQL = ""
				SET @SQL = " SELECT *  FROM ( SELECT FLAG = (CASE WHEN ISNULL(COUNT(1),0) > 1 THEN 1 ELSE -1 END), MSG = (CASE WHEN ISNULL(COUNT(1),0) > 1 THEN 'FILE UPLOADED SUCCESSFULLY WITH NO OF ROWS - ' + CONVERT(VARCHAR,ISNULL(COUNT(1),0)) ELSE 'NO DATA FOUND IN THE FILE OR FILE IS NOT CORRECT.' END) FROM FOEXERCISEALLOCATION_TEMP_STD ) A "
			END
			IF @IMPFILE = 'SETT_STD'
			BEGIN
				SET @SQL = ""
				SET @SQL = " SELECT *  FROM ( SELECT FLAG = (CASE WHEN ISNULL(COUNT(1),0) > 1 THEN 1 ELSE -1 END), MSG = (CASE WHEN ISNULL(COUNT(1),0) > 1 THEN 'FILE UPLOADED SUCCESSFULLY WITH NO OF ROWS - ' + CONVERT(VARCHAR,ISNULL(COUNT(1),0)) ELSE 'NO DATA FOUND IN THE FILE OR FILE IS NOT CORRECT.' END) FROM SETT_MST ) A "
			END

						IF @IMPFILE = 'OBLIGATION_STD'
			BEGIN
				SET @SQL = ""
				SET @SQL = " SELECT *  FROM ( SELECT FLAG = (CASE WHEN ISNULL(COUNT(1),0) > 1 THEN 1 ELSE -1 END), MSG = (CASE WHEN ISNULL(COUNT(1),0) > 1 THEN 'FILE UPLOADED SUCCESSFULLY WITH NO OF ROWS - ' + CONVERT(VARCHAR,ISNULL(COUNT(1),0)) ELSE 'NO DATA FOUND IN THE FILE OR FILE IS NOT CORRECT.' END) FROM TBL_NSE_OBL ) A "
			END

			IF @IMPFILE = 'MARGIN_STD' OR @IMPFILE = 'MARGIN_EOD' 
			BEGIN
				SET @SQL = ""
				SET @SQL = " SELECT *  FROM ( SELECT FLAG = (CASE WHEN ISNULL(COUNT(1),0) > 0 THEN 1 ELSE -1 END), MSG = (CASE WHEN ISNULL(COUNT(1),0) > 0 THEN 'FILE UPLOADED SUCCESSFULLY WITH NO OF ROWS : ' + CONVERT(VARCHAR,ISNULL(COUNT(1),0)) ELSE 'NO DATA FOUND IN THE FILE OR FILE IS NOT CORRECT.' END) FROM FOMARGINNEW_IMP_STD ) A "
			END
			IF @IMPFILE = 'CONTRACT_STD'
			BEGIN
				SET @SQL = ""
				SET @SQL = " SELECT *  FROM ( SELECT FLAG = (CASE WHEN ISNULL(COUNT(1),0) > 1 THEN 1 ELSE -1 END), MSG = (CASE WHEN ISNULL(COUNT(1),0) > 1 THEN 'FILE UPLOADED SUCCESSFULLY WITH NO OF ROWS - ' + CONVERT(VARCHAR,ISNULL(COUNT(1),0)) ELSE 'NO DATA FOUND IN THE FILE OR FILE IS NOT CORRECT.' END) FROM FOSCRIP_IMP_STD ) A "
			END
			IF @IMPFILE = 'MRG_UDIFFEOD'
			BEGIN
				SET @SQL = ""
				SET @SQL = " SELECT *  FROM ( SELECT FLAG = (CASE WHEN ISNULL(COUNT(1),0) > 0 THEN 1 ELSE -1 END), MSG = (CASE WHEN ISNULL(COUNT(1),0) > 0 THEN 'FILE UPLOADED SUCCESSFULLY WITH NO OF ROWS : ' + CONVERT(VARCHAR,ISNULL(COUNT(1),0)) ELSE 'NO DATA FOUND IN THE FILE OR FILE IS NOT CORRECT.' END) FROM TBL_CMMARGINNEW_UDIFF_EOD WHERE LEFT(MARGINDATE,11) = '" + @SAUDA_DATE + "') A "
			END
			IF @IMPFILE = 'MRG_UDIFFPEAK'
			BEGIN
				SET @SQL = ""
				SET @SQL = " SELECT *  FROM ( SELECT FLAG = (CASE WHEN ISNULL(COUNT(1),0) > 0 THEN 1 ELSE -1 END), MSG = (CASE WHEN ISNULL(COUNT(1),0) > 0 THEN 'FILE UPLOADED SUCCESSFULLY WITH NO OF ROWS : ' + CONVERT(VARCHAR,ISNULL(COUNT(1),0)) ELSE 'NO DATA FOUND IN THE FILE OR FILE IS NOT CORRECT.' END) FROM TBL_CMMARGINNEW_UDIFF_EOD WHERE LEFT(MARGINDATE,11) = '" + @SAUDA_DATE + "') A "
			END
			IF @IMPFILE = 'C_VAR_BOD'
			BEGIN
			SET @SQL = ""
			SET @SQL = " SELECT *  FROM ( SELECT FLAG = (CASE WHEN ISNULL(COUNT(1),0) >= 1 THEN 1 ELSE -1 END), MSG = (CASE WHEN ISNULL(COUNT(1),0) >= 1 THEN 'FILE UPLOADED SUCCESSFULLY WITH NO OF ROWS - ' + CONVERT(VARCHAR,ISNULL(COUNT(1),0)) ELSE 'NO DATA FOUND IN THE FILE OR FILE IS NOT CORRECT.' END) FROM MG02_TMP) A "
			END

		
		END	
	
	UPDATE [CLS_TBL_PROCESS_DETAIL] SET SUB_PROCESS_ID = 0,          
	PROCESS_HALTED_REASON = @MESSAGE,          
	PROCESS_STATUS = 0, PROCESS_ENDED_DATE = GETDATE(),          
	PROCESS_OUTPUT_QUERY = @SQL, PROCESS_STATUS_ALERT_INTERVAL = '00:00:00'          
	WHERE SNO = @SNO 

	SELECT * FROM [CLS_TBL_PROCESS_DETAIL] WHERE PROCESS_FOR = @PROCESS_FOR --and PROCESS_STATUS <> 100 

 END

GO
