-- Object: PROCEDURE dbo.SAUDA_SUMMARY_REPORT
-- Server: 10.253.33.91 | DB: MSAJAG
--------------------------------------------------

--SELECT * FROM CMBILLVALAN WHERE SAUDA_DATE>='2019-06-18'  
  
--INE013A01015  
--INE455F01025  
--INE081A01012  
--INE802G01018  
--INE347G01014  
  
---'''61310'',''99969'',''99971'',''99988'',''99992'',''99970'''      
---SAUDA_SUMMARY_REPORT 'JUN 18 2019 ','JUL  8 2019','INE312H01016,INE455F01025,INE013A01015,INE081A01012'  
  
CREATE PROCEDURE [dbo].[SAUDA_SUMMARY_REPORT]  
(  
  
@FDATE VARCHAR(20),  
@TDATE VARCHAR(20),  
@ISIN VARCHAR(max)  
)  
AS  
BEGIN   
 Declare @ISINCODE Varchar(max)    
     
  
SET @ISINCODE = '''' + REPLACE(@ISIN,',',''',''') + ''''       
PRINT @ISINCODE  
   
DECLARE @FromDate DATETIME=CAST(@FDATE  AS DATETIME)  
  
DECLARE @ToDate DATETIME=DATEADD(MS, -1, DATEADD(D, 1, CONVERT(DATETIME2, @TDATE)))    
  
  
  
  
SELECT 'NSE'AS EXCHANGE, A.PARTY_CODE,SAUDA_DATE,SCRIP_CD, SERIES,ISIN, SCRIP_NAME, PTRADEDQTY = SUM(PQTYTRD + PQTYDEL) ,PTRADEDAMT = SUM(PAMTTRD + PAMTDEL) ,  
STRADEDQTY = SUM(SQTYTRD + SQTYDEL),   
STRADEDAMT = SUM((CASE WHEN SQTYTRD = 0 AND SAMTTRD <> 0 THEN -SAMTTRD ELSE SAMTTRD END) + (CASE WHEN SQTYDEL = 0 AND SAMTDEL <> 0 THEN -SAMTDEL ELSE SAMTDEL END)),  
BUYBROKERAGE = SUM(PBROKDEL),  
SELLDELIVERYCHRG = SUM(SBROKDEL),  
TRADING_TOTAL_BROKRAGE =SUM(PBrokTrd+SBrokTrd),  
DELIVERY_TOTAL_BROKRAGE =SUM(PBrokDel+SBrokDel),  
Total_turnover=sum(trdamt-delamt)+ sum(delamt)  
FROM CMBILLVALAN A WITH(NOLOCK) , INTRANET.risk.dbo.client_details b (nolock)   
WHERE A.SAUDA_DATE >=@FromDate AND A.SAUDA_DATE<=@ToDate  
AND A.PARTY_CODE=B.PARTY_CODE  
--AND ISIN  IN ('+ @ISIN +')  
--AND ISIN  =@ISIN  
and isin in (SELECT VALUE FROM fn_Split(@ISIN,','))  
--AND A.PARTY_CODE ='C24892'  
and b2c='y'  
     
GROUP BY A.PARTY_CODE,SAUDA_DATE,SCRIP_CD, SERIES,ISIN, SCRIP_NAME  
UNION ALL  
  
SELECT 'BSE'AS EXCHANGE, A.PARTY_CODE,SAUDA_DATE,SCRIP_CD, SERIES,ISIN, SCRIP_NAME, PTRADEDQTY = SUM(PQTYTRD + PQTYDEL) ,PTRADEDAMT = SUM(PAMTTRD + PAMTDEL) ,  
STRADEDQTY = SUM(SQTYTRD + SQTYDEL),   
STRADEDAMT = SUM((CASE WHEN SQTYTRD = 0 AND SAMTTRD <> 0 THEN -SAMTTRD ELSE SAMTTRD END) + (CASE WHEN SQTYDEL = 0 AND SAMTDEL <> 0 THEN -SAMTDEL ELSE SAMTDEL END)),  
BUYBROKERAGE = SUM(PBROKDEL),  
SELLDELIVERYCHRG = SUM(SBROKDEL),  
TRADING_TOTAL_BROKRAGE =SUM(PBrokTrd+SBrokTrd),  
DELIVERY_TOTAL_BROKRAGE =SUM(PBrokDel+SBrokDel),  
Total_turnover=sum(trdamt-delamt)+ sum(delamt)  
FROM [AngelBSECM].BSEDB_AB.DBO.CMBILLVALAN A WITH(NOLOCK) , INTRANET.risk.dbo.client_details b (nolock)   
WHERE A.SAUDA_DATE >=@FromDate AND A.SAUDA_DATE<=@ToDate  
AND A.PARTY_CODE=B.PARTY_CODE  
---AND cltcode IN (' + @CLTCODE + ')        
--AND ISIN  IN ('+ @ISIN +')  
--AND ISIN  =@ISIN  
and isin in (SELECT VALUE FROM fn_Split(@ISIN,','))  
--AND A.PARTY_CODE ='C24892'  
and b2c='y'  
     
GROUP BY A.PARTY_CODE,SAUDA_DATE,SCRIP_CD, SERIES,ISIN, SCRIP_NAME  
 ORDER  BY a.party_code,SAUDA_DATE,ISIN  
  
  
 END

GO
