-- Object: PROCEDURE dbo.CONTRACT_COUNT
-- Server: 10.253.33.91 | DB: MSAJAG
--------------------------------------------------


CREATE PROC [dbo].[CONTRACT_COUNT]  (@DATE DATETIME)
AS

SELECT A.*,CONTRACT_COUNT ,(TRADE-CONTRACT_COUNT) AS MISMATCH FROM (
SELECT EXCHANGE,SEGMENT ,COUNT(CL_CODE) AS TRADE FROM (
SELECT DISTINCT CL_CODE,EXCHANGE,SEGMENT 
FROM 
(SELECT DISTINCT PARTY_CODE CL_CODE,EXCHANGE = 'NSE' ,SEGMENT ='CAPITAL'  
FROM SETTLEMENT WITH(NOLOCK) WHERE SAUDA_DATE >=@DATE AND SAUDA_dATE <=@DATE + ' 23:59'  AND MARKETRATE <>'0.00' AND PARTY_CODE <>'SSSS' 
UNION ALL
SELECT DISTINCT (CASE WHEN LEFT(PARTY_CODE,2)='98' THEN REPLACE(PARTY_CODE,'98','') ELSE PARTY_cODE END )  ,EXCHANGE = 'BSE' ,SEGMENT ='CAPITAL'
 FROM AngelBSECM.BSEDB_AB.DBO.SETTLEMENT WITH(NOLOCK) WHERE SAUDA_DATE >=@DATE AND SAUDA_dATE <=@DATE + ' 23:59' AND MARKETRATE <>'0.00' AND PARTY_CODE <>'AAAA' 
UNION ALL
SELECT DISTINCT PARTY_CODE ,EXCHANGE = 'NSE' ,SEGMENT ='FUTURES'  FROM ANGELFO.NSEFO.DBO.FOBILLVALAN WITH(NOLOCK) WHERE SAUDA_DATE >=@DATE 
AND SAUDA_dATE <=@DATE + ' 23:59'  AND  LEFT(INST_TYPE,3)='OPT'  AND TRADETYPE ='BT'
UNION ALL
SELECT DISTINCT PARTY_CODE ,EXCHANGE = 'NSE' ,SEGMENT ='FUTURES'  FROM ANGELFO.NSEFO.DBO.FOBILLVALAN WITH(NOLOCK) WHERE SAUDA_DATE >=@DATE 
AND SAUDA_dATE <=@DATE + ' 23:59'  AND  LEFT(INST_TYPE,3)='FUT' 
UNION ALL
SELECT DISTINCT PARTY_CODE ,EXCHANGE = 'NSX' ,SEGMENT ='FUTURES'  FROM ANGELFO.NSECURFO.DBO.FOBILLVALAN WITH(NOLOCK) WHERE SAUDA_DATE >=@DATE 
AND SAUDA_dATE <=@DATE + ' 23:59'   AND PAMT<>SAMT 
UNION ALL
SELECT DISTINCT PARTY_CODE ,EXCHANGE = 'MCD' ,SEGMENT ='FUTURES'  FROM ANGELCOMMODITY.MCDXCDS.DBO.FOBILLVALAN WITH(NOLOCK) WHERE SAUDA_DATE >=@DATE 
AND SAUDA_dATE <=@DATE + ' 23:59'   AND PAMT<>SAMT 
) A )A
GROUP BY EXCHANGE,SEGMENT )A
FULL OUTER JOIN 
(
SELECT DISTINCT EXCHANGE,SEGMENT,COUNT(PARTY_CODE) CONTRACT_COUNT FROM (
sELECT DISTINCT PARTY_CODE,EXCHANGE,SEGMENT FROM COMMON_CONTRACT_DATA WITH(NOLOCK) WHERE SAUDA_DATE >=@DATE AND SAUDA_dATE <=@DATE + ' 23:59'
)B GROUP BY EXCHANGE,SEGMENT )B ON A.EXCHANGE =B.EXCHANGE AND A.SEGMENT=B.SEGMENT

GO
