-- Object: PROCEDURE dbo.PROC_GST_INV_MONTH
-- Server: 10.253.33.91 | DB: MSAJAG
--------------------------------------------------

create  PROC [dbo].[PROC_GST_INV_MONTH]
AS

DECLARE @MONTHYEAR VARCHAR(7)

DECLARE @FROMDATE	DATETIME,
		@TODATE		DATETIME

CREATE TABLE #MONTH
(
	SNO			INT	IDENTITY(1,1),
	MONTHYEAR	VARCHAR(7)
)
SET @MONTHYEAR = 'JUL2017'

WHILE CONVERT(DATETIME,@MONTHYEAR) <= GETDATE()
BEGIN
	INSERT INTO #MONTH 
	SELECT @MONTHYEAR
	SET @MONTHYEAR = UPPER(LEFT(LEFT(DATEADD(M,1,CONVERT(DATETIME,@MONTHYEAR)),11),3) + RIGHT(LEFT(DATEADD(M,1,CONVERT(DATETIME,@MONTHYEAR)),11),4))
	PRINT @MONTHYEAR
END

SELECT * FROM #MONTH
ORDER BY SNO 

DROP TABLE #MONTH

GO
