-- Object: PROCEDURE dbo.CLS_BULK_SEG_FILE_NSE_GENE
-- Server: 10.253.33.91 | DB: MSAJAG
--------------------------------------------------










--EXEC [CLS_BULK_SEG_FILE_NSE_GENE] 'SEP 20 2023'

CREATE procedure [dbo].[CLS_BULK_SEG_FILE_NSE_GENE]
(
	@RPTDATE VARCHAR(11)
)
AS
BEGIN
DECLARE @RECCNT BIGINT,
		@SNO	BIGINT,
		@TOSNO	BIGINT,
		@FILENUMBER INT,
		@FLAG	INT,
		--@RPTDATE VARCHAR(11),
		@RUNDATE varchar(11),
		@RUNDATE2 varchar(12)

--SET @RUNDATE='SEP  4 2023'
SET @SNO = 0
SET @FILENUMBER = 1
SET @FLAG = 1
SET @TOSNO = 0
--CONVERT(DATETIME, @RUNDATE,103)
set @RUNDATE=@RPTDATE
SELECT @RPTDATE=REPLACE(CONVERT(CHAR(11), CONVERT(DATETIME, @RUNDATE,103), 103), '/', '')
DECLARE @@FILELOC VARCHAR(500), @@QUERY VARCHAR(5000), @@FILEPATH VARCHAR(100), @@SQL VARCHAR(100), @@FILENAME VARCHAR(100)

SET @RPTDATE=LTRIM(RTRIM(@RPTDATE))
SELECT TOP 1  @@FILENAME  = 'NSE_AAACM6094R_'+ltrim(rtrim(@RPTDATE))+'.CSV' 


SELECT @RECCNT=isnull(MAX(SNO),0),@SNO=isnull(MIN(SNO),0) FROM TBL_RPT_CLIENT_COLL_SEG_NSE_NEW_SEG_NILBAL(NOLOCK) WHERE CONVERT(DATETIME,DATE,103) =CONVERT(DATETIME, @RUNDATE,103)

SET @TOSNO=@SNO+3000000


DECLARE @HEADERNAME VARCHAR(7000)
SET @RUNDATE2= ''''+REPLACE(CONVERT(CHAR(10), CONVERT(DATETIME, @RUNDATE,103), 103), '/', '-')+''''
--select @RUNDATE2,@RECCNT,@SNO,@TOSNO
--RETURN
IF(@RECCNT>0)
BEGIN 
WHILE @FLAG = 1 
BEGIN
	
	SELECT @@FILEPATH = 'J:\BACKOFFICE\NIL_BALANCE\'
	SELECT @@FILELOC =  @@FILEPATH + CONVERT(VARCHAR,@FILENUMBER) +'_'+ + @@FILENAME  

	IF(@FILENUMBER = 1)
	BEGIN
		TRUNCATE TABLE CLS_FILERDATA

		--INSERT INTO CLS_FILERDATA
		--SELECT  DATE+','+CLEARING_PAN+','+TRADING_PAN+','+CP_CODE+','+CP_PAN+','+CLIENT_PAN+','+ACCOUNT_TYPE+','+SEGMENT_INDICATOR+','+MTOM+','+VDT_LEDGER+','+EDT_LEDGER+','+PEAK_LEDGER+','+BG_REC_TM+','+FD_REC_TM+','+APPROVED_SEC_CASH_REC_TM+','+
		--APPROVED_SEC_NONCASH_REC_TM+','+NONAPPROVED_SEC_REC_TM+','+CC_APPROVED_COMM_REC_TM+','+OTHER_COLL_REC_TM+','+LIEU_EPI_LEDGER_CLTM+','+POOL_ACCOUNT_CLTM+','+CASH_RET_TM+','+BG_RET_TM+','+FD_RET_TM+','+APPROVED_SEC_CASH_RET_TM+','+APPROVED_SEC_NONCASH_RET_TM+','+
		--NONAPPROVED_SEC_RET_TM+','+CC_APPROVED_COMM_RET_TM+','+OTHER_COLL_RET_TM+','+CASH_WCM+','+BG_WCM+','+FD_WCM+','+APPROVED_SEC_CASH_WCM+','+APPROVED_SEC_NONCASH_WCM+','+NONAPPROVED_SEC_RET_WCM+','+CC_APPROVED_COMM_WCM+','+OTHER_COLL_WCM+','+CASH_RET_WCM+','+BG_RET_CM+','+
		--FD_RET_CM+','+APPROVED_SEC_CASH_RET_CM+','+APPROVED_SEC_NONCASH_RET_CM+','+NONAPPROVED_SEC_RET_RET_CM+','+CC_APPROVED_COMM_RET_CM+','+OTHER_COLL_RET_CM+','+CASH_WNCL+','+BG_WNCL+','+
		--FD_WNCL+','+APPROVED_SEC_CASH_WNCL+','+APPROVED_SEC_NONCASH_WNCL+','+CC_APPROVED_COMM_WNCL+','+MTF_INDICATOR+','+UNCLEAR_RECEIPT+','+GOV_SEC_TBILL_REC_BY_TM+','+GOV_SEC_TBILL_RET_BY_TM+','+
		--GOV_SEC_TBILL_PLACED_BY_CM+','+GOV_SEC_TBILL_RET_BY_CM+','+GOV_SEC_TBILL_PLACED_BY_NCL+','+BG_FUNDED_RET_WITH_CM+','+BG_NONFUNDED_RET_WITH_CM+','+BG_FUNDED_PLACED_WITH_NCL+','+BG_NONFUNDED_PLACED_WITH_NCL+','+
		--SETTLEMENT_AMOUNT+','+UNCLAIM_CL_FUNDS+','+CASH_COLL_MTF_POSITION FROM 
		--MSAJAG.DBO.TBL_RPT_CLIENT_COLL_SEG_NSE_NEW_SEG_NILBAL_MCDX_HEADER 
		SET @HEADERNAME=''
		SET @HEADERNAME='DATE,CLEARING MEMBER PAN,TRADING MEMBER PAN,CP CODE,CP PAN,CLIENT PAN,ACCOUNT TYPE,SEGMENT INDICATOR,UCC CODE,FINANCIAL LEDGER BALANCE-A IN THE BOOKS OF TM FOR CLIENTS AND IN THE BOOKS OF CM FOR TM (PRO) AND IN THE BOOKS OF CM FOR CP,FINANCIAL LEDGER BALANCE (CLEAR)-B IN THE BOOKS OF TM FOR CLIENTS AND IN THE BOOKS OF CM FOR TM (PRO) AND IN THE BOOKS OF CM FOR CP,PEAK FINANCIAL LEDGER BALANCE (CLEAR)-C IN THE BOOKS OF TM FOR CLIENTS AND IN THE BOOKS OF CM FOR TM (PRO) AND IN THE BOOKS OF CM FOR CP,BANK GUARANTEE (BG) RECEIVED BY TM FROM CLIENTS AND BY CM FROM TM (PRO) AND FROM CPS,FIXED DEPOSIT RECEIPT (FDR) RECEIVED BY TM FROM CLIENTS AND BY CM FROM TM(PRO) AND FROM CPS,APPROVED SECURITIES CASH COMPONENT RECEIVED BY TM FROM CLIENTS AND BY CM FROM TM(PRO) AND FROM CPS,APPROVED SECURITIES NON-CASH COMPONENT RECEIVED BY TM FROM CLIENTS AND BY CM FROM TM(PRO) AND FROM CPS,NON-APPROVED SECURITIES RECEIVED BY TM FROM CLIENTS AND BY CM FROM TM(PRO) AND FROM CPS,VALUE OF CC APPROVED COMMODITIES RECEIVED BY TM FROM CLIENTS AND BY CM FROM TM(PRO) AND FROM CPS,OTHER COLLATERALS RECEIVED BY TM FROM CLIENTS AND BY CM FROM TM(PRO) AND FROM CPS,CREDIT ENTRY IN LEDGER IN LIEU OF EPI FOR CLIENTS / TM PRO,POOL ACCOUNT FOR CLIENTS / TM PRO,CASH RETAINED BY TM,BANK GUARANTEE (BG) RETAINED BY TM,FIXED DEPOSIT RECEIPT (FDR) RETAINED BY TM,APPROVED SECURITIES CASH COMPONENT RETAINED BY TM,APPROVED SECURITIES NON-CASH COMPONENT RETAINED BY TM,NON-APPROVED SECURITIES RETAINED BY TM,VALUE OF CC APPROVED COMMODITIES RETAINED BY TM,OTHER COLLATERALS RETAINED BY TM,CASH PLACED WITH CM,BANK GUARANTEE (BG) PLACED WITH CM,FIXED DEPOSIT RECEIPT (FDR) PLACED WITH CM,APPROVED SECURITIES CASH COMPONENT PLACED WITH CM,APPROVED SECURITIES NON-CASH COMPONENT PLACED WITH CM,NON-APPROVED SECURITIES PLACED WITH CM,VALUE OF CC APPROVED COMMODITIES PLACED WITH CM,OTHER COLLATERALS PLACED WITH CM,CASH RETAINED WITH CM,BANK GUARANTEE (BG) RETAINED WITH CM,FIXED DEPOSIT RECEIPT (FDR) RETAINED WITH CM,APPROVED SECURITIES CASH COMPONENT RETAINED WITH CM,APPROVED SECURITIES NON-CASH COMPONENT RETAINED WITH CM,NON-APPROVED SECURITIES RETAINED WITH CM,VALUE OF CC APPROVED COMMODITIES RETAINED WITH CM,OTHER COLLATERALS RETAINED WITH CM,CASH PLACED WITH NCL,BANK GUARANTEE (BG) PLACED WITH NCL,FIXED DEPOSIT RECEIPT (FDR) PLACED WITH NCL,APPROVED SECURITIES CASH COMPONENT PLACED WITH NCL,APPROVED SECURITIES NON-CASH COMPONENT PLACED WITH NCL,VALUE OF CC APPROVED COMMODITIES PLACED WITH NCL,MTF /NON MTF INDICATOR,UNCLEARED RECEIPTS,GOVT SECURITIES / T-BILLS RECEIVED BY TM FROM CLIENTS AND BY CM FROM TM(PRO) AND FROM CPS,GOVT SECURITIES /T-BILLS RETAINED BY TM,GOVT SECURITIES/T-BILLS PLACED WITH CM,GOVT SECURITIES/T BILLS RETAINED WITH CM,GOVT SECURITIES/T BILLS PLACED WITH NCL,BANK GUARANTEE (BG) FUNDED PORTION RETAINED WITH CM,BANK GUARANTEE (BG) NON FUNDED PORTION RETAINED WITH CM,BANK GUARANTEE (BG) FUNDED PORTION PLACED WITH NCL,BANK GUARANTEE (BG) NON FUNDED PORTION PLACED WITH NCL,SETTLEMENT AMOUNT,UNCLAIMED/UNSETTLED CLIENT FUNDS,CASH COLLATERAL FOR MTF POSITIONS'
		
		INSERT INTO CLS_FILERDATA
		SELECT @HEADERNAME

		

		INSERT INTO CLS_FILERDATA
		SELECT   DATE+','+CLEARING_PAN+','+TRADING_PAN+','+CP_CODE+','+CP_PAN+','+CLIENT_PAN+','+ACCOUNT_TYPE+','+SEGMENT_INDICATOR+','+MTOM+','+CONVERT(VARCHAR(70),VDT_LEDGER)+','+
		CONVERT(VARCHAR(70),EDT_LEDGER)+','+
		CONVERT(VARCHAR(70),PEAK_LEDGER)+','+
		CONVERT(VARCHAR(70),BG_REC_TM)+','+
		CONVERT(VARCHAR(70),FD_REC_TM)+','+
		CONVERT(VARCHAR(70),APPROVED_SEC_CASH_REC_TM)+','+
		CONVERT(VARCHAR(70),APPROVED_SEC_NONCASH_REC_TM)+','+
		CONVERT(VARCHAR(70),NONAPPROVED_SEC_REC_TM)+','+
		CONVERT(VARCHAR(70),CC_APPROVED_COMM_REC_TM)+','+
		CONVERT(VARCHAR(70),OTHER_COLL_REC_TM)+','+
		CONVERT(VARCHAR(70),LIEU_EPI_LEDGER_CLTM)+','+
		CONVERT(VARCHAR(70),POOL_ACCOUNT_CLTM)+','+
		CONVERT(VARCHAR(70),CASH_RET_TM)+','+
		CONVERT(VARCHAR(70),BG_RET_TM)+','+
		CONVERT(VARCHAR(70),FD_RET_TM)+','+
		CONVERT(VARCHAR(70),APPROVED_SEC_CASH_RET_TM)+','+
		CONVERT(VARCHAR(70),APPROVED_SEC_NONCASH_RET_TM)+','+
		CONVERT(VARCHAR(70),NONAPPROVED_SEC_RET_TM)+','+
		CONVERT(VARCHAR(70),CC_APPROVED_COMM_RET_TM)+','+
		CONVERT(VARCHAR(70),OTHER_COLL_RET_TM)+','+
		CONVERT(VARCHAR(70),CASH_WCM)+','+
		CONVERT(VARCHAR(70),BG_WCM)+','+
		CONVERT(VARCHAR(70),FD_WCM)+','+
		CONVERT(VARCHAR(70),APPROVED_SEC_CASH_WCM)+','+
		CONVERT(VARCHAR(70),APPROVED_SEC_NONCASH_WCM)+','+
		CONVERT(VARCHAR(70),NONAPPROVED_SEC_RET_WCM)+','+
		CONVERT(VARCHAR(70),CC_APPROVED_COMM_WCM)+','+
		CONVERT(VARCHAR(70),OTHER_COLL_WCM)+','+
		CONVERT(VARCHAR(70),CASH_RET_WCM)+','+
		CONVERT(VARCHAR(70),BG_RET_CM)+','+
		CONVERT(VARCHAR(70),FD_RET_CM)+','+
		CONVERT(VARCHAR(70),APPROVED_SEC_CASH_RET_CM)+','+
		CONVERT(VARCHAR(70),APPROVED_SEC_NONCASH_RET_CM)+','+
		CONVERT(VARCHAR(70),NONAPPROVED_SEC_RET_RET_CM)+','+
		CONVERT(VARCHAR(70),CC_APPROVED_COMM_RET_CM)+','+
		CONVERT(VARCHAR(70),OTHER_COLL_RET_CM)+','+
		CONVERT(VARCHAR(70),CASH_WNCL)+','+
		CONVERT(VARCHAR(70),BG_WNCL)+','+
		CONVERT(VARCHAR(70),FD_WNCL)+','+
		CONVERT(VARCHAR(70),APPROVED_SEC_CASH_WNCL)+','+
		CONVERT(VARCHAR(70),APPROVED_SEC_NONCASH_WNCL)+','+
		CONVERT(VARCHAR(70),CC_APPROVED_COMM_WNCL)+','+
		CONVERT(VARCHAR(70),MTF_INDICATOR)+','+
		CONVERT(VARCHAR(70),UNCLEAR_RECEIPT)+','+
		CONVERT(VARCHAR(70),GOV_SEC_TBILL_REC_BY_TM)+','+
		CONVERT(VARCHAR(70),GOV_SEC_TBILL_RET_BY_TM)+','+
		CONVERT(VARCHAR(70),GOV_SEC_TBILL_PLACED_BY_CM)+','+
		CONVERT(VARCHAR(70),GOV_SEC_TBILL_RET_BY_CM)+','+
		CONVERT(VARCHAR(70),GOV_SEC_TBILL_PLACED_BY_NCL)+','+
		CONVERT(VARCHAR(70),BG_FUNDED_RET_WITH_CM)+','+
		CONVERT(VARCHAR(70),BG_NONFUNDED_RET_WITH_CM)+','+
		CONVERT(VARCHAR(70),BG_FUNDED_PLACED_WITH_NCL)+','+
		CONVERT(VARCHAR(70),BG_NONFUNDED_PLACED_WITH_NCL)+','+
		CONVERT(VARCHAR(70),SETTLEMENT_AMOUNT)+','+
		CONVERT(VARCHAR(70),UNCLAIM_CL_FUNDS)+','+
		CONVERT(VARCHAR(70),CASH_COLL_MTF_POSITION) 
		FROM MSAJAG.DBO.TBL_RPT_CLIENT_COLL_SEG_NSE_NEW_SEG_NILBAL(NOLOCK) --WHERE SNO > 22398883 AND SNO <= 25398883 AND DATE='11-09-2023'
		WHERE SNO > CONVERT(VARCHAR,@SNO) AND SNO <=  CONVERT(VARCHAR,@TOSNO) AND DATE=REPLACE(CONVERT(CHAR(10), CONVERT(DATETIME, @RUNDATE,103), 103), '/', '-')  


		
		--SET @@QUERY = ' BCP " SELECT DATE,CLEARING_PAN,TRADING_PAN,CP_CODE,CP_PAN,CLIENT_PAN,ACCOUNT_TYPE,SEGMENT_INDICATOR,MTOM,VDT_LEDGER,EDT_LEDGER,PEAK_LEDGER,BG_REC_TM,FD_REC_TM,APPROVED_SEC_CASH_REC_TM,APPROVED_SEC_NONCASH_REC_TM,NONAPPROVED_SEC_REC_TM,CC_APPROVED_COMM_REC_TM,OTHER_COLL_REC_TM,LIEU_EPI_LEDGER_CLTM,POOL_ACCOUNT_CLTM,CASH_RET_TM,BG_RET_TM,FD_RET_TM,APPROVED_SEC_CASH_RET_TM,APPROVED_SEC_NONCASH_RET_TM,NONAPPROVED_SEC_RET_TM,CC_APPROVED_COMM_RET_TM,OTHER_COLL_RET_TM,CASH_WCM,BG_WCM,FD_WCM,APPROVED_SEC_CASH_WCM,APPROVED_SEC_NONCASH_WCM,NONAPPROVED_SEC_RET_WCM,CC_APPROVED_COMM_WCM,OTHER_COLL_WCM,CASH_RET_WCM,BG_RET_CM,FD_RET_CM,APPROVED_SEC_CASH_RET_CM,APPROVED_SEC_NONCASH_RET_CM,NONAPPROVED_SEC_RET_RET_CM,CC_APPROVED_COMM_RET_CM,OTHER_COLL_RET_CM,CASH_WNCL,BG_WNCL,FD_WNCL,APPROVED_SEC_CASH_WNCL,APPROVED_SEC_NONCASH_WNCL,CC_APPROVED_COMM_WNCL,MTF_INDICATOR,UNCLEAR_RECEIPT,GOV_SEC_TBILL_REC_BY_TM,GOV_SEC_TBILL_RET_BY_TM,GOV_SEC_TBILL_PLACED_BY_CM,GOV_SEC_TBILL_RET_BY_CM,GOV_SEC_TBILL_PLACED_BY_NCL,BG_FUNDED_RET_WITH_CM,BG_NONFUNDED_RET_WITH_CM,BG_FUNDED_PLACED_WITH_NCL,BG_NONFUNDED_PLACED_WITH_NCL,SETTLEMENT_AMOUNT,UNCLAIM_CL_FUNDS,CASH_COLL_MTF_POSITION FROM MSAJAG.DBO.TBL_RPT_CLIENT_COLL_SEG_NSE_NEW_SEG_NILBAL_MCDX_HEADER UNION ALL SELECT DATE,CLEARING_PAN,TRADING_PAN,CP_CODE,CP_PAN,CLIENT_PAN,ACCOUNT_TYPE,SEGMENT_INDICATOR,MTOM,CONVERT(VARCHAR(70),VDT_LEDGER),CONVERT(VARCHAR(70),EDT_LEDGER),CONVERT(VARCHAR(70),PEAK_LEDGER),CONVERT(VARCHAR(70),BG_REC_TM),CONVERT(VARCHAR(70),FD_REC_TM),CONVERT(VARCHAR(70),APPROVED_SEC_CASH_REC_TM),CONVERT(VARCHAR(70),APPROVED_SEC_NONCASH_REC_TM),CONVERT(VARCHAR(70),NONAPPROVED_SEC_REC_TM),CONVERT(VARCHAR(70),CC_APPROVED_COMM_REC_TM),CONVERT(VARCHAR(70),OTHER_COLL_REC_TM),CONVERT(VARCHAR(70),LIEU_EPI_LEDGER_CLTM),CONVERT(VARCHAR(70),POOL_ACCOUNT_CLTM),CONVERT(VARCHAR(70),CASH_RET_TM),CONVERT(VARCHAR(70),BG_RET_TM),CONVERT(VARCHAR(70),FD_RET_TM),CONVERT(VARCHAR(70),APPROVED_SEC_CASH_RET_TM),CONVERT(VARCHAR(70),APPROVED_SEC_NONCASH_RET_TM),CONVERT(VARCHAR(70),NONAPPROVED_SEC_RET_TM),CONVERT(VARCHAR(70),CC_APPROVED_COMM_RET_TM),CONVERT(VARCHAR(70),OTHER_COLL_RET_TM),CONVERT(VARCHAR(70),CASH_WCM),CONVERT(VARCHAR(70),BG_WCM),CONVERT(VARCHAR(70),FD_WCM),CONVERT(VARCHAR(70),APPROVED_SEC_CASH_WCM),CONVERT(VARCHAR(70),APPROVED_SEC_NONCASH_WCM),CONVERT(VARCHAR(70),NONAPPROVED_SEC_RET_WCM),CONVERT(VARCHAR(70),CC_APPROVED_COMM_WCM),CONVERT(VARCHAR(70),OTHER_COLL_WCM),CONVERT(VARCHAR(70),CASH_RET_WCM),CONVERT(VARCHAR(70),BG_RET_CM),CONVERT(VARCHAR(70),FD_RET_CM),CONVERT(VARCHAR(70),APPROVED_SEC_CASH_RET_CM),CONVERT(VARCHAR(70),APPROVED_SEC_NONCASH_RET_CM),CONVERT(VARCHAR(70),NONAPPROVED_SEC_RET_RET_CM),CONVERT(VARCHAR(70),CC_APPROVED_COMM_RET_CM),CONVERT(VARCHAR(70),OTHER_COLL_RET_CM),CONVERT(VARCHAR(70),CASH_WNCL),CONVERT(VARCHAR(70),BG_WNCL),CONVERT(VARCHAR(70),FD_WNCL),CONVERT(VARCHAR(70),APPROVED_SEC_CASH_WNCL),CONVERT(VARCHAR(70),APPROVED_SEC_NONCASH_WNCL),CONVERT(VARCHAR(70),CC_APPROVED_COMM_WNCL),CONVERT(VARCHAR(70),MTF_INDICATOR),CONVERT(VARCHAR(70),UNCLEAR_RECEIPT),CONVERT(VARCHAR(70),GOV_SEC_TBILL_REC_BY_TM),CONVERT(VARCHAR(70),GOV_SEC_TBILL_RET_BY_TM),CONVERT(VARCHAR(70),GOV_SEC_TBILL_PLACED_BY_CM),CONVERT(VARCHAR(70),GOV_SEC_TBILL_RET_BY_CM),CONVERT(VARCHAR(70),GOV_SEC_TBILL_PLACED_BY_NCL),CONVERT(VARCHAR(70),BG_FUNDED_RET_WITH_CM),CONVERT(VARCHAR(70),BG_NONFUNDED_RET_WITH_CM),CONVERT(VARCHAR(70),BG_FUNDED_PLACED_WITH_NCL),CONVERT(VARCHAR(70),BG_NONFUNDED_PLACED_WITH_NCL),CONVERT(VARCHAR(70),SETTLEMENT_AMOUNT),CONVERT(VARCHAR(70),UNCLAIM_CL_FUNDS),CONVERT(VARCHAR(70),CASH_COLL_MTF_POSITION) FROM MSAJAG.DBO.TBL_RPT_CLIENT_COLL_SEG_NSE_NEW_SEG_NILBAL(NOLOCK) WHERE SNO > ' + CONVERT(VARCHAR,@SNO) + ' AND SNO <= '+ CONVERT(VARCHAR,@TOSNO)+' AND DATE='+@RUNDATE2 + '  " QUERYOUT "' + @@FILELOC + '" -c -UTF8 -T -Slocalhost ' 
		SET @@QUERY = ' BCP " SELECT FILEDATA FROM MSAJAG.DBO.CLS_FILERDATA(NOLOCK) ORDER BY SRNO " QUERYOUT "' + @@FILELOC + '" -c -UTF8 -T -Slocalhost ' 

	END
	ELSE IF(@FILENUMBER <> 1)
	BEGIN
		TRUNCATE TABLE CLS_FILERDATA


		

		--INSERT INTO CLS_FILERDATA
		--SELECT FILEDATA = DATE+','+CLEARING_PAN+','+TRADING_PAN+','+CP_CODE+','+CP_PAN+','+CLIENT_PAN+','+ACCOUNT_TYPE+','+SEGMENT_INDICATOR+','+MTOM+','+VDT_LEDGER+','+EDT_LEDGER+','+PEAK_LEDGER+','+BG_REC_TM+','+FD_REC_TM+','+APPROVED_SEC_CASH_REC_TM+','+
		--APPROVED_SEC_NONCASH_REC_TM+','+NONAPPROVED_SEC_REC_TM+','+CC_APPROVED_COMM_REC_TM+','+OTHER_COLL_REC_TM+','+LIEU_EPI_LEDGER_CLTM+','+POOL_ACCOUNT_CLTM+','+CASH_RET_TM+','+BG_RET_TM+','+FD_RET_TM+','+APPROVED_SEC_CASH_RET_TM+','+APPROVED_SEC_NONCASH_RET_TM+','+
		--NONAPPROVED_SEC_RET_TM+','+CC_APPROVED_COMM_RET_TM+','+OTHER_COLL_RET_TM+','+CASH_WCM+','+BG_WCM+','+FD_WCM+','+APPROVED_SEC_CASH_WCM+','+APPROVED_SEC_NONCASH_WCM+','+NONAPPROVED_SEC_RET_WCM+','+CC_APPROVED_COMM_WCM+','+OTHER_COLL_WCM+','+CASH_RET_WCM+','+BG_RET_CM+','+
		--FD_RET_CM+','+APPROVED_SEC_CASH_RET_CM+','+APPROVED_SEC_NONCASH_RET_CM+','+NONAPPROVED_SEC_RET_RET_CM+','+CC_APPROVED_COMM_RET_CM+','+OTHER_COLL_RET_CM+','+CASH_WNCL+','+BG_WNCL+','+
		--FD_WNCL+','+APPROVED_SEC_CASH_WNCL+','+APPROVED_SEC_NONCASH_WNCL+','+CC_APPROVED_COMM_WNCL+','+MTF_INDICATOR+','+UNCLEAR_RECEIPT+','+GOV_SEC_TBILL_REC_BY_TM+','+GOV_SEC_TBILL_RET_BY_TM+','+
		--GOV_SEC_TBILL_PLACED_BY_CM+','+GOV_SEC_TBILL_RET_BY_CM+','+GOV_SEC_TBILL_PLACED_BY_NCL+','+BG_FUNDED_RET_WITH_CM+','+BG_NONFUNDED_RET_WITH_CM+','+BG_FUNDED_PLACED_WITH_NCL+','+BG_NONFUNDED_PLACED_WITH_NCL+','+
		--SETTLEMENT_AMOUNT+','+UNCLAIM_CL_FUNDS+','+CASH_COLL_MTF_POSITION FROM 
		--MSAJAG.DBO.TBL_RPT_CLIENT_COLL_SEG_NSE_NEW_SEG_NILBAL_MCDX_HEADER 
		
		SET @HEADERNAME=''
		SET @HEADERNAME='DATE,CLEARING MEMBER PAN,TRADING MEMBER PAN,CP CODE,CP PAN,CLIENT PAN,ACCOUNT TYPE,SEGMENT INDICATOR,UCC CODE,FINANCIAL LEDGER BALANCE-A IN THE BOOKS OF TM FOR CLIENTS AND IN THE BOOKS OF CM FOR TM (PRO) AND IN THE BOOKS OF CM FOR CP,FINANCIAL LEDGER BALANCE (CLEAR)-B IN THE BOOKS OF TM FOR CLIENTS AND IN THE BOOKS OF CM FOR TM (PRO) AND IN THE BOOKS OF CM FOR CP,PEAK FINANCIAL LEDGER BALANCE (CLEAR)-C IN THE BOOKS OF TM FOR CLIENTS AND IN THE BOOKS OF CM FOR TM (PRO) AND IN THE BOOKS OF CM FOR CP,BANK GUARANTEE (BG) RECEIVED BY TM FROM CLIENTS AND BY CM FROM TM (PRO) AND FROM CPS,FIXED DEPOSIT RECEIPT (FDR) RECEIVED BY TM FROM CLIENTS AND BY CM FROM TM(PRO) AND FROM CPS,APPROVED SECURITIES CASH COMPONENT RECEIVED BY TM FROM CLIENTS AND BY CM FROM TM(PRO) AND FROM CPS,APPROVED SECURITIES NON-CASH COMPONENT RECEIVED BY TM FROM CLIENTS AND BY CM FROM TM(PRO) AND FROM CPS,NON-APPROVED SECURITIES RECEIVED BY TM FROM CLIENTS AND BY CM FROM TM(PRO) AND FROM CPS,VALUE OF CC APPROVED COMMODITIES RECEIVED BY TM FROM CLIENTS AND BY CM FROM TM(PRO) AND FROM CPS,OTHER COLLATERALS RECEIVED BY TM FROM CLIENTS AND BY CM FROM TM(PRO) AND FROM CPS,CREDIT ENTRY IN LEDGER IN LIEU OF EPI FOR CLIENTS / TM PRO,POOL ACCOUNT FOR CLIENTS / TM PRO,CASH RETAINED BY TM,BANK GUARANTEE (BG) RETAINED BY TM,FIXED DEPOSIT RECEIPT (FDR) RETAINED BY TM,APPROVED SECURITIES CASH COMPONENT RETAINED BY TM,APPROVED SECURITIES NON-CASH COMPONENT RETAINED BY TM,NON-APPROVED SECURITIES RETAINED BY TM,VALUE OF CC APPROVED COMMODITIES RETAINED BY TM,OTHER COLLATERALS RETAINED BY TM,CASH PLACED WITH CM,BANK GUARANTEE (BG) PLACED WITH CM,FIXED DEPOSIT RECEIPT (FDR) PLACED WITH CM,APPROVED SECURITIES CASH COMPONENT PLACED WITH CM,APPROVED SECURITIES NON-CASH COMPONENT PLACED WITH CM,NON-APPROVED SECURITIES PLACED WITH CM,VALUE OF CC APPROVED COMMODITIES PLACED WITH CM,OTHER COLLATERALS PLACED WITH CM,CASH RETAINED WITH CM,BANK GUARANTEE (BG) RETAINED WITH CM,FIXED DEPOSIT RECEIPT (FDR) RETAINED WITH CM,APPROVED SECURITIES CASH COMPONENT RETAINED WITH CM,APPROVED SECURITIES NON-CASH COMPONENT RETAINED WITH CM,NON-APPROVED SECURITIES RETAINED WITH CM,VALUE OF CC APPROVED COMMODITIES RETAINED WITH CM,OTHER COLLATERALS RETAINED WITH CM,CASH PLACED WITH NCL,BANK GUARANTEE (BG) PLACED WITH NCL,FIXED DEPOSIT RECEIPT (FDR) PLACED WITH NCL,APPROVED SECURITIES CASH COMPONENT PLACED WITH NCL,APPROVED SECURITIES NON-CASH COMPONENT PLACED WITH NCL,VALUE OF CC APPROVED COMMODITIES PLACED WITH NCL,MTF /NON MTF INDICATOR,UNCLEARED RECEIPTS,GOVT SECURITIES / T-BILLS RECEIVED BY TM FROM CLIENTS AND BY CM FROM TM(PRO) AND FROM CPS,GOVT SECURITIES /T-BILLS RETAINED BY TM,GOVT SECURITIES/T-BILLS PLACED WITH CM,GOVT SECURITIES/T BILLS RETAINED WITH CM,GOVT SECURITIES/T BILLS PLACED WITH NCL,BANK GUARANTEE (BG) FUNDED PORTION RETAINED WITH CM,BANK GUARANTEE (BG) NON FUNDED PORTION RETAINED WITH CM,BANK GUARANTEE (BG) FUNDED PORTION PLACED WITH NCL,BANK GUARANTEE (BG) NON FUNDED PORTION PLACED WITH NCL,SETTLEMENT AMOUNT,UNCLAIMED/UNSETTLED CLIENT FUNDS,CASH COLLATERAL FOR MTF POSITIONS'
		
		INSERT INTO CLS_FILERDATA
		SELECT @HEADERNAME

		INSERT INTO CLS_FILERDATA 
		SELECT FILEDATA= DATE+','+CLEARING_PAN+','+TRADING_PAN+','+CP_CODE+','+CP_PAN+','+CLIENT_PAN+','+ACCOUNT_TYPE+','+SEGMENT_INDICATOR+','+MTOM+','+CONVERT(VARCHAR(70),VDT_LEDGER)+','+
		CONVERT(VARCHAR(70),EDT_LEDGER)+','+
		CONVERT(VARCHAR(70),PEAK_LEDGER)+','+
		CONVERT(VARCHAR(70),BG_REC_TM)+','+
		CONVERT(VARCHAR(70),FD_REC_TM)+','+
		CONVERT(VARCHAR(70),APPROVED_SEC_CASH_REC_TM)+','+
		CONVERT(VARCHAR(70),APPROVED_SEC_NONCASH_REC_TM)+','+
		CONVERT(VARCHAR(70),NONAPPROVED_SEC_REC_TM)+','+
		CONVERT(VARCHAR(70),CC_APPROVED_COMM_REC_TM)+','+
		CONVERT(VARCHAR(70),OTHER_COLL_REC_TM)+','+
		CONVERT(VARCHAR(70),LIEU_EPI_LEDGER_CLTM)+','+
		CONVERT(VARCHAR(70),POOL_ACCOUNT_CLTM)+','+
		CONVERT(VARCHAR(70),CASH_RET_TM)+','+
		CONVERT(VARCHAR(70),BG_RET_TM)+','+
		CONVERT(VARCHAR(70),FD_RET_TM)+','+
		CONVERT(VARCHAR(70),APPROVED_SEC_CASH_RET_TM)+','+
		CONVERT(VARCHAR(70),APPROVED_SEC_NONCASH_RET_TM)+','+
		CONVERT(VARCHAR(70),NONAPPROVED_SEC_RET_TM)+','+
		CONVERT(VARCHAR(70),CC_APPROVED_COMM_RET_TM)+','+
		CONVERT(VARCHAR(70),OTHER_COLL_RET_TM)+','+
		CONVERT(VARCHAR(70),CASH_WCM)+','+
		CONVERT(VARCHAR(70),BG_WCM)+','+
		CONVERT(VARCHAR(70),FD_WCM)+','+
		CONVERT(VARCHAR(70),APPROVED_SEC_CASH_WCM)+','+
		CONVERT(VARCHAR(70),APPROVED_SEC_NONCASH_WCM)+','+
		CONVERT(VARCHAR(70),NONAPPROVED_SEC_RET_WCM)+','+
		CONVERT(VARCHAR(70),CC_APPROVED_COMM_WCM)+','+
		CONVERT(VARCHAR(70),OTHER_COLL_WCM)+','+
		CONVERT(VARCHAR(70),CASH_RET_WCM)+','+
		CONVERT(VARCHAR(70),BG_RET_CM)+','+
		CONVERT(VARCHAR(70),FD_RET_CM)+','+
		CONVERT(VARCHAR(70),APPROVED_SEC_CASH_RET_CM)+','+
		CONVERT(VARCHAR(70),APPROVED_SEC_NONCASH_RET_CM)+','+
		CONVERT(VARCHAR(70),NONAPPROVED_SEC_RET_RET_CM)+','+
		CONVERT(VARCHAR(70),CC_APPROVED_COMM_RET_CM)+','+
		CONVERT(VARCHAR(70),OTHER_COLL_RET_CM)+','+
		CONVERT(VARCHAR(70),CASH_WNCL)+','+
		CONVERT(VARCHAR(70),BG_WNCL)+','+
		CONVERT(VARCHAR(70),FD_WNCL)+','+
		CONVERT(VARCHAR(70),APPROVED_SEC_CASH_WNCL)+','+
		CONVERT(VARCHAR(70),APPROVED_SEC_NONCASH_WNCL)+','+
		CONVERT(VARCHAR(70),CC_APPROVED_COMM_WNCL)+','+
		CONVERT(VARCHAR(70),MTF_INDICATOR)+','+
		CONVERT(VARCHAR(70),UNCLEAR_RECEIPT)+','+
		CONVERT(VARCHAR(70),GOV_SEC_TBILL_REC_BY_TM)+','+
		CONVERT(VARCHAR(70),GOV_SEC_TBILL_RET_BY_TM)+','+
		CONVERT(VARCHAR(70),GOV_SEC_TBILL_PLACED_BY_CM)+','+
		CONVERT(VARCHAR(70),GOV_SEC_TBILL_RET_BY_CM)+','+
		CONVERT(VARCHAR(70),GOV_SEC_TBILL_PLACED_BY_NCL)+','+
		CONVERT(VARCHAR(70),BG_FUNDED_RET_WITH_CM)+','+
		CONVERT(VARCHAR(70),BG_NONFUNDED_RET_WITH_CM)+','+
		CONVERT(VARCHAR(70),BG_FUNDED_PLACED_WITH_NCL)+','+
		CONVERT(VARCHAR(70),BG_NONFUNDED_PLACED_WITH_NCL)+','+
		CONVERT(VARCHAR(70),SETTLEMENT_AMOUNT)+','+
		CONVERT(VARCHAR(70),UNCLAIM_CL_FUNDS)+','+
		CONVERT(VARCHAR(70),CASH_COLL_MTF_POSITION) 
		FROM MSAJAG.DBO.TBL_RPT_CLIENT_COLL_SEG_NSE_NEW_SEG_NILBAL(NOLOCK) --WHERE SNO > 22398883 AND SNO <= 22398884 AND DATE='11-09-2023'
		WHERE SNO > CONVERT(VARCHAR,@SNO) AND SNO <=  CONVERT(VARCHAR,@TOSNO) AND DATE=REPLACE(CONVERT(CHAR(10), CONVERT(DATETIME, @RUNDATE,103), 103), '/', '-')

		--SET @@QUERY = ' BCP "SELECT REPORTDATA FROM (SELECT * FROM MSAJAG.DBO.LEDGER1_TEXT WHERE SNO = 1 UNION ALL SELECT REPORTDATA,SNO FROM MSAJAG.DBO.LEDGER1_TEXT WHERE SNO > ' + CONVERT(VARCHAR,@SNO) + ' AND SNO <= '+ CONVERT(VARCHAR,@TOSNO) + ')P ORDER BY SNO " QUERYOUT "' + @@FILELOC + '" -T -C -T'', ''NO_OUTPUT'' ' 
		--SET @@QUERY = ' BCP " SELECT * FROM CLS_FILERDATA " QUERYOUT "' + @@FILELOC + '" -c -UTF8 -T -Slocalhost' 
		SET @@QUERY = ' BCP " SELECT FILEDATA FROM MSAJAG.DBO.CLS_FILERDATA(NOLOCK) ORDER BY SRNO " QUERYOUT "' + @@FILELOC + '" -c -UTF8 -T -Slocalhost ' 

	END

	--PRINT @@QUERY 
	EXEC MASTER.DBO.XP_CMDSHELL @@QUERY
	IF @TOSNO >= @RECCNT
	BEGIN
		SET @FLAG = 2
	END
	SET @SNO = @TOSNO
	SET @TOSNO = @TOSNO + 3000000
	SET @FILENUMBER = @FILENUMBER + 1
END
END
ELSE
BEGIN
 SELECT 'NO RECORDS FOUND '
END

--DECLARE @cmd varchar(1000)
--SET @cmd = 'bcp "SELECT * FROM MSAJAG.DBO.ledger1_text WHERE SNO > 0 AND SNO <= 300000 ORDER BY SNO " queryout "D:\BACKOFFICE\NIL_BALANCE\textfile.txt" -c -UTF8 -T -Slocalhost'
--EXEC master..xp_cmdshell @cmd

END

GO
