-- Object: PROCEDURE dbo.PROC_ALL_REPORT_STATUS
-- Server: 10.253.33.91 | DB: MSAJAG
--------------------------------------------------


CREATE PROCEDURE PROC_ALL_REPORT_STATUS (@RUNDATE VARCHAR(11),@REPORT VARCHAR(10))

AS  --- EXEC PROC_ALL_REPORT_STATUS 'SEP 12 2022'

SELECT SRNO,REPORT_DATE,ALLOCATION_FILES_PROCESS,REPORT_STAUS=STATUS 
FROM TBL_ALL_REPORT_STATUS
WHERE REPORT_DATE = @RUNDATE

GO
