-- Object: PROCEDURE dbo.RPT_WEEKLY_CLIENT_CASH_BALANCE_NEW_MCX_BKUP_28JAN2021
-- Server: 10.253.33.91 | DB: MSAJAG
--------------------------------------------------



--EXEC RPT_WEEKLY_CLIENT_CASH_BALANCE_NEW_MCX 'DEC 31 2021', 'DEC 31 2021', 'A144284', 'A144284'


CREATE PROCEDURE [dbo].[RPT_WEEKLY_CLIENT_CASH_BALANCE_NEW_MCX_BKUP_28JAN2021]
(
	--@FROMDATE	VARCHAR(11),
	--@TODATE		VARCHAR(11),
	--@EXCHANGE	VARCHAR(3)  = 'MCX',
	--@FROMPARTY	VARCHAR(20) = 'A000',
	--@TOPARTY	VARCHAR(20) = 'AZZZZZZZZZZ'

	
@FROMDATE   VARCHAR(11),
@TODATE      VARCHAR(11),
@FROMPARTY  VARCHAR(20) = 'a000',
@TOPARTY    VARCHAR(20) = 'azzzzzzzzz',
@EXCHANGE   VARCHAR(3)  = 'MCX',
@flag varchar(10) = ''
)
AS

DECLARE @FROMDT		INT,
		@TODT		INT,
		@RPTDATE	VARCHAR(11),
		@FILENAMEHS	VARCHAR(100),
		@FILENAMENH	VARCHAR(100),
		@PANNO		VARCHAR(20),
		@BATCHNO	INT,
		@FROFYMDATE	VARCHAR(11),
		@FRDATE_NEXT VARCHAR(11)

/* GET THE LIST OF LAST 12 MONTHS TRADED CLIENTS */
CREATE TABLE #CLIENT_LIST 
( 
	CLTCODE VARCHAR(10) 
) 

--INSERT INTO #CLIENT_LIST 
--EXEC GET_SEBI_AUDIT_CLIENT_LIST
--'', 
--@FROMDATE--, 'A'



		EXEC GET_SEBI_AUDIT_CLIENT_LIST 
		'', 
		@FROMDATE,
		1 


/* GET THE LIST OF LAST 12 MONTHS TRADED CLIENTS */

/*GET THE SELECTED SEGMENT CLIENTS */
CREATE TABLE #EXCHANGE_CLINETS
(
	CL_CODE VARCHAR(10)
)


INSERT INTO #EXCHANGE_CLINETS
EXEC GET_EXCH_REG_CLIENTS 'MCX', @FROMPARTY, @TOPARTY
		
SELECT	@TODT = DATEDIFF(DAY, CONVERT(DATETIME, @FROMDATE, 109), CONVERT(DATETIME, @TODATE, 109))

SELECT	@PANNO = ISNULL(LTRIM(RTRIM(PANNO)),'') FROM OWNER (NOLOCK)


SELECT	@BATCHNO = ISNULL(MAX(FLDBATCHNO),0)+1 FROM ASIANFILEBATCHNO  
WHERE	FLDFILENO = 'CE'  
AND LEFT(FLDFILEDATE,11) = LEFT(GETDATE(),11)

IF @BATCHNO = 1  
BEGIN  
	INSERT INTO ASIANFILEBATCHNO VALUES ('CE', @BATCHNO, GETDATE(), GETDATE())  
END  
ELSE  
BEGIN  
	UPDATE ASIANFILEBATCHNO SET FLDBATCHNO = @BATCHNO WHERE FLDFILENO = 'CE' AND LEFT(FLDFILEDATE,11) = LEFT(GETDATE(),11)
END  

SET	@FILENAMEHS = @PANNO + '_CE_' + REPLACE(CONVERT(VARCHAR,CONVERT(DATETIME,@TODATE,109),103),'/','') + '_' + RIGHT('00'+CONVERT(VARCHAR,@BATCHNO),2) + '.CSV'



SELECT TRADING_PAN, REPORT_DATE,UCC=PARENTCODE,CLIENT_PAN,CLIENT_NAME,SEGMENT_INDICATOR = CASE WHEN EXCHANGE = 'MTF' THEN 'MTF' ELSE 'NON MTF' END, EXCHANGE, SEGMENT,
VDT_BAL = ROUND(VDT_BAL, 2), EDT_BAL = ROUND(EDT_BAL, 2),PEAK_FINANCIAL_LEDGER = ROUND(PEAK_FINANCIAL_LEDGER, 2), BG, FDR, GOV_IND_SEC, GILT_FUNDS, EPI_LEDGER,POOL_ACCOUNT,CHQ_DEPOSITS,CHQ_ISSUE,
COMM_VALUE,LAST_SETT_DATE,OPEN_BILL1, OPEN_BILL2, MARGIN_REQ
INTO #REPORT_DATA
FROM ACCOUNT..CLIENT_CASH_DETAILS C, ACCOUNT..CLIENT_CASH_LED_BALANCES L
WHERE C.SNO = L.SNO
AND REPORT_DATE BETWEEN @FROMDATE AND @TODATE + ' 23:59'
AND UCC BETWEEN @FROMPARTY AND @TOPARTY 
--and Exchange='MCX' and Segment='Futures'
AND EXISTS(SELECT CL_CODE FROM #EXCHANGE_CLINETS WHERE CL_CODE = UCC)


DECLARE
	@TRADING_PAN VARCHAR(10)

SELECT TOP 1 @TRADING_PAN = TRADING_PAN FROM #REPORT_DATA



DELETE R FROM #REPORT_DATA R WHERE VDT_BAL = 0 AND EDT_BAL = 0 AND PEAK_FINANCIAL_LEDGER = 0 AND BG = 0 AND FDR = 0 AND GOV_IND_SEC = 0AND GILT_FUNDS = 0
AND EPI_LEDGER  = 0 AND POOL_ACCOUNT = 0 AND CHQ_DEPOSITS = 0 AND CHQ_ISSUE = 0 AND COMM_VALUE = 0

CREATE TABLE #CAL_DATES
(
	CAL_DATES DATETIME
)

INSERT INTO #CAL_DATES
EXEC ACCOUNT..GET_CAL_DATES @FROMDATE, @TODATE

INSERT INTO #REPORT_DATA
SELECT @TRADING_PAN, CAL_DATES, CL_CODE, PAN_GIR_NO, LONG_NAME, 'NON MTF', 'NSE', 'CAPITAL',  VDT_BAL = 0, EDT_BAL = 0,PEAK_FINANCIAL_LEDGER = 0, BG = 0, FDR = 0, GOV_IND_SEC = 0, GILT_FUNDS = 0, EPI_LEDGER = 0,POOL_ACCOUNT = 0,CHQ_DEPOSITS = 0,CHQ_ISSUE = 0,COMM_VALUE = 0,LAST_SETT_DATE = 'ND',OPEN_BILL1=0, OPEN_BILL2=0, MARGIN_REQ = 0
FROM CLIENT_DETAILS C, #CLIENT_LIST CL, #CAL_DATES CD
WHERE CL_CODE = CLTCODE
AND NOT EXISTS(SELECT UCC FROM #REPORT_DATA WHERE UCC = CLTCODE AND REPORT_DATE = CAL_DATES)
AND CL_CODE BETWEEN @FROMPARTY AND @TOPARTY
AND EXISTS(SELECT CL_CODE FROM #EXCHANGE_CLINETS WHERE CL_CODE = CL_CODE)


/*
CREATE TABLE #LAST_SETTLE
	(
		CLTCODE VARCHAR(10),
		LAST_SETT_DATE VARCHAR(20),
		CHK_DATE DATETIME
	)

	 

	  EXEC ACCOUNT.DBO.GET_LAST_SETTTLE_DATE
      @TODATE,
      'BSE', 'A'

	 
	  UPDATE C SET LAST_SETT_DATE = CASE WHEN CHK_DATE <= CONVERT(DATETIME,REPORT_DATE,105) THEN L.LAST_SETT_DATE ELSE C.LAST_SETT_DATE END 
	  FROM #REPORT_DATA C,  #LAST_SETTLE L  WHERE	UCC = CLTCODE

	  TRUNCATE TABLE #LAST_SETTLE

	  EXEC ACCOUNT.DBO.GET_LAST_SETTTLE_DATE
      @FROMDATE,
      'BSE', 'A'


	  UPDATE C SET LAST_SETT_DATE = CASE WHEN CHK_DATE <= CONVERT(DATETIME,REPORT_DATE,105) THEN L.LAST_SETT_DATE ELSE C.LAST_SETT_DATE END 
	  FROM #REPORT_DATA C,  #LAST_SETTLE L  WHERE	UCC = CLTCODE AND C.LAST_SETT_DATE IN('NA', 'ND', '')

	  */


	  		UPDATE	D
		SET		LAST_SETT_DATE = --CONVERT(VARCHAR,SETT_DATE, 105)
		case when SETT_DATE <= CONVERT(VARCHAR(11), CONVERT(datetime,REPORT_DATE, 105), 109) + ' 23:59' then CONVERT(VARCHAR,SETT_DATE, 105) else 'NA' end
		FROM	#REPORT_DATA D,
				(
					SELECT  party_code, SETT_DATE = max(SCCS_SettDate_Last) from Sebi_Payout--, #COLL D
					WHERE SCCS_SettDate_Last >= @FROMDATE 
					--and SCCS_SettDate_Last <= @TODATE 
					GROUP BY party_code
				) D1
		WHERE	UCC = party_code

		UPDATE	D
		SET		LAST_SETT_DATE = case when LAST_SETT_DATE = 'NA' then CONVERT(VARCHAR,SETT_DATE, 105) else LAST_SETT_DATE end
		FROM	#REPORT_DATA D,
				(
					SELECT  party_code, SETT_DATE = max(SCCS_SettDate_Last) from Sebi_Payout--, #COLL D
					WHERE SCCS_SettDate_Last < @FROMDATE
					GROUP BY party_code
				) D1
		WHERE	ucc = party_code

	UPDATE #REPORT_DATA SET CLIENT_PAN='NNNNN1111N' WHERE CLIENT_PAN LIKE '%[^0-9A-Za-z]%' OR LEN(CLIENT_PAN) <> '10' OR RIGHT(CLIENT_PAN, 1) LIKE '%[^A-Za-z]%'

DELETE FROM #REPORT_DATA WHERE UCC LIKE '%[^0-9A-Za-z]%'



CREATE TABLE #NET_MARGIN_BALANCE
(
	UCC VARCHAR(10),
	REPORT_DATE DATETIME,
	TOTAL_MARGIN MONEY
)

INSERT INTO #NET_MARGIN_BALANCE
SELECT UCC, REPORT_DATE, TOTAL_MARGIN = CASE WHEN SUM(VDT_BAL - OPEN_BILL1 - OPEN_BILL2 - CHQ_DEPOSITS + CHQ_ISSUE) > SUM(MARGIN_REQ) AND SUM(VDT_BAL - OPEN_BILL1 - OPEN_BILL2 - CHQ_DEPOSITS + CHQ_ISSUE) > 0 THEN SUM(MARGIN_REQ) ELSE CASE WHEN SUM(VDT_BAL - OPEN_BILL1 - OPEN_BILL2 - CHQ_DEPOSITS + CHQ_ISSUE) > 0 THEN SUM(VDT_BAL - OPEN_BILL1 - OPEN_BILL2 - CHQ_DEPOSITS + CHQ_ISSUE) ELSE 0 END END
FROM #REPORT_DATA
GROUP BY UCC, REPORT_DATE


CREATE TABLE #FINAL_DATA
(
	SNO INT IDENTITY(1, 1),
	FILE_NAMEING VARCHAR(200),
	REPORTDATE VARCHAR(10),
	UCC VARCHAR(10),
	REPORT_DATA VARCHAR(8000)
)


INSERT INTO #FINAL_DATA
SELECT @FILENAMEHS, CONVERT(VARCHAR(10), CONVERT(DATETIME, @FROMDATE, 109), 103), UCC = '00000', 'TRADING MEMBER PAN, DATE,UNIQUE CLIENT CODE ,CLIENT PAN ,CLIENT NAME,MTF/ NON MTF  INDICATOR, FINANCIAL LEDGER BALANCE-A , FINANCIAL LEDGER BALANCE (CLEAR)-B ,PEAK FINANCIAL LEDGER BALANCE (CLEAR)-C , FINANCIAL LEDGER BALANCE-MCX,FINANCIAL LEDGER BALANCE-NCDEX, FINANCIAL LEDGER BALANCE-ICEX, BANK GUARANTEE (BG) , FIXED DEPOSIT RECEIPT (FDR), GOVERNMENT OF INDIA SECURITIES , GILT FUNDS,CREDIT ENTRY IN LEDGER IN LIEU OF EPI,POOL ACCOUNT,UNCLEARED CHEQUES,VALUE OF COMMODITIES ,LAST SETTLEMENT DATE,ES INFORMATION TYPE,VALUE'
--UNION ALL
INSERT INTO #FINAL_DATA
SELECT @FILENAMEHS, CONVERT(VARCHAR(10), REPORT_DATE, 103), UCC, TRADING_PAN + ',' + CONVERT(VARCHAR(10), REPORT_DATE, 103) + ',' + UCC + ',' + CLIENT_PAN + ',' + CLIENT_NAME + ',' + SEGMENT_INDICATOR
+ ','
+ CONVERT(VARCHAR, SUM(VDT_BAL)) + ',' + CONVERT(VARCHAR, SUM(EDT_BAL)) + ',' + CONVERT(VARCHAR, SUM(PEAK_FINANCIAL_LEDGER)) + ','
+ CONVERT(VARCHAR, SUM(CASE WHEN EXCHANGE = 'MCX' THEN VDT_BAL ELSE 0 END)) + ','
+ CONVERT(VARCHAR, SUM(CASE WHEN EXCHANGE = 'NCX' THEN VDT_BAL ELSE 0 END)) + ','
+ CONVERT(VARCHAR, SUM(CASE WHEN EXCHANGE = 'ICX' THEN VDT_BAL ELSE 0 END)) + ','
+ CONVERT(VARCHAR, SUM(BG)) + ',' + CONVERT(VARCHAR, SUM(FDR)) + ',' + CONVERT(VARCHAR, SUM(GOV_IND_SEC)) + ',' + CONVERT(VARCHAR, SUM(GILT_FUNDS)) + ','
+ CONVERT(VARCHAR, SUM(EPI_LEDGER)) + ',' + CONVERT(VARCHAR, SUM(POOL_ACCOUNT)) + ',' + CONVERT(VARCHAR, SUM(CHQ_DEPOSITS))
+ ',' + CONVERT(VARCHAR, SUM(COMM_VALUE)) + ',' + CONVERT(VARCHAR, MAX(LAST_SETT_DATE)) + ',NA, NA'
FROM #REPORT_DATA
GROUP BY TRADING_PAN, CONVERT(VARCHAR(10), REPORT_DATE, 103), UCC, CLIENT_PAN, CLIENT_NAME, SEGMENT_INDICATOR
ORDER BY CONVERT(VARCHAR(10), REPORT_DATE, 103), UCC

INSERT INTO #FINAL_DATA
SELECT @FILENAMEHS, CONVERT(VARCHAR(10), REPORT_DATE, 103), UCC = 'ZZZZ',  TRADING_PAN + ',' + CONVERT(VARCHAR(10), REPORT_DATE, 103) + ',NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,TOTAL CREDIT BALANCE OF ALL CLIENTS,' + CONVERT(VARCHAR, SUM(CASE WHEN VDT_BAL > 0 THEN VDT_BAL ELSE 0 END)) FROM #REPORT_DATA GROUP BY TRADING_PAN,  CONVERT(VARCHAR(10), REPORT_DATE, 103) ORDER BY CONVERT(VARCHAR(10), REPORT_DATE, 103)

INSERT INTO #FINAL_DATA
SELECT @FILENAMEHS, CONVERT(VARCHAR(10), REPORT_DATE, 103), UCC = 'ZZZZ',  TRADING_PAN + ',' + CONVERT(VARCHAR(10), REPORT_DATE, 103) + ',NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,TOTAL DEBIT BALANCE OF ALL CLIENTS ,' + CONVERT(VARCHAR, ABS(SUM(CASE WHEN VDT_BAL < 0 THEN VDT_BAL ELSE 0 END))) FROM #REPORT_DATA  GROUP BY TRADING_PAN,  CONVERT(VARCHAR(10), REPORT_DATE, 103) ORDER BY CONVERT(VARCHAR(10), REPORT_DATE, 103)

INSERT INTO #FINAL_DATA
SELECT @FILENAMEHS, CONVERT(VARCHAR(10), REPORT_DATE, 103), UCC = 'ZZZZ',  TRADING_PAN + ',' + CONVERT(VARCHAR(10), REPORT_DATE, 103) + ',NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,VALUE OF NON FUNDED PORTION OF THE BANK GUARANTEE, 0' FROM #REPORT_DATA  GROUP BY TRADING_PAN,  CONVERT(VARCHAR(10), REPORT_DATE, 103) ORDER BY CONVERT(VARCHAR(10), REPORT_DATE, 103)

INSERT INTO #FINAL_DATA
SELECT @FILENAMEHS, CONVERT(VARCHAR(10), REPORT_DATE, 103), UCC = 'ZZZZ',  @TRADING_PAN + ',' + CONVERT(VARCHAR(10), REPORT_DATE, 103) + ',NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,TOTAL MARGIN UTILIZED FOR POSITIONS OF CREDIT BALANCE CLIENTS, ' + CONVERT(VARCHAR, SUM(TOTAL_MARGIN)) FROM #NET_MARGIN_BALANCE GROUP BY  CONVERT(VARCHAR(10), REPORT_DATE, 103) ORDER BY CONVERT(VARCHAR(10), REPORT_DATE, 103)

INSERT INTO #FINAL_DATA
SELECT @FILENAMEHS, CONVERT(VARCHAR(10), REPORT_DATE, 103), UCC = 'ZZZZ',  TRADING_PAN + ',' + CONVERT(VARCHAR(10), REPORT_DATE, 103) + ',NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,FREE/UNBLOCKED COLLATERAL DEPOSITED WITH CLEARING MEMBER, 0' FROM #REPORT_DATA  GROUP BY TRADING_PAN,  CONVERT(VARCHAR(10), REPORT_DATE, 103) ORDER BY CONVERT(VARCHAR(10), REPORT_DATE, 103)


SELECT @FILENAMEHS,REPORT_DATA   FROM #FINAL_DATA
ORDER BY REPORTDATE, SNO

GO
