-- Object: PROCEDURE dbo.RPT_GST_BREAKUP_SUMMARY
-- Server: 10.253.33.91 | DB: MSAJAG
--------------------------------------------------



CREATE PROC RPT_GST_BREAKUP_SUMMARY 
(  
 @FROM_DATE DATETIME,  
 @TO_DATE DATETIME,  
 @FROMSTATE VARCHAR(2)='',  
 @TOSTATE VARCHAR(2)='ZZ',  
 @FILLER1 VARCHAR(2)='',  
 @FILLER2 VARCHAR(2)=''    
)  
  
AS  

SET @TOSTATE = (CASE WHEN @TOSTATE = '' THEN 'ZZ' ELSE @TOSTATE END) 
--EXEC RPT_GST_BREAKUP_SUMMARY 'JUN 19 2017', 'JUN 19 2017', '', 'ZZZ', '', ''
SET @TO_DATE = LEFT(@TO_DATE,11) + ' 23:59:59'
EXEC RPT_GST_BREAKUP @FROM_DATE, @TO_DATE, @FROMSTATE, @TOSTATE, 'S'

GO
