-- Object: PROCEDURE dbo.Proc_NewBasicReport_SB
-- Server: 10.253.33.91 | DB: MSAJAG
--------------------------------------------------





/****** OBJECT:  STORED PROCEDURE DBO.PROC_NEWBASICREPORT    SCRIPT DATE: 5/12/2009 4:00:26 PM ******/
/****** OBJECT:  STORED PROCEDURE DBO.PROC_NEWBASICREPORT    SCRIPT DATE: 3/13/2009 7:04:11 PM ******/
/****** OBJECT:  STORED PROCEDURE DBO.PROC_NEWBASICREPORT    SCRIPT DATE: 06/07/2007 6:48:58 PM ******/  
/****** OBJECT:  STORED PROCEDURE DBO.PROC_NEWBASICREPORT    SCRIPT DATE: 01/15/2005 1:12:51 PM ******/  
/****** OBJECT:  STORED PROCEDURE DBO.PROC_NEWBASICREPORT    SCRIPT DATE: 12/06/2004 10:42:58 PM ******/  
/****** OBJECT:  STORED PROCEDURE DBO.PROC_NEWBASICREPORT    SCRIPT DATE: 12/06/2004 8:29:47 PM ******/  
  
CREATE PROCEDURE [dbo].[Proc_NewBasicReport_SB] (   
@SETT_NO VARCHAR(10),    ---1  SETTLEMENT NO(FROM)  
@TOSETT_NO VARCHAR(10),   ---2  SETTLEMENT NO (TO)  
@SETT_TYPE VARCHAR(3),   ---3  SETTLEMENT TYPE   
@SAUDA_DATE VARCHAR(11),  ---4 SAUDA_DATE (FROM)  
@TODATE VARCHAR(11),   ---5 SAUDA_DATE (TO)  
@FROMSCRIP VARCHAR(10),   ---6 FROM SCRIP_CD (FROM)  
@TOSCRIP VARCHAR(10),   ---7 TO SCRIP_CD (TO)  
@FROM VARCHAR(20),     ---8  FROM CONSOL  
@TO VARCHAR (20),     ---9  TO CONSOL  
@CONSOL VARCHAR(10),   ---10  CONSOL INDICATES THAT WHETHER IS "PARTY_CODE","TRADER","SUB BROKER","BRANCH"  
@DETAIL VARCHAR(3),    ---11  THIS IS OTHER DETAILS IN QUERY "B" = "BILL","C" = "CONFIRMATION","P" = "POSITION","BR" = "BROKERAGE","S" = "SAUDA SUMMARY"  
@LEVEL  SMALLINT,            ---12 WILL BE USED TO SELECT  LEVEL OF CONSOLIDATION DEFAULT 0  
@GROUPF VARCHAR(500),   ---13 (ANY NECESSARY GROUPING) THIS CAN BE DEFINED ON THE FLY BY DEVELOPER  
@ORDERF VARCHAR(500),   ---14 (ANY NECESSARY ORDER BY) THIS CAN DE DEFINED ON THE FLY BY DEVELOPER   
@USE1 VARCHAR(10),           ---15 TO BE USED LATER  FOR OTHER PURPOSES  
@STATUSID VARCHAR(15),  
@STATUSNAME VARCHAR(25),
@SERIES VARCHAR(5) ='' 
)  
  
AS
 SELECT PARTY_CODE, LONG_NAME=PARTY_NAME,PTRADEDQTY = SUM(PQTYTRD + PQTYDEL) ,PTRADEDAMT = SUM(PAMTTRD + PAMTDEL) ,
 STRADEDQTY = SUM(SQTYTRD + SQTYDEL), STRADEDAMT = SUM((CASE WHEN SQTYTRD = 0 AND
  SAMTTRD <> 0 THEN -SAMTTRD ELSE SAMTTRD END) + (CASE WHEN SQTYDEL = 0 AND SAMTDEL <> 0 
  THEN -SAMTDEL ELSE SAMTDEL END)), BUYBROKERAGE = SUM(PBROKTRD) , SELBROKERAGE= SUM(SBROKTRD) , 
  BUYDELIVERYCHRG = SUM(PBROKDEL), SELLDELIVERYCHRG = SUM(SBROKDEL),
   CLIENTTYPE, BILLPAMT = SUM(PAMT) , BILLSAMT = SUM(SAMT) , 
   PMARKETRATE = ( SUM(PRATE) / CASE WHEN SUM(PQTYTRD + PQTYDEL) > 0 THEN SUM(PQTYTRD + PQTYDEL) ELSE 1 END) , 
   SMARKETRATE = ( SUM(SRATE) / (CASE WHEN SUM(SQTYTRD + SQTYDEL) > 0 THEN SUM(SQTYTRD + SQTYDEL) ELSE 1 END ) ),  
   PNETRATE = ( SUM(PAMTTRD + PAMTDEL) / CASE WHEN SUM(PQTYTRD + PQTYDEL) > 0 THEN SUM(PQTYTRD + PQTYDEL) ELSE 1 END) , 
   SNETRATE = ( SUM((CASE WHEN SQTYTRD =0 AND SAMTTRD<>0 THEN -SAMTTRD ELSE SAMTTRD END) + (CASE WHEN SQTYDEL=0 AND SAMTDEL<>0 THEN -SAMTDEL ELSE SAMTDEL END)) / (CASE WHEN SUM(SQTYTRD + SQTYDEL) > 0 THEN SUM(SQTYTRD + SQTYDEL) ELSE 1 END ) ), 
   TRDAMT= SUM(TRDAMT) ,DELAMT=SUM(DELAMT), SERINEX=SUM(SERINEX),SERVICE_TAX= SUM(SERVICE_TAX) ,
   EXSERVICE_TAX= SUM(EXSERVICE_TAX),TURN_TAX=SUM(TURN_TAX),SEBI_TAX=SUM(SEBI_TAX),
   INS_CHRG=SUM(INS_CHRG),BROKER_CHRG=SUM(BROKER_CHRG),OTHER_CHRG=SUM(OTHER_CHRG), 
   MEMBERTYPE, COMPANYNAME,PNL = SUM(SAMTTRD-PAMTTRD) 
  FROM CMBILLVALAN S 
 WHERE S.SAUDA_DATE BETWEEN @SAUDA_DATE AND @TODATE AND S.SCRIP_CD BETWEEN @FROMSCRIP AND @TO
 /*AND S.SETT_NO BETWEEN '2017027' AND '2017243' */  AND S.PARTY_CODE BETWEEN @FROM AND 'z'  
  AND S.SUB_BROKER BETWEEN @STATUSNAME AND @STATUSNAME  AND  S.SETT_TYPE BETWEEN ''  AND 'Z' AND  TRADETYPE NOT IN ( 'IR' )  
 GROUP BY S.PARTY_CODE, PARTY_NAME,CLIENTTYPE ,MEMBERTYPE, COMPANYNAME
 ORDER   BY PARTY_CODE

GO
