-- Object: PROCEDURE dbo.RMS_NSE_SALE
-- Server: 10.253.33.91 | DB: MSAJAG
--------------------------------------------------

CREATE PROC RMS_NSE_SALE    
(      
 @TRADEDATE VARCHAR(11)      
)      
AS      
-- EXEC RMS_NSE_SALE 'FEB 26 2013'      
    
DECLARE @SNO INT,    
  @RECCNT INT,    
  @BATCHNO INT    
      
SELECT FILENAME=CONVERT(VARCHAR(50),''),    
LNO=0,    
FILLER1='1',    
FILLER2='2',    
SCRIP_CD=(CASE WHEN LEN(SCRIP_CD) <= 10 THEN LEFT(SCRIP_CD + SPACE(10),10) ELSE SCRIP_CD END),    
SERIES,    
FILLER3='1',    
FILLER4 = '           ',    
FILLER5 = '  ',    
FILLER6 = '         ',    
CL_RATE = CONVERT(NUMERIC(18,2),CL_RATE - CL_RATE*2.00/100.00),    
FILLER7 = '         ',    
QTY = TOSELLQTY,    
DIS_QTY = CEILING(CASE WHEN TOSELLQTY > 15 THEN TOSELLQTY / 10 ELSE TOSELLQTY END),    
MEMBERCODE,    
SELL_BUY = '2',    
PARTY_CODE=(CASE WHEN LEN(LTRIM(RTRIM(PARTY_CODE))) <= 10 THEN LEFT(LTRIM(RTRIM(PARTY_CODE)) + SPACE(10),10) ELSE LTRIM(RTRIM(PARTY_CODE)) END),    
FILLER8='                         ',    
FILLER9='                ',    
FILLER10='          '    
INTO #RMS      
FROM TBL_RMS_SALE, OWNER      
WHERE PROCESS_DATE = @TRADEDATE AND EXCHANGE = 'NSE'      
AND PARTY_CODE IN (SELECT PCODE FROM V_USERLIST    
         WHERE CATEGORY IN (2,4))  
           
UPDATE #RMS SET CL_RATE = ((FLOOR(( CL_RATE * POWER(10,2)+ 5 + -2.5)/(5 + 0 )) * (5 + 0))/POWER(10,2))  
WHERE CL_RATE > 10
    
ALTER TABLE #RMS    
ADD SNO INT IDENTITY(1,1)    
    
SELECT @SNO = MAX(SNO) FROM #RMS    
    
SET @RECCNT = 0    
    
SELECT @BATCHNO = ISNULL(MAX(FLDBATCHNO),0) FROM ASIANFILEBATCHNO    
WHERE FLDFILENO = @TRADEDATE     
AND FLDFILENO = 999    
    
WHILE @RECCNT <= @SNO    
BEGIN     
 SET @BATCHNO = @BATCHNO + 1     
 UPDATE #RMS SET FILENAME = 'OUTPUT_NSE_T6T7'     
              + REPLACE(CONVERT(VARCHAR,CONVERT(DATETIME,@TRADEDATE),103),'/','')    
              + convert(varchar,@BATCHNO) + '.csv',    
              LNO = (CASE WHEN SNO <= 900 THEN SNO ELSE SNO-@RECCNT END)    
 WHERE SNO > @RECCNT AND SNO <= @RECCNT + 900    
     
 SET @RECCNT = @RECCNT + 900    
 INSERT INTO ASIANFILEBATCHNO VALUES (999, @BATCHNO, @TRADEDATE, GETDATE())    
END    
    
SELECT FILENAME,LNO,FILLER1,FILLER2,SCRIP_CD,SERIES,FILLER3,FILLER4,FILLER5,    
    FILLER6,CL_RATE,FILLER7,QTY,DIS_QTY,MEMBERCODE,SELL_BUY,PARTY_CODE,    
    FILLER8,FILLER9,FILLER10     
FROM #RMS    
ORDER BY 1, PARTY_CODE    
    
DROP TABLE #RMS

GO
