-- Object: PROCEDURE dbo.PROC_COMBINE_MARGIN_TEST
-- Server: 10.253.33.91 | DB: MSAJAG
--------------------------------------------------


CREATE PROCEDURE [dbo].[PROC_COMBINE_MARGIN_TEST]     
(   
 @MARGINDATE VARCHAR(11),    
 @COMBINEFLAG INT = 1,    
 @FORREPORTING VARCHAR(1)='Y',    
 @CHECKFLAG INT = 0 ,
 @PEAK CHAR(1)='0'
)        
AS

    
SET NOCOUNT ON     

DECLARE @PREVDATE VARCHAR(11) ,
@TDAYNEXT	VARCHAR(11)
DECLARE @EPNDATE VARCHAR(11) 
  
DECLARE @EXCHANGE_NEW VARCHAR(3)    
    
DECLARE @SEGMENT_NEW VARCHAR(10)    
    
DECLARE @SHAREDB VARCHAR(35)    
    
DECLARE @SHARESERVER VARCHAR(35)    
    
DECLARE @ACCOUNTDB VARCHAR(35)    
    
DECLARE @ACCOUNTSERVER VARCHAR(35)    
    
    
    
DECLARE @EXCHANGEWISE_CURSOR CURSOR     
    
DECLARE @STRSQL VARCHAR(8000)     
    
DECLARE @MARGINDATENEW VARCHAR(11)    
    
DECLARE @MARGINDATECURSOR CURSOR    
    
DECLARE @MRGCUR CURSOR    
    
    
    
DECLARE @CNT INT    
    
DECLARE @DAY INT    
    
DECLARE @PARTY_CODE VARCHAR(10)    
    
DECLARE @SHRT_AMT NUMERIC(18,4)    
    
DECLARE @MARG_AMT NUMERIC(18,4)    
    
    
    
DECLARE @EXCHANGE_PRIORITY INT    
    
  
DECLARE   
@VARKEY  VARCHAR(8)   

UPDATE TBL_COMBINE_REPORTING_TDAY     
SET     
TDAY_MARGIN_SHORT = TDAY_CASH + TDAY_NONCASH
WHERE MARGINDATE = @MARGINDATE     
  
SELECT @VARKEY = DETAILKEY FROM VARCONTROL   
WHERE RECDATE >= @MARGINDATE AND RECDATE <= @MARGINDATE + ' 23:59'  
    
SELECT SETT_NO,SETT_TYPE,PARTY_CODE,SCRIP_CD,SERIES,QTY=NETQTY,PAYQTY=0,  
MTOM,NETAMT,  
ADNL_MARGIN=ADNL_MRG,  
ADNL_PER=CONVERT(NUMERIC(18,4),0),  
LEDAMT = CONVERT(NUMERIC(18,4),0)  
INTO #PAYIN  
FROM TBL_MG02 D   
WHERE D.MARGIN_DATE = @MARGINDATE  
AND Party_Code IN (SELECT PARTY_CODE FROM TBL_COMBINE_REPORTING_TDAY)

--AND MTOM <> 0   
/*  
UPDATE #PAYIN SET ADNL_PER = INDEXVAR  
FROM VARDETAIL D WHERE DETAILKEY =@VARKEY   
AND D.SCRIP_CD = #PAYIN.SCRIP_CD AND D.SERIES = #PAYIN.SERIES  
  
UPDATE #PAYIN SET ADNL_MARGIN = ABS(NETAMT*ADNL_PER) / 100  
--WHERE QTY < 0   
*/  
  
SELECT DISTINCT SETT_NO, SETT_TYPE INTO #SETT FROM #PAYIN   
  
UPDATE #PAYIN SET PAYQTY = D.QTY   
FROM (SELECT D.SETT_NO, D.SETT_TYPE, PARTY_CODE,SCRIP_CD,D.SERIES,QTY = SUM(QTY)  
   FROM ANGELDEMAT.MSAJAG.DBO.DELTRANS_REPORT D, #SETT S  
   WHERE D.SETT_NO = S.SETT_NO   
   AND D.SETT_TYPE = S.SETT_TYPE  
   AND FILLER2 = 1 AND DRCR = 'C' AND SHARETYPE <> 'AUCTION'  
   AND Party_Code IN (SELECT PARTY_CODE FROM TBL_COMBINE_REPORTING_TDAY)
   GROUP BY  D.SETT_NO, D.SETT_TYPE, PARTY_CODE,SCRIP_CD,D.SERIES ) D  
WHERE D.SETT_NO = #PAYIN.SETT_NO   
   AND D.SETT_TYPE = #PAYIN.SETT_TYPE  
   AND D.PARTY_CODE = #PAYIN.PARTY_CODE   
   AND D.SCRIP_CD = #PAYIN.SCRIP_CD   
   AND D.SERIES = #PAYIN.SERIES   
   AND #PAYIN.QTY < 0   

IF CONVERT(DATETIME,@MARGINDATE) <= CONVERT(DATETIME,'MAR  1 2023')
BEGIN
	IF (SELECT ISNULL(SUM(T2DAY_MARGIN+T2DAY_MTM),0) FROM TBL_COMBINE_REPORTING_TDAY   
		WHERE MARGINDATE = @MARGINDATE) > 0   
	BEGIN    
	 UPDATE #PAYIN SET LEDAMT = T.T2DAY_CASH  
	 FROM TBL_COMBINE_REPORTING_TDAY T  
	 WHERE MARGINDATE =@MARGINDATE   
	 AND #PAYIN.PARTY_CODE = T.PARTY_CODE   
	END  
	ELSE  
	BEGIN    
	 UPDATE #PAYIN SET LEDAMT = -1  
	 FROM TBL_COMBINE_REPORTING_TDAY T  
	 WHERE MARGINDATE =@MARGINDATE   
	 AND #PAYIN.PARTY_CODE = T.PARTY_CODE   
	END  
END
ELSE
BEGIN
	IF (SELECT ISNULL(SUM(T1DAY_MARGIN+T1DAY_MTM),0) FROM TBL_COMBINE_REPORTING_TDAY   
		WHERE MARGINDATE = @MARGINDATE) > 0   
	BEGIN    
	 UPDATE #PAYIN SET LEDAMT = T.T1DAY_CASH  
	 FROM TBL_COMBINE_REPORTING_TDAY T  
	 WHERE MARGINDATE =@MARGINDATE   
	 AND #PAYIN.PARTY_CODE = T.PARTY_CODE   
	END  
	ELSE  
	BEGIN    
	 UPDATE #PAYIN SET LEDAMT = -1  
	 FROM TBL_COMBINE_REPORTING_TDAY T  
	 WHERE MARGINDATE =@MARGINDATE   
	 AND #PAYIN.PARTY_CODE = T.PARTY_CODE   
	END  
END

UPDATE #PAYIN SET PAYQTY = ABS(QTY)  
WHERE QTY < 0 AND PAYQTY > ABS(QTY)   
   
SELECT PARTY_CODE, COLLECT=SUM(PRADNYA.DBO.FNMIN(MTOM,COLLECT))+CONVERT(NUMERIC(18,2),SUM(ADNL_MARGIN))   
INTO #MTMCOLLECT  
FROM (  
SELECT SETT_NO,SETT_TYPE,PARTY_CODE,MTOM=(CASE WHEN SUM(MTOM) < 0 THEN ABS(SUM(MTOM)) ELSE 0 END),  
COLLECT=SUM(CASE WHEN QTY < 0 AND MTOM < 0 THEN ABS(PAYQTY*(MTOM/ABS(QTY)))   
        WHEN QTY > 0 AND MTOM < 0 AND LEDAMT >= 0 THEN ABS(MTOM)
   ELSE 0 END),  
ADNL_MARGIN = SUM(CASE WHEN QTY < 0 AND ADNL_MARGIN > 0 THEN ABS(PAYQTY*(ADNL_MARGIN/ABS(QTY)))   
        WHEN QTY > 0 AND ADNL_MARGIN > 0 AND LEDAMT >= 0     
        THEN ABS(ADNL_MARGIN)   
      ELSE 0 END)  
FROM #PAYIN    
GROUP BY SETT_NO,SETT_TYPE,PARTY_CODE ) A  
GROUP BY PARTY_CODE  
  
CREATE INDEX ix_Party on #MTMCOLLECT(Party_Code)  
  

SELECT * FROM TBL_COMBINE_REPORTING_TDAY WHERE MARGINDATE='OCT  4 2022'
AND PARTY_CODE='A1009543'
SELECT * FROM TBL_COMBINE_REPORTING_TDAY_DETAIL WHERE MARGINDATE='OCT  4 2022'
AND PARTY_CODE='A1009543'

SELECT * FROM #PAYIN

UPDATE T SET TDAY_MTM = TDAY_MTM - COLLECT  
FROM TBL_COMBINE_REPORTING_TDAY T (NOLOCK),#MTMCOLLECT M (NOLOCK)  
WHERE MARGINDATE  = @MARGINDATE   AND T.PARTY_CODE = M.PARTY_CODE   
  
UPDATE T SET TDAY_MTM = TDAY_MTM - COLLECT  
FROM TBL_COMBINE_REPORTING_TDAY_DETAIL T (NOLOCK), #MTMCOLLECT M (NOLOCK)  
WHERE MARGINDATE  = @MARGINDATE   AND T.PARTY_CODE = M.PARTY_CODE   
AND EXCHANGE = 'NSE' AND SEGMENT = 'CAPITAL'  
  
SET @DAY = 0  
  
IF (SELECT ISNULL(SUM(T1DAY_MARGIN+T1DAY_MTM),0) FROM  TBL_COMBINE_REPORTING_TDAY WHERE MARGINDATE = @MARGINDATE) > 0     
BEGIN       
 SET @DAY = 1    
   
   
    DECLARE @FODATE DATETIME  
 SELECT @FODATE=MAX(MDATE) FROM ANGELFO.NSEFO.DBO.FOMARGINNEW WITH(NOLOCK)  
 WHERE MDATE <= @MARGINDATE   
  
 SELECT * INTO #FOMARGINNEW_DATA_FO  
    FROM ANGELFO.NSEFO.DBO.FOMARGINNEW M WITH(NOLOCK)  
 WHERE  MDATE = @FODATE  
   
  UPDATE T SET TDAY_MTM = TDAY_MTM - ISNULL(DEL_MARGIN,0)   
 FROM #FOMARGINNEW_DATA_FO M With(Nolock),TBL_COMBINE_REPORTING_TDAY T (NOLOCK)  
 WHERE MDATE = @FODATE  
 AND T.PARTY_CODE = M.PARTY_CODE   
 AND T.MARGINDATE  = @MARGINDATE    
  
 DECLARE @CMDATE DATETIME  
 SELECT @CMDATE=MAX(MDATE) FROM ANGELCOMMODITY.MCDX.DBO.FOMARGINNEW_DATA WITH(NOLOCK)  
 WHERE MDATE <= @MARGINDATE  
  
 SELECT * INTO #FOMARGINNEW_DATA_COMM   
    FROM ANGELCOMMODITY.MCDX.DBO.FOMARGINNEW_DATA M WITH(NOLOCK)  
 WHERE  MDATE = @CMDATE  
        
  UPDATE T SET TDAY_MTM = TDAY_MTM - ISNULL(OTHERMARGIN,0)   
 FROM TBL_COMBINE_REPORTING_TDAY T (NOLOCK)  
 INNER JOIN  #FOMARGINNEW_DATA_COMM M WITH(NOLOCK)  
 ON T.MARGINDATE  = @MARGINDATE    
 AND T.MARGINDATE=M.MDATE  
 AND T.PARTY_CODE = M.PARTY_CODE   
  
 DECLARE @NCDXMDATE DATETIME  
 SELECT @NCDXMDATE=MAX(MDATE) FROM ANGELCOMMODITY.NCDX.DBO.FOMARGINNEW_DATA WITH(NOLOCK)  
 WHERE MDATE <= @MARGINDATE  
  
 SELECT * INTO #FOMARGINNEW_DATA_NCOMM   
    FROM ANGELCOMMODITY.NCDX.DBO.FOMARGINNEW_DATA M WITH(NOLOCK)  
 WHERE  MDATE = @NCDXMDATE  
  
  
    
  UPDATE T SET TDAY_MTM = TDAY_MTM - ISNULL(OTHERMARGIN,0)   
 FROM TBL_COMBINE_REPORTING_TDAY T (NOLOCK)  
 INNER JOIN #FOMARGINNEW_DATA_NCOMM  M With(Nolock)  
 ON T.MARGINDATE  = @MARGINDATE    
 AND T.MARGINDATE=M.MDATE  
 AND T.PARTY_CODE = M.PARTY_CODE   
  
 DROP TABLE #FOMARGINNEW_DATA_COMM  
 DROP TABLE #FOMARGINNEW_DATA_NCOMM  
    
 IF (SELECT ISNULL(COUNT(1),0) FROM SETT_MST WHERE SEC_PAYIN = @TDAYNEXT AND SETT_TYPE ='M')>0
 BEGIN  
 UPDATE TBL_COMBINE_REPORTING_TDAY       
 SET   TDAY_MTM_SHORT = TDAY_MTM_SHORT + PRADNYA.DBO.FNMAX(/*(CASE WHEN (TDAY_MARGIN_SHORT - TDAY_MARGIN) > 0 THEN (TDAY_MARGIN_SHORT - TDAY_MARGIN) ELSE 0 END) */         
     + PRADNYA.DBO.FNMAX(((T1DAY_CASH+T1DAY_NONCASH+TDAY_MTM)-(TDAY_CASH + TDAY_NONCASH))    
     +(CASE WHEN (TDAY_CASH + TDAY_NONCASH)<0 THEN (TDAY_CASH + TDAY_NONCASH) ELSE 0 END)    
     ,0)+ PRADNYA.DBO.FNMIN((CASE WHEN (TDAY_CASH + TDAY_NONCASH)>0 THEN     
       (TDAY_CASH + TDAY_NONCASH-TDAY_MARGIN) ELSE 0 END ), PRADNYA.DBO.FNMAX(TDAY_MARGIN-T1DAY_MARGIN,0)),0) 
 WHERE MARGINDATE = @MARGINDATE     
 
/*  
 UPDATE TBL_COMBINE_REPORTING_TDAY set TDAY_MARGIN_SHORT = (CASE WHEN TDAY_MARGIN_SHORT - PRADNYA.DBO.fnMax(TDAY_MTM_SHORT,0) >= 0 THEN TDAY_MARGIN_SHORT ELSE 0 END)
 WHERE MARGINDATE = @MARGINDATE     
 AND TDAY_MARGIN_SHORT > 0 */

END
ELSE
BEGIN
  IF 1 = 2
  BEGIN
  	UPDATE TBL_COMBINE_REPORTING_TDAY       
	SET   TDAY_MTM_SHORT = TDAY_MTM_SHORT + PRADNYA.DBO.FNMAX(/*(CASE WHEN (TDAY_MARGIN_SHORT - TDAY_MARGIN) > 0 THEN (TDAY_MARGIN_SHORT - TDAY_MARGIN) ELSE 0 END) */         
		+ PRADNYA.DBO.FNMAX(((T1DAY_CASH+T1DAY_NONCASH)-(TDAY_CASH + TDAY_NONCASH))    
		+(CASE WHEN (TDAY_CASH + TDAY_NONCASH)<0 THEN (TDAY_CASH + TDAY_NONCASH) ELSE 0 END)    
		,0)+ PRADNYA.DBO.FNMIN((CASE WHEN (TDAY_CASH + TDAY_NONCASH)>0 THEN     
		(TDAY_CASH + TDAY_NONCASH-TDAY_MARGIN) ELSE 0 END ), PRADNYA.DBO.FNMAX(TDAY_MARGIN-T1DAY_MARGIN,0)),0)       
	WHERE MARGINDATE = @MARGINDATE 
  END
  ELSE
  BEGIN
	UPDATE TBL_COMBINE_REPORTING_TDAY       
	SET   TDAY_MTM_SHORT = TDAY_MTM_SHORT + PRADNYA.DBO.FNMAX(/*(CASE WHEN (TDAY_MARGIN_SHORT - TDAY_MARGIN) > 0 THEN (TDAY_MARGIN_SHORT - TDAY_MARGIN) ELSE 0 END) */         
		+ PRADNYA.DBO.FNMAX(((T1DAY_CASH+T1DAY_NONCASH+TDAY_MTM)-(TDAY_CASH + TDAY_NONCASH))    
		+(CASE WHEN (TDAY_CASH + TDAY_NONCASH)<0 THEN (TDAY_CASH + TDAY_NONCASH) ELSE 0 END)    
		,0)+ PRADNYA.DBO.FNMIN((CASE WHEN (TDAY_CASH + TDAY_NONCASH)>0 THEN     
		(TDAY_CASH + TDAY_NONCASH-TDAY_MARGIN) ELSE 0 END ), PRADNYA.DBO.FNMAX(TDAY_MARGIN-T1DAY_MARGIN,0)),0)       
	WHERE MARGINDATE = @MARGINDATE 
 END 
END 
  
/*  
IF CONVERT(DATETIME,@MARGINDATE) > CONVERT(DATETIME,'SEP 15 2020')  
BEGIN   
 UPDATE TBL_COMBINE_REPORTING_TDAY       
 SET   TDAY_MTM_SHORT = (CASE WHEN TDAY_MTM <= COLLECT THEN TDAY_MTM ELSE TDAY_MTM_SHORT + COLLECT END)  
 FROM #MTMCOLLECT   
 WHERE TBL_COMBINE_REPORTING_TDAY.MARGINDATE = @MARGINDATE   
 AND TBL_COMBINE_REPORTING_TDAY.PARTY_CODE = #MTMCOLLECT.PARTY_CODE   
END */  
  
    /*  
 SELECT * FROM TBL_COMBINE_REPORTING_TDAY     
 WHERE MARGINDATE = @MARGINDATE AND PARTY_CODE = 'P124903'   
  */  
 UPDATE TBL_COMBINE_REPORTING_TDAY SET TDAY_MTM_SHORT = 0     
 WHERE TBL_COMBINE_REPORTING_TDAY.MARGINDATE  = @MARGINDATE AND  TDAY_MTM_SHORT < 0    
  
  
 DECLARE @FTMDATE DATETIME  
 SELECT @FTMDATE=MAX(MDATE) FROM ANGELFO.NSEFO.DBO.FOMARGINNEW  WITH(NOLOCK)  
 WHERE MDATE <= @MARGINDATE  
  
 SELECT * INTO #FOMARGINNEW_DATA_FO_T   
    FROM ANGELFO.NSEFO.DBO.FOMARGINNEW M WITH(NOLOCK)  
 WHERE  MDATE = @FTMDATE  
  
    
 UPDATE T SET TDAY_MTM = TDAY_MTM + ISNULL(DEL_MARGIN,0)   
 FROM TBL_COMBINE_REPORTING_TDAY T,#FOMARGINNEW_DATA_FO_T M WITH(NOLOCK)  
 WHERE MDATE = @FTMDATE  
 AND T.PARTY_CODE = M.PARTY_CODE   
 AND T.MARGINDATE  = @MARGINDATE    
   
   
 DECLARE @CTMDATE DATETIME  
 SELECT @CTMDATE=MAX(MDATE) FROM ANGELCOMMODITY.MCDX.DBO.FOMARGINNEW_DATA WITH(NOLOCK)  
 WHERE MDATE <= @MARGINDATE  
  
 SELECT * INTO #FOMARGINNEW_DATA_COMM_T   
    FROM ANGELCOMMODITY.MCDX.DBO.FOMARGINNEW_DATA M WITH(NOLOCK)  
 WHERE  MDATE = @CTMDATE  
      
  UPDATE T SET TDAY_MTM = TDAY_MTM + ISNULL(OTHERMARGIN,0)   
 FROM TBL_COMBINE_REPORTING_TDAY T (NOLOCK)  
 INNER JOIN   
 #FOMARGINNEW_DATA_COMM_T M WITH(NOLOCK)  
 ON T.PARTY_CODE = M.PARTY_CODE   
 AND T.MARGINDATE =M.MDATE  
 AND T.MARGINDATE  = @MARGINDATE    
  
 DECLARE @CNMDATE DATETIME  
 SELECT @CNMDATE=MAX(MDATE) FROM ANGELCOMMODITY.NCDX.DBO.FOMARGINNEW_DATA WITH(NOLOCK)  
 WHERE MDATE <= @MARGINDATE  
  
 SELECT * INTO #NFOMARGINNEW_DATA_COMM_T   
    FROM ANGELCOMMODITY.NCDX.DBO.FOMARGINNEW_DATA M WITH(NOLOCK)  
 WHERE  MDATE = @CNMDATE  
  
  
  
  UPDATE T SET TDAY_MTM = TDAY_MTM + ISNULL(OTHERMARGIN,0)   
 FROM TBL_COMBINE_REPORTING_TDAY T WITH(NOLOCK)  
 INNER JOIN #NFOMARGINNEW_DATA_COMM_T M WITH(NOLOCK)  
 ON   
 T.PARTY_CODE = M.PARTY_CODE AND T.MARGINDATE =M.MDATE  
 AND T.MARGINDATE  = @MARGINDATE    
  
 DROP TABLE #FOMARGINNEW_DATA_COMM_T  
 DROP TABLE #NFOMARGINNEW_DATA_COMM_T  
  
  
     
END     
    
SELECT * FROM TBL_COMBINE_REPORTING_TDAY WHERE MARGINDATE='OCT  4 2022'
AND PARTY_CODE='A1009543'
SELECT * FROM TBL_COMBINE_REPORTING_TDAY_DETAIL WHERE MARGINDATE='OCT  4 2022'
AND PARTY_CODE='A1009543'

UPDATE TBL_COMBINE_REPORTING_TDAY SET TDAY_MARGIN_SHORT = TDAY_MARGIN_SHORT - TDAY_MARGIN    
WHERE MARGINDATE  = @MARGINDATE AND TDAY_MARGIN > 0     
/*    
SELECT * FROM TBL_COMBINE_REPORTING_TDAY    
WHERE MARGINDATE = 'JAN  7 2020'    
AND PARTY_CODE = 'A151487'    
*/    
    
UPDATE TBL_COMBINE_REPORTING_TDAY SET     
TDAY_MARGIN_SHORT = TDAY_MARGIN_SHORT - PRADNYA.DBO.FNMIN(TDAY_MARGIN_SHORT,ABS(PRADNYA.DBO.FNMIN((TDAY_MTM_SHORT-TDAY_MTM),0))),    
TDAY_MTM_SHORT = TDAY_MTM_SHORT + PRADNYA.DBO.FNMIN(TDAY_MARGIN_SHORT,ABS(PRADNYA.DBO.FNMIN((TDAY_MTM_SHORT-TDAY_MTM),0)))    
WHERE MARGINDATE  = @MARGINDATE AND TDAY_MTM_SHORT-TDAY_MTM < 0    
AND TDAY_MTM > 0 AND TDAY_MTM_SHORT > 0 AND TDAY_MARGIN_SHORT > 0     
/*    
SELECT * FROM TBL_COMBINE_REPORTING_TDAY    
WHERE MARGINDATE = 'JAN  7 2020'    
AND PARTY_CODE = 'A151487'    
*/    
   
  /*  
IF CONVERT(DATETIME,@MARGINDATE) > CONVERT(DATETIME,'SEP 15 2020')  
BEGIN   
 UPDATE TBL_COMBINE_REPORTING_TDAY       
 SET   TDAY_MTM_SHORT = (CASE WHEN TDAY_MTM <= COLLECT THEN TDAY_MTM ELSE TDAY_MTM_SHORT + COLLECT END)  
 FROM #MTMCOLLECT   
 WHERE TBL_COMBINE_REPORTING_TDAY.MARGINDATE = @MARGINDATE   
 AND TBL_COMBINE_REPORTING_TDAY.PARTY_CODE = #MTMCOLLECT.PARTY_CODE   
END*/  
  
UPDATE TBL_COMBINE_REPORTING_TDAY SET     
TDAY_MARGIN_SHORT = TDAY_MARGIN_SHORT - PRADNYA.DBO.FNMIN(TDAY_MARGIN_SHORT,ABS(PRADNYA.DBO.FNMIN((TDAY_MTM_SHORT-TDAY_MTM),0))),    
TDAY_MTM_SHORT = TDAY_MTM_SHORT + PRADNYA.DBO.FNMIN(TDAY_MARGIN_SHORT,ABS(PRADNYA.DBO.FNMIN((TDAY_MTM_SHORT-TDAY_MTM),0)))    
WHERE MARGINDATE  = @MARGINDATE AND TDAY_MTM_SHORT-TDAY_MTM < 0    
AND TDAY_MTM > 0 AND TDAY_MARGIN_SHORT > 0     
    
UPDATE TBL_COMBINE_REPORTING_TDAY SET TDAY_MTM_SHORT = TDAY_MTM_SHORT - TDAY_MTM    
WHERE MARGINDATE  = @MARGINDATE     
AND TDAY_MTM > 0 AND TDAY_MTM_SHORT - TDAY_MTM < 0     
  
--IF (SELECT ISNULL(SUM(TDAY_MARGIN+TDAY_MTM),0) FROM TBL_COMBINE_REPORTING_TDAY   
--    WHERE MARGINDATE = @MARGINDATE) >= 0   
--BEGIN    
 UPDATE TBL_COMBINE_REPORTING_TDAY SET TDAY_MARGIN_SHORT = 0,TDAY_MTM_SHORT=0  
 WHERE MARGINDATE = @MARGINDATE AND T2DAY_LEDGER >= 0 AND (TDAY_MARGIN_SHORT < 0  OR TDAY_MTM_SHORT < 0)
 AND PARTY_CODE IN (SELECT CL_CODE FROM CLIENT1 (NOLOCK) WHERE CL_TYPE = 'NRI')  
  
 UPDATE TBL_COMBINE_REPORTING_TDAY SET TDAY_MARGIN_SHORT =0 ---PRADNYA.DBO.FNMIN(ABS(TDAY_MARGIN_SHORT),ABS(T2DAY_LEDGER))  
 ,TDAY_MTM_SHORT=0  
 WHERE MARGINDATE = @MARGINDATE AND T2DAY_LEDGER < 0  AND (TDAY_MARGIN_SHORT < 0  OR TDAY_MTM_SHORT < 0)
 AND PARTY_CODE IN (SELECT CL_CODE FROM CLIENT1 (NOLOCK) WHERE CL_TYPE = 'NRI')   
--END   
  
UPDATE TBL_COMBINE_REPORTING_TDAY SET TDAY_MARGIN_SHORT =0  
WHERE MARGINDATE = @MARGINDATE AND TDAY_MARGIN = 0 AND TDAY_MARGIN_SHORT < = 0  
  
UPDATE TBL_COMBINE_REPORTING_TDAY SET TDAY_MARGIN_SHORT = -TDAY_MARGIN  
WHERE MARGINDATE = @MARGINDATE AND TDAY_MARGIN > 0 AND TDAY_MARGIN_SHORT < 0  
AND TDAY_MARGIN < ABS(TDAY_MARGIN_SHORT)  
  
/*    
UPDATE TBL_COMBINE_REPORTING_TDAY SET TDAY_MTM_SHORT = PRADNYA.DBO.FNMAX(TDAY_MTM_SHORT, -TDAY_MTM)    
WHERE MARGINDATE  = @MARGINDATE AND TDAY_MTM_SHORT < 0    
*/    
IF @COMBINEFLAG = 0     
    
BEGIN       
    
 UPDATE TBL_COMBINE_REPORTING_TDAY_DETAIL     
    
 SET TDAY_MARGIN_SHORT = T1.TDAY_MARGIN_SHORT,    
    
  TDAY_MTM_SHORT = T1.TDAY_MTM_SHORT,    
    
  T1DAY_MARGIN_SHORT = T1.T1DAY_MARGIN_SHORT,    
    
  T1DAY_MTM_SHORT = T1.T1DAY_MTM_SHORT,    
    
  T2DAY_MARGIN_SHORT = T1.T2DAY_MARGIN_SHORT,    
    
  T2DAY_MTM_SHORT = T1.T2DAY_MTM_SHORT,    
    
  --T_MARGINAVL = (CASE WHEN T1.TDAY_MARGIN_SHORT >= 0 THEN T1.TDAY_MARGIN ELSE T1.TDAY_MARGIN_SHORT END),    
    
  --T_MTMAVL = (CASE WHEN T1.TDAY_MTM_SHORT >= 0 THEN T1.TDAY_MTM ELSE T1.TDAY_MTM_SHORT END)     
    
  T_MARGINAVL = (CASE WHEN T1.TDAY_MARGIN_SHORT >= 0 THEN T1.TDAY_MARGIN     
    
  ELSE (CASE WHEN T1.TDAY_MARGIN  > ABS(T1.TDAY_MARGIN_SHORT) THEN T1.TDAY_MARGIN_SHORT ELSE -T1.TDAY_MARGIN END) END),    
    
  T_MTMAVL = (CASE WHEN T1.TDAY_MTM_SHORT >= 0 THEN T1.TDAY_MTM     
    
  ELSE (CASE WHEN T1.TDAY_MTM  > ABS(T1.TDAY_MTM_SHORT) THEN T1.TDAY_MTM_SHORT ELSE -T1.TDAY_MTM END) END)     
    
 FROM TBL_COMBINE_REPORTING_TDAY T1    
    
 WHERE TBL_COMBINE_REPORTING_TDAY_DETAIL.MARGINDATE = @MARGINDATE     
    
 AND T1.MARGINDATE = @MARGINDATE    
    
 AND TBL_COMBINE_REPORTING_TDAY_DETAIL.PARTY_CODE = T1.PARTY_CODE    
    
 AND TBL_COMBINE_REPORTING_TDAY_DETAIL.EXCHANGE = T1.EXCHANGE    
    
 AND TBL_COMBINE_REPORTING_TDAY_DETAIL.SEGMENT = T1.SEGMENT    
    
END    
    
ELSE    
    
BEGIN    
ALTER TABLE TBL_COMBINE_REPORTING_TDAY_DETAIL REBUILD
ALTER TABLE TBL_COMBINE_REPORTING_TDAY REBUILD     
    
 UPDATE T    
    
 SET T_MARGINAVL = TDAY_MARGIN     
 FROM TBL_COMBINE_REPORTING_TDAY_DETAIL T (Nolock)
    
 WHERE MARGINDATE = @MARGINDATE     
    
 AND EXISTS (SELECT PARTY_CODE FROM TBL_COMBINE_REPORTING_TDAY   (NolOCK) 
    
    WHERE MARGINDATE = @MARGINDATE     
    
    AND T.PARTY_CODE = TBL_COMBINE_REPORTING_TDAY.PARTY_CODE    
    
    AND TDAY_MARGIN_SHORT >= 0)    
    
    
    
 UPDATE T    
    
 SET T_MTMAVL = TDAY_MTM    
 From TBL_COMBINE_REPORTING_TDAY_DETAIL T (NOLOCK)
    
 WHERE MARGINDATE = @MARGINDATE     
    
 AND EXISTS (SELECT PARTY_CODE FROM TBL_COMBINE_REPORTING_TDAY   (NOLOCK)  
    
    WHERE MARGINDATE = @MARGINDATE     
    
    AND T.PARTY_CODE = TBL_COMBINE_REPORTING_TDAY.PARTY_CODE    
    
    AND TDAY_MTM_SHORT >= 0)    
    
 SELECT distinct PARTY_CODE INTO #PARTYCNT FROM TBL_COMBINE_REPORTING_TDAY_DETAIL    
 WHERE MARGINDATE = @MARGINDATE and EXCHANGE <> 'POA'    
 AND TDAY_MARGIN + TDAY_MTM > 0     
 GROUP BY PARTY_CODE     
 HAVING COUNT(1) = 1    
      
  CREATE CLUSTERED INDEX PARTIDX ON #PARTYCNT    
  (    
  PARTY_CODE    
  )    
    
 UPDATE T    
 SET T_MARGINAVL = (CASE WHEN T1.TDAY_MARGIN_SHORT >= 0 THEN T.TDAY_MARGIN ELSE T1.TDAY_MARGIN_SHORT END),   
 T_MTMAVL = T1.TDAY_MTM_SHORT    
 FROM TBL_COMBINE_REPORTING_TDAY T1 (NOLOCK)   ,TBL_COMBINE_REPORTING_TDAY_DETAIL T   (NOLOCK)  
 WHERE T.MARGINDATE = @MARGINDATE     
 AND T1.MARGINDATE = @MARGINDATE AND T.TDAY_MARGIN + T.TDAY_MTM > 0     
 AND T.PARTY_CODE = T1.PARTY_CODE    
 AND EXISTS (SELECT PARTY_CODE FROM #PARTYCNT (NOLOCK)     
    WHERE #PARTYCNT.PARTY_CODE = T.PARTY_CODE)    
   
SELECT * INTO #V2_TBL_EXCHANGE_MARGIN_REPORT FROM V2_TBL_EXCHANGE_MARGIN_REPORT  
  
 IF CONVERT(DATETIME,@MARGINDATE) > CONVERT(DATETIME,'SEP 15 2020')  
 BEGIN  
 UPDATE #V2_TBL_EXCHANGE_MARGIN_REPORT SET EXCHANGE_PRIORITY = 0 WHERE SEGMENT = 'CAPITAL'  
 end  
         
SELECT * FROM TBL_COMBINE_REPORTING_TDAY WHERE MARGINDATE='OCT  4 2022'
AND PARTY_CODE='A1009543'
SELECT * FROM TBL_COMBINE_REPORTING_TDAY_DETAIL WHERE MARGINDATE='OCT  4 2022'
AND PARTY_CODE='A1009543'

 SET @MRGCUR = CURSOR FOR    
 SELECT PARTY_CODE, AVAL_MARGIN=TDAY_MARGIN_SHORT FROM TBL_COMBINE_REPORTING_TDAY    
 WHERE MARGINDATE = @MARGINDATE  AND TDAY_MARGIN_SHORT < 0     
 AND NOT EXISTS (SELECT PARTY_CODE FROM #PARTYCNT    
    WHERE #PARTYCNT.PARTY_CODE = TBL_COMBINE_REPORTING_TDAY.PARTY_CODE)    
   ORDER BY PARTY_CODE     
    
 OPEN @MRGCUR    
 FETCH NEXT FROM @MRGCUR INTO @PARTY_CODE, @SHRT_AMT    
 WHILE @@FETCH_STATUS = 0    
 BEGIN    
  SET @EXCHANGEWISE_CURSOR = CURSOR FOR    
  SELECT PARTY_CODE, T.EXCHANGE, T.SEGMENT, TDAY_MARGIN, EXCHANGE_PRIORITY     
  FROM TBL_COMBINE_REPORTING_TDAY_DETAIL T, #V2_TBL_EXCHANGE_MARGIN_REPORT T1    
  WHERE MARGINDATE = @MARGINDATE    
  AND PARTY_CODE = @PARTY_CODE    
  AND T.EXCHANGE = T1.EXCHANGE     
  AND T.SEGMENT = T1.SEGMENT     
  AND TDAY_MARGIN > 0    
  ORDER BY EXCHANGE_PRIORITY DESC    
    
  OPEN @EXCHANGEWISE_CURSOR    
    
  FETCH NEXT FROM @EXCHANGEWISE_CURSOR INTO @PARTY_CODE, @EXCHANGE_NEW, @SEGMENT_NEW, @MARG_AMT, @EXCHANGE_PRIORITY    
  WHILE @@FETCH_STATUS = 0    
    
  BEGIN    
    
   IF @SHRT_AMT < 0     
    
   BEGIN    
    
    IF @MARG_AMT >= ABS(@SHRT_AMT)    
    
    BEGIN    
    
     UPDATE TBL_COMBINE_REPORTING_TDAY_DETAIL SET T_MARGINAVL = @SHRT_AMT    
     WHERE MARGINDATE = @MARGINDATE    
     AND PARTY_CODE = @PARTY_CODE    
     AND EXCHANGE = @EXCHANGE_NEW     
     AND SEGMENT = @SEGMENT_NEW     
     SET @SHRT_AMT = 0    
    
    END    
    
    ELSE    
    
    BEGIN    
    
     UPDATE TBL_COMBINE_REPORTING_TDAY_DETAIL SET T_MARGINAVL = -@MARG_AMT    
    
     WHERE MARGINDATE = @MARGINDATE    
    
     AND PARTY_CODE = @PARTY_CODE    
    
     AND EXCHANGE = @EXCHANGE_NEW     
    
     AND SEGMENT = @SEGMENT_NEW     
    
     SET @SHRT_AMT = @SHRT_AMT + @MARG_AMT    
    
    END    
    
   END    
    
   ELSE    
    
   BEGIN    
    
    UPDATE TBL_COMBINE_REPORTING_TDAY_DETAIL SET T_MARGINAVL = @MARG_AMT    
    
    WHERE MARGINDATE = @MARGINDATE    
    
    AND PARTY_CODE = @PARTY_CODE    
    
    AND EXCHANGE = @EXCHANGE_NEW     
    
    AND SEGMENT = @SEGMENT_NEW     
    
   END    
    
   FETCH NEXT FROM @EXCHANGEWISE_CURSOR INTO @PARTY_CODE, @EXCHANGE_NEW, @SEGMENT_NEW, @MARG_AMT, @EXCHANGE_PRIORITY    
    
  END    
    
  CLOSE @EXCHANGEWISE_CURSOR    
    
  DEALLOCATE @EXCHANGEWISE_CURSOR    
    
  FETCH NEXT FROM @MRGCUR INTO @PARTY_CODE, @SHRT_AMT    
    
 END   
    
 CLOSE @MRGCUR    
    
 DEALLOCATE @MRGCUR    
    
    
    
 SET @MRGCUR = CURSOR FOR    
    
 SELECT PARTY_CODE, AVAL_MARGIN=TDAY_MTM_SHORT FROM TBL_COMBINE_REPORTING_TDAY    
    
 WHERE MARGINDATE = @MARGINDATE   AND TDAY_MTM_SHORT < 0     
    
 AND NOT EXISTS (SELECT PARTY_CODE FROM #PARTYCNT    
    
    WHERE #PARTYCNT.PARTY_CODE = TBL_COMBINE_REPORTING_TDAY.PARTY_CODE)    
    
    
 ORDER BY PARTY_CODE     
    
 OPEN @MRGCUR    
    
 FETCH NEXT FROM @MRGCUR INTO @PARTY_CODE, @SHRT_AMT    
    
 WHILE @@FETCH_STATUS = 0    
    
 BEGIN    
    
  SET @EXCHANGEWISE_CURSOR = CURSOR FOR    
    
  SELECT PARTY_CODE, T.EXCHANGE, T.SEGMENT, TDAY_MTM, EXCHANGE_PRIORITY     
    
  FROM TBL_COMBINE_REPORTING_TDAY_DETAIL T, #V2_TBL_EXCHANGE_MARGIN_REPORT T1    
    
  WHERE MARGINDATE = @MARGINDATE    
    
  AND PARTY_CODE = @PARTY_CODE    
    
  AND T.EXCHANGE = T1.EXCHANGE     
    
  AND T.SEGMENT = T1.SEGMENT     
    
  AND TDAY_MTM > 0    
    
  ORDER BY EXCHANGE_PRIORITY DESC    
    
  OPEN @EXCHANGEWISE_CURSOR    
    
  FETCH NEXT FROM @EXCHANGEWISE_CURSOR INTO @PARTY_CODE, @EXCHANGE_NEW, @SEGMENT_NEW, @MARG_AMT, @EXCHANGE_PRIORITY    
    
  WHILE @@FETCH_STATUS = 0    
    
  BEGIN    
    
   IF @SHRT_AMT < 0     
    
   BEGIN    
    
    IF @MARG_AMT >= ABS(@SHRT_AMT)    
    
    BEGIN    
    
     UPDATE TBL_COMBINE_REPORTING_TDAY_DETAIL SET T_MTMAVL = @SHRT_AMT    
     WHERE MARGINDATE = @MARGINDATE    
     AND PARTY_CODE = @PARTY_CODE    
     AND EXCHANGE = @EXCHANGE_NEW     
     AND SEGMENT = @SEGMENT_NEW     
    
     SET @SHRT_AMT = 0    
    
    END    
    
    ELSE    
    
    BEGIN    
    
     UPDATE TBL_COMBINE_REPORTING_TDAY_DETAIL SET T_MTMAVL = -@MARG_AMT    
     WHERE MARGINDATE = @MARGINDATE    
     AND PARTY_CODE = @PARTY_CODE    
     AND EXCHANGE = @EXCHANGE_NEW     
     AND SEGMENT = @SEGMENT_NEW     
     SET @SHRT_AMT = @SHRT_AMT + @MARG_AMT    
    
    END    
    
   END    
    
   ELSE    
    
   BEGIN    
    
    UPDATE TBL_COMBINE_REPORTING_TDAY_DETAIL SET T_MTMAVL = @MARG_AMT    
    WHERE MARGINDATE = @MARGINDATE    
    AND PARTY_CODE = @PARTY_CODE    
    AND EXCHANGE = @EXCHANGE_NEW     
    AND SEGMENT = @SEGMENT_NEW     
    
   END    
    
   FETCH NEXT FROM @EXCHANGEWISE_CURSOR INTO @PARTY_CODE, @EXCHANGE_NEW, @SEGMENT_NEW, @MARG_AMT, @EXCHANGE_PRIORITY    
    
  END    
    
  CLOSE @EXCHANGEWISE_CURSOR    
    
  DEALLOCATE @EXCHANGEWISE_CURSOR    
    
  FETCH NEXT FROM @MRGCUR INTO @PARTY_CODE, @SHRT_AMT    
    
 END    
    
 CLOSE @MRGCUR    
    
 DEALLOCATE @MRGCUR    
    
     
SELECT * FROM TBL_COMBINE_REPORTING_TDAY WHERE MARGINDATE='OCT  4 2022'
AND PARTY_CODE='A1009543'
SELECT * FROM TBL_COMBINE_REPORTING_TDAY_DETAIL WHERE MARGINDATE='OCT  4 2022'
AND PARTY_CODE='A1009543'

 SET @MRGCUR = CURSOR FOR    
    
 SELECT PARTY_CODE, AVAL_MARGIN=PRADNYA.DBO.FNMAX(0,    
    
            PRADNYA.DBO.FNMIN(T2DAY_CASH,T2DAY_MARGIN_SHORT))     
    
 FROM TBL_COMBINE_REPORTING_TDAY    
    
 WHERE MARGINDATE = @MARGINDATE     
    
 AND NOT EXISTS (SELECT PARTY_CODE FROM #PARTYCNT    
    
    WHERE #PARTYCNT.PARTY_CODE = TBL_COMBINE_REPORTING_TDAY.PARTY_CODE)    
    
 AND TDAY_MTM_SHORT < 0 AND PRADNYA.DBO.FNMAX(0,    
    
            PRADNYA.DBO.FNMIN(T2DAY_CASH,T2DAY_MARGIN_SHORT)) > 0    
    
 ORDER BY PARTY_CODE     
    
 OPEN @MRGCUR    
    
 FETCH NEXT FROM @MRGCUR INTO @PARTY_CODE, @SHRT_AMT    
    
 WHILE @@FETCH_STATUS = 0    
    
 BEGIN    
    
  SET @EXCHANGEWISE_CURSOR = CURSOR FOR    
    
  SELECT PARTY_CODE, T.EXCHANGE, T.SEGMENT, TDAY_MTM=T_MTMAVL, EXCHANGE_PRIORITY     
  FROM TBL_COMBINE_REPORTING_TDAY_DETAIL T, #V2_TBL_EXCHANGE_MARGIN_REPORT T1    
  WHERE MARGINDATE = @MARGINDATE    
  AND PARTY_CODE = @PARTY_CODE    
  AND T.EXCHANGE = T1.EXCHANGE     
  AND T.SEGMENT = T1.SEGMENT     
  AND TDAY_MTM > 0 AND T_MTMAVL < 0    
  AND T.EXCHANGE IN ('NCX','MCX','NCM','MCM','NSE')  
  AND SEGMENT = (CASE WHEN EXCHANGE = 'NSE' THEN  'CAPITAL' ELSE 'FUTURES' END)  
  ORDER BY EXCHANGE_PRIORITY DESC    
    
  OPEN @EXCHANGEWISE_CURSOR    
    
  FETCH NEXT FROM @EXCHANGEWISE_CURSOR INTO @PARTY_CODE, @EXCHANGE_NEW, @SEGMENT_NEW, @MARG_AMT, @EXCHANGE_PRIORITY    
  WHILE @@FETCH_STATUS = 0    
  BEGIN    
   IF @SHRT_AMT > 0     
   BEGIN    
    IF ABS(@MARG_AMT) >= ABS(@SHRT_AMT)    
    BEGIN    
    
     UPDATE TBL_COMBINE_REPORTING_TDAY_DETAIL SET T_MTMAVL = T_MTMAVL + @SHRT_AMT    
     WHERE MARGINDATE = @MARGINDATE    
     AND PARTY_CODE = @PARTY_CODE    
     AND EXCHANGE = @EXCHANGE_NEW     
     AND SEGMENT = @SEGMENT_NEW     
    
     SET @SHRT_AMT = 0    
    
    END    
    
    ELSE    
    
    BEGIN    
    
     UPDATE TBL_COMBINE_REPORTING_TDAY_DETAIL SET T_MTMAVL = T_MTMAVL-@MARG_AMT    
     WHERE MARGINDATE = @MARGINDATE    
     AND PARTY_CODE = @PARTY_CODE    
     AND EXCHANGE = @EXCHANGE_NEW     
     AND SEGMENT = @SEGMENT_NEW     
    
     SET @SHRT_AMT = @SHRT_AMT + @MARG_AMT    
    
    END    
    
   END    
    
   ELSE    
    
   BEGIN    
    
    UPDATE TBL_COMBINE_REPORTING_TDAY_DETAIL SET T_MTMAVL = T_MTMAVL - @MARG_AMT    
    WHERE MARGINDATE = @MARGINDATE    
    AND PARTY_CODE = @PARTY_CODE    
    AND EXCHANGE = @EXCHANGE_NEW     
    AND SEGMENT = @SEGMENT_NEW     
    
   END    
    
   FETCH NEXT FROM @EXCHANGEWISE_CURSOR INTO @PARTY_CODE, @EXCHANGE_NEW, @SEGMENT_NEW, @MARG_AMT, @EXCHANGE_PRIORITY    
    
  END    
    
  CLOSE @EXCHANGEWISE_CURSOR    
    
  DEALLOCATE @EXCHANGEWISE_CURSOR    
    
  FETCH NEXT FROM @MRGCUR INTO @PARTY_CODE, @SHRT_AMT    
    
 END    
    
 CLOSE @MRGCUR    
    
 DEALLOCATE @MRGCUR      
    
    
    
END    
  
--SELECT * FROM TBL_COMBINE_REPORTING_TDAY  
--WHERE MARGINDATE='MAY  5 2021'  
----AND PARTY_CODE = 'A124830'  
--SELECT * FROM TBL_COMBINE_REPORTING_TDAY_DETAIL  
--WHERE MARGINDATE='MAY  5 2021'  
----AND PARTY_CODE = 'A124830'  
--SELECT * FROM #MTMCOLLECT  
----WHERE PARTY_CODE = 'A124830'  
--SELECT * FROM #EPNPOOL  
-----WHERE PARTY_CODE = 'A124830'  
  
UPDATE TBL_COMBINE_REPORTING_TDAY_DETAIL SET T_MTMAVL = 0   
WHERE MARGINDATE  = @MARGINDATE     
AND EXCHANGE = 'NSE' AND SEGMENT = 'CAPITAL'  
AND TDAY_MTM = 0   
  
UPDATE TBL_COMBINE_REPORTING_TDAY SET TDAY_MTM = TDAY_MTM + COLLECT, TDAY_MTM_SHORT = (CASE WHEN TDAY_MTM_SHORT < 0 THEN TDAY_MTM_SHORT ELSE TDAY_MTM_SHORT + COLLECT END)  
FROM #MTMCOLLECT M (NOLOCK)  
WHERE MARGINDATE  = @MARGINDATE   AND TBL_COMBINE_REPORTING_TDAY.PARTY_CODE = M.PARTY_CODE   
  
UPDATE TBL_COMBINE_REPORTING_TDAY_DETAIL SET TDAY_MTM = TDAY_MTM + COLLECT, T_MTMAVL = (CASE WHEN T_MTMAVL < 0 THEN T_MTMAVL ELSE T_MTMAVL + COLLECT END)  
FROM #MTMCOLLECT M (NOLOCK)  
WHERE MARGINDATE  = @MARGINDATE   AND TBL_COMBINE_REPORTING_TDAY_DETAIL.PARTY_CODE = M.PARTY_CODE   
AND EXCHANGE = 'NSE' AND SEGMENT = 'CAPITAL'

GO
