-- Object: PROCEDURE dbo.RPT_WEEKLY_CLIENT_CASH_BALANCE_NEW_MCX
-- Server: 10.253.33.91 | DB: MSAJAG
--------------------------------------------------



--EXEC RPT_WEEKLY_CLIENT_CASH_BALANCE_NEW_AHSAN 'FEB  3 2022', 'FEB  3 2022', 'A100018', 'A100018', 'NSE'
--EXEC RPT_WEEKLY_CLIENT_CASH_BALANCE_NEW 'SEP  9 2021', 'SEP  9 2021', 'A100018', 'A100018', 'NSE'
CREATE PROCEDURE [DBO].[RPT_WEEKLY_CLIENT_CASH_BALANCE_NEW_MCX]
(
  @FROMDATE   VARCHAR(11),
  @TODATE           VARCHAR(11),
  @FROMPARTY  VARCHAR(20) = 'A00000',
  @TOPARTY    VARCHAR(20) = 'ZZZZZZZ',
	@EXCHANGE   VARCHAR(3)  = 'MCX',
	@FLAG VARCHAR(10) = ''
)
AS

  DECLARE @FROMDT         INT,
          @TODT       INT,
          @RPTDATE    VARCHAR(11),
          @FILENAMEHS VARCHAR(100),
          @FILENAMENH VARCHAR(100),
          @PANNO            VARCHAR(20),
          @BATCHNO    INT,
          @FROFYMDATE VARCHAR(11),
          @FRDATE_NEXT VARCHAR(11)

DECLARE
		@@MFSS_FLAG BIT,
		@@MARGIN_FLAG BIT,
		@@PARENT_FLAG BIT,
		@@CLIENT_BANK_ACC VARCHAR(20)

	SELECT @@MFSS_FLAG = MFSS_FLAG, @@MARGIN_FLAG = MARGIN_FLAG, @@PARENT_FLAG = PARENT_FLAG, 
        @@CLIENT_BANK_ACC = CLIENT_BANK_ACC FROM MSAJAG..WEEKLY_CASH_BALANCES_SETTING
 
 ----------------------- MCX--------------------
CREATE TABLE #EXCHANGE_CLINETS
(
	CL_CODE VARCHAR(10)
)

INSERT INTO #EXCHANGE_CLINETS
EXEC GET_EXCH_REG_CLIENTS 'MCX', @FROMPARTY, @TOPARTY, @FROMDATE

CREATE INDEX #C ON #EXCHANGE_CLINETS (CL_CODE)
--- END MCX CLIENT ---------

 
CREATE TABLE #CL_LIST    
(    
 PARTY_CODE VARCHAR(10),    
 PARTY_NAME VARCHAR(100),    
 CLIENT_PAN VARCHAR(50),
 CL_TYPE VARCHAR(10),
 PARENT_CODE VARCHAR(10)   
)    
    
INSERT INTO #CL_LIST    
SELECT A.CL_CODE, LONG_NAME, PAN_GIR_NO, CL_TYPE, PARENTCODE = CASE WHEN @@PARENT_FLAG = 1 THEN PARENTCODE ELSE A.CL_CODE END
FROM MSAJAG..VW_CLIENT_DETAILS_DATA  A (NOLOCK)  
INNER JOIN #EXCHANGE_CLINETS B ON A.CL_CODE =B.CL_CODE 
WHERE A.CL_CODE BETWEEN @FROMPARTY AND @TOPARTY 
    

IF @@PARENT_FLAG = 1
BEGIN
	UPDATE C SET C.PARTY_NAME =C1.PARTY_NAME, C.CLIENT_PAN = C1.CLIENT_PAN
	FROM #CL_LIST C, (SELECT * FROM #CL_LIST WHERE PARTY_CODE = PARENT_CODE) C1
	WHERE C.PARTY_CODE = C1.PARENT_CODE
END


CREATE TABLE #CLIENT_LIST

(

      CLTCODE VARCHAR(10)

)

CREATE INDEX #CL ON #CLIENT_LIST (CLTCODE)
 
CREATE NONCLUSTERED INDEX [CLLIST] ON #CLIENT_LIST
		(
			[CLTCODE] ASC
		)

		EXEC GET_SEBI_AUDIT_CLIENT_LIST_SEBI 
		'', 
		@FROMDATE,
		1 

 
SELECT      @TODT = DATEDIFF(DAY, CONVERT(DATETIME, @FROMDATE, 109), CONVERT(DATETIME, @TODATE, 109))
SELECT      @PANNO = ISNULL(LTRIM(RTRIM(PANNO)),'') FROM OWNER (NOLOCK)
SELECT      @BATCHNO = ISNULL(MAX(FLDBATCHNO),0)+1 FROM ASIANFILEBATCHNO 
            WHERE FLDFILENO = 'CE' 
            AND LEFT(FLDFILEDATE,11) = LEFT(GETDATE(),11)

IF @BATCHNO = 1 
BEGIN 
      INSERT INTO ASIANFILEBATCHNO VALUES ('CE', @BATCHNO, GETDATE(), GETDATE()) 
END 
ELSE 
BEGIN 
      UPDATE ASIANFILEBATCHNO SET FLDBATCHNO = @BATCHNO WHERE FLDFILENO = 'CE' AND LEFT(FLDFILEDATE,11) = LEFT(GETDATE(),11)
END 
SET   @FILENAMEHS = @PANNO + '_CE_' + REPLACE(CONVERT(VARCHAR,CONVERT(DATETIME,@TODATE,109),103),'/','') + '_' + RIGHT('00'+CONVERT(VARCHAR,@BATCHNO),2) + '.CSV'

 DECLARE @MX DATE 
    SELECT @MX = MAX(STATUS_FROM_DATE ) FROM ACCOUNT..CLIENT_CASH_ACTIVE_LOG  WITH(NOLOCK) 
	WHERE STATUS_FROM_DATE <= @FROMDATE
    
    IF OBJECT_ID('TEMPDB..#CLIENT_CASH_ACTIVE_LOG_TEMP') IS NOT NULL
      DROP TABLE #CLIENT_CASH_ACTIVE_LOG_TEMP
      SELECT * INTO #CLIENT_CASH_ACTIVE_LOG_TEMP FROM ACCOUNT..CLIENT_CASH_ACTIVE_LOG  WHERE 1=0

    --IF (@FROMDATE >=@MX)
      INSERT INTO #CLIENT_CASH_ACTIVE_LOG_TEMP
      SELECT * FROM ACCOUNT..CLIENT_CASH_ACTIVE_LOG 
               WHERE STATUS_FLAG = 0 AND STATUS_FROM_DATE  =@MX --AND @FROMDATE BETWEEN STATUS_FROM_DATE AND STATUS_TO_DATE
    --ELSE 
    --BEGIN
    -- INSERT INTO #CLIENT_CASH_ACTIVE_LOG_TEMP
    --SELECT * FROM ACCOUNT..CLIENT_CASH_ACTIVE_LOG 
    --            WHERE STATUS_FLAG = 0 AND @FROMDATE BETWEEN STATUS_FROM_DATE AND STATUS_TO_DATE
    --END

     ;
WITH CTE 
AS
(
  SELECT *,ROW_NUMBER() OVER(PARTITION BY CLTCODE,	STATUS_FROM_DATE,	STATUS_TO_DATE	,STATUS_FLAG  ORDER BY CLTCODE ) RNK FROM #CLIENT_CASH_ACTIVE_LOG_TEMP
  WHERE STATUS_FLAG = 0  
)
DELETE FROM CTE WHERE RNK>1

 IF OBJECT_ID('TEMPDB..#CLIENT_CASH_DETAILS_TMP') IS NOT NULL
    DROP TABLE #CLIENT_CASH_DETAILS_TMP
 SELECT * INTO #CLIENT_CASH_DETAILS_TMP FROM ACCOUNT..CLIENT_CASH_DETAILS A
         WHERE REPORT_DATE BETWEEN @FROMDATE AND @TODATE + ' 23:59' AND UCC BETWEEN @FROMPARTY AND @TOPARTY
         AND EXISTS(SELECT CL_CODE FROM #EXCHANGE_CLINETS B WITH(NOLOCK) WHERE B.CL_CODE = A.UCC)

 CREATE INDEX IX_#CLIENT_CASH_DETAILS_TMP ON #CLIENT_CASH_DETAILS_TMP (SNO,UCC)

 CREATE INDEX #IX_CLIENT_TEMP ON #CLIENT_CASH_ACTIVE_LOG_TEMP (CLTCODE)

 SELECT L.* INTO #CLIENT_CASH_LED_BALANCES  FROM #CLIENT_CASH_DETAILS_TMP C 
INNER JOIN ACCOUNT..CLIENT_CASH_LED_BALANCES L WITH(NOLOCK) ON C.SNO = L.SNO 

 CREATE INDEX #IX_CLIENT_LDBAL ON #CLIENT_CASH_LED_BALANCES (SNO)


/* CHANGE IN QUERY TO GET THE NEW COLUMNS */ 
SELECT 
TRADING_PAN = LTRIM(RTRIM(ISNULL(TRADING_PAN, ''))), REPORT_DATE,UCC=LTRIM(RTRIM(ISNULL(PARENTCODE, ''))),CLIENT_PAN = LTRIM(RTRIM(ISNULL(CLIENT_PAN, ''))),CLIENT_NAME = LTRIM(RTRIM(ISNULL(CLIENT_NAME, ''))),
SEGMENT_INDICATOR = CASE WHEN EXCHANGE = 'MTF' THEN 'MTF' ELSE 'NON MTF' END, EXCHANGE, SEGMENT, 
--VDT_BAL = CASE WHEN EXCHANGE = 'MTF' THEN CASE WHEN ROUND(VDT_BAL, 2) + ROUND(ISNULL(CASH_COLL_MTF_POSITIONS,0), 2) < 0 THEN ROUND(VDT_BAL, 2) ELSE -ROUND(ISNULL(CASH_COLL_MTF_POSITIONS,0), 2) END ELSE ROUND(VDT_BAL, 2) END, 
--- VDT CODE UPDATED ON 17TH FEB AFTER THE  DISCUSSION WITH YOGESH
VDT_BAL = ROUND(VDT_BAL, 2),
--CASE WHEN EXCHANGE = 'MTF' THEN CASE WHEN ROUND(VDT_BAL, 2) + ROUND(ISNULL(CASH_COLL_MTF_POSITIONS,0), 2) > 0 THEN ROUND(VDT_BAL, 2) - (ROUND(VDT_BAL, 2) + ROUND(ISNULL(CASH_COLL_MTF_POSITIONS,0), 2)) ELSE ROUND(VDT_BAL, 2) END ELSE ROUND(VDT_BAL, 2) END,

EDT_BAL = ROUND(EDT_BAL, 2),PEAK_FINANCIAL_LEDGER = ROUND(PEAK_FINANCIAL_LEDGER, 2), BG, FDR, GOV_IND_SEC, GILT_FUNDS, EPI_LEDGER,POOL_ACCOUNT,CHQ_DEPOSITS,CHQ_ISSUE, 
COMM_VALUE,LAST_SETT_DATE,OPEN_BILL1, OPEN_BILL2, MARGIN_REQ, 
CASH_COLL_MTF_POSITIONS = CASE WHEN EXCHANGE = 'MTF' THEN CASE WHEN ROUND(VDT_BAL, 2) + ROUND(ISNULL(CASH_COLL_MTF_POSITIONS,0), 2) > 0 THEN CONVERT(VARCHAR, ROUND(VDT_BAL, 2) + ROUND(ISNULL(CASH_COLL_MTF_POSITIONS,0), 2)) ELSE CONVERT(VARCHAR, 0) END ELSE 'NA' END, 
UNCLAIMED_CLIENT_FUNDS = CASE WHEN REPORT_DATE BETWEEN STATUS_FROM_DATE AND STATUS_TO_DATE THEN 'YES' ELSE 'NO' END 
INTO #REPORT_DATA 
FROM 
#CLIENT_CASH_DETAILS_TMP C 
INNER JOIN #CLIENT_CASH_LED_BALANCES L WITH(NOLOCK) ON C.SNO = L.SNO 
LEFT OUTER JOIN  #CLIENT_CASH_ACTIVE_LOG_TEMP A ON UCC = A.CLTCODE 

--(SELECT * FROM ACCOUNT..CLIENT_CASH_DETAILS WHERE REPORT_DATE BETWEEN @FROMDATE AND @TODATE + ' 23:59' 
--AND UCC BETWEEN @FROMPARTY AND @TOPARTY) C 
--INNER JOIN ACCOUNT..CLIENT_CASH_LED_BALANCES  L 
--ON C.SNO = L.SNO 
--LEFT OUTER JOIN (SELECT * FROM ACCOUNT..CLIENT_CASH_ACTIVE_LOG WHERE STATUS_FLAG = 0) A 
--ON UCC = A.CLTCODE 
--WHERE 
-- EXISTS(SELECT CL_CODE FROM #EXCHANGE_CLINETS WITH(NOLOCK) WHERE CL_CODE = UCC) -- ADDED MCX CLINET 

 DELETE FROM #REPORT_DATA WHERE UCC='BBBB'

DECLARE
      @TRADING_PAN VARCHAR(10)

SELECT TOP 1 @TRADING_PAN = TRADING_PAN FROM #REPORT_DATA
DELETE R FROM #REPORT_DATA R 
         WHERE VDT_BAL = 0 AND EDT_BAL = 0 AND PEAK_FINANCIAL_LEDGER = 0 AND BG = 0 AND FDR = 0 AND GOV_IND_SEC = 0AND GILT_FUNDS = 0
              AND EPI_LEDGER  = 0 AND POOL_ACCOUNT = 0 AND CHQ_DEPOSITS = 0 AND CHQ_ISSUE = 0 AND COMM_VALUE = 0

CREATE TABLE #CAL_DATES
(
  CAL_DATES DATETIME
)

INSERT INTO #CAL_DATES
EXEC ACCOUNT..GET_CAL_DATES @FROMDATE, @TODATE
 
INSERT INTO #REPORT_DATA
SELECT TRADING_PAN = LTRIM(RTRIM(ISNULL(@TRADING_PAN, ''))), CAL_DATES, PARTY_CODE = LTRIM(RTRIM(ISNULL(PARENT_CODE, ''))), CLIENT_PAN = LTRIM(RTRIM(ISNULL(CLIENT_PAN, ''))), PARTY_NAME = LTRIM(RTRIM(ISNULL(PARTY_NAME, ''))), 'NON MTF', 'NSE', 'CAPITAL',  VDT_BAL = 0, EDT_BAL = 0,PEAK_FINANCIAL_LEDGER = 0, BG = 0, FDR = 0, GOV_IND_SEC = 0, GILT_FUNDS = 0, EPI_LEDGER = 0,POOL_ACCOUNT = 0,CHQ_DEPOSITS = 0,CHQ_ISSUE = 0,COMM_VALUE = 0,LAST_SETT_DATE = 'NA',OPEN_BILL1=0, OPEN_BILL2=0, MARGIN_REQ = 0, 'NA', CASE WHEN CAL_DATES BETWEEN STATUS_FROM_DATE AND STATUS_TO_DATE THEN 'YES' ELSE 'NO' END
FROM #CL_LIST C 
LEFT OUTER JOIN  #CLIENT_CASH_ACTIVE_LOG_TEMP A ON C.PARTY_CODE = A.CLTCODE,
--LEFT OUTER JOIN (SELECT * FROM ACCOUNT..CLIENT_CASH_ACTIVE_LOG WHERE STATUS_FLAG = 0) A
--ON PARTY_CODE = A.CLTCODE,
#CLIENT_LIST CL, #CAL_DATES CD
WHERE PARTY_CODE = CL.CLTCODE
AND NOT EXISTS(SELECT UCC FROM #REPORT_DATA WHERE UCC = CL.CLTCODE AND REPORT_DATE = CAL_DATES AND SEGMENT_INDICATOR = 'NON MTF')
AND PARTY_CODE BETWEEN @FROMPARTY AND @TOPARTY


/*CREATE TABLE #LAST_SETTLE

      (

            CLTCODE VARCHAR(10),

            LAST_SETT_DATE VARCHAR(20),

            CHK_DATE DATETIME

      )

 

     

 

        EXEC ACCOUNT.DBO.GET_LAST_SETTTLE_DATE

      @TODATE, @EXCHANGE

      --'BSE', 'A'

 

     

        UPDATE C SET LAST_SETT_DATE = CASE WHEN CHK_DATE <= CONVERT(DATETIME,REPORT_DATE,105) THEN L.LAST_SETT_DATE ELSE C.LAST_SETT_DATE END

        FROM #REPORT_DATA C,  #LAST_SETTLE L  WHERE   UCC = CLTCODE

 

        TRUNCATE TABLE #LAST_SETTLE

 

        EXEC ACCOUNT.DBO.GET_LAST_SETTTLE_DATE

      @FROMDATE,

      'BSE', 'A'

 

 

        UPDATE C SET LAST_SETT_DATE = CASE WHEN CHK_DATE <= CONVERT(DATETIME,REPORT_DATE,105) THEN L.LAST_SETT_DATE ELSE C.LAST_SETT_DATE END

        FROM #REPORT_DATA C,  #LAST_SETTLE L  WHERE   UCC = CLTCODE AND C.LAST_SETT_DATE IN('NA', 'ND', '')

		*/

		--UPDATE	D
		--SET		LAST_SETT_DATE = --CONVERT(VARCHAR,SETT_DATE, 105)
		--CASE WHEN SETT_DATE <= CONVERT(VARCHAR(11), CONVERT(DATETIME,REPORT_DATE, 105), 109) + ' 23:59' THEN CONVERT(VARCHAR,SETT_DATE, 105) ELSE 'NA' END
		--FROM	#REPORT_DATA D,
		--		(
		--			SELECT  PARTY_CODE, SETT_DATE = MAX(SCCS_SETTDATE_LAST) FROM SEBI_PAYOUT (NOLOCK)--, #COLL D
		--			WHERE SCCS_SETTDATE_LAST >= @FROMDATE 
		--			--AND SCCS_SETTDATE_LAST <= @TODATE 
		--			GROUP BY PARTY_CODE
		--		) D1
		--WHERE	UCC = PARTY_CODE

		--UPDATE	D
		--SET		LAST_SETT_DATE = CASE WHEN LAST_SETT_DATE = 'NA' THEN CONVERT(VARCHAR,SETT_DATE, 105) ELSE LAST_SETT_DATE END
		--FROM	#REPORT_DATA D,
		--		(
		--			SELECT  PARTY_CODE, SETT_DATE = MAX(SCCS_SETTDATE_LAST) FROM SEBI_PAYOUT (NOLOCK)--, #COLL D
		--			WHERE SCCS_SETTDATE_LAST < @FROMDATE
		--			GROUP BY PARTY_CODE
		--		) D1
		--WHERE	UCC = PARTY_CODE

UPDATE	D
		SET		LAST_SETT_DATE = --CONVERT(VARCHAR,SETT_DATE, 105)
		CASE WHEN SETT_DATE <= CONVERT(VARCHAR(11), CONVERT(DATETIME,REPORT_DATE, 105), 109) + ' 23:59' THEN CONVERT(VARCHAR,SETT_DATE, 105) ELSE 'NA' END
		FROM	#REPORT_DATA D,
				(
					SELECT  PARTY_CODE, SETT_DATE = MAX(SCCS_SETTDATE_LAST) FROM TBL_SEBI_PAYOUT_CCE_REPORTING (NOLOCK)--, #COLL D
					WHERE SCCS_SETTDATE_LAST >= @FROMDATE 
					--AND SCCS_SETTDATE_LAST <= @TODATE 
					GROUP BY PARTY_CODE
				) D1
		WHERE	UCC = PARTY_CODE

		UPDATE	D
		SET		LAST_SETT_DATE = CASE WHEN LAST_SETT_DATE = 'NA' THEN CONVERT(VARCHAR,SETT_DATE, 105) ELSE LAST_SETT_DATE END
		FROM	#REPORT_DATA D,
				(
					SELECT  PARTY_CODE, SETT_DATE = MAX(SCCS_SETTDATE_LAST) FROM TBL_SEBI_PAYOUT_CCE_REPORTING (NOLOCK)--, #COLL D
					WHERE SCCS_SETTDATE_LAST < @FROMDATE
					GROUP BY PARTY_CODE
				) D1
		WHERE	UCC = PARTY_CODE


			/*START THE CODE ADDITION*/

			--	IF OBJECT_ID('TEMPDB..#GRP_DLETEE', 'U') IS NOT NULL
			--	DROP TABLE #GRP_DLETEE
			--	SELECT UCC, REPORT_DATE , SEGMENT_INDICATOR 
			--	INTO #GRP_DLETEE
			--	FROM #REPORT_DATA 
			--	GROUP BY UCC, REPORT_DATE , SEGMENT_INDICATOR 
			--	HAVING 
			--		SUM(VDT_BAL) = 0 AND SUM(EDT_BAL) = 0 
			--	AND SUM(PEAK_FINANCIAL_LEDGER) = 0 AND SUM(BG) = 0 AND SUM(FDR) = 0 AND SUM(GOV_IND_SEC) = 0
			--	AND SUM(GILT_FUNDS) = 0 AND SUM(EPI_LEDGER)  = 0 AND SUM(POOL_ACCOUNT) = 0 
			--	AND SUM(CHQ_DEPOSITS) = 0 AND SUM(CHQ_ISSUE) = 0 AND SUM(COMM_VALUE) = 0

			--	CREATE INDEX IX_#GRP_DLETEE ON #GRP_DLETEE (UCC, REPORT_DATE ,SEGMENT_INDICATOR) 
     
			--IF OBJECT_ID('TEMPDB..#GRP_DLETEE_1', 'U') IS NOT NULL
			--DROP TABLE #GRP_DLETEE_1
			--SELECT UCC, REPORT_DATE 
			--INTO #GRP_DLETEE_1
			--FROM #REPORT_DATA 
			--GROUP BY   UCC, REPORT_DATE  HAVING SUM(VDT_BAL) = 0 AND SUM(EDT_BAL) = 0 
			--		AND SUM(PEAK_FINANCIAL_LEDGER) = 0 AND SUM(BG) = 0 AND SUM(FDR) = 0 AND SUM(GOV_IND_SEC) = 0
			--		AND SUM(GILT_FUNDS) = 0 AND SUM(EPI_LEDGER)  = 0 AND SUM(POOL_ACCOUNT) = 0 
			--		AND SUM(CHQ_DEPOSITS) = 0 AND SUM(CHQ_ISSUE) = 0 AND SUM(COMM_VALUE) = 0

			--CREATE INDEX IX_#GRP_DLETEE_1 ON #GRP_DLETEE_1 (UCC, REPORT_DATE ) 

			--DELETE R FROM  #REPORT_DATA R
			--	INNER JOIN #GRP_DLETEE R1 ON R.UCC = R1.UCC AND R.REPORT_DATE = R1.REPORT_DATE AND R.SEGMENT_INDICATOR = R1.SEGMENT_INDICATOR
			--	INNER JOIN #GRP_DLETEE_1 R2 ON R.UCC = R2.UCC AND R.REPORT_DATE = R2.REPORT_DATE  
			--	AND EXISTS(SELECT PARTY_CODE FROM #CL_LIST XY WHERE XY.PARTY_CODE = R.UCC)

				/*END CODE ADDITION ON 11 NOV 2022*/

    UPDATE #REPORT_DATA SET CLIENT_PAN='NNNNN1111N'
	WHERE CLIENT_PAN LIKE '%[^0-9A-ZA-Z]%' OR LEN(CLIENT_PAN) <> '10' OR RIGHT(CLIENT_PAN, 1) LIKE '%[^A-ZA-Z]%' OR CLIENT_PAN='NNNNN1111N'

  /* BELOW CONDITION COMMENTED ON 27/03/2023 BASED ON SANDIP MAIL  
	UPDATE #REPORT_DATA SET CLIENT_PAN='NNNNN1111N', UNCLAIMED_CLIENT_FUNDS = 'YES' 
	WHERE CLIENT_PAN LIKE '%[^0-9A-ZA-Z]%' OR LEN(CLIENT_PAN) <> '10' OR RIGHT(CLIENT_PAN, 1) LIKE '%[^A-ZA-Z]%' OR CLIENT_PAN='NNNNN1111N'

	UPDATE A SET UNCLAIMED_CLIENT_FUNDS = 'YES' FROM #REPORT_DATA A WHERE CLIENT_PAN IN 
	(SELECT CLIENT_PAN FROM 
	(SELECT DISTINCT UCC,CLIENT_PAN FROM #REPORT_DATA) A1 GROUP BY CLIENT_PAN HAVING COUNT (*) > 1)

	BELOW CONDITION COMMENTED ON 27/03/2023 BASED ON SANDIP MAIL  */

--DELETE FROM #REPORT_DATA WHERE UCC LIKE '%[^0-9A-ZA-Z]%'
/*NEW CODE START 2022 FEB 09*/
 
 SELECT REPORT_DATE, PARTY_CODE = UCC, EXCHANGE, SEGMENT, MARGIN_REQ
    INTO #MARGIN_BAL 
    FROM (SELECT SNO, REPORT_DATE, UCC, CLIENT_PAN FROM #CLIENT_CASH_DETAILS_TMP WHERE REPORT_DATE BETWEEN @FROMDATE AND @TODATE) C
	               INNER JOIN #CLIENT_CASH_LED_BALANCES D
    ON C.SNO = D.SNO AND MARGIN_REQ <> 0
    
    SELECT REPORT_DATE = PROCESS_DT, PARTY_CODE, EXCHANGE, SEGMENT, COLL = SUM(APPROVED_SEC_CASH_WNCL + APPROVED_SEC_NONCASH_WNCL + APPROVED_SEC_CASH_WCM + APPROVED_SEC_NONCASH_WCM + NONAPPROVED_SEC_RET_WCM)
    INTO #COLL_MARGIN 
    FROM MSAJAG.DBO.CLIENT_COLLATERAL_REPORTING_DETAILS
    WHERE PROCESS_DT BETWEEN @FROMDATE AND @TODATE
    AND APPROVED_SEC_CASH_WNCL + APPROVED_SEC_NONCASH_WNCL + APPROVED_SEC_CASH_WCM + APPROVED_SEC_NONCASH_WCM + NONAPPROVED_SEC_RET_WCM <> 0
    GROUP BY PARTY_CODE, EXCHANGE, SEGMENT, PROCESS_DT
    
    SELECT REPORT_DATE = M.REPORT_DATE, PARTY_CODE = M.PARTY_CODE, EXCHANGE = M.EXCHANGE, SEGMENT = M.SEGMENT, 
    MARGIN_REQ = CASE WHEN ABS(MARGIN_REQ) >  ABS(ISNULL(COLL, 0)) THEN ABS(MARGIN_REQ) - ABS(ISNULL(COLL, 0)) ELSE 0 END
    INTO #MARGIN_SHORTAGE
    FROM #MARGIN_BAL M
	    LEFT OUTER JOIN #COLL_MARGIN C
	    ON M.PARTY_CODE = C.PARTY_CODE
	    AND M.REPORT_DATE = C.REPORT_DATE
	    AND M.EXCHANGE = C.EXCHANGE
	    AND M.SEGMENT = C.SEGMENT
    CREATE TABLE #NET_MARGIN_BALANCE
    (
	    UCC VARCHAR(10),
	    REPORT_DATE DATETIME,
	    TOTAL_MARGIN MONEY
    )

    INSERT INTO #NET_MARGIN_BALANCE
    SELECT UCC, REPORT_DATE = R.REPORT_DATE, TOTAL_MARGIN = CASE WHEN SUM(EDT_BAL) > SUM(ISNULL(M.MARGIN_REQ, 0)) AND SUM(EDT_BAL) > 0 THEN SUM(ISNULL(M.MARGIN_REQ, 0)) ELSE CASE WHEN SUM(EDT_BAL) > 0 THEN SUM(EDT_BAL) ELSE 0 END END
    FROM #REPORT_DATA R LEFT OUTER JOIN #MARGIN_SHORTAGE M ON R.REPORT_DATE = M.REPORT_DATE AND R.UCC = M.PARTY_CODE
    GROUP BY UCC, R.REPORT_DATE
/* LOGIC END  2022-02-09*/


--SELECT * INTO REPORT_DATA_CHK1111 FROM #REPORT_DATA
-- RETURN
 

CREATE TABLE #FINAL_DATA
(
    SNO INT IDENTITY(1, 1),
    FILE_NAMEING VARCHAR(200),
    REPORTDATE VARCHAR(10),
    UCC VARCHAR(10),
    REPORT_DATA VARCHAR(8000)
)

 --SELECT *, RPT_DATE = GETDATE() INTO FINAL_DATA_TOTALCHK FROM #REPORT_DATA (NOLOCK)
 CREATE INDEX #DATE ON #FINAL_DATA(REPORTDATE)
 
/*INSERT INTO #FINAL_DATA
SELECT @FILENAMEHS, CONVERT(VARCHAR(10), CONVERT(DATETIME, @FROMDATE, 109), 105), UCC = '00000', 'TRADING MEMBER PAN,DATE,UNIQUE CLIENT CODE,CLIENT PAN,CLIENT NAME,MTF/ NON MTF INDICATOR,FINANCIAL LEDGER BALANCE-A,FINANCIAL LEDGER BALANCE (CLEAR)-B,PEAK FINANCIAL LEDGER BALANCE (CLEAR)-C,FINANCIAL LEDGER BALANCE-MCX,FINANCIAL LEDGER BALANCE-NCDEX,FINANCIAL LEDGER BALANCE-ICEX,BANK GUARANTEE (BG),FIXED DEPOSIT RECEIPT (FDR),GOVERNMENT OF INDIA SECURITIES (GSEC),GILT FUNDS,CREDIT ENTRY IN LEDGER IN LIEU OF EPI,POOL ACCOUNT,UNCLEARED CHEQUES,VALUE OF COMMODITIES,CASH COLLATERAL FOR MTF POSITIONS,UNCLAIMED/UNSETTLED CLIENT FUNDS,CLIENT BANK ACCOUNT NO.,LAST SETTLEMENT DATE,ES INFORMATION TYPE,VALUE'
--UNION ALL
INSERT INTO #FINAL_DATA
SELECT @FILENAMEHS, CONVERT(VARCHAR(10), REPORT_DATE, 105), UCC, TRADING_PAN + ',' + CONVERT(VARCHAR(10), REPORT_DATE, 105) + ',' + UCC + ',' + CLIENT_PAN + ',' + REPLACE(CLIENT_NAME,',','') + ',' + SEGMENT_INDICATOR
+ ','
+ CONVERT(VARCHAR, SUM(VDT_BAL)) + ',' + CONVERT(VARCHAR, SUM(EDT_BAL)) + ',' + CONVERT(VARCHAR, SUM(PEAK_FINANCIAL_LEDGER)) + ','
+ CONVERT(VARCHAR, SUM(CASE WHEN EXCHANGE = 'MCX' THEN EDT_BAL ELSE 0 END)) + ','
+ CONVERT(VARCHAR, SUM(CASE WHEN EXCHANGE = 'NCX' THEN EDT_BAL ELSE 0 END)) + ','
+ CONVERT(VARCHAR, SUM(CASE WHEN EXCHANGE = 'ICX' THEN EDT_BAL ELSE 0 END)) + ','
+ CONVERT(VARCHAR, SUM(BG)) + ',' + CONVERT(VARCHAR, SUM(FDR)) + ',' + CONVERT(VARCHAR, SUM(GOV_IND_SEC)) + ',' + CONVERT(VARCHAR, SUM(GILT_FUNDS)) + ','
+ CONVERT(VARCHAR, SUM(EPI_LEDGER)) + ',' + CONVERT(VARCHAR, SUM(POOL_ACCOUNT)) + ',' + CONVERT(VARCHAR, SUM(CHQ_DEPOSITS))
+ ',' + CONVERT(VARCHAR, SUM(COMM_VALUE)) + ',' 
+ CONVERT(VARCHAR, MAX(CASH_COLL_MTF_POSITIONS)) + ',' + UNCLAIMED_CLIENT_FUNDS + ',' + CASE WHEN UNCLAIMED_CLIENT_FUNDS = 'YES' THEN @@CLIENT_BANK_ACC ELSE 'NA' END + ',' + CASE WHEN UNCLAIMED_CLIENT_FUNDS = 'YES' THEN 'NA' ELSE CONVERT(VARCHAR, MAX(LAST_SETT_DATE)) END +','
--+ CONVERT(VARCHAR, MAX(LAST_SETT_DATE))
+ ',NA, NA'
FROM #REPORT_DATA
GROUP BY TRADING_PAN, CONVERT(VARCHAR(10), REPORT_DATE, 105), UCC, CLIENT_PAN, CLIENT_NAME, SEGMENT_INDICATOR,UNCLAIMED_CLIENT_FUNDS
ORDER BY CONVERT(VARCHAR(10), REPORT_DATE, 105), UCC
*/

INSERT INTO #FINAL_DATA
SELECT @FILENAMEHS, CONVERT(VARCHAR(10), CONVERT(DATETIME, @FROMDATE, 109), 105), UCC = '00000', 'TRADING MEMBER PAN,DATE,UNIQUE CLIENT CODE,CLIENT PAN,CLIENT NAME,MTF/ NON MTF INDICATOR,FINANCIAL LEDGER BALANCE-A,FINANCIAL LEDGER BALANCE (CLEAR)-B,PEAK FINANCIAL LEDGER BALANCE (CLEAR)-C,FINANCIAL LEDGER BALANCE-MCX,FINANCIAL LEDGER BALANCE-NCDEX,FINANCIAL LEDGER BALANCE-ICEX,BANK GUARANTEE (BG),FIXED DEPOSIT RECEIPT (FDR),GOVERNMENT OF INDIA SECURITIES (GSEC),GILT FUNDS,CREDIT ENTRY IN LEDGER IN LIEU OF EPI,POOL ACCOUNT,UNCLEARED CHEQUES,VALUE OF COMMODITIES,CASH COLLATERAL FOR MTF POSITIONS,UNCLAIMED/UNSETTLED CLIENT FUNDS,CLIENT BANK ACCOUNT NO.,LAST SETTLEMENT DATE,ES INFORMATION TYPE,VALUE'
--UNION ALL
INSERT INTO #FINAL_DATA
SELECT @FILENAMEHS, CONVERT(VARCHAR(10), REPORT_DATE, 105), UCC, TRADING_PAN + ',' + CONVERT(VARCHAR(10), REPORT_DATE, 105) + ',' + UCC + ',' + CLIENT_PAN + ',' + REPLACE(CLIENT_NAME,',','') + ',' + SEGMENT_INDICATOR
+ ','
+ CONVERT(VARCHAR, SUM(VDT_BAL)) + ',' + CONVERT(VARCHAR, SUM(EDT_BAL)) + ',' + CONVERT(VARCHAR, SUM(PEAK_FINANCIAL_LEDGER)) + ','
+ CONVERT(VARCHAR, SUM(CASE WHEN EXCHANGE = 'MCX' THEN VDT_BAL ELSE 0 END)) + ','
+ CONVERT(VARCHAR, SUM(CASE WHEN EXCHANGE = 'NCX' THEN VDT_BAL ELSE 0 END)) + ','
+ CONVERT(VARCHAR, SUM(CASE WHEN EXCHANGE = 'ICX' THEN VDT_BAL ELSE 0 END)) + ','
+ CONVERT(VARCHAR, SUM(BG)) + ',' + CONVERT(VARCHAR, SUM(FDR)) + ',' + CONVERT(VARCHAR, SUM(GOV_IND_SEC)) + ',' + CONVERT(VARCHAR, SUM(GILT_FUNDS)) + ','
+ CONVERT(VARCHAR, SUM(EPI_LEDGER)) + ',' + CONVERT(VARCHAR, SUM(POOL_ACCOUNT)) + ',' + CONVERT(VARCHAR, SUM(CHQ_DEPOSITS))
+ ',' + CONVERT(VARCHAR, SUM(COMM_VALUE)) + ',' 
+ CONVERT(VARCHAR, MAX(CASH_COLL_MTF_POSITIONS)) + ',' + UNCLAIMED_CLIENT_FUNDS + ',' + CASE WHEN UNCLAIMED_CLIENT_FUNDS = 'YES' THEN @@CLIENT_BANK_ACC ELSE 'NA' END + ',' + CASE WHEN UNCLAIMED_CLIENT_FUNDS = 'YES' THEN 'NA' ELSE CONVERT(VARCHAR, MAX(LAST_SETT_DATE)) END 
+ ',NA, NA'
FROM #REPORT_DATA
GROUP BY TRADING_PAN, CONVERT(VARCHAR(10), REPORT_DATE, 105), UCC, CLIENT_PAN, CLIENT_NAME, SEGMENT_INDICATOR,UNCLAIMED_CLIENT_FUNDS
ORDER BY CONVERT(VARCHAR(10), REPORT_DATE, 105), UCC
/* END CHANGE IN QUERY FOR NEW REPORT */

----INSERT INTO #FINAL_DATA
----SELECT @FILENAMEHS, CONVERT(VARCHAR(10), REPORT_DATE, 103), UCC = 'ZZZZ',  TRADING_PAN + ',' + CONVERT(VARCHAR(10), REPORT_DATE, 103) + ',NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,TOTAL CREDIT BALANCE OF ALL CLIENTS,' + CONVERT(VARCHAR, SUM(CASE WHEN VDT_BAL > 0 THEN VDT_BAL ELSE 0 END)) FROM #REPORT_DATA GROUP BY TRADING_PAN,  CONVERT(VARCHAR(10), REPORT_DATE, 103) ORDER BY CONVERT(VARCHAR(10), REPORT_DATE, 103)

----INSERT INTO #FINAL_DATA
----SELECT @FILENAMEHS, CONVERT(VARCHAR(10), REPORT_DATE, 103), UCC = 'ZZZZ',  TRADING_PAN + ',' + CONVERT(VARCHAR(10), REPORT_DATE, 103) + ',NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,TOTAL DEBIT BALANCE OF ALL CLIENTS ,' + CONVERT(VARCHAR, ABS(SUM(CASE WHEN VDT_BAL < 0 THEN VDT_BAL ELSE 0 END))) FROM #REPORT_DATA  GROUP BY TRADING_PAN,  CONVERT(VARCHAR(10), REPORT_DATE, 103) ORDER BY CONVERT(VARCHAR(10), REPORT_DATE, 103)
INSERT INTO #FINAL_DATA
SELECT @FILENAMEHS, CONVERT(VARCHAR(10), REPORT_DATE, 105), UCC = 'ZZZZ',  TRADING_PAN + ',' + CONVERT(VARCHAR(10), REPORT_DATE, 105) + ',NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,TOTAL CR BALANCE,' + CONVERT(VARCHAR, SUM(CASE WHEN EDT_BAL > 0 THEN EDT_BAL ELSE 0 END)) FROM 
(SELECT TRADING_PAN, REPORT_DATE, UCC, CLIENT_PAN, CLIENT_NAME, SEGMENT_INDICATOR, EDT_BAL = SUM(EDT_BAL) FROM #REPORT_DATA GROUP BY TRADING_PAN, REPORT_DATE, UCC, CLIENT_PAN, CLIENT_NAME, SEGMENT_INDICATOR) A 
GROUP BY TRADING_PAN, CONVERT(VARCHAR(10), REPORT_DATE, 105)
ORDER BY CONVERT(VARCHAR(10), REPORT_DATE, 105)

INSERT INTO #FINAL_DATA
SELECT @FILENAMEHS, CONVERT(VARCHAR(10), REPORT_DATE, 105), UCC = 'ZZZZ',  TRADING_PAN + ',' + CONVERT(VARCHAR(10), REPORT_DATE, 105) + ',NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,TOTAL DR BALANCE,' + CONVERT(VARCHAR, SUM(CASE WHEN EDT_BAL < 0 THEN EDT_BAL ELSE 0 END)) FROM 
(SELECT TRADING_PAN, REPORT_DATE, UCC, CLIENT_PAN, CLIENT_NAME, SEGMENT_INDICATOR, EDT_BAL = SUM(EDT_BAL) FROM #REPORT_DATA GROUP BY TRADING_PAN, REPORT_DATE, UCC, CLIENT_PAN, CLIENT_NAME, SEGMENT_INDICATOR) A 
GROUP BY TRADING_PAN, CONVERT(VARCHAR(10), REPORT_DATE, 105)
ORDER BY CONVERT(VARCHAR(10), REPORT_DATE, 105)



--INSERT INTO #FINAL_DATA
--SELECT @FILENAMEHS, CONVERT(VARCHAR(10), REPORT_DATE, 105), UCC = 'ZZZZ',  TRADING_PAN + ',' + CONVERT(VARCHAR(10), REPORT_DATE, 105) + ',NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NON FUNDED BG,0' FROM #REPORT_DATA  GROUP BY TRADING_PAN,  CONVERT(VARCHAR(10), REPORT_DATE, 105) ORDER BY CONVERT(VARCHAR(10), REPORT_DATE, 105)
INSERT INTO #FINAL_DATA
SELECT @FILENAMEHS, CONVERT(VARCHAR(10), CAL_DATES, 105), UCC = 'ZZZZ',  @TRADING_PAN + ',' + CONVERT(VARCHAR(10), CAL_DATES, 105) + ',NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NON FUNDED BG,' + CONVERT(VARCHAR, SUM(ISNULL(BANK_FUND_AMT, 0)) / 2) FROM  #CAL_DATES C LEFT OUTER JOIN ACCOUNT.DBO.TBL_BGDATA BG  ON CAL_DATES BETWEEN FROMDATE AND TODATE
GROUP BY CONVERT(VARCHAR(11), CAL_DATES, 105), CAL_DATES
ORDER BY CONVERT(VARCHAR(11), CAL_DATES, 105)


INSERT INTO #FINAL_DATA
SELECT @FILENAMEHS, CONVERT(VARCHAR(10), REPORT_DATE, 105), UCC = 'ZZZZ',  @TRADING_PAN + ',' + CONVERT(VARCHAR(10), REPORT_DATE, 105) + ',NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,TOTAL CR MARGIN,' + CONVERT(VARCHAR, SUM(TOTAL_MARGIN)) FROM #NET_MARGIN_BALANCE GROUP BY  CONVERT(VARCHAR(10), REPORT_DATE, 105) ORDER BY CONVERT(VARCHAR(10), REPORT_DATE, 105)

INSERT INTO #FINAL_DATA
SELECT @FILENAMEHS, CONVERT(VARCHAR(10), REPORT_DATE, 105), UCC = 'ZZZZ',  TRADING_PAN + ',' + CONVERT(VARCHAR(10), REPORT_DATE, 105) + ',NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,FREE COLL AT CM,0' FROM #REPORT_DATA  GROUP BY TRADING_PAN,  CONVERT(VARCHAR(10), REPORT_DATE, 105) ORDER BY CONVERT(VARCHAR(10), REPORT_DATE, 105)

 

 

SELECT @FILENAMEHS,REPORT_DATA   FROM #FINAL_DATA (NOLOCK)
ORDER BY REPORTDATE, SNO


--SELECT * FROM #FINAL_DATA

GO
