-- Object: PROCEDURE dbo.PROC_SHORT_MARGIN_INSERT
-- Server: 10.253.33.91 | DB: MSAJAG
--------------------------------------------------


CREATE PROC [dbo].[PROC_SHORT_MARGIN_INSERT]
(
	@MARGINDATE	VARCHAR(11),
	@FILENAME	VARCHAR(500),
	@UNAME		VARCHAR(50) = 'AUTO'
)
AS
DECLARE @EXCHANGE	VARCHAR(3),
		@SEGMENT	VARCHAR(7)
		
SET @EXCHANGE = 'NSE'
SET @SEGMENT = 'CAPITAL'

IF @FILENAME LIKE '%C_SA04%'
BEGIN
	SET @EXCHANGE = 'NSE'
	SET @SEGMENT = 'CAPITAL'
END
IF @FILENAME LIKE '%F_SA04%'
BEGIN
	SET @EXCHANGE = 'NSE'
	SET @SEGMENT = 'FUTURES'
END
IF @FILENAME LIKE '%X_SA04%'
BEGIN
	SET @EXCHANGE = 'NSX'
	SET @SEGMENT = 'FUTURES'
END

IF @FILENAME LIKE '%O_SA04%'
BEGIN
	SET @EXCHANGE = 'NCE'
	SET @SEGMENT = 'FUTURES'
END


IF @FILENAME LIKE '%MCX_EODSAR%'
BEGIN
	SET @EXCHANGE = 'MCX'
	SET @SEGMENT = 'FUTURES'
END

IF @FILENAME LIKE '%MCX_INTRASAR%'
BEGIN
	SET @EXCHANGE = 'MCX'
	SET @SEGMENT = 'FUTURES'
END

IF @FILENAME LIKE '%NCCL_COM%'
BEGIN
	SET @EXCHANGE = 'NCX'
	SET @SEGMENT = 'FUTURES'
END

IF @EXCHANGE IN ('NSE','NSX','NCE')
BEGIN
	--UPDATE TBL_SHORT_ALLOC_TMP SET CLIENT_CODE = NEWPARTY_CODE
	--FROM PARTYMAPPING
	--WHERE CLIENT_CODE = OLDPARTY_CODE  

	DELETE FROM TBL_SHORT_ALLOC 
	WHERE MARGINDATE = @MARGINDATE
	AND EXCHANGE = @EXCHANGE AND SEGMENT = @SEGMENT

	INSERT INTO TBL_SHORT_ALLOC 
	SELECT --MARGINDATE=CONVERT(DATETIME,LEFT(MARGINDATE,2)+'/'+RIGHT(LEFT(MARGINDATE,4),2)+'/'+RIGHT(MARGINDATE,4),103),
	MARGINDATE=LEFT (MARGINDATE,11),
		   INDICATOR,EXCHANGE=@EXCHANGE,SEGMENT=@SEGMENT,CLIENT_CODE,MARGIN_REQ,TOTAL_CASH_COLL,
		   TOTAL_NONCASH_COLL,EXCESS_OTHER_SEG,TOTAL_VALUE_COLL,EOD_SHORT_ALLOC,UPLOAD_BY=@UNAME,UPLOAD_ON=GETDATE()
	FROM TBL_SHORT_ALLOC_TMP
END

IF @EXCHANGE = 'MCX' AND @FILENAME LIKE '%MCX_EODSAR%'
BEGIN 
	DELETE FROM TBL_MCX_SHORT_ALLOC 
	WHERE MARGINDATE = @MARGINDATE 

	INSERT INTO TBL_MCX_SHORT_ALLOC 
	SELECT *,UPLOAD_BY=@UNAME,UPLOAD_ON=GETDATE()
	FROM TBL_MCX_SHORT_ALLOC_TMP
END

IF @EXCHANGE = 'MCX' AND @FILENAME LIKE '%MCX_INTRASAR%'
BEGIN 
	DELETE FROM TBL_MCX_SHORT_ALLOC_INTRA 
	WHERE MARGINDATE = @MARGINDATE 

	INSERT INTO TBL_MCX_SHORT_ALLOC_INTRA 
	SELECT MARGINDATE,
		   CMID,
		   TMID,
		   CLIENT_CODE,
		   EOD_SHORT_ALLOC,
		   @FILENAME,
		   UPLOAD_BY=@UNAME,
		   UPLOAD_ON=GETDATE()
	FROM TBL_MCX_SHORT_ALLOC_INTRA_TMP
END

IF @EXCHANGE = 'NCX' AND @FILENAME LIKE '%NCCL_COM%'
BEGIN 
	DELETE FROM TBL_NCX_SHORT_ALLOC_INTRA 
	WHERE MARGINDATE = @MARGINDATE 

	INSERT INTO TBL_NCX_SHORT_ALLOC_INTRA 
	SELECT *,
		   @FILENAME,
		   UPLOAD_BY=@UNAME,
		   UPLOAD_ON=GETDATE()
	FROM TBL_NCX_SHORT_ALLOC_INTRA_TMP
END

GO
