-- Object: PROCEDURE dbo.MIG_CITRUS_TO_CLIENT_DETAILS_EQUITY_suresh1
-- Server: 10.253.33.91 | DB: MSAJAG
--------------------------------------------------



-- DEPLOY AT NSE CM MAIN SERER - MSAJAG DB  
 --  

CREATE PROC [dbo].[MIG_CITRUS_TO_CLIENT_DETAILS_EQUITY_suresh1]  

(  
 @FDATE VARCHAR(11)='',  
 @TDATE VARCHAR(11)=''  
)  
  
--WITH ENCRYPTION  
  
AS  
  
BEGIN  
  
IF @FDATE ='' AND @TDATE =''   
BEGIN  
 SELECT @FDATE = LEFT(MIN(CL_ACTIVATED_ON),11),@TDATE = LEFT(MAX(CL_ACTIVATED_ON),11)  
 FROM ABVSCITRUS.CRMDB_A.DBO.VIEW_CLASS_CLIENT_DETAILS_suresh  
 WHERE DATA_MIGRATE_STAT = 0  
END  
  
CREATE TABLE #DATA  
(  
 [SRNO] [INT] NOT NULL,  
 [CL_CODE] [VARCHAR](10) NOT NULL,  
 [BRANCH_CD] [VARCHAR](10) NULL,  
 [PARTY_CODE] [VARCHAR](10) NOT NULL,  
 [SUB_BROKER] [VARCHAR](10) NOT NULL,  
 [TRADER] [VARCHAR](20) NULL,  
 [LONG_NAME] [VARCHAR](100) NULL,  
 [SHORT_NAME] [VARCHAR](30) NULL,  
 [L_ADDRESS1] [VARCHAR](100) NULL,  
 [L_CITY] [VARCHAR](40) NULL,  
 [L_ADDRESS2] [VARCHAR](100) NULL,  
 [L_STATE] [VARCHAR](50) NULL,  
 [L_ADDRESS3] [VARCHAR](100) NULL,  
 [L_NATION] [VARCHAR](15) NULL,  
 [L_ZIP] [VARCHAR](10) NULL,  
 [PAN_GIR_NO] [VARCHAR](50) NULL,  
 [WARD_NO] [VARCHAR](50) NULL,  
 [SEBI_REGN_NO] [VARCHAR](25) NULL,  
 [RES_PHONE1] [VARCHAR](15) NULL,  
 [RES_PHONE2] [VARCHAR](15) NULL,  
 [OFF_PHONE1] [VARCHAR](15) NULL,  
 [OFF_PHONE2] [VARCHAR](15) NULL,  
 [MOBILE_PAGER] [VARCHAR](40) NULL,  
 [FAX] [VARCHAR](15) NULL,  
 [EMAIL] [VARCHAR](100) NULL,  
 [CL_TYPE] [VARCHAR](3) NOT NULL,  
 [CL_STATUS] [VARCHAR](3) NOT NULL,  
 [FAMILY] [VARCHAR](10) NOT NULL,  
 [REGION] [VARCHAR](20) NULL,  
 [AREA] [VARCHAR](20) NULL,  
 [P_ADDRESS1] [VARCHAR](100) NULL,  
 [P_CITY] [VARCHAR](40) NULL,  
 [P_ADDRESS2] [VARCHAR](100) NULL,  
 [P_STATE] [VARCHAR](50) NULL,  
 [P_ADDRESS3] [VARCHAR](100) NULL,  
 [P_NATION] [VARCHAR](15) NULL,  
 [P_ZIP] [VARCHAR](10) NULL,  
 [P_PHONE] [VARCHAR](15) NULL,  
 [ADDEMAILID] [VARCHAR](230) NULL,  
 [SEX] [CHAR](1) NULL,  
 [DOB] [DATETIME] NULL,  
 [INTRODUCER] [VARCHAR](30) NULL,  
 [APPROVER] [VARCHAR](30) NULL,  
 [INTERACTMODE] [TINYINT] NULL,  
 [PASSPORT_NO] [VARCHAR](30) NULL,  
 [PASSPORT_ISSUED_AT] [VARCHAR](30) NULL,  
 [PASSPORT_ISSUED_ON] [DATETIME] NULL,  
 [PASSPORT_EXPIRES_ON] [DATETIME] NULL,  
 [LICENCE_NO] [VARCHAR](30) NULL,  
 [LICENCE_ISSUED_AT] [VARCHAR](30) NULL,  
 [LICENCE_ISSUED_ON] [DATETIME] NULL,  
 [LICENCE_EXPIRES_ON] [DATETIME] NULL,  
 [RAT_CARD_NO] [VARCHAR](30) NULL,  
 [RAT_CARD_ISSUED_AT] [VARCHAR](30) NULL,  
 [RAT_CARD_ISSUED_ON] [DATETIME] NULL,  
 [VOTERSID_NO] [VARCHAR](30) NULL,  
 [VOTERSID_ISSUED_AT] [VARCHAR](30) NULL,  
 [VOTERSID_ISSUED_ON] [DATETIME] NULL,  
 [IT_RETURN_YR] [VARCHAR](30) NULL,  
 [IT_RETURN_FILED_ON] [DATETIME] NULL,  
 [REGR_NO] [VARCHAR](50) NULL,  
 [REGR_AT] [VARCHAR](50) NULL,  
 [REGR_ON] [DATETIME] NULL,  
 [REGR_AUTHORITY] [VARCHAR](50) NULL,  
 [CLIENT_AGREEMENT_ON] [DATETIME] NULL,  
 [SETT_MODE] [VARCHAR](50) NULL,  
 [DEALING_WITH_OTHER_TM] [VARCHAR](50) NULL,  
 [OTHER_AC_NO] [VARCHAR](50) NULL,  
 [INTRODUCER_ID] [VARCHAR](50) NULL,  
 [INTRODUCER_RELATION] [VARCHAR](50) NULL,  
 [REPATRIAT_BANK] [NUMERIC](18, 0) NULL,  
 [REPATRIAT_BANK_AC_NO] [VARCHAR](30) NULL,  
 [CHK_KYC_FORM] [TINYINT] NULL,  
 [CHK_CORPORATE_DEED] [TINYINT] NULL,  
 [CHK_BANK_CERTIFICATE] [TINYINT] NULL,  
 [CHK_ANNUAL_REPORT] [TINYINT] NULL,  
 [CHK_NETWORTH_CERT] [TINYINT] NULL,  
 [CHK_CORP_DTLS_RECD] [TINYINT] NULL,  
 [BANK_NAME] [VARCHAR](100) NULL,  
 [BRANCH_NAME] [VARCHAR](50) NULL,  
 [AC_TYPE] [VARCHAR](10) NULL,  
 [AC_NUM] [VARCHAR](20) NULL,  
 [DEPOSITORY1] [VARCHAR](7) NULL,  

 [DPID1] [VARCHAR](16) NULL,  

 [CLTDPID1] [VARCHAR](16) NULL,  

 [POA1] [CHAR](1) NULL,  

 [DEPOSITORY2] [VARCHAR](7) NULL,  

 [DPID2] [VARCHAR](16) NULL,  

 [CLTDPID2] [VARCHAR](16) NULL,  

 [POA2] [CHAR](1) NULL,  

 [DEPOSITORY3] [VARCHAR](7) NULL,  

 [DPID3] [VARCHAR](16) NULL,  

 [CLTDPID3] [VARCHAR](16) NULL,  

 [POA3] [CHAR](1) NULL,  

 [REL_MGR] [VARCHAR](10) NULL,  

 [C_GROUP] [VARCHAR](10) NULL,  

 [SBU] [VARCHAR](10) NULL,  

 [STATUS] [CHAR](1) NULL,  

 [IMP_STATUS] [TINYINT] NULL,  

 [MODIFIDEDBY] [VARCHAR](25) NULL,  

 [MODIFIDEDON] [DATETIME] NULL,  

 [BANK_ID] [VARCHAR](20) NULL,  

 [MAPIN_ID] [VARCHAR](12) NULL,  

 [UCC_CODE] [VARCHAR](12) NULL,  

 [MICR_NO] [VARCHAR](10) NULL,  

 [IFSC_CODE] [VARCHAR](20) NULL,  

 [DIRECTOR_NAME] [VARCHAR](500) NULL,  

 [PAYLOCATION] [VARCHAR](20) NULL,  

 [FMCODE] [VARCHAR](10) NULL,  

 [PARENTCODE] [VARCHAR](10) NULL,  

 [PRODUCTCODE] [VARCHAR](2) NULL,  

 [INCOME_SLAB] [VARCHAR](50) NULL,  

 [NETWORTH_SLAB] [VARCHAR](50) NULL,  

 [AUTOFUNDPAYOUT] [INT] NULL,  

 [SEBI_REG_DATE] [DATETIME] NULL,  

 [SEBI_EXP_DATE] [DATETIME] NULL,  

 [PERSON_TAG] [INT] NULL,  

 [COMMODITY_TRADER] [VARCHAR](20) NULL,  

 [CHANNEL_TYPE] [VARCHAR](20) NULL,  

 [DMA_AGREEMENT_DATE] [DATETIME] NULL,  

 [DMA_ACTIVATION_DATE] [DATETIME] NULL,  

 [FO_TRADER] [VARCHAR](20) NULL,  

 [CDS_TRADER] [VARCHAR](20) NULL,  

 [CDS_SUBBROKER] [VARCHAR](10) NULL,  

 [RES_PHONE1_STD] [VARCHAR](10) NULL,  

 [RES_PHONE2_STD] [VARCHAR](10) NULL,  

 [OFF_PHONE1_STD] [VARCHAR](10) NULL,  

 [OFF_PHONE2_STD] [VARCHAR](10) NULL,  

 [P_PHONE_STD] [VARCHAR](10) NULL,  

 [BANKID] [INT] NULL,  

 [VALID_REGION] [VARCHAR](1),  

 [VALID_AREA] [VARCHAR](1),  

 [VALID_TRADER] [VARCHAR](1),  

 [VALID_SUBBROKER] [VARCHAR](1),  

 [VALID_BRANCH] [VARCHAR](1),  

 [VALID_BANK] [VARCHAR](1),  

 [VALID_DPBANK1] [VARCHAR](1),  

 [VALID_DPBANK2] [VARCHAR](1),  

 [VALID_DPBANK3] [VARCHAR](1),  

 [RECVALID] [VARCHAR](1),  

 [OCCUPATION] INT  

)  

                              

INSERT INTO #DATA                                  

SELECT DISTINCT  

 REF_SRNO,CL_CODE,BRANCH_CD,PARTY_CODE,SUB_BROKER,TRADER,  

 LONG_NAME=LEFT(LONG_NAME,100),SHORT_NAME=LEFT(REPLACE(SHORT_NAME, ' NULL ', ''),21),L_ADDRESS1=LEFT(L_ADDRESS1,40),  

 L_CITY=LEFT(L_CITY,40),L_ADDRESS2=LEFT(L_ADDRESS2,40),  

 L_STATE=CASE LEFT(L_STATE,50) WHEN 'GUJARAT' THEN 'GUJARAT' WHEN 'TAMIL NADU' THEN 'TAMILNADU' ELSE LEFT(L_STATE,50) END,  

 L_ADDRESS3=LEFT(L_ADDRESS3,40),L_NATION=LEFT(L_NATION,15),L_ZIP=LEFT(L_ZIP,10),  

 PAN_GIR_NO,WARD_NO,SEBI_REGN_NO=ISNULL(SEBI_REGN_NO,''),RES_PHONE1=LEFT(RES_PHONE1,15),  

 RES_PHONE2=LEFT(RES_PHONE2,15),OFF_PHONE1=LEFT(OFF_PHONE1,15),OFF_PHONE2=LEFT(OFF_PHONE2,15),  

    MOBILE_PAGER=LEFT(MOBILE_PAGER,40),  

 FAX=LEFT(FAX,15),EMAIL=LEFT(EMAIL,100),  

 CL_STATUS,CL_TYPE=(CASE CL_TYPE WHEN 'ROR' THEN 'IND' ELSE CL_TYPE END),FAMILY,REGION,AREA,  

 P_ADDRESS1=LEFT(P_ADDRESS1,100),P_CITY=LEFT(P_CITY,20),  

 P_ADDRESS2=LEFT(P_ADDRESS2,100),P_STATE=CASE LEFT(P_STATE,50) WHEN 'GUJARAT' THEN 'GUJARAT' WHEN 'TAMIL NADU' THEN 'TAMILNADU' ELSE LEFT(P_STATE,50) END,  

 P_ADDRESS3=LEFT(P_ADDRESS3,100),P_NATION=LEFT(P_NATION,15),P_ZIP=LEFT(P_ZIP,10),  

 P_PHONE=LEFT(P_PHONE,15),ADDEMAILID=LEFT(ADDEMAILID,230),  

 SEX=ISNULL(SEX, 'M'),DOB=CONVERT(DATETIME,DOB,103),INTRODUCER=LEFT(INTRODUCER,30),APPROVER,INTERACTMODE,PASSPORT_NO,PASSPORT_ISSUED_AT,  

 PASSPORT_ISSUED_ON,PASSPORT_EXPIRES_ON,LICENCE_NO,LICENCE_ISSUED_AT,  

 LICENCE_ISSUED_ON,LICENCE_EXPIRES_ON,RAT_CARD_NO,RAT_CARD_ISSUED_AT,  

 RAT_CARD_ISSUED_ON,VOTERSID_NO,VOTERSID_ISSUED_AT,VOTERSID_ISSUED_ON,  

 IT_RETURN_YR,IT_RETURN_FILED_ON,REGR_NO,REGR_AT,REGR_ON,REGR_AUTHORITY,  

 CLIENT_AGREEMENT_ON,SETT_MODE,DEALING_WITH_OTHER_TM,OTHER_AC_NO,INTRODUCER_ID,  

 INTRODUCER_RELATION,REPATRIAT_BANK,REPATRIAT_BANK_AC_NO,CHK_KYC_FORM,  

 CHK_CORPORATE_DEED,CHK_BANK_CERTIFICATE,CHK_ANNUAL_REPORT,CHK_NETWORTH_CERT,  

 CHK_CORP_DTLS_RECD,BANK_NAME, BRANCH_NAME = left(BRANCH_NAME,40),AC_TYPE=LEFT(AC_TYPE, 1),AC_NUM,DEPOSITORY1,DPID1,  

 CLTDPID1,POA1,DEPOSITORY2,  

 DPID2 = CASE WHEN CONVERT(VARCHAR, DPID2) = '0' THEN '' ELSE CONVERT(VARCHAR, DPID2) END,CLTDPID2,POA2,DEPOSITORY3,  

 DPID3 = CASE WHEN CONVERT(VARCHAR, DPID3) = '0' THEN '' ELSE CONVERT(VARCHAR, DPID3) END,CLTDPID3, 

 POA3,REL_MGR='RELMGR',C_GROUP,SBU,[STATUS],IMP_STATUS,MODIFIDEDBY,MODIFIDEDON,BANK_ID,  

 MAPIN_ID,UCC_CODE = PARTY_CODE,MICR_NO,IFSC_CODE,DIRECTOR_NAME,  

 PAYLOCATION = '',FMCODE,PARENTCODE=CL_CODE,PRODUCTCODE='00',  

 INCOME_SLAB,NETWORTH_SLAB,AUTOFUNDPAYOUT,SEBI_REG_DATE,SEBI_EXP_DATE,PERSON_TAG,  

 COMMODITY_TRADER,CHANNEL_TYPE,DMA_AGREEMENT_DATE,DMA_ACTIVATION_DATE,FO_TRADER,  

 CDS_TRADER,CDS_SUBBROKER,RES_PHONE1_STD=LEFT(RES_PHONE1_STD,10),RES_PHONE2_STD=LEFT(RES_PHONE2_STD,10),  

 OFF_PHONE1_STD=LEFT(OFF_PHONE1_STD,10),OFF_PHONE2_STD=LEFT(OFF_PHONE2_STD,10),P_PHONE_STD=LEFT(P_PHONE_STD,10),BANKID=0,  

 VALID_REGION = 'N',VALID_AREA = 'N',VALID_TRADER = 'N',VALID_SUBBROKER = 'N',  

 VALID_BRANCH = 'N',VALID_BANK = CASE WHEN AC_NUM ='' THEN 'Y' ELSE 'N' END,  

 VALID_DPBANK1 = CASE WHEN CLTDPID1 ='' THEN 'Y' ELSE 'N' END,  

 VALID_DPBANK2 = CASE WHEN CLTDPID2 ='' THEN 'Y' ELSE 'N' END,  

 VALID_DPBANK3 = CASE WHEN CLTDPID3 ='' THEN 'Y' ELSE 'N' END,  

 RECVALID ='N', OCCUPATION  

FROM   

 ABVSCITRUS.CRMDB_A.DBO.VIEW_CLASS_CLIENT_DETAILS_suresh  

WHERE  

 CL_ACTIVATED_ON BETWEEN @FDATE AND @TDATE + ' 23:59'   
  and cl_code='A110394'

 AND DATA_MIGRATE_STAT = 0  

  

IF (SELECT COUNT(1) FROM #DATA) = 0 RETURN  

  

CREATE TABLE #DATA_BROK   

(  

 [SRNO] [INT] NOT NULL,  

 [CL_CODE] [VARCHAR](10) NOT NULL,  

 [EXCHANGE] [VARCHAR](3) NOT NULL,  

 [SEGMENT] [VARCHAR](7) NOT NULL,  

 [BROK_SCHEME] [TINYINT] NULL,  

 [TRD_BROK] [INT] NULL,  

 [DEL_BROK] [INT] NULL,  

 [SER_TAX] [TINYINT] NULL,  

 [SER_TAX_METHOD] [TINYINT] NULL,  

 [CREDIT_LIMIT] [INT] NOT NULL,  

 [INACTIVE_FROM] [DATETIME] NULL,  

 [PRINT_OPTIONS] [TINYINT] NULL,  

 [NO_OF_COPIES] [INT] NULL,  

 [PARTICIPANT_CODE] [VARCHAR](15) NULL,  

 [CUSTODIAN_CODE] [VARCHAR](50) NULL,  

 [INST_CONTRACT] [CHAR](1) NULL,  

 [ROUND_STYLE] [INT] NULL,  

 [STP_PROVIDER] [VARCHAR](5) NULL,  

 [STP_RP_STYLE] [TINYINT] NULL,  

 [MARKET_TYPE] [INT] NULL,  

 [MULTIPLIER] [INT] NULL,  

 [CHARGED] [INT] NULL,  

 [MAINTENANCE] [INT] NULL,  

 [REQD_BY_EXCH] [INT] NULL,  

 [REQD_BY_BROKER] [INT] NULL,  

 [CLIENT_RATING] [VARCHAR](10) NULL,  

 [DEBIT_BALANCE] [CHAR](1) NULL,  

 [INTER_SETT] [CHAR](1) NULL,  

 [TRD_STT] [MONEY] NULL,  

 [TRD_TRAN_CHRGS] [FLOAT] NULL,  

 [TRD_SEBI_FEES] [MONEY] NULL,  

 [TRD_STAMP_DUTY] [MONEY] NULL,  

 [TRD_OTHER_CHRGS] [MONEY] NULL,  

 [TRD_EFF_DT] [DATETIME] NULL,  

 [DEL_STT] [MONEY] NULL,  

 [DEL_TRAN_CHRGS] [FLOAT] NULL,  

 [DEL_SEBI_FEES] [MONEY] NULL,  

 [DEL_STAMP_DUTY] [MONEY] NULL,  

 [DEL_OTHER_CHRGS] [MONEY] NULL,  

 [DEL_EFF_DT] [DATETIME] NULL,  

 [ROUNDING_METHOD] [VARCHAR](10) NULL,  

 [ROUND_TO_DIGIT] [TINYINT] NULL,  

 [ROUND_TO_PAISE] [INT] NULL,  

 [FUT_BROK] [INT] NULL,  

 [FUT_OPT_BROK] [INT] NULL,  

 [FUT_FUT_FIN_BROK] [INT] NULL,  

 [FUT_OPT_EXC] [INT] NULL,  

 [FUT_BROK_APPLICABLE] [INT] NULL,  

 [FUT_STT] [SMALLINT] NULL,  

 [FUT_TRAN_CHRGS] [SMALLINT] NULL,  

 [FUT_SEBI_FEES] [SMALLINT] NULL,  

 [FUT_STAMP_DUTY] [SMALLINT] NULL,  

 [FUT_OTHER_CHRGS] [SMALLINT] NULL,  

 [STATUS] [CHAR](1) NULL,  

 [MODIFIEDON] [DATETIME] NULL,  

 [MODIFIEDBY] [VARCHAR](25) NULL,  

 [IMP_STATUS] [TINYINT] NULL,  

 [PAY_B3B_PAYMENT] [CHAR](1) NULL,  

 [PAY_BANK_NAME] [VARCHAR](50) NULL,  

 [PAY_BRANCH_NAME] [VARCHAR](50) NULL,  

 [PAY_AC_NO] [VARCHAR](20) NULL,  

 [PAY_PAYMENT_MODE] [CHAR](1) NULL,  

 [BROK_EFF_DATE] [DATETIME] NULL,  

 [INST_TRD_BROK] [INT] NULL,  

 [INST_DEL_BROK] [INT] NULL,  

 [SYSTEMDATE] [DATETIME] NULL,  

 [ACTIVE_DATE] [DATETIME] NULL,  

 [CHECKACTIVECLIENT] [VARCHAR](1) NULL,  

 [DEACTIVE_REMARKS] [VARCHAR](100) NULL,  

 [DEACTIVE_VALUE] [VARCHAR](1) NULL,  

 [VALUE_PACK] [VARCHAR](20) NULL,  

 [VALID_TRD_BROK] [VARCHAR](1),  

 [VALID_DEL_BROK] [VARCHAR](1),  

 [VALID_FUT_BROK] [VARCHAR](1),  

 [VALID_OPT_BROK] [VARCHAR](1),  

 [VALID_FUT_EXP_BROK] [VARCHAR](1),  

 [VALID_OPT_EXC_BROK] [VARCHAR](1),  

 [VALID_VALUEPACK_BROK] [VARCHAR](1),  

 [RECVALID] [VARCHAR](1)  

)  

                       

INSERT INTO #DATA_BROK  

SELECT   

 REF_SRNO,CL_CODE,EXCHANGE,SEGMENT,  

 BROK_SCHEME = (CASE WHEN SEGMENT <> 'CAPITAL'   

         THEN BROK_SCHEME ELSE (CASE WHEN BROK_SCHEME = 1 THEN 2 ELSE BROK_SCHEME END)  

       END),  

 TRD_BROK,DEL_BROK,SER_TAX,SER_TAX_METHOD,CREDIT_LIMIT,INACTIVE_FROM,PRINT_OPTIONS,  

 NO_OF_COPIES,PARTICIPANT_CODE,CUSTODIAN_CODE,INST_CONTRACT,ROUND_STYLE,STP_PROVIDER,STP_RP_STYLE,MARKET_TYPE,MULTIPLIER,CHARGED,  

 MAINTENANCE,REQD_BY_EXCH,REQD_BY_BROKER,CLIENT_RATING,DEBIT_BALANCE,INTER_SETT,TRD_STT,TRD_TRAN_CHRGS,TRD_SEBI_FEES,TRD_STAMP_DUTY,   TRD_OTHER_CHRGS,TRD_EFF_DT,DEL_STT,DEL_TRAN_CHRGS,DEL_SEBI_FEES,DEL_STAMP_DUTY,DEL_OTHER_CHRGS,DEL_EFF_DT,ROUNDING_METHOD, 

 ROUND_TO_DIGIT,ROUND_TO_PAISE,FUT_BROK,FUT_OPT_BROK,FUT_FUT_FIN_BROK,FUT_OPT_EXC,FUT_BROK_APPLICABLE,FUT_STT,FUT_TRAN_CHRGS,  

 FUT_SEBI_FEES,FUT_STAMP_DUTY,FUT_OTHER_CHRGS,[STATUS],MODIFIEDON,MODIFIEDBY,IMP_STATUS,PAY_B3B_PAYMENT,PAY_BANK_NAME='HDFC',PAY_BRANCH_NAME ='MUMBAI',  

 PAY_AC_NO,PAY_PAYMENT_MODE,BROK_EFF_DATE,INST_TRD_BROK,INST_DEL_BROK,SYSTEMDATE,ACTIVE_DATE,CHECKACTIVECLIENT,DEACTIVE_REMARKS,  

 DEACTIVE_VALUE,TRD_VALUE_PACK,  

 VALID_TRD_BROK = 'N',VALID_DEL_BROK = 'N',VALID_FUT_BROK = 'N',VALID_OPT_BROK = 'N',  

 VALID_FUT_EXP_BROK = 'N',VALID_OPT_EXC_BROK = 'N',VALID_VALUEPACK_BROK = 'N',RECVALID = 'N'   

FROM   

 ABVSCITRUS.CRMDB_A.DBO.VIEW_CLASS_CLIENT_BROK_DETAILS_suresh  

WHERE   

 CL_ACTIVATED_ON BETWEEN @FDATE AND @TDATE + ' 23:59'   

 AND DATA_MIGRATE_STAT = 0  
 and cl_code='A110394'

 AND EXCHANGE NOT IN ('NCX','MCX')  
 
 
 
IF (SELECT COUNT(1) FROM #DATA) > 0                                

BEGIN      
 print 'data'   

	/*--------------------------------------- VALIDATIONS STARTS --------------------------------------------------*/            

  ---- VALIDATE REGION ----   

  UPDATE #DATA  

  SET VALID_REGION= 'Y'  

  FROM #DATA AS A, REGION AS B  

  WHERE A.REGION = B.REGIONCODE  

  

  ---- VALIDATE AREA ----  

  UPDATE #DATA   

  SET VALID_AREA = 'Y'   

  FROM #DATA AS A, AREA AS B   

  WHERE A.AREA = B.AREACODE  

    

  ---- VALIDATE TRADER ----  

  UPDATE #DATA  

  SET VALID_TRADER = 'Y'  

  FROM #DATA AS A, BRANCHES AS B  

  WHERE A.TRADER = B.SHORT_NAME  

  AND A.BRANCH_CD = B.BRANCH_CD  

  

 ---- VALIDATE SUBBROKER ----  

 UPDATE #DATA  

 SET VALID_SUBBROKER = 'Y'  

 FROM #DATA AS A, SUBBROKERS AS B  

 WHERE A.SUB_BROKER = B.SUB_BROKER  

                                   

 ---- VALIDATE BRANCH ----  

 UPDATE #DATA   

 SET VALID_BRANCH = 'Y'  

 FROM #DATA AS A, BRANCH AS B   

 WHERE A.BRANCH_CD = B.BRANCH_CODE   

  

 ---- VALIDATE BANK ----  

 UPDATE #DATA   

 SET VALID_BANK = 'Y' /*,BANKID=B.RBI_BANKID  

 FROM #DATA AS A, ACCOUNT.DBO.RBIBANKMASTER AS B   

 WHERE A.BANK_NAME = B.BANK_NAME   

 AND A.BRANCH_NAME = B.BRANCH_NAME   

 AND A.MICR_NO = B.MICR_CODE   

 AND A.IFSC_CODE = ISNUL(B.IFSC_CODE,'')*/  

 WHERE AC_NUM <> ''  

  

 ---- VALIDATE DPBANK ----  

 UPDATE #DATA   

 SET VALID_DPBANK1 = 'Y'   

 FROM #DATA AS A, BANK AS B   

 WHERE A.DPID1 = B.BANKID   

 AND CLTDPID1<> ''                                   

  

 ---- VALIDATE DPBANK ----  

 UPDATE #DATA   

 SET VALID_DPBANK2 = 'Y'   

 FROM #DATA AS A, BANK AS B   

 WHERE A.DPID2 = B.BANKID   

 AND CLTDPID2<> ''                          

                          

 ---- VALIDATE DPBANK ----  

 UPDATE #DATA   

 SET VALID_DPBANK3 = 'Y'   

 FROM #DATA AS A, BANK AS B   

 WHERE A.DPID3 = B.BANKID   

 AND CLTDPID3<> ''  

  

 -- UPDATING VALID RECORD -----  

 UPDATE #DATA    

 SET RECVALID='Y'    

 WHERE  

 VALID_REGION = 'Y'    

 AND VALID_AREA = 'Y'    

 AND VALID_TRADER = 'Y'    

 AND VALID_SUBBROKER = 'Y'    

 AND VALID_BRANCH = 'Y'    

 AND VALID_BANK = 'Y'    

 AND VALID_DPBANK1 = 'Y'   

 AND VALID_DPBANK2 = 'Y'   

 AND VALID_DPBANK3 = 'Y'   

  

 ---------------------------------- NSE CM------------------------------------  

 UPDATE #DATA_BROK SET VALID_TRD_BROK = 'Y', BROK_SCHEME = (CASE WHEN TRD_DEL = 'F' THEN 2 ELSE 0 END)

 FROM BROKTABLE  

 WHERE EXCHANGE ='NSE' AND SEGMENT = 'CAPITAL'  

 AND TABLE_NO = TRD_BROK

 AND LINE_NO = 1

 AND TRD_DEL IN ('F', 'T')

                 

 UPDATE #DATA_BROK SET VALID_DEL_BROK = 'Y'   

 WHERE EXCHANGE ='NSE' AND SEGMENT = 'CAPITAL'  

 AND EXISTS (SELECT TABLE_NO FROM BROKTABLE (NOLOCK) WHERE TABLE_NO = DEL_BROK   

    AND TRD_DEL = 'D')  

                   

 ----------------------------------- BSE CM ------------------------------------

 

 UPDATE #DATA_BROK SET VALID_TRD_BROK = 'Y', BROK_SCHEME = (CASE WHEN TRD_DEL = 'F' THEN 2 ELSE 0 END)

 FROM ANAND.BSEDB_AB.DBO.BROKTABLE WITH(NOLOCK)   

 WHERE EXCHANGE ='BSE' AND SEGMENT = 'CAPITAL'  

 AND TABLE_NO = TRD_BROK

 AND LINE_NO = 1

 AND TRD_DEL IN ('F', 'T')  

               

 UPDATE #DATA_BROK SET VALID_DEL_BROK = 'Y'   

 WHERE EXCHANGE ='BSE' AND SEGMENT = 'CAPITAL'  

 AND EXISTS (SELECT TABLE_NO FROM ANAND.BSEDB_AB.DBO.BROKTABLE WITH(NOLOCK) WHERE TABLE_NO = DEL_BROK   

    AND TRD_DEL = 'D')                   

                   

 ----------------------------------- MCX CM ------------------------------------  

 /*  

 UPDATE #DATA_BROK SET VALID_TRD_BROK = 'Y'   

 WHERE EXCHANGE ='MSX' AND SEGMENT = 'CAPITAL'  

 AND EXISTS (SELECT TABLE_NO FROM MCXDB.DBO.BROKTABLE (NOLOCK) WHERE TABLE_NO = TRD_BROK   

    AND TRD_DEL = CASE WHEN BROK_SCHEME <> 0 THEN 'F' ELSE TRD_DEL END)  

                

 UPDATE #DATA_BROK SET VALID_DEL_BROK = 'Y'   

 WHERE EXCHANGE ='MSX' AND SEGMENT = 'CAPITAL'  

 AND EXISTS (SELECT TABLE_NO FROM MCXDB.DBO.BROKTABLE (NOLOCK) WHERE TABLE_NO = DEL_BROK   

    AND TRD_DEL = 'D')  

    */               

 ----------------------------------- NSEFO ---------------------------------------------- 

 UPDATE #DATA_BROK SET VALID_FUT_BROK = 'Y', BROK_SCHEME = (CASE WHEN TRD_DEL = 'F' THEN 3 ELSE 0 END)
 FROM ANGELFO.NSEFO.DBO.BROKTABLE-- WITH(NOLOCK)   
 WHERE EXCHANGE ='NSE' AND SEGMENT = 'FUTURES'  
 AND TABLE_NO = FUT_BROK
 AND LINE_NO = 1
 AND TRD_DEL IN ('F', 'T')  
 
 UPDATE #DATA_BROK SET VALID_FUT_BROK = 'Y'  
 WHERE EXCHANGE ='NSE' AND SEGMENT = 'FUTURES'  
 ----AND EXISTS (SELECT SP_SCHEME_ID FROM /*[SAN2].*/NSEFO.DBO.BRANCH_SCHEME_MAPPING WITH(NOLOCK) WHERE SP_SCHEME_ID = FUT_BROK)  
 AND VALID_FUT_BROK = 'N'   
  
 UPDATE #DATA_BROK SET VALID_FUT_EXP_BROK = 'Y'   
 WHERE EXCHANGE ='NSE' AND SEGMENT = 'FUTURES'  
 --AND EXISTS (SELECT TABLE_NO FROM /*[SAN2].*/NSEFO.DBO.BROKTABLE WITH(NOLOCK) WHERE TABLE_NO = FUT_FUT_FIN_BROK   
 --   AND TRD_DEL IN ('T','D'))    
      
 UPDATE #DATA_BROK SET VALID_OPT_BROK = 'Y'   
 WHERE EXCHANGE ='NSE' AND SEGMENT = 'FUTURES'  
 ----AND EXISTS (SELECT SP_SCHEME_ID FROM /*[SAN2].*/NSEFO.DBO.BRANCH_SCHEME_MAPPING WITH(NOLOCK) WHERE SP_SCHEME_ID = FUT_OPT_BROK )    
  
 UPDATE #DATA_BROK SET VALID_OPT_EXC_BROK = 'Y'   
 WHERE EXCHANGE ='NSE' AND SEGMENT = 'FUTURES'  
 --AND EXISTS (SELECT SP_SCHEME_ID FROM /*[SAN2].*/NSEFO.DBO.BRANCH_SCHEME_MAPPING WITH(NOLOCK) WHERE SP_SCHEME_ID = FUT_OPT_EXC )    
 --             
 ------------------------------------ BSEFO -----------------------------------------------------------------------  
 
 UPDATE #DATA_BROK SET VALID_FUT_BROK = 'Y', BROK_SCHEME = (CASE WHEN TRD_DEL = 'F' THEN 3 ELSE 0 END)
 FROM ANGELCOMMODITY.BSEFO.DBO.BROKTABLE WITH(NOLOCK)   
 WHERE EXCHANGE ='BSE' AND SEGMENT = 'FUTURES'  
 AND TABLE_NO = FUT_BROK
 AND LINE_NO = 1
 AND TRD_DEL IN ('F', 'T')  
  
 UPDATE #DATA_BROK SET VALID_FUT_BROK = 'Y'  
 WHERE EXCHANGE ='BSE' AND SEGMENT = 'FUTURES'  
 ----AND EXISTS (SELECT SP_SCHEME_ID FROM /*[SAN2].*/NSEFO.DBO.BRANCH_SCHEME_MAPPING WITH(NOLOCK) WHERE SP_SCHEME_ID = FUT_BROK)  
 AND VALID_FUT_BROK = 'N'   
  
 UPDATE #DATA_BROK SET VALID_FUT_EXP_BROK = 'Y'   
 WHERE EXCHANGE ='BSE' AND SEGMENT = 'FUTURES'  
 --AND EXISTS (SELECT TABLE_NO FROM /*[SAN2].*/BSEFO.DBO.BROKTABLE WITH(NOLOCK) WHERE TABLE_NO = FUT_FUT_FIN_BROK   
 --   AND TRD_DEL IN ('T','D'))    
      
 UPDATE #DATA_BROK SET VALID_OPT_BROK = 'Y'   
 WHERE EXCHANGE ='BSE' AND SEGMENT = 'FUTURES'  
 ----AND EXISTS (SELECT SP_SCHEME_ID FROM /*[SAN2].*/NSEFO.DBO.BRANCH_SCHEME_MAPPING WITH(NOLOCK) WHERE SP_SCHEME_ID = FUT_OPT_BROK )    
  
 UPDATE #DATA_BROK SET VALID_OPT_EXC_BROK = 'Y'   
 WHERE EXCHANGE ='BSE' AND SEGMENT = 'FUTURES'  
 --AND EXISTS (SELECT SP_SCHEME_ID FROM /*[SAN2].*/BSEFO.DBO.BRANCH_SCHEME_MAPPING WITH(NOLOCK) WHERE SP_SCHEME_ID = FUT_OPT_EXC )    
 --   
 ------------------------------------- MCX FO --------------------------------------------------------------------  
 /*  
 UPDATE #DATA_BROK SET VALID_FUT_BROK = 'Y'   
 WHERE EXCHANGE ='MFO' AND SEGMENT = 'FUTURES'  
 AND EXISTS (SELECT TABLE_NO FROM /*[SAN2].*/MCXFO.DBO.BROKTABLE WITH(NOLOCK) WHERE TABLE_NO = FUT_BROK   
    AND TRD_DEL = CASE WHEN BROK_SCHEME <> 0 THEN 'F' ELSE TRD_DEL END)  
  
 UPDATE #DATA_BROK SET VALID_FUT_BROK = 'Y'  
 WHERE EXCHANGE ='MFO' AND SEGMENT = 'FUTURES'  
 AND EXISTS (SELECT SP_SCHEME_ID FROM /*[SAN2].*/MCXFO.DBO.BRANCH_SCHEME_MAPPING WITH(NOLOCK) WHERE SP_SCHEME_ID = FUT_BROK)  
 AND VALID_FUT_BROK = 'N'   
  
 UPDATE #DATA_BROK SET VALID_FUT_EXP_BROK = 'Y'   
 WHERE EXCHANGE ='MFO' AND SEGMENT = 'FUTURES'  
 AND EXISTS (SELECT TABLE_NO FROM /*[SAN2].*/MCXFO.DBO.BROKTABLE WITH(NOLOCK) WHERE TABLE_NO = FUT_FUT_FIN_BROK   
    AND TRD_DEL IN ('T','D'))    

     
 UPDATE #DATA_BROK SET VALID_OPT_BROK = 'Y'   
 WHERE EXCHANGE ='MFO' AND SEGMENT = 'FUTURES'  
 AND EXISTS (SELECT SP_SCHEME_ID FROM /*[SAN2].*/MCXFO.DBO.BRANCH_SCHEME_MAPPING WITH(NOLOCK) WHERE SP_SCHEME_ID = FUT_OPT_BROK )    
  
 UPDATE #DATA_BROK SET VALID_OPT_EXC_BROK = 'Y'   
 WHERE EXCHANGE ='MFO' AND SEGMENT = 'FUTURES'  
 AND EXISTS (SELECT SP_SCHEME_ID FROM /*[SAN2].*/MCXFO.DBO.BRANCH_SCHEME_MAPPING WITH(NOLOCK) WHERE SP_SCHEME_ID = FUT_OPT_EXC )    
 */  
 ---------------------------------------- NSE & BSE CURFO -------------------------------------------------------------------  
 UPDATE #DATA_BROK SET VALID_FUT_BROK = 'Y', BROK_SCHEME = (CASE WHEN TRD_DEL = 'F' THEN 3 ELSE 0 END)
 FROM ANGELFO.NSECURFO.DBO.BROKTABLE WITH(NOLOCK)   
 WHERE EXCHANGE ='NSX' AND SEGMENT = 'FUTURES'  
 AND TABLE_NO = FUT_BROK
 AND LINE_NO = 1
 AND TRD_DEL IN ('F', 'T')  
   
 UPDATE #DATA_BROK SET VALID_FUT_BROK = 'Y'   
 WHERE EXCHANGE ='NSX' AND SEGMENT = 'FUTURES'  
 ----AND EXISTS (SELECT SP_SCHEME_ID FROM /*[SAN2].*/NSEFO.DBO.BRANCH_SCHEME_MAPPING WITH(NOLOCK) WHERE SP_SCHEME_ID = FUT_BROK)  
 AND VALID_FUT_BROK = 'N'   
  
 UPDATE #DATA_BROK SET VALID_FUT_EXP_BROK = 'Y'   
 WHERE EXCHANGE ='NSX' AND SEGMENT = 'FUTURES'  
 AND EXISTS (SELECT TABLE_NO FROM /*[SAN2].*/ANGELFO.NSECURFO.DBO.BROKTABLE WITH(NOLOCK) WHERE TABLE_NO = FUT_FUT_FIN_BROK   
    --AND TRD_DEL IN ('T','D')
    )    
      
 UPDATE #DATA_BROK SET VALID_OPT_BROK = 'Y'   
 WHERE EXCHANGE ='NSX' AND SEGMENT = 'FUTURES'  
 ----AND EXISTS (SELECT SP_SCHEME_ID FROM /*[SAN2].*/NSEFO.DBO.BRANCH_SCHEME_MAPPING WITH(NOLOCK) WHERE SP_SCHEME_ID = FUT_OPT_BROK )    
  
 UPDATE #DATA_BROK SET VALID_OPT_EXC_BROK = 'Y'   
 WHERE EXCHANGE ='NSX' AND SEGMENT = 'FUTURES'  


UPDATE #DATA_BROK SET VALID_FUT_BROK = 'Y', BROK_SCHEME = (CASE WHEN TRD_DEL = 'F' THEN 3 ELSE 0 END)

FROM ANGELFO.NSECURFO.DBO.BROKTABLE WITH(NOLOCK)   
 WHERE EXCHANGE ='BSX' AND SEGMENT = 'FUTURES'  
 AND TABLE_NO = FUT_BROK
 AND LINE_NO = 1
 AND TRD_DEL IN ('F', 'T')  
   
 UPDATE #DATA_BROK SET VALID_FUT_BROK = 'Y'   
 WHERE EXCHANGE ='BSX' AND SEGMENT = 'FUTURES'  
 ----AND EXISTS (SELECT SP_SCHEME_ID FROM /*[SAN2].*/NSEFO.DBO.BRANCH_SCHEME_MAPPING WITH(NOLOCK) WHERE SP_SCHEME_ID = FUT_BROK)  
 AND VALID_FUT_BROK = 'N'   
  
 UPDATE #DATA_BROK SET VALID_FUT_EXP_BROK = 'Y'   
 WHERE EXCHANGE ='BSX' AND SEGMENT = 'FUTURES'  
 AND EXISTS (SELECT TABLE_NO FROM /*[SAN2].*/ANGELFO.NSECURFO.DBO.BROKTABLE WITH(NOLOCK) WHERE TABLE_NO = FUT_FUT_FIN_BROK   
    --AND TRD_DEL IN ('T','D')
    )    
      

 UPDATE #DATA_BROK SET VALID_OPT_BROK = 'Y'   

 WHERE EXCHANGE ='BSX' AND SEGMENT = 'FUTURES'  

 ----AND EXISTS (SELECT SP_SCHEME_ID FROM /*[SAN2].*/NSEFO.DBO.BRANCH_SCHEME_MAPPING WITH(NOLOCK) WHERE SP_SCHEME_ID = FUT_OPT_BROK )    

  

 UPDATE #DATA_BROK SET VALID_OPT_EXC_BROK = 'Y'   

 WHERE EXCHANGE ='BSX' AND SEGMENT = 'FUTURES' 

-- AND EXISTS (SELECT SP_SCHEME_ID FROM /*[SAN2].*/ANGELFO.NSEFO.DBO.BRANCH_SCHEME_MAPPING WITH(NOLOCK) WHERE SP_SCHEME_ID = FUT_OPT_EXC )   

  

 --UPDATE #DATA_BROK SET VALID_FUT_BROK = 'Y'   

 --WHERE EXCHANGE ='BSX' AND SEGMENT = 'FUTURES'  

 --AND EXISTS (SELECT TABLE_NO FROM /*[192.168.100.246].*/ANGELCOMMODITY.BSECURFO.DBO.BROKTABLE WITH(NOLOCK) WHERE TABLE_NO = FUT_BROK   

 --   AND TRD_DEL = CASE WHEN BROK_SCHEME <> 0 THEN 'F' ELSE TRD_DEL END)  

  

 --UPDATE #DATA_BROK SET VALID_FUT_BROK = 'Y'   

 --WHERE EXCHANGE ='BSX' AND SEGMENT = 'FUTURES'  

 ------AND EXISTS (SELECT SP_SCHEME_ID FROM /*[192.168.100.246].*/NSEFO.DBO.BRANCH_SCHEME_MAPPING WITH(NOLOCK) WHERE SP_SCHEME_ID = FUT_BROK)  

 --AND VALID_FUT_BROK = 'N'   

  

 --UPDATE #DATA_BROK SET VALID_FUT_EXP_BROK = 'Y'   

 --WHERE EXCHANGE ='BSX' AND SEGMENT = 'FUTURES'  

 --AND EXISTS (SELECT TABLE_NO FROM /*[192.168.100.246].*/ANGELCOMMODITY.BSECURFO.DBO.BROKTABLE WITH(NOLOCK) WHERE TABLE_NO = FUT_FUT_FIN_BROK   

 --   AND TRD_DEL IN ('T','D'))    

      

 --UPDATE #DATA_BROK SET VALID_OPT_BROK = 'Y'   

 --WHERE EXCHANGE ='BSX' AND SEGMENT = 'FUTURES'  

 ------AND EXISTS (SELECT SP_SCHEME_ID FROM /*[192.168.100.246].*/NSEFO.DBO.BRANCH_SCHEME_MAPPING WITH(NOLOCK) WHERE SP_SCHEME_ID = FUT_OPT_BROK )    

  

 --UPDATE #DATA_BROK SET VALID_OPT_EXC_BROK = 'Y'   

 --WHERE EXCHANGE ='BSX' AND SEGMENT = 'FUTURES'  

 ------AND EXISTS (SELECT SP_SCHEME_ID FROM /*[192.168.100.246].*/NSEFO.DBO.BRANCH_SCHEME_MAPPING WITH(NOLOCK) WHERE SP_SCHEME_ID = FUT_OPT_EXC )                

       

 ------------------------------------------------- MCX CURFO -----------------------------------------------------------  

 UPDATE #DATA_BROK SET VALID_FUT_BROK = 'Y', BROK_SCHEME = (CASE WHEN TRD_DEL = 'F' THEN 3 ELSE 0 END)

 FROM ANGELCOMMODITY.MCDXCDS.DBO.BROKTABLE WITH(NOLOCK)   

 WHERE EXCHANGE ='MCD' AND SEGMENT = 'FUTURES'  

 AND TABLE_NO = FUT_BROK

 AND LINE_NO = 1

 AND TRD_DEL IN ('F', 'T')  

   

 UPDATE #DATA_BROK SET VALID_FUT_BROK = 'Y'  

 WHERE EXCHANGE ='MCD' AND SEGMENT = 'FUTURES'  

 ----AND EXISTS (SELECT SP_SCHEME_ID FROM /*[SAN2].*/NSEFO.DBO.BRANCH_SCHEME_MAPPING WITH(NOLOCK) WHERE SP_SCHEME_ID = FUT_BROK)  

 AND VALID_FUT_BROK = 'N'   

  

 UPDATE #DATA_BROK SET VALID_FUT_EXP_BROK = 'Y'   

 WHERE EXCHANGE ='MCD' AND SEGMENT = 'FUTURES'  

 AND EXISTS (SELECT TABLE_NO FROM /*[SAN2].*/ANGELCOMMODITY.MCDXCDS.DBO.BROKTABLE WITH(NOLOCK) WHERE TABLE_NO = FUT_FUT_FIN_BROK   

    --AND TRD_DEL IN ('T','D')

    )    

      

 UPDATE #DATA_BROK SET VALID_OPT_BROK = 'Y'   

 WHERE EXCHANGE ='MCD' AND SEGMENT = 'FUTURES'  

 ----AND EXISTS (SELECT SP_SCHEME_ID FROM /*[SAN2].*/NSEFO.DBO.BRANCH_SCHEME_MAPPING WITH(NOLOCK) WHERE SP_SCHEME_ID = FUT_OPT_BROK )    

  

 UPDATE #DATA_BROK SET VALID_OPT_EXC_BROK = 'Y'   

 WHERE EXCHANGE ='MCD' AND SEGMENT = 'FUTURES'  

 ----AND EXISTS (SELECT SP_SCHEME_ID FROM /*[SAN2].*/NSEFO.DBO.BRANCH_SCHEME_MAPPING WITH(NOLOCK) WHERE SP_SCHEME_ID = FUT_OPT_EXC )   

  

 ------------------------------------------------- PREPAID -----------------------------------------------------------  

 /*UPDATE #DATA_BROK SET VALID_VALUEPACK_BROK = 'Y'   

 WHERE EXISTS (SELECT SCHEME_NO FROM V2_PREPAID_SCHEME WITH(NOLOCK) WHERE SCHEME_NO = VALUE_PACK  

     AND SCHEME_STATUS = 1 )    

 */  

 UPDATE #DATA_BROK SET RECVALID  ='Y'  

 WHERE  

 VALID_TRD_BROK = 'Y' AND  

 VALID_DEL_BROK = 'Y' AND  

 /*AND  

 VALID_VALUEPACK_BROK = 'Y'*/  

 SEGMENT = 'CAPITAL'   

  

 UPDATE #DATA_BROK SET RECVALID = 'Y'  

 WHERE  

 VALID_FUT_BROK = 'Y' AND  

 VALID_OPT_BROK = 'Y' AND  

 VALID_FUT_EXP_BROK = 'Y' AND  

 VALID_OPT_EXC_BROK = 'Y' AND  

 /*AND  

 VALID_VALUEPACK_BROK = 'Y'*/  

 SEGMENT <> 'CAPITAL'  

  

 /*TO REMOVE*/  

 UPDATE #DATA_BROK SET RECVALID  ='Y' WHERE EXCHANGE + SEGMENT IN ('MCDFUTURES', 'BSEFUTURES', 'MFOFUTURES')  

  

 UPDATE #DATA SET RECVALID = 'N'  

 FROM #DATA_BROK  

 WHERE #DATA_BROK.CL_CODE = #DATA.CL_CODE  

 AND #DATA_BROK.RECVALID = 'N'  
 
 
 

   

 /*--------------------------------------- VALIDATIONS END--------------------------------------------------*/  

   

 -- REMOVING THE DUPLICATES, IF ANY  

 DELETE D FROM #DATA D    

 WHERE EXISTS  

 (    

  SELECT DD.CL_CODE,DD.EXCHANGE,DD.SEGMENT FROM  #DATA_BROK DD  

  WHERE  

  D.CL_CODE = DD.CL_CODE  

  GROUP BY  DD.CL_CODE,DD.EXCHANGE,DD.SEGMENT  

  HAVING COUNT(1) >1  

 )  

  

 DELETE D FROM #DATA D    

 WHERE EXISTS  

 (    

  SELECT DD.CL_CODE FROM  #DATA DD  

  WHERE  

  D.CL_CODE = DD.CL_CODE  

  GROUP BY  DD.CL_CODE  

  HAVING COUNT(1) >1  

 )  

  

  

 DELETE D FROM #DATA_BROK D  

 WHERE EXISTS  

 (    

  SELECT DD.CL_CODE,DD.EXCHANGE,DD.SEGMENT FROM  #DATA_BROK DD  

  WHERE  

  D.CL_CODE = DD.CL_CODE  

  GROUP BY  DD.CL_CODE,DD.EXCHANGE,DD.SEGMENT  

  HAVING COUNT(1) >1  

 )  

  
/*
 DELETE #DATA  -- REMOVING DUPLICATE  

 WHERE EXISTS (SELECT CL_CODE FROM CLIENT_DETAILS WHERE CLIENT_DETAILS.CL_CODE = #DATA.CL_CODE)  
*/
   

 DELETE #DATA  

 WHERE NOT EXISTS (SELECT CL_CODE FROM #DATA_BROK WHERE #DATA_BROK.CL_CODE = #DATA.CL_CODE)  

   

 DELETE #DATA_BROK  

 WHERE NOT EXISTS (SELECT CL_CODE FROM #DATA WHERE #DATA_BROK.CL_CODE = #DATA.CL_CODE)  


 DECLARE  

  @CNT INT    

 SELECT @CNT = COUNT(1) FROM #DATA WHERE RECVALID='N'  

 DECLARE @INTBATCHNO INT  

  

 SELECT @INTBATCHNO = ISNULL(MAX(BATCH_NO),0)+1 FROM  

 MIG_CITRUS_TO_CLIENT_LOG (NOLOCK) WHERE IMPORTED_ON BETWEEN LEFT(GETDATE(),11) AND LEFT(GETDATE(),11) + ' 23:59'  

  

  

 IF @CNT > 0  

 BEGIN  

  SELECT 'MISMATCH IN CLIENT_DETAILS & CLIENT_BROK_DETAILS RECORD COUNT'  

  

  INSERT INTO MIG_CITRUS_TO_CLIENT_LOG                  

  SELECT   

   B.CL_CODE ,  

   EXCHANGE,  

   SEGMENT ,  

   RECSTAT = CASE WHEN B.RECVALID='Y' AND A.RECVALID='Y' THEN 'UPDATED' ELSE 'INVALID' END,  

   GETDATE(),  

   @INTBATCHNO,  

   ERRMSG = CASE   

      WHEN B.RECVALID='Y' AND A.RECVALID='Y' THEN ''  

      ELSE  

       CASE WHEN A.VALID_REGION = 'N' THEN 'REGION: ' + A.REGION ELSE '' END +   

       CASE WHEN A.VALID_AREA = 'N' THEN ';AREA: ' + A.AREA ELSE '' END +   

       CASE WHEN A.VALID_TRADER = 'N' THEN ';TRADER: ' + A.TRADER ELSE '' END +   

       CASE WHEN A.VALID_SUBBROKER = 'N' THEN ';SUBBROKER: ' + A.SUB_BROKER ELSE '' END +   

       CASE WHEN VALID_TRD_BROK = 'N' THEN ';TRD BROK: ' + CONVERT(VARCHAR,TRD_BROK)  ELSE '' END +   

       CASE WHEN VALID_DEL_BROK = 'N' THEN ';DEL BROK: ' + CONVERT(VARCHAR,DEL_BROK)  ELSE '' END +   

       CASE WHEN VALID_FUT_BROK = 'N' THEN ';FUT BROK: ' + CONVERT(VARCHAR,FUT_BROK)  ELSE '' END +   

       CASE WHEN VALID_OPT_BROK = 'N' THEN ';OPT BROK: ' + CONVERT(VARCHAR,FUT_OPT_BROK)  ELSE '' END +   

       CASE WHEN VALID_FUT_EXP_BROK = 'N' THEN ';FUT EXP BROK: ' + CONVERT(VARCHAR,FUT_FUT_FIN_BROK)  ELSE '' END +   

       CASE WHEN VALID_OPT_EXC_BROK = 'N' THEN ';OPT EXC BROK: ' + CONVERT(VARCHAR,FUT_OPT_EXC)  ELSE '' END +   

       CASE WHEN VALID_VALUEPACK_BROK = 'N' THEN ';VALUE PACK: ' + CONVERT(VARCHAR,VALUE_PACK)  ELSE '' END +         

       CASE WHEN A.VALID_BANK = 'N' THEN 'BANK: ' + A.AC_NUM ELSE '' END  +  

       CASE WHEN A.VALID_DPBANK1 = 'N' THEN 'DP BANK1: ' + A.CLTDPID1 ELSE '' END  +  

       CASE WHEN A.VALID_DPBANK2 = 'N' THEN 'DP BANK2: ' + A.CLTDPID2 ELSE '' END  +  

       CASE WHEN A.VALID_DPBANK3 = 'N' THEN 'DP BANK3: ' + A.CLTDPID3 ELSE '' END    

          

      END  

  FROM #DATA A,#DATA_BROK B  

  WHERE A.CL_CODE=B.CL_CODE  

  AND (A.RECVALID='N' OR B.RECVALID='N')  

  

  SELECT DISTINCT A.CL_CODE INTO #ERR_CL_CODE FROM #DATA A,#DATA_BROK B  

  WHERE A.CL_CODE=B.CL_CODE  

  AND (A.RECVALID='N' OR B.RECVALID='N')  

  

  DELETE #DATA WHERE EXISTS (SELECT CL_CODE FROM #ERR_CL_CODE WHERE #ERR_CL_CODE.CL_CODE = #DATA.CL_CODE)  

  DELETE #DATA_BROK WHERE EXISTS (SELECT CL_CODE FROM #ERR_CL_CODE WHERE #ERR_CL_CODE.CL_CODE = #DATA_BROK.CL_CODE)  

    

  DROP TABLE #ERR_CL_CODE  

    

  IF (SELECT COUNT(1) FROM #DATA_BROK)=0  

  BEGIN  

   DROP TABLE #DATA  

   DROP TABLE #DATA_BROK    

   RETURN  

  END  

 END  
 



  

 INSERT INTO MIG_CITRUS_TO_CLIENT_LOG                  

 SELECT   

  B.CL_CODE ,  

  EXCHANGE,  

  SEGMENT ,  

  RECSTAT = CASE WHEN B.RECVALID='Y' AND A.RECVALID='Y' THEN 'UPDATED' ELSE 'INVALID' END,  

  GETDATE(),  

  @INTBATCHNO,  

  ERRMSG = CASE   

     WHEN B.RECVALID='Y' AND A.RECVALID='Y' THEN ''  

     ELSE  

      CASE WHEN A.VALID_REGION = 'N' THEN 'REGION: ' + A.REGION ELSE '' END +   

      CASE WHEN A.VALID_AREA = 'N' THEN ';AREA: ' + A.AREA ELSE '' END +   

      CASE WHEN A.VALID_TRADER = 'N' THEN ';TRADER: ' + A.TRADER ELSE '' END +   

      CASE WHEN A.VALID_SUBBROKER = 'N' THEN ';SUBBROKER: ' + A.SUB_BROKER ELSE '' END +   

      CASE WHEN VALID_TRD_BROK = 'N' THEN ';TRD BROK: ' + CONVERT(VARCHAR,TRD_BROK)  ELSE '' END +   

      CASE WHEN VALID_DEL_BROK = 'N' THEN ';DEL BROK: ' + CONVERT(VARCHAR,DEL_BROK)  ELSE '' END +   

      CASE WHEN VALID_FUT_BROK = 'N' THEN ';FUT BROK: ' + CONVERT(VARCHAR,FUT_BROK)  ELSE '' END +   

      CASE WHEN VALID_OPT_BROK = 'N' THEN ';OPT BROK: ' + CONVERT(VARCHAR,FUT_OPT_BROK)  ELSE '' END +   

      CASE WHEN VALID_FUT_EXP_BROK = 'N' THEN ';FUT EXP BROK: ' + CONVERT(VARCHAR,FUT_FUT_FIN_BROK)  ELSE '' END +   

      CASE WHEN VALID_OPT_EXC_BROK = 'N' THEN ';OPT EXC BROK: ' + CONVERT(VARCHAR,FUT_OPT_EXC)  ELSE '' END +   

      CASE WHEN VALID_VALUEPACK_BROK = 'N' THEN ';VALUE PACK: ' + CONVERT(VARCHAR,VALUE_PACK)  ELSE '' END +  

      CASE WHEN A.VALID_BANK = 'N' THEN 'BANK: ' + A.AC_NUM ELSE '' END  +  

      CASE WHEN A.VALID_DPBANK1 = 'N' THEN 'DP BANK1: ' + A.CLTDPID1 ELSE '' END  +  

      CASE WHEN A.VALID_DPBANK2 = 'N' THEN 'DP BANK2: ' + A.CLTDPID2 ELSE '' END  +  

      CASE WHEN A.VALID_DPBANK3 = 'N' THEN 'DP BANK3: ' + A.CLTDPID3 ELSE '' END    

     END  

 FROM #DATA A,#DATA_BROK B  

 WHERE A.CL_CODE=B.CL_CODE  

 
select *from #data

select *from #DATA_BROK
return
 

 INSERT INTO CLIENT_DETAILS  

 (   

  CL_CODE,BRANCH_CD,PARTY_CODE,SUB_BROKER,TRADER,LONG_NAME,SHORT_NAME,L_ADDRESS1,L_CITY,L_ADDRESS2,  

  L_STATE,L_ADDRESS3,L_NATION,L_ZIP,PAN_GIR_NO,WARD_NO,SEBI_REGN_NO,RES_PHONE1,RES_PHONE2,  

  OFF_PHONE1,OFF_PHONE2,MOBILE_PAGER,FAX,EMAIL,CL_TYPE,CL_STATUS,FAMILY,REGION,AREA,P_ADDRESS1,  

  P_CITY,P_ADDRESS2,P_STATE,P_ADDRESS3,P_NATION,P_ZIP,P_PHONE,ADDEMAILID,SEX,DOB,APPROVER,  

  INTERACTMODE,PASSPORT_NO,PASSPORT_ISSUED_AT,PASSPORT_ISSUED_ON,PASSPORT_EXPIRES_ON,LICENCE_NO,  

  LICENCE_ISSUED_AT,LICENCE_ISSUED_ON,LICENCE_EXPIRES_ON,RAT_CARD_NO, RAT_CARD_ISSUED_AT,RAT_CARD_ISSUED_ON,  

  VOTERSID_NO,VOTERSID_ISSUED_AT,VOTERSID_ISSUED_ON,IT_RETURN_YR,IT_RETURN_FILED_ON,REGR_NO, REGR_AT,  

  REGR_ON,REGR_AUTHORITY,CLIENT_AGREEMENT_ON,SETT_MODE,DEALING_WITH_OTHER_TM,OTHER_AC_NO,INTRODUCER_ID,INTRODUCER,  

  INTRODUCER_RELATION,REPATRIAT_BANK,REPATRIAT_BANK_AC_NO,CHK_KYC_FORM,CHK_CORPORATE_DEED,CHK_BANK_CERTIFICATE,  

  CHK_ANNUAL_REPORT,CHK_NETWORTH_CERT,CHK_CORP_DTLS_RECD,DEPOSITORY1,DPID1,CLTDPID1,POA1,DEPOSITORY2,  

  DPID2,CLTDPID2,POA2,DEPOSITORY3,DPID3,CLTDPID3,POA3,REL_MGR,C_GROUP,SBU,[STATUS],IMP_STATUS,  

  BANK_ID,MAPIN_ID,UCC_CODE,FMCODE,MICR_NO,BANK_NAME,BRANCH_NAME,AC_TYPE,AC_NUM,  

  DIRECTOR_NAME,PAYLOCATION,RES_PHONE1_STD,RES_PHONE2_STD,OFF_PHONE1_STD,OFF_PHONE2_STD,P_PHONE_STD,
  MODIFIDEDBY,MODIFIDEDON,PARENTCODE,PRODUCTCODE  

 )  

 SELECT DISTINCT  

  CL_CODE,BRANCH_CD,PARTY_CODE,SUB_BROKER,TRADER,LONG_NAME,

  SHORT_NAME= REPLACE(REPLACE(SHORT_NAME, 'NULL', ''), '  ', ''),L_ADDRESS1,L_CITY,L_ADDRESS2,  

  L_STATE,L_ADDRESS3,L_NATION,L_ZIP,PAN_GIR_NO,WARD_NO,SEBI_REGN_NO,RES_PHONE1,RES_PHONE2,  

  OFF_PHONE1,OFF_PHONE2,MOBILE_PAGER,FAX,EMAIL,CL_TYPE,CL_STATUS,FAMILY,REGION,AREA,P_ADDRESS1,  

  P_CITY,P_ADDRESS2,P_STATE,LEFT(P_ADDRESS3, 50),P_NATION,P_ZIP,P_PHONE,ADDEMAILID,SEX,DOB,APPROVER,  

  INTERACTMODE,PASSPORT_NO,PASSPORT_ISSUED_AT,PASSPORT_ISSUED_ON,PASSPORT_EXPIRES_ON,LICENCE_NO,  

  LICENCE_ISSUED_AT,LICENCE_ISSUED_ON,LICENCE_EXPIRES_ON,RAT_CARD_NO, RAT_CARD_ISSUED_AT,RAT_CARD_ISSUED_ON,  

  VOTERSID_NO,VOTERSID_ISSUED_AT,VOTERSID_ISSUED_ON,IT_RETURN_YR,IT_RETURN_FILED_ON,REGR_NO, REGR_AT,  

  REGR_ON,REGR_AUTHORITY,CLIENT_AGREEMENT_ON,SETT_MODE,DEALING_WITH_OTHER_TM,OTHER_AC_NO,INTRODUCER_ID,INTRODUCER,  

  INTRODUCER_RELATION,REPATRIAT_BANK,REPATRIAT_BANK_AC_NO,CHK_KYC_FORM,CHK_CORPORATE_DEED,CHK_BANK_CERTIFICATE,  

  CHK_ANNUAL_REPORT,CHK_NETWORTH_CERT,CHK_CORP_DTLS_RECD,DEPOSITORY1,DPID1,CLTDPID1,POA1,DEPOSITORY2,  

  DPID2,CLTDPID2,POA2,DEPOSITORY3,DPID3,CLTDPID3,POA3,REL_MGR,C_GROUP,SBU,[STATUS],IMP_STATUS,  

  BANK_ID,MAPIN_ID,UCC_CODE,FMCODE,MICR_NO,BANK_NAME,BRANCH_NAME,AC_TYPE,AC_NUM,  

  DIRECTOR_NAME,PAYLOCATION,RES_PHONE1_STD,RES_PHONE2_STD,OFF_PHONE1_STD,OFF_PHONE2_STD,P_PHONE_STD,
  'CITRUS',MODIFIDEDON,PARENTCODE,PRODUCTCODE 

 FROM #DATA WHERE RECVALID='Y'  

 AND EXISTS (SELECT TOP 1 * FROM #DATA_BROK WHERE #DATA_BROK.CL_CODE = #DATA.CL_CODE)  

 AND NOT EXISTS (SELECT CL_CODE FROM CLIENT_DETAILS WHERE CLIENT_DETAILS.CL_CODE = #DATA.CL_CODE)

update client_details set 	cl_code	=	isnull(	cl_code	,'')	,

	branch_cd	=	isnull(	branch_cd	,'')	,

	party_code	=	isnull(	party_code	,'')	,

	sub_broker	=	isnull(	sub_broker	,'')	,

	trader	=	isnull(	trader	,'')	,

	long_name	=	isnull(	long_name	,'')	,

	short_name	=	isnull(	short_name	,'')	,

	l_address1	=	isnull(	l_address1	,'')	,

	l_city	=	isnull(	l_city	,'')	,

	l_address2	=	isnull(	l_address2	,'')	,

	l_state	=	isnull(	l_state	,'')	,

	l_address3	=	isnull(	l_address3	,'')	,

	l_nation	=	isnull(	l_nation	,'')	,

	l_zip	=	isnull(	l_zip	,'')	,

	pan_gir_no	=	isnull(	pan_gir_no	,'')	,

	ward_no	=	isnull(	ward_no	,'')	,

	sebi_regn_no	=	isnull(	sebi_regn_no	,'')	,

	res_phone1	=	isnull(	res_phone1	,'')	,

	res_phone2	=	isnull(	res_phone2	,'')	,

	off_phone1	=	isnull(	off_phone1	,'')	,

	off_phone2	=	isnull(	off_phone2	,'')	,

	mobile_pager	=	isnull(	mobile_pager	,''),

	fax	=	isnull(	fax	,'')	,

	email	=	isnull(	email	,'')	,

	cl_type	=	isnull(	cl_type	,'')	,

	cl_status	=	isnull(	cl_status	,'')	,

	family	=	isnull(	family	,'')	,

	region	=	isnull(	region	,'')	,

	area	=	isnull(	area	,'')	,

	p_address1	=	isnull(	p_address1	,'')	,

	p_city	=	isnull(	p_city	,'')	,

	p_address2	=	isnull(	p_address2	,'')	,

	p_state	=	isnull(	p_state	,'')	,

	p_address3	=	isnull(	p_address3	,'')	,

	p_nation	=	isnull(	p_nation	,'')	,

	p_zip	=	isnull(	p_zip	,'')	,

	p_phone	=	isnull(	p_phone	,'')	,

	addemailid	=	isnull(	addemailid	,'')	,

	sex	=	isnull(	sex	,'')	,

	dob	=	isnull(	dob	,'')	,

	introducer	=	isnull(	introducer	,'')	,

	approver	=	isnull(	approver	,'')	,

	interactmode	=	isnull(	interactmode	,'')	,

	passport_no	=	isnull(	passport_no	,'')	,

	passport_issued_at	=	isnull(	passport_issued_at	,'')	,

	passport_issued_on	=	isnull(	passport_issued_on	,'')	,

	passport_expires_on	=	isnull(	passport_expires_on	,'')	,

	licence_no	=	isnull(	licence_no	,'')	,

	licence_issued_at	=	isnull(	licence_issued_at	,'')	,

	licence_issued_on	=	isnull(	licence_issued_on	,'')	,

	licence_expires_on	=	isnull(	licence_expires_on	,'')	,

	rat_card_no	=	isnull(	rat_card_no	,'')	,

	rat_card_issued_at	=	isnull(	rat_card_issued_at	,'')	,

	rat_card_issued_on	=	isnull(	rat_card_issued_on	,'')	,

	votersid_no	=	isnull(	votersid_no	,'')	,

	votersid_issued_at	=	isnull(	votersid_issued_at	,'')	,

	votersid_issued_on	=	isnull(	votersid_issued_on	,'')	,

	it_return_yr	=	isnull(	it_return_yr	,'')	,

	it_return_filed_on	=	isnull(	it_return_filed_on	,'')	,

	regr_no	=	isnull(	regr_no	,'')	,

	regr_at	=	isnull(	regr_at	,'')	,

	regr_on	=	isnull(	regr_on	,'')	,

	regr_authority	=	isnull(	regr_authority	,'')	,

	client_agreement_on	=	isnull(	client_agreement_on	,'')	,

	sett_mode	=	isnull(	sett_mode	,'')	,

	dealing_with_other_tm	=	isnull(	dealing_with_other_tm	,'')	,

	other_ac_no	=	isnull(	other_ac_no	,'')	,

	introducer_id	=	isnull(	introducer_id	,'')	,

	introducer_relation	=	isnull(	introducer_relation	,'')	,

	repatriat_bank	=	isnull(	repatriat_bank	,'0')	,

	repatriat_bank_ac_no	=	isnull(	repatriat_bank_ac_no	,'')	,

	chk_kyc_form	=	isnull(	chk_kyc_form	,'')	,

	chk_corporate_deed	=	isnull(	chk_corporate_deed	,'')	,

	chk_bank_certificate	=	isnull(	chk_bank_certificate	,'')	,

	chk_annual_report	=	isnull(	chk_annual_report	,'')	,

	chk_networth_cert	=	isnull(	chk_networth_cert	,'')	,

	chk_corp_dtls_recd	=	isnull(	chk_corp_dtls_recd	,'')	,

	Bank_Name	=	isnull(	Bank_Name	,'')	,

	Branch_Name	=	isnull(	Branch_Name	,'')	,

	AC_Type	=	isnull(	AC_Type	,'')	,

	AC_Num	=	isnull(	AC_Num	,'')	,

	Depository1	=	isnull(	Depository1	,'')	,

	DpId1	=	isnull(	DpId1	,'')	,

	CltDpId1	=	isnull(	CltDpId1	,'')	,

	Poa1	=	isnull(	Poa1	,'')	,

	Depository2	=	isnull(	Depository2	,'')	,

	DpId2	=	isnull(	DpId2	,'')	,

	CltDpId2	=	isnull(	CltDpId2	,'')	,

	Poa2	=	isnull(	Poa2	,'')	,

	Depository3	=	isnull(	Depository3	,'')	,

	DpId3	=	isnull(	DpId3	,'')	,

	CltDpId3	=	isnull(	CltDpId3	,'')	,

	Poa3	=	isnull(	Poa3	,'')	,

	rel_mgr	=	isnull(	rel_mgr	,'')	,

	c_group	=	isnull(	c_group	,'')	,

	sbu	=	isnull(	sbu	,'')	,

	Status	=	isnull(	Status	,'')	,

	Imp_Status	=	isnull(	Imp_Status	,'0')	,

	ModifidedBy	=	isnull(	ModifidedBy	,'')	,

	ModifidedOn	=	isnull(	ModifidedOn	,'')	,

	Bank_id	=	isnull(	Bank_id	,'0')	,

	Mapin_id	=	isnull(	Mapin_id	,'')	,

	UCC_Code	=	isnull(	UCC_Code	,'')	,

	Micr_No	=	isnull(	Micr_No	,'')	,

	Director_name	=	isnull(	Director_name	,'')	,

	paylocation	=	isnull(	paylocation	,'')	,

	FMCode	=	isnull(	FMCode	,'')	,

	INCOME_SLAB	=	isnull(	INCOME_SLAB	,'')	,

	NETWORTH_SLAB	=	isnull(	NETWORTH_SLAB	,'')	,

	PARENTCODE	=	isnull(	PARENTCODE	,'')	,

	PRODUCTCODE	=	isnull(	PRODUCTCODE	,'')	,

	RES_PHONE1_STD	=	isnull(	RES_PHONE1_STD	,'')	,

	RES_PHONE2_STD	=	isnull(	RES_PHONE2_STD	,'')	,

	OFF_PHONE1_STD	=	isnull(	OFF_PHONE1_STD	,'')	,

	OFF_PHONE2_STD	=	isnull(	OFF_PHONE2_STD	,'')	,

	P_PHONE_STD	=	isnull(	P_PHONE_STD	,'')	 

	where EXISTS (SELECT TOP 1 * FROM #DATA WHERE client_details.CL_CODE = #DATA.CL_CODE) 
	 
/*
 INSERT INTO ABVSCITRUS.CRMDB_A.DBO.MIG_CLIENT_DETAILS  

 (   

  CL_CODE,BRANCH_CD,PARTY_CODE,SUB_BROKER,TRADER,LONG_NAME,SHORT_NAME,L_ADDRESS1,L_CITY,L_ADDRESS2,  

  L_STATE,L_ADDRESS3,L_NATION,L_ZIP,PAN_GIR_NO,WARD_NO,SEBI_REGN_NO,RES_PHONE1,RES_PHONE2,  

  OFF_PHONE1,OFF_PHONE2,MOBILE_PAGER,FAX,EMAIL,CL_TYPE,CL_STATUS,FAMILY,REGION,AREA,P_ADDRESS1,  

  P_CITY,P_ADDRESS2,P_STATE,P_ADDRESS3,P_NATION,P_ZIP,P_PHONE,ADDEMAILID,SEX,DOB,APPROVER,  

  INTERACTMODE,PASSPORT_NO,PASSPORT_ISSUED_AT,PASSPORT_ISSUED_ON,PASSPORT_EXPIRES_ON,LICENCE_NO,  

  LICENCE_ISSUED_AT,LICENCE_ISSUED_ON,LICENCE_EXPIRES_ON,RAT_CARD_NO, RAT_CARD_ISSUED_AT,RAT_CARD_ISSUED_ON,  

  VOTERSID_NO,VOTERSID_ISSUED_AT,VOTERSID_ISSUED_ON,IT_RETURN_YR,IT_RETURN_FILED_ON,REGR_NO, REGR_AT,  

  REGR_ON,REGR_AUTHORITY,CLIENT_AGREEMENT_ON,SETT_MODE,DEALING_WITH_OTHER_TM,OTHER_AC_NO,INTRODUCER_ID,INTRODUCER,  

  INTRODUCER_RELATION,REPATRIAT_BANK,REPATRIAT_BANK_AC_NO,CHK_KYC_FORM,CHK_CORPORATE_DEED,CHK_BANK_CERTIFICATE,  

  CHK_ANNUAL_REPORT,CHK_NETWORTH_CERT,CHK_CORP_DTLS_RECD,DEPOSITORY1,DPID1,CLTDPID1,POA1,DEPOSITORY2,  

  DPID2,CLTDPID2,POA2,DEPOSITORY3,DPID3,CLTDPID3,POA3,REL_MGR,C_GROUP,SBU,[STATUS],IMP_STATUS,  

  BANK_ID,MAPIN_ID,UCC_CODE,FMCODE,MICR_NO,BANK_NAME,BRANCH_NAME,AC_TYPE,AC_NUM,  

  DIRECTOR_NAME,PAYLOCATION,RES_PHONE1_STD,RES_PHONE2_STD,OFF_PHONE1_STD,OFF_PHONE2_STD,P_PHONE_STD,
  MODIFIDEDBY,MODIFIDEDON,PARENTCODE,PRODUCTCODE  

 )  

 SELECT DISTINCT  

  CL_CODE,BRANCH_CD,PARTY_CODE,SUB_BROKER,TRADER,LONG_NAME,

  SHORT_NAME= REPLACE(REPLACE(SHORT_NAME, 'NULL', ''), '  ', ''),L_ADDRESS1,L_CITY,L_ADDRESS2,  

  L_STATE,L_ADDRESS3,L_NATION,L_ZIP,PAN_GIR_NO,WARD_NO,SEBI_REGN_NO,RES_PHONE1,RES_PHONE2,  

  OFF_PHONE1,OFF_PHONE2,MOBILE_PAGER,FAX,EMAIL,CL_TYPE,CL_STATUS,FAMILY,REGION,AREA,P_ADDRESS1,  

  P_CITY,P_ADDRESS2,P_STATE,LEFT(P_ADDRESS3, 50),P_NATION,P_ZIP,P_PHONE,ADDEMAILID,SEX,DOB,APPROVER,  

  INTERACTMODE,PASSPORT_NO,PASSPORT_ISSUED_AT,PASSPORT_ISSUED_ON,PASSPORT_EXPIRES_ON,LICENCE_NO,  

  LICENCE_ISSUED_AT,LICENCE_ISSUED_ON,LICENCE_EXPIRES_ON,RAT_CARD_NO, RAT_CARD_ISSUED_AT,RAT_CARD_ISSUED_ON,  

  VOTERSID_NO,VOTERSID_ISSUED_AT,VOTERSID_ISSUED_ON,IT_RETURN_YR,IT_RETURN_FILED_ON,REGR_NO, REGR_AT,  

  REGR_ON,REGR_AUTHORITY,CLIENT_AGREEMENT_ON,SETT_MODE,DEALING_WITH_OTHER_TM,OTHER_AC_NO,INTRODUCER_ID,INTRODUCER,  

  INTRODUCER_RELATION,REPATRIAT_BANK,REPATRIAT_BANK_AC_NO,CHK_KYC_FORM,CHK_CORPORATE_DEED,CHK_BANK_CERTIFICATE,  

  CHK_ANNUAL_REPORT,CHK_NETWORTH_CERT,CHK_CORP_DTLS_RECD,DEPOSITORY1,DPID1,CLTDPID1,POA1,DEPOSITORY2,  

  DPID2,CLTDPID2,POA2,DEPOSITORY3,DPID3,CLTDPID3,POA3,REL_MGR,C_GROUP,SBU,[STATUS],IMP_STATUS,  

  BANK_ID,MAPIN_ID,UCC_CODE,FMCODE,MICR_NO,BANK_NAME,BRANCH_NAME,AC_TYPE,AC_NUM,  

  DIRECTOR_NAME,PAYLOCATION,RES_PHONE1_STD,RES_PHONE2_STD,OFF_PHONE1_STD,OFF_PHONE2_STD,P_PHONE_STD,
  'CITRUS',MODIFIDEDON,PARENTCODE,PRODUCTCODE 

 FROM #DATA WHERE RECVALID='Y'  

 AND EXISTS (SELECT TOP 1 * FROM #DATA_BROK WHERE #DATA_BROK.CL_CODE = #DATA.CL_CODE)  

 AND NOT EXISTS (SELECT CL_CODE FROM ABVSCITRUS.CRMDB_A.DBO.MIG_CLIENT_DETAILS M WHERE M.CL_CODE = #DATA.CL_CODE)

update M 
    set 	cl_code	=	isnull(	cl_code	,'')	,

	branch_cd	=	isnull(	branch_cd	,'')	,

	party_code	=	isnull(	party_code	,'')	,

	sub_broker	=	isnull(	sub_broker	,'')	,

	trader	=	isnull(	trader	,'')	,

	long_name	=	isnull(	long_name	,'')	,

	short_name	=	isnull(	short_name	,'')	,

	l_address1	=	isnull(	l_address1	,'')	,

	l_city	=	isnull(	l_city	,'')	,

	l_address2	=	isnull(	l_address2	,'')	,

	l_state	=	isnull(	l_state	,'')	,

	l_address3	=	isnull(	l_address3	,'')	,

	l_nation	=	isnull(	l_nation	,'')	,

	l_zip	=	isnull(	l_zip	,'')	,

	pan_gir_no	=	isnull(	pan_gir_no	,'')	,

	ward_no	=	isnull(	ward_no	,'')	,

	sebi_regn_no	=	isnull(	sebi_regn_no	,'')	,

	res_phone1	=	isnull(	res_phone1	,'')	,

	res_phone2	=	isnull(	res_phone2	,'')	,

	off_phone1	=	isnull(	off_phone1	,'')	,

	off_phone2	=	isnull(	off_phone2	,'')	,

	mobile_pager	=	isnull(	mobile_pager	,''),

	fax	=	isnull(	fax	,'')	,

	email	=	isnull(	email	,'')	,

	cl_type	=	isnull(	cl_type	,'')	,

	cl_status	=	isnull(	cl_status	,'')	,

	family	=	isnull(	family	,'')	,

	region	=	isnull(	region	,'')	,

	area	=	isnull(	area	,'')	,

	p_address1	=	isnull(	p_address1	,'')	,

	p_city	=	isnull(	p_city	,'')	,

	p_address2	=	isnull(	p_address2	,'')	,

	p_state	=	isnull(	p_state	,'')	,

	p_address3	=	isnull(	p_address3	,'')	,

	p_nation	=	isnull(	p_nation	,'')	,

	p_zip	=	isnull(	p_zip	,'')	,

	p_phone	=	isnull(	p_phone	,'')	,

	addemailid	=	isnull(	addemailid	,'')	,

	sex	=	isnull(	sex	,'')	,

	dob	=	isnull(	dob	,'')	,

	introducer	=	isnull(	introducer	,'')	,

	approver	=	isnull(	approver	,'')	,

	interactmode	=	isnull(	interactmode	,'')	,

	passport_no	=	isnull(	passport_no	,'')	,

	passport_issued_at	=	isnull(	passport_issued_at	,'')	,

	passport_issued_on	=	isnull(	passport_issued_on	,'')	,

	passport_expires_on	=	isnull(	passport_expires_on	,'')	,

	licence_no	=	isnull(	licence_no	,'')	,

	licence_issued_at	=	isnull(	licence_issued_at	,'')	,

	licence_issued_on	=	isnull(	licence_issued_on	,'')	,

	licence_expires_on	=	isnull(	licence_expires_on	,'')	,

	rat_card_no	=	isnull(	rat_card_no	,'')	,

	rat_card_issued_at	=	isnull(	rat_card_issued_at	,'')	,

	rat_card_issued_on	=	isnull(	rat_card_issued_on	,'')	,

	votersid_no	=	isnull(	votersid_no	,'')	,

	votersid_issued_at	=	isnull(	votersid_issued_at	,'')	,

	votersid_issued_on	=	isnull(	votersid_issued_on	,'')	,

	it_return_yr	=	isnull(	it_return_yr	,'')	,

	it_return_filed_on	=	isnull(	it_return_filed_on	,'')	,

	regr_no	=	isnull(	regr_no	,'')	,

	regr_at	=	isnull(	regr_at	,'')	,

	regr_on	=	isnull(	regr_on	,'')	,

	regr_authority	=	isnull(	regr_authority	,'')	,

	client_agreement_on	=	isnull(	client_agreement_on	,'')	,

	sett_mode	=	isnull(	sett_mode	,'')	,

	dealing_with_other_tm	=	isnull(	dealing_with_other_tm	,'')	,

	other_ac_no	=	isnull(	other_ac_no	,'')	,

	introducer_id	=	isnull(	introducer_id	,'')	,

	introducer_relation	=	isnull(	introducer_relation	,'')	,

	repatriat_bank	=	isnull(	repatriat_bank	,'0')	,

	repatriat_bank_ac_no	=	isnull(	repatriat_bank_ac_no	,'')	,

	chk_kyc_form	=	isnull(	chk_kyc_form	,'')	,

	chk_corporate_deed	=	isnull(	chk_corporate_deed	,'')	,

	chk_bank_certificate	=	isnull(	chk_bank_certificate	,'')	,

	chk_annual_report	=	isnull(	chk_annual_report	,'')	,

	chk_networth_cert	=	isnull(	chk_networth_cert	,'')	,

	chk_corp_dtls_recd	=	isnull(	chk_corp_dtls_recd	,'')	,

	Bank_Name	=	isnull(	Bank_Name	,'')	,

	Branch_Name	=	isnull(	Branch_Name	,'')	,

	AC_Type	=	isnull(	AC_Type	,'')	,

	AC_Num	=	isnull(	AC_Num	,'')	,

	Depository1	=	isnull(	Depository1	,'')	,

	DpId1	=	isnull(	DpId1	,'')	,

	CltDpId1	=	isnull(	CltDpId1	,'')	,

	Poa1	=	isnull(	Poa1	,'')	,

	Depository2	=	isnull(	Depository2	,'')	,

	DpId2	=	isnull(	DpId2	,'')	,

	CltDpId2	=	isnull(	CltDpId2	,'')	,

	Poa2	=	isnull(	Poa2	,'')	,

	Depository3	=	isnull(	Depository3	,'')	,

	DpId3	=	isnull(	DpId3	,'')	,

	CltDpId3	=	isnull(	CltDpId3	,'')	,

	Poa3	=	isnull(	Poa3	,'')	,

	rel_mgr	=	isnull(	rel_mgr	,'')	,

	c_group	=	isnull(	c_group	,'')	,

	sbu	=	isnull(	sbu	,'')	,

	Status	=	isnull(	Status	,'')	,

	Imp_Status	=	isnull(	Imp_Status	,'0')	,

	ModifidedBy	=	isnull(	ModifidedBy	,'')	,

	ModifidedOn	=	isnull(	ModifidedOn	,'')	,

	Bank_id	=	isnull(	Bank_id	,'0')	,

	Mapin_id	=	isnull(	Mapin_id	,'')	,

	UCC_Code	=	isnull(	UCC_Code	,'')	,

	Micr_No	=	isnull(	Micr_No	,'')	,

	Director_name	=	isnull(	Director_name	,'')	,

	paylocation	=	isnull(	paylocation	,'')	,

	FMCode	=	isnull(	FMCode	,'')	,

	INCOME_SLAB	=	isnull(	INCOME_SLAB	,'')	,

	NETWORTH_SLAB	=	isnull(	NETWORTH_SLAB	,'')	,

	PARENTCODE	=	isnull(	PARENTCODE	,'')	,

	PRODUCTCODE	=	isnull(	PRODUCTCODE	,'')	,

	RES_PHONE1_STD	=	isnull(	RES_PHONE1_STD	,'')	,

	RES_PHONE2_STD	=	isnull(	RES_PHONE2_STD	,'')	,

	OFF_PHONE1_STD	=	isnull(	OFF_PHONE1_STD	,'')	,

	OFF_PHONE2_STD	=	isnull(	OFF_PHONE2_STD	,'')	,

	P_PHONE_STD	=	isnull(	P_PHONE_STD	,'')

	FROM ABVSCITRUS.CRMDB_A.DBO.MIG_client_details M 

	where EXISTS (SELECT TOP 1 * FROM #DATA WHERE M.CL_CODE = #DATA.CL_CODE)  
 */



 INSERT INTO CLIENT_MASTER_UCC_DATA  

 (  

  PARTY_CODE,UPDATIONFLAG,RELATIONSHIP,MASTERPAN,TYPEOFFACILITY,CATEGORY,FATHERNAME,GENDER,NATIONALITY,NATIONALITY_OTHER,PAN_EXEMPT,  

  PAN_EXEMPT_CATEGORY,AADHAR_UID,IN_PERSON,IN_PERSON_DATE,PEP,DATE_OF_DECLARATION,GROSS_INCOME,NET_WORTH,NET_WORTH_DATE,PROOF_OF_ID,  

  PROOF_OF_ADDRESS,OCCUPATION,OCCUPATION_OTHER,MARITALSTATUS,DATEOFCOMMENCMENT,PLACEOFINCORPRATION,[STATUS],STATUS_OTHER,RES_STATUS_IND,  

  DOCUMENTS,PERMFOREIGN_STATE,PERMFOREIGN_COUNTRY,PERMFOREIGN_ADDRESS_PROFF,PERMFOREIGN_REFID,PERMFOREIGN_REFID_DATE,PLACEOFCOMM,  

  FORMNO,COR_ADDRESS_PROOF_REF_DATE,COR_ADD_PROOF_REF_ID,TRADE_CATEGORY,PROOF_ADDRESS_COMM,GROSS_ANN_COMM,PEP_COMM,  

  OCCUPATION_COMM,PROOF_ADDRESS_DET1,PROOF_ADDRESS_DET2,PROOF_ADDRESS_DET3,PROOF_ADDRESS_DET4,PROOF_ADDRESS_DET5,  

  COMM_OCC_OTHER,PANEXEMPTPROOF,PROOF_NUMBER,ISSUE_PLACE,ISSUE_DATE,GROSS_DATE,PARTNERS_KARTA_UID,  

  PARTNERS_CO_PARCENER_UID,STATUS_REMARKS   

 )                

 SELECT  

  PARTY_CODE,UPDATIONFLAG,RELATIONSHIP,MASTERPAN,TYPEOFFACILITY,CATEGORY,FATHERNAME,GENDER,NATIONALITY,NATIONALITY_OTHER,PAN_EXEMPT,  

  PAN_EXEMPT_CATEGORY,AADHAR_UID,IN_PERSON,IN_PERSON_DATE,PEP,DATE_OF_DECLARATION,GROSS_INCOME,NET_WORTH,NET_WORTH_DATE,PROOF_OF_ID,  

  PROOF_OF_ADDRESS,OCCUPATION,OCCUPATION_OTHER,MARITALSTATUS,DATEOFCOMMENCMENT,PLACEOFINCORPRATION,STATUS,STATUS_OTHER,RES_STATUS_IND,  

  DOCUMENTS,PERMFOREIGN_STATE,PERMFOREIGN_COUNTRY,PERMFOREIGN_ADDRESS_PROFF,PERMFOREIGN_REFID,PERMFOREIGN_REFID_DATE,PLACEOFCOMM,FORMNO,  

  COR_ADDRESS_PROOF_REF_DATE,COR_ADD_PROOF_REF_ID,TRADE_CATEGORY,PROOF_ADDRESS_COMM,GROSS_ANN_COMM,PEP_COMM,OCCUPATION_COMM,  

  PROOF_ADDRESS_DET1,PROOF_ADDRESS_DET2,PROOF_ADDRESS_DET3,PROOF_ADDRESS_DET4,PROOF_ADDRESS_DET5,COMM_OCC_OTHER,PANEXEMPTPROOF,  

  PROOF_NUMBER,ISSUE_PLACE,ISSUE_DATE,GROSS_DATE,PARTNERS_KARTA_UID,PARTNERS_CO_PARCENER_UID,STATUS_REMARKS  

 FROM ABVSCITRUS.CRMDB_A.DBO.VIEW_CLASS_CLIENT_MASTER_UCC_DATA U

 WHERE EXISTS (SELECT CL_CODE FROM #DATA WHERE CL_CODE = PARTY_CODE AND RECVALID='Y')
 
 AND NOT EXISTS (SELECT PARTY_CODE FROM CLIENT_MASTER_UCC_DATA U1 WHERE U.PARTY_CODE = U1.PARTY_CODE)



update CLIENT_MASTER_UCC_DATA set 						

	PARTY_CODE	=	isnull(	PARTY_CODE	,'')	,

	UPDATIONFLAG	=	isnull(	UPDATIONFLAG	,'')	,

	RELATIONSHIP	=	isnull(	RELATIONSHIP	,'')	,

	MASTERPAN	=	isnull(	MASTERPAN	,'')	,

	TYPEOFFACILITY	=	isnull(	TYPEOFFACILITY	,'')	,

	CATEGORY	=	isnull(	CATEGORY	,'')	,

	FATHERNAME	=	isnull(	FATHERNAME	,'')	,

	GENDER	=	isnull(	GENDER	,'')	,

	NATIONALITY	=	isnull(	NATIONALITY	,'')	,

	NATIONALITY_OTHER	=	isnull(	NATIONALITY_OTHER	,'')	,

	PAN_EXEMPT	=	isnull(	PAN_EXEMPT	,'')	,

	PAN_EXEMPT_CATEGORY	=	isnull(	PAN_EXEMPT_CATEGORY	,'')	,

	AADHAR_UID	=	isnull(	AADHAR_UID	,'')	,

	IN_PERSON	=	isnull(	IN_PERSON	,'')	,

	IN_PERSON_DATE	=	isnull(	IN_PERSON_DATE	,'')	,

	PEP	=	isnull(	PEP	,'')	,

	DATE_OF_DECLARATION	=	isnull(	DATE_OF_DECLARATION	,'')	,

	GROSS_INCOME	=	isnull(	GROSS_INCOME	,'') 	,

	NET_WORTH	=	isnull(	NET_WORTH	,'0')	,

	NET_WORTH_DATE	=	isnull(	NET_WORTH_DATE	,'')	,

	PROOF_OF_ID	=	isnull(	PROOF_OF_ID	,'')	,

	PROOF_OF_ADDRESS	=	isnull(	PROOF_OF_ADDRESS	,'')	,

	OCCUPATION	=	isnull(	OCCUPATION	,'')	,

	OCCUPATION_OTHER	=	isnull(	OCCUPATION_OTHER	,'')	,

	MARITALSTATUS	=	isnull(	MARITALSTATUS	,'')	,

	DATEOFCOMMENCMENT	=	isnull(	DATEOFCOMMENCMENT	,'')	,

	PLACEOFINCORPRATION	=	isnull(	PLACEOFINCORPRATION	,'')	,

	STATUS	=	isnull(	STATUS	,'')	,

	STATUS_OTHER	=	isnull(	STATUS_OTHER	,'')	,

	RES_STATUS_IND	=	isnull(	RES_STATUS_IND	,'')	,

	DOCUMENTS	=	isnull(	DOCUMENTS	,'')	,

	PERMFOREIGN_STATE	=	isnull(	PERMFOREIGN_STATE	,'')	,

	PERMFOREIGN_COUNTRY	=	isnull(	PERMFOREIGN_COUNTRY	,'')	,

	PERMFOREIGN_ADDRESS_PROFF	=	isnull(	PERMFOREIGN_ADDRESS_PROFF	,'')	,

	PERMFOREIGN_REFID	=	isnull(	PERMFOREIGN_REFID	,'')	,

	PERMFOREIGN_REFID_DATE	=	isnull(	PERMFOREIGN_REFID_DATE	,'')	,

	PLACEOFCOMM	=	isnull(	PLACEOFCOMM	,'')	,

	FORMNO	=	isnull(	FORMNO	,'')	,

	COR_ADDRESS_PROOF_REF_DATE	=	isnull(	COR_ADDRESS_PROOF_REF_DATE	,'')	,

	COR_ADD_PROOF_REF_ID	=	isnull(	COR_ADD_PROOF_REF_ID	,'')	,

	TRADE_CATEGORY	=	isnull(	TRADE_CATEGORY	,'')	,

	PROOF_ADDRESS_COMM	=	isnull(	PROOF_ADDRESS_COMM	,'')	,

	GROSS_ANN_COMM	=	isnull(	GROSS_ANN_COMM	,'')	,

	PEP_COMM	=	isnull(	PEP_COMM	,'')	,

	OCCUPATION_COMM	=	isnull(	OCCUPATION_COMM	,'')	,

	PROOF_ADDRESS_DET1	=	isnull(	PROOF_ADDRESS_DET1	,'')	,

	PROOF_ADDRESS_DET2	=	isnull(	PROOF_ADDRESS_DET2	,'')	,

	PROOF_ADDRESS_DET3	=	isnull(	PROOF_ADDRESS_DET3	,'')	,

	PROOF_ADDRESS_DET4	=	isnull(	PROOF_ADDRESS_DET4	,'')	,

	PROOF_ADDRESS_DET5	=	isnull(	PROOF_ADDRESS_DET5	,'')	,

	COMM_OCC_OTHER	=	isnull(	COMM_OCC_OTHER	,'')	,

	PANEXEMPTPROOF	=	isnull(	PANEXEMPTPROOF	,'')	,

	PROOF_NUMBER	=	isnull(	PROOF_NUMBER	,'')	,

	ISSUE_PLACE	=	isnull(	ISSUE_PLACE	,'')	,

	ISSUE_DATE	=	isnull(	ISSUE_DATE	,'')	,

	GROSS_DATE	=	isnull(	GROSS_DATE	,'')	,

	STATUS_REMARKS	=	isnull(	STATUS_REMARKS	,'')	,

	PARTNERS_KARTA_UID	=	isnull(	PARTNERS_KARTA_UID	,'')	,

	PARTNERS_CO_PARCENER_UID	=	isnull(	PARTNERS_CO_PARCENER_UID	,'')	

WHERE EXISTS (SELECT TOP 1 * FROM #DATA WHERE CLIENT_MASTER_UCC_DATA.PARTY_CODE = #DATA.CL_CODE)  

  

 INSERT INTO CLIENT_BROK_DETAILS  

 (  

  CL_CODE,EXCHANGE,SEGMENT,BROK_SCHEME,TRD_BROK,DEL_BROK,SER_TAX,SER_TAX_METHOD,CREDIT_LIMIT,INACTIVE_FROM,PRINT_OPTIONS,  

  NO_OF_COPIES,PARTICIPANT_CODE,CUSTODIAN_CODE,INST_CONTRACT,ROUND_STYLE,STP_PROVIDER,STP_RP_STYLE,MARKET_TYPE,MULTIPLIER,  

  CHARGED,MAINTENANCE,REQD_BY_EXCH,REQD_BY_BROKER,CLIENT_RATING,DEBIT_BALANCE,INTER_SETT,TRD_STT,TRD_TRAN_CHRGS, TRD_SEBI_FEES,  

  TRD_STAMP_DUTY,TRD_OTHER_CHRGS,TRD_EFF_DT,DEL_STT,DEL_TRAN_CHRGS,DEL_SEBI_FEES,DEL_STAMP_DUTY,DEL_OTHER_CHRGS,DEL_EFF_DT,  

  ROUNDING_METHOD,ROUND_TO_DIGIT,ROUND_TO_PAISE,FUT_BROK,FUT_OPT_BROK,FUT_FUT_FIN_BROK,FUT_OPT_EXC,FUT_BROK_APPLICABLE,FUT_STT,  

  FUT_TRAN_CHRGS,FUT_SEBI_FEES,FUT_STAMP_DUTY,FUT_OTHER_CHRGS,[STATUS],MODIFIEDON,MODIFIEDBY,IMP_STATUS,PAY_B3B_PAYMENT,PAY_BANK_NAME,  

  PAY_BRANCH_NAME,PAY_AC_NO,PAY_PAYMENT_MODE,BROK_EFF_DATE,INST_TRD_BROK,INST_DEL_BROK,SYSTEMDATE,ACTIVE_DATE,CHECKACTIVECLIENT  

 )  

 SELECT  

  CL_CODE,EXCHANGE,SEGMENT,BROK_SCHEME,TRD_BROK=CASE WHEN SEGMENT='FUTURES' THEN 0 ELSE TRD_BROK END,

  DEL_BROK,SER_TAX=ISNULL(SER_TAX, 0),SER_TAX_METHOD,CREDIT_LIMIT,INACTIVE_FROM,PRINT_OPTIONS,  

  NO_OF_COPIES,PARTICIPANT_CODE,CUSTODIAN_CODE,INST_CONTRACT,ROUND_STYLE,STP_PROVIDER,STP_RP_STYLE,MARKET_TYPE,MULTIPLIER,  

  CHARGED,MAINTENANCE,REQD_BY_EXCH,REQD_BY_BROKER,CLIENT_RATING,DEBIT_BALANCE,INTER_SETT,TRD_STT=ISNULL(TRD_STT, 1),TRD_TRAN_CHRGS=ISNULL(TRD_TRAN_CHRGS, 1),TRD_SEBI_FEES=ISNULL(TRD_SEBI_FEES, 0),  

  TRD_STAMP_DUTY=ISNULL(TRD_STAMP_DUTY, 1),TRD_OTHER_CHRGS=ISNULL(TRD_OTHER_CHRGS, 0),TRD_EFF_DT,DEL_STT=ISNULL(DEL_STT, 1),DEL_TRAN_CHRGS=ISNULL(DEL_TRAN_CHRGS, 1),DEL_SEBI_FEES=ISNULL(DEL_SEBI_FEES, 0),DEL_STAMP_DUTY=ISNULL(DEL_STAMP_DUTY, 1),  

  DEL_OTHER_CHRGS=ISNULL(DEL_OTHER_CHRGS, 0),DEL_EFF_DT,  

  ROUNDING_METHOD,ROUND_TO_DIGIT,ROUND_TO_PAISE,FUT_BROK,FUT_OPT_BROK=CASE WHEN SEGMENT='FUTURES' THEN FUT_BROK ELSE FUT_OPT_BROK END,FUT_FUT_FIN_BROK/*=CASE WHEN SEGMENT='FUTURES' THEN FUT_BROK ELSE FUT_FUT_FIN_BROK END*/,  

  FUT_OPT_EXC=CASE WHEN SEGMENT='FUTURES' THEN FUT_BROK ELSE FUT_OPT_EXC END,FUT_BROK_APPLICABLE,FUT_STT=ISNULL(FUT_STT, 1),  

  FUT_TRAN_CHRGS=ISNULL(FUT_TRAN_CHRGS, 1),FUT_SEBI_FEES=ISNULL(FUT_SEBI_FEES, 0),FUT_STAMP_DUTY=ISNULL(FUT_STAMP_DUTY, 1),FUT_OTHER_CHRGS=ISNULL(FUT_OTHER_CHRGS, 0),[STATUS],MODIFIEDON,MODIFIEDBY,IMP_STATUS,PAY_B3B_PAYMENT,

  PAY_BANK_NAME,PAY_BRANCH_NAME,PAY_AC_NO,PAY_PAYMENT_MODE,BROK_EFF_DATE,INST_TRD_BROK,INST_DEL_BROK,SYSTEMDATE,ACTIVE_DATE,CHECKACTIVECLIENT  

 FROM #DATA_BROK A WHERE RECVALID='Y'



  UPDATE

	B

 SET

	TRD_SEBI_FEES = M.TRD_SEBITURN_TAX, 

	DEL_SEBI_FEES = M.DEL_SEBITURN_TAX, 

	TRD_TRAN_CHRGS = M.TRD_TURNOVER_TAX,

	DEL_TRAN_CHRGS = M.DEL_TURNOVER_TAX, 

	TRD_STAMP_DUTY = M.TRD_BROKER_NOTE, 

	DEL_STAMP_DUTY = M.DEL_BROKER_NOTE, 

	TRD_STT = TRD_INSURANCE_CHRG,

	DEL_STT = DEL_INSURANCE_CHRG,

	FUT_TRAN_CHRGS = 1, 

	FUT_SEBI_FEES = 1,

	FUT_STT = 1,

	FUT_STAMP_DUTY = 1,

	FUT_OTHER_CHRGS = 1  

 FROM

	CLIENT_BROK_DETAILS B,

	( SELECT EXCHANGE, SEGMENT, 

		TRD_SEBITURN_TAX = SUM(CASE WHEN TRANS_CAT IN ('TRD', 'FUT') THEN SEBITURN_TAX ELSE CONVERT(NUMERIC(18,6),0) END),

		DEL_SEBITURN_TAX = SUM(CASE WHEN TRANS_CAT IN ('DEL', 'OPT') THEN SEBITURN_TAX ELSE CONVERT(NUMERIC(18,6),0) END),

		TRD_TURNOVER_TAX = SUM(CASE WHEN TRANS_CAT IN ('TRD', 'FUT') THEN TURNOVER_TAX ELSE CONVERT(NUMERIC(18,6),0) END),

		DEL_TURNOVER_TAX = SUM(CASE WHEN TRANS_CAT IN ('DEL', 'OPT') THEN TURNOVER_TAX ELSE CONVERT(NUMERIC(18,6),0) END),

		TRD_BROKER_NOTE = SUM(CASE WHEN TRANS_CAT IN ('TRD', 'FUT') THEN BROKER_NOTE ELSE CONVERT(NUMERIC(18,6),0) END),

		DEL_BROKER_NOTE = SUM(CASE WHEN TRANS_CAT IN ('DEL', 'OPT') THEN BROKER_NOTE ELSE CONVERT(NUMERIC(18,6),0) END),

		TRD_INSURANCE_CHRG = SUM(CASE WHEN TRANS_CAT IN ('TRD', 'FUT') THEN INSURANCE_CHRG ELSE CONVERT(NUMERIC(18,6),0) END),

		DEL_INSURANCE_CHRG = SUM(CASE WHEN TRANS_CAT IN ('DEL', 'OPT') THEN INSURANCE_CHRG ELSE CONVERT(NUMERIC(18,6),0) END)

		FROM CLIENT_MASTER_TAXES

		WHERE TRANS_CAT <> 'PRO'

		GROUP BY EXCHANGE, SEGMENT ) M,

	#DATA_BROK D

 WHERE

    B.EXCHANGE + B.SEGMENT = M.EXCHANGE + M.SEGMENT

    AND B.CL_CODE = D.CL_CODE

    AND RECVALID='Y'



update client_brok_details set 	Cl_Code	=	isnull(	Cl_Code	,'')	,

	Exchange	=	isnull(	Exchange	,'')	,

	Segment	=	isnull(	Segment	,'')	,

	Brok_Scheme	=	isnull(	Brok_Scheme	,'0')	,

	Trd_Brok	=	isnull(	Trd_Brok	,'0')	,

	Del_Brok	=	isnull(	Del_Brok	,'0')	,

	Ser_Tax	=	isnull(	Ser_Tax	,'0')	,

	Ser_Tax_Method	=	isnull(	Ser_Tax_Method	,'0')	,

	Credit_Limit	=	isnull(	Credit_Limit	,'0')	,

	InActive_From	=	isnull(	InActive_From	,'')	,

	Print_Options	=	isnull(	Print_Options	,'0')	,

	No_Of_Copies	=	isnull(	No_Of_Copies	,'0')	,

	Participant_Code	=	isnull(	Participant_Code	,''),

	Custodian_Code	=	isnull(	Custodian_Code	,'')	,

	Inst_Contract	=	isnull(	Inst_Contract	,'')	,

	Round_Style	=	isnull(	Round_Style	,'0')	,

	STP_Provider	=	isnull(	STP_Provider	,'')	,

	STP_Rp_Style	=	isnull(	STP_Rp_Style	,'0')	,

	Market_Type	=	isnull(	Market_Type	,'0')	,

	Multiplier	=	isnull(	Multiplier	,'0')	,

	Charged	=	isnull(	Charged	,'0')	,

	Maintenance	=	isnull(	Maintenance	,'0')	,

	Reqd_By_Exch	=	isnull(	Reqd_By_Exch	,'0')	,

	Reqd_By_Broker	=	isnull(	Reqd_By_Broker	,'0')	,

	Client_Rating	=	isnull(	Client_Rating	,'0')	,

	Debit_Balance	=	isnull(	Debit_Balance	,'2')	,

	Inter_Sett	=	isnull(	Inter_Sett	,'0')	,

	TRD_STT	=	isnull(	TRD_STT	,'0')	,

	Trd_Tran_Chrgs	=	isnull(	Trd_Tran_Chrgs	,'0')	,

	Trd_Sebi_Fees	=	isnull(	Trd_Sebi_Fees	,'0')	,

	Trd_Stamp_Duty	=	isnull(	Trd_Stamp_Duty	,'0')	,

	Trd_Other_Chrgs	=	isnull(	Trd_Other_Chrgs	,'0')	,

	Trd_Eff_Dt	=	isnull(	Trd_Eff_Dt	,'')	,

	Del_Stt	=	isnull(	Del_Stt	,'0')	,

	Del_Tran_Chrgs	=	isnull(	Del_Tran_Chrgs	,'0')	,

	Del_SEBI_Fees	=	isnull(	Del_SEBI_Fees	,'0')	,

	Del_Stamp_Duty	=	isnull(	Del_Stamp_Duty	,'0')	,

	Del_Other_Chrgs	=	isnull(	Del_Other_Chrgs	,'0')	,

	Del_Eff_Dt	=	isnull(	Del_Eff_Dt	,'')	,

	Rounding_Method	=	isnull(	Rounding_Method	,'ACTUAL')	,

	Round_To_Digit	=	isnull(	Round_To_Digit	,'0')	,

	Round_To_Paise	=	isnull(	Round_To_Paise	,'4')	,

	Fut_Brok	=	isnull(	Fut_Brok	,'0')	,

	Fut_Opt_Brok	=	isnull(	Fut_Opt_Brok	,'0')	,

	Fut_Fut_Fin_Brok	=	isnull(	Fut_Fut_Fin_Brok	,'0')	,

	Fut_Opt_Exc	=	isnull(	Fut_Opt_Exc	,'0')	,

	Fut_Brok_Applicable	=	isnull(	Fut_Brok_Applicable	,'0')	,

	Fut_Stt	=	isnull(	Fut_Stt	,'0')	,

	Fut_Tran_Chrgs	=	isnull(	Fut_Tran_Chrgs	,'0')	,

	Fut_Sebi_Fees	=	isnull(	Fut_Sebi_Fees	,'0')	,

	Fut_Stamp_Duty	=	isnull(	Fut_Stamp_Duty	,'0')	,

	Fut_Other_Chrgs	=	isnull(	Fut_Other_Chrgs	,'0')	,

	Status	=	isnull(	Status	,'I')	,

	Modifiedon	=	isnull(	Modifiedon	,'')	,

	Modifiedby	=	isnull(	Modifiedby	,'')	,

	Imp_Status	=	isnull(	Imp_Status	,'0')	,

	Pay_B3B_Payment	=	isnull(	Pay_B3B_Payment	,'0')	,

	Pay_Bank_name	=	isnull(	Pay_Bank_name	,'')	,

	Pay_Branch_name	=	isnull(	Pay_Branch_name	,'')	,

	Pay_AC_No	=	isnull(	Pay_AC_No	,'0')	,

	Pay_payment_Mode	=	isnull(	Pay_payment_Mode	,'0')	,

	Brok_Eff_Date	=	isnull(	Brok_Eff_Date	,'')	,

	Inst_Trd_Brok	=	isnull(	Inst_Trd_Brok	,'0')	,

	Inst_Del_Brok	=	isnull(	Inst_Del_Brok	,'0')	,

	SYSTEMDATE	=	isnull(	SYSTEMDATE	,'')	,

	Active_Date	=	isnull(	Active_Date	,'')	,

	CheckActiveClient	=	isnull(	CheckActiveClient	,'0')	,

	Deactive_Remarks	=	isnull(	Deactive_Remarks	,'')	,

	Deactive_value	=	isnull(	Deactive_value	,'')

	where EXISTS (SELECT TOP 1 * FROM #DATA_BROK WHERE #DATA_BROK.CL_CODE = client_brok_details.CL_CODE)  
/*

INSERT INTO ABVSCITRUS.CRMDB_A.DBO.MIG_CLIENT_BROK_DETAILS  

 (  

  CL_CODE,EXCHANGE,SEGMENT,BROK_SCHEME,TRD_BROK,DEL_BROK,SER_TAX,SER_TAX_METHOD,CREDIT_LIMIT,INACTIVE_FROM,PRINT_OPTIONS,  

  NO_OF_COPIES,PARTICIPANT_CODE,CUSTODIAN_CODE,INST_CONTRACT,ROUND_STYLE,STP_PROVIDER,STP_RP_STYLE,MARKET_TYPE,MULTIPLIER,  

  CHARGED,MAINTENANCE,REQD_BY_EXCH,REQD_BY_BROKER,CLIENT_RATING,DEBIT_BALANCE,INTER_SETT,TRD_STT,TRD_TRAN_CHRGS, TRD_SEBI_FEES,  

  TRD_STAMP_DUTY,TRD_OTHER_CHRGS,TRD_EFF_DT,DEL_STT,DEL_TRAN_CHRGS,DEL_SEBI_FEES,DEL_STAMP_DUTY,DEL_OTHER_CHRGS,DEL_EFF_DT,  

  ROUNDING_METHOD,ROUND_TO_DIGIT,ROUND_TO_PAISE,FUT_BROK,FUT_OPT_BROK,FUT_FUT_FIN_BROK,FUT_OPT_EXC,FUT_BROK_APPLICABLE,FUT_STT,  

  FUT_TRAN_CHRGS,FUT_SEBI_FEES,FUT_STAMP_DUTY,FUT_OTHER_CHRGS,[STATUS],MODIFIEDON,MODIFIEDBY,IMP_STATUS,PAY_B3B_PAYMENT,PAY_BANK_NAME,  

  PAY_BRANCH_NAME,PAY_AC_NO,PAY_PAYMENT_MODE,BROK_EFF_DATE,INST_TRD_BROK,INST_DEL_BROK,SYSTEMDATE,ACTIVE_DATE,CHECKACTIVECLIENT  

 )  

 SELECT  

  CL_CODE,EXCHANGE,SEGMENT,BROK_SCHEME,TRD_BROK=CASE WHEN SEGMENT='FUTURES' THEN 0 ELSE TRD_BROK END,

  DEL_BROK,SER_TAX=ISNULL(SER_TAX, 0),SER_TAX_METHOD,CREDIT_LIMIT,INACTIVE_FROM,PRINT_OPTIONS,  

  NO_OF_COPIES,PARTICIPANT_CODE,CUSTODIAN_CODE,INST_CONTRACT,ROUND_STYLE,STP_PROVIDER,STP_RP_STYLE,MARKET_TYPE,MULTIPLIER,  

  CHARGED,MAINTENANCE,REQD_BY_EXCH,REQD_BY_BROKER,CLIENT_RATING,DEBIT_BALANCE,INTER_SETT,TRD_STT=ISNULL(TRD_STT, 1),TRD_TRAN_CHRGS=ISNULL(TRD_TRAN_CHRGS, 1),TRD_SEBI_FEES=ISNULL(TRD_SEBI_FEES, 0),  

  TRD_STAMP_DUTY=ISNULL(TRD_STAMP_DUTY, 1),TRD_OTHER_CHRGS=ISNULL(TRD_OTHER_CHRGS, 0),TRD_EFF_DT,DEL_STT=ISNULL(DEL_STT, 1),DEL_TRAN_CHRGS=ISNULL(DEL_TRAN_CHRGS, 1),DEL_SEBI_FEES=ISNULL(DEL_SEBI_FEES, 0),DEL_STAMP_DUTY=ISNULL(DEL_STAMP_DUTY, 1),  

  DEL_OTHER_CHRGS=ISNULL(DEL_OTHER_CHRGS, 0),DEL_EFF_DT,  

  ROUNDING_METHOD,ROUND_TO_DIGIT,ROUND_TO_PAISE,FUT_BROK,FUT_OPT_BROK=CASE WHEN SEGMENT='FUTURES' THEN FUT_BROK ELSE FUT_OPT_BROK END,FUT_FUT_FIN_BROK/*=CASE WHEN SEGMENT='FUTURES' THEN FUT_BROK ELSE FUT_FUT_FIN_BROK END*/,  

  FUT_OPT_EXC=CASE WHEN SEGMENT='FUTURES' THEN FUT_BROK ELSE FUT_OPT_EXC END,FUT_BROK_APPLICABLE,FUT_STT=ISNULL(FUT_STT, 1),  

  FUT_TRAN_CHRGS=ISNULL(FUT_TRAN_CHRGS, 1),FUT_SEBI_FEES=ISNULL(FUT_SEBI_FEES, 0),FUT_STAMP_DUTY=ISNULL(FUT_STAMP_DUTY, 1),FUT_OTHER_CHRGS=ISNULL(FUT_OTHER_CHRGS, 0),[STATUS],MODIFIEDON,MODIFIEDBY,IMP_STATUS,PAY_B3B_PAYMENT,

  PAY_BANK_NAME,PAY_BRANCH_NAME,PAY_AC_NO,PAY_PAYMENT_MODE,BROK_EFF_DATE,INST_TRD_BROK,INST_DEL_BROK,SYSTEMDATE,ACTIVE_DATE,CHECKACTIVECLIENT  

 FROM #DATA_BROK A WHERE RECVALID='Y'



  UPDATE

	B

 SET

	TRD_SEBI_FEES = M.TRD_SEBITURN_TAX, 

	DEL_SEBI_FEES = M.DEL_SEBITURN_TAX, 

	TRD_TRAN_CHRGS = M.TRD_TURNOVER_TAX,

	DEL_TRAN_CHRGS = M.DEL_TURNOVER_TAX, 

	TRD_STAMP_DUTY = M.TRD_BROKER_NOTE, 

	DEL_STAMP_DUTY = M.DEL_BROKER_NOTE, 

	TRD_STT = TRD_INSURANCE_CHRG,

	DEL_STT = DEL_INSURANCE_CHRG,

	FUT_TRAN_CHRGS = 1, 

	FUT_SEBI_FEES = 1,

	FUT_STT = 1,

	FUT_STAMP_DUTY = 1,

	FUT_OTHER_CHRGS = 1  

 FROM

	ABVSCITRUS.CRMDB_A.DBO.MIG_CLIENT_BROK_DETAILS B,

	( SELECT EXCHANGE, SEGMENT, 

		TRD_SEBITURN_TAX = SUM(CASE WHEN TRANS_CAT IN ('TRD', 'FUT') THEN SEBITURN_TAX ELSE CONVERT(NUMERIC(18,6),0) END),

		DEL_SEBITURN_TAX = SUM(CASE WHEN TRANS_CAT IN ('DEL', 'OPT') THEN SEBITURN_TAX ELSE CONVERT(NUMERIC(18,6),0) END),

		TRD_TURNOVER_TAX = SUM(CASE WHEN TRANS_CAT IN ('TRD', 'FUT') THEN TURNOVER_TAX ELSE CONVERT(NUMERIC(18,6),0) END),

		DEL_TURNOVER_TAX = SUM(CASE WHEN TRANS_CAT IN ('DEL', 'OPT') THEN TURNOVER_TAX ELSE CONVERT(NUMERIC(18,6),0) END),

		TRD_BROKER_NOTE = SUM(CASE WHEN TRANS_CAT IN ('TRD', 'FUT') THEN BROKER_NOTE ELSE CONVERT(NUMERIC(18,6),0) END),

		DEL_BROKER_NOTE = SUM(CASE WHEN TRANS_CAT IN ('DEL', 'OPT') THEN BROKER_NOTE ELSE CONVERT(NUMERIC(18,6),0) END),

		TRD_INSURANCE_CHRG = SUM(CASE WHEN TRANS_CAT IN ('TRD', 'FUT') THEN INSURANCE_CHRG ELSE CONVERT(NUMERIC(18,6),0) END),

		DEL_INSURANCE_CHRG = SUM(CASE WHEN TRANS_CAT IN ('DEL', 'OPT') THEN INSURANCE_CHRG ELSE CONVERT(NUMERIC(18,6),0) END)

		FROM CLIENT_MASTER_TAXES

		WHERE TRANS_CAT <> 'PRO'

		GROUP BY EXCHANGE, SEGMENT ) M,

	#DATA_BROK D

 WHERE

    B.EXCHANGE + B.SEGMENT = M.EXCHANGE + M.SEGMENT

    AND B.CL_CODE = D.CL_CODE

    AND RECVALID='Y'



update B 
    set 	Cl_Code	=	isnull(	Cl_Code	,'')	,

	Exchange	=	isnull(	Exchange	,'')	,

	Segment	=	isnull(	Segment	,'')	,

	Brok_Scheme	=	isnull(	Brok_Scheme	,'0')	,

	Trd_Brok	=	isnull(	Trd_Brok	,'0')	,

	Del_Brok	=	isnull(	Del_Brok	,'0')	,

	Ser_Tax	=	isnull(	Ser_Tax	,'0')	,

	Ser_Tax_Method	=	isnull(	Ser_Tax_Method	,'0')	,

	Credit_Limit	=	isnull(	Credit_Limit	,'0')	,

	InActive_From	=	isnull(	InActive_From	,'')	,

	Print_Options	=	isnull(	Print_Options	,'0')	,

	No_Of_Copies	=	isnull(	No_Of_Copies	,'0')	,

	Participant_Code	=	isnull(	Participant_Code	,''),

	Custodian_Code	=	isnull(	Custodian_Code	,'')	,

	Inst_Contract	=	isnull(	Inst_Contract	,'')	,

	Round_Style	=	isnull(	Round_Style	,'0')	,

	STP_Provider	=	isnull(	STP_Provider	,'')	,

	STP_Rp_Style	=	isnull(	STP_Rp_Style	,'0')	,

	Market_Type	=	isnull(	Market_Type	,'0')	,

	Multiplier	=	isnull(	Multiplier	,'0')	,

	Charged	=	isnull(	Charged	,'0')	,

	Maintenance	=	isnull(	Maintenance	,'0')	,

	Reqd_By_Exch	=	isnull(	Reqd_By_Exch	,'0')	,

	Reqd_By_Broker	=	isnull(	Reqd_By_Broker	,'0')	,

	Client_Rating	=	isnull(	Client_Rating	,'0')	,

	Debit_Balance	=	isnull(	Debit_Balance	,'2')	,

	Inter_Sett	=	isnull(	Inter_Sett	,'0')	,

	TRD_STT	=	isnull(	TRD_STT	,'0')	,

	Trd_Tran_Chrgs	=	isnull(	Trd_Tran_Chrgs	,'0')	,

	Trd_Sebi_Fees	=	isnull(	Trd_Sebi_Fees	,'0')	,

	Trd_Stamp_Duty	=	isnull(	Trd_Stamp_Duty	,'0')	,

	Trd_Other_Chrgs	=	isnull(	Trd_Other_Chrgs	,'0')	,

	Trd_Eff_Dt	=	isnull(	Trd_Eff_Dt	,'')	,

	Del_Stt	=	isnull(	Del_Stt	,'0')	,

	Del_Tran_Chrgs	=	isnull(	Del_Tran_Chrgs	,'0')	,

	Del_SEBI_Fees	=	isnull(	Del_SEBI_Fees	,'0')	,

	Del_Stamp_Duty	=	isnull(	Del_Stamp_Duty	,'0')	,

	Del_Other_Chrgs	=	isnull(	Del_Other_Chrgs	,'0')	,

	Del_Eff_Dt	=	isnull(	Del_Eff_Dt	,'')	,

	Rounding_Method	=	isnull(	Rounding_Method	,'ACTUAL')	,

	Round_To_Digit	=	isnull(	Round_To_Digit	,'0')	,

	Round_To_Paise	=	isnull(	Round_To_Paise	,'4')	,

	Fut_Brok	=	isnull(	Fut_Brok	,'0')	,

	Fut_Opt_Brok	=	isnull(	Fut_Opt_Brok	,'0')	,

	Fut_Fut_Fin_Brok	=	isnull(	Fut_Fut_Fin_Brok	,'0')	,

	Fut_Opt_Exc	=	isnull(	Fut_Opt_Exc	,'0')	,

	Fut_Brok_Applicable	=	isnull(	Fut_Brok_Applicable	,'0')	,

	Fut_Stt	=	isnull(	Fut_Stt	,'0')	,

	Fut_Tran_Chrgs	=	isnull(	Fut_Tran_Chrgs	,'0')	,

	Fut_Sebi_Fees	=	isnull(	Fut_Sebi_Fees	,'0')	,

	Fut_Stamp_Duty	=	isnull(	Fut_Stamp_Duty	,'0')	,

	Fut_Other_Chrgs	=	isnull(	Fut_Other_Chrgs	,'0')	,

	Status	=	isnull(	Status	,'I')	,

	Modifiedon	=	isnull(	Modifiedon	,'')	,

	Modifiedby	=	isnull(	Modifiedby	,'')	,

	Imp_Status	=	isnull(	Imp_Status	,'0')	,

	Pay_B3B_Payment	=	isnull(	Pay_B3B_Payment	,'0')	,

	Pay_Bank_name	=	isnull(	Pay_Bank_name	,'')	,

	Pay_Branch_name	=	isnull(	Pay_Branch_name	,'')	,

	Pay_AC_No	=	isnull(	Pay_AC_No	,'0')	,

	Pay_payment_Mode	=	isnull(	Pay_payment_Mode	,'0')	,

	Brok_Eff_Date	=	isnull(	Brok_Eff_Date	,'')	,

	Inst_Trd_Brok	=	isnull(	Inst_Trd_Brok	,'0')	,

	Inst_Del_Brok	=	isnull(	Inst_Del_Brok	,'0')	,

	SYSTEMDATE	=	isnull(	SYSTEMDATE	,'')	,

	Active_Date	=	isnull(	Active_Date	,'')	,

	CheckActiveClient	=	isnull(	CheckActiveClient	,'0')	,

	Deactive_Remarks	=	isnull(	Deactive_Remarks	,'')	,

	Deactive_value	=	isnull(	Deactive_value	,'')

	FROM ABVSCITRUS.CRMDB_A.DBO.MIG_client_brok_details b

	where EXISTS (SELECT TOP 1 * FROM #DATA_BROK WHERE #DATA_BROK.CL_CODE = b.CL_CODE)  

*/

--EXEC ABVSCITRUS.CRMDB_A.DBO.MIG_PROC_CLIENT_MASTER

 INSERT INTO CLIENT_MASTER_NOMINEE_DATA  

 (

 PARTY_CODE,NOMINEE,RELATIONSHIP,ADDRESS1,ADDRESS2,DOB,NAMEOFGUARDIAN,NOMINEEPANNO,MINORFLAG,NOMINEEPHONE,GUARDIANPHONE,GUARDIANPANNO,CIN

 )

 SELECT

	V.PARTY_CODE,NOMINEE,RELATIONSHIP,ADDRESS1,ADDRESS2,V.DOB,NAMEOFGUARDIAN,NOMINEEPANNO,MINORFLAG,NOMINEEPHONE,GUARDIANPHONE,GUARDIANPANNO,CIN

FROM

	ABVSCITRUS.CRMDB_A.DBO.VIEW_NOMINEE_DTLS V,

	#DATA 

WHERE 

	V.PARTY_CODE = #DATA.CL_CODE

	AND RECVALID='Y'



update CLIENT_MASTER_NOMINEE_DATA set 	 

	PARTY_CODE	=	isnull(	PARTY_CODE	,'')	,

	NOMINEE	=	isnull(	NOMINEE	,'')	,

	RELATIONSHIP	=	isnull(	RELATIONSHIP	,'')	,

	ADDRESS1	=	isnull(	ADDRESS1	,'')	,

	ADDRESS2	=	isnull(	ADDRESS2	,'')	,

	DOB	=	isnull(	DOB	,'')	,

	NAMEOFGUARDIAN	=	isnull(	NAMEOFGUARDIAN	,'')	,

	NOMINEEPANNO	=	isnull(	NOMINEEPANNO	,'')	,

	MINORFLAG	=	isnull(	MINORFLAG	,'')	,

	NOMINEEPHONE	=	isnull(	NOMINEEPHONE	,'')	,

	GUARDIANPHONE	=	isnull(	GUARDIANPHONE	,'')	,

	GUARDIANPANNO	=	isnull(	GUARDIANPANNO	,'')	,

	CIN	=	isnull(	CIN	,'')	

	where EXISTS (SELECT TOP 1 * FROM #DATA_BROK WHERE #DATA_BROK.CL_CODE = CLIENT_MASTER_NOMINEE_DATA.PARTY_CODE)  


	INSERT INTO MULTIBANKID_COMMONINTERFACE
		(Cltcode,Bankid,Bank_Name,Branch,Accno,Acctype,Chequename,Defaultbank,Exchange,Segment,UpdateFlag,upddate,IFSCCode,Micr_Code)
    SELECT M.* FROM 
		ABVSCITRUS.CRMDB_A.DBO.VIEW_CLASS_CLIENT_MULTIBANK_WODEFAULT M,
		#DATA 
	WHERE 
		BO_PARTYCODE = #DATA.CL_CODE
		AND RECVALID='Y'
		AND NOT EXISTS (SELECT CLTCODE FROM MULTIBANKID_COMMONINTERFACE WHERE BO_PARTYCODE = CLTCODE)

	INSERT INTO CLIENT_CONTACT_DETAILS
    SELECT D.* FROM 
		ABVSCITRUS.CRMDB_A.DBO.GETHOLDERDATA_NONIND D,
		#DATA 
	WHERE 
		D.CL_CODE = #DATA.CL_CODE
		AND RECVALID='Y'		
		AND NOT EXISTS (SELECT CL_CODE FROM CLIENT_CONTACT_DETAILS C WHERE D.CL_CODE = C.CL_CODE)

 ----------------------------------------------------------------------------------------------------------------                                

 INSERT INTO ANGELFO.BSEMFSS.DBO.MFSS_CLIENT  

 (  

  PARTY_CODE,PARTY_NAME,CL_TYPE,CL_BALANCE,CL_STATUS,BRANCH_CD,SUB_BROKER,TRADER,AREA,REGION,SBU,  

  FAMILY,GENDER,OCCUPATION_CODE,TAX_STATUS,PAN_NO,KYC_FLAG,ADDR1,ADDR2,ADDR3,CITY,STATE,ZIP,NATION,  

  OFFICE_PHONE,RES_PHONE,MOBILE_NO,EMAIL_ID,BANK_NAME,BANK_BRANCH,BANK_CITY,ACC_NO,PAYMODE,MICR_NO,  

  DOB,GAURDIAN_NAME,GAURDIAN_PAN_NO,NOMINEE_NAME,NOMINEE_RELATION,BANK_AC_TYPE,STAT_COMM_MODE,DP_TYPE,  

  DPID,CLTDPID,MODE_HOLDING,HOLDER2_CODE,HOLDER2_NAME,HOLDER2_PAN_NO,HOLDER2_KYC_FLAG,HOLDER3_CODE,  

  HOLDER3_NAME,HOLDER3_PAN_NO,HOLDER3_KYC_FLAG,BUY_BROK_TABLE_NO,SELL_BROK_TABLE_NO,BROK_EFF_DATE,  

  NEFTCODE,CHEQUENAME,RESIFAX,OFFICEFAX,MAPINID,REMARK,UCC_STATUS,ADDEDBY,ADDEDON,ACTIVE_FROM,  

  INACTIVE_FROM,POAFLAG  

 )  

 SELECT DISTINCT  

  A.CL_CODE ,LONG_NAME ,CL_TYPE ,CL_BALANCE='E',CL_STATUS ,BRANCH_CD ,SUB_BROKER,TRADER ,AREA ,REGION ,SBU = 'HO' ,FAMILY,  

  SEX ,OCCUPATION_CODE=OCCUPATION,TAX_STATUS=FMCODE ,PAN_GIR_NO ,KYC_FLAG='Y' ,L_ADDRESS1 ,left(isnull(L_ADDRESS2,50),'') ,left(isnull(L_ADDRESS3,50),''),

  L_CITY ,L_STATE ,L_ZIP ,L_NATION ,P_PHONE ,RES_PHONE1=ISNULL(RES_PHONE1, '') ,MOBILE_PAGER ,EMAIL=ISNULL(EMAIL,'') ,BANK_NAME ,BRANCH_NAME ,BANK_CITY=BRANCH_NAME,    

  AC_NUM ,AC_TYPE = 1 ,MICR_NO ,DOB ,GAURDIAN_NAME='' ,GAURDIAN_PAN_NO='' ,NOMINEE_NAME='' ,NOMINEE_RELATION='',   

  BANK_AC_TYPE= CASE WHEN AC_TYPE = 'CURRENT' THEN 'CB' ELSE 'SB' END ,STAT_COMM_MODE='E' ,DEPOSITORY1 ,DPID1 ,CLTDPID1 ,MODE_HOLDING=CHANNEL_TYPE,  

  HOLDER2_CODE='' ,HOLDER2_NAME=ISNULL(APP_NAME_2, '') ,HOLDER2_PAN_NO=ISNULL(APP_PAN_NO_2, '') ,HOLDER2_KYC_FLAG='' ,  

  HOLDER3_CODE='' ,HOLDER3_NAME=ISNULL(APP_NAME_3, '') ,HOLDER3_PAN_NO=ISNULL(APP_PAN_NO_3, '') ,HOLDER3_KYC_FLAG='' ,  

  BUY_BROK_TABLE_NO = '1',SELL_BROK_TABLE_NO= '1',BROK_EFF_DATE,NEFTCODE=LEFT(IFSC_CODE, 11) ,CHEQUENAME='' ,   

  RESIFAX='' ,OFFICEFAX='' ,MAPINID='' ,REMARK='' ,UCC_STATUS='' ,ADDEDBY='CITRUS' ,ADDEDON=GETDATE() ,  

  ACTIVE_FROM=GETDATE() ,INACTIVE_FROM='DEC 31 2049 23:59' ,  

  POAFLAG  = CASE WHEN POA1=1 THEN 'YES'ELSE 'NO' END  

 FROM #DATA A LEFT OUTER JOIN ABVSCITRUS.CRMDB_A.DBO.VIEW_OTHER_HOLDER_DETAILS ON BO_PARTYCODE = A.CL_CODE,#DATA_BROK B  

 WHERE A.RECVALID = 'Y' AND A.CL_CODE=B.CL_CODE AND B.EXCHANGE='BSE'  AND B.SEGMENT='CAPITAL'  

 AND NOT EXISTS(SELECT PARTY_CODE FROM ANGELFO.BSEMFSS.DBO.MFSS_CLIENT M WHERE A.CL_CODE = M.PARTY_CODE)   

       

 ------------------------------------------------------------------------------------------------------                  

 INSERT INTO ANGELFO.NSEMFSS.DBO.MFSS_CLIENT  

 (  

  PARTY_CODE,PARTY_NAME,CL_TYPE,CL_BALANCE,CL_STATUS,BRANCH_CD,SUB_BROKER,TRADER,AREA,REGION,SBU,  

  FAMILY,GENDER,OCCUPATION_CODE,TAX_STATUS,PAN_NO,KYC_FLAG,ADDR1,ADDR2,ADDR3,CITY,STATE,ZIP,NATION,  

  OFFICE_PHONE,RES_PHONE,MOBILE_NO,EMAIL_ID,BANK_NAME,BANK_BRANCH,BANK_CITY,ACC_NO,PAYMODE,MICR_NO,  

  DOB,GAURDIAN_NAME,GAURDIAN_PAN_NO,NOMINEE_NAME,NOMINEE_RELATION,BANK_AC_TYPE,STAT_COMM_MODE,DP_TYPE,  

  DPID,CLTDPID,MODE_HOLDING,HOLDER2_CODE,HOLDER2_NAME,HOLDER2_PAN_NO,HOLDER2_KYC_FLAG,HOLDER3_CODE,  

  HOLDER3_NAME,HOLDER3_PAN_NO,HOLDER3_KYC_FLAG,BUY_BROK_TABLE_NO,SELL_BROK_TABLE_NO,BROK_EFF_DATE,  

  NEFTCODE,CHEQUENAME,RESIFAX,OFFICEFAX,MAPINID,REMARK,UCC_STATUS,ADDEDBY,ADDEDON,ACTIVE_FROM,  

  INACTIVE_FROM,POAFLAG  

 )  

 SELECT DISTINCT  

  A.CL_CODE ,LONG_NAME ,CL_TYPE ,CL_BALANCE='E',CL_STATUS ,BRANCH_CD ,SUB_BROKER,TRADER ,AREA ,REGION ,SBU = 'HO' ,FAMILY,  

  SEX ,OCCUPATION_CODE=OCCUPATION,TAX_STATUS=FMCODE ,PAN_GIR_NO ,KYC_FLAG='Y' ,L_ADDRESS1 ,left(isnull(L_ADDRESS2,50),'') ,left(isnull(L_ADDRESS3,50),''),  

  L_CITY ,L_STATE ,L_ZIP ,L_NATION ,P_PHONE ,RES_PHONE1=ISNULL(RES_PHONE1, '') ,MOBILE_PAGER ,EMAIL=ISNULL(EMAIL,'') ,BANK_NAME ,BRANCH_NAME ,BANK_CITY=BRANCH_NAME,    

  AC_NUM ,AC_TYPE = 1 ,MICR_NO ,DOB ,GAURDIAN_NAME='' ,GAURDIAN_PAN_NO='' ,NOMINEE_NAME='' ,NOMINEE_RELATION='',   

  BANK_AC_TYPE= CASE WHEN AC_TYPE = 'CURRENT' THEN 'CB' ELSE 'SB' END ,STAT_COMM_MODE='E' ,DEPOSITORY1 ,DPID1 ,CLTDPID1 ,MODE_HOLDING=CHANNEL_TYPE,  

  HOLDER2_CODE='' ,HOLDER2_NAME=ISNULL(APP_NAME_2, '') ,HOLDER2_PAN_NO=ISNULL(APP_PAN_NO_2, '') ,HOLDER2_KYC_FLAG='' ,  

  HOLDER3_CODE='' ,HOLDER3_NAME=ISNULL(APP_NAME_3, '') ,HOLDER3_PAN_NO=ISNULL(APP_PAN_NO_3, '') ,HOLDER3_KYC_FLAG='' ,    

  BUY_BROK_TABLE_NO = '1',SELL_BROK_TABLE_NO= '1',BROK_EFF_DATE,NEFTCODE=LEFT(IFSC_CODE, 11) ,CHEQUENAME='' ,  

  RESIFAX='' ,OFFICEFAX='' ,MAPINID='' ,REMARK='' ,UCC_STATUS='' ,ADDEDBY='CITRUS' ,ADDEDON=GETDATE() ,  

  ACTIVE_FROM=GETDATE() ,INACTIVE_FROM='DEC 31 2049 23:59' ,  

  POAFLAG  =CASE WHEN POA1=1 THEN 'YES'ELSE 'NO' END

 FROM #DATA A LEFT OUTER JOIN ABVSCITRUS.CRMDB_A.DBO.VIEW_OTHER_HOLDER_DETAILS ON BO_PARTYCODE = A.CL_CODE,#DATA_BROK B  

 WHERE A.RECVALID = 'Y' AND A.CL_CODE=B.CL_CODE AND B.EXCHANGE='NSE'  AND B.SEGMENT='CAPITAL'                  

 AND NOT EXISTS(SELECT PARTY_CODE FROM ANGELFO.NSEMFSS.DBO.MFSS_CLIENT M WHERE A.CL_CODE = M.PARTY_CODE)   

       
/*
 DELETE ANGELFO.BBO_FA.DBO.ACMAST  

 FROM ANGELFO.BBO_FA.DBO.ACMAST AS A,#DATA AS B ,#DATA_BROK C  

 WHERE B.RECVALID = 'Y'  

 AND A.CLTCODE = B.PARTY_CODE  

 AND B.CL_CODE=C.CL_CODE   

 AND C.EXCHANGE IN ('NSE','BSE') AND C.SEGMENT='CAPITAL'  
*/
    

 INSERT INTO ANGELFO.BBO_FA.DBO.ACMAST            

 SELECT DISTINCT LONG_NAME ,LONG_NAME ,'ASSET' ,4 ,'' ,PARTY_CODE ,'' ,'A0307000000' ,'' ,MICR_NO ,BRANCH_CD ,0 ,'C' ,'' ,'' ,'' ,'NSE' ,'MFSS'       

 FROM #DATA WHERE RECVALID='Y'  

 AND EXISTS (SELECT TOP 1 * FROM #DATA_BROK WHERE #DATA_BROK.CL_CODE = #DATA.CL_CODE)   

  

 INSERT INTO ANGELFO.BBO_FA.DBO.ACMAST            

 SELECT DISTINCT LONG_NAME ,LONG_NAME ,'ASSET' ,4 ,'' ,PARTY_CODE ,'' ,'A0307000000' ,'' ,MICR_NO ,BRANCH_CD ,0 ,'C' ,'' ,'' ,'' ,'BSE' ,'MFSS'       

 FROM #DATA WHERE RECVALID='Y'  

 AND EXISTS (SELECT TOP 1 * FROM #DATA_BROK WHERE #DATA_BROK.CL_CODE = #DATA.CL_CODE)   

            
/*
 DELETE ANGELFO.NSEMFSS.DBO.MFSS_DPMASTER  

 FROM ANGELFO.NSEMFSS.DBO.MFSS_DPMASTER AS A ,#DATA AS B,#DATA_BROK C  

 WHERE A.PARTY_CODE = B.PARTY_CODE   

 AND B.CL_CODE=C.CL_CODE   

 AND C.EXCHANGE='NSE'AND C.SEGMENT='CAPITAL'  

 AND A.DPID = B.DPID1  

 AND A.CLTDPID = B.CLTDPID1  

 AND B.RECVALID = 'Y'  

  

 DELETE ANGELFO.BSEMFSS.DBO.MFSS_DPMASTER  

 FROM ANGELFO.BSEMFSS.DBO.MFSS_DPMASTER AS A ,#DATA AS B,#DATA_BROK C  

 WHERE A.PARTY_CODE = B.PARTY_CODE   

 AND B.CL_CODE=C.CL_CODE   

 AND C.EXCHANGE='BSE'AND C.SEGMENT='CAPITAL'  

 AND A.DPID = B.DPID1  

 AND A.CLTDPID = B.CLTDPID1  

 AND B.RECVALID = 'Y'  

  */            

 INSERT INTO ANGELFO.NSEMFSS.DBO.MFSS_DPMASTER            

 SELECT DISTINCT  

  A.CL_CODE,LONG_NAME,OCCUPATION_CODE=OCCUPATION,TAX_STATUS=FMCODE,PAN_NO=PAN_GIR_NO,DOB=DOB,  

  GAURDIAN_NAME='',GAURDIAN_PAN_NO='',  

  DP_TYPE=(CASE WHEN DPID1 LIKE '1%' THEN 'CDSL'   

       WHEN DPID1 LIKE 'IN%' THEN 'NSDL' ELSE '' END),  

  DPID=DPID1,  

  CLTDPID=CLTDPID1,MODE_HOLDING=CHANNEL_TYPE,  

  HOLDER2_NAME=ISNULL(APP_NAME_2, ''),HOLDER2_PAN_NO=ISNULL(APP_PAN_NO_2, ''),  

  HOLDER3_NAME=ISNULL(APP_NAME_3, ''),HOLDER3_PAN_NO=ISNULL(APP_PAN_NO_3, ''),  

  DEFAULTDP='1',ADDEDBY='SYSTEM',ADDEDON=GETDATE(),POAFLAG=CASE WHEN POA1=1 THEN 'YES'ELSE 'NO' END       

 FROM #DATA A LEFT OUTER JOIN ABVSCITRUS.CRMDB_A.DBO.VIEW_OTHER_HOLDER_DETAILS ON BO_PARTYCODE = A.CL_CODE,#DATA_BROK B  

 WHERE A.RECVALID = 'Y' AND A.CL_CODE=B.CL_CODE AND EXCHANGE='NSE'  AND SEGMENT='CAPITAL'  

              

 INSERT INTO ANGELFO.BSEMFSS.DBO.MFSS_DPMASTER            

 SELECT DISTINCT  

  A.CL_CODE,LONG_NAME,OCCUPATION_CODE=OCCUPATION,TAX_STATUS=FMCODE,PAN_NO=PAN_GIR_NO,DOB=DOB,  

  GAURDIAN_NAME='',GAURDIAN_PAN_NO='',  

        DP_TYPE=(CASE WHEN DPID1 LIKE '1%' THEN 'CDSL'   

       WHEN DPID1 LIKE 'IN%' THEN 'NSDL' ELSE '' END),  

     DPID=DPID1,  

  CLTDPID=CLTDPID1,MODE_HOLDING=CHANNEL_TYPE,  

  HOLDER2_NAME=ISNULL(APP_NAME_2, ''),HOLDER2_PAN_NO=ISNULL(APP_PAN_NO_2, ''),  

  HOLDER3_NAME=ISNULL(APP_NAME_3, ''),HOLDER3_PAN_NO=ISNULL(APP_PAN_NO_3, ''),  

  DEFAULTDP='1',ADDEDBY='SYSTEM',ADDEDON=GETDATE(),POAFLAG=CASE WHEN POA1=1 THEN 'YES'ELSE 'NO' END       

 FROM #DATA A LEFT OUTER JOIN ABVSCITRUS.CRMDB_A.DBO.VIEW_OTHER_HOLDER_DETAILS ON BO_PARTYCODE = A.CL_CODE,#DATA_BROK B  

 WHERE A.RECVALID = 'Y' AND A.CL_CODE=B.CL_CODE AND EXCHANGE='BSE'  AND SEGMENT='CAPITAL'  

   
/*
 UPDATE ANGELFO.NSEMFSS.DBO.MFSS_BROKERAGE_MASTER  

 SET TODATE = DATEADD(D, - 1, CONVERT(VARCHAR(11), CONVERT(DATETIME, GETDATE(), 103), 109) + ' 23:59')  

 FROM #DATA A ,ANGELFO.NSEMFSS.DBO.MFSS_BROKERAGE_MASTER B ,#DATA_BROK C  

 WHERE A.PARTY_CODE = B.PARTY_CODE  

 AND A.CL_CODE=C.CL_CODE AND C.EXCHANGE='NSE'AND C.SEGMENT='CAPITAL'  

 AND GETDATE() BETWEEN FROMDATE AND TODATE  

  

 UPDATE ANGELFO.BSEMFSS.DBO.MFSS_BROKERAGE_MASTER  

 SET TODATE = DATEADD(D, - 1, CONVERT(VARCHAR(11), CONVERT(DATETIME, GETDATE(), 103), 109) + ' 23:59')  

 FROM #DATA A ,ANGELFO.BSEMFSS.DBO.MFSS_BROKERAGE_MASTER B ,#DATA_BROK C  

 WHERE A.PARTY_CODE = B.PARTY_CODE  

 AND A.CL_CODE=C.CL_CODE AND C.EXCHANGE='BSE'AND C.SEGMENT='CAPITAL'  

 AND GETDATE() BETWEEN FROMDATE AND TODATE  

  */

 INSERT INTO ANGELFO.NSEMFSS.DBO.MFSS_BROKERAGE_MASTER 

 (

	PARTY_CODE,

	BUY_BROK_TABLE_NO,

	SELL_BROK_TABLE_NO,

	FROMDATE,

	TODATE

 )

 SELECT DISTINCT  

 PARTY_CODE,BUY_BROK_TABLE_NO='1',SELL_BROK_TABLE_NO='1',BROK_EFF_DATE=LEFT(GETDATE(),11) ,'DEC 31 2049 23:59'    

 FROM #DATA A,#DATA_BROK B   

 WHERE A.RECVALID = 'Y' AND A.CL_CODE=B.CL_CODE AND B.EXCHANGE='NSE'  AND B.SEGMENT='CAPITAL'   

 AND EXISTS(SELECT PARTY_CODE FROM ANGELFO.NSEMFSS.DBO.MFSS_CLIENT M WHERE A.CL_CODE = M.PARTY_CODE)   

             

 INSERT INTO ANGELFO.BSEMFSS.DBO.MFSS_BROKERAGE_MASTER            

 (

	PARTY_CODE,

	BUY_BROK_TABLE_NO,

	SELL_BROK_TABLE_NO,

	FROMDATE,

	TODATE

 )

 SELECT DISTINCT   

 PARTY_CODE,BUY_BROK_TABLE_NO='1',SELL_BROK_TABLE_NO='1',BROK_EFF_DATE=LEFT(GETDATE(),11) ,'DEC 31 2049 23:59'    

 FROM #DATA A,#DATA_BROK B   

 WHERE A.RECVALID = 'Y' AND A.CL_CODE=B.CL_CODE AND B.EXCHANGE='BSE'  AND B.SEGMENT='CAPITAL'   

 AND EXISTS(SELECT PARTY_CODE FROM ANGELFO.BSEMFSS.DBO.MFSS_CLIENT M WHERE A.CL_CODE = M.PARTY_CODE)   

  

 /*  

 DELETE BBO_FA.DBO.MULTIBANKID  

 FROM BBO_FA.DBO.MULTIBANKID AS A,#DATA AS B ,#DATA_BROK C   

 WHERE B.RECVALID = 'Y'  

 AND A.CLTCODE = B.PARTY_CODE  

 AND B.CL_CODE=C.CL_CODE AND C.EXCHANGE='NSE'AND C.SEGMENT='CAPITAL'    

            

 INSERT INTO BBO_FA.DBO.MULTIBANKID            

 SELECT DISTINCT PARTY_CODE,ISNULL(BANKID,'0'),AC_NUM,'SB',SHORT_NAME,'1','NSE','MFSS'  

 FROM #DATA A,#DATA_BROK B  

 WHERE A.RECVALID = 'Y' AND A.CL_CODE=B.CL_CODE AND B.EXCHANGE='NSE'  AND B.SEGMENT='CAPITAL'  

 */  

  

 DELETE ANGELFO.BBO_FA.DBO.MULTIBANKID  

 FROM ANGELFO.BBO_FA.DBO.MULTIBANKID AS A,#DATA AS B  

 WHERE B.RECVALID = 'Y'  

 AND B.CL_CODE=A.CLTCODE AND SEGMENT='MFSS'    

            

 INSERT INTO ANGELFO.BBO_FA.DBO.MULTIBANKID  

 (Cltcode,Bankid,Accno,Acctype,Chequename,Defaultbank,exchange,segment)

 SELECT DISTINCT PARTY_CODE,ISNULL(BANKID,'0'),AC_NUM,'SB',SHORT_NAME,'1','NSE','MFSS'  

 FROM #DATA A  

 WHERE A.RECVALID = 'Y'  

  

 INSERT INTO ANGELFO.BBO_FA.DBO.MULTIBANKID  

 (Cltcode,Bankid,Accno,Acctype,Chequename,Defaultbank,exchange,segment)

 SELECT DISTINCT PARTY_CODE,ISNULL(BANKID,'0'),AC_NUM,'SB',SHORT_NAME,'1','BSE','MFSS'  

 FROM #DATA A  

 WHERE A.RECVALID = 'Y'    

 ------------------------CLIENT LOG-IN CREATION FOR CLASS BO ACCESS------------------------  

 /*  

 DECLARE                                        

    @PARTYCUR CURSOR,                                        

    @USERID  VARCHAR(20),                               

    @PARTYCODE  VARCHAR(10) ,                                

    @PARTYNAME  VARCHAR(100)                           

                                  

    DECLARE @@ADMINCOUNT INT                               

    DECLARE @@CONTROLCOUNT INT                                    

    DECLARE @@USERCOUNT INT                                    

    DECLARE @@CATEGORYCODE INT                                    

    DECLARE @@USERLOGINID INT                           

    DECLARE @@ADMINAUTO INT      

    DECLARE @CLTDPID1 VARCHAR(16)      

  

    DECLARE @PASSWORD VARCHAR(20)  

    -- GETTING RANDON PASSWORD    

   ;WITH n(n) AS (SELECT 1 UNION ALL SELECT n+1 FROM n WHERE n<36)  

   SELECT @PASSWORD = LEFT((SELECT ''+SUBSTRING('0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ',n,1)  

   FROM n ORDER BY NEWID() FOR XML PATH('')),8)  

     

   SET @PARTYCUR = CURSOR FOR                                    

    SELECT   

    DISTINCT CL_CODE,  

    CL_CODE,LONG_NAME,RIGHT(CLTDPID1,8)                                

    FROM                                  

     #DATA                                  

    WHERE CL_CODE NOT IN                                   

     (                                  

      SELECT FLDUSERNAME FROM MSAJAG.DBO.TBLPRADNYAUSERS                                  

     )                                  

       AND EXISTS (SELECT TOP 1 * FROM #DATA_BROK WHERE #DATA_BROK.CL_CODE = #DATA.CL_CODE)                                

   OPEN @PARTYCUR                                                  

   FETCH NEXT FROM @PARTYCUR INTO @USERID,@PARTYCODE,@PARTYNAME,@CLTDPID1                                

   WHILE @@FETCH_STATUS = 0                                         

   BEGIN                                  

     SELECT @@ADMINCOUNT = COUNT(1) FROM TBLADMIN WHERE UPPER(FLDSTATUS) = 'CLIENT'                                     

     IF @@ADMINCOUNT >0                

     BEGIN                                    

   SELECT @@ADMINCOUNT = COUNT(1) FROM TBLCATEGORY WHERE UPPER(FLDCATEGORYNAME) = 'CLIENT'                                       

     IF @@ADMINCOUNT >0                                    

     BEGIN                                    

                                        

     SELECT @@USERCOUNT = COUNT(1) FROM TBLPRADNYAUSERS WHERE FLDUSERNAME = @USERID                          

     IF @@USERCOUNT = 0                                    

     BEGIN                                              

    SELECT @@CATEGORYCODE = FLDCATEGORYCODE FROM TBLCATEGORY WHERE UPPER(FLDCATEGORYNAME) = 'CLIENT'                                    

                                          

    SELECT @@ADMINAUTO = FLDAUTO_ADMIN FROM TBLADMIN WHERE UPPER(FLDSTATUS) = 'CLIENT'                                       

                              

    INSERT INTO MSAJAG.DBO.TBLPRADNYAUSERS                                    

    (FLDUSERNAME,FLDPASSWORD,FLDFIRSTNAME,FLDMIDDLENAME,FLDLASTNAME,FLDSEX,FLDADDRESS1,FLDADDRESS2,FLDPHONE1,FLDPHONE2,FLDCATEGORY,FLDADMINAUTO,FLDSTNAME,PWD_EXPIRY_DATE)                                    

    VALUES                                    

    (@USERID, @PASSWORD, LEFT(@PARTYNAME,25), '','', 'MALE',                                    

    '','','','', @@CATEGORYCODE, @@ADMINAUTO, @PARTYCODE, 'DEC 31 2049')                                    

  

    SELECT @@USERLOGINID = FLDAUTO FROM MSAJAG.DBO.TBLPRADNYAUSERS WHERE FLDUSERNAME = @USERID                                    

  

    INSERT INTO MSAJAG.DBO.TBLUSERCONTROLMASTER                                    

    (FLDUSERID,FLDPWDEXPIRY,FLDMAXATTEMPT,FLDATTEMPTCNT,FLDSTATUS,FLDLOGINFLAG,FLDACCESSLVL,FLDIPADD,FLDTIMEOUT,FLDFIRSTLOGIN,FLDFORCELOGOUT,FLD_MAC_ID)                                    

    VALUES                                    

    (@@USERLOGINID, 365, 100, 0, 0, 0, 'F', '', 30, 'N', 0,'')                                  

     END                                  

    END                                    

  END                                

                                 

 FETCH NEXT FROM @PARTYCUR INTO @USERID,@PARTYCODE,@PARTYNAME,@CLTDPID1                                  

 END                                        

 CLOSE @PARTYCUR                           

 DEALLOCATE @PARTYCUR  

 */  

END                             

           

           

UPDATE #DATA_BROK SET RECVALID ='N'  

WHERE NOT EXISTS (SELECT CL_CODE FROM CLIENT_BROK_DETAILS WHERE CLIENT_BROK_DETAILS.CL_CODE = #DATA_BROK.CL_CODE  

     AND CLIENT_BROK_DETAILS.EXCHANGE = #DATA_BROK.EXCHANGE  

     AND CLIENT_BROK_DETAILS.SEGMENT = #DATA_BROK.SEGMENT)  

  

UPDATE #DATA SET RECVALID ='N'  

WHERE NOT EXISTS (SELECT CL_CODE FROM CLIENT_DETAILS WHERE CLIENT_DETAILS.CL_CODE = #DATA.CL_CODE)  

  

UPDATE #DATA_BROK SET RECVALID ='N'  

WHERE EXISTS (SELECT CL_CODE FROM #DATA WHERE #DATA.CL_CODE = #DATA_BROK.CL_CODE AND #DATA.RECVALID='N')   

  

UPDATE #DATA SET RECVALID ='N'  

WHERE EXISTS (SELECT CL_CODE FROM #DATA_BROK WHERE #DATA.CL_CODE = #DATA_BROK.CL_CODE AND #DATA_BROK.RECVALID='N')   

  

--SET XACT_ABORT ON  

  

---- UPDATE CITRUS TABLE FOR THE FLAG  

DECLARE                       

 @CRNNO BIGINT,  

 @CRNCUR CURSOR  

            

SET @CRNCUR = CURSOR FOR  

SELECT DISTINCT SRNO FROM #DATA WHERE RECVALID='Y'  

UNION  

SELECT DISTINCT SRNO FROM #DATA_BROK WHERE RECVALID='Y'  

  

OPEN @CRNCUR  

            

FETCH NEXT FROM @CRNCUR INTO @CRNNO      

WHILE @@FETCH_STATUS = 0             

BEGIN            

 EXEC ABVSCITRUS.CRMDB_A.DBO.SP_CLASS_MIG_STATUS_UPD 'E','N',@CRNNO  

 FETCH NEXT FROM @CRNCUR INTO @CRNNO      

END            

CLOSE @CRNCUR            

DEALLOCATE @CRNCUR         

  

--SET XACT_ABORT OFF  

  

DROP TABLE #DATA                  

DROP TABLE #DATA_BROK               

  

END

GO
