-- Object: PROCEDURE dbo.RPT_CROSSMARGIN
-- Server: 10.253.33.91 | DB: MSAJAG
--------------------------------------------------


CREATE PROC RPT_CROSSMARGIN
(
	@STATUSID VARCHAR(25), @STATUSNAME VARCHAR(25), 
	@FROMDATE VARCHAR(11), @TODATE VARCHAR(11), 
	@FROMPARTY VARCHAR(10), @TOPARTY VARCHAR(10), 
	@REPORTFOR VARCHAR(10)
) 

AS

IF @REPORTFOR = 'FAIL' 
BEGIN
	SELECT REPORT_DATE=CONVERT(VARCHAR,REPORT_DATE,103),T.CL_CODE,LONG_NAME,FILENAME,
	UPLOADED_BY,UPLOADED_ON=CONVERT(VARCHAR,UPLOADED_ON), 
	DD = DAY(REPORT_DATE), MM = MONTH(REPORT_DATE), YY = YEAR(REPORT_DATE) 
	FROM TBL_CROSS_MARGIN_STATUS T, CLIENT_DETAILS C
	WHERE REPORT_DATE BETWEEN @FROMDATE AND @TODATE + ' 23:59:59'
	AND T.CL_CODE BETWEEN @FROMPARTY AND @TOPARTY
	AND T.CL_CODE = C.CL_CODE
	AND @STATUSNAME =             
					  (CASE             
							WHEN @STATUSID = 'BRANCH' THEN C.BRANCH_CD            
							WHEN @STATUSID = 'SUBBROKER' THEN C.SUB_BROKER            
							WHEN @STATUSID = 'TRADER' THEN C.TRADER            
							WHEN @STATUSID = 'FAMILY' THEN C.FAMILY            
							WHEN @STATUSID = 'AREA' THEN C.AREA            
							WHEN @STATUSID = 'REGION' THEN C.REGION            
							WHEN @STATUSID = 'CLIENT' THEN C.CL_CODE
					  ELSE             
							'BROKER'            
					  END)    
	UNION
	SELECT REPORT_DATE=CONVERT(VARCHAR,REPORT_DATE,103),T.CL_CODE,LONG_NAME=T.CL_CODE,FILENAME,
	UPLOADED_BY,UPLOADED_ON=CONVERT(VARCHAR,UPLOADED_ON), 
	DD = DAY(REPORT_DATE), MM = MONTH(REPORT_DATE), YY = YEAR(REPORT_DATE) 
	FROM TBL_CROSS_MARGIN_STATUS T
	WHERE REPORT_DATE BETWEEN @FROMDATE AND @TODATE + ' 23:59:59'
	AND T.CL_CODE BETWEEN @FROMPARTY AND @TOPARTY
	AND @STATUSNAME = 'BROKER'            
	AND T.CL_CODE NOT IN (SELECT CL_CODE FROM CLIENT_DETAILS C WHERE T.CL_CODE = C.CL_CODE)            
	ORDER BY T.CL_CODE, YEAR(REPORT_DATE) ASC, MONTH(REPORT_DATE) ASC, DAY(REPORT_DATE) ASC
END 

IF @REPORTFOR = 'MG15' 
BEGIN
	SELECT REPORT_DATE=CONVERT(VARCHAR,REPORT_DATE,103),T.CL_CODE,LONG_NAME,
	INTIAL_MARGIN_BENEFIT, EXPOSURE_MARGIN_BENEFIT, 
	TOTALMARGIN_BENEFIT = INTIAL_MARGIN_BENEFIT + EXPOSURE_MARGIN_BENEFIT,
	UPLOADED_BY,UPLOADED_ON=CONVERT(VARCHAR,UPLOADED_ON), 
	DD = DAY(REPORT_DATE), MM = MONTH(REPORT_DATE), YY = YEAR(REPORT_DATE)
	FROM TBL_CROSS_MARGIN_MG15 T, CLIENT_DETAILS C
	WHERE REPORT_DATE BETWEEN @FROMDATE AND @TODATE + ' 23:59:59'
	AND T.CL_CODE BETWEEN @FROMPARTY AND @TOPARTY
	AND T.CL_CODE = C.CL_CODE
	AND @STATUSNAME =             
					  (CASE             
							WHEN @STATUSID = 'BRANCH' THEN C.BRANCH_CD            
							WHEN @STATUSID = 'SUBBROKER' THEN C.SUB_BROKER            
							WHEN @STATUSID = 'TRADER' THEN C.TRADER            
							WHEN @STATUSID = 'FAMILY' THEN C.FAMILY            
							WHEN @STATUSID = 'AREA' THEN C.AREA            
							WHEN @STATUSID = 'REGION' THEN C.REGION            
							WHEN @STATUSID = 'CLIENT' THEN C.CL_CODE
					  ELSE             
							'BROKER'            
					  END)  
	UNION 
	SELECT REPORT_DATE=CONVERT(VARCHAR,REPORT_DATE,103),T.CL_CODE,LONG_NAME=T.CL_CODE,
	INTIAL_MARGIN_BENEFIT, EXPOSURE_MARGIN_BENEFIT, 
	TOTALMARGIN_BENEFIT = INTIAL_MARGIN_BENEFIT + EXPOSURE_MARGIN_BENEFIT,
	UPLOADED_BY,UPLOADED_ON=CONVERT(VARCHAR,UPLOADED_ON), 
	DD = DAY(REPORT_DATE), MM = MONTH(REPORT_DATE), YY = YEAR(REPORT_DATE)
	FROM TBL_CROSS_MARGIN_MG15 T
	WHERE REPORT_DATE BETWEEN @FROMDATE AND @TODATE + ' 23:59:59'
	AND T.CL_CODE BETWEEN @FROMPARTY AND @TOPARTY
	AND @STATUSNAME = 'BROKER'
	AND T.CL_CODE NOT IN (SELECT CL_CODE FROM CLIENT_DETAILS C WHERE T.CL_CODE = C.CL_CODE)            
	ORDER BY T.CL_CODE, YEAR(REPORT_DATE) ASC, MONTH(REPORT_DATE) ASC, DAY(REPORT_DATE) ASC
END 

IF @REPORTFOR = 'XM01' 
BEGIN
	SELECT REPORT_DATE=CONVERT(VARCHAR,REPORT_DATE,103),T.CL_CODE,LONG_NAME,
	CONTRACT_DESC, NET_POSITION, OFFSET_POSITION,
	UPLOADED_BY,UPLOADED_ON=CONVERT(VARCHAR,UPLOADED_ON), 
	DD = DAY(REPORT_DATE), MM = MONTH(REPORT_DATE), YY = YEAR(REPORT_DATE)
	FROM TBL_CROSS_MARGIN_XM01 T, CLIENT_DETAILS C
	WHERE REPORT_DATE BETWEEN @FROMDATE AND @TODATE + ' 23:59:59'
	AND T.CL_CODE BETWEEN @FROMPARTY AND @TOPARTY
	AND T.CL_CODE = C.CL_CODE
	AND @STATUSNAME =             
					  (CASE             
							WHEN @STATUSID = 'BRANCH' THEN C.BRANCH_CD            
							WHEN @STATUSID = 'SUBBROKER' THEN C.SUB_BROKER            
							WHEN @STATUSID = 'TRADER' THEN C.TRADER            
							WHEN @STATUSID = 'FAMILY' THEN C.FAMILY            
							WHEN @STATUSID = 'AREA' THEN C.AREA            
							WHEN @STATUSID = 'REGION' THEN C.REGION            
							WHEN @STATUSID = 'CLIENT' THEN C.CL_CODE
					  ELSE             
							'BROKER'            
					  END) 
	UNION
	SELECT REPORT_DATE=CONVERT(VARCHAR,REPORT_DATE,103),T.CL_CODE,LONG_NAME=T.CL_CODE,
	CONTRACT_DESC, NET_POSITION, OFFSET_POSITION,
	UPLOADED_BY,UPLOADED_ON=CONVERT(VARCHAR,UPLOADED_ON), 
	DD = DAY(REPORT_DATE), MM = MONTH(REPORT_DATE), YY = YEAR(REPORT_DATE)
	FROM TBL_CROSS_MARGIN_XM01 T
	WHERE REPORT_DATE BETWEEN @FROMDATE AND @TODATE + ' 23:59:59'
	AND T.CL_CODE BETWEEN @FROMPARTY AND @TOPARTY
	AND @STATUSNAME = 'BROKER'            
	AND T.CL_CODE NOT IN (SELECT CL_CODE FROM CLIENT_DETAILS C WHERE T.CL_CODE = C.CL_CODE)
	ORDER BY T.CL_CODE, YEAR(REPORT_DATE) ASC, MONTH(REPORT_DATE) ASC, DAY(REPORT_DATE) ASC
END 

IF @REPORTFOR = 'CXM01' 
BEGIN
	SELECT REPORT_DATE=CONVERT(VARCHAR,REPORT_DATE,103),T.CL_CODE,LONG_NAME,
	SETT_NO, SETT_TYPE, SCRIP_CD, SERIES, NETOPENQTY, OFFSETTQTY, ORG_MARGIN, MARGIN_BENEFIT, APPL_MARGIN,
	UPLOADED_BY,UPLOADED_ON=CONVERT(VARCHAR,UPLOADED_ON), 
	DD = DAY(REPORT_DATE), MM = MONTH(REPORT_DATE), YY = YEAR(REPORT_DATE), RECORDTYPE
	FROM TBL_CROSS_MARGIN_NSECM_XM01 T, CLIENT_DETAILS C
	WHERE REPORT_DATE BETWEEN @FROMDATE AND @TODATE + ' 23:59:59'  
	AND T.CL_CODE = C.CL_CODE AND RECORDTYPE <> 30
	AND T.CL_CODE BETWEEN @FROMPARTY AND @TOPARTY
	AND @STATUSNAME =             
					  (CASE             
							WHEN @STATUSID = 'BRANCH' THEN C.BRANCH_CD            
							WHEN @STATUSID = 'SUBBROKER' THEN C.SUB_BROKER            
							WHEN @STATUSID = 'TRADER' THEN C.TRADER            
							WHEN @STATUSID = 'FAMILY' THEN C.FAMILY            
							WHEN @STATUSID = 'AREA' THEN C.AREA            
							WHEN @STATUSID = 'REGION' THEN C.REGION            
							WHEN @STATUSID = 'CLIENT' THEN C.CL_CODE
					  ELSE             
							'BROKER'            
					  END) 
	UNION 
	SELECT REPORT_DATE=CONVERT(VARCHAR,REPORT_DATE,103),T.CL_CODE, LONG_NAME = T.CL_CODE,
	SETT_NO, SETT_TYPE, SCRIP_CD, SERIES, NETOPENQTY, OFFSETTQTY, ORG_MARGIN, MARGIN_BENEFIT, APPL_MARGIN,
	UPLOADED_BY,UPLOADED_ON=CONVERT(VARCHAR,UPLOADED_ON), 
	DD = DAY(REPORT_DATE), MM = MONTH(REPORT_DATE), YY = YEAR(REPORT_DATE), RECORDTYPE
	FROM TBL_CROSS_MARGIN_NSECM_XM01 T
	WHERE REPORT_DATE BETWEEN @FROMDATE AND @TODATE + ' 23:59:59'  
	AND T.CL_CODE BETWEEN @FROMPARTY AND @TOPARTY
	AND @STATUSNAME = 'BROKER' AND RECORDTYPE <> 30            
	AND T.CL_CODE NOT IN (SELECT CL_CODE FROM CLIENT_DETAILS C WHERE T.CL_CODE = C.CL_CODE)
	ORDER BY YEAR(REPORT_DATE) ASC, MONTH(REPORT_DATE) ASC, DAY(REPORT_DATE), 
			 T.CL_CODE, RECORDTYPE, SETT_NO, SETT_TYPE, SCRIP_CD, SERIES ASC
END

GO
