-- Object: PROCEDURE dbo.RPT_UCCFILEGENERATION
-- Server: 10.253.33.91 | DB: MSAJAG
--------------------------------------------------



--EXEC RPT_UCCFILEGENERATION 'JUL 20 2007','OCT  1 2008','0','ZZZZZZ','A','','ZZZZZZZ',''


CREATE  PROC [DBO].[RPT_UCCFILEGENERATION]  
 (  
 @FROMDATE VARCHAR(11),  
 @TODATE VARCHAR(11),  
 @PARTYFROM VARCHAR(10),  
 @PARTYTO VARCHAR(10),  
 @OPTIONVAL VARCHAR(2),
 @FROMBRANCH VARCHAR(15),  
 @TOBRANCH VARCHAR(15),  
 @CLTYPE VARCHAR(2) = ''
 )  
  
 AS  
  
 SET NOCOUNT ON  
  
 SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED  
  
 IF @PARTYTO='' BEGIN SET @PARTYTO = 'ZZZZZZ' END
 IF @TOBRANCH='' BEGIN SET @TOBRANCH ='ZZZZZZ' END
  
 CREATE TABLE #CLIENTLIST  
 (PARTY_CODE VARCHAR(10))  
   
 CREATE INDEX [INDXCL2] ON #CLIENTLIST ([PARTY_CODE])  
  
/*-----------------------------------------------------------------------------  
  FETCHING TRADED CLIENT LIST TO #CLIENTLIS  
-----------------------------------------------------------------------------*/  
  
 IF @OPTIONVAL = 'T'  
  BEGIN  
   INSERT INTO #CLIENTLIST  
   SELECT  
    DISTINCT PARTY_CODE  
   FROM  
    SETTLEMENT (NOLOCK)  
   WHERE  
    SAUDA_DATE BETWEEN @FROMDATE AND @TODATE + ' 23:59'  
    AND PARTY_CODE BETWEEN @PARTYFROM AND @PARTYTO  
   
   INSERT INTO #CLIENTLIST  
   SELECT  
    DISTINCT PARTY_CODE  
   FROM  
    HISTORY (NOLOCK)  
   WHERE  
    SAUDA_DATE BETWEEN @FROMDATE AND @TODATE + ' 23:59'  
    AND PARTY_CODE BETWEEN @PARTYFROM AND @PARTYTO  
   
   INSERT INTO #CLIENTLIST  
   SELECT  
    DISTINCT PARTY_CODE  
   FROM  
    ISETTLEMENT (NOLOCK)  
   WHERE  
    SAUDA_DATE BETWEEN @FROMDATE AND @TODATE + ' 23:59'  
    AND PARTY_CODE BETWEEN @PARTYFROM AND @PARTYTO  
   
   INSERT INTO #CLIENTLIST  
   SELECT  
    DISTINCT PARTY_CODE  
   FROM  
    IHISTORY (NOLOCK)  
   WHERE  
    SAUDA_DATE BETWEEN @FROMDATE AND @TODATE + ' 23:59'  
    AND PARTY_CODE BETWEEN @PARTYFROM AND @PARTYTO  
   
  END
 ELSE IF @OPTIONVAL = 'M'
 BEGIN
   INSERT INTO #CLIENTLIST  
   SELECT  
     PARTY_CODE  
   FROM  
    MSAJAG.DBO.CLIENT_DETAILS C (NOLOCK), 
    MSAJAG.DBO.CLIENT_BROK_DETAILS B (NOLOCK)
   WHERE  
    C.CL_CODE = B.CL_CODE 
    AND EXCHANGE = 'NSE' AND SEGMENT = 'CAPITAL'
    AND PARTY_CODE BETWEEN @PARTYFROM AND @PARTYTO
	AND BRANCH_CD BETWEEN @FROMBRANCH AND @TOBRANCH
    AND C.MODIFIDEDON BETWEEN @FROMDATE AND @TODATE + ' 23:59'  
    AND LEFT(SYSTEMDATE,11) <> LEFT(MODIFIDEDON,11)
 END
 ELSE  
  BEGIN  
   INSERT INTO #CLIENTLIST  
   SELECT  
     PARTY_CODE  
   FROM  
    CLIENT2  
   WHERE  
    PARTY_CODE BETWEEN @PARTYFROM AND @PARTYTO  
  END  
   
  
/*-----------------------------------------------------------------------------  
   FETCHING DATA TO #UCC_NSE  
-----------------------------------------------------------------------------*/  

   
 SELECT   
  DISTINCT   
  SEGMENT = 'C',  
  CLIENTCODE = C2.PARTY_CODE,
  LONGNAME = (CASE WHEN ISNULL(ADDEMAILID,'') <> '' AND ADDEMAILID NOT LIKE '%@%' 
			THEN LEFT(REPLACE(REPLACE(REPLACE(ISNULL(ADDEMAILID,''),'.',''),',',''),';',''),150)
			ELSE LEFT(REPLACE(REPLACE(REPLACE(ISNULL(C1.LONG_NAME,''),'.',''),',',''),';',''),150)
		END),
  CATEGORY = (CASE WHEN ISNULL(C1.CL_STATUS,'') IN ('NOR','NRI','ROR','PRO','IND','IN')   
    THEN 'IND'   
    ELSE ISNULL(C1.CL_STATUS,'')   
    END),  
  ADDRESS1 = L_ADDRESS1, ---(CASE WHEN LEN(L_ADDRESS1) < 5 THEN L_ADDRESS1 + ' ' + L_ADDRESS2 ELSE L_ADDRESS1 END),
  ADDRESS2 = L_ADDRESS2,
  ADDRESS3 = L_ADDRESS3,
  FULLADDRESS =   
	   ISNULL(RTRIM(L_ADDRESS1),'') + ' '   
	   + ISNULL(RTRIM(L_ADDRESS2),'') + ' '   
	   + ISNULL(RTRIM(L_ADDRESS3),''),   
  CITY = L_CITY,
  STATE = L_STATE,
  ZIP = ISNULL(L_ZIP,''),  
  NATION = L_NATION,
  ISDCODE = ' ',
  STDCODE = ' ',
  PHONE1 = (CASE WHEN ISNULL(C1.RES_PHONE1,'') <> ''   
		  THEN REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(C1.RES_PHONE1,'/',''),'(',''),')',''),'-',''),':',''),';','')  
		  WHEN ISNULL(C1.RES_PHONE2,'') <> ''   
		  THEN REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(C1.RES_PHONE2,'/',''),'(',''),')',''),'-',''),':',''),';','')  
		  WHEN ISNULL(C1.OFF_PHONE1,'') <> ''   
		  THEN REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(C1.OFF_PHONE1,'/',''),'(',''),')',''),'-',''),':',''),';','')  
		  WHEN ISNULL(C1.OFF_PHONE2,'') <> ''   
		  THEN REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(C1.OFF_PHONE2,'/',''),'(',''),')',''),'-',''),':',''),';','')  
		  ELSE ''  
    		END),
  MOBILENO = ISNULL(C1.MOBILE_PAGER,''), 
  EMAIL = C1.EMAIL,
  AGGREMENTDATE =     
   (CASE WHEN C5.CLIENT_AGRE_DT IS NULL     
    THEN ''     
    ELSE CASE WHEN (LEFT(CONVERT(VARCHAR,C5.CLIENT_AGRE_DT,109),11) ='JAN 1 1900')     
    THEN ''     
    ELSE CASE WHEN (CONVERT(INT, DATENAME(DAY, C5.CLIENT_AGRE_DT)) < 10)     
    THEN ('0' + DATENAME(DAY, C5.CLIENT_AGRE_DT))     
    ELSE (DATENAME(DAY, C5.CLIENT_AGRE_DT))     
    END + '-' + (LEFT(DATENAME(MONTH, C5.CLIENT_AGRE_DT), 3)) + '-' + (CONVERT(VARCHAR, YEAR(C5.CLIENT_AGRE_DT)))     
    END END),  
  DOB = (CASE WHEN C1.CL_STATUS IN ('HUF', 'CC', 'PSF', 'IC', 'MF', 'DFI', 'OCB', 'TS', 'SB','BC') THEN '' ELSE
   (CASE WHEN C5.BIRTHDATE IS NULL   
    THEN ''   
    ELSE CASE WHEN (LEFT(CONVERT(VARCHAR,C5.BIRTHDATE,109),11) ='JAN 1 1900')   
    THEN ''   
    ELSE CASE WHEN (CONVERT(INT, DATENAME(DAY, C5.BIRTHDATE)) < 10)   
    THEN ('0' + DATENAME(DAY, C5.BIRTHDATE))   
    ELSE (DATENAME(DAY, C5.BIRTHDATE))   
    END + '-' + (LEFT(DATENAME(MONTH, C5.BIRTHDATE), 3)) + '-' + (CONVERT(VARCHAR, YEAR(C5.BIRTHDATE)))   
    END END) END),  
  PAN = ISNULL(PAN_GIR_NO, ''),  
  WARD = ISNULL(C1.WARD_NO, ''),  
  PASSPORTNO = ISNULL(C5.PASSPORTDTL, ''),  
  PASSPORTPLACE = ISNULL(C5.PASSPORTPLACEOFISSUE, ''),  
  PASSPORTDATE =  
   (CASE WHEN C5.PASSPORTDATEOFISSUE IS NULL   
    THEN ''   
    ELSE CASE WHEN (LEFT(CONVERT(VARCHAR,C5.PASSPORTDATEOFISSUE,109),11) ='JAN 1 1900')   
    THEN ''   
    ELSE CASE WHEN (CONVERT(INT, DATENAME(DAY, C5.PASSPORTDATEOFISSUE)) < 10)   
    THEN ('0' + DATENAME(DAY, C5.PASSPORTDATEOFISSUE))   
    ELSE (DATENAME(DAY, C5.PASSPORTDATEOFISSUE))   
    END + '-' + (LEFT(DATENAME(MONTH, C5.PASSPORTDATEOFISSUE), 3)) + '-' + (CONVERT(VARCHAR, YEAR(C5.PASSPORTDATEOFISSUE)))   
    END END),  
  DRIVINGLICNO = ISNULL(C5.DRIVELICENDTL, ''),  
  DRIVINGLICPLACE = ISNULL(C5.LICENCENOPLACEOFISSUE, ''),  
  DRIVINGLICDATE =   
   (CASE WHEN C5.LICENCENODATEOFISSUE IS NULL   
    THEN ''   
    ELSE CASE WHEN (LEFT(CONVERT(VARCHAR,C5.LICENCENODATEOFISSUE,109),11) ='JAN 1 1900')   
    THEN ''   
    ELSE CASE WHEN (CONVERT(INT, DATENAME(DAY, C5.LICENCENODATEOFISSUE)) < 10)   
    THEN ('0' + DATENAME(DAY, C5.LICENCENODATEOFISSUE))   
    ELSE (DATENAME(DAY, C5.LICENCENODATEOFISSUE))   
    END + '-' + (LEFT(DATENAME(MONTH, C5.LICENCENODATEOFISSUE), 3)) + '-' + (CONVERT(VARCHAR, YEAR(C5.LICENCENODATEOFISSUE)))   
    END END),  
  VOTERID = ISNULL(C5.VOTERSIDDTL, ''),  
  VOTERIDPLACE = ISNULL(C5.VOTERIDPLACEOFISSUE, ''),  
  VOTERIDDATE =   
   (CASE WHEN C5.VOTERIDDATEOFISSUE IS NULL   
    THEN ''   
    ELSE CASE WHEN (LEFT(CONVERT(VARCHAR,C5.VOTERIDDATEOFISSUE,109),11) ='JAN 1 1900')   
    THEN ''   
    ELSE CASE WHEN (CONVERT(INT, DATENAME(DAY, C5.VOTERIDDATEOFISSUE)) < 10)   
    THEN ('0' + DATENAME(DAY, C5.VOTERIDDATEOFISSUE))   
    ELSE (DATENAME(DAY, C5.VOTERIDDATEOFISSUE))   
    END + '-' + (LEFT(DATENAME(MONTH, C5.VOTERIDDATEOFISSUE), 3)) + '-' + (CONVERT(VARCHAR, YEAR(C5.VOTERIDDATEOFISSUE)))   
    END END),   
  RATIONCARDID = ISNULL(C5.RATIONCARDDTL, ''),  
  RATIONCARDIDPLACE = ISNULL(C5.RATIONCARDPLACEOFISSUE, ''),  
  RATIONCARDIDDATE =  
   (CASE WHEN C5.RATIONCARDDATEOFISSUE IS NULL   
    THEN ''   
    ELSE CASE WHEN (LEFT(CONVERT(VARCHAR,C5.RATIONCARDDATEOFISSUE,109),11) ='JAN 1 1900')   
    THEN ''   
    ELSE CASE WHEN (CONVERT(INT, DATENAME(DAY, C5.RATIONCARDDATEOFISSUE)) < 10)   
    THEN ('0' + DATENAME(DAY, C5.RATIONCARDDATEOFISSUE))   
    ELSE (DATENAME(DAY, C5.RATIONCARDDATEOFISSUE))   
    END + '-' + (LEFT(DATENAME(MONTH, C5.RATIONCARDDATEOFISSUE), 3)) + '-' + (CONVERT(VARCHAR, YEAR(C5.RATIONCARDDATEOFISSUE)))   
    END END),   
  REGNO = ISNULL(C5.REGR_NO, ''),  
  REGAUTHORITY = ISNULL(C5.REGR_AUTH, ''),  
  REGPALCE = ISNULL(C5.REGR_PLACE, ''),  
  REGDATE =   
   (CASE WHEN C5.REGR_DATE IS NULL   
    THEN ''   
    ELSE CASE WHEN (LEFT(CONVERT(VARCHAR,C5.REGR_DATE,109),11) ='JAN 1 1900')   
    THEN ''   
    ELSE CASE WHEN (CONVERT(INT, DATENAME(DAY, C5.REGR_DATE)) < 10)   
    THEN ('0' + DATENAME(DAY, C5.REGR_DATE))   
    ELSE (DATENAME(DAY, C5.REGR_DATE))   
    END + '-' + (LEFT(DATENAME(MONTH, C5.REGR_DATE), 3)) + '-' + (CONVERT(VARCHAR, YEAR(C5.REGR_DATE)))   
    END END),  
  INTRODUCER = ISNULL(C5.INTRODUCER, ''),  
  INTRORELATION = ISNULL(C5.INTROD_RELATION, ''),  
  INTROCLID = ISNULL(C5.INTROD_CLIENT_ID, ''),  
  OTHERACCNO = ISNULL(C5.ANY_OTHER_ACC, ''),  
  SETTMODE = ISNULL(C5.SETT_MODE, ''),  
  OTHERTMCLIENT = ISNULL(C5.DEALING_WITH_OTHRER_TM, ''),  
  UCCCLIENTCODE = SPACE(15),  
  MAPINID = SPACE(20),  
  ENDOFRECDFLAG = ISNULL('E', ''),  
  BANKACCTYPE = SPACE(2),  
  BANKACCOUNT = SPACE(20),  
  BENFACCOUNT = SPACE(20),  
  BANKNAME = SPACE(60),  
  BANKFULLADDRESS = SPACE(255),  
  DPBANKNAME = SPACE(50),  
  DPID = SPACE(20),  
  DEPOSITORY = SPACE(8),  
  NSDL_DEPOSITORYNAME = SPACE(4),   
  NSDL_DEPOSITORYPARTICIPANTID = SPACE(8),  
  NSDL_DEPOSITORYPARTICIPANTNAME = SPACE(25),   
  NSDL_BENEFICIARYACCOUNTID = SPACE(8),  
  CDSL_DEPOSITORYNAME = SPACE(4),   
  CDSL_DEPOSITORYPARTICIPANTID = SPACE(8),  
  CDSL_DEPOSITORYPARTICIPANTNAME = SPACE(25),   
  CDSL_BENEFICIARYACCOUNTID = SPACE(16),  
  CL_ACCOUNTNO = SPACE(25),
  PROOFTYPE = ' ',
  PROOFNO = ' ',
  PROOFISSUEPLACE = ' ',
  PROOFISSUEDATE = ' ',
  CONTACTPERSON1 = SPACE(100),
  DESIGNATIONCONTACTPERSON1 = SPACE(60),
  PANCONTACTPERSON1 = SPACE(10),
  ADDCONTRACTPERSON1 = SPACE(255),
  CONTACTNOCONTACTPERSON1 = SPACE(60),
  EMAILCONTACTPERSON1 = SPACE(60),
  CONTACTPERSON2 = SPACE(100),
  DESIGNATIONCONTACTPERSON2 = SPACE(60),
  PANCONTACTPERSON2 = SPACE(10),
  ADDCONTRACTPERSON2 = SPACE(255),
  CONTACTNOCONTACTPERSON2 = SPACE(60),
  EMAILCONTACTPERSON2 = SPACE(60),
  CONTACTPERSON3 = SPACE(100),
  DESIGNATIONCONTACTPERSON3 = SPACE(60),
  PANCONTACTPERSON3 = SPACE(10),
  ADDCONTRACTPERSON3 = SPACE(255),
  CONTACTNOCONTACTPERSON3 = SPACE(60),
  EMAILCONTACTPERSON3 = SPACE(60),
  UPDATIONFLAG	= CONVERT(VARCHAR(1),'N'),
  RELATIONSHIP	= CONVERT(VARCHAR(1),''),
  MASTERPAN		= CONVERT(VARCHAR(15),''),
  TYPEOFFACILITY= CONVERT(VARCHAR(1),''),
  CIN_NO		= CONVERT(VARCHAR(21),'')

 INTO #UCC_NSE   
  
 FROM   
  CLIENT1 C1(NOLOCK),  
  CLIENT2 C2(NOLOCK),  
  CLIENT5 C5(NOLOCK),
  #CLIENTLIST CL (NOLOCK)

 WHERE   
  C1.CL_CODE = C2.CL_CODE  
  AND C1.CL_CODE = C5.CL_CODE  
  AND CL.PARTY_CODE = C2.PARTY_CODE
  AND C1.CL_TYPE <> 'REM'  
  AND 1 = (CASE   
		WHEN @CLTYPE='' THEN 1   
		WHEN @CLTYPE='I' THEN (CASE WHEN C1.CL_TYPE = 'INS' THEN 1 ELSE 0 END)
		WHEN @CLTYPE='C' THEN (CASE WHEN C1.CL_TYPE <> 'INS' THEN 1 ELSE 0 END)
		ELSE 0  
		END)  
  AND BRANCH_CD BETWEEN @FROMBRANCH AND @TOBRANCH 
  AND C5.SYSTUMDATE BETWEEN   
   CASE WHEN @OPTIONVAL = 'A' THEN @FROMDATE ELSE 'JAN  1 1900' END  
    AND  
   CASE WHEN @OPTIONVAL = 'A' THEN @TODATE + ' 23:59' ELSE 'DEC 31 2049 23:59' END  
  AND C5.ACTIVEFROM BETWEEN  
   CASE WHEN @OPTIONVAL = 'S' THEN @FROMDATE ELSE 'JAN  1 1900' END  
    AND  
   CASE WHEN @OPTIONVAL = 'S' THEN @TODATE + ' 23:59' ELSE 'DEC 31 2049 23:59' END  

  AND C5.INACTIVEFROM NOT BETWEEN  
   CASE WHEN @OPTIONVAL = 'S' THEN @FROMDATE ELSE 'JAN  1 1900' END  
    AND  
   CASE WHEN @OPTIONVAL = 'S' THEN @TODATE + ' 23:59' ELSE '' END  

  AND C5.INACTIVEFROM BETWEEN  
   CASE WHEN @OPTIONVAL = 'I' THEN @FROMDATE ELSE 'JAN  1 1900' END  
    AND  
   CASE WHEN @OPTIONVAL = 'I' THEN @TODATE + ' 23:59' ELSE 'DEC 31 2049 23:59' END  
  
/*-----------------------------------------------------------------------------
  UPDATING #UCC_NSE FOR UCC DETAILS
------------------------------------------------------------------------------*/  
  
	UPDATE
		#UCC_NSE
		SET   
			UCCCLIENTCODE = ISNULL(UC.UCC_CODE,''),
			MAPINID = ISNULL(UC.MAPIDID,'')
		FROM
			UCC_CLIENT UC (NOLOCK)
		WHERE
			UC.PARTY_CODE = #UCC_NSE.CLIENTCODE 

/*-----------------------------------------------------------------------------
  UPDATING #UCC_NSE FOR CLIENT DETAILS
------------------------------------------------------------------------------*/  

	UPDATE
		#UCC_NSE
		SET   
			CONTACTPERSON1 = ISNULL(CD.CONTACT_NAME,''),
			DESIGNATIONCONTACTPERSON1 = ISNULL(CD.DESIGNATION,''),
			PANCONTACTPERSON1 = ISNULL(CD.PANNO,''),
			ADDCONTRACTPERSON1 = 
					LEFT((ISNULL(RTRIM(CD.ADDRESS1),'') + ' '   
					+ ISNULL(RTRIM(CD.ADDRESS2),'') + ' '   
					+ ISNULL(RTRIM(CD.ADDRESS3),'') + ' '   
					+ ISNULL(RTRIM(CD.CITY),'') + ' '   
					+ ISNULL(RTRIM(CD.ZIP),'') + ' '
					+ ISNULL(RTRIM(CD.STATE),'') + ' '
					+ ISNULL(RTRIM(CD.NATION),'')),255),
			CONTACTNOCONTACTPERSON1 = ISNULL(CD.PHONE_NO,''),
			EMAILCONTACTPERSON1 = ISNULL(CD.EMAIL,'')
		FROM
			MSAJAG.DBO.CLIENT_CONTACT_DETAILS CD (NOLOCK)
		WHERE
			CD.CL_CODE = #UCC_NSE.CLIENTCODE 
			AND LINE_NO = 1

/*-----------------------------------------------------------------------------
  UPDATING #UCC_NSE FOR EMAIL / SMS SERVICES DETAILS
------------------------------------------------------------------------------*/  

	UPDATE
		#UCC_NSE
		SET   
			UPDATIONFLAG	= ISNULL(CM.UPDATIONFLAG,'N'),
			RELATIONSHIP	= ISNULL(CM.RELATIONSHIP,''),
			MASTERPAN		= ISNULL(CM.MASTERPAN,''),
			TYPEOFFACILITY	= ISNULL(CM.TYPEOFFACILITY,'')
	FROM
		MSAJAG.DBO.CLIENT_MASTER_UCC_DATA CM (NOLOCK)
	WHERE
		#UCC_NSE.CLIENTCODE = CM.PARTY_CODE

/*-----------------------------------------------------------------------------
  UPDATING #UCC_NSE FOR CIN DETAILS
------------------------------------------------------------------------------*/

	UPDATE
		#UCC_NSE
		SET   
			CIN_NO = ISNULL(CM.CIN,'')
	FROM
		MSAJAG.DBO.CLIENT_MASTER_NOMINEE_DATA CM (NOLOCK)
	WHERE
		#UCC_NSE.CLIENTCODE = CM.PARTY_CODE

/*-----------------------------------------------------------------------------  
  UPDATING #UCC_NSE FOR ACCOUNT DETAILS  
-----------------------------------------------------------------------------*/  
/*  
 UPDATE   
  #UCC_NSE   
  SET BANKACCTYPE =   
   (CASE WHEN LEFT(C4.DEPOSITORY,6) = 'SAVING'   
    THEN '10' ELSE CASE WHEN LEFT(C4.DEPOSITORY,7) = 'CURRENT'   
    THEN '11' ELSE '99' END   
    END),  
  BANKACCOUNT =   
   (CASE WHEN LEFT(C4.DEPOSITORY,7) IN ('SAVING','CURRENT','NRE','NRO')   
    THEN CLTDPID ELSE ''   
    END),  
  CL_ACCOUNTNO=CLTDPID  
 FROM   
  CLIENT4 C4   
 WHERE   
  C4.DEPOSITORY NOT IN ('CDSL', 'NSDL')  
  AND C4.PARTY_CODE = CLIENTCODE  
*/  
/*-----------------------------------------------------------------------------  
  UPDATING #UCC_NSE FOR DP DETAILS  
-----------------------------------------------------------------------------*/  
  
 UPDATE   
  #UCC_NSE   
  SET BENFACCOUNT =  ISNULL(CLTDPID,''),   
  DPID = ISNULL(C4.BANKID,''),   
  DEPOSITORY = ISNULL(C4.DEPOSITORY,'')  
 FROM   
  CLIENT4 C4  
 WHERE   
  C4.DEPOSITORY IN ('CDSL', 'NSDL')     
  AND C4.PARTY_CODE = CLIENTCODE   
  AND DEFDP = 1  
   
/*-----------------------------------------------------------------------------  
  UPDATING #UCC_NSE FOR BANK NAME  
-----------------------------------------------------------------------------*/  
 /* 
 UPDATE   
  #UCC_NSE   
  SET BANKNAME = ISNULL(LEFT(BANK_NAME,60),''),   
  BANKFULLADDRESS = ISNULL(LEFT(BRANCH_NAME,255),'')  
 FROM   
  (SELECT   
   PARTY_CODE,  
   BANK_NAME,   
   BRANCH_NAME   
  FROM   
   CLIENT4 C4,   
   POBANK P  
  WHERE   
   CONVERT(VARCHAR, P.BANKID) = C4.BANKID  
   AND DEPOSITORY NOT IN ('CDSL', 'NSDL')) A  
 WHERE   
  PARTY_CODE = CLIENTCODE  
  */
/*-----------------------------------------------------------------------------  
  UPDATING #UCC_NSE MULTIPLE DP DETAILS  
-----------------------------------------------------------------------------*/  
  
 UPDATE   
  #UCC_NSE   
  SET NSDL_DEPOSITORYNAME = (CASE WHEN M.DPTYPE ='NSDL' THEN LEFT(M.DPTYPE,4) ELSE '' END),  
  NSDL_DEPOSITORYPARTICIPANTID = CASE WHEN M.DPTYPE ='NSDL' THEN LEFT(M.DPID,8) ELSE '' END ,  
  NSDL_DEPOSITORYPARTICIPANTNAME = CASE WHEN M.DPTYPE ='NSDL' THEN LEFT(M.INTRODUCER,25) ELSE '' END,   
  NSDL_BENEFICIARYACCOUNTID = CASE WHEN M.DPTYPE ='NSDL' THEN LEFT(M.CLTDPNO,8) ELSE '' END,
  CDSL_DEPOSITORYNAME = (CASE WHEN M.DPTYPE ='CDSL' THEN LEFT(M.DPTYPE,4) ELSE '' END),  
  CDSL_DEPOSITORYPARTICIPANTID = CASE WHEN M.DPTYPE ='CDSL' THEN LEFT(M.DPID,8) ELSE '' END,  
  CDSL_DEPOSITORYPARTICIPANTNAME = CASE WHEN M.DPTYPE ='CDSL' THEN LEFT(M.INTRODUCER,25) ELSE '' END,   
  CDSL_BENEFICIARYACCOUNTID = CASE WHEN M.DPTYPE ='CDSL' THEN LEFT(M.CLTDPNO,16) ELSE '' END  
 FROM   
  MULTICLTID M  
 WHERE   
  M.DEF=1   
  AND M.PARTY_CODE = CLIENTCODE   


 UPDATE   
  #UCC_NSE SET DPBANKNAME = ISNULL(LEFT(A.BANKNAME,50),'')  
  FROM(   
   SELECT PARTY_CODE,BANKNAME   
   FROM CLIENT4 C4, BANK P  
   WHERE CONVERT(VARCHAR,  P.BANKID) = C4.BANKID  
   AND DEPOSITORY IN ('CDSL', 'NSDL')  
   ) A  
  WHERE PARTY_CODE = CLIENTCODE  
  
/*-----------------------------------------------------------------------------  
  FETCHING FINAL OUTPUT  
-----------------------------------------------------------------------------*/  
  
  
 SELECT *   
 FROM #UCC_NSE   
 ORDER BY CLIENTCODE

GO
