-- Object: PROCEDURE dbo.POP_EPN_LEDGER
-- Server: 10.253.33.91 | DB: MSAJAG
--------------------------------------------------


CREATE PROC POP_EPN_LEDGER
AS

DECLARE @SAUDA_DATE VARCHAR(11),
	@SETTCUR CURSOR 

SET @SETTCUR = CURSOR FOR 
SELECT DISTINCT TRANSDATE FROM TBL_EPN_BENEFIT 
ORDER BY 1 
OPEN @SETTCUR 
FETCH NEXT FROM @SETTCUR INTO @SAUDA_DATE 
WHILE @@FETCH_STATUS = 0 
BEGIN
	EXEC PROC_EPI_LEDGER_INSERT @SAUDA_DATE
	FETCH NEXT FROM @SETTCUR INTO @SAUDA_DATE 
END
CLOSE @SETTCUR 
DEALLOCATE @SETTCUR

GO
