-- Object: PROCEDURE dbo.BROK_MODIFICATION
-- Server: 10.253.33.91 | DB: MSAJAG
--------------------------------------------------

CREATE PROCEDURE [dbo].[BROK_MODIFICATION]    
(    
@FROMDATE DATETIME,    
@TODATE DATETIME    
)    
    
AS    
-----DEL    
---- BROK_MODIFICATION 'APR 23 2019','APR 23 2019'    
    
--SET @FROMDATE ='JUL 11 2018'    
    
--SET @TODATE ='JUL 11 2018'    
    
SELECT DISTINCT PARTY_CODE,EXCHANGE,PREVIOUS_PERC,PREVIOUS_VAL,NEW_PERC,NEW_VAL,FROM_dATE,Scheme_Type INTO #BROK FROM (    
SELECT DISTINCT A.PARTY_CODE,B.TABLE_NO AS TABLENO,A.TABLE_NO,C.PERC AS PREVIOUS_PERC,D.PERC AS NEW_PERC,    
C.MIN_VAL AS PREVIOUS_VAL,D.MIN_VAL AS NEW_VAL    
,B.FROM_dATE AS FROMDATE,B.TO_DATE AS TODATE,A.FROM_dATE,A.TO_DATE ,A.Scheme_Type,'NSE'AS EXCHANGE FROM    
(SELECT * FROM CLIENTBROK_SCHEME WHERE FROM_DATE >=@FROMDATE AND FROM_DATE <=@TODATE    
AND TO_DATE >GETDATE() AND SCHEME_TYPE ='DEL' AND TRADE_TYPE ='NRM')A    
INNER JOIN     
(SELECT A.* FROM     
(SELECT * FROM CLIENTBROK_SCHEME WHERE SCHEME_TYPE ='DEL' AND TRADE_TYPE ='NRM')A    
INNER JOIN     
(SELECT PARTY_CODE,MAX(FROM_dATE) FROM_dATE,MAX(TO_DATE) AS TO_DATE FROM CLIENTBROK_SCHEME    
WHERE TO_DATE < GETDATE() AND SCHEME_TYPE ='DEL' AND TRADE_TYPE ='NRM'     
AND PARTY_CODE IN (SELECT DISTINCT PARTY_CODE FROM CLIENTBROK_SCHEME WHERE FROM_DATE >=@FROMDATE AND FROM_DATE <=@TODATE    
AND TO_DATE >GETDATE() AND SCHEME_TYPE ='DEL' AND TRADE_TYPE ='NRM') GROUP BY PARTY_CODE)B    
ON A.PARTY_CODE=B.PARTY_CODE    
AND A.FROM_DATE =B.FROM_DATE    
AND A.TO_DATE =B.TO_DATE ) B    
ON A.PARTY_CODE=B.PARTY_CODE    
AND A.TABLE_NO <> B.TABLE_NO    
INNER JOIN     
(SELECT DISTINCT TABLE_NO,SUM(CASE WHEN VAL_PERC ='P' then normal else 0 end ) AS PERC,    
SUM(CASE WHEN VAL_PERC ='V' AND Lower_lim =0 then normal else 0 end ) AS MIN_VAL    
 FROM BROKTABLE WHERE TRD_DEL ='D'       
 GROUP BY TABLE_NO) AS C    
ON B.TABLE_NO=C.TABLE_NO    
INNER JOIN     
(SELECT DISTINCT TABLE_NO,SUM(CASE WHEN VAL_PERC ='P' then normal else 0 end ) AS PERC,    
SUM(CASE WHEN VAL_PERC ='V' AND Lower_lim =0 then normal else 0 end ) AS MIN_VAL    
 FROM BROKTABLE WHERE TRD_DEL ='D'       
 GROUP BY TABLE_NO) AS D    
ON A.TABLE_NO=D.TABLE_NO    
    
    
UNION ALL    
--TRD    
SELECT DISTINCT A.PARTY_CODE,B.TABLE_NO AS TABLENO,A.TABLE_NO,C.PERC AS PREVIOUS_PERC,D.PERC AS NEW_PERC,    
C.MIN_VAL AS PREVIOUS_VAL,D.MIN_VAL AS NEW_VAL,    
B.FROM_dATE AS FROMDATE,B.TO_DATE AS TODATE,A.FROM_dATE,A.TO_DATE,A.Scheme_Type,'NSE'AS EXCHANGE   FROM    
(SELECT * FROM CLIENTBROK_SCHEME WHERE FROM_DATE >=@FROMDATE AND FROM_DATE <=@TODATE    
AND TO_DATE >GETDATE() AND SCHEME_TYPE ='TRD' AND TRADE_TYPE ='NRM')A    
INNER JOIN     
(SELECT A.* FROM     
(SELECT * FROM CLIENTBROK_SCHEME WHERE SCHEME_TYPE ='TRD' AND TRADE_TYPE ='NRM')A    
INNER JOIN     
(SELECT PARTY_CODE,MAX(FROM_dATE) FROM_dATE,MAX(TO_DATE) AS TO_DATE FROM CLIENTBROK_SCHEME    
WHERE TO_DATE < GETDATE() AND SCHEME_TYPE ='TRD' AND TRADE_TYPE ='NRM'     
AND PARTY_CODE IN (SELECT DISTINCT PARTY_CODE FROM CLIENTBROK_SCHEME WHERE FROM_DATE >=@FROMDATE AND FROM_DATE <=@TODATE    
AND TO_DATE >GETDATE() AND SCHEME_TYPE ='TRD' AND TRADE_TYPE ='NRM') GROUP BY PARTY_CODE)B    
ON A.PARTY_CODE=B.PARTY_CODE    
AND A.FROM_DATE =B.FROM_DATE    
AND A.TO_DATE =B.TO_DATE ) B    
ON A.PARTY_CODE=B.PARTY_CODE    
AND A.TABLE_NO <> B.TABLE_NO    
INNER JOIN     
(SELECT DISTINCT TABLE_NO,SUM(CASE WHEN VAL_PERC ='P' then Day_puc else 0 end ) AS PERC,    
SUM(CASE WHEN VAL_PERC ='V' AND Lower_lim =0 then Day_puc else 0 end ) AS MIN_VAL    
 FROM BROKTABLE WHERE TRD_DEL IN ('T','F')      
 GROUP BY TABLE_NO)  C    
ON B.TABLE_NO=C.TABLE_NO    
INNER JOIN     
(SELECT DISTINCT TABLE_NO,SUM(CASE WHEN VAL_PERC ='P' then Day_puc else 0 end ) AS PERC,    
SUM(CASE WHEN VAL_PERC ='V' AND Lower_lim =0 then Day_puc else 0 end ) AS MIN_VAL    
 FROM BROKTABLE WHERE TRD_DEL IN ('T','F')      
 GROUP BY TABLE_NO)  D    
ON A.TABLE_NO=D.TABLE_NO    
UNION ALL    
    
SELECT  DISTINCT A.PARTY_CODE,B.TABLE_NO AS TABLENO,A.TABLE_NO,C.PERC AS PREVIOUS_PERC,D.PERC AS NEW_PERC,    
C.MIN_VAL AS PREVIOUS_VAL,D.MIN_VAL AS NEW_VAL,B.FROM_dATE AS FROMDATE,B.TO_DATE AS TODATE,A.FROM_dATE,A.TO_DATE ,A.Scheme_Type,'BSE'AS EXCHANGE FROM    
(SELECT * FROM [AngelBSECM].BSEDB_AB.DBO.CLIENTBROK_SCHEME WHERE FROM_DATE >=@FROMDATE AND FROM_DATE <=@TODATE    
AND TO_DATE >GETDATE() AND SCHEME_TYPE ='DEL' AND TRADE_TYPE ='NRM')A    
INNER JOIN     
(SELECT A.* FROM     
(SELECT * FROM [AngelBSECM].BSEDB_AB.DBO.CLIENTBROK_SCHEME WHERE SCHEME_TYPE ='DEL' AND TRADE_TYPE ='NRM')A    
INNER JOIN     
(SELECT PARTY_CODE,MAX(FROM_dATE) FROM_dATE,MAX(TO_DATE) AS TO_DATE FROM [AngelBSECM].BSEDB_AB.DBO.CLIENTBROK_SCHEME    
WHERE TO_DATE < GETDATE() AND SCHEME_TYPE ='DEL' AND TRADE_TYPE ='NRM'     
AND PARTY_CODE IN (SELECT DISTINCT PARTY_CODE FROM [AngelBSECM].BSEDB_AB.DBO.CLIENTBROK_SCHEME WHERE FROM_DATE >=@FROMDATE AND FROM_DATE <=@TODATE    
AND TO_DATE >GETDATE() AND SCHEME_TYPE ='DEL' AND TRADE_TYPE ='NRM') GROUP BY PARTY_CODE)B    
ON A.PARTY_CODE=B.PARTY_CODE    
AND A.FROM_DATE =B.FROM_DATE    
AND A.TO_DATE =B.TO_DATE ) B    
ON A.PARTY_CODE=B.PARTY_CODE    
AND A.TABLE_NO <> B.TABLE_NO    
INNER JOIN     
(SELECT DISTINCT TABLE_NO,SUM(CASE WHEN VAL_PERC ='P' then normal else 0 end ) AS PERC,    
SUM(CASE WHEN VAL_PERC ='V' AND Lower_lim =0 then normal else 0 end ) AS MIN_VAL FROM [AngelBSECM].BSEDB_AB.DBO.BROKTABLE    
WHERE TRD_DEL ='D'       
 GROUP BY TABLE_NO ) AS C    
ON B.TABLE_NO=C.TABLE_NO    
    
INNER JOIN     
(SELECT DISTINCT TABLE_NO,SUM(CASE WHEN VAL_PERC ='P' then normal else 0 end ) AS PERC,    
SUM(CASE WHEN VAL_PERC ='V' AND Lower_lim =0 then normal else 0 end ) AS MIN_VAL FROM [AngelBSECM].BSEDB_AB.DBO.BROKTABLE     
WHERE TRD_DEL ='D'       
 GROUP BY TABLE_NO ) AS D    
ON A.TABLE_NO=D.TABLE_NO    
    
    
    
UNION ALL    
--TRD    
SELECT  DISTINCT A.PARTY_CODE,B.TABLE_NO AS TABLENO,A.TABLE_NO,C.PERC AS PREVIOUS_PERC,D.PERC AS NEW_PERC,    
C.MIN_VAL AS PREVIOUS_VAL,D.MIN_VAL AS NEW_VAL,B.FROM_dATE AS FROMDATE,B.TO_DATE AS TODATE,A.FROM_dATE,A.TO_DATE,A.Scheme_Type,'BSE'AS EXCHANGE   FROM    
(SELECT * FROM [AngelBSECM].BSEDB_AB.DBO.CLIENTBROK_SCHEME WHERE FROM_DATE >=@FROMDATE AND FROM_DATE <=@TODATE    
AND TO_DATE >GETDATE() AND SCHEME_TYPE ='TRD' AND TRADE_TYPE ='NRM')A    
INNER JOIN     
(SELECT A.* FROM     
(SELECT * FROM [AngelBSECM].BSEDB_AB.DBO.CLIENTBROK_SCHEME WHERE SCHEME_TYPE ='TRD' AND TRADE_TYPE ='NRM')A    
INNER JOIN     
(SELECT PARTY_CODE,MAX(FROM_dATE) FROM_dATE,MAX(TO_DATE) AS TO_DATE FROM [AngelBSECM].BSEDB_AB.DBO.CLIENTBROK_SCHEME    
WHERE TO_DATE < GETDATE() AND SCHEME_TYPE ='TRD' AND TRADE_TYPE ='NRM'     
AND PARTY_CODE IN (SELECT DISTINCT PARTY_CODE FROM [AngelBSECM].BSEDB_AB.DBO.CLIENTBROK_SCHEME WHERE FROM_DATE >=@FROMDATE AND FROM_DATE <=@TODATE    
AND TO_DATE >GETDATE() AND SCHEME_TYPE ='TRD' AND TRADE_TYPE ='NRM') GROUP BY PARTY_CODE)B    
ON A.PARTY_CODE=B.PARTY_CODE    
AND A.FROM_DATE =B.FROM_DATE    
AND A.TO_DATE =B.TO_DATE ) B    
ON A.PARTY_CODE=B.PARTY_CODE    
AND A.TABLE_NO <> B.TABLE_NO    
INNER JOIN     
(SELECT DISTINCT TABLE_NO,SUM(CASE WHEN VAL_PERC ='P' then Day_puc else 0 end ) AS PERC,    
SUM(CASE WHEN VAL_PERC ='V' AND Lower_lim =0 then Day_puc else 0 end ) AS MIN_VAL    
FROM [AngelBSECM].BSEDB_AB.DBO.BROKTABLE WHERE TRD_DEL IN ('T','F')  GROUP BY TABLE_NO  ) AS C    
ON B.TABLE_NO=C.TABLE_NO    
INNER JOIN     
(SELECT DISTINCT TABLE_NO,SUM(CASE WHEN VAL_PERC ='P' then Day_puc else 0 end ) AS PERC,    
SUM(CASE WHEN VAL_PERC ='V' AND Lower_lim =0 then Day_puc else 0 end ) AS MIN_VAL    
FROM [AngelBSECM].BSEDB_AB.DBO.BROKTABLE WHERE TRD_DEL IN ('T','F')  GROUP BY TABLE_NO  ) AS D    
ON A.TABLE_NO=D.TABLE_NO    
    
    
--UNION ALL    
-------OPT    
-- SELECT DISTINCT A.PARTY_CODE,B.OPT_broktable AS OPTBrokTable,A.OPT_broktable,    
-- C.PERC AS PREVIOUS_PERC,D.PERC AS NEW_PERC,    
--C.MIN_VAL AS PREVIOUS_VAL,D.MIN_VAL AS NEW_VAL,B.DATE_FROM AS DATEFROM,B.DATE_TO AS DATETO,A.DATE_FROM,A.DATE_TO,'OPT','NSEFO'AS EXCHANGE   FROM    
--(SELECT * FROM ANGELFO.NSEFO.DBO.FOCLIENTBROKSCHEME WHERE DATE_FROM >=@FROMDATE AND DATE_FROM <=@TODATE    
--AND DATE_TO >GETDATE()  )A    
--INNER JOIN     
--(SELECT A.* FROM     
--(SELECT * FROM ANGELFO.NSEFO.DBO.FOCLIENTBROKSCHEME  )A    
--INNER JOIN     
--(SELECT PARTY_CODE,MAX(DATE_FROM) DATE_FROM,MAX(DATE_TO) AS DATE_TO FROM ANGELFO.NSEFO.DBO.FOCLIENTBROKSCHEME    
--WHERE DATE_TO < GETDATE()       
--AND PARTY_CODE IN (SELECT DISTINCT PARTY_CODE FROM ANGELFO.NSEFO.DBO.FOCLIENTBROKSCHEME WHERE DATE_FROM >=@FROMDATE AND DATE_FROM <=@TODATE    
--AND DATE_TO >GETDATE()  ) GROUP BY PARTY_CODE)B    
--ON A.PARTY_CODE=B.PARTY_CODE    
--AND A.DATE_FROM =B.DATE_FROM    
--AND A.DATE_TO =B.DATE_TO ) B    
--ON A.PARTY_CODE=B.PARTY_CODE    
--AND A.OPT_broktable <> B.OPT_broktable    
--INNER JOIN     
--(SELECT DISTINCT TABLE_NO,SUM(CASE WHEN VAL_PERC ='P' then Day_puc else 0 end ) AS PERC,    
--SUM(CASE WHEN VAL_PERC ='V' AND Lower_lim =0 then Day_puc else 0 end ) AS MIN_VAL FROM ANGELFO.NSEFO.DBO.BROKTABLE    
-- WHERE TRD_DEL IN ('T','F')  GROUP BY TABLE_NO ) AS C    
--ON B.OPT_broktable=C.TABLE_NO    
--INNER JOIN     
--(SELECT DISTINCT TABLE_NO,SUM(CASE WHEN VAL_PERC ='P' then Day_puc else 0 end ) AS PERC,    
--SUM(CASE WHEN VAL_PERC ='V' AND Lower_lim =0 then Day_puc else 0 end ) AS MIN_VAL FROM ANGELFO.NSEFO.DBO.BROKTABLE    
-- WHERE TRD_DEL IN ('T','F')  GROUP BY TABLE_NO ) AS D    
--ON A.OPT_broktable=D.TABLE_NO    
    
    
UNION ALL    
--FUT    
 SELECT DISTINCT A.PARTY_CODE,B.FUT_broktable AS FUTBrokTable,A.FUT_broktable,    
 C.PERC AS PREVIOUS_PERC,D.PERC AS NEW_PERC,    
C.MIN_VAL AS PREVIOUS_VAL,D.MIN_VAL AS NEW_VAL,B.DATE_FROM AS DATEFROM,B.DATE_TO AS DATETO,A.DATE_FROM,A.DATE_TO,'FUT','NSEFO'AS EXCHANGE   FROM    
(SELECT * FROM ANGELFO.NSEFO.DBO.FOCLIENTBROKSCHEME WHERE DATE_FROM >=@FROMDATE AND DATE_FROM <=@TODATE    
AND DATE_TO >GETDATE()  )A    
INNER JOIN     
(SELECT A.* FROM     
(SELECT * FROM ANGELFO.NSEFO.DBO.FOCLIENTBROKSCHEME  )A    
INNER JOIN     
(SELECT PARTY_CODE,MAX(DATE_FROM) DATE_FROM,MAX(DATE_TO) AS DATE_TO FROM ANGELFO.NSEFO.DBO.FOCLIENTBROKSCHEME    
WHERE DATE_TO < GETDATE()       
AND PARTY_CODE IN (SELECT DISTINCT PARTY_CODE FROM ANGELFO.NSEFO.DBO.FOCLIENTBROKSCHEME WHERE DATE_FROM >=@FROMDATE AND DATE_FROM <=@TODATE    
AND DATE_TO >GETDATE()  ) GROUP BY PARTY_CODE)B    
ON A.PARTY_CODE=B.PARTY_CODE    
AND A.DATE_FROM =B.DATE_FROM    
AND A.DATE_TO =B.DATE_TO ) B    
ON A.PARTY_CODE=B.PARTY_CODE    
AND A.FUT_broktable <> B.FUT_broktable    
INNER JOIN     
(SELECT DISTINCT TABLE_NO,SUM(CASE WHEN VAL_PERC ='P' then Day_puc else 0 end ) AS PERC,    
SUM(CASE WHEN VAL_PERC ='V' AND Lower_lim =0 then Day_puc else 0 end ) AS MIN_VAL FROM ANGELFO.NSEFO.DBO.BROKTABLE    
 WHERE TRD_DEL IN ('T','F')  GROUP BY TABLE_NO ) AS C    
ON B.FUT_broktable=C.TABLE_NO    
INNER JOIN     
(SELECT DISTINCT TABLE_NO,SUM(CASE WHEN VAL_PERC ='P' then Day_puc else 0 end ) AS PERC,    
SUM(CASE WHEN VAL_PERC ='V' AND Lower_lim =0 then Day_puc else 0 end ) AS MIN_VAL FROM ANGELFO.NSEFO.DBO.BROKTABLE    
 WHERE TRD_DEL IN ('T','F')  GROUP BY TABLE_NO ) AS D    
ON A.FUT_broktable=D.TABLE_NO    
    
    
    
--UNION ALL    
    
--SELECT DISTINCT A.PARTY_CODE,B.OPT_broktable AS OPTBrokTable,A.OPT_broktable,    
--  C.PERC AS PREVIOUS_PERC,D.PERC AS NEW_PERC,    
--C.MIN_VAL AS PREVIOUS_VAL,D.MIN_VAL AS NEW_VAL,B.DATE_FROM AS DATEFROM,B.DATE_TO AS DATETO,A.DATE_FROM,A.DATE_TO,'OPT','NSX'AS EXCHANGE   FROM    
--(SELECT * FROM ANGELFO.NSECURFO.DBO.FOCLIENTBROKSCHEME WHERE DATE_FROM >=@FROMDATE AND DATE_FROM <=@TODATE    
--AND DATE_TO >GETDATE()  )A    
--INNER JOIN     
--(SELECT A.* FROM     
--(SELECT * FROM ANGELFO.NSECURFO.DBO.FOCLIENTBROKSCHEME  )A    
--INNER JOIN     
--(SELECT PARTY_CODE,MAX(DATE_FROM) DATE_FROM,MAX(DATE_TO) AS DATE_TO FROM ANGELFO.NSECURFO.DBO.FOCLIENTBROKSCHEME    
--WHERE DATE_TO < GETDATE()       
--AND PARTY_CODE IN (SELECT DISTINCT PARTY_CODE FROM ANGELFO.NSECURFO.DBO.FOCLIENTBROKSCHEME WHERE DATE_FROM >=@FROMDATE AND DATE_FROM <=@TODATE    
--AND DATE_TO >GETDATE()  ) GROUP BY PARTY_CODE)B    
--ON A.PARTY_CODE=B.PARTY_CODE    
--AND A.DATE_FROM =B.DATE_FROM    
--AND A.DATE_TO =B.DATE_TO ) B    
--ON A.PARTY_CODE=B.PARTY_CODE    
--AND A.OPT_broktable <> B.OPT_broktable    
--INNER JOIN     
--(SELECT DISTINCT TABLE_NO,SUM(CASE WHEN VAL_PERC ='P' then Day_puc else 0 end ) AS PERC,    
--SUM(CASE WHEN VAL_PERC ='V' AND Lower_lim =0 then Day_puc else 0 end ) AS MIN_VAL FROM ANGELFO.NSECURFO.DBO.BROKTABLE    
-- WHERE TRD_DEL IN ('T','F')  GROUP BY TABLE_NO ) AS C    
--ON B.OPT_broktable=C.TABLE_NO    
--INNER JOIN   --(SELECT DISTINCT TABLE_NO,SUM(CASE WHEN VAL_PERC ='P' then Day_puc else 0 end ) AS PERC,    
--SUM(CASE WHEN VAL_PERC ='V' AND Lower_lim =0 then Day_puc else 0 end ) AS MIN_VAL FROM ANGELFO.NSECURFO.DBO.BROKTABLE    
-- WHERE TRD_DEL IN ('T','F')  GROUP BY TABLE_NO ) AS D    
--ON A.OPT_broktable=D.TABLE_NO    
    
UNION ALL    
    
SELECT DISTINCT A.PARTY_CODE,B.FUT_broktable AS FUTBrokTable,A.FUT_broktable,    
  C.PERC AS PREVIOUS_PERC,D.PERC AS NEW_PERC,    
C.MIN_VAL AS PREVIOUS_VAL,D.MIN_VAL AS NEW_VAL,B.DATE_FROM AS DATEFROM,B.DATE_TO AS DATETO,A.DATE_FROM,A.DATE_TO,'FUT','NSX'AS EXCHANGE    FROM    
(SELECT * FROM ANGELFO.NSECURFO.DBO.FOCLIENTBROKSCHEME WHERE DATE_FROM >=@FROMDATE AND DATE_FROM <=@TODATE    
AND DATE_TO >GETDATE()  )A    
INNER JOIN     
(SELECT A.* FROM     
(SELECT * FROM ANGELFO.NSECURFO.DBO.FOCLIENTBROKSCHEME  )A    
INNER JOIN     
(SELECT PARTY_CODE,MAX(DATE_FROM) DATE_FROM,MAX(DATE_TO) AS DATE_TO FROM ANGELFO.NSECURFO.DBO.FOCLIENTBROKSCHEME    
WHERE DATE_TO < GETDATE()       
AND PARTY_CODE IN (SELECT DISTINCT PARTY_CODE FROM ANGELFO.NSECURFO.DBO.FOCLIENTBROKSCHEME WHERE DATE_FROM >=@FROMDATE AND DATE_FROM <=@TODATE    
AND DATE_TO >GETDATE()  ) GROUP BY PARTY_CODE)B    
ON A.PARTY_CODE=B.PARTY_CODE    
AND A.DATE_FROM =B.DATE_FROM    
AND A.DATE_TO =B.DATE_TO ) B    
ON A.PARTY_CODE=B.PARTY_CODE    
AND A.FUT_broktable <> B.FUT_broktable    
INNER JOIN     
(SELECT DISTINCT TABLE_NO,SUM(CASE WHEN VAL_PERC ='P' then Day_puc else 0 end ) AS PERC,    
SUM(CASE WHEN VAL_PERC ='V' AND Lower_lim =0 then Day_puc else 0 end ) AS MIN_VAL FROM ANGELFO.NSECURFO.DBO.BROKTABLE    
 WHERE TRD_DEL IN ('T','F')  GROUP BY TABLE_NO ) AS C    
ON B.OPT_broktable=C.TABLE_NO    
INNER JOIN     
(SELECT DISTINCT TABLE_NO,SUM(CASE WHEN VAL_PERC ='P' then Day_puc else 0 end ) AS PERC,    
SUM(CASE WHEN VAL_PERC ='V' AND Lower_lim =0 then Day_puc else 0 end ) AS MIN_VAL FROM ANGELFO.NSECURFO.DBO.BROKTABLE    
 WHERE TRD_DEL IN ('T','F')  GROUP BY TABLE_NO ) AS D    
ON A.OPT_broktable=D.TABLE_NO    
    
UNION ALL    
    
----MCDXCDS-------------    
SELECT DISTINCT A.PARTY_CODE,B.OPT_broktable AS OPTBrokTable,A.OPT_broktable,    
  C.PERC AS PREVIOUS_PERC,D.PERC AS NEW_PERC,    
C.MIN_VAL AS PREVIOUS_VAL,D.MIN_VAL AS NEW_VAL,B.DATE_FROM AS DATEFROM,B.DATE_TO AS DATETO,A.DATE_FROM,A.DATE_TO,'OPT','MCDXCDS'AS EXCHANGE   FROM    
(SELECT * FROM ANGELCOMMODITY.MCDXCDS.DBO.FOCLIENTBROKSCHEME WHERE DATE_FROM >=@FROMDATE AND DATE_FROM <=@TODATE    
AND DATE_TO >GETDATE()  )A    
INNER JOIN     
(SELECT A.* FROM     
(SELECT * FROM [AngelCommodity].MCDXCDS.DBO.FOCLIENTBROKSCHEME  )A    
INNER JOIN     
(SELECT PARTY_CODE,MAX(DATE_FROM) DATE_FROM,MAX(DATE_TO) AS DATE_TO FROM ANGELCOMMODITY.MCDXCDS.DBO.FOCLIENTBROKSCHEME    
WHERE DATE_TO < GETDATE()       
AND PARTY_CODE IN (SELECT DISTINCT PARTY_CODE FROM [AngelCommodity].MCDXCDS.DBO.FOCLIENTBROKSCHEME WHERE DATE_FROM >=@FROMDATE AND DATE_FROM <=@TODATE    
AND DATE_TO >GETDATE()  ) GROUP BY PARTY_CODE)B    
ON A.PARTY_CODE=B.PARTY_CODE    
AND A.DATE_FROM =B.DATE_FROM    
AND A.DATE_TO =B.DATE_TO ) B    
ON A.PARTY_CODE=B.PARTY_CODE    
AND A.OPT_broktable <> B.OPT_broktable    
INNER JOIN     
(SELECT DISTINCT TABLE_NO,SUM(CASE WHEN VAL_PERC ='P' then Day_puc else 0 end ) AS PERC,    
SUM(CASE WHEN VAL_PERC ='V' AND Lower_lim =0 then Day_puc else 0 end ) AS MIN_VAL FROM ANGELCOMMODITY.mcdxcds.dbo.BROKTABLE    
 WHERE TRD_DEL IN ('T','F')  GROUP BY TABLE_NO ) AS C    
ON B.OPT_broktable=C.TABLE_NO    
INNER JOIN     
(SELECT DISTINCT TABLE_NO,SUM(CASE WHEN VAL_PERC ='P' then Day_puc else 0 end ) AS PERC,   
SUM(CASE WHEN VAL_PERC ='V' AND Lower_lim =0 then Day_puc else 0 end ) AS MIN_VAL FROM ANGELCOMMODITY.mcdxcds.dbo.BROKTABLE    
 WHERE TRD_DEL IN ('T','F')  GROUP BY TABLE_NO ) AS D    
ON A.OPT_broktable=D.TABLE_NO    
    
    
UNION ALL    
--FUT    
 SELECT DISTINCT A.PARTY_CODE,B.FUT_broktable AS FUTBrokTable,A.FUT_broktable,    
  C.PERC AS PREVIOUS_PERC,D.PERC AS NEW_PERC,    
C.MIN_VAL AS PREVIOUS_VAL,D.MIN_VAL AS NEW_VAL,B.DATE_FROM AS DATEFROM,B.DATE_TO AS DATETO,A.DATE_FROM,A.DATE_TO,'FUT','MCDXCDS'AS EXCHANGE   FROM    
(SELECT * FROM ANGELCOMMODITY.MCDXCDS.DBO.FOCLIENTBROKSCHEME WHERE DATE_FROM >=@FROMDATE AND DATE_FROM <=@TODATE    
AND DATE_TO >GETDATE()  )A    
INNER JOIN     
(SELECT A.* FROM     
(SELECT * FROM ANGELCOMMODITY.MCDXCDS.DBO.FOCLIENTBROKSCHEME  )A    
INNER JOIN     
(SELECT PARTY_CODE,MAX(DATE_FROM) DATE_FROM,MAX(DATE_TO) AS DATE_TO FROM ANGELCOMMODITY.MCDXCDS.DBO.FOCLIENTBROKSCHEME    
WHERE DATE_TO < GETDATE()       
AND PARTY_CODE IN (SELECT DISTINCT PARTY_CODE FROM ANGELCOMMODITY.MCDXCDS.DBO.FOCLIENTBROKSCHEME WHERE DATE_FROM >=@FROMDATE AND DATE_FROM <=@TODATE    
AND DATE_TO >GETDATE()  ) GROUP BY PARTY_CODE)B    
ON A.PARTY_CODE=B.PARTY_CODE    
AND A.DATE_FROM =B.DATE_FROM    
AND A.DATE_TO =B.DATE_TO ) B    
ON A.PARTY_CODE=B.PARTY_CODE    
AND A.FUT_broktable <> B.FUT_broktable    
INNER JOIN     
(SELECT DISTINCT TABLE_NO,SUM(CASE WHEN VAL_PERC ='P' then Day_puc else 0 end ) AS PERC,    
SUM(CASE WHEN VAL_PERC ='V' AND Lower_lim =0 then Day_puc else 0 end ) AS MIN_VAL FROM ANGELCOMMODITY.mcdxcds.dbo.BROKTABLE    
 WHERE TRD_DEL IN ('T','F')  GROUP BY TABLE_NO ) AS C    
ON B.OPT_broktable=C.TABLE_NO    
INNER JOIN     
(SELECT DISTINCT TABLE_NO,SUM(CASE WHEN VAL_PERC ='P' then Day_puc else 0 end ) AS PERC,    
SUM(CASE WHEN VAL_PERC ='V' AND Lower_lim =0 then Day_puc else 0 end ) AS MIN_VAL FROM ANGELCOMMODITY.mcdxcds.dbo.BROKTABLE    
 WHERE TRD_DEL IN ('T','F')  GROUP BY TABLE_NO ) AS D    
ON A.OPT_broktable=D.TABLE_NO ) A    
     
 ALTER TABLE #BROK     
 ALTER COLUMN Scheme_Type VARCHAR(25)    
    
    
 --SELECT * FROM #BROK     
    
 INSERT INTO  #BROK    
 EXEC ANGELFO.NSEFO.DBO.MODIFICATION_OPTIONS @FROMDATE,@TODATE    
    
    
/*** EXISTING BROKERAGE ADDITION ***/    
    
SELECT DISTINCT PARTY_CODE,EXCHANGE,PREVIOUS_PERC,PREVIOUS_VAL,NEW_PERC,NEW_VAL,FROM_dATE,Scheme_Type INTO #TOTBROK FROM (    
SELECT DISTINCT A.PARTY_CODE,C.PERC AS PREVIOUS_PERC,C.PERC AS NEW_PERC,    
C.MIN_VAL AS PREVIOUS_VAL,C.MIN_VAL AS NEW_VAL,    
A.FROM_dATE,A.TO_DATE ,A.Scheme_Type,'NSE'AS EXCHANGE FROM    
(SELECT * FROM CLIENTBROK_SCHEME WHERE TO_DATE >=@FROMDATE    
AND TO_DATE >GETDATE() AND SCHEME_TYPE ='DEL' AND TRADE_TYPE ='NRM'  AND PARTY_CODE IN (SELECT PARTY_CODE FROM #BROK) )A    
INNER JOIN     
(SELECT DISTINCT TABLE_NO,SUM(CASE WHEN VAL_PERC ='P' then normal else 0 end ) AS PERC,    
SUM(CASE WHEN VAL_PERC ='V' AND Lower_lim =0 then normal else 0 end ) AS MIN_VAL    
 FROM BROKTABLE WHERE TRD_DEL ='D'       
 GROUP BY TABLE_NO)  C    
ON A.TABLE_NO=C.TABLE_NO    
    
    
    
UNION ALL    
--TRD    
SELECT DISTINCT A.PARTY_CODE,C.PERC AS PREVIOUS_PERC,C.PERC AS NEW_PERC,    
C.MIN_VAL AS PREVIOUS_VAL,C.MIN_VAL AS NEW_VAL,    
A.FROM_dATE,A.TO_DATE,A.Scheme_Type,'NSE'AS EXCHANGE   FROM    
(SELECT * FROM CLIENTBROK_SCHEME WHERE TO_DATE >=@FROMDATE    
AND TO_DATE >GETDATE() AND SCHEME_TYPE ='TRD' AND TRADE_TYPE ='NRM'  AND PARTY_CODE IN (SELECT PARTY_CODE FROM #BROK))A    
INNER JOIN     
(SELECT DISTINCT TABLE_NO,SUM(CASE WHEN VAL_PERC ='P' then Day_puc else 0 end ) AS PERC,    
SUM(CASE WHEN VAL_PERC ='V' AND Lower_lim =0 then Day_puc else 0 end ) AS MIN_VAL    
 FROM BROKTABLE WHERE TRD_DEL IN ('T','F')      
 GROUP BY TABLE_NO)  C    
ON A.TABLE_NO=C.TABLE_NO    
     
UNION ALL    
    
SELECT  DISTINCT A.PARTY_CODE,C.PERC AS PREVIOUS_PERC,C.PERC AS NEW_PERC,    
C.MIN_VAL AS PREVIOUS_VAL,C.MIN_VAL AS NEW_VAL,A.FROM_dATE,A.TO_DATE ,A.Scheme_Type,'BSE'AS EXCHANGE FROM    
(SELECT * FROM [AngelBSECM].BSEDB_AB.DBO.CLIENTBROK_SCHEME WHERE TO_DATE >=@FROMDATE    
AND TO_DATE >GETDATE() AND SCHEME_TYPE ='DEL' AND TRADE_TYPE ='NRM'  AND PARTY_CODE IN (SELECT PARTY_CODE FROM #BROK))A    
INNER JOIN     
    
(SELECT DISTINCT TABLE_NO,SUM(CASE WHEN VAL_PERC ='P' then normal else 0 end ) AS PERC,    
SUM(CASE WHEN VAL_PERC ='V' AND Lower_lim =0 then normal else 0 end ) AS MIN_VAL FROM [AngelBSECM].BSEDB_AB.DBO.BROKTABLE    
WHERE TRD_DEL ='D'       
 GROUP BY TABLE_NO ) AS C    
ON A.TABLE_NO=C.TABLE_NO    
    
    
UNION ALL    
--TRD    
SELECT  DISTINCT A.PARTY_CODE,C.PERC AS PREVIOUS_PERC,C.PERC AS NEW_PERC,    
C.MIN_VAL AS PREVIOUS_VAL,C.MIN_VAL AS NEW_VAL,A.FROM_dATE,A.TO_DATE,A.Scheme_Type,'BSE'AS EXCHANGE   FROM    
(SELECT * FROM [AngelBSECM].BSEDB_AB.DBO.CLIENTBROK_SCHEME WHERE TO_DATE >=@FROMDATE    
AND TO_DATE >GETDATE() AND SCHEME_TYPE ='TRD' AND TRADE_TYPE ='NRM'  AND PARTY_CODE IN (SELECT PARTY_CODE FROM #BROK))A    
INNER JOIN     
    
(SELECT DISTINCT TABLE_NO,SUM(CASE WHEN VAL_PERC ='P' then Day_puc else 0 end ) AS PERC,    
SUM(CASE WHEN VAL_PERC ='V' AND Lower_lim =0 then Day_puc else 0 end ) AS MIN_VAL    
FROM [AngelBSECM].BSEDB_AB.DBO.BROKTABLE WHERE TRD_DEL IN ('T','F')  GROUP BY TABLE_NO  ) AS C    
ON C.TABLE_NO=A.TABLE_NO    
    
UNION ALL    
--FUT    
 SELECT DISTINCT A.PARTY_CODE,    
 C.PERC AS PREVIOUS_PERC,C.PERC AS NEW_PERC,    
C.MIN_VAL AS PREVIOUS_VAL,C.MIN_VAL AS NEW_VAL,A.DATE_FROM,A.DATE_TO,'FUT','NSEFO'AS EXCHANGE   FROM    
(SELECT * FROM ANGELFO.NSEFO.DBO.FOCLIENTBROKSCHEME WHERE DATE_TO >=@FROMDATE  AND PARTY_CODE IN (SELECT PARTY_CODE FROM #BROK)    
 )A    
INNER JOIN     
    
(SELECT DISTINCT TABLE_NO,SUM(CASE WHEN VAL_PERC ='P' then Day_puc else 0 end ) AS PERC,    
SUM(CASE WHEN VAL_PERC ='V' AND Lower_lim =0 then Day_puc else 0 end ) AS MIN_VAL FROM ANGELFO.NSEFO.DBO.BROKTABLE    
 WHERE TRD_DEL IN ('T','F')  GROUP BY TABLE_NO ) AS C    
ON A.FUT_broktable=C.TABLE_NO    
    
    
    
UNION ALL    
    
SELECT DISTINCT A.PARTY_CODE,    
  C.PERC AS PREVIOUS_PERC,C.PERC AS NEW_PERC,    
C.MIN_VAL AS PREVIOUS_VAL,C.MIN_VAL AS NEW_VAL,A.DATE_FROM,A.DATE_TO,'FUT','NSX'AS EXCHANGE    FROM    
(SELECT * FROM ANGELFO.NSECURFO.DBO.FOCLIENTBROKSCHEME WHERE DATE_TO >=@FROMDATE  AND PARTY_CODE IN (SELECT PARTY_CODE FROM #BROK)    
 )A    
    
INNER JOIN     
(SELECT DISTINCT TABLE_NO,SUM(CASE WHEN VAL_PERC ='P' then Day_puc else 0 end ) AS PERC,    
SUM(CASE WHEN VAL_PERC ='V' AND Lower_lim =0 then Day_puc else 0 end ) AS MIN_VAL FROM ANGELFO.NSECURFO.DBO.BROKTABLE    
 WHERE TRD_DEL IN ('T','F')  GROUP BY TABLE_NO ) AS C    
ON A.FUT_broktable=C.TABLE_NO    
    
UNION ALL    
--FUT    
 SELECT DISTINCT A.PARTY_CODE,    
  C.PERC AS PREVIOUS_PERC,C.PERC AS NEW_PERC,    
C.MIN_VAL AS PREVIOUS_VAL,C.MIN_VAL AS NEW_VAL,A.DATE_FROM,A.DATE_TO,'FUT','MCDXCDS'AS EXCHANGE   FROM    
(SELECT * FROM ANGELCOMMODITY.MCDXCDS.DBO.FOCLIENTBROKSCHEME WHERE DATE_TO >=@FROMDATE  AND PARTY_CODE IN (SELECT PARTY_CODE FROM #BROK)    
 )A    
INNER JOIN     
(SELECT DISTINCT TABLE_NO,SUM(CASE WHEN VAL_PERC ='P' then Day_puc else 0 end ) AS PERC,    
SUM(CASE WHEN VAL_PERC ='V' AND Lower_lim =0 then Day_puc else 0 end ) AS MIN_VAL FROM ANGELCOMMODITY.mcdxcds.dbo.BROKTABLE    
 WHERE TRD_DEL IN ('T','F')  GROUP BY TABLE_NO ) AS C    
ON A.FUT_broktable=C.TABLE_NO    
)A    
    
INSERT INTO #TOTBROK    
SELECT SP_PARTY_CODE AS PARTY_CODE,EXCHANGE,OLD_NSE_brokerage AS PREVIOUS_PERC, '0' PREVIOUS_VAL,new_NSE_brokerage NEW_PERC,'0'NEW_VAL,     
SP_Date_FROM FROM_dATE  ,SCHEME AS SCHEME_TYPE    
 FROM  (    
 SELECT DISTINCT A.SP_PARTY_CODE,A.SP_Min_BrokAmt OLD_NSE_brokerage,A.SP_Scheme_Id AS OLD_SP_Scheme_Id     
 ,A.SP_Min_BrokAmt new_NSE_brokerage,'NIFTY'AS SCHEME ,A.SP_Scheme_Id AS NEW_SP_Scheme_Id ,A.SP_TRD_TYPE ,A.SP_CreatedBy ,'NSEFO'AS EXCHANGE,A.SP_Date_FROM  FROM    
(SELECT * FROM  ANGELFO.NSEFO.DBO.Scheme_Mapping WITH (NOLOCK) WHERE   SP_Date_To >=@FROMDATE    
 AND SP_TRD_TYPE ='TRD' AND SP_SCRIP ='NIFTY' AND  SP_PARTY_CODE IN (SELECT PARTY_CODE FROM #BROK) )A    
    
    
UNION ALL    
    
 SELECT DISTINCT A.SP_PARTY_CODE,A.SP_Min_BrokAmt OLD_NSE_brokerage,A.SP_Scheme_Id AS OLD_SP_Scheme_Id     
 ,A.SP_Min_BrokAmt new_NSE_brokerage,'ALL'AS SCHEME ,A.SP_Scheme_Id AS NEW_SP_Scheme_Id ,A.SP_TRD_TYPE ,A.SP_CreatedBy ,'NSEFO'AS EXCHANGE,A.SP_Date_FROM  FROM    
(SELECT * FROM  ANGELFO.NSEFO.DBO.Scheme_Mapping WITH (NOLOCK) WHERE SP_Date_To >=@FROMDATE    
 AND SP_TRD_TYPE ='TRD' AND SP_SCRIP ='ALL' AND  SP_PARTY_CODE IN (SELECT PARTY_CODE FROM #BROK) )A    
    
UNION ALL    
    
 SELECT DISTINCT A.SP_PARTY_CODE,A.SP_Min_BrokAmt OLD_NSE_brokerage,A.SP_Scheme_Id AS OLD_SP_Scheme_Id     
 ,A.SP_Min_BrokAmt new_NSE_brokerage,'ALL'AS SCHEME ,A.SP_Scheme_Id AS NEW_SP_Scheme_Id ,A.SP_TRD_TYPE ,A.SP_CreatedBy ,'NSX'AS EXCHANGE,A.SP_Date_FROM  FROM    
(SELECT * FROM  ANGELFO.NSECURFO.DBO.Scheme_Mapping WITH (NOLOCK) WHERE SP_Date_To >=@FROMDATE    
 AND SP_TRD_TYPE ='TRD' AND SP_SCRIP ='ALL'  AND  SP_PARTY_CODE IN (SELECT PARTY_CODE FROM #BROK) )A    
    
) A    
    
ALTER TABLE  #TOTBROK    
ADD MOD_CHANGE VARCHAR(10)    
UPDATE #TOTBROK SET MOD_CHANGE ='N'    
    
UPDATE T SET PREVIOUS_PERC =B.PREVIOUS_PERC, PREVIOUS_VAL=B.PREVIOUS_VAL, NEW_PERC=B.NEW_PERC ,    
NEW_VAL =B.NEW_VAL ,MOD_CHANGE='Y' FROM #TOTBROK T,    
 #BROK  B    
 WHERE T.PARTY_CODE =B.Party_Code     
 AND T.EXCHANGE=B.EXCHANGE AND T.Scheme_Type=B.Scheme_Type     
    
 /* REMOVAL OF VBB CLIENTS START : SIVA ***/    
  CREATE INDEX #T ON #TOTBROK(PARTY_CODE)    
    
 DELETE FROM #TOTBROK  WHERE EXISTS (    
 SELECT DISTINCT SP_PARTY_CODE FROM Scheme_Mapping WITH (NOLOCK) WHERE SP_PARTY_CODE=PARTY_CODE AND SP_Computation_Level ='O'     
 AND @FROMDATE BETWEEN SP_Date_From AND SP_Date_To    
 UNION      
  SELECT DISTINCT SP_PARTY_CODE FROM ANGELCOMMODITY.MCDX.DBO.Scheme_Mapping WITH (NOLOCK) WHERE SP_PARTY_CODE=PARTY_CODE AND SP_Computation_Level ='O'     
 AND   @FROMDATE BETWEEN SP_Date_From AND SP_Date_To)    
 /***cOMPLETES***/    
    
    
 /***Clients exception for loader not done****/     
    
 SELECT DISTINCT CL_CODE INTO #CL  FROM CLIENT_BROK_DETAILS WHERE MODIFIEDON >=@FROMDATE AND MODIFIEDON <=@TODATE +' 23:59' AND IMP_STATUS <> '1'    
 AND CONVERT(VARCHAR(11),ACTIVE_DATE,120)<>  CONVERT(VARCHAR(11),BROK_EFF_DATE,120)     
    
/*************Changes End Here **************/     
    
 CREATE INDEX #T ON #CL(CL_CODE)    
    
SELECT B.PARTY_CODE,LONG_NAME,EMAIL,EXCHANGE,PREVIOUS_PERC,PREVIOUS_VAL,NEW_PERC,NEW_VAL,FROM_dATE as Mod_date,Scheme_Type Mod_type,MOD_CHANGE    
 FROM #TOTBROK B,CLIENT_DETAILS D    
WHERE B.PARTY_CODE =D.CL_CODE  AND D.CL_CODE NOT IN (SELECT * FROM #CL)    
ORDER BY PARTY_CODE ,EXCHANGE

GO
