-- Object: PROCEDURE dbo.CUSTOM_SEGMENT_STATUS_REPORT
-- Server: 10.253.33.91 | DB: MSAJAG
--------------------------------------------------

CREATE PROCEDURE [dbo].[CUSTOM_SEGMENT_STATUS_REPORT] (@RUNDATE VARCHAR(11))

AS --- EXEC CUSTOM_SEGMENT_STATUS_REPORT 'MAR 16 2022'

SELECT CL_CODE,PANNO=CONVERT(VARCHAR(20),''),EXCHANGE,SEGMENT,
ACTIVE_DATE=CONVERT(VARCHAR(11),ACTIVE_DATE,105),
INACTIVE_FROM=CONVERT(VARCHAR(11),INACTIVE_FROM,105),
DEACTIVE_VALUE,DEACTIVE_REMARKS,LAST_TRADE_DATE=CONVERT(VARCHAR(11),''),DPID=CONVERT(VARCHAR(20),''),HOLDING_STATUS='N' INTO #DATA
FROM MSAJAG.DBO.CLIENT_BROK_DETAILS WHERE CL_CODE IN (SELECT PARTY_CODE FROM IMPORT_PARTY_CODE)

UPDATE #DATA SET PANNO = B.PAN_GIR_NO FROM DBO.CLIENT_DETAILS B WITH (NOLOCK) WHERE #DATA.CL_CODE = B.CL_CODE

UPDATE #DATA SET DPID = CLIENT_CODE FROM #DATA A,
(SELECT CLIENT_CODE,NISE_PARTY_CODE FROM AngelDP4.DMAT.CITRUS_USR.TBL_CLIENT_MASTER WITH (NOLOCK)) B
WHERE A.CL_CODE = B.NISE_PARTY_CODE

UPDATE #DATA SET HOLDING_STATUS = HOLDING FROM #DATA A,
(SELECT DISTINCT HLD_AC_CODE,HOLDING='Y' FROM AngelDP4.[DMAT].[CITRUS_USR].[HOLDING]) B
WHERE A.DPID = B.HLD_AC_CODE

UPDATE A SET LAST_TRADE_DATE = CONVERT(VARCHAR(11),VDT,105) FROM #DATA A,
(SELECT CLTCODE,VDT=MAX(VDT) FROM ACCOUNT.DBO.LEDGER_ALL WITH (NOLOCK) 
WHERE VTYP='15' GROUP BY CLTCODE) B WHERE A.Cl_CODE = B.CLTCODE

SELECT CL_CODE,PANNO,EXCHANGE,SEGMENT,ACTIVE_DATE,INACTIVE_FROM,DEACTIVE_VALUE,DEACTIVE_REMARKS,LAST_TRADE_DATE,
DPID=''''+DPID,HOLDING_STATUS
FROM #DATA 
ORDER BY CL_CODE

GO
