-- Object: PROCEDURE dbo.MARGIN_PEN_COMINED_ANG
-- Server: 10.253.33.91 | DB: MSAJAG
--------------------------------------------------

      
CREATE PROC [dbo].[MARGIN_PEN_COMINED_ANG](@FROMDATE VARCHAR(11),@TODATE VARCHAR(11),@FROMPARTY VARCHAR(10)= 'A000000000',@TOPARTY VARCHAR(10)= 'ZZZZZZZZZZ')      
      
AS      
      
--MARGIN_PEN_COMINED_ANG 'MAR  6 2023','MAR  6 2023'      
      
SELECT  FORMAT(MARGIN_DATE,'dd/MM/yyyy') as MARGIN_DATE,PARTY_CODE,SHORTAGE,PENALTY_PERC,PENALTY_AMT = CONVERT(NUMERIC (18,2) , PENALTY_AMT),      
  SERVICE_TAX = CONVERT(NUMERIC (18,2) , SERVICE_TAX),DAYS_3_COUNT,MONTH_5_COUNT,LEDGER_POST_FLAG,EXCHANGE       
  INTO #MARGIN_PENALTY       
FROM (      
SELECT  MARGIN_DATE,PARTY_CODE,SHORTAGE,PENALTY_PERC,PENALTY_AMT,DAYS_3_COUNT,MONTH_5_COUNT,LEDGER_POST_FLAG,SERVICE_TAX,EXCHANGE = 'NSE'       
FROM AngelNSECM.MSAJAG.DBO.CMMARGIN_PENALTY WITH (NOLOCK)       
WHERE MARGIN_DATE BETWEEN @FROMDATE AND @TODATE + ' 23:59' AND PARTY_CODE BETWEEN @FROMPARTY AND @TOPARTY      
UNION ALL      
SELECT MARGIN_DATE,PARTY_CODE,SHORTAGE,PENALTY_PERC,PENALTY_AMT,DAYS_3_COUNT,MONTH_5_COUNT,LEDGER_POST_FLAG,SERVICE_TAX,EXCHANGE = 'NSEFO'       
FROM ANGELFO.NSEFO.DBO.FOMARGIN_PENALTY WITH (NOLOCK)       
WHERE MARGIN_DATE BETWEEN @FROMDATE AND @TODATE + ' 23:59' AND PARTY_CODE BETWEEN @FROMPARTY AND @TOPARTY      
UNION ALL      
SELECT MARGIN_DATE,PARTY_CODE,SHORTAGE,PENALTY_PERC,PENALTY_AMT,DAYS_3_COUNT,MONTH_5_COUNT,LEDGER_POST_FLAG,SERVICE_TAX,EXCHANGE = 'NSECUR'       
FROM ANGELFO.NSECURFO.DBO.FOMARGIN_PENALTY WITH (NOLOCK)       
WHERE MARGIN_DATE BETWEEN @FROMDATE AND @TODATE + ' 23:59' AND PARTY_CODE BETWEEN @FROMPARTY AND @TOPARTY      
UNION ALL      
SELECT  MARGIN_DATE,PARTY_CODE,SHORTAGE,PENALTY_PERC,PENALTY_AMT,DAYS_3_COUNT,MONTH_5_COUNT,LEDGER_POST_FLAG,SERVICE_TAX,EXCHANGE = 'NCDX'       
FROM ANGELCOMMODITY.NCDX.DBO.FOMARGIN_PENALTY WITH (NOLOCK)       
WHERE MARGIN_DATE BETWEEN @FROMDATE AND @TODATE + ' 23:59' AND PARTY_CODE BETWEEN @FROMPARTY AND @TOPARTY      
UNION ALL      
SELECT  MARGIN_DATE,PARTY_CODE,SHORTAGE,PENALTY_PERC,PENALTY_AMT,DAYS_3_COUNT,MONTH_5_COUNT,LEDGER_POST_FLAG,SERVICE_TAX,EXCHANGE = 'MCDX'       
FROM ANGELCOMMODITY.MCDX.DBO.FOMARGIN_PENALTY WITH (NOLOCK)       
WHERE MARGIN_DATE BETWEEN @FROMDATE AND @TODATE + ' 23:59' AND PARTY_CODE BETWEEN @FROMPARTY AND @TOPARTY      
 ) AS A        
      
CREATE CLUSTERED INDEX CLTMGR ON #MARGIN_PENALTY (PARTY_CODE)      
  
SELECT DISTINCT PARTY_CODE INTO #MARGIN_PENALTY1 FROM #MARGIN_PENALTY  
  
;WITH CTE AS (SELECT CL_CODE, B2B_B2C FROM #MARGIN_PENALTY1 A , VW_BTB_BTC WHERE A.PARTY_CODE = VW_BTB_BTC.CL_CODE)      
      
--SELECT A.*, B2B_B2C  INTO #MARGIN_PENALTY_FINAL FROM #MARGIN_PENALTY A , VW_B2B_B2C_CLIENT_DETAILS WHERE A.PARTY_CODE = VW_B2B_B2C_CLIENT_DETAILS.CL_CODE      
      
SELECT A.*, B2B_B2C  INTO #MARGIN_PENALTY_FINAL FROM #MARGIN_PENALTY A LEFT OUTER JOIN CTE ON (A.PARTY_CODE = CTE.CL_CODE)  
  
SELECT * FROM #MARGIN_PENALTY_FINAL ORDER BY PARTY_CODE,EXCHANGE      
      
DROP TABLE #MARGIN_PENALTY   
DROP TABLE #MARGIN_PENALTY1   
DROP TABLE #MARGIN_PENALTY_FINAL

GO
