-- Object: PROCEDURE dbo.CLS_OBLIGATION_IMPORT_FILE
-- Server: 10.253.33.91 | DB: MSAJAG
--------------------------------------------------



CREATE PROC [dbo].[CLS_OBLIGATION_IMPORT_FILE] 
(
	@PDATE VARCHAR(11),
	@SETTTYPE VARCHAR(2),
	@SETTNO VARCHAR(20), 
	@SESSIONID VARCHAR(100),
	@UNAME VARCHAR(20) 
) AS 

BEGIN

 DECLARE @RECCNT              INT
 

  TRUNCATE TABLE TBL_OBLIGATION_UDIFF
  DELETE FROM TBL_NSE_OBL WHERE SETT_NO = @SETTNO AND SETT_TYPE = @SETTTYPE 
  
  
  INSERT INTO TBL_OBLIGATION_UDIFF
  SELECT DBO.PIECE(FILE_DATA,',',1),
		DBO.PIECE(FILE_DATA,',',2),
		DBO.PIECE(FILE_DATA,',',3),
		DBO.PIECE(FILE_DATA,',',4),
		DBO.PIECE(FILE_DATA,',',5),
		DBO.PIECE(FILE_DATA,',',6),
		DBO.PIECE(FILE_DATA,',',7),
		DBO.PIECE(FILE_DATA,',',8),
		DBO.PIECE(FILE_DATA,',',9),
		DBO.PIECE(FILE_DATA,',',10),
		DBO.PIECE(FILE_DATA,',',11),
		DBO.PIECE(FILE_DATA,',',12),
		DBO.PIECE(FILE_DATA,',',13),
		DBO.PIECE(FILE_DATA,',',14),
		DBO.PIECE(FILE_DATA,',',15),
		DBO.PIECE(FILE_DATA,',',16),
		DBO.PIECE(FILE_DATA,',',17),
		DBO.PIECE(FILE_DATA,',',18),
		DBO.PIECE(FILE_DATA,',',19),
		DBO.PIECE(FILE_DATA,',',20),
		DBO.PIECE(FILE_DATA,',',21),
		DBO.PIECE(FILE_DATA,',',22),
		DBO.PIECE(FILE_DATA,',',23),
		DBO.PIECE(FILE_DATA,',',24),
		DBO.PIECE(FILE_DATA,',',25),
		DBO.PIECE(FILE_DATA,',',26),
		DBO.PIECE(FILE_DATA,',',27), 
		DBO.PIECE(FILE_DATA,',',28),
		DBO.PIECE(FILE_DATA,',',29),
		DBO.PIECE(FILE_DATA,',',30),
		DBO.PIECE(FILE_DATA,',',31),
		DBO.PIECE(FILE_DATA,',',32),
		DBO.PIECE(FILE_DATA,',',33)
	FROM STAMPDUTY_FILEDATA  
	-- WHERE  
   --SESSION_ID= @SESSIONID   
   --AND LEFT(FILE_DATA,1) <> 'Sgmt'

    UPDATE A SET STTLMTP = PROCESS_VALUE
	FROM TBL_OBLIGATION_UDIFF A,MSAJAG..TBL_STANDARD_VALUES B
		WHERE A.STTLMTP = B.FIELD_VALUE
		AND FIELD_DESC='SETTLEMENTTYPE'
		AND EXCHANGE='NSE'
		AND SEGMENT='CAPITAL'




  INSERT INTO TBL_NSE_OBL  
  SELECT   
		SETT_NO = SCTIESSTTLMTXID,
		SETT_TYPE = STTLMTP,
		TM_CODE = BRKRORCTDNPTCPTID,
		TM_BR_CODE = CLRMMBID,
		PARTICIPANTCODE = CTDNPTCPTID,
		CUST_CODE = CLNTID,
		SCRIP_CD = TCKRSYMB,
		SERIES = SCTYSRS,
		SCRIP_CODE = TCKRSYMB,
		OLB_DATE = CAST(CONVERT(DATETIMEOFFSET,RPTGDT,127) AS DATETIME),
		ND_FLAG = FNLOBLGTNFLG,
		D_PQTY = DALYBUYTRADGVOL,
		D_SQTY = DALYSELLTRADGVOL,
		D_PAMT = DALYBUYTRADGVAL,
		D_SAMT = DALYSELLTRADGVAL,
		C_PQTY = BUYDLVRBLQTY,
		C_SQTY = SELLDLVRBLQTY,
		C_PAMT = BUYDLVRYVAL,
		C_SAMT = SELLDLVRBLVAL,
		FINAL_OBL_FLAG = FNLOBLGTNFLG
  FROM TBL_OBLIGATION_UDIFF
 WHERE SCTIESSTTLMTXID = @SETTNO AND STTLMTP = @SETTTYPE




SELECT @RECCNT = ISNULL(COUNT(1),0) FROM TBL_NSE_OBL WHERE SETT_NO = @SETTNO AND SETT_TYPE = @SETTTYPE 
IF @RECCNT > 0
BEGIN
       SELECT STRMSGCODE = 1, STRMSG = 'FILE UPLOADED SUCCESSFULLY WITH NO OF RECORD(S) ' + CONVERT(VARCHAR,@RECCNT)
END
ELSE
BEGIN
       SELECT STRMSGCODE = -1, STRMSG = 'PLEASE CHECK AND IMPORT CORRECT FILE'
END

END

GO
