-- Object: PROCEDURE dbo.NSENRIHEADER_t1_27may2022
-- Server: 10.253.33.91 | DB: MSAJAG
--------------------------------------------------

CREATE PROC  NSENRIHEADER_t1_27may2022 (@SDATE AS VARCHAR(11),@SELL_BUY AS VARCHAR(1))           
AS                        
DECLARE @@SETT_NO VARCHAR(8) ,@@SETT_NO1 VARCHAR(8)          
          
SELECT @@SETT_NO = SETT_NO FROM SETT_MST WHERE START_DATE LIKE @SDATE+'%'  AND SETT_TYPE ='M'     
SELECT @@SETT_NO1 = SETT_NO FROM SETT_MST WHERE START_DATE LIKE @SDATE+'%'  AND SETT_TYPE ='N'     
        
 SELECT EXCHANGE,A.PARTY_CODE,SAUDA_DATE,SELL_BUY,CONTRACTNO,ROUND(SUM(SERVICE_TAX+ISNULL(NSERTAX,0)),2)SERVICE_TAX,                      
 EDUCESS,EXCHAGE_LEVIES,STT,STAMPDUTY,ISNULL(MINBROKERAGE,0)MINBROKERAGE,OTHER_CHARGES,NO_OF_TRANSACTIONS,                    
 ROUND((TOTALAMT),2)TOTALAMT ,a.SETT_NO                      
 FROM                      
(SELECT  'NSECM' AS EXCHANGE,PARTY_CODE,SAUDA_DATE,SELL_BUY,CONTRACTNO,                        
SUM(NSERTAX)AS SERVICE_TAX,0 AS EDUCESS,ROUND(SUM(TURN_TAX),2) AS EXCHAGE_LEVIES,SUM(INS_CHRG)AS STT,                        
ROUND(SUM(BROKER_CHRG),2) AS STAMPDUTY,                        
ROUND(SUM(SEBI_TAX),2) AS OTHER_CHARGES,COUNT(PARTY_CODE) AS NO_OF_TRANSACTIONS,                        
SUM(PAMT-SAMT)+SUM(INS_CHRG+NSERTAX+BROKER_CHRG+TURN_TAX+SEBI_TAX)                     
AS TOTALAMT  , SETT_NO                     
from CONTRACT_DATA WHERE SETT_NO in (@@SETT_NO,@@SETT_NO1) AND SELL_BUY = @SELL_BUY                      
And SCRIP_CD <>'BROKERAGE'  AND PARTY_CODE IN (                    
SELECT cl_code FROM Client1 WHERE Cl_type ='NRI')                    
GROUP BY PARTY_CODE,SAUDA_DATE,SELL_BUY,CONTRACTNO ,SETT_NO ) A                      
LEFT OUTER JOIN                       
(SELECT  PARTY_CODE,NSERTAX,BROKERAGE AS MINBROKERAGE,SETT_NO                        
from CONTRACT_DATA WHERE SETT_NO in (@@SETT_NO,@@SETT_NO1) AND SELL_BUY = @SELL_BUY                      
AND PARTY_CODE IN (SELECT cl_code FROM Client1 WHERE Cl_type ='NRI')                    
and SCRIP_CD = 'BROKERAGE')B                      
ON A.PARTY_CODE=B.PARTY_CODE and a.SETT_NO=b.SETT_NO                     
GROUP BY EXCHANGE,A.PARTY_CODE,SAUDA_DATE,SELL_BUY,CONTRACTNO,                      
 EDUCESS,EXCHAGE_LEVIES,STT,STAMPDUTY,MINBROKERAGE,OTHER_CHARGES,NO_OF_TRANSACTIONS,TOTALAMT,NSERTAX ,            
 SERVICE_TAX,a.SETT_NO

GO
