-- Object: PROCEDURE dbo.MFSS_AUTO_RECON_NACH_SIP_REPORT
-- Server: 10.253.33.91 | DB: MSAJAG
--------------------------------------------------


CREATE PROCEDURE [dbo].[MFSS_AUTO_RECON_NACH_SIP_REPORT] (@FDATE DATETIME,@TDATE DATETIME)

AS ---EXEC MFSS_AUTO_RECON_NACH_SIP_REPORT 'JUL 11 2021','JUL 12 2021'

SELECT  CLTCODE,VDT,BANKCODE,RELDATE,VNO,EXCHANGE,VAMT,DRCR,DDNO,VTYP,RECONCIL_DATE=IMPORT_DATE,
RECO_USER,RECOSTATUS=CASE WHEN RECO_FLAG='Y' THEN 'RECONCILED' ELSE 'PENDING' END
FROM ANGELFO.BBO_FA.DBO.TBL_MFSS_SIP_NACH WITH (NOLOCK)
WHERE IMPORT_DATE BETWEEN @FDATE AND @TDATE + ' 23:59'
ORDER BY VDT

GO
