-- Object: PROCEDURE dbo.Pdf_CashTradesReport_SummaryNSEFO_Daily_Bak_OCT012024
-- Server: 10.253.33.91 | DB: MSAJAG
--------------------------------------------------






-- =============================================
-- Author:		Dinesh Jadhav
-- Create date: Oct 1 2018
-- Description:	Cash trade summary Report NSEFO
-- =============================================
CREATE  PROCEDURE [dbo].[Pdf_CashTradesReport_SummaryNSEFO_Daily_Bak_OCT012024]
@Frompartycode varchar(20),
@Topartycode varchar(20),
@FromDate varchar(20),
@ToDate varchar(20)

/*
exec  Pdf_CashTradesReport_SummaryNSEFO_Daily 'M79991','M79991','oct  25 2018','oct 25 2018'

*/

AS
BEGIN
DECLARE 
        @@FromDate VARCHAR(50), 
		@@ToDate varchar(50)

		SET @@FromDate=left(ltrim(rtrim(Cast(@FromDate as datetime))),11) +' 00:00:000'
		SET @@ToDate=left(ltrim(rtrim(Cast(@ToDate as datetime))),11)+' 23:59:000'
  
		print  @@ToDate
		print  @@FromDate

		SELECT PARTY_CODE,TRD_DT = CONVERT(VARCHAR(11),SAUDA_DATE,103),TRADETYPE,INST_TYPE,
		SYMBOL=(CASE WHEN SYMBOL ='BROKERAGE' THEN '**Additional Brokerage**' ELSE SYMBOL END),
		EXPIRYDATE,OPTION_TYPE,STRIKE_PRICE,AUCTIONPART,
		CASE WHEN TRADETYPE = 'BF' THEN CASE WHEN SUM(PQTY) > SUM(SQTY) THEN SUM(PQTY) - SUM(SQTY) ELSE 0 END ELSE SUM(PQTY) END AS BUYQTY,        
		CASE WHEN TRADETYPE = 'BF' THEN CASE WHEN SUM(PQTY) > SUM(SQTY) THEN CASE WHEN SUM(PQTY) > 0 THEN SUM(PAMT)/SUM(PQTY) ELSE 0 END ELSE 0 END ELSE 
		CASE WHEN SUM(PQTY) > 0 THEN SUM(PRATE) ELSE 0 END END AS BUYRATE,        
		CASE WHEN TRADETYPE = 'BF' THEN CASE WHEN SUM(PQTY) < SUM(SQTY) THEN SUM(SQTY) - SUM(PQTY) ELSE 0 END ELSE SUM(SQTY) END AS SELLQTY,                          
		CASE WHEN TRADETYPE = 'BF' THEN CASE WHEN SUM(PQTY) < SUM(SQTY) THEN CASE WHEN SUM(SQTY) > 0 THEN SUM(SAMT)/SUM(SQTY) ELSE 0 END ELSE 0 END ELSE
		CASE WHEN SUM(SQTY) > 0 THEN SUM(SRATE) ELSE 0 END END AS SELLRATE,
		BROKERAGE = SUM(PBROKAMT+SBROKAMT), STT = SUM(INS_CHRG),OTHER_TAX  = SUM(SERVICE_TAX+TURN_TAX+SEBI_TAX+BROKER_NOTE),
		CLOSING_RATE = CASE WHEN SUM(PQTY) <> SUM(SQTY)  THEN CL_RATE ELSE 0 END,
		GRAND_TOTAL = SUM(SBILLAMT) - SUM(PBILLAMT+SERVICE_TAX+INS_CHRG+TURN_TAX+SEBI_TAX+BROKER_NOTE), CMclosing
		FROM ANGELFO.NSEFO.DBO.FOBILLVALAN  WITH (NOLOCK)   
		WHERE SAUDA_DATE >=@@FromDate AND SAUDA_DATE <=@@ToDate --AND SYMBOL <> 'BROKERAGE' 
		GROUP BY PARTY_CODE,CONVERT(VARCHAR(11),SAUDA_DATE,103),TRADETYPE,INST_TYPE,SYMBOL,EXPIRYDATE,OPTION_TYPE,STRIKE_PRICE,AUCTIONPART,CMclosing,CL_RATE
		ORDER BY PARTY_CODE,CONVERT(VARCHAR(11),SAUDA_DATE,103),INST_TYPE,SYMBOL,EXPIRYDATE,OPTION_TYPE,STRIKE_PRICE,TRADETYPE
END

GO
