-- Object: PROCEDURE dbo.USP_GST_CreditNote_GSTReport
-- Server: 10.253.33.91 | DB: MSAJAG
--------------------------------------------------


--	USP_GST_CreditNote_GSTReport '1000086', '','01/01/2017',  '30/12/2017','G'

CREATE PROC [dbo].[USP_GST_CreditNote_GSTReport]
@FromPartyCode VARCHAR(20),
@ToPartyCode VARCHAR(20),
@FromDate VARCHAR(20),
@ToDate VARCHAR(20),
@ReportType CHAR -- C FOR Credit Report G FOR GST Report

AS

BEGIN

/*
DECLARE @FromPartyCode VARCHAR(20)
DECLARE @ToPartyCode VARCHAR(20)
DECLARE @FromDate VARCHAR(20)
DECLARE @ToDate VARCHAR(20)

SET @FromPartyCode = 'WXBPANKA'
SET @ToPartyCode = 'WXBPANKA'
SET @FromDate = '01/06/2017'
SET @ToDate  =  '30/12/2017'
*/

IF (@ReportType = 'C')

BEGIN

		SELECT A.PARTY_CODE,LONG_NAME AS Party_Name,DATENAME(MONTH,INVOICE_DATE) + ' ' + DATENAME(YYYY,INVOICE_DATE) AS INVOICE_DATE ,
				B.GST_NO,INV_NO,INVOICE_TYPE, SOURCESTATE,TARGETSTATE, SUM(TAXABLE_AMT) AS TAXABLE_AMT,
			   [TOTAL GST]   = SUM(CGST_AMOUNT) + SUM(SGST_AMOUNT) + SUM(IGST_AMOUNT),
			   SUM(CGST_AMOUNT) AS CGST_AMOUNT , SUM(SGST_AMOUNT) AS SGST_AMOUNT , SUM(IGST_AMOUNT) AS IGST_AMOUNT,
			   [INVOICE VALUE] = SUM(TAXABLE_AMT)  + SUM(CGST_AMOUNT) + SUM(SGST_AMOUNT) + SUM(IGST_AMOUNT) 
		FROM TBL_GST_INVOICE A
				INNER JOIN TBL_CLIENT_GST_DATA B
				ON A.PARTY_CODE = B.PARTY_CODE
		WHERE GETDATE() between EFF_FROM_DATE And EFF_TO_DATE  
				AND A.PARTY_CODE BETWEEN CASE WHEN @FromPartyCode = '' THEN '00' ELSE @FromPartyCode END 
										 AND CASE WHEN @ToPartyCode = '' THEN 'ZZ' ELSE @ToPartyCode END 
				AND A.INVOICE_DATE BETWEEN CONVERT(DATETIME,@FromDate,103) AND CONVERT(DATETIME,@ToDate,103)
		GROUP BY A.PARTY_CODE,LONG_NAME ,DATENAME(MONTH,INVOICE_DATE) + ' ' + DATENAME(YYYY,INVOICE_DATE) ,B.GST_NO,INV_NO,INVOICE_TYPE, SOURCESTATE,TARGETSTATE

END

IF (@ReportType = 'G')

BEGIN

		SELECT A.PARTY_CODE,LONG_NAME AS Party_Name,B.GST_NO,INV_NO as [CREDIT NOTE NUMBER],'' AS [INCOME TYPE],INVOICE_TYPE, SOURCESTATE,TARGETSTATE, SUM(TAXABLE_AMT) AS TAXABLE_AMT,
			   [TOTAL GST]   = SUM(CGST_AMOUNT) + SUM(SGST_AMOUNT) + SUM(IGST_AMOUNT),
				SUM(CGST_AMOUNT) AS CGST_AMOUNT , SUM(SGST_AMOUNT) AS SGST_AMOUNT , SUM(IGST_AMOUNT) AS IGST_AMOUNT,
			   [INVOICE VALUE] = SUM(TAXABLE_AMT)  + SUM(CGST_AMOUNT) + SUM(SGST_AMOUNT) + SUM(IGST_AMOUNT) 
			   ,DATENAME(MONTH,INVOICE_DATE) + ' ' + DATENAME(YYYY,INVOICE_DATE) AS INVOICE_DATE, REV_INT_REF_NO
		FROM TBL_GST_INVOICE A
				INNER JOIN TBL_CLIENT_GST_DATA B
				ON A.PARTY_CODE = B.PARTY_CODE
		WHERE GETDATE() between EFF_FROM_DATE And EFF_TO_DATE  
				AND A.PARTY_CODE BETWEEN CASE WHEN @FromPartyCode = '' THEN '00' ELSE @FromPartyCode END 
										AND CASE WHEN @ToPartyCode = '' THEN 'ZZ' ELSE @ToPartyCode END 
				AND A.INVOICE_DATE BETWEEN CONVERT(DATETIME,@FromDate,103) AND CONVERT(DATETIME,@ToDate,103)
				GROUP BY A.PARTY_CODE,LONG_NAME ,DATENAME(MONTH,INVOICE_DATE) + ' ' + DATENAME(YYYY,INVOICE_DATE) ,B.GST_NO,INV_NO,INVOICE_TYPE, SOURCESTATE,TARGETSTATE,REV_INT_REF_NO
END

END

GO
