-- Object: PROCEDURE dbo.EXCHCONTROLACC_MIS
-- Server: 10.253.33.91 | DB: MSAJAG
--------------------------------------------------



CREATE PROC EXCHCONTROLACC_MIS(@SAUDA_DATE VARCHAR(11))

AS

CREATE TABLE #EXCHCONTROLACC (EXCHANGE VARCHAR(30),CLTCODE VARCHAR(30),GLNAME VARCHAR(200))

 INSERT INTO #EXCHCONTROLACC SELECT 'NSECM','99985','Clearing House' 
 INSERT INTO #EXCHCONTROLACC SELECT 'NSEFO','99885','Clearing House' 
 INSERT INTO #EXCHCONTROLACC SELECT 'NSEFO','99897','Premium' 
 INSERT INTO #EXCHCONTROLACC SELECT 'NSEFO','99880','Option Allocation' 
 INSERT INTO #EXCHCONTROLACC SELECT 'NSECD','99885','Clearing House' 
 INSERT INTO #EXCHCONTROLACC SELECT 'NSECD','99897','Premium' 
 INSERT INTO #EXCHCONTROLACC SELECT 'NSECD','99880','Option Excercised' 
 INSERT INTO #EXCHCONTROLACC SELECT 'MCX','99885','Clearing House' 
 INSERT INTO #EXCHCONTROLACC SELECT 'MCX','99897','Premium' 
 INSERT INTO #EXCHCONTROLACC SELECT 'MCX','99880','Option Allocation' 
 INSERT INTO #EXCHCONTROLACC SELECT 'NCDEX','99885','Clearing House' 
 INSERT INTO #EXCHCONTROLACC SELECT 'NCDEX','99897','Premium' 
 INSERT INTO #EXCHCONTROLACC SELECT 'NCDEX','99880','Option Allocation' 
 INSERT INTO #EXCHCONTROLACC SELECT 'BSE','99785','Clearing House' 
 INSERT INTO #EXCHCONTROLACC SELECT 'NSEFO','99899','Stamp Duty' 
 INSERT INTO #EXCHCONTROLACC SELECT 'NSE/BSE','99973/99773','Stamp Duty' 
 INSERT INTO #EXCHCONTROLACC SELECT 'NSECD','99899','Stamp Duty' 
 INSERT INTO #EXCHCONTROLACC SELECT 'MCX','99899','Stamp Duty' 
 INSERT INTO #EXCHCONTROLACC SELECT 'NCDEX','99899','Stamp Duty' 
 INSERT INTO #EXCHCONTROLACC SELECT 'NSEFO','99972','STT' 
 INSERT INTO #EXCHCONTROLACC SELECT 'NSE/BSE','99972/99772','STT' 
 INSERT INTO #EXCHCONTROLACC SELECT 'MCX','99972','CTT' 
 INSERT INTO #EXCHCONTROLACC SELECT 'NCDEX','99972','CTT Charges' 

 ALTER TABLE #EXCHCONTROLACC ADD [Valan Posting] NUMERIC(18,2),[Exchange Obligation] NUMERIC(18,2),[Ledger Bal] NUMERIC(18,2),  
 [Dif( Vallan vs Exch File)] NUMERIC(18,2),[ Dif(Led vs Vallan Posting)] NUMERIC(18,2), Remark VARCHAR(100),[Classification] VARCHAR(100),
 Reason VARCHAR(100) 

 UPDATE #EXCHCONTROLACC SET [Classification] = CASE WHEN GLNAME = 'Stamp Duty' THEN 'Stamp Duty'
													WHEN GLNAME = 'STT' THEN 'STT'
													WHEN GLNAME = 'CTT' THEN 'STT'
													WHEN GLNAME = 'CTT Charges' THEN 'STT'
													ELSE 'Control A/c' END 

 UPDATE #EXCHCONTROLACC SET [Valan Posting] = 0,[Exchange Obligation] = 0,[Ledger Bal] = 0 ,[Dif( Vallan vs Exch File)] = 0 ,
 [ Dif(Led vs Vallan Posting)] = 0,Remark = 'Untally',Reason=''
 

SELECT CONVERT(VARCHAR(30),CLTCODE)AS CLTCODE,
NARRATION,SUM(CASE WHEN DRCR = 'D' THEN -VAMT ELSE VAMT END) AS VAMT,VDT,EDT, CONVERT(VARCHAR(30),EXCHANGE)AS EXCHANGE INTO #LEDGERGL
FROM ACCOUNT.DBO.LEDGER_ALL WHERE CLTCODE  IN ('99985','99885','99897','99880','99785','99899','99973','99972') 
AND EXCHANGE NOT IN ('NSE','BSE')
AND VDT BETWEEN @SAUDA_DATE AND @SAUDA_DATE + ' 23:59:59' AND VTYP = 15
GROUP BY VDT,EDT,EXCHANGE,CLTCODE,NARRATION

INSERT INTO #LEDGERGL
SELECT CONVERT(VARCHAR(30),CLTCODE)AS CLTCODE,
NARRATION,SUM(CASE WHEN DRCR = 'D' THEN -VAMT ELSE VAMT END) AS VAMT,VDT,EDT, CONVERT(VARCHAR(30),EXCHANGE)AS EXCHANGE 
FROM ACCOUNT.DBO.LEDGER_ALL WHERE CLTCODE  IN ('99985','99885','99897','99880','99785','99899','99973','99972') 
AND EXCHANGE IN ('NSE','BSE')
AND VDT <= @SAUDA_DATE AND  EDT > @SAUDA_DATE
AND VTYP = 15
GROUP BY VDT,EDT,EXCHANGE,CLTCODE,NARRATION

DECLARE @START_DATE VARCHAR(11)

SELECT @START_DATE = SDTCUR FROM ACCOUNT.DBO.PARAMETER WITH (NOLOCK) WHERE @SAUDA_DATE BETWEEN SDTCUR AND LDTCUR

SELECT CONVERT(VARCHAR(30),CLTCODE)AS CLTCODE,
SUM(CASE WHEN DRCR = 'D' THEN -VAMT ELSE VAMT END) AS VAMT, CONVERT(VARCHAR(30),EXCHANGE)AS EXCHANGE INTO #LEDGERGL_BAL
FROM ACCOUNT.DBO.LEDGER_ALL WHERE CLTCODE  IN ('99985','99885','99897','99880','99785','99899','99973','99972') 
AND VDT BETWEEN @START_DATE AND @SAUDA_DATE + ' 23:59:59' 
GROUP BY EXCHANGE,CLTCODE

UPDATE  #LEDGERGL SET EXCHANGE = 'NCDEX' WHERE EXCHANGE = 'NCX'
UPDATE  #LEDGERGL SET EXCHANGE = 'NSECD' WHERE EXCHANGE = 'NSX'
UPDATE  #LEDGERGL SET CLTCODE = '99973/99773',EXCHANGE = 'NSE/BSE' WHERE EXCHANGE IN ('NSE','BSE') AND CLTCODE IN ('99973','99773')
UPDATE  #LEDGERGL SET CLTCODE = '99972/99772',EXCHANGE = 'NSE/BSE' WHERE EXCHANGE IN ('NSE','BSE') AND CLTCODE IN ('99972','99772')
UPDATE  #LEDGERGL SET EXCHANGE = 'NSECM' WHERE EXCHANGE = 'NSE'


UPDATE  #LEDGERGL_BAL SET EXCHANGE = 'NCDEX' WHERE EXCHANGE = 'NCX'
UPDATE  #LEDGERGL_BAL SET EXCHANGE = 'NSECD' WHERE EXCHANGE = 'NSX'
UPDATE  #LEDGERGL_BAL SET CLTCODE = '99973/99773',EXCHANGE = 'NSE/BSE' WHERE EXCHANGE IN ('NSE','BSE') AND CLTCODE IN ('99973','99773')
UPDATE  #LEDGERGL_BAL SET CLTCODE = '99972/99772',EXCHANGE = 'NSE/BSE' WHERE EXCHANGE IN ('NSE','BSE') AND CLTCODE IN ('99972','99772')
UPDATE  #LEDGERGL_BAL SET EXCHANGE = 'NSECM' WHERE EXCHANGE = 'NSE'


SELECT  CLTCODE,EXCHANGE,SUM(VAMT) AS VAMT INTO  #LEDGERGL_NSEBSE FROM #LEDGERGL
WHERE EXCHANGE IN ('NSECM','BSE','NSE/BSE') --AND RIGHT(LEFT(NARRATION,20),1) IN ('N','W','M','Z')
GROUP BY CLTCODE ,EXCHANGE

UPDATE #EXCHCONTROLACC SET [Valan Posting] = VAMT FROM #LEDGERGL  WHERE #LEDGERGL.EXCHANGE = #EXCHCONTROLACC.EXCHANGE
AND #EXCHCONTROLACC.CLTCODE = #LEDGERGL.CLTCODE AND #EXCHCONTROLACC.EXCHANGE NOT IN ('NSECM','BSE','NSE/BSE')

UPDATE #EXCHCONTROLACC SET [Valan Posting] = VAMT FROM #LEDGERGL_NSEBSE  WHERE #LEDGERGL_NSEBSE.EXCHANGE = #EXCHCONTROLACC.EXCHANGE
AND #EXCHCONTROLACC.CLTCODE = #LEDGERGL_NSEBSE.CLTCODE AND  #LEDGERGL_NSEBSE.EXCHANGE IN ('NSECM','BSE','NSE/BSE')

/*
SELECT EXCHANGE='NSECM',SAUDA_DATE=OLB_DATE,SETT_NO,SETT_TYPE,PAMT=SUM(C_PAMT),SAMT=SUM(C_SAMT),NET_PAYIN_PAYOUT=SUM(C_PAMT)-SUM(C_SAMT) INTO #CASH
FROM MSAJAG.DBO.TBL_NSE_OBL WHERE OLB_DATE BETWEEN @SAUDA_DATE AND @SAUDA_DATE + ' 23:59'
GROUP BY SETT_NO,SETT_TYPE,OLB_DATE
ORDER BY OLB_DATE,SETT_NO
*/

SELECT EXCHANGE='NSEFO',SAUDA_DATE=FOEA_POSITION_DATE,PREMIUM_ACCOUNT=SUM(FOEA_NETPREMIUM),
CLEARING_HOUSE = SUM(FOEA_DAILY_MTM_SETTLEMENT_VALUE) + SUM(FOEA_FUTURES_FINAL_SETTLEMENT_VALUE),
OPTION_EX_ALLOCATION=SUM(FOEA_EXERCISED_ASSIGNED_VALUE),
NET_PAYIN_PAYOUT=SUM(FOEA_NETPREMIUM)+SUM(FOEA_DAILY_MTM_SETTLEMENT_VALUE) + SUM(FOEA_FUTURES_FINAL_SETTLEMENT_VALUE)+SUM(FOEA_EXERCISED_ASSIGNED_VALUE) INTO #FNO
FROM ANGELFO.NSEFO.DBO.FOEXERCISEALLOCATION WITH (NOLOCK)
WHERE FOEA_POSITION_DATE BETWEEN @SAUDA_DATE AND @SAUDA_DATE + ' 23:59'
GROUP BY FOEA_POSITION_DATE
UNION ALL
SELECT EXCHANGE='NSECD',SAUDA_DATE=FOEA_POSITION_DATE,PREMIUM_ACCOUNT=SUM(FOEA_NETPREMIUM),
CLEARING_HOUSE = SUM(FOEA_DAILY_MTM_SETTLEMENT_VALUE) + SUM(FOEA_FUTURES_FINAL_SETTLEMENT_VALUE),
OPTION_EX_ALLOCATION=SUM(FOEA_EXERCISED_ASSIGNED_VALUE),
NET_PAYIN_PAYOUT=SUM(FOEA_NETPREMIUM)+SUM(FOEA_DAILY_MTM_SETTLEMENT_VALUE) + SUM(FOEA_FUTURES_FINAL_SETTLEMENT_VALUE)+SUM(FOEA_EXERCISED_ASSIGNED_VALUE)
FROM ANGELFO.NSECURFO.DBO.FOEXERCISEALLOCATION WITH (NOLOCK)
WHERE FOEA_POSITION_DATE BETWEEN @SAUDA_DATE AND @SAUDA_DATE + ' 23:59'
GROUP BY FOEA_POSITION_DATE
UNION ALL
SELECT EXCHANGE='MCX',SAUDA_DATE=FOEA_POSITION_DATE,PREMIUM_ACCOUNT=SUM(FOEA_NETPREMIUM),
CLEARING_HOUSE = SUM(FOEA_DAILY_MTM_SETTLEMENT_VALUE) + SUM(FOEA_FUTURES_FINAL_SETTLEMENT_VALUE),
OPTION_EX_ALLOCATION=SUM(FOEA_EXERCISED_ASSIGNED_VALUE),
NET_PAYIN_PAYOUT=SUM(FOEA_NETPREMIUM)+SUM(FOEA_DAILY_MTM_SETTLEMENT_VALUE) + SUM(FOEA_FUTURES_FINAL_SETTLEMENT_VALUE)+SUM(FOEA_EXERCISED_ASSIGNED_VALUE)
FROM ANGELCOMMODITY.MCDX.DBO.FOEXERCISEALLOCATION WITH (NOLOCK)
WHERE FOEA_POSITION_DATE BETWEEN @SAUDA_DATE AND @SAUDA_DATE + ' 23:59'
GROUP BY FOEA_POSITION_DATE
UNION ALL
SELECT EXCHANGE='NCDEX',SAUDA_DATE=FOEA_POSITION_DATE,PREMIUM_ACCOUNT=SUM(FOEA_NETPREMIUM),
CLEARING_HOUSE = SUM(FOEA_DAILY_MTM_SETTLEMENT_VALUE) + SUM(FOEA_FUTURES_FINAL_SETTLEMENT_VALUE),
OPTION_EX_ALLOCATION=SUM(FOEA_EXERCISED_ASSIGNED_VALUE),
NET_PAYIN_PAYOUT=SUM(FOEA_NETPREMIUM)+SUM(FOEA_DAILY_MTM_SETTLEMENT_VALUE) + SUM(FOEA_FUTURES_FINAL_SETTLEMENT_VALUE)+SUM(FOEA_EXERCISED_ASSIGNED_VALUE)
FROM ANGELCOMMODITY.NCDX.DBO.FOEXERCISEALLOCATION WITH (NOLOCK)
WHERE FOEA_POSITION_DATE BETWEEN @SAUDA_DATE AND @SAUDA_DATE + ' 23:59'
GROUP BY FOEA_POSITION_DATE
ORDER BY EXCHANGE,SAUDA_DATE

UPDATE #EXCHCONTROLACC SET [Exchange Obligation] = CLEARING_HOUSE FROM #FNO  WHERE #EXCHCONTROLACC.EXCHANGE = #FNO.EXCHANGE AND CLTCODE = '99885'
UPDATE #EXCHCONTROLACC SET [Exchange Obligation] = PREMIUM_ACCOUNT FROM #FNO  WHERE #EXCHCONTROLACC.EXCHANGE = #FNO.EXCHANGE AND CLTCODE = '99897'
UPDATE #EXCHCONTROLACC SET [Exchange Obligation] = OPTION_EX_ALLOCATION FROM #FNO  WHERE #EXCHCONTROLACC.EXCHANGE = #FNO.EXCHANGE AND CLTCODE = '99880'

--SELECT '99985' AS CLTCODE,'NSECM' AS EXCHANGE,SUM(NET_PAYIN_PAYOUT) AS NET_PAYIN_PAYOUT INTO #CASH_FINAL FROM #CASH

--UPDATE #EXCHCONTROLACC SET [Exchange Obligation] = NET_PAYIN_PAYOUT FROM #CASH_FINAL  WHERE #EXCHCONTROLACC.EXCHANGE = #CASH_FINAL.EXCHANGE 
--AND #EXCHCONTROLACC.CLTCODE = #CASH_FINAL.CLTCODE 

UPDATE #EXCHCONTROLACC SET [Ledger Bal] = VAMT FROM #LEDGERGL_BAL  
WHERE #EXCHCONTROLACC.EXCHANGE = #LEDGERGL_BAL.EXCHANGE AND #EXCHCONTROLACC.CLTCODE = #LEDGERGL_BAL.CLTCODE


UPDATE #EXCHCONTROLACC SET [Dif( Vallan vs Exch File)] = [Valan Posting]  + [Exchange Obligation]
UPDATE #EXCHCONTROLACC SET [ Dif(Led vs Vallan Posting)] = [Valan Posting]  - [Ledger Bal]
UPDATE #EXCHCONTROLACC SET Remark = 'Tally' WHERE [Dif( Vallan vs Exch File)] = 0 AND [ Dif(Led vs Vallan Posting)] = 0 


SELECT * FROM #EXCHCONTROLACC ORDER BY 10,1


DROP TABLE #EXCHCONTROLACC
DROP TABLE #LEDGERGL
DROP TABLE #LEDGERGL_NSEBSE
DROP TABLE #FNO
--DROP TABLE #CASH
--DROP TABLE #CASH_FINAL
DROP TABLE #LEDGERGL_BAL

GO
