-- Object: PROCEDURE dbo.RPT_WEEKLY_CLIENT_CASH_BALANCE_NEW_MCX_ANG
-- Server: 10.253.33.91 | DB: MSAJAG
--------------------------------------------------

  
CREATE PROCEDURE [dbo].[RPT_WEEKLY_CLIENT_CASH_BALANCE_NEW_MCX_ANG] (@REPORT_DATE VARCHAR(11))    
AS    
    
DECLARE @FILENAME VARCHAR(200)     
DECLARE @CASHFILENAME VARCHAR(200)     
DECLARE @DATACASH VARCHAR(MAX)    
    
TRUNCATE TABLE MSAJAG.DBO.EXCHANGECCE    
    
INSERT INTO MSAJAG.DBO.EXCHANGECCE(CASHFILENAME,DATACASH)    
EXEC MSAJAG.DBO.RPT_WEEKLY_CLIENT_CASH_BALANCE_NEW_MCX @REPORT_DATE, @REPORT_DATE, 'A000000000', 'ZZZZZZZZZZ', 'MCX'    
    
SELECT @FILENAME = CASHFILENAME FROM EXCHANGECCE    
    
SET @CASHFILENAME = 'J:\BACKOFFICE\EXPORT\MCX_' + @FILENAME --+'.CSV'    
SET @DATACASH = 'EXEC MASTER.DBO.XP_CMDSHELL ''BCP " SELECT DATACASH FROM MSAJAG.DBO.EXCHANGECCE " QUERYOUT ' + @CASHFILENAME+ ' -c -t"," -c -t"," -r"\n" -T'', NO_OUTPUT'    
    
EXEC(@DATACASH)    
    
SELECT 'File Exported \\Backoffice\Export for '+ CONVERT(VARCHAR(11),@REPORT_DATE,105)

GO
