-- Object: PROCEDURE dbo.KYC_ACC_INFO
-- Server: 10.253.33.91 | DB: MSAJAG
--------------------------------------------------

--EXEC KYC_ACC_INFO '07/09/2017, 07/09/2017', '','E' 

CREATE PROC [dbo].[KYC_ACC_INFO]
(
@fromdate VARCHAR(11),
@todate VARCHAR(11),
@RPT_TYPE VARCHAR(1)
)
AS
set @FROMDATE=convert(DATETIME,@fromdate,103)    
 set @TODATE=convert(DATETIME,@todate,103)  

SELECT * INTO #1 FROM INTRANET.RISK.DBO.CLIENT_DETAILS WHERE 
FIRST_ACTIVE_DATE > = @fromdate and First_Active_Date <=@todate + ' 23:59'
AND B2C ='Y'
 
SELECT * INTO #RCS FROM CLIENT_BROK_DETAILS
WHERE CL_CODE IN (SELECT CL_CODE FROM #1)
AND INACTIVE_FROM > GETDATE ()
 
SELECT DISTINCT  CL_CODE,EXCHANGE,SEGMENT,TRD_BROK,DEL_BROK,FUT_BROK,TABLE_NAME,DAY_PUC INTO #FINAL13 FROM #RCS R,AngelBSECM.BSEDB_AB.DBO.BROKTABLE B
WHERE EXCHANGE ='BSE' AND SEGMENT ='CAPITAL' AND TRD_BROK=TABLE_NO AND VAL_PERC ='P' AND  TRD_DEL IN ('N','F')---AND TABLE_NAME NOT LIKE 'Angel%' ----WHERE 
ORDER BY EXCHANGE,SEGMENT,CL_CODE
 
UPDATE  #FINAL13 SET TABLE_NAME = (CASE WHEN DAY_PUC ='0.028' THEN 'Angel Preferred'
WHEN DAY_PUC ='0.022' THEN 'Angel Premier'
WHEN DAY_PUC ='0.016' THEN 'Angel Elite'
WHEN DAY_PUC ='0.04' THEN 'Angel Classic'
ELSE 'Custom' END )
WHERE TRD_BROK NOT IN (6719,6721,6723,6725) 

SELECT DISTINCT CL_CODE,EXCHANGE,SEGMENT,TRD_BROK,DEL_BROK,FUT_BROK,TABLE_NAME,DAY_PUC INTO #COMM FROM #RCS R,ANGELCOMMODITY.MCDX.DBO.BROKTABLE B
WHERE EXCHANGE ='MCX' AND SEGMENT ='FUTURES' AND FUT_BROK=TABLE_NO  AND VAL_PERC ='P' AND  TRD_DEL IN ('N','F')
ORDER BY EXCHANGE,SEGMENT,CL_CODE
 
 
UPDATE  #COMM SET TABLE_NAME = (CASE WHEN DAY_PUC ='0.028' THEN 'Angel Preferred'
								WHEN DAY_PUC ='0.022' THEN 'Angel Premier'
								WHEN DAY_PUC ='0.016' THEN 'Angel Elite'
								WHEN DAY_PUC ='0.04' THEN 'Angel Classic'
								ELSE 'Custom' END )
WHERE FUT_BROK NOT IN (6719,6721,6723,6849,6850,6851,6852) 
 
 
ALTER TABLE #1
ADD BROKERAGE VARCHAR(35)
 

UPDATE #1 SET BROKERAGE=TABLE_NAME FROM #FINAL13 WHERE #FINAL13.Cl_Code=#1.CL_CODE 

UPDATE #1 SET BROKERAGE=TABLE_NAME FROM #COMM WHERE #COMM.Cl_Code=#1.CL_CODE  AND BROKERAGE IS NULL


IF @RPT_TYPE ='A'
BEGIN 
SELECT REGION,	BRANCH_CD,	SUB_BROKER,	CL_CODE,	LONG_NAME,CONVERT(VARCHAR(11),FIRST_ACTIVE_DATE,120) Active_Date ,BROKERAGE =ISNULL(BROKERAGE,'Client Inactive / Closed')
FROM #1
ORDER BY CONVERT(VARCHAR(11),FIRST_ACTIVE_DATE,120) , CL_CODE 
END

IF @RPT_TYPE ='E'
BEGIN 
SELECT CL_CODE,EXCHANGE,SEGMENT,TRD_BROK,DEL_BROK,FUT_BROK,TABLE_NAME AS BROKERAGE FROM #FINAL13
END

IF @RPT_TYPE ='C'
BEGIN 
SELECT CL_CODE,EXCHANGE,SEGMENT,TRD_BROK,DEL_BROK,FUT_BROK,TABLE_NAME  AS BROKERAGE FROM #COMM
END

GO
