-- Object: PROCEDURE dbo.RPT_WEEKLY_CLIENT_CASH_BALANCE_NEW_NSE_ANG
-- Server: 10.253.33.91 | DB: MSAJAG
--------------------------------------------------


CREATE PROCEDURE [dbo].[RPT_WEEKLY_CLIENT_CASH_BALANCE_NEW_NSE_ANG] (@FROMDATE   VARCHAR(11),          
      @TODATE           VARCHAR(11),          
      @FROMPARTY  VARCHAR(20),          
      @TOPARTY    VARCHAR(20),@EXCHANGE VARCHAR(3) = 'NSE',@FLAG VARCHAR(10)='')          
AS          
          
--EXEC [RPT_WEEKLY_CLIENT_CASH_BALANCE_NEW_NSE_ANG] '18/02/2022','18/02/2022','00000','ZZZZZZZZZ'      
      
DECLARE @FILENAME VARCHAR(200)           
DECLARE @CASHFILENAME VARCHAR(200)           
DECLARE @DATACASH VARCHAR(MAX)          
          
TRUNCATE TABLE EXCHANGECCE_NSE          
    
EXEC RPT_WEEKLY_CLIENT_CASH_BALANCE_NEW_ANG_BULK @FROMDATE,@TODATE,@FROMPARTY,@TOPARTY        
          
SELECT @FILENAME = CASHFILENAME FROM EXCHANGECCE_NSE          
    
SET @CASHFILENAME = 'J:\BACKOFFICE\EXPORT\NSE_' + @FILENAME --+'.CSV'          
SET @DATACASH = 'EXEC MASTER.DBO.XP_CMDSHELL ''BCP " SELECT DATACASH FROM MSAJAG.DBO.EXCHANGECCE_NSE ORDER BY SNO ASC " QUERYOUT ' + @CASHFILENAME+ ' -c -t"," -c -t"," -r"\n" -T'', NO_OUTPUT'          
          
EXEC(@DATACASH)          
          
SELECT 'File Exported \\Backoffice\Export for '+ CONVERT(VARCHAR(11),@FROMDATE,105)

GO
