-- Object: PROCEDURE dbo.V3_COMBINED_CONTRACTNOTE_DETAIL_INTEROP
-- Server: 10.253.33.91 | DB: MSAJAG
--------------------------------------------------




CREATE PROCEDURE [dbo].[V3_COMBINED_CONTRACTNOTE_DETAIL_INTEROP] (
	@STATUSID VARCHAR(15),
	@STATUSNAME VARCHAR(25),
	@FROMDATE VARCHAR(11),
	@TODATE VARCHAR(11),
	@FROMPARTY VARCHAR(10),
	@TOPARTY VARCHAR(10),
	@FROMBRANCH VARCHAR(10),
	@TOBRANCH VARCHAR(10),
	@FROMSUB_BROKER VARCHAR(10),
	@TOSUB_BROKER VARCHAR(10),
	@FROMCONTRACT VARCHAR(10),
	@TOCONTRACT VARCHAR(10),
	@CONTFLAG VARCHAR(10),
	@EXCHANGE VARCHAR(15),
	@BOUNCEDFLAG INT = 0,
	@PRINTFLAG VARCHAR(6),
	@SETT_TYPE VARCHAR(2) = '',
	@COMPANY_NAME VARCHAR(100) = '',
	@CONTRACTGROUP VARCHAR(20) = '',
	@FORPDF VARCHAR(1) = 'N'
	)
AS

SET NOCOUNT ON

/*
	EXEC [V3_COMBINED_CONTRACTNOTE_DETAIL_INTEROP] 'BROKER','BROKER','DEC 24 2018','DEC 24 2021','','ZZZZZZ','','ZZZZZZZZ','','ZZZZZZ','','99999999','','',0,''
	EXEC [V2_COMBINED_CONTRACTNOTE_DETAIL] 'BROKER','BROKER','DEC 24 2014','DEC 24 2014','','ZZZZZZ','','ZZZZZZZZ','','ZZZZZZ','','99999999','','',0,'',''
	exec msajag..[v2_combined_contractnote_detail] @STATUSID='Broker',@STATUSNAME='Broker',@FROMDATE='04/09/2014',@TODATE='04/09/2014',@FROMPARTY='1MA008',@TOPARTY='1MA008',@FROMBRANCH='',@TOBRANCH='',@FROMSUB_BROKER='',@TOSUB_BROKER='',@FROMCONTRACT='0',@TO

	CONTRACT='9999999999',@CONTFLAG='',@EXCHANGE='',@BOUNCEDFLAG='',@PRINTFLAG='',@SETT_TYPE='',@COMPANY_NAME='',@FORPDF='N'
*/

--SET @STATUSID = 'BROKER'
--SET @STATUSNAME = 'BROKER'

IF LEN(@FROMDATE) = 10 AND CHARINDEX('/', @FROMDATE) > 0
BEGIN
	SET @FROMDATE = CONVERT(VARCHAR(11), CONVERT(DATETIME, @FROMDATE, 103), 109)
END

IF LEN(@TODATE) = 10 AND CHARINDEX('/', @TODATE) > 0
BEGIN
	SET @TODATE = CONVERT(VARCHAR(11), CONVERT(DATETIME, @TODATE, 103), 109)
END


IF @TODATE = ''
BEGIN
	SET @TODATE = @FROMDATE
END

IF @TOPARTY = ''
BEGIN
	SET @TOPARTY = 'ZZZZZZZZZZ'
END

IF @TOBRANCH = ''
BEGIN
	SET @TOBRANCH = 'ZZZZZZZZZZ'
END

IF @TOSUB_BROKER = ''
BEGIN
	SET @TOSUB_BROKER = 'ZZZZZZZZZZ'
END

IF @TOCONTRACT = ''
BEGIN
	SET @TOCONTRACT = '9999999999'
END

DECLARE @COLNAME VARCHAR(6)

SET @COLNAME = ''

IF @CONTFLAG = 'CONTRACT'
BEGIN
	SELECT @COLNAME = RPT_CODE
	FROM V2_CONTRACTPRINT_SETTING_COMBINED
	WHERE RPT_TYPE = 'ORDER'
		AND RPT_PRINTFLAG = 1
END
ELSE
BEGIN
	SELECT @COLNAME = RPT_CODE
	FROM V2_CONTRACTPRINT_SETTING_COMBINED
	WHERE RPT_TYPE = 'ORDER'
		AND RPT_PRINTFLAG_DIGI = 1
END

DECLARE @CONTRACT_TYPE		INT
DECLARE @FNO_CONTRACT_BILL	INT,
		@STTFLAG			INT,
		@SERFLAG			INT,
		@INTEROP			VARCHAR(10),
		@INTEROPFNO			VARCHAR(10),
		@INTEROPCUR			VARCHAR(10),
		@PRINTDEALING		VARCHAR(100),
		@IPFTFLAG			INT
		
--	PRINT	@COMPANY_NAME

SET @CONTRACT_TYPE = 0
SET @FNO_CONTRACT_BILL = 0
SET @STTFLAG = 0
SET @SERFLAG = 0
SET @INTEROP = ''
SET	@INTEROPFNO = ''
SET	@INTEROPCUR = ''
SET @PRINTDEALING=''
SET @IPFTFLAG = 1

--SELECT @INTEROP = CLEARINGCODE FROM TBL_INTEROP_SETTING (NOLOCK) 
--WHERE @FROMDATE BETWEEN FROM_DATE AND TO_DATE

--SELECT @IPFTFLAG = COUNT(1) FROM SYS.TABLES WHERE NAME='TBL_ADDITIONAL_TAX_DATA'

SELECT 
	@CONTRACT_TYPE = CONTRACT_TYPE,
	@FNO_CONTRACT_BILL = FNO_CONTRACT_BILL,
	@STTFLAG = PRINT_STT_COLUMN,
	@PRINTDEALING=PRINT_DEALING
FROM TBL_COMMONCONTRACT_MASTER(NOLOCK)
WHERE @FROMDATE BETWEEN EFFECTIVE_FROM AND EFFECTIVE_TO


SELECT DISTINCT 
	EXCHANGE = LTRIM(RTRIM(M.EXCHANGE))+LTRIM(RTRIM(M.SEGMENT)),
	SHAREDB = LTRIM(RTRIM(M.SHAREDB)),
	SHARESERVER = LTRIM(RTRIM(M.SHARESERVER))
INTO
	#EXCHANGELIST

FROM 
	PRADNYA..MULTICOMPANY M(NOLOCK)
WHERE 
	CATEGORY IN (
		'EQUITY',
		'DERIVATIVES',
		'CURRENCY'		
		)
	AND M.SEGMENT NOT IN ('SLBS')
	AND SEGMENT_DESCRIPTION NOT LIKE '%PCM%'
	AND PRIMARYSERVER = 1
	--AND ISNULL(CONTRACTGROUP,'') = (CASE WHEN @CONTRACTGROUP = '' THEN ISNULL(CONTRACTGROUP,'') ELSE @CONTRACTGROUP END)
	AND EXCHANGE <> 'ICX'



	CREATE TABLE #INTEROP_SETT 
	(
	SEGMENT VARCHAR(10),
	VALUE  VARCHAR(10)
	)

	DECLARE @EXCHANGE_NEW1 VARCHAR(10)
	DECLARE @SEGMENT_NEW1 VARCHAR(10)
	DECLARE @SHAREDB1 VARCHAR(35)
	DECLARE @SHARESERVER1 VARCHAR(35)
	DECLARE @EXCHANGEWISE_CURSOR1 CURSOR 
	DECLARE @STRSQL1 VARCHAR(8000) 

	SET @EXCHANGEWISE_CURSOR1 = CURSOR
	FOR
	SELECT	DISTINCT 
			EXCHANGE,
			SHAREDB,
			SHARESERVER
	FROM	#EXCHANGELIST M(NOLOCK)
	WHERE	EXCHANGE IN ('BSECAPITAL','NSECAPITAL','BSEFUTURES','NSEFUTURES','NSXFUTURES','BSXFUTURES')
		
	OPEN @EXCHANGEWISE_CURSOR1

	FETCH NEXT
	FROM @EXCHANGEWISE_CURSOR1
	INTO
		@EXCHANGE_NEW1,
		@SHAREDB1,
		@SHARESERVER1

	WHILE @@FETCH_STATUS = 0
	BEGIN
		SET @STRSQL1 = ''
		IF @SHARESERVER1 = @@SERVERNAME 
		BEGIN
			SET @SHARESERVER1 = ''
		END
		ELSE
		BEGIN
			SET @SHARESERVER1 = @SHARESERVER1 + '.'
		END
		
		BEGIN
			
			IF (@EXCHANGE_NEW1 = 'NSECAPITAL')
			BEGIN
				SET @STRSQL1 = 'IF (SELECT COUNT(1) FROM ' + @SHARESERVER1 + @SHAREDB1 + '.SYS.TABLES WHERE NAME=''TBL_INTEROP_SETTING'') > 0 '
				SET @STRSQL1 = @STRSQL1 + 'BEGIN '
				SET @STRSQL1 = @STRSQL1 + 'INSERT INTO #INTEROP_SETT '
				SET @STRSQL1 = @STRSQL1 + 'SELECT ''NSECAPITAL'',CLEARINGCODE FROM ' + @SHARESERVER1 + @SHAREDB1 + '.DBO.TBL_INTEROP_SETTING '
				--SET @STRSQL1 = @STRSQL1 + 'WHERE '''+ @FROMDATE +''' BETWEEN FROM_DATE AND TO_DATE '
				SET @STRSQL1 = @STRSQL1 + 'END '
				PRINT @STRSQL1
				EXEC (@STRSQL1)
			END
			ELSE IF (@EXCHANGE_NEW1 = 'NSEFUTURES')
			BEGIN
				SET @STRSQL1 = 'IF (SELECT COUNT(1) FROM ' + @SHARESERVER1 + @SHAREDB1 + '.SYS.TABLES WHERE NAME=''TBL_INTEROP_SETTING'') > 0 '
				SET @STRSQL1 = @STRSQL1 + 'BEGIN '
				SET @STRSQL1 = @STRSQL1 + 'INSERT INTO #INTEROP_SETT '
				SET @STRSQL1 = @STRSQL1 + 'SELECT ''NSEFUTURES'',CLEARINGCODE FROM ' + @SHARESERVER1 + @SHAREDB1 + '.DBO.TBL_INTEROP_SETTING '
				--SET @STRSQL1 = @STRSQL1 + 'WHERE '''+ @FROMDATE +''' BETWEEN FROM_DATE AND TO_DATE '
				SET @STRSQL1 = @STRSQL1 + 'END '
				PRINT @STRSQL1
				EXEC (@STRSQL1)
			END
			ELSE IF (@EXCHANGE_NEW1 = 'NSXFUTURES')
			BEGIN
				SET @STRSQL1 = 'IF (SELECT COUNT(1) FROM ' + @SHARESERVER1 + @SHAREDB1 + '.SYS.TABLES WHERE NAME=''TBL_INTEROP_SETTING'') > 0 '
				SET @STRSQL1 = @STRSQL1 + 'BEGIN '
				SET @STRSQL1 = @STRSQL1 + 'INSERT INTO #INTEROP_SETT '
				SET @STRSQL1 = @STRSQL1 + 'SELECT ''NSXFUTURES'',CLEARINGCODE FROM ' + @SHARESERVER1 + @SHAREDB1 + '.DBO.TBL_INTEROP_SETTING '
				--SET @STRSQL1 = @STRSQL1 + 'WHERE '''+ @FROMDATE +''' BETWEEN FROM_DATE AND TO_DATE '
				SET @STRSQL1 = @STRSQL1 + 'END '
				PRINT @STRSQL1
				EXEC (@STRSQL1)
			END

		END
		
		FETCH NEXT
		FROM @EXCHANGEWISE_CURSOR1
		INTO 
			@EXCHANGE_NEW1,
			@SHAREDB1,
			@SHARESERVER1
	END

	CLOSE @EXCHANGEWISE_CURSOR1
	DEALLOCATE @EXCHANGEWISE_CURSOR1
	



	SELECT @INTEROP		= VALUE FROM #INTEROP_SETT WHERE SEGMENT IN ('NSECAPITAL','BSECAPITAL')
	SELECT @INTEROPFNO	= VALUE FROM #INTEROP_SETT WHERE SEGMENT IN ('NSEFUTURES','BSEFUTURES')
	SELECT @INTEROPCUR  = VALUE FROM #INTEROP_SETT WHERE SEGMENT IN ('NSXFUTURES','BSXFUTURES')


SELECT * INTO #CONTDATA
FROM COMMON_CONTRACT_DATA C WITH (NOLOCK)
WHERE SAUDA_DATE BETWEEN @FROMDATE AND @TODATE + ' 23:59:59'
AND PARTY_CODE BETWEEN @FROMPARTY AND @TOPARTY
AND BRANCH_CD BETWEEN @FROMBRANCH AND @TOBRANCH
AND SUB_BROKER BETWEEN @FROMSUB_BROKER AND @TOSUB_BROKER
AND EXISTS (SELECT EXCHANGE FROM #EXCHANGELIST E WHERE E.EXCHANGE = LTRIM(RTRIM(C.EXCHANGE))+LTRIM(RTRIM(C.SEGMENT)) )


/* ---- START CHANGES FOR T1T2 SETTELEMENT ---*/
/* ---- ADDED EXTAR CONDITION              ---*/


ALTER	TABLE #CONTDATA
ALTER	COLUMN SETTTYPE_DESC VARCHAR(50)

UPDATE	#CONTDATA 
SET		SETTTYPE_DESC = ISNULL(T.SETT_DESC,'')
FROM	TBL_SETTTYPE_DESC T (NOLOCK)
WHERE	T.SETT_TYPE = #CONTDATA.SETT_TYPE 
		AND #CONTDATA.SETTTYPE_DESC = ''

/*
UPDATE	#CONTDATA
SET		SETTTYPE_DESC = (
		CASE
			WHEN SETT_TYPE = 'M'  THEN 'Normal'
			WHEN SETT_TYPE = 'Z'  THEN 'Trade For Trade'
			WHEN SETT_TYPE = 'RD' THEN 'Rolling Market'
			WHEN SETT_TYPE = 'RC' THEN 'Odd Lot'
			ELSE SETTTYPE_DESC
		END)
*/

/* ---- END CHANGES FOR T1T2 SETTELEMENT   ---*/


CREATE TABLE #PARTY (PARTYCODE VARCHAR(15))

IF @BOUNCEDFLAG = 0
BEGIN
	INSERT INTO #PARTY
	SELECT DISTINCT PARTY_CODE
	FROM #CONTDATA C WITH (NOLOCK)
	WHERE SAUDA_DATE BETWEEN @FROMDATE AND @TODATE + ' 23:59:59'
		AND PARTY_CODE BETWEEN @FROMPARTY AND @TOPARTY
		AND EXISTS (SELECT EXCHANGE FROM #EXCHANGELIST E WHERE E.EXCHANGE = LTRIM(RTRIM(C.EXCHANGE))+LTRIM(RTRIM(C.SEGMENT)) )
END
ELSE
BEGIN
	IF (@EXCHANGE = '') 
	BEGIN
		INSERT INTO #PARTY
		SELECT DISTINCT PARTY_CODE
		FROM TBL_ECNBOUNCED WITH (NOLOCK)
		WHERE SDATE BETWEEN @FROMDATE AND @TODATE + ' 23:59:59'
		--AND EXCHANGE = 'ALLEQUITY'
	END	
	ELSE
	BEGIN
		INSERT INTO #PARTY
		SELECT DISTINCT PARTY_CODE
		FROM TBL_ECNBOUNCED WITH (NOLOCK)
		WHERE SDATE BETWEEN @FROMDATE AND @TODATE + ' 23:59:59'
		/*AND EXCHANGE = (
		CASE
			WHEN @EXCHANGE = 'NSECAPITAL' THEN 'NSECM'
			WHEN @EXCHANGE = 'BSECAPITAL' THEN 'BSECM'
			WHEN @EXCHANGE = 'NSEFUTURES' THEN 'NSEFO'
			ELSE ''
		END)*/	
	END	
END


SELECT 
	ORDERBYFLAG = (
	CASE 
		WHEN @COLNAME = 'ORD_N' THEN PARTYNAME 
		WHEN @COLNAME = 'ORD_P' THEN PARTY_CODE 
		WHEN @COLNAME = 'ORD_BP' THEN RTRIM(LTRIM(BRANCH_CD)) + RTRIM(LTRIM(PARTY_CODE)) 
		WHEN @COLNAME = 'ORD_BN' THEN RTRIM(LTRIM(BRANCH_CD)) + RTRIM(LTRIM(PARTYNAME)) 
		WHEN @COLNAME = 'ORD_DP' THEN RTRIM(LTRIM(BRANCH_CD)) + RTRIM(LTRIM(SUB_BROKER)) + RTRIM(LTRIM(TRADER)) + RTRIM(LTRIM(PARTY_CODE)) 
		WHEN @COLNAME = 'ORD_DN' THEN RTRIM(LTRIM(BRANCH_CD)) + RTRIM(LTRIM(SUB_BROKER)) + RTRIM(LTRIM(TRADER)) + RTRIM(LTRIM(PARTYNAME)) 
		ELSE RTRIM(LTRIM(BRANCH_CD)) + RTRIM(LTRIM(SUB_BROKER)) + RTRIM(LTRIM(TRADER)) + RTRIM(LTRIM(PARTY_CODE)) 
	END),
	CONTRACTNO,
	CONTRACTNO_NEW = (CASE WHEN @CONTRACT_TYPE = 1 THEN CONTRACTNO ELSE CONTRACTNO_NEW END),
	SAUDA_DATE = CONVERT(VARCHAR, CONVERT(DATETIME, SAUDA_DATE, 109), 103),
	SETT_NO,
	SETT_TYPE,
	SETT_DATE,
	PARTY_CODE,
	PARTYNAME,
	L_ADDRESS1,
	L_ADDRESS2,
	L_ADDRESS3,
	L_STATE,
	L_CITY,
	L_ZIP,
	OFF_PHONE1,
	OFF_PHONE2,
	PAN_GIR_NO,
	EXCHANGE,
	SEGMENT,
	ORDER_NO,
	ORDER_TIME,
	TRADE_NO,
	TRADE_TIME,
	SCRIPNAME = REPLACE(REPLACE(SCRIPNAME,'(BT)','') ,'(BF)',''),
	QTY,
	TMARK,
	--SELL_BUY = (CASE WHEN SELL_BUY = 1 THEN 'BUY' ELSE 'SELL' END),
	SELL_BUY = (CASE WHEN QTY = 0 THEN '' ELSE (CASE WHEN SELL_BUY = 1 THEN 'BUY' ELSE 'SELL' END) END),
	MARKETRATE,
	MARKETAMT = ABS(MARKETAMT),
	BROKERAGE = ABS(BROKERAGE),
	SERVICE_TAX,
	INS_CHRG,
	IPFT_CHRG = CONVERT(NUMERIC(18,4), 0), -- (CASE WHEN @IPFTFLAG = 0 THEN CONVERT(NUMERIC(18,4), 0) ELSE IPFT_CHRG END),
	NETAMOUNT,
	SEBI_TAX,
	TURN_TAX,
	BROKER_CHRG,
	OTHER_CHRG,
	NETAMOUNTALL,
	PRINTF,
	BROK,
	NETRATE,
	CL_RATE,
	UCC_CODE,
	BROKERSEBIREGNO,
	MEMBERCODE,
	CINNO,
	BRANCH_CD,
	SUB_BROKER,
	TRADER,
	AREA,
	REGION,
	FAMILY,
	MAPIDID,
	SEBI_NO,
	PARTICIPANT_CODE,
	CL_TYPE,
	SERVICE_CHRG,
	SETTTYPE_DESC,
	BFCF_FLAG=CASE WHEN @FNO_CONTRACT_BILL=0 THEN '' ELSE BFCF_FLAG END ,
	CONTRACT_HEADER_DET,
	REMARK = (
	CASE
		WHEN SEGMENT = 'FUTURES' THEN EXCHANGE+'FO'
		ELSE EXCHANGE END) + (CASE WHEN SEGMENT='CAPITAL' THEN '-'+ SETT_TYPE ELSE '' END) + (CASE WHEN REMARK = '' THEN '' ELSE ' - ' + REMARK END),
	COMPANYNAME,
	REMARK_ID = REMARK_ID,
	REMARK_DESC,
	NETOBLIGATION,
	SETTLEMENT_DET = CONVERT(VARCHAR(600), ''),
	CONTRACTNO_DET = CONVERT(VARCHAR(600), ''),
	BROKERSEBIREGNO_DET = CONVERT(VARCHAR(600), ''),
	MEMBERCODE_DET = CONVERT(VARCHAR(600), ''),
	CIN_DET = CONVERT(VARCHAR(600), ''),
	NETAMOUNTEX = CONVERT(NUMERIC(20, 6), 0),
	SEBI_TAXEX = CONVERT(NUMERIC(18, 4), 0),
	TURN_TAXEX = CONVERT(NUMERIC(18, 4), 0),
	BROKER_CHRGEX = CONVERT(NUMERIC(18, 4), 0),
	OTHER_CHRGEX = CONVERT(NUMERIC(18, 4), 0),
	INS_CHRGEX = CONVERT(NUMERIC(18, 4), 0),
	IPFT_CHRGEX= CONVERT(NUMERIC(18, 4), 0),
	SERVICE_TAXEX = CONVERT(NUMERIC(18, 4), 0),
	SCRIPNAME_NEW = CONVERT(VARCHAR(300), ''),
	REMARK_DET = CONVERT(VARCHAR(300), ''),
	ORDFLAG = (CASE WHEN QTY = 0 THEN 2 ELSE 1 END),
	ISIN,
	ORD_DATE = CONVERT(VARCHAR,SAUDA_DATE,112),
	EXCHANGE_OLD = EXCHANGE,
	SEGMENT_OLD = SEGMENT,
	INTEROPCODE = CONVERT(VARCHAR(10),''),
	SCRIPDESC = CONVERT(VARCHAR(100),SCRIPNAME),
	CONTRACTNO_OLD = CONTRACTNO,
	SETT_NO_OLD = SETT_NO,
	SETT_TYPE_OLD = SETT_TYPE,
	SETTTYPE_DESC_OLD = SETTTYPE_DESC
INTO #CONTRACT
FROM #CONTDATA C(NOLOCK),
	CLIENT_PRINT_SETTINGS CP(NOLOCK),
	#PARTY P
WHERE SAUDA_DATE BETWEEN @FROMDATE AND @TODATE + ' 23:59:59'
	AND PARTY_CODE BETWEEN @FROMPARTY AND @TOPARTY
	AND CONTRACTNO BETWEEN @FROMCONTRACT AND @TOCONTRACT
	--AND COMPANYNAME = (CASE WHEN @COMPANY_NAME <> '' THEN @COMPANY_NAME ELSE COMPANYNAME END)
	AND BRANCH_CD BETWEEN @FROMBRANCH AND @TOBRANCH
	AND SUB_BROKER BETWEEN @FROMSUB_BROKER AND @TOSUB_BROKER
	AND @STATUSNAME = (CASE WHEN @STATUSID = 'BRANCH' THEN BRANCH_CD WHEN @STATUSID = 'SUBBROKER' THEN SUB_BROKER WHEN @STATUSID = 'TRADER' 
	THEN TRADER WHEN @STATUSID = 'FAMILY' THEN FAMILY WHEN @STATUSID = 'AREA' THEN AREA WHEN @STATUSID = 'REGION' THEN REGION 
	WHEN @STATUSID = 'CLIENT' THEN PARTY_CODE ELSE 'BROKER' END)
	AND C.PARTY_CODE = P.PARTYCODE
	AND C.PRINTF = CP.PRINT_FLAG
	AND CP.VALID_REPORT LIKE (CASE WHEN @BOUNCEDFLAG = 0 THEN '%' + @CONTFLAG + '%' ELSE CP.VALID_REPORT END)
	---AND CP.VALID_REPORT LIKE '%' + @CONTFLAG + '%'
	---AND EXCHANGE + SEGMENT = (CASE WHEN @EXCHANGE <> '' THEN @EXCHANGE ELSE EXCHANGE + SEGMENT END)
	AND SEGMENT = (CASE WHEN @EXCHANGE <> '' THEN RIGHT(@EXCHANGE,7) ELSE SEGMENT END)
	AND EXCHANGE = (CASE WHEN RIGHT(@EXCHANGE,7) = 'FUTURES' THEN LEFT(@EXCHANGE,3) ELSE EXCHANGE END)	
	AND LEFT(BFCF_FLAG, 2) <> (CASE WHEN @FNO_CONTRACT_BILL = 0 THEN 'BF' ELSE 'DF' END)
	AND EXISTS (SELECT EXCHANGE FROM #EXCHANGELIST E WHERE E.EXCHANGE = LTRIM(RTRIM(C.EXCHANGE))+LTRIM(RTRIM(C.SEGMENT)) )


CREATE CLUSTERED INDEX [IDXCONT] ON [DBO].[#CONTRACT] (
	[PARTY_CODE],
	[EXCHANGE],
	[SEGMENT],
	[SCRIPNAME]
	)
	

ALTER TABLE #CONTRACT
ALTER COLUMN EXCHANGE VARCHAR(5)

UPDATE	#CONTRACT SET INTEROPCODE = ISNULL(VALUE,'') 
FROM	#INTEROP_SETT 
WHERE	#INTEROP_SETT.SEGMENT IN ('NSECAPITAL','BSECAPITAL')
		--AND RIGHT(#INTEROP_SETT.SEGMENT,6) = #CONTRACT.SEGMENT
		AND #CONTRACT.SEGMENT = 'CAPITAL'

UPDATE	#CONTRACT SET INTEROPCODE = ISNULL(VALUE,'') 
FROM	#INTEROP_SETT 
WHERE	#INTEROP_SETT.SEGMENT IN ('NSEFUTURES','BSEFUTURES')
		--AND RIGHT(#INTEROP_SETT.SEGMENT,7) = #CONTRACT.SEGMENT
		AND #CONTRACT.EXCHANGE+#CONTRACT.SEGMENT IN ('NSEFUTURES','BSEFUTURES')

UPDATE	#CONTRACT SET INTEROPCODE = ISNULL(VALUE,'')
FROM	#INTEROP_SETT 
WHERE	#INTEROP_SETT.SEGMENT IN ('NSXFUTURES','BSXFUTURES')
		--AND RIGHT(#INTEROP_SETT.SEGMENT,7) = #CONTRACT.SEGMENT
		AND #CONTRACT.EXCHANGE+#CONTRACT.SEGMENT IN ('NSXFUTURES','BSXFUTURES','MCDFUTURES')

UPDATE	#CONTRACT SET TMARK = (CASE WHEN INTEROPCODE <> '' THEN '' ELSE TMARK END)

UPDATE	#CONTRACT SET SCRIPDESC = ISNULL(C.SCRIPNAME,'')
FROM	#CONTDATA C
WHERE	LTRIM(RTRIM(C.ISIN)) = LTRIM(RTRIM(#CONTRACT.ISIN))
		AND C.SEGMENT = #CONTRACT.SEGMENT
		AND C.SEGMENT = 'CAPITAL' AND C.EXCHANGE = 'NSE'


/*
SELECT * INTO #CONTRACT_1 FROM #CONTRACT

UPDATE	#CONTRACT
SET		TMARK = ''
FROM	#CONTRACT_1 A
WHERE	A.PARTY_CODE = #CONTRACT.PARTY_CODE
		AND LEFT(A.SAUDA_DATE,11) = LEFT(#CONTRACT.SAUDA_DATE,11)
		AND A.CONTRACTNO_NEW = #CONTRACT.CONTRACTNO_NEW
		AND A.SCRIPNAME = #CONTRACT.SCRIPNAME
		AND A.SELL_BUY <> #CONTRACT.SELL_BUY
		AND A.SEGMENT = #CONTRACT.SEGMENT
		AND A.SEGMENT = 'CAPITAL'
*/


UPDATE	#CONTRACT
SET		CONTRACTNO = ISNULL(C.CONTRACTNO,''),
		SETT_NO = ISNULL(C.SETT_NO,''),
		SETT_DATE = ISNULL(C.SETT_DATE,''),
		SETT_TYPE = (
		CASE
			WHEN C.SETT_TYPE = (CASE WHEN INTEROPCODE = 'NSCCL' THEN 'D' ELSE 'N' END) THEN (CASE WHEN INTEROPCODE = 'NSCCL' THEN 'N' ELSE 'D' END)
			WHEN C.SETT_TYPE = (CASE WHEN INTEROPCODE = 'NSCCL' THEN 'C' ELSE 'W' END) THEN (CASE WHEN INTEROPCODE = 'NSCCL' THEN 'W' ELSE 'C' END)
			WHEN C.SETT_TYPE = (CASE WHEN INTEROPCODE = 'NSCCL' THEN 'AD' ELSE 'A' END) THEN (CASE WHEN INTEROPCODE = 'NSCCL' THEN 'A' ELSE 'AD' END)
			WHEN C.SETT_TYPE = (CASE WHEN INTEROPCODE = 'NSCCL' THEN 'AC' ELSE 'X' END) THEN (CASE WHEN INTEROPCODE = 'NSCCL' THEN 'X' ELSE 'AC' END)
			ELSE C.SETT_TYPE
		END),
		EXCHANGE = (CASE WHEN INTEROPCODE = 'NSCCL' THEN 'NSE' ELSE 'BSE' END),
		SETTTYPE_DESC = (
		CASE
			WHEN INTEROPCODE = 'NSCCL'	AND C.SETT_TYPE = 'D' THEN 'Normal'
			WHEN INTEROPCODE = 'NSCCL'	AND C.SETT_TYPE = 'C' THEN 'Trade For Trade'
			WHEN INTEROPCODE = 'NSCCL'	AND C.SETT_TYPE = 'A' THEN 'Auction'
			WHEN INTEROPCODE = 'NSCCL'	AND C.SETT_TYPE = 'X' THEN 'Auction Trade For Trade'
			WHEN INTEROPCODE = 'ICCl'	AND C.SETT_TYPE = 'N' THEN 'Rolling Market'
			WHEN INTEROPCODE = 'ICCl'	AND C.SETT_TYPE = 'W' THEN 'Odd Lot'
			WHEN INTEROPCODE = 'ICCl'	AND C.SETT_TYPE = 'AD' THEN 'Auction Rolling'
			WHEN INTEROPCODE = 'ICCl'	AND C.SETT_TYPE = 'AC' THEN 'Auction Odd Lot'
			ELSE C.SETTTYPE_DESC
		END)
FROM	#CONTDATA C
WHERE	LEFT(CONVERT(DATETIME,#CONTRACT.SAUDA_DATE,103),11) = LEFT(C.SAUDA_DATE,11)
		AND #CONTRACT.PARTY_CODE = C.PARTY_CODE
		AND #CONTRACT.EXCHANGE = (CASE WHEN INTEROPCODE = 'NSCCL' THEN 'BSE' ELSE 'NSE' END)
		AND #CONTRACT.SEGMENT = 'CAPITAL'
		AND C.EXCHANGE = (CASE WHEN INTEROPCODE = 'NSCCL' THEN 'NSE' ELSE 'BSE' END)
		AND C.SEGMENT = 'CAPITAL'
		AND C.SETT_TYPE IN ('N','W','D','C','AD','AC','A','X','M','Z')
		AND #CONTRACT.SETT_TYPE IN ('N','W','D','C','AD','AC','A','X')
		AND INTEROPCODE <> ''


UPDATE	#CONTRACT
SET		SETT_NO = ISNULL(SM.SETT_NO,''),
		SETT_DATE = CONVERT(VARCHAR,ISNULL(SM.FUNDS_PAYIN,''),103),
		SETT_TYPE = ISNULL(SM.SETT_TYPE,''),
		EXCHANGE = (CASE WHEN INTEROPCODE = 'NSCCL' THEN 'NSE' ELSE 'BSE' END),
		SETTTYPE_DESC = (
		CASE
			WHEN INTEROPCODE = 'NSCCL'	AND #CONTRACT.SETT_TYPE = 'D' THEN 'Normal'
			WHEN INTEROPCODE = 'NSCCL'	AND #CONTRACT.SETT_TYPE = 'C' THEN 'Trade For Trade'
			WHEN INTEROPCODE = 'NSCCL'	AND #CONTRACT.SETT_TYPE = 'A' THEN 'Auction'
			WHEN INTEROPCODE = 'NSCCL'	AND #CONTRACT.SETT_TYPE = 'X' THEN 'Auction Trade For Trade'
			WHEN INTEROPCODE = 'ICCl'	AND #CONTRACT.SETT_TYPE = 'N' THEN 'Rolling Market'
			WHEN INTEROPCODE = 'ICCl'	AND #CONTRACT.SETT_TYPE = 'W' THEN 'Odd Lot'
			WHEN INTEROPCODE = 'ICCl'	AND #CONTRACT.SETT_TYPE = 'AD' THEN 'Auction Rolling'
			WHEN INTEROPCODE = 'ICCl'	AND #CONTRACT.SETT_TYPE = 'AC' THEN 'Auction Odd Lot'
			ELSE #CONTRACT.SETTTYPE_DESC
		END)
FROM	SETT_MST SM (NOLOCK)
WHERE	SM.START_DATE BETWEEN @FROMDATE AND @TODATE + ' 23:59:59'
		AND LEFT(CONVERT(DATETIME,#CONTRACT.SAUDA_DATE,103),11) = LEFT(SM.START_DATE,11)
		AND SM.SETT_TYPE = (CASE	WHEN #CONTRACT.SETT_TYPE='D' THEN 'N'
									WHEN #CONTRACT.SETT_TYPE='C' THEN 'W'
									WHEN #CONTRACT.SETT_TYPE='AD' THEN 'A'
									WHEN #CONTRACT.SETT_TYPE='AC' THEN 'X'
									ELSE 'ZZ'
								END)
		AND #CONTRACT.INTEROPCODE <> ''
		AND #CONTRACT.SEGMENT = 'CAPITAL'
		AND #CONTRACT.EXCHANGE = 'BSE'
		AND #CONTRACT.EXCHANGE <> (CASE WHEN INTEROPCODE = 'NSCCL' THEN 'NSE' ELSE 'BSE' END)
		AND #CONTRACT.SETT_TYPE IN ('N','W','D','C','AD','AC','A','X')


UPDATE	#CONTRACT
SET		SETT_NO = ISNULL(SM.SETT_NO,''),
		SETT_DATE = CONVERT(VARCHAR,ISNULL(SM.FUNDS_PAYIN,''),103),
		SETT_TYPE = ISNULL(SM.SETT_TYPE,''),
		EXCHANGE = (CASE WHEN INTEROPCODE = 'NSCCL' THEN 'NSE' ELSE 'BSE' END),
		SETTTYPE_DESC = (
		CASE
			WHEN INTEROPCODE = 'NSCCL'	AND #CONTRACT.SETT_TYPE = 'D' THEN 'Normal'
			WHEN INTEROPCODE = 'NSCCL'	AND #CONTRACT.SETT_TYPE = 'C' THEN 'Trade For Trade'
			WHEN INTEROPCODE = 'NSCCL'	AND #CONTRACT.SETT_TYPE = 'A' THEN 'Auction'
			WHEN INTEROPCODE = 'NSCCL'	AND #CONTRACT.SETT_TYPE = 'X' THEN 'Auction Trade For Trade'
			WHEN INTEROPCODE = 'ICCL'	AND #CONTRACT.SETT_TYPE = 'M' THEN 'Rolling Market'
			WHEN INTEROPCODE = 'ICCL'	AND #CONTRACT.SETT_TYPE = 'Z' THEN 'Trade For Trade'
			WHEN INTEROPCODE = 'ICCl'	AND #CONTRACT.SETT_TYPE = 'N' THEN 'Rolling Market'
			WHEN INTEROPCODE = 'ICCl'	AND #CONTRACT.SETT_TYPE = 'W' THEN 'Odd Lot'
			WHEN INTEROPCODE = 'ICCl'	AND #CONTRACT.SETT_TYPE = 'AD' THEN 'Auction Rolling'
			WHEN INTEROPCODE = 'ICCl'	AND #CONTRACT.SETT_TYPE = 'AC' THEN 'Auction Odd Lot'
			ELSE #CONTRACT.SETTTYPE_DESC
		END)
FROM	BSEDB.DBO.SETT_MST SM (NOLOCK)
WHERE	SM.START_DATE BETWEEN @FROMDATE AND @TODATE + ' 23:59:59'
		AND LEFT(CONVERT(DATETIME,#CONTRACT.SAUDA_DATE,103),11) = LEFT(SM.START_DATE,11)
		AND SM.SETT_TYPE = (CASE	WHEN #CONTRACT.SETT_TYPE='N' THEN 'D'
									WHEN #CONTRACT.SETT_TYPE='W' THEN 'C'
									WHEN #CONTRACT.SETT_TYPE='A' THEN 'AD'
									WHEN #CONTRACT.SETT_TYPE='X' THEN 'AC'
									WHEN #CONTRACT.SETT_TYPE='M' THEN 'RD'
									WHEN #CONTRACT.SETT_TYPE='Z' THEN 'RC'
									ELSE 'ZZ'
								END)
		AND #CONTRACT.INTEROPCODE <> ''
		AND #CONTRACT.SEGMENT = 'CAPITAL'
		AND #CONTRACT.EXCHANGE = 'NSE'
		AND #CONTRACT.EXCHANGE <> (CASE WHEN INTEROPCODE = 'NSCCL' THEN 'NSE' ELSE 'BSE' END)
		AND #CONTRACT.SETT_TYPE IN ('N','W','D','C','AD','AC','A','X','M','Z')





UPDATE	#CONTRACT
SET		CONTRACTNO = ISNULL(C.CONTRACTNO,''),
		EXCHANGE = (CASE WHEN INTEROPCODE = 'NSCCL' THEN 'NSE' ELSE 'BSE' END)
FROM	#CONTDATA C
WHERE	LEFT(CONVERT(DATETIME,#CONTRACT.SAUDA_DATE,103),11) = LEFT(C.SAUDA_DATE,11)
		AND #CONTRACT.PARTY_CODE = C.PARTY_CODE
		AND #CONTRACT.EXCHANGE = (CASE WHEN INTEROPCODE = 'NSCCL' THEN 'BSE' ELSE 'NSE' END)
		AND #CONTRACT.SEGMENT = C.SEGMENT
		AND C.EXCHANGE = (CASE WHEN INTEROPCODE = 'NSCCL' THEN 'NSE' ELSE 'BSE' END)
		AND C.SEGMENT = 'FUTURES'
		AND C.EXCHANGE IN ('NSE','BSE')
		AND INTEROPCODE <> ''


UPDATE	#CONTRACT
SET		EXCHANGE = (CASE 
						WHEN INTEROPCODE = 'NSCCL' THEN 'NSX' 
						WHEN INTEROPCODE = 'ICCL' THEN 'BSX' 
						ELSE EXCHANGE END)
WHERE	EXCHANGE IN ('NSX','BSX','MCD')


UPDATE	#CONTRACT
SET		CONTRACTNO = ISNULL(C.CONTRACTNO,''),
		EXCHANGE = (CASE 
						WHEN INTEROPCODE = 'NSCCL' THEN 'NSX' 
						WHEN INTEROPCODE = 'ICCL' THEN 'BSX'
						ELSE #CONTRACT.EXCHANGE
					END)
FROM	#CONTDATA C
WHERE	LEFT(CONVERT(DATETIME,#CONTRACT.SAUDA_DATE,103),11) = LEFT(C.SAUDA_DATE,11)
		AND #CONTRACT.PARTY_CODE = C.PARTY_CODE
		AND #CONTRACT.EXCHANGE IN ('NSX','BSX','MCD')
		AND #CONTRACT.SEGMENT = C.SEGMENT
		AND C.EXCHANGE = (CASE WHEN INTEROPCODE = 'NSCCL' THEN 'NSX' ELSE C.EXCHANGE END)
		AND C.SEGMENT = 'FUTURES'
		AND C.EXCHANGE IN ('NSX','BSX','MCD')
		AND INTEROPCODE <> ''


UPDATE	#CONTRACT
SET		CONTRACT_HEADER_DET = (
		CASE
			WHEN INTEROPCODE = 'NSCCL' THEN  + 'Clearing Corporation Cash Market (BSE & NSE)::  NCL (NSE Clearing Ltd.)'
			WHEN INTEROPCODE = 'ICCL' THEN  + 'Clearing Corporation Cash Market (BSE & NSE)::  ICCL (Indian Clearing Corporation Ltd.)'
			ELSE CONTRACT_HEADER_DET
		END) + (
		CASE 
			WHEN SEGMENT = 'CAPITAL' THEN ' (' + LTRIM(RTRIM(SETT_NO)) + ' - ' + LTRIM(RTRIM(SETT_DATE)) + ')'  --+ ' - Ref. No: ' + LTRIM(RTRIM(CONTRACTNO)) + ')' 
			ELSE 'Ref. No: ' + LTRIM(RTRIM(CONTRACTNO)) 
		END)
WHERE	SETT_TYPE IN ('N','W','D','C','AD','AC','A','X','') AND SEGMENT = 'CAPITAL'
		AND INTEROPCODE <> ''

UPDATE	#CONTRACT
SET		CONTRACT_HEADER_DET = (
		CASE 
			WHEN INTEROPCODE = 'NSCCL' THEN 'Clearing Coporation for Equity Derivative :: NCL - (NSE Clearing Ltd.)' + (
			CASE WHEN LEFT(BFCF_FLAG, 2) = 'BF' THEN ' - Broght Forward Position' ELSE '' END)
			WHEN INTEROPCODE = 'ICCL' THEN 'Clearing Coporation for Equity Derivative :: ICCL (Indian Clearing Corporation Ltd.)' + (
			CASE WHEN LEFT(BFCF_FLAG, 2) = 'BF' THEN ' - Broght Forward Position' ELSE '' END)
			ELSE CONTRACT_HEADER_DET
		END)								
WHERE	SEGMENT = 'FUTURES' AND EXCHANGE_OLD IN ('NSE','BSE')
		AND (BFCF_FLAG = 'BF_F' OR LEFT(BFCF_FLAG, 2) = 'BT')
		AND INTEROPCODE <> ''


UPDATE	#CONTRACT
SET		CONTRACT_HEADER_DET = (
		CASE
			WHEN INTEROPCODE = 'NSCCL' THEN 'Clearing Coporation for Currency Derivatives Market :: NCL - (NSE Clearing Ltd.)' + (
			CASE WHEN LEFT(BFCF_FLAG, 2) = 'BF' THEN ' - Broght Forward Position' ELSE '' END)
			WHEN INTEROPCODE = 'ICCL' THEN 'Clearing Coporation for Currency Derivatives Market :: ICCL (Indian Clearing Corporation Ltd.)' + (
			CASE WHEN LEFT(BFCF_FLAG, 2) = 'BF' THEN ' - Broght Forward Position' ELSE '' END)
			ELSE CONTRACT_HEADER_DET
		END)			
WHERE	SEGMENT = 'FUTURES' AND EXCHANGE_OLD IN ('NSX','BSX','MCD')
		AND (BFCF_FLAG = 'BF_F' OR LEFT(BFCF_FLAG, 2) = 'BT')
		AND INTEROPCODE <> ''
		



--UPDATE	#CONTRACT SET EXCHANGE = @INTEROP WHERE SEGMENT = 'CAPITAL'

--UPDATE	#CONTRACT SET EXCHANGE = @INTEROP WHERE SEGMENT = 'FUTURES'


/*

	SELECT DISTINCT PARTY_CODE,
		SAUDA_DATE,
		SETTLEMENT_DET = STUFF((
				SELECT DISTINCT EXCHANGE + '-' + SEGMENT + '-' + LTRIM(RTRIM(SETT_NO)) + '-' + LTRIM(RTRIM(SETTTYPE_DESC)) + '-' + Sett_Date + '-' + LTRIM(RTRIM(CONTRACTNO)) + '#'
				FROM #CONTRACT C
				WHERE B.PARTY_CODE = C.PARTY_CODE
					AND B.SAUDA_DATE = C.SAUDA_DATE
					AND C.SEGMENT = 'CAPITAL'
					AND C.CONTRACTNO <> 0
				ORDER BY 1
				FOR XML PATH('')
				), 1, 0, ''),
		CONTRACTNO_DET = STUFF((
				SELECT DISTINCT EXCHANGE + '-' + SEGMENT + '-' + LTRIM(RTRIM(CONTRACTNO)) + '#'
				FROM #CONTRACT C
				WHERE B.PARTY_CODE = C.PARTY_CODE
					AND B.SAUDA_DATE = C.SAUDA_DATE
					AND C.CONTRACTNO <> 0
				ORDER BY 1
				FOR XML PATH('')
				), 1, 0, ''),
		BROKERSEBIREGNO_DET = STUFF((
				SELECT DISTINCT EXCHANGE + ' ' + SEGMENT + '-' + LTRIM(RTRIM(BROKERSEBIREGNO)) + '#'
				FROM #CONTRACT C
				WHERE B.PARTY_CODE = C.PARTY_CODE
					AND B.SAUDA_DATE = C.SAUDA_DATE
				ORDER BY 1
				FOR XML PATH('')
				), 1, 0, ''),
		MEMBERCODE_DET = STUFF((
				SELECT DISTINCT EXCHANGE + ' ' + SEGMENT + '-' + LTRIM(RTRIM(MEMBERCODE)) + '#'
				FROM #CONTRACT C
				WHERE B.PARTY_CODE = C.PARTY_CODE
					AND B.SAUDA_DATE = C.SAUDA_DATE
				ORDER BY 1
				FOR XML PATH('')
				), 1, 0, ''),
		CIN_DET=STUFF((
				SELECT DISTINCT EXCHANGE + ' ' + SEGMENT + '-' + LTRIM(RTRIM(CINNO)) + '#'
				FROM #CONTRACT C
				WHERE B.PARTY_CODE = C.PARTY_CODE
					AND B.SAUDA_DATE = C.SAUDA_DATE
				ORDER BY 1
				FOR XML PATH('')
				), 1, 0, '')		
	INTO	#CONTSETT_DET
	FROM	#CONTRACT B
	*/


/* ---- START CHANGES FOR T1T2 SETTELEMENT ---*/

UPDATE	#CONTRACT
SET		SETTTYPE_DESC = (
		CASE
			WHEN #CONTRACT.SETT_TYPE = 'RD' THEN 'Normal'
			WHEN #CONTRACT.SETT_TYPE = 'RC' THEN 'Trade For Trade'
			WHEN #CONTRACT.SETT_TYPE = 'TD' THEN 'Normal'
			ELSE SETTTYPE_DESC
		END),
		SETT_TYPE = LTRIM(RTRIM(T.NSE_SETT_TYPE)),
		SETT_NO = LTRIM(RTRIM(SM.SETT_NO))
FROM	TBL_INTEROP_SETT_TYPE T(NOLOCK),
		SETT_MST SM(NOLOCK)
WHERE	T.BSE_SETT_TYPE = #CONTRACT.SETT_TYPE
		AND T.NSE_SETT_TYPE = SM.SETT_TYPE
		--AND SM.START_DATE BETWEEN @FROMDATE AND @TODATE + ' 23:59:59'
		AND CONVERT(VARCHAR,SM.START_DATE,112) = #CONTRACT.ORD_DATE
		AND INTEROPCODE = 'NSCCL'
		AND #CONTRACT.SETT_TYPE_OLD IN ('M','Z','RD','RC','TD','5')


UPDATE	#CONTRACT
SET		SETTTYPE_DESC = (
		CASE
			WHEN #CONTRACT.SETT_TYPE = 'M' THEN 'Rolling Market'
			WHEN #CONTRACT.SETT_TYPE = 'Z' THEN 'Odd Lot'
			WHEN #CONTRACT.SETT_TYPE = '5' THEN 'Rolling Market'
			ELSE SETTTYPE_DESC
		END),
		SETT_TYPE = LTRIM(RTRIM(T.BSE_SETT_TYPE)),
		SETT_NO = LTRIM(RTRIM(SM.SETT_NO))
FROM	TBL_INTEROP_SETT_TYPE T(NOLOCK),
		BSEDB.DBO.SETT_MST SM(NOLOCK)
WHERE	T.NSE_SETT_TYPE = #CONTRACT.SETT_TYPE
		AND T.BSE_SETT_TYPE = SM.SETT_TYPE
		--AND SM.START_DATE BETWEEN @FROMDATE AND @TODATE + ' 23:59:59'
		AND CONVERT(VARCHAR,SM.START_DATE,112) = #CONTRACT.ORD_DATE
		AND INTEROPCODE = 'ICCL'
		AND #CONTRACT.SETT_TYPE_OLD IN ('M','Z','RD','RC')


UPDATE	#CONTRACT
SET		CONTRACT_HEADER_DET = (
		CASE
			WHEN INTEROPCODE = 'NSCCL' THEN  + 'Clearing Corporation Cash Market (BSE & NSE)::  NCL (NSE Clearing Ltd.)'
			WHEN INTEROPCODE = 'ICCL' THEN  + 'Clearing Corporation Cash Market (BSE & NSE)::  ICCL (Indian Clearing Corporation Ltd.)'
			ELSE CONTRACT_HEADER_DET
		END) + (
		CASE 
			WHEN SEGMENT = 'CAPITAL' THEN ' (' + LTRIM(RTRIM(SETT_NO)) + ' - ' + LTRIM(RTRIM(SETT_DATE)) + ' - Ref. No: ' + LTRIM(RTRIM(CONTRACTNO)) + ')' 
			ELSE 'Ref. No: ' + LTRIM(RTRIM(CONTRACTNO)) 
		END),
		EXCHANGE = (
		CASE 
			WHEN INTEROPCODE = 'NSCCL' THEN 'NSE' 
			WHEN INTEROPCODE = 'ICCL' THEN 'BSE'
			ELSE EXCHANGE 
		END)
WHERE	SETT_TYPE IN ('M','Z','RD','RC','TD','5') AND SEGMENT = 'CAPITAL'
		AND INTEROPCODE <> ''


IF (CONVERT(DATETIME,@FROMDATE) < 'JAN 27 2023')
BEGIN
	UPDATE	#CONTRACT SET SETTTYPE_DESC = LTRIM(RTRIM(SETTTYPE_DESC)) + (CASE WHEN LTRIM(RTRIM(SETTTYPE_DESC)) <> '' THEN ' ' + (
			CASE
				WHEN SETT_TYPE_OLD IN ('M','Z','RD','RC') THEN 'T1'
				WHEN SETT_TYPE_OLD IN ('TD','5') THEN 'T0'
				ELSE 'T2'
			END) ELSE '' END) /*,
			EXCHANGE = (
			CASE 
				WHEN INTEROPCODE = 'NSCCL' THEN 'NSE' 
				WHEN INTEROPCODE = 'ICCL' THEN 'BSE'
				ELSE EXCHANGE 
			END)
			*/
END
ELSE
BEGIN
	UPDATE	#CONTRACT SET SETTTYPE_DESC = LTRIM(RTRIM(SETTTYPE_DESC)) + (CASE WHEN LTRIM(RTRIM(SETTTYPE_DESC)) <> '' THEN ' ' + 'T1' ELSE '' END)
	WHERE   SETT_TYPE_OLD not IN ('TD','5')
	UPDATE	#CONTRACT SET SETTTYPE_DESC = LTRIM(RTRIM(SETTTYPE_DESC)) + (CASE WHEN LTRIM(RTRIM(SETTTYPE_DESC)) <> '' THEN ' ' + 'T0' ELSE '' END)
	WHERE   SETT_TYPE_OLD IN ('TD','5')
END

/* ---- END CHANGES FOR T1T2 SETTELEMENT ---*/

UPDATE	#CONTRACT
SET		SETT_NO = BSEDB.DBO.CONVERTSETTNO(#CONTRACT.SETT_NO,#CONTRACT.SAUDA_DATE,1)
FROM	DEL_MARKETTYPE D (NOLOCK)
WHERE	D.SETT_TYPE = #CONTRACT.SETT_TYPE
		AND IS_SETT_CHANGE = 1 AND D.EXCHANGE = 'BSE' and #CONTRACT.EXCHANGE='BSE' AND #CONTRACT.SEGMENT ='CAPITAL'
		AND INTEROPCODE = 'ICCl'


IF (@EXCHANGE <> '')
BEGIN
	UPDATE #CONTRACT
	SET SETTLEMENT_DET = CASE WHEN EXCHANGE ='NSX' THEN 'NSE' ELSE EXCHANGE END + '-' + CASE WHEN EXCHANGE ='NSX' THEN 'Currency Derivatives' 
	WHEN SEGMENT ='CAPITAL' THEN 'Capital Market' ELSE 'Derivatives' END + '-' + LTRIM(RTRIM(SETT_NO)) + '-' + LTRIM(RTRIM(SETTTYPE_DESC)) 
	+ '-' + SETT_DATE + '-' + '' + '#',
		CONTRACTNO_DET = EXCHANGE + '-' + SEGMENT + '-' + LTRIM(RTRIM(CONTRACTNO)) + '#',
		BROKERSEBIREGNO_DET = EXCHANGE + ' ' + SEGMENT + '-' + LTRIM(RTRIM(BROKERSEBIREGNO)) + '#',
		MEMBERCODE_DET = EXCHANGE + ' ' + SEGMENT + '-' + LTRIM(RTRIM(MEMBERCODE)) + '#',
		CIN_DET = EXCHANGE + ' ' + SEGMENT + '-' + LTRIM(RTRIM(CINNO)) + '#'
END
ELSE
BEGIN

	DECLARE @PARTY_CODE VARCHAR(20)
	DECLARE @DESC VARCHAR(MAX)
	DECLARE @SAUDA_DATE VARCHAR(20)

	CREATE TABLE #SETTLEMENT_DET
	(  
	PARTY_CODE		VARCHAR(20),
	SAUDA_DATE		VARCHAR(11), 
	CONTRACTNO_NEW	VARCHAR(10),
	SETTLEMENT_DET	VARCHAR(1000),
	EXCHANGE1		VARCHAR(10),
	SEGMENT1		VARCHAR(10),
	ORDFLAG			INT
	)
	CREATE CLUSTERED INDEX [IDXSETTCONT] ON [DBO].[#SETTLEMENT_DET] (  
	[PARTY_CODE],  
	[CONTRACTNO_NEW], 
	[ORDFLAG],
	[EXCHANGE1],  
	[SEGMENT1]  
	)
	

	IF (CONVERT(DATETIME,@FROMDATE) < 'JAN 27 2023')
	BEGIN
		UPDATE	#CONTRACT SET SETT_DATE = ISNULL(FUNDS_PAYIN,'')
		FROM	(
				SELECT FUNDS_PAYIN = CONVERT(VARCHAR,MIN(SEC_PAYIN),103) FROM MSAJAG.DBO.SETT_MST (NOLOCK) 
				WHERE START_DATE < @FROMDATE AND FUNDS_PAYIN > @FROMDATE
				AND SETT_TYPE = 'N'
				) A 
		WHERE	SETT_DATE = '' AND SEGMENT='FUTURES' 
	END
	ELSE
	BEGIN
		UPDATE	#CONTRACT
		SET		SETT_DATE = CONVERT(VARCHAR,ISNULL(FUNDS_PAYIN,''),103)
		FROM	MSAJAG.DBO.SETT_MST M (NOLOCK)
		WHERE	START_DATE BETWEEN @FROMDATE AND @FROMDATE + ' 23:59:59' AND M.SETT_TYPE = 'M'
				AND #CONTRACT.SETT_DATE = '' AND #CONTRACT.SEGMENT='FUTURES' 
	END

	
	UPDATE #CONTRACT SET SETT_DATE = SAUDA_DATE
	WHERE SETT_DATE = ''

	SELECT DISTINCT PARTY_CODE,
		SAUDA_DATE, CONTRACTNO_NEW,
		SETTLEMENT_DET = CASE WHEN EXCHANGE = 'NSX' THEN 'NSE' ELSE EXCHANGE END + '-' +
		CASE 
			WHEN EXCHANGE_OLD IN ('NSX','BSX','MCD') THEN 'Currency Derivatives' 
			WHEN SEGMENT ='CAPITAL' THEN 'Capital Market' 
			ELSE 'Derivatives' 
		END
		+ '-' + LTRIM(RTRIM(SETT_NO)) + '-' 
		--+ (CASE WHEN INTEROPCODE <> '' AND SETT_TYPE IN ('N','W','D','C','AD','AC','A','X') THEN '' ELSE LTRIM(RTRIM(SETTTYPE_DESC)) END)
		+ LTRIM(RTRIM(SETTTYPE_DESC))
		--+ '-' + SETT_DATE + '-' + '' + '#',
		+ '-' + SETT_DATE + '-' + LTRIM(RTRIM(CONTRACTNO)) + '#',

		EXCHANGE1 = EXCHANGE, SEGMENT1 = SEGMENT, 
		ORDFLAG = (
		CASE 
			WHEN SEGMENT='CAPITAL' THEN 1
			WHEN EXCHANGE_OLD IN ('NSE','BSE') AND SEGMENT='FUTURES' THEN 2
			WHEN EXCHANGE_OLD IN ('NSX','BSX','MCD') AND SEGMENT='FUTURES' THEN 3
			ELSE 4
		END)
	INTO #SETTLEMENT_DET_1
	FROM #CONTRACT
	--WHERE CONTRACTNO <> 0
	ORDER BY PARTY_CODE, CONTRACTNO_NEW

	
	IF @EXCHANGE = ''
	BEGIN
		IF @INTEROP = 'NSCCL' OR @INTEROPFNO='NSCCL' OR @INTEROPCUR='NSCCL'
			BEGIN
			INSERT INTO #SETTLEMENT_DET_1
			SELECT PARTY_CODE, SAUDA_DATE, CONTRACTNO_NEW,
			CASE WHEN EXCHANGE ='NSX' THEN 'NSE' ELSE EXCHANGE END + '-' + CASE WHEN EXCHANGE IN ('NSX','BSX','MCD') THEN 'Currency Derivatives' WHEN SEGMENT ='CAPITAL' THEN 'Capital Market' ELSE 'Derivatives' END
				+ '-' + '.' + '-' +(
				CASE 
					WHEN EXCHANGE+SEGMENT = 'BSECAPITAL' AND @INTEROP <> '' AND @INTEROP = 'NSCCL' THEN 'NA'
					WHEN EXCHANGE+SEGMENT = 'NSECAPITAL' AND @INTEROP <> '' AND @INTEROP = 'ICCL'	THEN 'NA'
					WHEN EXCHANGE+SEGMENT = 'BSEFUTURES' AND @INTEROPFNO <> '' AND @INTEROPFNO = 'NSCCL' THEN 'NA'
					WHEN EXCHANGE+SEGMENT = 'NSEFUTURES' AND @INTEROPFNO <> '' AND @INTEROPFNO = 'ICCL'	THEN 'NA'
					WHEN EXCHANGE+SEGMENT = 'BSXFUTURES' AND @INTEROPCUR <> '' AND @INTEROPCUR = 'NSCCL' THEN 'NA'
					WHEN EXCHANGE+SEGMENT = 'NSXFUTURES' AND @INTEROPCUR <> '' AND @INTEROPCUR = 'ICCL'	THEN 'NA'
					ELSE '.'
				END) 
				--+ '-' 
				--+ LTRIM(RTRIM(SETTTYPE_DESC)) 
				+ '-' + '.' + '-' + '.' + '#',
				EXCHANGE, SEGMENT,
				ORDFLAG = (
				CASE 
					WHEN SEGMENT='CAPITAL' THEN 1
					WHEN EXCHANGE IN ('NSE','BSE') AND SEGMENT='FUTURES' THEN 2
					WHEN EXCHANGE IN ('NSX','BSX','MCD') AND SEGMENT='FUTURES' THEN 3
					ELSE 4
				END)
			FROM PRADNYA.DBO.MULTICOMPANY, #SETTLEMENT_DET_1 D 
			--FROM   #SETTLEMENT_DET_1 D LEFT OUTER JOIN  PRADNYA.DBO.MULTICOMPANY
			--ON EXCHANGE=EXCHANGE1 AND SEGMENT=SEGMENT1 
			WHERE 
			PRIMARYSERVER = 1 
			AND SEGMENT IN ('CAPITAL','FUTURES')
			AND EXCHANGE NOT IN ('BCM','MFO','BXM','UCX','USM','USX','FDX','MCX','NCX','DGX','DXM','MDB','ACE','MCM','MFC','NCM','NMC','NSP','NXP','NXM','NDM','NDB','MXM','ICX' )
			AND EXCHANGE NOT IN (SELECT EXCHANGE1 FROM #SETTLEMENT_DET_1 
								 WHERE EXCHANGE1 = EXCHANGE AND SEGMENT = SEGMENT1
								 AND D.PARTY_CODE = #SETTLEMENT_DET_1.PARTY_CODE
								 AND D.CONTRACTNO_NEW = #SETTLEMENT_DET_1.CONTRACTNO_NEW)
			AND EXCHANGE IN ('NSE','NSX')
											   	
			GROUP BY PARTY_CODE, SAUDA_DATE, EXCHANGE, SEGMENT, CONTRACTNO_NEW
			ORDER BY PARTY_CODE, SAUDA_DATE, EXCHANGE, SEGMENT, CONTRACTNO_NEW
			END
		IF @INTEROP = 'ICCL' OR @INTEROPFNO='ICCL' OR @INTEROPCUR='ICCL'
			BEGIN
			INSERT INTO #SETTLEMENT_DET_1
			SELECT PARTY_CODE, SAUDA_DATE, CONTRACTNO_NEW,
			CASE WHEN EXCHANGE ='NSX' THEN 'NSE' ELSE EXCHANGE END + '-' + CASE WHEN EXCHANGE IN ('NSX','BSX','MCD') THEN 'Currency Derivatives' WHEN SEGMENT ='CAPITAL' THEN 'Capital Market' ELSE 'Derivatives' END
				+ '-' + '.' + '-' +(
				CASE 
					WHEN EXCHANGE+SEGMENT = 'BSECAPITAL' AND @INTEROP <> '' AND @INTEROP = 'NSCCL' THEN 'NA'
					WHEN EXCHANGE+SEGMENT = 'NSECAPITAL' AND @INTEROP <> '' AND @INTEROP = 'ICCL'	THEN 'NA'
					WHEN EXCHANGE+SEGMENT = 'BSEFUTURES' AND @INTEROPFNO <> '' AND @INTEROPFNO = 'NSCCL' THEN 'NA'
					WHEN EXCHANGE+SEGMENT = 'NSEFUTURES' AND @INTEROPFNO <> '' AND @INTEROPFNO = 'ICCL'	THEN 'NA'
					WHEN EXCHANGE+SEGMENT = 'BSXFUTURES' AND @INTEROPCUR <> '' AND @INTEROPCUR = 'NSCCL' THEN 'NA'
					WHEN EXCHANGE+SEGMENT = 'NSXFUTURES' AND @INTEROPCUR <> '' AND @INTEROPCUR = 'ICCL'	THEN 'NA'
					ELSE '.'
				END) 
				--+ '-' 
				--+ LTRIM(RTRIM(SETTTYPE_DESC)) 
				+ '-' + '.' + '-' + '.' + '#',
				EXCHANGE, SEGMENT,
				ORDFLAG = (
				CASE 
					WHEN SEGMENT='CAPITAL' THEN 1
					WHEN EXCHANGE IN ('NSE','BSE') AND SEGMENT='FUTURES' THEN 2
					WHEN EXCHANGE IN ('NSX','BSX','MCD') AND SEGMENT='FUTURES' THEN 3
					ELSE 4
				END)
			FROM PRADNYA.DBO.MULTICOMPANY, #SETTLEMENT_DET_1 D 
			--FROM   #SETTLEMENT_DET_1 D LEFT OUTER JOIN  PRADNYA.DBO.MULTICOMPANY
			--ON EXCHANGE=EXCHANGE1 AND SEGMENT=SEGMENT1 
			WHERE 
			PRIMARYSERVER = 1 
			AND SEGMENT IN ('CAPITAL','FUTURES')
			AND EXCHANGE NOT IN ('BCM','MFO','BXM','UCX','USM','USX','FDX','MCX','NCX','DGX','DXM','MDB','ACE','MCM','MFC','NCM','NMC','NSP','NXP','NXM','NDM','NDB','MXM','ICX' )
			AND EXCHANGE NOT IN (SELECT EXCHANGE1 FROM #SETTLEMENT_DET_1 
								 WHERE EXCHANGE1 = EXCHANGE AND SEGMENT = SEGMENT1
								 AND D.PARTY_CODE = #SETTLEMENT_DET_1.PARTY_CODE
								 AND D.CONTRACTNO_NEW = #SETTLEMENT_DET_1.CONTRACTNO_NEW)
			AND EXCHANGE IN ('BSE','BSX')	
	
											   	
			GROUP BY PARTY_CODE, SAUDA_DATE, EXCHANGE, SEGMENT, CONTRACTNO_NEW
			ORDER BY PARTY_CODE, SAUDA_DATE, EXCHANGE, SEGMENT, CONTRACTNO_NEW

		END 

		
	END 

	INSERT INTO #SETTLEMENT_DET
	SELECT * FROM #SETTLEMENT_DET_1
	ORDER BY PARTY_CODE, CONTRACTNO_NEW, ORDFLAG, EXCHANGE1, SEGMENT1

	
	ALTER TABLE #SETTLEMENT_DET

	ALTER COLUMN SETTLEMENT_DET VARCHAR(MAX)

	DECLARE @CONTRACTNO_NEW VARCHAR(MAX)
	SET @DESC = ''
	SET @PARTY_CODE = ''
	SET @SAUDA_DATE = ''
	SET @CONTRACTNO_NEW = ''
	
	
	UPDATE #SETTLEMENT_DET
	SET @DESC = SETTLEMENT_DET = CASE WHEN @PARTY_CODE = PARTY_CODE
				AND @SAUDA_DATE = SAUDA_DATE AND @CONTRACTNO_NEW = CONTRACTNO_NEW THEN @DESC + '' + SETTLEMENT_DET ELSE SETTLEMENT_DET END,
		@PARTY_CODE = PARTY_CODE,
		@SAUDA_DATE = SAUDA_DATE,
		@CONTRACTNO_NEW = CONTRACTNO_NEW

	--SELECT * FROM #SETTLEMENT_DET

	SELECT DISTINCT PARTY_CODE,
		SAUDA_DATE,CONTRACTNO_NEW,
		CONTRACTNO_DET = EXCHANGE + '-' + SEGMENT + '-' + LTRIM(RTRIM(CONTRACTNO)) + '#'
	INTO #CONTRACTNO_DET
	FROM #CONTRACT C
	--WHERE CONTRACTNO <> 0
	ORDER BY PARTY_CODE,CONTRACTNO_NEW

	ALTER TABLE #CONTRACTNO_DET

	ALTER COLUMN CONTRACTNO_DET VARCHAR(MAX)

	SET @DESC = ''
	SET @PARTY_CODE = ''
	SET @SAUDA_DATE = ''

	UPDATE #CONTRACTNO_DET
	SET @DESC = CONTRACTNO_DET = CASE WHEN @PARTY_CODE = PARTY_CODE
				AND @SAUDA_DATE = SAUDA_DATE AND @CONTRACTNO_NEW = CONTRACTNO_NEW THEN @DESC + '' + CONTRACTNO_DET ELSE CONTRACTNO_DET END,
		@PARTY_CODE = PARTY_CODE,
		@SAUDA_DATE = SAUDA_DATE,
		@CONTRACTNO_NEW= CONTRACTNO_NEW

	SELECT DISTINCT PARTY_CODE,
		SAUDA_DATE,
		CONTRACTNO_NEW,
		BROKERSEBIREGNO_DET = EXCHANGE + ' ' + SEGMENT + '-' + LTRIM(RTRIM(BROKERSEBIREGNO)) + '#'
	INTO #BROKERSEBIREGNO_DET
	FROM #CONTRACT C
	--WHERE CONTRACTNO <> 0
	ORDER BY PARTY_CODE

	ALTER TABLE #BROKERSEBIREGNO_DET

	ALTER COLUMN BROKERSEBIREGNO_DET VARCHAR(MAX)

	SET @DESC = ''
	SET @PARTY_CODE = ''
	SET @SAUDA_DATE = ''
	set @CONTRACTNO_NEW =''

	UPDATE #BROKERSEBIREGNO_DET
	SET @DESC = BROKERSEBIREGNO_DET = CASE WHEN @PARTY_CODE = PARTY_CODE
				AND @SAUDA_DATE = SAUDA_DATE THEN @DESC + '' + BROKERSEBIREGNO_DET ELSE BROKERSEBIREGNO_DET END,
		@PARTY_CODE = PARTY_CODE,
		@SAUDA_DATE = SAUDA_DATE,
		@CONTRACTNO_NEW = CONTRACTNO_NEW

	SELECT DISTINCT PARTY_CODE,
		SAUDA_DATE,
		CONTRACTNO_NEW,
		MEMBERCODE_DET = EXCHANGE + ' ' + SEGMENT + '-' + LTRIM(RTRIM(MEMBERCODE)) + '#'
	INTO #MEMBERCODE_DET
	FROM #CONTRACT C
	--WHERE CONTRACTNO <> 0
	ORDER BY PARTY_CODE

	ALTER TABLE #MEMBERCODE_DET

	ALTER COLUMN MEMBERCODE_DET VARCHAR(MAX)

	SET @DESC = ''
	SET @PARTY_CODE = ''
	SET @SAUDA_DATE = ''
	set @CONTRACTNO_NEW = ''

	UPDATE #MEMBERCODE_DET
	SET @DESC = MEMBERCODE_DET = CASE WHEN @PARTY_CODE = PARTY_CODE
				AND @SAUDA_DATE = SAUDA_DATE THEN @DESC + '' + MEMBERCODE_DET ELSE MEMBERCODE_DET END,
		@PARTY_CODE = PARTY_CODE,
		@SAUDA_DATE = SAUDA_DATE,
		@CONTRACTNO_NEW = CONTRACTNO_NEW

	SELECT DISTINCT PARTY_CODE,
		SAUDA_DATE,
		CONTRACTNO_NEW,
		CIN_DET = EXCHANGE + ' ' + SEGMENT + '-' + LTRIM(RTRIM(CINNO)) + '#'
	INTO #CIN_DET
	FROM #CONTRACT
	--WHERE CONTRACTNO <> 0
	ORDER BY PARTY_CODE

	ALTER TABLE #CIN_DET

	ALTER COLUMN CIN_DET VARCHAR(MAX)

	SET @DESC = ''
	SET @PARTY_CODE = ''
	SET @SAUDA_DATE = ''
	SET @CONTRACTNO_NEW = ''

	UPDATE #CIN_DET
	SET @DESC = CIN_DET = CASE WHEN @PARTY_CODE = PARTY_CODE
				AND @SAUDA_DATE = SAUDA_DATE THEN @DESC + '' + CIN_DET ELSE CIN_DET END,
		@PARTY_CODE = PARTY_CODE,
		@SAUDA_DATE = SAUDA_DATE,
		@CONTRACTNO_NEW = CONTRACTNO_NEW

	SELECT DISTINCT PARTY_CODE,
		SAUDA_DATE,
		CONTRACTNO_NEW,
		REMARK_DET = '(' + REMARK_ID + ')' + ':-' + REMARK_DESC + '#'
	INTO #REMARK_DET
	FROM #CONTRACT
	WHERE REMARK_ID <> ''
	ORDER BY PARTY_CODE
	
	
	ALTER TABLE #REMARK_DET

	ALTER COLUMN REMARK_DET VARCHAR(MAX)

	SET @DESC = ''
	SET @PARTY_CODE = ''
	SET @SAUDA_DATE = ''
	SET @CONTRACTNO_NEW = ''


	UPDATE #REMARK_DET
	SET @DESC = REMARK_DET = CASE WHEN @PARTY_CODE = PARTY_CODE
				AND @SAUDA_DATE = SAUDA_DATE THEN @DESC + ' ' + REMARK_DET ELSE REMARK_DET END,
		@PARTY_CODE = PARTY_CODE,
		@SAUDA_DATE = SAUDA_DATE,
		@CONTRACTNO_NEW = CONTRACTNO_NEW

	SELECT A1.PARTY_CODE,
		A1.SAUDA_DATE,
		SETTLEMENT_DET,
		CONTRACTNO_DET,
		BROKERSEBIREGNO_DET,
		MEMBERCODE_DET,
		CIN_DET,
		REMARK_DET,
		A1.CONTRACTNO_NEW		
	INTO #CONTSETT_DET
	FROM (
		SELECT DISTINCT PARTY_CODE,
			SAUDA_DATE,
			CONTRACTNO_NEW
		FROM #CONTRACT
		) A1
	LEFT JOIN (
		SELECT PARTY_CODE,
			SAUDA_DATE,
			SETTLEMENT_DET = MAX(SETTLEMENT_DET),
			CONTRACTNO_NEW
		FROM #SETTLEMENT_DET
		GROUP BY PARTY_CODE,
			SAUDA_DATE,
			CONTRACTNO_NEW
		) A
		ON (
				A1.SAUDA_DATE = A.SAUDA_DATE
				AND A1.PARTY_CODE = A.PARTY_CODE
				AND A1.CONTRACTNO_NEW = A.CONTRACTNO_NEW
				)
	LEFT JOIN (
		SELECT PARTY_CODE,
			SAUDA_DATE,
			CONTRACTNO_DET = MAX(CONTRACTNO_DET),
			CONTRACTNO_NEW
		FROM #CONTRACTNO_DET
		GROUP BY PARTY_CODE,
			SAUDA_DATE,
			CONTRACTNO_NEW
		) B
		ON (
				A1.SAUDA_DATE = B.SAUDA_DATE
				AND A1.PARTY_CODE = B.PARTY_CODE
				AND A1.CONTRACTNO_NEW = B.CONTRACTNO_NEW
				)
	LEFT JOIN (
		SELECT PARTY_CODE,
			SAUDA_DATE,
			BROKERSEBIREGNO_DET = MAX(BROKERSEBIREGNO_DET),
			CONTRACTNO_NEW
		FROM #BROKERSEBIREGNO_DET
		GROUP BY PARTY_CODE,
			SAUDA_DATE,
			CONTRACTNO_NEW
		) C
		ON (
				A1.SAUDA_DATE = C.SAUDA_DATE
				AND A1.PARTY_CODE = C.PARTY_CODE
				AND A1.CONTRACTNO_NEW = C.CONTRACTNO_NEW
				)
	LEFT JOIN (
		SELECT PARTY_CODE,
			SAUDA_DATE,
			MEMBERCODE_DET = MAX(MEMBERCODE_DET),
			CONTRACTNO_NEW
		FROM #MEMBERCODE_DET
		GROUP BY PARTY_CODE,
			SAUDA_DATE,
			CONTRACTNO_NEW
		) D
		ON (
				A1.SAUDA_DATE = D.SAUDA_DATE
				AND A1.PARTY_CODE = D.PARTY_CODE
				AND A1.CONTRACTNO_NEW = C.CONTRACTNO_NEW
				)
	LEFT JOIN (
		SELECT PARTY_CODE,
			SAUDA_DATE,
			CIN_DET = MAX(CIN_DET),
			CONTRACTNO_NEW
		FROM #CIN_DET
		GROUP BY PARTY_CODE,
			SAUDA_DATE,
			CONTRACTNO_NEW
		) E
		ON (
				A1.SAUDA_DATE = E.SAUDA_DATE
				AND A1.PARTY_CODE = E.PARTY_CODE
				AND A1.CONTRACTNO_NEW = C.CONTRACTNO_NEW
				)
	LEFT JOIN (
		SELECT PARTY_CODE,
			SAUDA_DATE,
			REMARK_DET = MAX(REMARK_DET),
			CONTRACTNO_NEW
		FROM #REMARK_DET
		GROUP BY PARTY_CODE,
			SAUDA_DATE,
			CONTRACTNO_NEW
		) F
		ON (
				A1.SAUDA_DATE = F.SAUDA_DATE
				AND A1.PARTY_CODE = F.PARTY_CODE
				AND A1.CONTRACTNO_NEW = C.CONTRACTNO_NEW
				)
	
	DROP TABLE #SETTLEMENT_DET

	DROP TABLE #CONTRACTNO_DET

	DROP TABLE #BROKERSEBIREGNO_DET

	DROP TABLE #MEMBERCODE_DET

	DROP TABLE #CIN_DET

	DROP TABLE #REMARK_DET

	ALTER TABLE #CONTRACT
	ALTER COLUMN SETTLEMENT_DET VARCHAR(MAX)

	ALTER TABLE #CONTRACT
	ALTER COLUMN CONTRACTNO_DET VARCHAR(MAX)

	UPDATE #CONTRACT
	SET SETTLEMENT_DET = ISNULL(C.SETTLEMENT_DET, ''),
		CONTRACTNO_DET = ISNULL(C.CONTRACTNO_DET, ''),
		BROKERSEBIREGNO_DET = ISNULL(C.BROKERSEBIREGNO_DET, ''),
		MEMBERCODE_DET = ISNULL(C.MEMBERCODE_DET, ''),
		CIN_DET = ISNULL(C.CIN_DET, ''),
		REMARK_DET = ISNULL(C.REMARK_DET, '')
	FROM #CONTSETT_DET C
	WHERE #CONTRACT.PARTY_CODE = C.PARTY_CODE
		AND #CONTRACT.SAUDA_DATE = C.SAUDA_DATE
		AND #CONTRACT.CONTRACTNO_NEW = C.CONTRACTNO_NEW

END

UPDATE #CONTRACT SET REMARK_DET = REMARK_DET + CASE WHEN  LEFT(BFCF_FLAG, 2)  ='BF' THEN ' B/fwd' ELSE '' END
WHERE SEGMENT ='FUTURES'

UPDATE #CONTRACT SET REMARK = REMARK + CASE WHEN  LEFT(BFCF_FLAG, 2) = 'BF' THEN ' - B/fwd' ELSE '' END
WHERE SEGMENT ='FUTURES'

/*
UPDATE	#CONTRACT SET NETOBLIGATION = ISNULL(A.NETOBLIGATION,0)
FROM	( 
		SELECT  SAUDA_DATE,
				EXCHANGE,
				SEGMENT,
				CONTRACTNO_NEW,
				NETOBLIGATION = MAX(NETOBLIGATION)
		FROM	#CONTRACT
		WHERE	NETOBLIGATION <> 0
		GROUP BY
				SAUDA_DATE,
				EXCHANGE,
				SEGMENT,
				CONTRACTNO_NEW 
		) A
WHERE	#CONTRACT.SAUDA_DATE = A.SAUDA_DATE
		AND #CONTRACT.EXCHANGE = A.EXCHANGE
		AND #CONTRACT.SEGMENT = A.SEGMENT
		AND #CONTRACT.CONTRACTNO_NEW = A.CONTRACTNO_NEW
*/		

SELECT PARTY_CODE,
	SAUDA_DATE,
	EXCHANGE,
	SEGMENT,
	CONTRACTNO_NEW,
	SETT_NO,
	--SETT_TYPE,
	SERVICE_TAX = SUM(SERVICE_TAX),
	INS_CHRG = SUM(INS_CHRG),
	IPFT_CHRG= SUM(IPFT_CHRG),
	NETAMOUNT = SUM(CASE WHEN SETT_TYPE IN ('OB','DL','TK','BX') THEN -BROKERAGE ELSE NETAMOUNT END),
	SEBI_TAX = SUM(SEBI_TAX),
	TURN_TAX = SUM(TURN_TAX),
	BROKER_CHRG = SUM(BROKER_CHRG),
	OTHER_CHRG = SUM(OTHER_CHRG),
	NETOBLIGATION = MAX(NETOBLIGATION),
	TOTBROKERAGE = SUM(CASE WHEN SETT_TYPE IN ('OB','DL','TK','BX') THEN BROKERAGE ELSE 0 END)
INTO #CONTRACT1
FROM #CONTRACT
GROUP BY PARTY_CODE,
	SAUDA_DATE,
	EXCHANGE,
	SEGMENT,
	CONTRACTNO_NEW,
	SETT_NO--,
	--SETT_TYPE

UPDATE #CONTRACT
--SET NETAMOUNTEX = (CASE WHEN C1.SEGMENT = 'FUTURES' THEN (CASE WHEN C1.NETOBLIGATION=0 THEN  C1.NETAMOUNT ELSE C1.NETOBLIGATION  END) ELSE C1.NETAMOUNT END),
SET NETAMOUNTEX = (
	CASE 
		WHEN C1.SEGMENT = 'FUTURES' THEN C1.NETAMOUNT
		--CASE WHEN C1.NETOBLIGATION <> 0 THEN C1.NETOBLIGATION ELSE C1.NETAMOUNT END
		ELSE C1.NETAMOUNT
	END),
	SEBI_TAXEX = C1.SEBI_TAX,
	TURN_TAXEX = C1.TURN_TAX,
	BROKER_CHRGEX = C1.BROKER_CHRG,
	OTHER_CHRGEX = C1.OTHER_CHRG,
	INS_CHRGEX = C1.INS_CHRG,
	IPFT_CHRGEX= ISNULL(C1.IPFT_CHRG,0),
	SERVICE_TAXEX = C1.SERVICE_TAX
FROM #CONTRACT C(NOLOCK),
	#CONTRACT1 C1(NOLOCK)
WHERE C.PARTY_CODE = C1.PARTY_CODE
	AND C.SAUDA_DATE = C1.SAUDA_DATE
	AND C.EXCHANGE = C1.EXCHANGE
	AND C.SEGMENT = C1.SEGMENT
	AND C.CONTRACTNO_NEW = C1.CONTRACTNO_NEW
	AND C.SETT_NO = C1.SETT_NO
	--AND C.SETT_TYPE = C1.SETT_TYPE

--### START GST CHANGES ###---

ALTER TABLE #CONTRACT
ADD	CGST_TAXEX NUMERIC(18, 6)

ALTER TABLE #CONTRACT
ADD	SGST_TAXEX NUMERIC(18, 6)

ALTER TABLE #CONTRACT
ADD	IGST_TAXEX NUMERIC(18, 6)

ALTER TABLE #CONTRACT
ADD	UGST_TAXEX NUMERIC(18, 6)

ALTER TABLE #CONTRACT
ADD	CGST NUMERIC(18, 6)

ALTER TABLE #CONTRACT
ADD	SGST NUMERIC(18, 6)

ALTER TABLE #CONTRACT
ADD	IGST NUMERIC(18, 6)

ALTER TABLE #CONTRACT
ADD	UGST NUMERIC(18, 6)

ALTER TABLE #CONTRACT
ADD	CLGSTNO VARCHAR(30)

ALTER TABLE #CONTRACT
ADD	GSTFLAG INT DEFAULT(0)

ALTER TABLE #CONTRACT
ADD	CGST_PER NUMERIC(18, 2)

ALTER TABLE #CONTRACT
ADD	SGST_PER NUMERIC(18, 2)

ALTER TABLE #CONTRACT
ADD	IGST_PER NUMERIC(18, 2)

ALTER TABLE #CONTRACT
ADD	UGST_PER NUMERIC(18, 2)

ALTER TABLE #CONTRACT
ADD	TARGETSTATE VARCHAR(30) 

ALTER TABLE #CONTRACT
ADD	SOURCESTATE VARCHAR(30) 

ALTER TABLE #CONTRACT
ADD	STATE_CODE VARCHAR(30) 

ALTER TABLE #CONTRACT
ADD	DEAL_CLIENT_ADD VARCHAR(MAX)

ALTER TABLE #CONTRACT
ADD	TGST_NO VARCHAR(30)

ALTER TABLE #CONTRACT
ADD	TPAN_NO VARCHAR(30)

ALTER TABLE #CONTRACT
ADD	TDESC_SERVICE VARCHAR(100)

ALTER TABLE #CONTRACT
ADD	TACC_SERVICE_NO VARCHAR(50)

ALTER TABLE #CONTRACT
ADD	TAXABLE_VALUE NUMERIC(18,4)

ALTER TABLE #CONTRACT
ADD	BROKERAGE_TAXEX NUMERIC(18,4)

ALTER TABLE #CONTRACT
ADD FOOTER_TAXABLE_TEXT VARCHAR(1000)

/* --- KFC --- */

ALTER TABLE #CONTRACT
ADD	KCESS_PER NUMERIC(18, 2)

ALTER TABLE #CONTRACT
ADD	KCESS NUMERIC(18, 6)

ALTER TABLE #CONTRACT
ADD	KCESS_TAXEX NUMERIC(18, 4)

/* --- KFC --- */


UPDATE #CONTRACT SET
	CGST_TAXEX = 0,
	SGST_TAXEX = 0,
	IGST_TAXEX = 0,
	UGST_TAXEX = 0,
	CGST = 0,
	SGST = 0,
	IGST = 0,
	UGST = 0,
	CLGSTNO = '',
	GSTFLAG = 0,
	CGST_PER = 0,
	SGST_PER = 0,
	IGST_PER = 0,
	UGST_PER = 0,
	TARGETSTATE = '',
	SOURCESTATE = '',
	STATE_CODE = '',
	DEAL_CLIENT_ADD = '',
	TGST_NO = '',
	TPAN_NO = '',
	TDESC_SERVICE = '',
	TACC_SERVICE_NO = '',
	TAXABLE_VALUE = 0,
	BROKERAGE_TAXEX = 0,
	FOOTER_TAXABLE_TEXT = ''
	
/* --- KFC --- */

	,KCESS_PER = 0, 
	KCESS=0, 
	KCESS_TAXEX=0

/* --- KFC --- */


SELECT G.PARTY_CODE, TARGETSTATE=G.L_STATE, SOURCESTATE=STATE,
GST_PER =CONVERT(NUMERIC(18,4),0),
CGST_PER=CONVERT(NUMERIC(18,4),0),
IGST_PER=CONVERT(NUMERIC(18,4),0),
SGST_PER=CONVERT(NUMERIC(18,4),0),
UGST_PER=CONVERT(NUMERIC(18,4),0),
P.SAUDA_DATE,
STATE_CODE = CONVERT(VARCHAR(20),''),	
DEAL_CLIENT_ADD = L.ADDRESS1 +' '+ L.ADDRESS2 +' '+ L.CITY +' '+ L.ZIP,
TGST_NO = L.GST_NO
INTO #GSTDATA
FROM TBL_CLIENT_GST_DATA G, TBL_GST_LOCATION L, #CONTRACT P
WHERE GST_LOCATION = LOC_CODE
AND CONVERT(DATETIME,SAUDA_DATE,103) BETWEEN G.EFF_FROM_DATE AND G.EFF_TO_DATE 
AND G.PARTY_CODE = P.PARTY_CODE

INSERT INTO #GSTDATA
SELECT P.PARTY_CODE, TARGETSTATE=L_STATE, SOURCESTATE=L_STATE,
GST_PER =CONVERT(NUMERIC(18,4),0),
CGST_PER=CONVERT(NUMERIC(18,4),0),
IGST_PER=CONVERT(NUMERIC(18,4),0),
SGST_PER=CONVERT(NUMERIC(18,4),0),
UGST_PER=CONVERT(NUMERIC(18,4),0),
P.SAUDA_DATE,
STATE_CODE = '',
DEAL_CLIENT_ADD = '',
P.TGST_NO
FROM #CONTRACT P, OWNER 
WHERE NOT EXISTS (SELECT PARTY_CODE FROM #GSTDATA G
WHERE P.PARTY_CODE = G.PARTY_CODE
AND P.SAUDA_DATE = G.SAUDA_DATE)

UPDATE #GSTDATA SET 
TARGETSTATE = SOURCESTATE 
WHERE TARGETSTATE NOT IN (SELECT STATE FROM STATE_MASTER WHERE STATE <> 'OTHER')

UPDATE #GSTDATA SET 
GST_PER = D.GST_PER, 
CGST_PER=(CASE WHEN SOURCESTATE = TARGETSTATE THEN D.CGST_PER ELSE 0 END),
IGST_PER=(CASE WHEN SOURCESTATE <> TARGETSTATE THEN D.IGST_PER ELSE 0 END),
SGST_PER=(CASE WHEN SOURCESTATE = TARGETSTATE AND UTI_FLAG = 0 THEN D.SGST_PER ELSE 0 END),
UGST_PER=(CASE WHEN SOURCESTATE = TARGETSTATE AND UTI_FLAG = 1 THEN D.UGST_PER ELSE 0 END),
STATE_CODE = ISNULL(D.STATE_CODE,'')
FROM TBL_STATE_GST_DATA D
WHERE D.STATE_NAME = SOURCESTATE
AND CONVERT(DATETIME,SAUDA_DATE,103) BETWEEN EFF_FROM_DATE AND EFF_TO_DATE

/* --- KFC --- */
/*
ALTER TABLE #GSTDATA
ADD KCESS_PER NUMERIC(18,4)

UPDATE #GSTDATA SET SGST_PER = G.SGST_PER + CESSTAX , GST_PER = G.GST_PER + CESSTAX, KCESS_PER = CESSTAX
FROM TBL_CLIENT_GST_DATA C, TBL_STATE_GST_DATA G, TBL_GST_LOCATION L
WHERE #GSTDATA.Party_Code = C.PARTY_CODE
AND CONVERT(DATETIME,SAUDA_DATE,103) BETWEEN C.EFF_FROM_DATE AND C.EFF_TO_DATE 
AND CONVERT(DATETIME,SAUDA_DATE,103) BETWEEN G.EFF_FROM_DATE AND G.EFF_TO_DATE
AND C.L_STATE = G.STATE_NAME
AND C.GST_LOCATION = L.LOC_CODE 
AND L.STATE = G.STATE_NAME
AND C.GST_NO = ''
AND CESSTAX > 0 
*/
/* --- KFC --- */


UPDATE #CONTRACT SET 
	CGST_PER = G.CGST_PER,
	IGST_PER = G.IGST_PER,
	SGST_PER = G.SGST_PER,
	UGST_PER = G.UGST_PER,
	CGST_TAXEX = SERVICE_TAXEX * G.CGST_PER / G.GST_PER,
	SGST_TAXEX = SERVICE_TAXEX * G.SGST_PER / G.GST_PER,
	IGST_TAXEX = SERVICE_TAXEX * G.IGST_PER / G.GST_PER,
	UGST_TAXEX = SERVICE_TAXEX * G.UGST_PER / G.GST_PER,
	CGST = SERVICE_TAX * G.CGST_PER / G.GST_PER,
	SGST = SERVICE_TAX * G.SGST_PER / G.GST_PER,
	IGST = SERVICE_TAX * G.IGST_PER / G.GST_PER,
	UGST = SERVICE_TAX * G.UGST_PER / G.GST_PER,
	GSTFLAG = 1,
	TARGETSTATE = G.TARGETSTATE,
	SOURCESTATE = G.SOURCESTATE,
	STATE_CODE	= G.STATE_CODE,
	DEAL_CLIENT_ADD = G.DEAL_CLIENT_ADD,
	TGST_NO = G.TGST_NO/*,
	KCESS_PER = G.KCESS_PER*/
FROM #GSTDATA G
WHERE #CONTRACT.PARTY_CODE = G.PARTY_CODE
	AND #CONTRACT.SAUDA_DATE = G.SAUDA_DATE
	AND G.GST_PER > 0	
	

UPDATE	#CONTRACT
SET		L_ADDRESS1	= ISNULL(G.L_ADDRESS1,''),
		L_ADDRESS2	= ISNULL(G.L_ADDRESS2,''),
		L_ADDRESS3	= ISNULL(G.L_ADDRESS3,''),
		L_STATE		= ISNULL(G.L_STATE,''),
		L_CITY		= ISNULL(G.L_CITY,''),
		L_ZIP		= ISNULL(G.L_ZIP,''),
		CLGSTNO		= ISNULL(G.GST_NO,'')
FROM	TBL_CLIENT_GST_DATA G (NOLOCK)
WHERE	G.PARTY_CODE = #CONTRACT.PARTY_CODE
		AND CONVERT(DATETIME,SAUDA_DATE,103) BETWEEN G.EFF_FROM_DATE AND G.EFF_TO_DATE 


UPDATE #CONTRACT SET SGST_TAXEX = SERVICE_TAXEX - CGST_TAXEX - IGST_TAXEX - UGST_TAXEX,
SGST = SERVICE_TAX - CGST - IGST - UGST
WHERE  SGST_TAXEX > 0 

UPDATE #CONTRACT SET UGST_TAXEX = SERVICE_TAXEX - CGST_TAXEX - IGST_TAXEX - SGST_TAXEX,
UGST = SERVICE_TAX - CGST - IGST - SGST
WHERE  UGST_TAXEX > 0 


/* --- KFC --- */
/*
UPDATE	#CONTRACT 
SET 	KCESS		= (SGST*KCESS_PER/SGST_PER),
		KCESS_TAXEX = SGST_TAXEX*KCESS_PER/SGST_PER
WHERE	KCESS_PER > 0


UPDATE	#CONTRACT 
SET 	SGST_TAXEX	= SGST_TAXEX - KCESS_TAXEX,
		SGST		= SGST - KCESS,
		SGST_PER	= SGST_PER - KCESS_PER
WHERE	KCESS_PER > 0
*/
/* --- KFC --- */


UPDATE	#CONTRACT 
SET		TPAN_NO = ISNULL(PANNO,''),
		TDESC_SERVICE = ISNULL(SERVICE_DESCRIPTION,''),
		TACC_SERVICE_NO = ISNULL(ACCOUNT_SERVICE_NO,'')
FROM	OWNER (NOLOCK)


UPDATE	#CONTRACT
SET		BROKERAGE_TAXEX = ISNULL(C.BROKERAGE,0)
FROM	(SELECT 
			PARTY_CODE,SAUDA_DATE,EXCHANGE,SEGMENT,CONTRACTNO_NEW,SETT_NO,--SETT_TYPE,
			BROKERAGE = SUM(BROKERAGE)
		FROM #CONTRACT
		GROUP BY 
			PARTY_CODE,SAUDA_DATE,EXCHANGE,SEGMENT,CONTRACTNO_NEW,SETT_NO--,SETT_TYPE
		) C
WHERE	C.PARTY_CODE = #CONTRACT.PARTY_CODE
		AND C.SAUDA_DATE = #CONTRACT.SAUDA_DATE
		AND C.EXCHANGE = #CONTRACT.EXCHANGE
		AND C.SEGMENT = #CONTRACT.SEGMENT
		AND C.CONTRACTNO_NEW = #CONTRACT.CONTRACTNO_NEW	
		AND C.SETT_NO = #CONTRACT.SETT_NO	
		--AND C.SETT_TYPE = #CONTRACT.SETT_TYPE


UPDATE	#CONTRACT 
SET		FOOTER_TAXABLE_TEXT = (
		CASE
			WHEN ISNULL(G.TURNOVER_AC,0) = 1 THEN 'Transaction charges '
			ELSE ''
		END) + (
		CASE
			WHEN ISNULL(G.SEBI_TURN_AC,0) = 1 THEN 
			CASE WHEN ISNULL(G.TURNOVER_AC,0) = 1 THEN 'and Sebi Turnover fee' ELSE 'Sebi Turnover fee' END
			ELSE ''
		END),
		TAXABLE_VALUE = BROKERAGE_TAXEX + (
		CASE
			WHEN ISNULL(G.TURNOVER_AC,0) = 1 THEN TURN_TAXEX 
			ELSE 0
		END) + (
		CASE
			WHEN ISNULL(G.SEBI_TURN_AC,0) = 1 THEN SEBI_TAXEX
			ELSE 0
		END) + (
		CASE
			WHEN ISNULL(G.BROKER_NOTE_AC,0) = 1 THEN BROKER_CHRGEX
			ELSE 0
		END) + (
		CASE
			WHEN ISNULL(G.OTHER_CHRG_AC,0) = 1 THEN OTHER_CHRGEX
			ELSE 0
		END) + (
		CASE
			WHEN ISNULL(G.STT_TAX_AC,0) = 1 THEN INS_CHRGEX
			ELSE 0
		END)
FROM	GLOBALS G (NOLOCK)
WHERE	CONVERT(DATETIME,SAUDA_DATE,103) BETWEEN YEAR_START_DT AND YEAR_END_DT
		---AND #CONTRACT.EXCHANGE IN ('NSE','BSE') AND #CONTRACT.SEGMENT = 'CAPITAL'


UPDATE	#CONTRACT 
SET		TAXABLE_VALUE = BROKERAGE_TAXEX + (
		CASE
			WHEN ISNULL(G.TURNOVER_AC,0) = 1 THEN TURN_TAXEX 
			ELSE 0
		END) + (
		CASE
			WHEN ISNULL(G.SEBI_TURN_AC,0) = 1 THEN SEBI_TAXEX
			ELSE 0
		END) + (
		CASE
			WHEN ISNULL(G.BROKER_NOTE_AC,0) = 1 THEN BROKER_CHRGEX
			ELSE 0
		END) + (
		CASE
			WHEN ISNULL(G.OTHER_CHRG_AC,0) = 1 THEN OTHER_CHRGEX
			ELSE 0
		END) + (
		CASE
			WHEN ISNULL(G.INSURANCE_CHRG_AC,0) = 1 THEN INS_CHRGEX
			ELSE 0
		END)
FROM	NSEFO.DBO.FOGLOBALS G (NOLOCK)
WHERE	CONVERT(DATETIME,SAUDA_DATE,103) BETWEEN YEAR_START_DT AND YEAR_END_DT
		AND #CONTRACT.EXCHANGE_OLD IN ('NSE') AND #CONTRACT.SEGMENT = 'FUTURES'

/*

UPDATE	#CONTRACT 
SET		TAXABLE_VALUE = BROKERAGE_TAXEX + (
		CASE
			WHEN ISNULL(G.TURNOVER_AC,0) = 1 THEN TURN_TAXEX 
			ELSE 0
		END) + (
		CASE
			WHEN ISNULL(G.SEBI_TURN_AC,0) = 1 THEN SEBI_TAXEX
			ELSE 0
		END) + (
		CASE
			WHEN ISNULL(G.BROKER_NOTE_AC,0) = 1 THEN BROKER_CHRGEX
			ELSE 0
		END) + (
		CASE
			WHEN ISNULL(G.OTHER_CHRG_AC,0) = 1 THEN OTHER_CHRGEX
			ELSE 0
		END) + (
		CASE
			WHEN ISNULL(G.INSURANCE_CHRG_AC,0) = 1 THEN INS_CHRGEX
			ELSE 0
		END)
FROM	NSECURFO.DBO.FOGLOBALS G (NOLOCK)
WHERE	CONVERT(DATETIME,SAUDA_DATE,103) BETWEEN YEAR_START_DT AND YEAR_END_DT
		AND #CONTRACT.EXCHANGE_OLD IN ('NSX') AND #CONTRACT.SEGMENT = 'FUTURES'
		*/

--### END GST CHANGES ###---




--### START CROSS CURRENCY CHANGES ###---

	DECLARE @EXCHANGE_NEW VARCHAR(10)
	DECLARE @SEGMENT_NEW VARCHAR(10)
	DECLARE @SHAREDB VARCHAR(35)
	DECLARE @SHARESERVER VARCHAR(35)
	DECLARE @EXCHANGEWISE_CURSOR CURSOR 
	DECLARE @STRSQL VARCHAR(8000) 

	ALTER	TABLE #CONTRACT
	ADD		FOREIGN_PRICE  NUMERIC(18,4)

	UPDATE	#CONTRACT 
	SET		FOREIGN_PRICE = 0


	SET @EXCHANGEWISE_CURSOR = CURSOR
	FOR
	SELECT	DISTINCT 
			EXCHANGE,
			SHAREDB,
			SHARESERVER
	FROM	#EXCHANGELIST M(NOLOCK)
	WHERE	EXCHANGE IN ('NSXFUTURES','BSXFUTURES','MCDFUTURES')
		
	OPEN @EXCHANGEWISE_CURSOR

	FETCH NEXT
	FROM @EXCHANGEWISE_CURSOR
	INTO
		@EXCHANGE_NEW,
		@SHAREDB,
		@SHARESERVER

	WHILE @@FETCH_STATUS = 0
	BEGIN
		SET @STRSQL = ''
		IF @SHARESERVER = @@SERVERNAME 
		BEGIN
			SET @SHARESERVER = ''
		END
		ELSE
		BEGIN
			SET @SHARESERVER = @SHARESERVER + '.'
		END
		
		BEGIN

			IF (@EXCHANGE_NEW = 'NSXFUTURES')
			BEGIN
				SET @STRSQL = 'IF (SELECT COUNT(1) FROM ' + @SHARESERVER + @SHAREDB + '.SYS.TABLES WHERE NAME=''TBL_RBI_RATE'') > 0 '
				SET @STRSQL = @STRSQL + 'BEGIN '
				SET @STRSQL = @STRSQL + 'UPDATE	#CONTRACT '
				SET @STRSQL = @STRSQL + 'SET	FOREIGN_PRICE = (CASE WHEN LEFT(BFCF_FLAG, 2) = ''BT'' THEN #CONTRACT.MARKETRATE/ISNULL(T.RBI_REFERENCE_RATE,1) ELSE ISNULL(T.CROSS_CURRENCY_PRICE,0) END) '
				SET @STRSQL = @STRSQL + 'FROM	' + @SHARESERVER + @SHAREDB + '.DBO.TBL_RBI_RATE T '
				SET @STRSQL = @STRSQL + 'WHERE	LEFT(T.TRADE_DATE,11) = LEFT(CONVERT(DATETIME,#CONTRACT.SAUDA_DATE,103),11) '
				SET @STRSQL = @STRSQL + '		AND #CONTRACT.SCRIPNAME = RTRIM(T.INST_TYPE) + '' '' + RTRIM(T.SYMBOL) + '' '' + UPPER(REPLACE(CONVERT(VARCHAR,T.EXPIRY_DATE,6),'' '','''')) '
				SET @STRSQL = @STRSQL + '		AND #CONTRACT.EXCHANGE_OLD IN (''NSX'') '
				SET @STRSQL = @STRSQL + '		AND #CONTRACT.EXCHANGE_OLD+#CONTRACT.SEGMENT = ''' + @EXCHANGE_NEW +''' '
				SET @STRSQL = @STRSQL + ' END '
				PRINT @STRSQL
				EXEC (@STRSQL)
			END
			ELSE IF (@EXCHANGE_NEW = 'BSXFUTURES')
			BEGIN
				SET @STRSQL = @STRSQL + 'UPDATE	#CONTRACT '
				SET @STRSQL = @STRSQL + 'SET	FOREIGN_PRICE = (CASE WHEN LEFT(BFCF_FLAG, 2) = ''BT'' THEN #CONTRACT.MARKETRATE/(CASE WHEN ISNULL(T.RESERVED,1) = 0 THEN 1 ELSE  ISNULL(T.RESERVED,1) END) ELSE ISNULL(T.CL_RATE,0) END) '
				SET @STRSQL = @STRSQL + 'FROM	' + @SHARESERVER + @SHAREDB + '.DBO.FOCLOSING T '
				SET @STRSQL = @STRSQL + 'WHERE	LEFT(T.TRADE_DATE,11) = LEFT(CONVERT(DATETIME,#CONTRACT.SAUDA_DATE,103),11) '
				SET @STRSQL = @STRSQL + '		AND #CONTRACT.SCRIPNAME = (CASE '
				SET @STRSQL = @STRSQL + '			WHEN LEFT(T.INST_TYPE,3) = ''FUT'' THEN RTRIM(T.INST_TYPE) + '' '' + RTRIM(T.SYMBOL) + '' '' + UPPER(REPLACE(CONVERT(VARCHAR,T.EXPIRYDATE,6),'' '','''')) '
				SET @STRSQL = @STRSQL + '			ELSE RTRIM(T.INST_TYPE) + '' '' + RTRIM(T.SYMBOL) + '' '' + UPPER(REPLACE(CONVERT(VARCHAR,T.EXPIRYDATE,6),'' '','''')) + '' '' + CONVERT(VARCHAR,T.STRIKE_PRICE) + '' '' + RTRIM(T.OPTION_TYPE) '
				SET @STRSQL = @STRSQL + '			END) '				
				SET @STRSQL = @STRSQL + '		AND #CONTRACT.EXCHANGE_OLD IN (''BSX'') '
				SET @STRSQL = @STRSQL + '		AND #CONTRACT.EXCHANGE_OLD+#CONTRACT.SEGMENT = ''' + @EXCHANGE_NEW +''' '
				PRINT @STRSQL
				EXEC (@STRSQL)
			END
				
		END
		
		FETCH NEXT
		FROM @EXCHANGEWISE_CURSOR
		INTO 
			@EXCHANGE_NEW,
			@SHAREDB,
			@SHARESERVER
	END

	CLOSE @EXCHANGEWISE_CURSOR

	DEALLOCATE @EXCHANGEWISE_CURSOR

--### END CROSS CURRENCY CHANGES ###---


UPDATE #CONTRACT
--SET SCRIPNAME_NEW = SCRIPNAME + (CASE WHEN REMARK_ID <> '' THEN ' (' + REMARK_ID + ')' ELSE '' END)
SET SCRIPNAME_NEW = SCRIPNAME


DECLARE @SEBIREGNO VARCHAR(1000)
DECLARE @BR_CMDPID  VARCHAR(1000)
DECLARE @BSEBR_CMDPID  VARCHAR(1000)

--### START EXCHANGE/DEPOSITORY LISTING SCRIP ###---
DECLARE @EXCHANGE_SCRIP VARCHAR(100),
		@DEPOSITORY_SCRIP VARCHAR(100)
		
SELECT @EXCHANGE_SCRIP = EXCHANGE_LISTING_CODE, @DEPOSITORY_SCRIP = DEPOSITORY_LISTING_CODE FROM OWNER (NOLOCK)
--### END EXCHANGE/DEPOSITORY LISTING SCRIP ###---

IF @EXCHANGE = ''
BEGIN
	SELECT @SEBIREGNO = 'SEBI Registration No.:' + COMMONSEBINO FROM OWNER (NOLOCK)
	
	SELECT @BR_CMDPID = 'NSE Capital Market Depository :' + BR_CMDPID FROM OWNER (NOLOCK) --WHERE 1 = CASE WHEN @INTEROP = 'NSCCL' THEN 1 ELSE 2 END
	SELECT @BSEBR_CMDPID = 'BSE Capital Market Depository :' + BR_CMDPID FROM BSEDB..OWNER (NOLOCK) -- WHERE 1 = CASE WHEN @INTEROP = 'ICCL' THEN 1 ELSE 2 END
END

IF @EXCHANGE = 'NSECAPITAL'
BEGIN
	SELECT @SEBIREGNO = 'SEBI Registration No.: ' + brokersebiregno FROM OWNER (NOLOCK)
	SELECT @BR_CMDPID = 'Capital Market Depository :' + BR_CMDPID FROM OWNER (NOLOCK)
END

IF @EXCHANGE = 'BSECAPITAL'
BEGIN
	SELECT @SEBIREGNO = 'SEBI Registration No.: ' + brokersebiregno FROM BSEDB..OWNER (NOLOCK)
	SELECT @BR_CMDPID = 'Capital Market Depository :' + BR_CMDPID FROM BSEDB..OWNER (NOLOCK)
END

IF (SELECT COUNT(1) FROM SYS.DATABASES WHERE NAME = 'NSEFO') > 0
BEGIN
	IF @EXCHANGE = 'NSEFUTURES'
	BEGIN
		SELECT @SEBIREGNO = 'SEBI Registration No.: ' + brokersebiregno FROM NSEFO..FOOWNER (NOLOCK)
		SET @BR_CMDPID =''
	END
END

IF (SELECT COUNT(1) FROM SYS.DATABASES WHERE NAME = 'NSECURFO') > 0
BEGIN
	IF @EXCHANGE = 'NSXFUTURES'
	BEGIN
		SELECT @SEBIREGNO = 'SEBI Registration No.: NSX FUTURES:' + brokersebiregno FROM NSECURFO..FOOWNER (NOLOCK)
		SET @BR_CMDPID =''
	END
END


UPDATE	#CONTRACT
SET		SETTLEMENT_DET = (
		CASE 
			WHEN @INTEROP = 'NSCCL'		THEN REPLACE(SETTLEMENT_DET,'NSE-Capital Market','NCL-Capital Market')
			WHEN @INTEROP = 'ICCL'		THEN REPLACE(SETTLEMENT_DET,'BSE-Capital Market','ICCL-Capital Market')
			ELSE SETTLEMENT_DET
		END),
		CONTRACTNO_DET = (
		CASE 
			WHEN @INTEROP = 'NSCCL' THEN REPLACE(CONTRACTNO_DET,'NSE-CAPITAL','NCL-CAPITAL')
			WHEN @INTEROP = 'ICCL' THEN REPLACE(CONTRACTNO_DET,'BSE-CAPITAL','ICCL-CAPITAL')
			ELSE CONTRACTNO_DET
		END),
		BROKERSEBIREGNO_DET = (
		CASE 
			WHEN @INTEROP = 'NSCCL' THEN REPLACE(BROKERSEBIREGNO_DET,'NSE CAPITAL','NCL CAPITAL')
			WHEN @INTEROP = 'ICCL' THEN REPLACE(BROKERSEBIREGNO_DET,'BSE CAPITAL','ICCL CAPITAL')
			ELSE BROKERSEBIREGNO_DET
		END),
		MEMBERCODE_DET = (
		CASE 
			WHEN @INTEROP = 'NSCCL' THEN REPLACE(MEMBERCODE_DET,'NSE CAPITAL','NCL CAPITAL')
			WHEN @INTEROP = 'ICCL' THEN REPLACE(MEMBERCODE_DET,'BSE CAPITAL','ICCL CAPITAL')
			ELSE MEMBERCODE_DET
		END),	
		CIN_DET = (
		CASE 
			WHEN @INTEROP = 'NSCCL' THEN REPLACE(CIN_DET,'NSE CAPITAL','NCL CAPITAL')
			WHEN @INTEROP = 'ICCL' THEN REPLACE(CIN_DET,'BSE CAPITAL','ICCL CAPITAL')
			ELSE CIN_DET
		END)
WHERE	INTEROPCODE <> '' AND @INTEROP <> ''

UPDATE	#CONTRACT
SET		SETTLEMENT_DET = (
		CASE 
			WHEN @INTEROPFNO = 'NSCCL'	THEN REPLACE(SETTLEMENT_DET,'NSE-Derivatives','NCL-Derivatives')
			WHEN @INTEROPFNO = 'ICCL'	THEN REPLACE(SETTLEMENT_DET,'BSE-Derivatives','ICCL-Derivatives')
			ELSE SETTLEMENT_DET
		END),
		CONTRACTNO_DET = (
		CASE 
			WHEN @INTEROPFNO = 'NSCCL' THEN REPLACE(CONTRACTNO_DET,'NSE-FUTURES','NCL-FUTURES')
			WHEN @INTEROPFNO = 'ICCL' THEN REPLACE(CONTRACTNO_DET,'BSE-FUTURES','ICCL-FUTURES')
			ELSE CONTRACTNO_DET
		END),
		BROKERSEBIREGNO_DET = (
		CASE 
			WHEN @INTEROPFNO = 'NSCCL' THEN REPLACE(BROKERSEBIREGNO_DET,'NSE FUTURES','NCL FUTURES')
			WHEN @INTEROPFNO = 'ICCL' THEN REPLACE(BROKERSEBIREGNO_DET,'BSE FUTURES','ICCL FUTURES')
			ELSE BROKERSEBIREGNO_DET
		END),
		MEMBERCODE_DET = (
		CASE 
			WHEN @INTEROPFNO = 'NSCCL' THEN REPLACE(MEMBERCODE_DET,'NSE FUTURES','NCL FUTURES')
			WHEN @INTEROPFNO = 'ICCL' THEN REPLACE(MEMBERCODE_DET,'BSE FUTURES','ICCL FUTURES')
			ELSE MEMBERCODE_DET
		END),
		CIN_DET = (
		CASE 
			WHEN @INTEROPFNO = 'NSCCL' THEN REPLACE(CIN_DET,'NSE FUTURES','NCL FUTURES')
			WHEN @INTEROPFNO = 'ICCL' THEN REPLACE(CIN_DET,'BSE FUTURES','ICCL FUTURES')
			ELSE CIN_DET
		END)
WHERE	INTEROPCODE <> '' AND @INTEROPFNO <> ''

UPDATE	#CONTRACT
SET		SETTLEMENT_DET = (
		CASE 
			WHEN @INTEROPCUR = 'NSCCL'	THEN REPLACE(SETTLEMENT_DET,'NSE-Currency Derivatives','NCL-Currency Derivatives')
			WHEN @INTEROPCUR = 'ICCL'	THEN REPLACE(SETTLEMENT_DET,'BSX-Currency Derivatives','ICCL-Currency Derivatives')
			ELSE SETTLEMENT_DET
		END),
		CONTRACTNO_DET = (
		CASE 
			WHEN @INTEROPCUR = 'NSCCL' THEN REPLACE(CONTRACTNO_DET,'NSX-FUTURES','NCL-FUTURES')
			WHEN @INTEROPCUR = 'ICCL' THEN REPLACE(CONTRACTNO_DET,'BSX-FUTURES','ICCL-FUTURES')
			ELSE CONTRACTNO_DET
		END),
		BROKERSEBIREGNO_DET = (
		CASE 
			WHEN @INTEROPCUR = 'NSCCL' THEN REPLACE(BROKERSEBIREGNO_DET,'NSX FUTURES','NCL FUTURES')
			WHEN @INTEROPCUR = 'ICCL' THEN REPLACE(BROKERSEBIREGNO_DET,'BSX FUTURES','ICCL FUTURES')
			ELSE BROKERSEBIREGNO_DET
		END),
		MEMBERCODE_DET = (
		CASE 
			WHEN @INTEROPCUR = 'NSCCL' THEN REPLACE(MEMBERCODE_DET,'NSX FUTURES','NCL FUTURES')
			WHEN @INTEROPCUR = 'ICCL' THEN REPLACE(MEMBERCODE_DET,'BSX FUTURES','ICCL FUTURES')
			ELSE MEMBERCODE_DET
		END),
		CIN_DET = (
		CASE 
			WHEN @INTEROPCUR = 'NSCCL' THEN REPLACE(CIN_DET,'NSX FUTURES','NCL FUTURES')
			WHEN @INTEROPCUR = 'ICCL' THEN REPLACE(CIN_DET,'BSX FUTURES','ICCL FUTURES')
			ELSE CIN_DET
		END)
WHERE	INTEROPCODE <> '' AND @INTEROPCUR <> ''

UPDATE #CONTRACT
SET SETTLEMENT_DET=REPLACE(REPLACE(REPLACE(SETTLEMENT_DET,'NSE','NCL'),'BSE','ICCL'),'BSX','ICCL')

/*
UPDATE	#CONTRACT
SET		SETTLEMENT_DET = (
		CASE 
			WHEN @INTEROP = 'NSCCL' THEN REPLACE(SETTLEMENT_DET,'NSE-Capital Market','NCL-Capital Market')
			WHEN @INTEROP = 'ICCL'	THEN REPLACE(SETTLEMENT_DET,'BSE-Capital Market','ICCL-Capital Market')
			WHEN @INTEROPFNO = 'NSCCL' THEN REPLACE(SETTLEMENT_DET,'NSE-Derivatives','NCL-Derivatives')
			WHEN @INTEROPFNO = 'ICCL'	THEN REPLACE(SETTLEMENT_DET,'BSE-Derivatives','ICCL-Derivatives')
			WHEN @INTEROPCUR = 'NSCCL' THEN REPLACE(SETTLEMENT_DET,'NSE-Currency Derivatives','NCL-Currency Derivatives')
			WHEN @INTEROPCUR = 'ICCL'	THEN REPLACE(SETTLEMENT_DET,'BSX-Currency Derivatives','ICCL-Currency Derivatives')
			ELSE SETTLEMENT_DET
		END),
		CONTRACTNO_DET = (
		CASE 
			WHEN @INTEROP = 'NSCCL' THEN REPLACE(CONTRACTNO_DET,'NSE-CAPITAL','NCL-CAPITAL')
			WHEN @INTEROP = 'ICCL' THEN REPLACE(CONTRACTNO_DET,'BSE-CAPITAL','ICCL-CAPITAL')
			WHEN @INTEROPFNO = 'NSCCL' THEN REPLACE(CONTRACTNO_DET,'NSE-FUTURES','NCL-FUTURES')
			WHEN @INTEROPFNO = 'ICCL' THEN REPLACE(CONTRACTNO_DET,'BSE-FUTURES','ICCL-FUTURES')
			WHEN @INTEROPCUR = 'NSCCL' THEN REPLACE(CONTRACTNO_DET,'NSX-FUTURES','NCL-FUTURES')
			WHEN @INTEROPCUR = 'ICCL' THEN REPLACE(CONTRACTNO_DET,'BSX-FUTURES','ICCL-FUTURES')
			ELSE CONTRACTNO_DET
		END),
		BROKERSEBIREGNO_DET = (
		CASE 
			WHEN @INTEROP = 'NSCCL' THEN REPLACE(BROKERSEBIREGNO_DET,'NSE CAPITAL','NCL CAPITAL')
			WHEN @INTEROP = 'ICCL' THEN REPLACE(BROKERSEBIREGNO_DET,'BSE CAPITAL','ICCL CAPITAL')
			WHEN @INTEROPFNO = 'NSCCL' THEN REPLACE(BROKERSEBIREGNO_DET,'NSE FUTURES','NCL FUTURES')
			WHEN @INTEROPFNO = 'ICCL' THEN REPLACE(BROKERSEBIREGNO_DET,'BSE FUTURES','ICCL FUTURES')
			WHEN @INTEROPCUR = 'NSCCL' THEN REPLACE(BROKERSEBIREGNO_DET,'NSX FUTURES','NCL FUTURES')
			WHEN @INTEROPCUR = 'ICCL' THEN REPLACE(BROKERSEBIREGNO_DET,'BSX FUTURES','ICCL FUTURES')
			ELSE BROKERSEBIREGNO_DET
		END),			
		MEMBERCODE_DET = (
		CASE 
			WHEN @INTEROP = 'NSCCL' THEN REPLACE(MEMBERCODE_DET,'NSE CAPITAL','NCL CAPITAL')
			WHEN @INTEROP = 'ICCL' THEN REPLACE(MEMBERCODE_DET,'BSE CAPITAL','ICCL CAPITAL')
			WHEN @INTEROPFNO = 'NSCCL' THEN REPLACE(MEMBERCODE_DET,'NSE FUTURES','NCL FUTURES')
			WHEN @INTEROPFNO = 'ICCL' THEN REPLACE(MEMBERCODE_DET,'BSE FUTURES','ICCL FUTURES')
			WHEN @INTEROPCUR = 'NSCCL' THEN REPLACE(MEMBERCODE_DET,'NSX FUTURES','NCL FUTURES')
			WHEN @INTEROPCUR = 'ICCL' THEN REPLACE(MEMBERCODE_DET,'BSX FUTURES','ICCL FUTURES')
			ELSE MEMBERCODE_DET
		END),
		CIN_DET = (
		CASE 
			WHEN @INTEROP = 'NSCCL' THEN REPLACE(CIN_DET,'NSE CAPITAL','NCL CAPITAL')
			WHEN @INTEROP = 'ICCL' THEN REPLACE(CIN_DET,'BSE CAPITAL','ICCL CAPITAL')
			WHEN @INTEROPFNO = 'NSCCL' THEN REPLACE(CIN_DET,'NSE FUTURES','NCL FUTURES')
			WHEN @INTEROPFNO = 'ICCL' THEN REPLACE(CIN_DET,'BSE FUTURES','ICCL FUTURES')
			WHEN @INTEROPCUR = 'NSCCL' THEN REPLACE(CIN_DET,'NSX FUTURES','NCL FUTURES')
			WHEN @INTEROPCUR = 'ICCL' THEN REPLACE(CIN_DET,'BSX FUTURES','ICCL FUTURES')
			ELSE CIN_DET
		END)
*/



UPDATE	#CONTRACT
SET		EXCHANGE = (
		CASE 
			WHEN @INTEROP = 'NSCCL' THEN REPLACE(EXCHANGE,'NSE','NCL')
			WHEN @INTEROP = 'ICCL' THEN REPLACE(EXCHANGE,'BSE','ICCL')
			WHEN @INTEROPFNO = 'NSCCL' THEN REPLACE(EXCHANGE,'NSE','NCL')
			WHEN @INTEROPFNO = 'ICCL' THEN REPLACE(EXCHANGE,'BSE','ICCL')
			WHEN @INTEROPCUR = 'NSCCL' THEN REPLACE(EXCHANGE,'NSX','NCL')
			WHEN @INTEROPCUR = 'ICCL' THEN REPLACE(EXCHANGE,'BSX','ICCL')
			ELSE EXCHANGE
		END)		
WHERE	INTEROPCODE <> ''



ALTER	TABLE #CONTRACT
ADD		NRIACCNO VARCHAR(25),
		CL_STATUS VARCHAR(10)

UPDATE	#CONTRACT
SET		NRIACCNO = ISNULL(M.ACCNO,'')
FROM	ACCOUNT.dbo.MULTIBANKID M (NOLOCK)
WHERE	CLTCODE = PARTY_CODE
AND		DEFAULTBANK = 1

UPDATE	#CONTRACT
SET		CL_STATUS = ISNULL(C.CL_STATUS,'')
FROM	CLIENT_DETAILS C (NOLOCK)
WHERE	c.CL_CODE = #CONTRACT.PARTY_CODE


/*
----------Changes for Product Code---------

SELECT SAUDA_DATE,PARTY_CODE,EXCHANGE_OLD,SEGMENT_OLD,SCRIPNAME_NEW,PRODUCT_CODE,SERIES_CODE,B2.EXPIRYDATE,SCRIPNAME 
INTO   #BFOCONTRACT  
from   #CONTRACT LEFT OUTER JOIN BSEFO.DBO.BFOSCRIP2 B2 (NOLOCK)
ON     #CONTRACT.SCRIPNAME =  RTRIM(B2.PRODUCT_CODE) + ' ' + RTRIM(B2.SERIES_CODE) + ' ' + CONVERT(VARCHAR,B2.SERIES_ID,108)
WHERE  #CONTRACT.EXCHANGE_OLD+#CONTRACT.SEGMENT_OLD = 'BSEFUTURES'


UPDATE	#BFOCONTRACT
SET		SCRIPNAME_NEW = (
		CASE
				WHEN RIGHT(T.B_INST_TYPE,3) = 'FUT' THEN RTRIM(T.N_INST_TYPE) + ' ' + RTRIM(T.N_SYMBOL) + ' ' + UPPER(REPLACE(CONVERT(VARCHAR,T.N_EXPIRYDATE,6),' ','')) 
				ELSE RTRIM(T.N_INST_TYPE) + ' ' + RTRIM(T.N_SYMBOL) + ' ' + UPPER(REPLACE(CONVERT(VARCHAR,T.N_EXPIRYDATE,6),' ','')) + ' ' + CONVERT(VARCHAR,T.N_STRIKE_PRICE) + ' ' + RTRIM(T.N_OPTION_TYPE)
		END)
FROM	#BFOCONTRACT ,BSEFO.DBO.TBL_FOSCRIPMAP T (NOLOCK)
WHERE	#BFOCONTRACT.EXCHANGE_OLD+#BFOCONTRACT.SEGMENT_OLD = 'BSEFUTURES'
		AND CONVERT(DATETIME,#BFOCONTRACT.SAUDA_DATE,103) BETWEEN EFF_FROM AND EFF_TO
		AND RTRIM(#BFOCONTRACT.PRODUCT_CODE) = RTRIM(T.B_INST_TYPE) AND RTRIM(#BFOCONTRACT.SERIES_CODE) = RTRIM(T.B_SYMBOL)  AND RTRIM(#BFOCONTRACT.EXPIRYDATE) = RTRIM(T.EXPIRYDATE)

UPDATE	#CONTRACT
SET		SCRIPNAME_NEW=#BFOCONTRACT.SCRIPNAME_NEW
FROM	#BFOCONTRACT ,#CONTRACT
WHERE	#CONTRACT.EXCHANGE_OLD+#CONTRACT.SEGMENT_OLD = 'BSEFUTURES'
AND		#CONTRACT.PARTY_CODE=#BFOCONTRACT.PARTY_CODE
AND		CONVERT(DATETIME,#CONTRACT.SAUDA_DATE,103)=CONVERT(DATETIME,#BFOCONTRACT.SAUDA_DATE,103)
AND		#CONTRACT.SCRIPNAME=#BFOCONTRACT.SCRIPNAME
*/
----------Changes for Product Code-------


----------Changes for RE SCRIP-------

ALTER TABLE #CONTRACT
ADD	RE_SCRIP VARCHAR(5)

UPDATE	#CONTRACT SET RE_SCRIP = 'NO'

UPDATE	#CONTRACT
SET		RE_SCRIP = 'YES'
FROM	MULTIISIN M (NOLOCK)
WHERE	M.ISIN = #CONTRACT.ISIN
		AND SCRIP_CD LIKE '%-RE'

UPDATE	#CONTRACT
SET		RE_SCRIP = 'YES'
FROM	BSEDB..MULTIISIN M (NOLOCK),
		BSEDB..SCRIP2 S2 (NOLOCK)
WHERE	M.ISIN = #CONTRACT.ISIN
		AND S2.BSECODE = M.Scrip_Cd
		AND S2.DELSC_CAT='R' 
		AND RE_SCRIP = 'NO'

--UPDATE	#CONTRACT
--SET		RE_SCRIP = 'YES'

----------Changes for RE SCRIP-------




----------Changes for QR CODE-------

ALTER TABLE #CONTRACT
ADD	QR_CODE VARCHAR(MAX)

ALTER TABLE #CONTRACT
ADD	IRN_NO VARCHAR(500)


UPDATE	#CONTRACT 
SET 
QR_CODE = '',
IRN_NO=''





--SELECT * from TBL_GSTIN_RESPONSE_NEW

--UPDATE	#CONTRACT			
--SET		QR_CODE = ISNULL(V.QR_CODE,'ABC'),
--		IRN_NO = ISNULL(V.IRN,'0bb3142fc55815860aa6ca39eccbcc4e6c723d8e42f45860930ac817f98856e7')
--FROM	TBL_GSTIN_RESPONSE_NEW V
--WHERE	
--	#CONTRACT.CONTRACTNO = RIGHT(DOC_NO,LEN(DOC_NO)-CHARINDEX('/',DOC_NO))
	

----------Changes for QR CODE-------






/*---- Changes For HSN CODE Change ----*/

--UPDATE	#CONTRACT
--SET		TACC_SERVICE_NO = ISNULL(HSN_CODE,'')
--FROM	TBL_HSNCODE T(NOLOCK)
--WHERE	CONVERT(DATETIME,SAUDA_DATE,103) BETWEEN EFF_FROM AND EFF_TO

/*---- Changes For HSN CODE Change ----*/




/*Changes for new conract note*/



ALTER	TABLE #CONTRACT
ADD		PQTY		bigint,
		PMARKETRATE NUMERIC(18,4),
		PBROK		NUMERIC(18,4),
		PNETRATE	NUMERIC(18,4),
		PNETAMOUNT	NUMERIC(18,4),
		SQTY		bigint,
		SMARKETRATE NUMERIC(18,4),
		SBROK		NUMERIC(18,4),
		SNETRATE	NUMERIC(18,4),
		SNETAMOUNT	NUMERIC(18,4),
		NQTY		bigint,
		DEALINGADDRESS VARCHAR(200),
		CONTACT_PERSON VARCHAR(200),
		PMARKETAMT	NUMERIC(18,4),
		SMARKETAMT	NUMERIC(18,4),
		PBROKERAGE	NUMERIC(18,4),
		SBROKERAGE	NUMERIC(18,4)

--INSERT INTO #CONTRACT


UPDATE #CONTRACT
SET		PQTY =0,
		PMARKETRATE =0,
		PBROK =0,
		PNETRATE =0,
		PNETAMOUNT =0,
		SQTY =0,
		SMARKETRATE =0,
		SBROK =0,
		SNETRATE =0,
		SNETAMOUNT  =0,
		NQTY =0,
		DEALINGADDRESS='',
		CONTACT_PERSON='',
		PMARKETAMT=0,
		SMARKETAMT =0,
		PBROKERAGE =0,
		SBROKERAGE =0

UPDATE	#CONTRACT
SET		PMARKETAMT = (CASE WHEN SELL_BUY='BUY' THEN MARKETAMT ELSE 0 END),
		SMARKETAMT = (CASE WHEN SELL_BUY='SELL' THEN MARKETAMT ELSE 0 END),
		PQTY = (CASE WHEN SELL_BUY='BUY' THEN QTY ELSE 0 END),
		SQTY = (CASE WHEN SELL_BUY='SELL' THEN QTY ELSE 0 END),
		PBROKERAGE = (CASE WHEN SELL_BUY='BUY' THEN BROKERAGE ELSE 0 END),
		SBROKERAGE = (CASE WHEN SELL_BUY='SELL' THEN BROKERAGE ELSE 0 END)

/*** FOR FIX DEALING ADDRESS***/
DECLARE @BRANCHNAME VARCHAR(100)
SET @BRANCHNAME=''

SELECT @BRANCHNAME=BRANCHNAME from  DEALINGADDRESS



DECLARE @CONTACT_PERSON VARCHAR(200)
SET @CONTACT_PERSON=''

SELECT @CONTACT_PERSON =ISNULL(AUTHORISEDSIGNETORY1,'') + ISNULL(AUTHORISEDSIGNETORY2,'') + ISNULL(AUTHORISEDSIGNETORY3,'') + ISNULL(AUTHORISEDSIGNETORY4,'') 
 + ISNULL(AUTHORISEDSIGNETORY5,'') + ISNULL(AUTHORISEDSIGNETORY6,'') + ISNULL(AUTHORISEDSIGNETORY7,'')  
FROM AUTHORISEDSIGNETORIES 



IF LEN(@BRANCHNAME)>0
	BEGIN
		UPDATE #CONTRACT
		SET DEALINGADDRESS='Dealing Office/Branch Office:'+  BRANCHNAME + ' ' + ADDR1 + ' ' + ADDR2 + ' ' + ADDR3 + ' ' + ' Tel:' + ISNULL(PHONE1,'') + ' , FAX :' + ISNULL(FAX,'')
		from  DEALINGADDRESS
	END
/*** FOR FIX DEALING ADDRESS***/
ELSE
/*** FOR BRANCH , TRADER AND SUBBROKER  DEALING ADDRESS***/
	BEGIN

			CREATE TABLE #DEALINGADD
				(
					CODE		VARCHAR(20),
					LONG_NAME	VARCHAR(100),
					ADDRESS1	VARCHAR(100), 
					ADDRESS2	VARCHAR(100), 
					CITY		VARCHAR(50), 
					STATE		VARCHAR(50), 
					ZIP			VARCHAR(15), 
					PHONE1		VARCHAR(50), 
					FAX			VARCHAR(25), 
					EMAIL		VARCHAR(150), 
					CONTACT_PERSON VARCHAR(100)
				)
	
				IF (@PRINTDEALING = 'BRANCH')
				BEGIN
					INSERT INTO #DEALINGADD
					SELECT 
						CODE = LTRIM(RTRIM(BRANCH_CODE)), 
						LONG_NAME = LTRIM(RTRIM(LONG_NAME)), 
						ADDRESS1 = LTRIM(RTRIM(ADDRESS1)), 
						ADDRESS2 = LTRIM(RTRIM(ADDRESS2)), 
						CITY = LTRIM(RTRIM(CITY)), 
						STATE = LTRIM(RTRIM(STATE)), 
						ZIP = LTRIM(RTRIM(ZIP)), 
						PHONE1 = LTRIM(RTRIM(PHONE1)), 
						FAX = LTRIM(RTRIM(FAX)), 
						EMAIL = LTRIM(RTRIM(EMAIL)), 
						CONTACT_PERSON = LTRIM(RTRIM(CONTACT_PERSON))
					FROM BRANCH (NOLOCK) 
					--WHERE BRANCH_CODE = @CODE
				END
				ELSE IF (@PRINTDEALING = 'BRANCHES')
				BEGIN
					INSERT INTO #DEALINGADD
					SELECT 
						CODE = LTRIM(RTRIM(BRANCH_CD)), 
						LONG_NAME = LTRIM(RTRIM(LONG_NAME)), 
						ADDRESS1 = LTRIM(RTRIM(ADDRESS1)), 
						ADDRESS2 = LTRIM(RTRIM(ADDRESS2)), 
						CITY = LTRIM(RTRIM(CITY)), 
						STATE = LTRIM(RTRIM(STATE)), 
						ZIP = LTRIM(RTRIM(ZIP)), 
						PHONE1 = LTRIM(RTRIM(PHONE1)), 
						FAX = LTRIM(RTRIM(FAX)), 
						EMAIL = LTRIM(RTRIM(EMAIL)), 
						CONTACT_PERSON = LTRIM(RTRIM(CONTACT_PERSON))
					FROM BRANCHES (NOLOCK) 
						--WHERE SHORT_NAME = @CODE	
				END
				ELSE IF (@PRINTDEALING = 'SUBBROKERS')
				BEGIN
					INSERT INTO #DEALINGADD
					SELECT 
						CODE = LTRIM(RTRIM(SUB_BROKER)),
						LONG_NAME = LTRIM(RTRIM(NAME)), 
						ADDRESS1 = LTRIM(RTRIM(ADDRESS1)), 
						ADDRESS2 = LTRIM(RTRIM(ADDRESS2)), 
						CITY = LTRIM(RTRIM(CITY)), 
						STATE = LTRIM(RTRIM(STATE)), 
						ZIP = LTRIM(RTRIM(ZIP)), 
						PHONE1 = LTRIM(RTRIM(PHONE1)), 
						FAX = LTRIM(RTRIM(FAX)), 
						EMAIL = LTRIM(RTRIM(EMAIL)), 
						--BRANCH_CODE = LTRIM(RTRIM(SUB_BROKER)),
						CONTACT_PERSON 
					FROM SUBBROKERS (NOLOCK) 
					--WHERE SUB_BROKER = @CODE	
				END
				
				IF (@PRINTDEALING = 'BRANCH')
				BEGIN
					UPDATE #CONTRACT
					SET DEALINGADDRESS='Dealing Office/Branch Office:' + ' ' + ISNULL(ADDRESS1,'') + ' ' + ISNULL(ADDRESS2,'') + ' ' + ISNULL(CITY,'') + ' ' + ISNULL(STATE,'') + ' ' + ISNULL(ZIP,'') + ' Tel:' + ISNULL(PHONE1,'') + ' FAX:' + ISNULL(FAX,''),
					CONTACT_PERSON=#DEALINGADD.CONTACT_PERSON
					FROM #DEALINGADD
					WHERE BRANCH_CD=CODE
				END
				ELSE IF (@PRINTDEALING = 'BRANCHES')
				BEGIN
					UPDATE #CONTRACT
					SET DEALINGADDRESS='Dealing Office/Branch Office:' + ' ' + ISNULL(ADDRESS1,'') + ' ' + ISNULL(ADDRESS2,'') + ' ' + ISNULL(CITY,'') + ' ' + ISNULL(STATE,'') + ' ' + ISNULL(ZIP,'') + ' Tel:' + ISNULL(PHONE1,'') + ' FAX:' + ISNULL(FAX,''),
					CONTACT_PERSON=#DEALINGADD.CONTACT_PERSON
					FROM #DEALINGADD
					WHERE TRADER=CODE
				END
				ELSE IF (@PRINTDEALING = 'SUBBROKERS')
				BEGIN
					UPDATE #CONTRACT
					SET DEALINGADDRESS='Dealing Office/Branch Office:' + ' ' + ISNULL(ADDRESS1,'') + ' ' + ISNULL(ADDRESS2,'') + ' ' + ISNULL(CITY,'') + ' ' + ISNULL(STATE,'') + ' ' + ISNULL(ZIP,'') + ' Tel:' + ISNULL(PHONE1,'') + ' FAX:' + ISNULL(FAX,''),
					CONTACT_PERSON=#DEALINGADD.CONTACT_PERSON
					FROM #DEALINGADD
					WHERE SUB_BROKER=CODE
				END
				--SELECT * FROM #DEALINGADD
				DROP TABLE #DEALINGADD
/*** FOR BRANCH , TRADER AND SUBBROKER  DEALING ADDRESS***/
		END
/***** fix authorised signatory******/
	IF LEN(@CONTACT_PERSON) >0
	BEGIN
		UPDATE #CONTRACT
		SET CONTACT_PERSON=@CONTACT_PERSON
	
	END
/***** fix authorised signatory******/
/*Changes for new conract note*/
--SELECT * from #CONTRACT
--RETURN

IF @FORPDF <> 'Y'
	BEGIN

		SELECT 
			ORDERBYFLAG='',
			CONTRACTNO=MAX(CONTRACTNO),CONTRACTNO_NEW,SAUDA_DATE,
			SETT_NO,
			SETT_TYPE,
			SETT_DATE,
			PARTY_CODE,PARTYNAME,L_ADDRESS1,L_ADDRESS2,L_ADDRESS3,L_STATE,L_CITY,L_ZIP,
			OFF_PHONE1,OFF_PHONE2,PAN_GIR_NO,
			EXCHANGE=MAX(EXCHANGE),
			SEGMENT,
			ORDER_NO='',ORDER_TIME='',TRADE_NO='',TRADE_TIME='',
			SCRIPNAME = MAX(SCRIPNAME),
			QTY=SUM(QTY),
			TMARK='',
			SELL_BUY = (CASE WHEN SEGMENT='FUTURES' THEN SELL_BUY ELSE '' END),
			MARKETRATE= CONVERT(NUMERIC(18,4),ROUND((CASE WHEN  SUM(QTY) >0  THEN SUM(MARKETAMT)/SUM(QTY) ELSE 0 END),4)),			
			PQTY= SUM(CASE WHEN SELL_BUY='BUY'  THEN (QTY) ELSE 0 END),
			PMARKETRATE= CONVERT(NUMERIC(18,4),ROUND(CASE WHEN SUM(PQTY) > 0 THEN SUM(PMARKETAMT)/SUM(PQTY) ELSE 0 END,4)),
			PBROK=CONVERT(NUMERIC(18,4),ROUND(CASE WHEN SUM(PQTY) > 0 THEN SUM(PBROKERAGE)/SUM(PQTY) ELSE 0 END,4)),
			PNETRATE=CONVERT(NUMERIC(18,4),ROUND(ABS((CASE WHEN SUM(PQTY) > 0 THEN SUM(NETRATE*PQTY)/SUM(PQTY) ELSE 0 END)),4)),
			PNETAMOUNT=SUM(CASE WHEN SELL_BUY='BUY' THEN (NETAMOUNT) ELSE 0 END),

			SQTY=SUM(CASE WHEN SELL_BUY='SELL' THEN (QTY) ELSE 0 END),
			SMARKETRATE=CONVERT(NUMERIC(18,4),ROUND(CASE WHEN SUM(SQTY) > 0 THEN SUM(SMARKETAMT)/SUM(SQTY) ELSE 0 END,4)),
			SBROK=CONVERT(NUMERIC(18,4),ROUND(CASE WHEN SUM(SQTY) > 0 THEN SUM(SBROKERAGE)/SUM(SQTY) ELSE 0 END,4)),
			SNETRATE=CONVERT(NUMERIC(18,4),ROUND((CASE WHEN SUM(SQTY) > 0 THEN SUM(NETRATE*SQTY)/SUM(SQTY) ELSE 0 END),4)),
			SNETAMOUNT=SUM(CASE WHEN SELL_BUY='SELL' THEN (NETAMOUNT) ELSE 0 END),
			NQTY=SUM(PQTY-SQTY),			
			DEALINGADDRESS,
			CONTACT_PERSON,			
			MARKETAMT=SUM(MARKETAMT),
			BROKERAGE=SUM(BROKERAGE),
			SERVICE_TAX=SUM(SERVICE_TAX),
			INS_CHRG=SUM(INS_CHRG),
			IPFT_CHRG=SUM(IPFT_CHRG),
			NETAMOUNT=SUM(NETAMOUNT),
			SEBI_TAX=SUM(SEBI_TAX),
			TURN_TAX=SUM(TURN_TAX),
			BROKER_CHRG=SUM(BROKER_CHRG),
			OTHER_CHRG=SUM(OTHER_CHRG),
			NETAMOUNTALL=SUM(NETAMOUNTALL),PRINTF='',
			BROK=(CASE WHEN  SUM(QTY) >0  THEN SUM(BROKERAGE)/SUM(QTY) ELSE 0 END),
			NETRATE=(CASE WHEN  SUM(QTY) >0  THEN SUM(NETRATE*QTY)/SUM(QTY) ELSE 0 END),
			--CL_RATE=(CASE WHEN  SUM(QTY) >0  THEN SUM(CL_RATE)/SUM(QTY) ELSE 0 END),
			CL_RATE,
			UCC_CODE,BROKERSEBIREGNO,
			MEMBERCODE=MAX(MEMBERCODE),CINNO,BRANCH_CD,SUB_BROKER,TRADER,AREA,
			REGION,FAMILY,MAPIDID,SEBI_NO,PARTICIPANT_CODE,CL_TYPE,SERVICE_CHRG,
			SETTTYPE_DESC=MAX(SETTTYPE_DESC),
			BFCF_FLAG,CONTRACT_HEADER_DET=MAX(CONTRACT_HEADER_DET),
			REMARK=MAX(REMARK),
			COMPANYNAME,
			REMARK_ID = MAX(REMARK_ID),
			REMARK_DESC = MAX(REMARK_DESC),
			--NETOBLIGATION=(CASE WHEN  SUM(QTY) >0  THEN SUM(NETOBLIGATION)/SUM(QTY) ELSE 0 END) ,
			NETOBLIGATION=max(NETOBLIGATION),
			SETTLEMENT_DET,CONTRACTNO_DET,BROKERSEBIREGNO_DET,MEMBERCODE_DET,CIN_DET,
			NETAMOUNTEX,SEBI_TAXEX,TURN_TAXEX,BROKER_CHRGEX,OTHER_CHRGEX,INS_CHRGEX,
			IPFT_CHRGEX,SERVICE_TAXEX,
			SCRIPNAME_NEW=MAX(SCRIPNAME_NEW),REMARK_DET,ORDFLAG,ISIN,ORD_DATE,
			--EXCHANGE_OLD,
			SEGMENT_OLD = MAX(SEGMENT_OLD),
			INTEROPCODE,SCRIPDESC,
			CONTRACTNO_OLD=MAX(CONTRACTNO_OLD),
			SETT_NO_OLD=MAX(SETT_NO_OLD),
			SETT_TYPE_OLD=MAX(SETT_TYPE_OLD),
			SETTTYPE_DESC_OLD=MAX(SETTTYPE_DESC_OLD),
			CGST_TAXEX,
			SGST_TAXEX,
			IGST_TAXEX,
			UGST_TAXEX,
			CGST=SUM(CGST),SGST=SUM(SGST),IGST=SUM(IGST),UGST=SUM(UGST),CLGSTNO,GSTFLAG,CGST_PER,SGST_PER,IGST_PER,UGST_PER,
			TARGETSTATE,SOURCESTATE,STATE_CODE,DEAL_CLIENT_ADD,TGST_NO,TPAN_NO,TDESC_SERVICE,TACC_SERVICE_NO,
			TAXABLE_VALUE,BROKERAGE_TAXEX,FOOTER_TAXABLE_TEXT,KCESS_PER,KCESS,KCESS_TAXEX,
			--FOREIGN_PRICE=(CASE WHEN  SUM(QTY) >0  THEN SUM(FOREIGN_PRICE)/SUM(QTY) ELSE 0 END) ,
			FOREIGN_PRICE=(CASE WHEN  SUM(QTY) >0  THEN SUM(FOREIGN_PRICE*QTY)/SUM(QTY) ELSE 0 END) ,
			NRIACCNO,CL_STATUS,RE_SCRIP,QR_CODE,IRN_NO,
			SEBIREGNO = ISNULL(@SEBIREGNO,''),
			BR_CMDPID = ISNULL(@BR_CMDPID,''),
			BSEBR_CMDPID = ISNULL(@BSEBR_CMDPID,''),
			CONTRACT_HEADER_DET_NEW = MAX(REPLACE(CONTRACT_HEADER_DET,SETTTYPE_DESC,'')),
			STTFLAG = @STTFLAG,
			SERFLAG = @SERFLAG,

			--### START EXCHANGE/DEPOSITORY LISTING SCRIP ###---
			EXCHANGE_SCRIP = (
			CASE
				WHEN ISIN <> '' AND @EXCHANGE_SCRIP LIKE '%'+ISIN+'%' THEN  'YES'
				ELSE 'NO'
			END),
			DEPOSITORY_SCRIP = (
			CASE
				WHEN ISIN <> '' AND @DEPOSITORY_SCRIP LIKE '%'+ISIN+'%' THEN  'YES'
				ELSE 'NO'
			END),
			--### END EXCHANGE/DEPOSITORY LISTING SCRIP ###---
			FILENAME = 'COMM_CONTRACT_' + CONVERT(VARCHAR,CONVERT(DATETIME,SAUDA_DATE,103),112) + '_' + LTRIM(RTRIM(PARTY_CODE)) + '_' + LTRIM(RTRIM(CONTRACTNO_NEW))
				--SEBIREGNO,BR_CMDPID,BSEBR_CMDPID,
				--CONTRACT_HEADER_DET_NEW,STTFLAG,SERFLAG,EXCHANGE_SCRIP,DEPOSITORY_SCRIP,FILENAME
            ,
			SELLBUYFLAG = (CASE WHEN SEGMENT='FUTURES' THEN LEFT(SELL_BUY,1) 
			+ (CASE WHEN LEFT(BFCF_FLAG,2) = 'BF' THEN ' / '+ LEFT(BFCF_FLAG,2) ELSE REPLACE(REPLACE(REPLACE(BFCF_FLAG,'BT_F',''),'BT_O',''),'BT_B','') END) ELSE '' END) 

			from #CONTRACT
			GROUP BY 
			CONTRACTNO_NEW,SAUDA_DATE,
			SETT_DATE,PARTY_CODE,PARTYNAME,L_ADDRESS1,L_ADDRESS2,L_ADDRESS3,L_STATE,
			L_CITY,L_ZIP,OFF_PHONE1,OFF_PHONE2,PAN_GIR_NO,
			--EXCHANGE,
			SEGMENT,
			(CASE WHEN SEGMENT='FUTURES' THEN SELL_BUY ELSE '' END),
			--SCRIPNAME,
			UCC_CODE,BROKERSEBIREGNO,CINNO,BRANCH_CD,SUB_BROKER,
			TRADER,AREA,REGION,FAMILY,MAPIDID,SEBI_NO,PARTICIPANT_CODE,CL_TYPE,
			SERVICE_CHRG,
			NETAMOUNTEX,SEBI_TAXEX,TURN_TAXEX,BROKER_CHRGEX,OTHER_CHRGEX,INS_CHRGEX,
			IPFT_CHRGEX,SERVICE_TAXEX,
			CGST_TAXEX,SGST_TAXEX,IGST_TAXEX,UGST_TAXEX,
			BFCF_FLAG,COMPANYNAME,SETTLEMENT_DET,
			CONTRACTNO_DET,BROKERSEBIREGNO_DET,MEMBERCODE_DET,CIN_DET,
			--SCRIPNAME_NEW,
			REMARK_DET,ORDFLAG,ISIN,ORD_DATE,--EXCHANGE_OLD,
			SEGMENT_OLD,
			CLGSTNO,GSTFLAG,CGST_PER,SGST_PER,IGST_PER,UGST_PER,TARGETSTATE,
			SOURCESTATE,STATE_CODE,DEAL_CLIENT_ADD,TGST_NO,TPAN_NO,TDESC_SERVICE,
			TACC_SERVICE_NO,
			TAXABLE_VALUE,BROKERAGE_TAXEX,FOOTER_TAXABLE_TEXT,KCESS_PER,KCESS,
			KCESS_TAXEX,
			INTEROPCODE,SCRIPDESC,
			NRIACCNO,CL_STATUS,RE_SCRIP,QR_CODE,IRN_NO,
			DEALINGADDRESS,
			CONTACT_PERSON,
			CL_RATE,
			SETT_NO,
			SETT_TYPE,
			--REPLACE(CONTRACT_HEADER_DET,SETTTYPE_DESC,''),			
			(CASE WHEN SEGMENT='FUTURES' THEN LEFT(SELL_BUY,1) 
			+ (CASE WHEN LEFT(BFCF_FLAG,2) = 'BF' THEN ' / '+ LEFT(BFCF_FLAG,2) ELSE REPLACE(REPLACE(REPLACE(BFCF_FLAG,'BT_F',''),'BT_O',''),'BT_B','') END) ELSE '' END) 
			ORDER BY
			--ORDERBYFLAG,
			ORD_DATE,
			PARTY_CODE,
			CONTRACTNO_NEW,
			SEGMENT,
			--EXCHANGE,  
			SETT_NO,  
			BFCF_FLAG,
			ISIN,
			SCRIPNAME,
			(CASE WHEN SEGMENT='FUTURES' THEN SELL_BUY ELSE '' END),
			ORDFLAG
			

		END
ELSE
	BEGIN
		--CREATE TABLE #COMMON_CONTRACT
		--(
		--	SRNO INT IDENTITY(1, 1),
		--	ORDERBYFLAG VARCHAR(155),
		--	CONTRACTNO VARCHAR(10),
		--	CONTRACTNO_NEW VARCHAR(10),
		--	SAUDA_DATE VARCHAR(30),
		--	SETT_NO VARCHAR(10),
		--	SETT_TYPE VARCHAR(3),
		--	SETT_DATE VARCHAR(11),
		--	PARTY_CODE VARCHAR(15),
		--	PARTYNAME VARCHAR(100),
		--	L_ADDRESS1 VARCHAR(100),
		--	L_ADDRESS2 VARCHAR(100),
		--	L_ADDRESS3 VARCHAR(100),
		--	L_STATE VARCHAR(50),
		--	L_CITY VARCHAR(50),
		--	L_ZIP VARCHAR(10),
		--	OFF_PHONE1 VARCHAR(50),
		--	OFF_PHONE2 VARCHAR(50),
		--	PAN_GIR_NO VARCHAR(15),
		--	EXCHANGE VARCHAR(3),
		--	SEGMENT VARCHAR(10),
		--	ORDER_NO VARCHAR(20),
		--	ORDER_TIME VARCHAR(8),
		--	TRADE_NO VARCHAR(16),
		--	TRADE_TIME VARCHAR(8),
		--	SCRIPNAME VARCHAR(100),
		--	QTY BIGINT,
		--	TMARK VARCHAR(1),
		--	SELL_BUY VARCHAR(4),
		--	MARKETRATE NUMERIC(19, 4),
		--	MARKETAMT NUMERIC(19, 4),
		--	BROKERAGE NUMERIC(19, 4),
		--	SERVICE_TAX NUMERIC(19, 4),
		--	INS_CHRG NUMERIC(19, 4),
		--	NETAMOUNT NUMERIC(19, 4),
		--	SEBI_TAX NUMERIC(19, 4),
		--	TURN_TAX NUMERIC(19, 4),
		--	BROKER_CHRG NUMERIC(19, 4),
		--	OTHER_CHRG NUMERIC(19, 4),
		--	NETAMOUNTALL NUMERIC(19, 4),
		--	PRINTF TINYINT,
		--	BROK NUMERIC(19, 4),
		--	NETRATE NUMERIC(19, 4),
		--	CL_RATE NUMERIC(19, 4),
		--	UCC_CODE VARCHAR(20),
		--	BROKERSEBIREGNO VARCHAR(20),
		--	MEMBERCODE VARCHAR(50),
		--	CINNO VARCHAR(100),
		--	BRANCH_CD VARCHAR(15),
		--	SUB_BROKER VARCHAR(15),
		--	TRADER VARCHAR(25),
		--	AREA VARCHAR(25),
		--	REGION VARCHAR(25),
		--	FAMILY VARCHAR(15),
		--	MAPIDID VARCHAR(20),
		--	SEBI_NO VARCHAR(25),
		--	PARTICIPANT_CODE VARCHAR(16),
		--	CL_TYPE VARCHAR(3),
		--	SERVICE_CHRG TINYINT,
		--	SETTTYPE_DESC VARCHAR(35),
		--	BFCF_FLAG VARCHAR(6),
		--	CONTRACT_HEADER_DET VARCHAR(200),
		--	REMARK VARCHAR(100),
		--	COMPANYNAME VARCHAR(100),
		--	REMARK_ID VARCHAR(1),
		--	REMARK_DESC VARCHAR(200),
		--	NETOBLIGATION NUMERIC(19, 4),
		--	SETTLEMENT_DET VARCHAR(600),
		--	CONTRACTNO_DET VARCHAR(600),
		--	BROKERSEBIREGNO_DET VARCHAR(600),
		--	MEMBERCODE_DET VARCHAR(600),
		--	CIN_DET VARCHAR(600),
		--	NETAMOUNTEX NUMERIC(20, 6),
		--	SEBI_TAXEX NUMERIC(18, 4),
		--	TURN_TAXEX NUMERIC(18, 4),
		--	BROKER_CHRGEX NUMERIC(18, 4),
		--	OTHER_CHRGEX NUMERIC(18, 4),
		--	INS_CHRGEX NUMERIC(18, 4),
		--	SERVICE_TAXEX NUMERIC(18, 4),
		--	SCRIPNAME_NEW VARCHAR(300),
		--	REMARK_DET VARCHAR(300)
		--)
		/*INSERT INTO #COMMON_CONTRACT (ORDERBYFLAG, CONTRACTNO, CONTRACTNO_NEW, SAUDA_DATE, SETT_NO, SETT_TYPE,
					SETT_DATE, PARTY_CODE, PARTYNAME, L_ADDRESS1, L_ADDRESS2, L_ADDRESS3, L_STATE, L_CITY, L_ZIP,
					OFF_PHONE1, OFF_PHONE2, PAN_GIR_NO, EXCHANGE, SEGMENT, ORDER_NO, ORDER_TIME, TRADE_NO, TRADE_TIME,
					SCRIPNAME, QTY, TMARK, SELL_BUY, MARKETRATE, MARKETAMT, BROKERAGE, SERVICE_TAX, INS_CHRG,
					NETAMOUNT, SEBI_TAX, TURN_TAX, BROKER_CHRG, OTHER_CHRG, NETAMOUNTALL, PRINTF, BROK, NETRATE,
					CL_RATE, UCC_CODE, BROKERSEBIREGNO, MEMBERCODE, CINNO, BRANCH_CD, SUB_BROKER, TRADER, AREA,
					REGION, FAMILY, MAPIDID, SEBI_NO, PARTICIPANT_CODE, CL_TYPE, SERVICE_CHRG, SETTTYPE_DESC,
					BFCF_FLAG, CONTRACT_HEADER_DET, REMARK, COMPANYNAME, REMARK_ID, REMARK_DESC, NETOBLIGATION,
					SETTLEMENT_DET, CONTRACTNO_DET, BROKERSEBIREGNO_DET, MEMBERCODE_DET, CIN_DET, NETAMOUNTEX,
					SEBI_TAXEX, TURN_TAXEX, BROKER_CHRGEX, OTHER_CHRGEX, INS_CHRGEX, SERVICE_TAXEX,
					SCRIPNAME_NEW, REMARK_DET,
					STTFLAG,
					SERFLAG)*/
		SELECT	ORDERBYFLAG, CONTRACTNO, CONTRACTNO_NEW, SAUDA_DATE, SETT_NO, SETT_TYPE,
				SETT_DATE, PARTY_CODE, PARTYNAME, L_ADDRESS1, L_ADDRESS2, L_ADDRESS3, L_STATE, L_CITY, L_ZIP,
				OFF_PHONE1, OFF_PHONE2, PAN_GIR_NO, EXCHANGE, SEGMENT, ORDER_NO, ORDER_TIME, TRADE_NO, TRADE_TIME,
				SCRIPNAME, QTY, TMARK, SELL_BUY, MARKETRATE, MARKETAMT, BROKERAGE, SERVICE_TAX, INS_CHRG,IPFT_CHRG,
				NETAMOUNT, SEBI_TAX, TURN_TAX, BROKER_CHRG, OTHER_CHRG, NETAMOUNTALL, PRINTF, BROK, NETRATE,
				CL_RATE, UCC_CODE, BROKERSEBIREGNO, MEMBERCODE, CINNO, BRANCH_CD, SUB_BROKER, TRADER, AREA,
				REGION, FAMILY, MAPIDID, SEBI_NO, PARTICIPANT_CODE, CL_TYPE, SERVICE_CHRG, SETTTYPE_DESC,
				BFCF_FLAG, CONTRACT_HEADER_DET, REMARK, COMPANYNAME, REMARK_ID, REMARK_DESC, NETOBLIGATION,
				SETTLEMENT_DET, CONTRACTNO_DET, BROKERSEBIREGNO_DET, MEMBERCODE_DET, CIN_DET, NETAMOUNTEX,
				SEBI_TAXEX, TURN_TAXEX, BROKER_CHRGEX, OTHER_CHRGEX, INS_CHRGEX,IPFT_CHRGEX, SERVICE_TAXEX, SCRIPNAME_NEW, REMARK_DET,
				STTFLAG = @STTFLAG,
				SERFLAG = @SERFLAG,
				ISIN, ORD_DATE,
				EXCHANGE_SCRIP = (
				CASE
					WHEN ISIN <> '' AND @EXCHANGE_SCRIP LIKE '%'+ISIN+'%' THEN  'YES'
					ELSE 'NO'
				END),
				CGST_TAXEX,
				SGST_TAXEX,
				IGST_TAXEX,
				UGST_TAXEX,
				CGST,
				SGST,
				IGST,
				UGST,
				CLGSTNO,
				GSTFLAG,
				CGST_PER,
				SGST_PER,
				IGST_PER,
				UGST_PER,
				TARGETSTATE,
				SOURCESTATE,
				STATE_CODE,
				DEAL_CLIENT_ADD,
				TGST_NO,
				TPAN_NO,
				TDESC_SERVICE,
				TACC_SERVICE_NO,
				TAXABLE_VALUE,
				BROKERAGE_TAXEX,
				FILENAME = 'COMM_CONTRACT_' + CONVERT(VARCHAR,CONVERT(DATETIME,SAUDA_DATE,103),112) + '_' + LTRIM(RTRIM(PARTY_CODE)) + '_' + LTRIM(RTRIM(CONTRACTNO_NEW))
		FROM #CONTRACT
		ORDER BY
			ORD_DATE,
			ORDERBYFLAG,
			PARTY_CODE,
			CONTRACTNO_NEW,
			EXCHANGE,  
			SEGMENT, 
			SETT_NO, 
			BFCF_FLAG,
			ISIN,
			SCRIPNAME,
			CONTRACTNO DESC,
			SELL_BUY,
			ORDER_NO,
			ORDFLAG,
			TRADE_NO
	END




DROP TABLE #CONTDATA
DROP TABLE #CONTRACT
DROP TABLE #PARTY

GO
