-- Object: PROCEDURE dbo.BAK_PROC_CLIENT_COLLATREAL_ALLOC_VDT_EDT_22072022
-- Server: 10.253.33.91 | DB: MSAJAG
--------------------------------------------------



--PROC_CLIENT_COLLATREAL_ALLOC_VDT_EDT 'MAY  9 2022'
CREATE PROC	[dbo].[BAK_PROC_CLIENT_COLLATREAL_ALLOC_VDT_EDT_22072022]
(
	@RUNDATE VARCHAR(11)
)	
AS
DECLARE
		@PARTY_CODE	VARCHAR(10),
		@EXCHANGE	VARCHAR(3),
		@SEGMENT	VARCHAR(7),
		@NEWEXCHANGE	VARCHAR(3),
		@NEWSEGMENT	VARCHAR(7),
		@LEDBAL		NUMERIC(18,3),
		@NEWLEDBAL		NUMERIC(18,3),
		@DIFFLEDBAL		NUMERIC(18,3),
		@SNO	INT,
		@NEWSNO	INT,
		@ADJCUR		CURSOR,
		@ALLOCCURSOR	CURSOR
		 
SET NOCOUNT ON 

SELECT DISTINCT PARTY_CODE INTO #TEMPVDT
FROM CLIENT_COLLATERAL_REPORTING_DETAILS_TODAY  WITH(NOLOCK)
WHERE PROCESS_DT = @RUNDATE AND VDT_LEDGER > 0 AND EXCHANGE <> 'MTF'

CREATE INDEX #VDT ON #TEMPVDT(PARTY_CODE)

SELECT DISTINCT PARTY_CODE INTO #PARTYALLOC
FROM CLIENT_COLLATERAL_REPORTING_DETAILS_TODAY With(Nolock)
WHERE PROCESS_DT = @RUNDATE AND VDT_LEDGER < 0 AND EXCHANGE <> 'MTF'
AND PARTY_CODE IN ( SELECT PARTY_CODE FROM #TEMPVDT) 

CREATE INDEX #VDT ON #PARTYALLOC (PARTY_CODE)

SELECT PARTY_CODE, EXCHANGE, SEGMENT, VDT_LEDGER 
INTO #ADJDATA FROM CLIENT_COLLATERAL_REPORTING_DETAILS_TODAY  With(Nolock)
WHERE PROCESS_DT = @RUNDATE AND EXCHANGE <> 'MTF'
AND PARTY_CODE IN (SELECT PARTY_CODE FROM #PARTYALLOC  With(Nolock))

ALTER TABLE #ADJDATA
ADD SNO INT IDENTITY(1,1)

CREATE CLUSTERED INDEX IDXDT ON #ADJDATA
(
	SNO
)

CREATE NONCLUSTERED INDEX IDXPARTY ON #ADJDATA
(
	PARTY_CODE,EXCHANGE, SEGMENT,VDT_LEDGER
)

SELECT SNO, PARTY_CODE, EXCHANGE, SEGMENT, VDT_LEDGER INTO #FINALADJDATA
FROM #ADJDATA  With(Nolock)
WHERE VDT_LEDGER < 0  
AND PARTY_CODE IN ( SELECT PARTY_CODE
FROM #ADJDATA  With(Nolock)
WHERE VDT_LEDGER > 0 )

CREATE NONCLUSTERED INDEX IDXPARTY ON #FINALADJDATA
(
	PARTY_CODE--,EXCHANGE, SEGMENT 
)

SET @ADJCUR = CURSOR FOR 
--SELECT SNO, PARTY_CODE, EXCHANGE, SEGMENT, VDT_LEDGER
--FROM #ADJDATA  With(Nolock)
--WHERE VDT_LEDGER < 0  
--AND PARTY_CODE IN ( SELECT PARTY_CODE
--FROM #ADJDATA  With(Nolock)
--WHERE VDT_LEDGER > 0 )

SELECT SNO,PARTY_CODE, EXCHANGE, SEGMENT, VDT_LEDGER
FROM #FINALADJDATA WITH(NOLOCK)
--AND PARTY_CODE = '10114978'
ORDER BY PARTY_CODE, EXCHANGE, SEGMENT

RETURN

SELECT SNO,PARTY_CODE, EXCHANGE, SEGMENT, VDT_LEDGER
FROM #FINALADJDATA WITH(NOLOCK)
--AND PARTY_CODE = '10114978'
ORDER BY PARTY_CODE, EXCHANGE, SEGMENT
OPEN @ADJCUR
FETCH NEXT FROM @ADJCUR INTO @SNO, @PARTY_CODE, @EXCHANGE, @SEGMENT, @LEDBAL
WHILE @@FETCH_STATUS = 0 
BEGIN
	SET @ALLOCCURSOR = CURSOR FOR 
	SELECT SNO, EXCHANGE, SEGMENT, VDT_LEDGER FROM #ADJDATA With(NOLOCK)
	WHERE PARTY_CODE = @PARTY_CODE AND VDT_LEDGER > 0  
	ORDER BY EXCHANGE, SEGMENT
	OPEN @ALLOCCURSOR
	FETCH NEXT FROM @ALLOCCURSOR INTO @NEWSNO, @NEWEXCHANGE, @NEWSEGMENT, @NEWLEDBAL
	WHILE @@FETCH_STATUS = 0 
	BEGIN
		IF @LEDBAL < 0 AND @NEWLEDBAL > 0 
		BEGIN
			SELECT @DIFFLEDBAL = (CASE WHEN ABS(@LEDBAL) > ABS(@NEWLEDBAL) THEN ABS(@NEWLEDBAL) ELSE ABS(@LEDBAL) END)
			UPDATE #ADJDATA SET VDT_LEDGER = VDT_LEDGER - @DIFFLEDBAL
			WHERE SNO = @NEWSNO

			UPDATE #ADJDATA SET VDT_LEDGER = VDT_LEDGER + @DIFFLEDBAL
			WHERE SNO = @SNO

			SET @LEDBAL = @LEDBAL + @DIFFLEDBAL
		END 
		FETCH NEXT FROM @ALLOCCURSOR INTO @NEWSNO, @NEWEXCHANGE, @NEWSEGMENT, @NEWLEDBAL
	END
	CLOSE @ALLOCCURSOR
	DEALLOCATE @ALLOCCURSOR
	FETCH NEXT FROM @ADJCUR INTO @SNO, @PARTY_CODE, @EXCHANGE, @SEGMENT, @LEDBAL
END
CLOSE @ADJCUR
DEALLOCATE @ADJCUR


SELECT PARTY_CODE INTO #TEMPEDT 
FROM CLIENT_COLLATERAL_REPORTING_DETAILS_TODAY  With(Nolock)
WHERE PROCESS_DT = @RUNDATE AND EDT_LEDGER > 0 AND EXCHANGE <> 'MTF'

CREATE INDEX #EDT ON #TEMPEDT(PARTY_CODE)

SELECT DISTINCT PARTY_CODE INTO #PARTYALLOCEDT
FROM CLIENT_COLLATERAL_REPORTING_DETAILS_TODAY  With(Nolock)
WHERE PROCESS_DT = @RUNDATE AND EDT_LEDGER < 0 AND EXCHANGE <> 'MTF'
AND PARTY_CODE IN ( SELECT PARTY_CODE
FROM #TEMPEDT) 

CREATE INDEX #EDT ON #PARTYALLOCEDT (PARTY_CODE)

SELECT PARTY_CODE, EXCHANGE, SEGMENT, EDT_LEDGER 
INTO #ADJDATAEDT FROM CLIENT_COLLATERAL_REPORTING_DETAILS_TODAY  With(Nolock)
WHERE PROCESS_DT = @RUNDATE AND EXCHANGE <> 'MTF'
AND PARTY_CODE IN (SELECT PARTY_CODE FROM #PARTYALLOCEDT)

ALTER TABLE #ADJDATAEDT
ADD SNO INT IDENTITY(1,1)

CREATE CLUSTERED INDEX IDXDT ON #ADJDATAEDT
(
	SNO
)

CREATE NONCLUSTERED INDEX IDXPARTYLED ON #ADJDATAEDT
(
	PARTY_CODE, EXCHANGE, SEGMENT,EDT_LEDGER
)

SELECT SNO, PARTY_CODE, EXCHANGE, SEGMENT, EDT_LEDGER INTO #FINALADJDATAEDT
FROM #ADJDATAEDT  With(Nolock)
WHERE EDT_LEDGER < 0  
AND PARTY_CODE IN ( SELECT PARTY_CODE
FROM #ADJDATAEDT  With(Nolock)
WHERE EDT_LEDGER > 0 )

CREATE NONCLUSTERED INDEX #IDXPARTY ON #FINALADJDATAEDT
(
	PARTY_CODE,EXCHANGE, SEGMENT 
)

SET @ADJCUR = CURSOR FOR 
--SELECT SNO, PARTY_CODE, EXCHANGE, SEGMENT, EDT_LEDGER
--FROM #ADJDATAEDT  With(Nolock)
--WHERE EDT_LEDGER < 0  
--AND PARTY_CODE IN ( SELECT PARTY_CODE
--FROM #ADJDATAEDT  With(Nolock)
--WHERE EDT_LEDGER > 0 )
--AND PARTY_CODE = '10114978'
SELECT SNO, PARTY_CODE, EXCHANGE, SEGMENT, EDT_LEDGER
FROM #FINALADJDATAEDT  With(Nolock)--WHERE EDT_LEDGER < 0  
--AND PARTY_CODE IN ( SELECT PARTY_CODE
--FROM #ADJDATAEDT  With(Nolock)
--WHERE EDT_LEDGER > 0 )
ORDER BY PARTY_CODE, EXCHANGE, SEGMENT
OPEN @ADJCUR
FETCH NEXT FROM @ADJCUR INTO @SNO, @PARTY_CODE, @EXCHANGE, @SEGMENT, @LEDBAL
WHILE @@FETCH_STATUS = 0 
BEGIN
	SET @ALLOCCURSOR = CURSOR FOR 
	SELECT SNO, EXCHANGE, SEGMENT, EDT_LEDGER FROM #ADJDATAEDT  With(Nolock)
	WHERE PARTY_CODE = @PARTY_CODE AND EDT_LEDGER > 0  
	ORDER BY EXCHANGE, SEGMENT
	OPEN @ALLOCCURSOR
	FETCH NEXT FROM @ALLOCCURSOR INTO @NEWSNO, @NEWEXCHANGE, @NEWSEGMENT, @NEWLEDBAL
	WHILE @@FETCH_STATUS = 0 
	BEGIN
		IF @LEDBAL < 0 AND @NEWLEDBAL > 0 
		BEGIN
			SELECT @DIFFLEDBAL = (CASE WHEN ABS(@LEDBAL) > ABS(@NEWLEDBAL) THEN ABS(@NEWLEDBAL) ELSE ABS(@LEDBAL) END)
			UPDATE #ADJDATAEDT SET EDT_LEDGER = EDT_LEDGER - @DIFFLEDBAL
			WHERE SNO = @NEWSNO

			UPDATE #ADJDATAEDT SET EDT_LEDGER = EDT_LEDGER + @DIFFLEDBAL
			WHERE SNO = @SNO

			SET @LEDBAL = @LEDBAL + @DIFFLEDBAL
		END
		FETCH NEXT FROM @ALLOCCURSOR INTO @NEWSNO, @NEWEXCHANGE, @NEWSEGMENT, @NEWLEDBAL
	END
	CLOSE @ALLOCCURSOR
	DEALLOCATE @ALLOCCURSOR
	FETCH NEXT FROM @ADJCUR INTO @SNO, @PARTY_CODE, @EXCHANGE, @SEGMENT, @LEDBAL
END
CLOSE @ADJCUR
DEALLOCATE @ADJCUR

UPDATE CO SET VDT_LEDGER = C.VDT_LEDGER
FROM #ADJDATA C With(Nolock),CLIENT_COLLATERAL_REPORTING_DETAILS_TODAY  CO With(Nolock)
WHERE PROCESS_DT = @RUNDATE
AND C.PARTY_CODE = CO.PARTY_CODE
AND C.EXCHANGE = CO.EXCHANGE
AND C.SEGMENT = CO.SEGMENT

UPDATE CO SET EDT_LEDGER = C.EDT_LEDGER
FROM #ADJDATAEDT C With(Nolock),CLIENT_COLLATERAL_REPORTING_DETAILS_TODAY CO With(Nolock)
WHERE PROCESS_DT = @RUNDATE
AND C.PARTY_CODE = CO.PARTY_CODE
AND C.EXCHANGE = CO.EXCHANGE
AND C.SEGMENT = CO.SEGMENT

GO
