-- Object: PROCEDURE dbo.Add_client_proc_share_client_insert_tmp
-- Server: 10.253.33.91 | DB: MSAJAG
--------------------------------------------------

CREATE Proc Add_client_proc_share_client_insert_tmp

	@tmppartycode Varchar (10),
	@tmplongname Varchar (100),
	@tmpaddr1 Varchar (40),
	@tmpaddr2 Varchar (40),
	@tmpaddr3 Varchar (40),
	@tmpcity Varchar (40),
	@tmpstate Varchar (15),

	@tmpzipcode Varchar(10), 

	@tmptelnor Varchar (15),
	@tmptelnoo Varchar (15),
	@tmpcellno Varchar (40),
	@tmpfax Varchar (15),
	@tmpemail Varchar (50),
	@tmppanno Varchar (50),
	@tmpbranchcode Varchar (10),
	@tmptradercode Varchar (20),
	@tmpsubbrokercode Varchar (10),
	@tmpclienttype Varchar (3),
	@tmpclientstatus Varchar (3),
	@tmpregion Varchar (50),
	@tmparea Varchar (10),

	@tmpgroupcode Varchar(10), 

	@tmpfamilycode Varchar (10),
	@tmptranscat Varchar (3),
	@tmpbrokscheme Varchar (1),
	@tmptrdtableno Int,
	@tmpdeltableno Int,
	@tmpservicetax Int,
	@tmpprint Tinyint,
	@tmptransactionchargestrd Decimal(5, 4),
	@tmptransactionchargesdel Decimal(5, 4),
	@tmpstampdutytrd Decimal(5, 4),
	@tmpstampdutydel Decimal(5, 4),

	@tmproundoffmethod Varchar(20), 
	@tmproundtodigit Int, 
	@tmproundtopaisa Int, 
	@tmperrnum Numeric(19,8), 
	@tmpnozero Int,

	@tmpdebitbalance Tinyint,
	@tmpintersettlement Tinyint,
	@tmpbankname Varchar (50),
	@tmpbranchname Varchar (40),
	@tmpactype Varchar (7),
	@tmpacno Varchar (50),
	@tmpdepository Varchar (7),
	@tmpdpid Varchar (15),
	@tmpclientdpid Varchar (16),
	@tmpdefaultdp Varchar (1),
	@tmppoa Varchar (1),
	@tmpsex Varchar (1),
	@tmpdob Datetime,
	@tmpapprover Varchar (30),
	@tmppassportno Varchar (30),
	@tmppassportissuedat Varchar (30),
	@tmppassportissuedon Datetime,
	@tmppassportexpireson Datetime,
	@tmplicenceno Varchar (30),
	@tmplicenceissuedat Varchar (30),
	@tmplicenceissuedon Datetime,
	@tmplicenceexpireson Datetime,
	@tmprationcardno Varchar (30),
	@tmprationcardissuedat Varchar (30),
	@tmprationcardissuedon Datetime,
	@tmpvoteridno Varchar (30),
	@tmpvoteridissuedat Varchar (30),
	@tmpvoteridissuedon Datetime,
	@tmpdateofinc Datetime,
	@tmpregnno Varchar (50),
	@tmpinactivefrom Datetime,
	@tmpb2bpayment Varchar (50),
	@tmppaymentbankname Varchar (50),
	@tmppaymentbranchname Varchar (50),
	@tmppaymentmode Varchar (50),
	@tmppaymentacno Varchar (50),
	@tmpshortname Varchar (30)

As

Insert Into
	Tmp_client_details
Values
	(
		@tmppartycode,
		@tmplongname,
		@tmpaddr1,
		@tmpaddr2,
		@tmpaddr3,
		@tmpcity,
		@tmpstate,

		@tmpzipcode,

		@tmptelnor,
		@tmptelnoo,
		@tmpcellno,
		@tmpfax,
		@tmpemail,
		@tmppanno,
		@tmpbranchcode,
		@tmptradercode,
		@tmpsubbrokercode,
		@tmpclienttype,
		@tmpclientstatus,
		@tmpregion,
		@tmparea,

		@tmpgroupcode,

		@tmpfamilycode,
		@tmptranscat,
		@tmpbrokscheme,
		@tmptrdtableno,
		@tmpdeltableno,
		@tmpservicetax,
		@tmpprint,
		@tmptransactionchargestrd,
		@tmptransactionchargesdel,
		@tmpstampdutytrd,
		@tmpstampdutydel,

		@tmproundoffmethod,
		@tmproundtodigit,
		@tmproundtopaisa,
		@tmperrnum,
		@tmpnozero,

		@tmpdebitbalance,
		@tmpintersettlement,
		@tmpbankname,
		@tmpbranchname,
		@tmpactype,
		@tmpacno,
		@tmpdepository,
		@tmpdpid,
		@tmpclientdpid,
		@tmpdefaultdp,
		@tmppoa,
		@tmpsex,
		@tmpdob,
		@tmpapprover,
		@tmppassportno,
		@tmppassportissuedat,
		@tmppassportissuedon,
		@tmppassportexpireson,
		@tmplicenceno,
		@tmplicenceissuedat,
		@tmplicenceissuedon,
		@tmplicenceexpireson,
		@tmprationcardno,
		@tmprationcardissuedat,
		@tmprationcardissuedon,
		@tmpvoteridno,
		@tmpvoteridissuedat,
		@tmpvoteridissuedon,
		@tmpdateofinc,
		@tmpregnno,
		/*@tmpinactivefrom,*/
		/*Dateadd(dd, -1, Getdate()),*/
		convert(datetime,convert(varchar(2),datepart(mm,getdate()))+'/'+convert(varchar(2),datepart(dd,getdate()))+'/2049'),
		@tmpb2bpayment,
		@tmppaymentbankname,
		@tmppaymentbranchname,
		@tmppaymentmode,
		@tmppaymentacno,
		@tmpshortname
	)

GO
