-- Object: PROCEDURE dbo.BANKNIFTY_FINNIFTY_ISSUE_ANG_EMAIL
-- Server: 10.253.33.91 | DB: MSAJAG
--------------------------------------------------

CREATE PROC BANKNIFTY_FINNIFTY_ISSUE_ANG_EMAIL  
  
AS  
  
SELECT DISTINCT SCHEME_MAPPING.SP_PARTY_CODE,CONVERT(VARCHAR(11),SP_DATE_FROM,105) AS SP_DATE_FROM,  
SP_SCHEME_ID,SP_SCRIP,SP_MIN_BROKAMT,SP_MAX_BROKAMT INTO #SCHEME_MAPPING_BANKNIFTY  
FROM ANGELFO.NSEFO.DBO.SCHEME_MAPPING WITH (NOLOCK)  WHERE GETDATE() BETWEEN SP_DATE_FROM AND SP_DATE_TO  
AND SP_SCRIP = 'BANKNIFTY' AND SP_TRD_TYPE = 'TRD'  
  
SELECT DISTINCT SCHEME_MAPPING.SP_PARTY_CODE,CONVERT(VARCHAR(11),SP_DATE_FROM,105) AS SP_DATE_FROM,  
SP_SCHEME_ID,SP_SCRIP,SP_MIN_BROKAMT,SP_MAX_BROKAMT INTO #SCHEME_MAPPING_FINNIFTY  
FROM ANGELFO.NSEFO.DBO.SCHEME_MAPPING WITH (NOLOCK)  WHERE GETDATE() BETWEEN SP_DATE_FROM AND SP_DATE_TO  
AND SP_SCRIP = 'FINNIFTY' AND SP_TRD_TYPE = 'TRD'  
  
SELECT DISTINCT SCHEME_MAPPING.SP_PARTY_CODE,CONVERT(VARCHAR(11),SP_DATE_FROM,105) AS SP_DATE_FROM,  
SP_SCHEME_ID,SP_SCRIP,SP_MIN_BROKAMT,SP_MAX_BROKAMT INTO #SCHEME_MAPPING_ALL  
FROM ANGELFO.NSEFO.DBO.SCHEME_MAPPING WITH (NOLOCK)  WHERE GETDATE() BETWEEN SP_DATE_FROM AND SP_DATE_TO  
AND SP_SCRIP = 'ALL' AND SP_PARTY_CODE IN (SELECT SP_PARTY_CODE FROM #SCHEME_MAPPING_BANKNIFTY) AND SP_TRD_TYPE = 'TRD'  
  
SELECT CASE WHEN #SCHEME_MAPPING_BANKNIFTY.SP_Party_Code IS NULL THEN #SCHEME_MAPPING_FINNIFTY.SP_Party_Code  
ELSE #SCHEME_MAPPING_BANKNIFTY.SP_Party_Code END AS SP_Party_Code, #SCHEME_MAPPING_BANKNIFTY.SP_DATE_FROM AS BANKNIFTY_SP_DATE_FROM ,  
#SCHEME_MAPPING_BANKNIFTY.SP_Scheme_Id AS BANKNIFTY_ID,  
#SCHEME_MAPPING_BANKNIFTY.SP_Min_BrokAmt AS BANKNIFTY_SP_Min_BrokAmt,#SCHEME_MAPPING_BANKNIFTY.SP_Max_BrokAmt AS BANKNIFTY_SP_Max_BrokAmt,  
#SCHEME_MAPPING_FINNIFTY.SP_DATE_FROM AS FINNIFTY_SP_DATE_FROM,  
#SCHEME_MAPPING_FINNIFTY.SP_Scheme_Id AS FINNIFTY_ID,  
#SCHEME_MAPPING_FINNIFTY.SP_Min_BrokAmt AS FINNIFTY_SP_Min_BrokAmt,#SCHEME_MAPPING_FINNIFTY.SP_Max_BrokAmt AS FINNIFTY_SP_Max_BrokAmt,  
REASON = CONVERT(VARCHAR(10),'')  
INTO #CHECK  
FROM #SCHEME_MAPPING_BANKNIFTY  
FULL OUTER JOIN #SCHEME_MAPPING_FINNIFTY ON (#SCHEME_MAPPING_BANKNIFTY.SP_Party_Code = #SCHEME_MAPPING_FINNIFTY.SP_Party_Code)  
ORDER BY 1  
  
UPDATE #CHECK SET REASON = 'MISSING' WHERE (FINNIFTY_ID IS NULL OR BANKNIFTY_ID IS NULL)  
  
UPDATE #CHECK SET REASON = 'MISMATCH' WHERE FINNIFTY_ID <> BANKNIFTY_ID OR BANKNIFTY_SP_Max_BrokAmt <> FINNIFTY_SP_Max_BrokAmt OR BANKNIFTY_SP_Min_BrokAmt <> FINNIFTY_SP_Min_BrokAmt  
  
UPDATE #CHECK SET REASON = 'OKAY' WHERE REASON = ''  
  
SELECT C.*, A.SP_DATE_FROM AS SP_DATE_FROM ,A.SP_Scheme_Id AS ID,  
A.SP_Min_BrokAmt AS SP_Min_BrokAmt,A.SP_Max_BrokAmt AS SP_Max_BrokAmt,REASON_ALL = CONVERT(VARCHAR(10),'OKAY') INTO #CHECK_FINAL  
FROM #CHECK C LEFT OUTER JOIN #SCHEME_MAPPING_ALL A ON (C.SP_Party_Code = A.SP_PARTY_CODE)   ORDER BY 1   
  
UPDATE #CHECK_FINAL SET REASON_ALL = 'ISSUE' WHERE BANKNIFTY_SP_Min_BrokAmt > SP_Min_BrokAmt OR BANKNIFTY_SP_Max_BrokAmt > SP_Max_BrokAmt  
  
DELETE BANKNIFTY_FINNIFTY_ISSUE_ANG WHERE SRNO = 2  
  
INSERT INTO BANKNIFTY_FINNIFTY_ISSUE_ANG  
SELECT #CHECK_FINAL.*,2 AS SRNO FROM #CHECK_FINAL , CLIENT_BROK_DETAILS WITH (NOLOCK) WHERE (REASON <> 'OKAY' OR REASON_ALL <> 'OKAY')  
AND EXCHANGE = 'NSE' AND SEGMENT  = 'FUTURES' AND INACTIVE_FROM LIKE '%2049%' AND #CHECK_FINAL.SP_PARTY_CODE = CL_CODE  
AND IMP_STATUS = 1  

EXEC ANGELFO.NSEFO.DBO.UPD_MISS_FINNIFTY_ANG
  
DROP TABLE #SCHEME_MAPPING_BANKNIFTY  
DROP TABLE #SCHEME_MAPPING_FINNIFTY  
DROP TABLE #CHECK  
DROP TABLE #SCHEME_MAPPING_ALL  
DROP TABLE #CHECK_FINAL

  
DECLARE @bodycontent VARCHAR(max),@SUB varchar(500)                          
                           
SET @SUB = 'BANKNIFTY FINNIFTY Issues in Clients - '+ CONVERT(VARCHAR(11),GETDATE(),105)                          
                          
DECLARE @ADNAME VARCHAR(100) = 'J:\BACKOFFICE\EXPORT\' + 'BANKNIFTY_FINNIFTY_ISSUE_'+ REPLACE(CONVERT(VARCHAR(10), GETDATE(), 104), '.', '') + '.CSV'                          
--DECLARE @ADSTMT NVARCHAR(4000) = 'EXEC [MSAJAG].[DBO].[RPT_ACTIVE_CLIENT_VDT]  ''' + @RUNDATE + ''''                          
DECLARE @ADSTMT NVARCHAR(4000) = 'SELECT SP_Party_Code,BANKNIFTY_SP_DATE_FROM,BANKNIFTY_ID,BANKNIFTY_SP_Min_BrokAmt,BANKNIFTY_SP_Max_BrokAmt,FINNIFTY_SP_DATE_FROM,FINNIFTY_ID,FINNIFTY_SP_Min_BrokAmt,FINNIFTY_SP_Max_BrokAmt,REASON,SP_DATE_FROM,ID,SP_Min_BrokAmt,SP_Max_BrokAmt,REASON_ALL FROM [MSAJAG].[DBO].BANKNIFTY_FINNIFTY_ISSUE_ANG order by srno'                          
DECLARE @ADBCP VARCHAR(4000) = 'BCP "' + @ADSTMT + '" QUERYOUT "' + @ADNAME + '" -c -t"," -r"\n" -T'                          
                          
EXEC MASTER..XP_CMDSHELL @ADBCP , NO_OUTPUT                          
                          
                          
SELECT @bodycontent = '<p>Dear Team,</p>                          
<p>Please see the attached file for a BANKNIFTY FINNIFTY Issues data.</p>                          
<p>&nbsp;</p>'   + @ADNAME                  
                          
EXEC MSDB.DBO.SP_SEND_DBMAIL                           
@PROFILE_NAME='BO SUPPORT',                           
@RECIPIENTS='brokerage.modification@angelbroking.com',                          
@copy_recipients='dileswar.jena@angelbroking.com;siva.kopparapu@angelbroking.com;suresh.raut@angelbroking.com',                          
@blind_copy_recipients='ananthanarayanan.b@angelbroking.com',                          
@SUBJECT=@SUB,                          
@BODY=@BODYCONTENT,                          
--@FILE_ATTACHMENTS = @ADNAME,                          
@IMPORTANCE = 'HIGH',                          
@BODY_FORMAT ='HTML'

GO
