-- Object: PROCEDURE dbo.API_BANK_FUNDS_REPORTING
-- Server: 10.253.33.91 | DB: MSAJAG
--------------------------------------------------



--exec API_BANK_FUNDS_REPORTING 'jun  1 2021', 'jun  5 2021', '0405072361'

--EXEC ANGELFO.BBO_FA.DBO.BANK_FUNDS_REPORTING 'jun  1 2021','jun  5 2021','BSE','MFSS','03013'

--EXEC API_BANK_FUNDS_REPORTING 'jan  1 2021', 'jan 10 2021','26','26'
--Exec API_BANK_FUNDS_REPORTING 'JUN  1 2021','Dec  6 2018'

--exec API_BANK_FUNDS_REPORTING 'jun  1 2021', 'jun  1 2021', '03026', 'NSE~CAPITAL'
--exec API_BANK_FUNDS_REPORTING 'jun  1 2021', 'jun  1 2021', '0405072361', 'NSE~CAPITAL'

--select * from BANK_PURPOSE_MASTER where bankcode = '03026'

CREATE PROCEDURE [dbo].[API_BANK_FUNDS_REPORTING]
	@FR_DATE VARCHAR(11),
	@TO_DATE VARCHAR(11),
	@BANK_CODE VARCHAR(30) ,
	@BANK_CODE1 VARCHAR(30) = '',
	@EXCSEGMENT VARCHAR(500) = '' ,
	@DUMMY VARCHAR(500)='' 
AS

SET @BANK_CODE1 = @BANK_CODE
 
CREATE TABLE [DBO].[#BBDBNAME_LIST] (
	ACCOUNTDB VARCHAR(20)
	,EXCHANGE VARCHAR(6)
	,SEGMENT VARCHAR(10)
	,ACCOUNTSERVER VARCHAR(50)
	,SHAREDB VARCHAR(20)
	) ON [PRIMARY]

DECLARE
	@DB1 VARCHAR(1000)
	,@SQL VARCHAR(5000)
	,@SEGORD1 SMALLINT
	,@MAINREC1 AS CURSOR
	,@ACCOUNTDB1 VARCHAR(20)
	,@SHAREDB1 VARCHAR(20)
	,@ACCOUNTSVR1 VARCHAR(50)
	,@EXCHANGE1 VARCHAR(15)
	,@SEGMENT1 VARCHAR(15)
	,@ACCOUNTACC VARCHAR(30)



SELECT @EXCSEGMENT = case when len(@BANK_CODE) > 9 then EXCHANGE + '~' + SEGMENT else '' end, @ACCOUNTACC = ACCOUNTNO, @BANK_CODE = BANKCODE FROM BANK_PURPOSE_MASTER WHERE (BANKCODE = @BANK_CODE OR right(ACCOUNTNO, 10) = @BANK_CODE)

--select @EXCSEGMENT, @BANK_CODE, @ACCOUNTACC

IF @EXCSEGMENT <> ''
	SELECT @DB1 = " INSERT INTO #BBDBNAME_LIST SELECT ACCOUNTDB, EXCHANGE, SEGMENT, ACCOUNTSERVER, SHAREDB FROM PRADNYA.DBO.VW_REPORTING_MULTICOMPANY_ALL (NOLOCK) WHERE EXCHANGE+'~'+SEGMENT IN ('" + REPLACE(@EXCSEGMENT, ',', ''',''') + "') ORDER BY EXCHANGE "
ELSE
	SELECT @DB1 = " INSERT INTO #BBDBNAME_LIST SELECT ACCOUNTDB, EXCHANGE, SEGMENT, ACCOUNTSERVER, SHAREDB FROM PRADNYA.DBO.VW_REPORTING_MULTICOMPANY_ALL (NOLOCK) ORDER BY EXCHANGE "

--PRINT @DB1
EXEC (@DB1)




DECLARE @FILENAME   VARCHAR(50)
DECLARE @BATCHNO	INT  
DECLARE @MEMBERCODE VARCHAR(20)
DECLARE @MEMBERNAME	VARCHAR(500)

SELECT @MEMBERCODE = MEMBERCODE, @MEMBERNAME = ISNULL(LTRIM(RTRIM(COMPANY)),'') FROM OWNER (NOLOCK)
SELECT @BATCHNO = ISNULL(MAX(FLDBATCHNO),0)+1 FROM ASIANFILEBATCHNO  
WHERE FLDFILENO = 'BB'  
AND LEFT(FLDFILEDATE,11) = LEFT(GETDATE(),11)
  
IF @BATCHNO = 1  
BEGIN  
	INSERT INTO ASIANFILEBATCHNO VALUES ('BB', @BATCHNO, GETDATE(), GETDATE())  
END  
ELSE  
BEGIN  
	UPDATE ASIANFILEBATCHNO SET FLDBATCHNO = @BATCHNO WHERE FLDFILENO = 'BB' AND LEFT(FLDFILEDATE,11) = LEFT(GETDATE(),11)
END  
  
SET	@FILENAME = @MEMBERCODE + '_BB_' + REPLACE(CONVERT(VARCHAR,GETDATE(),103),'/','') + '_' + RIGHT('00'+CONVERT(VARCHAR,@BATCHNO),2) 




CREATE TABLE #BBLEDGER_PL
(
	VDT DATETIME,
	EDT DATETIME,
	LONG_NAME VARCHAR(150),
	BANK_ACC_NO VARCHAR(40),
	UCC_CODE VARCHAR(30),
	CLTCODE VARCHAR(10),
	CLIENT_PAN VARCHAR(50),
	NARRATION VARCHAR(500),
	VNO VARCHAR(12),
	VTYP INT,
	SETT_NO VARCHAR(10),
	CHQ_NO VARCHAR(30),
	DRAMOUNT MONEY,
	CRAMOUNT MONEY,
	RUNNING_BALANCE MONEY,
	OPBAL MONEY,
	PDT DATETIME,
	BANK_CODE VARCHAR(10),
	EXCHANGE VARCHAR(10),
	SEGMENT VARCHAR(10)
)


SET @MAINREC1 = CURSOR
FOR

SELECT ACCOUNTDB
	,EXCHANGE
	,SEGMENT
	,ACCOUNTSERVER
	,SHAREDB
FROM #BBDBNAME_LIST

SET @SEGORD1 = 1

OPEN @MAINREC1

FETCH NEXT
FROM @MAINREC1
INTO @ACCOUNTDB1
	,@EXCHANGE1
	,@SEGMENT1
	,@ACCOUNTSVR1
	,@SHAREDB1

WHILE @@FETCH_STATUS = 0
BEGIN

	SET @SQL = "INSERT INTO #BBLEDGER_PL EXEC " + @ACCOUNTSVR1 + "." + @ACCOUNTDB1 + ".DBO.BANK_FUNDS_REPORTING '" + @FR_DATE + "','" + @TO_DATE + "','"  + @EXCHANGE1 + "','"  + @SEGMENT1 + "','"  + @BANK_CODE + "'"
	PRINT @SQL
	EXEC (@SQL)

	
FETCH NEXT
	FROM @MAINREC1
	INTO @ACCOUNTDB1
		,@EXCHANGE1
		,@SEGMENT1
		,@ACCOUNTSVR1
		,@SHAREDB1
END

CLOSE @MAINREC1



/* FOR MFSS SEGMENT OPENING BALANCE */

--INSERT INTO #BBLEDGER_PL
--SELECT @FR_DATE + ' 23:59:59', @FR_DATE+ ' 23:59:59', '','','',BANK_CODE,'', NARRATION = 'OPENING BALANCE','',18,'','',
--		CASE WHEN SUM(OPBAL) < 0 THEN SUM(OPBAL) ELSE 0 END , 
--		CASE WHEN SUM(OPBAL) >= 0 THEN SUM(OPBAL) ELSE 0 END , 
--		SUM(CRAMOUNT + DRAMOUNT), 0,@TO_DATE + ' 23:59:59' ,BANK_CODE,EXCHANGE, SEGMENT
--FROM #BBLEDGER_PL
--WHERE SEGMENT = 'MFSS'
--GROUP BY BANK_CODE, EXCHANGE, SEGMENT


/* FOR MFSS SEGMENT OPENING BALANCE */

/* CODE FOR CB */


INSERT INTO #BBLEDGER_PL
SELECT @TO_DATE + ' 23:59:59', @TO_DATE + ' 23:59:59', '','','',BANK_CODE,'', NARRATION = 'Closing Balance','',50,'','',
		CASE WHEN SUM(CRAMOUNT + DRAMOUNT) < 0 THEN SUM(CRAMOUNT + DRAMOUNT) ELSE 0 END , 
		CASE WHEN SUM(CRAMOUNT + DRAMOUNT) >= 0 THEN SUM(CRAMOUNT + DRAMOUNT) ELSE 0 END , 
		SUM(CRAMOUNT + DRAMOUNT), 0,@TO_DATE + ' 23:59:59' ,BANK_CODE,EXCHANGE, SEGMENT
FROM #BBLEDGER_PL
GROUP BY BANK_CODE, EXCHANGE, SEGMENT

--SELECT * FROM #BBLEDGER_PL where vtyp = 18 
--return 
/* CODE FOR CB */

CREATE TABLE #BBLEDGER_PL_DETAILS_FINAL
(
	VDT DATETIME,
	EDT DATETIME,
	LONG_NAME VARCHAR(100),
	BANK_ACC_NO VARCHAR(40),
	UCC_CODE VARCHAR(12),
	CLTCODE VARCHAR(10),
	CLIENT_PAN VARCHAR(50),
	NARRATION VARCHAR(500),
	VNO VARCHAR(12),
	VTYP INT,
	SETT_NO VARCHAR(10),
	CHQ_NO VARCHAR(30),
	DRAMOUNT MONEY,
	CRAMOUNT MONEY,
	RUNNING_BALANCE MONEY,
	OPBAL MONEY,
	PDT DATETIME,
	BANK_CODE VARCHAR(10),
	EXCHANGE VARCHAR(10),
	SEGMENT VARCHAR(10),
	PURPOSE VARCHAR(500),
	SNO INT IDENTITY(1, 1)
)

INSERT INTO #BBLEDGER_PL_DETAILS_FINAL
SELECT B.*, PURPOSE = PURPOSE_REMARKS FROM #BBLEDGER_PL B, PURPOSE_MASTER P WHERE B.VTYP = P.VTYP AND NARRATION = 'OPENING BALANCE'
ORDER BY BANK_CODE, /*EXCHANGE, SEGMENT,*/ VDT, PDT

INSERT INTO #BBLEDGER_PL_DETAILS_FINAL
SELECT B.*, PURPOSE = PURPOSE_REMARKS FROM #BBLEDGER_PL B, PURPOSE_MASTER P WHERE B.VTYP = P.VTYP  AND NARRATION <> 'OPENING BALANCE'
ORDER BY BANK_CODE, /*EXCHANGE, SEGMENT,*/ VDT, PDT

--UPDATE L SET RUNNING_BALANCE = OPBAL + (SELECT SUM(CRAMOUNT + DRAMOUNT) FROM #BBLEDGER_PL_DETAILS_FINAL L1 WHERE L1.BANK_CODE = L.BANK_CODE AND L1.EXCHANGE = L.EXCHANGE AND L1.SEGMENT = L.SEGMENT AND L1.SNO <= L.SNO) FROM #BBLEDGER_PL_DETAILS_FINAL L
--WHERE NARRATION <> 'CLOSING BALANCE'


CREATE CLUSTERED INDEX BBLEDGER1 ON #BBLEDGER_PL_DETAILS_FINAL(SNO) 

CREATE INDEX BBLEDGER ON #BBLEDGER_PL_DETAILS_FINAL(BANK_CODE,SNO,NARRATION) 

UPDATE #BBLEDGER_PL_DETAILS_FINAL SET RUNNING_BALANCE = L.RUNNING_BAL FROM
(SELECT BANK_CODE, SNO, RUNNING_BAL = SUM(CRAMOUNT + DRAMOUNT)
OVER(PARTITION BY BANK_CODE ORDER BY SNO)
FROM #BBLEDGER_PL_DETAILS_FINAL) L WHERE L.BANK_CODE = #BBLEDGER_PL_DETAILS_FINAL.BANK_CODE AND L.SNO = #BBLEDGER_PL_DETAILS_FINAL.SNO
AND NARRATION <> 'CLOSING BALANCE'




DECLARE
	@MEMBER_CODE VARCHAR(200),
	@BANK_NAME VARCHAR(100),
	@ACCCODE VARCHAR(25)

SELECT @MEMBER_CODE = COMPANY FROM OWNER

--SELECT @BANK_NAME = LONGNAME, @ACCCODE = ACCDTLS FROM ACMAST_DETAILS WHERE CLTCODE = @BANK_CODE

--SELECT * FROM #BBLEDGER_PL_DETAILS_FINAL

--NEED TO APPLY THE LOGIC OF RUNNING BALANCE IN _WRAPPER PROCEDURE 
CREATE TABLE #REPORT_DATA
(
	BANK_CODE VARCHAR(10),
	EXCHANGE VARCHAR(10),
	SEGMENT VARCHAR(10),
	REPORTDATA VARCHAR(2000),
	SNO INT IDENTITY(1, 1)
)


--SELECT * FROM ACMAST_DETAILS A INNER JOIN  #BBLEDGER_PL_DETAILS_FINAL L ON  A.CLTCODE = L.BANK_CODE AND A.EXCHANGE = L.EXCHANGE AND A.SEGMENT = L.SEGMENT
 
--SELECT *
--FROM ACMAST_DETAILS A 
-- where EXISTS(SELECT BANK_CODE FROM #BBLEDGER_PL_DETAILS_FINAL L WHERE A.CLTCODE = L.BANK_CODE AND A.EXCHANGE = L.EXCHANGE AND A.SEGMENT = L.SEGMENT)


INSERT INTO #REPORT_DATA
SELECT BANKCODE =  '', EXCHANGE ='' , SEGMENT='' , REPORTDATA = 'MEMBER NAME,PERIOD,ACCOUNT NAME AND NUMBER,ACCOUNT TYPE,EXCHANGE,SEGMENT TYPE'
UNION ALL
/*SELECT DISTINCT BANKCODE = A.CLTCODE, A.EXCHANGE, A.SEGMENT, REPORTDATA = @MEMBER_CODE + ',' + REPLACE(CONVERT(VARCHAR, CONVERT(DATETIME, @FR_DATE), 103), '/', '-') + ' TO ' +
	REPLACE(CONVERT(VARCHAR, CONVERT(DATETIME, @TO_DATE), 103), '/', '-') + ',' 
    + A.LONGNAME + ',' +  ISNULL(ACCOUNTNO,'') + ','
    + ISNULL(BK.PURPOSE,'')+ ',' +
    --+  ISNULL((CASE WHEN A.EXCHANGE='NSE' AND A.SEGMENT='FUTURES' THEN 'FO' ELSE A.EXCHANGE END ),'')+ ',' +
	+  ISNULL( A.EXCHANGE ,'')+ ',' +
    CASE 
	WHEN A.EXCHANGE+A.SEGMENT IN ('NSEFUTURES','BSEFUTURES') THEN  'FO'
	WHEN A.EXCHANGE+A.SEGMENT IN ('BSECAPITAL','MTFMTF') THEN  'CM'		
	WHEN A.EXCHANGE+A.SEGMENT IN ('NSXFUTURES','BSXFUTURES','MCDFUTURES') THEN  'CDS'
	WHEN A.EXCHANGE+A.SEGMENT IN ('NSECAPITAL') /*AND  BK.SEXCHANGE='DEBT'*/ THEN  'CM'
	WHEN A.EXCHANGE+A.SEGMENT IN ('BSECAPITAL') /*AND  BK.SEXCHANGE='CDS'*/ THEN  'CM'	ELSE 'CM' 	
	END
---FROM ACMAST_DETAILS A 
--inner JOIN 
BANK_PURPOSE_MASTER BK
/*ON A.CLTCODE = BK.BANKCODE 
AND A.EXCHANGE= BK.EXCHANGE
AND A.SEGMENT= BK.SEGMENT*/
--and bk.ACCOUNTNO = @ACCOUNTACC
WHERE EXISTS(SELECT BANK_CODE FROM #BBLEDGER_PL_DETAILS_FINAL L 
WHERE A.CLTCODE = L.BANK_CODE AND BK.EXCHANGE = L.EXCHANGE AND bk.SEGMENT = L.SEGMENT /*and bk.ACCOUNTNO = l.BANK_ACC_NO*/ AND A.EXCHANGE NOT IN ('MCX','NCX','NSP') AND A.SEGMENT NOT IN ('SLBS'))*/

SELECT DISTINCT BANKCODE, EXCHANGE, SEGMENT, REPORTDATA = @MEMBER_CODE + ',' + REPLACE(CONVERT(VARCHAR, CONVERT(DATETIME, @FR_DATE), 103), '/', '-') + ' TO ' +
	REPLACE(CONVERT(VARCHAR, CONVERT(DATETIME, @TO_DATE), 103), '/', '-') + ',' 
    + BANKNAME + ',' +  ISNULL(ACCOUNTNO,'') + ','
    + ISNULL(BK.PURPOSE,'')+ ',' +
    --+  ISNULL((CASE WHEN A.EXCHANGE='NSE' AND A.SEGMENT='FUTURES' THEN 'FO' ELSE A.EXCHANGE END ),'')+ ',' +
	+  ISNULL( EXCHANGE ,'')+ ',' +
    CASE 
	WHEN EXCHANGE+SEGMENT IN ('NSEFUTURES','BSEFUTURES','MCXFUTURES','NCXFUTURES','NCEFUTURES') THEN  'FO'
	WHEN EXCHANGE+SEGMENT IN ('BSECAPITAL','MTFMTF') THEN  'CM'		
	WHEN EXCHANGE+SEGMENT IN ('NSXFUTURES','BSXFUTURES','MCDFUTURES') THEN  'CDS'
	WHEN EXCHANGE+SEGMENT IN ('NSECAPITAL') /*AND  BK.SEXCHANGE='DEBT'*/ THEN  'CM'
	WHEN EXCHANGE+SEGMENT IN ('BSECAPITAL') /*AND  BK.SEXCHANGE='CDS'*/ THEN  'CM'	
	WHEN EXCHANGE+SEGMENT IN ('BSEMFSS','NSEMFSS') /*AND  BK.SEXCHANGE='CDS'*/ THEN  'MFSS'	
	ELSE 'CM' 	
	END
FROM 
BANK_PURPOSE_MASTER BK
WHERE EXISTS(SELECT BANK_CODE FROM #BBLEDGER_PL_DETAILS_FINAL L 
WHERE BANKCODE = L.BANK_CODE AND BK.EXCHANGE = L.EXCHANGE AND bk.SEGMENT = L.SEGMENT /*and bk.ACCOUNTNO = l.BANK_ACC_NO AND BK.EXCHANGE NOT IN ('MCX','NCX','NSP') AND BK.SEGMENT NOT IN ('SLBS')*/)


INSERT INTO #REPORT_DATA
SELECT  TOP 1 BANK_CODE,EXCHANGE,SEGMENT,REPORTDATA = 'DATE	,VALUE DATE	,ACCOUNT NAME 	,BANK ACCOUNT NO.	,UNIQUE CLIENT CODE(UCC)	,BACK OFFICE CLIENT CODE	,CLIENT PAN	,NARRATION 	,VOUCHER NO. ,SETTLEMENT NO. ,REFERENCE NUMBER	,PAYMENT (Rs.)	,RECEIPT(Rs.),BALANCE(Rs.)	,PURPOSE'	
--,EXCHANGE	,SEGMENT'
FROM #REPORT_DATA	 
WHERE Bank_Code <> ""
ORDER BY BANK_CODE,sno, EXCHANGE,SEGMENT

INSERT INTO #REPORT_DATA
SELECT ISNULL(BANK_CODE,''), ISNULL(EXCHANGE,''), ISNULL(SEGMENT,''), REPORTDATA = ISNULL(REPLACE(CONVERT(VARCHAR(10), VDT, 103), '/', '-') ,'')+ ',' + ISNULL(REPLACE(CONVERT(VARCHAR(10), EDT, 103), '/', '-'),'') + ',' + ISNULL(LONG_NAME,'') + ',' + ISNULL(BANK_ACC_NO,'') + ',' + ISNULL(UCC_CODE,'') + ',' + ISNULL(CLTCODE,'') + ',' + ISNULL(CLIENT_PAN,'') + ',' + ISNULL(REPLACE(NARRATION, ',', ''),'') + ',' + ISNULL(VNO,'') + ',' + ISNULL(SETT_NO, '') + ',' + ISNULL(CHQ_NO, '') + ',' + ISNULL(CONVERT(VARCHAR, ABS(DRAMOUNT)),'') + ',' + ISNULL(CONVERT(VARCHAR, CRAMOUNT),'') + ',' + ISNULL(CONVERT(VARCHAR, RUNNING_BALANCE),'') + ',' + ISNULL(PURPOSE,'') /*+ ',' + ISNULL(EXCHANGE,'')+ ','+ISNULL(SEGMENT,'') */
FROM #BBLEDGER_PL_DETAILS_FINAL WHERE NARRATION = 'OPENING BALANCE' ORDER BY  BANK_CODE, SNO

INSERT INTO #REPORT_DATA
SELECT ISNULL(BANK_CODE,''), ISNULL(EXCHANGE,''), ISNULL(SEGMENT,''), REPORTDATA = ISNULL(REPLACE(CONVERT(VARCHAR(10), VDT, 103), '/', '-') ,'')+ ',' + ISNULL(REPLACE(CONVERT(VARCHAR(10), EDT, 103), '/', '-'),'') + ',' + ISNULL(LONG_NAME,'') + ',' + ISNULL(BANK_ACC_NO,'') + ',' + ISNULL(UCC_CODE,'') + ',' + ISNULL(CLTCODE,'') + ',' + ISNULL(CLIENT_PAN,'') + ',' + ISNULL(REPLACE(NARRATION, ',', ''),'') + ',' + ISNULL(VNO,'') + ',' + ISNULL(SETT_NO, '') + ',' + ISNULL(CHQ_NO, '') + ',' + ISNULL(CONVERT(VARCHAR, ABS(DRAMOUNT)),'') + ',' + ISNULL(CONVERT(VARCHAR, CRAMOUNT),'') + ',' + ISNULL(CONVERT(VARCHAR, RUNNING_BALANCE),'') + ',' + ISNULL(PURPOSE,'') /*+ ',' + ISNULL(EXCHANGE,'')+ ','+ISNULL(SEGMENT,'') */
FROM #BBLEDGER_PL_DETAILS_FINAL WHERE NARRATION <> 'OPENING BALANCE' ORDER BY  BANK_CODE, SNO


SELECT /*FILENAME = @FILENAME,*/ REPORTDATA FROM #REPORT_DATA ORDER BY BANK_CODE, SNO

GO
