-- Object: PROCEDURE dbo.PROC_NCL_SHORT_CALC_BAK_01122023
-- Server: 10.253.33.91 | DB: MSAJAG
--------------------------------------------------

/*
ALTER TABLE TBL_SHORT_ALLOC_ADJUST ADD INDICATOR VARCHAR(3)
*/

CREATE PROC [dbo].[PROC_NCL_SHORT_CALC_BAK_01122023]
(
	@MARGINDATE	VARCHAR(11)
)
AS
/*
ALTER TABLE TBL_SHORT_EOD_WORKING
ADD INDICATOR VARCHAR(2)
GO
UPDATE TBL_SHORT_EOD_WORKING SET INDICATOR = ISNULL(INDICATOR,'E')
*/

-- EXEC PROC_NCL_SHORT_CALC  'FEB 13 2023'

SELECT DISTINCT EXCHANGE,SEGMENT,PARTY_CODE=CLIENTCODE,ELIGIBLE_COLLATERAL_EOD=ISNULL(ELIGIBLE_COLLATERAL_EOD,0), 
MARGIN=CONVERT(NUMERIC(18,4),0), EOD_SHORT=CONVERT(NUMERIC(18,4),0),INDICATOR=CONVERT(VARCHAR(2),'E') INTO #DATA FROM TBL_CLIENT_COLL_RECO
WHERE TRANSDATE=@MARGINDATE
AND EXCHANGE IN ('MCX','NCX') 

INSERT INTO #DATA
SELECT EXCHANGE='MCX', SEGMENT='FUTURES',PARTY_CODE,0,REGULARMARGIN,EOD_SHORT=CONVERT(NUMERIC(18,4),0),INDICATOR='E'
FROM ANGELCOMMODITY.MCDX.DBO.FOMARGINNEW_DATA M
WHERE MDATE=@MARGINDATE 

INSERT INTO #DATA
SELECT EXCHANGE='MCX',SEGMENT='FUTURES',PARTY_CODE=CLIENT_CODE, ELIGIBLE_COLLATERAL_EOD=0,
MARGIN=0,EOD_SHORT=SUM(EOD_SHORT_ALLOC),INDICATOR='E'
FROM TBL_MCX_SHORT_ALLOC WHERE MARGINDATE=@MARGINDATE
GROUP BY CLIENT_CODE 

INSERT INTO #DATA
SELECT EXCHANGE='MCX',SEGMENT='FUTURES',PARTY_CODE=CLIENT_CODE, ELIGIBLE_COLLATERAL_EOD=SUM(CLT_OTHER_COLL+CLT_MARGIN_ALLOC-TOT_UPFRONT_MARGIN),
MARGIN=0,EOD_SHORT=0,INDICATOR
FROM TBL_MCX_SHORT_ALLOC_INTRADAY WHERE MARGINDATE=@MARGINDATE
GROUP BY CLIENT_CODE, INDICATOR
HAVING SUM(CLT_OTHER_COLL+CLT_MARGIN_ALLOC-TOT_UPFRONT_MARGIN) > 0 

INSERT INTO #DATA
SELECT EXCHANGE='NCX',SEGMENT='FUTURES',PARTY_CODE=CLIENT_CODE, ELIGIBLE_COLLATERAL_EOD=SUM(COLLATERAL_VALUE_SNAPSHOT-INITIALMARGIN-ELM_MARGIN),
MARGIN=0,EOD_SHORT=0,INDICATOR
FROM TBL_NCX_SHORT_ALLOC_INTRADAY WHERE MARGINDATE=@MARGINDATE
GROUP BY CLIENT_CODE, INDICATOR
HAVING SUM(COLLATERAL_VALUE_SNAPSHOT) > 0 

SELECT CLIENT_CODE, SHORT_ALLOC, INDICATOR INTO #MCXPEAKSHORT 
FROM TBL_MCX_SHORT_ALLOC_INTRADAY
WHERE MARGINDATE=@MARGINDATE
AND SHORT_ALLOC > 0 

SELECT P.CLIENT_CODE, P.SHORT_ALLOC, INDICATOR = MIN(INDICATOR) 
INTO #MCXPEAKSHORT_FINAL FROM #MCXPEAKSHORT P,
(SELECT CLIENT_CODE, SHORT_ALLOC = MAX(SHORT_ALLOC) FROM #MCXPEAKSHORT
GROUP BY CLIENT_CODE ) A
WHERE P.CLIENT_CODE = A.CLIENT_CODE
AND P.SHORT_ALLOC = A.SHORT_ALLOC
GROUP BY P.CLIENT_CODE, P.SHORT_ALLOC

SELECT *, INDICATOR=CONVERT(VARCHAR(2),'') INTO #TBL_MCX_SHORT_ALLOC_INTRA
FROM TBL_MCX_SHORT_ALLOC_INTRA
WHERE MARGINDATE=@MARGINDATE

UPDATE #TBL_MCX_SHORT_ALLOC_INTRA SET INDICATOR = P.INDICATOR
FROM #MCXPEAKSHORT_FINAL P
WHERE #TBL_MCX_SHORT_ALLOC_INTRA.CLIENT_CODE = P.CLIENT_CODE
AND #TBL_MCX_SHORT_ALLOC_INTRA.EOD_SHORT_ALLOC = P.SHORT_ALLOC

INSERT INTO #DATA
SELECT EXCHANGE='MCX',SEGMENT='FUTURES',PARTY_CODE=CLIENT_CODE, ELIGIBLE_COLLATERAL_EOD=0,
MARGIN=0,EOD_SHORT=EOD_SHORT_ALLOC,INDICATOR
FROM #TBL_MCX_SHORT_ALLOC_INTRA WHERE MARGINDATE=@MARGINDATE 
AND EOD_SHORT_ALLOC > 0 AND INDICATOR <> ''



SELECT CLIENT_CODE, SHORT_ALLOC=SHORT_ALLOCATION_SNAPSHOT, INDICATOR INTO #NCXPEAKSHORT 
FROM TBL_NCX_SHORT_ALLOC_INTRADAY
WHERE MARGINDATE=@MARGINDATE
AND SHORT_ALLOCATION_SNAPSHOT > 0 

UPDATE #NCXPEAKSHORT SET INDICATOR = RIGHT('00'+INDICATOR,2)

SELECT P.CLIENT_CODE, P.SHORT_ALLOC, INDICATOR = MIN(INDICATOR) 
INTO #NCXPEAKSHORT_FINAL FROM #NCXPEAKSHORT P,
(SELECT CLIENT_CODE, SHORT_ALLOC = MAX(SHORT_ALLOC) FROM #NCXPEAKSHORT
GROUP BY CLIENT_CODE ) A
WHERE P.CLIENT_CODE = A.CLIENT_CODE
AND P.SHORT_ALLOC = A.SHORT_ALLOC
GROUP BY P.CLIENT_CODE, P.SHORT_ALLOC

SELECT *, INDICATOR=CONVERT(VARCHAR(2),'') INTO #TBL_NCX_SHORT_ALLOC_INTRA
FROM TBL_NCX_SHORT_ALLOC_INTRA
WHERE MARGINDATE=@MARGINDATE

UPDATE #TBL_NCX_SHORT_ALLOC_INTRA SET INDICATOR = P.INDICATOR
FROM #NCXPEAKSHORT_FINAL P
WHERE #TBL_NCX_SHORT_ALLOC_INTRA.CLIENT_CODE = P.CLIENT_CODE
AND #TBL_NCX_SHORT_ALLOC_INTRA.EOD_SHORT_ALLOC = P.SHORT_ALLOC

INSERT INTO #DATA
SELECT EXCHANGE='NCX',SEGMENT='FUTURES',PARTY_CODE=CLIENT_CODE, ELIGIBLE_COLLATERAL_EOD=0,
MARGIN=0,EOD_SHORT=EOD_SHORT_ALLOC,INDICATOR
FROM #TBL_NCX_SHORT_ALLOC_INTRA WHERE MARGINDATE=@MARGINDATE 
AND EOD_SHORT_ALLOC > 0 AND INDICATOR <> ''


INSERT INTO #DATA
SELECT EXCHANGE='NCX', SEGMENT='FUTURES',PARTY_CODE,0,INITIALMARGIN,EOD_SHORT=TOTAL_EOD_SHORT,INDICATOR='E'
FROM ANGELCOMMODITY.NCDX.DBO.FOMARGINNEW_DATA M
WHERE MDATE=@MARGINDATE 

INSERT INTO #DATA
SELECT EXCHANGE='NCL',SEGMENT='NCL',PARTY_CODE=CLIENT_CODE, 
ELIGIBLE_COLLATERAL_EOD=0,
MARGIN=SUM(MARGIN_REQ),EOD_SHORT=SUM(EOD_SHORT_ALLOC),INDICATOR
FROM TBL_SHORT_ALLOC WHERE MARGINDATE=@MARGINDATE
GROUP BY CLIENT_CODE ,INDICATOR

INSERT INTO #DATA
SELECT EXCHANGE='NCL',SEGMENT='NCL',PARTY_CODE=CLIENT_CODE, 
ELIGIBLE_COLLATERAL_EOD=SUM(Total_value_Coll-MARGIN_REQ),
MARGIN=0,EOD_SHORT=0,INDICATOR
FROM TBL_SHORT_ALLOC_INTRADAY WHERE MARGINDATE=@MARGINDATE
GROUP BY CLIENT_CODE ,INDICATOR
HAVING SUM(TOTAL_VALUE_COLL-MARGIN_REQ) > 0 

UPDATE #DATA SET INDICATOR = RIGHT('00'+INDICATOR,2) WHERE INDICATOR <> 'E'

INSERT INTO #DATA
SELECT EXCHANGE='NCL',SEGMENT='NCL',PARTY_CODE=CLIENT_CODE, 
ELIGIBLE_COLLATERAL_EOD=SUM(Total_value_Coll-MARGIN_REQ),
MARGIN=0,EOD_SHORT=0,INDICATOR='05'
FROM TBL_SHORT_ALLOC_INTRADAY WHERE MARGINDATE=@MARGINDATE
AND INDICATOR = '04'
GROUP BY CLIENT_CODE ,INDICATOR
HAVING SUM(TOTAL_VALUE_COLL-MARGIN_REQ) > 0 

INSERT INTO #DATA
SELECT EXCHANGE='NCL',SEGMENT='NCL',PARTY_CODE=CLIENT_CODE, 
ELIGIBLE_COLLATERAL_EOD=SUM(Total_value_Coll-MARGIN_REQ),
MARGIN=0,EOD_SHORT=0,INDICATOR='06'
FROM TBL_SHORT_ALLOC_INTRADAY WHERE MARGINDATE=@MARGINDATE
AND INDICATOR = '04'
GROUP BY CLIENT_CODE ,INDICATOR
HAVING SUM(TOTAL_VALUE_COLL-MARGIN_REQ) > 0 

INSERT INTO #DATA
SELECT EXCHANGE='NCL',SEGMENT='NCL',PARTY_CODE=CLIENT_CODE, 
ELIGIBLE_COLLATERAL_EOD=SUM(Total_value_Coll-MARGIN_REQ),
MARGIN=0,EOD_SHORT=0,INDICATOR='07'
FROM TBL_SHORT_ALLOC_INTRADAY WHERE MARGINDATE=@MARGINDATE
AND INDICATOR = '04'
GROUP BY CLIENT_CODE ,INDICATOR
HAVING SUM(TOTAL_VALUE_COLL-MARGIN_REQ) > 0 

INSERT INTO #DATA
SELECT EXCHANGE='NCL',SEGMENT='NCL',PARTY_CODE=CLIENT_CODE, 
ELIGIBLE_COLLATERAL_EOD=SUM(Total_value_Coll-MARGIN_REQ),
MARGIN=0,EOD_SHORT=0,INDICATOR='08'
FROM TBL_SHORT_ALLOC_INTRADAY WHERE MARGINDATE=@MARGINDATE
AND INDICATOR = '04'
GROUP BY CLIENT_CODE ,INDICATOR
HAVING SUM(TOTAL_VALUE_COLL-MARGIN_REQ) > 0 

CREATE CLUSTERED INDEX IDXSEG ON #DATA
(
	EXCHANGE,SEGMENT
)

INSERT INTO #DATA
SELECT EXCHANGE='NCL',SEGMENT='NCL',PARTY_CODE, ELIGIBLE_COLLATERAL_EOD=SUM(ELIGIBLE_AMT+UTILIZED_AMT),
MARGIN=0,EOD_SHORT=0,INDICATOR ='E'
FROM TBL_CC01_DATA WHERE TRANSDATE =@MARGINDATE
AND EXCHANGE IN ('NSE','NSX','NCX')
--AND PARTY_CODE NOT IN (SELECT PARTY_CODE FROM #DATA WHERE EXCHANGE='NCL' AND SEGMENT='NCL')
GROUP BY PARTY_CODE 

SELECT EXCHANGE,SEGMENT,PARTY_CODE,
EXCESS_COLLATERAL=(CASE WHEN SUM(ELIGIBLE_COLLATERAL_EOD)-SUM(MARGIN) > 0 
					    THEN SUM(ELIGIBLE_COLLATERAL_EOD)-SUM(MARGIN) 
						ELSE 0 END),EOD_SHORT=SUM(EOD_SHORT),
ADJUST_AMT=CONVERT(NUMERIC(18,2),0), ADJUST_EXCHG_SEG=CONVERT(VARCHAR(15),''),
INDICATOR
INTO #DATA_NEW
FROM #DATA  
GROUP BY EXCHANGE, SEGMENT,PARTY_CODE,INDICATOR
HAVING SUM(ELIGIBLE_COLLATERAL_EOD)-SUM(MARGIN) > 0 OR SUM(EOD_SHORT) > 0 

SELECT * INTO #SPLIT FROM #DATA_NEW
WHERE 1 = 2 

SELECT * INTO #ADJUST FROM #DATA_NEW
WHERE 1 = 2 

SELECT * INTO #ADJUST_NEW FROM #DATA_NEW
WHERE 1 = 2 
 
DECLARE @ALLOCCUR CURSOR,
		@SEGCUR		CURSOR,
		@EXCHANGE	VARCHAR(3),
		@SEGMENT	VARCHAR(7),
		@NEWEXCHANGE	VARCHAR(3),
		@NEWSEGMENT	VARCHAR(7),
		@INDICATOR VARCHAR(2)

SET @ALLOCCUR = CURSOR FOR 
SELECT DISTINCT EXCHANGE,SEGMENT,INDICATOR FROM #DATA_NEW WHERE EOD_SHORT > 0 
OPEN @ALLOCCUR 
FETCH NEXT FROM @ALLOCCUR INTO @EXCHANGE,@SEGMENT,@INDICATOR
WHILE @@FETCH_STATUS = 0 
BEGIN 
	SET @SEGCUR = CURSOR FOR 
	SELECT DISTINCT EXCHANGE,SEGMENT FROM #DATA_NEW
	WHERE NOT (EXCHANGE = @EXCHANGE AND SEGMENT = @SEGMENT)
	AND EXCESS_COLLATERAL + ADJUST_AMT  > 0
	AND INDICATOR = @INDICATOR
	OPEN @SEGCUR 
	FETCH NEXT FROM @SEGCUR INTO @NEWEXCHANGE,@NEWSEGMENT 
	WHILE @@FETCH_STATUS = 0 
	BEGIN
		TRUNCATE TABLE #ADJUST
		TRUNCATE TABLE #ADJUST_NEW

		INSERT INTO #ADJUST 
		SELECT * FROM #DATA_NEW D
		WHERE D.EXCHANGE = @EXCHANGE
		AND D.SEGMENT = @SEGMENT	
		AND INDICATOR = @INDICATOR	
		AND EOD_SHORT - ADJUST_AMT > 0   
		AND ADJUST_EXCHG_SEG = ''

		INSERT INTO #ADJUST_NEW 
		SELECT * FROM #DATA_NEW D
		WHERE D.EXCHANGE = @NEWEXCHANGE
		AND D.SEGMENT = @NEWSEGMENT		
		AND INDICATOR = @INDICATOR
		AND D.EXCESS_COLLATERAL + D.ADJUST_AMT - EOD_SHORT > 0   
		AND ADJUST_EXCHG_SEG = ''
		 
		UPDATE #DATA_NEW SET ADJUST_AMT = #DATA_NEW.ADJUST_AMT + 
										  (CASE WHEN D.EXCESS_COLLATERAL + D.ADJUST_AMT - D.EOD_SHORT > #DATA_NEW.EOD_SHORT - #DATA_NEW.ADJUST_AMT  
											    THEN #DATA_NEW.EOD_SHORT - #DATA_NEW.ADJUST_AMT 
												ELSE D.EXCESS_COLLATERAL + D.ADJUST_AMT - D.EOD_SHORT 
										   END),
							 ADJUST_EXCHG_SEG = @NEWEXCHANGE+'#'+@NEWSEGMENT 
		FROM #ADJUST_NEW D
		WHERE D.PARTY_CODE = #DATA_NEW.PARTY_CODE
		AND D.EXCHANGE = @NEWEXCHANGE
		AND D.SEGMENT = @NEWSEGMENT
		AND D.INDICATOR = #DATA_NEW.INDICATOR
		AND #DATA_NEW.INDICATOR = @INDICATOR
		AND #DATA_NEW.EXCHANGE = @EXCHANGE
		AND #DATA_NEW.SEGMENT = @SEGMENT
		AND D.EXCESS_COLLATERAL + D.ADJUST_AMT - D.EOD_SHORT > 0 
		AND #DATA_NEW.EOD_SHORT - #DATA_NEW.ADJUST_AMT> 0 
		AND D.ADJUST_EXCHG_SEG = '' AND #DATA_NEW.ADJUST_EXCHG_SEG = ''

		UPDATE #ADJUST_NEW SET ADJUST_AMT = #ADJUST_NEW.ADJUST_AMT - 
										  (CASE WHEN #ADJUST_NEW.EXCESS_COLLATERAL + #ADJUST_NEW.ADJUST_AMT - #ADJUST_NEW.EOD_SHORT > D.EOD_SHORT - D.ADJUST_AMT  
											    THEN D.EOD_SHORT - D.ADJUST_AMT 
												ELSE #ADJUST_NEW.EXCESS_COLLATERAL + #ADJUST_NEW.ADJUST_AMT - #ADJUST_NEW.EOD_SHORT 
										   END),
							 ADJUST_EXCHG_SEG = @EXCHANGE+'#'+@SEGMENT 
		FROM #ADJUST D
		WHERE D.PARTY_CODE = #ADJUST_NEW.PARTY_CODE
		AND D.EXCHANGE = @EXCHANGE
		AND D.SEGMENT = @SEGMENT
		AND D.INDICATOR = #ADJUST_NEW.INDICATOR
		AND #ADJUST_NEW.INDICATOR = @INDICATOR
		AND #ADJUST_NEW.EXCHANGE = @NEWEXCHANGE
		AND #ADJUST_NEW.SEGMENT = @NEWSEGMENT
		AND #ADJUST_NEW.EXCESS_COLLATERAL + #ADJUST_NEW.ADJUST_AMT - #ADJUST_NEW.EOD_SHORT > 0 
		AND D.EOD_SHORT - D.ADJUST_AMT > 0 
		AND D.ADJUST_EXCHG_SEG = '' AND #ADJUST_NEW.ADJUST_EXCHG_SEG = ''
		
		UPDATE #DATA_NEW SET ADJUST_AMT = D.ADJUST_AMT, ADJUST_EXCHG_SEG=D.ADJUST_EXCHG_SEG
		FROM #ADJUST_NEW D
		WHERE D.PARTY_CODE = #DATA_NEW.PARTY_CODE
		AND D.EXCHANGE = @NEWEXCHANGE
		AND D.SEGMENT = @NEWSEGMENT
		AND D.INDICATOR = #DATA_NEW.INDICATOR
		AND #DATA_NEW.INDICATOR = @INDICATOR
		AND #DATA_NEW.EXCHANGE = @NEWEXCHANGE
		AND #DATA_NEW.SEGMENT = @NEWSEGMENT
		AND #DATA_NEW.ADJUST_EXCHG_SEG = ''  
		
		TRUNCATE TABLE #SPLIT

		INSERT INTO #SPLIT
		SELECT EXCHANGE,SEGMENT, PARTY_CODE,EXCESS_COLLATERAL,EOD_SHORT=EOD_SHORT-ADJUST_AMT,ADJUST_AMT=0,ADJUST_EXCHG_SEG ='', INDICATOR
		FROM #DATA_NEW
		WHERE  ADJUST_AMT > 0 
		AND EOD_SHORT > 0 AND EOD_SHORT>ADJUST_AMT
		AND ADJUST_EXCHG_SEG <> ''
		AND INDICATOR = @INDICATOR 
		
		INSERT INTO #SPLIT
		SELECT EXCHANGE,SEGMENT, PARTY_CODE,EXCESS_COLLATERAL,EOD_SHORT=ADJUST_AMT,ADJUST_AMT,ADJUST_EXCHG_SEG, INDICATOR 
		FROM #DATA_NEW
		WHERE   ADJUST_AMT > 0 
		AND EOD_SHORT > 0 AND EOD_SHORT>ADJUST_AMT
		AND ADJUST_EXCHG_SEG <> ''
		AND INDICATOR = @INDICATOR

		DELETE FROM #DATA_NEW WHERE   ADJUST_AMT > 0 
		AND EOD_SHORT > 0 AND EOD_SHORT>ADJUST_AMT
		AND ADJUST_EXCHG_SEG <> ''
		AND INDICATOR = @INDICATOR

		INSERT INTO #DATA_NEW
		SELECT * FROM #SPLIT
		WHERE INDICATOR = @INDICATOR
		FETCH NEXT FROM @SEGCUR INTO @NEWEXCHANGE,@NEWSEGMENT 
	END
	CLOSE @SEGCUR
	DEALLOCATE @SEGCUR
	FETCH NEXT FROM @ALLOCCUR INTO @EXCHANGE,@SEGMENT,@INDICATOR 
END
CLOSE @ALLOCCUR
DEALLOCATE @ALLOCCUR 

SELECT * INTO #DATA_FINAL FROM #DATA_NEW 

DELETE FROM TBL_SHORT_EOD_WORKING
WHERE MARGINDATE = @MARGINDATE

INSERT INTO TBL_SHORT_EOD_WORKING
SELECT MARGINDATE=@MARGINDATE,EXCHANGE,SEGMENT,PARTY_CODE,EXCESS_COLLATERAL,EOD_SHORT,ADJUST_AMT,ADJUST_EXCHG_SEG,RUNDATE=GETDATE(),INDICATOR
FROM #DATA_NEW

SELECT EXCHANGE,SEGMENT,PARTY_CODE=CLIENT_CODE,EOD_SHORT=EOD_SHORT_ALLOC,
OTHER_SEG_COLL=CONVERT(NUMERIC(18,4),0),OTHER_EXCHG_SEG=CONVERT(VARCHAR(20),''), INDICATOR
INTO #FINALADJ
FROM TBL_SHORT_ALLOC WHERE MARGINDATE=@MARGINDATE
AND EOD_SHORT_ALLOC > 0 

SELECT * INTO #ADJUST_FINAL
FROM #FINALADJ WHERE 1 = 2 

SET @ALLOCCUR = CURSOR FOR 
SELECT DISTINCT EXCHANGE,SEGMENT,INDICATOR FROM #DATA_FINAL WHERE ADJUST_AMT > 0 AND EXCHANGE = 'NCL'
ORDER BY EXCHANGE DESC,SEGMENT DESC
OPEN @ALLOCCUR 
FETCH NEXT FROM @ALLOCCUR INTO @EXCHANGE,@SEGMENT,@INDICATOR 
WHILE @@FETCH_STATUS = 0 
BEGIN 
	SET @SEGCUR = CURSOR FOR 
	SELECT DISTINCT EXCHANGE,SEGMENT FROM #FINALADJ
	WHERE NOT (EXCHANGE = @EXCHANGE AND SEGMENT = @SEGMENT)
	AND EOD_SHORT  > 0
	AND INDICATOR = @INDICATOR
	OPEN @SEGCUR 
	FETCH NEXT FROM @SEGCUR INTO @NEWEXCHANGE,@NEWSEGMENT 
	WHILE @@FETCH_STATUS = 0 
	BEGIN
		TRUNCATE TABLE #ADJUST_FINAL 

		INSERT INTO #ADJUST_FINAL 
		SELECT * FROM #FINALADJ D
		WHERE D.EXCHANGE = @NEWEXCHANGE
		AND D.SEGMENT = @NEWSEGMENT	
		AND INDICATOR = @INDICATOR	
		AND EOD_SHORT > 0   
		
		UPDATE #FINALADJ SET OTHER_SEG_COLL = 
										  (CASE WHEN D.ADJUST_AMT + OTHER_SEG_COLL > #FINALADJ.EOD_SHORT 
											    THEN #FINALADJ.EOD_SHORT 
												ELSE D.ADJUST_AMT + OTHER_SEG_COLL
										   END),
							 OTHER_EXCHG_SEG = ADJUST_EXCHG_SEG
		FROM #DATA_FINAL D
		WHERE D.PARTY_CODE = #FINALADJ.PARTY_CODE
		AND D.EXCHANGE = @EXCHANGE
		AND D.SEGMENT = @SEGMENT
		AND D.INDICATOR = #FINALADJ.INDICATOR
		AND D.INDICATOR = @INDICATOR
		AND #FINALADJ.EXCHANGE = @NEWEXCHANGE
		AND #FINALADJ.SEGMENT = @NEWSEGMENT
		AND D.ADJUST_AMT > 0 
		AND #FINALADJ.EOD_SHORT - #FINALADJ.OTHER_SEG_COLL > 0 
		
		UPDATE #DATA_FINAL SET ADJUST_AMT = #DATA_FINAL.ADJUST_AMT - 
										  (CASE WHEN #DATA_FINAL.ADJUST_AMT + OTHER_SEG_COLL > D.EOD_SHORT 
											    THEN D.EOD_SHORT 
												ELSE #DATA_FINAL.ADJUST_AMT + OTHER_SEG_COLL
										   END) 
		FROM #ADJUST_FINAL D
		WHERE D.PARTY_CODE = #DATA_FINAL.PARTY_CODE
		AND D.EXCHANGE = @NEWEXCHANGE
		AND D.SEGMENT = @NEWSEGMENT
		AND D.INDICATOR = #DATA_FINAL.INDICATOR
		AND D.INDICATOR = @INDICATOR
		AND #DATA_FINAL.EXCHANGE = @EXCHANGE
		AND #DATA_FINAL.SEGMENT = @SEGMENT
		AND #DATA_FINAL.ADJUST_AMT > 0 
		AND D.EOD_SHORT - D.OTHER_SEG_COLL > 0 
				 
		FETCH NEXT FROM @SEGCUR INTO @NEWEXCHANGE,@NEWSEGMENT 
	END
	CLOSE @SEGCUR
	DEALLOCATE @SEGCUR
	FETCH NEXT FROM @ALLOCCUR INTO @EXCHANGE,@SEGMENT,@INDICATOR
END
CLOSE @ALLOCCUR
DEALLOCATE @ALLOCCUR 

INSERT INTO #FINALADJ 
SELECT EXCHANGE,SEGMENT,PARTY_CODE,EOD_SHORT,ADJUST_AMT,ADJUST_EXCHG_SEG,INDICATOR FROM #DATA_NEW
WHERE ADJUST_AMT > 0 AND EXCHANGE NOT IN ('NSE','NSX','NCM','NCL')

DELETE FROM TBL_SHORT_ALLOC_ADJUST 
WHERE MARGINDATE = @MARGINDATE 

INSERT INTO TBL_SHORT_ALLOC_ADJUST 
SELECT MARGINDATE=@MARGINDATE, EXCHANGE,SEGMENT,PARTY_CODE,EOD_SHORT,OTHER_SEG_COLL,OTHER_EXCHG_SEG, PROCESSED_ON=GETDATE(), INDICATOR
FROM #FINALADJ 
WHERE OTHER_SEG_COLL > 0

GO
