-- Object: PROCEDURE dbo.BANK_MISMATCH
-- Server: 10.253.33.91 | DB: MSAJAG
--------------------------------------------------

  
CREATE PROC [dbo].[BANK_MISMATCH]   
( @FROMDATE DATETIME)  
AS   
  
SELECT DISTINCT PARTY_CODE INTO #T FROM (  
SELECT DISTINCT PARTY_CODE FROM CMBILLVALAN WITH(NOLOCK) WHERE SAUDA_DATE >=@FROMDATE AND SAUDA_DATE <=@FROMDATE +' 23:59'  
UNION ALL  
SELECT DISTINCT PARTY_CODE FROM AngelBSECM.BSEDB_AB.DBO.CMBILLVALAN  WITH(NOLOCK)  
WHERE SAUDA_DATE >=@FROMDATE AND SAUDA_DATE <=@FROMDATE +' 23:59'  
UNION ALL  
SELECT DISTINCT PARTY_CODE FROM ANGELFO.NSEFO.DBO.FOBILLVALAN  WITH(NOLOCK)  
WHERE SAUDA_DATE >=@FROMDATE AND SAUDA_DATE <=@FROMDATE +' 23:59' AND TRADETYPE ='BT'  
UNION ALL  
SELECT DISTINCT PARTY_CODE FROM ANGELFO.NSECURFO.DBO.FOBILLVALAN WITH(NOLOCK)  
WHERE SAUDA_DATE >=@FROMDATE AND SAUDA_DATE <=@FROMDATE +' 23:59' AND TRADETYPE ='BT'  
UNION ALL  
SELECT DISTINCT PARTY_CODE FROM ANGELCOMMODITY.MCDX.DBO.FOBILLVALAN   
WHERE SAUDA_DATE >=@FROMDATE AND SAUDA_DATE <=@FROMDATE +' 23:59' AND TRADETYPE ='BT'  
UNION ALL  
SELECT DISTINCT PARTY_CODE FROM ANGELCOMMODITY.NCDX.DBO.FOBILLVALAN WITH(NOLOCK)  
WHERE SAUDA_DATE >=@FROMDATE AND SAUDA_DATE <=@FROMDATE +' 23:59' AND TRADETYPE ='BT'  
UNION ALL  
SELECT DISTINCT PARTY_CODE FROM ANGELCOMMODITY.NCDX.DBO.FOBILLVALAN WITH(NOLOCK)  
WHERE SAUDA_DATE >=@FROMDATE AND SAUDA_DATE <=@FROMDATE +' 23:59' AND TRADETYPE ='BT' )A  
  
  
SELECT DISTINCT PARTY_CODE,BANKNAME,BRANCH,ACNUM,ACTYPE INTO #T1  
FROM PARTY_BANK_DETAILS WHERE PARTY_CODE IN (SELECT * FROM #T)  
  
  
SELECT #T1.* FROM #T1  
INNER JOIN   
(SELECT PARTY_CODE,BRANCH,ACNUM,ACTYPE FROM #T1  
GROUP BY PARTY_CODE,BRANCH,ACTYPE,ACNUM   
HAVING COUNT(ACNUM)>1  
) B  
ON #T1.PARTY_CODE=B.PARTY_CODE  
AND #T1.ACNUM=B.ACNUM  
ORDER BY #T1.PARTY_CODE

GO
