-- Object: PROCEDURE dbo.RPT_MARGIN_SHORTAGE_PENALTY
-- Server: 10.253.33.91 | DB: MSAJAG
--------------------------------------------------


  
  
create PROCEDURE [dbo].[RPT_MARGIN_SHORTAGE_PENALTY]  
(  
 @STATUSID VARCHAR(15),        
 @STATUSNAME VARCHAR(25),  
 @MARGIN_DATE_FROM VARCHAR(11),  
 @MARGIN_DATE_TO VARCHAR(11),  
 @PARTY_FROM VARCHAR(11),  
 @PARTY_TO VARCHAR(11)  
)  
AS  
  
IF @PARTY_TO = ''  
BEGIN  
 SET @PARTY_TO = 'ZZZZZZZZZ'  
END  
  
SELECT   
 MARGINDATE = CONVERT(VARCHAR,P.MARGIN_DATE,103),  
 P.PARTY_CODE,LONG_NAME,SHORTAGE,PENALTY_PERC,PENALTY_AMT,  
 DAYS_3_COUNT, SHORTAGE_COUNT1 = M.NCOUNT,  SHORTAGE_COUNT=MONTH_5_COUNT,  
  LEDGER_POST_FLAG = CASE WHEN LEDGER_POST_FLAG = 0 THEN 'N' ELSE 'Y' END,  
 MDAY = DAY(P.MARGIN_DATE),  
 MMONTH = MONTH(P.MARGIN_DATE),  
 MYEAR = YEAR(P.MARGIN_DATE)  
FROM   
 CMMARGIN_PENALTY P (NOLOCK),  
 CLIENT1 C1 (NOLOCK),  
 CLIENT2 C2 (NOLOCK),  
 CMMARGIN_PENALTY_POST_STAT L (NOLOCK),  
 (  
  SELECT PARTY_CODE, NCOUNT = COUNT(1) ,  
  COUNTMONTH = MONTH(MARGIN_DATE)  
  FROM CMMARGIN_PENALTY (NOLOCK)   
  WHERE MARGIN_DATE BETWEEN  @MARGIN_DATE_FROM AND @MARGIN_DATE_TO + ' 23:59'  

  GROUP BY PARTY_CODE,MONTH(MARGIN_DATE)  
 ) M  
WHERE   
 P.MARGIN_DATE = L.MARGIN_DATE  
 AND COUNTMONTH = MONTH(P.MARGIN_DATE)  
 AND P.PARTY_CODE = C2.PARTY_CODE  
 AND C1.CL_CODE = C2.CL_CODE  
 AND M.PARTY_CODE = P.PARTY_CODE  
 AND L.MARGIN_DATE BETWEEN  @MARGIN_DATE_FROM AND @MARGIN_DATE_TO + ' 23:59'  
 AND M.PARTY_CODE BETWEEN @PARTY_FROM AND @PARTY_TO  
    AND @STATUSNAME = (         
    CASE         
            WHEN @STATUSID = 'BRANCH'         
            THEN C1.BRANCH_CD         
            WHEN @STATUSID = 'SUBBROKER'         
            THEN C1.SUB_BROKER         
            WHEN @STATUSID = 'TRADER'         
            THEN C1.TRADER         
            WHEN @STATUSID = 'FAMILY'         
            THEN C1.FAMILY         
            WHEN @STATUSID = 'AREA'         
            THEN C1.AREA         
            WHEN @STATUSID = 'REGION'         
            THEN C1.REGION         
            WHEN @STATUSID = 'CLIENT'         
 THEN C2.PARTY_CODE         
            ELSE 'BROKER' END)         
ORDER BY MDAY,MMONTH,MYEAR

GO
