-- Object: PROCEDURE dbo.SMSSTATUS
-- Server: 10.253.33.91 | DB: MSAJAG
--------------------------------------------------


CREATE PROC SMSSTATUS
(
	@FDATE VARCHAR(11),
	@BATCH VARCHAR(50)
)
AS
/*
	EXEC SMSSTATUS '', '127201311232'
*/
IF LEN(@FDATE) = 10 AND CHARINDEX('/', @FDATE) > 0 
	BEGIN
		SET @FDATE = CONVERT(VARCHAR(11), CONVERT(DATETIME, @FDATE, 103), 109)
	END


IF @FDATE <> '' AND @BATCH = ''
	BEGIN
		--SELECT MESSAGEFOR, BATCH = MAX(BATCH) INTO #SMSRESULT FROM SMSRESULT WHERE FORDATE LIKE @FDATE + '%' GROUP BY MESSAGEFOR

		SELECT SENTON = CONVERT(VARCHAR(10), MAX(S.SENTON), 103), S.MESSAGEFOR, TOTALMSGS = COUNT(1), SUCCESS = SUM(CASE WHEN S.RETURNSTATUS = 'Y' THEN 1 ELSE 0 END),
		FAILURE = SUM(CASE WHEN S.RETURNSTATUS <> 'Y' THEN 1 ELSE 0 END)
		FROM
			SMSRESULT S 
		WHERE FORDATE LIKE @FDATE + '%'
		GROUP BY
			S.MESSAGEFOR
		--DROP TABLE #SMSRESULT
	END
IF @BATCH <> ''
	BEGIN
		SELECT PARTY_CODE, MOBILE, MESSAGETXT, MESSAGETYPE, [STATUS] = CASE WHEN RETURNSTATUS = 'Y' THEN 'SUCCESS' ELSE 'FAILED' END,
		TOKENID=RETURNFLAG,
		SENTON = CONVERT(VARCHAR(10), SENTON, 103), SMSFOR = CONVERT(VARCHAR(10), FORDATE, 103), SENTBY
		FROM SMSRESULT
		WHERE FORDATE LIKE @FDATE + '%'
			AND MESSAGEFOR = @BATCH
	END

GO
