-- Object: PROCEDURE dbo.RPT_EPN_VALUATION_CCE
-- Server: 10.253.33.91 | DB: MSAJAG
--------------------------------------------------


CREATE PROCEDURE RPT_EPN_VALUATION_CCE (@RUNDATE VARCHAR(11))

AS ---- EXEC RPT_EPN_VALUATION_CCE 'MAR 30 2022'

TRUNCATE TABLE EPN_VALUATION_CCE

INSERT INTO EPN_VALUATION_CCE
EXEC MSAJAG.DBO.GET_EPI_POOL_ACCOUNT @RUNDATE

DECLARE @EDTFILENAME1 VARCHAR(100) = 'J:\BACKOFFICE\EXPORT\' +'CCE_EPN_VALUATION_' + CONVERT(VARCHAR, CONVERT(DATETIME,@RUNDATE), 112) + '.CSV'
DECLARE @EDT1 VARCHAR(MAX)                            
SET @EDT1 = 'EXEC MASTER.DBO.XP_CMDSHELL ''BCP "SELECT ''''EXCHANGE'''',''''SEGMENT'''',''''PARTY_CODE'''',''''EPIAMOUNT''''' 
SET @EDT1 = @EDT1 + ' UNION ALL SELECT EXCHANGE,SEGMENT,LTRIM(RTRIM(PARTY_CODE)),CONVERT(VARCHAR,EPIACCOUNT) FROM MSAJAG.DBO.EPN_VALUATION_CCE" QUERYOUT ' +@EDTFILENAME1+ ' -c -t"," -c -t"," -r"\n" -T'', NO_OUTPUT'     
EXEC(@EDT1)

SELECT 'CCE EPN Valuation data Exported to ' + 'J:\BACKOFFICE\EXPORT\' +'CCE_EPN_VALUATION_' + CONVERT(VARCHAR, CONVERT(DATETIME,@RUNDATE), 112) + '.CSV'

GO
