-- Object: PROCEDURE dbo.PROC_SHORT_MARGIN_DWLOAD_MCX
-- Server: 10.253.33.91 | DB: MSAJAG
--------------------------------------------------


CREATE PROC [dbo].[PROC_SHORT_MARGIN_DWLOAD_MCX]
(
	@EFFDATE	VARCHAR(11) 
)
AS

SET NOCOUNT ON 

-- EXEC PROC_SHORT_MARGIN_DWLOAD_MCX 'AUG  2 2022'
   
SELECT * INTO #TBL_MCX_SHORT_ALLOC FROM TBL_MCX_SHORT_ALLOC
WHERE MARGINDATE = @EFFDATE

DECLARE @BATCHNO varchar(2)
DECLARE @FILEDATE VARCHAR(10)

IF  (SELECT COUNT(1) FROM ASIANFILEMARGINBATCHNO WHERE  LEFT(FILEDATE,11) = LEFT(@EFFDATE,11) ) = 0 
      BEGIN 
            INSERT INTO ASIANFILEMARGINBATCHNO 
            SELECT '1' ,LEFT(@EFFDATE,11),GETDATE()
      END
ELSE 
      BEGIN 
            SELECT @BATCHNO = MAX(FILEBATCHNO)+1 FROM ASIANFILEMARGINBATCHNO  
            WHERE LEFT(FILEDATE,11) = LEFT(@EFFDATE,11)
            UPDATE ASIANFILEMARGINBATCHNO SET FILEBATCHNO = @BATCHNO WHERE LEFT(FILEDATE,11) = LEFT(@EFFDATE,11)
      END

SET @FILEDATE = REPLACE(CONVERT(VARCHAR,CONVERT(DATETIME,@EFFDATE),103),'/','')

SELECT @BATCHNO = MAX(FILEBATCHNO) FROM ASIANFILEMARGINBATCHNO  
            WHERE LEFT(FILEDATE,11) = LEFT(@EFFDATE,11)




UPDATE #TBL_MCX_SHORT_ALLOC SET EXCESS_ICCL = ICL_COLL, EXCESS_NCL = NCL_COLL, EXCESS_NCCL = NCX_COLL, EXCESS_MCCIL = OTHER_COLL
FROM (SELECT PARTY_CODE,
				ICL_COLL=SUM(CASE WHEN LEFT(OTHER_EXCHG_SEG,3) = 'ICL' THEN OTHER_SEG_COLL ELSE 0 END),
				NCL_COLL=SUM(CASE WHEN LEFT(OTHER_EXCHG_SEG,3) = 'NCL' THEN OTHER_SEG_COLL ELSE 0 END),
				NCX_COLL=SUM(CASE WHEN LEFT(OTHER_EXCHG_SEG,3) = 'NCX' THEN OTHER_SEG_COLL ELSE 0 END),
				OTHER_COLL=SUM(CASE WHEN LEFT(OTHER_EXCHG_SEG,3) NOT IN ('ICL','NCL','NCX') THEN OTHER_SEG_COLL ELSE 0 END)
		FROM MSAJAG.DBO.TBL_SHORT_ALLOC_ADJUST T  
		WHERE T.MARGINDATE = @EFFDATE AND OTHER_SEG_COLL > 0 AND EXCHANGE = 'MCX'
		GROUP BY PARTY_CODE,EXCHANGE,SEGMENT) T
WHERE T.PARTY_CODE = #TBL_MCX_SHORT_ALLOC.CLIENT_CODE  

----SELECT
----FILENAME_EXCHG = REPLACE(FLDFILENAME,'.xls','_R.xls'),
----[Date]=REPLACE(CONVERT(VARCHAR,MARGINDATE,103),'/','-'),
----[CM ID]= LTRIM(RTRIM(CMID)), 
----[TM ID]= LTRIM(RTRIM(TMID)) ,
----[End Client/CP Code]= LTRIM(RTRIM(CLIENT_CODE)) ,
----[EOD Short Allocation (Rs)]=CONVERT(NUMERIC(18,2),EOD_SHORT_ALLOC) ,
------[EOD Short Allocation Reported (Rs)]=CONVERT(NUMERIC(18,2),EOD_SHORT_REP),
----[Excess collateral with NCL (Rs.)]=CONVERT(NUMERIC(18,2),EXCESS_NCL),
----[Excess collateral with ICCL(Rs.)]=CONVERT(NUMERIC(18,2),EXCESS_ICCL),
----[Excess collateral with NCCL(Rs.)]=CONVERT(NUMERIC(18,2),EXCESS_NCCL),
----[Excess collateral with MCCIL(Rs.)]=CONVERT(NUMERIC(18,2),EXCESS_MCCIL)

----FROM #TBL_MCX_SHORT_ALLOC
----WHERE MARGINDATE = @EFFDATE 

SELECT
FILENAME_EXCHG = REPLACE(FLDFILENAME ,'.csv',  '_R'+@BATCHNO+'.csv'),
--FILENAME_EXCHG = REPLACE(FLDFILENAME ,'.csv',  '_R'+@BATCHNO),
REPLACE(CONVERT(VARCHAR,MARGINDATE,103),'/','-'),
LTRIM(RTRIM(CMID)), 
LTRIM(RTRIM(TMID)) ,
LTRIM(RTRIM(CLIENT_CODE)) ,
CONVERT(NUMERIC(18,2),EOD_SHORT_ALLOC) ,
--[EOD Short Allocation Reported (Rs)]=CONVERT(NUMERIC(18,2),EOD_SHORT_REP),
CONVERT(NUMERIC(18,2),EXCESS_NCL),
CONVERT(NUMERIC(18,2),EXCESS_ICCL),
CONVERT(NUMERIC(18,2),EXCESS_NCCL),
CONVERT(NUMERIC(18,2),EXCESS_MCCIL)

FROM #TBL_MCX_SHORT_ALLOC
WHERE MARGINDATE = @EFFDATE

GO
