-- Object: PROCEDURE dbo.AUTO_AWS_CN_MAR_BILL_BKP_22AUG2025_SRE-39582
-- Server: 10.253.33.91 | DB: MSAJAG
--------------------------------------------------


 CREATE PROC [dbo].[AUTO_AWS_CN_MAR_BILL_BKP_22AUG2025_SRE-39582]
 AS
 BEGIN 
Declare @D varchar(11)
Declare @V varchar(11)
		select @D  = EXEC_DATE from TBL_CN_MAR_BILL_DATE	

	 select @V  = VAL from TBL_CN_MAR_BILL_DATE
	 
	 INSERT INTO AWS_CN_ALL_PROCESS_LOG
	 SELECT @V,@D,GETDATE(),'',''
	   
	    EXEC aws_Margin_Statement @D 
	 
	 UPDATE AWS_CN_ALL_PROCESS_LOG SET END_TIME = GETDATE() WHERE PROCESS_FOR =@V AND 	PROCESS_DATE =@D

	 UPDATE AWS_CN_ALL_PROCESS_LOG SET TOTAL_TIME = DATEDIFF(MINUTE,START_TIME,END_TIME) WHERE PROCESS_FOR =@V AND 	PROCESS_DATE =@D
END

GO
