-- Object: PROCEDURE dbo.RPT_OBLMATCH_NEW
-- Server: 10.253.33.91 | DB: MSAJAG
--------------------------------------------------

--Altered this SP under SRE-35483
CREATE PROC [dbo].[RPT_OBLMATCH_NEW]               

(@SETT_NO VARCHAR(7), @SETT_TYPE VARCHAR(2), @TDATE VARCHAR(11), @OBLFLAG VARCHAR(1),
@FROMFLAG int = 0)              

AS              

        

DECLARE @MEMBERCODE VARCHAR(15)        

        

SELECT @MEMBERCODE = MEMBERCODE FROM OWNER        

DECLARE @OTHER_SETT_NO VARCHAR(7),
		@OTHER_SETT_TYPE VARCHAR(2),
		@CLEARINGCODE	VARCHAR(10),
		@Start_Date VARCHAR(11) 

SELECT @Start_Date = START_DATE FROM SETT_MST 
WHERE Sett_No = @Sett_No And Sett_Type = @Sett_Type  

SELECT @CLEARINGCODE = ISNULL(CLEARINGCODE,'') FROM TBL_INTEROP_SETTING
WHERE  @START_DATE BETWEEN FROM_DATE AND TO_DATE

SELECT SCRIP_CD,SERIES,SCRIP_NAME=CONVERT(VARCHAR(50),''),          
E_PQTY=PQTY,E_PAMT=PAMT,E_SQTY=SQTY,E_SAMT=SAMT,E_NETQTY=NETQTY,E_NETAMT=NETAMT,          
B_PQTY=PQTY,B_PAMT=PAMT,B_SQTY=SQTY,B_SAMT=SAMT,B_NETQTY=NETQTY,B_NETAMT=NETAMT,          
MATCHSTATUS = 1          
INTO #BSE_OBL      
FROM AngelBSECM.BSEDB_AB.DBO.TBL_BSE_OBL   
WHERE 1 = 2 

IF @CLEARINGCODE = 'NSCCL'
BEGIN
	IF (SELECT ISNULL(COUNT(1),0) FROM TBL_INTEROP_SETT_TYPE 
		WHERE NSE_SETT_TYPE = @Sett_Type AND @Start_Date BETWEEN FROM_DATE AND TO_DATE) > 0
	BEGIN 
		SELECT @OTHER_SETT_TYPE = BSE_SETT_TYPE 
		FROM TBL_INTEROP_SETT_TYPE WHERE NSE_SETT_TYPE = @Sett_Type 
		AND @Start_Date BETWEEN FROM_DATE AND TO_DATE
		
		SELECT @OTHER_SETT_NO = SETT_NO FROM AngelBSECM.bsedb_ab.DBO.Sett_Mst 
		Where Start_date >= @Start_Date and Start_date <= @Start_Date + ' 23:59' 
		And Sett_Type = @OTHER_SETT_TYPE  
	 
		INSERT INTO #BSE_OBL
		EXEC AngelBSECM.BSEDB_AB.DBO.RPT_OBLMATCH @OTHER_SETT_NO, @OTHER_SETT_TYPE
		
		ALTER TABLE #BSE_OBL
		ADD ISIN VARCHAR(12)

		UPDATE #BSE_OBL SET ISIN = M.ISIN FROM TBL_EXCHG_SCRIP_MAP M
		WHERE M.BSECODE = SCRIP_CD AND SERIES = 'BSE' AND @Start_Date BETWEEN FROM_DATE AND TO_DATE 
		 
		UPDATE #BSE_OBL SET SCRIP_CD = NSE_SCRIP_CD, SERIES = NSE_SERIES FROM TBL_EXCHG_SCRIP_MAP M
		WHERE M.ISIN = #BSE_OBL.ISIN AND @Start_Date BETWEEN FROM_DATE AND TO_DATE 
		 
	END
END
        
SELECT               
PARTICIPANTCODE=(CASE WHEN PARTICIPANTCODE = '' OR PARTICIPANTCODE = '0' THEN MEMBERCODE ELSE PARTICIPANTCODE END), SCRIP_CD, SERIES,               
C_PQTY = SUM(C_PQTY), C_SQTY = SUM(C_SQTY),               
C_PAMT = SUM(C_PAMT), C_SAMT = SUM(C_SAMT),              
O_D_PQTY = 0, O_D_SQTY = 0,               
O_D_PAMT = CONVERT(NUMERIC(18, 4), 0),               
O_D_SAMT = CONVERT(NUMERIC(18, 4), 0)              
INTO #TBL_NSE_OBL              
FROM TBL_NSE_OBL, OWNER              
WHERE SETT_NO = @SETT_NO              
AND SETT_TYPE = @SETT_TYPE        
GROUP BY PARTICIPANTCODE, SCRIP_CD, SERIES, MEMBERCODE              

              

SELECT PARTIPANTCODE=CONVERT(VARCHAR(15),@MEMBERCODE), SCRIP_CD, SERIES,               
PQTY = SUM(CASE WHEN SELL_BUY = 1 THEN TRADEQTY ELSE 0 END),              
SQTY = SUM(CASE WHEN SELL_BUY = 2 THEN TRADEQTY ELSE 0 END),              
PAMT = SUM(CASE WHEN SELL_BUY = 1 THEN TRADEQTY*MARKETRATE ELSE 0 END),              
SAMT = SUM(CASE WHEN SELL_BUY = 2 THEN TRADEQTY*MARKETRATE ELSE 0 END)              
INTO #SETT               
FROM SETTLEMENT (NOLOCK)              
WHERE SETT_NO = @SETT_NO              
AND SETT_TYPE = @SETT_TYPE              
AND SAUDA_DATE <= @TDATE + ' 23:59:59'              
AND AUCTIONPART NOT IN ('AP', 'AR', 'FP', 'FL', 'FC')              
AND MARKETRATE > 0               
GROUP BY SCRIP_CD, SERIES              


ALTER TABLE #SETT 
ALTER COLUMN SERIES VARCHAR(5)



INSERT INTO #SETT 
SELECT MEMBERCODE, SCRIP_CD, SERIES, B_PQTY, B_SQTY, B_PAMT, B_SAMT
FROM #BSE_OBL, OWNER 

--- START T+0 SETTLEMENT CHANGES ---
UPDATE #SETT SET SERIES = 'T0'
WHERE SERIES = 'EQ' AND @SETT_TYPE = '5'
--- END T+0 SETTLEMENT CHANGES ---
              
SELECT PARTIPANTCODE, SCRIP_CD, SERIES, 
PQTY = SUM(PQTY), SQTY = SUM(SQTY),
PAMT = SUM(PAMT), SAMT = SUM(SAMT) 
INTO #SETT_FIN
FROM  #SETT
GROUP BY PARTIPANTCODE, SCRIP_CD, SERIES

IF @OBLFLAG = 'N'               

BEGIN              

 INSERT INTO #SETT_FIN              

 SELECT PARTIPANTCODE, SCRIP_CD, SERIES,               

 PQTY = SUM(CASE WHEN SELL_BUY = 1 THEN TRADEQTY ELSE 0 END),              

 SQTY = SUM(CASE WHEN SELL_BUY = 2 THEN TRADEQTY ELSE 0 END),              

 PAMT = SUM(CASE WHEN SELL_BUY = 1 THEN TRADEQTY*DUMMY1 ELSE 0 END),              

 SAMT = SUM(CASE WHEN SELL_BUY = 2 THEN TRADEQTY*DUMMY1 ELSE 0 END)              

 FROM ISETTLEMENT   (NOLOCK)           

 WHERE SETT_NO = @SETT_NO              

 AND SETT_TYPE = @SETT_TYPE              

 AND SAUDA_DATE <= @TDATE + ' 23:59:59'              

 GROUP BY PARTIPANTCODE, SCRIP_CD, SERIES              

END        

ELSE        

BEGIN        

 DELETE FROM #TBL_NSE_OBL WHERE PARTICIPANTCODE <> @MEMBERCODE             

END        

         

UPDATE #TBL_NSE_OBL SET O_D_PQTY = PQTY, O_D_SQTY = SQTY, O_D_PAMT = PAMT, O_D_SAMT = SAMT              

FROM #SETT_FIN S              

WHERE #TBL_NSE_OBL.SCRIP_CD = S.SCRIP_CD              

AND #TBL_NSE_OBL.SERIES = S.SERIES              

AND #TBL_NSE_OBL.PARTICIPANTCODE = S.PARTIPANTCODE              

              

INSERT INTO #TBL_NSE_OBL              

SELECT PARTIPANTCODE, SCRIP_CD, SERIES, 0, 0, 0, 0, PQTY, SQTY, PAMT, SAMT              

FROM #SETT_FIN S              

WHERE NOT EXISTS (              

 SELECT SCRIP_CD FROM #TBL_NSE_OBL              

 WHERE #TBL_NSE_OBL.SCRIP_CD = S.SCRIP_CD              

 AND #TBL_NSE_OBL.SERIES = S.SERIES              

 AND #TBL_NSE_OBL.PARTICIPANTCODE = S.PARTIPANTCODE)              

      

ALTER TABLE #TBL_NSE_OBL      

ADD MATCHSTATUS INT      

      

UPDATE #TBL_NSE_OBL SET MATCHSTATUS = 1      

  

UPDATE #TBL_NSE_OBL SET MATCHSTATUS = 0              

WHERE ( ( C_PQTY <> O_D_PQTY )              

 OR ( C_SQTY <> O_D_SQTY )              

 OR ( C_PAMT <> O_D_PAMT )              

 OR ( C_SAMT <> O_D_SAMT ))  
       
DELETE FROM TBL_FINOBL_STATUS 
WHERE SETT_NO = @SETT_NO AND SETT_TYPE = @SETT_TYPE 

INSERT INTO TBL_FINOBL_STATUS 
SELECT *, @SETT_NO, @SETT_TYPE FROM #TBL_NSE_OBL              
ORDER BY PARTICIPANTCODE, SCRIP_CD, SERIES

IF @FROMFLAG <> 0
BEGIN              
	SELECT PARTICIPANTCODE,SCRIP_CD,SERIES,C_PQTY,C_SQTY,C_PAMT,C_SAMT,O_D_PQTY,O_D_SQTY,O_D_PAMT,O_D_SAMT,MATCHSTATUS
  FROM TBL_FINOBL_STATUS              
  WHERE SETT_NO =  @SETT_NO
  AND SETT_TYPE = @SETT_TYPE
	ORDER BY PARTICIPANTCODE, SCRIP_CD, SERIES
END
ELSE
BEGIN
	SELECT PARTICIPANTCODE,SCRIP_CD,SERIES,C_PQTY,C_SQTY,C_PAMT,C_SAMT,O_D_PQTY,O_D_SQTY,O_D_PAMT,O_D_SAMT,MATCHSTATUS 
  FROM TBL_FINOBL_STATUS   
  WHERE SETT_NO =  @SETT_NO
  AND SETT_TYPE = @SETT_TYPE          
	ORDER BY PARTICIPANTCODE, SCRIP_CD, SERIES
END

GO
