-- Object: PROCEDURE dbo.CLIENTACC
-- Server: 10.253.33.91 | DB: MSAJAG
--------------------------------------------------

--EXEC CLIENTACC 'MAY 26 2020'
CREATE PROCEDURE [dbo].[CLIENTACC]
	@FROMDATE VARCHAR(11)
AS


--SELECT DISTINCT CLTCODE FROM ACCOUNT.DBO.LEDGER_ALL(Nolock) WHERE VTYP <> 18 AND VDT BETWEEN DATEADD(D, -365, @FROMDATE) AND @FROMDATE + ' 23:59'

SELECT DISTINCT CLTCODE INTO #CLT_A FROM ACCOUNT.DBO.LEDGER (Nolock) WHERE VTYP <> 18 AND VDT BETWEEN DATEADD(D, -365, @FROMDATE) AND @FROMDATE + ' 23:59'

INSERT INTO  #CLT_A
SELECT DISTINCT CLTCODE FROM ANGELBSECM.ACCOUNT_AB.DBO.LEDGER With(Nolock) WHERE VTYP <> 18 AND VDT BETWEEN DATEADD(D, -365, @FROMDATE) AND @FROMDATE + ' 23:59'

INSERT INTO  #CLT_A
SELECT DISTINCT CLTCODE FROM ANGELFO.ACCOUNTFO.DBO.LEDGER With(Nolock) WHERE VTYP <> 18 AND VDT BETWEEN DATEADD(D, -365, @FROMDATE) AND @FROMDATE + ' 23:59'

INSERT INTO  #CLT_A
SELECT DISTINCT CLTCODE FROM ANGELFO.ACCOUNTCURFO.DBO.LEDGER With(Nolock) WHERE VTYP <> 18 AND VDT BETWEEN DATEADD(D, -365, @FROMDATE) AND @FROMDATE + ' 23:59'

INSERT INTO  #CLT_A
SELECT DISTINCT CLTCODE FROM ANGELCOMMODITY.ACCOUNTMCDX.DBO.LEDGER With(Nolock) WHERE VTYP <> 18 AND VDT BETWEEN DATEADD(D, -365, @FROMDATE) AND @FROMDATE + ' 23:59'

INSERT INTO  #CLT_A
SELECT DISTINCT CLTCODE FROM ANGELCOMMODITY.ACCOUNTNCDX.DBO.LEDGER With(Nolock) WHERE VTYP <> 18 AND VDT BETWEEN DATEADD(D, -365, @FROMDATE) AND @FROMDATE + ' 23:59'

INSERT INTO  #CLT_A
SELECT DISTINCT CLTCODE FROM ANGELCOMMODITY.ACCOUNTMCDXCDS.DBO.LEDGER With(Nolock) WHERE VTYP <> 18 AND VDT BETWEEN DATEADD(D, -365, @FROMDATE) AND @FROMDATE + ' 23:59'

INSERT INTO  #CLT_A
SELECT DISTINCT CLTCODE FROM ANGELCOMMODITY.ACCOUNTMCDXCDS.DBO.LEDGER With(Nolock) WHERE VTYP <> 18 AND VDT BETWEEN DATEADD(D, -365, @FROMDATE) AND @FROMDATE + ' 23:59'

INSERT INTO  #CLT_A
SELECT DISTINCT CLTCODE FROM ANGELCOMMODITY.ACCOUNTbFO.DBO.LEDGER With(Nolock) WHERE VTYP <> 18 AND VDT BETWEEN DATEADD(D, -365, @FROMDATE) AND @FROMDATE + ' 23:59'

INSERT INTO  #CLT_A
SELECT DISTINCT CLTCODE FROM ANGELCOMMODITY.ACCOUNTCURBFO.DBO.LEDGER With(Nolock) WHERE VTYP <> 18 AND VDT BETWEEN DATEADD(D, -365, @FROMDATE) AND @FROMDATE + ' 23:59'

SELECT DISTINCT CLTCODE FROM #CLT_A

GO
