-- Object: PROCEDURE dbo.CLS_ADDITIONAL_TAX_CAL
-- Server: 10.253.33.91 | DB: MSAJAG
--------------------------------------------------





CREATE PROC [dbo].[CLS_ADDITIONAL_TAX_CAL]
	(
	@SETT_TYPE 	VARCHAR(2),
	@SAUDA_DATE 	VARCHAR(11),
	@FROMPARTY  	VARCHAR(10)='0',      
	@TOPARTY	VARCHAR(10)='ZZZZZZZZZZ'
	)
	
	AS
	
	/*
	EXEC CLS_ADDITIONAL_TAX_CAL 'N','APR 25 2023','','ZZZZZZ'
	*/

	DECLARE	@IPFTCHRG	NUMERIC(18,4),
			@IPFTCHRG_INS NUMERIC(18,4)

	SELECT @IPFTCHRG = ISNULL(IPFTCHRG,0), @IPFTCHRG_INS = ISNULL(IPFTCHRG_INS,0) FROM GLOBALS WHERE @SAUDA_DATE BETWEEN YEAR_START_DT AND YEAR_END_DT

	IF @IPFTCHRG = 0
	BEGIN
		RETURN
	END

	CREATE TABLE #ADDITIONAL_TAX_DATA
		(
		PARTY_CODE	VARCHAR(20),
		SAUDA_DATE	DATETIME,
		SETT_NO		VARCHAR(10),
		SETT_TYPE	VARCHAR(3),
		CONTRACTNO	VARCHAR(10),
		ORDER_NO	VARCHAR(20),
		TRADE_NO	VARCHAR(20),
		SCRIP_CD	VARCHAR(30),
		SERIES		VARCHAR(3),
		MARKETRATE	NUMERIC(18,4),
		TRADEQTY	INT,
		AMOUNT		NUMERIC(18,4),
		SELL_BUY	INT,
		TRDTYPE		CHAR(1),
		IPFT_CHRG	NUMERIC(18,4),
		ADD_CHRG_1	NUMERIC(18,4),
		ADD_CHRG_2	NUMERIC(18,4),
		ADD_CHRG_3	NUMERIC(18,4),
		ADD_CHRG_4	NUMERIC(18,4),
		ADD_CHRG_5	NUMERIC(18,4)
		)

	CREATE NONCLUSTERED INDEX [IDXADX1] ON [#ADDITIONAL_TAX_DATA] 
		(
		[SAUDA_DATE] ASC,
		[PARTY_CODE] ASC
		)

	CREATE NONCLUSTERED INDEX [IDXADX2] ON [#ADDITIONAL_TAX_DATA] 
		(
		[SETT_NO] ASC,
		[SETT_TYPE] ASC,
		[PARTY_CODE] ASC
		)

	INSERT	INTO #ADDITIONAL_TAX_DATA
	SELECT	PARTY_CODE,
			SAUDA_DATE = LEFT(SAUDA_DATE,11),
			SETT_NO,
			SETT_TYPE,
			CONTRACTNO,
			ORDER_NO = '',
			TRADE_NO = '',
			SCRIP_CD,
			SERIES,
			MARKETRATE = SUM(MARKETRATE*TRADEQTY)/SUM(TRADEQTY),
			TRADEQTY = SUM(TRADEQTY),
			AMOUNT = SUM(MARKETRATE*TRADEQTY),
			SELL_BUY,
			TRDTYPE	= 'N',
			IPFT_CHRG = 0,
			ADD_CHRG_1 = 0,
			ADD_CHRG_2 = 0,
			ADD_CHRG_3 = 0,
			ADD_CHRG_4 = 0,
			ADD_CHRG_5 = 0
	FROM	SETTLEMENT
	WHERE	SAUDA_DATE BETWEEN @SAUDA_DATE AND @SAUDA_DATE + ' 23:59:59' 
			AND PARTY_CODE BETWEEN @FROMPARTY AND @TOPARTY 
			AND SETT_TYPE = @SETT_TYPE
			AND AUCTIONPART NOT LIKE 'A%'
			AND AUCTIONPART NOT LIKE 'F%' AND TRADEQTY > 0 AND TRADE_NO NOT LIKE '%C%'
	GROUP BY
			PARTY_CODE,
			LEFT(SAUDA_DATE,11),
			SETT_NO,
			SETT_TYPE,
			CONTRACTNO,
			SCRIP_CD,
			SERIES,
			SELL_BUY

	
	IF @IPFTCHRG_INS <> 0
	BEGIN
		INSERT	INTO #ADDITIONAL_TAX_DATA
		SELECT	PARTY_CODE,
				SAUDA_DATE = LEFT(SAUDA_DATE,11),
				SETT_NO,
				SETT_TYPE,
				CONTRACTNO,
				ORDER_NO = '',
				TRADE_NO = '',
				SCRIP_CD,
				SERIES,
				MARKETRATE = SUM(MARKETRATE*TRADEQTY)/SUM(TRADEQTY),
				TRADEQTY = SUM(TRADEQTY),
				AMOUNT = SUM(MARKETRATE*TRADEQTY),
				SELL_BUY,
				TRDTYPE	= 'I',
				IPFT_CHRG = 0,
				ADD_CHRG_1 = 0,
				ADD_CHRG_2 = 0,
				ADD_CHRG_3 = 0,
				ADD_CHRG_4 = 0,
				ADD_CHRG_5 = 0
		FROM	ISETTLEMENT
		WHERE	SAUDA_DATE BETWEEN @SAUDA_DATE AND @SAUDA_DATE + ' 23:59:59' 
				AND PARTY_CODE BETWEEN @FROMPARTY AND @TOPARTY 
				AND SETT_TYPE = @SETT_TYPE
				AND AUCTIONPART NOT LIKE 'A%'
				AND AUCTIONPART NOT LIKE 'F%' AND TRADEQTY > 0 AND TRADE_NO NOT LIKE '%C%'
		GROUP BY
				PARTY_CODE,
				LEFT(SAUDA_DATE,11),
				SETT_NO,
				SETT_TYPE,
				CONTRACTNO,
				SCRIP_CD,
				SERIES,
				SELL_BUY
	END

	/*
	UPDATE	#ADDITIONAL_TAX_DATA
	SET		IPFT_CHRG = ROUND(AMOUNT*TAX1/100,4)
	FROM	CLIENTTAXES_NEW C (NOLOCK)
	WHERE	C.PARTY_CODE = #ADDITIONAL_TAX_DATA.PARTY_CODE
			AND @SAUDA_DATE BETWEEN FROMDATE AND TODATE
			AND TAX1 > 0
	*/
	
	UPDATE	#ADDITIONAL_TAX_DATA
	SET		IPFT_CHRG = ROUND(AMOUNT*@IPFTCHRG/100,4)
	WHERE	AMOUNT > 0 AND @IPFTCHRG <> 0
			AND TRDTYPE	= 'N'

	
	UPDATE	#ADDITIONAL_TAX_DATA
	SET		IPFT_CHRG = ROUND(AMOUNT*@IPFTCHRG_INS/100,4)
	WHERE	AMOUNT > 0 AND @IPFTCHRG <> 0
			AND TRDTYPE	= 'I'
	
	
	DELETE	FROM TBL_ADDITIONAL_TAX_DATA
	WHERE	SAUDA_DATE	BETWEEN @SAUDA_DATE AND @SAUDA_DATE + ' 23:59:59' 
			AND PARTY_CODE BETWEEN @FROMPARTY AND @TOPARTY 
			AND SETT_TYPE = @SETT_TYPE

	INSERT INTO TBL_ADDITIONAL_TAX_DATA
	SELECT * FROM #ADDITIONAL_TAX_DATA


	DROP TABLE #ADDITIONAL_TAX_DATA

GO
