-- Object: PROCEDURE dbo.RPT_COLLATERAL_DATA_EXPORT
-- Server: 10.253.33.91 | DB: MSAJAG
--------------------------------------------------


CREATE PROCEDURE RPT_COLLATERAL_DATA_EXPORT (@RUNDATE VARCHAR(11),@REPORT VARCHAR(10))

AS ---- EXEC RPT_COLLATERAL_DATA_EXPORT 'JUN 01 2022','MRGRATE'

IF @REPORT = 'ALL'
BEGIN
TRUNCATE TABLE TBL_COLLATERAL_EXPORT

INSERT INTO TBL_COLLATERAL_EXPORT
SELECT EXCHANGE,SEGMENT,PARTY_CODE,COLL_TYPE,SCRIP_CD,SERIES,ISIN,QTY,MRG_CL_RATE,AMOUNT,MRG_VAR_MARGIN,FINALAMOUNT,EFFDATE,CREATEDON
FROM V2_TBL_COLLATERAL_MARGIN_COMBINE WITH (NOLOCK)
WHERE EFFDATE BETWEEN @RUNDATE AND @RUNDATE + ' 23:59:59'

DECLARE @DIRCOLLNAMEAM VARCHAR(100) = 
'J:\BACKOFFICE\EXPORT\' +'COLLATERAL_DATA_ALL_' + CONVERT(VARCHAR, CONVERT(DATETIME,@RUNDATE), 112) + '.CSV'

DECLARE @S VARCHAR(MAX)                            
SET @S = 'EXEC MASTER.DBO.XP_CMDSHELL ''BCP "SELECT ''''EXCHANGE'''',''''SEGMENT'''',''''PARTY_CODE'''',''''COLL_TYPE'''',''''SCRIP_CD'''',''''SERIES'''',''''ISIN'''',''''QTY'''',''''MRG_CL_RATE'''',''''AMOUNT'''',''''MRG_VAR_MARGIN'''',''''FINALAMOUNT'''',''''EFFDATE'''',''''CREATEDON''''' 
SET @S = @S + ' UNION ALL SELECT EXCHANGE,SEGMENT,PARTY_CODE,COLL_TYPE,SCRIP_CD,SERIES,ISIN,CONVERT(VARCHAR,QTY),CONVERT(VARCHAR,MRG_CL_RATE),CONVERT(VARCHAR,AMOUNT),CONVERT(VARCHAR,MRG_VAR_MARGIN),CONVERT(VARCHAR,FINALAMOUNT),CONVERT(VARCHAR,EFFDATE),CONVERT(VARCHAR,CREATEDON) FROM MSAJAG.DBO.TBL_COLLATERAL_EXPORT" QUERYOUT ' +@DIRCOLLNAMEAM+ ' -c -t"," -c -t"," -r"\n" -T'', NO_OUTPUT'
EXEC(@S)

SELECT 'Collateral All Data Exported to ' + 'J:\BACKOFFICE\EXPORT\' +'COLLATERAL_DATA_ALL_' + CONVERT(VARCHAR, CONVERT(DATETIME,@RUNDATE), 112) + '.CSV'
END

IF @REPORT = 'CASH'
BEGIN
TRUNCATE TABLE TBL_COLLATERAL_EXPORT

INSERT INTO TBL_COLLATERAL_EXPORT
SELECT EXCHANGE,SEGMENT,PARTY_CODE,COLL_TYPE,SCRIP_CD,SERIES,ISIN,QTY,MRG_CL_RATE,AMOUNT,MRG_VAR_MARGIN,FINALAMOUNT,EFFDATE,CREATEDON
FROM V2_TBL_COLLATERAL_MARGIN_COMBINE WITH (NOLOCK)
WHERE SEGMENT='CAPITAL' AND EFFDATE BETWEEN @RUNDATE AND @RUNDATE + ' 23:59:59'

DECLARE @DIRCOLLNAMEAMC VARCHAR(100) = 
'J:\BACKOFFICE\EXPORT\' +'COLLATERAL_DATA_CASH_' + CONVERT(VARCHAR, CONVERT(DATETIME,@RUNDATE), 112) + '.CSV'

DECLARE @CASH VARCHAR(MAX)                            
SET @CASH = 'EXEC MASTER.DBO.XP_CMDSHELL ''BCP "SELECT ''''EXCHANGE'''',''''SEGMENT'''',''''PARTY_CODE'''',''''COLL_TYPE'''',''''SCRIP_CD'''',''''SERIES'''',''''ISIN'''',''''QTY'''',''''MRG_CL_RATE'''',''''AMOUNT'''',''''MRG_VAR_MARGIN'''',''''FINALAMOUNT'''',''''EFFDATE'''',''''CREATEDON''''' 
SET @CASH = @CASH + ' UNION ALL SELECT EXCHANGE,SEGMENT,PARTY_CODE,COLL_TYPE,SCRIP_CD,SERIES,ISIN,CONVERT(VARCHAR,QTY),CONVERT(VARCHAR,MRG_CL_RATE),CONVERT(VARCHAR,AMOUNT),CONVERT(VARCHAR,MRG_VAR_MARGIN),CONVERT(VARCHAR,FINALAMOUNT),CONVERT(VARCHAR,EFFDATE),CONVERT(VARCHAR,CREATEDON) FROM MSAJAG.DBO.TBL_COLLATERAL_EXPORT" QUERYOUT ' +@DIRCOLLNAMEAMC+ ' -c -t"," -c -t"," -r"\n" -T'', NO_OUTPUT'
EXEC(@CASH)

SELECT 'Collateral Cash Data Exported to ' + 'J:\BACKOFFICE\EXPORT\' +'COLLATERAL_DATA_CASH_' + CONVERT(VARCHAR, CONVERT(DATETIME,@RUNDATE), 112) + '.CSV'
END

IF @REPORT = 'FUTURES'
BEGIN

TRUNCATE TABLE TBL_COLLATERAL_EXPORT

INSERT INTO TBL_COLLATERAL_EXPORT
SELECT EXCHANGE,SEGMENT,PARTY_CODE,COLL_TYPE,SCRIP_CD,SERIES,ISIN,QTY,MRG_CL_RATE,AMOUNT,MRG_VAR_MARGIN,FINALAMOUNT,EFFDATE,CREATEDON
FROM V2_TBL_COLLATERAL_MARGIN_COMBINE WITH (NOLOCK)
WHERE SEGMENT='FUTURES' AND EFFDATE BETWEEN @RUNDATE AND @RUNDATE + ' 23:59:59'

DECLARE @DIRCOLLNAMEAMF VARCHAR(100) = 
'J:\BACKOFFICE\EXPORT\' +'COLLATERAL_DATA_FUTURES_' + CONVERT(VARCHAR, CONVERT(DATETIME,@RUNDATE), 112) + '.CSV'

DECLARE @FNO VARCHAR(MAX)                            
SET @FNO = 'EXEC MASTER.DBO.XP_CMDSHELL ''BCP "SELECT ''''EXCHANGE'''',''''SEGMENT'''',''''PARTY_CODE'''',''''COLL_TYPE'''',''''SCRIP_CD'''',''''SERIES'''',''''ISIN'''',''''QTY'''',''''MRG_CL_RATE'''',''''AMOUNT'''',''''MRG_VAR_MARGIN'''',''''FINALAMOUNT'''',''''EFFDATE'''',''''CREATEDON''''' 
SET @FNO = @FNO + ' UNION ALL SELECT EXCHANGE,SEGMENT,PARTY_CODE,COLL_TYPE,SCRIP_CD,SERIES,ISIN,CONVERT(VARCHAR,QTY),CONVERT(VARCHAR,MRG_CL_RATE),CONVERT(VARCHAR,AMOUNT),CONVERT(VARCHAR,MRG_VAR_MARGIN),CONVERT(VARCHAR,FINALAMOUNT),CONVERT(VARCHAR,EFFDATE),CONVERT(VARCHAR,CREATEDON) FROM MSAJAG.DBO.TBL_COLLATERAL_EXPORT" QUERYOUT ' +@DIRCOLLNAMEAMF+ ' -c -t"," -c -t"," -r"\n" -T'', NO_OUTPUT'
EXEC(@FNO)

SELECT 'Collateral Futures Data Exported to ' + 'J:\BACKOFFICE\EXPORT\' +'COLLATERAL_DATA_FUTURES_' + CONVERT(VARCHAR, CONVERT(DATETIME,@RUNDATE), 112) + '.CSV'
END

IF @REPORT = 'MRGRATE'
BEGIN

TRUNCATE TABLE TBL_COLLATERAL_EXPORT

INSERT INTO TBL_COLLATERAL_EXPORT
SELECT EXCHANGE,SEGMENT,PARTY_CODE,COLL_TYPE,SCRIP_CD,SERIES,ISIN,QTY,MRG_CL_RATE,AMOUNT,MRG_VAR_MARGIN,FINALAMOUNT,EFFDATE,CREATEDON
FROM V2_TBL_COLLATERAL_MARGIN_COMBINE WITH (NOLOCK)
WHERE MRG_CL_RATE ='0' AND EFFDATE BETWEEN @RUNDATE AND @RUNDATE + ' 23:59:59'

DECLARE @DIRCOLLNAMEAMR VARCHAR(100) = 
'J:\BACKOFFICE\EXPORT\' +'COLLATERAL_DATA_MRGRATE_' + CONVERT(VARCHAR, CONVERT(DATETIME,@RUNDATE), 112) + '.CSV'

DECLARE @MRGRATE VARCHAR(MAX)                            
SET @MRGRATE = 'EXEC MASTER.DBO.XP_CMDSHELL ''BCP "SELECT ''''EXCHANGE'''',''''SEGMENT'''',''''PARTY_CODE'''',''''COLL_TYPE'''',''''SCRIP_CD'''',''''SERIES'''',''''ISIN'''',''''QTY'''',''''MRG_CL_RATE'''',''''AMOUNT'''',''''MRG_VAR_MARGIN'''',''''FINALAMOUNT'''',''''EFFDATE'''',''''CREATEDON''''' 
SET @MRGRATE = @MRGRATE + ' UNION ALL SELECT EXCHANGE,SEGMENT,PARTY_CODE,COLL_TYPE,SCRIP_CD,SERIES,ISIN,CONVERT(VARCHAR,QTY),CONVERT(VARCHAR,MRG_CL_RATE),CONVERT(VARCHAR,AMOUNT),CONVERT(VARCHAR,MRG_VAR_MARGIN),CONVERT(VARCHAR,FINALAMOUNT),CONVERT(VARCHAR,EFFDATE),CONVERT(VARCHAR,CREATEDON) FROM MSAJAG.DBO.TBL_COLLATERAL_EXPORT" QUERYOUT ' +@DIRCOLLNAMEAMR+ ' -c -t"," -c -t"," -r"\n" -T'', NO_OUTPUT'
EXEC(@MRGRATE)

SELECT 'Collateral MRG Rate Data Exported to ' + 'J:\BACKOFFICE\EXPORT\' +'COLLATERAL_DATA_MRGRATE_' + CONVERT(VARCHAR, CONVERT(DATETIME,@RUNDATE), 112) + '.CSV'
END

GO
