-- Object: PROCEDURE dbo.PROC_ALL_REPLEDGE_CALCULATION
-- Server: 10.253.33.91 | DB: MSAJAG
--------------------------------------------------

    
CREATE PROCEDURE [dbo].[PROC_ALL_REPLEDGE_CALCULATION] (@RPT_DATE VARCHAR(11),@REPORT VARCHAR(10))    
    
AS ---- PROC_ALL_REPLEDGE_CALCULATION 'SEP 12 2022',''    
    
DECLARE @PRV_DATE VARCHAR(11),@EPN_SETT_NO VARCHAR(11)    
    
SELECT @EPN_SETT_NO = SETT_NO-1 FROM SETT_MST WHERE SETT_TYPE='N' AND START_DATE  BETWEEN @RPT_DATE AND @RPT_DATE + ' 23:59:59'    
SELECT @PRV_DATE = LEFT(START_DATE,11) FROM SETT_MST WHERE SETT_TYPE='N' AND SETT_NO = @EPN_SETT_NO    
    
CREATE TABLE #CMPHOLD ( [SCRIP_CD] VARCHAR(12), [SERIES] VARCHAR(3),     
[PARTY_CODE] VARCHAR(10), [SETT_NO] VARCHAR(7), [SETT_TYPE] VARCHAR(2),     
[QTY] DECIMAL(38,0), [CERTNO] VARCHAR(16), [BDPID] VARCHAR(16), [BCLTDPID] VARCHAR(16),    
[INVQTY] DECIMAL(38,0), [FREE_QTY] DECIMAL(38,0), [REPLEDGEQTY] DECIMAL(38,0),     
[PARTY_NAME] VARCHAR(100), [LONG_NAME] VARCHAR(100), [CL_TYPE] VARCHAR(3) )    
    
INSERT INTO #CMPHOLD    
EXEC ANGELDEMAT.MSAJAG.DBO.Rpt_NseDelHoldParty 'broker','broker','A','ZZZZZZZZZZZZZZ','0','zzzz','','','%','%','ALL'    
    
    
/* Exchange Repledge Stock Details */    
    
DELETE FROM TBL_ALL_REPLD_STOCK WHERE REPORT_DATE = @RPT_DATE    
    
INSERT INTO TBL_ALL_REPLD_STOCK    
SELECT CONVERT(DATETIME,@RPT_DATE,103),PARTY_CODE,SCRIP_CD,SERIES='',CERTNO,REPLEDGEQTY=SUM(REPLEDGEQTY),    
CLRATE=CONVERT(MONEY,0),CCVAR=CONVERT(MONEY,0),CCVAR_HVALUE=CONVERT(MONEY,0),    
NRVAR=CONVERT(MONEY,0),NRVAR_HVALUE=CONVERT(MONEY,0),DIFF_HVALUE=CONVERT(MONEY,0),GETDATE()     
FROM #CMPHOLD WHERE BCLTDPID='1203320030135814' AND REPLEDGEQTY <> 0    
GROUP BY PARTY_CODE,SCRIP_CD,CERTNO    
    
    
/* ELIGIBLE STOCK MINUS FROM CMP STOCK */    
    
UPDATE A SET REPLEDGEQTY = REPLEDGEQTY - DIFF_QTY FROM TBL_ALL_REPLD_STOCK A,    
(SELECT REPORT_DATE,PARTY_CODE,ISIN,SYMBOL,DIFF_QTY=SUM(DIFF_QTY) FROM     
(SELECT REPORT_DATE,PARTY_CODE,ISIN,SYMBOL,DIFF_QTY FROM TBL_ALL_ELIGIBLE_QTY_CM WHERE DIFF_QTY <> 0    
UNION ALL    
SELECT REPORT_DATE,PARTY_CODE,ISIN,SYMBOL,DIFF_QTY FROM TBL_ALL_ELIGIBLE_QTY_CD WHERE DIFF_QTY <> 0) C    
GROUP BY REPORT_DATE,PARTY_CODE,ISIN,SYMBOL) B     
WHERE A.REPORT_DATE = B.REPORT_DATE AND A.PARTY_CODE = B.PARTY_CODE AND A.CERTNO = B.ISIN AND A.REPORT_DATE = @RPT_DATE    
    
    
DELETE FROM TBL_ALL_RELEASE_STOCK WHERE REPORT_DATE = @RPT_DATE    
    
INSERT INTO TBL_ALL_RELEASE_STOCK    
SELECT CONVERT(DATETIME,@RPT_DATE,103),PARTY_CODE,SCRIP_CD,SERIES,CERTNO,REPLEDGEQTY,RELEASE_QTY,    
MINREL_QTY=CONVERT(INT,0),CLRATE,CCVAR,CCVAR_HVALUE,GETDATE()     
FROM TBL_ALL_REPLD_STOCK A,    
(SELECT CLTCODE,ISIN,RELEASE_QTY=SUM(RELEASE_QTY) FROM TBL_ALL_EXCH_RELEASE WHERE REPORT_DATE=@RPT_DATE GROUP BY CLTCODE,ISIN) B    
WHERE A.PARTY_CODE = B.CLTCODE AND A.CERTNO = B.ISIN AND A.REPORT_DATE = @RPT_DATE    
    
UPDATE A SET MINREL_QTY = MINQTY FROM TBL_ALL_RELEASE_STOCK A,    
(SELECT PARTY_CODE,CERTNO,(SELECT MIN(NSECM) FROM ( VALUES (REPLEDGEQTY),(RELEASE_QTY)) AS NSECM (NSECM)) AS MINQTY    
FROM TBL_ALL_RELEASE_STOCK) B WHERE A.PARTY_CODE = B.PARTY_CODE AND A.CERTNO = B.CERTNO AND REPORT_DATE = @RPT_DATE    
    
UPDATE A SET CLRATE = CL_RATE FROM TBL_ALL_RELEASE_STOCK A,    
(SELECT SYSDATE,SCRIP_CD,SERIES,ISIN,CL_RATE FROM AngelNSECM.MSAJAG.DBO.CLOSING_MTM B WITH (NOLOCK) WHERE SYSDATE = @PRV_DATE) B    
WHERE A.CERTNO = B.ISIN AND REPORT_DATE = @RPT_DATE    
    
UPDATE A SET CLRATE = NAV_VALUE FROM TBL_ALL_RELEASE_STOCK A,    
(SELECT ISIN,NAV_VALUE FROM ANGELFO.BSEMFSS.DBO.MFSS_NAV WITH (NOLOCK) WHERE NAV_DATE BETWEEN @PRV_DATE AND @PRV_DATE + ' 23:59:59') B    
WHERE A.CERTNO = B.ISIN AND CLRATE=0 AND REPORT_DATE = @RPT_DATE    
    
UPDATE A SET CCVAR = HAIRCUT FROM TBL_ALL_RELEASE_STOCK A,    
(SELECT DISTINCT ISIN,HAIRCUT FROM TBL_CCCM_SCRIP_DATA WITH (NOLOCK) WHERE RECORDDATE= @PRV_DATE) B WHERE A.CERTNO = B.ISIN AND REPORT_DATE = @RPT_DATE    
    
UPDATE TBL_ALL_RELEASE_STOCK SET HVALUE = (MINREL_QTY*CLRATE)*((100-CCVAR))/100 WHERE REPORT_DATE = @RPT_DATE    
    
    
/* EXCHANGE RELESE STOCK MINUS FROM CMP STOCK */    
    
    
UPDATE A SET REPLEDGEQTY = REPLEDGEQTY - RELEASE_QTY FROM TBL_ALL_REPLD_STOCK A,    
(SELECT CLTCODE,ISIN,RELEASE_QTY=SUM(RELEASE_QTY) FROM TBL_ALL_EXCH_RELEASE WHERE REPORT_DATE=@RPT_DATE GROUP BY CLTCODE,ISIN) B    
WHERE A.PARTY_CODE = B.CLTCODE AND A.CERTNO = B.ISIN AND A.REPORT_DATE = @RPT_DATE    
    
UPDATE A SET CLRATE = CL_RATE FROM TBL_ALL_REPLD_STOCK A,    
(SELECT SYSDATE,SCRIP_CD,SERIES,ISIN,CL_RATE FROM  MSAJAG.DBO.CLOSING_MTM B WITH (NOLOCK) WHERE SYSDATE = @PRV_DATE) B    
WHERE A.CERTNO = B.ISIN AND REPORT_DATE = @RPT_DATE    
    
UPDATE A SET CLRATE = CL_RATE FROM TBL_ALL_REPLD_STOCK A,    
(SELECT SCRIP_CD,SERIES,CL_RATE FROM CLOSING WITH (NOLOCK) WHERE SysDate = @PRV_DATE) B     
WHERE A.SCRIP_CD = B.SCRIP_CD AND REPORT_DATE = @RPT_DATE AND CLRATE=0    
    
UPDATE A SET CLRATE = NAV_VALUE FROM TBL_ALL_REPLD_STOCK A,    
(SELECT ISIN,NAV_VALUE FROM ANGELFO.BSEMFSS.DBO.MFSS_NAV WITH (NOLOCK) WHERE NAV_DATE BETWEEN @PRV_DATE AND @PRV_DATE + ' 23:59:59') B    
WHERE A.CERTNO = B.ISIN AND CLRATE=0 AND REPORT_DATE = @RPT_DATE    
    
SELECT DISTINCT ISIN,NAV_VALUE INTO #HIST FROM ANGELFO.BSEMFSS.DBO.MFSS_NAV A1 WITH (NOLOCK)     
WHERE NAV_DATE IN (SELECT MAX(NAV_DATE)FROM ANGELFO.BSEMFSS.DBO.MFSS_NAV A2 WITH (NOLOCK) WHERE A1.ISIN = A2.ISIN)   


CREATE INDEX #C ON #HIST( ISIN,NAV_VALUE)
    
UPDATE A SET CLRATE = NAV_VALUE FROM TBL_ALL_REPLD_STOCK A,#HIST B WHERE A.REPORT_DATE = @RPT_DATE AND A.CERTNO = B.ISIN AND A.CLRATE=0     

SELECT CLOPM_ISIN_CD,CLOPM_CDSL_RT,CLOPM_DT INTO #MF FROM AGMUBODPL3.DMAT.CITRUS_USR.CLOSING_LAST_CDSL A WiTH(NOLOCK)    
WHERE CLOPM_DT IN (SELECT MAX(CLOPM_DT)     
FROM AGMUBODPL3.DMAT.CITRUS_USR.CLOSING_LAST_CDSL B WiTH(NOLOCK)     WHERE A.CLOPM_ISIN_CD = B.CLOPM_ISIN_CD)

CREATE INDEX #S ON #MF(CLOPM_ISIN_CD)
    
UPDATE TBL_ALL_REPLD_STOCK SET CLRATE = CLOPM_CDSL_RT FROM TBL_ALL_REPLD_STOCK A1,    
(SELECT CLOPM_ISIN_CD,CLOPM_CDSL_RT,CLOPM_DT FROM #MF) A2    
WHERE A1.CERTNO = A2.CLOPM_ISIN_CD AND CLRATE=0 AND REPORT_DATE = @RPT_DATE    
  
  --CREATE NONCLUSTERED INDEX [TBL_CCCM_SCRIP_DATA_temp] ON [dbo].[TBL_CCCM_SCRIP_DATA] ([RECORDDATE],[SCRIP_CD],[ISIN]) INCLUDE ([HAIRCUT])  

  SELECT DISTINCT ISIN,HAIRCUT INTO #PREVHAIRCUT FROM TBL_CCCM_SCRIP_DATA WITH (NOLOCK) WHERE RECORDDATE = @PRV_DATE
  CREATE INDEX IX_ISIN ON #PREVHAIRCUT(ISIN)
  
UPDATE A SET CCVAR = HAIRCUT FROM TBL_ALL_REPLD_STOCK A,    
(SELECT DISTINCT ISIN,HAIRCUT FROM #PREVHAIRCUT WITH (NOLOCK) ) B WHERE  REPORT_DATE = @RPT_DATE AND A.CERTNO = B.ISIN    
    
UPDATE TBL_ALL_REPLD_STOCK SET CCVAR_HVALUE = (REPLEDGEQTY*CLRATE)*((100-CCVAR))/100 WHERE REPORT_DATE = @RPT_DATE

SELECT ISIN,APPVAR INTO #VARDETAIL FROM VARDETAIL WITH(NOLOCK) WHERE DETAILKEY=REPLACE(CONVERT(VARCHAR(11),CONVERT(DATETIME,@PRV_DATE),105),'-','')
  CREATE INDEX IX_ISIN ON #VARDETAIL(ISIN)
    
UPDATE A SET NRVAR = APPVAR  FROM TBL_ALL_REPLD_STOCK A,    
(SELECT ISIN,APPVAR FROM #VARDETAIL) B WHERE A.CERTNO = B.ISIN    
    
UPDATE TBL_ALL_REPLD_STOCK SET NRVAR_HVALUE = (REPLEDGEQTY*CLRATE)*((100-NRVAR))/100 WHERE REPORT_DATE = @RPT_DATE    
    
UPDATE TBL_ALL_REPLD_STOCK SET DIFF_HVALUE = NRVAR_HVALUE-CCVAR_HVALUE WHERE REPORT_DATE = @RPT_DATE    
    
UPDATE TBL_ALL_REPLD_STOCK SET DIFF_HVALUE = 0 WHERE REPORT_DATE = @RPT_DATE AND DIFF_HVALUE < 0    
    
UPDATE TBL_ALL_REPORT_STATUS SET STATUS ='Completed' WHERE SRNO=7 AND REPORT_DATE = @RPT_DATE    
    
SELECT 'Repledge Stock Calculation Process Completed Successfully'

GO
