-- Object: PROCEDURE dbo.CONTRACT_DATA_EQ_COMM
-- Server: 10.253.33.91 | DB: MSAJAG
--------------------------------------------------

  
--EXEC CONTRACT_DATA_EQ_COMM '01/02/2018','28/02/2018','E'  
CREATE PROC CONTRACT_DATA_EQ_COMM  
(  
@fromdate VARCHAR(11),  
@todate VARCHAR(11),  
@RPT_TYPE VARCHAR(1)  
)  
AS  
set @FROMDATE=convert(DATETIME,@fromdate,103)      
 set @TODATE=convert(DATETIME,@todate,103)    
  
IF @RPT_TYPE ='E'  
BEGIN   
  
SELECT DISTINCT PARTY_CODE,CONTRACTNO,L_STATE,CONVERT(VARCHAR(11),SAUDA_DATE ,120) AS SAUDA_DATE  
INTO #EQ FROM COMMON_CONTRACT_DATA WITH (NOLOCK)   
 WHERE SAUDA_DATE>=@FROMDATE AND SAUDA_DATE<=@TODATE + ' 23:59:59'   
  
 SELECT D.*,GST_LOCATION INTO #EQFINAL FROM #EQ D   
 LEFT OUTER JOIN  TBL_CLIENT_GST_DATA T WITH (NOLOCK)  ON D.PARTY_CODE=T.PARTY_CODE  
 AND D.SAUDA_DATE BETWEEN EFF_FROM_DATE AND EFF_TO_DATE   
 WHERE CONTRACTNO<>'0'   
  
  
 UPDATE F SET GST_LOCATION =D.GST_LOCATION FROM  #EQFINAL F,CLIENT_DETAILS D  WHERE F.GST_LOCATION IS NULL  
 AND F.PARTY_CODE=D.PARTY_CODE  
 --AND F.SAUDA_DATE BETWEEN EFF_FROM_DATE AND EFF_TO_DATE  
  
 SELECT GST_LOCATION,L_STATE,COUNT(1) as COUNT_EQ,MONTH(SAUDA_dATE) FROM #EQFINAL  
 GROUP BY GST_LOCATION,L_STATE,MONTH(SAUDA_dATE)  
  
END  
  
IF @RPT_TYPE ='C'  
BEGIN   
  
SELECT DISTINCT PARTY_CODE,CONTRACTNO,L_STATE,CONVERT(VARCHAR(11),SAUDA_DATE ,120) AS SAUDA_DATE  
INTO #COMM FROM [AngelCommodity].MCDX.DBO.COMMON_CONTRACT_DATA WITH (NOLOCK)   
 WHERE SAUDA_DATE>=@FROMDATE AND SAUDA_DATE<=@TODATE + ' 23:59:59'  
  
 SELECT D.*,GST_LOCATION INTO #COMMFINAL FROM #COMM D   
 LEFT OUTER JOIN  [AngelCommodity].MCDX.DBO.TBL_CLIENT_GST_DATA T WITH (NOLOCK)  ON D.PARTY_CODE=T.PARTY_CODE  
 AND D.SAUDA_DATE BETWEEN EFF_FROM_DATE AND EFF_TO_DATE     
 WHERE CONTRACTNO<>'0'   
  
 UPDATE F SET GST_LOCATION =D.GST_LOCATION FROM  #COMMFINAL F,[AngelCommodity].MCDX.DBO.TBL_CLIENT_GST_DATA D  WHERE F.GST_LOCATION IS NULL  
 AND F.PARTY_CODE=D.PARTY_CODE  
 AND F.SAUDA_DATE BETWEEN EFF_FROM_DATE AND EFF_TO_DATE  
  
  UPDATE F SET GST_LOCATION =D.GST_LOCATION FROM  #COMMFINAL F,[AngelCommodity].NCDX.DBO.TBL_CLIENT_GST_DATA D  WHERE F.GST_LOCATION IS NULL  
 AND F.PARTY_CODE=D.PARTY_CODE  
 AND F.SAUDA_DATE BETWEEN EFF_FROM_DATE AND EFF_TO_DATE  
  
 SELECT GST_LOCATION,L_STATE,COUNT(1) as COUNT_COMM,MONTH(SAUDA_dATE) FROM #COMMFINAL  
 GROUP BY GST_LOCATION,L_STATE,MONTH(SAUDA_dATE)  
  
END

GO
