-- Object: PROCEDURE dbo.INSDELTRANSPRINTPOOLIST
-- Server: 10.253.33.91 | DB: MSAJAG
--------------------------------------------------


CREATE PROC [dbo].[INSDELTRANSPRINTPOOLIST] (@OPTFLAG INT, @BDPTYPE VARCHAR(4), @BDPID VARCHAR(8), @BCLTDPID VARCHAR(16),  
@CATEGORY VARCHAR(10), @BRANCHCODE VARCHAR(10))   
AS  
DECLARE   
@SETT_NO VARCHAR(7),  
@SETT_TYPE VARCHAR(2),  
@SNO NUMERIC,  
@QTY NUMERIC(18,3),  
@DIFFQTY NUMERIC(18,3),  
@SLIPNO INT,  
@BATCHNO INT,  
@TRANSDATE VARCHAR(11),  
@HOLDERNAME VARCHAR(30),  
@FOLIONO VARCHAR(20),  
@PARTY_CODE VARCHAR(10),  
@CERTNO VARCHAR(12),  
@TRTYPE INT,  
@DPID VARCHAR(8),  
@CLTDPID VARCHAR(16),  
@DELBDPID VARCHAR(8),  
@DELBCLTDPID VARCHAR(16),  
@ALLQTY NUMERIC(18,3),  
@DELCUR CURSOR,  
@BENCUR CURSOR  
  
IF @OPTFLAG = 1   
BEGIN  
	UPDATE DELTRANS SET DELIVERED = 'G', SLIPNO = D.SLIPNO,   
	BATCHNO = D.BATCHNO, FOLIONO = D.FOLIONO,  
	TRANSDATE = D.TRANSDATE, HOLDERNAME = D.HOLDERNAME  
	FROM DELTRANSPRINTPOOL D  
	WHERE DELTRANS.SETT_NO = D.SETT_NO  
	AND DELTRANS.SETT_TYPE = D.SETT_TYPE  
	AND DELTRANS.PARTY_CODE >= D.FROMPARTY  
	AND DELTRANS.PARTY_CODE <= D.TOPARTY   
	AND DELTRANS.PARTY_CODE = (CASE WHEN D.PARTY_CODE = 'INTER' OR D.PARTY_CODE = '' THEN DELTRANS.PARTY_CODE ELSE D.PARTY_CODE END)
	AND DELTRANS.CERTNO = D.CERTNO  
	AND DELTRANS.TRTYPE = D.TRTYPE  
	AND FILLER2 = 1  
	AND DRCR = 'D'  
	AND DELTRANS.BDPTYPE = D.BDPTYPE  
	AND DELTRANS.BDPID = D.BDPID  
	AND DELTRANS.BCLTDPID = D.BCLTDPID  
	AND DELIVERED = '0'  
	AND DELTRANS.ISETT_NO = D.ISETT_NO  
	AND DELTRANS.ISETT_TYPE = D.ISETT_TYPE  
	AND OPTIONFLAG = 1  AND DELTRANS.PARTY_CODE <> 'BROKER'  
END

GO
