-- Object: PROCEDURE dbo.RPT_WEEKLY_CLIENT_CASH_BALANCE_WRAPPER
-- Server: 10.253.33.91 | DB: MSAJAG
--------------------------------------------------


-- [RPT_WEEKLY_CLIENT_CASH_BALANCE_WRAPPER] '23/04/2021','23/04/2021','00','zzzzz' 

CREATE PROC [dbo].[RPT_WEEKLY_CLIENT_CASH_BALANCE_WRAPPER] 
( 
@FROMDATE VARCHAR(12), 
@TODATE VARCHAR(12) ,
@FROMCODE_PARAM VARCHAR(50),
@TOCODE_PARAM VARCHAR(50)
) 
AS 

BEGIN 

DECLARE @SESSION_ID VARCHAR(15), @FD VARCHAR(12) 

SELECT @SESSION_ID= SESSIONID FROM ACCOUNT..VW_SESSIONID 

SET @FROMDATE =  CONVERT(DATETIME,@FROMDATE,103) 
SET @TODATE =  CONVERT(DATETIME,@TODATE,103) 

CREATE TABLE #TMP_CLTLIST
(
	SNO INT IDENTITY(1, 1),
	CLTCODE VARCHAR(10),
	BATCHNO INT
)

INSERT INTO #TMP_CLTLIST
SELECT CL_CODE,0 FROM CLIENT_DETAILS where cl_code between @FROMCODE_PARAM and @TOCODE_PARAM order by cl_code

UPDATE #TMP_CLTLIST SET BATCHNO = (SNO / 1000000) + 1

--select * from #TMP_CLTLIST

DECLARE @MIN INT 
DECLARE @MAX INT 
DECLARE @FROMCODE VARCHAR(50)
DECLARE @TOCODE VARCHAR(50)

SET @MIN = 1 
SELECT @MAX = MAX(BATCHNO) FROM #TMP_CLTLIST

WHILE(@MIN <= @MAX)
BEGIN


SELECT @FROMCODE = MIN(CLTCODE), @TOCODE=MAX(CLTCODE) FROM #TMP_CLTLIST WHERE BATCHNO = @MIN

EXEC RPT_WEEKLY_CLIENT_CASH_BALANCE_NEW_NCX_FILEGEN @FROMDATE, @TODATE,@FROMCODE,@TOCODE,'NCX','',1 


DECLARE @@FILELOC VARCHAR(500), @@QUERY VARCHAR(500), @@SQL VARCHAR(100), @@FILENAME VARCHAR(100), @@FILEPATH VARCHAR(100) 
SELECT @@FILEPATH = FILEPATH FROM MSAJAG..WEEKLY_CASH_BALANCES_SETTING 

SELECT TOP 1  @@FILENAME  = 'BATCH_' + convert(varchar,@MIN)+ '_' + FNAME  FROM  TMP_WEEKLY_CLIENT_CASH_FILENAME 


SELECT @@FILELOC =  @@FILEPATH  + @@FILENAME  
SELECT @@FILENAME AS FILENAME1, @@FILELOC AS FILEPATH 

SET @@QUERY = ' BCP "SELECT REPORTDATA FROM MSAJAG.DBO.TMP_WEEKLY_CLIENT_CASH ORDER BY SRNO' + '" QUERYOUT "' + @@FILELOC + '" -c -q -T' 
PRINT @@QUERY 
EXEC MASTER.DBO.XP_CMDSHELL @@QUERY, no_output 

--SELECT @FROMCODE , @TOCODE
--SELECT @MIN
SET @MIN= @MIN+1
END
drop table #TMP_CLTLIST
end

GO
