-- Object: PROCEDURE dbo.PROC_SHORT_MARGIN_INTRA_INSERT
-- Server: 10.253.33.91 | DB: MSAJAG
--------------------------------------------------


CREATE PROC [dbo].[PROC_SHORT_MARGIN_INTRA_INSERT]
(
	@MARGINDATE	VARCHAR(11),
	@FLDFILENAME	VARCHAR(500),
	@UPLOAD_BY		VARCHAR(50) = 'AUTO'
)
AS
DECLARE
	@FILENAME VARCHAR(50)
SELECT @FILENAME = RIGHT(@FLDFILENAME, CHARINDEX('\', REVERSE(@FLDFILENAME),0) - 1)

DECLARE @EXCHANGE	VARCHAR(3),
		@SEGMENT	VARCHAR(7)
		
SET @EXCHANGE = 'NSE'
SET @SEGMENT = 'CAPITAL'

IF @FILENAME LIKE '%C_SA01%'
BEGIN		
	SET @EXCHANGE = 'NSE'
	SET @SEGMENT = 'CAPITAL'
END
IF @FILENAME LIKE '%F_SA01%'
BEGIN
	SET @EXCHANGE = 'NSE'
	SET @SEGMENT = 'FUTURES'
END
IF @FILENAME LIKE '%X_SA01%'
BEGIN
	SET @EXCHANGE = 'NSX'
	SET @SEGMENT = 'FUTURES'
END

IF @FILENAME LIKE '%MCX_PEAK%'
BEGIN
	SET @EXCHANGE = 'MCX'
	SET @SEGMENT = 'FUTURES'
END

IF @FILENAME LIKE '%NCCL_MARGIN%'
BEGIN
	SET @EXCHANGE = 'NCX'
	SET @SEGMENT = 'FUTURES'
END

DECLARE @INDICATOR VARCHAR(3)
	
DECLARE @UPLOAD_ON DATETIME
SET @UPLOAD_ON = GETDATE()

IF @EXCHANGE IN ('NSE','NSX')
BEGIN
	SELECT @INDICATOR = RIGHT(REPLACE(@FLDFILENAME, '.LIS', ''), 2)

	INSERT INTO TBL_SHORT_ALLOC_INTRADAY_LOG
	SELECT *, @UPLOAD_ON FROM TBL_SHORT_ALLOC_INTRADAY 
	WHERE MARGINDATE = @MARGINDATE AND INDICATOR = @INDICATOR AND EXCHANGE = @EXCHANGE AND SEGMENT = @SEGMENT

	DELETE FROM TBL_SHORT_ALLOC_INTRADAY WHERE MARGINDATE = @MARGINDATE AND INDICATOR = @INDICATOR 
	AND EXCHANGE = @EXCHANGE AND SEGMENT = @SEGMENT
	
	INSERT INTO TBL_SHORT_ALLOC_INTRADAY
	SELECT MARGINDATE = @MARGINDATE,@INDICATOR,@EXCHANGE,@SEGMENT,Client_CODE,Margin_Req,Total_Cash_Coll,Total_NonCash_Coll,
	Excess_Other_Seg=0,Total_value_Coll,EOD_Short_Alloc,@FILENAME,@UPLOAD_BY,@UPLOAD_ON
	FROM TBL_CAPITAL_SHORT_ALLOC_INTRADAY_TMP
	WHERE MARGINDATE = @MARGINDATE 
END

IF @EXCHANGE = 'MCX'
BEGIN  
	SELECT @INDICATOR = '0' + CONVERT(VARCHAR, CONVERT(INT, RIGHT(REPLACE(@FLDFILENAME, '.CSV', ''), 2)) - 1)
	 
	INSERT INTO TBL_MCX_SHORT_ALLOC_INTRADAY_LOG
	SELECT *, @UPLOAD_ON FROM TBL_MCX_SHORT_ALLOC_INTRADAY WHERE MARGINDATE = @MARGINDATE AND INDICATOR = @INDICATOR

	DELETE FROM TBL_MCX_SHORT_ALLOC_INTRADAY WHERE MARGINDATE = @MARGINDATE AND INDICATOR = @INDICATOR
	
	INSERT INTO TBL_MCX_SHORT_ALLOC_INTRADAY
	SELECT MARGINDATE = CONVERT(DATETIME, MARGINDATE, 103),@INDICATOR,SNAP_TIME,CMID,TMID,CLIENT_CODE,INITIALMARGIN,ELM,NET_BUY_PREMIUM,
	TOT_UPFRONT_MARGIN,CLT_MARGIN_ALLOC,CLT_OTHER_COLL,SHORT_ALLOC,@INDICATOR,@UPLOAD_BY,@UPLOAD_ON
	FROM TBL_MCX_SHORT_ALLOC_INTRADAY_TMP WHERE MARGINDATE = @MARGINDATE
END

IF @EXCHANGE = 'NCX'
BEGIN  
	SELECT @INDICATOR = '0' + CONVERT(VARCHAR, CONVERT(INT, RIGHT(REPLACE(@FLDFILENAME, '.CSV', ''), 2)) - 1)
	  
	DELETE FROM TBL_NCX_SHORT_ALLOC_INTRADAY WHERE MARGINDATE = @MARGINDATE AND INDICATOR = @INDICATOR
	
	INSERT INTO TBL_NCX_SHORT_ALLOC_INTRADAY
	SELECT *,@FILENAME,@UPLOAD_BY,@UPLOAD_ON
	FROM TBL_NCX_SHORT_ALLOC_INTRADAY_TMP WHERE MARGINDATE = @MARGINDATE
END

GO
