-- Object: PROCEDURE dbo.RPT_RMSDEBITSTOCK_REPORT
-- Server: 10.253.33.91 | DB: MSAJAG
--------------------------------------------------




CREATE PROC RPT_RMSDEBITSTOCK_REPORT  
(@RMSDATE VARCHAR(11),  
 @PARENTCODE VARCHAR(10),  
 @PARTY_CODE VARCHAR(10)  
)  
AS  
  
SELECT PARENTCODE, PARTY_CODE, LONG_NAME, SCRIP_CD, SERIES, SCRIP_NAME, CERTNO,  
UN_BENHOLDQTY = SUM(CASE WHEN PLEDGE <> 'Y' THEN BENHOLD ELSE 0 END),  
UN_BENHOLD = SUM(CASE WHEN PLEDGE <> 'Y' THEN BENHOLD * CL_RATE ELSE 0 END) -   
       SUM(CASE WHEN PLEDGE <> 'Y' THEN BENHOLD * CL_RATE * VARMARGIN / 100 ELSE 0 END),   
BENHOLDQTY = SUM(CASE WHEN PLEDGE = 'Y' THEN BENHOLD ELSE 0 END),  
BENHOLD = SUM(CASE WHEN PLEDGE = 'Y' THEN BENHOLD * CL_RATE ELSE 0 END) -   
       SUM(CASE WHEN PLEDGE = 'Y' THEN BENHOLD * CL_RATE * VARMARGIN / 100 ELSE 0 END),  
UN_POAHOLDQTY = SUM(CASE WHEN PLEDGE <> 'Y' THEN POAHOLD ELSE 0 END),  
UN_POAHOLD = SUM(CASE WHEN PLEDGE <> 'Y' THEN POAHOLD * CL_RATE ELSE 0 END) -   
          SUM(CASE WHEN PLEDGE <> 'Y' THEN POAHOLD * CL_RATE * VARMARGIN / 100 ELSE 0 END),   
POAHOLDQTY = SUM(CASE WHEN PLEDGE = 'Y' THEN POAHOLD ELSE 0 END),  
POAHOLD = SUM(CASE WHEN PLEDGE = 'Y' THEN POAHOLD * CL_RATE ELSE 0 END) -   
       SUM(CASE WHEN PLEDGE = 'Y' THEN POAHOLD * CL_RATE * VARMARGIN / 100 ELSE 0 END),   
POOLHOLDQTY = SUM(POOLHOLD),  
POOLHOLD = SUM(POOLHOLD * CL_RATE) - SUM(POOLHOLD * CL_RATE * VARMARGIN / 100),  
UN_BUYOPENPOSQTY = SUM(CASE WHEN PLEDGE <> 'Y' THEN BUYOPENPOS ELSE 0 END),  
UN_BUYOPENPOS = SUM(CASE WHEN PLEDGE <> 'Y' THEN (BUYOPENPOS * CL_RATE) - (BUYOPENPOS * CL_RATE * VARMARGIN / 100) ELSE 0 END),   
BUYOPENPOSQTY = SUM(CASE WHEN PLEDGE = 'Y' THEN BUYOPENPOS ELSE 0 END),  
BUYOPENPOS = SUM(CASE WHEN PLEDGE = 'Y' THEN (BUYOPENPOS * CL_RATE) - (BUYOPENPOS * CL_RATE * VARMARGIN / 100) ELSE 0 END),   
SELLOPENPOSQTY = SUM(SELLOPENPOS),  
SELLOPENPOS = SUM(SELLOPENPOS * CL_RATE) + SUM(SELLOPENPOS * CL_RATE * VARMARGIN / 100),   
SELLSHORTQTY = SUM(SELLSHORT),  
SELLSHORT = SUM(SELLSHORT * CL_RATE) + SUM(SELLSHORT * CL_RATE * VARMARGIN / 100),  
NDBUYPOSQTY = SUM(NDBUYPOS),  
NDBUYPOS = SUM(NDBUYPOS * CL_RATE) + SUM(NDBUYPOS * CL_RATE * VARMARGIN / 100),   
EPN_PNL = SUM(EPN_PNL), EXCHANGE, SEGMENT='CAPITAL', VARMARGIN, CL_RATE  
FROM (  
SELECT EXCHANGE = (CASE WHEN D.BRANCH_CD = 'BSE' THEN 'BSE' ELSE 'NSE' END),   
PARENTCODE = C1.PARTY_CODE,   
D.PARTY_CODE, C1.LONG_NAME,   
SCRIP_CD, SERIES, SCRIP_NAME,  
BENHOLD = SUM(CASE WHEN HOLDFLAG = 'HOLD' THEN DEBITQTY ELSE 0 END),  
POAHOLD = SUM(CASE WHEN HOLDFLAG = 'POA' THEN DEBITQTY ELSE 0 END),  
POOLHOLD = SUM(PAYQTY),
BUYOPENPOS = SUM(CASE WHEN HOLDFLAG <> 'NDPOS' THEN FUTQTY ELSE 0 END),
SELLOPENPOS = (CASE WHEN SUM(SHRTQTY) >= SUM(DEBITQTY)   
     THEN (SUM(SHRTQTY) - SUM(DEBITQTY))              
        ELSE 0  
      END),  
SELLSHORT = SUM(SHRTQTY),  
NDBUYPOS = SUM(CASE WHEN HOLDFLAG = 'NDPOS' THEN FUTQTY ELSE 0 END),  
EPN_PNL = SUM(CASE WHEN HOLDFLAG = 'EPN' OR HOLDFLAG = 'PNL' THEN CL_RATE ELSE 0 END),  
CERTNO, PLEDGE, 
CL_RATE = (CASE WHEN HOLDFLAG = 'EPN' OR HOLDFLAG = 'PNL' THEN 0 ELSE CL_RATE END), 
VARMARGIN  
FROM DELDEBITSUMMARYNEW D, CLIENTTYPE C, CLIENT_DETAILS C1  
WHERE RUNDATE BETWEEN @RMSDATE AND @RMSDATE + ' 23:59'  
AND C1.PARTY_CODE = @PARENTCODE  
AND D.PARTY_CODE = (CASE WHEN @PARTY_CODE = '' THEN D.PARTY_CODE ELSE @PARTY_CODE END)  
AND C1.PARTY_CODE = D.PARTY_CODE AND C.CL_TYPE = C1.CL_TYPE   
AND HOLDFLAG NOT IN ('OPAY', 'OHOLD', 'OMAR', 'OSHRT', 'OPOOL')
GROUP BY (CASE WHEN D.BRANCH_CD = 'BSE' THEN 'BSE' ELSE 'NSE' END),   
D.PARTY_CODE, C1.PARTY_CODE, C1.LONG_NAME, SCRIP_CD, SERIES, SCRIP_NAME, CERTNO, VARMARGIN, PLEDGE, CL_RATE, HOLDFLAG) A  
GROUP BY PARENTCODE, PARTY_CODE, LONG_NAME, EXCHANGE, SCRIP_CD, SERIES, SCRIP_NAME, CERTNO, VARMARGIN, CL_RATE  
ORDER BY PARENTCODE, EXCHANGE, PARTY_CODE, SCRIP_NAME, SCRIP_CD, SERIES

GO
