-- Object: PROCEDURE dbo.RPT_CLIENT_COLL_SEG_NSE_NEW_SEG_DEFAULT_PARA_DATACHK
-- Server: 10.253.33.91 | DB: MSAJAG
--------------------------------------------------





--exec RPT_CLIENT_COLL_SEG_NSE_NEW_SEG_DEFAULT_PARA_DATACHK 'mar 13 2023'


CREATE PROC [dbo].[RPT_CLIENT_COLL_SEG_NSE_NEW_SEG_DEFAULT_PARA_DATACHK]
(
	@RUNDATE	VARCHAR(11),
	@EXCHANGE	VARCHAR(3)='NSE'
)
AS
-- EXEC RPT_CLIENT_COLL_SEG_NSE_NEW_SEG 'JAN 24 2023'

CREATE TABLE #CL_FOR_SETTLEMENT_AMOUNT
(
	PARTY_CODE VARCHAR(10),
	EXCHANGE VARCHAR(10)
)

INSERT INTO #CL_FOR_SETTLEMENT_AMOUNT
SELECT PARTY_CODE, EXCHANGE = MAX(EXCHANGE) FROM CLIENT_COLLATERAL_REPORTING_DETAILS_NEW (NOLOCK)
WHERE PROCESS_DT=@RUNDATE AND Exchange NOT IN ('NSE','NSX','MTF') AND isnull(SETTLEMENT_AMOUNT, 0) <> 0
AND PARTY_CODE NOT IN(SELECT PARTY_CODE FROM CLIENT_COLLATERAL_REPORTING_DETAILS_NEW (NOLOCK)
WHERE PROCESS_DT=@RUNDATE AND Exchange IN ('NSE','NSX','MTF'))
group by PARTY_CODE



SELECT FILENAME=CLEARING_PAN+'_'+REPLACE(CONVERT(VARCHAR,PROCESS_DT,103),'/','')+'_01.csv',
Date=REPLACE(CONVERT(VARCHAR,PROCESS_DT,103),'/','-'),
CLEARING_PAN,TRADING_PAN,CP_CODE,CP_PAN,
CLIENT_PAN=CASE WHEN ACCOUNT_TYPE='P' THEN '' ELSE CASE WHEN CLIENT_PAN LIKE '%[^0-9A-Za-z]%' OR LEN(CLIENT_PAN) <> '10' OR RIGHT(CLIENT_PAN, 1) LIKE '%[^A-Za-z]%' THEN 'NNNNN1111N' 
				ELSE CLIENT_PAN END END,
ACCOUNT_TYPE,SEGMENT_INDICATOR,--MTOM=PARTY_CODE,
MTOM=UPPER(REPLACE(REPLACE(PARTY_CODE,' ',''),'`','')),
VDT_LEDGER,
EDT_LEDGER,
PEAK_LEDGER,
BG_REC_TM,FD_REC_TM,APPROVED_SEC_CASH_REC_TM,APPROVED_SEC_NONCASH_REC_TM,
NONAPPROVED_SEC_REC_TM,CC_APPROVED_COMM_REC_TM,OTHER_COLL_REC_TM,convert(numeric (18,3 ),LIEU_EPI_LEDGER_CLTM ),
POOL_ACCOUNT_CLTM,CASH_RET_TM,BG_RET_TM,FD_RET_TM,APPROVED_SEC_CASH_RET_TM,
APPROVED_SEC_NONCASH_RET_TM,NONAPPROVED_SEC_RET_TM,CC_APPROVED_COMM_RET_TM,OTHER_COLL_RET_TM,
CASH_WCM,BG_WCM,FD_WCM,APPROVED_SEC_CASH_WCM,APPROVED_SEC_NONCASH_WCM,NONAPPROVED_SEC_RET_WCM,
CC_APPROVED_COMM_WCM,OTHER_COLL_WCM,CASH_RET_WCM,BG_RET_CM,FD_RET_CM,APPROVED_SEC_CASH_RET_CM,
APPROVED_SEC_NONCASH_RET_CM,NONAPPROVED_SEC_RET_RET_CM,CC_APPROVED_COMM_RET_CM,OTHER_COLL_RET_CM,
CASH_WNCL,BG_WNCL = convert(numeric (18,3 ),BG_WNCL),FD_WNCL = convert(numeric (18,3 ),FD_WNCL),APPROVED_SEC_CASH_WNCL,APPROVED_SEC_NONCASH_WNCL = convert(numeric (18,3 ),APPROVED_SEC_NONCASH_WNCL),CC_APPROVED_COMM_WNCL,
--MTF_INDICATOR = CASE WHEN EXCHANGE = 'NSE' AND SEGMENT = 'CAPITAL' THEN 'NON MTF' WHEN EXCHANGE = 'MTF' THEN 'MTF' ELSE 'NA' END ,
MTF_INDICATOR = CASE WHEN EXCHANGE = 'MTF' THEN 'MTF' ELSE 'NON MTF' END ,
UNCLEAR_RECEIPT= isnull(UNCLEAR_RECEIPT, 0),GOV_SEC_TBILL_REC_BY_TM = isnull(GOV_SEC_TBILL_REC_BY_TM, 0),GOV_SEC_TBILL_RET_BY_TM = isnull(GOV_SEC_TBILL_RET_BY_TM, 0),GOV_SEC_TBILL_PLACED_BY_CM = isnull(GOV_SEC_TBILL_PLACED_BY_CM,0),GOV_SEC_TBILL_RET_BY_CM = isnull(GOV_SEC_TBILL_RET_BY_CM, 0),GOV_SEC_TBILL_PLACED_BY_NCL = isnull(GOV_SEC_TBILL_PLACED_BY_NCL, 0),
BG_FUNDED_RET_WITH_CM = isnull(BG_FUNDED_RET_WITH_CM, 0),BG_NONFUNDED_RET_WITH_CM = isnull(BG_NONFUNDED_RET_WITH_CM, 0),BG_FUNDED_PLACED_WITH_NCL = isnull(BG_FUNDED_PLACED_WITH_NCL, 0),BG_NONFUNDED_PLACED_WITH_NCL = isnull(BG_NONFUNDED_PLACED_WITH_NCL, 0),SETTLEMENT_AMOUNT = isnull(SETTLEMENT_AMOUNT, 0),UNCLAIM_CL_FUNDS = isnull(UNCLAIM_CL_FUNDS, 'NA'),CASH_COLL_MTF_POSITION = ISNULL(CASH_COLL_MTF_POSITION, 0)
--EXCHANGE,SEGMENT,UPFRONT_MARGIN,PEAK_MARGIN,PARTY_CODE
FROM CLIENT_COLLATERAL_REPORTING_DETAILS_NEW (NOLOCK)
WHERE PROCESS_DT=@RUNDATE
--AND PARTY_CODE='B420108'
AND Exchange IN ('NSE','NSX','MTF')
--AND PARTY_CODE BETWEEN 'A' AND 'ZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZ999999'

UNION ALL

SELECT FILENAME=CLEARING_PAN+'_'+REPLACE(CONVERT(VARCHAR,PROCESS_DT,103),'/','')+'_01.csv',
Date=REPLACE(CONVERT(VARCHAR,PROCESS_DT,103),'/','-'),
CLEARING_PAN,TRADING_PAN,CP_CODE,CP_PAN,
CLIENT_PAN=CASE WHEN ACCOUNT_TYPE='P' THEN '' ELSE CASE WHEN CLIENT_PAN LIKE '%[^0-9A-Za-z]%' OR LEN(CLIENT_PAN) <> '10' OR RIGHT(CLIENT_PAN, 1) LIKE '%[^A-Za-z]%' THEN 'NNNNN1111N' 
				ELSE CLIENT_PAN END END,
ACCOUNT_TYPE,SEGMENT_INDICATOR = 'CM',--MTOM=PARTY_CODE,
MTOM=UPPER(REPLACE(REPLACE(R.PARTY_CODE,' ',''),'`','')),
VDT_LEDGER = 0,
EDT_LEDGER = 0,
PEAK_LEDGER = 0,
BG_REC_TM = 0,FD_REC_TM = 0,APPROVED_SEC_CASH_REC_TM = 0,APPROVED_SEC_NONCASH_REC_TM = 0,
NONAPPROVED_SEC_REC_TM = 0,CC_APPROVED_COMM_REC_TM = 0,OTHER_COLL_REC_TM = 0,convert(numeric (18,3 ),0 ),
POOL_ACCOUNT_CLTM = 0,CASH_RET_TM = 0,BG_RET_TM = 0,FD_RET_TM = 0,APPROVED_SEC_CASH_RET_TM = 0,
APPROVED_SEC_NONCASH_RET_TM = 0,NONAPPROVED_SEC_RET_TM = 0,CC_APPROVED_COMM_RET_TM = 0,OTHER_COLL_RET_TM = 0,
CASH_WCM = 0,BG_WCM = 0,FD_WCM = 0,APPROVED_SEC_CASH_WCM = 0,APPROVED_SEC_NONCASH_WCM = 0,NONAPPROVED_SEC_RET_WCM = 0,
CC_APPROVED_COMM_WCM = 0,OTHER_COLL_WCM = 0,CASH_RET_WCM = 0,BG_RET_CM = 0,FD_RET_CM = 0,APPROVED_SEC_CASH_RET_CM = 0,
APPROVED_SEC_NONCASH_RET_CM = 0,NONAPPROVED_SEC_RET_RET_CM = 0,CC_APPROVED_COMM_RET_CM = 0,OTHER_COLL_RET_CM = 0,
CASH_WNCL = 0,BG_WNCL = convert(numeric (18,3 ),0),FD_WNCL = convert(numeric (18,3 ),0),APPROVED_SEC_CASH_WNCL = 0,APPROVED_SEC_NONCASH_WNCL = convert(numeric (18,3 ),0),CC_APPROVED_COMM_WNCL = 0,
--MTF_INDICATOR = CASE WHEN EXCHANGE = 'NSE' AND SEGMENT = 'CAPITAL' THEN 'NON MTF' WHEN EXCHANGE = 'MTF' THEN 'MTF' ELSE 'NA' END ,
MTF_INDICATOR = CASE WHEN r.EXCHANGE = 'MTF' THEN 'MTF' ELSE 'NON MTF' END ,
UNCLEAR_RECEIPT= isnull(UNCLEAR_RECEIPT, 0),GOV_SEC_TBILL_REC_BY_TM = isnull(GOV_SEC_TBILL_REC_BY_TM, 0),GOV_SEC_TBILL_RET_BY_TM = isnull(GOV_SEC_TBILL_RET_BY_TM, 0),GOV_SEC_TBILL_PLACED_BY_CM = isnull(GOV_SEC_TBILL_PLACED_BY_CM,0),GOV_SEC_TBILL_RET_BY_CM = isnull(GOV_SEC_TBILL_RET_BY_CM, 0),GOV_SEC_TBILL_PLACED_BY_NCL = isnull(GOV_SEC_TBILL_PLACED_BY_NCL, 0),
BG_FUNDED_RET_WITH_CM = isnull(BG_FUNDED_RET_WITH_CM, 0),BG_NONFUNDED_RET_WITH_CM = isnull(BG_NONFUNDED_RET_WITH_CM, 0),BG_FUNDED_PLACED_WITH_NCL = isnull(BG_FUNDED_PLACED_WITH_NCL, 0),BG_NONFUNDED_PLACED_WITH_NCL = isnull(BG_NONFUNDED_PLACED_WITH_NCL, 0),SETTLEMENT_AMOUNT = isnull(SETTLEMENT_AMOUNT, 0),UNCLAIM_CL_FUNDS = isnull(UNCLAIM_CL_FUNDS, 'NA'),CASH_COLL_MTF_POSITION = ISNULL(CASH_COLL_MTF_POSITION, 0)
--EXCHANGE,SEGMENT,UPFRONT_MARGIN,PEAK_MARGIN,PARTY_CODE
FROM CLIENT_COLLATERAL_REPORTING_DETAILS_NEW R (NOLOCK)
INNER JOIN #CL_FOR_SETTLEMENT_AMOUNT C ON R.PARTY_CODE = C.PARTY_CODE AND R.EXCHANGE = C.EXCHANGE
WHERE PROCESS_DT=@RUNDATE
--AND PARTY_CODE='B420108'


--ORDER BY 1, EXCHANGE, CLEARING_PAN, TRADING_PAN, CLIENT_PAN, SEGMENT_INDICATOR

GO
