-- Object: PROCEDURE dbo.API_CLIENT_FUNDS_REPORTING_NEW
-- Server: 10.253.33.91 | DB: MSAJAG
--------------------------------------------------






--	EXEC API_CLIENT_FUNDS_REPORTING 'APR  1 2018', 'NOV 27 2018','suresh','suresh'

CREATE PROCEDURE [dbo].[API_CLIENT_FUNDS_REPORTING_NEW]
	@FR_DATE VARCHAR(11),
	@TO_DATE VARCHAR(11),
	@FR_CODE VARCHAR(10) = '0',
	@TO_CODE VARCHAR(10) = 'ZZZZZ',
	@EXCSEGMENT VARCHAR(500) = '',
	@ACCTYPE	VARCHAR(5)  = ''


AS

/*
EXEC API_CLIENT_FUNDS_REPORTING 'JAN  1 2019','JAN  7 2019','J55358','J55358'
*/

DECLARE @FILENAME   VARCHAR(50)
DECLARE @BATCHNO	INT  
DECLARE @MEMBERCODE VARCHAR(20)
DECLARE @MEMBERNAME	VARCHAR(500)

SELECT @MEMBERCODE = MEMBERCODE, @MEMBERNAME = ISNULL(LTRIM(RTRIM(COMPANY)),'') FROM OWNER (NOLOCK)
SELECT @BATCHNO = ISNULL(MAX(FLDBATCHNO),0)+1 FROM ASIANFILEBATCHNO  
WHERE FLDFILENO = 'CL'  
AND LEFT(FLDFILEDATE,11) = LEFT(GETDATE(),11)
  
IF @BATCHNO = 1  
BEGIN  
	INSERT INTO ASIANFILEBATCHNO VALUES ('CL', @BATCHNO, GETDATE(), GETDATE())  
END  
ELSE  
BEGIN  
	UPDATE ASIANFILEBATCHNO SET FLDBATCHNO = @BATCHNO WHERE FLDFILENO = 'CL' AND LEFT(FLDFILEDATE,11) = LEFT(GETDATE(),11)
END  
  
SET	@FILENAME = @MEMBERCODE + '_CL_' + REPLACE(CONVERT(VARCHAR,GETDATE(),103),'/','') + '_' + RIGHT('00'+CONVERT(VARCHAR,@BATCHNO),2) 


CREATE TABLE [DBO].[#DBNAME_LIST] (
	ACCOUNTDB VARCHAR(20)
	,EXCHANGE VARCHAR(6)
	,SEGMENT VARCHAR(10)
	,ACCOUNTSERVER VARCHAR(50)
	,SHAREDB VARCHAR(20)
	) ON [PRIMARY]

DECLARE
	@@DB1 VARCHAR(1000)
	,@@SQL VARCHAR(5000)
	,@@SEGORD1 SMALLINT
	,@@MAINREC1 AS CURSOR
	,@@ACCOUNTDB1 VARCHAR(20)
	,@@SHAREDB1 VARCHAR(20)
	,@@ACCOUNTSVR1 VARCHAR(50)
	,@@EXCHANGE1 VARCHAR(15)
	,@@SEGMENT1 VARCHAR(15)

IF @EXCSEGMENT <> ''
	SELECT @@DB1 = " INSERT INTO #DBNAME_LIST SELECT ACCOUNTDB, EXCHANGE, SEGMENT, ACCOUNTSERVER, SHAREDB FROM PRADNYA.DBO.VW_REPORTING_MULTICOMPANY (NOLOCK) WHERE EXCHANGE+'~'+SEGMENT IN ('" + REPLACE(@EXCSEGMENT, ',', ''',''') + "') ORDER BY EXCHANGE "
ELSE
	SELECT @@DB1 = " INSERT INTO #DBNAME_LIST SELECT ACCOUNTDB, EXCHANGE, SEGMENT, ACCOUNTSERVER, SHAREDB FROM PRADNYA.DBO.VW_REPORTING_MULTICOMPANY (NOLOCK) ORDER BY EXCHANGE "

EXEC (@@DB1)

CREATE TABLE #LEDGER_PL_DETAILS
(
	UCC_CODE VARCHAR(30),
	CLTCODE VARCHAR(10),
	LONG_NAME VARCHAR(150),
	CLIENT_PAN VARCHAR(50),
	VDT DATETIME,
	EDT DATETIME,
	EXCHANGE VARCHAR(10),
	SEGMENT VARCHAR(10),
	SETT_NO VARCHAR(10),
	CHQ_NO VARCHAR(30),
	VTYPE VARCHAR(30),
	NARRATION VARCHAR(500),
	VNO VARCHAR(12),
	DRAMOUNT MONEY,
	CRAMOUNT MONEY,
	RUNNING_BALANCE MONEY,
	OPBAL MONEY,
	PDT DATETIME
)

SET @@MAINREC1 = CURSOR
FOR

SELECT ACCOUNTDB
	,EXCHANGE
	,SEGMENT
	,ACCOUNTSERVER
	,SHAREDB
FROM #DBNAME_LIST

SET @@SEGORD1 = 1

OPEN @@MAINREC1

FETCH NEXT
FROM @@MAINREC1
INTO @@ACCOUNTDB1
	,@@EXCHANGE1
	,@@SEGMENT1
	,@@ACCOUNTSVR1
	,@@SHAREDB1

WHILE @@FETCH_STATUS = 0
BEGIN

	SET @@SQL = "INSERT INTO #LEDGER_PL_DETAILS EXEC " + @@ACCOUNTSVR1 + "." + @@ACCOUNTDB1 + ".DBO.CLIENT_FUNDS_REPORTING '" + @FR_DATE + "','" + @TO_DATE + "','" + @@EXCHANGE1 + "','" + @@SEGMENT1 + "','" + @FR_CODE + "','" + @TO_CODE + "'"
	PRINT @@SQL
	EXEC (@@SQL)


FETCH NEXT
	FROM @@MAINREC1
	INTO @@ACCOUNTDB1
		,@@EXCHANGE1
		,@@SEGMENT1
		,@@ACCOUNTSVR1
		,@@SHAREDB1
END

CLOSE @@MAINREC1

CREATE TABLE #LEDGER_PL_DETAILS_FINAL
(
	UCC_CODE VARCHAR(30),
	CLTCODE VARCHAR(10),
	LONG_NAME VARCHAR(150),
	CLIENT_PAN VARCHAR(30),
	VDT DATETIME,
	EDT DATETIME,
	EXCHANGE VARCHAR(10),
	SEGMENT VARCHAR(10),
	SETT_NO VARCHAR(10),
	CHQ_NO VARCHAR(30),
	VTYPE VARCHAR(30),
	NARRATION VARCHAR(500),
	VNO VARCHAR(12),
	DRAMOUNT MONEY,
	CRAMOUNT MONEY,
	RUNNING_BALANCE MONEY,
	OPBAL MONEY,
	PDT DATETIME,
	SNO INT IDENTITY(1, 1)
)

INSERT INTO #LEDGER_PL_DETAILS_FINAL
SELECT * FROM #LEDGER_PL_DETAILS WHERE CLTCODE IN (SELECT PARTY_CODE FROM IMPORT_PARTY_CODE) 
ORDER BY CLTCODE, VDT, PDT

UPDATE L SET RUNNING_BALANCE = (SELECT SUM(CRAMOUNT - DRAMOUNT) FROM #LEDGER_PL_DETAILS_FINAL L1 WHERE L.CLTCODE = L1.CLTCODE AND L1.SNO <= L.SNO) FROM #LEDGER_PL_DETAILS_FINAL L

--SELECT * FROM #LEDGER_PL_DETAILS_FINAL ORDER BY SNO
/*
DECLARE
	@MEMBER_CODE VARCHAR(200)
SELECT @MEMBER_CODE = COMPANY FROM OWNER
*/

--NEED TO APPLY THE LOGIC OF RUNNING BALANCE IN _WRAPPER PROCEDURE 
SELECT FILENAME = @FILENAME, DATA = @MEMBERNAME+','+ REPLACE(CONVERT(VARCHAR, CONVERT(DATETIME, @FR_DATE , 109), 103), '/', '') + ' to ' + REPLACE(CONVERT(VARCHAR, CONVERT(DATETIME, @TO_DATE , 109), 103), '/', '')
UNION ALL
SELECT FILENAME = @FILENAME, DATA = UCC_CODE + ',' + CLTCODE + ',' + LONG_NAME + ',' + CLIENT_PAN + ',' + REPLACE(CONVERT(VARCHAR(10), VDT, 103), '/', '-') + ',' + REPLACE(CONVERT(VARCHAR(10), EDT, 103), '/', '-') + ',' + EXCHANGE + ',' + SEGMENT + ',' + ISNULL(SETT_NO, '') + ',' + ISNULL(CHQ_NO, '') + ',' + VTYPE + ',' + NARRATION + ',' + VNO + ',' + CONVERT(VARCHAR, DRAMOUNT) + ',' + CONVERT(VARCHAR, CRAMOUNT) + ',' + CONVERT(VARCHAR, RUNNING_BALANCE) FROM #LEDGER_PL_DETAILS_FINAL

GO
