-- Object: PROCEDURE dbo.PROC_SERVICE_TAX_UPDATE_07012014
-- Server: 10.253.33.91 | DB: MSAJAG
--------------------------------------------------

  
CREATE PROC PROC_SERVICE_TAX_UPDATE_07012014  
(      
 @SETT_TYPE VARCHAR(2),       
 @SAUDA_DATE VARCHAR(11),       
 @FROMPARTY VARCHAR(10),       
 @TOPARTY VARCHAR(10)      
)       
AS   
UPDATE SETTLEMENT SET   
SERVICE_TAX = ((TRADEQTY*BROKAPPLIED)+  
       (CASE WHEN TURNOVER_AC = 1 AND TURNOVER_TAX = 1   
      THEN TURN_TAX  
             ELSE 0   
        END)+  
       (CASE WHEN SEBI_TURN_AC = 1 AND SEBI_TURN_TAX = 1   
      THEN SEBI_TAX  
             ELSE 0   
        END)+  
       (CASE WHEN BROKER_NOTE_AC = 1 AND BROKERNOTE = 1   
      THEN BROKER_CHRG  
             ELSE 0   
        END)+  
       (CASE WHEN OTHER_CHRG_AC = 1 AND C2.OTHER_CHRG = 1  
      THEN SETTLEMENT.OTHER_CHRG  
             ELSE 0   
        END)+  
       (CASE WHEN STT_TAX_AC = 1 AND C2.INSURANCE_CHRG = 1  
      THEN SETTLEMENT.OTHER_CHRG  
             ELSE 0   
        END)) * G.SERVICE_TAX/100,  
NSERTAX    = ((TRADEQTY*NBROKAPP)+  
       (CASE WHEN TURNOVER_AC = 1 AND TURNOVER_TAX = 1   
      THEN TURN_TAX  
             ELSE 0   
        END)+  
       (CASE WHEN SEBI_TURN_AC = 1 AND SEBI_TURN_TAX = 1   
      THEN SEBI_TAX  
             ELSE 0   
        END)+  
       (CASE WHEN BROKER_NOTE_AC = 1 AND BROKERNOTE = 1   
      THEN BROKER_CHRG  
             ELSE 0   
        END)+  
       (CASE WHEN OTHER_CHRG_AC = 1 AND C2.OTHER_CHRG = 1  
      THEN SETTLEMENT.OTHER_CHRG  
             ELSE 0   
        END)+  
       (CASE WHEN STT_TAX_AC = 1 AND C2.INSURANCE_CHRG = 1  
      THEN SETTLEMENT.OTHER_CHRG  
             ELSE 0   
        END)) * G.SERVICE_TAX/100  
FROM GLOBALS G, CLIENT2 C2  
WHERE SETT_TYPE = @SETT_TYPE  
AND SAUDA_DATE LIKE @SAUDA_DATE + '%'  
AND SETTLEMENT.PARTY_CODE = C2.PARTY_CODE  
AND C2.PARTY_CODE BETWEEN @FROMPARTY AND @TOPARTY  
AND AUCTIONPART NOT LIKE 'A%'   
AND 1 <> (CASE WHEN SERVICE_CHRG = 1 AND SERTAXMETHOD = 1   
        THEN 1 ELSE 0 END)  
AND SAUDA_DATE BETWEEN YEAR_START_DT AND YEAR_END_DT  
  
UPDATE ISETTLEMENT SET   
SERVICE_TAX = ((TRADEQTY*BROKAPPLIED)+  
       (CASE WHEN TURNOVER_AC = 1 AND TURNOVER_TAX = 1   
      THEN TURN_TAX  
             ELSE 0   
        END)+  
       (CASE WHEN SEBI_TURN_AC = 1 AND SEBI_TURN_TAX = 1   
      THEN SEBI_TAX  
             ELSE 0   
        END)+  
       (CASE WHEN BROKER_NOTE_AC = 1 AND BROKERNOTE = 1   
      THEN BROKER_CHRG  
             ELSE 0   
        END)+  
       (CASE WHEN OTHER_CHRG_AC = 1 AND C2.OTHER_CHRG = 1  
      THEN ISETTLEMENT.OTHER_CHRG  
             ELSE 0   
        END)+  
       (CASE WHEN STT_TAX_AC = 1 AND C2.INSURANCE_CHRG = 1  
      THEN ISETTLEMENT.OTHER_CHRG  
             ELSE 0   
        END)) * G.SERVICE_TAX/100,  
NSERTAX    = ((TRADEQTY*NBROKAPP)+  
       (CASE WHEN TURNOVER_AC = 1 AND TURNOVER_TAX = 1   
      THEN TURN_TAX  
             ELSE 0   
        END)+  
       (CASE WHEN SEBI_TURN_AC = 1 AND SEBI_TURN_TAX = 1   
      THEN SEBI_TAX  
             ELSE 0   
        END)+  
       (CASE WHEN BROKER_NOTE_AC = 1 AND BROKERNOTE = 1   
      THEN BROKER_CHRG  
             ELSE 0   
        END)+  
       (CASE WHEN OTHER_CHRG_AC = 1 AND C2.OTHER_CHRG = 1  
      THEN ISETTLEMENT.OTHER_CHRG  
             ELSE 0   
        END)+  
       (CASE WHEN STT_TAX_AC = 1 AND C2.INSURANCE_CHRG = 1  
      THEN ISETTLEMENT.OTHER_CHRG  
             ELSE 0   
        END)) * G.SERVICE_TAX/100  
FROM GLOBALS G, CLIENT2 C2  
WHERE SETT_TYPE = @SETT_TYPE  
AND SAUDA_DATE LIKE @SAUDA_DATE + '%'  
AND ISETTLEMENT.PARTY_CODE = C2.PARTY_CODE  
AND C2.PARTY_CODE BETWEEN @FROMPARTY AND @TOPARTY  
AND AUCTIONPART NOT LIKE 'A%'   
AND 1 <> (CASE WHEN SERVICE_CHRG = 1 AND SERTAXMETHOD = 1   
        THEN 1 ELSE 0 END)  
AND SAUDA_DATE BETWEEN YEAR_START_DT AND YEAR_END_DT

GO
