-- Object: PROCEDURE dbo.PENDING_ISIN
-- Server: 10.253.33.91 | DB: MSAJAG
--------------------------------------------------


CREATE PROC [dbo].[PENDING_ISIN]
AS
 

INSERT INTO MULTIISIN
SELECT * FROM  ANGELDEMAT.MSAJAG.DBO.MULTIISIN A
WHERE  NOT EXISTS  (SELECT ISIN FROM MULTIISIN M WHERE M.Scrip_cd =A.Scrip_cd  AND M.Series =A.Series AND M.Valid = A.Valid  )


UPDATE M SET ISIN =A.ISIN FROM MULTIISIN M,ANGELDEMAT.MSAJAG.DBO.MULTIISIN A
WHERE M.Scrip_cd =A.Scrip_cd  AND M.Series =A.Series 
AND M.Isin <> A.ISIN  AND M.Valid =A.Valid

 
 
----DECLARE @SDATE DATETIME

----SET @SDATE = (
----SELECT TOP 1 *    FROM (
----SELECT DISTINCT  Sec_Payin ,ROW_NUMBER() OVER (ORDER BY Sec_Payin)  AS SNO  FROM SETT_MST 
----WHERE Sec_Payin <   CONVERT(VARCHAR(11),GETDATE()-1,120) AND SETT_TYPE ='N' 
---- ) A ORDER BY Sec_Payin DESC)

 
------BEGIN TRAN 
------UPDATE C SET ISIN =M.ISIN  FROM CMBILLVALAN C WITH(NOLOCK),MULTIISIN M WHERE SAUDA_DATE >=@SDATE
------AND C.ISIN <>M.Isin 
------AND C.SCRIP_CD <>'BROKERAGE' AND M.Scrip_cd =C.SCRIP_CD AND M.Series =C.SERIES  AND VALID =1 AND SETT_TYPE IN ('N','W')
------COMMIT

GO
