-- Object: PROCEDURE dbo.BAK_PROC_CLIENT_COLLATREAL_ALLOC_MODANGEL
-- Server: 10.253.33.91 | DB: MSAJAG
--------------------------------------------------


CREATE PROC	[dbo].[BAK_PROC_CLIENT_COLLATREAL_ALLOC_MODANGEL]
(
	@RUNDATE VARCHAR(11)
)	
AS
DECLARE
		@PARTY_CODE	VARCHAR(10),
		@EXCHANGE	VARCHAR(3),
		@SEGMENT	VARCHAR(7),
		@NEWEXCHANGE	VARCHAR(3),
		@NEWSEGMENT	VARCHAR(7),
		@LEDBAL		NUMERIC(18,3),
		@NEWLEDBAL		NUMERIC(18,3),
		@DIFFLEDBAL		NUMERIC(18,3),
		@SNO	INT,
		@NEWSNO	INT,
		@ADJCUR		CURSOR,
		@ALLOCCURSOR	CURSOR
		 
SELECT DISTINCT PARTY_CODE INTO #PARTYUPSTK_C
FROM CLIENT_COLLATERAL_REPORTING_DETAILS_TODAY
WHERE PROCESS_DT = @RUNDATE 
AND EDT_LEDGER+POOL_ACCOUNT_CLTM+LIEU_EPI_LEDGER_CLTM+
APPROVED_SEC_CASH_REC_TM+APPROVED_SEC_NONCASH_REC_TM+NONAPPROVED_SEC_REC_TM-UPFRONT_MARGIN < 0 
AND UPFRONT_MARGIN > 0 
AND EXCHANGE <> 'MTF'
AND PARTY_CODE IN ( SELECT PARTY_CODE
FROM CLIENT_COLLATERAL_REPORTING_DETAILS_TODAY
WHERE PROCESS_DT = @RUNDATE  
AND EDT_LEDGER+POOL_ACCOUNT_CLTM+LIEU_EPI_LEDGER_CLTM+
APPROVED_SEC_CASH_REC_TM+APPROVED_SEC_NONCASH_REC_TM+NONAPPROVED_SEC_REC_TM-UPFRONT_MARGIN >0 
AND APPROVED_SEC_CASH_RET_TM > 0 AND EXCHANGE <> 'MTF') 

SELECT PARTY_CODE, EXCHANGE, SEGMENT, SHORT=EDT_LEDGER+POOL_ACCOUNT_CLTM+LIEU_EPI_LEDGER_CLTM+
APPROVED_SEC_CASH_REC_TM+APPROVED_SEC_NONCASH_REC_TM+NONAPPROVED_SEC_REC_TM-UPFRONT_MARGIN,APPROVED_SEC_CASH_REC_TM,
APPROVED_SEC_CASH_RET_TM,NONAPPROVED_SEC_REC_TM,NONAPPROVED_SEC_RET_TM
INTO #ADJDATASTK_C FROM CLIENT_COLLATERAL_REPORTING_DETAILS_TODAY
WHERE PROCESS_DT = @RUNDATE AND EXCHANGE <> 'MTF'
AND PARTY_CODE IN (SELECT PARTY_CODE FROM #PARTYUPSTK_C)

ALTER TABLE #ADJDATASTK_C
ADD [SNO]			INT IDENTITY(1,1),
	[IsProcessed]	BIT ,
	[PartyCount]	INT,
	[Balance]		NUMERIC(19,6),
	[DIFFLEDBAL]	NUMERIC(19,6)

CREATE CLUSTERED INDEX IDXDT ON #ADJDATASTK_C
(
	[SNO]
)

 UPDATE OBJ
	SET [PartyCount] = T.[Count]
 FROM #ADJDATASTK_C OBJ
 INNER JOIN 
 (
	SELECT 
		[PARTY_CODE] ,
		[Count] = COUNT(*)
	FROM #ADJDATASTK_C 
	WHERE [SHORT] > 0 AND [APPROVED_SEC_CASH_RET_TM] > 0 
	GROUP BY [PARTY_CODE]
 ) T ON OBJ.[PARTY_CODE] = T.[PARTY_CODE]

UPDATE T 
	SET [Balance] =  CASE WHEN T.[SHORT] > T.[APPROVED_SEC_CASH_RET_TM] THEN T.[APPROVED_SEC_CASH_RET_TM] ELSE T.[SHORT] END
FROM #ADJDATASTK_C T 
WHERE ISNULL(T.[PartyCount],0) = 1

UPDATE OBJ 
	SET OBJ.[APPROVED_SEC_CASH_RET_TM] = OBJ.[APPROVED_SEC_CASH_RET_TM] + (CASE WHEN ABS(OBJ.[SHORT]) > ABS(T.[Balance]) THEN ABS(T.[Balance]) ELSE ABS(OBJ.[SHORT]) END),
		OBJ.[APPROVED_SEC_CASH_REC_TM] = OBJ.[APPROVED_SEC_CASH_REC_TM] + (CASE WHEN ABS(OBJ.[SHORT]) > ABS(T.[Balance]) THEN ABS(T.[Balance]) ELSE ABS(OBJ.[SHORT]) END),
		OBJ.[DIFFLEDBAL] = (CASE WHEN ABS(OBJ.[SHORT]) > ABS(T.[Balance]) THEN ABS(T.[Balance]) ELSE ABS(OBJ.[SHORT]) END),
		OBJ.[IsProcessed] = 1
FROM #ADJDATASTK_C OBJ
INNER JOIN #ADJDATASTK_C T ON OBJ.[PARTY_CODE] = T.[PARTY_CODE] AND ISNULL(T.[PartyCount],0) = 1
AND OBJ.[SHORT] < 0

UPDATE OBJ 
	SET OBJ.[APPROVED_SEC_CASH_RET_TM] = OBJ.[APPROVED_SEC_CASH_RET_TM] - T.[DIFFLEDBAL],
		OBJ.[APPROVED_SEC_CASH_REC_TM] = OBJ.[APPROVED_SEC_CASH_REC_TM] - T.[DIFFLEDBAL]
FROM #ADJDATASTK_C OBJ
INNER JOIN #ADJDATASTK_C T ON OBJ.[PARTY_CODE] = T.[PARTY_CODE] AND ISNULL(OBJ.[PartyCount],0) = 1
AND T.[SHORT] < 0 AND T.[IsProcessed] = 1

SET @ADJCUR = CURSOR FAST_FORWARD FOR 
SELECT SNO, PARTY_CODE, EXCHANGE, SEGMENT, SHORT
FROM #ADJDATASTK_C
WHERE SHORT < 0  and ISNULL([IsProcessed],0) <> 1
AND PARTY_CODE IN ( SELECT PARTY_CODE
FROM #ADJDATASTK_C
WHERE SHORT > 0 AND ISNULL([PartyCount],0) <> 1)
--AND PARTY_CODE = '10114978'
ORDER BY PARTY_CODE, EXCHANGE, SEGMENT
OPEN @ADJCUR
FETCH NEXT FROM @ADJCUR INTO @SNO, @PARTY_CODE, @EXCHANGE, @SEGMENT, @LEDBAL
WHILE @@FETCH_STATUS = 0 
BEGIN
	SET @ALLOCCURSOR = CURSOR FAST_FORWARD FOR 
	SELECT SNO, EXCHANGE, SEGMENT, BALANCE = (CASE WHEN SHORT > APPROVED_SEC_CASH_RET_TM THEN APPROVED_SEC_CASH_RET_TM ELSE SHORT END) 
	FROM #ADJDATASTK_C
	WHERE PARTY_CODE = @PARTY_CODE AND SHORT > 0 AND APPROVED_SEC_CASH_RET_TM > 0 AND ISNULL([PartyCount],0) <> 1
	ORDER BY EXCHANGE, SEGMENT
	OPEN @ALLOCCURSOR
	FETCH NEXT FROM @ALLOCCURSOR INTO @NEWSNO, @NEWEXCHANGE, @NEWSEGMENT, @NEWLEDBAL
	WHILE @@FETCH_STATUS = 0 
	BEGIN
		IF @LEDBAL < 0 AND @NEWLEDBAL > 0 
		BEGIN
			SELECT @DIFFLEDBAL = (CASE WHEN ABS(@LEDBAL) > ABS(@NEWLEDBAL) THEN ABS(@NEWLEDBAL) ELSE ABS(@LEDBAL) END)

			UPDATE #ADJDATASTK_C SET APPROVED_SEC_CASH_RET_TM = APPROVED_SEC_CASH_RET_TM - @DIFFLEDBAL,
			APPROVED_SEC_CASH_REC_TM = APPROVED_SEC_CASH_REC_TM - @DIFFLEDBAL
			WHERE SNO = @NEWSNO

			UPDATE #ADJDATASTK_C SET APPROVED_SEC_CASH_RET_TM = APPROVED_SEC_CASH_RET_TM + @DIFFLEDBAL,
			APPROVED_SEC_CASH_REC_TM = APPROVED_SEC_CASH_REC_TM + @DIFFLEDBAL
			WHERE SNO = @SNO

			SET @LEDBAL = @LEDBAL + @DIFFLEDBAL
		END
		FETCH NEXT FROM @ALLOCCURSOR INTO @NEWSNO, @NEWEXCHANGE, @NEWSEGMENT, @NEWLEDBAL
	END
	CLOSE @ALLOCCURSOR
	DEALLOCATE @ALLOCCURSOR
	FETCH NEXT FROM @ADJCUR INTO @SNO, @PARTY_CODE, @EXCHANGE, @SEGMENT, @LEDBAL
END
CLOSE @ADJCUR
DEALLOCATE @ADJCUR

UPDATE CLIENT_COLLATERAL_REPORTING_DETAILS_TODAY SET APPROVED_SEC_CASH_RET_TM = C.APPROVED_SEC_CASH_RET_TM,
APPROVED_SEC_CASH_REC_TM = C.APPROVED_SEC_CASH_REC_TM
FROM #ADJDATASTK_C C
WHERE PROCESS_DT = @RUNDATE
AND C.PARTY_CODE = CLIENT_COLLATERAL_REPORTING_DETAILS_TODAY.PARTY_CODE
AND C.EXCHANGE = CLIENT_COLLATERAL_REPORTING_DETAILS_TODAY.EXCHANGE
AND C.SEGMENT = CLIENT_COLLATERAL_REPORTING_DETAILS_TODAY.SEGMENT

SELECT DISTINCT PARTY_CODE INTO #PARTYUPSTK
FROM CLIENT_COLLATERAL_REPORTING_DETAILS_TODAY
WHERE PROCESS_DT = @RUNDATE 
AND EDT_LEDGER+POOL_ACCOUNT_CLTM+LIEU_EPI_LEDGER_CLTM+
APPROVED_SEC_CASH_REC_TM+APPROVED_SEC_NONCASH_REC_TM+NONAPPROVED_SEC_REC_TM-UPFRONT_MARGIN < 0 
AND UPFRONT_MARGIN > 0 
AND EXCHANGE <> 'MTF'
AND PARTY_CODE IN ( SELECT PARTY_CODE
FROM CLIENT_COLLATERAL_REPORTING_DETAILS_TODAY
WHERE PROCESS_DT = @RUNDATE  
AND EDT_LEDGER+POOL_ACCOUNT_CLTM+LIEU_EPI_LEDGER_CLTM+
APPROVED_SEC_CASH_REC_TM+APPROVED_SEC_NONCASH_REC_TM+NONAPPROVED_SEC_REC_TM-UPFRONT_MARGIN >0 
AND APPROVED_SEC_NONCASH_RET_TM > 0 AND EXCHANGE <> 'MTF') 

SELECT PARTY_CODE, EXCHANGE, SEGMENT, SHORT=EDT_LEDGER+POOL_ACCOUNT_CLTM+LIEU_EPI_LEDGER_CLTM+
APPROVED_SEC_CASH_REC_TM+APPROVED_SEC_NONCASH_REC_TM+NONAPPROVED_SEC_REC_TM-UPFRONT_MARGIN,APPROVED_SEC_NONCASH_REC_TM,
APPROVED_SEC_NONCASH_RET_TM,NONAPPROVED_SEC_REC_TM,NONAPPROVED_SEC_RET_TM
INTO #ADJDATASTK FROM CLIENT_COLLATERAL_REPORTING_DETAILS_TODAY
WHERE PROCESS_DT = @RUNDATE AND EXCHANGE <> 'MTF'
AND PARTY_CODE IN (SELECT PARTY_CODE FROM #PARTYUPSTK)

ALTER TABLE #ADJDATASTK
ADD [SNO]			INT IDENTITY(1,1),
	[IsProcessed]	BIT ,
	[PartyCount]	INT,
	[Balance]		NUMERIC(19,6),
	[DIFFLEDBAL]	NUMERIC(19,6)

CREATE CLUSTERED INDEX IDXDT ON #ADJDATASTK
(
	SNO
)

UPDATE OBJ
	SET [PartyCount] = T.[Count]
 FROM #ADJDATASTK OBJ
 INNER JOIN 
 (
	SELECT 
		[PARTY_CODE] ,
		[Count] = COUNT(*)
	FROM #ADJDATASTK 
	WHERE [SHORT] > 0 AND [APPROVED_SEC_NONCASH_RET_TM] > 0 
	GROUP BY [PARTY_CODE]
 ) T ON OBJ.[PARTY_CODE] = T.[PARTY_CODE]

UPDATE T 
	SET [Balance] =  CASE WHEN T.[SHORT] > T.[APPROVED_SEC_NONCASH_RET_TM] THEN T.[APPROVED_SEC_NONCASH_RET_TM] ELSE T.[SHORT] END
FROM #ADJDATASTK T 
WHERE ISNULL(T.[PartyCount],0) = 1

UPDATE OBJ 
	SET OBJ.[APPROVED_SEC_NONCASH_RET_TM] = OBJ.[APPROVED_SEC_NONCASH_RET_TM] + (CASE WHEN ABS(OBJ.[SHORT]) > ABS(T.[Balance]) THEN ABS(T.[Balance]) ELSE ABS(OBJ.[SHORT]) END),
		OBJ.[APPROVED_SEC_NONCASH_REC_TM] = OBJ.[APPROVED_SEC_NONCASH_REC_TM] + (CASE WHEN ABS(OBJ.[SHORT]) > ABS(T.[Balance]) THEN ABS(T.[Balance]) ELSE ABS(OBJ.[SHORT]) END),
		OBJ.[DIFFLEDBAL] = (CASE WHEN ABS(OBJ.[SHORT]) > ABS(T.[Balance]) THEN ABS(T.[Balance]) ELSE ABS(OBJ.[SHORT]) END),
		OBJ.[IsProcessed] = 1
FROM #ADJDATASTK OBJ
INNER JOIN #ADJDATASTK T ON OBJ.[PARTY_CODE] = T.[PARTY_CODE] AND ISNULL(T.[PartyCount],0) = 1
AND OBJ.[SHORT] < 0

UPDATE OBJ 
	SET OBJ.[APPROVED_SEC_NONCASH_RET_TM] = OBJ.[APPROVED_SEC_NONCASH_RET_TM] - T.[DIFFLEDBAL],
		OBJ.[APPROVED_SEC_NONCASH_REC_TM] = OBJ.[APPROVED_SEC_NONCASH_REC_TM] - T.[DIFFLEDBAL]
FROM #ADJDATASTK OBJ
INNER JOIN #ADJDATASTK T ON OBJ.[PARTY_CODE] = T.[PARTY_CODE] AND ISNULL(OBJ.[PartyCount],0) = 1
AND T.[SHORT] < 0 AND T.[IsProcessed] = 1

SET @ADJCUR = CURSOR FAST_FORWARD FOR 
SELECT SNO, PARTY_CODE, EXCHANGE, SEGMENT, SHORT
FROM #ADJDATASTK
WHERE SHORT < 0  AND  ISNULL([IsProcessed],0) <> 1
AND PARTY_CODE IN ( SELECT PARTY_CODE
FROM #ADJDATASTK
WHERE SHORT > 0 AND ISNULL([PartyCount],0) <> 1 )
--AND PARTY_CODE = '10114978'
ORDER BY PARTY_CODE, EXCHANGE, SEGMENT
OPEN @ADJCUR
FETCH NEXT FROM @ADJCUR INTO @SNO, @PARTY_CODE, @EXCHANGE, @SEGMENT, @LEDBAL
WHILE @@FETCH_STATUS = 0 
BEGIN
	SET @ALLOCCURSOR = CURSOR FAST_FORWARD FOR 
	SELECT SNO, EXCHANGE, SEGMENT, BALANCE = (CASE WHEN SHORT > APPROVED_SEC_NONCASH_RET_TM THEN APPROVED_SEC_NONCASH_RET_TM ELSE SHORT END) 
	FROM #ADJDATASTK
	WHERE PARTY_CODE = @PARTY_CODE AND SHORT > 0 AND APPROVED_SEC_NONCASH_RET_TM > 0 AND ISNULL([PartyCount],0) <> 1
	ORDER BY EXCHANGE, SEGMENT
	OPEN @ALLOCCURSOR
	FETCH NEXT FROM @ALLOCCURSOR INTO @NEWSNO, @NEWEXCHANGE, @NEWSEGMENT, @NEWLEDBAL
	WHILE @@FETCH_STATUS = 0 
	BEGIN
		IF @LEDBAL < 0 AND @NEWLEDBAL > 0 
		BEGIN
			SELECT @DIFFLEDBAL = (CASE WHEN ABS(@LEDBAL) > ABS(@NEWLEDBAL) THEN ABS(@NEWLEDBAL) ELSE ABS(@LEDBAL) END)
			UPDATE #ADJDATASTK SET APPROVED_SEC_NONCASH_RET_TM = APPROVED_SEC_NONCASH_RET_TM - @DIFFLEDBAL,
			APPROVED_SEC_NONCASH_REC_TM = APPROVED_SEC_NONCASH_REC_TM - @DIFFLEDBAL
			WHERE [SNO] = @NEWSNO

			UPDATE #ADJDATASTK SET APPROVED_SEC_NONCASH_RET_TM = APPROVED_SEC_NONCASH_RET_TM + @DIFFLEDBAL,
			APPROVED_SEC_NONCASH_REC_TM = APPROVED_SEC_NONCASH_REC_TM + @DIFFLEDBAL
			WHERE [SNO] = @SNO

			SET @LEDBAL = @LEDBAL + @DIFFLEDBAL
		END
		FETCH NEXT FROM @ALLOCCURSOR INTO @NEWSNO, @NEWEXCHANGE, @NEWSEGMENT, @NEWLEDBAL
	END
	CLOSE @ALLOCCURSOR
	DEALLOCATE @ALLOCCURSOR
	FETCH NEXT FROM @ADJCUR INTO @SNO, @PARTY_CODE, @EXCHANGE, @SEGMENT, @LEDBAL
END
CLOSE @ADJCUR
DEALLOCATE @ADJCUR

UPDATE CLIENT_COLLATERAL_REPORTING_DETAILS_TODAY 
SET APPROVED_SEC_NONCASH_RET_TM = C.APPROVED_SEC_NONCASH_RET_TM,
APPROVED_SEC_NONCASH_REC_TM = C.APPROVED_SEC_NONCASH_REC_TM
FROM #ADJDATASTK C
WHERE PROCESS_DT = @RUNDATE
AND C.PARTY_CODE = CLIENT_COLLATERAL_REPORTING_DETAILS_TODAY.PARTY_CODE
AND C.EXCHANGE = CLIENT_COLLATERAL_REPORTING_DETAILS_TODAY.EXCHANGE
AND C.SEGMENT = CLIENT_COLLATERAL_REPORTING_DETAILS_TODAY.SEGMENT

SELECT DISTINCT PARTY_CODE INTO #PARTYUPSTK_NON
FROM CLIENT_COLLATERAL_REPORTING_DETAILS_TODAY
WHERE PROCESS_DT = @RUNDATE 
AND EDT_LEDGER+POOL_ACCOUNT_CLTM+LIEU_EPI_LEDGER_CLTM+
APPROVED_SEC_CASH_REC_TM+APPROVED_SEC_NONCASH_REC_TM+NONAPPROVED_SEC_REC_TM-UPFRONT_MARGIN < 0 
AND UPFRONT_MARGIN > 0 
AND EXCHANGE <> 'MTF'
AND PARTY_CODE IN ( SELECT PARTY_CODE
FROM CLIENT_COLLATERAL_REPORTING_DETAILS_TODAY
WHERE PROCESS_DT = @RUNDATE  
AND EDT_LEDGER+POOL_ACCOUNT_CLTM+LIEU_EPI_LEDGER_CLTM+
APPROVED_SEC_CASH_REC_TM+APPROVED_SEC_NONCASH_REC_TM+NONAPPROVED_SEC_REC_TM-UPFRONT_MARGIN >0 
AND NONAPPROVED_SEC_RET_TM > 0 AND EXCHANGE <> 'MTF') 

SELECT PARTY_CODE, EXCHANGE, SEGMENT, SHORT=EDT_LEDGER+POOL_ACCOUNT_CLTM+LIEU_EPI_LEDGER_CLTM+
APPROVED_SEC_CASH_REC_TM+APPROVED_SEC_NONCASH_REC_TM+NONAPPROVED_SEC_REC_TM-UPFRONT_MARGIN,APPROVED_SEC_NONCASH_REC_TM,
APPROVED_SEC_NONCASH_RET_TM,NONAPPROVED_SEC_REC_TM,NONAPPROVED_SEC_RET_TM
INTO #ADJDATASTK_NON FROM CLIENT_COLLATERAL_REPORTING_DETAILS_TODAY
WHERE PROCESS_DT = @RUNDATE AND EXCHANGE <> 'MTF'
AND PARTY_CODE IN (SELECT PARTY_CODE FROM #PARTYUPSTK_NON)

--Main Optimization start from here 
--Added Few Coulumn required for processing
ALTER TABLE #ADJDATASTK_NON
ADD SNO INT IDENTITY(1,1),
[IsProcessed]  BIT ,
 [PartyCount] INT,
 [Balance]  NUMERIC(19,6),
 [DIFFLEDBAL]  NUMERIC(19,6)
 SELECT COUNT(*) FROM #ADJDATASTK_NON

CREATE CLUSTERED INDEX IDXDT ON #ADJDATASTK_NON
(
	SNO
)

--Find out the records for which we have only 1 PARTY_CODE exist so that we can avoid cursor for that and use update statement directly
 UPDATE OBJ
	SET [PartyCount] = T.[Count]
 FROM #ADJDATASTK_NON OBJ
 INNER JOIN 
 (
 SELECT 
		[PARTY_CODE] ,
		[Count] = COUNT(*)
	FROM #ADJDATASTK_NON 
	WHERE [SHORT] > 0 AND [NONAPPROVED_SEC_RET_TM] > 0 
	GROUP BY [PARTY_CODE]
 ) T ON OBJ.PARTY_CODE = T.PARTY_CODE

 UPDATE T 
	SET [Balance] =  CASE WHEN T.[SHORT] > T.[NONAPPROVED_SEC_RET_TM] THEN T.[NONAPPROVED_SEC_RET_TM] ELSE T.[SHORT] END
 FROM #ADJDATASTK_NON T 
 WHERE ISNULL(T.[PartyCount],0) = 1

 UPDATE OBJ 
	SET OBJ.NONAPPROVED_SEC_RET_TM = OBJ.NONAPPROVED_SEC_RET_TM + (CASE WHEN ABS(OBJ.[SHORT]) > ABS(T.[Balance]) THEN ABS(T.[Balance]) ELSE ABS(OBJ.[SHORT]) END),
		OBJ.NONAPPROVED_SEC_REC_TM = OBJ.NONAPPROVED_SEC_REC_TM + (CASE WHEN ABS(OBJ.[SHORT]) > ABS(T.[Balance]) THEN ABS(T.[Balance]) ELSE ABS(OBJ.[SHORT]) END),
		OBJ.[DIFFLEDBAL] = (CASE WHEN ABS(OBJ.[SHORT]) > ABS(T.[Balance]) THEN ABS(T.[Balance]) ELSE ABS(OBJ.[SHORT]) END),
		OBJ.[IsProcessed] = 1
FROM #ADJDATASTK_NON OBJ
INNER JOIN #ADJDATASTK_NON T ON OBJ.PARTY_CODE = T.PARTY_CODE AND ISNULL(T.[PartyCount],0) = 1
AND OBJ.[SHORT] < 0

UPDATE OBJ 
	SET OBJ.NONAPPROVED_SEC_RET_TM = OBJ.NONAPPROVED_SEC_RET_TM - T.[DIFFLEDBAL],
		OBJ.NONAPPROVED_SEC_REC_TM = OBJ.NONAPPROVED_SEC_REC_TM - T.[DIFFLEDBAL]
FROM #ADJDATASTK_NON OBJ
INNER JOIN #ADJDATASTK_NON T ON OBJ.PARTY_CODE = T.PARTY_CODE AND ISNULL(OBJ.[PartyCount],0) = 1
AND T.[SHORT] < 0 AND T.[IsProcessed] = 1

-- now  only using cursor for records for which we have more then 1 PARTY_CODE exists
SET @ADJCUR = CURSOR FAST_FORWARD FOR
SELECT   SNO, PARTY_CODE, EXCHANGE, SEGMENT, SHORT
FROM #ADJDATASTK_NON
WHERE SHORT < 0  and ISNULL([IsProcessed],0) <> 1
AND PARTY_CODE IN ( 
SELECT PARTY_CODE
FROM #ADJDATASTK_NON
WHERE SHORT > 0 AND NONAPPROVED_SEC_RET_TM > 0  AND ISNULL([PartyCount],0) <> 1
 )
--AND PARTY_CODE = '10114978'
ORDER BY PARTY_CODE, EXCHANGE, SEGMENT
OPEN @ADJCUR
FETCH NEXT FROM @ADJCUR INTO @SNO, @PARTY_CODE, @EXCHANGE, @SEGMENT, @LEDBAL
WHILE @@FETCH_STATUS = 0 --18000
BEGIN
	SET @ALLOCCURSOR = CURSOR FAST_FORWARD FOR 
	SELECT SNO, EXCHANGE, SEGMENT, BALANCE = (CASE WHEN SHORT > NONAPPROVED_SEC_RET_TM THEN NONAPPROVED_SEC_RET_TM ELSE SHORT END) 
	FROM #ADJDATASTK_NON
	WHERE PARTY_CODE = @PARTY_CODE AND SHORT > 0 AND NONAPPROVED_SEC_RET_TM > 0  AND ISNULL([PartyCount],0) <> 1
	ORDER BY EXCHANGE, SEGMENT
	OPEN @ALLOCCURSOR
	FETCH NEXT FROM @ALLOCCURSOR INTO @NEWSNO, @NEWEXCHANGE, @NEWSEGMENT, @NEWLEDBAL
	WHILE @@FETCH_STATUS = 0 
	BEGIN
		IF @LEDBAL < 0 AND @NEWLEDBAL > 0 
		BEGIN
			SELECT @DIFFLEDBAL = (CASE WHEN ABS(@LEDBAL) > ABS(@NEWLEDBAL) THEN ABS(@NEWLEDBAL) ELSE ABS(@LEDBAL) END)
			UPDATE #ADJDATASTK_NON SET NONAPPROVED_SEC_RET_TM = NONAPPROVED_SEC_RET_TM - @DIFFLEDBAL,
			NONAPPROVED_SEC_REC_TM = NONAPPROVED_SEC_REC_TM - @DIFFLEDBAL
			WHERE SNO = @NEWSNO

			UPDATE #ADJDATASTK_NON SET NONAPPROVED_SEC_RET_TM = NONAPPROVED_SEC_RET_TM + @DIFFLEDBAL,
			NONAPPROVED_SEC_REC_TM = NONAPPROVED_SEC_REC_TM + @DIFFLEDBAL
			WHERE SNO = @SNO

			SET @LEDBAL = @LEDBAL + @DIFFLEDBAL
		END
		FETCH NEXT FROM @ALLOCCURSOR INTO @NEWSNO, @NEWEXCHANGE, @NEWSEGMENT, @NEWLEDBAL
	END
	CLOSE @ALLOCCURSOR
	DEALLOCATE @ALLOCCURSOR
	FETCH NEXT FROM @ADJCUR INTO @SNO, @PARTY_CODE, @EXCHANGE, @SEGMENT, @LEDBAL
END
CLOSE @ADJCUR
DEALLOCATE @ADJCUR
 --Main Optimization end here 

UPDATE CLIENT_COLLATERAL_REPORTING_DETAILS_TODAY SET NONAPPROVED_SEC_RET_TM = C.NONAPPROVED_SEC_RET_TM,
NONAPPROVED_SEC_REC_TM = C.NONAPPROVED_SEC_REC_TM
FROM #ADJDATASTK_NON C
WHERE PROCESS_DT = @RUNDATE
AND C.PARTY_CODE = CLIENT_COLLATERAL_REPORTING_DETAILS_TODAY.PARTY_CODE
AND C.EXCHANGE = CLIENT_COLLATERAL_REPORTING_DETAILS_TODAY.EXCHANGE
AND C.SEGMENT = CLIENT_COLLATERAL_REPORTING_DETAILS_TODAY.SEGMENT

SELECT DISTINCT PARTY_CODE INTO #PARTYUPLED
FROM CLIENT_COLLATERAL_REPORTING_DETAILS_TODAY
WHERE PROCESS_DT = @RUNDATE 
AND EDT_LEDGER+POOL_ACCOUNT_CLTM+LIEU_EPI_LEDGER_CLTM+
APPROVED_SEC_CASH_REC_TM+APPROVED_SEC_NONCASH_REC_TM+NONAPPROVED_SEC_REC_TM-UPFRONT_MARGIN < 0 
AND UPFRONT_MARGIN > 0 
AND EXCHANGE <> 'MTF'
AND PARTY_CODE IN ( SELECT PARTY_CODE
FROM CLIENT_COLLATERAL_REPORTING_DETAILS_TODAY
WHERE PROCESS_DT = @RUNDATE  
AND EDT_LEDGER+POOL_ACCOUNT_CLTM+LIEU_EPI_LEDGER_CLTM+
APPROVED_SEC_CASH_REC_TM+APPROVED_SEC_NONCASH_REC_TM-UPFRONT_MARGIN >0 
AND EDT_LEDGER > 0 AND EXCHANGE <> 'MTF') 

SELECT PARTY_CODE, EXCHANGE, SEGMENT, SHORT=EDT_LEDGER+POOL_ACCOUNT_CLTM+LIEU_EPI_LEDGER_CLTM+
APPROVED_SEC_CASH_REC_TM+APPROVED_SEC_NONCASH_REC_TM+NONAPPROVED_SEC_REC_TM-UPFRONT_MARGIN,EDT_LEDGER
INTO #ADJDATALED FROM CLIENT_COLLATERAL_REPORTING_DETAILS_TODAY
WHERE PROCESS_DT = @RUNDATE AND EXCHANGE <> 'MTF'
AND PARTY_CODE IN (SELECT PARTY_CODE FROM #PARTYUPLED)

ALTER TABLE #ADJDATALED
ADD	[SNO]			INT IDENTITY(1,1),
	[IsProcessed]	BIT ,
	[PartyCount]	INT,
	[Balance]		NUMERIC(19,6),
	[DIFFLEDBAL]	NUMERIC(19,6)

CREATE CLUSTERED INDEX IDXDT ON #ADJDATALED
(
	[SNO]
)

UPDATE OBJ
	SET [PartyCount] = T.[Count]
 FROM #ADJDATALED OBJ
 INNER JOIN 
 (
	SELECT 
		[PARTY_CODE] ,
		[Count] = COUNT(*)
	FROM #ADJDATALED 
	WHERE SHORT > 0 AND [EDT_LEDGER] > 0 
	GROUP BY [PARTY_CODE]
 ) T ON OBJ.[PARTY_CODE] = T.[PARTY_CODE]

 UPDATE T 
	SET [Balance] =  CASE WHEN T.[SHORT] > T.[EDT_LEDGER] THEN T.[EDT_LEDGER] ELSE T.[SHORT] END
 FROM #ADJDATALED T 
 WHERE ISNULL(T.[PartyCount],0) = 1

UPDATE OBJ 
	SET OBJ.EDT_LEDGER = OBJ.[EDT_LEDGER] + (CASE WHEN ABS(OBJ.[SHORT]) > ABS(T.[Balance]) THEN ABS(T.[Balance]) ELSE ABS(OBJ.[SHORT]) END),
		OBJ.[DIFFLEDBAL] = (CASE WHEN ABS(OBJ.[SHORT]) > ABS(T.[Balance]) THEN ABS(T.[Balance]) ELSE ABS(OBJ.[SHORT]) END),
		OBJ.[IsProcessed] = 1
FROM #ADJDATALED OBJ
INNER JOIN #ADJDATALED T ON OBJ.PARTY_CODE = T.PARTY_CODE AND ISNULL(T.[PartyCount],0) = 1
AND OBJ.[SHORT] < 0

UPDATE OBJ 
	SET OBJ.EDT_LEDGER = OBJ.[EDT_LEDGER] - T.[DIFFLEDBAL]
FROM #ADJDATALED OBJ
INNER JOIN #ADJDATALED T ON OBJ.[PARTY_CODE] = T.[PARTY_CODE] AND ISNULL(OBJ.[PartyCount],0) = 1
AND T.[SHORT] < 0 AND T.[IsProcessed] = 1

SET @ADJCUR = CURSOR FAST_FORWARD FOR 
SELECT SNO, PARTY_CODE, EXCHANGE, SEGMENT, SHORT
FROM #ADJDATALED
WHERE SHORT < 0  AND [IsProcessed] <> 1
AND PARTY_CODE IN ( SELECT PARTY_CODE
FROM #ADJDATALED
WHERE SHORT > 0 AND ISNULL([PartyCount],0) <> 1)
--AND PARTY_CODE = '10114978'
ORDER BY PARTY_CODE, EXCHANGE, SEGMENT
OPEN @ADJCUR
FETCH NEXT FROM @ADJCUR INTO @SNO, @PARTY_CODE, @EXCHANGE, @SEGMENT, @LEDBAL
WHILE @@FETCH_STATUS = 0 
BEGIN
	SET @ALLOCCURSOR = CURSOR FAST_FORWARD FOR 
	SELECT SNO, EXCHANGE, SEGMENT, BALANCE = (CASE WHEN SHORT > EDT_LEDGER THEN EDT_LEDGER ELSE SHORT END) 
	FROM #ADJDATALED
	WHERE PARTY_CODE = @PARTY_CODE AND SHORT > 0 AND EDT_LEDGER > 0  AND ISNULL([PartyCount],0) <> 1
	ORDER BY EXCHANGE, SEGMENT
	OPEN @ALLOCCURSOR
	FETCH NEXT FROM @ALLOCCURSOR INTO @NEWSNO, @NEWEXCHANGE, @NEWSEGMENT, @NEWLEDBAL
	WHILE @@FETCH_STATUS = 0 
	BEGIN
		IF @LEDBAL < 0 AND @NEWLEDBAL > 0 
		BEGIN
			SELECT @DIFFLEDBAL = (CASE WHEN ABS(@LEDBAL) > ABS(@NEWLEDBAL) THEN ABS(@NEWLEDBAL) ELSE ABS(@LEDBAL) END)
			UPDATE #ADJDATALED SET EDT_LEDGER = EDT_LEDGER - @DIFFLEDBAL
			WHERE SNO = @NEWSNO

			UPDATE #ADJDATALED SET EDT_LEDGER = EDT_LEDGER + @DIFFLEDBAL
			WHERE SNO = @SNO

			SET @LEDBAL = @LEDBAL + @DIFFLEDBAL
		END
		FETCH NEXT FROM @ALLOCCURSOR INTO @NEWSNO, @NEWEXCHANGE, @NEWSEGMENT, @NEWLEDBAL
	END
	CLOSE @ALLOCCURSOR
	DEALLOCATE @ALLOCCURSOR
	FETCH NEXT FROM @ADJCUR INTO @SNO, @PARTY_CODE, @EXCHANGE, @SEGMENT, @LEDBAL
END
CLOSE @ADJCUR
DEALLOCATE @ADJCUR

UPDATE CLIENT_COLLATERAL_REPORTING_DETAILS_TODAY SET EDT_LEDGER = C.EDT_LEDGER
FROM #ADJDATALED C
WHERE PROCESS_DT = @RUNDATE
AND C.PARTY_CODE = CLIENT_COLLATERAL_REPORTING_DETAILS_TODAY.PARTY_CODE
AND C.EXCHANGE = CLIENT_COLLATERAL_REPORTING_DETAILS_TODAY.EXCHANGE
AND C.SEGMENT = CLIENT_COLLATERAL_REPORTING_DETAILS_TODAY.SEGMENT

SELECT DISTINCT PARTY_CODE INTO #PARTYUPLEDEPN
FROM CLIENT_COLLATERAL_REPORTING_DETAILS_TODAY
WHERE PROCESS_DT = @RUNDATE 
AND EDT_LEDGER+POOL_ACCOUNT_CLTM+LIEU_EPI_LEDGER_CLTM+
APPROVED_SEC_CASH_REC_TM+APPROVED_SEC_NONCASH_REC_TM+NONAPPROVED_SEC_REC_TM-UPFRONT_MARGIN < 0 
AND UPFRONT_MARGIN > 0 
AND EXCHANGE <> 'MTF'
AND PARTY_CODE IN ( SELECT PARTY_CODE
FROM CLIENT_COLLATERAL_REPORTING_DETAILS_TODAY
WHERE PROCESS_DT = @RUNDATE  
AND EDT_LEDGER+POOL_ACCOUNT_CLTM+LIEU_EPI_LEDGER_CLTM+
APPROVED_SEC_CASH_REC_TM+APPROVED_SEC_NONCASH_REC_TM+NONAPPROVED_SEC_REC_TM-UPFRONT_MARGIN >0 
AND EDT_LEDGER+LIEU_EPI_LEDGER_CLTM > 0 AND EXCHANGE <> 'MTF') 
AND PARTY_CODE <> ''

SELECT PARTY_CODE, EXCHANGE, SEGMENT, SHORT=EDT_LEDGER+POOL_ACCOUNT_CLTM+LIEU_EPI_LEDGER_CLTM+
APPROVED_SEC_CASH_REC_TM+APPROVED_SEC_NONCASH_REC_TM+NONAPPROVED_SEC_REC_TM-UPFRONT_MARGIN,EDT_LEDGER,LIEU_EPI_LEDGER_CLTM,VDT_LEDGER
INTO #ADJDATALEDEPN FROM CLIENT_COLLATERAL_REPORTING_DETAILS_TODAY
WHERE PROCESS_DT = @RUNDATE AND EXCHANGE <> 'MTF'
AND PARTY_CODE IN (SELECT PARTY_CODE FROM #PARTYUPLEDEPN)
AND PARTY_CODE <> ''

ALTER TABLE #ADJDATALEDEPN
ADD [SNO]			INT IDENTITY(1,1),
	[IsProcessed]	BIT ,
	[PartyCount]	INT,
	[Balance]		NUMERIC(19,6),
	[DIFFLEDBAL]	NUMERIC(19,6)

CREATE CLUSTERED INDEX IDXDT ON #ADJDATALEDEPN
(
	SNO
)

 UPDATE OBJ
	SET [PartyCount] = T.[Count]
 FROM #ADJDATALEDEPN OBJ
 INNER JOIN 
 (
	SELECT 
		[PARTY_CODE] ,
		[Count] = COUNT(*)
	FROM #ADJDATALEDEPN 
	WHERE SHORT > 0 AND LIEU_EPI_LEDGER_CLTM > 0 
	GROUP BY [PARTY_CODE]
 ) T ON OBJ.PARTY_CODE = T.PARTY_CODE

 UPDATE T 
	SET [Balance] =  CASE WHEN T.[SHORT] > T.[LIEU_EPI_LEDGER_CLTM] THEN T.[LIEU_EPI_LEDGER_CLTM] ELSE T.[SHORT] END
 FROM #ADJDATALEDEPN T 
 WHERE ISNULL(T.[PartyCount],0) = 1

UPDATE OBJ 
	SET OBJ.LIEU_EPI_LEDGER_CLTM = OBJ.LIEU_EPI_LEDGER_CLTM + (CASE WHEN ABS(OBJ.[SHORT]) > ABS(T.[Balance]) THEN ABS(T.[Balance]) ELSE ABS(OBJ.[SHORT]) END),
		OBJ.[DIFFLEDBAL] = (CASE WHEN ABS(OBJ.[SHORT]) > ABS(T.[Balance]) THEN ABS(T.[Balance]) ELSE ABS(OBJ.[SHORT]) END),
		OBJ.[IsProcessed] = 1
FROM #ADJDATALEDEPN OBJ
INNER JOIN #ADJDATALEDEPN T ON OBJ.PARTY_CODE = T.PARTY_CODE AND ISNULL(T.[PartyCount],0) = 1
AND OBJ.[SHORT] < 0

UPDATE OBJ 
	SET OBJ.LIEU_EPI_LEDGER_CLTM = OBJ.LIEU_EPI_LEDGER_CLTM - T.[DIFFLEDBAL]
FROM #ADJDATALEDEPN OBJ
INNER JOIN #ADJDATALEDEPN T ON OBJ.PARTY_CODE = T.PARTY_CODE AND ISNULL(OBJ.[PartyCount],0) = 1
AND T.[SHORT] < 0 AND T.[IsProcessed] = 1

SET @ADJCUR = CURSOR FAST_FORWARD FOR 
SELECT SNO, PARTY_CODE, EXCHANGE, SEGMENT, SHORT
FROM #ADJDATALEDEPN
WHERE SHORT < 0  AND [IsProcessed] <> 1
AND PARTY_CODE IN ( SELECT PARTY_CODE
FROM #ADJDATALEDEPN
WHERE SHORT > 0 AND ISNULL([PartyCount],0) <> 1 )
and PARTY_CODE <> ''
ORDER BY PARTY_CODE, EXCHANGE, SEGMENT
OPEN @ADJCUR
FETCH NEXT FROM @ADJCUR INTO @SNO, @PARTY_CODE, @EXCHANGE, @SEGMENT, @LEDBAL
WHILE @@FETCH_STATUS = 0 
BEGIN
	SET @ALLOCCURSOR = CURSOR FAST_FORWARD FOR 
	SELECT SNO, EXCHANGE, SEGMENT, BALANCE = (CASE WHEN SHORT > LIEU_EPI_LEDGER_CLTM THEN LIEU_EPI_LEDGER_CLTM ELSE SHORT END) 
	FROM #ADJDATALEDEPN
	WHERE PARTY_CODE = @PARTY_CODE AND SHORT > 0 AND LIEU_EPI_LEDGER_CLTM > 0  AND ISNULL([PartyCount],0) <> 1
	ORDER BY EXCHANGE, SEGMENT
	OPEN @ALLOCCURSOR
	FETCH NEXT FROM @ALLOCCURSOR INTO @NEWSNO, @NEWEXCHANGE, @NEWSEGMENT, @NEWLEDBAL
	WHILE @@FETCH_STATUS = 0 
	BEGIN
		IF @LEDBAL < 0 AND @NEWLEDBAL > 0 
		BEGIN
			SELECT @DIFFLEDBAL = (CASE WHEN ABS(@LEDBAL) > ABS(@NEWLEDBAL) THEN ABS(@NEWLEDBAL) ELSE ABS(@LEDBAL) END)
			UPDATE #ADJDATALEDEPN SET LIEU_EPI_LEDGER_CLTM = LIEU_EPI_LEDGER_CLTM - @DIFFLEDBAL, 
			VDT_LEDGER = VDT_LEDGER - @DIFFLEDBAL
			WHERE SNO = @NEWSNO

			UPDATE #ADJDATALEDEPN SET VDT_LEDGER = VDT_LEDGER + @DIFFLEDBAL, 
			LIEU_EPI_LEDGER_CLTM = LIEU_EPI_LEDGER_CLTM + @DIFFLEDBAL
			WHERE SNO = @SNO

			SET @LEDBAL = @LEDBAL + @DIFFLEDBAL
		END
		FETCH NEXT FROM @ALLOCCURSOR INTO @NEWSNO, @NEWEXCHANGE, @NEWSEGMENT, @NEWLEDBAL
	END
	CLOSE @ALLOCCURSOR
	DEALLOCATE @ALLOCCURSOR
	FETCH NEXT FROM @ADJCUR INTO @SNO, @PARTY_CODE, @EXCHANGE, @SEGMENT, @LEDBAL
END
CLOSE @ADJCUR
DEALLOCATE @ADJCUR

UPDATE CLIENT_COLLATERAL_REPORTING_DETAILS_TODAY SET VDT_LEDGER = C.VDT_LEDGER, LIEU_EPI_LEDGER_CLTM = C.LIEU_EPI_LEDGER_CLTM
FROM #ADJDATALEDEPN C
WHERE PROCESS_DT = @RUNDATE
AND C.PARTY_CODE = CLIENT_COLLATERAL_REPORTING_DETAILS_TODAY.PARTY_CODE
AND C.EXCHANGE = CLIENT_COLLATERAL_REPORTING_DETAILS_TODAY.EXCHANGE
AND C.SEGMENT = CLIENT_COLLATERAL_REPORTING_DETAILS_TODAY.SEGMENT

GO
