-- Object: PROCEDURE dbo.PROC_CLIENT_COLLATREAL_ALLOC_CMCC_BKUP_24SEP21
-- Server: 10.253.33.91 | DB: MSAJAG
--------------------------------------------------


CREATE PROC	[dbo].[PROC_CLIENT_COLLATREAL_ALLOC_CMCC]
(
	@RUNDATE VARCHAR(11)
)	
AS


-- EXEC PROC_CLIENT_COLLATREAL_ALLOC_CMCC 'SEP  2 2021'
DECLARE
		@PARTY_CODE	VARCHAR(10),
		@EXCHANGE	VARCHAR(3),
		@SEGMENT	VARCHAR(7),
		@NEWEXCHANGE	VARCHAR(3),
		@NEWSEGMENT	VARCHAR(7),
		@LEDBAL		NUMERIC(18,4),
		@NEWLEDBAL		NUMERIC(18,4),
		@DIFFLEDBAL		NUMERIC(18,4),
		@FDAMOUNT		NUMERIC(18,4),
		@SNO	INT,
		@NEWSNO	INT,
		@ACCOUNT_TYPE	VARCHAR(1),
		@ADJCUR		CURSOR,
		@ALLOCCURSOR	CURSOR,
		@SEGCUR		CURSOR
		
SELECT PARTY_CODE, EDT_LEDGER, VDT_LEDGER, EXCHANGE, SEGMENT, FD_REC_TM, FD_WCM, CASH_WCM, BG_REC_TM, BG_WCM 
INTO #SEGLED
FROM CLIENT_COLLATERAL_REPORTING_DETAILS
WHERE PRCOESS_DT = @RUNDATE  
AND EDT_LEDGER > 0 
AND EXCHANGE <> 'MTF' 
AND 1 = 2 

ALTER TABLE #SEGLED
ADD SNO INT IDENTITY(1,1)

CREATE CLUSTERED INDEX IDXDT ON #SEGLED
(
	SNO
)

SET @SEGCUR = CURSOR FOR
SELECT EXCHANGE, SEGMENT, FDAMOUNT, ACCOUNT_TYPE FROM TBL_CMCC_DATA
WHERE TRANSDATE= @RUNDATE AND FDAMOUNT > 0 
ORDER BY FDAMOUNT DESC
OPEN @SEGCUR
FETCH NEXT FROM @SEGCUR INTO @EXCHANGE, @SEGMENT, @FDAMOUNT, @ACCOUNT_TYPE
WHILE @@FETCH_STATUS = 0 
BEGIN   
	TRUNCATE TABLE #SEGLED
	INSERT  INTO #SEGLED
	SELECT PARTY_CODE, EDT_LEDGER, VDT_LEDGER, EXCHANGE, SEGMENT, FD_REC_TM, FD_WCM, CASH_WCM, BG_REC_TM, BG_WCM
	FROM CLIENT_COLLATERAL_REPORTING_DETAILS
	WHERE PRCOESS_DT = @RUNDATE  
	AND EDT_LEDGER > 0 
	AND EXCHANGE = @EXCHANGE
	AND SEGMENT = @SEGMENT
	AND ACCOUNT_TYPE = @ACCOUNT_TYPE

	SET @ADJCUR = CURSOR FOR 
	SELECT SNO, PARTY_CODE, EDT_LEDGER
	FROM #SEGLED 
	ORDER BY EDT_LEDGER DESC
	OPEN @ADJCUR
	FETCH NEXT FROM @ADJCUR INTO @SNO, @PARTY_CODE, @LEDBAL
	WHILE @@FETCH_STATUS = 0 
	BEGIN
		IF @LEDBAL >= @FDAMOUNT
		BEGIN 
			UPDATE #SEGLED SET EDT_LEDGER = EDT_LEDGER - @FDAMOUNT, VDT_LEDGER = VDT_LEDGER - @FDAMOUNT,
			FD_REC_TM = FD_REC_TM + @FDAMOUNT, FD_WCM = FD_WCM + @FDAMOUNT
			WHERE SNO = @SNO

			SET @FDAMOUNT = 0 
		END
		ELSE
		BEGIN	
			UPDATE #SEGLED SET EDT_LEDGER = EDT_LEDGER - @LEDBAL, VDT_LEDGER = VDT_LEDGER - @LEDBAL,
			FD_REC_TM = FD_REC_TM + @LEDBAL, FD_WCM = FD_WCM + @LEDBAL
			WHERE SNO = @SNO

			SET @FDAMOUNT = @FDAMOUNT - @LEDBAL
		END	
		IF @FDAMOUNT <= 0 
		BEGIN
			BREAK;
		END
		FETCH NEXT FROM @ADJCUR INTO @SNO, @PARTY_CODE, @LEDBAL	 
	END
	CLOSE @ADJCUR
	DEALLOCATE @ADJCUR
	FETCH NEXT FROM @SEGCUR INTO @EXCHANGE, @SEGMENT, @FDAMOUNT, @ACCOUNT_TYPE
END
CLOSE @SEGCUR
DEALLOCATE @SEGCUR

UPDATE CLIENT_COLLATERAL_REPORTING_DETAILS SET EDT_LEDGER = C.EDT_LEDGER,
VDT_LEDGER = C.VDT_LEDGER, FD_REC_TM = C.FD_REC_TM, FD_WCM = C.FD_WCM,
FD_WNCL = (CASE WHEN c.SEGMENT='CAPITAL' THEN c.FD_WCM ELSE FD_WNCL END)
FROM #SEGLED C
WHERE PRCOESS_DT = @RUNDATE
AND C.PARTY_CODE = CLIENT_COLLATERAL_REPORTING_DETAILS.PARTY_CODE
AND C.EXCHANGE = CLIENT_COLLATERAL_REPORTING_DETAILS.EXCHANGE
AND C.SEGMENT = CLIENT_COLLATERAL_REPORTING_DETAILS.SEGMENT

SET @SEGCUR = CURSOR FOR
SELECT EXCHANGE, SEGMENT, BGAMOUNT, ACCOUNT_TYPE FROM TBL_CMCC_DATA
WHERE TRANSDATE= @RUNDATE AND BGAMOUNT > 0 
ORDER BY FDAMOUNT DESC
OPEN @SEGCUR
FETCH NEXT FROM @SEGCUR INTO @EXCHANGE, @SEGMENT, @FDAMOUNT, @ACCOUNT_TYPE
WHILE @@FETCH_STATUS = 0 
BEGIN   
	TRUNCATE TABLE #SEGLED
	INSERT  INTO #SEGLED
	SELECT PARTY_CODE, EDT_LEDGER, VDT_LEDGER, EXCHANGE, SEGMENT, FD_REC_TM, FD_WCM, CASH_WCM, BG_REC_TM, BG_WCM
	FROM CLIENT_COLLATERAL_REPORTING_DETAILS
	WHERE PRCOESS_DT = @RUNDATE  
	AND EDT_LEDGER > 0 
	AND EXCHANGE = @EXCHANGE
	AND SEGMENT = @SEGMENT 	
	AND ACCOUNT_TYPE = @ACCOUNT_TYPE

		SET @ADJCUR = CURSOR FOR 
	SELECT SNO, PARTY_CODE, EDT_LEDGER
	FROM #SEGLED 
	ORDER BY EDT_LEDGER DESC
	OPEN @ADJCUR
	FETCH NEXT FROM @ADJCUR INTO @SNO, @PARTY_CODE, @LEDBAL
	WHILE @@FETCH_STATUS = 0 
	BEGIN
		IF @LEDBAL >= @FDAMOUNT
		BEGIN 
			UPDATE #SEGLED SET EDT_LEDGER = EDT_LEDGER - @FDAMOUNT, VDT_LEDGER = VDT_LEDGER - @FDAMOUNT,
			BG_REC_TM = BG_REC_TM + @FDAMOUNT, BG_WCM = BG_WCM + @FDAMOUNT
			WHERE SNO = @SNO

			SET @FDAMOUNT = 0 
		END
		ELSE
		BEGIN	
			UPDATE #SEGLED SET EDT_LEDGER = EDT_LEDGER - @LEDBAL, VDT_LEDGER = VDT_LEDGER - @LEDBAL,
			BG_REC_TM = BG_REC_TM + @LEDBAL, BG_WCM = BG_WCM + @LEDBAL
			WHERE SNO = @SNO

			SET @FDAMOUNT = @FDAMOUNT - @LEDBAL
		END	
		IF @FDAMOUNT <= 0 
		BEGIN
			BREAK;
		END
		FETCH NEXT FROM @ADJCUR INTO @SNO, @PARTY_CODE, @LEDBAL	 
	END
	CLOSE @ADJCUR
	DEALLOCATE @ADJCUR
	FETCH NEXT FROM @SEGCUR INTO @EXCHANGE, @SEGMENT, @FDAMOUNT, @ACCOUNT_TYPE
END
CLOSE @SEGCUR
DEALLOCATE @SEGCUR

UPDATE CLIENT_COLLATERAL_REPORTING_DETAILS SET EDT_LEDGER = C.EDT_LEDGER,
VDT_LEDGER = C.VDT_LEDGER, BG_REC_TM = C.BG_REC_TM, BG_WCM = C.BG_WCM,
BG_WNCL = (CASE WHEN c.SEGMENT='CAPITAL' THEN c.BG_WCM ELSE BG_WNCL END)
FROM #SEGLED C
WHERE PRCOESS_DT = @RUNDATE
AND C.PARTY_CODE = CLIENT_COLLATERAL_REPORTING_DETAILS.PARTY_CODE
AND C.EXCHANGE = CLIENT_COLLATERAL_REPORTING_DETAILS.EXCHANGE
AND C.SEGMENT = CLIENT_COLLATERAL_REPORTING_DETAILS.SEGMENT

SET @SEGCUR = CURSOR FOR
SELECT EXCHANGE, SEGMENT, CASHAMOUNT, ACCOUNT_TYPE FROM TBL_CMCC_DATA
WHERE TRANSDATE= @RUNDATE AND CASHAMOUNT > 0 
ORDER BY FDAMOUNT DESC
OPEN @SEGCUR
FETCH NEXT FROM @SEGCUR INTO @EXCHANGE, @SEGMENT, @FDAMOUNT, @ACCOUNT_TYPE
WHILE @@FETCH_STATUS = 0 
BEGIN   
	TRUNCATE TABLE #SEGLED
	INSERT  INTO #SEGLED
	SELECT PARTY_CODE, EDT_LEDGER, VDT_LEDGER, EXCHANGE, SEGMENT, FD_REC_TM, FD_WCM, CASH_WCM
	FROM CLIENT_COLLATERAL_REPORTING_DETAILS
	WHERE PRCOESS_DT = @RUNDATE  
	AND EDT_LEDGER > 0 
	AND EXCHANGE = @EXCHANGE
	AND SEGMENT = @SEGMENT 
	AND ACCOUNT_TYPE=@ACCOUNT_TYPE

	SET @ADJCUR = CURSOR FOR 
	SELECT SNO, PARTY_CODE, EDT_LEDGER
	FROM #SEGLED 
	ORDER BY EDT_LEDGER DESC
	OPEN @ADJCUR
	FETCH NEXT FROM @ADJCUR INTO @SNO, @PARTY_CODE, @LEDBAL
	WHILE @@FETCH_STATUS = 0 
	BEGIN
		IF @LEDBAL >= @FDAMOUNT
		BEGIN 
			UPDATE #SEGLED SET
			CASH_WCM = CASH_WCM + @FDAMOUNT
			WHERE SNO = @SNO

			SET @FDAMOUNT = 0 
		END
		ELSE
		BEGIN	
			UPDATE #SEGLED SET  
			CASH_WCM = CASH_WCM + @LEDBAL
			WHERE SNO = @SNO

			SET @FDAMOUNT = @FDAMOUNT - @LEDBAL
		END	
		IF @FDAMOUNT <= 0 
		BEGIN
			BREAK;
		END
		FETCH NEXT FROM @ADJCUR INTO @SNO, @PARTY_CODE, @LEDBAL	 
	END
	CLOSE @ADJCUR
	DEALLOCATE @ADJCUR
	FETCH NEXT FROM @SEGCUR INTO @EXCHANGE, @SEGMENT, @FDAMOUNT, @ACCOUNT_TYPE
END
CLOSE @SEGCUR
DEALLOCATE @SEGCUR

UPDATE CLIENT_COLLATERAL_REPORTING_DETAILS SET CASH_WCM = C.CASH_WCM, 
CASH_WNCL = (CASE WHEN c.SEGMENT='CAPITAL' THEN c.CASH_WCM ELSE CASH_WNCL END),
CASH_RET_TM = (CASE WHEN CLIENT_COLLATERAL_REPORTING_DETAILS.EDT_LEDGER - c.CASH_WCM > 0 
					THEN CLIENT_COLLATERAL_REPORTING_DETAILS.EDT_LEDGER - c.CASH_WCM ELSE 0 END)
FROM #SEGLED C
WHERE PRCOESS_DT = @RUNDATE
AND C.PARTY_CODE = CLIENT_COLLATERAL_REPORTING_DETAILS.PARTY_CODE
AND C.EXCHANGE = CLIENT_COLLATERAL_REPORTING_DETAILS.EXCHANGE
AND C.SEGMENT = CLIENT_COLLATERAL_REPORTING_DETAILS.SEGMENT

GO
