-- Object: PROCEDURE dbo.MARGIN_RELEASE
-- Server: 10.253.33.91 | DB: MSAJAG
--------------------------------------------------

CREATE PROC MARGIN_RELEASE
AS
SELECT SETT_NO,SETT_TYPE,START_DATE  INTO #SETT FROM SETT_MST WHERE SEC_PAYIN =(
SELECT MIN(SEC_PAYIN) FROM SETT_MST WHERE SEC_PAYIN >=CONVERT(VARCHAR(11),GETDATE(),120)
 )

SELECT PARTY_CODE,SETT_NO,SETT_TYPE, MARGIN=SUM(MINIMUM_MARGIN+ADNL_MRG) FROM TBL_MG02 T (NOLOCK) WHERE EXISTS (SELECT SETT_NO FROM #SETT S  (NOLOCK) WHERE 
T.SETT_NO=S.SETT_NO AND T.SETT_TYPE=S.SETT_TYPE AND T.MARGIN_DATE=START_DATE)
GROUP BY PARTY_CODE ,SETT_NO,SETT_TYPE
HAVING SUM(MINIMUM_MARGIN+ADNL_MRG) <>0

GO
