-- Object: PROCEDURE dbo.CLS_REPORT_FETCH
-- Server: 10.253.33.91 | DB: MSAJAG
--------------------------------------------------


CREATE PROC [dbo].[CLS_REPORT_FETCH]
	(
	@RPT_FETCHFOR	VARCHAR(15),
	@RPT_CODE		VARCHAR(10) = '',
	@RPT_EXCHANGE	VARCHAR(15) = ''
	)

	AS

	-- EXEC CLS_REPORT_FETCH 'RPTGRP','','NSE-CAPITAL'
	-- EXEC CLS_REPORT_FETCH 'RPTLIST','4','NSE-CAPITAL'

	CREATE TABLE #TBLREPORTS
		(
		SRNO		INT,
		RPT_NAME	VARCHAR(100)
		)

	/*
	IF @RPT_EXCHANGE <> ''
	BEGIN
		INSERT	INTO #TBLREPORTS
		SELECT	SRNO, RPT_NAME FROM CLS_REPORT_SETTING_EXTRA (NOLOCK)
		WHERE	EXCHANGE LIKE '%'+ @RPT_EXCHANGE +'%'
	END
	ELSE
	BEGIN
	*/
		INSERT	INTO #TBLREPORTS
		SELECT	SRNO, RPT_NAME FROM CLS_REPORT_SETTING (NOLOCK)
		WHERE	SRNO = (CASE WHEN @RPT_CODE = '' THEN SRNO ELSE @RPT_CODE END)
	--END


	IF @RPT_FETCHFOR = 'RPTGRP'
	BEGIN
		SELECT DISTINCT RPT_FILEFOR FROM CLS_REPORT_SETTING CL(NOLOCK)  
		WHERE EXISTS (SELECT RPT_NAME FROM #TBLREPORTS WHERE #TBLREPORTS.RPT_NAME = CL.RPT_NAME)
	END

	IF @RPT_FETCHFOR = 'RPTLIST'
	BEGIN
		SELECT * FROM CLS_REPORT_SETTING CL(NOLOCK)
		WHERE EXISTS (SELECT RPT_NAME FROM #TBLREPORTS WHERE #TBLREPORTS.RPT_NAME = CL.RPT_NAME)
		AND SRNO = (CASE WHEN @RPT_CODE = '' THEN SRNO ELSE @RPT_CODE END)
	END

	DROP TABLE #TBLREPORTS

GO
