-- Object: PROCEDURE dbo.CLS_DYNAMICREPORTGENERATOR
-- Server: 10.253.33.91 | DB: MSAJAG
--------------------------------------------------





CREATE PROCEDURE [dbo].[CLS_DYNAMICREPORTGENERATOR]
 (
 @CTRLGROUP VARCHAR(50) = '',
 @CTRLCODE VARCHAR(50) = '',
 @CATEGORY VARCHAR(50) = ''
) 

AS

	--This is for Distinct Menu Creation query with no parameter
	--Table Record Set - One	
	--SELECT DISTINCT CTRL_GROUP,CTRL_CODE,DESCRIPTION FROM CLS_DYANAMIC_REPORT_SETTINGS WHERE CTRL_GROUP !='' AND WHO_CAN_ACCESS LIKE  ',' + @CATEGORY + ',%'
	SELECT DISTINCT CTRL_GROUP,CTRL_CODE,DESCRIPTION FROM CLS_DYANAMIC_REPORT_SETTINGS WHERE CTRL_GROUP !='' AND WHO_CAN_ACCESS LIKE  ',%' + @CATEGORY + ',%'

   --This is for Report Selection query with Ctrl Code and Group Code
   --Table Record Set - Two	
   IF @CTRLGROUP <> '' AND @CTRLCODE <> ''
    BEGIN 
	   SELECT 
		   SRNO,CTRL_GROUP,CTRL_CODE,CTRL_TYPE,CTRL_ID,CTRL_LABEL,EVENTHANDLER,VALIDATION,INROW,DBTYPE,DEF_VALUE,LOV_QRY,F2_CODE,AUTOCOMPLETE_CODE,
		   DESCRIPTION,PROC_NAME_LVL1,PROC_PARAMS_LVL1,PROC_NAME_LVL2,PROC_PARAMS_LVL2,RPT_REDIRECT,RPT_REDIRECT_PARAM,REPORT_HEADER_LVL1,REPORT_HEADER_LVL2,
		   REPORT_TOTAL_LVL1,REPORT_SUBTOTAL_LVL1,REPORT_TOTAL_LVL2,REPORT_SUBTOTAL_LVL2,GEN_CSV,GEN_PDF,RESPONSE_FILE_NAME =RESPONSE_FILE_NAME,ACTIVE,
		   WHO_CAN_ACCESS
	   FROM 
		   CLS_DYANAMIC_REPORT_SETTINGS WHERE CTRL_GROUP = @CTRLGROUP AND CTRL_CODE = @CTRLCODE ORDER BY INROW
	END

GO
