-- Object: PROCEDURE dbo.UpdateTrade_NOTIS_BAKJUL212017
-- Server: 10.253.33.91 | DB: MSAJAG
--------------------------------------------------



  
CREATE PROC [dbo].[UpdateTrade_NOTIS_BAKJUL212017] AS          
UPDATE TRADE_IMP_NOTIS SET CPID = LEFT(CPID, 3), ORDERTIME = LEFT(ORDERTIME, 20)      
TRUNCATE TABLE TRADEMISSING          
INSERT INTO FTTRADE          
SELECT TRADE_NO,ORDER_NO,STATUS,SCRIP_CD,SERIES,SCRIPNAME,INSTRUMENT,BOOKTYPE,MARKETTYPE,USER_ID,PARTIPANTCODE,          
BRANCH_ID,SELL_BUY,TRADEQTY,MARKETRATE,PRO_CLI,PARTY_CODE,AUCTIONPART,AUCTIONNO,SETTNO,SAUDA_DATE,TRADEMODIFIED,          
CPID=ORDERTIME,1,'N','',MARKETRATE,'0'          
FROM TRADE_IMP_NOTIS  

INSERT INTO TRADE_CTCLID_TMP
SELECT DISTINCT SAUDA_DATE, ORDER_NO, SCRIP_CD, SERIES, RESERVE FROM TRADE_IMP_NOTIS
WHERE LEN(RESERVE) > 10

GO
