-- Object: PROCEDURE dbo.Updatetrade_standard
-- Server: 10.253.33.91 | DB: MSAJAG
--------------------------------------------------



CREATE PROC [dbo].[Updatetrade_standard] AS      
--UPDATE TRADE_IMP SET CPID = LEFT(CPID, 3), ORDERTIME = LEFT(ORDERTIME, 20)  

--UPDATE TRADE_STANDARD_IMP SET CPID = LEFT(CPID, 3), ORDER_TIME = LEFT(ORDER_TIME, 20) 
TRUNCATE TABLE TRADEMISSING   

UPDATE A SET RPTDTXSTS = PROCESS_VALUE
FROM TRADE_STANDARD_IMP A,TBL_STANDARD_VALUES B
WHERE A.RPTDTXSTS = B.FIELD_VALUE
AND FIELD_DESC='TRADESTATUS'
AND EXCHANGE='NSE'
AND SEGMENT='CAPITAL' 
 
INSERT INTO FTTRADE  
SELECT  TRADENO=UNQTRADIDR,
		ORDERNO=ISNULL(LTRIM(RTRIM(ORDRREF)),'000000000'),
		STATUS = RPTDTXSTS,
		SCRIP_CD=LTRIM(RTRIM(TCKRSYMB)),
		SERIES=LTRIM(RTRIM(SCTYSRS)),
		SCRIPNAME=LEFT(LTRIM(RTRIM(FININSTRMNM)),25),
		INSTRUMENT=SCTYSRS,
		PLCOFTRAD='1',---BOOKTYPE ---????
		MARKETTYPE=LEFT(LTRIM(RTRIM(MKTTPANDID)),1),
		USERID=ISNULL(LTRIM(RTRIM(INSTGUSR)),''),
		PARTIPANTCODE=case when ISNULL(CTDNPTCPTID,'') = '' then BRKR else LTRIM(RTRIM(REPLACE(ISNULL(CTDNPTCPTID,''),' ',''))) end,     
		BRNCHID=CLNTID,
		SELLBUY=CASE WHEN LTRIM(RTRIM(BUYSELLIND))='B' THEN '1' ELSE '2' END,
		TRADEQTY=LTRIM(RTRIM(TRADQTY)),
		MARKETRATE=LTRIM(RTRIM(PRIC)),
		PRO_CLI = CASE WHEN LTRIM(RTRIM(ClntTp))='C' THEN '1' WHEN LTRIM(RTRIM(ClntTp))='P' THEN '2' ELSE '3' END,
		PARTYCODE=LTRIM(RTRIM(CLNTID)),
		AUCTIONPART=LEFT(LTRIM(RTRIM(MKTTPANDID)),1) ,
		AUCTNID=CASE WHEN ORDRTP='Y' THEN 1 ELSE 0 END,
		SETTNO=ISNULL(LTRIM(RTRIM(SCTIESSTTLMTXID)),''),
		SAUDADATE=CAST(CONVERT(DATETIMEOFFSET,TRADDTTM,127) AS DATETIME),
		TRADEMODIFY=CAST(CONVERT(DATETIMEOFFSET,ORDRDTTM,127) AS DATETIME),      
		CPID=CAST(CONVERT(DATETIMEOFFSET,ISNULL(CONVERT(VARCHAR,LTRIM(RTRIM(ORDRDTTM))),''),127) AS DATETIME),
		SETTFLAG=1,
		TMARK='N',
		SCHEME=STTLMTP,
		DUMMY1=LTRIM(RTRIM(PRIC)),
		DUMMY2='0'      
FROM TRADE_STANDARD_IMP
WHERE SGMT='CM'
AND  Xchg = 'NSE' 
AND UPPER(TRADDT)<>'TRADDT'
TRUNCATE TABLE TRADE_STANDARD_IMP

GO
