-- Object: PROCEDURE dbo.RPT_CLIENT_COLL_ALLOC_CHK
-- Server: 10.253.33.91 | DB: MSAJAG
--------------------------------------------------



CREATE PROC [dbo].[RPT_CLIENT_COLL_ALLOC_CHK]
(
	@RUNDATE	VARCHAR(11),
	@FLAG		INT = 0,
	@PARTY_CODE VARCHAR(10) = ''
)
AS
DECLARE @PREVDATE VARCHAR(11),
		@FILENAME	VARCHAR(50),
		@BATCHNO	INT,
		@SNO	INT,
		@NOOFREC	INT,
		@FILEREC	INT,
		@MEMBERCODE	VARCHAR(10),
		@CMCUR		CURSOR,
		@ORG_MEMBERCODE	VARCHAR(10)

-- EXEC RPT_CLIENT_COLL_ALLOC @RUNDATE = 'FEB 10 2022'

SET @SNO=0
SET @FILEREC = 10000

IF (SELECT ISNULL(COUNT(1),0) FROM TBL_CLIENT_COLL_ALLOCATE WHERE PROCESS_DT = @RUNDATE
AND ALLOCATECASH > 0 ) <= 0 
BEGIN
	SELECT * FROM TBL_CLIENT_COLL_ALLOCATE WHERE 1 = 2
	RETURN
END
SELECT @MEMBERCODE = MEMBERCODE, @ORG_MEMBERCODE = MEMBERCODE  FROM OWNER 

SELECT @PREVDATE = ISNULL(MAX(PROCESS_DT),'APR  1 2020') FROM TBL_CLIENT_COLL_ALLOCATE 
WHERE PROCESS_DT < @RUNDATE

SELECT PARTY_CODE, SEGMENT_INDICATOR, CP_CODE, ACCOUNT_TYPE, 
P_ALLOCATECASH=(CASE WHEN ALLOCATECASH > 0 THEN ALLOCATECASH ELSE CONVERT(NUMERIC(18,2),0) END),
C_ALLOCATECASH=CONVERT(NUMERIC(18,2),0),EXCHANGE,SEGMENT 
INTO #DATA FROM TBL_CLIENT_COLL_ALLOCATE
WHERE PROCESS_DT = @PREVDATE
AND ALLOCATECASH > 0
AND 1 = 2 

SELECT EXCHANGE, SEGMENT, PARTY_CODE=CLI_CODE,CP_CODE,UPLOAD_ON=MAX(UPLOAD_ON) INTO #ALLOC_SEG FROM TBL_CLIENT_COLL_FILE 
WHERE FILEDATE = @RUNDATE AND BATCH_STATUS IN ('G','D')  
GROUP BY EXCHANGE, SEGMENT, CLI_CODE,CP_CODE

CREATE INDEX #PARTY ON #ALLOC_SEG(EXCHANGE,SEGMENT,PARTY_CODE)

INSERT INTO #DATA 
SELECT PARTY_CODE, SEGMENT_INDICATOR, CP_CODE, ACCOUNT_TYPE, 
P_ALLOCATECASH=(CASE WHEN ALLOCATECASH > 0 THEN ALLOCATECASH ELSE 0 END),
C_ALLOCATECASH=CONVERT(NUMERIC(18,2),0),EXCHANGE,SEGMENT 
FROM TBL_CLIENT_COLL_ALLOCATE 
WHERE PROCESS_DT = @PREVDATE
AND ALLOCATECASH > 0
AND EXCHANGE NOT IN (SELECT EXCHANGE FROM #ALLOC_SEG 
WHERE #ALLOC_SEG.EXCHANGE = TBL_CLIENT_COLL_ALLOCATE.EXCHANGE
AND #ALLOC_SEG.SEGMENT = TBL_CLIENT_COLL_ALLOCATE.SEGMENT
AND #ALLOC_SEG.PARTY_CODE = TBL_CLIENT_COLL_ALLOCATE.PARTY_CODE 
AND #ALLOC_SEG.CP_CODE = TBL_CLIENT_COLL_ALLOCATE.CP_CODE)
AND 1 = (CASE WHEN(EXCHANGE = 'MCX' AND SEGMENT ='FUTURES') THEN 0 ELSE 1 END)
AND 1 = (CASE WHEN(EXCHANGE = 'NCX' AND SEGMENT ='FUTURES') THEN 0 ELSE 1 END) 
AND EXCHANGE NOT IN ('NSE','NSX','BSE','BSX','BCX')
AND PARTY_CODE = CASE WHEN @PARTY_CODE <> '' THEN @PARTY_CODE ELSE PARTY_CODE END
 
INSERT INTO #DATA 
SELECT PARTY_CODE=(CASE WHEN LEN(CLIENTCODE) > 10 THEN '' ELSE CLIENTCODE END), SEGMENT_INDICATOR='', 
CP_CODE=(CASE WHEN LEN(CLIENTCODE) > 10 THEN CLIENTCODE ELSE '' END), 
ACCOUNT_TYPE=(CASE WHEN CLIENTCODE = '' THEN 'P' ELSE 'C' END), 
P_ALLOCATECASH=AMOUNT,
C_ALLOCATECASH=CONVERT(NUMERIC(18,2),0),EXCHANGE,SEGMENT 
FROM TBL_CLIENT_COLL_RECO
WHERE TRANSDATE = @RUNDATE   
AND EXCHANGE IN ('MCX','NCX','BSE','BSX','BCX')
AND CLIENTCODE = CASE WHEN @PARTY_CODE <> '' THEN @PARTY_CODE ELSE CLIENTCODE END

INSERT INTO #DATA 
SELECT PARTY_CODE=(CASE WHEN LEN(CLIENTCODE) > 10 THEN '' ELSE CLIENTCODE END), SEGMENT_INDICATOR='', 
CP_CODE=(CASE WHEN LEN(CLIENTCODE) > 10 THEN CLIENTCODE ELSE '' END), 
ACCOUNT_TYPE=(CASE WHEN CLIENTCODE = '' THEN 'P' ELSE 'C' END), 
P_ALLOCATECASH=AMOUNT,
C_ALLOCATECASH=CONVERT(NUMERIC(18,2),0),EXCHANGE,SEGMENT 
FROM TBL_CLIENT_COLL_RECO
WHERE TRANSDATE = @PREVDATE   
AND EXCHANGE IN ('NSE','NSX')
AND EXCHANGE NOT IN (SELECT EXCHANGE FROM #ALLOC_SEG 
WHERE #ALLOC_SEG.EXCHANGE = TBL_CLIENT_COLL_RECO.EXCHANGE
AND #ALLOC_SEG.SEGMENT = TBL_CLIENT_COLL_RECO.SEGMENT
AND #ALLOC_SEG.PARTY_CODE = (CASE WHEN LEN(TBL_CLIENT_COLL_RECO.CLIENTCODE) <= 10 THEN TBL_CLIENT_COLL_RECO.CLIENTCODE ELSE '' END)
AND #ALLOC_SEG.CP_CODE = (CASE WHEN LEN(TBL_CLIENT_COLL_RECO.CLIENTCODE) > 10 THEN TBL_CLIENT_COLL_RECO.CLIENTCODE ELSE '' END))
AND CLIENTCODE = CASE WHEN @PARTY_CODE <> '' THEN @PARTY_CODE ELSE CLIENTCODE END

UPDATE #DATA SET SEGMENT_INDICATOR = SEG_TYPE
FROM TBL_CMCC_DETAIL T
WHERE @RUNDATE BETWEEN FROM_DATE AND TO_DATE 
AND #DATA.EXCHANGE = T.EXCHANGE AND #DATA.SEGMENT = T.SEGMENT 

INSERT INTO #DATA 
SELECT PARTY_CODE=CLI_CODE, SEGMENT_INDICATOR, CP_CODE, ACCOUNT_TYPE, 
P_ALLOCATECASH=(CASE WHEN AMOUNT > 0 THEN AMOUNT ELSE 0 END),
C_ALLOCATECASH=CONVERT(NUMERIC(18,2),0),EXCHANGE,SEGMENT 
FROM TBL_CLIENT_COLL_FILE WITH(NOLOCK)
WHERE FIlEDATE = @RUNDATE  AND BATCH_STATUS IN ('G','D')
AND AMOUNT > 0 
AND EXISTS (SELECT EXCHANGE FROM #ALLOC_SEG WITH(NOLOCK)
WHERE #ALLOC_SEG.EXCHANGE = TBL_CLIENT_COLL_FILE.EXCHANGE
AND #ALLOC_SEG.SEGMENT = TBL_CLIENT_COLL_FILE.SEGMENT
AND #ALLOC_SEG.PARTY_CODE = TBL_CLIENT_COLL_FILE.CLI_CODE 
AND #ALLOC_SEG.CP_CODE = TBL_CLIENT_COLL_FILE.CP_CODE 
AND #ALLOC_SEG.UPLOAD_ON = TBL_CLIENT_COLL_FILE.UPLOAD_ON)
AND EXCHANGE NOT IN ('MCX','NCX','BSE','BSX','BCX')
AND CLI_CODE = CASE WHEN @PARTY_CODE <> '' THEN @PARTY_CODE ELSE CLI_CODE END

INSERT INTO #DATA 
SELECT PARTY_CODE, SEGMENT_INDICATOR, CP_CODE, ACCOUNT_TYPE, 
P_ALLOCATECASH=CONVERT(NUMERIC(18,2),0),
C_ALLOCATECASH=(CASE WHEN ALLOCATECASH > 0 THEN ALLOCATECASH ELSE 0 END),EXCHANGE,SEGMENT 
FROM TBL_CLIENT_COLL_ALLOCATE
WHERE PROCESS_DT = @RUNDATE
AND ALLOCATECASH > 0 
AND PARTY_CODE = CASE WHEN @PARTY_CODE <> '' THEN @PARTY_CODE ELSE PARTY_CODE END
 
IF @FLAG = 0 OR @FLAG = 1 
BEGIN 
	SELECT FILENAME='WORKING_'+REPLACE(CONVERT(VARCHAR,CONVERT(DATETIME,@RUNDATE),103),'/','')+'.CSV',
	DATA='PARTY_CODE,CLEARING_PAN,TRADING_PAN,CP_CODE,CP_PAN,CLIENT_PAN,ACCOUNT_TYPE,SEGMENT_INDICATOR,'+
		'EXCHANGE,SEGMENT,CLIENTCOLL_ORG,CLIENTCOLLCASH,CLIENTCOLLNONCASH,REPLD_NONCASH,REPLD_NONCASHEQ,'+
		'MARGIN,MARGIN_SHORT_EXCESS,PEAK_MARGIN,UPFRONT_MARGIN,ALLOCATECASH,ALLOCATENONCASH,'+
		'BALANCECASH,BALANCENONCASH,PROCASH,CLIENTCASH,BALANCEPROFUNDSHORT,EPNAMOUNT,'+
		'EXCESSCOLL,BLOCKFUND',FLAG=1
		INTO #WORKINGDATA
	UNION ALL
	SELECT  FILENAME='WORKING_'+REPLACE(CONVERT(VARCHAR,CONVERT(DATETIME,@RUNDATE),103),'/','')+'.CSV',
	LTRIM(RTRIM(CONVERT(VARCHAR,PARTY_CODE)))+','+LTRIM(RTRIM(CONVERT(VARCHAR,CLEARING_PAN)))+','+LTRIM(RTRIM(CONVERT(VARCHAR,TRADING_PAN)))+','+LTRIM(RTRIM(CONVERT(VARCHAR,CP_CODE)))+','+
	LTRIM(RTRIM(CONVERT(VARCHAR,CP_PAN)))+','+LTRIM(RTRIM(CONVERT(VARCHAR,CLIENT_PAN)))+','+LTRIM(RTRIM(CONVERT(VARCHAR,ACCOUNT_TYPE)))+','+LTRIM(RTRIM(CONVERT(VARCHAR,SEGMENT_INDICATOR)))+','+
	LTRIM(RTRIM(CONVERT(VARCHAR,EXCHANGE)))+','+LTRIM(RTRIM(CONVERT(VARCHAR,SEGMENT)))+','+LTRIM(RTRIM(CONVERT(VARCHAR,CLIENTCOLL_ORG)))+','+LTRIM(RTRIM(CONVERT(VARCHAR,CLIENTCOLLCASH)))+','+
	LTRIM(RTRIM(CONVERT(VARCHAR,CLIENTCOLLNONCASH)))+','+LTRIM(RTRIM(CONVERT(VARCHAR,REPLD_NONCASH)))+','+LTRIM(RTRIM(CONVERT(VARCHAR,REPLD_NONCASHEQ)))+','+LTRIM(RTRIM(CONVERT(VARCHAR,MARGIN)))+','+
	LTRIM(RTRIM(CONVERT(VARCHAR,MARGIN_SHORT_EXCESS)))+','+LTRIM(RTRIM(CONVERT(VARCHAR,PEAK_MARGIN)))+','+LTRIM(RTRIM(CONVERT(VARCHAR,UPFRONT_MARGIN)))+','+ 
	LTRIM(RTRIM(CONVERT(VARCHAR,PROCASH+CC_CM_CASH)))+','+LTRIM(RTRIM(CONVERT(VARCHAR,ALLOCATENONCASH)))+','+LTRIM(RTRIM(CONVERT(VARCHAR,BALANCECASH)))+','+
	LTRIM(RTRIM(CONVERT(VARCHAR,BALANCENONCASH)))+','+LTRIM(RTRIM(CONVERT(VARCHAR,PROCASH)))+','+LTRIM(RTRIM(CONVERT(VARCHAR,CC_CM_CASH)))+','+
	LTRIM(RTRIM(CONVERT(VARCHAR,TOTALMARGIN)))+','+LTRIM(RTRIM(CONVERT(VARCHAR,MARGINRATIO)))+','+LTRIM(RTRIM(CONVERT(VARCHAR,EXCESSCOLL)))+','+LTRIM(RTRIM(CONVERT(VARCHAR,BLOCKFUND))),FLAG=2
	FROM TBL_CLIENT_COLL_ALLOCATE
	WHERE PROCESS_DT= @RUNDATE  
	AND PARTY_CODE = CASE WHEN @PARTY_CODE <> '' THEN @PARTY_CODE ELSE PARTY_CODE END
 
	SELECT FILENAME,DATA FROM #WORKINGDATA
	ORDER BY FLAG 
END

SELECT [CURRENT DATE]=REPLACE(CONVERT(VARCHAR,CONVERT(DATETIME,@RUNDATE),106),' ','-'),
	   T.EXCHANGE, T.SEGMENT, 
	   SEGMENT_INDICATOR,
	   [CM CODE]=CMCODE,
	   [TM CODE]=(CASE WHEN ACCOUNT_TYPE = 'P' THEN '' ELSE TMCODE END),
	   [CP CODE]=CP_CODE,
	   [CLI CODE]=PARTY_CODE,
	[ACCOUNT TYPE]=ACCOUNT_TYPE,
	AMOUNT=SUM(C_ALLOCATECASH), 
	FILLER1='',
	FILLER2='',
	FILLER3='',
	FILLER4='',
	FILLER5='',
	FILLER6='',
	ACTION=(CASE WHEN SUM(C_ALLOCATECASH)-SUM(P_ALLOCATECASH) > 0 THEN 'U' ELSE 'D' END)
	INTO #FILEDATA_NSE
FROM #DATA T, TBL_CMCC_DETAIL C
WHERE @RUNDATE BETWEEN FROM_DATE AND TO_DATE
AND T.EXCHANGE = C.EXCHANGE AND T.SEGMENT=C.SEGMENT
AND T.EXCHANGE IN ('NSE','NSX','NCE')
GROUP BY CMCODE, TMCODE, T.EXCHANGE, T.SEGMENT, SEGMENT_INDICATOR, PARTY_CODE, CP_CODE, ACCOUNT_TYPE
HAVING SUM(C_ALLOCATECASH) <> SUM(P_ALLOCATECASH)
ORDER BY CMCODE, TMCODE, ACTION, PARTY_CODE, SEGMENT_INDICATOR

SELECT * INTO #FILEDATA 
FROM #FILEDATA_NSE
WHERE 1 = 2 

SELECT * INTO #FILEDATA_D
FROM #FILEDATA_NSE
WHERE 1 = 2 

ALTER TABLE #FILEDATA
ADD SNO INT IDENTITY(1,1)

ALTER TABLE #FILEDATA_D
ADD SNO INT IDENTITY(1,1)

INSERT INTO #FILEDATA
SELECT [CURRENT DATE], EXCHANGE, SEGMENT, [SEGMENT_INDICATOR], [CM CODE], [TM CODE], [CP CODE], [CLI CODE], [ACCOUNT TYPE], [AMOUNT], [FILLER1], [FILLER2], [FILLER3], [FILLER4], [FILLER5], [FILLER6], [ACTION]
FROM #FILEDATA_NSE
WHERE ACTION='D'
ORDER BY ACTION, EXCHANGE, SEGMENT, [CLI CODE]

INSERT INTO #FILEDATA_D
SELECT [CURRENT DATE], EXCHANGE, SEGMENT, [SEGMENT_INDICATOR], [CM CODE], [TM CODE], [CP CODE], [CLI CODE], [ACCOUNT TYPE], [AMOUNT], [FILLER1], [FILLER2], [FILLER3], [FILLER4], [FILLER5], [FILLER6], [ACTION]
FROM #FILEDATA_NSE
WHERE ACTION='U'
ORDER BY ACTION, EXCHANGE, SEGMENT, [CLI CODE]

IF @FLAG = 0 OR @FLAG = 2 
BEGIN 
	SELECT FILENME='NSEFULLFILE_'+REPLACE(CONVERT(VARCHAR,CONVERT(DATETIME,@RUNDATE),103),'/','')+'.CSV',
	[CURRENT DATE], [SEGMENT_INDICATOR], [CM CODE], [TM CODE], [CP CODE], [CLI CODE], [ACCOUNT TYPE], 
	[AMOUNT], [FILLER1], [FILLER2], [FILLER3], [FILLER4], [FILLER5], [FILLER6], [ACTION]
	FROM #FILEDATA
	UNION ALL
	SELECT FILENME='NSEFULLFILE_'+REPLACE(CONVERT(VARCHAR,CONVERT(DATETIME,@RUNDATE),103),'/','')+'.CSV',
	[CURRENT DATE], [SEGMENT_INDICATOR], [CM CODE], [TM CODE], [CP CODE], [CLI CODE], [ACCOUNT TYPE], 
	[AMOUNT], [FILLER1], [FILLER2], [FILLER3], [FILLER4], [FILLER5], [FILLER6], [ACTION]
	FROM #FILEDATA_D
	ORDER BY 7 
END

IF @FLAG = 0 OR @FLAG = 2 
BEGIN 
SET @NOOFREC = 0

SELECT @NOOFREC = ISNULL(COUNT(1),0) FROM #FILEDATA
WHERE [CM CODE] = @ORG_MEMBERCODE
AND ACTION = 'D'
IF @NOOFREC > 0 
BEGIN
	SET @CMCUR	= CURSOR FOR
	SELECT DISTINCT [CM CODE] FROM #FILEDATA
	WHERE [CM CODE] = @ORG_MEMBERCODE
	AND ACTION = 'D'
	OPEN @CMCUR
	FETCH NEXT FROM @CMCUR INTO @MEMBERCODE
	WHILE @@FETCH_STATUS = 0
	BEGIN	
		SELECT @BATCHNO = 0    
		SET @SNO = 0  
    
		SELECT @BATCHNO = ISNULL(MAX(FLDBATCHNO),0) FROM ASIANFILEBATCHNO    
		WHERE FLDFILENO = @MEMBERCODE    
		AND FLDFILEDATE = @RUNDATE  
 
		WHILE @SNO < @NOOFREC
		BEGIN
			SET @BATCHNO = @BATCHNO + 1 
			SET @FILENAME = @MEMBERCODE + '_ALLOC_' + REPLACE(CONVERT(VARCHAR,CONVERT(DATETIME,@RUNDATE),103),'/','') +'.T'+RIGHT('0000'+CONVERT(VARCHAR,@BATCHNO),4)

			SELECT FILENAME=@FILENAME,
			[CURRENT DATE], [SEGMENT_INDICATOR], [CM CODE], 
			[TM CODE] = (CASE WHEN [ACCOUNT TYPE] = 'P' THEN '' ELSE [TM CODE] END), [CP CODE], [CLI CODE], [ACCOUNT TYPE], [AMOUNT], [FILLER1], [FILLER2], [FILLER3], [FILLER4], [FILLER5], [FILLER6], [ACTION]
			FROM #FILEDATA
			WHERE SNO > @SNO AND SNO <= @SNO + @FILEREC
			AND [CM CODE] = @MEMBERCODE
			AND ACTION = 'D'
			ORDER BY SNO 
			
			INSERT INTO TBL_CLIENT_COLL_FILE 
			SELECT FILENAME=@FILENAME,
			[CURRENT DATE], EXCHANGE, SEGMENT, [SEGMENT_INDICATOR], [CM CODE], [TM CODE], [CP CODE], [CLI CODE], [ACCOUNT TYPE], [AMOUNT], [FILLER1], [FILLER2], [FILLER3], [FILLER4], [FILLER5], [FILLER6], [ACTION],
			@BATCHNO,'CLASSBO','',GETDATE(),'G','','',GETDATE()	
			FROM #FILEDATA
			WHERE SNO > @SNO AND SNO <= @SNO + @FILEREC
			AND [CM CODE] = @MEMBERCODE
			AND ACTION = 'D'
			ORDER BY SNO 			 
			
			SET @SNO = @SNO + @FILEREC
		END

		INSERT INTO ASIANFILEBATCHNO    
		SELECT @MEMBERCODE, @BATCHNO, @RUNDATE, GETDATE()

		FETCH NEXT FROM @CMCUR INTO @MEMBERCODE
	END
END


SET @NOOFREC = 0

SELECT @NOOFREC = ISNULL(COUNT(1),0) FROM #FILEDATA_D
WHERE [CM CODE] = @ORG_MEMBERCODE
AND ACTION = 'U'
IF @NOOFREC > 0 
BEGIN
	SET @CMCUR	= CURSOR FOR
	SELECT DISTINCT [CM CODE] FROM #FILEDATA_D
	WHERE [CM CODE] = @ORG_MEMBERCODE
	AND ACTION = 'U'
	OPEN @CMCUR
	FETCH NEXT FROM @CMCUR INTO @MEMBERCODE
	WHILE @@FETCH_STATUS = 0
	BEGIN	
		SELECT @BATCHNO = 0    
		SELECT @SNO = 0  
    
		SELECT @BATCHNO = ISNULL(MAX(FLDBATCHNO),0) FROM ASIANFILEBATCHNO    
		WHERE FLDFILENO = @MEMBERCODE    
		AND FLDFILEDATE = @RUNDATE  
 
		WHILE @SNO < @NOOFREC
		BEGIN
			SET @BATCHNO = @BATCHNO + 1 
			SET @FILENAME = @MEMBERCODE + '_ALLOC_' + REPLACE(CONVERT(VARCHAR,CONVERT(DATETIME,@RUNDATE),103),'/','') +'.T'+RIGHT('0000'+CONVERT(VARCHAR,@BATCHNO),4)

			SELECT FILENAME=@FILENAME,
			[CURRENT DATE], [SEGMENT_INDICATOR], [CM CODE], 
			[TM CODE] = (CASE WHEN [ACCOUNT TYPE] = 'P' THEN '' ELSE [TM CODE] END), [CP CODE], [CLI CODE], [ACCOUNT TYPE], [AMOUNT], [FILLER1], [FILLER2], [FILLER3], [FILLER4], [FILLER5], [FILLER6], [ACTION]
			FROM #FILEDATA_D
			WHERE SNO > @SNO AND SNO <= @SNO + @FILEREC
			AND [CM CODE] = @MEMBERCODE
			AND ACTION = 'U'
			ORDER BY SNO 
			
			INSERT INTO TBL_CLIENT_COLL_FILE 
			SELECT FILENAME=@FILENAME,
			[CURRENT DATE], EXCHANGE, SEGMENT, [SEGMENT_INDICATOR], [CM CODE], [TM CODE], [CP CODE], [CLI CODE], [ACCOUNT TYPE], [AMOUNT], [FILLER1], [FILLER2], [FILLER3], [FILLER4], [FILLER5], [FILLER6], [ACTION],
			@BATCHNO,'CLASSBO','',GETDATE(),'G','','',GETDATE()	
			FROM #FILEDATA_D
			WHERE SNO > @SNO AND SNO <= @SNO + @FILEREC
			AND [CM CODE] = @MEMBERCODE
			AND ACTION = 'U'
			ORDER BY SNO 			 
			
			SET @SNO = @SNO + @FILEREC
		END

		INSERT INTO ASIANFILEBATCHNO    
		SELECT @MEMBERCODE, @BATCHNO, @RUNDATE, GETDATE()

		FETCH NEXT FROM @CMCUR INTO @MEMBERCODE
	END
END

SET @NOOFREC = 0

SELECT @NOOFREC = ISNULL(COUNT(1),0) FROM #FILEDATA
WHERE [CM CODE] <> @ORG_MEMBERCODE
IF @NOOFREC > 0 
BEGIN
	SET @CMCUR	= CURSOR FOR
	SELECT DISTINCT [CM CODE] FROM #FILEDATA
	WHERE [CM CODE] <> @ORG_MEMBERCODE
	OPEN @CMCUR
	FETCH NEXT FROM @CMCUR INTO @MEMBERCODE
	WHILE @@FETCH_STATUS = 0
	BEGIN	
		SELECT @BATCHNO = 0    
		SET @SNO = 0  
    
		SELECT @BATCHNO = ISNULL(MAX(FLDBATCHNO),0) FROM ASIANFILEBATCHNO    
		WHERE FLDFILENO = @MEMBERCODE    
		AND FLDFILEDATE = @RUNDATE  
  
		SET @BATCHNO = @BATCHNO + 1 
		SET @FILENAME = @MEMBERCODE + '_ALLOC_' + REPLACE(CONVERT(VARCHAR,CONVERT(DATETIME,@RUNDATE),103),'/','') +'.T'+RIGHT('0000'+CONVERT(VARCHAR,@BATCHNO),4)

		SELECT FILENAME=@FILENAME,
		[CURRENT DATE], [SEGMENT_INDICATOR], [CM CODE], [TM CODE], [CP CODE], [CLI CODE], [ACCOUNT TYPE], [AMOUNT], [FILLER1], [FILLER2], [FILLER3], [FILLER4], [FILLER5], [FILLER6], [ACTION]
		FROM #FILEDATA
		WHERE [CM CODE] = @MEMBERCODE
		ORDER BY SNO 
			
		INSERT INTO TBL_CLIENT_COLL_FILE 
		SELECT FILENAME=@FILENAME,
		[CURRENT DATE], EXCHANGE, SEGMENT, [SEGMENT_INDICATOR], [CM CODE], [TM CODE], [CP CODE], [CLI CODE], [ACCOUNT TYPE], [AMOUNT], [FILLER1], [FILLER2], [FILLER3], [FILLER4], [FILLER5], [FILLER6], [ACTION],
		@BATCHNO,'CLASSBO','',GETDATE(),'G','','',GETDATE()	
		FROM #FILEDATA
		WHERE [CM CODE] = @MEMBERCODE
		ORDER BY SNO 			 
			 
		INSERT INTO ASIANFILEBATCHNO    
		SELECT @MEMBERCODE, @BATCHNO, @RUNDATE, GETDATE()

		FETCH NEXT FROM @CMCUR INTO @MEMBERCODE
	END
END


SET @NOOFREC = 0

SELECT @NOOFREC = ISNULL(COUNT(1),0) FROM #FILEDATA_D
WHERE [CM CODE] <> @ORG_MEMBERCODE
IF @NOOFREC > 0 
BEGIN
	SET @CMCUR	= CURSOR FOR
	SELECT DISTINCT [CM CODE] FROM #FILEDATA_D
	WHERE [CM CODE] <> @ORG_MEMBERCODE
	OPEN @CMCUR
	FETCH NEXT FROM @CMCUR INTO @MEMBERCODE
	WHILE @@FETCH_STATUS = 0
	BEGIN	
		SELECT @BATCHNO = 0    
		SET @SNO = 0  
    
		SELECT @BATCHNO = ISNULL(MAX(FLDBATCHNO),0) FROM ASIANFILEBATCHNO    
		WHERE FLDFILENO = @MEMBERCODE    
		AND FLDFILEDATE = @RUNDATE  
  
		SET @BATCHNO = @BATCHNO + 1 
		SET @FILENAME = @MEMBERCODE + '_ALLOC_' + REPLACE(CONVERT(VARCHAR,CONVERT(DATETIME,@RUNDATE),103),'/','') +'.T'+RIGHT('0000'+CONVERT(VARCHAR,@BATCHNO),4)

		SELECT FILENAME=@FILENAME,
		[CURRENT DATE], [SEGMENT_INDICATOR], [CM CODE], [TM CODE], [CP CODE], [CLI CODE], [ACCOUNT TYPE], [AMOUNT], [FILLER1], [FILLER2], [FILLER3], [FILLER4], [FILLER5], [FILLER6], [ACTION]
		FROM #FILEDATA_D
		WHERE [CM CODE] = @MEMBERCODE
		ORDER BY SNO 
			
		INSERT INTO TBL_CLIENT_COLL_FILE 
		SELECT FILENAME=@FILENAME,
		[CURRENT DATE], EXCHANGE, SEGMENT, [SEGMENT_INDICATOR], [CM CODE], [TM CODE], [CP CODE], [CLI CODE], [ACCOUNT TYPE], [AMOUNT], [FILLER1], [FILLER2], [FILLER3], [FILLER4], [FILLER5], [FILLER6], [ACTION],
		@BATCHNO,'CLASSBO','',GETDATE(),'G','','',GETDATE()	
		FROM #FILEDATA_D
		WHERE [CM CODE] = @MEMBERCODE
		ORDER BY SNO 			 
			 
		INSERT INTO ASIANFILEBATCHNO    
		SELECT @MEMBERCODE, @BATCHNO, @RUNDATE, GETDATE()

		FETCH NEXT FROM @CMCUR INTO @MEMBERCODE
	END
END
END

SELECT [CURRENT DATE]=REPLACE(CONVERT(VARCHAR,CONVERT(DATETIME,@RUNDATE),106),' ','-'),
	   T.EXCHANGE, T.SEGMENT,
	   SEGMENT_INDICATOR,
	   [CM CODE]=CMCODE,
	   [TM CODE]=(CASE WHEN ACCOUNT_TYPE = 'P' THEN '' ELSE TMCODE END),
	   [CP CODE]=CP_CODE,
	   [CLI CODE]=PARTY_CODE,
	[ACCOUNT TYPE]=ACCOUNT_TYPE,
	AMOUNT=SUM(C_ALLOCATECASH), 
	FILLER1='',
	FILLER2='',
	FILLER3='',
	FILLER4='',
	FILLER5='',
	FILLER6='',
	ACTION='A',
	ORDERACTION=(CASE WHEN SUM(C_ALLOCATECASH)-SUM(P_ALLOCATECASH) > 0 THEN 'U' ELSE 'D' END),
	P_ALLOCATECASH = SUM(P_ALLOCATECASH)
	INTO #FILEDATA_BSE
FROM #DATA T, TBL_CMCC_DETAIL C
WHERE @RUNDATE BETWEEN FROM_DATE AND TO_DATE
AND T.EXCHANGE = C.EXCHANGE AND T.SEGMENT=C.SEGMENT
AND T.EXCHANGE IN ('BSE','BSX','BCX')
GROUP BY CMCODE, TMCODE, T.EXCHANGE, T.SEGMENT, SEGMENT_INDICATOR, PARTY_CODE, CP_CODE, ACCOUNT_TYPE
HAVING SUM(C_ALLOCATECASH) <> SUM(P_ALLOCATECASH)
ORDER BY ACTION, CMCODE, TMCODE, PARTY_CODE, SEGMENT_INDICATOR

SELECT EXCHANGE, SEGMENT, [SEGMENT_INDICATOR], [CM CODE], [TM CODE], [CP CODE], [CLI CODE], [ACCOUNT TYPE], AMOUNT, P_ALLOCATECASH, DIFFAMT = CONVERT(NUMERIC(18,3),0)
INTO #PRODIFF_ICCL FROM #FILEDATA_BSE WHERE [ACCOUNT TYPE]='P'

INSERT INTO #PRODIFF_ICCL
SELECT DISTINCT EXCHANGE, SEGMENT, [SEGMENT_INDICATOR], [CM CODE], [TM CODE], [CP CODE], [CLI CODE] = '', [ACCOUNT TYPE] = 'P', AMOUNT=0, 
P_ALLOCATECASH = 0,
DIFF=0
FROM #FILEDATA_BSE
WHERE EXCHANGE NOT IN (SELECT EXCHANGE FROM #PRODIFF_ICCL WHERE #PRODIFF_ICCL.EXCHANGE = #FILEDATA_BSE.EXCHANGE
AND #PRODIFF_ICCL.SEGMENT = #FILEDATA_BSE.SEGMENT)

UPDATE #PRODIFF_ICCL SET DIFFAMT = #PRODIFF_ICCL.AMOUNT + AMT
FROM (SELECT EXCHANGE, SEGMENT, AMT=SUM(P_ALLOCATECASH-AMOUNT) FROM #FILEDATA_BSE
	  WHERE ORDERACTION = 'D' AND [ACCOUNT TYPE] <> 'P'
	  GROUP BY EXCHANGE, SEGMENT )A
WHERE #PRODIFF_ICCL.EXCHANGE = A.EXCHANGE
AND #PRODIFF_ICCL.SEGMENT = A.SEGMENT
AND #PRODIFF_ICCL.[ACCOUNT TYPE]='P'

DELETE FROM #FILEDATA_BSE
WHERE [ACCOUNT TYPE] = 'P'

INSERT INTO #FILEDATA_BSE
SELECT [CURRENT DATE]=REPLACE(CONVERT(VARCHAR,CONVERT(DATETIME,@RUNDATE),106),' ','-'),
EXCHANGE, SEGMENT, [SEGMENT_INDICATOR], [CM CODE], [TM CODE], [CP CODE], [CLI CODE], [ACCOUNT TYPE], AMOUNT=AMOUNT+DIFFAMT, 
FILLER1='',
FILLER2='',
FILLER3='',
FILLER4='',
FILLER5='',
FILLER6='',
ACTION='A',
ORDERACTION = 'D',
P_ALLOCATECASH = 0
FROM #PRODIFF_ICCL

INSERT INTO #FILEDATA_BSE
SELECT [CURRENT DATE]=REPLACE(CONVERT(VARCHAR,CONVERT(DATETIME,@RUNDATE),106),' ','-'),
EXCHANGE, SEGMENT, [SEGMENT_INDICATOR], [CM CODE], [TM CODE], [CP CODE], [CLI CODE], [ACCOUNT TYPE], AMOUNT=AMOUNT, 
FILLER1='',
FILLER2='',
FILLER3='',
FILLER4='',
FILLER5='',
FILLER6='',
ACTION='A',
ORDERACTION = 'U',
P_ALLOCATECASH = 0
FROM #PRODIFF_ICCL
 
SELECT * INTO #FILEDATA_ICCL 
FROM #FILEDATA_BSE
WHERE 1 = 2 

ALTER TABLE #FILEDATA_ICCL
ADD SNO INT IDENTITY(1,1)

SELECT * INTO #FILEDATA_ICCL_D
FROM #FILEDATA_BSE
WHERE 1 = 2 

ALTER TABLE #FILEDATA_ICCL_D
ADD SNO INT IDENTITY(1,1)

INSERT INTO #FILEDATA_ICCL
SELECT [CURRENT DATE], EXCHANGE, SEGMENT, [SEGMENT_INDICATOR], [CM CODE], [TM CODE], [CP CODE], [CLI CODE], [ACCOUNT TYPE], [AMOUNT], [FILLER1], [FILLER2], [FILLER3], [FILLER4], [FILLER5], [FILLER6], [ACTION], [ORDERACTION],[P_ALLOCATECASH]
FROM #FILEDATA_BSE WHERE ORDERACTION = 'D'  
ORDER BY EXCHANGE, SEGMENT, ORDERACTION, [CLI CODE] DESC

INSERT INTO #FILEDATA_ICCL_D
SELECT [CURRENT DATE], EXCHANGE, SEGMENT, [SEGMENT_INDICATOR], [CM CODE], [TM CODE], [CP CODE], [CLI CODE], [ACCOUNT TYPE], [AMOUNT], [FILLER1], [FILLER2], [FILLER3], [FILLER4], [FILLER5], [FILLER6], [ACTION], [ORDERACTION],[P_ALLOCATECASH]
FROM #FILEDATA_BSE WHERE ORDERACTION = 'U'
ORDER BY EXCHANGE, SEGMENT, ORDERACTION, [CLI CODE] ASC
IF @FLAG = 0 OR @FLAG = 2 
BEGIN 
SELECT FILENME='BSEFULLFILE_'+REPLACE(CONVERT(VARCHAR,CONVERT(DATETIME,@RUNDATE),103),'/','')+'.CSV',
[CURRENT DATE], [SEGMENT_INDICATOR], [CM CODE], [TM CODE], [CP CODE], [CLI CODE], [ACCOUNT TYPE], [AMOUNT], [FILLER1], [FILLER2], [FILLER3], [FILLER4], [FILLER5], [FILLER6], [ACTION]
FROM #FILEDATA_ICCL
UNION ALL
SELECT FILENME='BSEFULLFILE_'+REPLACE(CONVERT(VARCHAR,CONVERT(DATETIME,@RUNDATE),103),'/','')+'.CSV',
[CURRENT DATE], [SEGMENT_INDICATOR], [CM CODE], [TM CODE], [CP CODE], [CLI CODE], [ACCOUNT TYPE], [AMOUNT], [FILLER1], [FILLER2], [FILLER3], [FILLER4], [FILLER5], [FILLER6], [ACTION]
FROM #FILEDATA_ICCL_D
ORDER BY 7
END

IF @FLAG = 0 OR @FLAG = 2 
BEGIN 
SET @NOOFREC = 0 

SELECT @NOOFREC = ISNULL(COUNT(1),0) FROM #FILEDATA_ICCL
WHERE ORDERACTION = 'D'
IF @NOOFREC > 0 
BEGIN
	SET @FILEREC = 50000
	SELECT TOP 1  @MEMBERCODE = [CM CODE] FROM #FILEDATA_ICCL
	SELECT @BATCHNO = 0    
	SET @SNO = 0  
    
	SELECT @BATCHNO = ISNULL(MAX(FLDBATCHNO),0) FROM ASIANFILEBATCHNO    
	WHERE FLDFILENO = 'BSECLTCOLL'    
	AND FLDFILEDATE = @RUNDATE  
 
	WHILE @SNO < @NOOFREC
	BEGIN
		SET @BATCHNO = @BATCHNO + 1 
		SET @FILENAME = 'ICCLCOLL_' + @MEMBERCODE + '_' + REPLACE(CONVERT(VARCHAR,CONVERT(DATETIME,@RUNDATE),103),'/','') +'_'+RIGHT('0000'+CONVERT(VARCHAR,@BATCHNO),4) + '.CSV'

		SELECT FILENAME=@FILENAME,
		[CURRENT DATE], [SEGMENT_INDICATOR], [CM CODE], [TM CODE], [CP CODE], [CLI CODE], [ACCOUNT TYPE], [AMOUNT], [FILLER1], [FILLER2], [FILLER3], [FILLER4], [FILLER5], [FILLER6], [ACTION]
		FROM #FILEDATA_ICCL
		WHERE ORDERACTION = 'D'
		AND SNO > @SNO AND SNO <= @SNO + @FILEREC
		ORDER BY SNO 
		
		INSERT INTO TBL_CLIENT_COLL_FILE
		SELECT FILENAME=@FILENAME,
		[CURRENT DATE], EXCHANGE, SEGMENT, [SEGMENT_INDICATOR], [CM CODE], [TM CODE], [CP CODE], [CLI CODE], [ACCOUNT TYPE], [AMOUNT], [FILLER1], [FILLER2], [FILLER3], [FILLER4], [FILLER5], [FILLER6], [ACTION],
		@BATCHNO,'CLASSBO','',GETDATE(),'G','','',GETDATE()	
		FROM #FILEDATA_ICCL
		WHERE ORDERACTION = 'D'
		AND SNO > @SNO AND SNO <= @SNO + @FILEREC
		ORDER BY SNO 

		SET @SNO = @SNO + @FILEREC
	END

	INSERT INTO ASIANFILEBATCHNO    
	SELECT 'BSECLTCOLL', @BATCHNO, @RUNDATE, GETDATE()
END


SET @NOOFREC = 0 

SELECT @NOOFREC = ISNULL(COUNT(1),0) FROM #FILEDATA_ICCL_D
WHERE ORDERACTION = 'U'
IF @NOOFREC > 0 
BEGIN
	SET @FILEREC = 50000
	SELECT TOP 1  @MEMBERCODE = [CM CODE] FROM #FILEDATA_ICCL_D
	SELECT @BATCHNO = 0    
	SET @SNO = 0  
    
	SELECT @BATCHNO = ISNULL(MAX(FLDBATCHNO),0) FROM ASIANFILEBATCHNO    
	WHERE FLDFILENO = 'BSECLTCOLL'    
	AND FLDFILEDATE = @RUNDATE  
 
	WHILE @SNO < @NOOFREC
	BEGIN
		SET @BATCHNO = @BATCHNO + 1 
		SET @FILENAME = 'ICCLCOLL_' + @MEMBERCODE + '_' + REPLACE(CONVERT(VARCHAR,CONVERT(DATETIME,@RUNDATE),103),'/','') +'_'+RIGHT('0000'+CONVERT(VARCHAR,@BATCHNO),4) + '.CSV'

		SELECT FILENAME=@FILENAME,
		[CURRENT DATE], [SEGMENT_INDICATOR], [CM CODE], [TM CODE], [CP CODE], [CLI CODE], [ACCOUNT TYPE], [AMOUNT], [FILLER1], [FILLER2], [FILLER3], [FILLER4], [FILLER5], [FILLER6], [ACTION]
		FROM #FILEDATA_ICCL_D
		WHERE ORDERACTION = 'U'
		AND SNO > @SNO AND SNO <= @SNO + @FILEREC
		ORDER BY SNO 
		
		INSERT INTO TBL_CLIENT_COLL_FILE
		SELECT FILENAME=@FILENAME,
		[CURRENT DATE], EXCHANGE, SEGMENT, [SEGMENT_INDICATOR], [CM CODE], [TM CODE], [CP CODE], [CLI CODE], [ACCOUNT TYPE], [AMOUNT], [FILLER1], [FILLER2], [FILLER3], [FILLER4], [FILLER5], [FILLER6], [ACTION],
		@BATCHNO,'CLASSBO','',GETDATE(),'G','','',GETDATE()	
		FROM #FILEDATA_ICCL_D
		WHERE ORDERACTION = 'U'
		AND SNO > @SNO AND SNO <= @SNO + @FILEREC
		ORDER BY SNO 

		SET @SNO = @SNO + @FILEREC
	END

	INSERT INTO ASIANFILEBATCHNO    
	SELECT 'BSECLTCOLL', @BATCHNO, @RUNDATE, GETDATE()
END
END

SELECT [CURRENT DATE]=REPLACE(CONVERT(VARCHAR,CONVERT(DATETIME,@RUNDATE),106),' ','-'),
	   T.EXCHANGE, T.SEGMENT,
	   SEGMENT_INDICATOR,
	   [CM CODE]=CMCODE,
	   [TM CODE]=(CASE WHEN ACCOUNT_TYPE = 'P' THEN '' ELSE TMCODE END),
	   [CP CODE]=CP_CODE,
	   [CLI CODE]=PARTY_CODE,
	[ACCOUNT TYPE]=ACCOUNT_TYPE,
	AMOUNT=SUM(C_ALLOCATECASH), 
	FILLER1='',
	FILLER2='',
	FILLER3='',
	FILLER4='',
	FILLER5='',
	FILLER6='',
	ACTION='',
	ORDERACTION=(CASE WHEN SUM(C_ALLOCATECASH)-SUM(P_ALLOCATECASH) > 0 THEN 'U' ELSE 'D' END)
	INTO #FILEDATA_NCDX_TMP
FROM #DATA T, TBL_CMCC_DETAIL C
WHERE @RUNDATE BETWEEN FROM_DATE AND TO_DATE
AND T.EXCHANGE = C.EXCHANGE AND T.SEGMENT=C.SEGMENT
AND T.EXCHANGE IN ('NCX')
GROUP BY CMCODE, TMCODE, T.EXCHANGE, T.SEGMENT, SEGMENT_INDICATOR, PARTY_CODE, CP_CODE, ACCOUNT_TYPE
HAVING SUM(C_ALLOCATECASH) <> SUM(P_ALLOCATECASH)
ORDER BY CMCODE, TMCODE, ACTION, PARTY_CODE, SEGMENT_INDICATOR

SELECT * INTO #FILEDATA_NCDX 
FROM #FILEDATA_NCDX_TMP
WHERE 1 = 2 

ALTER TABLE #FILEDATA_NCDX
ADD SNO INT IDENTITY(1,1)

INSERT INTO #FILEDATA_NCDX
SELECT [CURRENT DATE], EXCHANGE, SEGMENT, [SEGMENT_INDICATOR], [CM CODE], [TM CODE], [CP CODE], [CLI CODE], [ACCOUNT TYPE], [AMOUNT], [FILLER1], [FILLER2], [FILLER3], [FILLER4], [FILLER5], [FILLER6], [ACTION], [ORDERACTION]
FROM #FILEDATA_NCDX_TMP
ORDER BY EXCHANGE, SEGMENT, ORDERACTION, [CLI CODE]

IF @FLAG = 0 OR @FLAG = 2 
BEGIN 
SELECT FILENME='NCDXFULLFILE_'+REPLACE(CONVERT(VARCHAR,CONVERT(DATETIME,@RUNDATE),103),'/','')+'.CSV',
[CURRENT DATE], [SEGMENT_INDICATOR], [CM CODE], [TM CODE], [CP CODE], [CLI CODE], [ACCOUNT TYPE], [AMOUNT], [FILLER1], [FILLER2], [FILLER3], [FILLER4], [FILLER5], [FILLER6], [ACTION]
FROM #FILEDATA_NCDX
ORDER BY SNO 
END

IF @FLAG = 0 OR @FLAG = 2 
BEGIN 
SET @NOOFREC = 0

SELECT @NOOFREC = ISNULL(COUNT(1),0) FROM #FILEDATA_NCDX
WHERE ORDERACTION = 'D'
IF @NOOFREC > 0 
BEGIN
	SET @FILEREC = 50000
	SELECT TOP 1  @MEMBERCODE = [CM CODE] FROM #FILEDATA_NCDX
	SELECT @BATCHNO = 0    
	SET @SNO = 0  
    
	SELECT @BATCHNO = ISNULL(MAX(FLDBATCHNO),0) FROM ASIANFILEBATCHNO    
	WHERE FLDFILENO = 'NCXCLTCOLL'    
	AND FLDFILEDATE = @RUNDATE  
 
	WHILE @SNO < @NOOFREC
	BEGIN
		SET @BATCHNO = @BATCHNO + 1 
		SET @FILENAME = 'NCCL_ALLOC_' + @MEMBERCODE + '_' + REPLACE(CONVERT(VARCHAR,CONVERT(DATETIME,@RUNDATE),103),'/','') +'_T'+RIGHT('0000'+CONVERT(VARCHAR,@BATCHNO),4) + '.CSV'

		SELECT FILENAME=@FILENAME,
		[CURRENT DATE], [SEGMENT_INDICATOR], [CM CODE], [TM CODE], [CP CODE], [CLI CODE], [ACCOUNT TYPE], [AMOUNT], [FILLER1], [FILLER2], [FILLER3], [FILLER4], [FILLER5], [FILLER6], [ACTION]
		FROM #FILEDATA_NCDX
		WHERE SNO > @SNO AND SNO <= @SNO + @FILEREC
		AND ORDERACTION = 'D'
		ORDER BY SNO 
		
		INSERT INTO TBL_CLIENT_COLL_FILE
		SELECT FILENAME=@FILENAME,
		[CURRENT DATE], EXCHANGE, SEGMENT, [SEGMENT_INDICATOR], [CM CODE], [TM CODE], [CP CODE], [CLI CODE], [ACCOUNT TYPE], [AMOUNT], [FILLER1], [FILLER2], [FILLER3], [FILLER4], [FILLER5], [FILLER6], [ACTION],
		@BATCHNO,'CLASSBO','',GETDATE(),'G','','',GETDATE()	
		FROM #FILEDATA_NCDX
		WHERE SNO > @SNO AND SNO <= @SNO + @FILEREC
		AND ORDERACTION = 'D'
		ORDER BY SNO 

		SET @SNO = @SNO + @FILEREC
	END

	INSERT INTO ASIANFILEBATCHNO    
	SELECT 'NCXCLTCOLL', @BATCHNO, @RUNDATE, GETDATE()
END

SET @NOOFREC = 0

SELECT @NOOFREC = ISNULL(COUNT(1),0) FROM #FILEDATA_NCDX
WHERE ORDERACTION = 'U'
IF @NOOFREC > 0 
BEGIN
	SET @FILEREC = 50000
	SELECT TOP 1  @MEMBERCODE = [CM CODE] FROM #FILEDATA_NCDX
	SELECT @BATCHNO = 0    
	SET @SNO = 0  
    
	SELECT @BATCHNO = ISNULL(MAX(FLDBATCHNO),0) FROM ASIANFILEBATCHNO    
	WHERE FLDFILENO = 'NCXCLTCOLL'    
	AND FLDFILEDATE = @RUNDATE  
 
	WHILE @SNO < @NOOFREC
	BEGIN
		SET @BATCHNO = @BATCHNO + 1 
		SET @FILENAME = 'NCCL_ALLOC_' + @MEMBERCODE + '_' + REPLACE(CONVERT(VARCHAR,CONVERT(DATETIME,@RUNDATE),103),'/','') +'_T'+RIGHT('0000'+CONVERT(VARCHAR,@BATCHNO),4) + '.CSV'

		SELECT FILENAME=@FILENAME,
		[CURRENT DATE], [SEGMENT_INDICATOR], [CM CODE], [TM CODE], [CP CODE], [CLI CODE], [ACCOUNT TYPE], [AMOUNT], [FILLER1], [FILLER2], [FILLER3], [FILLER4], [FILLER5], [FILLER6], [ACTION]
		FROM #FILEDATA_NCDX
		WHERE SNO > @SNO AND SNO <= @SNO + @FILEREC
		AND ORDERACTION = 'U'
		ORDER BY SNO 
		
		INSERT INTO TBL_CLIENT_COLL_FILE
		SELECT FILENAME=@FILENAME,
		[CURRENT DATE], EXCHANGE, SEGMENT, [SEGMENT_INDICATOR], [CM CODE], [TM CODE], [CP CODE], [CLI CODE], [ACCOUNT TYPE], [AMOUNT], [FILLER1], [FILLER2], [FILLER3], [FILLER4], [FILLER5], [FILLER6], [ACTION],
		@BATCHNO,'CLASSBO','',GETDATE(),'G','','',GETDATE()	
		FROM #FILEDATA_NCDX
		WHERE SNO > @SNO AND SNO <= @SNO + @FILEREC
		AND ORDERACTION = 'U'
		ORDER BY SNO 

		SET @SNO = @SNO + @FILEREC
	END

	INSERT INTO ASIANFILEBATCHNO    
	SELECT 'NCXCLTCOLL', @BATCHNO, @RUNDATE, GETDATE()
END
END

SELECT * INTO #NCDX_REPLD 
FROM TBL_CLIENT_COLL_ALLOCATE
WHERE PROCESS_DT= @RUNDATE  
AND REPLD_NONCASH + REPLD_NONCASHEQ > 0 
AND EXCHANGE = 'NCX' AND SEGMENT = 'FUTURES'
--IF @FLAG = 0 OR @FLAG = 2 
--BEGIN 
--SET @NOOFREC = 0

--ALTER TABLE #NCDX_REPLD
--ADD SNO INT IDENTITY(1,1)

--SELECT @NOOFREC = ISNULL(COUNT(1),0) FROM #NCDX_REPLD
--IF @NOOFREC > 0 
--BEGIN
--	SET @FILEREC = 50000
--	SELECT TOP 1  @MEMBERCODE = [CM CODE] FROM #NCDX_REPLD
--	SELECT @BATCHNO = 0    
--	SET @SNO = 0  
    
--	SELECT @BATCHNO = ISNULL(MAX(FLDBATCHNO),0) FROM ASIANFILEBATCHNO    
--	WHERE FLDFILENO = 'NCXCLTPLD'    
--	AND FLDFILEDATE = @RUNDATE  
 
--	WHILE @SNO < @NOOFREC
--	BEGIN
--		SET @BATCHNO = @BATCHNO + 1 
--		SET @FILENAME = 'NCCL_NCASHLMT_' + @MEMBERCODE + '_' + REPLACE(CONVERT(VARCHAR,CONVERT(DATETIME,@RUNDATE),103),'/','') +'_T'+RIGHT('0000'+CONVERT(VARCHAR,@BATCHNO),4) + '.CSV'

--		SELECT FILENAME=@FILENAME,
--		[CURRENT DATE], [SEGMENT_INDICATOR], [CM CODE], [TM CODE], [CP CODE], [CLI CODE], [ACCOUNT TYPE], [AMOUNT], [FILLER1], [FILLER2], [FILLER3], [FILLER4], [FILLER5], [FILLER6], [ACTION]
--		FROM #NCDX_REPLD
--		WHERE SNO > @SNO AND SNO <= @SNO + @FILEREC
--		ORDER BY SNO 

--		SET @SNO = @SNO + @FILEREC
--	END

--	INSERT INTO ASIANFILEBATCHNO    
--	SELECT 'NCXCLTPLD', @BATCHNO, @RUNDATE, GETDATE()
--END
--END

SELECT [CURRENT DATE]=REPLACE(CONVERT(VARCHAR,CONVERT(DATETIME,@RUNDATE),106),' ','-'),
	   T.EXCHANGE, T.SEGMENT,
	   SEGMENT_INDICATOR,
	   [CM CODE]=CMCODE,
	   [TM CODE]=(CASE WHEN ACCOUNT_TYPE = 'P' THEN '' ELSE TMCODE END),
	   [CP CODE]=CP_CODE,
	   [CLI CODE]=PARTY_CODE,
	[ACCOUNT TYPE]=ACCOUNT_TYPE,
	AMOUNT=ABS(SUM(C_ALLOCATECASH)-SUM(P_ALLOCATECASH)), 
	FILLER1='',
	FILLER2='',
	FILLER3='',
	FILLER4='',
	FILLER5='',
	FILLER6='',
	ACTION=(CASE WHEN SUM(C_ALLOCATECASH)-SUM(P_ALLOCATECASH) > 0 THEN 'A' ELSE 'D' END)
	INTO #FILEDATA_MCDX_NEW
FROM #DATA T, TBL_CMCC_DETAIL C
WHERE @RUNDATE BETWEEN FROM_DATE AND TO_DATE
AND T.EXCHANGE = C.EXCHANGE AND T.SEGMENT=C.SEGMENT
AND T.EXCHANGE IN ('MCX')
GROUP BY CMCODE, TMCODE, T.EXCHANGE, T.SEGMENT, SEGMENT_INDICATOR, PARTY_CODE, CP_CODE, ACCOUNT_TYPE
HAVING SUM(C_ALLOCATECASH) <> SUM(P_ALLOCATECASH)
ORDER BY CMCODE, TMCODE, ACTION DESC, PARTY_CODE, SEGMENT_INDICATOR

SELECT * INTO #FILEDATA_MCDX FROM #FILEDATA_MCDX_NEW WHERE 1 = 2 

ALTER TABLE #FILEDATA_MCDX
ADD SNO INT IDENTITY(1,1)

SELECT * INTO #FILEDATA_MCDX_D FROM #FILEDATA_MCDX_NEW WHERE 1 = 2 

ALTER TABLE #FILEDATA_MCDX_D
ADD SNO INT IDENTITY(1,1)

INSERT INTO #FILEDATA_MCDX
SELECT [CURRENT DATE], EXCHANGE, SEGMENT, [SEGMENT_INDICATOR], [CM CODE], [TM CODE], [CP CODE], [CLI CODE], [ACCOUNT TYPE], [AMOUNT], [FILLER1], [FILLER2], [FILLER3], [FILLER4], [FILLER5], [FILLER6], [ACTION]
FROM #FILEDATA_MCDX_NEW WHERE [ACTION] = 'D'
ORDER BY EXCHANGE, SEGMENT, ACTION DESC, [CLI CODE]
 
INSERT INTO #FILEDATA_MCDX_D
SELECT [CURRENT DATE], EXCHANGE, SEGMENT, [SEGMENT_INDICATOR], [CM CODE], [TM CODE], [CP CODE], [CLI CODE], [ACCOUNT TYPE], [AMOUNT], [FILLER1], [FILLER2], [FILLER3], [FILLER4], [FILLER5], [FILLER6], [ACTION]
FROM #FILEDATA_MCDX_NEW WHERE [ACTION] = 'A'
ORDER BY EXCHANGE, SEGMENT, ACTION DESC, [CLI CODE]
IF @FLAG = 0 OR @FLAG = 2 
BEGIN 
SET @NOOFREC = 0 

SELECT @NOOFREC = ISNULL(COUNT(1),0) FROM #FILEDATA_MCDX
WHERE [ACTION] = 'D'
IF @NOOFREC > 0 
BEGIN
	SET @FILEREC = @NOOFREC
	SELECT TOP 1  @MEMBERCODE = [CM CODE] FROM #FILEDATA_MCDX 
	SELECT @BATCHNO = 0   
	SET @SNO = 0  
    
	SELECT @BATCHNO = ISNULL(MAX(FLDBATCHNO),0) FROM ASIANFILEBATCHNO    
	WHERE FLDFILENO = 'MCXCLTCOLL'    
	AND FLDFILEDATE = @RUNDATE  
 
	WHILE @SNO < @NOOFREC
	BEGIN
		SET @BATCHNO = @BATCHNO + 1 
		SET @FILENAME = 'MCCLCOLL_' + @MEMBERCODE + '_' + REPLACE(CONVERT(VARCHAR,CONVERT(DATETIME,@RUNDATE),103),'/','') +'.'+RIGHT('000'+CONVERT(VARCHAR,@BATCHNO),3) 

		SELECT FILENAME=@FILENAME,
		[CURRENT DATE], [SEGMENT_INDICATOR], [CM CODE], [TM CODE], [CP CODE], [CLI CODE], [ACCOUNT TYPE], [AMOUNT], [FILLER1], [FILLER2], [FILLER3], [FILLER4], [FILLER5], [FILLER6], [ACTION]
		FROM #FILEDATA_MCDX
		WHERE SNO > @SNO AND SNO <= @SNO + @FILEREC
		AND [ACTION] = 'D'
		ORDER BY SNO 
		
		INSERT INTO TBL_CLIENT_COLL_FILE
		SELECT FILENAME=@FILENAME,
		[CURRENT DATE], EXCHANGE, SEGMENT, [SEGMENT_INDICATOR], [CM CODE], [TM CODE], [CP CODE], [CLI CODE], [ACCOUNT TYPE], [AMOUNT], [FILLER1], [FILLER2], [FILLER3], [FILLER4], [FILLER5], [FILLER6], [ACTION],
		@BATCHNO,'CLASSBO','',GETDATE(),'G','','',GETDATE()	
		FROM #FILEDATA_MCDX
		WHERE SNO > @SNO AND SNO <= @SNO + @FILEREC
		AND [ACTION] = 'D'
		ORDER BY SNO 

		SET @SNO = @SNO + @FILEREC
	END

	INSERT INTO ASIANFILEBATCHNO    
	SELECT 'MCXCLTCOLL', @BATCHNO, @RUNDATE, GETDATE()
END

SET @NOOFREC = 0 

SELECT @NOOFREC = ISNULL(COUNT(1),0) FROM #FILEDATA_MCDX_D
WHERE [ACTION] = 'A'
IF @NOOFREC > 0 
BEGIN
	SET @FILEREC = @NOOFREC
	SELECT TOP 1  @MEMBERCODE = [CM CODE] FROM #FILEDATA_MCDX_D 
	SELECT @BATCHNO = 0   
	SET @SNO = 0  
    
	SELECT @BATCHNO = ISNULL(MAX(FLDBATCHNO),0) FROM ASIANFILEBATCHNO    
	WHERE FLDFILENO = 'MCXCLTCOLL'    
	AND FLDFILEDATE = @RUNDATE  
 
	WHILE @SNO < @NOOFREC
	BEGIN
		SET @BATCHNO = @BATCHNO + 1 
		SET @FILENAME = 'MCCLCOLL_' + @MEMBERCODE + '_' + REPLACE(CONVERT(VARCHAR,CONVERT(DATETIME,@RUNDATE),103),'/','') +'.'+RIGHT('000'+CONVERT(VARCHAR,@BATCHNO),3) 

		SELECT FILENAME=@FILENAME,
		[CURRENT DATE], [SEGMENT_INDICATOR], [CM CODE], [TM CODE], [CP CODE], [CLI CODE], [ACCOUNT TYPE], [AMOUNT], [FILLER1], [FILLER2], [FILLER3], [FILLER4], [FILLER5], [FILLER6], [ACTION]
		FROM #FILEDATA_MCDX_D
		WHERE SNO > @SNO AND SNO <= @SNO + @FILEREC
		AND [ACTION] = 'A'
		ORDER BY SNO 
		
		INSERT INTO TBL_CLIENT_COLL_FILE
		SELECT FILENAME=@FILENAME,
		[CURRENT DATE], EXCHANGE, SEGMENT, [SEGMENT_INDICATOR], [CM CODE], [TM CODE], [CP CODE], [CLI CODE], [ACCOUNT TYPE], [AMOUNT], [FILLER1], [FILLER2], [FILLER3], [FILLER4], [FILLER5], [FILLER6], [ACTION],
		@BATCHNO,'CLASSBO','',GETDATE(),'G','','',GETDATE()	
		FROM #FILEDATA_MCDX_D
		WHERE SNO > @SNO AND SNO <= @SNO + @FILEREC
		AND [ACTION] = 'A'
		ORDER BY SNO 

		SET @SNO = @SNO + @FILEREC
	END

	INSERT INTO ASIANFILEBATCHNO    
	SELECT 'MCXCLTCOLL', @BATCHNO, @RUNDATE, GETDATE()
END
END

DROP TABLE #FILEDATA
DROP TABLE #FILEDATA_ICCL
DROP TABLE #FILEDATA_NCDX
DROP TABLE #FILEDATA_MCDX
DROP TABLE #NCDX_REPLD
DROP TABLE #DATA

GO
