-- Object: PROCEDURE dbo.C_SECURITYVALUATION_OTHER
-- Server: 10.253.33.91 | DB: MSAJAG
--------------------------------------------------


---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
create PROC [dbo].[C_SECURITYVALUATION_OTHER](  

          @EXCHANGE VARCHAR(3),    

          @SEGMENT  VARCHAR(7),    

          @SHAREDB  VARCHAR(20),    

          @VALDATE  VARCHAR(11))  

AS  

  

DECLARE @PRV_DATE VARCHAR(11)    

  

SELECT @PRV_DATE = MAX(SYSDATE) FROM CLOSING (NOLOCK)        

WHERE SYSDATE < @VALDATE    

   

   

 INSERT INTO C_VALUATION  

 SELECT @EXCHANGE,@SEGMENT,'NORMAL',@SHAREDB,SCRIP_CD,SERIES,NAV_VALUE,@VALDATE  

 FROM  

 (  

  SELECT DISTINCT C.SCRIP_CD, C.SERIES,ISIN  

  FROM   

  (  

   SELECT PARTY_CODE,SCRIP_CD,SERIES, ISIN, QTY=SUM(CASE WHEN DRCR='D' THEN QTY ELSE -QTY END)  

   FROM MSAJAG.DBO.C_SECURITIESMST S WHERE PARTY_CODE <> 'BROKER'   

   AND EFFDATE <= @VALDATE + ' 23:59:59'   

   AND SERIES = 'MF'  

   AND S.EXCHANGE = @EXCHANGE  AND S.SEGMENT = @SEGMENT  

   GROUP BY PARTY_CODE,SCRIP_CD,SERIES,ISIN  

   HAVING SUM(CASE WHEN DRCR='D' THEN QTY ELSE -QTY END) <> 0  

  ) C  

 ) SEC, MFSS_NAV01 MFSS_NAV01  

 WHERE MFSS_NAV01.NAV_DATE BETWEEN @PRV_DATE AND  @PRV_DATE + ' 23:59'  

 AND MFSS_NAV01.ISIN = SEC.ISIN  

  





INSERT INTO C_VALUATION  

 SELECT @EXCHANGE,@SEGMENT,'NORMAL',SHAREDB=SEC.ISIN,SCRIP_CD,SERIES,NAV_VALUE=ISNULL(NAV_VALUE,0),@VALDATE  

 FROM  

 (  

  SELECT DISTINCT C.SCRIP_CD, C.SERIES,ISIN  

  FROM   

  (  

   SELECT PARTY_CODE,SCRIP_CD,SERIES, ISIN, QTY=SUM(CASE WHEN DRCR='D' THEN QTY ELSE -QTY END)  

   FROM MSAJAG.DBO.C_SECURITIESMST S WHERE PARTY_CODE <> 'BROKER'   

   AND EFFDATE <= @VALDATE + ' 23:59:59'   

   AND SERIES = 'MF'  

   AND S.EXCHANGE = @EXCHANGE  AND S.SEGMENT = @SEGMENT  

   GROUP BY PARTY_CODE,SCRIP_CD,SERIES,ISIN  

   HAVING SUM(CASE WHEN DRCR='D' THEN QTY ELSE -QTY END) <> 0  

  ) C  

 ) SEC

 LEFT OUTER JOIN

 MFSS_NAV01 MFSS_NAV01  

 ON ( MFSS_NAV01.NAV_DATE BETWEEN @PRV_DATE AND  @PRV_DATE + ' 23:59'  

	AND MFSS_NAV01.ISIN = SEC.ISIN )

	
/*
	

UPDATE C_VALUATION SET CL_RATE = NAV_VALUE

FROM MFSS_NAV MFSS_NAV  

WHERE MFSS_NAV.NAV_DATE BETWEEN @PRV_DATE AND  @PRV_DATE + ' 23:59'  

AND MFSS_NAV.ISIN = C_VALUATION.SHAREDB

AND SERIES = 'MF'

AND C_VALUATION.CL_RATE = 0 

AND SYSDATE BETWEEN @VALDATE AND  @VALDATE + ' 23:59'

*/

UPDATE C_VALUATION SET SHAREDB = @SHAREDB

WHERE SERIES = 'MF'

AND SYSDATE BETWEEN @VALDATE AND  @VALDATE + ' 23:59'

GO
