-- Object: PROCEDURE dbo.PROC_COLL_ALLOC_RES_BKP_20220803
-- Server: 10.253.33.91 | DB: MSAJAG
--------------------------------------------------


CREATE PROC [dbo].[PROC_COLL_ALLOC_RES_BKP_20220803] (@TDATE VARCHAR(10), @FILEFOR VARCHAR(20), @FILETYPE VARCHAR(50), @PROGID VARCHAR(50), @UNAME VARCHAR(50),@FILENAME VARCHAR(100) = '')

AS

-- EXEC PROC_COLL_ALLOC_RES '09/04/2018', '', '', '1234567890', ''
DECLARE @RECCNT INT,
		@FILEDATE	DATETIME,
		@EXCHANGE	VARCHAR(3),
		@SEGMENT	VARCHAR(7),
		@ORG_FILENAME VARCHAR(100),
		@BATCHNO	INT

SELECT UPD_FILENAME,FILEDATE,EXCHANGE,SEGMENT,SEGMENT_INDICATOR,CM_CODE,TM_CODE,CP_CODE,CLI_CODE,ACCOUNT_TYPE,
	   AMOUNT,FILLER1,FILLER2,FILLER3,FILLER4,FILLER5,FILLER6,ACTION_TYPE,BATCHNO,SOURCE_FROM,UPLOAD_BY,
	   UPLOAD_ON,BATCH_STATUS,RESPONSE_CODE,RESPONSE_BY,RESPONSE_ON
INTO #TBL_CLIENT_COLL_FILE 
FROM TBL_CLIENT_COLL_FILE
WHERE 1 = 2 

SET @EXCHANGE = ''
SET @BATCHNO = 0

SET @ORG_FILENAME = REVERSE(.DBO.PIECE(REVERSE(@FILENAME),'\',1))

IF @ORG_FILENAME LIKE '%ICCL%'
BEGIN
	SET @EXCHANGE = 'BSE'
	SET @ORG_FILENAME = RIGHT(@ORG_FILENAME,LEN(@ORG_FILENAME)-4)
	SET @BATCHNO = LEFT(RIGHT(@ORG_FILENAME,8),4)
END

IF @ORG_FILENAME LIKE '%NCCL%'
BEGIN
	SET @EXCHANGE = 'NCX'
	SET @ORG_FILENAME = REPLACE(@ORG_FILENAME,'_S','_T')
	SET @BATCHNO = LEFT(RIGHT(@ORG_FILENAME,8),4)
END

IF @ORG_FILENAME LIKE '%MCCL%'
BEGIN
	SET @EXCHANGE = 'MCX'
	SET @ORG_FILENAME = REPLACE(@ORG_FILENAME,'.E','.')
	SET @BATCHNO = RIGHT(@ORG_FILENAME,3)
END

IF @EXCHANGE = ''
BEGIN
	SET @EXCHANGE = 'NSE'
	SET @ORG_FILENAME = REPLACE(@ORG_FILENAME,'.S','.T')
	SET @BATCHNO = RIGHT(@ORG_FILENAME,4)
END

INSERT INTO #TBL_CLIENT_COLL_FILE   
SELECT @ORG_FILENAME,.DBO.PIECE(FILE_DATA,',',1),@EXCHANGE,
		.DBO.PIECE(FILE_DATA,',',2), .DBO.PIECE(FILE_DATA,',',2),
		.DBO.PIECE(FILE_DATA,',',3), .DBO.PIECE(FILE_DATA,',',4),
		.DBO.PIECE(FILE_DATA,',',5), .DBO.PIECE(FILE_DATA,',',6),
		.DBO.PIECE(FILE_DATA,',',7), .DBO.PIECE(FILE_DATA,',',8),
		.DBO.PIECE(FILE_DATA,',',9), .DBO.PIECE(FILE_DATA,',',10),
		.DBO.PIECE(FILE_DATA,',',11), .DBO.PIECE(FILE_DATA,',',12),
		.DBO.PIECE(FILE_DATA,',',13), .DBO.PIECE(FILE_DATA,',',14),
		.DBO.PIECE(FILE_DATA,',',15), 
		@BATCHNO,'FILE','',GETDATE(),
		(CASE WHEN LEN(LTRIM(RTRIM(.DBO.PIECE(FILE_DATA,',',16)))) > 0 THEN 'F' ELSE 'D' END),
		.DBO.PIECE(FILE_DATA,',',16),
		RESPONSE_BY = @UNAME, RESPONSE_ON = GETDATE()
FROM FILEDATA
WHERE PROGID = @PROGID AND ISNULL(.DBO.PIECE(FILE_DATA,',',1),'')  = REPLACE(CONVERT(VARCHAR,CONVERT(DATETIME,@TDATE,103),106),' ','-')

SELECT @RECCNT = 0 
SELECT @RECCNT = ISNULL(COUNT(1),0) FROM #TBL_CLIENT_COLL_FILE

IF @RECCNT > 0 
BEGIN 
	UPDATE #TBL_CLIENT_COLL_FILE SET SEGMENT = D.SEGMENT
	FROM TBL_CMCC_DETAIL D
	WHERE #TBL_CLIENT_COLL_FILE.EXCHANGE = D.EXCHANGE
	AND SEGMENT_INDICATOR = SEG_TYPE
	 
	UPDATE TBL_CLIENT_COLL_FILE SET 
	BATCH_STATUS = D.BATCH_STATUS,
	RESPONSE_CODE = D.RESPONSE_CODE,
	RESPONSE_BY = D.RESPONSE_BY,
	RESPONSE_ON = D.RESPONSE_ON
	FROM #TBL_CLIENT_COLL_FILE D
	WHERE TBL_CLIENT_COLL_FILE.FILEDATE = CONVERT(DATETIME,@TDATE,103)
	AND TBL_CLIENT_COLL_FILE.UPD_FILENAME = @ORG_FILENAME
	AND TBL_CLIENT_COLL_FILE.EXCHANGE = D.EXCHANGE	
	AND TBL_CLIENT_COLL_FILE.SEGMENT = D.SEGMENT 
	AND TBL_CLIENT_COLL_FILE.SEGMENT_INDICATOR = D.SEGMENT_INDICATOR	
	AND TBL_CLIENT_COLL_FILE.CM_CODE = D.CM_CODE	
	AND TBL_CLIENT_COLL_FILE.TM_CODE = D.TM_CODE	
	AND TBL_CLIENT_COLL_FILE.CP_CODE = D.CP_CODE	
	AND TBL_CLIENT_COLL_FILE.CLI_CODE = D.CLI_CODE	
	AND TBL_CLIENT_COLL_FILE.ACCOUNT_TYPE = D.ACCOUNT_TYPE
	AND TBL_CLIENT_COLL_FILE.BATCHNO = D.BATCHNO

	INSERT INTO TBL_CLIENT_COLL_FILE
	SELECT * FROM #TBL_CLIENT_COLL_FILE
	WHERE NOT EXISTS (SELECT CLI_CODE FROM TBL_CLIENT_COLL_FILE D
	WHERE D.FILEDATE = CONVERT(DATETIME,@TDATE,103)
	AND #TBL_CLIENT_COLL_FILE.UPD_FILENAME = @ORG_FILENAME
	AND #TBL_CLIENT_COLL_FILE.EXCHANGE = D.EXCHANGE	
	AND #TBL_CLIENT_COLL_FILE.SEGMENT = D.SEGMENT 
	AND #TBL_CLIENT_COLL_FILE.SEGMENT_INDICATOR = D.SEGMENT_INDICATOR	
	AND #TBL_CLIENT_COLL_FILE.CM_CODE = D.CM_CODE	
	AND #TBL_CLIENT_COLL_FILE.TM_CODE = D.TM_CODE	
	AND #TBL_CLIENT_COLL_FILE.CP_CODE = D.CP_CODE	
	AND #TBL_CLIENT_COLL_FILE.CLI_CODE = D.CLI_CODE	
	AND #TBL_CLIENT_COLL_FILE.ACCOUNT_TYPE = D.ACCOUNT_TYPE
	AND #TBL_CLIENT_COLL_FILE.BATCHNO = D.BATCHNO)
END
 
SELECT STRMSGCODE = 1, STRMSG = CONVERT(VARCHAR,@RECCNT) + ' RECORD(S) UPLOADED.'

GO
