-- Object: PROCEDURE dbo.POP_CALC_GST_INVOICE
-- Server: 10.253.33.91 | DB: MSAJAG
--------------------------------------------------





CREATE PROC [dbo].[POP_CALC_GST_INVOICE] 
(
	@FORTHEMONTH	VARCHAR(8)
)
AS

DECLARE @FORTHEDAY	VARCHAR(11),
		@FROMDATE	VARCHAR(11),
		@TODATE		VARCHAR(11)

SET @FROMDATE = LEFT(CONVERT(DATETIME,@FORTHEMONTH),11)

SET @TODATE = LEFT(DATEADD(M,1,CONVERT(DATETIME,@FORTHEMONTH))-1,11)

TRUNCATE TABLE TBL_GST_INVOICE_TMP

SET @FORTHEDAY = @FROMDATE
WHILE CONVERT(DATETIME,@FORTHEDAY) <= CONVERT(DATETIME,@TODATE)
BEGIN
	EXEC CALC_GST_INVOICE @FORTHEDAY

	SET @FORTHEDAY = CONVERT(DATETIME,@FORTHEDAY) + 1
END

CREATE TABLE #INVNOGENSERIES
(
	PARTY_CODE		VARCHAR(10),
	INVOICE_SERIES	VARCHAR(10),
	INV_NO			VARCHAR(16),
	STATECODE		VARCHAR(2),
	LOCATIONCODE	VARCHAR(20),
	INVOICE_CATEGORY	VARCHAR(100),
	RECORDFOR		VARCHAR(100),
	INVOICE_TYPE	VARCHAR(100),
	INV_SRNO		NUMERIC(18,0),
	SUBRECORDFOR    VARCHAR(100),
	REV_INT_REF_NO	VARCHAR(100)
)

CREATE TABLE #INVNOGEN
(
	SNO				INT	IDENTITY(1,1),
	PARTY_CODE		VARCHAR(10),
	STATECODE		VARCHAR(2),
	LOCATIONCODE	VARCHAR(20),
	INVOICE_CATEGORY	VARCHAR(100),
	RECORDFOR		VARCHAR(100),
	INVOICE_TYPE	VARCHAR(100),
	SUBRECORDFOR	VARCHAR(100),
	REV_INT_REF_NO	VARCHAR(100)
)

CREATE NONCLUSTERED INDEX [IX_Type] ON [dbo].[#INVNOGEN]
(
	[RECORDFOR] ASC,
	[INVOICE_TYPE] ASC,
	[INVOICE_CATEGORY] ASC,
	LOCATIONCODE ASC,
	STATECODE ASC,
	[SUBRECORDFOR] ASC
)


CREATE NONCLUSTERED INDEX [IX_party] ON [dbo].[#INVNOGEN]
(
	party_CODE
)


SELECT * INTO #TBL_GST_INVOICE FROM TBL_GST_INVOICE 
WHERE INVOICE_DATE BETWEEN @FROMDATE AND @TODATE

CREATE  CLUSTERED INDEX IX_1 on #TBL_GST_INVOICE (INVOICE_DATE,INV_NO)

INSERT INTO #INVNOGENSERIES
SELECT DISTINCT PARTY_CODE, INVOICE_SERIES, G.INV_NO,
				I.STATECODE, LOCATIONCODE,
				I.INVOICE_CATEGORY, I.RECORDFOR,
				I.INVOICE_TYPE,I.SRNO, SUBRECORDFOR,
				REV_INT_REF_NO
FROM #TBL_GST_INVOICE G, TBL_INVOICE_NO I
WHERE G.INV_NO <> '' 
AND INVOICE_DATE BETWEEN INV_FROM_DATE AND INV_TO_DATE
AND INVOICE_DATE BETWEEN @FROMDATE AND @TODATE
AND G.STATE_CODE = (CASE WHEN I.STATECODE = '' THEN G.STATE_CODE ELSE I.STATECODE END)
AND LOCATION_CODE = (CASE WHEN LOCATIONCODE = '' THEN LOCATION_CODE ELSE LOCATIONCODE END)
AND G.INVOICE_CATEGORY = (CASE WHEN I.INVOICE_CATEGORY = '' THEN G.INVOICE_CATEGORY ELSE I.INVOICE_CATEGORY END)
AND G.RECORDFOR = (CASE WHEN I.RECORDFOR = '' THEN G.RECORDFOR ELSE I.RECORDFOR END)
AND G.INVOICE_TYPE = (CASE WHEN I.INVOICE_TYPE = '' THEN G.INVOICE_TYPE ELSE I.INVOICE_TYPE END)
ORDER BY PARTY_CODE

UPDATE TBL_GST_INVOICE_TMP SET REV_INT_REF_NO = R.INV_NO 
FROM ACCOUNT.DBO.GST_REVERSAL_ENTRY_DETAILS R
WHERE INVOICE_DATE = CONVERT(DATETIME,VDT,103)
AND TBL_GST_INVOICE_TMP.PARTY_CODE = R.PARTY_CODE
AND INT_REF_NO = 'NSE_CAPITAL_' + CONVERT(VARCHAR,VNO) + '_' + CONVERT(VARCHAR,VTYP) + '_' + CONVERT(VARCHAR,BOOKTYPE)

UPDATE TBL_GST_INVOICE_TMP SET INV_NO = I.INV_NO
FROM #INVNOGENSERIES I
WHERE TBL_GST_INVOICE_TMP.PARTY_CODE = I.PARTY_CODE
AND TBL_GST_INVOICE_TMP.STATE_CODE = (CASE WHEN I.STATECODE = '' THEN TBL_GST_INVOICE_TMP.STATE_CODE ELSE I.STATECODE END)
AND TBL_GST_INVOICE_TMP.LOCATION_CODE = (CASE WHEN LOCATIONCODE = '' THEN TBL_GST_INVOICE_TMP.LOCATION_CODE ELSE LOCATIONCODE END)
AND TBL_GST_INVOICE_TMP.INVOICE_CATEGORY = (CASE WHEN I.INVOICE_CATEGORY = '' THEN TBL_GST_INVOICE_TMP.INVOICE_CATEGORY ELSE I.INVOICE_CATEGORY END)
AND TBL_GST_INVOICE_TMP.RECORDFOR = (CASE WHEN I.RECORDFOR = '' THEN TBL_GST_INVOICE_TMP.RECORDFOR ELSE I.RECORDFOR END)
AND TBL_GST_INVOICE_TMP.INVOICE_TYPE = (CASE WHEN I.INVOICE_TYPE = '' THEN TBL_GST_INVOICE_TMP.INVOICE_TYPE ELSE I.INVOICE_TYPE END)
AND TBL_GST_INVOICE_TMP.SUBRECORDFOR = I.SUBRECORDFOR
AND TBL_GST_INVOICE_TMP.REV_INT_REF_NO = I.REV_INT_REF_NO


INSERT  INTO TBL_GST_INVOICE_LOG
SELECT INVOICE_DATE,EXCHANGE,SEGMENT,RECORDFOR,SUBRECORDFOR,INV_DESC,SETT_NO,SETT_TYPE,PARTY_CODE,CONTRACTNO,INT_REF_NO,
TAXABLE_AMT,TAX_AMT,INVOICE_TYPE,INVOICE_SUBTYPE,INVOICE_CATEGORY,REV_INT_REF_NO,LOCATION_CODE,SOURCESTATE,TARGETSTATE,
STATE_CODE,INV_NO,SACCODE,SAC_DESC,BRANCH_CODE,IGST_RATE,IGST_AMOUNT,CGST_RATE,CGST_AMOUNT,SGST_RATE,SGST_AMOUNT,LOGDATE=GETDATE(),TOTCHRG
FROM #TBL_GST_INVOICE
WHERE #TBL_GST_INVOICE.INV_NO NOT IN (SELECT DISTINCT INV_NO FROM TBL_GST_INVOICE_TMP )
										 -- WHERE #TBL_GST_INVOICE.INV_NO = TBL_GST_INVOICE_TMP.INV_NO )
					

TRUNCATE TABLE #INVNOGENSERIES

INSERT INTO #INVNOGENSERIES
SELECT DISTINCT PARTY_CODE, INVOICE_SERIES, I.INV_NO,
I.STATECODE, LOCATIONCODE, I.INVOICE_CATEGORY, I.RECORDFOR, I.INVOICE_TYPE,
INV_SRNO = I.SRNO, SUBRECORDFOR, REV_INT_REF_NO
FROM TBL_GST_INVOICE_TMP G, TBL_INVOICE_NO I
WHERE G.INV_NO = '' 
AND INVOICE_DATE BETWEEN INV_FROM_DATE AND INV_TO_DATE
AND INVOICE_DATE BETWEEN @FROMDATE AND @TODATE
AND G.STATE_CODE = (CASE WHEN I.STATECODE = '' THEN G.STATE_CODE ELSE I.STATECODE END)
AND LOCATION_CODE = (CASE WHEN LOCATIONCODE = '' THEN LOCATION_CODE ELSE LOCATIONCODE END)
AND G.INVOICE_CATEGORY = (CASE WHEN I.INVOICE_CATEGORY = '' THEN G.INVOICE_CATEGORY ELSE I.INVOICE_CATEGORY END)
AND G.RECORDFOR = (CASE WHEN I.RECORDFOR = '' THEN G.RECORDFOR ELSE I.RECORDFOR END)
AND G.INVOICE_TYPE = (CASE WHEN I.INVOICE_TYPE = '' THEN G.INVOICE_TYPE ELSE I.INVOICE_TYPE END)
ORDER BY PARTY_CODE, INVOICE_SERIES

DECLARE @INVOICE_SERIES	VARCHAR(10),
		@INV_NO			NUMERIC(18,0),
		@INV_SRNO		NUMERIC(18,0),
		@INV_CURSOR		CURSOR

SET @INV_CURSOR = CURSOR FOR 
	SELECT DISTINCT INVOICE_SERIES, INV_NO, INV_SRNO FROM #INVNOGENSERIES
OPEN @INV_CURSOR
FETCH NEXT FROM @INV_CURSOR INTO @INVOICE_SERIES, @INV_NO, @INV_SRNO
WHILE @@FETCH_STATUS = 0
BEGIN
	TRUNCATE TABLE #INVNOGEN
	INSERT INTO #INVNOGEN
	SELECT PARTY_CODE, STATECODE, LOCATIONCODE, INVOICE_CATEGORY, RECORDFOR, INVOICE_TYPE, SUBRECORDFOR, REV_INT_REF_NO 
	FROM #INVNOGENSERIES
	WHERE INVOICE_SERIES = @INVOICE_SERIES
	ORDER BY PARTY_CODE

	UPDATE  TBL_GST_INVOICE_TMP SET INV_NO = @INVOICE_SERIES + RIGHT('00000000' + CONVERT(VARCHAR,(I.SNO + @INV_NO)), 7)
	FROM #INVNOGEN I
	WHERE TBL_GST_INVOICE_TMP.PARTY_CODE = I.PARTY_CODE
	AND TBL_GST_INVOICE_TMP.INV_NO = ''
	AND INVOICE_DATE BETWEEN @FROMDATE AND @TODATE
	AND TBL_GST_INVOICE_TMP.STATE_CODE = (CASE WHEN I.STATECODE = '' THEN TBL_GST_INVOICE_TMP.STATE_CODE ELSE I.STATECODE END)
	AND TBL_GST_INVOICE_TMP.LOCATION_CODE = (CASE WHEN LOCATIONCODE = '' THEN LOCATION_CODE ELSE LOCATIONCODE END)
	AND TBL_GST_INVOICE_TMP.INVOICE_CATEGORY = (CASE WHEN I.INVOICE_CATEGORY = '' THEN TBL_GST_INVOICE_TMP.INVOICE_CATEGORY ELSE I.INVOICE_CATEGORY END)
	AND TBL_GST_INVOICE_TMP.RECORDFOR = (CASE WHEN I.RECORDFOR = '' THEN TBL_GST_INVOICE_TMP.RECORDFOR ELSE I.RECORDFOR END)
	AND TBL_GST_INVOICE_TMP.INVOICE_TYPE = (CASE WHEN I.INVOICE_TYPE = '' THEN TBL_GST_INVOICE_TMP.INVOICE_TYPE ELSE I.INVOICE_TYPE END)
	AND TBL_GST_INVOICE_TMP.SUBRECORDFOR = I.SUBRECORDFOR
	AND TBL_GST_INVOICE_TMP.REV_INT_REF_NO = I.REV_INT_REF_NO

	SELECT @INV_NO = @INV_NO + ISNULL(MAX(SNO),0) FROM #INVNOGEN

	UPDATE TBL_INVOICE_NO SET INV_NO = @INV_NO
	WHERE SRNO = @INV_SRNO

	FETCH NEXT FROM @INV_CURSOR INTO @INVOICE_SERIES, @INV_NO, @INV_SRNO
END
CLOSE @INV_CURSOR
DEALLOCATE @INV_CURSOR

/*
INSERT INTO TBL_INVOICE_NO
SELECT DISTINCT INV_FROM_DATE='APR  1 2017',INV_TO_DATE='MAR 31 2018 23:59:59',STATE_CODE,LOCATION_CODE,
		INVOICE_CATEGORY,INV_NO=0,RECORDFOR,INVOICE_TYPE,
		INVOICE_SERIES=STATE_CODE+RIGHT(LOCATION_CODE,2)+'/'+LEFT(RECORDFOR,1)+LEFT(INVOICE_CATEGORY,1)+'/'+LEFT(INVOICE_TYPE,1)
FROM TBL_GST_INVOICE_TMP */

UPDATE TBL_GST_INVOICE_TMP SET SACCODE = T.SACCODE, SAC_DESC = [DESC]
FROM ACCOUNT.DBO.TBL_SAC_CODE_UPDATE T
WHERE CLTCODE = SUBRECORDFOR
AND INVOICE_DATE BETWEEN EFF_FROM_DATE AND EFF_TO_DATE 

DELETE FROM TBL_GST_INVOICE
WHERE INVOICE_DATE BETWEEN @FROMDATE AND @TODATE + ' 23:59:59'

INSERT INTO TBL_GST_INVOICE 
SELECT * FROM TBL_GST_INVOICE_TMP

GO
