-- Object: PROCEDURE dbo.PROC_CLIENT_COLLATREAL_ALLOC_LED_BKUP_04JUL2022
-- Server: 10.253.33.91 | DB: MSAJAG
--------------------------------------------------

CREATE PROC [dbo].[PROC_CLIENT_COLLATREAL_ALLOC_LED_BKUP_04JUL2022] 
(
	@RUNDATE VARCHAR(11)
)	
AS

--DECLARE @RUNDATE VARCHAR(11)
--SET @RUNDATE ='2022-05-10'

DECLARE 
		@EXCHANGE	VARCHAR(3),
		@SEGMENT	VARCHAR(7),
		@NEWEXCHANGE	VARCHAR(3),
		@NEWSEGMENT	VARCHAR(7),
		@ALLOCCUR	CURSOR,
		@SETCUR	CURSOR,
		@ADJ_AMOUNT NUMERIC(18,3),
		@EXCESS_AMOUNT	NUMERIC(18,3),
		@CL_AMOUNT NUMERIC(18,3),
		@PARTYCUR	CURSOR,
		@PARTY_CODE	VARCHAR(20), 
		@CLEARING_PAN VARCHAR(20), 	
		@TRADING_PAN VARCHAR(20), 
		@CP_CODE VARCHAR(20), 
		@CP_PAN VARCHAR(20), 
		@CLIENT_PAN VARCHAR(20)

SET NOCOUNT ON 
		
SELECT EDT_LEDGER=SUM(CASE WHEN EDT_LEDGER > 0 THEN EDT_LEDGER ELSE 0 END), EXCHANGE, SEGMENT,
FD_AMOUNT=CONVERT(NUMERIC(18,2),0),
BG_AMOUNT=CONVERT(NUMERIC(18,2),0),
CASH_AMOUNT=CONVERT(NUMERIC(18,2),0),
EXCESSAMT=SUM(CASE WHEN EDT_LEDGER > 0 AND (EDT_LEDGER+LIEU_EPI_LEDGER_CLTM+POOL_ACCOUNT_CLTM+
					APPROVED_SEC_CASH_REC_TM+APPROVED_SEC_NONCASH_REC_TM+NONAPPROVED_SEC_REC_TM-UPFRONT_MARGIN) > 0  
				THEN (CASE WHEN (EDT_LEDGER+LIEU_EPI_LEDGER_CLTM+POOL_ACCOUNT_CLTM+
					APPROVED_SEC_CASH_REC_TM+APPROVED_SEC_NONCASH_REC_TM+NONAPPROVED_SEC_REC_TM-UPFRONT_MARGIN) < EDT_LEDGER 
				THEN (EDT_LEDGER+LIEU_EPI_LEDGER_CLTM+POOL_ACCOUNT_CLTM+
					APPROVED_SEC_CASH_REC_TM+APPROVED_SEC_NONCASH_REC_TM+NONAPPROVED_SEC_REC_TM-UPFRONT_MARGIN) 
				ELSE EDT_LEDGER END)
		ELSE 0 END) INTO #ALLOC_ADJ
FROM CLIENT_COLLATERAL_REPORTING_DETAILS_TODAY WITH(NOLOCK)
WHERE PROCESS_DT= @RUNDATE
AND ACCOUNT_TYPE = 'C'  AND EDT_LEDGER > 0 
GROUP BY EXCHANGE, SEGMENT

SELECT PARTY_CODE, TRADING_PAN, CLIENT_PAN,
		EXCESSAMT=(CASE WHEN EDT_LEDGER > 0 AND (EDT_LEDGER+LIEU_EPI_LEDGER_CLTM+POOL_ACCOUNT_CLTM+
					APPROVED_SEC_CASH_REC_TM+APPROVED_SEC_NONCASH_REC_TM+NONAPPROVED_SEC_REC_TM-UPFRONT_MARGIN) > 0  
				THEN (CASE WHEN (EDT_LEDGER+LIEU_EPI_LEDGER_CLTM+POOL_ACCOUNT_CLTM+
					APPROVED_SEC_CASH_REC_TM+APPROVED_SEC_NONCASH_REC_TM+NONAPPROVED_SEC_REC_TM-UPFRONT_MARGIN) < EDT_LEDGER 
				THEN (EDT_LEDGER+LIEU_EPI_LEDGER_CLTM+POOL_ACCOUNT_CLTM+
					APPROVED_SEC_CASH_REC_TM+APPROVED_SEC_NONCASH_REC_TM+NONAPPROVED_SEC_REC_TM-UPFRONT_MARGIN) 
				ELSE EDT_LEDGER END)
		ELSE 0 END)  
		into #partydata
		FROM CLIENT_COLLATERAL_REPORTING_DETAILS_TODAY WITH(NOLOCK)
		WHERE PROCESS_DT=@RUNDATE
		AND ACCOUNT_TYPE = 'C'AND EDT_LEDGER > 0 
		and 1= 2 

CREATE INDEX #CL_1 ON #PARTYDATA (PARTY_CODE, TRADING_PAN, CLIENT_PAN,EXCESSAMT)

UPDATE #ALLOC_ADJ 
SET FD_AMOUNT = FDAMOUNT, BG_AMOUNT = BGAMOUNT 
FROM TBL_CMCC_DATA C WITH(NOLOCK)
WHERE TRANSDATE=@RUNDATE
AND #ALLOC_ADJ.EXCHANGE = C.EXCHANGE 
AND #ALLOC_ADJ.SEGMENT = C.SEGMENT 
AND ACCOUNT_TYPE='C' AND ALLOC_LEVEL='TM'

UPDATE #ALLOC_ADJ SET CASH_AMOUNT = CASHAMOUNT
FROM TBL_CMCC_DATA C WITH(NOLOCK)
WHERE TRANSDATE=@RUNDATE
AND #ALLOC_ADJ.EXCHANGE = C.EXCHANGE 
AND #ALLOC_ADJ.SEGMENT = C.SEGMENT 
AND ACCOUNT_TYPE='C' AND ALLOC_LEVEL<>'TM'

SELECT * INTO #ALLOC_CASH FROM #ALLOC_ADJ
WHERE 1 = 2 

SELECT EXCHANGE, SEGMENT, ADJUST=ABS((CASE WHEN EDT_LEDGER-FD_AMOUNT-BG_AMOUNT-CASH_AMOUNT > EXCESSAMT 
						THEN EXCESSAMT ELSE EDT_LEDGER-FD_AMOUNT-BG_AMOUNT-CASH_AMOUNT END))
						into #ADJ_BANKBAL
FROM #ALLOC_ADJ
WHERE  (CASE WHEN EDT_LEDGER-FD_AMOUNT-BG_AMOUNT-CASH_AMOUNT > EXCESSAMT 
						THEN EXCESSAMT ELSE EDT_LEDGER-FD_AMOUNT-BG_AMOUNT-CASH_AMOUNT END) < 0  
ORDER BY 3 DESC
 
SET @SETCUR = CURSOR FOR 
SELECT * FROM #ADJ_BANKBAL
OPEN @SETCUR 
FETCH NEXT FROM @SETCUR INTO @EXCHANGE, @SEGMENT, @ADJ_AMOUNT
WHILE @@FETCH_STATUS = 0
BEGIN 
	TRUNCATE TABLE #ALLOC_CASH

	INSERT INTO #ALLOC_CASH 
	SELECT EDT_LEDGER=SUM(CASE WHEN EDT_LEDGER > 0 THEN EDT_LEDGER ELSE 0 END), EXCHANGE, SEGMENT,
	FD_AMOUNT=CONVERT(NUMERIC(18,2),0),
	BG_AMOUNT=CONVERT(NUMERIC(18,2),0),
	CASH_AMOUNT=CONVERT(NUMERIC(18,2),0),
	EXCESSAMT=SUM(CASE WHEN EDT_LEDGER > 0 AND (EDT_LEDGER+LIEU_EPI_LEDGER_CLTM+POOL_ACCOUNT_CLTM+
					APPROVED_SEC_CASH_REC_TM+APPROVED_SEC_NONCASH_REC_TM+NONAPPROVED_SEC_REC_TM-UPFRONT_MARGIN) > 0  
				THEN (CASE WHEN (EDT_LEDGER+LIEU_EPI_LEDGER_CLTM+POOL_ACCOUNT_CLTM+
					APPROVED_SEC_CASH_REC_TM+APPROVED_SEC_NONCASH_REC_TM+NONAPPROVED_SEC_REC_TM-UPFRONT_MARGIN) < EDT_LEDGER 
				THEN (EDT_LEDGER+LIEU_EPI_LEDGER_CLTM+POOL_ACCOUNT_CLTM+
					APPROVED_SEC_CASH_REC_TM+APPROVED_SEC_NONCASH_REC_TM+NONAPPROVED_SEC_REC_TM-UPFRONT_MARGIN) 
				ELSE EDT_LEDGER END)
		ELSE 0 END)
	FROM CLIENT_COLLATERAL_REPORTING_DETAILS_TODAY
	WHERE PROCESS_DT= @RUNDATE
	AND ACCOUNT_TYPE = 'C' AND EDT_LEDGER > 0 
	GROUP BY EXCHANGE, SEGMENT
	

	UPDATE #ALLOC_CASH SET FD_AMOUNT = FDAMOUNT, BG_AMOUNT = BGAMOUNT 
	FROM TBL_CMCC_DATA C WITH(NOLOCK)
	WHERE TRANSDATE=@RUNDATE
	AND #ALLOC_CASH.EXCHANGE = C.EXCHANGE 
	AND #ALLOC_CASH.SEGMENT = C.SEGMENT 
	AND ACCOUNT_TYPE='C' AND ALLOC_LEVEL='TM'

	UPDATE #ALLOC_CASH SET CASH_AMOUNT = CASHAMOUNT
	FROM TBL_CMCC_DATA C WITH(NOLOCK)
	WHERE TRANSDATE=@RUNDATE
	AND #ALLOC_CASH.EXCHANGE = C.EXCHANGE 
	AND #ALLOC_CASH.SEGMENT = C.SEGMENT 
	AND ACCOUNT_TYPE='C' AND ALLOC_LEVEL<>'TM'
	 
	SET @ALLOCCUR = CURSOR FOR 
	SELECT EXCHANGE, SEGMENT, ADJUST=(CASE WHEN EDT_LEDGER-FD_AMOUNT-BG_AMOUNT-CASH_AMOUNT > EXCESSAMT 
						   THEN EXCESSAMT ELSE EDT_LEDGER-FD_AMOUNT-BG_AMOUNT-CASH_AMOUNT END)
	FROM #ALLOC_CASH
	WHERE Exchange not in (select EXCHANGE from #ADJ_BANKBAL where #ADJ_BANKBAL.EXCHANGE = #ALLOC_CASH.EXCHANGE
	and #ADJ_BANKBAL.SEGMENT = #ALLOC_CASH.SEGMENT )
	AND (CASE WHEN EDT_LEDGER-FD_AMOUNT-BG_AMOUNT-CASH_AMOUNT > EXCESSAMT 
						   THEN EXCESSAMT ELSE EDT_LEDGER-FD_AMOUNT-BG_AMOUNT-CASH_AMOUNT END) > 0  
	OPEN @ALLOCCUR
	FETCH NEXT FROM @ALLOCCUR INTO @NEWEXCHANGE, @NEWSEGMENT, @EXCESS_AMOUNT
	WHILE @@FETCH_STATUS = 0 
	BEGIN 
		 
		SET @EXCESS_AMOUNT = (CASE WHEN @EXCESS_AMOUNT > @ADJ_AMOUNT THEN @ADJ_AMOUNT ELSE @EXCESS_AMOUNT END) 
		 
		truncate table #partydata
		insert into #partydata
		
    SELECT PARTY_CODE, TRADING_PAN, CLIENT_PAN,
		EXCESSAMT=(CASE WHEN EDT_LEDGER > 0 AND (EDT_LEDGER+LIEU_EPI_LEDGER_CLTM+POOL_ACCOUNT_CLTM+
					APPROVED_SEC_CASH_REC_TM+APPROVED_SEC_NONCASH_REC_TM+NONAPPROVED_SEC_REC_TM-UPFRONT_MARGIN) > 0  
				THEN (CASE WHEN (EDT_LEDGER+LIEU_EPI_LEDGER_CLTM+POOL_ACCOUNT_CLTM+
					APPROVED_SEC_CASH_REC_TM+APPROVED_SEC_NONCASH_REC_TM+NONAPPROVED_SEC_REC_TM-UPFRONT_MARGIN) < EDT_LEDGER 
				THEN (EDT_LEDGER+LIEU_EPI_LEDGER_CLTM+POOL_ACCOUNT_CLTM+
					APPROVED_SEC_CASH_REC_TM+APPROVED_SEC_NONCASH_REC_TM+NONAPPROVED_SEC_REC_TM-UPFRONT_MARGIN) 
				ELSE EDT_LEDGER END)
		ELSE 0 END)
		FROM CLIENT_COLLATERAL_REPORTING_DETAILS_TODAY WITH(NOLOCK)
		WHERE PROCESS_DT=@RUNDATE
		AND ACCOUNT_TYPE = 'C'  
		AND EXCHANGE=@NEWEXCHANGE AND SEGMENT=@NEWSEGMENT
		AND (CASE WHEN EDT_LEDGER > 0 AND (EDT_LEDGER+LIEU_EPI_LEDGER_CLTM+POOL_ACCOUNT_CLTM+
					APPROVED_SEC_CASH_REC_TM+APPROVED_SEC_NONCASH_REC_TM+NONAPPROVED_SEC_REC_TM-UPFRONT_MARGIN) > 0  
				THEN (CASE WHEN (EDT_LEDGER+LIEU_EPI_LEDGER_CLTM+POOL_ACCOUNT_CLTM+
					APPROVED_SEC_CASH_REC_TM+APPROVED_SEC_NONCASH_REC_TM+NONAPPROVED_SEC_REC_TM-UPFRONT_MARGIN) < EDT_LEDGER 
				THEN (EDT_LEDGER+LIEU_EPI_LEDGER_CLTM+POOL_ACCOUNT_CLTM+
					APPROVED_SEC_CASH_REC_TM+APPROVED_SEC_NONCASH_REC_TM+NONAPPROVED_SEC_REC_TM-UPFRONT_MARGIN) 
				ELSE EDT_LEDGER END)
		ELSE 0 END) > 0 AND EDT_LEDGER > 0 
		AND PARTY_CODE IN (SELECT PARTY_CODE FROM CLIENT_COLLATERAL_REPORTING_DETAILS_TODAY WITH(NOLOCK)
		WHERE PROCESS_DT=@RUNDATE
		AND ACCOUNT_TYPE = 'C'
		AND EXCHANGE=@EXCHANGE AND SEGMENT=@SEGMENT AND EDT_LEDGER >= 0 )
		 
		 
		SET @PARTYCUR = CURSOR FOR 
		SELECT * FROM #PARTYDATA
		OPEN @PARTYCUR 
		FETCH NEXT FROM  @PARTYCUR INTO @PARTY_CODE, @TRADING_PAN, @CLIENT_PAN,	@CL_AMOUNT
		WHILE @@FETCH_STATUS = 0   
		BEGIN
			IF @EXCESS_AMOUNT > 0 
			BEGIN
				IF @EXCESS_AMOUNT > @CL_AMOUNT
				BEGIN
					
          UPDATE C SET EDT_LEDGER = EDT_LEDGER - @CL_AMOUNT
					FROM CLIENT_COLLATERAL_REPORTING_DETAILS_TODAY C WITH(NOLOCK)
					WHERE PROCESS_DT=@RUNDATE
					AND ACCOUNT_TYPE = 'C'
					AND PARTY_CODE = @PARTY_CODE 
					AND EXCHANGE=@NEWEXCHANGE AND SEGMENT=@NEWSEGMENT
					AND TRADING_PAN = @TRADING_PAN 
					AND CLIENT_PAN = @CLIENT_PAN
          -------------------------------------------- AHSAN
					UPDATE C SET EDT_LEDGER = EDT_LEDGER + @CL_AMOUNT
					FROM CLIENT_COLLATERAL_REPORTING_DETAILS_TODAY C WITH(NOLOCK)
					WHERE 
              PROCESS_DT=@RUNDATE
					AND ACCOUNT_TYPE = 'C'
					AND PARTY_CODE = @PARTY_CODE 
					AND EXCHANGE=@EXCHANGE AND SEGMENT=@SEGMENT
					AND TRADING_PAN = @TRADING_PAN 
					AND CLIENT_PAN = @CLIENT_PAN

					SET @EXCESS_AMOUNT = @EXCESS_AMOUNT - @CL_AMOUNT
					SET @ADJ_AMOUNT = @ADJ_AMOUNT - @CL_AMOUNT
         --- print 'Ahsan'
				END
				ELSE
				BEGIN
					UPDATE C SET EDT_LEDGER = EDT_LEDGER - @EXCESS_AMOUNT
					FROM CLIENT_COLLATERAL_REPORTING_DETAILS_TODAY C WITH(NOLOCK) 
					WHERE PROCESS_DT=@RUNDATE AND PARTY_CODE = @PARTY_CODE 
					AND ACCOUNT_TYPE = 'C'
					AND EXCHANGE=@NEWEXCHANGE AND SEGMENT=@NEWSEGMENT
					AND TRADING_PAN = @TRADING_PAN 
					AND CLIENT_PAN = @CLIENT_PAN

					UPDATE C SET EDT_LEDGER = EDT_LEDGER + @EXCESS_AMOUNT
					FROM CLIENT_COLLATERAL_REPORTING_DETAILS_TODAY C WITH(NOLOCK)
					WHERE PROCESS_DT=@RUNDATE AND PARTY_CODE = @PARTY_CODE 
					AND ACCOUNT_TYPE = 'C'
					AND EXCHANGE=@EXCHANGE AND SEGMENT=@SEGMENT
					AND TRADING_PAN = @TRADING_PAN 
					AND CLIENT_PAN = @CLIENT_PAN
					
					SET @ADJ_AMOUNT = @ADJ_AMOUNT - @EXCESS_AMOUNT
					SET @EXCESS_AMOUNT = 0
				END
			END
			FETCH NEXT FROM  @PARTYCUR INTO @PARTY_CODE, @TRADING_PAN, @CLIENT_PAN,	@CL_AMOUNT
		END
		CLOSE @PARTYCUR
		DEALLOCATE @PARTYCUR
		FETCH NEXT FROM @ALLOCCUR INTO @NEWEXCHANGE, @NEWSEGMENT, @EXCESS_AMOUNT
	END	
	CLOSE @ALLOCCUR
	DEALLOCATE @ALLOCCUR

	FETCH NEXT FROM @SETCUR INTO @EXCHANGE, @SEGMENT, @ADJ_AMOUNT
END
CLOSE @SETCUR
DEALLOCATE @SETCUR

GO
