-- Object: PROCEDURE dbo.CHECK_CCE_SEBIPAYOUT_ANG
-- Server: 10.253.33.91 | DB: MSAJAG
--------------------------------------------------

  
CREATE PROC [dbo].[CHECK_CCE_SEBIPAYOUT_ANG] ( @REPORTDT VARCHAR(11), @REPORTDT1 VARCHAR(11))  
  
AS  



  
-- EXEC CHECK_CCE_SEBIPAYOUT_ANG 'JAN 19 2023'  
  
--SELECT * INTO #CLIENT_CASH_ACTIVE_LOG FROM ACCOUNT..CLIENT_CASH_ACTIVE_LOG WHERE @REPORTDT BETWEEN STATUS_FROM_DATE AND STATUS_TO_DATE  AND STATUS_FLAG = 0  
  
SELECT * INTO #CLIENT_CASH_ACTIVE_LOG FROM ACCOUNT..CLIENT_CASH_ACTIVE_LOG 
WHERE  STATUS_FROM_DATE = @REPORTDT  AND  STATUS_FLAG = 0  -- CHANGED FROM 2ND MAY 2023
  
SELECT CONVERT(VARCHAR(10),REPORT_DATE,105) AS REPORT_DATE,UCC,SEGMENT_INDICATOR AS [MTF/ NON MTF INDICATOR],SUM(VDT_BAL) AS [FINANCIAL LEDGER BALANCE-A],  
SUM(EDT_BAL) AS [FINANCIAL LEDGER BALANCE (CLEAR)-B] INTO #CCE_UNCLAIMED_CLIENT_FUNDS_ANG --,[HEMANT FILE DATA-UNCLAIMED/UNSETTLED CLIENT FUNDS]   
FROM CCE_UNCLAIMED_CLIENT_FUNDS_ANG   WITH(NOLOCK)   
  WHERE REPORT_DATE = @REPORTDT AND SEGMENT_INDICATOR = 'NON MTF'  
  GROUP BY REPORT_DATE,UCC,SEGMENT_INDICATOR  
  
SELECT A.*,B.CLTCODE INTO #CHECK1 FROM #CCE_UNCLAIMED_CLIENT_FUNDS_ANG A FULL OUTER JOIN #CLIENT_CASH_ACTIVE_LOG B  
ON (UCC = CLTCODE)   
  
  
SELECT REPORT_DATE,UCC,[MTF/ NON MTF INDICATOR],[FINANCIAL LEDGER BALANCE-A],  
[FINANCIAL LEDGER BALANCE (CLEAR)-B],[HEMANT FILE DATA-UNCLAIMED/UNSETTLED CLIENT FUNDS] =   
CASE WHEN CLTCODE = UCC THEN 'YES' ELSE CLTCODE END,UNSETTLED_SEPARATEBANK_CLIENT = CONVERT(VARCHAR(10),''),  
UNSETTLED_SEPARATEBANK_CLIENT_AMOUNT =  CONVERT(NUMERIC(18,2),0),  
UNSETTLED_SEPARATEBANK_CLIENT_DT =  CONVERT(VARCHAR(10),''),[MATCH/UNMATCH] =  CONVERT(VARCHAR(20),'UNMACTHED') INTO #CHECK3  
FROM #CHECK1 ORDER BY 2  
  
SELECT * INTO #CHECK2  FROM [MIS].SCCS.DBO.UNSETTLED_SEPARATEBANK WHERE BALANCE_DATE = (  
SELECT MAX(BALANCE_DATE) FROM [MIS].SCCS.DBO.UNSETTLED_SEPARATEBANK  WHERE BALANCE_DATE <= CONVERT(DATE,@REPORTDT))  
  
IF (SELECT COUNT(1) FROM #CHECK2 ) = 0  
BEGIN  
INSERT INTO #CHECK2 SELECT * FROM [MIS].SCCS.DBO.UNSETTLED_SEPARATEBANK_HIST WHERE BALANCE_DATE = (  
SELECT MAX(BALANCE_DATE) FROM [MIS].SCCS.DBO.UNSETTLED_SEPARATEBANK_HIST WHERE BALANCE_DATE <= CONVERT(DATE,@REPORTDT))  
END  
  
  
UPDATE #CHECK3 SET UNSETTLED_SEPARATEBANK_CLIENT = CLTCODE ,UNSETTLED_SEPARATEBANK_CLIENT_AMOUNT = BALANCE,  
UNSETTLED_SEPARATEBANK_CLIENT_DT = CONVERT(VARCHAR(10),BALANCE_DATE,105)  
FROM  #CHECK2 WHERE UCC = CLTCODE   
  
  
UPDATE #CHECK3 SET UNSETTLED_SEPARATEBANK_CLIENT = CLTCODE ,UNSETTLED_SEPARATEBANK_CLIENT_AMOUNT = BALANCE,  
UNSETTLED_SEPARATEBANK_CLIENT_DT =  CONVERT(VARCHAR(10),BALANCE_DATE,105)  
FROM  #CHECK2 WHERE [HEMANT FILE DATA-UNCLAIMED/UNSETTLED CLIENT FUNDS] = CLTCODE   
  
UPDATE #CHECK3 SET  [MATCH/UNMATCH] = 'MATCHED' WHERE UCC = UNSETTLED_SEPARATEBANK_CLIENT AND [HEMANT FILE DATA-UNCLAIMED/UNSETTLED CLIENT FUNDS] = 'YES'  
  
UPDATE #CHECK3 SET [REPORT_DATE] = CONVERT(VARCHAR(10),CONVERT(DATE,@REPORTDT),105)  
  
SELECT [REPORT_DATE],  
CASE WHEN [UCC] IS NULL THEN '' ELSE [UCC] END AS [UCC],  
CASE WHEN [MTF/ NON MTF INDICATOR] IS NULL THEN '' ELSE [MTF/ NON MTF INDICATOR] END AS [MTF/ NON MTF INDICATOR],  
CASE WHEN [FINANCIAL LEDGER BALANCE-A] IS NULL THEN '' ELSE [FINANCIAL LEDGER BALANCE-A] END  AS [FINANCIAL LEDGER BALANCE-A],  
CASE WHEN [FINANCIAL LEDGER BALANCE (CLEAR)-B] IS NULL THEN '' ELSE [FINANCIAL LEDGER BALANCE (CLEAR)-B] END AS [FINANCIAL LEDGER BALANCE (CLEAR)-B],  
CASE WHEN [HEMANT FILE DATA-UNCLAIMED/UNSETTLED CLIENT FUNDS] IS NULL THEN '' ELSE  
[HEMANT FILE DATA-UNCLAIMED/UNSETTLED CLIENT FUNDS] END AS [HEMANT FILE DATA-UNCLAIMED/UNSETTLED CLIENT FUNDS],  
[UNSETTLED_SEPARATEBANK_CLIENT],[UNSETTLED_SEPARATEBANK_CLIENT_AMOUNT],[UNSETTLED_SEPARATEBANK_CLIENT_DT],[MATCH/UNMATCH]  
FROM #CHECK3 ORDER BY 2  
  
  
DROP TABLE #CLIENT_CASH_ACTIVE_LOG  
DROP TABLE #CCE_UNCLAIMED_CLIENT_FUNDS_ANG  
DROP TABLE #CHECK1  
DROP TABLE #CHECK2  
DROP TABLE #CHECK3

GO
