-- Object: PROCEDURE dbo.RPT_RMS_TRADE_SELL
-- Server: 10.253.33.91 | DB: MSAJAG
--------------------------------------------------


CREATE PROC [DBO].[RPT_RMS_TRADE_SELL]       
(      
 @EXCHANGE VARCHAR(3),    
 @FILEFOR VARCHAR(4),    
 @ORDERTYPE VARCHAR(6),    
 @FROMPARTY VARCHAR(10),    
 @TOPARTY VARCHAR(10),    
 @POAFLAG VARCHAR(3),    
 @BRANCH VARCHAR(1000)    
)      
      
AS      
  
DECLARE @MEMCODE VARCHAR(15)      
    
INSERT INTO TBL_RMS_FILE_LOG    
SELECT @EXCHANGE, @FILEFOR, @ORDERTYPE, @FROMPARTY, @TOPARTY, @POAFLAG, @BRANCH, GETDATE()    
      
SELECT DISTINCT BRANCH_CODE INTO #BRANCH FROM BRANCH     
WHERE BRANCH_CODE NOT IN (SELECT SPLITTED_VALUE FROM PRADNYA.DBO.FUN_SPLITSTRING (@BRANCH,','))    
  
SELECT SNO, EXCHANGE = 'NSE', PARTY_CODE, SCRIP_CD, SERIES=CONVERT(VARCHAR(6),''), QTY, CL_RATE=CONVERT(NUMERIC(18,4),0), MEMBERCODE = @MEMCODE  
INTO #TBL_RMS_SALE  
FROM DELTRANS  
WHERE 1 = 2   
     
IF @EXCHANGE = 'NSE'      
BEGIN      
 SELECT @MEMCODE = MEMBERCODE       
 FROM OWNER       
END      
ELSE      
BEGIN      
 SELECT @MEMCODE = 'CLIENT'      
END      
  
INSERT INTO #TBL_RMS_SALE  
SELECT EXCHANGE, PARTY_CODE, SCRIP_CD, SERIES, QTY = SUM(TOSELLQTY),       
CL_RATE, MEMBERCODE = @MEMCODE      
FROM TBL_RMS_SALE      
WHERE TOSELLQTY > 0       
AND EXCHANGE = @EXCHANGE    
AND PARTY_CODE BETWEEN @FROMPARTY AND @TOPARTY    
AND BRANCH_CD IN (SELECT BRANCH_CODE FROM #BRANCH )    
GROUP BY EXCHANGE, SCRIP_CD, SERIES, PARTY_CODE, CL_RATE    
ORDER BY EXCHANGE, SCRIP_CD, SERIES, PARTY_CODE  
  
IF @POAFLAG = 'YES'     
BEGIN    
DELETE FROM #TBL_RMS_SALE  
WHERE PARTY_CODE IN (SELECT PARTY_CODE FROM MULTICLTID    
    WHERE DEF = 1)    
END    
  
IF @FILEFOR = 'NEAT' AND @EXCHANGE = 'NSE'  
BEGIN    
 IF @ORDERTYPE = 'LIMIT'  
 BEGIN  
  SELECT DATA=CONVERT(VARCHAR,SNO) + ',1,2,' + RTRIM(SCRIP_CD) + ',' + RTRIM(SERIES) + ',1,,,,' + CONVERT(VARCHAR,CONVERT(NUMERIC(18,2),CL_RATE)) + ',,' + CONVERT(VARCHAR,QTY) + ',,' + RTRIM(MEMBERCODE) + ',2,' + RTRIM(PARTY_CODE) + ',DEBIT CLEARENCE,', SNO  
  FROM #TBL_RMS_SALE  
  ORDER BY SNO  
 END  
 ELSE  
 BEGIN  
  SELECT DATA=CONVERT(VARCHAR,SNO) + ',1,2,' + RTRIM(SCRIP_CD) + ',' + RTRIM(SERIES) + ',1,,,,MKT,,' + CONVERT(VARCHAR,QTY) + ',,' + RTRIM(MEMBERCODE) + ',2,' + RTRIM(PARTY_CODE) + ',DEBIT CLEARENCE,', SNO  
  FROM #TBL_RMS_SALE  
  ORDER BY SNO   
 END  
END    
  
IF @FILEFOR = 'ODIN' AND @EXCHANGE = 'NSE'  
BEGIN   
 IF @ORDERTYPE = 'LIMIT'  
 BEGIN  
  --SELECT DATA=CONVERT(VARCHAR,SNO) + ',1,2,' + RTRIM(SCRIP_CD) + ',' + RTRIM(SERIES) + ',1,,,,' + CONVERT(VARCHAR,CONVERT(NUMERIC(18,2),CL_RATE)) + ',,' + CONVERT(VARCHAR,QTY) + ',,' + RTRIM(MEMBERCODE) + ',2,' + RTRIM(PARTY_CODE) + ',DEBIT CLEARENCE,,DLV', SNO  
  SELECT DATA=CONVERT(VARCHAR,SNO) + ',1,2,' + RTRIM(SCRIP_CD) + ',' + RTRIM(SERIES) + ',1,,,,' + CONVERT(VARCHAR,CONVERT(NUMERIC(18,2),CL_RATE)) + ',,' + CONVERT(VARCHAR,QTY) + ',,,2,' + RTRIM(PARTY_CODE) + ',,,1', SNO FROM #TBL_RMS_SALE  ORDER BY SNO  
 END  
 ELSE  
 BEGIN  
  --SELECT DATA=CONVERT(VARCHAR,SNO) + ',1,2,' + RTRIM(SCRIP_CD) + ',' + RTRIM(SERIES) + ',1,,,,MKT,,' + CONVERT(VARCHAR,QTY) + ',,' + RTRIM(MEMBERCODE) + ',2,' + RTRIM(PARTY_CODE) + ',DEBIT CLEARENCE,,DLV', SNO  
  SELECT DATA=CONVERT(VARCHAR,SNO) + ',1,2,' + RTRIM(SCRIP_CD) + ',' + RTRIM(SERIES) + ',1,,,,' + CONVERT(VARCHAR,CONVERT(NUMERIC(18,2),'0.00')) + ',,' + CONVERT(VARCHAR,QTY) + ',,,2,' + RTRIM(PARTY_CODE) + ',,,1', SNO FROM #TBL_RMS_SALE  
  ORDER BY SNO   
 END  
END    
  
IF @FILEFOR = 'NEAT' AND @EXCHANGE = 'BSE'  
BEGIN    
 IF @ORDERTYPE = 'LIMIT'  
 BEGIN   
  SELECT DATA='S|' + CONVERT(VARCHAR,QTY) + '|' + CONVERT(VARCHAR,QTY) + '|' + RTRIM(SERIES) + '|' + CONVERT(VARCHAR,CONVERT(NUMERIC(18,2),CL_RATE)*100) + '|' + RTRIM(PARTY_CODE) + '|EOSESS|CLIENT|L', SNO   
  FROM #TBL_RMS_SALE      
 END   
 ELSE  
 BEGIN   
  SELECT DATA='S|' + CONVERT(VARCHAR,QTY) + '|' + CONVERT(VARCHAR,QTY) + '|' + RTRIM(SERIES) + '|' + CONVERT(VARCHAR,CONVERT(NUMERIC(18,2),CL_RATE)*100) + '|' + RTRIM(PARTY_CODE) + '|EOSESS|CLIENT|G', SNO   
  FROM #TBL_RMS_SALE      
 END    
END    
  
IF @FILEFOR = 'ODIN' AND @EXCHANGE = 'BSE'  
BEGIN   
 IF @ORDERTYPE = 'LIMIT'  
 BEGIN   
  --SELECT DATA='S|' + CONVERT(VARCHAR,QTY) + '||' + RTRIM(SERIES) + '|MKT|' + CONVERT(VARCHAR,QTY) + '|'  + CONVERT(VARCHAR,CONVERT(NUMERIC(18,2),CL_RATE)*100) + '|' + RTRIM(PARTY_CODE) + '|EOSESS|'  + '|L||DELV|', SNO   
  SELECT DATA='S|' + CONVERT(VARCHAR,QTY) + '|' + CONVERT(VARCHAR,QTY) + '|' + RTRIM(SERIES) + '|'  + REPLACE(CONVERT(VARCHAR,CONVERT(NUMERIC(18,2),CL_RATE)),'.','') + '|' + RTRIM(PARTY_CODE) + '|EOD|CLIENT|L|', SNO   
  FROM #TBL_RMS_SALE      
 END   
 ELSE  
 BEGIN   
  --SELECT DATA='S|' + CONVERT(VARCHAR,QTY) + '||' + RTRIM(SERIES) + '|MKT|' + CONVERT(VARCHAR,QTY) + '|'  + CONVERT(VARCHAR,CONVERT(NUMERIC(18,2),CL_RATE)*100) + '|' + RTRIM(PARTY_CODE) + '|EOSESS|'  + '|M||DELV|', SNO   
  SELECT DATA='S|' + CONVERT(VARCHAR,QTY) + '|' + CONVERT(VARCHAR,QTY) + '|' + RTRIM(SERIES) + '|MKT|' + RTRIM(PARTY_CODE) + '|EOD|CLIENT|M|', SNO   
  FROM #TBL_RMS_SALE      
 END    
END

GO
