-- Object: PROCEDURE dbo.PROC_SHORT_MARGIN_UPINTRA_NCX
-- Server: 10.253.33.91 | DB: MSAJAG
--------------------------------------------------

-- Exec PROC_SHORT_MARGIN_UPINTRA_NCX 'Feb 13 2023','D:\BACKOFFICE\SA04\NCCL_COM_PSA_00220_13022023154216.CSV','BROKER'

CREATE PROCEDURE [dbo].[PROC_SHORT_MARGIN_UPINTRA_NCX]
	@MARGINDATE VARCHAR(11),
	@FLDFILENAME VARCHAR (300),
	@UPLOAD_BY VARCHAR(30) = ''
AS

TRUNCATE TABLE TBL_NCX_SHORT_ALLOC_INTRA_TMP
 
DECLARE
	@STRSQL VARCHAR(1000)
		
DECLARE
	@FILENAME VARCHAR(50)
SELECT @FILENAME = RIGHT(@FLDFILENAME, CHARINDEX('\', REVERSE(@FLDFILENAME),0) - 1)

	Set @strSql = 'Bulk insert TBL_NCX_SHORT_ALLOC_INTRA_TMP from ''' + @FLDFILENAME  + '''  with ( FIELDTERMINATOR = '','', ROWTERMINATOR = ''\n'',FIRSTROW=2 )'
	Exec(@strSql)
	   
	DELETE FROM TBL_NCX_SHORT_ALLOC_INTRA WHERE MARGINDATE = @MARGINDATE 
	
UPDATE TBL_NCX_SHORT_ALLOC_INTRA_TMP 
SET MARGINDATE = REPLACE(MARGINDATE,'''',''),
    TMID = REPLACE(TMID,'''',''),
    CLIENT_CODE = REPLACE(CLIENT_CODE,'''','')

UPDATE TBL_NCX_SHORT_ALLOC_INTRA_TMP SET PEAK_SNAP_TIME = ISNULL(PEAK_SNAP_TIME,'')
	
INSERT INTO TBL_NCX_SHORT_ALLOC_INTRA 
SELECT *,
@FILENAME,@UPLOAD_BY,UPLOAD_ON=GETDATE()
FROM TBL_NCX_SHORT_ALLOC_INTRA_TMP WHERE CONVERT(DATETIME,MARGINDATE) = @MARGINDATE

GO
