-- Object: PROCEDURE dbo.NSE_SCRIPMAPPINGINSERT_BKP_14AUG2025_SRE_85483_
-- Server: 10.253.33.91 | DB: MSAJAG
--------------------------------------------------




CREATE PROC [dbo].[NSE_SCRIPMAPPINGINSERT_BKP_14AUG2025_SRE_85483_]
AS

UPDATE TBL_EXCHG_SCRIP_MAP_TMP SET UPDFLAG = 1
FROM TBL_EXCHG_SCRIP_MAP T
WHERE T.ISIN = TBL_EXCHG_SCRIP_MAP_TMP.ISIN
AND T.BSECODE = TBL_EXCHG_SCRIP_MAP_TMP.BSECODE
AND T.NSE_SCRIP_CD = TBL_EXCHG_SCRIP_MAP_TMP.NSE_SCRIP_CD 
AND T.NSE_SERIES = TBL_EXCHG_SCRIP_MAP_TMP.NSE_SERIES 
AND GETDATE() BETWEEN FROM_DATE AND TO_DATE

UPDATE TBL_EXCHG_SCRIP_MAP SET TO_DATE = LEFT(GETDATE()-1,11) + ' 23:59:59'
WHERE GETDATE() BETWEEN FROM_DATE AND TO_DATE AND ISIN NOT IN (SELECT ISIN FROM TBL_EXCHG_SCRIP_MAP_TMP)

UPDATE TBL_EXCHG_SCRIP_MAP SET TO_DATE = LEFT(GETDATE()-1,11) + ' 23:59:59'
WHERE GETDATE() BETWEEN FROM_DATE AND TO_DATE AND ISIN IN (SELECT ISIN FROM TBL_EXCHG_SCRIP_MAP_TMP WHERE UPDFLAG = 0)

INSERT INTO TBL_EXCHG_SCRIP_MAP
SELECT ISIN, BSECODE, BSE_GROUP, SCRIP_NAME, NSE_SCRIP_CD, NSE_SERIES,
FROM_DATE=LEFT(GETDATE(),11),TO_DATE='DEC 31 2049 23:59:59',ADDED_ON=GETDATE(),ADDED_BY='BACKEND'
FROM TBL_EXCHG_SCRIP_MAP_TMP
WHERE UPDFLAG = 0

DECLARE @CO_CODE	INT

SELECT DISTINCT NSE_SCRIP_CD = NSE_SCRIP_CD, NSE_SERIES = NSE_SERIES, ISIN, LONG_NAME = SCRIP_NAME
INTO #NEWSCRIP FROM TBL_EXCHG_SCRIP_MAP
WHERE NSE_SCRIP_CD NOT IN (SELECT SCRIP_CD FROM SCRIP2 WHERE SERIES = NSE_SERIES) 

INSERT INTO MULTIISIN
SELECT SCRIP_CD = NSE_SCRIP_CD, SERIES = NSE_SERIES, ISIN, VALID = 1
FROM #NEWSCRIP
WHERE NSE_SCRIP_CD NOT IN (SELECT SCRIP_CD FROM MULTIISIN WHERE VALID = 1)
AND ISIN NOT IN (SELECT ISIN FROM MULTIISIN WHERE VALID = 1)

ALTER TABLE #NEWSCRIP
ADD SNO INT IDENTITY(1,1)

SELECT @CO_CODE = ISNULL(MAX(CONVERT(INT,CO_CODE)),0) FROM SCRIP2


INSERT INTO SCRIP2
SELECT CO_CODE = @CO_CODE + SNO, SERIES = NSE_SERIES, EXCHANGE ='NSE', SCRIP_CD = NSE_SCRIP_CD, SCRIP_CAT = 'HIG', 
NO_DEL_FR = 'Jan  1 1900 12:00AM', NO_DEL_TO = 'Jan  1 1900 12:00AM', CL_RATE = 0, CLOS_RATE_DT = 0, MIN_TRD_QTY = 0, 0,
ISIN, DELSC_CAT = 'A', SECTOR = '', TRACK = '', CDOL_NO = '', RES1 = '', RES2 = '', RES3 = '', RES4 = '', GLOBALCUSTODIAN = '',
COMMON_CODE = '', INDEXNAME = '', INDUSTRY = '', BLOOOMBERG = '', RICCODE = '', REUTERS = '', IES = '', NOOFISSUEDSHARES = 0,
STATUS = 'A', ADRGDRRATIO = 0, GEMULTIPLE = 0, GroupforGE = 0, RBICEILINGINDICATORFLAG = '', REBICEILINGINDICATORTVALUE = 0
FROM #NEWSCRIP

INSERT INTO SCRIP1
SELECT CO_CODE = @CO_CODE + SNO, SERIES = NSE_SERIES, SHORT_NAME = NSE_SCRIP_CD, LONG_NAME, MARKET_LOT = 1, FACE_VAL = 1,
BOOK_CL_DT = 'Jan  1 1900 12:00AM', EX_DIV_DT = '', EX_BON_DT = '', EX_RIT_DT = '', EQT_TYPE = NSE_SERIES, SUB_TYPE = NSE_SERIES,
AGENT_CD = '', DEMAT_FLAG = '0', DEMAT_DATE = '2049-12-31 00:00:00.000', RES1 = '', RES2 = '', RES3 = '', RES4 = '' 
FROM #NEWSCRIP

DROP TABLE #NEWSCRIP

GO
