-- Object: PROCEDURE dbo.CLS_COMMON_CONTRACT_DEALINGADD
-- Server: 10.253.33.91 | DB: MSAJAG
--------------------------------------------------





CREATE PROC [dbo].[CLS_COMMON_CONTRACT_DEALINGADD]
	(
	@ADDFOR VARCHAR(15),
	@CODE	VARCHAR(20)
	)

	AS
	
	/*
	EXEC CLS_COMMON_CONTRACT_DEALINGADD 'BRANCH','HO'
	*/
	
	CREATE TABLE #DEALINGADD
	(
		CODE		VARCHAR(20),
		LONG_NAME	VARCHAR(100),
		ADDRESS1	VARCHAR(100), 
		ADDRESS2	VARCHAR(100), 
		CITY		VARCHAR(50), 
		STATE		VARCHAR(50), 
		ZIP			VARCHAR(15), 
		PHONE1		VARCHAR(50), 
		FAX			VARCHAR(25), 
		EMAIL		VARCHAR(50), 
		CONTACT_PERSON VARCHAR(100)
	)
	
	IF (@ADDFOR = 'BRANCH')
	BEGIN
		INSERT INTO #DEALINGADD
		SELECT 
			CODE = LTRIM(RTRIM(BRANCH_CODE)), 
			LONG_NAME = LTRIM(RTRIM(LONG_NAME)), 
			ADDRESS1 = LTRIM(RTRIM(ADDRESS1)), 
			ADDRESS2 = LTRIM(RTRIM(ADDRESS2)), 
			CITY = LTRIM(RTRIM(CITY)), 
			STATE = LTRIM(RTRIM(STATE)), 
			ZIP = LTRIM(RTRIM(ZIP)), 
			PHONE1 = LTRIM(RTRIM(PHONE1)), 
			FAX = LTRIM(RTRIM(FAX)), 
			EMAIL = LTRIM(RTRIM(EMAIL)), 
			CONTACT_PERSON = LTRIM(RTRIM(CONTACT_PERSON))
		FROM BRANCH (NOLOCK) 
		WHERE BRANCH_CODE = @CODE
	END
	ELSE IF (@ADDFOR = 'BRANCHES')
	BEGIN
		INSERT INTO #DEALINGADD
		SELECT 
			CODE = LTRIM(RTRIM(BRANCH_CD)), 
			LONG_NAME = LTRIM(RTRIM(LONG_NAME)), 
			ADDRESS1 = LTRIM(RTRIM(ADDRESS1)), 
			ADDRESS2 = LTRIM(RTRIM(ADDRESS2)), 
			CITY = LTRIM(RTRIM(CITY)), 
			STATE = LTRIM(RTRIM(STATE)), 
			ZIP = LTRIM(RTRIM(ZIP)), 
			PHONE1 = LTRIM(RTRIM(PHONE1)), 
			FAX = LTRIM(RTRIM(FAX)), 
			EMAIL = LTRIM(RTRIM(EMAIL)), 
			CONTACT_PERSON = LTRIM(RTRIM(CONTACT_PERSON))
		FROM BRANCHES (NOLOCK) 
			WHERE SHORT_NAME = @CODE	
	END
	ELSE IF (@ADDFOR = 'SUBBROKERS')
	BEGIN
		INSERT INTO #DEALINGADD
		SELECT 
			CODE = LTRIM(RTRIM(SUB_BROKER)),
			LONG_NAME = LTRIM(RTRIM(NAME)), 
			ADDRESS1 = LTRIM(RTRIM(ADDRESS1)), 
			ADDRESS2 = LTRIM(RTRIM(ADDRESS2)), 
			CITY = LTRIM(RTRIM(CITY)), 
			STATE = LTRIM(RTRIM(STATE)), 
			ZIP = LTRIM(RTRIM(ZIP)), 
			PHONE1 = LTRIM(RTRIM(PHONE1)), 
			FAX = LTRIM(RTRIM(FAX)), 
			EMAIL = LTRIM(RTRIM(EMAIL)), 
			BRANCH_CODE = LTRIM(RTRIM(SUB_BROKER)),
			CONTACT_PERSON 
		FROM SUBBROKERS (NOLOCK) 
		WHERE SUB_BROKER = @CODE	
	END
	
	SELECT * FROM #DEALINGADD
	
	DROP TABLE #DEALINGADD

GO
