-- Object: PROCEDURE dbo.PROC_PRODUCT_SHORTAGE_NEW_BKUP_11May2023
-- Server: 10.253.33.91 | DB: MSAJAG
--------------------------------------------------



CREATE PROC [dbo].[PROC_PRODUCT_SHORTAGE_NEW_BKUP_11May2023]
(
	@START_DATE VARCHAR(11)
)
AS

DECLARE	@SETT_NO	VARCHAR(7),
		@EPNDATE	DATETIME

-- EXEC PROC_PRODUCT_SHORTAGE_NEW @START_DATE = 'NOV 15 2022'

SELECT * INTO #SETT_MST FROM SETT_MST (NOLOCK) WHERE START_DATE = @START_DATE
AND SETT_TYPE NOT IN ('A','X','Q','AF','AC','AD')
 
	---ADDED ON 12-01-2021 FOR MISMATCH IN MULTIISIN AND DELIVERYCLT
	UPDATE M 
	SET M.I_ISIN = A.ISIN
	FROM DELIVERYCLT M (NOLOCK) , MultiIsin A (NOLOCK) , #SETT_MST S
	WHERE M.SETT_NO=S.SETT_NO
	AND M.SETT_TYPE = S.SETT_TYPE
	AND Valid='1'
	AND M.Scrip_cd=A.Scrip_cd
	AND M.Series=A.Series
	AND M.I_ISIN <> A.ISIN
	---ADDED ON 12-01-2021 FOR MISMATCH IN MULTIISIN AND DELIVERYCLT

SELECT M.*, RECQTY=0,MARKQTY=0, EPN=0,EPN_CC=0,ALLHOLDING=0 INTO #DEL FROM  DELIVERYCLT_GROSS_FLAG M (NOLOCK) , #SETT_MST S
WHERE M.SETT_NO=S.SETT_NO
	AND M.SETT_TYPE = S.SETT_TYPE
AND INOUT='I' 

SELECT M.SETT_NO, M.SETT_TYPE, TRANSDATE = ISNULL(MAX(TRANSDATE),'APR  1 2020')
INTO #EPNSETT 
FROM TBL_PAYIN_DATA M (NOLOCK), #SETT_MST S
WHERE M.SETT_NO=S.SETT_NO
AND M.SETT_TYPE = S.SETT_TYPE
GROUP BY M.SETT_NO, M.SETT_TYPE

SELECT T.* INTO #EPN FROM TBL_PAYIN_DATA T (NOLOCK), #EPNSETT S
WHERE T.SETT_NO = S.SETT_NO AND T.SETT_TYPE = S.SETT_TYPE
AND T.TRANSDATE = S.TRANSDATE
AND RECORD_TYPE='EPN'
AND EPN_STATUS = 'S'

CREATE CLUSTERED INDEX IDXPARTY ON #DEL 
(
	PARTY_CODE,
	I_ISIN
)

SELECT PARTY_CODE, CERTNO,QTY=SUM(QTY) INTO #DELTRANS FROM DELTRANS D (NOLOCK) 
WHERE 
DRCR='D' AND FILLER2=1 AND SHARETYPE <>'AUCTION' AND DELIVERED ='0' AND TRTYPE NOT IN (907,1000,1002) 
AND EXISTS (SELECT Party_Code FROM #DEL WHERE #DEL.PARTY_CODE=D.PARTY_CODE
AND #DEL.I_ISIN=D.CERTNO )
GROUP BY PARTY_CODE, CERTNO

SELECT M.* INTO #POOLDATA FROM DELTRANS M (NOLOCK), #SETT_MST S
WHERE M.SETT_NO=S.SETT_NO
AND M.SETT_TYPE = S.SETT_TYPE
AND FILLER2=1 AND SHARETYPE <>'AUCTION'
AND Drcr = 'C'

SELECT M.* INTO #POOLDATADR FROM DELTRANS M (NOLOCK), #SETT_MST S
WHERE M.SETT_NO=S.SETT_NO
AND M.SETT_TYPE = S.SETT_TYPE
AND FILLER2=1 AND SHARETYPE <>'AUCTION'
AND Drcr = 'D'

UPDATE #POOLDATA SET Filler1 = 'EARLY PAY-IN' FROM #POOLDATADR P
WHERE P.Certno = #POOLDATA.Certno AND P.Tcode = #POOLDATA.Tcode
AND P.Drcr = 'D' AND P.Trtype = 906  
AND #POOLDATA.Drcr= 'C' AND #POOLDATA.Trtype <> 906

UPDATE #DEL SET ALLHOLDING =D.QTY
FROM #DELTRANS D
WHERE #DEL.PARTY_CODE=D.PARTY_CODE
AND #DEL.I_ISIN=D.CERTNO 

UPDATE #DEL SET EPN_CC = EPNQTY 
FROM (SELECT PARTY_CODE, Scrip_Cd, Series,EPNQTY=SUM(EPNQTY) FROM #EPN
      GROUP BY PARTY_CODE, SCRIP_CD,Series)D
WHERE #DEL.PARTY_CODE=D.PARTY_CODE
AND #DEL.SCRIP_CD=D.SCRIP_CD
AND #DEL.SERIES = D.SERIES
AND FLAG='N'

UPDATE #DEL SET RECQTY =D.QTY, EPN = EPNQTY 
FROM (SELECT SETT_NO,SETT_TYPE,PARTY_CODE, CERTNO,QTY=SUM(QTY), EPNQTY = SUM(CASE WHEN Filler1 = 'EARLY PAY-IN' THEN Qty ELSE 0 END) FROM #POOLDATA
  WHERE DRCR='C' AND FILLER2=1 AND SHARETYPE <>'AUCTION'
      GROUP BY SETT_NO,SETT_TYPE,PARTY_CODE, CERTNO)D
WHERE #DEL.SETT_NO = D.SETT_NO
AND #DEL.SETT_TYPE = D.SETT_TYPE
AND #DEL.PARTY_CODE=D.PARTY_CODE
AND #DEL.I_ISIN=D.CERTNO
AND FLAG='N'

UPDATE #DEL SET MARKQTY =D.QTY
FROM (SELECT ISETT_NO, ISETT_TYPE, PARTY_CODE, CERTNO,QTY=SUM(QTY) FROM DELTRANS M (NOLOCK), #SETT_MST S
	WHERE M.SETT_NO=S.SETT_NO
	AND M.SETT_TYPE = S.SETT_TYPE
	AND DRCR='D' AND FILLER2=1 AND SHARETYPE <>'AUCTION'
	 AND DELIVERED<>'D'
   GROUP BY ISETT_NO, ISETT_TYPE,PARTY_CODE, CERTNO)D
WHERE #DEL.SETT_NO = D.ISETT_NO
AND #DEL.SETT_TYPE = D.ISETT_TYPE
AND #DEL.PARTY_CODE=D.PARTY_CODE
AND #DEL.I_ISIN=D.CERTNO
AND FLAG='N'

ALTER TABLE #DEL 
ADD BTST INT

UPDATE #DEL SET BTST=0

SELECT PARTY_CODE, I_ISIN, QTY = SUM(QTY), FLAG 
INTO #BTST
FROM DELIVERYCLT_GROSS_FLAG D (NOLOCK), SETT_MST S, (select distinct sec_payin = CONVERT(DATETIME,LEFT(SEC_PAYIN,11)) from #del d, sett_mst s1 (NOLOCK) 
											where d.sett_no = s1.sett_no and d.sett_type = s1.sett_type) m
WHERE D.SETT_NO = S.SETT_NO 
AND D.SETT_TYPE = S.SETT_TYPE 
AND s.SEC_PAYIN > @START_DATE
AND INOUT = 'O'
AND START_DATE < @START_DATE
and CONVERT(DATETIME,LEFT(S.SEC_PAYIN,11)) <= CONVERT(DATETIME,LEFT(S.Sec_Payin,11))
AND S.SETT_TYPE NOT IN ('A','AD','AC','X','Q') 
GROUP BY PARTY_CODE, I_ISIN, FLAG


UPDATE #DEL SET BTST =D.QTY 
FROM #BTST D
WHERE #DEL.FLAG = D.FLAG
AND D.PARTY_CODE=#DEL.PARTY_CODE
AND D.I_ISIN= #DEL.I_ISIN

ALTER TABLE #DEL 
ADD POA VARCHAR(3)

UPDATE #DEL SET POA='NO'
/*
UPDATE #DEL SET POA =D.QTY
FROM (SELECT PARTY_CODE, ISIN,QTY=SUM(CASE WHEN TORECQTY > BALANCE THEN BALANCE ELSE TORECQTY END) FROM DELPOASHORTAGE
  WHERE 
   SETT_NO=@SETT_NO AND SETT_TYPE IN ('N','W') 
   AND BALANCE >0
   GROUP BY PARTY_CODE, ISIN)D
WHERE #DEL.PARTY_CODE=D.PARTY_CODE
AND #DEL.I_ISIN=D.ISIN
AND FLAG='N'*/

UPDATE #DEL SET POA = 'YES'
FROM MULTICLTID M (NOLOCK) 
WHERE M.Party_Code = #DEL.PARTY_CODE
AND Def = 1

SELECT SHORTQTY=(QTY-(RECQTY+MARKQTY)), * FROM #DEL  
ORDER BY FLAG, SCRIP_CD, PARTY_CODE

DROP TABLE #DEL

GO
