-- Object: PROCEDURE dbo.CLS_CLOSING_RATE
-- Server: 10.253.33.91 | DB: MSAJAG
--------------------------------------------------



CREATE PROC [dbo].[CLS_CLOSING_RATE]  
 (  
	@FRMDATE VARCHAR(10),  
	@TODATE  VARCHAR(10),
	@SCRIPCD VARCHAR(20)
 )  
   
 AS  
  
 --EXEC CLS_CLOSING_RATE '01/05/2013','31/12/2014' ,'' 
   
 DECLARE @R_FRMDATE VARCHAR(11),  
   @R_TODATE VARCHAR(11)  
   
 SELECT @R_FRMDATE = CONVERT(VARCHAR,CONVERT(DATETIME,@FRMDATE,103),109)  
 SELECT @R_TODATE = CONVERT(VARCHAR,CONVERT(DATETIME,@TODATE,103),109)  
   
 SELECT  
	MARKET,SCRIP_CD,
	SERIES,
	[DATE]=CONVERT(VARCHAR(11),SYSDATE,103),
	CL_RATE,
	PRE_CL_RATE,OPEN_RATE,HI_RATE,
	LOW_RATE,TOT_TRADE_QTY=TOTTRDQTY,TOTAL_TURNOVER=TOTTURNOVER,
	YEAR_HIRATE=YEARHIRATE,YEAR_LOW_RATE=YEARLOWRATE
 FROM  
  CLOSING (NOLOCK)  
 WHERE  
  SYSDATE BETWEEN @R_FRMDATE AND @R_TODATE + ' 23:59' 
  AND SCRIP_CD = CASE WHEN @SCRIPCD ='' THEN SCRIP_CD ELSE @SCRIPCD END
 ORDER BY    
  SYSDATE,SCRIP_CD,SERIES

GO
