-- Object: PROCEDURE dbo.CLS_RPT_TRANSSTATEMENTBEN
-- Server: 10.253.33.91 | DB: MSAJAG
--------------------------------------------------




CREATE PROC [dbo].[CLS_RPT_TRANSSTATEMENTBEN]                     
(@FROMDATE VARCHAR(11), 
@TODATE VARCHAR(11), 
@FROMPARTY VARCHAR(10), 
@TOPARTY VARCHAR(10), 
@FROMSCRIP VARCHAR(12), 
@TOSCRIP VARCHAR(12),                    
@CLTDPID VARCHAR(16), 
@DPID VARCHAR(10), 
@FLAGOPTION VARCHAR(10), 
@STATUSID VARCHAR(50), 
@STATUSNAME VARCHAR(50),
@REPORTFLAG varchar(5)
)                    
AS 
-- exec CLS_RPT_TRANSSTATEMENTBEN   '01/01/2008' , '01/01/2018', '0A146',  '0A146','ANDHRSUGAR', 'ANDHRSUGAR',  '12010900' ,'1201090000011183','S','Broker','broker',''
DECLARE @NEWFROMDATE VARCHAR(11)        
        
SELECT @NEWFROMDATE = 'APR  1 1950'        
 
  DECLARE @FLAG INT

SET @FLAG = 0
 IF @FLAGOPTION='P'
SET @FLAG = 1

IF @FROMDATE LIKE '%/%'
BEGIN
SELECT @FROMDATE=CONVERT(VARCHAR(11),CONVERT( DATETIME ,@FROMDATE,103),109)
SELECT @TODATE=CONVERT(VARCHAR(11),CONVERT( DATETIME ,@TODATE,103),109)
END

       
IF LEN(@DPID) < 8               
 SELECT @DPID = 'AAAA'              
              
IF LEN(@CLTDPID) < 8               
 SELECT @CLTDPID = 'AAAA'              
        

SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED                      
SELECT * INTO #DEL_TRANSSTAT FROM DELTRANS_REPORT WITH(NOLOCK)                       
WHERE PARTY_CODE >= @FROMPARTY AND PARTY_CODE <= @TOPARTY                      
AND SCRIP_CD >= @FROMSCRIP AND SCRIP_CD <= @TOSCRIP                      
AND TRANSDATE >= @NEWFROMDATE AND TRANSDATE <= @TODATE                      
          
CREATE           
  INDEX [DELHOLD] ON [DBO].[#DEL_TRANSSTAT] ([TRANSDATE], [PARTY_CODE], [SCRIP_CD], [HOLDERNAME], [DRCR], [BDPTYPE], [BDPID], [BCLTDPID])          
          
          
IF @FLAG = 1                     
BEGIN                    
 SELECT  TRANSDATE=CONVERT(VARCHAR,TRANSDATE,103), SETT_NO, SETT_TYPE, D.PARTY_CODE, C1.LONG_NAME,                     
  C1.L_ADDRESS1, C1.L_ADDRESS2, C1.L_ADDRESS3, C1.L_CITY, C1.L_STATE, C1.L_ZIP, C1.FAMILY,                    
  D.SCRIP_CD, SCRIP_NAME = D.SCRIP_CD+'( ' + CERTNO + ')', CERTNO, CQTY = SUM(QTY), DQTY = 0, SLIPNO, DPID=BDPID, CLTDPID=BCLTDPID, TRTYPE,                     
  REASON = (CASE WHEN HOLDERNAME LIKE 'MARGIN%' OR ACCOUNTTYPE = 'MAR' THEN 'MARGIN RELEASED' ELSE 'TRANS TO BEN' END),                    
   BDPID, BCLTDPID, TRANSDATE1 = TRANSDATE,FLAG=1                    
 INTO #DEL_TRANSSTAT_1        
 FROM  #DEL_TRANSSTAT D, DELIVERYDP DP,                      
  CLIENT2 C2,                     
  CLIENT1 C1                    
 WHERE  DRCR = 'D'                     
 AND  SHARETYPE <> 'AUCTION'                     
 AND  CERTNO LIKE 'IN%'                    
 AND  DELIVERED = 'G'                     
 AND  FILLER2 = 0                     
 AND  C2.CL_CODE = C1.CL_CODE                     
 AND  C2.PARTY_CODE = D.PARTY_CODE                     
 AND  TRANSDATE >= @NEWFROMDATE                     
 AND  TRANSDATE <= @TODATE                    
 AND  D.PARTY_CODE >= @FROMPARTY                     
 AND  D.PARTY_CODE <= @TOPARTY                    
 AND  D.SCRIP_CD >= @FROMSCRIP AND D.SCRIP_CD <= @TOSCRIP                    
 AND  HOLDERNAME LIKE '%' + RTRIM(LTRIM(@CLTDPID)) + '%'                    
 AND HOLDERNAME NOT LIKE 'MARGIN%'                        
 AND DP.DPID = BDPID AND DP.DPCLTNO = BCLTDPID              
 AND  C1.BRANCH_CD LIKE  (CASE WHEN @STATUSID = 'BRANCH'   THEN @STATUSNAME ELSE '%' END)                    
 AND  C1.SUB_BROKER LIKE  (CASE WHEN @STATUSID = 'SUBBROKER'  THEN @STATUSNAME ELSE '%' END)                    
 AND  C1.TRADER LIKE   (CASE WHEN @STATUSID = 'TRADER'   THEN @STATUSNAME ELSE '%' END)                    
 AND  C1.FAMILY LIKE   (CASE WHEN @STATUSID = 'FAMILY'   THEN @STATUSNAME ELSE '%' END)                    
 AND  C2.PARTY_CODE LIKE  (CASE WHEN @STATUSID = 'CLIENT'   THEN @STATUSNAME ELSE '%' END)                     
 GROUP BY TRANSDATE, SETT_NO, SETT_TYPE, D.PARTY_CODE, C1.LONG_NAME,                     
  C1.L_ADDRESS1, C1.L_ADDRESS2, C1.L_ADDRESS3, C1.L_CITY, C1.L_STATE, C1.L_ZIP, C1.FAMILY,                    
  D.SCRIP_CD, CERTNO, SLIPNO, ACCOUNTTYPE, TRTYPE, ISETT_NO, ISETT_TYPE, BDPID, BCLTDPID, HOLDERNAME                      
                    
 UNION ALL 
         
 SELECT  TRANSDATE=CONVERT(VARCHAR,TRANSDATE,103), SETT_NO, SETT_TYPE, D.PARTY_CODE, C1.LONG_NAME,                     
  C1.L_ADDRESS1, C1.L_ADDRESS2, C1.L_ADDRESS3, C1.L_CITY, C1.L_STATE, C1.L_ZIP, C1.FAMILY,                    
  D.SCRIP_CD, SCRIP_NAME = D.SCRIP_CD+'( ' + CERTNO + ')', CERTNO, CQTY = SUM(QTY), DQTY = 0, SLIPNO, DPID=D.DPID, CLTDPID=D.CLTDPID, TRTYPE,            
  REASON = (CASE WHEN ACCOUNTTYPE = 'MAR' THEN 'MARGIN REC' ELSE REASON END), BDPID, BCLTDPID, TRANSDATE1 = TRANSDATE,FLAG=2                      
 FROM  #DEL_TRANSSTAT D, DELIVERYDP DP,                     
  CLIENT2 C2,                  
  CLIENT1 C1                    
 WHERE  DRCR = 'C'                     
 AND  SHARETYPE <> 'AUCTION'                     
 AND  CERTNO LIKE 'IN%'                    
 /*AND DELIVERED = '0'*/ AND FILLER2 = 1                     
 AND  C2.CL_CODE = C1.CL_CODE                     
 AND  C2.PARTY_CODE = D.PARTY_CODE                     
 AND  TRANSDATE >= @NEWFROMDATE                     
 AND  TRANSDATE <= @TODATE                    
 AND  D.PARTY_CODE >= @FROMPARTY                     
 AND  D.PARTY_CODE <= @TOPARTY                    
 AND  D.SCRIP_CD >= @FROMSCRIP                     
 AND  D.SCRIP_CD <= @TOSCRIP                    
 AND BDPID = @DPID AND BCLTDPID = @CLTDPID     
 AND DP.DPID = BDPID AND DP.DPCLTNO = BCLTDPID                
 /*AND SETT_NO = '2000000' */ AND FILLER1 NOT IN ('SPLIT','BONUS')                    
 AND  C1.BRANCH_CD LIKE  (CASE WHEN @STATUSID = 'BRANCH'   THEN @STATUSNAME ELSE '%' END)                    
 AND  C1.SUB_BROKER LIKE  (CASE WHEN @STATUSID = 'SUBBROKER'  THEN @STATUSNAME ELSE '%' END)                    
 AND  C1.TRADER LIKE   (CASE WHEN @STATUSID = 'TRADER'   THEN @STATUSNAME ELSE '%' END)                    
 AND  C1.FAMILY LIKE   (CASE WHEN @STATUSID = 'FAMILY'   THEN @STATUSNAME ELSE '%' END)                    
 AND  C2.PARTY_CODE LIKE  (CASE WHEN @STATUSID = 'CLIENT'   THEN @STATUSNAME ELSE '%' END)                     
 GROUP BY TRANSDATE, SETT_NO, SETT_TYPE, D.PARTY_CODE, C1.LONG_NAME,                     
  C1.L_ADDRESS1, C1.L_ADDRESS2, C1.L_ADDRESS3, C1.L_CITY, C1.L_STATE, C1.L_ZIP, C1.FAMILY,                    
  D.SCRIP_CD, CERTNO, SLIPNO, ACCOUNTTYPE, D.DPID, CLTDPID, TRTYPE, ISETT_NO, ISETT_TYPE, BDPID, BCLTDPID ,REASON                    
                    
 UNION ALL               
                    
 SELECT  TRANSDATE=CONVERT(VARCHAR,TRANSDATE,103), SETT_NO, SETT_TYPE, D.PARTY_CODE, C1.LONG_NAME,                     
  C1.L_ADDRESS1, C1.L_ADDRESS2, C1.L_ADDRESS3, C1.L_CITY, C1.L_STATE, C1.L_ZIP, C1.FAMILY,                    
  D.SCRIP_CD, SCRIP_NAME = D.SCRIP_CD+'( ' + CERTNO + ')', CERTNO, CQTY = SUM(QTY), DQTY = 0, SLIPNO=0, DPID='', CLTDPID='', TRTYPE,                     
  REASON = (CASE WHEN ACCOUNTTYPE = 'MAR' THEN 'MARGIN REC' ELSE REASON END), BDPID, BCLTDPID, TRANSDATE1 = TRANSDATE,FLAG=3                      
 FROM  #DEL_TRANSSTAT D, DELIVERYDP DP, CLIENT2 C2, CLIENT1 C1                    
 WHERE  DRCR = 'C'                     
 AND  SHARETYPE <> 'AUCTION'                     
 AND  CERTNO LIKE 'IN%'                    
 AND  DELIVERED = '0'                     
 AND  FILLER2 = 1                     
 AND  C2.CL_CODE = C1.CL_CODE                     
 AND  C2.PARTY_CODE = D.PARTY_CODE                     
 AND  TRANSDATE >= @NEWFROMDATE                     
 AND  TRANSDATE <= @TODATE                    
 AND  D.PARTY_CODE >= @FROMPARTY                     
 AND  D.PARTY_CODE <= @TOPARTY                    
 AND  D.SCRIP_CD >= @FROMSCRIP                     
 AND  D.SCRIP_CD <= @TOSCRIP                    
 AND BDPID = @DPID AND BCLTDPID = @CLTDPID    
 AND DP.DPID = BDPID AND DP.DPCLTNO = BCLTDPID                 
 AND  FILLER1 IN ('SPLIT','BONUS')                    
 AND  C1.BRANCH_CD LIKE  (CASE WHEN @STATUSID = 'BRANCH'   THEN @STATUSNAME ELSE '%' END)                    
 AND  C1.SUB_BROKER LIKE  (CASE WHEN @STATUSID = 'SUBBROKER'  THEN @STATUSNAME ELSE '%' END)                    
 AND  C1.TRADER LIKE   (CASE WHEN @STATUSID = 'TRADER'   THEN @STATUSNAME ELSE '%' END)                    
 AND  C1.FAMILY LIKE   (CASE WHEN @STATUSID = 'FAMILY'   THEN @STATUSNAME ELSE '%' END)                    
 AND  C2.PARTY_CODE LIKE  (CASE WHEN @STATUSID = 'CLIENT'   THEN @STATUSNAME ELSE '%' END)                     
 GROUP BY TRANSDATE, SETT_NO, SETT_TYPE, D.PARTY_CODE, C1.LONG_NAME,                     
  C1.L_ADDRESS1, C1.L_ADDRESS2, C1.L_ADDRESS3, C1.L_CITY, C1.L_STATE, C1.L_ZIP, C1.FAMILY,                    
  D.SCRIP_CD, CERTNO, SLIPNO, ACCOUNTTYPE, TRTYPE, ISETT_NO, ISETT_TYPE, BDPID, BCLTDPID ,REASON                    
                    
 UNION ALL
         
 SELECT  TRANSDATE=CONVERT(VARCHAR,TRANSDATE,103), SETT_NO, SETT_TYPE, D.PARTY_CODE, C1.LONG_NAME,                    
  C1.L_ADDRESS1, C1.L_ADDRESS2, C1.L_ADDRESS3, C1.L_CITY, C1.L_STATE, C1.L_ZIP, C1.FAMILY,                  
  D.SCRIP_CD, SCRIP_NAME = D.SCRIP_CD+'( ' + CERTNO + ')', CERTNO, CQTY = 0,     
  DQTY = SUM(QTY), SLIPNO=(CASE WHEN FILLER1 = 'SPLIT' THEN 0 ELSE SLIPNO END),                     
  DPID =  (CASE  WHEN TRTYPE IN (1000,907,908)  THEN ''                     
            WHEN FILLER1 = 'SPLIT'    THEN ''                    
            WHEN FILLER1 LIKE 'CHANGE TO%'  THEN ''                      
           ELSE D.DPID END),                     
  CLTDPID = (CASE  WHEN TRTYPE IN (1000,907,908)  THEN ''                     
    WHEN FILLER1 = 'SPLIT'    THEN ''                   
                         WHEN FILLER1 LIKE 'CHANGE TO%'  THEN ''                    
      ELSE D.CLTDPID                     
      END),                    
  TRTYPE,                     
  REASON =  (CASE  WHEN TRTYPE IN (1000,907,908)  THEN 'TRANS TO POOL - ' + ISETT_NO + '-' + ISETT_TYPE                     
           ELSE                     
    (CASE  WHEN FILLER1 = 'SPLIT'    THEN 'CORPORATE ACTION'                     
                WHEN FILLER1 LIKE 'CHANGE TO%'      THEN FILLER1                    
              ELSE                     
    (CASE WHEN ACCOUNTTYPE = 'MAR' THEN 'MARGIN RELEASE'           
    ELSE  REASON                     
    END)                     
    END)                    
    END),                     
  BDPID, BCLTDPID, TRANSDATE1 = TRANSDATE,FLAG=4                      
 FROM  #DEL_TRANSSTAT D, DELIVERYDP DP,                    
  CLIENT2 C2,                     
  CLIENT1 C1                    
 WHERE  FILLER2 = 1                     
 AND  DRCR = 'D'                     
 AND  DELIVERED <> '0'                     
 AND  SHARETYPE <> 'AUCTION'                     
 AND  CERTNO LIKE 'IN%'                    
 AND  C2.CL_CODE = C1.CL_CODE                     
 AND  C2.PARTY_CODE = D.PARTY_CODE                     
 AND  TRANSDATE >= @NEWFROMDATE                     
 AND  TRANSDATE <= @TODATE                    
 AND  D.PARTY_CODE >= @FROMPARTY                     
 AND  D.PARTY_CODE <= @TOPARTY                    
 AND  D.SCRIP_CD >= @FROMSCRIP                     
 AND  D.SCRIP_CD <= @TOSCRIP                    
 AND BDPID = @DPID AND BCLTDPID = @CLTDPID    
 AND DP.DPID = BDPID AND DP.DPCLTNO = BCLTDPID                
 AND  C1.BRANCH_CD LIKE  (CASE WHEN @STATUSID = 'BRANCH'   THEN @STATUSNAME ELSE '%' END)                    
 AND  C1.SUB_BROKER LIKE  (CASE WHEN @STATUSID = 'SUBBROKER'  THEN @STATUSNAME ELSE '%' END)                    
 AND  C1.TRADER LIKE   (CASE WHEN @STATUSID = 'TRADER'   THEN @STATUSNAME ELSE '%' END)                    
 AND  C1.FAMILY LIKE   (CASE WHEN @STATUSID = 'FAMILY'   THEN @STATUSNAME ELSE '%' END)                    
 AND  C2.PARTY_CODE LIKE  (CASE WHEN @STATUSID = 'CLIENT'   THEN @STATUSNAME ELSE '%' END)                     
 AND  HOLDERNAME NOT LIKE 'MARGIN%'                    
 GROUP BY TRANSDATE, SETT_NO, SETT_TYPE, D.PARTY_CODE, C1.LONG_NAME,                     
  C1.L_ADDRESS1, C1.L_ADDRESS2, C1.L_ADDRESS3, C1.L_CITY, C1.L_STATE, C1.L_ZIP, C1.FAMILY,                    
  D.SCRIP_CD, CERTNO, SLIPNO, ACCOUNTTYPE, D.DPID, D.CLTDPID, TRTYPE, ISETT_NO, ISETT_TYPE, BDPID, BCLTDPID , FILLER1, REASON                    
                    
 UNION ALL 
        
 SELECT  TRANSDATE=CONVERT(VARCHAR,TRANSDATE,103), SETT_NO, SETT_TYPE, D.PARTY_CODE, C1.LONG_NAME,                     
  C1.L_ADDRESS1, C1.L_ADDRESS2, C1.L_ADDRESS3, C1.L_CITY, C1.L_STATE, C1.L_ZIP, C1.FAMILY,                    
  D.SCRIP_CD, SCRIP_NAME = D.SCRIP_CD+'( ' + CERTNO + ')', CERTNO, CQTY = 0, DQTY = SUM(QTY), SLIPNO, DPID=DP.DPID, CLTDPID=DP.DPCLTNO, TRTYPE,                     
  REASON = (CASE WHEN HOLDERNAME LIKE 'MARGIN%' OR ACCOUNTTYPE = 'MAR' THEN 'TRANS TO MARGIN' ELSE 'TRANS TO BEN' END),                    
   BDPID, BCLTDPID, TRANSDATE1 = TRANSDATE,FLAG=1                    
 FROM  #DEL_TRANSSTAT D,    
  CLIENT2 C2,                     
  CLIENT1 C1,                     
  DELIVERYDP DP                    
 WHERE  DRCR = 'D'                     
 AND  SHARETYPE <> 'AUCTION'                     
 AND  CERTNO LIKE 'IN%'                    
 AND  DELIVERED = 'G'                     
 AND  FILLER2 = 0                     
 AND  C2.CL_CODE = C1.CL_CODE                     
 AND  C2.PARTY_CODE = D.PARTY_CODE                     
 AND  TRANSDATE >= @NEWFROMDATE                     
 AND  TRANSDATE <= @TODATE                    
 AND  D.PARTY_CODE >= @FROMPARTY                     
 AND  D.PARTY_CODE <= @TOPARTY                    
 AND  D.SCRIP_CD >= @FROMSCRIP                     
 AND  D.SCRIP_CD <= @TOSCRIP                    
 AND BDPID = @DPID AND BCLTDPID = @CLTDPID                 
 AND DESCRIPTION NOT LIKE '%POOL%'                  
 AND  (HOLDERNAME LIKE 'BEN ' + DP.DPCLTNO                     
  OR HOLDERNAME LIKE 'MARGIN ' + DP.DPCLTNO)                   
 AND  C1.BRANCH_CD LIKE  (CASE WHEN @STATUSID = 'BRANCH'   THEN @STATUSNAME ELSE '%' END)                    
 AND  C1.SUB_BROKER LIKE  (CASE WHEN @STATUSID = 'SUBBROKER'  THEN @STATUSNAME ELSE '%' END)                    
 AND  C1.TRADER LIKE   (CASE WHEN @STATUSID = 'TRADER'   THEN @STATUSNAME ELSE '%' END)                    
 AND  C1.FAMILY LIKE   (CASE WHEN @STATUSID = 'FAMILY'   THEN @STATUSNAME ELSE '%' END)                    
 AND  C2.PARTY_CODE LIKE  (CASE WHEN @STATUSID = 'CLIENT'   THEN @STATUSNAME ELSE '%' END)                     
 GROUP BY TRANSDATE, SETT_NO, SETT_TYPE, D.PARTY_CODE, C1.LONG_NAME,                     
  C1.L_ADDRESS1, C1.L_ADDRESS2, C1.L_ADDRESS3, C1.L_CITY, C1.L_STATE, C1.L_ZIP, C1.FAMILY,                   
  D.SCRIP_CD, CERTNO, SLIPNO, TRTYPE, ACCOUNTTYPE, DP.DPID, DPCLTNO , ISETT_NO, ISETT_TYPE, BDPID, BCLTDPID, HOLDERNAME                      
  
          
 SELECT TRANSDATE=CONVERT(VARCHAR,CONVERT(DATETIME,@FROMDATE),103),        
 SETT_NO='',SETT_TYPE='',PARTY_CODE,LONG_NAME,L_ADDRESS1,L_ADDRESS2,L_ADDRESS3,L_CITY,L_STATE,        
 L_ZIP,FAMILY,SCRIP_CD,SCRIP_NAME,CERTNO,        
 CQTY=(CASE WHEN SUM(CQTY-DQTY) > 0 THEN SUM(CQTY-DQTY) ELSE 0 END),        
 DQTY=(CASE WHEN SUM(DQTY-CQTY) > 0 THEN SUM(DQTY-CQTY) ELSE 0 END),        
 SLIPNO='0',DPID='',CLTDPID='',TRTYPE='0',REASON='OPENING BALANCE',BDPID='',BCLTDPID='',        
 TRANSDATE1=CONVERT(DATETIME,@FROMDATE),FLAG=0
 INTO #DEL_TRANSSTAT_3        
 FROM #DEL_TRANSSTAT_1 D1    
 WHERE TRANSDATE1 < @FROMDATE  
 
 GROUP BY PARTY_CODE,LONG_NAME,L_ADDRESS1,L_ADDRESS2,L_ADDRESS3,L_CITY,L_STATE,        
 L_ZIP,FAMILY,SCRIP_CD,SCRIP_NAME,CERTNO
 HAVING SUM(DQTY-CQTY) <> 0 
         
 UNION ALL 
        
 SELECT * FROM  #DEL_TRANSSTAT_1        
 WHERE TRANSDATE1 >= @FROMDATE AND TRANSDATE1 <= @TODATE 
        
 UNION ALL 
        
 SELECT TRANSDATE=CONVERT(VARCHAR,CONVERT(DATETIME,@TODATE),103),        
 SETT_NO='',SETT_TYPE='',PARTY_CODE,LONG_NAME,L_ADDRESS1,L_ADDRESS2,L_ADDRESS3,L_CITY,L_STATE,        
 L_ZIP,FAMILY,SCRIP_CD,SCRIP_NAME,CERTNO,        
 CQTY=(CASE WHEN SUM(CQTY-DQTY) > 0 THEN SUM(CQTY-DQTY) ELSE 0 END),        
 DQTY=(CASE WHEN SUM(DQTY-CQTY) > 0 THEN SUM(DQTY-CQTY) ELSE 0 END),        
 SLIPNO='0',DPID='',CLTDPID='',TRTYPE='0',REASON='CLOSING BALANCE',BDPID='',BCLTDPID='',        
 TRANSDATE1=CONVERT(DATETIME,@TODATE),FLAG=6        
 FROM #DEL_TRANSSTAT_1 D1    
 WHERE TRANSDATE1 <= @TODATE    
 AND EXISTS (SELECT PARTY_CODE FROM #DEL_TRANSSTAT_1 D2     
    WHERE D1.PARTY_CODE = D2.PARTY_CODE AND D1.CERTNO = D2.CERTNO     
    AND TRANSDATE1 >= @FROMDATE AND TRANSDATE1 <= @TODATE)    
 GROUP BY PARTY_CODE,LONG_NAME,L_ADDRESS1,L_ADDRESS2,L_ADDRESS3,L_CITY,L_STATE,        
 L_ZIP,FAMILY,SCRIP_CD,SCRIP_NAME,CERTNO        
 ORDER BY PARTY_CODE, SCRIP_CD, CERTNO, TRANSDATE1, FLAG, SETT_NO, SETT_TYPE 
 

 IF(@REPORTFLAG='C')
 BEGIN
	 SELECT PARTYCODE=PARTY_CODE,SCRIPNAME=SCRIP_CD+' : '+SCRIP_NAME,TRANSDATE,SETT_NO,SETT_TYPE,LONG_NAME,L_ADDRESS1,L_ADDRESS2,L_ADDRESS3,L_CITY,L_STATE,L_ZIP,FAMILY,CERTNO,CQTY,DQTY,SLIPNO,DPID,CLTDPID,TRTYPE,REASON,BDPID,BCLTDPID  
	 FROM #DEL_TRANSSTAT_3
	 WHERE  PARTY_CODE<>''
	 ORDER BY PARTY_CODE, SCRIP_CD, CERTNO, TRANSDATE1, FLAG, SETT_NO, SETT_TYPE
 END
 ELSE
 BEGIN
	 INSERT INTO #DEL_TRANSSTAT_3
	 SELECT DISTINCT TRANSDATE='01/01/2049',SETT_NO='',SETT_TYPE='',PARTY_CODE,LONG_NAME='',L_ADDRESS1='',L_ADDRESS2='',L_ADDRESS3='',L_CITY='',L_STATE='',L_ZIP='',FAMILY='',SCRIP_CD='',SCRIP_NAME=''
	 ,CERTNO='',CQTY='0.00',DQTY='0.00',0,DPID='',CLTDPID='',TRTYPE=0,REASON='',BDPID='',BCLTDPID='',TRANSDATE1='01/01/2049',0
	 FROM #DEL_TRANSSTAT_3
	 GROUP BY TRANSDATE,PARTY_CODE,LONG_NAME,L_ADDRESS1,L_ADDRESS2,L_ADDRESS3,L_CITY,L_STATE,L_ZIP,FAMILY,SLIPNO ,TRTYPE,FLAG,CQTY,DQTY,TRANSDATE1
 
	 INSERT INTO #DEL_TRANSSTAT_3
	  SELECT DISTINCT TRANSDATE='01/01/2049',SETT_NO='',SETT_TYPE='',PARTY_CODE,LONG_NAME='',L_ADDRESS1='',L_ADDRESS2='',L_ADDRESS3='',L_CITY='',L_STATE='',L_ZIP='',FAMILY='',SCRIP_CD,SCRIP_NAME
	 ,CERTNO='',CQTY='0.00',DQTY='0.00',0,DPID='',CLTDPID='',TRTYPE=0,REASON='',BDPID='',BCLTDPID='',TRANSDATE1='01/01/2049',0
	 FROM #DEL_TRANSSTAT_3
	 WHERE SCRIP_CD <>'' AND SCRIP_NAME<>''

	 SELECT TRANSDATE,SETT_NO,SETT_TYPE,PARTY_CODE,LONG_NAME,L_ADDRESS1,L_ADDRESS2,L_ADDRESS3,L_CITY,L_STATE,L_ZIP,FAMILY,SCRIP_NAME,SCRIP_CD,CERTNO,CQTY,DQTY,SLIPNO,DPID,CLTDPID,TRTYPE,REASON,BDPID,BCLTDPID,TRANSDATE1,FLAG  
	 FROM #DEL_TRANSSTAT_3
	 WHERE  PARTY_CODE<>''
	 ORDER BY PARTY_CODE, SCRIP_CD, CERTNO, TRANSDATE1, FLAG, SETT_NO, SETT_TYPE
 END 
        
END                    
ELSE                    
BEGIN  
                  
 SELECT  TRANSDATE=CONVERT(VARCHAR,TRANSDATE,103), SETT_NO, SETT_TYPE, D.PARTY_CODE, C1.LONG_NAME,                     
  C1.L_ADDRESS1, C1.L_ADDRESS2, C1.L_ADDRESS3, C1.L_CITY, C1.L_STATE, C1.L_ZIP, C1.FAMILY,                    
  D.SCRIP_CD, SCRIP_NAME = D.SCRIP_CD+'( ' + CERTNO + ')', CERTNO, CQTY = SUM(QTY), DQTY = 0, SLIPNO, DPID=BDPID, CLTDPID=BCLTDPID, TRTYPE,                     
  REASON = (CASE WHEN HOLDERNAME LIKE 'MARGIN%' OR ACCOUNTTYPE = 'MAR' THEN 'MARGIN RELEASED' ELSE 'TRANS TO BEN' END),                    
   BDPID, BCLTDPID, TRANSDATE1 = TRANSDATE,FLAG=1                    
 INTO #DEL_TRANSSTAT_2       
 FROM  #DEL_TRANSSTAT D, DELIVERYDP DP,                      
  CLIENT2 C2,                     
  CLIENT1 C1                    
 WHERE  DRCR = 'D'                     
 AND  SHARETYPE <> 'AUCTION'                     
 AND  CERTNO LIKE 'IN%'                    
 AND  DELIVERED = 'G'                     
 AND  FILLER2 = 0                     
 AND  C2.CL_CODE = C1.CL_CODE                     
 AND  C2.PARTY_CODE = D.PARTY_CODE                     
 AND  TRANSDATE >= @NEWFROMDATE                     
 AND  TRANSDATE <= @TODATE                    
 AND  D.PARTY_CODE >= @FROMPARTY                     
 AND  D.PARTY_CODE <= @TOPARTY                    
 AND  D.SCRIP_CD >= @FROMSCRIP AND D.SCRIP_CD <= @TOSCRIP                    
 AND  HOLDERNAME LIKE '%' + RTRIM(LTRIM(@CLTDPID)) + '%'                    
 AND HOLDERNAME NOT LIKE 'MARGIN%'                        
 AND DP.DPID = BDPID AND DP.DPCLTNO = BCLTDPID    
 --AND SETT_NO <> '2000000'                    
 AND  C1.BRANCH_CD LIKE  (CASE WHEN @STATUSID = 'BRANCH'   THEN @STATUSNAME ELSE '%' END)                    
 AND  C1.SUB_BROKER LIKE  (CASE WHEN @STATUSID = 'SUBBROKER'  THEN @STATUSNAME ELSE '%' END)                    
 AND  C1.TRADER LIKE   (CASE WHEN @STATUSID = 'TRADER'   THEN @STATUSNAME ELSE '%' END)                    
 AND  C1.FAMILY LIKE   (CASE WHEN @STATUSID = 'FAMILY'   THEN @STATUSNAME ELSE '%' END)                    
 AND  C2.PARTY_CODE LIKE  (CASE WHEN @STATUSID = 'CLIENT'   THEN @STATUSNAME ELSE '%' END)                     
 GROUP BY TRANSDATE, SETT_NO, SETT_TYPE, D.PARTY_CODE, C1.LONG_NAME,                     
  C1.L_ADDRESS1, C1.L_ADDRESS2, C1.L_ADDRESS3, C1.L_CITY, C1.L_STATE, C1.L_ZIP, C1.FAMILY,                    
  D.SCRIP_CD, CERTNO, SLIPNO, ACCOUNTTYPE, TRTYPE, ISETT_NO, ISETT_TYPE, BDPID, BCLTDPID, HOLDERNAME                      
                    
 UNION ALL  
        
 SELECT  TRANSDATE=CONVERT(VARCHAR,TRANSDATE,103), SETT_NO, SETT_TYPE, D.PARTY_CODE, C1.LONG_NAME,                     
  C1.L_ADDRESS1, C1.L_ADDRESS2, C1.L_ADDRESS3, C1.L_CITY, C1.L_STATE, C1.L_ZIP, C1.FAMILY,                    
  D.SCRIP_CD, SCRIP_NAME = D.SCRIP_CD+'( ' + CERTNO + ')', CERTNO, CQTY = SUM(QTY), DQTY = 0, SLIPNO, DPID=D.DPID, CLTDPID=D.CLTDPID, TRTYPE,            
  REASON = (CASE WHEN ACCOUNTTYPE = 'MAR' THEN 'MARGIN REC' ELSE REASON END), BDPID, BCLTDPID, TRANSDATE1 = TRANSDATE,FLAG=2                      
 FROM  #DEL_TRANSSTAT D, DELIVERYDP DP,                     
  CLIENT2 C2,                  
  CLIENT1 C1                    
 WHERE  DRCR = 'C'                     
 AND  SHARETYPE <> 'AUCTION'                     
 AND  CERTNO LIKE 'IN%'                    
 /*AND DELIVERED = '0'*/ AND FILLER2 = 1                     
 AND  C2.CL_CODE = C1.CL_CODE                     
 AND  C2.PARTY_CODE = D.PARTY_CODE                     
 AND  TRANSDATE >= @NEWFROMDATE                     
 AND  TRANSDATE <= @TODATE                    
 AND  D.PARTY_CODE >= @FROMPARTY                     
 AND  D.PARTY_CODE <= @TOPARTY                    
 AND  D.SCRIP_CD >= @FROMSCRIP                     
 AND  D.SCRIP_CD <= @TOSCRIP                    
 AND BDPID = @DPID AND BCLTDPID = @CLTDPID     
 AND DP.DPID = BDPID AND DP.DPCLTNO = BCLTDPID                
 /*AND SETT_NO = '2000000' */ AND FILLER1 NOT IN ('SPLIT','BONUS')                    
 AND  C1.BRANCH_CD LIKE  (CASE WHEN @STATUSID = 'BRANCH'   THEN @STATUSNAME ELSE '%' END)                    
 AND  C1.SUB_BROKER LIKE  (CASE WHEN @STATUSID = 'SUBBROKER'  THEN @STATUSNAME ELSE '%' END)                    
 AND  C1.TRADER LIKE   (CASE WHEN @STATUSID = 'TRADER'   THEN @STATUSNAME ELSE '%' END)                    
 AND  C1.FAMILY LIKE   (CASE WHEN @STATUSID = 'FAMILY'   THEN @STATUSNAME ELSE '%' END)                    
 AND  C2.PARTY_CODE LIKE  (CASE WHEN @STATUSID = 'CLIENT'   THEN @STATUSNAME ELSE '%' END)                     
 GROUP BY TRANSDATE, SETT_NO, SETT_TYPE, D.PARTY_CODE, C1.LONG_NAME,                     
  C1.L_ADDRESS1, C1.L_ADDRESS2, C1.L_ADDRESS3, C1.L_CITY, C1.L_STATE, C1.L_ZIP, C1.FAMILY,                    
  D.SCRIP_CD, CERTNO, SLIPNO, ACCOUNTTYPE, D.DPID, CLTDPID, TRTYPE, ISETT_NO, ISETT_TYPE, BDPID, BCLTDPID ,REASON                    
                    
 UNION ALL               
                    
 SELECT  TRANSDATE=CONVERT(VARCHAR,TRANSDATE,103), SETT_NO, SETT_TYPE, D.PARTY_CODE, C1.LONG_NAME,                     
  C1.L_ADDRESS1, C1.L_ADDRESS2, C1.L_ADDRESS3, C1.L_CITY, C1.L_STATE, C1.L_ZIP, C1.FAMILY,                    
  D.SCRIP_CD, SCRIP_NAME = D.SCRIP_CD+'( ' + CERTNO + ')', CERTNO, CQTY = SUM(QTY), DQTY = 0, SLIPNO=0, DPID='', CLTDPID='', TRTYPE,                     
  REASON = (CASE WHEN ACCOUNTTYPE = 'MAR' THEN 'MARGIN REC' ELSE REASON END), BDPID, BCLTDPID, TRANSDATE1 = TRANSDATE,FLAG=3                      
 FROM  #DEL_TRANSSTAT D, DELIVERYDP DP, CLIENT2 C2, CLIENT1 C1                    
 WHERE  DRCR = 'C'                     
 AND  SHARETYPE <> 'AUCTION'                     
 AND  CERTNO LIKE 'IN%'                    
 AND  DELIVERED = '0'                     
 AND  FILLER2 = 1                     
 AND  C2.CL_CODE = C1.CL_CODE                     
 AND  C2.PARTY_CODE = D.PARTY_CODE                     
 AND  TRANSDATE >= @NEWFROMDATE                     
 AND  TRANSDATE <= @TODATE                    
 AND  D.PARTY_CODE >= @FROMPARTY                     
 AND  D.PARTY_CODE <= @TOPARTY                    
 AND  D.SCRIP_CD >= @FROMSCRIP                     
 AND  D.SCRIP_CD <= @TOSCRIP                    
 AND BDPID = @DPID AND BCLTDPID = @CLTDPID    
 AND DP.DPID = BDPID AND DP.DPCLTNO = BCLTDPID                 
 AND  FILLER1 IN ('SPLIT','BONUS')                    
 AND  C1.BRANCH_CD LIKE  (CASE WHEN @STATUSID = 'BRANCH'   THEN @STATUSNAME ELSE '%' END)                    
 AND  C1.SUB_BROKER LIKE  (CASE WHEN @STATUSID = 'SUBBROKER'  THEN @STATUSNAME ELSE '%' END)                    
 AND  C1.TRADER LIKE   (CASE WHEN @STATUSID = 'TRADER'   THEN @STATUSNAME ELSE '%' END)                    
 AND  C1.FAMILY LIKE   (CASE WHEN @STATUSID = 'FAMILY'   THEN @STATUSNAME ELSE '%' END)                    
 AND  C2.PARTY_CODE LIKE  (CASE WHEN @STATUSID = 'CLIENT'   THEN @STATUSNAME ELSE '%' END)                     
 GROUP BY TRANSDATE, SETT_NO, SETT_TYPE, D.PARTY_CODE, C1.LONG_NAME,                     
  C1.L_ADDRESS1, C1.L_ADDRESS2, C1.L_ADDRESS3, C1.L_CITY, C1.L_STATE, C1.L_ZIP, C1.FAMILY,                    
  D.SCRIP_CD, CERTNO, SLIPNO, ACCOUNTTYPE, TRTYPE, ISETT_NO, ISETT_TYPE, BDPID, BCLTDPID ,REASON                    
                    
 UNION ALL
         
 SELECT  TRANSDATE=CONVERT(VARCHAR,TRANSDATE,103), SETT_NO, SETT_TYPE, D.PARTY_CODE, C1.LONG_NAME,                    
  C1.L_ADDRESS1, C1.L_ADDRESS2, C1.L_ADDRESS3, C1.L_CITY, C1.L_STATE, C1.L_ZIP, C1.FAMILY,                  
  D.SCRIP_CD, SCRIP_NAME = D.SCRIP_CD+'( ' + CERTNO + ')', CERTNO, CQTY = 0,     
  DQTY = SUM(QTY), SLIPNO=(CASE WHEN FILLER1 = 'SPLIT' THEN 0 ELSE SLIPNO END),                     
  DPID =  (CASE  WHEN TRTYPE IN (1000,907,908)  THEN ''                     
            WHEN FILLER1 = 'SPLIT'    THEN ''                    
            WHEN FILLER1 LIKE 'CHANGE TO%'  THEN ''                      
           ELSE D.DPID END),                     
  CLTDPID = (CASE  WHEN TRTYPE IN (1000,907,908)  THEN ''                     
    WHEN FILLER1 = 'SPLIT'    THEN ''                   
                         WHEN FILLER1 LIKE 'CHANGE TO%'  THEN ''                    
      ELSE D.CLTDPID                     
      END),                    
  TRTYPE,                     
  REASON =  (CASE  WHEN TRTYPE IN (1000,907,908)  THEN 'TRANS TO POOL - ' + ISETT_NO + '-' + ISETT_TYPE                     
           ELSE                     
    (CASE  WHEN FILLER1 = 'SPLIT'    THEN 'CORPORATE ACTION'                     
                WHEN FILLER1 LIKE 'CHANGE TO%'      THEN FILLER1                    
              ELSE                     
    (CASE WHEN ACCOUNTTYPE = 'MAR' THEN 'MARGIN RELEASE'           
    ELSE  REASON                     
    END)                     
    END)                    
    END),                     
  BDPID, BCLTDPID, TRANSDATE1 = TRANSDATE,FLAG=4                      
 FROM  #DEL_TRANSSTAT D, DELIVERYDP DP,                    
  CLIENT2 C2,                     
  CLIENT1 C1                    
 WHERE  FILLER2 = 1                     
 AND  DRCR = 'D'                     
 AND  DELIVERED <> '0'                     
 AND  SHARETYPE <> 'AUCTION'                     
 AND  CERTNO LIKE 'IN%'                    
 AND  C2.CL_CODE = C1.CL_CODE                     
 AND  C2.PARTY_CODE = D.PARTY_CODE                     
 AND  TRANSDATE >= @NEWFROMDATE                     
 AND  TRANSDATE <= @TODATE                    
 AND  D.PARTY_CODE >= @FROMPARTY                     
 AND  D.PARTY_CODE <= @TOPARTY                    
 AND  D.SCRIP_CD >= @FROMSCRIP                     
 AND  D.SCRIP_CD <= @TOSCRIP                    
 AND BDPID = @DPID AND BCLTDPID = @CLTDPID    
 AND DP.DPID = BDPID AND DP.DPCLTNO = BCLTDPID                
 AND  C1.BRANCH_CD LIKE  (CASE WHEN @STATUSID = 'BRANCH'   THEN @STATUSNAME ELSE '%' END)                    
 AND  C1.SUB_BROKER LIKE  (CASE WHEN @STATUSID = 'SUBBROKER'  THEN @STATUSNAME ELSE '%' END)                    
 AND  C1.TRADER LIKE   (CASE WHEN @STATUSID = 'TRADER'   THEN @STATUSNAME ELSE '%' END)                    
 AND  C1.FAMILY LIKE   (CASE WHEN @STATUSID = 'FAMILY'   THEN @STATUSNAME ELSE '%' END)                    
 AND  C2.PARTY_CODE LIKE  (CASE WHEN @STATUSID = 'CLIENT'   THEN @STATUSNAME ELSE '%' END)                     
 AND  HOLDERNAME NOT LIKE 'MARGIN%'                    
 GROUP BY TRANSDATE, SETT_NO, SETT_TYPE, D.PARTY_CODE, C1.LONG_NAME,                     
  C1.L_ADDRESS1, C1.L_ADDRESS2, C1.L_ADDRESS3, C1.L_CITY, C1.L_STATE, C1.L_ZIP, C1.FAMILY,                    
  D.SCRIP_CD, CERTNO, SLIPNO, ACCOUNTTYPE, D.DPID, D.CLTDPID, TRTYPE, ISETT_NO, ISETT_TYPE, BDPID, BCLTDPID , FILLER1, REASON                    
                    
 UNION ALL 
        
 SELECT  TRANSDATE=CONVERT(VARCHAR,TRANSDATE,103), SETT_NO, SETT_TYPE, D.PARTY_CODE, C1.LONG_NAME,                     
  C1.L_ADDRESS1, C1.L_ADDRESS2, C1.L_ADDRESS3, C1.L_CITY, C1.L_STATE, C1.L_ZIP, C1.FAMILY,                    
  D.SCRIP_CD, SCRIP_NAME = D.SCRIP_CD+'( ' + CERTNO + ')', CERTNO, CQTY = 0, DQTY = SUM(QTY), SLIPNO, DPID=DP.DPID, CLTDPID=DP.DPCLTNO, TRTYPE,                     
  REASON = (CASE WHEN HOLDERNAME LIKE 'MARGIN%' OR ACCOUNTTYPE = 'MAR' THEN 'TRANS TO MARGIN' ELSE 'TRANS TO BEN' END),                    
   BDPID, BCLTDPID, TRANSDATE1 = TRANSDATE,FLAG=1                    
 FROM  #DEL_TRANSSTAT D,    
  CLIENT2 C2,                     
  CLIENT1 C1,                
  DELIVERYDP DP                    
 WHERE  DRCR = 'D'                     
 AND  SHARETYPE <> 'AUCTION'                     
 AND  CERTNO LIKE 'IN%'                    
 AND  DELIVERED = 'G'                     
 AND  FILLER2 = 0                     
 AND  C2.CL_CODE = C1.CL_CODE                     
 AND  C2.PARTY_CODE = D.PARTY_CODE                     
 AND  TRANSDATE >= @NEWFROMDATE                     
 AND  TRANSDATE <= @TODATE                    
 AND  D.PARTY_CODE >= @FROMPARTY                     
 AND  D.PARTY_CODE <= @TOPARTY                    
 AND  D.SCRIP_CD >= @FROMSCRIP                     
 AND  D.SCRIP_CD <= @TOSCRIP                    
 AND BDPID = @DPID AND BCLTDPID = @CLTDPID                 
 AND DESCRIPTION NOT LIKE '%POOL%'                  
 AND  (HOLDERNAME LIKE 'BEN ' + DP.DPCLTNO                     
  OR HOLDERNAME LIKE 'MARGIN ' + DP.DPCLTNO)                   
 AND  C1.BRANCH_CD LIKE  (CASE WHEN @STATUSID = 'BRANCH'   THEN @STATUSNAME ELSE '%' END)                    
 AND  C1.SUB_BROKER LIKE  (CASE WHEN @STATUSID = 'SUBBROKER'  THEN @STATUSNAME ELSE '%' END)                    
 AND  C1.TRADER LIKE   (CASE WHEN @STATUSID = 'TRADER'   THEN @STATUSNAME ELSE '%' END)                    
 AND  C1.FAMILY LIKE   (CASE WHEN @STATUSID = 'FAMILY'   THEN @STATUSNAME ELSE '%' END)                    
 AND  C2.PARTY_CODE LIKE  (CASE WHEN @STATUSID = 'CLIENT'   THEN @STATUSNAME ELSE '%' END)                     
 GROUP BY TRANSDATE, SETT_NO, SETT_TYPE, D.PARTY_CODE, C1.LONG_NAME,                     
  C1.L_ADDRESS1, C1.L_ADDRESS2, C1.L_ADDRESS3, C1.L_CITY, C1.L_STATE, C1.L_ZIP, C1.FAMILY,                   
  D.SCRIP_CD, CERTNO, SLIPNO, TRTYPE, ACCOUNTTYPE, DP.DPID, DPCLTNO , ISETT_NO, ISETT_TYPE, BDPID, BCLTDPID, HOLDERNAME                      
    
 SELECT TRANSDATE=CONVERT(VARCHAR,CONVERT(DATETIME,@FROMDATE),103),        
 SETT_NO='',SETT_TYPE='',PARTY_CODE='',LONG_NAME='',L_ADDRESS1='',L_ADDRESS2='',L_ADDRESS3='',        
 L_CITY='',L_STATE='', L_ZIP='',FAMILY='',SCRIP_CD,SCRIP_NAME,CERTNO,        
 CQTY=(CASE WHEN SUM(CQTY-DQTY) > 0 THEN SUM(CQTY-DQTY) ELSE 0 END),        
 DQTY=(CASE WHEN SUM(DQTY-CQTY) > 0 THEN SUM(DQTY-CQTY) ELSE 0 END),        
 SLIPNO='0',DPID='',CLTDPID='',TRTYPE='0',REASON='OPENING BALANCE',BDPID='',BCLTDPID='',        
 TRANSDATE1=CONVERT(DATETIME,@FROMDATE),FLAG=0
 INTO #DEL_TRANSSTAT_4        
 FROM #DEL_TRANSSTAT_2 D1       
 WHERE TRANSDATE1 < @FROMDATE 
 GROUP BY SCRIP_CD,SCRIP_NAME,CERTNO    
 HAVING SUM(CQTY-DQTY) <> 0
          
 UNION ALL
         
 SELECT * FROM  #DEL_TRANSSTAT_2        
 WHERE TRANSDATE1 >= @FROMDATE AND TRANSDATE1 <= @TODATE
         
 UNION ALL
         
 SELECT TRANSDATE=CONVERT(VARCHAR,CONVERT(DATETIME,@TODATE),103),        
 SETT_NO='',SETT_TYPE='',PARTY_CODE='',LONG_NAME='',L_ADDRESS1='',L_ADDRESS2='',L_ADDRESS3='',        
 L_CITY='',L_STATE='', L_ZIP='',FAMILY='',SCRIP_CD,SCRIP_NAME,CERTNO,        
 CQTY=(CASE WHEN SUM(CQTY-DQTY) > 0 THEN SUM(CQTY-DQTY) ELSE 0 END),        
 DQTY=(CASE WHEN SUM(DQTY-CQTY) > 0 THEN SUM(DQTY-CQTY) ELSE 0 END),        
 SLIPNO='0',DPID='',CLTDPID='',TRTYPE='0',REASON='CLOSING BALANCE',BDPID='',BCLTDPID='',        
 TRANSDATE1=CONVERT(DATETIME,@TODATE),FLAG=6        
 FROM #DEL_TRANSSTAT_2 D1    
 WHERE TRANSDATE1 <= @TODATE        
 AND EXISTS (SELECT PARTY_CODE FROM #DEL_TRANSSTAT_2 D2     
    WHERE D1.CERTNO = D2.CERTNO AND D1.PARTY_CODE = D2.PARTY_CODE    
    AND TRANSDATE1 >= @FROMDATE AND TRANSDATE1 <= @TODATE)
 GROUP BY SCRIP_CD,SCRIP_NAME,CERTNO 
 HAVING SUM(CQTY-DQTY) <> 0       
 ORDER BY SCRIP_CD, CERTNO, TRANSDATE1, FLAG, SETT_NO, SETT_TYPE, PARTY_CODE 
 
 INSERT INTO #DEL_TRANSSTAT_4
 SELECT DISTINCT TRANSDATE='01/01/2049',SETT_NO='',SETT_TYPE='',PARTY_CODE,LONG_NAME='',L_ADDRESS1='',L_ADDRESS2='',L_ADDRESS3='',L_CITY='',L_STATE='',L_ZIP='',FAMILY='',SCRIP_CD='',SCRIP_NAME=''
 ,CERTNO='',CQTY='0.00',DQTY='0.00',0,DPID='',CLTDPID='',TRTYPE=0,REASON='',BDPID='',BCLTDPID='',TRANSDATE1='01/01/2049',0
 FROM #DEL_TRANSSTAT_4
 GROUP BY TRANSDATE,PARTY_CODE,LONG_NAME,L_ADDRESS1,L_ADDRESS2,L_ADDRESS3,L_CITY,L_STATE,L_ZIP,FAMILY,SLIPNO ,TRTYPE,FLAG,CQTY,DQTY,TRANSDATE1
 
 INSERT INTO #DEL_TRANSSTAT_4
  SELECT DISTINCT TRANSDATE='01/01/2049',SETT_NO='',SETT_TYPE='',PARTY_CODE,LONG_NAME='',L_ADDRESS1='',L_ADDRESS2='',L_ADDRESS3='',L_CITY='',L_STATE='',L_ZIP='',FAMILY='',SCRIP_CD,SCRIP_NAME
 ,CERTNO='',CQTY='0.00',DQTY='0.00',0,DPID='',CLTDPID='',TRTYPE=0,REASON='',BDPID='',BCLTDPID='',TRANSDATE1='01/01/2049',0
 FROM #DEL_TRANSSTAT_4
 WHERE SCRIP_CD <>'' AND SCRIP_NAME<>''

 SELECT TRANSDATE,SETT_NO,SETT_TYPE,PARTY_CODE,LONG_NAME,L_ADDRESS1,L_ADDRESS2,L_ADDRESS3,L_CITY,L_STATE,L_ZIP,FAMILY,SCRIP_NAME,SCRIP_CD,CERTNO,CQTY,DQTY,SLIPNO,DPID,CLTDPID,TRTYPE,REASON,BDPID,BCLTDPID,TRANSDATE1,FLAG 
 FROM #DEL_TRANSSTAT_4
 WHERE  PARTY_CODE<>''
 ORDER BY PARTY_CODE, SCRIP_CD, CERTNO, TRANSDATE1, FLAG, SETT_NO, SETT_TYPE 
                    
END                    
                  
DROP TABLE #DEL_TRANSSTAT

GO
