-- Object: PROCEDURE dbo.CNT_Omnesys_UPDATE_bkp_20220208
-- Server: 10.253.33.91 | DB: MSAJAG
--------------------------------------------------

CREATE PROC [dbo].[CNT_Omnesys_UPDATE_bkp_20220208]

AS
BEGIN

----------------START
/*This Code is Comented By Ahsan 2022 01 18*/
--EXEC [196.1.115.159].msdb.DBO.SP_START_JOB 'OMNESYS_COMM_SQ_OFF' 
--WAITFOR DELAY '00:02:15'; 
/*End The Code Comments Addition*/

/*This is added By Ahsan 2022 01 18*/
EXEC [196.1.115.159].msdb.DBO.SP_START_JOB 'OMNESYS_CASH_SQ_OFF_NEW_COMM' 
  TRUNCATE TABLE CNT_OMNESYS
  INSERT INTO CNT_OMNESYS
  (
	  EXCHG_ORDER_NO,
	  REMARKS,
	  USERID,
	  TIME,
	  EXCHG,
	  FILE_DATE,
	  ACC_ID
  )
  SELECT 
	  EXCHG_ORDER_NO,
	  REMARKS,
	  USERID,
	  CONVERT(TIME,TIME),
	  EXCHG,
	  CONVERT(DATE,FILE_DATE),
	  ACC_ID
  FROM tbl_CNT_Omnesys_temp

WAITFOR DELAY '00:02:15'; 

/*End The Code Addition 18th Jan 2022*/

DECLARE @COUNT INT 
DECLARE @BODYMSG NVARCHAR(MAX)    
DECLARE @SUBJECT NVARCHAR(MAX)  
DECLARE @TABLEHTML NVARCHAR(MAX)  
DECLARE @FINALCOUNT NVARCHAR(MAX)
DECLARE @C INT 
SELECT @C =COUNT(EXCHG_ORDER_NO) FROM CNT_Omnesys WHERE  EXCHG in ('MCX' ,'NCDEX') AND FILE_DATE >= CONVERT(VARCHAR(10),GETDATE()-1,120)

 IF @C > 0 
 BEGIN 
 
UPDATE ORDER_TRANS_JV_CALC SET ORDER_TYPE ='ONLINE'
WHERE TRADE_DATE >= CONVERT(VARCHAR(10),GETDATE()-1,120)
AND ORDER_NO IN (SELECT EXCHG_ORDER_NO FROM CNT_Omnesys WHERE REMARKS IS NOT NULL)
and ORDER_TYPE <> 'ONLINE'


UPDATE ORDER_TRANS_JV_CALC SET ORDER_TYPE ='ONLINE'
WHERE TRADE_DATE >= CONVERT(VARCHAR(10),GETDATE()-1,120)
AND ORDER_NO IN (SELECT EXCHG_ORDER_NO FROM CNT_Omnesys WHERE REMARKS IS NOT NULL)
and ORDER_TYPE <> 'ONLINE'


UPDATE ORDER_TRANS_JV_CALC SET ORDER_TYPE ='ONLINE'
WHERE TRADE_DATE >= CONVERT(VARCHAR(10),GETDATE()-1,120)
AND ORDER_NO IN (SELECT EXCHG_ORDER_NO FROM CNT_Omnesys WHERE REMARKS ='SmartApi')
and ORDER_TYPE <> 'ONLINE'

UPDATE ORDER_TRANS_JV_CALC SET ORDER_TYPE ='ONLINE'
WHERE TRADE_DATE >= CONVERT(VARCHAR(10),GETDATE()-1,120)
AND ORDER_NO IN (SELECT EXCHG_ORDER_NO FROM CNT_Omnesys WHERE REMARKS <> '')
and ORDER_TYPE <> 'ONLINE'
 
UPDATE ORDER_TRANS_JV_CALC SET ORDER_TYPE ='ONLINE'
WHERE TRADE_DATE >= CONVERT(VARCHAR(10),GETDATE()-1,120)
AND ORDER_NO IN (SELECT EXCHG_ORDER_NO FROM CNT_Omnesys WHERE  USERID IN ('RISKAD','OMSYS1')  AND EXCHG IN ('NFO' ,'NSE','BSE')
AND TIME BETWEEN '15:15' AND '15:24:59'
 )
and ORDER_TYPE <> 'ONLINE'
AND  EXCHANGE IN ('BSE','NSE')

UPDATE ORDER_TRANS_JV_CALC SET ORDER_TYPE ='ONLINE'
WHERE TRADE_DATE >= CONVERT(VARCHAR(10),GETDATE()-1,120)
AND ORDER_NO IN (SELECT EXCHG_ORDER_NO FROM CNT_Omnesys WHERE USERID IN ('RISKAD','OMSYS1') AND EXCHG in ('CDS')
AND TIME BETWEEN '16:45' AND '17:00'
 )
and ORDER_TYPE <> 'ONLINE'
AND EXCHANGE ='NSECDS'

UPDATE ORDER_TRANS_JV_CALC SET ORDER_TYPE ='ONLINE'
WHERE TRADE_DATE >= CONVERT(VARCHAR(10),GETDATE()-1,120)
AND ORDER_NO IN (SELECT EXCHG_ORDER_NO FROM CNT_Omnesys WHERE USERID IN ('RISKAD','OMSYS1') AND EXCHG in ('MCX' ,'NCDEX')
AND TIME BETWEEN '20:45' AND '21:00'
 )
and ORDER_TYPE <> 'ONLINE'
AND EXCHANGE IN ('MCX' ,'NCDEX')

UPDATE ORDER_TRANS_JV_CALC SET ORDER_TYPE ='ONLINE'
WHERE TRADE_DATE >= CONVERT(VARCHAR(10),GETDATE()-1,120)
AND ORDER_NO IN (SELECT EXCHG_ORDER_NO FROM CNT_Omnesys WHERE USERID IN ('RISKAD','OMSYS1') AND EXCHG in ('MCX' ,'NCDEX')
AND TIME BETWEEN '23:15' AND '23:30'
 )
and ORDER_TYPE <> 'ONLINE'
AND EXCHANGE IN ('MCX' ,'NCDEX')

SELECT EXCHG_ORDER_NO INTO #TRADENXT FROM CNT_Omnesys WHERE  REMARKS ='TRADENXT'

SELECT EXCHG_ORDER_NO INTO #TradeNXT_Dealer FROM CNT_Omnesys WHERE  REMARKS ='TradeNXT_Dealer' 

	 CREATE INDEX #T1 ON #TradeNXT_Dealer(EXCHG_ORDER_NO)
 
UPDATE ORDER_TRANS_JV_CALC SET ORDER_TYPE ='OFFLINE',PRODUCT_TYPE='TradeNXT_Dealer'
WHERE TRADE_DATE >= CONVERT(VARCHAR(10),GETDATE()-1,120)
AND ORDER_NO IN (SELECT EXCHG_ORDER_NO FROM #TradeNXT_Dealer )
and ORDER_TYPE <>'OFFLINE'

UPDATE ORDER_TRANS_JV_CALC SET ORDER_TYPE ='ONLINE'
WHERE TRADE_DATE >= CONVERT(VARCHAR(10),GETDATE()-1,120)
AND ORDER_NO IN (SELECT EXCHG_ORDER_NO FROM #TRADENXT )
and ORDER_TYPE ='OFFLINE'

UPDATE ORDER_TRANS_JV_CALC SET ORDER_TYPE ='OFFLINE',PRODUCT_TYPE='TradeNXT_Dealer'
WHERE TRADE_DATE >= CONVERT(VARCHAR(10),GETDATE()-1,120)
AND ORDER_NO IN (SELECT EXCHG_ORDER_NO FROM #TradeNXT_Dealer )
and ORDER_TYPE <>'OFFLINE'

UPDATE ORDER_TRANS_JV_CALC SET ORDER_TYPE ='ONLINE'
WHERE TRADE_DATE >= CONVERT(VARCHAR(10),GETDATE()-1,120)
AND ORDER_NO IN (SELECT EXCHG_ORDER_NO FROM CNT_Omnesys WHERE  USERID IN ('CHIEF','CHIEF1')
 )
and ORDER_TYPE <> 'ONLINE'

UPDATE ORDER_TRANS_JV_CALC SET PRODUCT_TYPE ='RISK-SQ-OFF'
WHERE TRADE_DATE >= CONVERT(VARCHAR(10),GETDATE()-1,120)
AND ORDER_NO IN (SELECT EXCHG_ORDER_NO FROM CNT_Omnesys WHERE  USERID IN ('OMSYS1','MRO14')
 )
and ORDER_TYPE = 'OFFLINE'
AND PRODUCT_TYPE IS NULL

--------------------add on 29 sep 2021

UPDATE ORDER_TRANS_JV_CALC SET ORDER_TYPE ='ONLINE'
WHERE TRADE_DATE >= CONVERT(VARCHAR(10),GETDATE()-1,120)
AND ORDER_NO IN (SELECT EXCHG_ORDER_NO FROM CNT_Omnesys WHERE REMARKS IS  NULL)
and ORDER_TYPE <> 'ONLINE'

UPDATE ORDER_TRANS_JV_CALC SET ORDER_TYPE ='ONLINE'
WHERE TRADE_DATE >= CONVERT(VARCHAR(10),GETDATE()-1,120)
AND ORDER_NO IN (SELECT EXCHG_ORDER_NO FROM CNT_Omnesys WHERE REMARKS ='')
and ORDER_TYPE <> 'ONLINE'


UPDATE ORDER_TRANS_JV_CALC SET ORDER_TYPE ='ONLINE'
WHERE TRADE_DATE >= CONVERT(VARCHAR(10),GETDATE()-1,120)
AND ORDER_NO IN (SELECT EXCHG_ORDER_NO FROM CNT_Omnesys WHERE REMARKS IS  NULL)
and ORDER_TYPE <> 'ONLINE'

UPDATE ORDER_TRANS_JV_CALC SET ORDER_TYPE ='ONLINE'
WHERE TRADE_DATE >= CONVERT(VARCHAR(10),GETDATE()-1,120)
AND ORDER_NO IN (SELECT EXCHG_ORDER_NO FROM CNT_Omnesys WHERE REMARKS ='')
and ORDER_TYPE <> 'ONLINE'

-------------------added with confrimation by Martin ,Tushar,Shashi soni.

UPDATE ORDER_TRANS_JV_CALC SET PRODUCT_TYPE ='Direct-Terminal'
--select * from ORDER_TRANS_JV_CALC
WHERE TRADE_DATE >= CONVERT(VARCHAR(10),GETDATE()-1,120)
and ORDER_TYPE = 'OFFLINE'
AND PRODUCT_TYPE IS NULL

---AEMobile  One more condition added on 18-Jan-2022 Same orderno in diffreny exchange around 30 Cases everyday 
UPDATE  A 
SET ORDER_TYPE ='ONLINE'
FROM ORDER_TRANS_JV_CALC  A
INNER JOIN CNT_Omnesys B On A.ORDER_NO =B.EXCHG_ORDER_NO AND A.PARTY_CODE=B.ACC_ID
WHERE TRADE_DATE >= CONVERT(VARCHAR(10),GETDATE()-1,120) AND B.REMARKS ='AEMobile'
AND ORDER_NO IN (SELECT EXCHG_ORDER_NO FROM CNT_Omnesys WHERE REMARKS ='AEMobile' GROUP BY EXCHG_ORDER_NO)
AND ORDER_TYPE <> 'ONLINE'
------------------ END

  set @FINALCOUNT ='<big>'+'<FONT COLOR="blue">'+ '<b>' + 'CNT CHARGES COMPLETED FOR THE DAY..! ' +'</FONT>' + '</b>'+ '</big> '
  
END 

ELSE 

BEGIN

  set @FINALCOUNT ='<big>'+'<FONT COLOR="RED">'+ '<b>' + 'CHECK OMENSYS FILE IS NOT PRESENT ON THE PATH OR FILE FORMAT ISSUE,CNT CHARGES NOT UPDATED FOR THE DAY..! ' +'</FONT>' + '</b>'+ '</big> '
  
  END
SET @SUBJECT = 'CNT FINAL ALERT...!!!'   

EXEC MSDB.DBO.SP_SEND_DBMAIL    
@PROFILE_NAME ='DBA',
@RECIPIENTS='PUNIT.VERMA@angelbroking.com' ,    
@COPY_RECIPIENTS='',    
@SUBJECT = @SUBJECT,    
@BODY = @FINALCOUNT,     
@BODY_FORMAT = 'HTML' ;    


------------------------CLOSE
 END

GO
