-- Object: PROCEDURE dbo.RPT_CLIENT_COLL_SEG_NSE_NEW_EXPORT
-- Server: 10.253.33.91 | DB: MSAJAG
--------------------------------------------------

CREATE PROCEDURE RPT_CLIENT_COLL_SEG_NSE_NEW_EXPORT (@RUNDATE VARCHAR(11))

AS ---- EXEC RPT_CLIENT_COLL_SEG_NSE_NEW_EXPORT 'OCT 15 2021'

DECLARE @ADNAME VARCHAR(100) = 'J:\BACKOFFICE\EXPORT\' + 'CLIENT_COLL_SEG_NSE_'+ REPLACE(CONVERT(VARCHAR(10), CONVERT(DATETIME,@RUNDATE), 104), '.', '') + '.CSV'
DECLARE @ADSTMT NVARCHAR(4000) = 'EXEC [MSAJAG].[DBO].[RPT_CLIENT_COLL_SEG_NSE_NEW]  ''' + @RUNDATE + ''''
DECLARE @ADBCP VARCHAR(4000) = 'BCP "' + @ADSTMT + '" QUERYOUT "' + @ADNAME + '" -c -t"," -r"\n" -T'
PRINT @ADNAME

EXEC MASTER..XP_CMDSHELL @ADBCP , NO_OUTPUT

SELECT 'Report Successfully Exported to :' + @ADNAME

GO
