-- Object: PROCEDURE dbo.PROC_CM_MARGIN_INSERT
-- Server: 10.253.33.91 | DB: MSAJAG
--------------------------------------------------


CREATE PROC PROC_CM_MARGIN_INSERT
(
	@MARGINDATE	VARCHAR(11),
	@UNAME		VARCHAR(50) = 'AUTO'
)
AS

UPDATE TBL_CMMARGIN_TMP SET PARTY_CODE = NEWPARTY_CODE
FROM PARTYMAPPING
WHERE PARTY_CODE = OLDPARTY_CODE  

DELETE FROM TBL_CMMARGIN
WHERE MARGINDATE = @MARGINDATE

INSERT INTO TBL_CMMARGIN
SELECT MARGINDATE,PARTY_CODE,VARMARGIN,EXTREME_LOSS_MARGIN,ADDITIONAL_MARGIN,MTOM_LOSS,
	   TOTAL_MARGIN_MIN,CL_FLAG,UPLOAD_ON=GETDATE(),UPLOAD_BY=@UNAME,TOTAL_MARGIN_VAR,PEAKMARGIN
FROM TBL_CMMARGIN_TMP

GO
