-- Object: PROCEDURE dbo.PROC_CC_APP_SCRIP_UPLOAD
-- Server: 10.253.33.91 | DB: MSAJAG
--------------------------------------------------

CREATE PROC [dbo].[PROC_CC_APP_SCRIP_UPLOAD] (@TDATE VARCHAR(10), @FILEFOR VARCHAR(20), @FILETYPE VARCHAR(50), @PROGID VARCHAR(50), @UNAME VARCHAR(50),@FILENAME VARCHAR(100) = '')

AS

-- EXEC PROC_ILLIQUID_UPLOAD '09/04/2018', '', '', '1234567890', ''
DECLARE @RECCNT INT,

		@FILEDATE	DATETIME

SELECT DISTINCT FILEDATE=CONVERT(DATETIME,.DBO.PIECE(FILE_DATA,',',5),103) INTO #FILEDATE 
FROM FILEDATA
WHERE PROGID = @PROGID AND ISNULL(.DBO.PIECE(FILE_DATA,',',2),'')  LIKE 'IN%'

IF (SELECT ISNULL(COUNT(1),0) FROM #FILEDATE ) > 1 
BEGIN
	SELECT STRMSGCODE = -1, STRMSG = ' SELECTED FILE CONTAINS MULTIPLE DATES, CAN NOT UPLOAD THE FILE'
	RETURN
END

IF (SELECT ISNULL(COUNT(1),0) FROM #FILEDATE WHERE FILEDATE <> CONVERT(DATETIME,@TDATE,103)) > 0 
BEGIN
	SELECT STRMSGCODE = -1, STRMSG = ' SELECTED DATE AND FILE DATE NOT MATCHING, CAN NOT UPLOAD THE FILE'
	RETURN
END

IF (SELECT ISNULL(COUNT(1),0) FROM #FILEDATE WHERE FILEDATE < CONVERT(DATETIME,LEFT(GETDATE(),11)) ) > 0 
BEGIN
	SELECT STRMSGCODE = -1, STRMSG = ' FILE DATE IS LESS THEN THE CURRENT DATE, CAN NOT UPLOAD THE FILE'
	RETURN
END

SELECT EXCHANGE,SEGMENT,ISIN,EFF_FROM_DATE,EFF_TO_DATE,GROUPNAME,UPLOAD_BY,UPLOAD_ON
INTO #DATA
FROM TBL_CC_APP_SCRIP
WHERE 1 = 2 

INSERT INTO #DATA (EXCHANGE,SEGMENT,ISIN,EFF_FROM_DATE,EFF_TO_DATE,GROUPNAME,UPLOAD_BY,UPLOAD_ON)
SELECT .DBO.PIECE(FILE_DATA,',',3),.DBO.PIECE(FILE_DATA,',',4),.DBO.PIECE(FILE_DATA,',',2),
		CONVERT(DATETIME,.DBO.PIECE(FILE_DATA,',',5),103),'DEC 31 2049 23:59:59',.DBO.PIECE(FILE_DATA,',',6),
		UPLOAD_BY = @UNAME, UPLOAD_ON = GETDATE()
FROM FILEDATA
WHERE PROGID = @PROGID AND ISNULL(.DBO.PIECE(FILE_DATA,',',2),'')  LIKE 'IN%'

SELECT @RECCNT = 0 
SELECT @RECCNT = ISNULL(COUNT(1),0) FROM #DATA

IF @RECCNT > 0 
BEGIN
	UPDATE TBL_CC_APP_SCRIP SET EFF_TO_DATE = LEFT(CONVERT(DATETIME,@TDATE,103)-1, 11) + ' 23:59:59'
	WHERE EFF_TO_DATE >= LEFT(GETDATE(),11)
	 
	DELETE FROM TBL_CC_APP_SCRIP 
	WHERE EFF_FROM_DATE > EFF_TO_DATE 

	INSERT INTO TBL_CC_APP_SCRIP
	SELECT * FROM #DATA
END

/*

DELETE FROM FILEDATA

WHERE PROGID = @PROGID

*/
SELECT STRMSGCODE = 1, STRMSG = CONVERT(VARCHAR,@RECCNT) + ' RECORD(S) UPLOADED.'

GO
