-- Object: PROCEDURE dbo.CLS_COMB_MARGIN_CALC_REPORT
-- Server: 10.253.33.91 | DB: MSAJAG
--------------------------------------------------


CREATE PROC [dbo].[CLS_COMB_MARGIN_CALC_REPORT]
(
	@FROMDATE varchar(11),
	@TODATE varchar(11),
	@FROMPARTY VARCHAR(20),
	@TOPARTY VARCHAR(20),
	@EXCHANGE VARCHAR(10)
)

AS
BEGIN
	IF LEN(@FROMDATE) = 10 AND CHARINDEX('/', @FROMDATE) > 0  
	 BEGIN  
		SET @FROMDATE = CONVERT(VARCHAR(11), CONVERT(DATETIME, @FROMDATE, 103), 109)  
	 END  

	IF LEN(@TODATE) = 10 AND CHARINDEX('/', @TODATE) > 0  
	 BEGIN  
		SET @TODATE = CONVERT(VARCHAR(11), CONVERT(DATETIME, @TODATE, 103), 109)  
	 END  
	 print @FROMDATE
	  print @TODATE
	EXEC COMB_MARGIN_CALC_REPORT @FROMDATE,@TODATE,@FROMPARTY,@TOPARTY,@EXCHANGE
END

GO
