-- Object: PROCEDURE dbo.usp_rtb_nse_valan_BKP_14FEB2025_SRE-34208
-- Server: 10.253.33.91 | DB: MSAJAG
--------------------------------------------------


--Altered the SP due to https://angelbrokingpl.atlassian.net/browse/SRE-30317
CREATE PROC [dbo].[usp_rtb_nse_valan_BKP_14FEB2025_SRE-34208]  

(@DATE AS DATETIME)  

AS

BEGIN  
    
Select * Into #CLIENT1 from Client1 Where cl_code in (
SELECT Distinct PARTY_CODE  FROM  MSAJAG.DBO.CMBILLVALANDATA_RTB with(NOLOCK) WHERE SAUDA_DATE =@DATE AND SETT_TYPE IN ('M','Z') )

CREATE INDEX #C ON #CLIENT1(CL_CODE)

--SELECT * INTO #NSEVALAN FROM  MSAJAG.DBO.CMBILLVALANDATA_RTB with(NOLOCK) WHERE SAUDA_DATE =@DATE AND SETT_TYPE IN ('M','Z') ---- COMMENTED ON 28 JAN 2025 AND 03 FEB 2025

SELECT SETT_NO,SETT_TYPE,BILLNO,CONTRACTNO,PARTY_CODE,PARTY_NAME,SCRIP_CD,SERIES,SCRIP_NAME,ISIN,SAUDA_DATE,PQTYTRD,PAMTTRD,PQTYDEL,PAMTDEL,SQTYTRD,SAMTTRD,SQTYDEL,
SAMTDEL,PBROKTRD,SBROKTRD,PBROKDEL,SBROKDEL,FAMILY,FAMILY_NAME,TERMINAL_ID,CLIENTTYPE,TRADETYPE,TRADER,SUB_BROKER,BRANCH_CD,PARTICIPANTCODE,PAMT,SAMT,PRATE,SRATE,
TRDAMT,DELAMT,SERINEX,SERVICE_TAX,EXSERVICE_TAX,TURN_TAX,SEBI_TAX,INS_CHRG,BROKER_CHRG,OTHER_CHRG,REGION,START_DATE,END_DATE,UPDATE_DATE,STATUS_NAME,EXCHANGE,SEGMENT,
MEMBERTYPE,COMPANYNAME,DUMMY1,DUMMY2,DUMMY3,DUMMY4,DUMMY5,AREA 
INTO #NSEVALAN 
FROM  MSAJAG.DBO.CMBILLVALANDATA_RTB with(NOLOCK) WHERE SAUDA_DATE =@DATE AND SETT_TYPE IN ('M','Z')
 
CREATE INDEX #C ON #NSEVALAN(PARTY_CODE)

UPDATE B SET PARTY_NAME = SHORT_NAME,FAMILY=C.FAMILY,FAMILY_NAME= SHORT_NAME,CLIENTTYPE =CL_TYPE
FROM #NSEVALAN B,#CLIENT1 C
WHERE B.PARTY_CODE=C.CL_CODE 

delete from CMBILLVALAN WHERE SAUDA_DATE =@DATE AND SETT_TYPE IN ('M','Z')

INSERT INTO CMBILLVALAN
SELECT  * FROM #NSEVALAN (NOLOCK)

SELECT  * into #ACCBILL FROM  ACCBILLDATA_RTB (NOLOCK) WHERE START_DATE =@DATE AND SETT_TYPE IN ('M','Z')

delete from ACCBILL WHERE Start_Date =@DATE AND SETT_TYPE IN ('M','Z')

 INSERT INTO ACCBILL
SELECT  * FROM  #ACCBILL (NOLOCK)  

delete from accbill_org WHERE Start_Date =@DATE AND SETT_TYPE IN ('M','Z')

 INSERT INTO accbill_org
SELECT  * FROM  #ACCBILL (NOLOCK)  

END

GO
