-- Object: PROCEDURE dbo.CLS_CLIENT_INFO
-- Server: 10.253.33.91 | DB: MSAJAG
--------------------------------------------------


CREATE PROCEDURE [dbo].[CLS_CLIENT_INFO]    
(    
@FROMDATE VARCHAR(11),    
@TODATE VARCHAR(11),    
@FROMPARTY VARCHAR(25),    
@TOPARTY VARCHAR(25)    
)    
AS     
IF LEN(@FROMDATE) = 10 AND CHARINDEX('/', @FROMDATE) > 0    
BEGIN    
 SET @FROMDATE = CONVERT(VARCHAR(11), CONVERT(DATETIME, @FROMDATE, 103), 109)    
END    
IF LEN(@TODATE) = 10 AND CHARINDEX('/', @TODATE) > 0    
BEGIN    
 SET @TODATE = CONVERT(VARCHAR(11), CONVERT(DATETIME, @TODATE, 103), 109)    
END    
--EXEC CLS_CLIENT_INFO 'Sep 10 2005','Sep 10 2015','HOC00024','HOC00024'    
SELECT     
 DISTINCT     
 [CLIENT CODE]=PARTY_CODE,    
 [CLIENT NAME]=CD.LONG_NAME,    
 [REGISTRATION DATE] = CONVERT(VARCHAR,MIN(SYSTEMDATE),103),  
 REPORTDATE=left(convert(varchar,Getdate(),103),11),    
 L_ADDRESS1,    
 L_ADDRESS2,    
 L_ADDRESS3,    
 L_CITY,    
 L_ZIP,    
 RES_PHONE1,    
 RES_PHONE2,    
 OFF_PHONE1,    
 OFF_PHONE2,    
 CELLNO = MOBILE_PAGER,    
 PAN_GIR_NO,    
 EMAIL=LOWER(CD.EMAIL),    
 PASSPORT_NO AS PASSPORTNO,    
 VOTERSID_NO AS VOTERSID,    
 RAT_CARD_NO AS RATIONCARD,    
 LICENCE_NO AS LICENCENO,    
 (    
  CASE     
   WHEN YEAR(PASSPORT_ISSUED_ON) = '1900'    
    THEN ''    
   ELSE CONVERT(VARCHAR, PASSPORT_ISSUED_ON, 103)    
   END    
  ) AS PASSPORTDATEOFISSUE,    
 PASSPORT_ISSUED_AT AS PASSPORTPLACEOFISSUE,    
 (    
  CASE     
   WHEN YEAR(VOTERSID_ISSUED_ON) = '1900'    
    THEN ''    
   ELSE CONVERT(VARCHAR, VOTERSID_ISSUED_ON, 103)    
   END    
  ) AS VOTERIDDATEOFISSUE,    
 VOTERSID_ISSUED_AT AS VOTERIDPLACEOFISSUE,    
 (    
  CASE     
   WHEN YEAR(LICENCE_ISSUED_ON) = '1900'    
    THEN ''    
   ELSE CONVERT(VARCHAR, LICENCE_ISSUED_ON, 103)    
   END    
  ) AS LICENCENODATEOFISSUE,    
 LICENCE_ISSUED_AT AS LICENCENOPLACEOFISSUE,    
 (    
  CASE     
   WHEN YEAR(RAT_CARD_ISSUED_ON) = '1900'    
    THEN ''    
   ELSE CONVERT(VARCHAR, RAT_CARD_ISSUED_ON, 103)    
   END    
  ) AS RATIONCARDDATEOFISSUE,    
 RAT_CARD_ISSUED_AT AS RATIONCARDPLACEOFISSUE,    
 (    
  CASE     
   WHEN YEAR(PASSPORT_EXPIRES_ON) = '1900'    
    THEN ''    
   ELSE CONVERT(VARCHAR, PASSPORT_EXPIRES_ON, 103)    
   END    
  ) AS PASSPORT_EXPIRES_ON,    
 (    
  CASE     
   WHEN YEAR(LICENCE_EXPIRES_ON) = '1900'    
    THEN ''    
   ELSE CONVERT(VARCHAR, LICENCE_EXPIRES_ON, 103)    
   END    
  ) AS LICENCE_EXPIRES_ON,    
 BANK_NAME,    
 BRANCH_NAME,    
 AC_NUM AS AC_NUM,    
 (    
  CASE     
   WHEN AC_TYPE = 'S'    
    THEN 'SAVING'    
   WHEN AC_TYPE = 'C'    
    THEN 'CURRENT'    
   ELSE 'OTHER'    
   END    
  ) AS AC_TYPE,    
 BANKNAME = ISNULL(BANKNAME, 'N/A'),    
 DPID1 AS BANKID,    
 CLTDPID1 AS CLTDPID,    
 UPPER(DEPOSITORY1) AS DEPOSITORY,    
 --SYSTEMDATE = LEFT(MIN(SYSTEMDATE), 11),    
 BRANCH_CD = BR.BRANCH_CODE,    
 BRNAME = BR.BRANCH,    
 BRADD1 = BR.ADDRESS1,    
 BRADD2 = BR.ADDRESS2,    
 BRCITY = BR.CITY,    
 BRZIP = BR.ZIP,    
 BRPHONE1 = BR.PHONE1,    
 BRPHONE2 = BR.PHONE2,    
 BREMAIL = BR.EMAIL,    
 FLAG_NODETAIL,FLAG_PASSPORTDET,FLAG_LICENCEDET,FLAG_VOTERDET,    
 FLAG_RATCARDDET,FLAG_BANKDET,FLAG_DPDET,FLAG_BROKDET    
    
FROM     
    CLIENT_BROK_DETAILS CB,    
 CLIENT_DETAILS CD    
 LEFT JOIN BANK BA    
 ON (DPID1 = BANKID)    
 LEFT JOIN BRANCH BR    
 ON (BR.BRANCH_CODE = CD.BRANCH_CD),    
 CLS_CLIENT_SETTING    
     
WHERE     
    CB.CL_CODE = CD.CL_CODE    
 AND PARTY_CODE >= @FROMPARTY    
 AND PARTY_CODE <= @TOPARTY    
 AND SYSTEMDATE >= @FROMDATE    
 AND SYSTEMDATE <= @TODATE + ' 23:59:59'    
GROUP BY CD.LONG_NAME,    
 L_ADDRESS1,    
 L_ADDRESS2,    
 L_ADDRESS3,    
 L_CITY,    
 L_ZIP,    
 PARTY_CODE,    
 RES_PHONE1,    
 RES_PHONE2,    
 OFF_PHONE1,    
 OFF_PHONE2,    
 MOBILE_PAGER,    
 PAN_GIR_NO,    
 CD.EMAIL,    
 PASSPORT_NO,    
 VOTERSID_NO,    
 RAT_CARD_NO,    
 LICENCE_NO,    
 PASSPORT_ISSUED_ON,    
 PASSPORT_ISSUED_AT,    
 VOTERSID_ISSUED_ON,    
 PASSPORT_EXPIRES_ON,    
 LICENCE_EXPIRES_ON,    
 VOTERSID_ISSUED_AT,    
 LICENCE_ISSUED_ON,    
 LICENCE_ISSUED_AT,    
 RAT_CARD_ISSUED_ON,    
 RAT_CARD_ISSUED_AT,    
 BANK_NAME,    
 BRANCH_NAME,    
 AC_NUM,    
 AC_TYPE,    
 BA.BANKNAME,    
CD.DPID1,    
 CD.CLTDPID1,    
 CD.DEPOSITORY1,    
 BR.BRANCH_CODE,    
 BR.BRANCH,    
 BR.ADDRESS1,    
 BR.ADDRESS2,    
 BR.CITY,    
 BR.ZIP,    
 BR.PHONE1,    
 BR.PHONE2,    
 BR.EMAIL,    
 FLAG_NODETAIL,FLAG_PASSPORTDET,FLAG_LICENCEDET,FLAG_VOTERDET,FLAG_RATCARDDET,    
 FLAG_BANKDET,FLAG_DPDET,FLAG_BROKDET    
ORDER BY PARTY_CODE

GO
