-- Object: PROCEDURE dbo.ORDER_JV_CAL_NSE_BSE_NSEFO_BACKDate_Process
-- Server: 10.253.33.91 | DB: MSAJAG
--------------------------------------------------

--- Step 3 JV 
CREATE PROC [dbo].[ORDER_JV_CAL_NSE_BSE_NSEFO_BACKDate_Process]
(
@TO_DATE DATETIME
)
AS

BEGIN
  --DECLARE @TO_DATE DATETIME

  SET @TO_DATE =  CONVERT (VARCHAR (10),@TO_DATE,120)
 
  IF OBJECT_ID('tempdb..#trd1') IS NOT NULL
  DROP TABLE #trd1
  IF OBJECT_ID('tempdb..#TEMP') IS NOT NULL
  DROP TABLE #TEMP
  IF OBJECT_ID('tempdb..#testr') IS NOT NULL
  DROP TABLE #testr

  SELECT DISTINCT CD_Party_Code into #trd1
  FROM Charges_Detail WHERE  CD_Computation_Level ='O' AND CD_Sauda_Date >= @TO_DATE   AND CD_Sauda_Date <= @TO_DATE+' 23:59'
  UNION ALL
  SELECT DISTINCT CD_Party_Code   FROM ANAND.BSEDB_AB.DBO.Charges_Detail WHERE  CD_Computation_Level ='O' 
  AND CD_Sauda_Date >= @TO_DATE AND CD_SAUDA_DATE <= @TO_DATE +' 23:59'
  UNION ALL
  SELECT DISTINCT CD_Party_Code   FROM ANGELFO.NSEFO.DBO.Charges_Detail WHERE  CD_ComputationLevel ='O' 
  AND CD_Sauda_Date >= @TO_DATE   AND CD_Sauda_Date <= @TO_DATE+' 23:59'


	SELECT 
		 SAUDA_DATE = LTRIM(RTRIM(.DBO.PIECE(FILE_DATA,',',1))) , 
		PARTY_CODE=LTRIM(RTRIM(.DBO.PIECE(FILE_DATA,',',23))),
		Delaer=LTRIM(RTRIM(.DBO.PIECE(FILE_DATA,',',2))),
		--SYMBOL=(CASE WHEN LTRIM(RTRIM(.DBO.PIECE(FILE_DATA,',',4))) = 'BSE' AND LTRIM(RTRIM(.DBO.PIECE(FILE_DATA,',',8))) = ''
		--			 THEN LTRIM(RTRIM(.DBO.PIECE(FILE_DATA,',',9))) 
		--			 ELSE LTRIM(RTRIM(.DBO.PIECE(FILE_DATA,',',10)))
		--		END),
		--EXPIRYDATE=LTRIM(RTRIM(.DBO.PIECE(FILE_DATA,',',12))),
		--STRIKE_PRICE=(CASE WHEN LTRIM(RTRIM(.DBO.PIECE(FILE_DATA,',',13))) = '' THEN '0' ELSE LTRIM(RTRIM(.DBO.PIECE(FILE_DATA,',',13))) END),
		--OPTION_TYPE=LTRIM(RTRIM(.DBO.PIECE(FILE_DATA,',',14))),
	 --   INTIATED_BY=LTRIM(RTRIM(.DBO.PIECE(FILE_DATA,',',2))),
		 PRODUCT_TYPE=LTRIM(RTRIM(.DBO.PIECE(FILE_DATA,',',32))),
		ORDER_NO=LTRIM(RTRIM(.DBO.PIECE(FILE_DATA,',',25))),
		ORDER_INIT_FROM=LTRIM(RTRIM(.DBO.PIECE(FILE_DATA,',',35))),
		ORDER_MODY_FROM=LTRIM(RTRIM(.DBO.PIECE(FILE_DATA,',',36))),
		SEGMENT=LTRIM(RTRIM(.DBO.PIECE(FILE_DATA,',',4))),
		INST_TYPE=LTRIM(RTRIM(.DBO.PIECE(FILE_DATA,',',8))),
		INS=LTRIM(RTRIM(.DBO.PIECE(FILE_DATA,',',29))),
		UPLOADED_BY = 'AUTO',
		UPLOADED_ON = GETDATE() INTO #TEMP 
	FROM ANGELCOMMODITY.MCDX.DBO.FILEDATA WITH(NOLOCK)
	WHERE  ISNUMERIC(.DBO.PIECE(FILE_DATA,',',18)) = 1 ---and LTRIM(RTRIM(.DBO.PIECE(FILE_DATA,',',35))) ='TWS'
	---AND LTRIM(RTRIM(.DBO.PIECE(FILE_DATA,',',1))) = @TDATE
 	 AND LTRIM(RTRIM(.DBO.PIECE(FILE_DATA,',',23))) in(SELECT DISTINCT CD_Party_Code FROM #trd1)


	 CREATE INDEX #T1 ON #TEMP(PARTY_CODE)
 
SELECT *  INTO #WSIP FROM #TEMP WHERE  LTRIM(INS) like 'WSIP%'

 
  select * into #testr   from #TEMP WHERE 
  PARTY_CODE IN (SELECT  * from #trd1)


 CREATE INDEX #T1 ON #testr(PARTY_CODE,ORDER_NO,SEGMENT)
 
	 CREATE INDEX #T1 ON #trd1(CD_Party_Code)

INSERT INTO ORDER_TRANS_JV_CALC

SELECT A.Party_Code,A.SUB_BROKER,PRODUCT_TYPE,ORDER_NO,ORDER_TYPE,EXCHANGE,SEGMENT,ORDER_FLAG,A.CL_TYPE,TRADE_DATE,l_state FROM (
SELECT  DISTINCT A.Party_Code,SUB_BROKER=Delaer,PRODUCT_TYPE=ORDER_INIT_FROM,A.ORDER_NO ,
( CASE WHEN ORDER_INIT_FROM IN ('AngelEye','AEMobile','RISKADMIN','TIMERADMIN','DIET') THEN 'ONLINE' ELSE 'OFFLINE' END) AS ORDER_TYPE, 
EXCHANGE,A.SEGMENT ,ORDER_FLAG ='',CL_TYPE='' ,TRADE_DATE  FROM (
SELECT DISTINCT PARTY_CODE,ORDER_NO,EXCHANGE='NSE',SEGMENT='CAPITAL',CONVERT(VARCHAR(11),SAUDA_DATE,120) TRADE_DATE 
FROM SETTLEMENT WITH (NOLOCK) WHERE Sauda_Date >= @TO_DATE AND SAUDA_DATE <= @TO_DATE +' 23:59' AND sett_type not in ( 'A','X','BX','TX','DX') 
AND PARTY_CODE IN ( SELECT  * from #trd1)  
UNION ALL
SELECT DISTINCT PARTY_CODE,ORDER_NO,EXCHANGE='BSE',SEGMENT='CAPITAL',CONVERT(VARCHAR(11),SAUDA_DATE,120) TRADE_DATE 
FROM ANAND.BSEDB_AB.DBO.SETTLEMENT WITH (NOLOCK) WHERE Sauda_Date >= @TO_DATE AND SAUDA_DATE <= @TO_DATE +' 23:59' AND sett_type not in ( 'AD','AC','OB','TK','DL')  
AND PARTY_CODE IN ( SELECT  * from #trd1)  
UNION ALL
SELECT DISTINCT PARTY_CODE,ORDER_NO,EXCHANGE='NSE',SEGMENT='FUTURES',CONVERT(VARCHAR(11),SAUDA_DATE,120) TRADE_DATE 
FROM ANGELFO.NSEFO.DBO.FOSETTLEMENT WITH (NOLOCK) WHERE Sauda_Date >= @TO_DATE AND SAUDA_DATE <= @TO_DATE +' 23:59' AND AuctionPart <> 'CA' and Price <> 0
and  PARTY_CODE IN ( SELECT  * from #trd1)  
 ) A
LEFT OUTER JOIN 
( SELECT DISTINCT PARTY_CODE,Delaer =(CASE WHEN Delaer=PARTY_CODE THEN '' ELSE Delaer END),ORDER_INIT_FROM,SEGMENT ,INST_TYPE ,ORDER_NO 
 FROM  #testr WITH (NOLOCK)   ) R 
ON A.Party_Code =R.PARTY_CODE AND  A.ORDER_NO=R.ORDER_NO AND R.SEGMENT=EXCHANGE AND 
(CASE WHEN isnuLL(INST_TYPE,'')='' THEN 'CAPITAL' ELSE 'FUTURES' END)  = A.SEGMENT ) A ,
Client_Details B WHERE A.Party_Code =B.cl_code



UPDATE B SET ORDER_TYPE ='ONLINE'
FROM SETTLEMENT A,ORDER_TRANS_JV_CALC B
WHERE A.Party_Code =B.PARTY_CODE 
AND A.Order_no =B.ORDER_NO
AND Sauda_Date >= @TO_DATE AND SAUDA_DATE <= @TO_DATE +' 23:59'
AND TRADE_DATE >= @TO_DATE AND TRADE_DATE <= @TO_DATE +' 23:59'
--AND TRADE_DATE >= '2022-01-13'   AND  TRADE_DATE <='2022-01-13'  +' 23:59'
AND Scrip_Cd  ='ICICINXT50'
AND User_id IN (23879,23919 )     
AND EXCHANGE ='NSE'
AND SEGMENT ='CAPITAL'


UPDATE B SET ORDER_TYPE ='ONLINE'
FROM SETTLEMENT A,ORDER_TRANS_JV_CALC B
WHERE A.Party_Code =B.PARTY_CODE 
AND A.Order_no =B.ORDER_NO
AND Sauda_Date >= @TO_DATE AND SAUDA_DATE <= @TO_DATE +' 23:59'
AND TRADE_DATE >= @TO_DATE AND TRADE_DATE <= @TO_DATE +' 23:59'
AND Scrip_Cd  ='AXISGOLD'
--AND User_id IN (23879,23919 )     
AND EXCHANGE ='NSE'
AND SEGMENT ='CAPITAL'



UPDATE B SET ORDER_TYPE ='ONLINE'
FROM anand.bsedb_ab.dbo.SETTLEMENT A,ORDER_TRANS_JV_CALC B
WHERE A.Party_Code =B.PARTY_CODE 
AND A.Order_no =B.ORDER_NO
AND Sauda_Date >= @TO_DATE AND SAUDA_DATE <= @TO_DATE +' 23:59'
AND TRADE_DATE >= @TO_DATE AND TRADE_DATE <= @TO_DATE +' 23:59'
AND Scrip_Cd  ='533570'
--AND User_id IN (23879,23919 )     
AND EXCHANGE ='BSE'
AND SEGMENT ='CAPITAL'
 
UPDATE O  SET ORDER_TYPE = 'EXE_ONLINE'
FROM ORDER_TRANS_JV_CALC O ,EXECPTION_CNT E
WHERE 
 
O.TRADE_DATE >= @TO_DATE AND O.TRADE_DATE <= @TO_DATE +' 23:59'
--O.TRADE_DATE >= CONVERT (VARCHAR (10),GETDATE()-1,120)
 AND E.PARTY_CODE = O.PARTY_CODE
 AND O.ORDER_TYPE = 'OFFLINE'

UPDATE O SET ORDER_TYPE = 'SIP_ONLINE' 
from ORDER_TRANS_JV_CALC  O, #WSIP T
 where   
 O.TRADE_DATE >= @TO_DATE AND O.TRADE_DATE <= @TO_DATE +' 23:59'
 AND LTRIM(T.PARTY_CODE) = O.PARTY_CODE
 AND O.ORDER_NO = LTRIM(T.ORDER_NO)
 AND O.ORDER_TYPE = 'OFFLINE'
 --AND  Sauda_date >=  @TO_DATE

 END

GO
