-- Object: PROCEDURE dbo.PROC_EPI_LEDGER_INSERT
-- Server: 10.253.33.91 | DB: MSAJAG
--------------------------------------------------


CREATE PROC PROC_EPI_LEDGER_INSERT
(
	@SAUDA_DATE VARCHAR(11)
)
AS

-- EXEC PROC_EPI_LEDGER_INSERT 'SEP 11 2020'
DECLARE @PREVDATE   VARCHAR(11)
		  
SELECT @PREVDATE = MAX(START_DATE) FROM SETT_MST WHERE Start_date < @SAUDA_DATE 

DELETE FROM TBL_EPI_LEDGER
WHERE TRANSDATE = @SAUDA_DATE 

INSERT INTO TBL_EPI_LEDGER
SELECT TRANSDATE=CONVERT(DATETIME,@SAUDA_DATE), PARTY_CODE, SETT_NO, SETT_TYPE, 
	   SCRIP_CD, SERIES, EPNQTY_CC, SELLRATE = CONVERT(NUMERIC(18,2),ABS(SELLAMOUNT/SELLQTY)), 
	   CRAMT = CONVERT(NUMERIC(18,4),0), DRAMT = CONVERT(NUMERIC(18,4),CASHBENEFIT),
	   NARRATION = CONVERT(VARCHAR(200),'REVERRSAL OF EPI SALE CREDIT DATED ' + LEFT(TRANSDATE,11) + ' FOR ' + SCRIP_CD + '-' 
	   + SERIES + '-' + CONVERT(VARCHAR,CONVERT(INT,EPNQTY_CC)) + ' @ ' +  CONVERT(VARCHAR,CONVERT(NUMERIC(18,2),ABS(SELLAMOUNT/SELLQTY)))),
	   FLAG = 1
FROM  TBL_EPN_BENEFIT
WHERE TRANSDATE = @PREVDATE
AND SELLQTY > 0 AND EPNQTY_CC > 0 

INSERT INTO TBL_EPI_LEDGER
SELECT TRANSDATE, PARTY_CODE, SETT_NO, SETT_TYPE, 
	   SCRIP_CD, SERIES, EPNQTY_CC, SELLRATE = ABS(SELLAMOUNT/SELLQTY), 
	   CRAMT = CONVERT(NUMERIC(18,4),CASHBENEFIT), DRAMT = CONVERT(NUMERIC(18,4),0),
	   NARRATION = 'EPI SALE CREDIT DATED ' + LEFT(TRANSDATE,11) + ' FOR ' + SCRIP_CD + '-' 
	   + SERIES + '-' + CONVERT(VARCHAR,CONVERT(INT,EPNQTY_CC)) + ' @ ' +  CONVERT(VARCHAR,CONVERT(NUMERIC(18,2),ABS(SELLAMOUNT/SELLQTY))),
	   FLAG = 2
FROM  TBL_EPN_BENEFIT
WHERE TRANSDATE = @SAUDA_DATE
AND SELLQTY > 0 AND EPNQTY_CC > 0

GO
