-- Object: PROCEDURE dbo.First_Trade_Reversal_Itrade_prime
-- Server: 10.253.33.91 | DB: MSAJAG
--------------------------------------------------


 --FIRST_TRADE_REVERSAL '2019-06-24' ,'48',4
CREATE PROC [dbo].[First_Trade_Reversal_Itrade_prime] (@SDATE DATETIME , @TIMELIMIT INT,@NO_OF_TRADES INT,@CampaignType VARCHAR(20))
AS


DECLARE @DAY INT
SET @DAY = @TIMELIMIT/24 

SET @DAY = (CASE WHEN  @DAY=1 THEN 0 ELSE @DAY END)
DECLARE @PREVDATE DATETIME ,@CURDATE DATETIME

 
SELECT @CURDATE = MAX(START_DATE)   FROM SETT_MST WHERE START_DATE <= @SDATE  AND SETT_TYPE ='N'


SELECT @PREVDATE=MAX(START_DATE)  FROM SETT_MST WHERE START_DATE <= @SDATE-@DAY  AND SETT_TYPE ='N'

 IF @PREVDATE <  '2019-09-23' 
   BEGIN 
   SET @PREVDATE ='2019-09-23'
   END 

SELECT CLIENTCODE,CreationDate INTO #CLIENT FROM [MIS].KYC.DBO.vw_itrade_prime_clientinfo  WHERE CreationDate >=@PREVDATE 
AND CreationDate <=@CURDATE + ' 23:59'    --AND TimeLimitInHour =@TIMELIMIT
and CampaignType =@CampaignType
 
  
 SELECT * INTO #CASH FROM (
SELECT DISTINCT PARTY_CODE, M.SAUDA_DATE,ORDER_TIME   ,ROW_NUMBER() OVER(Partition by PARTY_CODE ORDER BY PARTY_CODE,ORDER_TIME ASC) AS RNO
 FROM COMMON_CONTRACT_DATA M  WHERE SAUDA_DATE >=@PREVDATE    AND SAUDA_DATE <=@CURDATE +' 23:59'
 AND EXISTS  (SELECT CLIENTCODE FROM #CLIENT WHERE CLIENTCODE =PARTY_CODE AND 
 SAUDA_DATE+ORDER_TIME > CreationDate) AND SCRIPNAME <>'BROKERAGE' AND (ORDER_TIME <>'' AND ORDER_TIME <>'00:00:00')  

 ) A WHERE  RNO <= @NO_OF_TRADES

SELECT DISTINCT C.PARTY_CODE,ORDER_TIME,ORDER_NO,SUM(C.BROKERAGE) AS BROKERAGE ,EXCHANGE,SEGMENT, SAUDA_DATE,TMARK INTO #REVERSAL FROM COMMON_CONTRACT_DATA C WHERE EXISTS ( SELECT *  FROM #CASH
   WHERE  C.PARTY_CODE=PARTY_CODE AND C.ORDER_TIME=ORDER_TIME AND C.SAUDA_DATE=#CASH.SAUDA_DATE ) 
  AND SAUDA_DATE >=@PREVDATE    AND SAUDA_DATE <=@CURDATE +' 23:59'
  GROUP BY C.PARTY_CODE,ORDER_TIME,ORDER_NO,EXCHANGE,SEGMENT, SAUDA_DATE,TMARK

  /* CASH END */ 

  /* COMM START*/

  SELECT * INTO #COMM FROM (
SELECT DISTINCT PARTY_CODE, M.SAUDA_DATE,ORDER_TIME   ,ROW_NUMBER() OVER(Partition by PARTY_CODE ORDER BY PARTY_CODE,ORDER_TIME ASC) AS RNO
FROM ANGELCOMMODITY.MCDX.DBO.COMMON_CONTRACT_DATA M  WHERE SAUDA_DATE >=@PREVDATE    AND SAUDA_DATE <=@CURDATE +' 23:59'
 AND  EXISTS  (SELECT CLIENTCODE FROM #CLIENT WHERE CLIENTCODE =PARTY_CODE AND 
  SAUDA_DATE+ORDER_TIME > CreationDate) AND SCRIPNAME <>'BROKERAGE' AND (ORDER_TIME <>'' AND ORDER_TIME <>'00:00:00') )A
 WHERE  RNO <= @NO_OF_TRADES

 SELECT DISTINCT C.PARTY_CODE,ORDER_TIME,ORDER_NO,SUM(C.BROKERAGE) AS BROKERAGE,EXCHANGE,SEGMENT,C.SAUDA_DATE,C.TMARK  INTO  #REVERSAL_COMM FROM ANGELCOMMODITY.MCDX.DBO.COMMON_CONTRACT_DATA C 
 WHERE EXISTS ( SELECT * FROM #COMM
   WHERE  C.PARTY_CODE=PARTY_CODE AND C.ORDER_TIME=ORDER_TIME AND C.SAUDA_DATE=#COMM.SAUDA_DATE  )
AND C.SAUDA_DATE >=@PREVDATE    AND C.SAUDA_DATE <=@CURDATE +' 23:59'
group by C.PARTY_CODE,ORDER_TIME,ORDER_NO,EXCHANGE,SEGMENT,C.SAUDA_DATE,C.TMARK 
 
SELECT DISTINCT R.PARTY_CODE,R.ORDER_TIME,R.ORDER_NO,SUM(C.BROKERAGE) AS BROKERAGE,R.EXCHANGE,R.SEGMENT,R.TMARK INTO #FINAL
FROM #REVERSAL R, COMMON_CONTRACT_DATA C 
WHERE  C.PARTY_CODE=R.PARTY_CODE AND R.ORDER_NO=C.ORDER_NO AND C.SAUDA_DATE >=@PREVDATE    
AND C.SAUDA_DATE <=@CURDATE +' 23:59' --AND (C.ORDER_TIME ='' OR C.ORDER_TIME ='00:00:00')
GROUP BY R.PARTY_CODE,R.ORDER_TIME,R.ORDER_NO,R.EXCHANGE,R.SEGMENT,C.SAUDA_DATE,R.TMARK


/* COMM END*/

INSERT INTO #FINAL
SELECT DISTINCT R.PARTY_CODE,R.ORDER_TIME,R.ORDER_NO,SUM(C.BROKERAGE) AS BROKERAGE ,R.EXCHANGE,R.SEGMENT ,R.TMARK
FROM #REVERSAL_COMM R,  ANGELCOMMODITY.MCDX.DBO.COMMON_CONTRACT_DATA C 
WHERE  C.PARTY_CODE=R.PARTY_CODE AND R.ORDER_NO=C.ORDER_NO AND C.SAUDA_DATE >=@PREVDATE    
AND C.SAUDA_DATE <=@CURDATE +' 23:59' --AND (C.ORDER_TIME ='' OR C.ORDER_TIME ='00:00:00')
GROUP BY R.PARTY_CODE,R.ORDER_TIME,R.ORDER_NO,R.EXCHANGE,R.SEGMENT,C.SAUDA_DATE,R.TMARK

SELECT F.*,@CURDATE  AS SAUDA_DATE ,B2C,ROW_NUMBER() OVER(Partition by F.PARTY_CODE ORDER BY F.PARTY_CODE,F.ORDER_TIME ASC)AS RNO
FROM #FINAL F,INTRANET.RISK.DBO.CLIENT_DETAILS D,
(SELECT PARTY_CODE,ORDER_TIME,ROW_NUMBER() OVER(Partition by PARTY_CODE ORDER BY PARTY_CODE,ORDER_TIME ASC) AS RNO  FROM #FINAL) M
WHERE F.PARTY_CODE =D.CL_CODE AND F.ORDER_TIME =M.ORDER_TIME AND RNO <= @NO_OF_TRADES
AND F.PARTY_CODE =M.PARTY_CODE

GO
