-- Object: PROCEDURE dbo.UCC_DATA_REPORT
-- Server: 10.253.33.91 | DB: MSAJAG
--------------------------------------------------

 



CREATE PROCEDURE [dbo].[UCC_DATA_REPORT]
(
@DATE DATE)
AS
BEGIN 


		EXEC ABVSINSURANCEBO.msdb.DBO.SP_START_JOB 'VILAS_UCC_DATA' 
		
		WAITFOR DELAY '00:0:45'; 
		
		SELECT CLIENT_CODE,NISE_PARTY_CODE FROM AGMUBODPL3.dmat.citrus_usr.TBL_CLIENT_MASTER WHERE CLIENT_CODE IN (SELECT * FROM SSRS_CLIENTID)
		
		END

GO
