-- Object: PROCEDURE dbo.API_BANK_FUNDS_REPORTING_BKUP_24JUN2021
-- Server: 10.253.33.91 | DB: MSAJAG
--------------------------------------------------





--exec API_BANK_FUNDS_REPORTING 'jun 26 2021', 'jun 26 2021', '03026', 'NSE~CAPITAL'
--Exec [API_BANK_FUNDS_REPORTING] 'JUN  1 2021','JUN  1 2021'

CREATE PROCEDURE [dbo].[API_BANK_FUNDS_REPORTING_BKUP_24JUN2021]
	@FR_DATE VARCHAR(11),
	@TO_DATE VARCHAR(11),
	@BANK_CODE VARCHAR(10) = '',
	@EXCSEGMENT VARCHAR(500) = ''
AS
/* 
 declare @FR_DATE VARCHAR(11)
declare 	@TO_DATE VARCHAR(11)
declare 	@BANK_CODE VARCHAR(10) 
declare 	@EXCSEGMENT VARCHAR(500)

 set @FR_DATE = 'AUG  7 2019'
set 	@TO_DATE = 'AUG  7 2019'
set 	@BANK_CODE = ''
set 	@EXCSEGMENT = ''
*/

 IF(LEN(@FR_DATE) = 10)
 SET @FR_DATE = CONVERT(DATETIME,@FR_DATE,103)

 IF(LEN(@TO_DATE) = 10)
 SET @TO_DATE = CONVERT(DATETIME,@TO_DATE,103)

 --SET @FR_DATE = CONVERT(DATETIME,@FR_DATE,103)
 --SET @TO_DATE = CONVERT(DATETIME,@TO_DATE,103)

CREATE TABLE [DBO].[#BBDBNAME_LIST] (
	ACCOUNTDB VARCHAR(20)
	,EXCHANGE VARCHAR(6)
	,SEGMENT VARCHAR(10)
	,ACCOUNTSERVER VARCHAR(50)
	,SHAREDB VARCHAR(20)
	) ON [PRIMARY]

DECLARE
	@DB1 VARCHAR(1000)
	,@SQL VARCHAR(5000)
	,@SEGORD1 SMALLINT
	,@MAINREC1 AS CURSOR
	,@ACCOUNTDB1 VARCHAR(20)
	,@SHAREDB1 VARCHAR(20)
	,@ACCOUNTSVR1 VARCHAR(50)
	,@EXCHANGE1 VARCHAR(15)
	,@SEGMENT1 VARCHAR(15)

IF @EXCSEGMENT <> ''
	SELECT @DB1 = " INSERT INTO #BBDBNAME_LIST SELECT ACCOUNTDB, EXCHANGE, SEGMENT, ACCOUNTSERVER, SHAREDB FROM PRADNYA.DBO.VW_REPORTING_MULTICOMPANY (NOLOCK) WHERE EXCHANGE+'~'+SEGMENT IN ('" + REPLACE(@EXCSEGMENT, ',', ''',''') + "') ORDER BY EXCHANGE "
ELSE
	SELECT @DB1 = " INSERT INTO #BBDBNAME_LIST SELECT ACCOUNTDB, EXCHANGE, SEGMENT, ACCOUNTSERVER, SHAREDB FROM PRADNYA.DBO.VW_REPORTING_MULTICOMPANY (NOLOCK) ORDER BY EXCHANGE "

--PRINT @DB1
EXEC (@DB1)



DECLARE @FILENAME   VARCHAR(50)
DECLARE @BATCHNO	INT  
DECLARE @MEMBERCODE VARCHAR(20)
DECLARE @MEMBERNAME	VARCHAR(500)

SELECT @MEMBERCODE = MEMBERCODE, @MEMBERNAME = ISNULL(LTRIM(RTRIM(COMPANY)),'') FROM OWNER (NOLOCK)
SELECT @BATCHNO = ISNULL(MAX(FLDBATCHNO),0)+1 FROM ASIANFILEBATCHNO  
WHERE FLDFILENO = 'BB'  
AND LEFT(FLDFILEDATE,11) = LEFT(GETDATE(),11)
  
IF @BATCHNO = 1  
BEGIN  
	INSERT INTO ASIANFILEBATCHNO VALUES ('BB', @BATCHNO, GETDATE(), GETDATE())  
END  
ELSE  
BEGIN  
	UPDATE ASIANFILEBATCHNO SET FLDBATCHNO = @BATCHNO WHERE FLDFILENO = 'BB' AND LEFT(FLDFILEDATE,11) = LEFT(GETDATE(),11)
END  
  
SET	@FILENAME = @MEMBERCODE + '_BB_' + REPLACE(CONVERT(VARCHAR,GETDATE(),103),'/','') + '_' + RIGHT('00'+CONVERT(VARCHAR,@BATCHNO),2) 


CREATE TABLE #BBLEDGER_PL
(
	VDT DATETIME,
	EDT DATETIME,
	LONG_NAME VARCHAR(150),
	BANK_ACC_NO VARCHAR(30),
	UCC_CODE VARCHAR(30),
	CLTCODE VARCHAR(10),
	CLIENT_PAN VARCHAR(50),
	NARRATION VARCHAR(500),
	VNO VARCHAR(12),
	VTYP INT,
	SETT_NO VARCHAR(10),
	CHQ_NO VARCHAR(30),
	DRAMOUNT MONEY,
	CRAMOUNT MONEY,
	RUNNING_BALANCE MONEY,
	OPBAL MONEY,
	PDT DATETIME,
	BANK_CODE VARCHAR(10),
	EXCHANGE VARCHAR(10),
	SEGMENT VARCHAR(10)
)

 CREATE CLUSTERED INDEX [BBLEDGER_PL1] ON [DBO].[#BBLEDGER_PL]           
 (        
 [CLTCODE] ASC, 
 [UCC_CODE],
 [VNO],
 [VTYP],
 [BANK_ACC_NO],     
 [LONG_NAME],
 [CLIENT_PAN],
 [NARRATION],
 [EDT],
 [SETT_NO]    
) 

SET @MAINREC1 = CURSOR
FOR

SELECT ACCOUNTDB
	,EXCHANGE
	,SEGMENT
	,ACCOUNTSERVER
	,SHAREDB
FROM #BBDBNAME_LIST

SET @SEGORD1 = 1

OPEN @MAINREC1

FETCH NEXT
FROM @MAINREC1
INTO @ACCOUNTDB1
	,@EXCHANGE1
	,@SEGMENT1
	,@ACCOUNTSVR1
	,@SHAREDB1

WHILE @@FETCH_STATUS = 0
BEGIN

	 SET @SQL = "INSERT INTO #BBLEDGER_PL EXEC " + @ACCOUNTSVR1 + "." + @ACCOUNTDB1 + ".DBO.BANK_FUNDS_REPORTING '" + @FR_DATE + "','" + @TO_DATE + "','"  + @EXCHANGE1 + "','"  + @SEGMENT1 + "','"  + @BANK_CODE + "'"
	    --SET @SQL = "INSERT INTO #BBLEDGER_PL EXEC CLASSDATABASELIVE.ACCOUNT.DBO.BANK_FUNDS_REPORTING 'AUG 19 2019','AUG 19 2019','NSE','CAPITAL',''"

	PRINT @SQL
	EXEC (@SQL)

	
FETCH NEXT
	FROM @MAINREC1
	INTO @ACCOUNTDB1
		,@EXCHANGE1
		,@SEGMENT1
		,@ACCOUNTSVR1
		,@SHAREDB1
END

CLOSE @MAINREC1


/* CODE FOR CB */

INSERT INTO #BBLEDGER_PL
SELECT @TO_DATE + ' 23:59:59', @TO_DATE + ' 23:59:59', '','','',BANK_CODE,'', NARRATION = 'Closing Balance','',50,'','',
		CASE WHEN SUM(CRAMOUNT + DRAMOUNT) < 0 THEN SUM(CRAMOUNT + DRAMOUNT) ELSE 0 END , 
		CASE WHEN SUM(CRAMOUNT + DRAMOUNT) >= 0 THEN SUM(CRAMOUNT + DRAMOUNT) ELSE 0 END , 
		0, 0,@TO_DATE + ' 23:59:59' ,BANK_CODE,EXCHANGE, SEGMENT
FROM #BBLEDGER_PL
GROUP BY BANK_CODE, EXCHANGE, SEGMENT



/* CODE FOR CB */


CREATE TABLE #BBLEDGER_PL_DETAILS_FINAL
(
	VDT DATETIME,
	EDT DATETIME,
	LONG_NAME VARCHAR(100),
	BANK_ACC_NO VARCHAR(30),
	UCC_CODE VARCHAR(12),
	CLTCODE VARCHAR(10),
	CLIENT_PAN VARCHAR(30),
	NARRATION VARCHAR(500),
	VNO VARCHAR(12),
	VTYP INT,
	SETT_NO VARCHAR(10),
	CHQ_NO VARCHAR(30),
	DRAMOUNT MONEY,
	CRAMOUNT MONEY,
	RUNNING_BALANCE MONEY,
	OPBAL MONEY,
	PDT DATETIME,
	BANK_CODE VARCHAR(10),
	EXCHANGE VARCHAR(10),
	SEGMENT VARCHAR(10),
	PURPOSE VARCHAR(500),
	SNO INT IDENTITY(1, 1),
	OrderBy INT
)



ALTER TABLE #BBLEDGER_PL
ADD OrderBy INT

UPDATE #BBLEDGER_PL
SET OrderBy = 2
WHERE NARRATION LIKE 'OPENING BALANCE'

UPDATE #BBLEDGER_PL
SET OrderBy = 4
WHERE NARRATION LIKE 'CLOSING BALANCE'

UPDATE #BBLEDGER_PL
SET OrderBy = 3

WHERE OrderBy  IS NULL 


--SELECT * FROM #BBLEDGER_PL
 CREATE CLUSTERED INDEX [BBLEDGER_PL_DETAILS_FINAL1] ON [DBO].[#BBLEDGER_PL_DETAILS_FINAL]           
(          
 [CLTCODE] ASC, 
 [UCC_CODE],
 [VNO],
 [VTYP],
 [BANK_ACC_NO],     
 [LONG_NAME],
 [CLIENT_PAN],
 [NARRATION],
 [EDT],
 [SETT_NO]
)  

INSERT INTO #BBLEDGER_PL_DETAILS_FINAL
SELECT DISTINCT VDT,EDT,LONG_NAME,BANK_ACC_NO,UCC_CODE,CLTCODE,
CLIENT_PAN,NARRATION,VNO,B.VTYP,SETT_NO,CHQ_NO,
DRAMOUNT,CRAMOUNT,RUNNING_BALANCE,OPBAL,PDT,BANK_CODE,
EXCHANGE,SEGMENT, --PURPOSE = PURPOSE_REMARKS,
(CASE WHEN CLTCODE LIKE 'FDR%' AND B.VTYP=2 THEN 'FDR RELEASED' 
	  WHEN CLTCODE LIKE 'FDR%' AND B.VTYP=3 THEN 'FDR CREATED'
	  WHEN BANK_CODE IN (SELECT BANKCODE FROM BANK_PURPOSE_MASTER WHERE PURPOSE='SETTLEMENT ACCOUNT') AND B.CRAMOUNT<>'0' AND B.VTYP=5 THEN 'PAYIN' 
	  WHEN BANK_CODE IN (SELECT BANKCODE FROM BANK_PURPOSE_MASTER WHERE PURPOSE='SETTLEMENT ACCOUNT') AND B.DRAMOUNT<>'0' AND B.VTYP=5 THEN 'PAYOUT'
      WHEN BANK_CODE IN (SELECT BANKCODE FROM BANK_PURPOSE_MASTER WHERE PURPOSE ='SETTLEMENT ACCOUNT') AND B.VTYP IN (2,3) THEN 'Settlement-Payment'  
      WHEN BANK_CODE IN (SELECT BANKCODE FROM BANK_PURPOSE_MASTER WHERE PURPOSE IN ('CLIENT BANK ACCOUNT','OWN/PROPRIETARY ACCOUNT')) AND B.VTYP=5 THEN 'OWN ACCOUNT'  
	  --WHEN BANK_CODE IN (SELECT BANKCODE FROM BANK_PURPOSE_MASTER WHERE PURPOSE IN ('CLIENT','OWN')) AND B.VTYP=5 THEN 'Inter-Client-Bank'  
	  ELSE PURPOSE_REMARKS END) AS PURPOSE,
OrderBy
FROM #BBLEDGER_PL B, PURPOSE_MASTER P 
WHERE B.VTYP = P.VTYP 
ORDER BY BANK_CODE, EXCHANGE, SEGMENT, OrderBy,  VDT, PDT

--INSERT INTO #BBLEDGER_PL_DETAILS_FINAL
--SELECT VDT,EDT,LONG_NAME,BANK_ACC_NO,UCC_CODE,CLTCODE,CLIENT_PAN,NARRATION,VNO,VTYP,SETT_NO,CHQ_NO,DRAMOUNT
--,CRAMOUNT,RUNNING_BALANCE,OPBAL,PDT,BANK_CODE,EXCHANGE,SEGMENT,
--(CASE WHEN BANK_CODE IN (SELECT BANKCODE FROM BANK_PURPOSE_MASTER WHERE PURPOSE='SETTLEMENT') AND CRAMOUNT<>'0' AND VTYP=5 THEN 'PAYOUT' 
--	  WHEN BANK_CODE IN (SELECT BANKCODE FROM BANK_PURPOSE_MASTER WHERE PURPOSE='SETTLEMENT') AND DRAMOUNT<>'0' AND VTYP=5 THEN 'PAYIN'
--      WHEN BANK_CODE IN (SELECT BANKCODE FROM BANK_PURPOSE_MASTER WHERE PURPOSE ='SETTLEMENT') AND VTYP IN (2,3) THEN 'Settlement-Payment'  
--      WHEN BANK_CODE IN (SELECT BANKCODE FROM BANK_PURPOSE_MASTER WHERE PURPOSE IN ('CLIENT','OWN')) AND VTYP=5 THEN 'Inter-Client-Bank' 
--	  ELSE PURPOSE END)AS PURPOSE,OrderBy
--FROM #BBLEDGER_PL_DETAILS_FINAL

UPDATE L SET RUNNING_BALANCE = OPBAL + (SELECT SUM(CRAMOUNT + DRAMOUNT) 
FROM #BBLEDGER_PL_DETAILS_FINAL L1 
WHERE L1.BANK_CODE = L.BANK_CODE AND L1.EXCHANGE = L.EXCHANGE AND L1.SEGMENT = L.SEGMENT AND L1.SNO <= L.SNO) FROM #BBLEDGER_PL_DETAILS_FINAL L

DECLARE
	@MEMBER_CODE VARCHAR(200),
	@BANK_NAME VARCHAR(100),
	@ACCCODE VARCHAR(25)

SELECT @MEMBER_CODE = COMPANY FROM OWNER

--NEED TO APPLY THE LOGIC OF RUNNING BALANCE IN _WRAPPER PROCEDURE 
CREATE TABLE #REPORT_DATA
(
	BANK_CODE VARCHAR(10),
	EXCHANGE VARCHAR(10),
	SEGMENT VARCHAR(10),
	REPORTDATA VARCHAR(2000),
	--SNO INT IDENTITY(1, 1),
	ORDERBY INT,
	ORDERBY_FLAG INT,
	SNO INT
)

--SELECT * FROM #BBLEDGER_PL_DETAILS_FINAL 
--RETURN

INSERT INTO #REPORT_DATA
SELECT BANKCODE =  '', EXCHANGE ='' , SEGMENT='' , REPORTDATA = 'MEMBER NAME,PERIOD,ACCOUNT NAME AND NUMBER,ACCOUNT TYPE,EXCHANGE,SEGMENT TYPE',0,0, 0
UNION ALL
SELECT DISTINCT BANKCODE = A.CLTCODE, A.EXCHANGE, A.SEGMENT, REPORTDATA = @MEMBER_CODE + ',' + REPLACE(CONVERT(VARCHAR, CONVERT(DATETIME, @FR_DATE), 103), '/', '') + ' TO ' +
	REPLACE(CONVERT(VARCHAR, CONVERT(DATETIME, @TO_DATE), 103), '/', '') + ',' 
    + A.LONGNAME + /*',' +  ISNULL(ACCOUNTNO,'') +*/ ','
    + ISNULL(BK.PURPOSE,'')+ ',' +
    --+  ISNULL((CASE WHEN A.EXCHANGE='NSE' AND A.SEGMENT='FUTURES' THEN 'FO' ELSE A.EXCHANGE END ),'')+ ',' +
	+  ISNULL( A.EXCHANGE ,'')+ ',' +
    CASE 
	WHEN A.EXCHANGE+A.SEGMENT IN ('NSEFUTURES','BSEFUTURES') THEN  'FO'
	WHEN A.EXCHANGE+A.SEGMENT IN ('BSECAPITAL','MTFMTF') THEN  'CM'		
	WHEN A.EXCHANGE+A.SEGMENT IN ('NSXFUTURES','BSXFUTURES','MCDFUTURES') THEN  'CDS'
	WHEN A.EXCHANGE+A.SEGMENT IN ('NSECAPITAL') /*AND  BK.SEXCHANGE='DEBT'*/ THEN  'DEBT'
	WHEN A.EXCHANGE+A.SEGMENT IN ('BSECAPITAL') /*AND  BK.SEXCHANGE='CDS'*/ THEN  'CDS'	ELSE 'CM' 		
	END ,0,0, 0
FROM ACMAST_DETAILS A 
RIGHT OUTER JOIN BANK_PURPOSE_MASTER BK
ON A.CLTCODE = BK.BANKCODE 
AND A.EXCHANGE= BK.EXCHANGE
AND A.SEGMENT= BK.SEGMENT
WHERE EXISTS(SELECT BANK_CODE FROM #BBLEDGER_PL_DETAILS_FINAL L 
WHERE A.CLTCODE = L.BANK_CODE AND A.EXCHANGE = L.EXCHANGE AND A.SEGMENT = L.SEGMENT AND A.EXCHANGE NOT IN ('MCX','NCX','NSP') AND A.SEGMENT NOT IN ('SLBS'))


INSERT INTO #REPORT_DATA

--SELECT BANKCODE =  '', EXCHANGE ='' , SEGMENT='' , REPORTDATA = 'DATE	,VALUEDATE	,ACCOUNTNAME 	,BANKACCOUNTNUMBER	,CLIENTCODE	,BACKOFFICECLIENTCODE	,CLIENTPAN	,NARRATION 	,VOUCHERNO	,SETTNO	,REFNO	,PAYMENT(RS)	,RECEIPT(RS)	,BALANCE(RS)	,PURPOSE	,EXCHANGE	,SEGMENT', 1 ,1
--UNION ALL
SELECT   ISNULL(BANK_CODE,''), ISNULL(EXCHANGE,''), ISNULL(SEGMENT,''), REPORTDATA = ISNULL(REPLACE(CONVERT(VARCHAR(10), VDT, 103), '/', '-') ,'')+ ',' + 
ISNULL(REPLACE(CONVERT(VARCHAR(10), EDT, 103), '/', '-'),'') + ',' + ISNULL(LONG_NAME,'') + ',' 
+ ISNULL(BANK_ACC_NO,'') + ',' + ISNULL(UCC_CODE,'') + ',' + 
ISNULL(CLTCODE,'') + ',' + ISNULL(CLIENT_PAN,'') + ',' + ISNULL(REPLACE(NARRATION, ',', ''),'') + ',' + ISNULL(VNO,'') + ',' + ISNULL(SETT_NO, '') + ',' + ISNULL(CHQ_NO, '') + ',' + 
ISNULL(CONVERT(VARCHAR, ABS(DRAMOUNT)),'') + ',' + ISNULL(CONVERT(VARCHAR, CRAMOUNT),'') + ',' + 
CASE WHEN ISNULL(NARRATION,'')= 'Closing Balance' THEN '' ELSE  ISNULL(CONVERT(VARCHAR, RUNNING_BALANCE),'') END + ',' + ISNULL(PURPOSE,'') /*+ ',' +
 ISNULL(EXCHANGE,'')+ ','+ISNULL(SEGMENT,'') */
 ,ISNULL(OrderBy,''), 2, sno
FROM #BBLEDGER_PL_DETAILS_FINAL BL WHERE 
	RUNNING_BALANCE<>'0' 
 --BL.BANK_CODE IN (SELECT LP.BANKCODE  FROM BANK_PURPOSE_MASTER LP WHERE BL.BANK_CODE=LP.BANKCODE AND BL.EXCHANGE=LP.EXCHANGE AND BL.SEGMENT=LP.SEGMENT )
ORDER BY  sno, EXCHANGE, SEGMENT
SELECT  DISTINCT * INTO #REPORT_DATA1 FROM #REPORT_DATA  ORDER BY BANK_CODE,sno,EXCHANGE,SEGMENT,ORDERBY


INSERT INTO #REPORT_DATA1
SELECT  TOP 1 BANK_CODE,EXCHANGE,SEGMENT,REPORTDATA = 'DATE	,VALUE DATE	,ACCOUNT NAME 	,BANK ACCOUNT NO.	,UNIQUE CLIENT CODE(UCC)	,BACK OFFICE CLIENT CODE	,CLIENT PAN	,NARRATION 	,VOUCHER NO. ,SETTLEMENT NO. ,REFERENCE NUMBER	,PAYMENT (Rs.)	,RECEIPT(Rs.),BALANCE(Rs.)	,PURPOSE	,EXCHANGE	,SEGMENT',1,1, sno
FROM #REPORT_DATA1	 
WHERE Bank_Code <> ""
ORDER BY BANK_CODE,sno, EXCHANGE,SEGMENT,ORDERBY


SELECT REPORTDATA FROM #REPORT_DATA1
ORDER BY BANK_CODE,sno,EXCHANGE,SEGMENT,ORDERBY
--
--SELECT  BANK_CODE,Exchange,segment,ORDERBY, ISNULL(REPORTDATA,'')AS REPORTDATA  
--FROM #REPORT_DATA 
--ORDER BY BANK_CODE,Exchange,segment,ORDERBY


--SELECT FILENAME = @FILENAME,  REPORTDATA FROM #REPORT_DATA 
--where BANK_CODE = 'GB001'
--ORDER BY BANK_CODE,Exchange,segment,ORDERBY

GO
