-- Object: PROCEDURE dbo.RPT_WEEKLY_CLIENT_CASH_BALANCE_NEW
-- Server: 10.253.33.91 | DB: MSAJAG
--------------------------------------------------




--EXEC RPT_WEEKLY_CLIENT_CASH_BALANCE_NEW_AHSAN 'FEB  3 2022', 'FEB  3 2022', 'A100026', 'A100026', 'NSE'
--EXEC RPT_WEEKLY_CLIENT_CASH_BALANCE_NEW_AHSAN 'FEB  3 2022', 'FEB  3 2022', 'A100018', 'A100018', 'NSE'
--EXEC RPT_WEEKLY_CLIENT_CASH_BALANCE_NEW 'may  2 2023', 'may  2 2023', 'A10016', 'A10016', 'NSE'
--------- new
CREATE PROCEDURE [dbo].[RPT_WEEKLY_CLIENT_CASH_BALANCE_NEW]
(
  @FROMDATE   VARCHAR(11),
  @TODATE           VARCHAR(11),
  @FROMPARTY  VARCHAR(20) = 'A00000',
  @TOPARTY    VARCHAR(20) = 'ZZZZZZZ',
  @EXCHANGE   VARCHAR(3)  = 'NSE',
  @flag varchar(10) = ''
)
AS

--DECLARE
--  @FROMDATE   VARCHAR(11),
--  @TODATE           VARCHAR(11),
--  @FROMPARTY  VARCHAR(20) = 'A00000',
--  @TOPARTY    VARCHAR(20) = 'ZZZZZZZ',
--  @EXCHANGE   VARCHAR(3)  = 'NSE',
--  @flag varchar(10) = ''

--  SELECT 
--  @FROMDATE   ='SEP 21 2022',
--  @TODATE     ='SEP 21 2022',
--  @FROMPARTY  ='A00000',
--  @TOPARTY    ='BBBBB',
--  @EXCHANGE   ='NSE',
--  @flag       =''

DECLARE @FROMDT         INT,
            @TODT       INT,
            @RPTDATE    VARCHAR(11),
            @FILENAMEHS VARCHAR(100),
            @FILENAMENH VARCHAR(100),
            @PANNO            VARCHAR(20),
            @BATCHNO    INT,
            @FROFYMDATE VARCHAR(11),
            @FRDATE_NEXT VARCHAR(11)

DECLARE
		@@MFSS_FLAG BIT,
		@@MARGIN_FLAG BIT,
		@@PARENT_FLAG BIT,
		@@CLIENT_BANK_ACC varchar(20)

	SELECT @@MFSS_FLAG = MFSS_FLAG, @@MARGIN_FLAG = MARGIN_FLAG, @@PARENT_FLAG = PARENT_FLAG, 
        @@CLIENT_BANK_ACC = CLIENT_BANK_ACC FROM MSAJAG..WEEKLY_CASH_BALANCES_SETTING
 /*SELECT * FROM ACCOUNT..CLIENT_CASH_ACTIVE_LOG WHERE STATUS_FLAG = 0*/
   
    DECLARE @MX DATE 
    SELECT @MX = MAX(STATUS_FROM_DATE ) FROm ACCOUNT..CLIENT_CASH_ACTIVE_LOG  WITH(NOLOCK) 
	where STATUS_FROM_DATE <= @FROMDATE
    
    IF OBJECT_ID('tempdb..#CLIENT_CASH_ACTIVE_LOG_temp') IS NOT NULL
      DROP TABLE #CLIENT_CASH_ACTIVE_LOG_temp
      Select * INTO #CLIENT_CASH_ACTIVE_LOG_temp from ACCOUNT..CLIENT_CASH_ACTIVE_LOG  where 1=0

    --IF (@FROMDATE >=@MX)
      INSERT INTO #CLIENT_CASH_ACTIVE_LOG_temp
      SELECT * FROM ACCOUNT..CLIENT_CASH_ACTIVE_LOG 
               WHERE STATUS_FLAG = 0 AND STATUS_FROM_DATE  = @MX --and @FROMDATE between STATUS_FROM_DATE and status_to_date
    --ELSE 
    --BEGIN
    -- INSERT INTO #CLIENT_CASH_ACTIVE_LOG_temp
    --SELECT * FROM ACCOUNT..CLIENT_CASH_ACTIVE_LOG 
    --            WHERE STATUS_FLAG = 0 AND @FROMDATE between STATUS_FROM_DATE and status_to_date
    --END

	--select *from #CLIENT_CASH_ACTIVE_LOG_temp where cltcode= 'A10016'
	--return 

   CREATE INDEX CLTCODE ON #CLIENT_CASH_ACTIVE_LOG_TEMP(CLTCODE)

     ;
WITH CTE 
AS
(
  SELECT *,ROw_number() OVER(Partition by CLTCODE,	STATUS_FROM_DATE,	STATUS_TO_DATE	,STATUS_FLAG  order by CLTCODE ) RNK FROM #CLIENT_CASH_ACTIVE_LOG_temp
  WHERE STATUS_FLAG = 0  
)
DELETE FROM CTE WHERE RNK>1
 
 IF OBJECT_ID('tempdb..#CL_LIST') IS NOT NULL
    DROP TABLE #CL_LIST

CREATE TABLE #CL_LIST    
(    
 PARTY_CODE VARCHAR(10),    
 PARTY_NAME VARCHAR(100),    
 CLIENT_PAN VARCHAR(50),
 CL_TYPE VARCHAR(10),
 PARENT_CODE VARCHAR(10)   
)    
    
INSERT INTO #CL_LIST    
SELECT CL_CODE, LONG_NAME, PAN_GIR_NO, CL_TYPE, PARENTCODE = CASE WHEN @@PARENT_FLAG = 1 THEN PARENTCODE ELSE CL_CODE END
FROM MSAJAG..VW_CLIENT_DETAILS_DATA  (NOLOCK)  
WHERE CL_CODE BETWEEN @FROMPARTY AND @TOPARTY    

IF @@PARENT_FLAG = 1
BEGIN
	UPDATE C 
	SET C.PARTY_NAME =C1.PARTY_NAME, 
	    C.CLIENT_PAN = C1.CLIENT_PAN
	FROM #CL_LIST C
	INNER JOIN #CL_LIST C1 ON C.PARTY_CODE = C1.PARENT_CODE
	--,(SELECT * FROM #CL_LIST WHERE PARTY_CODE = PARENT_CODE) C1
	--WHERE C.PARTY_CODE = C1.PARENT_CODE
END
IF OBJECT_ID('tempdb..#CLIENT_LIST') IS NOT NULL
    DROP TABLE #CLIENT_LIST

CREATE TABLE #CLIENT_LIST
(
      CLTCODE VARCHAR(10)
)
CREATE INDEX #CL ON #CLIENT_LIST (CLTCODE)
CREATE NONCLUSTERED INDEX [CLLIST] ON #CLIENT_LIST
		(
			[CLTCODE] ASC
		)

		EXEC GET_SEBI_AUDIT_CLIENT_LIST_SEBI 
		'', 
		@FROMDATE,
		1 

SELECT      @TODT = DATEDIFF(DAY, CONVERT(DATETIME, @FROMDATE, 109), CONVERT(dATETIME, @TODATE, 109))
SELECT      @PANNO = ISNULL(LTRIM(RTRIM(PANNO)),'') FROM OWNER (NOLOCK)
SELECT      @BATCHNO = ISNULL(MAX(FLDBATCHNO),0)+1 FROM ASIANFILEBATCHNO 
            WHERE FLDFILENO = 'CE' 
                  AND LEFT(FLDFILEDATE,11) = LEFT(GETDATE(),11)

  IF @BATCHNO = 1 
  BEGIN 
        INSERT INTO ASIANFILEBATCHNO VALUES ('CE', @BATCHNO, GETDATE(), GETDATE()) 
  END 
  ELSE 
  BEGIN 
        UPDATE ASIANFILEBATCHNO SET FLDBATCHNO = @BATCHNO WHERE FLDFILENO = 'CE' AND LEFT(FLDFILEDATE,11) = LEFT(GETDATE(),11)
  END 
  SET   @FILENAMEHS = @PANNO + '_CE_' + REPLACE(CONVERT(VARCHAR,CONVERT(DATETIME,@TODATE,109),103),'/','') + '_' + RIGHT('00'+CONVERT(VARCHAR,@BATCHNO),2) + '.CSV'
 
 IF OBJECT_ID('tempdb..#CLIENT_CASH_DETAILS_tmp') IS NOT NULL
    DROP TABLE #CLIENT_CASH_DETAILS_tmp
 SELECT * INTO #CLIENT_CASH_DETAILS_tmp FROM ACCOUNT..CLIENT_CASH_DETAILS WHERE REPORT_DATE BETWEEN @FROMDATE AND @TODATE + ' 23:59' AND UCC BETWEEN @FROMPARTY AND @TOPARTY
 CREATE INDEX IX_#CLIENT_CASH_DETAILS_TMP ON #CLIENT_CASH_DETAILS_TMP (SNO,UCC)
 
 
 --IF OBJECT_ID('tempdb..#CLIENT_CASH_DETAILS_tmp') IS NOT NULL
 --   DROP TABLE #CLIENT_CASH_LED_BALANCES_tmp
 --Select * INTO #CLIENT_CASH_LED_BALANCES_tmp from ACCOUNT..CLIENT_CASH_LED_BALANCES  L 
 --WHERE  EXIST

/* CHANGE IN QUERY TO GET THE NEW COLUMNS */ 

SELECT L.* INTO #CLIENT_CASH_LED_BALANCES from ACCOUNT..CLIENT_CASH_LED_BALANCES  L
 INNER JOIN #CLIENT_CASH_DETAILS_tmp C ON C.SNO = L.SNO 

 CREATE INDEX SNO ON #CLIENT_CASH_LED_BALANCES (SNO)


SELECT 
TRADING_PAN = LTRIM(RTRIM(ISNULL(TRADING_PAN, ''))), REPORT_DATE,UCC=LTRIM(RTRIM(ISNULL(PARENTCODE, ''))),
CLIENT_PAN = LTRIM(RTRIM(ISNULL(CLIENT_PAN, ''))),CLIENT_NAME = LTRIM(RTRIM(ISNULL(CLIENT_NAME, ''))),
SEGMENT_INDICATOR = CASE WHEN EXCHANGE = 'MTF' THEN 'MTF' ELSE 'NON MTF' END, EXCHANGE, SEGMENT, 
--VDT_BAL = CASE WHEN EXCHANGE = 'MTF' THEN CASE WHEN ROUND(VDT_BAL, 2) + ROUND(ISNULL(CASH_COLL_MTF_POSITIONS,0), 2) < 0 THEN ROUND(VDT_BAL, 2) ELSE -ROUND(ISNULL(CASH_COLL_MTF_POSITIONS,0), 2) END ELSE ROUND(VDT_BAL, 2) END, 
-- Below VDT_BAL code added on 18th Feb 2022 Yogesh
VDT_BAL = ROUND(VDT_BAL, 2), --CASE WHEN EXCHANGE = 'MTF' THEN CASE WHEN ROUND(VDT_BAL, 2) + ROUND(ISNULL(CASH_COLL_MTF_POSITIONS,0), 2) > 0 THEN ROUND(VDT_BAL, 2) - (ROUND(VDT_BAL, 2) + ROUND(ISNULL(CASH_COLL_MTF_POSITIONS,0), 2)) ELSE ROUND(VDT_BAL, 2) END ELSE ROUND(VDT_BAL, 2) END,
EDT_BAL = ROUND(EDT_BAL, 2),PEAK_FINANCIAL_LEDGER = ROUND(PEAK_FINANCIAL_LEDGER, 2), BG, FDR, GOV_IND_SEC, GILT_FUNDS, EPI_LEDGER,POOL_ACCOUNT,CHQ_DEPOSITS,CHQ_ISSUE, 
COMM_VALUE,LAST_SETT_DATE,OPEN_BILL1, OPEN_BILL2, MARGIN_REQ, 
CASH_COLL_MTF_POSITIONS = CASE WHEN EXCHANGE = 'MTF' THEN 
                                    CASE WHEN ROUND(VDT_BAL, 2) + ROUND(ISNULL(CASH_COLL_MTF_POSITIONS,0), 2) > 0 
                                           THEN CONVERT(VARCHAR, ROUND(VDT_BAL, 2) + ROUND(ISNULL(CASH_COLL_MTF_POSITIONS,0), 2)) 
                                              ELSE CONVERT(VARCHAR, 0) END 
                                                    ELSE 'NA' END, 
UNCLAIMED_CLIENT_FUNDS = CASE WHEN REPORT_DATE BETWEEN STATUS_FROM_DATE AND STATUS_TO_DATE THEN 'YES' ELSE 'NO' END 
INTO #REPORT_DATA 
FROM #CLIENT_CASH_DETAILS_tmp C 
INNER JOIN #CLIENT_CASH_LED_BALANCES L WITH(NOLOCK) ON C.SNO = L.SNO 
--(SELECT * FROM ACCOUNT..CLIENT_CASH_DETAILS WHERE REPORT_DATE BETWEEN @FROMDATE AND @TODATE + ' 23:59' AND UCC BETWEEN @FROMPARTY AND @TOPARTY) C 
--INNER JOIN   ACCOUNT..CLIENT_CASH_LED_BALANCES  L 
--ON C.SNO = L.SNO 
LEFT OUTER JOIN  #CLIENT_CASH_ACTIVE_LOG_temp A ON UCC = A.CLTCODE 

--select * from #CLIENT_CASH_ACTIVE_LOG_temp  where ucc = @FROMPARTY
--return

CREATE INDEX IX_#REPORT_DATA111 ON #REPORT_DATA (UCC) INCLUDE (REPORT_DATE ,SEGMENT_INDICATOR,UNCLAIMED_CLIENT_FUNDS)
 		 
---------------- AHSAN
 DELETE FROM #REPORT_DATA WHERE UCC='BBBB'

declare
      @TRADING_PAN varchar(10)
      
SELECT TOP 1 @TRADING_PAN = TRADING_PAN FROM #REPORT_DATA
/*delete R from #REPORT_DATA R WHERE VDT_BAL = 0 and EDT_BAL = 0 and PEAK_FINANCIAL_LEDGER = 0 and BG = 0 and FDR = 0 and GOV_IND_SEC = 0and GILT_FUNDS = 0
         and EPI_LEDGER  = 0 and POOL_ACCOUNT = 0 and CHQ_DEPOSITS = 0 and CHQ_ISSUE = 0 and COMM_VALUE = 0*/

   IF OBJECT_ID('tempdb..#GRP_DLETEE', 'U') IS NOT NULL
        DROP TABLE #GRP_DLETEE
        SELECT UCC, REPORT_DATE , SEGMENT_INDICATOR 
        INTO #GRP_DLETEE
        FROM #REPORT_DATA 
        GROUP BY UCC, REPORT_DATE , SEGMENT_INDICATOR 
        HAVING SUM(VDT_BAL) = 0 AND SUM(EDT_BAL) = 0 
        AND SUM(PEAK_FINANCIAL_LEDGER) = 0 AND SUM(BG) = 0 AND SUM(FDR) = 0 AND SUM(GOV_IND_SEC) = 0
        AND SUM(GILT_FUNDS) = 0 AND SUM(EPI_LEDGER)  = 0 AND SUM(POOL_ACCOUNT) = 0 
        AND SUM(CHQ_DEPOSITS) = 0 AND SUM(CHQ_ISSUE) = 0 AND SUM(COMM_VALUE) = 0

     CREATE INDEX IX_#GRP_DLETEE ON #GRP_DLETEE (UCC, REPORT_DATE ,SEGMENT_INDICATOR) 

	 DELETE G FROM #GRP_DLETEE G WHERE EXISTS (
		SELECT  UCC FROM #REPORT_DATA R WHERE G.UCC=R.UCC AND EXCHANGE IN ('MCX','NCX') AND ( VDT_BAL <>0 OR EDT_BAL <>0))
     
 
IF OBJECT_ID('tempdb..#GRP_DLETEE_1', 'U') IS NOT NULL
DROP TABLE #GRP_DLETEE_1
SELECT UCC, REPORT_DATE 
    INTO #GRP_DLETEE_1
    FROM #REPORT_DATA 
    GROUP BY UCC, REPORT_DATE  HAVING SUM(VDT_BAL) = 0 AND SUM(EDT_BAL) = 0 
          AND SUM(PEAK_FINANCIAL_LEDGER) = 0 AND SUM(BG) = 0 AND SUM(FDR) = 0 AND SUM(GOV_IND_SEC) = 0
          AND SUM(GILT_FUNDS) = 0 AND SUM(EPI_LEDGER)  = 0 AND SUM(POOL_ACCOUNT) = 0 
          AND SUM(CHQ_DEPOSITS) = 0 AND SUM(CHQ_ISSUE) = 0 AND SUM(COMM_VALUE) = 0

	
CREATE INDEX IX_#GRP_DLETEE_1 ON #GRP_DLETEE_1 (UCC, REPORT_DATE ) 

  	  DELETE G FROM #GRP_DLETEE_1 G WHERE EXISTS (
		SELECT  UCC FROM #REPORT_DATA R WHERE G.UCC=R.UCC AND EXCHANGE IN ('MCX','NCX') AND ( VDT_BAL <>0 OR EDT_BAL <>0))


 DELETE R FROM  #REPORT_DATA R
       INNER JOIN #GRP_DLETEE R1 ON R.UCC = R1.UCC AND R.REPORT_DATE = R1.REPORT_DATE AND R.SEGMENT_INDICATOR = R1.SEGMENT_INDICATOR
       INNER JOIN #GRP_DLETEE_1 R2 ON R.UCC = R2.UCC AND R.REPORT_DATE = R2.REPORT_DATE  
      AND EXISTS(SELECT PARTY_CODE FROM #CL_LIST XY WHERE XY.PARTY_CODE = R.UCC)
      
     

--DELETE R FROM #REPORT_DATA R
--    INNER JOIN #GRP_DLETEE R1 ON R.UCC = R1.UCC AND R.REPORT_DATE = R1.REPORT_DATE
--    AND EXISTS(SELECT PARTY_CODE FROM #CL_LIST XY WHERE XY.PARTY_CODE = R.UCC)

--DELETE R FROM #REPORT_DATA R, 
--(
--SELECT UCC, REPORT_DATE FROM #REPORT_DATA GROUP BY UCC, REPORT_DATE HAVING SUM(VDT_BAL) = 0 AND SUM(EDT_BAL) = 0 
--AND SUM(PEAK_FINANCIAL_LEDGER) = 0 AND SUM(BG) = 0 AND SUM(FDR) = 0 AND SUM(GOV_IND_SEC) = 0
--AND SUM(GILT_FUNDS) = 0 AND SUM(EPI_LEDGER)  = 0 AND SUM(POOL_ACCOUNT) = 0 
--AND SUM(CHQ_DEPOSITS) = 0 AND SUM(CHQ_ISSUE) = 0 AND SUM(COMM_VALUE) = 0
--) R1
--WHERE R.UCC = R1.UCC AND R.REPORT_DATE = R1.REPORT_DATE
--AND R.UCC NOT IN(SELECT PARTY_CODE FROM #CL_LIST)

CREATE TABLE #CAL_DATES
(
  CAL_DATES DATETIME
)
INSERT INTO #CAL_DATES
EXEC ACCOUNT..GET_CAL_DATES @FROMDATE, @TODATE

create index IX_#CAL_DATES ON #CAL_DATES(CAL_DATES)  
 
INSERT INTO #REPORT_DATA
SELECT TRADING_PAN = LTRIM(RTRIM(ISNULL(@TRADING_PAN, ''))), CAL_DATES, PARTY_CODE = LTRIM(RTRIM(ISNULL(PARENT_CODE, ''))), CLIENT_PAN = LTRIM(RTRIM(ISNULL(CLIENT_PAN, ''))), 
PARTY_NAME = LTRIM(RTRIM(ISNULL(PARTY_NAME, ''))), 'NON MTF', 'NSE', 'CAPITAL',  
VDT_BAL = 0, EDT_BAL = 0,PEAK_FINANCIAL_LEDGER = 0, BG = 0, FDR = 0, GOV_IND_SEC = 0, GILT_FUNDS = 0, 
EPI_LEDGER = 0,POOL_ACCOUNT = 0,CHQ_DEPOSITS = 0,CHQ_ISSUE = 0,COMM_VALUE = 0,LAST_SETT_DATE = 'NA',
OPEN_BILL1=0, OPEN_BILL2=0, MARGIN_REQ = 0, 'NA', 
CASE WHEN CAL_DATES BETWEEN STATUS_FROM_DATE AND STATUS_TO_DATE THEN 'YES' ELSE 'NO' END
FROM #CL_LIST C 
LEFT OUTER JOIN #CLIENT_CASH_ACTIVE_LOG_temp A ON PARTY_CODE = A.CLTCODE
INNER JOIN #CLIENT_LIST CL ON PARTY_CODE = CL.CLTCODE , #CAL_DATES CD
WHERE PARTY_CODE = CL.CLTCODE
AND NOT EXISTS(SELECT UCC FROM #REPORT_DATA WHERE UCC = CL.CLTCODE AND REPORT_DATE = CD.CAL_DATES AND SEGMENT_INDICATOR = 'NON MTF')
AND PARTY_CODE BETWEEN @FROMPARTY AND @TOPARTY

--drop table TMP_NEW_Condition_REPORT_DATA
--select * INTO TMP_NEW_Condition_REPORT_DATA from #REPORT_DATA
--return;

--INSERT INTO #REPORT_DATA
--SELECT TRADING_PAN = LTRIM(RTRIM(ISNULL(@TRADING_PAN, ''))), CAL_DATES, PARTY_CODE = LTRIM(RTRIM(ISNULL(PARENT_CODE, ''))), CLIENT_PAN = LTRIM(RTRIM(ISNULL(CLIENT_PAN, ''))), PARTY_NAME = LTRIM(RTRIM(ISNULL(PARTY_NAME, ''))), 'NON MTF', 'NSE', 'CAPITAL',  VDT_BAL = 0, EDT_BAL = 0,PEAK_FINANCIAL_LEDGER = 0, BG = 0, FDR = 0, GOV_IND_SEC = 0, GILT_FUNDS = 0, EPI_LEDGER = 0,POOL_ACCOUNT = 0,CHQ_DEPOSITS = 0,CHQ_ISSUE = 0,COMM_VALUE = 0,LAST_SETT_DATE = 'NA',OPEN_BILL1=0, OPEN_BILL2=0, MARGIN_REQ = 0, 'NA', CASE WHEN CAL_DATES BETWEEN STATUS_FROM_DATE AND STATUS_TO_DATE THEN 'YES' ELSE 'NO' END
--FROM #CL_LIST C 
--LEFT OUTER JOIN (SELECT * FROM #CLIENT_CASH_ACTIVE_LOG_temp) A
--ON PARTY_CODE = A.CLTCODE, #CLIENT_LIST CL, #CAL_DATES CD
--WHERE PARTY_CODE = CL.CLTCODE
--AND NOT EXISTS(SELECT UCC FROM #REPORT_DATA WHERE UCC = CL.CLTCODE AND REPORT_DATE = CAL_DATES AND SEGMENT_INDICATOR = 'NON MTF')
--AND PARTY_CODE BETWEEN @FROMPARTY AND @TOPARTY

/*CREATE TABLE #LAST_SETTLE

      (

            CLTCODE VARCHAR(10),

            LAST_SETT_DATE VARCHAR(20),

            chk_date datetime

      )

        EXEC ACCOUNT.DBO.Get_last_setttle_date
      @TODATE, @EXCHANGE
      --'BSE', 'A'

        UPDATE C SET LAST_SETT_DATE = CASE WHEN chk_date <= CONVERT(DATETIME,REPORT_DATE,105) THEN L.LAST_SETT_DATE ELSE C.LAST_SETT_DATE END

        FROM #REPORT_DATA C,  #LAST_SETTLE L  WHERE   UCC = CLTCODE

 

        truncate table #LAST_SETTLE

 

        EXEC ACCOUNT.DBO.Get_last_setttle_date

      @FROMDATE,

      'BSE', 'A'

 

 

        UPDATE C SET LAST_SETT_DATE = CASE WHEN chk_date <= CONVERT(DATETIME,REPORT_DATE,105) THEN L.LAST_SETT_DATE ELSE C.LAST_SETT_DATE END

        FROM #REPORT_DATA C,  #LAST_SETTLE L  WHERE   UCC = CLTCODE AND C.LAST_SETT_DATE IN('NA', 'ND', '')

		*/

		UPDATE	D
		SET		LAST_SETT_DATE = --CONVERT(VARCHAR,SETT_DATE, 105)
		case when SETT_DATE <= CONVERT(VARCHAR(11), CONVERT(datetime,REPORT_DATE, 105), 109) + ' 23:59' then CONVERT(VARCHAR,SETT_DATE, 105) else 'NA' end
		FROM	#REPORT_DATA D,
					(
					SELECT  party_code, SETT_DATE = max(SCCS_SettDate_Last) 
					from MSAJAG.dbo.tbl_SEBI_PAYOUT_CCE_Reporting (Nolock)--, #COLL D
					WHERE SCCS_SettDate_Last >= @FROMDATE 
					--and SCCS_SettDate_Last <= @TODATE 
					GROUP BY party_code
				) D1
		WHERE	D.UCC = party_code

		UPDATE	D
		SET		LAST_SETT_DATE = case when LAST_SETT_DATE = 'NA' then CONVERT(VARCHAR,SETT_DATE, 105) else LAST_SETT_DATE end
		FROM	#REPORT_DATA D,
				(
					SELECT  
          party_code, SETT_DATE = max(SCCS_SettDate_Last) from MSAJAG.dbo.tbl_SEBI_PAYOUT_CCE_Reporting (Nolock)--, #COLL D
					WHERE SCCS_SettDate_Last < @FROMDATE
					GROUP BY party_code
				) D1
		WHERE	ucc = party_code

 UPDATE #REPORT_DATA SET CLIENT_PAN='NNNNN1111N'
	WHERE CLIENT_PAN LIKE '%[^0-9A-Za-z]%' OR LEN(CLIENT_PAN) <> '10' OR RIGHT(CLIENT_PAN, 1) LIKE '%[^A-Za-z]%' OR CLIENT_PAN='NNNNN1111N'

  /* Below condition commented on 27/03/2023 based on sandip mail  
	UPDATE #REPORT_DATA SET CLIENT_PAN='NNNNN1111N', UNCLAIMED_CLIENT_FUNDS = 'YES' 
	WHERE CLIENT_PAN LIKE '%[^0-9A-Za-z]%' OR LEN(CLIENT_PAN) <> '10' OR RIGHT(CLIENT_PAN, 1) LIKE '%[^A-Za-z]%' OR CLIENT_PAN='NNNNN1111N'

	UPDATE A SET UNCLAIMED_CLIENT_FUNDS = 'YES' FROM #REPORT_DATA A WHERE CLIENT_PAN IN 
	(SELECT CLIENT_PAN FROM 
	(SELECT DISTINCT UCC,CLIENT_PAN FROM #REPORT_DATA) A1 GROUP BY CLIENT_PAN HAVING COUNT (*) > 1)

	Below condition commented on 27/03/2023 based on sandip mail  */



  /*below patch added on 30 Sep 2022*/

		DELETE A 
		FROM CCE_UNCLAIMED_CLIENT_FUNDS_ANG A  WITH(NOLOCK) 
		WHERE REPORT_DATE =@FROMDATE AND UCC BETWEEN @FROMPARTY AND @TOPARTY

		INSERT INTO CCE_UNCLAIMED_CLIENT_FUNDS_ANG
		(TRADING_PAN,REPORT_DATE,UCC,CLIENT_PAN,CLIENT_NAME,SEGMENT_INDICATOR,EXCHANGE,SEGMENT
		,VDT_BAL,EDT_BAL,PEAK_FINANCIAL_LEDGER,BG,FDR,GOV_IND_SEC,GILT_FUNDS,EPI_LEDGER
		,POOL_ACCOUNT,CHQ_DEPOSITS,CHQ_ISSUE,COMM_VALUE,LAST_SETT_DATE,OPEN_BILL1,OPEN_BILL2,MARGIN_REQ
		,CASH_COLL_MTF_POSITIONS,UNCLAIMED_CLIENT_FUNDS,RUNDATE
		)
		SELECT 
		TRADING_PAN,REPORT_DATE,UCC,CLIENT_PAN,CLIENT_NAME,SEGMENT_INDICATOR,EXCHANGE,SEGMENT
		,VDT_BAL,EDT_BAL,PEAK_FINANCIAL_LEDGER,BG,FDR,GOV_IND_SEC,GILT_FUNDS,EPI_LEDGER
		,POOL_ACCOUNT,CHQ_DEPOSITS,CHQ_ISSUE,COMM_VALUE,LAST_SETT_DATE,OPEN_BILL1,OPEN_BILL2,MARGIN_REQ
		,CASH_COLL_MTF_POSITIONS,UNCLAIMED_CLIENT_FUNDS, CONVERT(DATE,GETDATE() )
		FROM #REPORT_DATA 
		WHERE UNCLAIMED_CLIENT_FUNDS = 'YES' AND UCC BETWEEN @FROMPARTY AND @TOPARTY
-- NEW PATCH AS PER 26/12/2022 --
  
       /*END patch added on 30 Sep 2022*/

--DELETE FROM #REPORT_DATA WHERE UCC LIKE '%[^0-9A-Za-z]%'

/*New Code Start 2022 Feb 09*/
 
 SELECT REPORT_DATE, PARTY_CODE = UCC, EXCHANGE, SEGMENT, MARGIN_REQ
    INTO #MARGIN_BAL 
    FROM (SELECT SNO, REPORT_DATE, UCC, CLIENT_PAN FROM #CLIENT_CASH_DETAILS_tmp  ) C
	               INNER JOIN #CLIENT_CASH_LED_BALANCES D
    ON C.SNO = D.SNO AND MARGIN_REQ <> 0

	CREATE INDEX PARTY_CODE ON #MARGIN_BAL(PARTY_CODE,REPORT_DATE,EXCHANGE,SEGMENT)

    
    SELECT REPORT_DATE = PROCESS_DT, PARTY_CODE, EXCHANGE, SEGMENT, COLL = SUM(APPROVED_SEC_CASH_WNCL + APPROVED_SEC_NONCASH_WNCL + APPROVED_SEC_CASH_WCM + APPROVED_SEC_NONCASH_WCM + NONAPPROVED_SEC_RET_WCM)
    INTO #COLL_MARGIN 
    FROM MSAJAG.DBO.CLIENT_COLLATERAL_REPORTING_DETAILS
    WHERE PROCESS_DT BETWEEN @FROMDATE AND @TODATE
    AND APPROVED_SEC_CASH_WNCL + APPROVED_SEC_NONCASH_WNCL + APPROVED_SEC_CASH_WCM + APPROVED_SEC_NONCASH_WCM + NONAPPROVED_SEC_RET_WCM <> 0
    GROUP BY PARTY_CODE, EXCHANGE, SEGMENT, PROCESS_DT
    
    SELECT REPORT_DATE = M.REPORT_DATE, PARTY_CODE = M.PARTY_CODE, EXCHANGE = M.EXCHANGE, SEGMENT = M.SEGMENT, 
    MARGIN_REQ = CASE WHEN ABS(MARGIN_REQ) >  ABS(ISNULL(COLL, 0)) THEN ABS(MARGIN_REQ) - ABS(ISNULL(COLL, 0)) ELSE 0 END
    INTO #MARGIN_SHORTAGE
    FROM #MARGIN_BAL M
	    LEFT OUTER JOIN #COLL_MARGIN C
	    ON M.PARTY_CODE = C.PARTY_CODE
	    AND M.REPORT_DATE = C.REPORT_DATE
	    AND M.EXCHANGE = C.EXCHANGE
	    AND M.SEGMENT = C.SEGMENT
    CREATE TABLE #NET_MARGIN_BALANCE
    (
	    UCC VARCHAR(10),
	    REPORT_DATE DATETIME,
	    TOTAL_MARGIN MONEY
    )

    INSERT INTO #NET_MARGIN_BALANCE
    SELECT UCC, REPORT_DATE = R.REPORT_DATE, TOTAL_MARGIN = CASE WHEN SUM(EDT_BAL) > SUM(ISNULL(M.MARGIN_REQ, 0)) AND SUM(EDT_BAL) > 0 THEN SUM(ISNULL(M.MARGIN_REQ, 0)) ELSE CASE WHEN SUM(EDT_BAL) > 0 THEN SUM(EDT_BAL) ELSE 0 END END
    FROM #REPORT_DATA R LEFT OUTER JOIN #MARGIN_SHORTAGE M ON R.REPORT_DATE = M.REPORT_DATE AND R.UCC = M.PARTY_CODE
    GROUP BY UCC, R.REPORT_DATE
/* LOGIC END  2022-02-09*/

CREATE TABLE #FINAL_dATA
(
  SNO INT IDENTITY(1, 1),
  FILE_NAMEING VARCHAR(200),
  REPORTDATE VARCHAR(10),
  UCC VARCHAR(10),
  REPORT_DATA VARCHAR(8000)
)
 --SELECT *, RPT_DATE = GETDATE() INTO FINAL_DATA_TOTALCHK FROM #REPORT_DATA (Nolock)
 CREATE INDEX #DATE ON #FINAL_DATA(REPORTDATE,SNO)
 

/*INSERT INTO #FINAL_DATA
SELECT @FILENAMEHS, CONVERT(VARCHAR(10), CONVERT(DATETIME, @FROMDATE, 109), 105), UCC = '00000', 'TRADING MEMBER PAN,DATE,UNIQUE CLIENT CODE,CLIENT PAN,CLIENT NAME,MTF/ NON MTF INDICATOR,FINANCIAL LEDGER BALANCE-A,FINANCIAL LEDGER BALANCE (CLEAR)-B,Peak Financial Ledger Balance (clear)-C,FINANCIAL LEDGER BALANCE-MCX,FINANCIAL LEDGER BALANCE-NCDEX,FINANCIAL LEDGER BALANCE-ICEX,BANK GUARANTEE (BG),FIXED DEPOSIT RECEIPT (FDR),GOVERNMENT OF INDIA SECURITIES (GSEC),GILT FUNDS,Credit entry in ledger in lieu of EPI,Pool Account,Uncleared Cheques,Value of Commodities,Cash Collateral for MTF Positions,Unclaimed/Unsettled Client Funds,Client Bank Account No.,LAST SETTLEMENT DATE,ES INFORMATION TYPE,Value'
--UNION ALL
INSERT INTO #FINAL_DATA
SELECT @FILENAMEHS, CONVERT(VARCHAR(10), REPORT_DATE, 105), UCC, TRADING_PAN + ',' + CONVERT(VARCHAR(10), REPORT_DATE, 105) + ',' + UCC + ',' + CLIENT_PAN + ',' + replace(CLIENT_NAME,',','') + ',' + SEGMENT_INDICATOR
+ ','
+ CONVERT(VARCHAR, SUM(VDT_BAL)) + ',' + CONVERT(VARCHAR, SUM(EDT_BAL)) + ',' + CONVERT(VARCHAR, SUM(PEAK_FINANCIAL_LEDGER)) + ','
+ CONVERT(VARCHAR, SUM(CASE WHEN EXCHANGE = 'MCX' THEN EDT_BAL ELSE 0 END)) + ','
+ CONVERT(VARCHAR, SUM(CASE WHEN EXCHANGE = 'NCX' THEN EDT_BAL ELSE 0 END)) + ','
+ CONVERT(VARCHAR, SUM(CASE WHEN EXCHANGE = 'ICX' THEN EDT_BAL ELSE 0 END)) + ','
+ CONVERT(VARCHAR, SUM(BG)) + ',' + CONVERT(VARCHAR, SUM(FDR)) + ',' + CONVERT(VARCHAR, SUM(GOV_IND_SEC)) + ',' + CONVERT(VARCHAR, SUM(GILT_FUNDS)) + ','
+ CONVERT(VARCHAR, SUM(EPI_LEDGER)) + ',' + CONVERT(VARCHAR, SUM(POOL_ACCOUNT)) + ',' + CONVERT(VARCHAR, SUM(CHQ_DEPOSITS))
+ ',' + CONVERT(VARCHAR, SUM(COMM_VALUE)) + ',' 
+ CONVERT(VARCHAR, MAX(CASH_COLL_MTF_POSITIONS)) + ',' + UNCLAIMED_CLIENT_FUNDS + ',' + CASE WHEN UNCLAIMED_CLIENT_FUNDS = 'YES' THEN @@CLIENT_BANK_ACC ELSE 'NA' END + ',' + CASE WHEN UNCLAIMED_CLIENT_FUNDS = 'YES' THEN 'NA' ELSE CONVERT(VARCHAR, MAX(LAST_SETT_DATE)) END +','
--+ CONVERT(VARCHAR, MAX(LAST_SETT_DATE))
+ ',NA, NA'
FROM #REPORT_DATA
GROUP BY TRADING_PAN, CONVERT(VARCHAR(10), REPORT_DATE, 105), UCC, CLIENT_PAN, CLIENT_NAME, SEGMENT_INDICATOR,UNCLAIMED_CLIENT_FUNDS
ORDER BY CONVERT(VARCHAR(10), REPORT_DATE, 105), UCC
*/


INSERT INTO #FINAL_DATA
SELECT @FILENAMEHS, CONVERT(VARCHAR(10), CONVERT(DATETIME, @FROMDATE, 109), 105), UCC = '00000', 'TRADING MEMBER PAN,DATE,UNIQUE CLIENT CODE,CLIENT PAN,CLIENT NAME,MTF/ NON MTF INDICATOR,FINANCIAL LEDGER BALANCE-A,FINANCIAL LEDGER BALANCE (CLEAR)-B,Peak Financial Ledger Balance (clear)-C,FINANCIAL LEDGER BALANCE-MCX,FINANCIAL LEDGER BALANCE-NCDEX,FINANCIAL LEDGER BALANCE-ICEX,BANK GUARANTEE (BG),FIXED DEPOSIT RECEIPT (FDR),GOVERNMENT OF INDIA SECURITIES (GSEC),GILT FUNDS,Credit entry in ledger in lieu of EPI,Pool Account,Uncleared Cheques,Value of Commodities,Cash Collateral for MTF Positions,Unclaimed/Unsettled Client Funds,Client Bank Account No.,LAST SETTLEMENT DATE,ES INFORMATION TYPE,Value'
--UNION ALL
INSERT INTO #FINAL_DATA
SELECT @FILENAMEHS, CONVERT(VARCHAR(10), REPORT_DATE, 105), UCC, TRADING_PAN + ',' + CONVERT(VARCHAR(10), REPORT_DATE, 105) + ',' + UCC + ',' + CLIENT_PAN + ',' + replace(CLIENT_NAME,',','') + ',' + SEGMENT_INDICATOR
+ ','
+ CONVERT(VARCHAR, SUM(VDT_BAL)) + ',' + CONVERT(VARCHAR, SUM(EDT_BAL)) + ',' + CONVERT(VARCHAR, SUM(PEAK_FINANCIAL_LEDGER)) + ','
+ CONVERT(VARCHAR, SUM(CASE WHEN EXCHANGE = 'MCX' THEN VDT_BAL ELSE 0 END)) + ','
+ CONVERT(VARCHAR, SUM(CASE WHEN EXCHANGE = 'NCX' THEN VDT_BAL ELSE 0 END)) + ','
+ CONVERT(VARCHAR, SUM(CASE WHEN EXCHANGE = 'ICX' THEN VDT_BAL ELSE 0 END)) + ','
+ CONVERT(VARCHAR, SUM(BG)) + ',' + CONVERT(VARCHAR, SUM(FDR)) + ',' + CONVERT(VARCHAR, SUM(GOV_IND_SEC)) + ',' + CONVERT(VARCHAR, SUM(GILT_FUNDS)) + ','
+ CONVERT(VARCHAR, SUM(EPI_LEDGER)) + ',' + CONVERT(VARCHAR, SUM(POOL_ACCOUNT)) + ',' + CONVERT(VARCHAR, SUM(CHQ_DEPOSITS))
+ ',' + CONVERT(VARCHAR, SUM(COMM_VALUE)) + ',' 
+ CONVERT(VARCHAR, MAX(CASH_COLL_MTF_POSITIONS)) + ',' + UNCLAIMED_CLIENT_FUNDS + ',' + CASE WHEN UNCLAIMED_CLIENT_FUNDS = 'YES' THEN @@CLIENT_BANK_ACC ELSE 'NA' END + ',' + CASE WHEN UNCLAIMED_CLIENT_FUNDS = 'YES' THEN 'NA' ELSE CONVERT(VARCHAR, MAX(LAST_SETT_DATE)) END 
+ ',NA, NA'
FROM #REPORT_DATA
GROUP BY TRADING_PAN, CONVERT(VARCHAR(10), REPORT_DATE, 105), UCC, CLIENT_PAN, CLIENT_NAME, SEGMENT_INDICATOR,UNCLAIMED_CLIENT_FUNDS
ORDER BY CONVERT(VARCHAR(10), REPORT_DATE, 105), UCC
/* END CHANGE IN QUERY FOR NEW REPORT */

----INSERT INTO #FINAL_DATA
----SELECT @FILENAMEHS, CONVERT(VARCHAR(10), REPORT_DATE, 103), UCC = 'ZZZZ',  TRADING_PAN + ',' + CONVERT(VARCHAR(10), REPORT_DATE, 103) + ',NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,TOTAL CREDIT BALANCE OF ALL CLIENTS,' + CONVERT(VARCHAR, SUM(CASE WHEN VDT_BAL > 0 THEN VDT_BAL ELSE 0 END)) FROM #REPORT_DATA GROUP BY TRADING_PAN,  CONVERT(VARCHAR(10), REPORT_DATE, 103) ORDER BY CONVERT(VARCHAR(10), REPORT_DATE, 103)

----INSERT INTO #FINAL_DATA
----SELECT @FILENAMEHS, CONVERT(VARCHAR(10), REPORT_DATE, 103), UCC = 'ZZZZ',  TRADING_PAN + ',' + CONVERT(VARCHAR(10), REPORT_DATE, 103) + ',NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,TOTAL DEBIT BALANCE OF ALL CLIENTS ,' + CONVERT(VARCHAR, ABS(SUM(CASE WHEN VDT_BAL < 0 THEN VDT_BAL ELSE 0 END))) FROM #REPORT_DATA  GROUP BY TRADING_PAN,  CONVERT(VARCHAR(10), REPORT_DATE, 103) ORDER BY CONVERT(VARCHAR(10), REPORT_DATE, 103)
INSERT INTO #FINAL_dATA
SELECT @FILENAMEHS, CONVERT(VARCHAR(10), REPORT_DATE, 105), UCC = 'ZZZZ',  TRADING_PAN + ',' + CONVERT(VARCHAR(10), REPORT_DATE, 105) + ',NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,TOTAL CR BALANCE,' + CONVERT(VARCHAR, SUM(CASE WHEN EDT_BAL > 0 THEN EDT_BAL ELSE 0 END)) FROM 
(select TRADING_PAN, REPORT_DATE, UCC, CLIENT_PAN, CLIENT_NAME, SEGMENT_INDICATOR, EDT_BAL = sum(EDT_BAL) from #REPORT_DATA group by TRADING_PAN, REPORT_DATE, UCC, CLIENT_PAN, CLIENT_NAME, SEGMENT_INDICATOR) a 
group by TRADING_PAN, CONVERT(VARCHAR(10), REPORT_DATE, 105)
ORDER BY CONVERT(VARCHAR(10), REPORT_DATE, 105)

INSERT INTO #FINAL_dATA
SELECT @FILENAMEHS, CONVERT(VARCHAR(10), REPORT_DATE, 105), UCC = 'ZZZZ',  TRADING_PAN + ',' + CONVERT(VARCHAR(10), REPORT_DATE, 105) + ',NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,TOTAL DR BALANCE,' + CONVERT(VARCHAR, SUM(CASE WHEN EDT_BAL < 0 THEN EDT_BAL ELSE 0 END)) FROM 
(select TRADING_PAN, REPORT_DATE, UCC, CLIENT_PAN, CLIENT_NAME, SEGMENT_INDICATOR, EDT_BAL = sum(EDT_BAL) from #REPORT_DATA group by TRADING_PAN, REPORT_DATE, UCC, CLIENT_PAN, CLIENT_NAME, SEGMENT_INDICATOR) a 
group by TRADING_PAN, CONVERT(VARCHAR(10), REPORT_DATE, 105)
ORDER BY CONVERT(VARCHAR(10), REPORT_DATE, 105)

--INSERT INTO #FINAL_DATA
--SELECT @FILENAMEHS, CONVERT(VARCHAR(10), REPORT_DATE, 105), UCC = 'ZZZZ',  TRADING_PAN + ',' + CONVERT(VARCHAR(10), REPORT_DATE, 105) + ',NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NON FUNDED BG,0' FROM #REPORT_DATA  GROUP BY TRADING_PAN,  CONVERT(VARCHAR(10), REPORT_DATE, 105) ORDER BY CONVERT(VARCHAR(10), REPORT_DATE, 105)
INSERT INTO #FINAL_dATA
SELECT @FILENAMEHS, CONVERT(VARCHAR(10), CAL_DATES, 105), UCC = 'ZZZZ',  @TRADING_PAN + ',' + CONVERT(VARCHAR(10), CAL_DATES, 105) + ',NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NON FUNDED BG,' + CONVERT(VARCHAR, SUM(ISNULL(BANK_FUND_AMT, 0)) / 2) FROM  #CAL_DATES C LEFT OUTER JOIN ACCOUNT.DBO.TBL_BGDATA BG  ON CAL_DATES BETWEEN FROMDATE AND TODATE
GROUP BY convert(varchar(11), CAL_DATES, 105), CAL_DATES
order by convert(varchar(11), CAL_DATES, 105)

INSERT INTO #FINAL_DATA
SELECT @FILENAMEHS, CONVERT(VARCHAR(10), REPORT_DATE, 105), UCC = 'ZZZZ',  @TRADING_PAN + ',' + CONVERT(VARCHAR(10), REPORT_DATE, 105) + ',NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,TOTAL CR MARGIN,' + CONVERT(VARCHAR, SUM(TOTAL_MARGIN)) FROM #NET_MARGIN_BALANCE GROUP BY  CONVERT(VARCHAR(10), REPORT_DATE, 105) ORDER BY CONVERT(VARCHAR(10), REPORT_DATE, 105)

INSERT INTO #FINAL_DATA
SELECT @FILENAMEHS, CONVERT(VARCHAR(10), REPORT_DATE, 105), UCC = 'ZZZZ',  TRADING_PAN + ',' + CONVERT(VARCHAR(10), REPORT_DATE, 105) + ',NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,FREE COLL AT CM,0' FROM #REPORT_DATA  GROUP BY TRADING_PAN,  CONVERT(VARCHAR(10), REPORT_DATE, 105) ORDER BY CONVERT(VARCHAR(10), REPORT_DATE, 105)

--/*Temporary*/
--IF OBJECT_ID('dbo.tbl_FINAL_dATA_NULL', 'U') IS NOT NULL 
--  DROP TABLE dbo.tbl_FINAL_dATA_NULL; 
--Select @FILENAMEHS [FILENAME],REPORT_DATA  INTO dbo.tbl_FINAL_dATA_NULL  FROM #FINAL_dATA (Nolock)
--where charindex('null',REPORT_DATA) >0
--ORDER BY REPORTDATE, SNO 

--DELETE A 
--FROM #FINAL_dATA A  
--where charindex('null',REPORT_DATA) >0
--/*End*/
 
IF OBJECT_ID('dbo.tbl_CCE_FINAL_Data_LOG', 'U') IS NOT NULL 
  DROP TABLE dbo.tbl_CCE_FINAL_Data_LOG; 
SELECT @FILENAMEHS [FILENAME],REPORT_DATA  
      INTO dbo.tbl_CCE_FINAL_Data_LOG  FROM #FINAL_dATA (Nolock)
ORDER BY REPORTDATE, SNO

SELECT @FILENAMEHS [FILENAME],REPORT_DATA  
       FROM #FINAL_dATA (Nolock)
ORDER BY REPORTDATE, SNO

--EXEC xp_cmdshell 'bcp "SELECT * FROM dbo.tbl_CCE_FINAL_Data_LOG" queryout "J:\Backoffice\Ahsan\CCE.txt" -T -c -t,' 

--M351330
--VJIV1013
--select top 100* from dbo.tbl_CCE_FINAL_Data_LOG 
--SELECT 'AAACM6094R_CE_21092022_04.CSV' [FILENAME],REPORT_DATA  
--      INTO dbo.tbl_CCE_FINAL_Data_LOG  FROM #FINAL_dATA (Nolock)
--ORDER BY REPORTDATE, SNO

--SELECT * FROM tbl_CCE_FINAL_dATA_LOG
--ORDER BY  SNO
 --select top 100 * from dbo.tbl_CCE_FINAL_Data_LOG



-- select * from #CLIENT_CASH_DETAILS_tmp C 
--INNER JOIN ACCOUNT..CLIENT_CASH_LED_BALANCES L WITH(NOLOCK) ON C.SNO = L.SNO

GO
