-- Object: PROCEDURE dbo.RPT_CLIENT_COLL_SEG_MCX
-- Server: 10.253.33.91 | DB: MSAJAG
--------------------------------------------------


CREATE PROC [dbo].[RPT_CLIENT_COLL_SEG_MCX]
(
	@RUNDATE	VARCHAR(11),
	@EXCHANGE	VARCHAR(3)='MCX'
)
AS
-- EXEC RPT_CLIENT_COLL_SEG_MCX 'SEP 20 2021'

SELECT FILENAME=CLEARING_PAN+'_'+REPLACE(CONVERT(VARCHAR,PROCESS_DT,103),'/','')+'_01.csv',
Date=REPLACE(CONVERT(VARCHAR,PROCESS_DT,103),'/','-'),
CLEARING_PAN,TRADING_PAN,CP_CODE,CP_PAN, CLIENT_PAN,ACCOUNT_TYPE,SEGMENT_INDICATOR,MTOM=UPPER(PARTY_CODE),VDT_LEDGER,
EDT_LEDGER,
PEAK_LEDGER,
BG_REC_TM,FD_REC_TM,APPROVED_SEC_CASH_REC_TM,APPROVED_SEC_NONCASH_REC_TM,
NONAPPROVED_SEC_REC_TM,CC_APPROVED_COMM_REC_TM,OTHER_COLL_REC_TM,LIEU_EPI_LEDGER_CLTM,
POOL_ACCOUNT_CLTM,CASH_RET_TM,BG_RET_TM,FD_RET_TM,APPROVED_SEC_CASH_RET_TM,
APPROVED_SEC_NONCASH_RET_TM,NONAPPROVED_SEC_RET_TM,CC_APPROVED_COMM_RET_TM,OTHER_COLL_RET_TM,
CASH_WCM,BG_WCM,FD_WCM,APPROVED_SEC_CASH_WCM,APPROVED_SEC_NONCASH_WCM,NONAPPROVED_SEC_RET_WCM,
CC_APPROVED_COMM_WCM,OTHER_COLL_WCM,CASH_RET_WCM,BG_RET_CM,FD_RET_CM,APPROVED_SEC_CASH_RET_CM,
APPROVED_SEC_NONCASH_RET_CM,NONAPPROVED_SEC_RET_RET_CM,CC_APPROVED_COMM_RET_CM,OTHER_COLL_RET_CM,
CASH_WNCL,BG_WNCL,FD_WNCL,APPROVED_SEC_CASH_WNCL,APPROVED_SEC_NONCASH_WNCL,CC_APPROVED_COMM_WNCL
--EXCHANGE,SEGMENT,UPFRONT_MARGIN,PEAK_MARGIN,PARTY_CODE
FROM CLIENT_COLLATERAL_REPORTING_DETAILS
WHERE PROCESS_DT=@RUNDATE
AND Exchange='MCX'
ORDER BY EXCHANGE, CLEARING_PAN, TRADING_PAN, CLIENT_PAN, SEGMENT_INDICATOR

GO
