-- Object: PROCEDURE dbo.CLS_GET_DATA_DP_ROUTE
-- Server: 10.253.33.91 | DB: MSAJAG
--------------------------------------------------



CREATE PROCEDURE [dbo].[CLS_GET_DATA_DP_ROUTE](
	@PROTOKEN VARCHAR(50),
	@MAPPEDUSERNAME VARCHAR(100)

	)
AS
BEGIN
	--  select * from CLASSAPP.DBO.PASSPORT_LOGIN_MAP
	SELECT  FLDUSERNAME + '$' + FLDPASSWORD AS Data FROM MSAJAG..TBLPRADNYAUSERS A
 inner join  CLASSAPP..PASSPORT_LOGIN_MAP B on b.CLASS_LOGIN = a.Fldusername
 WHERE  MAPPED_LOGIN = @MAPPEDUSERNAME AND VERIFICATION_KEY = @PROTOKEN AND APP_CODE = 'CD'


END

GO
