-- Object: PROCEDURE dbo.CMR_MOVE_HIST
-- Server: 10.253.33.91 | DB: MSAJAG
--------------------------------------------------

CREATE PROC [dbo].[CMR_MOVE_HIST]

AS
BEGIN
DECLARE @CMR_DATE DATE
SELECT TOP 1 @CMR_DATE =  MARGINDATE FROM
(
SELECT  DISTINCT TOP 10 MARGINDATE FROM TBL_COMBINE_REPORTING WITH (NOLOCK)ORDER BY MARGINDATE DESC
 )A ORDER BY MARGINDATE
 --PRINT @DATE

INSERT INTO TBL_COMBINE_REPORTING_HIST
SELECT * FROM TBL_COMBINE_REPORTING
WHERE MARGINDATE < @CMR_DATE

DELETE FROM TBL_COMBINE_REPORTING
WHERE  MARGINDATE < @CMR_DATE
-----------
INSERT INTO TBL_COMBINE_REPORTING_DETAIL_HIST
SELECT * FROM TBL_COMBINE_REPORTING_DETAIL
WHERE MARGINDATE < @CMR_DATE

DELETE FROM TBL_COMBINE_REPORTING_DETAIL
WHERE  MARGINDATE < @CMR_DATE

 END

GO
