-- Object: PROCEDURE dbo.REBUILD_TRADE_PROCESS
-- Server: 10.253.33.91 | DB: MSAJAG
--------------------------------------------------

CREATE PROC [dbo].[REBUILD_TRADE_PROCESS]

AS 



--ALTER INDEX [IDXSETT] ON [dbo].[VBB_Charges_detail_Temp_2] REBUILD PARTITION = ALL WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)



ALTER INDEX [IX_PARTY] ON [dbo].[VBB_Charges_detail_Temp_2] REBUILD PARTITION = ALL WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)



ALTER INDEX [partyidx] ON [dbo].[VBB_Settlement] REBUILD PARTITION = ALL WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)



ALTER INDEX [NonClusteredIndex-20170417-180640] ON [dbo].[VBB_Settlement] REBUILD PARTITION = ALL WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)



ALTER INDEX [IDXPARTY] ON [dbo].[VBB_Charges_detail_Temp_1] REBUILD PARTITION = ALL WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)



ALTER INDEX [IDXPARTY] ON [dbo].[VBB_Charges_detail_Temp] REBUILD PARTITION = ALL WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)





ALTER INDEX [ix_parentcode] ON [dbo].[TRD_CLIENT] REBUILD PARTITION = ALL WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)



ALTER INDEX [IX_PARTY] ON [dbo].[TRD_CLIENT] REBUILD PARTITION = ALL WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)

ALTER INDEX [cl_code] ON [dbo].[Trd_Client2] REBUILD PARTITION = ALL WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90)

ALTER INDEX [Clcode] ON [dbo].[Trd_Client2] REBUILD PARTITION = ALL WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90)

ALTER INDEX [Clcode] ON [dbo].[Trd_Client1] REBUILD PARTITION = ALL WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90)



ALTER INDEX [Party] ON [dbo].[trade] REBUILD PARTITION = ALL WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)





ALTER INDEX [Trdind] ON [dbo].[trade] REBUILD PARTITION = ALL WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 80)



ALTER INDEX [IX_DATE] ON [dbo].[globals] REBUILD PARTITION = ALL WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)



ALTER INDEX [Set_Mst] ON [dbo].[Trd_Sett_Mst] REBUILD PARTITION = ALL WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 80)



ALTER INDEX [Set_Mst1] ON [dbo].[Trd_Sett_Mst] REBUILD PARTITION = ALL WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)



ALTER INDEX [Settparty] ON [dbo].[Trd_Contractno] REBUILD PARTITION = ALL WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90)



ALTER INDEX [Tableno] ON [dbo].[Trd_Broktable] REBUILD PARTITION = ALL WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90)

--sp_current_process 136

--ALTER INDEX [parentidx] ON [dbo].[BBGSettlement] REBUILD PARTITION = ALL WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)



--ALTER INDEX [Partysett] ON [dbo].[BBGSettlement] REBUILD PARTITION = ALL WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)



ALTER INDEX [ix_brk] ON [dbo].[Trd_Clientbrok_Scheme] REBUILD PARTITION = ALL WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)



ALTER INDEX [Brkscheme] ON [dbo].[Trd_Clientbrok_Scheme] REBUILD PARTITION = ALL WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 80)



ALTER INDEX [cont_indx] ON [dbo].[TRD_CONTRACT_ROUNDING] REBUILD PARTITION = ALL WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90)



ALTER INDEX [ix_cr] ON [dbo].[TRD_CONTRACT_ROUNDING] REBUILD PARTITION = ALL WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)



ALTER INDEX [Cltax] ON [dbo].[Trd_Clienttaxes_New] REBUILD PARTITION = ALL WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 80)



ALTER INDEX [Cltax1] ON [dbo].[Trd_Clienttaxes_New] REBUILD PARTITION = ALL WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)




ALTER INDEX [idxParty] ON [dbo].[TRD_SCHEME_MAPPING] REBUILD PARTITION = ALL WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90)



ALTER INDEX [idxS] ON [dbo].[TRD_SCHEME_MAPPING] REBUILD PARTITION = ALL WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90)






/*
ALTER INDEX [SCRIDX] ON [dbo].[COMBINE_SETTLEMENT] REBUILD PARTITION = ALL WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)





ALTER INDEX [Stt_Index] ON [dbo].[COMBINE_SETTLEMENT] REBUILD PARTITION = ALL WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)





ALTER INDEX [SRNO] ON [dbo].[COMBINE_SETTLEMENT] REBUILD PARTITION = ALL WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)



ALTER INDEX [sett_type] ON [dbo].[COMBINE_SETTLEMENT] REBUILD PARTITION = ALL WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)



ALTER INDEX [Partycode] ON [dbo].[COMBINE_SETTLEMENT] REBUILD PARTITION = ALL WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)









---------------TRD_CLIENT          ---->   PK_TRD_CLIENT, party_code

ALTER INDEX  PK_TRD_CLIENT  ON MSAJAG.dbo.TRD_CLIENT



--ALTER INDEX  party_code  ON MSAJAG.dbo.TRD_CLIENT

--REBUILD;

--GO

---------------------TRADE ---->IX_IND, IX_PARTY, Trdind

ALTER INDEX  Trdind  ON MSAJAG.dbo.TRADE



----------------------GLOBALS ------> gdate

----ALTER INDEX  gdate  ON MSAJAG.dbo.GLOBALS

----REBUILD;



-----------------------TRD_SETT_MST----->Set_Mst, Set_Mst1

ALTER INDEX  Set_Mst  ON MSAJAG.dbo.TRD_SETT_MST

REBUILD;

GO

ALTER INDEX  Set_Mst1  ON MSAJAG.dbo.TRD_SETT_MST

REBUILD;

GO

-----------------------TRD_CONTRACTNO ----> Settparty

ALTER INDEX  Settparty  ON MSAJAG.dbo.TRD_CONTRACTNO

REBUILD;

GO

------------------------TRD_BROKTABLE ---> Tableno

ALTER INDEX  Tableno  ON MSAJAG.dbo.TRD_BROKTABLE

REBUILD;

GO

------------------------BBGSETTLEMENT  ---->IDXPARTY, ix_missing_BBGSettlement, party_ix, Partysett, PROIDX

--ALTER INDEX  IDXPARTY  ON MSAJAG.dbo.BBGSETTLEMENT

--REBUILD;

--GO

--ALTER INDEX  ix_missing_BBGSettlement  ON MSAJAG.dbo.BBGSETTLEMENT

--REBUILD;

--GO

--ALTER INDEX  party_ix  ON MSAJAG.dbo.BBGSETTLEMENT

--REBUILD;

--GO

ALTER INDEX  Partysett  ON MSAJAG.dbo.BBGSETTLEMENT

REBUILD;

GO

ALTER INDEX  parentidx  ON MSAJAG.dbo.BBGSETTLEMENT

REBUILD;

--GO

--ALTER INDEX [IDXPARTY] ON MSAJAG.[dbo].[VBB_Charges_detail_Temp] REBUILD PARTITION = ALL WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)

--GO

--ALTER INDEX [IDXPARTY] ON MSAJAG.[dbo].[VBB_Charges_detail_Temp_1] REBUILD PARTITION = ALL WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)

--GO

--ALTER INDEX [IDXPARTY] ON MSAJAG.[dbo].[VBB_Charges_detail_Temp_2] REBUILD PARTITION = ALL WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)

--GO





-------------------------TRD_CLIENTBROK_SCHEME ----> Brkscheme, ix_brk

ALTER INDEX  Brkscheme  ON MSAJAG.dbo.TRD_CLIENTBROK_SCHEME

REBUILD;

GO

ALTER INDEX  ix_brk  ON MSAJAG.dbo.TRD_CLIENTBROK_SCHEME

REBUILD;

GO

-----------------------TRD_CONTRACT_ROUNDING ----> cont_indx,ix_cr

ALTER INDEX  cont_indx  ON MSAJAG.dbo.TRD_CONTRACT_ROUNDING

REBUILD;

GO

ALTER INDEX  ix_cr  ON MSAJAG.dbo.TRD_CONTRACT_ROUNDING

REBUILD;

GO

-----------------------TRD_CLIENTTAXES_NEW ---> Cltax, Cltax1

ALTER INDEX  Cltax  ON MSAJAG.dbo.TRD_CLIENTTAXES_NEW

REBUILD;

GO

ALTER INDEX  Cltax1  ON MSAJAG.dbo.TRD_CLIENTTAXES_NEW

REBUILD;

GO

-----------------------TRD_SCHEME_MAPPING---->idxParty, idxS8I

ALTER INDEX  idxParty  ON MSAJAG.dbo.TRD_SCHEME_MAPPING

REBUILD;

GO

ALTER INDEX  idxS  ON MSAJAG.dbo.TRD_SCHEME_MAPPING

REBUILD;

GO





ALTER INDEX  [NonClusteredIndex-20170417-180640]  ON MSAJAG.dbo.VBB_Settlement

REBUILD;

GO



ALTER INDEX  partyidx  ON MSAJAG.dbo.VBB_Settlement

REBUILD;

GO



-------------------------COMBINE_SETTLEMENT---->idxParty, idxS8I

--ALTER INDEX  Partycode  ON MSAJAG.dbo.COMBINE_SETTLEMENT

--REBUILD;

--GO

--ALTER INDEX  SCRIDX  ON MSAJAG.dbo.COMBINE_SETTLEMENT

--REBUILD;

--GO

--ALTER INDEX  sett_type  ON MSAJAG.dbo.COMBINE_SETTLEMENT

--REBUILD;

--GO

--ALTER INDEX  SRNO  ON MSAJAG.dbo.COMBINE_SETTLEMENT

--REBUILD;

--GO

--ALTER INDEX  Stt_Index  ON MSAJAG.dbo.COMBINE_SETTLEMENT

--REBUILD;

--GO

*/

GO
