-- Object: PROCEDURE dbo.CLS_ADMIN_GETMENUHEAD
-- Server: 10.253.33.91 | DB: MSAJAG
--------------------------------------------------


CREATE PROC CLS_ADMIN_GETMENUHEAD
AS
SELECT FLDHEADCODE=FLDMENUCODE, FLDMENUNAME=FLDMENUNAME FROM TBLMENUHEAD

GO
