-- Object: PROCEDURE dbo.PROC_COMBINE_MARGIN_REPORTING_PEAK_chk
-- Server: 10.253.33.91 | DB: MSAJAG
--------------------------------------------------


CREATE PROCEDURE [dbo].[PROC_COMBINE_MARGIN_REPORTING_PEAK_chk]   
( 
	@MARGINDATE VARCHAR(11),  
	@COMBINEFLAG INT = 1,  
	@FORREPORTING VARCHAR(1)='Y',  
	@CHECKFLAG INT = 0  
)      
  
AS      
  
-- EXEC PROC_COMBINE_MARGIN_REPORTING_PEAK_CHK 'APR 27 2021', 1, 'Y', 0  
  
  
--DUE TO COMBINE_REPORTING LIVE   
--SET @COMBINEFLAG = 0  
  
  
  
SET NOCOUNT ON   

DECLARE @PREVDATE VARCHAR(11)

DECLARE @EXCHANGE_NEW VARCHAR(3)  
  
DECLARE @SEGMENT_NEW VARCHAR(10)  
  
DECLARE @SHAREDB VARCHAR(35)  
  
DECLARE @SHARESERVER VARCHAR(35)  
  
DECLARE @ACCOUNTDB VARCHAR(35)  
  
DECLARE @ACCOUNTSERVER VARCHAR(35)  
  
  
  
DECLARE @EXCHANGEWISE_CURSOR CURSOR   
  
DECLARE @STRSQL VARCHAR(8000)   
  
DECLARE @MARGINDATENEW VARCHAR(11)  
  
DECLARE @MARGINDATECURSOR CURSOR  
  
DECLARE @MRGCUR CURSOR  
  
  
  
DECLARE @CNT INT  
  
DECLARE @DAY INT  
  
DECLARE @PARTY_CODE VARCHAR(10)  
  
DECLARE @SHRT_AMT NUMERIC(18,4)  
  
DECLARE @MARG_AMT NUMERIC(18,4)  
  
  
  
DECLARE @EXCHANGE_PRIORITY INT  
  

DECLARE 
@VARKEY 	VARCHAR(8) 

   
SELECT * INTO #V2_TBL_EXCHANGE_MARGIN_REPORT_PEAK FROM V2_TBL_EXCHANGE_MARGIN_REPORT_PEAK
WHERE @MARGINDATE BETWEEN FROM_DATE AND TO_DATE
  

DELETE FROM TBL_COMBINE_REPORTING_PEAK_TDAY_DETAIL
WHERE MARGINDATE = @MARGINDATE   
  
DELETE FROM TBL_COMBINE_REPORTING_PEAK_TDAY
WHERE MARGINDATE = @MARGINDATE  
   
INSERT INTO TBL_COMBINE_REPORTING_PEAK_TDAY
SELECT * FROM  TBL_COMBINE_REPORTING_PEAK 
WHERE MARGINDATE = @MARGINDATE  
and party_code = 'A136401'
  
INSERT INTO TBL_COMBINE_REPORTING_PEAK_TDAY_DETAIL    
SELECT * FROM  TBL_COMBINE_REPORTING_PEAK_DETAIL
WHERE MARGINDATE = @MARGINDATE  
and party_code = 'A136401'

	SELECT @PREVDATE = MAX(TRANSDATE) FROM TBL_EPN_BENEFIT
	WHERE TRANSDATE < @MARGINDATE  
	 /*
	SELECT @PREVDATE = MAX(TRANSDATE) FROM TBL_EPN_BENEFIT
	WHERE TRANSDATE < @MARGINDATE */

	SELECT PARTY_CODE, CASHBENEFIT=SUM(CASHBENEFIT)*20/100-(SUM(CASHBENEFIT)*20/100)*PEAK_PER/100 
	INTO #EPNREV FROM (
	SELECT PARTY_CODE, CASHBENEFIT=-SUM(CASHBENEFIT) FROM TBL_EPN_BENEFIT T
	WHERE TRANSDATE = @PREVDATE 
	AND SETT_NO IN (SELECT SETT_NO FROM TBL_EPN_BENEFIT T1
	WHERE TRANSDATE = @MARGINDATE AND T.SETT_NO = T1.SETT_NO AND T.SETT_TYPE = T1.SETT_TYPE)
	GROUP BY PARTY_CODE 
	UNION ALL
	SELECT PARTY_CODE, CASHBENEFIT=SUM(CASHBENEFIT) FROM TBL_EPN_BENEFIT T
	WHERE TRANSDATE = @MARGINDATE
	GROUP BY PARTY_CODE ) A, #V2_TBL_EXCHANGE_MARGIN_REPORT_PEAK p
	WHERE P.EXCHANGE = 'NSE' AND P.SEGMENT = 'CAPITAL' and party_code = 'A136401'
	GROUP BY PARTY_CODE, PEAK_PER
	HAVING SUM(CASHBENEFIT) > 0 
	
	
UPDATE TBL_COMBINE_REPORTING_PEAK_TDAY SET TDAY_CASH = TDAY_CASH - CASHBENEFIT, TDAY_MARGIN = TDAY_MARGIN - CASHBENEFIT
FROM #EPNREV 
WHERE MARGINDATE = @MARGINDATE AND TBL_COMBINE_REPORTING_PEAK_TDAY.PARTY_CODE = #EPNREV.PARTY_CODE 
AND TDAY_MARGIN > 0 
 
UPDATE TBL_COMBINE_REPORTING_PEAK_TDAY_DETAIL SET TDAY_MARGIN = TDAY_MARGIN - CASHBENEFIT
FROM #EPNREV 
WHERE MARGINDATE = @MARGINDATE AND TBL_COMBINE_REPORTING_PEAK_TDAY_DETAIL.PARTY_CODE = #EPNREV.PARTY_CODE 
AND EXCHANGE='NSE' AND SEGMENT = 'CAPITAL'
AND TDAY_MARGIN > 0 

UPDATE TBL_COMBINE_REPORTING_PEAK_TDAY   
SET   
TDAY_MARGIN_SHORT = TDAY_CASH + TDAY_NONCASH    
WHERE MARGINDATE = @MARGINDATE   

  
UPDATE TBL_COMBINE_REPORTING_PEAK_TDAY SET TDAY_MARGIN_SHORT = TDAY_MARGIN_SHORT - TDAY_MARGIN  
WHERE MARGINDATE  = @MARGINDATE AND TDAY_MARGIN > 0   
/*  
SELECT * FROM TBL_COMBINE_REPORTING_PEAK_TDAY  
WHERE MARGINDATE = 'JAN  7 2020'  
AND PARTY_CODE = 'A151487'  
*/  
  
UPDATE TBL_COMBINE_REPORTING_PEAK_TDAY SET   
TDAY_MARGIN_SHORT = TDAY_MARGIN_SHORT - PRADNYA.DBO.FNMIN(TDAY_MARGIN_SHORT,ABS(PRADNYA.DBO.FNMIN((TDAY_MTM_SHORT-TDAY_MTM),0))),  
TDAY_MTM_SHORT = TDAY_MTM_SHORT + PRADNYA.DBO.FNMIN(TDAY_MARGIN_SHORT,ABS(PRADNYA.DBO.FNMIN((TDAY_MTM_SHORT-TDAY_MTM),0)))  
WHERE MARGINDATE  = @MARGINDATE AND TDAY_MTM_SHORT-TDAY_MTM < 0  
AND TDAY_MTM > 0 AND TDAY_MTM_SHORT > 0 AND TDAY_MARGIN_SHORT > 0   
/*  
SELECT * FROM TBL_COMBINE_REPORTING_PEAK_TDAY  
WHERE MARGINDATE = 'JAN  7 2020'  
AND PARTY_CODE = 'A151487'  
*/  

UPDATE TBL_COMBINE_REPORTING_PEAK_TDAY SET   
TDAY_MARGIN_SHORT = TDAY_MARGIN_SHORT - PRADNYA.DBO.FNMIN(TDAY_MARGIN_SHORT,ABS(PRADNYA.DBO.FNMIN((TDAY_MTM_SHORT-TDAY_MTM),0))),  
TDAY_MTM_SHORT = TDAY_MTM_SHORT + PRADNYA.DBO.FNMIN(TDAY_MARGIN_SHORT,ABS(PRADNYA.DBO.FNMIN((TDAY_MTM_SHORT-TDAY_MTM),0)))  
WHERE MARGINDATE  = @MARGINDATE AND TDAY_MTM_SHORT-TDAY_MTM < 0  
AND TDAY_MTM > 0 AND TDAY_MARGIN_SHORT > 0   
  
UPDATE TBL_COMBINE_REPORTING_PEAK_TDAY SET TDAY_MTM_SHORT = TDAY_MTM_SHORT - TDAY_MTM  
WHERE MARGINDATE  = @MARGINDATE   
AND TDAY_MTM > 0 AND TDAY_MTM_SHORT - TDAY_MTM < 0   

IF (SELECT ISNULL(SUM(TDAY_MARGIN+TDAY_MTM),0) FROM TBL_COMBINE_REPORTING_PEAK_TDAY 
				WHERE MARGINDATE = @MARGINDATE) >= 0 
BEGIN  
	UPDATE TBL_COMBINE_REPORTING_PEAK_TDAY SET TDAY_MARGIN_SHORT = 0,TDAY_MTM_SHORT=0
	WHERE MARGINDATE = @MARGINDATE AND TDAY_MARGIN_SHORT <> 0 
	AND PARTY_CODE IN (SELECT CL_CODE FROM CLIENT1 WHERE CL_TYPE = 'NRI')

	--UPDATE TBL_COMBINE_REPORTING_PEAK_TDAY SET TDAY_MARGIN_SHORT =0 ---PRADNYA.DBO.FNMIN(ABS(TDAY_MARGIN_SHORT),ABS(T2DAY_LEDGER))
	--,TDAY_MTM_SHORT=0
	--WHERE MARGINDATE = @MARGINDATE AND TDAY_MARGIN_SHORT < 0 
	--AND PARTY_CODE IN (SELECT CL_CODE FROM CLIENT1 WHERE CL_TYPE = 'NRI') 
END 

UPDATE TBL_COMBINE_REPORTING_PEAK_TDAY SET TDAY_MARGIN_SHORT =0
WHERE MARGINDATE = @MARGINDATE AND TDAY_MARGIN = 0 AND TDAY_MARGIN_SHORT < = 0

UPDATE TBL_COMBINE_REPORTING_PEAK_TDAY SET TDAY_MARGIN_SHORT = -TDAY_MARGIN
WHERE MARGINDATE = @MARGINDATE AND TDAY_MARGIN > 0 AND TDAY_MARGIN_SHORT < 0
AND TDAY_MARGIN < ABS(TDAY_MARGIN_SHORT)

 /* 
UPDATE TBL_COMBINE_REPORTING_PEAK_TDAY SET TDAY_MTM_SHORT = PRADNYA.DBO.FNMAX(TDAY_MTM_SHORT, -TDAY_MTM)  
WHERE MARGINDATE  = @MARGINDATE AND TDAY_MTM_SHORT < 0  
*/  
IF @COMBINEFLAG = 0   
  
BEGIN     
  
 UPDATE TBL_COMBINE_REPORTING_PEAK_TDAY_DETAIL   
  
 SET TDAY_MARGIN_SHORT = T1.TDAY_MARGIN_SHORT,  
  
  TDAY_MTM_SHORT = T1.TDAY_MTM_SHORT,  
  
  T1DAY_MARGIN_SHORT = T1.T1DAY_MARGIN_SHORT,  
  
  T1DAY_MTM_SHORT = T1.T1DAY_MTM_SHORT,  
  
  T2DAY_MARGIN_SHORT = T1.T2DAY_MARGIN_SHORT,  
  
  T2DAY_MTM_SHORT = T1.T2DAY_MTM_SHORT,  
  
  --T_MARGINAVL = (CASE WHEN T1.TDAY_MARGIN_SHORT >= 0 THEN T1.TDAY_MARGIN ELSE T1.TDAY_MARGIN_SHORT END),  
  
  --T_MTMAVL = (CASE WHEN T1.TDAY_MTM_SHORT >= 0 THEN T1.TDAY_MTM ELSE T1.TDAY_MTM_SHORT END)   
  
  T_MARGINAVL = (CASE WHEN T1.TDAY_MARGIN_SHORT >= 0 THEN T1.TDAY_MARGIN   
  
  ELSE (CASE WHEN T1.TDAY_MARGIN  > ABS(T1.TDAY_MARGIN_SHORT) THEN T1.TDAY_MARGIN_SHORT ELSE -T1.TDAY_MARGIN END) END),  
  
  T_MTMAVL = (CASE WHEN T1.TDAY_MTM_SHORT >= 0 THEN T1.TDAY_MTM   
  
  ELSE (CASE WHEN T1.TDAY_MTM  > ABS(T1.TDAY_MTM_SHORT) THEN T1.TDAY_MTM_SHORT ELSE -T1.TDAY_MTM END) END)   
  
 FROM TBL_COMBINE_REPORTING_PEAK_TDAY T1  
  
 WHERE TBL_COMBINE_REPORTING_PEAK_TDAY_DETAIL.MARGINDATE = @MARGINDATE   
  
 AND T1.MARGINDATE = @MARGINDATE  
  
 AND TBL_COMBINE_REPORTING_PEAK_TDAY_DETAIL.PARTY_CODE = T1.PARTY_CODE  
  
 AND TBL_COMBINE_REPORTING_PEAK_TDAY_DETAIL.EXCHANGE = T1.EXCHANGE  
  
 AND TBL_COMBINE_REPORTING_PEAK_TDAY_DETAIL.SEGMENT = T1.SEGMENT  
  
END  
  
ELSE  
  
BEGIN  
   
  
 UPDATE TBL_COMBINE_REPORTING_PEAK_TDAY_DETAIL  
  
 SET T_MARGINAVL = TDAY_MARGIN   
  
 WHERE MARGINDATE = @MARGINDATE   
  
 AND EXISTS (SELECT PARTY_CODE FROM TBL_COMBINE_REPORTING_PEAK_TDAY  
  
    WHERE MARGINDATE = @MARGINDATE   
  
    AND TBL_COMBINE_REPORTING_PEAK_TDAY_DETAIL.PARTY_CODE = TBL_COMBINE_REPORTING_PEAK_TDAY.PARTY_CODE  
  
    AND TDAY_MARGIN_SHORT >= 0)  
  
  
  
 UPDATE TBL_COMBINE_REPORTING_PEAK_TDAY_DETAIL  
  
 SET T_MTMAVL = TDAY_MTM  
  
 WHERE MARGINDATE = @MARGINDATE   
  
 AND EXISTS (SELECT PARTY_CODE FROM TBL_COMBINE_REPORTING_PEAK_TDAY  
  
    WHERE MARGINDATE = @MARGINDATE   
  
    AND TBL_COMBINE_REPORTING_PEAK_TDAY_DETAIL.PARTY_CODE = TBL_COMBINE_REPORTING_PEAK_TDAY.PARTY_CODE  
  
    AND TDAY_MTM_SHORT >= 0)  
  
 SELECT distinct PARTY_CODE INTO #PARTYCNT FROM TBL_COMBINE_REPORTING_PEAK_TDAY_DETAIL  
 WHERE MARGINDATE = @MARGINDATE and EXCHANGE <> 'POA'  
 AND TDAY_MARGIN + TDAY_MTM > 0   
 GROUP BY PARTY_CODE   
 HAVING COUNT(1) = 1  
    
  CREATE CLUSTERED INDEX PARTIDX ON #PARTYCNT  
  (  
  PARTY_CODE  
  )  
  
 UPDATE TBL_COMBINE_REPORTING_PEAK_TDAY_DETAIL  
 SET T_MARGINAVL = T1.TDAY_MARGIN_SHORT, T_MTMAVL = T1.TDAY_MTM_SHORT  
 FROM TBL_COMBINE_REPORTING_PEAK_TDAY T1  
 WHERE TBL_COMBINE_REPORTING_PEAK_TDAY_DETAIL.MARGINDATE = @MARGINDATE   
 AND T1.MARGINDATE = @MARGINDATE AND TBL_COMBINE_REPORTING_PEAK_TDAY_DETAIL.TDAY_MARGIN + TBL_COMBINE_REPORTING_PEAK_TDAY_DETAIL.TDAY_MTM > 0   
 AND TBL_COMBINE_REPORTING_PEAK_TDAY_DETAIL.PARTY_CODE = T1.PARTY_CODE  
 AND EXISTS (SELECT PARTY_CODE FROM #PARTYCNT  
    WHERE #PARTYCNT.PARTY_CODE = TBL_COMBINE_REPORTING_PEAK_TDAY_DETAIL.PARTY_CODE)  

 IF CONVERT(DATETIME,@MARGINDATE) > CONVERT(DATETIME,'SEP 15 2020')
 BEGIN
	UPDATE #V2_TBL_EXCHANGE_MARGIN_REPORT_PEAK SET EXCHANGE_PRIORITY = 0 WHERE SEGMENT = 'CAPITAL'
 end
       
 SET @MRGCUR = CURSOR FOR  
 SELECT PARTY_CODE, AVAL_MARGIN=TDAY_MARGIN_SHORT FROM TBL_COMBINE_REPORTING_PEAK_TDAY  
 WHERE MARGINDATE = @MARGINDATE  AND TDAY_MARGIN_SHORT < 0   
 AND NOT EXISTS (SELECT PARTY_CODE FROM #PARTYCNT  
    WHERE #PARTYCNT.PARTY_CODE = TBL_COMBINE_REPORTING_PEAK_TDAY.PARTY_CODE)  
   ORDER BY PARTY_CODE   
  
 OPEN @MRGCUR  
 FETCH NEXT FROM @MRGCUR INTO @PARTY_CODE, @SHRT_AMT  
 WHILE @@FETCH_STATUS = 0  
 BEGIN  
  SET @EXCHANGEWISE_CURSOR = CURSOR FOR  
  SELECT PARTY_CODE, T.EXCHANGE, T.SEGMENT, TDAY_MARGIN, EXCHANGE_PRIORITY   
  FROM TBL_COMBINE_REPORTING_PEAK_TDAY_DETAIL T, #V2_TBL_EXCHANGE_MARGIN_REPORT_PEAK T1  
  WHERE MARGINDATE = @MARGINDATE  
  AND PARTY_CODE = @PARTY_CODE  
  AND T.EXCHANGE = T1.EXCHANGE   
  AND T.SEGMENT = T1.SEGMENT   
  AND TDAY_MARGIN > 0  
  ORDER BY TDAY_MARGIN DESC, EXCHANGE_PRIORITY DESC  
  
  OPEN @EXCHANGEWISE_CURSOR  
  
  FETCH NEXT FROM @EXCHANGEWISE_CURSOR INTO @PARTY_CODE, @EXCHANGE_NEW, @SEGMENT_NEW, @MARG_AMT, @EXCHANGE_PRIORITY  
  WHILE @@FETCH_STATUS = 0  
  
  BEGIN  
  
   IF @SHRT_AMT < 0   
  
   BEGIN  
  
    IF @MARG_AMT >= ABS(@SHRT_AMT)  
  
    BEGIN  
  
     UPDATE TBL_COMBINE_REPORTING_PEAK_TDAY_DETAIL SET T_MARGINAVL = @SHRT_AMT  
     WHERE MARGINDATE = @MARGINDATE  
     AND PARTY_CODE = @PARTY_CODE  
     AND EXCHANGE = @EXCHANGE_NEW   
     AND SEGMENT = @SEGMENT_NEW   
     SET @SHRT_AMT = 0  
  
    END  
  
    ELSE  
  
    BEGIN  
  
     UPDATE TBL_COMBINE_REPORTING_PEAK_TDAY_DETAIL SET T_MARGINAVL = -@MARG_AMT  
  
     WHERE MARGINDATE = @MARGINDATE  
  
     AND PARTY_CODE = @PARTY_CODE  
  
     AND EXCHANGE = @EXCHANGE_NEW   
  
     AND SEGMENT = @SEGMENT_NEW   
  
     SET @SHRT_AMT = @SHRT_AMT + @MARG_AMT  
  
    END  
  
   END  
  
   ELSE  
  
   BEGIN  
  
    UPDATE TBL_COMBINE_REPORTING_PEAK_TDAY_DETAIL SET T_MARGINAVL = @MARG_AMT  
  
    WHERE MARGINDATE = @MARGINDATE  
  
    AND PARTY_CODE = @PARTY_CODE  
  
    AND EXCHANGE = @EXCHANGE_NEW   
  
    AND SEGMENT = @SEGMENT_NEW   
  
   END  
  
   FETCH NEXT FROM @EXCHANGEWISE_CURSOR INTO @PARTY_CODE, @EXCHANGE_NEW, @SEGMENT_NEW, @MARG_AMT, @EXCHANGE_PRIORITY  
  
  END  
  
  CLOSE @EXCHANGEWISE_CURSOR  
  
  DEALLOCATE @EXCHANGEWISE_CURSOR  
  
  FETCH NEXT FROM @MRGCUR INTO @PARTY_CODE, @SHRT_AMT  
  
 END  
  
 CLOSE @MRGCUR  
  
 DEALLOCATE @MRGCUR  
  
  
  
 SET @MRGCUR = CURSOR FOR  
  
 SELECT PARTY_CODE, AVAL_MARGIN=TDAY_MTM_SHORT FROM TBL_COMBINE_REPORTING_PEAK_TDAY  
  
 WHERE MARGINDATE = @MARGINDATE   
  
 AND NOT EXISTS (SELECT PARTY_CODE FROM #PARTYCNT  
  
    WHERE #PARTYCNT.PARTY_CODE = TBL_COMBINE_REPORTING_PEAK_TDAY.PARTY_CODE)  
  
 AND TDAY_MTM_SHORT < 0   
  
 ORDER BY PARTY_CODE   
  
 OPEN @MRGCUR  
  
 FETCH NEXT FROM @MRGCUR INTO @PARTY_CODE, @SHRT_AMT  
  
 WHILE @@FETCH_STATUS = 0  
  
 BEGIN  
  
  SET @EXCHANGEWISE_CURSOR = CURSOR FOR  
  
  SELECT PARTY_CODE, T.EXCHANGE, T.SEGMENT, TDAY_MTM, EXCHANGE_PRIORITY   
  
  FROM TBL_COMBINE_REPORTING_PEAK_TDAY_DETAIL T, #V2_TBL_EXCHANGE_MARGIN_REPORT_PEAK T1  
  
  WHERE MARGINDATE = @MARGINDATE  
  
  AND PARTY_CODE = @PARTY_CODE  
  
  AND T.EXCHANGE = T1.EXCHANGE   
  
  AND T.SEGMENT = T1.SEGMENT   
  
  AND TDAY_MTM > 0  
  
  ORDER BY EXCHANGE_PRIORITY DESC  
  
  OPEN @EXCHANGEWISE_CURSOR  
  
  FETCH NEXT FROM @EXCHANGEWISE_CURSOR INTO @PARTY_CODE, @EXCHANGE_NEW, @SEGMENT_NEW, @MARG_AMT, @EXCHANGE_PRIORITY  
  
  WHILE @@FETCH_STATUS = 0  
  
  BEGIN  
  
   IF @SHRT_AMT < 0   
  
   BEGIN  
  
    IF @MARG_AMT >= ABS(@SHRT_AMT)  
  
    BEGIN  
  
     UPDATE TBL_COMBINE_REPORTING_PEAK_TDAY_DETAIL SET T_MTMAVL = @SHRT_AMT  
     WHERE MARGINDATE = @MARGINDATE  
     AND PARTY_CODE = @PARTY_CODE  
     AND EXCHANGE = @EXCHANGE_NEW   
     AND SEGMENT = @SEGMENT_NEW   
  
     SET @SHRT_AMT = 0  
  
    END  
  
    ELSE  
  
    BEGIN  
  
     UPDATE TBL_COMBINE_REPORTING_PEAK_TDAY_DETAIL SET T_MTMAVL = -@MARG_AMT  
     WHERE MARGINDATE = @MARGINDATE  
     AND PARTY_CODE = @PARTY_CODE  
     AND EXCHANGE = @EXCHANGE_NEW   
     AND SEGMENT = @SEGMENT_NEW   
     SET @SHRT_AMT = @SHRT_AMT + @MARG_AMT  
  
    END  
  
   END  
  
   ELSE  
  
   BEGIN  
  
    UPDATE TBL_COMBINE_REPORTING_PEAK_TDAY_DETAIL SET T_MTMAVL = @MARG_AMT  
    WHERE MARGINDATE = @MARGINDATE  
    AND PARTY_CODE = @PARTY_CODE  
    AND EXCHANGE = @EXCHANGE_NEW   
    AND SEGMENT = @SEGMENT_NEW   
  
   END  
  
   FETCH NEXT FROM @EXCHANGEWISE_CURSOR INTO @PARTY_CODE, @EXCHANGE_NEW, @SEGMENT_NEW, @MARG_AMT, @EXCHANGE_PRIORITY  
  
  END  
  
  CLOSE @EXCHANGEWISE_CURSOR  
  
  DEALLOCATE @EXCHANGEWISE_CURSOR  
  
  FETCH NEXT FROM @MRGCUR INTO @PARTY_CODE, @SHRT_AMT  
  
 END  
  
 CLOSE @MRGCUR  
  
 DEALLOCATE @MRGCUR  
  
   
 SET @MRGCUR = CURSOR FOR  
  
 SELECT PARTY_CODE, AVAL_MARGIN=PRADNYA.DBO.FNMAX(0,  
  
            PRADNYA.DBO.FNMIN(T2DAY_CASH,T2DAY_MARGIN_SHORT))   
  
 FROM TBL_COMBINE_REPORTING_PEAK_TDAY  
  
 WHERE MARGINDATE = @MARGINDATE   
  
 AND NOT EXISTS (SELECT PARTY_CODE FROM #PARTYCNT  
  
    WHERE #PARTYCNT.PARTY_CODE = TBL_COMBINE_REPORTING_PEAK_TDAY.PARTY_CODE)  
  
 AND TDAY_MTM_SHORT < 0 AND PRADNYA.DBO.FNMAX(0,  
  
            PRADNYA.DBO.FNMIN(T2DAY_CASH,T2DAY_MARGIN_SHORT)) > 0  
  
 ORDER BY PARTY_CODE   
  
 OPEN @MRGCUR  
  
 FETCH NEXT FROM @MRGCUR INTO @PARTY_CODE, @SHRT_AMT  
  
 WHILE @@FETCH_STATUS = 0  
  
 BEGIN  
  
  SET @EXCHANGEWISE_CURSOR = CURSOR FOR  
  
  SELECT PARTY_CODE, T.EXCHANGE, T.SEGMENT, TDAY_MTM=T_MTMAVL, EXCHANGE_PRIORITY   
  FROM TBL_COMBINE_REPORTING_PEAK_TDAY_DETAIL T, #V2_TBL_EXCHANGE_MARGIN_REPORT_PEAK T1  
  WHERE MARGINDATE = @MARGINDATE  
  AND PARTY_CODE = @PARTY_CODE  
  AND T.EXCHANGE = T1.EXCHANGE   
  AND T.SEGMENT = T1.SEGMENT   
  AND TDAY_MTM > 0 AND T_MTMAVL < 0  
  AND T.EXCHANGE IN ('NCX','MCX','NCM','MCM','NSE')
  AND SEGMENT = (CASE WHEN EXCHANGE = 'NSE' THEN  'CAPITAL' ELSE 'FUTURES' END)
  ORDER BY EXCHANGE_PRIORITY DESC  
  
  OPEN @EXCHANGEWISE_CURSOR  
  
  FETCH NEXT FROM @EXCHANGEWISE_CURSOR INTO @PARTY_CODE, @EXCHANGE_NEW, @SEGMENT_NEW, @MARG_AMT, @EXCHANGE_PRIORITY  
  WHILE @@FETCH_STATUS = 0  
  BEGIN  
   IF @SHRT_AMT > 0   
   BEGIN  
    IF ABS(@MARG_AMT) >= ABS(@SHRT_AMT)  
    BEGIN  
  
     UPDATE TBL_COMBINE_REPORTING_PEAK_TDAY_DETAIL SET T_MTMAVL = T_MTMAVL + @SHRT_AMT  
     WHERE MARGINDATE = @MARGINDATE  
     AND PARTY_CODE = @PARTY_CODE  
     AND EXCHANGE = @EXCHANGE_NEW   
     AND SEGMENT = @SEGMENT_NEW   
  
     SET @SHRT_AMT = 0  
  
    END  
  
    ELSE  
  
    BEGIN  
  
     UPDATE TBL_COMBINE_REPORTING_PEAK_TDAY_DETAIL SET T_MTMAVL = T_MTMAVL-@MARG_AMT  
     WHERE MARGINDATE = @MARGINDATE  
     AND PARTY_CODE = @PARTY_CODE  
     AND EXCHANGE = @EXCHANGE_NEW   
     AND SEGMENT = @SEGMENT_NEW   
  
     SET @SHRT_AMT = @SHRT_AMT + @MARG_AMT  
  
    END  
  
   END  
  
   ELSE  
  
   BEGIN  
  
    UPDATE TBL_COMBINE_REPORTING_PEAK_TDAY_DETAIL SET T_MTMAVL = T_MTMAVL - @MARG_AMT  
    WHERE MARGINDATE = @MARGINDATE  
    AND PARTY_CODE = @PARTY_CODE  
    AND EXCHANGE = @EXCHANGE_NEW   
    AND SEGMENT = @SEGMENT_NEW   
  
   END  
  
   FETCH NEXT FROM @EXCHANGEWISE_CURSOR INTO @PARTY_CODE, @EXCHANGE_NEW, @SEGMENT_NEW, @MARG_AMT, @EXCHANGE_PRIORITY  
  
  END  
  
  CLOSE @EXCHANGEWISE_CURSOR  
  
  DEALLOCATE @EXCHANGEWISE_CURSOR  
  
  FETCH NEXT FROM @MRGCUR INTO @PARTY_CODE, @SHRT_AMT  
  
 END  
  
 CLOSE @MRGCUR  
  
 DEALLOCATE @MRGCUR    
  
  
  
END  
  
UPDATE TBL_COMBINE_REPORTING_PEAK_TDAY_DETAIL SET 
T_MARGINAVL = (CASE WHEN T_MARGINAVL >= 0 THEN T_MARGINAVL + CASHBENEFIT ELSE T_MARGINAVL END), TDAY_MARGIN = TDAY_MARGIN + CASHBENEFIT
FROM #EPNREV 
WHERE MARGINDATE  = @MARGINDATE AND EXCHANGE = 'NSE' AND SEGMENT = 'CAPITAL'
AND TBL_COMBINE_REPORTING_PEAK_TDAY_DETAIL.PARTY_CODE = #EPNREV.PARTY_CODE 
--AND TDAY_MARGIN > 0 

UPDATE TBL_COMBINE_REPORTING_PEAK_TDAY SET TDAY_CASH = TDAY_CASH + CASHBENEFIT, 
TDAY_MARGIN = TDAY_MARGIN + CASHBENEFIT, 
TDAY_MARGIN_SHORT = (CASE WHEN TDAY_MARGIN_SHORT < 0 THEN TDAY_MARGIN_SHORT ELSE TDAY_MARGIN_SHORT + CASHBENEFIT END)
FROM #EPNREV 
WHERE MARGINDATE  = @MARGINDATE 
AND TBL_COMBINE_REPORTING_PEAK_TDAY.PARTY_CODE = #EPNREV.PARTY_CODE 

UPDATE TBL_COMBINE_REPORTING_PEAK_TDAY SET TDAY_MARGIN_SHORT = A.TDAY_MARGIN_SHORT 
FROM ( 
SELECT  PARTY_CODE, TDAY_MARGIN_SHORT = SUM(T_MARGINAVL)
FROM TBL_COMBINE_REPORTING_PEAK_TDAY_DETAIL 
WHERE MARGINDATE = @MARGINDATE AND T_MARGINAVL < 0 
GROUP BY PARTY_CODE ) A
WHERE MARGINDATE = @MARGINDATE
AND A.PARTY_CODE = TBL_COMBINE_REPORTING_PEAK_TDAY.PARTY_CODE 

UPDATE TBL_COMBINE_REPORTING_PEAK_TDAY_DETAIL SET T_MARGINAVL = -TDAY_MARGIN 
WHERE MARGINDATE = @MARGINDATE AND T_MARGINAVL < 0 AND ABS(T_MARGINAVL) > TDAY_MARGIN

GO
