-- Object: PROCEDURE dbo.First_Trade_Reversal_BKP_24062019
-- Server: 10.253.33.91 | DB: MSAJAG
--------------------------------------------------


 --FIRST_TRADE_REVERSAL '2019-06-23' ,'48'
CREATE PROC [dbo].[First_Trade_Reversal_BKP_24062019] (@SDATE DATETIME , @TIMELIMIT INT)
AS


DECLARE @DAY INT
SET @DAY = @TIMELIMIT/24 


SET @DAY = (CASE WHEN  @DAY=1 THEN 0 ELSE @DAY END)


DECLARE @PREVDATE DATETIME ,@CURDATE DATETIME

 
SELECT @CURDATE = MAX(START_DATE)   FROM SETT_MST WHERE START_DATE < @SDATE  AND SETT_TYPE ='N'


SELECT @PREVDATE=MAX(START_DATE)  FROM SETT_MST WHERE START_DATE < @SDATE-@DAY  AND SETT_TYPE ='N'

 

SELECT CLIENTCODE INTO #CLIENT FROM [196.1.115.167].KYC.DBO.VW_ITRADE_CAMPAIGN_CONSENT WHERE CLIENTCONSENTDATE >=@PREVDATE 
AND CLIENTCONSENTDATE <=@CURDATE + ' 23:59'   
 
 SELECT * FROM [196.1.115.167].KYC.DBO.VW_ITRADE_CAMPAIGN_CONSENT



SELECT DISTINCT C.PARTY_CODE,ORDER_TIME,ORDER_NO,BROKERAGE ,EXCHANGE,SEGMENT INTO #REVERSAL FROM COMMON_CONTRACT_DATA C WHERE EXISTS ( SELECT * FROM (
SELECT PARTY_CODE,MIN(ORDER_TIME)ORDER_TIME  FROM COMMON_CONTRACT_DATA M  WHERE SAUDA_DATE >=@PREVDATE    AND SAUDA_DATE <=@CURDATE +' 23:59'
 AND PARTY_CODE IN (SELECT * FROM #CLIENT) AND SCRIPNAME <>'BROKERAGE' AND (ORDER_TIME <>'' AND ORDER_TIME <>'00:00:00') GROUP BY PARTY_CODE
  )D WHERE  C.PARTY_CODE=D.PARTY_CODE AND C.ORDER_TIME=D.ORDER_TIME 
 ) AND SAUDA_DATE >=@PREVDATE    AND SAUDA_DATE <=@CURDATE +' 23:59'


 SELECT DISTINCT C.PARTY_CODE,ORDER_TIME,ORDER_NO,BROKERAGE,EXCHANGE,SEGMENT INTO  #REVERSAL_COMM FROM ANGELCOMMODITY.MCDX.DBO.COMMON_CONTRACT_DATA C 
 WHERE EXISTS ( SELECT * FROM (
SELECT PARTY_CODE,MIN(ORDER_TIME)ORDER_TIME  FROM ANGELCOMMODITY.MCDX.DBO.COMMON_CONTRACT_DATA M  WHERE SAUDA_DATE >=@PREVDATE    AND SAUDA_DATE <=@CURDATE +' 23:59'
 AND PARTY_CODE IN (SELECT * FROM #CLIENT) AND SCRIPNAME <>'BROKERAGE' AND (ORDER_TIME <>'' AND ORDER_TIME <>'00:00:00') GROUP BY PARTY_CODE
  )D WHERE  C.PARTY_CODE=D.PARTY_CODE AND C.ORDER_TIME=D.ORDER_TIME 
 ) 
AND SAUDA_DATE >=@PREVDATE    AND SAUDA_DATE <=@CURDATE +' 23:59'



 
SELECT R.PARTY_CODE,R.ORDER_TIME,R.ORDER_NO,SUM(C.BROKERAGE) AS BROKERAGE,R.EXCHANGE,R.SEGMENT INTO #FINAL
FROM #REVERSAL R, COMMON_CONTRACT_DATA C 
WHERE  C.PARTY_CODE=R.PARTY_CODE AND R.ORDER_NO=C.ORDER_NO AND SAUDA_DATE >=@PREVDATE    AND SAUDA_DATE <=@CURDATE +' 23:59' AND (C.ORDER_TIME ='' OR C.ORDER_TIME ='00:00:00')
GROUP BY R.PARTY_CODE,R.ORDER_TIME,R.ORDER_NO,R.EXCHANGE,R.SEGMENT


INSERT INTO #FINAL
SELECT R.PARTY_CODE,R.ORDER_TIME,R.ORDER_NO,SUM(C.BROKERAGE) AS BROKERAGE ,R.EXCHANGE,R.SEGMENT
FROM #REVERSAL_COMM R, COMMON_CONTRACT_DATA C 
WHERE  C.PARTY_CODE=R.PARTY_CODE AND R.ORDER_NO=C.ORDER_NO AND SAUDA_DATE >=@PREVDATE    AND SAUDA_DATE <=@CURDATE +' 23:59' AND (C.ORDER_TIME ='' OR C.ORDER_TIME ='00:00:00')
GROUP BY R.PARTY_CODE,R.ORDER_TIME,R.ORDER_NO,R.EXCHANGE,R.SEGMENT



 

SELECT F.*,@CURDATE  AS SAUDA_DATE ,B2C FROM #FINAL F,[196.1.115.132].RISK.DBO.CLIENT_DETAILS D,
(SELECT PARTY_CODE,MIN(ORDER_TIME) ORDER_TIME  FROM #FINAL GROUP BY PARTY_CODE) M
WHERE F.PARTY_CODE =D.CL_CODE AND F.ORDER_TIME =M.ORDER_TIME
AND F.PARTY_CODE =M.PARTY_CODE

GO
