-- Object: PROCEDURE dbo.USP_AUTO_ARCHIVAL_ORDER_TRANS_JV_CALC
-- Server: 10.253.33.91 | DB: MSAJAG
--------------------------------------------------

CREATE PROCEDURE dbo.USP_AUTO_ARCHIVAL_ORDER_TRANS_JV_CALC
AS
BEGIN

  DECLARE @TradeDT Date
  SELECT @TradeDT =Min(TRADE_DATE) FROM ORDER_TRANS_JV_CALC WITH(NOLOCK) where ORDER_TYPE ='ONLINE'
  DECLARE @ToDt DATE
  SELECT @ToDt =CONVERT(DATE,DATEADD(DD, -7, GETDATE()) )

  --DELETE A  FROM ORDER_TRANS_JV_CALC A WITH(NOLOCK) 
  --          WHERE TRADE_DATE >=@TradeDT  AND TRADE_DATE <=@ToDt 
  --                AND ORDER_TYPE ='ONLINE'
  IF(@TradeDT > @ToDt)
  BEGIN
    RETURN;
  END
  ELSE 
  BEGIN
  IF OBJECT_ID('tempdb..#TEMP_ORDER_TRANS_JV_CALC') IS NOT NULL
    DROP TABLE #TEMP_ORDER_TRANS_JV_CALC
  Select 
  SR_NO
  ,PARTY_CODE
  ,SUB_BROKER
  ,PRODUCT_TYPE
  ,ORDER_NO
  ,ORDER_TYPE
  ,EXCHANGE
  ,SEGMENT
  ,ORDER_FLAG
  ,CL_TYPE
  ,TRADE_DATE
  ,STATE  INTO #TEMP_ORDER_TRANS_JV_CALC 
  FROM ORDER_TRANS_JV_CALC A WITH(NOLOCK) WHERE 
                             TRADE_DATE >=@TradeDT  AND TRADE_DATE <=@ToDt 
--------------- Step 2 Insert to History Tables 
set QUOTED_IDENTIFIER ON
SET IDENTITY_INSERT ORDER_TRANS_JV_CALC_HISTORY ON
INSERT INTO ORDER_TRANS_JV_CALC_HISTORY
(
SR_NO
,PARTY_CODE
,SUB_BROKER
,PRODUCT_TYPE
,ORDER_NO
,ORDER_TYPE
,EXCHANGE
,SEGMENT
,ORDER_FLAG
,CL_TYPE
,TRADE_DATE
,STATE
)
SELECT * FROM #TEMP_ORDER_TRANS_JV_CALC

SET IDENTITY_INSERT ORDER_TRANS_JV_CALC_HISTORY OFF
----------------------------------------------------  

--Deletion From Main Tables 
DELETE A  FROM ORDER_TRANS_JV_CALC A WITH(NOLOCK) 
            WHERE TRADE_DATE >=@TradeDT  AND TRADE_DATE <=@ToDt 
                  AND ORDER_TYPE ='ONLINE'
 END
--SELECT MAX(TRADE_DATE),MIN(TRADE_DATE) FROm #TEMP_ORDER_TRANS_JV_CALC
--Select Count(1),TRADE_DATE from #TEMP_ORDER_TRANS_JV_CALC-- WHERE ORDER_TYPE <> 'OFFLINE' and TRADE_DATE <'2022-04-29'
--Group by TRADE_DATE
--order by TRADE_DATE
--sp_spaceused 'ORDER_TRANS_JV_CALC_HISTORY'
--select 990563265 /10000000 , 114577224/1024/1024

END

GO
