-- Object: PROCEDURE dbo.ADDEDIT_ADDITIONAL_BROEKRAGE_bak_13022019
-- Server: 10.253.33.91 | DB: MSAJAG
--------------------------------------------------



create PROCEDURE [dbo].[ADDEDIT_ADDITIONAL_BROEKRAGE_bak_13022019]      
(      
 @PARTY_CODE VARCHAR(10),      
 @BRANCH_CD VARCHAR(10),      
 @SUB_BROKER VARCHAR(25),      
 @FROMDATE VARCHAR(10),      
 @TODATE VARCHAR(10),      
 @TRD_BROK_VAL NUMERIC(18,4),      
 @DEL_BROK_VAL NUMERIC(18,4),      
 @RECTYPE VARCHAR(4),      
 @USERID VARCHAR(10),      
 @SRNO INT       
)      
AS      
BEGIN      
 IF @RECTYPE='ADD'       
 BEGIN         
  IF(SELECT COUNT(*) FROM TBL_ADDITIONAL_BROEKRAGE WHERE PARTY_CODE = @PARTY_CODE AND BRANCH_CD = @BRANCH_CD AND SUB_BROKER= @SUB_BROKER    
 AND ((FROMDATE BETWEEN CONVERT(VARCHAR(11), CONVERT(DATETIME, @FROMDATE, 103), 109) AND CONVERT(VARCHAR(11), CONVERT(DATETIME, @TODATE, 103), 109) + ' 23:59:59')    
 OR (TODATE BETWEEN CONVERT(VARCHAR(11), CONVERT(DATETIME, @FROMDATE, 103), 109) AND CONVERT(VARCHAR(11), CONVERT(DATETIME, @TODATE, 103), 109) + ' 23:59:59')))>0    
  BEGIN    
 SELECT 'DUPLICATE RECORD'     
 RETURN    
  END    
     
  INSERT INTO TBL_ADDITIONAL_BROEKRAGE(PARTY_CODE,BRANCH_CD,SUB_BROKER,TRD_BROK_VAL,DEL_BROK_VAL,FROMDATE,TODATE,ADDED_BY,ADDED_ON,MODIFIED_BY,MODIFIED_ON)      
  VALUES(@PARTY_CODE,@BRANCH_CD,@SUB_BROKER,@TRD_BROK_VAL,@DEL_BROK_VAL,CONVERT(VARCHAR(11), CONVERT(DATETIME, @FROMDATE, 103), 109),CONVERT(VARCHAR(11),      
  CONVERT(DATETIME, @TODATE, 103), 109),@USERID,GETDATE(),'','')     
  SELECT 'RECORD INSERTED SUCCESSFULLY'     
 END      
 IF @RECTYPE='EDIT'     
 BEGIN      
 UPDATE TBL_ADDITIONAL_BROEKRAGE SET     
  BRANCH_CD = @BRANCH_CD,    
  SUB_BROKER= @SUB_BROKER,    
  TRD_BROK_VAL =@TRD_BROK_VAL,    
  DEL_BROK_VAL = @DEL_BROK_VAL,    
  FROMDATE = CONVERT(VARCHAR(11), CONVERT(DATETIME, @FROMDATE, 103), 109),    
  TODATE = CONVERT(VARCHAR(11), CONVERT(DATETIME, @TODATE, 103), 109) + ' 23:59:59',    
  MODIFIED_BY = @USERID,    
  MODIFIED_ON = GETDATE()    
 WHERE PARTY_CODE =@PARTY_CODE AND TODATE >=GETDATE()
 
 UPDATE ANAND.BSEDB_AB.DBO.TBL_ADDITIONAL_BROEKRAGE SET     
  BRANCH_CD = @BRANCH_CD,    
  SUB_BROKER= @SUB_BROKER,    
  TRD_BROK_VAL =@TRD_BROK_VAL,    
  DEL_BROK_VAL = @DEL_BROK_VAL,    
  FROMDATE = CONVERT(VARCHAR(11), CONVERT(DATETIME, @FROMDATE, 103), 109),    
  TODATE = CONVERT(VARCHAR(11), CONVERT(DATETIME, @TODATE, 103), 109) + ' 23:59:59',    
  MODIFIED_BY = @USERID,    
  MODIFIED_ON = GETDATE()    
 WHERE PARTY_CODE =@PARTY_CODE AND TODATE >=GETDATE()
 
  
  UPDATE ANGELFO.NSEFO.DBO.TBL_ADDITIONAL_BROEKRAGE SET     
  BRANCH_CD = @BRANCH_CD,    
  SUB_BROKER= @SUB_BROKER,    
  TRD_BROK_VAL =@TRD_BROK_VAL,    
  DEL_BROK_VAL = @DEL_BROK_VAL,    
  FROMDATE = CONVERT(VARCHAR(11), CONVERT(DATETIME, @FROMDATE, 103), 109),    
  TODATE = CONVERT(VARCHAR(11), CONVERT(DATETIME, @TODATE, 103), 109) + ' 23:59:59',    
  MODIFIED_BY = @USERID,    
  MODIFIED_ON = GETDATE()    
 WHERE PARTY_CODE =@PARTY_CODE AND TODATE >=GETDATE()
 
   UPDATE ANGELFO.NSECURFO.DBO.TBL_ADDITIONAL_BROEKRAGE SET     
  BRANCH_CD = @BRANCH_CD,    
  SUB_BROKER= @SUB_BROKER,    
  TRD_BROK_VAL =@TRD_BROK_VAL,    
  DEL_BROK_VAL = @DEL_BROK_VAL,    
  FROMDATE = CONVERT(VARCHAR(11), CONVERT(DATETIME, @FROMDATE, 103), 109),    
  TODATE = CONVERT(VARCHAR(11), CONVERT(DATETIME, @TODATE, 103), 109) + ' 23:59:59',    
  MODIFIED_BY = @USERID,    
  MODIFIED_ON = GETDATE()    
 WHERE PARTY_CODE =@PARTY_CODE AND TODATE >=GETDATE()
 
    UPDATE ANGELCOMMODITY.MCDX.DBO.TBL_ADDITIONAL_BROEKRAGE SET     
  BRANCH_CD = @BRANCH_CD,    
  SUB_BROKER= @SUB_BROKER,    
  TRD_BROK_VAL =@TRD_BROK_VAL,    
  DEL_BROK_VAL = @DEL_BROK_VAL,    
  FROMDATE = CONVERT(VARCHAR(11), CONVERT(DATETIME, @FROMDATE, 103), 109),    
  TODATE = CONVERT(VARCHAR(11), CONVERT(DATETIME, @TODATE, 103), 109) + ' 23:59:59',    
  MODIFIED_BY = @USERID,    
  MODIFIED_ON = GETDATE()    
 WHERE PARTY_CODE =@PARTY_CODE AND TODATE >=GETDATE()
 
     UPDATE ANGELCOMMODITY.NCDX.DBO.TBL_ADDITIONAL_BROEKRAGE SET     
  BRANCH_CD = @BRANCH_CD,    
  SUB_BROKER= @SUB_BROKER,    
  TRD_BROK_VAL =@TRD_BROK_VAL,    
  DEL_BROK_VAL = @DEL_BROK_VAL,    
  FROMDATE = CONVERT(VARCHAR(11), CONVERT(DATETIME, @FROMDATE, 103), 109),    
  TODATE = CONVERT(VARCHAR(11), CONVERT(DATETIME, @TODATE, 103), 109) + ' 23:59:59',    
  MODIFIED_BY = @USERID,    
  MODIFIED_ON = GETDATE()    
 WHERE PARTY_CODE =@PARTY_CODE AND TODATE >=GETDATE()
 
UPDATE ANGELCOMMODITY.MCDXCDS.DBO.TBL_ADDITIONAL_BROEKRAGE SET     
  BRANCH_CD = @BRANCH_CD,    
  SUB_BROKER= @SUB_BROKER,    
  TRD_BROK_VAL =@TRD_BROK_VAL,    
  DEL_BROK_VAL = @DEL_BROK_VAL,    
  FROMDATE = CONVERT(VARCHAR(11), CONVERT(DATETIME, @FROMDATE, 103), 109),    
  TODATE = CONVERT(VARCHAR(11), CONVERT(DATETIME, @TODATE, 103), 109) + ' 23:59:59',    
  MODIFIED_BY = @USERID,    
  MODIFIED_ON = GETDATE()    
 WHERE PARTY_CODE =@PARTY_CODE AND TODATE >=GETDATE() 
         
     
    SELECT 'RECORD UPDATED SUCCESSFULLY'    
    
 END      
       
END

GO
