-- Object: PROCEDURE dbo.CLS_MARGIN_SHORTAGE_PENALTY
-- Server: 10.253.33.91 | DB: MSAJAG
--------------------------------------------------



  
  
CREATE PROCEDURE [dbo].[CLS_MARGIN_SHORTAGE_PENALTY]  
(  

 @STATUSID VARCHAR(15),        
 @STATUSNAME VARCHAR(25),  
 @MARGIN_DATE_FROM VARCHAR(11),  
 @MARGIN_DATE_TO VARCHAR(11),  
 @PARTY_FROM VARCHAR(11),  
 @PARTY_TO VARCHAR(11)  
)  
AS  
  
IF @PARTY_TO = ''  
BEGIN  
 SET @PARTY_TO = 'ZZZZZZZZZ'  
END  

IF LEN(@MARGIN_DATE_FROM) = 10 AND CHARINDEX('/',@MARGIN_DATE_FROM) > 0    
BEGIN
	SET @MARGIN_DATE_FROM = CONVERT(VARCHAR (11), CONVERT(DATETIME,@MARGIN_DATE_FROM,103),109)
END

IF LEN(@MARGIN_DATE_TO) = 10 AND CHARINDEX('/',@MARGIN_DATE_TO) > 0    
BEGIN
	SET @MARGIN_DATE_TO = CONVERT(VARCHAR (11), CONVERT(DATETIME,@MARGIN_DATE_TO,103),109)
END

DECLARE @EXCHANGE VARCHAR(15)

SELECT TOP 1 @EXCHANGE =EXCHANGE +' - CAPITAL' FROM GLOBALS (NOLOCK)
  
SELECT   
 MARGINDATE = CONVERT(VARCHAR,P.MARGIN_DATE,103),  
 CLIENT_CODE = P.PARTY_CODE,
 CLIENT_NAME = LONG_NAME,
 SHORTAGE,PENALTY_PERC,PENALTY_AMT, 
 DAYS_3_COUNT, MONTH_5_COUNT,SHORTAGE_COUNT = M.NCOUNT,   
 LEDGER_POST_FLAG = CASE WHEN LEDGER_POST_FLAG = 0 THEN 'N' ELSE 'Y' END, 
 SERVICE_TAX, 
 MDAY = DAY(P.MARGIN_DATE),  
 MMONTH = MONTH(P.MARGIN_DATE),  
 MYEAR = YEAR(P.MARGIN_DATE),
 L_ADDRESS1 = ISNULL(L_ADDRESS1,''),
L_ADDRESS2 = ISNULL(L_ADDRESS2,''),
L_ADDRESS3 = ISNULL(L_ADDRESS3,''),
L_CITY = ISNULL(L_CITY,''),
L_ZIP = ISNULL(L_ZIP,''),
L_STATE = ISNULL(L_STATE,''),
L_NATION = ISNULL(L_NATION,''),
PAN_GIR_NO = ISNULL(PAN_GIR_NO,''),
EXCHANGE = @EXCHANGE	  
FROM   
 CMMARGIN_PENALTY P (NOLOCK),  
 CLIENT1 C1 (NOLOCK),  
 CLIENT2 C2 (NOLOCK),  
 CMMARGIN_PENALTY_POST_STAT L (NOLOCK),  
 (  
  SELECT PARTY_CODE, NCOUNT = COUNT(1) ,  
  COUNTMONTH = MONTH(MARGIN_DATE)  
  FROM CMMARGIN_PENALTY (NOLOCK)   
  WHERE MARGIN_DATE BETWEEN  @MARGIN_DATE_FROM AND @MARGIN_DATE_TO + ' 23:59'  

  GROUP BY PARTY_CODE,MONTH(MARGIN_DATE)  
 ) M  
WHERE   
 P.MARGIN_DATE = L.MARGIN_DATE  
 AND COUNTMONTH = MONTH(P.MARGIN_DATE)  
 AND P.PARTY_CODE = C2.PARTY_CODE  
 AND C1.CL_CODE = C2.CL_CODE  
 AND M.PARTY_CODE = P.PARTY_CODE  
 AND L.MARGIN_DATE BETWEEN  @MARGIN_DATE_FROM AND @MARGIN_DATE_TO + ' 23:59'  
 AND M.PARTY_CODE BETWEEN @PARTY_FROM AND @PARTY_TO  
    AND @STATUSNAME = (         
    CASE         
            WHEN @STATUSID = 'BRANCH'         
            THEN C1.BRANCH_CD         
            WHEN @STATUSID = 'SUBBROKER'         
            THEN C1.SUB_BROKER         
            WHEN @STATUSID = 'TRADER'         
            THEN C1.TRADER         
            WHEN @STATUSID = 'FAMILY'         
            THEN C1.FAMILY         
            WHEN @STATUSID = 'AREA'         
            THEN C1.AREA         
            WHEN @STATUSID = 'REGION'         
            THEN C1.REGION         
            WHEN @STATUSID = 'CLIENT'         
 THEN C2.PARTY_CODE         
            ELSE 'BROKER' END)         
ORDER BY MDAY,MMONTH,MYEAR

GO
