-- Object: PROCEDURE dbo.RPT_HOLDING_AGEING_RPT
-- Server: 10.253.33.91 | DB: MSAJAG
--------------------------------------------------


CREATE PROC [dbo].[RPT_HOLDING_AGEING_RPT]
(
    @ROSDATE		VARCHAR(11),
	@NOOFDAYS		INT = 5,
	@PARTY_CODE		VARCHAR(10)='',
	@ISIN			VARCHAR(12)='',
	@TOPARTY_CODE		VARCHAR(20)='',
	@STATUSID		VARCHAR(20)='',
	@STATUSNAME		VARCHAR(30)=''
)

AS
	--EXEC RPT_HOLDING_AGEING_RPT 'OCT 10 2019', 5, '', '','ZZZZZZZZ','BROKER','BROKER'

	SELECT T.SETT_NO, T.SETT_TYPE,PARTY_CODE,SCRIP_CD,T.SERIES,ISIN=CERTNO,QTY=SUM(CRQTY-DRQTY),BDPID,BCLTDPID,
	HOLDDATE=MIN(TRANSDATE),NOOFDAYS=1, CL_RATE=CONVERT(NUMERIC(18,4),0),
	RUNDATE=GETDATE()
	INTO #HOLD FROM TBL_DEL_HOLD_SEC T, SETT_MST S, DELIVERYDP D
	WHERE T.SETT_NO = S.SETT_NO AND T.SETT_TYPE = S.SETT_TYPE
	AND T.SETT_NO<>'2000000' AND PARTY_CODE NOT IN('BROKER','NSE','BSE','EXE')
	AND D.DPID=T.BDPID AND T.BCLTDPID=DPCLTNO
	AND DESCRIPTION LIKE '%CUSA%'
	AND PARTY_CODE = (CASE WHEN @PARTY_CODE = '' THEN PARTY_CODE ELSE  @PARTY_CODE END)
	AND CERTNO = (CASE WHEN @ISIN = '' THEN CERTNO ELSE @ISIN END)
	and transdate <= @ROSDATE+' 23:59'
	GROUP BY T.SETT_NO, T.SETT_TYPE,T.PARTY_CODE,SCRIP_CD,T.SERIES,CERTNO,BDPID,BCLTDPID,SEC_PAYIN
	HAVING SUM(CRQTY-DRQTY) > 0 

	UPDATE #HOLD SET NOOFDAYS = 
	(SELECT ISNULL(COUNT(DISTINCT LEFT(SEC_PAYIN,11)),0) FROM SETT_MST S
	WHERE S.SEC_PAYIN >= #HOLD.HOLDDATE AND S.SEC_PAYIN <= @ROSDATE +' 23:59'
	AND SETT_TYPE IN ('N','D'))

	SELECT SCRIP_CD, SERIES, CL_RATE, ISIN = CONVERT(VARCHAR(12),'')
	INTO #CLDATA 
	FROM CLOSING C 
	WHERE SYSDATE = (SELECT MAX(SYSDATE) FROM CLOSING 
						WHERE SYSDATE <= LEFT(GETDATE(),11) + ' 23:59')

	INSERT INTO #CLDATA 
	SELECT SCRIP_CD, SERIES, CL_RATE, ISIN = CONVERT(VARCHAR(12),'')
	FROM BSEDB.DBO.CLOSING C 
	WHERE SYSDATE = (SELECT MAX(SYSDATE) FROM BSEDB.DBO.CLOSING 
						WHERE SYSDATE <= LEFT(GETDATE(),11) + ' 23:59')

	UPDATE #CLDATA SET ISIN = M.ISIN
	FROM MULTIISIN_NEW M
	WHERE #CLDATA.SCRIP_CD = M.SCRIP_CD
	AND #CLDATA.SERIES IN ('EQ','BE','BZ')
	AND M.SERIES IN ('EQ','BE','BZ')
	AND GETDATE() BETWEEN EFF_FROM AND EFF_TO

	UPDATE #CLDATA SET ISIN = M.ISIN
	FROM MULTIISIN_NEW M
	WHERE #CLDATA.SCRIP_CD = M.SCRIP_CD
	AND #CLDATA.SERIES = M.SERIES
	AND GETDATE() BETWEEN EFF_FROM AND EFF_TO
	AND #CLDATA.ISIN = ''

	UPDATE #CLDATA SET ISIN = M.ISIN
	FROM BSEDB.DBO.MULTIISIN_NEW M
	WHERE #CLDATA.SCRIP_CD = M.SCRIP_CD
	AND GETDATE() BETWEEN EFF_FROM AND EFF_TO
	AND #CLDATA.ISIN = ''

	UPDATE #HOLD SET CL_RATE = C.CL_RATE 
	FROM (SELECT ISIN, CL_RATE = MIN(CL_RATE) 
			FROM #CLDATA C  
			GROUP BY ISIN) C
	WHERE #HOLD.ISIN = C.ISIN

	SELECT *, 
	NSE_SYMBOL=CONVERT(VARCHAR(12),''), 
	NSE_SERIES=CONVERT(VARCHAR(3),''),
	BSECODE=CONVERT(VARCHAR(12),''),
	SCRIP_NAME=CONVERT(VARCHAR(50),'')  
	INTO #HOLDAGE
	FROM  #HOLD 
	
	UPDATE #HOLDAGE SET NSE_SYMBOL = M.SCRIP_CD, NSE_SERIES = M.SERIES
	FROM MULTIISIN_NEW M  (NOLOCK)
	WHERE M.ISIN = #HOLDAGE.ISIN 
	AND @ROSDATE BETWEEN EFF_FROM AND EFF_TO

	UPDATE #HOLDAGE SET NSE_SYMBOL = M.SCRIP_CD, NSE_SERIES = M.SERIES
	FROM MULTIISIN M  (NOLOCK)
	WHERE M.ISIN = #HOLDAGE.ISIN 
	AND VALID = 1 and NSE_SYMBOL =''
	
	UPDATE #HOLDAGE SET BSECODE = M.SCRIP_CD 
	FROM MULTIISIN_NEW M  (NOLOCK)
	WHERE M.ISIN = #HOLDAGE.ISIN 
	AND @ROSDATE BETWEEN EFF_FROM AND EFF_TO

	UPDATE #HOLDAGE SET BSECODE = M.SCRIP_CD 
	FROM BSEDB.dbo.MULTIISIN M  (NOLOCK)
	WHERE M.ISIN = #HOLDAGE.ISIN 
	AND VALID = 1 and BSECODE =''

	UPDATE #HOLDAGE SET SCRIP_NAME = LEFT(S1.LONG_NAME,50) FROM SCRIP1 S1, SCRIP2 S2
	WHERE S1.CO_CODE = S2.CO_CODE AND S1.SERIES = S2.SERIES
	AND S2.SCRIP_CD = NSE_SYMBOL AND S2.SERIES = NSE_SERIES
	AND NSE_SYMBOL <> ''

	UPDATE #HOLDAGE SET SCRIP_NAME = LEFT(S1.LONG_NAME,50) FROM BSEDB.DBO.SCRIP1 S1, BSEDB.DBO.SCRIP2 S2
	WHERE S1.CO_CODE = S2.CO_CODE AND S1.SERIES = S2.SERIES
	AND S2.BSECODE = #HOLDAGE.BSECODE 
	AND SCRIP_NAME = ''
	AND #HOLDAGE.BSECODE <> ''

	SELECT 
	SETT_NO,SETT_TYPE,h.PARTY_CODE,NSE_SYMBOL,NSE_SERIES,BSECODE,SCRIP_NAME,ISIN,
	QTY,BDPID,BCLTDPID,HOLDDATE=LEFT(HOLDDATE,11),NOOFDAYS,CL_RATE,
	HOLDING_AMT=QTY*CL_RATE,
	RUNDATE=LEFT(RUNDATE,11) + ' '+ CONVERT(VARCHAR,RUNDATE,108) 
	FROM #HOLDAGE H, CLIENT_DETAILS D(NOLOCK)
	WHERE H.PARTY_CODE = D.CL_CODE
	AND @STATUSNAME = 
					(CASE 
						WHEN @STATUSID = 'BRANCH'		THEN D.BRANCH_CD 
						WHEN @STATUSID = 'SUBBROKER'	THEN D.SUB_BROKER 
						WHEN @STATUSID = 'TRADER'		THEN D.TRADER 
						WHEN @STATUSID = 'FAMILY'		THEN D.FAMILY 
						WHEN @STATUSID = 'AREA'			THEN D.AREA 
						WHEN @STATUSID = 'REGION'		THEN D.REGION 
						WHEN @STATUSID = 'CLIENT'		THEN D.CL_CODE 
						ELSE 'BROKER' 
					END)
	ORDER BY H.PARTY_CODE,NOOFDAYS DESC,NSE_SYMBOL,SCRIP_NAME

	DROP TABLE #HOLD
	DROP TABLE #CLDATA
	DROP TABLE #HOLDAGE

GO
