-- Object: PROCEDURE dbo.PROC_CORPACT_ND
-- Server: 10.253.33.91 | DB: MSAJAG
--------------------------------------------------

CREATE PROC [DBO].[PROC_CORPACT_ND] AS

DELETE FROM NODEL
WHERE EXISTS ( SELECT SETT_NO FROM TBL_NSE_CORPACT_TMP T
			   WHERE T.SETT_NO <> ''
			   AND NODEL.SCRIP_CD = T.SCRIP_CD
			   AND NODEL.SERIES	 = T.SERIES
			   AND T.SETT_NO = SETTLED_IN)

INSERT INTO NODEL
SELECT SRNO, SCRIP_CD, T.SERIES,
S.SETT_NO, T.SETT_TYPE,
ND_START_DATE, ND_END_DATE = LEFT(ND_END_DATE,11) + ' 23:59',
SETTLED_IN = T.SETT_NO 
FROM TBL_NSE_CORPACT_TMP T, SETT_MST S
WHERE T.SETT_NO <> '' AND T.SETT_TYPE IN ('N', 'W')
AND LEFT(T.ND_START_DATE, 11) = LEFT(S.START_DATE, 11)
AND S.SETT_TYPE = T.SETT_TYPE

INSERT INTO TBL_NSE_CORPACT
SELECT SCRIP_CD,SERIES,SCRIP_NAME,SEC_CODE,REC_DATE,BC_START_DATE,BC_END_DATE,
EX_DATE,ND_START_DATE,ND_END_DATE,SETT_TYPE,SETT_NO,REMARK,ISIN,STATUS,UPLOADDATE 
FROM TBL_NSE_CORPACT_TMP
WHERE NOT EXISTS (SELECT SCRIP_CD FROM TBL_NSE_CORPACT T
				  WHERE TBL_NSE_CORPACT_TMP.SCRIP_CD = T.SCRIP_CD
				  AND TBL_NSE_CORPACT_TMP.SERIES	 = T.SERIES
				  AND ( TBL_NSE_CORPACT_TMP.REC_DATE	 = T.REC_DATE
				  OR	TBL_NSE_CORPACT_TMP.BC_START_DATE = T.BC_START_DATE))

SELECT SCRIP_CD,SERIES,
REC_DATE=LEFT(CONVERT(VARCHAR,REC_DATE,109),11),
BC_START_DATE=LEFT(CONVERT(VARCHAR,BC_START_DATE,109),11),
BC_END_DATE=LEFT(CONVERT(VARCHAR,BC_END_DATE,109),11),
EX_DATE=LEFT(CONVERT(VARCHAR,EX_DATE,109),11),
ND_START_DATE=LEFT(CONVERT(VARCHAR,ND_START_DATE,109),11),
ND_END_DATE=LEFT(CONVERT(VARCHAR,ND_END_DATE,109),11),
SETT_TYPE,
SETT_NO,REMARK,ISIN,STATUS,NDFLAG=(CASE WHEN SETT_NO <> '' AND SETT_TYPE IN ('N', 'W') THEN 'ND' ELSE 'NON-ND' END) 
FROM TBL_NSE_CORPACT_TMP
ORDER BY SCRIP_CD, SERIES

GO
