-- Object: PROCEDURE dbo.PROC_CC01_UPLOAD_BKUP_02May2024
-- Server: 10.253.33.91 | DB: MSAJAG
--------------------------------------------------


CREATE PROC [dbo].[PROC_CC01_UPLOAD_BKUP_02May2024] 
(
@TDATE VARCHAR(10),
@FILEFOR VARCHAR(20), 
@FILETYPE VARCHAR(50), 
@PROGID VARCHAR(50), 
@UNAME VARCHAR(50),
@FILENAME VARCHAR(100) = ''
)

AS

-- EXEC PROC_CC01_UPLOAD '09/04/2018', '', '', '1234567890', ''
DECLARE @RECCNT INT,
		@FILEDATE	DATETIME,
		@EXCHANGE	VARCHAR(3),
		@SEGMENT	VARCHAR(7)

SELECT @FILEDATE = CONVERT(DATETIME,LEFT(LEFT(RIGHT(@FILENAME,12),8),2) + '/' + RIGHT(LEFT(LEFT(RIGHT(@FILENAME,12),8),4),2) + '/' + LEFT(RIGHT(@FILENAME,8),4),103)

SELECT @EXCHANGE = ''
SELECT @SEGMENT = ''
IF LEFT(REVERSE(.DBO.PIECE(REVERSE(@FILENAME),'\',1)),2)='F_' 
BEGIN
	SELECT @EXCHANGE = 'NSE'
	SELECT @SEGMENT = 'FUTURES'
END
IF LEFT(REVERSE(.DBO.PIECE(REVERSE(@FILENAME),'\',1)),2)='C_' 
BEGIN
	SELECT @EXCHANGE = 'NSE'
	SELECT @SEGMENT = 'CAPITAL'
END
IF LEFT(REVERSE(.DBO.PIECE(REVERSE(@FILENAME),'\',1)),2)='X_' 
BEGIN
	SELECT @EXCHANGE = 'NSX'
	SELECT @SEGMENT = 'FUTURES'
END
IF LEFT(REVERSE(.DBO.PIECE(REVERSE(@FILENAME),'\',1)),2)='EQ' 
BEGIN
	SELECT @EXCHANGE = 'BSE'
	SELECT @SEGMENT = 'CAPITAL'
END 
IF LEFT(REVERSE(.DBO.PIECE(REVERSE(@FILENAME),'\',1)),2)='FO' 
BEGIN
	SELECT @EXCHANGE = 'BSE'
	SELECT @SEGMENT = 'FUTURES'
END

IF @FILEDATE <> CONVERT(DATETIME,@TDATE,103) 
BEGIN
	SELECT STRMSGCODE = -1, STRMSG = 'FILE DATE AND SELECTED DATE IS NOT MATCHING'
	RETURN
END

IF @EXCHANGE = '' 
BEGIN
	SELECT STRMSGCODE = -1, STRMSG = 'THIS FILE IS NOT CONFIGURED FOR UPLOAD'
	RETURN
END
 
DELETE FROM TBL_CC01_DATA
WHERE TRANSDATE = @FILEDATE
AND EXCHANGE = @EXCHANGE
AND SEGMENT = @SEGMENT

IF @EXCHANGE IN ('NSE','NSX')
BEGIN
	INSERT INTO TBL_CC01_DATA 
	SELECT @FILEDATE, @EXCHANGE, @SEGMENT, .DBO.PIECE(FILE_DATA,',',1),.DBO.PIECE(FILE_DATA,',',2),
		   CONVERT(NUMERIC(18,4),.DBO.PIECE(FILE_DATA,',',3))+CONVERT(NUMERIC(18,4),.DBO.PIECE(FILE_DATA,',',4)),  
			UPLOAD_BY = CONVERT(VARCHAR,.DBO.PIECE(FILE_DATA,',',2)), UPLOAD_ON = GETDATE()
	FROM FILEDATA
	WHERE PROGID = @PROGID AND ISNULL(.DBO.PIECE(FILE_DATA,',',1),'') <> ''
END

IF @EXCHANGE IN ('BSE','BSX')
BEGIN
	INSERT INTO TBL_CC01_DATA 
	SELECT @FILEDATE, @EXCHANGE, @SEGMENT, (CASE WHEN .DBO.PIECE(FILE_DATA,',',5) <> '' THEN .DBO.PIECE(FILE_DATA,',',5) ELSE .DBO.PIECE(FILE_DATA,',',6) END),
		   .DBO.PIECE(FILE_DATA,',',9),.DBO.PIECE(FILE_DATA,',',10),  
			UPLOAD_BY = @UNAME, UPLOAD_ON = GETDATE()
	FROM FILEDATA
	WHERE PROGID = @PROGID AND ISNULL(.DBO.PIECE(FILE_DATA,',',1),'') <> ''
	AND ISNULL(.DBO.PIECE(FILE_DATA,',',1),'') = REPLACE(@TDATE,'/','')
END


SELECT @RECCNT = 0 
SELECT @RECCNT = ISNULL(COUNT(1),0) FROM TBL_CC01_DATA
WHERE TRANSDATE = @FILEDATE
AND EXCHANGE = @EXCHANGE
  
SELECT STRMSGCODE = 1, STRMSG = CONVERT(VARCHAR,@RECCNT) + ' RECORD(S) UPLOADED.'

GO
