-- Object: PROCEDURE dbo.AUTO_CALCULATE_STAMP_DUTY
-- Server: 10.253.33.91 | DB: MSAJAG
--------------------------------------------------

CREATE PROC [dbo].[AUTO_CALCULATE_STAMP_DUTY]

(
	@FLAG VARCHAR(2),
	@DATE VARCHAR(11)
)
 AS
 BEGIN

 INSERT INTO CALCULATE_STAMP_DUTY_PROCESS_LOG  
		SELECT @FLAG,@DATE,GETDATE(), 'START' 
 SET  @DATE= CONVERT(varchar(11),@DATE,100)

--EXEC COMBINE_SETTLEMENT_IDX
EXEC CALCULATE_STAMP_DUTY_NEW_process @FLAG,@DATE, 'a00' ,'zzzzzz'   

 INSERT INTO CALCULATE_STAMP_DUTY_PROCESS_LOG  
	SELECT @FLAG,@DATE,GETDATE(), 'END'
SELECT 'PROCESS CALCULATE_STAMP_DUTY FOR '+@FLAG+' AND '+@DATE +' COMPLETED SUCCESSFULLY...!!!'  AS STATUS

END

GO
