-- Object: PROCEDURE dbo.GET_MTF_POSITION_UPD
-- Server: 10.253.33.91 | DB: MSAJAG
--------------------------------------------------


CREATE PROCEDURE GET_MTF_POSITION_UPD
	@REPORT_DATE VARCHAR(11),
	@PARTY_CODE VARCHAR(10) = ''
AS

CREATE TABLE #MTFDATA
(
	PARTY_CODE VARCHAR(10), 
	NETAMT MONEY
)

INSERT INTO #MTFDATA
EXEC MSAJAG..GET_MTF_SPLIT_BAL @REPORT_DATE

CREATE TABLE #CLIENT_CASH_LED_BALANCES
(
	SNO BIGINT,
	PARTY_CODE VARCHAR(10),
	NETAMT MONEY
)

CREATE NONCLUSTERED INDEX [IDX_GET_MTF_POS] ON #CLIENT_CASH_LED_BALANCES
(
	[SNO] ASC
)

INSERT INTO #CLIENT_CASH_LED_BALANCES
SELECT D.SNO, D.PARTY_CODE, 0
FROM CLIENT_CASH_LED_BALANCES D, (SELECT SNO FROM CLIENT_CASH_DETAILS WHERE REPORT_DATE = @REPORT_DATE) C
WHERE D.SNO = C.SNO AND EXCHANGE = 'MTF'

UPDATE C SET C.NETAMT = M.NETAMT FROM #CLIENT_CASH_LED_BALANCES C, #MTFDATA M
WHERE C.PARTY_CODE = M.PARTY_CODE
AND C.PARTY_CODE = @PARTY_CODE

UPDATE C SET CASH_COLL_MTF_POSITIONS = NETAMT FROM CLIENT_CASH_LED_BALANCES C, #CLIENT_CASH_LED_BALANCES C1
WHERE C.SNO = C1.SNO AND EXCHANGE = 'MTF'

GO
