-- Object: PROCEDURE dbo.PR_MIG_CITRUS_MULTIBANK_UPD_02082018
-- Server: 10.253.33.91 | DB: MSAJAG
--------------------------------------------------

--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
CREATE   PROC  [dbo].[PR_MIG_CITRUS_MULTIBANK_UPD_02082018] (@PARTY_CODE VARCHAR(12)='') AS      
      
CREATE TABLE [#MIG_CITRUS_MULTIBANK_TMP]      
(      
 [PARTY_CODE] [VARCHAR](10) NULL,      
 [BANK_NAME] [VARCHAR](100) NULL,      
 [BRANCH_NAME] [VARCHAR](150) NULL,      
 [MICR] [VARCHAR](25) NULL,      
 [IFSC_CD] [VARCHAR](25) NULL,      
 [AC_NO] [VARCHAR](20) NOT NULL,      
 [AC_TYPE] [VARCHAR](20) NOT NULL,      
 [AC_NAME] [VARCHAR](100) NULL,      
 [DEF] [INT],      
 [BANM_ID] [VARCHAR](20) NOT NULL      
)       
      
      
CREATE CLUSTERED INDEX IDXBNK ON #MIG_CITRUS_MULTIBANK_TMP (PARTY_CODE,BANK_NAME,BRANCH_NAME)      


INSERT INTO #MIG_CITRUS_MULTIBANK_TMP       
SELECT BO_PARTYCODE,BANM_NAME,BANM_BRANCH,BANM_MICR,BANM_IFSC_CD,CLIBA_AC_NO,      
AC_TYPE= CASE WHEN CLIBA_AC_TYPE in ( 'SAVINGS','SAVING') THEN 'SAVING'       
   WHEN CLIBA_AC_TYPE = 'CURRENT' THEN 'CURRENT'          
   ELSE '' END,CLIBA_AC_NAME,CLIBA_DEF_FLG, BANM_ID = CONVERT(VARCHAR(20), BANM_ID)      
FROM [172.31.16.57].CRMDB_A.DBO.VIEW_CLASS_CLIENT_MULTIBANK_ALL A      
WHERE  CLIBA_AC_NO <> '' 
and bo_partycode='SHJV1061'     
--AND BO_PARTYCODE IN (SELECT PARTY_CODE FROM [172.31.16.57].CRMDB_A.DBO.CLIENT_DP_BANK_MIG WITH (NOLOCK) WHERE UPD_FLAG = 'N' AND MOD3 LIKE '%BANK%')
      
IF (SELECT COUNT(1) FROM #MIG_CITRUS_MULTIBANK_TMP) =0      
BEGIN      
 RETURN      
END      
      
DECLARE @SHAREDB VARCHAR(35)      
DECLARE @SHARESERVER VARCHAR(35)      
DECLARE @ACCOUNTDB VARCHAR(35)      
DECLARE @ACCOUNTSERVER VARCHAR(35)      
DECLARE @EXCHANGEWISE_CURSOR CURSOR       
DECLARE @STRSQL VARCHAR(8000)       
      
SET @EXCHANGEWISE_CURSOR = CURSOR      
FOR      
SELECT DISTINCT SHAREDB,SHARESERVER,ACCOUNTDB,ACCOUNTSERVER      
FROM PRADNYA..MULTICOMPANY M(NOLOCK)      
WHERE PRIMARYSERVER=1      
AND LEFT(ACCOUNTDB,7) ='ACCOUNT'      
--AND EXCHANGE = 'NSE'      
--AND SEGMENT = 'CAPITAL'      
      
OPEN @EXCHANGEWISE_CURSOR      
      
FETCH NEXT FROM @EXCHANGEWISE_CURSOR INTO @SHAREDB,@SHARESERVER,@ACCOUNTDB,@ACCOUNTSERVER      
       
WHILE @@FETCH_STATUS = 0      
BEGIN      
 SET @STRSQL = ''      
 IF @SHARESERVER = @@SERVERNAME       
 BEGIN      
  SET @SHARESERVER =''      
  SET @ACCOUNTSERVER =''      
 END      
 ELSE      
 BEGIN      
  SET @SHARESERVER = @SHARESERVER + '.'      
  SET @ACCOUNTSERVER = @ACCOUNTSERVER + '.'      
 END      
       
 /*      
 SET @STRSQL = 'INSERT INTO ' + @SHARESERVER + @SHAREDB +'.DBO.POBANK (BANK_NAME,BRANCH_NAME)'      
 SET @STRSQL = @STRSQL + ' SELECT DISTINCT BANK_NAME, BRANCH_NAME '      
 SET @STRSQL = @STRSQL + ' FROM #MIG_CITRUS_MULTIBANK  C'      
 SET @STRSQL = @STRSQL + ' WHERE NOT EXISTS (SELECT BANK_NAME FROM POBANK'      
 SET @STRSQL = @STRSQL + ' WHERE POBANK.BANK_NAME = C.BANK_NAME AND POBANK.BRANCH_NAME = C.BRANCH_NAME)'      
 EXEC (@STRSQL)       
 */      
      
-- SET @STRSQL = ' INSERT INTO ' + @ACCOUNTSERVER + @ACCOUNTDB + '.DBO.MULTIBANKID(CLTCODE,BANKID, ACCNO, ACCTYPE, CHEQUENAME, DEFAULTBANK,IFSCCODE)'      
-- SET @STRSQL = @STRSQL + ' SELECT PARTY_CODE,P.BANKID,AC_NO,AC_TYPE,AC_NAME, DEF,IFSC_CD'      
-- SET @STRSQL = @STRSQL + ' FROM #MIG_CITRUS_MULTIBANK M (NOLOCK) , '+ @SHARESERVER + @SHAREDB +'.DBO.POBANK P (NOLOCK)'      
-- SET @STRSQL = @STRSQL + ' WHERE P.BANK_NAME = M.BANK_NAME AND P.BRANCH_NAME = M.BRANCH_NAME'      
-- SET @STRSQL = @STRSQL + ' AND NOT EXISTS (SELECT CLTCODE FROM  ' + @ACCOUNTSERVER + @ACCOUNTDB + '.DBO.MULTIBANKID A WHERE A.CLTCODE = PARTY_CODE '      
-- SET @STRSQL = @STRSQL + '      AND A.BANKID = P.BANKID AND A.ACCNO = M.AC_NO)'      
--      
-- EXEC (@STRSQL)      

 SET @STRSQL =  'SELECT M.* INTO #MIG_CITRUS_MULTIBANK  '
 SET @STRSQL = @STRSQL + ' FROM  '+ @SHARESERVER + @SHAREDB + '.DBO.CLIENT5 ,#MIG_CITRUS_MULTIBANK_TMP M WITH (NOLOCK)'
 SET @STRSQL = @STRSQL + ' WHERE M.PARTY_CODE=CL_CODE '

	
 SET @STRSQL = @STRSQL + ' IF (SELECT COUNT(1) FROM #MIG_CITRUS_MULTIBANK) > 0'
 SET @STRSQL = @STRSQL + ' BEGIN'
 SET @STRSQL = @STRSQL + ' INSERT INTO '+ @SHARESERVER + @SHAREDB + '.DBO.POBANK (BANK_NAME,BRANCH_NAME)'
 SET @STRSQL = @STRSQL + ' SELECT DISTINCT BANK_NAME=LEFT(ISNULL(BANK_NAME, ''''),50), BRANCH_NAME=LEFT(ISNULL(BRANCH_NAME, ''''),40)'
 SET @STRSQL = @STRSQL + ' FROM #MIG_CITRUS_MULTIBANK M WITH (NOLOCK)'
 SET @STRSQL = @STRSQL + ' WHERE NOT EXISTS (SELECT BANK_NAME, BRANCH_NAME FROM '+ @SHARESERVER + @SHAREDB + '.DBO.POBANK WITH (NOLOCK) WHERE M.BANK_NAME = BANK_NAME AND M.BRANCH_NAME = BRANCH_NAME)'
	
 SET @STRSQL = @STRSQL + ' SELECT PARTY_CODE,BANKID = MAX(P.BANKID),AC_NO,AC_TYPE,AC_NAME, DEF'      
 SET @STRSQL = @STRSQL + ' INTO #MULTIBANKID_ACC '      
 SET @STRSQL = @STRSQL + ' FROM #MIG_CITRUS_MULTIBANK M (NOLOCK) , '+ @SHARESERVER + @SHAREDB + '.DBO.POBANK P (NOLOCK)'      
 SET @STRSQL = @STRSQL + ' WHERE P.BANK_NAME = M.BANK_NAME AND P.BRANCH_NAME = M.BRANCH_NAME'      
 SET @STRSQL = @STRSQL + ' AND NOT EXISTS (SELECT CLTCODE FROM  ' + @ACCOUNTSERVER +  @ACCOUNTDB + '.DBO.MULTIBANKID A WHERE A.CLTCODE = PARTY_CODE '      
 SET @STRSQL = @STRSQL + '      AND A.BANKID = CONVERT(VARCHAR ,P.BANKID) AND A.ACCNO = M.AC_NO)'      
 SET @STRSQL = @STRSQL + ' GROUP BY PARTY_CODE,AC_NO,AC_TYPE,AC_NAME, DEF '      
      
 --SET @STRSQL = @STRSQL + ' INSERT INTO ' + @ACCOUNTSERVER +  @ACCOUNTDB + '.DBO.MULTIBANKID_LOG(CLTCODE,BANKID, ACCNO, ACCTYPE, CHEQUENAME, DEFAULTBANK)'      
 --SET @STRSQL = @STRSQL + ' SELECT * FROM #MULTIBANKID_ACC '      
     
 SET @STRSQL = @STRSQL + ' INSERT INTO ' + @ACCOUNTSERVER +  @ACCOUNTDB + '.DBO.MULTIBANKID(CLTCODE,BANKID, ACCNO, ACCTYPE, CHEQUENAME, DEFAULTBANK)'      
 SET @STRSQL = @STRSQL + ' SELECT * FROM #MULTIBANKID_ACC '      
       
 --SET @STRSQL = @STRSQL + ' SELECT * INTO MIG_CITRUS_MULTIBANK_SRUESH1 FROM #MULTIBANKID_ACC '      
       
 
 --PRINT (@STRSQL)      
 --EXEC (@STRSQL)      
      
 SET @STRSQL = @STRSQL +'  UPDATE ' + @ACCOUNTSERVER + @ACCOUNTDB + '.DBO.MULTIBANKID SET DEFAULTBANK = 0'      
 SET @STRSQL = @STRSQL + ' FROM #MIG_CITRUS_MULTIBANK_TMP T WHERE CLTCODE =PARTY_CODE '
 SET @STRSQL = @STRSQL + ' AND EXISTS (SELECT PARTY_CODE FROM #MULTIBANKID_ACC T1 WHERE T.PARTY_CODE = T1.PARTY_CODE AND DEF = 1) '
      
 --EXEC (@STRSQL)       
        
 SET @STRSQL = @STRSQL +'  UPDATE M'      
 SET @STRSQL = @STRSQL + ' SET DEFAULTBANK = 1'      
 SET @STRSQL = @STRSQL + ' FROM #MIG_CITRUS_MULTIBANK_TMP A,'      
 SET @STRSQL = @STRSQL + ' ' + @ACCOUNTSERVER +  @ACCOUNTDB + '.DBO.MULTIBANKID M,'      
 SET @STRSQL = @STRSQL + ' '+ @SHARESERVER + @SHAREDB +'.DBO.POBANK P (NOLOCK)'      
 SET @STRSQL = @STRSQL + ' WHERE P.BANK_NAME = A.BANK_NAME AND P.BRANCH_NAME = A.BRANCH_NAME'      
 SET @STRSQL = @STRSQL + ' AND DEF = 1 AND M.CLTCODE = A.PARTY_CODE AND A.AC_NO = M.ACCNO /*AND M.BANKID=P.BANKID*/' 

 SET @STRSQL = @STRSQL + ' DROP TABLE #MULTIBANKID_ACC ' 
 
 SET @STRSQL = @STRSQL + ' END'   
    

 SET @STRSQL = @STRSQL + ' DROP TABLE #MIG_CITRUS_MULTIBANK '      
-- print @STRSQL      
 EXEC (@STRSQL)      
       
 FETCH NEXT FROM @EXCHANGEWISE_CURSOR INTO @SHAREDB,@SHARESERVER,@ACCOUNTDB,@ACCOUNTSERVER      
END      
CLOSE @EXCHANGEWISE_CURSOR      
DEALLOCATE @EXCHANGEWISE_CURSOR       
      
      
      
/*---------------------------------- MFSS -------------------------------*/      
IF (SELECT COUNT(1) FROM ANGELFO.BSEMFSS.DBO.MFSS_CLIENT WHERE PARTY_CODE= @PARTY_CODE) > 0  --AND 1 = 2       
BEGIN      
 SET @EXCHANGEWISE_CURSOR = CURSOR      
 FOR      
 SELECT DISTINCT SHAREDB,SHARESERVER,ACCOUNTDB,ACCOUNTSERVER      
 FROM PRADNYA..MULTICOMPANY_ALL M(NOLOCK)      
 WHERE PRIMARYSERVER=1      
      
 OPEN @EXCHANGEWISE_CURSOR      
      
 FETCH NEXT FROM @EXCHANGEWISE_CURSOR INTO @SHAREDB,@SHARESERVER,@ACCOUNTDB,@ACCOUNTSERVER      
        
 WHILE @@FETCH_STATUS = 0      
 BEGIN      
  SET @STRSQL = ''      
  IF @SHARESERVER = @@SERVERNAME       
  BEGIN      
   SET @SHARESERVER =''      
   SET @ACCOUNTSERVER ='' 
   SET @SHAREDB =''  
  END      
  ELSE      
  BEGIN   
   SET @SHARESERVER = @SHARESERVER + '.'      
   SET @ACCOUNTSERVER = @ACCOUNTSERVER + '.'      
   SET @SHAREDB = @SHAREDB + '.'      
  END      
        
  /*      
  SET @STRSQL = 'INSERT INTO ' + @SHARESERVER + @SHAREDB +'.DBO.POBANK (BANK_NAME,BRANCH_NAME)'      
  SET @STRSQL = @STRSQL + ' SELECT DISTINCT BANK_NAME, BRANCH_NAME '      
  SET @STRSQL = @STRSQL + ' FROM #MIG_CITRUS_MULTIBANK  C'      
  SET @STRSQL = @STRSQL + ' WHERE NOT EXISTS (SELECT BANK_NAME FROM POBANK'      
  SET @STRSQL = @STRSQL + ' WHERE POBANK.BANK_NAME = C.BANK_NAME AND POBANK.BRANCH_NAME = C.BRANCH_NAME)'      
  EXEC (@STRSQL)       
  */      
      
--  SET @STRSQL = ' INSERT INTO ' + @ACCOUNTSERVER + @ACCOUNTDB + '.DBO.MULTIBANKID(CLTCODE,BANKID, ACCNO, ACCTYPE, CHEQUENAME, DEFAULTBANK,EXCHANGE,SEGMENT)'      
--  SET @STRSQL = @STRSQL + ' SELECT PARTY_CODE,P.BANKID,AC_NO,CASE WHEN AC_TYPE =''SAVING'' THEN ''SB'' ELSE ''CB'' END,AC_NAME, DEF,'''+ LEFT(@SHAREDB,3) + ''',''MFSS'''      
--  SET @STRSQL = @STRSQL + ' FROM #MIG_CITRUS_MULTIBANK M (NOLOCK) , MSAJAG.DBO.POBANK P (NOLOCK)'      
--  SET @STRSQL = @STRSQL + ' WHERE P.BANK_NAME = M.BANK_NAME AND P.BRANCH_NAME = M.BRANCH_NAME'      
--  SET @STRSQL = @STRSQL + ' AND NOT EXISTS (SELECT CLTCODE FROM  ' + @ACCOUNTSERVER + @ACCOUNTDB + '.DBO.MULTIBANKID A WHERE A.CLTCODE = PARTY_CODE '      
--  SET @STRSQL = @STRSQL + '      AND A.BANKID = P.BANKID AND A.ACCNO = M.AC_NO)'      
--      
--  EXEC (@STRSQL)      
      
  SET @STRSQL =  ' SELECT PARTY_CODE,BANKID=MAX(P.BANKID),AC_NO,AC_TYPE = CASE WHEN AC_TYPE =''SAVING'' THEN ''SB'' ELSE ''CB'' END,AC_NAME, DEF, EXCAHNGE = '''+ LEFT(@SHAREDB,3) + ''',SEGMENT = ''MFSS'''      
  SET @STRSQL = @STRSQL + ' INTO #MF_MULTIBANKID '      
  SET @STRSQL = @STRSQL + ' FROM #MIG_CITRUS_MULTIBANK_TMP M (NOLOCK) ,'+ @SHARESERVER + @SHAREDB +'DBO.POBANK P (NOLOCK)'      
  SET @STRSQL = @STRSQL + ' WHERE P.BANK_NAME = M.BANK_NAME AND P.BRANCH_NAME = M.BRANCH_NAME'      
  SET @STRSQL = @STRSQL + ' AND NOT EXISTS (SELECT CLTCODE FROM  ' + @ACCOUNTSERVER + @ACCOUNTDB + '.DBO.MULTIBANKID A WHERE A.CLTCODE = PARTY_CODE '      
  SET @STRSQL = @STRSQL + '      /*AND A.BANKID =  CONVERT(VARCHAR,BANKID)*/ AND A.ACCNO = AC_NO)'      
  SET @STRSQL = @STRSQL + ' GROUP BY PARTY_CODE,AC_NO,CASE WHEN AC_TYPE =''SAVING'' THEN ''SB'' ELSE ''CB'' END,AC_NAME, DEF '      
   print @STRSQL
  -- SET @STRSQL = @STRSQL + ' INSERT INTO ' + @ACCOUNTSERVER + @ACCOUNTDB + '.DBO.MULTIBANKID_LOG(CLTCODE,BANKID, ACCNO, ACCTYPE, CHEQUENAME, DEFAULTBANK,EXCHANGE,SEGMENT)'      
  --SET @STRSQL = @STRSQL + ' SELECT * FROM #MF_MULTIBANKID B '  
  
        
  SET @STRSQL = @STRSQL + ' INSERT INTO ' + @ACCOUNTSERVER + @ACCOUNTDB + '.DBO.MULTIBANKID(CLTCODE,BANKID, ACCNO, ACCTYPE, CHEQUENAME, DEFAULTBANK,EXCHANGE,SEGMENT)'      
  SET @STRSQL = @STRSQL + ' SELECT * FROM #MF_MULTIBANKID B '     
  PRINT    @STRSQL     
    SET @STRSQL = @STRSQL + ' SELECT * FROM ' + @ACCOUNTSERVER + @ACCOUNTDB + '.DBO.#MF_MULTIBANKID B '  
    --PRINT    @STRSQL   
   
      
      
          
  SET @STRSQL = @STRSQL + ' DROP TABLE  #MF_MULTIBANKID'        
        
  PRINT @STRSQL      
  EXEC (@STRSQL)      
        
  /*  SET @STRSQL = 'UPDATE ' + @ACCOUNTSERVER + @ACCOUNTDB + '.DBO.MULTIBANKID SET DEFAULTBANK = 0'      
  SET @STRSQL = @STRSQL + ' WHERE CLTCODE = ''' + @PARTY_CODE  + ''''      
      
  
         
  SET @STRSQL = 'UPDATE M'      
  SET @STRSQL = @STRSQL + ' SET DEFAULTBANK = 1'      
  SET @STRSQL = @STRSQL + ' FROM #MIG_CITRUS_MULTIBANK_TMP A,'      
  SET @STRSQL = @STRSQL + ' ' + @ACCOUNTSERVER +  @ACCOUNTDB + '.DBO.MULTIBANKID M'      
  SET @STRSQL = @STRSQL + ' WHERE DEF = 1 AND M.CLTCODE = A.PARTY_CODE AND A.AC_NO = M.ACCNO /*AND A.BANM_ID = M.BANKID*/' 
  */
  
    SET @STRSQL = 'UPDATE M'      
  SET @STRSQL = @STRSQL + ' SET DEFAULTBANK = 0'      
  SET @STRSQL = @STRSQL + ' FROM #MIG_CITRUS_MULTIBANK_TMP A,'      
  SET @STRSQL = @STRSQL + ' ' + @ACCOUNTSERVER +  @ACCOUNTDB + '.DBO.MULTIBANKID M'      
  SET @STRSQL = @STRSQL + ' WHERE  M.CLTCODE = A.PARTY_CODE' 
  print   @STRSQL
  
    SET @STRSQL = 'UPDATE M'      
  SET @STRSQL = @STRSQL + ' SET DEFAULTBANK = 1'      
  SET @STRSQL = @STRSQL + ' FROM #MIG_CITRUS_MULTIBANK_TMP A,'      
  SET @STRSQL = @STRSQL + ' ' + @ACCOUNTSERVER +  @ACCOUNTDB + '.DBO.MULTIBANKID M'      
  SET @STRSQL = @STRSQL + ' WHERE DEF = 1 AND M.CLTCODE = A.PARTY_CODE AND A.AC_NO = M.ACCNO /*AND A.BANM_ID = M.BANKID*/'   
  PRINT @STRSQL      
  EXEC (@STRSQL)      
      
  SET @STRSQL = 'UPDATE M SET BANK_NAME = C.BANK_NAME, BANK_BRANCH = C.BRANCH_NAME, BANK_CITY = C.BRANCH_NAME, ACC_NO = AC_NO, MICR_NO = MICR'      
  SET @STRSQL = @STRSQL + ' FROM ' + @SHARESERVER + @SHAREDB + 'DBO.MFSS_CLIENT M, #MIG_CITRUS_MULTIBANK_TMP C '      
  SET @STRSQL = @STRSQL + 'WHERE M.PARTY_CODE = C.PARTY_CODE AND M.PARTY_CODE = ''' + @PARTY_CODE  + ''' AND DEF = 1'      
      
PRINT @STRSQL      
  EXEC (@STRSQL)      
        
  FETCH NEXT FROM @EXCHANGEWISE_CURSOR INTO @SHAREDB,@SHARESERVER,@ACCOUNTDB,@ACCOUNTSERVER      
 END      
 CLOSE @EXCHANGEWISE_CURSOR      
 DEALLOCATE @EXCHANGEWISE_CURSOR       
 END      

	UPDATE C
	SET UPD_FLAG = 'Y', UPD_DT = GETDATE()
	FROM [172.31.16.57].CRMDB_A.DBO.CLIENT_DP_BANK_MIG C INNER JOIN  #MIG_CITRUS_MULTIBANK_TMP M ON C.PARTY_CODE=M.PARTY_CODE
	AND UPD_FLAG = 'N'
	AND MOD3 NOT LIKE '%DP%'
 
      
DROP TABLE #MIG_CITRUS_MULTIBANK_TMP      
/*------------------------- END OF THE PROC -----------------------*/

GO
