-- Object: PROCEDURE dbo.TEST_Date
-- Server: 10.253.33.91 | DB: MSAJAG
--------------------------------------------------

CREATE PROCEDuRE TEST_Date
(
@MARGINDATE VARCHAR(11)
)
AS
SELECT *
  FROM V2_TBL_EXCHANGE_MARGIN_REPORT_PEAK P,TBL_COMBINE_REPORTING_PEAK_DETAIL
  WHERE MARGINDATE = @MARGINDATE  
  AND TBL_COMBINE_REPORTING_PEAK_DETAIL.EXCHANGE = P.EXCHANGE 
  AND TBL_COMBINE_REPORTING_PEAK_DETAIL.SEGMENT = P.SEGMENT 
  AND PEAK_PER > 0

GO
