-- Object: PROCEDURE dbo.CLS_CREATE_LINK
-- Server: 10.253.33.91 | DB: MSAJAG
--------------------------------------------------




/*
EXEC CLS_CREATE_LINK
COMMIT
*/

CREATE PROC [dbo].[CLS_CREATE_LINK]
AS
BEGIN

DECLARE @Fldcategorycode VARCHAR(50)
DECLARE @Fldadminauto INT

IF NOT EXISTS 
(
	SELECT Fldcategoryname FROM TBLCATEGORY WHERE Fldcategoryname = 'ALL_CP'
)
BEGIN
		
	SELECT ' ALERT : NOT FOUND [ALL_CP] CATEGORY IN TBLCATEGORY TABLE ' AS [RESULT]

	RETURN 
END 
ELSE 
BEGIN
		SELECT @Fldcategorycode = Fldcategorycode , @Fldadminauto = Fldadminauto FROM TBLCATEGORY WHERE Fldcategoryname = 'ALL_CP'
END 

IF NOT EXISTS 
(
	SELECT FLDUSERNAME FROM TBLPRADNYAUSERS WHERE FLDUSERNAME = 'CLASSUSER'
)
BEGIN
		
	SELECT ' ALERT : NOT FOUND [CLASSUSER] USER IN TBLPRADNYAUSERS TABLE ' AS [RESULT]

	RETURN 
END 
--ELSE 
--BEGIN
--		SELECT @Fldcategorycode = Fldcategorycode , @Fldadminauto = Fldadminauto FROM TBLCATEGORY WHERE Fldcategoryname = 'ALL_CP'
--END 

CREATE TABLE #TEMP_TBLMENUHEAD
(
FLDMENUCODE	VARCHAR(20),
FLDMENUNAME VARCHAR(20),
REPORTID INT
)

BEGIN TRY
BEGIN TRAN

INSERT INTO #TEMP_TBLMENUHEAD
SELECT A.Fldmenucode, Fldmenuname , MIN(ISNULL(Fldreportgrp,7)) AS Fldreportgrp
FROM TBLMENUHEAD A
		INNER JOIN TBLREPORTGRP B
		ON A.Fldmenucode = B.Fldmenugrp 
GROUP BY A.Fldmenucode,Fldmenuname


CREATE TABLE #TEMP_TBLREPORTS
(
	FLDREPORTNAME VARCHAR(60),
	FLDPATH VARCHAR(500),
	FLDTARGET VARCHAR(25),
	FLDDESC VARCHAR(80),
	FLDREPORTGRP VARCHAR(10),
	FLDMENUGRP VARCHAR(3),
	FLDSTATUS VARCHAR(20),
	FLDORDER INT,
	MENUGRP VARCHAR(100),
	REPORTGRP VARCHAR(100)
)

SELECT SRNO,FLDREPORTPATH, ROW_NUMBER() OVER (PARTITION BY FLDREPORTPATH ORDER BY FLDREPORTPATH) AS CNT
INTO #DUP_CLS_TBLREPORTS
FROM CLS_TBLREPORTS

DELETE A
FROM CLS_TBLREPORTS A
	INNER JOIN #DUP_CLS_TBLREPORTS  B
		ON A.SRNO = B.SRNO
WHERE CNT > 1
--select * from tblmenuhead
INSERT INTO #TEMP_TBLREPORTS
(FLDREPORTNAME,FLDDESC,FLDPATH,FLDTARGET,FLDSTATUS,FLDORDER,MENUGRP,REPORTGRP)
SELECT FLDREPORTCODE, FLDREMARK,  FLDREPORTPATH, 'fraTopic','ALL',0, 
CASE WHEN UPPER(REPLACE(.DBO.CLS_PIECE(FLDREPORTPATH, '/', 1),'_',' ')) = 'SHARE TRANSACTION' THEN 'SHARE TRANSACTION'
	WHEN UPPER(REPLACE(.DBO.CLS_PIECE(FLDREPORTPATH, '/', 1),'_',' ')) = 'FINANCE TRANSACTION' THEN 'FINANCE TRANSACTION'
	WHEN UPPER(REPLACE(.DBO.CLS_PIECE(FLDREPORTPATH, '/', 1),'_',' ')) = 'FINANCE REPORT' THEN 'FINANCE REPORT'
	WHEN UPPER(REPLACE(.DBO.CLS_PIECE(FLDREPORTPATH, '/', 1),'_',' ')) = 'SHARE REPORTS' THEN 'SHARE REPORT'
	WHEN UPPER(REPLACE(.DBO.CLS_PIECE(FLDREPORTPATH, '/', 1),'_',' ')) = 'UTILITY' THEN 'UTILITY'
	WHEN UPPER(REPLACE(.DBO.CLS_PIECE(FLDREPORTPATH, '/', 1),'_',' ')) = 'SHARE MASTER' THEN 'SHARE MASTER'
	WHEN UPPER(REPLACE(.DBO.CLS_PIECE(FLDREPORTPATH, '/', 1),'_',' ')) = 'FINANCE MASTER' THEN 'FINANCE MASTER'
	WHEN UPPER(REPLACE(.DBO.CLS_PIECE('BLOCK PAN.HTML', '.', 2),'_',' ')) = 'HTML' THEN 'SHARE REPORT'
ELSE 'UTILITY'
END, 
CASE
	 WHEN (.DBO.CLS_PIECE(FLDREPORTPATH, '/', 1)  = 'SHARE_MASTER' AND .DBO.CLS_PIECE(FLDREPORTPATH, '/', 2) = 'COLLATERAL') THEN 'COLLATERAL MASTERS' 
	 WHEN (.DBO.CLS_PIECE(FLDREPORTPATH, '/', 1)  = 'SHARE_MASTER' AND .DBO.CLS_PIECE(FLDREPORTPATH, '/', 2) = 'EQUITY') THEN 'MASTERS' 
	 WHEN (.DBO.CLS_PIECE(FLDREPORTPATH, '/', 1)  = 'SHARE_MASTER' AND .DBO.CLS_PIECE(FLDREPORTPATH, '/', 3) = 'VBB') THEN 'BROKERAGE' 
	 --WHEN .DBO.CLS_PIECE(FLDREPORTPATH, '/', 1)  = 'SHARE_MASTER' THEN 'MASTERS' 
	 WHEN .DBO.CLS_PIECE(FLDREPORTPATH, '/', 1)  = 'FINANCE_REPORT' THEN 'DAILY REPORTS' 
	 WHEN (.DBO.CLS_PIECE(FLDREPORTPATH, '/', 1)  = 'SHARE_REPORTS' AND .DBO.CLS_PIECE(FLDREPORTPATH, '/', 2) = 'OTHER_REPORT') THEN 'OTHER_REPORTS' 
	 WHEN (.DBO.CLS_PIECE(FLDREPORTPATH, '/', 1)  = 'SHARE_REPORTS' AND .DBO.CLS_PIECE(FLDREPORTPATH, '/', 2) = 'EQUITY') THEN 'SETTLEMENT_REPORTS' 
	 WHEN (.DBO.CLS_PIECE(FLDREPORTPATH, '/', 1)  = 'SHARE_REPORTS' AND .DBO.CLS_PIECE(FLDREPORTPATH, '/', 2) = 'DERIVATIVE') THEN 'DELIVERY_REPORTS' 
	 --WHEN .DBO.CLS_PIECE(FLDREPORTPATH, '/', 1)  = 'SHARE_REPORTS' THEN 'NEW_REPORTS' 
	 WHEN (.DBO.CLS_PIECE(FLDREPORTPATH, '/', 1)  = 'SHARE_TRANSACTION' AND .DBO.CLS_PIECE(FLDREPORTPATH, '/', 3) = 'CM_PROCESS') THEN 'DELIVERY_IMPORT' 
	 WHEN (.DBO.CLS_PIECE(FLDREPORTPATH, '/', 1)  = 'SHARE_TRANSACTION' AND .DBO.CLS_PIECE(FLDREPORTPATH, '/', 3) = 'DELIVERY_PROCESS') THEN 'DELIVERY_PROCESS'
	 WHEN (.DBO.CLS_PIECE(FLDREPORTPATH, '/', 1)  = 'SHARE_TRANSACTION' AND .DBO.CLS_PIECE(FLDREPORTPATH, '/', 2) = 'DERIVATIVE') THEN 'DERIVATIES'
	 WHEN (.DBO.CLS_PIECE(FLDREPORTPATH, '/', 1)  = 'SHARE_TRANSACTION' AND .DBO.CLS_PIECE(FLDREPORTPATH, '/', 2) = 'EQUITY' AND ISNULL(.DBO.CLS_PIECE(FLDREPORTPATH, '/', 3),'') = '') THEN 'DAILY' 

	 --WHEN .DBO.CLS_PIECE(FLDREPORTPATH, '/', 1)  = 'SHARE_TRANSACTION' THEN 'DAILY' 
	 WHEN (.DBO.CLS_PIECE(FLDREPORTPATH, '/', 1)  = 'FINANCE_TRANSACTION' AND .DBO.CLS_PIECE(FLDREPORTPATH, '/', 2) = 'BANK_RECONCILIATION') THEN 'BANK RECONCILIATION'
	 WHEN (.DBO.CLS_PIECE(FLDREPORTPATH, '/', 1)  = 'FINANCE_TRANSACTION' AND .DBO.CLS_PIECE(FLDREPORTPATH, '/', 2) = 'VOUCHER_ENTRY') THEN 'VOUCHER ENTRY MODULE'
	 WHEN (.DBO.CLS_PIECE(FLDREPORTPATH, '/', 1)  = 'FINANCE_TRANSACTION' AND .DBO.CLS_PIECE(FLDREPORTPATH, '/', 2) = 'INTEREST MODULE') THEN 'MONEY PAYOUT'
	 WHEN (.DBO.CLS_PIECE(FLDREPORTPATH, '/', 1)  = 'FINANCE_TRANSACTION' AND .DBO.CLS_PIECE(FLDREPORTPATH, '/', 2) = 'MONEY_PAYOUT') THEN 'MONEY PAYOUT'
	 WHEN (.DBO.CLS_PIECE(FLDREPORTPATH, '/', 1)  = 'FINANCE_TRANSACTION' AND .DBO.CLS_PIECE(FLDREPORTPATH, '/', 2) = 'FILE_UPLOAD') THEN 'FILE UPLOAD'
	WHEN (.DBO.CLS_PIECE(FLDREPORTPATH, '/', 1)  = 'FINANCE_TRANSACTION' AND .DBO.CLS_PIECE(FLDREPORTPATH, '/', 2) = 'ATOM') THEN 'VOUCHER ENTRY MODULE'
	 WHEN (.DBO.CLS_PIECE(FLDREPORTPATH, '/', 1)  = 'FINANCE_TRANSACTION' AND .DBO.CLS_PIECE(FLDREPORTPATH, '/', 2) = 'CMS') THEN 'CMS'

	 --WHEN .DBO.CLS_PIECE(FLDREPORTPATH, '/', 1)  = 'FINANCE_TRANSACTION' THEN 'BANK_TRANSACTIONS' 
	 WHEN .DBO.CLS_PIECE(FLDREPORTPATH, '/', 1)  = 'FINANCE_MASTER' THEN 'ACCOUNT_MASTERS' 

	 WHEN .DBO.CLS_PIECE(FLDREPORTPATH, '/', 1)  = 'Utility' THEN 'UTILITIES_SERVICES' 
ELSE 'UTILITY'	
	 
	 

END
FROM CLS_TBLREPORTS
WHERE FLDREPORTPATH NOT IN (SELECT FLDPATH FROM Tblreports)
	AND FLDREPORTPATH NOT LIKE 'LOGIN/%'
	UPDATE T SET FLDREPORTGRP = 34 from #TEMP_TBLREPORTS T WHERE isnull(t.FLDREPORTGRP,'') = '' 
	UPDATE T SET FLDMENUGRP = MH.Fldmenucode from  #TEMP_TBLREPORTS T, TBLMENUHEAD MH where T.MENUGRP = MH.Fldmenuname
	UPDATE T SET FLDREPORTGRP = MH.Fldreportgrp from  #TEMP_TBLREPORTS T, TBLREPORTGRP MH where T.REPORTGRP = MH.Fldgrpname
	select * from #TEMP_TBLREPORTS
IF EXISTS (
				SELECT MENUGRP FROM #Temp_TBLREPORTS 
				WHERE MENUGRP NOT IN (SELECT Fldmenuname FROM #TEMP_TBLMENUHEAD ) 
		 )
BEGIN

	 SELECT ' ALERT : BELOW GROUP NAME NOT EXISTS IN TBLMENUHEAD TABLE ' AS [RESULT]
	 UNION ALL
	 SELECT  MENUGRP 
	 FROM #Temp_TBLREPORTS 
	 WHERE MENUGRP NOT IN (SELECT Fldmenuname FROM #TEMP_TBLMENUHEAD ) 

	 RETURN
END 		 	
	



--UPDATE A
--SET A.FLDMENUGRP  = B.Fldmenucode,A.FLDREPORTGRP  = B.REPORTID--, Fldorder =  (SELECT ROW_NUMBER() OVER (PARTITION BY A.FLDMENUGRP ORDER BY A.FLDMENUGRP ))
--FROM #TEMP_TBLREPORTS A
--		INNER JOIN #TEMP_TBLMENUHEAD B
--		ON A.MENUGRP =B.Fldmenuname

--UPDATE #TEMP_TBLREPORTS 
--SET FLDMENUGRP  =  (SELECT ROW_NUMBER() OVER (PARTITION BY FLDMENUGRP ORDER BY FLDPATH ) FROM #TEMP_TBLREPORTS)

INSERT INTO TBLREPORTS
SELECT FLDREPORTNAME,FLDPATH,FLDTARGET,FLDDESC,FLDREPORTGRP,FLDMENUGRP,FLDSTATUS,FLDORDER
FROM #Temp_TBLREPORTS
WHERE FLDREPORTGRP	IS NOT NULL AND FLDMENUGRP IS NOT NULL


INSERT INTO TBLCATMENU
SELECT A.Fldreportcode, @Fldadminauto, ',' + @Fldcategorycode + ','
FROM TBLREPORTS A
		INNER JOIN 	#Temp_TBLREPORTS B
		ON A.FLDREPORTNAME = B.FLDREPORTNAME
WHERE A.Fldreportcode NOT IN (SELECT Fldreportcode FROM Tblcatmenu)

SELECT 'PROCESS DONE.' AS [RESULT]

COMMIT 
END TRY
BEGIN CATCH

	SELECT 'ERROR IS : ' + ERROR_MESSAGE() AS [RESULT]
	ROLLBACK 

END CATCH

DROP TABLE #Temp_TBLREPORTS
DROP TABLE #TEMP_TBLMENUHEAD
END

GO
