-- Object: PROCEDURE dbo.V2_ClientMaster_CleanUp
-- Server: 10.253.33.91 | DB: MSAJAG
--------------------------------------------------

CREATE Proc V2_ClientMaster_CleanUp

as

----------------------------------------------------------------------------------------------------------------------
-- PROC 1
----------------------------------------------------------------------------------------------------------------------


Update 
	Client_Details_Uppili
Set
	Region = R1.RegionCode
From 
	Region R1
Where
	Client_Details_Uppili.Branch_cd = r1.Branch_Code
and 
	Client_Details_Uppili.Party_Code in
		(
			Select 
				party_Code
			from
				Region R
			right outer join
				Client_Details_Uppili Du
			on	(
				du.Branch_cd = r.Branch_Code
			and
				du.region = r.regioncode
				)
			Where isnull(du.region,'') = ''
		)	


----------------------------------------------------------------------------------------------------------------------
-- PROC 2
----------------------------------------------------------------------------------------------------------------------

Update Client_Details_Uppili Set L_State = 'ANDHRA PRADESH' Where L_State = 'A P'
Update Client_Details_Uppili Set L_State = 'ANDHRA PRADESH' Where L_State = 'A.P.'
Update Client_Details_Uppili Set L_State = 'ANDHRA PRADESH' Where L_State = 'ADNDHRA PRADESH'
Update Client_Details_Uppili Set L_State = 'ANDHRA PRADESH' Where L_State = 'AHDHRA PRADESH'
Update Client_Details_Uppili Set L_State = 'ANDHRA PRADESH' Where L_State = 'AHDRA PRADESH'
Update Client_Details_Uppili Set L_State = 'ANDHRA PRADESH' Where L_State = 'AHNDRA PRADESH'
Update Client_Details_Uppili Set L_State = 'ANDHRA PRADESH' Where L_State = 'ANADRA PRADESH'
Update Client_Details_Uppili Set L_State = 'ANDHRA PRADESH' Where L_State = 'ANDHARA PARDESH'
Update Client_Details_Uppili Set L_State = 'ANDHRA PRADESH' Where L_State = 'ANDHARA PRADESH'
Update Client_Details_Uppili Set L_State = 'ANDHRA PRADESH' Where L_State = 'ANDHARAPRADESH'
Update Client_Details_Uppili Set L_State = 'ANDHRA PRADESH' Where L_State = 'ANDHERA PRADEHS'
Update Client_Details_Uppili Set L_State = 'ANDHRA PRADESH' Where L_State = 'ANDHERA PRADESH'
Update Client_Details_Uppili Set L_State = 'ANDHRA PRADESH' Where L_State = 'ANDHERAPRADESH'
Update Client_Details_Uppili Set L_State = 'ANDHRA PRADESH' Where L_State = 'ANDHR PRADESH'
Update Client_Details_Uppili Set L_State = 'ANDHRA PRADESH' Where L_State = 'ANDHRA  PRADESH'
Update Client_Details_Uppili Set L_State = 'ANDHRA PRADESH' Where L_State = 'ANDHRA -PRADESH'
Update Client_Details_Uppili Set L_State = 'ANDHRA PRADESH' Where L_State = 'ANDHRA PARADESH'
Update Client_Details_Uppili Set L_State = 'ANDHRA PRADESH' Where L_State = 'ANDHRA PARDESH'
Update Client_Details_Uppili Set L_State = 'ANDHRA PRADESH' Where L_State = 'ANDHRA PERDESH'
Update Client_Details_Uppili Set L_State = 'ANDHRA PRADESH' Where L_State = 'ANDHRA PRADESHQ'
Update Client_Details_Uppili Set L_State = 'ANDHRA PRADESH' Where L_State = 'ANDHRA PRASDESH'
Update Client_Details_Uppili Set L_State = 'ANDHRA PRADESH' Where L_State = 'ANDHRA PRDESH'
Update Client_Details_Uppili Set L_State = 'ANDHRA PRADESH' Where L_State = 'ANDHRA RADESH'
Update Client_Details_Uppili Set L_State = 'ANDHRA PRADESH' Where L_State = 'ANDHRA RPRADESH'
Update Client_Details_Uppili Set L_State = 'ANDHRA PRADESH' Where L_State = 'ANDHRA-PRADESH'
Update Client_Details_Uppili Set L_State = 'ANDHRA PRADESH' Where L_State = 'ANDHRAPRADEH'
Update Client_Details_Uppili Set L_State = 'ANDHRA PRADESH' Where L_State = 'ANDHRAPRADESH'
Update Client_Details_Uppili Set L_State = 'ANDHRA PRADESH' Where L_State = 'ANDHRAPRDASH'
Update Client_Details_Uppili Set L_State = 'ANDHRA PRADESH' Where L_State = 'ANDHRAPRDESH'
Update Client_Details_Uppili Set L_State = 'ANDHRA PRADESH' Where L_State = 'ANDHRAPUR'
Update Client_Details_Uppili Set L_State = 'ANDHRA PRADESH' Where L_State = 'ANDHYA PRADESH'
Update Client_Details_Uppili Set L_State = 'ANDHRA PRADESH' Where L_State = 'ANDRA PRADESH'
Update Client_Details_Uppili Set L_State = 'ANDHRA PRADESH' Where L_State = 'ANDRA-PRADESH'
Update Client_Details_Uppili Set L_State = 'ANDHRA PRADESH' Where L_State = 'ANDRAH PRADESH'
Update Client_Details_Uppili Set L_State = 'ANDHRA PRADESH' Where L_State = 'ANDRAPRADEASH'
Update Client_Details_Uppili Set L_State = 'ANDHRA PRADESH' Where L_State = 'ANDRAPRADESH'
Update Client_Details_Uppili Set L_State = 'ANDHRA PRADESH' Where L_State = 'ANHDRA PRADESH'
Update Client_Details_Uppili Set L_State = 'ANDHRA PRADESH' Where L_State = 'AP'
Update Client_Details_Uppili Set L_State = 'ANDHRA PRADESH' Where L_State = 'APLOA'
Update Client_Details_Uppili Set L_State = 'ANDHRA PRADESH' Where L_State = 'HYDERABAD'
Update Client_Details_Uppili Set L_State = 'ANDHRA PRADESH' Where L_State = 'HYDERBAD'
Update Client_Details_Uppili Set L_State = 'ANDHRA PRADESH' Where L_State = 'HYDRABAD'
Update Client_Details_Uppili Set L_State = 'ANDHRA PRADESH' Where L_State = 'HYEDARABAD'
Update Client_Details_Uppili Set L_State = 'ANDHRA PRADESH' Where L_State = 'NADHRA PRADESH'
Update Client_Details_Uppili Set L_State = 'ANDHRA PRADESH' Where L_State = 'SECANDERABAD'
Update Client_Details_Uppili Set L_State = 'ANDHRA PRADESH' Where L_State = 'SECUNDERABAD'
Update Client_Details_Uppili Set L_State = 'ANDHRA PRADESH' Where L_State = 'SECUNDRABAD'
Update Client_Details_Uppili Set L_State = 'ARUNACHAL PRADESH' Where L_State = 'ARUNACHAL PRADE'
Update Client_Details_Uppili Set L_State = 'BAHRAIN' Where L_State = 'BAHARAIN'
Update Client_Details_Uppili Set L_State = 'BAHRAIN' Where L_State = 'BAHARIAN'
Update Client_Details_Uppili Set L_State = 'BAHRAIN' Where L_State = 'BAHARIN'
Update Client_Details_Uppili Set L_State = 'BAHRAIN' Where L_State = 'BAHRAIN'
Update Client_Details_Uppili Set L_State = 'BAHRAIN' Where L_State = 'BAHREAN'
Update Client_Details_Uppili Set L_State = 'BAHRAIN' Where L_State = 'BAHRIAN'
Update Client_Details_Uppili Set L_State = 'BAHRAIN' Where L_State = 'BARHAIN'
Update Client_Details_Uppili Set L_State = 'BAHRAIN' Where L_State = 'BEHRAIN'
Update Client_Details_Uppili Set L_State = 'BAHRAIN' Where L_State = 'BHARAIN'
Update Client_Details_Uppili Set L_State = 'CHHATTISGARH' Where L_State = 'C G'
Update Client_Details_Uppili Set L_State = 'CHHATTISGARH' Where L_State = 'C.G.'
Update Client_Details_Uppili Set L_State = 'CHHATTISGARH' Where L_State = 'CHATHISGHAR'
Update Client_Details_Uppili Set L_State = 'CHHATTISGARH' Where L_State = 'CHATISGARH'
Update Client_Details_Uppili Set L_State = 'CHHATTISGARH' Where L_State = 'CHATISGRAH'
Update Client_Details_Uppili Set L_State = 'CHHATTISGARH' Where L_State = 'CHATISHGAD'
Update Client_Details_Uppili Set L_State = 'CHHATTISGARH' Where L_State = 'CHATTIGARH'
Update Client_Details_Uppili Set L_State = 'CHHATTISGARH' Where L_State = 'CHATTIS GADH'
Update Client_Details_Uppili Set L_State = 'CHHATTISGARH' Where L_State = 'CHATTIS GHAD'
Update Client_Details_Uppili Set L_State = 'CHHATTISGARH' Where L_State = 'CHATTISGAD'
Update Client_Details_Uppili Set L_State = 'CHHATTISGARH' Where L_State = 'CHATTISGADH'
Update Client_Details_Uppili Set L_State = 'CHHATTISGARH' Where L_State = 'CHATTISGAR'
Update Client_Details_Uppili Set L_State = 'CHHATTISGARH' Where L_State = 'CHATTISGARDH'
Update Client_Details_Uppili Set L_State = 'CHHATTISGARH' Where L_State = 'CHATTISGARH'
Update Client_Details_Uppili Set L_State = 'CHHATTISGARH' Where L_State = 'CHATTISGRAH'
Update Client_Details_Uppili Set L_State = 'CHHATTISGARH' Where L_State = 'CHATTISGRTH'
Update Client_Details_Uppili Set L_State = 'CHHATTISGARH' Where L_State = 'CHATTISH GADH'
Update Client_Details_Uppili Set L_State = 'CHHATTISGARH' Where L_State = 'CHATTISHGARH'
Update Client_Details_Uppili Set L_State = 'CHHATTISGARH' Where L_State = 'CHHATIS GADH'
Update Client_Details_Uppili Set L_State = 'CHHATTISGARH' Where L_State = 'CHHATIS GARH'
Update Client_Details_Uppili Set L_State = 'CHHATTISGARH' Where L_State = 'CHHATISGADH'
Update Client_Details_Uppili Set L_State = 'CHHATTISGARH' Where L_State = 'CHHATISGAR'
Update Client_Details_Uppili Set L_State = 'CHHATTISGARH' Where L_State = 'CHHATISGARH'
Update Client_Details_Uppili Set L_State = 'CHHATTISGARH' Where L_State = 'CHHATISGART'
Update Client_Details_Uppili Set L_State = 'CHHATTISGARH' Where L_State = 'CHHATISGRAGH'
Update Client_Details_Uppili Set L_State = 'CHHATTISGARH' Where L_State = 'CHHATISGRAH'
Update Client_Details_Uppili Set L_State = 'CHHATTISGARH' Where L_State = 'CHHATISH GARH'
Update Client_Details_Uppili Set L_State = 'CHHATTISGARH' Where L_State = 'CHHATISHGARH'
Update Client_Details_Uppili Set L_State = 'CHHATTISGARH' Where L_State = 'CHHATSIGARH'
Update Client_Details_Uppili Set L_State = 'CHHATTISGARH' Where L_State = 'CHHATSIGRAH'
Update Client_Details_Uppili Set L_State = 'CHHATTISGARH' Where L_State = 'CHHATTISGAD'
Update Client_Details_Uppili Set L_State = 'CHHATTISGARH' Where L_State = 'CHHATTISGAR'
Update Client_Details_Uppili Set L_State = 'CHHATTISGARH' Where L_State = 'CHHATTISHGARH'
Update Client_Details_Uppili Set L_State = 'CHHATTISGARH' Where L_State = 'CHHTISGARH'
Update Client_Details_Uppili Set L_State = 'CHHATTISGARH' Where L_State = 'CHHTISHGAD'
Update Client_Details_Uppili Set L_State = 'CHHATTISGARH' Where L_State = 'CHHTTISGARH'
Update Client_Details_Uppili Set L_State = 'CHHATTISGARH' Where L_State = 'GHATTISGADH'
Update Client_Details_Uppili Set L_State = 'CHHATTISGARH' Where L_State = 'GHHATSIGRAH'
Update Client_Details_Uppili Set L_State = 'DAMAN AND DIU' Where L_State = 'DAMAN'
Update Client_Details_Uppili Set L_State = 'DAMAN AND DIU' Where L_State = 'DAMAN & DEV'
Update Client_Details_Uppili Set L_State = 'DAMAN AND DIU' Where L_State = 'DAMAN & DIU'
Update Client_Details_Uppili Set L_State = 'DAMAN AND DIU' Where L_State = 'DAMAN & DIU U T'
Update Client_Details_Uppili Set L_State = 'DAMAN AND DIU' Where L_State = 'DAMAN & DIV'
Update Client_Details_Uppili Set L_State = 'DAMAN AND DIU' Where L_State = 'DAMAN & DIV U T'
Update Client_Details_Uppili Set L_State = 'DAMAN AND DIU' Where L_State = 'DIU & DAMAN'
Update Client_Details_Uppili Set L_State = 'DAMAN AND DIU' Where L_State = 'DIV & DAMAN'
Update Client_Details_Uppili Set L_State = 'DAMAN AND DIU' Where L_State = 'UTDAMAN'
Update Client_Details_Uppili Set L_State = 'DELHI' Where L_State = 'DEHLI'
Update Client_Details_Uppili Set L_State = 'DELHI' Where L_State = 'DILHI'
Update Client_Details_Uppili Set L_State = 'DELHI' Where L_State = 'NEW DELHI'
Update Client_Details_Uppili Set L_State = 'DELHI' Where L_State = 'NEW DILHI'
Update Client_Details_Uppili Set L_State = 'DELHI' Where L_State = 'NEW DLEHI'
Update Client_Details_Uppili Set L_State = 'DELHI' Where L_State = 'NEWDELHI'
Update Client_Details_Uppili Set L_State = 'DELHI' Where L_State = 'NEWELHI'
Update Client_Details_Uppili Set L_State = 'GUJARAT' Where L_State = '.GUJARAT'
Update Client_Details_Uppili Set L_State = 'GUJARAT' Where L_State = 'AHAMEDABAD'
Update Client_Details_Uppili Set L_State = 'GUJARAT' Where L_State = 'AHEMDABAD'
Update Client_Details_Uppili Set L_State = 'GUJARAT' Where L_State = 'AHMEDABAD'
Update Client_Details_Uppili Set L_State = 'GUJARAT' Where L_State = 'ANAND'
Update Client_Details_Uppili Set L_State = 'GUJARAT' Where L_State = 'BARODA'
Update Client_Details_Uppili Set L_State = 'GUJARAT' Where L_State = 'BHAVNAGAR'
Update Client_Details_Uppili Set L_State = 'GUJARAT' Where L_State = 'DUJARAT'
Update Client_Details_Uppili Set L_State = 'GUJARAT' Where L_State = 'GAUAJARAT'
Update Client_Details_Uppili Set L_State = 'GUJARAT' Where L_State = 'GAUJARAT'
Update Client_Details_Uppili Set L_State = 'GUJARAT' Where L_State = 'GIKARAT'
Update Client_Details_Uppili Set L_State = 'GUJARAT' Where L_State = 'GJARAT'
Update Client_Details_Uppili Set L_State = 'GUJARAT' Where L_State = 'GJRAT'
Update Client_Details_Uppili Set L_State = 'GUJARAT' Where L_State = 'GJURAT'
Update Client_Details_Uppili Set L_State = 'GUJARAT' Where L_State = 'GRJARAT'
Update Client_Details_Uppili Set L_State = 'GUJARAT' Where L_State = 'GU8JARAT'
Update Client_Details_Uppili Set L_State = 'GUJARAT' Where L_State = 'GUAJARAT'
Update Client_Details_Uppili Set L_State = 'GUJARAT' Where L_State = 'GUAJART'
Update Client_Details_Uppili Set L_State = 'GUJARAT' Where L_State = 'GUAJRAT'
Update Client_Details_Uppili Set L_State = 'GUJARAT' Where L_State = 'GUARAT'
Update Client_Details_Uppili Set L_State = 'GUJARAT' Where L_State = 'GUGARAT'
Update Client_Details_Uppili Set L_State = 'GUJARAT' Where L_State = 'GUHARAT'
Update Client_Details_Uppili Set L_State = 'GUJARAT' Where L_State = 'GUIARAT'
Update Client_Details_Uppili Set L_State = 'GUJARAT' Where L_State = 'GUIJARAT'
Update Client_Details_Uppili Set L_State = 'GUJARAT' Where L_State = 'GUJ'
Update Client_Details_Uppili Set L_State = 'GUJARAT' Where L_State = 'GUJ RAT'
Update Client_Details_Uppili Set L_State = 'GUJARAT' Where L_State = 'GUJA'
Update Client_Details_Uppili Set L_State = 'GUJARAT' Where L_State = 'GUJAART'
Update Client_Details_Uppili Set L_State = 'GUJARAT' Where L_State = 'GUJAAT'
Update Client_Details_Uppili Set L_State = 'GUJARAT' Where L_State = 'GUJARAAT'
Update Client_Details_Uppili Set L_State = 'GUJARAT' Where L_State = 'GUJARAJ'
Update Client_Details_Uppili Set L_State = 'GUJARAT' Where L_State = 'GUJARART'
Update Client_Details_Uppili Set L_State = 'GUJARAT' Where L_State = 'GUJARAT N G'
Update Client_Details_Uppili Set L_State = 'GUJARAT' Where L_State = 'GUJARAT Q'
Update Client_Details_Uppili Set L_State = 'GUJARAT' Where L_State = 'GUJARAT1'
Update Client_Details_Uppili Set L_State = 'GUJARAT' Where L_State = 'GUJARATH'
Update Client_Details_Uppili Set L_State = 'GUJARAT' Where L_State = 'GUJARATQ'
Update Client_Details_Uppili Set L_State = 'GUJARAT' Where L_State = 'GUJARAY'
Update Client_Details_Uppili Set L_State = 'GUJARAT' Where L_State = 'GUJART'
Update Client_Details_Uppili Set L_State = 'GUJARAT' Where L_State = 'GUJARTA'
Update Client_Details_Uppili Set L_State = 'GUJARAT' Where L_State = 'GUJATRAT'
Update Client_Details_Uppili Set L_State = 'GUJARAT' Where L_State = 'GUJKARAT'
Update Client_Details_Uppili Set L_State = 'GUJARAT' Where L_State = 'GUJRA'
Update Client_Details_Uppili Set L_State = 'GUJARAT' Where L_State = 'GUJRART'
Update Client_Details_Uppili Set L_State = 'GUJARAT' Where L_State = 'GUJRATH'
Update Client_Details_Uppili Set L_State = 'GUJARAT' Where L_State = 'GUJRATQ'
Update Client_Details_Uppili Set L_State = 'GUJARAT' Where L_State = 'GUJRT'
Update Client_Details_Uppili Set L_State = 'GUJARAT' Where L_State = 'GUJRTAT'
Update Client_Details_Uppili Set L_State = 'GUJARAT' Where L_State = 'GUJSARAT'
Update Client_Details_Uppili Set L_State = 'GUJARAT' Where L_State = 'GUJTAT'
Update Client_Details_Uppili Set L_State = 'GUJARAT' Where L_State = 'GUJUARAT'
Update Client_Details_Uppili Set L_State = 'GUJARAT' Where L_State = 'GUJURAT'
Update Client_Details_Uppili Set L_State = 'GUJARAT' Where L_State = 'GUJURTA'
Update Client_Details_Uppili Set L_State = 'GUJARAT' Where L_State = 'GUKARAT'
Update Client_Details_Uppili Set L_State = 'GUJARAT' Where L_State = 'GURARAT'
Update Client_Details_Uppili Set L_State = 'GUJARAT' Where L_State = 'GURAT'
Update Client_Details_Uppili Set L_State = 'GUJARAT' Where L_State = 'GURJAT'
Update Client_Details_Uppili Set L_State = 'GUJARAT' Where L_State = 'GURJRAT'
Update Client_Details_Uppili Set L_State = 'GUJARAT' Where L_State = 'JUGARAT'
Update Client_Details_Uppili Set L_State = 'GUJARAT' Where L_State = 'JUNAGAD'
Update Client_Details_Uppili Set L_State = 'GUJARAT' Where L_State = 'JUNAGADH'
Update Client_Details_Uppili Set L_State = 'GUJARAT' Where L_State = 'KUTCH'
Update Client_Details_Uppili Set L_State = 'GUJARAT' Where L_State = 'N G'
Update Client_Details_Uppili Set L_State = 'GUJARAT' Where L_State = 'N GUJARAT'
Update Client_Details_Uppili Set L_State = 'GUJARAT' Where L_State = 'NADIAD'
Update Client_Details_Uppili Set L_State = 'GUJARAT' Where L_State = 'NEW GUJARAT'
Update Client_Details_Uppili Set L_State = 'GUJARAT' Where L_State = 'NEW GUJRAT'
Update Client_Details_Uppili Set L_State = 'GUJARAT' Where L_State = 'NG'
Update Client_Details_Uppili Set L_State = 'GUJARAT' Where L_State = 'NORTH GUJARAT'
Update Client_Details_Uppili Set L_State = 'GUJARAT' Where L_State = 'RAJKOT'
Update Client_Details_Uppili Set L_State = 'GUJARAT' Where L_State = 'SILVASSA'
Update Client_Details_Uppili Set L_State = 'GUJARAT' Where L_State = 'SUJARAT'
Update Client_Details_Uppili Set L_State = 'GUJARAT' Where L_State = 'SURAT'
Update Client_Details_Uppili Set L_State = 'GUJARAT' Where L_State = 'VADODARA'
Update Client_Details_Uppili Set L_State = 'GUJARAT' Where L_State = 'VAPI'
Update Client_Details_Uppili Set L_State = 'HARYANA' Where L_State = 'HARAYAN'
Update Client_Details_Uppili Set L_State = 'HARYANA' Where L_State = 'HARAYANA'
Update Client_Details_Uppili Set L_State = 'HARYANA' Where L_State = 'HARIANA'
Update Client_Details_Uppili Set L_State = 'HARYANA' Where L_State = 'HARIYA'
Update Client_Details_Uppili Set L_State = 'HARYANA' Where L_State = 'HARIYANA'
Update Client_Details_Uppili Set L_State = 'HARYANA' Where L_State = 'HARYYANA'
Update Client_Details_Uppili Set L_State = 'HARYANA' Where L_State = 'HYRYANA'
Update Client_Details_Uppili Set L_State = 'HARYANA' Where L_State = 'ROHTAK'
Update Client_Details_Uppili Set L_State = 'HIMACHAL PRADESH' Where L_State = 'HIMACHAL PRADES'
Update Client_Details_Uppili Set L_State = 'HIMACHAL PRADESH' Where L_State = 'HIMACHALPRADES'
Update Client_Details_Uppili Set L_State = 'HIMACHAL PRADESH' Where L_State = 'HIMACHALPRADESH'
Update Client_Details_Uppili Set L_State = 'HIMACHAL PRADESH' Where L_State = 'HIMCHAL PRADESH'
Update Client_Details_Uppili Set L_State = 'HIMACHAL PRADESH' Where L_State = 'HMACHAL PRADESH'
Update Client_Details_Uppili Set L_State = 'JAMMU AND KASHMIR' Where L_State = 'J & K'
Update Client_Details_Uppili Set L_State = 'JAMMU AND KASHMIR' Where L_State = 'JAMMU'
Update Client_Details_Uppili Set L_State = 'JAMMU AND KASHMIR' Where L_State = 'JAMMU & KASHMIR'
Update Client_Details_Uppili Set L_State = 'JAMMU AND KASHMIR' Where L_State = 'JAMMU &KASHMIR'
Update Client_Details_Uppili Set L_State = 'JAMMU AND KASHMIR' Where L_State = 'JAMMU AND KASHM'
Update Client_Details_Uppili Set L_State = 'JAMMU AND KASHMIR' Where L_State = 'JAMMU KASHMIR'
Update Client_Details_Uppili Set L_State = 'JAMMU AND KASHMIR' Where L_State = 'JAMMUKASHMIR'
Update Client_Details_Uppili Set L_State = 'JAMMU AND KASHMIR' Where L_State = 'JAMU & KASHMIR'
Update Client_Details_Uppili Set L_State = 'JAMMU AND KASHMIR' Where L_State = 'JAMU AND KASHMI'
Update Client_Details_Uppili Set L_State = 'JAMMU AND KASHMIR' Where L_State = 'KASHMIR'
Update Client_Details_Uppili Set L_State = 'JHARKHAND' Where L_State = 'JHAR KHAND'
Update Client_Details_Uppili Set L_State = 'JHARKHAND' Where L_State = 'ZHARKHAND'
Update Client_Details_Uppili Set L_State = 'KARNATAKA' Where L_State = 'BANGAL'
Update Client_Details_Uppili Set L_State = 'KARNATAKA' Where L_State = 'BANGALORE'
Update Client_Details_Uppili Set L_State = 'KARNATAKA' Where L_State = 'BANGLORE'
Update Client_Details_Uppili Set L_State = 'KARNATAKA' Where L_State = 'BNAGLORE'
Update Client_Details_Uppili Set L_State = 'KARNATAKA' Where L_State = 'KANATAKA'
Update Client_Details_Uppili Set L_State = 'KARNATAKA' Where L_State = 'KARANATAK'
Update Client_Details_Uppili Set L_State = 'KARNATAKA' Where L_State = 'KARANATAKA'
Update Client_Details_Uppili Set L_State = 'KARNATAKA' Where L_State = 'KARANATKA'
Update Client_Details_Uppili Set L_State = 'KARNATAKA' Where L_State = 'KARANTAKA'
Update Client_Details_Uppili Set L_State = 'KARNATAKA' Where L_State = 'KARATAKA'
Update Client_Details_Uppili Set L_State = 'KARNATAKA' Where L_State = 'KARNAKATA'
Update Client_Details_Uppili Set L_State = 'KARNATAKA' Where L_State = 'KARNARAKA'
Update Client_Details_Uppili Set L_State = 'KARNATAKA' Where L_State = 'KARNATAK'
Update Client_Details_Uppili Set L_State = 'KARNATAKA' Where L_State = 'KARNATAKE'
Update Client_Details_Uppili Set L_State = 'KARNATAKA' Where L_State = 'KARNATKA'
Update Client_Details_Uppili Set L_State = 'KARNATAKA' Where L_State = 'KARNATTAKA'
Update Client_Details_Uppili Set L_State = 'KERALA' Where L_State = 'KERLA'
Update Client_Details_Uppili Set L_State = 'MADHYA PRADESH' Where L_State = 'BHOPAL'
Update Client_Details_Uppili Set L_State = 'MADHYA PRADESH' Where L_State = 'INDORE'
Update Client_Details_Uppili Set L_State = 'MADHYA PRADESH' Where L_State = 'M P'
Update Client_Details_Uppili Set L_State = 'MADHYA PRADESH' Where L_State = 'M. P'
Update Client_Details_Uppili Set L_State = 'MADHYA PRADESH' Where L_State = 'M.P'
Update Client_Details_Uppili Set L_State = 'MADHYA PRADESH' Where L_State = 'M.P.'
Update Client_Details_Uppili Set L_State = 'MADHYA PRADESH' Where L_State = 'MADAHYAPRADESH'
Update Client_Details_Uppili Set L_State = 'MADHYA PRADESH' Where L_State = 'MADHA PRADESH'
Update Client_Details_Uppili Set L_State = 'MADHYA PRADESH' Where L_State = 'MADHAPRADESH'
Update Client_Details_Uppili Set L_State = 'MADHYA PRADESH' Where L_State = 'MADHAPREDAS'
Update Client_Details_Uppili Set L_State = 'MADHYA PRADESH' Where L_State = 'MADHAY PARDESH'
Update Client_Details_Uppili Set L_State = 'MADHYA PRADESH' Where L_State = 'MADHAY PRADESH'
Update Client_Details_Uppili Set L_State = 'MADHYA PRADESH' Where L_State = 'MADHAYA PRADESH'
Update Client_Details_Uppili Set L_State = 'MADHYA PRADESH' Where L_State = 'MADHAYAPRADESH'
Update Client_Details_Uppili Set L_State = 'MADHYA PRADESH' Where L_State = 'MADHAYPRADESH'
Update Client_Details_Uppili Set L_State = 'MADHYA PRADESH' Where L_State = 'MADHHYA PRADESH'
Update Client_Details_Uppili Set L_State = 'MADHYA PRADESH' Where L_State = 'MADHY PARADESH'
Update Client_Details_Uppili Set L_State = 'MADHYA PRADESH' Where L_State = 'MADHY PARDESH'
Update Client_Details_Uppili Set L_State = 'MADHYA PRADESH' Where L_State = 'MADHY PRADESH'
Update Client_Details_Uppili Set L_State = 'MADHYA PRADESH' Where L_State = 'MADHYA  PPADESH'
Update Client_Details_Uppili Set L_State = 'MADHYA PRADESH' Where L_State = 'MADHYA  PRADESH'
Update Client_Details_Uppili Set L_State = 'MADHYA PRADESH' Where L_State = 'MADHYA PARADESH'
Update Client_Details_Uppili Set L_State = 'MADHYA PRADESH' Where L_State = 'MADHYA PARDESH'
Update Client_Details_Uppili Set L_State = 'MADHYA PRADESH' Where L_State = 'MADHYA PRAADESH'
Update Client_Details_Uppili Set L_State = 'MADHYA PRADESH' Where L_State = 'MADHYA PRADASH'
Update Client_Details_Uppili Set L_State = 'MADHYA PRADESH' Where L_State = 'MADHYA PRADISH'
Update Client_Details_Uppili Set L_State = 'MADHYA PRADESH' Where L_State = 'MADHYA PRDESH'
Update Client_Details_Uppili Set L_State = 'MADHYA PRADESH' Where L_State = 'MADHYA PREDESH'
Update Client_Details_Uppili Set L_State = 'MADHYA PRADESH' Where L_State = 'MADHYA- PRADESH'
Update Client_Details_Uppili Set L_State = 'MADHYA PRADESH' Where L_State = 'MADHYA-PRADESH'
Update Client_Details_Uppili Set L_State = 'MADHYA PRADESH' Where L_State = 'MADHYAPRADEH'
Update Client_Details_Uppili Set L_State = 'MADHYA PRADESH' Where L_State = 'MADHYAPRADESH'
Update Client_Details_Uppili Set L_State = 'MADHYA PRADESH' Where L_State = 'MADHYAPRDESH'
Update Client_Details_Uppili Set L_State = 'MADHYA PRADESH' Where L_State = 'MADHYARADESH'
Update Client_Details_Uppili Set L_State = 'MADHYA PRADESH' Where L_State = 'MADHYPRADESH'
Update Client_Details_Uppili Set L_State = 'MADHYA PRADESH' Where L_State = 'MADYA PRADESH'
Update Client_Details_Uppili Set L_State = 'MADHYA PRADESH' Where L_State = 'MADYAPRADESH'
Update Client_Details_Uppili Set L_State = 'MADHYA PRADESH' Where L_State = 'MADYAPREDESH'
Update Client_Details_Uppili Set L_State = 'MADHYA PRADESH' Where L_State = 'MADYPRADESH'
Update Client_Details_Uppili Set L_State = 'MADHYA PRADESH' Where L_State = 'MADYPREDESH'
Update Client_Details_Uppili Set L_State = 'MADHYA PRADESH' Where L_State = 'MAHDHYA PRADESH'
Update Client_Details_Uppili Set L_State = 'MADHYA PRADESH' Where L_State = 'MAHDYA PRADESH'
Update Client_Details_Uppili Set L_State = 'MADHYA PRADESH' Where L_State = 'MAHDYA PRDESH'
Update Client_Details_Uppili Set L_State = 'MADHYA PRADESH' Where L_State = 'MP'
Update Client_Details_Uppili Set L_State = 'MAHARASHTRA' Where L_State = '.MAHARASHTRA'
Update Client_Details_Uppili Set L_State = 'MAHARASHTRA' Where L_State = 'HAHA'
Update Client_Details_Uppili Set L_State = 'MAHARASHTRA' Where L_State = 'HAMA'
Update Client_Details_Uppili Set L_State = 'MAHARASHTRA' Where L_State = 'HARASHTRA'
Update Client_Details_Uppili Set L_State = 'MAHARASHTRA' Where L_State = 'JALGAON'
Update Client_Details_Uppili Set L_State = 'MAHARASHTRA' Where L_State = 'JALONJALON'
Update Client_Details_Uppili Set L_State = 'MAHARASHTRA' Where L_State = 'KAHARASHTRA'
Update Client_Details_Uppili Set L_State = 'MAHARASHTRA' Where L_State = 'M H'
Update Client_Details_Uppili Set L_State = 'MAHARASHTRA' Where L_State = 'MAAHARASHTRA'
Update Client_Details_Uppili Set L_State = 'MAHARASHTRA' Where L_State = 'MAARAHTRA'
Update Client_Details_Uppili Set L_State = 'MAHARASHTRA' Where L_State = 'MAARASHATRA'
Update Client_Details_Uppili Set L_State = 'MAHARASHTRA' Where L_State = 'MAARASHTRA'
Update Client_Details_Uppili Set L_State = 'MAHARASHTRA' Where L_State = 'mah'
Update Client_Details_Uppili Set L_State = 'MAHARASHTRA' Where L_State = 'MAHA'
Update Client_Details_Uppili Set L_State = 'MAHARASHTRA' Where L_State = 'MAHAARSHTRA'
Update Client_Details_Uppili Set L_State = 'MAHARASHTRA' Where L_State = 'MAHAASHTRA'
Update Client_Details_Uppili Set L_State = 'MAHARASHTRA' Where L_State = 'MAHAH'
Update Client_Details_Uppili Set L_State = 'MAHARASHTRA' Where L_State = 'MAHAHARASHTRA'
Update Client_Details_Uppili Set L_State = 'MAHARASHTRA' Where L_State = 'MAHAHRASHTRA'
Update Client_Details_Uppili Set L_State = 'MAHARASHTRA' Where L_State = 'MAHAR)ASHTRA'
Update Client_Details_Uppili Set L_State = 'MAHARASHTRA' Where L_State = 'MAHARA'
Update Client_Details_Uppili Set L_State = 'MAHARASHTRA' Where L_State = 'MAHARAASHTRA'
Update Client_Details_Uppili Set L_State = 'MAHARASHTRA' Where L_State = 'MAHARAHASTRA'
Update Client_Details_Uppili Set L_State = 'MAHARASHTRA' Where L_State = 'MAHARAHATRA'
Update Client_Details_Uppili Set L_State = 'MAHARASHTRA' Where L_State = 'MAHARAHSHTRA'
Update Client_Details_Uppili Set L_State = 'MAHARASHTRA' Where L_State = 'MAHARAHSTARA'
Update Client_Details_Uppili Set L_State = 'MAHARASHTRA' Where L_State = 'MAHARAHSTRA'
Update Client_Details_Uppili Set L_State = 'MAHARASHTRA' Where L_State = 'MAHARAHTRA'
Update Client_Details_Uppili Set L_State = 'MAHARASHTRA' Where L_State = 'MAHARARSHTRA'
Update Client_Details_Uppili Set L_State = 'MAHARASHTRA' Where L_State = 'MAHARASAHTRA'
Update Client_Details_Uppili Set L_State = 'MAHARASHTRA' Where L_State = 'MAHARASHATRA'
Update Client_Details_Uppili Set L_State = 'MAHARASHTRA' Where L_State = 'MAHARASHRA'
Update Client_Details_Uppili Set L_State = 'MAHARASHTRA' Where L_State = 'MAHARASHRTA'
Update Client_Details_Uppili Set L_State = 'MAHARASHTRA' Where L_State = 'MAHARASHRTRA'
Update Client_Details_Uppili Set L_State = 'MAHARASHTRA' Where L_State = 'MAHARASHSTRA'
Update Client_Details_Uppili Set L_State = 'MAHARASHTRA' Where L_State = 'MAHARASHT'
Update Client_Details_Uppili Set L_State = 'MAHARASHTRA' Where L_State = 'MAHARASHTA'
Update Client_Details_Uppili Set L_State = 'MAHARASHTRA' Where L_State = 'MAHARASHTAR'
Update Client_Details_Uppili Set L_State = 'MAHARASHTRA' Where L_State = 'MAHARASHTARA'
Update Client_Details_Uppili Set L_State = 'MAHARASHTRA' Where L_State = 'MAHARASHTR'
Update Client_Details_Uppili Set L_State = 'MAHARASHTRA' Where L_State = 'MAHARASHTR A'
Update Client_Details_Uppili Set L_State = 'MAHARASHTRA' Where L_State = 'MAHARASHTRA Q'
Update Client_Details_Uppili Set L_State = 'MAHARASHTRA' Where L_State = 'MAHARASHTRAA'
Update Client_Details_Uppili Set L_State = 'MAHARASHTRA' Where L_State = 'MAHARASHTRAAA'
Update Client_Details_Uppili Set L_State = 'MAHARASHTRA' Where L_State = 'MAHARASHTRAQ'
Update Client_Details_Uppili Set L_State = 'MAHARASHTRA' Where L_State = 'MAHARASHTRASTRA'
Update Client_Details_Uppili Set L_State = 'MAHARASHTRA' Where L_State = 'MAHARASHTRE'
Update Client_Details_Uppili Set L_State = 'MAHARASHTRA' Where L_State = 'MAHARASHTRRA'
Update Client_Details_Uppili Set L_State = 'MAHARASHTRA' Where L_State = 'MAHARASHTRTA'
Update Client_Details_Uppili Set L_State = 'MAHARASHTRA' Where L_State = 'MAHARASRTA'
Update Client_Details_Uppili Set L_State = 'MAHARASHTRA' Where L_State = 'MAHARASTA'
Update Client_Details_Uppili Set L_State = 'MAHARASHTRA' Where L_State = 'MAHARASTHA'
Update Client_Details_Uppili Set L_State = 'MAHARASHTRA' Where L_State = 'MAHARASTHRA'
Update Client_Details_Uppili Set L_State = 'MAHARASHTRA' Where L_State = 'MAHARASTR'
Update Client_Details_Uppili Set L_State = 'MAHARASHTRA' Where L_State = 'MAHARASTRA'
Update Client_Details_Uppili Set L_State = 'MAHARASHTRA' Where L_State = 'MAHARASTRAQ'
Update Client_Details_Uppili Set L_State = 'MAHARASHTRA' Where L_State = 'MAHARASTRAS'
Update Client_Details_Uppili Set L_State = 'MAHARASHTRA' Where L_State = 'MAHARATHRA'
Update Client_Details_Uppili Set L_State = 'MAHARASHTRA' Where L_State = 'MAHARATHSTRA'
Update Client_Details_Uppili Set L_State = 'MAHARASHTRA' Where L_State = 'MAHARATRA'
Update Client_Details_Uppili Set L_State = 'MAHARASHTRA' Where L_State = 'MAHARATSTRA'
Update Client_Details_Uppili Set L_State = 'MAHARASHTRA' Where L_State = 'MAHAREASHTRA'
Update Client_Details_Uppili Set L_State = 'MAHARASHTRA' Where L_State = 'MAHARHATRA'
Update Client_Details_Uppili Set L_State = 'MAHARASHTRA' Where L_State = 'MAHARHTRA'
Update Client_Details_Uppili Set L_State = 'MAHARASHTRA' Where L_State = 'MAHARSAHTRA'
Update Client_Details_Uppili Set L_State = 'MAHARASHTRA' Where L_State = 'MAHARSATRA'
Update Client_Details_Uppili Set L_State = 'MAHARASHTRA' Where L_State = 'MAHARSHATRA'
Update Client_Details_Uppili Set L_State = 'MAHARASHTRA' Where L_State = 'MAHARSHTRA'
Update Client_Details_Uppili Set L_State = 'MAHARASHTRA' Where L_State = 'MAHARSTA'
Update Client_Details_Uppili Set L_State = 'MAHARASHTRA' Where L_State = 'MAHARSTHRA'
Update Client_Details_Uppili Set L_State = 'MAHARASHTRA' Where L_State = 'MAHARSTRA'
Update Client_Details_Uppili Set L_State = 'MAHARASHTRA' Where L_State = 'MAHARTSTRA'
Update Client_Details_Uppili Set L_State = 'MAHARASHTRA' Where L_State = 'MAHASATRA'
Update Client_Details_Uppili Set L_State = 'MAHARASHTRA' Where L_State = 'MAHASTRA'
Update Client_Details_Uppili Set L_State = 'MAHARASHTRA' Where L_State = 'MAHATASHTRA'
Update Client_Details_Uppili Set L_State = 'MAHARASHTRA' Where L_State = 'MAHGARASHTRA'
Update Client_Details_Uppili Set L_State = 'MAHARASHTRA' Where L_State = 'MAHJARASHTRA'
Update Client_Details_Uppili Set L_State = 'MAHARASHTRA' Where L_State = 'MAHRAHSTRA'
Update Client_Details_Uppili Set L_State = 'MAHARASHTRA' Where L_State = 'MAHRASHTARA'
Update Client_Details_Uppili Set L_State = 'MAHARASHTRA' Where L_State = 'MAHRASHTRA'
Update Client_Details_Uppili Set L_State = 'MAHARASHTRA' Where L_State = 'MAHRASTRA'
Update Client_Details_Uppili Set L_State = 'MAHARASHTRA' Where L_State = 'MARASHATRA'
Update Client_Details_Uppili Set L_State = 'MAHARASHTRA' Where L_State = 'MARASHATRAM'
Update Client_Details_Uppili Set L_State = 'MAHARASHTRA' Where L_State = 'MARASHTRA'
Update Client_Details_Uppili Set L_State = 'MAHARASHTRA' Where L_State = 'MASHARASHTRA'
Update Client_Details_Uppili Set L_State = 'MAHARASHTRA' Where L_State = 'MASHARASTRA'
Update Client_Details_Uppili Set L_State = 'MAHARASHTRA' Where L_State = 'MHAH'
Update Client_Details_Uppili Set L_State = 'MAHARASHTRA' Where L_State = 'MHARASHTRA'
Update Client_Details_Uppili Set L_State = 'MAHARASHTRA' Where L_State = 'MJAHA'
Update Client_Details_Uppili Set L_State = 'MAHARASHTRA' Where L_State = 'MQHARASHTRA'
Update Client_Details_Uppili Set L_State = 'MAHARASHTRA' Where L_State = 'MUMBAI'
Update Client_Details_Uppili Set L_State = 'MAHARASHTRA' Where L_State = 'MZHARASHTRA'
Update Client_Details_Uppili Set L_State = 'MAHARASHTRA' Where L_State = 'NAHARASHTRA'
Update Client_Details_Uppili Set L_State = 'MAHARASHTRA' Where L_State = 'NANDED'
Update Client_Details_Uppili Set L_State = 'MAHARASHTRA' Where L_State = 'NASIK'
Update Client_Details_Uppili Set L_State = 'MAHARASHTRA' Where L_State = 'PUNE'
Update Client_Details_Uppili Set L_State = 'MAHARASHTRA' Where L_State = 'RAIGAD'
Update Client_Details_Uppili Set L_State = 'MAHARASHTRA' Where L_State = 'THANE'
Update Client_Details_Uppili Set L_State = 'MAHARASHTRA' Where L_State = 'ULHASNAGAR'
Update Client_Details_Uppili Set L_State = 'ORISSA' Where L_State = 'ORISA'
Update Client_Details_Uppili Set L_State = 'ORISSA' Where L_State = 'ORRISA'
Update Client_Details_Uppili Set L_State = 'PUNJAB' Where L_State = 'AMRITSAR'
Update Client_Details_Uppili Set L_State = 'PUNJAB' Where L_State = 'PANJAB'
Update Client_Details_Uppili Set L_State = 'RAJASTHAN' Where L_State = 'AJMER'
Update Client_Details_Uppili Set L_State = 'RAJASTHAN' Where L_State = 'JODHPUR'
Update Client_Details_Uppili Set L_State = 'RAJASTHAN' Where L_State = 'NAGAUR'
Update Client_Details_Uppili Set L_State = 'RAJASTHAN' Where L_State = 'RAJ'
Update Client_Details_Uppili Set L_State = 'RAJASTHAN' Where L_State = 'RAJASHTAN'
Update Client_Details_Uppili Set L_State = 'RAJASTHAN' Where L_State = 'RAJASHTHAN'
Update Client_Details_Uppili Set L_State = 'RAJASTHAN' Where L_State = 'RAJASTAN'
Update Client_Details_Uppili Set L_State = 'RAJASTHAN' Where L_State = 'RAJESHTHAN'
Update Client_Details_Uppili Set L_State = 'RAJASTHAN' Where L_State = 'RAJESTAN'
Update Client_Details_Uppili Set L_State = 'RAJASTHAN' Where L_State = 'RAJESTHAN'
Update Client_Details_Uppili Set L_State = 'RAJASTHAN' Where L_State = 'RAJSHTAN'
Update Client_Details_Uppili Set L_State = 'RAJASTHAN' Where L_State = 'RAJSTAN'
Update Client_Details_Uppili Set L_State = 'RAJASTHAN' Where L_State = 'RAJSTHAN'
Update Client_Details_Uppili Set L_State = 'RAJASTHAN' Where L_State = 'RAJTHAN'
Update Client_Details_Uppili Set L_State = 'TAMILNADU' Where L_State = 'CHEENAI'
Update Client_Details_Uppili Set L_State = 'TAMILNADU' Where L_State = 'CHENNAI'
Update Client_Details_Uppili Set L_State = 'TAMILNADU' Where L_State = 'COLMBATORE'
Update Client_Details_Uppili Set L_State = 'TAMILNADU' Where L_State = 'MADRAS'
Update Client_Details_Uppili Set L_State = 'TAMILNADU' Where L_State = 'TALMILNADU'
Update Client_Details_Uppili Set L_State = 'TAMILNADU' Where L_State = 'TAMIL NADU'
Update Client_Details_Uppili Set L_State = 'TAMILNADU' Where L_State = 'TAMIL NAU'
Update Client_Details_Uppili Set L_State = 'TAMILNADU' Where L_State = 'TAMILANADU'
Update Client_Details_Uppili Set L_State = 'TAMILNADU' Where L_State = 'TAMILNADAU'
Update Client_Details_Uppili Set L_State = 'TAMILNADU' Where L_State = 'TAMILNANU'
Update Client_Details_Uppili Set L_State = 'TAMILNADU' Where L_State = 'TAMULNADU'
Update Client_Details_Uppili Set L_State = 'UTTAR PRADESH' Where L_State = 'ALLAHABAD'
Update Client_Details_Uppili Set L_State = 'UTTAR PRADESH' Where L_State = 'U P'
Update Client_Details_Uppili Set L_State = 'UTTAR PRADESH' Where L_State = 'U.P.'
Update Client_Details_Uppili Set L_State = 'UTTAR PRADESH' Where L_State = 'UP'
Update Client_Details_Uppili Set L_State = 'UTTAR PRADESH' Where L_State = 'UT'
Update Client_Details_Uppili Set L_State = 'UTTAR PRADESH' Where L_State = 'UTAR PRADESH'
Update Client_Details_Uppili Set L_State = 'UTTAR PRADESH' Where L_State = 'UTTAR  PRADESH'
Update Client_Details_Uppili Set L_State = 'UTTAR PRADESH' Where L_State = 'UTTAR PARDESH'
Update Client_Details_Uppili Set L_State = 'UTTAR PRADESH' Where L_State = 'UTTAR PRASDES'
Update Client_Details_Uppili Set L_State = 'UTTAR PRADESH' Where L_State = 'UTTARPRADES'
Update Client_Details_Uppili Set L_State = 'UTTAR PRADESH' Where L_State = 'UTTARPRADESH'
Update Client_Details_Uppili Set L_State = 'UTTAR PRADESH' Where L_State = 'UTTATR PRADESH'
Update Client_Details_Uppili Set L_State = 'UTTAR PRADESH' Where L_State = 'UTTER PRADESH'
Update Client_Details_Uppili Set L_State = 'UTTAR PRADESH' Where L_State = 'UTTERPRADESH'
Update Client_Details_Uppili Set L_State = 'UTTAR PRADESH' Where L_State = 'UTTRPRADESH'
Update Client_Details_Uppili Set L_State = 'UTTARANCHAL' Where L_State = 'DEHRADUN'
Update Client_Details_Uppili Set L_State = 'UTTARANCHAL' Where L_State = 'UTARANCHAL'
Update Client_Details_Uppili Set L_State = 'UTTARANCHAL' Where L_State = 'UTTARANACHAL'
Update Client_Details_Uppili Set L_State = 'UTTARANCHAL' Where L_State = 'UTTARANCHALL'
Update Client_Details_Uppili Set L_State = 'UTTARANCHAL' Where L_State = 'UTTARNCHAL'
Update Client_Details_Uppili Set L_State = 'UTTARANCHAL' Where L_State = 'UTTRANCHAL'
Update Client_Details_Uppili Set L_State = 'WEST BENGAL' Where L_State = 'CALCUTTA'
Update Client_Details_Uppili Set L_State = 'WEST BENGAL' Where L_State = 'KOLKATA'
Update Client_Details_Uppili Set L_State = 'WEST BENGAL' Where L_State = 'KOLKATTA'
Update Client_Details_Uppili Set L_State = 'WEST BENGAL' Where L_State = 'W B'
Update Client_Details_Uppili Set L_State = 'WEST BENGAL' Where L_State = 'WAST BANGAL'
Update Client_Details_Uppili Set L_State = 'WEST BENGAL' Where L_State = 'WEST BANGAL'
Update Client_Details_Uppili Set L_State = 'WEST BENGAL' Where L_State = 'WEST BANGOL'
Update Client_Details_Uppili Set L_State = 'WEST BENGAL' Where L_State = 'WEST BENGOL'
Update Client_Details_Uppili Set L_State = 'WEST BENGAL' Where L_State = 'WEST-BENGAL'
Update Client_Details_Uppili Set L_State = 'WEST BENGAL' Where L_State = 'WESTBANGAL'
Update Client_Details_Uppili Set L_State = 'WEST BENGAL' Where L_State = 'WESTBENGAL'

Update Client_Details_Uppili Set L_State = 'KUWAIT' Where L_State = 'KUWAIT'
Update Client_Details_Uppili Set L_State = 'KUWAIT' Where L_State = 'KUWAT'
Update Client_Details_Uppili Set L_State = 'MADHYA PRADESH' Where L_State = 'INDOR'
Update Client_Details_Uppili Set L_State = 'NEW JERSY' Where L_State = 'NEW JERSY'
Update Client_Details_Uppili Set L_State = 'PENNSYLVANIA' Where L_State = 'PENNSYLVANIA'
Update Client_Details_Uppili Set L_State = 'PHILADELPHIA' Where L_State = 'PHILADELPHIA'
Update Client_Details_Uppili Set L_State = 'RAJASTHAN' Where L_State = 'ALWAR'
Update Client_Details_Uppili Set L_State = 'TOKYO' Where L_State = 'TOKYO'
Update Client_Details_Uppili Set L_State = 'TOKYO' Where L_State = 'TPKYO'
Update Client_Details_Uppili Set L_State = 'U.A.E' Where L_State = 'U A E'
Update Client_Details_Uppili Set L_State = 'U.A.E' Where L_State = 'UAE'
Update Client_Details_Uppili Set L_State = 'UNITED STATES' Where L_State = 'UNITED KINGDOM'
Update Client_Details_Uppili Set L_State = 'UNITED STATES' Where L_State = 'UNITED STATES'
Update Client_Details_Uppili Set L_State = 'UNITED STATES' Where L_State = 'USA'
Update Client_Details_Uppili Set L_State = 'WEST BENGAL' Where L_State = 'NEW BANGAL'


----------------------------------------------------------------------------------------------------------------------
-- PROC 3
----------------------------------------------------------------------------------------------------------------------


Update 
	Client1
Set 
	Region = r1.Region,
	l_state = r1.l_state
From 
	Anand1.Msajag.Dbo.Client_Details_Uppili R1
where
	Client1.Cl_code = r1.Cl_Code

GO
