-- Object: PROCEDURE dbo.USP_CCE_REPORT_DATA
-- Server: 10.253.33.91 | DB: Dustbin
--------------------------------------------------

---- // USE DUSTBIN   --- // ANAND1                        
---- // DESCRIPTION :- SANDIP TOTE DATA. CREATED BY HRISHI                        
                        
CREATE PROC [dbo].[USP_CCE_REPORT_DATA]                        
AS          
          
DECLARE @SQL VARCHAR (MAX) ,@SQL2 VARCHAR (MAX), @SQLFINAL VARCHAR (MAX) , @PATH VARCHAR (MAX)                         
SET @PATH='J:\Backoffice\SL_AUTO\SANDIP_T\CCE_PEAK_DATA\INPUT\CCE_DATE.txt'                          
                     
 IF OBJECT_ID(N'tempdb..#DATE') IS NOT NULL                    
    DROP TABLE #DATE                    
CREATE TABLE #DATE (FDATE VARCHAR(50))                        
                        
SET @SQL='BULK INSERT  #DATE FROM ' + ''''+ @PATH +''''                        
SET @SQL2=' WITH                          
    (                          
           FIRSTROW = 1,                          
           FIELDTERMINATOR = '','',  --CSV FIELD DELIMITER                          
           ROWTERMINATOR = ''\n'',   --USE TO SHIFT THE CONTROL TO NEXT ROW                          
           TABLOCK                          
    )'                          
                        
SET @SQLFINAL= @SQL + @SQL2                          
PRINT @SQLFINAL                          
EXEC (@SQLFINAL)                        
                        
--SELECT TOP 10 * FROM #DATE
                    
 IF OBJECT_ID(N'tempdb..#DATA') IS NOT NULL                    
 DROP TABLE #DATA                    
          
DECLARE @FDATE VARCHAR(11),@TDATE VARCHAR(11),@MDATE VARCHAR(11)          
SELECT @MDATE=FDATE FROM #DATE          
--PRINT @MDATE          
          
SELECT @FDATE = MAX(MARGINDATE),@TDATE = MAX(MARGINDATE)           
FROM MSAJAG.DBO.TBL_COMBINE_REPORTING_PEAK_DETAIL A WITH (NOLOCK) WHERE  MARGINDATE <= @MDATE          
          
IF OBJECT_ID(N'tempdb..#MARGIN_PEAK') IS NOT NULL                    
DROP TABLE #MARGIN_PEAK          
SELECT A.EXCHANGE,A.SEGMENT,A.PARTY_CODE,MARGINDATE,TDAY_LEDGER = SUM(TDAY_LEDGER),TDAY_MARGIN = SUM(TDAY_MARGIN),TDAY_CASHCOLL = SUM(TDAY_CASHCOLL),          
TDAY_NONCASH = SUM(TDAY_NONCASH),TDAY_MTM = SUM(TDAY_MTM)                       
INTO #MARGIN_PEAK                              
FROM MSAJAG.DBO.TBL_COMBINE_REPORTING_PEAK_DETAIL A WITH (NOLOCK) WHERE  MARGINDATE BETWEEN @FDATE AND @TDATE + ' 23:59'                        
GROUP BY A.EXCHANGE,A.SEGMENT,A.PARTY_CODE,MARGINDATE  ORDER BY MARGINDATE,A.PARTY_CODE                          
          
SET  @FDATE = @MDATE          
SET  @TDATE = @MDATE          
          
DELETE #MARGIN_PEAK WHERE PARTY_CODE IN ('12798','BBBB','ERROR')          
          
IF OBJECT_ID(N'tempdb..#EXCHANGE_CLINETS_DISTINCT_MAR_PEAK') IS NOT NULL          
DROP TABLE #EXCHANGE_CLINETS_DISTINCT_MAR_PEAK          
SELECT DISTINCT PARTY_CODE AS CL_CODE INTO #EXCHANGE_CLINETS_DISTINCT_MAR_PEAK FROM #MARGIN_PEAK WHERE (TDAY_MARGIN <> 0 OR TDAY_MTM <> 0 )          
          
CREATE INDEX CLIIDX ON #EXCHANGE_CLINETS_DISTINCT_MAR_PEAK(CL_CODE)          
          
DELETE #MARGIN_PEAK WHERE PARTY_CODE NOT IN (SELECT CL_CODE FROM #EXCHANGE_CLINETS_DISTINCT_MAR_PEAK)          
          
IF OBJECT_ID(N'tempdb..#MARGIN_FINAL_PEAK') IS NOT NULL          
DROP TABLE #MARGIN_FINAL_PEAK          
SELECT PARTY_CODE,SUM(TDAY_LEDGER) AS M_LEDGER_PEAK INTO #MARGIN_FINAL_PEAK FROM #MARGIN_PEAK GROUP BY PARTY_CODE          
          
IF OBJECT_ID(N'tempdb..#CCE_MAR') IS NOT NULL          
DROP TABLE #CCE_MAR          
SELECT REPORT_DATE,SNO INTO #CCE_MAR FROM ACCOUNT.DBO.CLIENT_CASH_DETAILS(NOLOCK) WHERE REPORT_DATE BETWEEN @FDATE AND @TDATE + ' 23:59'          
          
IF OBJECT_ID(N'tempdb..#CCERPT_MAR') IS NOT NULL                    
DROP TABLE #CCERPT_MAR          
SELECT REPORT_DATE,UCC=LTRIM(RTRIM(ISNULL(PARTY_CODE, ''))),            
EXCHANGE=CASE WHEN L.EXCHANGE='MTF' THEN 'MTF' ELSE 'BROKING' END,EDT_BAL=ROUND(L.EDT_BAL,2),PEAK_FINANCIAL_LEDGER          
INTO #CCERPT_MAR            
FROM #CCE_MAR C, ACCOUNT.DBO.CLIENT_CASH_LED_BALANCES L WITH (NOLOCK) WHERE C.SNO = L.SNO            
AND EXCHANGE <> 'MTF'            
          
DELETE FROM #CCERPT_MAR WHERE UCC='BBBB'          
          
IF OBJECT_ID(N'tempdb..#CASHREPORTING_MAR_PEAK') IS NOT NULL                    
DROP TABLE #CASHREPORTING_MAR_PEAK          
SELECT REPORT_DATE,UCC=LTRIM(RTRIM(ISNULL(UCC, ''))),EDT_BAL=SUM(EDT_BAL),          
PEAK_FINANCIAL_LEDGER = SUM(PEAK_FINANCIAL_LEDGER)          
INTO #CASHREPORTING_MAR_PEAK            
FROM #CCERPT_MAR , #EXCHANGE_CLINETS_DISTINCT_MAR_PEAK WHERE UCC BETWEEN 'A' AND 'ZZZZZZZZZZZZZZZZZ9999'           
AND UCC = CL_CODE          
GROUP BY REPORT_DATE,UCC            
          
          
--------------------------------------------------------------------------------------------------------------------------------------                    
IF OBJECT_ID(N'DUSTBIN..TBL_MARGIN_PEAK') IS NOT NULL  -- PEAK MARGIN        
DROP TABLE TBL_MARGIN_PEAK      
      
SELECT EXCHANGE,SEGMENT,PARTY_CODE,CONVERT(VARCHAR,MARGINDATE,23) AS 'MARGINDATE',CONVERT(VARCHAR,TDAY_LEDGER) AS 'TDAY_LEDGER',CONVERT(VARCHAR,TDAY_MARGIN) AS 'TDAY_MARGIN',      
CONVERT(VARCHAR,TDAY_CASHCOLL) AS 'TDAY_CASHCOLL',CONVERT(VARCHAR,TDAY_NONCASH) AS 'TDAY_NONCASH',CONVERT(VARCHAR,TDAY_MTM) AS 'TDAY_MTM'       
INTO DUSTBIN.DBO.TBL_MARGIN_PEAK      
FROM #MARGIN_PEAK ORDER BY 3       
          
IF OBJECT_ID(N'DUSTBIN..TBL_CASHREPORTING_MAR_PEAK') IS NOT NULL  -- PEAK LED CCE      
DROP TABLE TBL_CASHREPORTING_MAR_PEAK      
      
SELECT CONVERT(VARCHAR,REPORT_DATE,23) AS 'REPORT_DATE',UCC,CONVERT(VARCHAR,EDT_BAL) AS 'EDT_BAL',CONVERT(VARCHAR,PEAK_FINANCIAL_LEDGER) AS 'PEAK_FINANCIAL_LEDGER'      
INTO DUSTBIN.DBO.TBL_CASHREPORTING_MAR_PEAK      
FROM #CASHREPORTING_MAR_PEAK ORDER BY 2      
          
IF OBJECT_ID(N'DUSTBIN..TBL_REC_PAY') IS NOT NULL                    
DROP TABLE TBL_REC_PAY          
;WITH CTE AS (          
SELECT CLTCODE,SUM(CASE WHEN VTYP = 2 THEN VAMT ELSE 0 END) AS REC,SUM(CASE WHEN VTYP = 3 THEN VAMT ELSE 0 END) AS PAY          
FROM ACCOUNT.DBO.LEDGER L WITH (NOLOCK),#CASHREPORTING_MAR_PEAK M WHERE L.CLTCODE = M.UCC AND VDT BETWEEN @FDATE AND @TDATE + ' 23:59:59'          
GROUP BY CLTCODE )      
      
SELECT CLTCODE,CONVERT(VARCHAR,REC) AS 'REC',CONVERT(VARCHAR,PAY) AS 'PAY' INTO DUSTBIN.DBO.TBL_REC_PAY FROM CTE  WHERE (REC <> 0 OR PAY <> 0) ORDER BY 1 -- REC AND PAYMENT      
------------------------------------------------------------------------------------------------------------------------------------          
      
--SELECT TOP 10 * FROM TBL_MARGIN_PEAK      
--SELECT TOP 10 * FROM TBL_CASHREPORTING_MAR_PEAK      
--SELECT TOP 10 * FROM TBL_REC_PAY      
      
DROP TABLE #EXCHANGE_CLINETS_DISTINCT_MAR_PEAK          
DROP TABLE #CCERPT_MAR          
DROP TABLE #CASHREPORTING_MAR_PEAK          
DROP TABLE #CCE_MAR          
DROP TABLE #MARGIN_FINAL_PEAK          
DROP TABLE #MARGIN_PEAK       
          
--SELECT TOP 10 * FROM DUSTBIN.DBO.TBL_MARGIN_PEAK          
--SELECT TOP 10 * FROM DUSTBIN.DBO.TBL_CASHREPORTING_MAR_PEAK          
--SELECT TOP 10 * FROM DUSTBIN.DBO.TBL_REC_PAY          
            
------ // 1st FILE GENERATION      
DECLARE @RPT_DATE VARCHAR(30)=REPLACE(CONVERT(VARCHAR(10),GETDATE(),3),'/','')          
DECLARE @FILENAME VARCHAR(100) = 'J:\Backoffice\SL_AUTO\SANDIP_T\CCE_PEAK_DATA\OUTPUT\' +'CCE_MARGIN_PEAK_DATA' + '.CSV'      
DECLARE @ALL VARCHAR(MAX)      
          
SET @ALL = 'EXEC MASTER.DBO.XP_CMDSHELL ''BCP "SELECT ''''EXCHANGE'''',''''SEGMENT'''',''''PARTY_CODE'''',''''MARGINDATE'''',''''TDAY_LEDGER'''',''''TDAY_MARGIN'''',''''TDAY_CASHCOLL'''',''''TDAY_NONCASH'''',''''TDAY_MTM'''''          
SET @ALL = @ALL+ ' UNION ALL SELECT * FROM DUSTBIN.DBO.TBL_MARGIN_PEAK'                        
--SET @ALL = 'EXEC MASTER.DBO.XP_CMDSHELL ''BCP "SELECT * FROM DUSTBIN.DBO.TBL_MARGIN_PEAK'               
--PRINT @ALL          
SET @ALL=@ALL+' " QUERYOUT ' +@FILENAME+ ' -c -t"," -c -t"," -r"\n" -T'', NO_OUTPUT'                        
PRINT @ALL          
EXEC(@ALL)          
      
---- // 2nd FILE GENERATION      
DECLARE @FILENAME1 VARCHAR(100) = 'J:\Backoffice\SL_AUTO\SANDIP_T\CCE_PEAK_DATA\OUTPUT\' +'CCE_CASHREPORTING_MAR_PEAK_DATA' + '.CSV'          
DECLARE @ALL1 VARCHAR(MAX)          
          
SET @ALL1 = 'EXEC MASTER.DBO.XP_CMDSHELL ''BCP "SELECT ''''REPORT_DATE'''',''''UCC'''',''''EDT_BAL'''',''''PEAK_FINANCIAL_LEDGER'''''          
SET @ALL1 = @ALL1+ ' UNION ALL SELECT * FROM DUSTBIN.DBO.TBL_CASHREPORTING_MAR_PEAK'                          
--PRINT @ALL1          
SET @ALL1=@ALL1+' " QUERYOUT ' +@FILENAME1+ ' -c -t"," -c -t"," -r"\n" -T'', NO_OUTPUT'                        
PRINT @ALL1          
EXEC(@ALL1)          
      
------ // 3rd FILE GENERATION      
DECLARE @FILENAME2 VARCHAR(100) = 'J:\Backoffice\SL_AUTO\SANDIP_T\CCE_PEAK_DATA\OUTPUT\' +'CCE_REC_PAY_DATA' + '.CSV'          
DECLARE @ALL2 VARCHAR(MAX)          
          
SET @ALL2 = 'EXEC MASTER.DBO.XP_CMDSHELL ''BCP "SELECT ''''CLTCODE'''',''''REC'''',''''PAY'''''      
SET @ALL2 = @ALL2+ ' UNION ALL SELECT * FROM DUSTBIN.DBO.TBL_REC_PAY'                              
--PRINT @ALL2      
SET @ALL2=@ALL2+' " QUERYOUT ' +@FILENAME2+ ' -c -t"," -c -t"," -r"\n" -T'', NO_OUTPUT'                        
PRINT @ALL2          
EXEC(@ALL2)          
          
DROP TABLE DUSTBIN.DBO.TBL_MARGIN_PEAK          
DROP TABLE DUSTBIN.DBO.TBL_CASHREPORTING_MAR_PEAK          
DROP TABLE DUSTBIN.DBO.TBL_REC_PAY          
                        
SELECT 'CCE REPORTING FILES EXPORTED TO CCE REPORTING FILES EXPORTED TO J:\\Backoffice\SL_AUTO\SANDIP_T\CCE_PEAK_DATA\OUTPUT FOLDER' AS 'REMARK'

GO
