-- Object: PROCEDURE dbo.USP_RPT_BANK_RECO_REPORT_ANG
-- Server: 10.253.33.91 | DB: Dustbin
--------------------------------------------------

---- // RUN AT .91 USE DUSTBIN
---- // VISHAL DOSHI FRONTEND

/*
DESCRIPTION:- CREATED BY HRISHI ON JUL 24 2024 FOR AVOID BO DEPENDENCY
REQUESTED BY:- VISHAL DOSHI
SRE / ORE:- ORE-3852
*/

CREATE PROCEDURE USP_RPT_BANK_RECO_REPORT_ANG (@FDATE DATE)

AS
BEGIN
----DECLARE FDATE='JUL 23 2024'

CREATE TABLE #TEMPDATA
(
SRNO INT,
[BANK NAME] VARCHAR (255),
DETAILS VARCHAR (255),
BANKCODE VARCHAR (255),
[TYPE OF ACCOUNT] VARCHAR (255),
SEGMENT VARCHAR (255),
[NAME] VARCHAR (255),
[BANK STATEMENT BALANCE] VARCHAR (255),
[BANK BOOK BALANCE] VARCHAR (255),
[CHQ. DEPOSITED BUT NOT CREDITED] VARCHAR (255),
[CHQ. ISSUED BUT NOT DEBITED] VARCHAR (255),
DIFF VARCHAR (255),
[TALLY/ UNTALLY] VARCHAR (255),
REMARKS VARCHAR (255)
)

----CREATE INDEX IDX_#TEMPDATA ON #TEMPDATA (SRNO, [BANK NAME], BANKCODE) 

INSERT INTO #TEMPDATA
EXEC ACCOUNT.DBO.BANK_RECO_REPORT_ANG @FDATE

--SELECT * FROM #TEMPDATA

IF OBJECT_ID(N'DUSTBIN..TBL_BANK_RECO_REPORT_ANG_DATA') IS NOT NULL
DROP TABLE DUSTBIN.DBO.TBL_BANK_RECO_REPORT_ANG_DATA

SELECT CONVERT (VARCHAR (10),SRNO) AS SRNO, [BANK NAME], DETAILS, BANKCODE, [TYPE OF ACCOUNT], SEGMENT, [NAME], [BANK STATEMENT BALANCE],
[BANK BOOK BALANCE], [CHQ. DEPOSITED BUT NOT CREDITED], [CHQ. ISSUED BUT NOT DEBITED], DIFF, [TALLY/ UNTALLY], REMARKS 
INTO DUSTBIN.DBO.TBL_BANK_RECO_REPORT_ANG_DATA
FROM #TEMPDATA

----SELECT * FROM DUSTBIN.DBO.TBL_BANK_RECO_REPORT_ANG_DATA

DECLARE @FILENAME VARCHAR(100) = 'J:\Backoffice\EXPORT\RECO_FILES_AUTO\' +'BANK_RECO_REPORT_ANG_DATA' + '.CSV'
----DECLARE @FDATE DATE ='JUL 24 2024'
DECLARE @ALL VARCHAR(MAX)

SET @ALL = 'EXEC MASTER.DBO.XP_CMDSHELL ''BCP "SELECT ''''SRNO'''',''''[BANK NAME]'''',''''DETAILS'''',''''BANKCODE'''',''''[TYPE OF ACCOUNT]'''',''''SEGMENT'''',''''[NAME]'''',''''[BANK STATEMENT BALANCE]'''',''''[BANK BOOK BALANCE]'''',''''[CHQ. DEPOSITED BUT NOT CREDITED]'''',''''[CHQ. ISSUED BUT NOT DEBITED]'''',''''DIFF'''',''''[TALLY/ UNTALLY]'''',''''REMARKS'''''
SET @ALL = @ALL+ ' UNION ALL SELECT * FROM DUSTBIN.DBO.TBL_BANK_RECO_REPORT_ANG_DATA'          
PRINT @ALL            
SET @ALL=@ALL+' " QUERYOUT ' +@FILENAME+ ' -c -t"," -c -t"," -r"\n" -T'', NO_OUTPUT'
PRINT @ALL            
EXEC(@ALL)            

SELECT 'BANK_RECO_REPORT_ANG DATA FILE EXPORTED TO ' + @FILENAME + ' FOR DATE ' + CONVERT (VARCHAR(11),@FDATE,0) AS REMARKS

END

GO
