-- Object: PROCEDURE dbo.DEBIT_BILL_DATA_NEW
-- Server: 10.253.33.91 | DB: Dustbin
--------------------------------------------------


--  DROP TABLE #TBL    
--DROP TABLE #TBLMAIN    
--DROP TABLE #FINALDATA         
  
      
CREATE Proc [dbo].[DEBIT_BILL_DATA_NEW] ( @FILTER INT)    
      
AS      
  --DECLARE @FILTER INT='1'    
BEGIN      
      
DECLARE @DT DATE=GETDATE()-@FILTER    
    
CREATE TABLE #TBL      
(CL_CODE VARCHAR(15),      
 BILL_AMT MONEY ,      
 EXCHANGE VARCHAR(15))      
       
 CREATE NONCLUSTERED INDEX #T ON #TBL      
 (CL_CODE ASC,EXCHANGE ASC)      
      
       
 INSERT INTO #TBL      
 SELECT CLTCODE, SUM(CASE WHEN DRCR ='C' THEN VAMT*-1 ELSE VAMT END),'NSE'       
 FROM ACCOUNT.DBO.LEDGER WITH(NOLOCK) where Vtyp='15'  and CONVERT(DATE,VDT) =CONVERT(DATE,Getdate()-@FILTER)
 --and cltcode IN ('CNBC2072','S1538575') 
 and cltcode >='A00000000' and Cltcode <='ZZZZZZZZZZ'  
 GROUP BY CLTCODE
       
  INSERT INTO #TBL      
 SELECT CLTCODE, SUM(CASE WHEN DRCR ='C' THEN VAMT*-1 ELSE VAMT END) ,'BSE'       
 FROM [ANAND].ACCOUNT_AB.DBO.LEDGER WITH(NOLOCK) where Vtyp='15'  and CONVERT(DATE,VDT) =CONVERT(DATE,Getdate()-@FILTER)   
 --and cltcode IN ('CNBC2072')   
 and cltcode >='A00000000' and Cltcode <='ZZZZZZZZZZ'  
 GROUP BY CLTCODE
       
  INSERT INTO #TBL      
 SELECT  CLTCODE,SUM(CASE WHEN DRCR ='C' THEN VAMT*-1 ELSE VAMT END) ,'NSEFO'       
 FROM [ANGELFO].ACCOUNTFO.DBO.LEDGER WITH(NOLOCK) WHERE Vtyp='15'  and CONVERT(DATE,VDT) =CONVERT(DATE,Getdate()-@FILTER)  
  --and cltcode IN ('CNBC2072')   
 and cltcode >='A00000000' and Cltcode <='ZZZZZZZZZZ'        
 GROUP BY CLTCODE
       
  INSERT INTO #TBL      
 SELECT  CLTCODE,SUM(CASE WHEN DRCR ='C' THEN VAMT*-1 ELSE VAMT END)  ,'NSECURFO'       
 FROM [ANGELFO].ACCOUNTCURFO.DBO.LEDGER WITH(NOLOCK) WHERE Vtyp='15'  and CONVERT(DATE,VDT) =CONVERT(DATE,Getdate()-@FILTER)   
  --and cltcode IN ('CNBC2072')   
 and cltcode >='A00000000' and Cltcode <='ZZZZZZZZZZ'  
 GROUP BY CLTCODE
       
   INSERT INTO #TBL      
 SELECT  CLTCODE,SUM(CASE WHEN DRCR ='C' THEN VAMT*-1 ELSE VAMT END) ,'MCDX'       
 FROM [ANGELCOMMODITY].ACCOUNTMCDX.DBO.LEDGER WITH(NOLOCK) WHERE Vtyp='15'  and CONVERT(DATE,VDT) =CONVERT(DATE,Getdate()-@FILTER) 
 --and cltcode IN ('CNBC2072')   
 and cltcode >='A00000000' and Cltcode <='ZZZZZZZZZZ'  
 GROUP BY CLTCODE
       
    INSERT INTO #TBL      
 SELECT  CLTCODE,SUM(CASE WHEN DRCR ='C' THEN VAMT*-1 ELSE VAMT END)  ,'NCDX'      
 FROM [ANGELCOMMODITY].ACCOUNTNCDX.DBO.LEDGER WITH(NOLOCK) WHERE Vtyp='15'  and CONVERT(DATE,VDT) =CONVERT(DATE,Getdate()-@FILTER)
  --and cltcode IN ('CNBC2072')   
 and cltcode >='A00000000' and Cltcode <='ZZZZZZZZZZ'  
 GROUP BY CLTCODE
      
      
CREATE TABLE #TBLMAIN      
(CL_CODE VARCHAR(15),      
NSE_BAL MONEY,      
BSE_BAL MONEY,      
NSEFO_BAL MONEY,      
NSECURFO_BAL MONEY,      
MCX_BAL MONEY,      
NCDX_BAL MONEY,      
TOTAL_BAL MONEY      
 )        
      
      
 CREATE NONCLUSTERED INDEX #TQ ON #TBLMAIN      
 (CL_CODE ASC)      
      
      
INSERT INTO  #TBLMAIN      
SELECT DISTINCT CL_CODE,'0','0','0','0','0','0', '0' FROM #TBL      
      
 UPDATE  #TBLMAIN SET NSE_BAL = BILL_AMT FROM #TBL WHERE EXCHANGE ='NSE' AND #TBLMAIN.CL_CODE=#TBL.CL_CODE        
 UPDATE  #TBLMAIN SET BSE_BAL = BILL_AMT FROM #TBL WHERE EXCHANGE ='BSE'AND #TBLMAIN.CL_CODE=#TBL.CL_CODE      
 UPDATE  #TBLMAIN SET NSEFO_BAL = BILL_AMT FROM #TBL WHERE EXCHANGE ='NSEFO'AND #TBLMAIN.CL_CODE=#TBL.CL_CODE      
  UPDATE #TBLMAIN SET NSECURFO_BAL = BILL_AMT FROM #TBL WHERE EXCHANGE ='NSECURFO'AND #TBLMAIN.CL_CODE=#TBL.CL_CODE      
 UPDATE  #TBLMAIN SET MCX_BAL = BILL_AMT FROM #TBL WHERE EXCHANGE ='MCX'AND #TBLMAIN.CL_CODE=#TBL.CL_CODE      
 UPDATE  #TBLMAIN SET NCDX_BAL = BILL_AMT FROM #TBL WHERE EXCHANGE ='NCDX'AND #TBLMAIN.CL_CODE=#TBL.CL_CODE      
 UPDATE  #TBLMAIN SET TOTAL_BAL =  NSE_BAL+BSE_BAL+NSEFO_BAL+NSECURFO_BAL+MCX_BAL+NCDX_BAL      
     
    
      
  SELECT @DT AS 'BILL_DATE',* INTO #FINALDATA FROM #TBLMAIN where TOTAL_BAL >='1'      
    
  SELECT * FROM #FINALDATA ORDER BY CL_CODE    
  
  DROP TABLE #TBL    
DROP TABLE #TBLMAIN    
      
  END

GO
