-- Object: PROCEDURE dbo.RPT_MTF_SHORTAGE
-- Server: 10.253.33.91 | DB: Dustbin
--------------------------------------------------

 

CREATE PROC RPT_MTF_SHORTAGE (@sauda_date datetime)

AS 
SELECT M.* , CLIENT_FUND_AMT = CONVERT(NUMERIC(18,4),0) INTO #TBL_MTF_DATA
FROM MTFTRADE.DBO.TBL_MTF_DATA M
WHERE SAUDA_DATE =@sauda_date

Create index #c on #TBL_MTF_DATA(PARTY_CODE,SAUDA_DATE)

	  
UPDATE #TBL_MTF_DATA SET MTOM_LOSS = -MTOM_LOSS
WHERE SAUDA_DATE > 'NOV 27 2019'

UPDATE	#TBL_MTF_DATA SET CLIENT_FUND_AMT = ISNULL(A.AMT,0)
FROM	(
		SELECT PARTY_CODE, AMT=SUM(nCliNetAmt),SAUDA_DATE  FROM MTFTRADE.DBO.tbl_MTR_MaintMarginQty
		WHERE	SAUDA_DATE =@sauda_date
		GROUP BY PARTY_CODE,SAUDA_DATE
		) A
WHERE	#TBL_MTF_DATA.PARTY_CODE = A.PARTY_CODE
AND A.SAUDA_DATE=#TBL_MTF_DATA.SAUDA_DATE



SELECT SAUDA_DATE, T.PARTY_CODE, 
FUDEDVAL = SUM(NETAMT), 
MTOM = SUM(MTOM_LOSS), 
MARGIN_REQ = SUM(MARGIN_REQ),
MTFLEDBAL,  
AVALABLECASH = MTFLEDBAL + SUM(NETAMT)-CLIENT_FUND_AMT,
COLLATERALBHC = CONVERT(NUMERIC(18,4),0),
COLLATERALAHC = CONVERT(NUMERIC(18,4),0),
MARGIN_SHORTFALL = CONVERT(NUMERIC(18,4),0)
INTO #DATA
FROM  #TBL_MTF_DATA T 
WHERE SAUDA_DATE =@sauda_date
GROUP BY SAUDA_DATE, T.PARTY_CODE,  MTFLEDBAL,CLIENT_FUND_AMT

INSERT INTO #DATA
SELECT SAUDA_DATE, T.PARTY_CODE, 
FUDEDVAL =  CONVERT(NUMERIC(18,4),0),
MTOM =  CONVERT(NUMERIC(18,4),0),
MARGIN_REQ =  CONVERT(NUMERIC(18,4),0),
MTFLEDBAL = CONVERT(NUMERIC(18,4),0),  
AVALABLECASH =  CONVERT(NUMERIC(18,4),0),
COLLATERALBHC = SUM(QTY*CL_RATE),
COLLATERALAHC = SUM(QTY*CL_RATE-QTY*CL_RATE*HAIRCUT/100), 
MARGIN_SHORTFALL = CONVERT(NUMERIC(18,4),0)
FROM MTFTRADE.DBO.TBL_PRODUCT_HOLD_DATA T 
WHERE SAUDA_DATE=@sauda_date
AND HOLDFLAG = 'MTFCOLL'
gROUP BY SAUDA_DATE,T.PARTY_CODE 

SELECT REPORTDATE=CONVERT(VARCHAR,SAUDA_DATE,103),
PARTY_CODE,
FUDEDVAL = SUM(FUDEDVAL),
MTOM = SUM(MTOM),
MARGIN_REQ=SUM(MARGIN_REQ),
FUDEDVALAFM = SUM(FUDEDVAL)+SUM(MTOM)-SUM(MARGIN_REQ),
MTFLEDBAL = SUM(MTFLEDBAL),
AVALABLECASH=SUM(AVALABLECASH),
COLLATERALBHC=SUM(COLLATERALBHC),
COLLATERALAHC=SUM(COLLATERALAHC),
MARGIN_SHORTFALL= SUM(MTOM)-SUM(MARGIN_REQ) + SUM(AVALABLECASH) + SUM(COLLATERALAHC),
ORDERBYDATE=SAUDA_DATE 
FROM #DATA 
GROUP BY PARTY_CODE, SAUDA_DATE
ORDER BY PARTY_CODE,ORDERBYDATE

DROP TABLE #DATA

GO
