-- Object: VIEW dbo.LIFE_TIME_AMC_DP
-- Server: 10.253.33.231 | DB: inhouse
--------------------------------------------------


CREATE VIEW [dbo].[LIFE_TIME_AMC_DP]    
AS    
SELECT  DPAM_SBA_NO As DP_ID,CLIDB_EFF_FROM_DT,CLIDB_EFF_TO_DT,DPAM_BBO_CODE,BROK_NAME =(CASE WHEN CLIDB_BROM_ID= '73' THEN 'LIFE 2500' ELSE 'LIFE 1250' END)     
FROM AGMUBODPL3.DMAT.CITRUS_USR.CLIENT_DP_BRKG B,AGMUBODPL3.DMAT.CITRUS_USR.DP_ACCT_MSTR D     
WHERE   CLIDB_BROM_ID IN ('28','29','30','31','73') AND CLIDB_DPAM_ID =DPAM_ID    
AND CLIDB_EFF_TO_DT >GETDATE() AND LEFT(DPAM_SBA_NO,8)='12033200'  
UNION ALL  
SELECT  DPAM_SBA_NO,CLIDB_EFF_FROM_DT,CLIDB_EFF_TO_DT,DPAM_BBO_CODE,BROK_NAME =(CASE WHEN CLIDB_BROM_ID= '73' THEN 'LIFE 2500' ELSE 'LIFE 1250' END)     
FROM AngelDP5.DMAT.CITRUS_USR.CLIENT_DP_BRKG B,AngelDP5.DMAT.CITRUS_USR.DP_ACCT_MSTR D     
WHERE   CLIDB_BROM_ID IN ('28','29','30','31','73') AND CLIDB_DPAM_ID =DPAM_ID    
AND CLIDB_EFF_TO_DT >GETDATE() AND LEFT(DPAM_SBA_NO,8)='12033201'  
UNION ALL  
SELECT  DPAM_SBA_NO,CLIDB_EFF_FROM_DT,CLIDB_EFF_TO_DT,DPAM_BBO_CODE,BROK_NAME =(CASE WHEN CLIDB_BROM_ID= '73' THEN 'LIFE 2500' ELSE 'LIFE 1250' END)     
FROM ANGELDP202.DMAT.CITRUS_USR.CLIENT_DP_BRKG B,ANGELDP202.DMAT.CITRUS_USR.DP_ACCT_MSTR D     
WHERE   CLIDB_BROM_ID IN ('28','29','30','31','73') AND CLIDB_DPAM_ID =DPAM_ID    
AND CLIDB_EFF_TO_DT >GETDATE() AND LEFT(DPAM_SBA_NO,8)='12033202'
UNION ALL  
SELECT  DPAM_SBA_NO,CLIDB_EFF_FROM_DT,CLIDB_EFF_TO_DT,DPAM_BBO_CODE,BROK_NAME =(CASE WHEN CLIDB_BROM_ID= '73' THEN 'LIFE 2500' ELSE 'LIFE 1250' END)     
FROM ABVSDP203.DMAT.CITRUS_USR.CLIENT_DP_BRKG B,ABVSDP203.DMAT.CITRUS_USR.DP_ACCT_MSTR D     
WHERE   CLIDB_BROM_ID IN ('28','29','30','31','73') AND CLIDB_DPAM_ID =DPAM_ID    
AND CLIDB_EFF_TO_DT >GETDATE() AND LEFT(DPAM_SBA_NO,8)='12033203'

GO
