-- Object: PROCEDURE citrus_usr.VW_FILESTATUS_FORANGEL
-- Server: 10.253.33.231 | DB: DMAT
--------------------------------------------------

 --ALTER THIS VIEW UNDER SRE-34226

CREATE PROCEDURE [citrus_usr].[VW_FILESTATUS_FORANGEL]  
AS  
BEGIN  
DELETE FROM FILESTATUS_FORANGEL  
INSERT INTO FILESTATUS_FORANGEL  
SELECT TOP 1  TASK_NAME,  CASE WHEN STATUS='RUNNING' THEN 'Y' ELSE 'N' END FILERUNNINGSTATUS,CASE WHEN STATUS='RUNNING' THEN '' ELSE TASK_END_DATE END    
TASK_END_DATE,TASK_ID  FROM AGMUBODPL3.DMAT.citrus_usr.FILETASK  WHERE TASK_NAME LIKE 'DPM DP57%'  ORDER BY 3 DESC  
INSERT INTO FILESTATUS_FORANGEL   
SELECT TOP 1  TASK_NAME ,CASE WHEN STATUS='RUNNING' THEN 'Y' ELSE 'N' END FILERUNNINGSTATUS,CASE WHEN STATUS='RUNNING' THEN '' ELSE TASK_END_DATE END  TASK_END_DATE,TASK_ID FROM
 AGMUBODPL3.DMAT.citrus_usr.FILETASK  WHERE TASK_NAME LIKE 'CLIENT MASTE%' ORDER BY 3 DESC  
INSERT INTO FILESTATUS_FORANGEL  
SELECT TOP 1 'HOLDING DUMP 'TASK_NAME, CASE WHEN STATUS='START' THEN 'Y' ELSE 'N' END FILERUNNINGSTATUS,CASE WHEN STATUS='START' THEN '' ELSE DT END  TASK_END_DATE,ID TASK_ID 
FROM AGMUBODPL3.DMAT.citrus_usr.HOLDINGDUMPLOG  ORDER BY 3 DESC 


 
INSERT INTO FILESTATUS_FORANGEL  
SELECT TOP 1  TASK_NAME,  CASE WHEN STATUS='RUNNING' THEN 'Y' ELSE 'N' END FILERUNNINGSTATUS,CASE WHEN STATUS='RUNNING' THEN '' ELSE TASK_END_DATE END    
TASK_END_DATE,TASK_ID  FROM AngelDP5.DMAT.citrus_usr.FILETASK  WHERE TASK_NAME LIKE 'DPM DP57%'  ORDER BY 3 DESC  
INSERT INTO FILESTATUS_FORANGEL   
SELECT TOP 1  TASK_NAME ,CASE WHEN STATUS='RUNNING' THEN 'Y' ELSE 'N' END FILERUNNINGSTATUS,CASE WHEN STATUS='RUNNING' THEN '' ELSE TASK_END_DATE END  TASK_END_DATE,TASK_ID FROM
 AngelDP5.DMAT.citrus_usr.FILETASK  WHERE TASK_NAME LIKE 'CLIENT MASTE%' ORDER BY 3 DESC  
INSERT INTO FILESTATUS_FORANGEL  
SELECT TOP 1 'HOLDING DUMP 'TASK_NAME, CASE WHEN STATUS='START' THEN 'Y' ELSE 'N' END FILERUNNINGSTATUS,CASE WHEN STATUS='START' THEN '' ELSE DT END  TASK_END_DATE,ID TASK_ID 
FROM AngelDP5.DMAT.citrus_usr.HOLDINGDUMPLOG  ORDER BY 3 DESC   



INSERT INTO FILESTATUS_FORANGEL  
SELECT TOP 1  TASK_NAME,  CASE WHEN STATUS='RUNNING' THEN 'Y' ELSE 'N' END FILERUNNINGSTATUS,CASE WHEN STATUS='RUNNING' THEN '' ELSE TASK_END_DATE END    
TASK_END_DATE,TASK_ID  FROM ANGELDP202.DMAT.citrus_usr.FILETASK  WHERE TASK_NAME LIKE 'DPM DP57%'  ORDER BY 3 DESC  
INSERT INTO FILESTATUS_FORANGEL   
SELECT TOP 1  TASK_NAME ,CASE WHEN STATUS='RUNNING' THEN 'Y' ELSE 'N' END FILERUNNINGSTATUS,CASE WHEN STATUS='RUNNING' THEN '' ELSE TASK_END_DATE END  TASK_END_DATE,TASK_ID FROM
 ANGELDP202.DMAT.citrus_usr.FILETASK  WHERE TASK_NAME LIKE 'CLIENT MASTE%' ORDER BY 3 DESC  
INSERT INTO FILESTATUS_FORANGEL  
SELECT TOP 1 'HOLDING DUMP 'TASK_NAME, CASE WHEN STATUS='START' THEN 'Y' ELSE 'N' END FILERUNNINGSTATUS,CASE WHEN STATUS='START' THEN '' ELSE DT END  TASK_END_DATE,ID TASK_ID 
FROM ANGELDP202.DMAT.citrus_usr.HOLDINGDUMPLOG  ORDER BY 3 DESC  

  
  INSERT INTO FILESTATUS_FORANGEL  
SELECT TOP 1  TASK_NAME,  CASE WHEN STATUS='RUNNING' THEN 'Y' ELSE 'N' END FILERUNNINGSTATUS,CASE WHEN STATUS='RUNNING' THEN '' ELSE TASK_END_DATE END    
TASK_END_DATE,TASK_ID  FROM ABVSDP203.DMAT.citrus_usr.FILETASK  WHERE TASK_NAME LIKE 'DPM DP57%'  ORDER BY 3 DESC  
INSERT INTO FILESTATUS_FORANGEL   
SELECT TOP 1  TASK_NAME ,CASE WHEN STATUS='RUNNING' THEN 'Y' ELSE 'N' END FILERUNNINGSTATUS,CASE WHEN STATUS='RUNNING' THEN '' ELSE TASK_END_DATE END  TASK_END_DATE,TASK_ID FROM
 ABVSDP203.DMAT.citrus_usr.FILETASK  WHERE TASK_NAME LIKE 'CLIENT MASTE%' ORDER BY 3 DESC  
INSERT INTO FILESTATUS_FORANGEL  
SELECT TOP 1 'HOLDING DUMP 'TASK_NAME, CASE WHEN STATUS='START' THEN 'Y' ELSE 'N' END FILERUNNINGSTATUS,CASE WHEN STATUS='START' THEN '' ELSE DT END  TASK_END_DATE,ID TASK_ID 
FROM ABVSDP203.DMAT.citrus_usr.HOLDINGDUMPLOG  ORDER BY 3 DESC  

  INSERT INTO FILESTATUS_FORANGEL  
SELECT TOP 1  TASK_NAME,  CASE WHEN STATUS='RUNNING' THEN 'Y' ELSE 'N' END FILERUNNINGSTATUS,CASE WHEN STATUS='RUNNING' THEN '' ELSE TASK_END_DATE END    
TASK_END_DATE,TASK_ID  FROM ABVSDP204.DMAT.citrus_usr.FILETASK  WHERE TASK_NAME LIKE 'DPM DP57%'  ORDER BY 3 DESC  
INSERT INTO FILESTATUS_FORANGEL   
SELECT TOP 1  TASK_NAME ,CASE WHEN STATUS='RUNNING' THEN 'Y' ELSE 'N' END FILERUNNINGSTATUS,CASE WHEN STATUS='RUNNING' THEN '' ELSE TASK_END_DATE END  TASK_END_DATE,TASK_ID FROM
 ABVSDP204.DMAT.citrus_usr.FILETASK  WHERE TASK_NAME LIKE 'CLIENT MASTE%' ORDER BY 3 DESC  
INSERT INTO FILESTATUS_FORANGEL  
SELECT TOP 1 'HOLDING DUMP 'TASK_NAME, CASE WHEN STATUS='START' THEN 'Y' ELSE 'N' END FILERUNNINGSTATUS,CASE WHEN STATUS='START' THEN '' ELSE DT END  TASK_END_DATE,ID TASK_ID 
FROM ABVSDP204.DMAT.citrus_usr.HOLDINGDUMPLOG  ORDER BY 3 DESC  




SELECT * FROM FILESTATUS_FORANGEL  
END

GO
