-- Object: PROCEDURE citrus_usr.USP_GET_ALL_CLIENT_DP_REPORT_IPARTNER
-- Server: 10.253.33.231 | DB: DMAT
--------------------------------------------------


 --ALTER THIS VIEW UNDER SRE-34226

CREATE Procedure [citrus_usr].[USP_GET_ALL_CLIENT_DP_REPORT_IPARTNER] (@SUB_BROKER VARCHAR(100))
As
CREATE TABLE #SB 
(  CLIENT_ID  VARCHAR(18), 
  FIRST_HOLD_NAME    VARCHAR(100) 
 ,DPID   VARCHAR(18) 
 ,POA_VER    VARCHAR(18) 
 ,ACTIVE_DATE  VARCHAR(25) 
 ,AMC_SCHEME     VARCHAR(50) 
 ,DP_LEDGER    VARCHAR(18)  
 ,ACCRUAL_CHARGES     VARCHAR(18) 
 ,ACCOUNT_STATUS    VARCHAR(25) 
 ,CLIENT_SUB_TYPE    VARCHAR(100) 
 , DATE_OF_BIRTH    VARCHAR(25) 
 ,NOMINEE    VARCHAR(50) )  



 INSERT INTO #SB
 EXEC AGMUBODPL3.DMAT.dbo.USP_GET_ALL_CLIENT_DP_REPORT_IPARTNER  @SUB_BROKER
 
 INSERT INTO #SB
 EXEC AngelDP5.DMAT.dbo.USP_GET_ALL_CLIENT_DP_REPORT_IPARTNER @SUB_BROKER
 
 INSERT INTO #SB
 EXEC Angeldp202.DMAT.dbo.USP_GET_ALL_CLIENT_DP_REPORT_IPARTNER @SUB_BROKER
  INSERT INTO #SB
 EXEC ABVSDP203.DMAT.dbo.USP_GET_ALL_CLIENT_DP_REPORT_IPARTNER @SUB_BROKER

 INSERT INTO #SB
 EXEC ABVSDP204.DMAT.dbo.USP_GET_ALL_CLIENT_DP_REPORT_IPARTNER @SUB_BROKER


 SELECT * FROM #SB ORDER BY CLIENT_ID

GO
