-- Object: PROCEDURE citrus_usr.AMCDATE
-- Server: 10.253.33.231 | DB: DMAT
--------------------------------------------------

 --ALTER THIS VIEW UNDER SRE-34226
CREATE PROC  [citrus_usr].[AMCDATE] (@NO_OF_DAYS INT)  
AS

CREATE TABLE #AMC_DATA
(CLIENT_CODE VARCHAR(16),NISE_PARTY_CODE VARCHAR(15),AMC_CHARGE INT,NEXT_AMC_DATE DATETIME)

INSERT INTO #AMC_DATA
EXEC AGMUBODPL3.DMAT.CITRUS_USR.AMCDATE @NO_OF_DAYS

INSERT INTO #AMC_DATA
EXEC AngelDP5.DMAT.CITRUS_USR.AMCDATE @NO_OF_DAYS

INSERT INTO #AMC_DATA
EXEC Angeldp202.DMAT.CITRUS_USR.AMCDATE @NO_OF_DAYS

INSERT INTO #AMC_DATA
EXEC ABVSDP203.DMAT.CITRUS_USR.AMCDATE @NO_OF_DAYS

INSERT INTO #AMC_DATA
EXEC ABVSDP204.DMAT.CITRUS_USR.AMCDATE @NO_OF_DAYS


SELECT * FROM #AMC_DATA WITH(NOLOCK)

GO
