-- Object: VIEW citrus_usr.DP_TRX_DTLS_CDSL
-- Server: 10.253.33.231 | DB: DMAT
--------------------------------------------------


 --ALTER THIS VIEW UNDER SRE-34226


CREATE VIEW [citrus_usr].[DP_TRX_DTLS_CDSL]
AS 
 
SELECT * FROM  AngelDP5.DMAT.CITRUS_USR.DP_TRX_DTLS_CDSL WITH(NOLOCK)  
UNION ALL
SELECT * FROM  AGMUBODPL3.DMAT.CITRUS_USR.DP_TRX_DTLS_CDSL WITH(NOLOCK) 
UNION ALL
SELECT * FROM  angeldp202.DMAT.CITRUS_USR.DP_TRX_DTLS_CDSL WITH(NOLOCK) 
Union all
Select * from ABVSDP203.dMAT.CITRUS_USR.DP_TRX_DTLS_CDSL WITH(NOLOCK) 
Union all
Select * from ABVSDP204.dMAT.CITRUS_USR.DP_TRX_DTLS_CDSL WITH(NOLOCK)

GO
