-- Object: TABLE citrus_usr.FIN_GROUP_MSTR
-- Server: 10.253.33.227 | DB: DMAT
--------------------------------------------------

CREATE TABLE [citrus_usr].[FIN_GROUP_MSTR]
(
    [FINGM_GROUP_CODE] NUMERIC(10, 0) NOT NULL,
    [FINGM_GROUP_NAME] VARCHAR(50) NOT NULL,
    [FINGM_CREATED_BY] VARCHAR(25) NOT NULL,
    [FINGM_CREATED_DT] DATETIME NOT NULL,
    [FINGM_LST_UPD_BY] VARCHAR(25) NOT NULL,
    [FINGM_LST_UPD_DT] DATETIME NOT NULL,
    [FINGM_DELETED_IND] SMALLINT NOT NULL
);

GO
