-- Object: TABLE citrus_usr.TMP_DPMVR_RESPONSE
-- Server: 10.253.33.227 | DB: DMAT
--------------------------------------------------

CREATE TABLE [citrus_usr].[TMP_DPMVR_RESPONSE]
(
    [TMPDPMVR_BATCHNO] VARCHAR(7) NULL,
    [TMPDPMVR_RECTYP] VARCHAR(2) NULL,
    [TMPDPMVR_LINENO] VARCHAR(5) NULL,
    [TMPDPMVR_TRANTYP] VARCHAR(3) NULL,
    [TMPDPMVR_TRANFLG] VARCHAR(25) NULL,
    [TMPDPMVR_INSTID] NUMERIC(18, 0) NULL,
    [TMPDPMVR_SENDREFNO1] VARCHAR(35) NULL,
    [TMPDPMVR_SENDREFNO2] VARCHAR(35) NULL,
    [TMPDPMVR_TRANSTAT] VARCHAR(25) NULL,
    [TMPDPMVR_INTREFNO] VARCHAR(20) NULL,
    [TMPDPMVR_FILLER] VARCHAR(20) NULL
);

GO
