-- Object: PROCEDURE citrus_usr.VW_CLIENT_DETAILS_ForDp1
-- Server: 10.253.33.227 | DB: DMAT
--------------------------------------------------






CREATE PROCEDURE [citrus_usr].[VW_CLIENT_DETAILS_ForDp1]
AS




	SELECT * INTO #CLIENT_DETAILS FROM [AngelNseCM].MSAJAG.DBO.CLIENT_details

	CREATE CLUSTERED INDEX PARTY ON #CLIENT_DETAILS
	(
	PARTY_CODE ASC
	)


SELECT * INTO #MULTICLTID_NSE FROM [ANGELDEMAT].MSAJAG.DBO.MULTICLTID

CREATE CLUSTERED INDEX PARTY_BSE ON #MULTICLTID_NSE
(
PARTY_CODE ASC
)


SELECT * INTO #MULTICLTID_BSE FROM [ANGELDEMAT].BSEDB.DBO.MULTICLTID

CREATE CLUSTERED INDEX PARTY_BSE ON #MULTICLTID_BSE
(
PARTY_CODE ASC
)

SELECT      
CD.CL_CODE ,CD.REGION,CD.BRANCH_CD,CD.SUB_BROKER,CD.AREA,CD.TRADER,CD.FAMILY,M.CLTDPNO as client_code,M.DEF      
FROM #CLIENT_DETAILS CD      
INNER JOIN #MULTICLTID_NSE M ON CD.CL_CODE=M.PARTY_CODE      
WHERE M.DPTYPE='CDSL'     
  
UNION    
SELECT      
CD1.CL_CODE,CD1.REGION,CD1.BRANCH_CD,CD1.SUB_BROKER,CD1.AREA,CD1.TRADER,CD1.FAMILY,M1.CLTDPNO as client_code,M1.DEF      
FROM #CLIENT_DETAILS CD1      
INNER JOIN #MULTICLTID_BSE M1 ON CD1.CL_CODE=M1.PARTY_CODE      
WHERE M1.DPTYPE='CDSL'

GO
