-- Object: TABLE citrus_usr.DP_HLDG_DTLS
-- Server: 10.253.33.227 | DB: DMAT
--------------------------------------------------

CREATE TABLE [citrus_usr].[DP_HLDG_DTLS]
(
    [DPHD_ID] NUMERIC(10, 0) NOT NULL,
    [DPHD_DPAM_ID] NUMERIC(10, 0) NOT NULL,
    [DPHD_ISIN] VARCHAR(20) NOT NULL,
    [DPHD_TRATM_ID] NUMERIC(10, 0) NOT NULL,
    [DPHD_HOLDING_DT] DATETIME NOT NULL,
    [DPHD_CREATED_BY] VARCHAR(20) NOT NULL,
    [DPHD_CREATED_DT] DATETIME NOT NULL,
    [DPHD_LST_UPD_BY] VARCHAR(20) NOT NULL,
    [DPHD_LST_UPD_DT] DATETIME NOT NULL,
    [DPHD_DELETED_IND ] SMALLINT NOT NULL
);

GO
