-- Object: TABLE citrus_usr.CLIENT_DP_BRKG_HST
-- Server: 10.253.33.227 | DB: DMAT
--------------------------------------------------

CREATE TABLE [citrus_usr].[CLIENT_DP_BRKG_HST]
(
    [CLIDB_BROM_ID] DECIMAL(10, 0) NOT NULL,
    [CLIDB_CREATED_BY] VARCHAR(25) NOT NULL,
    [CLIDB_CREATED_DT] DATETIME NOT NULL,
    [CLIDB_LST_UPD_BY] VARCHAR(25) NOT NULL,
    [CLIDB_LST_UPD_DT] DATETIME NOT NULL,
    [CLIDB_DELETED_IND] SMALLINT NOT NULL
);

GO
