-- Object: PROCEDURE citrus_usr.Pr_POA_Mstr
-- Server: 10.253.33.227 | DB: DMAT
--------------------------------------------------

--EXEC PR_POA_MSTR ''
CREATE PROCEDURE [citrus_usr].[Pr_POA_Mstr]
(@PA_LOGIN_NAME VARCHAR(11))
AS
BEGIN


SELECT DISTINCT POAM_MASTER_ID FROM POA_MSTR WHERE POAM_DELETED_IND=1
UNION ALL
SELECT DISTINCT DPAM_SBA_NO FROM DP_ACCT_MSTR WHERE DPAM_DELETED_IND=1 AND LEFT(DPAM_SBA_NO,1)='2'
AND NOT EXISTS (SELECT DISTINCT POAM_MASTER_ID FROM POA_MSTR WHERE POAM_DELETED_IND=1 AND POAM_MASTER_ID=DPAM_SBA_NO)
UNION ALL
SELECT 'NSE POA'
UNION ALL
SELECT  'BSE POA'
UNION ALL
SELECT 'MARGIN'

END

GO
