-- Object: PROCEDURE citrus_usr.AGEING_SSIS_RPT
-- Server: 10.253.33.227 | DB: DMAT
--------------------------------------------------

  
---AGEING_SSIS_RPT 'aug 31 2021'  
  
CREATE procedure  AGEING_SSIS_RPT  
(@DATE DATETIME)  
AS   
BEGIN   
  
 create table  #temp   
( CLTCODE VARCHAR(25),  
  BALAMT MONEY,  
  CR007Total MONEY,DR007Total MONEY,CR015Total MONEY,DR015Total MONEY ,CR030Total MONEY,DR030Total MONEY,  
  CR060Total MONEY,  
  DR060Total MONEY,  
  CR090Total MONEY,  
  DR090Total MONEY,  
  CR180Total MONEY,  
  DR180Total MONEY,  
  CR360Total MONEY,  
  DR360Total MONEY,  
  CR720Total MONEY,  
  DR720Total MONEY,  
  CR1080Total MONEY,  
  DR1080Total MONEY,  
  CR1081Total MONEY,  
  DR1081Total MONEY  
     )  
  
 CREATE NONCLUSTERED INDEX #T ON #temp  
 (CLTCODE ASC )  
  
 --DECLARE @DATE DATETIME  
 --SET @DATE=@DATE  
   
     CREATE NONCLUSTERED INDEX #CLI_CODE ON TBL_AGEING_SSRS_DATA  
(CLIENT_CODE ASC ) 
  
INSERT INTO #temp  
select LD_CLIENTCD,BALAMT=SUM(LD_AMOUNT*-1),  
  CR007Total=SUM(case when LD_AMOUNT >0 and LD_DT > @DATE-08 then LD_AMOUNT else 0 end),  
  DR007Total=SUM(case when LD_AMOUNT <0 and LD_DT > @DATE-08 then -LD_AMOUNT else 0 end),  
  CR015Total=SUM(case when LD_AMOUNT >0 and LD_DT <= @DATE-08 and LD_DT > @DATE-16 then LD_AMOUNT else 0 end),  
  DR015Total=SUM(case when LD_AMOUNT <0 and LD_DT <= @DATE-08 and LD_DT > @DATE-16 then -LD_AMOUNT else 0 end),  
  CR030Total=SUM(case when LD_AMOUNT >0 and LD_DT <= @DATE-16 and LD_DT > @DATE-31 then LD_AMOUNT else 0 end),  
  DR030Total=SUM(case when LD_AMOUNT <0 and LD_DT <= @DATE-16 and LD_DT > @DATE-31 then -LD_AMOUNT else 0 end),  
  CR060Total=SUM(case when LD_AMOUNT >0 and LD_DT <= @DATE-31 and LD_DT > @DATE-61 then LD_AMOUNT else 0 end),  
  DR060Total=SUM(case when LD_AMOUNT <0 and LD_DT <= @DATE-31 and LD_DT > @DATE-61 then -LD_AMOUNT else 0 end),  
  CR090Total=SUM(case when LD_AMOUNT >0 and LD_DT <= @DATE-61 and LD_DT > @DATE-91 then LD_AMOUNT else 0 end),  
  DR090Total=SUM(case when LD_AMOUNT <0 and LD_DT <= @DATE-61 and LD_DT > @DATE-91 then -LD_AMOUNT else 0 end),  
  CR180Total=SUM(case when LD_AMOUNT >0 and LD_DT <= @DATE-91 and LD_DT > @DATE-181 then LD_AMOUNT else 0 end),  
  DR180Total=SUM(case when LD_AMOUNT <0 and LD_DT <= @DATE-91 and LD_DT > @DATE-181 then -LD_AMOUNT else 0 end),  
  CR360Total=SUM(case when LD_AMOUNT >0 and LD_DT <= @DATE-181 and LD_DT > @DATE-360 then LD_AMOUNT else 0 end),  
  DR360Total=SUM(case when LD_AMOUNT <0 and LD_DT <= @DATE-181 and LD_DT > @DATE-360 then -LD_AMOUNT else 0 end)  ,  
  
  CR720Total=SUM(case when LD_AMOUNT >0 and LD_DT <= @DATE-361 and LD_DT > @DATE-720 then LD_AMOUNT else 0 end),  
  DR720Total=SUM(case when LD_AMOUNT <0 and LD_DT <= @DATE-361 and LD_DT > @DATE-720 then -LD_AMOUNT else 0 end)  ,  
  
  CR1080Total=SUM(case when LD_AMOUNT >0 and LD_DT <= @DATE-721 and LD_DT > @DATE-1080 then LD_AMOUNT else 0 end),  
  DR1080Total=SUM(case when LD_AMOUNT <0 and LD_DT <= @DATE-721 and LD_DT > @DATE-1080 then -LD_AMOUNT else 0 end)  ,  
  
  CR1081Total=SUM(case when LD_AMOUNT >0 and LD_DT <= @DATE-1081 then LD_AMOUNT else 0 end),  
  DR1081Total=SUM(case when LD_AMOUNT <0 and LD_DT <= @DATE-1081 then -LD_AMOUNT else 0 end)   
  FROM (SELECT LD_CLIENTCD,LD_AMOUNT,LD_DT   FROM SYNERGY_LEDGER WITH(NOLOCK) WHERE LD_DT <=@DATE  
AND LD_CLIENTCD LIKE '120332%'  
UNION ALL  
SELECT CLIENT_CODE,amount,LD_DT FROM TBL_AGEING_SSRS_DATA  WITH(NOLOCK)  
   ) A  
GROUP BY LD_CLIENTCD  
   
   
   
   
   
   
    
   
  
SELECT CLTCODE,SUM(BALAMT) BALAMT,SUM(CR007Total) CR007Total,SUM(DR007Total) DR007Total,SUM(CR015Total) CR015Total,SUM(DR015Total) DR015Total,  
SUM(CR030Total) CR030Total,SUM(DR030Total) DR030Total,  
SUM(CR060Total) CR060Total,SUM(DR060Total) DR060Total,SUM(CR090Total)CR090Total,SUM(DR090Total)DR090Total,SUM(CR180Total)CR180Total,SUM(DR180Total)DR180Total,  
SUM(CR360Total)CR360Total,SUM(DR360Total) DR360Total ,SUM(CR720Total)CR720Total,SUM(DR720Total) DR720Total  
  
,SUM(CR1080Total)CR1080Total,SUM(DR1080Total) DR1080Total  
,SUM(CR1081Total)CR1081Total,SUM(DR1081Total) DR1081Total  
 INTO #TOTAL  
  FROM #temp T  
  GROUP BY CLTCODE  
  
    CREATE NONCLUSTERED INDEX #CL_CODE ON #TOTAL  
 (CLTCODE ASC )  
  
     
 CREATE TABLE #DEBTORS  
 (CLTCODE VARCHAR(18),  
  NET_LD_DOCUMENTTYPE MONEY,DAY7 MONEY,DAY15 MONEY,DAY30  MONEY,DAY60  MONEY, DAY90 MONEY,DAY180 MONEY, DAY360 MONEY, DAY720 MONEY, DAY1080 MONEY, DAY1081 MONEY)  
  
   CREATE NONCLUSTERED INDEX #D ON #DEBTORS  
 (CLTCODE ASC )  
   
 INSERT INTO #DEBTORS (CLTCODE,NET_LD_DOCUMENTTYPE)  
  SELECT CLTCODE,BALAMT  FROM #TOTAL   WHERE BALAMT > 0    
     
   UPDATE #DEBTORS SET DAY7=  
    (CASE WHEN NET_LD_DOCUMENTTYPE <= DR007TOTAL THEN NET_LD_DOCUMENTTYPE ELSE DR007TOTAL END)    
    FROM  #TOTAL B     
    WHERE #DEBTORS.CLTCODE=B.CLTCODE AND NET_LD_DOCUMENTTYPE > 0     
      
    --15  
    UPDATE #DEBTORS SET DAY15=  
    (CASE WHEN NET_LD_DOCUMENTTYPE-DAY7 >= DR015TOTAL THEN DR015TOTAL ELSE NET_LD_DOCUMENTTYPE-DAY7 END)    
    FROM  #TOTAL B     
    WHERE #DEBTORS.CLTCODE=B.CLTCODE AND NET_LD_DOCUMENTTYPE > 0     
      
    --30  
    UPDATE #DEBTORS SET DAY30=  
    (CASE WHEN NET_LD_DOCUMENTTYPE-(DAY7+DAY15) >= DR030TOTAL THEN DR030TOTAL ELSE NET_LD_DOCUMENTTYPE-(DAY7+DAY15) END)    
    FROM  #TOTAL B     
    WHERE #DEBTORS.CLTCODE=B.CLTCODE AND NET_LD_DOCUMENTTYPE > 0     
      
      --60  
    UPDATE #DEBTORS SET DAY60=  
    (CASE WHEN NET_LD_DOCUMENTTYPE-(DAY7+DAY15+DAY30) >= DR060TOTAL THEN DR060TOTAL ELSE NET_LD_DOCUMENTTYPE-(DAY7+DAY15+DAY30) END)    
    FROM  #TOTAL B     
    WHERE #DEBTORS.CLTCODE=B.CLTCODE AND NET_LD_DOCUMENTTYPE > 0     
      
      --90  
    UPDATE #DEBTORS SET DAY90=  
    (CASE WHEN NET_LD_DOCUMENTTYPE-(DAY7+DAY15+DAY30+DAY60) >= DR090TOTAL THEN DR090TOTAL ELSE NET_LD_DOCUMENTTYPE-(DAY7+DAY15+DAY30+DAY60) END)    
    FROM  #TOTAL B     
    WHERE #DEBTORS.CLTCODE=B.CLTCODE AND NET_LD_DOCUMENTTYPE > 0     
      
      --180  
    UPDATE #DEBTORS SET DAY180=  
    (CASE WHEN NET_LD_DOCUMENTTYPE-(DAY7+DAY15+DAY30+DAY60+DAY90) >= DR180TOTAL   
    THEN DR180TOTAL ELSE NET_LD_DOCUMENTTYPE-(DAY7+DAY15+DAY30+DAY60+DAY90) END)    
    FROM  #TOTAL B     
    WHERE #DEBTORS.CLTCODE=B.CLTCODE AND NET_LD_DOCUMENTTYPE > 0     
      
      --360  
    UPDATE #DEBTORS SET DAY360=  
    (CASE WHEN NET_LD_DOCUMENTTYPE-(DAY7+DAY15+DAY30+DAY60+DAY90+DAY180) >= DR360TOTAL   
    THEN DR360TOTAL ELSE NET_LD_DOCUMENTTYPE-(DAY7+DAY15+DAY30+DAY60+DAY90+DAY180) END)    
    FROM  #TOTAL B     
    WHERE #DEBTORS.CLTCODE=B.CLTCODE AND NET_LD_DOCUMENTTYPE > 0    
      
          --720  
    UPDATE #DEBTORS SET DAY720=  
    (CASE WHEN NET_LD_DOCUMENTTYPE-(DAY7+DAY15+DAY30+DAY60+DAY90+DAY180+DAY360) >= DR720TOTAL   
    THEN DR720TOTAL ELSE NET_LD_DOCUMENTTYPE-(DAY7+DAY15+DAY30+DAY60+DAY90+DAY180+DAY360) END)    
    FROM  #TOTAL B     
    WHERE #DEBTORS.CLTCODE=B.CLTCODE AND NET_LD_DOCUMENTTYPE > 0    
  
  
          --1080  
    UPDATE #DEBTORS SET DAY1080=  
    (CASE WHEN NET_LD_DOCUMENTTYPE-(DAY7+DAY15+DAY30+DAY60+DAY90+DAY180+DAY360+DAY720) >= DR1080TOTAL   
    THEN DR1080TOTAL ELSE NET_LD_DOCUMENTTYPE-(DAY7+DAY15+DAY30+DAY60+DAY90+DAY180+DAY360+DAY720) END)    
    FROM  #TOTAL B     
    WHERE #DEBTORS.CLTCODE=B.CLTCODE AND NET_LD_DOCUMENTTYPE > 0    
  
  
          --1081  
    UPDATE #DEBTORS SET DAY1081=  
    (CASE WHEN NET_LD_DOCUMENTTYPE-(DAY7+DAY15+DAY30+DAY60+DAY90+DAY180+DAY360+DAY720+DAY1080) >= DR1081TOTAL   
    THEN DR1081TOTAL ELSE NET_LD_DOCUMENTTYPE-(DAY7+DAY15+DAY30+DAY60+DAY90+DAY180+DAY360+DAY720+DAY1080) END)    
    FROM  #TOTAL B     
    WHERE #DEBTORS.CLTCODE=B.CLTCODE AND NET_LD_DOCUMENTTYPE > 0    
  
  
         
  
   
    
  -----------CREDITORS  
   
  
    
 CREATE TABLE #CREDITORS  
 (CLTCODE VARCHAR(18),  
  NET_LD_DOCUMENTTYPE MONEY,DAY7 MONEY,DAY15 MONEY,DAY30  MONEY,DAY60  MONEY, DAY90 MONEY,DAY180 MONEY, DAY360 MONEY, DAY720 MONEY, DAY1080 MONEY, DAY1081 MONEY)  
  
   CREATE NONCLUSTERED INDEX #D ON #CREDITORS  
 (CLTCODE ASC )  
  
   INSERT INTO #CREDITORS (CLTCODE,NET_LD_DOCUMENTTYPE)  
  SELECT CLTCODE,BALAMT*-1  FROM #TOTAL   WHERE BALAMT < 0     
  
   
     
    UPDATE #CREDITORS SET DAY7=  
    (CASE WHEN NET_LD_DOCUMENTTYPE <= CR007TOTAL THEN NET_LD_DOCUMENTTYPE ELSE CR007TOTAL END)    
    FROM  #TOTAL B     
    WHERE #CREDITORS.CLTCODE=B.CLTCODE AND NET_LD_DOCUMENTTYPE > 0     
      
    --15  
    UPDATE #CREDITORS SET DAY15=  
    (CASE WHEN NET_LD_DOCUMENTTYPE-DAY7 >= CR015TOTAL THEN CR015TOTAL ELSE NET_LD_DOCUMENTTYPE-DAY7 END)    
    FROM  #TOTAL B     
    WHERE #CREDITORS.CLTCODE=B.CLTCODE AND NET_LD_DOCUMENTTYPE  > 0     
      
    --30  
    UPDATE #CREDITORS SET DAY30=  
    (CASE WHEN NET_LD_DOCUMENTTYPE-(DAY7+DAY15) >= CR030TOTAL THEN CR030TOTAL ELSE NET_LD_DOCUMENTTYPE-(DAY7+DAY15) END)    
    FROM  #TOTAL B     
    WHERE #CREDITORS.CLTCODE=B.CLTCODE AND NET_LD_DOCUMENTTYPE  > 0     
      
      --60  
    UPDATE #CREDITORS SET DAY60=  
    (CASE WHEN NET_LD_DOCUMENTTYPE-(DAY7+DAY15+DAY30) >= CR060TOTAL THEN CR060TOTAL ELSE NET_LD_DOCUMENTTYPE-(DAY7+DAY15+DAY30) END)    
    FROM  #TOTAL B     
    WHERE #CREDITORS.CLTCODE=B.CLTCODE AND NET_LD_DOCUMENTTYPE  > 0     
      
      --90  
    UPDATE #CREDITORS SET DAY90=  
    (CASE WHEN NET_LD_DOCUMENTTYPE-(DAY7+DAY15+DAY30+DAY60) >= CR090TOTAL THEN CR090TOTAL ELSE NET_LD_DOCUMENTTYPE-(DAY7+DAY15+DAY30+DAY60) END)    
    FROM  #TOTAL B     
    WHERE #CREDITORS.CLTCODE=B.CLTCODE AND NET_LD_DOCUMENTTYPE  > 0     
      
      --180  
    UPDATE #CREDITORS SET DAY180=  
    (CASE WHEN NET_LD_DOCUMENTTYPE-(DAY7+DAY15+DAY30+DAY60+DAY90) >= CR180TOTAL   
    THEN CR180TOTAL ELSE NET_LD_DOCUMENTTYPE-(DAY7+DAY15+DAY30+DAY60+DAY90) END)    
    FROM  #TOTAL B     
    WHERE #CREDITORS.CLTCODE=B.CLTCODE AND NET_LD_DOCUMENTTYPE  > 0     
      
      --360  
    UPDATE #CREDITORS SET DAY360=  
    (CASE WHEN NET_LD_DOCUMENTTYPE-(DAY7+DAY15+DAY30+DAY60+DAY90+DAY180) >= CR360TOTAL   
    THEN CR360TOTAL ELSE NET_LD_DOCUMENTTYPE-(DAY7+DAY15+DAY30+DAY60+DAY90+DAY180) END)    
    FROM  #TOTAL B     
    WHERE #CREDITORS.CLTCODE=B.CLTCODE AND NET_LD_DOCUMENTTYPE  > 0     
      
          --720  
    UPDATE #CREDITORS SET DAY720=  
    (CASE WHEN NET_LD_DOCUMENTTYPE-(DAY7+DAY15+DAY30+DAY60+DAY90+DAY180+DAY360+DAY720) >= CR720TOTAL   
    THEN CR720TOTAL ELSE NET_LD_DOCUMENTTYPE-(DAY7+DAY15+DAY30+DAY60+DAY90+DAY180+DAY360+DAY720) END)    
    FROM  #TOTAL B     
    WHERE #CREDITORS.CLTCODE=B.CLTCODE AND NET_LD_DOCUMENTTYPE > 0     
  
  
        --720  
    UPDATE #CREDITORS SET DAY720=  
    (CASE WHEN NET_LD_DOCUMENTTYPE-(DAY7+DAY15+DAY30+DAY60+DAY90+DAY180+DAY360) >= CR720TOTAL   
    THEN CR720TOTAL ELSE NET_LD_DOCUMENTTYPE-(DAY7+DAY15+DAY30+DAY60+DAY90+DAY180+DAY360) END)    
    FROM  #TOTAL B     
    WHERE #CREDITORS.CLTCODE=B.CLTCODE AND NET_LD_DOCUMENTTYPE > 0     
  
        --1080  
    UPDATE #CREDITORS SET DAY1080=  
    (CASE WHEN NET_LD_DOCUMENTTYPE-(DAY7+DAY15+DAY30+DAY60+DAY90+DAY180+DAY360+DAY720) >= CR1080TOTAL   
    THEN CR1080TOTAL ELSE NET_LD_DOCUMENTTYPE-(DAY7+DAY15+DAY30+DAY60+DAY90+DAY180+DAY360+DAY720) END)    
    FROM  #TOTAL B     
    WHERE #CREDITORS.CLTCODE=B.CLTCODE AND NET_LD_DOCUMENTTYPE > 0    
      
     --1081  
    UPDATE #CREDITORS SET DAY1081=  
    (CASE WHEN NET_LD_DOCUMENTTYPE-(DAY7+DAY15+DAY30+DAY60+DAY90+DAY180+DAY360+DAY720+DAY1080) >= CR1081TOTAL   
    THEN CR1081TOTAL ELSE NET_LD_DOCUMENTTYPE-(DAY7+DAY15+DAY30+DAY60+DAY90+DAY180+DAY360+DAY720+DAY1080) END)    
    FROM  #TOTAL B     
    WHERE #CREDITORS.CLTCODE=B.CLTCODE AND NET_LD_DOCUMENTTYPE > 0     
  
      
  
       
  
 SELECT * INTO #HOLD1 FROM SYNERGY_HOLDING WITH(NOLOCK) WHERE HLD_HOLD_DATE =@DATE  
 CREATE NONCLUSTERED INDEX #D ON #HOLD1  
(HLD_AC_CODE ASC ,HLD_ISIN_CODE ASC ) 
  
  
  
  SELECT V.* INTO #CLOSIN1 FROM  VW_ISIN_RATE_MASTER V WITH(NOLOCK),  
  (SELECT ISIN,MAX(RATE_DATE) AS RD FROM  VW_ISIN_RATE_MASTER WITH(NOLOCK)  WHERE  RATE_DATE <=@DATE GROUP BY ISIN ) B  
  WHERE  RATE_DATE <=@DATE AND V.ISIN=B.ISIN AND RD=RATE_DATE  
  
   CREATE NONCLUSTERED INDEX #D ON #CLOSIN1  
(ISIN ASC ) 
  
  
  
  SELECT HLD_AC_CODE,SUM(HLD_AC_POS*CLOSE_PRICE)VALUE INTO #HOLDING FROM #HOLD1 H, #CLOSIN1 WHERE ISIN=HLD_ISIN_CODE  GROUP BY HLD_AC_CODE  
  
ALTER TABLE  #CREDITORS  
ADD VALUATION MONEY  
ALTER TABLE  #DEBTORS  
ADD VALUATION MONEY  
  
  
UPDATE #DEBTORS SET VALUATION= VALUE   FROM #HOLDING WHERE   CLTCODE=HLD_AC_CODE  
  
SELECT *,DEF=(CASE WHEN ISNULL(VALUATION,0)>NET_LD_DOCUMENTTYPE THEN 'Secured' else 'RISK' END),'DEBTORS'as TYPE  INTO AGEING_REPORT_DATA FROM #DEBTORS  
UNION ALL  
SELECT *,DEF=(CASE WHEN ISNULL(VALUATION,0)>NET_LD_DOCUMENTTYPE THEN 'Secured' else 'RISK' END),'CREDITORS'AS TYPE FROM #CREDITORS  

    END

GO
