-- Object: PROCEDURE citrus_usr.PR_FIX_LENGTH
-- Server: 10.253.33.227 | DB: DMAT
--------------------------------------------------

--CREATE TABLE TBL_PRINTING(FLD VARCHAR(100),COL NUMERIC, ROW NUMERIC)
--SELECT * FROM TBL_PRINTING 
--SELECT * FROM TBL_PRINTING  WHERE FLD LIKE 'CLIID9%'
--EXEC PR_FIX_LENGTH 'ROW','CLIID9',''
--EXEC PR_FIX_LENGTH '89754688','CLIID',''
--SELECT @L_ROW = ROW FROM TBL_PRINTING WHERE FLD LIKE CLIID9+'%'

CREATE PROCEDURE [citrus_usr].[PR_FIX_LENGTH](@PA_VALUE VARCHAR(1000),@PA_FLD VARCHAR(100),@PA_OUTPUT VARCHAR(1000) OUT)
AS
BEGIN 

DECLARE @L_ROW NUMERIC
SET @L_ROW = 0
IF @PA_VALUE = 'ROW'
BEGIN 
SELECT @L_ROW = ROW FROM TBL_PRINTING WHERE FLD LIKE @PA_FLD+'%'
SELECT @L_ROW
END 
ELSE 
BEGIN

DECLARE @L_COL NUMERIC
DECLARE @L_LEN NUMERIC

IF @PA_FLD ='CLIID'
BEGIN 



DECLARE @L_VAL VARCHAR(100)

SET @L_VAL  = ''
SET @L_COL = 0 
SELECT @L_COL = COL FROM TBL_PRINTING WHERE FLD = 'CLIID9'
SELECT @L_LEN  = @L_COL - LEN('1')

DECLARE @L_ID NUMERIC 

SET @L_ID = 1
WHILE @L_ID <= 8
BEGIN 

 SET @L_VAL = @L_VAL + CASE WHEN @L_ID = 1 THEN SUBSTRING(@PA_VALUE , 1, 1)
WHEN @L_ID = 2 THEN SUBSTRING(@PA_VALUE , 2, 1)
WHEN @L_ID = 3 THEN SUBSTRING(@PA_VALUE , 3, 1)
WHEN @L_ID = 4 THEN SUBSTRING(@PA_VALUE , 4, 1)
WHEN @L_ID = 5 THEN SUBSTRING(@PA_VALUE , 5, 1)
WHEN @L_ID = 6 THEN SUBSTRING(@PA_VALUE , 6, 1)
WHEN @L_ID = 7 THEN SUBSTRING(@PA_VALUE , 7, 1)
WHEN @L_ID = 8 THEN SUBSTRING(@PA_VALUE , 8, 1)
END + '|||'--SPACE(3)

 SET @L_ID = @L_ID + 1 
END 

SELECT  replace(SPACE(@L_LEN),' ','|') + @L_VAL



END 
ELSE 
BEGIN
 


SET @L_COL = 0 
SELECT @L_COL = COL FROM TBL_PRINTING WHERE FLD = @PA_FLD
SELECT @L_LEN  = @L_COL - LEN(@PA_VALUE)
SELECT SPACE(@L_LEN) + @PA_VALUE

END 

END

END

GO
