-- Object: PROCEDURE citrus_usr.pr_rpt_balancesheet
-- Server: 10.253.33.227 | DB: DMAT
--------------------------------------------------

--EXEC [PR_RPT_BALANCESHEET] 'APR 01 2010','AUG 31 2010',1,2,'' 

CREATE PROC [citrus_usr].[pr_rpt_balancesheet]  
(
 @PA_FROM_DT DATETIME,
 @PA_TO_DT DATETIME,
 @PA_DPMID NUMERIC,
 @PA_FINID NUMERIC,
 @PA_OUT VARCHAR(1000) OUTPUT
)
AS  
BEGIN
    DECLARE
    @L_SQL VARCHAR(8000)
    
    SET @L_SQL = '' 

    SET @L_SQL = @L_SQL + ' SELECT ''A'' As FINGT_GROUP_BY ,FINGT_GROUP_NAME, FINA_ACC_CODE, FINA_ACC_NAME , SUM(LDG_AMOUNT) AMOUNT  
							FROM FIN_ACCOUNT_MSTR ,FIN_GROUP_MSTR, LEDGER'+CONVERT(VARCHAR,@PA_FINID) +  ',FIN_GROUP_TRANS
							WHERE FINA_GROUP_ID = FINGM_GROUP_CODE AND LDG_ACCOUNT_ID = FINA_ACC_ID 
                            AND LDG_ACCOUNT_TYPE IN (''G'',''B'',''C'')	AND FINGT_GROUP_NAME =''APPLICATION OF FUNDS''
                            AND  FINA_GROUP_ID = FINGM_GROUP_CODE
							AND CONVERT(VARCHAR,LDG_VOUCHER_DT,103) BETWEEN ''' + CONVERT(VARCHAR,@PA_FROM_DT,103) +  ''' AND ''' + CONVERT(VARCHAR,@PA_TO_DT,103) + ''' 
                            AND LDG_DELETED_IND = 1  
							GROUP BY   FINA_ACC_CODE, FINA_ACC_NAME,FINGT_GROUP_NAME  

							UNION   

							SELECT ''L'' As FINGT_GROUP_BY,FINGT_GROUP_NAME, FINA_ACC_CODE, FINA_ACC_NAME ,SUM(LDG_AMOUNT)  AMOUNT  
							FROM FIN_ACCOUNT_MSTR ,FIN_GROUP_MSTR, LEDGER'+CONVERT(VARCHAR,@PA_FINID) +  ',FIN_GROUP_TRANS
							WHERE FINA_GROUP_ID = FINGM_GROUP_CODE  AND LDG_ACCOUNT_ID = FINA_ACC_ID 
                            AND LDG_ACCOUNT_TYPE IN (''G'',''B'',''C'') AND FINGT_GROUP_NAME =''SOURCES OF FUNDS'' 
                            AND   FINA_GROUP_ID = FINGM_GROUP_CODE
							AND CONVERT(VARCHAR,LDG_VOUCHER_DT,103) BETWEEN ''' + CONVERT(VARCHAR,@PA_FROM_DT,103) + ''' AND ''' + CONVERT(VARCHAR,@PA_TO_DT,103) + ''' 
                            AND LDG_DELETED_IND = 1  
							GROUP BY  FINA_ACC_CODE, FINA_ACC_NAME,FINGT_GROUP_NAME '  
  

   PRINT @L_SQL
   EXEC(@L_SQL)

END

GO
