-- Object: PROCEDURE citrus_usr.PR_RPT_LOGGED_DTLS
-- Server: 10.253.33.227 | DB: DMAT
--------------------------------------------------


CREATE PROCEDURE [citrus_usr].[PR_RPT_LOGGED_DTLS]
(
 @PA_FROM_DT VARCHAR(50)
,@PA_TO_DT VARCHAR(50)
)
AS 
BEGIN
SELECT DISTINCT ISNULL(LOGG_NAME,'') LOGG_NAME,
ISNULL(LOGG_IP,'') LOGG_IP,
--LOGG_SERVERIP,
--LOGG_CURRENTCNT,
--LOGG_TOTALCNT,
--LOGG_DT,
ISNULL(LOGG_PC_NAME, '')LOGG_PC_NAME
FROM LOGGED_MSTR
WHERE CONVERT(VARCHAR(11),LOGG_DT,109) BETWEEN @PA_FROM_DT AND  @PA_TO_DT
--ORDER BY LOGG_DT DESC
END

GO
