-- Object: TABLE citrus_usr.NSDL_HOLDING_DTLS
-- Server: 10.253.33.227 | DB: DMAT
--------------------------------------------------

CREATE TABLE [citrus_usr].[NSDL_HOLDING_DTLS]
(
    [NSDHM_BR_CODE] VARCHAR(6) NULL,
    [NSDHM_DPM_ID] VARCHAR(25) NULL,
    [NSDHM_BEN_ACCT_NO] VARCHAR(16) NULL,
    [NSDHM_DPAM_ID] NUMERIC(10, 0) NULL,
    [NSDHM_TRASTM_CD] VARCHAR(20) NULL,
    [NSDHM_REQUEST_DT] DATETIME NULL,
    [NSDHM_TRANSACTION_DT] DATETIME NULL,
    [NSDHM_ISIN] VARCHAR(12) NULL,
    [NSDHM_QTY] NUMERIC(18, 3) NULL,
    [NSDHM_BOOK_NAAR_CD] VARCHAR(3) NULL,
    [NSDHM_BOOK_TYPE] VARCHAR(2) NULL,
    [NSDHM_CC_ID] VARCHAR(20) NULL,
    [NSDHM_SETT_TYPE] VARCHAR(5) NULL,
    [NSDHM_BLOCK_LOG_FLAG] CHAR(1) NULL,
    [NSDHM_BLOCK_LOCK_CD] VARCHAR(25) NULL,
    [NSDHM_LOCKIN_REL_DATE] DATETIME NULL,
    [NSDHM_COUNTER_DPM_ID] VARCHAR(20) NULL,
    [NSDHM_COUNTER_BO_ID] VARCHAR(25) NULL,
    [NSDHM_COUNTER_CMBP_ID] VARCHAR(25) NULL,
    [NSDHM_OTHER_SETT_TYPE] VARCHAR(50) NULL,
    [NSDHM_OTHER_SETT_NO] VARCHAR(50) NULL,
    [NSDHM_DPM_TRANS_NO] VARCHAR(50) NULL,
    [NSDHM_DM_TRANS_NO] VARCHAR(50) NULL,
    [NSDHM_INT_REF_NO] VARCHAR(50) NULL,
    [NSDHM_REG_RSN1] VARCHAR(50) NULL,
    [NSDHM_REG_RSN2] VARCHAR(50) NULL,
    [NSDHM_REG_RSN3] VARCHAR(50) NULL,
    [NSDHM_REG_RSN4] VARCHAR(50) NULL,
    [NSDHM_BEN_CTGRY] VARCHAR(25) NULL,
    [NSDHM_BEN_ACCT_TYPE] VARCHAR(25) NULL,
    [NSDHM_CREATED_BY] VARCHAR(25) NULL,
    [NSDHM_CREATED_DT] DATETIME NULL,
    [NSDHM_LST_UPD_BY] VARCHAR(25) NULL,
    [NSDHM_LST_UPD_DT] DATETIME NULL,
    [NSDHM_DELETED_IND] SMALLINT NULL,
    [NSDHM_SETT_NO] VARCHAR(50) NULL,
    [NSDHM_SLIP_NO] VARCHAR(50) NULL,
    [NSDHM_CHARGE] NUMERIC(10, 5) NULL,
    [NSDHM_DP_CHARGE] NUMERIC(10, 5) NULL,
    [NSDHM_LN_NO] INT NULL,
    [NSDHM_TRN_DESCP] VARCHAR(200) NULL,
    [WAIVE_FLAG] CHAR(1) NULL
);

GO
