-- Object: TABLE citrus_usr.a_12
-- Server: 10.253.33.227 | DB: DMAT
--------------------------------------------------

CREATE TABLE [citrus_usr].[a_12]
(
    [ENTPD_ID] NUMERIC(10, 0) NOT NULL,
    [ENTPD_ENTP_ID] NUMERIC(10, 0) NOT NULL,
    [ENTPD_ENTDM_ID] NUMERIC(10, 0) NOT NULL,
    [ENTPD_ENTDM_CD] VARCHAR(20) NOT NULL,
    [ENTPD_VALUE] VARCHAR(50) NULL,
    [ENTPD_CREATED_BY] VARCHAR(25) NULL,
    [ENTPD_CREATED_DT] DATETIME NOT NULL,
    [ENTPD_LST_UPD_BY] VARCHAR(25) NOT NULL,
    [ENTPD_LST_UPD_DT] DATETIME NOT NULL,
    [ENTPD_DELETED_IND] SMALLINT NOT NULL
);

GO
