-- Object: PROCEDURE citrus_usr.PR_IMPORT_BULK_DPT3
-- Server: 10.253.33.227 | DB: DMAT
--------------------------------------------------

--begin tran
--EXEC PR_IMPORT_BULK_DPT3 'CDSL','HO','BULK','D:\BulkInsDbfolder\DPT3\08DPT3U.06062020042253.SOD', '*|~*'  ,'|*~|' ,''   

--rollback
CREATE PROCEDURE [citrus_usr].[PR_IMPORT_BULK_DPT3](@PA_EXCH          VARCHAR(20)              
,@PA_LOGIN_NAME    VARCHAR(20)              
,@PA_MODE          VARCHAR(10)                                              
,@PA_DB_SOURCE     VARCHAR(250)              
,@ROWDELIMITER     CHAR(4) =     '*|~*'                
,@COLDELIMITER     CHAR(4) =     '|*~|'                
,@PA_ERRMSG        VARCHAR(8000) OUTPUT )            
AS 
BEGIN 

TRUNCATE TABLE DPT3_TMP
DECLARE @@SSQL  VARCHAR(8000)

SET @@SSQL ='BULK INSERT DPT3_TMP	 FROM ''' + @pa_db_source + ''' WITH 
(
FIELDTERMINATOR = ''~'',
ROWTERMINATOR = ''\n''
)'

EXEC(@@SSQL)
 

INSERT INTO DPT3_MSTR
SELECT 
DPT3T_IDENTIFIER,
DPT3T_EDIS_TXN_TYPE,
DPT3T_EDIS_TXN_STATUS,
DPT3T_BO_ID,
DPT3T_ISIN,
DPT3T_EX_ID,
DPT3T_CM_ID,
DPT3T_TXN_ID,
DPT3T_TXN_TIME,
DPT3T_TXN_QUANTITY,
DPT3T_TOT_LOCKED_QTY,
DPT3T_PENDING_QTY,
DPT3T_COUNTER_BOID,
DPT3T_EXEC_DATE,
DPT3T_SETTLE_ID,
DPT3T_VALIDITY_DAYS,
@PA_LOGIN_NAME,
getdate(),
@PA_LOGIN_NAME,
getdate(),
'1'
 FROM DPT3_TMP
 WHERE NOT EXISTS (SELECT 1 FROM DPT3_MSTR 
							WHERE DPT3T_BO_ID=DPT3_BO_ID  
							AND DPT3T_EDIS_TXN_TYPE= DPT3_EDIS_TXN_TYPE  
							AND DPT3T_EDIS_TXN_STATUS=DPT3_EDIS_TXN_STATUS 
							AND DPT3T_ISIN=DPT3_ISIN
							AND DPT3T_CM_ID = DPT3_CM_ID
							AND DPT3T_TXN_ID = DPT3_TXN_ID
							AND DPT3T_TXN_TIME = DPT3_TXN_TIME
							AND DPT3T_TXN_QUANTITY = DPT3_TXN_QUANTITY
							AND DPT3T_TOT_LOCKED_QTY = DPT3_TOT_LOCKED_QTY
							AND DPT3T_PENDING_QTY = DPT3_PENDING_QTY
							AND DPT3T_COUNTER_BOID = DPT3_COUNTER_BOID
							AND DPT3T_EXEC_DATE = DPT3_EXEC_DATE
							AND DPT3T_SETTLE_ID = DPT3_SETTLE_ID
							AND DPT3T_VALIDITY_DAYS = DPT3_VALIDITY_DAYS
					)
 
END

GO
