-- Object: TABLE citrus_usr.cc_clnd_converter
-- Server: 10.253.33.227 | DB: DMAT
--------------------------------------------------

CREATE TABLE [citrus_usr].[cc_clnd_converter]
(
    [SRC] NVARCHAR(MAX) NULL,
    [CNTRLSCTIESDPSTRYPTCPT] NVARCHAR(MAX) NULL,
    [LINENB] NVARCHAR(MAX) NULL,
    [XCHG] NVARCHAR(MAX) NULL,
    [CLRSYSID] NVARCHAR(MAX) NULL,
    [MKTTPANDID] NVARCHAR(MAX) NULL,
    [SCTIESSTTLMTXID] NVARCHAR(MAX) NULL,
    [STTLMPRDFR] NVARCHAR(MAX) NULL,
    [STTLMPRDTO] NVARCHAR(MAX) NULL,
    [NSLDDDLNDT] NVARCHAR(MAX) NULL,
    [PAYINDT] NVARCHAR(MAX) NULL,
    [PYOUTDT] NVARCHAR(MAX) NULL,
    [RMKS] NVARCHAR(MAX) NULL,
    [DUMMY1] NVARCHAR(MAX) NULL,
    [DUMMY2] NVARCHAR(MAX) NULL,
    [DUMMY3] NVARCHAR(MAX) NULL,
    [DUMMY4] NVARCHAR(MAX) NULL
);

GO
