-- Object: TABLE citrus_usr.DMT_STATUS_MSTR
-- Server: 10.253.33.227 | DB: DMAT
--------------------------------------------------

CREATE TABLE [citrus_usr].[DMT_STATUS_MSTR]
(
    [DMTS_DMT_REQ_NO] VARCHAR(8) NULL,
    [DMTS_RTA_ID] VARCHAR(6) NULL,
    [DMTS_DMT_REQ_QTY] NUMERIC(17, 3) NULL,
    [DMTS_DMT_ACCP_QTY] NUMERIC(17, 3) NULL,
    [DMTS_DMT_REJ_QTY] NUMERIC(17, 3) NULL,
    [DMTS_ISIN] VARCHAR(12) NULL,
    [DMTS_ISIN_SHRT_NM] VARCHAR(20) NULL,
    [DMTS_AGEING_PERIOD] VARCHAR(3) NULL,
    [DMTS_DMT_REQ_FRM_NOS] VARCHAR(16) NULL,
    [DMTS_BO_ID] VARCHAR(16) NULL,
    [DMTS_DISP_DT] DATETIME NULL,
    [DMTS_DMT_REQ_RECDT] DATETIME NULL,
    [DMTS_DMT_PEND_REASON] VARCHAR(18) NULL,
    [DMTS_DRN_STATUS] VARCHAR(5) NULL,
    [DMTS_DRN_SETUP_DT] DATETIME NULL,
    [DMTS_SEC_TYPE_DESC] VARCHAR(20) NULL,
    [DMTS_DRN_CLOSE_DT] DATETIME NULL,
    [DMTS_NO_CERT] VARCHAR(5) NULL,
    [DMTS_BO_FHNAME] VARCHAR(142) NULL,
    [DMTS_DRN_REJ_SEQ] VARCHAR(2) NULL,
    [DMTS_REJ_QTY] NUMERIC(17, 3) NULL,
    [DMTS_REJ_CD] VARCHAR(2) NULL,
    [DMTS_REJ_REASON] VARCHAR(100) NULL,
    [DMTS_DPAM_ID] NUMERIC(18, 0) NULL,
    [DMTS_DPM_ID] NUMERIC(18, 0) NULL,
    [DMTS_CHARGE] NUMERIC(18, 0) NULL,
    [DMTS_DP_CHARGE] NUMERIC(18, 0) NULL,
    [DMTS_QTYTYP_CD] CHAR(1) NULL,
    [DMTS_QTYTYP_DESC] VARCHAR(40) NULL,
    [DMTS_LOCKIN_QTY] NUMERIC(18, 3) NULL,
    [DMTS_LOCKIN_REASONCD] NUMERIC(18, 3) NULL,
    [DMTS_LOCKIN_REASONDESC] VARCHAR(40) NULL
);

GO
