-- Object: TABLE citrus_usr.SSRS_JV_MONTHLY
-- Server: 10.253.33.227 | DB: DMAT
--------------------------------------------------

CREATE TABLE [citrus_usr].[SSRS_JV_MONTHLY]
(
    [LD_CLIENTCD] VARCHAR(50) NULL,
    [LD_DT] DATETIME NULL,
    [LD_AMOUNT] NUMERIC(18, 4) NULL,
    [LD_PARTICULAR] VARCHAR(250) NULL,
    [LD_CHEQUENO] VARCHAR(15) NULL,
    [LD_DEBITFLAG] VARCHAR(1) NOT NULL,
    [LD_DOCUMENTTYPE] VARCHAR(1) NOT NULL,
    [LD_DOCUMENTNO] NUMERIC(10, 0) NULL,
    [MKRID] VARCHAR(25) NOT NULL,
    [MKRDT] DATETIME NOT NULL,
    [LD_ACCYEAR] INT NULL,
    [LD_DPID] VARCHAR(8) NULL,
    [FIRST_HOLD_STATE] VARCHAR(25) NULL
);

GO
