-- Object: PROCEDURE citrus_usr.PR_CDSL_PRETRADE_EDIS_RESPONSE_ANGEL_MF
-- Server: 10.253.33.227 | DB: DMAT
--------------------------------------------------

--BEGIN TRAN
--EXEC PR_CDSL_PRETRADE_EDIS_RESPONSE_ANGEL '',''
--SELECT * FROM EDIS_PRE_DPTDC_MAK
--select * from dptdc_mak with(nolock) where DPTDC_SLIP_NO='2705202051271038'
--ROLLBACK
CREATE PROCEDURE [citrus_usr].[PR_CDSL_PRETRADE_EDIS_RESPONSE_ANGEL_MF]
(
@PA_REQID VARCHAR(100)
,@PA_LOGINNAMES VARCHAR(100)
)
AS
BEGIN 

UPDATE T SET DPTDC_STATUS='D',DPTDC_TRANS_NO=CDSL_TRXN_ID
FROM EDIS_PRE_DPTDC_MAK T  ,E_DIS_PROCESS_DATA,DP_ACCT_MSTR WHERE DPAM_ID=DPTDC_DPAM_ID 
AND ISNULL(LTRIM(RTRIM(DPTDC_SLIP_NO)),'')=ISNULL(LTRIM(RTRIM(SLIP_NO)),'')
and isin=DPTDC_ISIN and qty=DPTDC_QTY*-1 AND DPAM_SBA_NO=BOID
AND DPTDC_STATUS='P' AND ISNULL(dptdc_trans_no,'')=''
AND NOT EXISTS (
SELECT 1 FROM DPTDC_MAK I WHERE  I.DPTDC_SLIP_NO=T.DPTDC_TRANS_NO
) 

INSERT INTO DPTDC_MAK
SELECT 
DPTDC_ID
,DPTDC_DPAM_ID
,DPTDC_REQUEST_DT
,CDSL_TRXN_ID --DPTDC_SLIP_NO
,DPTDC_ISIN
,DPTDC_BATCH_NO
,DPTDC_LINE_NO
,DPTDC_QTY
,DPTDC_INTERNAL_REF_NO
,null --DPTDC_TRANS_NO
,DPTDC_MKT_TYPE
,DPTDC_SETTLEMENT_NO
,DPTDC_EXECUTION_DT
,DPTDC_OTHER_SETTLEMENT_TYPE
,DPTDC_OTHER_SETTLEMENT_NO
,DPTDC_COUNTER_DP_ID
,DPTDC_COUNTER_CMBP_ID
,DPTDC_COUNTER_DEMAT_ACCT_NO
,dptdC_trastm_cd
,DPTDC_DTLS_ID
,DPTDC_BOOKING_NARRATION
,DPTDC_BOOKING_TYPE
,DPTDC_CONVERTED_QTY
,DPTDC_REASON_CD
,'P' DPTDC_STATUS
,DPTDC_INTERNAL_TRASTM
,DPTDC_EXCM_ID
,DPTDC_CASH_TRF
,DPTDC_CM_ID
,DPTDC_CREATED_BY
,DPTDC_CREATED_DT
,DPTDC_LST_UPD_BY
,DPTDC_LST_UPD_DT
,DPTDC_DELETED_IND
,dptdc_rmks
,DPTDC_ERRMSG
,DPTDC_BROKERBATCH_NO
,DPTDC_BROKER_INTERNAL_REF_NO
,dptdc_mid_chk
,dptdc_res_cd
,dptdc_res_desc
,DPTDC_PAYMODE
,DPTDC_BANKACNO
,DPTDC_BANKACNAME
,DPTDC_BANKBRNAME
,DPTDC_TRANSFEREENAME
,DPTDC_DOI
,DPTDC_CHQ_REFNO
FROM EDIS_PRE_DPTDC_MAK O,E_DIS_PROCESS_DATA,DP_ACCT_MSTR WHERE 
DPAM_ID=DPTDC_DPAM_ID 
AND ISNULL(LTRIM(RTRIM(DPTDC_SLIP_NO)),'')=ISNULL(LTRIM(RTRIM(SLIP_NO)),'')
and isin=DPTDC_ISIN and qty=DPTDC_QTY*-1 AND DPAM_SBA_NO=BOID
AND DPTDC_STATUS='D' AND ISNULL(dptdc_trans_no,'')<>''
--DPTDC_SLIP_NO=SLIP_NO
AND NOT EXISTS (
SELECT 1 FROM DPTDC_MAK I WHERE  I.DPTDC_ID=O.DPTDC_ID AND I.DPTDC_REQUEST_DT=O.DPTDC_REQUEST_DT 
--I.DPTDC_SLIP_NO=O.DPTDC_TRANS_NO
--and I.DPTDC_ISIN=O.DPTDC_ISIN and I.DPTDC_QTY=O.DPTDC_QTY AND DPAM_ID=DPTDC_DPAM_ID
) 
END

GO
