-- Object: TABLE citrus_usr.TBL_AUTO_PROCESS_LISNER_LOG
-- Server: 10.253.33.227 | DB: DMAT
--------------------------------------------------

CREATE TABLE [citrus_usr].[TBL_AUTO_PROCESS_LISNER_LOG]
(
    [SNO] INT IDENTITY(1,1) NOT NULL,
    [BUSINESS_DATE] DATETIME NULL,
    [PROCESS_FOR] VARCHAR(50) NULL,
    [PROCESS_FILE_NAME] VARCHAR(50) NULL,
    [PROCESS_FLAG] INT NULL,
    [PROCESS_SETUP_DATE] DATETIME NULL
);

GO
