-- Object: PROCEDURE citrus_usr.PR_UPD_POA_AMC
-- Server: 10.253.33.227 | DB: DMAT
--------------------------------------------------

CREATE PROCEDURE [citrus_usr].[PR_UPD_POA_AMC]
(
@PA_LOGIN_NAME VARCHAR(50),
@PA_TYPE VARCHAR(20)
)
AS 
BEGIN
 IF @PA_TYPE='POA'
	 BEGIN             
			UPDATE T2 SET TMPPOA_DPAM_ID=DPAM_ID FROM DP_ACCT_MSTR T1,TMP_POALIST_MSTR T2 WHERE 
			TMPPOA_BOID=DPAM_SBA_NO AND DPAM_DELETED_IND=1
            
			IF EXISTS (SELECT * FROM ACCOUNT_GROUP_MAPPING WHERE GROUP_CD='POA')
			BEGIN            
			DELETE FROM ACCOUNT_GROUP_MAPPING WHERE GROUP_CD='POA'
			END
            INSERT INTO ACCOUNT_GROUP_MAPPING (DPAM_ID , GROUP_CD,CREATED_DT,CREATED_BY ,LST_UPD_DT,LST_UPD_BY , DELETED_IND)
            SELECT TMPPOA_DPAM_ID,'POA',GETDATE(),@PA_LOGIN_NAME,GETDATE(),@PA_LOGIN_NAME,1 FROM TMP_POALIST_MSTR
	 END
 IF @PA_TYPE='AMC'
	 BEGIN
			UPDATE T2 SET TMPAMC_DPAM_ID=DPAM_ID FROM DP_ACCT_MSTR T1,TMP_AMCLIST_MSTR T2 WHERE 
			TMPAMC_BOID=DPAM_SBA_NO AND DPAM_DELETED_IND=1

			IF EXISTS (SELECT * FROM ACCOUNT_GROUP_MAPPING WHERE GROUP_CD='AMC')
			BEGIN            
			DELETE FROM ACCOUNT_GROUP_MAPPING WHERE GROUP_CD='AMC'
			END

            INSERT INTO ACCOUNT_GROUP_MAPPING (DPAM_ID , GROUP_CD,CREATED_DT,CREATED_BY ,LST_UPD_DT,LST_UPD_BY , DELETED_IND)
            SELECT TMPAMC_DPAM_ID,'AMC',GETDATE(),@PA_LOGIN_NAME,GETDATE(),@PA_LOGIN_NAME,1 FROM TMP_AMCLIST_MSTR
	 END
END

GO
