-- Object: PROCEDURE citrus_usr.BrkTrnsEdtScn
-- Server: 10.253.33.227 | DB: DMAT
--------------------------------------------------

/*

SELECT * FROM  DP_TRX_DTLS WHERE DPTD_BROKERBATCH_NO = '2032530' 
SELECT * FROM  DP_TRX_DTLS WHERE DPTD_BROKERBATCH_NO BETWEEN FROM BATCHNO AND TO BATCHNO

SELECT DPTD_BROKERBATCH_NO FROM DP_TRX_DTLS

SP_HELPTEXT  CLIENTMODTRAIL


EXEC   BRKTRNSEDTSCN 'jan 5 2009','jan 5 2009','2032530','10752099'
	Jan  5 2009	Jan  5 2009	 2032530	10752099


*/

CREATE PROC [citrus_usr].[BrkTrnsEdtScn]
 
@frmdate   DATETIME,  
@toDate   DATETIME ,
@BROKERBATCHNO VARCHAR(20),
@DPTD_SLIP_NO varchar(20)
 AS


SET @TODATE = DATEADD(hh,23,@TODATE)  

 
SELECT 
		DPTD_ID,DPAM_SBA_NO,DPTD_ISIN,
		CASE WHEN ISNULL(DPTD_QTY,'0')='0' THEN '-NA-' ELSE ISNULL(DPTD_QTY,'')END DPTD_QTY ,
		DPTD_SLIP_NO,
		DPTD_BROKERBATCH_NO 
		--DPTD_TRASTM_CD 
FROM  
		DP_TRX_DTLS,DP_ACCT_MSTR 
WHERE 
	DPTD_DPAM_ID=DPAM_ID 
    AND DPAM_DELETED_IND=1 AND
   	DPTD_BROKERBATCH_NO = @BROKERBATCHNO 
	and DPTD_LST_UPD_DT between @frmdate and @toDate
	and DPTD_SLIP_NO=@DPTD_SLIP_NO
       



--SELECT DPTD_COUNTER_DEMAT_ACCT_NO,DPTD_CONVERTED_QTY,DPTD_SLIP_NO,DPTD_BROKERBATCH_NO,DPTD_TRASTM_CD FROM  DP_TRX_DTLS WHERE DPTD_BROKERBATCH_NO BETWEEN @FROMBROKERBATCHNO AND  @TOBROKERBATCHNO

GO
