-- Object: TABLE citrus_usr.RMT_STATUS_MSTR
-- Server: 10.253.33.227 | DB: DMAT
--------------------------------------------------

CREATE TABLE [citrus_usr].[RMT_STATUS_MSTR]
(
    [RMTS_RMT_REQ_NO] NUMERIC(18, 0) NULL,
    [RMTS_BO_ID] VARCHAR(16) NULL,
    [RMTS_ISIN_ALPHA_CD] VARCHAR(12) NULL,
    [RMTS_ISIN_SHRT_NM] VARCHAR(20) NULL,
    [RMTS_RMT_REF_NO] VARCHAR(16) NULL,
    [RMTS_QTY_REQ_FOR_RMT_NOS] NUMERIC(16, 0) NULL,
    [RMTS_RRN_STAT_DESC] VARCHAR(19) NULL,
    [RMTS_REC_DT] DATETIME NULL,
    [RMTS_NO_DAYS_ELAPSED] NUMERIC(18, 0) NULL,
    [RMTS_SEC_TYPE_DESC] VARCHAR(40) NULL,
    [RMTS_BO_NM] VARCHAR(100) NULL,
    [RMTS_LOT_TYPE_DESC] VARCHAR(9) NULL,
    [RMTS_DENM_NO] NUMERIC(18, 0) NULL,
    [RMTS_QTY_TYPE_DESC] VARCHAR(15) NULL,
    [RMTS_LOCK_REASON_CD] NUMERIC(18, 0) NULL,
    [RMTS_LOCK_REASON_DESC] VARCHAR(40) NULL,
    [RMTS_DPAM_ID] NUMERIC(18, 0) NULL,
    [RMTS_DPM_ID] NUMERIC(18, 0) NULL,
    [RMTS_CHARGE] NUMERIC(18, 0) NULL,
    [RMTS_DP_CHARGE] NUMERIC(18, 0) NULL,
    [RMTS_SETUP_DT] DATETIME NULL,
    [RMTS_CONF_DT] DATETIME NULL,
    [RMTS_STAT_CD] VARCHAR(5) NULL,
    [RMTS_STAT_DESC] VARCHAR(40) NULL,
    [RMTS_LOCKIN_QTY] NUMERIC(17, 3) NULL
);

GO
