-- Object: PROCEDURE citrus_usr.PR_RECON_REPORT
-- Server: 10.253.33.227 | DB: DMAT
--------------------------------------------------

--EXEC PR_RECON_REPORT 'DEC 14 2021','DEC 14 2021', 'HO'
CREATE  PROC [citrus_usr].[PR_RECON_REPORT]
(@PA_FROM_DT DATETIME, @PA_TO_DT DATETIME    
,@PA_LOGIN_NAME VARCHAR(100)    
)          
AS 
BEGIN

if exists (
select 1 from CDSL_RECON_LOG where CRL_FILEDT  BETWEEN @PA_FROM_DT AND @PA_TO_DT  and CRL_RECONSTATUS = 'MISMATCH')

--SELECT  TOP 7  CONVERT (VARCHAR(11), CRL_FILEDT,103) [RECON DATE], CRL_RECONSTATUS [RECON STATUS]  
--FROM CDSL_RECON_LOG ORDER BY CRL_CURRDT DESC 
begin 
SELECT ''''+ CLIENT_HLDG BOID,ISIN_HLDG,EDMAT_HLDG,CDAS_HLDG,MISMATCH_DATE FROM CDSL_RECON_MISMATCH_DATA WHERE MISMATCH_DATE BETWEEN @PA_FROM_DT AND @PA_TO_DT ORDER BY MISMATCH_DATE
end 

else 
begin 
SELECT  TOP 7  CONVERT (VARCHAR(11), CRL_FILEDT,103) [RECON DATE], CRL_RECONSTATUS [RECON STATUS] 
from CDSL_RECON_LOG 
where CRL_FILEDT  BETWEEN @PA_FROM_DT AND @PA_TO_DT
end 
 
END

GO
