-- Object: PROCEDURE citrus_usr.DP_Ageing_punit
-- Server: 10.253.33.227 | DB: DMAT
--------------------------------------------------

--select * from  Sheet1$



--update  Sheet1$ set main_code = '2019'







-----------m

--------------------m



--------m







--------m





-------------m















CREATE proc DP_Ageing_punit 

as









create table  #temp 

( CLTCODE VARCHAR(25),

  BALAMT MONEY,

  CR007Total MONEY,DR007Total MONEY,CR015Total MONEY,DR015Total MONEY ,CR030Total MONEY,DR030Total MONEY,

		CR060Total MONEY,

		DR060Total MONEY,

		CR090Total MONEY,

		DR090Total MONEY,

		CR180Total MONEY,

		DR180Total MONEY,

		CR360Total MONEY,

		DR360Total MONEY,

		CR361Total MONEY,

		DR361Total MONEY

		 )



 CREATE NONCLUSTERED INDEX #T ON #temp

 (CLTCODE ASC )



 DECLARE @DT DATETIME

 SET @DT='2019-01-31' 

 





INSERT INTO #temp

select LD_CLIENTCD,BALAMT=SUM(LD_AMOUNT*-1),

		CR007Total=SUM(case when LD_AMOUNT >0 and LD_DT > @dt-08 then LD_AMOUNT else 0 end),

		DR007Total=SUM(case when LD_AMOUNT <0 and LD_DT > @dt-08 then -LD_AMOUNT else 0 end),

		CR015Total=SUM(case when LD_AMOUNT >0 and LD_DT <= @dt-08 and LD_DT > @dt-16 then LD_AMOUNT else 0 end),

		DR015Total=SUM(case when LD_AMOUNT <0 and LD_DT <= @dt-08 and LD_DT > @dt-16 then -LD_AMOUNT else 0 end),

		CR030Total=SUM(case when LD_AMOUNT >0 and LD_DT <= @dt-16 and LD_DT > @dt-31 then LD_AMOUNT else 0 end),

		DR030Total=SUM(case when LD_AMOUNT <0 and LD_DT <= @dt-16 and LD_DT > @dt-31 then -LD_AMOUNT else 0 end),

		CR060Total=SUM(case when LD_AMOUNT >0 and LD_DT <= @dt-31 and LD_DT > @dt-61 then LD_AMOUNT else 0 end),

		DR060Total=SUM(case when LD_AMOUNT <0 and LD_DT <= @dt-31 and LD_DT > @dt-61 then -LD_AMOUNT else 0 end),

		CR090Total=SUM(case when LD_AMOUNT >0 and LD_DT <= @dt-61 and LD_DT > @dt-91 then LD_AMOUNT else 0 end),

		DR090Total=SUM(case when LD_AMOUNT <0 and LD_DT <= @dt-61 and LD_DT > @dt-91 then -LD_AMOUNT else 0 end),

		CR180Total=SUM(case when LD_AMOUNT >0 and LD_DT <= @dt-91 and LD_DT > @dt-181 then LD_AMOUNT else 0 end),

		DR180Total=SUM(case when LD_AMOUNT <0 and LD_DT <= @dt-91 and LD_DT > @dt-181 then -LD_AMOUNT else 0 end),

		CR360Total=SUM(case when LD_AMOUNT >0 and LD_DT <= @dt-181 and LD_DT > @dt-360 then LD_AMOUNT else 0 end),

		DR360Total=SUM(case when LD_AMOUNT <0 and LD_DT <= @dt-181 and LD_DT > @dt-360 then -LD_AMOUNT else 0 end)  ,

		CR361Total=SUM(case when LD_AMOUNT >0 and LD_DT <= @dt-361 then LD_AMOUNT else 0 end),

		DR361Total=SUM(case when LD_AMOUNT <0 and LD_DT <= @dt-361 then -LD_AMOUNT else 0 end) 

		FROM (SELECT LD_CLIENTCD,LD_AMOUNT,LD_DT   FROM SYNERGY_LEDGER WHERE LD_DT <='2019-01-31 23:59'

AND LD_CLIENTCD LIKE '120332%'

UNION ALL

SELECT CLIENT_CODE,amount,LD_DT FROM Sheet1$  

   ) A

GROUP BY LD_CLIENTCD



 

 

 

 select * from #temp

 select sum(BALAMT) from #temp

 

  

	



SELECT CLTCODE,SUM(BALAMT) BALAMT,SUM(CR007Total) CR007Total,SUM(DR007Total) DR007Total,SUM(CR015Total) CR015Total,SUM(DR015Total) DR015Total,

SUM(CR030Total) CR030Total,SUM(DR030Total) DR030Total,

SUM(CR060Total) CR060Total,SUM(DR060Total) DR060Total,SUM(CR090Total)CR090Total,SUM(DR090Total)DR090Total,SUM(CR180Total)CR180Total,SUM(DR180Total)DR180Total,

SUM(CR360Total)CR360Total,SUM(DR360Total) DR360Total ,SUM(CR361Total)CR361Total,SUM(DR361Total) DR361Total INTO #TOTAL

	 FROM #temp T

	 GROUP BY CLTCODE

	



		 

	CREATE TABLE #DEBTORS

	(CLTCODE VARCHAR(18),

	 NET_LD_DOCUMENTTYPE MONEY,DAY7 MONEY,DAY15 MONEY,DAY30  MONEY,DAY60  MONEY, DAY90 MONEY,DAY180 MONEY, DAY360 MONEY, DAY361 MONEY)



	  CREATE NONCLUSTERED INDEX #D ON #DEBTORS

 (CLTCODE ASC )

 

 INSERT INTO #DEBTORS (CLTCODE,NET_LD_DOCUMENTTYPE)

	 SELECT CLTCODE,BALAMT  FROM #TOTAL   WHERE BALAMT > 0  

   

   UPDATE #DEBTORS SET DAY7=

				(CASE WHEN NET_LD_DOCUMENTTYPE <= DR007TOTAL THEN NET_LD_DOCUMENTTYPE ELSE DR007TOTAL END)  

				FROM  #TOTAL B   

				WHERE #DEBTORS.CLTCODE=B.CLTCODE AND NET_LD_DOCUMENTTYPE > 0   

				

				--15

				UPDATE #DEBTORS SET DAY15=

				(CASE WHEN NET_LD_DOCUMENTTYPE-DAY7 >= DR015TOTAL THEN DR015TOTAL ELSE NET_LD_DOCUMENTTYPE-DAY7 END)  

				FROM  #TOTAL B   

				WHERE #DEBTORS.CLTCODE=B.CLTCODE AND NET_LD_DOCUMENTTYPE > 0   

				

				--30

				UPDATE #DEBTORS SET DAY30=

				(CASE WHEN NET_LD_DOCUMENTTYPE-(DAY7+DAY15) >= DR030TOTAL THEN DR030TOTAL ELSE NET_LD_DOCUMENTTYPE-(DAY7+DAY15) END)  

				FROM  #TOTAL B   

				WHERE #DEBTORS.CLTCODE=B.CLTCODE AND NET_LD_DOCUMENTTYPE > 0   

				

						--60

				UPDATE #DEBTORS SET DAY60=

				(CASE WHEN NET_LD_DOCUMENTTYPE-(DAY7+DAY15+DAY30) >= DR060TOTAL THEN DR060TOTAL ELSE NET_LD_DOCUMENTTYPE-(DAY7+DAY15+DAY30) END)  

				FROM  #TOTAL B   

				WHERE #DEBTORS.CLTCODE=B.CLTCODE AND NET_LD_DOCUMENTTYPE > 0   

				

						--90

				UPDATE #DEBTORS SET DAY90=

				(CASE WHEN NET_LD_DOCUMENTTYPE-(DAY7+DAY15+DAY30+DAY60) >= DR090TOTAL THEN DR090TOTAL ELSE NET_LD_DOCUMENTTYPE-(DAY7+DAY15+DAY30+DAY60) END)  

				FROM  #TOTAL B   

				WHERE #DEBTORS.CLTCODE=B.CLTCODE AND NET_LD_DOCUMENTTYPE > 0   

				

						--180

				UPDATE #DEBTORS SET DAY180=

				(CASE WHEN NET_LD_DOCUMENTTYPE-(DAY7+DAY15+DAY30+DAY60+DAY90) >= DR180TOTAL 

				THEN DR180TOTAL ELSE NET_LD_DOCUMENTTYPE-(DAY7+DAY15+DAY30+DAY60+DAY90) END)  

				FROM  #TOTAL B   

				WHERE #DEBTORS.CLTCODE=B.CLTCODE AND NET_LD_DOCUMENTTYPE > 0   

				

						--360

				UPDATE #DEBTORS SET DAY360=

				(CASE WHEN NET_LD_DOCUMENTTYPE-(DAY7+DAY15+DAY30+DAY60+DAY90+DAY180) >= DR360TOTAL 

				THEN DR360TOTAL ELSE NET_LD_DOCUMENTTYPE-(DAY7+DAY15+DAY30+DAY60+DAY90+DAY180) END)  

				FROM  #TOTAL B   

				WHERE #DEBTORS.CLTCODE=B.CLTCODE AND NET_LD_DOCUMENTTYPE > 0  

				

										--361

				UPDATE #DEBTORS SET DAY361=

				(CASE WHEN NET_LD_DOCUMENTTYPE-(DAY7+DAY15+DAY30+DAY60+DAY90+DAY180+DAY360) >= DR361TOTAL 

				THEN DR361TOTAL ELSE NET_LD_DOCUMENTTYPE-(DAY7+DAY15+DAY30+DAY60+DAY90+DAY180+DAY360) END)  

				FROM  #TOTAL B   

				WHERE #DEBTORS.CLTCODE=B.CLTCODE AND NET_LD_DOCUMENTTYPE > 0  





				--SELECT * FROM #TOTAL

	 

	 -----------CREDITORS

	



	 

	CREATE TABLE #CREDITORS

	(CLTCODE VARCHAR(18),

	 NET_LD_DOCUMENTTYPE MONEY,DAY7 MONEY,DAY15 MONEY,DAY30  MONEY,DAY60  MONEY, DAY90 MONEY,DAY180 MONEY, DAY360 MONEY, DAY361 MONEY)



	  CREATE NONCLUSTERED INDEX #D ON #CREDITORS

 (CLTCODE ASC )



  	INSERT INTO #CREDITORS (CLTCODE,NET_LD_DOCUMENTTYPE)

	 SELECT CLTCODE,BALAMT*-1  FROM #TOTAL   WHERE BALAMT < 0   



 SELECT * FROM #CREDITORS

   

				UPDATE #CREDITORS SET DAY7=

				(CASE WHEN NET_LD_DOCUMENTTYPE <= CR007TOTAL THEN NET_LD_DOCUMENTTYPE ELSE CR007TOTAL END)  

				FROM  #TOTAL B   

				WHERE #CREDITORS.CLTCODE=B.CLTCODE AND NET_LD_DOCUMENTTYPE > 0   

				

				--15

				UPDATE #CREDITORS SET DAY15=

				(CASE WHEN NET_LD_DOCUMENTTYPE-DAY7 >= CR015TOTAL THEN CR015TOTAL ELSE NET_LD_DOCUMENTTYPE-DAY7 END)  

				FROM  #TOTAL B   

				WHERE #CREDITORS.CLTCODE=B.CLTCODE AND NET_LD_DOCUMENTTYPE  > 0   

				

				--30

				UPDATE #CREDITORS SET DAY30=

				(CASE WHEN NET_LD_DOCUMENTTYPE-(DAY7+DAY15) >= CR030TOTAL THEN CR030TOTAL ELSE NET_LD_DOCUMENTTYPE-(DAY7+DAY15) END)  

				FROM  #TOTAL B   

				WHERE #CREDITORS.CLTCODE=B.CLTCODE AND NET_LD_DOCUMENTTYPE  > 0   

				

						--60

				UPDATE #CREDITORS SET DAY60=

				(CASE WHEN NET_LD_DOCUMENTTYPE-(DAY7+DAY15+DAY30) >= CR060TOTAL THEN CR060TOTAL ELSE NET_LD_DOCUMENTTYPE-(DAY7+DAY15+DAY30) END)  

				FROM  #TOTAL B   

				WHERE #CREDITORS.CLTCODE=B.CLTCODE AND NET_LD_DOCUMENTTYPE  > 0   

				

						--90

				UPDATE #CREDITORS SET DAY90=

				(CASE WHEN NET_LD_DOCUMENTTYPE-(DAY7+DAY15+DAY30+DAY60) >= CR090TOTAL THEN CR090TOTAL ELSE NET_LD_DOCUMENTTYPE-(DAY7+DAY15+DAY30+DAY60) END)  

				FROM  #TOTAL B   

				WHERE #CREDITORS.CLTCODE=B.CLTCODE AND NET_LD_DOCUMENTTYPE  > 0   

				

						--180

				UPDATE #CREDITORS SET DAY180=

				(CASE WHEN NET_LD_DOCUMENTTYPE-(DAY7+DAY15+DAY30+DAY60+DAY90) >= CR180TOTAL 

				THEN CR180TOTAL ELSE NET_LD_DOCUMENTTYPE-(DAY7+DAY15+DAY30+DAY60+DAY90) END)  

				FROM  #TOTAL B   

				WHERE #CREDITORS.CLTCODE=B.CLTCODE AND NET_LD_DOCUMENTTYPE  > 0   

				

						--360

				UPDATE #CREDITORS SET DAY360=

				(CASE WHEN NET_LD_DOCUMENTTYPE-(DAY7+DAY15+DAY30+DAY60+DAY90+DAY180) >= CR360TOTAL 

				THEN CR360TOTAL ELSE NET_LD_DOCUMENTTYPE-(DAY7+DAY15+DAY30+DAY60+DAY90+DAY180) END)  

				FROM  #TOTAL B   

				WHERE #CREDITORS.CLTCODE=B.CLTCODE AND NET_LD_DOCUMENTTYPE  > 0   

				

										--361

				UPDATE #CREDITORS SET DAY361=

				(CASE WHEN NET_LD_DOCUMENTTYPE-(DAY7+DAY15+DAY30+DAY60+DAY90+DAY180+DAY360) >= CR361TOTAL 

				THEN CR361TOTAL ELSE NET_LD_DOCUMENTTYPE-(DAY7+DAY15+DAY30+DAY60+DAY90+DAY180+DAY360) END)  

				FROM  #TOTAL B   

				WHERE #CREDITORS.CLTCODE=B.CLTCODE AND NET_LD_DOCUMENTTYPE > 0   



				SELECT * FROM #CREDITORS

				SELECT * FROM #DEBTORS





 SELECT * INTO #HOLD FROM SYNERGY_HOLDING WHERE HLD_HOLD_DATE ='2019-01-31'



  SELECT V.* INTO #CLOSIN FROM  VW_ISIN_RATE_MASTER V,

  (SELECT ISIN,MAX(RATE_DATE) AS RD FROM  VW_ISIN_RATE_MASTER  WHERE  RATE_DATE <='2019-01-31' GROUP BY ISIN ) B

  WHERE  RATE_DATE <='2019-01-31' AND V.ISIN=B.ISIN AND RD=RATE_DATE



  SELECT HLD_AC_CODE,SUM(HLD_AC_POS*CLOSE_PRICE)VALUE INTO #HOLD_nov FROM #HOLD H, #CLOSIN WHERE ISIN=HLD_ISIN_CODE  GROUP BY HLD_AC_CODE



  	ALTER TABLE  #CREDITORS

	ADD VALUATION MONEY

		ALTER TABLE  #DEBTORS

	ADD VALUATION MONEY

	    UPDATE #DEBTORS SET VALUATION= VALUE   FROM #HOLD_nov WHERE   CLTCODE=HLD_AC_CODE



		SELECT *,DEF=(CASE WHEN ISNULL(VALUATION,0)>NET_LD_DOCUMENTTYPE THEN 'Secured' else 'RISK' END) FROM #DEBTORS



				SELECT *,DEF=(CASE WHEN ISNULL(VALUATION,0)>NET_LD_DOCUMENTTYPE THEN 'Secured' else 'RISK' END) FROM #CREDITORS

GO
