-- Object: PROCEDURE citrus_usr.PR_RTA_PENDING_LISNER
-- Server: 10.253.33.227 | DB: DMAT
--------------------------------------------------






CREATE PROCEDURE [citrus_usr].[PR_RTA_PENDING_LISNER] 
(
@PA_EXCSM_ID NUMERIC,
@PA_CUTOFFDATE DATETIME,
@PA_FROMDT DATETIME,
@PA_TODT DATETIME,
@PA_DRN_NO VARCHAR(30),
@PA_DRF_NO VARCHAR(30),
@PA_FOLLOWUP VARCHAR(20),
@PA_RTA VARCHAR(50),
@PA_ISIN VARCHAR(12),
@PA_ACTION VARCHAR(30),
@PA_FILLER1 VARCHAR(30),
@PA_FILLER2 VARCHAR(30)
)
AS BEGIN


--select *  from temp_rta  return

if (@PA_RTA='-- SELECT --')
set @PA_RTA='0'

declare @l_dpmid int
Select @l_dpmid=dpm_id from dp_mstr where default_dp is not null and DPM_DELETED_IND=1 and dpm_excsm_id=@PA_EXCSM_ID

 if (@PA_FROMDT<>'' and @PA_TODT<>'' )
begin
SELECT  DISTINCT DPAM_ID,DPAM_SBA_NO , DPAM_SBA_NAME , DEMRM_ISIN +'-'+ ISIN_NAME DEMRM_ISIN  ,DATEDIFF(day,DEMRM_REQUEST_DT,getdate()) AS dayss
, DEMRM_TRANSACTION_NO DRN, DEMRM_SLIP_SERIAL_NO DRF
--, DEMRD_FOLIO_NO,DEMRD_DISTINCTIVE_NO_FR,DEMRD_DISTINCTIVE_NO_TO, DEMRD_CERT_NO
,DEMRD_QTY DEMRD_QTY,         
CONVERT(VARCHAR,DEMRM_REQUEST_DT,103) DEMRM_REQUEST_DT
, CONVERT(NUMERIC(18,3),ABS(DEMRD_QTY)) QTY
,''   CATEGORY,ISNULL(DEMRM_TOTAL_CERTIFICATES,'0') NO_OF_CERTIFICATE          
,ISNULL(DPHD_SH_FNAME,'') SECONDHOLDER,ISNULL(DPHD_TH_FNAME,'') THIRDHOLDER 
, DEMRM_FREE_LOCKEDIN_YN  LOCKIN
, ENTM_NAME1+'-'+  ISNULL(ISIN_ADR1,'')+'-'+  ISNULL(ISIN_ADR2,'')+'-'+  ISNULL(ISIN_ADR3,'')+'-'+  ISNULL(isin_adrcity,'')
+'-'+  ISNULL(isin_adrstate,'')+'-'+  ISNULL(isin_adrcountry,'')+'-'+  ISNULL(isin_adrzip,'') ISIN_NAME,ENTM_NAME1  FROM DEMAT_REQUEST_MSTR 
, DMAT_DISPATCH,DEMAT_REQUEST_DTLS
, DP_ACCT_MSTR LEFT OUTER JOIN DP_HOLDER_DTLS DPHD   ON   DPHD_DPAM_ID = DPAM_ID      AND DPHD_DELETED_IND = 1 
, ISIN_MSTR , ENTITY_MSTR         
WHERE 	
DEMRM_DPAM_ID = DPAM_ID  
AND DEMRM_ID = DEMRD_DEMRM_ID     
AND ISNULL(DISP_TO,'') = 'R'   
AND DISP_TYPE ='N'  
AND ISNULL(DEMRM_INTERNAL_REJ,'')  = ''       
AND ISNULL(DEMRM_COMPANY_OBJ,'') = ''      
--AND ISNULL(DEMRM_CREDIT_RECD,'') <> 'Y'         
AND   DEMRM_ID =   DISP_DEMRM_ID    
AND  ISIN_CD = DEMRM_ISIN        
AND  ENTM_SHORT_NAME = CASE WHEN LEFT('12033200',2)='IN' THEN ISIN_REG_CD ELSE 'RTA_'+ISIN_REG_CD END        
AND  ENTM_ENTTM_CD =  CASE WHEN LEFT('12033200',2)='IN' THEN 'SR' ELSE 'RTA' END  
AND DEMRM_DELETED_IND = 1
AND ENTM_DELETED_IND = 1
AND DEMRM_TRANSACTION_NO NOT IN (SELECT  CDSHM_TRANS_NO FROM CDSL_HOLDING_DTLS WHERE CDSHM_CDAS_SUB_TRAS_TYPE in ('605','3207')
AND CDSHM_DELETED_IND=1)
and DPAM_DPM_ID	=@l_dpmid
--and DEMRM_REQUEST_DT<=@PA_CUTOFFDATE
and DEMRM_REQUEST_DT between @PA_FROMDT and @PA_TODT
and DEMRM_TRANSACTION_NO like @PA_DRN_NO + '%'
and demrm_isin like @PA_ISIN + '%'
--and ENTM_NAME1  like @PA_RTA +  '%'
and DEMRM_SLIP_SERIAL_NO like @PA_DRF_NO+'%'
and ENTM_ID like  case when @PA_RTA='0' then '%' else @PA_RTA end 
and DATEDIFF(dd,DEMRM_REQUEST_DT,getdate())>@PA_FOLLOWUP	
order by ENTM_NAME1
end 


 if (@PA_FROMDT='' and @PA_TODT='')
begin 
SELECT  DISTINCT DPAM_ID,DPAM_SBA_NO , DPAM_SBA_NAME , DEMRM_ISIN +'-'+ ISIN_NAME DEMRM_ISIN ,DATEDIFF(day,DEMRM_REQUEST_DT,getdate()) AS dayss
, DEMRM_TRANSACTION_NO DRN, DEMRM_SLIP_SERIAL_NO DRF
---, DEMRD_FOLIO_NO,DEMRD_DISTINCTIVE_NO_FR,DEMRD_DISTINCTIVE_NO_TO, DEMRD_CERT_NO
,DEMRD_QTY DEMRD_QTY,         
CONVERT(VARCHAR,DEMRM_REQUEST_DT,103) DEMRM_REQUEST_DT
, CONVERT(NUMERIC(18,3),ABS(DEMRD_QTY)) QTY
,''   CATEGORY,ISNULL(DEMRM_TOTAL_CERTIFICATES,'0') NO_OF_CERTIFICATE          
,ISNULL(DPHD_SH_FNAME,'') SECONDHOLDER,ISNULL(DPHD_TH_FNAME,'') THIRDHOLDER 
, DEMRM_FREE_LOCKEDIN_YN  LOCKIN
, ENTM_NAME1+'-'+  ISNULL(ISIN_ADR1,'')+'-'+  ISNULL(ISIN_ADR2,'')+'-'+  ISNULL(ISIN_ADR3,'')+'-'+  ISNULL(isin_adrcity,'')
+'-'+  ISNULL(isin_adrstate,'')+'-'+  ISNULL(isin_adrcountry,'')+'-'+  ISNULL(isin_adrzip,'')ISIN_NAME  FROM DEMAT_REQUEST_MSTR 
, DMAT_DISPATCH,DEMAT_REQUEST_DTLS
, DP_ACCT_MSTR LEFT OUTER JOIN DP_HOLDER_DTLS DPHD   ON   DPHD_DPAM_ID = DPAM_ID      AND DPHD_DELETED_IND = 1 
, ISIN_MSTR , ENTITY_MSTR         
WHERE 	
DEMRM_DPAM_ID = DPAM_ID  
AND DEMRM_ID = DEMRD_DEMRM_ID     
AND ISNULL(DISP_TO,'') = 'R'   
AND DISP_TYPE ='N'  
AND ISNULL(DEMRM_INTERNAL_REJ,'')  = ''       
AND ISNULL(DEMRM_COMPANY_OBJ,'') = ''      
--AND ISNULL(DEMRM_CREDIT_RECD,'') <> 'Y'         
AND   DEMRM_ID =   DISP_DEMRM_ID    
AND  ISIN_CD = DEMRM_ISIN        
AND  ENTM_SHORT_NAME = CASE WHEN LEFT('12033200',2)='IN' THEN ISIN_REG_CD ELSE 'RTA_'+ISIN_REG_CD END        
AND  ENTM_ENTTM_CD =  CASE WHEN LEFT('12033200',2)='IN' THEN 'SR' ELSE 'RTA' END  
AND DEMRM_DELETED_IND = 1
AND ENTM_DELETED_IND = 1
AND DEMRM_TRANSACTION_NO NOT IN (SELECT  CDSHM_TRANS_NO FROM CDSL_HOLDING_DTLS WHERE CDSHM_CDAS_SUB_TRAS_TYPE in ('605','3207')
AND CDSHM_DELETED_IND=1)
and DPAM_DPM_ID	=@l_dpmid
and DEMRM_REQUEST_DT<=@PA_CUTOFFDATE

and DEMRM_TRANSACTION_NO like @PA_DRN_NO + '%'
and demrm_isin like @PA_ISIN + '%'
--and ENTM_NAME1  like @PA_RTA +  '%'
and DEMRM_SLIP_SERIAL_NO like @PA_DRF_NO+'%'
and ENTM_ID like  case when @PA_RTA='0' then '%' else @PA_RTA end 
and DATEDIFF(dd,DEMRM_REQUEST_DT,getdate())>=@PA_FOLLOWUP	


end  

END

GO
