-- Object: TABLE citrus_usr.ROLES_ACTIONS_bak_18032021
-- Server: 10.253.33.227 | DB: DMAT
--------------------------------------------------

CREATE TABLE [citrus_usr].[ROLES_ACTIONS_bak_18032021]
(
    [ROLA_ROL_ID] NUMERIC(10, 0) NOT NULL,
    [ROLA_ACT_ID] NUMERIC(10, 0) NOT NULL,
    [ROLA_ACCESS1] NUMERIC(10, 0) NOT NULL,
    [ROLA_CREATED_BY] VARCHAR(25) NOT NULL,
    [ROLA_CREATED_DT] DATETIME NOT NULL,
    [ROLA_LST_UPD_BY] VARCHAR(25) NOT NULL,
    [ROLA_LST_UPD_DT] DATETIME NOT NULL,
    [ROLA_DELETED_IND] SMALLINT NOT NULL
);

GO
