-- Object: PROCEDURE citrus_usr.PR_RPT_BRKRFILE_CHKRPEND
-- Server: 10.253.33.227 | DB: DMAT
--------------------------------------------------

--PR_RPT_BRKRFILE_CHKRPEND 3,'01/04/2008','30/05/2010','ALL','CDSL'
	---3	May 13 2008	May 13 2010	ALL	CDSL
CREATE PROCEDURE [citrus_usr].[PR_RPT_BRKRFILE_CHKRPEND]
(
@PA_DPM_ID INT
,@PA_FROM_DT VARCHAR(11)
,@PA_TO_DT VARCHAR(11) 
,@PA_TRANS_TYPE VARCHAR(20)
,@PA_DP_TYPE VARCHAR(10)

)
AS 

BEGIN 

IF @PA_DP_TYPE='CDSL'
BEGIN 
	IF @PA_TRANS_TYPE='OFFM' 
	BEGIN 
	SELECT DISTINCT DMKR.DPTDC_SLIP_NO slipno,DMKR.DPTDC_CREATED_DT createddt,DMKR.DPTDC_CREATED_BY createby,DMKR.DPTDC_BROKERBATCH_NO brbatchno FROM DPTDC_MAK DMKR WHERE DPTDC_SLIP_NO NOT IN (SELECT DPTDC_SLIP_NO FROM DP_TRX_dTLS_CDSL DMSTR)
	AND ISNULL(DMKR.DPTDC_BROKERBATCH_NO,'') <>'' AND DMKR.DPTDC_TRASTM_CD IN ('BOCM','BOBO','CMBO','CMCM')
    AND DMKR.DPTDC_REQUEST_DT BETWEEN  CONVERT(VARCHAR,CONVERT(DATETIME, @PA_FROM_DT,103),106)+' 00:00:00' AND CONVERT(VARCHAR,CONVERT(DATETIME,@PA_TO_DT,103),106)+' 23:59:59'  
	END

	IF @PA_TRANS_TYPE='NP' 
	BEGIN 
	SELECT DISTINCT DMKR.DPTDC_SLIP_NO slipno,DMKR.DPTDC_CREATED_DT createddt,DMKR.DPTDC_CREATED_BY createby,DMKR.DPTDC_BROKERBATCH_NO brbatchno FROM DPTDC_MAK DMKR WHERE DPTDC_SLIP_NO NOT IN (SELECT DPTDC_SLIP_NO FROM DP_TRX_dTLS_CDSL DMSTR)
	AND ISNULL(DMKR.DPTDC_BROKERBATCH_NO,'') <>'' AND DMKR.DPTDC_TRASTM_CD IN ('NP')
    AND DMKR.DPTDC_REQUEST_DT BETWEEN  CONVERT(VARCHAR,CONVERT(DATETIME, @PA_FROM_DT,103),106)+' 00:00:00' AND CONVERT(VARCHAR,CONVERT(DATETIME,@PA_TO_DT,103),106)+' 23:59:59'  
	END

	IF @PA_TRANS_TYPE='EP' 
	BEGIN 
	SELECT DISTINCT DMKR.DPTDC_SLIP_NO slipno,DMKR.DPTDC_CREATED_DT createddt,DMKR.DPTDC_CREATED_BY createby,DMKR.DPTDC_BROKERBATCH_NO brbatchno FROM DPTDC_MAK DMKR WHERE DPTDC_SLIP_NO NOT IN (SELECT DPTDC_SLIP_NO FROM DP_TRX_dTLS_CDSL DMSTR)
	AND ISNULL(DMKR.DPTDC_BROKERBATCH_NO,'') <>'' AND DMKR.DPTDC_TRASTM_CD IN ('EP')
    AND DMKR.DPTDC_REQUEST_DT BETWEEN  CONVERT(VARCHAR,CONVERT(DATETIME, @PA_FROM_DT,103),106)+' 00:00:00' AND CONVERT(VARCHAR,CONVERT(DATETIME,@PA_TO_DT,103),106)+' 23:59:59'  
	END


	IF @PA_TRANS_TYPE='ID' 
	BEGIN 
	SELECT DISTINCT DMKR.DPTDC_SLIP_NO slipno,DMKR.DPTDC_CREATED_DT createddt,DMKR.DPTDC_CREATED_BY createby,DMKR.DPTDC_BROKERBATCH_NO brbatchno FROM DPTDC_MAK DMKR WHERE DPTDC_SLIP_NO NOT IN (SELECT DPTDC_SLIP_NO FROM DP_TRX_dTLS_CDSL DMSTR)
	AND ISNULL(DMKR.DPTDC_BROKERBATCH_NO,'') <>'' AND DMKR.DPTDC_TRASTM_CD IN ('ID')
    AND DMKR.DPTDC_REQUEST_DT BETWEEN  CONVERT(VARCHAR,CONVERT(DATETIME, @PA_FROM_DT,103),106)+' 00:00:00' AND CONVERT(VARCHAR,CONVERT(DATETIME,@PA_TO_DT,103),106)+' 23:59:59'  
	END

	IF @PA_TRANS_TYPE='ALL' 
	BEGIN 
	SELECT DISTINCT DMKR.DPTDC_SLIP_NO slipno,DMKR.DPTDC_CREATED_DT createddt,DMKR.DPTDC_CREATED_BY createby,DMKR.DPTDC_BROKERBATCH_NO brbatchno FROM DPTDC_MAK DMKR WHERE DPTDC_SLIP_NO NOT IN (SELECT DPTDC_SLIP_NO FROM DP_TRX_dTLS_CDSL DMSTR)
	AND ISNULL(DMKR.DPTDC_BROKERBATCH_NO,'') <>'' 
    AND DMKR.DPTDC_REQUEST_DT BETWEEN  CONVERT(VARCHAR,CONVERT(DATETIME, @PA_FROM_DT,103),106)+' 00:00:00' AND CONVERT(VARCHAR,CONVERT(DATETIME,@PA_TO_DT,103),106)+' 23:59:59'  
	END
   

END 

ELSE

BEGIN 
SELECT DISTINCT DMKR.DPTD_SLIP_NO slipno,DMKR.DPTD_CREATED_DT createddt,DMKR.DPTD_CREATED_BY createby,DMKR.DPTD_BROKERBATCH_NO brbatchno FROM DPTD_MAK DMKR WHERE DPTD_SLIP_NO NOT IN (SELECT DPTD_SLIP_NO FROM DP_TRX_dTLS DMSTR)
AND ISNULL(DMKR.DPTD_BROKERBATCH_NO,'') <>''  
AND DMKR.DPTD_REQUEST_DT BETWEEN  CONVERT(VARCHAR,CONVERT(DATETIME, @PA_FROM_DT,103),106)+' 00:00:00' AND CONVERT(VARCHAR,CONVERT(DATETIME,@PA_TO_DT,103),106)+' 23:59:59'  
END 

END

GO
