-- Object: TABLE citrus_usr.TMP_DPMRESPONSE
-- Server: 10.253.33.227 | DB: DMAT
--------------------------------------------------

CREATE TABLE [citrus_usr].[TMP_DPMRESPONSE]
(
    [TMPDPMRESP_BATCHNO] NUMERIC(7, 0) NULL,
    [TMPDPMRESP_RECTYP] NUMERIC(2, 0) NULL,
    [TMPDPMRESP_LINENO] NUMERIC(5, 0) NULL,
    [TMPDPMRESP_TRANTYP] CHAR(3) NULL,
    [TMPDPMRESP_TRANFLG] CHAR(1) NULL,
    [TMPDPMRESP_INSTID] NUMERIC(18, 0) NULL,
    [TMPDPMRESP_INTREFNO] VARCHAR(20) NULL,
    [TMPDPMRESP_SENDREFNO1] VARCHAR(35) NULL,
    [TMPDPMRESP_SENDREFNO2] VARCHAR(35) NULL,
    [TMPDPMRESP_ISIN] VARCHAR(12) NULL,
    [TMPDPMRESP_ACCPREJFLG] CHAR(1) NULL,
    [TMPDPMRESP_CLOSCONFNO] NUMERIC(7, 0) NULL,
    [TMPDPMRESP_FILLER] VARCHAR(20) NULL
);

GO
