-- Object: TABLE citrus_usr.A_21_07_15_9
-- Server: 10.253.33.227 | DB: DMAT
--------------------------------------------------

CREATE TABLE [citrus_usr].[A_21_07_15_9]
(
    [CONCMAK_ID] NUMERIC(10, 0) NOT NULL,
    [CONC_ENT_ID] NUMERIC(10, 0) NOT NULL,
    [CONC_CONCM_ID] NUMERIC(10, 0) NOT NULL,
    [CONC_CONCM_CD] VARCHAR(20) NOT NULL,
    [CONC_ID] NUMERIC(10, 0) NOT NULL,
    [CONC_VALUE] VARCHAR(50) NOT NULL,
    [CONC_CREATED_BY] VARCHAR(25) NOT NULL,
    [CONC_CREATED_DT] DATETIME NOT NULL,
    [CONC_LST_UPD_BY] VARCHAR(25) NOT NULL,
    [CONC_LST_UPD_DT] DATETIME NOT NULL,
    [CONC_DELETED_IND] SMALLINT NOT NULL
);

GO
