-- Object: TABLE dbo.SETTLEMENT_TYPE_MSTR
-- Server: 10.253.33.227 | DB: DMAT
--------------------------------------------------

CREATE TABLE [dbo].[SETTLEMENT_TYPE_MSTR]
(
    [SETTM_ID] NUMERIC(10, 0) NOT NULL,
    [SETTM_EXCM_ID] NUMERIC(10, 0) NOT NULL,
    [SETTM_TYPE] VARCHAR(20) NULL,
    [SETTM_DESC] VARCHAR(200) NULL,
    [SETTM_CREATED_BY] VARCHAR(25) NOT NULL,
    [SETTM_CREATED_DT] DATETIME NOT NULL,
    [SETTM_LST_UPD_BY] VARCHAR(25) NOT NULL,
    [SETTM_LST_UPD_DT] DATETIME NOT NULL,
    [SETTM_DELETED_IND] SMALLINT NOT NULL,
    [SETTM_TYPE_CDSL] VARCHAR(20) NULL
);

GO
