-- Object: VIEW dbo.VW_CLIENT_DETAILS_ForDp
-- Server: 10.253.33.227 | DB: DMAT
--------------------------------------------------





  
  
CREATE VIEW [dbo].[VW_CLIENT_DETAILS_ForDp]    
AS    
SELECT    
CD.CL_CODE ,CD.REGION,CD.BRANCH_CD,CD.SUB_BROKER,CD.AREA,CD.TRADER,CD.FAMILY,M.CLTDPNO as client_code,M.DEF ,GST_LOCATION AS BASELOCATION  
FROM [AngelNseCM].MSAJAG.DBO.CLIENT_details CD    
INNER JOIN [ANGELDEMAT].MSAJAG.DBO.MULTICLTID M ON CD.CL_CODE=M.PARTY_CODE    
WHERE M.DPTYPE='CDSL'   

UNION  
SELECT    
CD1.CL_CODE,CD1.REGION,CD1.BRANCH_CD,CD1.SUB_BROKER,CD1.AREA,CD1.TRADER,CD1.FAMILY,M1.CLTDPNO as client_code,M1.DEF   ,GST_LOCATION AS BASELOCATION  
FROM [AngelNseCM].MSAJAG.DBO.CLIENT_details CD1    
INNER JOIN [ANGELDEMAT].BSEDB.DBO.MULTICLTID M1 ON CD1.CL_CODE=M1.PARTY_CODE    
WHERE M1.DPTYPE='CDSL'

GO
