-- Object: PROCEDURE dbo.CLASS_AUTO_PROCESS_EDIT_MASTER
-- Server: 10.253.33.91 | DB: NSESLBS
--------------------------------------------------



CREATE PROCEDURE [dbo].[CLASS_AUTO_PROCESS_EDIT_MASTER]   
(  
 @TYPE varchar(1),  
 @PROCESSFOR varchar(30),  
 @PROCESSTYPE varchar(30)  
)   
AS    
  
SELECT @PROCESSFOR = (CASE WHEN @PROCESSFOR = '' THEN '--SELECT--' ELSE @PROCESSFOR END)  
SELECT @PROCESSTYPE = (CASE WHEN @PROCESSTYPE = '' THEN '--SELECT--' ELSE @PROCESSTYPE END)  
-- EXEC CLASS_AUTO_PROCESS_EDIT_MASTER 'E', 'SELECT','SELECT'  
BEGIN    
OPEN SYMMETRIC KEY   Key4CertAutoProcess  
     DECRYPTION BY   CERTIFICATE CertAutoProcess   
  
 IF @TYPE='P'  
 BEGIN  
  SELECT     
   SNO,PROCESS_TYPE,PROCESS_FOR,    
   PROCESS_START_TIME = LEFT(PROCESS_START_TIME,5),      
   PROCESS_END_TIME = LEFT(PROCESS_END_TIME,5) ,    
   IS_FILE_BASED,  
   PROCESS_ORDER_ID,    
   FILE_DWLOAD_LOCATION=.DBO.FN_DATA_DECRYPT('MKTTECH.IN',FILE_DWLOAD_LOCATION),    
   FILE_DWLOAD_NAME=.DBO.FN_DATA_DECRYPT('MKTTECH.IN',FILE_DWLOAD_NAME),    
   FILE_DWLOAD_USERID=.DBO.FN_DATA_DECRYPT('MKTTECH.IN',FILE_DWLOAD_USERID),    
   FILE_DWLOAD_PWD=.DBO.FN_DATA_DECRYPT('MKTTECH.IN',FILE_DWLOAD_PWD),    
   FILE_DWLOAD_MAP_DRIVE,    
   PROCESS_FILE_PATH=.DBO.FN_DATA_DECRYPT('MKTTECH.IN',PROCESS_FILE_PATH),    
   PROCESS_FILE_NAME=.DBO.FN_DATA_DECRYPT('MKTTECH.IN',PROCESS_FILE_NAME),    
   PROCESS_FILE_MOVE_PATH =.DBO.FN_DATA_DECRYPT('MKTTECH.IN',PROCESS_FILE_MOVE_PATH)     
  FROM  TBL_AUTO_PROCESS_MASTER    
  WHERE PROCESS_FOR = (CASE WHEN @PROCESSFOR LIKE '%SELECT%' THEN PROCESS_FOR ELSE @PROCESSFOR END)  
  AND   PROCESS_TYPE = (CASE WHEN @PROCESSTYPE LIKE '%SELECT%' THEN PROCESS_TYPE ELSE @PROCESSTYPE END)  
  ORDER BY PROCESS_TYPE,PROCESS_ORDER_ID,IS_FILE_BASED    
 END  
 IF @TYPE='E'  
 BEGIN  
  SELECT E.PROCESS_FOR,TO_EMAIL_ID,CC_EMAIL_ID,BCC_EMAIL_ID,EMAIL_SEND_FLAG  FROM TBL_AUTO_PROCESS_EMAIL E,  
  TBL_AUTO_PROCESS_MASTER M  
  WHERE E.PROCESS_FOR = M.PROCESS_FOR  
  AND E.PROCESS_FOR = (CASE WHEN @PROCESSFOR LIKE '%SELECT%' THEN E.PROCESS_FOR ELSE @PROCESSFOR END)  
  AND PROCESS_TYPE = (CASE WHEN @PROCESSTYPE LIKE '%SELECT%' THEN PROCESS_TYPE ELSE @PROCESSTYPE END)  
 END  
CLOSE SYMMETRIC KEY   Key4CertAutoProcess;  
END

GO
