-- Object: PROCEDURE dbo.Trade_Consolidation_Proc
-- Server: 10.253.33.91 | DB: NSESLBS
--------------------------------------------------


/*BEGIN TRAN
ROLLBACK*/
CREATE PROCEDURE Trade_Consolidation_Proc
	@SETT_NO VARCHAR(7),
	@SETT_TYPE VARCHAR(2),
	@SAUDA_DATE VARCHAR(10),
	@FROMPARTY VARCHAR(10),
	@TOPARTY VARCHAR(10),
	@SCRIP_CD VARCHAR(12),
	@SERIES VARCHAR(3),
	@SELL_BUY INT,
	@ORGCONTRACTNO VARCHAR(7),
	@MARKETRATE NUMERIC(18,4),
	@PARTIPANTCODE VARCHAR(15),
	@TERMINALID VARCHAR(10),
	@BRANCH_ID VARCHAR(10),
	@ORDER_NO VARCHAR(16),
	@LEVEL INT,
	@SPLITDATA VARCHAR(500),
	@STATUSNAME VARCHAR(50),
	@FROMWHERE VARCHAR(100),
	@XMLDATA VARCHAR(2000),
	@SEL_POS INT,
	@EDITNETRATE INT = 0,
	@CONSOLFLAG SMALLINT = 0,
	@PROCESSON VARCHAR(20) = 'ISETTLEMENT'

AS

/*
BEGIN TRAN
EXEC Trade_Consolidation_Proc '2007157', 'N', '20/08/2007', 'Z01138', 'Z01116', 'MICROTECH', 'EQ', '2', '0284126', 
229.2410, '', '', '', '', 2, '', 'AshokS/Broker/127.0.0.1', 'InsApp .NET Module(/InsApp/TranDetails.aspx)', 
'Z01138,Z01116,200,229.2400,228.5800,1,|', '0', 0, 1 

EXEC Trade_Consolidation_Proc '2007157', 'N', '20/08/2007', 'Z01138', 'Z01116', 'MICROTECH', 'EQ', '2', '0284223', 
229.1600, '', '', '', '', 102, '', 'AshokS/Broker/127.0.0.1', 'InsApp .NET Module(/InsApp/TranDetails.aspx)', 
'Z01138,Z01116,700,229.1600,228.5000,1,|', '0', 0, 0 
ROLLBACK
*/
	SET NOCOUNT ON
	DECLARE
		@CHK_POS INT,
		@CHK_DATA VARCHAR(50),
		@XMLRECORD VARCHAR(100),
		@TOTALQTY INT,
		@ROWCOUNT INT,
		@STARTROW INT,
		@OUTER CURSOR,
		@INNER CURSOR,
		@CONT CURSOR,
		@CONT_PARTY VARCHAR(10),
		@CONT_SNO INT,
		@CONT_CLTYPE VARCHAR(3),
		@NEWCONTNO VARCHAR(7),
		@FPARTY VARCHAR(10),
		@TPARTY VARCHAR(10),
		@TRFQTY INT,
		@MKTRATE NUMERIC(18,4),
		@NETRATE NUMERIC(18,4),

		@F1 VARCHAR(50),
		@QTY INT,
		@ORGQTY INT,
		@TQTY INT,
		@LQTY INT,
		@OUTERVAL VARCHAR(50),
		@SQL VARCHAR(2000),
		@BRKSQL VARCHAR(2000),

		@C1_STATUS INT,
		@C2_STATUS INT

	DECLARE
		@@FROMPARTY VARCHAR(10),
		@@TOPARTY VARCHAR(10),
		@@ORGQTY INT,
		@@TRFQTY INT,
		@@MKTRATE NUMERIC(18,4),
		@@NETRATE NUMERIC(18,4),
		@@CONTRACTNO VARCHAR(7),
		@@ORDER_NO VARCHAR(16),
		@@TRADE_NO VARCHAR(14)

SET @CHK_POS = 1

IF LEN(LTRIM(RTRIM(@XMLDATA))) > 0
	BEGIN
		CREATE TABLE #XMLDATA
		(
			FROMPARTY VARCHAR(10),
			TOPARTY VARCHAR(10),
			TRFQTY INT,
			MKTRATE NUMERIC(18,4),
			NETRATE NUMERIC(18,4),
			GENCONT TINYINT,
			CONTRACTNO VARCHAR(7),
			SNO INT IDENTITY(1,1)
		)
		CREATE TABLE #XMLDATA_ARR
		(
			FROMPARTY VARCHAR(10),
			TOPARTY VARCHAR(10),
			TRFQTY INT,
			MKTRATE NUMERIC(18,4),
			NETRATE NUMERIC(18,4),
			GENCONT TINYINT,
			CONTRACTNO VARCHAR(7),
			SNO INT IDENTITY(1,1)
		)
		WHILE 1 = 1
			BEGIN
				SET @XMLRECORD = .dbo.PIECE(@XMLDATA, '|', @CHK_POS)
				IF @XMLRECORD IS NOT NULL AND @XMLRECORD <> ''
					BEGIN
						INSERT INTO #XMLDATA (FROMPARTY, TOPARTY, TRFQTY, MKTRATE, NETRATE, GENCONT)
						VALUES (.dbo.PIECE(@XMLRECORD, ',', 1), .dbo.PIECE(@XMLRECORD, ',', 2), .dbo.PIECE(@XMLRECORD, ',', 3), .dbo.PIECE(@XMLRECORD, ',', 4), .dbo.PIECE(@XMLRECORD, ',', 5), .dbo.PIECE(@XMLRECORD, ',', 6))
						SET @CHK_POS = @CHK_POS + 1
					END
				ELSE
					BEGIN
						BREAK
					END
			END
			SET @CONT = CURSOR FOR
				SELECT SNO, TOPARTY FROM #XMLDATA WHERE GENCONT = 1
			OPEN @CONT
			FETCH NEXT FROM @CONT INTO @CONT_SNO, @CONT_PARTY
			WHILE @@FETCH_STATUS = 0
				BEGIN
					SELECT
						@CONT_CLTYPE = CL_TYPE
					FROM
						CLIENT1 C1,
						CLIENT2 C2
					WHERE
						C1.CL_CODE = C2.CL_CODE
						AND C2.PARTY_CODE = @CONT_PARTY
					IF @CONT_CLTYPE = 'PRO'
						BEGIN
							UPDATE
								#XMLDATA
							SET
								CONTRACTNO = '0000000'
							WHERE
								TOPARTY = @CONT_PARTY
								AND SNO = @CONT_SNO
							UPDATE
								#XMLDATA
							SET
								CONTRACTNO = '0000000'
							WHERE
								TOPARTY = @CONT_PARTY
								AND SNO <> @CONT_SNO
								AND GENCONT = 0
						END
					ELSE
						BEGIN
							SELECT
								@NEWCONTNO = CONVERT(VARCHAR(7), CONVERT(NUMERIC, CONTRACTNO) + 1)
							FROM
								CONTGEN
							WHERE
								CONVERT(DATETIME, @SAUDA_DATE, 103) BETWEEN START_DATE AND END_DATE

							UPDATE
								CONTGEN
							SET
								CONTRACTNO = @NEWCONTNO
							WHERE
								CONVERT(DATETIME, @SAUDA_DATE, 103) BETWEEN START_DATE AND END_DATE

							SELECT
								@NEWCONTNO = STUFF('0000000', 8 - LEN(@NEWCONTNO), LEN(@NEWCONTNO), @NEWCONTNO)

							UPDATE
								#XMLDATA
							SET
								CONTRACTNO = @NEWCONTNO
							WHERE
								TOPARTY = @CONT_PARTY
								AND SNO = @CONT_SNO

							UPDATE
								#XMLDATA
							SET
								CONTRACTNO = @NEWCONTNO
							WHERE
								TOPARTY = @CONT_PARTY
								AND SNO <> @CONT_SNO
								AND GENCONT = 0
								AND FROMPARTY = TOPARTY
						END
					FETCH NEXT FROM @CONT INTO @CONT_SNO, @CONT_PARTY
				END
			UPDATE
				#XMLDATA
			SET
				CONTRACTNO = ''
			WHERE
				CONTRACTNO IS NULL
			INSERT INTO #XMLDATA_ARR
				(FROMPARTY, TOPARTY, TRFQTY, MKTRATE, NETRATE, GENCONT, CONTRACTNO)
			SELECT FROMPARTY, TOPARTY, TRFQTY, MKTRATE, NETRATE, GENCONT, CONTRACTNO FROM #XMLDATA WHERE FROMPARTY = TOPARTY ORDER BY SNO
			INSERT INTO #XMLDATA_ARR
				(FROMPARTY, TOPARTY, TRFQTY, MKTRATE, NETRATE, GENCONT, CONTRACTNO)
			SELECT FROMPARTY, TOPARTY, TRFQTY, MKTRATE, NETRATE, GENCONT, CONTRACTNO FROM #XMLDATA WHERE FROMPARTY <> TOPARTY ORDER BY SNO

			TRUNCATE TABLE #XMLDATA
			INSERT INTO #XMLDATA (FROMPARTY, TOPARTY, TRFQTY, MKTRATE, NETRATE, GENCONT, CONTRACTNO) SELECT FROMPARTY, TOPARTY, TRFQTY, MKTRATE, NETRATE, GENCONT, CONTRACTNO FROM #XMLDATA_ARR ORDER BY SNO
			DROP TABLE #XMLDATA_ARR
			--SELECT * FROM #XMLDATA
			--RETURN
	END
ELSE
	BEGIN
		SELECT 'NO RECORDS TO SPLIT'
		RETURN
	END
SELECT @TOTALQTY = SUM(TRFQTY) FROM #XMLDATA
SET @CHK_POS = 1

IF @SEL_POS > 0
	BEGIN
		CREATE TABLE #SELECTED (F1 VARCHAR(50), AVAILQTY INT)
		WHILE @CHK_POS <= @SEL_POS
			BEGIN
				INSERT INTO #SELECTED SELECT .dbo.PIECE(@SPLITDATA, '#', @CHK_POS), 0
				SET @CHK_POS = @CHK_POS + 1
			END
		CREATE TABLE #SELECTED_A (F1 VARCHAR(50), QTY INT, ORGQTY INT)
		IF @LEVEL = 2					-- FOR CONTRACT NOS
			BEGIN
				--PRINT 'CONTRACT'
				INSERT INTO #SELECTED_A (F1, QTY, ORGQTY)
				SELECT I.CONTRACTNO, SUM(I.TRADEQTY), SUM(I.TRADEQTY) FROM ISETTLEMENT I, #SELECTED S
				WHERE
					I.CONTRACTNO = S.F1
					AND I.PARTY_CODE = @FROMPARTY
					AND I.SCRIP_CD = @SCRIP_CD
					AND I.SERIES = @SERIES
					AND I.SETT_NO = @SETT_NO
					AND I.SETT_TYPE = @SETT_TYPE
					AND I.SELL_BUY = @SELL_BUY
				GROUP BY
					I.CONTRACTNO
			END
		ELSE IF @LEVEL = 3			-- FOR ORDER NOS.
			BEGIN
				--PRINT 'ORDER'
				INSERT INTO #SELECTED_A (F1, QTY, ORGQTY)
				SELECT I.ORDER_NO, SUM(I.TRADEQTY), SUM(I.TRADEQTY) FROM ISETTLEMENT I, #SELECTED S
				WHERE
					I.ORDER_NO = S.F1
					AND I.PARTY_CODE = @FROMPARTY
					AND I.SCRIP_CD = @SCRIP_CD
					AND I.SERIES = @SERIES
					AND I.SETT_NO = @SETT_NO
					AND I.SETT_TYPE = @SETT_TYPE
					AND I.CONTRACTNO = @ORGCONTRACTNO
					AND I.SELL_BUY = @SELL_BUY
				GROUP BY
					I.ORDER_NO
			END
		ELSE IF @LEVEL = 102			-- FOR ORDER NOS. BUT TRADE TRANSFER
			BEGIN
				--PRINT 'ORDER 102'
				IF @PROCESSON = 'ISETTLEMENT'
					BEGIN
						INSERT INTO #SELECTED_A (F1, QTY, ORGQTY)
						SELECT I.ORDER_NO, SUM(I.TRADEQTY), SUM(I.TRADEQTY) FROM ISETTLEMENT I, #SELECTED S
						WHERE
							I.ORDER_NO = S.F1
							AND I.PARTY_CODE = @FROMPARTY
							AND I.SCRIP_CD = @SCRIP_CD
							AND I.SERIES = @SERIES
							AND I.SETT_NO = @SETT_NO
							AND I.SETT_TYPE = @SETT_TYPE
		--					AND I.CONTRACTNO = @ORGCONTRACTNO
							AND I.SELL_BUY = @SELL_BUY
						GROUP BY
							I.ORDER_NO
					END
				ELSE
					BEGIN
						INSERT INTO #SELECTED_A (F1, QTY, ORGQTY)
						SELECT I.ORDER_NO, SUM(I.TRADEQTY), SUM(I.TRADEQTY) FROM SETTLEMENT I, #SELECTED S
						WHERE
							I.ORDER_NO = S.F1
							AND I.PARTY_CODE = @FROMPARTY
							AND I.SCRIP_CD = @SCRIP_CD
							AND I.SERIES = @SERIES
							AND I.SETT_NO = @SETT_NO
							AND I.SETT_TYPE = @SETT_TYPE
		--					AND I.CONTRACTNO = @ORGCONTRACTNO
							AND I.SELL_BUY = @SELL_BUY
						GROUP BY
							I.ORDER_NO
					END
			END
		ELSE IF @LEVEL = 4			-- FOR TRADE NOS
			BEGIN
				--PRINT 'TRADES'
				IF @ORDER_NO = ''
					BEGIN
						INSERT INTO #SELECTED_A (F1, QTY, ORGQTY)
						SELECT I.TRADE_NO, SUM(I.TRADEQTY), SUM(I.TRADEQTY) FROM ISETTLEMENT I, #SELECTED S
						WHERE
							I.TRADE_NO = S.F1
							AND I.PARTY_CODE = @FROMPARTY
							AND I.SCRIP_CD = @SCRIP_CD
							AND I.SERIES = @SERIES
							AND I.SETT_NO = @SETT_NO
							AND I.SETT_TYPE = @SETT_TYPE
							AND I.CONTRACTNO = @ORGCONTRACTNO
							AND I.SELL_BUY = @SELL_BUY
						GROUP BY
							I.TRADE_NO
					END
				ELSE
					BEGIN
						INSERT INTO #SELECTED_A (F1, QTY, ORGQTY)
						SELECT I.TRADE_NO, SUM(I.TRADEQTY), SUM(I.TRADEQTY) FROM ISETTLEMENT I, #SELECTED S
						WHERE
							I.TRADE_NO = S.F1
							AND I.PARTY_CODE = @FROMPARTY
							AND I.SCRIP_CD = @SCRIP_CD
							AND I.SERIES = @SERIES
							AND I.SETT_NO = @SETT_NO
							AND I.SETT_TYPE = @SETT_TYPE
							AND I.CONTRACTNO = @ORGCONTRACTNO
							AND I.SELL_BUY = @SELL_BUY
							AND I.ORDER_NO = @ORDER_NO
						GROUP BY
							I.TRADE_NO
					END
			END
		ELSE IF @LEVEL = 103			-- FOR TRADE NOS BUT TRADE TRANSFER
			BEGIN
				--PRINT 'TRADES'
				IF @PROCESSON = 'ISETTLEMENT'
					BEGIN
						IF @ORDER_NO = ''
							BEGIN
								INSERT INTO #SELECTED_A (F1, QTY, ORGQTY)
								SELECT I.TRADE_NO, SUM(I.TRADEQTY), SUM(I.TRADEQTY) FROM ISETTLEMENT I, #SELECTED S
								WHERE
									I.TRADE_NO = S.F1
									AND I.PARTY_CODE = @FROMPARTY
									AND I.SCRIP_CD = @SCRIP_CD
									AND I.SERIES = @SERIES
									AND I.SETT_NO = @SETT_NO
									AND I.SETT_TYPE = @SETT_TYPE
		--							AND I.CONTRACTNO = @ORGCONTRACTNO
									AND I.SELL_BUY = @SELL_BUY
								GROUP BY
									I.TRADE_NO
							END
						ELSE
							BEGIN
								INSERT INTO #SELECTED_A (F1, QTY, ORGQTY)
								SELECT I.TRADE_NO, SUM(I.TRADEQTY), SUM(I.TRADEQTY) FROM ISETTLEMENT I, #SELECTED S
								WHERE
									I.TRADE_NO = S.F1
									AND I.PARTY_CODE = @FROMPARTY
									AND I.SCRIP_CD = @SCRIP_CD
									AND I.SERIES = @SERIES
									AND I.SETT_NO = @SETT_NO
									AND I.SETT_TYPE = @SETT_TYPE
		--							AND I.CONTRACTNO = @ORGCONTRACTNO
									AND I.SELL_BUY = @SELL_BUY
									AND I.ORDER_NO = @ORDER_NO
								GROUP BY
									I.TRADE_NO
							END
					END
				ELSE
					BEGIN
						IF @ORDER_NO = ''
							BEGIN
								INSERT INTO #SELECTED_A (F1, QTY, ORGQTY)
								SELECT I.TRADE_NO, SUM(I.TRADEQTY), SUM(I.TRADEQTY) FROM SETTLEMENT I, #SELECTED S
								WHERE
									I.TRADE_NO = S.F1
									AND I.PARTY_CODE = @FROMPARTY
									AND I.SCRIP_CD = @SCRIP_CD
									AND I.SERIES = @SERIES
									AND I.SETT_NO = @SETT_NO
									AND I.SETT_TYPE = @SETT_TYPE
		--							AND I.CONTRACTNO = @ORGCONTRACTNO
									AND I.SELL_BUY = @SELL_BUY
								GROUP BY
									I.TRADE_NO
							END
						ELSE
							BEGIN
								INSERT INTO #SELECTED_A (F1, QTY, ORGQTY)
								SELECT I.TRADE_NO, SUM(I.TRADEQTY), SUM(I.TRADEQTY) FROM SETTLEMENT I, #SELECTED S
								WHERE
									I.TRADE_NO = S.F1
									AND I.PARTY_CODE = @FROMPARTY
									AND I.SCRIP_CD = @SCRIP_CD
									AND I.SERIES = @SERIES
									AND I.SETT_NO = @SETT_NO
									AND I.SETT_TYPE = @SETT_TYPE
		--							AND I.CONTRACTNO = @ORGCONTRACTNO
									AND I.SELL_BUY = @SELL_BUY
									AND I.ORDER_NO = @ORDER_NO
								GROUP BY
									I.TRADE_NO
							END
					END
			END
		SELECT @ROWCOUNT = COUNT(1) FROM #SELECTED_A
		SET @STARTROW = 1
		SET @OUTER = CURSOR FOR
			SELECT F1, QTY FROM #SELECTED_A
		OPEN @OUTER
		FETCH NEXT FROM @OUTER INTO @F1, @QTY
		WHILE @STARTROW <= @ROWCOUNT
			BEGIN
				IF @TOTALQTY < @QTY
					BEGIN
						UPDATE #SELECTED_A SET QTY = @TOTALQTY WHERE F1 = @F1
						BREAK
					END
				ELSE
					BEGIN
						SET @TOTALQTY = @TOTALQTY - @QTY
					END
				FETCH NEXT FROM @OUTER INTO @F1, @QTY
				SET @STARTROW = @STARTROW + 1
			END
		CLOSE @OUTER
		--SELECT * FROM #SELECTED_A
		CREATE TABLE #DISTRIBUTED
		(
			FROMPARTY VARCHAR(10),
			TOPARTY VARCHAR(10),
			ORGQTY INT,
			TRFQTY INT,
			MKTRATE NUMERIC(18,4),
			NETRATE NUMERIC(18,4),
			CONTRACTNO VARCHAR(7),
			ORDER_NO VARCHAR(16),
			TRADE_NO VARCHAR(14),
			NEWCONTRACTNO VARCHAR(7)
		)
		SET @OUTER = CURSOR FOR
			SELECT F1, QTY, ORGQTY FROM #SELECTED_A
		SET @INNER = CURSOR FOR
			SELECT FROMPARTY, TOPARTY, TRFQTY, MKTRATE, NETRATE, ISNULL(CONTRACTNO, '') FROM #XMLDATA
		OPEN @OUTER
		FETCH NEXT FROM @OUTER INTO @F1, @QTY, @ORGQTY
		SET @C1_STATUS = @@FETCH_STATUS

		OPEN @INNER
		FETCH NEXT FROM @INNER INTO @FPARTY, @TPARTY, @TRFQTY, @MKTRATE, @NETRATE, @NEWCONTNO
		SET @C2_STATUS = @@FETCH_STATUS

		SET @LQTY = @QTY
		WHILE @C1_STATUS = 0 AND @C2_STATUS = 0
			BEGIN
				IF @LQTY > @TRFQTY
					BEGIN
						IF @LEVEL = 2
							INSERT INTO #DISTRIBUTED (FROMPARTY, TOPARTY, ORGQTY, TRFQTY, MKTRATE, NETRATE, CONTRACTNO, ORDER_NO, TRADE_NO, NEWCONTRACTNO) SELECT @FPARTY, @TPARTY, @ORGQTY, @TRFQTY, @MKTRATE, @NETRATE, @F1, '%', '%', @NEWCONTNO
						ELSE IF @LEVEL = 3
							INSERT INTO #DISTRIBUTED (FROMPARTY, TOPARTY, ORGQTY, TRFQTY, MKTRATE, NETRATE, CONTRACTNO, ORDER_NO, TRADE_NO, NEWCONTRACTNO) SELECT @FPARTY, @TPARTY, @ORGQTY, @TRFQTY, @MKTRATE, @NETRATE, @ORGCONTRACTNO, @F1, '%', @NEWCONTNO
						ELSE IF @LEVEL = 102
							INSERT INTO #DISTRIBUTED (FROMPARTY, TOPARTY, ORGQTY, TRFQTY, MKTRATE, NETRATE, CONTRACTNO, ORDER_NO, TRADE_NO, NEWCONTRACTNO) SELECT @FPARTY, @TPARTY, @ORGQTY, @TRFQTY, @MKTRATE, @NETRATE, @ORGCONTRACTNO, @F1, '%', @NEWCONTNO
						ELSE IF @LEVEL = 4
							IF @ORDER_NO = ''
								BEGIN
									INSERT INTO #DISTRIBUTED (FROMPARTY, TOPARTY, ORGQTY, TRFQTY, MKTRATE, NETRATE, CONTRACTNO, ORDER_NO, TRADE_NO, NEWCONTRACTNO) SELECT @FPARTY, @TPARTY, @ORGQTY, @TRFQTY, @MKTRATE, @NETRATE, @ORGCONTRACTNO, '%', @F1, @NEWCONTNO
								END
							ELSE
								BEGIN
									INSERT INTO #DISTRIBUTED (FROMPARTY, TOPARTY, ORGQTY, TRFQTY, MKTRATE, NETRATE, CONTRACTNO, ORDER_NO, TRADE_NO, NEWCONTRACTNO) SELECT @FPARTY, @TPARTY, @ORGQTY, @TRFQTY, @MKTRATE, @NETRATE, @ORGCONTRACTNO, @ORDER_NO, @F1, @NEWCONTNO
								END
						ELSE IF @LEVEL = 103
							IF @ORDER_NO = ''
								BEGIN
									INSERT INTO #DISTRIBUTED (FROMPARTY, TOPARTY, ORGQTY, TRFQTY, MKTRATE, NETRATE, CONTRACTNO, ORDER_NO, TRADE_NO, NEWCONTRACTNO) SELECT @FPARTY, @TPARTY, @ORGQTY, @TRFQTY, @MKTRATE, @NETRATE, @ORGCONTRACTNO, '%', @F1, @NEWCONTNO
								END
							ELSE
								BEGIN
									INSERT INTO #DISTRIBUTED (FROMPARTY, TOPARTY, ORGQTY, TRFQTY, MKTRATE, NETRATE, CONTRACTNO, ORDER_NO, TRADE_NO, NEWCONTRACTNO) SELECT @FPARTY, @TPARTY, @ORGQTY, @TRFQTY, @MKTRATE, @NETRATE, @ORGCONTRACTNO, @ORDER_NO, @F1, @NEWCONTNO
								END
						SET @LQTY = @LQTY - @TRFQTY
						FETCH NEXT FROM @INNER INTO @FPARTY, @TPARTY, @TRFQTY, @MKTRATE, @NETRATE, @NEWCONTNO
						SET @C2_STATUS = @@FETCH_STATUS
					END
				ELSE IF @LQTY < @TRFQTY AND @LQTY > 0
					BEGIN
						IF @LEVEL = 2
							INSERT INTO #DISTRIBUTED (FROMPARTY, TOPARTY, ORGQTY, TRFQTY, MKTRATE, NETRATE, CONTRACTNO, ORDER_NO, TRADE_NO, NEWCONTRACTNO) SELECT @FPARTY, @TPARTY, @ORGQTY, @LQTY, @MKTRATE, @NETRATE, @F1, '%', '%', @NEWCONTNO
						ELSE IF @LEVEL = 3
							INSERT INTO #DISTRIBUTED (FROMPARTY, TOPARTY, ORGQTY, TRFQTY, MKTRATE, NETRATE, CONTRACTNO, ORDER_NO, TRADE_NO, NEWCONTRACTNO) SELECT @FPARTY, @TPARTY, @ORGQTY, @LQTY, @MKTRATE, @NETRATE, @ORGCONTRACTNO, @F1, '%', @NEWCONTNO
						ELSE IF @LEVEL = 102
							INSERT INTO #DISTRIBUTED (FROMPARTY, TOPARTY, ORGQTY, TRFQTY, MKTRATE, NETRATE, CONTRACTNO, ORDER_NO, TRADE_NO, NEWCONTRACTNO) SELECT @FPARTY, @TPARTY, @ORGQTY, @LQTY, @MKTRATE, @NETRATE, @ORGCONTRACTNO, @F1, '%', @NEWCONTNO
						ELSE IF @LEVEL = 4
							IF @ORDER_NO = ''
								BEGIN
									INSERT INTO #DISTRIBUTED (FROMPARTY, TOPARTY, ORGQTY, TRFQTY, MKTRATE, NETRATE, CONTRACTNO, ORDER_NO, TRADE_NO, NEWCONTRACTNO) SELECT @FPARTY, @TPARTY, @ORGQTY, @LQTY, @MKTRATE, @NETRATE, @ORGCONTRACTNO, '%', @F1, @NEWCONTNO
								END
							ELSE
								BEGIN
									INSERT INTO #DISTRIBUTED (FROMPARTY, TOPARTY, ORGQTY, TRFQTY, MKTRATE, NETRATE, CONTRACTNO, ORDER_NO, TRADE_NO, NEWCONTRACTNO) SELECT @FPARTY, @TPARTY, @ORGQTY, @LQTY, @MKTRATE, @NETRATE, @ORGCONTRACTNO, @ORDER_NO, @F1, @NEWCONTNO
								END
						ELSE IF @LEVEL = 103
							IF @ORDER_NO = ''
								BEGIN
									INSERT INTO #DISTRIBUTED (FROMPARTY, TOPARTY, ORGQTY, TRFQTY, MKTRATE, NETRATE, CONTRACTNO, ORDER_NO, TRADE_NO, NEWCONTRACTNO) SELECT @FPARTY, @TPARTY, @ORGQTY, @LQTY, @MKTRATE, @NETRATE, @ORGCONTRACTNO, '%', @F1, @NEWCONTNO
								END
							ELSE
								BEGIN
									INSERT INTO #DISTRIBUTED (FROMPARTY, TOPARTY, ORGQTY, TRFQTY, MKTRATE, NETRATE, CONTRACTNO, ORDER_NO, TRADE_NO, NEWCONTRACTNO) SELECT @FPARTY, @TPARTY, @ORGQTY, @LQTY, @MKTRATE, @NETRATE, @ORGCONTRACTNO, @ORDER_NO, @F1, @NEWCONTNO
								END
						SET @TRFQTY = @TRFQTY - @LQTY
						FETCH NEXT FROM @OUTER INTO @F1, @QTY, @ORGQTY
						SET @C1_STATUS = @@FETCH_STATUS
						SET @LQTY = @QTY
					END
				ELSE IF @LQTY = @TRFQTY
					BEGIN
						IF @LEVEL = 2
							INSERT INTO #DISTRIBUTED (FROMPARTY, TOPARTY, ORGQTY, TRFQTY, MKTRATE, NETRATE, CONTRACTNO, ORDER_NO, TRADE_NO, NEWCONTRACTNO) SELECT @FPARTY, @TPARTY, @ORGQTY, @LQTY, @MKTRATE, @NETRATE, @F1, '%', '%', @NEWCONTNO
						ELSE IF @LEVEL = 3
							INSERT INTO #DISTRIBUTED (FROMPARTY, TOPARTY, ORGQTY, TRFQTY, MKTRATE, NETRATE, CONTRACTNO, ORDER_NO, TRADE_NO, NEWCONTRACTNO) SELECT @FPARTY, @TPARTY, @ORGQTY, @LQTY, @MKTRATE, @NETRATE, @ORGCONTRACTNO, @F1, '%', @NEWCONTNO
						ELSE IF @LEVEL = 102
							INSERT INTO #DISTRIBUTED (FROMPARTY, TOPARTY, ORGQTY, TRFQTY, MKTRATE, NETRATE, CONTRACTNO, ORDER_NO, TRADE_NO, NEWCONTRACTNO) SELECT @FPARTY, @TPARTY, @ORGQTY, @LQTY, @MKTRATE, @NETRATE, @ORGCONTRACTNO, @F1, '%', @NEWCONTNO
						ELSE IF @LEVEL = 4
							IF @ORDER_NO = ''
								BEGIN
									INSERT INTO #DISTRIBUTED (FROMPARTY, TOPARTY, ORGQTY, TRFQTY, MKTRATE, NETRATE, CONTRACTNO, ORDER_NO, TRADE_NO, NEWCONTRACTNO) SELECT @FPARTY, @TPARTY, @ORGQTY, @LQTY, @MKTRATE, @NETRATE, @ORGCONTRACTNO, '%', @F1, @NEWCONTNO
								END
							ELSE
								BEGIN
									INSERT INTO #DISTRIBUTED (FROMPARTY, TOPARTY, ORGQTY, TRFQTY, MKTRATE, NETRATE, CONTRACTNO, ORDER_NO, TRADE_NO, NEWCONTRACTNO) SELECT @FPARTY, @TPARTY, @ORGQTY, @LQTY, @MKTRATE, @NETRATE, @ORGCONTRACTNO, @ORDER_NO, @F1, @NEWCONTNO
								END
						ELSE IF @LEVEL = 103
							IF @ORDER_NO = ''
								BEGIN
									INSERT INTO #DISTRIBUTED (FROMPARTY, TOPARTY, ORGQTY, TRFQTY, MKTRATE, NETRATE, CONTRACTNO, ORDER_NO, TRADE_NO, NEWCONTRACTNO) SELECT @FPARTY, @TPARTY, @ORGQTY, @LQTY, @MKTRATE, @NETRATE, @ORGCONTRACTNO, '%', @F1, @NEWCONTNO
								END
							ELSE
								BEGIN
									INSERT INTO #DISTRIBUTED (FROMPARTY, TOPARTY, ORGQTY, TRFQTY, MKTRATE, NETRATE, CONTRACTNO, ORDER_NO, TRADE_NO, NEWCONTRACTNO) SELECT @FPARTY, @TPARTY, @ORGQTY, @LQTY, @MKTRATE, @NETRATE, @ORGCONTRACTNO, @ORDER_NO, @F1, @NEWCONTNO
								END
						FETCH NEXT FROM @OUTER INTO @F1, @QTY, @ORGQTY
						SET @C1_STATUS = @@FETCH_STATUS
						SET @LQTY = @QTY
						
						FETCH NEXT FROM @INNER INTO @FPARTY, @TPARTY, @TRFQTY, @MKTRATE, @NETRATE, @NEWCONTNO
						SET @C2_STATUS = @@FETCH_STATUS
					END
			END
		CLOSE @OUTER
		CLOSE @INNER
		DEALLOCATE @INNER
		SET @OUTER = CURSOR FOR
			SELECT LTRIM(RTRIM(FROMPARTY)), LTRIM(RTRIM(TOPARTY)), ORGQTY, TRFQTY, MKTRATE, NETRATE, LTRIM(RTRIM(CONTRACTNO)), LTRIM(RTRIM(ORDER_NO)), LTRIM(RTRIM(TRADE_NO)), LTRIM(RTRIM(NEWCONTRACTNO)) FROM #DISTRIBUTED
		OPEN @OUTER
		FETCH NEXT FROM @OUTER INTO @@FROMPARTY, @@TOPARTY, @@ORGQTY, @@TRFQTY, @@MKTRATE, @@NETRATE, @@CONTRACTNO, @@ORDER_NO, @@TRADE_NO, @NEWCONTNO
		WHILE @@FETCH_STATUS = 0
			BEGIN
				/*SELECT
					@TQTY = SUM(TRADEQTY)
				FROM
					ISETTLEMENT
				WHERE
					PARTY_CODE = @@FROMPARTY
					AND SCRIP_CD = @SCRIP_CD
					AND SERIES = @SERIES
					AND SETT_NO = @SETT_NO
					AND SETT_TYPE = @SETT_TYPE
					AND SELL_BUY = @SELL_BUY
					AND CONTRACTNO = @@CONTRACTNO
					AND ORDER_NO LIKE @@ORDER_NO
					AND TRADE_NO LIKE @@TRADE_NO
				IF @TQTY = @@ORGQTY
					BEGIN*/
				IF @LEVEL = 101 OR @LEVEL = 102 OR @LEVEL = 103
					BEGIN
						SET @SQL = "EXEC NSE_AfterContCursor_Ins_Internal '" + @SETT_NO + "', '" + @SETT_TYPE + "', "
						SET @SQL = @SQL + "'" + CONVERT(VARCHAR(11), CONVERT(DATETIME, @SAUDA_DATE, 103), 109) + "', "
						SET @SQL = @SQL + "'" + @@FROMPARTY + "', '" + @@TOPARTY + "', '" + @SCRIP_CD + "', '" + @SERIES + "', "
						SET @SQL = @SQL + CONVERT(VARCHAR, @SELL_BUY) + ", '" + @@CONTRACTNO + "', "
						SET @SQL = @SQL + CONVERT(VARCHAR, @@MKTRATE) + ", '%', '" + @TERMINALID + "', '%', "
						SET @SQL = @SQL + "'" + @@ORDER_NO + "', '" + @@TRADE_NO + "', " + CONVERT(VARCHAR, @@TRFQTY) + ", "
						SET @SQL = @SQL + "'" + @NEWCONTNO + "', '" + @STATUSNAME + "', '" + @FROMWHERE + "'"
						--PRINT @SQL
						EXEC(@SQL)
					END
				ELSE
					BEGIN
						SET @SQL = "EXEC NSE_AfterContCursor_Ins '" + @SETT_NO + "', '" + @SETT_TYPE + "', "
						SET @SQL = @SQL + "'" + CONVERT(VARCHAR(11), CONVERT(DATETIME, @SAUDA_DATE, 103), 109) + "', "
						SET @SQL = @SQL + "'" + @@FROMPARTY + "', '" + @@TOPARTY + "', '" + @SCRIP_CD + "', '" + @SERIES + "', "
						SET @SQL = @SQL + CONVERT(VARCHAR, @SELL_BUY) + ", '" + @@CONTRACTNO + "', "
						SET @SQL = @SQL + CONVERT(VARCHAR, @@MKTRATE) + ", '%', '" + @TERMINALID + "', '%', "
						SET @SQL = @SQL + "'" + @@ORDER_NO + "', '" + @@TRADE_NO + "', " + CONVERT(VARCHAR, @@TRFQTY) + ", "
						SET @SQL = @SQL + "'" + @NEWCONTNO + "', '" + @STATUSNAME + "', '" + @FROMWHERE + "', " + CONVERT(VARCHAR(1), @CONSOLFLAG)
						--PRINT @SQL
						EXEC(@SQL)
--						IF @EDITNETRATE = 1
--							BEGIN
								SET @BRKSQL = "EXEC NSESettBrokEditIns '" + @SETT_NO + "', '" + @SETT_TYPE + "', "
								SET @BRKSQL = @BRKSQL + "'" + @TPARTY + "', '" + @SCRIP_CD + "', '" + @SERIES + "', "
								SET @BRKSQL = @BRKSQL + "'" + CONVERT(VARCHAR(11), CONVERT(DATETIME, @SAUDA_DATE, 103), 109) + "', "
								SET @BRKSQL = @BRKSQL + "'" + CONVERT(VARCHAR, @SELL_BUY) + "', '%', '" + @@ORDER_NO + "', "
								SET @BRKSQL = @BRKSQL + "'" + @@CONTRACTNO + "', '" + @@TRADE_NO + "', " + CONVERT(VARCHAR(23), @@MKTRATE) + ", "
								SET @BRKSQL = @BRKSQL + "0, " + CONVERT(VARCHAR(23), @@NETRATE) + ", 1, 0, '" + @STATUSNAME + "', "
								SET @BRKSQL = @BRKSQL + "'" + @FROMWHERE + "'"
								EXEC (@BRKSQL)
--							END
					END
			--END
			/*	ELSE
					BEGIN
						RAISERROR('Total Quantity and Processed Quantity does not match. Somebody must have modified the Data from other Terminal', 16, 1)
						RETURN
					END*/
				FETCH NEXT FROM @OUTER INTO @@FROMPARTY, @@TOPARTY, @@ORGQTY, @@TRFQTY, @@MKTRATE, @@NETRATE, @@CONTRACTNO, @@ORDER_NO, @@TRADE_NO, @NEWCONTNO
			END
		--SELECT * FROM #DISTRIBUTED
		--RETURN
	END
ELSE
	BEGIN
		CREATE TABLE #XMLDATA_A
		(
			FROMPARTY VARCHAR(10),
			TOPARTY VARCHAR(10),
			TRFQTY INT,
			MKTRATE NUMERIC(18,4),
			NETRATE NUMERIC(18,4),
			CONTRACTNO VARCHAR(7),
			NEWCONTRACT VARCHAR(7)
		)
		INSERT INTO #XMLDATA_A (FROMPARTY, TOPARTY, TRFQTY, MKTRATE, NETRATE, CONTRACTNO, NEWCONTRACT)
		SELECT FROMPARTY, TOPARTY, TRFQTY, MKTRATE, NETRATE, @ORGCONTRACTNO, CONTRACTNO FROM #XMLDATA
		DECLARE
			@@XMLCURSOR CURSOR,
			@@MKRATE NUMERIC(18, 4),
			@@NTRATE NUMERIC(18, 4)
		SET @@XMLCURSOR = CURSOR FOR
			SELECT FROMPARTY, TOPARTY, TRFQTY, MKTRATE, NETRATE, CONTRACTNO, ISNULL(NEWCONTRACT, '') FROM #XMLDATA_A
		OPEN @@XMLCURSOR
		FETCH NEXT FROM @@XMLCURSOR INTO @FPARTY, @TPARTY, @TRFQTY, @@MKRATE, @@NTRATE, @@CONTRACTNO, @NEWCONTNO
		WHILE @@FETCH_STATUS = 0
			BEGIN
				IF @LEVEL = 101 OR @LEVEL = 102 OR @LEVEL = 103
					BEGIN
						SET @SQL = "EXEC NSE_AfterContCursor_Ins_Internal '" + @SETT_NO + "', '" + @SETT_TYPE + "', '" + CONVERT(VARCHAR(11), CONVERT(DATETIME, @SAUDA_DATE, 103), 109) + "', "
						SET @SQL = @SQL + "'" + @FPARTY + "', '" + @TPARTY + "', '" + @SCRIP_CD + "', '" + @SERIES + "', " + CONVERT(VARCHAR, @SELL_BUY) + ", "
						SET @SQL = @SQL + "'" + @@CONTRACTNO + "', " + CONVERT(VARCHAR(23), @@MKRATE) + ", '%', '" + ISNULL(@TERMINALID, '') + "', '%', '%', '%', "
						SET @SQL = @SQL + CONVERT(VARCHAR, @TRFQTY) + ", '" + @NEWCONTNO + "', '" + @STATUSNAME + "', '" + @FROMWHERE + "'"
					END
				ELSE
					BEGIN
						SET @SQL = "EXEC NSE_AfterContCursor_Ins '" + @SETT_NO + "', '" + @SETT_TYPE + "', '" + CONVERT(VARCHAR(11), CONVERT(DATETIME, @SAUDA_DATE, 103), 109) + "', "
						SET @SQL = @SQL + "'" + @FPARTY + "', '" + @TPARTY + "', '" + @SCRIP_CD + "', '" + @SERIES + "', " + CONVERT(VARCHAR, @SELL_BUY) + ", "
						SET @SQL = @SQL + "'" + @@CONTRACTNO + "', " + CONVERT(VARCHAR(23), @@MKRATE) + ", '%', '" + ISNULL(@TERMINALID, '') + "', '%', '%', '%', "
						SET @SQL = @SQL + CONVERT(VARCHAR, @TRFQTY) + ", '" + @NEWCONTNO + "', '" + @STATUSNAME + "', '" + @FROMWHERE + "', " + CONVERT(VARCHAR(1), @CONSOLFLAG)
--						IF @EDITNETRATE = 1
--							BEGIN
								SET @BRKSQL = "EXEC NSESettBrokEditIns '" + @SETT_NO + "', '" + @SETT_TYPE + "', "
								SET @BRKSQL = @BRKSQL + "'" + @TPARTY + "', '" + @SCRIP_CD + "', '" + @SERIES + "', "
								SET @BRKSQL = @BRKSQL + "'" + CONVERT(VARCHAR(11), CONVERT(DATETIME, @SAUDA_DATE, 103), 109) + "', "
								SET @BRKSQL = @BRKSQL + "'" + CONVERT(VARCHAR, @SELL_BUY) + "', '%', '%', "
								SET @BRKSQL = @BRKSQL + "'" + @@CONTRACTNO + "', '%', " + CONVERT(VARCHAR(23), @@MKTRATE) + ", "
								SET @BRKSQL = @BRKSQL + "0, " + CONVERT(VARCHAR(23), @@NTRATE) + ", 1, 0, '" + @STATUSNAME + "', "
								SET @BRKSQL = @BRKSQL + "'" + @FROMWHERE + "'"
--							END
					END
				EXEC(@SQL)
				EXEC(@BRKSQL)
				--PRINT @SQL
				--PRINT @BRKSQL
				FETCH NEXT FROM @@XMLCURSOR INTO @FPARTY, @TPARTY, @TRFQTY, @@MKRATE, @@NTRATE, @@CONTRACTNO, @NEWCONTNO
			END
	END

GO
