-- Object: PROCEDURE dbo.CBO_Func_SplitString
-- Server: 10.253.33.91 | DB: NSESLBS
--------------------------------------------------


CREATE  PROCEDURE [dbo].[CBO_Func_SplitString]
			@INPUT_STRING VARCHAR(1000)
AS         	
			DECLARE 
			@DELIMETER 	   VARCHAR(10),  
			@REMAININGSTRING   VARCHAR(1000),  
			@CURRSTRING        VARCHAR(1000),  
			@FOUNDAT           INTEGER,  
			@DELIMETERLENGTH   INT,  
			@OUTPUT_STRING     VARCHAR(500)

			SET @DELIMETERLENGTH = 1
			SET @REMAININGSTRING = @INPUT_STRING

WHILE @REMAININGSTRING <> ''  
	BEGIN  
	   SET @FOUNDAT = 0  
	   SET @FOUNDAT =  PATINDEX('%,%',@REMAININGSTRING)  
	   	IF @FOUNDAT > 0  
		   	BEGIN  
		  
		     		SET @CURRSTRING = SUBSTRING(@REMAININGSTRING, 0,@FOUNDAT)
				SET @OUTPUT_STRING = @CURRSTRING  
				print convert(varchar,@OUTPUT_STRING)
		     		SET @REMAININGSTRING = SUBSTRING(@REMAININGSTRING, @FOUNDAT+@DELIMETERLENGTH,LEN(@REMAININGSTRING)-@FOUNDAT+@DELIMETERLENGTH)  
		   	END  
	   	ELSE  
		   	BEGIN  
				SET @CURRSTRING      = @REMAININGSTRING  
				SET @REMAININGSTRING = ''  
	      
	   		END 
	   
	
END

GO
