-- Object: PROCEDURE dbo.CLASS_AUTO_PROCESS_BULK_UPDATE
-- Server: 10.253.33.91 | DB: NSESLBS
--------------------------------------------------



create PROCEDURE [dbo].[CLASS_AUTO_PROCESS_BULK_UPDATE]   
(  
 @UPD_DATA VARCHAR(MAX)  
)  
--NEWDATA~NEWDATA~NEWDATA~OLDDATA~OLDDATA~OLDDATA|  
AS  
--exec CLASS_AUTO_PROCESS_BULK_UPDATE @UPD_DATA='ftp.connect2nse.com~10412~Most@123~FTP.CONNECT2NSE.COM~10412~MOST@123|FTP.CONNECT2NSE.COM~10412~MOST@123~ftp.connect2nse.com~10412~Most@123|NEWDATA~NEWDATA~NEWDATA~OLDDATA~OLDDATA~OLDDATA|'  
BEGIN  
  
 DECLARE @RECNO INT,  
   @OLDFILE_DWLOAD_LOCATION VARCHAR(MAX),  
   @OLDFILE_DWLOAD_USERID  VARCHAR(MAX),  
   @OLDFILE_DWLOAD_PWD   VARCHAR(MAX),  
  
   @NEWFILE_DWLOAD_LOCATION VARCHAR(MAX),  
   @NEWFILE_DWLOAD_USERID  VARCHAR(MAX),  
   @NEWFILE_DWLOAD_PWD   VARCHAR(MAX)  
  
  
 SET @RECNO = 1  
  
 OPEN SYMMETRIC KEY   Key4CertAutoProcess            
   DECRYPTION BY   CERTIFICATE CertAutoProcess  
  
 WHILE ISNULL(.DBO.PIECE(@UPD_DATA,'|',@RECNO),'') <> ''  
 BEGIN  
  SELECT      
   @NEWFILE_DWLOAD_LOCATION = .DBO.PIECE(ISNULL(.DBO.PIECE(@UPD_DATA,'|',@RECNO),''),'~',1),  
   @NEWFILE_DWLOAD_USERID = .DBO.PIECE(ISNULL(.DBO.PIECE(@UPD_DATA,'|',@RECNO),''),'~',2),  
   @NEWFILE_DWLOAD_PWD = .DBO.PIECE(ISNULL(.DBO.PIECE(@UPD_DATA,'|',@RECNO),''),'~',3),  
   @OLDFILE_DWLOAD_LOCATION = ISNULL(.DBO.PIECE(ISNULL(.DBO.PIECE(@UPD_DATA,'|',@RECNO),''),'~',4),''),  
   @OLDFILE_DWLOAD_USERID = ISNULL(.DBO.PIECE(ISNULL(.DBO.PIECE(@UPD_DATA,'|',@RECNO),''),'~',5),''),  
   @OLDFILE_DWLOAD_PWD = ISNULL(.DBO.PIECE(ISNULL(.DBO.PIECE(@UPD_DATA,'|',@RECNO),''),'~',6),'')  
  
  UPDATE TBL_AUTO_PROCESS_MASTER SET  
  FILE_DWLOAD_LOCATION=DBO.FN_DATA_ENCRYPT('MKTTECH.IN',@NEWFILE_DWLOAD_LOCATION),  
  FILE_DWLOAD_USERID=DBO.FN_DATA_ENCRYPT('MKTTECH.IN',@NEWFILE_DWLOAD_USERID),  
  FILE_DWLOAD_PWD=DBO.FN_DATA_ENCRYPT('MKTTECH.IN',@NEWFILE_DWLOAD_PWD)  
  WHERE DBO.FN_DATA_DECRYPT('MKTTECH.IN',FILE_DWLOAD_LOCATION) = @OLDFILE_DWLOAD_LOCATION  
     AND DBO.FN_DATA_DECRYPT('MKTTECH.IN',FILE_DWLOAD_USERID) = @OLDFILE_DWLOAD_USERID  
     AND DBO.FN_DATA_DECRYPT('MKTTECH.IN',FILE_DWLOAD_PWD) = @OLDFILE_DWLOAD_PWD  
  
  SET @RECNO = @RECNO + 1   
 END  
 CLOSE SYMMETRIC KEY   Key4CertAutoProcess;    
 SELECT ERRCODE='0',MESSAGETEXT='Process Completed Successfully'  
END

GO
