-- Object: PROCEDURE dbo.FASTTRADE_ClientMaster
-- Server: 10.253.33.91 | DB: NSESLBS
--------------------------------------------------

CREATE Procedure FASTTRADE_ClientMaster ( @TradeDate Varchar(11))  AS      
      
SELECT RTRIM(LOGINID), RTRIM(OWNERID), RTRIM(BACKOFFICEID), RTRIM(USERTYPE), RTRIM(PASSWORD),      
(CASE WHEN LEN(RTRIM(FIRSTNAME)) = 0 THEN RTRIM(LOGINID) ELSE RTRIM(FIRSTNAME) END),RTRIM(LASTNAME),      
(CASE WHEN LEN(RTRIM(EMAIL)) = 0 THEN 'a' ELSE RTRIM(EMAIL) END),RTRIM(DEFAULTMARKETWATCH),
RTRIM(MOBILE_PAGER)     
FROM (      
SELECT DISTINCT
LOGINID = PARTY_CODE,       
OWNERID = 'BALAV',       
BACKOFFICEID = PARTY_CODE,      
USERTYPE = 1,      
PASSWORD = '123456',      
FIRSTNAME = LONG_NAME,      
LASTNAME = '',      
EMAIL = EMAIL,      
DEFAULTMARKETWATCH = 'Y',      
FLAG=3,
MOBILE_PAGER = ISNULL(MOBILE_PAGER,'')
FROM MSAJAG.DBO.CLIENT_DETAILS C1, MSAJAG.DBO.CLIENT_BROK_DETAILS C2      
WHERE C1.CL_CODE = C2.CL_CODE AND LEN(C1.CL_CODE) <= 8) A      
ORDER BY FLAG, 2

GO
