-- Object: PROCEDURE dbo.RPT_REGISTERSECURITIES
-- Server: 10.253.33.91 | DB: NSESLBS
--------------------------------------------------


CREATE  PROC RPT_REGISTERSECURITIES
	(
	@FROMDATE VARCHAR(11),
	@TODATE VARCHAR(11),
	@FROMSETT_NO VARCHAR(10),
	@TOSETT_NO VARCHAR(10),
	@FROMPARTY VARCHAR(15),
	@TOPARTY VARCHAR(15)
	)

	AS
	
	IF (@TOPARTY = '')
	BEGIN
		SELECT @TOPARTY = 'ZZZZZZZZZZZZ'
	END

	IF (@FROMSETT_NO = '')
	BEGIN
		SELECT @FROMSETT_NO = MIN(SETT_NO) FROM DELTRANS_REPORT WHERE PARTY_CODE BETWEEN @FROMPARTY AND @TOPARTY
	END 

	IF (@TOSETT_NO = '')
	BEGIN
		SELECT @TOSETT_NO = MAX(SETT_NO) FROM DELTRANS_REPORT WHERE PARTY_CODE BETWEEN @FROMPARTY AND @TOPARTY
	END 

	IF (@FROMDATE = '')
	BEGIN
		SELECT @FROMDATE = MIN(LEFT(TRANSDATE,11)) FROM DELTRANS_REPORT WHERE PARTY_CODE BETWEEN @FROMPARTY AND @TOPARTY
	END 

	IF (@TODATE = '')
	BEGIN
		SELECT @TODATE = MAX(LEFT(TRANSDATE,11)) FROM DELTRANS_REPORT WHERE PARTY_CODE BETWEEN @FROMPARTY AND @TOPARTY
	END 

	SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED
	SELECT 
		EXCHANGE = 'NSE', SEGMENT = 'CASH', 
		D.PARTY_CODE, 
		SETT_NO, 
		SETT_TYPE, 
		D.SCRIP_CD, 
		D.SERIES, 
		SCRIP_NAME = S2.SCRIP_CD, 
		QTY, 
		SELL_BUY = (CASE WHEN DRCR = 'C' THEN 'SELL' ELSE 'BUY' END), 
		TRANSDATE = CONVERT(VARCHAR, TRANSDATE, 103), 
		CERTNO, 
		FROMNO, 
		HOLDERNAME, 
		REASON, 
		CLTDPID, 
		DPID, 
		DELIVERED = 
			(CASE 
			WHEN DRCR = 'C' THEN 'RECIEVED'
			WHEN DRCR = 'D' AND DELIVERED = '0' THEN 'PENDING'
			WHEN DRCR = 'D' AND DELIVERED = 'G' THEN 'GENERATED'
			WHEN DRCR = 'D' AND DELIVERED = 'D' THEN 'DELIVERED'
		     END),
		BCLTDPID, 
		BDPID
	FROM 
		DELTRANS_REPORT D (NOLOCK), 
		SCRIP2 S2 (NOLOCK)
	WHERE 
		D.SETT_NO BETWEEN @FROMSETT_NO AND @TOSETT_NO 
		AND D.SCRIP_CD = S2.SCRIP_CD
		AND D.SERIES = S2.SERIES 
		AND D.PARTY_CODE BETWEEN @FROMPARTY AND @TOPARTY 
		AND D.TRANSDATE BETWEEN @FROMDATE AND @TODATE + ' 23:59'
		AND FILLER2 = 1 AND TRTYPE <> 906
		AND PARTY_CODE <> 'BROKER'
	
	ORDER BY 
		PARTY_CODE, 
		D.SCRIP_CD, 
		SETT_NO, 
		SETT_TYPE, 
		TRANSDATE

GO
