-- Object: PROCEDURE dbo.GET_PWD_EXPIRY
-- Server: 10.253.33.91 | DB: NSESLBS
--------------------------------------------------



CREATE PROC GET_PWD_EXPIRY
(
  @UNAME VARCHAR(100)
)
AS
SELECT LTRIM(RTRIM(T.FLDFIRSTNAME)) AS FIRSTNAME,   
 CASE WHEN DATEDIFF (DD, GETDATE(), T.PWD_EXPIRY_DATE) = 2  THEN  'THE DAY AFTER TOMORROW'  
 ELSE  
 	CASE WHEN  DATEDIFF (DD, GETDATE(), T.PWD_EXPIRY_DATE) = 1  THEN  'TOMORROW'  
 ELSE  
	CASE WHEN  DATEDIFF (DD, GETDATE(), T.PWD_EXPIRY_DATE) = 0  THEN  '<U>TODAY</U>'  
 ELSE  
	'ON ' + LEFT(CONVERT(VARCHAR, T.PWD_EXPIRY_DATE, 109), 11)  
END 
END 
END  
 AS PWD_EXPIRY_DATE  
 FROM  
	TBLPRADNYAUSERS T, TBLADMIN A 
 WHERE  
	T.FLDADMINAUTO = A.FLDAUTO_ADMIN  
	AND T.FLDUSERNAME = @UNAME 
	AND GETDATE() <= T.PWD_EXPIRY_DATE

GO
