-- Object: PROCEDURE dbo.PROC_NSE_TRADEIMPORT
-- Server: 10.253.33.91 | DB: NSESLBS
--------------------------------------------------

  
        
CREATE  PROC [dbo].[PROC_NSE_TRADEIMPORT]           
(          
 @SNO   NUMERIC(18,0),          
 @SUBPROCESSID INT,          
 @FILETYPE  VARCHAR(10),          
 @SAUDA_DATE  VARCHAR(11),          
 @FILEPATH  VARCHAR(200)          
)          
AS          
-- EXEC PROC_NSE_TRADEIMPORT 7,0,'NOTIS','Nov  3 2014','c:\temp\20141103\03112014_09900.txt'          
DECLARE @SQL  VARCHAR(MAX),          
  @TRADEQTY NUMERIC(18,0),          
  @CONFIRMQTY NUMERIC(18,0),          
  @TRADEAMT NUMERIC(18,4),          
  @CONFIRMAMT NUMERIC(18,4),          
  @RECCNT  NUMERIC(18,0),        
  @PREVDATE VARCHAR(11)          
          
SELECT @PREVDATE = MAX(START_DATE) FROM SETT_MST WHERE SETT_TYPE = 'N' AND START_dATE < @SAUDA_DATE        
          
IF @SUBPROCESSID = 0           
BEGIN          
 TRUNCATE TABLE TRADE_IMP_NOTIS          
 TRUNCATE TABLE TRADE          
 TRUNCATE TABLE FTTRADE          
  
 IF @FILETYPE = 'NOTIS'           
 BEGIN          
  BEGIN TRY          
  -- EXEC InstMaster_FromNormalServer 'SAMSUNG'      
   EXEC V2_PROCESSEOD 'EOD', 'AUTO', @PREVDATE        
         
   SET @SQL = LOWER('BULK INSERT TRADE_IMP_NOTIS FROM ''' + @FILEPATH + ''' WITH  (FIELDTERMINATOR = '','', ROWTERMINATOR = ''\N'' )')          
  
   EXEC (@SQL)          
  END TRY          
  BEGIN CATCH          
   UPDATE TBL_AUTO_PROCESS_DETAIL SET SUB_PROCESS_ID = 0,          
   PROCESS_HALTED_REASON = ERROR_MESSAGE(),          
   PROCESS_STATUS = 98, PROCESS_ENDED_DATE = GETDATE(),          
   PROCESS_OUTPUT_QUERY = '',   
   PROCESS_STATUS_ALERT_COUNT = 0          
   WHERE SNO = @SNO AND PROCESS_STATUS = 99            
   RETURN          
  END CATCH          
        
  EXEC UPDATETRADE_NOTIS          
 END          
          
 IF (SELECT ISNULL(COUNT(1),0) FROM TRADE WHERE LEFT(SAUDA_DATE,11) <> @SAUDA_DATE) > 0          
 BEGIN          
  UPDATE TBL_AUTO_PROCESS_DETAIL SET           
  PROCESS_HALTED_REASON = 'SELECTED FILE IS HAVING SOME OTHER DATE DATA THAN THE BUSINESS DATE.',          
  PROCESS_STATUS = 98, PROCESS_ENDED_DATE = GETDATE(),   
   PROCESS_STATUS_ALERT_COUNT = 0                   
  WHERE SNO = @SNO AND PROCESS_STATUS = 99          
          
  TRUNCATE TABLE TRADE          
            
  RETURN          
 END          
            
 IF 1 = 2           
 BEGIN          
  UPDATE TBL_AUTO_PROCESS_DETAIL SET           
  PROCESS_HALTED_REASON = 'NOT ALLOW TO IMPORT THE DATA OF OTHER THEN THE PROCESS DATE SET AS BOD.',          
  PROCESS_STATUS = 98, PROCESS_ENDED_DATE = GETDATE(),   
   PROCESS_STATUS_ALERT_COUNT = 0                   
  WHERE SNO = @SNO AND PROCESS_STATUS = 99          
          
  TRUNCATE TABLE TRADE          
            
  RETURN          
 END          
 ELSE          
 BEGIN         
   EXEC DUPRECCHECK          
	UPDATE TRADE SET Instrument= 1 
             
   --EXEC DUPRECCHECK_CTCLID          
          
   --EXEC DUPRECCHECK_PRODUCT          
             
   INSERT INTO STAT_TRD VALUES ('I10', @SAUDA_DATE + ' ' + CONVERT(VARCHAR,GETDATE(),108),@SAUDA_DATE,GETDATE())          
   SET @SUBPROCESSID = 1          
 END          
END          
          
IF @SUBPROCESSID = 1 OR @SUBPROCESSID = 0          
BEGIN          
 UPDATE TRADE SET DUMMY1 = MARKETRATE          
           
 EXEC DUPRECSETTCHECK          
          
 INSERT INTO STAT_TRD VALUES ('I20', @SAUDA_DATE + ' ' + CONVERT(VARCHAR,GETDATE(),108),@SAUDA_DATE,GETDATE())          
          
 IF (SELECT ISNULL(COUNT(1),0) FROM TRADE)  = 0          
 BEGIN          
  UPDATE TBL_AUTO_PROCESS_DETAIL SET SUB_PROCESS_ID = 1,          
  PROCESS_HALTED_REASON = 'ALL TRADES ARE DELETED BECAUSE OF DUPLICATION.',          
  PROCESS_STATUS = 100, PROCESS_ENDED_DATE = GETDATE(), PROCESS_STATUS_ALERT_INTERVAL = '00:00:00',   
   PROCESS_STATUS_ALERT_COUNT = 0                  
  WHERE SNO = @SNO AND PROCESS_STATUS = 99          
          
  DELETE FROM STAT_TRD WHERE Filedate = @SAUDA_DATE          
          
  RETURN          
 END          
 EXEC IMPCHANGES          
 SET @SUBPROCESSID = 2          
END          
          
IF @SUBPROCESSID = 2 OR @SUBPROCESSID = 0          
BEGIN          
 UPDATE TBL_AUTO_PROCESS_DETAIL SET SUB_PROCESS_ID = 2          
 WHERE SNO = @SNO AND PROCESS_STATUS = 99          
          
 UPDATE TRADE SET TRADE.PARTY_CODE = TERMPARTY.PARTY_CODE FROM TERMPARTY           
 WHERE TERMPARTY.USERID = TRADE.USER_ID AND TRADE.PARTY_CODE <> TERMPARTY.EXCEPTPARTY AND TRADE.PRO_CLI = PROCLI          
          
 INSERT INTO STAT_TRD VALUES ('I21', @SAUDA_DATE + ' ' + CONVERT(VARCHAR,GETDATE(),108),@SAUDA_DATE,GETDATE())          
 SET @SUBPROCESSID = 3          
          
END          
          
IF @SUBPROCESSID = 3 OR @SUBPROCESSID = 0          
BEGIN          
 SET @SUBPROCESSID = 4          
END          
          
IF @SUBPROCESSID = 4 OR @SUBPROCESSID = 0          
BEGIN          
 -- FOR SKIPPING OF TRADE IN CASE OF MISSING CLIENT AND SCRIP          
 SET @SUBPROCESSID = 5          
END          
          
IF @SUBPROCESSID = 5 OR @SUBPROCESSID = 0          
BEGIN          
 INSERT INTO STAT_TRD VALUES ('I40', @SAUDA_DATE + ' ' + CONVERT(VARCHAR,GETDATE(),108),@SAUDA_DATE,GETDATE())          
          
 EXEC TRD_CLIENTMASTER          
          
 IF (SELECT ISNULL(COUNT(1),0) FROM TRD_CLIENT WHERE INACTIVEFROM <= GETDATE()) > 0          
 BEGIN          
  UPDATE TBL_AUTO_PROCESS_DETAIL SET SUB_PROCESS_ID = 5,          
  PROCESS_HALTED_REASON = 'TRADES CONTAINS THE INACTIVE CLIENT DATA, PLEASE CORRECT.',          
  PROCESS_STATUS = 98, PROCESS_ENDED_DATE = GETDATE(),          
  PROCESS_OUTPUT_QUERY = 'SELECT PARTY_CODE, SHORT_NAME FROM TRD_CLIENT WHERE INACTIVEFROM <= GETDATE() ',   
   PROCESS_STATUS_ALERT_COUNT = 0                  
  WHERE SNO = @SNO AND PROCESS_STATUS = 99          
          
  RETURN          
 END          
          
 IF (SELECT ISNULL(COUNT(1),0) FROM TRADE WHERE PARTY_CODE NOT IN (SELECT PARTY_CODE FROM TRD_CLIENT)) > 0          
 BEGIN          
  UPDATE TBL_AUTO_PROCESS_DETAIL SET SUB_PROCESS_ID = 5,          
  PROCESS_HALTED_REASON = 'TRADES CONTAINS THE MISSING CLIENT DATA, PLEASE CORRECT.',          
  PROCESS_STATUS = 98, PROCESS_ENDED_DATE = GETDATE(),          
  PROCESS_OUTPUT_QUERY = 'SELECT DISTINCT PARTY_CODE, TERMINAL = USER_ID FROM TRADE WHERE PARTY_CODE NOT IN (SELECT PARTY_CODE FROM TRD_CLIENT) ',   
   PROCESS_STATUS_ALERT_COUNT = 0          
  WHERE SNO = @SNO AND PROCESS_STATUS = 99          
          
  RETURN          
 END          
          
 IF (SELECT ISNULL(COUNT(1),0) FROM TRADE WHERE SCRIP_CD NOT IN (SELECT SCRIP_CD FROM SCRIP2 S2, SCRIP1 S1           
   WHERE S1.CO_CODE = S2.CO_CODE AND S1.SERIES = S2.SERIES AND S2.SCRIP_CD = TRADE.SCRIP_CD AND S2.SERIES = TRADE.SERIES)) > 0          
 BEGIN          
  UPDATE TBL_AUTO_PROCESS_DETAIL SET SUB_PROCESS_ID = 5,          
  PROCESS_HALTED_REASON = 'TRADES CONTAINS THE MISSING SCRIP DATA, PLEASE CORRECT.',          
  PROCESS_STATUS = 98, PROCESS_ENDED_DATE = GETDATE(),          
  PROCESS_OUTPUT_QUERY = 'SELECT DISTINCT SCRIP_CD, SERIES FROM TRADE WHERE SCRIP_CD NOT IN (SELECT SCRIP_CD FROM SCRIP2 S2, SCRIP1 S1           
  WHERE S1.CO_CODE = S2.CO_CODE AND S1.SERIES = S2.SERIES AND S2.SCRIP_CD = TRADE.SCRIP_CD AND S2.SERIES = TRADE.SERIES) ' ,   
   PROCESS_STATUS_ALERT_COUNT = 0                 
  WHERE SNO = @SNO AND PROCESS_STATUS = 99          
          
  RETURN          
 END          
          
 SELECT @TRADEQTY = ISNULL(SUM(TRADEQTY),0), @TRADEAMT = ISNULL(SUM(TRADEQTY*MARKETRATE),0)          
 FROM TRADE          
          
 SELECT @CONFIRMQTY = ISNULL(SUM(TRADEQTY),0), @CONFIRMAMT = ISNULL(SUM(TRADEQTY*MARKETRATE),0)          
 FROM CONFIRMVIEW          
          
 IF (SELECT ISNULL(COUNT(1),0) FROM TRADE)  = 0          
 BEGIN          
  UPDATE TBL_AUTO_PROCESS_DETAIL SET SUB_PROCESS_ID = 5,          
  PROCESS_HALTED_REASON = 'NO DATA PRESENT IN THE TRADE.',          
  PROCESS_STATUS = 100, PROCESS_ENDED_DATE = GETDATE(),   
   PROCESS_STATUS_ALERT_COUNT = 0                  
  WHERE SNO = @SNO AND PROCESS_STATUS = 99          
          
  RETURN          
 END          
          
 IF (@TRADEQTY - @CONFIRMQTY) <> 0 OR (@TRADEAMT - @CONFIRMAMT) <> 0           
 BEGIN          
  IF @TRADEQTY > @CONFIRMQTY OR @TRADEAMT > @CONFIRMAMT          
  BEGIN          
   IF @CONFIRMQTY = 0          
   BEGIN          
    UPDATE TBL_AUTO_PROCESS_DETAIL SET SUB_PROCESS_ID = 5,          
    PROCESS_HALTED_REASON = 'SEEMS TO BE ISSUE IN SETTLEMENT MASTER.',          
    PROCESS_STATUS = 98, PROCESS_ENDED_DATE = GETDATE(),   
   PROCESS_STATUS_ALERT_COUNT = 0                  
    WHERE SNO = @SNO AND PROCESS_STATUS = 99          
   END        
   ELSE          
   BEGIN              
    UPDATE TBL_AUTO_PROCESS_DETAIL SET SUB_PROCESS_ID = 5,          
    PROCESS_HALTED_REASON = 'SOME OF PARTY ARE HAVING PROBLEM IN THE MASTER.',          
    PROCESS_STATUS = 98, PROCESS_ENDED_DATE = GETDATE(),          
    PROCESS_OUTPUT_QUERY = 'SELECT PARTY_CODE, SCRIP_CD, SERIES, ORDER_NO, TRADE_NO, TRADEQTY FROM TRADE T          
    WHERE PARTY_CODE NOT IN (SELECT PARTY_CODE FROM CONFIRMVIEW C          
    WHERE T.PARTY_CODE = C.PARTY_CODE AND T.SCRIP_CD = C.SCRIP_CD          
    AND T.SERIES = C.SERIES AND T.ORDER_NO = C.ORDER_NO AND T.TRADE_NO = C.TRADE_NO)',   
   PROCESS_STATUS_ALERT_COUNT = 0                  
    WHERE SNO = @SNO AND PROCESS_STATUS = 99          
   END          
  END          
  ELSE          
  BEGIN          
   UPDATE TBL_AUTO_PROCESS_DETAIL SET SUB_PROCESS_ID = 5,          
   PROCESS_HALTED_REASON = 'SOME OF PARTY ARE HAVING PROBLEM IN THE MASTER. DUPLICATE DATA IS COMING FROM THE CONFIRMATION.',          
 PROCESS_STATUS = 98, PROCESS_ENDED_DATE = GETDATE(),          
   PROCESS_OUTPUT_QUERY = 'SELECT PARTY_CODE, SCRIP_CD, SERIES, ORDER_NO, TRADE_NO CONFIRMVIEW C          
   GROUP BY PARTY_CODE, SCRIP_CD, SERIES, ORDER_NO, TRADE_NO          
   HAVING COUNT(1) > 1',   
   PROCESS_STATUS_ALERT_COUNT = 0                  
   WHERE SNO = @SNO AND PROCESS_STATUS = 99          
  END          
  RETURN          
 END          
 ELSE          
 BEGIN          
  UPDATE TBL_AUTO_PROCESS_DETAIL SET SUB_PROCESS_ID = 6          
  WHERE SNO = @SNO AND PROCESS_STATUS = 99          
          
  INSERT INTO STAT_TRD VALUES ('I70', @SAUDA_DATE + ' ' + CONVERT(VARCHAR,GETDATE(),108),@SAUDA_DATE,GETDATE())          
            
  SET @SUBPROCESSID = 6          
 END          
END          
          
IF @SUBPROCESSID = 6 OR @SUBPROCESSID = 0          
BEGIN          
 EXEC TRD_CLIENTMASTER          
 EXEC CONFIRMATIONALLTRADE          
           
 UPDATE TBL_AUTO_PROCESS_DETAIL SET SUB_PROCESS_ID = 7          
 WHERE SNO = @SNO AND PROCESS_STATUS = 99          
          
 INSERT INTO STAT_TRD VALUES ('I80', @SAUDA_DATE + ' ' + CONVERT(VARCHAR,GETDATE(),108),@SAUDA_DATE,GETDATE())          
 SET @SUBPROCESSID = 7          
END                  
IF @SUBPROCESSID = 7 OR @SUBPROCESSID = 0          
BEGIN          
 IF (SELECT ISNULL(COUNT(1),0) FROM TRADE)  = 0          
 BEGIN          
  UPDATE TBL_AUTO_PROCESS_DETAIL SET SUB_PROCESS_ID = 7,          
  PROCESS_HALTED_REASON = 'NO DATA PRESENT IN THE TRADE.',          
  PROCESS_STATUS = 100, PROCESS_ENDED_DATE = GETDATE(),   
   PROCESS_STATUS_ALERT_COUNT = 0                  
  WHERE SNO = @SNO AND PROCESS_STATUS = 99          
          
  RETURN          
 END          
          
 IF (Select IsNull(Count(*),0) From ContGen, Trade Where Sauda_Date >= Start_Date and Sauda_Date <= End_Date) <= 0          
 BEGIN          
  UPDATE TBL_AUTO_PROCESS_DETAIL SET SUB_PROCESS_ID = 7,          
  PROCESS_HALTED_REASON = 'Please Enter The Contract No in the Table for the Current Year.',          
  PROCESS_STATUS = 98, PROCESS_ENDED_DATE = GETDATE(),          
  PROCESS_OUTPUT_QUERY = '',   
   PROCESS_STATUS_ALERT_COUNT = 0                  
  WHERE SNO = @SNO AND PROCESS_STATUS = 99          
          
  RETURN          
 END          
 BEGIN TRAN          
  SELECT @TRADEQTY = 0          
  SELECT @TRADEQTY = ISNULL(SUM(TRADEQTY),0), @RECCNT = ISNULL(COUNT(1),0) FROM TRADE          
  SELECT @TRADEQTY = @TRADEQTY + ISNULL(SUM(TRADEQTY),0) FROM SETTLEMENT WHERE SAUDA_DATE LIKE @SAUDA_DATE + '%'          
  SELECT @TRADEQTY = @TRADEQTY + ISNULL(SUM(TRADEQTY),0) FROM ISETTLEMENT WHERE SAUDA_DATE LIKE @SAUDA_DATE + '%'          
  
  BEGIN TRY          
   EXEC ContractAllTrade          
  END TRY          
  BEGIN CATCH          
   ROLLBACK TRAN          
   UPDATE TBL_AUTO_PROCESS_DETAIL SET SUB_PROCESS_ID = 7,          
   PROCESS_HALTED_REASON = ERROR_MESSAGE(),          
   PROCESS_STATUS = 98, PROCESS_ENDED_DATE = GETDATE(),          
   PROCESS_OUTPUT_QUERY = ''          
   WHERE SNO = @SNO AND PROCESS_STATUS = 99            
   RETURN          
  END CATCH          
  SELECT @CONFIRMQTY = 0          
  SELECT @CONFIRMQTY = @CONFIRMQTY + ISNULL(SUM(TRADEQTY),0) FROM SETTLEMENT WHERE SAUDA_DATE LIKE @SAUDA_DATE + '%'          
  SELECT @CONFIRMQTY = @CONFIRMQTY + ISNULL(SUM(TRADEQTY),0) FROM ISETTLEMENT WHERE SAUDA_DATE LIKE @SAUDA_DATE + '%'          
          
  IF @TRADEQTY <> @CONFIRMQTY           
  BEGIN          
   UPDATE TBL_AUTO_PROCESS_DETAIL SET SUB_PROCESS_ID = 7,          
   PROCESS_HALTED_REASON = 'QTY BEFORE CONTRACT AND AFTER CONTRACT NOT MATCHING.',          
   PROCESS_STATUS = 98, PROCESS_ENDED_DATE = GETDATE(),          
   PROCESS_OUTPUT_QUERY = '',   
   PROCESS_STATUS_ALERT_COUNT = 0                  
   WHERE SNO = @SNO AND PROCESS_STATUS = 99          
            
   RETURN          
  END          
          
  Exec V2_PROCESSFORTODAY 'IMPORT TRADE', 'AUTO', '', '', @SAUDA_DATE          
  SET @SUBPROCESSID = 8          
 COMMIT           
          
 UPDATE TBL_AUTO_PROCESS_DETAIL SET SUB_PROCESS_ID = 8,          
 PROCESS_HALTED_REASON = 'TRADE IMPORTED SUCCESSFULLY WITH TOTAL NO OF RECORDS ' + CONVERT(VARCHAR,@RECCNT),          
 PROCESS_STATUS = 100, PROCESS_ENDED_DATE = GETDATE(),          
 PROCESS_OUTPUT_QUERY = '', PROCESS_STATUS_ALERT_INTERVAL = '00:00:00',   
   PROCESS_STATUS_ALERT_COUNT = 0                  
 WHERE SNO = @SNO AND PROCESS_STATUS = 99          
          
 INSERT INTO STAT_TRD VALUES ('I95', @SAUDA_DATE + ' ' + CONVERT(VARCHAR,GETDATE(),108),@SAUDA_DATE,GETDATE())          
END          
          
IF @SUBPROCESSID = 8 OR @SUBPROCESSID = 0          
BEGIN          
 DELETE FROM STAT_TRD WHERE FILEDATE = @SAUDA_DATE          
END

GO
