-- Object: PROCEDURE dbo.PROC_NSESLBS_EPN_POS
-- Server: 10.253.33.91 | DB: NSESLBS
--------------------------------------------------

CREATE PROC [dbo].[PROC_NSESLBS_EPN_POS]      
(  
  @EXPDATE VARCHAR(11)
)

AS

DECLARE @SETT_NO	VARCHAR(7)

SELECT @SETT_NO = SETT_NO FROM SETT_MST WHERE SETT_TYPE = 'P' AND RIGHT(SETT_NO,3) >= '500' 
AND LEFT(SEC_PAYIN, 11) = LEFT(CONVERT(DATETIME,@EXPDATE),11)
      
DELETE FROM MSAJAG.DBO.DELIVERYCLT      
WHERE SETT_NO = @SETT_NO
AND SETT_TYPE = 'P'      
  
DELETE FROM MSAJAG.DBO.DELNET      
WHERE SETT_NO = @SETT_NO
AND SETT_TYPE = 'P'      
  
INSERT INTO MSAJAG.DBO.DELIVERYCLT      
SELECT SETT_NO, SETT_TYPE, SCRIP_CD, SERIES='EQ', PARTY_CODE,       
TRADEQTY=MARKED_QTY,INOUT = 'I',BRANCH_CD = 'HO', PARTIPANTCODE = MEMBERCODE    
FROM TBL_SLBS_EPNPOS, OWNER     
WHERE SETT_NO = @SETT_NO
AND SETT_TYPE = 'P'     

INSERT INTO MSAJAG.DBO.DELNET      
SELECT SETT_NO, SETT_TYPE, SCRIP_CD, SERIES='EQ', 
TRADEQTY=SUM(MARKED_QTY),INOUT = 'I'    
FROM TBL_SLBS_EPNPOS     
WHERE SETT_NO = @SETT_NO
AND SETT_TYPE = 'P'     
GROUP BY SETT_NO, SETT_TYPE, SCRIP_CD

GO
