-- Object: PROCEDURE dbo.NBFC_POPULATECLIENT
-- Server: 10.253.33.91 | DB: NSESLBS
--------------------------------------------------

CREATE PROC NBFC_POPULATECLIENT (@FORPARTY VARCHAR(10) = '%') AS

INSERT INTO CLIENT_DETAILS
SELECT * FROM MSAJAG.DBO.CLIENT_DETAILS
WHERE CL_CODE LIKE @FORPARTY
AND CL_CODE IN (SELECT PARTY_CODE FROM MSAJAG.DBO.TBLCLIENTMARGIN
WHERE GETDATE() BETWEEN FROM_DATE AND TO_DATE)
AND CL_CODE NOT IN (SELECT CL_CODE FROM CLIENT_DETAILS)

INSERT INTO CLIENT_DETAILS
SELECT * FROM MSAJAG.DBO.CLIENT_DETAILS
WHERE CL_CODE LIKE @FORPARTY
AND CL_CODE IN (SELECT PARTY_CODE FROM BSEDB.DBO.TBLCLIENTMARGIN
WHERE GETDATE() BETWEEN FROM_DATE AND TO_DATE)
AND CL_CODE NOT IN (SELECT CL_CODE FROM CLIENT_DETAILS)

INSERT INTO CLIENT1
Select * FROM MSAJAG.DBO.CLIENT1 C
WHERE CL_CODE LIKE @FORPARTY
AND CL_CODE IN (SELECT PARTY_CODE FROM MSAJAG.DBO.TBLCLIENTMARGIN
WHERE GETDATE() BETWEEN FROM_DATE AND TO_DATE)
AND CL_CODE NOT IN (SELECT CL_CODE FROM CLIENT1)

INSERT INTO CLIENT1
Select * FROM BSEDB.DBO.CLIENT1 C
WHERE CL_CODE LIKE @FORPARTY
AND CL_CODE IN (SELECT PARTY_CODE FROM BSEDB.DBO.TBLCLIENTMARGIN
WHERE GETDATE() BETWEEN FROM_DATE AND TO_DATE)
AND CL_CODE NOT IN (SELECT CL_CODE FROM CLIENT1)

INSERT INTO CLIENT2
SELECT * FROM MSAJAG.DBO.CLIENT2
WHERE CL_CODE LIKE @FORPARTY
AND CL_CODE IN (SELECT PARTY_CODE FROM MSAJAG.DBO.TBLCLIENTMARGIN
WHERE GETDATE() BETWEEN FROM_DATE AND TO_DATE)
AND CL_CODE NOT IN (SELECT CL_CODE FROM CLIENT2)

INSERT INTO CLIENT2
SELECT * FROM BSEDB.DBO.CLIENT2
WHERE CL_CODE LIKE @FORPARTY
AND CL_CODE IN (SELECT PARTY_CODE FROM BSEDB.DBO.TBLCLIENTMARGIN
WHERE GETDATE() BETWEEN FROM_DATE AND TO_DATE)
AND CL_CODE NOT IN (SELECT CL_CODE FROM CLIENT2)

INSERT INTO CLIENT5
SELECT * FROM MSAJAG.DBO.CLIENT5
WHERE CL_CODE LIKE @FORPARTY
AND CL_CODE IN (SELECT PARTY_CODE FROM MSAJAG.DBO.TBLCLIENTMARGIN
WHERE GETDATE() BETWEEN FROM_DATE AND TO_DATE)
AND CL_CODE NOT IN (SELECT CL_CODE FROM CLIENT5)

INSERT INTO CLIENT5
SELECT * FROM BSEDB.DBO.CLIENT5
WHERE CL_CODE LIKE @FORPARTY
AND CL_CODE IN (SELECT PARTY_CODE FROM BSEDB.DBO.TBLCLIENTMARGIN
WHERE GETDATE() BETWEEN FROM_DATE AND TO_DATE)
AND CL_CODE NOT IN (SELECT CL_CODE FROM CLIENT5)

INSERT INTO CLIENT4
SELECT * FROM MSAJAG.DBO.CLIENT4
WHERE CL_CODE LIKE @FORPARTY
AND CL_CODE IN (SELECT PARTY_CODE FROM MSAJAG.DBO.TBLCLIENTMARGIN
WHERE GETDATE() BETWEEN FROM_DATE AND TO_DATE)
AND CL_CODE NOT IN (SELECT CL_CODE FROM CLIENT4)

INSERT INTO CLIENT4
SELECT * FROM BSEDB.DBO.CLIENT4
WHERE CL_CODE LIKE @FORPARTY
AND CL_CODE IN (SELECT PARTY_CODE FROM BSEDB.DBO.TBLCLIENTMARGIN
WHERE GETDATE() BETWEEN FROM_DATE AND TO_DATE)
AND CL_CODE NOT IN (SELECT CL_CODE FROM CLIENT4)

INSERT INTO MULTICLTID
SELECT * FROM MSAJAG.DBO.MULTICLTID
WHERE PARTY_CODE LIKE @FORPARTY
AND PARTY_CODE IN (SELECT PARTY_CODE FROM MSAJAG.DBO.TBLCLIENTMARGIN
WHERE GETDATE() BETWEEN FROM_DATE AND TO_DATE)
AND PARTY_CODE NOT IN (SELECT PARTY_CODE FROM MULTICLTID)

INSERT INTO MULTICLTID
SELECT * FROM BSEDB.DBO.MULTICLTID
WHERE PARTY_CODE LIKE @FORPARTY
AND PARTY_CODE IN (SELECT PARTY_CODE FROM BSEDB.DBO.TBLCLIENTMARGIN
WHERE GETDATE() BETWEEN FROM_DATE AND TO_DATE)
AND PARTY_CODE NOT IN (SELECT PARTY_CODE FROM MULTICLTID)

GO
