-- Object: PROCEDURE dbo.V2_UPDATE_PASSWORD
-- Server: 10.253.33.91 | DB: NSESLBS
--------------------------------------------------



CREATE PROC [dbo].[V2_UPDATE_PASSWORD]  
(  
 @PASSWORD VARCHAR(50),  
 @USERID VARCHAR(25),  
 @DAYCOUNT INT   
)  
  
AS  
  
  
SET NOCOUNT ON  
  
DECLARE @@FLDOLDPASSWORD TINYINT  
DECLARE @@FLDAUTO INT  
DECLARE @@PASSAUTO BIGINT  
DECLARE @@OLDPASSSTRING VARCHAR(2000)  
DECLARE @@OLDPASSCOUNT INT  
DECLARE @@NEWPASSSTRING VARCHAR(2000)  
  
  
/*  
CREATE TABLE TBLUSERPASSHIST  
(  
 FLDAUTO BIGINT IDENTITY(1,1),  
 FLDUSERID INT,  
 FLDOLDPASSLISTING VARCHAR(2000)  
)  
*/  
  
  
SELECT @@FLDOLDPASSWORD = ISNULL(FLDOLDPASSWORD,1) FROM TBLGLOBALPARAMS  
  
IF ISNULL(@@FLDOLDPASSWORD,0) = 0  
BEGIN  
 SET @@FLDOLDPASSWORD = 1  
END  
  
  
  
SELECT @@FLDAUTO = ISNULL(FLDAUTO,0) FROM TBLPRADNYAUSERS  
WHERE FLDUSERNAME = @USERID  
  
IF ISNULL(@@FLDAUTO,0) = 0  
BEGIN  
 SELECT MSG = 'USER NOT FOUND'  
 RETURN  
END  
  
  
  
SELECT @@OLDPASSSTRING = ISNULL(FLDOLDPASSLISTING,''), @@PASSAUTO = ISNULL(FLDAUTO,0)  FROM TBLUSERPASSHIST  
WHERE FLDUSERID = @@FLDAUTO  
  
IF ISNULL(@@OLDPASSSTRING,'') = ''  
BEGIN  
 SET @@OLDPASSSTRING = ''  
END  
  
IF ISNULL(@@PASSAUTO,0) = 0  
BEGIN  
 SET @@PASSAUTO = 0  
END  
  
  
SELECT   
 @@OLDPASSCOUNT = COUNT(1)  
FROM   
 FUN_SPLITSTRING (@@OLDPASSSTRING,'±')  
WHERE   
 SPLITTED_VALUE = @PASSWORD  
 AND SNO > (  
      SELECT   
        ISNULL(ISNULL(MAX(SNO),0) - @@FLDOLDPASSWORD, 0)  
      FROM   
       FUN_SPLITSTRING (@@OLDPASSSTRING,'±')  
     )  
  
  
IF ISNULL(@@OLDPASSCOUNT,0) > 0  
BEGIN  
 SELECT MSG = 'PASSWORD ALREADY USED DURING LAST ' + CAST(@@FLDOLDPASSWORD AS VARCHAR) + ' ATTEMPTS.  PLEASE CHANGE'  
 RETURN  
END  
  
  
  
UPDATE TBLPRADNYAUSERS   
SET   
 FLDPASSWORD = @PASSWORD,  
 PWD_EXPIRY_DATE = (GETDATE()+ @DAYCOUNT)  
WHERE   
 FLDAUTO = @@FLDAUTO  
  
          
UPDATE TBLUSERCONTROLMASTER   
SET   
 FLDATTEMPTCNT = 0,  
 FLDFIRSTLOGIN = 'N'  
WHERE   
 TBLUSERCONTROLMASTER.FLDUSERID = @@FLDAUTO   
  
  
  
SET @@NEWPASSSTRING = ''  
  
  
DECLARE @@STRING VARCHAR(100)  
  
DECLARE vendor_cursor CURSOR FOR   
  
SELECT SPLITTED_VALUE  
FROM   
 FUN_SPLITSTRING (@@OLDPASSSTRING,'±')  
WHERE  SNO > (  
      SELECT   
        ISNULL(ISNULL(MAX(SNO),0) - @@FLDOLDPASSWORD, 0)  
      FROM   
       FUN_SPLITSTRING (@@OLDPASSSTRING,'±')  
     )  
OPEN vendor_cursor  
  
FETCH NEXT FROM vendor_cursor   
INTO @@STRING  
  
WHILE @@FETCH_STATUS = 0  
BEGIN  
 SET @@NEWPASSSTRING = @@NEWPASSSTRING + @@STRING + '±'  
FETCH NEXT FROM vendor_cursor   
INTO @@STRING  
END   
  
CLOSE vendor_cursor  
DEALLOCATE vendor_cursor  
  
 SET @@NEWPASSSTRING = @@NEWPASSSTRING + @PASSWORD   
  
IF ISNULL(@@PASSAUTO,0) = 0  
BEGIN  
 INSERT INTO TBLUSERPASSHIST   
 (FLDUSERID, FLDOLDPASSLISTING)   
 VALUES  
 (@@FLDAUTO, @@NEWPASSSTRING)  
END  
ELSE  
BEGIN  
 UPDATE TBLUSERPASSHIST  
 SET FLDOLDPASSLISTING = @@NEWPASSSTRING  
 WHERE FLDAUTO = @@PASSAUTO  
 AND FLDUSERID = @@FLDAUTO   
END  
  
SELECT MSG = 'PASSWORD UPDATED SUCCESSFULLY'  
RETURN

GO
