-- Object: PROCEDURE dbo.PROC_Delpayoutcsv_UPLOAD
-- Server: 10.253.33.91 | DB: NSESLBS
--------------------------------------------------

CREATE PROC PROC_Delpayoutcsv_UPLOAD
(@FILEPATH VARCHAR(150))
AS
Declare @strSql varchar(400)   

SELECT RMNO,PARTY_CODE,SCRIP_CD,CERTNO,
SETT_NO,SETT_TYPE,QTY,BDPTYPE,BDPID,BCLTDPID,
DPTYPE,DPID,CLTDPID INTO #DELPAYCSV FROM DELPAYOUTCSV
WHERE 1 = 2 

set @strSql = 'Bulk insert #DELPAYCSV from ''' + @FilePath  + ''' with ( FIELDTERMINATOR = '','', ROWTERMINATOR = ''\n'' )'      
Exec(@strSql)    

INSERT INTO DELPAYOUTCSV (RMNO,PARTY_CODE,SCRIP_CD,CERTNO,SETT_NO,SETT_TYPE,QTY,BDPTYPE,BDPID,BCLTDPID,DPTYPE,DPID,CLTDPID)
SELECT * FROM #DELPAYCSV

GO
