-- Object: PROCEDURE dbo.RPT_ADMIN_LOG
-- Server: 10.253.33.91 | DB: NSESLBS
--------------------------------------------------



CREATE PROCEDURE [dbo].[RPT_ADMIN_LOG]
(
	@LOGTYPE VARCHAR(20),
	@DATEFROM VARCHAR(11),
	@DATETO VARCHAR(11),
	@REPORTORDER INT,
	@TXTNAME VARCHAR(25)
)
AS

/*
POSSIBLE VALUES OF @LOGTYPE 
	
	MENURIGHTS
	CATEGORY
	ADMIN_USER

*/

IF @LOGTYPE ='MENURIGHTS'
BEGIN
	/*
	VALID ORDER BY
		1 - REPORT NAME + DATE
		2 - CATEGORY + DATE
	*/
	SELECT 
		REPORTORDER = 
			CASE WHEN @REPORTORDER = 1 THEN REPORTNAME ELSE RIGHT(CATEGORYNAME,LEN(CATEGORYNAME)-1) END
			+ CONVERT(VARCHAR,YEAR(CREATEDON)) + CONVERT(VARCHAR,MONTH(CREATEDON)) + CONVERT(VARCHAR,DAY(CREATEDON)),
		REPORTNAME,
		LOGINCATEGORY,
		CATEGORYNAME,
		EDITFLAG =  ISNULL(CASE 
				WHEN EDIT_FLAG ='D' THEN 'CATEGORY DELETED' 
				WHEN EDIT_FLAG ='A' THEN 'CATEGORY ADDEDED'
				WHEN EDIT_FLAG ='E' THEN
				CASE WHEN LEFT(CATEGORYNAME,1) ='-' 
					THEN 'RIGHTS REMOVED'
					ELSE 'RIGHTS ADDED'
					END
			    END,'') ,
		CREATEDBY,
		CREATEDON =  CONVERT(VARCHAR,CREATEDON,109),
		MACHINEIP
	FROM
	(
		SELECT 
			REPORTNAME = TBLREPORTS.FLDREPORTNAME,
			LOGINCATEGORY = TBLADMIN.FLDNAME,
			CATEGORYNAME = LTRIM(RTRIM(DBO.FUN_GET_TBLREPORT (FLDCATEGORYCODE_OLD,FLDCATEGORYCODE_NEW))),
			EDIT_FLAG,
			CREATEDBY = CREATED_BY,
			CREATEDON = CREATED_ON,
			MACHINEIP = MACHINE_IP
		FROM
			TBLCATMENU_LOG (NOLOCK),
			TBLREPORTS (NOLOCK),
			TBLADMIN (NOLOCK)
		WHERE
			TBLADMIN.FLDAUTO_ADMIN = FLDADMINAUTO
			AND TBLCATMENU_LOG.FLDREPORTCODE = TBLREPORTS.FLDREPORTCODE
			AND TBLCATMENU_LOG.CREATED_ON BETWEEN @DATEFROM AND @DATETO + ' 23:59'
	) TBLLOG
	ORDER BY 1

END

IF @LOGTYPE ='CATEGORY'
BEGIN
	SELECT  
		REPORTORDER = FLDCATEGORYNAME +
		+ CONVERT(VARCHAR,YEAR(CREATED_ON)) + CONVERT(VARCHAR,MONTH(CREATED_ON)) + CONVERT(VARCHAR,DAY(CREATED_ON)),
		FLDCATEGORYNAME,
		FLDDESC ,
		EDIT_FLAG = CASE WHEN EDIT_FLAG ='A' THEN 'ADDED' ELSE 'DELETED' END,
		CREATED_ON = CONVERT(VARCHAR,CREATED_ON,109), 
		CREATED_BY 
	FROM 
		TBLCATEGORY_LOG (NOLOCK) 
	WHERE 
		CREATED_ON  BETWEEN @DATEFROM AND @DATETO + ' 23:59'
		AND FLDCATEGORYNAME LIKE @TXTNAME+'%'
	ORDER BY 1
END

IF @LOGTYPE ='REPORTLOG'
BEGIN
	SELECT 
		FLDREPORTNAME,FLDPATH,FLDTARGET,TB.FLDDESC,FLDGRPNAME,
		FLDSTATUS,
		EDIT_FLAG=
			CASE 
				WHEN EDIT_FLAG='A' THEN 'ADDED' 
				WHEN EDIT_FLAG='I' THEN 'EDITED'
				ELSE 'DELETED' END,
		CREATED_ON = CONVERT(VARCHAR,CREATED_ON,109), 
		CREATED_BY 
	FROM 
		TBLREPORTS_LOG TB, TBLREPORTGRP TG
	WHERE 
		TB.FLDREPORTGRP =TG.FLDREPORTGRP
		AND TB.FLDMENUGRP = TG.FLDMENUGRP
		AND CREATED_ON  BETWEEN @DATEFROM AND @DATETO + ' 23:59'
		AND FLDREPORTNAME LIKE @TXTNAME + '%'
	ORDER BY 1
END

IF @LOGTYPE ='ADMIN_USER'
BEGIN
	/*
	VALID ORDER BY
		1 - USER NAME+ DATE
		2 - EDIT FLAG  + DATE
	*/
	SELECT 
		REPORTORDER = CASE WHEN @REPORTORDER =1 THEN FLDNAME ELSE EDIT_FLAG END +
			+ CONVERT(VARCHAR,YEAR(CREATED_ON)) + CONVERT(VARCHAR,MONTH(CREATED_ON)) + CONVERT(VARCHAR,DAY(CREATED_ON))  ,
		USERNAME=FLDNAME,FLDPASSWORD,COMPANY=FLDCOMPANY,
		LOGINCATEGORY=FLDSTATUS,DESCRIPTION=FLDDESC,PASSWORD_EXP_DT = LEFT(PWD_EXPIRY_DATE,11),
		MAXWRONGATTEMP_ALLOWD = FLDMAXATTEMPT,
		USERSTATUS=CASE WHEN FLDUSERSTATUS =0 THEN 'ENABLED' ELSE 'DISABLED' END ,
		ACCESSLVL= CASE WHEN FLDACCESSLVL ='F' THEN 'FREE ACCESS' ELSE 'LIMITED' END ,
		IP_FILTER = FLDIPADD,
		FIRST_LOGIN_FLAG= FLDFIRSTLOGIN,
		EDIT_FLAG=
			CASE 
				WHEN EDIT_FLAG='A' THEN 'ADDED' 
				WHEN EDIT_FLAG='I' THEN 'EDITED'
				ELSE 'DELETED' END,
		CREATED_BY,CREATED_ON = CONVERT(VARCHAR,CREATED_ON,109), MACHINEIP = ISNULL(MACHINEIP,'') , FLDLOG_DATA = ISNULL(FLDLOG_DATA,'')
	FROM 
		TBLADMIN_LOG (NOLOCK) 
	WHERE
	 	TBLADMIN_LOG.CREATED_ON BETWEEN @DATEFROM AND @DATETO + ' 23:59'
		AND FLDNAME LIKE @TXTNAME+'%'
	ORDER BY 1

END

IF @LOGTYPE ='USERLOG'
BEGIN
	/*
	VALID ORDER BY
		1 - USER NAME+ DATE
		2 - EDIT FLAG  + DATE

	*/
	SELECT 
		REPORTORDER = CASE WHEN @REPORTORDER =1 THEN FLDUSERNAME ELSE EDIT_FLAG END +
			+ CONVERT(VARCHAR,YEAR(CREATED_ON)) + CONVERT(VARCHAR,MONTH(CREATED_ON)) + CONVERT(VARCHAR,DAY(CREATED_ON))  ,
		USERNAME=FLDUSERNAME,FLDPASSWORD,FLDFIRSTNAME,FLDMIDDLENAME,
		FLDLASTNAME,FLDSEX,FLDADDRESS1,FLDADDRESS2, FLDPHONE1, FLDPHONE2,
		PWDEXPIRYDAYS = ISNULL(B.FLDPWDEXPIRY,''),
		PWDEXPIRY = ISNULL(B.FLDPWDEXPIRY,''),
		MAXATTEMPT = ISNULL(B.FLDMAXATTEMPT,0),
		USERSTATUS = CASE WHEN ISNULL(B.FLDSTATUS,0) =0 THEN 'ENABLED' WHEN B.FLDSTATUS = 1 THEN 'DISABLED' ELSE 'UNAUTHORISED' END , 
		ATTEMPTCNT = ISNULL(B.FLDATTEMPTCNT,0), 
		LOGINFLAG = CASE WHEN ISNULL(B.FLDLOGINFLAG,0) = 0 THEN 'LOGGED OUT' ELSE 'LOGGED IN' END, 
		ACCESSLVL = CASE WHEN ISNULL(B.FLDACCESSLVL,'F') = 'F' THEN 'FREE ACCESS' ELSE 'LIMITED' END, 
		IPADD = ISNULL(B.FLDIPADD,''), 
		TIMEOUT = ISNULL(B.FLDTIMEOUT,0), 
		FIRSTLOGIN = CASE WHEN ISNULL(B.FLDFIRSTLOGIN,'N') = 'N' THEN 'NO' ELSE 'YES' END, 
		FORCELOGOUT = CASE WHEN ISNULL(B.FLDFORCELOGOUT,0) = 0 THEN 'ALLOW ACCESS' ELSE 'DO NOT ALLOW' END, 
		EDIT_FLAG=
			CASE 
				WHEN EDIT_FLAG='A' THEN 'ADDED' 
				WHEN EDIT_FLAG='I' THEN 'EDITED'
				ELSE 'DELETED' END,
		CREATED_BY,CREATED_ON = CONVERT(VARCHAR,CREATED_ON,109), MACHINEIP = ISNULL(MACHINEIP,'') , FLDLOG_DATA = ISNULL(FLDLOG_DATA,'') 
	FROM 
		TBLPRADNYAUSERS_LOG A (NOLOCK) 
		LEFT OUTER JOIN TBLUSERCONTROLMASTER B (NOLOCK) 
	ON 
		(B.FLDUSERID = A.FLDAUTO) 		
	WHERE
	 	A.CREATED_ON BETWEEN @DATEFROM AND @DATETO + ' 23:59'
		AND FLDUSERNAME LIKE @TXTNAME+'%' 
	ORDER BY 1
END

GO
