-- Object: PROCEDURE dbo.FT_CLIENTMASTER_UPLOAD
-- Server: 10.253.33.91 | DB: NSESLBS
--------------------------------------------------

CREATE   PROC FT_CLIENTMASTER_UPLOAD
	@TRADEDATE VARCHAR(11)

	AS

	SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED
	SELECT 
		OPERATIONCODE		= '1',
		USERID			= PARTY_CODE,	
		GROUPID			= 'HO',		
		USERNAME		= LEFT(LONG_NAME,40),	
		PASSWORD		= '',
		USERCATEGORY		= (CASE WHEN CL_TYPE IN ('INS','INST') THEN '3' ELSE '2' END),
		ADDRESS1		= '',
		ADDRESS2		= '',
		CITY			= '',
		STATEPIN		= '',
		TELEPHONENO		= '',
		FAXNO			= '',
		EMAIL			= '',
		DEALERSTATUS		= 'A',
		BROKERAGE		= '',
		SURVONOFF		= '1',
		SURVAUTOORMANUAL	= '0',
		BANKDPONOFF		= '0',
		PARTICIPANTCODE		= BANKID,
		FILLER			= '',
		FILLER			= '',
		FILLER			= '',
		FILLER			= '',
		MARKETALLOWED		= SUM(PCOUNT),
		CLIENTVALIDATIONONOFF	= '1',
		SPANONOFF		= '1',
		DERVPARTCODE		= BANKID,
		CLIENTIP		= '',
		MAXNOOFORDER		= '',
		MAXNOOFBCASTSCRIPS	= '',
		ALIASDEALERID		= '',
		EQFLAG			= '',
		DERVFLAG		= '0',
		COMBFLAG		= '0',
		BSEEQ			= '0',
		NSEBSECOMB		= '0',
		NEBSEEQ			= '0',
		FILLER			= '0',
		NSECASHCTCLBRANCHID	= '',
		NSECASHCTCLID		= '',
		BRANCHNAME		= '',
		DERVCTCLBRANCHID	= '',
		DERVCTCLID		= '',
		GROUPADMIN		= '',
		BSECASHCTCLBRANCHID	= '',
		BSECASHCTCLID		= '',
		LOGINALLOWED		= SUM(PCOUNT),
		PARTTYPE		= '',
		DIETUSER		= '0',
		INETNETUSER		= '0',
		IWINUSER		= '0',
		NETNETLINTE		= '0',
		MCXBRANCHID		= '',
		MCXCTCLID		= '',
		NCDEXBRANCHID		= '',
		NCDEXCTCLID		= '',
		PRODUCTTYPE		= 'Margin|'
	FROM
		(
		SELECT 
			DISTINCT
			PARTY_CODE,
			LONG_NAME,
			CL_TYPE,
			BANKID = (CASE WHEN CL_TYPE IN ('INS','INST') THEN BANKID ELSE '' END),
			PCOUNT = 1	
		FROM 
			CLIENT1 C1 (NOLOCK),
			CLIENT2 C2 (NOLOCK),
			CLIENT5 C5 (NOLOCK)
		WHERE
			C1.CL_CODE = C2.CL_CODE
			AND C5.CL_CODE = C1.CL_CODE
			AND C5.Systumdate >= @TRADEDATE 
		
		-----
		UNION
		-----
		
		SELECT 
			DISTINCT
			PARTY_CODE,
			LONG_NAME,
			CL_TYPE,
			BANKID = (CASE WHEN CL_TYPE IN ('INS','INST') THEN BANKID ELSE '' END),
			PCOUNT = 8	
		FROM 
			BSEDB..CLIENT1 C1 (NOLOCK),
			BSEDB..CLIENT2 C2 (NOLOCK),
			BSEDB..CLIENT5 C5 (NOLOCK)
		WHERE
			C1.CL_CODE = C2.CL_CODE
			AND C5.CL_CODE = C1.CL_CODE
			AND C5.Systumdate >= @TRADEDATE 
		
		-----
		UNION
		-----
		
		SELECT 
			DISTINCT
			PARTY_CODE,
			LONG_NAME,
			CL_TYPE,
			BANKID = (CASE WHEN CL_TYPE IN ('INS','INST') THEN BANKID ELSE '' END), 
			PCOUNT = 2	
		FROM 
			NSEFO..CLIENT1 C1 (NOLOCK),
			NSEFO..CLIENT2 C2 (NOLOCK),
			NSEFO..CLIENT5 C5 (NOLOCK)
		WHERE
			C1.CL_CODE = C2.CL_CODE
			AND C5.CL_CODE = C1.CL_CODE
			AND C5.Systumdate >= @TRADEDATE 
		
		-----
		UNION
		-----
		
		SELECT 
			DISTINCT
			PARTY_CODE,
			LONG_NAME,
			CL_TYPE,
			BANKID = (CASE WHEN CL_TYPE IN ('INS','INST') THEN BANKID ELSE '' END),
			PCOUNT = 16	
		FROM 
			MCDX..CLIENT1 C1 (NOLOCK),
			MCDX..CLIENT2 C2 (NOLOCK),
			MCDX..CLIENT5 C5 (NOLOCK)
		WHERE
			C1.CL_CODE = C2.CL_CODE
			AND C5.CL_CODE = C1.CL_CODE
			AND C5.Systumdate >= @TRADEDATE 
		
		-----
		UNION
		-----
		
		SELECT 
			DISTINCT
			PARTY_CODE,
			LONG_NAME,
			CL_TYPE,
			BANKID = (CASE WHEN CL_TYPE IN ('INS','INST') THEN BANKID ELSE '' END),
			PCOUNT = 64	
		FROM 
			NCDX..CLIENT1 C1 (NOLOCK),
			NCDX..CLIENT2 C2 (NOLOCK),
			NCDX..CLIENT5 C5 (NOLOCK)
		WHERE
			C1.CL_CODE = C2.CL_CODE
			AND C5.CL_CODE = C1.CL_CODE
			AND C5.Systumdate >= @TRADEDATE 
		/*
		-----
		UNION
		-----
		
		SELECT 
			DISTINCT
			PARTY_CODE,
			LONG_NAME,
			CL_TYPE,
			BANKID = (CASE WHEN CL_TYPE IN ('INS','INST') THEN BANKID ELSE '' END),
			PCOUNT = 4	
		FROM 
			BSEFO..CLIENT1 C1 (NOLOCK),
			BSEFO..CLIENT2 C2 (NOLOCK)
		WHERE
			C1.CL_CODE = C2.CL_CODE */
	
		)  CLIENTMASTER
	
	GROUP BY
		PARTY_CODE,
		LONG_NAME,
		CL_TYPE,
		BANKID
	
	ORDER BY
		PARTY_CODE,
		LEFT(LONG_NAME,40)

GO
