-- Object: PROCEDURE dbo.TRANSFER_TRADE_INS
-- Server: 10.253.33.91 | DB: NSESLBS
--------------------------------------------------

CREATE PROCEDURE TRANSFER_TRADE_INS
	@LEVEL VARCHAR(5),
	@FPARTY VARCHAR(10),
	@SCRIPCD VARCHAR(10),
	@SERIES VARCHAR(3),
	@SELLBUY INT,
	@SAUDA_DATE VARCHAR(10),
	@PROCESSON VARCHAR(20),
	@TPARTY VARCHAR(10),
	@STATUSNAME VARCHAR(100),
	@FROMWHERE VARCHAR(200)

AS

	SET @FPARTY = LTRIM(RTRIM(@FPARTY))
	SET @LEVEL = LTRIM(RTRIM(@LEVEL))
	SET @SCRIPCD = LTRIM(RTRIM(@SCRIPCD))
	SET @SERIES = LTRIM(RTRIM(@SERIES))
	SET @SAUDA_DATE = LTRIM(RTRIM(@SAUDA_DATE))
	SET @PROCESSON = LTRIM(RTRIM(@PROCESSON))
	SET @TPARTY = LTRIM(RTRIM(@TPARTY))
	SET @STATUSNAME = LTRIM(RTRIM(@STATUSNAME))
	SET @FROMWHERE = LTRIM(RTRIM(@FROMWHERE))
	SELECT
		FROMPARTY = @FPARTY,
		TOPARTY = @TPARTY,
		SCRIPCD = CASE @SCRIPCD WHEN '' THEN 'ALL' ELSE @SCRIPCD END,
		SERIES = CASE @SERIES WHEN '' THEN 'ALL' ELSE @SERIES END,
		SAUDADATE = @SAUDA_DATE,
		TABLE_PROCESS = @PROCESSON,
		USERNAME = @STATUSNAME,
		MODULE = @FROMWHERE

GO
