-- Object: PROCEDURE dbo.TRADE_CONSOLIDATION_INS_ALL
-- Server: 10.253.33.91 | DB: NSESLBS
--------------------------------------------------





CREATE PROC [dbo].[TRADE_CONSOLIDATION_INS_ALL]
	@SETTNO VARCHAR(7),
	@SETTTYPE VARCHAR(2),
	@SAUDADATE VARCHAR(10),
	@FROMPARTY VARCHAR(10),
	@TOPARTY VARCHAR(10),
	@FROMSCRIP VARCHAR(10),
	@TOSCRIP VARCHAR(10),
	@FROMTERM VARCHAR(10),
	@TOTERM VARCHAR(10),
	@CONSOLIDATE INT,
	@LEVEL INT,
	@CONTRACTNO VARCHAR(7),
	@AFTERCONTRACT VARCHAR(1) = 'Y',
	@SELL_BUY INT = 0,
	@PARTICIPANT VARCHAR(20) = '',
	@ORDER_NO VARCHAR(16) = '',
	@SHOW INT = 0,
	@TRFTABLE VARCHAR(20) = 'TRADE'
AS
	/*
	Exec TRADE_CONSOLIDATION_INS_ALL '', '', '01/06/2007', '0', 'ZZZZZZZZZZ', '', '', '', '', 3, 1, '', 'N', 0, '', ''
	Exec TRADE_CONSOLIDATION_INS_ALL '', '', '01/06/2007', '0', 'ZZZZZZZZZZ', '', '', '', '', 2, 2, '', 'Y', 0, '', '', 0
	*/
	DECLARE @SQL AS VARCHAR(8000)
	DECLARE @MEMBER VARCHAR(15)
	SET @MEMBER = ''
	SELECT @MEMBER = ISNULL(MEMBERCODE, '') FROM OWNER
	CREATE TABLE #TRADE_CONSOLIDATION
	(
		PARTY_CODE VARCHAR(10),
		ORGPARTY VARCHAR(10),
		PARTIPANTCODE VARCHAR(15),
		USER_ID VARCHAR(10),
		CONTRACTNO VARCHAR(7),
		SCRIP_CD VARCHAR(10),
		SERIES VARCHAR(2),
		SETT_NO VARCHAR(7),
		SETT_TYPE VARCHAR(2),
		DUMMY2 VARCHAR(15),
		SELL_BUY VARCHAR(4),
		QTY INT,
		MKTRATE MONEY,
		NETRATE MONEY,
		AMOUNT MONEY,
		DEALTICKETPRICE MONEY,
		NETAMOUNT MONEY,
		PARTY_NAME VARCHAR(100),
		R_MKTRATE INT,
		R_BROKERAGE INT,
		R_NETRATE INT,
		STP_TYPE VARCHAR(5),
		STP_FLAG BIT,
		CL_TYPE VARCHAR(3)
	)
	IF @CONSOLIDATE = 2
		BEGIN
			SET @SQL = "INSERT INTO #TRADE_CONSOLIDATION "
			SET @SQL = @SQL + "( "
			SET @SQL = @SQL + "	PARTY_CODE, "
			SET @SQL = @SQL + "	ORGPARTY, "
			SET @SQL = @SQL + "	PARTIPANTCODE, "
			SET @SQL = @SQL + "	USER_ID, "
			SET @SQL = @SQL + "	CONTRACTNO, "
			SET @SQL = @SQL + "	SCRIP_CD, "
			SET @SQL = @SQL + "	SERIES, "
			SET @SQL = @SQL + "	SETT_NO, "
			SET @SQL = @SQL + "	SETT_TYPE, "
			SET @SQL = @SQL + "	DUMMY2, "
			SET @SQL = @SQL + "	SELL_BUY, "
			SET @SQL = @SQL + "	QTY, "
			SET @SQL = @SQL + "	MKTRATE, "
			SET @SQL = @SQL + "	NETRATE, "
			SET @SQL = @SQL + "	AMOUNT, "
			SET @SQL = @SQL + "	DEALTICKETPRICE, "
			SET @SQL = @SQL + "	NETAMOUNT, "
			SET @SQL = @SQL + "	PARTY_NAME, "
			SET @SQL = @SQL + "	R_MKTRATE, "
			SET @SQL = @SQL + "	R_BROKERAGE, "
			SET @SQL = @SQL + "	R_NETRATE, "
			SET @SQL = @SQL + "	STP_TYPE, "
			SET @SQL = @SQL + "	STP_FLAG, "
			SET @SQL = @SQL + "	CL_TYPE "
			SET @SQL = @SQL + ") "
			SET @SQL = @SQL + "	SELECT "
			SET @SQL = @SQL + "		I.PARTY_CODE, "
			SET @SQL = @SQL + "		ORGPARTY = I.PARTY_CODE, "
			SET @SQL = @SQL + "		I.PARTIPANTCODE, "
			SET @SQL = @SQL + "		I.USER_ID, "
			SET @SQL = @SQL + "		I.CONTRACTNO, "
			SET @SQL = @SQL + "		I.SCRIP_CD, "
			SET @SQL = @SQL + "		I.SERIES, "
			SET @SQL = @SQL + "		I.SETT_NO, "
			SET @SQL = @SQL + "		I.SETT_TYPE, "
			SET @SQL = @SQL + "		I.DUMMY2, "
			SET @SQL = @SQL + "		SELL_BUY = CASE WHEN I.SELL_BUY = 1 THEN 'BUY' ELSE 'SALE' END, "
			SET @SQL = @SQL + "		QTY = SUM(I.TRADEQTY), "
			SET @SQL = @SQL + "		MKTRATE = ((SUM(I.DUMMY1*I.TRADEQTY)) / (SUM(I.TRADEQTY))), "
			SET @SQL = @SQL + "		NETRATE = CONVERT(NUMERIC(12, 4), CASE ISNULL(R.NETRATE, 4) WHEN 2 THEN ROUND(((SUM(I.NETRATE*I.TRADEQTY)) / (SUM(I.TRADEQTY))), 2, 1) WHEN 4 THEN ROUND(((SUM(I.NETRATE*I.TRADEQTY)) / (SUM(I.TRADEQTY))), 4, 1) ELSE ROUND(((SUM(I.NETRATE*I.TRADEQTY)) / (SUM(I.TRADEQTY))), 4, 1) END), "
			SET @SQL = @SQL + "		AMOUNT = SUM(I.TRADEQTY * I.MARKETRATE), "
			SET @SQL = @SQL + "		DEALTICKETPRICE = CONVERT(NUMERIC(12, 4), CASE ISNULL(R.MARKETRATE, 4) WHEN 2 THEN ROUND(((SUM(I.MARKETRATE*I.TRADEQTY)) / (SUM(I.TRADEQTY))), 2, 1) WHEN 4 THEN ROUND(((SUM(I.MARKETRATE*I.TRADEQTY)) / (SUM(I.TRADEQTY))), 4, 1) ELSE ROUND(((SUM(I.MARKETRATE*I.TRADEQTY)) / (SUM(I.TRADEQTY))), 4, 1) END), "
			SET @SQL = @SQL + "		NETAMOUNT = CONVERT(NUMERIC(12, 4), CASE ISNULL(R.NETRATE, 4) WHEN 2 THEN ROUND(((SUM(I.NETRATE*I.TRADEQTY)) / (SUM(I.TRADEQTY))), 2, 1) WHEN 4 THEN ROUND(((SUM(I.NETRATE*I.TRADEQTY)) / (SUM(I.TRADEQTY))), 4, 1) ELSE ROUND(((SUM(I.NETRATE*I.TRADEQTY)) / (SUM(I.TRADEQTY))), 4, 1) END), "
			SET @SQL = @SQL + "		PARTY_NAME = C1.LONG_NAME, "
			SET @SQL = @SQL + "		R_MKTRATE = ISNULL(R.MARKETRATE, 4), "
			SET @SQL = @SQL + "		R_BROKERAGE = ISNULL(R.BROKERAGE, 4), "
			SET @SQL = @SQL + "		R_NETRATE = ISNULL(R.NETRATE, 4), "
			SET @SQL = @SQL + "		STP_TYPE = C2.DUMMY6, "
			SET @SQL = @SQL + "		STP_FLAG = 0,"
			SET @SQL = @SQL + "		CL_TYPE = C1.CL_TYPE "
			SET @SQL = @SQL + "	FROM"
			SET @SQL = @SQL + "		ISETTLEMENT I, "
			SET @SQL = @SQL + "		CLIENT2 C2"
			SET @SQL = @SQL + "			LEFT JOIN INSTCLIENT_TBL R"
			SET @SQL = @SQL + "				ON (C2.PARTY_CODE = R.PARTYCODE),"
			SET @SQL = @SQL + "		CLIENT1 C1"
			SET @SQL = @SQL + "	WHERE"
			SET @SQL = @SQL + "		C1.CL_CODE = C2.CL_CODE"
			SET @SQL = @SQL + "		AND I.PARTY_CODE = C2.PARTY_CODE"
			SET @SQL = @SQL + "		AND CONVERT(VARCHAR(10), SAUDA_DATE, 103) = '" + @SAUDADATE + "'"
			SET @SQL = @SQL + "		AND I.TRADEQTY > 0"
			IF @SELL_BUY <> 0
				BEGIN
					SET @SQL = @SQL + "		AND I.SELL_BUY = " + CONVERT(VARCHAR(1), @SELL_BUY) + " "
				END
			IF LTRIM(RTRIM(@SETTNO)) <> ''
				BEGIN
					SET @SQL = @SQL + "		AND I.SETT_NO = '" + @SETTNO + "'"
					SET @SQL = @SQL + "		AND I.SETT_TYPE = '" + @SETTTYPE + "'"
				END
			IF @CONTRACTNO <> ''
				BEGIN
					SET @SQL = @SQL + "		AND I.CONTRACTNO = '" + @CONTRACTNO + "'"
				END
			IF @CONSOLIDATE = 0
				BEGIN
					SET @SQL = @SQL + "		AND I.DUMMY2 = 0"
				END
			ELSE IF @CONSOLIDATE = 1
				BEGIN
					SET @SQL = @SQL + "		AND I.DUMMY2 = 1"
				END
			IF @FROMPARTY <> '' AND @TOPARTY = ''
				BEGIN
					SET @SQL = @SQL + "		AND I.PARTY_CODE = '" + @FROMPARTY + "'"
				END
			ELSE IF @FROMPARTY <> '' AND @TOPARTY <> ''
				BEGIN
					SET @SQL = @SQL + "		AND I.PARTY_CODE >= '" + @FROMPARTY + "'"
					SET @SQL = @SQL + "		AND I.PARTY_CODE <= '" + @TOPARTY + "'"
				END
			IF @FROMSCRIP <> ''
				BEGIN
					SET @SQL = @SQL + "		AND I.SCRIP_CD = '" + @FROMSCRIP + "'"
				END
			IF @FROMTERM <> ''
				BEGIN
					SET @SQL = @SQL + "		AND I.USER_ID >= '" + @FROMTERM + "'"
				END
			IF @TOTERM <> ''
				BEGIN
					SET @SQL = @SQL + "		AND I.USER_ID <= '" + @TOTERM + "'"
				END
			SET @SQL = @SQL + "	GROUP BY"
			SET @SQL = @SQL + "		I.PARTY_CODE,"
			SET @SQL = @SQL + "		I.PARTIPANTCODE,"
			SET @SQL = @SQL + "		I.USER_ID,"
			SET @SQL = @SQL + "		I.CONTRACTNO,"
			SET @SQL = @SQL + "		I.SCRIP_CD,"
			SET @SQL = @SQL + "		I.SERIES,"
			SET @SQL = @SQL + "		I.SELL_BUY,"
			SET @SQL = @SQL + "		I.SETT_NO,"
			SET @SQL = @SQL + "		I.SETT_TYPE,"
			SET @SQL = @SQL + "		C1.LONG_NAME,"
			SET @SQL = @SQL + "		I.DUMMY2,"
			SET @SQL = @SQL + "		ISNULL(R.MARKETRATE, 4),"
			SET @SQL = @SQL + "		ISNULL(R.BROKERAGE, 4),"
			SET @SQL = @SQL + "		ISNULL(R.NETRATE, 4),"
			SET @SQL = @SQL + "		C2.DUMMY6,"
			SET @SQL = @SQL + "		C1.CL_TYPE "
			SET @SQL = @SQL + "	ORDER BY"
			SET @SQL = @SQL + "		I.PARTY_CODE,"
			SET @SQL = @SQL + "		I.SCRIP_CD,"
			SET @SQL = @SQL + "		I.SERIES,"
			SET @SQL = @SQL + "		I.CONTRACTNO,"
			SET @SQL = @SQL + "		I.SELL_BUY"
			EXEC(@SQL)
			UPDATE
				H
			SET
				STP_FLAG = 1
			FROM
				#TRADE_CONSOLIDATION H
			WHERE
				H.STP_TYPE <> 'NSDL'
				AND EXISTS
					(SELECT
						PARTYCODE,
						CONTRACTNO
					FROM
						STP_HEADER_NEW S
					WHERE
						H.PARTY_CODE = S.PARTYCODE
						AND H.CONTRACTNO = S.CONTRACTNO
					)
			UPDATE
				H
			SET
				STP_FLAG = 1
			FROM
				#TRADE_CONSOLIDATION H
			WHERE
				H.STP_TYPE = 'NSDL'
				AND EXISTS
					(SELECT
						PARTYCODE,
						CONTRACTNO
					FROM
						MSAJAG.dbo.STP_HEADER_NEW S
					WHERE
						H.PARTY_CODE = S.PARTYCODE
						AND H.CONTRACTNO = S.CONTRACTNO
						AND LASTDATETIME = 'NSE'
					)
			SELECT *, SAUDA_DATE = CONVERT(VARCHAR(11), CONVERT(DATETIME, @SAUDADATE, 103), 109) FROM #TRADE_CONSOLIDATION
		END
	ELSE IF @CONSOLIDATE = 3
		BEGIN
			SET @SQL = "INSERT INTO #TRADE_CONSOLIDATION "
			SET @SQL = @SQL + "( "
			SET @SQL = @SQL + "	PARTY_CODE, "
			SET @SQL = @SQL + "	ORGPARTY, "
			SET @SQL = @SQL + "	PARTIPANTCODE, "
			SET @SQL = @SQL + "	USER_ID, "
			SET @SQL = @SQL + "	CONTRACTNO, "
			SET @SQL = @SQL + "	SCRIP_CD, "
			SET @SQL = @SQL + "	SERIES, "
			SET @SQL = @SQL + "	SETT_NO, "
			SET @SQL = @SQL + "	SETT_TYPE, "
			SET @SQL = @SQL + "	DUMMY2, "
			SET @SQL = @SQL + "	SELL_BUY, "
			SET @SQL = @SQL + "	QTY, "
			SET @SQL = @SQL + "	MKTRATE, "
			SET @SQL = @SQL + "	NETRATE, "
			SET @SQL = @SQL + "	AMOUNT, "
			SET @SQL = @SQL + "	DEALTICKETPRICE, "
			SET @SQL = @SQL + "	NETAMOUNT, "
			SET @SQL = @SQL + "	PARTY_NAME, "
			SET @SQL = @SQL + "	R_MKTRATE, "
			SET @SQL = @SQL + "	R_BROKERAGE, "
			SET @SQL = @SQL + "	R_NETRATE, "
			SET @SQL = @SQL + "	STP_TYPE, "
			SET @SQL = @SQL + "	STP_FLAG, "
			SET @SQL = @SQL + "	CL_TYPE "
			SET @SQL = @SQL + ") "
			SET @SQL = @SQL + "	SELECT "
			SET @SQL = @SQL + "		I.PARTY_CODE, "
			SET @SQL = @SQL + "		ORGPARTY = I.PARTY_CODE, "
			SET @SQL = @SQL + "		I.PARTIPANTCODE, "
			SET @SQL = @SQL + "		I.USER_ID, "
			SET @SQL = @SQL + "		I.CONTRACTNO, "
			SET @SQL = @SQL + "		I.SCRIP_CD, "
			SET @SQL = @SQL + "		I.SERIES, "
			SET @SQL = @SQL + "		I.SETT_NO, "
			SET @SQL = @SQL + "		I.SETT_TYPE, "
			SET @SQL = @SQL + "		I.DUMMY2, "
			SET @SQL = @SQL + "		SELL_BUY = CASE WHEN I.SELL_BUY = 1 THEN 'BUY' ELSE 'SALE' END, "
			SET @SQL = @SQL + "		QTY = SUM(I.TRADEQTY), "
			SET @SQL = @SQL + "		MKTRATE = ((SUM(I.DUMMY1*I.TRADEQTY)) / (SUM(I.TRADEQTY))), "
			SET @SQL = @SQL + "		NETRATE = CONVERT(NUMERIC(12, 4), CASE ISNULL(R.NETRATE, 4) WHEN 2 THEN ROUND(((SUM(I.NETRATE*I.TRADEQTY)) / (SUM(I.TRADEQTY))), 2, 1) WHEN 4 THEN ROUND(((SUM(I.NETRATE*I.TRADEQTY)) / (SUM(I.TRADEQTY))), 4, 1) ELSE ROUND(((SUM(I.NETRATE*I.TRADEQTY)) / (SUM(I.TRADEQTY))), 4, 1) END), "
			SET @SQL = @SQL + "		AMOUNT = SUM(I.TRADEQTY * I.MARKETRATE), "
			SET @SQL = @SQL + "		DEALTICKETPRICE = CONVERT(NUMERIC(12, 4), CASE ISNULL(R.MARKETRATE, 4) WHEN 2 THEN ROUND(((SUM(I.MARKETRATE*I.TRADEQTY)) / (SUM(I.TRADEQTY))), 2, 1) WHEN 4 THEN ROUND(((SUM(I.MARKETRATE*I.TRADEQTY)) / (SUM(I.TRADEQTY))), 4, 1) ELSE ROUND(((SUM(I.MARKETRATE*I.TRADEQTY)) / (SUM(I.TRADEQTY))), 4, 1) END), "
			SET @SQL = @SQL + "		NETAMOUNT = CONVERT(NUMERIC(12, 4), CASE ISNULL(R.NETRATE, 4) WHEN 2 THEN ROUND(((SUM(I.NETRATE*I.TRADEQTY)) / (SUM(I.TRADEQTY))), 2, 1) WHEN 4 THEN ROUND(((SUM(I.NETRATE*I.TRADEQTY)) / (SUM(I.TRADEQTY))), 4, 1) ELSE ROUND(((SUM(I.NETRATE*I.TRADEQTY)) / (SUM(I.TRADEQTY))), 4, 1) END), "
			SET @SQL = @SQL + "		PARTY_NAME = C1.LONG_NAME, "
			SET @SQL = @SQL + "		R_MKTRATE = ISNULL(R.MARKETRATE, 4), "
			SET @SQL = @SQL + "		R_BROKERAGE = ISNULL(R.BROKERAGE, 4), "
			SET @SQL = @SQL + "		R_NETRATE = ISNULL(R.NETRATE, 4), "
			SET @SQL = @SQL + "		STP_TYPE = C2.DUMMY6, "
			SET @SQL = @SQL + "		STP_FLAG = 0,"
			SET @SQL = @SQL + "		CL_TYPE = C1.CL_TYPE "
			SET @SQL = @SQL + "	FROM"
			SET @SQL = @SQL + "		SETTLEMENT I, "
			SET @SQL = @SQL + "		CLIENT2 C2"
			SET @SQL = @SQL + "			LEFT JOIN INSTCLIENT_TBL R"
			SET @SQL = @SQL + "				ON (C2.PARTY_CODE = R.PARTYCODE),"
			SET @SQL = @SQL + "		CLIENT1 C1"
			SET @SQL = @SQL + "	WHERE"
			SET @SQL = @SQL + "		C1.CL_CODE = C2.CL_CODE"
			SET @SQL = @SQL + "		AND C1.CL_TYPE = 'INS'"
			SET @SQL = @SQL + "		AND I.PARTY_CODE = C2.PARTY_CODE"
			SET @SQL = @SQL + "		AND CONVERT(VARCHAR(10), SAUDA_DATE, 103) = '" + @SAUDADATE + "'"
			SET @SQL = @SQL + "		AND I.TRADEQTY > 0"
			IF @SELL_BUY <> 0
				BEGIN
					SET @SQL = @SQL + "		AND I.SELL_BUY = " + CONVERT(VARCHAR(1), @SELL_BUY) + " "
				END
			IF LTRIM(RTRIM(@SETTNO)) <> ''
				BEGIN
					SET @SQL = @SQL + "		AND I.SETT_NO = '" + @SETTNO + "'"
					SET @SQL = @SQL + "		AND I.SETT_TYPE = '" + @SETTTYPE + "'"
				END
			IF @CONTRACTNO <> ''
				BEGIN
					SET @SQL = @SQL + "		AND I.CONTRACTNO = '" + @CONTRACTNO + "'"
				END
			IF @CONSOLIDATE = 0
				BEGIN
					SET @SQL = @SQL + "		AND I.DUMMY2 = 0"
				END
			ELSE IF @CONSOLIDATE = 1
				BEGIN
					SET @SQL = @SQL + "		AND I.DUMMY2 = 1"
				END
			IF @FROMPARTY <> '' AND @TOPARTY = ''
				BEGIN
					SET @SQL = @SQL + "		AND I.PARTY_CODE = '" + @FROMPARTY + "'"
				END
			ELSE IF @FROMPARTY <> '' AND @TOPARTY <> ''
				BEGIN
					SET @SQL = @SQL + "		AND I.PARTY_CODE >= '" + @FROMPARTY + "'"
					SET @SQL = @SQL + "		AND I.PARTY_CODE <= '" + @TOPARTY + "'"
				END
			IF @FROMSCRIP <> ''
				BEGIN
					SET @SQL = @SQL + "		AND I.SCRIP_CD = '" + @FROMSCRIP + "'"
				END
			IF @FROMTERM <> ''
				BEGIN
					SET @SQL = @SQL + "		AND I.USER_ID >= '" + @FROMTERM + "'"
				END
			IF @TOTERM <> ''
				BEGIN
					SET @SQL = @SQL + "		AND I.USER_ID <= '" + @TOTERM + "'"
				END
			SET @SQL = @SQL + "	GROUP BY"
			SET @SQL = @SQL + "		I.PARTY_CODE,"
			SET @SQL = @SQL + "		I.PARTIPANTCODE,"
			SET @SQL = @SQL + "		I.USER_ID,"
			SET @SQL = @SQL + "		I.CONTRACTNO,"
			SET @SQL = @SQL + "		I.SCRIP_CD,"
			SET @SQL = @SQL + "		I.SERIES,"
			SET @SQL = @SQL + "		I.SELL_BUY,"
			SET @SQL = @SQL + "		I.SETT_NO,"
			SET @SQL = @SQL + "		I.SETT_TYPE,"
			SET @SQL = @SQL + "		C1.LONG_NAME,"
			SET @SQL = @SQL + "		I.DUMMY2,"
			SET @SQL = @SQL + "		ISNULL(R.MARKETRATE, 4),"
			SET @SQL = @SQL + "		ISNULL(R.BROKERAGE, 4),"
			SET @SQL = @SQL + "		ISNULL(R.NETRATE, 4),"
			SET @SQL = @SQL + "		C2.DUMMY6,"
			SET @SQL = @SQL + "		C1.CL_TYPE "
			SET @SQL = @SQL + "	ORDER BY"
			SET @SQL = @SQL + "		I.PARTY_CODE,"
			SET @SQL = @SQL + "		I.SCRIP_CD,"
			SET @SQL = @SQL + "		I.SERIES,"
			SET @SQL = @SQL + "		I.CONTRACTNO,"
			SET @SQL = @SQL + "		I.SELL_BUY"
			EXEC(@SQL)
			UPDATE
				H
			SET
				STP_FLAG = 1
			FROM
				#TRADE_CONSOLIDATION H
			WHERE
				H.STP_TYPE <> 'NSDL'
				AND EXISTS
					(SELECT
						PARTYCODE,
						CONTRACTNO
					FROM
						STP_HEADER_NEW S
					WHERE
						H.PARTY_CODE = S.PARTYCODE
						AND H.CONTRACTNO = S.CONTRACTNO
					)
			UPDATE
				H
			SET
				STP_FLAG = 1
			FROM
				#TRADE_CONSOLIDATION H
			WHERE
				H.STP_TYPE = 'NSDL'
				AND EXISTS
					(SELECT
						PARTYCODE,
						CONTRACTNO
					FROM
						MSAJAG.dbo.STP_HEADER_NEW S
					WHERE
						H.PARTY_CODE = S.PARTYCODE
						AND H.CONTRACTNO = S.CONTRACTNO
					)
			SELECT *, SAUDA_DATE = CONVERT(VARCHAR(11), CONVERT(DATETIME, @SAUDADATE, 103), 109) FROM #TRADE_CONSOLIDATION
		END

GO
