-- Object: PROCEDURE dbo.CBO_CLIENTLIST
-- Server: 10.253.33.91 | DB: NSESLBS
--------------------------------------------------


CREATE PROC CBO_CLIENTLIST
	@STATUSID VARCHAR(25),
	@STATUSNAME VARCHAR(25),
	@FROMAC VARCHAR(10)='0',
	@TOAC VARCHAR(10)='ZZZZ',
	@FROMFILTER VARCHAR(15)='',
	@FROMFILTERVAL VARCHAR(20)='',
	@TOFILTER VARCHAR(15)='',
	@TOFILTERVAL VARCHAR(20)=''
AS
/*
*/
IF @FROMFILTER <> ''
	BEGIN
		IF @TOFILTER = ''
			BEGIN
				SET @TOFILTER = @FROMFILTER
			END
	END
IF @FROMFILTERVAL <> ''
	BEGIN
		IF @TOFILTERVAL = ''
			BEGIN
				SET @TOFILTERVAL = @FROMFILTERVAL
			END
	END

SELECT
	*
FROM
	.dbo.CBO_FN_LOGINCHECK_BASIC(@STATUSID, @STATUSNAME)
WHERE
(
	1 =	(CASE WHEN @FROMFILTER = 'AREA' AND @TOFILTER = 'AREA' AND AREA BETWEEN @FROMFILTERVAL AND @TOFILTERVAL 
			THEN 1 
			WHEN @FROMFILTER = 'REGION' AND @TOFILTER = 'REGION' AND REGION BETWEEN @FROMFILTERVAL AND @TOFILTERVAL 
			THEN 1 
			WHEN @FROMFILTER = 'BRANCH' AND @TOFILTER = 'BRANCH' AND BRANCH_CD BETWEEN @FROMFILTERVAL AND @TOFILTERVAL 
			THEN 1 
			WHEN @FROMFILTER = 'SUBBROKER' AND @TOFILTER = 'SUBBROKER' AND SUB_BROKER BETWEEN @FROMFILTERVAL AND @TOFILTERVAL 
			THEN 1 
			WHEN @FROMFILTER = 'TRADER' AND @TOFILTER = 'TRADER' AND TRADER BETWEEN @FROMFILTERVAL AND @TOFILTERVAL 
			THEN 1 
			WHEN @FROMFILTER = 'FAMILY' AND @TOFILTER = 'FAMILY' AND FAMILY BETWEEN @FROMFILTERVAL AND @TOFILTERVAL 
			THEN 1 
			WHEN @FROMFILTER = 'CLIENT' AND @TOFILTER = 'CLIENT' AND PARTY_CODE BETWEEN @FROMFILTERVAL AND @TOFILTERVAL 
			THEN 1 
			ELSE 2
		END)
	OR
	(
	AREA =	(CASE WHEN @FROMFILTER = 'AREA' 
				THEN @FROMFILTERVAL
				WHEN @TOFILTER = 'AREA' 
				THEN @TOFILTERVAL 
				ELSE AREA
			END)
	AND  
	REGION=	(CASE WHEN @FROMFILTER = 'REGION' 
				THEN @FROMFILTERVAL
				WHEN @TOFILTER = 'REGION' 
				THEN @TOFILTERVAL 
				ELSE REGION
			END)
	AND
	BRANCH_CD=	(CASE WHEN @FROMFILTER = 'BRANCH' 
					THEN @FROMFILTERVAL
					WHEN @TOFILTER = 'BRANCH' 
					THEN @TOFILTERVAL 
					ELSE BRANCH_CD
				END)
	AND  
	SUB_BROKER=	(CASE WHEN @FROMFILTER = 'SUBBROKER' 
					THEN @FROMFILTERVAL
					WHEN @TOFILTER = 'SUBBROKER' 
					THEN @TOFILTERVAL 
					ELSE SUB_BROKER
				END)
	AND
	TRADER =	(CASE WHEN @FROMFILTER = 'TRADER' 
					THEN @FROMFILTERVAL
					WHEN @TOFILTER = 'TRADER' 
					THEN @TOFILTERVAL 
					ELSE TRADER
				END)
	AND  
	FAMILY =	(CASE WHEN @FROMFILTER = 'FAMILY' 
					THEN @FROMFILTERVAL
					WHEN @TOFILTER = 'FAMILY' 
					THEN @TOFILTERVAL 
					ELSE FAMILY
				END)
	AND  
	PARTY_CODE =	(CASE WHEN @FROMFILTER = 'CLIENT' 
						THEN @FROMFILTERVAL
						WHEN @TOFILTER = 'CLIENT' 
						THEN @TOFILTERVAL 
						ELSE PARTY_CODE
					END)
	)
)
AND PARTY_CODE BETWEEN @FROMAC AND @TOAC

GO
