-- Object: PROCEDURE dbo.UpdateTrade_NOTIS
-- Server: 10.253.33.91 | DB: NSESLBS
--------------------------------------------------


  
  CREATE PROC [dbo].[UpdateTrade_NOTIS] AS            
UPDATE TRADE_IMP_NOTIS SET CPID = LEFT(CPID, 3), ORDERTIME = LEFT(ORDERTIME, 20)        
TRUNCATE TABLE TRADEMISSING            
INSERT INTO FTTRADE            
SELECT TRADE_NO,ORDER_NO,STATUS,SCRIP_CD,SERIES,SCRIPNAME,INSTRUMENT,BOOKTYPE,MARKETTYPE,USER_ID,PARTIPANTCODE,            
BRANCH_ID,SELL_BUY,TRADEQTY,MARKETRATE,PRO_CLI,PARTY_CODE,AUCTIONPART,AUCTIONNO,SETTNO,SAUDA_DATE,TRADEMODIFIED,            
CPID=ORDERTIME,1,'N',0,MARKETRATE,'0',EXPIRYDATE         
FROM TRADE_IMP_NOTIS

GO
