-- Object: PROCEDURE dbo.RPT_CLIENTMARGINREPORT
-- Server: 10.253.33.91 | DB: NSESLBS
--------------------------------------------------



CREATE PROC [dbo].[RPT_CLIENTMARGINREPORT]    
	(    
	@MDATE VARCHAR(11),    
	@FROMBRANCH VARCHAR(15),    
	@TOBRANCH VARCHAR(15),    
	@FROMPARTY VARCHAR(15),    
	@TOPARTY VARCHAR(15),    
	@STATUSID VARCHAR(15),    
	@STATUSNAME VARCHAR(25),  
	@FROMSUBBROKER VARCHAR(15) = '',  
	@TOSUBBROKER VARCHAR(15) ='zzzzzzzz',
	@DCNFLAG INT = 0
	)    
     
	AS    
    
	SET @DCNFLAG = CONVERT(NUMERIC,@DCNFLAG)
    
	SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED    
	SELECT  
		EXCHANGE = 'NSE',  
		SEGMENT = 'SLBS',     
		MDT_FD = SUM(PREV_FD),     
		MDT_BG = SUM(PREV_BG),     
		MDT_SEC = SUM(PREV_SEC),     
		MDT_CASH= SUM(PREV_CASH),     
		MDT_TOTAL = SUM((PREV_FD+PREV_BG+PREV_SEC+PREV_CASH)),    
		MAR_UTILISED = SUM(PREV_VAR),    
		MDT1_FD = SUM(CURR_FD),    
		MDT1_BG = SUM(CURR_BG),    
		MDT1_SEC= SUM(CURR_SEC),    
		MDT1_CASH = SUM(CURR_CASH),    
		MDT1_TOTAL= SUM((CURR_FD+CURR_BG+CURR_SEC+CURR_CASH)),    
		MAR_ADJUSTMENT = SUM(MAR_ADJUST),    
		MAR_STATUS = SUM(MAR_STATUS),    
		MAR_UTILISED_EXC = SUM(PREV_VAR),
		MAR_ADJUSTMENT_EXC = SUM(MAR_ADJUST),    
		MAR_STATUS_EXC = SUM(MAR_STATUS),    
		
		M.PARTY_CODE,    
		C1.LONG_NAME,    
		C1.L_ADDRESS1,    
		C1.L_ADDRESS2,    
		C1.L_ADDRESS3,    
		C1.L_CITY,    
		C1.L_ZIP,    
		C1.L_STATE,    
		C1.L_NATION,    
		C1.EMAIL,    
		C1.PAN_GIR_NO,    
		C1.BRANCH_CD,    
		C1.SUB_BROKER    
	FROM    
		MARGIN_REPORTING M (NOLOCK),    
		CLIENT1 C1 (NOLOCK),
		CLIENT2 C2 (NOLOCK),
		CLIENT_PRINT_SETTINGS CP (NOLOCK)    
	WHERE    
		M.PARTY_CODE = C2.PARTY_CODE
		AND C1.CL_CODE = C2.CL_CODE
		AND SAUDA_DATE LIKE @MDATE + '%'    
		AND M.PARTY_CODE >= @FROMPARTY    
		AND M.PARTY_CODE <= @TOPARTY    
		AND BRANCH_CD  >= @FROMBRANCH    
		AND BRANCH_CD  <= @TOBRANCH    
		AND SUB_BROKER >= @FROMSUBBROKER  
		AND SUB_BROKER <= @TOSUBBROKER  
		AND C2.PRINTF = CP.PRINT_FLAG	
		AND CP.VALID_REPORT LIKE (CASE 
						WHEN @DCNFLAG = 0 THEN '%' 
						WHEN @DCNFLAG = 1 THEN '%CONTRACT%' 
						WHEN @DCNFLAG = 2 THEN '%DIGITAL%' 
						ELSE CP.VALID_REPORT 
					END)
		AND @STATUSNAME = (     
			CASE   
			WHEN @STATUSID = 'BRANCH'   
			THEN C1.BRANCH_CD   
			WHEN @STATUSID = 'SUBBROKER'   
			THEN C1.SUB_BROKER   
			WHEN @STATUSID = 'TRADER'   
			THEN C1.TRADER   
			WHEN @STATUSID = 'FAMILY'   
			THEN C1.FAMILY   
			WHEN @STATUSID = 'AREA'   
			THEN C1.AREA   
			WHEN @STATUSID = 'REGION'   
			THEN C1.REGION   
			WHEN @STATUSID = 'CLIENT'   
			THEN M.PARTY_CODE   
			ELSE 'BROKER' END)   
	    
	GROUP BY    
		M.PARTY_CODE,    
		C1.LONG_NAME,    
		C1.L_ADDRESS1,    
		C1.L_ADDRESS2,    
		C1.L_ADDRESS3,    
		C1.L_CITY,    
		C1.L_ZIP,    
		C1.L_STATE,    
		C1.L_NATION,    
		C1.EMAIL,    
		C1.PAN_GIR_NO,    
		C1.BRANCH_CD,    
		C1.SUB_BROKER    
	    
	ORDER BY    
		M.PARTY_CODE,    
		BRANCH_CD,    
		SUB_BROKER

GO
