-- Object: PROCEDURE dbo.TBL_MARGIN_REPORT
-- Server: 10.253.33.91 | DB: NSESLBS
--------------------------------------------------


CREATE PROC TBL_MARGIN_REPORT
(@STATUSID VARCHAR(25),
@STATUSNAME VARCHAR(25),
@FROMDATE VARCHAR(11),
@TODATE VARCHAR(11),
@FROMPARTY VARCHAR(10),
@TOPARTY VARCHAR(10)
)

AS
SELECT PARTY_CODE,MARGIN_DATE,SCRIP_CD,SCRIP_NAME=CONVERT(VARCHAR(50),''),EXPIRYDATE,SELLQTY,SELLAMT,MTOM,VARAMOUNT=VARAMT-SELLAMT-MTOM,VARAMT AS TOTALAMT
INTO #TBL_MG02
FROM TBL_MG02 ,CLIENT1 C
WHERE MARGIN_DATE BETWEEN @FROMDATE AND @TODATE
AND PARTY_CODE BETWEEN @FROMPARTY AND @TOPARTY
AND TBL_MG02.PARTY_CODE=C.CL_CODE
AND @STATUSNAME =             
					  (CASE             
							WHEN @STATUSID = 'BRANCH' THEN C.BRANCH_CD            
							WHEN @STATUSID = 'SUBBROKER' THEN C.SUB_BROKER            
							WHEN @STATUSID = 'TRADER' THEN C.TRADER            
							WHEN @STATUSID = 'FAMILY' THEN C.FAMILY            
							WHEN @STATUSID = 'AREA' THEN C.AREA            
							WHEN @STATUSID = 'REGION' THEN C.REGION            
							WHEN @STATUSID = 'CLIENT' THEN C.CL_CODE
					  ELSE             
							'BROKER'            
					  END)    

UPDATE T  SET SCRIP_NAME= S1.SHORT_NAME FROM #TBL_MG02 T,
SCRIP1 S1 ,SCRIP2 S2 
WHERE T.SCRIP_CD=S2.SCRIP_CD
AND S1.CO_CODE=S2.CO_CODE


SELECT * FROM #TBL_MG02

DROP TABLE #TBL_MG02

GO
