-- Object: TABLE dbo.SLIP_DETAIL
-- Server: 10.253.78.187 | DB: inhouse
--------------------------------------------------

CREATE TABLE [dbo].[SLIP_DETAIL]
(
    [SLIP_NO] VARCHAR(20) NULL,
    [SLIP_DATE] DATETIME NULL,
    [RECEIPT_CODE] INT NOT NULL,
    [CLIENT_CODE] VARCHAR(20) NULL,
    [ISIN] VARCHAR(12) NULL,
    [ISIN_NAME] VARCHAR(20) NULL,
    [QTY] MONEY NULL,
    [EXEC_DATE] DATETIME NULL,
    [STAGE] VARCHAR(1) NULL,
    [STATUS] VARCHAR(1) NULL,
    [REJECT_CODE] VARCHAR(10) NULL,
    [REJECT_REASON] VARCHAR(200) NULL
);

GO
