-- Object: TABLE dbo.TBL_EXP_CLIENT_POA
-- Server: 10.253.78.187 | DB: inhouse
--------------------------------------------------

CREATE TABLE [dbo].[TBL_EXP_CLIENT_POA]
(
    [RECEIPT_CODE] INT NULL,
    [BENEF_ACCNO] INT NULL,
    [SLIP_DATE] DATETIME NULL,
    [CLIENT_CODE] VARCHAR(16) NULL,
    [PURPOSE_CODE] VARCHAR(2) NULL,
    [POA_ID] VARCHAR(16) NULL,
    [SETUP_DATE] DATETIME NULL,
    [OPERATE_AC] VARCHAR(1) NULL,
    [GPA_BPA_FLAG] VARCHAR(1) NULL,
    [FROM_DATE] DATETIME NULL,
    [TO_DATE] DATETIME NULL,
    [REMARKS] VARCHAR(50) NULL,
    [STAGE] VARCHAR(1) NULL,
    [STATUS] VARCHAR(1) NULL,
    [TRXN_TYPE] VARCHAR(3) NULL
);

GO
