-- Object: VIEW citrus_usr.VW_NEWKYC_Nominee
-- Server: 10.253.78.187 | DB: DMAT
--------------------------------------------------


-- SELECT * FROM CITRUS_USR.VW_NEWKYC_NOMINEE 
create VIEW [citrus_usr].[VW_NEWKYC_Nominee]
AS
SELECT DPHD_DPAM_SBA_NO, DPHD_NOM_FNAME,
DPHD_NOM_MNAME,
DPHD_NOM_LNAME,
DPHD_NOM_FTHNAME,
CASE WHEN CONVERT(VARCHAR(11),DPHD_NOM_DOB,109)='JAN  1 1900' THEN '' ELSE CONVERT(VARCHAR(11),DPHD_NOM_DOB,109) END DPHD_NOM_DOB,
DPHD_NOM_PAN_NO,
DPHD_NOM_GENDER,
NOM_NRN_NO,
CITRUS_USR.FN_SPLITVAL(CITRUS_USR.FN_ACCT_ADDR_VALUE(DPHD_DPAM_ID,'NOMINEE_ADR1'),1) NADD1,
CITRUS_USR.FN_SPLITVAL(CITRUS_USR.FN_ACCT_ADDR_VALUE(DPHD_DPAM_ID,'NOMINEE_ADR1'),2)NADD2,
CITRUS_USR.FN_SPLITVAL(CITRUS_USR.FN_ACCT_ADDR_VALUE(DPHD_DPAM_ID,'NOMINEE_ADR1'),3) NADD3,
CITRUS_USR.FN_SPLITVAL(CITRUS_USR.FN_ACCT_ADDR_VALUE(DPHD_DPAM_ID,'NOMINEE_ADR1'),4) NCITY,
CITRUS_USR.FN_SPLITVAL(CITRUS_USR.FN_ACCT_ADDR_VALUE(DPHD_DPAM_ID,'NOMINEE_ADR1'),5) NSTATE,
CITRUS_USR.FN_SPLITVAL(CITRUS_USR.FN_ACCT_ADDR_VALUE(DPHD_DPAM_ID,'NOMINEE_ADR1'),6) NCOUNTRY,
CITRUS_USR.FN_SPLITVAL(CITRUS_USR.FN_ACCT_ADDR_VALUE(DPHD_DPAM_ID,'NOMINEE_ADR1'),7) NPINCODE,
ISNULL([citrus_usr].[fn_acct_conc_value](DPHD_DPAM_ID,'NOMINEE_MAIL'),'') NEMAIL,
ISNULL([citrus_usr].[fn_acct_conc_value](DPHD_DPAM_ID,'NOMINEE_MOB'),'') NMOB,
ISNULL([citrus_usr].[fn_acct_conc_value](DPHD_DPAM_ID,'NOMINEE_RES'),'') NRES,
ISNULL([citrus_usr].[fn_acct_conc_value](DPHD_DPAM_ID,'NOMINEE_OFF'),'') NOFF,
DPHD_NOMGAU_FNAME,
DPHD_NOMGAU_MNAME,
DPHD_NOMGAU_LNAME,
DPHD_NOMGAU_FTHNAME,
CASE WHEN CONVERT(VARCHAR(11),DPHD_NOMGAU_DOB,109)='JAN  1 1900' THEN '' ELSE CONVERT(VARCHAR(11),DPHD_NOMGAU_DOB,109) END DPHD_NOMGAU_DOB,
DPHD_NOMGAU_PAN_NO,
DPHD_NOMGAU_GENDER
FROM DP_HOLDER_DTLS
WHERE LEN(DPHD_DPAM_SBA_NO)='16'
AND DPHD_DELETED_IND=1 
AND ISNULL(DPHD_NOM_FNAME,'')<>''

GO
