-- Object: PROCEDURE citrus_usr.PR_ANGEL_BSDA_IMPORT_MSTR
-- Server: 10.253.78.187 | DB: DMAT
--------------------------------------------------



CREATE PROCEDURE [citrus_usr].[PR_ANGEL_BSDA_IMPORT_MSTR]
(
  @PA_BOID VARCHAR(16)
, @PA_BILLMONTH DATETIME
, @PA_FILLER1 VARCHAR(50)
, @PA_FILLER2 VARCHAR(50)
, @PA_FILLER3 VARCHAR(50)
, @PA_FILLER4 VARCHAR(50)
, @PA_FILLER5 VARCHAR(50)
)
AS
BEGIN

INSERT INTO ANGEL_BSDA_IMPORT_MSTR
SELECT 
--  @PA_BOID 
--, @PA_BILLMONTH 
--, @PA_FILLER1 
--, @PA_FILLER2 
--, @PA_FILLER3 
--, @PA_FILLER4 
--, @PA_FILLER5 
BOID
,BILLMONTH
,FILLER1
,FILLER2
,FILLER3
,FILLER4
,FILLER5
from TMP_ANGEL_BSDA_IMPORT_MSTR T
WHERE 
--NOT EXISTS (SELECT BOID FROM ANGEL_BSDA_IMPORT_MSTR WHERE BOID=@PA_BOID AND BILLMONTH=@PA_BILLMONTH)
NOT EXISTS (SELECT M.BOID FROM ANGEL_BSDA_IMPORT_MSTR M WHERE t.BOID=m.BOID AND t.BILLMONTH=t.BILLMONTH)
END

GO
