-- Object: PROCEDURE citrus_usr.pr_get_txt_filegen_ForAngelID_04112016
-- Server: 10.253.78.187 | DB: DMAT
--------------------------------------------------


--pr_get_txt_filegen_ForAngelID 'CXPTRX','12033200','1203320000714231','1203320000714231','Apr  1 2016','Apr 30 2016'
CREATE PROC [citrus_usr].[pr_get_txt_filegen_ForAngelID_04112016](@PA_ACTION VARCHAR(100),@PA_DPID VARCHAR(100)    
,@PA_BOID VARCHAR(100)    
,@PA_ISIN VARCHAR(100)    
,@PA_FROM_DATE DATETIME    
,@PA_TO_DATE DATETIME    
)    
AS    
BEGIN    
  
-- FOR ECNFLAG


--SELECT DISTINCT ACCP_VALUE, ACCP_CLISBA_ID , ACCP_ACCPM_PROP_CD 
--INTO #ACCOUNT_PROPERTIES_ECN FROM ACCOUNT_PROPERTIES 
--WHERE ACCP_ACCPM_PROP_CD = 'ECN_FLAG' 
--AND ACCP_VALUE NOT IN ('','//') AND ACCP_VALUE='NO'

create table #ACCOUNT_PROPERTIES_ECN (ACCP_VALUE varchar(50),ACCP_CLISBA_ID numeric,ACCP_ACCPM_PROP_CD varchar(50))


INSERT INTO #ACCOUNT_PROPERTIES_ECN 
SELECT '',DPAM_ID , '' FROM DP_ACCT_MSTR 
--WHERE
--NOT EXISTS (SELECT 1 FROM ACCOUNT_PROPERTIES WHERE ACCP_CLISBA_ID = DPAM_ID 
--AND ACCP_ACCPM_PROP_CD ='ECN_FLAG')


SELECT * INTO #TMP_CLIENT_CHARGES_CDSL FROM (
SELECT CLIC_DPAM_ID ,CLIC_TRANS_DT  FROM CLIENT_CHARGES_CDSL  WITH(NOLOCK)  ,DP_ACCT_MSTR   WITH(NOLOCK)  WHERE 
CLIC_TRANS_DT BETWEEN CITRUS_USR.UFN_GETFIRSTDAYOFMONTH(@PA_FROM_DATE) AND @PA_TO_DATE
AND CLIC_DPAM_ID = DPAM_ID AND CASE WHEN @PA_BOID ='' THEN '1' ELSE DPAM_SBA_NO END = CASE WHEN @PA_BOID ='' THEN '1' ELSE @PA_BOID END 
UNION 
SELECT CDSHM_DPAM_ID CLIC_DPAM_ID , CDSHM_TRAS_DT  CLIC_TRANS_DT FROM CDSL_HOLDING_DTLS WITH(NOLOCK) WHERE 
CDSHM_TRAS_DT  BETWEEN CITRUS_USR.UFN_GETFIRSTDAYOFMONTH(@PA_FROM_DATE) AND @PA_TO_DATE
 AND CASE WHEN @PA_BOID ='' THEN '1' ELSE CDSHM_BEN_ACCT_NO   END = CASE WHEN @PA_BOID ='' THEN '1' ELSE @PA_BOID END 
 AND CDSHM_TRATM_CD IN('2246','2277','2201','3102','2270','2220','2262','2251','2202','2205','2280') 
)  A 
     


-- FOR ECNFLAG

--SELECT DISTINCT '' ACCP_VALUE, DPAM_ID ACCP_CLISBA_ID , '' ACCP_ACCPM_PROP_CD 
--INTO #ACCOUNT_PROPERTIES_ECN FROM DP_ACCT_MSTR,TMP_BOUNCEBACK_MSTR
--WHERE DPAM_SBA_NO=[CLIENT  ID]

--INSERT INTO #ACCOUNT_PROPERTIES_ECN 
--SELECT '',DPAM_ID , '' FROM DP_ACCT_MSTR WHERE
--  EXISTS (SELECT 1 FROM ACCOUNT_PROPERTIES WHERE ACCP_CLISBA_ID = DPAM_ID 
--AND ACCP_ACCPM_PROP_CD ='ECN_FLAG')


    
  IF @PA_ACTION = 'HOLDING'    
  BEGIN     
  CREATE TABLE #HOLDINGALLFORVIEW  
  (DPHMCD_DPM_ID NUMERIC  
  ,DPHMCD_DPAM_ID NUMERIC  
  ,DPHMCD_ISIN VARCHAR(100)  
  ,DPHMCD_CURR_QTY NUMERIC(18,3)  
  ,DPHMCD_FREE_QTY NUMERIC(18,3)  
  ,DPHMCD_FREEZE_QTY NUMERIC(18,3)  
  ,DPHMCD_PLEDGE_QTY NUMERIC(18,3)  
  ,DPHMCD_DEMAT_PND_VER_QTY NUMERIC(18,3)  
  ,DPHMCD_REMAT_PND_CONF_QTY NUMERIC(18,3)  
  ,DPHMCD_DEMAT_PND_CONF_QTY NUMERIC(18,3)  
  ,DPHMCD_SAFE_KEEPING_QTY NUMERIC(18,3)  
  ,DPHMCD_LOCKIN_QTY NUMERIC(18,3)  
  ,DPHMCD_ELIMINATION_QTY NUMERIC(18,3)  
  ,DPHMCD_EARMARK_QTY NUMERIC(18,3)  
  ,DPHMCD_AVAIL_LEND_QTY NUMERIC(18,3)  
  ,DPHMCD_LEND_QTY NUMERIC(18,3)  
  ,DPHMCD_BORROW_QTY NUMERIC(18,3)  
  ,DPHMCD_HOLDING_DT DATETIME)   
    
  IF @PA_BOID <> '' AND NOT EXISTS (SELECT 1 FROM DP_HLDG_MSTR_CDSL_MONTHEND_HOLDING WHERE DPHMC_HOLDING_DT=@PA_TO_DATE)  
  INSERT INTO #HOLDINGALLFORVIEW(DPHMCD_DPM_ID   
  ,DPHMCD_DPAM_ID   
  ,DPHMCD_ISIN   
  ,DPHMCD_CURR_QTY   
  ,DPHMCD_FREE_QTY   
  ,DPHMCD_FREEZE_QTY   
  ,DPHMCD_PLEDGE_QTY   
  ,DPHMCD_DEMAT_PND_VER_QTY   
  ,DPHMCD_REMAT_PND_CONF_QTY   
  ,DPHMCD_DEMAT_PND_CONF_QTY   
  ,DPHMCD_SAFE_KEEPING_QTY   
  ,DPHMCD_LOCKIN_QTY   
  ,DPHMCD_ELIMINATION_QTY   
  ,DPHMCD_EARMARK_QTY   
  ,DPHMCD_AVAIL_LEND_QTY   
  ,DPHMCD_LEND_QTY   
  ,DPHMCD_BORROW_QTY   
  ,DPHMCD_HOLDING_DT)  
  EXEC [PR_GET_HOLDING_FIX_LATEST] 3,@PA_TO_DATE,@PA_TO_DATE,@PA_BOID,@PA_BOID,''    
  
  IF @PA_BOID <> '' AND  EXISTS (SELECT 1 FROM DP_HLDG_MSTR_CDSL_MONTHEND_HOLDING WHERE DPHMC_HOLDING_DT=@PA_TO_DATE)  
  INSERT INTO #HOLDINGALLFORVIEW(DPHMCD_DPM_ID   
  ,DPHMCD_DPAM_ID   
  ,DPHMCD_ISIN   
  ,DPHMCD_CURR_QTY   
  ,DPHMCD_FREE_QTY   
  ,DPHMCD_FREEZE_QTY   
  ,DPHMCD_PLEDGE_QTY   
  ,DPHMCD_DEMAT_PND_VER_QTY   
  ,DPHMCD_REMAT_PND_CONF_QTY   
  ,DPHMCD_DEMAT_PND_CONF_QTY   
  ,DPHMCD_SAFE_KEEPING_QTY   
  ,DPHMCD_LOCKIN_QTY   
  ,DPHMCD_ELIMINATION_QTY   
  ,DPHMCD_EARMARK_QTY   
  ,DPHMCD_AVAIL_LEND_QTY   
  ,DPHMCD_LEND_QTY   
  ,DPHMCD_BORROW_QTY   
  ,DPHMCD_HOLDING_DT)  
  SELECT  DPHMC_DPM_ID   
  ,DPHMC_DPAM_ID   
  ,DPHMC_ISIN   
  ,DPHMC_CURR_QTY   
  ,DPHMC_FREE_QTY   
  ,DPHMC_FREEZE_QTY   
  ,DPHMC_PLEDGE_QTY   
  ,DPHMC_DEMAT_PND_VER_QTY   
  ,DPHMC_REMAT_PND_CONF_QTY   
  ,DPHMC_DEMAT_PND_CONF_QTY   
  ,DPHMC_SAFE_KEEPING_QTY   
  ,DPHMC_LOCKIN_QTY   
  ,DPHMC_ELIMINATION_QTY   
  ,DPHMC_EARMARK_QTY   
  ,DPHMC_AVAIL_LEND_QTY   
  ,DPHMC_LEND_QTY   
  ,DPHMC_BORROW_QTY   
  ,DPHMC_HOLDING_DT FROM DP_HLDG_MSTR_CDSL_MONTHEND_HOLDING , DP_ACCT_MSTR 
  WHERE DPHMC_DPAM_ID = DPAM_ID AND DPAM_SBA_NO = @PA_BOID AND  DPHMC_HOLDING_DT = @PA_TO_DATE
  
  
  IF @PA_BOID = ''  AND NOT EXISTS (SELECT 1 FROM DP_HLDG_MSTR_CDSL_MONTHEND_HOLDING WHERE DPHMC_HOLDING_DT=@PA_TO_DATE)    
  INSERT INTO #HOLDINGALLFORVIEW(DPHMCD_DPM_ID   
  ,DPHMCD_DPAM_ID   
  ,DPHMCD_ISIN   
  ,DPHMCD_CURR_QTY   
  ,DPHMCD_FREE_QTY   
  ,DPHMCD_FREEZE_QTY   
  ,DPHMCD_PLEDGE_QTY   
  ,DPHMCD_DEMAT_PND_VER_QTY   
  ,DPHMCD_REMAT_PND_CONF_QTY   
  ,DPHMCD_DEMAT_PND_CONF_QTY   
  ,DPHMCD_SAFE_KEEPING_QTY   
  ,DPHMCD_LOCKIN_QTY   
  ,DPHMCD_ELIMINATION_QTY   
  ,DPHMCD_EARMARK_QTY   
  ,DPHMCD_AVAIL_LEND_QTY   
  ,DPHMCD_LEND_QTY   
  ,DPHMCD_BORROW_QTY   
  ,DPHMCD_HOLDING_DT)  
  EXEC [PR_GET_HOLDING_FIX_LATEST] 3,@PA_TO_DATE,@PA_TO_DATE,'0','9999999999999999','' 
  
  
  IF @PA_BOID = ''  AND  EXISTS (SELECT 1 FROM DP_HLDG_MSTR_CDSL_MONTHEND_HOLDING WHERE DPHMC_HOLDING_DT=@PA_TO_DATE)    
  INSERT INTO #HOLDINGALLFORVIEW(DPHMCD_DPM_ID   
  ,DPHMCD_DPAM_ID   
  ,DPHMCD_ISIN   
  ,DPHMCD_CURR_QTY   
  ,DPHMCD_FREE_QTY   
  ,DPHMCD_FREEZE_QTY   
  ,DPHMCD_PLEDGE_QTY   
  ,DPHMCD_DEMAT_PND_VER_QTY   
  ,DPHMCD_REMAT_PND_CONF_QTY   
  ,DPHMCD_DEMAT_PND_CONF_QTY   
  ,DPHMCD_SAFE_KEEPING_QTY   
  ,DPHMCD_LOCKIN_QTY   
  ,DPHMCD_ELIMINATION_QTY   
  ,DPHMCD_EARMARK_QTY   
  ,DPHMCD_AVAIL_LEND_QTY   
  ,DPHMCD_LEND_QTY   
  ,DPHMCD_BORROW_QTY   
  ,DPHMCD_HOLDING_DT)  
  SELECT  DPHMC_DPM_ID   
  ,DPHMC_DPAM_ID   
  ,DPHMC_ISIN   
  ,DPHMC_CURR_QTY   
  ,DPHMC_FREE_QTY   
  ,DPHMC_FREEZE_QTY   
  ,DPHMC_PLEDGE_QTY   
  ,DPHMC_DEMAT_PND_VER_QTY   
  ,DPHMC_REMAT_PND_CONF_QTY   
  ,DPHMC_DEMAT_PND_CONF_QTY   
  ,DPHMC_SAFE_KEEPING_QTY   
  ,DPHMC_LOCKIN_QTY   
  ,DPHMC_ELIMINATION_QTY   
  ,DPHMC_EARMARK_QTY   
  ,DPHMC_AVAIL_LEND_QTY   
  ,DPHMC_LEND_QTY   
  ,DPHMC_BORROW_QTY   
  ,DPHMC_HOLDING_DT FROM DP_HLDG_MSTR_CDSL_MONTHEND_HOLDING 
  WHERE DPHMC_HOLDING_DT = @PA_TO_DATE
  
	truncate table FILEGEN_FORANGELID_holding_MIMANSA

     INSERT INTO FILEGEN_FORANGELID_holding_MIMANSA
     SELECT distinct  DPAM_SBA_NO BOID , DPHMCD_ISIN ISIN_CD , ISIN_NAME 
     ,CONVERT(VARCHAR,CASE WHEN LEFT(DPHMCD_ISIN ,3) = 'INF' THEN CONVERT(NUMERIC(18,3),DPHMCD_FREEZE_QTY) ELSE CONVERT(NUMERIC(18,2),DPHMCD_FREEZE_QTY) END )   FREEZE_QTY
     ,CONVERT(VARCHAR,CASE WHEN LEFT(DPHMCD_ISIN ,3) = 'INF' THEN CONVERT(NUMERIC(18,3),DPHMCD_PLEDGE_QTY) ELSE  CONVERT(NUMERIC(18,2),DPHMCD_PLEDGE_QTY) END ) PLEDGE_QTY
     ,CONVERT(VARCHAR,CASE WHEN LEFT(DPHMCD_ISIN ,3) = 'INF' THEN CONVERT(NUMERIC(18,3),DPHMCD_FREE_QTY) ELSE CONVERT(NUMERIC(18,2),DPHMCD_FREE_QTY) END )       FREE_QTY    
     ,CONVERT(VARCHAR,CASE WHEN LEFT(DPHMCD_ISIN ,3) = 'INF' THEN CONVERT(NUMERIC(18,3),DPHMCD_LOCKIN_QTY) ELSE CONVERT(NUMERIC(18,2),DPHMCD_LOCKIN_QTY) END )   LOCKIN_QTY  
     ,CONVERT(VARCHAR,0)   FILLER0 
     ,CONVERT(VARCHAR,CASE WHEN LEFT(DPHMCD_ISIN ,3) = 'INF' THEN CONVERT(NUMERIC(18,3),DPHMCD_DEMAT_PND_VER_QTY) ELSE CONVERT(NUMERIC(18,2),DPHMCD_DEMAT_PND_VER_QTY) END )   DPHMCD_DEMAT_PND_VER_QTY    
     ,CONVERT(VARCHAR,0)  FILLER1
     ,CONVERT(VARCHAR,0)  FILLER2  
     ,CONVERT(VARCHAR,0)  FILLER3  
     ,CONVERT(VARCHAR,0)  FILLER4  
     ,CONVERT(VARCHAR,ISNULL(CONVERT(NUMERIC(18,2),CLOPM_CDSL_RT),'0')) AS CLOSINGRATE FROM #HOLDINGALLFORVIEW WITH (NOLOCK)
     LEFT OUTER JOIN  CLOSING_PRICE_MSTR_CDSL ON DPHMCD_ISIN = CLOPM_ISIN_CD AND ISNULL(CLOPM_DT,'01/01/1900') = ( SELECT TOP 1 CLOPM_DT FROM CLOSING_PRICE_MSTR_CDSL WHERE CLOPM_ISIN_CD = DPHMCD_ISIN AND CLOPM_DT <= @PA_TO_DATE AND CLOPM_DELETED_IND = 1  ORDER BY CLOPM_DT DESC)                                                             
     , DP_ACCT_MSTR WITH (NOLOCK), ISIN_MSTR WITH (NOLOCK)    ,
     #ACCOUNT_PROPERTIES_ECN
     WHERE DPHMCD_DPAM_ID = DPAM_ID   AND ACCP_CLISBA_ID=DPAM_ID  
     AND  ISIN_CD = DPHMCD_ISIN     
     AND DPAM_DELETED_IND = 1     
     AND DPAM_SBA_NO LIKE  @PA_BOID + '%' AND DPHMCD_ISIN LIKE @PA_ISIN + '%'    
     AND EXISTS(SELECT 1 FROM #TMP_CLIENT_CHARGES_CDSL WHERE CLIC_DPAM_ID = DPHMCD_DPAM_ID 
     AND CLIC_TRANS_DT BETWEEN CITRUS_USR.UFN_GETFIRSTDAYOFMONTH(@PA_FROM_DATE) AND @PA_TO_DATE ) 
     AND NOT EXISTS (SELECT CLIENT_CODE FROM ANGELOWNACCOUNT WHERE CLIENT_CODE=DPAM_SBA_NO) 
     order by DPAM_SBA_NO,DPHMCD_ISIN,ISIN_NAME,FREEZE_QTY,PLEDGE_QTY,FREE_QTY,LOCKIN_QTY,DPHMCD_DEMAT_PND_VER_QTY
       
       
  END     
  IF @PA_ACTION = 'TRX'    
  BEGIN     
  
   create table #ob(ob_cdshm_dpm_id numeric,ob_cdshm_dpam_id numeric,ob_cdshm_isin varchar(100),ob numeric(18,3))
  if @pa_boid <>'' 
  insert into #ob
  exec [pr_get_ob_fix] 3,@pa_from_date,@pa_to_date,@pa_boid,@pa_boid,''
  if @pa_boid ='' 
  insert into #ob
  exec [pr_get_ob_fix] 3,@pa_from_date,@pa_to_date,'0','9999999999999999',''
  
   
     
      
   select identity(numeric,1,1) id,cdshm_dpam_id ,cdshm_isin , convert(numeric(18,3),cdshm_qty) cdshm_qty, ISNULL(convert(numeric(18,3),ob),0) ob
    ,cdshm_tras_dt,  cdshm_ben_acct_no +'|'    
   +CONVERT(varchar(11),cdshm_tras_dt,112) +'|'    
   +cdshm_trans_no +'|'    
   +cdshm_isin +'|'+isin_name +'|'+CDSHM_TRATM_DESC +'|'++'|'+convert(varchar,'####')+'|'+case when CDSHM_QTY > 0 then 'C' else 'D' end     
   +'|'+isnull(cdshm_internal_trastm,'')--MKTRXD    
   +'|'+convert(varchar,abs(convert(numeric(18,3),cdshm_qty)))--1000    
   +'|'+convert(varchar,'$$$$')  
   +'|'++'|'+ convert(varchar,abs(convert(numeric(18,2),cdshm_charge)))as value--11   
   , CDSHM_TRATM_CD
   into #tempdata from cdsl_holding_dtls with(nolock) left outer join #ob 
   on CDSHM_DPAM_ID = ob_cdshm_dpam_id and CDSHM_ISIN = ob_cdshm_isin ,ISIN_MSTR with(nolock)
   ,#ACCOUNT_PROPERTIES_ECN where cdshm_ben_acct_no like  @pa_boid + '%' and cdshm_isin like @pa_isin + '%'    
   and ISIN_CD = cdshm_isin    
   and ACCP_CLISBA_ID=CDSHM_DPAM_ID
   and CDSHM_TRATM_DESC is not null    
   and CDSHM_TRAS_DT between @pa_from_date and @pa_to_date   
    and exists(select 1 from #TMP_CLIENT_CHARGES_CDSL where CLIC_DPAM_ID = CDSHM_DPAM_ID  and CLIC_TRANS_DT between @pa_from_date and @pa_to_date )  
    and CDSHM_TRATM_CD in  ('2246','2277','2201','3102','2270','2220','2205')    
    and not exists (select client_code from angelownaccount where client_code=CDSHM_BEN_ACCT_NO)
    order by CDSHM_DPAM_ID ,CDSHM_TRAS_DT, CDSHM_ISIN,case when CDSHM_QTY > 0 then 'C' else 'D' end
    
    
    
    
    select *,ob+ isnull((select SUM( cdshm_qty )  
    from #tempdata t2 where t1.CDSHM_ISIN= t2.CDSHM_ISIN and t1.CDSHM_DPAM_ID = t2.CDSHM_DPAM_ID 
    and t2.id<=t1.id  and t2.CDSHM_TRATM_CD <>'2201'
    ),0) closingbalance   into #tempfinal from #tempdata t1 
    
    select --*,closingbalance-cdshm_qty openingbalance , 
    replace(replace(value,'$$$$',closingbalance),'####',closingbalance-case when CDSHM_TRATM_CD ='2201' then 0 else cdshm_qty end) as value,ID into #dtmp
    from #tempfinal  order by id 
     
	 truncate table FILEGEN_FORANGELID_TRX_MIMANSA

     INSERT INTO FILEGEN_FORANGELID_TRX_MIMANSA

    Select  citrus_usr.FN_SPLITVAL_BY(value,1,'|') CLIENT_CODE,
    citrus_usr.FN_SPLITVAL_BY(value,2,'|') TRXN_DATE,
    citrus_usr.FN_SPLITVAL_BY(value,3,'|') TRXN_NO,
    citrus_usr.FN_SPLITVAL_BY(value,4,'|') ISIN_CD,
    citrus_usr.FN_SPLITVAL_BY(value,5,'|') ISIN_NAME,
    citrus_usr.FN_SPLITVAL_BY(value,6,'|') DESCRIPTION,
    citrus_usr.FN_SPLITVAL_BY(value,7,'|') SETTLEMENT_NO,
    citrus_usr.FN_SPLITVAL_BY(value,8,'|') OPENING_BALANCE,
    citrus_usr.FN_SPLITVAL_BY(value,9,'|') CREDIT_DEBIT,
    citrus_usr.FN_SPLITVAL_BY(value,10,'|') TRANSACTION_TYPE,
    citrus_usr.FN_SPLITVAL_BY(value,11,'|') FIELD10,    
    citrus_usr.FN_SPLITVAL_BY(value,12,'|') CLOSING_BALANCE,
    citrus_usr.FN_SPLITVAL_BY(value,13,'|') RATE,
    citrus_usr.FN_SPLITVAL_BY(value,14,'|') CHARGES
     from #Dtmp order by id
    --SELECT *,OB+(SELECT SUM(CDSHM_QTY) FROM #TEMPDATA T2 WHERE T1.CDSHM_ISIN= T2.CDSHM_ISIN AND T1.CDSHM_DPAM_ID = T2.CDSHM_DPAM_ID 
    --AND T2.ID<=T1.ID
    --)  RUNNINGBALANCE , REPLACE(REPLACE(VALUE,'$$$$',CONVERT(VARCHAR,OB+(SELECT SUM(CDSHM_QTY) FROM #TEMPDATA T2 WHERE T1.CDSHM_ISIN= T2.CDSHM_ISIN AND T1.CDSHM_DPAM_ID = T2.CDSHM_DPAM_ID 
    --AND T2.ID<=T1.ID
    --))),'####',CONVERT(VARCHAR,OB+(SELECT SUM(CDSHM_QTY) FROM #TEMPDATA T2 WHERE T1.CDSHM_ISIN= T2.CDSHM_ISIN AND T1.CDSHM_DPAM_ID = T2.CDSHM_DPAM_ID 
    --AND T2.ID<=T1.ID
    --)-CDSHM_QTY)) VALUE FROM #TEMPDATA T1     
       
       
      
  END     
  --IF @PA_ACTION = 'CLIENT'    
  --BEGIN
  
  
  --DECLARE @L_FIN_ID NUMERIC 
  --SELECT   @L_FIN_ID = FIN_ID FROM FINANCIAL_YR_MSTR WHERE @PA_FROM_DATE BETWEEN FIN_START_DT AND FIN_END_DT AND FIN_DELETED_IND =1 
  --DECLARE @SQL VARCHAR(8000)
  --SET @SQL = ''
  --SELECT @SQL  = 'SELECT DPAM_SBA_NO OS_BOID, SUM(LDG_AMOUNT) OS INTO ##BILLED_OS FROM LEDGER'+CONVERT(VARCHAR,@L_FIN_ID)
  --SELECT @SQL  = @SQL + ' , DP_ACCT_MSTR WHERE DPAM_ID = LDG_ACCOUNT_ID AND LDG_ACCOUNT_TYPE =''P'' AND LDG_DELETED_IND = 1'
  --SELECT @SQL  = @SQL + ' AND EXISTS (SELECT 1 FROM #TMP_CLIENT_CHARGES_CDSL WHERE CLIC_DPAM_ID = DPAM_ID AND CLIC_TRANS_DT BETWEEN '''+ CONVERT(VARCHAR(11),@PA_FROM_DATE,109) + ''' AND  ''' +  CONVERT(VARCHAR(11),@PA_TO_DATE,109)
  --SELECT @SQL  = @SQL + ''') AND LDG_VOUCHER_DT < ''' + CONVERT(VARCHAR(11),@PA_FROM_DATE,109)
  --SELECT @SQL  = @SQL + ''' GROUP BY DPAM_SBA_NO '
  --PRINT @SQL
  --EXEC(@SQL) 
  
  --SELECT * INTO #BILLED_OS FROM ##BILLED_OS
  --DROP TABLE ##BILLED_OS
  
  
  --DECLARE @SQL22 VARCHAR(8000)
  --SET @SQL22 = ''
  --SELECT @SQL22  = 'SELECT DPAM_SBA_NO OS_BOID22, SUM(LDG_AMOUNT) OS22 INTO ##BILLED_OS22 FROM LEDGER'+CONVERT(VARCHAR,@L_FIN_ID)
  --SELECT @SQL22  = @SQL22 + ' , DP_ACCT_MSTR WHERE DPAM_ID = LDG_ACCOUNT_ID AND LDG_ACCOUNT_TYPE =''P'' AND LDG_DELETED_IND = 1'
  --SELECT @SQL22  = @SQL22 + ' AND EXISTS (SELECT 1 FROM #TMP_CLIENT_CHARGES_CDSL WHERE CLIC_DPAM_ID = DPAM_ID AND CLIC_TRANS_DT BETWEEN '''+ CONVERT(VARCHAR(11),@PA_FROM_DATE,109) + ''' AND  ''' +  CONVERT(VARCHAR(11),@PA_TO_DATE,109)
  --SELECT @SQL22  = @SQL22 + ''') AND LDG_VOUCHER_DT < ''' + CONVERT(VARCHAR(11),@PA_TO_DATE,109)
  --SELECT @SQL22  = @SQL22 + ''' GROUP BY DPAM_SBA_NO '
  --PRINT @SQL22
  --EXEC(@SQL22) 
  
  --SELECT * INTO #BILLED_OS22 FROM ##BILLED_OS22
  --DROP TABLE ##BILLED_OS22
  
  --SELECT DPAM_SBA_NO CLIC_BO_ID ,   SUM(CLIC_CHARGE_AMT) AMT INTO #BILLAMT FROM CLIENT_CHARGES_CDSL , DP_ACCT_MSTR 
  --WHERE CLIC_TRANS_DT BETWEEN @PA_FROM_DATE AND @PA_TO_DATE 
  --AND CLIC_DPAM_ID= DPAM_ID AND DPAM_DELETED_IND = 1
  --AND CLIC_DELETED_IND = 1 
  --AND CLIC_CHARGE_NAME <>'SERVICE TAX' GROUP BY DPAM_SBA_NO
  
  --SELECT DPAM_SBA_NO CLIC_BO_ID_ST ,   SUM(CLIC_CHARGE_AMT) STAMT INTO #STAMT FROM CLIENT_CHARGES_CDSL , DP_ACCT_MSTR 
  --WHERE CLIC_TRANS_DT BETWEEN @PA_FROM_DATE AND @PA_TO_DATE 
  --AND CLIC_DPAM_ID= DPAM_ID AND DPAM_DELETED_IND = 1
  --AND CLIC_DELETED_IND = 1 
  --AND CLIC_CHARGE_NAME ='SERVICE TAX' GROUP BY DPAM_SBA_NO
   
        
  --  SELECT ISNULL(DPAM_BBO_CODE  ,'')  
  --  +'|'+DPAM_SBA_NO    
  --  +'|'+ENTTM_DESC    
  --  +'|'+STAM_CD    
  --  +'|'+CLICM_DESC    
  --  +'|'+SUBCM_DESC    
  --  +'|'+''-- 2015021457401    
  --  +'|'+CONVERT(VARCHAR(8),CONVERT(DATETIME,@PA_FROM_DATE,103),112) + '-' + CONVERT(VARCHAR(8),CONVERT(DATETIME,@PA_TO_DATE,103),112)--20150201-20150228    
  --  +'|'+CONVERT(VARCHAR(8),CONVERT(DATETIME,@PA_TO_DATE,103),112)--20150228    
  --  +'|'+CONVERT(VARCHAR(8),CONVERT(DATETIME,@PA_TO_DATE+30,103),112) -- ''--20150330    
  --  +'|'+DPAM_SBA_NAME    
  --  +'|'+ADDR1     
  --  +'|'+ADDR2    
  --  +'|'+ISNULL(ADDR3,'')    
  --  +'|'+CITY    
  --  +'|'+STATE    
  --  +'|'+PINCODE    
  --  +'|'+PRIPHNUM  --9431009950    
  --  +'|'+ LTRIM(RTRIM(ISNULL(REPLACE(CITRUS_USR.FN_FIND_RELATIONS_ACCT_NM(DPAM_SBA_NO,'BR'),'_BR',''),''))) + '~' + ISNULL(REPLACE(CITRUS_USR.FN_FIND_RELATIONS_ACCTLVL(DPAM_ID,'BR'),'_BR',''),'')--PATNA BR-RIP LTD~PTN    
  --  +'|'+EMAILID      
  --  +'|'+CASE WHEN ISNULL(CITRUS_USR.FN_UCC_BROM(DPAM_ID,@PA_TO_DATE),'')='1' THEN 'INVESTOR' ELSE ISNULL(CITRUS_USR.FN_UCC_BROM(DPAM_ID,@PA_TO_DATE),'') END --LIFE INVESTOR    
  --  +'|'+ CONVERT(VARCHAR,ISNULL(ABS(CONVERT(NUMERIC(18,2),AMT)),0))--CURR BILL AMT (SELECT TOP 1 CONVERT(VARCHAR,CONVERT(NUMERIC(18,2),SUM(CLIC_CHARGE_AMT)*-1)) FROM #TMP_CLIENT_CHARGES_CDSL WHERE CLIC_DPAM_ID=DPAM_ID AND CLIC_TRANS_DT BETWEEN @PA_FROM_DATE AND @PA_TO_DATE AND CLIC_CHARGE_NAME<>'SERVICE TAX')--11    
  --  +'|'+ CONVERT(VARCHAR,ISNULL(ABS(CONVERT(NUMERIC(18,2),STAMT)),0))--CURR BILL ST (SELECT TOP 1 CONVERT(VARCHAR,CONVERT(NUMERIC(18,2),SUM(CLIC_CHARGE_AMT)*-1)) FROM #TMP_CLIENT_CHARGES_CDSL WHERE CLIC_DPAM_ID=DPAM_ID AND CLIC_TRANS_DT BETWEEN @PA_FROM_DATE AND @PA_TO_DATE AND CLIC_CHARGE_NAME='SERVICE TAX')--11    --1.3596    
  --  +'|'+ CONVERT(VARCHAR,ISNULL(ABS(CONVERT(NUMERIC(18,2),OS)),0)) --PREV BAL AS ON JUN 30 2015(SELECT TOP  1 CONVERT(VARCHAR,SUM(LDG_AMOUNT)) FROM LEDGER2 WHERE LDG_ACCOUNT_ID=DPAM_ID AND LDG_DELETED_IND=1 AND LDG_VOUCHER_DT<=@PA_TO_DATE)--0    
  --  +'|'+ CONVERT(VARCHAR,ISNULL(ABS(CONVERT(NUMERIC(18,2),OS22)),0)+ISNULL(ABS(CONVERT(NUMERIC(18,2),STAMT)),0)+ISNULL(ABS(CONVERT(NUMERIC(18,2),AMT)),0))  -- NET AMOUNT CONVERT(VARCHAR,((SELECT TOP 1 CONVERT(NUMERIC(18,2),SUM(CLIC_CHARGE_AMT)*-1) FROM #TMP_CLIENT_CHARGES_CDSL WHERE CLIC_DPAM_ID=DPAM_ID AND CLIC_TRANS_DT BETWEEN @PA_FROM_DATE AND @PA_TO_DATE ) -     (SELECT TOP  1 SUM(LDG_AMOUNT) FROM LEDGER2 WHERE LDG_ACCOUNT_ID=DPAM_ID AND LDG_DELETED_IND=1 AND LDG_VOUCHER_DT<=@PA_TO_DATE) ))--(SELECT TOP 1 CONVERT(NUMERIC(18,2),SUM(CLIC_CHARGE_AMT))-CONVERT(NUMERIC(18,2),SUM(LDG_AMOUNT)) FROM #TMP_CLIENT_CHARGES_CDSL,LEDGER2 WHERE CLIC_DPAM_ID=DPAM_ID AND CLIC_DPAM_ID=LDG_ACCOUNT_ID AND LDG_DELETED_IND=1 AND LDG_VOUCHER_DT<=@PA_TO_DATE AND CLIC_TRANS_DT BETWEEN 'JUL  1 2015' AND 'JUL 31 2015')--12.3596    
  --  +'|'+CONVERT(VARCHAR(8),CONVERT(DATETIME,@PA_TO_DATE,103),112)--20150228    
  --  +'|'+CONVERT(VARCHAR(8),CONVERT(DATETIME,@PA_TO_DATE,103),112)--20150228    
  --  +'|'+CONVERT(VARCHAR(8),CONVERT(DATETIME,@PA_FROM_DATE,103),112) + '-' + CONVERT(VARCHAR(8),CONVERT(DATETIME,@PA_TO_DATE,103),112)--20150201-20150228    
  --  +'|'+CONVERT(VARCHAR(8),CONVERT(DATETIME,@PA_FROM_DATE,103),112) + '-' + CONVERT(VARCHAR(8),CONVERT(DATETIME,@PA_TO_DATE,103),112) AS VALUE --20150201-20150228    
    
    
  --  FROM DP_ACCT_MSTR WITH(NOLOCK) LEFT OUTER JOIN  #BILLED_OS ON OS_BOID = DPAM_SBA_NO 
  --  LEFT OUTER JOIN  #BILLED_OS22 ON OS_BOID22 = DPAM_SBA_NO 
  --  LEFT OUTER JOIN  #BILLAMT ON CLIC_BO_ID = DPAM_SBA_NO 
  --  LEFT OUTER JOIN  #STAMT ON CLIC_BO_ID_ST = DPAM_SBA_NO 
  --  , CLIENT_CTGRY_MSTR WITH(NOLOCK), ENTITY_TYPE_MSTR WITH(NOLOCK)
  --  , SUB_CTGRY_MSTR WITH(NOLOCK), DPS8_PC1 WITH(NOLOCK), STATUS_MSTR WITH(NOLOCK)    
  --  ,#ACCOUNT_PROPERTIES_ECN
    
  --  WHERE BOID = DPAM_SBA_NO AND STAM_CD = DPAM_STAM_CD    AND ACCP_CLISBA_ID=DPAM_ID 
  --  AND CLICM_CD  = DPAM_CLICM_CD     
  --  AND ENTTM_CD = DPAM_ENTTM_CD     
  --  AND DPAM_SUBCM_CD = SUBCM_CD     
  --  AND DPAM_DELETED_IND = 1     
  --  AND DPAM_SBA_NO LIKE @PA_BOID + '%'   
  --  AND EXISTS(SELECT 1 FROM #TMP_CLIENT_CHARGES_CDSL WHERE CLIC_DPAM_ID = DPAM_ID  AND CLIC_TRANS_DT BETWEEN @PA_FROM_DATE AND @PA_TO_DATE )   
  --  AND NOT EXISTS (SELECT CLIENT_CODE FROM ANGELOWNACCOUNT WHERE CLIENT_CODE=DPAM_SBA_NO)

  --    DROP TABLE #BILLED_OS
  --END      
  IF @PA_ACTION = 'LEDGER'    
  BEGIN     
  --PRINT 3     
      
  DECLARE @L_FIN_ID1 NUMERIC 
  SELECT   @L_FIN_ID1 = FIN_ID FROM FINANCIAL_YR_MSTR WHERE @PA_FROM_DATE BETWEEN FIN_START_DT AND FIN_END_DT AND FIN_DELETED_IND =1 
  DECLARE @SQL1 VARCHAR(8000)
  SET @SQL1 = ''
  SELECT @SQL1  = 'SELECT DPAM_SBA_NO OS_BOID, convert(numeric(18,2),SUM(LDG_AMOUNT)) OS INTO ##BILLED_OS_LEDGER FROM LEDGER'+CONVERT(VARCHAR,@L_FIN_ID1)
  SELECT @SQL1  = @SQL1 + ' , DP_ACCT_MSTR WHERE DPAM_ID = LDG_ACCOUNT_ID AND LDG_ACCOUNT_TYPE =''P'' AND LDG_DELETED_IND = 1'
  SELECT @SQL1  = @SQL1 + ' AND EXISTS (SELECT 1 FROM #TMP_CLIENT_CHARGES_CDSL WHERE CLIC_DPAM_ID = DPAM_ID AND CLIC_TRANS_DT BETWEEN '''+ CONVERT(VARCHAR(11),@PA_FROM_DATE,109) + ''' AND  ''' +  CONVERT(VARCHAR(11),@PA_TO_DATE,109)
  SELECT @SQL1  = @SQL1 + ''') AND LDG_VOUCHER_DT < ''' + CONVERT(VARCHAR(11),@PA_FROM_DATE,109)
  SELECT @SQL1  = @SQL1 + ''' GROUP BY DPAM_SBA_NO '
  PRINT @SQL1
  EXEC(@SQL1) 
  
  SELECT * INTO #BILLED_OS_LEDGER  FROM ##BILLED_OS_LEDGER  
  DROP TABLE ##BILLED_OS_LEDGER  
  
  
  
   DECLARE @SQL11 VARCHAR(8000)
  SET @SQL11 = ''
  SELECT @SQL11  = 'SELECT IDENTITY(NUMERIC,1,1) ID ,ldg_id, DPAM_SBA_NO R_BOID,ISNULL(OS,''0'') OS , convert(numeric(18,2),SUM(LDG_AMOUNT)) R_AMOUNT,LDG_VOUCHER_DT R_VO_DT,LDG_NARRATION RE_NARRATION INTO ##BILLED_RE FROM LEDGER'+CONVERT(VARCHAR,@L_FIN_ID1)
  SELECT @SQL11  = @SQL11 + ' , DP_ACCT_MSTR LEFT OUTER JOIN #BILLED_OS_LEDGER ON OS_BOID = DPAM_SBA_NO  WHERE DPAM_ID = LDG_ACCOUNT_ID AND LDG_ACCOUNT_TYPE =''P'' AND LDG_DELETED_IND = 1'
  SELECT @SQL11  = @SQL11 + ' AND EXISTS (SELECT 1 FROM #TMP_CLIENT_CHARGES_CDSL WHERE CLIC_DPAM_ID = DPAM_ID AND CLIC_TRANS_DT BETWEEN '''+ CONVERT(VARCHAR(11),@PA_FROM_DATE,109) + ''' AND  ''' +  CONVERT(VARCHAR(11),@PA_TO_DATE,109)
  SELECT @SQL11  = @SQL11 + ''')  AND LDG_VOUCHER_DT BETWEEN ''' + CONVERT(VARCHAR(11),@PA_FROM_DATE,109)
  SELECT @SQL11  = @SQL11 + ''' AND  ''' + CONVERT(VARCHAR(11),@PA_TO_DATE,109) + ''' GROUP BY DPAM_SBA_NO ,ISNULL(OS,''0''),LDG_VOUCHER_DT,LDG_NARRATION,ldg_id ORDER BY DPAM_SBA_NO ,LDG_VOUCHER_DT,ldg_id'
  PRINT @SQL11
  EXEC(@SQL11) 
  
   
  SELECT * INTO #BILLED_RE FROM ##BILLED_RE
  DROP TABLE  ##BILLED_RE
  
  
    
    
    SELECT *,ISNULL(OS,'0')+(SELECT SUM(R_AMOUNT) FROM #BILLED_RE T2 WHERE T1.R_BOID= T2.R_BOID --AND T1.R_VO_DT = T2.R_VO_DT 
    AND T2.ID<=T1.ID
    )  CLOSINGBALANCE  
     INTO #BILLED_FINAL 
    FROM #BILLED_RE T1 
  
   truncate table FILEGEN_FORANGELID_ledger_MIMANSA

   INSERT INTO FILEGEN_FORANGELID_ledger_MIMANSA

   SELECT DPAM_SBA_NO BOID ,   
   --+CONVERT(VARCHAR(11),ISNULL(R_VO_DT,''),112)
   CASE WHEN CONVERT(VARCHAR(11),ISNULL(R_VO_DT,''),112)='19000101' THEN '' ELSE CONVERT(VARCHAR(11),ISNULL(R_VO_DT,''),112) END  VOUCHERDATE,    
   ISNULL(RE_NARRATION,'') NARRATION,
   CONVERT(VARCHAR,ISNULL(CASE WHEN (ISNULL(CLOSINGBALANCE,0)-ISNULL((R_AMOUNT),0))<0 THEN (ISNULL(CLOSINGBALANCE,0)-ISNULL((R_AMOUNT),0))*-1 WHEN (ISNULL(CLOSINGBALANCE,0)-ISNULL((R_AMOUNT),0))>0 THEN (ISNULL(CLOSINGBALANCE,0)-ISNULL((R_AMOUNT),0))*-1 ELSE (ISNULL(CLOSINGBALANCE,0)-ISNULL((R_AMOUNT),0))  END,0)) CLOSINGBAL,
       
   CASE WHEN R_AMOUNT < 0 THEN 'D' ELSE 'C' END CREDITDEBIT_FLAG,
   CONVERT(VARCHAR,ISNULL((ABS(R_AMOUNT)),0)) AMOUNT,
   CONVERT(VARCHAR,CASE WHEN ISNULL(CLOSINGBALANCE,0)<0 THEN ISNULL(CLOSINGBALANCE,0)*-1 WHEN ISNULL(CLOSINGBALANCE,0)>0 THEN ISNULL(CLOSINGBALANCE,0)*-1 ELSE ISNULL(CLOSINGBALANCE,0) END) AS VALUE--+61.8    
   FROM DP_ACCT_MSTR WITH(NOLOCK)  
   --LEFT OUTER JOIN #BILLED_OS_LEDGER  ON OS_BOID = DPAM_SBA_NO 
   LEFT OUTER JOIN #BILLED_FINAL ON R_BOID= DPAM_SBA_NO 
     ,#ACCOUNT_PROPERTIES_ECN
    WHERE  ACCP_CLISBA_ID=DPAM_ID  
   AND DPAM_DELETED_IND = 1 AND DPAM_SBA_NO LIKE  @PA_BOID + '%'  
   AND EXISTS(SELECT 1 FROM #TMP_CLIENT_CHARGES_CDSL WHERE CLIC_DPAM_ID = DPAM_ID   AND CLIC_TRANS_DT BETWEEN @PA_FROM_DATE AND @PA_TO_DATE )    
   AND NOT EXISTS (SELECT CLIENT_CODE FROM ANGELOWNACCOUNT WHERE CLIENT_CODE=DPAM_SBA_NO)  
   AND R_AMOUNT <>0     
      
      
      
  END    
  IF @PA_ACTION = 'SUMMARY'    
  BEGIN     
  --PRINT @PA_ACTION     
   
   truncate table FILEGEN_FORANGELID_SUMMARY_MIMANSA

   INSERT INTO FILEGEN_FORANGELID_SUMMARY_MIMANSA
     
   SELECT ISNULL(DPAM_SBA_NO,'') BOID ,   
   +CASE WHEN  ISNULL(CLIC_CHARGE_NAME,'')='1_DIBOOK' THEN 'DIS BOOK CHARGES'
WHEN  ISNULL(CLIC_CHARGE_NAME,'')='1_POAFIXED' THEN 'POA CHARGES'
WHEN  ISNULL(CLIC_CHARGE_NAME,'')='INV CORP_ACMAIN' THEN 'ANNUAL MAINTAINENCE CHARGES'
WHEN  ISNULL(CLIC_CHARGE_NAME,'')='JK INV_ACMAIN' THEN 'ANNUAL MAINTAINENCE CHARGES'
WHEN  ISNULL(CLIC_CHARGE_NAME,'')='LIF1250_DIBOOK' THEN 'DIS BOOK CHARGES'
WHEN  ISNULL(CLIC_CHARGE_NAME,'')='LIF1250_ONETIME' THEN 'LIF1250 AMC CHARGES'
WHEN  ISNULL(CLIC_CHARGE_NAME,'')='LIF1250_POAFIXED' THEN 'POA CHARGES'
WHEN  ISNULL(CLIC_CHARGE_NAME,'')='LIF1250C_POAFIXED' THEN 'POA CHARGES'
WHEN  ISNULL(CLIC_CHARGE_NAME,'')='LIF1250Q_DIBOOK' THEN 'DIS BOOK CHARGES'
WHEN  ISNULL(CLIC_CHARGE_NAME,'')='NBC_ACMAIN' THEN 'ANNUAL MAINTAINENCE CHARGES'
WHEN  ISNULL(CLIC_CHARGE_NAME,'')='NBFC INVW_DIBOOK' THEN 'DIS BOOK CHARGES'
WHEN  ISNULL(CLIC_CHARGE_NAME,'')='TRADERS_ACMAIN' THEN 'ANNUAL MAINTAINENCE CHARGES'
WHEN  ISNULL(CLIC_CHARGE_NAME,'')='TRADERS_POAFIXED' THEN 'POA CHARGES'
WHEN  ISNULL(CLIC_CHARGE_NAME,'')='ZEROWAIVE_DIBOOK' THEN 'DIS BOOK CHARGES'
WHEN  ISNULL(CLIC_CHARGE_NAME,'')='ZEROWAIVE_POAFIXED' THEN 'POA CHARGES'
WHEN  ISNULL(CLIC_CHARGE_NAME,'')='ZEROWAIVE1_POAFIXED' THEN 'POA CHARGES'
WHEN  ISNULL(CLIC_CHARGE_NAME,'')='DEMAT COURIER CHARGE' THEN 'DEMAT CHARGES'
WHEN  ISNULL(CLIC_CHARGE_NAME,'')='DEMAT REJECTION CHARGE' THEN 'DEMAT REJECTION CHARGES'
WHEN  ISNULL(CLIC_CHARGE_NAME,'')='1_ACMAIN' THEN 'ANNUAL MAINTAINENCE CHARGES'
 ELSE ISNULL(CLIC_CHARGE_NAME,'') END DESCRIPTION ,     
   +CONVERT(VARCHAR,ISNULL(CONVERT(NUMERIC(18,4),SUM(CLIC_CHARGE_AMT)),'0')*-1) AMOUNT  
   FROM CLIENT_CHARGES_CDSL  WITH(NOLOCK)    
   ,DP_ACCT_MSTR WITH(NOLOCK)  ,#ACCOUNT_PROPERTIES_ECN  
   WHERE CLIC_DPAM_ID = DPAM_ID AND CLIC_DELETED_IND = 1     AND ACCP_CLISBA_ID=DPAM_ID
   AND DPAM_DELETED_IND = 1 AND DPAM_SBA_NO LIKE @PA_BOID + '%'  
   AND CLIC_TRANS_DT BETWEEN @PA_FROM_DATE AND @PA_TO_DATE     
   AND NOT EXISTS (SELECT CLIENT_CODE FROM ANGELOWNACCOUNT WHERE CLIENT_CODE=DPAM_SBA_NO)
   GROUP BY     DPAM_SBA_NO ,  CLIC_CHARGE_NAME
  END      
  

  if @pa_action = 'SEBI1'     -- No transaction and no holding during the year
  begin 

--DROP TABLE TMPHLDG
--CREATE TABLE #TMPHLDG     
--(    
--[DPHMCD_DPM_ID] [NUMERIC](18, 0) NOT NULL,    
--[DPHMCD_DPAM_ID] [NUMERIC](10, 0) NOT NULL,    
--[DPHMCD_ISIN] [VARCHAR](20) NOT NULL,    
--[DPHMCD_CURR_QTY] [NUMERIC](18, 3) NULL,    
--[DPHMCD_FREE_QTY] [NUMERIC](18, 3) NULL,    
--[DPHMCD_FREEZE_QTY] [NUMERIC](18, 3) NULL,    
--[DPHMCD_PLEDGE_QTY] [NUMERIC](18, 3) NULL,    
--[DPHMCD_DEMAT_PND_VER_QTY] [NUMERIC](18, 3) NULL,    
--[DPHMCD_REMAT_PND_CONF_QTY] [NUMERIC](18, 3) NULL,    
--[DPHMCD_DEMAT_PND_CONF_QTY] [NUMERIC](18, 3) NULL,    
--[DPHMCD_SAFE_KEEPING_QTY] [NUMERIC](18, 3) NULL,    
--[DPHMCD_LOCKIN_QTY] [NUMERIC](18, 3) NULL,    
--[DPHMCD_ELIMINATION_QTY] [NUMERIC](18, 3) NULL,    
--[DPHMCD_EARMARK_QTY] [NUMERIC](18, 3) NULL,    
--[DPHMCD_AVAIL_LEND_QTY] [NUMERIC](18, 3) NULL,    
--[DPHMCD_LEND_QTY] [NUMERIC](18, 3) NULL,    
--[DPHMCD_BORROW_QTY] [NUMERIC](18, 3) NULL,    
--[DPHMCD_HOLDING_DT] DATETIME    
--)      

--INSERT INTO #TMPHLDG
--EXEC  [PR_GET_HOLDING_FIX_LATEST]   3,'MAR 31 2015','MAR 31 2015','0','9999999999999999',''    
--SELECT * INTO  TMPHLDG FROM  #TMPHLDG  
  
SELECT 
DPAM_SBA_NO +'|'    
+CONVERT(VARCHAR(11),'MAR 31 2016',112) +'|'    
+'0' +'|'    
+'' +'|'+'' +'|'+'' +'|'++'|'+CONVERT(VARCHAR,'')+'|'
+''    
+'|'+ISNULL('','')--MKTRXD    
+'|'+CONVERT(VARCHAR,ABS(CONVERT(NUMERIC(18,3),0)))--1000    
+'|'+CONVERT(VARCHAR,'')  
+'|'++'|'+ CONVERT(VARCHAR,ABS(CONVERT(NUMERIC(18,2),0)))AS VALUE
FROM DP_ACCT_MSTR 
WHERE  DPAM_STAM_CD ='ACTIVE' AND NOT EXISTS (SELECT 1 
				  FROM CDSL_HOLDING_DTLS 
				WHERE CDSHM_BEN_ACCT_NO = DPAM_SBA_NO
				AND CDSHM_TRAS_DT BETWEEN 'APR 01 2015' AND 'MAR 31 2016'
)
AND  NOT EXISTS (SELECT 1 
				  FROM TMPHLDG 
				WHERE DPHMCD_DPAM_ID  = DPAM_ID 
				)   
  end  
  
if @pa_action = 'SEBI2'     -- Account which become zero balance during the year
  begin 
--drop table TMPHLDG_EOY
--CREATE TABLE #TMPHLDG_EOY     
--(    
-- [DPHMCD_DPM_ID] [NUMERIC](18, 0) NOT NULL,    
-- [DPHMCD_DPAM_ID] [NUMERIC](10, 0) NOT NULL,    
-- [DPHMCD_ISIN] [VARCHAR](20) NOT NULL,    
-- [DPHMCD_CURR_QTY] [NUMERIC](18, 3) NULL,    
-- [DPHMCD_FREE_QTY] [NUMERIC](18, 3) NULL,    
-- [DPHMCD_FREEZE_QTY] [NUMERIC](18, 3) NULL,    
-- [DPHMCD_PLEDGE_QTY] [NUMERIC](18, 3) NULL,    
-- [DPHMCD_DEMAT_PND_VER_QTY] [NUMERIC](18, 3) NULL,    
-- [DPHMCD_REMAT_PND_CONF_QTY] [NUMERIC](18, 3) NULL,    
-- [DPHMCD_DEMAT_PND_CONF_QTY] [NUMERIC](18, 3) NULL,    
-- [DPHMCD_SAFE_KEEPING_QTY] [NUMERIC](18, 3) NULL,    
-- [DPHMCD_LOCKIN_QTY] [NUMERIC](18, 3) NULL,    
-- [DPHMCD_ELIMINATION_QTY] [NUMERIC](18, 3) NULL,    
-- [DPHMCD_EARMARK_QTY] [NUMERIC](18, 3) NULL,    
-- [DPHMCD_AVAIL_LEND_QTY] [NUMERIC](18, 3) NULL,    
-- [DPHMCD_LEND_QTY] [NUMERIC](18, 3) NULL,    
-- [DPHMCD_BORROW_QTY] [NUMERIC](18, 3) NULL,    
-- [DPHMCD_HOLDING_DT] DATETIME    
-- )      
    
--    INSERT INTO #TMPHLDG_EOY     
--    EXEC  [PR_GET_HOLDING_FIX_LATEST]   3,'MAR 31 2016','MAR 31 2016','0','9999999999999999','' 
--  SELECT * INTO  TMPHLDG_EOY FROM  #TMPHLDG_EOY

SELECT DPAM_SBA_NO ,
DPAM_SBA_NO +'|'    
+CONVERT(VARCHAR(11),'MAR 31 2016',112) +'|'    
+'0' +'|'    
+'' +'|'+'' +'|'+'' +'|'++'|'+CONVERT(VARCHAR,'')+'|'
+''    
+'|'+ISNULL('','')--MKTRXD    
+'|'+CONVERT(VARCHAR,ABS(CONVERT(NUMERIC(18,3),0)))--1000    
+'|'+CONVERT(VARCHAR,'')  
+'|'++'|'+ CONVERT(VARCHAR,ABS(CONVERT(NUMERIC(18,2),0)))AS VALUE
FROM DP_ACCT_MSTR 
WHERE  DPAM_STAM_CD ='ACTIVE' 
AND   EXISTS (SELECT 1 
				  FROM TMPHLDG 
				WHERE DPHMCD_DPAM_ID  = DPAM_ID 
				) 

AND   NOT EXISTS (SELECT 1 
				  FROM TMPHLDG_EOY  
				WHERE DPHMCD_DPAM_ID  = DPAM_ID 
				) 
 
  end  
  
if @pa_action = 'SEBI3'     -- accounts with credit balance but no transactions during the year
  begin 


--DROP TABLE TMPHLDG3
--CREATE TABLE #TMPHLDG3     
--(    
--[DPHMCD_DPM_ID] [NUMERIC](18, 0) NOT NULL,    
--[DPHMCD_DPAM_ID] [NUMERIC](10, 0) NOT NULL,    
--[DPHMCD_ISIN] [VARCHAR](20) NOT NULL,    
--[DPHMCD_CURR_QTY] [NUMERIC](18, 3) NULL,    
--[DPHMCD_FREE_QTY] [NUMERIC](18, 3) NULL,    
--[DPHMCD_FREEZE_QTY] [NUMERIC](18, 3) NULL,    
--[DPHMCD_PLEDGE_QTY] [NUMERIC](18, 3) NULL,    
--[DPHMCD_DEMAT_PND_VER_QTY] [NUMERIC](18, 3) NULL,    
--[DPHMCD_REMAT_PND_CONF_QTY] [NUMERIC](18, 3) NULL,    
--[DPHMCD_DEMAT_PND_CONF_QTY] [NUMERIC](18, 3) NULL,    
--[DPHMCD_SAFE_KEEPING_QTY] [NUMERIC](18, 3) NULL,    
--[DPHMCD_LOCKIN_QTY] [NUMERIC](18, 3) NULL,    
--[DPHMCD_ELIMINATION_QTY] [NUMERIC](18, 3) NULL,    
--[DPHMCD_EARMARK_QTY] [NUMERIC](18, 3) NULL,    
--[DPHMCD_AVAIL_LEND_QTY] [NUMERIC](18, 3) NULL,    
--[DPHMCD_LEND_QTY] [NUMERIC](18, 3) NULL,    
--[DPHMCD_BORROW_QTY] [NUMERIC](18, 3) NULL,    
--[DPHMCD_HOLDING_DT] DATETIME    
--)      

--INSERT INTO #TMPHLDG3
--EXEC  [PR_GET_HOLDING_FIX_LATEST]   3,'MAR 31 2015','MAR 31 2015','0','9999999999999999',''    
--SELECT * INTO  TMPHLDG3 FROM  #TMPHLDG3  



SELECT  
DPAM_SBA_NO +'|'    
+CONVERT(VARCHAR(11),'MAR 31 2016',112) +'|'    
+'0' +'|'    
+'' +'|'+'' +'|'+'' +'|'++'|'+CONVERT(VARCHAR,'')+'|'
+''    
+'|'+ISNULL('','')--MKTRXD    
+'|'+CONVERT(VARCHAR,ABS(CONVERT(NUMERIC(18,3),0)))--1000    
+'|'+CONVERT(VARCHAR,'')  
+'|'++'|'+ CONVERT(VARCHAR,ABS(CONVERT(NUMERIC(18,2),0)))AS VALUE
FROM DP_ACCT_MSTR 
WHERE  DPAM_STAM_CD ='ACTIVE' AND NOT EXISTS (SELECT 1 
				  FROM CDSL_HOLDING_DTLS 
				WHERE CDSHM_BEN_ACCT_NO = DPAM_SBA_NO
				AND CDSHM_TRAS_DT BETWEEN 'APR 01 2015' AND 'MAR 31 2016'
)
AND   EXISTS (SELECT 1 
				  FROM TMPHLDG
				WHERE DPHMCD_DPAM_ID  = DPAM_ID 
				) 




  end      

IF @PA_ACTION = 'CXPTRX'    -- client having corr add and perm add are different
  BEGIN     
  
   create table #obCXP(ob_cdshm_dpm_id numeric,ob_cdshm_dpam_id numeric,ob_cdshm_isin varchar(100),ob numeric(18,3))
  if @pa_boid <>'' 
  insert into #obCXP
  exec [pr_get_ob_fix] 3,@pa_from_date,@pa_to_date,@pa_boid,@pa_boid,''
  if @pa_boid ='' 
  insert into #obCXP
  exec [pr_get_ob_fix] 3,@pa_from_date,@pa_to_date,'0','9999999999999999',''
  
   
     
      
   select identity(numeric,1,1) id,cdshm_dpam_id ,cdshm_isin , convert(numeric(18,3),cdshm_qty) cdshm_qty, ISNULL(convert(numeric(18,3),ob),0) ob
    ,cdshm_tras_dt,  cdshm_ben_acct_no +'|'    
   +CONVERT(varchar(11),cdshm_tras_dt,112) +'|'    
   +cdshm_trans_no +'|'    
   +cdshm_isin +'|'+isin_name +'|'+CDSHM_TRATM_DESC +'|'++'|'+convert(varchar,'####')+'|'+case when CDSHM_QTY > 0 then 'C' else 'D' end     
   +'|'+isnull(cdshm_internal_trastm,'')--MKTRXD    
   +'|'+convert(varchar,abs(convert(numeric(18,3),cdshm_qty)))--1000    
   +'|'+convert(varchar,'$$$$')  
   +'|'++'|'+ convert(varchar,abs(convert(numeric(18,2),cdshm_charge)))as value--11   
   , CDSHM_TRATM_CD
   into #tempdataobCXP from cdsl_holding_dtls with(nolock) left outer join #obCXP 
   on CDSHM_DPAM_ID = ob_cdshm_dpam_id and CDSHM_ISIN = ob_cdshm_isin ,ISIN_MSTR with(nolock)
   ,#ACCOUNT_PROPERTIES_ECN where cdshm_ben_acct_no like  @pa_boid + '%' and cdshm_isin like @pa_isin + '%'    
   and ISIN_CD = cdshm_isin    
   and ACCP_CLISBA_ID=CDSHM_DPAM_ID
   and CDSHM_TRATM_DESC is not null    
   and CDSHM_TRAS_DT between @pa_from_date and @pa_to_date   
    and exists(select 1 from #TMP_CLIENT_CHARGES_CDSL where CLIC_DPAM_ID = CDSHM_DPAM_ID  and CLIC_TRANS_DT between @pa_from_date and @pa_to_date )  
    and CDSHM_TRATM_CD in  ('2246','2277','2201','3102','2270','2220','2205')    
    and not exists (select client_code from angelownaccount where client_code=CDSHM_BEN_ACCT_NO)
    order by CDSHM_DPAM_ID ,CDSHM_TRAS_DT, CDSHM_ISIN,case when CDSHM_QTY > 0 then 'C' else 'D' end
    
    
    
    
    select *,ob+ isnull((select SUM( cdshm_qty )  
    from #tempdataobCXP t2 where t1.CDSHM_ISIN= t2.CDSHM_ISIN and t1.CDSHM_DPAM_ID = t2.CDSHM_DPAM_ID 
    and t2.id<=t1.id  and t2.CDSHM_TRATM_CD <>'2201'
    ),0) closingbalance   into #tempfinalCxp from #tempdataobCXP t1 
    
    select --*,closingbalance-cdshm_qty openingbalance , 
    replace(replace(value,'$$$$',closingbalance),'####',closingbalance-case when CDSHM_TRATM_CD ='2201' then 0 else cdshm_qty end) as value,ID into #dtmpCxp
    from #tempfinalCxp  order by id 
     


select pc1.boid into #CXPTEMP from dps8_pc1 pc1 left outer join dps8_pc12 pc12 on pc1.BOId = pc12.BOId 
where pc1.PinCode<>ISNULL(pc12.PinCode,pc1.PinCode)

	 truncate table FILEGEN_FORANGELID_TRX_MIMANSA

     INSERT INTO FILEGEN_FORANGELID_TRX_MIMANSA

    Select  citrus_usr.FN_SPLITVAL_BY(value,1,'|') CLIENT_CODE,
    citrus_usr.FN_SPLITVAL_BY(value,2,'|') TRXN_DATE,
    citrus_usr.FN_SPLITVAL_BY(value,3,'|') TRXN_NO,
    citrus_usr.FN_SPLITVAL_BY(value,4,'|') ISIN_CD,
    citrus_usr.FN_SPLITVAL_BY(value,5,'|') ISIN_NAME,
    citrus_usr.FN_SPLITVAL_BY(value,6,'|') DESCRIPTION,
    citrus_usr.FN_SPLITVAL_BY(value,7,'|') SETTLEMENT_NO,
    citrus_usr.FN_SPLITVAL_BY(value,8,'|') OPENING_BALANCE,
    citrus_usr.FN_SPLITVAL_BY(value,9,'|') CREDIT_DEBIT,
    citrus_usr.FN_SPLITVAL_BY(value,10,'|') TRANSACTION_TYPE,
    citrus_usr.FN_SPLITVAL_BY(value,11,'|') FIELD10,    
    citrus_usr.FN_SPLITVAL_BY(value,12,'|') CLOSING_BALANCE,
    citrus_usr.FN_SPLITVAL_BY(value,13,'|') RATE,
    citrus_usr.FN_SPLITVAL_BY(value,14,'|') CHARGES
     from #dtmpCxp 
     where exists (Select boid from #CXPTEMP where boid=citrus_usr.FN_SPLITVAL_BY(value,1,'|'))
     order by id
    --SELECT *,OB+(SELECT SUM(CDSHM_QTY) FROM #TEMPDATA T2 WHERE T1.CDSHM_ISIN= T2.CDSHM_ISIN AND T1.CDSHM_DPAM_ID = T2.CDSHM_DPAM_ID 
    --AND T2.ID<=T1.ID
    --)  RUNNINGBALANCE , REPLACE(REPLACE(VALUE,'$$$$',CONVERT(VARCHAR,OB+(SELECT SUM(CDSHM_QTY) FROM #TEMPDATA T2 WHERE T1.CDSHM_ISIN= T2.CDSHM_ISIN AND T1.CDSHM_DPAM_ID = T2.CDSHM_DPAM_ID 
    --AND T2.ID<=T1.ID
    --))),'####',CONVERT(VARCHAR,OB+(SELECT SUM(CDSHM_QTY) FROM #TEMPDATA T2 WHERE T1.CDSHM_ISIN= T2.CDSHM_ISIN AND T1.CDSHM_DPAM_ID = T2.CDSHM_DPAM_ID 
    --AND T2.ID<=T1.ID
    --)-CDSHM_QTY)) VALUE FROM #TEMPDATA T1     
       
       
      
  END          
    
END

GO
