-- Object: TABLE citrus_usr.TMP_DPMPLEDGE_CDSL
-- Server: 10.253.78.187 | DB: DMAT
--------------------------------------------------

CREATE TABLE [citrus_usr].[TMP_DPMPLEDGE_CDSL]
(
    [TMPDPMPLDG_PledgeType] CHAR(1) NULL,
    [TMPDPMPLDG_PledgeSubType] CHAR(1) NULL,
    [TMPDPMPLDG_Seq_No] VARCHAR(10) NULL,
    [TMPDPMPLDG_PledgorBOID] VARCHAR(16) NULL,
    [TMPDPMPLDG_PledgeeBOID] VARCHAR(16) NULL,
    [TMPDPMPLDG_ISIN] VARCHAR(12) NULL,
    [TMPDPMPLDG_QTY] VARCHAR(50) NULL,
    [TMPDPMPLDG_PLEDGE_VAL] VARCHAR(50) NULL,
    [TMPDPMPLDG_SETUP_DATE] VARCHAR(50) NULL,
    [TMPDPMPLDG_ACCEPT_DATE] VARCHAR(50) NULL,
    [TMPDPMPLDG_EXPIRY_DATE] VARCHAR(50) NULL,
    [TMPDPMPLDG_LOCKIN_ID] VARCHAR(50) NULL,
    [TMPDPMPLDG_AGREEMENTNO] VARCHAR(20) NULL,
    [TMPDPMPLDG_PLEDGOR_INTREFNO] VARCHAR(20) NULL,
    [TMPDPMPLDG_PLEDGEE_INTREFNO] VARCHAR(20) NULL,
    [TMPDPMPLDG_PLEDGE_RMKS] VARCHAR(50) NULL,
    [TMPDPMPLDG_PLDUNPLD_COUNTER] VARCHAR(10) NULL,
    [TMPDPMPLDG_UNPLDPARTQTY] VARCHAR(50) NULL,
    [TMPDPMPLDG_UNPLD_REQUESTDT] VARCHAR(50) NULL,
    [TMPDPMPLDG_UNPLD_INTREFNO] VARCHAR(50) NULL,
    [TMPDPMPLDG_UNPLD_RMKS] VARCHAR(50) NULL,
    [TMPDPMPLDG_PLD_REQFORMNO] VARCHAR(50) NULL,
    [TMPDPMPLDG_ERRMSG] VARCHAR(800) NULL
);

GO
