-- Object: VIEW citrus_usr.CLIENT_WITHOUT_POA
-- Server: 10.253.78.187 | DB: DMAT
--------------------------------------------------


CREATE VIEW CLIENT_WITHOUT_POA
AS 
SELECT NISE_PARTY_CODE,T.CLIENT_CODE CDSL_CLIENT_CODE,ACTIVE_DATE AS FROM_DATE
FROM TBL_CLIENT_MASTER T WITH(NOLOCK)
LEFT OUTER JOIN 
TBL_CLIENT_POA P WITH(NOLOCK)
ON T.CLIENT_CODE=P.CLIENT_CODE AND HOLDER_INDI =1
WHERE ACTIVE_DATE >GETDATE()-15 AND STATUS ='ACTIVE'
AND MASTER_POA IS NULL

GO
