-- Object: TABLE citrus_usr.client_details_hst
-- Server: 10.253.78.187 | DB: DMAT
--------------------------------------------------

CREATE TABLE [citrus_usr].[client_details_hst]
(
    [client_id] NUMERIC(18, 0) NOT NULL,
    [branch_cd] VARCHAR(10) NULL,
    [party_code] VARCHAR(10) NOT NULL,
    [sub_broker] VARCHAR(10) NULL,
    [trader] VARCHAR(20) NULL,
    [long_name] VARCHAR(100) NULL,
    [short_name] VARCHAR(21) NOT NULL,
    [l_address1] VARCHAR(40) NOT NULL,
    [l_city] VARCHAR(40) NULL,
    [l_address2] VARCHAR(40) NULL,
    [l_state] VARCHAR(50) NULL,
    [l_address3] VARCHAR(40) NULL,
    [l_nation] VARCHAR(15) NULL,
    [l_zip] VARCHAR(25) NULL,
    [pan_gir_no] VARCHAR(50) NULL,
    [ward_no] VARCHAR(50) NULL,
    [sebi_regn_no] VARCHAR(25) NULL,
    [res_phone1] VARCHAR(25) NULL,
    [res_phone2] VARCHAR(25) NULL,
    [off_phone1] VARCHAR(25) NULL,
    [off_phone2] VARCHAR(25) NULL,
    [mobile_pager] VARCHAR(40) NULL,
    [fax] VARCHAR(25) NULL,
    [email] VARCHAR(50) NULL,
    [cl_type] VARCHAR(10) NOT NULL,
    [cl_status] VARCHAR(10) NOT NULL,
    [family] VARCHAR(10) NULL,
    [region] VARCHAR(50) NULL,
    [area] VARCHAR(10) NULL,
    [p_address1] VARCHAR(50) NULL,
    [p_city] VARCHAR(20) NULL,
    [p_address2] VARCHAR(50) NULL,
    [p_state] VARCHAR(15) NULL,
    [p_address3] VARCHAR(50) NULL,
    [p_nation] VARCHAR(15) NULL,
    [p_zip] VARCHAR(10) NULL,
    [addemailid] VARCHAR(230) NULL,
    [sex] VARCHAR(10) NULL,
    [dob] DATETIME NULL,
    [approver] VARCHAR(30) NULL,
    [interactmode] INT NULL,
    [passport_no] VARCHAR(30) NULL,
    [passport_issued_at] VARCHAR(30) NULL,
    [passport_issued_on] DATETIME NULL,
    [passport_expires_on] DATETIME NULL,
    [licence_no] VARCHAR(30) NULL,
    [licence_issued_at] VARCHAR(30) NULL,
    [licence_issued_on] DATETIME NULL,
    [licence_expires_on] DATETIME NULL,
    [rat_card_no] VARCHAR(30) NULL,
    [rat_card_issued_at] VARCHAR(30) NULL,
    [rat_card_issued_on] DATETIME NULL,
    [votersid_no] VARCHAR(30) NULL,
    [votersid_issued_at] VARCHAR(30) NULL,
    [votersid_issued_on] DATETIME NULL,
    [it_return_yr] VARCHAR(30) NULL,
    [it_return_filed_on] DATETIME NULL,
    [regr_no] VARCHAR(50) NULL,
    [regr_at] VARCHAR(50) NULL,
    [regr_on] DATETIME NULL,
    [regr_authority] VARCHAR(50) NULL,
    [client_agreement_on] DATETIME NULL,
    [dealing_with_other_tm] VARCHAR(50) NULL,
    [other_ac_no] VARCHAR(50) NULL,
    [introducer_id] VARCHAR(50) NULL,
    [introducer] VARCHAR(50) NULL,
    [introducer_relation] VARCHAR(50) NULL,
    [chk_kyc_form] INT NULL,
    [chk_corporate_deed] INT NULL,
    [chk_bank_certificate] INT NULL,
    [chk_annual_report] INT NULL,
    [chk_networth_cert] INT NULL,
    [chk_corp_dtls_recd] INT NULL,
    [sbu] VARCHAR(25) NULL,
    [modifidedby] VARCHAR(25) NULL,
    [modifiedon] DATETIME NULL,
    [mapin_id] VARCHAR(12) NULL,
    [ucc_code] VARCHAR(12) NULL,
    [fm_code] VARCHAR(16) NULL,
    [micr_no] VARCHAR(10) NULL,
    [director_name] VARCHAR(100) NULL,
    [paylocation] VARCHAR(20) NULL,
    [cd_created_dt] DATETIME NOT NULL,
    [cd_lst_upd_dt] DATETIME NOT NULL,
    [cd_changed] CHAR(2) NOT NULL,
    [migrate_yn] INT NULL,
    [ucc_no] NUMERIC(18, 0) NOT NULL
);

GO
