-- Object: TABLE citrus_usr.WF_ACTIONS
-- Server: 10.253.78.187 | DB: DMAT
--------------------------------------------------

CREATE TABLE [citrus_usr].[WF_ACTIONS]
(
    [WFA_ID] NUMERIC(10, 0) NOT NULL,
    [WFA_ACT_ID] NUMERIC(10, 0) NOT NULL,
    [WFA_ACT_CD] VARCHAR(20) NOT NULL,
    [WFA_WFPM_ID] NUMERIC(10, 0) NOT NULL,
    [WFA_START] INT NULL,
    [WFA_END] INT NULL,
    [WFA_DESC] VARCHAR(200) NULL,
    [WFA_RMKS] VARCHAR(250) NULL,
    [WFA_CREATED_BY] VARCHAR(25) NOT NULL,
    [WFA_CREATED_DT] DATETIME NOT NULL,
    [WFA_LST_UPD_BY] VARCHAR(25) NOT NULL,
    [WFA_LST_UPD_DT] DATETIME NOT NULL,
    [WFA_DELETED_IND] SMALLINT NOT NULL
);

GO
