-- Object: TABLE citrus_usr.ACCDOCM_MAK
-- Server: 10.253.78.187 | DB: DMAT
--------------------------------------------------

CREATE TABLE [citrus_usr].[ACCDOCM_MAK]
(
    [ACCDOCM_ID] NUMERIC(10, 0) NOT NULL,
    [ACCDOCM_DOC_ID] NUMERIC(10, 0) NOT NULL,
    [ACCDOCM_CLICM_ID] NUMERIC(10, 0) NOT NULL,
    [ACCDOCM_ENTTM_ID] NUMERIC(10, 0) NOT NULL,
    [ACCDOCM_EXCPM_ID] NUMERIC(10, 0) NOT NULL,
    [ACCDOCM_CD] VARCHAR(20) NOT NULL,
    [ACCDOCM_DESC] VARCHAR(100) NULL,
    [ACCDOCM_RMKS] VARCHAR(250) NULL,
    [ACCDOCM_MDTY] SMALLINT NOT NULL,
    [ACCDOCM_ACCT_TYPE] VARCHAR(20) NOT NULL,
    [ACCDOCM_CREATED_BY] VARCHAR(25) NOT NULL,
    [ACCDOCM_CREATED_DT] DATETIME NOT NULL,
    [ACCDOCM_LST_UPD_BY] VARCHAR(25) NOT NULL,
    [ACCDOCM_LST_UPD_DT] DATETIME NOT NULL,
    [ACCDOCM_DELETED_IND] SMALLINT NOT NULL
);

GO
