-- Object: PROCEDURE citrus_usr.PR_INS_UPD_INSTA_BOID
-- Server: 10.253.78.187 | DB: DMAT
--------------------------------------------------


Create PROCEDURE [PR_INS_UPD_INSTA_BOID]
(@PA_LOGIN_NAME VARCHAR(30)
)
AS
BEGIN
INSERT INTO INSTA_BOID_MSTR
(
 INSTA_BOID 
,INSTA_FILEDATE 
,INSTA_PAN_GIR_NO 
,INSTA_FILLER1 
,INSTA_CREATED_BY 
,INSTA_CREATED_DT 
,INSTA_CREATED_LST_UPD_BY 
,INSTA_CREATED_LST_UPD_DT 
,INSTA_DELETED_IND 
)
SELECT  TMP_INSTA_BOID 
,TMP_INSTA_FILEDATE 
,TMP_INSTA_PAN_GIR_NO 
,TMP_INSTA_FILLER1
,@PA_LOGIN_NAME
,GETDATE()
,@PA_LOGIN_NAME
,GETDATE()
,1
 FROM TMP_INSTA_BOID_MSTR
WHERE NOT EXISTS (SELECT INSTA_BOID FROM INSTA_BOID_MSTR WHERE INSTA_FILEDATE=TMP_INSTA_FILEDATE
AND INSTA_DELETED_IND=1)

END

GO
