-- Object: TABLE citrus_usr.STATUS_MSTR_MAK
-- Server: 10.253.78.187 | DB: DMAT
--------------------------------------------------

CREATE TABLE [citrus_usr].[STATUS_MSTR_MAK]
(
    [STAM_ID] NUMERIC(10, 0) NOT NULL,
    [STAM_CD] VARCHAR(20) NOT NULL,
    [STAM_DESC] VARCHAR(100) NULL,
    [STAM_RMKS] VARCHAR(250) NULL,
    [STAM_CREATED_BY] VARCHAR(25) NOT NULL,
    [STAM_CREATED_DT] DATETIME NOT NULL,
    [STAM_LST_UPD_BY] VARCHAR(25) NOT NULL,
    [STAM_LST_UPD_DT] DATETIME NOT NULL,
    [STAM_DELETED_IND] SMALLINT NOT NULL
);

GO
