-- Object: VIEW citrus_usr.VW_FILESTATUS_TRX
-- Server: 10.253.78.187 | DB: DMAT
--------------------------------------------------

CREATE view VW_FILESTATUS_TRX 
as
SELECT TOP 1  TASK_NAME,  CASE WHEN STATUS='RUNNING' THEN 'Y' ELSE 'N' END FILERUNNINGSTATUS,CASE WHEN STATUS='RUNNING' THEN '' ELSE TASK_END_DATE END    
TASK_END_DATE,TASK_ID  FROM FILETASK  WHERE TASK_NAME LIKE 'DPM DP57%'  ORDER BY 3 DESC

GO
