-- Object: PROCEDURE citrus_usr.pr_relation_data_new1
-- Server: 10.253.78.187 | DB: DMAT
--------------------------------------------------

--EXEC pr_relation_data_new1

CREATE      proc [citrus_usr].[pr_relation_data_new1]
as 
begin 
DROP TABLE REL_DATA_NEW1

SELECT ENTM_ID , ENTM_NAME1 , ENTM_SHORT_NAME INTO #ENTITY_MSTR_RE FROM ENTITY_MSTR WHERE ENTM_ENTTM_CD = 'RE'
SELECT ENTM_ID , ENTM_NAME1 , ENTM_SHORT_NAME INTO #ENTITY_MSTR_AR FROM ENTITY_MSTR WHERE ENTM_ENTTM_CD = 'AR'
SELECT ENTM_ID , ENTM_NAME1 , ENTM_SHORT_NAME INTO #ENTITY_MSTR_BR FROM ENTITY_MSTR WHERE ENTM_ENTTM_CD = 'BR'
SELECT ENTM_ID , ENTM_NAME1 , ENTM_SHORT_NAME INTO #ENTITY_MSTR_SB FROM ENTITY_MSTR WHERE ENTM_ENTTM_CD = 'SB'
SELECT ENTM_ID , ENTM_NAME1 , ENTM_SHORT_NAME INTO #ENTITY_MSTR_BL FROM ENTITY_MSTR WHERE ENTM_ENTTM_CD = 'BL'

select ENTR_SBA ESBA,  ENTRE.ENTM_SHORT_NAME RECODE, ENTRE.ENTM_NAME1  RENAME, ENTAR.ENTM_SHORT_NAME ARCODE,ENTAR.ENTM_NAME1 ARNAME ,
 ENTBR.ENTM_SHORT_NAME BRCODE, ENTBR.ENTM_NAME1 BRNAME, ENTSB.ENTM_SHORT_NAME SBCODE , ENTSB.ENTM_NAME1 SBNAME ,
 ENTBL.ENTM_SHORT_NAME BLCODE, ENTBL.ENTM_NAME1 BLNAME
 INTO REL_DATA_NEW1
  from entity_relationship 
LEFT OUTER JOIN  #ENTITY_MSTR_RE ENTRE ON ENTRE.ENTM_ID = ENTR_RE 
LEFT OUTER JOIN  #ENTITY_MSTR_AR ENTAR ON ENTAR.ENTM_ID = ENTR_AR
LEFT OUTER JOIN  #ENTITY_MSTR_BR ENTBR ON ENTBR.ENTM_ID = ENTR_BR
LEFT OUTER JOIN  #ENTITY_MSTR_SB ENTSB ON ENTSB.ENTM_ID = ENTR_DUMMY4
LEFT OUTER JOIN  #ENTITY_MSTR_BL ENTBL ON ENTBL.ENTM_ID = ENTR_DUMMY5
 --WHERE ENTR_SBA = '1203320000000070'
 WHERE ENTR_DELETED_IND = 1 
 AND GETDATE () BETWEEN ENTR_FROM_DT AND ISNULL (ENTR_TO_DT , 'dEC 31 2999')
 
 
 
 DROP TABLE #ENTITY_MSTR_RE
  DROP TABLE #ENTITY_MSTR_AR
   DROP TABLE #ENTITY_MSTR_BR
    DROP TABLE #ENTITY_MSTR_SB
    DROP TABLE #ENTITY_MSTR_BL
    
    END

GO
