-- Object: PROCEDURE citrus_usr.pr_DIYD_count_for_checker
-- Server: 10.253.78.187 | DB: DMAT
--------------------------------------------------

--EXEC PR_DIYD_COUNT_FOR_CHECKER 'MAY 11 2020', 'MAY 11 2020','HO'
CREATE   PROC [citrus_usr].[pr_DIYD_count_for_checker](@PA_FROM_DT DATETIME, @PA_TO_DT DATETIME    
,@PA_LOGIN_NAME VARCHAR(100)    
)          
AS          
BEGIN 
SELECT COUNT(1) [COUNT] , 'PENDING FOR CHECKER' REMARKS FROM DPTDC_MAK , DP_ACCT_MSTR
WHERE DPTDC_REQUEST_DT =  @PA_FROM_DT --BETWEEN @PA_FROM_DT AND @PA_TO_DT
AND DPTDC_DELETED_IND IN ( '0','-1') AND DPAM_ID = DPTDC_DPAM_ID 
--AND DPTDC_SLIP_NO LIKE 'E%' AND 
and DPAM_SBA_NO = DPTDC_CREATED_BY 
and isnull(dptdc_res_cd ,'') =  ''

UNION 
SELECT COUNT(1)[COUNT] , 'READY FOR BATCH' REMARKS  FROM DP_TRX_DTLS_CDSL  WITH (NOLOCK), DP_ACCT_MSTR
 WHERE DPTDC_REQUEST_DT =@PA_FROM_DT
AND DPTDC_DELETED_IND IN ( 1)AND DPAM_ID = DPTDC_DPAM_ID 
and DPAM_SBA_NO = DPTDC_CREATED_BY 
--AND DPTDC_SLIP_NO LIKE 'E%'
AND DPTDC_BATCH_NO IS NULL 
and isnull (DPTDC_STATUS ,'') = 'P'
 
 UNION 
SELECT COUNT(DPTDC_ID)[COUNT] , 'RECORDS EXPORTED TODAY' REMARKS  FROM DP_TRX_DTLS_CDSL  WITH (NOLOCK), DP_ACCT_MSTR
 WHERE DPTDC_REQUEST_DT =@PA_FROM_DT
AND DPTDC_DELETED_IND IN ( 1)AND DPAM_ID = DPTDC_DPAM_ID 
and DPAM_SBA_NO = DPTDC_CREATED_BY 
--AND DPTDC_SLIP_NO LIKE 'E%'
AND DPTDC_BATCH_NO IS NOT  NULL

 UNION 
SELECT COUNT(DPTDC_ID)[COUNT] , 'RESPONSE NOT RECEIVED TODAY' REMARKS  FROM DP_TRX_DTLS_CDSL  WITH (NOLOCK), DP_ACCT_MSTR
 WHERE DPTDC_REQUEST_DT =@PA_FROM_DT
AND DPTDC_DELETED_IND IN ( 1)AND DPAM_ID = DPTDC_DPAM_ID 
and DPAM_SBA_NO = DPTDC_CREATED_BY 
--AND DPTDC_SLIP_NO LIKE 'E%'
AND DPTDC_BATCH_NO IS NOT  NULL
AND DPTDC_STATUS = 'P'
and isnull(DPTDC_TRANS_NO ,'0') =  '0'

END

GO
