-- Object: FUNCTION citrus_usr.FN_POATYPE
-- Server: 10.253.78.187 | DB: DMAT
--------------------------------------------------


CREATE FUNCTION CITRUS_USR.FN_POATYPE(@pA_BOID VARCHAR(16),@PA_MASTER VARCHAR(16))
RETURNS VARCHAR(100) 
AS
BEGIN 
RETURN(
SELECT TOP 1 DPPD_POA_TYPE FROM DP_POA_DTLS , DP_ACCT_MSTR WHERE DPPD_DPAM_ID = DPAM_ID AND DPAM_SBA_NO = @pA_BOID
AND dppd_master_id  = @PA_MASTER)

END

GO
