-- Object: FUNCTION citrus_usr.FN_PREPOSTOFF
-- Server: 10.253.78.187 | DB: DMAT
--------------------------------------------------


CREATE FUNCTION [citrus_usr].[FN_PREPOSTOFF](@PA_SLIP_NO VARCHAR(25))
RETURNS VARCHAR(25)
AS
BEGIN
DECLARE @L_SLIPNO CHAR(1)
--SELECT @L_SLIPNO='D'
SELECT @L_SLIPNO=DPTDC_STATUS 
FROM EDIS_PRE_DPTDC_MAK WITH(NOLOCK) WHERE DPTDC_TRANS_NO=@PA_SLIP_NO AND ISNULL(DPTDC_TRANS_NO,'0')<>'0'
RETURN @L_SLIPNO
END

GO
