-- Object: TABLE citrus_usr.bill_reprot_LOG
-- Server: 10.253.78.187 | DB: DMAT
--------------------------------------------------

CREATE TABLE [citrus_usr].[bill_reprot_LOG]
(
    [RUN_DATE] DATETIME NULL,
    [DPTYPE] VARCHAR(4) NULL,
    [EXCSMID] INT NULL,
    [FROMDATE] DATETIME NULL,
    [TODATE] DATETIME NULL,
    [BULK_PRINTFLAG] CHAR(1) NULL,
    [STOPBILLCLIENTS_FLAG] CHAR(1) NULL,
    [FROMACCID] VARCHAR(16) NULL,
    [TOACCID] VARCHAR(16) NULL,
    [GROUP_CD] VARCHAR(10) NULL,
    [TRANSCLIENTSONLY] CHAR(1) NULL,
    [HLDG_YN] CHAR(1) NULL,
    [PROFILE] VARCHAR(100) NULL,
    [LOGIN_PR_ENTM_ID] NUMERIC(18, 0) NULL,
    [LOGIN_ENTM_CD_CHAIN] VARCHAR(8000) NULL,
    [OUTPUT] VARCHAR(8000) NULL
);

GO
