-- Object: PROCEDURE citrus_usr.OS_RECOVERY_THURSDAY
-- Server: 10.253.78.187 | DB: DMAT
--------------------------------------------------





CREATE PROCEDURE [citrus_usr].[OS_RECOVERY_THURSDAY]
AS
BEGIN

SELECT * INTO #OS FROM  Vw_Acc_Curr_Bal WHERE Actual_amount>0

CREATE INDEX idx_client_code
ON #OS (CLIENT_CODE)


SELECT A.*,STATUS,TEMPLATE_cODE INTO #OS1 FROM #OS A
LEFT OUTER JOIN
 TBL_CLIENT_MASTER B
ON A.CLIENT_CODE=B.CLIENT_CODE

CREATE INDEX idx_party_code
ON #OS1 (PARTY_CODE)



SELECT A.*,sum(Net_Ledger) Net_Ledger,SUM(NET_AVAILABLE)AS NET_AVAILABLE FROM #OS1 A
LEFT OUTER JOIN
[CSOKYC-6].GENERAL.DBO.tbl_RMS_Collection_Cli B
ON A.PARTY_CODE=B.PARTY_cODE WHERE NET_LEDGER>0 
GROUP BY A.PARTY_CODE,CLIENT_CODE,Actual_amount,Accrual_bal,Branch_Code,STATUS,TEMPLATE_cODE

END

GO
