-- Object: VIEW citrus_usr.Vw_Template_Charges_BKP
-- Server: 10.253.78.187 | DB: DMAT
--------------------------------------------------

CREATE VIEW Vw_Template_Charges_BKP

AS

SELECT BROM_DESC [TEMPLATE_CODE],
CHAM_SLAB_no [CHARGES_CODE],
CHAM_SLAB_NAME [SLAB_CODE],
CHAM_CHARGE_MINVAL [MINIMUM_CHARGES],
CHAM_CHARGE_VALUE [MAXIMUM_CHARGES],
0 [MAILING_CHARGES]
FROM BROKERAGE_MSTR WITH(NOLOCK)
,PROFILE_CHARGES WITH(NOLOCK)
,CHARGE_MSTR  WITH(NOLOCK)
WHERE BROM_ID = PROC_PROFILE_ID 
AND PROC_SLAB_NO = CHAM_SLAB_NO 
AND BROM_DELETED_IND =1 
AND [PROC_DELETED_IND ] = 1
AND [CHAM_DELETED_IND ] = 1

GO
