-- Object: TABLE citrus_usr.INTERDP_STATUS_MSTR
-- Server: 10.253.78.187 | DB: DMAT
--------------------------------------------------

CREATE TABLE [citrus_usr].[INTERDP_STATUS_MSTR]
(
    [IDS_BOID] VARCHAR(16) NULL,
    [IDS_ISIN_ALPHA] VARCHAR(12) NULL,
    [IDS_ISIN_SHORT_NM] VARCHAR(20) NULL,
    [IDS_NSDL_CMBP_DPID] VARCHAR(8) NULL,
    [IDS_NSDL_SETT_ID] VARCHAR(16) NULL,
    [IDS_NSDL_CLTID] VARCHAR(8) NULL,
    [IDS_SENDER_TRX_REFNO] VARCHAR(16) NULL,
    [IDS_QTY] NUMERIC(16, 3) NULL,
    [IDS_BS_FLG] VARCHAR(4) NULL,
    [IDS_EXEC_DT] DATETIME NULL,
    [IDS_TRX_STAT_CD] VARCHAR(2) NULL,
    [IDS_INT_REF_NO] VARCHAR(16) NULL,
    [IDS_ERR_CD1] NUMERIC(18, 0) NULL,
    [IDS_ERR_CD2] NUMERIC(18, 0) NULL,
    [IDS_ERR_CD3] NUMERIC(18, 0) NULL,
    [IDS_ERR_CD4] NUMERIC(18, 0) NULL,
    [IDS_ERR_DESC1] VARCHAR(100) NULL,
    [IDS_ERR_DESC2] VARCHAR(100) NULL,
    [IDS_ERR_DESC3] VARCHAR(100) NULL,
    [IDS_ERR_DESC4] VARCHAR(100) NULL,
    [IDS_TRX_DT] DATETIME NULL,
    [IDS_LST_MOD_DT] VARCHAR(25) NULL,
    [IDS_DPAM_ID] NUMERIC(18, 0) NULL,
    [IDS_DPM_ID] NUMERIC(18, 0) NULL,
    [IDS_CHARGE] NUMERIC(18, 0) NULL,
    [IDS_DP_CHARGE] NUMERIC(18, 0) NULL,
    [IDS_CTR_SETTL_ID] VARCHAR(13) NULL
);

GO
