-- Object: TABLE citrus_usr.TPIN_RESPONSE_MSTR
-- Server: 10.253.78.187 | DB: DMAT
--------------------------------------------------

CREATE TABLE [citrus_usr].[TPIN_RESPONSE_MSTR]
(
    [TPM_BATCHNO] VARCHAR(20) NULL,
    [TPM_BOID] VARCHAR(16) NULL,
    [TPM_SF] CHAR(1) NULL,
    [TPM_ERR] VARCHAR(8000) NULL,
    [TPM_CREATED_BY] VARCHAR(200) NULL,
    [TPM_CREATED_DT] DATETIME NULL,
    [TPM_LST_UPD_BY] VARCHAR(200) NULL,
    [TPM_LST_UPD_DT] DATETIME NULL,
    [TPM_DELETED_IND] SMALLINT NULL
);

GO
