-- Object: TABLE citrus_usr.CLICM_HST
-- Server: 10.253.78.187 | DB: DMAT
--------------------------------------------------

CREATE TABLE [citrus_usr].[CLICM_HST]
(
    [CLICM_ID] NUMERIC(10, 0) NOT NULL,
    [CLICM_CD] VARCHAR(20) NOT NULL,
    [CLICM_DESC] VARCHAR(200) NULL,
    [CLICM_RMKS] VARCHAR(250) NULL,
    [CLICM_CREATED_BY] VARCHAR(25) NOT NULL,
    [CLICM_CREATED_DT] DATETIME NOT NULL,
    [CLICM_LST_UPD_BY] VARCHAR(25) NOT NULL,
    [CLICM_LST_UPD_DT] DATETIME NOT NULL,
    [CLICM_DELETED_IND] SMALLINT NOT NULL,
    [CLICM_ACTION] VARCHAR(20) NOT NULL,
    [clicm_bit] INT NOT NULL
);

GO
