-- Object: TABLE citrus_usr.LOGGED_MSTR
-- Server: 10.253.78.187 | DB: DMAT
--------------------------------------------------

CREATE TABLE [citrus_usr].[LOGGED_MSTR]
(
    [LOGG_NAME] VARCHAR(50) NULL,
    [LOGG_IP] VARCHAR(50) NULL,
    [LOGG_SERVERIP] VARCHAR(50) NULL,
    [LOGG_CURRENTCNT] NUMERIC(18, 0) NULL,
    [LOGG_TOTALCNT] NUMERIC(18, 0) NULL,
    [LOGG_DT] DATETIME NULL,
    [LOGG_CREATED_BY] VARCHAR(50) NULL,
    [LOGG_CREATED_DT] DATETIME NULL,
    [LOGG_LST_UPD_BY] VARCHAR(50) NULL,
    [LOGG_LST_UPD_DT] DATETIME NULL,
    [LOGG_DELETED_IND] INT NULL,
    [LOGG_PC_NAME] VARCHAR(100) NULL
);

GO
