-- Object: TABLE citrus_usr.DP_HLDG_MSTR_NSDL
-- Server: 10.253.78.187 | DB: DMAT
--------------------------------------------------

CREATE TABLE [citrus_usr].[DP_HLDG_MSTR_NSDL]
(
    [DPDHM_HOLDING_DT] DATETIME NOT NULL,
    [DPDHM_QTY] NUMERIC(18, 3) NULL,
    [DPDHM_ISIN] VARCHAR(20) NOT NULL,
    [DPDHM_DPM_ID] NUMERIC(10, 0) NULL,
    [DPDHM_DPAM_ID] NUMERIC(10, 0) NOT NULL,
    [DPDHM_BENF_CAT] VARCHAR(20) NOT NULL,
    [DPDHM_BENF_ACCT_TYP] VARCHAR(20) NOT NULL,
    [DPDHM_SETT_TYPE] VARCHAR(25) NULL,
    [DPDHM_SETT_NO] VARCHAR(25) NULL,
    [DPDHM_CC_ID] VARCHAR(8) NULL,
    [DPDHM_BLK_LOCK_FLG] CHAR(1) NULL,
    [DPDHM_BLK_LOCK_CD] CHAR(2) NULL,
    [DPDHM_REL_DT] DATETIME NULL,
    [DPDHM_CREATED_BY] VARCHAR(20) NOT NULL,
    [DPDHM_CREATED_DT] DATETIME NOT NULL,
    [DPDHM_LST_UPD_BY] VARCHAR(20) NOT NULL,
    [DPDHM_LST_UPD_DT] DATETIME NOT NULL,
    [DPDHM_DELETED_IND ] SMALLINT NOT NULL
);

GO
