-- Object: VIEW citrus_usr.BBOCODE_CHANGE
-- Server: 10.253.78.187 | DB: DMAT
--------------------------------------------------


CREATE VIEW [citrus_usr].[BBOCODE_CHANGE]

AS 

SELECT OLD_KYC_CODE,NEW_KYC_CODE,OLD_BRANCHCODE,NEW_BRANCHCODE,ENTRYDATE DATE FROM INTRANET.TESTDB.DBO.V_KYC_OLDNEW_SHIFTING WITH(NOLOCK) WHERE 
ENTRYDATE >=convert(varchar(11),GETDATE()-5,120)

GO
