-- Object: TABLE citrus_usr.CLIA_HST
-- Server: 10.253.78.187 | DB: DMAT
--------------------------------------------------

CREATE TABLE [citrus_usr].[CLIA_HST]
(
    [CLIA_CRN_NO] NUMERIC(10, 0) NOT NULL,
    [CLIA_ACCT_NO] VARCHAR(25) NOT NULL,
    [CLIA_ACCESS1] NUMERIC(10, 0) NOT NULL,
    [CLIA_STATUS1] NUMERIC(10, 0) NOT NULL,
    [CLIA_ACCESS2] NUMERIC(10, 0) NOT NULL,
    [CLIA_STATUS2] NUMERIC(10, 0) NOT NULL,
    [CLIA_CREATED_BY] VARCHAR(25) NOT NULL,
    [CLIA_CREATED_DT] DATETIME NOT NULL,
    [CLIA_LST_UPD_BY] VARCHAR(25) NOT NULL,
    [CLIA_LST_UPD_DT] DATETIME NOT NULL,
    [CLIA_DELETED_IND] SMALLINT NOT NULL,
    [CLIA_ACTION] VARCHAR(20) NOT NULL
);

GO
