-- Object: TABLE citrus_usr.ONLINE_DPTRX_BEN_MSTR
-- Server: 10.253.78.187 | DB: DMAT
--------------------------------------------------

CREATE TABLE [citrus_usr].[ONLINE_DPTRX_BEN_MSTR]
(
    [ONL_TRX_BOID] VARCHAR(16) NULL,
    [ONL_TRX_BONAME] VARCHAR(100) NULL,
    [ONL_TRXFEREE_DPID] VARCHAR(8) NULL,
    [ONL_CMBPID] VARCHAR(8) NULL,
    [ONL_TRXFEREE_DPNAME] VARCHAR(100) NULL,
    [ONL_TRXFEREE_BOID] VARCHAR(16) NULL,
    [ONL_TRXFEREE_BONAME] VARCHAR(100) NULL,
    [ONL_OTP] VARCHAR(5) NULL,
    [ONL_CREATED_BY] VARCHAR(50) NULL,
    [ONL_CREATED_DT] DATETIME NULL,
    [ONL_LST_UPD_BY] VARCHAR(50) NULL,
    [ONL_LST_UPD_DT] DATETIME NULL,
    [ONL_DELETED_IND] SMALLINT NULL,
    [REQID] BIGINT IDENTITY(1,1) NOT NULL,
    [ONL_BEN_Mobile_email] VARCHAR(100) NULL
);

GO
