-- Object: VIEW dbo.VW_CLIENT_MIMANSA
-- Server: 10.253.78.187 | DB: DMAT
--------------------------------------------------

CREATE VIEW VW_CLIENT_MIMANSA 
AS 
select BOID CLIENT_CODE,NISE_PARTY_CODE,FIRST_HOLD_NAME,ADDR1 FIRST_HOLD_ADDRESS1,ADDR2 FIRST_HOLD_ADDRESS2,ADDR3 FIRST_HOLD_ADDRESS3,
 CITY AS FIRST_HOLD_CITY,STATE FIRST_HOLD_STATE,PINCODE FIRST_HOLD_PINCODE,STATUS, SUB_TYPE ,TEMPLATE_CODE,
 BRANCH_CODE ,EMAIL_ADD ,FIRST_HOLD_MOBILE	 from citrus_usr.dps8_pc1 P,TBL_CLIENT_MASTER T where  BOID=CLIENT_CODE

GO
