-- Object: PROCEDURE dbo.PROC_PRODUCT_DATA_BKUP_25Nov2022
-- Server: 10.253.33.91 | DB: MTFTRADE
--------------------------------------------------



CREATE PROC [dbo].[PROC_PRODUCT_DATA_BKUP_25Nov2022](
           @SAUDA_DATE VARCHAR(11))
AS

SET NOCOUNT ON
-- EXEC PROC_PRODUCT_DATA 'Sep 18 2019'

DECLARE @PROCESSFLAG	INT,
		@PROCESS_START	DATETIME,
		@PROVPROCESSFLAG	INT
		
SELECT @PROCESS_START = GETDATE()

SELECT @PROCESSFLAG = ISNULL(COUNT(1),0) FROM TBL_MTF_LOG
WHERE FUNDING_DATE = @SAUDA_DATE

SELECT @PROVPROCESSFLAG = ISNULL(COUNT(1),0) FROM TBL_MTF_PROV_LOG
WHERE FUNDING_DATE = @SAUDA_DATE

SELECT DISTINCT PARTY_CODE INTO #PARTY FROM TBLCLIENTMARGIN 
WHERE @SAUDA_DATE BETWEEN FROM_DATE AND TO_DATE 

CREATE CLUSTERED INDEX PARTY ON #PARTY
(
	PARTY_CODE
)

IF @PROCESSFLAG=0 AND @PROVPROCESSFLAG = 0 
BEGIN
DELETE FROM TBL_PRODUCT_DATA 
WHERE SAUDA_DATE = @SAUDA_DATE
AND TRANSTYPE = 'TRNSE'

DELETE FROM TBL_PRODUCT_DATA 
WHERE SAUDA_DATE = @SAUDA_DATE
AND TRANSTYPE = 'TRBSE'



--MTF TRADES --
----DELETE TBL_MTF_ORDER WHERE SAUDA_DATE BETWEEN @SAUDA_DATE AND @SAUDA_DATE + ' 23:59:59'

----INSERT INTO TBL_MTF_ORDER
----SELECT EXCHNAGE = 'NSE',SEGMENT = 'CAPITAL',SAUDA_DATE,ORDER_NO,SCRIP_CD,SERIES,'SYSTEM',IMPORTED_ON 
----FROM MSAJAG..TRADE_PRODUCT WHERE SAUDA_DATE BETWEEN @SAUDA_DATE AND @SAUDA_DATE + ' 23:59:59' And PRODUCT_CODE = 'MTF'

----INSERT INTO TBL_MTF_ORDER
----SELECT EXCHNAGE = 'BSE',SEGMENT = 'CAPITAL',SAUDA_DATE,ORDER_NO,SCRIP_CD,SERIES,'SYSTEM',IMPORTED_ON 
----FROM BSEDB..TRADE_PRODUCT WHERE SAUDA_DATE BETWEEN @SAUDA_DATE AND @SAUDA_DATE + ' 23:59:59' And PRODUCT_CODE = 'MTF'
--MTF TRADES --

--SELECT * INTO #NSE_MTF FROM MSAJAG.DBO.TBL_CONTRACT_TERMINAL_MAPPING_NSE_MTF N 
---WHERE N.FROM_DATE BETWEEN @SAUDA_DATE AND @SAUDA_DATE + ' 23:59:59'

---SELECT * INTO #BSE_MTF FROM BSEDB.DBO.TBL_CONTRACT_TERMINAL_MAPPING_BSE_MTF N  
----WHERE N.FROM_DATE BETWEEN @SAUDA_DATE AND @SAUDA_DATE + ' 23:59:59'   

SELECT SAUDA_DATE,Sett_No,Sett_Type,PARTY_CODE,PRODUCT_CODE,SCRIP_CD,SERIES,BSECODE,Sell_Buy,ISIN,QTY,MKTAMT,NETAMT,CL_RATE,PAYIN_DATE,ADJUST_DATE,TRANSTYPE,PROCESSDATE
INTO #TBL_PRODUCT_DATA FROM TBL_PRODUCT_DATA
WHERE 1 = 2 

CREATE CLUSTERED INDEX SCR ON #TBL_PRODUCT_DATA
(
	SCRIP_CD,
	SERIES
)

INSERT INTO #TBL_PRODUCT_DATA 
SELECT SAUDA_DATE = LEFT(S.SAUDA_DATE,11), S.SETT_NO, S.SETT_TYPE, S.PARTY_CODE, PRODUCT_CODE='MTF', S.SCRIP_CD, S.SERIES, BSECODE = '', SELL_BUY, 
ISIN = CONVERT(VARCHAR(12),''),
QTY=SUM(TRADEQTY),
MKTAMT=SUM(TRADEQTY*MARKETRATE),
NETAMT=SUM(CASE WHEN SELL_BUY = 1 
				THEN TRADEQTY*MARKETRATE+(TRADEQTY*NBROKAPP+NSERTAX+TURN_TAX+SEBI_TAX+INS_CHRG+OTHER_CHRG+BROKER_CHRG) 
				ELSE TRADEQTY*MARKETRATE-(TRADEQTY*NBROKAPP+NSERTAX+TURN_TAX+SEBI_TAX+INS_CHRG+OTHER_CHRG+BROKER_CHRG) 
		   END),
CL_RATE = 0,
PAYIN_DATE=SM.SEC_PAYIN,
ADJUST_DATE='DEC 31 2049 23:59',
TRANSTYPE = 'TRNSE',
PROCESSDATE=GETDATE()--,
--TRADE_NO='', Order_No=''
FROM MSAJAG.DBO.SETTLEMENT S, MSAJAG.DBO.SETT_MST SM, #PARTY P
WHERE S.SAUDA_DATE BETWEEN @SAUDA_DATE AND @SAUDA_DATE + ' 23:59:59'
AND TRADEQTY > 0 
AND AUCTIONPART NOT LIKE 'F%'
AND AUCTIONPART NOT LIKE 'A%'
AND S.SETT_NO = SM.SETT_NO	
AND S.SETT_TYPE = SM.SETT_TYPE 
AND S.SETT_TYPE IN ('N', 'W')
AND P.PARTY_CODE = S.PARTY_CODE
AND SETTFLAG NOT IN (2,3)
GROUP BY LEFT(S.SAUDA_DATE,11), S.SETT_NO, S.SETT_TYPE, S.PARTY_CODE, S.SCRIP_CD, S.SERIES, 
SELL_BUY, SEC_PAYIN 
	
		 
INSERT INTO #TBL_PRODUCT_DATA 
SELECT SAUDA_DATE = LEFT(S.SAUDA_DATE,11), S.SETT_NO, S.SETT_TYPE, S.PARTY_CODE, PRODUCT_CODE='MTF', SCRIP_CD = '', SERIES = '', BSECODE = S.SCRIP_CD, SELL_BUY, 
ISIN = CONVERT(VARCHAR(12),''),
QTY=SUM(TRADEQTY),
MKTAMT=SUM(TRADEQTY*MARKETRATE),
NETAMT=SUM(CASE WHEN SELL_BUY = 1 
				THEN TRADEQTY*MARKETRATE+(TRADEQTY*NBROKAPP+NSERTAX+TURN_TAX+SEBI_TAX+INS_CHRG+OTHER_CHRG+BROKER_CHRG) 
				ELSE TRADEQTY*MARKETRATE-(TRADEQTY*NBROKAPP+NSERTAX+TURN_TAX+SEBI_TAX+INS_CHRG+OTHER_CHRG+BROKER_CHRG) 
		   END),
CL_RATE = 0,
PAYIN_DATE=SM.SEC_PAYIN,
ADJUST_DATE='DEC 31 2049 23:59',
TRANSTYPE = 'TRBSE',
PROCESSDATE=GETDATE()--,
--TRADE_NO='', Order_No=''
FROM ANAND.BSEDB_AB.DBO.SETTLEMENT S, ANAND.BSEDB_AB.DBO.SETT_MST SM, #PARTY P
WHERE S.SAUDA_DATE BETWEEN @SAUDA_DATE AND @SAUDA_DATE + ' 23:59:59'
AND TRADEQTY > 0 
AND AUCTIONPART NOT LIKE 'F%'
AND AUCTIONPART NOT LIKE 'A%'
AND S.SETT_NO = SM.SETT_NO	
AND S.SETT_TYPE = SM.SETT_TYPE
AND S.SETT_TYPE IN ('D', 'C')
AND P.PARTY_CODE = S.PARTY_CODE
AND SETTFLAG NOT IN (2,3)
--AND PRODUCT_CODE = 'NRML'
GROUP BY LEFT(S.SAUDA_DATE,11), S.SETT_NO, S.SETT_TYPE, S.PARTY_CODE, S.SCRIP_CD, S.SERIES, 
SELL_BUY, SEC_PAYIN

UPDATE #TBL_PRODUCT_DATA SET ISIN = M.ISIN
FROM MSAJAG.DBO.TBL_EXCHG_SCRIP_MAP M
WHERE M.NSE_SCRIP_CD = #TBL_PRODUCT_DATA.SCRIP_CD
AND M.NSE_SERIES = #TBL_PRODUCT_DATA.SERIES 
AND @SAUDA_DATE BETWEEN FROM_DATE AND TO_DATE

UPDATE #TBL_PRODUCT_DATA SET ISIN = M.ISIN
FROM MSAJAG.DBO.TBL_EXCHG_SCRIP_MAP M
WHERE M.BSECODE = #TBL_PRODUCT_DATA.SCRIP_CD
AND M.BSECODE <> ''
AND @SAUDA_DATE BETWEEN FROM_DATE AND TO_DATE

UPDATE #TBL_PRODUCT_DATA SET ISIN = M.ISIN
FROM ANGELDEMAT.MSAJAG.DBO.MULTIISIN M
WHERE SAUDA_DATE BETWEEN @SAUDA_DATE AND @SAUDA_DATE + ' 23:59:59'
AND #TBL_PRODUCT_DATA.SCRIP_CD IN ('BE','EQ','BZ')
AND #TBL_PRODUCT_DATA.SERIES IN ('BE','EQ','BZ')
AND VALID = 1 
AND #TBL_PRODUCT_DATA.ISIN = ''
AND TRANSTYPE = 'TRNSE'


UPDATE #TBL_PRODUCT_DATA SET ISIN = M.ISIN
FROM ANGELDEMAT.MSAJAG.DBO.MULTIISIN M
WHERE SAUDA_DATE BETWEEN @SAUDA_DATE AND @SAUDA_DATE + ' 23:59:59'
AND #TBL_PRODUCT_DATA.SCRIP_CD = M.Scrip_cd
AND #TBL_PRODUCT_DATA.SERIES = M.Series
AND VALID = 1 
AND #TBL_PRODUCT_DATA.ISIN = ''
AND TRANSTYPE = 'TRNSE'

UPDATE #TBL_PRODUCT_DATA SET ISIN = M.ISIN
FROM ANGELDEMAT.BSEDB.DBO.MULTIISIN M
WHERE SAUDA_DATE BETWEEN @SAUDA_DATE AND @SAUDA_DATE + ' 23:59:59'
AND #TBL_PRODUCT_DATA.BSECODE = M.Scrip_cd 
AND VALID = 1 
AND #TBL_PRODUCT_DATA.ISIN = ''
AND TRANSTYPE = 'TRBSE'

UPDATE #TBL_PRODUCT_DATA SET BSECODE = LEFT(M.Scrip_cd,6)
FROM ANGELDEMAT.BSEDB.DBO.MULTIISIN M
WHERE SAUDA_DATE BETWEEN @SAUDA_DATE AND @SAUDA_DATE + ' 23:59:59'
AND #TBL_PRODUCT_DATA.ISIN = M.ISIN
AND VALID = 1 
AND #TBL_PRODUCT_DATA.BSECODE = ''

UPDATE #TBL_PRODUCT_DATA SET SCRIP_CD = M.Scrip_cd, SERIES = M.Series 
FROM ANGELDEMAT.MSAJAG.DBO.MULTIISIN M
WHERE SAUDA_DATE BETWEEN @SAUDA_DATE AND @SAUDA_DATE + ' 23:59:59'
AND #TBL_PRODUCT_DATA.ISIN = M.ISIN
AND VALID = 1 
AND #TBL_PRODUCT_DATA.SCRIP_CD = ''

SELECT * INTO #NSECLOSING FROM MSAJAG.DBO.CLOSING WHERE  SYSDATE >= @SAUDA_DATE AND SYSDATE <=  @SAUDA_DATE + ' 23:59'

UPDATE #TBL_PRODUCT_DATA SET CL_RATE = C.CL_RATE
FROM #NSECLOSING C
WHERE SAUDA_DATE BETWEEN @SAUDA_DATE AND @SAUDA_DATE + ' 23:59:59'
AND #TBL_PRODUCT_DATA.SCRIP_CD = C.SCRIP_CD
AND #TBL_PRODUCT_DATA.SERIES = C.SERIES
AND #TBL_PRODUCT_DATA.CL_RATE = 0
AND SAUDA_DATE = LEFT(SYSDATE,11)

SELECT * INTO #BSECLOSING FROM ANAND.BSEDB_AB.DBO.CLOSING WHERE  SYSDATE >= @SAUDA_DATE AND SYSDATE <=  @SAUDA_DATE + ' 23:59'

CREATE INDEX #BSE ON #BSECLOSING
(SCRIP_CD,SYSDATE)

UPDATE #TBL_PRODUCT_DATA SET CL_RATE = C.CL_RATE
FROM #BSECLOSING C
WHERE #TBL_PRODUCT_DATA.SAUDA_DATE  =@SAUDA_DATE
AND #TBL_PRODUCT_DATA.BSECODE = C.SCRIP_CD
AND #TBL_PRODUCT_DATA.CL_RATE = 0
AND SAUDA_DATE = LEFT(SYSDATE,11) 

----- BELOW QUERY LIVE ON 08112019 FOR TESTING N47817

SELECT * INTO #SQOFF FROM MTF_SQUP_DETAILS
WHERE PARTY_CODE IN (
SELECT PARTY_CODE FROM #TBL_PRODUCT_DATA
WHERE SAUDA_DATE = @SAUDA_DATE AND #TBL_PRODUCT_DATA.PARTY_CODE = MTF_SQUP_DETAILS.PARTY_CODE
AND #TBL_PRODUCT_DATA.ISIN =MTF_SQUP_DETAILS.ISIN AND Sell_Buy=2
AND left(EXCHANGE,3)= right(TRANSTYPE,3))
AND @SAUDA_DATE =LEFT(PROCESSDATE,11)

UPDATE #TBL_PRODUCT_DATA SET QTY = QTY - SQQTY, MKTAMT = (MKTAMT/QTY) * (QTY - SQQTY),NETAMT = (NETAMT/QTY)* (QTY - SQQTY)
FROM #SQOFF
WHERE #SQOFF.PARTY_CODE = #TBL_PRODUCT_DATA.PARTY_CODE
AND #SQOFF.ISIN = #TBL_PRODUCT_DATA.ISIN 
AND SELL_BUY = 2 
AND left(EXCHANGE,3)= right(TRANSTYPE,3)

DELETE FROM #TBL_PRODUCT_DATA
WHERE SAUDA_DATE = @SAUDA_DATE
AND QTY <= 0 

DELETE FROM #TBL_PRODUCT_DATA
WHERE SAUDA_DATE = @SAUDA_DATE
AND NOT EXISTS (SELECT ISIN FROM TBLSCRIPMARGIN WHERE SAUDA_DATE BETWEEN FROM_DATE AND TO_DATE AND #TBL_PRODUCT_DATA.ISIN = TBLSCRIPMARGIN.ISIN)
AND SELL_BUY = 1 

UPDATE #TBL_PRODUCT_DATA SET MKTAMT = ROUND(MKTAMT,2), NETAMT = ROUND(NETAMT,2)
WHERE SAUDA_DATE = @SAUDA_DATE

INSERT INTO TBL_PRODUCT_DATA
SELECT * FROM #TBL_PRODUCT_DATA

INSERT INTO MTF_SQUP_DETAILS_LOG
SELECT *,GETDATE() FROM #SQOFF

-----ABOVE QUERY LIVE ON 08112019 FOR TESTING N47817

END

EXEC PROC_PRODUCT_SALE_ADJUST		@SAUDA_DATE

--IF @PROCESSFLAG = 0 
--BEGIN
	EXEC PROC_PRODUCT_PROCESS			@SAUDA_DATE
--END   

EXEC PROC_MTFBILLPOST				@SAUDA_DATE

EXEC PROC_PRODUCT_BUY_ADJUST		@SAUDA_DATE

--EXEC PROC_PRODUCT_PFADJUST			@SAUDA_DATE, 0

INSERT INTO TBL_MTF_DATA_LOG

SELECT SAUDA_DATE,PARTY_CODE,SCRIP_CD,SERIES,BSECODE,ISIN,QTY,MKTAMT,NETAMT,CL_RATE,CURR_CL_RATE,HAIRCUT,MARGIN_REQ,MTOM_LOSS,

		FOMARGIN,CMLEDBAL,MTFLEDBAL,FOLEDBAL,CMCASHEQCOLLATERAL,CMCASHCOLLATERAL,CMNONCASHCOLLATERAL,CMNONCASHCOLLATERAL_MTF,

		CMDEBITHOLD,CMDEBITHOLD_MTF,CMOPENPOS,MTFCASHEQCOLLATERAL,MTFCASHCOLLATERAL,MTFNONCASHCOLLATERAL,FOCASHEQCOLLATERAL,

		FOCASHCOLLATERAL,FONONCASHCOLLATERAL,FONONCASHCOLLATERAL_MTF,NET_AVL_FUND,POAHOLDING,POAHOLDING_MTF,SELLSHORT,

		CASHDEBITADJ,CASHNONCASHADJ,FONONCASHADJ,CASHLEDADJ,FOLEDBALADJ,POAADJ, RUNDATE=GETDATE()

FROM TBL_MTF_DATA

WHERE SAUDA_DATE = @SAUDA_DATE

IF @PROCESSFLAG = 0 
BEGIN
	TRUNCATE TABLE TBL_PRODUCT_POSITION_TMP

	--INSERT INTO TBL_PRODUCT_POSITION_TMP
	--SELECT SAUDA_DATE,SETT_NO,SETT_TYPE,PARTY_CODE,PRODUCT_CODE,SCRIP_CD,SERIES,BSECODE,SELL_BUY,
	--	   ISIN,QTY,MKTAMT,NETAMT,CL_RATE,PAYIN_DATE,ADJUST_DATE,TRANSTYPE,PROCESSDATE,TRADE_NO, Order_No
	--FROM  TBL_PRODUCT_POSITION 
 --   WHERE  SAUDA_DATE = @SAUDA_DATE  
 --          AND SELL_BUY = 1
	
	--EXEC PROC_PRODUCT_REQSHORT_ADJUST	@SAUDA_DATE
	--EXEC PROC_PRODUCT_BUY_ADJUST	@SAUDA_DATE, 2
	EXEC PROC_PRODUCT_PFADJUST		@SAUDA_DATE, 1
END

 
EXEC DELIVERY_INTEROP_MTF @SAUDA_DATE

IF @PROCESSFLAG = 0 
BEGIN 
	EXEC MTF_POS_RECO_DET @SAUDA_DATE, 'NON RECO', '%', '%', 1
	--EXEC MSAJAG.DBO.MTF_POOL_BEN_ADJUST @SAUDA_DATE
END

EXEC PROC_PRODUCT_LEDGER_ADJUST @SAUDA_DATE, 0

EXEC RPT_NSE_MTFFILE @SAUDA_DATE, 1, '' 


INSERT INTO TBL_MTF_DATA_LOG

SELECT SAUDA_DATE,PARTY_CODE,SCRIP_CD,SERIES,BSECODE,ISIN,QTY,MKTAMT,NETAMT,CL_RATE,CURR_CL_RATE,HAIRCUT,MARGIN_REQ,MTOM_LOSS,

		FOMARGIN,CMLEDBAL,MTFLEDBAL,FOLEDBAL,CMCASHEQCOLLATERAL,CMCASHCOLLATERAL,CMNONCASHCOLLATERAL,CMNONCASHCOLLATERAL_MTF,

		CMDEBITHOLD,CMDEBITHOLD_MTF,CMOPENPOS,MTFCASHEQCOLLATERAL,MTFCASHCOLLATERAL,MTFNONCASHCOLLATERAL,FOCASHEQCOLLATERAL,

		FOCASHCOLLATERAL,FONONCASHCOLLATERAL,FONONCASHCOLLATERAL_MTF,NET_AVL_FUND,POAHOLDING,POAHOLDING_MTF,SELLSHORT,

		CASHDEBITADJ,CASHNONCASHADJ,FONONCASHADJ,CASHLEDADJ,FOLEDBALADJ,POAADJ, RUNDATE=GETDATE() 

FROM TBL_MTF_DATA

WHERE SAUDA_DATE = @SAUDA_DATE

INSERT INTO TBL_MTF_LOG
SELECT @SAUDA_DATE, @PROCESS_START, GETDATE()

SELECT FLAG = 1, MSG = 'PROCESS OVER'

GO
