-- Object: PROCEDURE dbo.PROC_MTFBILLPOST_15072019
-- Server: 10.253.33.91 | DB: MTFTRADE
--------------------------------------------------




CREATE PROC [dbo].[PROC_MTFBILLPOST]
(
	@SAUDA_DATE VARCHAR(11)
)
AS

DECLARE 
		@GLCODE		VARCHAR(10),
		@VNO		VARCHAR(12),
		@CASHVNO		VARCHAR(12),
		@SDTCUR		VARCHAR(11),
		@LDTCUR		VARCHAR(11),
		@PAYIN_DATE	DATETIME

SET @VNO = ''

SELECT @SDTCUR = SDTCUR, @LDTCUR = LDTCUR
FROM PARAMETER WHERE @SAUDA_DATE BETWEEN @SDTCUR AND LDTCUR

SELECT @PAYIN_DATE = MAX(SEC_PAYIN) FROM MSAJAG.DBO.SETT_MST WHERE START_DATE <= @SAUDA_DATE AND SETT_TYPE = 'N'

-- EXEC PROC_MTFBILLPOST 'JUL 11 2017'
 
SELECT @GLCODE = ACCODE FROM VALANACCOUNT
WHERE ACNAME =  'MTF VALAN'

SELECT @VNO = ISNULL(MAX(VNO),'') FROM MTF_BILL_DETAIL
WHERE BILLDATE = @SAUDA_DATE 

IF @VNO = ''
BEGIN
	CREATE TABLE #VNO
	(
		VNO	VARCHAR(12)
	)
	INSERT INTO #VNO 
	EXEC ACC_GENVNO @SAUDA_DATE, 35, '01', @SDTCUR, @LDTCUR, 1

	SELECT @VNO = VNO FROM #VNO
	
	INSERT INTO MTF_BILL_DETAIL
	SELECT @SAUDA_DATE, @VNO
END
ELSE
BEGIN
	DELETE FROM LEDGER WHERE VNO = @VNO AND VTYP = '35' AND BOOKTYPE = '01'  
END

SELECT @CASHVNO = ISNULL(MAX(VNO),'') FROM ACCOUNT.DBO.MTF_BILL_DETAIL
WHERE BILLDATE = @SAUDA_DATE 

IF @CASHVNO = ''
BEGIN
	CREATE TABLE #CASHVNO
	(
		VNO	VARCHAR(12)
	)
	INSERT INTO #CASHVNO 
	EXEC ACCOUNT.DBO.ACC_GENVNO_NEW @SAUDA_DATE, 35, '01', @SDTCUR, @LDTCUR, 1

	SELECT @CASHVNO = VNO FROM #CASHVNO
	
	INSERT INTO ACCOUNT.DBO.MTF_BILL_DETAIL
	SELECT @SAUDA_DATE, @CASHVNO
END
ELSE
BEGIN
	DELETE FROM ACCOUNT.DBO.LEDGER WHERE VNO = @CASHVNO AND VTYP = '35' AND BOOKTYPE = '01'  
END

SELECT PARTY_CODE, AMOUNT = SUM(NETAMT), 
NARRATION = CONVERT(VARCHAR(100),'Transferred to MTF for ' + SETT_NO + '-' + LTRIM(RTRIM(SETT_TYPE)) + ' bill Dated ' + LEFT(SAUDA_DATE,11)), DRCR = 'D',
PAYIN_DATE,VNO = @VNO
INTO #BILL
FROM TBL_PRODUCT_POSITION
WHERE SAUDA_DATE = @SAUDA_DATE
AND SELL_BUY = 1 
GROUP BY SETT_NO, SETT_TYPE, PARTY_CODE, SAUDA_DATE,PAYIN_DATE

INSERT INTO #BILL
SELECT PARTY_CODE, AMOUNT = SUM(NETAMT), NARRATION = 'Reversed against sale of MTF shares dated ' + @SAUDA_DATE,DRCR = 'C',
PAYIN_DATE=@PAYIN_DATE,VNO = @VNO
FROM TBL_PRODUCT_POSITION P
WHERE SAUDA_DATE <= @SAUDA_DATE
AND SELL_BUY = 1 
AND ADJUST_DATE = @SAUDA_DATE
GROUP BY PARTY_CODE

SELECT PARTY_CODE, AMOUNT = SUM(NETAMT), 
NARRATION = CONVERT(VARCHAR(100),'Transferred to MTF for ' + SETT_NO + '-' + LTRIM(RTRIM(SETT_TYPE)) + ' bill Dated ' + LEFT(SAUDA_DATE,11)), DRCR = 'D',
PAYIN_DATE,VNO = @CASHVNO
INTO #CASHBILL
FROM TBL_PRODUCT_POSITION
WHERE SAUDA_DATE = @SAUDA_DATE
AND SELL_BUY = 1 AND TRANSTYPE = 'TRNSE'
GROUP BY SETT_NO, SETT_TYPE, PARTY_CODE, SAUDA_DATE,PAYIN_DATE

INSERT INTO #CASHBILL
SELECT PARTY_CODE, AMOUNT = SUM(NETAMT), NARRATION = 'Reversed against sale of MTF shares dated ' + @SAUDA_DATE,DRCR = 'C',
PAYIN_DATE=@PAYIN_DATE,VNO = @CASHVNO
FROM TBL_PRODUCT_POSITION P
WHERE SAUDA_DATE <= @SAUDA_DATE
AND SELL_BUY = 1 AND TRANSTYPE = 'TRNSE'
AND ADJUST_DATE = @SAUDA_DATE
GROUP BY PARTY_CODE 
 
UPDATE #CASHBILL SET DRCR = (CASE WHEN DRCR = 'C' THEN 'D' ELSE 'C' END)

ALTER TABLE #CASHBILL
ADD SNO INT IDENTITY(1,1)

ALTER TABLE #BILL
ADD SNO INT IDENTITY(1,1)

INSERT INTO #BILL
SELECT @GLCODE, AMOUNT = SUM(AMOUNT), NARRATION, DRCR = (CASE WHEN DRCR = 'C' THEN 'D' ELSE 'C' END), PAYIN_DATE, VNO
FROM #BILL
GROUP BY NARRATION, PAYIN_DATE, VNO, DRCR 

ALTER TABLE #BILL
ADD ACNAME VARCHAR(200) 

UPDATE #BILL SET ACNAME = A.LONGNAME 
FROM ACMAST A
WHERE #BILL.PARTY_CODE = A.CLTCODE

INSERT INTO LEDGER
SELECT '35', VNO, PAYIN_DATE, SNO, ACNAME, DRCR, AMOUNT, @SAUDA_DATE, '', '', 0, 0, GETDATE(), PARTY_CODE, '01', 'MTF PROCESS', GETDATE(), 'MTF PROCESS', 0, NARRATION
FROM #BILL


INSERT INTO #CASHBILL
SELECT @GLCODE, AMOUNT = SUM(AMOUNT), NARRATION, DRCR = (CASE WHEN DRCR = 'C' THEN 'D' ELSE 'C' END), 
PAYIN_DATE, VNO
FROM #CASHBILL
GROUP BY NARRATION, PAYIN_DATE, VNO, DRCR 

ALTER TABLE #CASHBILL
ADD ACNAME VARCHAR(200) 

UPDATE #CASHBILL SET ACNAME = A.LONGNAME 
FROM ACMAST A
WHERE #CASHBILL.PARTY_CODE = A.CLTCODE

INSERT INTO ACCOUNT.DBO.LEDGER
SELECT '35', VNO, PAYIN_DATE, SNO, ACNAME, DRCR, AMOUNT, @SAUDA_DATE, '', '', 0, 0, GETDATE(), PARTY_CODE, '01', 'MTF PROCESS', GETDATE(), 'MTF PROCESS', 0, NARRATION
FROM #CASHBILL

EXEC ANAND.ACCOUNT_AB.DBO.PROC_MTFBILLPOST @SAUDA_DATE

GO
