-- Object: PROCEDURE dbo.PROC_MTF_CA_NAMECHG_dummy
-- Server: 10.253.33.91 | DB: MTFTRADE
--------------------------------------------------





CREATE PROC [dbo].[PROC_MTF_CA_NAMECHG_dummy]
(
		@SAUDA_DATE VARCHAR(11),
		@OLDSYMBOL	VARCHAR(12),
		@NEWSYMBOL	VARCHAR(12),
		@OLDISIN	VARCHAR(12),
		@NEWISIN	VARCHAR(12),
		@RATIO		NUMERIC(18,4)
) AS

--  EXEC PROC_MTF_CA_NAMECHG @SAUDA_DATE= 'MAR 17 2020', @OLDSYMBOL = 'YESBANK', @NEWSYMBOL = 'YESBANK', @OLDISIN = 'INE528G01027', @NEWISIN = 'INE528G01035', @RATIO = 1  

--INSERT INTO TBL_PRODUCT_POS_ADJUST
SELECT SAUDA_DATE=@SAUDA_DATE,SETT_NO='2000000',SETT_TYPE=(CASE WHEN TRANSTYPE = 'TRNSE' THEN 'N' ELSE 'D' END),
PARTY_CODE,SCRIP_CD,
SERIES,BSECODE,ISIN,QTY=SUM(QTY),TRANSTYPE,ADDED_BY='',ADDED_ON=GETDATE()
FROM TBL_PRODUCT_POSITION
WHERE SAUDA_DATE < @SAUDA_DATE
AND SELL_BUY = 1 
AND ADJUST_DATE >= 'DEC 31 2049'
AND ISIN = @OLDISIN
AND SCRIP_CD = @OLDSYMBOL
GROUP BY PARTY_CODE,SCRIP_CD,SERIES,BSECODE,ISIN,TRANSTYPE

---SAUDA_dATE PROCESS DATE APR  6 2018

---INSERT INTO TBL_PRODUCT_POS_ADJUST_BUY
SELECT SAUDA_DATE=@SAUDA_DATE,SETT_NO='2000000',SETT_TYPE=(CASE WHEN TRANSTYPE = 'TRNSE' THEN 'N' ELSE 'D' END),
PARTY_CODE,SCRIP_CD=@NEWSYMBOL,
SERIES,BSECODE,ISIN=@NEWISIN,QTY=FLOOR(SUM(QTY)*@RATIO),TRANSTYPE,ADDED_BY='',ADDED_ON=GETDATE(),
MKTAMT = SUM(MKTAMT), NETAMT = SUM(NETAMT)
FROM TBL_PRODUCT_POSITION
WHERE SAUDA_DATE < @SAUDA_DATE
AND SELL_BUY = 1 
AND ADJUST_DATE >= 'DEC 31 2049'
AND ISIN = @OLDISIN
AND SCRIP_CD = @OLDSYMBOL
GROUP BY PARTY_CODE,SCRIP_CD,SERIES,BSECODE,ISIN,TRANSTYPE

GO
