-- Object: PROCEDURE dbo.MTF_POS_RECO_DET
-- Server: 10.253.33.91 | DB: MTFTRADE
--------------------------------------------------



-- EXEC MTF_POS_RECO_DET 'DEC 21 2020', 'NON RECO', 'J83805'          
CREATE PROC [dbo].[MTF_POS_RECO_DET]            
(            
 @TRANSDATE VARCHAR(11),        
 @OPT VARCHAR(10) = 'NON RECO',          
 @PARTY_CODE VARCHAR(10)='%',          
 @ISIN  VARCHAR(12)='%',  
 @flag int = 0            
)            
AS            
      
--SET XACT_ABORT ON      
      
DECLARE @INTERNALPARTY VARCHAR(10)      
      
SELECT @INTERNALPARTY = ''     
        
--SET @ISIN = 'INE421D01022'        
        
--DECLARE @TRANSDATE VARCHAR(11)          
          
--SET @TRANSDATE = 'OCT 14 2013'          
        
SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED        
        
SET @PARTY_CODE = (CASE WHEN @PARTY_CODE = '' THEN '%' ELSE @PARTY_CODE END)        
SET @ISIN = (CASE WHEN @ISIN = '' THEN '%' ELSE @ISIN END)        
        
IF LEN(@TRANSDATE) = 10         
BEGIN        
 SELECT @TRANSDATE = LEFT(CONVERT(DATETIME,@TRANSDATE,103),11)        
END        

--TRUNCATE TABLE TMP_HOLD        
          
SELECT PARTY_CODE, PARTY_NAME = CONVERT(VARCHAR(100),''),          
SCRIP_CD=CONVERT(VARCHAR(12),SCRIP_CD), 
SERIES=CONVERT(VARCHAR(3),SERIES), BSECODE=CONVERT(VARCHAR(12),BSECODE), SCRIP_NAME=CONVERT(VARCHAR(100),''),             
ISIN,           
NSEPOSQTY = SUM(CASE WHEN TRANSTYPE = 'TRNSE' THEN QTY ELSE 0 END),      
BSEPOSQTY = SUM(CASE WHEN TRANSTYPE = 'TRBSE' THEN QTY ELSE 0 END),           
FUTPAYINQTY = CONVERT(NUMERIC(18,3),0),          
FUTPAYOUTQTY = CONVERT(NUMERIC(18,3),0),           
NSEPOOLQTY = CONVERT(NUMERIC(18,3),0),   
BSEPOOLQTY = CONVERT(NUMERIC(18,3),0),    
POAQTY = CONVERT(NUMERIC(18,3),0),          
PLDGQTY = CONVERT(NUMERIC(18,3),0),         
CAQTY = 0,        
AUCQTY = CONVERT(NUMERIC(18,3),0),        
BROKERQTY = CONVERT(NUMERIC(18,3),0),        
CLTDPID=CONVERT(VARCHAR(17),'')          
INTO #POS FROM TBL_PRODUCT_POSITION (NOLOCK)          
WHERE SAUDA_DATE <= @TRANSDATE         
AND ADJUST_DATE > @TRANSDATE   
AND SELL_BUY = 1   
AND PARTY_CODE = (CASE WHEN @PARTY_CODE = '%' THEN PARTY_CODE ELSE @PARTY_CODE END)        
AND ISIN = (CASE WHEN @ISIN = '%' THEN ISIN ELSE @ISIN END)         
GROUP BY PARTY_CODE, SCRIP_CD, SERIES, BSECODE, ISIN          
HAVING SUM(QTY) > 0    

IF CONVERT(DATETIME,@TRANSDATE) + ' 16:30' > GETDATE() 
BEGIN
	INSERT INTO #POS 
	SELECT PARTY_CODE, PARTY_NAME = CONVERT(VARCHAR(100),''),          
	SCRIP_CD=CONVERT(VARCHAR(12),SCRIP_CD), 
	SERIES=CONVERT(VARCHAR(3),SERIES), BSECODE=CONVERT(VARCHAR(12),BSECODE), SCRIP_NAME=CONVERT(VARCHAR(100),''),             
	ISIN,           
	NSEPOSQTY = SUM(CASE WHEN TRANSTYPE = 'TRNSE' THEN -QTY ELSE 0 END),      
	BSEPOSQTY = SUM(CASE WHEN TRANSTYPE = 'TRBSE' THEN -QTY ELSE 0 END),           
	FUTPAYINQTY = CONVERT(NUMERIC(18,3),0),          
	FUTPAYOUTQTY = CONVERT(NUMERIC(18,3),0),           
	NSEPOOLQTY = CONVERT(NUMERIC(18,3),0),   
	BSEPOOLQTY = CONVERT(NUMERIC(18,3),0),    
	POAQTY = CONVERT(NUMERIC(18,3),0),          
	PLDGQTY = CONVERT(NUMERIC(18,3),0),         
	CAQTY = 0,        
	AUCQTY = CONVERT(NUMERIC(18,3),0),        
	BROKERQTY = CONVERT(NUMERIC(18,3),0),        
	CLTDPID=CONVERT(VARCHAR(17),'')          
	FROM TBL_PRODUCT_POS_ADJUST (NOLOCK)          
	WHERE SAUDA_DATE = @TRANSDATE  
	AND PARTY_CODE = (CASE WHEN @PARTY_CODE = '%' THEN PARTY_CODE ELSE @PARTY_CODE END)        
	AND ISIN = (CASE WHEN @ISIN = '%' THEN ISIN ELSE @ISIN END)         
	GROUP BY PARTY_CODE, SCRIP_CD, SERIES, BSECODE, ISIN          
	HAVING SUM(QTY) > 0  
	
	INSERT INTO #POS 
	SELECT PARTY_CODE, PARTY_NAME = CONVERT(VARCHAR(100),''),          
	SCRIP_CD=CONVERT(VARCHAR(12),SCRIP_CD), 
	SERIES=CONVERT(VARCHAR(3),SERIES), BSECODE=CONVERT(VARCHAR(12),BSECODE), SCRIP_NAME=CONVERT(VARCHAR(100),''),             
	ISIN,           
	NSEPOSQTY = SUM(CASE WHEN TRANSTYPE = 'TRNSE' THEN QTY ELSE 0 END),      
	BSEPOSQTY = SUM(CASE WHEN TRANSTYPE = 'TRBSE' THEN QTY ELSE 0 END),           
	FUTPAYINQTY = CONVERT(NUMERIC(18,3),0),          
	FUTPAYOUTQTY = CONVERT(NUMERIC(18,3),0),           
	NSEPOOLQTY = CONVERT(NUMERIC(18,3),0),   
	BSEPOOLQTY = CONVERT(NUMERIC(18,3),0),    
	POAQTY = CONVERT(NUMERIC(18,3),0),          
	PLDGQTY = CONVERT(NUMERIC(18,3),0),         
	CAQTY = 0,        
	AUCQTY = CONVERT(NUMERIC(18,3),0),        
	BROKERQTY = CONVERT(NUMERIC(18,3),0),        
	CLTDPID=CONVERT(VARCHAR(17),'')          
	FROM TBL_PRODUCT_POS_ADJUST_buy (NOLOCK)          
	WHERE SAUDA_DATE = @TRANSDATE  
	AND PARTY_CODE = (CASE WHEN @PARTY_CODE = '%' THEN PARTY_CODE ELSE @PARTY_CODE END)        
	AND ISIN = (CASE WHEN @ISIN = '%' THEN ISIN ELSE @ISIN END)         
	GROUP BY PARTY_CODE, SCRIP_CD, SERIES, BSECODE, ISIN          
	HAVING SUM(QTY) > 0   	 
 	
END
 

IF CONVERT(DATETIME,@TRANSDATE) + ' 14:30' > GETDATE() AND  @TRANSDATE = LEFT( GETDATE(), 11)
BEGIN 
	INSERT INTO #POS 
	SELECT PARTY_CODE, PARTY_NAME = CONVERT(VARCHAR(100),''),          
		SCRIP_CD=CONVERT(VARCHAR(12),SCRIP_CD), 
		SERIES=CONVERT(VARCHAR(3),SERIES), BSECODE=CONVERT(VARCHAR(12),''), SCRIP_NAME=CONVERT(VARCHAR(100),''),             
		ISIN=CERTNO,           
		NSEPOSQTY = 0,           
		BSEPOSQTY = 0,        
		FUTPAYINQTY = CONVERT(NUMERIC(18,3),0),          
		FUTPAYOUTQTY = SUM(QTY) ,           
		NSEPOOLQTY = CONVERT(NUMERIC(18,3),0),   
		BSEPOOLQTY = CONVERT(NUMERIC(18,3),0),    
		POAQTY = CONVERT(NUMERIC(18,3),0),          
		PLDGQTY = CONVERT(NUMERIC(18,3),0),         
		CAQTY = 0,        
		AUCQTY = CONVERT(NUMERIC(18,3),0),        
		BROKERQTY = CONVERT(NUMERIC(18,3),0),        
		CLTDPID=CONVERT(VARCHAR(17),'')          
		FROM angeldemat.MSAJAG.DBO.TBL_POA_PLD_ADNL     
		WHERE EXEDATE = @TRANSDATE  
		AND PARTY_CODE = (CASE WHEN @PARTY_CODE = '%' THEN PARTY_CODE ELSE @PARTY_CODE END)        
		AND CERTNO = (CASE WHEN @ISIN = '%' THEN CERTNO ELSE @ISIN END)
		--AND PAYQTY <> QTY        
		GROUP BY PARTY_CODE, SCRIP_CD, SERIES, CERTNO          
		HAVING SUM(QTY) > 0  
END 

SELECT SETT_NO, SETT_TYPE, PARTY_CODE, SCRIP_CD = CONVERT(VARCHAR(12),SCRIP_CD), 
SERIES = CONVERT(VARCHAR(3),SERIES), BSECODE, ISIN,
QTY = ABS(SUM(CASE WHEN SELL_BUY = 1 THEN QTY ELSE -QTY END)), 
FLAG = CONVERT(VARCHAR(12),'PAYOUT'), RECFLAG = 'MTF'
INTO #BTST
FROM TBL_PRODUCT_POSITION (NOLOCK)          
WHERE SAUDA_DATE <= @TRANSDATE         
AND PAYIN_DATE >= @TRANSDATE   
--AND SELL_BUY = 1   
AND PARTY_CODE = (CASE WHEN @PARTY_CODE = '%' THEN PARTY_CODE ELSE @PARTY_CODE END)        
AND ISIN = (CASE WHEN @ISIN = '%' THEN ISIN ELSE @ISIN END)  
AND Sett_No <> '2000000' 
AND SAUDA_DATE < 'JUL 15 2019'
GROUP BY SETT_NO, SETT_TYPE, PARTY_CODE, SCRIP_CD, SERIES, BSECODE, ISIN
HAVING SUM(CASE WHEN SELL_BUY = 1 THEN QTY ELSE -QTY END) > 0 

INSERT INTO #BTST
SELECT SETT_NO, SETT_TYPE, PARTY_CODE, SCRIP_CD, SERIES, BSECODE, ISIN,
QTY = ABS(SUM(CASE WHEN SELL_BUY = 1 THEN QTY ELSE -QTY END)), FLAG = 'PAYIN', RECFLAG = 'MTF'
FROM TBL_PRODUCT_POSITION (NOLOCK)          
WHERE SAUDA_DATE <= @TRANSDATE         
AND PAYIN_DATE >= @TRANSDATE   
--AND SELL_BUY = 2 
AND PARTY_CODE = (CASE WHEN @PARTY_CODE = '%' THEN PARTY_CODE ELSE @PARTY_CODE END)        
AND ISIN = (CASE WHEN @ISIN = '%' THEN ISIN ELSE @ISIN END)   
AND Sett_No <> '2000000' 
AND SAUDA_DATE < 'JUL 15 2019'  
GROUP BY SETT_NO, SETT_TYPE, PARTY_CODE, SCRIP_CD, SERIES, BSECODE, ISIN
HAVING SUM(CASE WHEN SELL_BUY = 1 THEN QTY ELSE -QTY END) < 0 

INSERT INTO #BTST
SELECT N.SETT_NO, N.SETT_TYPE, PARTY_CODE, SCRIP_CD, N.SERIES, BSECODE='', I_ISIN,
QTY = SUM(QTY), FLAG = 'PAYOUT', RECFLAG = 'MTF'
FROM NSE_DELIVERYCLT_MTF N, MSAJAG.DBO.SETT_MST S (NOLOCK)          
WHERE START_DATE <= @TRANSDATE         
AND SEC_PAYIN > @TRANSDATE   
AND INOUT  ='O'
AND N.SETT_NO = S.SETT_NO
AND N.SETT_TYPE = S.SETT_TYPE
AND PARTY_CODE = (CASE WHEN @PARTY_CODE = '%' THEN PARTY_CODE ELSE @PARTY_CODE END)        
AND I_ISIN = (CASE WHEN @ISIN = '%' THEN I_ISIN ELSE @ISIN END)   
AND N.Sett_No <> '2000000' 
AND START_DATE >= 'JUL 15 2019'  
GROUP BY N.SETT_NO, N.SETT_TYPE, PARTY_CODE, SCRIP_CD, N.SERIES, I_ISIN 
 
INSERT INTO #BTST
SELECT N.SETT_NO, N.SETT_TYPE, PARTY_CODE, SCRIP_CD, N.SERIES, BSECODE='', I_ISIN,
QTY = SUM(QTY), FLAG = 'PAYIN', RECFLAG = 'MTF'
FROM NSE_DELIVERYCLT_MTF N, MSAJAG.DBO.SETT_MST S (NOLOCK)          
WHERE START_DATE <= @TRANSDATE         
AND SEC_PAYIN > @TRANSDATE   
AND INOUT  ='I'
AND N.SETT_NO = S.SETT_NO
AND N.SETT_TYPE = S.SETT_TYPE
AND PARTY_CODE = (CASE WHEN @PARTY_CODE = '%' THEN PARTY_CODE ELSE @PARTY_CODE END)        
AND I_ISIN = (CASE WHEN @ISIN = '%' THEN I_ISIN ELSE @ISIN END)   
AND N.Sett_No <> '2000000' 
AND START_DATE >= 'JUL 15 2019'  
GROUP BY N.SETT_NO, N.SETT_TYPE, PARTY_CODE, SCRIP_CD, N.SERIES, I_ISIN 
 
INSERT INTO #POS   
SELECT PARTY_CODE, PARTY_NAME = CONVERT(VARCHAR(100),''),          
SCRIP_CD, SERIES, BSECODE=CONVERT(VARCHAR(12),BSECODE), SCRIP_NAME=CONVERT(VARCHAR(100),''),     ISIN,           
NSEPOSQTY = 0,            
BSEPOSQTY = 0,  
FUTPAYINQTY = SUM(CASE WHEN FLAG = 'PAYIN' THEN (QTY) ELSE 0 END),          
FUTPAYOUTQTY = SUM(CASE WHEN FLAG = 'PAYOUT' THEN (QTY) ELSE 0 END),                
NSEPOOLQTY = CONVERT(NUMERIC(18,3),0),   
BSEPOOLQTY = CONVERT(NUMERIC(18,3),0),            
POAQTY = CONVERT(NUMERIC(18,3),0),          
PLDGQTY = CONVERT(NUMERIC(18,3),0),         
CAQTY = 0,        
AUCQTY = CONVERT(NUMERIC(18,3),0),        
BROKERQTY = CONVERT(NUMERIC(18,3),0),        
CLTDPID=CONVERT(VARCHAR(17),'')  
FROM (
SELECT Sett_No, Sett_Type, PARTY_CODE, SCRIP_CD, SERIES, BSECODE, ISIN, FLAG, QTY = MIN(QTY) 
FROM #BTST 
GROUP BY Sett_No, Sett_Type, PARTY_CODE, SCRIP_CD, SERIES, BSECODE, ISIN, FLAG) A
GROUP BY Sett_No, Sett_Type, PARTY_CODE, SCRIP_CD, SERIES, BSECODE, ISIN, FLAG 

/*
INSERT INTO #POS   
SELECT PARTY_CODE, PARTY_NAME = CONVERT(VARCHAR(100),''),          
SCRIP_CD, SERIES, BSECODE=CONVERT(VARCHAR(12),BSECODE), SCRIP_NAME=CONVERT(VARCHAR(100),''),     ISIN,           
NSEPOSQTY = 0,            
BSEPOSQTY = 0,  
FUTPAYINQTY = CONVERT(NUMERIC(18,3),0),          
FUTPAYOUTQTY = SUM(QTY),                
NSEPOOLQTY = CONVERT(NUMERIC(18,3),0),   
BSEPOOLQTY = CONVERT(NUMERIC(18,3),0),            
POAQTY = CONVERT(NUMERIC(18,3),0),          
PLDGQTY = CONVERT(NUMERIC(18,3),0),         
CAQTY = 0,        
AUCQTY = CONVERT(NUMERIC(18,3),0),        
BROKERQTY = CONVERT(NUMERIC(18,3),0),        
CLTDPID=CONVERT(VARCHAR(17),'')          
FROM TBL_PRODUCT_POSITION (NOLOCK)          
WHERE SAUDA_DATE <= @TRANSDATE         
AND PAYIN_DATE >= @TRANSDATE   
AND SELL_BUY = 1   
AND PARTY_CODE = (CASE WHEN @PARTY_CODE = '%' THEN PARTY_CODE ELSE @PARTY_CODE END)        
AND ISIN = (CASE WHEN @ISIN = '%' THEN ISIN ELSE @ISIN END)  
AND Sett_No <> '2000000'         
GROUP BY PARTY_CODE, SCRIP_CD, SERIES, BSECODE, ISIN          
HAVING SUM(QTY) > 0   
     
INSERT INTO #POS   
SELECT PARTY_CODE, PARTY_NAME = CONVERT(VARCHAR(100),''),          
SCRIP_CD, SERIES, BSECODE=CONVERT(VARCHAR(12),BSECODE), SCRIP_NAME=CONVERT(VARCHAR(100),''),     
ISIN,           
NSEPOSQTY = 0,            
BSEPOSQTY = 0,          
FUTPAYINQTY = SUM(QTY),          
FUTPAYOUTQTY = 0,                
NSEPOOLQTY = CONVERT(NUMERIC(18,3),0),   
BSEPOOLQTY = CONVERT(NUMERIC(18,3),0),           
POAQTY = CONVERT(NUMERIC(18,3),0),          
PLDGQTY = CONVERT(NUMERIC(18,3),0),         
CAQTY = 0,        
AUCQTY = CONVERT(NUMERIC(18,3),0),        
BROKERQTY = CONVERT(NUMERIC(18,3),0),        
CLTDPID=CONVERT(VARCHAR(17),'')          
FROM TBL_PRODUCT_POSITION (NOLOCK)          
WHERE SAUDA_DATE <= @TRANSDATE         
AND PAYIN_DATE >= @TRANSDATE   
AND SELL_BUY = 2 AND PARTY_CODE = (CASE WHEN @PARTY_CODE = '%' THEN PARTY_CODE ELSE @PARTY_CODE END)        
AND ISIN = (CASE WHEN @ISIN = '%' THEN ISIN ELSE @ISIN END)   
AND Sett_No <> '2000000'        
GROUP BY PARTY_CODE, SCRIP_CD, SERIES, BSECODE, ISIN          
HAVING SUM(QTY) > 0   
*/
  

SELECT DISTINCT SETT_NO, SETT_TYPE, PARTY_CODE, ISIN, SELL_BUY   
INTO #DATA  
FROM TBL_PRODUCT_POSITION (NOLOCK)          
WHERE SAUDA_DATE <= @TRANSDATE         
AND PAYIN_DATE > @TRANSDATE   
 
INSERT INTO #POS            
EXEC angeldemat.MSAJAG.DBO.MTF_RECO @TRANSDATE, @OPT, @PARTY_CODE, @ISIN  

UPDATE #POS SET SCRIP_NAME = ''        
      
UPDATE #POS SET      
SCRIP_CD = M.SCRIP_CD, SERIES = M.SERIES           
FROM ANGELDEMAT.MSAJAG.DBO.MULTIISIN M          
WHERE #POS.ISIN = M.ISIN     
AND VALID = 1         
  
UPDATE #POS SET      
BSECODE = M.SCRIP_CD        
FROM ANGELDEMAT.BSEDB.DBO.MULTIISIN M          
WHERE #POS.ISIN = M.ISIN     
AND VALID = 1         
          
UPDATE #POS SET PARTY_NAME = LONG_NAME FROM MSAJAG.DBO.CLIENT1 (NOLOCK)          
WHERE CL_CODE = PARTY_CODE          

UPDATE #POS SET CLTDPID = (CASE WHEN BANKID LIKE 'IN%' THEN C4.BANKID + ' ' + C4.CLTDPID ELSE 'C' + C4.CLTDPID END)
FROM MSAJAG.DBO.CLIENT4 C4
WHERE #POS.PARTY_CODE = C4.PARTY_CODE
AND C4.DEPOSITORY IN ('CDSL','NSDL')
AND DEFDP = 1 

ALTER TABLE #POS        
ADD D_FLAG VARCHAR(1)        
          
update #POS set D_FLAG = ''  
   
UPDATE #POS SET D_FLAG = 'Y', PARTY_NAME = '*' + PARTY_NAME         
FROM TBLCLIENTMARGIN D  (NOLOCK)      
WHERE #POS.PARTY_CODE = D.PARTY_CODE        
AND TO_DATE <= @TRANSDATE + ' 23:59:59'        
  
SELECT PARTY_CODE,PARTY_NAME,SCRIP_CD,SERIES,BSECODE,SCRIP_NAME,ISIN,CLTDPID,D_FLAG,  
 NSEPOSQTY=SUM(NSEPOSQTY), BSEPOSQTY = SUM(BSEPOSQTY),  
 FUTPAYINQTY=(CASE WHEN SUM(FUTPAYINQTY) > 0 THEN SUM(FUTPAYINQTY) ELSE 0 END),          
 FUTPAYOUTQTY=(CASE WHEN SUM(FUTPAYOUTQTY) > 0 THEN SUM(FUTPAYOUTQTY) ELSE 0 END),          
 NSEPOOLQTY=SUM(NSEPOOLQTY), BSEPOOLQTY = SUM(BSEPOOLQTY),            
 DIFFQTY=SUM(NSEPOSQTY + BSEPOSQTY)+  
   (CASE WHEN SUM(FUTPAYINQTY) > 0 THEN SUM(FUTPAYINQTY) ELSE 0 END)-  
   (CASE WHEN SUM(FUTPAYOUTQTY) > 0 THEN SUM(FUTPAYOUTQTY) ELSE 0 END)-  
   SUM(NSEPOOLQTY) - SUM(BSEPOOLQTY)-SUM(POAQTY)-SUM(PLDGQTY)-SUM(CAQTY)  
INTO #POSFINAL  
FROM #POS           
GROUP BY PARTY_CODE,PARTY_NAME,SCRIP_CD,SERIES,BSECODE,SCRIP_NAME,ISIN,CLTDPID,D_FLAG  
  
update #POSFINAL set SCRIP_NAME = s1.long_name from msajag.dbo.scrip1 s1, msajag.dbo.scrip2 s2  
where s1.co_code = s2.co_code   
and s1.series = s2.series   
and s2.scrip_cd = #POSFINAL.scrip_cd   
and s2.series = #POSFINAL.series   
and #POSFINAL.SCRIP_NAME = ''  
  
update #POSFINAL set SCRIP_NAME = s1.long_name from AngelBSECM.BSEDB_AB.dbo.scrip1 s1, AngelBSECM.BSEDB_AB.dbo.scrip2 s2  
where s1.co_code = s2.co_code   
and s1.series = s2.series   
and s2.bsecode = #POSFINAL.BSECODE    
and #POSFINAL.SCRIP_NAME = ''  

DELETE FROM #POSFINAL WHERE ISIN = 'INX528G01035'
  
IF @TRANSDATE = LEFT(GETDATE(),11)  
BEGIN  
 DELETE FROM TBL_MTF_RECO  
 WHERE SAUDA_DATE=CONVERT(DATETIME,@TRANSDATE)  
 and PARTY_CODE = (CASE WHEN @PARTY_CODE = '%' THEN PARTY_CODE ELSE @PARTY_CODE END)        
 AND ISIN = (CASE WHEN @ISIN = '%' THEN ISIN ELSE @ISIN END)    
  
 INSERT INTO TBL_MTF_RECO  
 SELECT SAUDA_DATE=CONVERT(DATETIME,@TRANSDATE), *   
 FROM #POSFINAL  
 WHERE PARTY_CODE = (CASE WHEN @PARTY_CODE = '%' THEN PARTY_CODE ELSE @PARTY_CODE END)        
 AND ISIN = (CASE WHEN @ISIN = '%' THEN ISIN ELSE @ISIN END)    
END  
  
if @flag = 0  
begin  
 IF @OPT = 'NON RECO'         
 BEGIN          
  SELECT * FROM #POSFINAL  
  WHERE DIFFQTY <> 0      
  ORDER BY D_FLAG, PARTY_CODE, ISIN        
 END        
         
 IF @OPT = 'RECO'         
 BEGIN          
    
  SELECT * FROM #POSFINAL  
  WHERE DIFFQTY = 0      
  ORDER BY D_FLAG, PARTY_CODE, ISIN          
 END        
         
 IF @OPT = 'ALL'         
 BEGIN          
    
  SELECT * FROM #POSFINAL    
  ORDER BY D_FLAG, PARTY_CODE, ISIN           
 END           
END  
DROP TABLE #POS         
DROP TABLE #POSFINAL         
              
        
--SET XACT_ABORT OFF

GO
