-- Object: PROCEDURE dbo.PROC_MTF_AUTO_CLOSE
-- Server: 10.253.33.91 | DB: MTFTRADE
--------------------------------------------------

CREATE PROC [dbo].[PROC_MTF_AUTO_CLOSE]
AS

SET NOCOUNT ON
DECLARE @SAUDA_DATE VARCHAR(11),
		@SDTCUR	VARCHAR(11),
		@LDTCUR	VARCHAR(11)
		
	SET @SAUDA_DATE = LEFT(GETDATE(),11)
	SELECT @SDTCUR = SDTCUR, @LDTCUR = LDTCUR FROM ACCOUNT.DBO.PARAMETER 
	WHERE @SAUDA_DATE BETWEEN SDTCUR AND LDTCUR  

SELECT PARTY_CODE, SCRIP_CD, SERIES, BSECODE, ISIN, QTY=SUM(QTY), NETAMT=SUM(NETAMT), MTFLED=CONVERT(NUMERIC(18,4),0),
ADJQTY=0 INTO #MTF_DATA FROM TBL_PRODUCT_POSITION
WHERE SAUDA_DATE <= @SAUDA_DATE AND PAYIN_DATE <=@SAUDA_DATE
AND SELL_BUY= 1 
AND ADJUST_DATE > @SAUDA_DATE
AND QTY > 0 
GROUP BY PARTY_CODE, SCRIP_CD, SERIES, BSECODE, ISIN

CREATE CLUSTERED INDEX IDX_PARTY ON #MTF_DATA
(
	PARTY_CODE, SCRIP_CD, SERIES, BSECODE, ISIN
)

SELECT DISTINCT PARTY_CODE INTO #B_MTF_DATA FROM #MTF_DATA

UPDATE #MTF_DATA  SET MTFLED = VDTLEDBAL
FROM (SELECT L.CLTCODE, 
           VDTLEDBAL = SUM(CASE 
                             WHEN DRCR = 'C' THEN VAMT 
                             ELSE -VAMT 
                           END) 
    FROM   LEDGER L,  
		   (SELECT DISTINCT PARTY_CODE		
                             FROM   #B_MTF_DATA ) M	
    WHERE  L.VDT BETWEEN @SDTCUR AND @LDTCUR 
           AND L.VDT <= @SAUDA_DATE + ' 23:59:59' 
           AND L.CLTCODE = PARTY_CODE
		   /*AND VTYP <> (CASE WHEN VDT BETWEEN @SAUDA_DATE AND @SAUDA_DATE + ' 23:59' 
							 THEN '35' ELSE '' END)*/
    GROUP  BY L.CLTCODE ) L
WHERE PARTY_CODE =CLTCODE

	SELECT L.CLTCODE, 
           VDTLEDBAL = SUM(CASE 
                             WHEN DRCR = 'C' THEN VAMT 
                             ELSE -VAMT 
                           END),
			MTFLED=CONVERT(NUMERIC(18,4),0) 
    INTO   #B_LEDBAL 
    FROM   ACCOUNT.DBO.LEDGER L,  
		   (SELECT DISTINCT PARTY_CODE		
                             FROM   #B_MTF_DATA ) M	
    WHERE  L.VDT BETWEEN @SDTCUR AND @LDTCUR 
           AND L.VDT <= @SAUDA_DATE + ' 23:59:59' 
           AND L.CLTCODE = PARTY_CODE
		   /*AND VTYP <> (CASE WHEN VDT BETWEEN @SAUDA_DATE AND @SAUDA_DATE + ' 23:59' 
							 THEN '35' ELSE '' END)*/
    GROUP  BY L.CLTCODE 

	INSERT  INTO   #B_LEDBAL 
    SELECT L.CLTCODE, 
           VDTLEDBAL = SUM(CASE 
                             WHEN DRCR = 'D' THEN VAMT 
                             ELSE -VAMT 
                           END),
			MTFLED=CONVERT(NUMERIC(18,4),0) 
    FROM   ACCOUNT.DBO.LEDGER L,  
		   (SELECT DISTINCT PARTY_CODE		
                             FROM   #B_MTF_DATA ) M	
    WHERE  L.VDT <= @SAUDA_DATE
           AND L.EDT > @SAUDA_DATE + ' 23:59:59' 
           AND L.CLTCODE = PARTY_CODE
		   /*AND VTYP <> (CASE WHEN VDT BETWEEN @SAUDA_DATE AND @SAUDA_DATE + ' 23:59' 
							 THEN '35' ELSE '' END)*/
    GROUP  BY L.CLTCODE 

INSERT INTO   #B_LEDBAL 
    SELECT L.CLTCODE, 
           VDTLEDBAL = SUM(CASE 
                             WHEN DRCR = 'C' THEN VAMT 
                             ELSE -VAMT 
                           END),
			MTFLED=CONVERT(NUMERIC(18,4),0)      
    FROM    AngelBSECM.ACCOUNT_AB.DBO.LEDGER L,  
		   (SELECT DISTINCT PARTY_CODE		
                             FROM   #B_MTF_DATA ) M	
    WHERE  L.VDT BETWEEN @SDTCUR AND @LDTCUR 
           AND L.VDT <= @SAUDA_DATE + ' 23:59:59' 
           AND L.CLTCODE = PARTY_CODE
		   /*AND VTYP <> (CASE WHEN VDT BETWEEN @SAUDA_DATE AND @SAUDA_DATE + ' 23:59' 
							 THEN '35' ELSE '' END)*/
    GROUP  BY L.CLTCODE 

	INSERT INTO   #B_LEDBAL 
    SELECT L.CLTCODE, 
           VDTLEDBAL = SUM(CASE 
                             WHEN DRCR = 'D' THEN VAMT 
                             ELSE -VAMT 
                           END),
			MTFLED=CONVERT(NUMERIC(18,4),0)      
    FROM   AngelBSECM.ACCOUNT_AB.DBO.LEDGER L,  
		   (SELECT DISTINCT PARTY_CODE		
                             FROM   #B_MTF_DATA ) M	
    WHERE  L.VDT <= @SAUDA_DATE
           AND L.EDT > @SAUDA_DATE + ' 23:59:59' 
           AND L.CLTCODE = PARTY_CODE
		   /*AND VTYP <> (CASE WHEN VDT BETWEEN @SAUDA_DATE AND @SAUDA_DATE + ' 23:59' 
							 THEN '35' ELSE '' END)*/
    GROUP  BY L.CLTCODE 	
	
	INSERT INTO #B_LEDBAL 
    SELECT L.CLTCODE, 
           VDTLEDBAL = SUM(CASE 
                             WHEN DRCR = 'C' THEN VAMT 
                             ELSE -VAMT 
                           END),
			MTFLED=CONVERT(NUMERIC(18,4),0)  
    FROM   ANGELFO.ACCOUNTFO.DBO.LEDGER L, 
		   (SELECT DISTINCT PARTY_CODE		
                             FROM   #B_MTF_DATA ) M 
    WHERE  L.VDT BETWEEN @SDTCUR AND @LDTCUR 
           AND L.VDT <= @SAUDA_DATE + ' 23:59:59' 
           AND L.CLTCODE = PARTY_CODE 
    GROUP  BY L.CLTCODE 

    INSERT INTO #B_LEDBAL 
    SELECT L.CLTCODE, 
           VDTLEDBAL = SUM(CASE 
                             WHEN DRCR = 'D' THEN VAMT 
                             ELSE -VAMT 
                           END),
			MTFLED=CONVERT(NUMERIC(18,4),0)  
    FROM   ANGELFO.ACCOUNTFO.DBO.LEDGER L, 
		   (SELECT DISTINCT PARTY_CODE		
                             FROM   #B_MTF_DATA ) M 
    WHERE  L.VDT <= @SAUDA_DATE
           AND L.EDT > @SAUDA_DATE + ' 23:59:59' 
           AND L.CLTCODE = PARTY_CODE 
    GROUP  BY L.CLTCODE 

	INSERT INTO #B_LEDBAL 
    SELECT L.CLTCODE, 
           VDTLEDBAL = SUM(CASE 
                             WHEN DRCR = 'C' THEN VAMT 
                             ELSE -VAMT 
                           END),
			MTFLED=CONVERT(NUMERIC(18,4),0)  
    FROM   ANGELFO.ACCOUNTCURFO.DBO.LEDGER L,  
		   (SELECT DISTINCT PARTY_CODE		
                             FROM   #B_MTF_DATA ) M 
    WHERE  L.VDT BETWEEN @SDTCUR AND @LDTCUR 
           AND L.VDT <= @SAUDA_DATE + ' 23:59:59' 
           AND L.CLTCODE = PARTY_CODE
    GROUP  BY L.CLTCODE 

	INSERT INTO #B_LEDBAL 
    SELECT L.CLTCODE, 
           VDTLEDBAL = SUM(CASE 
                             WHEN DRCR = 'D' THEN VAMT 
                             ELSE -VAMT 
                           END),
			MTFLED=CONVERT(NUMERIC(18,4),0)  
    FROM  ANGELFO.ACCOUNTCURFO.DBO.LEDGER L,  
		   (SELECT DISTINCT PARTY_CODE		
                             FROM   #B_MTF_DATA ) M 
    WHERE  L.VDT <= @SAUDA_DATE 
           AND L.EDT > @SAUDA_DATE + ' 23:59:59' 
           AND L.CLTCODE = PARTY_CODE
    GROUP  BY L.CLTCODE  
	
	INSERT INTO #B_LEDBAL 
    SELECT L.CLTCODE, 
           VDTLEDBAL = SUM(CASE 
                             WHEN DRCR = 'C' THEN VAMT 
                             ELSE -VAMT 
                           END),
			MTFLED=CONVERT(NUMERIC(18,4),0)  
    FROM   ANGELCOMMODITY.ACCOUNTNCDX.DBO.LEDGER L,  
		   (SELECT DISTINCT PARTY_CODE		
                             FROM   #B_MTF_DATA ) M 
    WHERE  L.VDT BETWEEN @SDTCUR AND @LDTCUR 
           AND L.VDT <= @SAUDA_DATE + ' 23:59:59' 
           AND L.CLTCODE = PARTY_CODE
    GROUP  BY L.CLTCODE 

	INSERT INTO #B_LEDBAL 
    SELECT L.CLTCODE, 
           VDTLEDBAL = SUM(CASE 
                             WHEN DRCR = 'D' THEN VAMT 
                             ELSE -VAMT 
                           END),
			MTFLED=CONVERT(NUMERIC(18,4),0)  
    FROM  ANGELCOMMODITY.ACCOUNTNCDX.DBO.LEDGER L,  
		   (SELECT DISTINCT PARTY_CODE		
                             FROM   #B_MTF_DATA ) M 
    WHERE  L.VDT <= @SAUDA_DATE 
           AND L.EDT > @SAUDA_DATE + ' 23:59:59' 
           AND L.CLTCODE = PARTY_CODE
    GROUP  BY L.CLTCODE 

	
	INSERT INTO #B_LEDBAL 
    SELECT L.CLTCODE, 
           VDTLEDBAL = SUM(CASE 
                             WHEN DRCR = 'C' THEN VAMT 
                             ELSE -VAMT 
                           END),
			MTFLED=CONVERT(NUMERIC(18,4),0)  
    FROM   ANGELCOMMODITY.ACCOUNTMCDX.DBO.LEDGER L,  
		   (SELECT DISTINCT PARTY_CODE		
                             FROM   #B_MTF_DATA ) M 
    WHERE  L.VDT BETWEEN @SDTCUR AND @LDTCUR 
           AND L.VDT <= @SAUDA_DATE + ' 23:59:59' 
           AND L.CLTCODE = PARTY_CODE
    GROUP  BY L.CLTCODE 

	INSERT INTO #B_LEDBAL 
    SELECT L.CLTCODE, 
           VDTLEDBAL = SUM(CASE 
                             WHEN DRCR = 'D' THEN VAMT 
                             ELSE -VAMT 
                           END),
			MTFLED=CONVERT(NUMERIC(18,4),0)  
    FROM  ANGELCOMMODITY.ACCOUNTMCDX.DBO.LEDGER L,  
		   (SELECT DISTINCT PARTY_CODE		
                             FROM   #B_MTF_DATA ) M 
    WHERE  L.VDT <= @SAUDA_DATE 
           AND L.EDT > @SAUDA_DATE + ' 23:59:59' 
           AND L.CLTCODE = PARTY_CODE
    GROUP  BY L.CLTCODE 	
	
	INSERT INTO #B_LEDBAL 
	SELECT PARTY_CODE, VDTLEDBAL=0, MTFLED=SUM(NETAMT)+MTFLED FROM #MTF_DATA
	GROUP BY PARTY_CODE,MTFLED
	HAVING SUM(NETAMT)+MTFLED > 0 
	 
	DECLARE @MTFCUR		CURSOR,
			@PARTY_CODE	VARCHAR(10),
			@ISIN		VARCHAR(12),
			@POSCUR		CURSOR,
			@QTY		INT,
			@AMT		NUMERIC(18,4),
			@LEDBAL		NUMERIC(18,4),
			@ADJQTY		INT,
			@SCRIP_CD	VARCHAR(12), 
			@SERIES		VARCHAR(3), 
			@BSECODE	VARCHAR(12)

	SET @MTFCUR = CURSOR FOR
	SELECT CLTCODE, VDTLEDBAL=SUM(VDTLEDBAL)+SUM(MTFLED) FROM #B_LEDBAL	
	GROUP BY CLTCODE
	HAVING SUM(VDTLEDBAL)+SUM(MTFLED) > 0 
	ORDER BY CLTCODE 
	OPEN @MTFCUR
	FETCH NEXT FROM @MTFCUR INTO @PARTY_CODE, @LEDBAL
	WHILE @@FETCH_STATUS = 0 
	BEGIN
		IF @LEDBAL > 0 
		BEGIN
			SET @POSCUR = CURSOR FOR 
			SELECT ISIN, QTY, NETAMT, SCRIP_CD, SERIES, BSECODE FROM #MTF_DATA
			WHERE PARTY_CODE = @PARTY_CODE 
			ORDER BY NETAMT DESC 
			OPEN @POSCUR 
			FETCH NEXT FROM @POSCUR INTO @ISIN, @QTY, @AMT, @SCRIP_CD, @SERIES, @BSECODE 
			WHILE @@FETCH_STATUS = 0 
			BEGIN
				IF @AMT <= @LEDBAL 
				BEGIN
					UPDATE #MTF_DATA SET ADJQTY = @QTY
					WHERE PARTY_CODE = @PARTY_CODE 
					AND SCRIP_CD = @SCRIP_CD
					AND SERIES =  @SERIES
					AND BSECODE = @BSECODE
					AND ISIN = @ISIN

					SET @LEDBAL = @LEDBAL - @AMT
				END
				ELSE
				BEGIN
					SET @ADJQTY = FLOOR(@LEDBAL/ (@AMT / @QTY))
					IF @ADJQTY <= @QTY 
					BEGIN
						UPDATE #MTF_DATA SET ADJQTY = @ADJQTY
						WHERE PARTY_CODE = @PARTY_CODE  
						AND SCRIP_CD = @SCRIP_CD
						AND SERIES =  @SERIES
						AND BSECODE = @BSECODE
						AND ISIN = @ISIN
					END
					ELSE
					BEGIN
						SET @ADJQTY = 0 
					END
					SET @LEDBAL = @LEDBAL - (@ADJQTY*(@AMT / @QTY))
				END
				FETCH NEXT FROM @POSCUR INTO @ISIN, @QTY, @AMT, @SCRIP_CD, @SERIES, @BSECODE 
			END 
		END
		FETCH NEXT FROM @MTFCUR INTO @PARTY_CODE, @LEDBAL
	END
	CLOSE @MTFCUR
	DEALLOCATE @MTFCUR 

SELECT CLTCODE, VDTLEDBAL=SUM(VDTLEDBAL),MTFLED=SUM(MTFLED), ADJAMT=CONVERT(NUMERIC(18,4),0) 
INTO #FINAL FROM #B_LEDBAL	
GROUP BY CLTCODE
HAVING SUM(VDTLEDBAL)+SUM(MTFLED) > 0 
ORDER BY CLTCODE 

UPDATE #FINAL SET ADJAMT = M.ADJAMT
FROM (SELECT PARTY_CODE, ADJAMT=SUM(ADJQTY*(NETAMT/QTY)) FROM #MTF_DATA
	  GROUP BY PARTY_CODE )M
WHERE M.PARTY_CODE =#FINAL.CLTCODE

SELECT * FROM #FINAL WHERE ADJAMT > 0
ORDER BY CLTCODE

SELECT *FROM #MTF_DATA
WHERE PARTY_CODE IN (SELECT CLTCODE FROM #FINAL
WHERE ADJAMT > 0)
ORDER BY PARTY_CODE

GO
