-- Object: PROCEDURE dbo.RPT_MTR_MTFFILE_NEW_BSE_BKP_05FEB2026_SRE_43657
-- Server: 10.253.33.91 | DB: MTFTRADE
--------------------------------------------------










CREATE PROC [dbo].[RPT_MTR_MTFFILE_NEW_BSE_BKP_05FEB2026_SRE_43657]      
(      
	@SAUDA_DATE VARCHAR(11),
	@FLAG		INT = 0,
	@PARTY_CODE	VARCHAR(10) = ''      
)      
AS      

/*
DELETE FROM ASIANFILEBATCHNO WHERE fldFileDate LIKE 'JAN  8 2021%'
EXEC [RPT_MTR_MTFFILE_NEW] 'FEB  3 2025'  
*/
DECLARE @PREVDATE	VARCHAR(11),     
		@BATCHNO	INT,
		@SDTCUR		DATETIME,
		@LDTCUR		DATETIME,
		@NONFNO		INT,
		@FNO		INT,
		@EDT		DATETIME
      
SELECT	@SDTCUR = SDTCUR, @LDTCUR = LDTCUR FROM ACCOUNT.DBO.PARAMETER(NOLOCK) 
WHERE	@SAUDA_DATE BETWEEN SDTCUR AND LDTCUR  

SELECT	@EDT = LEFT(FUNDS_PAYIN,11) FROM [ANGELBSECM].BSEDB_AB.DBO.SETT_MST SM(NOLOCK)
WHERE	START_DATE BETWEEN @SAUDA_DATE AND @SAUDA_DATE + ' 23:59'
		AND SETT_TYPE IN ('RD')

SELECT @BATCHNO = 0    
    
SELECT @BATCHNO = ISNULL(MAX(FLDBATCHNO),0) FROM ASIANFILEBATCHNO    
WHERE FLDFILENO = 'MB'    
AND FLDFILEDATE = @SAUDA_DATE  

SELECT @PREVDATE = ISNULL(MAX(SAUDA_DATE),'APR  1 2017') FROM       
TBL_PRODUCT_POSITION WHERE SAUDA_DATE < @SAUDA_DATE    

CREATE TABLE #REPORT    
(    
	SNO INT IDENTITY(1,1),    
	DATA VARCHAR(5000)    
)   

SELECT SAUDA_DATE=CONVERT(VARCHAR,SAUDA_DATE,103),      
MEMBERCODE, SCRIP_CD, SERIES, PARTY_CODE=UPPER(P.PARTY_CODE),LONG_NAME=UPPER(LONG_NAME), 
PAN_GIR_NO=(CASE WHEN ISNULL(PAN_GIR_NO,'') = '' THEN P.PARTY_CODE ELSE ISNULL(PAN_GIR_NO,'') END),
BODQTY,    
BODVALUE,     
FRESHBQTY,      
FRESHBUY,      
FRESHSQTY,    
FRESHSELL,
NETQTY,      
NETAMOUNT,
M_BODQTY,
M_BODVALUE,
M_FRESHBQTY,
M_FRESHBUY,
M_FRESHSQTY,
M_FRESHSELL,
M_NETQTY,
M_NETAMOUNT,
EXCHANGE,
ISIN ,
DENSE_RANK() over ( order by MEMBERCODE,P.PARTY_CODE,SCRIP_CD,EXCHANGE) as nRowID
INTO #NSERPT
FROM TBL_MTR_REPORTING P, MSAJAG.DBO.CLIENT_DETAILS C (NOLOCK),[ANGELBSECM].BSEDB_AB.DBO.OWNER       
WHERE SAUDA_DATE = @SAUDA_DATE
AND C.CL_CODE = P.PARTY_CODE         
AND P.PARTY_CODE = (CASE WHEN @PARTY_CODE = '' THEN P.PARTY_CODE ELSE @PARTY_CODE END) 
AND (BODQTY + FRESHBQTY + FRESHSQTY) > 0 
--and scrip_cd='LAURUSLABS'

IF (SELECT ISNULL(COUNT(1),0) FROM #NSERPT ) <= 0
BEGIN
	SELECT * FROM #REPORT
	RETURN
END

	ALTER	TABLE #NSERPT
	ADD		VARMARGIN		NUMERIC(18,4),
			HAIRCUT			NUMERIC(18,4),
			EXPOSURE_AMT	NUMERIC(18,4),
			EXPOSURE_QTY	INT,
			CORP_QTY		INT,
			CORP_AMT		NUMERIC(18,4)


	UPDATE	#NSERPT
	SET		VARMARGIN = 0,
			HAIRCUT = 0,
			EXPOSURE_QTY = 0,
			CORP_QTY = 0,
			CORP_AMT = 0


	SELECT	@NONFNO = NONFNO, @FNO = FNO FROM TBL_MTF_MULTIPLIER
	WHERE	@SAUDA_DATE BETWEEN FROMDATE AND TODATE

	SELECT V.* INTO #B_NSE_VAR FROM MSAJAG.DBO.VARDETAIL V, 
	MSAJAG.DBO.VARCONTROL C
	WHERE C.RECDATE >= @SAUDA_DATE aND c.REcDATE <= @SAUDA_DATE + ' 23:59'
	AND C.DETAILKEY = V.DETAILKEY
	AND SERIES NOT IN ('BO')
	AND ISIN IN (SELECT DISTINCT ISIN FROM #NSERPT)

	SELECT V.* INTO  #BSE_VAR FROM [ANGELBSECM].BSEDB_AB.DBO.VARDETAIL V
	WHERE V.FDATE >= @SAUDA_DATE aND v.FDATE <= @SAUDA_DATE + ' 23:59'

    SELECT V.* INTO #B_BSE_VAR FROM  #BSE_VAR V
	WHERE  ISIN IN (SELECT ISIN FROM #NSERPT)

	CREATE INDEX #NISIN ON #B_NSE_VAR
	(ISIN )
	CREATE INDEX #BISIN ON #B_BSE_VAR
	(ISIN )

    UPDATE	#NSERPT 
    SET		VARMARGIN = M.APPVAR,
			--HAIRCUT = (CASE WHEN FOFLAG = 1 THEN M.APPVAR + @FNO * SECSPECVAR ELSE M.APPVAR + @NONFNO * SECSPECVAR END)
			HAIRCUT = M.APPVAR + @NONFNO * SECSPECVAR
    FROM	#B_NSE_VAR M
    WHERE	M.ISIN = #NSERPT.ISIN 
	AND		HAIRCUT = 0

	UPDATE	#NSERPT 
	SET		VARMARGIN = M.MARGIN,
			--HAIRCUT = (CASE WHEN FOFLAG = 1 THEN M.MARGIN + 3 * ELM ELSE M.MARGIN + 5 * ELM END)
			HAIRCUT = M.MARGIN + @NONFNO * ELM
	FROM	#B_BSE_VAR M
	WHERE	M.ISIN = #NSERPT.ISIN 
	AND		HAIRCUT = 0

	/** --- NEW CHANGES DONE ON 09/07/2025 --- **/
	
	UPDATE	#NSERPT 
	SET		EXPOSURE_AMT = (M_FRESHBUY-(M_FRESHBUY/100*VARMARGIN))/HAIRCUT*100
	WHERE	M_FRESHBQTY > 0 AND M_FRESHBUY > 0
			

	UPDATE	#NSERPT 
	SET		EXPOSURE_QTY = FLOOR(EXPOSURE_AMT/(M_FRESHBUY/M_FRESHBQTY))
	WHERE	M_FRESHBQTY > 0 AND M_FRESHBUY > 0

	/** --- NEW CHANGES DONE ON 09/07/2025 --- **/


	/** --- NEW CHANGES DONE ON 12/07/2025 FOR CA PROCESS ---  **/
	---SRE-41130
	UPDATE	#NSERPT 
	SET		--CORP_QTY = ISNULL(P.QTY,0),
			CORP_AMT = P.NETAMT,
			CORP_QTY = ABS(ISNULL(P.QTY,0)-(#NSERPT.BODQTY)),
			--CORP_AMT = (ISNULL(P.QTY,0)-(#NSERPT.BODQTY))*ROUND(P.NETAMT/#NSERPT.BODQTY,4),
			FRESHBQTY = FRESHBQTY-ISNULL(P.QTY,0),      
			FRESHBUY = FRESHBUY-ISNULL(P.NETAMT,0),
			FRESHSQTY = (CASE WHEN FRESHSQTY-ISNULL(P.QTY,0) > 0 THEN FRESHSQTY-ISNULL(P.QTY,0) ELSE 0 END),    
			FRESHSELL = (CASE WHEN FRESHSELL-P.NETAMT > 0 THEN FRESHSELL-P.NETAMT ELSE 0 END)
	FROM	TBL_PRODUCT_POS_ADJUST_BUY P(NOLOCK)
	WHERE	P.SAUDA_DATE = @SAUDA_DATE 
			AND P.PARTY_CODE = #NSERPT.PARTY_CODE
			AND P.SCRIP_CD = #NSERPT.SCRIP_CD
			AND P.ISIN = #NSERPT.ISIN
			AND ADDED_BY IN ('SPLIT','BONUS')
			AND ISNULL(P.QTY,0) > 0
			AND #NSERPT.BODQTY > 0
			AND EXCHANGE =  TRANSTYPE


    UPDATE	#NSERPT
			SET CORP_QTY = CORP_QTY - ISNULL(P.QTY,0)
	FROM	TBL_PRODUCT_POS_ADJUST P(NOLOCK)
	WHERE	P.SAUDA_DATE = @SAUDA_DATE 
			AND P.PARTY_CODE = #NSERPT.PARTY_CODE
			AND P.SCRIP_CD = #NSERPT.SCRIP_CD
			--AND P.ISIN = #NSERPT.ISIN
			AND ADDED_BY IN ('SPLIT','BONUS')
			AND ISNULL(P.QTY,0) > 0
			AND #NSERPT.CORP_QTY > 0
			AND EXCHANGE =  TRANSTYPE
			AND 1=2

---SRE-41130 END

	UPDATE	#NSERPT
	SET		NETQTY = BODQTY+FRESHBQTY-FRESHSQTY,      
			NETAMOUNT = BODVALUE+FRESHBUY-FRESHSELL
	WHERE	CORP_QTY > 0

	/** --- NEW CHANGES DONE ON 09/07/2025 --- **/


INSERT INTO ASIANFILEBATCHNO    
SELECT 'MB', @BATCHNO, @SAUDA_DATE, GETDATE()    
	    
SET @BATCHNO = @BATCHNO + 1 

INSERT INTO #REPORT     
SELECT DATA = '10,MTR,' + LTRIM(RTRIM(MEMBERCODE)) + ',' +     
REPLACE(CONVERT(VARCHAR,CONVERT(DATETIME,@SAUDA_DATE),103),'/','') + ',' +    
+ RIGHT('00' + CONVERT(VARCHAR,@BATCHNO),2) + ',1,' 
--+ CONVERT(VARCHAR,COUNT(1)) 
+ CONVERT(VARCHAR(10),max(nRowID))
+',' + CONVERT(VARCHAR,CONVERT(NUMERIC(18,2),ROUND(SUM(NETAMOUNT),2))) 
+',' + CONVERT(VARCHAR,CONVERT(NUMERIC(18,2),ROUND(SUM(M_FRESHBUY),2)))
+',' + CONVERT(VARCHAR,CONVERT(NUMERIC(18,2),ROUND(SUM(NETAMOUNT-M_FRESHBUY),2)))
FROM #NSERPT    
GROUP BY MEMBERCODE  
    
INSERT INTO #REPORT    
SELECT DATA = '30,SELF,01,' +     
CONVERT(VARCHAR,CONVERT(NUMERIC(18,2),ROUND(SUM(NETAMOUNT-M_FRESHBUY),2)))    
FROM #NSERPT   
GROUP BY #NSERPT.MEMBERCODE   

INSERT INTO #REPORT    
SELECT DATA = '20,' + REPLACE(LTRIM(RTRIM(LONG_NAME)),',','') + ',' +     
LTRIM(RTRIM(PAN_GIR_NO)) + ',' + 
LTRIM(RTRIM(UPPER(SCRIP_CD))) +',' + 
LTRIM(RTRIM(UPPER(SERIES))) +',' +   
LTRIM(RTRIM(UPPER(ISIN))) +',' +   
CONVERT(VARCHAR,SUM(BODQTY)) + ',' +     
CONVERT(VARCHAR,CONVERT(NUMERIC(18,2),ROUND(SUM(BODVALUE),2))) + ',' +      
CONVERT(VARCHAR,SUM(FRESHBQTY)) + ',' +    
CONVERT(VARCHAR,CONVERT(NUMERIC(18,2),ROUND(SUM(FRESHBUY),2))) + ',' +    
CONVERT(VARCHAR,SUM(FRESHSQTY)) + ',' +    
CONVERT(VARCHAR,CONVERT(NUMERIC(18,2),ROUND(SUM(FRESHSELL),2))) + ','  +     
CONVERT(VARCHAR,SUM(CORP_QTY)) + ',' + ---Corporate action Quantity
CONVERT(VARCHAR,SUM(NETQTY + CORP_QTY)) + ',' +     
CONVERT(VARCHAR,CONVERT(NUMERIC(18,2),ROUND(SUM(BODVALUE + FRESHBUY - FRESHSELL),2))) + ',' + 
CONVERT(VARCHAR,SUM(M_FRESHBQTY)) + ',' +

/*--- being the sell payin closing adj amount diff of FIFO vs Avg Rate   ---*/
CASE 
	WHEN SUM(NETQTY)=SUM(M_FRESHBQTY) THEN CONVERT(VARCHAR,CONVERT(NUMERIC(18,2),ROUND(SUM((BODVALUE + FRESHBUY - FRESHSELL)),2))) 
	ELSE CONVERT(VARCHAR,CONVERT(NUMERIC(18,2),ROUND(SUM(M_FRESHBUY),2))) 
END + ',' +
/*--- being the sell payin closing adj amount diff of FIFO vs Avg Rate   ---*/
CONVERT(VARCHAR,SUM(NETQTY-M_FRESHBQTY+CORP_QTY)) + ',' +
--CONVERT(VARCHAR,SUM((CASE WHEN M_FRESHBQTY > 0 THEN (NETQTY-M_FRESHBQTY) ELSE 0 END))) + ',' +   

/*--- being the sell payin closing adj amount diff of FIFO vs Avg Rate   ---*/
CONVERT(VARCHAR,CONVERT(NUMERIC(18,2),ROUND((SUM(BODVALUE + FRESHBUY - FRESHSELL)-
CASE 
	WHEN SUM(NETQTY)=SUM(M_FRESHBQTY) THEN SUM(BODVALUE + FRESHBUY - FRESHSELL)
	ELSE SUM(M_FRESHBUY)
END 
),2))) + ',' +
/*--- being the sell payin closing adj amount diff of FIFO vs Avg Rate   ---*/

--CONVERT(VARCHAR,CONVERT(NUMERIC(18,2),ROUND(SUM(CASE WHEN M_FRESHBQTY > 0 THEN (BODVALUE + FRESHBUY - FRESHSELL)-(M_FRESHBUY) ELSE 0 END),2))) + ',' +     
--CONVERT(VARCHAR,SUM((CASE WHEN M_FRESHBQTY > 0 THEN (NETQTY-M_FRESHBQTY) ELSE 0 END))) + ',' + 'N,'+ RIGHT(EXCHANGE,3)
--CONVERT(VARCHAR,SUM((CASE WHEN M_FRESHBQTY > 0 THEN (EXPOSURE_QTY) ELSE 0 END))) 
CONVERT(VARCHAR,CONVERT(NUMERIC(20,0),PRADNYA.DBO.FNMIN(SUM(NETQTY-M_FRESHBQTY+CORP_QTY),SUM((CASE WHEN M_FRESHBQTY > 0 THEN (EXPOSURE_QTY) ELSE 0 END))))) 
+ ',' + 'N,'+ RIGHT(EXCHANGE,3)
FROM #NSERPT    
GROUP BY MEMBERCODE,LONG_NAME, PARTY_CODE, SCRIP_CD, SERIES, PAN_GIR_NO, RIGHT(EXCHANGE,3), LTRIM(RTRIM(UPPER(ISIN))) 

SELECT H.PARTY_CODE, LONG_NAME, 
PAN_GIR_NO=(CASE WHEN ISNULL(PAN_GIR_NO,'') = '' THEN H.PARTY_CODE ELSE ISNULL(PAN_GIR_NO,'') END),
SCRIP_CD, SERIES, QTY = SUM(QTY), AMOUNT = CONVERT(NUMERIC(18,2),SUM(QTY*CL_RATE-QTY*CL_RATE*HAIRCUT/100)),
CAT = 'N', EXCHG = (CASE WHEN SERIES = 'BSE' OR SERIES = '' THEN 'BSE' ELSE 'NSE' END),
CASHCOLL = CONVERT(NUMERIC(18,2),0),
ISIN = ISNULL(H.ISIN,''),
CASH_EQV_FLAG = 0
INTO #HOLD
FROM TBL_PRODUCT_HOLD_DATA H, MSAJAG.DBO.CLIENT_DETAILS C (NOLOCK)
WHERE SAUDA_DATE = @SAUDA_DATE  
AND   HOLDFLAG = 'MTFCOLL'
AND SETT_NO <> 'BSE'
AND h.pARTY_cODE iN ( SELECT PARTY_CODE FROM #NSERPT WHERE NETQTY > 0 )
AND   C.CL_CODE = H.PARTY_CODE
GROUP BY H.PARTY_CODE, LONG_NAME, 
PAN_GIR_NO,SCRIP_CD, SERIES, ISNULL(H.ISIN,'')

DELETE FROM #HOLD WHERE SCRIP_CD=''

if convert(datetime,@sauda_date) = convert(datetime,'apr  2 2019')
begin
	TRUNCATE TABLE #HOLD
	INSERT INTO #HOLD
	SELECT H.PARTY_CODE, LONG_NAME, 
	PAN_GIR_NO=(CASE WHEN ISNULL(PAN_GIR_NO,'') = '' THEN H.PARTY_CODE ELSE ISNULL(PAN_GIR_NO,'') END),
	SCRIP_CD, SERIES, QTY = SUM(QTY), AMOUNT = CONVERT(NUMERIC(18,2),SUM(QTY*CL_RATE-QTY*CL_RATE*HAIRCUT/100)),
	CAT = 'N', EXCHG = (CASE WHEN SERIES = 'BSE' OR SERIES = '' THEN 'BSE' ELSE 'NSE' END),
	CASHCOLL = CONVERT(NUMERIC(18,2),0),
	ISIN = ISNULL(H.ISIN,'')
	FROM TBL_PRODUCT_HOLD_DATA_PROV H, MSAJAG.DBO.CLIENT_DETAILS C (NOLOCK)
	WHERE SAUDA_DATE = @SAUDA_DATE   
	AND SETT_NO <> 'BSE'
	AND H.PARTY_CODE IN (SELECT PARTY_CODE FROM #NSERPT WHERE NETQTY > 0 )
	AND   C.CL_CODE = H.PARTY_CODE
	GROUP BY H.PARTY_CODE, LONG_NAME, 
	PAN_GIR_NO, SCRIP_CD, SERIES, ISNULL(H.ISIN,'')
end

--UPDATE	#HOLD 
--SET		CASH_EQV_FLAG = 1
--FROM	MSAJAG..TBL_LIQUID_SCRIP S (NOLOCK)
--WHERE	LTRIM(RTRIM(S.ISIN)) = LTRIM(RTRIM(#HOLD.ISIN))
--		AND @SAUDA_DATE BETWEEN EFF_FROM_DATE AND EFF_TO_DATE 

SELECT PARTY_CODE, CASHCOLL=(CASE WHEN SUM(NETAMT) + MTFLEDBAL > 0 
								  THEN SUM(NETAMT) + MTFLEDBAL
								  ELSE 0
						     END),
				   MTFNONCASHCOLLATERAL = CONVERT(NUMERIC(18,2),0)
INTO #COLLCASH
FROM TBL_MTF_DATA
WHERE SAUDA_DATE = @SAUDA_DATE
GROUP BY PARTY_CODE, MTFLEDBAL

INSERT INTO #COLLCASH
SELECT DISTINCT PARTY_CODE, CASHCOLL = 0, MTFNONCASHCOLLATERAL = 0 FROM #HOLD
WHERE NOT EXISTS (SELECT PARTY_CODE FROM #COLLCASH WHERE #COLLCASH.PARTY_CODE = #HOLD.PARTY_CODE)

UPDATE #COLLCASH SET MTFNONCASHCOLLATERAL = NONCASH
FROM (SELECT PARTY_CODE, NONCASH = SUM(AMOUNT)
	  FROM #HOLD
	  GROUP BY PARTY_CODE) C
WHERE C.PARTY_CODE = #COLLCASH.PARTY_CODE

/*
UPDATE #HOLD SET CASHCOLL = C.CASHCOLL
FROM #COLLCASH C
WHERE C.PARTY_CODE = #HOLD.PARTY_CODE
*/


SELECT	PARTY_CODE, 
		CASHCOLL_AMT=CONVERT(NUMERIC(18,2),(CASE WHEN SUM(NETAMT) + MTFLEDBAL > 0 
				THEN SUM(NETAMT) + MTFLEDBAL
				ELSE 0
			END)),
		CASHPAYIN_AMT = CONVERT(NUMERIC(18,4),0),
		COLL_CASH_EQV_AMT = CONVERT(NUMERIC(18,4),0),
		COLL_CASH_NONEQV_AMT = CONVERT(NUMERIC(18,4),0)
INTO	#CASHCOLLBAL
FROM	TBL_MTF_DATA
WHERE	SAUDA_DATE = @SAUDA_DATE 
		AND PARTY_CODE = (CASE WHEN @PARTY_CODE = '' THEN PARTY_CODE ELSE @PARTY_CODE END)
GROUP BY
		PARTY_CODE, MTFLEDBAL


--INSERT	INTO #CASHCOLLBAL
--SELECT	CLTCODE, 
--		CASHCOLL_AMT = CONVERT(NUMERIC(18,2),SUM(L.VAMT)),
--		CASHPAYIN_AMT = CONVERT(NUMERIC(18,2),0),
--		COLL_CASH_EQV_AMT = CONVERT(NUMERIC(18,2),0),
--		COLL_CASH_NONEQV_AMT = CONVERT(NUMERIC(18,2),0)
--FROM	MTF_CASH_COLL_LEDGER L(NOLOCK)
--WHERE	L.VDT BETWEEN @SDTCUR AND @LDTCUR 
--		AND L.VDT <= @PREVDATE + ' 23:59:59' 
--		AND DRCR = 'C'
--		AND CLTCODE = (CASE WHEN @PARTY_CODE = '' THEN CLTCODE ELSE @PARTY_CODE END)
--GROUP BY
--		CLTCODE


--INSERT	INTO #CASHCOLLBAL
--SELECT	CLTCODE, 
--		CASHCOLL_AMT = CONVERT(NUMERIC(18,4),0),
--		CASHPAYIN_AMT = CONVERT(NUMERIC(18,4),SUM(CASE WHEN DRCR='C' THEN L.VAMT ELSE -L.VAMT END)),
--		COLL_CASH_EQV_AMT = CONVERT(NUMERIC(18,4),0),
--		COLL_CASH_NONEQV_AMT = CONVERT(NUMERIC(18,4),0)
--FROM	MTF_CASH_PAYIN_LEDGER L(NOLOCK)
--WHERE	L.VDT BETWEEN @SDTCUR AND @LDTCUR 
--		AND L.VDT <= @SAUDA_DATE + ' 23:59:59' 
--		AND L.EDT BETWEEN @SDTCUR AND @SAUDA_DATE + ' 23:59:59' 
--		AND CLTCODE = (CASE WHEN @PARTY_CODE = '' THEN CLTCODE ELSE @PARTY_CODE END)
--		AND NARRATION = 'MTF PAYIN'
--GROUP BY
--		CLTCODE


INSERT	INTO #CASHCOLLBAL
SELECT	PARTY_CODE, 
		CASHCOLL_AMT = CONVERT(NUMERIC(18,4),0),
		CASHPAYIN_AMT = SUM(M_FRESHBUY),
		COLL_CASH_EQV_AMT = CONVERT(NUMERIC(18,4),0),
		COLL_CASH_NONEQV_AMT = CONVERT(NUMERIC(18,4),0)
FROM	TBL_MTR_REPORTING L(NOLOCK)
WHERE	SAUDA_DATE BETWEEN @SAUDA_DATE AND @SAUDA_DATE + ' 23:59:59' 
		AND PARTY_CODE = (CASE WHEN @PARTY_CODE = '' THEN PARTY_CODE ELSE @PARTY_CODE END)
		AND (BODQTY + FRESHBQTY + FRESHSQTY) > 0
GROUP BY
		PARTY_CODE


--SELECT	CLTCODE, 
--		CASHCOLL_AMT = CONVERT(NUMERIC(18,4),0),
--		CASHPAYIN_AMT = CONVERT(NUMERIC(18,4),SUM(CASE WHEN DRCR='C' THEN L.VAMT ELSE -L.VAMT END)),
--		COLL_CASH_EQV_AMT = CONVERT(NUMERIC(18,4),0),
--		COLL_CASH_NONEQV_AMT = CONVERT(NUMERIC(18,4),0)
--FROM	MTF_CASH_PAYIN_LEDGER L(NOLOCK)
--WHERE	L.VDT BETWEEN @SDTCUR AND @LDTCUR 
--		AND L.VDT <= @SAUDA_DATE + ' 23:59:59' 
--		AND L.EDT BETWEEN @SDTCUR AND @SAUDA_DATE + ' 23:59:59' 
--		AND CLTCODE = (CASE WHEN @PARTY_CODE = '' THEN CLTCODE ELSE @PARTY_CODE END)
--		AND NARRATION = 'MTF PAYIN'
--GROUP BY
--		CLTCODE


SELECT	PARTY_CODE,
		PAYIN_AMT = SUM(PAYIN_AMT)
INTO	#PAYIN_COLL
FROM	(
		SELECT	PARTY_CODE = CLTCODE, 
				PAYIN_AMT = ISNULL(SUM(CASE WHEN DRCR='D' THEN -VAMT ELSE VAMT END),0)
		FROM	LEDGER P(NOLOCK)
		WHERE	P.VDT BETWEEN @SDTCUR AND @LDTCUR
				AND P.VDT >= @SAUDA_DATE  AND P.VDT <= @SAUDA_DATE + ' 23:59' 
				AND P.VTYP = '66'
				AND P.EDT BETWEEN @SDTCUR AND @EDT + ' 23:59'
		GROUP BY
				CLTCODE

		UNION

		SELECT	PARTY_CODE = CLTCODE, 
				PAYIN_AMT = ISNULL(SUM(CASE WHEN DRCR='D' THEN -VAMT ELSE VAMT END),0)
		FROM	LEDGER P(NOLOCK)
		WHERE	P.VDT BETWEEN @SDTCUR AND @LDTCUR
				AND P.VDT >= @SAUDA_DATE  AND P.VDT <= @SAUDA_DATE + ' 23:59' 
				AND P.VTYP = '67'
				AND P.EDT BETWEEN @SDTCUR AND @SAUDA_DATE + ' 23:59'
		GROUP BY
				CLTCODE
		) A
GROUP BY
		PARTY_CODE


INSERT	INTO #CASHCOLLBAL
SELECT	PARTY_CODE, 
		CASHCOLL_AMT = CONVERT(NUMERIC(18,4),0),
		CASHPAYIN_AMT = CONVERT(NUMERIC(18,4),0),
		COLL_CASH_EQV_AMT = CONVERT(NUMERIC(18,4),SUM(CASE WHEN CASH_EQV_FLAG=1 THEN L.AMOUNT ELSE 0 END)),
		COLL_CASH_NONEQV_AMT = CONVERT(NUMERIC(18,4),SUM(CASE WHEN CASH_EQV_FLAG=0 THEN L.AMOUNT ELSE 0 END))
FROM	#HOLD L(NOLOCK)
GROUP BY
		PARTY_CODE


SELECT	PARTY_CODE, 
		CASHCOLL_AMT = SUM(CASHCOLL_AMT),
		CASHPAYIN_AMT = SUM(CASHPAYIN_AMT),
		COLL_CASH_EQV_AMT = SUM(COLL_CASH_EQV_AMT),
		COLL_CASH_NONEQV_AMT = SUM(COLL_CASH_NONEQV_AMT)
INTO	#CASHCOLLBAL_NEW
FROM	#CASHCOLLBAL
GROUP BY
		PARTY_CODE

--UPDATE	#CASHCOLLBAL_NEW
--SET		CASHCOLL_AMT = CASHCOLL_AMT + ISNULL(#PAYIN_COLL.PAYIN_AMT,0)
--FROM	#PAYIN_COLL
--WHERE	#CASHCOLLBAL_NEW.PARTY_CODE = #PAYIN_COLL.PARTY_CODE

--SELECT '#CASHCOLLBAL',* FROM #CASHCOLLBAL WHERE PARTY_CODE='AA0895'
--SELECT '#PAYIN_COLL',* FROM #PAYIN_COLL WHERE PARTY_CODE='AA0895'
--SELECT '#CASHCOLLBAL_NEW',* FROM #CASHCOLLBAL_NEW WHERE PARTY_CODE='AA0895'
--ORDER BY PARTY_CODE


INSERT	INTO #REPORT  
SELECT	DATA = '40' 
		+ ',' + CONVERT(VARCHAR,CONVERT(NUMERIC(18,2),ROUND(SUM(CASHCOLL_AMT),2)))
		+ ',' + CONVERT(VARCHAR,CONVERT(NUMERIC(18,2),ROUND(SUM(COLL_CASH_EQV_AMT),2)))
		+ ',' + CONVERT(VARCHAR,CONVERT(NUMERIC(18,2),ROUND(SUM(COLL_CASH_NONEQV_AMT),2)))
FROM	#CASHCOLLBAL_NEW C(NOLOCK)


/*
INSERT INTO #REPORT  
SELECT DATA = '40,' 
	        + (CASE WHEN CONVERT(VARCHAR,CONVERT(NUMERIC(18,2), 
			             ISNULL(SUM(CASHCOLL),0))) = '0' 
					THEN '0.00'
					ELSE CONVERT(VARCHAR,CONVERT(NUMERIC(18,2), 
			             ISNULL(SUM(CASHCOLL),0)))
			   END) 
			+ ',0.00,' 
		    + (CASE WHEN CONVERT(VARCHAR,CONVERT(NUMERIC(18,2),SUM(MTFNONCASHCOLLATERAL))) = '0'
					THEN '0.00'
					ELSE CONVERT(VARCHAR,CONVERT(NUMERIC(18,2),SUM(MTFNONCASHCOLLATERAL)))
			   END)
FROM 
(
	SELECT PARTY_CODE, CASHCOLL, MTFNONCASHCOLLATERAL = SUM(MTFNONCASHCOLLATERAL) 
	FROM   #COLLCASH
	GROUP BY PARTY_CODE, CASHCOLL
) A
*/

INSERT INTO #REPORT  
SELECT DATA = '50,' 
+ REPLACE(LTRIM(RTRIM(LONG_NAME)),',','') 
+ ',' + UPPER(PAN_GIR_NO )
+ ',' + SCRIP_CD 
+ ',' + SERIES 
+ ',' + LTRIM(RTRIM(UPPER(ISIN))) 
+ ',' + CONVERT(VARCHAR,QTY) 
+ ',' + CONVERT(VARCHAR,CONVERT(NUMERIC(18,2),ROUND(AMOUNT,2)))
+ ',' + CAT 
+ ',' + EXCHG
FROM #HOLD WHERE AMOUNT <>0 


INSERT INTO #REPORT  
SELECT DATA = '60,' 
+ REPLACE(LTRIM(RTRIM(LONG_NAME)),',','') 
+ ',' + UPPER(PAN_GIR_NO) 
+ ',' + CONVERT(VARCHAR,CONVERT(NUMERIC(18,2),ROUND(SUM(CASHCOLL_AMT),2))) 
+ ',' + CONVERT(VARCHAR,CONVERT(NUMERIC(18,2),ROUND(SUM(CASHPAYIN_AMT),2)))
+ ',' + CONVERT(VARCHAR,CONVERT(NUMERIC(18,2),ROUND(SUM(CASHCOLL_AMT-CASHPAYIN_AMT),2))) 
FROM	#CASHCOLLBAL_NEW C, MSAJAG..CLIENT_DETAILS CD(NOLOCK)
WHERE	C.PARTY_CODE = CD.CL_CODE
GROUP BY
		REPLACE(LTRIM(RTRIM(LONG_NAME)),',',''),
		PAN_GIR_NO
--HAVING	SUM(CASHCOLL_AMT+CASHPAYIN_AMT) <> 0
HAVING	SUM(CASHCOLL_AMT+CASHPAYIN_AMT) <> 0

INSERT INTO #REPORT
SELECT DATA = 'I hereby confirm that my exposure towards the margin trading facility has not exceeded the borrowed funds (if any) and 50% of my networth.'

SELECT FILENAME = LTRIM(RTRIM('MTR_' + REPLACE(CONVERT(VARCHAR,CONVERT(DATETIME,@SAUDA_DATE),103),'/','')   
				+ '.T' + RIGHT('00' + CONVERT(VARCHAR,@BATCHNO),2))),    
DATA = LTRIM(RTRIM((DATA))) FROM #REPORT    
ORDER BY SNO

GO
