-- Object: PROCEDURE dbo.PROC_PRODUCT_BUY_ADJUST_NEWMTF_BAK_0902206
-- Server: 10.253.33.91 | DB: MTFTRADE
--------------------------------------------------









-- EXEC PROC_PRODUCT_BUY_ADJUST_NEWMTF 'DEC 10 2025'

CREATE PROC [dbo].[PROC_PRODUCT_BUY_ADJUST_NEWMTF_BAK_0902206] (@SAUDA_DATE VARCHAR(11), @flag int = 0 ) 
AS  
    DECLARE @PAYIN_DATE VARCHAR(11),
			@SDTCUR	DATETIME,
			@LDTCUR	DATETIME,
			@NONFNO	INT,
			@FNO	INT,
			@PREV_DATE varchar(11),
			@MTFCOLLVAR INT	

	SET NOCOUNT ON
	
	---Select * from TBL_MTF_MULTIPLIER

	SELECT @PREV_DATE = left(ISNULL(MAX(SYSDATE),@SAUDA_DATE),11) FROM   MSAJAG.DBO.CLOSING C 
	WHERE SYSDATE <= @SAUDA_DATE 

	SELECT @NONFNO = NONFNO, @FNO = FNO, @MTFCOLLVAR = MTFCOLLVAR FROM TBL_MTF_MULTIPLIER
	WHERE @SAUDA_DATE BETWEEN FROMDATE AND TODATE

	DECLARE  @PREV_DATE_NEW varchar(11)
   

IF (CONVERT(DATETIME,@SAUDA_DATE,109) >= 'JUN 30 2025')

BEGIN
              SET @PREV_DATE_NEW = @SAUDA_DATE
END
         ELSE
BEGIN
              SET @PREV_DATE_NEW = @PREV_DATE
END


	SELECT @SDTCUR = SDTCUR, @LDTCUR = LDTCUR FROM ACCOUNT.DBO.PARAMETER 
	WHERE @SAUDA_DATE BETWEEN SDTCUR AND LDTCUR  

	SELECT  PARTY_CODE, AMOUNT = SUM(NETAMT), SANC_LIM = CONVERT(NUMERIC(18,0),0)
	INTO #B_PFVALUE
	FROM  TBL_PRODUCT_POSITION 
    WHERE SAUDA_DATE <= @SAUDA_DATE 
           AND ADJUST_DATE > @SAUDA_DATE 
           AND SELL_BUY = 1
	GROUP BY PARTY_CODE

	UPDATE #B_PFVALUE SET SANC_LIM = SANCTIONED_AMT
	FROM TBLCLIENTMARGIN P
	WHERE P.PARTY_CODE = #B_PFVALUE.PARTY_CODE
	AND @SAUDA_DATE BETWEEN FROM_DATE AND TO_DATE

	DELETE FROM #B_PFVALUE
	--WHERE (AMOUNT <= SANC_LIM OR SANC_LIM = -1)

	DECLARE @PFCUR		CURSOR,
			@PARTY_CODE	VARCHAR(10),
			@AMOUNT		NUMERIC(18,4),
			@BUYCUR		CURSOR,
			@SNO		INT,
			@ISIN		VARCHAR(12),
			@QTY		INT,
			@NETAMT		NUMERIC(18,4),
			@ADJRATE	NUMERIC(18,4),
			@ADJQTY		INT

	SET @PFCUR = CURSOR FOR
	SELECT PARTY_CODE, AMOUNT = AMOUNT - SANC_LIM
	FROM #B_PFVALUE
	ORDER BY PARTY_CODE
	OPEN @PFCUR
	FETCH NEXT FROM @PFCUR INTO @PARTY_CODE, @AMOUNT
	WHILE @@FETCH_STATUS = 0
	BEGIN
		SET @BUYCUR = CURSOR FOR
		SELECT SNO, ISIN, QTY, NETAMT FROM TBL_PRODUCT_POSITION
		WHERE SAUDA_DATE = @SAUDA_DATE AND PARTY_CODE = @PARTY_CODE
		AND ADJUST_DATE > @SAUDA_DATE AND QTY > 0 and sett_no <> '2000000'
		ORDER BY NETAMT DESC
		OPEN @BUYCUR
		FETCH NEXT FROM @BUYCUR INTO @SNO, @ISIN, @QTY, @NETAMT
		WHILE @@FETCH_STATUS = 0
		BEGIN 
			IF @AMOUNT > 0 
			BEGIN
				IF @AMOUNT >= @NETAMT
				BEGIN
					UPDATE TBL_PRODUCT_POSITION SET QTY = 0, NETAMT = 0, MKTAMT = 0 
					WHERE SNO = @SNO

					SET @AMOUNT = @AMOUNT - @NETAMT
				END	
				ELSE
				BEGIN
					SET @ADJRATE = @NETAMT / @QTY
					SET @ADJQTY = CEILING(@AMOUNT / @ADJRATE)
					SET @ADJQTY = @QTY - @ADJQTY
					
					UPDATE TBL_PRODUCT_POSITION SET QTY = @ADJQTY, MKTAMT = @ADJQTY * (MKTAMT / @QTY),
					NETAMT = @ADJQTY * (NETAMT / @QTY)
					WHERE SNO = @SNO

					SET @AMOUNT = @AMOUNT - (@QTY - @ADJQTY) * (@NETAMT / @QTY)
				END	
			END
			FETCH NEXT FROM @BUYCUR INTO @SNO, @ISIN, @QTY, @NETAMT
		END
		CLOSE @BUYCUR
		DEALLOCATE @BUYCUR

		FETCH NEXT FROM @PFCUR INTO @PARTY_CODE, @AMOUNT
	END
	CLOSE @PFCUR
	DEALLOCATE @PFCUR

	DELETE FROM TBL_PRODUCT_POSITION
	WHERE SAUDA_DATE = @SAUDA_DATE AND QTY = 0
	 
	SELECT D.SETT_NO, D.SETT_TYPE, PARTY_CODE, SCRIP_CD, SERIES = CONVERT(VARCHAR(3),D.SERIES), 
	BSECODE = CONVERT(VARCHAR(6),''),ISIN = CONVERT(VARCHAR(12),''), QTY, SEC_PAYIN, START_DATE, 
	ORGQTY = QTY, HOLDFLAG = '1 BTST POSITION'
	INTO #B_BTSTMTF
	FROM MSAJAG.DBO.DELIVERYCLT D, MSAJAG.DBO.SETT_MST S
	WHERE S.SETT_NO = D.SETT_NO
	AND   S.SETT_TYPE = D.SETT_TYPE 
	AND   INOUT = 'O'
	AND	  D.SETT_TYPE IN ('N', 'W')
	AND   EXISTS (SELECT PARTY_CODE FROM TBLCLIENTMARGIN P
				  WHERE P.PARTY_CODE = D.PARTY_CODE
					AND @SAUDA_DATE BETWEEN FROM_DATE AND TO_DATE)
	AND S.START_DATE < @SAUDA_DATE
	AND	S.SEC_PAYIN > @SAUDA_DATE
	AND 1 =2 

	INSERT INTO #B_BTSTMTF
	SELECT D.SETT_NO, D.SETT_TYPE, PARTY_CODE, SCRIP_CD = CONVERT(VARCHAR(12),''), SERIES = CONVERT(VARCHAR(3),''), 
	BSECODE = SCRIP_CD, ISIN = CONVERT(VARCHAR(12),''), QTY, SEC_PAYIN, START_DATE,  	
	ORGQTY = QTY, HOLDFLAG = '1 BTST POSITION' 
	FROM AngelBSECM.BSEDB_AB.DBO.DELIVERYCLT D, AngelBSECM.BSEDB_AB.DBO.SETT_MST S
	WHERE S.SETT_NO = D.SETT_NO
	AND   S.SETT_TYPE = D.SETT_TYPE 
	AND	  INOUT = 'O'
	AND	  D.SETT_TYPE IN ('D', 'C')
	AND   EXISTS (SELECT PARTY_CODE FROM TBLCLIENTMARGIN P
				  WHERE P.PARTY_CODE = D.PARTY_CODE
					AND @SAUDA_DATE BETWEEN FROM_DATE AND TO_DATE)
	AND S.START_DATE < @SAUDA_DATE
	AND	S.SEC_PAYIN > @SAUDA_DATE
	AND 1 =2 
	/*
	UPDATE #B_BTSTMTF SET QTY = QTY - D.BUYQTY
	FROM (SELECT D.SETT_NO, D.SETT_TYPE, PARTY_CODE, SCRIP_CD, SERIES, BSECODE,
		  BUYQTY = SUM(QTY) FROM TBL_PRODUCT_POSITION D
		  WHERE SAUDA_DATE <= @SAUDA_DATE AND PAYIN_DATE > @SAUDA_DATE AND SELL_BUY = 1 
		  GROUP BY  D.SETT_NO, D.SETT_TYPE, PARTY_CODE, SCRIP_CD, SERIES, BSECODE ) D
	WHERE #B_BTSTMTF.SETT_NO = D.SETT_NO
	AND   #B_BTSTMTF.SETT_TYPE = D.SETT_TYPE
	AND   #B_BTSTMTF.PARTY_CODE = D.PARTY_CODE
	AND   ((#B_BTSTMTF.SCRIP_CD = D.SCRIP_CD
	AND   #B_BTSTMTF.SERIES = D.SERIES)
	OR   (#B_BTSTMTF.BSECODE = D.BSECODE))
	*/
	
	--IF @SAUDA_DATE = LEFT(GETDATE(),11)
	IF 1 = 1 
	BEGIN	
		IF @FLAG <> 2 
		BEGIN
			EXEC EDP_DP_BALANCE_UPDATE_NEW
		END

		INSERT INTO #B_BTSTMTF
		SELECT SETT_NO = '', SETT_TYPE = '', PARTY_CODE, SCRIP_CD = '', 
		SERIES, BSECODE = '', ISIN, QTY=FREEBAL, SEC_PAYIN='DEC 31 2049', START_DATE='DEC 31 2049',  	
		ORGQTY = FREEBAL, HOLDFLAG = 'POA' 
		FROM DELCDSLBALANCE
		WHERE EXISTS (SELECT PARTY_CODE FROM TBLCLIENTMARGIN 
					  WHERE DELCDSLBALANCE.PARTY_CODE = TBLCLIENTMARGIN.PARTY_CODE)

		DELETE FROM TBL_PRODUCT_HOLD_DATA    
		WHERE SAUDA_DATE = @SAUDA_DATE    
		AND HOLDFLAG IN ('POA','1 BTST POSITION') 

		INSERT INTO TBL_PRODUCT_HOLD_DATA
		SELECT @SAUDA_DATE, SETT_NO, SETT_TYPE, PARTY_CODE, SCRIP_CD, SERIES, BSECODE, ISIN, QTY, SEC_PAYIN, START_DATE, 
		ORGQTY, HOLDFLAG, CL_RATE = 0, HAIRCUT = 0, FOGFLAG = 0, MTFHAIRCUT = 0
		FROM #B_BTSTMTF
		WHERE QTY > 0   
	/*
		INSERT INTO TBL_PRODUCT_HOLD_DATA
		SELECT @SAUDA_DATE, SETT_NO, SETT_TYPE, PARTY_CODE, SCRIP_CD, SERIES, BSECODE, NEW_ISIN, 
		NEWQTY = (CASE WHEN CORP_TYPE = 'SPLIT' THEN NEWQTY - QTY ELSE NEWQTY END), 
		SEC_PAYIN = @SAUDA_DATE, START_DATE = @SAUDA_DATE, 
		ORGQTY = 0, HOLDFLAG = (CASE WHEN SEGMENT = 'FUTURES' THEN 'FOCOLL_P'
									WHEN SEGMENT = 'CAPITAL' AND ACCOUNTTYPE = 'MAR' THEN 'CMCOLL_P'
									WHEN SEGMENT = 'MTF' AND ACCOUNTTYPE = 'MAR' THEN 'MTFCOLL_P'
									ELSE 'BEN_P'
							   END), 
		CL_RATE = 0, HAIRCUT = 0, FOGFLAG = 0, MTFHAIRCUT = 0
		FROM MSAJAG.DBO.TBL_CORP_DATA_PROV P,
		(SELECT DPID, DPCLTNO, ACCOUNTTYPE, SEGMENT
		FROM BSEDB.DBO.DELIVERYDP DP
		WHERE DP.DESCRIPTION NOT LIKE '%POOL%'
		AND   DP.DESCRIPTION NOT LIKE '%PRINC%'
		AND DP.EXCHANGE = (CASE WHEN DP.EXCHANGE = 'MTF' AND DP.ACCOUNTTYPE = 'BEN' THEN '' ELSE DP.EXCHANGE END)
		UNION 
		SELECT DPID, DPCLTNO, ACCOUNTTYPE, SEGMENT
		FROM MSAJAG.DBO.DELIVERYDP DP
		WHERE DP.DESCRIPTION NOT LIKE '%POOL%'
		AND   DP.DESCRIPTION NOT LIKE '%PRINC%'
		AND DP.EXCHANGE = (CASE WHEN DP.EXCHANGE = 'MTF' AND DP.ACCOUNTTYPE = 'BEN' THEN '' ELSE DP.EXCHANGE END)) D
		WHERE RECORDDATE <= @SAUDA_DATE
		AND STATUSFLAG = 'P'
		AND P.BDPID = D.DPID
		AND P.BCLTDPID = D.DPCLTNO
		AND (CASE WHEN CORP_TYPE = 'SPLIT' THEN NEWQTY - QTY ELSE NEWQTY END) > 0
	
		INSERT INTO TBL_PRODUCT_HOLD_DATA
		SELECT @SAUDA_DATE, SETT_NO, SETT_TYPE, PARTY_CODE, SCRIP_CD, SERIES, BSECODE, NEW_ISIN, 
		NEWQTY = (CASE WHEN CORP_TYPE = 'SPLIT' THEN NEWQTY - QTY ELSE NEWQTY END), 
		SEC_PAYIN = @SAUDA_DATE, START_DATE = @SAUDA_DATE, 
		ORGQTY = 0, HOLDFLAG = 'POA_P', 
		CL_RATE = 0, HAIRCUT = 0, FOGFLAG = 0, MTFHAIRCUT = 0
		FROM MSAJAG.DBO.TBL_CORP_DATA_PROV P
		WHERE RECORDDATE <= @SAUDA_DATE
		AND STATUSFLAG = 'P'
		AND RECORDLOCATION = 'DP'*/
	END

	Select *  INTO #NSE_ISIN from  ANGELDEMAT.MSAJAG.DBO.MULTIISIN
	Select *  INTO #BSE_ISIN from  ANGELDEMAT.BSEDB.DBO.MULTIISIN 
        
        CREATE INDEX #NI ON #NSE_ISIN 
	(ISIN ,VALID)

        CREATE INDEX #BI ON #BSE_ISIN 
	(ISIN ,VALID)

 /*
	UPDATE TBL_PRODUCT_HOLD_DATA SET SCRIP_CD = M.SCRIP_CD, SERIES = M.SERIES
	FROM ANGELDEMAT.MSAJAG.DBO.MULTIISIN M
	WHERE SAUDA_DATE = @SAUDA_DATE
	AND TBL_PRODUCT_HOLD_DATA.ISIN = M.ISIN
	AND VALID = 1 

	UPDATE TBL_PRODUCT_HOLD_DATA SET BSECODE = LEFT(M.SCRIP_CD,6)
	FROM ANGELDEMAT.BSEDB.DBO.MULTIISIN M
	WHERE SAUDA_DATE = @SAUDA_DATE
	AND TBL_PRODUCT_HOLD_DATA.ISIN = M.ISIN
	AND VALID = 1 
	 */

	UPDATE TBL_PRODUCT_HOLD_DATA SET SCRIP_CD = M.SCRIP_CD, SERIES = M.SERIES
	FROM #NSE_ISIN M
	WHERE SAUDA_DATE = @SAUDA_DATE
	AND TBL_PRODUCT_HOLD_DATA.ISIN = M.ISIN
	AND VALID = 1 

	UPDATE TBL_PRODUCT_HOLD_DATA SET BSECODE = LEFT(M.SCRIP_CD,6)
	FROM #BSE_ISIN M
	WHERE SAUDA_DATE = @SAUDA_DATE
	AND TBL_PRODUCT_HOLD_DATA.ISIN = M.ISIN
	AND VALID = 1
	/*
	UPDATE TBL_PRODUCT_HOLD_DATA SET SCRIP_CD = M.SCRIP_CD, SERIES = M.SERIES
	FROM MSAJAG.DBO.MULTIISIN_NEW M
	WHERE SAUDA_DATE = @SAUDA_DATE
	AND @SAUDA_DATE BETWEEN EFF_FROM AND EFF_TO
	AND TBL_PRODUCT_HOLD_DATA.ISIN = M.ISIN

	UPDATE TBL_PRODUCT_HOLD_DATA SET BSECODE = LEFT(M.SCRIP_CD,6)
	FROM BSEDB.DBO.MULTIISIN_NEW M
	WHERE SAUDA_DATE = @SAUDA_DATE
	AND @SAUDA_DATE BETWEEN EFF_FROM AND EFF_TO
	AND TBL_PRODUCT_HOLD_DATA.ISIN = M.ISIN
	*/
	SELECT DISTINCT SCRIP_CD, SERIES, BSECODE, ISIN
	INTO #B_HOLDDATA FROM TBL_PRODUCT_HOLD_DATA
	WHERE SAUDA_DATE = @SAUDA_DATE

    SELECT SAUDA_DATE = CONVERT(DATETIME,@SAUDA_DATE), 
           PARTY_CODE, 
           SCRIP_CD, 
           SERIES, 
           BSECODE, 
           ISIN, 
           QTY = Sum(Qty), 
           MKTAMT = Sum(Mktamt), 
           NETAMT = Sum(Netamt), 
           CL_RATE = max(cl_rate), 
           CURR_CL_RATE = CONVERT(NUMERIC(18, 4), 0), 
           HAIRCUT = CONVERT(NUMERIC(18, 4), 0), 
           MARGIN_REQ = CONVERT(NUMERIC(18, 4), 0), 
           MTOM_LOSS = CONVERT(NUMERIC(18, 4), 0), 
           FOMARGIN = CONVERT(NUMERIC(18, 4), 0), 
           CMLEDBAL = CONVERT(NUMERIC(18, 4), 0), 
		   MTFLEDBAL = CONVERT(NUMERIC(18, 4), 0), 	
		   FOLEDBAL = CONVERT(NUMERIC(18, 4), 0), 
		   CMCASHEQCOLLATERAL = CONVERT(NUMERIC(18, 4), 0), 
		   CMCASHCOLLATERAL = CONVERT(NUMERIC(18, 4), 0), 
           CMNONCASHCOLLATERAL = CONVERT(NUMERIC(18, 4), 0), 
		   CMNONCASHCOLLATERAL_MTF = CONVERT(NUMERIC(18, 4), 0), 
		   CMDEBITHOLD = CONVERT(NUMERIC(18, 4), 0),
		   CMDEBITHOLD_MTF = CONVERT(NUMERIC(18, 4), 0),
		   CMOPENPOS = CONVERT(NUMERIC(18, 4), 0),
		   MTFCASHEQCOLLATERAL = CONVERT(NUMERIC(18, 4), 0),
		   MTFCASHCOLLATERAL = CONVERT(NUMERIC(18, 4), 0),
		   MTFNONCASHCOLLATERAL = CONVERT(NUMERIC(18, 4), 0),
		   FOCASHEQCOLLATERAL = CONVERT(NUMERIC(18, 4), 0), 
		   FOCASHCOLLATERAL = CONVERT(NUMERIC(18, 4), 0), 
		   FONONCASHCOLLATERAL = CONVERT(NUMERIC(18, 4), 0), 
		   FONONCASHCOLLATERAL_MTF = CONVERT(NUMERIC(18, 4), 0), 
           NET_AVL_FUND= CONVERT(NUMERIC(18, 4), 0),
		   POAHOLDING= CONVERT(NUMERIC(18, 4), 0),
		   POAHOLDING_MTF= CONVERT(NUMERIC(18, 4), 0),
		   SELLSHORT = CONVERT(NUMERIC(18, 4), 0),
		   ORG_SAUDA_DATE = SAUDA_DATE,
		  /*--- MTF NEW CHANGES ---*/
		   
		   MTF_FLAG = 0,
		   SETT_NO = MAX(SETT_NO),
		   PAYIN_DATE = MAX(PAYIN_DATE),
		   TRANSTYPE = (TRANSTYPE),
		   CURRENT_VAR = CONVERT(NUMERIC(18, 4), 0),
		   CURRENT_ELM = CONVERT(NUMERIC(18, 4), 0),
		   0 as FOFLAG,
		   HAIRCUTEXPOSURE = CONVERT(NUMERIC(18, 4), 0),
		   PREVIOUS_VAR = CONVERT(NUMERIC(18, 4), 0)
    INTO   #B_MTF_DATA 
    FROM   TBL_PRODUCT_POSITION 
    WHERE  SAUDA_DATE < @SAUDA_DATE 
           AND ADJUST_DATE > @SAUDA_DATE 
           AND SELL_BUY = 1 AND QTY > 0 
	Group By 
		   PARTY_CODE, 
           SCRIP_CD, 
           SERIES, 
           BSECODE, 
           ISIN,
		   SAUDA_DATE,
		   TRANSTYPE


	/*--- START NEW MTF CHANGES ---*/
    
	INSERT	INTO #B_MTF_DATA     
	SELECT	SAUDA_DATE = CONVERT(DATETIME,@SAUDA_DATE),     
			PARTY_CODE,     
			SCRIP_CD,     
			SERIES,     
			BSECODE,     
			ISIN,     
			QTY=sum(qty),     
			MKTAMT=sum(MKTAMT),     
			NETAMT=sum(NETAMT),     
			CL_RATE =max(Cl_Rate), 
			CURR_CL_RATE = CONVERT(NUMERIC(18, 4), 0),     
			HAIRCUT = CONVERT(NUMERIC(18, 4), 0),  
			--MTFHAIRCUT = CONVERT(NUMERIC(18, 4), 0),   
			MARGIN_REQ = CONVERT(NUMERIC(18, 4), 0),     
			MTOM_LOSS = CONVERT(NUMERIC(18, 4), 0),     
			FOMARGIN = CONVERT(NUMERIC(18, 4), 0),     
			CMLEDBAL = CONVERT(NUMERIC(18, 4), 0),     
			MTFLEDBAL = CONVERT(NUMERIC(18, 4), 0),      
			FOLEDBAL = CONVERT(NUMERIC(18, 4), 0),     
			CMCASHEQCOLLATERAL = CONVERT(NUMERIC(18, 4), 0),     
			CMCASHCOLLATERAL = CONVERT(NUMERIC(18, 4), 0),     
			CMNONCASHCOLLATERAL = CONVERT(NUMERIC(18, 4), 0),     
			CMNONCASHCOLLATERAL_MTF = CONVERT(NUMERIC(18, 4), 0),     
			CMDEBITHOLD = CONVERT(NUMERIC(18, 4), 0),    
			CMDEBITHOLD_MTF = CONVERT(NUMERIC(18, 4), 0),    
			CMOPENPOS = CONVERT(NUMERIC(18, 4), 0),    
			MTFCASHEQCOLLATERAL = CONVERT(NUMERIC(18, 4), 0),    
			MTFCASHCOLLATERAL = CONVERT(NUMERIC(18, 4), 0),    
			MTFNONCASHCOLLATERAL = CONVERT(NUMERIC(18, 4), 0),    
			FOCASHEQCOLLATERAL = CONVERT(NUMERIC(18, 4), 0),     
			FOCASHCOLLATERAL = CONVERT(NUMERIC(18, 4), 0),     
			FONONCASHCOLLATERAL = CONVERT(NUMERIC(18, 4), 0),     
			FONONCASHCOLLATERAL_MTF = CONVERT(NUMERIC(18, 4), 0),     
			NET_AVL_FUND= CONVERT(NUMERIC(18, 4), 0),    
			POAHOLDING= CONVERT(NUMERIC(18, 4), 0),    
			POAHOLDING_MTF= CONVERT(NUMERIC(18, 4), 0),    
			SELLSHORT = CONVERT(NUMERIC(18, 4), 0),
			ORG_SAUDA_DATE = SAUDA_DATE,
			MTF_FLAG = 1,
		    SETT_NO,
		    PAYIN_DATE,
		    TRANSTYPE,
			CURRENT_VAR = CONVERT(NUMERIC(18, 4), 0),
		    CURRENT_ELM = CONVERT(NUMERIC(18, 4), 0),
			0 as FOFLAG,
			HAIRCUTEXPOSURE = CONVERT(NUMERIC(18, 4), 0),
			PREVIOUS_VAR = CONVERT(NUMERIC(18, 4), 0)
    FROM	TBL_PRODUCT_POSITION with(nolock)     
    WHERE	SAUDA_DATE = @SAUDA_DATE 
			AND ADJUST_DATE > @SAUDA_DATE 
			AND SELL_BUY = 1
    GROUP BY PARTY_CODE,     
			SCRIP_CD,     
			SERIES,     
			BSECODE,     
			ISIN,  CL_RATE,  SAUDA_DATE,
		    SETT_NO,
		    PAYIN_DATE,
		    TRANSTYPE

	/*--- END NEW MTF CHANGES ---*/

	SELECT *  INTO #NSE_CLOSING from  MSAJAG.DBO.CLOSING WHERE SYSDATE >= @PREV_DATE  AND SYSDATE <= @PREV_DATE + ' 23:59' 
	SELECT *  INTO #BSE_CLOSING from  AngelBSECM.BSEDB_AB.DBO.CLOSING  WHERE SYSDATE >= @PREV_DATE AND SYSDATE <= @PREV_DATE + ' 23:59' 
        
	     CREATE INDEX #NCLOSING ON #NSE_CLOSING 
	(SCRIP_CD ,SERIES)

        CREATE INDEX #BCLSOING ON #BSE_CLOSING 
	(SCRIP_CD )


	/*************NEW ADDITION FOR T-1 CLOSING PRice *************/
	DECLARE @PREV_DATE_T1 VARCHAR(11)

	SELECT @PREV_DATE_T1 = left(ISNULL(MAX(SYSDATE),@SAUDA_DATE),11) FROM   MSAJAG.DBO.CLOSING C 
	WHERE SYSDATE <  @SAUDA_DATE 

	SELECT *  INTO #NSE_CLOSING_P from  MSAJAG.DBO.CLOSING WHERE SYSDATE >= @PREV_DATE_T1  AND SYSDATE <= @PREV_DATE_T1 + ' 23:59' 
	SELECT *  INTO #BSE_CLOSING_P from  AngelBSECM.BSEDB_AB.DBO.CLOSING  WHERE SYSDATE >= @PREV_DATE_T1 AND SYSDATE <= @PREV_DATE_T1 + ' 23:59' 


	       CREATE INDEX #NCLOSING ON #NSE_CLOSING_P 
	(SCRIP_CD ,SERIES)

        CREATE INDEX #BCLSOING ON #BSE_CLOSING_P 
	(SCRIP_CD )

	/*************NEW ADDITION FOR T-1 CLOSING PRice END*************/



	
	
    UPDATE #B_MTF_DATA 
    SET    CURR_CL_RATE = C.CL_RATE 
    FROM   #NSE_CLOSING C
    WHERE  SYSDATE >= @PREV_DATE
           AND SYSDATE <= @PREV_DATE + ' 23:59' 
           AND #B_MTF_DATA.SCRIP_CD = C.SCRIP_CD 
           AND #B_MTF_DATA.SERIES IN ( 'EQ', 'BE', 'BZ' ) 
           AND C.SERIES IN ( 'EQ', 'BE', 'BZ' ) 
           AND #B_MTF_DATA.CURR_CL_RATE = 0 

    UPDATE #B_MTF_DATA 
    SET    CURR_CL_RATE = C.CL_RATE 
    FROM   #NSE_CLOSING C 
    WHERE  SYSDATE >= @PREV_DATE
           AND SYSDATE <= @PREV_DATE+ ' 23:59' 
           AND #B_MTF_DATA.SCRIP_CD = C.SCRIP_CD 
           AND #B_MTF_DATA.SERIES = C.SERIES 
           AND C.SERIES NOT IN ( 'EQ', 'BE', 'BZ' ) 
           AND #B_MTF_DATA.CURR_CL_RATE = 0 

    UPDATE #B_MTF_DATA 
    SET    CURR_CL_RATE = C.CL_RATE 
    FROM   #BSE_CLOSING C
    WHERE  SYSDATE >= @PREV_DATE
           AND SYSDATE <= @PREV_DATE+ ' 23:59' 
           AND #B_MTF_DATA.BSECODE = C.SCRIP_CD 
           AND #B_MTF_DATA.CURR_CL_RATE = 0 

	/* CLOSING PRICE OPTI */

	UPDATE #B_MTF_DATA 
    SET    CL_RATE = C.CL_RATE 
    FROM   #NSE_CLOSING C 
    WHERE  SYSDATE >= @PREV_DATE 
           AND SYSDATE <= @PREV_DATE + ' 23:59' 
           AND #B_MTF_DATA.SCRIP_CD = C.SCRIP_CD 
           AND #B_MTF_DATA.SERIES IN ( 'EQ', 'BE', 'BZ' ) 
           AND C.SERIES IN ( 'EQ', 'BE', 'BZ' ) 
           --AND #B_MTF_DATA.CL_RATE = 0 

    UPDATE #B_MTF_DATA 
    SET    CL_RATE = C.CL_RATE 
    FROM   #NSE_CLOSING C 
    WHERE  SYSDATE >= @PREV_DATE 
           AND SYSDATE <= @PREV_DATE  + ' 23:59' 
           AND #B_MTF_DATA.SCRIP_CD = C.SCRIP_CD 
           AND #B_MTF_DATA.SERIES = C.SERIES 
           AND C.SERIES NOT IN ( 'EQ', 'BE', 'BZ' ) 
           --AND #B_MTF_DATA.CL_RATE = 0 

    UPDATE #B_MTF_DATA 
    SET    CL_RATE = C.CL_RATE 
    FROM   #NSE_CLOSING C 
    WHERE  SYSDATE >= @PREV_DATE 
           AND SYSDATE <= @PREV_DATE  + ' 23:59' 
           AND #B_MTF_DATA.BSECODE = C.SCRIP_CD 
           --AND #B_MTF_DATA.CL_RATE = 0 
		  
		 -- Select * from #B_MTF_DATA where party_code ='K78026'
	
    UPDATE #B_MTF_DATA 
    SET    CL_RATE = CURR_CL_RATE
	WHERE CL_RATE = 0
	UPDATE TBL_PRODUCT_HOLD_DATA 
    SET    CL_RATE = C.CL_RATE 
    FROM   #NSE_CLOSING_P C 
    WHERE  SAUDA_DATE = @SAUDA_DATE AND SYSDATE >= @PREV_DATE_T1
           AND SYSDATE <= @PREV_DATE_T1 + ' 23:59' 
           AND TBL_PRODUCT_HOLD_DATA.SCRIP_CD = C.SCRIP_CD 
           AND TBL_PRODUCT_HOLD_DATA.SERIES IN ( 'EQ', 'BE', 'BZ' ) 
           AND C.SERIES IN ( 'EQ', 'BE', 'BZ' ) 
           AND TBL_PRODUCT_HOLD_DATA.CL_RATE = 0 

    UPDATE TBL_PRODUCT_HOLD_DATA 
    SET    CL_RATE = C.CL_RATE 
    FROM   #NSE_CLOSING_P C 
    WHERE  SAUDA_DATE = @SAUDA_DATE AND SYSDATE >= @PREV_DATE_T1
           AND SYSDATE <= @PREV_DATE_T1 + ' 23:59' 
           AND TBL_PRODUCT_HOLD_DATA.SCRIP_CD = C.SCRIP_CD 
           AND TBL_PRODUCT_HOLD_DATA.SERIES = C.SERIES 
           AND C.SERIES NOT IN ( 'EQ', 'BE', 'BZ' ) 
           AND TBL_PRODUCT_HOLD_DATA.CL_RATE = 0 

    UPDATE TBL_PRODUCT_HOLD_DATA 
    SET    CL_RATE = C.CL_RATE 
    FROM   #BSE_CLOSING_P C 
    WHERE  SAUDA_DATE = @SAUDA_DATE AND SYSDATE >= @PREV_DATE_T1
           AND SYSDATE <= @PREV_DATE_T1 + ' 23:59' 
           AND TBL_PRODUCT_HOLD_DATA.BSECODE = C.SCRIP_CD 
           AND TBL_PRODUCT_HOLD_DATA.CL_RATE = 0 

	SELECT *, FOFLAG = 0, ACTIVEFLAG = 1 INTO #B_TBLSCRIPMARGIN 
	FROM TBLSCRIPMARGIN
	WHERE @SAUDA_DATE BETWEEN FROM_DATE AND TO_DATE

	
	CREATE CLUSTERED INDEX IDXDT ON #B_TBLSCRIPMARGIN
	(
		ISIN
	)
	
	INSERT INTO #B_TBLSCRIPMARGIN 
	SELECT DISTINCT SCRIP_CD,FROM_DATE=@SAUDA_DATE,TO_DATE=@SAUDA_DATE + ' 23:59:59',ENTERED_BY='',ENTERED_DATE=@SAUDA_DATE,
					SERIES,BSECODE,ISIN,SCRIP_GROUP,FUND_PER, FOFLAG = 0, ACTIVEFLAG = 0 
	FROM TBLSCRIPMARGIN 
	WHERE ISIN NOT IN (SELECT ISIN FROM #B_TBLSCRIPMARGIN)

	UPDATE #B_TBLSCRIPMARGIN SET FOFLAG = 1
	FROM ANGELFO.NSEFO.DBO.FOSCRIP2 F
	WHERE F.SYMBOL = #B_TBLSCRIPMARGIN.SCRIP_CD
	AND   F.EXPIRYDATE >= @SAUDA_DATE
	AND   INST_TYPE LIKE 'FUT%'

	UPDATE TBL_PRODUCT_HOLD_DATA SET FOGFLAG = 1
	FROM #B_TBLSCRIPMARGIN
	WHERE SAUDA_DATE=@SAUDA_DATE
--		  SAUDA_DATE BETWEEN  @SAUDA_DATE  AND @SAUDA_DATE + ' 23:59'
	AND #B_TBLSCRIPMARGIN.ISIN = TBL_PRODUCT_HOLD_DATA.ISIN
	AND ACTIVEFLAG = 1
	
	SELECT V.* INTO #B_NSE_VAR FROM MSAJAG.DBO.VARDETAIL V, 
	MSAJAG.DBO.VARCONTROL  C
	WHERE C.RECDATE >= @PREV_DATE_NEW  aND c.REcDATE <= @PREV_DATE_NEW  + ' 23:59'
	AND C.DETAILKEY = V.DETAILKEY
	AND SERIES IN ( 'EQ', 'BE', 'BZ' ) 
	AND ISIN IN (SELECT ISIN FROM #B_MTF_DATA UNION SELECT ISIN FROM #B_HOLDDATA)

	--SELECT V.* INTO #B_BSE_VAR FROM BSEDB.DBO.VARDETAIL V
	--WHERE V.FDATE = @SAUDA_DATE
	--AND ISIN IN (SELECT ISIN FROM #B_MTF_DATA UNION SELECT ISIN FROM #B_HOLDDATA)

 /** For Optimization*/ 
	SELECT V.* INTO  #BSE_VAR FROM ANGELBSECM.BSEDB_AB.DBO.VARDETAIL V
	WHERE V.FDATE >= @PREV_DATE_NEW  aND v.FDATE <= @PREV_DATE_NEW  + ' 23:59'

    SELECT V.* INTO #B_BSE_VAR FROM  #BSE_VAR V
	WHERE  ISIN IN (SELECT ISIN FROM #B_MTF_DATA UNION SELECT ISIN FROM #B_HOLDDATA)

	CREATE CLUSTERED INDEX #NISIN ON #B_NSE_VAR
	(ISIN )
	CREATE CLUSTERED INDEX #BISIN ON #B_BSE_VAR
	(ISIN )

    UPDATE #B_MTF_DATA 
    SET    HAIRCUT = (CASE WHEN T.FOFLAG = 1 THEN M.APPVAR + @FNO * SECSPECVAR ELSE M.APPVAR + @NONFNO * SECSPECVAR END),
           HAIRCUTEXPOSURE = (CASE WHEN VARMARGINRATE > (CASE WHEN T.FOFLAG = 1 THEN M.APPVAR + 5 * SECSPECVAR ELSE M.APPVAR + 5 * SECSPECVAR END)
						   THEN VARMARGINRATE
						   ELSE (CASE WHEN T.FOFLAG = 1 THEN M.APPVAR + 5 * SECSPECVAR ELSE M.APPVAR + 5 * SECSPECVAR END)
					  END), --- Here the if statement and else statement is same for future use.
           CURRENT_VAR = M.APPVAR,
		   CURRENT_ELM = SECSPECVAR,
		   FOFLAG = T.FOFLAG
    FROM   #B_NSE_VAR M, #B_TBLSCRIPMARGIN T 
    WHERE  M.ISIN = #B_MTF_DATA.ISIN 
	AND    M.ISIN = T.ISIN
	AND    HAIRCUT = 0
	
	------------------ START - SRE-40834 -------------------------
 
/*	
    UPDATE #B_MTF_DATA 
    SET    HAIRCUT = (CASE WHEN FOFLAG = 1  AND HAIRCUT < 25 THEN HAIRCUT + 2  ELSE HAIRCUT END)
    FROM   #B_TBLSCRIPMARGIN T 
    WHERE  #B_MTF_DATA.ISIN = T.ISIN AND FOFLAG=1
	AND    HAIRCUT <> 0
*/

	------------------ END - SRE-40834 -------------------------

	--UPDATE  #B_MTF_DATA SET  HAIRCUT = (CASE WHEN FOFLAG = 1 AND HAIRCUT <25 THEN HAIRCUT + 2  ELSE HAIRCUT END)
	--WHERE HAIRCUT <> 0
	
	UPDATE #B_MTF_DATA SET PREVIOUS_VAR = M.APPVAR
	From #B_NSE_VAR M, #B_TBLSCRIPMARGIN T 
    WHERE  M.ISIN = #B_MTF_DATA.ISIN 
	AND    M.ISIN = T.ISIN
	AND    PREVIOUS_VAR = 0
		

	UPDATE TBL_PRODUCT_HOLD_DATA 
    SET    MTFHAIRCUT = (CASE WHEN T.FOFLAG = 1 
							  THEN M.MARGIN + @FNO * ELM 
							  ELSE M.MARGIN + @NONFNO * ELM 
					     END)
    FROM   #B_BSE_VAR M, #B_TBLSCRIPMARGIN T
    WHERE  SAUDA_DATE = @SAUDA_DATE
	AND    M.ISIN = TBL_PRODUCT_HOLD_DATA.ISIN 
	AND    M.ISIN = T.ISIN
	AND    MTFHAIRCUT = 0
	AND    TBL_PRODUCT_HOLD_DATA.BSECODE = M.Scrip_Cd
	
	UPDATE TBL_PRODUCT_HOLD_DATA 
    SET    MTFHAIRCUT = (CASE WHEN T.FOFLAG = 1 
							  THEN M.MARGIN + @FNO * ELM 
							  ELSE M.MARGIN + @NONFNO * ELM 
					     END)
    FROM   #B_BSE_VAR M, #B_TBLSCRIPMARGIN T
    WHERE  SAUDA_DATE = @SAUDA_DATE
	AND    M.ISIN = TBL_PRODUCT_HOLD_DATA.ISIN 
	AND    M.ISIN = T.ISIN
	AND    MTFHAIRCUT = 0
	
    UPDATE TBL_PRODUCT_HOLD_DATA 
    SET    HAIRCUT = M.APPVAR
    FROM   #B_NSE_VAR M--,  #B_TBLSCRIPMARGIN T 
    WHERE  SAUDA_DATE = @SAUDA_DATE
	AND    M.ISIN = TBL_PRODUCT_HOLD_DATA.ISIN  
	--AND    M.ISIN = T.ISIN AND ACTIVEFLAG = 1
	
    UPDATE TBL_PRODUCT_HOLD_DATA 
    SET    MTFHAIRCUT = (CASE WHEN FOFLAG = 1 THEN M.APPVAR + @FNO * SECSPECVAR ELSE M.APPVAR + @NONFNO * SECSPECVAR END)
    FROM   #B_NSE_VAR M, #B_TBLSCRIPMARGIN T 
    WHERE  SAUDA_DATE = @SAUDA_DATE
	AND    M.ISIN = TBL_PRODUCT_HOLD_DATA.ISIN 
	AND    M.ISIN = T.ISIN AND ACTIVEFLAG = 1

    UPDATE TBL_PRODUCT_HOLD_DATA 
    SET    HAIRCUT = M.MARGIN --(CASE WHEN FOFLAG = 1 THEN M.MARGIN + 3 * ELLM ELSE M.MARGIN + 5 * ELM END)
    FROM   #B_BSE_VAR M--,  #B_TBLSCRIPMARGIN T  
    WHERE  SAUDA_DATE = @SAUDA_DATE
	AND    M.ISIN = TBL_PRODUCT_HOLD_DATA.ISIN  
	AND    HAIRCUT = 0
	--AND    M.ISIN = T.ISIN AND ACTIVEFLAG = 1
		
    UPDATE TBL_PRODUCT_HOLD_DATA 
    SET    MTFHAIRCUT = (CASE WHEN T.FOFLAG = 1 
							  THEN M.MARGIN + @FNO * ELM 
							  ELSE M.MARGIN + @NONFNO * ELM 
					     END)
    FROM   #B_BSE_VAR M, #B_TBLSCRIPMARGIN T
    WHERE  SAUDA_DATE = @SAUDA_DATE
	AND    M.ISIN = TBL_PRODUCT_HOLD_DATA.ISIN 
	AND    M.ISIN = T.ISIN
	AND    MTFHAIRCUT = 0 AND ACTIVEFLAG = 1

	IF @MTFCOLLVAR = 1 
	BEGIN
		UPDATE TBL_PRODUCT_HOLD_DATA     
		SET    MTFHAIRCUT = HAIRCUT, HAIRCUT = MTFHAIRCUT  
		WHERE SAUDA_DATE = @SAUDA_DATE
		AND ISIN IN (SELECT ISIN FROM #B_TBLSCRIPMARGIN) 
	END

	
	
	UPDATE TBL_PRODUCT_HOLD_DATA     
	SET    MTFHAIRCUT = (CASE WHEN MTFHAIRCUT = 0 THEN 100 ELSE MTFHAIRCUT END), 
		   HAIRCUT = (CASE WHEN HAIRCUT = 0 THEN 100 ELSE HAIRCUT END)  
	WHERE SAUDA_DATE = @SAUDA_DATE
	AND (MTFHAIRCUT = 0 OR HAIRCUT = 0)

    UPDATE #B_MTF_DATA 
    SET    HAIRCUT = 100 
    WHERE  HAIRCUT = 0 OR HAIRCUT > 100

	UPDATE #B_MTF_DATA 
    SET    HAIRCUT = F.VARMARGIN
	FROM MTF_ANGEL_Varmargin F
	WHERE @SAUDA_DATE BETWEEN F.From_date AND F.end_date
	AND #B_MTF_DATA.ISIN = F.ISIN 
	AND HAIRCUT < F.VARMARGIN


	 /** -- CHANGES LOGIC FOR PREVIOUS VAR ON DATE 07/02/2026 **/
	UPDATE #B_MTF_DATA SET PREVIOUS_VAR = F.VARMARGIN
	From MTF_ANGEL_Varmargin F
	WHERE @SAUDA_DATE BETWEEN F.From_date AND F.end_date
	AND #B_MTF_DATA.ISIN = F.ISIN 
	AND PREVIOUS_VAR < F.VARMARGIN
	/** -- CHANGES LOGIC FOR PREVIOUS VAR ON DATE 07/02/2026 **/
		

    UPDATE #B_MTF_DATA 
    SET    HAIRCUT = 100 
    WHERE  HAIRCUT = 0 OR HAIRCUT > 100

	UPDATE TBL_PRODUCT_HOLD_DATA     
	SET    MTFHAIRCUT = (CASE WHEN MTFHAIRCUT > 100 THEN 100 ELSE MTFHAIRCUT END), 
		   HAIRCUT = (CASE WHEN HAIRCUT > 100 THEN 100 ELSE HAIRCUT END)  
	WHERE SAUDA_DATE = @SAUDA_DATE
	AND (MTFHAIRCUT > 100 OR HAIRCUT > 100)
	
	UPDATE TBL_PRODUCT_HOLD_DATA              
	SET     HAIRCUT = 100        
	WHERE SAUDA_DATE = @SAUDA_DATE AND ISIN  IN (SELECT DISTINCT ISIN FROM MSAJAG.DBO.LIQUID_ISIN_FOVIOLATION L WHERE @SAUDA_DATE BETWEEN FROM_DATE AND TO_DATE)     

	/* 100% var Margin Change Start */   /*Changes Done by Siva K and Ganesh J 07032024*/
	UPDATE TBL_PRODUCT_HOLD_DATA
	SET    MTFHAIRCUT = 100,
		   HAIRCUT = 100
	WHERE SAUDA_DATE = @SAUDA_DATE
	AND NOT EXISTS (SELECT ISIN FROM   #B_TBLSCRIPMARGIN T WHERE TBL_PRODUCT_HOLD_DATA.ISIN=T.ISIN)
	  UPDATE #B_MTF_DATA
    SET    HAIRCUT = 100
    WHERE
	 NOT EXISTS (SELECT ISIN FROM   #B_TBLSCRIPMARGIN T WHERE #B_MTF_DATA.ISIN=T.ISIN)
	 	/* 100% var Margin Change End */


	UPDATE TBL_PRODUCT_HOLD_DATA 
    SET    HAIRCUT = 100   
	WHERE SAUDA_DATE = @SAUDA_DATE AND FOGFLAG = 0
	AND HOLDFLAG = 'MTFCOLL'


    
	/*--- ADDED NEW CONDITION FOR MARGIN CALCULATION FOR FRESH BUY & CARRY FORWORD POSITION ---*/

	UPDATE	#B_MTF_DATA 
    SET		MARGIN_REQ = NETAMT * (HAIRCUT) / 100 --,
			--MIN_Rate = MKTAMT * 1.00 / QTY
	WHERE	MTF_FLAG = 1

    UPDATE	#B_MTF_DATA 
    SET		MARGIN_REQ = (CASE WHEN (NETAMT > CL_RATE*QTY) THEN CL_RATE*QTY*HAIRCUT / 100 ELSE (NETAMT*HAIRCUT) / 100 END)--,
		    --MIN_Rate = case when MKTAMT/QTY > CL_RATE then CL_RATE ElSE MKTAMT*1.00/QTY END 
	WHERE	MTF_FLAG = 0

	
	 
	UPDATE #B_MTF_DATA 
	SET    MTOM_LOSS = ( NETAMT / QTY - CURR_CL_RATE ) * QTY 
	--WHERE HAIRCUT <> 100

	--/*	
	UPDATE #B_MTF_DATA SET MTOM_LOSS = (CASE WHEN MTOM_LOSS < 0 THEN 0 ELSE MTOM_LOSS END)
	--FROM (SELECT PARTY_CODE, MTOM_LOSS = SUM(MTOM_LOSS)
	--FROM #B_MTF_DATA 
	--GROUP BY PARTY_CODE) A
	--WHERE A.PARTY_CODE = #B_MTF_DATA.PARTY_CODE 
	--*/
	/*
	UPDATE #B_MTF_DATA SET SELLSHORT = A.SELL_SHORT
	FROM (SELECT PARTY_CODE, SELL_SHORT = SUM(QTY*CL_RATE + QTY*CL_RATE*HAIRCUT/100)
		  FROM TBL_PRODUCT_HOLD_DATA WHERE HOLDFLAG = 'OPEN SELL POS'
		  GROUP BY PARTY_CODE
		  HAVING SUM(QTY) > 0) A
	WHERE #B_MTF_DATA.PARTY_CODE = A.PARTY_CODE
	*/
	CREATE INDEX #PARTY ON #B_MTF_DATA (PARTY_CODE,ISIN,ORG_SAUDA_DATE)

	-- *******************************************************************************************************--
	-- ************************************  New Margin Requirement Calculation ***************************** -- 
	-- *******************************************************************************************************--
 

		SELECT	PARTY_CODE,
			SCRIP_CD,
			SERIES,
			sISIN AS ISIN,
			SAUDA_DATE,
			sEXCHANGE,
			ORG_SAUDA_DATE,
			MMQTY = nCLINETQTY,
			MM_MKTAMT = nCLINETAMT,
			nBrokerNetQty = NBROKERNETQTY,
			nBrokerNetAmt =  NBROKERNETAMT,
			nEXPOSUREQTY,
			convert(decimal(18,2),0) as HAIRCUT,
			convert(decimal(18,2),0) as HAIRCUTEXPOSURE,
			convert(decimal(18,4),0) as nCliNetAmt_Afer_HC,
			convert(decimal(18,4),0) as CL_RATE,
			convert(decimal(18,2),0) as CURRENT_VAR,
			convert(decimal(18,2),0) as nCurrentELM,
			nFOFLAG,
			convert(decimal(18,4),0) as NEW_MARGIN_REQ,
			convert(decimal(18,4),0) as NEW_NetMARGIN_REQ,
			convert(decimal(18,4),0) as  NEW_MTOM_LOSS,
			convert(decimal(18,4),0) as MIN_Rate,
			0 as MTF_FLAG,Buy_Rate=Round((Case when nCLINETAMT <>0 then nCLINETAMT/nCLINETQTY else 0 end),4),
			PAYIN_DATE ,
			convert(decimal(18,4),0) as Cash_Fund_Qty,
			convert(decimal(18,4),0) as CURR_CL_RATE --- ADDED ON 06/01/2026 ---
	INTO	#MMQTY
	FROM	TBL_MTR_MAINTMARGINQTY 
	WHERE	SAUDA_DATE = @SAUDA_DATE 


    CREATE INDEX #PARTY ON #MMQTY (PARTY_CODE,ISIN,ORG_SAUDA_DATE)



	Update A set CL_RATE = B.CL_RATE,
				 CURR_CL_RATE = B.CURR_CL_RATE, --- ADDED ON 06/01/2026 ---
				 CURRENT_VAR = B.CURRENT_VAR,
				 nCurrentELM = B.CURRENT_ELM,
				 HAIRCUT = B.HAIRCUT,
				 HAIRCUTEXPOSURE = B.HAIRCUTEXPOSURE,
				 MTF_FLAG = B.MTF_FLAG,
				 nFOFLAG = B.FOFLAG,
				 PAYIN_DATE = B.PAYIN_DATE,
				 MIN_Rate = case when B.MTF_FLAG = 1 then (nBrokerNetAmt * 1.00 / nBrokerNetQty) 
							     else (case when nBrokerNetAmt/nBrokerNetQty > B.CL_RATE then B.CL_RATE ElSE nBrokerNetAmt*1.00/nBrokerNetQty END ) End,
                 --nCliNetAmt_Afer_HC = (isnull(MMQTY,0)*B.CL_RATE) * (100-B.PREVIOUS_VAR)/100,
				 nCliNetAmt_Afer_HC = (isnull(MMQTY,0)*B.CURR_CL_RATE) * (100-B.PREVIOUS_VAR)/100,
				 nExposureQty=   (case when MM_MKTAMT<>0 Then  (case when nBrokerNetQty> (MM_MKTAMT /(Buy_Rate*((case when B.HAIRCUT > B.CURRENT_VAR+(B.CURRENT_ELM*5) Then  B.HAIRCUT else B.CURRENT_VAR+(B.CURRENT_ELM*5) end) )/100))
				 Then  (MM_MKTAMT /(Buy_Rate*(case when B.HAIRCUT > B.CURRENT_VAR+(B.CURRENT_ELM*5) Then  B.HAIRCUT else B.CURRENT_VAR+(B.CURRENT_ELM*5) end)/100)) else nBrokerNetQty End)  Else 0 End)
				  
	From #MMQTY A
	Inner Join #B_MTF_DATA B on A.PARTY_CODE = B.PARTY_CODE
		                   AND  A.ISIN = B.ISIN
						   AND  A.ORG_SAUDA_DATE = B.ORG_SAUDA_DATE
						   AND  A.SAUDA_DATE = B.SAUDA_DATE
	WHERE nBrokerNetQty > 0



 


	Update #MMQTY 
	SET NEW_MARGIN_REQ = (--(nExposureQty*MIN_Rate) * HAIRCUTEXPOSURE/100 +
		 (nExposureQty*MIN_Rate) * (((case when HAIRCUT > (CURRENT_VAR+nCurrentELM*5) Then  HAIRCUT else CURRENT_VAR+(nCurrentELM*5) end))/100) +
		 		 (Case when nExposureQty =0 Then ((nBrokerNetQty)*MIN_Rate) * HAIRCUT/100
				 Else 
		             (Case when nFOFLAG=1 Then ((nBrokerNetQty-nExposureQty)*MIN_Rate) * (case when haircut > (CURRENT_VAR+(nCurrentELM*3)) then HAIRCUT else (CURRENT_VAR+(nCurrentELM*3)) end)/100 
					 Else ((nBrokerNetQty-nExposureQty)*MIN_Rate) * ( case when haircut >   (CURRENT_VAR+(nCurrentELM*5)) Then HAIRCUT else   (CURRENT_VAR+(nCurrentELM*5)) end)/100  eND) END))
    
 
	Update #MMQTY 
	SET NEW_NetMARGIN_REQ = case when NEW_MARGIN_REQ - nCliNetAmt_Afer_HC > 0 then NEW_MARGIN_REQ - nCliNetAmt_Afer_HC else 0 end --NEW_MARGIN_REQ

   	UPDATE	#MMQTY 
	SET		NEW_MTOM_LOSS = ( nBrokerNetAmt /  nBrokerNetQty - CURR_CL_RATE ) * nBrokerNetQty --- CHANGES ON 06/01/2026 ( CURR_CL_RATE ) ---
	WHERE	HAIRCUT <> 100
	and nBrokerNetQty > 0

	UPDATE #MMQTY SET NEW_MTOM_LOSS = (CASE WHEN NEW_MTOM_LOSS < 0 THEN 0 ELSE #MMQTY.NEW_MTOM_LOSS END)

 



	---SELECT ( nBrokerNetAmt /  nBrokerNetQty - CURR_CL_RATE ) * nBrokerNetQty, nBrokerNetAmt /  nBrokerNetQty, CURR_CL_RATE,* FROM #MMQTY WHERE PARTY_CODE ='rp61'

	-- comMENTED ON 06/01/2026 ---
	-- UPDATE #MMQTY SET NEW_MTOM_LOSS = (CASE WHEN A.NEW_MTOM_LOSS < 0 THEN 0 ELSE #MMQTY.NEW_MTOM_LOSS END)
	--FROM (SELECT PARTY_CODE, NEW_MTOM_LOSS = SUM(NEW_MTOM_LOSS)
	--FROM #MMQTY 
	--GROUP BY PARTY_CODE) A
	--WHERE A.PARTY_CODE = #MMQTY.PARTY_CODE 

	--Update #MMQTY set NEW_MTOM_LOSS = case when NEW_MTOM_LOSS < 0 then 0 else NEW_MTOM_LOSS End
	
    Update tbl_MTR_MaintMarginQty set nOrgHairCut = B.HAIRCUT
    From tbl_MTR_MaintMarginQty A
	Inner Join #MMQTY B On A.Party_Code = B.Party_Code
					    And A.Sauda_date = B.Sauda_Date
						And A.ORG_SAUDA_DATE = B.ORG_SAUDA_DATE
						And A.sISIN = B.ISIN
						And A.sEXCHANGE = B.sEXCHANGE
	WHERE B.PAYIN_DATE = @SAUDA_DATE

    UPDATE TBL_MTR_MAINTMARGINQTY SET nCURRENTVAR = B.CURRENT_VAR,
									  nCURRENTELM = B.nCurrentELM,
									  nFOFLAG = B.nFOFLAG,
									  nCLINETAMT_AFER_HC = B.nCliNetAmt_Afer_HC,
									  nMARGIN_REQ = B.NEW_MARGIN_REQ,
									  nNETMARGIN_REQ = case when B.NEW_NETMARGIN_REQ > 0 then B.NEW_NETMARGIN_REQ else 0 end ,
									  nMTOM_LOSS = B.NEW_MTOM_LOSS,
									  PAYIN_DATE = B.PAYIN_DATE,
									  --CL_RATE = B.CL_RATE, --- COMMENTED ON 06/01/2026 ---
									  CL_RATE = B.CURR_CL_RATE,
									  nExposureQty=B.nExposureQty
    FROM TBL_MTR_MAINTMARGINQTY A
	INNER JOIN #MMQTY B ON A.PARTY_CODE = B.PARTY_CODE
					    AND A.SAUDA_DATE = B.SAUDA_DATE
						AND A.ORG_SAUDA_DATE = B.ORG_SAUDA_DATE
						AND A.SISIN = B.ISIN
						And A.sEXCHANGE = B.sEXCHANGE
	

	SELECT  PARTY_CODE,
			SAUDA_DATE,
			ORG_SAUDA_DATE,
			ISIN as sISIN,
			sum(NEW_NetMARGIN_REQ) as NEW_NetMARGIN_REQ, 
			sum(NEW_MTOM_LOSS) as NEW_MTOM_LOSS,
			sEXCHANGE
	Into #CombinedMarReq
	From #MMQTY
	Group by PARTY_CODE,
			 SAUDA_DATE,
			 ORG_SAUDA_DATE,
			 ISIN,
			 sEXCHANGE

	UPDATE A SET MTOM_LOSS = NEW_MTOM_LOSS,
						   MARGIN_REQ = NEW_NetMARGIN_REQ
	From #B_MTF_DATA A
	Inner Join #CombinedMarReq B on A.PARTY_CODE = B.PARTY_CODE
								And A.SAUDA_DATE = B.SAUDA_DATE
								And A.ORG_SAUDA_DATE = B.ORG_SAUDA_DATE
								And A.ISIN = B.sISIN
								and a.TRANSTYPE = B.sEXCHANGE


	-- *******************************************************************************************************--
	-- ************************************  New Margin Requirement Calculation ***************************** -- 
	-- *******************************************************************************************************--

	CREATE INDEX idx_b_mtf_data_party_code ON #B_MTF_DATA (PARTY_CODE);
	
    SELECT L.CLTCODE, 
           VDTLEDBAL = SUM(CASE 
                             WHEN DRCR = 'C' THEN VAMT 
                             ELSE -VAMT 
                           END) 
    INTO   #B_LEDBAL 
    FROM   ACCOUNT.DBO.LEDGER L,  
		   (SELECT DISTINCT PARTY_CODE		
                             FROM   #B_MTF_DATA ) M	
    WHERE  L.VDT BETWEEN @SDTCUR AND @LDTCUR 
           AND L.VDT <= @SAUDA_DATE + ' 23:59:59' 
           AND L.CLTCODE = PARTY_CODE
		   /*AND VTYP <> (CASE WHEN VDT BETWEEN @SAUDA_DATE AND @SAUDA_DATE + ' 23:59' 
							 THEN '35' ELSE '' END)*/
    GROUP  BY L.CLTCODE 

	INSERT  INTO   #B_LEDBAL 
    SELECT L.CLTCODE, 
           VDTLEDBAL = SUM(CASE 
                             WHEN DRCR = 'D' THEN VAMT 
                             ELSE -VAMT 
                           END)
    FROM   ACCOUNT.DBO.LEDGER L,  
		   (SELECT DISTINCT PARTY_CODE		
                             FROM   #B_MTF_DATA ) M	
    WHERE  L.VDT <= @SAUDA_DATE
           AND L.EDT > @SAUDA_DATE + ' 23:59:59' 
           AND L.CLTCODE = PARTY_CODE
		   /*AND VTYP <> (CASE WHEN VDT BETWEEN @SAUDA_DATE AND @SAUDA_DATE + ' 23:59' 
							 THEN '35' ELSE '' END)*/
    GROUP  BY L.CLTCODE 
		
	if @flag = 0
	begin
		INSERT INTO   #B_LEDBAL
		SELECT CLTCODE, VDTLEDBAL = -MTFTOCASHJV
		FROM TBL_PRODUCT_LED_ADJUST
		WHERE SAUDA_DATE = @SAUDA_DATE
	end
		
	INSERT INTO   #B_LEDBAL 
    SELECT L.CLTCODE, 
           VDTLEDBAL = SUM(CASE 
                             WHEN DRCR = 'C' THEN VAMT 
                             ELSE -VAMT 
                           END)     
    FROM    AngelBSECM.ACCOUNT_AB.DBO.LEDGER L,  
		   (SELECT DISTINCT PARTY_CODE		
                             FROM   #B_MTF_DATA ) M	
    WHERE  L.VDT BETWEEN @SDTCUR AND @LDTCUR 
           AND L.VDT <= @SAUDA_DATE + ' 23:59:59' 
           AND L.CLTCODE = PARTY_CODE
		   /*AND VTYP <> (CASE WHEN VDT BETWEEN @SAUDA_DATE AND @SAUDA_DATE + ' 23:59' 
							 THEN '35' ELSE '' END)*/
    GROUP  BY L.CLTCODE 

	INSERT INTO   #B_LEDBAL 
    SELECT L.CLTCODE, 
           VDTLEDBAL = SUM(CASE 
                             WHEN DRCR = 'D' THEN VAMT 
                             ELSE -VAMT 
                           END)     
    FROM   AngelBSECM.ACCOUNT_AB.DBO.LEDGER L,  
		   (SELECT DISTINCT PARTY_CODE		
                             FROM   #B_MTF_DATA ) M	
    WHERE  L.VDT <= @SAUDA_DATE
           AND L.EDT > @SAUDA_DATE + ' 23:59:59' 
           AND L.CLTCODE = PARTY_CODE
		   /*AND VTYP <> (CASE WHEN VDT BETWEEN @SAUDA_DATE AND @SAUDA_DATE + ' 23:59' 
							 THEN '35' ELSE '' END)*/
    GROUP  BY L.CLTCODE 
	
    /*  
     
    INSERT INTO #B_LEDBAL 
    SELECT A.CLTCODE, 
           VDTLEDBAL = SUM(CASE 
                             WHEN DRCR = 'C' THEN VAMT 
                             ELSE -VAMT 
                           END) 
    FROM   ACCOUNTBSE.DBO.LEDGER L, 
           ACCOUNTBSE.DBO.PARAMETER P, 
           ACCOUNTBSE.DBO.ACMAST A 
    WHERE  L.VDT BETWEEN @SDTCUR AND @LDTCUR 
           AND L.VDT <= @SAUDA_DATE + ' 23:59:59' 
           AND L.CLTCODE = A.CLTCODE 
           AND A.ACCAT = 4 
           AND GETDATE() BETWEEN @SDTCUR AND @LDTCUR 
           AND A.CLTCODE IN (SELECT PARTY_CODE 
                             FROM   #B_MTF_DATA 
                             WHERE  PARTY_CODE = A.CLTCODE) 
    GROUP  BY A.CLTCODE       
     
    */ 

	SELECT PARTY_CODE, AMOUNT = SUM(AMOUNT) INTO #B_MTFREVLED FROM (
		SELECT PARTY_CODE, AMOUNT = SUM(NETAMT) FROM TBL_PRODUCT_POSITION
		--WHERE  orgSAUDA_DATE = @SAUDA_DATE --AND SELL_BUY = 1 
		WHERE   SAUDA_DATE = @SAUDA_DATE 
           AND ADJUST_DATE >= @SAUDA_DATE 
           AND SELL_BUY = 1 --AND SETT_NO = '2000000'
		GROUP BY PARTY_CODE
		UNION ALL
		SELECT PARTY_CODE, AMOUNT = -SUM(NETAMT) FROM TBL_PRODUCT_POSITION
		WHERE  SAUDA_DATE <= @SAUDA_DATE AND SELL_BUY = 1 
			   AND ADJUST_DATE = @SAUDA_DATE 
		GROUP BY PARTY_CODE ) A where 1 = 2 
	GROUP BY PARTY_CODE

	INSERT INTO #B_LEDBAL 
	SELECT * FROM #B_MTFREVLED

    UPDATE #B_MTF_DATA 
    SET    CMLEDBAL = VDTLEDBAL 
    FROM   (SELECT CLTCODE, 
                   VDTLEDBAL = SUM(VDTLEDBAL) 
            FROM   #B_LEDBAL 
            GROUP  BY CLTCODE) A 
    WHERE  CLTCODE = PARTY_CODE 

	TRUNCATE TABLE #B_LEDBAL

	UPDATE #B_MTFREVLED SET AMOUNT = -AMOUNT

	INSERT INTO #B_LEDBAL 
	SELECT * FROM #B_MTFREVLED
	
	INSERT INTO #B_LEDBAL 
    SELECT L.CLTCODE, 
           VDTLEDBAL = SUM(CASE 
                             WHEN DRCR = 'C' THEN VAMT 
                             ELSE -VAMT 
                           END)  
    FROM   LEDGER L,  
		   (SELECT DISTINCT PARTY_CODE		
                             FROM   #B_MTF_DATA ) M	
    WHERE  L.VDT BETWEEN @SDTCUR AND @LDTCUR 
           AND L.VDT <= @SAUDA_DATE + ' 23:59:59' 
           AND L.CLTCODE = PARTY_CODE
		   /*AND VTYP <> (CASE WHEN VDT BETWEEN @SAUDA_DATE AND @SAUDA_DATE + ' 23:59' 
							 THEN '35' ELSE '' END)*/
    GROUP  BY L.CLTCODE 

	/*--- ADDED NEW CONDITION FOR NEW MTF 02/07/2025 ----*/
 
	UNION ALL 

	SELECT L.CLTCODE, 
			VDTLEDBAL = SUM(CASE 
								WHEN DRCR = 'C' THEN -VAMT 
								ELSE VAMT 
							END)  
	--SELECT NARRATION,*
	FROM   LEDGER L,  
		   (SELECT DISTINCT PARTY_CODE		
                             FROM   #B_MTF_DATA ) M
	WHERE  L.VDT BETWEEN @SDTCUR AND @LDTCUR 
           AND L.VDT <= @SAUDA_DATE + ' 23:59:59' 
           AND L.CLTCODE = PARTY_CODE
		   AND VTYP IN ('66')
		   /*AND VTYP <> (CASE WHEN VDT BETWEEN @SAUDA_DATE AND @SAUDA_DATE + ' 23:59' 
								THEN '35' ELSE '' END)*/
	GROUP  BY L.CLTCODE   

	/*--- ADDED NEW CONDITION FOR NEW MTF 02/07/2025 ----*/
    /*
	INSERT INTO #B_LEDBAL 
    SELECT L.CLTCODE, 
           VDTLEDBAL = SUM(CASE 
                             WHEN DRCR = 'D' THEN VAMT 
                             ELSE -VAMT 
                           END)  
    FROM   LEDGER L,  
		   (SELECT DISTINCT PARTY_CODE		
                             FROM   #B_MTF_DATA ) M	
    WHERE  L.VDT <= @SAUDA_DATE
           AND EDT > @SAUDA_DATE + ' 23:59:59' 
           AND L.CLTCODE = PARTY_CODE
		   /*AND VTYP <> (CASE WHEN VDT BETWEEN @SAUDA_DATE AND @SAUDA_DATE + ' 23:59' 
							 THEN '35' ELSE '' END)*/
    GROUP  BY L.CLTCODE
	*/
	if @flag = 0
	begin
		INSERT INTO   #B_LEDBAL
		SELECT CLTCODE, VDTLEDBAL = MTFTOCASHJV
		FROM TBL_PRODUCT_LED_ADJUST
		WHERE SAUDA_DATE = @SAUDA_DATE

		INSERT INTO   #B_LEDBAL
		SELECT CLTCODE, VDTLEDBAL = -MTFTOFOJV
		FROM TBL_PRODUCT_LED_ADJUST
		WHERE SAUDA_DATE = @SAUDA_DATE
	end
		
    UPDATE #B_MTF_DATA 
    SET    MTFLEDBAL = VDTLEDBAL 
    FROM   (SELECT CLTCODE, 
                   VDTLEDBAL = SUM(VDTLEDBAL) 
            FROM   #B_LEDBAL 
            GROUP  BY CLTCODE) A 
    WHERE  CLTCODE = PARTY_CODE 

	TRUNCATE TABLE #B_LEDBAL
    INSERT INTO #B_LEDBAL 
    SELECT L.CLTCODE, 
           VDTLEDBAL = SUM(CASE 
                             WHEN DRCR = 'C' THEN VAMT 
                             ELSE -VAMT 
                           END) 
    FROM   ANGELFO.ACCOUNTFO.DBO.LEDGER L, 
		   (SELECT DISTINCT PARTY_CODE		
                             FROM   #B_MTF_DATA ) M 
    WHERE  L.VDT BETWEEN @SDTCUR AND @LDTCUR 
           AND L.VDT <= @SAUDA_DATE + ' 23:59:59' 
           AND L.CLTCODE = PARTY_CODE 
    GROUP  BY L.CLTCODE 

    INSERT INTO #B_LEDBAL 
    SELECT L.CLTCODE, 
           VDTLEDBAL = SUM(CASE 
                             WHEN DRCR = 'D' THEN VAMT 
                             ELSE -VAMT 
                           END) 
    FROM   ANGELFO.ACCOUNTFO.DBO.LEDGER L, 
		   (SELECT DISTINCT PARTY_CODE		
                             FROM   #B_MTF_DATA ) M 
    WHERE  L.VDT >=GETDATE()-10
	       AND L.VDT <= @SAUDA_DATE
           AND L.EDT > @SAUDA_DATE + ' 23:59:59' 
           AND L.CLTCODE = PARTY_CODE 
    GROUP  BY L.CLTCODE 

	INSERT INTO #B_LEDBAL 
    SELECT L.CLTCODE, 
           VDTLEDBAL = SUM(CASE 
                             WHEN DRCR = 'C' THEN VAMT 
                             ELSE -VAMT 
                           END) 
    FROM   ANGELFO.ACCOUNTCURFO.DBO.LEDGER L,  
		   (SELECT DISTINCT PARTY_CODE		
                             FROM   #B_MTF_DATA ) M 
    WHERE  L.VDT BETWEEN @SDTCUR AND @LDTCUR 
           AND L.VDT <= @SAUDA_DATE + ' 23:59:59' 
           AND L.CLTCODE = PARTY_CODE
    GROUP  BY L.CLTCODE 

	INSERT INTO #B_LEDBAL 
    SELECT L.CLTCODE, 
           VDTLEDBAL = SUM(CASE 
                             WHEN DRCR = 'D' THEN VAMT 
                             ELSE -VAMT 
                           END) 
    FROM  ANGELFO.ACCOUNTCURFO.DBO.LEDGER L,  
		   (SELECT DISTINCT PARTY_CODE		
                             FROM   #B_MTF_DATA ) M 
    WHERE  L.VDT <= @SAUDA_DATE 
           AND L.EDT > @SAUDA_DATE + ' 23:59:59' 
           AND L.CLTCODE = PARTY_CODE
    GROUP  BY L.CLTCODE 
	/*********************************NCE LEDGER ADDITION***********************************/

	INSERT INTO #B_LEDBAL 
    SELECT L.CLTCODE, 
           VDTLEDBAL = SUM(CASE 
                             WHEN DRCR = 'C' THEN VAMT 
                             ELSE -VAMT 
                           END) 
    FROM   ANGELCOMMODITY.ACCOUNTNCE.DBO.LEDGER L,  
		   (SELECT DISTINCT PARTY_CODE		
                             FROM   #B_MTF_DATA ) M 
    WHERE  L.VDT BETWEEN @SDTCUR AND @LDTCUR 
           AND L.VDT <= @SAUDA_DATE + ' 23:59:59' 
           AND L.CLTCODE = PARTY_CODE
    GROUP  BY L.CLTCODE 

	INSERT INTO #B_LEDBAL 
    SELECT L.CLTCODE, 
           VDTLEDBAL = SUM(CASE 
                             WHEN DRCR = 'D' THEN VAMT 
                             ELSE -VAMT 
                           END) 
    FROM  ANGELCOMMODITY.ACCOUNTNCE.DBO.LEDGER L,  
		   (SELECT DISTINCT PARTY_CODE		
                             FROM   #B_MTF_DATA ) M 
    WHERE  L.VDT <= @SAUDA_DATE 
           AND L.EDT > @SAUDA_DATE + ' 23:59:59' 
           AND L.CLTCODE = PARTY_CODE
    GROUP  BY L.CLTCODE 
	/********************************END********************************/
	
	INSERT INTO #B_LEDBAL 
    SELECT L.CLTCODE, 
           VDTLEDBAL = SUM(CASE 
                             WHEN DRCR = 'C' THEN VAMT 
                             ELSE -VAMT 
                           END) 
    FROM  ANGELCOMMODITY.ACCOUNTNCDX.DBO.LEDGER L,  
		   (SELECT DISTINCT PARTY_CODE		
                             FROM   #B_MTF_DATA ) M 
    WHERE  L.VDT BETWEEN @SDTCUR AND @LDTCUR 
           AND L.VDT <= @SAUDA_DATE + ' 23:59:59' 
           AND L.CLTCODE = PARTY_CODE
    GROUP  BY L.CLTCODE 

	INSERT INTO #B_LEDBAL 
    SELECT L.CLTCODE, 
           VDTLEDBAL = SUM(CASE 
                             WHEN DRCR = 'D' THEN VAMT 
                             ELSE -VAMT 
                           END) 
    FROM  ANGELCOMMODITY.ACCOUNTNCDX.DBO.LEDGER L,  
		   (SELECT DISTINCT PARTY_CODE		
                             FROM   #B_MTF_DATA ) M 
    WHERE  L.VDT <= @SAUDA_DATE 
           AND L.EDT > @SAUDA_DATE + ' 23:59:59' 
           AND L.CLTCODE = PARTY_CODE
    GROUP  BY L.CLTCODE 

	
	INSERT INTO #B_LEDBAL 
    SELECT L.CLTCODE, 
           VDTLEDBAL = SUM(CASE 
                             WHEN DRCR = 'C' THEN VAMT 
                             ELSE -VAMT 
                           END) 
    FROM   ANGELCOMMODITY.ACCOUNTMCDX.DBO.LEDGER L,  
		   (SELECT DISTINCT PARTY_CODE		
                             FROM   #B_MTF_DATA ) M 
    WHERE  L.VDT BETWEEN @SDTCUR AND @LDTCUR 
           AND L.VDT <= @SAUDA_DATE + ' 23:59:59' 
           AND L.CLTCODE = PARTY_CODE
    GROUP  BY L.CLTCODE 

	INSERT INTO #B_LEDBAL 
    SELECT L.CLTCODE, 
           VDTLEDBAL = SUM(CASE 
                             WHEN DRCR = 'D' THEN VAMT 
                             ELSE -VAMT 
                           END) 
    FROM  ANGELCOMMODITY.ACCOUNTMCDX.DBO.LEDGER L,  
		   (SELECT DISTINCT PARTY_CODE		
                             FROM   #B_MTF_DATA ) M 
    WHERE  L.VDT <= @SAUDA_DATE 
           AND L.EDT > @SAUDA_DATE + ' 23:59:59' 
           AND L.CLTCODE = PARTY_CODE
    GROUP  BY L.CLTCODE 

	if @flag = 0
	begin
		INSERT INTO   #B_LEDBAL
		SELECT CLTCODE, VDTLEDBAL = MTFTOFOJV
		FROM TBL_PRODUCT_LED_ADJUST
		WHERE SAUDA_DATE = @SAUDA_DATE
	end
		
    UPDATE #B_MTF_DATA 
    SET    FOLEDBAL = VDTLEDBAL 
    FROM   (SELECT CLTCODE, 
                   VDTLEDBAL = SUM(VDTLEDBAL) 
            FROM   #B_LEDBAL 
            GROUP  BY CLTCODE) A 
    WHERE  CLTCODE = PARTY_CODE 

    UPDATE #B_MTF_DATA 
    SET    CMCASHCOLLATERAL = CASH - TOTALFD - TOTALBG
    FROM   MSAJAG.DBO.COLLATERAL C 
    WHERE  TRANS_DATE = (SELECT MAX(TRANS_DATE) 
                         FROM   MSAJAG.DBO.COLLATERAL C1 
                         WHERE  C1.TRANS_DATE <= @SAUDA_DATE + ' 23:59') 
           AND C.PARTY_CODE = #B_MTF_DATA.PARTY_CODE 
		   AND EXCHANGE NOT IN ('MCX', 'NCX')
		   AND SEGMENT = 'CAPITAL'  AND (CASH - TOTALFD - TOTALBG) > 0 

    UPDATE #B_MTF_DATA 
    SET    CMCASHEQCOLLATERAL = TOTALFD + TOTALBG
    FROM   MSAJAG.DBO.COLLATERAL C 
    WHERE  TRANS_DATE = (SELECT MAX(TRANS_DATE) 
                         FROM   MSAJAG.DBO.COLLATERAL C1 
                         WHERE  C1.TRANS_DATE <= @SAUDA_DATE + ' 23:59') 
           AND C.PARTY_CODE = #B_MTF_DATA.PARTY_CODE 
		   AND EXCHANGE NOT IN ('MCX', 'NCX')
		   AND SEGMENT = 'CAPITAL'   

	UPDATE #B_MTF_DATA 
    SET    CMNONCASHCOLLATERAL = CMNONCASHCOLLATERAL + NONCASH,
		   CMNONCASHCOLLATERAL_MTF = CMNONCASHCOLLATERAL_MTF + NONCASHMTF
	FROM   (SELECT PARTY_CODE, NONCASH = SUM(QTY*CL_RATE - QTY*CL_RATE*HAIRCUT/100),
			NONCASHMTF = SUM(CASE WHEN FOGFLAG = 1 THEN QTY*CL_RATE - QTY*CL_RATE*HAIRCUT/100 ELSE 0 END)
			FROM TBL_PRODUCT_HOLD_DATA
			WHERE SAUDA_DATE = @SAUDA_DATE AND HOLDFLAG IN ('CMCOLL','CMCOLL_P')
			GROUP BY PARTY_CODE ) A
	WHERE  #B_MTF_DATA.PARTY_CODE = A.PARTY_CODE

    UPDATE #B_MTF_DATA 
    SET    FOCASHCOLLATERAL = CASH - TOTALFD - TOTALBG
    FROM   MSAJAG.DBO.COLLATERAL C 
    WHERE  TRANS_DATE = (SELECT MAX(TRANS_DATE) 
                         FROM   MSAJAG.DBO.COLLATERAL C1 
                         WHERE  C1.TRANS_DATE <= @SAUDA_DATE + ' 23:59') 
           AND C.PARTY_CODE = #B_MTF_DATA.PARTY_CODE 
		   AND EXCHANGE NOT IN ('MCX', 'NCX')
		   AND SEGMENT = 'FUTURES' AND (CASH - TOTALFD - TOTALBG) > 0 

    UPDATE #B_MTF_DATA 
    SET    FOCASHEQCOLLATERAL = TOTALFD + TOTALBG
    FROM   MSAJAG.DBO.COLLATERAL C 
    WHERE  TRANS_DATE = (SELECT MAX(TRANS_DATE) 
                         FROM   MSAJAG.DBO.COLLATERAL C1 
                         WHERE  C1.TRANS_DATE <= @SAUDA_DATE + ' 23:59') 
           AND C.PARTY_CODE = #B_MTF_DATA.PARTY_CODE 
		   AND EXCHANGE NOT IN ('MCX', 'NCX')
		   AND SEGMENT = 'FUTURES' 


	UPDATE #B_MTF_DATA 
    SET    FONONCASHCOLLATERAL = FONONCASHCOLLATERAL + NONCASH,
		   FONONCASHCOLLATERAL_MTF = FONONCASHCOLLATERAL_MTF + NONCASHMTF
	FROM   (SELECT PARTY_CODE, NONCASH = SUM(QTY*CL_RATE - QTY*CL_RATE*HAIRCUT/100),
			NONCASHMTF = SUM(CASE WHEN FOGFLAG = 1 THEN QTY*CL_RATE - QTY*CL_RATE*HAIRCUT/100 ELSE 0 END)
			FROM TBL_PRODUCT_HOLD_DATA
			WHERE SAUDA_DATE = @SAUDA_DATE AND HOLDFLAG IN ('FOCOLL', 'FOCOLL_P')
			GROUP BY PARTY_CODE ) A
	WHERE  #B_MTF_DATA.PARTY_CODE = A.PARTY_CODE

    UPDATE #B_MTF_DATA 
    SET    MTFCASHCOLLATERAL = CASH - TOTALFD - TOTALBG  
    FROM   MSAJAG.DBO.COLLATERAL C 
    WHERE  TRANS_DATE = (SELECT MAX(TRANS_DATE) 
               FROM   MSAJAG.DBO.COLLATERAL C1 
                         WHERE  C1.TRANS_DATE <= @SAUDA_DATE + ' 23:59') 
           AND C.PARTY_CODE = #B_MTF_DATA.PARTY_CODE 
		   AND EXCHANGE = 'MTF'
		   AND SEGMENT = 'MTF' AND (CASH - TOTALFD - TOTALBG) > 0

    UPDATE #B_MTF_DATA 
    SET    MTFCASHEQCOLLATERAL = TOTALFD + TOTALBG  
    FROM   MSAJAG.DBO.COLLATERAL C 
    WHERE  TRANS_DATE = (SELECT MAX(TRANS_DATE) 
                         FROM   MSAJAG.DBO.COLLATERAL C1 
                         WHERE  C1.TRANS_DATE <= @SAUDA_DATE + ' 23:59') 
           AND C.PARTY_CODE = #B_MTF_DATA.PARTY_CODE 
		   AND EXCHANGE = 'MTF'
		   AND SEGMENT = 'MTF'  

	UPDATE #B_MTF_DATA 
    SET    MTFNONCASHCOLLATERAL = MTFNONCASHCOLLATERAL + NONCASH
	FROM   (SELECT PARTY_CODE, NONCASH = SUM(QTY*CL_RATE - QTY*CL_RATE*HAIRCUT/100)
			FROM TBL_PRODUCT_HOLD_DATA
			WHERE SAUDA_DATE = @SAUDA_DATE AND HOLDFLAG IN ('MTFCOLL','MTFCOLL_P')
			GROUP BY PARTY_CODE ) A
	WHERE  #B_MTF_DATA.PARTY_CODE = A.PARTY_CODE

	UPDATE #B_MTF_DATA 
    SET    POAHOLDING = NONCASH,
		   POAHOLDING_MTF = NONCASHMTF
	FROM   (SELECT PARTY_CODE, NONCASH = SUM(QTY*CL_RATE - QTY*CL_RATE*HAIRCUT/100),
			NONCASHMTF = SUM(CASE WHEN FOGFLAG = 1 THEN QTY*CL_RATE - QTY*CL_RATE*HAIRCUT/100 ELSE 0 END)
			FROM TBL_PRODUCT_HOLD_DATA
			WHERE SAUDA_DATE = @SAUDA_DATE
			AND HOLDFLAG IN ('POA', 'POA_P')
			GROUP BY PARTY_CODE ) A
	WHERE  #B_MTF_DATA.PARTY_CODE = A.PARTY_CODE

	UPDATE #B_MTF_DATA 
    SET    CMDEBITHOLD = NONCASH,
		   CMDEBITHOLD_MTF = 0--NONCASHMTF
	FROM   (SELECT PARTY_CODE, NONCASH = SUM(QTY*CL_RATE - QTY*CL_RATE*HAIRCUT/100),
			NONCASHMTF = SUM(CASE WHEN FOGFLAG = 1 THEN QTY*CL_RATE - QTY*CL_RATE*HAIRCUT/100 ELSE 0 END)
			FROM TBL_PRODUCT_HOLD_DATA
			WHERE SAUDA_DATE = @SAUDA_DATE
			AND HOLDFLAG IN ('BEN', 'BEN_P', 'EPN')
			GROUP BY PARTY_CODE ) A
	WHERE  #B_MTF_DATA.PARTY_CODE = A.PARTY_CODE

	
	UPDATE #B_MTF_DATA 
    SET    CMDEBITHOLD = CMDEBITHOLD + NONCASH 
	FROM   (SELECT PARTY_CODE, NONCASH = SUM(QTY*CL_RATE - QTY*CL_RATE*HAIRCUT/100) 
			FROM TBL_PRODUCT_HOLD_DATA
			WHERE SAUDA_DATE = @SAUDA_DATE
			AND HOLDFLAG IN ('BEN_C')
			GROUP BY PARTY_CODE ) A
	WHERE  #B_MTF_DATA.PARTY_CODE = A.PARTY_CODE

	/*
	UPDATE #B_MTF_DATA 
    SET    CMOPENPOS = NONCASH
	FROM   (SELECT PARTY_CODE, NONCASH = SUM(QTY*CL_RATE - QTY*CL_RATE*HAIRCUT/100)
			FROM TBL_PRODUCT_HOLD_DATA
			WHERE SAUDA_DATE = @SAUDA_DATE AND HOLDFLAG = '1 BTST POSITION'
			GROUP BY PARTY_CODE ) A
	WHERE  #B_MTF_DATA.PARTY_CODE = A.PARTY_CODE
	*/
    UPDATE #B_MTF_DATA 
    SET    FOMARGIN = TOTALMARGIN--SPREADMARGIN + MTOM 
    FROM   ANGELFO.NSEFO.DBO.FOMARGINNEW C 
    WHERE  MDATE = (SELECT MAX(MDATE) 
                    FROM    ANGELFO.NSEFO.DBO.FOMARGINNEW C1 
                    WHERE  C1.MDATE <= @SAUDA_DATE + ' 23:59') 
           AND C.PARTY_CODE = #B_MTF_DATA.PARTY_CODE
	
	/* --SRE-42095
	--- COMMENTED ON 01112025 BY INDER  TO NOT BLOCK CASH MARGING WHILE FETCHING COLLATERAL FROM CM LEDGER TO MTF SEGMENT
	UPDATE #B_MTF_DATA 
    SET    FOMARGIN = FOMARGIN + (CASE WHEN TOTAL_MARGIN > PEAKMARGIN THEN TOTAL_MARGIN ELSE PEAKMARGIN END)
    FROM   MSAJAG.DBO.TBL_CMMARGIN C 
    WHERE  MARGINDATE = (SELECT MAX(MARGINDATE) 
                    FROM    MSAJAG.DBO.TBL_CMMARGIN C1 
                    WHERE  C1.MARGINDATE <= @SAUDA_DATE + ' 23:59') 
           AND C.PARTY_CODE = #B_MTF_DATA.PARTY_CODE 
--- COMMENTED ON 01112025 BY INDER  TO NOT BLOCK CASH MARGING WHILE FETCHING COLLATERAL FROM CM LEDGER TO MTF SEGMENT
*/ --SRE-42095
    
	
	UPDATE #B_MTF_DATA 
    SET    FOMARGIN = FOMARGIN + TOTALMARGIN--FOMARGIN + SPREADMARGIN + MTOM 
    FROM   ANGELFO.NSECURFO.DBO.FOMARGINNEW C 
    WHERE  MDATE = (SELECT MAX(MDATE) 
                    FROM    ANGELFO.NSECURFO.DBO.FOMARGINNEW C1 
                    WHERE  C1.MDATE <= @SAUDA_DATE + ' 23:59') 
           AND C.PARTY_CODE = #B_MTF_DATA.PARTY_CODE 

		   
    UPDATE #B_MTF_DATA 
    SET    FOMARGIN = FOMARGIN + TOTALMARGIN--FOMARGIN + SPREADMARGIN + MTOM 
    FROM   ANGELCOMMODITY.MCDX.DBO.FOMARGINNEW C 
    WHERE  MDATE = (SELECT MAX(MDATE) 
                    FROM    ANGELCOMMODITY.MCDX.DBO.FOMARGINNEW C1 
                    WHERE  C1.MDATE <= @SAUDA_DATE + ' 23:59') 
           AND C.PARTY_CODE = #B_MTF_DATA.PARTY_CODE 
		   
    UPDATE #B_MTF_DATA 
    SET    FOMARGIN = FOMARGIN + TOTALMARGIN--FOMARGIN + SPREADMARGIN + MTOM 
    FROM   ANGELCOMMODITY.NCDX.DBO.FOMARGINNEW C 
    WHERE  MDATE = (SELECT MAX(MDATE) 
                    FROM    ANGELCOMMODITY.NCDX.DBO.FOMARGINNEW C1 
                    WHERE  C1.MDATE <= @SAUDA_DATE + ' 23:59') 
           AND C.PARTY_CODE = #B_MTF_DATA.PARTY_CODE 


/************************NCE MARGIN ADDIITON*************************/
    UPDATE #B_MTF_DATA 
    SET    FOMARGIN = FOMARGIN + TOTALMARGIN--FOMARGIN + SPREADMARGIN + MTOM 
    FROM   ANGELCOMMODITY.NCE.DBO.FOMARGINNEW C 
    WHERE  MDATE = (SELECT MAX(MDATE) 
                    FROM    ANGELCOMMODITY.NCE.DBO.FOMARGINNEW C1 
                    WHERE  C1.MDATE <= @SAUDA_DATE + ' 23:59') 
           AND C.PARTY_CODE = #B_MTF_DATA.PARTY_CODE 

/*******************************END*************************************/

	DELETE FROM TBL_MTF_DATA
	WHERE SAUDA_DATE = @SAUDA_DATE

	INSERT INTO TBL_MTF_DATA
	SELECT SAUDA_DATE,PARTY_CODE,SCRIP_CD,SERIES,BSECODE,ISIN, 
    QTY = SUM(QTY), 
    MKTAMT = SUM(MKTAMT), 
    NETAMT = SUM(NETAMT), 
    CL_RATE,CURR_CL_RATE,HAIRCUT,MARGIN_REQ=SUM(MARGIN_REQ),MTOM_LOSS=SUM(MTOM_LOSS),FOMARGIN,
	CMLEDBAL,MTFLEDBAL,FOLEDBAL,CMCASHEQCOLLATERAL,CMCASHCOLLATERAL,
	CMNONCASHCOLLATERAL,CMNONCASHCOLLATERAL_MTF,CMDEBITHOLD,CMDEBITHOLD_MTF,
	CMOPENPOS,MTFCASHEQCOLLATERAL,MTFCASHCOLLATERAL,MTFNONCASHCOLLATERAL,
	FOCASHEQCOLLATERAL,FOCASHCOLLATERAL,FONONCASHCOLLATERAL,FONONCASHCOLLATERAL_MTF,
	NET_AVL_FUND,POAHOLDING,POAHOLDING_MTF,SELLSHORT,
	CASHDEBITADJ = 0,
	CASHNONCASHADJ = 0,
	FONONCASHADJ = 0,
	CASHLEDADJ = 0,
	FOLEDBALADJ = 0,
	POAADJ = 0/*,
	ORG_SAUDA_DATE*/
	FROM #B_MTF_DATA
	GROUP BY SAUDA_DATE,PARTY_CODE,SCRIP_CD,SERIES,BSECODE,ISIN,
	CL_RATE,CURR_CL_RATE,HAIRCUT--,MARGIN_REQ,MTOM_LOSS
	,FOMARGIN,	CMLEDBAL,MTFLEDBAL,FOLEDBAL,CMCASHEQCOLLATERAL,CMCASHCOLLATERAL,
	CMNONCASHCOLLATERAL,CMNONCASHCOLLATERAL_MTF,CMDEBITHOLD,CMDEBITHOLD_MTF,
	CMOPENPOS,MTFCASHEQCOLLATERAL,MTFCASHCOLLATERAL,MTFNONCASHCOLLATERAL,
	FOCASHEQCOLLATERAL,FOCASHCOLLATERAL,FONONCASHCOLLATERAL,FONONCASHCOLLATERAL_MTF,
	NET_AVL_FUND,POAHOLDING,POAHOLDING_MTF,SELLSHORT --,ORG_SAUDA_DATE

	/*--- START NEW MTF CHANGES ---*/

	DELETE FROM TBL_MTF_DATA_BUY
	WHERE SAUDA_DATE = @SAUDA_DATE

	INSERT	INTO TBL_MTF_DATA_BUY
	SELECT SAUDA_DATE,PARTY_CODE,SCRIP_CD,SERIES,BSECODE,ISIN,QTY,
	MKTAMT,NETAMT,CL_RATE,CURR_CL_RATE,HAIRCUT,MARGIN_REQ,MTOM_LOSS,FOMARGIN,
	CMLEDBAL,MTFLEDBAL,FOLEDBAL,CMCASHEQCOLLATERAL,CMCASHCOLLATERAL,
	CMNONCASHCOLLATERAL,CMNONCASHCOLLATERAL_MTF,CMDEBITHOLD,CMDEBITHOLD_MTF,
	CMOPENPOS,MTFCASHEQCOLLATERAL,MTFCASHCOLLATERAL,MTFNONCASHCOLLATERAL,
	FOCASHEQCOLLATERAL,FOCASHCOLLATERAL,FONONCASHCOLLATERAL,FONONCASHCOLLATERAL_MTF,
	NET_AVL_FUND,POAHOLDING,POAHOLDING_MTF,SELLSHORT,
	CASHDEBITADJ = 0,
	CASHNONCASHADJ = 0,
	FONONCASHADJ = 0,
	CASHLEDADJ = 0,
	FOLEDBALADJ = 0,
	POAADJ = 0,
	ORG_HAIRCUT = HAIRCUT,
	ORG_MARGIN_REQ = MARGIN_REQ,
	SETT_NO,
	PAYIN_DATE,
	TRANSTYPE
	FROM #B_MTF_DATA  
	WHERE MTF_FLAG = 1

	/*--- END NEW MTF CHANGES ---*/

	/*	INSERT INTO TBL_MTF_DATA_LOG
	SELECT SAUDA_DATE,PARTY_CODE,SCRIP_CD,SERIES,BSECODE,ISIN,QTY,
	MKTAMT,NETAMT,CL_RATE,CURR_CL_RATE,HAIRCUT,MARGIN_REQ,MTOM_LOSS,FOMARGIN,
	CMLEDBAL,MTFLEDBAL,FOLEDBAL,CMCASHEQCOLLATERAL,CMCASHCOLLATERAL,
	CMNONCASHCOLLATERAL,CMNONCASHCOLLATERAL_MTF,CMDEBITHOLD,CMDEBITHOLD_MTF,
	CMOPENPOS,MTFCASHEQCOLLATERAL,MTFCASHCOLLATERAL,MTFNONCASHCOLLATERAL,
	FOCASHEQCOLLATERAL,FOCASHCOLLATERAL,FONONCASHCOLLATERAL,FONONCASHCOLLATERAL_MTF,
	NET_AVL_FUND,POAHOLDING,POAHOLDING_MTF,SELLSHORT,
	CASHDEBITADJ = 0,
	CASHNONCASHADJ = 0,
	FONONCASHADJ = 0,
	CASHLEDADJ = 0,
	FOLEDBALADJ = 0,
	POAADJ = 0
	FROM #B_MTF_DATA*/--ADDED SURESH

/*
    SELECT PARTY_CODE,
           NETFUNDREQ = ( CASE 
                            WHEN SUM(-MARGIN_REQ + MKTAMT) - FOMARGIN + LEDBAL + 
                                 COLLATERAL 
                                 - SUM( 
                                 MTOM_LOSS) > 0 THEN SUM(CASE 
                          WHEN @SAUDA_DATE = SAUDA_DATE THEN MKTAMT - NETAMT 
                 ELSE 0 
                          END) 
                            ELSE SUM(-MARGIN_REQ + MKTAMT) - FOMARGIN + LEDBAL + 
                                 COLLATERAL 
                                 - SUM( 
                                 MTOM_LOSS) 
                          END ) 
    INTO   #B_FUND_REQ 
    FROM   #B_MTF_DATA 
    GROUP  BY PARTY_CODE, 
              FOMARGIN, 
              LEDBAL, 
              COLLATERAL 

    UPDATE #B_MTF_DATA 
    SET    NET_AVL_FUND = NETFUNDREQ 
    FROM   #B_FUND_REQ 
    WHERE  #B_FUND_REQ.PARTY_CODE = #B_MTF_DATA.PARTY_CODE 

    DELETE FROM TBL_PRODUCT_DETAIL 
    WHERE  RUNDATE = @SAUDA_DATE 

    INSERT INTO TBL_PRODUCT_DETAIL 
    SELECT RUNDATE=CONVERT(DATETIME, @SAUDA_DATE), 
           *, 
           PROCESS_ON = GETDATE(), 
           PROCESS_BY = ''
    FROM   #B_MTF_DATA 

    DROP TABLE #B_MTF_DATA 

    DROP TABLE #B_LEDBAL 

    DROP TABLE #B_FUND_REQ 

    DROP TABLE #B_NRML_DATE   
*/

GO
