-- Object: PROCEDURE dbo.PROC_MTF_CHECK
-- Server: 10.253.33.91 | DB: MTFTRADE
--------------------------------------------------

CREATE PROC [dbo].[PROC_MTF_CHECK]
(
	@SAUDA_DATE VARCHAR(11)
)
AS

-- EXEC PROC_MTF_CHECK 'FEB 27 2020'

DECLARE @SDTCUR		DATETIME,
		@LDTCUR		DATETIME

SELECT @SDTCUR = SDTCUR, @LDTCUR = LDTCUR FROM ACCOUNT.DBO.PARAMETER 
WHERE @SAUDA_DATE BETWEEN SDTCUR AND LDTCUR 

SELECT DISTINCT PARTY_CODE INTO #MTFREJECT FROM TBL_PRODUCT_POSITION 
WHERE  SAUDA_DATE = @SAUDA_DATE AND SELL_BUY = 1     
AND ADJUST_DATE > @SAUDA_DATE

CREATE INDEX #PARTY ON #MTFREJECT(PARTY_CODE)


SELECT L.CLTCODE,     
           VDTLEDBAL = SUM(CASE     
                             WHEN DRCR = 'C' THEN VAMT     
                             ELSE -VAMT     
                           END)     
    INTO   #P_LEDBAL     
    FROM   ACCOUNT.DBO.LEDGER L (NOLOCK),      
     (SELECT DISTINCT PARTY_CODE      
                             FROM   #MTFREJECT (NOLOCK) ) M     
    WHERE  L.VDT BETWEEN @SDTCUR AND @LDTCUR     
           AND L.VDT <= @SAUDA_DATE + ' 23:59:59'     
           AND L.CLTCODE = PARTY_CODE    
     AND VTYP <> (CASE WHEN VDT BETWEEN @SAUDA_DATE AND @SAUDA_DATE + ' 23:59'     
        THEN '35' ELSE '' END)     
    GROUP  BY L.CLTCODE     
       
    INSERT INTO #P_LEDBAL     
    SELECT L.CLTCODE,     
           VDTLEDBAL = SUM(CASE     
                             WHEN DRCR = 'C' THEN VAMT     
                             ELSE -VAMT     
                           END)     
    FROM   AngelBSECM.ACCOUNT_AB.DBO.LEDGER L  ,      
     (SELECT DISTINCT PARTY_CODE      
                             FROM   #MTFREJECT ) M     
    WHERE  L.VDT BETWEEN @SDTCUR AND @LDTCUR     
           AND L.VDT <= @SAUDA_DATE + ' 23:59:59'     
           AND L.CLTCODE = PARTY_CODE    
     AND VTYP <> (CASE WHEN VDT BETWEEN @SAUDA_DATE AND @SAUDA_DATE + ' 23:59'     
        THEN '35' ELSE '' END)    
    GROUP  BY L.CLTCODE       

CREATE TABLE #P_MTFREVLED
(
	PARTY_CODE	VARCHAR(10),
	AMOUNT		NUMERIC(18,2)
)

DECLARE @NARR VARCHAR(100)
SELECT @NARR = 'SETTNO='+SETT_NO+'NSECM'+LTRIM(RTRIM(SETT_TYPE))+'BILL POSTED' 
FROM MSAJAG.DBO.SETT_MST WHERE START_DATE = @SAUDA_DATE AND SETT_TYPE = 'N'

IF (SELECT ISNULL(COUNT(1),0) FROM ACCOUNT.DBO.LEDGER 
WHERE VDT = @SAUDA_DATE AND VTYP = 15 AND NARRATION = @NARR ) > 0
BEGIN 
	INSERT INTO #P_MTFREVLED
	SELECT PARTY_CODE, AMOUNT = SUM(AMOUNT) FROM (    
	SELECT PARTY_CODE, AMOUNT = -SUM(NETAMT) FROM TBL_PRODUCT_POSITION    
	WHERE  SAUDA_DATE <= @SAUDA_DATE AND SELL_BUY = 1     
	AND ADJUST_DATE = @SAUDA_DATE     
	GROUP BY PARTY_CODE 
	UNION ALL    
	SELECT PARTY_CODE, AMOUNT = SUM(NETAMT) FROM TBL_PRODUCT_POSITION    
	WHERE  SAUDA_DATE = @SAUDA_DATE AND SELL_BUY = 1  
	AND ADJUST_DATE = @SAUDA_DATE 
	GROUP BY PARTY_CODE ) A    
	GROUP BY PARTY_CODE  
END
ELSE
BEGIN
	INSERT INTO #P_MTFREVLED
	SELECT PARTY_CODE, AMOUNT = -SUM(NETAMT) FROM TBL_PRODUCT_POSITION    
	WHERE  SAUDA_DATE = @SAUDA_DATE AND SELL_BUY = 1  
	AND ADJUST_DATE > @SAUDA_DATE 
	GROUP BY PARTY_CODE 
END

INSERT INTO #P_LEDBAL     
SELECT * FROM #P_MTFREVLED  

INSERT INTO #P_LEDBAL     
SELECT L.CLTCODE,     
        VDTLEDBAL = SUM(CASE     
                            WHEN DRCR = 'C' THEN VAMT     
                            ELSE -VAMT     
                        END)     
FROM   ANGELFO.ACCOUNTFO.DBO.LEDGER L,     
    (SELECT DISTINCT PARTY_CODE      
                            FROM   #MTFREJECT ) M     
WHERE  L.VDT BETWEEN @SDTCUR AND @LDTCUR     
        AND L.VDT <= @SAUDA_DATE + ' 23:59:59'     
        AND L.CLTCODE = PARTY_CODE     
GROUP  BY L.CLTCODE     

INSERT INTO #P_LEDBAL     
SELECT L.CLTCODE,     
        VDTLEDBAL = SUM(CASE     
                            WHEN DRCR = 'C' THEN VAMT     
                            ELSE -VAMT     
                        END)     
FROM   ANGELFO.ACCOUNTCURFO.DBO.LEDGER L,     
    (SELECT DISTINCT PARTY_CODE      
                            FROM   #MTFREJECT ) M     
WHERE  L.VDT BETWEEN @SDTCUR AND @LDTCUR     
        AND L.VDT <= @SAUDA_DATE + ' 23:59:59'     
        AND L.CLTCODE = PARTY_CODE     
GROUP  BY L.CLTCODE 

INSERT INTO #P_LEDBAL     
SELECT L.CLTCODE,     
        VDTLEDBAL = SUM(CASE     
                            WHEN DRCR = 'C' THEN VAMT     
                            ELSE -VAMT     
                        END)     
FROM   ANGELCOMMODITY.ACCOUNTNCDX.DBO.LEDGER L,     
    (SELECT DISTINCT PARTY_CODE      
                            FROM   #MTFREJECT ) M     
WHERE  L.VDT BETWEEN @SDTCUR AND @LDTCUR     
        AND L.VDT <= @SAUDA_DATE + ' 23:59:59'     
        AND L.CLTCODE = PARTY_CODE     
GROUP  BY L.CLTCODE 

INSERT INTO #P_LEDBAL     
SELECT L.CLTCODE,     
        VDTLEDBAL = SUM(CASE     
                            WHEN DRCR = 'C' THEN VAMT     
                            ELSE -VAMT     
                        END)     
FROM   ANGELCOMMODITY.ACCOUNTMCDX.DBO.LEDGER L,     
    (SELECT DISTINCT PARTY_CODE      
                            FROM   #MTFREJECT ) M     
WHERE  L.VDT BETWEEN @SDTCUR AND @LDTCUR     
        AND L.VDT <= @SAUDA_DATE + ' 23:59:59'     
        AND L.CLTCODE = PARTY_CODE     
GROUP  BY L.CLTCODE 

/* Margin Addition */

 DECLARE @MAXDT_M DATETIME ,@PREVDT_M DATETIME

 SELECT @MAXDT_M = MAX(UPDATEDDATE)  FROM [CSOKYC-6].GENERAL.DBO.NCMS_LD_API_UAT  WITH(NOLOCK)

  SELECT CLIENT_CODE ,MARGIN=SUM((MCX_SPAN+MCX_MVM)+(NCDX_SPAN+NCDX_MVM)+(NSEC_SPAN+NSEC_MVM)+(MCXC_SPAN+MCXC_MVM+NSEF_SPAN+NSEF_MVM) )  INTO #MARGIN
  FROM [CSOKYC-6].GENERAL.DBO.NCMS_LD_API_UAT WITH(NOLOCK) WHERE  UPDATEDDATE = @MAXDT_M
   GROUP BY CLIENT_CODE
  HAVING SUM( (MCX_SPAN+MCX_MVM)+(NCDX_SPAN+NCDX_MVM)+(NSEC_SPAN+NSEC_MVM)+(MCXC_SPAN+MCXC_MVM+NSEF_SPAN+NSEF_MVM) ) <>0
 

   SELECT @PREVDT_M=MAX(EFFDATE)
  FROM MSAJAG.DBO.COLLATERALDETAILS (NOLOCK) WHERE EFFDATE >=GETDATE()-5

    SELECT PARTY_CODE,MARGIN=SUM(FINALAMOUNT) INTO #NONCASH
  FROM MSAJAG.DBO.COLLATERALDETAILS (NOLOCK) WHERE EFFDATE >=@PREVDT_M GROUP BY PARTY_CODE


  SELECT M.*,ISNULL(N.MARGIN,0) AS NC , NET=( -M.MARGIN+ISNULL(N.MARGIN,0)) INTO #FINAL_NET  FROM #MARGIN M
  LEFT OUTER JOIN 
  #NONCASH N ON CLIENT_CODE=PARTY_CODE
  
  INSERT INTO #P_LEDBAL
  SELECT CLIENT_CODE,NET FROM #FINAL_NET WHERE NET <-500

  /*Margin addition Completed */
  /* MTF Stock auto closure Consideration 
   Date : 2023-09-26
   Added :  K Siva Kumar*/
 
  SELECT  PARTY_CODE,TOTALRELEASEVALUE=SUM(TOTALRELEASEVALUE) INTO #MTF_RELEASE FROM INTRANET.CMS.DBO.MTF_AUTORELEASE WITH(NOLOCK)
  GROUP BY PARTY_CODE

  INSERT INTO #P_LEDBAL
  SELECT  PARTY_CODE,TOTALRELEASEVALUE=TOTALRELEASEVALUE*-1 FROM #MTF_RELEASE WITH(NOLOCK)
  ---GROUP BY PARTY_CODE  

  /*End*/
   

SELECT CLTCODE, VDTLEDBAL = SUM(VDTLEDBAL)
INTO #MTFREJECTCODE
FROM   #P_LEDBAL
GROUP BY CLTCODE
HAVING SUM(VDTLEDBAL) >= -500


  /* Credit Balance Client Addition Based on RMTF
   Modify : Direct Payout
   Date: 2024-11-08
   Changed By : Siva Kumar
   Approved by : Rahul Shah*/
 
 SELECT DISTINCT PARTY_CODE INTO #RMTF FROM  ANGELDEMAT.INHOUSE.DBO.TBL_POA_PLD_ADNL_RMTF WITH(NOLOCK) 
 WHERE TRANSDATE>=@SAUDA_DATE  AND TRANSDATE<=  @SAUDA_DATE +' 23:59:59'

 CREATE INDEX #PARTY ON #RMTF(PARTY_CODE)

 DELETE FROM #MTFREJECTCODE  WHERE EXISTS (SELECT PARTY_CODE FROM #RMTF WHERE PARTY_CODE=CLTCODE)


  /* Credit Balance Client Addition Based on RMTF*/


DELETE FROM TBL_MTFREJECTCODE
WHERE SAUDA_DATE = @SAUDA_DATE

INSERT  INTO TBL_MTFREJECTCODE
SELECT SAUDA_DATE = @SAUDA_DATE, *, RUNDATE=GETDATE()
FROM #MTFREJECTCODE

/*
DECLARE @SAUDA_DATE VARCHAR(11),
		@SDTCUR		DATETIME,
		@LDTCUR		DATETIME

SET @SAUDA_DATE = 'FEB 18 2020'
SET @SDTCUR		= 'APR  1 2019'
SET @LDTCUR		= 'MAR 31 2020 23:59:59'
*/
DELETE FROM TBL_PRODUCT_POSITION    
WHERE  SAUDA_DATE = @SAUDA_DATE AND SELL_BUY = 1     
AND ADJUST_DATE > @SAUDA_DATE 
AND PARTY_CODE IN (SELECT CLTCODE FROM TBL_MTFREJECTCODE
				   WHERE SAUDA_DATE = @SAUDA_DATE AND PARTY_CODE = CLTCODE) 
AND SETT_NO <> '2000000'

GO
