-- Object: PROCEDURE dbo.PROC_PRODUCT_BUY_ADJUST_BAK_25112020
-- Server: 10.253.33.91 | DB: MTFTRADE
--------------------------------------------------



-- EXEC PROC_PRODUCT_BUY_ADJUST 'JUL 11 2017'
Create  PROC [dbo].[PROC_PRODUCT_BUY_ADJUST_BAK_25112020] (@SAUDA_DATE VARCHAR(11), @flag int = 0 ) 
AS  
    DECLARE @PAYIN_DATE VARCHAR(11),
			@SDTCUR	DATETIME,
			@LDTCUR	DATETIME,
			@NONFNO	INT,
			@FNO	INT,
			@PREV_DATE varchar(11),
			@MTFCOLLVAR INT	

	SET NOCOUNT ON 

	SELECT @PREV_DATE = left(ISNULL(MAX(SYSDATE),@SAUDA_DATE),11) FROM   MSAJAG.DBO.CLOSING C 
	WHERE SYSDATE < @SAUDA_DATE 

	SELECT @NONFNO = NONFNO, @FNO = FNO, @MTFCOLLVAR = MTFCOLLVAR FROM TBL_MTF_MULTIPLIER
	WHERE @SAUDA_DATE BETWEEN FROMDATE AND TODATE

	SELECT @SDTCUR = SDTCUR, @LDTCUR = LDTCUR FROM ACCOUNT.DBO.PARAMETER 
	WHERE @SAUDA_DATE BETWEEN SDTCUR AND LDTCUR  

	SELECT  PARTY_CODE, AMOUNT = SUM(NETAMT), SANC_LIM = CONVERT(NUMERIC(18,0),0)
	INTO #B_PFVALUE
	FROM  TBL_PRODUCT_POSITION 
    WHERE SAUDA_DATE <= @SAUDA_DATE 
           AND ADJUST_DATE > @SAUDA_DATE 
           AND SELL_BUY = 1
	GROUP BY PARTY_CODE

	UPDATE #B_PFVALUE SET SANC_LIM = SANCTIONED_AMT
	FROM TBLCLIENTMARGIN P
	WHERE P.PARTY_CODE = #B_PFVALUE.PARTY_CODE
	AND @SAUDA_DATE BETWEEN FROM_DATE AND TO_DATE

	DELETE FROM #B_PFVALUE
	--WHERE (AMOUNT <= SANC_LIM OR SANC_LIM = -1)

	DECLARE @PFCUR		CURSOR,
			@PARTY_CODE	VARCHAR(10),
			@AMOUNT		NUMERIC(18,4),
			@BUYCUR		CURSOR,
			@SNO		INT,
			@ISIN		VARCHAR(12),
			@QTY		INT,
			@NETAMT		NUMERIC(18,4),
			@ADJRATE	NUMERIC(18,4),
			@ADJQTY		INT

	SET @PFCUR = CURSOR FOR
	SELECT PARTY_CODE, AMOUNT = AMOUNT - SANC_LIM
	FROM #B_PFVALUE
	ORDER BY PARTY_CODE
	OPEN @PFCUR
	FETCH NEXT FROM @PFCUR INTO @PARTY_CODE, @AMOUNT
	WHILE @@FETCH_STATUS = 0
	BEGIN
		SET @BUYCUR = CURSOR FOR
		SELECT SNO, ISIN, QTY, NETAMT FROM TBL_PRODUCT_POSITION
		WHERE SAUDA_DATE = @SAUDA_DATE AND PARTY_CODE = @PARTY_CODE
		AND ADJUST_DATE > @SAUDA_DATE AND QTY > 0 and sett_no <> '2000000'
		ORDER BY NETAMT DESC
		OPEN @BUYCUR
		FETCH NEXT FROM @BUYCUR INTO @SNO, @ISIN, @QTY, @NETAMT
		WHILE @@FETCH_STATUS = 0
		BEGIN 
			IF @AMOUNT > 0 
			BEGIN
				IF @AMOUNT >= @NETAMT
				BEGIN
					UPDATE TBL_PRODUCT_POSITION SET QTY = 0, NETAMT = 0, MKTAMT = 0 
					WHERE SNO = @SNO

					SET @AMOUNT = @AMOUNT - @NETAMT
				END	
				ELSE
				BEGIN
					SET @ADJRATE = @NETAMT / @QTY
					SET @ADJQTY = CEILING(@AMOUNT / @ADJRATE)
					SET @ADJQTY = @QTY - @ADJQTY
					
					UPDATE TBL_PRODUCT_POSITION SET QTY = @ADJQTY, MKTAMT = @ADJQTY * (MKTAMT / @QTY),
					NETAMT = @ADJQTY * (NETAMT / @QTY)
					WHERE SNO = @SNO

					SET @AMOUNT = @AMOUNT - (@QTY - @ADJQTY) * (@NETAMT / @QTY)
				END	
			END
			FETCH NEXT FROM @BUYCUR INTO @SNO, @ISIN, @QTY, @NETAMT
		END
		CLOSE @BUYCUR
		DEALLOCATE @BUYCUR

		FETCH NEXT FROM @PFCUR INTO @PARTY_CODE, @AMOUNT
	END
	CLOSE @PFCUR
	DEALLOCATE @PFCUR

	DELETE FROM TBL_PRODUCT_POSITION
	WHERE SAUDA_DATE = @SAUDA_DATE AND QTY = 0
	 
	SELECT D.SETT_NO, D.SETT_TYPE, PARTY_CODE, SCRIP_CD, SERIES = CONVERT(VARCHAR(3),D.SERIES), 
	BSECODE = CONVERT(VARCHAR(6),''),ISIN = CONVERT(VARCHAR(12),''), QTY, SEC_PAYIN, START_DATE, 
	ORGQTY = QTY, HOLDFLAG = '1 BTST POSITION'
	INTO #B_BTSTMTF
	FROM MSAJAG.DBO.DELIVERYCLT D, MSAJAG.DBO.SETT_MST S
	WHERE S.SETT_NO = D.SETT_NO
	AND   S.SETT_TYPE = D.SETT_TYPE 
	AND   INOUT = 'O'
	AND	  D.SETT_TYPE IN ('N', 'W')
	AND   EXISTS (SELECT PARTY_CODE FROM TBLCLIENTMARGIN P
				  WHERE P.PARTY_CODE = D.PARTY_CODE
					AND @SAUDA_DATE BETWEEN FROM_DATE AND TO_DATE)
	AND S.START_DATE < @SAUDA_DATE
	AND	S.SEC_PAYIN > @SAUDA_DATE
	AND 1 =2 

	INSERT INTO #B_BTSTMTF
	SELECT D.SETT_NO, D.SETT_TYPE, PARTY_CODE, SCRIP_CD = CONVERT(VARCHAR(12),''), SERIES = CONVERT(VARCHAR(3),''), 
	BSECODE = SCRIP_CD, ISIN = CONVERT(VARCHAR(12),''), QTY, SEC_PAYIN, START_DATE,  	
	ORGQTY = QTY, HOLDFLAG = '1 BTST POSITION' 
	FROM ANAND.BSEDB_AB.DBO.DELIVERYCLT D, ANAND.BSEDB_AB.DBO.SETT_MST S
	WHERE S.SETT_NO = D.SETT_NO
	AND   S.SETT_TYPE = D.SETT_TYPE 
	AND	  INOUT = 'O'
	AND	  D.SETT_TYPE IN ('D', 'C')
	AND   EXISTS (SELECT PARTY_CODE FROM TBLCLIENTMARGIN P
				  WHERE P.PARTY_CODE = D.PARTY_CODE
					AND @SAUDA_DATE BETWEEN FROM_DATE AND TO_DATE)
	AND S.START_DATE < @SAUDA_DATE
	AND	S.SEC_PAYIN > @SAUDA_DATE
	AND 1 =2 
	/*
	UPDATE #B_BTSTMTF SET QTY = QTY - D.BUYQTY
	FROM (SELECT D.SETT_NO, D.SETT_TYPE, PARTY_CODE, SCRIP_CD, SERIES, BSECODE,
		  BUYQTY = SUM(QTY) FROM TBL_PRODUCT_POSITION D
		  WHERE SAUDA_DATE <= @SAUDA_DATE AND PAYIN_DATE > @SAUDA_DATE AND SELL_BUY = 1 
		  GROUP BY  D.SETT_NO, D.SETT_TYPE, PARTY_CODE, SCRIP_CD, SERIES, BSECODE ) D
	WHERE #B_BTSTMTF.SETT_NO = D.SETT_NO
	AND   #B_BTSTMTF.SETT_TYPE = D.SETT_TYPE
	AND   #B_BTSTMTF.PARTY_CODE = D.PARTY_CODE
	AND   ((#B_BTSTMTF.SCRIP_CD = D.SCRIP_CD
	AND   #B_BTSTMTF.SERIES = D.SERIES)
	OR   (#B_BTSTMTF.BSECODE = D.BSECODE))
	*/
	
	--IF @SAUDA_DATE = LEFT(GETDATE(),11)
	IF 1 = 1 
	BEGIN	
		IF @FLAG <> 2 
		BEGIN
			EXEC EDP_DP_BALANCE_UPDATE_NEW
		END

		INSERT INTO #B_BTSTMTF
		SELECT SETT_NO = '', SETT_TYPE = '', PARTY_CODE, SCRIP_CD = '', 
		SERIES, BSECODE = '', ISIN, QTY=FREEBAL, SEC_PAYIN='DEC 31 2049', START_DATE='DEC 31 2049',  	
		ORGQTY = FREEBAL, HOLDFLAG = 'POA' 
		FROM DELCDSLBALANCE
		WHERE EXISTS (SELECT PARTY_CODE FROM TBLCLIENTMARGIN 
					  WHERE DELCDSLBALANCE.PARTY_CODE = TBLCLIENTMARGIN.PARTY_CODE)

		DELETE FROM TBL_PRODUCT_HOLD_DATA    
		WHERE SAUDA_DATE = @SAUDA_DATE    
		AND HOLDFLAG IN ('POA','1 BTST POSITION') 

		INSERT INTO TBL_PRODUCT_HOLD_DATA
		SELECT @SAUDA_DATE, SETT_NO, SETT_TYPE, PARTY_CODE, SCRIP_CD, SERIES, BSECODE, ISIN, QTY, SEC_PAYIN, START_DATE, 
		ORGQTY, HOLDFLAG, CL_RATE = 0, HAIRCUT = 0, FOGFLAG = 0, MTFHAIRCUT = 0
		FROM #B_BTSTMTF
		WHERE QTY > 0   
	/*
		INSERT INTO TBL_PRODUCT_HOLD_DATA
		SELECT @SAUDA_DATE, SETT_NO, SETT_TYPE, PARTY_CODE, SCRIP_CD, SERIES, BSECODE, NEW_ISIN, 
		NEWQTY = (CASE WHEN CORP_TYPE = 'SPLIT' THEN NEWQTY - QTY ELSE NEWQTY END), 
		SEC_PAYIN = @SAUDA_DATE, START_DATE = @SAUDA_DATE, 
		ORGQTY = 0, HOLDFLAG = (CASE WHEN SEGMENT = 'FUTURES' THEN 'FOCOLL_P'
									WHEN SEGMENT = 'CAPITAL' AND ACCOUNTTYPE = 'MAR' THEN 'CMCOLL_P'
									WHEN SEGMENT = 'MTF' AND ACCOUNTTYPE = 'MAR' THEN 'MTFCOLL_P'
									ELSE 'BEN_P'
							   END), 
		CL_RATE = 0, HAIRCUT = 0, FOGFLAG = 0, MTFHAIRCUT = 0
		FROM MSAJAG.DBO.TBL_CORP_DATA_PROV P,
		(SELECT DPID, DPCLTNO, ACCOUNTTYPE, SEGMENT
		FROM BSEDB.DBO.DELIVERYDP DP
		WHERE DP.DESCRIPTION NOT LIKE '%POOL%'
		AND   DP.DESCRIPTION NOT LIKE '%PRINC%'
		AND DP.EXCHANGE = (CASE WHEN DP.EXCHANGE = 'MTF' AND DP.ACCOUNTTYPE = 'BEN' THEN '' ELSE DP.EXCHANGE END)
		UNION 
		SELECT DPID, DPCLTNO, ACCOUNTTYPE, SEGMENT
		FROM MSAJAG.DBO.DELIVERYDP DP
		WHERE DP.DESCRIPTION NOT LIKE '%POOL%'
		AND   DP.DESCRIPTION NOT LIKE '%PRINC%'
		AND DP.EXCHANGE = (CASE WHEN DP.EXCHANGE = 'MTF' AND DP.ACCOUNTTYPE = 'BEN' THEN '' ELSE DP.EXCHANGE END)) D
		WHERE RECORDDATE <= @SAUDA_DATE
		AND STATUSFLAG = 'P'
		AND P.BDPID = D.DPID
		AND P.BCLTDPID = D.DPCLTNO
		AND (CASE WHEN CORP_TYPE = 'SPLIT' THEN NEWQTY - QTY ELSE NEWQTY END) > 0
	
		INSERT INTO TBL_PRODUCT_HOLD_DATA
		SELECT @SAUDA_DATE, SETT_NO, SETT_TYPE, PARTY_CODE, SCRIP_CD, SERIES, BSECODE, NEW_ISIN, 
		NEWQTY = (CASE WHEN CORP_TYPE = 'SPLIT' THEN NEWQTY - QTY ELSE NEWQTY END), 
		SEC_PAYIN = @SAUDA_DATE, START_DATE = @SAUDA_DATE, 
		ORGQTY = 0, HOLDFLAG = 'POA_P', 
		CL_RATE = 0, HAIRCUT = 0, FOGFLAG = 0, MTFHAIRCUT = 0
		FROM MSAJAG.DBO.TBL_CORP_DATA_PROV P
		WHERE RECORDDATE <= @SAUDA_DATE
		AND STATUSFLAG = 'P'
		AND RECORDLOCATION = 'DP'*/
	END

	Select *  INTO #NSE_ISIN from  ANGELDEMAT.MSAJAG.DBO.MULTIISIN
	Select *  INTO #BSE_ISIN from  ANGELDEMAT.BSEDB.DBO.MULTIISIN 
        
        CREATE INDEX #NI ON #NSE_ISIN 
	(ISIN ,VALID)

        CREATE INDEX #BI ON #BSE_ISIN 
	(ISIN ,VALID)

/*
	UPDATE TBL_PRODUCT_HOLD_DATA SET SCRIP_CD = M.SCRIP_CD, SERIES = M.SERIES
	FROM ANGELDEMAT.MSAJAG.DBO.MULTIISIN M
	WHERE SAUDA_DATE = @SAUDA_DATE
	AND TBL_PRODUCT_HOLD_DATA.ISIN = M.ISIN
	AND VALID = 1 

	UPDATE TBL_PRODUCT_HOLD_DATA SET BSECODE = LEFT(M.SCRIP_CD,6)
	FROM ANGELDEMAT.BSEDB.DBO.MULTIISIN M
	WHERE SAUDA_DATE = @SAUDA_DATE
	AND TBL_PRODUCT_HOLD_DATA.ISIN = M.ISIN
	AND VALID = 1  */


	UPDATE TBL_PRODUCT_HOLD_DATA SET SCRIP_CD = M.SCRIP_CD, SERIES = M.SERIES
	FROM #NSE_ISIN M
	WHERE SAUDA_DATE = @SAUDA_DATE
	AND TBL_PRODUCT_HOLD_DATA.ISIN = M.ISIN
	AND VALID = 1 

	UPDATE TBL_PRODUCT_HOLD_DATA SET BSECODE = LEFT(M.SCRIP_CD,6)
	FROM #BSE_ISIN M
	WHERE SAUDA_DATE = @SAUDA_DATE
	AND TBL_PRODUCT_HOLD_DATA.ISIN = M.ISIN
	AND VALID = 1
	/*
	UPDATE TBL_PRODUCT_HOLD_DATA SET SCRIP_CD = M.SCRIP_CD, SERIES = M.SERIES
	FROM MSAJAG.DBO.MULTIISIN_NEW M
	WHERE SAUDA_DATE = @SAUDA_DATE
	AND @SAUDA_DATE BETWEEN EFF_FROM AND EFF_TO
	AND TBL_PRODUCT_HOLD_DATA.ISIN = M.ISIN

	UPDATE TBL_PRODUCT_HOLD_DATA SET BSECODE = LEFT(M.SCRIP_CD,6)
	FROM BSEDB.DBO.MULTIISIN_NEW M
	WHERE SAUDA_DATE = @SAUDA_DATE
	AND @SAUDA_DATE BETWEEN EFF_FROM AND EFF_TO
	AND TBL_PRODUCT_HOLD_DATA.ISIN = M.ISIN
	*/
	SELECT DISTINCT SCRIP_CD, SERIES, BSECODE, ISIN
	INTO #B_HOLDDATA FROM TBL_PRODUCT_HOLD_DATA
	WHERE SAUDA_DATE = @SAUDA_DATE

    SELECT SAUDA_DATE = CONVERT(DATETIME,@SAUDA_DATE), 
           PARTY_CODE, 
           SCRIP_CD, 
           SERIES, 
           BSECODE, 
           ISIN, 
           QTY = Sum(Qty), 
           MKTAMT = Sum(Mktamt), 
           NETAMT = Sum(Netamt), 
           CL_RATE =max(Cl_Rate), 
           CURR_CL_RATE = CONVERT(NUMERIC(18, 4), 0), 
           HAIRCUT = CONVERT(NUMERIC(18, 4), 0), 
           MARGIN_REQ = CONVERT(NUMERIC(18, 4), 0), 
           MTOM_LOSS = CONVERT(NUMERIC(18, 4), 0), 
           FOMARGIN = CONVERT(NUMERIC(18, 4), 0), 
           CMLEDBAL = CONVERT(NUMERIC(18, 4), 0), 
		   MTFLEDBAL = CONVERT(NUMERIC(18, 4), 0), 	
		   FOLEDBAL = CONVERT(NUMERIC(18, 4), 0), 
		   CMCASHEQCOLLATERAL = CONVERT(NUMERIC(18, 4), 0), 
		   CMCASHCOLLATERAL = CONVERT(NUMERIC(18, 4), 0), 
           CMNONCASHCOLLATERAL = CONVERT(NUMERIC(18, 4), 0), 
		   CMNONCASHCOLLATERAL_MTF = CONVERT(NUMERIC(18, 4), 0), 
		   CMDEBITHOLD = CONVERT(NUMERIC(18, 4), 0),
		   CMDEBITHOLD_MTF = CONVERT(NUMERIC(18, 4), 0),
		   CMOPENPOS = CONVERT(NUMERIC(18, 4), 0),
		   MTFCASHEQCOLLATERAL = CONVERT(NUMERIC(18, 4), 0),
		   MTFCASHCOLLATERAL = CONVERT(NUMERIC(18, 4), 0),
		   MTFNONCASHCOLLATERAL = CONVERT(NUMERIC(18, 4), 0),
		   FOCASHEQCOLLATERAL = CONVERT(NUMERIC(18, 4), 0), 
		   FOCASHCOLLATERAL = CONVERT(NUMERIC(18, 4), 0), 
		   FONONCASHCOLLATERAL = CONVERT(NUMERIC(18, 4), 0), 
		   FONONCASHCOLLATERAL_MTF = CONVERT(NUMERIC(18, 4), 0), 
           NET_AVL_FUND= CONVERT(NUMERIC(18, 4), 0),
		   POAHOLDING= CONVERT(NUMERIC(18, 4), 0),
		   POAHOLDING_MTF= CONVERT(NUMERIC(18, 4), 0),
		   SELLSHORT = CONVERT(NUMERIC(18, 4), 0)/*,
		   ORGSAUDA_DATE = SAUDA_DATE */
    INTO   #B_MTF_DATA 
    FROM   TBL_PRODUCT_POSITION 
    WHERE  SAUDA_DATE <= @SAUDA_DATE 
           AND ADJUST_DATE > @SAUDA_DATE 
           AND SELL_BUY = 1 AND QTY > 0 
	Group By 
		   PARTY_CODE, 
           SCRIP_CD, 
           SERIES, 
           BSECODE, 
           ISIN


	SELECT *  INTO #NSE_CLOSING from  MSAJAG.DBO.CLOSING WHERE SYSDATE >= @PREV_DATE  AND SYSDATE <= @PREV_DATE + ' 23:59' 
	SELECT *  INTO #BSE_CLOSING from  ANAND.BSEDB_AB.DBO.CLOSING  WHERE SYSDATE >= @PREV_DATE AND SYSDATE <= @PREV_DATE + ' 23:59' 
        
        CREATE INDEX #NCLOSING ON #NSE_CLOSING 
	(SCRIP_CD ,SERIES)

        CREATE INDEX #BCLSOING ON #BSE_CLOSING 
	(SCRIP_CD )
	
	
    UPDATE #B_MTF_DATA 
    SET    CURR_CL_RATE = C.CL_RATE 
    FROM   #NSE_CLOSING C
    WHERE  SYSDATE >= @PREV_DATE
           AND SYSDATE <= @PREV_DATE + ' 23:59' 
           AND #B_MTF_DATA.SCRIP_CD = C.SCRIP_CD 
           AND #B_MTF_DATA.SERIES IN ( 'EQ', 'BE', 'BZ' ) 
           AND C.SERIES IN ( 'EQ', 'BE', 'BZ' ) 
           AND #B_MTF_DATA.CURR_CL_RATE = 0 

    UPDATE #B_MTF_DATA 
    SET    CURR_CL_RATE = C.CL_RATE 
    FROM   #NSE_CLOSING C 
    WHERE  SYSDATE >= @PREV_DATE
           AND SYSDATE <= @PREV_DATE+ ' 23:59' 
           AND #B_MTF_DATA.SCRIP_CD = C.SCRIP_CD 
           AND #B_MTF_DATA.SERIES = C.SERIES 
           AND C.SERIES NOT IN ( 'EQ', 'BE', 'BZ' ) 
           AND #B_MTF_DATA.CURR_CL_RATE = 0 

    UPDATE #B_MTF_DATA 
    SET    CURR_CL_RATE = C.CL_RATE 
    FROM   #BSE_CLOSING C
    WHERE  SYSDATE >= @PREV_DATE
           AND SYSDATE <= @PREV_DATE+ ' 23:59' 
           AND #B_MTF_DATA.BSECODE = C.SCRIP_CD 
           AND #B_MTF_DATA.CURR_CL_RATE = 0 

	/* CLOSING PRICE OPTI*/
	
	UPDATE TBL_PRODUCT_HOLD_DATA 
    SET    CL_RATE = C.CL_RATE 
    FROM   #NSE_CLOSING C 
    WHERE  SAUDA_DATE = @SAUDA_DATE AND SYSDATE >= @PREV_DATE
           AND SYSDATE <= @PREV_DATE + ' 23:59' 
           AND TBL_PRODUCT_HOLD_DATA.SCRIP_CD = C.SCRIP_CD 
           AND TBL_PRODUCT_HOLD_DATA.SERIES IN ( 'EQ', 'BE', 'BZ' ) 
           AND C.SERIES IN ( 'EQ', 'BE', 'BZ' ) 
           AND TBL_PRODUCT_HOLD_DATA.CL_RATE = 0 

    UPDATE TBL_PRODUCT_HOLD_DATA 
    SET    CL_RATE = C.CL_RATE 
    FROM   #NSE_CLOSING C 
    WHERE  SAUDA_DATE = @SAUDA_DATE AND SYSDATE >= @PREV_DATE
           AND SYSDATE <= @PREV_DATE + ' 23:59' 
           AND TBL_PRODUCT_HOLD_DATA.SCRIP_CD = C.SCRIP_CD 
           AND TBL_PRODUCT_HOLD_DATA.SERIES = C.SERIES 
           AND C.SERIES NOT IN ( 'EQ', 'BE', 'BZ' ) 
           AND TBL_PRODUCT_HOLD_DATA.CL_RATE = 0 

    UPDATE TBL_PRODUCT_HOLD_DATA 
    SET    CL_RATE = C.CL_RATE 
    FROM   #BSE_CLOSING C 
    WHERE  SAUDA_DATE = @SAUDA_DATE AND SYSDATE >= @PREV_DATE
           AND SYSDATE <= @PREV_DATE + ' 23:59' 
           AND TBL_PRODUCT_HOLD_DATA.BSECODE = C.SCRIP_CD 
           AND TBL_PRODUCT_HOLD_DATA.CL_RATE = 0 

	SELECT *, FOFLAG = 0, ACTIVEFLAG = 1 INTO #B_TBLSCRIPMARGIN 
	FROM TBLSCRIPMARGIN
	WHERE @SAUDA_DATE BETWEEN FROM_DATE AND TO_DATE

	
	CREATE CLUSTERED INDEX IDXDT ON #B_TBLSCRIPMARGIN
	(
		ISIN
	)
	
	INSERT INTO #B_TBLSCRIPMARGIN 
	SELECT DISTINCT SCRIP_CD,FROM_DATE=@SAUDA_DATE,TO_DATE=@SAUDA_DATE + ' 23:59:59',ENTERED_BY='',ENTERED_DATE=@SAUDA_DATE,
					SERIES,BSECODE,ISIN,SCRIP_GROUP,FUND_PER, FOFLAG = 0, ACTIVEFLAG = 0 
	FROM TBLSCRIPMARGIN 
	WHERE ISIN NOT IN (SELECT ISIN FROM #B_TBLSCRIPMARGIN)

	UPDATE #B_TBLSCRIPMARGIN SET FOFLAG = 1
	FROM ANGELFO.NSEFO.DBO.FOSCRIP2 F
	WHERE F.SYMBOL = #B_TBLSCRIPMARGIN.SCRIP_CD
	AND   F.EXPIRYDATE >= @SAUDA_DATE
	AND   INST_TYPE LIKE 'FUT%'

	UPDATE TBL_PRODUCT_HOLD_DATA SET FOGFLAG = 1
	FROM #B_TBLSCRIPMARGIN
	WHERE SAUDA_DATE=@SAUDA_DATE
--		  SAUDA_DATE BETWEEN  @SAUDA_DATE  AND @SAUDA_DATE + ' 23:59'
	AND #B_TBLSCRIPMARGIN.ISIN = TBL_PRODUCT_HOLD_DATA.ISIN
	AND ACTIVEFLAG = 1
	
	SELECT V.* INTO #B_NSE_VAR FROM MSAJAG.DBO.VARDETAIL V, 
	MSAJAG.DBO.VARCONTROL  C
	WHERE C.RECDATE >= @PREV_DATE aND c.REcDATE <= @PREV_DATE + ' 23:59'
	AND C.DETAILKEY = V.DETAILKEY
	AND SERIES IN ( 'EQ', 'BE', 'BZ' ) 
	AND ISIN IN (SELECT ISIN FROM #B_MTF_DATA UNION SELECT ISIN FROM #B_HOLDDATA)

	--SELECT V.* INTO #B_BSE_VAR FROM BSEDB.DBO.VARDETAIL V
	--WHERE V.FDATE = @SAUDA_DATE
	--AND ISIN IN (SELECT ISIN FROM #B_MTF_DATA UNION SELECT ISIN FROM #B_HOLDDATA)

 /** For Optimization*/ 
	SELECT V.* INTO  #BSE_VAR FROM ANAND.BSEDB_AB.DBO.VARDETAIL V
	WHERE V.FDATE >= @PREV_DATE aND v.FDATE <= @PREV_DATE + ' 23:59'

    SELECT V.* INTO #B_BSE_VAR FROM  #BSE_VAR V
	WHERE  ISIN IN (SELECT ISIN FROM #B_MTF_DATA UNION SELECT ISIN FROM #B_HOLDDATA)

	CREATE CLUSTERED INDEX #NISIN ON #B_NSE_VAR
	(ISIN )
	CREATE CLUSTERED INDEX #BISIN ON #B_BSE_VAR
	(ISIN )

    UPDATE #B_MTF_DATA 
    SET    HAIRCUT = (CASE WHEN FOFLAG = 1 THEN M.APPVAR + @FNO * SECSPECVAR ELSE M.APPVAR + @NONFNO * SECSPECVAR END)
    FROM   #B_NSE_VAR M, #B_TBLSCRIPMARGIN T 
    WHERE  M.ISIN = #B_MTF_DATA.ISIN 
	AND    M.ISIN = T.ISIN
	AND    HAIRCUT = 0
	
	UPDATE TBL_PRODUCT_HOLD_DATA 
    SET    MTFHAIRCUT = (CASE WHEN FOFLAG = 1 
							  THEN M.MARGIN + @FNO * ELM 
							  ELSE M.MARGIN + @NONFNO * ELM 
					     END)
    FROM   #B_BSE_VAR M, #B_TBLSCRIPMARGIN T
    WHERE  SAUDA_DATE = @SAUDA_DATE
	AND    M.ISIN = TBL_PRODUCT_HOLD_DATA.ISIN 
	AND    M.ISIN = T.ISIN
	AND    MTFHAIRCUT = 0
	AND    TBL_PRODUCT_HOLD_DATA.BSECODE = M.Scrip_Cd
	
	UPDATE TBL_PRODUCT_HOLD_DATA 
    SET    MTFHAIRCUT = (CASE WHEN FOFLAG = 1 
							  THEN M.MARGIN + @FNO * ELM 
							  ELSE M.MARGIN + @NONFNO * ELM 
					     END)
    FROM   #B_BSE_VAR M, #B_TBLSCRIPMARGIN T
    WHERE  SAUDA_DATE = @SAUDA_DATE
	AND    M.ISIN = TBL_PRODUCT_HOLD_DATA.ISIN 
	AND    M.ISIN = T.ISIN
	AND    MTFHAIRCUT = 0
	
    UPDATE TBL_PRODUCT_HOLD_DATA 
    SET    HAIRCUT = M.APPVAR
    FROM   #B_NSE_VAR M--,  #B_TBLSCRIPMARGIN T 
    WHERE  SAUDA_DATE = @SAUDA_DATE
	AND    M.ISIN = TBL_PRODUCT_HOLD_DATA.ISIN  
	--AND    M.ISIN = T.ISIN AND ACTIVEFLAG = 1
	
    UPDATE TBL_PRODUCT_HOLD_DATA 
    SET    MTFHAIRCUT = (CASE WHEN FOFLAG = 1 THEN M.APPVAR + @FNO * SECSPECVAR ELSE M.APPVAR + @NONFNO * SECSPECVAR END)
    FROM   #B_NSE_VAR M, #B_TBLSCRIPMARGIN T 
    WHERE  SAUDA_DATE = @SAUDA_DATE
	AND    M.ISIN = TBL_PRODUCT_HOLD_DATA.ISIN 
	AND    M.ISIN = T.ISIN AND ACTIVEFLAG = 1

    UPDATE TBL_PRODUCT_HOLD_DATA 
    SET    HAIRCUT = M.MARGIN --(CASE WHEN FOFLAG = 1 THEN M.MARGIN + 3 * ELLM ELSE M.MARGIN + 5 * ELM END)
    FROM   #B_BSE_VAR M--,  #B_TBLSCRIPMARGIN T  
    WHERE  SAUDA_DATE = @SAUDA_DATE
	AND    M.ISIN = TBL_PRODUCT_HOLD_DATA.ISIN  
	AND    HAIRCUT = 0
	--AND    M.ISIN = T.ISIN AND ACTIVEFLAG = 1
		
    UPDATE TBL_PRODUCT_HOLD_DATA 
    SET    MTFHAIRCUT = (CASE WHEN FOFLAG = 1 
							  THEN M.MARGIN + @FNO * ELM 
							  ELSE M.MARGIN + @NONFNO * ELM 
					     END)
    FROM   #B_BSE_VAR M, #B_TBLSCRIPMARGIN T
    WHERE  SAUDA_DATE = @SAUDA_DATE
	AND    M.ISIN = TBL_PRODUCT_HOLD_DATA.ISIN 
	AND    M.ISIN = T.ISIN
	AND    MTFHAIRCUT = 0 AND ACTIVEFLAG = 1

	IF @MTFCOLLVAR = 1 
	BEGIN
		UPDATE TBL_PRODUCT_HOLD_DATA     
		SET    MTFHAIRCUT = HAIRCUT, HAIRCUT = MTFHAIRCUT  
		WHERE SAUDA_DATE = @SAUDA_DATE
		AND ISIN IN (SELECT ISIN FROM #B_TBLSCRIPMARGIN) 
	END

	UPDATE TBL_PRODUCT_HOLD_DATA     
	SET    MTFHAIRCUT = (CASE WHEN MTFHAIRCUT = 0 THEN 100 ELSE MTFHAIRCUT END), 
		   HAIRCUT = (CASE WHEN HAIRCUT = 0 THEN 100 ELSE HAIRCUT END)  
	WHERE SAUDA_DATE = @SAUDA_DATE
	AND (MTFHAIRCUT = 0 OR HAIRCUT = 0)

    UPDATE #B_MTF_DATA 
    SET    HAIRCUT = 100 
    WHERE  HAIRCUT = 0 OR HAIRCUT > 100

	UPDATE TBL_PRODUCT_HOLD_DATA     
	SET    MTFHAIRCUT = (CASE WHEN MTFHAIRCUT > 100 THEN 100 ELSE MTFHAIRCUT END), 
		   HAIRCUT = (CASE WHEN HAIRCUT > 100 THEN 100 ELSE HAIRCUT END)  
	WHERE SAUDA_DATE = @SAUDA_DATE
	AND (MTFHAIRCUT > 100 OR HAIRCUT > 100)
	
	UPDATE TBL_PRODUCT_HOLD_DATA              
	SET     HAIRCUT = 100        
	WHERE SAUDA_DATE = @SAUDA_DATE AND ISIN  IN (SELECT DISTINCT ISIN FROM MSAJAG.DBO.LIQUID_ISIN_FOVIOLATION L WHERE @SAUDA_DATE BETWEEN FROM_DATE AND TO_DATE)     

	UPDATE TBL_PRODUCT_HOLD_DATA 
    SET    HAIRCUT = 100   
	WHERE SAUDA_DATE = @SAUDA_DATE AND FOGFLAG = 0
	AND HOLDFLAG = 'MTFCOLL'

     UPDATE #B_MTF_DATA 
    SET    MARGIN_REQ = (Case When NETAMT > Curr_Cl_Rate*Qty Then Curr_Cl_Rate*Qty*HAIRCUT / 100 Else NETAMT*HAIRCUT / 100 End)

	
	 
	UPDATE #B_MTF_DATA 
	SET    MTOM_LOSS = ( MKTAMT / QTY - CURR_CL_RATE ) * QTY 
	WHERE HAIRCUT <> 100
	/*	
	UPDATE #B_MTF_DATA SET MTOM_LOSS = (CASE WHEN A.MTOM_LOSS < 0 THEN 0 ELSE #B_MTF_DATA.MTOM_LOSS END)
	FROM (SELECT PARTY_CODE, MTOM_LOSS = SUM(MTOM_LOSS)
	FROM #B_MTF_DATA 
	GROUP BY PARTY_CODE) A
	WHERE A.PARTY_CODE = #B_MTF_DATA.PARTY_CODE 
	*/
	/*
	UPDATE #B_MTF_DATA SET SELLSHORT = A.SELL_SHORT
	FROM (SELECT PARTY_CODE, SELL_SHORT = SUM(QTY*CL_RATE + QTY*CL_RATE*HAIRCUT/100)
		  FROM TBL_PRODUCT_HOLD_DATA WHERE HOLDFLAG = 'OPEN SELL POS'
		  GROUP BY PARTY_CODE
		  HAVING SUM(QTY) > 0) A
	WHERE #B_MTF_DATA.PARTY_CODE = A.PARTY_CODE
	*/
    SELECT L.CLTCODE, 
           VDTLEDBAL = SUM(CASE 
                             WHEN DRCR = 'C' THEN VAMT 
                             ELSE -VAMT 
                           END) 
    INTO   #B_LEDBAL 
    FROM   ACCOUNT.DBO.LEDGER L,  
		   (SELECT DISTINCT PARTY_CODE		
                             FROM   #B_MTF_DATA ) M	
    WHERE  L.VDT BETWEEN @SDTCUR AND @LDTCUR 
           AND L.VDT <= @SAUDA_DATE + ' 23:59:59' 
           AND L.CLTCODE = PARTY_CODE
		   /*AND VTYP <> (CASE WHEN VDT BETWEEN @SAUDA_DATE AND @SAUDA_DATE + ' 23:59' 
							 THEN '35' ELSE '' END)*/
    GROUP  BY L.CLTCODE 

	INSERT  INTO   #B_LEDBAL 
    SELECT L.CLTCODE, 
           VDTLEDBAL = SUM(CASE 
                             WHEN DRCR = 'D' THEN VAMT 
                             ELSE -VAMT 
                           END)
    FROM   ACCOUNT.DBO.LEDGER L,  
		   (SELECT DISTINCT PARTY_CODE		
                             FROM   #B_MTF_DATA ) M	
    WHERE  L.VDT <= @SAUDA_DATE
           AND L.EDT > @SAUDA_DATE + ' 23:59:59' 
           AND L.CLTCODE = PARTY_CODE
		   /*AND VTYP <> (CASE WHEN VDT BETWEEN @SAUDA_DATE AND @SAUDA_DATE + ' 23:59' 
							 THEN '35' ELSE '' END)*/
    GROUP  BY L.CLTCODE 
		
	if @flag = 0
	begin
		INSERT INTO   #B_LEDBAL
		SELECT CLTCODE, VDTLEDBAL = -MTFTOCASHJV
		FROM TBL_PRODUCT_LED_ADJUST
		WHERE SAUDA_DATE = @SAUDA_DATE
	end
		
	INSERT INTO   #B_LEDBAL 
    SELECT L.CLTCODE, 
           VDTLEDBAL = SUM(CASE 
                             WHEN DRCR = 'C' THEN VAMT 
                             ELSE -VAMT 
                           END)     
    FROM    ANAND.ACCOUNT_AB.DBO.LEDGER L,  
		   (SELECT DISTINCT PARTY_CODE		
                             FROM   #B_MTF_DATA ) M	
    WHERE  L.VDT BETWEEN @SDTCUR AND @LDTCUR 
           AND L.VDT <= @SAUDA_DATE + ' 23:59:59' 
           AND L.CLTCODE = PARTY_CODE
		   /*AND VTYP <> (CASE WHEN VDT BETWEEN @SAUDA_DATE AND @SAUDA_DATE + ' 23:59' 
							 THEN '35' ELSE '' END)*/
    GROUP  BY L.CLTCODE 

	INSERT INTO   #B_LEDBAL 
    SELECT L.CLTCODE, 
           VDTLEDBAL = SUM(CASE 
                             WHEN DRCR = 'D' THEN VAMT 
                             ELSE -VAMT 
                           END)     
    FROM   ANAND.ACCOUNT_AB.DBO.LEDGER L,  
		   (SELECT DISTINCT PARTY_CODE		
                             FROM   #B_MTF_DATA ) M	
    WHERE  L.VDT <= @SAUDA_DATE
           AND L.EDT > @SAUDA_DATE + ' 23:59:59' 
           AND L.CLTCODE = PARTY_CODE
		   /*AND VTYP <> (CASE WHEN VDT BETWEEN @SAUDA_DATE AND @SAUDA_DATE + ' 23:59' 
							 THEN '35' ELSE '' END)*/
    GROUP  BY L.CLTCODE 
	
    /*  
     
    INSERT INTO #B_LEDBAL 
    SELECT A.CLTCODE, 
           VDTLEDBAL = SUM(CASE 
                             WHEN DRCR = 'C' THEN VAMT 
                             ELSE -VAMT 
                           END) 
    FROM   ACCOUNTBSE.DBO.LEDGER L, 
           ACCOUNTBSE.DBO.PARAMETER P, 
           ACCOUNTBSE.DBO.ACMAST A 
    WHERE  L.VDT BETWEEN @SDTCUR AND @LDTCUR 
           AND L.VDT <= @SAUDA_DATE + ' 23:59:59' 
           AND L.CLTCODE = A.CLTCODE 
           AND A.ACCAT = 4 
           AND GETDATE() BETWEEN @SDTCUR AND @LDTCUR 
           AND A.CLTCODE IN (SELECT PARTY_CODE 
                             FROM   #B_MTF_DATA 
                             WHERE  PARTY_CODE = A.CLTCODE) 
    GROUP  BY A.CLTCODE       
     
    */ 

	SELECT PARTY_CODE, AMOUNT = SUM(AMOUNT) INTO #B_MTFREVLED FROM (
		SELECT PARTY_CODE, AMOUNT = SUM(NETAMT) FROM TBL_PRODUCT_POSITION
		--WHERE  orgSAUDA_DATE = @SAUDA_DATE --AND SELL_BUY = 1 
		WHERE   SAUDA_DATE = @SAUDA_DATE 
           AND ADJUST_DATE >= @SAUDA_DATE 
           AND SELL_BUY = 1 --AND SETT_NO = '2000000'
		GROUP BY PARTY_CODE
		UNION ALL
		SELECT PARTY_CODE, AMOUNT = -SUM(NETAMT) FROM TBL_PRODUCT_POSITION
		WHERE  SAUDA_DATE <= @SAUDA_DATE AND SELL_BUY = 1 
			   AND ADJUST_DATE = @SAUDA_DATE 
		GROUP BY PARTY_CODE ) A where 1 = 2 
	GROUP BY PARTY_CODE

	INSERT INTO #B_LEDBAL 
	SELECT * FROM #B_MTFREVLED

    UPDATE #B_MTF_DATA 
    SET    CMLEDBAL = VDTLEDBAL 
    FROM   (SELECT CLTCODE, 
                   VDTLEDBAL = SUM(VDTLEDBAL) 
            FROM   #B_LEDBAL 
            GROUP  BY CLTCODE) A 
    WHERE  CLTCODE = PARTY_CODE 

	TRUNCATE TABLE #B_LEDBAL

	UPDATE #B_MTFREVLED SET AMOUNT = -AMOUNT

	INSERT INTO #B_LEDBAL 
	SELECT * FROM #B_MTFREVLED
	
	INSERT INTO #B_LEDBAL 
    SELECT L.CLTCODE, 
           VDTLEDBAL = SUM(CASE 
                             WHEN DRCR = 'C' THEN VAMT 
                             ELSE -VAMT 
                           END)  
    FROM   LEDGER L,  
		   (SELECT DISTINCT PARTY_CODE		
                             FROM   #B_MTF_DATA ) M	
    WHERE  L.VDT BETWEEN @SDTCUR AND @LDTCUR 
           AND L.VDT <= @SAUDA_DATE + ' 23:59:59' 
           AND L.CLTCODE = PARTY_CODE
		   /*AND VTYP <> (CASE WHEN VDT BETWEEN @SAUDA_DATE AND @SAUDA_DATE + ' 23:59' 
							 THEN '35' ELSE '' END)*/
    GROUP  BY L.CLTCODE 
    /*
	INSERT INTO #B_LEDBAL 
    SELECT L.CLTCODE, 
           VDTLEDBAL = SUM(CASE 
                             WHEN DRCR = 'D' THEN VAMT 
                             ELSE -VAMT 
                           END)  
    FROM   LEDGER L,  
		   (SELECT DISTINCT PARTY_CODE		
                             FROM   #B_MTF_DATA ) M	
    WHERE  L.VDT <= @SAUDA_DATE
           AND EDT > @SAUDA_DATE + ' 23:59:59' 
           AND L.CLTCODE = PARTY_CODE
		   /*AND VTYP <> (CASE WHEN VDT BETWEEN @SAUDA_DATE AND @SAUDA_DATE + ' 23:59' 
							 THEN '35' ELSE '' END)*/
    GROUP  BY L.CLTCODE
	*/
	if @flag = 0
	begin
		INSERT INTO   #B_LEDBAL
		SELECT CLTCODE, VDTLEDBAL = MTFTOCASHJV
		FROM TBL_PRODUCT_LED_ADJUST
		WHERE SAUDA_DATE = @SAUDA_DATE

		INSERT INTO   #B_LEDBAL
		SELECT CLTCODE, VDTLEDBAL = -MTFTOFOJV
		FROM TBL_PRODUCT_LED_ADJUST
		WHERE SAUDA_DATE = @SAUDA_DATE
	end
		
    UPDATE #B_MTF_DATA 
    SET    MTFLEDBAL = VDTLEDBAL 
    FROM   (SELECT CLTCODE, 
                   VDTLEDBAL = SUM(VDTLEDBAL) 
            FROM   #B_LEDBAL 
            GROUP  BY CLTCODE) A 
    WHERE  CLTCODE = PARTY_CODE 

	TRUNCATE TABLE #B_LEDBAL
    INSERT INTO #B_LEDBAL 
    SELECT L.CLTCODE, 
           VDTLEDBAL = SUM(CASE 
                             WHEN DRCR = 'C' THEN VAMT 
                             ELSE -VAMT 
                           END) 
    FROM   ANGELFO.ACCOUNTFO.DBO.LEDGER L, 
		   (SELECT DISTINCT PARTY_CODE		
                             FROM   #B_MTF_DATA ) M 
    WHERE  L.VDT BETWEEN @SDTCUR AND @LDTCUR 
           AND L.VDT <= @SAUDA_DATE + ' 23:59:59' 
           AND L.CLTCODE = PARTY_CODE 
    GROUP  BY L.CLTCODE 

    INSERT INTO #B_LEDBAL 
    SELECT L.CLTCODE, 
           VDTLEDBAL = SUM(CASE 
                             WHEN DRCR = 'D' THEN VAMT 
                             ELSE -VAMT 
                           END) 
    FROM   ANGELFO.ACCOUNTFO.DBO.LEDGER L, 
		   (SELECT DISTINCT PARTY_CODE		
                             FROM   #B_MTF_DATA ) M 
    WHERE  L.VDT <= @SAUDA_DATE
           AND L.EDT > @SAUDA_DATE + ' 23:59:59' 
           AND L.CLTCODE = PARTY_CODE 
    GROUP  BY L.CLTCODE 

	INSERT INTO #B_LEDBAL 
    SELECT L.CLTCODE, 
           VDTLEDBAL = SUM(CASE 
                             WHEN DRCR = 'C' THEN VAMT 
                             ELSE -VAMT 
                           END) 
    FROM   ANGELFO.ACCOUNTCURFO.DBO.LEDGER L,  
		   (SELECT DISTINCT PARTY_CODE		
                             FROM   #B_MTF_DATA ) M 
    WHERE  L.VDT BETWEEN @SDTCUR AND @LDTCUR 
           AND L.VDT <= @SAUDA_DATE + ' 23:59:59' 
           AND L.CLTCODE = PARTY_CODE
    GROUP  BY L.CLTCODE 

	INSERT INTO #B_LEDBAL 
    SELECT L.CLTCODE, 
           VDTLEDBAL = SUM(CASE 
                             WHEN DRCR = 'D' THEN VAMT 
                             ELSE -VAMT 
                           END) 
    FROM  ANGELFO.ACCOUNTCURFO.DBO.LEDGER L,  
		   (SELECT DISTINCT PARTY_CODE		
                             FROM   #B_MTF_DATA ) M 
    WHERE  L.VDT <= @SAUDA_DATE 
           AND L.EDT > @SAUDA_DATE + ' 23:59:59' 
           AND L.CLTCODE = PARTY_CODE
    GROUP  BY L.CLTCODE 


	
	INSERT INTO #B_LEDBAL 
    SELECT L.CLTCODE, 
           VDTLEDBAL = SUM(CASE 
                             WHEN DRCR = 'C' THEN VAMT 
                             ELSE -VAMT 
                           END) 
    FROM   ANGELCOMMODITY.ACCOUNTNCDX.DBO.LEDGER L,  
		   (SELECT DISTINCT PARTY_CODE		
                             FROM   #B_MTF_DATA ) M 
    WHERE  L.VDT BETWEEN @SDTCUR AND @LDTCUR 
           AND L.VDT <= @SAUDA_DATE + ' 23:59:59' 
           AND L.CLTCODE = PARTY_CODE
    GROUP  BY L.CLTCODE 

	INSERT INTO #B_LEDBAL 
    SELECT L.CLTCODE, 
           VDTLEDBAL = SUM(CASE 
                             WHEN DRCR = 'D' THEN VAMT 
                             ELSE -VAMT 
                           END) 
    FROM  ANGELCOMMODITY.ACCOUNTNCDX.DBO.LEDGER L,  
		   (SELECT DISTINCT PARTY_CODE		
                             FROM   #B_MTF_DATA ) M 
    WHERE  L.VDT <= @SAUDA_DATE 
           AND L.EDT > @SAUDA_DATE + ' 23:59:59' 
           AND L.CLTCODE = PARTY_CODE
    GROUP  BY L.CLTCODE 

	
	INSERT INTO #B_LEDBAL 
    SELECT L.CLTCODE, 
           VDTLEDBAL = SUM(CASE 
                             WHEN DRCR = 'C' THEN VAMT 
                             ELSE -VAMT 
                           END) 
    FROM   ANGELCOMMODITY.ACCOUNTMCDX.DBO.LEDGER L,  
		   (SELECT DISTINCT PARTY_CODE		
                             FROM   #B_MTF_DATA ) M 
    WHERE  L.VDT BETWEEN @SDTCUR AND @LDTCUR 
           AND L.VDT <= @SAUDA_DATE + ' 23:59:59' 
           AND L.CLTCODE = PARTY_CODE
    GROUP  BY L.CLTCODE 

	INSERT INTO #B_LEDBAL 
    SELECT L.CLTCODE, 
           VDTLEDBAL = SUM(CASE 
                             WHEN DRCR = 'D' THEN VAMT 
                             ELSE -VAMT 
                           END) 
    FROM  ANGELCOMMODITY.ACCOUNTMCDX.DBO.LEDGER L,  
		   (SELECT DISTINCT PARTY_CODE		
                             FROM   #B_MTF_DATA ) M 
    WHERE  L.VDT <= @SAUDA_DATE 
           AND L.EDT > @SAUDA_DATE + ' 23:59:59' 
           AND L.CLTCODE = PARTY_CODE
    GROUP  BY L.CLTCODE 

	if @flag = 0
	begin
		INSERT INTO   #B_LEDBAL
		SELECT CLTCODE, VDTLEDBAL = MTFTOFOJV
		FROM TBL_PRODUCT_LED_ADJUST
		WHERE SAUDA_DATE = @SAUDA_DATE
	end
		
    UPDATE #B_MTF_DATA 
    SET    FOLEDBAL = VDTLEDBAL 
    FROM   (SELECT CLTCODE, 
                   VDTLEDBAL = SUM(VDTLEDBAL) 
            FROM   #B_LEDBAL 
            GROUP  BY CLTCODE) A 
    WHERE  CLTCODE = PARTY_CODE 

    UPDATE #B_MTF_DATA 
    SET    CMCASHCOLLATERAL = CASH - TOTALFD - TOTALBG
    FROM   MSAJAG.DBO.COLLATERAL C 
    WHERE  TRANS_DATE = (SELECT MAX(TRANS_DATE) 
                         FROM   MSAJAG.DBO.COLLATERAL C1 
                         WHERE  C1.TRANS_DATE <= @SAUDA_DATE + ' 23:59') 
           AND C.PARTY_CODE = #B_MTF_DATA.PARTY_CODE 
		   AND EXCHANGE NOT IN ('MCX', 'NCX')
		   AND SEGMENT = 'CAPITAL'  AND (CASH - TOTALFD - TOTALBG) > 0 

    UPDATE #B_MTF_DATA 
    SET    CMCASHEQCOLLATERAL = TOTALFD + TOTALBG
    FROM   MSAJAG.DBO.COLLATERAL C 
    WHERE  TRANS_DATE = (SELECT MAX(TRANS_DATE) 
                         FROM   MSAJAG.DBO.COLLATERAL C1 
                         WHERE  C1.TRANS_DATE <= @SAUDA_DATE + ' 23:59') 
           AND C.PARTY_CODE = #B_MTF_DATA.PARTY_CODE 
		   AND EXCHANGE NOT IN ('MCX', 'NCX')
		   AND SEGMENT = 'CAPITAL'   

	UPDATE #B_MTF_DATA 
    SET    CMNONCASHCOLLATERAL = CMNONCASHCOLLATERAL + NONCASH,
		   CMNONCASHCOLLATERAL_MTF = CMNONCASHCOLLATERAL_MTF + NONCASHMTF
	FROM   (SELECT PARTY_CODE, NONCASH = SUM(QTY*CL_RATE - QTY*CL_RATE*HAIRCUT/100),
			NONCASHMTF = SUM(CASE WHEN FOGFLAG = 1 THEN QTY*CL_RATE - QTY*CL_RATE*HAIRCUT/100 ELSE 0 END)
			FROM TBL_PRODUCT_HOLD_DATA
			WHERE SAUDA_DATE = @SAUDA_DATE AND HOLDFLAG IN ('CMCOLL','CMCOLL_P')
			GROUP BY PARTY_CODE ) A
	WHERE  #B_MTF_DATA.PARTY_CODE = A.PARTY_CODE

    UPDATE #B_MTF_DATA 
    SET    FOCASHCOLLATERAL = CASH - TOTALFD - TOTALBG
    FROM   MSAJAG.DBO.COLLATERAL C 
    WHERE  TRANS_DATE = (SELECT MAX(TRANS_DATE) 
                         FROM   MSAJAG.DBO.COLLATERAL C1 
                         WHERE  C1.TRANS_DATE <= @SAUDA_DATE + ' 23:59') 
           AND C.PARTY_CODE = #B_MTF_DATA.PARTY_CODE 
		   AND EXCHANGE NOT IN ('MCX', 'NCX')
		   AND SEGMENT = 'FUTURES' AND (CASH - TOTALFD - TOTALBG) > 0 

    UPDATE #B_MTF_DATA 
    SET    FOCASHEQCOLLATERAL = TOTALFD + TOTALBG
    FROM   MSAJAG.DBO.COLLATERAL C 
    WHERE  TRANS_DATE = (SELECT MAX(TRANS_DATE) 
                         FROM   MSAJAG.DBO.COLLATERAL C1 
                         WHERE  C1.TRANS_DATE <= @SAUDA_DATE + ' 23:59') 
           AND C.PARTY_CODE = #B_MTF_DATA.PARTY_CODE 
		   AND EXCHANGE NOT IN ('MCX', 'NCX')
		   AND SEGMENT = 'FUTURES' 


	UPDATE #B_MTF_DATA 
    SET    FONONCASHCOLLATERAL = FONONCASHCOLLATERAL + NONCASH,
		   FONONCASHCOLLATERAL_MTF = FONONCASHCOLLATERAL_MTF + NONCASHMTF
	FROM   (SELECT PARTY_CODE, NONCASH = SUM(QTY*CL_RATE - QTY*CL_RATE*HAIRCUT/100),
			NONCASHMTF = SUM(CASE WHEN FOGFLAG = 1 THEN QTY*CL_RATE - QTY*CL_RATE*HAIRCUT/100 ELSE 0 END)
			FROM TBL_PRODUCT_HOLD_DATA
			WHERE SAUDA_DATE = @SAUDA_DATE AND HOLDFLAG IN ('FOCOLL', 'FOCOLL_P')
			GROUP BY PARTY_CODE ) A
	WHERE  #B_MTF_DATA.PARTY_CODE = A.PARTY_CODE

    UPDATE #B_MTF_DATA 
    SET    MTFCASHCOLLATERAL = CASH - TOTALFD - TOTALBG  
    FROM   MSAJAG.DBO.COLLATERAL C 
    WHERE  TRANS_DATE = (SELECT MAX(TRANS_DATE) 
               FROM   MSAJAG.DBO.COLLATERAL C1 
                         WHERE  C1.TRANS_DATE <= @SAUDA_DATE + ' 23:59') 
           AND C.PARTY_CODE = #B_MTF_DATA.PARTY_CODE 
		   AND EXCHANGE = 'MTF'
		   AND SEGMENT = 'MTF' AND (CASH - TOTALFD - TOTALBG) > 0

    UPDATE #B_MTF_DATA 
    SET    MTFCASHEQCOLLATERAL = TOTALFD + TOTALBG  
    FROM   MSAJAG.DBO.COLLATERAL C 
    WHERE  TRANS_DATE = (SELECT MAX(TRANS_DATE) 
                         FROM   MSAJAG.DBO.COLLATERAL C1 
                         WHERE  C1.TRANS_DATE <= @SAUDA_DATE + ' 23:59') 
           AND C.PARTY_CODE = #B_MTF_DATA.PARTY_CODE 
		   AND EXCHANGE = 'MTF'
		   AND SEGMENT = 'MTF'  

	UPDATE #B_MTF_DATA 
    SET    MTFNONCASHCOLLATERAL = MTFNONCASHCOLLATERAL + NONCASH
	FROM   (SELECT PARTY_CODE, NONCASH = SUM(QTY*CL_RATE - QTY*CL_RATE*HAIRCUT/100)
			FROM TBL_PRODUCT_HOLD_DATA
			WHERE SAUDA_DATE = @SAUDA_DATE AND HOLDFLAG IN ('MTFCOLL','MTFCOLL_P')
			GROUP BY PARTY_CODE ) A
	WHERE  #B_MTF_DATA.PARTY_CODE = A.PARTY_CODE

	UPDATE #B_MTF_DATA 
    SET    POAHOLDING = NONCASH,
		   POAHOLDING_MTF = NONCASHMTF
	FROM   (SELECT PARTY_CODE, NONCASH = SUM(QTY*CL_RATE - QTY*CL_RATE*HAIRCUT/100),
			NONCASHMTF = SUM(CASE WHEN FOGFLAG = 1 THEN QTY*CL_RATE - QTY*CL_RATE*HAIRCUT/100 ELSE 0 END)
			FROM TBL_PRODUCT_HOLD_DATA
			WHERE SAUDA_DATE = @SAUDA_DATE
			AND HOLDFLAG IN ('POA', 'POA_P')
			GROUP BY PARTY_CODE ) A
	WHERE  #B_MTF_DATA.PARTY_CODE = A.PARTY_CODE

	UPDATE #B_MTF_DATA 
    SET    CMDEBITHOLD = NONCASH,
		   CMDEBITHOLD_MTF = 0--NONCASHMTF
	FROM   (SELECT PARTY_CODE, NONCASH = SUM(QTY*CL_RATE - QTY*CL_RATE*HAIRCUT/100),
			NONCASHMTF = SUM(CASE WHEN FOGFLAG = 1 THEN QTY*CL_RATE - QTY*CL_RATE*HAIRCUT/100 ELSE 0 END)
			FROM TBL_PRODUCT_HOLD_DATA
			WHERE SAUDA_DATE = @SAUDA_DATE
			AND HOLDFLAG IN ('BEN', 'BEN_P', 'EPN')
			GROUP BY PARTY_CODE ) A
	WHERE  #B_MTF_DATA.PARTY_CODE = A.PARTY_CODE

	
	UPDATE #B_MTF_DATA 
    SET    CMDEBITHOLD = CMDEBITHOLD + NONCASH 
	FROM   (SELECT PARTY_CODE, NONCASH = SUM(QTY*CL_RATE - QTY*CL_RATE*HAIRCUT/100) 
			FROM TBL_PRODUCT_HOLD_DATA
			WHERE SAUDA_DATE = @SAUDA_DATE
			AND HOLDFLAG IN ('BEN_C')
			GROUP BY PARTY_CODE ) A
	WHERE  #B_MTF_DATA.PARTY_CODE = A.PARTY_CODE

	/*
	UPDATE #B_MTF_DATA 
    SET    CMOPENPOS = NONCASH
	FROM   (SELECT PARTY_CODE, NONCASH = SUM(QTY*CL_RATE - QTY*CL_RATE*HAIRCUT/100)
			FROM TBL_PRODUCT_HOLD_DATA
			WHERE SAUDA_DATE = @SAUDA_DATE AND HOLDFLAG = '1 BTST POSITION'
			GROUP BY PARTY_CODE ) A
	WHERE  #B_MTF_DATA.PARTY_CODE = A.PARTY_CODE
	*/
    UPDATE #B_MTF_DATA 
    SET    FOMARGIN = TOTALMARGIN--SPREADMARGIN + MTOM 
    FROM   ANGELFO.NSEFO.DBO.FOMARGINNEW C 
    WHERE  MDATE = (SELECT MAX(MDATE) 
                    FROM    ANGELFO.NSEFO.DBO.FOMARGINNEW C1 
                    WHERE  C1.MDATE <= @SAUDA_DATE + ' 23:59') 
           AND C.PARTY_CODE = #B_MTF_DATA.PARTY_CODE
		    
	UPDATE #B_MTF_DATA 
    SET    FOMARGIN = FOMARGIN + (CASE WHEN TOTAL_MARGIN > PEAKMARGIN THEN TOTAL_MARGIN ELSE PEAKMARGIN END)
    FROM   MSAJAG.DBO.TBL_CMMARGIN C 
    WHERE  MARGINDATE = (SELECT MAX(MARGINDATE) 
                    FROM    MSAJAG.DBO.TBL_CMMARGIN C1 
                    WHERE  C1.MARGINDATE <= @SAUDA_DATE + ' 23:59') 
           AND C.PARTY_CODE = #B_MTF_DATA.PARTY_CODE 

    UPDATE #B_MTF_DATA 
    SET    FOMARGIN = FOMARGIN + TOTALMARGIN--FOMARGIN + SPREADMARGIN + MTOM 
    FROM   ANGELFO.NSECURFO.DBO.FOMARGINNEW C 
    WHERE  MDATE = (SELECT MAX(MDATE) 
                    FROM    ANGELFO.NSECURFO.DBO.FOMARGINNEW C1 
                    WHERE  C1.MDATE <= @SAUDA_DATE + ' 23:59') 
           AND C.PARTY_CODE = #B_MTF_DATA.PARTY_CODE 

		   
    UPDATE #B_MTF_DATA 
    SET    FOMARGIN = FOMARGIN + TOTALMARGIN--FOMARGIN + SPREADMARGIN + MTOM 
    FROM   ANGELCOMMODITY.MCDX.DBO.FOMARGINNEW C 
    WHERE  MDATE = (SELECT MAX(MDATE) 
                    FROM    ANGELCOMMODITY.MCDX.DBO.FOMARGINNEW C1 
                    WHERE  C1.MDATE <= @SAUDA_DATE + ' 23:59') 
           AND C.PARTY_CODE = #B_MTF_DATA.PARTY_CODE 
		   
    UPDATE #B_MTF_DATA 
    SET    FOMARGIN = FOMARGIN + TOTALMARGIN--FOMARGIN + SPREADMARGIN + MTOM 
    FROM   ANGELCOMMODITY.NCDX.DBO.FOMARGINNEW C 
    WHERE  MDATE = (SELECT MAX(MDATE) 
                    FROM    ANGELCOMMODITY.NCDX.DBO.FOMARGINNEW C1 
                    WHERE  C1.MDATE <= @SAUDA_DATE + ' 23:59') 
           AND C.PARTY_CODE = #B_MTF_DATA.PARTY_CODE 

	DELETE FROM TBL_MTF_DATA
	WHERE SAUDA_DATE = @SAUDA_DATE

	INSERT INTO TBL_MTF_DATA
	SELECT SAUDA_DATE,PARTY_CODE,SCRIP_CD,SERIES,BSECODE,ISIN,QTY,
	MKTAMT,NETAMT,CL_RATE,CURR_CL_RATE,HAIRCUT,MARGIN_REQ,MTOM_LOSS,FOMARGIN,
	CMLEDBAL,MTFLEDBAL,FOLEDBAL,CMCASHEQCOLLATERAL,CMCASHCOLLATERAL,
	CMNONCASHCOLLATERAL,CMNONCASHCOLLATERAL_MTF,CMDEBITHOLD,CMDEBITHOLD_MTF,
	CMOPENPOS,MTFCASHEQCOLLATERAL,MTFCASHCOLLATERAL,MTFNONCASHCOLLATERAL,
	FOCASHEQCOLLATERAL,FOCASHCOLLATERAL,FONONCASHCOLLATERAL,FONONCASHCOLLATERAL_MTF,
	NET_AVL_FUND,POAHOLDING,POAHOLDING_MTF,SELLSHORT,
	CASHDEBITADJ = 0,
	CASHNONCASHADJ = 0,
	FONONCASHADJ = 0,
	CASHLEDADJ = 0,
	FOLEDBALADJ = 0,
	POAADJ = 0 
	FROM #B_MTF_DATA

	/*	INSERT INTO TBL_MTF_DATA_LOG
	SELECT SAUDA_DATE,PARTY_CODE,SCRIP_CD,SERIES,BSECODE,ISIN,QTY,
	MKTAMT,NETAMT,CL_RATE,CURR_CL_RATE,HAIRCUT,MARGIN_REQ,MTOM_LOSS,FOMARGIN,
	CMLEDBAL,MTFLEDBAL,FOLEDBAL,CMCASHEQCOLLATERAL,CMCASHCOLLATERAL,
	CMNONCASHCOLLATERAL,CMNONCASHCOLLATERAL_MTF,CMDEBITHOLD,CMDEBITHOLD_MTF,
	CMOPENPOS,MTFCASHEQCOLLATERAL,MTFCASHCOLLATERAL,MTFNONCASHCOLLATERAL,
	FOCASHEQCOLLATERAL,FOCASHCOLLATERAL,FONONCASHCOLLATERAL,FONONCASHCOLLATERAL_MTF,
	NET_AVL_FUND,POAHOLDING,POAHOLDING_MTF,SELLSHORT,
	CASHDEBITADJ = 0,
	CASHNONCASHADJ = 0,
	FONONCASHADJ = 0,
	CASHLEDADJ = 0,
	FOLEDBALADJ = 0,
	POAADJ = 0
	FROM #B_MTF_DATA*/--ADDED SURESH

/*
    SELECT PARTY_CODE,
           NETFUNDREQ = ( CASE 
                            WHEN SUM(-MARGIN_REQ + MKTAMT) - FOMARGIN + LEDBAL + 
                                 COLLATERAL 
                                 - SUM( 
                                 MTOM_LOSS) > 0 THEN SUM(CASE 
                          WHEN @SAUDA_DATE = SAUDA_DATE THEN MKTAMT - NETAMT 
                 ELSE 0 
                          END) 
                            ELSE SUM(-MARGIN_REQ + MKTAMT) - FOMARGIN + LEDBAL + 
                                 COLLATERAL 
                                 - SUM( 
                                 MTOM_LOSS) 
                          END ) 
    INTO   #B_FUND_REQ 
    FROM   #B_MTF_DATA 
    GROUP  BY PARTY_CODE, 
              FOMARGIN, 
              LEDBAL, 
              COLLATERAL 

    UPDATE #B_MTF_DATA 
    SET    NET_AVL_FUND = NETFUNDREQ 
    FROM   #B_FUND_REQ 
    WHERE  #B_FUND_REQ.PARTY_CODE = #B_MTF_DATA.PARTY_CODE 

    DELETE FROM TBL_PRODUCT_DETAIL 
    WHERE  RUNDATE = @SAUDA_DATE 

    INSERT INTO TBL_PRODUCT_DETAIL 
    SELECT RUNDATE=CONVERT(DATETIME, @SAUDA_DATE), 
           *, 
           PROCESS_ON = GETDATE(), 
           PROCESS_BY = ''
    FROM   #B_MTF_DATA 

    DROP TABLE #B_MTF_DATA 

    DROP TABLE #B_LEDBAL 

    DROP TABLE #B_FUND_REQ 

    DROP TABLE #B_NRML_DATE   
*/

GO
