-- Object: PROCEDURE dbo.PROC_MTFBILLPOST_BKUP_25Nov2022
-- Server: 10.253.33.91 | DB: MTFTRADE
--------------------------------------------------



-- EXEC PROC_MTFBILLPOST 'MAR 13 2019'

CREATE PROC [dbo].[PROC_MTFBILLPOST_BKUP_25Nov2022]
(
	@SAUDA_DATE VARCHAR(11)
)
AS

DECLARE 
		@GLCODE		VARCHAR(10),
		@VNO		VARCHAR(12),
		@NSECASHVNO		VARCHAR(12),
		@BSECASHVNO		VARCHAR(12),
		@SDTCUR		VARCHAR(11),
		@LDTCUR		VARCHAR(11),
		@PAYIN_DATE	DATETIME,
		@FROMDATE	VARCHAR(11),
		@CLEARINGCODE	VARCHAR(10),
		@SETT_NO		VARCHAR(7),
		@SETT_TYPE		VARCHAR(2)

SET @VNO = ''
SET @CLEARINGCODE = ''
SET @SETT_NO = ''


SET @VNO = ''

SELECT @SDTCUR = SDTCUR, @LDTCUR = LDTCUR
FROM PARAMETER WHERE @SAUDA_DATE BETWEEN @SDTCUR AND LDTCUR

SELECT @PAYIN_DATE = @SAUDA_DATE-- MAX(SEC_PAYIN) FROM MSAJAG.DBO.SETT_MST WHERE START_DATE <= @SAUDA_DATE AND SETT_TYPE = 'N'

-- EXEC PROC_MTFBILLPOST 'JUL 11 2017'
 
SELECT @CLEARINGCODE = ISNULL(CLEARINGCODE,'') FROM MSAJAG.DBO.TBL_INTEROP_SETTING
WHERE  @SAUDA_DATE BETWEEN FROM_DATE AND TO_DATE
 
SELECT @SETT_NO = SETT_NO, @SETT_TYPE = SETT_TYPE,@PAYIN_DATE=Sec_Payin FROM MSAJAG.DBO.SETT_MST 
WHERE START_DATE = @SAUDA_DATE AND SETT_TYPE = 'N'
 

SELECT @GLCODE = ACCODE FROM VALANACCOUNT
WHERE ACNAME =  'MTF VALAN'

SELECT @VNO = ISNULL(MAX(VNO),'') FROM MTF_BILL_DETAIL
WHERE BILLDATE = @SAUDA_DATE 

IF @VNO = ''
BEGIN
	CREATE TABLE #VNO
	(
		VNO	VARCHAR(12)
	)
	INSERT INTO #VNO 
	EXEC ACC_GENVNO @SAUDA_DATE, 35, '01', @SDTCUR, @LDTCUR, 1

	SELECT @VNO = VNO FROM #VNO
	
	INSERT INTO MTF_BILL_DETAIL
	SELECT @SAUDA_DATE, @VNO
END
ELSE
BEGIN
	DELETE FROM LEDGER WHERE VNO = @VNO AND VTYP = '35' AND BOOKTYPE = '01'  
END

SELECT @NSECASHVNO = ISNULL(MAX(VNO),'') FROM ACCOUNT.DBO.MTF_BILL_DETAIL
WHERE BILLDATE = @SAUDA_DATE 

IF @NSECASHVNO <> ''
BEGIN
	DELETE FROM ACCOUNT.DBO.LEDGER WHERE VNO = @NSECASHVNO AND VTYP = '35' AND BOOKTYPE = '01'  
END

IF @CLEARINGCODE = '' OR @CLEARINGCODE = 'NSCCL'
BEGIN  
	IF @NSECASHVNO = ''
	BEGIN
		CREATE TABLE #NSECASHVNO
		(
			VNO	VARCHAR(12)
		)
		INSERT INTO #NSECASHVNO 
		EXEC ACCOUNT.DBO.ACC_GENVNO_NEW @SAUDA_DATE, 35, '01', @SDTCUR, @LDTCUR, 1

		SELECT @NSECASHVNO = VNO FROM #NSECASHVNO
	
		INSERT INTO ACCOUNT.DBO.MTF_BILL_DETAIL
		SELECT @SAUDA_DATE, @NSECASHVNO
	END  
END
 
SELECT *, MT_LIQUIDATE = 0
INTO #MT_LIQUID 
FROM TBL_PRODUCT_POSITION P
WHERE SAUDA_DATE <= @SAUDA_DATE
AND SELL_BUY = 1 
AND ADJUST_DATE = @SAUDA_DATE 

CREATE CLUSTERED INDEX IDX_SNO ON #MT_LIQUID
(	
	SNO
)
CREATE NONCLUSTERED INDEX IDX_PARTY ON #MT_LIQUID
(	
	PARTY_CODE,
	ISIN,
	SAUDA_DATE
)


DECLARE @PARTY_CODE VARCHAR(10),
		@ISIN		VARCHAR(12),
		@QTY		INT,
		@MTCUR		CURSOR,
		@POSQTY		INT,
		@POSCUR		CURSOR,
		@POSDATE	DATETIME,
		@SNO		NUMERIC(18,0)

SET @MTCUR = CURSOR FOR
SELECT PARTY_CODE, ISIN, QTY = SUM(QTY) FROM TBL_PRODUCT_POSITION P1
WHERE P1.SAUDA_DATE = @SAUDA_DATE	
AND P1.SELL_BUY = 2 AND P1.SETT_NO = '2000000'
GROUP BY PARTY_CODE, ISIN
ORDER BY PARTY_CODE, ISIN
OPEN @MTCUR
FETCH NEXT FROM @MTCUR INTO @PARTY_CODE, @ISIN, @QTY
WHILE @@FETCH_STATUS = 0
BEGIN
	SET @POSCUR = CURSOR FOR
	SELECT SNO, QTY, SAUDA_DATE FROM #MT_LIQUID
	WHERE PARTY_CODE = @PARTY_CODE
	AND ISIN = @ISIN
	ORDER BY SAUDA_DATE 
	OPEN @POSCUR
	FETCH NEXT FROM @POSCUR INTO @SNO, @POSQTY, @POSDATE
	WHILE @@FETCH_STATUS = 0
	BEGIN
		IF @POSQTY >= @QTY
		BEGIN
			UPDATE #MT_LIQUID SET MT_LIQUIDATE = @QTY 
			WHERE SNO = @SNO 
			SET @QTY = 0
		END
		ELSE
		BEGIN
			UPDATE #MT_LIQUID SET MT_LIQUIDATE = @POSQTY 
			WHERE SNO = @SNO 
			SET @QTY = @QTY - @POSQTY
		END
		IF @QTY <= 0 
		BEGIN
			BREAK
		END
		FETCH NEXT FROM @POSCUR INTO @SNO, @POSQTY, @POSDATE
	END
	CLOSE @POSCUR
	DEALLOCATE @POSCUR
	FETCH NEXT FROM @MTCUR INTO @PARTY_CODE, @ISIN, @QTY
END
CLOSE @MTCUR
DEALLOCATE @MTCUR

SELECT PARTY_CODE, AMOUNT = (CASE WHEN SUM(QTY) <> SUM(MT_LIQUIDATE) THEN SUM(NETAMT)-SUM((NETAMT/QTY)*MT_LIQUIDATE) ELSE 0 END), 
NARRATION = CONVERT(VARCHAR(100),'Reversed against sale of MTF shares dated ' + @SAUDA_DATE),DRCR = 'C',
PAYIN_DATE=(CASE WHEN PAYIN_DATE > @PAYIN_DATE THEN PAYIN_DATE ELSE @PAYIN_DATE END),VNO = @VNO
INTO #BILL
FROM #MT_LIQUID P
WHERE SAUDA_DATE <= @SAUDA_DATE
AND SELL_BUY = 1 
AND ADJUST_DATE = @SAUDA_DATE  
GROUP BY PARTY_CODE,(CASE WHEN PAYIN_DATE > @PAYIN_DATE THEN PAYIN_DATE ELSE @PAYIN_DATE END)
HAVING (CASE WHEN SUM(QTY) <> SUM(MT_LIQUIDATE) THEN SUM(NETAMT)-SUM((NETAMT/QTY)*MT_LIQUIDATE) ELSE 0 END) > 0 
 
INSERT INTO #BILL
SELECT PARTY_CODE, AMOUNT = (CASE WHEN SUM(QTY) <> SUM(MT_LIQUIDATE) THEN SUM((NETAMT/QTY)*MT_LIQUIDATE) ELSE SUM(NETAMT) END) , 
NARRATION = CONVERT(VARCHAR(100),'Reversed against sale of MTF shares dated ' + @SAUDA_DATE),DRCR = 'C',
PAYIN_DATE=(CASE WHEN PAYIN_DATE > @SAUDA_DATE THEN PAYIN_DATE ELSE @SAUDA_DATE END),VNO = @VNO
FROM #MT_LIQUID P
WHERE SAUDA_DATE <= @SAUDA_DATE
AND SELL_BUY = 1 
AND ADJUST_DATE = @SAUDA_DATE
AND MT_LIQUIDATE > 0 
GROUP BY PARTY_CODE,(CASE WHEN PAYIN_DATE > @SAUDA_DATE THEN PAYIN_DATE ELSE @SAUDA_DATE END)

IF @CLEARINGCODE = ''
BEGIN
	INSERT INTO #BILL
	SELECT PARTY_CODE, AMOUNT = SUM(NETAMT), 
	NARRATION = CONVERT(VARCHAR(100),'Transferred to MTF for ' + SETT_NO + '-' + LTRIM(RTRIM(SETT_TYPE)) + ' BILL DATE ' + LEFT(SAUDA_DATE,11)), DRCR = 'D',
	PAYIN_DATE,VNO = @VNO
	FROM TBL_PRODUCT_POSITION
	WHERE SAUDA_DATE = @SAUDA_DATE
	AND SELL_BUY = 1 --AND SETT_NO <> '2000000'
	GROUP BY SETT_NO, SETT_TYPE, PARTY_CODE, SAUDA_DATE,PAYIN_DATE
END
ELSE
BEGIN
	INSERT INTO #BILL
	SELECT PARTY_CODE, AMOUNT = SUM(NETAMT), 
	NARRATION = CONVERT(VARCHAR(100),'Transferred to MTF for ' + @SETT_NO + '-' + LTRIM(RTRIM(@SETT_TYPE)) + ' BILL DATE ' + LEFT(SAUDA_DATE,11)), DRCR = 'D',
	PAYIN_DATE,VNO = @VNO
	FROM TBL_PRODUCT_POSITION
	WHERE SAUDA_DATE = @SAUDA_DATE
	AND SELL_BUY = 1 --AND SETT_NO <> '2000000'
	GROUP BY PARTY_CODE, SAUDA_DATE,PAYIN_DATE
END

ALTER TABLE #BILL
ADD SNO INT IDENTITY(1,1)

UPDATE #BILL SET AMOUNT = CONVERT(NUMERIC(18,2),AMOUNT)

INSERT INTO #BILL
SELECT @GLCODE, AMOUNT = SUM(AMOUNT), NARRATION, DRCR = (CASE WHEN DRCR = 'C' THEN 'D' ELSE 'C' END), PAYIN_DATE, VNO
FROM #BILL
GROUP BY NARRATION, PAYIN_DATE, VNO, DRCR 

ALTER TABLE #BILL
ADD ACNAME VARCHAR(200) 

UPDATE #BILL SET ACNAME = A.LONGNAME 
FROM ACMAST A
WHERE #BILL.PARTY_CODE = A.CLTCODE

INSERT INTO LEDGER
SELECT '35', VNO, PAYIN_DATE, SNO, ACNAME, DRCR, AMOUNT, @SAUDA_DATE, '', '', 0, 0, GETDATE(), PARTY_CODE, '01', 'MTF PROCESS', GETDATE(), 'MTF PROCESS', 0, NARRATION
FROM #BILL

IF @CLEARINGCODE = '' OR @CLEARINGCODE = 'NSCCL'
BEGIN 
	SELECT PARTY_CODE, AMOUNT = (CASE WHEN SUM(QTY) <> SUM(MT_LIQUIDATE) THEN SUM(NETAMT)-SUM((NETAMT/QTY)*MT_LIQUIDATE) ELSE 0 END), 
	NARRATION = CONVERT(VARCHAR(100),'Reversed against sale of MTF shares dated ' + @SAUDA_DATE),DRCR = 'C',
	PAYIN_DATE=(CASE WHEN PAYIN_DATE > @PAYIN_DATE THEN PAYIN_DATE ELSE @PAYIN_DATE END),VNO = @NSECASHVNO
	INTO #NSECASHBILL
	FROM #MT_LIQUID P
	WHERE SAUDA_DATE <= @SAUDA_DATE
	AND SELL_BUY = 1 
	AND ADJUST_DATE = @SAUDA_DATE 
	AND 1 = (CASE WHEN @CLEARINGCODE = 'NSCCL' AND TRANSTYPE = 'TRNSE' THEN 1 
							       WHEN @CLEARINGCODE = 'NSCCL' AND TRANSTYPE = 'TRBSE' THEN 1
								   WHEN @CLEARINGCODE = '' AND TRANSTYPE = 'TRNSE' THEN 1
								   ELSE 2 END)
	GROUP BY PARTY_CODE,(CASE WHEN PAYIN_DATE > @PAYIN_DATE THEN PAYIN_DATE ELSE @PAYIN_DATE END)
	HAVING (CASE WHEN SUM(QTY) <> SUM(MT_LIQUIDATE) THEN SUM(NETAMT)-SUM((NETAMT/QTY)*MT_LIQUIDATE) ELSE 0 END) > 0 

	INSERT INTO #NSECASHBILL
	SELECT PARTY_CODE, AMOUNT = (CASE WHEN SUM(QTY) <> SUM(MT_LIQUIDATE) THEN SUM((NETAMT/QTY)*MT_LIQUIDATE) ELSE SUM(NETAMT) END), 
	NARRATION = CONVERT(VARCHAR(100),'Reversed against sale of MTF shares dated ' + @SAUDA_DATE),DRCR = 'C',
	PAYIN_DATE=(CASE WHEN PAYIN_DATE > @SAUDA_DATE THEN PAYIN_DATE ELSE @SAUDA_DATE END),VNO = @NSECASHVNO
	FROM #MT_LIQUID P
	WHERE SAUDA_DATE <= @SAUDA_DATE
	AND SELL_BUY = 1 
	AND ADJUST_DATE = @SAUDA_DATE
	AND 1 = (CASE WHEN @CLEARINGCODE = 'NSCCL' AND TRANSTYPE = 'TRNSE' THEN 1 
							       WHEN @CLEARINGCODE = 'NSCCL' AND TRANSTYPE = 'TRBSE' THEN 1
								   WHEN @CLEARINGCODE = '' AND TRANSTYPE = 'TRNSE' THEN 1
								   ELSE 2 END)
	AND MT_LIQUIDATE > 0 
	GROUP BY PARTY_CODE,(CASE WHEN PAYIN_DATE > @SAUDA_DATE THEN PAYIN_DATE ELSE @SAUDA_DATE END)

	IF @CLEARINGCODE = ''
	BEGIN
		INSERT INTO #NSECASHBILL
		SELECT PARTY_CODE, AMOUNT = SUM(NETAMT), 
		NARRATION = CONVERT(VARCHAR(100),'Transferred to MTF for ' + SETT_NO + '-' + LTRIM(RTRIM(SETT_TYPE)) + ' BILL DATE ' + LEFT(SAUDA_DATE,11)), DRCR = 'D',
		PAYIN_DATE,VNO = @NSECASHVNO
		FROM TBL_PRODUCT_POSITION
		WHERE SAUDA_DATE = @SAUDA_DATE
		AND SELL_BUY = 1 AND TRANSTYPE = 'TRNSE' --AND SETT_NO <> '2000000'
		GROUP BY SETT_NO, SETT_TYPE, PARTY_CODE, SAUDA_DATE,PAYIN_DATE
	END
	ELSE
	BEGIN
		INSERT INTO #NSECASHBILL
		SELECT PARTY_CODE, AMOUNT = SUM(NETAMT), 
		NARRATION = CONVERT(VARCHAR(100),'Transferred to MTF for ' + @SETT_NO + '-' + LTRIM(RTRIM(@SETT_TYPE)) + ' BILL DATE ' + LEFT(SAUDA_DATE,11)), DRCR = 'D',
		PAYIN_DATE,VNO = @NSECASHVNO
		FROM TBL_PRODUCT_POSITION
		WHERE SAUDA_DATE = @SAUDA_DATE
		AND SELL_BUY = 1 --AND TRANSTYPE = 'TRNSE' --AND SETT_NO <> '2000000'
		GROUP BY PARTY_CODE, SAUDA_DATE,PAYIN_DATE
	END

	UPDATE #NSECASHBILL SET DRCR = (CASE WHEN DRCR = 'C' THEN 'D' ELSE 'C' END)

	ALTER TABLE #NSECASHBILL
	ADD SNO INT IDENTITY(1,1)

	UPDATE #NSECASHBILL SET AMOUNT = CONVERT(NUMERIC(18,2),AMOUNT)

	INSERT INTO #NSECASHBILL
	SELECT @GLCODE, AMOUNT = SUM(AMOUNT), NARRATION, DRCR = (CASE WHEN DRCR = 'C' THEN 'D' ELSE 'C' END), 
	PAYIN_DATE, VNO
	FROM #NSECASHBILL
	GROUP BY NARRATION, PAYIN_DATE, VNO, DRCR 

	ALTER TABLE #NSECASHBILL
	ADD ACNAME VARCHAR(200) 

	UPDATE #NSECASHBILL SET ACNAME = A.LONGNAME 
	FROM ACMAST A
	WHERE #NSECASHBILL.PARTY_CODE = A.CLTCODE

	INSERT INTO ACCOUNT.DBO.LEDGER
	SELECT '35', VNO, PAYIN_DATE, SNO, ACNAME, DRCR, AMOUNT, @SAUDA_DATE, '', '', 0, 0, GETDATE(), PARTY_CODE, '01', 'MTF PROCESS', GETDATE(), 'MTF PROCESS', 0, NARRATION
	FROM #NSECASHBILL
END
 
SET @FROMDATE = LEFT(@SAUDA_DATE,3) + '  1 ' + CONVERT(VARCHAR,RIGHT(@SAUDA_DATE,4))

--EXEC CBO_INT_COMPUTATION @DATEFROM = @FROMDATE, @DATETO = @SAUDA_DATE  , @UNAME = '', @FLAG = 1

GO
