-- Object: PROCEDURE dbo.MFUND_RPT_FUNDING_OPENPOS_MORETHAN_90DAYS
-- Server: 10.253.33.91 | DB: MTFTRADE
--------------------------------------------------


CREATE PROC [dbo].[MFUND_RPT_FUNDING_OPENPOS_MORETHAN_90DAYS](                  
  @STATUSID VARCHAR(50),                    
  @STATUSNAME VARCHAR(50),                    
  @FROMDATE VARCHAR(11),                    
  @TODATE  VARCHAR(11),                    
  @FROMPARTY VARCHAR(10),                    
  @TOPARTY VARCHAR(10),                    
  @FROMSCRIP VARCHAR(50)='',                    
  @TOSCRIP VARCHAR(50)='ZZZZZZZ',                    
  @OPT VARCHAR(20)=''                  
)            
AS     
-- EXEC MFUND_RPT_FUNDING_OPENPOS 'BROKER', 'BROKER', 'aug 14 2017', 'aug 14 2017', 'V67413', 'V67413', '0', 'ZZZ', ''

SELECT @TOPARTY = (CASE WHEN @TOPARTY = '' AND @FROMPARTY <> '' THEN @FROMPARTY 
						WHEN @TOPARTY = '' AND @FROMPARTY = '' THEN 'ZZZZZZZZZZ'
						ELSE @TOPARTY END) 

SELECT @TOSCRIP = (CASE WHEN @TOSCRIP = '' AND @FROMSCRIP <> '' THEN @FROMSCRIP 
						WHEN @TOSCRIP = '' AND @FROMSCRIP = '' THEN 'ZZZZZZZZZZ'
						ELSE @TOSCRIP END) 
 												 
SELECT ORGBUYDATE = CONVERT(VARCHAR,SAUDA_DATE,103), 
PROCESSDATE=CONVERT(VARCHAR,CONVERT(DATETIME,@FROMDATE),103),
EXCHANGE = (CASE WHEN SETT_TYPE IN ('D', 'C') THEN 'BSE' ELSE 'NSE' END),
SETT_NO, SETT_TYPE, 
t.PARTY_CODE, LONG_NAME, SCRIP_NAME = CONVERT(VARCHAR(100),''),
SCRIP_CD, SERIES, BSECODE, ISIN, QTY, MARKETVALUE=MKTAMT, NETVALUE = NETAMT, 
CL_RATE,
HAIRCUT = CONVERT(NUMERIC(18,4),0),
MTOMLOSS = CONVERT(NUMERIC(18,4),0),
MARG_REQ = CONVERT(NUMERIC(18,4),0),
TOTAL_REQ = CONVERT(NUMERIC(18,4),0),
OPENDAY = DATEDIFF(D,SAUDA_DATE,CONVERT(DATETIME,@FROMDATE))
INTO #DATA
FROM TBL_PRODUCT_POSITION T, MSAJAG.DBO.CLIENT_details C1
WHERE SAUDA_DATE <= @FROMDATE 
AND ADJUST_DATE > @FROMDATE
AND SELL_BUY = 1 
AND C1.CL_CODE = t.PARTY_CODE
AND t.PARTY_CODE BETWEEN @FROMPARTY AND @TOPARTY
 

UPDATE #DATA SET CL_RATE = CURR_CL_RATE,
HAIRCUT = C.HAIRCUT
FROM TBL_MTF_DATA C
WHERE C.SAUDA_DATE = @FROMDATE
AND #DATA.ISIN = C.ISIN
AND #DATA.PARTY_CODE = C.PARTY_CODE

UPDATE #DATA SET MTOMLOSS = (CL_RATE * QTY - MARKETVALUE ) 
WHERE HAIRCUT <> 100

UPDATE #DATA SET MARG_REQ = MARKETVALUE * HAIRCUT / 100

UPDATE #DATA SET TOTAL_REQ = MARG_REQ - MTOMLOSS

UPDATE #DATA SET SCRIP_NAME = S1.LONG_NAME FROM MSAJAG.DBO.SCRIP1 S1, MSAJAG.DBO.SCRIP2 S2            
WHERE S1.CO_CODE = S2.CO_CODE AND S1.SERIES = S2.SERIES            
AND S2.SCRIP_CD = #DATA.SCRIP_CD AND S2.SERIES = #DATA.SERIES            
            
UPDATE #DATA SET SCRIP_NAME = S1.LONG_NAME FROM ANGELDEMAT.BSEDB.DBO.SCRIP1 S1, ANGELDEMAT.BSEDB.DBO.SCRIP2 S2            
WHERE S1.CO_CODE = S2.CO_CODE AND S1.SERIES = S2.SERIES            
AND S2.BSECODE = #DATA.BSECODE           
AND SCRIP_NAME = ''     

SELECT * FROM #DATA WHERE OPENDAY >=90
--WHERE SCRIP_NAME  >= @FROMSCRIP AND SCRIP_NAME  <= @TOSCRIP            
ORDER BY OPENDAY, PARTY_CODE, LONG_NAME, SCRIP_NAME

GO
