-- Object: PROCEDURE dbo.PROC_MTF_CORPACT_QTY
-- Server: 10.253.33.91 | DB: MTFTRADE
--------------------------------------------------



CREATE PROC [dbo].[PROC_MTF_CORPACT_QTY]
(
		@SAUDA_DATE VARCHAR(11),
		@OLDISIN	VARCHAR(12),
		@NEWISIN	VARCHAR(12),
		@FROMRATIO		NUMERIC(18,4),
		@TORATIO		NUMERIC(18,4),
		@EFFDATE	VARCHAR(11),
		@CORPTYPE	VARCHAR(20)
) AS

DECLARE @NEWSYMBOL	VARCHAR(12),
		@NEWSERIES	VARCHAR(3),
		@BSECODE	VARCHAR(12)

SELECT @NEWSYMBOL = '', @NEWSERIES = '', @BSECODE = ''

SELECT @NEWSYMBOL = SCRIP_CD, @NEWSERIES = SERIES FROM MSAJAG.DBO.MULTIISIN WHERE ISIN = @NEWISIN AND VALID = 1 
SELECT @BSECODE = SCRIP_CD FROM [ANGELBSECM].BSEDB_AB.DBO.MULTIISIN WHERE ISIN = @NEWISIN AND VALID = 1 

-- EXEC PROC_MTF_CORPACT_QTY @SAUDA_DATE= 'DEC 13 2019', @OLDISIN = 'INE860A01027', @NEWISIN = 'INE860A01027', @FROMRATIO = 2, @TORATIO = 1, @EFFDATE = 'DEC 17 2019', @CORPTYPE = 'BONUS'
	
INSERT INTO TBL_PRODUCT_POS_ADJUST
SELECT SAUDA_DATE=@EFFDATE,SETT_NO='2000000',SETT_TYPE=(CASE WHEN TRANSTYPE = 'TRNSE' THEN 'N' ELSE 'D' END),
PARTY_CODE,SCRIP_CD,
SERIES,BSECODE,ISIN,QTY=SUM(QTY),TRANSTYPE,ADDED_BY='',ADDED_ON=GETDATE()
FROM TBL_PRODUCT_POSITION
WHERE SAUDA_DATE < @SAUDA_DATE
AND SELL_BUY = 1 
AND ADJUST_DATE > @EFFDATE
AND ISIN = @OLDISIN
GROUP BY PARTY_CODE,SCRIP_CD,SERIES,BSECODE,ISIN,TRANSTYPE
HAVING FLOOR(SUM(QTY)*@TORATIO/@FROMRATIO) > 0  

---SAUDA_dATE PROCESS DATE APR  6 2018

IF @CORPTYPE = 'BONUS'
BEGIN
	INSERT INTO TBL_PRODUCT_POS_ADJUST_BUY
	SELECT SAUDA_DATE=@EFFDATE,SETT_NO='2000000',SETT_TYPE=(CASE WHEN TRANSTYPE = 'TRNSE' THEN 'N' ELSE 'D' END),
	PARTY_CODE,SCRIP_CD,
	SERIES,BSECODE,ISIN=@NEWISIN,QTY=SUM(QTY)+FLOOR(SUM(QTY)*@TORATIO/@FROMRATIO),TRANSTYPE,ADDED_BY=@CORPTYPE,ADDED_ON=GETDATE(),
	MKTAMT = SUM(MKTAMT), NETAMT = SUM(NETAMT)
	FROM TBL_PRODUCT_POSITION
	WHERE SAUDA_DATE < @SAUDA_DATE
	AND SELL_BUY = 1 
	AND ADJUST_DATE > @EFFDATE
	AND ISIN = @OLDISIN
	GROUP BY PARTY_CODE,SCRIP_CD,SERIES,BSECODE,ISIN,TRANSTYPE
	HAVING FLOOR(SUM(QTY)*@TORATIO/@FROMRATIO) > 0 
END

IF @CORPTYPE <> 'BONUS'
BEGIN
	UPDATE TBL_PRODUCT_POSITION SET SCRIP_CD=@NEWSYMBOL,SERIES=@NEWSERIES,BSECODE=@BSECODE,ISIN=@NEWISIN
	WHERE SAUDA_DATE >= @SAUDA_DATE AND SELL_BUY = 1 
	AND ADJUST_DATE > @EFFDATE
	AND ISIN = @OLDISIN

	INSERT INTO TBL_PRODUCT_POS_ADJUST_BUY
	SELECT SAUDA_DATE=@EFFDATE,SETT_NO='2000000',SETT_TYPE=(CASE WHEN TRANSTYPE = 'TRNSE' THEN 'N' ELSE 'D' END),
	PARTY_CODE,SCRIP_CD=@NEWSYMBOL,SERIES=@NEWSERIES,BSECODE=@BSECODE,ISIN=@NEWISIN,QTY=FLOOR(SUM(QTY)*@TORATIO/@FROMRATIO),TRANSTYPE,ADDED_BY=@CORPTYPE,ADDED_ON=GETDATE(),
	MKTAMT = SUM(MKTAMT), NETAMT = SUM(NETAMT)
	FROM TBL_PRODUCT_POSITION
	WHERE SAUDA_DATE < @SAUDA_DATE
	AND SELL_BUY = 1 
	AND ADJUST_DATE > @EFFDATE
	AND ISIN = @OLDISIN
	GROUP BY PARTY_CODE,ISIN,TRANSTYPE
	HAVING FLOOR(SUM(QTY)*@TORATIO/@FROMRATIO) > 0 
END

GO
