-- Object: PROCEDURE dbo.DELIVERY_INTEROP_MTF
-- Server: 10.253.33.91 | DB: MTFTRADE
--------------------------------------------------


CREATE PROC [dbo].[DELIVERY_INTEROP_MTF]
(
	@SAUDA_DATE	DATETIME
) 
AS

-- EXEC DELIVERY_INTEROP_MTF 'OCT 27 2022'
DECLARE @OTHER_SETT_TYPE VARCHAR(2),
		@OTHER_SETT_NO	VARCHAR(7),
		@Start_Date VARCHAR(11),
		@CLEARINGCODE	VARCHAR(10),
		@GROSS_NET_FLAG	VARCHAR(1)
		 
SELECT @CLEARINGCODE = ISNULL(CLEARINGCODE,'') FROM MSAJAG.DBO.TBL_INTEROP_SETTING
WHERE  @SAUDA_DATE BETWEEN FROM_DATE AND TO_DATE

IF @CLEARINGCODE = 'NSCCL'
BEGIN
	SELECT @OTHER_SETT_NO = SETT_NO FROM MSAJAG.DBO.SETT_MST 
	WHERE START_DATE = @SAUDA_DATE	AND SETT_tYPE = 'N'
END

IF @CLEARINGCODE = 'ICCL'
BEGIN
	SELECT @OTHER_SETT_NO = SETT_NO FROM AngelBSECM.BSEDB_AB.DBO.SETT_MST 
	WHERE START_DATE = @SAUDA_DATE	AND SETT_tYPE = 'D'
END

SELECT SETT_NO, SETT_TYPE, PARTY_CODE, SCRIP_CD, SERIES, 
INOUT = (CASE WHEN SUM(CASE WHEN SELL_BUY = 1 THEN QTY ELSE -QTY END) > 0 THEN 'O' ELSE 'I' END),
QTY=ABS(SUM(CASE WHEN SELL_BUY = 1 THEN QTY ELSE -QTY END)), BRANCH_CD= 'HO', PARTIPANTCODE=MEMBERCODE,I_ISIN=ISIN
INTO #NSEDEL
FROM MTFTRADE.DBO.TBL_PRODUCT_POSITION, MSAJAG.DBO.OWNER
WHERE SETT_NO <> '2000000' AND TRANSTYPE = 'TRNSE'
AND SAUDA_DATE = @SAUDA_DATE AND 1 = 2 
GROUP BY SETT_NO, SETT_TYPE, PARTY_CODE, SCRIP_CD, SERIES, MEMBERCODE,ISIN

SELECT SETT_NO, SETT_TYPE, PARTY_CODE, SCRIP_CD=BSECODE, SERIES='BSE', 
INOUT = (CASE WHEN SUM(CASE WHEN SELL_BUY = 1 THEN QTY ELSE -QTY END) > 0 THEN 'O' ELSE 'I' END),
QTY=ABS(SUM(CASE WHEN SELL_BUY = 1 THEN QTY ELSE -QTY END)), BRANCH_CD= 'HO', PARTIPANTCODE=MEMBERCODE,I_ISIN=ISIN
INTO #BSEDEL
FROM MTFTRADE.DBO.TBL_PRODUCT_POSITION, AngelBSECM.BSEDB_AB.DBO.OWNER
WHERE SETT_NO <> '2000000' AND TRANSTYPE = 'TRBSE' 
AND SAUDA_DATE = @SAUDA_DATE AND 1 = 2 
GROUP BY SETT_NO, SETT_TYPE, PARTY_CODE, BSECODE, MEMBERCODE,ISIN 

SELECT * INTO #MTFPOS FROM MTFTRADE.DBO.TBL_PRODUCT_POSITION 
WHERE SAUDA_DATE = @SAUDA_DATE AND SETT_NO <> '2000000'

IF @CLEARINGCODE = ''
BEGIN
	INSERT INTO #NSEDEL
	SELECT SETT_NO, SETT_TYPE, PARTY_CODE, SCRIP_CD, SERIES, 
	INOUT = (CASE WHEN SUM(CASE WHEN SELL_BUY = 1 THEN QTY ELSE -QTY END) > 0 THEN 'O' ELSE 'I' END),
	QTY=ABS(SUM(CASE WHEN SELL_BUY = 1 THEN QTY ELSE -QTY END)), BRANCH_CD= 'HO', PARTIPANTCODE=MEMBERCODE,I_ISIN=ISIN
	FROM #MTFPOS, MSAJAG.DBO.OWNER
	WHERE SETT_NO <> '2000000' AND TRANSTYPE = 'TRNSE'
	AND SAUDA_DATE = @SAUDA_DATE
	GROUP BY SETT_NO, SETT_TYPE, PARTY_CODE, SCRIP_CD, SERIES, MEMBERCODE,ISIN

	INSERT INTO #BSEDEL
	SELECT SETT_NO, SETT_TYPE, PARTY_CODE, SCRIP_CD=BSECODE, SERIES='BSE', 
	INOUT = (CASE WHEN SUM(CASE WHEN SELL_BUY = 1 THEN QTY ELSE -QTY END) > 0 THEN 'O' ELSE 'I' END),
	QTY=ABS(SUM(CASE WHEN SELL_BUY = 1 THEN QTY ELSE -QTY END)), BRANCH_CD= 'HO', PARTIPANTCODE=MEMBERCODE,I_ISIN=ISIN	
	FROM #MTFPOS, AngelBSECM.BSEDB_AB.DBO.OWNER
	WHERE SETT_NO <> '2000000' AND TRANSTYPE = 'TRBSE'
	GROUP BY SETT_NO, SETT_TYPE, PARTY_CODE, BSECODE, MEMBERCODE,ISIN 
END 

IF @CLEARINGCODE = 'NSCCL'
BEGIN
	UPDATE #MTFPOS SET SETT_NO=S1.SETT_NO, Sett_Type = NSE_SETT_TYPE
	FROM MSAJAG.DBO.TBL_INTEROP_SETT_TYPE S, MSAJAG.DBO.SETT_MST S1
	WHERE #MTFPOS.SETT_TYPE = BSE_SETT_TYPE 
	AND @SAUDA_DATE BETWEEN FROM_DATE AND TO_DATE 
	AND S1.SETT_TYPE = NSE_SETT_TYPE
	AND START_DATE = @SAUDA_DATE 
	
	UPDATE #MTFPOS SET SCRIP_CD = NSE_SCRIP_CD, SERIES = NSE_SERIES FROM MSAJAG.DBO.TBL_EXCHG_SCRIP_MAP M
	WHERE M.ISIN = #MTFPOS.ISIN AND @Start_Date BETWEEN FROM_DATE AND TO_DATE 
	AND #MTFPOS.BSECODE = M.BSECODE AND TRANSTYPE = 'TRBSE'
			
	UPDATE #MTFPOS SET SERIES=LEFT(SERIES,2)

	INSERT INTO #NSEDEL 
	SELECT SETT_NO, SETT_TYPE, PARTY_CODE, SCRIP_CD, SERIES, 
	INOUT = (CASE WHEN SUM(CASE WHEN SELL_BUY = 1 THEN QTY ELSE -QTY END) > 0 THEN 'O' ELSE 'I' END),
	QTY=ABS(SUM(CASE WHEN SELL_BUY = 1 THEN QTY ELSE -QTY END)), BRANCH_CD= 'HO', PARTIPANTCODE=MEMBERCODE,I_ISIN=ISIN	
	FROM #MTFPOS, MSAJAG.DBO.OWNER
	WHERE SETT_NO <> '2000000'  
	AND SAUDA_DATE = @SAUDA_DATE
	GROUP BY SETT_NO, SETT_TYPE, PARTY_CODE, SCRIP_CD, SERIES, MEMBERCODE,ISIN 
	
END

IF @CLEARINGCODE = 'ICCL'
BEGIN	 
	UPDATE #MTFPOS SET SETT_NO=S1.SETT_NO, Sett_Type = BSE_SETT_TYPE
	FROM MSAJAG.DBO.TBL_INTEROP_SETT_TYPE S, AngelBSECM.BSEDB_AB.DBO.SETT_MST S1
	WHERE #MTFPOS.SETT_TYPE = NSE_SETT_TYPE 
	AND @SAUDA_DATE BETWEEN FROM_DATE AND TO_DATE 
	AND S1.SETT_TYPE = BSE_SETT_TYPE
	AND START_DATE = @SAUDA_DATE 

	UPDATE #MTFPOS SET BSECODE = M.BSECODE FROM MSAJAG.DBO.TBL_EXCHG_SCRIP_MAP M
	WHERE M.ISIN = #MTFPOS.ISIN AND @Start_Date BETWEEN FROM_DATE AND TO_DATE 
	AND #MTFPOS.SCRIP_CD = M.NSE_SCRIP_CD
	AND #MTFPOS.SERIES = M.NSE_SERIES 
	AND TRANSTYPE = 'TRBSE'

	INSERT INTO #BSEDEL 
	SELECT SETT_NO, SETT_TYPE, PARTY_CODE, SCRIP_CD=BSECODE, SERIES='BSE', 
	INOUT = (CASE WHEN SUM(CASE WHEN SELL_BUY = 1 THEN QTY ELSE -QTY END) > 0 THEN 'O' ELSE 'I' END),
	QTY=ABS(SUM(CASE WHEN SELL_BUY = 1 THEN QTY ELSE -QTY END)), BRANCH_CD= 'HO', PARTIPANTCODE=MEMBERCODE,I_ISIN=ISIN 
	FROM #MTFPOS, BSEDB.DBO.OWNER
	WHERE SETT_NO <> '2000000'  
	GROUP BY SETT_NO, SETT_TYPE, PARTY_CODE, BSECODE, MEMBERCODE,ISIN 
END 

DELETE FROM NSE_DELIVERYCLT_MTF
WHERE SETT_NO IN (SELECT SETT_NO FROM #NSEDEL
					WHERE NSE_DELIVERYCLT_MTF.SETT_NO = #NSEDEL.Sett_NO
					AND NSE_DELIVERYCLT_MTF.SETT_TYPE = #NSEDEL.Sett_Type)

INSERT INTO NSE_DELIVERYCLT_MTF
(Sett_No,Sett_Type,Scrip_Cd,Series,Party_Code,Qty,Inout,Branch_Cd,Partipantcode,I_ISIN)
SELECT Sett_No,Sett_Type,Scrip_Cd,Series,Party_Code,Qty,Inout,Branch_Cd,Partipantcode,I_ISIN FROM #NSEDEL

DELETE FROM BSE_DELIVERYCLT_MTF
WHERE SETT_NO IN (SELECT SETT_NO FROM #BSEDEL
					WHERE BSE_DELIVERYCLT_MTF.SETT_NO = #BSEDEL.Sett_NO
					AND BSE_DELIVERYCLT_MTF.SETT_TYPE = #BSEDEL.Sett_Type)

INSERT INTO BSE_DELIVERYCLT_MTF (Sett_No,Sett_Type,Scrip_Cd,Series,Party_Code,Qty,Inout,Branch_Cd,Partipantcode,I_ISIN)
SELECT Sett_No,Sett_Type,Scrip_Cd,Series,Party_Code,Qty,Inout,Branch_Cd,Partipantcode,I_ISIN FROM #BSEDEL 

IF CONVERT(DATETIME, @SAUDA_DATE) >= 'AUG 28 2020'
BEGIN
	EXEC ANGELDEMAT.MSAJAG.dbo.PROC_MTF_PLD_DATA @SAUDA_DATE 
END

GO
