-- Object: PROCEDURE dbo.ADDEDIT_PARTY_MAKER_CHECKER
-- Server: 10.253.33.91 | DB: MTFTRADE
--------------------------------------------------

CREATE PROCEDURE [dbo].[ADDEDIT_PARTY_MAKER_CHECKER]    
(    
 @PARTYCODE VARCHAR(10),    
 @USERID VARCHAR(20),    
 @SRNO INT,    
 @STATUS VARCHAR(1),    
 @APPREMARK VARCHAR(100)    
)    
AS    
    
DECLARE @SANCTIONED_AMT  NUMERIC(18,4),    
  @MARGIN_INTEREST NUMERIC(18,4),   
  @FROM_DATE   DATETIME,    
  @TO_DATE   DATETIME,    
  @RECTYPE   VARCHAR(10),    
  @REMARKS   VARCHAR(100),    
  @RECCLOSE   VARCHAR(1),    
  @NEWSANCTIONED_AMT NUMERIC(18,4),
  @MIN_COVER     NUMERIC(18,4)
    
SELECT @SANCTIONED_AMT=SANCTIONED_AMT, @MARGIN_INTEREST=MARGIN_INTEREST ,   
       @FROM_DATE=FROM_DATE,@RECTYPE=RECTYPE,@REMARKS=REMARKS,    
       @TO_DATE=TO_DATE,@RECCLOSE=RECCLOSE,
       @MIN_COVER=MIN_COVER    
FROM TBLCLIENTMARGIN_MAKER_CHECKER     
WHERE PARTY_CODE = @PARTYCODE AND SRNO = @SRNO    
    
IF @STATUS = 'A'    
BEGIN    
 IF @RECTYPE = 'ADD'    
 BEGIN    
  INSERT INTO TBLCLIENTMARGIN_NEW     
  SELECT    
 PARTY_CODE,MARGIN_FUNDING,MARGIN_INTEREST,SANCTIONED_AMT,MAX_AMT,MIN_COVER,FROM_DATE,TO_DATE,ENTERED_BY=@USERID,ENTERED_DATE=GETDATE(),  
 AUTO_RMS,REMARKS,DOC_TYPE,FY_DOC  
  FROM TBLCLIENTMARGIN_MAKER_CHECKER WHERE PARTY_CODE = @PARTYCODE AND SRNO = @SRNO    
    
  DELETE FROM TBLCLIENTMARGIN    
  WHERE PARTY_CODE = @PARTYCODE    
      
  INSERT INTO TBLCLIENTMARGIN    
  SELECT  
    PARTY_CODE,MARGIN_FUNDING,MARGIN_INTEREST,SANCTIONED_AMT,MAX_AMT,MIN_COVER,FROM_DATE,TO_DATE,ENTERED_BY=@USERID,ENTERED_DATE=GETDATE(),  
 AUTO_RMS,REMARKS,DOC_TYPE,FY_DOC  
  FROM TBLCLIENTMARGIN_MAKER_CHECKER WHERE PARTY_CODE = @PARTYCODE AND SRNO = @SRNO    
 END    
    
 IF @RECTYPE = 'EDIT'    
 BEGIN    
  IF @RECCLOSE = 'Y'    
  BEGIN    
   UPDATE TBLCLIENTMARGIN_NEW SET TO_DATE = @FROM_DATE + ' 23:59:59',ENTERED_BY=@USERID,ENTERED_DATE=GETDATE()    
   WHERE PARTY_CODE = @PARTYCODE    
   AND LEFT(TO_DATE,11) > GETDATE()    
    
   UPDATE TBLCLIENTMARGIN SET TO_DATE = @FROM_DATE + ' 23:59:59',ENTERED_BY=@USERID,ENTERED_DATE=GETDATE()    
   WHERE PARTY_CODE = @PARTYCODE    
   AND LEFT(TO_DATE,11) > GETDATE()    
    
   UPDATE TBLCLIENTMARGIN_MAKER_CHECKER SET TO_DATE = @FROM_DATE + ' 23:59:59'     
   WHERE PARTY_CODE = @PARTYCODE AND SRNO = @SRNO    
  END    
  ELSE    
  BEGIN    
   IF CONVERT(DATETIME,@FROM_DATE) < LEFT(GETDATE(),11)    
   BEGIN    
    SELECT @NEWSANCTIONED_AMT = 0    
   END    
   ELSE    
   BEGIN    
    SELECT @NEWSANCTIONED_AMT = @SANCTIONED_AMT     
   END     
   INSERT INTO TBLCLIENTMARGIN_NEW     
   SELECT   
   PARTY_CODE,MARGIN_FUNDING,MARGIN_INTEREST,SANCTIONED_AMT,MAX_AMT,MIN_COVER,FROM_DATE,TO_DATE=LEFT(@FROM_DATE-1,11) + ' 23:59:59',  
   ENTERED_BY,ENTERED_DATE,AUTO_RMS,REMARKS,DOC_TYPE,FY_DOC   
   FROM TBLCLIENTMARGIN_NEW    
   WHERE PARTY_CODE = @PARTYCODE    
   AND @FROM_DATE BETWEEN FROM_DATE AND TO_DATE    
    
   UPDATE TBLCLIENTMARGIN_NEW SET FROM_DATE=@FROM_DATE    
   WHERE PARTY_CODE = @PARTYCODE    
   AND @FROM_DATE BETWEEN FROM_DATE AND TO_DATE    
    
   UPDATE TBLCLIENTMARGIN_NEW SET MARGIN_INTEREST=@MARGIN_INTEREST, MIN_COVER = @MIN_COVER,   
   SANCTIONED_AMT=(CASE WHEN @NEWSANCTIONED_AMT = 0 THEN SANCTIONED_AMT ELSE @SANCTIONED_AMT END),    
   ENTERED_BY=@USERID,ENTERED_DATE=GETDATE(),    
   REMARKS=@REMARKS    
   WHERE PARTY_CODE = @PARTYCODE    
   AND TO_DATE > @FROM_DATE     
    
   UPDATE TBLCLIENTMARGIN SET MARGIN_INTEREST=@MARGIN_INTEREST, MIN_COVER = @MIN_COVER,    
   SANCTIONED_AMT=(CASE WHEN @NEWSANCTIONED_AMT = 0 THEN SANCTIONED_AMT ELSE @SANCTIONED_AMT END),    
   ENTERED_BY=@USERID,ENTERED_DATE=GETDATE(),    
   REMARKS=@REMARKS    
   WHERE PARTY_CODE = @PARTYCODE    
   AND LEFT(TO_DATE,11) > GETDATE()    
  END    
 END    
END    
    
INSERT INTO TBLCLIENTMARGIN_MAKER_CHECKER_LOG    
      
SELECT PARTY_CODE,MARGIN_FUNDING,MARGIN_INTEREST,SANCTIONED_AMT,MAX_AMT,MIN_COVER,FROM_DATE,TO_DATE=LEFT(@FROM_DATE-1,11) + ' 23:59:59',  
   ENTERED_BY,ENTERED_DATE,AUTO_RMS,REMARKS,DOC_TYPE,FY_DOC,RECSTATUS=@STATUS,RECTYPE,RECCLOSE,APPROVED_BY=@USERID,APPROVED_ON=GETDATE(),  
   APP_REMARKS=@APPREMARK    
FROM TBLCLIENTMARGIN_MAKER_CHECKER WHERE PARTY_CODE = @PARTYCODE AND SRNO = @SRNO    
    
DELETE FROM TBLCLIENTMARGIN_MAKER_CHECKER WHERE PARTY_CODE = @PARTYCODE AND SRNO = @SRNO    
DELETE FROM TBLCLIENTMARGIN_NEW WHERE FROM_DATE > TO_DATE

GO
