-- Object: PROCEDURE dbo.PROC_MTF_CASH_MARGIN_DETAILS
-- Server: 10.253.33.91 | DB: INHOUSE
--------------------------------------------------


CREATE PROC [dbo].[PROC_MTF_CASH_MARGIN_DETAILS] (@SAUDA_DATE DATETIME)
  AS
  /*
  PURPOSE : PROVIDING MTF CASH MARGIN TOWARDS AWS CCE AND CCS PROCESS
  DEVLOPER : SIVA
  APPROVER : RAHUL SHAH
  */
 DELETE
 FROM MTF_TDAY_MARGIN_BENEFIT WHERE SAUDA_DATE=@SAUDA_DATE
 INSERT INTO MTF_TDAY_MARGIN_BENEFIT
 SELECT SAUDA_DATE,PARTY_CODE,REQUIRED_MARGIN=0,	AVAILABLE_CASH_BAL=0,	TODAY_MARGIN=VAMT
 FROM(
			SELECT	SAUDA_DATE,PARTY_CODE, VAMT = SUM(NETAMT) + MTFLEDBAL 		
			FROM	MTFTRADE.DBO.TBL_MTF_DATA M WITH (NOLOCK)
			WHERE	SAUDA_DATE = @SAUDA_DATE
			GROUP BY
					SAUDA_DATE,PARTY_CODE, MTFLEDBAL
			HAVING	(SUM(NETAMT) + MTFLEDBAL) > 0
			) A

			--EXEC MTFTRADE.DBO.RPT_NSE_MTFFILE_NEWMTF_NONPAYIN @SAUDA_DATE,1

			EXEC MTFTRADE.DBO.RPT_MTR_MTFFILE_NEW @SAUDA_DATE,1

GO
