-- Object: PROCEDURE dbo.PROC_NEWBASICREPORT_PARENT_IPFT_NXT
-- Server: 10.253.33.91 | DB: INHOUSE
--------------------------------------------------


--EXEC PROC_NEWBASICREPORT_PARENT '', '', '%', 'DEC 12 2000 ', 'DEC 12 2009 ', '', '', '0', 'ZZZ', 'PARTY_CODE', 'S', '0', '1', '1', '', 'BROKER', 'BROKER' 
--EXEC PROC_NEWBASICREPORT_PARENT '', '', '%', 'DEC 22 2006 ', 'DEC 22 2009 ', '', '', '0A141', '0A141', 'PARTY_CODE', 'S', '0', '3.3', '3.3', 'CLI', 'BROKER', 'BROKER'
--EXEC PROC_NEWBASICREPORT_PARENT '', '', '%', 'DEC 22 2006 ', 'DEC 22 2009 ', '', '', '1', 'HO', 'BRANCH_CD', 'S', '0', '1', '1', '', 'BROKER', 'BROKER' 
  
CREATE PROCEDURE [dbo].[PROC_NEWBASICREPORT_PARENT_IPFT_NXT] (   
@SAUDA_DATE VARCHAR(11),  ---4 SAUDA_DATE (FROM)  
@TODATE VARCHAR(11),   ---5 SAUDA_DATE (TO)  
@SUBBROKER VARCHAR(25) ,
@FLAG VARCHAR(1),
@PartyCode varchar(25))  

AS  
/*
exec PROC_NEWBASICREPORT_PARENT_IPFT_NXT 'Oct 01 2024','Oct 03 2024','ET','S','K8904'
exec PROC_NEWBASICREPORT_PARENT_IPFT_NXT 'Oct 01 2024','Oct 03 2024','ET','P','K8904'
*/


SELECT	
	
	PARTY_CODE,
	PARENTCODE,
	PARTY_NAME = LONG_NAME,
	CLIENTTYPE = CL_TYPE,
	BRANCH_CD,
	SUB_BROKER
INTO	
	#PARTYVIEW
FROM	
	MSAJAG.DBO.CLIENT1 C1 (NOLOCK), MSAJAG.DBO.CLIENT2 C2 (NOLOCK)
WHERE	
	C1.CL_CODE = C2.CL_CODE
	AND SUB_BROKER=@SUBBROKER AND C1.Cl_Code = @PartyCode


select sum(ipft_chrg) ipftchrg,PARTY_CODE into #TBL_ADDITIONAL_TAX_DATA from [ANGELNSECM].MSAJAG.dbo.TBL_ADDITIONAL_TAX_DATA T
where SAUDA_DATE BETWEEN @SAUDA_DATE AND @TODATE
group by PARTY_CODE


CREATE CLUSTERED INDEX [PARTY] ON [DBO].[#PARTYVIEW] 
(
	[PARENTCODE] ASC,
	[PARTY_CODE] ASC,BRANCH_CD,SUB_BROKER
)

IF @FLAG ='S'
BEGIN 

SELECT S.SCRIP_CD,S.SERIES,SCRIP_NAME,
PTRADEDQTY = SUM(PQTYTRD + PQTYDEL) ,
PTRADEDAMT = SUM(PAMTTRD + PAMTDEL) ,STRADEDQTY = SUM(SQTYTRD + SQTYDEL), STRADEDAMT = SUM(SAMTTRD + SAMTDEL), 
BUYBROKERAGE = SUM(PBROKTRD) , SELBROKERAGE= SUM(SBROKTRD) , BUYDELIVERYCHRG = SUM(PBROKDEL), 
SELLDELIVERYCHRG = SUM(SBROKDEL), CLIENTTYPE='', BILLPAMT = SUM(PAMT) , BILLSAMT = SUM(SAMT) , 
PMARKETRATE = ( SUM(PRATE) / CASE WHEN SUM(PQTYTRD + PQTYDEL) > 0 THEN SUM(PQTYTRD + PQTYDEL) ELSE 1 END) , 
SMARKETRATE = ( SUM(SRATE) / (CASE WHEN SUM(SQTYTRD + SQTYDEL) > 0 THEN SUM(SQTYTRD + SQTYDEL) ELSE 1 END ) ),  
PNETRATE = ( SUM(PAMTTRD + PAMTDEL) / CASE WHEN SUM(PQTYTRD + PQTYDEL) > 0 THEN SUM(PQTYTRD + PQTYDEL) ELSE 1 END) , 
SNETRATE = ( SUM(SAMTTRD+SAMTDEL) / (CASE WHEN SUM(SQTYTRD + SQTYDEL) > 0 THEN SUM(SQTYTRD + SQTYDEL) ELSE 1 END ) ), 
TRDAMT= SUM(TRDAMT) ,DELAMT=SUM(DELAMT), SERINEX=SUM(SERINEX),SERVICE_TAX= SUM(SERVICE_TAX) ,EXSERVICE_TAX= SUM(EXSERVICE_TAX),
TURN_TAX=SUM(TURN_TAX),SEBI_TAX=SUM(SEBI_TAX),INS_CHRG=SUM(INS_CHRG),BROKER_CHRG=SUM(BROKER_CHRG),OTHER_CHRG=SUM(OTHER_CHRG), 
MEMBERTYPE, COMPANYNAME,PNL = SUM(SAMTTRD-PAMTTRD) ,ipftchrg=max(IPFTCHRG)
 FROM MSAJAG.DBO.CMBILLVALAN S inner join #PARTYVIEW C (NOLOCK) on C.BRANCH_CD = S.BRANCH_CD  and  C.PARTY_CODE = S.PARTY_CODE  
left join (select sum(ipft_chrg) ipftchrg,party_code,SCRIP_CD from  MSAJAG.dbo.TBL_ADDITIONAL_TAX_DATA group by party_code,SCRIP_CD) IPFT  
on IPFT.party_code=S.party_code and IPFT.SCRIP_CD=S.SCRIP_CD
 WHERE S.SAUDA_DATE BETWEEN @SAUDA_DATE AND @TODATE AND S.SCRIP_CD BETWEEN '0MFL21BB' AND 'ZYLOG'
 /*AND S.SETT_NO BETWEEN '0490914' AND '2023505' */  
 AND C.PARENTCODE BETWEEN @PartyCode AND @PartyCode   
 AND C.SUB_BROKER =  @SUBBROKER  
 --and IPFT.party_code=S.party_code and IPFT.SAUDA_DATE=S.SAUDA_DATE
 AND  S.SETT_TYPE BETWEEN '   '  AND 'Z  ' AND  TRADETYPE NOT IN ( 'SCF','ICF','IR' )  
 GROUP BY S.SCRIP_CD,S.SERIES,SCRIP_NAME,MEMBERTYPE, COMPANYNAME 
 ORDER   BY SCRIP_CD  OPTION (FAST 1 ) 
 END

 
IF @FLAG ='P'
BEGIN 

SELECT PARTY_CODE=PARENTCODE, LONG_NAME=C.PARTY_NAME,
PTRADEDQTY = SUM(PQTYTRD + PQTYDEL) ,
PTRADEDAMT = SUM(PAMTTRD + PAMTDEL) ,STRADEDQTY = SUM(SQTYTRD + SQTYDEL), STRADEDAMT = SUM(SAMTTRD + SAMTDEL), 
BUYBROKERAGE = SUM(PBROKTRD) , SELBROKERAGE= SUM(SBROKTRD) , BUYDELIVERYCHRG = SUM(PBROKDEL), 
SELLDELIVERYCHRG = SUM(SBROKDEL), C.CLIENTTYPE, BILLPAMT = SUM(PAMT) , BILLSAMT = SUM(SAMT) , 
PMARKETRATE = ( SUM(PRATE) / CASE WHEN SUM(PQTYTRD + PQTYDEL) > 0 THEN SUM(PQTYTRD + PQTYDEL) ELSE 1 END) , 
SMARKETRATE = ( SUM(SRATE) / (CASE WHEN SUM(SQTYTRD + SQTYDEL) > 0 THEN SUM(SQTYTRD + SQTYDEL) ELSE 1 END ) ),  
PNETRATE = ( SUM(PAMTTRD + PAMTDEL) / CASE WHEN SUM(PQTYTRD + PQTYDEL) > 0 THEN SUM(PQTYTRD + PQTYDEL) ELSE 1 END) , 
SNETRATE = ( SUM(SAMTTRD+SAMTDEL) / (CASE WHEN SUM(SQTYTRD + SQTYDEL) > 0 THEN SUM(SQTYTRD + SQTYDEL) ELSE 1 END ) ), 
TRDAMT= SUM(TRDAMT) ,DELAMT=SUM(DELAMT), SERINEX=SUM(SERINEX),SERVICE_TAX= SUM(SERVICE_TAX) ,EXSERVICE_TAX= SUM(EXSERVICE_TAX),
TURN_TAX=SUM(TURN_TAX),SEBI_TAX=SUM(SEBI_TAX),INS_CHRG=SUM(INS_CHRG),BROKER_CHRG=SUM(BROKER_CHRG),OTHER_CHRG=SUM(OTHER_CHRG), 
MEMBERTYPE, COMPANYNAME,PNL = SUM(SAMTTRD-PAMTTRD) ,ipftchrg=max(IPFTCHRG)
 FROM MSAJAG.DBO.CMBILLVALAN S inner join #PARTYVIEW C (NOLOCK) on C.BRANCH_CD = S.BRANCH_CD  and  C.PARTY_CODE = S.PARTY_CODE  
 left join #TBL_ADDITIONAL_TAX_DATA IPFT on IPFT.party_code=S.party_code --and IPFT.SAUDA_DATE=convert(date,S.SAUDA_DATE)
 WHERE S.SAUDA_DATE BETWEEN @SAUDA_DATE AND @TODATE AND S.SCRIP_CD BETWEEN '0MFL21BB' AND 'ZYLOG'
 AND C.PARENTCODE BETWEEN @PartyCode AND @PartyCode   
 --AND C.PARTY_CODE = S.PARTY_CODE  
 --AND C.BRANCH_CD = S.BRANCH_CD  
 AND C.SUB_BROKER =  @SUBBROKER 
 --and IPFT.party_code=S.party_code-- and IPFT.SAUDA_DATE=S.SAUDA_DATE
 AND  S.SETT_TYPE BETWEEN '   '  AND 'Z  ' AND  TRADETYPE NOT IN ( 'SCF','ICF','IR' )  
 GROUP BY PARENTCODE, C.PARTY_NAME,C.CLIENTTYPE,MEMBERTYPE, COMPANYNAME 
 ORDER   BY PARENTCODE  OPTION (FAST 1 ) 
 END

GO
