-- Object: PROCEDURE dbo.BROK_GL_LEDGER_UP_DOWN_STREAM
-- Server: 10.253.33.91 | DB: INHOUSE
--------------------------------------------------


CREATE PROC BROK_GL_LEDGER_UP_DOWN_STREAM (@TODATE VARCHAR(11))

AS

DECLARE @FROMDATE  VARCHAR(11)

SET @FROMDATE = CONVERT(VARCHAR(11),CONVERT(VARCHAR(3),LEFT(@TODATE,3))+CONVERT(VARCHAR(3),' 1 ')+CONVERT(VARCHAR(4),RIGHT(@TODATE,4)))

SELECT CLTCODE,EXCHANGE,SUM(CASE WHEN DRCR = 'D' THEN -VAMT ELSE VAMT END) AS VAMT 
INTO #LEDGER_ALL_GL
FROM ACCOUNT.DBO.LEDGER_ALL WITH (NOLOCK)
WHERE CLTCODE IN ('520014','520122','520123','61310','61410','99890','99990')
AND VDT BETWEEN @FROMDATE AND @TODATE + ' 23:59:59'
GROUP BY CLTCODE,EXCHANGE

SELECT CLTCODE,ISNULL([NSE],0) AS [NSE],ISNULL([BSE],0) AS [BSE],ISNULL([NSEFO],0) AS [NSEFO],
ISNULL([NSX],0) AS [NSX],ISNULL([MCX],0) AS [MCX],ISNULL([NCX],0) AS [NCX],
TOTAL = ISNULL([NSE],0)+ISNULL([BSE],0)+ISNULL([NSEFO],0)+ISNULL([NSX],0)+ISNULL([MCX],0)+ISNULL([NCX],0)
FROM
(SELECT CLTCODE,EXCHANGE,VAMT FROM #LEDGER_ALL_GL) AS SORUCE
PIVOT
(SUM(VAMT) FOR EXCHANGE IN ([NSE],[BSE],[NSEFO],[NSX],[MCX],[NCX])) AS PVTTAB

DROP TABLE #LEDGER_ALL_GL

GO
