-- Object: PROCEDURE dbo.CAPITALREQUIREMENT_DETAIL_EOD_PEAK_ANG
-- Server: 10.253.33.91 | DB: INHOUSE
--------------------------------------------------


CREATE PROC CAPITALREQUIREMENT_DETAIL_EOD_PEAK_ANG (@TPYPE VARCHAR(1),@MDATE DATETIME)
AS

--DECLARE @MDATE DATETIME
--SET @MDATE = 'FEB 16 2024'

IF @TPYPE = 'A'
BEGIN
SELECT @MDATE = MAX(RECORDDATE) FROM MSAJAG.DBO.TBL_CCCM_SCRIP_DATA  WITH (NOLOCK)  
END



IF (SELECT COUNT(1) FROM  INHOUSE.DBO.CAPITALREQUIREMENT_DETAIL_EOD WHERE MDATE = @MDATE) > 0 
BEGIN
GOTO FINALSUMM;
END

SELECT CONVERT(VARCHAR(11),MARGINDATE,109) AS MARGINDATE,PARTY_CODE,SUM(TDAY_MARGIN) AS  TDAY_MARGIN,SUM(TDAY_LEDGER) AS TDAY_LEDGER,0 AS TDAY_CASHCOLL  
INTO #TBL_COMBINE_REPORTING_EOD
FROM MSAJAG.DBO.TBL_COMBINE_REPORTING_DETAIL WITH (NOLOCK)  
WHERE MARGINDATE = @MDATE
AND PARTY_CODE BETWEEN 'A' AND 'ZZZZZZZZZZ'
GROUP BY CONVERT(VARCHAR(11),MARGINDATE,109) ,PARTY_CODE
 
INSERT INTO #TBL_COMBINE_REPORTING_EOD
SELECT CONVERT(VARCHAR(11),MARGINDATE,109) AS MARGINDATE,PARTY_CODE,0 AS  TDAY_MARGIN,0 AS TDAY_LEDGER,SUM(TDAY_CASHCOLL) AS TDAY_CASHCOLL
FROM MSAJAG.DBO.TBL_COMBINE_REPORTING_DETAIL A  WITH (NOLOCK)              
WHERE A.MARGINDATE = @MDATE              
AND EXCHANGE = 'EPN' AND SEGMENT = 'EPN'           
AND PARTY_CODE BETWEEN 'A' AND 'ZZZZZZZZZZ'
GROUP BY CONVERT(VARCHAR(11),MARGINDATE,109) ,PARTY_CODE
 
 

IF (SELECT COUNT(*) FROM #TBL_COMBINE_REPORTING_EOD) = 0
BEGIN
INSERT INTO #TBL_COMBINE_REPORTING_EOD
SELECT CONVERT(VARCHAR(11),MARGINDATE,109) AS MARGINDATE,PARTY_CODE,MAX(TDAY_MARGIN) AS  TDAY_MARGIN,SUM(TDAY_LEDGER) AS TDAY_LEDGER,0 AS TDAY_CASHCOLL 
FROM MSAJAG.DBO.TBL_COMBINE_REPORTING_DETAIL_HIST WITH (NOLOCK)  
WHERE MARGINDATE = @MDATE
AND PARTY_CODE BETWEEN 'A' AND 'ZZZZZZZZZZ'
GROUP BY CONVERT(VARCHAR(11),MARGINDATE,109) ,PARTY_CODE
 
INSERT INTO #TBL_COMBINE_REPORTING_EOD
SELECT CONVERT(VARCHAR(11),MARGINDATE,109) AS MARGINDATE,PARTY_CODE,0 AS  TDAY_MARGIN,0 AS TDAY_LEDGER,SUM(TDAY_CASHCOLL) AS TDAY_CASHCOLL
FROM MSAJAG.DBO.TBL_COMBINE_REPORTING_DETAIL_HIST A  WITH (NOLOCK)              
WHERE A.MARGINDATE = @MDATE              
AND EXCHANGE = 'EPN' AND SEGMENT = 'EPN'           
AND PARTY_CODE BETWEEN 'A' AND 'ZZZZZZZZZZ'
GROUP BY CONVERT(VARCHAR(11),MARGINDATE,109) ,PARTY_CODE
 

END
 
SELECT CONVERT(VARCHAR(11),MARGINDATE,109) AS MARGINDATE,PARTY_CODE,SUM(TDAY_MARGIN) AS  TDAY_MARGIN,SUM(TDAY_LEDGER) AS TDAY_LEDGER,0 AS TDAY_CASHCOLL 
INTO #TBL_COMBINE_REPORTING_PEAK
FROM MSAJAG.DBO.TBL_COMBINE_REPORTING_PEAK_DETAIL WITH (NOLOCK)  
WHERE MARGINDATE = @MDATE
AND PARTY_CODE BETWEEN 'A' AND 'ZZZZZZZZZZ'
GROUP BY CONVERT(VARCHAR(11),MARGINDATE,109) ,PARTY_CODE

/*
INSERT INTO #TBL_COMBINE_REPORTING_PEAK
SELECT CONVERT(VARCHAR(11),MARGINDATE,109) AS MARGINDATE,PARTY_CODE,0 AS  TDAY_MARGIN,0 AS TDAY_LEDGER,SUM(TDAY_CASHCOLL) AS TDAY_CASHCOLL
FROM MSAJAG.DBO.TBL_COMBINE_REPORTING_PEAK_DETAIL A  WITH (NOLOCK)              
WHERE A.MARGINDATE = @MDATE              
AND EXCHANGE = 'EPN' AND SEGMENT = 'EPN'           
AND PARTY_CODE BETWEEN 'A' AND 'ZZZZZZZZZZ'
GROUP BY CONVERT(VARCHAR(11),MARGINDATE,109) ,PARTY_CODE
*/

SELECT PARTY_CODE,SUM(TDAY_MARGIN) AS MAX_MARGIN,SUM(TDAY_LEDGER) AS TDAY_LEDGER,SUM(TDAY_CASHCOLL) AS EPIAMOUNT INTO #TBL_COMBINE_REPORTING_PEAK1
FROM #TBL_COMBINE_REPORTING_PEAK
GROUP BY PARTY_CODE
 

SELECT PARTY_CODE,SUM(TDAY_MARGIN) AS MAX_MARGIN,SUM(TDAY_LEDGER) AS TDAY_LEDGER,SUM(TDAY_CASHCOLL) AS EPIAMOUNT INTO #CLIENTDATA
FROM #TBL_COMBINE_REPORTING_EOD
GROUP BY PARTY_CODE

UPDATE #TBL_COMBINE_REPORTING_PEAK1 SET EPIAMOUNT = #CLIENTDATA.EPIAMOUNT FROM #CLIENTDATA WHERE #CLIENTDATA.PARTY_CODE = #TBL_COMBINE_REPORTING_PEAK1.PARTY_CODE

DELETE #CLIENTDATA WHERE MAX_MARGIN = 0
DELETE #TBL_COMBINE_REPORTING_PEAK1 WHERE MAX_MARGIN = 0
               
  /*
SELECT PARTY_CODE ,CASE WHEN EOD_MARGIN > PEAK_MARGIN THEN EOD_MARGIN ELSE PEAK_MARGIN END AS MAX_MARGIN,
CASE WHEN EOD_EPI > PEAK_EPI THEN EOD_EPI ELSE PEAK_EPI END AS MAX_EPIAMOUNT,EOD_EPI AS  EPIAMOUNT
INTO #CLIENTDATA FROM (
SELECT PARTY_CODE,SUM(TDAY_MARGIN) AS EOD_MARGIN,0 AS PEAK_MARGIN,SUM(TDAY_CASHCOLL) AS EOD_EPI,0 AS PEAK_EPI FROM #TBL_COMBINE_REPORTING_EOD1 
GROUP BY PARTY_CODE
UNION ALL 
SELECT PARTY_CODE,0 AS EOD_MARGIN,SUM(TDAY_MARGIN) AS PEAK_MARGIN,0 AS EOD_EPI,SUM(TDAY_CASHCOLL) AS PEAK_EPI FROM #TBL_COMBINE_REPORTING_PEAK1 
GROUP BY PARTY_CODE) AS A
 
CREATE TABLE #EPI_POOL_ACCOUNT (EXCHANGE VARCHAR(10),SEGMENT VARCHAR(10),PARTY_CODE VARCHAR(10),POOLACCOUNT NUMERIC (18,2),
EPIAMOUNT NUMERIC (18,2) ,LEDACCOUNT NUMERIC (18,2))

INSERT INTO #EPI_POOL_ACCOUNT EXEC MSAJAG.DBO.GET_EPI_POOL_ACCOUNT @MDATE

SELECT PARTY_CODE AS CLTCODE,CASE WHEN EOD_MARGIN > PEAK_MARGIN THEN EOD_MARGIN ELSE PEAK_MARGIN END AS MAX_MARGIN
INTO #CLIENTDATA FROM (SELECT PARTY_CODE,SUM(TDAY_MARGIN) AS EOD_MARGIN,0 AS PEAK_MARGIN
FROM #TBL_COMBINE_REPORTING_EOD GROUP BY PARTY_CODE
UNION ALL SELECT PARTY_CODE,0 AS EOD_MARGIN,SUM(TDAY_MARGIN) AS PEAK_MARGIN FROM #TBL_COMBINE_REPORTING_PEAK GROUP BY PARTY_CODE) AS A

DELETE #EPI_POOL_ACCOUNT WHERE PARTY_CODE NOT IN (SELECT CLTCODE FROM #CLIENTDATA)

SELECT PARTY_CODE,SUM(EPIAMOUNT) AS EPIAMOUNT INTO #EPI_POOL_ACCOUNT1 FROM #EPI_POOL_ACCOUNT GROUP BY PARTY_CODE

*/

DECLARE @TODATE VARCHAR(11) 

SET @TODATE = @MDATE - 1

DECLARE @FINSTDT DATETIME 

DECLARE @FROMDATE VARCHAR(11)  
 
CREATE INDEX CLIIDX ON #CLIENTDATA (PARTY_CODE)

SELECT @FINSTDT = SDTCUR ,@FROMDATE  = SDTCUR FROM ACCOUNT.DBO.PARAMETER WITH (NOLOCK) WHERE @TODATE BETWEEN SDTCUR AND LDTCUR
 
SELECT CLTCODE,SUM(VAMT)AS VAMT,CONVERT(VARCHAR(10),'') AS SEGMENT  INTO #VDTLED FROM (    
SELECT L.CLTCODE,SUM(CASE WHEN DRCR='D'THEN VAMT ELSE -VAMT END)VAMT FROM   ACCOUNT.DBO.LEDGER L WITH(NOLOCK) 
WHERE    VDT>=@FINSTDT   AND  VDT< = @TODATE  + ' 23:59' AND 1 <> 1  GROUP BY L.CLTCODE)A    
 GROUP BY CLTCODE    
 HAVING SUM(VAMT) <>0

SELECT CLTCODE,SUM(VAMT) AS VAMT,CONVERT(VARCHAR(10),'') AS SEGMENT  INTO #EDTLED FROM (    
SELECT L.CLTCODE, VAMT = ISNULL(SUM(CASE WHEN UPPER(DRCR) = 'D' THEN VAMT ELSE -VAMT END ), 0) 
FROM ACCOUNT.DBO.LEDGER L WITH(NOLOCK) 
WHERE EDT >= @FROMDATE + ' 00:00:00' 	AND L.EDT <= @FROMDATE + ' 23:59:59'  AND VTYP = 18   AND 1 <> 1 
GROUP BY L.CLTCODE 
UNION ALL
SELECT L.CLTCODE, VAMT = ISNULL(SUM( CASE WHEN UPPER(DRCR) = 'C' THEN VAMT ELSE -VAMT END ), 0) 
FROM ACCOUNT.DBO.LEDGER L WITH (NOLOCK) 
WHERE VDT < @FROMDATE AND EDT >= @FROMDATE  AND 1 <> 1 
GROUP BY L.CLTCODE
UNION ALL
SELECT L.CLTCODE, VAMT = SUM(CASE WHEN DRCR = 'D' THEN L.VAMT ELSE -VAMT END) 
FROM  ACCOUNT.DBO.LEDGER L WITH (NOLOCK)  
WHERE L.EDT >= @FROMDATE + ' 00:00:00' 	AND L.EDT <= @TODATE + ' 23:59:59' AND VTYP <> 18  AND 1 <> 1  
GROUP BY L.CLTCODE)A     GROUP BY CLTCODE     HAVING SUM(VAMT) <>0

 SELECT * INTO #VDTLED_FINAL FROM #VDTLED WHERE 1 <> 1
 
 SELECT * INTO #EDTLED_FINAL FROM #EDTLED WHERE 1 <> 1

CREATE TABLE #MULTIDATABASE (SERVERNAME VARCHAR(100),DATABASENAME VARCHAR(100),SEGMENT VARCHAR(100),SRNO INT IDENTITY (1,1))

INSERT INTO #MULTIDATABASE SELECT 'ANAND1','ACCOUNT','NSE'
INSERT INTO #MULTIDATABASE SELECT 'ANAND1','ACCOUNTSLBS','SLBM'
INSERT INTO #MULTIDATABASE SELECT 'ANAND1','MTFTRADE','MTF'
INSERT INTO #MULTIDATABASE SELECT 'ANAND','ACCOUNT_AB','BSE'
INSERT INTO #MULTIDATABASE SELECT 'ANGELFO','ACCOUNTFO','NSEFO'
INSERT INTO #MULTIDATABASE SELECT 'ANGELFO','ACCOUNTCURFO','NSX'
INSERT INTO #MULTIDATABASE SELECT 'ANGELCOMMODITY','ACCOUNTNCDX','NCDX'
INSERT INTO #MULTIDATABASE SELECT 'ANGELCOMMODITY','ACCOUNTMCDX','MCX'
INSERT INTO #MULTIDATABASE SELECT 'ANGELCOMMODITY','ACCOUNTMCDXCDS','MCD'
INSERT INTO #MULTIDATABASE SELECT 'ANGELCOMMODITY','ACCOUNTBFO','BSEFO'
INSERT INTO #MULTIDATABASE SELECT 'ANGELCOMMODITY','ACCOUNTCURBFO','BSECURFO'


DECLARE @SNAME VARCHAR(100),@DNAME VARCHAR(100),@SEGMENT VARCHAR(100),@SRNOMAX INT,@COUNTINT INT

SET @COUNTINT = 1

SELECT @SRNOMAX = MAX(SRNO) FROM #MULTIDATABASE

WHILE @COUNTINT <= @SRNOMAX
BEGIN

SELECT @SNAME = SERVERNAME , @DNAME = DATABASENAME ,@SEGMENT = SEGMENT FROM #MULTIDATABASE WHERE SRNO = @COUNTINT

IF @SNAME = 'ANAND1'
BEGIN 

TRUNCATE TABLE #VDTLED

EXEC ('INSERT INTO #VDTLED
SELECT L.CLTCODE,SUM(CASE WHEN DRCR= ''D'' THEN -VAMT ELSE VAMT END) AS VAMT,''' + @SEGMENT + '''  FROM ' + @DNAME + '.DBO.LEDGER  L WITH (NOLOCK) 
WHERE  VDT BETWEEN ''' + @FINSTDT + ''' AND ''' + @TODATE + ' 23:59:59'' GROUP BY L.CLTCODE HAVING SUM(VAMT) <> 0 ') 

INSERT INTO #VDTLED_FINAL SELECT * FROM #VDTLED


TRUNCATE TABLE #EDTLED


EXEC ('INSERT  INTO #EDTLED  SELECT CLTCODE,SUM(VAMT) AS VAMT,SEGMENT FROM (    
SELECT L.CLTCODE, ISNULL(SUM(CASE WHEN UPPER(DRCR) = ''D'' THEN VAMT ELSE -VAMT END ), 0) AS VAMT , SEGMENT = ''' + @SEGMENT + '''  FROM ' + @DNAME + '.DBO.LEDGER  L WITH (NOLOCK) 
WHERE L.EDT >= ''' + @FROMDATE + '''' + '+ '' 00:00:00'' AND L.EDT <=  ''' + @FROMDATE + '''' + '+ '' 23:59:59'' AND VTYP = 18  
GROUP BY L.CLTCODE 
UNION ALL
SELECT L.CLTCODE, ISNULL(SUM( CASE WHEN UPPER(DRCR) = ''C'' THEN VAMT ELSE -VAMT END ), 0) AS VAMT , SEGMENT = ''' + @SEGMENT + '''  FROM ' + @DNAME + '.DBO.LEDGER  L WITH (NOLOCK) 
WHERE VDT < ''' + @FROMDATE  + ''' AND EDT >= ''' + @FROMDATE  + '''  
GROUP BY L.CLTCODE
UNION ALL
SELECT L.CLTCODE, SUM(CASE WHEN DRCR = ''D'' THEN L.VAMT ELSE -VAMT END) AS VAMT , SEGMENT = ''' + @SEGMENT + '''  FROM ' + @DNAME + '.DBO.LEDGER  L WITH (NOLOCK)  
WHERE L.EDT >= ''' + @FROMDATE + '''' + '+ '' 00:00:00'' AND L.EDT <=  ''' + @TODATE + '''' + '+ '' 23:59:59'' AND VTYP <> 18   
GROUP BY L.CLTCODE)A     GROUP BY CLTCODE,SEGMENT     HAVING SUM(VAMT) <> 0 ') 


INSERT INTO #EDTLED_FINAL SELECT * FROM #EDTLED


END
ELSE
BEGIN
TRUNCATE TABLE #VDTLED

EXEC ('INSERT INTO #VDTLED
SELECT L.CLTCODE,SUM(CASE WHEN DRCR= ''D'' THEN -VAMT ELSE VAMT END) AS VAMT,''' + @SEGMENT + '''  FROM ' + @SNAME + '.' + @DNAME + '.DBO.LEDGER L WITH (NOLOCK)  
WHERE  VDT BETWEEN ''' + @FINSTDT + ''' AND ''' + @TODATE + ' 23:59:59''    GROUP BY L.CLTCODE HAVING SUM(VAMT) <> 0 ') 

INSERT INTO #VDTLED_FINAL SELECT * FROM #VDTLED


TRUNCATE TABLE #EDTLED


EXEC ('INSERT  INTO #EDTLED  SELECT CLTCODE,SUM(VAMT) AS VAMT,SEGMENT FROM (    
SELECT L.CLTCODE, ISNULL(SUM(CASE WHEN UPPER(DRCR) = ''D'' THEN VAMT ELSE -VAMT END ), 0) AS VAMT , SEGMENT = ''' + @SEGMENT + '''  FROM ' + @SNAME + '.' + @DNAME + '.DBO.LEDGER  L WITH (NOLOCK)  
WHERE L.EDT >= ''' + @FROMDATE + '''' + '+ '' 00:00:00'' AND L.EDT <=  ''' + @FROMDATE + '''' + '+ '' 23:59:59'' AND VTYP = 18    
GROUP BY L.CLTCODE 
UNION ALL
SELECT L.CLTCODE, ISNULL(SUM( CASE WHEN UPPER(DRCR) = ''C'' THEN VAMT ELSE -VAMT END ), 0) AS VAMT , SEGMENT = ''' + @SEGMENT + '''  FROM ' + @SNAME + '.' + @DNAME + '.DBO.LEDGER  L WITH (NOLOCK) 
WHERE VDT < ''' + @FROMDATE  + ''' AND EDT >= ''' + @FROMDATE  + '''  
GROUP BY L.CLTCODE
UNION ALL
SELECT L.CLTCODE, SUM(CASE WHEN DRCR = ''D'' THEN L.VAMT ELSE -VAMT END) AS VAMT , SEGMENT = ''' + @SEGMENT + '''  FROM ' + @SNAME + '.' + @DNAME + '.DBO.LEDGER  L WITH (NOLOCK) 
WHERE L.EDT >= ''' + @FROMDATE + '''' + '+ '' 00:00:00'' AND L.EDT <=  ''' + @TODATE + '''' + '+ '' 23:59:59'' AND VTYP <> 18   
GROUP BY L.CLTCODE)A     GROUP BY CLTCODE,SEGMENT     HAVING SUM(VAMT) <> 0 ') 


INSERT INTO #EDTLED_FINAL SELECT * FROM #EDTLED

END

SET @COUNTINT = @COUNTINT + 1

END

SELECT CLTCODE,ISNULL([BSE],0) AS [BSE],ISNULL([BSECURFO],0) AS [BSECURFO],ISNULL([BSEFO],0) AS [BSEFO],
ISNULL([MCD],0) AS [MCD],ISNULL([MCX],0) AS [MCX],ISNULL([MTF] ,0) AS [MTF],
ISNULL([NCDX],0) AS [NCDX] ,ISNULL([NSE],0) AS [NSE],ISNULL([NSEFO],0) AS [NSEFO],ISNULL([NSX],0) AS [NSX],ISNULL([SLBM],0) AS [SLBM]
,ISNULL([BSE],0)+ISNULL([BSECURFO],0)+ISNULL([BSEFO],0)+ISNULL([MCD],0)+ISNULL([MCX],0)+ISNULL([MTF] ,0)+
ISNULL([NCDX],0)+ISNULL([NSE],0)+ISNULL([NSEFO],0)+ISNULL([NSX],0)+ISNULL([SLBM],0) AS TOTAL INTO #TEMP_VDT
FROM
(SELECT CLTCODE,VAMT,SEGMENT FROM #VDTLED_FINAL) AS A
PIVOT
(SUM(VAMT) FOR SEGMENT IN ([BSE],[BSECURFO],[BSEFO],[MCD],[MCX],[MTF],[NCDX],[NSE],[NSEFO],[NSX],[SLBM] )) AS B


CREATE INDEX CLIIDX ON #TEMP_VDT (CLTCODE)

  SELECT  CLTCODE,NSE AS NSE,BSE AS BSE,[NSEFO] AS FO,NSX AS NSX,    
  MCD AS MCD ,MCX AS MCX,[NCDX] AS NCX,BSEFO AS BSEFO,[BSECURFO] AS BSX,MTF AS MTF,[SLBM] AS SLBS,    
      TOTAL AS TOTAL  INTO #TEMP_VDT1
	  FROM #TEMP_VDT 
	   UNION ALL
	SELECT PARTY_CODE AS  CLTCODE,0 AS NSE,0 AS BSE,0 AS FO,0 AS NSX,    
  0 AS MCD ,0 AS MCX,0 AS NCX,0 AS BSEFO,0 AS BSX,0 AS MTF,0 AS SLBS,    
      0 AS TOTAL FROM #CLIENTDATA WHERE PARTY_CODE NOT IN (SELECT CLTCODE FROM #TEMP_VDT)
	



SELECT CLTCODE,ISNULL([BSE],0) AS [BSE],ISNULL([BSECURFO],0) AS [BSECURFO],ISNULL([BSEFO],0) AS [BSEFO],
ISNULL([MCD],0) AS [MCD],ISNULL([MCX],0) AS [MCX],ISNULL([MTF] ,0) AS [MTF],
ISNULL([NCDX],0) AS [NCDX] ,ISNULL([NSE],0) AS [NSE],ISNULL([NSEFO],0) AS [NSEFO],ISNULL([NSX],0) AS [NSX],ISNULL([SLBM],0) AS [SLBM]
,ISNULL([BSE],0)+ISNULL([BSECURFO],0)+ISNULL([BSEFO],0)+ISNULL([MCD],0)+ISNULL([MCX],0)+ISNULL([MTF] ,0)+
ISNULL([NCDX],0)+ISNULL([NSE],0)+ISNULL([NSEFO],0)+ISNULL([NSX],0)+ISNULL([SLBM],0) AS TOTAL INTO #TEMP_EDT
FROM
(SELECT CLTCODE,VAMT,SEGMENT FROM #EDTLED_FINAL) AS A
PIVOT
(SUM(VAMT) FOR SEGMENT IN ([BSE],[BSECURFO],[BSEFO],[MCD],[MCX],[MTF],[NCDX],[NSE],[NSEFO],[NSX],[SLBM] )) AS B

CREATE INDEX CLIIDX ON #TEMP_EDT (CLTCODE)

  SELECT  CLTCODE,NSE*-1 AS NSE,BSE*-1 AS BSE,[NSEFO]*-1 AS FO,NSX*-1 AS NSX,    
  MCD*-1 AS MCD ,MCX*-1 AS MCX,[NCDX]*-1 AS NCX,BSEFO*-1 AS BSEFO,[BSECURFO] AS BSX,MTF*-1 AS MTF,[SLBM]*-1 AS SLBS,    
      TOTAL*-1 AS TOTAL  INTO #TEMP_EDT1
	  FROM #TEMP_EDT 
	  UNION ALL
	SELECT PARTY_CODE AS  CLTCODE,0 AS NSE,0 AS BSE,0 AS FO,0 AS NSX,    
  0 AS MCD ,0 AS MCX,0 AS NCX,0 AS BSEFO,0 AS BSX,0 AS MTF,0 AS SLBS,    
      0 AS TOTAL FROM #CLIENTDATA WHERE PARTY_CODE NOT IN (SELECT CLTCODE FROM #TEMP_EDT)


CREATE INDEX CLIIDX ON #TEMP_VDT1 (CLTCODE)
CREATE INDEX CLIIDX ON #TEMP_EDT1 (CLTCODE)


 SELECT A.CLTCODE,SUM(ETOTAL) AS ETOTAL , SUM(VTOTAL) AS VTOTAL  INTO #TEMP_TOTAL FROM (
SELECT CLTCODE,TOTAL AS ETOTAL,0 AS VTOTAL  FROM #TEMP_EDT1 
UNION ALL
SELECT CLTCODE,0 AS ETOTAL,TOTAL AS VTOTAL  FROM #TEMP_VDT1  ) AS A  , #CLIENTDATA
WHERE A.CLTCODE = #CLIENTDATA.PARTY_CODE
GROUP BY A.CLTCODE
ORDER BY A.CLTCODE


 SELECT A.CLTCODE,SUM(ETOTAL) AS ETOTAL , SUM(VTOTAL) AS VTOTAL  INTO #TEMP_TOTAL_PEAK FROM (
SELECT CLTCODE,TOTAL AS ETOTAL,0 AS VTOTAL  FROM #TEMP_EDT1 
UNION ALL
SELECT CLTCODE,0 AS ETOTAL,TOTAL AS VTOTAL  FROM #TEMP_VDT1  ) AS A  , #TBL_COMBINE_REPORTING_PEAK1
WHERE A.CLTCODE = #TBL_COMBINE_REPORTING_PEAK1.PARTY_CODE
GROUP BY A.CLTCODE
ORDER BY A.CLTCODE
 

DROP TABLE #TEMP_VDT
DROP TABLE #VDTLED_FINAL
DROP TABLE #VDTLED
DROP TABLE #MULTIDATABASE
DROP TABLE #TEMP_VDT1
DROP TABLE #TEMP_EDT
DROP TABLE #EDTLED_FINAL
DROP TABLE #EDTLED
DROP TABLE #TEMP_EDT1

/*
-- PLEDGED
SELECT PARTY_CODE,CERTNO,SUM(QTY) AS QTY  INTO #DELTRANS_PLD
FROM [ANGELDEMAT].MSAJAG.DBO.DELTRANS WITH (NOLOCK) WHERE DRCR='D' AND DELIVERED ='0' AND FILLER2='1'  AND BCLTDPID ='1203320030135814'
AND BRANCHCD ='PLEDGE'
GROUP BY PARTY_CODE,CERTNO
-- PLEDGED

--REPLEDGED

SELECT BCLTDPID,CERTNO,PARTY_CODE,DRCR,QTY INTO #PLDRECD 
FROM [ANGELDEMAT].MSAJAG.DBO.DELTRANS_PLD WHERE DRCR='C' AND HOLDERNAME <>'REPLEDGE'

SELECT BCLTDPID,CERTNO,PARTY_CODE,DRCR,QTY INTO #PLDDEL 
FROM [ANGELDEMAT].MSAJAG.DBO.DELTRANS_PLD WHERE DRCR='D' AND DELIVERED ='D' AND HOLDERNAME <>'REPLEDGE'


SELECT * INTO #ABC FROM
(SELECT * FROM #PLDRECD
UNION ALL
SELECT * FROM #PLDDEL) X
 

SELECT BCLTDPID,CERTNO,PARTY_CODE,DRCR,QTY,QTY1=SUM(CASE WHEN DRCR='C' THEN QTY ELSE -QTY END) INTO #AB FROM #ABC
GROUP BY BCLTDPID,CERTNO,PARTY_CODE,DRCR,QTY
ORDER BY PARTY_CODE,CERTNO

 
SELECT BCLTDPID,CERTNO,PARTY_CODE,SUM(QTY1) AS QTY1 INTO #CC FROM #AB
GROUP BY BCLTDPID,CERTNO,PARTY_CODE

SELECT * FROM #CC WHERE QTY1 <>'0'  ORDER BY BCLTDPID,PARTY_CODE,CERTNO


--REPLEDGED
*/
/*

SELECT PROCESS_DATE,PARTY_CODE,SCRIP_CD,SERIES,ISIN,QTY,PLDQTY,REPLDQTY,CL_RATE,HAIRCUT 
FROM TBL_NONCASH_SUMMARY WITH (NOLOCK)  WHERE PROCESS_DATE = 'JAN 31 2024'  AND PARTY_CODE = 'A160820'
AND ISIN = 'INE201A01024'
ORDER BY 2


SELECT TOP 10  * FROM TBL_CCCM_SCRIP_DATA  WITH (NOLOCK) WHERE RECORDDATE = 'JAN 31 2024'  AND Client_Code = 'A160820'
AND ISIN = 'INE201A01024'

SELECT TOP 10 * FROM TBL_CC_HAIRCUT  WHERE SYSDATE = 'JAN 31 2024'

SP_HELPTEXT PROC_CC_HAIRCUT_UPLOAD

SP_HELPTEXT PROC_CCCM_SCRIP_UPLOAD

SP_HELPTEXT BULK_SEC_PLD_NCCL 


*/
 
 
SELECT  PROCESS_DATE,PARTY_CODE,  SUM((QTY *CL_RATE) - (QTY *CL_RATE *HAIRCUT/100)) AS QTYFULLVAL1,
SUM((PLDQTY *CL_RATE) - (PLDQTY *CL_RATE *HAIRCUT/100)) AS PLEDGEFULLVAL1,
SUM(((QTY *CL_RATE) - (QTY *CL_RATE *HAIRCUT/100)) - ((PLDQTY *CL_RATE) - (PLDQTY *CL_RATE *HAIRCUT/100))) AS PLEDGEINHAND1 INTO #TBL_NONCASH_REPORT
FROM MSAJAG.DBO.TBL_NONCASH_REPORT WITH (NOLOCK) WHERE PROCESS_DATE = @MDATE AND  BCLTDPID = '1203320030135814' GROUP BY PROCESS_DATE,PARTY_CODE
 
SELECT CLIENT_CODE,SUM(NET_EFF_VALUE) AS FINALVALUE ,SUM(NET_VALUE) AS TOTALVALUE,EXCESSTOTALVALUE = SUM(NET_VALUE) - SUM(NET_EFF_VALUE)
INTO #TBL_CCCM_SCRIP_DATA
FROM MSAJAG.DBO.TBL_CCCM_SCRIP_DATA  WITH (NOLOCK) WHERE RECORDDATE = @MDATE 
GROUP BY CLIENT_CODE


ALTER TABLE #CLIENTDATA ADD PLEDGEFULLVAL1 NUMERIC(18,2) ,  REPLEDGEFULLVAL1 NUMERIC(18,2)   , TOTALVALUE_CC NUMERIC(18,2)  , EXCESSTOTALVALUE_CC NUMERIC(18,2) 

UPDATE #CLIENTDATA SET PLEDGEFULLVAL1 = 0 , REPLEDGEFULLVAL1 = 0 , TOTALVALUE_CC = 0 ,EXCESSTOTALVALUE_CC = 0

UPDATE A SET PLEDGEFULLVAL1 = QTYFULLVAL1 , REPLEDGEFULLVAL1 = B.PLEDGEFULLVAL1  FROM #CLIENTDATA A , #TBL_NONCASH_REPORT B 
WHERE A.PARTY_CODE = B.PARTY_CODE


UPDATE A SET TOTALVALUE_CC = TOTALVALUE , EXCESSTOTALVALUE_CC = EXCESSTOTALVALUE  FROM #CLIENTDATA A , #TBL_CCCM_SCRIP_DATA B 
WHERE A.PARTY_CODE = B.CLIENT_CODE


ALTER TABLE #TBL_COMBINE_REPORTING_PEAK1 ADD PLEDGEFULLVAL1 NUMERIC(18,2) ,  REPLEDGEFULLVAL1 NUMERIC(18,2)   , TOTALVALUE_CC NUMERIC(18,2)  , EXCESSTOTALVALUE_CC NUMERIC(18,2) 

UPDATE #TBL_COMBINE_REPORTING_PEAK1 SET PLEDGEFULLVAL1 = 0 , REPLEDGEFULLVAL1 = 0 , TOTALVALUE_CC = 0 ,EXCESSTOTALVALUE_CC = 0

UPDATE A SET PLEDGEFULLVAL1 = QTYFULLVAL1 , REPLEDGEFULLVAL1 = B.PLEDGEFULLVAL1  FROM #TBL_COMBINE_REPORTING_PEAK1 A , #TBL_NONCASH_REPORT B 
WHERE A.PARTY_CODE = B.PARTY_CODE


UPDATE A SET TOTALVALUE_CC = TOTALVALUE , EXCESSTOTALVALUE_CC = EXCESSTOTALVALUE  FROM #TBL_COMBINE_REPORTING_PEAK1 A , #TBL_CCCM_SCRIP_DATA B 
WHERE A.PARTY_CODE = B.CLIENT_CODE


  
SELECT A.PARTY_CODE,MAX_MARGIN,CONVERT(NUMERIC(18,2),EPIAMOUNT) AS EPIAMOUNT,VTOTAL AS MAX_VDT,ETOTAL AS MAX_EDT,
[Sum of HC Mismatch] =  REPLEDGEFULLVAL1 - TOTALVALUE_CC,
[Sum of Excess Qty2] = EXCESSTOTALVALUE_CC,
[Max of Diff-VDT-EDT] = VTOTAL-ETOTAL,
[Sum of RepledgeValue] = REPLEDGEFULLVAL1,
[Sum of StockINHand Value] = PLEDGEFULLVAL1 - REPLEDGEFULLVAL1,
[Margin/2] = MAX_MARGIN/2,
[Cash Shortfall] = CASE WHEN (MAX_MARGIN/2) = 0 THEN 0
						WHEN TDAY_LEDGER < 0 THEN (MAX_MARGIN/2)
				        WHEN ((MAX_MARGIN/2) - TDAY_LEDGER) > 0  THEN  ((MAX_MARGIN/2) - TDAY_LEDGER) 
						ELSE 0 END,
[Non-cash shortfall] = CASE WHEN 
								((REPLEDGEFULLVAL1 +(CASE WHEN ETOTAL < 0 THEN 0 ELSE ETOTAL END)) - MAX_MARGIN) >= 0 THEN 0 ELSE 
								((REPLEDGEFULLVAL1 +(CASE WHEN ETOTAL < 0 THEN 0 ELSE ETOTAL END)) - MAX_MARGIN) END,
[Cash Shortfall for 50:50] = CONVERT(NUMERIC(18,2),0),	[Sum of HC Mismatch-used] = CONVERT(NUMERIC(18,2),0),	[Sum of Excess Qty21] = CONVERT(NUMERIC(18,2),0),
CONVERT(NUMERIC(18,2),0) AS	EPN,[Max of Diff-VDT-EDT1] = CONVERT(NUMERIC(18,2),0) ,	[Sum of StockINHand Value1] = CONVERT(NUMERIC(18,2),0),
[Cash Shortfall for 50:501] = CONVERT(NUMERIC(18,2),0),	[Funds] = CONVERT(NUMERIC(18,2),0),
PLEDGEFULLVAL1 , REPLEDGEFULLVAL1 , TOTALVALUE_CC ,EXCESSTOTALVALUE_CC,
[FUNDS / MAX_MARGIN %] =  CONVERT(NUMERIC(18,0),0),[90 %] = CONVERT(NUMERIC(18,0),90) ,[DIFF %] = CONVERT(NUMERIC(18,0),0),[DIFF AMT] = CONVERT(NUMERIC(18,2),0)
INTO #CHECK_EOD
FROM #CLIENTDATA A , #TEMP_TOTAL C 
WHERE    A.PARTY_CODE = C.CLTCODE -- AND A.PARTY_CODE IN ('A100079','A1000824')
ORDER BY 1


SELECT A.PARTY_CODE,MAX_MARGIN,CONVERT(NUMERIC(18,2),EPIAMOUNT) AS EPIAMOUNT,VTOTAL AS MAX_VDT,ETOTAL AS MAX_EDT,
[Sum of HC Mismatch] =  REPLEDGEFULLVAL1 - TOTALVALUE_CC,
[Sum of Excess Qty2] = EXCESSTOTALVALUE_CC,
[Max of Diff-VDT-EDT] = VTOTAL-ETOTAL,
[Sum of RepledgeValue] = REPLEDGEFULLVAL1,
[Sum of StockINHand Value] = PLEDGEFULLVAL1 - REPLEDGEFULLVAL1,
[Margin/2] = MAX_MARGIN/2,
[Cash Shortfall] = CASE WHEN (MAX_MARGIN/2) = 0 THEN 0
						WHEN TDAY_LEDGER < 0 THEN (MAX_MARGIN/2)
				        WHEN ((MAX_MARGIN/2) - TDAY_LEDGER) > 0  THEN  ((MAX_MARGIN/2) - TDAY_LEDGER) 
						ELSE 0 END,
[Non-cash shortfall] = CASE WHEN 
								((REPLEDGEFULLVAL1 +(CASE WHEN ETOTAL < 0 THEN 0 ELSE ETOTAL END)) - MAX_MARGIN) >= 0 THEN 0 ELSE 
								((REPLEDGEFULLVAL1 +(CASE WHEN ETOTAL < 0 THEN 0 ELSE ETOTAL END)) - MAX_MARGIN) END,
[Cash Shortfall for 50:50] = CONVERT(NUMERIC(18,2),0),	[Sum of HC Mismatch-used] = CONVERT(NUMERIC(18,2),0),	[Sum of Excess Qty21] = CONVERT(NUMERIC(18,2),0),
CONVERT(NUMERIC(18,2),0) AS	EPN,[Max of Diff-VDT-EDT1] = CONVERT(NUMERIC(18,2),0) ,	[Sum of StockINHand Value1] = CONVERT(NUMERIC(18,2),0),
[Cash Shortfall for 50:501] = CONVERT(NUMERIC(18,2),0),	[Funds] = CONVERT(NUMERIC(18,2),0),
PLEDGEFULLVAL1 , REPLEDGEFULLVAL1 , TOTALVALUE_CC ,EXCESSTOTALVALUE_CC ,
[FUNDS / MAX_MARGIN %] =  CONVERT(NUMERIC(18,0),0),[90 %] = CONVERT(NUMERIC(18,0),90) ,[DIFF %] = CONVERT(NUMERIC(18,0),0),[DIFF AMT] = CONVERT(NUMERIC(18,2),0)
INTO #CHECK_PEAK
FROM #TBL_COMBINE_REPORTING_PEAK1 A , #TEMP_TOTAL_PEAK C 
WHERE    A.PARTY_CODE = C.CLTCODE -- AND A.PARTY_CODE IN ('A100079','A1000824')
ORDER BY 1
 
UPDATE #CHECK_EOD SET [Cash Shortfall for 50:50] = ABS(CASE WHEN ([Cash Shortfall] + [Non-cash shortfall]) > 0 THEN 0 ELSE ([Cash Shortfall] + [Non-cash shortfall]) END)+[Cash Shortfall]

UPDATE #CHECK_EOD SET [Cash Shortfall for 50:501] = MinValue FROM (SELECT PARTY_CODE,(SELECT MIN(A) FROM (VALUES ([Cash Shortfall for 50:50]),(MAX_MARGIN)) AS UpdateScore(A)) AS MinValue  FROM #CHECK_EOD) AS A  WHERE A.PARTY_CODE = #CHECK_EOD.PARTY_CODE

UPDATE #CHECK_EOD SET [Sum of HC Mismatch-used] = MinValue FROM (SELECT PARTY_CODE,(SELECT MIN(A) FROM (VALUES (MAX_MARGIN-[Cash Shortfall for 50:50]),([Sum of HC Mismatch])) AS UpdateScore(A)) AS MinValue   FROM #CHECK_EOD) AS A  WHERE A.PARTY_CODE = #CHECK_EOD.PARTY_CODE

UPDATE #CHECK_EOD SET [Sum of Excess Qty21] = MinValue FROM (SELECT PARTY_CODE,(SELECT MIN(A) FROM (VALUES (MAX_MARGIN-[Cash Shortfall for 50:501]-[Sum of HC Mismatch-used]),([Sum of Excess Qty2])) AS UpdateScore(A)) AS MinValue FROM #CHECK_EOD) AS A  WHERE A.PARTY_CODE = #CHECK_EOD.PARTY_CODE

UPDATE #CHECK_EOD SET EPN = MinValue FROM (SELECT PARTY_CODE,(SELECT MIN(A) FROM (VALUES (MAX_MARGIN-[Cash Shortfall for 50:501]-[Sum of HC Mismatch-used]-[Sum of Excess Qty21]),(EPIAMOUNT*80/100)) AS UpdateScore(A)) AS MinValue FROM #CHECK_EOD) AS A  WHERE A.PARTY_CODE = #CHECK_EOD.PARTY_CODE

UPDATE #CHECK_EOD SET [Max of Diff-VDT-EDT1] = MinValue FROM (SELECT PARTY_CODE,(SELECT MIN(A) FROM (VALUES (MAX_MARGIN-[Cash Shortfall for 50:501]-[Sum of HC Mismatch-used]-[Sum of Excess Qty21]-EPN),([Max of Diff-VDT-EDT])) AS UpdateScore(A)) AS MinValue FROM #CHECK_EOD) AS A  WHERE A.PARTY_CODE = #CHECK_EOD.PARTY_CODE

UPDATE #CHECK_EOD SET [Sum of StockINHand Value1] =  MinValue FROM (SELECT PARTY_CODE,(SELECT MIN(A) FROM (VALUES (MAX_MARGIN-[Cash Shortfall for 50:501]-[Sum of HC Mismatch-used]-[Sum of Excess Qty21]-EPN-[Max of Diff-VDT-EDT1]),([Sum of StockINHand Value])) AS UpdateScore(A)) AS MinValue FROM #CHECK_EOD) AS A  WHERE A.PARTY_CODE = #CHECK_EOD.PARTY_CODE

UPDATE #CHECK_EOD SET [Funds] =  CASE WHEN (EPIAMOUNT + MAX_EDT + [Sum of RepledgeValue] + [Sum of StockINHand Value]) < 0 THEN 0 ELSE (EPIAMOUNT + MAX_EDT + [Sum of RepledgeValue] + [Sum of StockINHand Value]) END
   
UPDATE #CHECK_EOD SET [FUNDS / MAX_MARGIN %] =  CASE WHEN  [Funds] <> 0  THEN (MAX_MARGIN / [Funds])*100 ELSE 0 END

UPDATE #CHECK_EOD SET [DIFF %] =  CASE WHEN [FUNDS / MAX_MARGIN %] - [90 %] < 0 THEN 0 ELSE  [FUNDS / MAX_MARGIN %] - [90 %] END

UPDATE #CHECK_EOD SET [DIFF AMT] = CASE WHEN ([FUNDS / MAX_MARGIN %]) < 90 THEN 0 ELSE ([Funds]*[DIFF %]) +( [Funds]-([Funds]*[90 %])) END
  
UPDATE #CHECK_PEAK SET [Cash Shortfall for 50:50] = ABS(CASE WHEN ([Cash Shortfall] + [Non-cash shortfall]) > 0 THEN 0 ELSE ([Cash Shortfall] + [Non-cash shortfall]) END)+[Cash Shortfall]

UPDATE #CHECK_PEAK SET [Cash Shortfall for 50:501] = MinValue FROM (SELECT PARTY_CODE,(SELECT MIN(A) FROM (VALUES ([Cash Shortfall for 50:50]),(MAX_MARGIN)) AS UpdateScore(A)) AS MinValue  FROM #CHECK_PEAK) AS A  WHERE A.PARTY_CODE = #CHECK_PEAK.PARTY_CODE

UPDATE #CHECK_PEAK SET [Sum of HC Mismatch-used] = MinValue FROM (SELECT PARTY_CODE,(SELECT MIN(A) FROM (VALUES (MAX_MARGIN-[Cash Shortfall for 50:50]),([Sum of HC Mismatch])) AS UpdateScore(A)) AS MinValue   FROM #CHECK_PEAK) AS A  WHERE A.PARTY_CODE = #CHECK_PEAK.PARTY_CODE

UPDATE #CHECK_PEAK SET [Sum of Excess Qty21] = MinValue FROM (SELECT PARTY_CODE,(SELECT MIN(A) FROM (VALUES (MAX_MARGIN-[Cash Shortfall for 50:501]-[Sum of HC Mismatch-used]),([Sum of Excess Qty2])) AS UpdateScore(A)) AS MinValue FROM #CHECK_PEAK) AS A  WHERE A.PARTY_CODE = #CHECK_PEAK.PARTY_CODE

UPDATE #CHECK_PEAK SET EPN = MinValue FROM (SELECT PARTY_CODE,(SELECT MIN(A) FROM (VALUES (MAX_MARGIN-[Cash Shortfall for 50:501]-[Sum of HC Mismatch-used]-[Sum of Excess Qty21]),(EPIAMOUNT*80/100)) AS UpdateScore(A)) AS MinValue FROM #CHECK_PEAK) AS A  WHERE A.PARTY_CODE = #CHECK_PEAK.PARTY_CODE

UPDATE #CHECK_PEAK SET [Max of Diff-VDT-EDT1] = MinValue FROM (SELECT PARTY_CODE,(SELECT MIN(A) FROM (VALUES (MAX_MARGIN-[Cash Shortfall for 50:501]-[Sum of HC Mismatch-used]-[Sum of Excess Qty21]-EPN),([Max of Diff-VDT-EDT])) AS UpdateScore(A)) AS MinValue FROM #CHECK_PEAK) AS A  WHERE A.PARTY_CODE = #CHECK_PEAK.PARTY_CODE

UPDATE #CHECK_PEAK SET [Sum of StockINHand Value1] =  MinValue FROM (SELECT PARTY_CODE,(SELECT MIN(A) FROM (VALUES (MAX_MARGIN-[Cash Shortfall for 50:501]-[Sum of HC Mismatch-used]-[Sum of Excess Qty21]-EPN-[Max of Diff-VDT-EDT1]),([Sum of StockINHand Value])) AS UpdateScore(A)) AS MinValue FROM #CHECK_PEAK) AS A  WHERE A.PARTY_CODE = #CHECK_PEAK.PARTY_CODE

UPDATE #CHECK_PEAK SET [Funds] =  CASE WHEN (EPIAMOUNT + MAX_EDT + [Sum of RepledgeValue] + [Sum of StockINHand Value]) < 0 THEN 0 ELSE (EPIAMOUNT + MAX_EDT + [Sum of RepledgeValue] + [Sum of StockINHand Value]) END

UPDATE #CHECK_PEAK SET [FUNDS / MAX_MARGIN %] =    CASE WHEN  [Funds] <> 0  THEN (MAX_MARGIN / [Funds])*100 ELSE 0 END

UPDATE #CHECK_PEAK SET [DIFF %] =  CASE WHEN [FUNDS / MAX_MARGIN %] - [90 %] < 0 THEN 0 ELSE  [FUNDS / MAX_MARGIN %] - [90 %] END

UPDATE #CHECK_PEAK SET [DIFF AMT] = CASE WHEN ([FUNDS / MAX_MARGIN %]) < 90 THEN 0 ELSE ([Funds]*[DIFF %]) +( [Funds]-([Funds]*[90 %])) END
 
DELETE INHOUSE.DBO.CAPITALREQUIREMENT_DETAIL_EOD WHERE MDATE = @MDATE
DELETE INHOUSE.DBO.CAPITALREQUIREMENT_DETAIL_PEAK WHERE MDATE = @MDATE

INSERT INTO INHOUSE.DBO.CAPITALREQUIREMENT_DETAIL_EOD SELECT @MDATE AS MDATE,*  FROM #CHECK_EOD ORDER BY 1 
INSERT INTO INHOUSE.DBO.CAPITALREQUIREMENT_DETAIL_PEAK SELECT @MDATE AS MDATE,*  FROM #CHECK_PEAK ORDER BY 1 


DROP TABLE #CHECK_EOD
DROP TABLE #CHECK_PEAK
DROP TABLE #TBL_COMBINE_REPORTING_EOD
DROP TABLE #TEMP_TOTAL
DROP TABLE #CLIENTDATA
DROP TABLE #TBL_COMBINE_REPORTING_PEAK1
DROP TABLE #TBL_COMBINE_REPORTING_PEAK
DROP TABLE #TEMP_TOTAL_PEAK
DROP TABLE #TBL_NONCASH_REPORT
DROP TABLE #TBL_CCCM_SCRIP_DATA

FINALSUMM:

DELETE CAPITALREQUIREMENT_SUMM_PEAK WHERE MDATE = @MDATE

INSERT INTO CAPITALREQUIREMENT_SUMM_PEAK
SELECT MDATE,SUM(MAX_MARGIN)/10000000 AS [Margin],SUM([Cash Shortfall for 50:501])/10000000 AS [Cash Shortfall for 50:50]
,SUM([Sum of HC Mismatch-used])/10000000 AS [Sum of HC Mismatch] ,SUM([Sum of Excess Qty21])/10000000 AS [Sum of Excess Qty2],SUM(EPN)/10000000 AS [Max of EPN],
SUM([Max of Diff-VDT-EDT1])/10000000 AS [Diff- EDT & VDT],SUM([Sum of StockINHand Value1])/10000000 AS [Sum of StockINHand Value],[Intraday Pledge] = 0,[Allocation in Other CC]= 0,[Funds Pay in] = 0,
SUM(EXCESSTOTALVALUE_CC)/10000000 AS [RRM],[Buffer for RRM]  = 0,[Total] = 0,
[Exch Pay in] = 0,
[Creditors Payout] = 0, 
[Total Required] = 0,
[BG] = 0,
[CASH] = 0,
[Intraday] = 0,
[Margin for intraday to deposit with bank] = 0,
[Bill adjustment] = 0,
[Total Capital] = 0,[No. of Orders]  = 0
FROM CAPITALREQUIREMENT_DETAIL_PEAK WHERE MDATE = @MDATE
GROUP BY MDATE


DELETE CAPITALREQUIREMENT_SUMM_EOD WHERE MDATE = @MDATE

INSERT INTO CAPITALREQUIREMENT_SUMM_EOD
SELECT MDATE,SUM(MAX_MARGIN)/10000000 AS [Margin],SUM([Cash Shortfall for 50:501])/10000000 AS [Cash Shortfall for 50:50]
,SUM([Sum of HC Mismatch-used])/10000000 AS [Sum of HC Mismatch],SUM([Sum of Excess Qty21])/10000000 AS [Sum of Excess Qty2],SUM(EPN)/10000000 AS [Max of EPN],
SUM([Max of Diff-VDT-EDT1])/10000000 AS [Diff- EDT & VDT],SUM([Sum of StockINHand Value1])/10000000 AS [Sum of StockINHand Value],[Intraday Pledge] = 0,[Allocation in Other CC]= 0,[Funds Pay in] = 0,
SUM(EXCESSTOTALVALUE_CC)/10000000 AS [RRM],[Buffer for RRM]  = 0,[Total] = 0,
[Exch Pay in] = 0,
[Creditors Payout] = 0, 
[Total Required] = 0,
[BG] = 0,
[CASH] = 0,
[Intraday] = 0,
[Margin for intraday to deposit with bank] = 0,
[Bill adjustment] = 0,
[Total Capital] = 0,[No. of Orders]  = 0
FROM CAPITALREQUIREMENT_DETAIL_EOD WHERE MDATE = @MDATE
GROUP BY MDATE

  
SELECT EXCHANGE,SEGMENT,CONVERT(VARCHAR(11),SAUDA_DATE,109) AS SAUDA_DATE , COUNT(DISTINCT ORDER_NO) AS ORDER_NO  INTO #TEMPDETAIL 
FROM MSAJAG.DBO.COMMON_CONTRACT_DATA WITH (NOLOCK)    
WHERE SAUDA_DATE BETWEEN @MDATE AND @MDATE + ' 23:59'  AND QTY <> 0  AND ORDER_NO <> '' AND SETT_TYPE NOT IN ('A','AD','X','AF')
GROUP BY EXCHANGE,SEGMENT,CONVERT(VARCHAR(11),SAUDA_DATE,109)

IF (SELECT COUNT(1) FROM #TEMPDETAIL) = 0 
BEGIN 
INSERT INTO #TEMPDETAIL 
SELECT EXCHANGE,SEGMENT,CONVERT(VARCHAR(11),SAUDA_DATE,109) AS SAUDA_DATE ,ORDER_NO = COUNT(DISTINCT ORDER_NO) 
FROM MSAJAG.DBO.COMMON_CONTRACT_DATA_HISTORY WITH (NOLOCK)    
WHERE SAUDA_DATE BETWEEN @MDATE AND @MDATE + ' 23:59'  AND QTY <> 0  AND ORDER_NO <> '' AND SETT_TYPE NOT IN ('A','AD','X','AF')
GROUP BY EXCHANGE,SEGMENT,CONVERT(VARCHAR(11),SAUDA_DATE,109)
END

INSERT INTO #TEMPDETAIL 
SELECT EXCHANGE,SEGMENT,CONVERT(VARCHAR(11),SAUDA_DATE,109) AS SAUDA_DATE, COUNT(DISTINCT ORDER_NO) AS ORDER_NO 
FROM ANGELCOMMODITY.MCDX.DBO.COMMON_CONTRACT_DATA WITH (NOLOCK)      
WHERE SAUDA_DATE BETWEEN @MDATE AND @MDATE + ' 23:59'  AND QTY <> 0  AND ORDER_NO <> '' 
GROUP BY EXCHANGE,SEGMENT,CONVERT(VARCHAR(11),SAUDA_DATE,109)  

SELECT SAUDA_DATE,SUM(ORDER_NO) AS ORDER_NO INTO #TEMPDETAIL1 FROM #TEMPDETAIL GROUP BY SAUDA_DATE

UPDATE CAPITALREQUIREMENT_SUMM_PEAK SET [No. of Orders] = ORDER_NO FROM #TEMPDETAIL1 WHERE MDATE  = SAUDA_DATE
UPDATE CAPITALREQUIREMENT_SUMM_EOD SET [No. of Orders] = ORDER_NO FROM #TEMPDETAIL1 WHERE MDATE  = SAUDA_DATE


DROP TABLE #TEMPDETAIL1
DROP TABLE #TEMPDETAIL

GO
