-- Object: PROCEDURE dbo.NRI_AUCTION_ANG_EMAIL_ANG
-- Server: 10.253.33.91 | DB: INHOUSE
--------------------------------------------------


CREATE PROC NRI_AUCTION_ANG_EMAIL_ANG 

AS

DECLARE @SAUDA_DATE DATETIME

SET @SAUDA_DATE = GETDATE()
   
SELECT DISTINCT CL_CODE,SUB_BROKER INTO #CLIENTDATA FROM (  
SELECT DISTINCT CL_CODE,SUB_BROKER FROM MSAJAG.DBO.CLIENT_DETAILS WITH (NOLOCK) WHERE PARTY_CODE BETWEEN 'ZR001' AND 'ZRR999'  
UNION ALL  
SELECT DISTINCT CL_CODE,SUB_BROKER FROM MSAJAG.DBO.CLIENT_DETAILS WITH (NOLOCK) WHERE SUB_BROKER IN ('BHKWT','BH') ) AS A  
  
SELECT DISTINCT CONVERT(VARCHAR(11),SAUDA_DATE,105) AS SAUDA_DATE,EXCHANGE='NSE',SETT_TYPE,SETT_NO,PARTY_CODE,SUB_BROKER,CONTRACTNO,AUCTIONPART  
INTO #CONTRACTDATA  
FROM MSAJAG.DBO.SETTLEMENT S WITH (NOLOCK) ,#CLIENTDATA WHERE   PARTY_CODE = CL_CODE AND SAUDA_DATE BETWEEN @SAUDA_DATE - 7 AND @SAUDA_DATE + ' 23:59'  AND SETT_TYPE IN ('A','X')
AND AUCTIONPART LIKE 'F%' 

INSERT INTO #CONTRACTDATA  
SELECT DISTINCT CONVERT(VARCHAR(11),SAUDA_DATE,105) AS SAUDA_DATE,EXCHANGE='NSE',SETT_TYPE,SETT_NO,PARTY_CODE,SUB_BROKER,CONTRACTNO,AUCTIONPART 
FROM MSAJAG.DBO.HISTORY S WITH (NOLOCK) ,#CLIENTDATA WHERE   PARTY_CODE = CL_CODE AND SAUDA_DATE BETWEEN @SAUDA_DATE - 7 AND @SAUDA_DATE + ' 23:59'  AND SETT_TYPE IN ('A','X')
AND AUCTIONPART LIKE 'F%' 
 
--SELECT DISTINCT CLTCODE,BILLPOSTED1 = 'Y' INTO #BILLPOST FROM ACCOUNT.DBO.LEDGER WITH (NOLOCK) , #CLIENTDATA WHERE VDT BETWEEN @SAUDA_DATE - 70 AND @SAUDA_DATE + ' 23:59'  
--AND CLTCODE = CL_CODE  AND VTYP = 15  


--SELECT  DISTINCT CONVERT(VARCHAR(11),SAUDA_DATE,105) AS SAUDA_DATE,SEGMENT,PARTY_CODE,CONTRACTNO,INHOUSE1 = 'Y' INTO #TBL_NRITRADE_REPORTS
--FROM [196.1.115.132].RISK.DBO.TBL_NRITRADE_REPORTS WITH (NOLOCK) WHERE SAUDA_DATE BETWEEN @SAUDA_DATE AND @SAUDA_DATE + ' 23:59' 
  
--UPDATE #CONTRACTDATA SET BILLPOSTED = BILLPOSTED1 FROM #BILLPOST WHERE CLTCODE = PARTY_CODE  


--UPDATE #CONTRACTDATA SET INHOUSE = INHOUSE1 FROM #TBL_NRITRADE_REPORTS WHERE #CONTRACTDATA.PARTY_CODE = #TBL_NRITRADE_REPORTS.PARTY_CODE AND EXCHANGE = SEGMENT AND 
--#CONTRACTDATA.CONTRACTNO = #TBL_NRITRADE_REPORTS.CONTRACTNO 
   
DECLARE @EMAILS VARCHAR(4000),@BODYCONTENT VARCHAR(MAX),@TBLE VARCHAR(MAX),@SUB VARCHAR(4000),@SUB1 VARCHAR(4000),@XML VARCHAR(MAX)       

SET @SUB = 'NRI Auction Contracts for period : ' + CONVERT(VARCHAR(11),@SAUDA_DATE-7,105) + ' to ' +CONVERT(VARCHAR(11),@SAUDA_DATE,105)  
  
SET @SUB1 = 'NRI Auction Contracts for period : ' + CONVERT(VARCHAR(11),@SAUDA_DATE-7,105) + ' to ' +CONVERT(VARCHAR(11),@SAUDA_DATE,105) 
           
    
SET @XML =  CAST((SELECT [td/@align]='center',[td/@width]='10%',td = SAUDA_DATE,'',          
    [td/@align]='center',[td/@width]='10%',td = EXCHANGE ,'',          
    [td/@align]='center',[td/@width]='10%',td =SETT_TYPE,'', 
	[td/@align]='center',[td/@width]='10%',td =SETT_NO,'', 
	[td/@align]='center',[td/@width]='10%',td =PARTY_CODE,'',
	[td/@align]='center',[td/@width]='10%',td = AUCTIONPART,'' 
FROM #CONTRACTDATA 
ORDER BY EXCHANGE,SETT_TYPE,SUB_BROKER,PARTY_CODE   ASC FOR XML PATH('TR'), ELEMENTS ) AS VARCHAR(MAX))          

    
SET @TBLE ='<HEAD><STYLE>BODY>TABLE>TBODY>TR>TD:NTH-CHILD(1)BODY>TABLE>TBODY>TR>TD:NTH-CHILD(2)BODY>TABLE>TBODY > TR > TD:NTH-CHILD(3)BODY>TABLE>TBODY>TR>TD:NTH-CHILD(4)BODY>TABLE>TBODY>TR>TD:NTH-CHILD(5)BODY>TABLE>TBODY>TR>TD:NTH-CHILD(6)</STYLE> </HEAD> <TABLE BORDER = 1;> <THEAD> <TR STYLE="BACKGROUND-COLOR: #4F6E9C; COLOR: WHITE; FONT-SIZE: 13PX"><TH> SAUDA_DATE </TH> <TH> EXCHANGE </TH><TH> SETT_TYPE </TH><TH> SETT_NO </TH><TH> PARTY_CODE </TH><TH> AUCTIONPART </TH> </TR> </THEAD><TBODY STYLE="FONT-SIZE: 13PX;">'              
          
SET @TBLE = @TBLE + @XML +'</TBODY></TABLE></BODY></HTML>'          
          
SELECT @BODYCONTENT = '<HTML><P><SPAN STYLE="COLOR: RGB(0, 0, 128); FONT-FAMILY: VERDANA; FONT-SIZE: SMALL; FONT-STYLE: NORMAL; FONT-VARIANT-LIGATURES: NORMAL; FONT-VARIANT-CAPS: NORMAL; FONT-WEIGHT: 400; LETTER-SPACING: NORMAL; ORPHANS: 2; TEXT-ALIGN: START; TEXT-INDENT: 0PX; TEXT-TRANSFORM: NONE; WHITE-SPACE: NORMAL; WIDOWS: 2; WORD-SPACING: 0PX; -WEBKIT-TEXT-STROKE-WIDTH: 0PX; BACKGROUND-COLOR: RGB(255, 255, 255); TEXT-DECORATION-THICKNESS: INITIAL; TEXT-DECORATION-STYLE: INITIAL; TEXT-DECORATION-COLOR: INITIAL; DISPLAY: INLINE !IMPORTANT; FLOAT: NONE;">Dear All,</SPAN></P><P><SPAN STYLE="COLOR: RGB(0, 0, 128); FONT-FAMILY: VERDANA; FONT-SIZE: SMALL; FONT-STYLE: NORMAL; FONT-VARIANT-LIGATURES: NORMAL; FONT-VARIANT-CAPS: NORMAL; FONT-WEIGHT: 400; LETTER-SPACING: NORMAL; ORPHANS: 2; TEXT-ALIGN: START; TEXT-INDENT: 0PX; TEXT-TRANSFORM: NONE; WHITE-SPACE: NORMAL; WIDOWS: 2; WORD-SPACING: 0PX; -WEBKIT-TEXT-STROKE-WIDTH: 0PX; BACKGROUND-COLOR: RGB(255, 255, 255); TEXT-DECORATION-THICKNESS: INITIAL; TEXT-DECORATION-STYLE: INITIAL; TEXT-DECORATION-COLOR: INITIAL; DISPLAY: INLINE !IMPORTANT; FLOAT: NONE;">'+ @SUB1 + '</P>'+@TBLE+''          

EXEC MSDB.DBO.SP_SEND_DBMAIL           
@PROFILE_NAME='BO SUPPORT',           
@RECIPIENTS='bhavika.tiwari@angelbroking.com;dattu.mane@angelbroking.com',           
@blind_copy_recipients='ananthanarayanan.b@angelbroking.com',          
@SUBJECT=@SUB,          
@BODY=@BODYCONTENT,          
@IMPORTANCE = 'HIGH',          
@BODY_FORMAT ='HTML' 

DROP TABLE #CLIENTDATA  
DROP TABLE #CONTRACTDATA  
--DROP TABLE #BILLPOST
--DROP TABLE #TBL_NRITRADE_REPORTS

GO
