-- Object: PROCEDURE dbo.SEBI_NetValues
-- Server: 10.253.33.91 | DB: INHOUSE
--------------------------------------------------

--SEBI_NetValues  'NOV  9 2023'
CREATE proc SEBI_NetValues(@SAUDA_DATE VARCHAR(11))
as
begin
--DECLARE @SAUDA_DATE VARCHAR(11) = 'NOV  9 2023'

SELECT CONVERT(VARCHAR(30),CLTCODE)AS CLTCODE,
NARRATION,SUM(CASE WHEN DRCR = 'D' THEN -VAMT ELSE VAMT END) AS VAMT,VDT,EDT, CONVERT(VARCHAR(30),EXCHANGE)AS EXCHANGE INTO #LEDGERGL
FROM ACCOUNT.DBO.LEDGER_ALL WITH (NOLOCK) WHERE CLTCODE  IN ('99985','99885','99897','99880','99785' ) 
AND EXCHANGE NOT IN ('NSE','BSE')
AND VDT BETWEEN @SAUDA_DATE AND @SAUDA_DATE + ' 23:59:59' AND VTYP = 15
GROUP BY VDT,EDT,EXCHANGE,CLTCODE,NARRATION

INSERT INTO #LEDGERGL
SELECT CONVERT(VARCHAR(30),CLTCODE)AS CLTCODE,
NARRATION,SUM(CASE WHEN DRCR = 'D' THEN -VAMT ELSE VAMT END) AS VAMT,VDT,EDT, CONVERT(VARCHAR(30),EXCHANGE)AS EXCHANGE 
FROM ACCOUNT.DBO.LEDGER_ALL  WITH (NOLOCK) WHERE CLTCODE  IN ('99985','99885','99897','99880','99785') 
AND EXCHANGE IN ('NSE','BSE')
AND VDT <= @SAUDA_DATE AND  EDT > @SAUDA_DATE
AND VTYP = 15
GROUP BY VDT,EDT,EXCHANGE,CLTCODE,NARRATION

SELECT MARGINDATE,EXCH = 'NSECM',SUM(TOTAL_MARGIN) AS TOTAL_MARGIN  INTO #TOTAL_MARGIN_ALL
FROM MSAJAG.DBO.TBL_CMMARGIN WITH (NOLOCK) WHERE MARGINDATE BETWEEN @SAUDA_DATE AND @SAUDA_DATE + ' 23:59'
GROUP BY MARGINDATE


INSERT INTO #TOTAL_MARGIN_ALL
SELECT MARGINDATE,EXCH = 'NCDEX',SUM(INITIALMARGIN+MTMMARGIN) AS TOTAL_MARGIN FROM ANGELCOMMODITY.NCDX.DBO.TBL_CLIENTMARGIN  WITH (NOLOCK)
 WHERE MARGINDATE BETWEEN @SAUDA_DATE AND @SAUDA_DATE + ' 23:59' GROUP BY MARGINDATE

INSERT INTO #TOTAL_MARGIN_ALL
SELECT MARGINDATE,EXCH = 'NSEFO',SUM(INITIALMARGIN+MTMMARGIN) AS TOTAL_MARGIN 
FROM ANGELFO.NSEFO.DBO.TBL_CLIENTMARGIN  WITH (NOLOCK) WHERE MARGINDATE BETWEEN @SAUDA_DATE AND @SAUDA_DATE + ' 23:59'
GROUP BY MARGINDATE

INSERT INTO #TOTAL_MARGIN_ALL
SELECT  MARGINDATE,EXCH = 'NSECD',SUM(INITIALMARGIN+MTMMARGIN) AS TOTAL_MARGIN 
FROM ANGELFO.NSECURFO.DBO.TBL_CLIENTMARGIN  WITH (NOLOCK)  WHERE MARGINDATE BETWEEN @SAUDA_DATE AND @SAUDA_DATE + ' 23:59'
GROUP BY MARGINDATE

INSERT INTO #TOTAL_MARGIN_ALL
SELECT   MARGINDATE,EXCH = 'MCX',SUM(INITIALMARGIN+MTMMARGIN) AS TOTAL_MARGIN 
FROM ANGELCOMMODITY.MCDX.DBO.TBL_CLIENTMARGIN  WITH (NOLOCK)  WHERE MARGINDATE BETWEEN @SAUDA_DATE AND @SAUDA_DATE + ' 23:59'
GROUP BY MARGINDATE


SELECT Exchange,Segment,SUM(FinalAmount) AS FinalAmount INTO #COLLATERALDETAILS
FROM MSAJAG.DBO.COLLATERALDETAILS  WITH (NOLOCK)  WHERE EFFDATE BETWEEN @SAUDA_DATE AND @SAUDA_DATE + ' 23:59'
GROUP BY Exchange,Segment

SELECT FORMAT(SUM(GLAMT), 'N', 'en-us')  AS GLAMT,FORMAT(SUM(MARGIN), 'N', 'en-us')  AS MARGIN, FORMAT(SUM(COLLAMT), 'N', 'en-us')  AS COLLAMT FROM (
SELECT SUM(VAMT) AS GLAMT,0 AS MARGIN, 0 AS COLLAMT FROM #LEDGERGL UNION ALL
SELECT 0 AS GLAMT,SUM(TOTAL_MARGIN) AS MARGIN, 0 AS COLLAMT FROM #TOTAL_MARGIN_ALL UNION ALL
SELECT 0 AS GLAMT,0 AS MARGIN, SUM(FINALAMOUNT) AS COLLAMT FROM #COLLATERALDETAILS) AS A

DROP TABLE #LEDGERGL
DROP TABLE #TOTAL_MARGIN_ALL
DROP TABLE #COLLATERALDETAILS
End

GO
