-- Object: PROCEDURE dbo.GET_EXCHANGE_SEGMENT_04102012
-- Server: 10.253.33.91 | DB: PRADNYA
--------------------------------------------------

  
CREATE PROC [dbo].[GET_EXCHANGE_SEGMENT_04102012]  
AS  
SELECT EXCHANGE, SEGMENT, EXCHANGE + ' ' + SEGMENT FROM PRADNYA..MULTICOMPANY WHERE PRIMARYSERVER = 1 ORDER BY 3

GO
