-- Object: TABLE citrus_usr.DEMAT_TRAN_TRANM_DTLS_mak_bak160419
-- Server: 10.253.33.190 | DB: DMAT
--------------------------------------------------

CREATE TABLE [citrus_usr].[DEMAT_TRAN_TRANM_DTLS_mak_bak160419]
(
    [DEMTTD_DEMRM_ID] NUMERIC(10, 0) NOT NULL,
    [DEMTTD_HLD1] VARCHAR(50) NULL,
    [DEMTTD_HLD2] VARCHAR(50) NULL,
    [DEMTTD_HLD3] VARCHAR(50) NULL,
    [DEMTTD_SURV1] VARCHAR(50) NULL,
    [DEMTTD_SURV2] VARCHAR(50) NULL,
    [DEMTTD_SURV3] VARCHAR(50) NULL,
    [DEMTTD_CREATED_BY] VARCHAR(25) NOT NULL,
    [DEMTTD_CREATED_DT] DATETIME NOT NULL,
    [DEMTTD_LST_UPD_BY] VARCHAR(25) NOT NULL,
    [DEMTTD_LST_UPD_DT] DATETIME NOT NULL,
    [DEMTTD_DELETED_IND] SMALLINT NOT NULL
);

GO
