-- Object: TABLE citrus_usr.CDSL_UCC_DTLS_MAK
-- Server: 10.253.33.190 | DB: DMAT
--------------------------------------------------

CREATE TABLE [citrus_usr].[CDSL_UCC_DTLS_MAK]
(
    [CUDM_ID] NUMERIC(18, 0) NULL,
    [CUDM_BOID] VARCHAR(16) NULL,
    [CUDM_UCC] VARCHAR(100) NULL,
    [CUDM_EXID] VARCHAR(10) NULL,
    [CUDM_CMID] VARCHAR(10) NULL,
    [CUDM_TMCD] VARCHAR(20) NULL,
    [CUDM_SEGID] VARCHAR(30) NULL,
    [CUDM_LINKSTATUS] VARCHAR(200) NULL,
    [CUDM_CONSENTFLG] CHAR(1) NULL,
    [CUDM_DPAM_ID] NUMERIC(18, 0) NULL,
    [CUDM_CREATED_BY] VARCHAR(50) NULL,
    [CUDM_CREATED_DT] DATETIME NULL,
    [CUDM_LST_UPD_BY] VARCHAR(50) NULL,
    [CUDM_LST_UPD_DT] DATETIME NULL,
    [CUDM_DELETED_IND] SMALLINT NULL
);

GO
