-- Object: PROCEDURE citrus_usr.PR_SD_RPT
-- Server: 10.253.33.190 | DB: DMAT
--------------------------------------------------


CREATE  PROC [citrus_usr].[PR_SD_RPT](
@PA_FROM_DT DATETIME, @PA_TO_DT DATETIME   
,@PA_LOGIN_NAME VARCHAR(100) 
)
AS
BEGIN
SELECT ''''+DPAM_SBA_NO BOID,CLIC_CHARGE_AMT AMOUNT,convert (varchar  (11),  CLIC_TRANS_DT,103)  TRANSACTIONDATE,CLIC_CHARGE_NAME CHARGENAME
 FROM CLIENT_CHARGES_CDSL,DP_ACCT_MSTR WHERE DPAM_ID=CLIC_DPAM_ID AND CLIC_DELETED_IND=1 AND DPAM_DELETED_IND=1
AND CLIC_TRANS_DT BETWEEN @PA_FROM_DT AND @PA_TO_DT
AND CLIC_FLG='M' 
AND CLIC_CHARGE_NAME='STAMP DUTY CHARGES'
order by 3 , 1
END

GO
