-- Object: TABLE citrus_usr.INSTA_BOID_MSTR
-- Server: 10.253.33.190 | DB: DMAT
--------------------------------------------------

CREATE TABLE [citrus_usr].[INSTA_BOID_MSTR]
(
    [INSTA_BOID] VARCHAR(16) NULL,
    [INSTA_FILEDATE] DATETIME NULL,
    [INSTA_PAN_GIR_NO] VARCHAR(10) NULL,
    [INSTA_FILLER1] VARCHAR(20) NULL,
    [INSTA_CREATED_BY] VARCHAR(30) NULL,
    [INSTA_CREATED_DT] DATETIME NULL,
    [INSTA_CREATED_LST_UPD_BY] VARCHAR(30) NULL,
    [INSTA_CREATED_LST_UPD_DT] DATETIME NULL,
    [INSTA_DELETED_IND] SMALLINT NULL
);

GO
