-- Object: TABLE citrus_usr.CLISBA_HST
-- Server: 10.253.33.190 | DB: DMAT
--------------------------------------------------

CREATE TABLE [citrus_usr].[CLISBA_HST]
(
    [CLISBA_ID] NUMERIC(10, 0) NOT NULL,
    [CLISBA_CRN_NO] NUMERIC(10, 0) NOT NULL,
    [CLISBA_ACCT_NO] VARCHAR(25) NOT NULL,
    [CLISBA_NO] VARCHAR(25) NOT NULL,
    [CLISBA_NAME] VARCHAR(50) NOT NULL,
    [CLISBA_EXCPM_ID] NUMERIC(10, 0) NOT NULL,
    [CLISBA_ACCESS2] NUMERIC(10, 0) NOT NULL,
    [CLISBA_CREATED_BY] VARCHAR(25) NOT NULL,
    [CLISBA_CREATED_DT] DATETIME NOT NULL,
    [CLISBA_LST_UPD_BY] VARCHAR(25) NOT NULL,
    [CLISBA_LST_UPD_DT] DATETIME NOT NULL,
    [CLISBA_DELETED_IND] SMALLINT NOT NULL,
    [CLISBA_ACTION] VARCHAR(20) NOT NULL
);

GO
