-- Object: PROCEDURE citrus_usr.NONPOA_HOLDING_MKT
-- Server: 10.253.33.190 | DB: DMAT
--------------------------------------------------





CREATE PROC [citrus_usr].[NONPOA_HOLDING_MKT] 
AS
SELECT * INTO #SETT FROM [ANGELDEMAT].MSAJAG.DBO.SETT_MST 
WHERE SEC_PAYIN >=CONVERT(VARCHAR(11),GETDATE(),120)
AND START_DATE <=CONVERT(VARCHAR(11),GETDATE(),120)

CREATE INDEX #S ON #SETT(SETT_NO,SETT_TYPE) 

SELECT DISTINCT M.PARTY_CODE,M.CLTDPNO,I_ISIN,
REPLACE(LEFT(CONVERT(VARCHAR,SEC_PAYIN, 104), 10),'.','') AS PAYINDATE,START_DATE AS TRADE_DATE,
SEC_PAYIN AS SEC_PAYIN
INTO #CLT1  FROM [ANGELDEMAT].MSAJAG.DBO.MULTICLTID M WITH(NOLOCK),  
[ANGELDEMAT].MSAJAG.DBO.DELIVERYCLT D  WITH(NOLOCK)  ,#SETT S
WHERE D.SETT_NO=S.SETT_NO  AND D.PARTY_CODE=M.PARTY_CODE AND D.SETT_TYPE=S.SETT_TYPE   
 AND INOUT ='I'   AND DEF <>1  
  
  CREATE INDEX #C ON #CLT1(PARTY_CODE,CLTDPNO,I_ISIN )
   CREATE INDEX #F ON #CLT1(PAYINDATE,TRADE_DATE )

 DECLARE @REQUEST_DATE DATETIME
 SET @REQUEST_DATE = CONVERT(VARCHAR(11),GETDATE()-7,120)

SELECT PARTY_CODE=PARTYCODE, DPID=LEFT(CLIENT_ID,8), CLIENT_ID, ISIN, REF_NO,TRADEQTY=TRADEQTY,  
 REQUESTEDDATE=REQUESTEDDATE,INSTQTY=0,BATCHNO=0,BATCH_DATE='',SETTLEMENT_NO='',SETT_TYPE='',FLAG  Into #Final FROM (
SELECT DISTINCT CLIENT_ID=BOID,ISIN,
TRADEQTY=(CASE WHEN CAST(ISNULL(PEND_QTY,0)AS FLOAT)>0 THEN CAST(ISNULL(PEND_QTY,0) AS FLOAT) ELSE QTY END )          
,FLAG,REQUESTEDDATE=TRADE_DATE,NO_OF_DAYS ,DIS_TRXN_STATUS=ISNULL(DUMMY3,''),REF_NO=CDSL_TRXN_ID   ,SEC_PAYIN ,PARTYCODE
FROM  E_DIS_TRXN_DATA T (NOLOCK)  ,#CLT1 C (NOLOCK) WHERE 
REQUEST_DATE>=@REQUEST_DATE AND C.PARTY_CODE=PARTYCODE
AND I_ISIN=ISIN AND DUMMY2 =PAYINDATE 
AND ISNULL(VALID,0)=0 ) A WHERE  ISNULL(REF_NO,'') <> ''  	

SELECT * FROM #FINAL With(Nolock)

GO
