-- Object: PROCEDURE citrus_usr.PR_ONLINE_DPTRX_BEN_bak_05102016
-- Server: 10.253.33.190 | DB: DMAT
--------------------------------------------------




create PROCEDURE [citrus_usr].[PR_ONLINE_DPTRX_BEN]
(
@PA_ONL_ACTION VARCHAR(20)
,@PA_ONL_TRXFEREE_DPID VARCHAR(8)
,@PA_ONL_CMBPID VARCHAR(8)
,@PA_ONL_TRXFEREE_DPNAME VARCHAR(100)
,@PA_ONL_TRXFEREE_BOID VARCHAR(16)
,@PA_ONL_TRXFEREE_BONAME VARCHAR(100)
,@PA_ONL_OTP VARCHAR(5)
,@PA_ONL_LOGIN_NAMES VARCHAR(30)
,@PA_ONL_CREATED_BY VARCHAR(50)
,@PA_ONL_CREATED_DT DATETIME
,@PA_ONL_LST_UPD_BY VARCHAR(50)
,@PA_ONL_LST_UPD_DT DATETIME
,@PA_ONL_DELETED_IND SMALLINT
,@PA_ONL_TRX_BOID VARCHAR(16)
)
AS 
BEGIN


declare @bo_name varchar(1000) 

select @bo_name = DPAM_SBA_NAME from dp_acct_mstr where DPAM_SBA_NO = @PA_ONL_TRX_BOID and DPAM_DELETED_IND = 1 


IF @PA_ONL_ACTION='INS'
BEGIN
IF NOT EXISTS(SELECT 1 FROM ONLINE_DPTRX_BEN_MSTR WHERE (ONL_TRXFEREE_DPID=@PA_ONL_TRXFEREE_DPID OR ONL_CMBPID =@PA_ONL_CMBPID) AND ONL_TRXFEREE_BONAME= @PA_ONL_TRXFEREE_BONAME AND ONL_TRXFEREE_BOID=@PA_ONL_TRXFEREE_BOID AND ONL_DELETED_IND=1)
BEGIN
INSERT INTO ONLINE_DPTRX_BEN_MSTR (ONL_TRX_BOID,ONL_TRX_BONAME,ONL_TRXFEREE_DPID
,ONL_CMBPID
,ONL_TRXFEREE_DPNAME
,ONL_TRXFEREE_BOID
,ONL_TRXFEREE_BONAME
,ONL_OTP
,ONL_CREATED_BY
,ONL_CREATED_DT
,ONL_LST_UPD_BY
,ONL_LST_UPD_DT
,ONL_DELETED_IND)
SELECT 
@PA_ONL_TRX_BOID,@bo_name
,@PA_ONL_TRXFEREE_DPID
,@PA_ONL_CMBPID 
,@PA_ONL_TRXFEREE_DPNAME 
,@PA_ONL_TRXFEREE_BOID 
,@PA_ONL_TRXFEREE_BONAME 
,@PA_ONL_OTP 
,@PA_ONL_LOGIN_NAMES 
,GETDATE() 
,@PA_ONL_LOGIN_NAMES 
,GETDATE() 
,'1'

END 
END
IF @PA_ONL_ACTION='DEL'
BEGIN
IF EXISTS(SELECT 1 FROM ONLINE_DPTRX_BEN_MSTR WHERE (ONL_TRXFEREE_DPID=@PA_ONL_TRXFEREE_DPID OR ONL_CMBPID =@PA_ONL_CMBPID)  AND ONL_TRXFEREE_BOID=@PA_ONL_TRXFEREE_BOID AND ONL_DELETED_IND=1)
BEGIN
UPDATE ONLINE_DPTRX_BEN_MSTR SET ONL_DELETED_IND=9,ONL_LST_UPD_BY=@PA_ONL_LOGIN_NAMES,ONL_LST_UPD_DT=GETDATE() WHERE (ONL_TRXFEREE_DPID=@PA_ONL_TRXFEREE_DPID OR ONL_CMBPID =@PA_ONL_CMBPID) AND ONL_TRXFEREE_BONAME= @PA_ONL_TRXFEREE_BONAME AND ONL_TRXFEREE_BOID=@PA_ONL_TRXFEREE_BOID AND ONL_DELETED_IND=1

END 
END
END

GO
