-- Object: PROCEDURE citrus_usr.CLASS_AUTO_PROCESS_VIEW
-- Server: 10.253.33.190 | DB: DMAT
--------------------------------------------------

CREATE PROCEDURE [citrus_usr].[CLASS_AUTO_PROCESS_VIEW]    
(     
 @PROCESSDATE VARCHAR(11),    
 @PROCESSON VARCHAR(30),    
 @PROCESSTYPE VARCHAR(30),    
 @PROCESSFOR VARCHAR(30),    
 @UNAME VARCHAR(25),    
 @STATUSNAME VARCHAR(25),    
 @REQIP VARCHAR(100),    
 @STATUSID VARCHAR(25),    
 @PROCESSID INT,    
 @LEVEL VARCHAR(1)     
)    
AS    
    
OPEN SYMMETRIC KEY   Key4CertAutoProcess    
     DECRYPTION BY   CERTIFICATE CertAutoProcess     
    
SET @PROCESSDATE = CONVERT(VARCHAR(11), CONVERT(DATETIME, @PROCESSDATE, 103), 109)     
BEGIN     
      
 IF @LEVEL='1'---summary    
 BEGIN     
  SELECT SNO    
  ,PROCESS_TYPE    
  ,PROCESS_FOR    
  ,PROCESS_ID    
  ,SETT_NO    
  ,SETT_TYPE    
  ,PROCESS_START_DATE = CONVERT(VARCHAR(5),PROCESS_START_DATE,114)    
  ,PROCESS_END_DATE = CONVERT(VARCHAR(5),PROCESS_END_DATE,114)    
  ,PROCESS_FILE_NAME=dmat.citrus_usr.FN_DATA_DECRYPT('MKTTECH.IN',PROCESS_FILE_NAME)    
  ,WAIT_PERIOD = LEFT(WAIT_PERIOD,5)    
  ,APPROX_END_TIME = LEFT(APPROX_END_TIME,5)    
  ,PROCESS_STATUS = (CASE WHEN PROCESS_STATUS = 0 THEN 'PENDING' WHEN PROCESS_STATUS = 100 THEN 'COMPLETTED'     
       WHEN PROCESS_STATUS = 99 THEN 'IN - PROCESS' ELSE 'HALT DUE TO SOME ISSUE' END)     
  ,PROCESS_HALTED_REASON    , PROCESS_ORDER_ID      
  FROM dmat.citrus_usr.TBL_AUTO_PROCESS_DETAIL    
  WHERE     
  PROCESS_DATE = @PROCESSDATE    
  AND PROCESS_FOR LIKE CASE WHEN @PROCESSFOR='-----SELECT-----' THEN '' ELSE @PROCESSFOR END + '%'    
  AND PROCESS_TYPE LIKE CASE WHEN @PROCESSTYPE='-----SELECT-----' THEN '' ELSE @PROCESSTYPE END + '%'    
  AND PROCESS_STATUS  = CASE WHEN @PROCESSON <> '' THEN @PROCESSON ELSE PROCESS_STATUS END     
  --ORDER BY SNO               
 END    
     
 IF @LEVEL='2'---detail    
 BEGIN     
      
  DECLARE @PROCESSCUR CURSOR     
  DECLARE @IS_DEPEND_ON_ORG VARCHAR(20)    
  DECLARE @PROCESS_ID INT       
      
  CREATE TABLE #PROCESSID (PROCID INT,DEPEND_ON INT)    
      
  SET @PROCESSCUR = CURSOR FOR        
      SELECT PROCESS_ID,IS_DEPEND_ON_ORG=REPLACE(IS_DEPEND_ON_ORG,'#','')     
      FROM dmat.citrus_usr.TBL_AUTO_PROCESS_DETAIL     
      WHERE PROCESS_DATE = @PROCESSDATE    
  OPEN @PROCESSCUR    
      
  FETCH NEXT FROM @PROCESSCUR INTO @PROCESS_ID, @IS_DEPEND_ON_ORG    
  WHILE @@FETCH_STATUS = 0    
  BEGIN    
   INSERT INTO #PROCESSID    
   SELECT @PROCESS_ID,* FROM citrus_usr.fnSplitString2Tbl(@IS_DEPEND_ON_ORG,',')    
       
   FETCH NEXT FROM @PROCESSCUR INTO @PROCESS_ID, @IS_DEPEND_ON_ORG    
  END    
  CLOSE @PROCESSCUR    
  DEALLOCATE @PROCESSCUR    
      
  INSERT INTO #PROCESSID    
  SELECT PROCESS_ID,IS_DEPEND_ON_ORG=REPLACE(REPLACE(IS_DEPEND_ON_ORG,'#',''),',','')     
  FROM  dmat.citrus_usr.TBL_AUTO_PROCESS_DETAIL WHERE PROCESS_ID NOT IN(SELECT PROCID FROM #PROCESSID)    
      
      
  CREATE TABLE #PROC(PROCID INT,DPND INT,FLAG INT)    
  INSERT INTO #PROC VALUES(@PROCESSID,0,1)    
      
  DECLARE @EXITLOOP INT    
  SET @EXITLOOP = 0    
    
  DECLARE @I INT    
  SET @I = 1    
  --exec CLASS_AUTO_PROCESS_VIEW '18/12/2014','','','','','','','','12','2'    
  WHILE @EXITLOOP = 0    
  BEGIN    
   SET @I = @I + 1    
       
   INSERT INTO #PROC    
   SELECT PROCID,DEPEND_ON,@I FROM #PROCESSID WHERE DEPEND_ON IN (SELECT PROCID FROM #PROC WHERE FLAG=@I-1)    
       
   IF (SELECT COUNT(1) FROM #PROC WHERE FLAG=@I) =0    
   BEGIN    
    SET @EXITLOOP = 1    
   END    
    
  END    
       
  SELECT SNO    
  ,PROCESS_TYPE    
  ,PROCESS_FOR    
  ,PROCESS_ID    
  ,SETT_NO    
  ,SETT_TYPE    
  ,PROCESS_START_DATE = CONVERT(VARCHAR(5),PROCESS_START_DATE,114)    
  ,PROCESS_END_DATE = CONVERT(VARCHAR(5),PROCESS_END_DATE,114)    
  ,PROCESS_FILE_NAME=dmat.citrus_usr.FN_DATA_DECRYPT('MKTTECH.IN',PROCESS_FILE_NAME)    
  ,WAIT_PERIOD = LEFT(WAIT_PERIOD,5)    
  ,APPROX_END_TIME = LEFT(APPROX_END_TIME,5)    
  ,PROCESS_STATUS = (CASE WHEN PROCESS_STATUS = 0 THEN 'PENDING' WHEN PROCESS_STATUS = 100 THEN 'COMPLETTED'     
       WHEN PROCESS_STATUS = 99 THEN 'IN - PROCESS' ELSE 'HALT DUE TO SOME ISSUE' END)     
  ,PROCESS_HALTED_REASON   , process_order_id       
  FROM dmat.citrus_usr.TBL_AUTO_PROCESS_DETAIL D,#PROC     
  WHERE     
  PROCESS_DATE = @PROCESSDATE    
  --AND PROCESS_FOR LIKE CASE WHEN @PROCESSFOR='-----SELECT-----' THEN '' ELSE @PROCESSFOR END + '%'    
  --AND PROCESS_TYPE LIKE CASE WHEN @PROCESSTYPE='-----SELECT-----' THEN '' ELSE @PROCESSTYPE END + '%'    
  --AND PROCESS_STATUS  = CASE WHEN @PROCESSON <> '' THEN @PROCESSON ELSE PROCESS_STATUS END    
  AND PROCESS_ID = #PROC.PROCID    
  ORDER BY FLAG    
      
  DROP TABLE #PROCESSID    
  DROP TABLE #PROC    
    
 END     
END    
    
CLOSE SYMMETRIC KEY   Key4CertAutoProcess;

GO
