-- Object: TABLE citrus_usr.ENTTM_ENTR_MAPPING
-- Server: 10.253.33.190 | DB: DMAT
--------------------------------------------------

CREATE TABLE [citrus_usr].[ENTTM_ENTR_MAPPING]
(
    [ENTEM_ENTTM_CD] VARCHAR(20) NULL,
    [ENTEM_ENTR_COL_NAME] VARCHAR(50) NOT NULL,
    [ENTEM_CREATED_BY] VARCHAR(25) NOT NULL,
    [ENTEM_CREATED_DT] DATETIME NOT NULL,
    [ENTEM_LST_UPD_BY] VARCHAR(25) NOT NULL,
    [ENTEM_LST_UPD_DT] DATETIME NOT NULL,
    [ENTEM_DELETED_IND] SMALLINT NOT NULL
);

GO
