-- Object: TABLE citrus_usr.CDSL_DPM_RESPONSE
-- Server: 10.253.33.190 | DB: DMAT
--------------------------------------------------

CREATE TABLE [citrus_usr].[CDSL_DPM_RESPONSE]
(
    [CDSL_ACCT_ID] VARCHAR(20) NULL,
    [CDSL_LINE_NO] VARCHAR(20) NULL,
    [CDSL_BATCHNO] VARCHAR(20) NULL,
    [CDSL_CREATED_BY] VARCHAR(20) NULL,
    [CDSL_CREATED_DT] VARCHAR(11) NULL,
    [CDSL_LST_UPD_BY] VARCHAR(20) NULL,
    [CDSL_LST_UPD_DT] VARCHAR(11) NULL,
    [CDSL_DELETED_IND] INT NULL
);

GO
