-- Object: TABLE citrus_usr.tmp_Nov182019accl
-- Server: 10.253.33.190 | DB: DMAT
--------------------------------------------------

CREATE TABLE [citrus_usr].[tmp_Nov182019accl]
(
    [id] INT IDENTITY(1,1) NOT NULL,
    [ACCPM_PROP_ID] NUMERIC(10, 0) NOT NULL,
    [ACCPM_CLICM_ID] NUMERIC(10, 0) NOT NULL,
    [ACCPM_ENTTM_ID] BIGINT NULL,
    [ACCPM_EXCPM_ID] NUMERIC(10, 0) NOT NULL,
    [ACCPM_PROP_CD] VARCHAR(20) NOT NULL,
    [ACCPM_PROP_DESC] VARCHAR(100) NULL,
    [ACCPM_PROP_RMKS] VARCHAR(250) NULL,
    [ACCPM_MDTY] SMALLINT NOT NULL,
    [ACCPM_ACCT_TYPE] VARCHAR(20) NOT NULL,
    [ACCPM_DATATYPE] VARCHAR(5) NOT NULL,
    [ACCPM_CREATED_BY] VARCHAR(25) NOT NULL,
    [ACCPM_CREATED_DT] DATETIME NOT NULL,
    [ACCPM_LST_UPD_BY] VARCHAR(25) NOT NULL,
    [ACCPM_LST_UPD_DT] DATETIME NOT NULL,
    [ACCPM_DELETED_IND] SMALLINT NOT NULL,
    [accpm_default_val] VARCHAR(50) NULL,
    [realid] BIGINT NULL
);

GO
