-- Object: TABLE citrus_usr.TMP_BP_MSTR
-- Server: 10.253.33.190 | DB: DMAT
--------------------------------------------------

CREATE TABLE [citrus_usr].[TMP_BP_MSTR]
(
    [TMPBP_ID] VARCHAR(8) NULL,
    [TMPBP_ROLE] NUMERIC(2, 0) NULL,
    [TMPBP_ADD_L1] VARCHAR(60) NULL,
    [TMPBP_ADD_L2] VARCHAR(60) NULL,
    [TMPBP_ADD_L3] VARCHAR(60) NULL,
    [TMPBP_ADD_L4] VARCHAR(60) NULL,
    [TMPBP_ADD_PC] VARCHAR(7) NULL,
    [TMPBP_PH_NO] VARCHAR(24) NULL,
    [TMPBP_FAX_NO] VARCHAR(24) NULL,
    [TMPBP_ASS_CC_ID] VARCHAR(8) NULL,
    [TMPBP_ASS_DP_ID] VARCHAR(8) NULL,
    [TMPBP_ASS_CC_CM_ID] VARCHAR(16) NULL,
    [TMPBP_BP_CAT] CHAR(2) NULL,
    [TMPBP_BP_NM] VARCHAR(135) NULL,
    [TMPBP_BP_STAT] VARCHAR(100) NULL
);

GO
