-- Object: VIEW citrus_usr.CLIENT_MASTER_GET_IPO
-- Server: 10.253.33.190 | DB: DMAT
--------------------------------------------------

CREATE view CLIENT_MASTER_GET_IPO
as
SELECT DISTINCT CASE WHEN SUBCM_DESC LIKE '%INDIVI%' THEN 'IND' WHEN SUBCM_DESC LIKE '%HUF%' THEN 'HUF' 
WHEN SUBCM_DESC LIKE '%NRI%' THEN 'NRI' ELSE DPAM_SUBCM_CD END CM_USER_TYPE,
STAM_DESC CM_USER_STATUS
,CM_POA = (SELECT CASE WHEN COUNT(1)=0 THEN '0' ELSE '1' END FROM 
DP_POA_DTLS 
WHERE DPPD_DPAM_ID=DPAM_ID AND DPPD_DELETED_IND=1)	,
ISNULL(DPAM_SBA_NAME,'') CM_APPNAME1,
ISNULL(DPHD_SH_FNAME,'') + ' ' + ISNULL(DPHD_SH_MNAME,'') + ' ' +  ISNULL(DPHD_SH_LNAME,'') CM_APPNAME2,
ISNULL(DPHD_TH_FNAME,'') + ' ' + ISNULL(DPHD_TH_MNAME,'') + ' ' +  ISNULL(DPHD_TH_LNAME,'') CM_APPNAME3
,ISNULL(CLIM_DOB,'') CM_DOB1
,ISNULL(DPHD_SH_DOB,'') CM_DOB2
,ISNULL(DPHD_TH_DOB,'') CM_DOB3
,ISNULL(CLIM_GENDER,'') CM_GENDER1
,ISNULL(DPHD_SH_GENDER,'') CM_GENDER2
,ISNULL(DPHD_TH_GENDER,'') CM_GENDER3
,ISNULL(DPHD_FH_FTHNAME,'') CM_FATHERHUSBAND
,ISNULL(ENTP_VALUE,'') CM_PAN1
,ISNULL(DPHD_SH_PAN_NO,'') CM_PAN2
,ISNULL(DPHD_TH_PAN_NO,'') CM_PAN3
,'' CM_CIRCLE1
,'' CM_CIRCLE2
, ''CM_CIRCLE3
, ''CM_MAPINFLAG 
,'' CM_MAPIN
, '' CM_CATEGORY 
,  '' CM_BM_ID 
, '' CM_SBM_ID 
,rtrim(ltrim(ISNULL(DPHD_NOM_FNAME,''))) + ' ' + rtrim(ltrim(ISNULL(DPHD_NOM_MNAME,''))) + ' ' +  rtrim(ltrim(ISNULL(DPHD_NOM_LNAME,''))) CM_NOMINEE
, '' CM_NOMINEE_RELATION
,  ISNULL(DPHD_GAU_PAN_NO,'') CM_GUARDIANPAN
, CDD_DEPOSITORY = CASE WHEN LEN(DPAM_SBA_NO)=16 THEN 'CDSL' ELSE 'NSDL' END
,  CDD_DPID = (SELECT TOP 1 DPM_DPID FROM DP_MSTR WHERE DPM_EXCSM_ID=DPAM_EXCSM_ID AND DPM_DELETED_IND=1)
,   CDD_DPNAME = (SELECT TOP 1 DPM_NAME FROM DP_MSTR WHERE
    DPM_EXCSM_ID=DPAM_EXCSM_ID AND DPM_DELETED_IND=1) 
, CDD_CLIENTDPID = ISNULL(DPAM_SBA_NO,'')  
, CBD_BANK_NAME = (SELECT TOP 1  BANM_NAME FROM BANK_MSTR WHERE BANM_ID=CLIBA_BANM_ID) 
,    CBD_BRANCH = (SELECT TOP 1  BANM_BRANCH FROM BANK_MSTR WHERE BANM_ID=CLIBA_BANM_ID) 
,  CBD_CITY = (SELECT TOP 1  BANM_BRANCH FROM BANK_MSTR WHERE BANM_ID=CLIBA_BANM_ID) 
,  CBD_ACCTYPE = CLIBA_AC_TYPE 
,    CBD_ACCNO = CLIBA_AC_NO 
,  CBD_CUSTID = '' 
,  CBD_CHEQUENAME = '' ,ISNULL(ACCP_VALUE,'') CM_PARTY_CODE
,DPAM_SBA_NO
FROM DP_ACCT_MSTR
LEFT OUTER JOIN ENTITY_PROPERTIES ON
ENTP_ENT_ID=DPAM_CRN_NO AND ENTP_ENTPM_CD='PAN_GIR_NO' AND ENTP_DELETED_IND=1
,SUB_CTGRY_MSTR  
,STATUS_MSTR,DP_HOLDER_DTLS,CLIENT_MSTR 
,CLIENT_BANK_ACCTS 
left outer join ACCOUNT_PROPERTIES on  ACCP_CLISBA_ID=cliba_clisba_id AND ACCP_ACCPM_PROP_CD='BBO_CODE'
WHERE
 --DPAM_SBA_NO=@p_CM_UM_ID AND
 --- DPAM_SUBCM_CD =SUBCM_CD AND DPAM_DELETED_IND=1 
 DPAM_STAM_CD=STAM_CD AND DPAM_CRN_NO=CLIM_CRN_NO AND CLIM_DELETED_IND=1
AND DPAM_ID=DPHD_DPAM_ID AND CLIBA_CLISBA_ID=DPAM_ID AND CLIBA_FLG='1' 
AND ENTP_ENT_ID=DPAM_CRN_NO AND ENTP_ENTPM_CD='PAN_GIR_NO' AND ENTP_DELETED_IND=1

GO
