-- Object: TABLE citrus_usr.ENTITY_TYPE_ROLES
-- Server: 10.253.33.190 | DB: DMAT
--------------------------------------------------

CREATE TABLE [citrus_usr].[ENTITY_TYPE_ROLES]
(
    [ENTTRO_ENTTM_ID] NUMERIC(10, 0) NOT NULL,
    [ENTTRO_ROL_ID] NUMERIC(10, 0) NOT NULL,
    [ENTTRO_CREATED_BY] VARCHAR(25) NOT NULL,
    [ENTTRO_CREATED_DT] DATETIME NOT NULL,
    [ENTTRO_LST_UPD_BY] VARCHAR(25) NOT NULL,
    [ENTTRO_LST_UPD_DT] DATETIME NOT NULL,
    [ENTTRO_DELETED_IND] SMALLINT NOT NULL
);

GO
