-- Object: VIEW citrus_usr.cdsl_dp50
-- Server: 10.253.33.190 | DB: DMAT
--------------------------------------------------

create view [citrus_usr].[cdsl_dp50]
as


SELECT  DPHMCD_DPAM_ID
,'DPHMCD_CURR_QTY' [A] 
,DPHMCD_ISIN
,DPHMCD_CURR_QTY [qty]
FROM dp_daily_hldg_cdsl 
WHERE isnull(DPHMCD_CURR_QTY,0) <> 0

UNION

SELECT  DPHMCD_DPAM_ID
,'DPHMCD_FREE_QTY' [A]
,DPHMCD_ISIN
,DPHMCD_FREE_QTY [QTY]
FROM dp_daily_hldg_cdsl
WHERE isnull(DPHMCD_FREE_QTY,0) <> 0

UNION 

SELECT  DPHMCD_DPAM_ID
,'DPHMCD_FREEZE_QTY' [A]
,DPHMCD_ISIN
,DPHMCD_FREEZE_QTY  [QTY]
FROM dp_daily_hldg_cdsl
WHERE isnull(DPHMCD_FREEZE_QTY,0) <> 0
UNION 

SELECT  DPHMCD_DPAM_ID
,'DPHMCD_PLEDGE_QTY' [A]
,DPHMCD_ISIN
,DPHMCD_PLEDGE_QTY  [QTY]
FROM dp_daily_hldg_cdsl
WHERE isnull(DPHMCD_PLEDGE_QTY,0) <> 0
UNION 

SELECT  DPHMCD_DPAM_ID
,'DPHMCD_DEMAT_PND_VER_QTY' [A]
,DPHMCD_ISIN
,DPHMCD_DEMAT_PND_VER_QTY  [QTY]
FROM dp_daily_hldg_cdsl
WHERE isnull(DPHMCD_DEMAT_PND_VER_QTY,0) <> 0
UNION 

SELECT  DPHMCD_DPAM_ID
,'DPHMCD_REMAT_PND_CONF_QTY' [A]
,DPHMCD_ISIN
,DPHMCD_REMAT_PND_CONF_QTY  [QTY]
FROM dp_daily_hldg_cdsl
WHERE isnull(DPHMCD_REMAT_PND_CONF_QTY,0) <> 0
UNION 

SELECT  DPHMCD_DPAM_ID
,'DPHMCD_DEMAT_PND_CONF_QTY' [A]
,DPHMCD_ISIN
,DPHMCD_DEMAT_PND_CONF_QTY  [QTY]
FROM dp_daily_hldg_cdsl
WHERE isnull(DPHMCD_DEMAT_PND_CONF_QTY,0) <> 0
UNION 

SELECT  DPHMCD_DPAM_ID
,'DPHMCD_SAFE_KEEPING_QTY' [A]
,DPHMCD_ISIN
,DPHMCD_SAFE_KEEPING_QTY  [QTY]
FROM dp_daily_hldg_cdsl
WHERE isnull(DPHMCD_SAFE_KEEPING_QTY,0) <> 0
UNION 

SELECT  DPHMCD_DPAM_ID
,'DPHMCD_LOCKIN_QTY' [A]
,DPHMCD_ISIN
,DPHMCD_LOCKIN_QTY  [QTY]
FROM dp_daily_hldg_cdsl
WHERE isnull(DPHMCD_LOCKIN_QTY,0) <> 0
UNION 

SELECT  DPHMCD_DPAM_ID
,'DPHMCD_ELIMINATION_QTY' [A]
,DPHMCD_ISIN
,DPHMCD_ELIMINATION_QTY  [QTY]
FROM dp_daily_hldg_cdsl
WHERE isnull(DPHMCD_ELIMINATION_QTY,0) <> 0
UNION 

SELECT  DPHMCD_DPAM_ID
,'DPHMCD_EARMARK_QTY' [A]
,DPHMCD_ISIN
,DPHMCD_EARMARK_QTY  [QTY]
FROM dp_daily_hldg_cdsl
WHERE isnull(DPHMCD_EARMARK_QTY,0) <> 0

UNION 

SELECT  DPHMCD_DPAM_ID
,'DPHMCD_AVAIL_LEND_QTY' [A]
,DPHMCD_ISIN
,DPHMCD_AVAIL_LEND_QTY  [QTY]
FROM dp_daily_hldg_cdsl
WHERE isnull(DPHMCD_AVAIL_LEND_QTY,0) <> 0
UNION 

SELECT  DPHMCD_DPAM_ID
,'DPHMCD_LEND_QTY' [A]
,DPHMCD_ISIN
,DPHMCD_LEND_QTY  [QTY]
FROM dp_daily_hldg_cdsl
WHERE isnull(DPHMCD_LEND_QTY,0) <> 0
UNION 

SELECT  DPHMCD_DPAM_ID
,'DPHMCD_BORROW_QTY' [A]
,DPHMCD_ISIN
,DPHMCD_BORROW_QTY  [QTY]
FROM dp_daily_hldg_cdsl
WHERE isnull(DPHMCD_BORROW_QTY,0) <> 0

GO
