-- Object: TABLE citrus_usr.ISIN_EXCEPTION_MSTR
-- Server: 10.253.33.190 | DB: DMAT
--------------------------------------------------

CREATE TABLE [citrus_usr].[ISIN_EXCEPTION_MSTR]
(
    [ISINEM_ID] NUMERIC(18, 0) NULL,
    [ISINEM_ISIN_CD] VARCHAR(100) NULL,
    [ISINEM_EXCEP_TYPE] VARCHAR(100) NULL,
    [ISINEM_CREATED_BY] VARCHAR(50) NULL,
    [ISINEM_CREATED_DT] DATETIME NULL,
    [ISINEM_LST_UPD_BY] VARCHAR(50) NULL,
    [ISINEM_LST_UPD_DT] DATETIME NULL,
    [ISINEM_DELETED_IND] SMALLINT NULL
);

GO
