-- Object: FUNCTION citrus_usr.PIECE
-- Server: 10.253.33.190 | DB: DMAT
--------------------------------------------------

create FUNCTION [citrus_usr].[PIECE] ( @CHARACTEREXPRESSION VARCHAR(8000), @DELIMITER CHAR(1), @POSITION INTEGER)  
RETURNS VARCHAR(8000)  
AS  
BEGIN  
 IF @POSITION<1 RETURN NULL  
 IF LEN(@DELIMITER)<>1 RETURN NULL  
 DECLARE @START INTEGER  
 SET @START=1  
 WHILE @POSITION>1  
  BEGIN  
   SET @START=ISNULL(CHARINDEX(@DELIMITER, @CHARACTEREXPRESSION, @START),0)  
   IF @START=0 RETURN NULL  
   SET @POSITION= @POSITION-1  
   SET @START=@START+1  
  END  
 DECLARE @END INTEGER  
 SET @END= ISNULL(CHARINDEX(@DELIMITER, @CHARACTEREXPRESSION, @START),0)  
 IF @END=0 SET @END=LEN(@CHARACTEREXPRESSION)+1  
 RETURN SUBSTRING(@CHARACTEREXPRESSION, @START, @END-@START)  
END

GO
