-- Object: PROCEDURE citrus_usr.CLASS_AUTO_PROCESS_ALERT
-- Server: 10.253.33.190 | DB: DMAT
--------------------------------------------------

CREATE  PROC [citrus_usr].[CLASS_AUTO_PROCESS_ALERT]    
AS    
    
DECLARE @SNO NUMERIC(18,0),    
  @EXCHANGE VARCHAR(3),    
  @SEGMENT VARCHAR(7),    
  @BUSINESS_DATE VARCHAR(11),    
  @PROCESS_FOR VARCHAR(30),    
  @PROCESS_STATUS INT,    
  @PROCESS_START_DATE DATETIME,    
  @PROCESS_HALTED_REASON VARCHAR(500),    
  @PROCESS_FILE_NAME VARCHAR(500),    
  @SETT_NO  VARCHAR(10),    
  @SETT_TYPE  VARCHAR(10),    
  @TO_EMAIL_ID VARCHAR(500),    
  @CC_EMAIL_ID VARCHAR(500),    
  @BCC_EMAIL_ID VARCHAR(500),    
  @ALERT_CURSOR CURSOR,    
  @BODYTEXT  VARCHAR(MAX),    
  @SUBJECTTEXT    VARCHAR(MAX),    
  @PROCESS_OUTPUT_QUERY VARCHAR(MAX),    
  @XML NVARCHAR(MAX),    
  @INTERNAL_PROCESS_ID INT,    
  @ATTACHEMENT_FILE_NAME VARCHAR(200),    
  @FILE_DWLOAD_LOCATION VARCHAR(200),    
  @FILE_DWLOAD_NAME  VARCHAR(200)    
    
    
    
OPEN SYMMETRIC KEY   Key4CertAutoProcess    
     DECRYPTION BY   CERTIFICATE CertAutoProcess     
    
SET @ALERT_CURSOR = CURSOR FOR    
SELECT SNO, D.EXCHANGE, D.SEGMENT, BUSINESS_DATE, D.PROCESS_FOR, PROCESS_STATUS, PROCESS_START_DATE,     
PROCESS_FILE_NAME = citrus_usr.fn_CLASS_Auto_Process_Replace(citrus_usr.FN_DATA_DECRYPT('MKTTECH.IN',D.PROCESS_FILE_NAME),BUSINESS_DATE,MEMBERCODE,D.SETT_NO,LTRIM(RTRIM(D.SETT_TYPE))),    
PROCESS_HALTED_REASON = (CASE WHEN PROCESS_STATUS = 99     
         THEN (CASE WHEN PROCESS_STARTED_DATE + ' ' + APPROX_END_TIME > GETDATE() THEN 'PROCESS IS STILL GOING ON, PLEASE CHECK'    
         ELSE 'NOACTION' END)    
         WHEN PROCESS_STATUS = 0 AND PROCESS_HALTED_REASON = ''    
         THEN 'NOT YET STARTED'    
         ELSE PROCESS_HALTED_REASON END),    
TO_EMAIL_ID, CC_EMAIL_ID, BCC_EMAIL_ID,     
PROCESS_OUTPUT_QUERY = citrus_usr.fn_CLASS_Auto_Process_Replace(D.PROCESS_OUTPUT_QUERY,BUSINESS_DATE,MEMBERCODE,D.SETT_NO,LTRIM(RTRIM(D.SETT_TYPE))),    
D.SETT_NO, LTRIM(RTRIM(D.SETT_TYPE)), INTERNAL_PROCESS_ID, ATTACHEMENT_FILE_NAME    
FROM TBL_AUTO_PROCESS_DETAIL D, TBL_AUTO_PROCESS_EMAIL E, (select '' MEMBERCODE ) O --OWNER    
WHERE PROCESS_DATE = LEFT(GETDATE(),11)    
AND D.EXCHANGE = E.EXCHANGE    
AND D.SEGMENT = E.SEGMENT    
AND D.PROCESS_FOR = E.PROCESS_FOR    
AND PROCESS_STATUS_ALERT > PROCESS_STATUS_ALERT_COUNT     
AND GETDATE() >= PROCESS_LAST_ALERT_DATE + ' ' + PROCESS_STATUS_ALERT_INTERVAL    
AND (D.PROCESS_START_DATE <= GETDATE() + D.WAIT_PERIOD    
OR D.PROCESS_START_DATE <= GETDATE())    
AND 1 = (CASE WHEN PROCESS_STATUS = 0 AND PROCESS_HALTED_REASON = ''     
        THEN 0     
     ELSE 1    
   END)    
AND (CASE WHEN PROCESS_STATUS = 99     
         THEN (CASE WHEN PROCESS_STARTED_DATE + ' ' + APPROX_END_TIME > GETDATE() THEN 'PROCESS IS STILL GOING ON, PLEASE CHECK'    
         ELSE 'NOACTION' END)    
         ELSE PROCESS_HALTED_REASON END) <> 'NOACTION'    
AND IS_DEPEND_ON = ''    
ORDER BY SNO    
OPEN @ALERT_CURSOR    
FETCH NEXT FROM @ALERT_CURSOR INTO @SNO, @EXCHANGE, @SEGMENT, @BUSINESS_DATE, @PROCESS_FOR, @PROCESS_STATUS, @PROCESS_START_DATE, @PROCESS_FILE_NAME,     
       @PROCESS_HALTED_REASON, @TO_EMAIL_ID, @CC_EMAIL_ID, @BCC_EMAIL_ID, @PROCESS_OUTPUT_QUERY, @SETT_NO, @SETT_TYPE, @INTERNAL_PROCESS_ID,     
    @ATTACHEMENT_FILE_NAME    
WHILE @@FETCH_STATUS = 0    
BEGIN    
 SET @BODYTEXT = 'ALERT STATUS OF ' + @PROCESS_FOR + ' FOR THE EXCHANGE ' + @EXCHANGE + ' AND SEGMENT ' + @SEGMENT     
 IF LEN(@SETT_NO) <> ''     
 BEGIN    
  SET @BODYTEXT = @BODYTEXT + ' SETT NO - ' + CONVERT(VARCHAR,@SETT_NO) + ' AND SETT TYPE - ' + CONVERT(VARCHAR,@SETT_TYPE)    
 END    
 --SET @BODYTEXT = @BODYTEXT + ' FOR THE PROCESS NO - ' + CONVERT(VARCHAR,@SNO)    
 SET @SUBJECTTEXT = @BODYTEXT    
 SET @BODYTEXT = @BODYTEXT + ' <BR> ' + @PROCESS_HALTED_REASON     
 IF LEN(@PROCESS_FILE_NAME) > 0     
 BEGIN     
  IF @PROCESS_FILE_NAME NOT LIKE '%#%'    
  BEGIN    
   SET @BODYTEXT = @BODYTEXT + ' AS PER THE FILE ' + @PROCESS_FILE_NAME    
  END    
  ELSE    
  BEGIN    
   SELECT     
   @FILE_DWLOAD_LOCATION = citrus_usr.fn_CLASS_Auto_Process_Replace(DBO.FN_DATA_DECRYPT('MKTTECH.IN',M.FILE_DWLOAD_LOCATION),BUSINESS_DATE,MEMBERCODE,D.SETT_NO,LTRIM(RTRIM(D.SETT_TYPE))),    
   @FILE_DWLOAD_NAME = citrus_usr.fn_CLASS_Auto_Process_Replace(DBO.FN_DATA_DECRYPT('MKTTECH.IN',M.FILE_DWLOAD_NAME),BUSINESS_DATE,MEMBERCODE,D.SETT_NO,LTRIM(RTRIM(D.SETT_TYPE)))    
   FROM TBL_AUTO_PROCESS_DETAIL D,     
   TBL_AUTO_PROCESS_MASTER M,     
   (select '' MEMBERCODE ) O --OWNER O    
   WHERE PROCESS_DATE = LEFT(GETDATE(),11)    
   AND D.PROCESS_FOR = M.PROCESS_FOR    
   AND D.SNO = @SNO    
   SET @BODYTEXT = @BODYTEXT + ' NO NEW FILE PREENT IN LOCATION ' + @FILE_DWLOAD_LOCATION + '\' + @FILE_DWLOAD_NAME    
  END    
 END     
    
 IF @PROCESS_OUTPUT_QUERY <> '' AND @PROCESS_STATUS <> 0    
 BEGIN      
  --SET @PROCESS_OUTPUT_QUERY = 'EXECUTE SaveTableAsHTML @DBFetch = ''' + replace(@PROCESS_OUTPUT_QUERY,'''','''''') + ''''     
    
  --SET @PROCESS_OUTPUT_QUERY = ''''+replace(@PROCESS_OUTPUT_QUERY,'''','''''')+''''    
  --PRINT @PROCESS_OUTPUT_QUERY    
    
  exec SpCustomTable2HTML @PROCESS_OUTPUT_QUERY, @XML OUTPUT, ' border="1" cellpadding="2" cellspacing="0" style="font-size:14px";', ' style="color:blue;background-color:yellow;"'    
  --SELECT ISNULL(@XML,'')    
  SET @BODYTEXT = @BODYTEXT + ISNULL(@XML,'')    
      
  IF (SELECT ISNULL(COUNT(1),0) FROM TBL_AUTO_PROCESS_DETAIL WHERE SNO = @SNO    
   AND PROCESS_STATUS_ALERT > PROCESS_STATUS_ALERT_COUNT) > 0    
  BEGIN    
   EXEC msdb..SP_SEND_DBMAIL     
   @profile_name= 'DP AUTO PROCESS TEST PROFILE',    
   @RECIPIENTS=@TO_EMAIL_ID,    
   @BODY=@BODYTEXT,     
   @copy_recipients = @CC_EMAIL_ID,     
   @blind_copy_recipients = @BCC_EMAIL_ID,    
   @subject = @SUBJECTTEXT,    
   @body_format = 'HTML',    
   @FILE_ATTACHMENTS = @ATTACHEMENT_FILE_NAME    
  END    
 END    
 ELSE    
 BEGIN    
    
  IF (SELECT ISNULL(COUNT(1),0) FROM TBL_AUTO_PROCESS_DETAIL WHERE SNO = @SNO    
   AND PROCESS_STATUS_ALERT > PROCESS_STATUS_ALERT_COUNT) > 0    
  BEGIN    
   EXEC msdb..SP_SEND_DBMAIL     
   @profile_name= 'DP AUTO PROCESS TEST PROFILE',    
   @RECIPIENTS=@TO_EMAIL_ID,    
   @BODY=@BODYTEXT,     
   @copy_recipients = @CC_EMAIL_ID,     
   @blind_copy_recipients = @BCC_EMAIL_ID,    
   @subject = @SUBJECTTEXT,    
   @body_format = 'HTML',    
   @FILE_ATTACHMENTS = @ATTACHEMENT_FILE_NAME    
  END    
 END    
 UPDATE TBL_AUTO_PROCESS_DETAIL SET PROCESS_STATUS_ALERT_COUNT = PROCESS_STATUS_ALERT_COUNT + 1, PROCESS_LAST_ALERT_DATE = GETDATE()    
 WHERE SNO = @SNO    
 FETCH NEXT FROM @ALERT_CURSOR INTO @SNO, @EXCHANGE, @SEGMENT, @BUSINESS_DATE, @PROCESS_FOR, @PROCESS_STATUS, @PROCESS_START_DATE, @PROCESS_FILE_NAME,     
           @PROCESS_HALTED_REASON, @TO_EMAIL_ID, @CC_EMAIL_ID, @BCC_EMAIL_ID, @PROCESS_OUTPUT_QUERY, @SETT_NO, @SETT_TYPE, @INTERNAL_PROCESS_ID,     
     @ATTACHEMENT_FILE_NAME     
END    
CLOSE @ALERT_CURSOR    
DEALLOCATE @ALERT_CURSOR    
    
CLOSE SYMMETRIC KEY   Key4CertAutoProcess;

GO
