-- Object: TABLE citrus_usr.settlement_mstr_bak16082024
-- Server: 10.253.33.190 | DB: DMAT
--------------------------------------------------

CREATE TABLE [citrus_usr].[settlement_mstr_bak16082024]
(
    [SETM_ID] NUMERIC(10, 0) NOT NULL,
    [SETM_SETTM_ID] NUMERIC(10, 0) NOT NULL,
    [SETM_EXCM_ID] NUMERIC(10, 0) NOT NULL,
    [SETM_CCM_ID] NUMERIC(10, 0) NOT NULL,
    [SETM_NO] VARCHAR(20) NOT NULL,
    [SETM_START_DT] DATETIME NOT NULL,
    [SETM_END_DT] DATETIME NOT NULL,
    [SETM_DEADLINE_DT] DATETIME NOT NULL,
    [SETM_DEADLINE_TIME] VARCHAR(20) NOT NULL,
    [SETM_PAYIN_DT] DATETIME NOT NULL,
    [SETM_PAYOUT_DT] DATETIME NOT NULL,
    [SETM_AUCTION_DT] DATETIME NOT NULL,
    [SETM_CREATED_BY] VARCHAR(25) NOT NULL,
    [SETM_CREATED_DT] DATETIME NOT NULL,
    [SETM_LST_UPD_BY] VARCHAR(25) NOT NULL,
    [SETM_LST_UPD_DT] DATETIME NOT NULL,
    [SETM_DELETED_IND] SMALLINT NOT NULL
);

GO
