-- Object: TABLE citrus_usr.CONCM_HST
-- Server: 10.253.33.190 | DB: DMAT
--------------------------------------------------

CREATE TABLE [citrus_usr].[CONCM_HST]
(
    [CONCM_ID] NUMERIC(10, 0) NOT NULL,
    [CONCM_CD] VARCHAR(20) NOT NULL,
    [CONCM_DESC] VARCHAR(100) NULL,
    [CONCM_CLI_YN] INT NOT NULL,
    [CONCM_RMKS] VARCHAR(250) NULL,
    [CONCM_CREATED_BY] VARCHAR(25) NOT NULL,
    [CONCM_CREATED_DT] DATETIME NOT NULL,
    [CONCM_LST_UPD_BY] VARCHAR(25) NOT NULL,
    [CONCM_LST_UPD_DT] DATETIME NOT NULL,
    [CONCM_DELETED_IND] SMALLINT NOT NULL,
    [CONCM_ACTION] VARCHAR(20) NOT NULL
);

GO
