-- Object: TABLE citrus_usr.DEMRD_MAK
-- Server: 10.253.33.190 | DB: DMAT
--------------------------------------------------

CREATE TABLE [citrus_usr].[DEMRD_MAK]
(
    [DEMRD_ID] NUMERIC(10, 0) NOT NULL,
    [DEMRD_DEMRM_ID] NUMERIC(10, 0) NOT NULL,
    [DEMRD_FOLIO_NO] VARCHAR(20) NOT NULL,
    [DEMRD_CERT_NO] VARCHAR(20) NOT NULL,
    [DEMRD_DISTINCTIVE_NO_FR] VARCHAR(20) NOT NULL,
    [DEMRD_DISTINCTIVE_NO_TO] VARCHAR(20) NOT NULL,
    [DEMRD_QTY] NUMERIC(19, 5) NULL,
    [DEMRD_STATUS] VARCHAR(20) NULL,
    [DEMRD_REJ_CD] VARCHAR(20) NULL,
    [DEMRD_RMKS] VARCHAR(200) NULL,
    [DEMRD_CREATED_BY] VARCHAR(20) NOT NULL,
    [DEMRD_CREATED_DT] DATETIME NOT NULL,
    [DEMRD_LST_UPD_BY] VARCHAR(20) NOT NULL,
    [DEMRD_LST_UPD_DT] DATETIME NOT NULL,
    [DEMRD_DELETED_IND] SMALLINT NOT NULL
);

GO
