-- Object: VIEW citrus_usr.Bank_master
-- Server: 10.253.33.190 | DB: DMAT
--------------------------------------------------


 CREATE VIEW [citrus_usr].[Bank_master]

 AS

 SELECT  '1' AS BK_ID,BANM_MICR AS BK_MICR,
 (CASE WHEN BANM_BRANCH= BANM_MICR THEN banm_rtgs_cd ELSE  BANM_BRANCH END)AS BK_BRANCH,BANM_NAME AS BK_NAME, 
 TMPBA_DP_BANK_ADD1 AS BK_ADD1,TMPBA_DP_BANK_ADD2 AS BK_ADD2,TMPBA_DP_BANK_ADD3 AS BK_ADD3,
 TMPBA_DP_BANK_CITY AS BK_CITY,TMPBA_DP_BANK_STATE AS BK_STATE,TMPBA_DP_BANK_CNTRY AS BK_COUNTRY,
 TMPBA_DP_BANK_ZIP AS BK_PIN ,TMPBA_DP_BANK_PH1 AS BK_TELE1,TMPBA_DP_BANK_PH2 AS BK_TELE2,
 TMPBA_DP_BANK_FAX AS BK_FAX,TMPBA_DP_BANK_EMAIL AS BK_EMAIL,
 TMPBA_DP_BANK_CONNAME BK_CONNAME,TMPBA_DP_BANK_CONDESG AS BK_CONDESG
 FROM  BANK_MSTR B,bank_addresses_dtls S
 WHERE BANM_MICR= TMPBA_DP_BANK  AND (CASE WHEN BANM_BRANCH = BANM_MICR THEN banm_rtgs_cd ELSE  BANM_BRANCH END) = TMPBA_DP_BR  
 AND BANM_DELETED_IND =1

GO
