-- Object: TABLE citrus_usr.FIN_ACCOUNT_MSTR_MAK
-- Server: 10.253.33.190 | DB: DMAT
--------------------------------------------------

CREATE TABLE [citrus_usr].[FIN_ACCOUNT_MSTR_MAK]
(
    [FINA_ACC_ID] NUMERIC(10, 0) NULL,
    [FINA_ACC_CODE] VARCHAR(20) NULL,
    [FINA_ACC_NAME] VARCHAR(50) NULL,
    [FINA_ACC_TYPE] CHAR(1) NULL,
    [FINA_GROUP_ID] INT NULL,
    [FINA_BRANCH_ID] INT NULL,
    [FINA_DPM_ID] NUMERIC(10, 0) NULL,
    [FINA_CREATED_BY] VARCHAR(25) NULL,
    [FINA_CREATED_DT] DATETIME NULL,
    [FINA_LST_UPD_BY] VARCHAR(25) NULL,
    [FINA_LST_UPD_DT] DATETIME NULL,
    [FINA_DELETED_IND] SMALLINT NULL
);

GO
