-- Object: TABLE dbo.CLIENTMASTER_Spark_Hst
-- Server: 10.253.33.190 | DB: DMAT
--------------------------------------------------

CREATE TABLE [dbo].[CLIENTMASTER_Spark_Hst]
(
    [Cl_Code] INT IDENTITY(1,1) NOT NULL,
    [Cl_Name] VARCHAR(100) NULL,
    [Birth_Date] DATETIME NULL,
    [Sex] CHAR(1) NULL,
    [Category] INT NULL,
    [Category_desc] VARCHAR(40) NULL,
    [Contract_Type] CHAR(1) NULL,
    [Employer_Name] VARCHAR(40) NULL,
    [Guardian_Name] VARCHAR(40) NULL,
    [Agreement_Date] DATETIME NULL,
    [Commecement_Date] DATETIME NOT NULL,
    [Setteled_Through] VARCHAR(40) NOT NULL,
    [Custodiancode] VARCHAR(16) NULL,
    [P_Addr1] VARCHAR(50) NOT NULL,
    [P_Addr2] VARCHAR(50) NULL,
    [P_Addr3] VARCHAR(50) NULL,
    [P_city] VARCHAR(20) NULL,
    [P_State] CHAR(30) NULL,
    [P_Nation] CHAR(15) NULL,
    [P_Zip] CHAR(6) NULL,
    [P_Phone1] VARCHAR(15) NULL,
    [P_Phone2] VARCHAR(15) NULL,
    [C_Addr1] VARCHAR(50) NOT NULL,
    [C_Addr2] VARCHAR(50) NULL,
    [C_Addr3] VARCHAR(50) NULL,
    [C_city] VARCHAR(20) NULL,
    [C_State] CHAR(30) NULL,
    [C_Nation] CHAR(15) NULL,
    [C_Zip] CHAR(6) NULL,
    [C_Phone1] VARCHAR(15) NULL,
    [C_Phone2] VARCHAR(15) NULL,
    [Fax_no] VARCHAR(15) NULL,
    [Mobile_Pager] VARCHAR(15) NULL,
    [Email_1] VARCHAR(40) NULL,
    [Email_2] VARCHAR(40) NULL,
    [Email_3] VARCHAR(40) NULL,
    [Contactperson] VARCHAR(40) NOT NULL,
    [Designation] VARCHAR(25) NULL,
    [Reg_Doc_Type] VARCHAR(35) NOT NULL,
    [Reg_No] VARCHAR(25) NULL,
    [Reg_Authority] VARCHAR(40) NULL,
    [Reg_Palce] VARCHAR(20) NULL,
    [Reg_Date] DATETIME NULL,
    [Other_Document] VARCHAR(100) NULL,
    [Introducer_code] VARCHAR(12) NULL,
    [Introducer_Name] VARCHAR(40) NULL,
    [Introducer_Category] INT NULL,
    [Introducer_Cat_Desc] VARCHAR(20) NULL,
    [Introducer_Relation] VARCHAR(25) NULL,
    [Client_Relation] VARCHAR(25) NULL,
    [RM_Type] VARCHAR(1) NOT NULL,
    [RM_Code] VARCHAR(12) NOT NULL,
    [Branch_cd] CHAR(10) NOT NULL,
    [Family_Code] VARCHAR(60) NULL,
    [Group1] VARCHAR(20) NOT NULL,
    [Group2] VARCHAR(20) NOT NULL,
    [Group3] VARCHAR(20) NOT NULL,
    [InactiveFrom] DATETIME NOT NULL,
    [processed_by] CHAR(2) NOT NULL,
    [InvestorCode] VARCHAR(50) NULL,
    [Sebi_No] VARCHAR(50) NULL,
    [Pan_No] VARCHAR(50) NULL,
    [FundMgrCode] VARCHAR(50) NULL,
    [Contact_Addr] VARCHAR(50) NULL,
    [consolidation_base] VARCHAR(1) NULL,
    [AccountSettlement] VARCHAR(1) NULL,
    [RunningAccount] VARCHAR(1) NULL,
    [Created_by] VARCHAR(100) NULL,
    [created_Dt] DATETIME NULL,
    [lst_upd_by] VARCHAR(100) NULL,
    [lst_upd_dt] DATETIME NULL,
    [changed] CHAR(2) NULL,
    [migrate_yn] CHAR(2) NULL
);

GO
