-- Object: VIEW dbo.Synergy_CLIENT_MASTER
-- Server: 10.253.78.167 | DB: inhouse
--------------------------------------------------

   
  
CREATE view [dbo].[Synergy_CLIENT_MASTER]    
As    
/*select * from dmat.citrus_usr.Synergy_CLIENT_MASTER  */
  select  CM_CD,ltrim(rtrim(CM_NAME)) + ' ' + ltrim(rtrim(CM_MIDDLENAME)) + ' ' + ltrim(rtrim(CM_LASTNAME)) as CM_NAME,CM_TITLE,CM_SUFFIX,CM_ADD1,CM_ADD2,CM_ADD3,CM_CITY,CM_STATE,CM_COUNTRY,CM_PIN,CM_PHONEINDICATOR,CM_TELE1,CM_PHONEINDICATOR2,CM_TELE2,CM_TELE3,CM_FAX,CM_MOBILE,CM_ITCIRCLE,CM_EMAIL,CM_SECH_NAME,CM_THIH_NAME,CM_DATEOFMATURITY,CM_DPINTREFNO,CM_DATEOFBIRTH,CM_OCCUPATION,CM_ACCTYPE,CM_ACTIVE,CM_CLIENTTYPE,CM_CONFIRMATIONWAIVED,CM_SECURITYCODE,CM_RBIREFNO,CM_RBIAPPDATE,CM_SEBIREGNO,CM_TAXDEDUCTION,CM_CCID,CM_CMID,CM_STOCKEXCHANGE,CM_TRADINGID,CM_BOSTATEMENTCYCLE,CM_MICR,CM_BANKNAME,CM_BANKBRANCHNO,CM_BANKACTNO,CM_BANKCCY,CM_DIVBANKCODE,CM_DIVBRANCHNO,CM_DIVBANKACNO,CM_DIVBANKCCY,CM_POAID,CM_POANAME,CM_PWD,CM_OPENDATE,CM_ACC_CLOSUREDATE,CM_BRCODE,CM_BRBOFFCODE,CM_GROUPCD,CM_FAMILYCD,CM_CHGSSCHEME,CM_BILLCYCLE,CM_STATEMENTS,CM_BILLFLAG,CM_BILLCODE,CM_COLLECTIONCODE,CM_ALLOWCREDIT,CM_UPFRONt,CM_LASTBILL,CM_KEEPSETTLEMENT,CM_FRE_TRX,CM_FRE_HOLD,CM_FRE_BILL,CM_BLSAVINGCD,CM_AMTMNTDT,CM_UPDATEBAL,CM_SCHEDULE,CM_OPENINGBAL,CM_FREEZEDT,MKRDT,MKRID,CM_FREEZEYN,CM_FREEZEREASON,CM_PRODUCTCD,MKRTM,CM_REMISSER,CM_POAFORPAYIN,CM_POAREGDATE,FIRST_HOLD_UID,SECOND_HOLD_UID,THIRD_HOLD_UID,RGESS_FLAG,DIGI_ANNUAL,PSI_FLAG,RTA_FLAG,BSDA_FLAG from 
  dmat.citrus_usr.Synergy_CLIENT_MASTER

GO
