-- Object: PROCEDURE dbo.USP_ISIN_CLOSEPRICE
-- Server: 10.253.78.167 | DB: inhouse
--------------------------------------------------

CREATE PROC USP_ISIN_CLOSEPRICE    
@RATEDATE DATETIME    
AS    
  
 DECLARE  @VW_ISIN_RATE_MASTER TABLE(RATE_DATE DATETIME,ISIN VARCHAR(40),CLOSE_PRICE DECIMAL(18,2),EXCH_CODE VARCHAR(30))
 
 INSERT INTO @VW_ISIN_RATE_MASTER
 
 SELECT * FROM DMAT.CITRUS_USR.VW_ISIN_RATE_MASTER    
    
SELECT MAX(RATE_DATE) AS RATE_DATE, ISIN     
INTO #VW_ISIN_RATE_MASTER     
FROM @VW_ISIN_RATE_MASTER      
WHERE RATE_DATE <= @RATEDATE     
GROUP BY ISIN    
    
SELECT I.*, V.RATE_DATE, R.CLOSE_PRICE    
INTO #TBL_ISIN_CLOSEPRICE    
FROM    
(SELECT ISIN, COMP_NAME FROM VW_ISIN_MASTER WITH (NOLOCK)) I    
INNER JOIN #VW_ISIN_RATE_MASTER V    
ON (I.ISIN = V.ISIN)    
INNER JOIN    
@VW_ISIN_RATE_MASTER R     
ON (V.RATE_DATE = R.RATE_DATE AND V.ISIN = R.ISIN)    
    
SELECT * FROM #TBL_ISIN_CLOSEPRICE    
ORDER BY ISIN

/*
CREATE PROC USP_ISIN_CLOSEPRICE    
@RATEDATE DATETIME    
AS    
    
SELECT MAX(RATE_DATE) AS RATE_DATE, ISIN     
INTO #VW_ISIN_RATE_MASTER     
FROM VW_ISIN_RATE_MASTER WITH (NOLOCK)     
WHERE RATE_DATE <= @RATEDATE     
GROUP BY ISIN    
    
SELECT I.*, V.RATE_DATE, R.CLOSE_PRICE    
INTO #TBL_ISIN_CLOSEPRICE    
FROM    
(SELECT ISIN, COMP_NAME FROM VW_ISIN_MASTER WITH (NOLOCK)) I    
INNER JOIN #VW_ISIN_RATE_MASTER V    
ON (I.ISIN = V.ISIN)    
INNER JOIN    
VW_ISIN_RATE_MASTER R WITH (NOLOCK)    
ON (V.RATE_DATE = R.RATE_DATE AND V.ISIN = R.ISIN)    
    
SELECT * FROM #TBL_ISIN_CLOSEPRICE    
ORDER BY ISIN
*/

GO
