-- Object: TABLE dbo.SYNERGY_TRXN_DETAILS_LOG
-- Server: 10.253.78.167 | DB: inhouse
--------------------------------------------------

CREATE TABLE [dbo].[SYNERGY_TRXN_DETAILS_LOG]
(
    [TD_CURDATE] SMALLDATETIME NULL,
    [TD_AC_CODE] VARCHAR(16) NULL,
    [TD_ISIN_CODE] VARCHAR(12) NULL,
    [TD_QTY] MONEY NULL,
    [TD_CLEAR_CORPN] VARCHAR(8) NULL,
    [TD_COUNTERDP] VARCHAR(16) NULL,
    [TD_BENEFICIERY] VARCHAR(16) NULL,
    [TD_REFERENCE] VARCHAR(20) NULL,
    [TD_DESCRIPTION] VARCHAR(100) NULL,
    [TD_CATEGORY] VARCHAR(2) NULL,
    [TD_AC_TYPE] VARCHAR(4) NULL,
    [TD_NARRATION] VARCHAR(3) NULL,
    [TD_BOOKING_TYPE] VARCHAR(2) NULL,
    [TD_MARKET_TYPE] VARCHAR(2) NULL,
    [TD_SETTLEMENT] VARCHAR(13) NULL,
    [TD_BLOCKED] VARCHAR(1) NULL,
    [TD_BLOCKEDCD] VARCHAR(2) NULL,
    [TD_RDATE] VARCHAR(8) NULL,
    [TD_TRXDATE] VARCHAR(8) NULL,
    [TD_TRXTIME] VARCHAR(10) NULL,
    [TD_DEBIT_CREDIT] VARCHAR(1) NULL,
    [TD_TRXNO] VARCHAR(40) NULL,
    [TD_CHARGE_CODE] VARCHAR(2) NULL,
    [TD_RATE] NUMERIC(19, 4) NULL,
    [TD_AMOUNT] NUMERIC(19, 4) NULL,
    [TD_INTERNAL_REFNO] VARCHAR(20) NULL,
    [TD_COUNTERCMBPID] VARCHAR(8) NULL,
    [TD_TOTCERT] NUMERIC(4, 0) NULL,
    [TD_CHARGEFLAG] VARCHAR(1) NULL,
    [MKRID] VARCHAR(8) NULL,
    [MKRDT] VARCHAR(8) NULL,
    [TD_REJCODE] VARCHAR(4) NULL,
    [TD_BILLCODE] VARCHAR(16) NULL,
    [TD_CDSLCHARGE] NUMERIC(15, 2) NULL,
    [TD_PDCD] VARCHAR(2) NULL,
    [TD_PDCODE] VARCHAR(4) NULL,
    [TD_REMARKS] VARCHAR(100) NULL,
    [TD_ACTUALCDSLCHARGE] NUMERIC(15, 2) NULL,
    [UPDATE_DATETIME] DATETIME NOT NULL
);

GO
