-- Object: PROCEDURE dbo.REVERSAL_DATA
-- Server: 10.253.33.91 | DB: ACCOUNT
--------------------------------------------------

CREATE PROC [DBO].[REVERSAL_DATA]  
(  
  @FROMDATE VARCHAR(11),  
  @TODATE VARCHAR(11)  
 )           
 AS  
 BEGIN  
 SELECT DISTINCT  
 [CLTCODE] = A.CLTCODE,  
 [SHORT_NAME]= B.SHORT_NAME,  
 [REGION] = B.REGION,  
 [BRANCH] = B.BRANCH_CD,  
 [SUBBROKER] = B.SUB_BROKER,  
 [VDATE] = A.VDT,  
 [V_NO] = A.VNO,  
 [NARRATION] = A.NARRATION,  
 [VAMT] = A.VAMT,  
 [DDNO] = C.DDNO,  
 [VTYP] = A.VTYP,  
 [RELDT] = C.RELDT  
INTO  #TEMP2    
 FROM  
 LEDGER(NOLOCK) A,  
 msajag..CLIENT1(NOLOCK) B,  
 LEDGER1(NOLOCK) C  
 WHERE A.VTYP='3' AND A.VDT >= @FROMDATE AND A.VDT < =@TODATE + ' 23:59:59:999'    
 AND A.NARRATION LIKE '%REV%' AND ISNUMERIC(A.CLTCODE)  ='0' AND  
 A.CLTCODE = B.Cl_Code AND  A.VTYP = C.VTYP AND A.VNO = C.VNO  
 --AND A.CLTCODE IN (SELECT CLTCODE FROM ACMAST WHERE ACCAT=4)  
 ORDER BY A.CLTCODE  
  
 SELECT  
 [CLTCODE] = CLTCODE,  
 [ACNAME]= ACNAME,  
 [VNO] = VNO,  
 [DRCR] = DRCR   
 INTO #TEMP3  
 FROM LEDGER(NOLOCK) D  
 WHERE   
 D.VTYP='3' AND D.VDT >= @FROMDATE AND D.VDT <=@TODATE + ' 23:59:59:999'  
 AND D.VNO IN (SELECT V_NO FROM #TEMP2(NOLOCK))  
  
 SELECT B.CLTCODE,B.ACNAME,A.REGION,A.BRANCH,A.SUBBROKER,A.VDATE,A.V_NO,A.VAMT,B.DRCR,A.DDNO,A.NARRATION,A.RELDT,'NSE' AS EXCHANGE  
 FROM #TEMP2(NOLOCK) A INNER JOIN #TEMP3(NOLOCK) B ON A.V_NO=B.VNO  
   
END

GO
