-- Object: PROCEDURE dbo.RECEIPT_BANK_POSTING_bkp06July2017
-- Server: 10.253.33.91 | DB: ACCOUNT
--------------------------------------------------


CREATE PROCEDURE [dbo].[RECEIPT_BANK_POSTING_bkp06July2017]
(
	@TRANSACTION_ID VARCHAR(20), -- UNIQUE TRANSACTION NUMBER RECEIVED IN API
	@EFFECTIVE_DATE VARCHAR(20), -- RECEIPT EFFECTIVE DATE IN DD/MM/YYYY FORMAT
	@VOUCHER_DATE VARCHAR(20), -- RECEIPT VOUCHER DATE IN DD/MM/YYYY FORMAT
	@CLIENT_CODE VARCHAR(50), -- CLIENT OR GL ACCOUNT
	@AMOUNT MONEY, -- RECEIPT AMOUNT
	@NARRATION VARCHAR(234), -- RECEIPT NARRATION
	@BANK_CODE VARCHAR(10), -- BROKER BANK ACCOUNT
	@BANK_NAME VARCHAR(100), -- RECEIPT BANK NAME
	@REFERENCE_NO VARCHAR(15), -- RECEIPT REFERENCE NO
	@BRANCHCODE VARCHAR(20), -- CLIENT OR GL BRANCH CODE SPECIFIED IN BROKERS SYSTEM
	@BRANCH_NAME VARCHAR(50), -- RECEIPT BRANCH NAME
	@CHQ_MODE VARCHAR(1), -- RECEIPT CHEQUE MODE (C - CHEQUE , D - DD, I - INTERSEGMENT, N -NEFT/RTGS'
	@CHQ_DATE VARCHAR(20), -- RECEIPT CHEQUE DATE
	@CHQ_NAME VARCHAR(100), -- NAME OF CLIENT IN CASE THE RECEIVED FROM CLIENT
	@CL_MODE VARCHAR(1), -- CHEQUE CLEARING MODE
	@EXCHANGE VARCHAR(10), -- EXCHANGE FOR WHICH THE RECEIPT HAS BEEN ENTERED
	@SEGMENT VARCHAR(10),-- SEGMENT FOR WHICH THE RECEIPT HAS BEEN ENTERED
	@UNAME VARCHAR(25), -- LOGIN USER NAME
	@APIACCOUNT VARCHAR(25) -- API DETAILS SERVER
--	@APITABLE VARCHAR(25) -- APIDETAILS TABLE NAME
)
AS

DECLARE
	@@STD_DATE VARCHAR(11),
	@@LST_DATE VARCHAR(11),
	@@BRANCHFLAG AS TINYINT,
	@@VNOFLAG AS TINYINT,
	@@VNOMETHOD INT,
	@@ACNAME CHAR(100),
	@@BOOKTYPE CHAR(2),
	@@MICRNO VARCHAR(10),
	@@DRCR VARCHAR(1),
	@@VTYP SMALLINT,
	@@BANK_CODE VARCHAR(100),
	@@BACKDAYS INT,
	@@BACKDATE VARCHAR(11),
	@@SERIAL_NO INT,
	@@NEWVNO AS VARCHAR(12),
	@@MAXCOUNT AS INT,
	@@VDT AS VARCHAR(11),
	@@ERROR_COUNT AS INT,
	@@SQL AS VARCHAR(2000),
	@@MAXVNO AS INT,
	@USERCAT SMALLINT,
	@DRCR CHAR(1)
	
SET @DRCR = 'C'	

/*INSERT INTO APIDETAILS..API_PAYMENT_DETAILS
	(TRANSACTION_ID, EFFECTIVE_DATE, VOUCHER_DATE, CLIENT_CODE, AMOUNT, DRCR, NARRATION, BANK_CODE, BANK_NAME, REFERENCE_NO, BRANCHCODE, BRANCH_NAME, CHQ_MODE, CHQ_DATE, CHQ_NAME, CL_MODE, EXCHANGE, SEGMENT, UNAME, POST_DATE, ACTION_FLAG)
VALUES
(
	@TRANSACTION_ID,
	@EFFECTIVE_DATE,
	@VOUCHER_DATE,
	@CLIENT_CODE,
	@AMOUNT,
	@DRCR,
	@NARRATION,
	@BANK_CODE,
	@BANK_NAME,
	@REFERENCE_NO,
	@BRANCHCODE,
	@BRANCH_NAME,
	@CHQ_MODE,
	@CHQ_DATE,
	@CHQ_NAME,
	@CL_MODE,
	@EXCHANGE,
	@SEGMENT,
	@UNAME,
	GETDATE(),
	'I'
)*/

--SELECT @USERCAT = FLDCATEGORY FROM MSAJAG.DBO.TBLPRADNYAUSERS WHERE FLDUSERNAME = @UNAME

--BEGIN TRAN
	
CREATE TABLE #RECPAY_TABLE_TMP
(
	TRANSACTION_ID VARCHAR(20),
	SERIAL_NO INT,
	EDATE VARCHAR(20),
	VOUCHER_DATE VARCHAR(20),
	CLIENT_CODE VARCHAR(50),
	AMOUNT MONEY,
	DRCR VARCHAR(1),
	NARRATION VARCHAR(234),
	BANK_CODE VARCHAR(10),
	BANK_NAME VARCHAR(100),
	REF_NO VARCHAR(15),
	BRANCHCODE VARCHAR(20),
	BRANCH_NAME VARCHAR(50),
	CHQ_MODE VARCHAR(1),
	CHQ_DATE VARCHAR(20),
	CHQ_NAME VARCHAR(100),
	CL_MODE VARCHAR(1)
)

SELECT @@ERROR_COUNT = COUNT(1) FROM OWNER WHERE EXCHANGE = @EXCHANGE AND SEGMENT = @SEGMENT


IF @@ERROR_COUNT = 0
BEGIN
	--UPDATE APIDETAILS..API_PAYMENT_DETAILS SET POST_STATUS = 'FAIL', EXECUTION_REMARK = 'INVALID EXCHANGE SEGMENT POSTING' WHERE TRANSACTION_ID = @TRANSACTION_ID  AND ISNULL(POST_STATUS, '') = ''
	SET @@SQL = "INSERT INTO [" + @APIACCOUNT + "].APIDETAILS.DBO.API_RESULT_DETAILS"
	SET @@SQL = @@SQL + " SELECT POST_STATUS = 'FAIL', EXECUTION_REMARK = 'INVALID EXCHANGE SEGMENT POSTING', '" + @UNAME + "'"
	exec(@@SQL)
	RETURN
END

INSERT INTO #RECPAY_TABLE_TMP VALUES
(
	@TRANSACTION_ID,
	1,
	@EFFECTIVE_DATE,
	@VOUCHER_DATE,
	@CLIENT_CODE,
	@AMOUNT,
	@DRCR,
	@NARRATION,
	@BANK_CODE,
	@BANK_NAME,
	@REFERENCE_NO,
	@BRANCHCODE,
	@BRANCH_NAME,
	@CHQ_MODE,
	@CHQ_DATE,
	@CHQ_NAME,
	@CL_MODE
)

CREATE TABLE [#RECPAY_TABLE]
(
	TRANSACTION_ID VARCHAR(20),
	SERIAL_NO INT,
	EDATE VARCHAR(20),
	VOUCHER_DATE VARCHAR(20),
	CLIENT_CODE VARCHAR(50),
	AMOUNT MONEY,
	DRCR VARCHAR(1),
	NARRATION VARCHAR(234),
	BANK_CODE VARCHAR(10),
	BANK_NAME VARCHAR(100),
	REF_NO VARCHAR(15),
	BRANCHCODE VARCHAR(20),
	BRANCH_NAME VARCHAR(50),
	CHQ_MODE VARCHAR(1),
	CHQ_DATE VARCHAR(20),
	CHQ_NAME VARCHAR(100),
	CL_MODE VARCHAR(1),
	SNO INT IDENTITY (1, 1) NOT NULL ,
	VDT DATETIME NULL ,
	FYSTART DATETIME NULL ,
	FYEND DATETIME NULL ,
	UPDFLAG VARCHAR (1) NOT NULL DEFAULT('N'),
	EDT DATETIME NULL ,
	DDDT DATETIME NULL ,
	VNO VARCHAR (12) NULL ,
	VTYP SMALLINT NULL ,
	ACNAME VARCHAR (100) NULL ,
	COSTCODE SMALLINT NULL,
	BANKCOST SMALLINT NULL,
	LNO SMALLINT NOT NULL DEFAULT(0),
	BANKNAME VARCHAR(100) NULL,
	MICRNO INT NULL,
	BOOKTYPE VARCHAR(2) NULL,
) ON [PRIMARY]

INSERT INTO
 #RECPAY_TABLE
 (
  TRANSACTION_ID,
  SERIAL_NO,
  EDATE,
  VOUCHER_DATE,
  CLIENT_CODE,
  AMOUNT,
  DRCR,
  NARRATION,
  BANK_CODE,
  BANK_NAME,
  REF_NO,
  BRANCHCODE,
  BRANCH_NAME,
  CHQ_MODE,
  CHQ_DATE,
  CHQ_NAME,
  CL_MODE
 )
SELECT
 TRANSACTION_ID,
 SERIAL_NO,
 EDATE,
 VOUCHER_DATE,
 UPPER(LTRIM(RTRIM(CLIENT_CODE))),
 AMOUNT,
 UPPER(LTRIM(RTRIM(DRCR))),
 NARRATION,
 UPPER(LTRIM(RTRIM(BANK_CODE))),
 UPPER(LTRIM(RTRIM(BANK_NAME))),
 REF_NO,
 UPPER(LTRIM(RTRIM(BRANCHCODE))),
 UPPER(LTRIM(RTRIM(BRANCH_NAME))),
 UPPER(LTRIM(RTRIM(CHQ_MODE))),
 CHQ_DATE,
 CHQ_NAME,
 CL_MODE
FROM
 #RECPAY_TABLE_TMP

UPDATE
 #RECPAY_TABLE
SET
 VDT = CONVERT(DATETIME, RIGHT(VOUCHER_DATE,4) + '-' + SUBSTRING(VOUCHER_DATE,4,2) + '-' + LEFT(VOUCHER_DATE,2)),
 DDDT = CONVERT(DATETIME, RIGHT(CHQ_DATE,4) + '-' + SUBSTRING(CHQ_DATE,4,2) + '-' + LEFT(CHQ_DATE,2)),
 EDT = CONVERT(DATETIME, RIGHT(EDATE,4) + '-' + SUBSTRING(EDATE,4,2) + '-' + LEFT(EDATE,2))


SELECT TOP 1
 @@VDT = CONVERT(VARCHAR(11), VDT, 109)
FROM
 #RECPAY_TABLE


SELECT
 @@STD_DATE = CONVERT(VARCHAR(11), SDTCUR, 109),
 @@LST_DATE = CONVERT(VARCHAR(11), LDTCUR, 109),
 @@BRANCHFLAG = BRANCHFLAG,
 @@VNOFLAG = VNOFLAG
FROM
 PARAMETER
WHERE
 @@VDT BETWEEN SDTCUR AND LDTCUR

 IF @@BRANCHFLAG = 1
 BEGIN
  UPDATE
   #RECPAY_TABLE
  SET
   BRANCHCODE = A.BRANCHCODE,
   FYSTART = P.SDTCUR,
   FYEND = P.LDTCUR,
   UPDFLAG = 'Y',
   ACNAME = A.LONGNAME,
   COSTCODE = C.COSTCODE,
   BANKNAME = B.LONGNAME,
   BOOKTYPE = B.BOOKTYPE,
   MICRNO = ISNULL(B.MICRNO, 0)
  FROM
   ACMAST A, PARAMETER P, COSTMAST C, ACMAST B
  WHERE
   A.CLTCODE = CLIENT_CODE
AND B.CLTCODE = BANK_CODE
   AND P.CURYEAR = 1
   AND A.ACCAT IN ('3','4','18')
   AND B.ACCAT = '2'
   AND A.BRANCHCODE = COSTNAME

  UPDATE
   #RECPAY_TABLE
  SET
   VDT = CONVERT(DATETIME, RIGHT(VOUCHER_DATE,4) + '-' + SUBSTRING(VOUCHER_DATE,4,2) + '-' + LEFT(VOUCHER_DATE,2)),
   DDDT = CONVERT(DATETIME, RIGHT(CHQ_DATE,4) + '-' + SUBSTRING(CHQ_DATE,4,2) + '-' + LEFT(CHQ_DATE,2)),
   EDT = CONVERT(DATETIME, RIGHT(EDATE,4) + '-' + SUBSTRING(EDATE,4,2) + '-' + LEFT(EDATE,2)),
   FYSTART = P.SDTCUR,
   FYEND = P.LDTCUR,
   UPDFLAG = 'Y',
   ACNAME = A.LONGNAME,
   COSTCODE = (SELECT TOP 1 COSTCODE FROM COSTMAST WHERE COSTNAME = #RECPAY_TABLE.BRANCHCODE)  ,
   BANKNAME = B.LONGNAME,
   BOOKTYPE = B.BOOKTYPE,
   MICRNO = ISNULL(B.MICRNO, 0)
  FROM
   ACMAST A, PARAMETER P, COSTMAST C, ACMAST B
  WHERE
   A.CLTCODE = CLIENT_CODE
   AND B.CLTCODE = BANK_CODE
   AND P.CURYEAR = 1
   AND A.ACCAT IN ('3','4','18')
   AND B.ACCAT = '2'
   AND A.BRANCHCODE = 'ALL'
   AND #RECPAY_TABLE.BRANCHCODE <> 'ALL'

  UPDATE
   #RECPAY_TABLE
  SET
   BRANCHCODE = 'HO',
   VDT = CONVERT(DATETIME, RIGHT(VOUCHER_DATE,4) + '-' + SUBSTRING(VOUCHER_DATE,4,2) + '-' + LEFT(VOUCHER_DATE,2)),
   DDDT = CONVERT(DATETIME, RIGHT(CHQ_DATE,4) + '-' + SUBSTRING(CHQ_DATE,4,2) + '-' + LEFT(CHQ_DATE,2)),
   EDT = CONVERT(DATETIME, RIGHT(EDATE,4) + '-' + SUBSTRING(EDATE,4,2) + '-' + LEFT(EDATE,2)),
   FYSTART = P.SDTCUR,
   FYEND = P.LDTCUR,
   UPDFLAG = 'Y',
   ACNAME = A.LONGNAME,
   COSTCODE = (SELECT TOP 1 COSTCODE FROM COSTMAST WHERE COSTNAME = 'HO')  ,
   BANKNAME = B.LONGNAME,
   BOOKTYPE = B.BOOKTYPE,
   MICRNO = ISNULL(B.MICRNO, 0)
  FROM
   ACMAST A, PARAMETER P, COSTMAST C, ACMAST B
  WHERE
   A.CLTCODE = CLIENT_CODE
   AND B.CLTCODE = BANK_CODE
   AND P.CURYEAR = 1
   AND A.ACCAT IN ('3','4','18')
   AND B.ACCAT = '2'
   AND A.BRANCHCODE = 'ALL'
   AND #RECPAY_TABLE.BRANCHCODE = 'ALL'
 END
ELSE
 BEGIN
  UPDATE
   #RECPAY_TABLE
  SET
   FYSTART = @@STD_DATE,
   FYEND = @@LST_DATE + ' 23:59:59',
   UPDFLAG = 'Y',
   ACNAME = A.LONGNAME,
   BANKNAME = B.LONGNAME,
   BOOKTYPE = B.BOOKTYPE,
   MICRNO = ISNULL(B.MICRNO, 0)
  FROM
   ACMAST A, ACMAST B
  WHERE
   A.CLTCODE = CLIENT_CODE
   AND B.CLTCODE = BANK_CODE
   AND A.ACCAT IN ('3','4','18')
   AND B.ACCAT = '2'
 END


 UPDATE R
  SET VTYP =
 CASE WHEN AMOUNT1 > 0 THEN 3 ELSE 2 END
 FROM (SELECT AMOUNT1 = SUM(CASE DRCR WHEN 'D' THEN AMOUNT ELSE -AMOUNT END), SERIAL_NO FROM #RECPAY_TABLE GROUP BY SERIAL_NO) R1, #RECPAY_TABLE R
 WHERE R.SERIAL_NO = R1.SERIAL_NO
 
 SELECT @@VTYP = VTYP FROM #RECPAY_TABLE

/*--------------------------VALIDATION FOR VOUCHER DATE GRATER THAN EFFECTIVE DATE ------------------------*/
SELECT
	@@ERROR_COUNT = COUNT(1)
FROM
	#RECPAY_TABLE
WHERE
	VDT > EDT

IF @@ERROR_COUNT > 0
BEGIN
	SET @@SQL = "INSERT INTO [" + @APIACCOUNT + "].APIDETAILS.DBO.API_RESULT_DETAILS"
	SET @@SQL = @@SQL + " SELECT POST_STATUS = 'FAIL', EXECUTION_REMARK = 'VOUHER DATE CAN NOT BE GRATER THAT EFFECTIVE DATE.', '" + @UNAME + "'"
	EXEC(@@SQL)
	DROP TABLE #RECPAY_TABLE_TMP
	DROP TABLE #RECPAY_TABLE
--	ROLLBACK TRAN
--	UPDATE APIDETAILS..API_PAYMENT_DETAILS SET POST_STATUS = 'FAIL', EXECUTION_REMARK = 'VOUHER DATE CAN NOT BE GRATER THAT EFFECTIVE DATE.' WHERE TRANSACTION_ID = @TRANSACTION_ID  AND ISNULL(POST_STATUS, '') = ''
	RETURN
END

/*--------------------------VALIDATION FOR ZERO AMOUNT ------------------------*/
IF @AMOUNT <= 0
BEGIN
	SET @@SQL = "INSERT INTO [" + @APIACCOUNT + "].APIDETAILS.DBO.API_RESULT_DETAILS"
	SET @@SQL = @@SQL + " SELECT POST_STATUS = 'FAIL', EXECUTION_REMARK = 'VOUHER AMOUNT SHOULD BE ALWAY GRATER THAN 0', '" + @UNAME + "'"
	EXEC(@@SQL)
	DROP TABLE #RECPAY_TABLE_TMP
	DROP TABLE #RECPAY_TABLE
--	ROLLBACK TRAN
--	UPDATE APIDETAILS..API_PAYMENT_DETAILS SET POST_STATUS = 'FAIL', EXECUTION_REMARK = 'VOUHER AMOUNT SHOULD BE ALWAY GRATER THAN 0' WHERE TRANSACTION_ID = @TRANSACTION_ID  AND ISNULL(POST_STATUS, '') = ''
	RETURN
END


/*--------------------------VALIDATION FOR BLANK CHEQUE NUMBER ------------------------*/
SELECT
@@ERROR_COUNT = COUNT(1)
FROM
(
	SELECT DISTINCT
		 RP.REF_NO
	FROM
		#RECPAY_TABLE RP
		 WITH(NOLOCK)
	  where isnull(RP.REF_NO,'')=''
) A

IF @@ERROR_COUNT > 0
BEGIN
	SET @@SQL = "INSERT INTO [" + @APIACCOUNT + "].APIDETAILS.DBO.API_RESULT_DETAILS"
	SET @@SQL = @@SQL + " SELECT POST_STATUS = 'FAIL', EXECUTION_REMARK = 'CHEQUE NUMBER IS BLANK', '" + @UNAME + "'"
	EXEC(@@SQL)
	DROP TABLE #RECPAY_TABLE_TMP
	DROP TABLE #RECPAY_TABLE
--	ROLLBACK TRAN
--	UPDATE APIDETAILS..API_PAYMENT_DETAILS SET POST_STATUS = 'FAIL', EXECUTION_REMARK = 'CHEQUE NUMBER ALREADY EXISTS' WHERE TRANSACTION_ID = @TRANSACTION_ID  AND ISNULL(POST_STATUS, '') = ''
	RETURN
END

/*--------------------------VALIDATION FOR DUPLICATE CHEQUE NUMBER ------------------------*/
SELECT
@@ERROR_COUNT = COUNT(1)
FROM
(
	SELECT DISTINCT
		DDNO  = RP.REF_NO
	FROM
		#RECPAY_TABLE RP,
		LEDGER1 L1  WITH(NOLOCK)
	WHERE
		L1.DDNO = RP.REF_NO
		AND L1.DD = RP.CHQ_MODE
		AND L1.DRCR = @DRCR
		AND L1.VTYP = @@VTYP
		AND RP.REF_NO <> '0'
		AND ISNUMERIC(RP.REF_NO) = 1
) A


IF @@ERROR_COUNT > 0
BEGIN
	SET @@SQL = "INSERT INTO [" + @APIACCOUNT + "].APIDETAILS.DBO.API_RESULT_DETAILS"
	SET @@SQL = @@SQL + " SELECT POST_STATUS = 'FAIL', EXECUTION_REMARK = 'CHEQUE NUMBER ALREADY EXISTS', '" + @UNAME + "'"
	EXEC(@@SQL)
	DROP TABLE #RECPAY_TABLE_TMP
	DROP TABLE #RECPAY_TABLE
--	ROLLBACK TRAN
--	UPDATE APIDETAILS..API_PAYMENT_DETAILS SET POST_STATUS = 'FAIL', EXECUTION_REMARK = 'CHEQUE NUMBER ALREADY EXISTS' WHERE TRANSACTION_ID = @TRANSACTION_ID  AND ISNULL(POST_STATUS, '') = ''
	RETURN
END

/*--------------------------FINAL VALIDATION BASED ON UPDFLAG ------------------------*/
SELECT
 @@ERROR_COUNT = COUNT(1)
FROM
 (
  SELECT DISTINCT
   CLIENT_CODE
  FROM
   #RECPAY_TABLE
  WHERE
   UPDFLAG = 'N'
 ) A
IF @@ERROR_COUNT > 0
 BEGIN
	SET @@SQL = "INSERT INTO [" + @APIACCOUNT + "].APIDETAILS.DBO.API_RESULT_DETAILS"
	SET @@SQL = @@SQL + " SELECT POST_STATUS = 'FAIL', EXECUTION_REMARK = 'CLIENTS DO NOT EXIST', '" + @UNAME + "'"
	EXEC(@@SQL)
	DROP TABLE #RECPAY_TABLE_TMP
	DROP TABLE #RECPAY_TABLE
--	ROLLBACK TRAN
--	UPDATE APIDETAILS..API_PAYMENT_DETAILS SET POST_STATUS = 'FAIL', EXECUTION_REMARK = 'CLIENTS DO NOT EXIST' WHERE TRANSACTION_ID = @TRANSACTION_ID  AND ISNULL(POST_STATUS, '') = ''
	RETURN
 END


---------------------------VALIDATION FOR INACTIVE CLIENTS FROM CLIENT5---------------------
	UPDATE
		#RECPAY_TABLE
		SET UPDFLAG = 'N'
	FROM ( SELECT
		PARTY_CODE,
		INACTIVEFROM
	FROM MSAJAG.DBO.CLIENT5 C5 WITH(NOLOCK),
		MSAJAG.DBO.CLIENT2 C2 WITH(NOLOCK)
	WHERE C2.CL_CODE = C5.CL_CODE
		AND C2.PARTY_CODE IN (SELECT CLIENT_CODE FROM #RECPAY_TABLE)
		AND INACTIVEFROM <= GETDATE()) C
	WHERE CLIENT_CODE = C.PARTY_CODE


SELECT
 @@ERROR_COUNT = COUNT(1)
FROM
 (
  SELECT DISTINCT
   CLIENT_CODE
  FROM
   #RECPAY_TABLE
  WHERE
   UPDFLAG = 'N'
 ) A
IF @@ERROR_COUNT > 0
 BEGIN
	SET @@SQL = "INSERT INTO [" + @APIACCOUNT + "].APIDETAILS.DBO.API_RESULT_DETAILS"
	SET @@SQL = @@SQL + " SELECT POST_STATUS = 'FAIL', EXECUTION_REMARK = 'CLIENTS IS INACTIVE', '" + @UNAME + "'"
	EXEC(@@SQL)
	DROP TABLE #RECPAY_TABLE_TMP
	DROP TABLE #RECPAY_TABLE
--	ROLLBACK TRAN
--	UPDATE APIDETAILS..API_PAYMENT_DETAILS SET POST_STATUS = 'FAIL', EXECUTION_REMARK = 'CLIENTS IS INACTIVE' WHERE TRANSACTION_ID = @TRANSACTION_ID  AND ISNULL(POST_STATUS, '') = ''
	RETURN
 END

 SELECT @@BOOKTYPE = BOOKTYPE FROM ACMAST WHERE CLTCODE = @BANK_CODE


/*SELECT
	@@BACKDAYS = ISNULL(MAX(NODAYS), 0)
FROM
	USERWRITESTABLE
WHERE
	USERCATEGORY = @USERCAT
	AND VTYP = @@VTYP
	AND BOOKTYPE = @@BOOKTYPE

SELECT
	@@BACKDATE = CONVERT(DATETIME, CONVERT(VARCHAR(11), GETDATE(), 109)) - @@BACKDAYS

SELECT
	@@ERROR_COUNT = ISNULL(COUNT(VDT), 0)
FROM
	#RECPAY_TABLE
WHERE
	VDT < @@BACKDATE

IF @@ERROR_COUNT > 0
BEGIN
	SET @@SQL = "INSERT INTO [" + @APIACCOUNT + "].APIDETAILS.DBO.API_RESULT_DETAILS"
	SET @@SQL = @@SQL + " SELECT POST_STATUS = 'FAIL', EXECUTION_REMARK = 'VOUCHERS ARE HAVING BACK DATED VOUCHER DATES FOR WHICH RIGHTS HAVE NOT BEEN SET', '" + @UNAME + "'"
	EXEC(@@SQL)
	DROP TABLE #RECPAY_TABLE_TMP
	DROP TABLE #RECPAY_TABLE
--	ROLLBACK TRAN
--	UPDATE APIDETAILS..API_PAYMENT_DETAILS SET POST_STATUS = 'FAIL', EXECUTION_REMARK = 'VOUCHERS ARE HAVING BACK DATED VOUCHER DATES FOR WHICH RIGHTS HAVE NOT BEEN SET' WHERE TRANSACTION_ID = @TRANSACTION_ID  AND ISNULL(POST_STATUS, '') = ''
	RETURN
END
*/


CREATE TABLE #BANK_VNO
(
	SRNO INT,
	NEWSRNO INT IDENTITY (1, 1)
)

INSERT INTO
	#BANK_VNO
SELECT
	DISTINCT SERIAL_NO
FROM
	#RECPAY_TABLE

SELECT
	@@MAXCOUNT = COUNT(DISTINCT SNO)
FROM
	#RECPAY_TABLE

SELECT TOP 1
	@@VDT = VDT
FROM
	#RECPAY_TABLE

SELECT
	LASTVNO
INTO
	#VNO
FROM
	LASTVNO
WHERE
	1 = 2

SELECT @@MAXVNO = MAX(NEWSRNO) FROM #BANK_VNO

INSERT
	INTO #VNO
EXEC ACC_GENVNO_NEW
	@@VDT,
	@@VTYP,
	@@BOOKTYPE,
	@@STD_DATE,
	@@LST_DATE,
	@@MAXVNO

SELECT
	@@NEWVNO = LASTVNO
FROM
	#VNO

UPDATE
	RP
SET
	VNO = CONVERT(VARCHAR(12),CONVERT(NUMERIC,@@NEWVNO) + (NEWSRNO - 1))
FROM
	#RECPAY_TABLE RP,
	#BANK_VNO BV
WHERE
	RP.SERIAL_NO = BV.SRNO

DROP TABLE #VNO
DROP TABLE #BANK_VNO

/*   --------------------------AUTO GENERATION OF LNO ------------------------ */
UPDATE
	#RECPAY_TABLE
SET
	LNO = 2
WHERE
	VNO IN
	(
		SELECT
		VNO
		FROM
		#RECPAY_TABLE
		WITH(NOLOCK)
		GROUP BY
		VNO
		HAVING
		COUNT(*) = 1
	)


INSERT INTO
 LEDGER1
  (
   BNKNAME,
   BRNNAME,
   DD,
   DDNO,
   DDDT,
   RELDT,
   RELAMT,
   REFNO,
   RECEIPTNO,
   VTYP,
   VNO,
   LNO,
   DRCR,
   BOOKTYPE,
   MICRNO,
   SLIPNO,
   SLIPDATE,
   CHEQUEINNAME,
   CHQPRINTED,
   CLEAR_MODE
  )
SELECT
 BNKNAME = MAX(BANK_NAME),
 BRNNAME = MAX(BRANCH_NAME),
 DD = MAX(CHQ_MODE),
 DDNO = MAX(REF_NO),
 DDDT = MAX(DDDT),
 RELDT = '',
 RELAMT = ABS(SUM(CASE DRCR WHEN 'C' THEN AMOUNT ELSE -AMOUNT END)),
 REFNO = 0,
 RECEIPTNO = 0,
 VTYP,
 VNO,
 LNO = 2,
 @DRCR,
 BOOKTYPE = BOOKTYPE,
 MICRNO = MICRNO,
 SLIPNO = 0,
 SLIPDATE = '',
 CHEQUEINNAME = MAX(ISNULL(CHQ_NAME,'')),
 CHQPRINTED = 0,
 CLEAR_MODE = MAX(CL_MODE)
FROM
 #RECPAY_TABLE
GROUP BY
 VTYP,
 VNO,
 BOOKTYPE,
 MICRNO


 CREATE TABLE #LEDGER
(
 VTYP SMALLINT,
 VNO VARCHAR(12),
 EDT DATETIME,
 LNO SMALLINT,
 ACNAME VARCHAR(100),
 DRCR VARCHAR(1),
 VAMT MONEY,
 VDT DATETIME,
 VNO1 VARCHAR(12),
 REFNO CHAR(12),
 BALAMT MONEY,
 NODAYS INT,
 CDT DATETIME,
 CLTCODE VARCHAR(10),
 BOOKTYPE VARCHAR(2),
 ENTEREDBY VARCHAR(25),
 PDT DATETIME,
 CHECKEDBY VARCHAR(25),
 ACTNODAYS INT,
 NARRATION VARCHAR(234)
)    --SELECT VTYP, VNO,  EDT, LNO, ACNAME, DRCR, VAMT, VDT, VNO1, REFNO, BALAMT, NODAYS, CDT, CLTCODE, BOOKTYPE, ENTEREDBY, PDT, CHECKEDBY, ACTNODAYS, NARRATION INTO #LEDGER FROM LEDGER WHERE 1 = 0
CREATE TABLE #LEDGER3
(
 NARATNO INT,
 NARR VARCHAR(234),
 REFNO CHAR(12),
 VTYP SMALLINT,
 VNO VARCHAR(12),
 BOOKTYPE VARCHAR(2)
)
--SELECT * INTO #LEDGER3 FROM LEDGER3 WHERE 1 = 0
/*==============================
CLIENT SIDE RECORD
==============================*/
INSERT INTO
 #LEDGER
 (
  VTYP,
  VNO,
  EDT,
  LNO,
  ACNAME,
  DRCR,
  VAMT,
  VDT,
  VNO1,
  REFNO,
  BALAMT,
  NODAYS,
  CDT,
  CLTCODE,
  BOOKTYPE,
  ENTEREDBY,
  PDT,
  CHECKEDBY,
  ACTNODAYS,
  NARRATION
 )
SELECT
 VTYP,
 VNO,
 EDT = edt,--(CASE WHEN VTYP = 2 THEN 'DEC 31 2049' ELSE EDT END),
 LNO,
 ACNAME,
 DRCR,
 VAMT = AMOUNT,
 VDT,
 VNO1 = VNO,
 REFNO = 0,
 BALAMT = AMOUNT,
 NODAYS = 0,
 CDT = GETDATE(),
 CLTCODE = CLIENT_CODE,
 BOOKTYPE = BOOKTYPE,
 ENTEREDBY = 'B_' + LEFT(@UNAME, 23),
 PDT = GETDATE(),
 CHECKEDBY = @UNAME,
 ACTNODAYS = 0,
 NARRATION
FROM
 #RECPAY_TABLE
/*==============================
BANK SIDE RECORD
==============================*/
INSERT INTO
 #LEDGER
SELECT  DISTINCT
 VTYP,
 VNO,
 EDT = edt, --(CASE WHEN VTYP = 2 THEN 'DEC 31 2049' ELSE EDT END),
 LNO = 1,
 BANKNAME,
 MAX(DRCR1),
 VAMT = ABS(MAX(AMOUNT1)),
 VDT,
 VNO1 = VNO,
 REFNO = 0,
 BALAMT = ABS(MAX(AMOUNT1)),
 NODAYS = 0,
 CDT = GETDATE(),
 CLTCODE = BANK_CODE,
 BOOKTYPE = BOOKTYPE,
 ENTEREDBY = 'B_' + LEFT(@UNAME, 23),
 PDT = GETDATE(),
 CHECKEDBY = @UNAME,
 ACTNODAYS = 0,
 NARRATION = NARRATION_FIN
FROM
 #RECPAY_TABLE R, (SELECT SERIAL_NO, AMOUNT1 = SUM(CASE DRCR WHEN 'D' THEN AMOUNT ELSE -AMOUNT END), DRCR1 = CASE WHEN SUM(CASE DRCR WHEN 'D' THEN AMOUNT ELSE -AMOUNT END) > 0 THEN 'C' ELSE 'D' END, NARRATION_FIN = MAX(NARRATION) FROM #RECPAY_TABLE GROUP 
BY SERIAL_NO) R1
WHERE R.SERIAL_NO = R1.SERIAL_NO
GROUP BY
 VTYP,
 VNO,
 EDT,
 VDT,
 BANK_CODE,
 BOOKTYPE,
 BANKNAME,
 LNO,
 NARRATION_FIN
/*==============================
INSERTING ALL LEDGER RECORDS AT ONE TIME
==============================*/

INSERT INTO LEDGER  SELECT
 Vtyp,Vno,Edt,Lno,Acname,Drcr,Vamt,Vdt,Vno1,Refno,Balamt,Nodays,Cdt,Cltcode,Booktype,Enteredby,Pdt,Checkedby,Actnodays,Narration
FROM
 #LEDGER
ORDER BY
 BOOKTYPE,
 VTYP,
 VNO,
 LNO


           INSERT INTO
 #LEDGER3
SELECT
 NARATNO = 1,
 NARRATION = MAX(NARRATION),
 REFNO = 0,
 VTYP,
 VNO,
 BOOKTYPE
FROM
 #RECPAY_TABLE
GROUP BY
 VTYP,
 VNO,
 BOOKTYPE
/*==============================
CLIENT SIDE RECORD
==============================*/
INSERT INTO
 #LEDGER3
SELECT
 NARATNO = LNO,
 NARR = NARRATION,
 REFNO = 0,
 VTYP,
 VNO,
 BOOKTYPE
FROM
 #RECPAY_TABLE

 /*==============================
INSERTING ALL LEDGER3 RECORDS AT ONE TIME
==============================*/
INSERT INTO LEDGER3
SELECT
 *
FROM
 #LEDGER3
ORDER BY
 BOOKTYPE,
 VTYP,
 VNO,
 NARATNO
 
SET @@SQL = "INSERT INTO [" + @APIACCOUNT + "].APIDETAILS.DBO.API_RESULT_DETAILS"
SET @@SQL = @@SQL + " SELECT POST_STATUS = 'SUCCESS', EXECUTION_REMARK = VNO + '|' + CONVERT(VARCHAR, " + CONVERT(VARCHAR, @@VTYP) + ") + '|' + BOOKTYPE + '|' + CLIENT_CODE + '|' + BANK_CODE + '|' + CONVERT(VARCHAR, AMOUNT), '" + @UNAME + "' FROM #RECPAY_
TABLE"
EXEC(@@SQL)

/*UPDATE RD SET POST_STATUS = 'SUCCESS', EXECUTION_REMARK = VNO 
FROM APIDETAILS..API_PAYMENT_DETAILS RD, #RECPAY_TABLE R
WHERE RD.TRANSACTION_ID = R.TRANSACTION_ID
AND RD.TRANSACTION_ID = @TRANSACTION_ID
AND  ISNULL(POST_STATUS, '') = ''*/

DROP TABLE #RECPAY_TABLE_TMP
DROP TABLE #RECPAY_TABLE
--COMMIT TRAN

GO
