-- Object: PROCEDURE dbo.CLS_DPC_CHARGES_RPT
-- Server: 10.253.33.91 | DB: ACCOUNT
--------------------------------------------------






CREATE PROCEDURE [dbo].[CLS_DPC_CHARGES_RPT]      
(      
 @REPORT_LEVEL VARCHAR(10),      
 @FROM_DATE VARCHAR(11),      
 @TO_DATE VARCHAR(11),      
 @FROM_PARTY VARCHAR(10),      
 @TO_PARTY VARCHAR(10),      
 @SUMMARY_FLAG BIT,      
 @SEG_EXCH VARCHAR(200),      
 @ENTITY_TYPE VARCHAR(50),      
 @STATUSID VARCHAR(20),      
 @STATUSNAME VARCHAR(50),  
 @SHOWDIFF CHAR(1) = 'N',
 @SHOWCONSOLIDATED CHAR(1) = 'N',
 @SHOWZEROBAL CHAR(1) =  'N',
 @CHEKPOSTING INT = 0     
)      
AS      
/*    
--EXEC [CLS_DPC_CHARGES_RPT] 'AREA', 'mar 1 2010', 'OCT 1 2014', '00','ZZ',0,'NSE - CAPITAL|BSE - CAPITAL','ENTITY', 'BROKER','BROKER'     

exec [CLS_DPC_CHARGES_RPT] @REPORT_LEVEL='PARTY',@FROM_DATE='01/04/2016',@TO_DATE='30/04/2016',@FROM_PARTY='CL2887',@TO_PARTY='CL2887',@SUMMARY_FLAG=0,@SEG_EXCH='NSE - FUTURES',@ENTITY_TYPE='ENTITY',@STATUSID='Broker',@STATUSNAME='Broker',@SHOWDIFF='N'
  */    
DECLARE       
 @PIVOT_COLS VARCHAR(8000),      
 @PIVOT_VAL VARCHAR(8000),      
 
 @@SQL VARCHAR(8000)      
       
      
CREATE TABLE #DPC_CHARGES      
(      
 [DPC_DATE] [DATETIME] NULL,      
 [CLTCODE] [VARCHAR](10) NULL,      
 [LONG_NAME] [VARCHAR](100) NULL,      
 [BRANCH_CD] [VARCHAR](10) NULL,      
 [SUB_BROKER] [VARCHAR](25) NULL,      
 [TRADER] [VARCHAR](25) NULL,      
 [REGION] [VARCHAR](20) NULL,      
 [AREA] [VARCHAR](20) NULL,      
 [CL_TYPE] [VARCHAR](10) NULL,  
 [LEDGER_BALANCE] MONEY NULL,	    
 [DPC_BALANCE] [MONEY] NULL,      
 [DPC_CHARGE] [MONEY] NULL, 
 [CASH_COLLATREAL] [MONEY] NULL,      
 [NONCASH_COLLATREAL] [MONEY] NULL,      
 [MARGIN_REQ] [MONEY] NULL,      
 [DPC_PERCENTE] [MONEY] NULL,      
 [AMOUNT_REV] [MONEY] NULL,
 [PER_REV] [MONEY] NULL,      
 [MIN_BAL] [MONEY] NULL,      
 [EXCHANGE] [VARCHAR](10) NULL,      
 [SEGMENT] [VARCHAR](10) NULL,      
 [ENTITY] [VARCHAR](20) NULL,      
 [SEG_GROUP] VARCHAR(50) NULL,      
 [NET_BALANCE] MONEY NULL,      
 [NET_DPC_CHARGES] MONEY,      
 [NET_DPC_CHARGES_GLOBAL] MONEY    
)      
SET @SEG_EXCH =  REPLACE(@SEG_EXCH, ' - ', '-') 
SET @FROM_DATE =  CONVERT(vARCHAR(11),CONVERT(DATETIME,@FROM_DATE,103),109)
SET @TO_DATE =  CONVERT(vARCHAR(11),CONVERT(DATETIME,@TO_DATE,103),109)

SET @@SQL = "INSERT INTO #DPC_CHARGES "      
SET @@SQL = @@SQL + "(DPC_DATE, CLTCODE, LONG_NAME, BRANCH_CD, SUB_BROKER, TRADER, REGION, AREA, CL_TYPE, DPC_BALANCE, DPC_CHARGE,DPC_PERCENTE, AMOUNT_REV,[PER_REV],[MIN_BAL], NET_DPC_CHARGES_GLOBAL, EXCHANGE, SEGMENT, SEG_GROUP,CASH_COLLATREAL,NONCASH_COLLATREAL,MARGIN_REQ,LEDGER_BALANCE) "      
SET @@SQL = @@SQL + "SELECT "      
SET @@SQL = @@SQL + " DPC_DATE, CLTCODE = CASE WHEN '" + @REPORT_LEVEL + "' = 'PARTY' THEN CLTCODE ELSE E.ACCOUNT_CODE END, LONG_NAME = CASE WHEN '" + @REPORT_LEVEL + "' = 'PARTY' THEN LONG_NAME ELSE ACCOUNT_NAME END, BRANCH_CD, SUB_BROKER, TRADER, REGION, 
AREA, CL_TYPE, DPC_BALANCE, DPC_CHARGE=0,DPC_PERCENTE= CASE WHEN DPC_BALANCE < 0 THEN DEBIT_INT ELSE CREDIT_INT END , AMOUNT_REV=0,REVISED_PERC,MIN_BALANCE,DPC_CHARGE_GLOBAL=0,D.EXCHANGE, D.SEGMENT, D.EXCHANGE +'-'+ D.SEGMENT,CASH_COLLATREAL,NONCASH_COLLATREAL,MARGIN_REQ,LEDGER_BALANCE "      
SET @@SQL = @@SQL + "FROM "      
IF @REPORT_LEVEL = 'PARTY'      
 SET @@SQL = @@SQL + " ACCOUNT..CLS_DPC_CALCULATED D LEFT OUTER JOIN MSAJAG.DBO.ENTITY_DETAILS E ON E.ACCOUNT_CODE = CLTCODE "      
ELSE      
 SET @@SQL = @@SQL + " ACCOUNT..CLS_DPC_CALCULATED D, MSAJAG.DBO.ENTITY_DETAILS E "      
SET @@SQL = @@SQL + "WHERE "      
SET @@SQL = @@SQL + "DPC_DATE >= '" + @FROM_DATE + "' "      
SET @@SQL = @@SQL + "AND DPC_DATE <= '" + @TO_DATE + "' "      
IF @REPORT_LEVEL = 'PARTY'      
BEGIN      
 SET @@SQL = @@SQL + "AND CLTCODE BETWEEN '" + @FROM_PARTY + "' AND '" + @TO_PARTY + "' "      
END      
ELSE      
BEGIN      
 SET @@SQL = @@SQL + "AND " + @REPORT_LEVEL + " BETWEEN '" + @FROM_PARTY + "' AND '" + @TO_PARTY + "' "      
 SET @@SQL = @@SQL + "AND E.ACCOUNT_CODE = " + @REPORT_LEVEL + " "      
END      
IF @STATUSID <> 'BROKER'      
BEGIN      
 SET @@SQL = @@SQL + "AND " + @STATUSID + " = '" + @STATUSNAME + "' "      
END      
SET @@SQL = @@SQL + "AND D.EXCHANGE+'-'+ D.SEGMENT  IN ('" + REPLACE(@SEG_EXCH, '|', ''',''') + "')"      
PRINT @@SQL      
EXEC (@@SQL)     
  
    
INSERT INTO #DPC_CHARGES (CLTCODE, LONG_NAME, DPC_BALANCE, DPC_CHARGE, NET_DPC_CHARGES_GLOBAL, SEG_GROUP)    
SELECT 'ZZZZZZZZZZ', 'TOTAL', SUM(DPC_BALANCE), SUM(ROUND(DPC_CHARGE,2)),SUM(ROUND(NET_DPC_CHARGES_GLOBAL,2)), SEG_GROUP     
FROM #DPC_CHARGES    
GROUP BY SEG_GROUP    

      
-- OVER FUNCTION TO GET NET_BALANCE   

--DECLARE @CHEKPOSTING INT   
--set @CHEKPOSTING = 0

IF @SUMMARY_FLAG = 0      
BEGIN    
	
	UPDATE D SET NET_BALANCE = D1.DPC_BALANCE,      
				NET_DPC_CHARGES = (D1.DPC_BALANCE * DPC_PERCENTE) / 100/ 365  
	FROM #DPC_CHARGES D,      
	(
		SELECT DPC_DATE, CLTCODE, LONG_NAME,
			DPC_BALANCE = SUM(CASE WHEN DPC_BALANCE < 0 THEN DPC_BALANCE ELSE 0 END) OVER (PARTITION BY DPC_DATE, CLTCODE)FROM #DPC_CHARGES
	) D1      
	WHERE D.DPC_DATE = D1.DPC_DATE AND D.CLTCODE = D1.CLTCODE
	IF @CHEKPOSTING = 1
	BEGIN
		UPDATE D SET NET_BALANCE=D1.DPC_BALANCE,
					 NET_DPC_CHARGES=(
										CASE WHEN D.NET_DPC_CHARGES<1500--D.MIN_BAL 
											 THEN 
												((D1.DPC_BALANCE*D.PER_REV/100)/365)
											 ELSE
												((D1.DPC_BALANCE*D.DPC_PERCENTE/100)/365)
										END
									)
		FROM #DPC_CHARGES D,      
		(
			SELECT DPC_DATE, CLTCODE, LONG_NAME,
				DPC_BALANCE = SUM(CASE WHEN DPC_BALANCE < 0 THEN DPC_BALANCE ELSE 0 END) OVER (PARTITION BY DPC_DATE, CLTCODE)FROM #DPC_CHARGES
		) D1      
		WHERE D.DPC_DATE = D1.DPC_DATE AND D.CLTCODE = D1.CLTCODE
	END     

UPDATE #DPC_CHARGES SET NET_BALANCE = D1.NET_BALANCE, NET_DPC_CHARGES = D1.NET_DPC_CHARGES FROM    
(SELECT NET_DPC_CHARGES = SUM(NET_DPC_CHARGES), NET_BALANCE = SUM(NET_BALANCE) FROM    
(SELECT CLTCODE, NET_BALANCE = SUM(NET_BALANCE), NET_DPC_CHARGES = SUM(NET_DPC_CHARGES) FROM #DPC_CHARGES GROUP BY CLTCODE) D) D1    
WHERE #DPC_CHARGES.CLTCODE = 'ZZZZZZZZZZ' AND #DPC_CHARGES.LONG_NAME = 'TOTAL'  

END    
ELSE    
BEGIN  
	
	UPDATE D SET NET_BALANCE = D1.DPC_BALANCE,      
				 NET_DPC_CHARGES = ROUND((D1.DPC_BALANCE * DPC_PERCENTE) / 100/ 365,2),  
				 NET_DPC_CHARGES_GLOBAL = ROUND(D1.NET_DPC_CHARGES_GLOBAL,2)  
	FROM #DPC_CHARGES D,      
	(SELECT DPC_DATE, CLTCODE, LONG_NAME,      
	DPC_BALANCE = SUM(CASE WHEN DPC_BALANCE < 0 THEN DPC_BALANCE ELSE 0 END) OVER (PARTITION BY CLTCODE), 
	NET_DPC_CHARGES_GLOBAL = SUM(CASE WHEN NET_DPC_CHARGES_GLOBAL < 0 THEN NET_DPC_CHARGES_GLOBAL ELSE 0 END) OVER (PARTITION BY CLTCODE)      
	FROM #DPC_CHARGES) D1      
	WHERE D.CLTCODE = D1.CLTCODE
	IF @CHEKPOSTING = 1
	BEGIN
		UPDATE D SET NET_BALANCE = D1.DPC_BALANCE,      
				  NET_DPC_CHARGES = ROUND(
											(
												CASE WHEN D.NET_DPC_CHARGES<1500--D.MIN_BAL 
													 THEN 
														((D1.DPC_BALANCE*PER_REV/100)/365)
													 ELSE
														((D1.DPC_BALANCE*DPC_PERCENTE/100)/365)
												END
											)							
										,2),  
				  NET_DPC_CHARGES_GLOBAL = ROUND(D1.NET_DPC_CHARGES_GLOBAL,2)  
		FROM #DPC_CHARGES D,      
		(
		SELECT DPC_DATE, CLTCODE, LONG_NAME,      
		DPC_BALANCE = SUM(CASE WHEN DPC_BALANCE < 0 THEN DPC_BALANCE ELSE 0 END) OVER (PARTITION BY CLTCODE), 
		NET_DPC_CHARGES_GLOBAL = SUM(CASE WHEN NET_DPC_CHARGES_GLOBAL < 0 THEN NET_DPC_CHARGES_GLOBAL ELSE 0 END) OVER (PARTITION BY CLTCODE)
		FROM #DPC_CHARGES
		) D1      
		WHERE D.CLTCODE = D1.CLTCODE		
	END	  
 

UPDATE #DPC_CHARGES SET NET_DPC_CHARGES = D1.NET_DPC_CHARGES FROM    
(SELECT NET_DPC_CHARGES = MIN(NET_DPC_CHARGES) FROM    
(SELECT CLTCODE, NET_DPC_CHARGES = MIN(NET_DPC_CHARGES) FROM #DPC_CHARGES GROUP BY CLTCODE) D) D1    
WHERE #DPC_CHARGES.CLTCODE = 'ZZZZZZZZZZ' AND #DPC_CHARGES.LONG_NAME = 'TOTAL'  
  
END 


    




    
/*UPDATE #DPC_CHARGES SET NET_DPC_CHARGES = SUM(D1.NET_DPC_CHARGES)    
FROM  (SELECT CLTCODE, LONG_NAME, NET_DPC_CHARGES FROM #DPC_CHARGES GROUP BY CLTCODE, LONG_NAME, NET_DPC_CHARGES) D1    
WHERE #DPC_CHARGES.CLTCODE = 'ZZZZZZZZZZ' AND #DPC_CHARGES.LONG_NAME = 'TOTAL'*/    
    

SET @PIVOT_VAL = (SELECT      
STUFF(      
(      
SELECT ',['+ITEMS+'_LEDBAL]=ISNULL(SUM(['+ITEMS+']),0)'      
FROM ACCOUNT..CLS_SPLIT(@SEG_EXCH,'|')      
FOR XML PATH('')      
),1,1,''))      
      
SET @PIVOT_COLS = (SELECT      
STUFF(      
(      
SELECT ',['+ITEMS+']'      
FROM ACCOUNT..CLS_SPLIT(@SEG_EXCH,'|')      
FOR XML PATH('')      
),1,1,''))      
      

print @PIVOT_VAL
PRINT @PIVOT_COLS      

DECLARE @SELECT_COLS_MARGIN VARCHAR(8000)
DECLARE @SELECT_COLS_COL  VARCHAR(8000)
DECLARE @ALTERCOLS_MARGIN VARCHAR(8000)
DECLARE @ALTERCOLS_COL  VARCHAR(8000)
DECLARE @UPDATECOLS_MARGIN VARCHAR(8000)
DECLARE @UPDATECOLS_COL  VARCHAR(8000)


SET @ALTERCOLS_MARGIN =  (SELECT      
STUFF((SELECT ',['+ITEMS+'_MARGIN] MONEY'      
		FROM ACCOUNT..CLS_SPLIT(@SEG_EXCH,'|') WHERE  ITEMS <> 'NSE-CAPITAL'     
		FOR XML PATH('')      
	),1,1,''))

SET @ALTERCOLS_COL =  (SELECT      
STUFF((SELECT ',['+ITEMS+'_COL] MONEY'      
		FROM ACCOUNT..CLS_SPLIT(@SEG_EXCH,'|')      
		FOR XML PATH('')      
	),1,1,''))

IF @ALTERCOLS_MARGIN <> '' AND @ALTERCOLS_MARGIN IS NOT NULL
BEGIN
	EXEC ('ALTER TABLE #DPC_CHARGES ADD '+ @ALTERCOLS_MARGIN )
END

EXEC ('ALTER TABLE #DPC_CHARGES ADD ' + @ALTERCOLS_COL)


SET @SELECT_COLS_MARGIN =  (SELECT      
STUFF((SELECT ',['+ITEMS+'_MARGIN] = ISNULL(SUM(['+ITEMS+'_MARGIN]),0) '      
		FROM ACCOUNT..CLS_SPLIT(@SEG_EXCH,'|') WHERE  ITEMS <> 'NSE-CAPITAL'     
		FOR XML PATH('')      
	  ),1,1,''))



SET @SELECT_COLS_COL =  (SELECT      
STUFF((SELECT ',['+ITEMS+'_COL]= ISNULL(SUM(['+ITEMS+'_COL]),0) '      
		FROM ACCOUNT..CLS_SPLIT(@SEG_EXCH,'|')      
		FOR XML PATH('')      
		),1,1,''))

SET @ALTERCOLS_MARGIN =  (SELECT      
STUFF((SELECT ',['+ITEMS+'_MARGIN] '      
		FROM ACCOUNT..CLS_SPLIT(@SEG_EXCH,'|') WHERE  ITEMS <> 'NSE-CAPITAL'     
		FOR XML PATH('')      
	  ),1,1,''))

SET @ALTERCOLS_COL =  (SELECT      
STUFF((SELECT ',['+ITEMS+'_COL] '      
		FROM ACCOUNT..CLS_SPLIT(@SEG_EXCH,'|')      
		FOR XML PATH('')      
		),1,1,''))



SET @UPDATECOLS_MARGIN = (SELECT      
STUFF(      
(      
SELECT ',['+ITEMS+'_MARGIN] = CASE WHEN SEG_GROUP = '''+ITEMS+''' THEN MARGIN_REQ ELSE 0 END '       
FROM ACCOUNT..CLS_SPLIT(@SEG_EXCH,'|')  WHERE  ITEMS <> 'NSE-CAPITAL'       
FOR XML PATH('')      
),1,1,''))

SET @UPDATECOLS_COL = (SELECT      
STUFF(      
(      
SELECT ',['+ITEMS+'_COL] = CASE WHEN SEG_GROUP = '''+ITEMS+''' THEN (CASH_COLLATREAL + NONCASH_COLLATREAL) ELSE 0 END '       
FROM ACCOUNT..CLS_SPLIT(@SEG_EXCH,'|')      
FOR XML PATH('')      
),1,1,''))

IF @UPDATECOLS_MARGIN <> '' AND @UPDATECOLS_MARGIN IS NOT NULL
BEGIN	
	EXEC ("UPDATE #DPC_CHARGES SET " + @UPDATECOLS_MARGIN)
END


EXEC ("UPDATE #DPC_CHARGES SET " + @UPDATECOLS_COL)
	

--select * from #DPC_CHARGES

IF @SHOWDIFF = 'Y'  
 BEGIN  
  IF @SUMMARY_FLAG = 0      
 BEGIN      
  SET @@SQL = "SELECT DPC_DATE=CONVERT(VARCHAR,DPC_DATE,103), CLTCODE, LONG_NAME,"+@PIVOT_VAL+","+@SELECT_COLS_COL+","+@SELECT_COLS_MARGIN+",DPC_BALANCE = NET_BALANCE,CASE WHEN CLTCODE='ZZZZZZZZZZ' THEN MAX(NET_DPC_CHARGES) ELSE SUM(NET_DPC_CHARGES) END NET_DPC_CHARGES, NET_DPC_CHARGES_GLOBAL AS GLOBAL_CHRG"      
  SET @@SQL = @@SQL + " FROM (SELECT DPC_DATE, CLTCODE, LONG_NAME, SEG_GROUP,LEDGER_BALANCE, DPC_BALANCE, NET_BALANCE, NET_DPC_CHARGES, NET_DPC_CHARGES_GLOBAL,"+@ALTERCOLS_COL+","+@ALTERCOLS_MARGIN+"  FROM #DPC_CHARGES WHERE NET_DPC_CHARGES <> NET_DPC_CHARGES_GLOBAL) AS S "      
  SET @@SQL = @@SQL + " PIVOT ( SUM(LEDGER_BALANCE) FOR [SEG_GROUP] IN ("+@PIVOT_COLS+")) AS P "      
  SET @@SQL = @@SQL + " GROUP BY DPC_DATE, CLTCODE, LONG_NAME, NET_BALANCE, NET_DPC_CHARGES_GLOBAL "-- ,"+@ALTERCOLS_MARGIN+","+@ALTERCOLS_COL      
  SET @@SQL = @@SQL + " ORDER BY CLTCODE, CONVERT(DATETIME,DPC_DATE) "    
 END      
 ELSE      
 BEGIN   
  SET @@SQL = "SELECT CLTCODE, MAX(LONG_NAME),"+@PIVOT_VAL+","+@ALTERCOLS_COL+","+@ALTERCOLS_MARGIN+",DPC_BALANCE = ISNULL(NET_BALANCE, 0), CASE WHEN CLTCODE='ZZZZZZZZZZ' THEN MAX(NET_DPC_CHARGES) ELSE SUM(NET_DPC_CHARGES) END NET_DPC_CHARGES, GLOBAL_CHRG = ISNULL(NET_DPC_CHARGES_GLOBAL,0)"      
  SET @@SQL = @@SQL + " FROM (SELECT DPC_DATE, CLTCODE, LONG_NAME, SEG_GROUP,LEDGER_BALANCE, DPC_BALANCE, NET_BALANCE, NET_DPC_CHARGES_GLOBAL,"+@ALTERCOLS_COL+","+@ALTERCOLS_MARGIN+"  FROM #DPC_CHARGES "  
  SET @@SQL = @@SQL + " WHERE NET_DPC_CHARGES <> NET_DPC_CHARGES_GLOBAL) AS S "      
  SET @@SQL = @@SQL + " PIVOT (SUM(LEDGER_BALANCE) FOR [SEG_GROUP] IN ("+@PIVOT_COLS+")) AS P "      
  SET @@SQL = @@SQL + " GROUP BY CLTCODE, NET_BALANCE, NET_DPC_CHARGES, NET_DPC_CHARGES_GLOBAL "
  SET @@SQL = @@SQL + " ORDER BY CLTCODE "    
 END      
 END  
ELSE  
 BEGIN  
 IF @SUMMARY_FLAG = 0      
 BEGIN  
  IF @SELECT_COLS_MARGIN IS NULL
	BEGIN
	SET @@SQL = "SELECT DPC_DATE=CONVERT(VARCHAR,DPC_DATE,103), CLTCODE, LONG_NAME,"+@PIVOT_VAL+","+@SELECT_COLS_COL+",DPC_BALANCE = NET_BALANCE,CASE WHEN CLTCODE='ZZZZZZZZZZ' THEN MAX(NET_DPC_CHARGES) ELSE SUM(NET_DPC_CHARGES) END NET_DPC_CHARGES"      
    SET @@SQL = @@SQL + " FROM (SELECT DPC_DATE, CLTCODE, LONG_NAME, SEG_GROUP,LEDGER_BALANCE, DPC_BALANCE, NET_BALANCE,NET_DPC_CHARGES ,"+@ALTERCOLS_COL+" FROM #DPC_CHARGES ) AS S "      
	END
  ELSE
  BEGIN
	SET @@SQL = "SELECT DPC_DATE=CONVERT(VARCHAR,DPC_DATE,103), CLTCODE, LONG_NAME,"+@PIVOT_VAL+","+@SELECT_COLS_COL+","+@SELECT_COLS_MARGIN+",DPC_BALANCE = NET_BALANCE,CASE WHEN CLTCODE='ZZZZZZZZZZ' THEN MAX(NET_DPC_CHARGES) ELSE SUM(NET_DPC_CHARGES) END NET_DPC_CHARGES"      
	SET @@SQL = @@SQL + " FROM (SELECT DPC_DATE, CLTCODE, LONG_NAME, SEG_GROUP,LEDGER_BALANCE, DPC_BALANCE, NET_BALANCE, NET_DPC_CHARGES,"+@ALTERCOLS_COL+","+@ALTERCOLS_MARGIN+" FROM #DPC_CHARGES ) AS S "      
  END
  SET @@SQL = @@SQL + " PIVOT ( SUM(LEDGER_BALANCE) FOR [SEG_GROUP] IN ("+@PIVOT_COLS+")) AS P "      
  SET @@SQL = @@SQL + " GROUP BY DPC_DATE, CLTCODE, LONG_NAME, NET_BALANCE "--,"+@ALTERCOLS_MARGIN+","+@ALTERCOLS_COL      
  SET @@SQL = @@SQL + " ORDER BY CLTCODE, CONVERT(DATETIME,DPC_DATE) "    

  --SET @@SQL = @@SQL + " UNION SELECT DPC_DATE=CONVERT(VARCHAR,DPC_DATE,103), CLTCODE, LONG_NAME,"+@PIVOT_VAL_DUMMY+","+@PIVOT_VAL_COLLATERAL+",NET_BALANCE,NET_DPC_CHARGES"      
  ---SET @@SQL = @@SQL + " FROM (SELECT DPC_DATE, CLTCODE, LONG_NAME, SEG_GROUP, DPC_BALANCE, NET_BALANCE, NET_DPC_CHARGES,CASH_COLLATREAL FROM #DPC_CHARGES ) AS S "      
  --SET @@SQL = @@SQL + " PIVOT ( SUM(CASH_COLLATREAL) FOR [SEG_GROUP] IN ("+@PIVOT_VAL_COLLATERAL+")) AS P "      
  --SET @@SQL = @@SQL + " GROUP BY DPC_DATE, CLTCODE, LONG_NAME, NET_BALANCE, NET_DPC_CHARGES"      
  --SET @@SQL = @@SQL + " ORDER BY CLTCODE, CONVERT(DATETIME,DPC_DATE) "    

  --SET @@SQL = "UNION SELECT DPC_DATE=CONVERT(VARCHAR,DPC_DATE,103), CLTCODE, LONG_NAME,"+@PIVOT_VAL+",NET_BALANCE,NET_DPC_CHARGES"      
  --SET @@SQL = @@SQL + " FROM (SELECT DPC_DATE, CLTCODE, LONG_NAME, SEG_GROUP, DPC_BALANCE, NET_BALANCE, NET_DPC_CHARGES,CASH_COLLATREAL FROM #DPC_CHARGES ) AS S "      
  --SET @@SQL = @@SQL + " PIVOT ( SUM(CASH_COLLATREAL) FOR [SEG_GROUP] IN ("+@PIVOT_COLS+")) AS P "      
  --SET @@SQL = @@SQL + " GROUP BY DPC_DATE, CLTCODE, LONG_NAME, NET_BALANCE, NET_DPC_CHARGES"      
  --SET @@SQL = @@SQL + " ORDER BY CLTCODE, CONVERT(DATETIME,DPC_DATE) "    

 END      
 ELSE      
 BEGIN   
IF @SELECT_COLS_MARGIN IS NULL
  BEGIN
	SET @@SQL = "SELECT CLTCODE, MAX(LONG_NAME),"+@PIVOT_VAL+","+@SELECT_COLS_COL+",DPC_BALANCE = ISNULL(NET_BALANCE, 0),CASE WHEN CLTCODE='ZZZZZZZZZZ' THEN MAX(NET_DPC_CHARGES) ELSE SUM(NET_DPC_CHARGES) END NET_DPC_CHARGES"      	
 SET @@SQL = @@SQL + " FROM (SELECT DPC_DATE, CLTCODE, LONG_NAME, SEG_GROUP,LEDGER_BALANCE, DPC_BALANCE, NET_BALANCE, NET_DPC_CHARGES,"+@ALTERCOLS_COL+" FROM #DPC_CHARGES) AS S "  
  END	
ELSE 
BEGIN
  SET @@SQL = "SELECT CLTCODE, MAX(LONG_NAME),"+@PIVOT_VAL+","+@SELECT_COLS_COL+","+@SELECT_COLS_MARGIN+",DPC_BALANCE = ISNULL(NET_BALANCE, 0), CASE WHEN CLTCODE='ZZZZZZZZZZ' THEN MAX(NET_DPC_CHARGES) ELSE SUM(NET_DPC_CHARGES) END NET_DPC_CHARGES"      
  SET @@SQL = @@SQL + " FROM (SELECT DPC_DATE, CLTCODE, LONG_NAME, SEG_GROUP,LEDGER_BALANCE, DPC_BALANCE, NET_BALANCE, NET_DPC_CHARGES,"+@ALTERCOLS_COL+","+@ALTERCOLS_MARGIN+" FROM #DPC_CHARGES) AS S "  
END
--SET @@SQL = "SELECT CLTCODE, MAX(LONG_NAME),"+@PIVOT_VAL+","+@SELECT_COLS_COL+","+@SELECT_COLS_MARGIN+",DPC_BALANCE = ISNULL(NET_BALANCE, 0), NET_DPC_CHARGES = ISNULL(NET_DPC_CHARGES, 0)"      
  --SET @@SQL = @@SQL + " FROM (SELECT DPC_DATE, CLTCODE, LONG_NAME, SEG_GROUP,LEDGER_BALANCE, DPC_BALANCE, NET_BALANCE, NET_DPC_CHARGES,"+@ALTERCOLS_COL+","+@ALTERCOLS_MARGIN+" FROM #DPC_CHARGES) AS S "  
  SET @@SQL = @@SQL + " PIVOT (SUM(LEDGER_BALANCE) FOR [SEG_GROUP] IN ("+@PIVOT_COLS+")) AS P "      
  SET @@SQL = @@SQL + " WHERE ISNULL(NET_DPC_CHARGES, 0) < 0 GROUP BY CLTCODE, NET_BALANCE"
  SET @@SQL = @@SQL + " ORDER BY CLTCODE "    
 END      
 END  
  
PRINT @@SQL      
EXEC(@@SQL)

GO
