-- Object: PROCEDURE dbo.RPT_PARTYLEDGER_BRANCH_DETAILS
-- Server: 10.253.33.91 | DB: ACCOUNT
--------------------------------------------------

/*	*****************************************************************************************************
	THIS PROCEDURE WILL DISPLAY PARTY LEDGER DETAILS FOR BRANCH
	IN BROKER, AREA, REGION, BRANCH, SUBBROKER, TRADER AND PARTY LOGINS.
	THIS REPORT CAN BE VIEWED ON VOUCHER DATE OR EFFECTIVE DATE.
	CREATED BY	:=	YATIN DESAI
	CREATED DATE	:=	DECEMBER 02 2005
	DATABASE		:=	ACCOUNT AND ACCOUNTBSE AND ACCOUNTFO AND ACCOUNTMCDX AND ACCOUNTNCDX
	SYNTAX AS FOLLOWS -----
	EXEC RPT_PARTYLEDGER_BRANCH_DETAILS_V2 'APR  1 2005', 'DEC 31 2005', 'APR  1 2005', 'MAR 31 2006', 'BROKER', 'BROKER', 'VDT', '0', 'ZZZZ'
	EXEC RPT_PARTYLEDGER_BRANCH_DETAILS 'APR  1 2005', 'DEC 31 2005', 'APR  1 2005', 'MAR 31 2006', 'REGION', 'AHM', 'VDT', 'APS', 'ZPS'
	*****************************************************************************************************
*/
CREATE PROC RPT_PARTYLEDGER_BRANCH_DETAILS
	@FDATE VARCHAR(11),
	@TDATE VARCHAR(11),
	@STDDATE VARCHAR(11),
	@LSTDATE VARCHAR(11),
	@STATUSID VARCHAR(20),
	@STATUSNAME VARCHAR(20),
	@DISPLAYRPT VARCHAR(3),
	@FPARTY VARCHAR(10),
	@TPARTY VARCHAR(10)

AS

DECLARE
@@OBJID AS INT
SELECT @@OBJID = ISNULL(OBJECT_ID('NEWPARTYLEDGER'), 0)
IF @@OBJID = 0
	BEGIN
		EXEC CREATEPARTYLEDGER
	END

SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED

DELETE FROM NEWPARTYLEDGER WHERE SPID = @@SPID

IF @STATUSID = 'BROKER'
	BEGIN
		IF @DISPLAYRPT = 'VDT'
			BEGIN
				INSERT INTO NEWPARTYLEDGER (BRANCH_CODE, CLTCODE, ACNAME, VDT, EDT, VAMT, SPID)
				SELECT	A.BRANCHCODE,
						L.CLTCODE,
						A.ACNAME,
						CONVERT(VARCHAR(11), VDT, 109),
						CONVERT(VARCHAR(11), EDT, 109),
						CASE WHEN DRCR = 'C' THEN VAMT ELSE -VAMT END,
						@@SPID
				FROM
					ACMAST A (NOLOCK) LEFT JOIN LEDGER L (NOLOCK)
						ON A.CLTCODE = L.CLTCODE
				WHERE
					A.BRANCHCODE BETWEEN @FPARTY AND @TPARTY
					AND L.VDT BETWEEN @STDDATE AND @TDATE + ' 23:59:59'
					AND A.ACCAT IN (4, 104)
					

				INSERT INTO NEWPARTYLEDGER (BRANCH_CODE, CLTCODE, ACNAME, VDT, EDT, MAMT, SPID)
				SELECT	A.BRANCHCODE,
						M.PARTY_CODE,
						A.ACNAME,
						CONVERT(VARCHAR(11), M.VDT, 109),
						CONVERT(VARCHAR(11), L.EDT, 109),
						CASE WHEN M.DRCR = 'C' THEN AMOUNT ELSE -AMOUNT END,
						@@SPID
				FROM
					ACMAST A (NOLOCK) LEFT JOIN MARGINLEDGER M (NOLOCK)
						ON A.CLTCODE = M.PARTY_CODE,
					LEDGER L
				WHERE
					M.VNO = L.VNO AND M.VTYP = L.VTYP AND M.BOOKTYPE = L.BOOKTYPE AND M.LNO = L.LNO
					AND A.BRANCHCODE BETWEEN @FPARTY AND @TPARTY
					AND M.VDT BETWEEN @STDDATE AND @TDATE + ' 23:59:59'
					AND A.ACCAT IN (4, 104)

				UPDATE NEWPARTYLEDGER SET BRANCH = B.BRANCH FROM MSAJAG.DBO.BRANCH B
					WHERE NEWPARTYLEDGER.BRANCH_CODE = B.BRANCH_CODE
					AND SPID = @@SPID

				SELECT BRANCH_CODE AS BRANCHCODE, BRANCH, CLTCODE, ACNAME, VAMT, MAMT, UNREALISED
				FROM
					(
						SELECT BRANCH_CODE, BRANCH, CLTCODE = '00000000000', ACNAME = '', VAMT = '', MAMT = '', UNREALISED = ''
						FROM NEWPARTYLEDGER (NOLOCK)
						WHERE SPID = @@SPID
						GROUP BY BRANCH_CODE, BRANCH

					UNION ALL

						SELECT BRANCH_CODE, BRANCH, CLTCODE, ACNAME, '$$' + CONVERT(VARCHAR, SUM(VAMT), 1) AS VAMT, '$$' + CONVERT(VARCHAR, SUM(MAMT), 1) AS MAMT,
								'$$' + CONVERT(VARCHAR, SUM(CASE WHEN VDT <= @TDATE + ' 23:59:59' AND EDT > @TDATE + ' 23:59:59'
											THEN (VAMT + MAMT) ELSE 0 END), 1) AS UNREALISED
						FROM NEWPARTYLEDGER (NOLOCK)
						WHERE SPID = @@SPID
						GROUP BY BRANCH_CODE, BRANCH, CLTCODE, ACNAME

					UNION ALL

						SELECT BRANCH_CODE, BRANCH, CLTCODE = 'ZZZZZZZZZZZ', ACNAME = '', '$$' + CONVERT(VARCHAR, SUM(VAMT), 1) AS VAMT, '$$' + CONVERT(VARCHAR, SUM(MAMT), 1) AS MAMT,
								'$$' + CONVERT(VARCHAR, SUM(CASE WHEN VDT <= @TDATE + ' 23:59:59' AND EDT > @TDATE + ' 23:59:59'
											THEN (VAMT + MAMT) ELSE 0 END), 1) AS UNREALISED
						FROM NEWPARTYLEDGER (NOLOCK)
						WHERE SPID = @@SPID
						GROUP BY BRANCH_CODE, BRANCH

					UNION ALL

						SELECT BRANCH_CODE = 'ZZZZZZZZZZZ', BRANCH = '', CLTCODE = '', ACNAME = '', '$$' + CONVERT(VARCHAR, SUM(VAMT), 1) AS VAMT, '$$' + CONVERT(VARCHAR, SUM(MAMT), 1) AS MAMT,
								'$$' + CONVERT(VARCHAR, SUM(CASE WHEN VDT <= @TDATE + ' 23:59:59' AND EDT > @TDATE + ' 23:59:59'
											THEN (VAMT + MAMT) ELSE 0 END), 1) AS UNREALISED
						FROM NEWPARTYLEDGER (NOLOCK)
						WHERE SPID = @@SPID
					) A
				ORDER BY BRANCH_CODE, BRANCH, CLTCODE, ACNAME
			END
		ELSE IF @DISPLAYRPT = 'EDT'
			BEGIN
				INSERT INTO NEWPARTYLEDGER (BRANCH_CODE, CLTCODE, ACNAME, VDT, EDT, VAMT, SPID)
				SELECT	A.BRANCHCODE,
						L.CLTCODE,
						A.ACNAME,
						CONVERT(VARCHAR(11), VDT, 109),
						CONVERT(VARCHAR(11), EDT, 109),
						CASE WHEN DRCR = 'C' THEN VAMT ELSE -VAMT END,
						@@SPID
				FROM
					ACMAST A (NOLOCK) LEFT JOIN LEDGER L (NOLOCK)
						ON A.CLTCODE = L.CLTCODE
				WHERE
					A.BRANCHCODE BETWEEN @FPARTY AND @TPARTY
					AND L.EDT BETWEEN @STDDATE AND @TDATE + ' 23:59:59'
					AND A.ACCAT IN (4, 104)
					

				INSERT INTO NEWPARTYLEDGER (BRANCH_CODE, CLTCODE, ACNAME, VDT, EDT, MAMT, SPID)
				SELECT	A.BRANCHCODE,
						M.PARTY_CODE,
						A.ACNAME,
						CONVERT(VARCHAR(11), M.VDT, 109),
						CONVERT(VARCHAR(11), L.EDT, 109),
						CASE WHEN M.DRCR = 'C' THEN AMOUNT ELSE -AMOUNT END,
						@@SPID
				FROM
					ACMAST A (NOLOCK) LEFT JOIN MARGINLEDGER M (NOLOCK)
						ON A.CLTCODE = M.PARTY_CODE,
					LEDGER L
				WHERE
					M.VNO = L.VNO AND M.VTYP = L.VTYP AND M.BOOKTYPE = L.BOOKTYPE AND M.LNO = L.LNO
					AND A.BRANCHCODE BETWEEN @FPARTY AND @TPARTY
					AND L.EDT BETWEEN @STDDATE AND @TDATE + ' 23:59:59'
					AND A.ACCAT IN (4, 104)

				UPDATE NEWPARTYLEDGER SET BRANCH = B.BRANCH FROM MSAJAG.DBO.BRANCH B
					WHERE NEWPARTYLEDGER.BRANCH_CODE = B.BRANCH_CODE
					AND SPID = @@SPID

				SELECT BRANCH_CODE AS BRANCHCODE, BRANCH, CLTCODE, ACNAME, 
					'$$' + CONVERT(VARCHAR, SUM(VAMT), 1) AS VAMT, '$$' + CONVERT(VARCHAR, SUM(MAMT), 1) AS MAMT
				FROM
					(
						SELECT BRANCH_CODE, BRANCH, CLTCODE = '00000000000', ACNAME = '', VAMT = 0, MAMT = 0
						FROM NEWPARTYLEDGER (NOLOCK)
						WHERE SPID = @@SPID
						GROUP BY BRANCH_CODE, BRANCH

					UNION ALL

						SELECT BRANCH_CODE, BRANCH, CLTCODE, ACNAME,
								SUM(VAMT),
								SUM(MAMT)
						FROM NEWPARTYLEDGER (NOLOCK)
						WHERE SPID = @@SPID
						GROUP BY BRANCH_CODE, BRANCH, CLTCODE, ACNAME

					UNION ALL

						SELECT BRANCH_CODE, BRANCH, CLTCODE, ACNAME,
								SUM(CASE WHEN VAMT >= 0 THEN -VAMT ELSE ABS(VAMT) END),
								SUM(CASE WHEN MAMT >= 0 THEN -MAMT ELSE ABS(MAMT) END)
						FROM NEWPARTYLEDGER (NOLOCK)
						WHERE SPID = @@SPID
						AND VDT < @STDDATE
						AND EDT >= @STDDATE
						GROUP BY BRANCH_CODE, BRANCH, CLTCODE, ACNAME

					UNION ALL

						SELECT BRANCH_CODE, BRANCH, CLTCODE = 'ZZZZZZZZZZZ', ACNAME = '',
								SUM(VAMT),
								SUM(MAMT)
						FROM NEWPARTYLEDGER (NOLOCK)
						WHERE SPID = @@SPID
						GROUP BY BRANCH_CODE, BRANCH

					UNION ALL

						SELECT BRANCH_CODE, BRANCH, CLTCODE = 'ZZZZZZZZZZZ', ACNAME = '',
								SUM(CASE WHEN VAMT >= 0 THEN -VAMT ELSE ABS(VAMT) END),
								SUM(CASE WHEN MAMT >= 0 THEN -MAMT ELSE ABS(MAMT) END)
						FROM NEWPARTYLEDGER (NOLOCK)
						WHERE SPID = @@SPID
						AND VDT < @STDDATE
						AND EDT >= @STDDATE
						GROUP BY BRANCH_CODE, BRANCH

					UNION ALL
						SELECT BRANCH_CODE = 'ZZZZZZZZZZZ', BRANCH = '', CLTCODE = '', ACNAME = '',
								SUM(VAMT),
								SUM(MAMT)
						FROM NEWPARTYLEDGER (NOLOCK)
						WHERE SPID = @@SPID

					UNION ALL
						SELECT BRANCH_CODE = 'ZZZZZZZZZZZ', BRANCH = '', CLTCODE = '', ACNAME = '',
								SUM(CASE WHEN VAMT >= 0 THEN -VAMT ELSE ABS(VAMT) END),
								SUM(CASE WHEN MAMT >= 0 THEN -MAMT ELSE ABS(MAMT) END)
						FROM NEWPARTYLEDGER
						WHERE SPID = @@SPID
						AND VDT < @STDDATE
						AND EDT >= @STDDATE
					) A
				GROUP BY BRANCH_CODE, BRANCH, CLTCODE, ACNAME
				ORDER BY BRANCH_CODE, BRANCH, CLTCODE, ACNAME

			END
	END

--200500000914 - mcx - p - 995103

GO
