-- Object: PROCEDURE dbo.DEALLOCATED_DATA
-- Server: 10.253.33.91 | DB: ACCOUNT
--------------------------------------------------

CREATE PROCEDURE [DBO].[DEALLOCATED_DATA]        
--(        
-- @STATUSID VARCHAR(25), @STATUSNAME VARCHAR(25),         
-- @FROMDATE VARCHAR(11), @TODATE VARCHAR(11),         
-- @FROMPARTY VARCHAR(10), @TOPARTY VARCHAR(10),         
-- @REPORTFOR VARCHAR(10)        
--)          
AS        
SELECT SETT_NO,SETT_TYPE,TRTYPE,PARTY_CODE,SCRIP_CD,SERIES,QTY,CERTNO,REASON,DRCR,DELIVERED,DPID,CLTDPID,TRANSDATE,FILLER2,BDPID,BCLTDPID,'BSE' AS EXCHANGE         
FROM [AngelDemat].BSEDB.DBO.DELTRANS         
WHERE DRCR = 'D' AND FILLER2 = '1' AND DELIVERED = '0'         
AND TRTYPE IN ('905','1002')        
union         
SELECT SETT_NO,SETT_TYPE,TRTYPE,PARTY_CODE,SCRIP_CD,SERIES,QTY,CERTNO,REASON,DRCR,DELIVERED,DPID,CLTDPID,TRANSDATE,FILLER2,BDPID,BCLTDPID,'NSE' AS EXCHANGE          
FROM [AngelDemat].MSAJAG.DBO.DELTRANS         
WHERE DRCR = 'D' AND FILLER2 = '1' AND DELIVERED = '0'         
AND TRTYPE IN ('905','1002')       
ORDER BY EXCHANGE

GO
