-- Object: PROCEDURE dbo.V2_ACC_FUNDSPAYOUTALL_client
-- Server: 10.253.33.91 | DB: ACCOUNT
--------------------------------------------------


 create PROCEDURE [dbo].[V2_ACC_FUNDSPAYOUTALL_client]
	@EFFDATE VARCHAR(11),
	@SDATE VARCHAR(11),
	@STATUSNAME VARCHAR(30),
	@BRANCHCODE VARCHAR(10),
	@SBCODE VARCHAR(10),
	@NOREC VARCHAR(5) = '250',
	@REMARK VARCHAR(2) = '',
	@FPARTY VARCHAR(10),
	@TPARTY VARCHAR(10),
	@CLTYPE VARCHAR(4) = 'ALL', -- CLTYPE -> [WEB / NON-WEB / ALL]
	@PAYMODE CHAR(1),
	@FAMLEDBAL CHAR(1) = 'Y'

AS

	/*
	EXEC V2_ACC_FUNDSPAYOUTALL
		@EFFDATE = 'AUG  4 2007',
		@SDATE = 'APR  1 2005',
		@STATUSNAME = 'BROKER',
		@BRANCHCODE = 'ARSL',
		@SBCODE = 'BANGALORE',
		@NOREC = '1000',
		@REMARK = '',
		@FPARTY = '0',
		@TPARTY = 'ZZ',
		@CLTYPE = 'ALL',
		@PAYMODE = 'C',
		@FAMLEDBAL = 'Y'
	*/

	DECLARE
		@@PENDINGCNT VARCHAR(11),
		@@MAXDATE VARCHAR(11),
		@@SQL VARCHAR(3000)

	SET @@PENDINGCNT = 0
	SET @@MAXDATE = 'JAN  1 1900'

	SET NOCOUNT ON

	IF @FPARTY = ''
	BEGIN
		SET @FPARTY = '0000000000'
	END

	IF @TPARTY = ''
	BEGIN
		SET @TPARTY = 'ZZZZZZZZZZ'
	END

	--SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED

	/*=============================================================================
	LOOP FOR BROKER LOGIN TO REJECTION OF REQUESTS
	1. ALL OLD DATE PENDING REQUESTS
	2. MULTIPLE REQUESTS. ALL REQUESTS OTHER THAN THE FIRST REQUEST OF THE LOWEST AMOUNT ARE REJECTED.
	=============================================================================*/

	IF UPPER(@STATUSNAME) = 'BROKER'
	BEGIN
	SET @@PENDINGCNT =
	(
		SELECT
		COUNT(*)
		FROM ACCOUNT.DBO.V2_SETTPAYOUT_ALL WITH(NOLOCK)
		WHERE STATUS IN ('P', 'I')
		AND GENFLAG = 'A'
	)

	IF @@PENDINGCNT <> 0
	BEGIN
	SET @@MAXDATE =
	(
		SELECT
		LEFT(CONVERT(VARCHAR, MAX(REQUESTDT), 109), 11)
		FROM ACCOUNT.DBO.V2_SETTPAYOUT_ALL WITH(NOLOCK)
		WHERE STATUS IN ('P', 'I')
		AND GENFLAG = 'A'
	)
	END

  /*=============================================================================
  REJECT ALL OLD DATE PENDING REQUESTS
  =============================================================================*/
	UPDATE
		ACCOUNT.DBO.V2_SETTPAYOUT_ALL
	SET
		STATUS = 'R'
	WHERE
		STATUS IN ('P', 'I')
		AND GENFLAG = 'A'
		AND REQUESTDT < @@MAXDATE

	END

 /*===================================================================================
 TEMP TABLE CREATION:
 1. #LEDGERTMP: FINAL TABLE FOR LEDGER BALANCES AND BILL AMOUNT
 2. #LEDGERBILLTMP: TABLE FOR POPULATING BILL AMOUNTS AS POSTED IN ACCOUNT.DBO.V2_SETTPAYOUT_ALL TABLE FOR PENDING REQUESTS.
 ===================================================================================*/
 CREATE TABLE [DBO].[#V2_LEDGERBALANCEUP]
(
	[PARTYCODE] [VARCHAR](10) NULL,
	[PARTYNAME] [VARCHAR](100) NULL,
	[CHEQUENAME] [VARCHAR](100) NULL,
	[BRANCHCODE] [VARCHAR](10) NULL,
	[SUB_BROKER] [VARCHAR](10) NULL,
	[ACCAT] [VARCHAR](10) NULL,
	[BTOBPAYMENT] [INT] NULL,
	[EXCHANGE] [VARCHAR](3),
	[SEGMENT] [VARCHAR](7),
	[LEDBAL] [MONEY] NULL,
	[FAMLEDBAL] [MONEY] NULL,
	[AMTTOPAY] [MONEY] NULL,
	[PAYMODE] [VARCHAR](1) NULL,
	[BANKCODE] [VARCHAR](10) NULL,
	[GENFLAG] [VARCHAR](1),
	[CLIENTTYPE] [VARCHAR](3) NULL,
	[FAMILYCODE] [VARCHAR](10),
	[RUNDATE] [DATETIME] NULL,
	[UNCLEARED_AMT] [MONEY] NULL,
	[PAYAMT_TODAY] [MONEY] NULL,
	[CLIENT] [VARCHAR](10) NULL
 ) ON [PRIMARY]

	INSERT INTO
		#V2_LEDGERBALANCEUP
	EXEC
		V2_GETLEDBAL_ALL
		@SDATE,
		@FPARTY,
		@TPARTY,
		'A', --@GENFLAG
		'HO', --@USER
		@EFFDATE,
		'HO' --@COMP_FOR

	CREATE TABLE #V2_LEDGERTMPUP
	(
		[CLTCODE] [VARCHAR](10) NULL,
		[ACNAME] [VARCHAR](100) NULL,
		[CHEQUENAME] [VARCHAR](100) NULL,
		[BRANCHCODE] [VARCHAR](10) NULL,
		[SUB_BROKER] [VARCHAR] (10),
		[ACCAT] [INT] NULL,
		[BTOBPAYMENT] [INT] NULL,
		[EXCHANGE] [VARCHAR](3) NULL,
		[SEGMENT] [VARCHAR](7) NULL,
		[LEDBAL] [MONEY] NULL,
		[FAMLEDBAL] [MONEY] NULL,
		[AMTTOPAY] [MONEY] NULL,
		[REMARK] [VARCHAR](234) NULL,
		[PAYMODE] [VARCHAR](1) NULL,
		[BANKCODE] [VARCHAR](10) NULL,
		[CLIENTTYPE] [VARCHAR](3) NULL,
		[FAMILYCODE] [VARCHAR] (10),
		[STATUS] [CHAR] (1) NULL
	)

	CREATE TABLE #V2_LEDGERTMP
	(
		[CLTCODE] [VARCHAR](10) NULL,
		[ACNAME] [VARCHAR](100) NULL,
		[CHEQUENAME] [VARCHAR](100) NULL,
		[BRANCHCODE] [VARCHAR](10) NULL,
		[SUB_BROKER] [VARCHAR] (10),
		[ACCAT] [INT] NULL,
		[BTOBPAYMENT] [INT] NULL,
		[EXCHANGE] [VARCHAR](3),
		[SEGMENT] [VARCHAR](7),
		[LEDBAL] [MONEY] NULL,
		[FAMLEDBAL] [MONEY] NULL,
		[AMTTOPAY] [MONEY] NULL,
		[REMARK] [VARCHAR](234) NULL,
		[PAYMODE] [VARCHAR](1) NULL,
		[BANKCODE] [VARCHAR](10) NULL,
		[CLIENTTYPE] [VARCHAR](3) NULL,
		[FAMILYCODE] [VARCHAR] (10),
		[STATUS] [CHAR] (1) NULL,
		[SRNO] [INT] IDENTITY(1,1)
	)

	SELECT @@SQL = "INSERT INTO #V2_LEDGERTMPUP "
	SELECT @@SQL = @@SQL + " SELECT "
	SELECT @@SQL = @@SQL + "  CLTCODE = L.PARTYCODE, "
	SELECT @@SQL = @@SQL + "  ACNAME = L.PARTYNAME, "
	SELECT @@SQL = @@SQL + "  CHEQUENAME = L.CHEQUENAME, "
	SELECT @@SQL = @@SQL + "  BRANCHCODE = L.BRANCHCODE, "
	SELECT @@SQL = @@SQL + "  SUB_BROKER = S.SUB_BROKER, "
	SELECT @@SQL = @@SQL + "  ACCAT = L.ACCAT, "
	SELECT @@SQL = @@SQL + "  BTOBPAYMENT = L.BTOBPAYMENT, "
	SELECT @@SQL = @@SQL + "  EXCHANGE = L.EXCHANGE, "
	SELECT @@SQL = @@SQL + "  SEGMENT = L.SEGMENT, "
	SELECT @@SQL = @@SQL + "  LEDBAL = SUM(L.LEDBAL), "
	SELECT @@SQL = @@SQL + "  FAMLEDBAL = MAX(FAMLEDBAL), "
	SELECT @@SQL = @@SQL + "  AMTTOPAY = SUM(S.AMOUNTTOBEPAID), "
	SELECT @@SQL = @@SQL + "  S.REMARK, "
	SELECT @@SQL = @@SQL + "  PAYMODE = L.PAYMODE, "
	SELECT @@SQL = @@SQL + "  BANKCODE = L.BANKCODE, "
	SELECT @@SQL = @@SQL + "  CLIENTTYPE, "
	SELECT @@SQL = @@SQL + "  FAMILYCODE, "
	SELECT @@SQL = @@SQL + "  STATUS "
	SELECT @@SQL = @@SQL + " FROM  "
	SELECT @@SQL = @@SQL + "  #V2_LEDGERBALANCEUP L WITH(NOLOCK), "
	SELECT @@SQL = @@SQL + "  ACCOUNT.DBO.V2_SETTPAYOUT_ALL S WITH(NOLOCK) "
	SELECT @@SQL = @@SQL + " WHERE "
	SELECT @@SQL = @@SQL + "  S.CLTCODE = L.PARTYCODE "
	SELECT @@SQL = @@SQL + "  AND STATUS IN ('P', 'I') "
	SELECT @@SQL = @@SQL + "  AND S.GENFLAG = 'A' "
	SELECT @@SQL = @@SQL + "  AND S.EXCHANGE = L.EXCHANGE "
	SELECT @@SQL = @@SQL + "  AND S.SEGMENT = L.SEGMENT "
	SELECT @@SQL = @@SQL + "  AND UPPER(S.BRANCHCODE) LIKE (CASE WHEN UPPER('" + @BRANCHCODE + "') = 'ALL' THEN '%' ELSE UPPER('" + @BRANCHCODE + "') END) "
	SELECT @@SQL = @@SQL + "  AND UPPER(S.SUB_BROKER) LIKE (CASE WHEN UPPER('" + @SBCODE + "') = 'ALL' THEN '%' ELSE UPPER('" + @SBCODE + "') END) "

	IF @CLTYPE <> 'ALL'
	BEGIN
		SELECT @@SQL = @@SQL + "  AND L.CLIENTTYPE = '" + @CLTYPE + "' "
	END

	IF @PAYMODE <> 'A'
	BEGIN
		SELECT @@SQL = @@SQL + "  AND L.PAYMODE = '" + @PAYMODE + "' "
	END

	IF @REMARK = 'ON'
	BEGIN
		SELECT @@SQL = @@SQL + "  AND S.REMARK <> '' "
	END

	SELECT @@SQL = @@SQL + " GROUP BY "
	SELECT @@SQL = @@SQL + "  L.PARTYCODE, "
	SELECT @@SQL = @@SQL + "  L.PARTYNAME, "
	SELECT @@SQL = @@SQL + "  L.CHEQUENAME, "
	SELECT @@SQL = @@SQL + "  L.BRANCHCODE, "
	SELECT @@SQL = @@SQL + "  S.SUB_BROKER, "
	SELECT @@SQL = @@SQL + "  L.ACCAT, "
	SELECT @@SQL = @@SQL + "  L.BTOBPAYMENT, "
	SELECT @@SQL = @@SQL + "  S.REMARK, "
	SELECT @@SQL = @@SQL + "  L.PAYMODE, "
	SELECT @@SQL = @@SQL + "  L.BANKCODE, "
	SELECT @@SQL = @@SQL + "  L.EXCHANGE, "
	SELECT @@SQL = @@SQL + "  L.SEGMENT, "
	SELECT @@SQL = @@SQL + "  CLIENTTYPE, "
	SELECT @@SQL = @@SQL + "  FAMILYCODE, "
	SELECT @@SQL = @@SQL + "  STATUS "

	SELECT @@SQL = @@SQL + " UNION ALL "

	SELECT @@SQL = @@SQL + " SELECT "
	SELECT @@SQL = @@SQL + "  CLTCODE = L.PARTYCODE, "
	SELECT @@SQL = @@SQL + "  ACNAME = L.PARTYNAME, "
	SELECT @@SQL = @@SQL + "  CHEQUENAME = L.CHEQUENAME, "
	SELECT @@SQL = @@SQL + "  BRANCHCODE = L.BRANCHCODE, "
	SELECT @@SQL = @@SQL + "  SUB_BROKER = '', "
	SELECT @@SQL = @@SQL + "  ACCAT = L.ACCAT, "
	SELECT @@SQL = @@SQL + "  BTOBPAYMENT = L.BTOBPAYMENT, "
	SELECT @@SQL = @@SQL + "  EXCHANGE = L.EXCHANGE, "
	SELECT @@SQL = @@SQL + "  SEGMENT = L.SEGMENT, "
	SELECT @@SQL = @@SQL + "  LEDBAL = SUM(L.LEDBAL), "
	SELECT @@SQL = @@SQL + "  FAMLEDBAL = MAX(FAMLEDBAL), "
	SELECT @@SQL = @@SQL + "  AMTTOPAY = 0, "
	SELECT @@SQL = @@SQL + "  REMARK = '', "
	SELECT @@SQL = @@SQL + "  PAYMODE = L.PAYMODE, "
	SELECT @@SQL = @@SQL + "  BANKCODE = L.BANKCODE, "
	SELECT @@SQL = @@SQL + "  CLIENTTYPE, "
	SELECT @@SQL = @@SQL + "  FAMILYCODE, "
	SELECT @@SQL = @@SQL + "  STATUS = '' "
	SELECT @@SQL = @@SQL + " FROM  "
	SELECT @@SQL = @@SQL + "  #V2_LEDGERBALANCEUP L WHERE NOT EXISTS (SELECT * FROM "
	SELECT @@SQL = @@SQL + "  ACCOUNT.DBO.V2_SETTPAYOUT_ALL S WITH(NOLOCK) "
	SELECT @@SQL = @@SQL + "  WHERE S.CLTCODE = L.PARTYCODE "
	SELECT @@SQL = @@SQL + "  AND STATUS IN ('P', 'I') "
	SELECT @@SQL = @@SQL + "  AND S.GENFLAG = 'A' "
	SELECT @@SQL = @@SQL + "  AND S.EXCHANGE = L.EXCHANGE "
	SELECT @@SQL = @@SQL + "  AND S.SEGMENT = L.SEGMENT) "
	SELECT @@SQL = @@SQL + " GROUP BY "
	SELECT @@SQL = @@SQL + "  L.PARTYCODE, "
	SELECT @@SQL = @@SQL + "  L.PARTYNAME, "
	SELECT @@SQL = @@SQL + "  L.CHEQUENAME, "
	SELECT @@SQL = @@SQL + "  L.BRANCHCODE, "
	SELECT @@SQL = @@SQL + "  L.ACCAT, "
	SELECT @@SQL = @@SQL + "  L.BTOBPAYMENT, "
	SELECT @@SQL = @@SQL + "  L.PAYMODE, "
	SELECT @@SQL = @@SQL + "  L.BANKCODE, "
	SELECT @@SQL = @@SQL + "  L.EXCHANGE, "
	SELECT @@SQL = @@SQL + "  L.SEGMENT, "
	SELECT @@SQL = @@SQL + "  CLIENTTYPE, "
	SELECT @@SQL = @@SQL + "  FAMILYCODE "

	EXEC (@@SQL)

	SELECT @@SQL = "INSERT INTO #V2_LEDGERTMP "
	SELECT @@SQL = @@SQL + " SELECT "
	SELECT @@SQL = @@SQL + "  CLTCODE, "
	SELECT @@SQL = @@SQL + "  ACNAME, "
	SELECT @@SQL = @@SQL + "  CHEQUENAME, "
	SELECT @@SQL = @@SQL + "  BRANCHCODE, "
	SELECT @@SQL = @@SQL + "  SUB_BROKER, "
	SELECT @@SQL = @@SQL + "  ACCAT, "
	SELECT @@SQL = @@SQL + "  BTOBPAYMENT, "
	SELECT @@SQL = @@SQL + "  EXCHANGE, "
	SELECT @@SQL = @@SQL + "  SEGMENT, "
	SELECT @@SQL = @@SQL + "  LEDBAL = MAX(LEDBAL), "
	SELECT @@SQL = @@SQL + "  FAMLEDBAL = MAX(FAMLEDBAL), "
	SELECT @@SQL = @@SQL + "  AMTTOPAY = MAX(AMTTOPAY), "
	SELECT @@SQL = @@SQL + "  REMARK, "
	SELECT @@SQL = @@SQL + "  PAYMODE, "
	SELECT @@SQL = @@SQL + "  BANKCODE, "
	SELECT @@SQL = @@SQL + "  CLIENTTYPE, "
	SELECT @@SQL = @@SQL + "  FAMILYCODE, "
	SELECT @@SQL = @@SQL + "  STATUS "
	SELECT @@SQL = @@SQL + " FROM "
	SELECT @@SQL = @@SQL + "  #V2_LEDGERTMPUP "
	SELECT @@SQL = @@SQL + " GROUP BY "
	SELECT @@SQL = @@SQL + "  CLTCODE, "
	SELECT @@SQL = @@SQL + "  ACNAME, "
	SELECT @@SQL = @@SQL + "  CHEQUENAME, "
	SELECT @@SQL = @@SQL + "  BRANCHCODE, "
	SELECT @@SQL = @@SQL + "  SUB_BROKER, "
	SELECT @@SQL = @@SQL + "  ACCAT, "
	SELECT @@SQL = @@SQL + "  BTOBPAYMENT, "
	SELECT @@SQL = @@SQL + "  REMARK, "
	SELECT @@SQL = @@SQL + "  PAYMODE, "
	SELECT @@SQL = @@SQL + "  BANKCODE, "
	SELECT @@SQL = @@SQL + "  EXCHANGE, "
	SELECT @@SQL = @@SQL + "  SEGMENT, "
	SELECT @@SQL = @@SQL + "  CLIENTTYPE, "
	SELECT @@SQL = @@SQL + "  FAMILYCODE, "
	SELECT @@SQL = @@SQL + "  STATUS "

	EXEC (@@SQL)

	UPDATE
		TMP
	SET
		CHEQUENAME = M.CHEQUENAME
	FROM
		#V2_LEDGERTMP TMP,
		MULTIBANKID M
	WHERE
		M.CLTCODE = TMP.CLTCODE
		AND M.DEFAULTBANK = '1'

	CREATE TABLE [DBO].[#V2_LEDGERBALANCE_NET]
	(
		[PARTY_CODE] [VARCHAR](10) NULL,
		[NET_LEDBAL] [MONEY] NULL,
		[FAM_LEDBAL] [MONEY] NULL,
		[TOT_LEDBAL] [MONEY] NULL,
		[TOT_AMTTOPAY] [MONEY] NULL
	) ON [PRIMARY]

	INSERT INTO
		#V2_LEDGERBALANCE_NET
	SELECT
		CLTCODE,
		NET_LEDBAL = SUM(LEDBAL),
		FAM_LEDBAL = FAMLEDBAL,
		TOT_LEDBAL = SUM(LEDBAL),
		TOT_AMTTOPAY = CASE WHEN SUM(AMTTOPAY) <= SUM(LEDBAL) THEN SUM(AMTTOPAY) ELSE SUM(LEDBAL) END
	FROM
		#V2_LEDGERTMP
	GROUP BY
		CLTCODE,
		FAMLEDBAL

	IF @FAMLEDBAL = 'Y'
	BEGIN
		UPDATE
			#V2_LEDGERBALANCE_NET
		SET
			TOT_LEDBAL = CASE WHEN FAM_LEDBAL < 0 THEN TOT_LEDBAL - FAM_LEDBAL ELSE TOT_LEDBAL END,
		TOT_AMTTOPAY = CASE WHEN FAM_LEDBAL < 0 THEN TOT_AMTTOPAY - FAM_LEDBAL ELSE TOT_AMTTOPAY END
	END

	DELETE
		#V2_LEDGERBALANCE_NET
	WHERE
		TOT_AMTTOPAY <= 0

	IF EXISTS(SELECT NAME FROM TEMPDB..SYSOBJECTS WHERE NAME = N'##V2_LEDGERBALANCE_APP')
		DROP TABLE ##V2_LEDGERBALANCE_APP

	SELECT
		PARTYCODE = L.CLTCODE,
		PARTYNAME = ACNAME,
		BRANCHCODE,
		SUB_BROKER,
		BTOBPAYMENT,
		CLIENTTYPE,
		L.EXCHANGE,
		L.SEGMENT,
		L.LEDBAL,
		AMTTOPAY = CASE WHEN L.LEDBAL < AMTTOPAY THEN L.LEDBAL ELSE AMTTOPAY END,
		PAYMODE,
		BANKCODE,
		FAMILYCODE,
		FAM_LEDBAL = ISNULL(FAM_LEDBAL,0),
		NET_LEDBAL = ISNULL(NET_LEDBAL,0),
		TOT_LEDBAL = ISNULL(TOT_LEDBAL,0),
		TOT_AMTTOPAY = ISNULL(TOT_AMTTOPAY,0),
		CASH = ISNULL(CASH,0),
		NONCASH = ISNULL(NONCASH,0),
		COLLATERAL = ISNULL(COLLATERAL,0),
		IMR = ISNULL(IMR,0),
		EMR = ISNULL(EMR,0),
		MARGIN = ISNULL(MARGIN,0),
		MARGINDATE = ISNULL(CONVERT(VARCHAR(11),MARGINDATE),' '),
		FOLEDBAL = ISNULL(F.LEDBAL,0),
		REMARK,
		SRNO,
		STATUS
	INTO
		##V2_LEDGERBALANCE_APP
	FROM
		#V2_LEDGERTMP L WITH(NOLOCK)
		LEFT OUTER JOIN
		#V2_LEDGERBALANCE_NET N WITH(NOLOCK)
		ON CLTCODE = PARTY_CODE
		LEFT OUTER JOIN
		V2_FOLEDBAL F WITH(NOLOCK)
		ON PARTY_CODE = F.CLTCODE
		AND L.EXCHANGE = F.EXCHANGE
		AND L.SEGMENT = F.SEGMENT
	ORDER BY
		BRANCHCODE,
		L.CLTCODE,
		L.SEGMENT,
		L.EXCHANGE DESC

	DELETE
		L
	FROM
		#V2_LEDGERBALANCEUP L,
		#V2_LEDGERTMP T
	WHERE
		L.PARTYCODE = T.CLTCODE
		AND L.EXCHANGE = T.EXCHANGE
		AND L.SEGMENT = T.SEGMENT

	DELETE #V2_LEDGERBALANCEUP WHERE LEDBAL > 0

	UPDATE
		A
	SET
		AMTTOPAY = CASE WHEN A.LEDBAL + L.LEDBAL < A.AMTTOPAY THEN A.LEDBAL + L.LEDBAL ELSE A.AMTTOPAY END,
		NET_LEDBAL = CASE WHEN A.NET_LEDBAL + L.LEDBAL < A.NET_LEDBAL THEN A.NET_LEDBAL + L.LEDBAL ELSE A.NET_LEDBAL END,
		TOT_LEDBAL = CASE WHEN A.TOT_LEDBAL + L.LEDBAL < A.TOT_LEDBAL THEN A.TOT_LEDBAL + L.LEDBAL ELSE A.TOT_LEDBAL END,
		TOT_AMTTOPAY = CASE WHEN A.NET_LEDBAL + L.LEDBAL < A.TOT_AMTTOPAY THEN A.NET_LEDBAL + L.LEDBAL ELSE A.TOT_AMTTOPAY END
	FROM
		##V2_LEDGERBALANCE_APP A,
		#V2_LEDGERBALANCEUP L
	WHERE
		L.PARTYCODE = A.PARTYCODE
		AND A.EXCHANGE IN ('NSE', 'BSE')
		AND A.SEGMENT IN ('CAPITAL', 'FUTURES')

	UPDATE
		##V2_LEDGERBALANCE_APP
	SET
		AMTTOPAY = 0
	WHERE
		AMTTOPAY < 0

/*------------------------------------------------EOF---------------------------------------------------*/

GO
