-- Object: PROCEDURE dbo.BAK_RPT_CASH_REPORTING_DIFF_MRG_12052023
-- Server: 10.253.33.91 | DB: ACCOUNT
--------------------------------------------------









CREATE PROC [dbo].[BAK_RPT_CASH_REPORTING_DIFF_MRG_12052023] (@FDATE VARCHAR(11),@TDATE VARCHAR(11))

AS

-- EXEC RPT_CASH_REPORTING_DIFF_MRG 'FEB 17 2023','FEB 17 2023'

SET @TDATE = @FDATE
                    
SELECT A.EXCHANGE,A.SEGMENT,A.PARTY_CODE,MARGINDATE,TDAY_LEDGER = SUM(TDAY_LEDGER),TDAY_MARGIN = SUM(TDAY_MARGIN),TDAY_CASHCOLL = SUM(TDAY_CASHCOLL),
TDAY_NONCASH = SUM(TDAY_NONCASH),TDAY_MTM = SUM(TDAY_MTM)             
INTO #MARGIN                    
FROM MSAJAG.DBO.TBL_COMBINE_REPORTING_DETAIL A WITH (NOLOCK) WHERE  MARGINDATE BETWEEN @FDATE AND @TDATE + ' 23:59'              
GROUP BY A.EXCHANGE,A.SEGMENT,A.PARTY_CODE,MARGINDATE  ORDER BY MARGINDATE,A.PARTY_CODE                    

                  
SELECT A.EXCHANGE,A.SEGMENT,A.PARTY_CODE,MARGINDATE,TDAY_LEDGER = SUM(TDAY_LEDGER),TDAY_MARGIN = SUM(TDAY_MARGIN),TDAY_CASHCOLL = SUM(TDAY_CASHCOLL),
TDAY_NONCASH = SUM(TDAY_NONCASH),TDAY_MTM = SUM(TDAY_MTM)             
INTO #MARGIN_PEAK                    
FROM MSAJAG.DBO.TBL_COMBINE_REPORTING_PEAK_DETAIL A WITH (NOLOCK) WHERE  MARGINDATE BETWEEN @FDATE AND @TDATE + ' 23:59'              
GROUP BY A.EXCHANGE,A.SEGMENT,A.PARTY_CODE,MARGINDATE  ORDER BY MARGINDATE,A.PARTY_CODE                    


DELETE #MARGIN WHERE PARTY_CODE IN ('12798','BBBB','ERROR')

DELETE #MARGIN_PEAK WHERE PARTY_CODE IN ('12798','BBBB','ERROR')
                
SELECT DISTINCT PARTY_CODE AS CL_CODE INTO #EXCHANGE_CLINETS_DISTINCT_MAR FROM #MARGIN WHERE (TDAY_MARGIN <> 0 OR TDAY_MTM <> 0 )
SELECT DISTINCT PARTY_CODE AS CL_CODE INTO #EXCHANGE_CLINETS_DISTINCT_MAR_PEAK FROM #MARGIN_PEAK WHERE (TDAY_MARGIN <> 0 OR TDAY_MTM <> 0 )


CREATE INDEX CLIIDX ON #EXCHANGE_CLINETS_DISTINCT_MAR(CL_CODE)
CREATE INDEX CLIIDX ON #EXCHANGE_CLINETS_DISTINCT_MAR_PEAK(CL_CODE)

DELETE #MARGIN WHERE PARTY_CODE NOT IN (SELECT CL_CODE FROM #EXCHANGE_CLINETS_DISTINCT_MAR)
DELETE #MARGIN_PEAK WHERE PARTY_CODE NOT IN (SELECT CL_CODE FROM #EXCHANGE_CLINETS_DISTINCT_MAR_PEAK)

SELECT CLTCODE,SUM(VAMT)*-1 AS VAMT INTO #LEDGER_REC
FROM LEDGER WITH (NOLOCK) , #EXCHANGE_CLINETS_DISTINCT_MAR WHERE VDT BETWEEN @TDATE AND @TDATE + ' 23:59' AND CL_CODE = CLTCODE
AND EDT = CONVERT(DATETIME,@TDATE) + 1 AND VTYP = 2 GROUP BY CLTCODE

SELECT PARTY_CODE,SUM(TDAY_LEDGER) AS M_LEDGER INTO #MARGIN_FINAL FROM #MARGIN GROUP BY PARTY_CODE
SELECT PARTY_CODE,SUM(TDAY_LEDGER) AS M_LEDGER_PEAK INTO #MARGIN_FINAL_PEAK FROM #MARGIN_PEAK GROUP BY PARTY_CODE

SELECT REPORT_DATE,SNO INTO #CCE_MAR FROM ACCOUNT.DBO.CLIENT_CASH_DETAILS(NOLOCK) WHERE REPORT_DATE BETWEEN @FDATE AND @TDATE + ' 23:59'

SELECT REPORT_DATE,UCC=LTRIM(RTRIM(ISNULL(PARTY_CODE, ''))),  
EXCHANGE=CASE WHEN L.EXCHANGE='MTF' THEN 'MTF' ELSE 'BROKING' END,EDT_BAL=ROUND(L.EDT_BAL,2),PEAK_FINANCIAL_LEDGER,
EPI_LEDGER,POOL_ACCOUNT,CASH_COLL_MTF_POSITIONS
INTO #CCERPT_MAR  
FROM #CCE_MAR C, ACCOUNT.DBO.CLIENT_CASH_LED_BALANCES L WITH (NOLOCK) WHERE C.SNO = L.SNO  
AND EXCHANGE <> 'MTF'  

DELETE FROM #CCERPT_MAR WHERE UCC='BBBB'
  
SELECT REPORT_DATE,UCC=LTRIM(RTRIM(ISNULL(UCC, ''))),EDT_BAL=SUM(EDT_BAL),
PEAK_FINANCIAL_LEDGER = SUM(PEAK_FINANCIAL_LEDGER),EPI_LEDGER = SUM(EPI_LEDGER),POOL_ACCOUNT = SUM(POOL_ACCOUNT),
CASH_COLL_MTF_POSITIONS = SUM(CASH_COLL_MTF_POSITIONS)
INTO #CASHREPORTING_MAR  
FROM #CCERPT_MAR , #EXCHANGE_CLINETS_DISTINCT_MAR WHERE UCC BETWEEN 'A' AND 'ZZZZZZZZZZZZZZZZZ9999' 
AND UCC = CL_CODE
GROUP BY REPORT_DATE,UCC  

SELECT REPORT_DATE,UCC=LTRIM(RTRIM(ISNULL(UCC, ''))),EDT_BAL=SUM(EDT_BAL),
PEAK_FINANCIAL_LEDGER = SUM(PEAK_FINANCIAL_LEDGER),EPI_LEDGER = SUM(EPI_LEDGER),POOL_ACCOUNT = SUM(POOL_ACCOUNT),
CASH_COLL_MTF_POSITIONS = SUM(CASH_COLL_MTF_POSITIONS)
INTO #CASHREPORTING_MAR_PEAK  
FROM #CCERPT_MAR , #EXCHANGE_CLINETS_DISTINCT_MAR_PEAK WHERE UCC BETWEEN 'A' AND 'ZZZZZZZZZZZZZZZZZ9999' 
AND UCC = CL_CODE
GROUP BY REPORT_DATE,UCC  
  


/* EDT LEDGER BALANCE DATA */  
  
  
DECLARE @START_DATE VARCHAR(11)

IF LEN(@TDATE) = 10      
BEGIN      
 SELECT @TDATE = CONVERT(VARCHAR(11), CONVERT(DATETIME, @TDATE, 103), 109)      
END      
      
SELECT @START_DATE = CONVERT(VARCHAR(11), SDTCUR, 109) FROM ACCOUNT.DBO.PARAMETER WITH (NOLOCK) WHERE @TDATE BETWEEN SDTCUR AND LDTCUR

SELECT CLTCODE,EDTBAL=SUM(EDTBAL),EXCHANGE='NSECM' INTO #EDTBAL_DIFF_MAR FROM
(SELECT CLTCODE,    
EDTBAL = CASE WHEN EDT >= @START_DATE AND EDT <= @TDATE + ' 23:59' THEN SUM(CASE DRCR WHEN 'D' THEN VAMT ELSE -VAMT END) ELSE 0 END       
+ CASE WHEN EDT >= @START_DATE AND VDT < @START_DATE THEN SUM(CASE DRCR WHEN 'C' THEN VAMT ELSE -VAMT END) ELSE 0 END  
FROM
(SELECT VNO,LNO,VTYP,EDT,DRCR,VAMT,VDT,CLTCODE,BOOKTYPE,NARRATION FROM ACCOUNT.DBO.LEDGER (NOLOCK) , #EXCHANGE_CLINETS_DISTINCT_MAR WHERE CLTCODE = CL_CODE AND
EDT >= @START_DATE AND CDT <= DATEADD(MI, -15, GETDATE())     
AND VDT <= @TDATE + ' 23:59' AND CDT <= DATEADD(MI, -15, GETDATE())) L   
GROUP BY L.CLTCODE,L.VDT, EDT, L.VTYP, DRCR) A GROUP BY A.CLTCODE


INSERT INTO #EDTBAL_DIFF_MAR
SELECT CLTCODE,EDTBAL=SUM(EDTBAL),EXCHANGE='BSECM' FROM
(SELECT CLTCODE,          
EDTBAL = CASE WHEN EDT >= @START_DATE AND EDT <= @TDATE + ' 23:59' THEN SUM(CASE DRCR WHEN 'D' THEN VAMT ELSE -VAMT END) ELSE 0 END       
+ CASE WHEN EDT >= @START_DATE AND VDT < @START_DATE THEN SUM(CASE DRCR WHEN 'C' THEN VAMT ELSE -VAMT END) ELSE 0 END  
FROM       
(SELECT VNO,LNO,VTYP,EDT,DRCR,VAMT,VDT,CLTCODE,BOOKTYPE,NARRATION 
FROM AngelBSECM.ACCOUNT_AB.DBO.LEDGER WITH (NOLOCK) 
WHERE EDT >= @START_DATE AND VDT <= @TDATE + ' 23:59')    L 
GROUP BY L.CLTCODE,L.VDT, EDT, L.VTYP, DRCR) A GROUP BY A.CLTCODE

INSERT INTO #EDTBAL_DIFF_MAR
SELECT CLTCODE,EDTBAL=SUM(EDTBAL),EXCHANGE='NSEFO' FROM
(SELECT CLTCODE,    
EDTBAL = CASE WHEN EDT >= @START_DATE AND EDT <= @TDATE + ' 23:59' THEN SUM(CASE DRCR WHEN 'D' THEN VAMT ELSE -VAMT END) ELSE 0 END       
+ CASE WHEN EDT >= @START_DATE AND VDT < @START_DATE THEN SUM(CASE DRCR WHEN 'C' THEN VAMT ELSE -VAMT END) ELSE 0 END  
FROM       
(SELECT VNO,LNO,VTYP,EDT,DRCR,VAMT,VDT,CLTCODE,BOOKTYPE,NARRATION 
FROM ANGELFO.ACCOUNTFO.DBO.LEDGER WITH(NOLOCK)  
WHERE EDT >= @START_DATE AND VDT <= @TDATE + ' 23:59') L
GROUP BY L.CLTCODE,L.VDT, EDT, L.VTYP, DRCR) A GROUP BY A.CLTCODE

INSERT INTO #EDTBAL_DIFF_MAR
SELECT CLTCODE,EDTBAL=SUM(EDTBAL),EXCHANGE='BSEFO' FROM
(SELECT CLTCODE,    
EDTBAL = CASE WHEN EDT >= @START_DATE AND EDT <= @TDATE + ' 23:59' THEN SUM(CASE DRCR WHEN 'D' THEN VAMT ELSE -VAMT END) ELSE 0 END       
+ CASE WHEN EDT >= @START_DATE AND VDT < @START_DATE THEN SUM(CASE DRCR WHEN 'C' THEN VAMT ELSE -VAMT END) ELSE 0 END  
FROM       
(SELECT VNO,LNO,VTYP,EDT,DRCR,VAMT,VDT,CLTCODE,BOOKTYPE,NARRATION 
FROM  ANGELCOMMODITY.ACCOUNTBFO.DBO.LEDGER L WITH (NOLOCK)  
WHERE EDT >= @START_DATE AND VDT <= @TDATE + ' 23:59') L
GROUP BY L.CLTCODE,L.VDT, EDT, L.VTYP, DRCR) A GROUP BY A.CLTCODE


INSERT INTO #EDTBAL_DIFF_MAR
SELECT CLTCODE,EDTBAL=SUM(EDTBAL),EXCHANGE='NSECD' FROM
(SELECT CLTCODE,    
EDTBAL = CASE WHEN EDT >= @START_DATE AND EDT <= @TDATE + ' 23:59' THEN SUM(CASE DRCR WHEN 'D' THEN VAMT ELSE -VAMT END) ELSE 0 END       
+ CASE WHEN EDT >= @START_DATE AND VDT < @START_DATE THEN SUM(CASE DRCR WHEN 'C' THEN VAMT ELSE -VAMT END) ELSE 0 END  
FROM       
(SELECT VNO,LNO,VTYP,EDT,DRCR,VAMT,VDT,CLTCODE,BOOKTYPE,NARRATION 
FROM ANGELFO.ACCOUNTCURFO.DBO.LEDGER WITH(NOLOCK)  
WHERE EDT >= @START_DATE AND VDT <= @TDATE + ' 23:59') L 
GROUP BY L.CLTCODE,L.VDT, EDT, L.VTYP, DRCR) A GROUP BY A.CLTCODE


INSERT INTO #EDTBAL_DIFF_MAR
SELECT CLTCODE,EDTBAL=SUM(EDTBAL),EXCHANGE='BSECD' FROM
(SELECT CLTCODE,    
EDTBAL = CASE WHEN EDT >= @START_DATE AND EDT <= @TDATE + ' 23:59' THEN SUM(CASE DRCR WHEN 'D' THEN VAMT ELSE -VAMT END) ELSE 0 END       
+ CASE WHEN EDT >= @START_DATE AND VDT < @START_DATE THEN SUM(CASE DRCR WHEN 'C' THEN VAMT ELSE -VAMT END) ELSE 0 END  
FROM       
(SELECT VNO,LNO,VTYP,EDT,DRCR,VAMT,VDT,CLTCODE,BOOKTYPE,NARRATION 
FROM ANGELCOMMODITY.ACCOUNTCURBFO.DBO.LEDGER WITH(NOLOCK)  
WHERE EDT >= @START_DATE AND VDT <= @TDATE + ' 23:59' ) L 
GROUP BY L.CLTCODE,L.VDT, EDT, L.VTYP, DRCR) A GROUP BY A.CLTCODE


INSERT INTO #EDTBAL_DIFF_MAR
SELECT CLTCODE,EDTBAL=SUM(EDTBAL),EXCHANGE='MCXCD' FROM
(SELECT CLTCODE,    
EDTBAL = CASE WHEN EDT >= @START_DATE AND EDT <= @TDATE + ' 23:59' THEN SUM(CASE DRCR WHEN 'D' THEN VAMT ELSE -VAMT END) ELSE 0 END       
+ CASE WHEN EDT >= @START_DATE AND VDT < @START_DATE THEN SUM(CASE DRCR WHEN 'C' THEN VAMT ELSE -VAMT END) ELSE 0 END  
FROM       
(SELECT VNO,LNO,VTYP,EDT,DRCR,VAMT,VDT,CLTCODE,BOOKTYPE,NARRATION 
FROM ANGELCOMMODITY.ACCOUNTMCDXCDS.DBO.LEDGER WITH(NOLOCK)  
WHERE EDT >= @START_DATE AND VDT <= @TDATE + ' 23:59') L 
GROUP BY L.CLTCODE,L.VDT, EDT, L.VTYP, DRCR) A GROUP BY A.CLTCODE


INSERT INTO #EDTBAL_DIFF_MAR
SELECT CLTCODE,EDTBAL=SUM(EDTBAL),EXCHANGE='SLBS' FROM
(SELECT CLTCODE,    
EDTBAL = CASE WHEN EDT >= @START_DATE AND EDT <= @TDATE + ' 23:59' THEN SUM(CASE DRCR WHEN 'D' THEN VAMT ELSE -VAMT END) ELSE 0 END       
+ CASE WHEN EDT >= @START_DATE AND VDT < @START_DATE THEN SUM(CASE DRCR WHEN 'C' THEN VAMT ELSE -VAMT END) ELSE 0 END  
FROM       
(SELECT VNO,LNO,VTYP,EDT,DRCR,VAMT,VDT,CLTCODE,BOOKTYPE,NARRATION 
FROM ACCOUNTSLBS.DBO.LEDGER WITH(NOLOCK)  
WHERE EDT >= @START_DATE AND VDT <= @TDATE + ' 23:59') L
GROUP BY L.CLTCODE,L.VDT, EDT, L.VTYP, DRCR) A GROUP BY A.CLTCODE


INSERT INTO #EDTBAL_DIFF_MAR
SELECT CLTCODE,EDTBAL=SUM(EDTBAL),EXCHANGE='MCDX' FROM
(SELECT CLTCODE,    
EDTBAL = CASE WHEN EDT >= @START_DATE AND EDT <= @TDATE + ' 23:59' THEN SUM(CASE DRCR WHEN 'D' THEN VAMT ELSE -VAMT END) ELSE 0 END       
+ CASE WHEN EDT >= @START_DATE AND VDT < @START_DATE THEN SUM(CASE DRCR WHEN 'C' THEN VAMT ELSE -VAMT END) ELSE 0 END  
FROM       
(SELECT VNO,LNO,VTYP,EDT,DRCR,VAMT,VDT,CLTCODE,BOOKTYPE,NARRATION 
FROM ANGELCOMMODITY.ACCOUNTMCDX.DBO.LEDGER WITH(NOLOCK)  
WHERE EDT >= @START_DATE AND VDT <= @TDATE + ' 23:59') L 
GROUP BY L.CLTCODE,L.VDT, EDT, L.VTYP, DRCR) A GROUP BY A.CLTCODE


INSERT INTO #EDTBAL_DIFF_MAR
SELECT CLTCODE,EDTBAL=SUM(EDTBAL),EXCHANGE='NCDX' FROM
(SELECT CLTCODE,    
EDTBAL = CASE WHEN EDT >= @START_DATE AND EDT <= @TDATE + ' 23:59' THEN SUM(CASE DRCR WHEN 'D' THEN VAMT ELSE -VAMT END) ELSE 0 END       
+ CASE WHEN EDT >= @START_DATE AND VDT < @START_DATE THEN SUM(CASE DRCR WHEN 'C' THEN VAMT ELSE -VAMT END) ELSE 0 END  
FROM       
(SELECT VNO,LNO,VTYP,EDT,DRCR,VAMT,VDT,CLTCODE,BOOKTYPE,NARRATION 
FROM ANGELCOMMODITY.ACCOUNTNCDX.DBO.LEDGER WITH(NOLOCK)  
WHERE EDT >= @START_DATE AND VDT <= @TDATE + ' 23:59') L  
GROUP BY L.CLTCODE,L.VDT, EDT, L.VTYP, DRCR) A GROUP BY A.CLTCODE


SELECT CLTCODE,TB_EDT=SUM(ROUND(EDTBAL,2)) INTO #TBEDT_MAR FROM #EDTBAL_DIFF_MAR  , #EXCHANGE_CLINETS_DISTINCT_MAR
WHERE  CLTCODE  = CL_CODE
GROUP BY CLTCODE

 
/* DIFF CLIENT DATA FILE EXPORT */ 


SELECT UCC,
TB_EDT_AMOUNT=ROUND(SUM(CLASS_LEDGER),0),M_LEDGER=ROUND(SUM(M_LEDGER),0),CCE_EDT_AMOUNT=ROUND(SUM(CASH_EDT_BAL),0),REC_AMT_T1 = CONVERT(NUMERIC(18,2),0) 
INTO #DIFF_DATA_MAR  
FROM (  
SELECT UCC,CLASS_LEDGER=CONVERT(MONEY,0),M_LEDGER=CONVERT(MONEY,0),CASH_EDT_BAL=EDT_BAL FROM #CASHREPORTING_MAR  
UNION ALL  
SELECT PARTY_CODE,CLASS_LEDGER=CONVERT(MONEY,0),M_LEDGER=M_LEDGER,CASH_EDT_BAL=CONVERT(MONEY,0) FROM #MARGIN_FINAL   
UNION ALL  
SELECT CLTCODE,CLASS_LEDGER=TB_EDT,M_LEDGER=CONVERT(MONEY,0),CASH_EDT_BAL=CONVERT(MONEY,0) FROM #TBEDT_MAR ) A  
GROUP BY UCC  


UPDATE #DIFF_DATA_MAR SET REC_AMT_T1 = VAMT FROM #LEDGER_REC WHERE UCC = CLTCODE

SELECT UCC,TDAY_CASHCOLL=ROUND(SUM(TDAY_CASHCOLL),2),EPI_LEDGER=ROUND(SUM(EPI_LEDGER),2) INTO #DIFF_DATA_EPN  
FROM (  
SELECT UCC,TDAY_CASHCOLL=CONVERT(MONEY,0),EPI_LEDGER=EPI_LEDGER FROM #CASHREPORTING_MAR  WHERE EPI_LEDGER <> 0 
UNION ALL  
SELECT PARTY_CODE,TDAY_CASHCOLL=TDAY_CASHCOLL,EPI_LEDGER=CONVERT(MONEY,0) FROM #MARGIN  WHERE EXCHANGE  = 'EPN' AND TDAY_CASHCOLL <> 0 
) A  
GROUP BY UCC  


SELECT UCC,TDAY_NONCASH=ROUND(SUM(TDAY_NONCASH),0),POOL_ACCOUNT=ROUND(SUM(POOL_ACCOUNT),0) INTO #DIFF_DATA_POOL  
FROM (  
SELECT UCC,TDAY_NONCASH=CONVERT(MONEY,0),POOL_ACCOUNT=POOL_ACCOUNT FROM #CASHREPORTING_MAR  WHERE POOL_ACCOUNT <> 0 
UNION ALL  
SELECT PARTY_CODE,TDAY_NONCASH=TDAY_NONCASH,POOL_ACCOUNT=CONVERT(MONEY,0) FROM #MARGIN  WHERE EXCHANGE  = 'EPN' AND TDAY_NONCASH <>0
) A  
GROUP BY UCC  


SELECT UCC,M_LEDGER_PEAK=ROUND(SUM(M_LEDGER_PEAK),2),PEAK_FINANCIAL_LEDGER=ROUND(SUM(PEAK_FINANCIAL_LEDGER),2) INTO #DIFF_DATA_PEAK  
FROM (  
SELECT UCC,M_LEDGER_PEAK=CONVERT(MONEY,0),PEAK_FINANCIAL_LEDGER=PEAK_FINANCIAL_LEDGER FROM #CASHREPORTING_MAR_PEAK  WHERE PEAK_FINANCIAL_LEDGER <> 0 
UNION ALL  
SELECT PARTY_CODE,M_LEDGER_PEAK=M_LEDGER_PEAK,PEAK_FINANCIAL_LEDGER=CONVERT(MONEY,0) FROM #MARGIN_FINAL_PEAK
) A  
GROUP BY UCC 

SELECT Report_Date,REPORT,SUM([Balance In TB]) AS [Balance In TB],SUM([Balance In CCE]) AS [Balance In CCE],SUM([Balance In Margin]) AS [Balance In Margin],
REC_AMT_T1 = CONVERT(NUMERIC(18,2),0),DIFF_TB_CCE = 0 ,DIFF_TB_MAR = 0 ,DIFF_CCE_MAR = 0 INTO #CHECK FROM (
SELECT Report_Date=CONVERT(VARCHAR(11),CONVERT(DATETIME,@TDATE),105),Report='EDT-Balance',[Balance In TB]=ABS(SUM(ROUND(TB_EDT,2))),[Balance In CCE] = 0,
[Balance In Margin] = 0,DIFF_TB_CCE=CONVERT(MONEY,0),DIFF_TB_MAR=CONVERT(MONEY,0),DIFF_CCE_MAR=CONVERT(MONEY,0)
FROM #TBEDT_MAR
UNION ALL
SELECT Report_Date=CONVERT(VARCHAR(11),CONVERT(DATETIME,@TDATE),105),Report='EDT-Balance',[Balance In TB]=0,[Balance In CCE]=ABS(SUM(ROUND(EDT_BAL,2))),
[Balance In Margin] = 0,DIFF_TB_CCE=CONVERT(MONEY,0),DIFF_TB_MAR=CONVERT(MONEY,0),DIFF_CCE_MAR=CONVERT(MONEY,0)
FROM #CASHREPORTING_MAR
UNION ALL
SELECT Report_Date=CONVERT(VARCHAR(11),CONVERT(DATETIME,@TDATE),105),Report='EDT-Balance',[Balance In TB]=0,[Balance In CCE] = 0,
[Balance In Margin]=ABS(SUM(ROUND(M_LEDGER,2))), DIFF_TB_CCE=CONVERT(MONEY,0),DIFF_TB_MAR=CONVERT(MONEY,0),DIFF_CCE_MAR=CONVERT(MONEY,0)
FROM #MARGIN_FINAL
UNION ALL
SELECT Report_Date=CONVERT(VARCHAR(11),CONVERT(DATETIME,@TDATE),105),Report='EPN Amount',[Balance In TB]=0,[Balance In CCE]=ABS(SUM(ROUND(EPI_LEDGER,2))),
[Balance In Margin] = 0,DIFF_TB_CCE=CONVERT(MONEY,0),DIFF_TB_MAR=CONVERT(MONEY,0),DIFF_CCE_MAR=CONVERT(MONEY,0)
FROM #CASHREPORTING_MAR WHERE EPI_LEDGER <> 0 
UNION ALL
SELECT Report_Date=CONVERT(VARCHAR(11),CONVERT(DATETIME,@TDATE),105),Report='EPN Amount',[Balance In TB]= 0,[Balance In CCE] = 0,
[Balance In Margin]=ABS(SUM(ROUND(TDAY_CASHCOLL,2))),
DIFF_TB_CCE=CONVERT(MONEY,0),DIFF_TB_MAR=CONVERT(MONEY,0),DIFF_CCE_MAR=CONVERT(MONEY,0)
FROM #MARGIN WHERE EXCHANGE  = 'EPN' AND TDAY_CASHCOLL <> 0
UNION ALL
SELECT Report_Date=CONVERT(VARCHAR(11),CONVERT(DATETIME,@TDATE),105),Report='POOL Amount',[Balance In TB] = 0,[Balance In CCE] = ABS(SUM(ROUND(POOL_ACCOUNT,2))),
[Balance In Margin] = 0,DIFF_TB_CCE=CONVERT(MONEY,0),DIFF_TB_MAR=CONVERT(MONEY,0),DIFF_CCE_MAR=CONVERT(MONEY,0)
FROM #CASHREPORTING_MAR WHERE POOL_ACCOUNT <> 0 
UNION ALL
SELECT Report_Date=CONVERT(VARCHAR(11),CONVERT(DATETIME,@TDATE),105),Report='POOL Amount',[Balance In TB] = 0,[Balance In CCE] = 0,
[Balance In Margin]=ABS(SUM(ROUND(TDAY_NONCASH,2))),DIFF_TB_CCE=CONVERT(MONEY,0),DIFF_TB_MAR=CONVERT(MONEY,0),DIFF_CCE_MAR=CONVERT(MONEY,0)
FROM #MARGIN WHERE EXCHANGE  = 'EPN' AND TDAY_NONCASH <> 0
UNION ALL
SELECT Report_Date=CONVERT(VARCHAR(11),CONVERT(DATETIME,@TDATE),105),Report='PEAK-Balance',[Balance In TB]=0,[Balance In CCE]=ABS(SUM(ROUND(PEAK_FINANCIAL_LEDGER,2))),
[Balance In Margin] = 0,DIFF_TB_CCE=CONVERT(MONEY,0),DIFF_TB_MAR=CONVERT(MONEY,0),DIFF_CCE_MAR=CONVERT(MONEY,0)
FROM #CASHREPORTING_MAR_PEAK
UNION ALL
SELECT Report_Date=CONVERT(VARCHAR(11),CONVERT(DATETIME,@TDATE),105),Report='PEAK-Balance',[Balance In TB]=0,[Balance In CCE] = 0,
[Balance In Margin]=ABS(SUM(ROUND(M_LEDGER_PEAK,2))), DIFF_TB_CCE=CONVERT(MONEY,0),DIFF_TB_MAR=CONVERT(MONEY,0),DIFF_CCE_MAR=CONVERT(MONEY,0)
FROM #MARGIN_FINAL_PEAK) A 
GROUP BY Report_Date,REPORT


SELECT REPORT='EDT-Balance',UCC,TB_EDT_AMOUNT,M_LEDGER,REC_AMT_T1,CCE_EDT_AMOUNT INTO #CHECK1 
FROM #DIFF_DATA_MAR  WHERE (ABS(TB_EDT_AMOUNT) <> ABS(CCE_EDT_AMOUNT) OR ABS(TB_EDT_AMOUNT) <> ABS(M_LEDGER) 
OR  ABS(CCE_EDT_AMOUNT) <>  ABS(M_LEDGER))  
UNION ALL
SELECT REPORT='EPN Amount',UCC,TB_EDT_AMOUNT=0,M_LEDGER=TDAY_CASHCOLL,REC_AMT_T1=0,CCE_EDT_AMOUNT=EPI_LEDGER
FROM #DIFF_DATA_EPN  WHERE (ABS(TDAY_CASHCOLL) <> ABS(EPI_LEDGER) )  
UNION ALL
SELECT REPORT='Pool Amount',UCC,TB_EDT_AMOUNT=0,M_LEDGER=TDAY_NONCASH,REC_AMT_T1=0,CCE_EDT_AMOUNT=POOL_ACCOUNT
FROM #DIFF_DATA_POOL  WHERE (ABS(TDAY_NONCASH) <> ABS(POOL_ACCOUNT))
UNION ALL
SELECT REPORT='PEAK-Balance',UCC,TB_EDT_AMOUNT=0,M_LEDGER=M_LEDGER_PEAK,REC_AMT_T1=0,CCE_EDT_AMOUNT=PEAK_FINANCIAL_LEDGER
FROM #DIFF_DATA_PEAK  WHERE (ABS(M_LEDGER_PEAK) <> ABS(PEAK_FINANCIAL_LEDGER)) 


SELECT *,(CONVERT(NUMERIC(18,2),TB_EDT_AMOUNT)+CONVERT(NUMERIC(18,2),M_LEDGER)) AS DIFF, 
(CONVERT(NUMERIC(18,2),TB_EDT_AMOUNT)+CONVERT(NUMERIC(18,2),M_LEDGER+REC_AMT_T1)) AS DIFF1
INTO #CHECK2 FROM #CHECK1 WHERE REPORT='EDT-Balance' 
AND (CONVERT(NUMERIC(18,2),TB_EDT_AMOUNT)+CONVERT(NUMERIC(18,2),M_LEDGER)) NOT BETWEEN -1 AND 1

ALTER TABLE #CHECK ALTER COLUMN DIFF_TB_CCE NUMERIC(18,2)

ALTER TABLE #CHECK ALTER COLUMN DIFF_TB_MAR NUMERIC(18,2)

ALTER TABLE #CHECK ALTER COLUMN DIFF_CCE_MAR NUMERIC(18,2)

UPDATE #CHECK SET REC_AMT_T1 = (SELECT VAMT FROM (SELECT SUM(REC_AMT_T1) AS VAMT FROM #CHECK2 ) AS A) WHERE REPORT = 'EDT-Balance'

--UPDATE #CHECK SET DIFF_TB_CCE = [Balance In TB] - [Balance In CCE], DIFF_TB_MAR =  [Balance In TB] - ([Balance In Margin] + REC_AMT_T1), 
--DIFF_CCE_MAR =  [Balance In CCE] - ([Balance In Margin] + REC_AMT_T1) WHERE REPORT = 'EDT-Balance'

UPDATE #CHECK SET DIFF_TB_CCE = [Balance In TB] - [Balance In CCE], DIFF_TB_MAR =  [Balance In TB] - ([Balance In Margin]), 
DIFF_CCE_MAR =  [Balance In CCE] - ([Balance In Margin]) WHERE REPORT = 'EDT-Balance'

UPDATE #CHECK SET DIFF_CCE_MAR =  [Balance In CCE] - [Balance In Margin] WHERE REPORT <> 'EDT-Balance'


--SELECT REPORT,UCC,TB_EDT_AMOUNT,M_LEDGER,CCE_EDT_AMOUNT FROM #CHECK2 WHERE DIFF1 NOT BETWEEN -1 AND 1

TRUNCATE TABLE RPT_CASH_REPORTING_DIFF_MRG_ANG

INSERT INTO  RPT_CASH_REPORTING_DIFF_MRG_ANG
SELECT REPORT,UCC,TB_EDT_AMOUNT,M_LEDGER,CCE_EDT_AMOUNT  FROM #CHECK2 WHERE DIFF NOT BETWEEN -1 AND 1
UNION ALL
SELECT REPORT,UCC,TB_EDT_AMOUNT,M_LEDGER,CCE_EDT_AMOUNT FROM #CHECK1 WHERE REPORT <> 'EDT-Balance'

TRUNCATE TABLE RPT_CASH_REPORTING_DIFF_MRG_ANG_SUMM

INSERT INTO RPT_CASH_REPORTING_DIFF_MRG_ANG_SUMM
SELECT REPORT_DATE,REPORT,[BALANCE IN TB],[BALANCE IN CCE],[BALANCE IN MARGIN],[DIFF_TB_CCE],[DIFF_TB_MAR],[DIFF_CCE_MAR] FROM #CHECK


DECLARE @FNOFILENAME VARCHAR(1000) = 'J:\BACKOFFICE\EXPORT\' +'RPT_CASH_REPORTING_DIFF_MRG_' + CONVERT(VARCHAR,CONVERT(DATETIME, @FDATE), 112) + '.CSV'        
DECLARE @FNO VARCHAR(1000)                                    
SET @FNO = 'EXEC MASTER.DBO.XP_CMDSHELL ''BCP "SELECT ''''REPORT'''',''''UCC'''',''''TB_EDT_AMOUNT'''',''''M_LEDGER'''',''''CCE_EDT_AMOUNT'''''         
SET @FNO = @FNO + ' UNION ALL SELECT REPORT,LTRIM(RTRIM(UCC)),CONVERT(VARCHAR,TB_EDT_AMOUNT),CONVERT(VARCHAR,M_LEDGER),CONVERT(VARCHAR,CCE_EDT_AMOUNT) FROM ACCOUNT.DBO.RPT_CASH_REPORTING_DIFF_MRG_ANG" QUERYOUT ' +@FNOFILENAME+ ' -c -t"," -c -t"," -r"\n" -T'', NO_OUTPUT'        
EXEC(@FNO)      
      
DECLARE @FNOFILENAMES VARCHAR(1000) = 'J:\BACKOFFICE\EXPORT\' +'RPT_CASH_REPORTING_DIFF_MRG_SUMM_' + CONVERT(VARCHAR,CONVERT(DATETIME, @FDATE), 112) + '.CSV'      
DECLARE @FNOS VARCHAR(1000)                                    
SET @FNOS = 'EXEC MASTER.DBO.XP_CMDSHELL ''BCP "SELECT ''''REPORT_DATE'''',''''REPORT'''',''''BALANCE IN TB'''',''''BALANCE IN CCE'''',''''BALANCE IN MARGIN'''',''''DIFF_TB_CCE'''',''''DIFF_TB_MAR'''',''''DIFF_CCE_MAR'''''         
SET @FNOS = @FNOS + ' UNION ALL SELECT REPORT_DATE,LTRIM(RTRIM(REPORT)),CONVERT(VARCHAR,[BALANCE IN TB]),CONVERT(VARCHAR,[BALANCE IN CCE]),CONVERT(VARCHAR,[BALANCE IN MARGIN]),CONVERT(VARCHAR,[DIFF_TB_CCE]),CONVERT(VARCHAR,[DIFF_TB_MAR]),CONVERT(VARCHAR,[DIFF_CCE_MAR])  FROM ACCOUNT.DBO.RPT_CASH_REPORTING_DIFF_MRG_ANG_SUMM" QUERYOUT ' +@FNOFILENAMES+ ' -c -t"," -c -t"," -r"\n" -T'', NO_OUTPUT'        
EXEC(@FNOS)   

SELECT * FROM RPT_CASH_REPORTING_DIFF_MRG_ANG_SUMM

DROP TABLE #MARGIN
DROP TABLE #MARGIN_FINAL
DROP TABLE #CASHREPORTING_MAR
DROP TABLE #TBEDT_MAR
DROP TABLE #DIFF_DATA_POOL
DROP TABLE #DIFF_DATA_EPN
DROP TABLE #DIFF_DATA_MAR
DROP TABLE #EDTBAL_DIFF_MAR
DROP TABLE #EXCHANGE_CLINETS_DISTINCT_MAR
DROP TABLE #CCE_MAR
DROP TABLE #CCERPT_MAR
DROP TABLE #CHECK
DROP TABLE #CHECK1
DROP TABLE #LEDGER_REC
DROP TABLE #CHECK2
DROP TABLE #MARGIN_PEAK
DROP TABLE #DIFF_DATA_PEAK
DROP TABLE #EXCHANGE_CLINETS_DISTINCT_MAR_PEAK
DROP TABLE #MARGIN_FINAL_PEAK
DROP TABLE #CASHREPORTING_MAR_PEAK

GO
