-- Object: PROCEDURE dbo.NBFC_ENET_RECO
-- Server: 10.253.33.91 | DB: ACCOUNT
--------------------------------------------------


CREATE PROC [dbo].[NBFC_ENET_RECO]
(
	@ENET_FLAG	VARCHAR(20)
)
AS

	SELECT CLTCODE, VDT,
	AMOUNT=SUM(CASE WHEN DRCR = 'C' 
					THEN VAMT 
					ELSE -VAMT 
			   END), 
	ACTNODAYS, ENET_AMT = CONVERT(NUMERIC(18,4),0),
	ENET_REF_NO = CONVERT(VARCHAR(20),''),
	RECO_DATE = CONVERT(DATETIME, LEFT(GETDATE(),11)),
	Vno = (case when ENTEREDBY = 'ANIMESH' then '' else Vno end)
	INTO #MAINDATA
	FROM LEDGER L
	WHERE vtyp in (2,3)
	--ENTEREDBY = 'ANIMESH'
	AND CLTCODE IN (SELECT CLIENTCODE FROM ABVSCITRUS.NBFC.DBO.TBL_ENET_STATUS
					WHERE CLIENTCODE = CLTCODE 
					AND VDT <= ENET_FILE_DATE)
	AND VNO IN (SELECT VNO FROM LEDGER1 L1
	WHERE L.VNO = L1.VNO AND L.VTYP = L1.VTYP AND L.BOOKTYPE = L1.BOOKTYPE 
	AND ISNULL(DDNO,'100214') = '100214')
	GROUP BY VDT, CLTCODE, ACTNODAYS, (case when ENTEREDBY = 'ANIMESH' then '' else Vno end)
	ORDER BY CLTCODE

	UPDATE #MAINDATA SET ENET_AMT = (CASE WHEN @ENET_FLAG = 'AC62' THEN -T.ENET_AMT ELSE T.ENET_AMT END), 
	ENET_REF_NO = T.ENET_REF_NO, RECO_DATE = ENET_DATE
	FROM ABVSCITRUS.NBFC.DBO.TBL_ENET_STATUS T
	WHERE CLIENTCODE = CLTCODE

	SELECT L.VNO, VTYP, BOOKTYPE, ENET_REF_NO, RECO_DATE
	INTO #ENET_RECO_MAIN FROM LEDGER L, #MAINDATA D
	WHERE D.VDT = L.VDT
	AND   D.CLTCODE = L.CLTCODE
	AND   D.ACTNODAYS = L.ACTNODAYS
	AND L.VNO = (CASE WHEN ENTEREDBY = 'ANIMESH' THEN L.VNO ELSE D.VNO END)
	AND VTYP IN (2,3)
	AND   AMOUNT + ENET_AMT = 0

	UPDATE LEDGER1 SET DDNO = ENET_REF_NO
	FROM #ENET_RECO_MAIN E
	WHERE LEDGER1.VNO = E.VNO
	AND LEDGER1.VTYP = E.VTYP
	AND LEDGER1.BOOKTYPE = E.BOOKTYPE

	DROP TABLE #MAINDATA
	DROP TABLE #ENET_RECO_MAIN

GO
