-- Object: PROCEDURE dbo.CLS_RECON_MATCH_UNMATCH_REPORT_WRAPPER_BAK_JAN_02_2017
-- Server: 10.253.33.91 | DB: ACCOUNT
--------------------------------------------------




CREATE PROCEDURE [dbo].[CLS_RECON_MATCH_UNMATCH_REPORT_WRAPPER_BAK_JAN_02_2017]
(
         @FROM_DATE NVARCHAR(50)          
        ,@TO_DATE NVARCHAR(50)          
		,@BANKCODE NVARCHAR(30)
		,@MATCHEDFLAG NVARCHAR(30)
		,@FILETYPE NVARCHAR(30)
		,@BANKNAME NVARCHAR(30)
		,@SEGMENT NVARCHAR(30)
		,@PARAM_VAL1 NVARCHAR(MAX)
		,@BULKDELETE  NVARCHAR(20)
		,@LOGINNAME NVARCHAR(50)
		)

AS

IF @SEGMENT='0'
SET @SEGMENT = ''
IF (@FILETYPE = 'ALL'  OR @FILETYPE = '0') 
SET @FILETYPE = ''

IF UPPER(@FILETYPE)='ENCRYPTION'
BEGIN 
	SELECT * FROM RECON_ENCRYPTION_DETAILS (NOLOCK)
	WHERE (SEGMENT=@SEGMENT OR @SEGMENT='')
	AND (BANKNAME=@BANKNAME OR @BANKNAME='')
	AND INCRYPTIONDATE BETWEEN  CONVERT(DATETIME, @FROM_DATE, 105) AND CONVERT(DATETIME, @TO_DATE, 105)
	 
END
ELSE
BEGIN
CREATE TABLE #TEMP_REPORT_WRAPPER(ROWID INT NOT NULL IDENTITY (1, 1)
, FILEUPLOADID NVARCHAR(50)
, UPLOADDATE DATETIME
, EDATE DATETIME
, VALUEDATE DATETIME
, MATCHEDDATE DATETIME
--, SDATE				  DATETIME	
, SEGMENT NVARCHAR(50)
, BANK NVARCHAR(50)
, ARRANGEMENTTYPE NVARCHAR(50)
, BANKCODE NVARCHAR(50)
, BANKACCOUNT NVARCHAR(50)
, ACCOUNTNO NVARCHAR(70)
, NARRATION NVARCHAR(MAX)
, CHEQUENO NVARCHAR(50)
, DRCR NVARCHAR(5)
, BANKSTATEMENTAMOUNT MONEY
, VOUCHERAMOUNT MONEY
, BANKLOCATION NVARCHAR(50)
, ANGELLOCATION NVARCHAR(50)
, CLIENTCODE NVARCHAR(50)
, CLIENTNAME NVARCHAR(50)
, STATUS NVARCHAR(50)
, CROSSREFNO NVARCHAR(50)
, VOUCHERNO NVARCHAR(50)
, MATCHEDBY NVARCHAR(50)
, VOUCHERDATE NVARCHAR(50)
, DEPOSITDATE NVARCHAR(50)
, MATCHEDFLAG BIT
, VNO VARCHAR(15)
, VTYP INT
, BOOKTYPE VARCHAR(3)
, TRAN_STATUS VARCHAR(12)
, REPORT_FLAG NVARCHAR(100)
, UPLOADFILENAME NVARCHAR(100)
, UPLOADSTATUS NVARCHAR(15)
, FILEUPLOAD_SDATE DATETIME
, FILEUPLOAD_EDATE DATETIME
, USERNAME NVARCHAR(100)
--,PRIMARY KEY (ROWID, FILEUPLOADID,MATCHEDFLAG)							
)

CREATE TABLE #LEDGER_TO_MAP(VNO VARCHAR(12)
, VTYP INT
, BOOKTYPE VARCHAR(3)
, CLTCODE VARCHAR(10)
, DDNO VARCHAR(30)
, RELAMT MONEY
, DRCR CHAR(1)
, BANKSTATEMENTAMOUNT MONEY
, NARRATION NVARCHAR(250)
, CLIENTNAME NVARCHAR(100)
, VOUCHERNO NVARCHAR(15)
, VOUCHERDATE DATETIME
, SEGMENT VARCHAR(20))

IF @SEGMENT <> '' 
BEGIN


INSERT INTO #TEMP_REPORT_WRAPPER
EXEC [CLS_RECON_MATCH_UNMATCH_REPORT]	@FROM_DATE
										,@TO_DATE
										,@BANKCODE
										,@MATCHEDFLAG
										,@FILETYPE
										,@BANKNAME
										,@SEGMENT
										,@PARAM_VAL1
										,@BULKDELETE
										,@LOGINNAME




UPDATE TRW
SET	UPLOADFILENAME = RL.UPLOADFILENAME
	,UPLOADSTATUS = RL.UPLOADSTATUS
	,FILEUPLOAD_SDATE = RL.FILEUPLOAD_SDATE
	,FILEUPLOAD_EDATE = RL.FILEUPLOAD_EDATE
	,TRW.BANKACCOUNT = RBM.BANKACCOUNT
FROM RECON_BANK_FILEUPLOAD_LOGS RL, #TEMP_REPORT_WRAPPER TRW, RECON_BANK_MASTER_VW RBM
WHERE TRW.FILEUPLOADID = RL.UPLOADID
AND RBM.SEGMENT = RL.SEGMENT
AND RBM.FILETYPE = RL.FILETYPE
AND RBM.BankName = RL.BANKNAME
AND RBM.BANKCODE = RL.BANKCODE
AND (RL.FILETYPE = @FILETYPE OR @FILETYPE = '')
AND (RL.BANKNAME = @BANKNAME OR @BANKNAME = '')
AND (RL.SEGMENT = @SEGMENT OR @SEGMENT = '')

SELECT
	FILEUPLOADID AS UPLOADID
	,MAX(SEGMENT) SEGMENT
	,BANK AS 'BANKNAME'
	,BANKACCOUNT
	,ARRANGEMENTTYPE AS FILETYPE
	,CONVERT(VARCHAR(10), MAX(VALUEDATE), 105) VALUEDATE --R.VALUEDATE
	,UPLOADFILENAME
	,UPLOADSTATUS
	,MIN(CONVERT(NVARCHAR, FILEUPLOAD_SDATE, 120)) FILEUPLOAD_SDATE
	,MAX(CONVERT(NVARCHAR, FILEUPLOAD_EDATE, 120)) FILEUPLOAD_EDATE
FROM #TEMP_REPORT_WRAPPER
WHERE (ARRANGEMENTTYPE = @FILETYPE OR @FILETYPE = '')
AND (BANK = @BANKNAME OR @BANKNAME = '')
AND (SEGMENT = @SEGMENT OR @SEGMENT = '')
GROUP BY	FILEUPLOADID
			,SEGMENT
			,BANK
			,BANKACCOUNT
			,ARRANGEMENTTYPE
			,UPLOADFILENAME
			,UPLOADSTATUS

			IF(@BULKDELETE<>'BULK' OR @BULKDELETE<>'SummaryReport' OR @BULKDELETE='')
			BEGIN

					INSERT INTO #LEDGER_TO_MAP
						SELECT
							L.VNO
							,L.VTYP
							,L.BOOKTYPE
							,L.CLTCODE
							,L1.DDNO
							,L1.RELAMT
							,L1.DRCR
							,L1.RELAMT
							,L.NARRATION
							,L.ACNAME
							,L1.VNO
							,L.VDT
							,SEGMENT = @SEGMENT
						FROM	LEDGER L
								,LEDGER1 L1
								,#TEMP_REPORT_WRAPPER T
						WHERE L.VNO = L1.VNO
						AND L.VTYP = L1.VTYP
						AND L.LNO = L1.LNO
						AND L.BOOKTYPE = L1.BOOKTYPE
						AND L1.VNO = T.VNO
						AND L1.VTYP = T.VTYP
						AND L1.BOOKTYPE = T.BOOKTYPE
						AND EXISTS (SELECT VNO	FROM #TEMP_REPORT_WRAPPER L11 
							WHERE L11.VNO = L.VNO
							AND L11.VTYP = L.VTYP
							AND L11.BOOKTYPE = L.BOOKTYPE	
						)

					UPDATE T
					SET	BANKSTATEMENTAMOUNT = T.VOUCHERAMOUNT--L.BANKSTATEMENTAMOUNT
						,CLIENTCODE = L.CLTCODE
						,CLIENTNAME = L.CLIENTNAME
						,VOUCHERNO = L.VOUCHERNO
						,VOUCHERDATE = L.VOUCHERDATE
						,STATUS =CASE WHEN T.MATCHEDFLAG = 1 THEN 'RECONCILED'ELSE 'UNRECONCILED' END
						FROM #TEMP_REPORT_WRAPPER T
						, #LEDGER_TO_MAP L
						WHERE T.VNO = L.VNO
						AND T.VTYP = L.VTYP
						AND T.BOOKTYPE = L.BOOKTYPE
						AND T.DRCR = L.DRCR
						AND T.SEGMENT = L.SEGMENT
				END

	SELECT	* FROM #TEMP_REPORT_WRAPPER RL
	WHERE (RL.ARRANGEMENTTYPE = @FILETYPE OR @FILETYPE = '')
	AND (RL.BANK = @BANKNAME OR @BANKNAME = '')
	AND (RL.SEGMENT = @SEGMENT OR @SEGMENT = '')

	SELECT
	FILEUPLOADID AS UPLOADID
	,MAX(SEGMENT) SEGMENT
	,BANK AS 'BANKNAME'
	,BANKACCOUNT
	,ARRANGEMENTTYPE AS FILETYPE
	,CONVERT(VARCHAR(10), MAX(VALUEDATE), 105) VALUEDATE --R.VALUEDATE
	,UPLOADFILENAME
	,UPLOADSTATUS
	,MIN(CONVERT(NVARCHAR, FILEUPLOAD_SDATE, 120)) FILEUPLOAD_SDATE
	,MAX(CONVERT(NVARCHAR, FILEUPLOAD_EDATE, 120)) FILEUPLOAD_EDATE
	,DRCR
	,COUNT(DRCR) AS 'TOTALENTRIES'
	,SUM(CASE WHEN MATCHEDFLAG = 1 THEN 1 ELSE 0 END) AS 'RECONCILED'
	,SUM(CASE WHEN MATCHEDFLAG = 0 THEN 1 ELSE 0 END) AS 'UNRECONCILED'
	,(SUM(CASE WHEN MATCHEDFLAG = 1 THEN 1 ELSE 0 END) * 100 / COUNT(DRCR)) 'RECONCILED %'
	FROM #TEMP_REPORT_WRAPPER
	WHERE (ARRANGEMENTTYPE = @FILETYPE OR @FILETYPE = '')
	AND (BANK = @BANKNAME OR @BANKNAME = '')
	AND (SEGMENT = @SEGMENT OR @SEGMENT = '')
	GROUP BY	FILEUPLOADID
				,SEGMENT
				,BANK
				,BANKACCOUNT
				,ARRANGEMENTTYPE
				,UPLOADFILENAME
				,UPLOADSTATUS
				,DRCR

END 

ELSE 

BEGIN
		DECLARE @@ACCOUNTSERVER NVARCHAR(100),@@ACCOUNTDB NVARCHAR(100),@@SQL NVARCHAR(MAX),@@SEGMENT  NVARCHAR(50)
		DECLARE  @TEMP_SEGMENT TABLE(SEGMENT NVARCHAR(50), ACCOUNTDB NVARCHAR(100),ACCOUNTSERVER NVARCHAR(100))

		INSERT INTO @TEMP_SEGMENT
		SELECT DISTINCT  L.SEGMENT,ACCOUNTDB,ACCOUNTSERVER
		FROM	RECON_BANK_FILEUPLOAD_LOGS_VW L
		,PRADNYA.DBO.MULTICOMPANY P
		WHERE P.EXCHANGE + '-' + P.SEGMENT = L.SEGMENT
		AND PRIMARYSERVER = 1

WHILE (SELECT	COUNT(*)	FROM @TEMP_SEGMENT) > 0 
	BEGIN
		SELECT TOP 1	@@SEGMENT=SEGMENT, @@ACCOUNTDB = ACCOUNTDB	,@@ACCOUNTSERVER = ACCOUNTSERVER FROM @TEMP_SEGMENT
		SET @@SQL = ''
		SET @@SQL ="INSERT INTO #TEMP_REPORT_WRAPPER EXEC " 
		+ @@ACCOUNTSERVER + "." + @@ACCOUNTDB+ ".DBO.CLS_RECON_MATCH_UNMATCH_REPORT '"+ @FROM_DATE + "','" + @TO_DATE + "','" + @BANKCODE+ "','" 
				+ @MATCHEDFLAG + "','" + @FILETYPE + "','" + @BANKNAME + "','" +@@SEGMENT + "','" + @PARAM_VAL1 + "','" +  @BULKDELETE + "','" +  @LOGINNAME + "'"
				
		--SET @@SQL ="INSERT INTO #TEMP_REPORT_WRAPPER EXEC " + @@ACCOUNTSERVER + "." + @@ACCOUNTDB+ ".DBO.CLS_RECON_MATCH_UNMATCH_REPORT '"+ @FROM_DATE + "','" + @TO_DATE + "','" + @BANKCODE+ "','" 
		--		+ @MATCHEDFLAG + "','" + @FILETYPE + "','" + @BANKNAME + "','" +@@SEGMENT + "','" + @PARAM_VAL1 + "','" +  @BULKDELETE + "'"
		
		EXEC (@@SQL)
		PRINT @@SQL	 
		

		SET @@SQL = ''
		SET @@SQL ="UPDATE TRW SET	UPLOADFILENAME = RL.UPLOADFILENAME
					,UPLOADSTATUS = RL.UPLOADSTATUS
					,FILEUPLOAD_SDATE = RL.FILEUPLOAD_SDATE
					,FILEUPLOAD_EDATE = RL.FILEUPLOAD_EDATE
					,TRW.BANKACCOUNT = RL.BANKACCOUNT FROM "
					 + @@ACCOUNTSERVER + "." + @@ACCOUNTDB	+ ".[DBO].RECON_BANK_FILEUPLOAD_LOGS RL, #TEMP_REPORT_WRAPPER TRW
					WHERE TRW.FILEUPLOADID = RL.UPLOADID
					AND TRW.SEGMENT = RL.SEGMENT
					AND TRW.ARRANGEMENTTYPE = RL.FILETYPE
					AND TRW.Bank = RL.BANKNAME
					AND TRW.BANKCODE = RL.BANKCODE"
					--AND (RL.FILETYPE = @FILETYPE OR @FILETYPE='')
					--AND (RL.BANKNAME = @BANKNAME OR @BANKNAME='')
					--AND (RL.SEGMENT = @SEGMENT OR @SEGMENT='')
					EXEC (@@SQL)
					PRINT @@SQL

		DELETE FROM @TEMP_SEGMENT WHERE ACCOUNTDB = @@ACCOUNTDB AND SEGMENT=@@SEGMENT
	END
			SELECT
			FILEUPLOADID AS UPLOADID
			,CASE WHEN BANK='STANDARD CHARTERED BANK' THEN '' -- MAX(SEGMENT)
			WHEN BANK='YES BANK' THEN '' ELSE MAX(SEGMENT) END SEGMENT
			--SELECT
			--FILEUPLOADID AS UPLOADID
			--,'' AS SEGMENT --MAX(SEGMENT)
			,BANK AS 'BANKNAME'
			,MAX(BANKACCOUNT)BANKACCOUNT
			,ARRANGEMENTTYPE AS FILETYPE
			,CONVERT(VARCHAR(10), MAX(VALUEDATE), 105) VALUEDATE --R.VALUEDATE
			,UPLOADFILENAME
			,UPLOADSTATUS
			,MIN(CONVERT(NVARCHAR, FILEUPLOAD_SDATE, 120)) FILEUPLOAD_SDATE
			,MAX(CONVERT(NVARCHAR, FILEUPLOAD_EDATE, 120)) FILEUPLOAD_EDATE
			FROM #TEMP_REPORT_WRAPPER
			WHERE (ARRANGEMENTTYPE = @FILETYPE OR @FILETYPE='') AND (BANK = @BANKNAME OR @BANKNAME='') AND (SEGMENT = @SEGMENT OR @SEGMENT='')
			GROUP BY	FILEUPLOADID
			,BANK
			--,BANKACCOUNT
			,ARRANGEMENTTYPE
			,UPLOADFILENAME
			,UPLOADSTATUS

		IF(@BULKDELETE<>'BULK' OR @BULKDELETE<>'SummaryReport' OR @BULKDELETE='')
		BEGIN

			INSERT INTO @TEMP_SEGMENT
		SELECT DISTINCT  L.SEGMENT,ACCOUNTDB,ACCOUNTSERVER
		FROM	RECON_BANK_FILEUPLOAD_LOGS_VW L
		,PRADNYA.DBO.MULTICOMPANY P
		WHERE P.EXCHANGE + '-' + P.SEGMENT = L.SEGMENT
		AND PRIMARYSERVER = 1

			WHILE (SELECT	COUNT(*)	FROM @TEMP_SEGMENT) > 0 
			BEGIN
			SELECT TOP 1	@@SEGMENT=SEGMENT, @@ACCOUNTDB = ACCOUNTDB	,@@ACCOUNTSERVER = ACCOUNTSERVER FROM @TEMP_SEGMENT
			
			SET @@SQL = ''
			SET @@SQL ="INSERT INTO #LEDGER_TO_MAP 
			SELECT L.VNO
			,L.VTYP	,L.BOOKTYPE	,L.CLTCODE,L1.DDNO,L1.RELAMT,L1.DRCR,L1.RELAMT,L.NARRATION,L.ACNAME,L1.VNO,L.VDT,'" + @@SEGMENT + "' FROM " 
			+ @@ACCOUNTSERVER + "." + @@ACCOUNTDB+ ".DBO.LEDGER L ,"
			+ @@ACCOUNTSERVER + "." + @@ACCOUNTDB+ ".DBO.LEDGER1 L1 ,
			#TEMP_REPORT_WRAPPER T
			WHERE L.VNO = L1.VNO
			AND L.VTYP = L1.VTYP
			AND L.LNO = L1.LNO
			AND L.BOOKTYPE = L1.BOOKTYPE
			AND L1.VNO = T.VNO
			AND L1.VTYP = T.VTYP
			AND L1.BOOKTYPE = T.BOOKTYPE
			AND EXISTS (SELECT
			VNO
			FROM #TEMP_REPORT_WRAPPER L11 (NOLOCK)
			WHERE L11.VNO = L.VNO
			AND L11.VTYP = L.VTYP
			AND L11.BOOKTYPE = L.BOOKTYPE			
			) "
			
			EXEC (@@SQL)
			PRINT @@SQL
			DELETE FROM @TEMP_SEGMENT WHERE ACCOUNTDB = @@ACCOUNTDB AND SEGMENT=@@SEGMENT
			END

			
			UPDATE T
			SET	BANKSTATEMENTAMOUNT = T.VOUCHERAMOUNT--L.BANKSTATEMENTAMOUNT
			,CLIENTCODE = L.CLTCODE
			,CLIENTNAME = L.CLIENTNAME
			,VOUCHERNO = L.VOUCHERNO
			,VOUCHERDATE = L.VOUCHERDATE
			,STATUS =CASE WHEN T.MATCHEDFLAG = 1 THEN 'RECONCILED' ELSE 'UNRECONCILED' END
			FROM #TEMP_REPORT_WRAPPER T, #LEDGER_TO_MAP L
			WHERE T.VNO = L.VNO
			AND T.VTYP = L.VTYP
			AND T.BOOKTYPE = L.BOOKTYPE
			AND T.DRCR = L.DRCR
			AND T.SEGMENT = L.SEGMENT
			
			
END

	SELECT	* FROM #TEMP_REPORT_WRAPPER RL
	WHERE (RL.ARRANGEMENTTYPE = @FILETYPE OR @FILETYPE='')
	AND (RL.BANK = @BANKNAME OR @BANKNAME='')
	AND (RL.SEGMENT = @SEGMENT OR @SEGMENT='')


SELECT
	FILEUPLOADID AS UPLOADID
	,SEGMENT SEGMENT
	,BANK AS 'BANKNAME'
	,BANKACCOUNT
	,ARRANGEMENTTYPE AS FILETYPE
	,CONVERT(VARCHAR(10), MAX(VALUEDATE), 105) VALUEDATE --R.VALUEDATE
	,UPLOADFILENAME
	,UPLOADSTATUS
	,MIN(CONVERT(NVARCHAR, FILEUPLOAD_SDATE, 120)) FILEUPLOAD_SDATE
	,MAX(CONVERT(NVARCHAR, FILEUPLOAD_EDATE, 120)) FILEUPLOAD_EDATE
	,DRCR
	,COUNT(DRCR) AS 'TOTALENTRIES'
	,SUM(CASE WHEN MATCHEDFLAG = 1 THEN 1 ELSE 0  END) AS 'RECONCILED'
	,SUM(CASE WHEN MATCHEDFLAG = 0 THEN 1 ELSE 0 END) AS 'UNRECONCILED'
	,(SUM(CASE WHEN MATCHEDFLAG = 1 THEN 1 ELSE 0 END) * 100 / COUNT(DRCR)) 'RECONCILED %'
	FROM #TEMP_REPORT_WRAPPER
	WHERE (ARRANGEMENTTYPE = @FILETYPE OR @FILETYPE='')
	AND (BANK = @BANKNAME OR @BANKNAME='')
	AND (SEGMENT = @SEGMENT OR @SEGMENT='')
	GROUP BY	FILEUPLOADID
				,SEGMENT
				,BANK
				,BANKACCOUNT
				,ARRANGEMENTTYPE
				,UPLOADFILENAME
				,UPLOADSTATUS
				,DRCR

END

DROP TABLE #LEDGER_TO_MAP
END

GO
