-- Object: PROCEDURE dbo.COLL_CHECK_ANG
-- Server: 10.253.33.91 | DB: ACCOUNT
--------------------------------------------------

CREATE PROC COLL_CHECK_ANG (@COLLDATE VARCHAR(11),@FLAG VARCHAR(10))  
AS

SELECT  PARTY_CODE,SUM(FINALAMOUNT) AS COLL_AMT INTO #COLLATERALDETAILS FROM MSAJAG.DBO.COLLATERALDETAILS WITH (NOLOCK) WHERE EFFDATE = @COLLDATE
AND PARTY_CODE BETWEEN 'A' AND 'ZZZZZZZZZZ' AND COLL_TYPE = 'SEC'  AND QTY <> 0   
GROUP BY PARTY_CODE  
  
SELECT DISTINCT PARTY_CODE INTO #V2_TBL_COLLATERAL_MARGIN_COMBINE FROM MSAJAG.DBO.V2_TBL_COLLATERAL_MARGIN_COMBINE  WITH (NOLOCK)  
WHERE EFFDATE = @COLLDATE AND COLL_TYPE = 'SEC'

SELECT * INTO #CHECK FROM #COLLATERALDETAILS WHERE  PARTY_CODE  NOT IN ( SELECT PARTY_CODE FROM #V2_TBL_COLLATERAL_MARGIN_COMBINE )  
  
SELECT D.PARTY_CODE,SUM(TDAY_MARGIN) AS TDAY_MARGIN,SUM(TDAY_MTM) AS TDAY_MTM,SUM(COLL_AMT) AS COLL_AMT FROM   
MSAJAG.DBO.TBL_COMBINE_REPORTING_DETAIL D WITH (NOLOCK) ,#CHECK   
WHERE MARGINDATE = @COLLDATE AND (TDAY_MARGIN <> 0 OR TDAY_MTM <> 0)  
AND #CHECK.PARTY_CODE = D.PARTY_CODE GROUP BY D.PARTY_CODE

DROP TABLE #COLLATERALDETAILS
DROP TABLE #V2_TBL_COLLATERAL_MARGIN_COMBINE
DROP TABLE #CHECK

GO
