-- Object: PROCEDURE dbo.Virtual_Transactions
-- Server: 10.253.33.91 | DB: ACCOUNT
--------------------------------------------------

  
CREATE PROC [dbo].[Virtual_Transactions]  
  
  @FROM_DATE VARCHAR(11),  
  @TO_DATE VARCHAR(11) ,  
  @FROM_PARTY VARCHAR(20) ,  
  @TO_PARTY VARCHAR(20)  
    
AS   
  
SET @FROM_PARTY = CASE WHEN @FROM_PARTY = '' THEN '000' else @FROM_PARTY END  
SET  @TO_PARTY = CASE WHEN @TO_PARTY = '' THEN 'ZZZ' ELSE @TO_PARTY END  
  
--SELECT @FROM_PARTY, @TO_PARTY  
  
IF LEN(@FROM_DATE) = 10              
  
BEGIN              
  
 SELECT @FROM_DATE = CONVERT(VARCHAR(11), CONVERT(DATETIME, @FROM_DATE, 103), 109)              
  
 SELECT @TO_DATE = CONVERT(VARCHAR(11), CONVERT(DATETIME, @TO_DATE, 103), 109)              
  
END      
  
 SELECT DISTINCT A.*, (CASE WHEN VAMT <> 0 THEN 'Y' ELSE 'N' END) AS LEDGERPOST  INTO #FINAL   
 FROM         
(SELECT          
 BR_CODE,SB_CODE,V.PARTY_CODE,PARTY_NAME,SEGMENT,AMOUNT,TXN_DATE,SOURCE_BANK_ACNO,BANK_REF_NO  
 TXN_REF_NO,PRODUCT,REMARKS          
FROM      
VIRTUAL_MIS_LEDGER_REPORT V ,MSAJAG..CLIENT_DETAILS C1        
WHERE               
V.PARTY_CODE BETWEEN @FROM_PARTY AND @TO_PARTY                
AND   
V.PARTY_CODE=C1.CL_CODE        
AND TXN_DATE >= @FROM_DATE AND TXN_DATE <= @TO_DATE +' 23:59'        
 ) A LEFT OUTER JOIN (SELECT * FROM LEDGER_ALL WHERE VDT >= @FROM_DATE AND VDT <= @TO_DATE +' 23:59' AND VTYP =2) AS B  
  
  ON A.PARTY_CODE=B.CLTCODE  
AND (CASE WHEN NARRATION LIKE '%IMPS|%' THEN  substring(narration,charindex('|',narration)+5,30)   
 WHEN NARRATION LIKE '%IMPS/%' THEN  SUBSTRING(REPLACE(NARRATION,'VIRTUAL IMPS/P2A/',''),0, CHARINDEX('/', REPLACE(NARRATION,'VIRTUAL IMPS/P2A/','')))   
ELSE .DBO.PIECE(REPLACE(NARRATION,'VIRTUAL ',''), '|', 1) END  ) =TXN_REF_NO            
AND txn_date=CONVERT(VARCHAR(11),VDT,120)  
AND EXCHANGE=SEGMENT  
order by TXN_DATE,A.PARTY_CODE,BR_CODE  
  
ALTER TABLE #FINAL  
ADD RESPONSE_DATE  datetime NULL  
ALTER TABLE #FINAL  
ADD VNO  VARCHAR(20)  NULL  
  
ALTER TABLE #FINAL  
ALTER COLUMN  LEDGERPOST  VARCHAR(20)  NULL  
  
INSERT INTO #FINAL (PARTY_CODE,SEGMENT,PRODUCT,AMOUNT,TXN_REF_NO,VNO,LEDGERPOST,TXN_DATE,RESPONSE_DATE)  
SELECT CltCode,  
(CASE WHEN EXCHANGE  = 'NSE' AND SEGMENT ='FUTURES' THEN 'NSEFO' ELSE EXCHANGE END) AS SEGMENT  
,'CMS'AS PRODUCT ,CreditAmt,SUBSTRING (Narration,CHARINDEX('NO',Narration)+3,08) AS Internal_Ref,VoucherNo,  
'COMPLETED' AS [STATUS],  
AddDt,  
ApprovalDate  FROM   
(SELECT  (CASE WHEN RowState ='1' THEN 'COMPLETED' WHEN RowState ='0' THEN 'PENDING' END) AS STATUS,CltCode,Exchange,Segment,  
Narration,VoucherType,CreditAmt,DebitAmt,OppCode,AddBy,ApprovedBy ,VoucherNo  
,LEDGERVNO,AddDt,ApprovalDate,ApprovalFlag,  
(CASE WHEN RowState =1 THEN  convert (varchar(11),vdate,120) ELSE AddDt END)  as VDATE  
 FROM [AngelBSECM].ACCOUNT_AB.dbo.V2_OFFLINE_LEDGER_ENTRIES WITH (NOLOCK)  
WHERE OppCode <> 02093  
AND vdate between  @FROM_DATE and @TO_DATE  
--AND convert (varchar(11),vdate,120) = '2020-01-18'  
And RowState IN ('0','1')    
and TPFlag <> 1   
AND VoucherType = 2   
)A   
WHERE STATUS = 'COMPLETED'  
UNION ALL  
SELECT CltCode,  
(CASE WHEN EXCHANGE  = 'NSE' AND SEGMENT ='FUTURES' THEN 'NSEFO' ELSE EXCHANGE END) AS SEGMENT  
,'CMS'AS PRODUCT ,CreditAmt,SUBSTRING (Narration,CHARINDEX('NO',Narration)+3,08) AS Internal_Ref,VoucherNo,  
'TP' AS [STATUS],  
AddDt,  
ApprovalDate  
FROM [AngelBSECM].ACCOUNT_AB.dbo.V2_OFFLINE_LEDGER_ENTRIES WITH (NOLOCK)  
WHERE  OppCode <> 02093  
--AND convert (varchar(11),vdate,120) = '2020-01-18'  
AND vdate between  @FROM_DATE and @TO_DATE  
and TPFlag = 1  
AND VoucherType = 2   
  
SELECT PARTY_CODE,SEGMENT,PRODUCT,AMOUNT,TXN_REF_NO,VNO,LEDGERPOST,TXN_DATE,RESPONSE_DATE FROM #FINAL  
  
DROP TABLE #FINAL

GO
