-- Object: PROCEDURE dbo.INTERJV_CLOSED_ACCOUNT
-- Server: 10.253.33.91 | DB: ACCOUNT
--------------------------------------------------

    
CREATE PROCEDURE [dbo].[INTERJV_CLOSED_ACCOUNT]  (@TODATE VARCHAR(11))    
AS    
/*    
SELECT DISTINCT PARTY_CODE,ProcessOn = CONVERT(VARCHAR(11),ProcessOn) INTO #CLOSE     
FROM mimansa.CRM.DBO.VIEW_AUTOCLOSUREPROC_LOG WITH (NOLOCK)    
WHERE ProcessOn BETWEEN 'DEC 18 2021' AND 'DEC 18 2021' + ' 23:59' AND SEGMENT LIKE '%ALL%'    
*/    

--EXEC [INTERJV_CLOSED_ACCOUNT] 'JUN 15 2022'

DECLARE @TODATE1 VARCHAR(10)    
    
SELECT @TODATE1=CONVERT(VARCHAR(10), CAST(@TODATE AS DATE), 101)     
    
SELECT DISTINCT PARTY_CODE INTO #CLOSE    
FROM mimansa.CRM.DBO.TBL_CLOSURE_PROC_AUTOMATION WITH(NOLOCK)    
WHERE  SEGMENT LIKE '%ALL%' AND CONVERT(VARCHAR(10),UPDATEDON,101) = CONVERT(VARCHAR(10),@TODATE1)    
    
CREATE CLUSTERED INDEX IDXCLI ON #CLOSE(PARTY_CODE)    
    
--SET @TODATE = 'DEC  2 2021'    
    
DECLARE @FROMDATE VARCHAR(11)    
    
SELECT @FROMDATE =SDTCUR FROM ACCOUNT.DBO.PARAMETER WITH(NOLOCK) WHERE @TODATE BETWEEN SDTCUR AND LDTCUR        
    
--DROP TABLE #EDTLED    
SELECT CLTCODE, LEDBAL = ISNULL(SUM(CASE WHEN UPPER(DRCR) = 'D' THEN VAMT ELSE -VAMT END ), 0) , EXCHANGE = 'NSECM' INTO #EDTLED    
FROM ACCOUNT.DBO.LEDGER WITH(NOLOCK) ,  #CLOSE    
WHERE EDT LIKE @FROMDATE + '%' AND VTYP = 18  AND CLTCODE= PARTY_CODE    
GROUP BY CLTCODE     
UNION ALL    
SELECT CLTCODE, LEDBAL = ISNULL(SUM( CASE WHEN UPPER(B.DRCR) = 'C' THEN B.VAMT ELSE -B.VAMT END ), 0) , EXCHANGE = 'NSECM'    
FROM ACCOUNT.DBO.LEDGER B WITH (NOLOCK) ,  #CLOSE    
WHERE B.VDT < @FROMDATE AND EDT >= @FROMDATE AND CLTCODE=Party_code    
GROUP BY CLTCODE    
UNION ALL    
SELECT CLTCODE, LEDBAL = SUM(CASE WHEN L.DRCR = 'D' THEN L.VAMT ELSE -L.VAMT END) , EXCHANGE = 'NSECM'     
FROM  ACCOUNT.DBO.LEDGER L WITH (NOLOCK) ,  #CLOSE     
WHERE L.EDT >= @FROMDATE + ' 00:00:00'  AND L.EDT <= @TODATE + ' 23:59:59' AND VTYP <> 18  AND CLTCODE=Party_code    
GROUP BY CLTCODE    
    
INSERT INTO #EDTLED --- BSECM    
SELECT CLTCODE, LEDBAL = ISNULL(SUM(CASE WHEN UPPER(DRCR) = 'D' THEN VAMT ELSE -VAMT END ), 0) , EXCHANGE = 'BSECM'     
FROM AngelBSECM.ACCOUNT_AB.DBO.LEDGER WITH(NOLOCK) ,  #CLOSE    
WHERE EDT LIKE @FROMDATE + '%' AND VTYP = 18  AND CLTCODE=Party_code    
GROUP BY CLTCODE     
UNION ALL    
SELECT CLTCODE, LEDBAL = ISNULL(SUM( CASE WHEN UPPER(B.DRCR) = 'C' THEN B.VAMT ELSE -B.VAMT END ), 0) , EXCHANGE = 'BSECM'    
FROM AngelBSECM.ACCOUNT_AB.DBO.LEDGER B WITH (NOLOCK) ,  #CLOSE    
WHERE B.VDT < @FROMDATE AND EDT >= @FROMDATE AND CLTCODE=Party_code    
GROUP BY CLTCODE    
UNION ALL    
SELECT CLTCODE, LEDBAL = SUM(CASE WHEN L.DRCR = 'D' THEN L.VAMT ELSE -L.VAMT END) , EXCHANGE = 'BSECM'     
FROM  AngelBSECM.ACCOUNT_AB.DBO.LEDGER L WITH (NOLOCK)  ,  #CLOSE    
WHERE L.EDT >= @FROMDATE + ' 00:00:00'  AND L.EDT <= @TODATE + ' 23:59:59' AND VTYP <> 18  AND CLTCODE=Party_code    
GROUP BY CLTCODE    
    
INSERT INTO #EDTLED --- NSEFO    
SELECT CLTCODE, LEDBAL = ISNULL(SUM(CASE WHEN UPPER(DRCR) = 'D' THEN VAMT ELSE -VAMT END ), 0) , EXCHANGE = 'NSEFO'     
FROM ANGELFO.ACCOUNTFO.DBO.LEDGER WITH(NOLOCK) ,  #CLOSE    
WHERE EDT LIKE @FROMDATE + '%' AND VTYP = 18  AND CLTCODE=Party_code    
GROUP BY CLTCODE     
UNION ALL    
SELECT CLTCODE, LEDBAL = ISNULL(SUM( CASE WHEN UPPER(B.DRCR) = 'C' THEN B.VAMT ELSE -B.VAMT END ), 0) , EXCHANGE = 'NSEFO'    
FROM ANGELFO.ACCOUNTFO.DBO.LEDGER B WITH (NOLOCK) ,  #CLOSE    
WHERE B.VDT < @FROMDATE AND EDT >= @FROMDATE AND CLTCODE=Party_code    
GROUP BY CLTCODE    
UNION ALL    
SELECT CLTCODE, LEDBAL = SUM(CASE WHEN L.DRCR = 'D' THEN L.VAMT ELSE -L.VAMT END) , EXCHANGE = 'NSEFO'     
FROM  ANGELFO.ACCOUNTFO.DBO.LEDGER L WITH (NOLOCK)  ,  #CLOSE    
WHERE L.EDT >= @FROMDATE + ' 00:00:00'  AND L.EDT <= @TODATE + ' 23:59:59' AND VTYP <> 18  AND CLTCODE=Party_code    
GROUP BY CLTCODE    
    
INSERT INTO #EDTLED --- BSEFO    
SELECT CLTCODE, LEDBAL = ISNULL(SUM(CASE WHEN UPPER(DRCR) = 'D' THEN VAMT ELSE -VAMT END ), 0) , EXCHANGE = 'BSEFO'     
FROM ANGELCOMMODITY.ACCOUNTBFO.DBO.LEDGER WITH(NOLOCK) ,  #CLOSE    
WHERE EDT LIKE @FROMDATE + '%' AND VTYP = 18  AND CLTCODE=Party_code    
GROUP BY CLTCODE     
UNION ALL    
SELECT CLTCODE, LEDBAL = ISNULL(SUM( CASE WHEN UPPER(B.DRCR) = 'C' THEN B.VAMT ELSE -B.VAMT END ), 0) , EXCHANGE = 'BSEFO'    
FROM ANGELCOMMODITY.ACCOUNTBFO.DBO.LEDGER B WITH (NOLOCK) ,  #CLOSE    
WHERE B.VDT < @FROMDATE AND EDT >= @FROMDATE AND CLTCODE=Party_code    
GROUP BY CLTCODE    
UNION ALL    
SELECT CLTCODE, LEDBAL = SUM(CASE WHEN L.DRCR = 'D' THEN L.VAMT ELSE -L.VAMT END) , EXCHANGE = 'BSEFO'     
FROM  ANGELCOMMODITY.ACCOUNTBFO.DBO.LEDGER L WITH (NOLOCK)  ,  #CLOSE    
WHERE L.EDT >= @FROMDATE + ' 00:00:00'  AND L.EDT <= @TODATE + ' 23:59:59' AND VTYP <> 18  AND CLTCODE=Party_code    
GROUP BY CLTCODE    
    
INSERT INTO #EDTLED --- NSECD    
SELECT CLTCODE, LEDBAL = ISNULL(SUM(CASE WHEN UPPER(DRCR) = 'D' THEN VAMT ELSE -VAMT END ), 0) , EXCHANGE = 'NSECD'     
FROM ANGELFO.ACCOUNTCURFO.DBO.LEDGER WITH(NOLOCK) ,  #CLOSE    
WHERE EDT LIKE @FROMDATE + '%' AND VTYP = 18  AND CLTCODE=Party_code    
GROUP BY CLTCODE     
UNION ALL    
SELECT CLTCODE, LEDBAL = ISNULL(SUM( CASE WHEN UPPER(B.DRCR) = 'C' THEN B.VAMT ELSE -B.VAMT END ), 0) , EXCHANGE = 'NSECD'    
FROM ANGELFO.ACCOUNTCURFO.DBO.LEDGER B WITH (NOLOCK) ,  #CLOSE    
WHERE B.VDT < @FROMDATE AND EDT >= @FROMDATE AND CLTCODE=Party_code    
GROUP BY CLTCODE    
UNION ALL    
SELECT CLTCODE, LEDBAL = SUM(CASE WHEN L.DRCR = 'D' THEN L.VAMT ELSE -L.VAMT END) , EXCHANGE = 'NSECD'     
FROM  ANGELFO.ACCOUNTCURFO.DBO.LEDGER L WITH (NOLOCK) ,  #CLOSE     
WHERE L.EDT >= @FROMDATE + ' 00:00:00'  AND L.EDT <= @TODATE + ' 23:59:59' AND VTYP <> 18  AND CLTCODE=Party_code    
GROUP BY CLTCODE    
    
INSERT INTO #EDTLED --- BSECD    
SELECT CLTCODE, LEDBAL = ISNULL(SUM(CASE WHEN UPPER(DRCR) = 'D' THEN VAMT ELSE -VAMT END ), 0) , EXCHANGE = 'BSECD'     
FROM ANGELCOMMODITY.ACCOUNTCURBFO.DBO.LEDGER WITH(NOLOCK) ,  #CLOSE    
WHERE EDT LIKE @FROMDATE + '%' AND VTYP = 18  AND CLTCODE=Party_code    
GROUP BY CLTCODE     
UNION ALL    
SELECT CLTCODE, LEDBAL = ISNULL(SUM( CASE WHEN UPPER(B.DRCR) = 'C' THEN B.VAMT ELSE -B.VAMT END ), 0) , EXCHANGE = 'BSECD'    
FROM ANGELCOMMODITY.ACCOUNTCURBFO.DBO.LEDGER B WITH (NOLOCK) ,  #CLOSE    
WHERE B.VDT < @FROMDATE AND EDT >= @FROMDATE AND CLTCODE=Party_code    
GROUP BY CLTCODE    
UNION ALL    
SELECT CLTCODE, LEDBAL = SUM(CASE WHEN L.DRCR = 'D' THEN L.VAMT ELSE -L.VAMT END) , EXCHANGE = 'BSECD'     
FROM  ANGELCOMMODITY.ACCOUNTCURBFO.DBO.LEDGER L WITH (NOLOCK)  ,  #CLOSE    
WHERE L.EDT >= @FROMDATE + ' 00:00:00'  AND L.EDT <= @TODATE + ' 23:59:59' AND VTYP <> 18  AND CLTCODE=Party_code    
GROUP BY CLTCODE    
    
INSERT INTO #EDTLED --- MCXCD    
SELECT CLTCODE, LEDBAL = ISNULL(SUM(CASE WHEN UPPER(DRCR) = 'D' THEN VAMT ELSE -VAMT END ), 0) , EXCHANGE = 'MCXCD'     
FROM ANGELCOMMODITY.ACCOUNTMCDXCDS.DBO.LEDGER WITH(NOLOCK) ,  #CLOSE    
WHERE EDT LIKE @FROMDATE + '%' AND VTYP = 18  AND CLTCODE=Party_code    
GROUP BY CLTCODE     
UNION ALL    
SELECT CLTCODE, LEDBAL = ISNULL(SUM( CASE WHEN UPPER(B.DRCR) = 'C' THEN B.VAMT ELSE -B.VAMT END ), 0) , EXCHANGE = 'MCXCD'    
FROM ANGELCOMMODITY.ACCOUNTMCDXCDS.DBO.LEDGER B WITH (NOLOCK) ,  #CLOSE    
WHERE B.VDT < @FROMDATE AND EDT >= @FROMDATE AND CLTCODE=Party_code    
GROUP BY CLTCODE    
UNION ALL    
SELECT CLTCODE, LEDBAL = SUM(CASE WHEN L.DRCR = 'D' THEN L.VAMT ELSE -L.VAMT END) , EXCHANGE = 'MCXCD'     
FROM  ANGELCOMMODITY.ACCOUNTMCDXCDS.DBO.LEDGER L WITH (NOLOCK)  ,  #CLOSE    
WHERE L.EDT >= @FROMDATE + ' 00:00:00'  AND L.EDT <= @TODATE + ' 23:59:59' AND VTYP <> 18  AND CLTCODE=Party_code    
GROUP BY CLTCODE    
    
INSERT INTO #EDTLED --- MTF    
SELECT CLTCODE, LEDBAL = ISNULL(SUM(CASE WHEN UPPER(DRCR) = 'D' THEN VAMT ELSE -VAMT END ), 0) , EXCHANGE = 'MTF'     
FROM MTFTRADE.DBO.LEDGER WITH(NOLOCK) ,  #CLOSE    
WHERE EDT LIKE @FROMDATE + '%' AND VTYP = 18  AND CLTCODE=Party_code    
GROUP BY CLTCODE     
UNION ALL    
SELECT CLTCODE, LEDBAL = ISNULL(SUM( CASE WHEN UPPER(B.DRCR) = 'C' THEN B.VAMT ELSE -B.VAMT END ), 0) , EXCHANGE = 'MTF'    
FROM MTFTRADE.DBO.LEDGER B WITH (NOLOCK) ,  #CLOSE    
WHERE B.VDT < @FROMDATE AND EDT >= @FROMDATE AND CLTCODE=Party_code    
GROUP BY CLTCODE    
UNION ALL    
SELECT CLTCODE, LEDBAL = SUM(CASE WHEN L.DRCR = 'D' THEN L.VAMT ELSE -L.VAMT END) , EXCHANGE = 'MTF'     
FROM  MTFTRADE.DBO.LEDGER L WITH (NOLOCK)  ,  #CLOSE    
WHERE L.EDT >= @FROMDATE + ' 00:00:00'  AND L.EDT <= @TODATE + ' 23:59:59' AND VTYP <> 18  AND CLTCODE=Party_code    
GROUP BY CLTCODE    
    
INSERT INTO #EDTLED --- SLBS    
SELECT CLTCODE, LEDBAL = ISNULL(SUM(CASE WHEN UPPER(DRCR) = 'D' THEN VAMT ELSE -VAMT END ), 0) , EXCHANGE = 'SLBS'     
FROM ACCOUNTSLBS.DBO.LEDGER WITH(NOLOCK) ,  #CLOSE    
WHERE EDT LIKE @FROMDATE + '%' AND VTYP = 18  AND CLTCODE=Party_code    
GROUP BY CLTCODE     
UNION ALL    
SELECT CLTCODE, LEDBAL = ISNULL(SUM( CASE WHEN UPPER(B.DRCR) = 'C' THEN B.VAMT ELSE -B.VAMT END ), 0) , EXCHANGE = 'SLBS'    
FROM ACCOUNTSLBS.DBO.LEDGER B WITH (NOLOCK) ,  #CLOSE    
WHERE B.VDT < @FROMDATE AND EDT >= @FROMDATE AND CLTCODE=Party_code    
GROUP BY CLTCODE    
UNION ALL    
SELECT CLTCODE, LEDBAL = SUM(CASE WHEN L.DRCR = 'D' THEN L.VAMT ELSE -L.VAMT END) , EXCHANGE = 'SLBS'     
FROM  ACCOUNTSLBS.DBO.LEDGER L WITH (NOLOCK)  ,  #CLOSE    
WHERE L.EDT >= @FROMDATE + ' 00:00:00'  AND L.EDT <= @TODATE + ' 23:59:59' AND VTYP <> 18  AND CLTCODE=Party_code    
GROUP BY CLTCODE    
    
/* -- IGNORE THE BSEMF    
INSERT INTO #EDTLED --- BSEMF    
SELECT CLTCODE,LEDBAL = SUM(DRAMOUNT+CRAMOUNT),EXCHANGE='BSEMF' FROM (    
SELECT B.CLTCODE,DRAMOUNT=(-B.DRAMOUNT),B.CRAMOUNT FROM ANGELFO.BBO_FA.DBO.ACC_TBL1 A (NOLOCK), ANGELFO.BBO_FA.DBO.ACC_TBL3 B (NOLOCK),  #CLOSE    
WHERE A.SNO = B.MASTERSNO    
AND CONVERT(DATETIME,CONVERT(VARCHAR(11),EDT)) LIKE @FROMDATE + '%' AND VTYPE = 18 AND CLTCODE=Party_code    
UNION ALL     
SELECT B.CLTCODE,DRAMOUNT=B.DRAMOUNT,CRAMOUNT=-B.CRAMOUNT FROM ANGELFO.BBO_FA.DBO.ACC_TBL1 A (NOLOCK), ANGELFO.BBO_FA.DBO.ACC_TBL3 B (NOLOCK),  #CLOSE    
WHERE A.SNO = B.MASTERSNO    
AND CONVERT(DATETIME,CONVERT(VARCHAR(11),VDT)) < @FROMDATE     
AND CONVERT(DATETIME,CONVERT(VARCHAR(11),EDT))>=@FROMDATE  AND CLTCODE=Party_code    
UNION ALL    
SELECT B.CLTCODE,DRAMOUNT=(-B.DRAMOUNT),B.CRAMOUNT FROM ANGELFO.BBO_FA.DBO.ACC_TBL1 A (NOLOCK), ANGELFO.BBO_FA.DBO.ACC_TBL3 B (NOLOCK),  #CLOSE    
WHERE A.SNO = B.MASTERSNO    
AND CONVERT(DATETIME,CONVERT(VARCHAR(11),EDT)) >= @FROMDATE + ' 00:00:00'     
AND CONVERT(DATETIME,CONVERT(VARCHAR(11),EDT)) <= @TODATE + ' 23:59:59' AND A.VTYPE <> 18  AND CLTCODE=Party_code ) A     
GROUP BY A.CLTCODE    
*/    
    
INSERT INTO #EDTLED --- MCDX    
SELECT CLTCODE, LEDBAL = ISNULL(SUM(CASE WHEN UPPER(DRCR) = 'D' THEN VAMT ELSE -VAMT END ), 0) , EXCHANGE = 'MCDX'     
FROM ANGELCOMMODITY.ACCOUNTMCDX.DBO.LEDGER WITH(NOLOCK) ,  #CLOSE    
WHERE EDT LIKE @FROMDATE + '%' AND VTYP = 18  AND CLTCODE=Party_code    
GROUP BY CLTCODE     
UNION ALL    
SELECT CLTCODE, LEDBAL = ISNULL(SUM( CASE WHEN UPPER(B.DRCR) = 'C' THEN B.VAMT ELSE -B.VAMT END ), 0) , EXCHANGE = 'MCDX'    
FROM ANGELCOMMODITY.ACCOUNTMCDX.DBO.LEDGER B WITH (NOLOCK) ,  #CLOSE    
WHERE B.VDT < @FROMDATE AND EDT >= @FROMDATE AND CLTCODE=Party_code    
GROUP BY CLTCODE    
UNION ALL    
SELECT CLTCODE, LEDBAL = SUM(CASE WHEN L.DRCR = 'D' THEN L.VAMT ELSE -L.VAMT END) , EXCHANGE = 'MCDX'     
FROM  ANGELCOMMODITY.ACCOUNTMCDX.DBO.LEDGER L WITH (NOLOCK)  ,  #CLOSE    
WHERE L.EDT >= @FROMDATE + ' 00:00:00'  AND L.EDT <= @TODATE + ' 23:59:59' AND VTYP <> 18  AND CLTCODE=Party_code    
GROUP BY CLTCODE    
    
INSERT INTO #EDTLED --- NCDX    
SELECT CLTCODE, LEDBAL = ISNULL(SUM(CASE WHEN UPPER(DRCR) = 'D' THEN VAMT ELSE -VAMT END ), 0) , EXCHANGE = 'NCDX'     
FROM ANGELCOMMODITY.ACCOUNTNCDX.DBO.LEDGER WITH(NOLOCK) ,  #CLOSE    
WHERE EDT LIKE @FROMDATE + '%' AND VTYP = 18  AND CLTCODE=Party_code    
GROUP BY CLTCODE     
UNION ALL    
SELECT CLTCODE, LEDBAL = ISNULL(SUM( CASE WHEN UPPER(B.DRCR) = 'C' THEN B.VAMT ELSE -B.VAMT END ), 0) , EXCHANGE = 'NCDX'    
FROM ANGELCOMMODITY.ACCOUNTNCDX.DBO.LEDGER B WITH (NOLOCK) ,  #CLOSE    
WHERE B.VDT < @FROMDATE AND EDT >= @FROMDATE AND CLTCODE=Party_code    
GROUP BY CLTCODE    
UNION ALL    
SELECT CLTCODE, LEDBAL = SUM(CASE WHEN L.DRCR = 'D' THEN L.VAMT ELSE -L.VAMT END) , EXCHANGE = 'NCDX'     
FROM  ANGELCOMMODITY.ACCOUNTNCDX.DBO.LEDGER L WITH (NOLOCK)  ,  #CLOSE    
WHERE L.EDT >= @FROMDATE + ' 00:00:00'  AND L.EDT <= @TODATE + ' 23:59:59' AND VTYP <> 18  AND CLTCODE=Party_code    
GROUP BY CLTCODE    
    
SELECT EDT=@TODATE,CLTCODE,EXCHANGE,LEDBAL=SUM(LEDBAL)     
INTO #EDTLED_FINAL    
FROM #EDTLED GROUP BY CLTCODE,EXCHANGE ORDER BY 1    
    
CREATE TABLE #TEMPBALANCE (EDT VARCHAR(11),CLTCODE VARCHAR(10),BAL_NSECM NUMERIC (18,2),BAL_BSECM NUMERIC (18,2)    
,BAL_MTF NUMERIC (18,2),BAL_NSEFO NUMERIC (18,2),BAL_NSECUR NUMERIC (18,2),BAL_MCDX NUMERIC (18,2),    
BAL_NCDX NUMERIC (18,2),BAL_MCXCD NUMERIC (18,2),BAL_BSEMF NUMERIC (18,2))    
    
INSERT INTO #TEMPBALANCE    
SELECT EDT , CLTCODE ,     
SUM (CASE WHEN EXCHANGE = 'NSECM' THEN LEDBAL ELSE '0' END ),     
SUM (CASE WHEN EXCHANGE = 'BSECM' THEN LEDBAL ELSE '0' END ),     
SUM (CASE WHEN EXCHANGE = 'MTF' THEN LEDBAL ELSE '0' END ),    
SUM (CASE WHEN EXCHANGE = 'NSEFO' THEN LEDBAL ELSE '0' END ),    
SUM (CASE WHEN EXCHANGE = 'NSECD' THEN LEDBAL ELSE '0' END ),    
SUM (CASE WHEN EXCHANGE = 'MCDX' THEN LEDBAL ELSE '0' END ),    
SUM (CASE WHEN EXCHANGE = 'NCDX' THEN LEDBAL ELSE '0' END ),    
SUM (CASE WHEN EXCHANGE = 'MCXCD' THEN LEDBAL ELSE '0' END ),    
SUM (CASE WHEN EXCHANGE = 'BSEMF' THEN LEDBAL ELSE '0' END )    
FROM #EDTLED_FINAL GROUP BY  EDT , CLTCODE     
    
CREATE TABLE #INTERJVFILE(SNO Int Identity(1,1),VDT VARCHAR(11),EDT VARCHAR(11),CLTCODE VARCHAR(11), DRCR VARCHAR(1),AMOUNT NUMERIC(18,2),     
FROM_SEGMENT VARCHAR(10),TO_SEGMENT VARCHAR(10), NARRATION VARCHAR(500),SRNO NUMERIC(18,0) , BRANCH VARCHAR(3),TCLTCODE VARCHAR(11),SCLTCODE VARCHAR(11))     
    
CREATE TABLE #INTERJVFILE_CM(VDT VARCHAR(11),EDT VARCHAR(11),CLTCODE VARCHAR(11), DRCR VARCHAR(1),AMOUNT NUMERIC(18,2),     
FROM_SEGMENT VARCHAR(10),TO_SEGMENT VARCHAR(10), NARRATION VARCHAR(500),SRNO NUMERIC(18,0) , BRANCH VARCHAR(3),TCLTCODE VARCHAR(11),SCLTCODE VARCHAR(11))     
    
INSERT INTO #INTERJVFILE    
SELECT EDT,EDT,CLTCODE  ,     
CASE WHEN BAL_NSEFO < 0  THEN  'C' ELSE 'D' END, AMOUNT =  BAL_NSEFO , 'NSEFO','NSECM', NARRATION = '',SRNO = 0 , BRANCH = 'ALL','',''     
FROM #TEMPBALANCE    
WHERE  BAL_NSEFO <> 0    
    
INSERT INTO #INTERJVFILE    
SELECT EDT,EDT,CLTCODE  ,     
CASE WHEN BAL_BSECM < 0  THEN  'C' ELSE 'D' END, AMOUNT =  BAL_BSECM , 'BSECM','NSECM', NARRATION = '',SRNO = 0 , BRANCH = 'ALL','',''    
FROM #TEMPBALANCE    
WHERE  BAL_BSECM <> 0    
    
INSERT INTO #INTERJVFILE    
SELECT EDT,EDT,CLTCODE  ,     
CASE WHEN BAL_MTF < 0  THEN  'C' ELSE 'D' END, AMOUNT =  BAL_MTF , 'MTF','NSECM', NARRATION = '',SRNO = 0 , BRANCH = 'ALL','',''    
FROM #TEMPBALANCE    
WHERE  BAL_MTF <> 0    
    
INSERT INTO #INTERJVFILE    
SELECT EDT,EDT,CLTCODE  ,     
CASE WHEN BAL_NSECUR < 0  THEN  'C' ELSE 'D' END, AMOUNT =  BAL_NSECUR , 'NSECD','NSECM', NARRATION = '',SRNO = 0 , BRANCH = 'ALL','',''    
FROM #TEMPBALANCE    
WHERE  BAL_NSECUR <> 0    
    
    
INSERT INTO #INTERJVFILE    
SELECT EDT,EDT,CLTCODE  ,     
CASE WHEN BAL_MCDX < 0  THEN  'C' ELSE 'D' END, AMOUNT =  BAL_MCDX , 'MCDX','NSECM', NARRATION = '',SRNO = 0 , BRANCH = 'ALL','',''    
FROM #TEMPBALANCE    
WHERE  BAL_MCDX <> 0    
    
    
INSERT INTO #INTERJVFILE    
SELECT EDT,EDT,CLTCODE  ,     
CASE WHEN BAL_NCDX < 0  THEN  'C' ELSE 'D' END, AMOUNT =  BAL_NCDX , 'NCDX','NSECM', NARRATION = '',SRNO = 0 , BRANCH = 'ALL','',''    
FROM #TEMPBALANCE    
WHERE  BAL_NCDX <> 0    
    
    
INSERT INTO #INTERJVFILE    
SELECT EDT,EDT,CLTCODE  ,     
CASE WHEN BAL_MCXCD < 0  THEN  'C' ELSE 'D' END, AMOUNT =  BAL_MCXCD , 'MCXCD','NSECM', NARRATION = '',SRNO = 0 , BRANCH = 'ALL','',''    
FROM #TEMPBALANCE    
WHERE  BAL_MCXCD <> 0    
    
    
INSERT INTO #INTERJVFILE    
SELECT EDT,EDT,CLTCODE  ,     
CASE WHEN BAL_BSEMF < 0  THEN  'C' ELSE 'D' END, AMOUNT =  BAL_BSEMF , 'BSEMF','NSECM', NARRATION = '',SRNO = 0 , BRANCH = 'ALL','',''    
FROM #TEMPBALANCE    
WHERE  BAL_BSEMF <> 0    
    
UPDATE #INTERJVFILE SET SRNO  = SNO    


UPDATE #INTERJVFILE SET NARRATION  = 'FUND TRANSFER FROM ' + FROM_SEGMENT + ' TO ' +  TO_SEGMENT, BRANCH = 'ALL',AMOUNT = ABS(AMOUNT)    
WHERE DRCR = 'C'

UPDATE #INTERJVFILE SET NARRATION  = 'FUND TRANSFER FROM ' + TO_SEGMENT + ' TO ' +  FROM_SEGMENT, BRANCH = 'ALL',AMOUNT = ABS(AMOUNT)    
WHERE DRCR = 'D'
    
INSERT INTO #INTERJVFILE    
SELECT EDT,EDT,CLTCODE = '43000051'  ,CASE WHEN DRCR = 'D' THEN 'C' ELSE 'D' END,     
AMOUNT , FROM_SEGMENT,TO_SEGMENT, NARRATION,SRNO , BRANCH,'',''     
FROM #INTERJVFILE    
 
UPDATE #INTERJVFILE SET TCLTCODE = '43000005' , SCLTCODE= '43000002' WHERE CLTCODE = '43000051' AND FROM_SEGMENT = 'MCDX'

UPDATE #INTERJVFILE SET TCLTCODE = '43000004' , SCLTCODE= '43000002' WHERE CLTCODE = '43000051' AND FROM_SEGMENT = 'NCDX'

UPDATE #INTERJVFILE SET TCLTCODE = '43000001' , SCLTCODE= '43000002' WHERE CLTCODE = '43000051' AND FROM_SEGMENT = 'BSECM'

UPDATE #INTERJVFILE SET TCLTCODE = '43000006' , SCLTCODE= '43000006' WHERE CLTCODE = '43000051' AND FROM_SEGMENT = 'NSECD'

UPDATE #INTERJVFILE SET TCLTCODE = '43000003' , SCLTCODE= '43000002' WHERE CLTCODE = '43000051' AND FROM_SEGMENT = 'NSEFO'
    
    
    
INSERT INTO #INTERJVFILE_CM    
SELECT EDT,EDT,RTRIM(LTRIM(CLTCODE))  ,CASE WHEN DRCR = 'D' THEN 'C' ELSE 'D' END,     
AMOUNT , FROM_SEGMENT,TO_SEGMENT, NARRATION ,SRNO,BRANCH,TCLTCODE,SCLTCODE     
FROM #INTERJVFILE    
 
/* 

UPDATE #INTERJVFILE_CM SET CLTCODE = '43000001'   WHERE CLTCODE = '43000051' AND TO_SEGMENT = 'NSEFO'
UPDATE #INTERJVFILE_CM SET CLTCODE = '43000001'   WHERE CLTCODE = '43000051' AND TO_SEGMENT = 'NSEFO'
UPDATE #INTERJVFILE_CM SET CLTCODE = '43000001'   WHERE CLTCODE = '43000051' AND TO_SEGMENT = 'BSECM'
UPDATE #INTERJVFILE_CM SET CLTCODE = '43000004'   WHERE CLTCODE = '43000051' AND TO_SEGMENT = 'NCDX'
UPDATE #INTERJVFILE_CM SET CLTCODE = '43000005'   WHERE CLTCODE = '43000051' AND TO_SEGMENT = 'MCDX'


UPDATE #INTERJVFILE SET CLTCODE = '43000002'   WHERE CLTCODE = '43000051' AND FROM_SEGMENT = 'MCDX'
UPDATE #INTERJVFILE SET CLTCODE = '43000002'   WHERE CLTCODE = '43000051' AND FROM_SEGMENT = 'NCDX'
UPDATE #INTERJVFILE SET CLTCODE = '43000002'   WHERE CLTCODE = '43000051' AND FROM_SEGMENT = 'BSECM'
UPDATE #INTERJVFILE SET CLTCODE = '43000003'   WHERE CLTCODE = '43000051' AND FROM_SEGMENT = 'NSEFO'
UPDATE #INTERJVFILE SET CLTCODE = '43000006'   WHERE CLTCODE = '43000051' AND FROM_SEGMENT = 'NSECD'


*/
    
TRUNCATE TABLE INTERJVFILE_CM_CHECK_ANG    
    
INSERT INTO  INTERJVFILE_CM_CHECK_ANG SELECT * FROM #INTERJVFILE_CM    
    
SELECT CONVERT(CHAR(10), CONVERT(DATE,VDT), 103) AS VDT,CONVERT(CHAR(10), CONVERT(DATE,EDT), 103)AS EDT,CLTCODE,DRCR,AMOUNT,NARRATION,SRNO,BRANCH   
FROM INTERJVFILE_CM_CHECK_ANG WHERE CLTCODE <> '43000051'    
  
  
DECLARE @CASHFILENAME VARCHAR(200)     
DECLARE @CASH VARCHAR(MAX)    

TRUNCATE TABLE MSAJAG.DBO.EXCHANGECCE    

INSERT INTO MSAJAG.DBO.EXCHANGECCE    
SELECT '','Sr No.,VDATE,EDATE,LedgerCode,DRCR,Provision_Amount,Narration,Branch'

INSERT INTO MSAJAG.DBO.EXCHANGECCE    
SELECT '',CONVERT(VARCHAR(1000),SRNO)+ ',' + CONVERT(VARCHAR(1000),CONVERT(CHAR(10), CONVERT(DATE,VDT), 103))+ ',' +
CONVERT(VARCHAR(1000),CONVERT(CHAR(10), CONVERT(DATE,EDT), 103)) + ',' +CONVERT(VARCHAR(1000),CLTCODE)+ ',' +
CONVERT(VARCHAR(1000),CASE WHEN DRCR = 'D' THEN 'C' ELSE 'D' END)+ ',' + CONVERT(VARCHAR(1000),AMOUNT) + ',' + CONVERT(VARCHAR(1000),NARRATION) + ',' + CONVERT(VARCHAR(1000),BRANCH) 
FROM INTERJVFILE_CM_CHECK_ANG WHERE CLTCODE <> '43000051'     ORDER BY SRNO ASC


INSERT INTO MSAJAG.DBO.EXCHANGECCE    
SELECT '',CONVERT(VARCHAR(1000),SRNO)+ ',' + CONVERT(VARCHAR(1000),CONVERT(CHAR(10), CONVERT(DATE,VDT), 103))+ ',' +
CONVERT(VARCHAR(1000),CONVERT(CHAR(10), CONVERT(DATE,EDT), 103)) + ',' +CONVERT(VARCHAR(1000),TCLTCODE)+ ',' +
CONVERT(VARCHAR(1000),CASE WHEN DRCR = 'D' THEN 'C' ELSE 'D' END)+ ',' + CONVERT(VARCHAR(1000),AMOUNT) + ',' + CONVERT(VARCHAR(1000),NARRATION) + ',' + CONVERT(VARCHAR(1000),BRANCH) 
FROM INTERJVFILE_CM_CHECK_ANG WHERE CLTCODE = '43000051'     ORDER BY SRNO ASC
    
SET @CASHFILENAME = 'J:\BACKOFFICE\EXPORT\' +'INTERJV_TEST3_ACCCLOSURE_NSECM_' + CONVERT(VARCHAR, GETDATE(), 112) + '.CSV'                           
--SET @CASH = 'EXEC MASTER.DBO.XP_CMDSHELL ''BCP " SELECT CONVERT(CHAR(10), CONVERT(DATE,VDT), 103) AS VDT,CONVERT(CHAR(10), CONVERT(DATE,EDT), 103)AS EDT,CLTCODE,DRCR,AMOUNT,NARRATION '     
--SET @CASH = @CASH + ' ,SRNO,BRANCH FROM [ANAND1].ACCOUNT.DBO.INTERJVFILE_CM_CHECK_ANG " QUERYOUT ' +@CASHFILENAME+ ' -c -t"," -c -t"," -r"\n" -T'', NO_OUTPUT'
SET @CASH = 'EXEC MASTER.DBO.XP_CMDSHELL ''BCP " SELECT DATACASH FROM [ANAND1].MSAJAG.DBO.EXCHANGECCE ORDER BY SNO ASC " QUERYOUT ' +@CASHFILENAME+ ' -c -t"," -c -t"," -r"\n" -T'', NO_OUTPUT'    
EXEC(@CASH)    

TRUNCATE TABLE MSAJAG.DBO.EXCHANGECCE    

INSERT INTO MSAJAG.DBO.EXCHANGECCE    
SELECT '','Sr No.,VDATE,EDATE,LedgerCode,DRCR,Provision_Amount,Narration,Branch'

INSERT INTO MSAJAG.DBO.EXCHANGECCE    
SELECT '',CONVERT(VARCHAR(1000),SRNO)+ ',' + CONVERT(VARCHAR(1000),CONVERT(CHAR(10), CONVERT(DATE,VDT), 103))+ ',' +
CONVERT(VARCHAR(1000),CONVERT(CHAR(10), CONVERT(DATE,EDT), 103)) + ',' +CONVERT(VARCHAR(1000),SCLTCODE)+ ',' +
CONVERT(VARCHAR(1000),DRCR)+ ',' + CONVERT(VARCHAR(1000),AMOUNT) + ',' + CONVERT(VARCHAR(1000),NARRATION) + ',' + CONVERT(VARCHAR(1000),BRANCH) 
FROM INTERJVFILE_CM_CHECK_ANG WHERE FROM_SEGMENT = 'BSECM' AND CLTCODE = '43000051'    ORDER BY SRNO ASC


INSERT INTO MSAJAG.DBO.EXCHANGECCE    
SELECT '',CONVERT(VARCHAR(1000),SRNO)+ ',' + CONVERT(VARCHAR(1000),CONVERT(CHAR(10), CONVERT(DATE,VDT), 103))+ ',' +
CONVERT(VARCHAR(1000),CONVERT(CHAR(10), CONVERT(DATE,EDT), 103)) + ',' +CONVERT(VARCHAR(1000),CLTCODE)+ ',' +
CONVERT(VARCHAR(1000),DRCR)+ ',' + CONVERT(VARCHAR(1000),AMOUNT) + ',' + CONVERT(VARCHAR(1000),NARRATION) + ',' + CONVERT(VARCHAR(1000),BRANCH) 
FROM INTERJVFILE_CM_CHECK_ANG WHERE FROM_SEGMENT = 'BSECM' AND CLTCODE <> '43000051'    ORDER BY SRNO ASC
    
SET @CASHFILENAME = 'J:\BACKOFFICE\EXPORT\' +'INTERJV_TEST3_ACCCLOSURE_BSECM_' + CONVERT(VARCHAR, GETDATE(), 112) + '.CSV'                            
--SET @CASH = 'EXEC MASTER.DBO.XP_CMDSHELL ''BCP " SELECT CONVERT(CHAR(10), CONVERT(DATE,VDT), 103) AS VDT,CONVERT(CHAR(10), CONVERT(DATE,EDT), 103)AS EDT,CLTCODE,DRCR,AMOUNT,NARRATION '     
--SET @CASH = @CASH + ' ,SRNO,BRANCH FROM [ANAND1].ACCOUNT.DBO.INTERJVFILE_CM_CHECK_ANG WHERE FROM_SEGMENT = ''''BSECM'''' " QUERYOUT ' +@CASHFILENAME+ ' -c -t"," -c -t"," -r"\n" -T'', NO_OUTPUT'    
SET @CASH = 'EXEC MASTER.DBO.XP_CMDSHELL ''BCP " SELECT DATACASH FROM [ANAND1].MSAJAG.DBO.EXCHANGECCE ORDER BY SNO ASC " QUERYOUT ' +@CASHFILENAME+ ' -c -t"," -c -t"," -r"\n" -T'', NO_OUTPUT'    
EXEC(@CASH)    

TRUNCATE TABLE MSAJAG.DBO.EXCHANGECCE    

INSERT INTO MSAJAG.DBO.EXCHANGECCE    
SELECT '','Sr No.,VDATE,EDATE,LedgerCode,DRCR,Provision_Amount,Narration,Branch'

INSERT INTO MSAJAG.DBO.EXCHANGECCE    
SELECT '',CONVERT(VARCHAR(1000),SRNO)+ ',' + CONVERT(VARCHAR(1000),CONVERT(CHAR(10), CONVERT(DATE,VDT), 103))+ ',' +
CONVERT(VARCHAR(1000),CONVERT(CHAR(10), CONVERT(DATE,EDT), 103)) + ',' +CONVERT(VARCHAR(1000),SCLTCODE)+ ',' +
CONVERT(VARCHAR(1000),DRCR)+ ',' + CONVERT(VARCHAR(1000),AMOUNT) + ',' + CONVERT(VARCHAR(1000),NARRATION) + ',' + CONVERT(VARCHAR(1000),BRANCH) 
FROM INTERJVFILE_CM_CHECK_ANG WHERE FROM_SEGMENT = 'NSEFO' AND CLTCODE = '43000051'  ORDER BY SRNO ASC


INSERT INTO MSAJAG.DBO.EXCHANGECCE    
SELECT '',CONVERT(VARCHAR(1000),SRNO)+ ',' + CONVERT(VARCHAR(1000),CONVERT(CHAR(10), CONVERT(DATE,VDT), 103))+ ',' +
CONVERT(VARCHAR(1000),CONVERT(CHAR(10), CONVERT(DATE,EDT), 103)) + ',' +CONVERT(VARCHAR(1000),CLTCODE)+ ',' +
CONVERT(VARCHAR(1000),DRCR)+ ',' + CONVERT(VARCHAR(1000),AMOUNT) + ',' + CONVERT(VARCHAR(1000),NARRATION) + ',' + CONVERT(VARCHAR(1000),BRANCH) 
FROM INTERJVFILE_CM_CHECK_ANG WHERE FROM_SEGMENT = 'NSEFO' AND CLTCODE <> '43000051'  ORDER BY SRNO ASC

SET @CASHFILENAME = 'J:\BACKOFFICE\EXPORT\' +'INTERJV_TEST3_ACCCLOSURE_NSEFO_' + CONVERT(VARCHAR, GETDATE(), 112) + '.CSV'                            
--SET @CASH = 'EXEC MASTER.DBO.XP_CMDSHELL ''BCP " SELECT CONVERT(CHAR(10), CONVERT(DATE,VDT), 103) AS VDT,CONVERT(CHAR(10), CONVERT(DATE,EDT), 103)AS EDT,CLTCODE,DRCR,AMOUNT,NARRATION '     
--SET @CASH = @CASH + ' ,SRNO,BRANCH FROM [ANAND1].ACCOUNT.DBO.INTERJVFILE_CM_CHECK_ANG WHERE FROM_SEGMENT = ''''NSEFO'''' " QUERYOUT ' +@CASHFILENAME+ ' -c -t"," -c -t"," -r"\n" -T'', NO_OUTPUT'    
SET @CASH = 'EXEC MASTER.DBO.XP_CMDSHELL ''BCP " SELECT DATACASH FROM [ANAND1].MSAJAG.DBO.EXCHANGECCE ORDER BY SNO ASC " QUERYOUT ' +@CASHFILENAME+ ' -c -t"," -c -t"," -r"\n" -T'', NO_OUTPUT'    
EXEC(@CASH)    

TRUNCATE TABLE MSAJAG.DBO.EXCHANGECCE    

INSERT INTO MSAJAG.DBO.EXCHANGECCE    
SELECT '','Sr No.,VDATE,EDATE,LedgerCode,DRCR,Provision_Amount,Narration,Branch'

INSERT INTO MSAJAG.DBO.EXCHANGECCE    
SELECT '',CONVERT(VARCHAR(1000),SRNO)+ ',' + CONVERT(VARCHAR(1000),CONVERT(CHAR(10), CONVERT(DATE,VDT), 103))+ ',' +
CONVERT(VARCHAR(1000),CONVERT(CHAR(10), CONVERT(DATE,EDT), 103)) + ',' +CONVERT(VARCHAR(1000),CLTCODE)+ ',' +
CONVERT(VARCHAR(1000),DRCR)+ ',' + CONVERT(VARCHAR(1000),AMOUNT) + ',' + CONVERT(VARCHAR(1000),NARRATION) + ',' + CONVERT(VARCHAR(1000),BRANCH) 
FROM INTERJVFILE_CM_CHECK_ANG WHERE FROM_SEGMENT = 'NSECD' AND CLTCODE <> '43000051'  ORDER BY SRNO ASC


INSERT INTO MSAJAG.DBO.EXCHANGECCE    
SELECT '',CONVERT(VARCHAR(1000),SRNO)+ ',' + CONVERT(VARCHAR(1000),CONVERT(CHAR(10), CONVERT(DATE,VDT), 103))+ ',' +
CONVERT(VARCHAR(1000),CONVERT(CHAR(10), CONVERT(DATE,EDT), 103)) + ',' +CONVERT(VARCHAR(1000),SCLTCODE)+ ',' +
CONVERT(VARCHAR(1000),DRCR)+ ',' + CONVERT(VARCHAR(1000),AMOUNT) + ',' + CONVERT(VARCHAR(1000),NARRATION) + ',' + CONVERT(VARCHAR(1000),BRANCH) 
FROM INTERJVFILE_CM_CHECK_ANG WHERE FROM_SEGMENT = 'NSECD' AND CLTCODE = '43000051'  ORDER BY SRNO ASC

    
SET @CASHFILENAME = 'J:\BACKOFFICE\EXPORT\' +'INTERJV_TEST3_ACCCLOSURE_NSECD_' + CONVERT(VARCHAR, GETDATE(), 112) + '.CSV'                            
--SET @CASH = 'EXEC MASTER.DBO.XP_CMDSHELL ''BCP " SELECT CONVERT(CHAR(10), CONVERT(DATE,VDT), 103) AS VDT,CONVERT(CHAR(10), CONVERT(DATE,EDT), 103)AS EDT,CLTCODE,DRCR,AMOUNT,NARRATION '     
--SET @CASH = @CASH + ' ,SRNO,BRANCH FROM [ANAND1].ACCOUNT.DBO.INTERJVFILE_CM_CHECK_ANG WHERE FROM_SEGMENT = ''''NSECD'''' " QUERYOUT ' +@CASHFILENAME+ ' -c -t"," -c -t"," -r"\n" -T'', NO_OUTPUT'    
SET @CASH = 'EXEC MASTER.DBO.XP_CMDSHELL ''BCP " SELECT DATACASH FROM [ANAND1].MSAJAG.DBO.EXCHANGECCE ORDER BY SNO ASC " QUERYOUT ' +@CASHFILENAME+ ' -c -t"," -c -t"," -r"\n" -T'', NO_OUTPUT'    
EXEC(@CASH)    

TRUNCATE TABLE MSAJAG.DBO.EXCHANGECCE    

INSERT INTO MSAJAG.DBO.EXCHANGECCE    
SELECT '','Sr No.,VDATE,EDATE,LedgerCode,DRCR,Provision_Amount,Narration,Branch'

INSERT INTO MSAJAG.DBO.EXCHANGECCE    
SELECT '',CONVERT(VARCHAR(1000),SRNO)+ ',' + CONVERT(VARCHAR(1000),CONVERT(CHAR(10), CONVERT(DATE,VDT), 103))+ ',' +
CONVERT(VARCHAR(1000),CONVERT(CHAR(10), CONVERT(DATE,EDT), 103)) + ',' +CONVERT(VARCHAR(1000),SCLTCODE)+ ',' +
CONVERT(VARCHAR(1000),DRCR)+ ',' + CONVERT(VARCHAR(1000),AMOUNT) + ',' + CONVERT(VARCHAR(1000),NARRATION) + ',' + CONVERT(VARCHAR(1000),BRANCH) 
FROM INTERJVFILE_CM_CHECK_ANG WHERE FROM_SEGMENT = 'MCDX'  AND CLTCODE = '43000051'  ORDER BY SRNO ASC
    

INSERT INTO MSAJAG.DBO.EXCHANGECCE    
SELECT '',CONVERT(VARCHAR(1000),SRNO)+ ',' + CONVERT(VARCHAR(1000),CONVERT(CHAR(10), CONVERT(DATE,VDT), 103))+ ',' +
CONVERT(VARCHAR(1000),CONVERT(CHAR(10), CONVERT(DATE,EDT), 103)) + ',' +CONVERT(VARCHAR(1000),CLTCODE)+ ',' +
CONVERT(VARCHAR(1000),DRCR)+ ',' + CONVERT(VARCHAR(1000),AMOUNT) + ',' + CONVERT(VARCHAR(1000),NARRATION) + ',' + CONVERT(VARCHAR(1000),BRANCH) 
FROM INTERJVFILE_CM_CHECK_ANG WHERE FROM_SEGMENT = 'MCDX'  AND CLTCODE <> '43000051'  ORDER BY SRNO ASC
    

SET @CASHFILENAME = 'J:\BACKOFFICE\EXPORT\' +'INTERJV_TEST3_ACCCLOSURE_MCDX_' + CONVERT(VARCHAR, GETDATE(), 112) + '.CSV'                            
--SET @CASH = 'EXEC MASTER.DBO.XP_CMDSHELL ''BCP " SELECT CONVERT(CHAR(10), CONVERT(DATE,VDT), 103) AS VDT,CONVERT(CHAR(10), CONVERT(DATE,EDT), 103)AS EDT,CLTCODE,DRCR,AMOUNT,NARRATION '     
--SET @CASH = @CASH + ' ,SRNO,BRANCH FROM [ANAND1].ACCOUNT.DBO.INTERJVFILE_CM_CHECK_ANG WHERE FROM_SEGMENT = ''''MCDX'''' " QUERYOUT ' +@CASHFILENAME+ ' -c -t"," -c -t"," -r"\n" -T'', NO_OUTPUT'    
SET @CASH = 'EXEC MASTER.DBO.XP_CMDSHELL ''BCP " SELECT DATACASH FROM [ANAND1].MSAJAG.DBO.EXCHANGECCE ORDER BY SNO ASC " QUERYOUT ' +@CASHFILENAME+ ' -c -t"," -c -t"," -r"\n" -T'', NO_OUTPUT'    
EXEC(@CASH)    

TRUNCATE TABLE MSAJAG.DBO.EXCHANGECCE    

INSERT INTO MSAJAG.DBO.EXCHANGECCE    
SELECT '','Sr No.,VDATE,EDATE,LedgerCode,DRCR,Provision_Amount,Narration,Branch'

INSERT INTO MSAJAG.DBO.EXCHANGECCE    
SELECT '',CONVERT(VARCHAR(1000),SRNO)+ ',' + CONVERT(VARCHAR(1000),CONVERT(CHAR(10), CONVERT(DATE,VDT), 103))+ ',' +
CONVERT(VARCHAR(1000),CONVERT(CHAR(10), CONVERT(DATE,EDT), 103)) + ',' +CONVERT(VARCHAR(1000),SCLTCODE)+ ',' +
CONVERT(VARCHAR(1000),DRCR)+ ',' + CONVERT(VARCHAR(1000),AMOUNT) + ',' + CONVERT(VARCHAR(1000),NARRATION) + ',' + CONVERT(VARCHAR(1000),BRANCH) 
FROM INTERJVFILE_CM_CHECK_ANG WHERE FROM_SEGMENT = 'NCDX' AND CLTCODE = '43000051' ORDER BY SRNO ASC


INSERT INTO MSAJAG.DBO.EXCHANGECCE    
SELECT '',CONVERT(VARCHAR(1000),SRNO)+ ',' + CONVERT(VARCHAR(1000),CONVERT(CHAR(10), CONVERT(DATE,VDT), 103))+ ',' +
CONVERT(VARCHAR(1000),CONVERT(CHAR(10), CONVERT(DATE,EDT), 103)) + ',' +CONVERT(VARCHAR(1000),CLTCODE)+ ',' +
CONVERT(VARCHAR(1000),DRCR)+ ',' + CONVERT(VARCHAR(1000),AMOUNT) + ',' + CONVERT(VARCHAR(1000),NARRATION) + ',' + CONVERT(VARCHAR(1000),BRANCH) 
FROM INTERJVFILE_CM_CHECK_ANG WHERE FROM_SEGMENT = 'NCDX'  AND CLTCODE <> '43000051'   ORDER BY SRNO ASC
    
SET @CASHFILENAME = 'J:\BACKOFFICE\EXPORT\' +'INTERJV_TEST3_ACCCLOSURE_NCDX_' + CONVERT(VARCHAR, GETDATE(), 112) + '.CSV'                            
--SET @CASH = 'EXEC MASTER.DBO.XP_CMDSHELL ''BCP " SELECT CONVERT(CHAR(10), CONVERT(DATE,VDT), 103) AS VDT,CONVERT(CHAR(10), CONVERT(DATE,EDT), 103)AS EDT,CLTCODE,DRCR,AMOUNT,NARRATION '     
--SET @CASH = @CASH + ' ,SRNO,BRANCH FROM [ANAND1].ACCOUNT.DBO.INTERJVFILE_CM_CHECK_ANG WHERE FROM_SEGMENT = ''''NCDX'''' " QUERYOUT ' +@CASHFILENAME+ ' -c -t"," -c -t"," -r"\n" -T'', NO_OUTPUT'    
SET @CASH = 'EXEC MASTER.DBO.XP_CMDSHELL ''BCP " SELECT DATACASH FROM [ANAND1].MSAJAG.DBO.EXCHANGECCE ORDER BY SNO ASC " QUERYOUT ' +@CASHFILENAME+ ' -c -t"," -c -t"," -r"\n" -T'', NO_OUTPUT'    
EXEC(@CASH)        
    
DROP TABLE #EDTLED    
DROP TABLE #EDTLED_FINAL    
DROP TABLE #TEMPBALANCE    
DROP TABLE #INTERJVFILE    
DROP TABLE #INTERJVFILE_CM    
DROP TABLE #CLOSE

GO
