-- Object: PROCEDURE dbo.BANK_PayinPout_New_2
-- Server: 10.253.33.91 | DB: ACCOUNT
--------------------------------------------------


--Changes are under SRE-33776
  
CREATE PROC [dbo].[BANK_PayinPout_New_2]  
AS  
DECLARE @EDT VARCHAR(11) = (GETDATE()-2)  
  
SELECT DISTINCT * INTO #BANKCODE FROM (  
SELECT CLTCODE,ACNAME, EXCHANGE='NSECM'  
FROM ACMAST A WITH (NOLOCK)  WHERE ACCAT = 2   
UNION ALL  
SELECT CLTCODE,ACNAME, EXCHANGE='BSECM'   
FROM ANAND.ACCOUNT_AB.DBO.ACMAST A WITH (NOLOCK)  WHERE ACCAT = 2  ) AS A  
  
  
SELECT DISTINCT * INTO #CLIENTCODE FROM (  
SELECT CLTCODE,ACNAME, EXCHANGE='NSECM'  
FROM ACMAST A WITH (NOLOCK)  WHERE ACCAT = 4   
UNION ALL  
SELECT CLTCODE,ACNAME, EXCHANGE='BSECM'   
FROM ANAND.ACCOUNT_AB.DBO.ACMAST A WITH (NOLOCK)  WHERE ACCAT = 4  ) AS A  
  
CREATE CLUSTERED INDEX CLIIDX  ON #BANKCODE(CLTCODE,EXCHANGE)  
CREATE CLUSTERED INDEX CLIIDX2  ON #CLIENTCODE(CLTCODE,EXCHANGE)  
  
  
SELECT CONVERT(VARCHAR(11),EDT) AS EDT,EXCHANGE='NSECM',L.VTYP AS VTYP,BANKCODE = A.CLTCODE,BANKNAME = '',VNO,DRCR,BOOKTYPE INTO #BANKREPORT  
FROM LEDGER L WITH (NOLOCK), #BANKCODE A  
WHERE EDT BETWEEN @EDT AND @EDT + ' 23:59' AND L.CLTCODE = A.CLTCODE AND EXCHANGE='NSECM' AND VTYP <> 18  
UNION ALL  
SELECT CONVERT(VARCHAR(11),EDT) AS EDT,EXCHANGE='BSECM',L.VTYP,BANKCODE = A.CLTCODE,BANKNAME = '',VNO,DRCR,BOOKTYPE  
FROM ANAND.ACCOUNT_AB.DBO.LEDGER L WITH (NOLOCK), #BANKCODE A  
WHERE EDT BETWEEN @EDT AND @EDT + ' 23:59'  AND L.CLTCODE = A.CLTCODE AND EXCHANGE='BSECM' AND VTYP <> 18
  
/*  
INSERT INTO #BANKREPORT  
SELECT CONVERT(VARCHAR(11),EDT) AS EDT,EXCHANGE='NSECM',L.VTYP AS VTYP,BANKCODE = A.CLTCODE,BANKNAME = '',VNO,DRCR,BOOKTYPE  
FROM LEDGER L WITH (NOLOCK), #BANKCODE A  
WHERE EDT BETWEEN @EDT AND @EDT + ' 23:59' AND L.CLTCODE = A.CLTCODE AND EXCHANGE='NSECM' AND VTYP = 3 AND NARRATION LIKE 'Amt Transfer A/c%'  
UNION ALL  
SELECT CONVERT(VARCHAR(11),EDT) AS EDT,EXCHANGE='BSECM',L.VTYP,BANKCODE = A.CLTCODE,BANKNAME = '',VNO,DRCR,BOOKTYPE  
FROM ANAND.ACCOUNT_AB.DBO.LEDGER L WITH (NOLOCK), #BANKCODE A  
WHERE EDT BETWEEN @EDT AND @EDT + ' 23:59'  AND L.CLTCODE = A.CLTCODE AND EXCHANGE='BSECM' AND VTYP = 3 AND NARRATION LIKE 'Amt Transfer A/c%'  
  
  
INSERT INTO #BANKREPORT  
SELECT CONVERT(VARCHAR(11),EDT) AS EDT,EXCHANGE='NSECM',L.VTYP AS VTYP,BANKCODE = A.CLTCODE,BANKNAME = '',VNO,DRCR,BOOKTYPE  
FROM LEDGER L WITH (NOLOCK), #BANKCODE A  
WHERE EDT BETWEEN @EDT AND @EDT + ' 23:59' AND L.CLTCODE = A.CLTCODE AND EXCHANGE='NSECM' AND VTYP = 3 AND NARRATION LIKE 'Amount transferred to A/C%'  
UNION ALL  
SELECT CONVERT(VARCHAR(11),EDT) AS EDT,EXCHANGE='BSECM',L.VTYP,BANKCODE = A.CLTCODE,BANKNAME = '',VNO,DRCR,BOOKTYPE  
FROM ANAND.ACCOUNT_AB.DBO.LEDGER L WITH (NOLOCK), #BANKCODE A  
WHERE EDT BETWEEN @EDT AND @EDT + ' 23:59'  AND L.CLTCODE = A.CLTCODE AND EXCHANGE='BSECM' AND VTYP = 3 AND NARRATION LIKE 'Amount transferred to A/C%'  
  
INSERT INTO #BANKREPORT  
SELECT CONVERT(VARCHAR(11),EDT) AS EDT,EXCHANGE='NSECM',L.VTYP AS VTYP,BANKCODE = A.CLTCODE,BANKNAME = '',VNO,DRCR,BOOKTYPE   
FROM LEDGER L WITH (NOLOCK), #BANKCODE A  
WHERE EDT BETWEEN @EDT AND @EDT + ' 23:59' AND L.CLTCODE = A.CLTCODE AND EXCHANGE='NSECM' AND VTYP = 3 AND NARRATION LIKE 'Amt Transfer Quarterly Settlement%'  
UNION ALL  
SELECT CONVERT(VARCHAR(11),EDT) AS EDT,EXCHANGE='BSECM',L.VTYP,BANKCODE = A.CLTCODE,BANKNAME = '',VNO,DRCR,BOOKTYPE  
FROM ANAND.ACCOUNT_AB.DBO.LEDGER L WITH (NOLOCK), #BANKCODE A  
WHERE EDT BETWEEN @EDT AND @EDT + ' 23:59'  AND L.CLTCODE = A.CLTCODE AND EXCHANGE='BSECM' AND VTYP = 3 AND NARRATION LIKE 'Amt Transfer Quarterly Settlement%'  
*/  
  
  
CREATE CLUSTERED INDEX CLTIDXLED ON #BANKREPORT(VTYP,VNO,BOOKTYPE)  
  
/*  
DELETE #BANKREPORT FROM #BANKREPORT A , LEDGER1 L WITH (NOLOCK) WHERE A.VNO = L.VNO AND A.VTYP = L.VTYP AND A.BOOKTYPE = L.BOOKTYPE  
AND A.EDT > L.RELDT AND EXCHANGE='NSECM' AND A.VTYP = 2  
  
DELETE #BANKREPORT  FROM #BANKREPORT A , ANAND.ACCOUNT_AB.DBO.LEDGER1 L WITH (NOLOCK) WHERE A.VNO = L.VNO AND A.VTYP = L.VTYP AND A.BOOKTYPE = L.BOOKTYPE  
AND A.EDT > L.RELDT AND EXCHANGE='BSECM' AND A.VTYP = 2  
  
*/  
  
SELECT CONVERT(VARCHAR(11),A.EDT) AS EDT,A.CLTCODE,VAMT,A.VNO,A.VTYP,EXCHANGE,A.BOOKTYPE INTO #LEDGER_PAY FROM LEDGER A WITH (NOLOCK) , #BANKREPORT B   
WHERE  A.EDT BETWEEN @EDT AND @EDT + ' 23:59' AND A.CLTCODE <> B.BANKCODE  AND  A.VTYP <> 18 AND A.VTYP = B.VTYP AND A.VNO = B.VNO  AND A.BOOKTYPE = B.BOOKTYPE  
AND EXCHANGE = 'NSECM'  
  
INSERT INTO #LEDGER_PAY   
SELECT CONVERT(VARCHAR(11),A.EDT) AS EDT,A.CLTCODE,VAMT,A.VNO,A.VTYP,EXCHANGE,A.BOOKTYPE FROM ANAND.ACCOUNT_AB.DBO.LEDGER A WITH (NOLOCK) , #BANKREPORT B   
WHERE  A.EDT BETWEEN @EDT AND @EDT + ' 23:59' AND A.CLTCODE <> B.BANKCODE AND  A.VTYP <> 18 AND A.VTYP = B.VTYP AND A.VNO = B.VNO  AND A.BOOKTYPE = B.BOOKTYPE  
AND EXCHANGE = 'BSECM'  
  
DELETE #LEDGER_PAY WHERE CLTCODE NOT IN (SELECT CLTCODE FROM #CLIENTCODE)  
  
  
ALTER TABLE #BANKREPORT ALTER COLUMN BANKNAME VARCHAR(150)  
  
UPDATE #BANKREPORT SET BANKNAME = ACNAME  
FROM #BANKCODE WHERE #BANKCODE.CLTCODE = #BANKREPORT.BANKCODE AND #BANKCODE.EXCHANGE = #BANKREPORT.EXCHANGE   
  
  
SELECT CONVERT(VARCHAR(11),A.EDT) AS EDT,A.EXCHANGE AS EXCHANGE,A.VTYP AS VTYP,BANKCODE = A.BANKCODE,BANKNAME ,  
[PAYIN AMOUNT] = CONVERT(NUMERIC(18,2),SUM(CASE WHEN DRCR = 'D' THEN VAMT ELSE 0 END)),  
[PAYOUT AMOUNT] = CONVERT(NUMERIC(18,2),SUM(CASE WHEN DRCR = 'C' THEN VAMT ELSE 0 END)),COUNT_ENT=COUNT(A.VNO)  
INTO #LEDGER_PAY_FINAL FROM #BANKREPORT A, #LEDGER_PAY B WITH (NOLOCK) WHERE  A.VNO = B.VNO AND A.VTYP = B.VTYP  
AND A.EXCHANGE = B.EXCHANGE AND A.BOOKTYPE = B.BOOKTYPE  
GROUP BY  CONVERT(VARCHAR(11),A.EDT) ,A.EXCHANGE ,A.VTYP,A.BANKCODE,BANKNAME  
  
  
DECLARE @EMAILS VARCHAR(4000),@BODYCONTENT VARCHAR(MAX),@PEOPLE VARCHAR(4000),@SNAME VARCHAR(4000),@SUB VARCHAR(4000),@XML VARCHAR(MAX),@TBLE VARCHAR(MAX),@SUB1 VARCHAR(4000)        
        
SET @SUB = 'Bank Payin / Payout Report as on : ' + CONVERT(VARCHAR(11),@edt,105)      
        
        
SET @SUB1 = 'Following is the Bank Pay-in / Payout report.'       
        
SET @XML =  CAST((SELECT [td/@align]='center',[td/@width]='10%',td = EDT,'',        
    [td/@align]='center',[td/@width]='10%',td = EXCHANGE ,'',        
    [td/@align]='center',[td/@width]='10%',td =VTYP,'',        
    [td/@align]='center',[td/@width]='10%',td = BANKCODE,'',        
    [td/@align]='center',[td/@width]='30%',td = BANKNAME,'',        
    [td/@align]='center',[td/@width]='10%',td = [PAYIN AMOUNT] ,'',        
    [td/@align]='center',[td/@width]='10%',td = [PAYOUT AMOUNT],'',  
 [td/@align]='center',[td/@width]='10%',td = COUNT_ENT,''  
FROM #LEDGER_PAY_FINAL ORDER BY EXCHANGE,VTYP,BANKCODE DESC FOR XML PATH('TR'), ELEMENTS ) AS VARCHAR(MAX))        
  
  
  
SET @TBLE ='<HTML><HEAD><STYLE>BODY>TABLE>TBODY>TR>TD:NTH-CHILD(1)BODY>TABLE>TBODY>TR>TD:NTH-CHILD(2)BODY>TABLE>TBODY > TR > TD:NTH-CHILD(3)BODY>TABLE>TBODY>TR>TD:NTH-CHILD(4)BODY>TABLE>TBODY>TR>TD:NTH-CHILD(5)BODY>TABLE>TBODY>TR>TD:NTH-CHILD(6)BODY>TABLE>TBODY>TR>TD:NTH-CHILD(7)BODY>TABLE>TBODY>TR>TD:NTH-CHILD(10) BODY > TABLE > TBODY > TR > TD:NTH-CHILD(11)BODY > TABLE > TBODY > TR > TD:NTH-CHILD(12) BODY > TABLE > TBODY > TR > TD:NTH-CHILD(13) </STYLE> </HEAD> <TABLE BORDER = 1;> <THEAD> <TR STYLE="BACKGROUND-COLOR: #4F6E9C; COLOR: WHITE; FONT-SIZE: 13PX"><TH> Effective Date </TH> <TH> Exchange </TH><TH> Vtyp </TH><TH> Bankcode </TH> <TH> BankName </TH> <TH> Payin Amount </TH> <TH> Payout Amount </TH> <TH> Count Ent </TH> </TR> </THEAD><TBODY STYLE="FONT-SIZE: 13PX;">'            
        
SET @TBLE = @TBLE + @XML +'</TBODY></TABLE></BODY></HTML>'        
        
SELECT @BODYCONTENT = '<P><SPAN STYLE="COLOR: RGB(0, 0, 128); FONT-FAMILY: VERDANA; FONT-SIZE: SMALL; FONT-STYLE: NORMAL; FONT-VARIANT-LIGATURES: NORMAL; FONT-VARIANT-CAPS: NORMAL; FONT-WEIGHT: 400; LETTER-SPACING: NORMAL; ORPHANS: 2; TEXT-ALIGN: START; TEXT-INDENT: 0PX; TEXT-TRANSFORM: NONE; WHITE-SPACE: NORMAL; WIDOWS: 2; WORD-SPACING: 0PX; -WEBKIT-TEXT-STROKE-WIDTH: 0PX; BACKGROUND-COLOR: RGB(255, 255, 255); TEXT-DECORATION-THICKNESS: INITIAL; TEXT-DECORATION-STYLE: INITIAL; TEXT-DECORATION-COLOR: INITIAL; DISPLAY: INLINE !IMPORTANT; FLOAT: NONE;">Dear All,</SPAN></P><P><SPAN STYLE="COLOR: RGB(0, 0, 128); FONT-FAMILY: VERDANA; FONT-SIZE: SMALL; FONT-STYLE: NORMAL; FONT-VARIANT-LIGATURES: NORMAL; FONT-VARIANT-CAPS: NORMAL; FONT-WEIGHT: 400; LETTER-SPACING: NORMAL; ORPHANS: 2; TEXT-ALIGN: START; TEXT-INDENT: 0PX; TEXT-TRANSFORM: NONE; WHITE-SPACE: NORMAL; WIDOWS: 2; WORD-SPACING: 0PX; -WEBKIT-TEXT-STROKE-WIDTH: 0PX; BACKGROUND-COLOR: RGB(255, 255, 255); TEXT-DECORATION-THICKNESS: INITIAL; TEXT-DECORATION-STYLE: INITIAL; TEXT-DECORATION-COLOR: INITIAL; DISPLAY: INLINE !IMPORTANT; FLOAT: NONE;">'+ @SUB1 + '</P>'+@TBLE+''        
             
EXEC MSDB.DBO.SP_SEND_DBMAIL         
@PROFILE_NAME='BO SUPPORT',         
@RECIPIENTS='narayan.patankar@angelbroking.com;rahulc.shah@angelbroking.com;vishal.doshi@angelbroking.com;corporatefinance@angelbroking.com;sajeev@angelbroking.com;banking@angelbroking.com;pranita@angelbroking.com',               
@SUBJECT=@SUB,        
@BODY=@BODYCONTENT,        
@IMPORTANCE = 'HIGH',        
@BODY_FORMAT ='HTML'        
  
--SELECT @BODYCONTENT  
  
DROP TABLE #CLIENTCODE  
DROP TABLE #LEDGER_PAY  
DROP TABLE #LEDGER_PAY_FINAL  
DROP TABLE #BANKCODE  
DROP TABLE #BANKREPORT

GO
