-- Object: PROCEDURE dbo.CLS_RECON_ACC_PRINTRECONCILE_28112022
-- Server: 10.253.33.91 | DB: ACCOUNT
--------------------------------------------------



CREATE PROCEDURE  [dbo].[CLS_RECON_ACC_PRINTRECONCILE]    
                      
@CODE VARCHAR(10),                        
@REPORTTYPE VARCHAR(10), 
@FDATE  VARCHAR(11) ,
@TDATE  VARCHAR(20),
@USERAMOUNT VARCHAR(50), 
@REPORTFLAG VARCHAR(50) ,
@SELECTIONBY VARCHAR(3)='VDT'
                   
AS

SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED

SELECT	@TDATE = CONVERT(VARCHAR(11), CONVERT(DATETIME, @TDATE, 103), 109)
SELECT	@FDATE = CONVERT(VARCHAR(11), CONVERT(DATETIME, @FDATE, 103), 109)



SET @TDATE= @TDATE +' 23:59:59'
--SET @FDATE=@FDATE +' 23:59:59'

CREATE TABLE #TEMPBANKRECON(CLTCODE VARCHAR(50), BOOKDATE DATETIME, DESCRIPTION VARCHAR(150), AMOUNT MONEY, DRCR VARCHAR(5), VALUEDATE DATETIME, REFERENCENO VARCHAR(50)
, STATUSID VARCHAR(50), STATUSNAME VARCHAR(50), LOGINNAME VARCHAR(50), CROSSREFERENCENO BIGINT, STATUS VARCHAR(50), BOOKDATE1 VARCHAR(50))


IF UPPER(@REPORTTYPE) = 'STATEMENT' 
BEGIN
SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED

IF OBJECT_ID('tempdb..#TEMPLEDGERDATA') IS NOT NULL
DROP TABLE #TEMPLEDGERDATA

SELECT VNO,VTYP,BOOKTYPE
INTO #TEMPLEDGERDATA FROM LEDGER (NOLOCK)
WHERE CLTCODE = @CODE
--AND VDT <= @TDATE
--AND (VDT <= CASE WHEN @SELECTIONBY='VDT' THEN @TDATE END OR EDT <= CASE WHEN @SELECTIONBY='EDT' THEN @TDATE END)
AND @TDATE  >= (CASE WHEN @SELECTIONBY='VDT' THEN 'VDT' ELSE 'EDT' END)

CREATE NONCLUSTERED INDEX IDX_LEDGDATA ON #TEMPLEDGERDATA(VTYP,VNO,BOOKTYPE)

IF OBJECT_ID('tempdb..#TEMPCHEQUELEDGER') IS NOT NULL
DROP TABLE #TEMPCHEQUELEDGER

SELECT VNO,VTYP,BOOKTYPE 
INTO #TEMPCHEQUELEDGER FROM LEDGER (NOLOCK)
WHERE CLTCODE = @CODE
--AND VDT <= @TDATE
--AND (VDT <= CASE WHEN @SELECTIONBY='VDT' THEN @TDATE END OR EDT <= CASE WHEN @SELECTIONBY='EDT' THEN @TDATE END)
AND @TDATE  >= (CASE WHEN @SELECTIONBY='VDT' THEN 'VDT' ELSE 'EDT' END)
AND VTYP = 16

CREATE NONCLUSTERED INDEX IDX_LEDGCHQDATA ON #TEMPCHEQUELEDGER(VNO,VTYP,BOOKTYPE)

IF OBJECT_ID('tempdb..#TEMPDATALEDGER1') IS NOT NULL
DROP TABLE #TEMPDATALEDGER1

--SELECT DDNO,DDDT,RELDT,RELAMT,VTYP,VNO,LNO,DRCR,REFNO,BOOKTYPE,MICRNO,CLEAR_MODE 
--INTO #TEMPDATALEDGER1 FROM LEDGER1(NOLOCK)
--WHERE RELDT = '1900-01-01 00:00:00.000' OR RELDT > @TDATE

SELECT DDNO,DDDT,RELDT,RELAMT,L1.VTYP,L1.VNO,L1.LNO,L1.DRCR,REFNO,L1.BOOKTYPE,MICRNO,CLEAR_MODE   INTO #TEMPDATALEDGER1 
 FROM LEDGER1(NOLOCK)  L1  INNER JOIN #TEMPLEDGERDATA L ON L1.VNO=L.VNO AND L1.VTYP=L.VTYP AND L1.BOOKTYPE=L.BOOKTYPE
 INNER JOIN #TEMPCHEQUELEDGER L2 ON L1.VNO=L2.VNO AND L1.VTYP=L2.VTYP AND L1.BOOKTYPE=L2.BOOKTYPE 
 WHERE RELDT = '1900-01-01 00:00:00.000' OR RELDT > @TDATE

CREATE NONCLUSTERED INDEX IDX_LEDG1 ON #TEMPDATALEDGER1(VTYP,BOOKTYPE,VNO,LNO)


SELECT
	L.VTYP,L.BOOKTYPE,L.VNO,VDT,EDT=CONVERT(VARCHAR(11), EDT, 105),TDATE = CONVERT(VARCHAR, L.VDT, 103),ISNULL(DDNO, '') DDNO,ISNULL(CLTCODE, '') CLTCODE,ISNULL(ACNAME, '') ACNAME,L.DRCR
	,DRAMT = (CASE	WHEN UPPER(L.DRCR) = 'D' THEN RELAMT ELSE 0	END)
	,CRAMT = (CASE	WHEN UPPER(L.DRCR) = 'C' THEN RELAMT ELSE 0	END)
	,TRELDT = ISNULL(CONVERT(VARCHAR, RELDT, 103), '')
	,L1.REFNO
	,NARRATION = LEFT(L.NARRATION, 75) 
	INTO #TEMPLEDGER
	FROM	LEDGER L
		,(SELECT * FROM #TEMPDATALEDGER1	) L1
		,(SELECT * FROM #TEMPLEDGERDATA) L2
			WHERE L.VTYP = L2.VTYP
			AND L.VNO = L2.VNO
			AND L.BOOKTYPE = L2.BOOKTYPE
			AND L.VTYP = L1.VTYP
			AND L.BOOKTYPE = L1.BOOKTYPE
			AND L.VNO = L1.VNO
			AND L.LNO = L1.LNO
			AND CLTCODE <> @CODE
		AND NOT EXISTS (SELECT	L3.DDNO	FROM	LEDGER1 L3	,(SELECT * FROM #TEMPCHEQUELEDGER) L4
			WHERE L1.DDNO = L3.DDNO
			AND CONVERT(VARCHAR(11), L1.DDDT, 109) = CONVERT(VARCHAR(11), L3.DDDT, 109)
			AND L1.RELAMT = L3.RELAMT
			AND L3.VNO = L4.VNO
			AND L3.VTYP = L4.VTYP
			AND L3.BOOKTYPE = L4.BOOKTYPE
			AND L1.BOOKTYPE = L3.BOOKTYPE)
			ORDER BY L.DRCR, VDT, L.VTYP, L.VNO

SELECT	* INTO #TEMPLEDGER2
FROM #TEMPLEDGER WHERE 1 = 2

ALTER TABLE #TEMPLEDGER2
ADD MAXVDT DATETIME

	INSERT INTO #TEMPLEDGER2
	SELECT		VTYP,BOOKTYPE,VNO,VDT,EDT,TDATE,DDNO,CLTCODE,ACNAME,DRCR,DRAMT,CRAMT,TRELDT,REFNO,NARRATION	,VDT	FROM #TEMPLEDGER 
	UNION
	SELECT '','','','','','','','','','D',0,0,'','','ADD :: CHEQUES ISSUED BUT NOT PRESENTED :','01-01-2010'	FROM #TEMPLEDGER 
	UNION 
	SELECT '','','','','','','','','','C',0,0,'','','LESS :: LIST OF CHEQUES DEPOSITED BUT NOT CREDITED :','01-01-2010'FROM #TEMPLEDGER
	UNION 
	SELECT '','','','','','','','','','D',SUM(DRAMT),0,'','','TOTAL DEBIT AMOUNT','01-01-2049'	FROM #TEMPLEDGER 
	UNION 
	SELECT '','','','','','','','','','C',0,SUM(CRAMT),'','','TOTAL CREDIT AMOUNT','01-01-2049'FROM #TEMPLEDGER

	SELECT  VTYP,BOOKTYPE,VNO,VDT = CONVERT(VARCHAR(11), VDT, 105),EDT,TDATE,DDNO,CLTCODE,ACNAME,DRCR,DRAMT,CRAMT,TRELDT,REFNO,NARRATION,MAXVDT FROM #TEMPLEDGER2
	ORDER BY DRCR, MAXVDT
	
	
	INSERT INTO #TEMPBANKRECON
	EXEC CLS_BANKRECO_REPORT	@CODE,@TDATE
	
	SELECT	* INTO #TEMPBANKRECON2 FROM #TEMPBANKRECON WHERE 1 = 2

	ALTER TABLE #TEMPBANKRECON2	ADD ORDERDATE DATETIME

	INSERT INTO #TEMPBANKRECON2
	SELECT CLTCODE,BOOKDATE,LEFT(DESCRIPTION, 100),AMOUNT,DRCR,VALUEDATE,REFERENCENO,STATUSID,STATUSNAME,LOGINNAME,CROSSREFERENCENO,STATUS,BOOKDATE1,ORDERDATE = BOOKDATE
	FROM #TEMPBANKRECON 

	UNION 

	SELECT '','','LESS :: CHEQUES DEBITED BY BANK :',0	,'C','','','','','','','','',ORDERDATE = '01-01-2010' --FROM #TEMPBANKRECON
	

	UNION 

	SELECT '','','ADD :: CHEQUES CREDITED BY  BANK :',0	,'D','','','','',''	,''	,'','',ORDERDATE = '01-01-2010'	--FROM #TEMPBANKRECON
	

	UNION 

	SELECT '','','TOTAL CREDIT AMOUNT',CASE WHEN DRCR = 'C' THEN SUM(AMOUNT) ELSE 0 END	,'C','','','','','','','','',ORDERDATE = '01-01-2049'FROM #TEMPBANKRECON
	GROUP BY DRCR 

	UNION 

	SELECT '','','TOTAL DEBIT AMOUNT',CASE	WHEN DRCR = 'D' THEN SUM(AMOUNT)	ELSE 0	END	,'D','','','','',''	,''	,'','',ORDERDATE = '01-01-2049'	FROM #TEMPBANKRECON
	GROUP BY DRCR

	DELETE FROM #TEMPBANKRECON2
	WHERE DESCRIPTION IN ('TOTAL CREDIT AMOUNT', 'TOTAL DEBIT AMOUNT')	AND AMOUNT = 0

	
	
--BANK STATEMENT
	SELECT	CLTCODE	,BOOKDATE = CONVERT(VARCHAR(11), BOOKDATE, 105)	,DESCRIPTION = LEFT(DESCRIPTION, 75)	,AMOUNT	,DRCR	,VALUEDATE = CONVERT(VARCHAR(11), BOOKDATE, 105)
	,REFERENCENO,STATUSID,STATUSNAME,LOGINNAME,CROSSREFERENCENO,STATUS,BOOKDATE1,ORDERDATE FROM #TEMPBANKRECON2-- WHERE  ORDERDATE<>'01-01-2010'
	ORDER BY DRCR, ORDERDATE 

--TOTAL
		CREATE TABLE #FINALRESULT(LEDGERBALANCE MONEY, CRAMT MONEY, DRAMT MONEY, CREDITBANKSTATEMENT MONEY, DEBITBANKSTATEMENT MONEY, USERAMOUNT MONEY, ORDERBY INT)
		DECLARE @USERAMT MONEY
		SET @USERAMT = 0

		IF (@USERAMOUNT <> '') 
		SELECT	@USERAMT = CAST(@USERAMOUNT AS MONEY)

 
		INSERT INTO #FINALRESULT
		SELECT
		SUM(CASE WHEN LEDGER.DRCR = 'D' THEN -VAMT	ELSE VAMT END) AS 'LEDGERBALANCE'
		,'' AS 'CRAMT'
		,'' AS 'DRAMT'
		,'' AS 'CREDITBANKSTATEMENT'
		,'' AS 'DEBITBANKSTATEMENT'
		,'' AS 'USERAMOUNT'
		,1 AS 'ORDERBY'
		FROM LEDGER(NOLOCK)
		WHERE VDT BETWEEN @FDATE AND @TDATE
		AND LEDGER.CLTCODE = @CODE
		
		UNION 

		SELECT	'',CRAMT,''	,'','','',2 AS 'ORDERBY'FROM #TEMPLEDGER2
		WHERE NARRATION = 'TOTAL CREDIT AMOUNT' 

		UNION 
		
		SELECT	'','',DRAMT,'','','',3 AS 'ORDERBY'	FROM #TEMPLEDGER2
		WHERE NARRATION = 'TOTAL DEBIT AMOUNT' 

		UNION 

		SELECT '','','',AMOUNT,'','',4 AS 'ORDERBY'	FROM #TEMPBANKRECON2
		WHERE DESCRIPTION = 'TOTAL CREDIT AMOUNT'
		
		UNION
		
		SELECT	''	,''	,''	,'',AMOUNT,'',5 AS 'ORDERBY' FROM #TEMPBANKRECON2
		WHERE DESCRIPTION = 'TOTAL DEBIT AMOUNT' 
		
		UNION 
		
		SELECT	'','','','','',@USERAMT
		,6 AS 'ORDERBY'

	SELECT LEDGERBALANCE = ISNULL(LEDGERBALANCE,'00'),CRAMT,DRAMT,CREDITBANKSTATEMENT,DEBITBANKSTATEMENT,USERAMOUNT,ORDERBY FROM #FINALRESULT
	ORDER BY ORDERBY

	SELECT	ABS(SUM(LEDGERBALANCE + CRAMT - DRAMT - CREDITBANKSTATEMENT + DEBITBANKSTATEMENT)) AS 'TOTALCAL'
		,ABS(SUM(LEDGERBALANCE + CRAMT - DRAMT - CREDITBANKSTATEMENT + DEBITBANKSTATEMENT) )- @USERAMT AS 'FINALTOTALCAL'
		,@USERAMT AS 'USERAMOUNT'
	FROM #FINALRESULT


IF @REPORTFLAG = 'C' 
BEGIN

CREATE TABLE #TEMPLEDGER3(VOUCHERDATE DATETIME,
VOUCHERNO VARCHAR(75),
DDNO VARCHAR(30),
CLTCODE NVARCHAR(50),
ACNAME NVARCHAR(200),
DEBIT DECIMAL(18, 2),
CREDIT DECIMAL(18, 2),
ORDERBY INT)

--UPDATE #TEMPLEDGER2 SET MAXVDT='01-01-2011' WHERE MAXVDT=''

INSERT INTO #TEMPLEDGER3
	SELECT	VDT,VNO,DDNO,CLTCODE,NARRATION,DRAMT,CRAMT,1 FROM #TEMPLEDGER2
	ORDER BY DRCR, MAXVDT
 

INSERT INTO #TEMPLEDGER3
	SELECT BOOKDATE,'',REFERENCENO,CLTCODE,DESCRIPTION
	,CASE	WHEN DRCR = 'C' THEN AMOUNT	ELSE 0	END
	,CASE	WHEN DRCR = 'D' THEN AMOUNT	ELSE 0	END
	,2
	FROM #TEMPBANKRECON2
	ORDER BY DRCR, ORDERDATE
UPDATE #TEMPLEDGER2 SET MAXVDT='' WHERE MAXVDT='01-01-2011'

INSERT INTO #TEMPLEDGER3 (VOUCHERNO, DEBIT, ORDERBY)
	SELECT	'BALANCE AS PER OUR BOOKS :'
	,LEDGERBALANCE
	,3
	FROM #FINALRESULT
	WHERE LEDGERBALANCE <> '0.00'

INSERT INTO #TEMPLEDGER3 (VOUCHERNO, DEBIT, ORDERBY)
	SELECT 'LESS :: LIST OF CHEQUES DEPOSITED BUT NOT CREDITED :'
	,CRAMT 
	,4
	FROM #FINALRESULT
	WHERE CRAMT <> '0.00'

INSERT INTO #TEMPLEDGER3 (VOUCHERNO, DEBIT, ORDERBY)
	SELECT
	'ADD :: CHEQUES ISSUED BUT NOT PRESENTED :'
	,DRAMT
	,5
	FROM #FINALRESULT
	WHERE DRAMT <> '0.00'

INSERT INTO #TEMPLEDGER3 (VOUCHERNO, DEBIT, ORDERBY)
	SELECT
	'LESS :: CHEQUES DEBITED BY BANK :'
	,DEBITBANKSTATEMENT
	,6
	FROM #FINALRESULT
	WHERE DEBITBANKSTATEMENT <> '0.00'

INSERT INTO #TEMPLEDGER3 (VOUCHERNO, DEBIT, ORDERBY)
	SELECT
	'ADD :: CHEQUES CREDITED BY  BANK :'
	,CREDITBANKSTATEMENT
	,7
	FROM #FINALRESULT
	WHERE CREDITBANKSTATEMENT <> '0.00'

INSERT INTO #TEMPLEDGER3 (VOUCHERNO, DEBIT, ORDERBY)
	SELECT
	'BALANCE AS PER BANK STATEMENT :'
	,ABS(SUM(LEDGERBALANCE + CRAMT - DRAMT - CREDITBANKSTATEMENT + DEBITBANKSTATEMENT))
	,8 AS 'TOTALCAL'
	FROM #FINALRESULT

INSERT INTO #TEMPLEDGER3 (VOUCHERNO, DEBIT, ORDERBY)
	SELECT
	'ENTERED BY USER :'
	,@USERAMT AS 'USERAMOUNT'
	,9

INSERT INTO #TEMPLEDGER3 (VOUCHERNO, DEBIT, ORDERBY)
	SELECT
	'DIFFERENCE IN BALANCES :'
	,ABS(SUM(LEDGERBALANCE + CRAMT - DRAMT - CREDITBANKSTATEMENT + DEBITBANKSTATEMENT) )- @USERAMT AS 'FINALTOTALCAL'
	,10
	FROM #FINALRESULT

SELECT
	VOUCHERDATE = CONVERT(VARCHAR(11), VOUCHERDATE, 103)
	,VOUCHERNO
	,DDNO
	,CLTCODE
	,ACNAME
	,CREDIT = DEBIT
	,DEBIT = CREDIT
FROM #TEMPLEDGER3
ORDER BY ORDERBY ASC


END

END

ELSE 

BEGIN
	SELECT DISTINCT	VTYP,BOOKTYPE,VNO,LNO INTO #TBLBANKRECO_TMP FROM LEDGER
	WHERE CLTCODE = @CODE
	AND VDT >= @FDATE
	AND VDT <= @TDATE

	CREATE CLUSTERED
	INDEX [PARTYVDT] ON [DBO].[#TBLBANKRECO_TMP] ([VNO], [VTYP], [BOOKTYPE])
	WITH
	FILLFACTOR = 90
	ON [PRIMARY]

	SELECT	L.* INTO #LEDGER_TMP FROM	LEDGER L,#TBLBANKRECO_TMP T
	WHERE L.VNO = T.VNO
	AND L.VTYP = T.VTYP
	AND L.BOOKTYPE = T.BOOKTYPE

	CREATE CLUSTERED
	INDEX [PARTYVDT] ON [DBO].[#LEDGER_TMP] ([VNO], [VTYP], [BOOKTYPE], [LNO])
	WITH
	FILLFACTOR = 90
	ON [PRIMARY]

	SELECT L.* INTO #LEDGER1_TMP FROM	LEDGER1 L,#TBLBANKRECO_TMP T
	WHERE L.VNO = T.VNO
	AND L.VTYP = T.VTYP
	AND L.BOOKTYPE = T.BOOKTYPE

	CREATE CLUSTERED
	INDEX [PARTYVDT] ON [DBO].[#LEDGER1_TMP] ([VNO], [VTYP], [BOOKTYPE], [LNO])
	WITH
	FILLFACTOR = 90
	ON [PRIMARY]

	SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED
	SELECT	L.VTYP	,L.BOOKTYPE,L.VNO,VDT,TDATE = CONVERT(VARCHAR, L.VDT, 103),ISNULL(DDNO, '') DDNO,ISNULL(CLTCODE, '') CLTCODE,ISNULL(ACNAME, '') ACNAME,L.DRCR
	,DRAMT = (CASE	WHEN UPPER(L.DRCR) = 'D' THEN RELAMT ELSE 0	END)
	,CRAMT = (CASE	WHEN UPPER(L.DRCR) = 'C' THEN RELAMT ELSE 0	END)
	,TRELDT = ISNULL(CONVERT(VARCHAR, RELDT, 103), '')
	,L1.REFNO
	,L.NARRATION
	FROM	#LEDGER_TMP L,#LEDGER1_TMP L1
	WHERE L.VNO = L1.VNO
	AND L.VTYP = L1.VTYP
	AND L.BOOKTYPE = L1.BOOKTYPE

	EXEC CLS_BANKRECO_REPORT	@CODE,@TDATE

	DROP TABLE #TBLBANKRECO_TMP
	DROP TABLE #LEDGER_TMP
	DROP TABLE #LEDGER1_TMP


END

GO
