-- Object: PROCEDURE dbo.GET_AUDIT_DATA_NEW_DETAILS_bkp_20220207
-- Server: 10.253.33.91 | DB: ACCOUNT
--------------------------------------------------




-- EXEC GET_AUDIT_DATA_NEW_DETAILS 'Feb 22 2021', 'Feb 27 2021', '000', 'zzz' 

CREATE PROCEDURE [dbo].[GET_AUDIT_DATA_NEW_DETAILS_bkp_20220207]    
 @REPORT_DATE VARCHAR(11), 
@REPORT_DATE_TO  VARCHAR(11), 
@CLTCODE_FR VARCHAR(10) = '00000',    
 @CLTCODE_TO VARCHAR(10) = 'ZZZZZ',    
 @SESSIONID VARCHAR(15) = '8888888888',    
 @EXCH_LIST VARCHAR(1000) = ''  
AS  

DECLARE 
      @PANNO            VARCHAR(20) 

SELECT      @PANNO = ISNULL(LTRIM(RTRIM(PANNO)),'') FROM OWNER (NOLOCK) 

DECLARE 
                  @@MFSS_FLAG BIT, 
                  @@MARGIN_FLAG BIT, 
                  @@PARENT_FLAG BIT 

            SELECT @@MFSS_FLAG = MFSS_FLAG, @@MARGIN_FLAG = MARGIN_FLAG, @@PARENT_FLAG = PARENT_FLAG FROM MSAJAG..WEEKLY_CASH_BALANCES_SETTING 

DECLARE 
      @@DATA_SRV VARCHAR(30), 
      @@DATA_SDB VARCHAR(30), 
      @@DATA_ADB VARCHAR(30), 
      @EXCHANGE VARCHAR(10), 
      @SEGMENT VARCHAR(10), 
      @REPORT_FORMULA VARCHAR(50), 
      @ACCSERVER      VARCHAR(30), 
      @ACCDB                  VARCHAR(30), 
      @MEMBERCODE       VARCHAR(10) 
      
DECLARE 
      @@SQL VARCHAR(MAX), 
      @BBO_FA_SRV VARCHAR(100), 
      @OPEN_DATE VARCHAR(11) 

      SELECT @OPEN_DATE = CONVERT(VARCHAR(11), SDTCUR, 109) FROM PARAMETER WHERE @REPORT_DATE BETWEEN SDTCUR AND LDTCUR 

      SET @BBO_FA_SRV = '' 

      SELECT @BBO_FA_SRV=  ACCOUNTSERVER FROM PRADNYA.DBO.AUDIT_MULTICOMPANY_ALL_NEW WHERE SEGMENT = 'MFSS' AND EXCHANGE = 'BSE' 

SELECT @MEMBERCODE = MEMBERCODE FROM MSAJAG.DBO.OWNER 
CREATE TABLE #CL_LIST    
(    
 SRNO INT IDENTITY(1, 1), 
PARTY_CODE VARCHAR(10),    
 PARTY_NAME VARCHAR(100),    
 CLIENT_PAN VARCHAR(50), 
CL_TYPE VARCHAR(10), 
PARENT_CODE VARCHAR(10)   
)    
     
INSERT INTO #CL_LIST    
SELECT CL_CODE, LONG_NAME, PAN_GIR_NO, CL_TYPE, PARENTCODE = CASE WHEN @@PARENT_FLAG = 1 THEN PARENTCODE ELSE CL_CODE END 
FROM MSAJAG..VW_CLIENT_DETAILS_DATA  (NOLOCK)  
WHERE CL_CODE BETWEEN @CLTCODE_FR AND @CLTCODE_TO    


/* QUERY TO UPDATE THE PARENT DETAILS FOR THE DETAILS */ 
IF @@PARENT_FLAG = 1 
BEGIN 
      UPDATE C SET C.PARTY_NAME =C1.PARTY_NAME, C.CLIENT_PAN = C1.CLIENT_PAN 
      FROM #CL_LIST C, (SELECT * FROM #CL_LIST WHERE PARTY_CODE = PARENT_CODE) C1 
      WHERE C1.PARTY_CODE = C.PARENT_CODE 
END 

    

CREATE TABLE [DBO].[#DBNAME](ACCOUNTDB VARCHAR(20), 
EXCHANGE VARCHAR(6), 
SEGMENT VARCHAR(10), 
ACCOUNTSERVER VARCHAR(50), 
SHAREDB VARCHAR(20)) ON [PRIMARY] 
DECLARE @@DB VARCHAR(1000) 

--SET @EXCSEGMENT = REPLACE(LEFT(@EXCSEGMENT,LEN(@EXCSEGMENT)),'|',',')          
--PRINT @EXCSEGMENT 

CREATE TABLE #WEEKLY_REPORT_DETAILS 
( 
      SRNO INT, 
      UCC VARCHAR(10), 
      PARTY_CODE VARCHAR(10),    
      PARTY_NAME VARCHAR(100),    
      CLIENT_PAN VARCHAR(50), 
      CL_TYPE VARCHAR(10), 
      VDT DATETIME, 
      EDT DATETIME, 
      EXCHSEG VARCHAR(20), 
      SETT_TYPE VARCHAR(10), 
      SETT_NO VARCHAR(10), 
      CHQNO VARCHAR(50), 
      VDESC VARCHAR(50), 
      NARRATION VARCHAR(2000), 
      VNO VARCHAR(12), 
      DEBIT MONEY, 
      CREDIT MONEY, 
      BALANCE MONEY, 
      TABLE_CODE VARCHAR(10) 
) 

CREATE TABLE #VMAST 
( 
      VTYPE INT, 
      VDESC VARCHAR(100), 
      SHORTDESC VARCHAR(50) 
) 

CREATE TABLE #LEDGER 
( 
      CLTCODE VARCHAR(10), 
      VDT DATETIME, 
      EDT DATETIME, 
      DRCR VARCHAR(2), 
      VAMT MONEY, 
      NARRATION VARCHAR(500), 
      VNO VARCHAR(12), 
      VTYP INT, 
      BOOKTYPE VARCHAR(3), 
      LNO INT, 
      TABLE_CODE VARCHAR(10) 
) 

CREATE TABLE #REPORT_DATA 
( 
      CLTCODE VARCHAR(10), 
      VDT DATETIME, 
      EDT DATETIME, 
      DRCR VARCHAR(2), 
      VAMT MONEY, 
      NARRATION VARCHAR(500), 
      DDNO VARCHAR(30), 
      RELDT DATETIME, 
      SETT_NO VARCHAR(10), 
      SETT_TYPE VARCHAR(10), 
      VNO VARCHAR(12), 
      VTYP INT, 
      BOOKTYPE VARCHAR(3), 
      TABLE_CODE VARCHAR(10) 
) 

          


INSERT INTO #DBNAME SELECT ACCOUNTDB, EXCHANGE, SEGMENT, ACCOUNTSERVER, SHAREDB FROM PRADNYA.DBO.AUDIT_MULTICOMPANY_ALL_NEW (NOLOCK) WHERE SEGMENT <> 'MFSS' 

DECLARE @@MAINREC AS CURSOR 

/* GETTING T1 AND T2 DAYS LOGIC TO GET THE OPEN BILL LOGIC */ 



/* CURSOR SET FOR NON MFSS SEGMENSTS */ 
--SET @@SQL = ""          
SET @@MAINREC = CURSOR FOR SELECT 
      ACCOUNTDB 
      ,EXCHANGE 
      ,SEGMENT 
      ,ACCOUNTSERVER 
      ,SHAREDB 
FROM #DBNAME 


OPEN @@MAINREC 
FETCH NEXT FROM @@MAINREC INTO @@DATA_ADB, @EXCHANGE, @SEGMENT, @@DATA_SRV, @@DATA_SDB 
WHILE @@FETCH_STATUS = 0 
BEGIN 
      TRUNCATE TABLE #LEDGER 
      TRUNCATE TABLE #VMAST 
      TRUNCATE TABLE #REPORT_DATA 

      SET @@SQL = "INSERT INTO #LEDGER " 
      IF @@DATA_SRV <> @@SERVERNAME 
            SET @@SQL = @@SQL + " SELECT CLTCODE, VDT, EDT, DRCR, VAMT, NARRATION, VNO, VTYP, BOOKTYPE, LNO, TABLE_CODE = CASE WHEN EDT > '" + @REPORT_DATE_TO + " 23:59:59' THEN 'TB2' ELSE 'TB1' END FROM " + @@DATA_SRV + "." + @@DATA_ADB + ".DBO.LEDGER L, #CL_LIST CL WHERE EDT >= '" + @OPEN_DATE + "' AND VDT <= '" + @REPORT_DATE_TO + " 23:59' AND PARTY_CODE = CLTCODE" 
      ELSE 
            SET @@SQL = @@SQL + " SELECT CLTCODE, VDT, EDT, DRCR, VAMT, NARRATION, VNO, VTYP, BOOKTYPE, LNO, TABLE_CODE = CASE WHEN EDT > '" + @REPORT_DATE_TO + " 23:59:59' THEN 'TB2' ELSE 'TB1' END FROM " + @@DATA_ADB + ".DBO.LEDGER (NOLOCK) L, #CL_LIST CL WHERE EDT >= '" + @OPEN_DATE + "' AND VDT <= '" + @REPORT_DATE_TO + " 23:59' AND PARTY_CODE = CLTCODE" 
      PRINT @@SQL 
      EXEC (@@SQL) 
      
      SET @@SQL = "INSERT INTO #VMAST " 
      IF @@DATA_SRV <> @@SERVERNAME 
            SET @@SQL = @@SQL + " SELECT VTYPE, VDESC, SHORTDESC FROM " + @@DATA_SRV + "." + @@DATA_ADB + ".DBO.VMAST" 
      ELSE 
            SET @@SQL = @@SQL + " SELECT VTYPE, VDESC, SHORTDESC FROM " + @@DATA_ADB + ".DBO.VMAST" 
      PRINT @@SQL 
      EXEC (@@SQL)      
      
      

      IF @@MARGIN_FLAG = 1 
      BEGIN 
            SET @@SQL = "INSERT INTO #LEDGER " 
            IF @@DATA_SRV <> @@SERVERNAME 
                  SET @@SQL = @@SQL + " SELECT CLTCODE = ML.PARTY_CODE, ML.VDT, EDT, ML.DRCR, AMOUNT, NARRATION, ML.VNO, ML.VTYP, ML.BOOKTYPE, ML.LNO, TABLE_CODE = CASE WHEN EDT > '" + @REPORT_DATE_TO + " 23:59:59' THEN 'TB2' ELSE 'TB1' END FROM " + @@DATA_SRV + "." + @@DATA_ADB + ".DBO.LEDGER L," + @@DATA_SRV + "." + @@DATA_ADB + ".DBO.MARGINLEDGER ML, #CL_LIST CL WHERE EDT >= '" + @OPEN_DATE + "' AND L.VDT <= '" + @REPORT_DATE_TO + " 23:59' AND CL.PARTY_CODE = ML.PARTY_CODE AND L.VNO = ML.VNO AND L.VTYP = ML.VTYP AND L.BOOKTYPE = ML.BOOKTYPE AND L.LNO = ML.LNO " 
            ELSE 
                  --SET @@SQL = @@SQL + " SELECT CLTCODE = PARTY_CODE, ML.VDT, EDT, ML.DRCR, AMOUNT, NARRATION, ML.VNO, ML.VTYP, ML.BOOKTYPE, ML.LNO, TABLE_CODE = CASE WHEN EDT > '" + @REPORT_DATE_TO + " 23:59:59' THEN 'TB2' ELSE 'TB1' END FROM " + @@DATA_ADB + ".DBO.LEDGER (NOLOCK) L, #CL_LIST CL WHERE EDT >= '" + @REPORT_DATE + "' AND VDT <= '" + @REPORT_DATE_TO + " 23:59' AND PARTY_CODE = CLTCODE" 
                  SET @@SQL = @@SQL + " SELECT CLTCODE = ML.PARTY_CODE, ML.VDT, EDT, ML.DRCR, AMOUNT, NARRATION, ML.VNO, ML.VTYP, ML.BOOKTYPE, ML.LNO, TABLE_CODE = CASE WHEN EDT > '" + @REPORT_DATE_TO + " 23:59:59' THEN 'TB2' ELSE 'TB1' END FROM " + @@DATA_ADB + ".DBO.LEDGER L," + @@DATA_ADB + ".DBO.MARGINLEDGER ML, #CL_LIST CL WHERE EDT >= '" + @OPEN_DATE + "' AND L.VDT <= '" + @REPORT_DATE_TO + " 23:59' AND CL.PARTY_CODE = ML.PARTY_CODE AND L.VNO = ML.VNO AND L.VTYP = ML.VTYP AND L.BOOKTYPE = ML.BOOKTYPE AND L.LNO = ML.LNO " 
            PRINT @@SQL 
            EXEC (@@SQL) 
      END 

      INSERT INTO #REPORT_DATA 
      SELECT CLTCODE, VDT = @REPORT_DATE, EDT = @REPORT_DATE, 
      DRCR = CASE WHEN SUM(VAMT) > 0 THEN 'C' ELSE 'D' END, 
      VAMT = ABS(SUM(VAMT)), NARRATION = 'OPENING BALANCE', DDNO = '', RELDT = '', 
      SETT_NO = '', SETT_TYPE = '', VNO = '', VTYP = '18', BOOKTYPE = '', TABLE_CODE = '' 
      FROM 
      ( 
            SELECT CLTCODE, 
            VAMT = (SUM(CASE WHEN (VTYP = 18 OR EDT < @REPORT_DATE) THEN CASE WHEN DRCR = 'C' THEN VAMT ELSE -VAMT END ELSE 0 END)) 
            FROM #LEDGER L 
            WHERE EDT BETWEEN @OPEN_DATE AND @REPORT_DATE 
            GROUP BY CLTCODE 
            UNION ALL 
            SELECT CLTCODE, 
            VAMT = (SUM(CASE WHEN DRCR = 'D' THEN VAMT ELSE -VAMT END)) 
            FROM #LEDGER L 
            WHERE EDT >= @OPEN_DATE AND VDT < @OPEN_DATE 
            GROUP BY CLTCODE 
      ) A 
      GROUP BY CLTCODE 

      SET @@SQL = " INSERT INTO #REPORT_DATA " 
      SET @@SQL = @@SQL + " SELECT CLTCODE, L.VDT, L.EDT, L.DRCR, VAMT, L.NARRATION, DDNO, RELDT, SETT_NO, SETT_TYPE, L.VNO, L.VTYP, L.BOOKTYPE, TABLE_CODE = CASE WHEN L.EDT > '" + @REPORT_DATE_TO + " 23:59:59' THEN 'TB2' ELSE 'TB1' END " 
      SET @@SQL = @@SQL + " FROM (SELECT * FROM #LEDGER WHERE EDT >= '" + @REPORT_DATE + "' AND vdt <= '" + @REPORT_DATE_TO + " 23:59') L " 
      SET @@SQL = @@SQL + " LEFT OUTER JOIN " + @@DATA_SRV + "." + @@DATA_ADB + ".DBO.LEDGER1 L1 ON L.VNO = L1.VNO AND L.VTYP = L1.VTYP AND L.BOOKTYPE = L1.BOOKTYPE AND L.LNO = L1.LNO " 
      SET @@SQL = @@SQL + " LEFT OUTER JOIN " + @@DATA_SRV + "." + @@DATA_ADB + ".DBO.BILLPOSTED B ON L.VNO = B.VNO AND L.VTYP = B.VTYP AND L.BOOKTYPE = B.BOOKTYPE " 
      SET @@SQL = @@SQL + " WHERE L.VTYP <> 18 " 
      PRINT @@SQL 
      EXEC (@@SQL) 



      INSERT INTO #WEEKLY_REPORT_DETAILS 
      SELECT SRNO, PARENT_CODE, PARTY_CODE, PARTY_NAME, CLIENT_PAN, CL_TYPE, VDT, EDT, @EXCHANGE + @SEGMENT,SETT_TYPE = ISNULL(SETT_TYPE, ''), 
      SETT_NO = ISNULL(SETT_NO, ''), DDNO = ISNULL(DDNO, ''), VDESC = Shortdesc, L.NARRATION, VNO, 
      DEBIT = CASE WHEN DRCR = 'D' THEN VAMT ELSE 0 END, CREDIT = CASE WHEN DRCR = 'C' THEN VAMT ELSE 0 END, RUNNING = 0, TABLE_CODE 
      FROM #CL_LIST C, #REPORT_DATA L, #VMAST V 
      WHERE CLTCODE = PARTY_CODE 
      AND L.VTYP = V.VTYPE 

FETCH NEXT FROM @@MAINREC INTO @@DATA_ADB, @EXCHANGE, @SEGMENT, @@DATA_SRV, @@DATA_SDB 
END 
/* CURSOR SET FOR NON MFSS SEGMENSTS */ 

IF @@MFSS_FLAG = 1 
BEGIN 
      INSERT INTO #WEEKLY_REPORT_DETAILS 
      SELECT SRNO, PARENT_CODE, PARTY_CODE, PARTY_NAME, CLIENT_PAN, CL_TYPE, VDT = @REPORT_DATE, EDT = @REPORT_DATE, EXCHANGE + SEGMENT, 
      SETT_TYPE = '', SETT_NO = '', 
      '', VDESC=V.ShortDesc, NARRATION = 'OPENING BALANCE', VNO = '', CASE WHEN SUM(DRAMOUNT - CRAMOUNT) > 0 THEN SUM(DRAMOUNT - CRAMOUNT) ELSE 0 END, CASE WHEN SUM(CRAMOUNT - DRAMOUNT) > 0 THEN SUM(CRAMOUNT - DRAMOUNT) ELSE 0 END, 
      RUNNING = 0, TABLE_CODE = 'TB1' 
      FROM #CL_LIST C, 
      (SELECT CLTCODE, EXCHANGE, SEGMENT, DRAMOUNT, CRAMOUNT FROM BBO_FA..ACC_LEDGER_PL WHERE EDT >= @OPEN_DATE AND EDT < @REPORT_DATE 
      UNION ALL 
      SELECT CLTCODE, EXCHANGE, SEGMENT, DRAMOUNT = CASE WHEN CRAMOUNT <> 0 THEN CRAMOUNT ELSE 0 END, 
      CRAMOUNT = CASE WHEN DRAMOUNT <> 0 THEN DRAMOUNT ELSE 0 END FROM BBO_FA..ACC_LEDGER_PL WHERE EDT >= @OPEN_DATE AND VDT < @OPEN_DATE) L, 
      (SELECT * FROM BBO_FA..VMAST WHERE Vtype = 18) V 
      WHERE PARTY_CODE = CLTCODE 
      GROUP BY SRNO, PARENT_CODE, PARTY_CODE, PARTY_NAME, CLIENT_PAN, CL_TYPE, EXCHANGE + SEGMENT, V.ShortDesc 


      INSERT INTO #WEEKLY_REPORT_DETAILS 
      SELECT SRNO, PARENT_CODE, PARTY_CODE, PARTY_NAME, CLIENT_PAN, CL_TYPE, VDT, EDT, EXCHANGE + SEGMENT, 
      SETT_TYPE, SETT_NO, 
      CASE WHEN ISNULL(CR_REFNO, '') <>'' THEN  ISNULL(CR_REFNO, '') ELSE ISNULL(DR_REFNO, '') END, VDESC=V.ShortDesc, L.NARRATION, VNO, DRAMOUNT, CRAMOUNT, RUNNING = 0, TABLE_CODE = 'TB1' 
      FROM #CL_LIST C, (SELECT * FROM BBO_FA..ACC_LEDGER_PL WHERE EDT BETWEEN @REPORT_DATE AND @REPORT_DATE_TO + ' 23:59') L, BBO_FA..VMAST V 
      WHERE PARTY_CODE = CLTCODE 
      AND L.VTYPE = V.VTYPE 
END 

INSERT INTO WEEKLY_REPORT_DETAILS_LOG 
SELECT *, GETDATE() FROM WEEKLY_REPORT_DETAILS 

TRUNCATE TABLE WEEKLY_REPORT_DETAILS 

INSERT INTO WEEKLY_REPORT_DETAILS 
SELECT * , GETDATE(), @REPORT_DATE, @REPORT_DATE_TO FROM #WEEKLY_REPORT_DETAILS 

DROP TABLE #LEDGER 
DROP TABLE #REPORT_DATA 
DROP TABLE #WEEKLY_REPORT_DETAILS 
DROP TABLE #CL_LIST 

SELECT 'SOF PROCESS COMPLITED FOR THE PERIOD OF '+ UPPER(@REPORT_DATE) + ' TO '+UPPER(@REPORT_DATE_TO)

GO
