-- Object: PROCEDURE dbo.CLS_DPC_COMPUTATION_WRAPPER
-- Server: 10.253.33.91 | DB: ACCOUNT
--------------------------------------------------





CREATE PROCEDURE [dbo].[CLS_DPC_COMPUTATION_WRAPPER]
(
	@FDATE VARCHAR(11)
	,@TDATE VARCHAR(11)
	,@FCODE VARCHAR(10)
	,@TCODE VARCHAR(10)
	,@BRANCH_CD VARCHAR(MAX) ='ALL'
)
AS
/*
DELETE FROM CLS_DPC_CALCULATED WHERE DPC_DATE BETWEEN 'DEC  1 2015' AND 'DEC 31 2015' AND CLTCODE BETWEEN '000' AND 'ZZZZ'
dbcc shrinkfile(2,0)
EXEC [CLS_DPC_COMPUTATION_WRAPPER] 'APR  1 2016','APR 30 2016','p137','p137','ALL' --9.45
XKA5802
E330410

EXEC BOUATSVR2.ACCOUNT..CLS_DPC_COMPUTATION 'AUG  1 2015','AUG 31 2015','A00','AZZZZ','NSE','CAPITAL','( PSPANMARGIN)|( MTOM)|( NONSPREADMARGIN)|(PSPANMARGIN + MTOM+ NONSPREADMARGIN)|(0)','2|  |V  |C|0^3|  |E  |D|0^15|01|V  |C|0^15|01|V  |D|0' 
EXEC CLS_CLIENTPROFILE_DATA 'A0000','AZZZZ','juL 31 2015','NSE','FUTURES'
EXEC CLS_CLIENTPROFILE_DATA 'GAIM3389','GAIM3389','jun 30 2015','NSE','CAPITAL' 
SELECT * FROM CLS_DPC_STAGING
SELECT * FROM DPC_CALCULATED
*/
BEGIN
	--SELECT EXCHANGE,SEGMENT,* FROM PRADNYA..MULTICOMPANY WHERE PRIMARYSERVER = 1

	TRUNCATE table CLS_DPC_STAGING
	--DELETE FROM CLS_DPC_CALCULATED WHERE POSTED_FLAG = 0 AND DPC_DATE BETWEEN @FDATE AND @TDATE AND CLTCODE BETWEEN @FCODE AND @TCODE
	--DELETE FROM CLS_DPC_CALCULATED WHERE DPC_DATE BETWEEN @FDATE AND @TDATE AND CLTCODE BETWEEN @FCODE AND @TCODE
	IF @BRANCH_CD ='ALL'
	BEGIN
		DELETE CLS_DPC_CALCULATED WHERE DPC_DATE BETWEEN @FDATE AND @TDATE AND CLTCODE BETWEEN @FCODE AND @TCODE --AND EXCHANGE = 'NSE' AND SEGMENT = 'CAPITAL'
	END
	ELSE
	BEGIN
		DELETE CLS_DPC_CALCULATED WHERE DPC_DATE BETWEEN @FDATE AND @TDATE AND CLTCODE BETWEEN @FCODE AND @TCODE AND BRANCH_CD IN (SELECT ITEMS FROM .DBO.CLS_SPLIT(@BRANCH_CD,'|'))  --AND EXCHANGE = 'NSE' AND SEGMENT = 'CAPITAL'
	END
--	and BRANCH_CD not in ('MOSTINVEST','RETAILNAT')
	

	if @@rowcount >0 
	print 'Recalculating.............'
	
	/*IF(SELECT 1 WHERE (SELECT MAX(DPC_DATE) FROM CLS_DPC_CALUCATED WHERE POSTED_FLAG = 0) BETWEEN @FDATE AND @TDATE) = 1
	BEGIN
		SELECT 'Entries has been already posted.'
		return
	END*/
SELECT * INTO #TEMP_EXCH_SEG FROM (
	SELECT  
		EXCHANGE
		,SEGMENT
		,ACCOUNTDB
		,ACCOUNTSERVER 
	 FROM PRADNYA..MULTICOMPANY WHERE PRIMARYSERVER = 1 AND EXCHANGE + '-' + SEGMENT IN 
	('NSE-CAPITAL','NSE-FUTURES','BSE-CAPITAL','NSX-FUTURES','MCD-FUTURES','NCX-FUTURES','MCX-FUTURES')
	--('NSE-FUTURES','NSX-FUTURES')
	--('NSE-CAPITAL', 'NSE-FUTURES','NSX-FUTURES','BSX-FUTURES')
	/*UNION ALL
	SELECT  
		EXCHANGE
		,SEGMENT
		,ACCOUNTDB
		,ACCOUNTSERVER = '['+SHAREIP+']'
	 FROM [192.168.99.163].PRADNYA.DBO.MULTICOMPANY WHERE PRIMARYSERVER = 1 AND EXCHANGE + '-' + SEGMENT IN 
	 ('NCX-FUTURES','MCX-FUTURES')*/
) A

CREATE TABLE #V2_CLIENT_DETAILS     
(        
 PARTY_CODE VARCHAR(10) NOT NULL,          
 LONG_NAME VARCHAR(100),         
 AREA VARCHAR(25) NOT NULL,          
 REGION VARCHAR(25) NOT NULL,          
 BRANCH_CD VARCHAR(20) NOT NULL,           
 SUB_BROKER VARCHAR(25) NOT NULL,           
 TRADER VARCHAR(25) NOT NULL,          
 CL_TYPE VARCHAR(10) NOT NULL,          
 C_GROUP  VARCHAR(10) NOT NULL,        
 INACTIVE_FROM DATETIME       


)  

TRUNCATE TABLE CLS_DPC_CALCULATED_TEMP

TRUNCATE TABLE DPC_V2_TBL_COLLATERAL_MARGIN_ALL_DATA

DECLARE
	@FR_CALENDER_DATE1 VARCHAR(11)

SELECT @FR_CALENDER_DATE1 = CONVERT(VARCHAR(11), DATEADD(D, -5, @FDATE), 109)
			
INSERT INTO DPC_V2_TBL_COLLATERAL_MARGIN_ALL_DATA
SELECT 
	PARTY_CODE, Trans_Date, CASH_NCASH = 'C', CASH, EXCHANGE, SEGMENT 
FROM 
	MSAJAG..Collateral 
WHERE 
	Trans_Date BETWEEN @FR_CALENDER_DATE1 AND @TDATE AND PARTY_CODE >= @FCODE AND PARTY_CODE <= @TCODE
union all
SELECT 
	PARTY_CODE, Trans_Date, CASH_NCASH = 'N', NONCASH, EXCHANGE, SEGMENT 
FROM 
	MSAJAG..Collateral 
WHERE 
	Trans_Date BETWEEN @FR_CALENDER_DATE1 AND @TDATE AND PARTY_CODE >= @FCODE AND PARTY_CODE <= @TCODE



--ALTER TABLE [dbo].[#V2_CLIENT_DETAILS] ADD  CONSTRAINT [PK_CLTA134] PRIMARY KEY CLUSTERED 
--(
--	[PARTY_CODE] ASC
--) 
        
--SELECT BRANCH = ITEMS INTO #TEMP_BRANCHES FROM .DBO.CLS_SPLIT('RRANCHEAD|RNETWORK|PXDINESHKV|RETAILSLM|RETAILMLD|RETAILJOD|RETAILGUH|RNIDHIGUPT|RCHOUDHRYS|RGANDHIINV|RETAILRANC|RRANCASANS|RRANCDHANB|RRANCDURGA|RRANCHO|RRANCKOLKA|RRANCPATNA|RRANCRANIG|RRANCTATA','|')
	SELECT BRANCH = ITEMS INTO #TEMP_BRANCHES FROM .DBO.CLS_SPLIT(@BRANCH_CD,'|')
--SELECT BRANCH = BRANCH_CODE INTO #TEMP_BRANCHES FROM MSAJAG.DBO.BRANCH 
--where  
	--((@FCODE = @TCODE AND branch_code = (SELECT BRANCH_CD FROM MSAJAG..CLIENT_DETAILS WHERE CL_CODE = @FCODE)) 
    --OR (@FCODE <> @TCODE))
DECLARE DPC_BRANCHWIESE CURSOR FOR 
SELECT BRANCH FROM #TEMP_BRANCHES
 DECLARE @@BRANCH VARCHAR(30)
 OPEN DPC_BRANCHWIESE 	
	FETCH NEXT FROM DPC_BRANCHWIESE  INTO @@BRANCH
	WHILE @@FETCH_STATUS = 0
		BEGIN
			TRUNCATE TABLE #V2_CLIENT_DETAILS

			INSERT INTO #V2_CLIENT_DETAILS          
			SELECT PARTY_CODE, LONG_NAME = LONG_NAME, AREA, REGION, BRANCH_CD, SUB_BROKER, TRADER, CL_TYPE,         
			C_GROUP, INACTIVE_FROM         
			FROM MSAJAG.DBO.CLIENT_DETAILS CD, (SELECT CL_CODE, INACTIVE_FROM = MAX(INACTIVE_FROM) FROM MSAJAG..CLIENT_BROK_DETAILS WHERE INACTIVE_FROM >= @FDATE GROUP BY CL_CODE) B       
			WHERE       
			CD.PARTY_CODE = B.CL_CODE
			AND CD.PARTY_CODE >= @FCODE AND CD.PARTY_CODE <= @TCODE  
			AND CD.BRANCH_CD = CASE WHEN @BRANCH_CD='ALL' THEN CD.BRANCH_CD ELSE @@BRANCH END
			
			DECLARE DPC_CURSOR CURSOR FOR SELECT * FROM #TEMP_EXCH_SEG
			
			 DECLARE @@EXCHANGE VARCHAR(3),@@SEGMENT VARCHAR(25),@@ACCOUNTDB VARCHAR(20),@@ACCOUNTSERVER VARCHAR(20), @@SQL VARCHAR(8000)
			,@SPAN_FORMULA VARCHAR(100)
			,@EXPOSURE_FORMULA VARCHAR(100)
			,@SPECIAL_FORMULA VARCHAR(100)
			,@ALL_FORMULA VARCHAR(100)
			,@NA_FORMULA VARCHAR(100)
			,@FORMULAS VARCHAR(MAX) 
			,@VTYPESETINGS VARCHAR(8000)
			SET @VTYPESETINGS  = (SELECT      
			STUFF(      
			(      
			SELECT '^'+VTYPE+'|'+BOOKTYPE+'|'+TYPE+'|'+DRCR+'|'+CONVERT(VARCHAR,EXCLUSION_FLAG)
			FROM DPC_VTYPE_SETTINGS
			FOR XML PATH('')      
			),1,1,''))

			SET @FORMULAS  = ''
			
			OPEN DPC_CURSOR 	
			FETCH NEXT FROM DPC_CURSOR  INTO @@EXCHANGE,@@SEGMENT,@@ACCOUNTDB, @@ACCOUNTSERVER
			WHILE @@FETCH_STATUS = 0
				BEGIN
					IF  @@SEGMENT = 'FUTURES'
					BEGIN
						SELECT @SPAN_FORMULA = FORMULA FROM CLS_TBL_DPCMARGIN_FORMULA WHERE EXCHANGE = @@EXCHANGE AND SEGMENT = @@SEGMENT AND MARGINFOR ='SPAN'
						SELECT @EXPOSURE_FORMULA = FORMULA FROM CLS_TBL_DPCMARGIN_FORMULA WHERE EXCHANGE = @@EXCHANGE AND SEGMENT = @@SEGMENT AND MARGINFOR ='EXPOSURE'
						SELECT @SPECIAL_FORMULA = FORMULA FROM CLS_TBL_DPCMARGIN_FORMULA WHERE EXCHANGE = @@EXCHANGE AND SEGMENT = @@SEGMENT AND MARGINFOR ='SPECIAL'
						SELECT @ALL_FORMULA = FORMULA FROM CLS_TBL_DPCMARGIN_FORMULA WHERE EXCHANGE = @@EXCHANGE AND SEGMENT = @@SEGMENT AND MARGINFOR ='ALL'
						SELECT @NA_FORMULA = FORMULA FROM CLS_TBL_DPCMARGIN_FORMULA WHERE EXCHANGE = @@EXCHANGE AND SEGMENT = @@SEGMENT AND MARGINFOR ='NA'
						SET @FORMULAS  = '('+@SPAN_FORMULA+ ')|(' + @EXPOSURE_FORMULA+ ')|(' + @SPECIAL_FORMULA + ')|(' +@ALL_FORMULA + ')|(' + @NA_FORMULA+')'
					END
					PRINT @@SEGMENT + @@EXCHANGE
					SET @@SQL = " "
						/*IF(@@SERVERNAME <> REPLACE(REPLACE(@@ACCOUNTSERVER,'[',''),']',''))
						BEGIN
							SET @@SQL = "DELETE FROM "+ @@ACCOUNTSERVER + '.' + @@ACCOUNTDB +".DBO.CLS_CLIENTPROFILE_DPC_TEMP  "
							--SET @@SQL = @@SQL + " INSERT INTO "+ @@ACCOUNTSERVER + '.' + @@ACCOUNTDB +".dbo.CLS_CLIENTPROFILE_DPC_TEMP "
						END
						ELSE 
						BEGIN
							SET @@SQL = "DELETE FROM "+ @@ACCOUNTDB +".DBO.CLS_CLIENTPROFILE_DPC_TEMP  "
							--SET @@SQL = @@SQL + " INSERT INTO "+ @@ACCOUNTDB +".dbo.CLS_CLIENTPROFILE_DPC_TEMP "
					
						END
						SET @@SQL = @@SQL + " EXEC CLS_CLIENTPROFILE_DATA '"+@FCODE+"','"+@TCODE+"','"+@TDATE+"','"+@@EXCHANGE+"','"+@@SEGMENT+"','"+@@BRANCH+"' "
						print(@@SQL)
						EXEC (@@SQL)*/ 

						IF(@@SERVERNAME <> REPLACE(REPLACE(@@ACCOUNTSERVER,'[',''),']',''))
						BEGIN
							--SET @@SQL = "DELETE FROM "+ @@ACCOUNTSERVER + '.' + @@ACCOUNTDB +".DBO.VW_V2_TBL_COLLATERAL_MARGIN_ALL_DATA  "
							SET @@SQL = " INSERT INTO "+ @@ACCOUNTSERVER + '.' + @@ACCOUNTDB +".dbo.VW_V2_TBL_COLLATERAL_MARGIN_ALL_DATA "
						END
						ELSE 
						BEGIN
							--SET @@SQL = "DELETE FROM "+ @@ACCOUNTDB +".DBO.VW_V2_TBL_COLLATERAL_MARGIN_ALL_DATA  "
							SET @@SQL = " INSERT INTO "+ @@ACCOUNTDB +".dbo.VW_V2_TBL_COLLATERAL_MARGIN_ALL_DATA "
					
						END
						SET @@SQL = @@SQL + " SELECT PARTY_CODE, EFFDATE, CASH_COLL, NONCASH_COLL, EXCHANGE, SEGMENT FROM DPC_V2_TBL_COLLATERAL_MARGIN_ALL_DATA WHERE EXCHANGE = '" + @@EXCHANGE + "' AND SEGMENT = '" + @@SEGMENT + "' AND EFFDATE BETWEEN '" + @FR_CALENDER_DATE1 + "' AND '" + @TDATE + "' AND PARTY_CODE >='" + @FCODE + "' AND PARTY_CODE <= '" + @TCODE + "'"
						print(@@SQL)
						EXEC (@@SQL) 

						IF @@EXCHANGE ='NCX' OR @@EXCHANGE = 'MCX'
						BEGIN
							DECLARE 
							@BACKDATE VARCHAR(11)
							,@LEDGER_FDATE VARCHAR(11)
							,@TODATE VARCHAR(11)
							SELECT @LEDGER_FDATE = CONVERT(VARCHAR(11), SDTCUR, 109) FROM PARAMETER WHERE @TDATE BETWEEN SDTCUR AND LDTCUR
							SET @BACKDATE = (SELECT DATEADD(DAY,-15,CONVERT(DATETIME,@LEDGER_FDATE,103)))
							SET @TODATE =CONVERT(VARCHAR(11),CONVERT(DATETIME,@TDATE,103),109)
							
							SET @@SQL =  "INSERT INTO  " + @@ACCOUNTSERVER +".MSAJAG.DBO.TEMP_SETT_MST "
							SET @@SQL = @@SQL + " SELECT * FROM MSAJAG.dbo.SETT_MST WHERE SETT_TYPE = 'N' AND START_DATE>= '"+@BACKDATE+"' AND START_DATE <= DATEADD(D, 10, '"+@TODATE+" 23:59') "
							SET @@SQL = @@SQL + " ORDER BY START_DATE ASC "
							PRINT @@SQL
							--EXEC (@@SQL)
						END
						-- SETT_MST
						
						SET @@SQL = " "
						IF(@@SERVERNAME <> REPLACE(REPLACE(@@ACCOUNTSERVER,'[',''),']',''))
						BEGIN
							SELECT @@ACCOUNTSERVER, @@ACCOUNTDB, @FDATE, @TDATE, @FCODE, @TCODE, @@EXCHANGE, @@SEGMENT, @FORMULAS , @VTYPESETINGS
							SET @@SQL = " INSERT INTO CLS_DPC_STAGING "
							
							SET @@SQL = @@SQL + " EXEC " + @@ACCOUNTSERVER + '.' + @@ACCOUNTDB + "..CLS_DPC_COMPUTATION '"+@FDATE+"','"+@TDATE+"','"+@FCODE+"','"+@TCODE+"','"+@@EXCHANGE+"','"+@@SEGMENT+"','"+ @FORMULAS +"','"+@VTYPESETINGS+"' "
						END
						ELSE
						BEGIN
							SET @@SQL = " INSERT INTO CLS_DPC_STAGING "
							
							SET @@SQL = @@SQL + " EXEC CLS_DPC_COMPUTATION '"+@FDATE+"','"+@TDATE+"','"+@FCODE+"','"+@TCODE+"','"+@@EXCHANGE+"','"+@@SEGMENT+"','"+ @FORMULAS +"','"+@VTYPESETINGS+"' "
						END
							print @@SQL
							--SELECT @FDATE,@TDATE,@FCODE,@TCODE,@@EXCHANGE,@@SEGMENT,@FORMULAS,@VTYPESETINGS
						EXEC (@@SQL) 
					FETCH NEXT FROM DPC_CURSOR  INTO @@EXCHANGE,@@SEGMENT,@@ACCOUNTDB, @@ACCOUNTSERVER
				END
			CLOSE DPC_CURSOR 	
			DEALLOCATE DPC_CURSOR
			INSERT INTO CLS_DPC_CALCULATED_TEMP(
				LONG_NAME
				,CLTCODE
				,DPC_DATE
				,SETTLEMENT_DATE
				,DPC_BALANCE
				,LEDGER_BALANCE 
				,CASH_COLLATREAL
				,NONCASH_COLLATREAL
				,MARGIN_REQ
				,BRANCH_CD
				,SUB_BROKER
				,TRADER
				,REGION
				,AREA
				,CL_TYPE
				,PROFILE_SRNO
				,CREDIT_INT
				,DEBIT_INT
				,FROMDATE
				,TODATE
				,EXEMPT_NOOFDAYS
				,EXEMPT_NOOFDAYS_CR
				,MIN_INTEREST
				,MIN_BALANCE
				,EXCHANGE
				,SEGMENT
				,INACTIVE
				,MARGIN_EXP_FLAG
				,COLL_FLAG
				,COLL_VALUE
				,CREATED_DATE
				,CREATED_BY
				,REVISED_AMT
				,REVISED_PERC
			)
			SELECT 
				LONG_NAME
				,CLTCODE
				,DPC_DATE = SETTLEMENT_DATE
				,SETTLEMENT_DATE
				,DPC_BALANCE =  SUM(LEDGER_BALANCE) --(SUM(LEDGER_BALANCE) + sum(CASE WHEN SEGMENT ='CAPITAL' THEN CASH_COLLATREAL ELSE 0 END)) - (CASE WHEN (SUM(MARGIN_REQ) - SUM(NONCASH_COLLATREAL) - sum(CASE WHEN SEGMENT <> 'CAPITAL' THEN CASH_COLLATREAL ELSE 0 END)) >  0 THEN (SUM(MARGIN_REQ) - SUM(NONCASH_COLLATREAL)- sum(CASE WHEN SEGMENT <> 'CAPITAL' THEN CASH_COLLATREAL ELSE 0 END)) ELSE 0 END)
				,LEDGER_BALANCE = SUM(LEDGER_BALANCE)
				,CASH_COLLATREAL= SUM(CASH_COLLATREAL)
				,NONCASH_COLLATREAL= SUM(NONCASH_COLLATREAL) --(CASE WHEN (SUM(MARGIN_REQ) * COLL_VALUE/100) < SUM(NONCASH_COLLATREAL) THEN (SUM(MARGIN_REQ) * COLL_VALUE/100)  ELSE SUM(NONCASH_COLLATREAL) end)
				,MARGIN_REQ= SUM(MARGIN_REQ)
				,BRANCH_CD
				,SUB_BROKER
				,TRADER
				,REGION
				,AREA
				,CL_TYPE
				,PROFILE_SRNO = max(PROFILE_SRNO)
				,CREDIT_INT = max(CREDIT_INT)
				,DEBIT_INT = max(DEBIT_INT)
				,FROMDATE = max(FROMDATE)
				,TODATE = max(TODATE)
				,EXEMPT_NOOFDAYS = max(EXEMPT_NOOFDAYS)
				,EXEMPT_NOOFDAYS_CR = max(EXEMPT_NOOFDAYS_CR)
				,MIN_INTEREST = max(MIN_INTEREST)
				,MIN_BALANCE = max(MIN_BALANCE)
				,EXCHANGE = EXCHANGE
				,SEGMENT = SEGMENT
				,INACTIVE = max(INACTIVE)
				,MARGIN_EXP_FLAG = max(MARGIN_EXP_FLAG)
				,COLL_FLAG = max(COLL_FLAG)
				,COLL_VALUE = MAX(COLL_VALUE)
				,CREATED_DATE = GETDATE()
				,CREATED_BY = ''
				,REVISED_AMT = MAX(REVISED_AMT)
				,REVISED_PERC = MAX(REVISED_PERC)

			FROM 
				CLS_DPC_STAGING
			GROUP
			BY
				LONG_NAME
				,CLTCODE
				--,DPC_DATE
				,SETTLEMENT_DATE
				,BRANCH_CD
				,SUB_BROKER
				,TRADER
				,REGION
				,AREA
				,CL_TYPE
				,EXCHANGE
				,SEGMENT
				,COLL_VALUE
				/*,PROFILE_SRNO
				,CREDIT_INT
				,DEBIT_INT
				,FROMDATE
				,TODATE
				,EXEMPT_NOOFDAYS
				,EXEMPT_NOOFDAYS_CR
				,MIN_INTEREST
				,MIN_BALANCE
				,EXCHANGE
				,SEGMENT
				,INACTIVE
				,MARGIN_EXP_FLAG
				,COLL_FLAG*/
			ORDER BY
				EXCHANGE
				,SEGMENT 
				,LONG_NAME
				,CLTCODE
			--,DPC_DATE

		TRUNCATE table CLS_DPC_STAGING

		FETCH NEXT FROM DPC_BRANCHWIESE  INTO @@BRANCH
	END
	CLOSE DPC_BRANCHWIESE 	
	DEALLOCATE DPC_BRANCHWIESE

	

	
	--SELECT * FROM CLS_DPC_CALUCATED 
DROP TABLE #TEMP_EXCH_SEG
DROP TABLE #TEMP_BRANCHES

--ALTER TABLE [dbo].[#V2_CLIENT_DETAILS] DROP CONSTRAINT [PK_CLTA124]


DROP TABLE #V2_CLIENT_DETAILS

INSERT INTO CLS_DPC_CALCULATED(
				LONG_NAME
				,CLTCODE
				,DPC_DATE
				,SETTLEMENT_DATE
				,DPC_BALANCE
				,LEDGER_BALANCE 
				,CASH_COLLATREAL
				,NONCASH_COLLATREAL
				,ACTUAL_NONCASH_COLLATREAL
				,MARGIN_REQ
				,BRANCH_CD
				,SUB_BROKER
				,TRADER
				,REGION
				,AREA
				,CL_TYPE
				,PROFILE_SRNO
				,CREDIT_INT
				,DEBIT_INT
				,FROMDATE
				,TODATE
				,EXEMPT_NOOFDAYS
				,EXEMPT_NOOFDAYS_CR
				,MIN_INTEREST
				,MIN_BALANCE
				,EXCHANGE
				,SEGMENT
				,INACTIVE
				,MARGIN_EXP_FLAG
				,COLL_FLAG
				,CREATED_DATE
				,CREATED_BY
				,REVISED_AMT
				,REVISED_PERC
			)
SELECT
	LONG_NAME
	,CLTCODE
	,DPC_DATE
	,SETTLEMENT_DATE
	--,DPC_BALANCE =  (SUM(LEDGER_BALANCE) + sum(CASE WHEN SEGMENT ='CAPITAL' THEN CASH_COLLATREAL ELSE 0 END)) - (CASE WHEN (SUM(MARGIN_REQ) - (CASE WHEN (SUM(MARGIN_REQ) * MAX(COLL_VALUE)/100) < SUM(NONCASH_COLLATREAL) THEN (SUM(MARGIN_REQ) * MAX(COLL_VALUE)/100)  ELSE SUM(NONCASH_COLLATREAL) end) + sum(CASE WHEN SEGMENT <> 'CAPITAL' THEN CASH_COLLATREAL ELSE 0 END)) >  0 THEN (SUM(MARGIN_REQ) - (CASE WHEN (SUM(MARGIN_REQ) * MAX(COLL_VALUE)/100) < SUM(NONCASH_COLLATREAL) THEN (SUM(MARGIN_REQ) * MAX(COLL_VALUE)/100)  ELSE SUM(NONCASH_COLLATREAL) end) - sum(CASE WHEN SEGMENT <> 'CAPITAL' THEN CASH_COLLATREAL ELSE 0 END)) ELSE 0 END)
	,DPC_BALANCE = SUM(LEDGER_BALANCE) + SUM(CASH_COLLATREAL) -
					CASE WHEN SUM(MARGIN_REQ) > 
					CASE WHEN SUM(NONCASH_COLLATREAL) > (SUM(MARGIN_REQ) * MAX(COLL_VALUE)/100) THEN (SUM(MARGIN_REQ) * MAX(COLL_VALUE)/100) ELSE SUM(NONCASH_COLLATREAL) END
					THEN SUM(MARGIN_REQ) - 
					CASE WHEN SUM(NONCASH_COLLATREAL) > (SUM(MARGIN_REQ) * MAX(COLL_VALUE)/100) THEN (SUM(MARGIN_REQ) * MAX(COLL_VALUE)/100) ELSE SUM(NONCASH_COLLATREAL) END ELSE 0 END
	,LEDGER_BALANCE = SUM(LEDGER_BALANCE)
	,CASH_COLLATREAL= SUM(CASH_COLLATREAL)
	,NONCASH_COLLATREAL= (CASE WHEN (SUM(MARGIN_REQ) * MAX(COLL_VALUE)/100) < SUM(NONCASH_COLLATREAL) THEN (SUM(MARGIN_REQ) * MAX(COLL_VALUE)/100)  ELSE SUM(NONCASH_COLLATREAL) end)
	,ACTUAL_NONCASH_COLLATREAL= sum(NONCASH_COLLATREAL)
	,MARGIN_REQ= SUM(MARGIN_REQ)
	,BRANCH_CD
	,SUB_BROKER
	,TRADER
	,REGION
	,AREA
	,CL_TYPE
	,PROFILE_SRNO 
	,CREDIT_INT 
	,DEBIT_INT 
	,FROMDATE = max(FROMDATE)
	,TODATE = max(TODATE)
	,EXEMPT_NOOFDAYS = max(EXEMPT_NOOFDAYS)
	,EXEMPT_NOOFDAYS_CR = max(EXEMPT_NOOFDAYS_CR)
	,MIN_INTEREST = max(MIN_INTEREST)
	,MIN_BALANCE = max(MIN_BALANCE)
	,EXCHANGE = EXCHANGE
	,SEGMENT = SEGMENT
	,INACTIVE = max(INACTIVE)
	,MARGIN_EXP_FLAG = max(MARGIN_EXP_FLAG)
	,COLL_FLAG = max(COLL_FLAG)
	,CREATED_DATE = GETDATE()
	,CREATED_BY = ''
	,REVISED_AMT = max(REVISED_AMT)
	,REVISED_PERC = max(REVISED_PERC)
FROM
	CLS_DPC_CALCULATED_TEMP
--WHERE  EXCHANGE = 'NSE' AND SEGMENT = 'CAPITAL'
GROUP
			BY
				LONG_NAME
				,CLTCODE
				,DPC_DATE
				,SETTLEMENT_DATE
				,BRANCH_CD
				,SUB_BROKER
				,TRADER
				,REGION
				,AREA
				,CL_TYPE
				,EXCHANGE
				,SEGMENT
				,PROFILE_SRNO
				,CREDIT_INT
				,DEBIT_INT
				/*,FROMDATE
				,TODATE
				,EXEMPT_NOOFDAYS
				,EXEMPT_NOOFDAYS_CR
				,MIN_INTEREST
				,MIN_BALANCE
				,EXCHANGE
				,SEGMENT
				,INACTIVE
				,MARGIN_EXP_FLAG
				,COLL_FLAG*/
			ORDER BY
				EXCHANGE
				,SEGMENT 
				,LONG_NAME
				,CLTCODE
				

--TRUNCATE TABLE CLS_DPC_CALCULATED_TEMP

	
END

GO
