-- Object: PROCEDURE dbo.V2_OFFLINE_UPLOAD_PUTLOG
-- Server: 10.253.33.91 | DB: ACCOUNT
--------------------------------------------------

    
    
CREATE PROC [dbo].[V2_OFFLINE_UPLOAD_PUTLOG]    
(    
 @P_EXCHANGE VARCHAR(3),    
 @P_SEGMENT VARCHAR(10),    
 @P_VOUCHERTYPE SMALLINT,    
 @P_ERRORCODE INT,    
 @P_ERRORMSG VARCHAR(255),    
 @P_UPDATEBY VARCHAR(25)    
)    
AS    
  
BEGIN DISTRIBUTED TRANSACTION   
  
INSERT INTO AngelBSECM.ACCOUNT_AB.DBO.OFFLINE_UPLOAD_LOG    
(    
 OUL_EXCHANGE,    
 OUL_SEGMENT,    
 OUL_VOUCHERTYPE,    
 OUL_ERRORCODE,    
 OUL_ERRORMSG ,    
 OUL_UPDATEBY,    
 OUL_UPDATEDT    
)    
VALUES    
(    
 @P_EXCHANGE,    
 @P_SEGMENT,    
 @P_VOUCHERTYPE,    
 @P_ERRORCODE,    
 @P_ERRORMSG,    
 @P_UPDATEBY,    
 GETDATE()    
)  
  
COMMIT TRANSACTION

GO
