-- Object: PROCEDURE dbo.SFCM_PROVISIONAL_10082021
-- Server: 10.253.33.91 | DB: ACCOUNT
--------------------------------------------------


  
CREATE PROC [DBO].[SFCM_PROVISIONAL]  (@TODATE  DATETIME)AS            

--- EXEC SFCM_PROVISIONAL 'JUN 11 2021'

BEGIN       

DECLARE @FROMDATE DATETIME          
SELECT @FROMDATE =SDTCUR FROM PARAMETER WHERE @TODATE BETWEEN SDTCUR AND LDTCUR
         
SELECT CLTCODE,NETAMT=SUM(CASE WHEN DRCR='D' THEN -VAMT ELSE VAMT END) INTO #EDTLED     --- NSECM            
FROM LEDGER WHERE VDT >=@FROMDATE AND EDT <=@TODATE  + ' 23:59'        
GROUP BY CLTCODE            

INSERT INTO #EDTLED  --- BSECM
SELECT CLTCODE,NETAMT=SUM(CASE WHEN DRCR='D' THEN -VAMT ELSE VAMT END)                  
FROM ANAND.ACCOUNT_AB.DBO.LEDGER WHERE VDT >=@FROMDATE AND EDT <=@TODATE  + ' 23:59'        
GROUP BY CLTCODE

INSERT INTO #EDTLED  --- NSEFO
SELECT CLTCODE,NETAMT=SUM(CASE WHEN DRCR='D' THEN -VAMT ELSE VAMT END)                  
FROM ANGELFO.ACCOUNTFO.DBO.LEDGER WHERE VDT >=@FROMDATE AND EDT <=@TODATE  + ' 23:59'        
GROUP BY CLTCODE

INSERT INTO #EDTLED  --- BSEFO
SELECT CLTCODE,NETAMT=SUM(CASE WHEN DRCR='D' THEN -VAMT ELSE VAMT END)                  
FROM ANGELCOMMODITY.ACCOUNTBFO.DBO.LEDGER WHERE VDT >=@FROMDATE AND EDT <=@TODATE  + ' 23:59'        
GROUP BY CLTCODE

INSERT INTO #EDTLED  --- NSECD
SELECT CLTCODE,NETAMT=SUM(CASE WHEN DRCR='D' THEN -VAMT ELSE VAMT END)                  
FROM ANGELFO.ACCOUNTCURFO.DBO.LEDGER WHERE VDT >=@FROMDATE AND EDT <=@TODATE  + ' 23:59'        
GROUP BY CLTCODE        

INSERT INTO #EDTLED  --- BSECD
SELECT CLTCODE,NETAMT=SUM(CASE WHEN DRCR='D' THEN -VAMT ELSE VAMT END)                  
FROM ANGELCOMMODITY.ACCOUNTCURBFO.DBO.LEDGER WHERE VDT >=@FROMDATE AND EDT <=@TODATE  + ' 23:59'        
GROUP BY CLTCODE
            
INSERT INTO #EDTLED  --- MCXCD
SELECT CLTCODE,NETAMT=SUM(CASE WHEN DRCR='D' THEN -VAMT ELSE VAMT END)                  
FROM ANGELCOMMODITY.ACCOUNTMCDXCDS.DBO.LEDGER WHERE VDT >=@FROMDATE AND EDT <=@TODATE  + ' 23:59'        
GROUP BY CLTCODE         
               
INSERT INTO #EDTLED  --- MTF
SELECT CLTCODE,NETAMT=SUM(CASE WHEN DRCR='D' THEN -VAMT ELSE VAMT END)                  
FROM MTFTRADE.DBO.LEDGER WHERE VDT >=@FROMDATE AND EDT <=@TODATE  + ' 23:59'        
GROUP BY CLTCODE  

INSERT INTO #EDTLED  --- SLBS
SELECT CLTCODE,NETAMT=SUM(CASE WHEN DRCR='D' THEN -VAMT ELSE VAMT END)                  
FROM ACCOUNTSLBS.DBO.LEDGER WHERE VDT >=@FROMDATE AND EDT <=@TODATE  + ' 23:59'        
GROUP BY CLTCODE   
         
INSERT INTO #EDTLED  --- MCDX
SELECT CLTCODE,NETAMT=SUM(CASE WHEN DRCR='D' THEN -VAMT ELSE VAMT END)                  
FROM ANGELCOMMODITY.ACCOUNTMCDX.DBO.LEDGER WHERE VDT >=@FROMDATE AND EDT <=@TODATE  + ' 23:59'        
GROUP BY CLTCODE

INSERT INTO #EDTLED  --- NCDX
SELECT CLTCODE,NETAMT=SUM(CASE WHEN DRCR='D' THEN -VAMT ELSE VAMT END)                  
FROM ANGELCOMMODITY.ACCOUNTNCDX.DBO.LEDGER WHERE VDT >=@FROMDATE AND EDT <=@TODATE  + ' 23:59'        
GROUP BY CLTCODE


/* ONLINE ENTY RECO LOGIC FOR RECEPIT AND PAYMENTS ENTRIES */


SELECT CLTCODE,SUM(CASE WHEN DRCR ='D' THEN -VAMT ELSE VAMT END) AS BALANCE INTO #TDAY_UNRECO --- NSECM
FROM ACCOUNT.DBO.LEDGER WITH (NOLOCK) WHERE VTYP='2' AND VDT >= @FROMDATE AND EDT='2049-12-31 00:00:00.000' 
AND ENTEREDBY IN ('B_TPR' ,'TPR') GROUP BY CLTCODE
UNION ALL
SELECT CLTCODE,SUM(CASE WHEN DRCR ='C' THEN -VAMT ELSE VAMT END) AS BALANCE
FROM ACCOUNT.DBO.LEDGER WITH (NOLOCK) WHERE VTYP='3' AND VDT > =  @FROMDATE AND EDT='2049-12-31 00:00:00.000' 
GROUP BY CLTCODE

INSERT INTO #TDAY_UNRECO --- BSECM
SELECT CLTCODE,SUM(CASE WHEN DRCR ='D' THEN -VAMT ELSE VAMT END) AS BALANCE 
FROM ANAND.ACCOUNT_AB.DBO.LEDGER WITH (NOLOCK) WHERE VTYP='2' AND VDT > = @FROMDATE AND EDT='2049-12-31 00:00:00.000' 
AND ENTEREDBY IN ('B_TPR' ,'TPR') GROUP BY CLTCODE
UNION ALL
SELECT CLTCODE,SUM(CASE WHEN DRCR ='C' THEN -VAMT ELSE VAMT END) AS BALANCE
FROM ANAND.ACCOUNT_AB.DBO.LEDGER WITH (NOLOCK) WHERE VTYP='3' AND VDT > =  @FROMDATE AND EDT='2049-12-31 00:00:00.000' 
GROUP BY CLTCODE

INSERT INTO #TDAY_UNRECO --- NSEFO
SELECT CLTCODE,SUM(CASE WHEN DRCR ='D' THEN -VAMT ELSE VAMT END) AS BALANCE 
FROM ANGELFO.ACCOUNTFO.DBO.LEDGER WITH (NOLOCK) WHERE VTYP='2' AND VDT > = @FROMDATE AND EDT='2049-12-31 00:00:00.000' 
AND ENTEREDBY IN ('B_TPR' ,'TPR') GROUP BY CLTCODE
UNION ALL
SELECT CLTCODE,SUM(CASE WHEN DRCR ='C' THEN -VAMT ELSE VAMT END) AS BALANCE
FROM ANGELFO.ACCOUNTFO.DBO.LEDGER WITH (NOLOCK) WHERE VTYP='3' AND VDT > =  @FROMDATE AND EDT='2049-12-31 00:00:00.000' 
GROUP BY CLTCODE

INSERT INTO #TDAY_UNRECO --- BSEFO
SELECT CLTCODE,SUM(CASE WHEN DRCR ='D' THEN -VAMT ELSE VAMT END) AS BALANCE 
FROM ANGELCOMMODITY.ACCOUNTBFO.DBO.LEDGER WITH (NOLOCK) WHERE VTYP='2' AND VDT > = @FROMDATE AND EDT='2049-12-31 00:00:00.000' 
AND ENTEREDBY IN ('B_TPR' ,'TPR') GROUP BY CLTCODE
UNION ALL
SELECT CLTCODE,SUM(CASE WHEN DRCR ='C' THEN -VAMT ELSE VAMT END) AS BALANCE
FROM ANGELCOMMODITY.ACCOUNTBFO.DBO.LEDGER WITH (NOLOCK) WHERE VTYP='3' AND VDT > =  @FROMDATE AND EDT='2049-12-31 00:00:00.000' 
GROUP BY CLTCODE

INSERT INTO #TDAY_UNRECO --- NSECD
SELECT CLTCODE,SUM(CASE WHEN DRCR ='D' THEN -VAMT ELSE VAMT END) AS BALANCE 
FROM ANGELFO.ACCOUNTCURFO.DBO.LEDGER WITH (NOLOCK) WHERE VTYP='2' AND VDT > = @FROMDATE AND EDT='2049-12-31 00:00:00.000' 
AND ENTEREDBY IN ('B_TPR' ,'TPR') GROUP BY CLTCODE
UNION ALL
SELECT CLTCODE,SUM(CASE WHEN DRCR ='C' THEN -VAMT ELSE VAMT END) AS BALANCE
FROM ANGELFO.ACCOUNTCURFO.DBO.LEDGER WITH (NOLOCK) WHERE VTYP='3' AND VDT > =  @FROMDATE AND EDT='2049-12-31 00:00:00.000' 
GROUP BY CLTCODE

INSERT INTO #TDAY_UNRECO --- BSECD
SELECT CLTCODE,SUM(CASE WHEN DRCR ='D' THEN -VAMT ELSE VAMT END) AS BALANCE 
FROM ANGELCOMMODITY.ACCOUNTCURBFO.DBO.LEDGER WITH (NOLOCK) WHERE VTYP='2' AND VDT > = @FROMDATE AND EDT='2049-12-31 00:00:00.000' 
AND ENTEREDBY IN ('B_TPR' ,'TPR') GROUP BY CLTCODE
UNION ALL
SELECT CLTCODE,SUM(CASE WHEN DRCR ='C' THEN -VAMT ELSE VAMT END) AS BALANCE
FROM ANGELCOMMODITY.ACCOUNTCURBFO.DBO.LEDGER WITH (NOLOCK) WHERE VTYP='3' AND VDT > =  @FROMDATE AND EDT='2049-12-31 00:00:00.000' 
GROUP BY CLTCODE
        
INSERT INTO #TDAY_UNRECO --- MCXCD
SELECT CLTCODE,SUM(CASE WHEN DRCR ='D' THEN -VAMT ELSE VAMT END) AS BALANCE 
FROM ANGELCOMMODITY.ACCOUNTMCDXCDS.DBO.LEDGER WITH (NOLOCK) WHERE VTYP='2' AND VDT > = @FROMDATE AND EDT='2049-12-31 00:00:00.000' 
AND ENTEREDBY IN ('B_TPR' ,'TPR') GROUP BY CLTCODE
UNION ALL
SELECT CLTCODE,SUM(CASE WHEN DRCR ='C' THEN -VAMT ELSE VAMT END) AS BALANCE
FROM ANGELCOMMODITY.ACCOUNTMCDXCDS.DBO.LEDGER WITH (NOLOCK) WHERE VTYP='3' AND VDT > =  @FROMDATE AND EDT='2049-12-31 00:00:00.000' 
GROUP BY CLTCODE        

INSERT INTO #TDAY_UNRECO --- MTF
SELECT CLTCODE,SUM(CASE WHEN DRCR ='D' THEN -VAMT ELSE VAMT END) AS BALANCE 
FROM MTFTRADE.DBO.LEDGER WITH (NOLOCK) WHERE VTYP='2' AND VDT > = @FROMDATE AND EDT='2049-12-31 00:00:00.000' 
AND ENTEREDBY IN ('B_TPR' ,'TPR') GROUP BY CLTCODE
UNION ALL
SELECT CLTCODE,SUM(CASE WHEN DRCR ='C' THEN -VAMT ELSE VAMT END) AS BALANCE
FROM MTFTRADE.DBO.LEDGER WITH (NOLOCK) WHERE VTYP='3' AND VDT > =  @FROMDATE AND EDT='2049-12-31 00:00:00.000' 
GROUP BY CLTCODE
          
INSERT INTO #TDAY_UNRECO --- SLBS
SELECT CLTCODE,SUM(CASE WHEN DRCR ='D' THEN -VAMT ELSE VAMT END) AS BALANCE 
FROM ACCOUNTSLBS.DBO.LEDGER WITH (NOLOCK) WHERE VTYP='2' AND VDT > = @FROMDATE AND EDT='2049-12-31 00:00:00.000' 
AND ENTEREDBY IN ('B_TPR' ,'TPR') GROUP BY CLTCODE
UNION ALL
SELECT CLTCODE,SUM(CASE WHEN DRCR ='C' THEN -VAMT ELSE VAMT END) AS BALANCE
FROM ACCOUNTSLBS.DBO.LEDGER WITH (NOLOCK) WHERE VTYP='3' AND VDT > =  @FROMDATE AND EDT='2049-12-31 00:00:00.000' 
GROUP BY CLTCODE
   
INSERT INTO #TDAY_UNRECO --- MCDX
SELECT CLTCODE,SUM(CASE WHEN DRCR ='D' THEN -VAMT ELSE VAMT END) AS BALANCE 
FROM ANGELCOMMODITY.ACCOUNTMCDX.DBO.LEDGER WITH (NOLOCK) WHERE VTYP='2' AND VDT > = @FROMDATE AND EDT='2049-12-31 00:00:00.000' 
AND ENTEREDBY IN ('B_TPR' ,'TPR') GROUP BY CLTCODE
UNION ALL
SELECT CLTCODE,SUM(CASE WHEN DRCR ='C' THEN -VAMT ELSE VAMT END) AS BALANCE
FROM ANGELCOMMODITY.ACCOUNTMCDX.DBO.LEDGER WITH (NOLOCK) WHERE VTYP='3' AND VDT > =  @FROMDATE AND EDT='2049-12-31 00:00:00.000' 
GROUP BY CLTCODE

INSERT INTO #TDAY_UNRECO --- NCDX
SELECT CLTCODE,SUM(CASE WHEN DRCR ='D' THEN -VAMT ELSE VAMT END) AS BALANCE 
FROM ANGELCOMMODITY.ACCOUNTNCDX.DBO.LEDGER WITH (NOLOCK) WHERE VTYP='2' AND VDT > = @FROMDATE AND EDT='2049-12-31 00:00:00.000' 
AND ENTEREDBY IN ('B_TPR' ,'TPR') GROUP BY CLTCODE
UNION ALL
SELECT CLTCODE,SUM(CASE WHEN DRCR ='C' THEN -VAMT ELSE VAMT END) AS BALANCE
FROM ANGELCOMMODITY.ACCOUNTNCDX.DBO.LEDGER WITH (NOLOCK) WHERE VTYP='3' AND VDT > =  @FROMDATE AND EDT='2049-12-31 00:00:00.000' 
GROUP BY CLTCODE


INSERT INTO #EDTLED        
SELECT * FROM #TDAY_UNRECO        
        
CREATE TABLE #CC (CLTCODE VARCHAR(10), BALANCE MONEY)

INSERT INTO   #CC               
SELECT CLTCODE,SUM(NETAMT) AS BALANCE  FROM #EDTLED A, MSAJAG.DBO.CLIENT_DETAILS M  WITH (NOLOCK)      
WHERE CLTCODE BETWEEN 'A' AND 'ZZZZZZZZZZZZZZZZZ999999999999' AND A.CLTCODE=M.CL_CODE GROUP BY CLTCODE

SELECT CONVERT(VARCHAR,(SUM(BALANCE)/10000000)) +' - CR' AS BALANCE FROM #CC WHERE BALANCE >0  AND CLTCODE NOT LIKE '%ERROR%'          
 UNION ALL          
SELECT CONVERT(VARCHAR,(SUM(BALANCE)/10000000)) +' - DR' AS BALANCE FROM #CC WHERE BALANCE <0   AND CLTCODE NOT LIKE '%ERROR%'         

END

GO
