-- Object: PROCEDURE dbo.FETCH_GST_INVOICE_ACCOUNT_BKUP_10APR2021
-- Server: 10.253.33.91 | DB: ACCOUNT
--------------------------------------------------




CREATE PROC [dbo].[FETCH_GST_INVOICE_ACCOUNT_BKUP_10APR2021]
(
	@FORTHEDAY	VARCHAR(11),
	@EXCHANGE	VARCHAR(3),
	@SEGMENT	VARCHAR(7)
)
AS


SELECT DISTINCT VNO, VTYP, BOOKTYPE, VDT=CONVERT(DATETIME,LEFT(VDT,11)), FLAG = (CASE WHEN DRCR = 'C' THEN 'DEBIT' ELSE 'CREDIT' END)
INTO #GSTLED FROM LEDGER L (Nolock)
WHERE VDT BETWEEN @FORTHEDAY AND @FORTHEDAY + ' 23:59:59'
AND CLTCODE IN (SELECT ACCODE FROM MSAJAG..VALANACCOUNT (Nolock) WHERE ACNAME LIKE '%GST%')
AND VNO IN (SELECT VNO FROM LEDGER G (Nolock)
			WHERE VDT BETWEEN @FORTHEDAY AND @FORTHEDAY + ' 23:59:59'
			AND L.VNO = G.VNO 
			AND L.Vtyp = G.Vtyp
			AND L.Booktype = G.Booktype
			AND EXISTS (SELECT CLTCODE FROM ACMAST A WHERE A.CLTCODE = G.CLTCODE AND ACCAT = 4) )
AND VTYP NOT IN ('15', '21')

SELECT G.VNO, G.VTYP, G.BOOKTYPE, G.VDT, G.FLAG, L.CLTCODE, VAMT, L.NARRATION, ACTYPE=0
INTO #GSTLED_TEMP
FROM LEDGER L (Nolock), #GSTLED G
WHERE L.VDT BETWEEN @FORTHEDAY AND @FORTHEDAY + ' 23:59:59'
		AND L.VNO = G.VNO 
		AND L.Vtyp = G.Vtyp
		AND L.Booktype = G.Booktype

UPDATE #GSTLED_TEMP SET ACTYPE = 2
WHERE EXISTS  (SELECT CLTCODE FROM ACMAST A (Nolock) WHERE A.CLTCODE = #GSTLED_TEMP.CLTCODE AND ACCAT = 4)

UPDATE #GSTLED_TEMP SET ACTYPE = 1
WHERE EXISTS  (SELECT ACCODE FROM MSAJAG..VALANACCOUNT WHERE ACCODE = CLTCODE AND ACNAME LIKE '%GST%')

SELECT G.VNO, G.VTYP, G.BOOKTYPE, G.VDT, G.FLAG, 
CLTCODE = MAX(CASE WHEN ACTYPE = 2 THEN CLTCODE ELSE '' END),
GLCODE = MAX(CASE WHEN ACTYPE = 0 THEN CLTCODE ELSE '' END),
TAXABLE_AMT = SUM(CASE WHEN ACTYPE = 0 THEN VAMT ELSE 0 END),
TAX_AMT = SUM(CASE WHEN ACTYPE = 1 THEN VAMT ELSE 0 END),
Narration = CONVERT(VARCHAR(500),'')
INTO #GSTACCFINAL
FROM #GSTLED_TEMP G
GROUP BY G.VNO, G.VTYP, G.BOOKTYPE, G.VDT, G.FLAG

SELECT      DISTINCT
         G.VNO, G.VTYP, G.BOOKTYPE, G.VDT,

         STUFF(
               (SELECT      ',' + G1.Narration
               FROM      #GSTLED_TEMP AS G1
               WHERE      G1.VNO = G.VNO
			   AND        G1.VTYP = G.VTYP
			   AND        G1.BOOKTYPE = G.BOOKTYPE
			   AND ACTYPE = 2
               FOR XML PATH('')), 1, 1, '') AS Narration
INTO #NARR
FROM      #GSTLED_TEMP G WHERE ACTYPE = 2
ORDER BY   G.VNO, G.VTYP, G.BOOKTYPE, G.VDT 

UPDATE #GSTACCFINAL SET Narration = G.Narration
FROM #NARR G
WHERE #GSTACCFINAL.VNO = G.VNO
AND        #GSTACCFINAL.VTYP = G.VTYP
AND        #GSTACCFINAL.BOOKTYPE = G.BOOKTYPE

SELECT INVOICE_DATE = VDT, EXCHANGE = @EXCHANGE, SEGMENT = @SEGMENT, RECORDFOR = 'LEDGER',
SUBRECORDFOR=GLCODE, INV_DESC=NARRATION, SETT_NO = '', SETT_TYPE = '',
PARTY_CODE = CLTCODE, CONTRACTNO = '', INT_REF_NO = @EXCHANGE + '_' + @SEGMENT + '_' + VNO + '_' + CONVERT(VARCHAR,VTYP) + '_' + CONVERT(VARCHAR,BOOKTYPE), 
TAXABLE_AMT, TAX_AMT, INVOICE_TYPE = FLAG, INVOICE_SUBTYPE = '', INVOICE_CATEGORY = '', REV_INT_REF_NO = '',
LOCATION_CODE = '', SOURCESTATE = '', TARGETSTATE = '', STATE_CODE = '', INV_NO = '', SACCODE = '', SAC_DESC = '',
BRANCH_CODE = CONVERT(VARCHAR(10),''),
IGST_RATE = CONVERT(NUMERIC(18,4),0),
IGST_AMOUNT = CONVERT(NUMERIC(18,4),0),
CGST_RATE = CONVERT(NUMERIC(18,4),0),
CGST_AMOUNT = CONVERT(NUMERIC(18,4),0),
SGST_RATE = CONVERT(NUMERIC(18,4),0),
SGST_AMOUNT = CONVERT(NUMERIC(18,4),0)
FROM #GSTACCFINAL

GO
