-- Object: PROCEDURE dbo.RPT_TOP10_CREDITORS
-- Server: 10.253.33.91 | DB: ACCOUNT
--------------------------------------------------

  
CREATE PROCEDURE [dbo].[RPT_TOP10_CREDITORS] (@FDATE VARCHAR(11),@TDATE VARCHAR(11))  
  
AS ---- EXEC RPT_TOP10_CREDITORS 'MAR 31 2022','MAR 31 2022'  
  
CREATE TABLE #SCFM (REPORT_DATE DATETIME,CLTCODE VARCHAR(10),BROKING MONEY,MTF MONEY,NET_BALANCE MONEY)  
  
IF EXISTS(SELECT 1 FROM ACCOUNT.DBO.SCFM_REPORTING A WITH (NOLOCK) WHERE REPORT_DATE BETWEEN @FDATE AND @TDATE + ' 23:59')  
BEGIN  
INSERT INTO #SCFM  
SELECT REPORT_DATE,CLTCODE,BROKING=NET_BALANCE-MTF,MTF,NET_BALANCE   
FROM ACCOUNT.DBO.SCFM_REPORTING WHERE REPORT_DATE BETWEEN @FDATE AND @TDATE + ' 23:59'  
END  
  
IF EXISTS(SELECT 1 FROM ACCOUNT.DBO.SCFM_REPORTING_LOG A WITH (NOLOCK) WHERE REPORT_DATE BETWEEN @FDATE AND @TDATE + ' 23:59')  
BEGIN  
INSERT INTO #SCFM  
SELECT REPORT_DATE,CLTCODE,BROKING=NET_BALANCE-MTF,MTF,NET_BALANCE   
FROM ACCOUNT.DBO.SCFM_REPORTING_LOG WHERE REPORT_DATE BETWEEN @FDATE AND @TDATE + ' 23:59'  
END  
  
SELECT REPORT_DATE,CLTCODE,CR_AMT=SUM(MTF) INTO #DR FROM (  
SELECT REPORT_DATE,CLTCODE, MTF FROM #SCFM WHERE MTF < 0  
UNION all  
SELECT REPORT_DATE,CLTCODE,BROKING FROM #SCFM WHERE BROKING < 0)A  
GROUP BY A.REPORT_DATE,A.CLTCODE  
  
SELECT TOP 20 *,REPORT='Creditors' FROM #DR  WHERE CLTCODE <> 'ERROR'  ORDER BY CR_AMT

GO
