-- Object: PROCEDURE dbo.RPT_SCFM_DATA10_31032022
-- Server: 10.253.33.91 | DB: ACCOUNT
--------------------------------------------------

  
  
CREATE PROCEDURE [dbo].[RPT_SCFM_DATA10_31032022] (@FDATE VARCHAR(11),@RUNDATE VARCHAR(11))  
   
AS --- EXEC RPT_SCFM_DATA10 'FEB 16 2022','FEB 16 2022'  
  
CREATE TABLE #DRCR (REPORT_DATE VARCHAR(11),CLTCODE VARCHAR(10),BROKING_BAL MONEY,MTF_BAL MONEY)  
  
IF EXISTS(SELECT 1 FROM ACCOUNT.DBO.SCFM_REPORTING A WITH (NOLOCK) WHERE REPORT_DATE BETWEEN @RUNDATE AND @RUNDATE + ' 23:59')  
BEGIN  
INSERT INTO #DRCR                 
SELECT REPORT_DATE=CONVERT(VARCHAR(11),REPORT_DATE,105),CLTCODE,  
ROUND(BSECM,2)+ROUND(BSEFO,2)+ROUND(BSECD,2)+ROUND(NSECM,2)+ROUND(NSEFO,2)+ROUND(NSECD,2)+  
ROUND(SLBS,2)+ROUND(MCXCD,2)+ROUND(MCDX,2)+ROUND(NCDX,2) AS BROKING_BAL,ROUND(MTF,2) AS MTF_BAL  
FROM SCFM_REPORTING WITH (NOLOCK) WHERE REPORT_DATE BETWEEN @RUNDATE AND @RUNDATE + ' 23:59'  
END  
  
IF EXISTS(SELECT 1 FROM ACCOUNT.DBO.SCFM_REPORTING_LOG A WITH (NOLOCK) WHERE REPORT_DATE BETWEEN @RUNDATE AND @RUNDATE + ' 23:59')  
BEGIN  
INSERT INTO #DRCR                 
SELECT REPORT_DATE=CONVERT(VARCHAR(11),REPORT_DATE,105),CLTCODE,  
ROUND(BSECM,2)+ROUND(BSEFO,2)+ROUND(BSECD,2)+ROUND(NSECM,2)+ROUND(NSEFO,2)+ROUND(NSECD,2)+  
ROUND(SLBS,2)+ROUND(MCXCD,2)+ROUND(MCDX,2)+ROUND(NCDX,2) AS BROKING_BAL,ROUND(MTF,2) AS MTF_BAL  
from SCFM_REPORTING_LOG WITH (NOLOCK) WHERE REPORT_DATE BETWEEN @RUNDATE AND @RUNDATE + ' 23:59'  
END  


IF EXISTS(SELECT 1 FROM ACCOUNT.DBO.SCFM_REPORTING_HISTORY A WITH (NOLOCK) WHERE REPORT_DATE BETWEEN @RUNDATE AND @RUNDATE + ' 23:59')        
BEGIN        
INSERT INTO #DRCR                       
SELECT REPORT_DATE=CONVERT(VARCHAR(11),REPORT_DATE,105),CLTCODE,        
ROUND(BSECM,2)+ROUND(BSEFO,2)+ROUND(BSECD,2)+ROUND(NSECM,2)+ROUND(NSEFO,2)+ROUND(NSECD,2)+        
ROUND(SLBS,2)+ROUND(MCXCD,2)+ROUND(MCDX,2)+ROUND(NCDX,2) AS BROKING_BAL,ROUND(MTF,2) AS MTF_BAL        
FROM SCFM_REPORTING_HISTORY WITH (NOLOCK) WHERE REPORT_DATE BETWEEN @RUNDATE AND @RUNDATE + ' 23:59'-- AND REPORT_DATE <> 'MAR 25 2022'         
/*  
INSERT INTO #DRCR                       
SELECT REPORT_DATE=CONVERT(VARCHAR(11),REPORT_DATE,105),CLTCODE,        
ROUND(BSECM*-1,2)+ROUND(BSEFO*-1,2)+ROUND(BSECD*-1,2)+ROUND(NSECM*-1,2)+ROUND(NSEFO*-1,2)+ROUND(NSECD*-1,2)+        
ROUND(SLBS*-1,2)+ROUND(MCXCD*-1,2)+ROUND(MCDX*-1,2)+ROUND(NCDX*-1,2) AS BROKING_BAL,ROUND(MTF*-1,2) AS MTF_BAL           
from SCFM_REPORTING_HISTORY WITH (NOLOCK) WHERE REPORT_DATE BETWEEN @RUNDATE AND @RUNDATE + ' 23:59' AND REPORT_DATE = 'MAR 25 2022'      
   */ 
END        
  
SELECT REPORT_DATE=CONVERT(VARCHAR(11),REPORT_DATE,105),CLTCODE,REPORT='MTF Creditors',DR_CR_AMT=SUM(MTF_BAL) INTO #SCFMNEWCR  
FROM #DRCR WITH (NOLOCK) WHERE MTF_BAL > 0 GROUP BY REPORT_DATE,CLTCODE  
UNION ALL  
SELECT REPORT_DATE=CONVERT(VARCHAR(11),REPORT_DATE,105),CLTCODE,REPORT='Broking Creditors',DR_CR_AMT=SUM(BROKING_BAL)  
from #DRCR WHERE BROKING_BAL > 0 GROUP BY REPORT_DATE,CLTCODE  
  
SELECT REPORT_DATE,CLTCODE,TOTAL_CRDITOR=SUM(DR_CR_AMT),REPLEDG_STOCK=CONVERT(MONEY,0),MARGIN_AMT=CONVERT(MONEY,0),  
MARGIN_ADJ=CONVERT(MONEY,0),NEW_MARGIN_AMT=CONVERT(MONEY,0),MIN_LED_MAR=CONVERT(MONEY,0) INTO #SCFMCR   
FROM #SCFMNEWCR GROUP BY CLTCODE,REPORT_DATE  
  
  
/* MARGIN UPDATE */ -- DROP TABLE #FDATA  
  
CREATE TABLE #MRG (PARTY_CODE VARCHAR(11),MARGIN MONEY,SEGMENT VARCHAR(5))  
  
IF (SELECT COUNT(*) FROM MSAJAG.DBO.TBL_CMMARGIN WITH (NOLOCK) WHERE MARGINDATE BETWEEN @RUNDATE AND @RUNDATE + ' 23:59') <> 0  
BEGIN  
INSERT INTO #MRG  
SELECT PARTY_CODE, SUM(TOTAL_MARGIN_VAR) AS MARGIN,SEGMENT='CM'   
FROM MSAJAG.DBO.TBL_CMMARGIN WITH (NOLOCK) WHERE MARGINDATE BETWEEN @RUNDATE AND @RUNDATE + ' 23:59' GROUP BY PARTY_CODE  
END  
ELSE  
BEGIN  
INSERT INTO #MRG  
SELECT PARTY_CODE, SUM(TOTAL_MARGIN_VAR) AS MARGIN,SEGMENT='CM'   
FROM MSAJAG.DBO.TBL_CMMARGIN WITH (NOLOCK)  
WHERE MARGINDATE  = (SELECT MAX(MARGINDATE) FROM MSAJAG.DBO.TBL_CMMARGIN WITH (NOLOCK) WHERE MARGINDATE < @RUNDATE)  
GROUP BY PARTY_CODE  
END  
  
  
IF (SELECT COUNT(*) FROM ANGELFO.NSEFO.DBO.FOMARGINNEW WITH (NOLOCK) WHERE MDATE BETWEEN @RUNDATE AND @RUNDATE + ' 23:59') <> 0  
BEGIN  
INSERT INTO #MRG  
SELECT PARTY_CODE,SUM(TOTALMARGIN) AS MARGIN, SEGMENT='FO'  
FROM ANGELFO.NSEFO.DBO.FOMARGINNEW WITH (NOLOCK) WHERE MDATE BETWEEN @RUNDATE AND @RUNDATE + ' 23:59' GROUP BY PARTY_CODE  
END  
ELSE  
BEGIN  
INSERT INTO #MRG  
SELECT PARTY_CODE,SUM(TOTALMARGIN) AS MARGIN, SEGMENT='FO'  
FROM ANGELFO.NSEFO.DBO.FOMARGINNEW WITH (NOLOCK)  
WHERE MDATE  = (SELECT MAX(MDATE)FROM ANGELFO.NSEFO.DBO.FOMARGINNEW WITH (NOLOCK) WHERE MDATE < @RUNDATE) GROUP BY PARTY_CODE  
END  
  
  
IF (SELECT COUNT(*) FROM ANGELFO.NSECURFO.DBO.FOMARGINNEW WITH (NOLOCK) WHERE MDATE BETWEEN @RUNDATE AND @RUNDATE + ' 23:59') <> 0  
BEGIN  
INSERT INTO #MRG  
SELECT PARTY_CODE,SUM(TOTALMARGIN) AS MARGIN, SEGMENT='CD'  
FROM ANGELFO.NSECURFO.DBO.FOMARGINNEW WITH (NOLOCK) WHERE MDATE BETWEEN @RUNDATE AND @RUNDATE + ' 23:59' GROUP BY PARTY_CODE  
END  
ELSE  
BEGIN  
INSERT INTO #MRG  
SELECT PARTY_CODE,SUM(TOTALMARGIN) AS MARGIN, SEGMENT='CD'  
FROM ANGELFO.NSECURFO.DBO.FOMARGINNEW WITH (NOLOCK)  
WHERE MDATE  = (SELECT MAX(MDATE)FROM ANGELFO.NSECURFO.DBO.FOMARGINNEW WITH (NOLOCK) WHERE MDATE < @RUNDATE) GROUP BY PARTY_CODE  
END  
  
  
IF (SELECT COUNT(*) FROM ANGELCOMMODITY.MCDX.DBO.FOMARGINNEW WITH (NOLOCK) WHERE MDATE BETWEEN @RUNDATE AND @RUNDATE + ' 23:59') <> 0  
BEGIN  
INSERT INTO #MRG  
SELECT PARTY_CODE,SUM(TOTALMARGIN) AS MARGIN, SEGMENT='MX'  
FROM ANGELCOMMODITY.MCDX.DBO.FOMARGINNEW WITH (NOLOCK) WHERE MDATE BETWEEN @RUNDATE AND @RUNDATE + ' 23:59' GROUP BY PARTY_CODE  
END  
ELSE  
BEGIN  
INSERT INTO #MRG  
SELECT PARTY_CODE,SUM(TOTALMARGIN) AS MARGIN, SEGMENT='MX'  
FROM ANGELCOMMODITY.MCDX.DBO.FOMARGINNEW WITH (NOLOCK)  
WHERE MDATE  = (SELECT MAX(MDATE)FROM ANGELCOMMODITY.MCDX.DBO.FOMARGINNEW WITH (NOLOCK) WHERE MDATE < @RUNDATE) GROUP BY PARTY_CODE  
END  
  
  
IF (SELECT COUNT(*) FROM ANGELCOMMODITY.NCDX.DBO.TBL_CLIENTMARGIN WITH (NOLOCK) WHERE MARGINDATE BETWEEN @RUNDATE AND @RUNDATE + ' 23:59') <> 0  
BEGIN  
INSERT INTO #MRG  
SELECT PARTY_CODE,SUM(INITIALMARGIN)+SUM(CASE WHEN MTMMARGIN < 0 THEN 0 ELSE MTMMARGIN END ) + SUM(ADDMARGIN) AS MARGIN,SEGMENT='NX'  
FROM ANGELCOMMODITY.NCDX.DBO.TBL_CLIENTMARGIN WITH (NOLOCK) WHERE MARGINDATE BETWEEN @RUNDATE AND @RUNDATE + ' 23:59' GROUP BY PARTY_CODE  
END  
ELSE  
BEGIN  
INSERT INTO #MRG  
SELECT PARTY_CODE,SUM(INITIALMARGIN)+SUM(CASE WHEN MTMMARGIN < 0 THEN 0 ELSE MTMMARGIN END ) + SUM(ADDMARGIN) AS MARGIN,SEGMENT='NX'  
FROM ANGELCOMMODITY.NCDX.DBO.TBL_CLIENTMARGIN WITH (NOLOCK)   
WHERE MARGINDATE = (SELECT MAX(MARGINDATE)FROM ANGELCOMMODITY.NCDX.DBO.TBL_CLIENTMARGIN WITH (NOLOCK) WHERE MARGINDATE < @RUNDATE) GROUP BY PARTY_CODE  
END  
  
  
SELECT PARTY_CODE,CM_MARGIN=ISNULL([CM],0),FO_MARGIN=ISNULL([FO],0),  
CD_MARGIN=ISNULL([CD],0),MX_MARGIN=ISNULL([MX],0),NX_MARGIN=ISNULL([NX],0),  
TOTAL_MARIN=ISNULL([CM],0)+ISNULL([FO],0)+ISNULL([CD],0)+ISNULL([MX],0)+ISNULL([NX],0)  INTO #ALLMRG  
FROM (  
SELECT PARTY_CODE,MARGIN,SEGMENT FROM #MRG) AS SourceTable  
PIVOT  
(SUM(MARGIN) FOR SEGMENT IN ([CM],[FO],[CD],[MX],[NX])) AS PivotTable  
  
UPDATE #SCFMCR SET MARGIN_AMT = B.TOTAL_MARIN FROM #SCFMCR A, #ALLMRG B WHERE A.CLTCODE = B.PARTY_CODE  
  
  
/* RE-PLEDGE STOCK VALUES */  
  
IF (SELECT COUNT(*) FROM MSAJAG.DBO.TBL_CC01_DATA WITH (NOLOCK) WHERE TRANSDATE BETWEEN @RUNDATE AND @RUNDATE + ' 23:59') <> 0  
BEGIN  
UPDATE #SCFMCR SET REPLEDG_STOCK = UTILIZED_AMT FROM #SCFMCR A,  
(SELECT TRANSDATE=CONVERT(VARCHAR(11),TRANSDATE,105),PARTY_CODE,UTILIZED_AMT=SUM(UTILIZED_AMT)   
FROM MSAJAG.DBO.TBL_CC01_DATA WITH (NOLOCK)  
WHERE EXCHANGE='NSE' AND TRANSDATE BETWEEN @RUNDATE AND @RUNDATE + ' 23:59'  
GROUP BY TRANSDATE,PARTY_CODE HAVING SUM(UTILIZED_AMT) <> 0) B  
WHERE A.REPORT_DATE = B.TRANSDATE AND A.CLTCODE = B.PARTY_CODE   
END  
 ELSE  
BEGIN  
SELECT  'CC01 Files not imported for ' + @RUNDATE  
RETURN  
END  
  
UPDATE #SCFMCR SET MARGIN_ADJ = CASE WHEN ((MARGIN_AMT/2)-REPLEDG_STOCK)<0 THEN 0 ELSE ((MARGIN_AMT/2)-REPLEDG_STOCK) END  
  
UPDATE #SCFMCR SET NEW_MARGIN_AMT = (MARGIN_AMT/2) + MARGIN_ADJ  
  
UPDATE #SCFMCR SET MIN_LED_MAR = LED_MAR_MIN FROM #SCFMCR A,  
(SELECT CLTCODE,(SELECT MIN(NSECM) FROM ( VALUES (TOTAL_CRDITOR),(NEW_MARGIN_AMT)) AS NSECM (NSECM)) AS LED_MAR_MIN  
FROM #SCFMCR) B WHERE A.CLTCODE = B.CLTCODE  
  
  
SELECT REPORT_DATE,CLTCODE,  
TOTAL_CRDITOR_AMT=SUM(TOTAL_CRDITOR),  
CREDITOR_MARGIN_AMT=SUM(MARGIN_AMT),  
MIN_MARGIN_CR_AMT=SUM(MIN_LED_MAR),SUM(REPLEDG_STOCK) AS REPLEDG_STOCK,SUM(MARGIN_ADJ) AS MARGIN_ADJ,SUM(NEW_MARGIN_AMT) AS   NEW_MARGIN_AMT
FROM #SCFMCR   WHERE CLTCODE BETWEEN 'A' AND 'MZZZZZZZZZZ'
GROUP BY REPORT_DATE,CLTCODE  

SELECT REPORT_DATE,CLTCODE,  
TOTAL_CRDITOR_AMT=SUM(TOTAL_CRDITOR),  
CREDITOR_MARGIN_AMT=SUM(MARGIN_AMT),  
MIN_MARGIN_CR_AMT=SUM(MIN_LED_MAR),SUM(REPLEDG_STOCK) AS REPLEDG_STOCK,SUM(MARGIN_ADJ) AS MARGIN_ADJ,SUM(NEW_MARGIN_AMT) AS   NEW_MARGIN_AMT  
FROM #SCFMCR   WHERE CLTCODE BETWEEN 'N' AND 'ZZZZZZZZZZZ'
GROUP BY REPORT_DATE,CLTCODE  

/* Final Report */  
  
SELECT REPORT_DATE,  
TOTAL_CRDITOR_AMT=SUM(TOTAL_CRDITOR),  
CREDITOR_MARGIN_AMT=SUM(MARGIN_AMT),  
MIN_MARGIN_CR_AMT=SUM(MIN_LED_MAR)  
FROM #SCFMCR  
GROUP BY REPORT_DATE

GO
