-- Object: PROCEDURE dbo.GET_LEDGER_AUDIT_DATA_BAK_02082022
-- Server: 10.253.33.91 | DB: ACCOUNT
--------------------------------------------------



--EXEC V2_GET_LEDGER_FORMULA_BALANCES 'MAR 31 2013', '9999999999', 0, ''    
--EXEC [MTSRVR06\DEV].ACCOUNT..V2_GET_LEDGER_FORMULA_BALANCES 'MAR 31 2013','9999999999','', 'VDTBAL_OPBAL, T_DAY_BILL, FDT_RECEIPT'    


CREATE PROCEDURE [dbo].[GET_LEDGER_AUDIT_DATA_BAK_02082022]      
 @EFFDATE VARCHAR(11),    
 @SESSIONID VARCHAR(500),    
 @PROCESS_CODE VARCHAR(10),    
 @REPORT_FORMULA VARCHAR(MAX),  
 @EXCHANGE VARCHAR(10),  
 @SEGMENT VARCHAR(50),
 @TABLE_NAME VARCHAR(20) = '' 
AS      
    
DECLARE      
 @START_DATE VARCHAR(11)      
      
IF LEN(@EFFDATE) = 10      
BEGIN      
 SELECT @EFFDATE = CONVERT(VARCHAR(11), CONVERT(DATETIME, @EFFDATE, 103), 109)      
END      
      
SELECT @START_DATE = CONVERT(VARCHAR(11), SDTCUR, 109)      
FROM PARAMETER      
WHERE @EFFDATE BETWEEN SDTCUR AND LDTCUR      
    
    
CREATE TABLE #REPORT_DATA    
(    
 CLTCODE VARCHAR(10),    
 PARTY_NAME VARCHAR(100),       
 ENTITY_LEVEL VARCHAR(20),    
 ENTITY_CODE VARCHAR(25),      
 VDTBAL MONEY,      
 EDTBAL MONEY,      
 FDT_RECEIPT MONEY,      
 FDT_PAYMENTS MONEY,  
 MARGIN_BAL MONEY    
)    
    
DECLARE    
 @@SQL VARCHAR(MAX)    
    
INSERT INTO #REPORT_DATA      
SELECT       
 CLTCODE,    
 PARTY_NAME,       
 ENTITY_LEVEL,    
 ENTITY_CODE,      
 VDTBAL = SUM(VDTBAL),      
 EDTBAL = SUM(EDTBAL),      
 FDT_RECEIPT = SUM(FDT_RECEIPT),      
 FDT_PAYMENTS = SUM(FDT_PAYMENTS),  
 MARGIN_BAL = 0  
FROM      
(SELECT       
 CLTCODE = L.CLTCODE,    
 PARTY_NAME,    
 ENTITY_LEVEL,    
 ENTITY_CODE,      
 VDTBAL = CASE WHEN VDT >= @START_DATE THEN SUM(CASE DRCR WHEN 'D' THEN VAMT ELSE -VAMT END) ELSE 0 END,      
 EDTBAL = CASE WHEN EDT >= @START_DATE AND EDT <= @EFFDATE + ' 23:59' THEN SUM(CASE DRCR WHEN 'D' THEN VAMT ELSE -VAMT END) ELSE 0 END       
   + CASE WHEN EDT >= @START_DATE AND VDT < @START_DATE THEN SUM(CASE DRCR WHEN 'C' THEN VAMT ELSE -VAMT END) ELSE 0 END,      
 FDT_RECEIPT = CASE WHEN (EDT > @EFFDATE + ' 23:59') AND L.VTYP = 2 THEN SUM(VAMT) ELSE 0 END,      
 FDT_PAYMENTS = CASE WHEN (EDT > @EFFDATE + ' 23:59') AND L.VTYP = 3 THEN SUM(VAMT) ELSE 0 END  
FROM       
 --(SELECT VNO,LNO,VTYP,EDT,DRCR,VAMT,VDT,CLTCODE,BOOKTYPE,NARRATION FROM LEDGER WHERE (VDT >= @START_DATE OR EDT >= @START_DATE)      
 --AND VDT <= @EFFDATE + ' 23:59')    L,/*    
 (SELECT VNO,LNO,VTYP,EDT,DRCR,VAMT,VDT,CLTCODE,BOOKTYPE,NARRATION FROM LEDGER (NOLOCK) WHERE 
 --(VDT >= @START_DATE OR 
 EDT >= @START_DATE
 AND CDT <= DATEADD(MI, -15, GETDATE())
 --)      
 AND VDT <= @EFFDATE + ' 23:59' AND CDT <= DATEADD(MI, -15, GETDATE()))    L,/*    
 LEFT OUTER JOIN (SELECT RELDT = (CASE WHEN RELDT = '' THEN CONVERT(DATETIME,'DEC 31 2049 23:59') ELSE RELDT END), 
						    VTYP,VNO,LNO,BOOKTYPE FROM LEDGER1 WHERE (RELDT > @EFFDATE + ' 23:59' OR RELDT = '')) L1  
 ON L.VTYP = L1.VTYP AND L.BOOKTYPE = L1.BOOKTYPE AND L.VNO = L1.VNO AND L.LNO = L1.LNO,  */
 FORMULA_CLIENT_MASTER A      
WHERE      
 A.CLTCODE = L.CLTCODE AND SESSION_ID = @SESSIONID    
 GROUP BY       
 L.CLTCODE, PARTY_NAME, ENTITY_LEVEL, ENTITY_CODE,  L.VDT, EDT, L.VTYP, DRCR--, L1.RELDT      
) A      
GROUP BY CLTCODE, PARTY_NAME, ENTITY_LEVEL, ENTITY_CODE        
--HAVING SUM(VDTBAL) <> 0 AND SUM(EDTBAL) <> 0 
/*
UPDATE R SET R.FDT_RECEIPT = A.FDT_RECEIPT, R.FDT_PAYMENTS = A.FDT_PAYMENTS
FROM #REPORT_DATA R, (SELECT CLTCODE, FDT_RECEIPT = SUM(CASE WHEN L1.VTYP = 2 THEN VAMT ELSE 0 END),
FDT_PAYMENTS = SUM(CASE WHEN L1.VTYP = 3 THEN VAMT ELSE 0 END) FROM
(SELECT VNO,LNO,VTYP,EDT,DRCR,VAMT,VDT,CLTCODE,BOOKTYPE,NARRATION FROM LEDGER WHERE VDT <= @EFFDATE + ' 23:59')    L,    
(SELECT RELDT = (CASE WHEN RELDT = '' THEN CONVERT(DATETIME,'DEC 31 2049 23:59') ELSE RELDT END), 
						    VTYP,VNO,LNO,BOOKTYPE FROM LEDGER1 WHERE (RELDT > @EFFDATE + ' 23:59' OR RELDT = '') and CLEAR_MODE <> 'C') L1  
 WHERE L.VTYP = L1.VTYP AND L.BOOKTYPE = L1.BOOKTYPE AND L.VNO = L1.VNO AND L.LNO = L1.LNO
AND L1.VTYP IN(2, 3)  
GROUP BY CLTCODE ) A
WHERE R.CLTCODE = A.CLTCODE
 */ 
/*  
UPDATE RD SET MARGIN_BAL = ML.AMOUNT  
FROM #REPORT_DATA RD, (  
 SELECT PARTY_CODE, AMOUNT = SUM(CASE DRCR WHEN 'C' THEN AMOUNT ELSE -AMOUNT END)  
 FROM MARGINLEDGER ML  
 WHERE VDT >= @START_DATE AND VDT <= @EFFDATE + ' 23:59'  
 GROUP BY PARTY_CODE  
)ML  
WHERE RD.CLTCODE = PARTY_CODE  
*/  
IF @TABLE_NAME <> ''
BEGIN
	SET @@SQL = " TRUNCATE TABLE " + @TABLE_NAME  
	EXEC (@@SQL)
END

IF @TABLE_NAME <> ''
   SET @@SQL = " INSERT INTO " + @TABLE_NAME + " SELECT "    
ELSE
SET @@SQL = " SELECT "   
 
SET @@SQL = @@SQL + " CLTCODE, "    
SET @@SQL = @@SQL + " PARTY_NAME, "    
SET @@SQL = @@SQL + " ENTITY_LEVEL,"    
SET @@SQL = @@SQL + " ENTITY_CODE, "    
SET @@SQL = @@SQL + @REPORT_FORMULA + ", EXCHANGE = '" + @EXCHANGE + "', SEGMENT = '" + @SEGMENT + "', SESSIONID = '" + @SESSIONID + "', POPULATE_DATE = GETDATE() "    
SET @@SQL = @@SQL + " FROM "    
SET @@SQL = @@SQL + " #REPORT_DATA"    

EXEC (@@SQL)

GO
