-- Object: PROCEDURE dbo.RPT_RECO_DATA_MISIV
-- Server: 10.253.33.91 | DB: ACCOUNT
--------------------------------------------------



CREATE PROCEDURE [dbo].[RPT_RECO_DATA_MISIV] (@TODATE DATETIME)

AS  ---- EXEC RPT_RECO_DATA_MISIV 'JUN  1 2021'

TRUNCATE TABLE UNRECOMIS

INSERT INTO UNRECOMIS
SELECT EXCHNAGE='NSECM',A.CLTCODE,A.VAMT,A.DRCR,A.VTYP,A.VNO,A.BOOKTYPE,A.VDT,A.EDT,A.CDT,B.RELDT,B.DDNO,NARRATION=REPLACE(REPLACE(A.NARRATION,',',''),'|',''),A.ENTEREDBY,
CATEGORY=CONVERT(VARCHAR(150),''),RECOSTATUS=CONVERT(VARCHAR(50),'UNRECONCILED') 
FROM ACCOUNT.DBO.LEDGER A WITH (NOLOCK) ,ACCOUNT.DBO.LEDGER1 B WITH (NOLOCK)
WHERE A.VNO = B.VNO AND A.VTYP = B.VTYP AND A.VAMT = B.RELAMT AND A.VDT BETWEEN @TODATE - 180 AND @TODATE + ' 23:59' AND A.VTYP IN ('2','3','16','17')
AND  B.RELDT ='1900-01-01 00:00:00.000'

INSERT INTO UNRECOMIS
SELECT EXCHNAGE='BSECM',A.CLTCODE,A.VAMT,A.DRCR,A.VTYP,A.VNO,A.BOOKTYPE,A.VDT,A.EDT,A.CDT,B.RELDT,B.DDNO,NARRATION=REPLACE(REPLACE(A.NARRATION,',',''),'|',''),A.ENTEREDBY,
CATEGORY=CONVERT(VARCHAR(150),''),RECOSTATUS=CONVERT(VARCHAR(50),'UNRECONCILED') --INTO UNRECOMIS
FROM ANAND.ACCOUNT_AB.DBO.LEDGER A WITH (NOLOCK) ,ANAND.ACCOUNT_AB.DBO.LEDGER1 B WITH (NOLOCK)
WHERE A.VNO = B.VNO AND A.VTYP = B.VTYP AND A.VAMT = B.RELAMT AND A.VDT BETWEEN @TODATE - 180 AND @TODATE + ' 23:59' AND A.VTYP IN ('2','3','16','17')
AND  B.RELDT ='1900-01-01 00:00:00.000'

INSERT INTO UNRECOMIS
SELECT EXCHNAGE='NSEFO',A.CLTCODE,A.VAMT,A.DRCR,A.VTYP,A.VNO,A.BOOKTYPE,A.VDT,A.EDT,A.CDT,B.RELDT,B.DDNO,NARRATION=REPLACE(REPLACE(A.NARRATION,',',''),'|',''),A.ENTEREDBY,
CATEGORY=CONVERT(VARCHAR(150),''),RECOSTATUS=CONVERT(VARCHAR(50),'UNRECONCILED') 
FROM ANGELFO.ACCOUNTFO.DBO.LEDGER A WITH (NOLOCK) ,ANGELFO.ACCOUNTFO.DBO.LEDGER1  B WITH (NOLOCK)
WHERE A.VNO = B.VNO AND A.VTYP = B.VTYP AND A.VAMT = B.RELAMT AND A.VDT BETWEEN @TODATE - 180 AND @TODATE + ' 23:59' AND A.VTYP IN ('2','3','16','17')
AND  B.RELDT ='1900-01-01 00:00:00.000'

INSERT INTO UNRECOMIS
SELECT EXCHNAGE='NSECD',A.CLTCODE,A.VAMT,A.DRCR,A.VTYP,A.VNO,A.BOOKTYPE,A.VDT,A.EDT,A.CDT,B.RELDT,B.DDNO,NARRATION=REPLACE(REPLACE(A.NARRATION,',',''),'|',''),A.ENTEREDBY,
CATEGORY=CONVERT(VARCHAR(150),''),RECOSTATUS=CONVERT(VARCHAR(50),'UNRECONCILED') 
FROM ANGELFO.ACCOUNTCURFO.DBO.LEDGER A WITH (NOLOCK) ,ANGELFO.ACCOUNTCURFO.DBO.LEDGER1  B WITH (NOLOCK)
WHERE A.VNO = B.VNO AND A.VTYP = B.VTYP AND A.VAMT = B.RELAMT AND A.VDT BETWEEN @TODATE - 180 AND @TODATE + ' 23:59' AND A.VTYP IN ('2','3','16','17')
AND  B.RELDT ='1900-01-01 00:00:00.000'

INSERT INTO UNRECOMIS
SELECT EXCHNAGE='MCXCD',A.CLTCODE,A.VAMT,A.DRCR,A.VTYP,A.VNO,A.BOOKTYPE,A.VDT,A.EDT,A.CDT,B.RELDT,B.DDNO,NARRATION=REPLACE(REPLACE(A.NARRATION,',',''),'|',''),A.ENTEREDBY,
CATEGORY=CONVERT(VARCHAR(150),''),RECOSTATUS=CONVERT(VARCHAR(50),'UNRECONCILED') 
FROM ANGELCOMMODITY.ACCOUNTMCDXCDS.DBO.LEDGER A WITH (NOLOCK) ,ANGELCOMMODITY.ACCOUNTMCDXCDS.DBO.LEDGER1  B WITH (NOLOCK)
WHERE A.VNO = B.VNO AND A.VTYP = B.VTYP AND A.VAMT = B.RELAMT AND A.VDT BETWEEN @TODATE - 180 AND @TODATE + ' 23:59' AND A.VTYP IN ('2','3','16','17')
AND  B.RELDT ='1900-01-01 00:00:00.000'

INSERT INTO UNRECOMIS
SELECT EXCHNAGE='MCDX',A.CLTCODE,A.VAMT,A.DRCR,A.VTYP,A.VNO,A.BOOKTYPE,A.VDT,A.EDT,A.CDT,B.RELDT,B.DDNO,NARRATION=REPLACE(REPLACE(A.NARRATION,',',''),'|',''),A.ENTEREDBY,
CATEGORY=CONVERT(VARCHAR(150),''),RECOSTATUS=CONVERT(VARCHAR(50),'UNRECONCILED') 
FROM ANGELCOMMODITY.ACCOUNTMCDX.DBO.LEDGER A WITH (NOLOCK) ,ANGELCOMMODITY.ACCOUNTMCDX.DBO.LEDGER1  B WITH (NOLOCK)
WHERE A.VNO = B.VNO AND A.VTYP = B.VTYP AND A.VAMT = B.RELAMT AND A.VDT BETWEEN @TODATE - 180 AND @TODATE + ' 23:59' AND A.VTYP IN ('2','3','16','17')
AND  B.RELDT ='1900-01-01 00:00:00.000'

INSERT INTO UNRECOMIS
SELECT EXCHNAGE='NCDX',A.CLTCODE,A.VAMT,A.DRCR,A.VTYP,A.VNO,A.BOOKTYPE,A.VDT,A.EDT,A.CDT,B.RELDT,B.DDNO,NARRATION=REPLACE(REPLACE(A.NARRATION,',',''),'|',''),A.ENTEREDBY,
CATEGORY=CONVERT(VARCHAR(150),''),RECOSTATUS=CONVERT(VARCHAR(50),'UNRECONCILED') 
FROM ANGELCOMMODITY.ACCOUNTNCDX.DBO.LEDGER A WITH (NOLOCK) ,ANGELCOMMODITY.ACCOUNTNCDX.DBO.LEDGER1  B WITH (NOLOCK)
WHERE A.VNO = B.VNO AND A.VTYP = B.VTYP AND A.VAMT = B.RELAMT AND A.VDT BETWEEN @TODATE - 180 AND @TODATE + ' 23:59' AND A.VTYP IN ('2','3','16','17')
AND  B.RELDT ='1900-01-01 00:00:00.000'

INSERT INTO UNRECOMIS
SELECT EXCHNAGE='BSEFO',A.CLTCODE,A.VAMT,A.DRCR,A.VTYP,A.VNO,A.BOOKTYPE,A.VDT,A.EDT,A.CDT,B.RELDT,B.DDNO,NARRATION=REPLACE(REPLACE(A.NARRATION,',',''),'|',''),A.ENTEREDBY,
CATEGORY=CONVERT(VARCHAR(150),''),RECOSTATUS=CONVERT(VARCHAR(50),'UNRECONCILED') 
FROM ANGELCOMMODITY.ACCOUNTBFO.DBO.LEDGER A WITH (NOLOCK) ,ANGELCOMMODITY.ACCOUNTBFO.DBO.LEDGER1  B WITH (NOLOCK)
WHERE A.VNO = B.VNO AND A.VTYP = B.VTYP AND A.VAMT = B.RELAMT AND A.VDT BETWEEN @TODATE - 180 AND @TODATE + ' 23:59' AND A.VTYP IN ('2','3','16','17')
AND  B.RELDT ='1900-01-01 00:00:00.000'

INSERT INTO UNRECOMIS
SELECT EXCHNAGE='BSECD',A.CLTCODE,A.VAMT,A.DRCR,A.VTYP,A.VNO,A.BOOKTYPE,A.VDT,A.EDT,A.CDT,B.RELDT,B.DDNO,NARRATION=REPLACE(REPLACE(A.NARRATION,',',''),'|',''),A.ENTEREDBY,
CATEGORY=CONVERT(VARCHAR(150),''),RECOSTATUS=CONVERT(VARCHAR(50),'UNRECONCILED') 
FROM ANGELCOMMODITY.ACCOUNTCURBFO.DBO.LEDGER A WITH (NOLOCK) ,ANGELCOMMODITY.ACCOUNTCURBFO.DBO.LEDGER1  B WITH (NOLOCK)
WHERE A.VNO = B.VNO AND A.VTYP = B.VTYP AND A.VAMT = B.RELAMT AND A.VDT BETWEEN @TODATE - 180 AND @TODATE + ' 23:59' AND A.VTYP IN ('2','3','16','17')
AND  B.RELDT ='1900-01-01 00:00:00.000'

INSERT INTO UNRECOMIS
SELECT EXCHANGE='BSEMF',A.MAINLEDGER,AMOUNT=CASE WHEN A.DRAMOUNT=0 THEN A.CRAMOUNT ELSE A.DRAMOUNT END,
DRCR=CASE WHEN A.DRAMOUNT=0 THEN 'C' ELSE 'D' END,A.VTYPE,A.VNO,A.BOOKTYPE,VDT,EDT,A.POSTED_ON,RELDATE=A.CR_RELDT,
INSTNO,NARRATION=REPLACE(REPLACE(A.NARRATION,',',''),'|',''),A.POSTED_BY,CATEGORY=CONVERT(VARCHAR(150),''),RECOSTATUS=CONVERT(VARCHAR(50),'UNRECONCILED') 
FROM ANGELFO.BBO_FA.DBO.ACC_LEDGER_NEW A (NOLOCK) WHERE A.VDT BETWEEN @TODATE - 180 AND @TODATE + ' 23:59' 
AND VTYPE ='2' AND A.CR_RELDT='1900-01-01 00:00:00.000'
UNION ALL
SELECT EXCHANGE='BSEMF',A.MAINLEDGER,AMOUNT=CASE WHEN A.DRAMOUNT=0 THEN A.CRAMOUNT ELSE A.DRAMOUNT END,
DRCR=CASE WHEN A.DRAMOUNT=0 THEN 'C' ELSE 'D' END,A.VTYPE,A.VNO,A.BOOKTYPE,VDT,EDT,A.POSTED_ON,RELDATE=A.DR_RELDT,
INSTNO,NARRATION=REPLACE(REPLACE(A.NARRATION,',',''),'|',''),A.POSTED_BY,CATEGORY=CONVERT(VARCHAR(150),''),RECOSTATUS=CONVERT(VARCHAR(50),'UNRECONCILED') 
FROM ANGELFO.BBO_FA.DBO.ACC_LEDGER_NEW A (NOLOCK) WHERE A.VDT BETWEEN @TODATE - 180 AND @TODATE + ' 23:59' 
AND VTYPE ='3' AND A.DR_RELDT='1900-01-01 00:00:00.000'


UPDATE UNRECOMIS SET CATEGORY='CMS' FROM UNRECOMIS A,
(SELECT  VNO,VTYP FROM UNRECOMIS WHERE NARRATION LIKE '%CHQ%') B WHERE A.VNO =B.VNO AND A.VTYP = B.VTYP

UPDATE UNRECOMIS SET CATEGORY='ONLINE' FROM UNRECOMIS A,
(SELECT  VNO,VTYP FROM UNRECOMIS WHERE NARRATION='AMOUNT RECEIVED') B WHERE A.VNO =B.VNO AND A.VTYP = B.VTYP

UPDATE UNRECOMIS SET CATEGORY='ONLINE' FROM UNRECOMIS A,
(SELECT  VNO,VTYP FROM UNRECOMIS WHERE NARRATION='AMOUNT RECEIVED-SUCCESS') B WHERE A.VNO =B.VNO AND A.VTYP = B.VTYP

UPDATE UNRECOMIS SET CATEGORY='NBFC' FROM UNRECOMIS A,
(SELECT  VNO,VTYP FROM UNRECOMIS WHERE ENTEREDBY IN ('ANIMESH','B_E04123')) B WHERE A.VNO =B.VNO AND A.VTYP = B.VTYP

UPDATE UNRECOMIS SET CATEGORY='DUPLICATE' FROM UNRECOMIS A,
(SELECT  VNO,VTYP FROM UNRECOMIS WHERE NARRATION LIKE '%DUPLICATE%') B WHERE A.VNO =B.VNO AND A.VTYP = B.VTYP

UPDATE UNRECOMIS SET CATEGORY='PAYOUT' FROM UNRECOMIS A,
(SELECT  VNO,VTYP FROM UNRECOMIS WHERE NARRATION LIKE '%A/C xxxx%') B WHERE A.VNO =B.VNO AND A.VTYP = B.VTYP

UPDATE UNRECOMIS SET CATEGORY='PAYOUT' FROM UNRECOMIS A,
(SELECT  VNO,VTYP FROM UNRECOMIS WHERE NARRATION LIKE '%PayOut%') B WHERE A.VNO =B.VNO AND A.VTYP = B.VTYP

UPDATE UNRECOMIS SET CATEGORY='PAYOUT' FROM UNRECOMIS A,
(SELECT  VNO,VTYP FROM UNRECOMIS WHERE NARRATION LIKE '%Pay Out%') B WHERE A.VNO =B.VNO AND A.VTYP = B.VTYP

UPDATE UNRECOMIS SET CATEGORY='PAYOUT' FROM UNRECOMIS A,
(SELECT  VNO,VTYP FROM UNRECOMIS WHERE NARRATION LIKE '%Quarterly%') B WHERE A.VNO =B.VNO AND A.VTYP = B.VTYP

UPDATE UNRECOMIS SET CATEGORY='REFUND' FROM UNRECOMIS A,
(SELECT  VNO,VTYP FROM UNRECOMIS WHERE NARRATION LIKE '%REFUND%') B WHERE A.VNO =B.VNO AND A.VTYP = B.VTYP

UPDATE UNRECOMIS SET CATEGORY='NRI' FROM UNRECOMIS A,
(SELECT  VNO,VTYP FROM UNRECOMIS WHERE CLTCODE LIKE 'ZR%') B WHERE A.VNO =B.VNO AND A.VTYP = B.VTYP

UPDATE UNRECOMIS SET CATEGORY='SBTAG' FROM UNRECOMIS A,
(SELECT  VNO,VTYP FROM UNRECOMIS WHERE CLTCODE IN ('05017','02015','1000011')) B WHERE A.VNO =B.VNO AND A.VTYP = B.VTYP

UPDATE UNRECOMIS SET CATEGORY='CONTROL' FROM UNRECOMIS A,
(SELECT  VNO,VTYP FROM UNRECOMIS WHERE NARRATION NOT LIKE '%REFUND%' AND CLTCODE IN ('43000002','430000015','5100000018','43000003','43000004','5100000017','440001')) B 
WHERE A.VNO =B.VNO AND A.VTYP = B.VTYP

UPDATE UNRECOMIS SET CATEGORY='CONTROL' FROM UNRECOMIS A,
(SELECT  VNO,VTYP FROM UNRECOMIS WHERE ENTEREDBY LIKE '%E06832%') B WHERE A.VNO =B.VNO AND A.VTYP = B.VTYP

UPDATE UNRECOMIS SET CATEGORY='MF SIP' FROM UNRECOMIS A,
(SELECT  VNO,VTYP FROM UNRECOMIS WHERE NARRATION LIKE '%SIP%') B WHERE A.VNO =B.VNO AND A.VTYP = B.VTYP

UPDATE UNRECOMIS SET CATEGORY='MISC' FROM UNRECOMIS A,
(SELECT  VNO,VTYP FROM UNRECOMIS WHERE CATEGORY='') B WHERE A.VNO =B.VNO AND A.VTYP = B.VTYP

DELETE FROM UNRECOMIS WHERE CLTCODE LIKE '99%'
DELETE FROM UNRECOMIS WHERE CLTCODE LIKE '20%'

TRUNCATE TABLE REPORTDATA

INSERT INTO REPORTDATA
SELECT * ,DATEDIFF(DAY,VDT,@TODATE) AS NODAY,MISSTATUS=CONVERT(VARCHAR(50),'') FROM UNRECOMIS WHERE VTYP='2' AND DRCR='D'
UNION ALL
SELECT * ,DATEDIFF(DAY,VDT,@TODATE) AS NODAY,MISSTATUS=CONVERT(VARCHAR(50),'') FROM UNRECOMIS WHERE VTYP='3' AND DRCR='C'

UPDATE REPORTDATA SET MISSTATUS = CONVERT(VARCHAR(11),VDT,105) WHERE NODAY BETWEEN '0' AND '7'
UPDATE REPORTDATA SET MISSTATUS = '08-15DAYS' WHERE NODAY BETWEEN '8' AND '15'
UPDATE REPORTDATA SET MISSTATUS = '16-30DAYS' WHERE NODAY BETWEEN '16' AND '30'
UPDATE REPORTDATA SET MISSTATUS = '31-60DAYS' WHERE NODAY BETWEEN '31' AND '60'
UPDATE REPORTDATA SET MISSTATUS = '61-90DAYS' WHERE NODAY BETWEEN '61' AND '90'
UPDATE REPORTDATA SET MISSTATUS = '91+DAYS' WHERE NODAY BETWEEN '91' AND '999999999'

SELECT EXCHNAGE='EXCHNAGE',CLTCODE='CLTCODE',VAMT='VAMT',DRCR='DRCR',VTYP='VTYP',VNO='VNO',BOOKTYPE='BOOKTYPE',
NODAY='NODAY',MISSTATUS='MISSTATUS',VDT='VDT',EDT='EDT',CDT='CDT',RELDT='RELDT',DDNO='DDNO',
NARRATION='NARRATION',ENTEREDBY='ENTEREDBY',CATEGORY='CATEGORY',RECOSTATUS='RECOSTATUS'
UNION ALL
SELECT EXCHNAGE,CLTCODE,VAMT=CONVERT(VARCHAR,VAMT),DRCR,VTYP=CONVERT(VARCHAR,VTYP),VNO=CONVERT(VARCHAR,VNO),BOOKTYPE,NODAY=CONVERT(VARCHAR,NODAY),
MISSTATUS,VDT=CONVERT(VARCHAR(11),VDT,105),EDT=CONVERT(VARCHAR(11),EDT,105),CDT=CONVERT(VARCHAR,CDT),RELDT=CONVERT(VARCHAR,RELDT),
DDNO,NARRATION,ENTEREDBY,CATEGORY,RECOSTATUS
FROM REPORTDATA

GO
