-- Object: PROCEDURE dbo.RPT_RECO_MISIII
-- Server: 10.253.33.91 | DB: ACCOUNT
--------------------------------------------------


CREATE PROCEDURE [dbo].[RPT_RECO_MISIII] (@TODATE DATETIME)

AS --- RPT_RECO_MIS_UPDATE 'MAY 26 2021'

SELECT EXCHNAGE='NSECM',CLTCODE,VAMT,DRCR,VTYP,VNO,BOOKTYPE,VDT,EDT,CDT,
RELDATE = (SELECT MAX(reldt) FROM ACCOUNT.DBO.LEDGER1 B WITH (NOLOCK) WHERE A.VNO = B.vno AND A.VTYP = B.vtyp),
DDNO = (SELECT MAX(DDNO) FROM ACCOUNT.DBO.LEDGER1 B WITH (NOLOCK) WHERE A.VNO = B.vno AND A.VTYP = B.vtyp),NARRATION,ENTEREDBY,
ACTYPE=CONVERT(VARCHAR(150),''),RECOSTATUS=CONVERT(VARCHAR(50),'RECONCILED') INTO #RECOMIS
FROM ACCOUNT.DBO.LEDGER A WITH (NOLOCK) 
WHERE VDT BETWEEN @TODATE - 15 AND @TODATE + ' 23:59' AND DRCR='D' AND VTYP='2'

INSERT INTO #RECOMIS
SELECT EXCHNAGE='BSECM',CLTCODE,VAMT,DRCR,VTYP,VNO,BOOKTYPE,VDT,EDT,CDT,
RELDATE = (SELECT MAX(reldt) FROM ANAND.ACCOUNT_AB.DBO.LEDGER1 B WITH (NOLOCK) WHERE A.VNO = B.vno AND A.VTYP = B.vtyp),
DDNO = (SELECT MAX(DDNO) FROM ANAND.ACCOUNT_AB.DBO.LEDGER1 B WITH (NOLOCK) WHERE A.VNO = B.vno AND A.VTYP = B.vtyp),NARRATION,ENTEREDBY,
ACTYPE=CONVERT(VARCHAR(150),''),RECOSTATUS=CONVERT(VARCHAR(50),'RECONCILED') 
FROM ANAND.ACCOUNT_AB.DBO.LEDGER A WITH (NOLOCK) 
WHERE VDT BETWEEN @TODATE - 15 AND @TODATE + ' 23:59' AND DRCR='D' AND VTYP='2'


INSERT INTO #RECOMIS
SELECT EXCHNAGE='NSEFO',CLTCODE,VAMT,DRCR,VTYP,VNO,BOOKTYPE,VDT,EDT,CDT,
RELDATE = (SELECT MAX(reldt) FROM ANGELFO.ACCOUNTFO.DBO.LEDGER1 B WITH (NOLOCK) WHERE A.VNO = B.vno AND A.VTYP = B.vtyp),
DDNO = (SELECT MAX(DDNO) FROM ANGELFO.ACCOUNTFO.DBO.LEDGER1 B WITH (NOLOCK) WHERE A.VNO = B.vno AND A.VTYP = B.vtyp),NARRATION,ENTEREDBY,
ACTYPE=CONVERT(VARCHAR(150),''),RECOSTATUS=CONVERT(VARCHAR(50),'RECONCILED') 
FROM ANGELFO.ACCOUNTFO.DBO.LEDGER A WITH (NOLOCK) 
WHERE VDT BETWEEN @TODATE - 15 AND @TODATE + ' 23:59' AND DRCR='D' AND VTYP='2'


INSERT INTO #RECOMIS
SELECT EXCHNAGE='NSECD',CLTCODE,VAMT,DRCR,VTYP,VNO,BOOKTYPE,VDT,EDT,CDT,
RELDATE = (SELECT MAX(reldt) FROM ANGELFO.ACCOUNTCURFO.DBO.LEDGER1 B WITH (NOLOCK) WHERE A.VNO = B.vno AND A.VTYP = B.vtyp),
DDNO = (SELECT MAX(DDNO) FROM ANGELFO.ACCOUNTCURFO.DBO.LEDGER1 B WITH (NOLOCK) WHERE A.VNO = B.vno AND A.VTYP = B.vtyp),NARRATION,ENTEREDBY,
ACTYPE=CONVERT(VARCHAR(150),''),RECOSTATUS=CONVERT(VARCHAR(50),'RECONCILED') 
FROM ANGELFO.ACCOUNTCURFO.DBO.LEDGER A WITH (NOLOCK) 
WHERE VDT BETWEEN @TODATE - 15 AND @TODATE + ' 23:59' AND DRCR='D' AND VTYP='2'


INSERT INTO #RECOMIS
SELECT EXCHNAGE='MCXCD',CLTCODE,VAMT,DRCR,VTYP,VNO,BOOKTYPE,VDT,EDT,CDT,
RELDATE = (SELECT MAX(reldt) FROM ANGELCOMMODITY.ACCOUNTMCDXCDS.DBO.LEDGER1 B WITH (NOLOCK) WHERE A.VNO = B.vno AND A.VTYP = B.vtyp),
DDNO = (SELECT MAX(DDNO) FROM ANGELCOMMODITY.ACCOUNTMCDXCDS.DBO.LEDGER1 B WITH (NOLOCK) WHERE A.VNO = B.vno AND A.VTYP = B.vtyp),NARRATION,ENTEREDBY,
ACTYPE=CONVERT(VARCHAR(150),''),RECOSTATUS=CONVERT(VARCHAR(50),'RECONCILED') 
FROM ANGELCOMMODITY.ACCOUNTMCDXCDS.DBO.LEDGER A WITH (NOLOCK) 
WHERE VDT BETWEEN @TODATE - 15 AND @TODATE + ' 23:59' AND DRCR='D' AND VTYP='2'

INSERT INTO #RECOMIS
SELECT EXCHNAGE='MCDX',CLTCODE,VAMT,DRCR,VTYP,VNO,BOOKTYPE,VDT,EDT,CDT,
RELDATE = (SELECT MAX(reldt) FROM ANGELCOMMODITY.ACCOUNTMCDX.DBO.LEDGER1 B WITH (NOLOCK) WHERE A.VNO = B.vno AND A.VTYP = B.vtyp),
DDNO = (SELECT MAX(DDNO) FROM ANGELCOMMODITY.ACCOUNTMCDX.DBO.LEDGER1 B WITH (NOLOCK) WHERE A.VNO = B.vno AND A.VTYP = B.vtyp),NARRATION,ENTEREDBY,
ACTYPE=CONVERT(VARCHAR(150),''),RECOSTATUS=CONVERT(VARCHAR(50),'RECONCILED') 
FROM ANGELCOMMODITY.ACCOUNTMCDX.DBO.LEDGER A WITH (NOLOCK) 
WHERE VDT BETWEEN @TODATE - 15 AND @TODATE + ' 23:59' AND DRCR='D' AND VTYP='2'


INSERT INTO #RECOMIS
SELECT EXCHNAGE='NCDX',CLTCODE,VAMT,DRCR,VTYP,VNO,BOOKTYPE,VDT,EDT,CDT,
RELDATE = (SELECT MAX(reldt) FROM ANGELCOMMODITY.ACCOUNTNCDX.DBO.LEDGER1 B WITH (NOLOCK) WHERE A.VNO = B.vno AND A.VTYP = B.vtyp),
DDNO = (SELECT MAX(DDNO) FROM ANGELCOMMODITY.ACCOUNTNCDX.DBO.LEDGER1 B WITH (NOLOCK) WHERE A.VNO = B.vno AND A.VTYP = B.vtyp),NARRATION,ENTEREDBY,
ACTYPE=CONVERT(VARCHAR(150),''),RECOSTATUS=CONVERT(VARCHAR(50),'RECONCILED') 
FROM ANGELCOMMODITY.ACCOUNTNCDX.DBO.LEDGER A WITH (NOLOCK) 
WHERE VDT BETWEEN @TODATE - 15 AND @TODATE + ' 23:59' AND DRCR='D' AND VTYP='2'


INSERT INTO #RECOMIS
SELECT EXCHNAGE='BSEFO',CLTCODE,VAMT,DRCR,VTYP,VNO,BOOKTYPE,VDT,EDT,CDT,
RELDATE = (SELECT MAX(reldt) FROM ANGELCOMMODITY.ACCOUNTBFO.DBO.LEDGER1 B WITH (NOLOCK) WHERE A.VNO = B.vno AND A.VTYP = B.vtyp),
DDNO = (SELECT MAX(DDNO) FROM ANGELCOMMODITY.ACCOUNTBFO.DBO.LEDGER1 B WITH (NOLOCK) WHERE A.VNO = B.vno AND A.VTYP = B.vtyp),NARRATION,ENTEREDBY,
ACTYPE=CONVERT(VARCHAR(150),''),RECOSTATUS=CONVERT(VARCHAR(50),'RECONCILED') 
FROM ANGELCOMMODITY.ACCOUNTBFO.DBO.LEDGER A WITH (NOLOCK) 
WHERE VDT BETWEEN @TODATE - 15 AND @TODATE + ' 23:59' AND DRCR='D' AND VTYP='2'


INSERT INTO #RECOMIS
SELECT EXCHNAGE='BSECD',CLTCODE,VAMT,DRCR,VTYP,VNO,BOOKTYPE,VDT,EDT,CDT,
RELDATE = (SELECT MAX(reldt) FROM ANGELCOMMODITY.ACCOUNTCURBFO.DBO.LEDGER1 B WITH (NOLOCK) WHERE A.VNO = B.vno AND A.VTYP = B.vtyp),
DDNO = (SELECT MAX(DDNO) FROM ANGELCOMMODITY.ACCOUNTCURBFO.DBO.LEDGER1 B WITH (NOLOCK) WHERE A.VNO = B.vno AND A.VTYP = B.vtyp),NARRATION,ENTEREDBY,
ACTYPE=CONVERT(VARCHAR(150),''),RECOSTATUS=CONVERT(VARCHAR(50),'RECONCILED') 
FROM ANGELCOMMODITY.ACCOUNTCURBFO.DBO.LEDGER A WITH (NOLOCK) 
WHERE VDT BETWEEN @TODATE - 15 AND @TODATE + ' 23:59' AND DRCR='D' AND VTYP='2'

INSERT INTO #RECOMIS
SELECT EXCHANGE='BSEMF',B.OPP_BANK,B.CRAMOUNT,DRCR='D',A.VTYPE,A.VNO,A.BOOKTYPE,VDT=CONVERT(DATETIME,CONVERT(VARCHAR(11),A.VDT)),B.EDT,
CDT=A.POSTED_ON,RELDATE=C.CR_RELDT,DDNO=C.INSTNO,B.NARRATION,A.POSTED_BY,ACTYPE=CONVERT(VARCHAR(150),''),RECOSTATUS=CONVERT(VARCHAR(50),'RECONCILED')
FROM ANGELFO.BBO_FA.DBO.ACC_TBL1 A (NOLOCK),ANGELFO.BBO_FA.DBO.ACC_TBL3 B (NOLOCK) , ANGELFO.BBO_FA.DBO.ACC_TBL4 C (NOLOCK)
WHERE A.SNO = B.MASTERSNO AND B.MASTERSNO = C.MASTERSNO AND VTYPE='2' 
AND CONVERT(DATETIME,CONVERT(VARCHAR(11),VDT)) BETWEEN @TODATE - 15 AND @TODATE + ' 23:59' 


UPDATE #RECOMIS SET RECOSTATUS ='UNRECONCILED' WHERE RELDATE='1900-01-01 00:00:00.000'

UPDATE #RECOMIS SET ACTYPE = BANKACTYPE FROM #RECOMIS A , ACCOUNT.DBO.BANK_MASTER_TYPE B 
WHERE A.CLTCODE = B.BANKCODE AND A.EXCHNAGE = B.EXCHANGE

SELECT *,BANKSOURCE=CONVERT(VARCHAR(50),'BILLDESK') INTO #BANKSOURCE FROM #RECOMIS WHERE VTYP=2 AND RECOSTATUS='UNRECONCILED' AND NARRATION='AMOUNT RECEIVED' 
UNION ALL
SELECT *,BANKSOURCE=CONVERT(VARCHAR(50),'BILLDESK') FROM #RECOMIS WHERE VTYP=2 AND RECOSTATUS='UNRECONCILED' AND NARRATION LIKE '%VIRTUAL%'

UPDATE #BANKSOURCE SET BANKSOURCE='VIRTUAL' WHERE CLTCODE='2093'
UPDATE #BANKSOURCE SET BANKSOURCE='DIRECT' WHERE CLTCODE IN ('05016','02086','03026','04040','04007')
UPDATE #BANKSOURCE SET BANKSOURCE='DIRECT' WHERE CLTCODE='02020' AND DDNO LIKE '21%'
--UPDATE #BANKSOURCE SET BANKSOURCE='HDFCUPI' WHERE CLTCODE='02020' AND DDNO LIKE '11%'
UPDATE #BANKSOURCE SET BANKSOURCE='HDFCUPI' WHERE CLTCODE='02020' AND DDNO LIKE '12%'
UPDATE #BANKSOURCE SET BANKSOURCE='ATOM' WHERE CLTCODE='04007' AND DDNO LIKE '11000%' AND LEN(DDNO)=14
UPDATE #BANKSOURCE SET BANKSOURCE='HDFCUPI' WHERE CLTCODE='04007' AND DDNO LIKE '11%' AND LEN(DDNO)=12
UPDATE #BANKSOURCE SET BANKSOURCE='DIRECT' WHERE CLTCODE='03014' AND LEN(DDNO)='10' AND DDNO LIKE '011%'
UPDATE #BANKSOURCE SET BANKSOURCE='DIRECT' WHERE CLTCODE='03014' AND LEN(DDNO)='10' AND DDNO LIKE '016%'
UPDATE #BANKSOURCE SET BANKSOURCE='ATOM' WHERE CLTCODE='03014' AND DDNO LIKE '11000%'
--UPDATE #BANKSOURCE SET BANKSOURCE='TECHPROCESS' WHERE CLTCODE='03014' AND LEN(DDNO)='10' AND DDNO LIKE '15%'
UPDATE #BANKSOURCE SET BANKSOURCE='TECHPROCESS' WHERE CLTCODE='03014' AND LEN(DDNO)='10' AND DDNO LIKE '17%'
UPDATE #BANKSOURCE SET BANKSOURCE='RAZORPAY' WHERE CLTCODE='03014' AND DDNO LIKE 'PAY%'


DECLARE @COLS1 AS NVARCHAR(MAX),@COLS2 AS NVARCHAR(MAX),@COLS3 AS NVARCHAR(MAX),@QUERY  AS NVARCHAR(MAX)

;with cte (datelist, maxdate) as
(select min(VDT) datelist, max(VDT) maxdate from #BANKSOURCE
union all
select dateadd(dd, 1, datelist), maxdate from cte WHERE datelist < maxdate) 
select c.datelist
INTO #TEMPDATES
from cte c
option (maxrecursion 0);


select @cols1 = STUFF((SELECT distinct ',' + QUOTENAME(CONVERT(VARCHAR(11), datelist, 105)) +'=ISNULL('+ QUOTENAME(CONVERT(VARCHAR(11), datelist, 105)) + ',0)' from #tempDates
FOR XML PATH(''), TYPE ).value('.', 'NVARCHAR(MAX)') ,1,1,'')

select @cols2 = STUFF((SELECT distinct ',' + QUOTENAME(CONVERT(VARCHAR(11), datelist, 105)) from #tempDates
FOR XML PATH(''), TYPE ).value('.', 'NVARCHAR(MAX)') ,1,1,'')

select @cols3 = STUFF((SELECT distinct '+' +'ISNULL('+ QUOTENAME(CONVERT(VARCHAR(11), datelist, 105)) + ',0)' FROM #tempDates
FOR XML PATH(''), TYPE ).value('.', 'NVARCHAR(MAX)') ,1,1,'')


set @query = 'SELECT BANKSOURCE, ' + @cols1 + ',GRAND_TOTAL= '+@cols3+' from 
         (
SELECT BANKSOURCE,VDT=CONVERT(VARCHAR(11),VDT,105),AMOUNT=ROUND(SUM(VAMT)/10000000,2) FROM #BANKSOURCE GROUP BY BANKSOURCE,CONVERT(VARCHAR(11),VDT,105)) AS SourceTable
        PIVOT 
         ( SUM(AMOUNT) for VDT in (' + @cols2 + ')) AS PivotTable 
		 UNION ALL
		 SELECT BANKSOURCE, ' + @cols1 + ',GRAND_TOTAL= '+@cols3+' from 
         (
SELECT BANKSOURCE=''TOTAL'',VDT=CONVERT(VARCHAR(11),VDT,105),AMOUNT=ROUND(SUM(VAMT)/10000000,2) FROM #BANKSOURCE GROUP BY CONVERT(VARCHAR(11),VDT,105)) AS SourceTable
        PIVOT 
         ( SUM(AMOUNT) for VDT in (' + @cols2 + ')) AS PivotTable'

EXECUTE(@QUERY)

-- SELECT * FROM #BANKSOURCE

GO
