-- Object: PROCEDURE dbo.DRCR_EXPORT
-- Server: 10.253.33.91 | DB: ACCOUNT
--------------------------------------------------


CREATE PROC [dbo].[DRCR_EXPORT] ( @TDATE [varchar](11))

AS

DECLARE @N AS VARCHAR(2) = '2'
DECLARE @path AS VARCHAR(200) =  'J:\BACKOFFICE\DRCRFILES'
DECLARE @deleteSql AS VARCHAR(512)
SET @deleteSql = 'forfiles /P "' + @path + '" /S /M *.* /D -' + @N + ' /C "cmd /c del @PATH"'

EXEC master.dbo.xp_cmdshell @deleteSql, NO_OUTPUT


DECLARE @DIRCOLLNAMEAM VARCHAR(100) = 'J:\BACKOFFICE\DRCRFILES\' +'CREDITORS_AM_' + CONVERT(VARCHAR(11),CONVERT(DATETIME,@TDATE),112) + '.CSV'

DECLARE @DIRCOLLSTMTAM NVARCHAR(4000) = 'EXEC [ACCOUNT].[DBO].[RPT_SFCM_CREDITOR_AM]  ''' + @TDATE + ''''

DECLARE @DIRCOLLBCPAM VARCHAR(4000) = 'BCP "' + @DIRCOLLSTMTAM + '" QUERYOUT "' + @DIRCOLLNAMEAM + '" -c -t"," -r"\n" -T'

EXEC MASTER..XP_CMDSHELL @DIRCOLLBCPAM, NO_OUTPUT


DECLARE @DIRCOLLNAMENZ VARCHAR(100) = 'J:\BACKOFFICE\DRCRFILES\' +'CREDITORS_NZ_' + CONVERT(VARCHAR(11),CONVERT(DATETIME,@TDATE),112) + '.CSV'

DECLARE @DIRCOLLSTMTNZ NVARCHAR(4000) = 'EXEC [ACCOUNT].[DBO].[RPT_SFCM_CREDITOR_NZ]  ''' + @TDATE + ''''

DECLARE @DIRCOLLBCPNZ VARCHAR(4000) = 'BCP "' + @DIRCOLLSTMTNZ + '" QUERYOUT "' + @DIRCOLLNAMENZ + '" -c -t"," -r"\n" -T'

EXEC MASTER..XP_CMDSHELL @DIRCOLLBCPNZ, NO_OUTPUT


DECLARE @DIRCOLLNAMEDRAM VARCHAR(100) = 'J:\BACKOFFICE\DRCRFILES\' +'DEBTORS_AM_' + CONVERT(VARCHAR(11),CONVERT(DATETIME,@TDATE),112) + '.CSV'

DECLARE @DIRCOLLSTMTDRAM NVARCHAR(4000) = 'EXEC [ACCOUNT].[DBO].[RPT_SFCM_DEBTORS_AM]  ''' + @TDATE + ''''

DECLARE @DIRCOLLBCPDRAM VARCHAR(4000) = 'BCP "' + @DIRCOLLSTMTDRAM + '" QUERYOUT "' + @DIRCOLLNAMEDRAM + '" -c -t"," -r"\n" -T'

EXEC MASTER..XP_CMDSHELL @DIRCOLLBCPDRAM, NO_OUTPUT


DECLARE @DIRCOLLNAMEDRNZ VARCHAR(100) = 'J:\BACKOFFICE\DRCRFILES\' +'DEBTORS_NZ_' + CONVERT(VARCHAR(11),CONVERT(DATETIME,@TDATE),112) + '.CSV'

DECLARE @DIRCOLLSTMTDRNZ NVARCHAR(4000) = 'EXEC [ACCOUNT].[DBO].[RPT_SFCM_DEBTORS_NZ]  ''' + @TDATE + ''''

DECLARE @DIRCOLLBCPDRNZ VARCHAR(4000) = 'BCP "' + @DIRCOLLSTMTDRNZ + '" QUERYOUT "' + @DIRCOLLNAMEDRNZ + '" -c -t"," -r"\n" -T'

EXEC MASTER..XP_CMDSHELL @DIRCOLLBCPDRNZ, NO_OUTPUT

GO
