-- Object: PROCEDURE dbo.RPT_FUNDS_PAYIN_PAYOUT
-- Server: 10.253.33.91 | DB: ACCOUNT
--------------------------------------------------

CREATE PROCEDURE [dbo].[RPT_FUNDS_PAYIN_PAYOUT] (@FDATE VARCHAR(11),@TDATE VARCHAR(11),@RPT VARCHAR(10)) 
AS  ---- EXEC RPT_FUNDS_PAYIN_PAYOUT 'APR  1 2021','SEP 20 2021','NSECD'
IF @RPT = 'BSECM'
BEGIN
SELECT VDT=CONVERT(VARCHAR(11),VDT,105),CLTCODE='99785', RECEIPTS=SUM(PAYMENTS),PAYMENTS=SUM(RECEIPTS),NETPAYINPAYOUT=SUM(PAYMENTS)-SUM(RECEIPTS),
EXCHANGE='BSECM' FROM (
SELECT VDT,RECEIPTS=CASE WHEN DRCR='D' THEN SUM(VAMT) ELSE 0 END,
PAYMENTS=CASE WHEN DRCR='C' THEN SUM(VAMT) ELSE 0 END
FROM AngelBSECM.ACCOUNT_AB.DBO.LEDGER WITH (NOLOCK) WHERE CLTCODE='99785' AND VTYP IN (2,3)
AND VDT BETWEEN @FDATE AND @TDATE + ' 23:59'
GROUP BY VDT,DRCR ) A GROUP BY VDT
ORDER BY 1
END

IF @RPT = 'NSECM'
BEGIN
SELECT VDT,CLTCODE='99985',RECEIPTS=SUM(PAYMENTS),PAYMENTS=SUM(RECEIPTS),NETPAYINPAYOUT=SUM(PAYMENTS)-SUM(RECEIPTS),
EXCHANGE='NSECM' FROM (
SELECT VDT=CONVERT(VARCHAR(11),VDT,105),RECEIPTS=CASE WHEN DRCR='D' THEN SUM(VAMT) ELSE 0 END,
PAYMENTS=CASE WHEN DRCR='C' THEN SUM(VAMT) ELSE 0 END
FROM LEDGER WITH (NOLOCK) WHERE CLTCODE='99985' AND VTYP IN (2,3)
AND VDT BETWEEN @FDATE AND @TDATE + ' 23:59'
GROUP BY CONVERT(VARCHAR(11),VDT,105),DRCR ) A GROUP BY VDT
ORDER BY 1
END

IF @RPT = 'NSEFO'
BEGIN
SELECT VDT,CLTCODE='99885',RECEIPTS=SUM(PAYMENTS),PAYMENTS=SUM(RECEIPTS),NETPAYINPAYOUT=SUM(PAYMENTS)-SUM(RECEIPTS),
EXCHANGE='NSEFO' FROM (
SELECT VDT=CONVERT(VARCHAR(11),VDT,105),RECEIPTS=CASE WHEN DRCR='D' THEN SUM(VAMT) ELSE 0 END,
PAYMENTS=CASE WHEN DRCR='C' THEN SUM(VAMT) ELSE 0 END
FROM ANGELFO.ACCOUNTFO.DBO.LEDGER WITH (NOLOCK) WHERE CLTCODE='99885' AND VTYP IN (2,3)
AND VDT BETWEEN @FDATE AND @TDATE + ' 23:59'
GROUP BY CONVERT(VARCHAR(11),VDT,105),DRCR ) A GROUP BY VDT
ORDER BY 1
END

IF @RPT = 'NSECD'
BEGIN
SELECT VDT,CLTCODE='99885',RECEIPTS=SUM(PAYMENTS),PAYMENTS=SUM(RECEIPTS),NETPAYINPAYOUT=SUM(PAYMENTS)-SUM(RECEIPTS),
EXCHANGE='NSECD' FROM (
SELECT VDT=CONVERT(VARCHAR(11),VDT,105),RECEIPTS=CASE WHEN DRCR='D' THEN SUM(VAMT) ELSE 0 END,
PAYMENTS=CASE WHEN DRCR='C' THEN SUM(VAMT) ELSE 0 END
FROM ANGELFO.ACCOUNTCURFO.DBO.LEDGER WITH (NOLOCK) WHERE CLTCODE='99885' AND VTYP IN (2,3)
AND VDT BETWEEN @FDATE AND @TDATE + ' 23:59'
GROUP BY CONVERT(VARCHAR(11),VDT,105),DRCR ) A GROUP BY VDT
UNION ALL
SELECT VDT,CLTCODE='99897',RECEIPTS=SUM(PAYMENTS),PAYMENTS=SUM(RECEIPTS),NETPAYINPAYOUT=SUM(PAYMENTS)-SUM(RECEIPTS),
EXCHANGE='NSECD' FROM (
SELECT VDT=CONVERT(VARCHAR(11),VDT,105),RECEIPTS=CASE WHEN DRCR='D' THEN SUM(VAMT) ELSE 0 END,
PAYMENTS=CASE WHEN DRCR='C' THEN SUM(VAMT) ELSE 0 END
FROM ANGELFO.ACCOUNTCURFO.DBO.LEDGER WITH (NOLOCK) WHERE CLTCODE='99897' AND VTYP IN (2,3)
AND VDT BETWEEN @FDATE AND @TDATE + ' 23:59'
GROUP BY CONVERT(VARCHAR(11),VDT,105),DRCR ) A GROUP BY VDT
UNION ALL
SELECT VDT,CLTCODE='99880',RECEIPTS=SUM(PAYMENTS),PAYMENTS=SUM(RECEIPTS),NETPAYINPAYOUT=SUM(PAYMENTS)-SUM(RECEIPTS),
EXCHANGE='NSECD' FROM (
SELECT VDT=CONVERT(VARCHAR(11),VDT,105),RECEIPTS=CASE WHEN DRCR='D' THEN SUM(VAMT) ELSE 0 END,
PAYMENTS=CASE WHEN DRCR='C' THEN SUM(VAMT) ELSE 0 END
FROM ANGELFO.ACCOUNTCURFO.DBO.LEDGER WITH (NOLOCK) WHERE CLTCODE='99880' AND VTYP IN (2,3)
AND VDT BETWEEN @FDATE AND @TDATE + ' 23:59'
GROUP BY CONVERT(VARCHAR(11),VDT,105),DRCR ) A GROUP BY VDT
ORDER BY 1
END

IF @RPT = 'MCDX'
BEGIN
SELECT VDT,CLTCODE='99885',RECEIPTS=SUM(PAYMENTS),PAYMENTS=SUM(RECEIPTS),NETPAYINPAYOUT=SUM(PAYMENTS)-SUM(RECEIPTS),
EXCHANGE='MCDX' FROM (
SELECT VDT=CONVERT(VARCHAR(11),VDT,105),RECEIPTS=CASE WHEN DRCR='D' THEN SUM(VAMT) ELSE 0 END,
PAYMENTS=CASE WHEN DRCR='C' THEN SUM(VAMT) ELSE 0 END
FROM ANGELCOMMODITY.ACCOUNTMCDX.DBO.LEDGER WITH (NOLOCK) WHERE CLTCODE='99885' AND VTYP IN (2,3)
AND VDT BETWEEN @FDATE AND @TDATE + ' 23:59'
GROUP BY CONVERT(VARCHAR(11),VDT,105),DRCR ) A GROUP BY VDT
ORDER BY 1
END

IF @RPT = 'NCDX'
BEGIN
SELECT VDT,CLTCODE='99885',RECEIPTS=SUM(PAYMENTS),PAYMENTS=SUM(RECEIPTS),NETPAYINPAYOUT=SUM(PAYMENTS)-SUM(RECEIPTS),
EXCHANGE='NCDX' FROM (
SELECT VDT=CONVERT(VARCHAR(11),VDT,105),RECEIPTS=CASE WHEN DRCR='D' THEN SUM(VAMT) ELSE 0 END,
PAYMENTS=CASE WHEN DRCR='C' THEN SUM(VAMT) ELSE 0 END
FROM ANGELCOMMODITY.ACCOUNTNCDX.DBO.LEDGER WITH (NOLOCK) WHERE CLTCODE='99885' AND VTYP IN (2,3)
AND  VDT BETWEEN @FDATE AND @TDATE + ' 23:59'
GROUP BY CONVERT(VARCHAR(11),VDT,105),DRCR ) A GROUP BY VDT
ORDER BY 1
END

GO
