-- Object: PROCEDURE dbo.RPT_CLOSE_CLIENT_LEDGER
-- Server: 10.253.33.91 | DB: ACCOUNT
--------------------------------------------------

CREATE PROCEDURE [dbo].[RPT_CLOSE_CLIENT_LEDGER] (@TDATE DATETIME)

AS ---- EXEC RPT_CLOSE_CLIENT_LEDGER 'MAR 11 2022'

DECLARE @FDATE VARCHAR(11)
SELECT @FDATE =SDTCUR FROM ACCOUNT.DBO.PARAMETER WHERE @TDATE BETWEEN SDTCUR AND LDTCUR

SELECT CL_CODE,CLOSEDATE=INACTIVE_FROM,VDT_LEDGER=CONVERT(MONEY,0),
CASE WHEN EXCHANGE='NSE' AND SEGMENT='CAPITAL' THEN 'NSECM' WHEN EXCHANGE='BSE' AND SEGMENT='CAPITAL' THEN 'BSECM'
	 WHEN EXCHANGE='NSE' AND SEGMENT='FUTURES' THEN 'NSEFO' WHEN EXCHANGE='BSE' AND SEGMENT='FUTURES' THEN 'BSEFO'
	 WHEN EXCHANGE='NSE' AND SEGMENT='FUTURES' THEN 'NSEFO' WHEN EXCHANGE='BSE' AND SEGMENT='FUTURES' THEN 'BSEFO'
	 WHEN EXCHANGE='NCX' AND SEGMENT='FUTURES' THEN 'NSECD' WHEN EXCHANGE='BSX' AND SEGMENT='FUTURES' THEN 'BSECD'
	 WHEN EXCHANGE='MCD' AND SEGMENT='FUTURES' THEN 'MCXCD' WHEN EXCHANGE='NSE' AND SEGMENT='SLBS' THEN 'SLBS'
	 WHEN EXCHANGE='MCX' AND SEGMENT='FUTURES' THEN 'MCDX' WHEN EXCHANGE='NCX' AND SEGMENT='FUTURES' THEN 'NCDX' END AS CLOSESEGMENTS INTO #CLTCLOSE
FROM MSAJAG.DBO.CLIENT_BROK_DETAILS
WHERE INACTIVE_FROM BETWEEN 'OCT  1 2021' AND GETDATE () AND DEACTIVE_VALUE='C'
ORDER BY CL_CODE,CLOSESEGMENTS

CREATE CLUSTERED INDEX IDXCOL1 ON #CLTCLOSE (CLOSESEGMENTS,CL_CODE)


SELECT CLTCODE,NETAMT=SUM(CASE WHEN DRCR='D' THEN -VAMT ELSE VAMT END),EXCHANGE='NSECM' INTO #VDTLED                  
FROM ACCOUNT.DBO.LEDGER WITH (NOLOCK) WHERE VDT >=@FDATE AND VDT <=@TDATE  + ' 23:59' 
AND CLTCODE IN (SELECT CL_CODE FROM #CLTCLOSE)
GROUP BY CLTCODE

INSERT INTO #VDTLED
SELECT CLTCODE,NETAMT=SUM(CASE WHEN DRCR='D' THEN -VAMT ELSE VAMT END),EXCHANGE='BSECM'                  
FROM AngelBSECM.ACCOUNT_AB.DBO.LEDGER WITH (NOLOCK) WHERE VDT >=@FDATE AND VDT <=@TDATE  + ' 23:59' 
AND CLTCODE IN (SELECT CL_CODE FROM #CLTCLOSE)
GROUP BY CLTCODE

INSERT INTO #VDTLED
SELECT CLTCODE,NETAMT=SUM(CASE WHEN DRCR='D' THEN -VAMT ELSE VAMT END),EXCHANGE='NSEFO'                  
FROM ANGELFO.ACCOUNTFO.DBO.LEDGER WITH (NOLOCK) WHERE VDT >=@FDATE AND VDT <=@TDATE  + ' 23:59' 
AND CLTCODE IN (SELECT CL_CODE FROM #CLTCLOSE)
GROUP BY CLTCODE

INSERT INTO #VDTLED
SELECT CLTCODE,NETAMT=SUM(CASE WHEN DRCR='D' THEN -VAMT ELSE VAMT END),EXCHANGE='BSEFO'                  
FROM ANGELCOMMODITY.ACCOUNTBFO.DBO.LEDGER WITH (NOLOCK) WHERE VDT >=@FDATE AND VDT <=@TDATE  + ' 23:59' 
AND CLTCODE IN (SELECT CL_CODE FROM #CLTCLOSE)
GROUP BY CLTCODE

INSERT INTO #VDTLED
SELECT CLTCODE,NETAMT=SUM(CASE WHEN DRCR='D' THEN -VAMT ELSE VAMT END),EXCHANGE='MTF'                  
FROM MTFTRADE.DBO.LEDGER WITH (NOLOCK) WHERE VDT >=@FDATE AND VDT <=@TDATE  + ' 23:59' 
AND CLTCODE IN (SELECT CL_CODE FROM #CLTCLOSE)
GROUP BY CLTCODE

INSERT INTO #VDTLED
SELECT CLTCODE,OPPBAL=SUM(DRAMOUNT+CRAMOUNT),EXCHANGE='BSEMF' FROM (
SELECT B.CLTCODE,EXCHANGE,A.VTYPE,A.VNO,B.EDT,DRAMOUNT=(-B.DRAMOUNT),B.CRAMOUNT
FROM ANGELFO.BBO_FA.DBO.ACC_TBL1 A (NOLOCK), ANGELFO.BBO_FA.DBO.ACC_TBL3 B (NOLOCK)
WHERE A.SNO = B.MASTERSNO  AND CONVERT(DATETIME,CONVERT(VARCHAR(11),VDT)) BETWEEN @FDATE AND @TDATE + ' 23:59:59' ) B 
WHERE CLTCODE IN (SELECT CL_CODE FROM #CLTCLOSE)
GROUP BY CLTCODE

INSERT INTO #VDTLED
SELECT CLTCODE,NETAMT=SUM(CASE WHEN DRCR='D' THEN -VAMT ELSE VAMT END),EXCHANGE='NSECD'                  
FROM ANGELFO.ACCOUNTCURFO.DBO.LEDGER WITH (NOLOCK) WHERE VDT >=@FDATE AND VDT <=@TDATE  + ' 23:59' 
AND CLTCODE IN (SELECT CL_CODE FROM #CLTCLOSE)
GROUP BY CLTCODE

INSERT INTO #VDTLED
SELECT CLTCODE,NETAMT=SUM(CASE WHEN DRCR='D' THEN -VAMT ELSE VAMT END),EXCHANGE='BSECD'                  
FROM ANGELCOMMODITY.ACCOUNTCURBFO.DBO.LEDGER WITH (NOLOCK) WHERE VDT >=@FDATE AND VDT <=@TDATE  + ' 23:59' 
AND CLTCODE IN (SELECT CL_CODE FROM #CLTCLOSE)
GROUP BY CLTCODE

INSERT INTO #VDTLED
SELECT CLTCODE,NETAMT=SUM(CASE WHEN DRCR='D' THEN -VAMT ELSE VAMT END),EXCHANGE='MCXCD'                  
FROM ANGELCOMMODITY.ACCOUNTMCDXCDS.DBO.LEDGER WITH (NOLOCK) WHERE VDT >=@FDATE AND VDT <=@TDATE  + ' 23:59' 
AND CLTCODE IN (SELECT CL_CODE FROM #CLTCLOSE)
GROUP BY CLTCODE

INSERT INTO #VDTLED
SELECT CLTCODE,NETAMT=SUM(CASE WHEN DRCR='D' THEN -VAMT ELSE VAMT END),EXCHANGE='SLBS'                  
FROM ACCOUNTSLBS.DBO.LEDGER WITH (NOLOCK) WHERE VDT >=@FDATE AND VDT <=@TDATE  + ' 23:59' 
AND CLTCODE IN (SELECT CL_CODE FROM #CLTCLOSE)
GROUP BY CLTCODE

INSERT INTO #VDTLED
SELECT CLTCODE,NETAMT=SUM(CASE WHEN DRCR='D' THEN -VAMT ELSE VAMT END),EXCHANGE='MCDX'                  
FROM ANGELCOMMODITY.ACCOUNTMCDX.DBO.LEDGER WITH (NOLOCK) WHERE VDT >=@FDATE AND VDT <=@TDATE  + ' 23:59' 
AND CLTCODE IN (SELECT CL_CODE FROM #CLTCLOSE)
GROUP BY CLTCODE

INSERT INTO #VDTLED
SELECT CLTCODE,NETAMT=SUM(CASE WHEN DRCR='D' THEN -VAMT ELSE VAMT END),EXCHANGE='NCDX'                  
FROM ANGELCOMMODITY.ACCOUNTNCDX.DBO.LEDGER WITH (NOLOCK) WHERE VDT >=@FDATE AND VDT <=@TDATE  + ' 23:59' 
AND CLTCODE IN (SELECT CL_CODE FROM #CLTCLOSE)
GROUP BY CLTCODE

UPDATE #CLTCLOSE SET VDT_LEDGER = NETAMT FROM #CLTCLOSE A, #VDTLED B WHERE A.Cl_Code = B.CLTCODE AND A.CLOSESEGMENTS = B.EXCHANGE

SELECT CL_CODE,
STUFF((SELECT DISTINCT '-' + CAST(T2.CLOSESEGMENTS AS VARCHAR(10)) FROM #CLTCLOSE T2 WHERE T2.CL_CODE = T1.CL_CODE FOR XML PATH('')),1,1,'') AS CLOSESEGMENTS,
MAX(CLOSEDATE) AS CLOSEDATE INTO #CLTCLOSE_DATA
FROM #CLTCLOSE T1 WHERE T1.VDT_LEDGER <> 0
GROUP BY CL_CODE

SELECT REPORT_DATE=CONVERT(VARCHAR(11),@TDATE,105),CLTCODE,[NSECM]=ISNULL([NSECM],0),[BSECM]=ISNULL([BSECM],0),[NSEFO]=ISNULL([NSEFO],0),[BSEFO]=ISNULL([BSEFO],0),[BSEMF]=ISNULL([BSEMF],0),
[MTF]=ISNULL([MTF],0),[SLBS]=ISNULL([SLBS],0),[NSECD]=ISNULL([NSECD],0),[BSECD]=ISNULL([BSECD],0),[MCXCD]=ISNULL([MCXCD],0),
[MCDX]=ISNULL([MCDX],0),[NCDX]=ISNULL([NCDX],0),OS_CHARGES=CONVERT(MONEY,0),
NET_BALANCE=ISNULL([NSECM],0)+ISNULL([BSECM],0)+ISNULL([NSEFO],0)+ISNULL([BSEFO],0)+ISNULL([BSEMF],0)+ISNULL([MTF],0)+ISNULL([SLBS],0)+ISNULL([NSECD],0)
+ISNULL([BSECD],0)+ISNULL([MCXCD],0)+ISNULL([MCDX],0)+ISNULL([NCDX],0),CLOSE_SEGMENTS=CONVERT(VARCHAR(100),''),CLOSE_DATE=CONVERT(VARCHAR(15),'') INTO #LED
FROM ( SELECT CLTCODE,NETAMT=ROUND(NETAMT,2),EXCHANGE FROM #VDTLED WHERE CLTCODE IN (SELECT CL_CODE FROM #CLTCLOSE_DATA)) AS SourceTable
PIVOT
(SUM(NETAMT) FOR EXCHANGE IN ([NSECM],[BSECM],[NSEFO],[BSEFO],[BSEMF],[MTF],[SLBS],[NSECD],[BSECD],[MCXCD],[MCDX],[NCDX])) AS PivotTable
ORDER BY PivotTable.CLTCODE

UPDATE #LED SET CLOSE_SEGMENTS = CLOSESEGMENTS, CLOSE_DATE = CONVERT(VARCHAR(11),CLOSEDATE,105) FROM #LED A, #CLTCLOSE_DATA B WHERE A.CLTCODE = B.CL_CODE

/*
DELETE FROM #LED WHERE (NSECM IS NULL OR NSECM=0) AND CLOSE_SEGMENTS='NSECM' ---LIKE '%NSECM%'
DELETE FROM #LED WHERE (BSECM IS NULL OR BSECM=0) AND CLOSE_SEGMENTS='BSECM' ---LIKE '%BSECM%'

DELETE FROM #LED WHERE (BSEFO IS NULL OR BSEFO=0) AND CLOSE_SEGMENTS='BSEFO' ---LIKE '%BSEFO%'
DELETE FROM #LED WHERE (NSEFO IS NULL OR NSEFO=0) AND CLOSE_SEGMENTS='NSEFO' ---LIKE '%NSEFO%'

DELETE FROM #LED WHERE (NSECD IS NULL OR NSECD=0) AND CLOSE_SEGMENTS='NSECD' ---LIKE '%NSECD%'
DELETE FROM #LED WHERE (BSECD IS NULL OR BSECD=0) AND CLOSE_SEGMENTS='BSECD' ---LIKE '%BSECD%'
DELETE FROM #LED WHERE (MCXCD IS NULL OR MCXCD=0) AND CLOSE_SEGMENTS='MCXCD' ---LIKE '%MCXCD%'

DELETE FROM #LED WHERE (MCDX IS NULL OR MCDX=0) AND CLOSE_SEGMENTS='MCDX' ---LIKE '%MCDX%'
DELETE FROM #LED WHERE (NCDX IS NULL OR NCDX=0) AND CLOSE_SEGMENTS='NCDX' ---LIKE '%NCDX%'

DELETE FROM #LED WHERE NSECM=0 AND BSECM=0 AND NSEFO=0 AND BSEFO=0 AND BSEMF=0 AND MTF=0 AND SLBS=0 AND NSECD=0 AND BSECD=0 AND MCXCD=0 AND MCDX=0 AND NCDX=0
*/

SELECT PARTY_CODE,OST_CHARGES=ROUND(SUM(CHARGES_AMT),2) INTO #OSCHRG 
FROM INTRANET.[MISC].[DBO].CLI_ACCCHARGES A
WHERE UPDATED_ON > = LEFT(GETDATE(),11) AND PARTY_CODE IN (SELECT CLTCODE FROM #LED )
GROUP BY PARTY_CODE

UPDATE A SET OS_CHARGES = OST_CHARGES FROM #LED A, #OSCHRG B WHERE A.CLTCODE = B.PARTY_CODE

DELETE FROM #LED WHERE CLTCODE IN ('AL57627','05SDIH')

SELECT 'REPORT_DATE','CLTCODE','NSECM','BSECM','NSEFO','BSEFO','BSEMF','MTF','SLBS','NSECD',
'BSECD','MCXCD','MCDX','NCDX','OS_CHARGES','NET_BALANCE','CLOSE_SEGMENTS','CLOSE_DATE'
UNION ALL
SELECT REPORT_DATE,CLTCODE,CONVERT(VARCHAR,NSECM),CONVERT(VARCHAR,BSECM),CONVERT(VARCHAR,NSEFO),
CONVERT(VARCHAR,BSEFO),CONVERT(VARCHAR,BSEMF),CONVERT(VARCHAR,MTF),CONVERT(VARCHAR,SLBS),
CONVERT(VARCHAR,NSECD),CONVERT(VARCHAR,BSECD),CONVERT(VARCHAR,MCXCD),CONVERT(VARCHAR,MCDX),CONVERT(VARCHAR,NCDX),
CONVERT(VARCHAR,OS_CHARGES),CONVERT(VARCHAR,NET_BALANCE-OS_CHARGES),CLOSE_SEGMENTS,CLOSE_DATE
FROM #LED WHERE NET_BALANCE <> 0

GO
