-- Object: PROCEDURE dbo.sebiaudit
-- Server: 10.253.33.91 | DB: ACCOUNT
--------------------------------------------------




  
CREATE PROC [dbo].[sebiaudit]          
(      
 @REPORTDATE VARCHAR(11)      
)      
AS          
DECLARE @NSEMEMBERCODE VARCHAR(10),      
  @BSEMEMBERCODE VARCHAR(10)      
      
SELECT @NSEMEMBERCODE = MEMBERCODE FROM MSAJAG.DBO.OWNER      
SELECT @BSEMEMBERCODE = MEMBERCODE FROM [AngelBSECM].BSEDB_AB.DBO.OWNER      
    
INSERT INTO SEBI_EXCEP_PARTY    
SELECT CL_CODE FROM MSAJAG.DBO.CLIENT1 with(nolock) WHERE CL_TYPE IN ('PRO','BAF','BAO','REM','IFA')    
AND CL_CODE NOT IN (SELECT MEMBERCODE FROM MSAJAG.DBO.OWNER with(nolock)    
     UNION      
     SELECT MEMBERCODE FROM [AngelBSECM].BSEDB_AB.DBO.OWNER with(nolock))    
AND CL_CODE NOT IN (SELECT PARTY_CODE FROM SEBI_EXCEP_PARTY)     
         
CREATE TABLE #TBL_EXCHG_REPORT_TEMP          
(          
 EFFDATE    DATETIME,          
 BANK_BALANCE  NUMERIC(18,2),          
 EXCHG_CASH_COLL  NUMERIC(18,2),          
 CREDITOR_BALANCE NUMERIC(18,2),          
 DEBTOR_BALANCE  NUMERIC(18,2),          
 EXCHG_NONCASH_COLL NUMERIC(18,2),          
 NON_FUNDED_BG  NUMERIC(18,2),          
 PROP_MARGIN_OBL  NUMERIC(18,2),          
 CREDITOR_MARGIN_UTL NUMERIC(18,2),          
 UNUTL_COLLATERAL NUMERIC(18,2),          
 TOTAL_FUND   NUMERIC(18,2),          
 CLIENT_FUND_UTL  NUMERIC(18,2),          
 FUND_BY_OWN   NUMERIC(18,2),          
 PROCESS_DATE  DATETIME           
)          
          
CREATE TABLE #TBL_EXCHG_REPORT          
(          
 EFFDATE    DATETIME,          
 BANK_BALANCE  NUMERIC(18,2),          
 EXCHG_CASH_COLL  NUMERIC(18,2),          
 CREDITOR_BALANCE NUMERIC(18,2),          
 DEBTOR_BALANCE  NUMERIC(18,2),          
 EXCHG_NONCASH_COLL NUMERIC(18,2),          
 NON_FUNDED_BG  NUMERIC(18,2),          
 PROP_MARGIN_OBL  NUMERIC(18,2),          
 CREDITOR_MARGIN_UTL NUMERIC(18,2),          
 UNUTL_COLLATERAL NUMERIC(18,2),          
 TOTAL_FUND   NUMERIC(18,2),          
 CLIENT_FUND_UTL  NUMERIC(18,2),          
 FUND_BY_OWN   NUMERIC(18,2),          
 PROCESS_DATE  DATETIME           
)          
          
DECLARE @FROMDATE DATETIME          
          
SET @FROMDATE = @REPORTDATE      
          
INSERT INTO #TBL_EXCHG_REPORT_TEMP (EFFDATE, BANK_BALANCE)          
SELECT @FROMDATE, AMOUNT = SUM(BANK_BALANCE)           
FROM TBL_BANK_BALANCE with(nolock)          
WHERE EFF_DATE = @FROMDATE          
          
INSERT INTO #TBL_EXCHG_REPORT_TEMP (EFFDATE, UNUTL_COLLATERAL)          
SELECT @FROMDATE, AMOUNT = SUM(UNUTL_FUND_AMT)           
FROM TBL_EXCHGBAL_DATA with(nolock)          
WHERE EFF_DATE = @FROMDATE          
    
SELECT C.* INTO #COLL_MEMBER    
FROM MSAJAG.DBO.COLLATERALDETAILS C (NOLOCK), MSAJAG.DBO.CLIENT_DETAILS D (NOLOCK)          
WHERE EFFDATE = @REPORTDATE      
AND C.PARTY_CODE = D.CL_CODE          
--AND CL_TYPE = 'PRO'          
AND C.PARTY_CODE  IN (@NSEMEMBERCODE, @BSEMEMBERCODE)       
    
UPDATE #COLL_MEMBER SET COLL_TYPE = 'MARGIN'    
WHERE ISIN IN (SELECT ISIN FROM MSAJAG.DBO.EXCHG_CASH_ISIN     
    WHERE @REPORTDATE BETWEEN FROMDATE AND TODATE)    
          
SELECT           
CASHCOLL = SUM(CASE WHEN COLL_TYPE NOT IN ('SEC') THEN FINALAMOUNT ELSE 0 END),           
BG_ORG_FUND = SUM(CASE WHEN COLL_TYPE IN ('FD', 'BG') THEN FINALAMOUNT ELSE 0 END),           
NONCASHCOLL = SUM(CASE WHEN COLL_TYPE = 'SEC' THEN FINALAMOUNT ELSE 0 END),           
BGNO  = FD_BG_NO,          
COLL_TYPE          
INTO #COLLDATA          
FROM #COLL_MEMBER      
GROUP BY FD_BG_NO, COLL_TYPE           
          
UPDATE #COLLDATA SET BG_ORG_FUND = BANK_FUND_AMT           
FROM TBL_BGDATA B with(nolock)          
WHERE @REPORTDATE BETWEEN FROMDATE AND TODATE          
AND #COLLDATA.BGNO = B.BGNO          
AND COLL_TYPE = 'BG'          
          
INSERT INTO #TBL_EXCHG_REPORT_TEMP (EFFDATE, EXCHG_CASH_COLL, NON_FUNDED_BG)          
SELECT @FROMDATE,           
EXCHG_CASH_COLL = SUM(CASE WHEN COLL_TYPE = 'BG' THEN BG_ORG_FUND ELSE CASHCOLL END),          
NON_FUNDED_BG = SUM(CASE WHEN COLL_TYPE = 'BG' THEN CASHCOLL - BG_ORG_FUND ELSE 0 END)           
FROM #COLLDATA           
          
INSERT INTO #TBL_EXCHG_REPORT_TEMP (EFFDATE, EXCHG_NONCASH_COLL)          
SELECT @FROMDATE, AMOUNT = SUM(NONCASHCOLL)           
FROM #COLLDATA           
WHERE COLL_TYPE = 'SEC'          
          
SELECT PARTY_CODE, AMOUNT = ISNULL(TOTAL_VDTBAL,0)           
        - ISNULL(TOTAL_OPENBILL,0)            
        - ISNULL(TOTAL_DEPOSITS,0)           
        + ISNULL(TOTAL_ISSUE,0),          
       MARGIN_REQ = ISNULL(TOTAL_MARGIN,0),          
       CL_TYPE          
INTO #LEDDATA          
FROM ACCOUNT.DBO.FINAL_AUDIT_DATA          
WHERE EFFDATE = @REPORTDATE          
           
INSERT INTO #LEDDATA          
SELECT C.PARTY_CODE, AMOUNT = SUM(FINALAMOUNT), 0, D.CL_TYPE          
FROM MSAJAG.DBO.COLLATERALDETAILS C (NOLOCK), MSAJAG.DBO.CLIENT_DETAILS D (NOLOCK)          
WHERE EFFDATE = @REPORTDATE          
AND C.PARTY_CODE = D.CL_CODE          
AND COLL_TYPE = 'MARGIN'          
AND C.PARTY_CODE NOT IN (@NSEMEMBERCODE, @BSEMEMBERCODE)      
AND D.CL_TYPE <> 'PRO'      
AND C.PARTY_CODE NOT IN (SELECT PARTY_CODE FROM SEBI_EXCEP_PARTY)      
GROUP BY C.PARTY_CODE, CL_TYPE          
          
INSERT INTO #LEDDATA          
SELECT C.PARTY_CODE, AMOUNT = SUM(FINALAMOUNT), 0, D.CL_TYPE          
FROM MSAJAG.DBO.COLLATERALDETAILS C (NOLOCK), MSAJAG.DBO.CLIENT1 D (NOLOCK)          
WHERE EFFDATE = @REPORTDATE          
AND C.PARTY_CODE = D.CL_CODE          
AND COLL_TYPE = 'MARGIN'          
AND D.CL_TYPE <> 'PRO'      
AND C.PARTY_CODE NOT IN (SELECT PARTY_CODE FROM SEBI_EXCEP_PARTY)      
AND NOT EXISTS (SELECT CL_CODE FROM MSAJAG.DBO.CLIENT_DETAILS D1 (NOLOCK) WHERE D.CL_CODE = D1.CL_CODE)          
GROUP BY C.PARTY_CODE, CL_TYPE          
          
SELECT PARTY_CODE,           
    CREDITOR_BALANCE = (CASE WHEN SUM(AMOUNT) >= 0 THEN SUM(AMOUNT) ELSE 0 END),          
    DEBTOR_BALANCE = (CASE WHEN SUM(AMOUNT) < 0 THEN ABS(SUM(AMOUNT)) ELSE 0 END),          
    CL_TYPE = MAX(CL_TYPE)           
INTO #LEDBAL          
FROM #LEDDATA           
WHERE PARTY_CODE NOT IN (@NSEMEMBERCODE, @BSEMEMBERCODE)      
AND CL_TYPE <> 'PRO'      
AND PARTY_CODE NOT IN (SELECT PARTY_CODE FROM SEBI_EXCEP_PARTY)      
GROUP BY PARTY_CODE          
/*  
select * into bak_sebi_data_sum  
from #LEDDATA  
WHERE PARTY_CODE NOT IN (@NSEMEMBERCODE, @BSEMEMBERCODE)      
AND CL_TYPE <> 'PRO'      
AND PARTY_CODE NOT IN (SELECT PARTY_CODE FROM SEBI_EXCEP_PARTY)      
*/          
INSERT INTO #TBL_EXCHG_REPORT_TEMP (EFFDATE, CREDITOR_MARGIN_UTL)          
SELECT @FROMDATE,           
    CREDITOR_MARGIN_UTL = SUM(MARGIN_REQ)           
FROM #LEDDATA           
WHERE EXISTS (SELECT PARTY_CODE FROM #LEDBAL           
     WHERE #LEDBAL.PARTY_CODE = #LEDDATA.PARTY_CODE AND CREDITOR_BALANCE >= 0 AND DEBTOR_BALANCE = 0)          
AND PARTY_CODE NOT IN (@NSEMEMBERCODE, @BSEMEMBERCODE)      
AND CL_TYPE <> 'PRO'       
AND PARTY_CODE NOT IN (SELECT PARTY_CODE FROM SEBI_EXCEP_PARTY)      
          
INSERT INTO #TBL_EXCHG_REPORT_TEMP (EFFDATE, PROP_MARGIN_OBL)          
SELECT @FROMDATE,           
    PROP_MARGIN_OBL = SUM(MARGIN_REQ)           
FROM #LEDDATA           
WHERE PARTY_CODE  IN (@NSEMEMBERCODE, @BSEMEMBERCODE)      
          
INSERT INTO #TBL_EXCHG_REPORT_TEMP (EFFDATE, CREDITOR_BALANCE, DEBTOR_BALANCE)          
SELECT @FROMDATE,           
    CREDITOR_BALANCE = SUM(CREDITOR_BALANCE),          
    DEBTOR_BALANCE = SUM(DEBTOR_BALANCE)          
FROM #LEDBAL          
WHERE PARTY_CODE NOT IN (SELECT PARTY_CODE FROM SEBI_EXCEP_PARTY)      
/*    
SELECT * INTO BAK_LEDDATA_SUM   FROM #LEDBAL      
WHERE PARTY_CODE NOT IN (SELECT PARTY_CODE FROM SEBI_EXCEP_PARTY)      
*/        
INSERT INTO #TBL_EXCHG_REPORT          
SELECT EFFDATE,BANK_BALANCE=SUM(ISNULL(BANK_BALANCE,0)),EXCHG_CASH_COLL=SUM(ISNULL(EXCHG_CASH_COLL,0)),          
    CREDITOR_BALANCE=SUM(ISNULL(CREDITOR_BALANCE,0)),DEBTOR_BALANCE=SUM(ISNULL(DEBTOR_BALANCE,0)),          
    EXCHG_NONCASH_COLL=SUM(ISNULL(EXCHG_NONCASH_COLL,0)),NON_FUNDED_BG=SUM(ISNULL(NON_FUNDED_BG,0)),          
    PROP_MARGIN_OBL=SUM(ISNULL(PROP_MARGIN_OBL,0)),CREDITOR_MARGIN_UTL=SUM(ISNULL(CREDITOR_MARGIN_UTL,0)),          
    UNUTL_COLLATERAL=SUM(ISNULL(UNUTL_COLLATERAL,0)),TOTAL_FUND=SUM(ISNULL(TOTAL_FUND,0)),          
    CLIENT_FUND_UTL=SUM(ISNULL(CLIENT_FUND_UTL,0)),FUND_BY_OWN=SUM(ISNULL(FUND_BY_OWN,0)),          
    PROCESS_DATE=GETDATE()          
FROM   #TBL_EXCHG_REPORT_TEMP          
GROUP BY EFFDATE          
          
UPDATE #TBL_EXCHG_REPORT SET TOTAL_FUND = BANK_BALANCE + EXCHG_CASH_COLL - CREDITOR_BALANCE          
          
UPDATE #TBL_EXCHG_REPORT SET           
CLIENT_FUND_UTL = (CASE WHEN ABS(TOTAL_FUND) < DEBTOR_BALANCE THEN TOTAL_FUND ELSE 0 END)          
WHERE TOTAL_FUND < 0          
          
UPDATE #TBL_EXCHG_REPORT SET           
FUND_BY_OWN = (CASE WHEN TOTAL_FUND > DEBTOR_BALANCE THEN TOTAL_FUND - DEBTOR_BALANCE ELSE 0 END)          
WHERE TOTAL_FUND >= 0          
          
SELECT EFFDATE,BANK_BALANCE,EXCHG_CASH_COLL,CREDITOR_BALANCE,DEBTOR_BALANCE,          
    EXCHG_NONCASH_COLL,NON_FUNDED_BG,PROP_MARGIN_OBL,CREDITOR_MARGIN_UTL,          
    UNUTL_COLLATERAL,TOTAL_FUND           
FROM #TBL_EXCHG_REPORT           
          
DROP TABLE #TBL_EXCHG_REPORT_TEMP          
DROP TABLE #TBL_EXCHG_REPORT          
DROP TABLE #COLLDATA          
DROP TABLE #LEDDATA          
DROP TABLE #LEDBAL

GO
