-- Object: PROCEDURE dbo.EXPCETIONAL_EDT_REPORT
-- Server: 10.253.33.91 | DB: ACCOUNT
--------------------------------------------------


CREATE PROCEDURE [dbo].[EXPCETIONAL_EDT_REPORT] (@EDTDATE DATETIME)

AS ---- EXEC EXPCETIONAL_EDT_REPORT 'MAY 06 2022'

SELECT A.CLTCODE,BANKCODE=CONVERT(VARCHAR(20),''),BANK_NAME=CONVERT(VARCHAR(MAX),''),
A.VDT,A.EDT,RELDATE=CONVERT(DATETIME,''),A.VNO,A.VTYP,DDNO=CONVERT(VARCHAR(500),''),
A.DRCR,A.VAMT,A.CDT,A.ENTEREDBY,A.CHECKEDBY,A.NARRATION INTO #EDTRPT
FROM LEDGER A WITH (NOLOCK), MSAJAG.DBO.CLIENT_DETAILS B WITH (NOLOCK)
WHERE A.CLTCODE = B.CL_CODE
AND VDT > = @EDTDATE-7 AND VDT  < = @EDTDATE + ' 23:59:59' AND RIGHT(LEFT(EDT,11),4) = '2049'
AND A.VTYP IN (3,2) AND A.ENTEREDBY NOT IN ('TPR','B_TPR','B_KYC','TPR1','PMTGATEWAY')

UPDATE #EDTRPT SET BANKCODE = B.CLTCODE, BANK_NAME = B.ACNAME FROM #EDTRPT A, LEDGER B WITH (NOLOCK)
WHERE A.VNO = B.VNO AND A.VTYP = B.VTYP AND A.VAMT = B.VAMT AND A.CLTCODE <>  B.CLTCODE

UPDATE #EDTRPT SET RELDATE = B.reldt, DDNO= B.ddno FROM #EDTRPT A, LEDGER1 B WITH (NOLOCK)
WHERE A.VNO = B.VNO AND A.VTYP = B.VTYP AND A.VAMT = B.relamt

SELECT * FROM #EDTRPT ORDER BY VNO

GO
