-- Object: PROCEDURE dbo.BANK_FUNDS_REPORTING_BKUP_01JAN2019
-- Server: 10.253.33.91 | DB: ACCOUNT
--------------------------------------------------





--EXEC BANK_FUNDS_REPORTING 'APR  1 2013', 'NOV 27 2013', 'BANK01'

CREATE PROCEDURE [dbo].[BANK_FUNDS_REPORTING_BKUP_01JAN2019]
	@FR_DATE VARCHAR(11),
	@TO_DATE VARCHAR(11),
	@BANK_CODE VARCHAR(10)
AS

CREATE TABLE #LEDGER_PL
(
	VDT DATETIME,
	EDT DATETIME,
	LONG_NAME VARCHAR(100),
	BANK_ACC_NO VARCHAR(30),
	UCC_CODE VARCHAR(10),
	CLTCODE VARCHAR(10),
	CLIENT_PAN VARCHAR(30),
	NARRATION VARCHAR(500),
	VNO VARCHAR(12),
	SETT_NO VARCHAR(10),
	CHQ_NO VARCHAR(30),
	DRAMOUNT MONEY,
	CRAMOUNT MONEY,
	RUNNING_BALANCE MONEY,
	EXCHANGE VARCHAR(10),
	SEGMENT VARCHAR(10),
	VTYP INT,
	BOOKTYPE VARCHAR(3),
	PDT DATETIME,
	OPBAL MONEY
)

INSERT INTO #LEDGER_PL
SELECT
	VDT, EDT, LONG_NAME, ACCNO, UCC_CODE, CL_CODE, PAN_GIR_NO, NARRATION = L.NARRATION, VNO, SETT_NO = '', CHQ_NO = '',  
	DRAMOUNT = CASE WHEN DRCR = 'D' THEN VAMT ELSE 0 END,
	CRAMOUNT = CASE WHEN DRCR = 'C' THEN VAMT ELSE 0 END, 0, EXCHANGE, SEGMENT, L.VTYP, L.BOOKTYPE, PDT, OPBAL = 0
FROM
	MSAJAG..CLIENT_DETAILS C, (SELECT CLTCODE, VAMT, DRCR, NARRATION, VDT, EDT, PDT, VTYP, VNO, BOOKTYPE FROM LEDGER WHERE VDT BETWEEN @FR_DATE AND @TO_DATE + ' 23:59') L, VMAST V, OWNER O, MULTIBANKID M
WHERE
	C.CL_CODE = L.CLTCODE
	AND C.CL_CODE = M.CLTCODE
	AND L.VTYP = V.VTYPE
	AND EXISTS(SELECT VNO FROM LEDGER LL WHERE VDT BETWEEN @FR_DATE AND @TO_DATE + ' 23:59' AND CLTCODE = @BANK_CODE AND L.VNO = LL.VNO AND L.VTYP = LL.VTYP AND L.BOOKTYPE = LL.BOOKTYPE)
	AND L.CLTCODE <> @BANK_CODE
ORDER BY L.CLTCODE, CONVERT(DATETIME, CONVERT(VARCHAR(11), VDT, 109)), PDT

UPDATE L SET L.CHQ_NO = L1.DDNO FROM #LEDGER_PL L, LEDGER1 L1
WHERE L.VNO = L1.VNO AND L.VTYP = L1.VTYP AND L.BOOKTYPE = L1.BOOKTYPE

UPDATE L SET L.SETT_NO = L1.SETT_NO FROM #LEDGER_PL L, BILLPOSTED L1
WHERE L.VNO = L1.VNO AND L.VTYP = L1.VTYP AND L.BOOKTYPE = L1.BOOKTYPE

UPDATE L SET BANK_ACC_NO = ACCNO FROM #LEDGER_PL L, MULTIBANKID L1
WHERE L.CLTCODE = L1.CLTCODE AND DEFAULTBANK = 1 


CREATE TABLE #OPBAL
(
	CLTCODE VARCHAR(10),
	OPBAL MONEY
)

INSERT INTO #OPBAL
SELECT CLTCODE, AMOUNT = SUM(AMOUNT) FROM
(
	SELECT CLTCODE = L.CLTCODE, AMOUNT = SUM(CASE WHEN DRCR = 'C' THEN VAMT ELSE -VAMT END)
	FROM LEDGER L, PARAMETER P
	WHERE L.CLTCODE = @BANK_CODE AND L.VDT >= SDTCUR AND VDT < @FR_DATE AND @FR_DATE BETWEEN SDTCUR AND LDTCUR AND VTYP <> 18
	GROUP BY L.CLTCODE
	UNION ALL
	SELECT CLTCODE = L.CLTCODE, AMOUNT = SUM(CASE WHEN DRCR = 'C' THEN VAMT ELSE -VAMT END)
	FROM LEDGER L, PARAMETER P
	WHERE L.CLTCODE = @BANK_CODE AND @FR_DATE BETWEEN SDTCUR AND LDTCUR
	AND VDT BETWEEN SDTCUR AND LDTCUR AND VTYP = 18
	GROUP BY L.CLTCODE
) L
GROUP BY CLTCODE

UPDATE L SET L.OPBAL = O.OPBAL FROM #LEDGER_PL L, #OPBAL O


SELECT VDT,
	EDT,
	LONG_NAME,
	BANK_ACC_NO,
	UCC_CODE,
	CLTCODE,
	CLIENT_PAN,
	NARRATION,
	VNO,
	SETT_NO,
	CHQ_NO,
	DRAMOUNT,
	CRAMOUNT,
	RUNNING_BALANCE,
	OPBAL,
	PDT FROM #LEDGER_PL

GO
