-- Object: PROCEDURE dbo.CLS_RECON_BANK_FILEUPLOAD_LOGS_WEEK
-- Server: 10.253.33.91 | DB: ACCOUNT
--------------------------------------------------


	CREATE  PROCEDURE [dbo].[CLS_RECON_BANK_FILEUPLOAD_LOGS_WEEK]
	AS
	
	BEGIN
	DECLARE @REPROCUPLOADDATE DATETIME,@NDAY INT ,@MBANKACCOUNT NVARCHAR(50)
	DECLARE @@SQL VARCHAR(MAX)
	, @@ACCOUNTDB VARCHAR(20)
	, @@ACCOUNTSERVER VARCHAR(20)
	, @BANKACCOUNT VARCHAR(50)
	, @UPLOADID         NVARCHAR(50)
	, @SEGMENT        NVARCHAR(50)
	, @BANKCODE       NVARCHAR(50)
	, @BANKNAME       NVARCHAR(50)
	, @FILETYPE       NVARCHAR(50)
	, @CLIENT		  NVARCHAR(50)
	, @FILEFORMATE    NVARCHAR(50)
	, @ENCRYPTIONCODE NVARCHAR(50)
	, @UNAME VARCHAR(50)
	, @REPROCESS_FLAG CHAR(1)
	, @UPLOAD_FLAG NVARCHAR(50)
	, @UPLOADDATE NVARCHAR(25)
	,@FILE_PATH NVARCHAR(500)
	
	
	SET @UNAME='AUTO'
	SET @FILE_PATH=''
	SET @SEGMENT = ''
	SET @BANKCODE = ''
	SET @BANKACCOUNT = ''
	SET @@ACCOUNTDB = ''
	SET @@ACCOUNTSERVER = ''	
	SET @NDAY = 0
	SET @REPROCESS_FLAG='R'
	SET @REPROCUPLOADDATE = GETDATE()
	DECLARE @COMBINEFILE NVARCHAR(2),@UPLOADFILENAME NVARCHAR(100)
	SET @UPLOADFILENAME=''
	SET @COMBINEFILE=1

	CREATE TABLE #RECON_BANK_MASTER_REPROCESS(
	BANKMASTERID INT IDENTITY(1,1) NOT NULL,
	SEGMENT NVARCHAR(50) NOT NULL,
	BANKNAME NVARCHAR(100) NULL,
	BANKCODE NVARCHAR(50) NULL,
	BANKACCOUNT NVARCHAR(50) NOT NULL,	
	FILETYPE NVARCHAR(50) NOT NULL,	
	REPROCESSFLAG NVARCHAR(50) NULL,
	VALUEDATE DATETIME	)

		CREATE TABLE  #TEMPBANKMASTER (SEGMENT NVARCHAR(50))

		INSERT INTO #TEMPBANKMASTER (SEGMENT)
		SELECT DISTINCT SEGMENT FROM RECON_BANK_MASTER_VW(NOLOCK) 
		WHERE FILETYPE<>'ENCRYPTION'		
		AND SEGMENT in('NSE-CAPITAL')

WHILE (SELECT COUNT(*)	FROM #TEMPBANKMASTER)> 0 
	BEGIN	
 
		SELECT TOP 1 @SEGMENT=SEGMENT FROM #TEMPBANKMASTER	

		SELECT	@@ACCOUNTDB = ACCOUNTDB	,@@ACCOUNTSERVER = ACCOUNTSERVER FROM PRADNYA.DBO.MULTICOMPANY
		WHERE EXCHANGE + '-' + SEGMENT = @SEGMENT AND PRIMARYSERVER = 1

	SET @@SQL = ''

	SET @@SQL = "INSERT INTO #RECON_BANK_MASTER_REPROCESS(SEGMENT,BANKNAME,BANKCODE,BANKACCOUNT,FILETYPE,REPROCESSFLAG,VALUEDATE) 
	SELECT DISTINCT SEGMENT, BANKNAME,BANKCODE, BANKACCOUNT,FILETYPE,0,R.VALUEDATE FROM  " + @@ACCOUNTSERVER + "."
	 + @@ACCOUNTDB+ ".[DBO].RECON_BANK_FILEUPLOAD_LOGS R," +@@ACCOUNTSERVER + "." + @@ACCOUNTDB+ ".[DBO].BANKRECO BR
	WHERE R.UPLOADID=BR.DUMMY2
	AND BR.STATUS='UNMATCHED'
	AND R.SEGMENT ='"+@SEGMENT+"'
	AND R.VALUEDATE BETWEEN  '"+ CONVERT(VARCHAR(11),DATEADD(DAY, -7,   @REPROCUPLOADDATE ), 113)+"'  AND  '"+CONVERT(VARCHAR(11), @REPROCUPLOADDATE ,113)+"'
	ORDER BY SEGMENT,BANKCODE"

	EXEC(@@SQL)
	PRINT @@SQL	
	DELETE FROM #TEMPBANKMASTER		
	WHERE SEGMENT = ISNULL(@SEGMENT, '')

	
	END
	--SELECT * FROM #RECON_BANK_MASTER_REPROCESS RETURN 

			WHILE (SELECT COUNT(*)	FROM #RECON_BANK_MASTER_REPROCESS WHERE REPROCESSFLAG<>'1')> 0 
				BEGIN	
				
				DELETE FROM  #RECON_BANK_MASTER_REPROCESS 	WHERE  REPROCESSFLAG='1'

					SET @SEGMENT = ''
					SET @BANKNAME = ''
					SET @BANKCODE = ''
					SET @MBANKACCOUNT = ''
					SET @FILETYPE = ''
					SET @@ACCOUNTDB = ''
					SET @@ACCOUNTSERVER = ''
					SET @REPROCUPLOADDATE = ''
					DECLARE @VALUEDATELOOP DATETIME
					DECLARE @VALUEDATEINNER NVARCHAR(20)

					SELECT TOP 1 @SEGMENT = SEGMENT,@BANKNAME = BANKNAME,@BANKCODE = BANKCODE,@MBANKACCOUNT = BANKACCOUNT
					,@FILETYPE = FILETYPE 
					,@VALUEDATEINNER=CONVERT(VARCHAR(10),CONVERT(DATE,VALUEDATE,106),103),@VALUEDATELOOP=VALUEDATE FROM #RECON_BANK_MASTER_REPROCESS
					WHERE REPROCESSFLAG<>'1'

					SELECT @@ACCOUNTDB = ACCOUNTDB,@@ACCOUNTSERVER = ACCOUNTSERVER FROM PRADNYA.DBO.MULTICOMPANY
					WHERE EXCHANGE + '-' + SEGMENT = @SEGMENT AND PRIMARYSERVER = 1

								
					DECLARE @DATELOOP INT =1
						
						--EXEC CLS_RECON_INSERT_PROCESS @UPLOADID,@FILETYPE,@BANKNAME,@UPLOAD_FLAG,@REPROCESS_FLAG
						--,@VALUEDATEINNER,@BANKCODE,@SEGMENT

						SET @@SQL = ''
						SET @@SQL = "EXEC  " + @@ACCOUNTSERVER + "." + @@ACCOUNTDB
						+ ".DBO.CLS_RECON_INSERT_PROCESS '"
						+ ISNULL(@UPLOADID, '') + "','" 
						+ ISNULL(@FILETYPE, '') + "','" 
						+ ISNULL(@BANKNAME, '') + "','" 
						+ ISNULL(@UPLOAD_FLAG, '') + "','"
						+ ISNULL(@REPROCESS_FLAG, '') + "','" 
						+ CONVERT(VARCHAR(10), @VALUEDATEINNER, 103) 
						+ "','" + ISNULL(@BANKCODE, '') 
						+ "','" + ISNULL(@MBANKACCOUNT, '') 
						+ "','" + ISNULL(@SEGMENT, '') 
						+ "','" + @UNAME 
						+ "','" + @FILE_PATH 
						+ "','" + @COMBINEFILE 
						+ "','" + @UPLOADFILENAME + "'"

						EXEC (@@SQL)
						PRINT @@SQL
						SET @@SQL = ''						

						SET @DATELOOP=@DATELOOP+1

						PRINT @SEGMENT+@BANKNAME+@BANKCODE+@FILETYPE+@VALUEDATEINNER

					UPDATE #RECON_BANK_MASTER_REPROCESS SET REPROCESSFLAG='1'
					WHERE SEGMENT = @SEGMENT AND BANKNAME = @BANKNAME AND BANKCODE = @BANKCODE 
					AND FILETYPE = @FILETYPE AND VALUEDATE=@VALUEDATELOOP
					
				END
	END

GO
