-- Object: PROCEDURE dbo.Ageingcursor_MTF_ALL_SEGMENT
-- Server: 10.253.33.91 | DB: ACCOUNT
--------------------------------------------------

--EXEC Ageingcursor_MTF 'DCR101', 'DCR101', 'APR 1 2017', 'nov 19 2017','PARTY','','',0, 'D','VDT','BROKER','BROKER',2,8,29,180,181,'ALL'
CREATE PROCEDURE [dbo].[Ageingcursor_MTF_ALL_SEGMENT]
	@FROMPARTY VARCHAR(10),
	@TOPARTY VARCHAR(10),
	@OPENDATE VARCHAR(11),
	@TODATE VARCHAR(11),
	@REPORTTYPE VARCHAR(15),
	@BRANCH VARCHAR(10),
	@FAMILY VARCHAR(10),
	@AMOUTGTTHAN MONEY,
	@AGEOPTION VARCHAR(1),
	@DTTYPE VARCHAR(3),
	@STATUSID VARCHAR(10),
	@STATUSNAME VARCHAR(25),
	@DAYS1 INT,
	@DAYS2 INT,
	@DAYS3 INT,
	@DAYS4 INT,
	@DAYS5 INT,
	@CLIENTTYPE VARCHAR(5)

AS
DECLARE
	@@PARTYCUR AS CURSOR,
	@@BALCUR AS CURSOR,
	@@BALDATE AS VARCHAR(11),
	@@OPENBALDT AS VARCHAR(11),
	@@OPENBALDTMIN AS VARCHAR(11),
	@@BALAMT AS MONEY,
	@@OCLTCODE AS VARCHAR(10),
	@@VTYP AS SMALLINT,
	@@VNO VARCHAR(12),
	@@EVDT AS DATETIME,
	@@VAMT AS MONEY,
	@@CLOSBAL AS MONEY,
	@@NODAYS AS INT,
	@@ACNAME VARCHAR(100),
	@@CLTCODE AS VARCHAR(10),
	@@BRANCHCODE AS VARCHAR(25),
	@@AREA AS VARCHAR(25),
	@@REGION AS VARCHAR(25),
	@@DRCR    AS VARCHAR(1),
	@@STARTDT AS DATETIME


SET NOCOUNT ON
SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED

IF LEN(@OPENDATE) = 10
	SELECT @OPENDATE = CONVERT(VARCHAR(11), CONVERT(DATETIME, @OPENDATE, 102), 109)

IF LEN(@TODATE) = 10
	SELECT @TODATE = CONVERT(VARCHAR(11), CONVERT(DATETIME, @TODATE, 102), 109)

	

SELECT @@STARTDT = ( SELECT LEFT(CONVERT(VARCHAR,DATEADD(MM,-12,CONVERT(DATETIME,@TODATE)),109),11) )

SELECT @@BRANCHCODE = ''

IF UPPER(@STATUSID) = 'BROKER'
BEGIN
IF @BRANCH = ''
BEGIN
   SELECT @@BRANCHCODE = '%'
   SELECT @@AREA = '%'
   SELECT @@REGION = '%'
END
ELSE
BEGIN
 SELECT @@BRANCHCODE = @BRANCH
 SELECT @@AREA = '%'
 SELECT @@REGION = '%'
END

END
ELSE IF UPPER(@STATUSID) = 'BRANCH'
BEGIN
   SELECT @@BRANCHCODE = RTRIM(@STATUSNAME)
   SELECT @@AREA = '%'
   SELECT @@REGION = '%'
END
ELSE IF UPPER(@STATUSID) = 'AREA'
BEGIN
   SELECT @@REGION = '%'
   SELECT @@BRANCHCODE = '%'
   SELECT @@AREA = RTRIM(@STATUSNAME)
END
ELSE IF UPPER(@STATUSID) = 'REGION'
BEGIN
   SELECT @@REGION = RTRIM(@STATUSNAME)
   SELECT @@BRANCHCODE = '%'
SELECT @@AREA =  '%'
END

CREATE TABLE [DBO].[#CLOSEBAL]
(
  [CLTCODE] [VARCHAR] (10) ,
  [CLOSBAL] [MONEY] NULL
) ON [PRIMARY]

CREATE   INDEX [INDXTMP] ON [DBO].[#CLOSEBAL] ([CLTCODE])


CREATE TABLE [DBO].[#LEDGERTRAN]
(
  [CLTCODE] [VARCHAR] (10) ,
  [VTYP] [SMALLINT] NOT NULL ,
  [VNO] [VARCHAR]  (12) ,
  [EVDT] [DATETIME] NULL ,
  [VAMT] [MONEY] NULL ,
  [CLOSBAL] [MONEY] NULL ,
  [RUNNINGBAL] [MONEY] NULL
) ON [PRIMARY]

CREATE   INDEX [INDXTMP1] ON [DBO].[#LEDGERTRAN] ([CLTCODE])


CREATE TABLE [DBO].[#FINTEMPAGEING]
(
  [CLTCODE] [VARCHAR] (10) ,
  [BALAMT] [MONEY] NULL ,
  [AGEDAYS] [INT] NULL ,
  [DRCR] [CHAR] (1)  ,
)

CREATE   INDEX [INDXTMP3] ON [DBO].[#FINTEMPAGEING] ([AGEDAYS])

SELECT @@OPENBALDTMIN =  LEFT(CONVERT(VARCHAR,ISNULL(MIN(VDT),0),109),11) FROM LEDGER_ALL L
WHERE VTYP = 18 AND VDT < = @OPENDATE
/*
SELECT CLTCODE,VDT AS BALDATE , VAMT CLOSBAL, AGEDAYS=0   INTO  #TEMPAGEING  FROM LEDGER WHERE 1=2
SELECT CLTCODE,VDT AS BALDATE , VAMT CLOSBAL, AGEDAYS=0   INTO  #TEMPAGEING1  FROM LEDGER WHERE 1=2
*/
IF @DTTYPE='VDT'
BEGIN
	/* --------------     GETTING  CLOSING BAL     ---------*/
	SELECT @@OPENBALDT=LEFT(CONVERT(VARCHAR,ISNULL(MAX(VDT),0),109),11) FROM LEDGER_ALL
	WHERE VTYP = '18' AND VDT < = @OPENDATE

	IF UPPER(@REPORTTYPE) = 'PARTY'
	BEGIN
		INSERT   INTO #CLOSEBAL
		SELECT L.CLTCODE,
		CLOSBAL = SUM( CASE WHEN DRCR = 'D' THEN VAMT ELSE -VAMT END)
		FROM VW_LEDGER_TEMP_NEW_ALL_SEGMENT L  /*WITH (INDEX(LEDIND_TEMP))*/ 
		WHERE VDT >= @@OPENBALDT + ' 00:00:00' AND VDT <= @TODATE + ' 23:59:59'
		AND L.CLTCODE >= @FROMPARTY AND L.CLTCODE <= @TOPARTY --AND BRANCH_CD LIKE @@BRANCHCODE+'%'
		 
		AND @TODATE BETWEEN FROM_DATE AND TO_DATE
		GROUP BY L.CLTCODE
		HAVING ABS(SUM( CASE WHEN DRCR = 'D' THEN VAMT ELSE -VAMT END)) > @AMOUTGTTHAN
		
	END
	ELSE IF UPPER(@REPORTTYPE) = 'FAMILY'
	BEGIN
		INSERT   INTO #CLOSEBAL
		SELECT FAMILY AS CLTCODE,
		CLOSBAL = SUM( CASE WHEN DRCR = 'D' THEN VAMT ELSE -VAMT END)
		FROM VW_LEDGER_TEMP_NEW_ALL_SEGMENT /*WITH (INDEX(LEDIND_TEMP))*/ WHERE VDT >= @@OPENBALDT + ' 00:00:00' AND VDT <= @TODATE + ' 23:59:59'
		AND FAMILY >= @FROMPARTY AND FAMILY <= @TOPARTY
		AND BRANCH_CD LIKE @@BRANCHCODE+'%'
		AND @TODATE BETWEEN FROM_DATE AND TO_DATE
		GROUP BY FAMILY
		HAVING ABS(SUM( CASE WHEN DRCR = 'D' THEN VAMT ELSE -VAMT END)) > @AMOUTGTTHAN

/*		INSERT   INTO #TEMPAGEING1
		SELECT FAMILY AS CLTCODE, BALDATE=@TODATE,
		CLOSBAL = SUM( CASE WHEN DRCR = 'D' THEN VAMT ELSE -VAMT END),AGEDAYS=0
		FROM LEDGER L,  MSAJAG.DBO.CLIENT1 C1, MSAJAG.DBO.CLIENT2 C2 WHERE C1.CL_CODE = C2.CL_CODE
		AND VDT >= @@OPENBALDT + ' 00:00:00' AND VDT <= @TODATE + ' 23:59:59'
		AND L.CLTCODE = C2.PARTY_CODE
		AND BRANCH_CD LIKE @@BRANCHCODE+'%'
		AND C1.FAMILY >= @FROMPARTY AND C1.FAMILY <= @TOPARTY
		GROUP BY FAMILY
		ORDER BY FAMILY

		INSERT   INTO #TEMPAGEING
		SELECT CLTCODE, BALDATE=@TODATE,
		CLOSBAL = SUM(CLOSBAL),AGEDAYS=0
		FROM #TEMPAGEING1
		GROUP BY CLTCODE
		ORDER BY CLTCODE*/

	END
	ELSE IF UPPER(@REPORTTYPE) = 'FAMILYPARTY'
	BEGIN
		INSERT   INTO #CLOSEBAL
		SELECT L.CLTCODE,
		CLOSBAL = SUM( CASE WHEN DRCR = 'D' THEN VAMT ELSE -VAMT END)
		FROM VW_LEDGER_TEMP_NEW_ALL_SEGMENT L /*WITH (INDEX(LEDIND_TEMP))*/ WHERE VDT >= @@OPENBALDT + ' 00:00:00' AND VDT <= @TODATE + ' 23:59:59'
		AND L.CLTCODE >= @FROMPARTY AND L.CLTCODE <= @TOPARTY
		AND BRANCH_CD LIKE @@BRANCHCODE+'%'
		AND FAMILY = @FAMILY
		GROUP BY L.CLTCODE
		HAVING ABS(SUM( CASE WHEN DRCR = 'D' THEN VAMT ELSE -VAMT END)) > @AMOUTGTTHAN
	END

	/* --------------     GETTING TRANS DATA       ---------*/
	IF UPPER(@REPORTTYPE) = 'PARTY' OR UPPER(@REPORTTYPE) = 'FAMILYPARTY'
	BEGIN
		IF UPPER(RTRIM(@AGEOPTION)) = 'D'
		BEGIN
			INSERT INTO #LEDGERTRAN
			SELECT L.CLTCODE, VTYP, VNO, VDT, VAMT, CLOSBAL,0
			FROM VW_LEDGER_TEMP_NEW_ALL_SEGMENT L , #CLOSEBAL A  WITH(INDEX(INDXTMP)) 
			WHERE CLOSBAL >= 0 AND DRCR = ( CASE WHEN CLOSBAL >= 0 THEN 'D' ELSE 'C' END )
			AND L.CLTCODE = A.CLTCODE
			 
			AND VDT <= @TODATE  + ' 23:59:59'
			AND @TODATE BETWEEN FROM_DATE AND TO_DATE
			--     AND VDT > DATEADD(MONTH,-12,@@OPENBALDT)
			AND VTYP NOT IN(18, 15, 35)

			/* NEW QUERY TO HANDLE THE MTF TRADE */
			INSERT INTO #LEDGERTRAN
			SELECT L.CLTCODE, VTYP = 15, VNO = MAX(VNO), VDT = CONVERT(VARCHAR(11), VDT, 109), VAMT = SUM(CASE WHEN DRCR = 'D' THEN VAMT ELSE -VAMT END), CLOSBAL,0
			FROM VW_LEDGER_TEMP_NEW_ALL_SEGMENT L , #CLOSEBAL A  WITH(INDEX(INDXTMP)) 
			WHERE CLOSBAL >= 0 
			AND L.CLTCODE = A.CLTCODE  
			AND VDT <= @TODATE  + ' 23:59:59'
			--     AND VDT > DATEADD(MONTH,-12,@@OPENBALDT)
			AND 1 = (CASE WHEN VTYP = 35 THEN 1 
						  WHEN VTYP = 15 AND NARRATION LIKE '%NSECMNBILL%' THEN 1 
						  WHEN VTYP = 15 AND NARRATION LIKE '%BSECMDBILL%' THEN 1 
						  ELSE 2
					 END)
			AND VTYP IN (15,35)
			AND @TODATE BETWEEN FROM_DATE AND TO_DATE
			GROUP BY L.CLTCODE, CONVERT(VARCHAR(11), VDT, 109), CLOSBAL
			HAVING SUM(CASE WHEN DRCR = 'D' THEN VAMT ELSE -VAMT END) >= 0

			INSERT INTO #LEDGERTRAN
			SELECT L.CLTCODE, VTYP = 15, VNO = VNO, VDT = CONVERT(VARCHAR(11), VDT, 109), VAMT = (CASE WHEN DRCR = 'D' THEN VAMT ELSE -VAMT END), CLOSBAL,0
			FROM VW_LEDGER_TEMP_NEW_ALL_SEGMENT L , #CLOSEBAL A  WITH(INDEX(INDXTMP)) 
			WHERE CLOSBAL >= 0 
			AND L.CLTCODE = A.CLTCODE  
			AND VDT <= @TODATE  + ' 23:59:59'
			--     AND VDT > DATEADD(MONTH,-12,@@OPENBALDT)
			AND 1 = (CASE WHEN VTYP = 35 THEN 2 
						  WHEN VTYP = 15 AND NARRATION LIKE '%NSECMNBILL%' THEN 2 
						  WHEN VTYP = 15 AND NARRATION LIKE '%BSECMDBILL%' THEN 2 
						  ELSE 1
					 END)
			AND VTYP IN (15,35)
			AND DRCR = 'D'
			AND @TODATE BETWEEN FROM_DATE AND TO_DATE
			

			/* NEW QUERY TO HANDLE THE MTF TRADE */

			INSERT INTO #LEDGERTRAN
			SELECT L.CLTCODE, VTYP, VNO, VDT, VAMT, CLOSBAL,0
			FROM VW_LEDGER_TEMP_NEW_ALL_SEGMENT L , #CLOSEBAL A  WITH(INDEX(INDXTMP)) 
			WHERE CLOSBAL >= 0 AND DRCR = ( CASE WHEN CLOSBAL >= 0 THEN 'D' ELSE 'C' END )
			AND L.CLTCODE = A.CLTCODE  
			AND VDT LIKE @@OPENBALDTMIN  + ' %'
			AND VTYP = 18
			AND @TODATE BETWEEN FROM_DATE AND TO_DATE
		END
		ELSE IF UPPER(RTRIM(@AGEOPTION)) = 'C'
		BEGIN
			INSERT INTO #LEDGERTRAN
			SELECT L.CLTCODE, VTYP, VNO, VDT, VAMT, CLOSBAL,0
			FROM VW_LEDGER_TEMP_NEW_ALL_SEGMENT L , #CLOSEBAL A  WITH(INDEX(INDXTMP))
			WHERE CLOSBAL < 0 AND DRCR = ( CASE WHEN CLOSBAL >= 0 THEN 'D' ELSE 'C' END )
			AND L.CLTCODE = A.CLTCODE
			AND VDT <= @TODATE  + ' 23:59:59'
			--     AND VDT > DATEADD(MONTH,-12,@@OPENBALDT)
			AND VTYP not in(15, 35, 18)
			AND @TODATE BETWEEN FROM_DATE AND TO_DATE

			/* NEW QUERY TO HANDLE THE MTF TRADE */
			INSERT INTO #LEDGERTRAN
			SELECT L.CLTCODE, VTYP = 15, VNO = MAX(VNO), VDT = CONVERT(VARCHAR(11), VDT, 109), 
			VAMT = SUM(CASE WHEN DRCR = 'D' THEN VAMT ELSE -VAMT END), CLOSBAL,0
			FROM VW_LEDGER_TEMP_NEW_ALL_SEGMENT L , #CLOSEBAL A  WITH(INDEX(INDXTMP))
			WHERE CLOSBAL < 0 
			AND L.CLTCODE = A.CLTCODE
			AND VDT <= @TODATE  + ' 23:59:59'
			--     AND VDT > DATEADD(MONTH,-12,@@OPENBALDT)
			AND 1 = (CASE WHEN VTYP = 35 THEN 1 
						  WHEN VTYP = 15 AND NARRATION LIKE '%NSECMNBILL%' THEN 1 
						  WHEN VTYP = 15 AND NARRATION LIKE '%BSECMDBILL%' THEN 1 
						  ELSE 2
					 END)
			AND VTYP IN (15,35)
			AND @TODATE BETWEEN FROM_DATE AND TO_DATE
			GROUP BY L.CLTCODE, CONVERT(VARCHAR(11), VDT, 109), CLOSBAL
			HAVING SUM(CASE WHEN DRCR = 'D' THEN VAMT ELSE -VAMT END) < 0

			INSERT INTO #LEDGERTRAN
			SELECT L.CLTCODE, VTYP = 15, VNO = VNO, VDT = CONVERT(VARCHAR(11), VDT, 109), 
			VAMT = (CASE WHEN DRCR = 'D' THEN VAMT ELSE -VAMT END), CLOSBAL,0
			FROM VW_LEDGER_TEMP_NEW_ALL_SEGMENT L , #CLOSEBAL A  WITH(INDEX(INDXTMP))
			WHERE CLOSBAL < 0 
			AND L.CLTCODE = A.CLTCODE
			AND VDT <= @TODATE  + ' 23:59:59'
			--     AND VDT > DATEADD(MONTH,-12,@@OPENBALDT)
			AND 1 = (CASE WHEN VTYP = 35 THEN 2 
						  WHEN VTYP = 15 AND NARRATION LIKE '%NSECMNBILL%' THEN 2
						  WHEN VTYP = 15 AND NARRATION LIKE '%BSECMDBILL%' THEN 2 
						  ELSE 1
					 END)
			AND VTYP IN (15,35)
			AND DRCR = 'C'
			AND @TODATE BETWEEN FROM_DATE AND TO_DATE
			
			/* NEW QUERY TO HANDLE THE MTF TRADE */

			INSERT INTO #LEDGERTRAN
			SELECT L.CLTCODE, VTYP, VNO, VDT, VAMT, CLOSBAL,0
			FROM VW_LEDGER_TEMP_NEW_ALL_SEGMENT L , #CLOSEBAL A  WITH(INDEX(INDXTMP))
			WHERE CLOSBAL < 0 AND DRCR = ( CASE WHEN CLOSBAL >= 0 THEN 'D' ELSE 'C' END )
			AND L.CLTCODE = A.CLTCODE
			AND VDT LIKE @@OPENBALDTMIN  + ' %'
			AND VTYP = 18
			AND @TODATE BETWEEN FROM_DATE AND TO_DATE
		END
		ELSE
		BEGIN
			INSERT INTO #LEDGERTRAN
			SELECT L.CLTCODE, VTYP, VNO, VDT, VAMT, CLOSBAL,0
			FROM VW_LEDGER_TEMP_NEW_ALL_SEGMENT L , #CLOSEBAL A  WITH(INDEX(INDXTMP)),MTFTRADE.DBO.TblClientMargin M 
			WHERE DRCR = ( CASE WHEN CLOSBAL >= 0 THEN 'D' ELSE 'C' END )
			AND L.CLTCODE = A.CLTCODE
			AND L.CLTCODE =M.Party_Code
			AND VDT <= @TODATE  + ' 23:59:59'
			--     AND VDT > DATEADD(MONTH,-12,@@OPENBALDT)
			AND VTYP not in(15, 35, 18)
			AND @TODATE BETWEEN M.FROM_DATE AND M.TO_DATE

			/* NEW QUERY TO HANDLE THE MTF TRADE */
			INSERT INTO #LEDGERTRAN
			SELECT L.CLTCODE, VTYP = 15, VNO = MAX(VNO), VDT = CONVERT(VARCHAR(11), VDT, 109), 
				   VAMT = SUM(CASE WHEN DRCR = 'D' THEN VAMT ELSE -VAMT END), CLOSBAL,0
			FROM VW_LEDGER_TEMP_NEW_ALL_SEGMENT L , #CLOSEBAL A  WITH(INDEX(INDXTMP))
			WHERE L.CLTCODE = A.CLTCODE
			AND VDT <= @TODATE  + ' 23:59:59'
			--     AND VDT > DATEADD(MONTH,-12,@@OPENBALDT)
			AND 1 = (CASE WHEN VTYP = 35 THEN 1 
						  WHEN VTYP = 15 AND NARRATION LIKE '%NSECMNBILL%' THEN 1 
						  WHEN VTYP = 15 AND NARRATION LIKE '%BSECMDBILL%' THEN 1 
						  ELSE 2
					 END)
			AND VTYP IN (15,35)
			AND @TODATE BETWEEN FROM_DATE AND TO_DATE
			GROUP BY L.CLTCODE, CONVERT(VARCHAR(11), VDT, 109), CLOSBAL
			HAVING (SUM(CASE WHEN DRCR = 'D' THEN VAMT ELSE -VAMT END) < 0 AND CLOSBAL < 0) 
			OR (SUM(CASE WHEN DRCR = 'D' THEN VAMT ELSE -VAMT END) >= 0 AND CLOSBAL >= 0)

			INSERT INTO #LEDGERTRAN
			SELECT L.CLTCODE, VTYP = 15, VNO = (VNO), VDT = CONVERT(VARCHAR(11), VDT, 109), 
				   VAMT = (CASE WHEN DRCR = 'D' THEN VAMT ELSE -VAMT END), CLOSBAL,0
			FROM VW_LEDGER_TEMP_NEW_ALL_SEGMENT L , #CLOSEBAL A  WITH(INDEX(INDXTMP))
			WHERE L.CLTCODE = A.CLTCODE
			AND VDT <= @TODATE  + ' 23:59:59'
			--     AND VDT > DATEADD(MONTH,-12,@@OPENBALDT)
			AND 1 = (CASE WHEN VTYP = 35 THEN 2 
						  WHEN VTYP = 15 AND NARRATION LIKE '%NSECMNBILL%' THEN 2 
						  WHEN VTYP = 15 AND NARRATION LIKE '%BSECMDBILL%' THEN 2 
						  ELSE 1
					 END)
			AND VTYP IN (15,35)
			AND @TODATE BETWEEN FROM_DATE AND TO_DATE
			
			/* NEW QUERY TO HANDLE THE MTF TRADE */

			INSERT INTO #LEDGERTRAN
			SELECT L.CLTCODE, VTYP, VNO, VDT, VAMT, CLOSBAL,0
			FROM VW_LEDGER_TEMP_NEW_ALL_SEGMENT L , #CLOSEBAL A  WITH(INDEX(INDXTMP))
			WHERE DRCR = ( CASE WHEN CLOSBAL >= 0 THEN 'D' ELSE 'C' END )
			AND L.CLTCODE = A.CLTCODE
			AND VDT LIKE @@OPENBALDTMIN  + ' %'
			AND VTYP = 18
			AND @TODATE BETWEEN FROM_DATE AND TO_DATE
		END
	END
    ELSE
    BEGIN
		IF UPPER(RTRIM(@AGEOPTION)) = 'D'
		BEGIN
			INSERT INTO #LEDGERTRAN
			SELECT CLTCODE=FAMILY, VTYP, VNO, VDT, VAMT, CLOSBAL, 0
			FROM VW_LEDGER_TEMP_NEW_ALL_SEGMENT L , #CLOSEBAL A  WHERE A.CLTCODE = FAMILY
			AND CLOSBAL >= 0 AND DRCR = ( CASE WHEN CLOSBAL >= 0 THEN 'D' ELSE 'C' END )
			AND VDT <= @TODATE  + ' 23:59:59'
			--     AND VDT > DATEADD(MONTH,-12,@@OPENBALDT)
			AND FAMILY >= @FROMPARTY AND FAMILY <= @TOPARTY
			AND VTYP <> '18'
			AND @TODATE BETWEEN FROM_DATE AND TO_DATE

			INSERT INTO #LEDGERTRAN
			SELECT CLTCODE=FAMILY, VTYP, VNO, VDT, VAMT, CLOSBAL, 0
			FROM VW_LEDGER_TEMP_NEW_ALL_SEGMENT L , #CLOSEBAL A  WHERE A.CLTCODE = FAMILY
			AND CLOSBAL >= 0 AND DRCR = ( CASE WHEN CLOSBAL >= 0 THEN 'D' ELSE 'C' END )
			AND FAMILY >= @FROMPARTY AND FAMILY <= @TOPARTY
			AND VDT LIKE @@OPENBALDTMIN  + ' %'
			AND VTYP = 18
		END
		ELSE IF UPPER(RTRIM(@AGEOPTION)) = 'C'
		BEGIN
			INSERT INTO #LEDGERTRAN
			SELECT CLTCODE=FAMILY, VTYP, VNO, VDT, VAMT, CLOSBAL, 0
			FROM VW_LEDGER_TEMP_NEW_ALL_SEGMENT L , #CLOSEBAL A  WHERE  A.CLTCODE = FAMILY
			AND CLOSBAL < 0 AND DRCR = ( CASE WHEN CLOSBAL >= 0 THEN 'D' ELSE 'C' END )
			AND VDT <= @TODATE  + ' 23:59:59'
			--     AND VDT > DATEADD(MONTH,-12,@@OPENBALDT)
			AND FAMILY >= @FROMPARTY AND FAMILY <= @TOPARTY
			AND VTYP <> '18'

			INSERT INTO #LEDGERTRAN
			SELECT CLTCODE=FAMILY, VTYP, VNO, VDT, VAMT, CLOSBAL, 0
			FROM VW_LEDGER_TEMP_NEW_ALL_SEGMENT L , #CLOSEBAL A  WHERE  A.CLTCODE = FAMILY
			AND CLOSBAL < 0 AND DRCR = ( CASE WHEN CLOSBAL >= 0 THEN 'D' ELSE 'C' END )
			AND FAMILY >= @FROMPARTY AND FAMILY <= @TOPARTY
			AND VDT LIKE @@OPENBALDTMIN  + ' %'
			AND VTYP = 18
		END
		ELSE
		BEGIN
		PRINT 'VIN'
			INSERT INTO #LEDGERTRAN
			SELECT CLTCODE=FAMILY, VTYP, VNO, VDT, VAMT, CLOSBAL, 0
			FROM VW_LEDGER_TEMP_NEW_ALL_SEGMENT L , #CLOSEBAL A  WHERE A.CLTCODE = FAMILY
			AND DRCR = ( CASE WHEN CLOSBAL >= 0 THEN 'D' ELSE 'C' END )
			AND VDT <= @TODATE  + ' 23:59:59'
			--     AND VDT > DATEADD(MONTH,-12,@@OPENBALDT)
			AND FAMILY >= @FROMPARTY AND FAMILY <= @TOPARTY
			AND VTYP <> '18'
			--SELECT * FROM #LEDGERTRAN
			--RETURN
			INSERT INTO #LEDGERTRAN
			SELECT CLTCODE=FAMILY, VTYP, VNO, VDT, VAMT, CLOSBAL, 0
			FROM VW_LEDGER_TEMP_NEW_ALL_SEGMENT L , #CLOSEBAL A  WHERE A.CLTCODE = FAMILY
			AND DRCR = ( CASE WHEN CLOSBAL >= 0 THEN 'D' ELSE 'C' END )
			AND FAMILY >= @FROMPARTY AND FAMILY <= @TOPARTY
			AND VDT LIKE @@OPENBALDTMIN  + ' %'
			AND VTYP = 18
		END
	END
END
ELSE      /* -----------           REPORT BY EDT --------------*/
BEGIN
	/* --------------     GETTING  CLOSING BAL     ---------*/
	SELECT @@OPENBALDT=LEFT(CONVERT(VARCHAR,ISNULL(MAX(EDT),0),109),11) FROM VW_LEDGER_TEMP_NEW_ALL_SEGMENT
	WHERE VTYP = '18' AND EDT < = @OPENDATE

	IF UPPER(@REPORTTYPE) = 'PARTY'
	BEGIN
		INSERT   INTO #CLOSEBAL
		SELECT L.CLTCODE,
		CLOSBAL = SUM( CASE WHEN DRCR = 'D' THEN VAMT ELSE -VAMT END)
		FROM VW_LEDGER_TEMP_NEW_ALL_SEGMENT L /*WITH(INDEX(LED2IND_EDT_TEMP))*/ WHERE EDT >= @@OPENBALDT + ' 00:00:00' AND EDT <= @TODATE + ' 23:59:59'
		AND L.CLTCODE >= @FROMPARTY AND L.CLTCODE <= @TOPARTY AND BRANCH_CD LIKE @@BRANCHCODE+'%'
		AND @TODATE BETWEEN FROM_DATE AND TO_DATE
		GROUP BY L.CLTCODE
		HAVING ABS(SUM( CASE WHEN DRCR = 'D' THEN VAMT ELSE -VAMT END)) > @AMOUTGTTHAN
		
	END
	ELSE IF UPPER(@REPORTTYPE) = 'FAMILY'
	BEGIN
		INSERT   INTO #CLOSEBAL
		SELECT FAMILY AS CLTCODE,
		CLOSBAL = SUM( CASE WHEN DRCR = 'D' THEN VAMT ELSE -VAMT END)
		FROM VW_LEDGER_TEMP_NEW_ALL_SEGMENT L /*WITH(INDEX(LED2IND_EDT_TEMP))*/
		WHERE EDT >= @@OPENBALDT + ' 00:00:00' AND EDT <= @TODATE + ' 23:59:59'
		AND FAMILY >= @FROMPARTY AND FAMILY <= @TOPARTY
		AND BRANCH_CD LIKE @@BRANCHCODE+'%'
		GROUP BY FAMILY
		HAVING ABS(SUM( CASE WHEN DRCR = 'D' THEN VAMT ELSE -VAMT END)) > @AMOUTGTTHAN
	END
	ELSE IF UPPER(@REPORTTYPE) = 'FAMILYPARTY'
	BEGIN
		INSERT   INTO #CLOSEBAL
		SELECT L.CLTCODE,
		CLOSBAL = SUM( CASE WHEN DRCR = 'D' THEN VAMT ELSE -VAMT END)
		FROM VW_LEDGER_TEMP_NEW_ALL_SEGMENT L  /*WITH(INDEX(LED2IND_EDT_TEMP))*/
		WHERE EDT >= @@OPENBALDT + ' 00:00:00' AND EDT <= @TODATE + ' 23:59:59'
		AND L.CLTCODE >= @FROMPARTY AND L.CLTCODE <= @TOPARTY
		AND BRANCH_CD LIKE @@BRANCHCODE+'%'
		AND FAMILY = @FAMILY
		GROUP BY L.CLTCODE
		HAVING ABS(SUM( CASE WHEN DRCR = 'D' THEN VAMT ELSE -VAMT END)) > @AMOUTGTTHAN
	END

	/* --------------     GETTING TRANS DATA       ---------*/
	IF UPPER(@REPORTTYPE) = 'PARTY' OR UPPER(@REPORTTYPE) = 'FAMILYPARTY'
	BEGIN
       IF UPPER(RTRIM(@AGEOPTION)) = 'D'
		BEGIN
			INSERT INTO #LEDGERTRAN
			SELECT L.CLTCODE, VTYP, VNO, EDT, VAMT, CLOSBAL, 0
			FROM VW_LEDGER_TEMP_NEW_ALL_SEGMENT L , #CLOSEBAL A  WITH(INDEX(INDXTMP))
			WHERE CLOSBAL >= 0 AND DRCR = ( CASE WHEN CLOSBAL >= 0 THEN 'D' ELSE 'C' END )
			AND L.CLTCODE = A.CLTCODE
			AND EDT <= @TODATE  + ' 23:59:59'
			--    AND EDT > DATEADD(MONTH,-12,@@OPENBALDT)
			AND VTYP <> '18'
			AND @TODATE BETWEEN FROM_DATE AND TO_DATE

			INSERT INTO #LEDGERTRAN
			SELECT L.CLTCODE, VTYP, VNO, EDT, VAMT, CLOSBAL, 0
			FROM VW_LEDGER_TEMP_NEW_ALL_SEGMENT L , #CLOSEBAL A  WITH(INDEX(INDXTMP))
			WHERE CLOSBAL >= 0 AND DRCR = ( CASE WHEN CLOSBAL >= 0 THEN 'D' ELSE 'C' END )
			AND L.CLTCODE = A.CLTCODE
			AND EDT LIKE @@OPENBALDTMIN  + ' %'
			AND VTYP = 18
			AND @TODATE BETWEEN FROM_DATE AND TO_DATE
		END
		ELSE IF UPPER(RTRIM(@AGEOPTION)) = 'C'
		BEGIN
			INSERT INTO #LEDGERTRAN
			SELECT L.CLTCODE, VTYP, VNO, EDT, VAMT, CLOSBAL, 0
			FROM VW_LEDGER_TEMP_NEW_ALL_SEGMENT L , #CLOSEBAL A  WITH(INDEX(INDXTMP))
			WHERE CLOSBAL < 0 AND DRCR = ( CASE WHEN CLOSBAL >= 0 THEN 'D' ELSE 'C' END )
			AND L.CLTCODE = A.CLTCODE
			AND EDT <= @TODATE  + ' 23:59:59'
			--    AND EDT > DATEADD(MONTH,-12,@@OPENBALDT)
			AND VTYP <> '18'
			AND @TODATE BETWEEN FROM_DATE AND TO_DATE

			INSERT INTO #LEDGERTRAN
			SELECT L.CLTCODE, VTYP, VNO, EDT, VAMT, CLOSBAL, 0
			FROM VW_LEDGER_TEMP_NEW_ALL_SEGMENT L , #CLOSEBAL A  WITH(INDEX(INDXTMP))
			WHERE CLOSBAL < 0 AND DRCR = ( CASE WHEN CLOSBAL >= 0 THEN 'D' ELSE 'C' END )
			AND L.CLTCODE = A.CLTCODE
			AND EDT LIKE @@OPENBALDTMIN  + ' %'
			AND VTYP = 18
			AND @TODATE BETWEEN FROM_DATE AND TO_DATE
		END
		ELSE
		BEGIN
			INSERT INTO #LEDGERTRAN
			SELECT L.CLTCODE, VTYP, VNO, EDT, VAMT, CLOSBAL, 0
			FROM VW_LEDGER_TEMP_NEW_ALL_SEGMENT L , #CLOSEBAL A  WITH(INDEX(INDXTMP))
			WHERE DRCR = ( CASE WHEN CLOSBAL >= 0 THEN 'D' ELSE 'C' END )
			AND L.CLTCODE = A.CLTCODE
			AND EDT <= @TODATE  + ' 23:59:59'
			--    AND EDT > DATEADD(MONTH,-12,@@OPENBALDT)
			AND VTYP <> '18'
			AND @TODATE BETWEEN FROM_DATE AND TO_DATE

			INSERT INTO #LEDGERTRAN
			SELECT L.CLTCODE, VTYP, VNO, EDT, VAMT, CLOSBAL, 0
			FROM VW_LEDGER_TEMP_NEW_ALL_SEGMENT L , #CLOSEBAL A  WITH(INDEX(INDXTMP))
			WHERE DRCR = ( CASE WHEN CLOSBAL >= 0 THEN 'D' ELSE 'C' END )
			AND L.CLTCODE = A.CLTCODE
			AND EDT LIKE @@OPENBALDTMIN  + ' %'
			AND VTYP = 18
			AND @TODATE BETWEEN FROM_DATE AND TO_DATE
		END
	END
	ELSE
    BEGIN
		IF UPPER(RTRIM(@AGEOPTION)) = 'D'
		BEGIN
			INSERT INTO #LEDGERTRAN
			SELECT CLTCODE=FAMILY, VTYP, VNO, EDT, VAMT, CLOSBAL, 0
			FROM VW_LEDGER_TEMP_NEW_ALL_SEGMENT L,  #CLOSEBAL A WHERE A.CLTCODE = FAMILY
			AND CLOSBAL >= 0 AND DRCR = ( CASE WHEN CLOSBAL >= 0 THEN 'D' ELSE 'C' END )
			AND EDT <= @TODATE  + ' 23:59:59'
			--    AND EDT > DATEADD(MONTH,-12,@@OPENBALDT)
			AND FAMILY >= @FROMPARTY AND FAMILY <= @TOPARTY
			AND VTYP <> '18'

			INSERT INTO #LEDGERTRAN
			SELECT CLTCODE=FAMILY, VTYP, VNO, EDT, VAMT, CLOSBAL, 0
			FROM VW_LEDGER_TEMP_NEW_ALL_SEGMENT L,  #CLOSEBAL A WHERE A.CLTCODE = FAMILY
			AND CLOSBAL >= 0 AND DRCR = ( CASE WHEN CLOSBAL >= 0 THEN 'D' ELSE 'C' END )
			AND EDT LIKE @@OPENBALDTMIN  + ' %'
			AND FAMILY >= @FROMPARTY AND FAMILY <= @TOPARTY
			AND VTYP = 18
		END
		ELSE IF UPPER(RTRIM(@AGEOPTION)) = 'C'
		BEGIN
			INSERT INTO #LEDGERTRAN
			SELECT CLTCODE=FAMILY, VTYP, VNO, EDT, VAMT, CLOSBAL, 0
			FROM VW_LEDGER_TEMP_NEW_ALL_SEGMENT L , #CLOSEBAL A  WITH(INDEX(INDXTMP)) WHERE  A.CLTCODE = FAMILY
			AND CLOSBAL < 0 AND DRCR = ( CASE WHEN CLOSBAL >= 0 THEN 'D' ELSE 'C' END )
			AND EDT <= @TODATE  + ' 23:59:59'
			--    AND EDT > DATEADD(MONTH,-12,@@OPENBALDT)
			AND FAMILY >= @FROMPARTY AND FAMILY <= @TOPARTY
			AND VTYP <> '18'

			INSERT INTO #LEDGERTRAN
			SELECT CLTCODE=FAMILY, VTYP, VNO, EDT, VAMT, CLOSBAL, 0
			FROM VW_LEDGER_TEMP_NEW_ALL_SEGMENT L , #CLOSEBAL A  WITH(INDEX(INDXTMP)) WHERE  A.CLTCODE = FAMILY
			AND CLOSBAL < 0 AND DRCR = ( CASE WHEN CLOSBAL >= 0 THEN 'D' ELSE 'C' END )
			AND FAMILY >= @FROMPARTY AND FAMILY <= @TOPARTY
			AND EDT LIKE @@OPENBALDTMIN  + ' %'
			AND VTYP = 18
		END
		ELSE
		BEGIN
			INSERT INTO #LEDGERTRAN
			SELECT CLTCODE=FAMILY, VTYP, VNO, EDT, VAMT, CLOSBAL, 0
			FROM VW_LEDGER_TEMP_NEW_ALL_SEGMENT L , #CLOSEBAL A  WITH(INDEX(INDXTMP)) WHERE A.CLTCODE = FAMILY
			AND DRCR = ( CASE WHEN CLOSBAL >= 0 THEN 'D' ELSE 'C' END )
			AND EDT <= @TODATE  + ' 23:59:59'
			AND EDT LIKE @@OPENBALDTMIN  + ' %'
			AND FAMILY >= @FROMPARTY AND FAMILY <= @TOPARTY
			AND VTYP <> '18'

			INSERT INTO #LEDGERTRAN
			SELECT CLTCODE=FAMILY, VTYP, VNO, EDT, VAMT, CLOSBAL, 0
			FROM VW_LEDGER_TEMP_NEW_ALL_SEGMENT L , #CLOSEBAL A  WITH(INDEX(INDXTMP)) WHERE A.CLTCODE = FAMILY
			AND DRCR = ( CASE WHEN CLOSBAL >= 0 THEN 'D' ELSE 'C' END )
			AND FAMILY >= @FROMPARTY AND FAMILY <= @TOPARTY
			AND EDT LIKE @@OPENBALDTMIN  + ' %'
			AND VTYP = 18
		END
	END
END


CREATE TABLE #AGEING_DAYS  
(  
 VDT DATETIME,  
 NODAYS INT,  
 SNO INT  
)    
   
INSERT INTO #AGEING_DAYS   
EXEC GET_CALENDER_DAYS @TODATE 



/*UPDATING RUNNING BALANCE*/

SET @@PARTYCUR = CURSOR FOR
	SELECT DISTINCT CLTCODE  FROM #LEDGERTRAN

OPEN @@PARTYCUR
	FETCH NEXT FROM @@PARTYCUR INTO @@CLTCODE

WHILE @@FETCH_STATUS = 0
BEGIN

	SET @@BALCUR = CURSOR FOR
	SELECT VTYP, VNO, EVDT, VAMT, CLOSBAL, NODAYS   FROM #LEDGERTRAN T, #AGEING_DAYS A
	WHERE CLTCODE = @@CLTCODE
	AND CONVERT(VARCHAR(11), EVDT, 109) = CONVERT(VARCHAR(11), VDT, 109)
	ORDER BY EVDT DESC, VTYP, VNO

	OPEN @@BALCUR
	FETCH NEXT FROM @@BALCUR INTO  @@VTYP, @@VNO, @@EVDT, @@VAMT, @@CLOSBAL, @@NODAYS

	WHILE @@FETCH_STATUS = 0
	BEGIN
		SELECT @@OCLTCODE = @@CLTCODE
		SELECT @@BALAMT = ABS(@@CLOSBAL)
		IF @@CLOSBAL >= 0
		BEGIN
			SELECT @@DRCR = 'D'
		END
		ELSE
		BEGIN
			SELECT @@DRCR = 'C'
		END
		WHILE @@FETCH_STATUS = 0 AND @@OCLTCODE = @@CLTCODE  AND @@BALAMT > 0
		BEGIN
		IF @@BALAMT >= @@VAMT
		BEGIN
			INSERT INTO #FINTEMPAGEING
			SELECT @@CLTCODE, @@VAMT, @@NODAYS, @@DRCR
			SELECT @@BALAMT = @@BALAMT - @@VAMT
		END
		ELSE
		BEGIN
			INSERT INTO #FINTEMPAGEING
			SELECT @@CLTCODE, @@BALAMT, @@NODAYS, @@DRCR
			SELECT @@BALAMT = @@BALAMT - @@VAMT
		END
		FETCH NEXT FROM @@BALCUR INTO   @@VTYP, @@VNO, @@EVDT, @@VAMT, @@CLOSBAL, @@NODAYS
		END
		IF @@BALAMT > 0
		BEGIN
			INSERT INTO #FINTEMPAGEING
			SELECT @@OCLTCODE, @@BALAMT, @DAYS5, @@DRCR
			SELECT @@BALAMT = @@BALAMT - @@VAMT
		END
		BREAK
	END
	CLOSE @@BALCUR
	DEALLOCATE @@BALCUR

	FETCH NEXT FROM @@PARTYCUR INTO @@CLTCODE
END

SELECT UPPER(CLTCODE) AS CLTCODE, BALANCE=SUM(BALAMT), AGEDAYS = @DAYS1, DRCR  INTO #AGEINGLIST
FROM #FINTEMPAGEING
WHERE AGEDAYS >= 0 AND AGEDAYS <= @DAYS1
GROUP BY UPPER(CLTCODE), DRCR

CREATE   INDEX [INDXTMP5] ON [DBO].[#AGEINGLIST] ([CLTCODE])

INSERT INTO #AGEINGLIST
SELECT UPPER(CLTCODE) AS CLTCODE, BALANCE=SUM(BALAMT), AGEDAYS = @DAYS2, DRCR
FROM #FINTEMPAGEING
WHERE AGEDAYS >= (@DAYS1 + 1) AND AGEDAYS <= @DAYS2
GROUP BY UPPER(CLTCODE), DRCR

INSERT INTO #AGEINGLIST
SELECT UPPER(CLTCODE) AS CLTCODE, BALANCE=SUM(BALAMT), AGEDAYS = @DAYS3, DRCR
FROM #FINTEMPAGEING
WHERE AGEDAYS >= (@DAYS2 + 1) AND AGEDAYS <= @DAYS3
GROUP BY UPPER(CLTCODE), DRCR

INSERT INTO #AGEINGLIST
SELECT UPPER(CLTCODE) AS CLTCODE, BALANCE=SUM(BALAMT), AGEDAYS = @DAYS4, DRCR
FROM #FINTEMPAGEING
WHERE AGEDAYS >= (@DAYS3 + 1) AND AGEDAYS <= @DAYS4
GROUP BY UPPER(CLTCODE), DRCR


INSERT INTO #AGEINGLIST
SELECT UPPER(CLTCODE) AS CLTCODE, BALANCE=SUM(BALAMT), AGEDAYS = @DAYS5, DRCR
FROM #FINTEMPAGEING
WHERE AGEDAYS >= @DAYS5
GROUP BY UPPER(CLTCODE), DRCR


IF UPPER(@STATUSID) = 'SUBBROKER'
BEGIN
	IF UPPER(@CLIENTTYPE)='ALL'
	BEGIN
		SELECT A1.CLTCODE, A2.CL_TYPE, SHORT_NAME = LEFT(A2.SHORT_NAME,18), A2.BRANCH_CD AS BRANCHCODE,BALANCE, AGEDAYS, A1.DRCR, SUB_BROKER, TRADER, AREA, REGION
		FROM #AGEINGLIST A1 WITH(INDEX(INDXTMP5)) , MSAJAG.DBO.Client_Details A2
		WHERE
		A1.CLTCODE = A2.CL_CODE
		AND A1.CLTCODE=A2.CL_CODE
		/*AND A2.CL_TYPE IN ('ONL','OFL','INS','ONO','NRI','NON','BAF','BAO','REM','IFA')*/ --Commented on 11 Oct 2012 Santosh B
		AND SUB_BROKER = @STATUSNAME
		ORDER BY A2.CL_CODE, A2.SHORT_NAME
	END
	ELSE
		BEGIN
		SELECT A1.CLTCODE, A2.CL_TYPE, SHORT_NAME = LEFT(A2.SHORT_NAME,18), A2.BRANCH_CD AS BRANCHCODE,BALANCE, AGEDAYS, A1.DRCR, SUB_BROKER, TRADER, AREA, REGION
		FROM #AGEINGLIST A1 WITH(INDEX(INDXTMP5)) , MSAJAG.DBO.Client_Details A2
		WHERE
		A1.CLTCODE = A2.CL_CODE
		AND A1.CLTCODE=A2.CL_CODE
		AND A2.CL_TYPE=@CLIENTTYPE
		AND SUB_BROKER = @STATUSNAME
		ORDER BY A2.CL_CODE, A2.SHORT_NAME
	END
END
ELSE IF UPPER(@STATUSID) = 'TRADER'
BEGIN
	IF UPPER(@CLIENTTYPE)='ALL'
	BEGIN
		SELECT A1.CLTCODE, A2.CL_TYPE, SHORT_NAME = LEFT(A2.SHORT_NAME,18), A2.BRANCH_CD AS BRANCHCODE,BALANCE, AGEDAYS, A1.DRCR, SUB_BROKER, TRADER, AREA, REGION
		FROM #AGEINGLIST A1 WITH(INDEX(INDXTMP5)) , MSAJAG.DBO.Client_Details A2
		WHERE
		A1.CLTCODE = A2.CL_CODE
		AND A1.CLTCODE=A2.CL_CODE
		--AND A2.CL_TYPE IN ('ONL','OFL','INS','ONO','NRI','NON','BAF','BAO','REM','IFA')
		AND TRADER = @STATUSNAME
		ORDER BY A2.CL_CODE, A2.SHORT_NAME
	END
	ELSE
	BEGIN
		SELECT A1.CLTCODE, A2.CL_TYPE, SHORT_NAME = LEFT(A2.SHORT_NAME,18), A2.BRANCH_CD AS BRANCHCODE,BALANCE, AGEDAYS, A1.DRCR, SUB_BROKER, TRADER, AREA, REGION
		FROM #AGEINGLIST A1 WITH(INDEX(INDXTMP5)) , MSAJAG.DBO.Client_Details A2
		WHERE
		A1.CLTCODE = A2.CL_CODE
		AND A1.CLTCODE=A2.CL_CODE
		AND A2.CL_TYPE=@CLIENTTYPE
		AND TRADER = @STATUSNAME
		ORDER BY A2.CL_CODE, A2.SHORT_NAME
	END
END
ELSE IF UPPER(@STATUSID) = 'AREA'
BEGIN
	IF UPPER(@CLIENTTYPE)='ALL'
	BEGIN
		SELECT A1.CLTCODE,A2.CL_TYPE, SHORT_NAME = LEFT(A2.SHORT_NAME,18), A2.BRANCH_CD AS BRANCHCODE,BALANCE, AGEDAYS, A1.DRCR, SUB_BROKER, TRADER, AREA, REGION
		FROM #AGEINGLIST A1 WITH(INDEX(INDXTMP5)) , MSAJAG.DBO.Client_Details A2
		WHERE
		A1.CLTCODE = A2.CL_CODE
		AND A1.CLTCODE=A2.CL_CODE
		--AND A2.CL_TYPE IN ('ONL','OFL','INS','ONO','NRI','NON','BAF','BAO','REM','IFA')
		AND AREA = @STATUSNAME
		ORDER BY A2.CL_CODE, A2.SHORT_NAME
	END
	ELSE
	BEGIN
		SELECT A1.CLTCODE,A2.CL_TYPE, SHORT_NAME = LEFT(A2.SHORT_NAME,18), A2.BRANCH_CD AS BRANCHCODE,BALANCE, AGEDAYS, A1.DRCR, SUB_BROKER, TRADER, AREA, REGION
		FROM #AGEINGLIST A1 WITH(INDEX(INDXTMP5)) , MSAJAG.DBO.Client_Details A2
		WHERE
		A1.CLTCODE = A2.CL_CODE
		AND A1.CLTCODE=A2.CL_CODE
		AND A2.CL_TYPE=@CLIENTTYPE
		AND AREA = @STATUSNAME
		ORDER BY A2.CL_CODE, A2.SHORT_NAME
	END
END

ELSE IF UPPER(@STATUSID) = 'REGION'
BEGIN
	IF UPPER(@CLIENTTYPE)='ALL'
	BEGIN
		SELECT A1.CLTCODE,A2.CL_TYPE, SHORT_NAME = LEFT(A2.SHORT_NAME,18), A2.BRANCH_CD AS BRANCHCODE,BALANCE, AGEDAYS, A1.DRCR, SUB_BROKER, TRADER, AREA, REGION
		FROM #AGEINGLIST A1 WITH(INDEX(INDXTMP5)) , MSAJAG.DBO.CLIENT1 A2
		WHERE
		A1.CLTCODE = A2.CL_CODE
		AND A1.CLTCODE=A2.CL_CODE
		--AND A2.CL_TYPE IN ('ONL','OFL','INS','ONO','NRI','NON','BAF','BAO','REM','IFA')
		AND REGION = @STATUSNAME
		ORDER BY A2.CL_CODE, A2.SHORT_NAME
	END
	ELSE
	BEGIN
		SELECT A1.CLTCODE,A2.CL_TYPE, SHORT_NAME = LEFT(A2.SHORT_NAME,18), A2.BRANCH_CD AS BRANCHCODE,BALANCE, AGEDAYS, A1.DRCR, SUB_BROKER, TRADER, AREA, REGION
		FROM #AGEINGLIST A1 WITH(INDEX(INDXTMP5)) , MSAJAG.DBO.Client_Details A2
		WHERE
		A1.CLTCODE = A2.CL_CODE
		AND A1.CLTCODE=A2.CL_CODE
		AND A2.CL_TYPE=@CLIENTTYPE
		AND REGION = @STATUSNAME
		ORDER BY A2.CL_CODE, A2.SHORT_NAME
	END
END
ELSE
IF UPPER(@CLIENTTYPE)='ALL'
BEGIN
	--PRINT 'ALL'
	SELECT A1.CLTCODE, C1.CL_TYPE, SHORT_NAME = LEFT(A2.ACNAME,18), A2.BRANCHCODE, BALANCE, AGEDAYS, A1.DRCR, SUB_BROKER, TRADER, AREA, REGION
	FROM #AGEINGLIST A1 WITH(INDEX(INDXTMP5)) ,   ACMAST A2 ,MSAJAG.DBO.Client_Details C1
	WHERE
	A1.CLTCODE = A2.CLTCODE
	AND A1.CLTCODE=C1.CL_CODE
	--AND C1.CL_TYPE IN ('ONL','OFL','INS','ONO','NRI','NON','BAF','BAO','REM','IFA')
	ORDER BY A1.CLTCODE,A2.ACNAME
END
ELSE
BEGIN
	--PRINT 'NOTALL'
	SELECT A1.CLTCODE, C1.CL_TYPE, SHORT_NAME = LEFT(A2.ACNAME,18), A2.BRANCHCODE, BALANCE, AGEDAYS, A1.DRCR, SUB_BROKER, TRADER, AREA, REGION
	FROM #AGEINGLIST A1 WITH(INDEX(INDXTMP5)) ,   ACMAST A2 ,MSAJAG.DBO.Client_Details C1
	WHERE
	A1.CLTCODE = A2.CLTCODE
	AND A1.CLTCODE=C1.CL_CODE
	AND C1.CL_TYPE=@CLIENTTYPE
	ORDER BY A1.CLTCODE,A2.ACNAME
END


DROP TABLE #CLOSEBAL
DROP TABLE #LEDGERTRAN
DROP TABLE #FINTEMPAGEING
DROP TABLE #AGEINGLIST

GO
