-- Object: PROCEDURE dbo.CLS_RECON_DELETION_PROCESS
-- Server: 10.253.33.91 | DB: ACCOUNT
--------------------------------------------------




CREATE PROCEDURE [dbo].[CLS_RECON_DELETION_PROCESS]
( @UPLOADID NVARCHAR(50)
,@LOGINNAME NVARCHAR(50))
AS
BEGIN

DECLARE @BANKCODE NVARCHAR(50)
          ,@BANKACCOUNT NVARCHAR(50)
          ,@SEGMENT NVARCHAR(50)
          ,@FILETYPE NVARCHAR(50)

SELECT
	@BANKCODE = BANKCODE
	,@BANKACCOUNT = BANKACCOUNT
	,@SEGMENT = SEGMENT
	,@FILETYPE = FILETYPE
FROM RECON_BANK_FILEUPLOAD_LOGS(NOLOCK)
WHERE UPLOADID = @UPLOADID

 BEGIN TRY

	BEGIN TRAN

			IF(@FILETYPE='CMS')
			BEGIN

				DELETE FROM BANKRECO WHERE Dummy2=@UPLOADID

				--UPDATE L1
				--SET EDT = ''
				--FROM RECON_CMS_DATA N
				--, LEDGER L1
				--WHERE N.VNO = L1.VNO
				--AND N.VTYP = L1.VTYP
				--AND N.BOOKTYPE = L1.BOOKTYPE
				--AND N.VALUEDATE = L1.EDT
				--AND N.UPLOADID = @UPLOADID

				UPDATE L1
				SET RELDT = '' ,refno=''
				FROM RECON_CMS_DATA N
				, LEDGER1 L1
				WHERE N.VNO = L1.VNO
				AND N.VTYP = L1.VTYP
				AND N.BOOKTYPE = L1.BOOKTYPE
				AND N.VALUEDATE = L1.RELDT
				AND N.UPLOADID = @UPLOADID

				--DELETE FROM RECON_CMS_DATA	WHERE UPLOADID = @UPLOADID
				UPDATE RECON_CMS_DATA SET ROWTYPE='DR',MODIFIEDDATE=GETDATE()  
				WHERE UPLOADID = @UPLOADID

			END

			IF(@FILETYPE='NON-CMS' OR @FILETYPE='TECHPROCESS')
			BEGIN

				DELETE FROM BANKRECO WHERE Dummy2=@UPLOADID

				--UPDATE L1
				--SET EDT = ''
				--FROM RECON_NONCMS_DATA N
				--, LEDGER L1
				--WHERE N.VNO = L1.VNO
				--AND N.VTYP = L1.VTYP
				--AND N.BOOKTYPE = L1.BOOKTYPE
				--AND N.VALUEDATE = L1.EDT
				--AND N.UPLOADID = @UPLOADID

				UPDATE L1
				SET RELDT = '',refno=''
				FROM RECON_NONCMS_DATA N
				, LEDGER1 L1
				WHERE N.VNO = L1.VNO
				AND N.VTYP = L1.VTYP
				AND N.BOOKTYPE = L1.BOOKTYPE
				AND N.VALUEDATE = L1.RELDT
				AND N.UPLOADID = @UPLOADID


				UPDATE E SET MATCH_STATUS=0
				FROM RECON_ENCRYPTION_DETAILS E, Recon_NONCMS_Data RN
				WHERE E.CROSS_NO=RN.CROSS_NO
				AND RN.UPLOADID=@UPLOADID
				
				--DELETE FROM RECON_NONCMS_DATA
				--WHERE UPLOADID = @UPLOADID
				UPDATE RECON_NONCMS_DATA SET LedgerBalance='DR', ModifiedDate=GETDATE()
				WHERE UPLOADID = @UPLOADID
			END
			
			INSERT INTO RECON_BANK_DELETION_LOGS (UPLOADID, SEGMENT, BANKCODE, BANKNAME, FILETYPE, BANKACCOUNT, UPLOADFILENAME
			, MODIFIEDDATE, UPLOADSTATUS, UPLOADBY, FILEUPLOAD_SDATE, FILEUPLOAD_EDATE, VALUEDATE ,MatchedFlag, USERNAME, PERFORMDATE)

			SELECT UPLOADID, SEGMENT, BANKCODE, BANKNAME, FILETYPE, BANKACCOUNT, UPLOADFILENAME, MODIFIEDDATE, UPLOADSTATUS, UPLOADBY
			, FILEUPLOAD_SDATE, FILEUPLOAD_EDATE, VALUEDATE,0,@LOGINNAME,GETDATE()
			FROM RECON_BANK_FILEUPLOAD_LOGS(NOLOCK)
			WHERE UPLOADID = @UPLOADID

			DELETE FROM RECON_BANK_FILEUPLOAD_LOGS
			WHERE UPLOADID = @UPLOADID	

		COMMIT

END TRY

BEGIN CATCH

	ROLLBACK

END CATCH
END

GO
