-- Object: PROCEDURE dbo.GST_SERVICE_TAX_SPLIT
-- Server: 10.253.33.91 | DB: ACCOUNT
--------------------------------------------------

CREATE PROC [dbo].[GST_SERVICE_TAX_SPLIT]      
AS      
      
DECLARE @SPLITCODE VARCHAR(10)      
      
DECLARE @GSTDATE DATETIME      
      
SET  @GSTDATE = 'AUG  1 2022'      
      
SELECT @SPLITCODE = ACCODE FROM MSAJAG.DBO.VALANACCOUNT      
WHERE ACNAME = 'SPLIT TAX'      
      
SELECT VNO, VTYP, BOOKTYPE,       
VDT = CONVERT(DATETIME,LEFT(VDT,11)),       
LNO=MAX(LNO)       
INTO #STAXVNO FROM LEDGER      (Nolock)
WHERE VDT >= @GSTDATE      
AND CLTCODE = @SPLITCODE      AND VTYP <>18  
GROUP BY VNO, VTYP, BOOKTYPE, CONVERT(DATETIME,LEFT(VDT,11))      

Create INDeX #VNO on #STAXVNO (VNO,VTYP,BOOKTYPE)
      

SELECT L.VTYP, L.VNO, L.EDT, L.LNO, L.ACNAME, L.DRCR, L.VAMT, L.VDT, L.VNO1, L.REFNO, L.BALAMT,       
    L.NODAYS, L.CDT, L.CLTCODE, L.BOOKTYPE, L.ENTEREDBY, L.PDT, L.CHECKEDBY, L.ACTNODAYS, L.NARRATION       
INTO #LEDGER       
FROM LEDGER L  (Nolock), #STAXVNO V  (Nolock)     
WHERE L.VDT >= @GSTDATE       
AND LEFT(L.VDT,11) = LEFT(V.VDT,11)      
AND L.VNO = V.VNO      
AND L.VTYP = V.VTYP      
AND L.BOOKTYPE = V.BOOKTYPE      
      
SELECT VNO,VTYP,BOOKTYPE,RECCNT = COUNT(1) INTO #WRONGDATA       
FROM (SELECT DISTINCT CLTCODE, VNO,VTYP,BOOKTYPE      
FROM #LEDGER      
WHERE CLTCODE IN (SELECT CLTCODE FROM ACMAST (Nolock) WHERE ACCAT = 4)      
GROUP BY CLTCODE,VNO,VTYP,BOOKTYPE) A      
GROUP BY VNO,VTYP,BOOKTYPE      
HAVING COUNT(1) > 1      
      
DELETE FROM #LEDGER      
WHERE EXISTS (SELECT VNO FROM #WRONGDATA      
     WHERE #WRONGDATA.VNO = #LEDGER.VNO      
     AND #WRONGDATA.VTYP = #LEDGER.VTYP      
     AND   #WRONGDATA.BOOKTYPE = #LEDGER.BOOKTYPE)       
      
SELECT DISTINCT PARTY_CODE, SOURCESTATE = G.STATE,       
    TARGETSTATE = L_STATE, VDT = CONVERT(DATETIME,LEFT(VDT,11)), VNO, VTYP, BOOKTYPE,      
GST_PER = CONVERT(NUMERIC(18,2),0),      
CGST_PER = CONVERT(NUMERIC(18,2),0),      
SGST_PER = CONVERT(NUMERIC(18,2),0),      
IGST_PER = CONVERT(NUMERIC(18,2),0),      
UGST_PER = CONVERT(NUMERIC(18,2),0),      
STATE_CODE = CONVERT(VARCHAR(2),'')      
INTO #FINDATA      
FROM #LEDGER L (Nolock) , MSAJAG.DBO.TBL_CLIENT_GST_DATA C (Nolock), MSAJAG.DBO.TBL_GST_LOCATION G  (Nolock)     
WHERE L.CLTCODE = C.PARTY_CODE      
AND C.GST_LOCATION = G.LOC_CODE      
AND VDT BETWEEN EFF_FROM_DATE AND EFF_TO_DATE      
      
INSERT INTO #FINDATA      
SELECT DISTINCT CL_CODE,SOURCESTATE=OWNER.STATE,       
TARGETSTATE=L_STATE,  VDT=CONVERT(DATETIME,LEFT(VDT,11)), VNO, VTYP, BOOKTYPE,      
GST_PER = CONVERT(NUMERIC(18,2),0),      
CGST_PER = CONVERT(NUMERIC(18,2),0),      
SGST_PER = CONVERT(NUMERIC(18,2),0),      
IGST_PER = CONVERT(NUMERIC(18,2),0),      
UGST_PER = CONVERT(NUMERIC(18,2),0),      
STATE_CODE = CONVERT(VARCHAR(2),'')      
FROM #LEDGER N, MSAJAG.DBO.OWNER OWNER,      
MSAJAG.DBO.TBL_STATE_GST_DATA T (Nolock), MSAJAG.DBO.Client_Details G   (Nolock)   
WHERE  OWNER.STATE = STATE_NAME      
AND VDT BETWEEN T.EFF_FROM_DATE AND T.EFF_TO_DATE         
AND G.CL_CODE NOT IN (SELECT PARTY_CODE FROM #FINDATA (Nolock) WHERE G.CL_CODE = #FINDATA.PARTY_CODE)      
AND G.CL_CODE = N.CLTCODE      
      
DELETE FROM #LEDGER       
WHERE NOT EXISTS (SELECT VNO FROM #FINDATA      
     WHERE #FINDATA.VNO = #LEDGER.VNO      
     AND #FINDATA.VTYP = #LEDGER.VTYP      
     AND   #FINDATA.BOOKTYPE = #LEDGER.BOOKTYPE)       

----- To check and delete entry (To ignore it) has multiple code in sigle VNO with GST SPlT GL code
		SELECT A.Vno,A.Vtyp,A.BOOKTYPE INTO #WRONGDATA1 FROM
		(  SELECT S= SUM(VAMT),VNO,VTYP,BOOKTYPE FROM #LEDGER 
		  GROUP BY VNO,VTYP,BOOKTYPE 
		  )A
		 ,(SELECT S = SUM(VAMT),VNO,VTYP,BOOKTYPE FROM LEDGER  (Nolock)     
		WHERE VDT >= @GSTDATE      
		AND EXISTS (SELECT VNO FROM #LEDGER      
			 WHERE LEDGER.VNO = #LEDGER.VNO      
			 AND LEDGER.VTYP = #LEDGER.VTYP      
			 AND   LEDGER.BOOKTYPE = #LEDGER.BOOKTYPE)  GROUP BY VNO,VTYP,BOOKTYPE  ) B
			 WHERE A.VNO = B.VNO
			 AND A.VTYP =B.VTYP
			 AND A.BOOKTYPE =B.BOOKTYPE
			 AND A.S <> B.S
	 
		DELETE FROM #LEDGER      
		WHERE EXISTS (SELECT VNO FROM #WRONGDATA1      
			 WHERE #WRONGDATA1.VNO = #LEDGER.VNO      
			 AND #WRONGDATA1.VTYP = #LEDGER.VTYP      
			 AND   #WRONGDATA1.BOOKTYPE = #LEDGER.BOOKTYPE)   
----- To check and delete entry has multiple code in sigle VNO with GST SPlT GL code
	  
UPDATE #FINDATA SET TARGETSTATE = SOURCESTATE      
WHERE TARGETSTATE NOT IN (SELECT STATE FROM MSAJAG.DBO.STATE_MASTER WHERE STATE <> 'OTHER')      
      
UPDATE #FINDATA SET      
 GST_PER  = (CASE WHEN TARGETSTATE = SOURCESTATE THEN S.GST_PER ELSE 0 END),      
 CGST_PER = (CASE WHEN TARGETSTATE = SOURCESTATE THEN S.CGST_PER ELSE 0 END),      
 SGST_PER = (CASE WHEN TARGETSTATE = SOURCESTATE AND UTI_FLAG = 0 THEN S.SGST_PER ELSE 0 END),      
 IGST_PER = (CASE WHEN TARGETSTATE <> SOURCESTATE THEN S.IGST_PER ELSE 0 END),      
 UGST_PER = (CASE WHEN TARGETSTATE = SOURCESTATE AND UTI_FLAG = 1 THEN S.UGST_PER ELSE 0 END),      
 STATE_CODE = S.STATE_CODE       
FROM MSAJAG.DBO.TBL_STATE_GST_DATA S    (Nolock)  
WHERE STATE_NAME = SOURCESTATE      
AND VDT BETWEEN EFF_FROM_DATE AND EFF_TO_DATE      
      
SELECT L.* INTO #SGSTLED FROM #LEDGER L, #FINDATA F       
WHERE LEFT(L.VDT,11) = LEFT(F.VDT,11)       
  AND L.VNO = F.VNO      
  AND L.VTYP = F.VTYP      
  AND L.BOOKTYPE = L.BOOKTYPE      
  AND L.CLTCODE = @SPLITCODE      
  AND (SGST_PER + UGST_PER) > 0       
      
SELECT VNO, VTYP, BOOKTYPE, LNO=MAX(LNO) + 1  
INTO #LINENO    
FROM #LEDGER  
GROUP BY VNO, VTYP, BOOKTYPE  
  
UPDATE #SGSTLED SET CLTCODE = ACCODE, VAMT = ROUND(VAMT * SGST_PER / GST_PER,2),     
LNO = L.LNO-- #SGSTLED.LNO + 1    
FROM MSAJAG.DBO.VALANACCOUNT V, #FINDATA F, #LINENO L    
WHERE LEFT(#SGSTLED.VDT,11) = LEFT(F.VDT,11)     
  AND #SGSTLED.VNO = F.VNO    
  AND #SGSTLED.VTYP = F.VTYP    
  AND #SGSTLED.BOOKTYPE = F.BOOKTYPE    
  AND #SGSTLED.VNO = L.VNO    
  AND #SGSTLED.VTYP = L.VTYP    
  AND #SGSTLED.BOOKTYPE = L.BOOKTYPE  
  AND V.ACNAME = STATE_CODE + '_SGST'    
  AND SGST_PER > 0     
    
UPDATE #SGSTLED SET CLTCODE = ACCODE, VAMT = ROUND(VAMT * UGST_PER / GST_PER,2),     
LNO = L.LNO-- #SGSTLED.LNO + 1   
FROM MSAJAG.DBO.VALANACCOUNT V, #FINDATA F, #LINENO L      
WHERE LEFT(#SGSTLED.VDT,11) = LEFT(F.VDT,11)    
  AND #SGSTLED.VNO = F.VNO    
  AND #SGSTLED.VTYP = F.VTYP    
  AND #SGSTLED.BOOKTYPE = F.BOOKTYPE    
  AND #SGSTLED.VNO = L.VNO    
  AND #SGSTLED.VTYP = L.VTYP    
  AND #SGSTLED.BOOKTYPE = L.BOOKTYPE  
  AND V.ACNAME = STATE_CODE + '_UGST'    
  AND UGST_PER > 0  
        
UPDATE #LEDGER SET VAMT = #LEDGER.VAMT - F.VAMT      
FROM #SGSTLED F      
WHERE LEFT(#LEDGER.VDT,11) = LEFT(F.VDT,11)       
  AND #LEDGER.VNO = F.VNO      
  AND #LEDGER.VTYP = F.VTYP      
  AND #LEDGER.BOOKTYPE = F.BOOKTYPE      
  AND #LEDGER.CLTCODE = @SPLITCODE      
      
UPDATE #LEDGER SET CLTCODE = ACCODE      
FROM MSAJAG.DBO.VALANACCOUNT V, #FINDATA F      
WHERE LEFT(#LEDGER.VDT,11) = LEFT(F.VDT,11)      
  AND #LEDGER.VNO = F.VNO      
  AND #LEDGER.VTYP = F.VTYP      
  AND #LEDGER.BOOKTYPE = F.BOOKTYPE      
  AND V.ACNAME = STATE_CODE + '_CGST'      
  AND CGST_PER > 0       
  AND #LEDGER.CLTCODE = @SPLITCODE      
      
UPDATE #LEDGER SET CLTCODE = ACCODE      
FROM MSAJAG.DBO.VALANACCOUNT V, #FINDATA F      
WHERE LEFT(#LEDGER.VDT,11) = LEFT(F.VDT,11)      
  AND #LEDGER.VNO = F.VNO      
  AND #LEDGER.VTYP = F.VTYP      
  AND #LEDGER.BOOKTYPE = F.BOOKTYPE      
  AND V.ACNAME = STATE_CODE + '_IGST'      
  AND IGST_PER > 0       
  AND #LEDGER.CLTCODE = @SPLITCODE      
      
INSERT INTO #LEDGER       
SELECT * FROM #SGSTLED      
      
UPDATE #LEDGER SET ACNAME = A.ACNAME      
FROM ACMAST A       
WHERE A.CLTCODE = #LEDGER.CLTCODE      
      
DECLARE @CRVAMT MONEY      
DECLARE @DRVAMT MONEY      
DECLARE @CRVAMT_NEW MONEY      
DECLARE @DRVAMT_NEW MONEY      
      
SET @CRVAMT = 0       
SET @DRVAMT = 0       
SET @CRVAMT_NEW = 0       
SET @DRVAMT_NEW = 0       
      
SELECT @CRVAMT = SUM(CASE WHEN DRCR = 'C' THEN VAMT ELSE 0 END),      
    @DRVAMT = SUM(CASE WHEN DRCR = 'D' THEN VAMT ELSE 0 END)      
FROM LEDGER      
WHERE VDT >= @GSTDATE      
AND EXISTS (SELECT VNO FROM #LEDGER      
     WHERE LEDGER.VNO = #LEDGER.VNO      
     AND LEDGER.VTYP = #LEDGER.VTYP      
     AND   LEDGER.BOOKTYPE = #LEDGER.BOOKTYPE)      
      
SELECT @CRVAMT_NEW = SUM(CASE WHEN DRCR = 'C' THEN VAMT ELSE 0 END),      
    @DRVAMT_NEW = SUM(CASE WHEN DRCR = 'D' THEN VAMT ELSE 0 END)      
FROM #LEDGER       
      
IF @CRVAMT = @CRVAMT_NEW AND @DRVAMT = @DRVAMT_NEW      
BEGIN      

 DELETE L FROM LEDGER  L  (Nolock)  
 WHERE VDT >= @GSTDATE      
 AND EXISTS (SELECT VNO FROM #LEDGER  (Nolock)    
      WHERE L.VNO = #LEDGER.VNO      
      AND L.VTYP = #LEDGER.VTYP      
      AND   L.BOOKTYPE = #LEDGER.BOOKTYPE)      

 INSERT INTO LEDGER      
 SELECT VTYP,VNO,EDT,LNO,ACNAME,DRCR,VAMT,VDT,VNO1,REFNO,BALAMT,NODAYS,CDT,CLTCODE,BOOKTYPE,ENTEREDBY,      
 PDT,CHECKEDBY,ACTNODAYS,NARRATION       
 FROM #LEDGER       
END

GO
