-- Object: PROCEDURE dbo.PROC_NBFC_CASH
-- Server: 10.253.33.91 | DB: ACCOUNT
--------------------------------------------------

CREATE PROC [dbo].[PROC_NBFC_CASH]
(
	@TRANSDATE	VARCHAR(11),
	@EXCHANGE	VARCHAR(3),
	@SEGMENT	VARCHAR(7),
	@BATCHNO	INT
)
AS

DECLARE       
--  @PREVDATE_1 VARCHAR(11),      
  @PREVDATE VARCHAR(11),      
  @SDTCUR VARCHAR(11),      
  @CUTOFFDATE DATETIME,
  @RefNo	Varchar(4) 
  
DECLARE @STARTDATE VARCHAR(11)  


SELECT @REFNO = MAX(REFNO) FROM ABVSCITRUS.NBFC.DBO.NBFC_REF_NO
WHERE TRANSDATE = @TRANSDATE AND BATCHNO = @BATCHNO 

SELECT @REFNO = RIGHT('0000'+ @RefNo,4)

SELECT @SDTCUR = SDTCUR FROM PARAMETER      
WHERE @TRANSDATE BETWEEN SDTCUR AND LDTCUR  
  
SELECT CLTCODE, AMOUNT=VAMT, FROM_EXCHANGE=@EXCHANGE, FROM_SEGMENT = @SEGMENT,
TO_EXCHANGE='NBF', TO_SEGMENT = 'NBFC',  
BANKNAME = CONVERT(VARCHAR(4),''),
BANK_GL = CONVERT(VARCHAR(10),''),
JV_GL = CONVERT(VARCHAR(10),''),
NARRATION,
INTNO = CONVERT(VARCHAR(30),'')
INTO #FINALLEDGER_CR  
FROM ABVSCITRUS.ACCOUNTNBFC.DBO.LEDGER_LIVE
WHERE VDT = @TRANSDATE 
AND ACTNODAYS = @BATCHNO 
AND CLTCODE <> 'GB196'
AND DRCR = 'D'
AND CHECKEDBY = @EXCHANGE + 'CASH'

SELECT CLTCODE, AMOUNT = VAMT, FROM_EXCHANGE=@EXCHANGE, FROM_SEGMENT = @SEGMENT,
TO_EXCHANGE='NBF', TO_SEGMENT = 'NBFC',
BANKNAME = CONVERT(VARCHAR(4),''),
BANK_GL = CONVERT(VARCHAR(10),''),
JV_GL = CONVERT(VARCHAR(10),''),
NARRATION,
INTNO = CONVERT(VARCHAR(30),'')
INTO #FINALLEDGER_DR  
FROM ABVSCITRUS.ACCOUNTNBFC.DBO.LEDGER_LIVE   
WHERE VDT = @TRANSDATE 
AND ACTNODAYS = @BATCHNO 
AND CLTCODE <> 'GB196'
AND DRCR = 'C'
AND CHECKEDBY = @EXCHANGE + 'CASH'

SELECT CLTCODE, BNAME = LEFT(BANK_NAME,4), BANK_NAME, ACCNO 
INTO #BNK
	FROM ABVSCITRUS.ACCOUNTNBFC.DBO.MULTIBANKID M, ABVSCITRUS.NBFC.DBO.POBANK P
	WHERE P.BANKID = M.BANKID AND DEFAULTBANK = 1

UPDATE #FINALLEDGER_CR SET BANKNAME = BNAME, NARRATION = 'AMOUNT PAID_' + ACCNO,
INTNO = ACCNO 
FROM #BNK 
WHERE #FINALLEDGER_CR.CLTCODE = #BNK.CLTCODE	

UPDATE #FINALLEDGER_DR SET BANKNAME = BNAME, NARRATION = 'Amount received against_' + ACCNO,
INTNO = ACCNO 
FROM #BNK 
WHERE #FINALLEDGER_DR.CLTCODE = #BNK.CLTCODE	

UPDATE #FINALLEDGER_DR SET BANK_GL = BANK_GLCODE,
INTNO = (CASE WHEN LEFT(N.BANK_NAME,4) = 'INDU' 
			 THEN FILEBROKERCODE+@refno+LTRIM(rtrim(CLTCODE))
			 ELSE ''
		END) 
FROM ABVSCITRUS.NBFC.DBO.NBFC_OTHERGLCODE N
WHERE #FINALLEDGER_DR.FROM_EXCHANGE = N.FROM_EXCHANGE
AND #FINALLEDGER_DR.FROM_SEGMENT = N.FROM_SEGMENT
AND #FINALLEDGER_DR.BANKNAME = N.BANK_NAME 
AND #FINALLEDGER_DR.TO_EXCHANGE = 'NBF'

UPDATE #FINALLEDGER_CR SET BANK_GL = BANK_GLCODE,
INTNO = (CASE WHEN LEFT(N.BANK_NAME,4) = 'INDU' 
			 THEN FILEBROKERCODE+@refno+LTRIM(rtrim(CLTCODE))
			 ELSE ''
		END) 
FROM ABVSCITRUS.NBFC.DBO.NBFC_OTHERGLCODE N
WHERE #FINALLEDGER_CR.FROM_EXCHANGE = N.FROM_EXCHANGE
AND #FINALLEDGER_CR.FROM_SEGMENT = N.FROM_SEGMENT
AND #FINALLEDGER_CR.BANKNAME = N.BANK_NAME
AND #FINALLEDGER_CR.TO_EXCHANGE = 'NBF'

SELECT *,
BANK_GL = CONVERT(VARCHAR(10),''),
JV_GL = CONVERT(VARCHAR(10),''),
INTNO =  CONVERT(VARCHAR(30),'')
INTO #LEDGER_CR FROM LEDGER      
WHERE VTYP = 2 AND 1 =2      
      
SELECT *,
BANK_GL = CONVERT(VARCHAR(10),''),
JV_GL = CONVERT(VARCHAR(10),''),
INTNO =  CONVERT(VARCHAR(30),'')
INTO #LEDGER_DR FROM LEDGER      
WHERE VTYP = 3 AND 1 =2    
      
ALTER TABLE #LEDGER_CR      
ADD SNO INT IDENTITY(1,1)      
      
ALTER TABLE #LEDGER_DR      
ADD SNO INT IDENTITY(1,1)      
      
DECLARE @VNO BIGINT      
      
ALTER TABLE #FINALLEDGER_CR      
ADD SNO INT IDENTITY(1,1)      
      
ALTER TABLE #FINALLEDGER_DR      
ADD SNO INT IDENTITY(1,1)      

TRUNCATE TABLE #LEDGER_CR
TRUNCATE TABLE #LEDGER_DR

SET @VNO = 0       
INSERT INTO #LEDGER_CR      
SELECT VTYP = 2, VNO = SNO, EDT = @TRANSDATE, LNO=1, ACNAME = CLTCODE, DRCR='C', VAMT=ABS(AMOUNT), VDT=@TRANSDATE,VNO1=SNO,    
REFNO=0,BALAMT=0,NODAYS=0,CDT=@TRANSDATE,CLTCODE,BOOKTYPE='01', ENTEREDBY='BACKEND-ANI', PDT = GETDATE(),     
CHECKEDBY =FROM_EXCHANGE+'CASH', '0', NARRATION,
BANK_GL,
JV_GL, INTNO  
FROM #FINALLEDGER_DR  
WHERE BANK_GL <> ''    
ORDER BY SNO      
    
INSERT INTO #LEDGER_DR      
SELECT VTYP = 3, VNO = SNO, EDT = @TRANSDATE, LNO=1, ACNAME = CLTCODE, DRCR='D', VAMT=ABS(AMOUNT), VDT=@TRANSDATE,VNO1=SNO,    
REFNO=0,BALAMT=0,NODAYS=0,CDT=@TRANSDATE,CLTCODE,BOOKTYPE='01', ENTEREDBY='BACKEND-ANI', PDT = GETDATE(),     
CHECKEDBY =FROM_EXCHANGE+'CASH', '0', NARRATION,
BANK_GL,
JV_GL, INTNO         
FROM #FINALLEDGER_CR      
WHERE BANK_GL <> ''
ORDER BY SNO      

SELECT @VNO = ISNULL(MAX(LASTVNO),0) FROM lastvno L      
WHERE VTYP = 2 AND BOOKTYPE = 'E8'       
AND VDT = @SDTCUR      
IF @VNO = 0    
BEGIN     
 SELECT @VNO = CONVERT(VARCHAR,RIGHT(@SDTCUR,4)) + '00000000'    
 INSERT INTO lastvno VALUES (2, 'E8', @SDTCUR, @VNO)    
END      
    
INSERT INTO LEDGER      
SELECT VTYP,VNO=@VNO+SNO,EDT,LNO+1,ACNAME,DRCR,VAMT,VDT=VDT,VNO1=@VNO+SNO,REFNO,BALAMT,NODAYS,CDT,CLTCODE,BOOKTYPE='E8',ENTEREDBY='ANIMESH',      
   PDT,CHECKEDBY,ACTNODAYS=@BATCHNO,NARRATION     
FROM #LEDGER_CR       
    
INSERT INTO LEDGER      
SELECT VTYP,VNO=@VNO+SNO,EDT,LNO,ACNAME,DRCR='D',VAMT,VDT=VDT,VNO1=@VNO+SNO,REFNO,BALAMT,NODAYS,CDT,CLTCODE=BANK_GL,BOOKTYPE='E8',ENTEREDBY='ANIMESH',      
   PDT,CHECKEDBY,ACTNODAYS=@BATCHNO,NARRATION     
FROM #LEDGER_CR       
    
INSERT INTO LEDGER1       
SELECT       
 BNKNAME = '',       
 BRNNAME = 'MUMBAI',       
 DD = 'Q',       
 DDNO = (CASE WHEN INTNO <> '' THEN INTNO ELSE '100214' END),       
 DDDT = VDT,       
 RELDT = '',      
 RELAMT = VAMT,      
 REFNO = '',      
 RECEIPTNO = 0,      
 VTYP,      
 VNO=@VNO+SNO,      
 LNO+1,      
 DRCR,      
 BOOKTYPE='E8',      
 MICRNO = '',      
 SLIPNO = '',      
 SLIPDATE = '',      
 CHEQUEINNAME = '',      
 CHQPRINTED = 0,      
 CLEAR_MODE = ''      
FROM #LEDGER_CR      
    
SELECT @VNO = @VNO + MAX(SNO) FROM #LEDGER_CR      
      
TRUNCATE TABLE #LEDGER_CR    
      
UPDATE lastvno SET LASTVNO = @VNO      
WHERE VTYP = 2 AND BOOKTYPE = 'E8'       
AND VDT = @SDTCUR AND ISNULL(@VNO,0) <> 0       

SET @VNO = 0  
      
SELECT @VNO = ISNULL(MAX(LASTVNO),0) FROM lastvno L      
WHERE VTYP = 3 AND BOOKTYPE = 'E8'       
AND VDT = @SDTCUR      
    
IF @VNO = 0    
BEGIN     
 SELECT @VNO = CONVERT(VARCHAR,RIGHT(@SDTCUR,4)) + '00000000'    
 INSERT INTO lastvno VALUES (3, 'E8', @SDTCUR, @VNO)    
END      
      
INSERT INTO LEDGER      
SELECT VTYP,VNO=@VNO+SNO,EDT,LNO+1,ACNAME,DRCR,VAMT,VDT=VDT,VNO1=@VNO+SNO,REFNO,BALAMT,NODAYS,CDT,CLTCODE,    
BOOKTYPE='E8',ENTEREDBY='ANIMESH',      
   PDT,CHECKEDBY,ACTNODAYS=@BATCHNO,NARRATION FROM #LEDGER_DR       
      
INSERT INTO LEDGER      
SELECT VTYP,VNO=@VNO+SNO,EDT,LNO,ACNAME,DRCR='C',VAMT,VDT=VDT,VNO1=@VNO+SNO,REFNO,BALAMT,NODAYS,CDT,    
CLTCODE=BANK_GL,BOOKTYPE='E8',ENTEREDBY='ANIMESH',      
   PDT,CHECKEDBY,ACTNODAYS=@BATCHNO,NARRATION FROM #LEDGER_DR       


INSERT INTO LEDGER1       
SELECT       
 BNKNAME = '',       
 BRNNAME = 'MUMBAI',       
 DD = 'Q',       
 DDNO = (CASE WHEN INTNO <> '' THEN INTNO ELSE '100214' END),       
 DDDT = VDT,       
 RELDT = '',      
 RELAMT = VAMT,      
 REFNO = '',      
 RECEIPTNO = 0,      
 VTYP,      
 VNO=@VNO+SNO,      
 LNO+1,      
 DRCR,      
 BOOKTYPE='E8',      
 MICRNO = '',      
 SLIPNO = '',      
 SLIPDATE = '',      
 CHEQUEINNAME = '',      
 CHQPRINTED = 0,      
 CLEAR_MODE = ''      
FROM #LEDGER_DR      
     
SELECT @VNO = @VNO + MAX(SNO) FROM #LEDGER_DR      
      
TRUNCATE TABLE #LEDGER_DR    
     
UPDATE lastvno SET LASTVNO = @VNO      
WHERE VTYP = 3 AND BOOKTYPE = 'E8'       
AND VDT = @SDTCUR AND ISNULL(@VNO,0) <> 0   

UPDATE LEDGER SET CLTCODE ='02019' ,ACNAME ='HDFC BK CLIENT A/C H.O'
WHERE CLTCODE ='02014' AND VTYP =3 
AND VDT = @TRANSDATE AND ENTEREDBY ='ANIMESH' AND BOOKTYPE ='E8'

UPDATE LEDGER SET ACNAME = LONGNAME 
FROM ACMAST A      
WHERE VDT = @TRANSDATE AND A.CLTCODE = LEDGER.CLTCODE      
AND LEDGER.ACNAME <> LONGNAME

GO
