-- Object: PROCEDURE dbo.RPT_EDT_LEDGER_ALL
-- Server: 10.253.33.91 | DB: ACCOUNT
--------------------------------------------------

--Altered this SP under SRE-31606
CREATE PROCEDURE [dbo].[RPT_EDT_LEDGER_ALL] (@TODATE DATETIME,@CLTCODE VARCHAR(11))

AS --- EXEC RPT_EDT_LEDGER_ALL 'OCT 11 2021','A686863'

DECLARE @FROMDATE VARCHAR(11)

SELECT @FROMDATE =SDTCUR FROM ACCOUNT.DBO.PARAMETER WHERE @TODATE BETWEEN SDTCUR AND LDTCUR    

SELECT CLTCODE, LEDBAL = ISNULL(SUM(CASE WHEN UPPER(DRCR) = 'C' THEN VAMT ELSE -VAMT END ), 0) , EXCHANGE = 'NSECM' INTO #EDTLED
FROM ACCOUNT.DBO.LEDGER WITH(NOLOCK) 
WHERE EDT LIKE @FROMDATE + '%' AND VTYP = 18  AND CLTCODE = @CLTCODE
GROUP BY CLTCODE 
UNION ALL
SELECT CLTCODE, LEDBAL = ISNULL(SUM( CASE WHEN UPPER(B.DRCR) = 'D' THEN B.VAMT ELSE -B.VAMT END ), 0) , EXCHANGE = 'NSECM'
FROM ACCOUNT.DBO.LEDGER B WITH (NOLOCK) 
WHERE B.VDT < @FROMDATE AND EDT >= @FROMDATE AND CLTCODE = @CLTCODE
GROUP BY CLTCODE
UNION ALL
SELECT CLTCODE, LEDBAL = SUM(CASE WHEN L.DRCR = 'C' THEN L.VAMT ELSE -L.VAMT END) , EXCHANGE = 'NSECM' 
FROM  ACCOUNT.DBO.LEDGER L WITH (NOLOCK) 	
WHERE L.EDT >= @FROMDATE + ' 00:00:00' 	AND L.EDT <= @TODATE + ' 23:59:59' AND VTYP <> 18  AND CLTCODE = @CLTCODE
GROUP BY CLTCODE

INSERT INTO #EDTLED --- BSECM
SELECT CLTCODE, LEDBAL = ISNULL(SUM(CASE WHEN UPPER(DRCR) = 'C' THEN VAMT ELSE -VAMT END ), 0) , EXCHANGE = 'BSECM' 
FROM AngelBSECM.ACCOUNT_AB.DBO.LEDGER WITH(NOLOCK) 
WHERE EDT LIKE @FROMDATE + '%' AND VTYP = 18  AND CLTCODE = @CLTCODE
GROUP BY CLTCODE 
UNION ALL
SELECT CLTCODE, LEDBAL = ISNULL(SUM( CASE WHEN UPPER(B.DRCR) = 'D' THEN B.VAMT ELSE -B.VAMT END ), 0) , EXCHANGE = 'BSECM'
FROM AngelBSECM.ACCOUNT_AB.DBO.LEDGER B WITH (NOLOCK) 
WHERE B.VDT < @FROMDATE AND EDT >= @FROMDATE AND CLTCODE = @CLTCODE
GROUP BY CLTCODE
UNION ALL
SELECT CLTCODE, LEDBAL = SUM(CASE WHEN L.DRCR = 'C' THEN L.VAMT ELSE -L.VAMT END) , EXCHANGE = 'BSECM' 
FROM  AngelBSECM.ACCOUNT_AB.DBO.LEDGER L WITH (NOLOCK) 	
WHERE L.EDT >= @FROMDATE + ' 00:00:00' 	AND L.EDT <= @TODATE + ' 23:59:59' AND VTYP <> 18  AND CLTCODE = @CLTCODE
GROUP BY CLTCODE

INSERT INTO #EDTLED --- NSEFO
SELECT CLTCODE, LEDBAL = ISNULL(SUM(CASE WHEN UPPER(DRCR) = 'C' THEN VAMT ELSE -VAMT END ), 0) , EXCHANGE = 'NSEFO' 
FROM ANGELFO.ACCOUNTFO.DBO.LEDGER WITH(NOLOCK) 
WHERE EDT LIKE @FROMDATE + '%' AND VTYP = 18  AND CLTCODE = @CLTCODE
GROUP BY CLTCODE 
UNION ALL
SELECT CLTCODE, LEDBAL = ISNULL(SUM( CASE WHEN UPPER(B.DRCR) = 'D' THEN B.VAMT ELSE -B.VAMT END ), 0) , EXCHANGE = 'NSEFO'
FROM ANGELFO.ACCOUNTFO.DBO.LEDGER B WITH (NOLOCK) 
WHERE B.VDT < @FROMDATE AND EDT >= @FROMDATE AND CLTCODE = @CLTCODE
GROUP BY CLTCODE
UNION ALL
SELECT CLTCODE, LEDBAL = SUM(CASE WHEN L.DRCR = 'C' THEN L.VAMT ELSE -L.VAMT END) , EXCHANGE = 'NSEFO' 
FROM  ANGELFO.ACCOUNTFO.DBO.LEDGER L WITH (NOLOCK) 	
WHERE L.EDT >= @FROMDATE + ' 00:00:00' 	AND L.EDT <= @TODATE + ' 23:59:59' AND VTYP <> 18  AND CLTCODE = @CLTCODE
GROUP BY CLTCODE

INSERT INTO #EDTLED --- BSEFO
SELECT CLTCODE, LEDBAL = ISNULL(SUM(CASE WHEN UPPER(DRCR) = 'C' THEN VAMT ELSE -VAMT END ), 0) , EXCHANGE = 'BSEFO' 
FROM ANGELCOMMODITY.ACCOUNTBFO.DBO.LEDGER WITH(NOLOCK) 
WHERE EDT LIKE @FROMDATE + '%' AND VTYP = 18  AND CLTCODE = @CLTCODE
GROUP BY CLTCODE 
UNION ALL
SELECT CLTCODE, LEDBAL = ISNULL(SUM( CASE WHEN UPPER(B.DRCR) = 'D' THEN B.VAMT ELSE -B.VAMT END ), 0) , EXCHANGE = 'BSEFO'
FROM ANGELCOMMODITY.ACCOUNTBFO.DBO.LEDGER B WITH (NOLOCK) 
WHERE B.VDT < @FROMDATE AND EDT >= @FROMDATE AND CLTCODE = @CLTCODE
GROUP BY CLTCODE
UNION ALL
SELECT CLTCODE, LEDBAL = SUM(CASE WHEN L.DRCR = 'C' THEN L.VAMT ELSE -L.VAMT END) , EXCHANGE = 'BSEFO' 
FROM  ANGELCOMMODITY.ACCOUNTBFO.DBO.LEDGER L WITH (NOLOCK) 	
WHERE L.EDT >= @FROMDATE + ' 00:00:00' 	AND L.EDT <= @TODATE + ' 23:59:59' AND VTYP <> 18  AND CLTCODE = @CLTCODE
GROUP BY CLTCODE

INSERT INTO #EDTLED --- NSECD
SELECT CLTCODE, LEDBAL = ISNULL(SUM(CASE WHEN UPPER(DRCR) = 'C' THEN VAMT ELSE -VAMT END ), 0) , EXCHANGE = 'NSECD' 
FROM ANGELFO.ACCOUNTCURFO.DBO.LEDGER WITH(NOLOCK) 
WHERE EDT LIKE @FROMDATE + '%' AND VTYP = 18  AND CLTCODE = @CLTCODE
GROUP BY CLTCODE 
UNION ALL
SELECT CLTCODE, LEDBAL = ISNULL(SUM( CASE WHEN UPPER(B.DRCR) = 'D' THEN B.VAMT ELSE -B.VAMT END ), 0) , EXCHANGE = 'NSECD'
FROM ANGELFO.ACCOUNTCURFO.DBO.LEDGER B WITH (NOLOCK) 
WHERE B.VDT < @FROMDATE AND EDT >= @FROMDATE AND CLTCODE = @CLTCODE
GROUP BY CLTCODE
UNION ALL
SELECT CLTCODE, LEDBAL = SUM(CASE WHEN L.DRCR = 'C' THEN L.VAMT ELSE -L.VAMT END) , EXCHANGE = 'NSECD' 
FROM  ANGELFO.ACCOUNTCURFO.DBO.LEDGER L WITH (NOLOCK) 	
WHERE L.EDT >= @FROMDATE + ' 00:00:00' 	AND L.EDT <= @TODATE + ' 23:59:59' AND VTYP <> 18  AND CLTCODE = @CLTCODE
GROUP BY CLTCODE

INSERT INTO #EDTLED --- BSECD
SELECT CLTCODE, LEDBAL = ISNULL(SUM(CASE WHEN UPPER(DRCR) = 'C' THEN VAMT ELSE -VAMT END ), 0) , EXCHANGE = 'BSECD' 
FROM ANGELCOMMODITY.ACCOUNTCURBFO.DBO.LEDGER WITH(NOLOCK) 
WHERE EDT LIKE @FROMDATE + '%' AND VTYP = 18  AND CLTCODE = @CLTCODE
GROUP BY CLTCODE 
UNION ALL
SELECT CLTCODE, LEDBAL = ISNULL(SUM( CASE WHEN UPPER(B.DRCR) = 'D' THEN B.VAMT ELSE -B.VAMT END ), 0) , EXCHANGE = 'BSECD'
FROM ANGELCOMMODITY.ACCOUNTCURBFO.DBO.LEDGER B WITH (NOLOCK) 
WHERE B.VDT < @FROMDATE AND EDT >= @FROMDATE AND CLTCODE = @CLTCODE
GROUP BY CLTCODE
UNION ALL
SELECT CLTCODE, LEDBAL = SUM(CASE WHEN L.DRCR = 'C' THEN L.VAMT ELSE -L.VAMT END) , EXCHANGE = 'BSECD' 
FROM  ANGELCOMMODITY.ACCOUNTCURBFO.DBO.LEDGER L WITH (NOLOCK) 	
WHERE L.EDT >= @FROMDATE + ' 00:00:00' 	AND L.EDT <= @TODATE + ' 23:59:59' AND VTYP <> 18  AND CLTCODE = @CLTCODE
GROUP BY CLTCODE

INSERT INTO #EDTLED --- MCXCD
SELECT CLTCODE, LEDBAL = ISNULL(SUM(CASE WHEN UPPER(DRCR) = 'C' THEN VAMT ELSE -VAMT END ), 0) , EXCHANGE = 'MCXCD' 
FROM ANGELCOMMODITY.ACCOUNTMCDXCDS.DBO.LEDGER WITH(NOLOCK) 
WHERE EDT LIKE @FROMDATE + '%' AND VTYP = 18  AND CLTCODE = @CLTCODE
GROUP BY CLTCODE 
UNION ALL
SELECT CLTCODE, LEDBAL = ISNULL(SUM( CASE WHEN UPPER(B.DRCR) = 'D' THEN B.VAMT ELSE -B.VAMT END ), 0) , EXCHANGE = 'MCXCD'
FROM ANGELCOMMODITY.ACCOUNTMCDXCDS.DBO.LEDGER B WITH (NOLOCK) 
WHERE B.VDT < @FROMDATE AND EDT >= @FROMDATE AND CLTCODE = @CLTCODE
GROUP BY CLTCODE
UNION ALL
SELECT CLTCODE, LEDBAL = SUM(CASE WHEN L.DRCR = 'C' THEN L.VAMT ELSE -L.VAMT END) , EXCHANGE = 'MCXCD' 
FROM  ANGELCOMMODITY.ACCOUNTMCDXCDS.DBO.LEDGER L WITH (NOLOCK) 	
WHERE L.EDT >= @FROMDATE + ' 00:00:00' 	AND L.EDT <= @TODATE + ' 23:59:59' AND VTYP <> 18  AND CLTCODE = @CLTCODE
GROUP BY CLTCODE

INSERT INTO #EDTLED --- MTF
SELECT CLTCODE, LEDBAL = ISNULL(SUM(CASE WHEN UPPER(DRCR) = 'C' THEN VAMT ELSE -VAMT END ), 0) , EXCHANGE = 'MTF' 
FROM MTFTRADE.DBO.LEDGER WITH(NOLOCK) 
WHERE EDT LIKE @FROMDATE + '%' AND VTYP = 18  AND CLTCODE = @CLTCODE
GROUP BY CLTCODE 
UNION ALL
SELECT CLTCODE, LEDBAL = ISNULL(SUM( CASE WHEN UPPER(B.DRCR) = 'D' THEN B.VAMT ELSE -B.VAMT END ), 0) , EXCHANGE = 'MTF'
FROM MTFTRADE.DBO.LEDGER B WITH (NOLOCK) 
WHERE B.VDT < @FROMDATE AND EDT >= @FROMDATE AND CLTCODE = @CLTCODE
GROUP BY CLTCODE
UNION ALL
SELECT CLTCODE, LEDBAL = SUM(CASE WHEN L.DRCR = 'C' THEN L.VAMT ELSE -L.VAMT END) , EXCHANGE = 'MTF' 
FROM  MTFTRADE.DBO.LEDGER L WITH (NOLOCK) 	
WHERE L.EDT >= @FROMDATE + ' 00:00:00' 	AND L.EDT <= @TODATE + ' 23:59:59' AND VTYP <> 18  AND CLTCODE = @CLTCODE
GROUP BY CLTCODE

INSERT INTO #EDTLED --- SLBS
SELECT CLTCODE, LEDBAL = ISNULL(SUM(CASE WHEN UPPER(DRCR) = 'C' THEN VAMT ELSE -VAMT END ), 0) , EXCHANGE = 'SLBS' 
FROM ACCOUNTSLBS.DBO.LEDGER WITH(NOLOCK) 
WHERE EDT LIKE @FROMDATE + '%' AND VTYP = 18  AND CLTCODE = @CLTCODE
GROUP BY CLTCODE 
UNION ALL
SELECT CLTCODE, LEDBAL = ISNULL(SUM( CASE WHEN UPPER(B.DRCR) = 'D' THEN B.VAMT ELSE -B.VAMT END ), 0) , EXCHANGE = 'SLBS'
FROM ACCOUNTSLBS.DBO.LEDGER B WITH (NOLOCK) 
WHERE B.VDT < @FROMDATE AND EDT >= @FROMDATE AND CLTCODE = @CLTCODE
GROUP BY CLTCODE
UNION ALL
SELECT CLTCODE, LEDBAL = SUM(CASE WHEN L.DRCR = 'C' THEN L.VAMT ELSE -L.VAMT END) , EXCHANGE = 'SLBS' 
FROM  ACCOUNTSLBS.DBO.LEDGER L WITH (NOLOCK) 	
WHERE L.EDT >= @FROMDATE + ' 00:00:00' 	AND L.EDT <= @TODATE + ' 23:59:59' AND VTYP <> 18  AND CLTCODE = @CLTCODE
GROUP BY CLTCODE


INSERT INTO #EDTLED --- BSEMF
SELECT CLTCODE,LEDBAL = SUM(DRAMOUNT+CRAMOUNT),EXCHANGE='BSEMF' FROM (
SELECT B.CLTCODE,DRAMOUNT=(-B.DRAMOUNT),B.CRAMOUNT FROM ANGELFO.BBO_FA.DBO.ACC_TBL1 A (NOLOCK), ANGELFO.BBO_FA.DBO.ACC_TBL3 B (NOLOCK)
WHERE A.SNO = B.MASTERSNO
AND CONVERT(DATETIME,CONVERT(VARCHAR(11),EDT)) LIKE @FROMDATE + '%' AND VTYPE = 18  AND CLTCODE = @CLTCODE
UNION ALL 
SELECT B.CLTCODE,DRAMOUNT=B.DRAMOUNT,CRAMOUNT=-B.CRAMOUNT FROM ANGELFO.BBO_FA.DBO.ACC_TBL1 A (NOLOCK), ANGELFO.BBO_FA.DBO.ACC_TBL3 B (NOLOCK)
WHERE A.SNO = B.MASTERSNO
AND CONVERT(DATETIME,CONVERT(VARCHAR(11),VDT)) < @FROMDATE 
AND CONVERT(DATETIME,CONVERT(VARCHAR(11),EDT))>=@FROMDATE  AND CLTCODE = @CLTCODE
UNION ALL
SELECT B.CLTCODE,DRAMOUNT=(-B.DRAMOUNT),B.CRAMOUNT FROM ANGELFO.BBO_FA.DBO.ACC_TBL1 A (NOLOCK), ANGELFO.BBO_FA.DBO.ACC_TBL3 B (NOLOCK)
WHERE A.SNO = B.MASTERSNO
AND CONVERT(DATETIME,CONVERT(VARCHAR(11),EDT)) >= @FROMDATE + ' 00:00:00' 
AND CONVERT(DATETIME,CONVERT(VARCHAR(11),EDT)) <= @TODATE + ' 23:59:59' AND A.VTYPE <> 18  AND CLTCODE = @CLTCODE) A
GROUP BY A.CLTCODE


INSERT INTO #EDTLED --- MCDX
SELECT CLTCODE, LEDBAL = ISNULL(SUM(CASE WHEN UPPER(DRCR) = 'C' THEN VAMT ELSE -VAMT END ), 0) , EXCHANGE = 'MCDX' 
FROM ANGELCOMMODITY.ACCOUNTMCDX.DBO.LEDGER WITH(NOLOCK) 
WHERE EDT LIKE @FROMDATE + '%' AND VTYP = 18  AND CLTCODE = @CLTCODE
GROUP BY CLTCODE 
UNION ALL
SELECT CLTCODE, LEDBAL = ISNULL(SUM( CASE WHEN UPPER(B.DRCR) = 'D' THEN B.VAMT ELSE -B.VAMT END ), 0) , EXCHANGE = 'MCDX'
FROM ANGELCOMMODITY.ACCOUNTMCDX.DBO.LEDGER B WITH (NOLOCK) 
WHERE B.VDT < @FROMDATE AND EDT >= @FROMDATE AND CLTCODE = @CLTCODE
GROUP BY CLTCODE
UNION ALL
SELECT CLTCODE, LEDBAL = SUM(CASE WHEN L.DRCR = 'C' THEN L.VAMT ELSE -L.VAMT END) , EXCHANGE = 'MCDX' 
FROM  ANGELCOMMODITY.ACCOUNTMCDX.DBO.LEDGER L WITH (NOLOCK) 	
WHERE L.EDT >= @FROMDATE + ' 00:00:00' 	AND L.EDT <= @TODATE + ' 23:59:59' AND VTYP <> 18  AND CLTCODE = @CLTCODE
GROUP BY CLTCODE

INSERT INTO #EDTLED --- NCDX
SELECT CLTCODE, LEDBAL = ISNULL(SUM(CASE WHEN UPPER(DRCR) = 'C' THEN VAMT ELSE -VAMT END ), 0) , EXCHANGE = 'NCDX' 
FROM ANGELCOMMODITY.ACCOUNTNCDX.DBO.LEDGER WITH(NOLOCK) 
WHERE EDT LIKE @FROMDATE + '%' AND VTYP = 18  AND CLTCODE = @CLTCODE
GROUP BY CLTCODE 
UNION ALL
SELECT CLTCODE, LEDBAL = ISNULL(SUM( CASE WHEN UPPER(B.DRCR) = 'D' THEN B.VAMT ELSE -B.VAMT END ), 0) , EXCHANGE = 'NCDX'
FROM ANGELCOMMODITY.ACCOUNTNCDX.DBO.LEDGER B WITH (NOLOCK) 
WHERE B.VDT < @FROMDATE AND EDT >= @FROMDATE AND CLTCODE = @CLTCODE
GROUP BY CLTCODE
UNION ALL
SELECT CLTCODE, LEDBAL = SUM(CASE WHEN L.DRCR = 'C' THEN L.VAMT ELSE -L.VAMT END) , EXCHANGE = 'NCDX' 
FROM  ANGELCOMMODITY.ACCOUNTNCDX.DBO.LEDGER L WITH (NOLOCK) 	
WHERE L.EDT >= @FROMDATE + ' 00:00:00' 	AND L.EDT <= @TODATE + ' 23:59:59' AND VTYP <> 18  AND CLTCODE = @CLTCODE
GROUP BY CLTCODE

INSERT INTO #EDTLED --- NCE
SELECT CLTCODE, LEDBAL = ISNULL(SUM(CASE WHEN UPPER(DRCR) = 'C' THEN VAMT ELSE -VAMT END ), 0) , EXCHANGE = 'NCE' 
FROM ANGELCOMMODITY.ACCOUNTNCE.DBO.LEDGER WITH(NOLOCK) 
WHERE EDT LIKE @FROMDATE + '%' AND VTYP = 18  AND CLTCODE = @CLTCODE
GROUP BY CLTCODE 
UNION ALL
SELECT CLTCODE, LEDBAL = ISNULL(SUM( CASE WHEN UPPER(B.DRCR) = 'D' THEN B.VAMT ELSE -B.VAMT END ), 0) , EXCHANGE = 'NCE'
FROM ANGELCOMMODITY.ACCOUNTNCE.DBO.LEDGER B WITH (NOLOCK) 
WHERE B.VDT < @FROMDATE AND EDT >= @FROMDATE AND CLTCODE = @CLTCODE
GROUP BY CLTCODE
UNION ALL
SELECT CLTCODE, LEDBAL = SUM(CASE WHEN L.DRCR = 'C' THEN L.VAMT ELSE -L.VAMT END) , EXCHANGE = 'NCE' 
FROM  ANGELCOMMODITY.ACCOUNTNCE.DBO.LEDGER L WITH (NOLOCK) 	
WHERE L.EDT >= @FROMDATE + ' 00:00:00' 	AND L.EDT <= @TODATE + ' 23:59:59' AND VTYP <> 18  AND CLTCODE = @CLTCODE
GROUP BY CLTCODE

SELECT REPORT_DATE=CONVERT(VARCHAR(11),@TODATE,105),CLTCODE,[NSECM]=ISNULL([NSECM],0),[BSECM]=ISNULL([BSECM],0),
[NSEFO]=ISNULL([NSEFO],0),[BSEFO]=ISNULL([BSEFO],0),[BSEMF]=ISNULL([BSEMF],0),[MTF]=ISNULL([MTF],0),
[SLBS]=ISNULL([SLBS],0),[NSECD]=ISNULL([NSECD],0),[BSECD]=ISNULL([BSECD],0),[MCXCD]=ISNULL([MCXCD],0),
[MCDX]=ISNULL([MCDX],0),[NCDX]=ISNULL([NCDX],0),[NCE]=ISNULL([NCE],0),
NET_BALANCE=ISNULL([NSECM],0)+ISNULL([BSECM],0)+ISNULL([NSEFO],0)+ISNULL([BSEFO],0)+ISNULL([BSEMF],0)+ISNULL([MTF],0)
+ISNULL([SLBS],0)+ISNULL([NSECD],0)+ISNULL([BSECD],0)+ISNULL([MCXCD],0)+ISNULL([MCDX],0)+ISNULL([NCDX],0)+ISNULL([NCE],0)
FROM ( SELECT CLTCODE,LEDBAL,EXCHANGE FROM #EDTLED WHERE CLTCODE BETWEEN 'A' AND 'ZZZZZZZZZ999999999' ) AS SOURCETABLE
PIVOT
(SUM(LEDBAL) FOR EXCHANGE IN ([NSECM],[BSECM],[NSEFO],[BSEFO],[BSEMF],[MTF],[SLBS],[NSECD],[BSECD],[MCXCD],[MCDX],[NCDX],[NCE])) AS PIVOTTABLE
ORDER BY PIVOTTABLE.CLTCODE

GO
