-- Object: PROCEDURE dbo.SEBI_RiskChecking_For_Provisonal
-- Server: 10.253.33.91 | DB: ACCOUNT
--------------------------------------------------

--SEBI_RiskChecking_For_Provisonal '07/12/2023' 
create proc SEBI_RiskChecking_For_Provisonal(@MDATE VARCHAR(11) )
as
DECLARE @TODATE VARCHAR(11) 
set @TODATE=replace(CONVERT(VARCHAR(12),convert(datetime, @MDATE,103),109), '/', ' ')  
--SET @TODATE = 'DEC  7 2023'

DECLARE @FINSTDT DATETIME 

DECLARE @FROMDATE VARCHAR(11)  

SELECT CLTCODE ,SUM(VAMT) AS PAYAMT INTO #CLIENTDATA FROM LEDGER L  WITH (NOLOCK) , MSAJAG.DBO.CLIENT_DETAILS C WITH (NOLOCK) 
WHERE VDT BETWEEN @TODATE AND @TODATE + ' 23:59' AND VTYP = 3 AND L.CLTCODE = C.CL_CODE
--AND NARRATION LIKE '%AMT TRANSFER QUARTERLY SETTLEMENT%'
GROUP BY CLTCODE

CREATE INDEX CLIIDX ON #CLIENTDATA (CLTCODE)

SELECT @FINSTDT = SDTCUR ,@FROMDATE  = SDTCUR FROM ACCOUNT.DBO.PARAMETER WITH (NOLOCK) WHERE @TODATE BETWEEN SDTCUR AND LDTCUR
 
SELECT CLTCODE,SUM(VAMT)AS VAMT,CONVERT(VARCHAR(10),'') AS SEGMENT  INTO #VDTLED FROM (    
SELECT L.CLTCODE,SUM(CASE WHEN DRCR='D'THEN VAMT ELSE -VAMT END)VAMT FROM   ACCOUNT.DBO.LEDGER L WITH(NOLOCK) 
WHERE    VDT>=@FINSTDT   AND  VDT< = @TODATE  + ' 23:59' AND 1 <> 1  GROUP BY L.CLTCODE)A    
 GROUP BY CLTCODE    
 HAVING SUM(VAMT) <>0

SELECT CLTCODE,SUM(VAMT) AS VAMT,CONVERT(VARCHAR(10),'') AS SEGMENT  INTO #EDTLED FROM (    
SELECT L.CLTCODE, VAMT = ISNULL(SUM(CASE WHEN UPPER(DRCR) = 'D' THEN VAMT ELSE -VAMT END ), 0) 
FROM ACCOUNT.DBO.LEDGER L WITH(NOLOCK) 
WHERE EDT >= @FROMDATE + ' 00:00:00' 	AND L.EDT <= @FROMDATE + ' 23:59:59'  AND VTYP = 18   AND 1 <> 1 
GROUP BY L.CLTCODE 
UNION ALL
SELECT L.CLTCODE, VAMT = ISNULL(SUM( CASE WHEN UPPER(DRCR) = 'C' THEN VAMT ELSE -VAMT END ), 0) 
FROM ACCOUNT.DBO.LEDGER L WITH (NOLOCK) 
WHERE VDT < @FROMDATE AND EDT >= @FROMDATE  AND 1 <> 1 
GROUP BY L.CLTCODE
UNION ALL
SELECT L.CLTCODE, VAMT = SUM(CASE WHEN DRCR = 'D' THEN L.VAMT ELSE -VAMT END) 
FROM  ACCOUNT.DBO.LEDGER L WITH (NOLOCK)  
WHERE L.EDT >= @FROMDATE + ' 00:00:00' 	AND L.EDT <= @TODATE + ' 23:59:59' AND VTYP <> 18  AND 1 <> 1  
GROUP BY L.CLTCODE)A     GROUP BY CLTCODE     HAVING SUM(VAMT) <>0

 SELECT * INTO #VDTLED_FINAL FROM #VDTLED WHERE 1 <> 1
 
 SELECT * INTO #EDTLED_FINAL FROM #EDTLED WHERE 1 <> 1

CREATE TABLE #MULTIDATABASE (SERVERNAME VARCHAR(100),DATABASENAME VARCHAR(100),SEGMENT VARCHAR(100),SRNO INT IDENTITY (1,1))

INSERT INTO #MULTIDATABASE SELECT 'ANAND1','ACCOUNT','NSE'
INSERT INTO #MULTIDATABASE SELECT 'ANAND1','ACCOUNTSLBS','SLBM'
INSERT INTO #MULTIDATABASE SELECT 'ANAND1','MTFTRADE','MTF'
INSERT INTO #MULTIDATABASE SELECT 'ANAND','ACCOUNT_AB','BSE'
INSERT INTO #MULTIDATABASE SELECT 'ANGELFO','ACCOUNTFO','NSEFO'
INSERT INTO #MULTIDATABASE SELECT 'ANGELFO','ACCOUNTCURFO','NSX'
INSERT INTO #MULTIDATABASE SELECT 'ANGELCOMMODITY','ACCOUNTNCDX','NCDX'
INSERT INTO #MULTIDATABASE SELECT 'ANGELCOMMODITY','ACCOUNTMCDX','MCX'
INSERT INTO #MULTIDATABASE SELECT 'ANGELCOMMODITY','ACCOUNTMCDXCDS','MCD'
INSERT INTO #MULTIDATABASE SELECT 'ANGELCOMMODITY','ACCOUNTBFO','BSEFO'
INSERT INTO #MULTIDATABASE SELECT 'ANGELCOMMODITY','ACCOUNTCURBFO','BSECURFO'


DECLARE @SNAME VARCHAR(100),@DNAME VARCHAR(100),@SEGMENT VARCHAR(100),@SRNOMAX INT,@COUNTINT INT

SET @COUNTINT = 1

SELECT @SRNOMAX = MAX(SRNO) FROM #MULTIDATABASE

WHILE @COUNTINT <= @SRNOMAX
BEGIN

SELECT @SNAME = SERVERNAME , @DNAME = DATABASENAME ,@SEGMENT = SEGMENT FROM #MULTIDATABASE WHERE SRNO = @COUNTINT

IF @SNAME = 'ANAND1'
BEGIN 

TRUNCATE TABLE #VDTLED

EXEC ('INSERT INTO #VDTLED
SELECT L.CLTCODE,SUM(CASE WHEN DRCR= ''D'' THEN -VAMT ELSE VAMT END) AS VAMT,''' + @SEGMENT + '''  FROM ' + @DNAME + '.DBO.LEDGER  L WITH (NOLOCK) 
WHERE  VDT BETWEEN ''' + @FINSTDT + ''' AND ''' + @TODATE + ' 23:59:59'' GROUP BY L.CLTCODE HAVING SUM(VAMT) <> 0 ') 

INSERT INTO #VDTLED_FINAL SELECT * FROM #VDTLED


TRUNCATE TABLE #EDTLED


EXEC ('INSERT  INTO #EDTLED  SELECT CLTCODE,SUM(VAMT) AS VAMT,SEGMENT FROM (    
SELECT L.CLTCODE, ISNULL(SUM(CASE WHEN UPPER(DRCR) = ''D'' THEN VAMT ELSE -VAMT END ), 0) AS VAMT , SEGMENT = ''' + @SEGMENT + '''  FROM ' + @DNAME + '.DBO.LEDGER  L WITH (NOLOCK) 
WHERE L.EDT >= ''' + @FROMDATE + '''' + '+ '' 00:00:00'' AND L.EDT <=  ''' + @FROMDATE + '''' + '+ '' 23:59:59'' AND VTYP = 18  
GROUP BY L.CLTCODE 
UNION ALL
SELECT L.CLTCODE, ISNULL(SUM( CASE WHEN UPPER(DRCR) = ''C'' THEN VAMT ELSE -VAMT END ), 0) AS VAMT , SEGMENT = ''' + @SEGMENT + '''  FROM ' + @DNAME + '.DBO.LEDGER  L WITH (NOLOCK) 
WHERE VDT < ''' + @FROMDATE  + ''' AND EDT >= ''' + @FROMDATE  + '''  
GROUP BY L.CLTCODE
UNION ALL
SELECT L.CLTCODE, SUM(CASE WHEN DRCR = ''D'' THEN L.VAMT ELSE -VAMT END) AS VAMT , SEGMENT = ''' + @SEGMENT + '''  FROM ' + @DNAME + '.DBO.LEDGER  L WITH (NOLOCK)  
WHERE L.EDT >= ''' + @FROMDATE + '''' + '+ '' 00:00:00'' AND L.EDT <=  ''' + @TODATE + '''' + '+ '' 23:59:59'' AND VTYP <> 18   
GROUP BY L.CLTCODE)A     GROUP BY CLTCODE,SEGMENT     HAVING SUM(VAMT) <> 0 ') 


INSERT INTO #EDTLED_FINAL SELECT * FROM #EDTLED


END
ELSE
BEGIN
TRUNCATE TABLE #VDTLED

EXEC ('INSERT INTO #VDTLED
SELECT L.CLTCODE,SUM(CASE WHEN DRCR= ''D'' THEN -VAMT ELSE VAMT END) AS VAMT,''' + @SEGMENT + '''  FROM ' + @SNAME + '.' + @DNAME + '.DBO.LEDGER L WITH (NOLOCK)  
WHERE  VDT BETWEEN ''' + @FINSTDT + ''' AND ''' + @TODATE + ' 23:59:59''    GROUP BY L.CLTCODE HAVING SUM(VAMT) <> 0 ') 

INSERT INTO #VDTLED_FINAL SELECT * FROM #VDTLED


TRUNCATE TABLE #EDTLED


EXEC ('INSERT  INTO #EDTLED  SELECT CLTCODE,SUM(VAMT) AS VAMT,SEGMENT FROM (    
SELECT L.CLTCODE, ISNULL(SUM(CASE WHEN UPPER(DRCR) = ''D'' THEN VAMT ELSE -VAMT END ), 0) AS VAMT , SEGMENT = ''' + @SEGMENT + '''  FROM ' + @SNAME + '.' + @DNAME + '.DBO.LEDGER  L WITH (NOLOCK)  
WHERE L.EDT >= ''' + @FROMDATE + '''' + '+ '' 00:00:00'' AND L.EDT <=  ''' + @FROMDATE + '''' + '+ '' 23:59:59'' AND VTYP = 18    
GROUP BY L.CLTCODE 
UNION ALL
SELECT L.CLTCODE, ISNULL(SUM( CASE WHEN UPPER(DRCR) = ''C'' THEN VAMT ELSE -VAMT END ), 0) AS VAMT , SEGMENT = ''' + @SEGMENT + '''  FROM ' + @SNAME + '.' + @DNAME + '.DBO.LEDGER  L WITH (NOLOCK) 
WHERE VDT < ''' + @FROMDATE  + ''' AND EDT >= ''' + @FROMDATE  + '''  
GROUP BY L.CLTCODE
UNION ALL
SELECT L.CLTCODE, SUM(CASE WHEN DRCR = ''D'' THEN L.VAMT ELSE -VAMT END) AS VAMT , SEGMENT = ''' + @SEGMENT + '''  FROM ' + @SNAME + '.' + @DNAME + '.DBO.LEDGER  L WITH (NOLOCK) 
WHERE L.EDT >= ''' + @FROMDATE + '''' + '+ '' 00:00:00'' AND L.EDT <=  ''' + @TODATE + '''' + '+ '' 23:59:59'' AND VTYP <> 18   
GROUP BY L.CLTCODE)A     GROUP BY CLTCODE,SEGMENT     HAVING SUM(VAMT) <> 0 ') 


INSERT INTO #EDTLED_FINAL SELECT * FROM #EDTLED

END

SET @COUNTINT = @COUNTINT + 1

END

SELECT CLTCODE,ISNULL([BSE],0) AS [BSE],ISNULL([BSECURFO],0) AS [BSECURFO],ISNULL([BSEFO],0) AS [BSEFO],
ISNULL([MCD],0) AS [MCD],ISNULL([MCX],0) AS [MCX],ISNULL([MTF] ,0) AS [MTF],
ISNULL([NCDX],0) AS [NCDX] ,ISNULL([NSE],0) AS [NSE],ISNULL([NSEFO],0) AS [NSEFO],ISNULL([NSX],0) AS [NSX],ISNULL([SLBM],0) AS [SLBM]
,ISNULL([BSE],0)+ISNULL([BSECURFO],0)+ISNULL([BSEFO],0)+ISNULL([MCD],0)+ISNULL([MCX],0)+ISNULL([MTF] ,0)+
ISNULL([NCDX],0)+ISNULL([NSE],0)+ISNULL([NSEFO],0)+ISNULL([NSX],0)+ISNULL([SLBM],0) AS TOTAL INTO #TEMP_VDT
FROM
(SELECT CLTCODE,VAMT,SEGMENT FROM #VDTLED_FINAL) AS A
PIVOT
(SUM(VAMT) FOR SEGMENT IN ([BSE],[BSECURFO],[BSEFO],[MCD],[MCX],[MTF],[NCDX],[NSE],[NSEFO],[NSX],[SLBM] )) AS B


CREATE INDEX CLIIDX ON #TEMP_VDT (CLTCODE)

  SELECT  CLTCODE,NSE AS NSE,BSE AS BSE,[NSEFO] AS FO,NSX AS NSX,    
  MCD AS MCD ,MCX AS MCX,[NCDX] AS NCX,BSEFO AS BSEFO,[BSECURFO] AS BSX,MTF AS MTF,[SLBM] AS SLBS,    
      TOTAL AS TOTAL  INTO #TEMP_VDT1
	  FROM #TEMP_VDT 
	   UNION ALL
	SELECT   CLTCODE,0 AS NSE,0 AS BSE,0 AS FO,0 AS NSX,    
  0 AS MCD ,0 AS MCX,0 AS NCX,0 AS BSEFO,0 AS BSX,0 AS MTF,0 AS SLBS,    
      0 AS TOTAL FROM #CLIENTDATA WHERE CLTCODE NOT IN (SELECT CLTCODE FROM #TEMP_VDT)
	



SELECT CLTCODE,ISNULL([BSE],0) AS [BSE],ISNULL([BSECURFO],0) AS [BSECURFO],ISNULL([BSEFO],0) AS [BSEFO],
ISNULL([MCD],0) AS [MCD],ISNULL([MCX],0) AS [MCX],ISNULL([MTF] ,0) AS [MTF],
ISNULL([NCDX],0) AS [NCDX] ,ISNULL([NSE],0) AS [NSE],ISNULL([NSEFO],0) AS [NSEFO],ISNULL([NSX],0) AS [NSX],ISNULL([SLBM],0) AS [SLBM]
,ISNULL([BSE],0)+ISNULL([BSECURFO],0)+ISNULL([BSEFO],0)+ISNULL([MCD],0)+ISNULL([MCX],0)+ISNULL([MTF] ,0)+
ISNULL([NCDX],0)+ISNULL([NSE],0)+ISNULL([NSEFO],0)+ISNULL([NSX],0)+ISNULL([SLBM],0) AS TOTAL INTO #TEMP_EDT
FROM
(SELECT CLTCODE,VAMT,SEGMENT FROM #EDTLED_FINAL) AS A
PIVOT
(SUM(VAMT) FOR SEGMENT IN ([BSE],[BSECURFO],[BSEFO],[MCD],[MCX],[MTF],[NCDX],[NSE],[NSEFO],[NSX],[SLBM] )) AS B

CREATE INDEX CLIIDX ON #TEMP_EDT (CLTCODE)

  SELECT  CLTCODE,NSE*-1 AS NSE,BSE*-1 AS BSE,[NSEFO]*-1 AS FO,NSX*-1 AS NSX,    
  MCD*-1 AS MCD ,MCX*-1 AS MCX,[NCDX]*-1 AS NCX,BSEFO*-1 AS BSEFO,[BSECURFO] AS BSX,MTF*-1 AS MTF,[SLBM]*-1 AS SLBS,    
      TOTAL*-1 AS TOTAL  INTO #TEMP_EDT1
	  FROM #TEMP_EDT 
	  UNION ALL
	SELECT   CLTCODE,0 AS NSE,0 AS BSE,0 AS FO,0 AS NSX,    
  0 AS MCD ,0 AS MCX,0 AS NCX,0 AS BSEFO,0 AS BSX,0 AS MTF,0 AS SLBS,    
      0 AS TOTAL FROM #CLIENTDATA WHERE CLTCODE NOT IN (SELECT CLTCODE FROM #TEMP_EDT)


CREATE INDEX CLIIDX ON #TEMP_VDT1 (CLTCODE)
CREATE INDEX CLIIDX ON #TEMP_EDT1 (CLTCODE)


SELECT C.CLTCODE,E.TOTAL AS ETOTAL,V.TOTAL AS VTOTAL,PAYAMT FROM #TEMP_EDT1 E , #TEMP_VDT1 V, #CLIENTDATA C 
WHERE C.CLTCODE = V.CLTCODE AND C.CLTCODE = E.CLTCODE
AND (E.TOTAL < 0  )

DROP TABLE #TEMP_VDT
DROP TABLE #VDTLED_FINAL
DROP TABLE #VDTLED
DROP TABLE #MULTIDATABASE
DROP TABLE #CLIENTDATA
DROP TABLE #TEMP_VDT1
DROP TABLE #TEMP_EDT
DROP TABLE #EDTLED_FINAL
DROP TABLE #EDTLED
DROP TABLE #TEMP_EDT1

GO
