-- Object: PROCEDURE dbo.CREATEPARTYLEDGER
-- Server: 10.253.33.91 | DB: ACCOUNT
--------------------------------------------------

CREATE PROC CREATEPARTYLEDGER
AS
CREATE TABLE NEWPARTYLEDGER
	(
		BRANCH_CODE VARCHAR(11),
		BRANCH VARCHAR(40),
		CLTCODE VARCHAR(11),
		ACNAME VARCHAR(50),
		VDT DATETIME,
		EDT DATETIME,
		VAMT MONEY DEFAULT(0) NOT NULL,
		MAMT MONEY DEFAULT(0) NOT NULL,
		SPID SMALLINT
	)

GO
