-- Object: PROCEDURE dbo.CLS_RECON_NONCMS_AXIS_PROCESS_BKP_04112023
-- Server: 10.253.33.91 | DB: ACCOUNT
--------------------------------------------------




CREATE PROCEDURE [dbo].[CLS_RECON_NONCMS_AXIS_PROCESS_BKP_04112023]
( @UPLOADID NVARCHAR(50) 
,@BANKCODE NVARCHAR(50)
,@FILE_PATH NVARCHAR(150)
,@UNAME NVARCHAR(50)) 

AS
BEGIN
BEGIN TRY

INSERT INTO #NONCMS_DATA (
		UPLOADID
		, BANKACCOUNT
		, BANKCODE
		, DESCRIPTION
		, LEDGERBALANCE
		, DRCR
		, AMT
		, VALUEDATE
		, REFERENCENO
		, CLTACCOUNT
		, CUSTOMERREFERENCE
		, TRANSACTIONDETAIL
		, VNO
		, VTYP
		, BOOKTYPE
		, MATCHEDFLAG
		, UPLOADSTATUS
		, UPLOADEDDATE
		, MODIFIEDDATE
		, UPLOADBY)
	SELECT
	U.UPLOADID
	,(SELECT BANKACCOUNT FROM RECON_BANK_FILEUPLOAD_LOGS(NOLOCK) WHERE UPLOADID=@UPLOADID) AS 'BANKACCOUNT'
	,@BANKCODE AS 'BANKCODE'
	,RTRIM(LTRIM(ISNULL(DBO.PIECE(FILE_DATA,'Æ',4) , ''))) AS 'DESCRIPTION'
	,'' AS 'LEDGERBALANCE'	
	,CASE WHEN RTRIM(LTRIM(ISNULL(DBO.PIECE(FILE_DATA,'Æ',6) , '')))='CR' THEN 'C'
		WHEN RTRIM(LTRIM(ISNULL(DBO.PIECE(FILE_DATA,'Æ',6) , '')))='DR' THEN 'D' ELSE '' END AS 'DRCR'
	
	,CAST (RTRIM(LTRIM(DBO.PIECE(FILE_DATA,'Æ',5))) AS DECIMAL(20,2)) AS 'AMT'
	--,CAST(RTRIM(LTRIM(DBO.PIECE(FILE_DATA,'Æ',2))) AS DATETIME) AS 'VALUEDATE'
	,CONVERT(DATETIME, RTRIM(LTRIM(.DBO.PIECE(FILE_DATA,'Æ',2))), 103) AS 'VALUEDATE'
	,CASE WHEN  DBO.PIECE(FILE_DATA,'Æ',4) LIKE '%ICONN/%' THEN .DBO.PIECE(DBO.PIECE(FILE_DATA,'Æ',4),'/',2)
		  WHEN ISNULL(DBO.PIECE(FILE_DATA,'Æ',3) , '')='' OR ISNULL(DBO.PIECE(FILE_DATA,'Æ',3) , '')='-'  THEN '' 	        
		  ELSE ISNULL(RTRIM(LTRIM(DBO.PIECE(FILE_DATA,'Æ',3))) , '')  END AS 'REFERENCENO'
	,'' AS 'CLTACCOUNT'
	,'' AS 'CUSTOMERREFERENCE'
	,'' AS 'TRANSACTIONDETAIL'
	,'' AS 'VNO'
	,'' AS 'VTYP'
	,0  AS 'BOOKTYPE'
	,0
	,'PENDING' AS 'UPLOADSTATUS'
	,(SELECT FILEUPLOAD_SDATE FROM RECON_BANK_FILEUPLOAD_LOGS(NOLOCK) WHERE UPLOADID=@UPLOADID) AS 'FILEUPLOAD_SDATE'
	,GETDATE()
	,@UNAME	
	FROM RECON_BANK_FILEUPLOAD_LOGS U (NOLOCK)
	INNER JOIN MSAJAG..FILEDATA F (NOLOCK)
		ON U.UPLOADID = F.PROGID
	WHERE F.PROGID = @UPLOADID
	AND ISNULL(DBO.PIECE(FILE_DATA,'Æ',5) , '')<>''
	AND ISNULL(DBO.PIECE(FILE_DATA,'Æ',2) , '')<>'VALUE DATE'

	--SELECT * FROM #NONCMS_DATA RETURN
	END TRY
	BEGIN CATCH  
  
 SELECT MSG=ERROR_MESSAGE()  
 DELETE D FROM RECON_BANK_UPLOAD_PROCESS_INFO D(NOLOCK) WHERE UPLOADID=@UPLOADID  
 DELETE FROM MSAJAG..FILEDATA WHERE PROGID=@UPLOADID  
 DELETE FROM RECON_BANK_FILEUPLOAD_LOGS WHERE UPLOADID=@UPLOADID  
 RETURN  
 END CATCH
	END

GO
