-- Object: PROCEDURE dbo.CLS_BANKRECO_FETCH_BAKDEC262016
-- Server: 10.253.33.91 | DB: ACCOUNT
--------------------------------------------------






CREATE PROCEDURE [dbo].[CLS_BANKRECO_FETCH_BAKDEC262016]
(
	@FCLTCODE VARCHAR(10),
	@TCLTCODE VARCHAR(10)
	,@DATE_FROM VARCHAR(11)
	,@DATE_TO VARCHAR(11)
	,@BANKCODE VARCHAR(30)
	,@DRCR CHAR(1)
	,@REFNO VARCHAR(30)
	,@CHEQUE_NO VARCHAR(30)
	,@AMOUNT NUMERIC(18,2)
	,@STATUS CHAR(1) = ''
	,@FLAG CHAR(2)
	,@SortBy NVARCHAR(50)
	,@BB_DATE_FROM VARCHAR(11)
	,@BB_DATE_TO VARCHAR(11)
	,@FILETYPE NVARCHAR(20)
)
AS 
/*
EXEC CLS_BANKRECO_FETCH '','','01/03/2010','01/12/2015','BANK01','D','','0','',''
EXEC CLS_BANKRECO_FETCH '','','01/03/2007','01/03/2015','BANK01','','','0','','L'
EXEC CLS_BANKRECO_FETCH '','','01/03/2007','01/03/2015','BANK01','','5','0','','BS'
EXEC CLS_BANKRECO_FETCH '','','01/03/2007','01/03/2015','BANK01','','5','0','','BB'
exec CLS_BANKRECO_FETCH @FCLTCODE='0A143',@TCLTCODE='0A147',@DATE_FROM='01/01/2010',@DATE_TO ='01/01/2015',@BANKCODE='bank01',@DRCR='D',@REFNO='',@STATUS=' ',@FLAG=''
*/
BEGIN
--SET @AMOUNT = (CASE WHEN @AMOUNT = 0 THEN 999999999 ELSE @AMOUNT END)
	IF @FLAG ='' OR @FLAG ='L'  /****BOTH BANK STAAND BANK BOOK AS WELL AS FOR LEDGER ENTRY****/
	BEGIN
	
		SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED 
			SELECT /*TOP 15*/ 
				ROW_NUMBER() OVER (ORDER BY REFERENCENO,B.VALUEDATE,DESCRIPTION,AMOUNT,DRCR,CROSSREFERENCENO,BR_SNO,BOOKDATE) AS "RNO",	
				REFERENCENO
				,VALUEDATE = CONVERT(VARCHAR(11)
				,CONVERT(DATETIME,B.ValueDate),103)
				, LEFT (DESCRIPTION,20) AS 'DESCRIPTION'
				/*,CASE	WHEN FILETYPE = 'CMS' THEN '<FONT COLOR="RED">' +LEFT (DESCRIPTION,20) +'</FONT>'
				ELSE '<FONT COLOR="BLUE">'+LEFT (DESCRIPTION,20)+'</FONT>'
				END 	AS 'DESCRIPTION'	*/		
				, DESCRIPTION AS 'TDESCRIPTION'
				, AMOUNT = ROUND(AMOUNT,2)
				,AMOUNTWITH_SIGN = ROUND(CASE WHEN DRCR = 'C' THEN  AMOUNT ELSE -AMOUNT END,2)
				,DRCR
				,CROSSREFERENCENO
				,BR_SNO
				,BOOKDATE = CONVERT(VARCHAR(11),CONVERT(DATETIME,BOOKDATE),103)
				,MATCH_FLAG =''
				,COLOR='' 
				FROM BANKRECO B WITH (NOLOCK) 
				,RECON_BANK_FILEUPLOAD_LOGS S
			WHERE 
				--MICRNO = '123456' AND 
				--DUMMY1 = '0' AND	
				B.DUMMY2=S.UPLOADID
				AND CLTCODE = @BANKCODE 	
				AND BOOKDATE BETWEEN CONVERT(VARCHAR(11),CONVERT(DATETIME,@DATE_FROM,103),109)+ ' 00:00:00'
				AND CONVERT(VARCHAR(11),CONVERT(DATETIME,@DATE_TO,103),109)+ ' 23:59:59'
				AND STATUS = 'UNMATCHED' 
				AND LTRIM(RTRIM(DRCR))= (CASE WHEN @DRCR = '' THEN LTRIM(RTRIM(DRCR))ELSE @DRCR END)
				AND AMOUNT =  CASE WHEN @AMOUNT = 0 THEN AMOUNT ELSE @AMOUNT END 
				AND FILETYPE=@FILETYPE
			ORDER BY RNO,AMOUNT,VALUEDATE 
			--CASE WHEN @SortBy ='AMOUNT' THEN AMOUNT END, 
			 --CASE WHEN @SortBy ='Cheque No.' THEN REFERENCENO END, 
			 --CASE WHEN @SortBy ='Date' THEN VALUEDATE END, 
			 --CASE WHEN @SortBy ='Client Code' THEN CLTCODE END   
			
		IF @FLAG =''	
			BEGIN
			SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED 
				SELECT /*TOP 15*/ 	
					L.ACNAME
					,L1.DRCR
					,L.CLTCODE
					, L1.DDNO --.DBO.REMOVE_ZERO(DDNO, '0')
					,DDDT = CONVERT(VARCHAR(10),DDDT,103)
					,RELAMT
					,RELAMTWITH_SIGN  = ROUND(CASE WHEN L1.DRCR = 'C' THEN RELAMT ELSE -RELAMT END,2)
					,VDT = CONVERT(VARCHAR(10),VDT,103)
					,L1.VNO
					,L1.VTYP
					,L1.BOOKTYPE
					,L1.LNO
					,RELDT
					,SHORTDESC
					,L1_SNO
					,ACCNO=''
					,MATCH_FLAG =''
					,COLOR='' 
					,VALUEDT = ''
					,A.BRANCHCODE AS BRANCHCODE--'Test'/*A.Pobranch*/ AS BRANCHCODE
				FROM 
					LEDGER L WITH (NOLOCK),LEDGER1 L1 WITH (NOLOCK)
					--,MULTIBANKID M WITH (NOLOCK)
					, 	VMAST V 
					,ACMAST A
				WHERE 
					L1.DDNO = (CASE WHEN @CHEQUE_NO  = '' THEN L1.DDNO ELSE @CHEQUE_NO  END)
					AND L1.VTYP IN ( '2','3' ,'5', '19','17', '20' ) 
					AND L.CLTCODE >= (CASE WHEN @FCLTCODE = '' THEN L.CLTCODE ELSE @FCLTCODE END)
					AND L.CLTCODE <= (CASE WHEN @TCLTCODE = '' THEN L.CLTCODE ELSE @TCLTCODE END)
					--AND L.CLTCODE=M.CLTCODE
					--AND DEFAULTBANK = 1 
					AND L.VNO=L1.VNO AND L.VTYP=L1.VTYP AND L.LNO=L1.LNO
					AND L.BOOKTYPE=L1.BOOKTYPE 	
					AND LTRIM(RTRIM(L1.DRCR))= (CASE WHEN @DRCR = '' THEN LTRIM(RTRIM(L1.DRCR))ELSE @DRCR END)
					AND EXISTS (SELECT VNO FROM LEDGER L2 WITH (NOLOCK) WHERE CLTCODE = @BANKCODE 
								AND L.VTYP=L2.VTYP AND L.BOOKTYPE = L2.BOOKTYPE AND L.VNO = L2.VNO 	
								AND L2.VDT >= ( CASE WHEN @BB_DATE_FROM='' THEN CONVERT(VARCHAR(11),CONVERT(DATETIME,@DATE_FROM,103),109)+ ' 00:00:00' ELSE CONVERT(VARCHAR(11),CONVERT(DATETIME,@BB_DATE_FROM,103),109)+ ' 00:00:00' END )
								AND L2.VDT <= (CASE WHEN @BB_DATE_TO='' THEN CONVERT(VARCHAR(11),CONVERT(DATETIME,@DATE_TO,103),109) + ' 23:59:59' ELSE CONVERT(VARCHAR(11),CONVERT(DATETIME,@BB_DATE_TO,103),109) + ' 23:59:59' END )) 	
					AND L.CLTCODE <> @BANKCODE AND RELDT LIKE 'JAN  1 1900%' 
					AND V.VTYPE =L.VTYP AND UPPER(CLEAR_MODE) <> 'C' 
					AND RELAMT <=  CASE WHEN @AMOUNT = 0 THEN RELAMT ELSE @AMOUNT END 
					AND L.CLTCODE=A.CLTCODE
				ORDER BY RELAMT,VDT,L1.VTYP,L1.VNO  
			END
			
	END
	ELSE IF @FLAG ='BS' /****BANK STATEMENT****/
	BEGIN
		 SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED
            SELECT
				ROW_NUMBER() OVER (ORDER BY REFERENCENO,b.VALUEDATE,DESCRIPTION,AMOUNT,B.DRCR,CROSSREFERENCENO,BR_SNO) AS "RNO",
				REFERENCENO,
				VALUEDATE = CONVERT(VARCHAR(11),
				CONVERT(DATETIME,B.VALUEDATE),103),
				LEFT (DESCRIPTION,15)DESCRIPTION,
				DESCRIPTION AS 'TDESCRIPTION',
				AMOUNT = ROUND(AMOUNT,2),
				AMOUNTWITH_SIGN = ROUND(CASE WHEN DRCR = 'C' THEN  AMOUNT ELSE -AMOUNT END,2),
				B.DRCR,
				CROSSREFERENCENO,
				BR_SNO ,DUMMY1,MATCH_FLAG = ''
            FROM
				BANKRECO B WITH (NOLOCK) ,RECON_BANK_FILEUPLOAD_LOGS s
            WHERE 
			B.DUMMY2=S.UPLOADID
			AND FILETYPE=@FILETYPE
				AND CROSSREFERENCENO = (CASE WHEN @REFNO = '' THEN CROSSREFERENCENO ELSE @REFNO END)
				--AND DUMMY1 = '0' 
				AND CLTCODE = @BANKCODE AND [STATUS] = (CASE WHEN @STATUS = 'M' THEN 'MATCHED' ELSE [STATUS] END)
				AND LTRIM(RTRIM(B.DRCR))= (CASE WHEN @DRCR = '' THEN LTRIM(RTRIM(B.DRCR))ELSE @DRCR END)
				AND AMOUNT =  CASE WHEN @AMOUNT = 0 THEN AMOUNT ELSE @AMOUNT END 
				AND B.VALUEDATE  BETWEEN CONVERT(VARCHAR(11),CONVERT(DATETIME,@DATE_FROM,103),109) AND CONVERT(VARCHAR(11),CONVERT(DATETIME,@DATE_TO,103),109)
            ORDER BY RNO,VALUEDATE, 	AMOUNT, 	B.DRCR
            --CASE WHEN @SortBy ='AMOUNT' THEN AMOUNT END, 
			 --CASE WHEN @SortBy ='Cheque No.' THEN REFERENCENO END, 
			 --CASE WHEN @SortBy ='Date' THEN VALUEDATE END, 
			 --CASE WHEN @SortBy ='Client Code' THEN CLTCODE END 
	END
	ELSE IF @FLAG ='BB' AND @REFNO = ''/****BANK BOOK****/
	BEGIN
		SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED 
		
        SELECT
			L1.DRCR,
			L.CLTCODE,L.VNO,
			L1.DDNO,--DBO.REMOVE_ZERO(DDNO, '0')
			DDDT = CONVERT(VARCHAR(10),DDDT,103),
			RELAMT = ROUND(RELAMT,2),
			VDT = CONVERT(VARCHAR(10),VDT,103),
			RELDT = CONVERT(VARCHAR(10),RELDT,103),
			L1.REFNO,MATCH_FLAG ='' 
        FROM 
			LEDGER L WITH (NOLOCK), 	LEDGER1 L1 WITH (NOLOCK), 	VMAST V 
        WHERE 
			L1.VTYP IN ( '2','3' ,'5', '19','17', '20' )
			AND L1.DDNO = (CASE WHEN @CHEQUE_NO  = '' THEN L1.DDNO ELSE @CHEQUE_NO  END)
			AND L1.REFNO = (CASE WHEN @REFNO = '' THEN L1.REFNO ELSE @REFNO END)
			AND L.CLTCODE >= (CASE WHEN @FCLTCODE = '' THEN L.CLTCODE ELSE @FCLTCODE END)
			AND L.CLTCODE <= (CASE WHEN @TCLTCODE = '' THEN L.CLTCODE ELSE @TCLTCODE END)
			AND L.VNO=L1.VNO 	AND L.VTYP=L1.VTYP
			AND L.LNO=L1.LNO 	AND L.BOOKTYPE=L1.BOOKTYPE
			AND EXISTS 	( SELECT VNO FROM LEDGER L2 WITH (NOLOCK) WHERE CLTCODE = @BANKCODE AND L.VTYP=L2.VTYP 
			AND L.BOOKTYPE = L2.BOOKTYPE AND L.VNO = L2.VNO AND L2.VDT >=CONVERT(VARCHAR(11),CONVERT(DATETIME,@DATE_FROM,103),109) + ' 00:00:00'
			AND L2.VDT <= CONVERT(VARCHAR(11),CONVERT(DATETIME,@DATE_TO,103),109)+ ' 23:59:59' ) AND L.CLTCODE <> @BANKCODE AND RELDT NOT LIKE 'JAN  1 1900%'
			AND LTRIM(RTRIM(L1.DRCR))= (CASE WHEN @DRCR = '' THEN LTRIM(RTRIM(L1.DRCR))ELSE @DRCR END)
			AND V.VTYPE =L.VTYP 	AND UPPER(CLEAR_MODE) <> 'C' 
			AND L1.REFNO NOT IN ('0','')
			AND RELAMT <=  CASE WHEN @AMOUNT = 0 THEN RELAMT ELSE @AMOUNT END
	END
	
	ELSE IF @FLAG ='BB' AND @REFNO <> ''/****BANK BOOK FOR CHECKEDEDIT****/
	BEGIN

		SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED 
		
        SELECT
			L1.DRCR,
			L.CLTCODE,L.VNO,
			L1.DDNO,--DBO.REMOVE_ZERO(DDNO, '0')
			DDDT = CONVERT(VARCHAR(10),DDDT,103),
			RELAMT = ROUND(RELAMT,2),
			VDT = CONVERT(VARCHAR(10),VDT,103),
			RELDT = CONVERT(VARCHAR(10),RELDT,103),
			L1.REFNO,MATCH_FLAG ='' 
			,A.BRANCHCODE AS BRANCHCODE--'Test_BB'/*A.Pobranch*/ AS BRANCHCODE
        FROM 
			LEDGER L WITH (NOLOCK), 	LEDGER1 L1 WITH (NOLOCK), 	VMAST V ,ACMAST A
        WHERE 
			L1.VTYP IN ( '2','3' ,'5', '19','17', '20' )			
			AND L1.REFNO = @REFNO			
			AND L.VNO=L1.VNO 	AND L.VTYP=L1.VTYP
			AND L.LNO=L1.LNO 	AND L.BOOKTYPE=L1.BOOKTYPE
			AND EXISTS 	( SELECT VNO FROM LEDGER L2 WITH (NOLOCK) WHERE CLTCODE = @BANKCODE AND L.VTYP=L2.VTYP 
			AND L.BOOKTYPE = L2.BOOKTYPE 
			AND L.VNO = L2.VNO 
			--AND L2.VDT >=CONVERT(VARCHAR(11),CONVERT(DATETIME,@DATE_FROM,103),109) + ' 00:00:00'
			--AND L2.VDT <= CONVERT(VARCHAR(11),CONVERT(DATETIME,@DATE_TO,103),109)+ ' 23:59:59' 
			) 
			--AND L.CLTCODE <> @BANKCODE 
			AND RELDT NOT LIKE 'JAN  1 1900%'
			--AND LTRIM(RTRIM(L1.DRCR))= (CASE WHEN @DRCR = '' THEN LTRIM(RTRIM(L1.DRCR))ELSE @DRCR END)
			AND V.VTYPE =L.VTYP 	
			--AND UPPER(CLEAR_MODE) <> 'C' 
			AND L1.REFNO NOT IN ('0','')
			AND RELAMT <=  CASE WHEN @AMOUNT = 0 THEN RELAMT ELSE @AMOUNT END
			AND L.CLTCODE=A.CLTCODE
	END
	
END

GO
