-- Object: PROCEDURE dbo.CCE_REPORT_DRCR_SUMMARY
-- Server: 10.253.33.91 | DB: ACCOUNT
--------------------------------------------------


CREATE PROCEDURE [dbo].[CCE_REPORT_DRCR_SUMMARY] (@RUNDATE VARCHAR(11))

AS --- EXEC CCE_REPORT_DRCR_SUMMARY 'OCT 12 2021'

SELECT REPORT_DATE,SNO INTO #CCE FROM CLIENT_CASH_DETAILS WITH (NOLOCK) 
WHERE REPORT_DATE BETWEEN @RUNDATE AND @RUNDATE + ' 23:59'

SELECT REPORT_DATE,UCC=LTRIM(RTRIM(ISNULL(PARTY_CODE,''))),
VDT_BAL = SUM(VDT_BAL), EDT_BAL = SUM(EDT_BAL) INTO #REPORTING
FROM #CCE C , CLIENT_CASH_LED_BALANCES L WITH (NOLOCK)
WHERE C.SNO = L.SNO AND PARTY_CODE BETWEEN 'A' AND 'ZZZZZZZZZZZZZZZZZ9999'
GROUP BY REPORT_DATE,PARTY_CODE

SELECT REPORT_DATE=CONVERT(varchar(11),REPORT_DATE,105),REPORT='CASH/EQ-Creditors - EDT',
CONVERT(VARCHAR,(SUM(EDT_BAL)/10000000)) as [Balance In CR],SUM(EDT_BAL) as [Balance In Rs]
FROM #REPORTING WHERE EDT_BAL >0 AND UCC!='BBBB' GROUP BY REPORT_DATE      
UNION ALL          
SELECT REPORT_DATE=CONVERT(varchar(11),REPORT_DATE,105),REPORT='CASH/EQ-Debtors - EDT',
CONVERT(VARCHAR,(SUM(EDT_BAL)/10000000)) as [Balance In CR],SUM(EDT_BAL) as [Balance In Rs]
FROM #REPORTING WHERE EDT_BAL <0 AND UCC!='BBBB' GROUP BY REPORT_DATE
UNION ALL 
SELECT REPORT_DATE=CONVERT(varchar(11),REPORT_DATE,105),REPORT='CASH/EQ-Creditors - VDT',
CONVERT(VARCHAR,(SUM(VDT_BAL)/10000000)) as [Balance In CR],SUM(VDT_BAL) as [Balance In Rs]
FROM #REPORTING WHERE VDT_BAL >0 AND UCC!='BBBB' GROUP BY REPORT_DATE      
UNION ALL          
SELECT REPORT_DATE=CONVERT(varchar(11),REPORT_DATE,105),REPORT='CASH/EQ-Debtors - VDT',
CONVERT(VARCHAR,(SUM(VDT_BAL)/10000000)) as [Balance In CR],SUM(VDT_BAL) as [Balance In Rs]
FROM #REPORTING WHERE VDT_BAL <0 AND UCC!='BBBB' GROUP BY REPORT_DATE

DROP TABLE #CCE
DROP TABLE #REPORTING

GO
