-- Object: PROCEDURE dbo.V2_OFFLINE_REV_UPDATE
-- Server: 10.253.33.91 | DB: ACCOUNT
--------------------------------------------------


CREATE PROC [dbo].[V2_OFFLINE_REV_UPDATE]
(
	@NEWVNO VARCHAR(12),
	@EXCHANGE VARCHAR(3), 
	@SEGMENT VARCHAR(20)
)
AS
SET XACT_ABORT ON
UPDATE 
	O
SET 
	LEDGERVNO = CONVERT(VARCHAR(12),CONVERT(NUMERIC,@NEWVNO) + (NEWSRNO - 1)), 
	ROWSTATE = 1,
	APPROVALFLAG = 1,
	APPROVALDATE = GETDATE()
FROM 
	AngelBSECM.ACCOUNT_AB.DBO.V2_OFFLINE_LEDGER_ENTRIES O, BANK_VNO B
WHERE
	 O.VOUCHERNO = B.VOUCHERNO 
	AND O.ROWSTATE = 9 
	AND O.SNO = B.SNO
	AND O.EXCHANGE = B.EXCHANGE 
	AND O.SEGMENT = B.SEGMENT
	AND O.EXCHANGE = @EXCHANGE 
	AND O.SEGMENT =	@SEGMENT 

DELETE 
	BANK_VNO 
WHERE  
	EXCHANGE = @EXCHANGE 
	AND SEGMENT = @SEGMENT

SET XACT_ABORT OFF

GO
