-- Object: PROCEDURE dbo.GL_ACCOUNT_TPT
-- Server: 10.253.33.91 | DB: ACCOUNT
--------------------------------------------------

CREATE PROCEDURE GL_ACCOUNT_TPT (@FROMDATE VARCHAR(11))    
    
AS    
  
--GL_ACCOUNT_TPT 'FEB 11 2022'  
    
SELECT VDT,NARRATION,ISNULL(A.PAN_GIR_NO,'') AS PAN_GIR_NO,VNO,VTYP,VAMT,ISNULL(B.CL_CODE,'') AS CL_CODE,DRAMT,CRAMT INTO #GLFINDAMT FROM (    
SELECT VDT,NARRATION, PAN_GIR_NO = RIGHT(LEFT(NARRATION,27),10),VNO,VTYP,VAMT,    
DRAMT = SUM( CASE WHEN DRCR = 'D' THEN VAMT ELSE '0' END) ,CRAMT = SUM (CASE WHEN DRCR = 'C' THEN VAMT ELSE '0' END)     
FROM LEDGER WITH (NOLOCK) WHERE CLTCODE = '440001' AND VTYP = 2      
AND NARRATION NOT LIKE '%Pan_Reference%' GROUP BY  VDT,NARRATION,VNO,VTYP,VAMT    
UNION ALL    
SELECT VDT,NARRATION,PAN_GIR_NO = RIGHT(LEFT(NARRATION,52),10),VNO,VTYP,VAMT,    
DRAMT = SUM( CASE WHEN DRCR = 'D' THEN VAMT ELSE '0' END) ,CRAMT = SUM (CASE WHEN DRCR = 'C' THEN VAMT ELSE '0' END)     
FROM LEDGER WITH (NOLOCK) WHERE CLTCODE = '440001' AND VTYP = 2     
AND NARRATION LIKE '%Pan_Reference%' GROUP BY VDT,NARRATION,VNO,VTYP,VAMT    
UNION ALL    
SELECT VDT,NARRATION,PAN_GIR_NO = RIGHT(LEFT(NARRATION,17),10),VNO,VTYP,VAMT,    
DRAMT = SUM( CASE WHEN DRCR = 'D' THEN VAMT ELSE '0' END) ,CRAMT = SUM (CASE WHEN DRCR = 'C' THEN VAMT ELSE '0' END)     
FROM LEDGER WITH (NOLOCK) WHERE CLTCODE = '440001' AND VTYP = 3 GROUP BY VDT,NARRATION,VNO,VTYP,VAMT    
UNION ALL    
SELECT VDT,NARRATION,PAN_GIR_NO = ISNULL(DBO.PIECE(NARRATION,'_',4),''),VNO,VTYP,VAMT,    
DRAMT = SUM( CASE WHEN DRCR = 'D' THEN VAMT ELSE '0' END) ,CRAMT = SUM (CASE WHEN DRCR = 'C' THEN VAMT ELSE '0' END)     
FROM LEDGER WITH (NOLOCK) WHERE CLTCODE = '440001' AND VTYP = 8 AND NARRATION LIKE 'AMT REC_%' AND NARRATION  NOT LIKE 'AMT RECD_%'    
AND NARRATION NOT LIKE '%PAN%'    
GROUP BY VDT,NARRATION,VNO,VTYP,VAMT    
UNION ALL    
SELECT VDT,NARRATION,PAN_GIR_NO =RIGHT(NARRATION,10),VNO,VTYP,VAMT,    
DRAMT = SUM( CASE WHEN DRCR = 'D' THEN VAMT ELSE '0' END) ,CRAMT = SUM (CASE WHEN DRCR = 'C' THEN VAMT ELSE '0' END)     
FROM LEDGER WITH (NOLOCK) WHERE CLTCODE = '440001' AND VTYP = 8  AND NARRATION  LIKE '%PAN%'    
GROUP BY VDT,NARRATION,VNO,VTYP,VAMT    
UNION ALL    
SELECT VDT,NARRATION,PAN_GIR_NO  = 'REWARD',VNO,VTYP,VAMT,    
DRAMT = SUM( CASE WHEN DRCR = 'D' THEN VAMT ELSE '0' END) ,CRAMT = SUM (CASE WHEN DRCR = 'C' THEN VAMT ELSE '0' END)     
FROM LEDGER WITH (NOLOCK) WHERE CLTCODE = '440001' AND VTYP = 8 AND NARRATION LIKE '%REWARD%' AND NARRATION  NOT LIKE 'AMT RECD_%'     
 AND NARRATION NOT LIKE '%PAN%'     
GROUP BY VDT,NARRATION,VNO,VTYP,VAMT    
UNION ALL    
SELECT VDT,NARRATION,PAN_GIR_NO  = ISNULL(DBO.PIECE(NARRATION,'_',4),'') ,VNO,VTYP,VAMT,    
DRAMT = SUM( CASE WHEN DRCR = 'D' THEN VAMT ELSE '0' END) ,CRAMT = SUM (CASE WHEN DRCR = 'C' THEN VAMT ELSE '0' END)     
FROM LEDGER WITH (NOLOCK) WHERE CLTCODE = '440001' AND VTYP = 8 AND NARRATION NOT LIKE '%REWARD%' AND NARRATION LIKE 'AMT RECD_%'    
AND NARRATION NOT LIKE 'AMT RECD CHQ NO%' AND NARRATION NOT LIKE '%PAN%'     
GROUP BY VDT,NARRATION,VNO,VTYP,VAMT    
UNION ALL    
SELECT VDT,NARRATION,PAN_GIR_NO = LEFT(NARRATION,10),VNO,VTYP,VAMT,    
DRAMT = SUM( CASE WHEN DRCR = 'D' THEN VAMT ELSE '0' END) ,CRAMT = SUM (CASE WHEN DRCR = 'C' THEN VAMT ELSE '0' END)     
FROM LEDGER WITH (NOLOCK) WHERE CLTCODE = '440001' AND VTYP = 8 AND NARRATION NOT LIKE '%REWARD%' AND NARRATION  NOT LIKE 'AMT RECD_%'    
AND NARRATION NOT LIKE '%AMT%' AND NARRATION NOT LIKE '%PAN%'  GROUP BY VDT,NARRATION,VNO,VTYP,VAMT    
) AS A LEFT OUTER JOIN MSAJAG.DBO.CLIENT_DETAILS B WITH (NOLOCK)     
ON (A.PAN_GIR_NO = B.PAN_GIR_NO) AND B.PAN_GIR_NO <> ''    
  
SELECT DISTINCT A.PAN_GIR_NO,A.CL_CODE AS CLTCODE1,B.CL_CODE AS CLTCODE2 INTO #DUPPAN  
FROM #GLFINDAMT A , #GLFINDAMT B  
WHERE A.PAN_GIR_NO = B.PAN_GIR_NO AND A.CL_CODE <> B.CL_CODE  
  
  
UPDATE #GLFINDAMT SET CL_CODE = '' FROM  
(SELECT B.CL_CODE,MAX(INACTIVE_FROM) AS INACTIVE_FROM  
FROM #DUPPAN A ,MSAJAG.DBO.CLIENT_BROK_DETAILS B WITH (NOLOCK) WHERE CLTCODE1 = B.CL_CODE  
GROUP BY B.CL_CODE) A WHERE A.CL_CODE = #GLFINDAMT.CL_CODE AND INACTIVE_FROM NOT LIKE '%2049%'  
  
  
UPDATE #GLFINDAMT SET CL_CODE = '' FROM  
(SELECT B.CL_CODE,MAX(INACTIVE_FROM) AS INACTIVE_FROM  
FROM #DUPPAN A ,MSAJAG.DBO.CLIENT_BROK_DETAILS B WITH (NOLOCK) WHERE  CLTCODE2 = B.CL_CODE  
GROUP BY B.CL_CODE) A WHERE A.CL_CODE = #GLFINDAMT.CL_CODE AND INACTIVE_FROM NOT LIKE '%2049%'  
  
SELECT DISTINCT * INTO #GLFINDAMT_DUP FROM #GLFINDAMT  
  
DELETE FROM #GLFINDAMT_DUP WHERE CL_CODE = '' AND PAN_GIR_NO IN (SELECT PAN_GIR_NO FROM #GLFINDAMT_DUP WHERE CL_CODE <> '')  
  
TRUNCATE TABLE #GLFINDAMT  
  
INSERT INTO #GLFINDAMT SELECT * FROM #GLFINDAMT_DUP    
    
INSERT INTO #GLFINDAMT    
SELECT VDT,NARRATION,'' AS PAN_GIR_NO,VNO,VTYP,VAMT,'' AS CL_CODE,    
DRAMT = SUM( CASE WHEN DRCR = 'D' THEN VAMT ELSE '0' END) ,CRAMT = SUM (CASE WHEN DRCR = 'C' THEN VAMT ELSE '0' END)     
FROM LEDGER A WITH (NOLOCK)     
WHERE CLTCODE = '440001' AND VTYP = 8 AND VNO NOT IN (SELECT VNO FROM #GLFINDAMT WHERE VTYP = 8)    
GROUP BY VDT,NARRATION,VNO,VTYP,VAMT ORDER BY VNO ASC    
    
SELECT A.*,ISNULL(DDNO,'') AS DDNO INTO #GLFINDAMT_FINAL FROM #GLFINDAMT A LEFT OUTER JOIN LEDGER1 B  WITH (NOLOCK)  ON (A.VNO = B.VNO AND A.VTYP = B.VTYP)     
    
ALTER TABLE #GLFINDAMT_FINAL ADD STATUSF VARCHAR(50)    
    
UPDATE #GLFINDAMT_FINAL SET STATUSF = ''    
    
UPDATE #GLFINDAMT_FINAL SET STATUSF = 'REFUND'    
FROM    
(SELECT * FROM #GLFINDAMT_FINAL WHERE VTYP = 2)  A ,(SELECT * FROM #GLFINDAMT_FINAL WHERE VTYP = 3)  B    
WHERE A.PAN_GIR_NO = B.PAN_GIR_NO AND A.VAMT = B.VAMT AND A.PAN_GIR_NO = #GLFINDAMT_FINAL.PAN_GIR_NO    
AND B.VAMT = #GLFINDAMT_FINAL.VAMT AND #GLFINDAMT_FINAL.STATUSF = ''    
    
UPDATE #GLFINDAMT_FINAL SET STATUSF = 'RECONCILED'    
FROM    
(SELECT * FROM #GLFINDAMT_FINAL WHERE VTYP = 2)  A ,(SELECT * FROM #GLFINDAMT_FINAL WHERE VTYP = 8)  B    
WHERE A.PAN_GIR_NO = B.PAN_GIR_NO AND A.VAMT = B.VAMT AND A.PAN_GIR_NO = #GLFINDAMT_FINAL.PAN_GIR_NO    
AND B.VAMT = #GLFINDAMT_FINAL.VAMT AND #GLFINDAMT_FINAL.STATUSF = ''    
    
UPDATE #GLFINDAMT_FINAL SET STATUSF = 'TEST' WHERE VAMT <= 100 AND STATUSF = ''    
    
UPDATE #GLFINDAMT_FINAL SET STATUSF = 'AOC' WHERE VAMT <= 699 AND VAMT > 100  AND STATUSF = ''    
    
UPDATE #GLFINDAMT_FINAL SET STATUSF = 'MISMATCH' WHERE  STATUSF = ''    
    
    
SELECT PAN_GIR_NO INTO #PAN_GIR_NO_MISMATCH FROM #GLFINDAMT_FINAL A    
WHERE A.PAN_GIR_NO <> '' AND A.STATUSF = 'RECONCILED'     
GROUP BY  A.PAN_GIR_NO HAVING (SUM(A.DRAMT)- SUM(A.CRAMT)) <> 0     
    
UPDATE #GLFINDAMT_FINAL SET STATUSF = 'MISMATCH'     
FROM #PAN_GIR_NO_MISMATCH    
WHERE #PAN_GIR_NO_MISMATCH.PAN_GIR_NO = #GLFINDAMT_FINAL.PAN_GIR_NO AND STATUSF = 'RECONCILED'    
    
    
SELECT VoucherDt = CONVERT(CHAR(10), VDT, 103) ,SHORTDESC,VNO,#GLFINDAMT_FINAL.NARRATION,DDNO,DRAMT,CRAMT,PAN_GIR_NO AS PAN ,CL_CODE,  
STATUSF AS [STATUS/COMMENT]   
FROM #GLFINDAMT_FINAL  , VMAST WHERE VTYPE = VTYP ORDER BY VDT  ASC  
  
  
DROP TABLE #GLFINDAMT_DUP  
DROP TABLE #DUPPAN  
DROP TABLE #PAN_GIR_NO_MISMATCH    
DROP TABLE #GLFINDAMT    
DROP TABLE #GLFINDAMT_FINAL

GO
