-- Object: PROCEDURE dbo.RECO_TIM_REPORT
-- Server: 10.253.33.91 | DB: ACCOUNT
--------------------------------------------------


CREATE PROC [dbo].[RECO_TIM_REPORT](@FROMDATE VARCHAR(11),@TODATE VARCHAR(11))              
AS              
              
--DECLARE @VDT VARCHAR(11) = 'APR 27 2022'              
            
--EXEC RECO_TIM_REPORT 'DEC  9 2022'  ,'DEC  9 2022'        
      
SELECT DISTINCT L.CLTCODE,L.VNO,L.VTYP,L.BOOKTYPE,L.EDT,L.VDT,MAX(L.CDT) AS CDT,L.ENTEREDBY,L1.RELDT,L1.DDNO,MAX(L1.UPDDATE) AS  UPDDATE,MAX(L.UPDDATE) AS  EUPDDATE              
INTO #LEDGER_TRIG              
FROM LEDGER_TRIG L WITH (NOLOCK), LEDGER1_TRIG L1 WITH (NOLOCK),ACMAST A WITH (NOLOCK)              
WHERE L.VTYP IN (2,3)              
AND ACCAT = 4 AND A.CLTCODE =L.CLTCODE AND L.VNO = L1.VNO AND L.VTYP = L1.VTYP AND L.BOOKTYPE = L1.BOOKTYPE              
AND RELDT  LIKE '%1900%' AND EDT  LIKE '%2049%' AND L.DBACTION = L1.DBACTION AND L.DBACTION = 'MODIFIED'              
AND (VDT BETWEEN @FROMDATE AND  @TODATE + ' 23:59'  OR L1.UPDDATE  BETWEEN @FROMDATE AND  @TODATE + ' 23:59'  OR L.UPDDATE 
BETWEEN @FROMDATE AND  @TODATE + ' 23:59')       
GROUP BY L.CLTCODE,L.VNO,L.VTYP,L.BOOKTYPE,L.EDT,L.VDT,L.ENTEREDBY,L1.RELDT,L1.DDNO 

CREATE CLUSTERED INDEX CLILED ON #LEDGER_TRIG (VNO,VTYP,BOOKTYPE)

/*
SELECT * INTO #LEDGER1_TRIG 
FROM LEDGER1_TRIG WHERE DDDT BETWEEN @FROMDATE AND  @TODATE + ' 23:59'  --OR UPDDATE  BETWEEN @FROMDATE AND  @TODATE + ' 23:59'
AND RELDT  LIKE '%1900%'
AND CONVERT(VARCHAR(11),DDDT) <> CONVERT(VARCHAR(11),UPDDATE) 
AND VTYP IN (2,3) AND DBACTION = 'MODIFIED'   


CREATE INDEX CLILED1 ON #LEDGER1_TRIG (VNO,VTYP,BOOKTYPE.RELDT,DBACTION,UPDDATE)


INSERT INTO #LEDGER_TRIG
SELECT DISTINCT L.CLTCODE,L.VNO,L.VTYP,L.BOOKTYPE,L.EDT,L.VDT,MAX(L.CDT) AS CDT,L.ENTEREDBY,L1.RELDT,L1.DDNO,MAX(L1.UPDDATE) AS  UPDDATE,MAX(L1.UPDDATE) AS  EUPDDATE            
FROM LEDGER L WITH (NOLOCK), #LEDGER1_TRIG L1 WITH (NOLOCK),ACMAST A WITH (NOLOCK)            
WHERE L.VTYP IN (2,3)            
AND ACCAT = 4 AND A.CLTCODE =L.CLTCODE AND L.VNO = L1.VNO AND L.VTYP = L1.VTYP AND L.BOOKTYPE = L1.BOOKTYPE            
AND RELDT  LIKE '%1900%'  AND L1.DBACTION = 'MODIFIED' AND CONVERT(VARCHAR(11),L.VDT) <> CONVERT(VARCHAR(11),L1.UPDDATE)          
AND VDT BETWEEN @FROMDATE AND  @TODATE + ' 23:59'     
AND NOT EXISTS (SELECT * FROM #LEDGER_TRIG L2 WHERE L2.VNO = L.VNO AND L2.VTYP = L.VTYP AND L2.BOOKTYPE = L.BOOKTYPE)
GROUP BY L.CLTCODE,L.VNO,L.VTYP,L.BOOKTYPE,L.EDT,L.VDT,L.ENTEREDBY,L1.RELDT,L1.DDNO      
*/
              
SELECT EXCHANGE = 'NSECM',              
L.CLTCODE,L.VNO,L.VTYP,L.EDT AS NEWEDT,LT.EDT AS OLDEDT,L.VDT,L.CDT,L.ENTEREDBY AS MODIFIEDBY,L1.RELDT AS NEWRELDT,LT.RELDT AS OLDRELDT,        
L1.DDNO,L.NARRATION,L.VAMT,LT.UPDDATE,LT.EUPDDATE,LT.ENTEREDBY,              
LT.BOOKTYPE,CONVERT(TIME,LT.UPDDATE) AS UPDTIME    ,CONVERT(TIME,LT.EUPDDATE) AS EUPDTIME            
INTO #LEDGER_TEMP              
FROM LEDGER L WITH (NOLOCK), LEDGER1 L1 WITH (NOLOCK),ACMAST A WITH (NOLOCK) ,#LEDGER_TRIG LT              
WHERE ACCAT = 4 AND A.CLTCODE =L.CLTCODE AND L.VTYP = L1.VTYP  AND L.VNO = L1.VNO  AND L.BOOKTYPE = L1.BOOKTYPE              
AND LT.VNO = L1.VNO AND LT.VTYP = L1.VTYP AND LT.BOOKTYPE = L1.BOOKTYPE AND  CONVERT(DATE,LT.UPDDATE) >=  CONVERT(DATE,L1.RELDT+1)              
AND (CONVERT(TIME,LT.EUPDDATE) > '03:00:00' OR CONVERT(TIME,LT.UPDDATE) > '03:00:00' )             
AND L1.RELDT NOT LIKE '%1900%' AND L.EDT NOT LIKE '%2049%'              
              
              
SELECT EXCHANGE,L1.CLTCODE,L1.VNO,L1.VTYP,FORMAT(L1.NEWEDT,'dd/MM/yyyy') AS NEWEDT,FORMAT(L1.OLDEDT,'dd/MM/yyyy') AS OLDEDT,        
FORMAT(L1.VDT,'dd/MM/yyyy') AS VDT,FORMAT(L1.CDT,'dd/MM/yyyy') AS CDT,            
MODIFIEDBY,FORMAT(NEWRELDT,'dd/MM/yyyy') AS NEWRELDT,FORMAT(OLDRELDT,'dd/MM/yyyy') AS OLDRELDT,L1.DDNO,L1.NARRATION,L1.VAMT,            
FORMAT(L1.UPDDATE,'dd/MM/yyyy') AS RELUPDDATE,L1.ENTEREDBY,FORMAT(L1.EUPDDATE,'dd/MM/yyyy') AS EDTUPDDATE,L.CLTCODE               
AS BANKCODE ,FORMAT(L1.UPDDATE,'HH:mm:ss') AS UPDTIME ,FORMAT(CONVERT(DATETIME,EUPDTIME),'HH:mm:ss') AS EUPDTIME ,L1.NEWEDT AS NEWEDT1,L1.VDT AS VDT1               
INTO #LEDGER_FINAL              
FROM LEDGER L WITH (NOLOCK), #LEDGER_TEMP L1,ACMAST A   WITH (NOLOCK)            
WHERE ACCAT = 2 AND A.CLTCODE = L.CLTCODE AND L.VNO = L1.VNO AND L.VTYP = L1.VTYP AND L.BOOKTYPE = L1.BOOKTYPE              
AND L1.CLTCODE <> L.CLTCODE AND (CONVERT(TIME,L1.EUPDDATE) > '03:00:00' OR CONVERT(TIME,L1.UPDDATE) > '03:00:00' )         
              
SELECT DISTINCT EXCHANGE,CLTCODE,VNO,VTYP,NEWEDT,OLDEDT,VDT,CDT,MODIFIEDBY,NEWRELDT,OLDRELDT,DDNO,NARRATION,VAMT,RELUPDDATE,ENTEREDBY,EDTUPDDATE,BANKCODE,UPDTIME,EUPDTIME  
FROM #LEDGER_FINAL     
WHERE  (CONVERT(TIME,UPDTIME) > '03:00:00' OR (CONVERT(TIME,EUPDTIME) > '03:00:00' AND CONVERT(DATE,NEWEDT1) > CONVERT(DATE,VDT1)) )       
ORDER BY VDT,CLTCODE ASC            
              
DROP TABLE #LEDGER_TRIG              
DROP TABLE #LEDGER_TEMP              
DROP TABLE #LEDGER_FINAL
--DROP TABLE #LEDGER1_TRIG

GO
