-- Object: PROCEDURE dbo.CMSRECO_BULK_YES
-- Server: 10.253.33.91 | DB: ACCOUNT
--------------------------------------------------









CREATE PROC [dbo].[CMSRECO_BULK_YES]
 @BANKCODE VARCHAR(10),      
 @FNAME VARCHAR(500),      
 @UNAME VARCHAR(100)      
      
AS      
      
SET NOCOUNT ON       
/*--------------------------VALIDATION FOR SINVOUCHER TYPE BASED ON DRCR ------------------------*/      
      
DECLARE        
 @@ERROR_COUNT INT,       
 @@CMSRECOCOUNT AS INT,       
 @@MICRNO AS VARCHAR(10),      
 @@FROMDATE AS DATETIME,      
 @@SQL VARCHAR(8000)      
      
      
/*        SELECT @@ERROR_COUNT = COUNT(1) FROM (SELECT U_FILENAME FROM V2_UPLOADED_FILES        
WHERE U_FILENAME = '" & UCASE(FNAME) &' AND U_MODULE = 'CMS AUTO-RECONCILIATION') A       
      
IF @@ERROR_COUNT > 0       
BEGIN       
SELECT 'THE FILE YOU ARE UPLOADING IS ALREADY UPLOADED. PLEASE UPLOAD ANOTHER FILE.' + '" & UCASE(FNAME) &'       
RETURN       
END */      
      
/*--        DROP TABLE #CMS_TABLE        
--        DROP TABLE #CMS_TABLE_TMP  */      
CREATE TABLE #CMS_TABLE_TMP       
(       
 STRLINETEXT VARCHAR(8000)       
)       
      
CREATE TABLE [DBO].[#CMS_TABLE_TEST] (       
	CORPORATION_CODE VARCHAR(15),
	CLIENT_CODE VARCHAR(20),
	PICKUP_LOC_CODE VARCHAR(50),
	PICKUP_POINT_CODE VARCHAR(50),
	ACCT_ENTRY_AMNT VARCHAR(25),
	DEPOSIT_SLIP_AMT VARCHAR(25),
	DRAWEE_BANK_DESCRIPTION VARCHAR(50),
	ACT_CLIENT_VALUE_DATE VARCHAR(30),
	CLEARING_LOC_DESC VARCHAR(50),
	DEBIT_CREDIT_FLAG VARCHAR(50),
	DEPOSIT_DATE VARCHAR(20),
	DEPOSIT_ENTRY_DATE VARCHAR(20),
	DEPOSIT_NMBR VARCHAR(25),
	DRAWER_DESCRIPTION VARCHAR(100),
	INPUT_DEPOSIT_NMBR VARCHAR(25),
	INSTRUMENT_DATE VARCHAR(25),
	INSTRUMENT_NMBR VARCHAR(30),
	PRODUCT_CODE VARCHAR(25),
	PRODUCT_DESCRIPTION VARCHAR(50),
	REMARKS VARCHAR(50),
	RETURN_REASON VARCHAR(100),
	VALUE_DATE VARCHAR(25),
	ENRICHMENT VARCHAR(500),
	ENRICHMENT1 VARCHAR(500),
	ENRICHMENT2 VARCHAR(500),
	ENRICHMENT3 VARCHAR(500),
	ENRICHMENT4 VARCHAR(500),
	ENRICHMENT5 VARCHAR(500),
	ENRICHMENT6 VARCHAR(500),
	ENRICHMENT7 VARCHAR(500),
	ENRICHMENT8 VARCHAR(500),      
	ENRICHMENT9 VARCHAR(500)
) ON [PRIMARY]       
      
CREATE TABLE [DBO].[#CMS_TABLE] (       
	[SNO] [INT] NOT NULL IDENTITY(1,1),       
	CORPORATION_CODE VARCHAR(15),
	CLIENT_CODE VARCHAR(20),
	PICKUP_LOC_CODE VARCHAR(50),
	PICKUP_POINT_CODE VARCHAR(50),
	ACCT_ENTRY_AMNT VARCHAR(25),
	DEPOSIT_SLIP_AMT VARCHAR(25),
	DRAWEE_BANK_DESCRIPTION VARCHAR(50),
	ACT_CLIENT_VALUE_DATE VARCHAR(20),
	CLEARING_LOC_DESC VARCHAR(50),
	DEBIT_CREDIT_FLAG VARCHAR(5),
	DEPOSIT_DATE VARCHAR(20),
	DEPOSIT_ENTRY_DATE VARCHAR(20),
	DEPOSIT_NMBR VARCHAR(25),
	DRAWER_DESCRIPTION VARCHAR(100),
	INPUT_DEPOSIT_NMBR VARCHAR(25),
	INSTRUMENT_DATE VARCHAR(25),
	INSTRUMENT_NMBR VARCHAR(25),
	PRODUCT_CODE VARCHAR(25),
	PRODUCT_DESCRIPTION VARCHAR(50),
	REMARKS VARCHAR(50),
	RETURN_REASON VARCHAR(50),
	VALUE_DATE VARCHAR(25),
	ENRICHMENT VARCHAR(500),
	ENRICHMENT1 VARCHAR(25),
	ENRICHMENT2 VARCHAR(25),
	ENRICHMENT3 VARCHAR(25),
	ENRICHMENT4 VARCHAR(25),
	ENRICHMENT5 VARCHAR(25),
	ENRICHMENT6 VARCHAR(25),
	ENRICHMENT7 VARCHAR(25),
	ENRICHMENT8 VARCHAR(25),      
	ENRICHMENT9 VARCHAR(25),  
	[STRBANKCODE] [VARCHAR] (10) NOT NULL,       
	[STRSTATUS] [VARCHAR] (8) NOT NULL,
	[E3] [VARCHAR] (20) NULL,
	[CROSSREFERENCENO] INT NULL, 
) ON [PRIMARY]       
      
      
      
SELECT @@SQL = "BULK INSERT #CMS_TABLE_TMP FROM '" + @FNAME + "' WITH (FIELDTERMINATOR = ',', ROWTERMINATOR = '\n', FIRSTROW = 2, LASTROW = 2, KEEPNULLS)"      
EXEC (@@SQL)   
     
SELECT @@SQL = "BULK INSERT #CMS_TABLE_TEST FROM '" + @FNAME + "' WITH (FIELDTERMINATOR = ',', ROWTERMINATOR = '\n', FIRSTROW = 2, KEEPNULLS)"                  
EXEC (@@SQL)        

CREATE TABLE #CMS_PROCESS
(
	[SNO] [INT] NOT NULL IDENTITY(1,1),       
	BANKCODE VARCHAR(10), 
	CLTCODE VARCHAR(10),
	ACCNO VARCHAR(30), 
	DEPOSIT_DATE DATETIME, 
	ENTRY_AMNT MONEY,
	INST_NO VARCHAR(30),
	DRCR CHAR(1),
	VALUE_DATE DATETIME,
	[CROSSREFERENCENO] INT NULL,
	STRSTATUS VARCHAR(10)
)

DECLARE
	@CMS_CODE VARCHAR(20)
	
SELECT @CMS_CODE = CMS_CODE FROM COMPANY_MASTER_SETTING M, Owner O
WHERE M.EXCHANGE = O.Exchange AND M.SEGMENT = O.segment	



INSERT INTO #CMS_PROCESS
SELECT 
	@BANKCODE, 
	LEFT(LTRIM(RTRIM(.DBO.PIECE((REPLACE(REPLACE(ENRICHMENT, 'CLIENT ID :- ', ''), 'CLIENT ACCOUNT NO :- ', '')), '.' , 1))), 10),
	LEFT(LTRIM(RTRIM(.DBO.PIECE((REPLACE(REPLACE(ENRICHMENT, 'CLIENT ID :- ', ''), 'CLIENT ACCOUNT NO :- ', '')), '.' , 2))), 30),
	CONVERT(DATETIME, DEPOSIT_DATE, 101),
	ACCT_ENTRY_AMNT,
	.DBO.REMOVE_ZERO1(INSTRUMENT_NMBR,'0'),
	DEBIT_CREDIT_FLAG,
	CONVERT(DATETIME, VALUE_DATE, 101),
	0,
	'MISMATCH'
FROM #CMS_TABLE_TEST
WHERE CLIENT_CODE = @CMS_CODE



/*      
INSERT INTO V2_UPLOADED_FILES       
SELECT       
 @FNAME,       
 @FNAME,       
 COUNT(1),       
 'B',       
 GETDATE(),       
 @UNAME,       
 'CMS AUTO-RECONCILIATION'       
*/      
      

 
 
      
SELECT @@FROMDATE = DATEADD ( DD , -90, getdate())       

CREATE TABLE #FIRST_HASH_LEDGER
(
	VNO VARCHAR(12),
	VTYP INT,
	BOOKTYPE VARCHAR(3),
	LNO INT,
	CLTCODE VARCHAR(10)
)


INSERT INTO       
 #FIRST_HASH_LEDGER             
SELECT       
 VNO,       
 VTYP,      
 BOOKTYPE,       
 LNO,
 CLTCODE
FROM       
 LEDGER L WITH (NOLOCK)
WHERE       
 VTYP IN (2, 3, 5, 19, 20, 17)       
 AND EXISTS(SELECT VNO FROM LEDGER L1 WHERE L.VNO = L1.VNO AND L.VTYP = L1.VTYP AND L.BOOKTYPE = L1.BOOKTYPE AND CLTCODE = @BANKCODE AND VDT >= @@FROMDATE)
 
      
      
SELECT       
 L1.VNO,       
 L1.VTYP,       
 L1.BOOKTYPE,       
 L1.RELAMT,       
 .dbo.REMOVE_ZERO1(L1.ddno, '0')as ddno,
 L1.DRCR,       
 STATUS = 'MISMATCH',       
 SNO = 0,
 REFNO = L1.REFNO,
 CLTCODE,
 RELDT
INTO       
 #FIRST_HASH_LEDGER1       
FROM       
 LEDGER1 L1 WITH (NOLOCK),       
 #FIRST_HASH_LEDGER F WITH (NOLOCK)       
WHERE       
 F.VNO = L1.VNO       
 AND F.VTYP = L1.VTYP       
 AND F.BOOKTYPE = L1.BOOKTYPE       
 AND F.LNO = L1.LNO       
 AND L1.RELDT = ''       
 AND L1.DDNO <> ''       
 AND L1.DDNO <> '0'       
      
DROP TABLE #FIRST_HASH_LEDGER 

DECLARE
	@@CROSS_NO INT
	
SELECT @@CROSS_NO = MAX(CROSSREFERENCENO) FROM BANKRECO

UPDATE #CMS_PROCESS SET CROSSREFERENCENO = @@CROSS_NO + SNO
      
UPDATE       
 L1       
SET       
 STATUS = 'CORRECT',       
 SNO = C.SNO,
 L1.REFNO = CROSSREFERENCENO,
 RELDT = VALUE_DATE      
FROM    
 #FIRST_HASH_LEDGER1 L1,       
 #CMS_PROCESS C WITH (NOLOCK),
 MULTIBANKID M       
WHERE       
 L1.RELAMT = C.ENTRY_AMNT       
 AND L1.DDNO = C.INST_NO
 AND L1.DRCR = C.DRCR
 AND L1.CLTCODE = C.CLTCODE
 AND L1.CLTCODE = M.CLTCODE
 AND M.ACCNO = C.ACCNO
 AND L1.VNO IN      
 (SELECT MIN(VNO) FROM #FIRST_HASH_LEDGER1 L2      
   WHERE L2.RELAMT = C.ENTRY_AMNT       
   AND L2.DDNO = C.INST_NO       
   AND L2.DRCR = C.DRCR)     
 -------------- Added For Matching   
 UPDATE       
 L1       
SET       
 STATUS = 'CORRECT',       
 SNO = C.SNO,
 L1.REFNO = CROSSREFERENCENO,
 RELDT = VALUE_DATE      
FROM    
 #FIRST_HASH_LEDGER1 L1,       
 #CMS_PROCESS C WITH (NOLOCK),
 MULTIBANKID M       
WHERE       
 L1.RELAMT = C.ENTRY_AMNT       
 AND L1.DDNO = C.INST_NO
 AND L1.DRCR = C.DRCR
 AND L1.CLTCODE = C.CLTCODE
 AND L1.CLTCODE = M.CLTCODE
 AND RIGHT(M.ACCNO,5) = RIGHT(C.ACCNO,5)
 AND L1.STATUS <> 'CORRECT'
 AND L1.VNO IN      
 (SELECT MIN(VNO) FROM #FIRST_HASH_LEDGER1 L2      
   WHERE L2.RELAMT = C.ENTRY_AMNT       
   AND L2.DDNO = C.INST_NO       
   AND L2.DRCR = C.DRCR)      
   
   
------------ End Here   
     
      
UPDATE       
 C      
SET       
 STRSTATUS = 'CORRECT'       
FROM       
 #CMS_PROCESS C,       
 #FIRST_HASH_LEDGER1 L1 WITH (NOLOCK)       
WHERE       
 C.SNO = L1.SNO
 
 
 
DELETE       
FROM       
 #FIRST_HASH_LEDGER1       
WHERE       
 STATUS <> 'CORRECT'       
      
SELECT       
 @@ERROR_COUNT = COUNT(1)       
FROM       
 #CMS_PROCESS      
WHERE       
 STRSTATUS <> 'CORRECT'
 AND DRCR = 'C'       
      
SELECT       
 @@MICRNO = MICRNO       
FROM       
 ACMAST       
WHERE       
 CLTCODE = @BANKCODE 
 
 
BEGIN TRAN             
      
/*DELETE FROM CMSRECO WHERE BANK_CODE = @BANKCODEAND FILEHEADER_DATE = @@FILEHEADERDATE       
DELETE FROM CMSRECODETAILS WHERE BANK_CODE = @BANKCODEAND FILEHEADER_DATE = @@FILEHEADERDATE  */      
      
      
/*-----------------------INSERTING INTO CMSRECO, CMSRECODETAILS AND UPDATING LEDGER1 WHEN ALL ARE MATCHED---------*/       
/*
 INSERT        
 INTO CMSRECO        
 (       
  FILEHEADER_DATE,        
  BANK_CODE,        
  MICR_NO,        
  ENTRY_AMOUNT,        
  DEPOSIT_AMOUNT,        
  INST_AMOUNT,        
  STATUS_ID,        
  STATUS_NAME,        
  UPLOAD_BY,        
  UPLOAD_DATE,        
  AMOUNTMISMATCH,        
  MANUALUPDATE,        
  LEDGERAMOUNT       
 )        
 SELECT        
  @@FILEHEADERDATE,        
  BANK_CODE = @BANKCODE,        
  @@MICRNO,        
  ENTRY_AMOUNT =  CASE  WHEN STRDC = 'D'  THEN -SUM(STRENTRYAMOUNT)  ELSE SUM(STRENTRYAMOUNT)  END,        
  DEPOSIT_AMOUNT =  CASE  WHEN STRDC = 'D'  THEN -SUM(STRDEPOSITAMOUNT)  ELSE SUM(STRDEPOSITAMOUNT)  END,        
  INST_AMOUNT =  CASE  WHEN STRDC = 'D'  THEN -SUM(STRINSTAMOUNT)  ELSE SUM(STRINSTAMOUNT)  END,        
  STATUS_ID = @UNAME,        
  STATUS_NAME = @UNAME,        
  UPLOAD_BY = @UNAME,        
  UPLOAD_DATE = GETDATE(),        
  AMOUNTMISMATCH = 'NO',        
  MANUALUPDATE = 'NO',        
  LEDGERAMOUNT =  CASE  WHEN STRDC = 'D'  THEN -SUM(STRENTRYAMOUNT)  ELSE SUM(STRENTRYAMOUNT)  END        
 FROM       
  #CMS_TABLE WITH(NOLOCK)  
  WHERE STRDC = 'C'    
 GROUP BY       
  STRDC        
       
*/       
       
 UPDATE        
  LEDGER1        
 SET       
  RELDT = L1.RELDT,    
  REFNO = L1.REFNO        
 FROM       
  #FIRST_HASH_LEDGER1 L1        
 WHERE       
  LEDGER1.VNO = L1.VNO        
  AND LEDGER1.VTYP = L1.VTYP        
  AND LEDGER1.BOOKTYPE = L1.BOOKTYPE        
  AND LEDGER1.RELAMT = L1.RELAMT        
  AND LEDGER1.DRCR = L1.DRCR        
  AND LEDGER1.RELDT = ''        
  AND STATUS = 'CORRECT'      
       
/*        
      
INSERT        
INTO CMSRECODETAILS        
(        
 FILEHEADER_DATE,        
 ROW_TYPE,        
 ENTRY_ID,        
 ENTRY_TYPE,        
 DEBIT_CREDIT,        
 ENTRY_AMOUNT,        
 VALUE_DATE,        
 POST_DATE,        
 PROD_CODE,        
 PICKUP_LOCATION,        
 PICKUP_DISC,        
 PICKUP_DATE,        
 DEPOSIT_SLIP,      
 DEPOSIT_DATE,        
 DEPOSIT_AMOUNT,        
 NO_OF_INST,        
 DEPOSIT_REMARK,        
 INST_NO,        
 DRAWEE_BANK,        
 CLEAR_LOC,        
 INST_AMOUNT,        
 INST_DATE,        
 DRAWER_NAME,        
 ENRICHMENT_NO,        
 ENRICHMENT_DATE,        
 ENRICHMENT_REMARKS,        
 FILLER,        
 BANK_CODE,        
 MICR_NO,        
 STATUS_ID,        
 STATUS_NAME,        
 UPLOAD_BY,        
 UPLOAD_DATE,        
 STATUS,        
LEDGERAMOUNT        
)        
SELECT        
 @@FILEHEADERDATE,        
 STRROWTYPE,        
 STRENTRYID,        
 STRENTRYTYPE,        
 STRDC,        
 STRENTRYAMOUNT,        
 STRVALUEDATE,        
 STRPOSTDATE,        
 STRPRDCODE,        
 STRPKLOCATION,        
 STRPKDESCRIPTION,        
 STRPKDATE,        
 STRDEPOSITSLIP,        
 STRDEPOSITDATE,        
 STRDEPOSITAMOUNT,        
 STRNOOFINST,        
 STRDEPOSITREMARK,        
 STRINSTNO,        
 STRDRAWEEBANK,        
 STRCLEARLOCATION,        
 STRINSTAMOUNT,        
 STRINSTDATE,        
 STRDRAWERNAME,        
 STRENRICHMENTNO,        
 STRENRICHMENTDATE,        
 STRENRICHMENTREMARK,        
 STRFILLER,        
 STRBANKCODE,        
 @@MICRNO,        
 STATUS_ID = @UNAME,        
 STATUS_NAME = @UNAME,        
 UPLOAD_BY = @UNAME,        
 UPLOAD_DATE = GETDATE(),        
 STRSTATUS,        
 LEDGERAMOUNT = 0       
FROM       
 #CMS_TABLE WITH(NOLOCK) 
 WHERE STRDC = 'C'   
 
 UPDATE BANKRECO SET STATUS = 'MATCHED' WHERE CLTCODE = @BANKCODE AND DESCRIPTION LIKE '%CMS%' AND DRCR = 'C' AND BOOKDATE = @@FILEHEADERDATE        
*/
/*
DECLARE
	@@CROSS_NO INT
	
SELECT @@CROSS_NO = MAX(@@CROSS_NO) FROM BANKRECO*/

--DELETE FROM BANKRECO WHERE CLTCODE = @BANKCODE AND BOOKDATE = @@FILEHEADERDATE AND DESCRIPTION LIKE '%CMS%'

INSERT INTO BANKRECO(Cltcode,BookDate,Description,Amount,DrCr,ValueDate,ReferenceNo,StatusId,StatusName,LoginName,CrossReferenceNo,Status,MicrNo,Dummy1,Dummy2,CMS_SrNo)
SELECT @BANKCODE, VALUE_DATE, CLTCODE + ' ' + ACCNO + 'CMS ', ENTRY_AMNT, DRCR, VALUE_DATE, INST_NO, 'broker', 'broker', @UNAME, CROSSREFERENCENO, CASE WHEN STRSTATUS = 'CORRECT' THEN 'MATCHED' ELSE 'UNMATCHED' END, '999999999', '0', '0', ''
FROM #CMS_PROCESS
--WHERE STRENTRYTYPE = 'T'

/*SELECT @@CROSS_NO = MAX(CROSSREFERENCENO) FROM BANKRECO


INSERT INTO BANKRECO(Cltcode,BookDate,Description,Amount,DrCr,ValueDate,ReferenceNo,StatusId,StatusName,LoginName,CrossReferenceNo,Status,MicrNo,Dummy1,Dummy2,CMS_SrNo)
SELECT @BANKCODE, @@FILEHEADERDATE, 'CMS CHARGES', SUM(STRENTRYAMOUNT), STRDC, STRVALUEDATE, '0', 'broker', 'broker', @UNAME, @@CROSS_NO + 1, 'UNMATCHED', '999999999', '0', '0', ''
FROM #CMS_PROCESS
--WHERE STRENTRYTYPE = 'C'
GROUP BY STRDC, STRVALUEDATE
*/

IF @@ERROR_COUNT = 0       
BEGIN       
    
 SELECT 'DATA UPLOADED SUCCESSFULLY' AS RESULT  
    
END       
ELSE       
BEGIN       
 SELECT 'FILE UPLOADED SUCCESSFULLY WITH FOLLOWING MISMATCHES'       
 UNION ALL       
 select 'INST_NO, INST_AMT, INST_DATE, VALUE_DATE, STATUS '
 UNION ALL       
 SELECT       
  INST_NO + ', ' + CONVERT(VARCHAR, ENTRY_AMNT) + ', ' + CONVERT(VARCHAR(10), VALUE_DATE, 103) + ', AMOUNTMISMATCH' AS RESULT       
 FROM       
  #CMS_PROCESS       
 WHERE       
  STRSTATUS <> 'CORRECT'      
END        
DROP TABLE #CMS_TABLE        
DROP TABLE #CMS_TABLE_TMP       
DROP TABLE #FIRST_HASH_LEDGER1       

COMMIT TRAN

GO
