-- Object: PROCEDURE dbo.EDT_CHANGE_PROC_RPT_ANG
-- Server: 10.253.33.91 | DB: ACCOUNT
--------------------------------------------------

CREATE PROC EDT_CHANGE_PROC_RPT_ANG (@VDT DATETIME)

AS

SELECT CLTCODE,VNO,VTYP,VAMT,CONVERT(VARCHAR(10),VDT,105) AS VDT,CONVERT(VARCHAR(10),MIN(EDT),105) AS BEFEDT,CONVERT(VARCHAR(10),MAX(EDT),105) AS AFTEDT
,CONVERT(VARCHAR(10),'') AS EDT,CONVERT(VARCHAR(30),'') AS UPDDATE,CONVERT(VARCHAR(30),'') AS UPDDATE1,CHECKEDBY INTO #CHECK
FROM LEDGER_TRIG WHERE VTYP =3 
AND CLTCODE BETWEEN 'A' AND 'ZZZZZZZZZZ'
AND VDT = @VDT AND EDT NOT LIKE '%2049%'
GROUP BY CLTCODE,VNO,VTYP,VAMT,CONVERT(VARCHAR(10),VDT,105),CONVERT(VARCHAR(10),UPDDATE,105),CHECKEDBY
HAVING CONVERT(VARCHAR(10),MIN(EDT),105) <> CONVERT(VARCHAR(10),MAX(EDT),105)
ORDER BY CLTCODE


UPDATE #CHECK SET UPDDATE = LEDGER_TRIG.UPDDATE FROM LEDGER_TRIG WHERE LEDGER_TRIG.VNO = #CHECK.VNO AND LEDGER_TRIG.VTYP = #CHECK.VTYP 
AND  LEDGER_TRIG.CLTCODE = #CHECK.CLTCODE AND CONVERT(VARCHAR(10),LEDGER_TRIG.EDT,105) = BEFEDT

UPDATE #CHECK SET UPDDATE1 = LEDGER_TRIG.UPDDATE FROM LEDGER_TRIG WHERE LEDGER_TRIG.VNO = #CHECK.VNO AND LEDGER_TRIG.VTYP = #CHECK.VTYP 
AND  LEDGER_TRIG.CLTCODE = #CHECK.CLTCODE AND CONVERT(VARCHAR(10),LEDGER_TRIG.EDT,105)  = AFTEDT

UPDATE #CHECK SET EDT = CONVERT(VARCHAR(10),LEDGER.EDT,105) FROM LEDGER WHERE LEDGER.VNO = #CHECK.VNO AND LEDGER.VTYP = #CHECK.VTYP 
AND  LEDGER.CLTCODE = #CHECK.CLTCODE 

SELECT * FROM #CHECK ORDER BY CLTCODE

DROP TABLE #CHECK

GO
