-- Object: PROCEDURE dbo.RPT_RECO_DATA_MISIII
-- Server: 10.253.33.91 | DB: ACCOUNT
--------------------------------------------------



CREATE PROCEDURE [dbo].[RPT_RECO_DATA_MISIII] (@TODATE DATETIME)

AS --- RPT_RECO_DATA_MISIII 'JUN  1 2021'

TRUNCATE TABLE RECOMISII

INSERT INTO RECOMISII
SELECT EXCHNAGE='NSECM',CLTCODE,VAMT,DRCR,VTYP,VNO,BOOKTYPE,VDT,EDT,CDT,
RELDATE = (SELECT MAX(reldt) FROM ACCOUNT.DBO.LEDGER1 B WITH (NOLOCK) WHERE A.VNO = B.vno AND A.VTYP = B.vtyp),
DDNO = (SELECT MAX(DDNO) FROM ACCOUNT.DBO.LEDGER1 B WITH (NOLOCK) WHERE A.VNO = B.vno AND A.VTYP = B.vtyp),NARRATION,ENTEREDBY,
ACTYPE=CONVERT(VARCHAR(150),''),RECOSTATUS=CONVERT(VARCHAR(50),'RECONCILED')
FROM ACCOUNT.DBO.LEDGER A WITH (NOLOCK) 
WHERE VDT BETWEEN @TODATE - 15 AND @TODATE + ' 23:59' AND DRCR='D' AND VTYP='2'

INSERT INTO RECOMISII
SELECT EXCHNAGE='BSECM',CLTCODE,VAMT,DRCR,VTYP,VNO,BOOKTYPE,VDT,EDT,CDT,
RELDATE = (SELECT MAX(reldt) FROM ANAND.ACCOUNT_AB.DBO.LEDGER1 B WITH (NOLOCK) WHERE A.VNO = B.vno AND A.VTYP = B.vtyp),
DDNO = (SELECT MAX(DDNO) FROM ANAND.ACCOUNT_AB.DBO.LEDGER1 B WITH (NOLOCK) WHERE A.VNO = B.vno AND A.VTYP = B.vtyp),NARRATION,ENTEREDBY,
ACTYPE=CONVERT(VARCHAR(150),''),RECOSTATUS=CONVERT(VARCHAR(50),'RECONCILED') 
FROM ANAND.ACCOUNT_AB.DBO.LEDGER A WITH (NOLOCK) 
WHERE VDT BETWEEN @TODATE - 15 AND @TODATE + ' 23:59' AND DRCR='D' AND VTYP='2'


INSERT INTO RECOMISII
SELECT EXCHNAGE='NSEFO',CLTCODE,VAMT,DRCR,VTYP,VNO,BOOKTYPE,VDT,EDT,CDT,
RELDATE = (SELECT MAX(reldt) FROM ANGELFO.ACCOUNTFO.DBO.LEDGER1 B WITH (NOLOCK) WHERE A.VNO = B.vno AND A.VTYP = B.vtyp),
DDNO = (SELECT MAX(DDNO) FROM ANGELFO.ACCOUNTFO.DBO.LEDGER1 B WITH (NOLOCK) WHERE A.VNO = B.vno AND A.VTYP = B.vtyp),NARRATION,ENTEREDBY,
ACTYPE=CONVERT(VARCHAR(150),''),RECOSTATUS=CONVERT(VARCHAR(50),'RECONCILED') 
FROM ANGELFO.ACCOUNTFO.DBO.LEDGER A WITH (NOLOCK) 
WHERE VDT BETWEEN @TODATE - 15 AND @TODATE + ' 23:59' AND DRCR='D' AND VTYP='2'


INSERT INTO RECOMISII
SELECT EXCHNAGE='NSECD',CLTCODE,VAMT,DRCR,VTYP,VNO,BOOKTYPE,VDT,EDT,CDT,
RELDATE = (SELECT MAX(reldt) FROM ANGELFO.ACCOUNTCURFO.DBO.LEDGER1 B WITH (NOLOCK) WHERE A.VNO = B.vno AND A.VTYP = B.vtyp),
DDNO = (SELECT MAX(DDNO) FROM ANGELFO.ACCOUNTCURFO.DBO.LEDGER1 B WITH (NOLOCK) WHERE A.VNO = B.vno AND A.VTYP = B.vtyp),NARRATION,ENTEREDBY,
ACTYPE=CONVERT(VARCHAR(150),''),RECOSTATUS=CONVERT(VARCHAR(50),'RECONCILED') 
FROM ANGELFO.ACCOUNTCURFO.DBO.LEDGER A WITH (NOLOCK) 
WHERE VDT BETWEEN @TODATE - 15 AND @TODATE + ' 23:59' AND DRCR='D' AND VTYP='2'


INSERT INTO RECOMISII
SELECT EXCHNAGE='MCXCD',CLTCODE,VAMT,DRCR,VTYP,VNO,BOOKTYPE,VDT,EDT,CDT,
RELDATE = (SELECT MAX(reldt) FROM ANGELCOMMODITY.ACCOUNTMCDXCDS.DBO.LEDGER1 B WITH (NOLOCK) WHERE A.VNO = B.vno AND A.VTYP = B.vtyp),
DDNO = (SELECT MAX(DDNO) FROM ANGELCOMMODITY.ACCOUNTMCDXCDS.DBO.LEDGER1 B WITH (NOLOCK) WHERE A.VNO = B.vno AND A.VTYP = B.vtyp),NARRATION,ENTEREDBY,
ACTYPE=CONVERT(VARCHAR(150),''),RECOSTATUS=CONVERT(VARCHAR(50),'RECONCILED') 
FROM ANGELCOMMODITY.ACCOUNTMCDXCDS.DBO.LEDGER A WITH (NOLOCK) 
WHERE VDT BETWEEN @TODATE - 15 AND @TODATE + ' 23:59' AND DRCR='D' AND VTYP='2'

INSERT INTO RECOMISII
SELECT EXCHNAGE='MCDX',CLTCODE,VAMT,DRCR,VTYP,VNO,BOOKTYPE,VDT,EDT,CDT,
RELDATE = (SELECT MAX(reldt) FROM ANGELCOMMODITY.ACCOUNTMCDX.DBO.LEDGER1 B WITH (NOLOCK) WHERE A.VNO = B.vno AND A.VTYP = B.vtyp),
DDNO = (SELECT MAX(DDNO) FROM ANGELCOMMODITY.ACCOUNTMCDX.DBO.LEDGER1 B WITH (NOLOCK) WHERE A.VNO = B.vno AND A.VTYP = B.vtyp),NARRATION,ENTEREDBY,
ACTYPE=CONVERT(VARCHAR(150),''),RECOSTATUS=CONVERT(VARCHAR(50),'RECONCILED') 
FROM ANGELCOMMODITY.ACCOUNTMCDX.DBO.LEDGER A WITH (NOLOCK) 
WHERE VDT BETWEEN @TODATE - 15 AND @TODATE + ' 23:59' AND DRCR='D' AND VTYP='2'


INSERT INTO RECOMISII
SELECT EXCHNAGE='NCDX',CLTCODE,VAMT,DRCR,VTYP,VNO,BOOKTYPE,VDT,EDT,CDT,
RELDATE = (SELECT MAX(reldt) FROM ANGELCOMMODITY.ACCOUNTNCDX.DBO.LEDGER1 B WITH (NOLOCK) WHERE A.VNO = B.vno AND A.VTYP = B.vtyp),
DDNO = (SELECT MAX(DDNO) FROM ANGELCOMMODITY.ACCOUNTNCDX.DBO.LEDGER1 B WITH (NOLOCK) WHERE A.VNO = B.vno AND A.VTYP = B.vtyp),NARRATION,ENTEREDBY,
ACTYPE=CONVERT(VARCHAR(150),''),RECOSTATUS=CONVERT(VARCHAR(50),'RECONCILED') 
FROM ANGELCOMMODITY.ACCOUNTNCDX.DBO.LEDGER A WITH (NOLOCK) 
WHERE VDT BETWEEN @TODATE - 15 AND @TODATE + ' 23:59' AND DRCR='D' AND VTYP='2'


INSERT INTO RECOMISII
SELECT EXCHNAGE='BSEFO',CLTCODE,VAMT,DRCR,VTYP,VNO,BOOKTYPE,VDT,EDT,CDT,
RELDATE = (SELECT MAX(reldt) FROM ANGELCOMMODITY.ACCOUNTBFO.DBO.LEDGER1 B WITH (NOLOCK) WHERE A.VNO = B.vno AND A.VTYP = B.vtyp),
DDNO = (SELECT MAX(DDNO) FROM ANGELCOMMODITY.ACCOUNTBFO.DBO.LEDGER1 B WITH (NOLOCK) WHERE A.VNO = B.vno AND A.VTYP = B.vtyp),NARRATION,ENTEREDBY,
ACTYPE=CONVERT(VARCHAR(150),''),RECOSTATUS=CONVERT(VARCHAR(50),'RECONCILED') 
FROM ANGELCOMMODITY.ACCOUNTBFO.DBO.LEDGER A WITH (NOLOCK) 
WHERE VDT BETWEEN @TODATE - 15 AND @TODATE + ' 23:59' AND DRCR='D' AND VTYP='2'


INSERT INTO RECOMISII
SELECT EXCHNAGE='BSECD',CLTCODE,VAMT,DRCR,VTYP,VNO,BOOKTYPE,VDT,EDT,CDT,
RELDATE = (SELECT MAX(reldt) FROM ANGELCOMMODITY.ACCOUNTCURBFO.DBO.LEDGER1 B WITH (NOLOCK) WHERE A.VNO = B.vno AND A.VTYP = B.vtyp),
DDNO = (SELECT MAX(DDNO) FROM ANGELCOMMODITY.ACCOUNTCURBFO.DBO.LEDGER1 B WITH (NOLOCK) WHERE A.VNO = B.vno AND A.VTYP = B.vtyp),NARRATION,ENTEREDBY,
ACTYPE=CONVERT(VARCHAR(150),''),RECOSTATUS=CONVERT(VARCHAR(50),'RECONCILED') 
FROM ANGELCOMMODITY.ACCOUNTCURBFO.DBO.LEDGER A WITH (NOLOCK) 
WHERE VDT BETWEEN @TODATE - 15 AND @TODATE + ' 23:59' AND DRCR='D' AND VTYP='2'

INSERT INTO RECOMISII
SELECT EXCHANGE='BSEMF',B.OPP_BANK,B.CRAMOUNT,DRCR='D',A.VTYPE,A.VNO,A.BOOKTYPE,VDT=CONVERT(DATETIME,CONVERT(VARCHAR(11),A.VDT)),B.EDT,
CDT=A.POSTED_ON,RELDATE=C.CR_RELDT,DDNO=C.INSTNO,B.NARRATION,A.POSTED_BY,ACTYPE=CONVERT(VARCHAR(150),''),RECOSTATUS=CONVERT(VARCHAR(50),'RECONCILED')
FROM ANGELFO.BBO_FA.DBO.ACC_TBL1 A (NOLOCK),ANGELFO.BBO_FA.DBO.ACC_TBL3 B (NOLOCK) , ANGELFO.BBO_FA.DBO.ACC_TBL4 C (NOLOCK)
WHERE A.SNO = B.MASTERSNO AND B.MASTERSNO = C.MASTERSNO AND VTYPE='2' 
AND CONVERT(DATETIME,CONVERT(VARCHAR(11),VDT)) BETWEEN @TODATE - 15 AND @TODATE + ' 23:59' 


UPDATE RECOMISII SET RECOSTATUS ='UNRECONCILED' WHERE RELDATE='1900-01-01 00:00:00.000'

UPDATE RECOMISII SET ACTYPE = BANKACTYPE FROM RECOMISII A , ACCOUNT.DBO.BANK_MASTER_TYPE B 
WHERE A.CLTCODE = B.BANKCODE AND A.EXCHNAGE = B.EXCHANGE

TRUNCATE TABLE BANKSOURCE

INSERT INTO BANKSOURCE
SELECT *,BANKSOURCE=CONVERT(VARCHAR(50),'BILLDESK') FROM RECOMISII WHERE VTYP=2 AND RECOSTATUS='UNRECONCILED' AND NARRATION='AMOUNT RECEIVED' 
UNION ALL
SELECT *,BANKSOURCE=CONVERT(VARCHAR(50),'BILLDESK') FROM RECOMISII WHERE VTYP=2 AND RECOSTATUS='UNRECONCILED' AND NARRATION LIKE '%VIRTUAL%'

UPDATE BANKSOURCE SET BANKSOURCE='VIRTUAL' WHERE CLTCODE='2093'
UPDATE BANKSOURCE SET BANKSOURCE='DIRECT' WHERE CLTCODE IN ('05016','02086','03026','04040','04007')
UPDATE BANKSOURCE SET BANKSOURCE='DIRECT' WHERE CLTCODE='02020' AND DDNO LIKE '21%'
--UPDATE BANKSOURCE SET BANKSOURCE='HDFCUPI' WHERE CLTCODE='02020' AND DDNO LIKE '11%'
UPDATE BANKSOURCE SET BANKSOURCE='HDFCUPI' WHERE CLTCODE='02020' AND DDNO LIKE '12%'
UPDATE BANKSOURCE SET BANKSOURCE='ATOM' WHERE CLTCODE='04007' AND DDNO LIKE '11000%' AND LEN(DDNO)=14
UPDATE BANKSOURCE SET BANKSOURCE='HDFCUPI' WHERE CLTCODE='04007' AND DDNO LIKE '11%' AND LEN(DDNO)=12
UPDATE BANKSOURCE SET BANKSOURCE='DIRECT' WHERE CLTCODE='03014' AND LEN(DDNO)='10' AND DDNO LIKE '011%'
UPDATE BANKSOURCE SET BANKSOURCE='DIRECT' WHERE CLTCODE='03014' AND LEN(DDNO)='10' AND DDNO LIKE '016%'
UPDATE BANKSOURCE SET BANKSOURCE='ATOM' WHERE CLTCODE='03014' AND DDNO LIKE '11000%'
UPDATE BANKSOURCE SET BANKSOURCE='TECHPROCESS' WHERE CLTCODE='03014' AND LEN(DDNO)='10' AND DDNO LIKE '15%'
UPDATE BANKSOURCE SET BANKSOURCE='RAZORPAY' WHERE CLTCODE='03014' AND DDNO LIKE 'PAY%'

SELECT EXCHNAGE='EXCHNAGE',CLTCODE='CLTCODE',VAMT='VAMT',DRCR='DRCR',VTYP='VTYP',VNO='VNO',
BOOKTYPE='BOOKTYPE',VDT='VDT',EDT='EDT',CDT='CDT',RELDATE='RELDATE',DDNO='DDNO',NARRATION='NARRATION',
ENTEREDBY='ENTEREDBY',ACTYPE='ACTYPE',RECOSTATUS='RECOSTATUS',BANKSOURCE='BANKSOURCE'
UNION ALL
SELECT EXCHNAGE,CLTCODE,VAMT=CONVERT(VARCHAR,VAMT),DRCR,VTYP=CONVERT(VARCHAR,VTYP),VNO=CONVERT(VARCHAR,VNO),
BOOKTYPE=CONVERT(VARCHAR,BOOKTYPE),VDT=CONVERT(VARCHAR(11),VDT,105),EDT=CONVERT(VARCHAR(11),EDT,105),CDT=CONVERT(VARCHAR,CDT),
RELDATE=CONVERT(VARCHAR,RELDATE),DDNO,NARRATION,ENTEREDBY,ACTYPE,RECOSTATUS,BANKSOURCE
FROM BANKSOURCE

GO
