-- Object: PROCEDURE dbo.CLS_BANKRECO_REPORT
-- Server: 10.253.33.91 | DB: ACCOUNT
--------------------------------------------------



CREATE PROCEDURE [dbo].[CLS_BANKRECO_REPORT]

@CODE VARCHAR(10),                     
@TDATE  varchar(11)

AS

BEGIN
SELECT @TDATE=CONVERT(VARCHAR(11),CONVERT (DATETIME,@TDATE,103),109)
SELECT
	CLTCODE
	,BOOKDATE
	,DESCRIPTION = REPLACE([DESCRIPTION], '', '')
	,AMOUNT
	,DRCR
	,VALUEDATE
	,REFERENCENO
	,STATUSID
	,STATUSNAME
	,LOGINNAME
	,CROSSREFERENCENO
	,STATUS
	,BOOKDATE1 = CONVERT(VARCHAR(10), BOOKDATE, 103)
FROM BANKRECO
WHERE CLTCODE = @CODE
AND STATUS = 'UNMATCHED'
AND BOOKDATE <= @TDATE UNION SELECT
	CLTCODE
	,BOOKDATE
	,DESCRIPTION = REPLACE([DESCRIPTION], '', '')
	,AMOUNT
	,DRCR
	,VALUEDATE
	,REFERENCENO
	,STATUSID
	,STATUSNAME
	,LOGINNAME
	,CROSSREFERENCENO
	,STATUS
	,BOOKDATE1 = CONVERT(VARCHAR(10), BOOKDATE, 103)
FROM BANKRECO
WHERE CLTCODE = @CODE
AND BOOKDATE <= @TDATE
AND VALUEDATE > @TDATE
AND VALUEDATE <= ''
AND STATUS = 'MATCHED' UNION SELECT
	CLTCODE
	,BOOKDATE
	,DESCRIPTION = REPLACE([DESCRIPTION], '', '')
	,AMOUNT
	,CASE
		WHEN DRCR = 'D' THEN 'C'
		ELSE 'D'
	END
	,VALUEDATE
	,REFERENCENO
	,STATUSID
	,STATUSNAME
	,LOGINNAME
	,CROSSREFERENCENO
	,STATUS
	,BOOKDATE1 = CONVERT(VARCHAR(10), BOOKDATE, 103)
FROM BANKRECO
WHERE CLTCODE = @CODE
AND BOOKDATE > @TDATE
AND VALUEDATE <= @TDATE
AND VALUEDATE <> ''
ORDER BY DRCR, BOOKDATE

END

GO
