-- Object: VIEW dbo.TRXN_DETAILS
-- Server: 10.253.33.190 | DB: inhouse
--------------------------------------------------

CREATE VIEW TRXN_DETAILS    
AS    
/*    
SELECT TD_CURDATE, TD_AC_CODE, TD_ISIN_CODE, TD_QTY, TD_CLEAR_CORPN, TD_COUNTERDP, TD_BENEFICIERY,    
TD_REFERENCE, TD_DESCRIPTION, TD_CATEGORY, TD_AC_TYPE, TD_NARRATION, TD_BOOKING_TYPE, TD_MARKET_TYPE,    
TD_SETTLEMENT, TD_BLOCKED, TD_BLOCKEDCD, TD_RDATE, TD_TRXDATE, TD_TRXTIME, TD_DEBIT_CREDIT, TD_TRXNO,    
TD_CHARGE_CODE, TD_RATE, TD_AMOUNT, TD_INTERNAL_REFNO, TD_COUNTERCMBPID, TD_TOTCERT, TD_CHARGEFLAG,    
T.MKRID, T.MKRDT, TD_REJCODE, TD_BILLCODE, TD_CDSLCHARGE, TD_PDCD, TD_PDCODE, TD_REMARKS, TD_ACTUALCDSLCHARGE,    
CM_BLSAVINGCD = ISNULL(C.CM_BLSAVINGCD, '')    
FROM SYNERGY_TRXN_DETAILS T WITH (NOLOCK), SYNERGY_CLIENT_MASTER C WITH (NOLOCK)    
WHERE T.TD_AC_CODE = C.CM_CD    
*/    
/*    
SELECT T.*    
FROM SYNERGY_TRXN_DETAILS T WITH (NOLOCK), SYNERGY_CLIENT_MASTER C WITH (NOLOCK)    
WHERE T.TD_AC_CODE = C.CM_CD    
*/    
SELECT TD_CURDATE = ISNULL(TD_CURDATE, ''), TD_AC_CODE = ISNULL(TD_AC_CODE, ''), TD_ISIN_CODE = ISNULL(TD_ISIN_CODE, ''), TD_QTY = ISNULL(TD_QTY, 0),    
TD_CLEAR_CORPN = ISNULL(TD_CLEAR_CORPN, ''), TD_COUNTERDP = ISNULL(TD_COUNTERDP, ''), TD_BENEFICIERY = ISNULL(TD_BENEFICIERY, ''), TD_REFERENCE = ISNULL(TD_REFERENCE, ''),    
TD_DESCRIPTION = ISNULL(TD_DESCRIPTION, ''), TD_CATEGORY = ISNULL(TD_CATEGORY, ''), TD_AC_TYPE = ISNULL(TD_AC_TYPE, ''), TD_NARRATION = ISNULL(TD_NARRATION, ''),    
TD_BOOKING_TYPE = ISNULL(TD_BOOKING_TYPE, ''), TD_MARKET_TYPE = ISNULL(TD_MARKET_TYPE, ''), TD_SETTLEMENT = ISNULL(TD_SETTLEMENT, ''),    
TD_BLOCKED = ISNULL(TD_BLOCKED, ''), TD_BLOCKEDCD = ISNULL(TD_BLOCKEDCD, ''), TD_RDATE = ISNULL(TD_RDATE, ''), TD_TRXDATE = ISNULL(TD_TRXDATE, ''),    
TD_TRXTIME = ISNULL(TD_TRXTIME, ''), TD_DEBIT_CREDIT = ISNULL(TD_DEBIT_CREDIT, ''), TD_TRXNO = ISNULL(TD_TRXNO, ''), TD_CHARGE_CODE = ISNULL(TD_CHARGE_CODE, ''),    
TD_RATE = ISNULL(TD_RATE, 0), TD_AMOUNT = ISNULL(TD_AMOUNT, 0), TD_INTERNAL_REFNO = ISNULL(TD_INTERNAL_REFNO, ''), TD_COUNTERCMBPID = ISNULL(TD_COUNTERCMBPID, ''),    
TD_TOTCERT, TD_CHARGEFLAG = ISNULL(TD_CHARGEFLAG, ''), MKRID = ISNULL(T.MKRID, ''), MKRDT = ISNULL(T.MKRDT, ''), TD_REJCODE = ISNULL(TD_REJCODE, ''),    
TD_BILLCODE = ISNULL(TD_BILLCODE, ''), TD_CDSLCHARGE = ISNULL(TD_CDSLCHARGE, 0), TD_PDCD = ISNULL(TD_PDCD, ''), TD_PDCODE = ISNULL(TD_PDCODE, ''),    
TD_REMARKS = ISNULL(TD_REMARKS, ''), TD_ACTUALCDSLCHARGE = ISNULL(TD_ACTUALCDSLCHARGE, 0), CM_BLSAVINGCD = ISNULL(C.CM_BLSAVINGCD, '')    
FROM SYNERGY_TRXN_DETAILS T WITH (NOLOCK), SYNERGY_CLIENT_MASTER C WITH (NOLOCK)    
WHERE T.TD_AC_CODE = C.CM_CD

GO
