-- Object: PROCEDURE dbo.USP_BROK_DETAIL_REPORT
-- Server: 10.253.33.91 | DB: scratchpad
--------------------------------------------------


---|| DESCRIPTION :- BROK DETAILS REPORT KYC TEAM (NILESH PAWAR)
---|| CREATED BY :- HRISHI Y
---|| CREATED DATE :- 03-NOV-2024

CREATE PROC [dbo].[USP_BROK_DETAIL_REPORT]

AS

DECLARE @SQL VARCHAR (MAX) ,@SQL2 VARCHAR (MAX), @SQLFINAL VARCHAR (MAX) , @PATH VARCHAR (MAX)
SET @PATH='J:\Backoffice\SL_AUTO\NILESH_P\BROK_DATA\INPUT\INPUT.txt'

IF OBJECT_ID(N'tempdb..#INPUT_DATA') IS NOT NULL
DROP TABLE #INPUT_DATA
CREATE TABLE #INPUT_DATA (CODE VARCHAR (100))

SET @SQL='BULK INSERT #INPUT_DATA FROM ' + ''''+ @PATH +''''
SET @SQL2=' WITH
(                                          
       FIRSTROW = 1,                                          
       FIELDTERMINATOR = '','',  --CSV FIELD DELIMITER                                          
       ROWTERMINATOR = ''\n'',   --USE TO SHIFT THE CONTROL TO NEXT ROW                                          
       TABLOCK                                          
)'

SET @SQLFINAL= @SQL + @SQL2          
PRINT @SQLFINAL          
EXEC (@SQLFINAL)          

--SELECT TOP 10 * FROM #INPUT_DATA

--DECLARE @TDATE DATETIME = 'SEP  2 2024'

IF OBJECT_ID(N'TEMPDB..#CHECKBROK') IS NOT NULL
DROP TABLE #CHECKBROK

SELECT CL_CODE,EXCH = EXCHANGE+SEGMENT,BROK_SCHEME,TRD_BROK,DEL_BROK,CASH_VBB_TRD='00',CASH_VBB_DEL='00',                
Fut_Opt_Brok,                
Fut_Fut_Fin_Brok,                
Fut_Opt_Exc,                
Fut_Brok_Applicable                ,
OPT_VBB_TRD='00',OPT_VBB_DEL='00',BTB_BTC = ''         
INTO #CHECKBROK                
FROM MSAJAG.DBO.CLIENT_BROK_DETAILS C WITH (NOLOCK)  INNER JOIN #INPUT_DATA I ON C.CL_CODE=I.CODE

CREATE INDEX CLIIDX ON #CHECKBROK (CL_CODE,EXCH)                

DELETE FROM #CHECKBROK WHERE EXCH IN ('BSXFUTURES','MCDFUTURES','NSESLBS')

UPDATE #CHECKBROK SET CASH_VBB_TRD = SP_SCHEME_ID FROM                
MSAJAG.DBO.SCHEME_MAPPING WITH (NOLOCK) WHERE SP_PARTY_CODE = CL_CODE AND EXCH = 'NSECAPITAL'                  
AND GETDATE () BETWEEN SP_DATE_FROM AND SP_DATE_TO AND SP_TRD_TYPE= 'TRD'        AND SP_SCRIP = 'ALL'          
                
UPDATE #CHECKBROK SET CASH_VBB_DEL = SP_SCHEME_ID FROM                
MSAJAG.DBO.SCHEME_MAPPING WITH (NOLOCK) WHERE SP_PARTY_CODE = CL_CODE AND EXCH = 'NSECAPITAL'                  
AND GETDATE () BETWEEN SP_DATE_FROM AND SP_DATE_TO AND SP_TRD_TYPE= 'DEL'           AND SP_SCRIP = 'ALL'       
                
UPDATE #CHECKBROK SET CASH_VBB_TRD = SP_SCHEME_ID FROM                
ANAND.BSEDB_AB.DBO.SCHEME_MAPPING WITH (NOLOCK) WHERE SP_PARTY_CODE = CL_CODE AND EXCH = 'BSECAPITAL'                 
AND GETDATE () BETWEEN SP_DATE_FROM AND SP_DATE_TO  AND SP_TRD_TYPE= 'TRD'         AND SP_SCRIP = 'ALL'         
                
UPDATE #CHECKBROK SET CASH_VBB_DEL = SP_SCHEME_ID FROM                
ANAND.BSEDB_AB.DBO.SCHEME_MAPPING WITH (NOLOCK) WHERE SP_PARTY_CODE = CL_CODE AND EXCH = 'BSECAPITAL'                  
AND GETDATE () BETWEEN SP_DATE_FROM AND SP_DATE_TO AND SP_TRD_TYPE= 'DEL'           AND SP_SCRIP = 'ALL'       
                
UPDATE #CHECKBROK SET OPT_VBB_TRD = SP_SCHEME_ID FROM                
ANGELFO.NSEFO.DBO.SCHEME_MAPPING WITH (NOLOCK) WHERE SP_PARTY_CODE = CL_CODE AND EXCH = 'NSEFUTURES'                 
AND GETDATE () BETWEEN SP_DATE_FROM AND SP_DATE_TO                
AND SP_INST_TYPE = 'OPT'                
AND SP_TRD_TYPE= 'TRD'        AND SP_SCRIP = 'ALL'           
                
UPDATE #CHECKBROK SET OPT_VBB_DEL = SP_SCHEME_ID FROM                
ANGELFO.NSEFO.DBO.SCHEME_MAPPING WITH (NOLOCK) WHERE SP_PARTY_CODE = CL_CODE   AND EXCH = 'NSEFUTURES'                 
AND GETDATE () BETWEEN SP_DATE_FROM AND SP_DATE_TO                
AND SP_INST_TYPE = 'OPT'                
AND SP_TRD_TYPE= 'DEL'        AND SP_SCRIP = 'ALL'           
                
UPDATE #CHECKBROK SET OPT_VBB_TRD = SP_SCHEME_ID FROM                
ANGELFO.NSECURFO.DBO.SCHEME_MAPPING WITH (NOLOCK) WHERE SP_PARTY_CODE = CL_CODE  AND EXCH = 'NSXFUTURES'                 
AND GETDATE () BETWEEN SP_DATE_FROM AND SP_DATE_TO                
AND SP_INST_TYPE = 'OPT'                
AND SP_TRD_TYPE= 'TRD'        AND SP_SCRIP = 'ALL'           
                
UPDATE #CHECKBROK SET OPT_VBB_DEL = SP_SCHEME_ID FROM                
ANGELFO.NSECURFO.DBO.SCHEME_MAPPING WITH (NOLOCK) WHERE SP_PARTY_CODE = CL_CODE  AND EXCH = 'NSXFUTURES'                
AND GETDATE () BETWEEN SP_DATE_FROM AND SP_DATE_TO                
AND SP_INST_TYPE = 'OPT'                
AND SP_TRD_TYPE= 'DEL'           AND SP_SCRIP = 'ALL'       
                
                
UPDATE #CHECKBROK SET OPT_VBB_TRD = SP_SCHEME_ID FROM                
ANGELCOMMODITY.NCDX.DBO.SCHEME_MAPPING WITH (NOLOCK) WHERE SP_PARTY_CODE = CL_CODE  AND EXCH = 'NCXFUTURES'                  
AND GETDATE () BETWEEN SP_DATE_FROM AND SP_DATE_TO                
AND SP_INST_TYPE = 'OPT'                
AND SP_TRD_TYPE= 'TRD'       AND SP_SCRIP = 'ALL'         
                
UPDATE #CHECKBROK SET OPT_VBB_DEL = SP_SCHEME_ID FROM                
ANGELCOMMODITY.NCDX.DBO.SCHEME_MAPPING WITH (NOLOCK) WHERE SP_PARTY_CODE = CL_CODE  AND EXCH = 'NCXFUTURES'                  
AND GETDATE () BETWEEN SP_DATE_FROM AND SP_DATE_TO                
AND SP_INST_TYPE = 'OPT'              AND SP_TRD_TYPE= 'DEL'       AND SP_SCRIP = 'ALL'            
                
                
UPDATE #CHECKBROK SET OPT_VBB_TRD = SP_SCHEME_ID FROM                
ANGELCOMMODITY.MCDX.DBO.SCHEME_MAPPING WITH (NOLOCK) WHERE SP_PARTY_CODE = CL_CODE  AND EXCH = 'MCXFUTURES'                
AND GETDATE () BETWEEN SP_DATE_FROM AND SP_DATE_TO                 
AND SP_INST_TYPE = 'OPT'                
AND SP_TRD_TYPE= 'TRD'           AND SP_SCRIP = 'ALL'       
                
UPDATE #CHECKBROK SET OPT_VBB_DEL = SP_SCHEME_ID FROM                
ANGELCOMMODITY.MCDX.DBO.SCHEME_MAPPING WITH (NOLOCK) WHERE SP_PARTY_CODE = CL_CODE AND EXCH = 'MCXFUTURES'                  
AND GETDATE () BETWEEN SP_DATE_FROM AND SP_DATE_TO                 
AND SP_INST_TYPE = 'OPT'                
AND SP_TRD_TYPE= 'DEL'     AND SP_SCRIP = 'ALL'    


UPDATE #CHECKBROK SET OPT_VBB_TRD = SP_SCHEME_ID FROM                
ANGELCOMMODITY.BSEFO.DBO.SCHEME_MAPPING WITH (NOLOCK) WHERE SP_PARTY_CODE = CL_CODE  AND EXCH = 'BSEFUTURES'                
AND GETDATE () BETWEEN SP_DATE_FROM AND SP_DATE_TO                 
AND SP_Product_Type = 'OPT'                
AND SP_TRD_TYPE= 'TRD'           AND SP_Product_code = 'ALL'       

UPDATE #CHECKBROK SET OPT_VBB_DEL = SP_SCHEME_ID FROM                
ANGELCOMMODITY.BSEFO.DBO.SCHEME_MAPPING WITH (NOLOCK) WHERE SP_PARTY_CODE = CL_CODE AND EXCH = 'BSEFUTURES'                  
AND GETDATE () BETWEEN SP_DATE_FROM AND SP_DATE_TO                 
AND SP_Product_Type = 'OPT'                
AND SP_TRD_TYPE= 'DEL'     AND SP_Product_code = 'ALL'   

UPDATE #CHECKBROK SET OPT_VBB_TRD = SP_SCHEME_ID FROM                
ANGELCOMMODITY.NCE.DBO.SCHEME_MAPPING WITH (NOLOCK) WHERE SP_PARTY_CODE = CL_CODE  AND EXCH = 'NCEFUTURES'                
AND GETDATE () BETWEEN SP_DATE_FROM AND SP_DATE_TO                 
AND SP_INST_TYPE = 'OPT'                
AND SP_TRD_TYPE= 'TRD'           AND SP_SCRIP = 'ALL'       
                
UPDATE #CHECKBROK SET OPT_VBB_DEL = SP_SCHEME_ID FROM                
ANGELCOMMODITY.NCE.DBO.SCHEME_MAPPING WITH (NOLOCK) WHERE SP_PARTY_CODE = CL_CODE AND EXCH = 'NCEFUTURES'                  
AND GETDATE () BETWEEN SP_DATE_FROM AND SP_DATE_TO                 
AND SP_INST_TYPE = 'OPT'                
AND SP_TRD_TYPE= 'DEL'     AND SP_SCRIP = 'ALL'     

------->> 2ND FILE LOGIC

SELECT CL_CODE,MAX(ISNULL([BSECAPITAL_BROK_SCHEME],'')) AS [BSECAPITAL_BROK_SCHEME],
MAX(ISNULL([BSEFUTURES_BROK_SCHEME],'')) AS [BSEFUTURES_BROK_SCHEME],
MAX(ISNULL([MCXFUTURES_BROK_SCHEME],'')) AS [MCXFUTURES_BROK_SCHEME],
MAX(ISNULL([NCXFUTURES_BROK_SCHEME],'')) AS [NCXFUTURES_BROK_SCHEME],
MAX(ISNULL([NSECAPITAL_BROK_SCHEME],'')) AS [NSECAPITAL_BROK_SCHEME],
MAX(ISNULL([NSEFUTURES_BROK_SCHEME],'')) AS [NSEFUTURES_BROK_SCHEME],
MAX(ISNULL([NSXFUTURES_BROK_SCHEME],'')) AS [NSXFUTURES_BROK_SCHEME],
MAX(ISNULL([NCEFUTURES_BROK_SCHEME],'')) AS [NCEFUTURES_BROK_SCHEME],
MAX(ISNULL([BSECAPITAL_TRD_BROK],'')) AS [BSECAPITAL_TRD_BROK],
MAX(ISNULL([BSEFUTURES_TRD_BROK],'')) AS [BSEFUTURES_TRD_BROK],
MAX(ISNULL([MCXFUTURES_TRD_BROK],'')) AS [MCXFUTURES_TRD_BROK],
MAX(ISNULL([NCXFUTURES_TRD_BROK],'')) AS [NCXFUTURES_TRD_BROK],
MAX(ISNULL([NSECAPITAL_TRD_BROK],'')) AS [NSECAPITAL_TRD_BROK],
MAX(ISNULL([NSEFUTURES_TRD_BROK],'')) AS [NSEFUTURES_TRD_BROK],
MAX(ISNULL([NSXFUTURES_TRD_BROK],'')) AS [NSXFUTURES_TRD_BROK],
MAX(ISNULL([NCEFUTURES_TRD_BROK],'')) AS [NCEFUTURES_TRD_BROK],
MAX(ISNULL([BSECAPITAL_DEL_BROK],'')) AS [BSECAPITAL_DEL_BROK],
MAX(ISNULL([BSEFUTURES_DEL_BROK],'')) AS [BSEFUTURES_DEL_BROK],
MAX(ISNULL([MCXFUTURES_DEL_BROK],'')) AS [MCXFUTURES_DEL_BROK],
MAX(ISNULL([NCXFUTURES_DEL_BROK],'')) AS [NCXFUTURES_DEL_BROK],
MAX(ISNULL([NSECAPITAL_DEL_BROK],'')) AS [NSECAPITAL_DEL_BROK],
MAX(ISNULL([NSEFUTURES_DEL_BROK],'')) AS [NSEFUTURES_DEL_BROK],
MAX(ISNULL([NSXFUTURES_DEL_BROK],'')) AS [NSXFUTURES_DEL_BROK],
MAX(ISNULL([NCEFUTURES_DEL_BROK],'')) AS [NCEFUTURES_DEL_BROK],
MAX(ISNULL([BSECAPITAL_CASH_VBB_TRD],'')) AS [BSECAPITAL_CASH_VBB_TRD],
MAX(ISNULL([BSEFUTURES_CASH_VBB_TRD],'')) AS [BSEFUTURES_CASH_VBB_TRD],
MAX(ISNULL([MCXFUTURES_CASH_VBB_TRD],'')) AS [MCXFUTURES_CASH_VBB_TRD],
MAX(ISNULL([NCXFUTURES_CASH_VBB_TRD],'')) AS [NCXFUTURES_CASH_VBB_TRD],
MAX(ISNULL([NSECAPITAL_CASH_VBB_TRD],'')) AS [NSECAPITAL_CASH_VBB_TRD],
MAX(ISNULL([NSEFUTURES_CASH_VBB_TRD],'')) AS [NSEFUTURES_CASH_VBB_TRD],
MAX(ISNULL([NSXFUTURES_CASH_VBB_TRD],'')) AS [NSXFUTURES_CASH_VBB_TRD],
MAX(ISNULL([NCEFUTURES_CASH_VBB_TRD],'')) AS [NCEFUTURES_CASH_VBB_TRD],
MAX(ISNULL([BSECAPITAL_CASH_VBB_DEL],'')) AS [BSECAPITAL_CASH_VBB_DEL],
MAX(ISNULL([BSEFUTURES_CASH_VBB_DEL],'')) AS [BSEFUTURES_CASH_VBB_DEL],
MAX(ISNULL([MCXFUTURES_CASH_VBB_DEL],'')) AS [MCXFUTURES_CASH_VBB_DEL],
MAX(ISNULL([NCXFUTURES_CASH_VBB_DEL],'')) AS [NCXFUTURES_CASH_VBB_DEL],
MAX(ISNULL([NSECAPITAL_CASH_VBB_DEL],'')) AS [NSECAPITAL_CASH_VBB_DEL],
MAX(ISNULL([NSEFUTURES_CASH_VBB_DEL],'')) AS [NSEFUTURES_CASH_VBB_DEL],
MAX(ISNULL([NSXFUTURES_CASH_VBB_DEL],'')) AS [NSXFUTURES_CASH_VBB_DEL],
MAX(ISNULL([NCEFUTURES_CASH_VBB_DEL],'')) AS [NCEFUTURES_CASH_VBB_DEL],
MAX(ISNULL([BSECAPITAL_FUT_OPT_BROK],'')) AS [BSECAPITAL_FUT_OPT_BROK],
MAX(ISNULL([BSEFUTURES_FUT_OPT_BROK],'')) AS [BSEFUTURES_FUT_OPT_BROK],
MAX(ISNULL([MCXFUTURES_FUT_OPT_BROK],'')) AS [MCXFUTURES_FUT_OPT_BROK],
MAX(ISNULL([NCXFUTURES_FUT_OPT_BROK],'')) AS [NCXFUTURES_FUT_OPT_BROK],
MAX(ISNULL([NSECAPITAL_FUT_OPT_BROK],'')) AS [NSECAPITAL_FUT_OPT_BROK],
MAX(ISNULL([NSEFUTURES_FUT_OPT_BROK],'')) AS [NSEFUTURES_FUT_OPT_BROK],
MAX(ISNULL([NSXFUTURES_FUT_OPT_BROK],'')) AS [NSXFUTURES_FUT_OPT_BROK],
MAX(ISNULL([NCEFUTURES_FUT_OPT_BROK],'')) AS [NCEFUTURES_FUT_OPT_BROK],
MAX(ISNULL([BSECAPITAL_FUT_FUT_FIN_BROK],'')) AS [BSECAPITAL_FUT_FUT_FIN_BROK],
MAX(ISNULL([BSEFUTURES_FUT_FUT_FIN_BROK],'')) AS [BSEFUTURES_FUT_FUT_FIN_BROK],
MAX(ISNULL([MCXFUTURES_FUT_FUT_FIN_BROK],'')) AS [MCXFUTURES_FUT_FUT_FIN_BROK],
MAX(ISNULL([NCXFUTURES_FUT_FUT_FIN_BROK],'')) AS [NCXFUTURES_FUT_FUT_FIN_BROK],
MAX(ISNULL([NSECAPITAL_FUT_FUT_FIN_BROK],'')) AS [NSECAPITAL_FUT_FUT_FIN_BROK],
MAX(ISNULL([NSEFUTURES_FUT_FUT_FIN_BROK],'')) AS [NSEFUTURES_FUT_FUT_FIN_BROK],
MAX(ISNULL([NSXFUTURES_FUT_FUT_FIN_BROK],'')) AS [NSXFUTURES_FUT_FUT_FIN_BROK],
MAX(ISNULL([NCEFUTURES_FUT_FUT_FIN_BROK],'')) AS [NCEFUTURES_FUT_FUT_FIN_BROK],
MAX(ISNULL([BSECAPITAL_FUT_OPT_EXC],'')) AS [BSECAPITAL_FUT_OPT_EXC],
MAX(ISNULL([BSEFUTURES_FUT_OPT_EXC],'')) AS [BSEFUTURES_FUT_OPT_EXC],
MAX(ISNULL([MCXFUTURES_FUT_OPT_EXC],'')) AS [MCXFUTURES_FUT_OPT_EXC],
MAX(ISNULL([NCXFUTURES_FUT_OPT_EXC],'')) AS [NCXFUTURES_FUT_OPT_EXC],
MAX(ISNULL([NSECAPITAL_FUT_OPT_EXC],'')) AS [NSECAPITAL_FUT_OPT_EXC],
MAX(ISNULL([NSEFUTURES_FUT_OPT_EXC],'')) AS [NSEFUTURES_FUT_OPT_EXC],
MAX(ISNULL([NSXFUTURES_FUT_OPT_EXC],'')) AS [NSXFUTURES_FUT_OPT_EXC],
MAX(ISNULL([NCEFUTURES_FUT_OPT_EXC],'')) AS [NCEFUTURES_FUT_OPT_EXC],
MAX(ISNULL([BSECAPITAL_FUT_BROK_APPLICABLE],'')) AS [BSECAPITAL_FUT_BROK_APPLICABLE],
MAX(ISNULL([BSEFUTURES_FUT_BROK_APPLICABLE],'')) AS [BSEFUTURES_FUT_BROK_APPLICABLE],
MAX(ISNULL([MCXFUTURES_FUT_BROK_APPLICABLE],'')) AS [MCXFUTURES_FUT_BROK_APPLICABLE],
MAX(ISNULL([NCXFUTURES_FUT_BROK_APPLICABLE],'')) AS [NCXFUTURES_FUT_BROK_APPLICABLE],
MAX(ISNULL([NSECAPITAL_FUT_BROK_APPLICABLE],'')) AS [NSECAPITAL_FUT_BROK_APPLICABLE],
MAX(ISNULL([NSEFUTURES_FUT_BROK_APPLICABLE],'')) AS [NSEFUTURES_FUT_BROK_APPLICABLE],
MAX(ISNULL([NSXFUTURES_FUT_BROK_APPLICABLE],'')) AS [NSXFUTURES_FUT_BROK_APPLICABLE],
MAX(ISNULL([NCEFUTURES_FUT_BROK_APPLICABLE],'')) AS [NCEFUTURES_FUT_BROK_APPLICABLE],
MAX(ISNULL([BSECAPITAL_OPT_VBB_TRD],'')) AS [BSECAPITAL_OPT_VBB_TRD],
MAX(ISNULL([BSEFUTURES_OPT_VBB_TRD],'')) AS [BSEFUTURES_OPT_VBB_TRD],
MAX(ISNULL([MCXFUTURES_OPT_VBB_TRD],'')) AS [MCXFUTURES_OPT_VBB_TRD],
MAX(ISNULL([NCXFUTURES_OPT_VBB_TRD],'')) AS [NCXFUTURES_OPT_VBB_TRD],
MAX(ISNULL([NSECAPITAL_OPT_VBB_TRD],'')) AS [NSECAPITAL_OPT_VBB_TRD],
MAX(ISNULL([NSEFUTURES_OPT_VBB_TRD],'')) AS [NSEFUTURES_OPT_VBB_TRD],
MAX(ISNULL([NSXFUTURES_OPT_VBB_TRD],'')) AS [NSXFUTURES_OPT_VBB_TRD],
MAX(ISNULL([NCEFUTURES_OPT_VBB_TRD],'')) AS [NCEFUTURES_OPT_VBB_TRD],
MAX(ISNULL([BSECAPITAL_OPT_VBB_DEL],'')) AS [BSECAPITAL_OPT_VBB_DEL],
MAX(ISNULL([BSEFUTURES_OPT_VBB_DEL],'')) AS [BSEFUTURES_OPT_VBB_DEL],
MAX(ISNULL([MCXFUTURES_OPT_VBB_DEL],'')) AS [MCXFUTURES_OPT_VBB_DEL],
MAX(ISNULL([NCXFUTURES_OPT_VBB_DEL],'')) AS [NCXFUTURES_OPT_VBB_DEL],
MAX(ISNULL([NSECAPITAL_OPT_VBB_DEL],'')) AS [NSECAPITAL_OPT_VBB_DEL],
MAX(ISNULL([NSEFUTURES_OPT_VBB_DEL],'')) AS [NSEFUTURES_OPT_VBB_DEL],
MAX(ISNULL([NSXFUTURES_OPT_VBB_DEL],'')) AS [NSXFUTURES_OPT_VBB_DEL],
MAX(ISNULL([NCEFUTURES_OPT_VBB_DEL],'')) AS [NCEFUTURES_OPT_VBB_DEL] INTO #CHECKBROK1
FROM 
(SELECT CL_CODE,EXCH+'_'+'BROK_SCHEME' AS EXCH_BROK_SCHEME
,EXCH+'_'+'TRD_BROK' AS EXCH_TRD_BROK,EXCH+'_'+'DEL_BROK' AS EXCH_DEL_BROK,EXCH+'_'+'CASH_VBB_TRD' AS EXCH_CASH_VBB_TRD,
EXCH+'_'+'CASH_VBB_DEL' AS EXCH_CASH_VBB_DEL,
EXCH+'_'+'FUT_OPT_BROK' AS EXCH_FUT_OPT_BROK,
EXCH+'_'+'FUT_FUT_FIN_BROK' AS EXCH_FUT_FUT_FIN_BROK,
EXCH+'_'+'FUT_OPT_EXC' AS EXCH_FUT_OPT_EXC,
EXCH+'_'+'FUT_BROK_APPLICABLE' AS EXCH_FUT_BROK_APPLICABLE,
EXCH+'_'+'OPT_VBB_TRD' AS EXCH_OPT_VBB_TRD,
EXCH+'_'+'OPT_VBB_DEL' AS EXCH_OPT_VBB_DEL,
BROK_SCHEME,TRD_BROK,DEL_BROK,CASH_VBB_TRD,CASH_VBB_DEL,FUT_OPT_BROK,FUT_FUT_FIN_BROK,FUT_OPT_EXC,FUT_BROK_APPLICABLE,OPT_VBB_TRD,OPT_VBB_DEL FROM #CHECKBROK) AS SOUR
PIVOT
(MAX(BROK_SCHEME) FOR EXCH_BROK_SCHEME IN ([BSECAPITAL_BROK_SCHEME],[BSEFUTURES_BROK_SCHEME],[MCXFUTURES_BROK_SCHEME],[NCXFUTURES_BROK_SCHEME],
[NSECAPITAL_BROK_SCHEME],[NSEFUTURES_BROK_SCHEME],[NSXFUTURES_BROK_SCHEME],[NCEFUTURES_BROK_SCHEME])) AS PVT
PIVOT
(MAX(TRD_BROK) FOR EXCH_TRD_BROK IN ([BSECAPITAL_TRD_BROK],
[BSEFUTURES_TRD_BROK],
[MCXFUTURES_TRD_BROK],
[NCXFUTURES_TRD_BROK],
[NSECAPITAL_TRD_BROK],
[NSEFUTURES_TRD_BROK],
[NSXFUTURES_TRD_BROK],
[NCEFUTURES_TRD_BROK])) AS PVT2
PIVOT
(MAX(DEL_BROK) FOR EXCH_DEL_BROK IN ([BSECAPITAL_DEL_BROK],
[BSEFUTURES_DEL_BROK],
[MCXFUTURES_DEL_BROK],
[NCXFUTURES_DEL_BROK],
[NSECAPITAL_DEL_BROK],
[NSEFUTURES_DEL_BROK],
[NSXFUTURES_DEL_BROK],
[NCEFUTURES_DEL_BROK])) AS PVT3
PIVOT
(MAX(CASH_VBB_TRD) FOR EXCH_CASH_VBB_TRD IN ([BSECAPITAL_CASH_VBB_TRD],
[BSEFUTURES_CASH_VBB_TRD],
[MCXFUTURES_CASH_VBB_TRD],
[NCXFUTURES_CASH_VBB_TRD],
[NSECAPITAL_CASH_VBB_TRD],
[NSEFUTURES_CASH_VBB_TRD],
[NSXFUTURES_CASH_VBB_TRD],
[NCEFUTURES_CASH_VBB_TRD])) AS PVT4
PIVOT
(MAX(CASH_VBB_DEL) FOR EXCH_CASH_VBB_DEL IN ([BSECAPITAL_CASH_VBB_DEL],
[BSEFUTURES_CASH_VBB_DEL],
[MCXFUTURES_CASH_VBB_DEL],
[NCXFUTURES_CASH_VBB_DEL],
[NSECAPITAL_CASH_VBB_DEL],
[NSEFUTURES_CASH_VBB_DEL],
[NSXFUTURES_CASH_VBB_DEL],
[NCEFUTURES_CASH_VBB_DEL])) AS PVT5
PIVOT
(MAX(FUT_OPT_BROK) FOR EXCH_FUT_OPT_BROK IN ([BSECAPITAL_FUT_OPT_BROK],
[BSEFUTURES_FUT_OPT_BROK],
[MCXFUTURES_FUT_OPT_BROK],
[NCXFUTURES_FUT_OPT_BROK],
[NSECAPITAL_FUT_OPT_BROK],
[NSEFUTURES_FUT_OPT_BROK],
[NSXFUTURES_FUT_OPT_BROK],
[NCEFUTURES_FUT_OPT_BROK])) AS PVT6
PIVOT
(MAX(FUT_FUT_FIN_BROK) FOR EXCH_FUT_FUT_FIN_BROK IN ([BSECAPITAL_FUT_FUT_FIN_BROK],
[BSEFUTURES_FUT_FUT_FIN_BROK],
[MCXFUTURES_FUT_FUT_FIN_BROK],
[NCXFUTURES_FUT_FUT_FIN_BROK],
[NSECAPITAL_FUT_FUT_FIN_BROK],
[NSEFUTURES_FUT_FUT_FIN_BROK],
[NSXFUTURES_FUT_FUT_FIN_BROK],
[NCEFUTURES_FUT_FUT_FIN_BROK])) AS PVT7
PIVOT
(MAX(FUT_OPT_EXC) FOR EXCH_FUT_OPT_EXC IN ([BSECAPITAL_FUT_OPT_EXC],
[BSEFUTURES_FUT_OPT_EXC],
[MCXFUTURES_FUT_OPT_EXC],
[NCXFUTURES_FUT_OPT_EXC],
[NSECAPITAL_FUT_OPT_EXC],
[NSEFUTURES_FUT_OPT_EXC],
[NSXFUTURES_FUT_OPT_EXC],
[NCEFUTURES_FUT_OPT_EXC])) AS PVT8
PIVOT
(MAX(FUT_BROK_APPLICABLE) FOR EXCH_FUT_BROK_APPLICABLE IN ([BSECAPITAL_FUT_BROK_APPLICABLE],
[BSEFUTURES_FUT_BROK_APPLICABLE],
[MCXFUTURES_FUT_BROK_APPLICABLE],
[NCXFUTURES_FUT_BROK_APPLICABLE],
[NSECAPITAL_FUT_BROK_APPLICABLE],
[NSEFUTURES_FUT_BROK_APPLICABLE],
[NSXFUTURES_FUT_BROK_APPLICABLE],
[NCEFUTURES_FUT_BROK_APPLICABLE])) AS PVT9
PIVOT
(MAX(OPT_VBB_TRD) FOR EXCH_OPT_VBB_TRD IN ([BSECAPITAL_OPT_VBB_TRD],
[BSEFUTURES_OPT_VBB_TRD],
[MCXFUTURES_OPT_VBB_TRD],
[NCXFUTURES_OPT_VBB_TRD],
[NSECAPITAL_OPT_VBB_TRD],
[NSEFUTURES_OPT_VBB_TRD],
[NSXFUTURES_OPT_VBB_TRD],
[NCEFUTURES_OPT_VBB_TRD])) AS PVT10
PIVOT
(MAX(OPT_VBB_DEL) FOR EXCH_OPT_VBB_DEL IN ([BSECAPITAL_OPT_VBB_DEL],
[BSEFUTURES_OPT_VBB_DEL],
[MCXFUTURES_OPT_VBB_DEL],
[NCXFUTURES_OPT_VBB_DEL],
[NSECAPITAL_OPT_VBB_DEL],
[NSEFUTURES_OPT_VBB_DEL],
[NSXFUTURES_OPT_VBB_DEL],
[NCEFUTURES_OPT_VBB_DEL])) AS PVT11
GROUP BY CL_CODE


TRUNCATE TABLE SCRATCHPAD.DBO.TBL_BROK_DETAILS_DATA
TRUNCATE TABLE SCRATCHPAD.DBO.TBL_BROK_DETAILS_DATA_PIVOT

INSERT INTO SCRATCHPAD.DBO.TBL_BROK_DETAILS_DATA
SELECT CL_CODE,EXCH,CONVERT(VARCHAR (20),BROK_SCHEME) AS BROK_SCHEME, CONVERT(VARCHAR (20),TRD_BROK) AS TRD_BROK, CONVERT(VARCHAR (20),DEL_BROK) AS DEL_BROK, CASH_VBB_TRD, CASH_VBB_DEL,
CONVERT(VARCHAR (20),Fut_Opt_Brok) AS Fut_Opt_Brok, CONVERT(VARCHAR (20),Fut_Fut_Fin_Brok) AS Fut_Fut_Fin_Brok, CONVERT(VARCHAR (20),Fut_Opt_Exc) AS Fut_Opt_Exc, CONVERT(VARCHAR (20),Fut_Brok_Applicable) AS Fut_Brok_Applicable,
OPT_VBB_TRD, OPT_VBB_DEL, BTB_BTC
FROM #CHECKBROK

--INSERT INTO SCRATCHPAD.DBO.TBL_BROK_DETAILS_DATA_PIVOT
--SELECT CL_CODE, CAST (BSECAPITAL_BROK_SCHEME AS VARCHAR) AS BSECAPITAL_BROK_SCHEME, BSECAPITAL_CASH_VBB_DEL, BSECAPITAL_CASH_VBB_TRD, CAST (BSECAPITAL_DEL_BROK AS VARCHAR) AS BSECAPITAL_DEL_BROK,
--CAST (BSECAPITAL_FUT_BROK_APPLICABLE AS VARCHAR) AS BSECAPITAL_FUT_BROK_APPLICABLE, CAST (BSECAPITAL_FUT_FUT_FIN_BROK AS VARCHAR) AS BSECAPITAL_FUT_FUT_FIN_BROK, 
--CAST (BSECAPITAL_FUT_OPT_BROK AS VARCHAR) AS BSECAPITAL_FUT_OPT_BROK, CAST (BSECAPITAL_FUT_OPT_EXC AS VARCHAR) AS BSECAPITAL_FUT_OPT_EXC, BSECAPITAL_OPT_VBB_DEL, BSECAPITAL_OPT_VBB_TRD,
--CAST (BSECAPITAL_TRD_BROK AS VARCHAR) AS BSECAPITAL_TRD_BROK, CAST (BSEFUTURES_BROK_SCHEME AS VARCHAR) AS BSEFUTURES_BROK_SCHEME, BSEFUTURES_CASH_VBB_DEL, BSEFUTURES_CASH_VBB_TRD,
--CAST (BSEFUTURES_DEL_BROK AS VARCHAR) AS BSEFUTURES_DEL_BROK, CAST (BSEFUTURES_FUT_BROK_APPLICABLE AS VARCHAR) AS BSEFUTURES_FUT_BROK_APPLICABLE, CAST (BSEFUTURES_FUT_FUT_FIN_BROK AS VARCHAR) AS BSEFUTURES_FUT_FUT_FIN_BROK,
--CAST (BSEFUTURES_FUT_OPT_BROK AS VARCHAR) AS BSEFUTURES_FUT_OPT_BROK, CAST (BSEFUTURES_FUT_OPT_EXC AS VARCHAR) AS BSEFUTURES_FUT_OPT_EXC,

--FROM #CHECKBROK1

---------------------- || FILE GENERATION LOGIC || ----------------------

--DECLARE @RPT_DATE VARCHAR(30)=REPLACE(CONVERT(VARCHAR(10),GETDATE(),3),'/','')          
DECLARE @FILENAME VARCHAR(100) = 'J:\Backoffice\SL_AUTO\NILESH_P\BROK_DATA\OUTPUT\' +'BROK_DETAIL_REPORT' + '.CSV'          
DECLARE @ALL VARCHAR(MAX)                    
                    
SET @ALL = 'EXEC MASTER.DBO.XP_CMDSHELL ''BCP "SELECT ''''CL_CODE'''',	''''EXCH'''',	''''BROK_SCHEME'''',	''''TRD_BROK'''',	''''DEL_BROK'''',	''''CASH_VBB_TRD'''',	''''CASH_VBB_DEL'''',	''''Fut_Opt_Brok'''',	''''Fut_Fut_Fin_Brok'''',	''''Fut_Opt_Exc'''',	''''Fut_Brok_Applicable'''',	''''OPT_VBB_TRD'''',	''''OPT_VBB_DEL'''',	''''BTB_BTC'''''                    
SET @ALL = @ALL+ ' UNION ALL SELECT * FROM SCRATCHPAD.DBO.TBL_BROK_DETAILS_DATA'                  
PRINT @ALL                    
SET @ALL=@ALL+' " QUERYOUT ' +@FILENAME+ ' -c -t"," -c -t"," -r"\n" -T'', NO_OUTPUT'                    
PRINT @ALL                    
EXEC(@ALL)                    

---------------------- || FILE GENERATION LOGIC || ----------------------
                
SELECT 'BROK DETAILS REPORT DATA FILE EXPORTED TO \\10.253.33.91\' + @FILENAME AS 'REMARK'

GO
